### PR TITLE
Removes unused dogborg file

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Why does this exist

## Why It's Good For The Game

It shouldn't exist

## Changelog
:cl:
del: Removed unused dog borg code
/:cl:

### CODE REVIEW

**Comment by Sinestia** [comment]
This leaves the borgi in through the borging panel, right?

Looks so on a quick find-in-files

Hope that stays because it's a niche smite/gimmick for borg players

**Comment by Effemu** [comment]
>smite/gimmick for borg players

no...

**Comment by eeSPee** [comment]
Dogborg has no icons or associated sounds.

**Comment by ItsTisme** [comment]
Iam genuinly supprised we even had this in the first place

**Comment by OceanFish1** [comment]
> Iam genuinly supprised we even had this in the first place

Probably had it because furries :trollface:

**Comment by ItsTisme** [comment]
> > Iam genuinly supprised we even had this in the first place
> 
> Probably had it because furries :trollface:

the last commit that changed it was the great line ending PR. So its ancient as fuck

EDIT: found the commit, not even the PR

https://github.com/BeeStation/BeeStation-Hornet/commit/fe6aa709ea409b4fe9b7f8719788397b0662effa

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
delete the dogborg sleeper as well at least

**Comment by ivanmixo** [comment]
Uh I don't think the sleeper exists

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Why are you removing borgi?

**Review by PowerfulBacon — APPROVED** [review]

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Wait you need to remove the .dme reference too

**Review by PowerfulBacon — APPROVED** [review]
actually apparently this file isn't even referenced in the dme

**Comment by ItsTisme** [comment]
icons/robots.dmi still has the borgi bot icon just FYI

**Pull request merged**
