### PR TITLE
Cap slaughter & laughter demons to 1 each 

### PR DESCRIPTION
**Pull request by Sinestia**
## About The Pull Request

3 -> 1

remember 2 touch wiki

## Why It's Good For The Game

one last nerf to this meta w/o outright deleting them
you can spend at most 3 points now. spawning several is excessively dangerous to an early crew (you cant even shove them) and on top of that is a repetitive way to play 

## Changelog
:cl:froststahr
balance: wizard demons have been capped to one each
/:cl:

### CODE REVIEW

**Comment by ZombiesVsPlants** [comment]
I cannot tell if this is a meme pr or not

**Comment by ghost** [comment]
nice meme PR

**Comment by DatBoiTim** [comment]
Nah I legitimately like this. Demon wizard is boring to watch and unfun to fight.

**Comment by Sinestia** [comment]
> I cannot tell if this is a meme pr or not

Nah, this comes up basically half the time there's a wiz (more if we don't count wizzes who die instantly) so I thought I'd just submit another nerf to see if people wanted it

**Comment by ZombiesVsPlants** [comment]
>you cant even shove them
this is funny af not gonna lie

**Comment by ghost** [comment]
you could robust them pretty easily with shotguns and throwing plants/toolboxes at them and running away

**Comment by MNarath1** [comment]
> Nah I legitimately like this. Demon wizard is boring to watch and unfun to fight.

there are no demon wizards on bee anymore cause someone else already made and successfully merged a PR to make sure wizards cannot mindswap with demons

**Comment by Sinestia** [comment]
>there are no demon wizards on bee anymore cause someone else already made and successfully merged a PR to make sure wizards cannot mindswap with demons 

That's not true at all

**Comment by MNarath1** [comment]
> >there are no demon wizards on bee anymore cause someone else already made and successfully merged a PR to make sure wizards cannot mindswap with demons 
> 
> 
> 
> That's not true at all

https://github.com/BeeStation/BeeStation-Hornet/pull/2983
Take a look for yourself if you do not believe me.

**Comment by Sinestia** [comment]
> > > there are no demon wizards on bee anymore cause someone else already made and successfully merged a PR to make sure wizards cannot mindswap with demons
> > 
> > 
> > That's not true at all
> 
> #2983
> Take a look for yourself if you do not believe me.

bruh i was responding to him saying that there's no demon wizards anymore

**Review by utilbird — APPROVED** [review]
I'm tired of having to spawn paranormal ERT every time 2 or more appear.

**Comment by hotimep** [comment]
i will still spawn in a clown and slaughter demon and you will still cry and shake in your boots

**Comment by utilbird** [comment]
image

**Pull request merged**
