### PR TITLE
Adds buildable and plantable landmines, smartmines and the exploding rubber duck traitor item

### PR DESCRIPTION
**Pull request by WhyIsCaeciliusTaken**
## About The Pull Request
Iterates upon the existing code for landmines away missions use. Previously, landmines only existed in the admin game panel as well as pre-planted in away missions. This PR allows for landmines to be planted by players, and sets down framework to make it easy to add new plantable landmines. Of the currrently 
existing mines only stun, clown and explosive mines are plantable, but the others can be easily added if desired. Additionally, three new mines have been added, all of which are plantable, and stun and clown mines can both be build in protolathe, requiring the basic sec tech and clown tech research nodes respectively.

The new mines are:
Smart Stun Mines: Available after advanced weapons technology, smart stun mines do not trigger if their activator has a mindshield implant.
Exploding Rubber Duck: Available from the traitor uplink for 3TC. These look exactly like rubber ducks but cause a small explosion when stepped on.
High Yield Exploding Rubber Duck: A more powerful, 9TC version of the regular exploding rubber duck.

Mines can detonate adjacent mines with their activation sparks. Throwing items onto any  mine will detonate them. Mines cannot be defused or moved once placed.

## Why It's Good For The Game
Mines provide interesting options for area denial by both sec (with smartmines) and the rest of the crew (With regular mines). Mines are balanced by the fact that they cannot be hidden under piles of random stuff because placing an object onto their tile triggers them.

Clown mines provide a cheap, completely harmless prank item for clowns to build when  there is no bananium.

Exploding rubber ducks are a funny traitor item that will be balanced once people get used to the idea of their existence. Plus people being terrified of a random rubber duck in the halls is hilarious.

## Changelog
:cl:
add: Some landmines can now be carried about and placed.
add: Added smartmines, which do not trigger when activated by mindshielded people.
add: Stun, Smart Stun and clown mines can be built in techfabs, requiring Sec, Adv Weapon and Clown tech respectively.
add: Exploding rubber duck traitor item. 3TC, explodes when walked on.
add: High Yield 9TC version of the exploding rubber duck.
tweak: Stun mines do stamina damage instead of hardstuns.
tweak: Clown mines are louder
admin: Mine planting is logged in attack logs.
/:cl:

### CODE REVIEW

**Comment by WhyIsCaeciliusTaken** [comment]
Why is this still trying to merge those commits?

**Comment by Isy232** [comment]
Chem mines would be nice.

**Comment by WhyIsCaeciliusTaken** [comment]
> Chem mines would be nice.

Chem mines would involve rewriting quite a lot of mine code at best and a complete mine code rewrite at worst.  Just use proximity sensors.

**Comment by WhyIsCaeciliusTaken** [comment]
Closing so I can fix the commits crap and fix it.

**Pull request closed without merging**
