### PR TITLE
Literally 1984 - Removes the centralized ore silo, adds department ore silos

### PR DESCRIPTION
**Pull request by JixS4v**
## About The Pull Request
Reworks the way mats are managed in the game.

## Why It's Good For The Game

Moar cargo work, cargo is more important to the station as a whole (control over materials). I'd expand on this but it's just a draft for now. Better reasons outlined by Ruko in his PR (9722). This is a bit of a different approach to removal.

### To-Do List

Minimum viable product:
Removes the centralized ore silo in its entirety
- [x] Mapping changes

Replaces the ore silo with a per-department ore silo system (manual delivery by cargo)
- [x] Mapping changes
- [x] Code changes

Material Deposit Machine in every department, acts as a depositing interface (locked to cargo access so cargo can pull mats OUT of your techfab too)
- [x] Mapping changes
- [x] Code changes
- [x] Spriting changes (credit to JikkaJoestar)

Make silo logs work with multiple silos (not really needed for an initial water testing TM):
- [ ] Code changes
- [ ] UI changes

Stretch goals (not needed for TM):
- [ ] Improved mulebot system which actually works for mat delivery
- [ ] QM console for mat management (would just be done through fax and paperwork otherwise)
- [ ] Material management console that can request specific mat orders per-department instaead of using paper/comms
- [ ] Striped overlays for dept ore silos

Changed maps:
- [x] Meta
- [x] Delta
- [x] Box
- [x] Rad
- [x] Kilo
- [x] Fland
- [x] Corg

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://youtu.be/6P-AyhQuo74

</details>

## Changelog
:cl: JixS4v, JikkaJoestar, Ratón
del: Removes the centralized Ore Silo
add: Adds per-department Ore Silos which are supplied with mats by cargo
add: Adds a new machine: The Material Deposit Machine, which lets cargo technicians deposit materials into a department's silo without having to get let in
/:cl:

### CODE REVIEW

**Comment by JixS4v** [comment]
Local idiot forgets to take out low memory mode

**Comment by tontyGH** [comment]
image

**Comment by ClownMoff** [comment]
Not funny lil bro deactivate this PR

**Comment by JixS4v** [comment]
Local idiot commits low memory mode again, pledges to fix when PR gets marked for review

**Comment by PowerfulBacon** [comment]
Why is this written as an ore silo removal when it adds more ore silos into the game?

Departmental ore silos is a good idea and allows cargo to actually manage the resources of given departments and prevents 1 role from consuming literally all the mats. If this works out maybe in the future we can add material requests that people can apply for from cargo so that they can get extra resources to create a big thing, or maybe trading departmental funds for resources.

**Comment by JixS4v** [comment]
> Why is this written as an ore silo removal when it adds more ore silos into the game?
> 
> Departmental ore silos is a good idea and allows cargo to actually manage the resources of given departments and prevents 1 role from consuming literally all the mats. If this works out maybe in the future we can add material requests that people can apply for from cargo so that they can get extra resources to create a big thing, or maybe trading departmental funds for resources.

It's a compromise to the ore silo removal as it makes cargo deliver mats while not having the tedium of refilling every single individual machine. It does remove the central ore silo so that's why I tagged it as such, but I can change the name to something more descriptive.

**Comment by JixS4v** [comment]
Also those are ideas I tried to outline in the stretch goals, after the main stuff in the PR is added. The departmental funds idea is good and sounds like a good use of departmental funds

**Comment by JixS4v** [comment]
Alright I shall mark this for review since the bit needed for a testmerge is done (bacon said it could be a bit dodgy since we want feedback on this as soon as possible)

**Comment by Rukofamicom** [comment]
Needs testing evidence before it can be considered for testmerge

**Comment by JixS4v** [comment]
> Needs testing evidence before it can be considered for testmerge

I shall record some evidence then.

**Comment by JixS4v** [comment]
> Needs testing evidence before it can be considered for testmerge

Updated PR with testing evidence, commit 1984 rn

**Review by PestoVerde322 — APPROVED** [review]
map and iconwise are good to go, may need overhaul on the deposit machines later.

**Comment by Rukofamicom** [comment]
Actually gonna slap this label on too, because this is really something we should all discuss and more or less agree upon before merging

**Review by ike709 — APPROVED** [review]
I like the idea. Didn't have time to review the code.

**Comment by francinum** [comment]
This is a half-measure that is *slightly* better than the current state of things, but only really puppeteers the idea it's supposed to be serving.

Magic department ID locks on the material storage components is incredibly arbitrary and only serves as a monkey wrench to prevent people from going back to the Old Ways via their own hand. This isn't great ergonomically.

Deposit machines miss the point of delivery in the first place and turn it into actual busywork that misses the entire point of hand-delivery in the first place: <ins>player interaction</ins>

It's not my cart, but this doesn't actually fix anything. ~~And matter bin upgrades are still worthless~~

**Comment by francinum** [comment]
also on a more objective note you appear to have (accidentally) removed all the animation frames from
`icons/obj/machines/mining_machines.dmi:ore_redemption` in 88eb804bb77f22b54f2e322326bdd3eec4bc6d45

**Comment by JixS4v** [comment]
> This is a half-measure that is _slightly_ better than the current state of things, but only really puppeteers the idea it's supposed to be serving.
> Magic department ID locks on the material storage components is incredibly arbitrary and only serves as a monkey wrench to prevent people from going back to the Old Ways via their own hand. This isn't great ergonomically.
I have thought about this myself quite a lot. The issue is that there really isn't any way to actually lock the silos to the departments. It would make perfect sense for NT to split up the station's mats into different departments and to only make the containers compatible with their respective department's machines, like with protolathes which are split up into different categories, so I honestly see this as a fair solution and the best one we got.

> Deposit machines miss the point of delivery in the first place and turn it into actual busywork that misses the entire point of hand-delivery in the first place: player interaction
I don't believe cargo having to get into the department will make the interactions any more meaningful. If anything, they'll just ship them through disposals and let the department insert the mats into the lathe. Cargo having to manually go around the station delivering mats and allocating different amounts, with a console that lets them reallocate mats on the go is, in my opinion, a big upside of the PR. 

> It's not my cart, but this doesn't actually fix anything aside from having seven boxes to steal from instead of one. ~And matter bin upgrades are still worthless...~
I do believe this is still an upside, but for the reasons I outlined above, I think cargo does benefit from added work that makes them more important to the station at all times. I do think that more player interactions will be derived from the mat requests and conflict from resource scarcity than before though.

**Comment by JixS4v** [comment]
> also on a more objective note you appear to have (accidentally) removed all the animation frames from `icons/obj/machines/mining_machines.dmi:ore_redemption` in [88eb804](https://github.com/BeeStation/BeeStation-Hornet/commit/88eb804bb77f22b54f2e322326bdd3eec4bc6d45)

lemme see if i can fix that, that sounds like it's broken

**Comment by PowerfulBacon** [comment]
We did mention the points you bring up on discord. Abritrary locking is a poor solution and inelegant but is acceptable for a testmerge since the thing I really want to actually see is the effect of the delivering of the materials. On discord I mentioned that delivering materials doesn't really have a whole lot of choice or interactions to it, it is more for cargo to do but there are no decisions, risks or rewards that are made when delivering materials to departments apart from "does this department need this?" which I think will lead to the tasks being quite menial, resulting in players getting bored of delivering materials pretty fast.

My prediction was that at the start of rounds, cargo will deliver some materials to departments as they come in but will quickly stop delivering and will rely on people to come and get their own materials, either by asking at the cargo front desk, or by just dumping a pile of materials on a table for people to grab, however I am not entirely sure how this will play out at the moment and could be entirely wrong on everything.

Currently the way that I am weighing it up in my head is:
Benefits:
- Pirates and swarmers can't destroy the station by simply destroying the silo and making everyone unable to figure out how to use resources for themselves.
- Cargo technicians are forced to leave their department.

Drawbacks:
- The new job task added is pretty menial and has little choice involved
- There is no need to interact with the people delivering the materials outside of asking for resources: Getting different resources delivered doesn't give you certain advantages or disadvantages, it is just simply always better to have all the resources. On top of this, delivery is entirely automated through the ORMs. If all of the ORMs were inside of cargo, the only thing that would change is that cargo technicians wouldn't be forced to leave their department. No interactions, meaningful or meaningless, are lost or gained by making this optimisation outside of generic interactions you get from simply being outside the department.

**Comment by JixS4v** [comment]
> We did mention the points you bring up on discord. Abritrary locking is a poor solution and is inelegant, but is acceptable for a testmerge since the thing I really want to actually see is the effect of the delivering of the materials. 

I still think arbitrary locking (which already happens with other machines like protolathes for department-specific items) is the best solution to have the machines be linked to their respective departments. It also makes sense in the way I could very well see any company compartmentalizing their resources on a department basis with arbitrary restrictions put in place for security. The two other ways I thought of were making it so silos have a distance limit and limiting the amount of machines connected which all come with different drawbacks I adressed on the discord.

>On discord I mentioned that delivering materials doesn't really have a whole lot of choice or interactions to it, it is more for cargo to do but there are no decisions, risks or rewards that are made when delivering materials to departments apart from "does this department need this?" which I think will lead to the tasks being quite menial, resulting in players getting bored of delivering materials pretty fast.

Delivering materials is as menial as upgrading stuff, yet scientists still do it because it's their job. Ideally, cargo staff that doesn't perform deliveries would be charged under dereliction since their duty is very important to the function of the station. On top of that, I think the ability for mat supplies to be sabotaged by stealing a crate of a mulebot in the hallways or from a cargo tech still adds ways for antagonists to mess with departments that could lead to fun situations. 

> My prediction was that at the start of rounds, cargo will deliver some materials to departments as they come in but will quickly stop delivering and will rely on people to come and get their own materials, either by asking at the cargo front desk, or by just dumping a pile of materials on a table for people to grab, however I am not entirely sure how this will play out at the moment and could be entirely wrong on everything.

I won't respond to this since it's just a prediction and it hasn't been testmerged yet

> Currently the way that I am weighing it up in my head is: Benefits:
> 
>     * Pirates and swarmers can't destroy the station by simply destroying the silo and making everyone unable to figure out how to use resources for themselves.
>
>     * Cargo technicians are forced to leave their department.
> 
> 
> Drawbacks:
> 
>     * The new job task added is pretty menial and has little choice involved

This is true, I think Haliris is working on a way to make cargo deliveries less of a pain. The cratewrapping PR was also a good start in my opinion.

> 
>     * There is no need to interact with the people delivering the materials outside of asking for resources: 
>Getting different resources delivered doesn't give you certain advantages or disadvantages, it is just simply always better to have all the resources. 

This isn't true. For instance, robotics will eat through the whole station's mat supply if they decide to start making mechs. Having this be managed by cargo instead allows them to decide if the mech is important enough to have the resources for robotics be allocated to science.

> On top of this, delivery is entirely automated through the ORMs. If all of the ORMs were inside of cargo, the only thing that would change is that cargo technicians wouldn't be forced to leave their department. No interactions, meaningful or meaningless, are lost or gained by making this optimisation outside of generic interactions you get from simply being outside the department.

I outlined the reasons I think manual delivery will lead to more interactions, generally getting out of your department is also good since it lets you get involved with the current happenings of the station.

**Comment by JixS4v** [comment]
15 day bump 🥺

**Comment by Admiral-Gigaton** [comment]
heeeelll naaah man this shit is gunna give players an aneurism and cause a massive revolt in players, similar to how everyone on TG had a conniption over funky crate sprites. god i hope this isnt merged, sorry to you coder, but my mans, this is not how you reinforce RP between departments. its ss14 all over again.

**Comment by JixS4v** [comment]
> edit: i apologize for my previous statement, i forgot the "adds departmental ore silos" part. still, not the best idea, but whats stopping them from manually making a centralized ore silo?

The silos are locked to machines from one department and you can't print the multidepartment ones unless golems give it to you or something.

**Comment by Admiral-Gigaton** [comment]
> > edit: i apologize for my previous statement, i forgot the "adds departmental ore silos" part. still, not the best idea, but whats stopping them from manually making a centralized ore silo?
> 
> The silos are locked to machines from one department and you can't print the multidepartment ones unless golems give it to you or something.

whats stopping me from slapping every single ore silo in the middle of cargo, and hooking up non-departmental machines (circuit imprinters... uhhh i cant think of anything else for this) to one silo, like the engie silo?

**Comment by JixS4v** [comment]
> > > edit: i apologize for my previous statement, i forgot the "adds departmental ore silos" part. still, not the best idea, but whats stopping them from manually making a centralized ore silo?
> > 
> > 
> > The silos are locked to machines from one department and you can't print the multidepartment ones unless golems give it to you or something.
> 
> whats stopping me from slapping every single ore silo in the middle of cargo, and hooking up non-departmental machines (circuit imprinters... uhhh i cant think of anything else for this) to one silo, like the engie silo?

nothing but time and effort, but you'll need to get into every head's office and take the silo out, and you'll be much more susceptible to pirates/swarmers attacking cargo

**Comment by JixS4v** [comment]
Drafting since I need to remap some stuff and I got no time

**Comment by JixS4v** [comment]
Good night my sweet prince.... May we reunite again some day, when I have time

**Comment by Rukofamicom** [comment]
:cry:

**Pull request closed without merging**
