### PR TITLE
Delta fixes

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
just a few fixes / upgrades for delta station
The plant is removed (it was merged at the same time supply consoles were added)
Imgur img
The ORM is moved slightly left. Originally, my plan was to have it acting as a wall, but it turns out that it will only accept ore from the north. Rather than confuse miners, I just put it back and put a new arrow on it.
Imgur img
I adjusted the reflectors in the SM room so they don't require as much setup, just alignment. No other map requires this, and frankly it's annoying, it does not contribute to any type of gameplay other than requiring additional time.
Imgur img
The heater has been switched to a freezer. Although it's easier now to change them -  no one is legitimately using a heater on the cooling loop. It's not even a great sabotage. It's just an annoyance.
Imgur img
Swapped the two vents for one dual port vent. These were not working, last I checked, but who knows, there's no reason not to swap them to the superior dual port vent anyways.
Imgur img

## Why It's Good For The Game
fixes

## Changelog
:cl:
tweak: Delta station has a number of extraneous and overlapping plants removed.
tweak: Delta station SM is now marginally easier to set up.
tweak: Delta station ORM is now moved slightly left.
tweak: Delta station southern engi room now properly uses dual port vents.

/:cl:

### CODE REVIEW

**Comment by jlsnow301** [comment]
Really not sure how commits from my revs changes got in here

**Comment by PowerfulBacon** [comment]
There is space under a window in cargo too

**Comment by jlsnow301** [comment]
> There is space under a window in cargo too

Will resolve later today

**Comment by jlsnow301** [comment]
Okay. Space tile is resolved. I need to stop myself any time I get into the map editor, as I tend to get carried away. If there's too much here, I can revert it.

- fixed the cargo missing tile- removed a box overlapping another supply console in medbay, again, this is another merge artefact
- removed some unused wiring in maints that should have been removed during random maints PR
- Moved some of the equipment in medbay sleepers area so that there is light in the bottom left corner and the space suits (you didn't even know they were there huh) are now more reachable

reverted:
- ~~replaced a couple other vents (the ones between airlocks) with dual port vents, tested them individually~~
- ~~removed some plants, changed some others to randomized~~
- ~~some maintenance APCs removed. most of these were removed prior, only some in forgotten places remained. i can reimplement them if you're fond of maintenance APCs, but they're random grief bait to me~~

**Comment by PowerfulBacon** [comment]
APCs are required in all areas including maints.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
APCs must be in all areas including maints, removing an APC from the area will do weird things; either make the area unpowered entirely or make it have infinite power.

**Comment by jlsnow301** [comment]
> APCs must be in all areas including maints, removing an APC from the area will do weird things; either make the area unpowered entirely or make it have infinite power.

I reimplemented all the ones I had deleted. Note: There are still a lot of maints without apcs

**Comment by utilbird** [comment]
I personally don't like having the reflectors setup in an almost completely ideal way roundstart, only requiring a few simple angle changes to have it working perfectly. Engineering doesn't have a whole lot to do as is

**Comment by jlsnow301** [comment]
> I personally don't like having the reflectors setup in an almost completely ideal way roundstart, only requiring a few simple angle changes to have it working perfectly. Engineering doesn't have a whole lot to do as is

my philosophy behind this is that it was neither fun nor conducive of creative configurations - which are primarly in atmospheric combinations. and every map but delta has a streamlined configuration ready

**Pull request closed without merging**
