### PR TITLE
[PORT] Joy mask but acutally funny

### PR DESCRIPTION
**Pull request by PestoVerde322**
## About The Pull Request

_This is a port of https://github.com/tgstation/tgstation/pull/67583_

This Pr ads 4 new emojis to the joy mask, you can switch the emoji with a system similar to the Tiki or mime mask.
The "joy mask" has been renamed to "emotion mask".

The new emotes are: Pensive, Flushed, Angry and Pleading.

Credits to Twaticus, Wallemations and 13spaceman for the code and spritework.

## Why It's Good For The Game

The joy mask is one of the best things in the autodrobe, more choice and now you can use internals aswell, making it viable for fun gimmicks.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

immagine

</details>

## Changelog
:cl:
add: 4 new emojis added to the joy mask! Check the AutoDrobe
/:cl:

### CODE REVIEW

**Comment by Pirill** [comment]
Amazing, I was just thinking about this mask the other day.

**Comment by DerpiestBruh** [comment]
This isn't a Lisa reference, close this PR immediately!!!

**Comment by PestoVerde322** [comment]
> This isn't a Lisa reference, close this PR immediately!!!

You could always sprite, code and PR it, what's stopping you after all?

**Comment by Crossedfall** [comment]
> And you can also use internals with it now.

How does a paper mask held to your head with some loose string create an airtight seal around your face?

**Comment by PestoVerde322** [comment]
> > And you can also use internals with it now.
> 
> How does a paper mask held to your head with some loose string create an airtight seal around your face?

Not a clue, removed the internals support.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by ItsTisme** [comment]
worried about flushed, other then that looks very nice

**Pull request merged**
