### PR TITLE
Borgi smite and nerfs for two braindead easyclap chems

### PR DESCRIPTION
**Pull request by Toxici11i**
## About The Pull Request
Chemical changes -
-----------------------
Reduces the time taken for haloperidol and chloral hydrate to filter out of peoples systems, along with adding an overdose limit for haloperidol (3 braindamage/second up to a maximum of 80, toxin, seizurse).

Borgo
---------------------
Adds a new admin only borg. Borgi!(meant for smites, has no modules.)

## Why It's Good For The Game

Stops mediborgs from abusing the fact they can inject you with 1000u of haloperidol, knocking you into stamina crit/sleep for 9 thousand years. Also nerfs chloral hydrate by increasing its metabolism rate from 1.5 to 2.0 to help counteract its lethality and ability to be easily made.

Makes players not want to kill themselves when a medibot runs up to them, injects them with 60+U of haloperidol and they cant complain because it "isnt human harm". Overdose limits should be implemented for most chems and there will be another PR dedicated to balancing stun/poison chemicals.
Borgi is mostly for admeme fun and we need a way to punish ERPers or griffers using a borg

## Changelog
:cl:
add: Added Borgini from citadel code as an admeme smite.
balanced: balanced haloperidol and chloral hydrate
/:cl:

### CODE REVIEW

**Comment by catmanpop** [comment]
Remind me to smite myself once I have internet back, data dont count

**Comment by qwertyquerty** [comment]
Why are these in the same PR

**Comment by catmanpop** [comment]
Both are pretty good if you ask me

**Comment by Toxici11i** [comment]
I dont know why i merged them into the same PR, probably because it was just easier. Borgi is admeme only and doesnt conflict (tested) with beecode and the chems by themselves are a small balance change. If you want, i can split this PR into two.

**Comment by Toxici11i** [comment]
Also, by what i mean by smite is that its a unpickable borg module with no items, meaning the only way to get set to it is like being turned into a clownbot by admemery - the borg console. Mostly designed for people being annoying/breaking laws as borgo or just memes

tbh i dont know where the smite code is, otherwise i would just add a verb for it/edit the current smite verb.

**Comment by qwertyquerty** [comment]
Please make 2 prs.

**Pull request closed without merging**
