### PR TITLE
Revamped, animated with sounds and additional emotes

### PR DESCRIPTION
**Pull request by Chirynnn**
## About The Pull Request
This is a project I've been working on non-stop for maybe 8-9 hours, 10 total.
This PR does the following things:
- **Changes the emote text colors from gray to a nice blue, as it's much more aesthetically pleasing in my opinion**
- **Emotes added/improved with sounds**:
Cough - 3 female and male variants
Dwoop - Silicon and IPC only
Gasp - 6 female and male variants
Mothsqueak(msqueak) - Moth and mothroach only
Moth laugh soound
Mothchitter(chitter) - Moth and mothroach only
Sigh - One female and male variants
Snap2(snap2) - Snaps twice
Snap3(snap3) - Snaps thrice
Sneeze - female and male variant
Sniff - female and male variant

- **Emotes added without sounds**:
blep
clear - "Clears their throat"
etwitch - "Twitches their ears"
eyeroll - "Rolls their eyes"
huff - "lets out a huff!"
headtilt - "Tilts their head"

- **ANIMATED emotes added with sounds**:
sweatdrop
glasses (must have any glasses on the eye slot)
question
exclaim
annoyed
sigh
realize

Credits where it's due for the awesome animated emotes and sounds: https://github.com/Skyrat-SS13/Skyrat-tg/pull/6259
And credits to Skyrat as well for inspiring me to add all those emotes
https://github.com/shiptest-ss13/Shiptest/pull/972 for the moff death sound

## Why It's Good For The Game
Right now, I feel like emotes are not used nearly enough, besides the basic ones which are *laugh, *spin or *flip, the unholy trinity. This PR aims to give players an incentive to use the new ones, as well as making them look prettier with the blue text rather than the ugly gray from before.  

## Testing Photographs and Procedure

<details>

https://user-images.githubusercontent.com/77589317/188939147-7d6255e4-a76e-4e74-87a5-f37b8f9b6958.mp4

</details>

## Changelog
:cl:
add: Added the following emotes: (With sounds) gasp, cough, sigh, sneeze, sniff, dwoop, msqueak, chitter, snap2, snap3, blep; (Without sounds) blep, clear, etwitch, eyeroll, huff, headtilt; (ANIMATED with sounds) sweatdrop, glasses, question, exclaim, annoyed, sigh, realize
tweak: Changed the emoji text color to blue, as opposed to gray
soundadd: Added sounds for the emotes: cough, dwoop, gasp, msqueak, moth laugh, chitter, sigh, snap2, snap3, sneeze, sniff, sweatdrop, question, exclaim, annoyed and realize
imageadd: Added animations for the emotes: sweatdrop, realize, glasses, question, exclaim, sigh and annoyed
code: Added a var for emote cooldown, but didn't get around to using it
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
missing *nya
👎

**Comment by PowerfulBacon** [comment]
I don't like the inconsistency with the colour change from the emote overhead chat message and the way it looks like command chat, but it looks alright and neither looks better than the other imo.

**Comment by PowerfulBacon** [comment]
Sweatdrop shouldn't repeat like 3 times, since the noise is way too short for the animation.

image
This looks like a paintbrush, I assume its meant to be exclamation?
When the animation starts, rather than animating in, it appears for a frame and then starts animating. Haven't looked at the code, but if it uses flick() or changes icon state, use an icon state with an animation repeat count set to 1 instead.

image
These look good, but they need an outline.

I have no idea what the stars represent, I guess its meant to be like being knocked unconcious? Not super clear

image
I could not tell you what this means. Looks like a floating blue liver

**Comment by Chirynnn** [comment]
> I don't like the inconsistency with the colour change from the emote overhead chat message and the way it looks like command chat, but it looks alright and neither looks better than the other imo.

I looked for hours and only found the line for overhead, I can't find the command chat one whatsoever.

> I have no idea what the stars represent, I guess its meant to be like being knocked unconcious? Not super clear
It's the realize emote, pretty straightforward I guess.

>I could not tell you what this means. Looks like a floating blue liver
I guess so, it's the annoyed emote, it's supposed to symbolize gloom or something I don't know.

>When the animation starts, rather than animating in, it appears for a frame and then starts animating. Haven't looked at the code, but if it uses flick() or changes icon state, use an icon state with an animation repeat count set to 1 instead.
I noticed that too, but didn't really know how to fix it, this is maybe my third or fourth time coding that isn't completely copy paste.

>These look good, but they need an outline.
Is it.. really required? Would you rather them having a black outline?

**Comment by Fronsis** [comment]
Oh my god... is it here? after years of waiting a kind soul brought from SR the *chitters for Moths???? HALLELUJAH!!!!!

Though i do agree the  ( ! ) being twisted is a little strange..

Also in my personal opinion the size of some of them seems..a little big but that's just my taste, bah when i imagine it i picture it a little more smaller

Kie is gonna have a field day.

**Comment by Chirynnn** [comment]
Added funy deathgasp to moffs, thanks Milly for the idea

**Comment by kit-katz** [comment]
i think the ? and exclaim should have a smaller animation sprites they are a bit TO big compared to the rest
also exlaim should probably be a straight ! rather than the crooked variant you got there...
and lastly anoyed should probably be the red 💢... you know the one. this blue "liver" do be a bit strange compared to the rest
other than that this is amazing

**Comment by Chirynnn** [comment]
> i think the ? and exclaim should have a smaller animation sprites they are a bit TO big compared to the rest also exlaim should probably be a straight ! rather than the crooked variant you got there... and lastly anoyed should probably be the red 💢... you know the one. this blue "liver" do be a bit strange compared to the rest other than that this is amazing
I didn't make them sadly, so I have no clue on how to do what you and Bacon suggested

**Comment by PowerfulBacon** [comment]
My comment and lookthrough wasn't asking what they were, more indicating what I could tell without actually reading the text. If we are going to have visual emotes, it should be clear what they represent. My questions aren't there to be answered, they are there so that changes can be made so no questions need to be asked in the first place.

**Comment by Chirynnn** [comment]
I don't know how to do sprites, much less animate them, so I suppose I'll have to remove them until someone offers to make some sprites.

**Comment by Pirill** [comment]
I second the suggestion to add cat emotes. All of them.

**Comment by Chirynnn** [comment]
I'm closing this. I don't want to do this anymore as I cannot be bothered to code any more whatsoever. If anybody else wants to complete it then feel free, just read what Bacon wants changed in this PR.

**Pull request closed without merging**
