### PR TITLE
Coders now require admin approval to enable debug verbs

### PR DESCRIPTION
**Pull request by ike709**
## About The Pull Request

Maintainers no longer start with their permissions. Instead, they can request approval from an admin. It currently can't be revoked once granted. Don't make me change that.

Currently mulling creating a new rank for Super Trustworthy(TM) maintainers to bypass approval.

Not tested yet, and admin code is pretty cursed so DNM for now.

## Why It's Good For The Game

Debug permissions are for testing and debugging, not memes.

## Changelog
:cl:
admin: Maintainers no longer start with debug permissions. Instead, they can be requested from admins with the new Request Debug Permissions verb.
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Note to self: Rewrite this to just change their rank so the permissions can be defined in config.

**Comment by qwertyquerty** [comment]
🔑

**Comment by jupyterkat** [comment]
great job, elon :clap:

**Comment by Archanial** [comment]
Ided pr

**Comment by Archanial** [comment]
Grudge coding

**Comment by MCterra10** [comment]
are there really even enough maintainers for this to be a necessary system?

**Comment by LemonInTheDark** [comment]
lol what

**Comment by jupyterkat** [comment]
the state of bee, fellas

**Comment by ike709** [comment]
> are there really even enough maintainers for this to be a necessary system?

No but if we ever get more then giving them +DEBUG right out of the gate is probably a bad idea, based off of the abuse rate.

**Comment by utilbird** [comment]
despite consisting of less than a third of the active maintainers, elon makes up more than 99% of sdql calls.
image

My in game perms were removed, imo this is an unnecessary measure

**Comment by OceanFish1** [comment]
Literally 1984
Also
Maintaners trolled

**Comment by MCterra10** [comment]
>chess SDQL call

Could someone even be more based? 
Why do only admins get to do funny shit, this is a lame pr

**Comment by Sinestia** [comment]
> 
> 
> > chess SDQL call
> 
> Could someone even be more based?
> Why do only admins get to do funny shit, this is a lame pr

admins would get slapped for doing what he did lol 

Idk if this is super necessary though, this stuff is rare and there aren't many maintainers, they can probably handle warnings.

**Comment by MCterra10** [comment]
> 
> 
> > > chess SDQL call
> > 
> > 
> > Could someone even be more based?
> > Why do only admins get to do funny shit, this is a lame pr
> 
> admins would get slapped for doing what he did lol
> 
> Idk if this is super necessary though, this stuff is rare and there aren't many maintainers, they can probably handle warnings.

admins have sent the entire bee movie as a 50MB mp4 file to the chat before, I don't understand why all of a sudden elon sends a chess game to the chat and coder permissions have to be reworked
society 😔

**Comment by utilbird** [comment]
maintainers are an oppressed race

**Comment by ike709** [comment]
I don't have the energy to deal with this

**Pull request closed without merging**
