### PR TITLE
New bans default to global

### PR DESCRIPTION
**Pull request by Rukofamicom**
## About The Pull Request

Admins no longer have to remember to change their bans from Local to Global when making new bans

## Why It's Good For The Game

None of our bans should be local anymore.

## Changelog
:cl:
admin: New bans no longer default to local.
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — COMMENTED** [review]
The global box is checked if the ban isnt a global ban and the local box is checked if the ban is a global ban

**Comment by Rukofamicom** [comment]
If that's true then I have absolutely no idea how to make this PR. I reversed a single isnull value from local to global and that changes which bubble is selected by default. 

Close this PR if what you say is true because I apparently don't understand UI code in the least.

**Comment by PowerfulBacon** [comment]
image

**Comment by Rukofamicom** [comment]
Both bubbles are marked as checked before this PR. 

image

**Comment by PowerfulBacon** [comment]
If its not a global ban then that one will show as being checked

**Comment by Rukofamicom** [comment]
So... how do I force it to default to global. That is the entire point of this PR.

**Comment by Rukofamicom** [comment]
Fixed in the laziest way imaginable. 
image

**Review by PowerfulBacon — APPROVED** [review]
This seems find to me, after doing some digging and understanding the spaghetti of this code, this should work fine

**Pull request merged**
