### PR TITLE
Aristocrat coats & Hastur Robes rework

### PR DESCRIPTION
**Pull request by Malgover**
## About The Pull Request

This PR adds 4 new coats to the law office's wardrobe and reworks the Hastur robes. 
coats
hastur2

Orange:
orange

Red:
red

Brown:
brown

Blue:
blue

Hastur robes:
hastur

## Why It's Good For The Game

The more clothes the better, and the law office's wardrobe is lackluster compared to other wardrobes. This PR aims to provide our beloved lawyers with more customization. Now they can truly look like lawyers!

As for the Hastur robes, I thought the original sprite was quite ugly and needed a change (no offense to the original spriter). I used the Eldritch armor as a base for the sprite to be more coherent with the server's artstyle. 
The robe is now available to purchase from the Chaplain's wardrobe.

PS: I closed my previous PR because I don't understand how anything works on GitHub.

## Changelog
:cl:
adds: aristocrat coats to the law office's wardrobe and reworks the hastur robes.
/:cl:##

### CODE REVIEW

**Comment by ToasterBan** [comment]
you fucked up the changelog, make sure you do "adds:" not "Adds"

**Comment by Malgover** [comment]
> you fucked up the changelog, make sure you do "adds:" not "Adds"

Fixed, thank you

**Comment by Archanial** [comment]
Not fixed, make it lowercase

**Comment by Malgover** [comment]
> Not fixed, make it lowercase

Fixed now. :(

**Comment by Malgover** [comment]
Here's a closer look at the robe with a new rune I plan on implementing. 
Space Station 13 2021-04-27 181558

The hood is now also part of the robe instead of being a separate clothing item.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
