### PR TITLE
Xenomorph Rebalance

### PR DESCRIPTION
**Pull request by Isy232**
## About The Pull Request

This PR nerfs xenomorphs in general. If you want to see exactly what it does you can see the files changed for the most accurate description of the changes.

In general:
- A single xeno can no longer stunlock cyborgs. (The borg gets a 0.5 second long chance to run away between stuns)
- Neurotoxin is not longer a 10 second stun, it does 45 stamina damage and a 1 second knockdown but only costs 30 to shoot instead of 50.
- Xenomorph disarms are no longer a 10 second long stun, it does 90 stamina damage (equal to a stun baton) and can no longer rip guns out of your hands on the first hit.
- Hunter pounce is now a 5 second stun instead of 10.
- All xenomorphs get about a 25% health increase.
- Planting weeds costs 25 plasma instead of 50.
- Corrosive acid costs 50 plasma instead of 200. (This melts items on the ground or doors and walls.)

## Why It's Good For The Game

Xenomorphs are exceptionally overpowered in their current state, utterly destroying anything that isn't a deathsquad with 10 second long stuns. Xenos now for the most part do stamina damage and require more than 2 hits to knock someone down and they no longer instantly remove your held weapons. (Except for cyborgs).

To counter the loss of all of these cancerous stuns, xenos get a fair bit more health and I doubt they will need anything more.

Something to point out is that xenomorphs are in no way weak after these changes.
- A sentinel can hit you with neurotoxin once, then run up to you and disarm you once. This will put you into stamina crit if you are unarmored, 2 hits if you are armored. They also have near invisibility in the right conditions.
- A hunter has the same speed as a person on meth or syndicate stimulants. They can easily run away from difficult fights in search of weaker prey or if their target lacks a shield, pounce on them and then disarm them into stam crit while they are paralyzed from the pounce.
- Queen and Praetorian both have the neurotoxin ability, even more health than the sentinel and d
- ANY xenomorph can disarm someone twice to put them into stamina crit. With riot armour it is 3 hits and if you add a riot shield on top of that there is a block chance. If you're this geared up your a fair threat to a single xenomorph.
- Drone lacks combat abilities, but it still has the same melee power as all other xenomorphs. Its not meant to be a combat caste.

## Changelog
:cl:
balance: A single xeno can no longer stunlock cyborgs and deal damage to them.
balance: Neurotoxin is not longer a 10 second stun, it does 45 stamina damage and a 1 second knockdown but only costs 30 to shoot instead of 50.
balance: Xenomorph disarms are no longer a 10 second long stun, it does 90 stamina damage (equal to a stun baton) and can no longer rip guns out of your hands on the first hit.
balance: All xenomorphs get about a 25% health increase.
balance: Planting weeds costs 25 plasma instead of 50.
balance: Corrosive acid costs 50 plasma instead of 200. (This melts items on the ground or doors and walls.)
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
I dislike the changes to spit and to pounce. they seem somewhat excessive

**Comment by Cenrus** [comment]
pounce is countered by shields, so I think you shouldn't reduce the stun so much

**Comment by zeskorion** [comment]
pounce is also somewhat clunky to land in general. neurotox should remain a stun that can fuck up tiders, and instead get fucked by thick clothes

**Comment by Isy232** [comment]
> pounce is countered by shields, so I think you shouldn't reduce the stun so much

Right, I'll set it to 5, that is guaranteed long enough to disarm them into stun or put them nearly into crit.

**Comment by Crossedfall** [comment]
Do you mind updating your CL to properly list out the changes? It should look like this:
```
:cl:
balance: Xenos can no longer stunlock cyborgs.
balance: Neurotoxin is no longer a 10 second stun, it does 30 stamina damage but only costs 20 to shoot instead of 50
/:cl:
```

Keep the balance descriptions short, but make sure it provides enough context to people reading the changelog in-game to know what has actually been adjusted.

**Comment by Isy232** [comment]
> Do you mind updating your CL to properly list out the changes? It should look like this:
> 
> ```
> :cl:
> balance: Xenos can no longer stunlock cyborgs.
> balance: Neurotoxin is no longer a 10 second stun, it does 30 stamina damage but only costs 20 to shoot instead of 50
> /:cl:
> ```
> 
> Keep the balance descriptions short, but make sure it provides enough context to people reading the changelog in-game to know what has actually been adjusted.

Just did that, I think I got it right

**Comment by Isy232** [comment]
> pounce is also somewhat clunky to land in general. neurotox should remain a stun that can fuck up tiders, and instead get fucked by thick clothes

I think it shouldn't be a stun, because then it would be overpowered against those without protection and useless against those with. Xenos have may stuns in other ways. I'll put the stam damage up to 45 instead so its a 3 shot stun.

If you still don't think thats enough, xenos health has been increased a fair bit, mainly so that xenomorphs are no longer glass cannons.

Hunters should be easily able to run away if they get hurt, provided they don't get trapped. They have the same speed as someone on meth, can run over tables and under plastic flaps.

Sentinels have an extra hundred health to offset neuro being nerfed, and 3 shots is really quite good. They can also still go nearly invisible.

I'll also up disarm damage to match neurotoxin damage.

I honestly think that they will still be too strong after this but I could definitely be wrong.

**Comment by Isy232** [comment]
I'm open to debate balance surrounding this PR further and please know that I don't want to nerf xenos into oblivion. Back on TGMC I was a xeno main and I definitely find xenos very interesting. Its just that since they are so strong there is no fun in fighting them.

**Comment by Isy232** [comment]
They also cannot be used as any sort of common antagonist because anything less than a deathsquad or combat mech is near utterly incapable of fighting them.

**Comment by qwertyquerty** [comment]
Checks don't pass, vote failed

**Pull request closed without merging**
