### PR TITLE
AI VOX expansion

### PR DESCRIPTION
**Pull request by OverwatchVoice**
## About The Pull Request
Expands the AI vox with six "announcement start" sounds from Half-Life 1, ranging from simple beeps to klaxons for emergency alerts

## Why It's Good For The Game
Now AIs can roleplay as an automatic announcer easier!

I've seen some AI players adding sounds sunch as scensor to the start of their vox messages, but currently available sounds are very limiting, and very annoying.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
To be added

</details>

## Changelog
:cl:
add: Six new "announcement start" sounds played by the AI vox
/:cl:

### CODE REVIEW

**Comment by Dejaku51** [comment]
### For people that are too lazy to download them
_Note: they might sound different ingame_

https://user-images.githubusercontent.com/40302913/160680625-d26c8a6a-24cf-4c90-b597-7c35800d16ef.mov


https://user-images.githubusercontent.com/40302913/160680627-c174759e-6eff-4b2c-acff-7616e9d4ad24.mov


https://user-images.githubusercontent.com/40302913/160680629-b72ee873-b836-4342-97f6-313d74b6196d.mov


https://user-images.githubusercontent.com/40302913/160680634-8070b26b-286e-4e95-a7f8-168487ad58e1.mov


https://user-images.githubusercontent.com/40302913/160680637-e0443b30-c301-4d45-9dd9-f0d239e729fa.mov


https://user-images.githubusercontent.com/40302913/160680640-458f79d9-f696-4cbb-bc08-4558ad18fa76.mov

**Comment by AnCopper** [comment]
I don't think we can use these sounds.

**Comment by OverwatchVoice** [comment]
> I don't think we can use these sounds.

Out of fear of copyright infringements?

BeeStation already uses a few sounds ripped from various source games and the vox system has 90% of its vocabulary taken from hl1, so I doubt it'd be a cause of concern

**Comment by OverwatchVoice** [comment]
Can't open this again because I was dumb and used the master branch. I'll be making a new one.

**Pull request closed without merging**
