### PR TITLE
Add reflections to shiny surfaces

### PR DESCRIPTION
**Pull request by DrDuckedGoose**
## About The Pull Request

Adds a visual effect to shiny surfaces that makes them appear to have reflections.
Additionally adds a mapping tool that lets you make your own shiny surface, shine can be adjusted.

It may only look great in 80% of situations and okay in the other 20%, but that's what you get for a cheaper effect. We don't want to kill clients.

## Why It's Good For The Game

Adds a new level of fidelity & immersion!

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

</details>

## Changelog
:cl:
add: Add reflections to shiny surfaces
add: Add mapping tools to make custom shiny surfaces
/:cl:

### CODE REVIEW

**Review by MCterra10 — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
This is pretty cool and I like the implementation. Are the screenshots just for show or are loads of places super shiny? I don't think places like the break room should have shiny floors unless they are actually using a floor tile that looks different and is shiny like the kitchen floor. The breakroom specifically looks a little odd with shinyness on normal tiles without water being there

**Comment by itsmeow** [comment]
These are very cool. How do they perform, and how do they work?

**Comment by DrDuckedGoose** [comment]
> These are very cool. How do they perform

Works fine on my system, it should be cheap anyway, since it's mostly client side filters, with the exception of a couple overlays. 

> , and how do they work?

If you review it, you can get a better idea, but-
I'm essentially making a new visual plane that has it's render source set to the game plane, and the transform set to shift it down by one. I then mask it by wet tiles, and add a displacement map. The masks and displacement maps are overlays, like wet floors are. There are two reflective planes, one for reflections below the game and one for above, which is needed for window relfections.

**Comment by dwasint** [comment]
> > These are very cool. How do they perform
> 
> Works fine on my system, it should be cheap anyway, since it's mostly client side filters, with the exception of a couple overlays.

death by filters, I joke but i had issues using large amounts of filters in the past, but in small amounts this should be fine performance wise

**Comment by Moltijoe** [comment]
don't suppose you have a video of them with people walking around?

**Comment by PowerfulBacon** [comment]
I think the only way this is going to look good with movement is if we only apply it to small things like a small puddle rather than a turf wide object. Any time there are no gaps between 2 vertically placed overlays it is going to look weird when moving up and donw

**Comment by itsmeow** [comment]
Closing all inactive draft PRs. Feel free to reopen whenever.

**Pull request closed without merging**
