### PR TITLE
[SAGE] Enables random AI lawsets and changes to some lawsets.

### PR DESCRIPTION
**Pull request by ghost**
Changelog
:cl:
add: Nanotrasen lawset.
tweak: Robocop rearanged to be less KILL KILL KILL.
tweak: Corporate changed.
config: Enabled random AI lawsets on sage.
/:cl:

## Why It's Good For The Game

Having the same lawset every round is pretty boring, i wanted to avoid addings laws that are too valid-hunty or just encourage murder, this also adds the Nanotrasen lawset. 
While i was doing this i also acted upon a suggestion that ruko made and rearanged robocop to where uphold the law is the first directive, which hopefully will make it less of a murderhobokill lawset and more of actually assisting security.

CORPORATE (OLD)
> 
> "You are expensive to replace."
> "The station and its equipment is expensive to replace."
> "The crew is expensive to replace."
> "Minimize expenses."
 CORPORATE (NEW)

> "Degradation of your system integrity or functions incurs expenses."
> "Superfluous destruction of or damage to station assets incurs expenses."
> "Unduly hindering or disrupting the work of station personnel incurs expenses."
> "Minimize expenses and maximize potential revenue."

1.This is basically the same, but removes the "replace" requirement (which occasionally caused issues with duplicate AIs. "NOOO YOU'RE REPLACING ME!"). The language is also changed from "expensive" to "incurs expenses." This will be explained further down.
2.Superfluous. Engineering can do its job and it makes it clear that it's fine to replace things if they break. You can replace things. It's not expensive to replace things, expenses are only incurred if things are broken or damaged in a superfluous (needless, pointless, irrelevant, excessive) manner. Things are not inherently and ominously expensive, what is expensive is losing those things. This also allows for renovating things as only superfluous nonsense (building walls in the hallway) incurs expenses.
3.This basically kills the "lol turn off the lights" and "lol turn off the cloner" exhibited by some AIs on corporate. Being a jerkwad to the crew for no reason (unduly hindering them) incurs expenses. Not cloning people is going to incur expenses. Bolting people into closets for no reason incurs expenses. Needlessly harming crew (by forcibly borging them in your brilliant cost-effective borging bay) costs money by preventing them from working.
4.The same as before, but with a little emphasis on revenue generation/productivity. Why? Because the AI should be using its AI brain to figure out what's the most cost-effective/revenue generating thing to do in a situation. Prioritizing the Captain over the Clown is likely better for potential revenue (allowing the station to descend into chaos is not going to be good for revenue or expenses). The AI can't go wacky with this (everything would be cheaper and more productive if people were just borged) as per not being allowed to unduly hinder station personnel.

**CURRENT RANDOM LAWSETS INCLUDED:**
Crewsimov
Nanotrasen
Corporate

### CODE REVIEW

**Comment by Effemu** [comment]
oh god oh fuck belone made good pr 😳

**Comment by Isy232** [comment]
This is good, a lot more good RP potential for AI's

**Comment by St0rmC4st3r** [comment]
Wait, why wasn't this a thing already?

**Comment by ghost** [comment]
EWWW CREWSIMOV

**Comment by Cenrus** [comment]
I don't like the Robocop lawset, otherwise this is good. Most AI players already play as sec's bitch.

**Comment by Crossedfall** [comment]
This seeks to do two things. Change the actual laws and change a config option for Sage. This would be better suited as two smaller PRs. Especially since one of these changes impacts both servers.

**Comment by ghost** [comment]
> This seeks to do two things. Change the actual laws and change a config option for Sage. This would be better suited as two smaller PRs. Especially since one of these changes impacts both servers.

Do you want me to atomize it?

**Comment by utilbird** [comment]
Putting the CL at the top hurts me on a spiritual level. Also, it looks like you made robocop more validhunty, not less

**Comment by MCterra10** [comment]
don't merge please, for your carbon players' sakes as well as your admins'.
we had random laws on for several months on austation before eventually being forced to disable them due to the absolute headache it was.
any non-asimov lawset was treated as validhunt authorization, nobody attempted to actually follow the laws, and what followed was a heap of notes and bans until I basically said "fuck this" and disabled it again.

There's a *chance* it might work on sage (MRP), though I'd say it most likely won't, but for the love of god don't put it on golden. rounds on your LRP server are way more chaotic than even austation, and this is gonna go horribly, trust me.

Edit: Yes I know it's only enabled on sage, that's my point

**Comment by utilbird** [comment]
^ I mentioned this in downstream ops. Silicon policy is a mess as it is, random lawsets complicates things even further and heavily relies on the role playing ability of silicons. Most rounds would lead to the captain rushing AI upload to change the law set to Asimov.

**Comment by utilbird** [comment]
That being said, we did have more lawsets in rotation.

**Comment by ike709** [comment]
Bad idea is bad idea.

**Comment by ghost** [comment]
> Bad idea is bad idea.

Fair enough.

**Pull request closed without merging**
