### PR TITLE
logs some of the most cancerous random maint runes

### PR DESCRIPTION
**Pull request by bloons3**
## Changelog
:cl:
admin: logs more cluwne spawns from random maint runes
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
But the cluwne rune doesnt even appear ingame?

**Comment by bloons3** [comment]
> But the cluwne rune doesnt even appear ingame?

Clown Curse does, and someone might add the rune back in again.

**Comment by zeskorion** [comment]
R 

> > But the cluwne rune doesnt even appear ingame?
> 
> Clown Curse does, and someone might add the rune back in again.

Cluwnecurse shouldnt appear without the rune. Its probably a spawn trap you're thinking of

**Comment by bloons3** [comment]
> R
> 
> > > But the cluwne rune doesnt even appear ingame?
> > 
> > 
> > Clown Curse does, and someone might add the rune back in again.
> 
> Cluwnecurse shouldnt appear without the rune. Its probably a spawn trap you're thinking of

Clown Trap, the harmless floor cluwne spawner. It is mapped in several rooms as an obj spawner.

/obj/effect/trap/nexus/cluwnecurse - harmless floorcluwne, now logged

/obj/effect/rune/cluwne/ - danger clown

**Comment by zeskorion** [comment]
> > R
> > > > But the cluwne rune doesnt even appear ingame?
> > > 
> > > 
> > > Clown Curse does, and someone might add the rune back in again.
> > 
> > 
> > Cluwnecurse shouldnt appear without the rune. Its probably a spawn trap you're thinking of
> 
> Clown Trap, the harmless floor cluwne spawner. It is mapped in several rooms as an obj spawner.

Aaah, i forgot how i coded it nvm carry on

**Review by utilbird — APPROVED** [review]

**Pull request merged**
