### PR TITLE
Captains alert does different noises for each sec level

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
Each sec level makes the captains announcer have a different noise

## Why It's Good For The Game
Gives more attention to the announcement at higher seclevels

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/73374039/189497004-bd5e44f8-549c-4e40-9b3a-36658a31d3ac.mp4

</details>

## Changelog
:cl:
add: captains alert noise changes per sec level
/:cl:

### CODE REVIEW

**Comment by CydiaLamiales** [comment]
I really think you should use other sounds for Red and Delta.

**Comment by Penwin0** [comment]
Red and Delta really don't fit at all

**Comment by Haliris** [comment]
I don't know, I like how the train station sound alert contrasts with the chaos and violence that can occur during Red Alert. I find the goofiness fitting and funny.

**Comment by PowerfulBacon** [comment]
These sounds aren't the best, I would be fine with captain announcement being the red alert alarm sound on red and delta. The banana honk sound effect and radiation meter dont fit

**Comment by BarteG44** [comment]
i like the idea but hate the sounds you used

**Comment by itsmeow** [comment]
Listened to new sounds, they're better

**Pull request closed without merging**
