### PR TITLE
Surgery changes (Self surgery, tend wounds, anesthetics do something, nerfed surgery table, buffed abductor table)

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request

Allows self surgery to be used for several surgery procedures. It has a very steep (-60%) success penalty at the moment. Being near a mirror lowers the penalty to -40%. These numbers are up for debate and i'm willing lower them substantially if needed, but the changes detailed below may explain the apparently less punishing chance
Adds the basic Tend Wounds surgery from /tg/
Surgery table no longer has a 100% surgery chance. It now has an 80% chance- meaning sterilizene or anesthetics are now necessary for a 100% success surgery. Ghetto tables now have an even lower chance, and abductor table actually has a 20% boost to surgery success chance
Surgery now has a substantial (50%) boost when the patient is not conscious- anesthetics were actually purely there for cosmetic reasons before, apparently

## Why It's Good For The Game
adds a bit more depth to surgery, as well as the popular tend wounds surgery

the exhaustive list of self-surgery viable operations are as follows:
tend wounds
amputation
prosthetic replacement (expect a Ghetto Prosthetic pr with peglegs, hook hands, etc at a later date)
cavity implant
soft organ manipulation (everything but the head and chest. Yes, you can spoon out your eyes without help)
dental implant
embedded object removal
viral bonding
vein threading

Note: most essential surgeries that give surgery the most use (torso organ manipulation, mainly, as well as implant removal) still need someone else. The most significant changes here are allowing tiders to cut themselves up trying to replace their arms and legs, and self dental implants, as well as tend wounds for big brained tiders

## Changelog
:cl:
add: tend wounds surgery
add: Anesthesia now has a use
tweak: turns self_operable to true on many surgeries
balance: self surgery now has a significant penalty, which can be reduced by using a mirror
balance: nerfs to all surgery tables but abductor table to encourage sterilizer/anesthesia 
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
As much as I'm rather indifferent to this change, I still think it's incredibly funny this would allow you to take your own organs out.

**Comment by zeskorion** [comment]
> As much as I'm rather indifferent to this change, I still think it's incredibly funny this would allow you to take your own organs out.

actually, you cant do torso organ manipulation, so all you can really rip out is ears, tongue, and eyes

**Comment by SomeAngryMiner** [comment]
cant wait to gouge my eyes out, or reenact the tactics of evil dead.
I was afraid this would be terribly unbalanced, but, you managed to keep it nice n cool with something as conflictive as self surgery, good job.

**Comment by St0rmC4st3r** [comment]
Make it so morphine, krokodil and mining salve give a minor chance boost while they are in the system, but only one at a time to prevent stacking, since the first two are real life painkillers (morphine and desa**morphine**) and mining salve prevents you from feeling damage.

**Comment by zeskorion** [comment]
> Make it so morphine, krokodil and mining salve give a minor chance boost while they are in the system, but only one at a time to prevent stacking, since the first two are real life painkillers (morphine and desa**morphine**) and mining salve prevents you from feeling damage.

Mining salve already works as a sterilizer at +10%.. you can knock someone out with morphine for +50%

**Comment by zeskorion** [comment]
> cant wait to gouge my eyes out, or reenact the tactics of evil dead.
> I was afraid this would be terribly unbalanced, but, you managed to keep it nice n cool with something as conflictive as self surgery, good job.

Thanks


Hmmm... making zombie infection from bites dependent on limb hits so you can amputate yourself as a cure would be interesting. But i dont wanna go through the effort

**Pull request merged**
