### PR TITLE
fix roundstart cultists not getting objectives

### PR DESCRIPTION
**Pull request by MCterra10**
## About The Pull Request
Title

## Why It's Good For The Game
This is pretty annoying

## Changelog
:cl: MCterra
fix: fix roundstart cultists not getting objectives
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Huh I thought this was intentional so you couldnt meta the sunmon location  lmao

**Comment by YakiAttaki** [comment]
> Huh I thought this was intentional so you couldnt meta the sunmon location lmao

how is it intentional that roundstart cultists end up with no objectives?

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
> 
> 
> > Huh I thought this was intentional so you couldnt meta the sunmon location lmao
> 
> how is it intentional that roundstart cultists end up with no objectives?

So they couldn't meta their summon locations

**Comment by MCterra10** [comment]
> 
> 
> > > Huh I thought this was intentional so you couldnt meta the sunmon location lmao
> > 
> > 
> > how is it intentional that roundstart cultists end up with no objectives?
> 
> So they couldn't meta their summon locations

that makes zero sense though if cultists recruited with the rune get the objectives anyway lmfao

**Pull request merged**
