### PR TITLE
Reinforced Wood Tables

### PR DESCRIPTION
**Pull request by fighterslam**
## About The Pull Request
Ports reinforced wooden tables from Shiptest, made by TetraZeta at https://github.com/shiptest-ss13/Shiptest/pull/39

## Why It's Good For The Game
More tables!

## Changelog
:cl: fighterslam
add: Adds reinforced wooden tables, buildable by applying plasteel to a wooden table frame.
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
this thing has its own dmi file all to itself
this is normal for other 4 quadrant structures?

**Comment by TerryTehCoder** [comment]
This might be the greatest addition to table history since skateboard drifting. I'll be keeping my eyes out for the motorized wheelchair drift next.

**Comment by ivanmixo** [comment]
> this thing has its own dmi file all to itself
> this is normal for other 4 quadrant structures?

Yeah, all the tables get their own .dmi file due to the corner bits.

**Comment by qwertyquerty** [comment]
:key:

**Comment by francinum** [comment]
Sorry mate this sprite fucking sucks
🔑

**Pull request closed without merging**
