### PR TITLE
[Bounty] Battle Royale on round delay + Battle royale bettering

### LINKED ISSUE #3060: Make battle royal automatically start if restart is delayed.
Feature requests are handled in the repository, but you could also discuss your ideas on beestation discord or forums here: https://forums.beestation13.com/

### PR DESCRIPTION
**Pull request by PowerfulBacon**
resolves https://github.com/BeeStation/BeeStation-Hornet/issues/3060

## About The Pull Request

When delaying round end admins will be prompted if they want to run battle royale.
When all the tickets are completed, battle royale will enter sudden death mode and the wall speed will be set to 0. (The game will then last for radius second which is a maximum of ~120)
Basic loot drops will now spawn more than 1 item, since usually they are useless.
Players now spawn with a choice beacon containing a syndicate hardsuit, energy sword, combat medkit or syndicate balloon.
Battle royale loot is now weighted.
Fixed super rare drops taking 900 seconds to arrive.
Players will no longer collide with each other during the first 30 seconds of the game.
Players will now spawn with a toolbelt and insulated gloves.

This took way longer than it should have.

## Why It's Good For The Game

Improvements to battle royale and a bounty. If admins are doing long tickets they will now be prompted to trigger battle royale after the round ends, and the game mode will run itself without them needing to do things, so they can focus on the tickets.

## Changelog
:cl:
add: Upon delaying rounded, admins will be prompted if they want to start battle royale.
tweak: Battle royale loot is now weighted
tweak: Battle royale players will now spawn with a toolbelt and insulated gloves.
tweak: Players can no longer collide with each other in the first 30 seconds of battle royale.
tweak: Players now spawn with a choice beacon in battle royale.
tweak: Battle royale will have the wall speed set to maximum upon all tickets being completed.
tweak: Battle royale wall now has a minimum radius of 3.
balance: Battle royale basic drops will now spawn 1 - 3 items
fix: Elite battle royale drops no longer take 15 minutes to land.
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
Doesn't battle royale delete mobs, which disconnects their logs from players or something?

**Comment by PowerfulBacon** [comment]
> 
> 
> Doesn't battle royale delete mobs, which disconnects their logs from players or something?

Logs are stored on the client (and the mob, but nobody ever looks at the mob logs since the client logs are more detailed)

**Comment by ike709** [comment]
This needs to not interfere with the logs in any way and preferably not bloat them either.

**Comment by PowerfulBacon** [comment]
> This needs to not interfere with the logs in any way and preferably not bloat them either.

Pausing player attack logs round end would be super useful. currently its super hard to tell rounded grief from just before rounded grief.

**Comment by MNarath1** [comment]
would it be possible to exclude people already playing CTF from the mob purge i understand that the station z level needs to be purged for BR but there is no reason to do the same for the CC z level that would at least allow people to choose not to parttake

**Comment by PowerfulBacon** [comment]
Additional Log Helpers have been added: The log files on a mob (right click logs) will now show the state of the game in the log (and will automatically pause after round end). Writte logs to log files using the log_message proc will also show the gamestate at the time of logging, but will never pause. (People can still break the rules after round end!)

**Comment by heepox** [comment]
epic

**Comment by PowerfulBacon** [comment]
🔑

**Comment by jlsnow301** [comment]
r e o p e n  t h i s :(

**Pull request closed without merging**
