### PR TITLE
Remaps all turbines for Atmos Tech QoL and to reduce radleak incidents

### PR DESCRIPTION
**Pull request by Tsar-Salat**
## About The Pull Request
This is a PR that does several things to all the turbine setups in all 7 maps.
For all maps:
- Utilizes depleted uranium glass and replaces the metal walls that contained the inner chambers with glass aswell. 
- Several minor repipings were done, as gas pumps under glass window tiles cannot be interacted with
- Moved buttons and wall devices off the (now glass) inner tiles and onto adjacent walls, as devices on walls is against mapper policy
- I made all the walls into regular iron walls. For some reason some of the maps were iron walls, some were rwalls. Seemed unnecessary when someone could just break a window or an airlock to get in and just stifled players.

EXCEPTIONS: Corg and Meta were both given bigger reworks of their Atmos Engines/Incinerator compared to the others

Meta: Turbine exhaust was simplified and strange manifold under the tile was changed into a visible one above the tile.

Corg: Full engine repiping. I moved the whole setup up one tile, added an actual exhaust then split it into two routes: Exhaust and TEG.

## Why It's Good For The Game
The primary intention here was part of the ongoing effort to remove unnecessary complexities that hurt player interest in atmos. Additional reasoning in streamlining the incinerators, making use of new features we have in the code, and my own personal contempt for railroading player creativity (why the hell were all the walls rwalls)

The addition of the replacement depleted uranium glass promotes visibility aswell as making any fusion or trit setups cause less radiation leakage which could lead to bans or people getting roundremoved. An individual now has to *purposefully* burn gas AND remove these windows to grief, which makes it much more obvious to command and admins when someone radleaks  "on accident". A creative traitor with perhaps a hijack objective could still sabotage and replace these specialized glass as easily as before, so no impact is made on that front, which is the intention of this author. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

metanew

corgnewNEW

boxnew

kilonew

pubbynew

deltanew

</details>

## Changelog
:cl: RKz
add: All station incinerators now utilize the breakthrough new anti-radiation technology of Depleted Uranium! Incident #36690, #39352, #40930, and others anomalies should now be _99.99%_ totally preventable!
tweak: Repiped corg incinerator in its entirety. Its waste pipe now has a pipenet route to a space outlet or TEG. Minor simplifications to Meta incinerator
tweak: I standardized the layout of some of the turbines. They are supposedly cookie-cutter technology just brought over and welded onto their respective station, and it gave me the opportunity to cut out some of the unnecessary piping bullshit(looking at you meta) that overcomplicated the turbine's purpose. None of my changes (save corg) should effect the turbine's actual functionality of put gas in, filter it out.
balance: rwalls of some incinerators have been replaced with iron walls to decrease stifling of atmosian creativity. Technically a balance change as it makes incinerators easier to break into. Technically...
admin: Accidental radleaks much less likely. "Why didnt you burn that risky mix where there is equipment to handle it", is now a viable question to ask griefers.
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
oh wow im dumb. I piped corg exhaust to the fucking *SUPERMATTER* intake, not TEG 
big L

Major L

**Comment by Tsar-Salat** [comment]
epicly

now follows le epic waste pipe to where the actual pump to TEG is

epicly-er

**Comment by Tsar-Salat** [comment]
Observant individuals will notice this is very thematically similiar to #8046 , my first PR. I deleted that branch in its entirety and atomized it only to turbine changes, with no AAC edits whatsoever.

I do plan on coming back to the AAC change eventually, but this change I think is more urgent rather than fixing the AAC fuckery we have going on.

**Comment by Penwin0** [comment]
> * Utilizes depleted uranium glass and replaces the metal walls that contained the inner chambers with glass aswell.

I don't think atmos techs should be babyproofed like this, if they disregarded getting proper rad protection they deserve the consequences

**Comment by Tsar-Salat** [comment]
> > * Utilizes depleted uranium glass and replaces the metal walls that contained the inner chambers with glass aswell.
> 
> I don't think atmos techs should be babyproofed like this, if they disregarded getting proper rad protection they deserve the consequences

Its not a baby-proof. Its a grief-repellant. It specifically stops people who dont know what the fuck they are doing from irradiating a bunch of shit. Any griefer would have to either remove the glass, or do their reaction somewhere else. 
Considering how annoying determining intentions are for admins, it makes it rather crystal whether someone either:
- A. is new and messed up their reaction, where it stays relatively little contamination (I didnt make all the walls radglass)
- B. Purposefully removed the windows, or did their radiation experiments outside the designated zone, where an admin can just apply a simple roleban/serverban without having to sift through a shitton of logs.

I literally had my radiation report sit around for a month or so because the logging was so poor, lets make it rather clear cut, yeah?

Besides, that specific change has existed on live pubby for the past few months since pissglass got added.

**Comment by Tsar-Salat** [comment]
Update. Fixed Corg and Kilo. Removed all my changes to Fland.

ugly button
Fixed Ugly buttons on Kilo


camerareplace
Moved camera off glass

**Comment by Tsar-Salat** [comment]
lights

**Comment by Tsar-Salat** [comment]
image
Was told the waste injector looked ugly. Should be better now

**Review by itsmeow — DISMISSED** [review]
looks fine. why did you switch the direction of the dual vent pump on meta?

**Comment by Tsar-Salat** [comment]
> why did you switch the direction of the dual vent pump on meta?

Ah apologies. I standardized most of the turbines, so this was somewhat of an unintentional byproduct.

My reasoning is that, since the layer manifold adapters run perpendicular instead of parallel to the intake and exhaust, it will be much harder to accidentely attach the wrong pipe to it and flood distro with a turbine burn mix.

**Review by itsmeow — APPROVED** [review]

**Pull request merged**
