### PR TITLE
Assistants have a bounty to get coffee

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
The civ bounty machine now has a bounty to obtain some coffee.

## Why It's Good For The Game
the "intern getting coffee" trope is funny imo

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

how do i force a specific bounty to appear

</details>

## Changelog
:cl:
add: Some Nanotrasen officials have been using the requests board to get free coffee, be advised.
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
you should just make this a crew objective for assistants

"Give coffee to X amount of (DEPARTMENT_WORKERS - scientists, medbay staff, etc)"

**Comment by etherware-novice** [comment]
well yes but then how would you..like actually track that? also there aren't THAT many solars drink venders so it would have to be low

**Comment by Coding-Grape** [comment]
> well yes but then how would you..like actually track that? also there aren't THAT many solars drink venders so it would have to be low

Make the coffee with civilian garden

**Comment by etherware-novice** [comment]
i dont know how to code botany, and again how do i check if coffee was "delivered"?

**Comment by PowerfulBacon** [comment]
This is far too easy, it just involves going to a vending machine, getting a like 20 credit coffee and putting it on a shuttle for like 1000 credit profit. It's not like you have to brew the coffee and there are vending machines on centcom.

**Comment by etherware-novice** [comment]
ok what about 21c

**Comment by LodedDiper69** [comment]
> well yes but then how would you..like actually track that? also there aren't THAT many solars drink venders so it would have to be low

You can check if these people ever had coffee in their system. But you also dont need to do that and just do a general "hand out coffee to the crew" without any objective tracking.

**Comment by etherware-novice** [comment]
ok ill make it a crew objective please dont close this

**Comment by EvilDragonfiend** [comment]
> ok ill make it a crew objective please dont close this

Even though crew obejctives are easy ones enough, coffee is incredibly ridiculously easy to access. That won't be approved.

**Comment by BarteG44** [comment]
> This is far too easy, it just involves going to a vending machine, getting a like 20 credit coffee and putting it on a shuttle for like 1000 credit profit. It's not like you have to brew the coffee and there are vending machines on centcom.

me when trash bounty

**Comment by itsmeow** [comment]
I like the idea of this being a crew objective, to get coffee to so many crewmembers, as it gives assistants something to that actually pertains to their job instead of greytiding.

The way I'd do it is adding a signal to the give hotkey so that every time you GIVE coffee with that mechanic it adds one to your counter.

**Comment by itsmeow** [comment]
> Even though crew obejctives are easy ones already, coffee is incredibly ridiculously easy to access. That won't be approved.

Crew objectives already suck, station engineers get one to keep station integrity above x%.

It almost never goes below 95 so long as you don't have 5 serial bombers and a singloose.

**Comment by etherware-novice** [comment]
> > Even though crew obejctives are easy ones already, coffee is incredibly ridiculously easy to access. That won't be approved.
> 
> Crew objectives already suck, station engineers get one to keep station integrity above x%.
> 
> It almost never goes below 95 so long as you don't have 5 serial bombers and a singloose.

as if that doesnt always happen?

**Comment by itsmeow** [comment]
I've only seen three singlooses in around 600 hours

**Comment by ike709** [comment]
🔑 lame

**Comment by etherware-novice** [comment]
you couldve been nicer..

**Pull request closed without merging**
