### PR TITLE
Noslip turfs under medbay showers

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
was asked to do it, honestly surprised noone had tried it already

## Why It's Good For The Game
It sucks to just mistakenly slip on a puddle underneath the medbay emergency showers, most of which are in highly trafficked areas. People are sick of this and so am I. So I fixed it.

## Changelog
:cl:
add: Noslip tiles beneath all medbay showers
/:cl:

### CODE REVIEW

**Comment by prophed** [comment]
But that is the beauty of leaving the showers running.

**Review by ike709 — APPROVED** [review]
Sad that mapdiffbot is dead.

**Comment by MarkSuckerberg** [comment]
Isn't it though?

**Comment by Crossedfall** [comment]
mapdiffbot lives once more

**Comment by qwertyquerty** [comment]
Would be cool if it looked like this
H-3595

**Comment by MarkSuckerberg** [comment]
I'd much prefer if it looked like that. Not a fan of the bright yellow tiles to be perfectly honest.

**Comment by ike709** [comment]
WYSI.

**Comment by MarkSuckerberg** [comment]
i map and code already, not gonna sprite too. Gonna go yell at the ~~slaves~~ spriters

**Comment by qwertyquerty** [comment]
We can change the icons later

**Pull request merged**
