### PR TITLE
Bioscanners

### PR DESCRIPTION
**Pull request by TsunamiAnt**
## About The Pull Request

Collection of all fixes and tweaks to avoid having to do single PRs for one line changes.

- Health analyzers can now be researched at tier 2
- Docs spawn with analyzers again
- Health analyzers can only scan the basic damage types+blood volume. This will cover most use cases except for more advanced situations which will require the bioscanner.
- No more radiation.
- Bioscanners take less time to scan people and you can escape from them by using resist.

## Why It's Good For The Game

Fixes are good. Good tweaks are better

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

More or less just logic changes, I could screenshot the code?

</details>

## Changelog
:cl:
tweak: Tweaked health analyzers to make them available again.
balance: Made health analyzers a bit weaker to compensate for their increased availability.
balance: Radiation scanning damage removed completely.
fix: Properly added health analyzers to the tech node.
fix: Added mutation and blind/deafness to the bioscanner readout.
fix: Color coded the damage readouts for the bioscanner.
/:cl:

### CODE REVIEW

**Comment by TsunamiAnt** [comment]
Let's keep this un-merged for a bit, since the only real data we have right now is from a bugged round and then lots of deadpop.

**Comment by Rukofamicom** [comment]
> * Health analyzers are now no longer gated behind research disks, they are now a standard tier 2 research and can be printed at the medlathe as usual.
> * Health analyzers now take a second to scan and can only scan the basic damage types+blood volume. This will cover most use cases except for more advanced situations which will require the bioscanner.

These are good compromises to consider, though I agree that it shouldn't be merged until after the dust has settled and we have a clear idea of the current situation now.

> * Analyzers now do half as much radiation damage, as such they can be used 6+ times before they stop working.
> * Bioscanners now work twice as quickly.

I don't like these, especially since all of the outcry about radiation is entirely based in ignorance. 
A few people started saying things about the radiation and how awful it was that were just wildly untrue, like comparing the scanners to the traitor item. 

Bioscanners operating with their delay has a certain cool factor to it.

**Comment by PowerfulBacon** [comment]
I think the health analysers should return to the standard medical position's loadout

**Comment by TsunamiAnt** [comment]
I will keep the description updated as people demand tweaks from me. They've chained me against the PR and are forcing me to keep doing things.

**Comment by SunShine214** [comment]
I do like this, as having a sort of diagnosis pipeline is cool. It was a little strange how multifunctioning the scanners were. Rads, traumas? I think I will enjoy using the bio scanner for detecting decay and organ damages and such.

**Comment by TsunamiAnt** [comment]
Fuck this, I'm making a new PR. This is hell

**Pull request closed without merging**
