### PR TITLE
Gives the Roboticist and their superiors AI Private access

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
Grants the Roboticist, RD, and Captain AI Private access in their radio keys. Technically its not "granting" access because you can set a radio to it but it helps to always have access.

It also completely replaces an old unused Robotics headset and makes the Roboticist start with the new headset.

## Why It's Good For The Game
The Roboticists can more directly communicate with the AI and silicons to command them
The RD would *greatly* benefit from knowing whats going on in AI-sensitive areas, as the AI's function falls under their job description.
The captain just gets everything so add it on.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

robo_ground

robo_chat

</details>

## Changelog
:cl:
add: Added ai private to the Robo, RD, and Captains encryption keys
imageadd: Replaces the old Roboticist's headset
del: Removed the old (unused) Roboticist's headset
add: Adds new robotics headset to robos roundstart gear
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
What's the point of this when you can just have a personal station bounce radio that set to AI private?

**Comment by EvilDragonfiend** [comment]
also, AI private is mostly used as an AI to hear the station, not a way to conversate with people mostly.

**Comment by etherware-novice** [comment]
well its somewhat difficult to get the game to speak into a sbr, headsets are more private, and you might forget to get a sbr, so having it always on and a quick :o away is handy

**Comment by etherware-novice** [comment]
> also, AI private is mostly used as an AI to hear the station, not a way to conversate with people mostly.

but its still handy to always have comms into ai upload to quickly tell if anything bad is going down

**Comment by EvilDragonfiend** [comment]
I am still not sure. those people are just enough to talk in R&D channel. AI channel isn't necessary.

**Comment by itsmeow** [comment]
yeah no, AI private is PRIVATE for the AI

**Comment by etherware-novice** [comment]
oh

**Pull request closed without merging**
