### PR TITLE
Locks humans behind the paywall

### PR DESCRIPTION
**Pull request by super12pl**
Locks humans behind the paywall. Imagine how many people gonna pay for it.

## Changelog
:cl:
tweak: humans are now behind the paywall
/:cl:

### CODE REVIEW

**Review by qwertyquerty — CHANGES_REQUESTED** [review]
Should be `TRUE`, and you need to format your PR correctly and add a CL

**Comment by PowerfulBacon** [comment]
???

**Comment by PowerfulBacon** [comment]
You cant just lock the default species behind a paywall

**Comment by St0rmC4st3r** [comment]
Of course you can!

**Comment by Bastian0930** [comment]
You can, qwerty did.

**Comment by TeomanTheGreat** [comment]
> You can, qwerty did.

Catgirl isn't a default species mr degenerate its only an ascetic difference at most it isn't even original

**Pull request closed without merging**
