### PR TITLE
Some minor efficiency tweaks

### PR DESCRIPTION
**Pull request by utilbird**
## About The Pull Request

I saw a few ways we could reduce some unnecessary server load, this should considerably increase performance during highpop  

## Why It's Good For The Game

Optimization

## Changelog
:cl:
code: Tweaks some return values
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I just ctrl-fed for define EF_FALSE. God damn it

**Comment by PowerfulBacon** [comment]
in b4 qwerty merges it

**Comment by utilbird** [comment]
You should do it before him so he doesn't get the satisfaction

**Comment by Crossedfall** [comment]
Now **this** is efficiency

**Pull request closed without merging**
