### PR TITLE
Augment sprites

### PR DESCRIPTION
**Pull request by Sylphily**
## About The Pull Request

resprites the cyborg augments

## Why It's Good For The Game
varying sprites for genders, also fixes the broken chest sprite with races that have no gender
this also fixes some clipping with sprites

## Changelog
:cl: Shoutgun.boom
imageadd: adds varying gender sprites and adds a sprite for races with no gender. Also adds the very important blinking lights.
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
booba.gif

**Comment by PowerfulBacon** [comment]
Post screenshots

**Comment by utilbird** [comment]
my vision is augmented

**Comment by Sylphily** [comment]
Closing due to some one else doing something better than my sad attempt

**Pull request closed without merging**
