### PR TITLE
Repaths petcollar

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Pet collar is not just item, it can be worn by pets, it can't be worn by players

## Why It's Good For The Game
Previous pr was kinda memey but I am serious in this one. It's cringe, breaks roleplay and """refences""" fetish.

## Changelog
:cl:
tweak: Petcollar cannot be worn by players.
/:cl:

### CODE REVIEW

**Comment by Sylphily** [comment]
dis pr not funney


feleinds that i get to cuff and put on a dog bed and force a collar on is

**Comment by DatBoiTim** [comment]
Previous choice was awesome but if this is best we can get I'll take it

**Comment by Sinestia** [comment]
Noooooooo


buff pet collars by making them act like tinfoil but only for felinids


also
https://github.com/BeeStation/BeeStation-Hornet/pull/7

>USURPING PR 7

**Comment by Naevii** [comment]
refund my coins

**Comment by St0rmC4st3r** [comment]
April fools is over, you are two days too late.

**Comment by TeomanTheGreat** [comment]
The furries are getting mad in the comments. Bruh. Please give me one good way that wearing a pet collar enhances your experience.

**Comment by DatBoiTim** [comment]
> The furries are getting mad in the comments. Bruh. Please give me one good way that wearing a pet collar enhances your experience.

And explain how that enhancement doesn't fit into fetish content

**Comment by Kapu1178** [comment]
> 
> 
> > The furries are getting mad in the comments. Bruh. Please give me one good way that wearing a pet collar enhances your experience.
> 
> And explain how that enhancement doesn't fit into fetish content

females are fetish content

**Comment by DatBoiTim** [comment]
> > > The furries are getting mad in the comments. Bruh. Please give me one good way that wearing a pet collar enhances your experience.
> > 
> > 
> > And explain how that enhancement doesn't fit into fetish content
> 
> females are fetish content

Don't even try to change the subject lmao

**Comment by OceanFish1** [comment]
> The furries are getting mad in the comments. Bruh. Please give me one good way that wearing a pet collar enhances your experience.

Actual state of beestation furries are major playerbase bruh copeseethed

**Comment by Sinestia** [comment]
> The furries are getting mad in the comments. Bruh. Please give me one good way that wearing a pet collar enhances your experience.

Can you give a good reason that carrying this is negative


>ERP

you people literally would basically see women in-game as fetish content were they never there

is cringe content above all lol. I need the right to force it upon ppl and the opportunity for them to prove that they aren't worth interacting with

**Comment by TeomanTheGreat** [comment]
> > The furries are getting mad in the comments. Bruh. Please give me one good way that wearing a pet collar enhances your experience.
> 
> Can you give a good reason that carrying this is negative

Sure. Wearing a pet collar is super weird and is reserved to the type of idiot who likes to be treated like a pet hence why they are wearing a pet collar. People acting like animals on a space station is unprofessional and extremely unbased. Imagine if you went to work in some high profile job in a state of the art space station wearing a pet collar. It just doesn't fit does it?
Edit: also you answered a question with another question

**Comment by utilbird** [comment]
The whole point of it is that it's supposed to be cringe, "people" who unironically wear them are ridiculed. 
Fetish content argument is supposed to be a ironic, it can be applied to almost anything and I don't really want to review a feet removal PR. If it's your main point, you've done something wrong.

**Comment by TeomanTheGreat** [comment]
> The whole point of it is that it's supposed to be cringe, "people" who unironically wear them are ridiculed. 
> Fetish content argument is supposed to be a ironic, it can be applied to almost anything and I don't really want to review a feet removal PR. If it's your main point, you've done something wrong.

How do you ironically wear a pet collar. Also think of it this way. Why do people out in the streets not wear pet collars. Why are they even called pet collars. Because they are for animals. Also is your entire argument "but they are supposed to be ironic and cringe!"

**Comment by utilbird** [comment]
They are cringe though, by removing it you're letting the hornies establish their dominance. This has been around longer than most of our players have 🤔

**Comment by MCterra10** [comment]
:key:

**Comment by TeomanTheGreat** [comment]
> They are

Are you responding "they are" because I said that pet collars were for animals and therefore the people who wear them are animals? If so the whole point is that they shouldn't act like animals. There is a reason they are catpeople and not actual cats with no human characteristics.

**Comment by utilbird** [comment]
> Are you responding "they are" because I said that pet collars were for animals and therefore the people who wear them are animals? If so the whole point is that they shouldn't act like animals. There is a reason they are catpeople and not actual cats with no human characteristics.

No, I was responding to your last bit

**Comment by DatBoiTim** [comment]
Make people who wear pet collars count as simple mobs via rules?

**Comment by TeomanTheGreat** [comment]
> > Are you responding "they are" because I said that pet collars were for animals and therefore the people who wear them are animals? If so the whole point is that they shouldn't act like animals. There is a reason they are catpeople and not actual cats with no human characteristics.
> 
> No, I was responding to your last bit

My mistake then.

**Comment by DatBoiTim** [comment]
If we go the treat as a simple mob rule you can just murder them :joker:

**Comment by yorii** [comment]
Oh boy here we go again

**Comment by githubuser4141** [comment]
> > > The furries are getting mad in the comments. Bruh. Please give me one good way that wearing a pet collar enhances your experience.
> > 
> > 
> > Can you give a good reason that carrying this is negative
> 
> Sure. Wearing a pet collar is super weird and is reserved to the type of idiot who likes to be treated like a pet hence why they are wearing a pet collar. People acting like animals on a space station is unprofessional and extremely unbased. Imagine if you went to work in some high profile job in a state of the art space station wearing a pet collar. It just doesn't fit does it?
> Edit: also you answered a question with another question

It'd depend, people goof off at work all the time, it'd probably earn them some weird looks but then again who wouldn't be a bit loopy if they're living in a completely artificial environment for months/years on end? And let's not forget that in SS13 you do stuff you wouldn't IRL like _professional astronauts throwing food on the floor, Medbay re-using syringes and leaving surgical tools on the floor_, etc etc.

**Comment by TeomanTheGreat** [comment]
> > > > The furries are getting mad in the comments. Bruh. Please give me one good way that wearing a pet collar enhances your experience.
> > > 
> > > 
> > > Can you give a good reason that carrying this is negative
> > 
> > Sure. Wearing a pet collar is super weird and is reserved to the type of idiot who likes to be treated like a pet hence why they are wearing a pet collar. People acting like animals on a space station is unprofessional and extremely unbased. Imagine if you went to work in some high profile job in a state of the art space station wearing a pet collar. It just doesn't fit does it?
> > Edit: also you answered a question with another question
> 
> It'd depend, people goof off at work all the time, it'd probably earn them some weird looks but then again who wouldn't be a bit loopy if they're living in a completely artificial environment for months/years on end? And let's not forget that in SS13 you do stuff you wouldn't IRL like _professional astronauts throwing food on the floor, Medbay re-using syringes and leaving surgical tools on the floor_, etc etc.

Is medical malpractice and throwing food at eachother really on the same level as acting like a pet?

**Pull request closed without merging**
