### PR TITLE
Modernizes BeeStation

### PR DESCRIPTION
**Pull request by CthulhuOnIce**
## About The Pull Request

Adds a long set of changes to the game to bring it up to AAA standards

### Nametags
I added a minecraft-style nametag to players that shows your username
image
I know you're wondering if it interferes with runechat but... 
image

### Death
I felt that the way players die in this game don't really meet AAA standards, so instead of becoming a gross yucky corpse when you die, all your stuff gets dropped to the floor and your body gets deleted.

[Demo](https://gfycat.com/AlarmedWeeIraniangroundjay)

### Right Click
The right click popup menus have been removed. Right clicking is now the same as left clicking. HOWEVER you can use the "Use Right Click" verb in the IC tab to re-enable right clicking for exactly thirty seconds.

### Chat
In order to make the ingame chat more expressive, I have enabled the use of emojis in normal chat.
image
image

### Vote kick
In order to take some of the stress from administrators, I have implemented a vote kick system that allows you to initiate votes to kick players from the game.

## Why It's Good For The Game

We have been stuck in the past, and now it is time for us to move into the ***future***

## Changelog
:cl:
add: Add votekick
del: Removes dead human bodies
del: Removes right click popup menus
add: Adds minecraft style nametag
add: Use of emojis in conversational IC chat
tweak: rename traitor to impostor
/:cl:

### CODE REVIEW

**Comment by Bestparty** [comment]
yes finaly the spessman will be enjoyable again

**Comment by february-ops** [comment]
Fatal flaw traitor should be renamed to impostor and iaa to hide and seek

**Comment by CthulhuOnIce** [comment]
ok done @february-ops

**Comment by TeomanTheGreat** [comment]
Very funny meme pr

**Comment by CthulhuOnIce** [comment]
> Very funny meme pr

What do you mean

**Review by ike709 — APPROVED** [review]
Quality PR.

**Comment by february-ops** [comment]
Merge when?

**Comment by ghost** [comment]
Speedmerge this.

**Comment by VictorVow** [comment]
Fortnite battle bus option for spawning needed.

**Comment by moonheart08** [comment]
Forgot to include lootboxes and gacha mechanics

**Comment by Moccha-Bee** [comment]
speed merge it already

**Comment by utilbird** [comment]
Lootboxes 😳

**Comment by ghost** [comment]
God has abandoned us

**Review by Crossedfall — APPROVED** [review]
An inspiring PR for these trying times.

**Comment by eeSPee** [comment]
SS13 has been missing out on so many trends! Let's bring it to today with these following features:

* Every minigame is not a match 3 game, because we need to capitalize on the trend and implement 4 currencies.
* SS13 is a roguelike, and some of the progress you did carries over...
* ...as autoclicker factories! Now RP, cargo money, genetics and SM setup is generated automatically depending of the progress of each individual player!
* Instead of doing your jobs on SS13, you are on a open world 30000x30000 map with NPCs that give you fetch quest!
* 4 currencies for minigames; money (earned by playing and paying), extra lives, resets and power points. All these will help your character exceed at his tasks!
* Instead of doing boring SS13 jobs and construction, SS13 is now a class based shooter with interesting classes such as engineer (explosion), scientist (summon mobs), sec officer (robust stun) and many more!
* You actually need to play SS13 in squads of 3 and last squad winning greentexts!
* Each beeshop item is a 1$ - 20$ DLC purchase!

**Comment by february-ops** [comment]
> SS13 has been missing out on so many trends! Let's bring it to today with these following features:
> 
> * Every minigame is not a match 3 game, because we need to capitalize on the trend and implement 4 currencies.
> * SS13 is a roguelike, and some of the progress you did carries over...
> * ...as autoclicker factories! Now RP, cargo money, genetics and SM setup is generated automatically depending of the progress of each individual player!
> * Instead of doing your jobs on SS13, you are on a open world 30000x30000 map with NPCs that give you fetch quest!
> * 4 currencies for minigames; money (earned by playing and paying), extra lives, resets and power points. All these will help your character exceed at his tasks!
> * Instead of doing boring SS13 jobs and construction, SS13 is now a class based shooter with interesting classes such as engineer (explosion), scientist (summon mobs), sec officer (robust stun) and many more!
> * You actually need to play SS13 in squads of 3 and last squad winning greentexts!
> * Each beeshop item is a 1$ - 20$ DLC purchase!

Why cant people use actual money to buy the currency? Very backward thinking

**Review by Archanial — CHANGES_REQUESTED** [review]
We need lootcrates and paid cosmetics

**Comment by PowerfulBacon** [comment]
What about a TTT karma system tolower player damage if they kill non traitors. Also loot boxes would be cool

**Comment by eeSPee** [comment]
> What about a TTT karma system tolower player damage if they kill non traitors. Also loot boxes would be cool

Take it one step further and pull a page from Fallout74; players are invulnerable to damage (PvP disabled) unless a traitor/other player attacks them first.

**Comment by Blueturbo47** [comment]
I like it but I don't think everyone will, I think having some of these in preferences to switch between would be nice.

**Comment by qwertyquerty** [comment]
funny

**Pull request closed without merging**
