### PR TITLE
drip tgstation#56491

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This Pull Request adds an o̶v̶e̶r̶p̶r̶i̶c̶e̶d̶ lavish Swag outfit along with a pair of baller Swag Shoes to go with it. They can be found in the beecoin shop  the perfect outfit for any spessman lacking in the style department.
image
image

The outfit costs 69k beecoins while the shoes cost 31k beecoins, better save your coins if you want to have drip.

Swag Shoes sprited by TWATICUS#0784
Swag Outfit sprited by Dawson#8115
Coded by Jimmy the Suicidal Maniac#3652
## Why It's Good For The Game

Now anyone can secure some bitches. Better yet, maybe the admin will PM your hot ass and stop fuckin' with whatever nukie or captain they're PMing. Also happens to look really cool.

## Changelog
:cl:c420-o, TWATICUS, Dawson, Suicidal Maniac, BeloneX
add: swag outfit available in beecoin shop
add: swag shoes availble in beecoin shop
/:cl:

---

Ports tgstation/tgstation#56491

### CODE REVIEW

**Comment by Isy232** [comment]
Make it like 6.9K or something, I dont want to spent 7/10th's of an antag token to buy 1 cosmetic.

**Comment by heepox** [comment]
> Make it like 6.9K or something, I dont want to spent 7/10th's of an antag token to buy 1 cosmetic.

i would rather make it cost 200k all in total for true drip experience.

**Comment by ghost** [comment]
> Make it like 6.9K or something, I dont want to spent 7/10th's of an antag token to buy 1 cosmetic.

The price for drip is a high one.

**Comment by ToasterBan** [comment]
> Make it like 6.9K or something, I dont want to spent 7/10th's of an antag token to buy 1 cosmetic.

doesn't the EXTREMELY MASCULINE HAT cost the same as an antag token?

**Comment by TeomanTheGreat** [comment]
Speed merge when (this is a very important pr)

**Comment by DatBoiTim** [comment]
If this isn't speedmerged, I will cry

**Comment by Cooliebruv** [comment]
Hell to the yes 
Keep the price as is, make them a luxury item that only the true drip gods that bought the drip full-price can wear

**Review by utilbird — APPROVED** [review]

**Comment by Crossedfall** [comment]
Is this meme still funny?

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
