### PR TITLE
Allows you to tuck the nuclear authentication disk (and plushes) into bed

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Adds an element, the tuckable element. Objects with this element can be tucked into bed by hitting a bed with it.

You can now make beds by hitting them with a blanket.
You can now tuck plushes into bed.
You can now tuck the disk into bed, too.

If the disk is in bed, and tucked in with a blanket, lone op weight will either tick up twice as fast if pop is greater than 20, or half as fast if it's less than 20.
103530288-5f630680-4e44-11eb-9ad4-13b503043ef3

## Why It's Good For The Game

Disky has been on watch for almost two decades, and no one has allowed them to rest. Sleep tight, disky.

## Changelog
add: You can now make beds with blankets.
add: You can now tuck plushes into bed.
add: You can also tuck the nuclear authentication disk into bed. If it's comfortable enough, it might even ward off lone ops. Or it might entice a lone op to come even faster.
/:cl:

Ports: https://github.com/tgstation/tgstation/pull/55940

### CODE REVIEW

**Comment by ToasterBan** [comment]
probably the best thing you have ever coded

**Comment by ghost** [comment]
> probably the best thing you have ever coded

I haven't.

**Comment by utilbird** [comment]
Now captain doesn't have to do their one and only job 😓

**Comment by Sinestia** [comment]
should make lone ops more common as the syndicate show up for the slumber party

**Comment by Penwin0** [comment]
Good pr

**Comment by zeskorion** [comment]
Bad mechanic.  Loneop ticks up when disk is stationary for a reason.

**Comment by ghost** [comment]
- Moved the tucking action to an element and gave it to plushes as well. Still working with the element stuff and figuring stuff out, so it might not be optimal yet.

- If the player pop is over 20, tucking the disk in now doubles the probability of lone op ticking up.

- If the pop if below 20, it halves the probability instead (to avoid low-pop lone op grief).

**Comment by ghost** [comment]
the only based pr belone made

**Comment by PowerfulBacon** [comment]
Stale feel free to reopen when it compiles

**Pull request closed without merging**
