### PR TITLE
Beaker, dropper, bottle syringe and pill bottle resprite

### PR DESCRIPTION
**Pull request by CydiaLamiales**
## About The Pull Request
Ports sprites from
https://github.com/discordia-space/CEV-Eris/pull/6070/
https://github.com/tgstation/tgstation/pull/58760
https://github.com/tgstation/tgstation/pull/58433

## Why It's Good For The Game
The sprites for beakers and bottles are honestly quite flat and tiny, it can sometimes be hard to make out how much they're filled or the color of the filling. This improves the visual clarity of them + generally updates old sprites.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
New pill bottle sprites

image

New bottle, beaker and dropper sprites

image

New syringe sprites

image

image

showcase

Cryostasis beaker sprite

https://github.com/BeeStation/BeeStation-Hornet/assets/110184118/2a9d29d5-b8f1-477e-b166-81257ffe3290
</details>

## Changelog
:cl:CeUvi,Twaticus,maxymax13,PestoVerde322,CydiaLamiales
add: Changing the name/description of a bottle or a beaker now adds a "label" icon to it.
imageadd: Added new Bottle, Beaker, Syringe, Dropper, Pill bottle icons
/:cl:

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
Everything seems fine, but I really don't like the pill bottles. They look awfully like Actimel drink.

**Comment by PowerfulBacon** [comment]
I guess its more convenient, but they do seem a bit weirdly big on the ground

**Comment by CydiaLamiales** [comment]
Updated the pill bottle sprites

image

**Comment by CydiaLamiales** [comment]
Pills updated again
image

**Comment by CydiaLamiales** [comment]
New cryostasis beaker sprite by @PestoVerde322 

https://github.com/BeeStation/BeeStation-Hornet/assets/110184118/2a9d29d5-b8f1-477e-b166-81257ffe3290

**Review by PestoVerde322 — APPROVED** [review]

**Review by Rukofamicom — APPROVED** [review]

**Pull request merged**
