### PR TITLE
Riot Armor resprite

### PR DESCRIPTION
**Pull request by Malgover**
## About The Pull Request

This PR is a resprite for the riot armor.

In a (fake) riot:
riot

## Why It's Good For The Game

The old sprite looked like a plate armor from the Middle Ages. This PR fixes that.

## Changelog
:cl:
fix: resprite of riot armor
/:cl:

### CODE REVIEW

**Comment by Troontjelolo** [comment]
me likey

**Comment by ItsTisme** [comment]
Looks aight, but its alot more lowkey about it being riot armor.

**Comment by Malgover** [comment]
Update:

Shoulder pads are now one pixel higher:
new1
riot2

**Comment by Malgover** [comment]
Final update: made the armor darker and put the NT logo in the back.

new1
new2

For comparison:
old

**Comment by Archanial** [comment]
Good sprite but the title is misleading, it's a resprite not a rework.

**Comment by OceanFish1** [comment]
really patriotic sprite for NT members and the sprite overal is nice

**Comment by Malgover** [comment]
Updated the back sprite:

newer

**Review by PowerfulBacon — APPROVED** [review]

**Comment by SinfulBliss** [comment]
I think the armor would be better lighter. The body looks a lot like bulletproof armor.

**Pull request merged**
