### PR TITLE
Removes the funny word from owospeak

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Removes the funny word.

## Why It's Good For The Game

Funny word is bad.

## Changelog
:cl:
del: owospeak doesn't have the funny word in it anymore
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
more like you're adding it cause it filters it out

**Comment by francinum** [comment]
I believe this dies in the filter on live anyways.

**Review by francinum — APPROVED** [review]

**Comment by ivanmixo** [comment]
Eh still a no no word which github may get mad about

**Comment by francinum** [comment]
s'why I merged it

**Pull request merged**
