### PR TITLE
Ports SCP-012, SCP-151, SCP-173, SCP-294, and SCP-529

### PR DESCRIPTION
**Pull request by ro5490**
## About The Pull Request
Adds SCP-173 plus its relevent effects, sounds, icons and so on.
Admin spawn only currently.

Original creators - JakeDaBoss and Kachnov / https://github.com/SS13-SCP13/SS13-SCP13
Hippie Port by - Toxici11i / HippieStation/HippieStation#12224
Code adjustments by - Ro5490

## Why It's Good For The Game
Big boi horror factor. +admibus memes
012, the music sheet that will make you kill yourself to complete it.
151, the oil painting that will make you vomit water and start to "drown"
173, NECK SNAP
294, want a cup of spewium for no reason? go for it!
529, Just a regular ol cat.... with half a body. shes called josie!

## Changelog
:cl:
add: adds SCP-173
add: adds SCP-294
add: adds SCP-012
add: adds SCP-151
add: adds SCP-529
add: adds SCP Pry-door code to airlocks
fix: fixed Blindness AOE Spell
fix: fixed Statue-code
soundadd: added soundfiles for necksnaps
imageadd: added some icons for SCPs
tweak: changes up the description of infinite pizza boxes
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
SCPs do not belong in ss13 code.

there I said it

**Comment by ro5490** [comment]
Turns out the Travis Cl check bugs out from time to time

**Comment by ghost** [comment]
jakedaboss didn't make shit. it was just Kachnov

**Comment by ro5490** [comment]
> jakedaboss didn't make shit. it was just Kachnov

I just looked at the contribution tab tbh, they've both got a high amount of contribs

**Comment by ro5490** [comment]
merged a pull to the wrong branch so now this pull has all the new SCP stuff that I got working in it...
whelp

**Review by qwertyquerty — CHANGES_REQUESTED** [review]
@ike709 think they should put all SCPs in some isolated SCP directory? I think so

**Comment by ro5490** [comment]
> @ike709 think they should put all SCPs in some isolated SCP directory? I think so

@qwertyquerty On it, pretty quick fix there, any preference where you want the folder?

**Comment by ro5490** [comment]
Done @ike709 @qwertyquerty 

can revert easily if needed

**Comment by ro5490** [comment]
genuinely confused why its failing to build, its building just fine in VSC and running fine via dream-daemon and dream maker ;-;

**Comment by ro5490** [comment]
Analyzing proc bodies...
code/modules/projectiles/projectile/energy/ebow.dm, line 41, column 6:
error: undefined proc: "adjustBrainLoss" on /mob/living/carbon

but... ebow.dm only has 17 lines wtf

**Comment by ro5490** [comment]
TRAVIIISSSS REEEEEEEE

**Comment by ro5490** [comment]
Everything broke due to the new updates. Not sure how to revert, Keep this on ice til the pizza stuff gets reverted
@Crossedfall

**Comment by ro5490** [comment]
Adding Wiki Pages now, not sure how to mark them as drafts due to this not being merged yet though.

**Comment by ro5490** [comment]
https://wiki.beestation13.com/view/SCP-173
https://wiki.beestation13.com/view/SCP_-_Anomalous_Objects

**Comment by ro5490** [comment]
@Crossedfall Wiki pages are up nd working

**Comment by ike709** [comment]
There are a significant numbers of problems still in the code which would require a substantial rewrite, which, to be brutally honest, I don't think you're capable of yet. I suggest working on smaller PRs to get better at DM first.

**Comment by ike709** [comment]
Sorry for wasting your time with the wiki changes, this PR wasn't in a state yet where those should have been requested.

**Comment by ro5490** [comment]
Oof

**Comment by ro5490** [comment]
> merge my scp code for just this weekend I beg
> scp halloween

@ike709

**Pull request closed without merging**
