### PR TITLE
Moves sage back to Asimov

### PR DESCRIPTION
**Pull request by utilbird**
Retiring soon so I'll throw out my last hoorah

## About The Pull Request

Replaces roundstart Crewsimov with Asimov

## Why It's Good For The Game

Crewsimov is a crutch. It negates one of if not the largest downside of playing non-human characters. It pushes races even closer to reskins than actual game modifiers.
Having it enabled by default on an MRP server is counter-intuitive as it deprives roleplay diversity for both the silicon and non-human player. 

The most significant problem with Asimov was griefing behavior towards non-humans from silicons. Something that is much less common and disruptive on a now exclusively MRP codebase. There's no real reason to use Crewsimov over Asimov unless you're either 
A) Completely unable to handle being at an inherit disadvantage because of your own choices and preferences
B) A furry server

The only good argument I've heard against Asimov so far is non-human heads, in which case, tough shit. There's no reason for the AI to actively disobey you unless you're priorities conflict with their laws (i.e harming humans or getting overidden with law 2).
Complaining about the AI not listening as a non-human head is like complaining about getting outran as a crippled quirked HoS

## Changelog
:cl:
config: Changes roundstart lawset to asimov
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
> Something that is much less common and disruptive on a now exclusively MRP codebase

I'll believe it when I see it. This is *far more* of a policy thing than a code thing.

**Comment by Sinestia** [comment]
When you do this, you are stomping on a lot of players.


Which can be worth it sometimes, but I don't think it really is in this case. It won't help the atmosphere much or encourage much RP. From my observation a lot of the better players are non-human playing sec/heads. 

In a blank slate though I'd much prefer this

**Comment by utilbird** [comment]
> I'll believe it when I see it. This is far more of a policy thing than a code thing.

A better way to put it is that it's much easier to enforce the rules on those abusing Asimov on an MRP server. LRP quickly devolves into a game of rule lawyering

**Comment by williamcll** [comment]
This will break a lot of other MRP settings such as a non-human on command/security and discourages gameplay of non-humans. Once the AI on golden decideds it is better to let the SM delaminate rather than letting the moth engineer fix it.

Also conflicts with #4953

**Comment by mcmeiler** [comment]
> Once the AI on golden decideds it is better to let the SM delaminate rather than letting the moth engineer fix it.

That's just a breach of silicon policy though, as the SM detonating could harm humans, unless I'm completely wrong on this.

**Comment by williamcll** [comment]
> > Once the AI on golden decideds it is better to let the SM delaminate rather than letting the moth engineer fix it.
> 
> That's just a breach of silicon policy though, as the SM detonating could harm humans, unless I'm completely wrong on this.

There were no humans on the station at that time.

**Comment by ZombiesVsPlants** [comment]
It works on Austation

**Comment by Kapu1178** [comment]
crossed's pr is much better.

**Comment by ghost** [comment]
Austation has this and it's been doing fine with a population of 33% Felinids

**Comment by amidoingitright** [comment]
you literally have a case study of this working on austation 
your penal colony is far more stable with less rules than the great island you shipped us from

**Comment by amidoingitright** [comment]
> > > Once the AI on golden decideds it is better to let the SM delaminate rather than letting the moth engineer fix it.
> > 
> > 
> > That's just a breach of silicon policy though, as the SM detonating could harm humans, unless I'm completely wrong on this.
> 
> There were no humans on the station at that time.

law 3
ensure your own survival
cant exactly survive when the power is out

**Comment by Sinestia** [comment]
Our rules don't let AIs just be malicious for no reason either

Like if you're purged you can't plasmaflood, you're limited to lavaland escalation and protecting your own freedom

That guy would easily get banned if reported

**Comment by PowerfulBacon** [comment]
The big reason for crewsimov and why its better than asimov is it prevents borgs from validhunting by default. Borgs love to validhunt, and allowing them to do that roundstart is a bad idea.

**Comment by AnCopper** [comment]
Asimov is too valid hunty.

**Comment by Absolutely-Steph** [comment]
Ocasional asimov is good for shaking things up.
Only asimov is a huge fuck you to all races other than humans.
I am not sure if any race is mechanically equivalent to humans, they all have downsides and only a few upsides. This would make it even worse.

**Comment by ike709** [comment]
If we were to dump crewsimov, we would need to replace it with an asimov-crewsimov hybrid that gives preferential treatment to humans but doesn't completely exempt nonhumans from the laws, IMO.

**Comment by Absolutely-Steph** [comment]
> asimov-crewsimov hybrid

So essentially solved by #4956
I don't get why human supremacy isn't frowned upon, or why it's somehow regarded as a good thing? Are the other species only in the game so that players can justify being dicks to someone?

**Comment by PowerfulBacon** [comment]
I believe the prefered option was to enable randomized AI laws

**Pull request closed without merging**
