### PR TITLE
[PORT] TGUI 4.0, Smart Asset Caching, TGchat

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Ports:
https://github.com/tgstation/tgstation/pull/53026
https://github.com/tgstation/tgstation/pull/49982
https://github.com/tgstation/tgstation/pull/52947
https://github.com/tgstation/tgstation/pull/52321
https://github.com/tgstation/tgstation/pull/52323
https://github.com/tgstation/tgstation/pull/52408
https://github.com/tgstation/tgstation/pull/53075
https://github.com/tgstation/tgstation/pull/52280
https://github.com/tgstation/tgstation/pull/53012
https://github.com/tgstation/tgstation/pull/53141
https://github.com/tgstation/tgstation/pull/52233
https://github.com/tgstation/tgstation/pull/52681
https://github.com/tgstation/tgstation/pull/52426
https://github.com/tgstation/tgstation/pull/52085
https://github.com/tgstation/tgstation/pull/52955

Todo:
- [x] Port all the stuff on the project
- [x] Update our specific TGUI interfaces to TGUI 4.0
- [x] Update sending assets on all TGUI interfaces
- [ ] Final check all the ui_interacts to find where the script fucked up.
- [x] Fix asset_cache runtimes which fuck up all vending machines.

## Bee specific interfaces that need updating
- [x] AdminSecretsPanel
- [x] AdvancedAirlockController
- [x] TicketBroswer
- [x] TicketMessanger
- [x] Other stuff that I forgot about
- [x] May or may not have broken youtube.dll

## Why It's Good For The Game

Better loading or some shit, a chat system that is pretty easy to edit and has a lot of potential for formatting changes and looks great and some other stuff too.

## Btw for cooders

Your filepath to the files must NOT contain spaces otherwise asset transport breaks. If you load your .dme to compile your amazing code and all the vending machine icons are broken, remove spaces from your path to the .dme

## Important stuff for Downstreams

Other stuff:
Downstreams read this PR since it has important stuff on it that makes it actually work and stuff **https://github.com/tgstation/tgstation/pull/52681**

## Changelog MrStonedOne, StyleMistake
:cl:
refactor: Browser resources (images/css/javascript) will no longer be needlessly resent to all clients between rounds and reconnections
tweak: Reduced the number of single use html files saved to the Browser Resource folder (tmp12345) on player machines.
add: tgchat: Unread message count is now smarter and won't increase on other tabs if you have already read the same message in the active tab.
add: tgchat: Admin PMs are now properly annotated and can be filtered into separate tabs.
fix: tgchat: Fix: Highlighted message overlay no longer blocks clicks. Clicking a highlighted (F) link should work as it should.
fix: tgui: Fixed NTOS bluescreen due to calling .includes() on a stylesheet href which could be null on certain browsers.
code: tgchat: Chat schema bumped to version 5. All chat-related settings were reset to avoid breakage.
refactor: Interface assets (js/css/images) can now be managed using an external webserver instead of byond's one at a time file transfer queue.
admin: Adds admin verb toggle-cdn that allows admins to disable the external webserver asset transport and revert to the old system. Useful if the webserver backing this goes down (thanks cloudflare).
config: New config file, resources.txt, (must be loaded by an $include statement from the main config)
server: The external_rsc_urls.txt config has been moved to the main config system.
refactor: tgui windows should load faster after an initial load, if using the fancy mode. Please report any breakages.
/:cl:

### CODE REVIEW

**Comment by LordSaladin** [comment]
yes it beats killing your eyes.

**Comment by PowerfulBacon** [comment]
Codewise, everything is ported across, now onto updating every single interface to support TGUI 4

**Comment by PowerfulBacon** [comment]
I have no idea why the asset loading is broken and can't seem to fix it

**Comment by optimumtact** [comment]
do you have an actual website to serve the assets off?

**Comment by PowerfulBacon** [comment]
> do you have an actual website to serve the assets off?

We have a thing with the .zip file for the RSC file

**Comment by optimumtact** [comment]
right, but you need to set up the tgui/tgchat asset loading to serve off a website that the byond server can write to a folder share of, it doesn't magically work out of the box.

**Comment by PowerfulBacon** [comment]
> right, but you need to set up the tgui/tgchat asset loading to serve off a website that the byond server can write to a folder share of, it doesn't magically work out of the box.

Thank you, I have again used my ability of not being able to read and found the porting guide on the original PR, going to see about getting it set up

**Comment by TeomanTheGreat** [comment]
Cool

**Comment by PowerfulBacon** [comment]
so close...

**Comment by PowerfulBacon** [comment]
I think this needs the config to be changed

**Comment by PowerfulBacon** [comment]
- (FIXED) DNA modification console icons are now weird rather than just not there
- (FIXED) Clockwork slab UI is missing the main part
- (FIXED) Night shift lighting always shows as unlocked
- )FIXED) Nuke op antag menu is missing icons
- (FIXED) The new TGUI menu tab selection is ugly
- (FIXED) AI APC thing doesn't work
- (FIXED) Modular computers do not work
- Broken items on some things <-- What does this even mean?
- (FIXED) Secrets panel just doesn't work at all

**Comment by Crossedfall** [comment]
Passed the sniff test in staging. Ready for a TM in production.

**Comment by PowerfulBacon** [comment]
(FIXED GPS apparently is fucked

**Comment by PowerfulBacon** [comment]
(FIXED) Hacking menu is way too wide

**Comment by eLeCtrOssSnake** [comment]
Fix the top right part of the screen being nut on even though I am on the dark theme.

**Comment by eLeCtrOssSnake** [comment]
Crafting is also broken

**Comment by eLeCtrOssSnake** [comment]
Far from being merged. Causes lag, fucks up round reconnect, UI is slow as fuck. Many UI's are broken, unscalable, load slowly. Dark theme is broken. Chat x2 x3 messages are broken.

**Comment by PowerfulBacon** [comment]
[resolved] VV needs asset sending

**Comment by PowerfulBacon** [comment]
Crafting menu works fine

**Comment by VictorVow** [comment]
- Trying to use secHUDs to View Record on someone opens up http://127.0.0.1:42977/tmp287/browseroutput.html?src=[mob_472];hud=s;view=1 in an Internet Explorer browser window. Also trying to change arrest status does the same.
- Door wires pop-up don't open maximised. 
- Getting frequent crashes in BYOND too with this update.

**Comment by TotallyNotChief** [comment]
https://www.youtube.com/watch?v=nZMOom54b2E
after you hit the shock wire, the doors will keep shocking you over and over unless you manually close the hacking window

**Comment by ike709** [comment]
YOLO.

**Pull request merged**
