### PR TITLE
Fixes silicons teleporting intellicards and ID cards using modular consoles

### LINKED ISSUE #5715: Modular consoles and Intellicards
## Testmerges:

#5442 
#5617 

## Reproduction:

1. Place an intellicard in a modular console
2. Have a cyborg use the console
3. Have the cyborg try to remove the intellicard
4. Watch as the intellicard teleports to the cyborg's location

### PR DESCRIPTION
**Pull request by benbot16**
## About The Pull Request

closes #5715 

Currently, when an AI or cyborg ejects an ID/intellicard from a modular console, the console then tries to put the intellicard/ID in the silicon's hand. As silicons don't have hands, the console decides to put the card at the silicon's feet instead, even if said silicon is across the map.

This *should* fix that.

## Why It's Good For The Game

AIs having the capacity to teleport every ID that gets put in a console to the AI core probably isn't intentional. 

## Changelog
:cl:
code: Fixes modular consoles teleporting intellicards/IDs to cyborgs and AIs who try to eject them
/:cl:

### CODE REVIEW

**Review by Archanial — CHANGES_REQUESTED** [review]
This isn't properfix, you should check if user has hands and then put it either in hands or on the floor where console is

**Comment by BrumalLake** [comment]
> 
> 
> This isn't properfix, you should check if user has hands and then put it either in hands or on the floor where console is

i thought that too at first, but the else branch force moves it so it's pretty much dropping it at the object's location assuming that's what drop_location() returns

**Comment by francinum** [comment]
Does this account for telekinesis?

**Comment by benbot16** [comment]
> This isn't properfix, you should check if user has hands and then put it either in hands or on the floor where console is

Right, changed it to something more sensible. This should also cover other ranged stuff too.

**Review by Archanial — APPROVED** [review]

**Pull request merged**
