### PR TITLE
More convenient mining airlocks

### PR DESCRIPTION
**Pull request by PerishedFraud**
Changes mining airlocks into regular ones and adds a tiny fan on the outer airlock. No more pressure issues and long waiting times.
Moves Frank to the otherwise unused old smelting room so he doesn't annoy miners.

Originally used a holofirelock, but tiny fan is better it seems.

Still my first PR, so kindly be lenient with me if anything is wrong.

e

### CODE REVIEW

**Comment by ghost** [comment]
why not just add a tiny fan, it would.look way less ugly.

**Comment by PerishedFraud** [comment]
Tiny fan or not, I'd still take a regular door over the pressure airlocks any day, and I think many would agree with it.

This also has the subtle feature of letting people take shelter from storms in the first room, while still locking the base out. (I mean, technically they can use the tiles with the lights outside of the base but whatever)

**Comment by ghost** [comment]
please just put a tiny fan there instead, the holofan looks out of place

**Comment by ike709** [comment]
Just increase the pressure in the distro loop. Speed is tied to pipenet pressure. Failing that a tiny fan would be better.

**Comment by PerishedFraud** [comment]
Aight, I'll see what I can do. Tiny fan goes on the same tile as door, or inbetween?

**Comment by PerishedFraud** [comment]
Added tiny fan. Seems good!

**Comment by PowerfulBacon** [comment]
mapmerjer

**Pull request closed without merging**
