### PR TITLE
Flandstation fix batch (FlandStation Sp5.2) 

### PR DESCRIPTION
**Pull request by PestoVerde322**
## About The Pull Request

This Pr Fixes some oddities related to a misplaced vending machine, address the broken shutters around brig, implementing some new ones and, after much complaining, the science team got their xenobio console back.

## Why It's Good For The Game

Map fixes are indeed good yes.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

[Unfortunateley, nothing much to see really]

</details>

## Changelog
:cl:
fix: [Flandstation] fixed a cigarette machine in sci being blocked off
fix: [Flandstation] Security shutters are no longer a mess, also added an extra couple of shutters on the side entrance.
fix: [Flandstation] Adjusted some camera position, alognside new standardized fire alarms and speakers.
fix: adjusted a decal using old colors compared to the new one
add: [Flandstation] after much complaining, Science got their xenobio console back, enjoy it while it lasts.
/:cl:

### CODE REVIEW

**Comment by Eric-01** [comment]
Unreachable-medical-records-console
Medbay deck on Fland. The medical records console in the corner and the air alarm behind it are unreachable.

**Comment by Penwin0** [comment]
> Medbay deck on Fland. The medical records console in the corner and the air alarm behind it are unreachable.

This is not related to this PR, please make an issue instead

**Review by Penwin0 — CHANGES_REQUESTED** [review]
Screenshot_1468

There appears to be a hole here

**Review by Penwin0 — COMMENTED** [review]
Changes in chemistry look fine, changes to decals near engi and CE office also look fine.

Xenobiology console looks a bit weird with 2 chairs sharing 1 console, was there always just one?

Changes in science are more than just the console and the smokes vendor, they look fine.

**Comment by PestoVerde322** [comment]
> Screenshot_1468
> 
> There appears to be a hole here

fixed it, leftover from fixing brig stuff

**Review by Penwin0 — CHANGES_REQUESTED** [review]
The fact that you added even more changes pains me greatly.

This decal looks off
Screenshot_1471

**Review by Penwin0 — APPROVED** [review]
Took a while to look at everything, didn't find anything wacky this time though there's a ton of changes

**Pull request merged**
