### PR TITLE
[Port] Food Buffs from the chef

### PR DESCRIPTION
**Pull request by XeonMations**
## About The Pull Request

Adds the system of food buffs. Without the purity shenanigens.

https://github.com/tgstation/tgstation/pull/77887 PR's [HackMD document that is relevant here](https://hackmd.io/@ZSLHD7nTTlWNegwCVVdJBw/ryqRgDluj)

Partially ported TG Station PRs:
- [x] https://github.com/tgstation/tgstation/pull/77887 (Food purity not added in.)
- [x] https://github.com/tgstation/tgstation/pull/78136
- [x] https://github.com/tgstation/tgstation/pull/78481
- [x] https://github.com/tgstation/tgstation/pull/80677
- [x] https://github.com/tgstation/tgstation/pull/81719 (Only the status effect code, since our ice cream code is not new enough to have this applied to it. Add it to the to do list, Tsar-salat!)
- [x] https://github.com/tgstation/tgstation/pull/84889

## Why It's Good For The Game

Adding some small buffs for eating the chef's food is food for more interactions with the chef. Nonantags and antags alike.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Be aware, all testing evidence has doubled lengths due to an oversight that i caught after recording. The issue has been fixed. The proper time for each effect is 5 MINUTES * CRAFTING_COMPLEXITY (1-5)

https://github.com/user-attachments/assets/7295a2ec-15a6-422f-b388-3260d44ae909

https://github.com/user-attachments/assets/fd031610-167e-414b-9a39-631bdc169bc3

https://github.com/user-attachments/assets/22ffbf7b-4853-4cab-8d1b-0ae24c986368

https://github.com/user-attachments/assets/64bf1ffa-16bf-4607-8dd8-a44a32ccb32c

https://github.com/user-attachments/assets/f609d95f-6e9d-4bcc-8b16-3e82e6e85a25

https://github.com/user-attachments/assets/1e1ac471-204b-4f0d-8bde-2e3a99eaa832

https://github.com/user-attachments/assets/a168af43-b3da-4b1a-8c3d-36c7ff83eb94

</details>

## Changelog
:cl: XeonMations
balance: Eating the chef's food now provides small buffs to you.
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
> and replaces the entire system with food buffs instead.

How do you plan to account for differences with reagent purity and sourcing? We don't have the fermichem framework necessary for that.

Overall, I think this could be a very good replacement to what's currently a simple but somewhat unintuitive system, however I think this is necessary to ask early on even if this is just a draft at the moment.

**Comment by XeonMations** [comment]
> How do you plan to account for differences with reagent purity and sourcing?

For now I believe it will be a simple check for if the food was made by the chef for sourcing. 

As for reagent purity, i've decided to have that replaced with food complexity, resulting in more difficult items to give stronger buffs for longer, compared to simpler foods.

**Comment by PowerfulBacon** [comment]
Do better foods get better buffs?

**Comment by XeonMations** [comment]
> Do better foods get better buffs?

Depending on the food, yes. The more complex the food is to make, the better buffs it gives.

**Comment by Rukofamicom** [comment]
I'm entirely confused by this PR, does this actually remove the starvation debuff or is there a complete misunderstanding of what Maltodextrin does?

**Review by Rukofamicom — DISMISSED** [review]
Regardless of the answer, leave maltodextrin as it is.

There are foods available without maltodextrin, such as the cargo pizzas, public garden, directly from botany and otherwise (There are also other options, but these are the ones available to everyone). Maltodextrin serves an important role keeping food relevant as a mechanic in general, and keeping quick fix foods as a quick fix. 

Adding buffs to chef food is a fantastic addition on top of maltodextrin, but removing maltodextrin is not a good move for the game.

**Comment by XeonMations** [comment]
After a talk with Ruko, I've decided to do something completely different.

**Comment by XeonMations** [comment]
Still adding the chef buffs!~

**Comment by Rukofamicom** [comment]
Just to be clear on the resolution of the conversation:

image

**Comment by XeonMations** [comment]
> Secondary PR will be up to remove slowdown from starvation

Secondary PR is https://github.com/BeeStation/BeeStation-Hornet/pull/11771

**Comment by PowerfulBacon** [comment]
With only a single buff, it feels like there's a lot less mechanical incentive to make the more complex food, why bother with cooked food if you can feed everyone with bread?

**Review by PowerfulBacon — APPROVED** [review]
Oh I see each effect has a strength

**Review by PowerfulBacon — APPROVED** [review]
Oh I see each effect has a strength

**Review by Rukofamicom — APPROVED** [review]

**Pull request merged**
