### PR TITLE
New ID sprites

### PR DESCRIPTION
**Pull request by PestoVerde322**
## About The Pull Request

Based on the suggestion of DesertSage on the Beestation discord, I decided to sprite in new sprites for the IDs, making them overall more fancy and whatnot.

## Why It's Good For The Game

The focus of the resprite is to (aside making them look more cool) make the IDs easier to identify based on the job a crewmember have (example, the Virologist have the medical colour, with a green line indicating that they're indeed a virologist).
Also I added more job-dedicated sprites (like Janitors, deputy, lawyers) and gave a sick shine effect on silver, golden and budget cards.

## Testing Photographs and Procedure

<details>

<summary>Screenshots&Videos</summary>

immagine

</details>

## Changelog
:cl:
add: Created new sprites for the IDs, there is also new sprites for dedicated jobs (eg. janitors).
/:cl:

### CODE REVIEW

**Comment by Wilchenx** [comment]
bloat tbh

**Comment by PestoVerde322** [comment]
> bloat tbh

How it bloats? All I do in this PR is new sprites for the IDs and adding some Extra ID sprites which, codewise, it's just a few extra lines.
Sure i could GAGSify this and make it modular in the process but i feel at the same time there isn't much demand for it.

**Review by PowerfulBacon — DISMISSED** [review]
Code and concept are pretty good, I feel like some of the colours don't match up very well and the IDs can look like a lot is going on (The HOPs one for example with 3 non-matching colours)

**Review by PowerfulBacon — APPROVED** [review]

**Comment by yyzsong** [comment]
I really do not like how they are curved.
What's with the black spot at the right?

**Comment by ta3370** [comment]
My mind took the black line on the right to be where you put a Lanyard Clip

**Review by Archanial — APPROVED** [review]
I like them

**Pull request merged**
