### PR TITLE
Boxstation Showers Take 2

### PR DESCRIPTION
**Pull request by LastCrusader105**
## About The Pull Request
adds Showers To boxstations Engineering

## Why It's Good For The Game
slimes, rads , fire, heat, stink all beaten by showers yet boxstation has none

## Changelog
:cl:
add: Added showers to box station engineering
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
129007 changes

**Comment by LastCrusader105** [comment]
I used Strong DMM I dunno

**Comment by ghost** [comment]
Why are you merging from your master?

**Comment by LastCrusader105** [comment]
> Why are you merging from your master?

Cause I’m a tard and I dunno what I’m doing

**Comment by Moccha-Bee** [comment]
@LastCrusader105 bro, delete your master branch fetch it from beestation create a branch based on that master branch and make the changes there. You never make changes to the master branch

**Comment by LastCrusader105** [comment]
@Moccha-Bee i did then I merged it to the master one

I figured I can just delete it and recreate the master at will once it’s added to bee?

**Comment by Moccha-Bee** [comment]
> @Moccha-Bee i did then I merged it to the master one
> 
> I figured I can just delete it and recreate the master at will once it’s added to bee?

That's not how you do it, the master branch is the default branch all other branches will be based on, its kinda like the blueprint for the game, you create changes on another branch that will follow that blueprint and then push it to be made into a pr.

**Comment by LastCrusader105** [comment]
True true but atm I’m just working on this So it’s no issue but I shall do in future
I’m taking Baby steps moccha 😘

**Comment by Moccha-Bee** [comment]
> True true but atm I’m just working on this So it’s no issue but I shall do in future
> I’m taking Baby steps moccha 😘

ask people in disco... you are banned, yes sorry lol.

**Comment by qwertyquerty** [comment]
learn 2 map merge
learn 2 git branch

**Comment by LastCrusader105** [comment]
> learn 2 map merge
> learn 2 git branch

Thank you qwerty, very cool,very helpful

**Pull request closed without merging**
