### PR TITLE
Reverts Detective and Brig Phys antag eligibility

### PR DESCRIPTION
**Pull request by mystery3525**
## About The Pull Request
Partially reverts #3561 (The antag eligibility part) and fully reverts #6372
Additionally, brig phys and detective now both count as security in hostile enemies for all applicable teams/rulesets.

## Why It's Good For The Game

This PR seeks possibly bring the detective and brig physician closer into relevancy by adding a trust layer that can be got behind. I don't have too much of a strong want to have this pulled through, but it would be nice. Meta-protection exists as a consequence of wanting to have an easier trust system and the bubble dynamic that is security vs antags.

As as side note/observation, as an admin with 300 recent ghost hours, I have *seen* people who have zero security hours try to roll detective or brig physician for the possibility of getting an antag, fail to roll, and either do the bare minimum or cryo after 30 minutes, because these roles have been degraded down the the point that they are seen as opportunities for the "bad cop" dynamic and people would only treat them like that, just a food for thought. As a side bonus, maybe if the detective is not treated like a meta-enemy then they will be trusted more to investigate crime scenes.

This will probably require voting.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

idk, look at files?

</details>

## Changelog
:cl:
balance: detective cannot be antag
balance: brig physician cannot be antag
tweak: detective and brig physician are now mindshielded
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
This is a bad idea. Meta protections are bad in general and those two roles aren't security.
🔑

**Comment by PowerfulBacon** [comment]
> This PR seeks possibly bring the detective and brig physician closer into relevancy by adding a trust layer that can be got behind.

How does this bring them closer to relevancy? Their usefulness is the same wether or not they are antag, the difference is that if they are an antag they won't be using their usefullness. If they are irrelevant, then making it so they can't be an antag won't change anything since it wouldn't matter if they are antag or not since their duties are not relevantly needed.

>  Meta-protection exists as a consequence of wanting to have an easier trust system and the bubble dynamic that is security vs antags.

And we want to encourage having an easy trust system and encourage the hard line between security and antags?

> As a side bonus, maybe if the detective is not treated like a meta-enemy then they will be trusted more to investigate crime scenes.

I think this ties into the first point, where if they aren't useful then making it so they can't be antag won't make them more useful. I have seen people hire new brig physicians when the old one turned out to be a traitor which indicates to me that they are useful and are relevant roles, since people are hiring other non-protected crew members to do this job. I've seen detectives be asked for to investigate crime scenes, however I think they are undervalued due to their tooling and equipment, but definitely not due to the fact they are protected from antagonists.

Final things, meta-protection is bad and removes:
 - Questioning whether or not someone can be trusted, before trusting them because you have to for your own sake.
 - The plot twists that come from finding out someone you trusted was actually acting against you this whole time.
 - It reduces the chance for potentially interesting situations to arise from situations where you need more people and are willing to take risks. Without risks, you have significantly less power to your actions and less consequences.

**Comment by DerpiestBruh** [comment]
salt pr

**Comment by EvilDragonfiend** [comment]
Remove brig phys from the roll. How about assigning one during a round?

**Comment by ANAME593** [comment]
> This is a bad idea. Meta protections are bad in general and those two roles aren't security. 🔑

while this is technically true, both of them are usually trusted heavily and can easily access security the detective literally gets a baton + a .38 revolver and if they're a traitor their own syndie uplink, they're even stronger if its a heretic/ling.

Brig phys.
a brig phys can enter the brig, is heavily trusted because its the norm to trust them can obtain sec gear or armory access if sec is understaffed. i think brig phys antags are going to be at a massive advantage then to lets say a antag that isn't command.  maybe we could leave brig phys and let the playerbase learn to treat them like med docs over time.

however det shouldn't be antag he is well equipped and antags shouldn't be  at such a position.

**Comment by PowerfulBacon** [comment]
🔑 Due to points above

**Pull request closed without merging**
