### PR TITLE
Revert "More Crates And Some Changes To Other Crates"

### PR DESCRIPTION
**Pull request by Cenrus**
Reverts BeeStation/BeeStation-Hornet#1610

This PR was poorly balanced. Adding late game tech to cargo isn't a good idea when we have budget cards, you can order advanced surgery tools, bluespace beakers, tools, even uranium for extremely powerful viruses.

Science has some really bad powercreep and making more materials plentiful encourages it.

### CODE REVIEW

**Review by St0rmC4st3r — APPROVED** [review]
The synthflesh pack was intended to be ridiculously expensive in the first place, so I am happy it is back to normal. 
As for the prices going up again, I must mention that we still need to make cargo orderables more affordable, but it is a talk for another PR.

**Comment by Isy232** [comment]
Nothing here is stronger than a maxcap or the fuckery a competent chemist can get up to without anything from science or cargo.

If you have issues with specific crates, why did you not just talk with me when I was making this PR. Some of these crates contained controversial shit, I talked it out with Victor until we agreed on something. I also removed the things that you specifically asked for me to remove.

If there is a particular crate or item in a crate that is an issue, I can PR the change to fix it myself, preferably don't revert everything and let me fix what needs to be done. I'll check back here in a bit.

**Comment by Ohagi-Chan** [comment]
Me and the boys over at austation figured that you could use a destructive analyser to extract the materials from the bluespace beakers, snag the bluespace crystals and sell the rest back to centcom at a mindboggling profit.

By the time you've done this enough to afford a whole cargo shuttle worth of crates, it has become an 80k investment with 120k profits. 150% profit...

Admittedly that's a balance issue with mineral sale values not your crate, but the fact remains that each crate contains up to 7 sheets of bluespace crytal.

**Comment by Isy232** [comment]
Ah, shidt, I tried to balance it, I'll get around to fixing that.

At least it should take time so shouldn't be horribly abusable.

**Comment by ike709** [comment]
Fix the conflicts and I'll overrule the vote and merge it anyways.

The original PR can be remade with less absurdly unbalanced changes.

**Comment by Isy232** [comment]
#1772

Fixing it over there as now I have time, mention any changes you want in my DM's or on that PR and I'll get them done.

**Pull request merged**
