### PR TITLE
[PORT] Spans out and Alphabetizes the Lists in _globalvars/lists 

### PR DESCRIPTION
**Pull request by mystery3525**
## About The Pull Request

Ports: https://github.com/tgstation/tgstation/pull/64018

> On the tin. Every list with two or more variables gets spanned out and alphabetized. Anything that sorta followed this was alphabetized or made to make sense. I didn't alphabetize the directions though, because North/South/East/West makes sense in it's own way.

I believe enforcing an equivalent standard as /tg/ will lead to better maintainability in the long run

## Why It's Good For The Game

> Code improvement, looks better, good comparisons, etc.

(Additionally an optional pre-requisite for some of my other refactor ports)

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

it compiles
image

</details>

## Changelog
:cl: san7890 ported by mystery352
code: _globalvars/lists now has a lot of lists spanned out and alphabetized.
/:cl:

### CODE REVIEW

**Comment by mystery3525** [comment]
FUCK

**Comment by Tsar-Salat** [comment]
Ports:
- https://github.com/tgstation/tgstation/pull/49693
- https://github.com/tgstation/tgstation/pull/60954
- https://github.com/tgstation/tgstation/pull/64018

**Comment by mystery3525** [comment]
now we're good, poisoned the commit history there

**Comment by itsmeow** [comment]
You know this isn't technically a pre-requisite and you could just ignore it

Not every PR that touches another PR has to be ported 😭

**Review by PestoVerde322 — APPROVED** [review]
It's just a shuffle around of codestuff to be more readable and whatnot, not so sure how this ties to https://github.com/BeeStation/BeeStation-Hornet/pull/8556, But it's a good QoL change for reading code. Approved.

**Review by itsmeow — APPROVED** [review]
fine i guess, nothing looks wrong

**Pull request merged**
