### PR TITLE
even smaller felinid buff

### PR DESCRIPTION
**Pull request by That0nePerson**
## About The Pull Request
Felinids now get dusted instantly upon spawning roundstart. This puts them in a much better position than being alive, as they can not die anymore.

## Why It's Good For The Game
image

## Changelog
:cl:
balance: even smaller felinid buff
/:cl:

### CODE REVIEW

**Comment by That0nePerson** [comment]
funny is over

**Review by francinum — APPROVED** [review]
time to game on the furries

**Comment by OceanFish1** [comment]
less gooooo

**Comment by mat-lap** [comment]
speedmerge this

**Comment by TeomanTheGreat** [comment]
Number 1 victory royale

**Comment by yorii** [comment]
uh oh

**Comment by francinum** [comment]
I'll joke and do stupid shit
but the last thing I'm going to actually do is damage the codebase in one of these fits.

**Comment by Archanial** [comment]
Ok

**Comment by TheFakeElon** [comment]
image

**Comment by utilbird** [comment]
image

**Comment by TeomanTheGreat** [comment]
Victory

**Comment by Raven-Industries** [comment]
Keep this in mind next April 1st

**Comment by PowerfulBacon** [comment]
Why the fuck did you merge this lol

**Comment by xNightHowlx** [comment]
### Chong approves.

**Pull request merged**
