### PR TITLE
Adds mute quirk (this time it's neutral)

### PR DESCRIPTION
**Pull request by Hardly3D**
## About The Pull Request
This PR is basically another take for https://github.com/BeeStation/BeeStation-Hornet/pull/5778 but with some changes to fix some of it's biggest flaws, which was it basically being free quirk points for people like mimes.

Adds a new neutral quirk (formerly negative) which makes you mute, PDAs and emotes can still be used just fine however.

## Why It's Good For The Game

We got paraplegic, blind, and deaf available as a quirk, so mute would be a fine addition as it would also be a helpful tool for our mute players, and it would also be good for roleplay as well and even encourage some players to try roleplaying as a mute character.

It will also allow people, especially medical to see that you're actually mute as well as show it up in the records.

The main concern in the original PR was about the mute quirk being negative and giving two quirk points which would allow people, especially mimes to use it solely to powergame quirk points, I decided to make another PR except it's neutral this time so that only people who are actually interested in RPing as a mute will take it instead of muh powergamers who just want the funny points.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Slightly outdated as I had reverted the social anxiety nerf
image

image

</details>

## Changelog
:cl:Hardly
add: Added mute as a neutral quirk
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Social anxiety should probably remain negative, it's a pretty bad one with no way to make it good at all

**Comment by mcmeiler** [comment]
I'd love to see more neutral quirks, and this seems like a decent enough addition, as it won't be powergamed for points this time.

Though, yeah, social anxiety should *probably* remain a negative.

**Comment by EvilDragonfiend** [comment]
if you consider Social anxiety to be abused by mime, I have a suggestion.
Make it mime version - they can't emote when they're anxious. then you can still make it -1.

but also, you can make Mute negative trait as long as the trait takes away mime abilities, or force them to be assistant.

**Comment by Pirill** [comment]
While I'm all for adding a mute trait, the balance changes are frankly stupid and oddly fixated on game balance reasons. This isn't a fault with the PR itself, but rather the community outlook.

First off, there's a real obsession with positive quirks being used to powergame, despite the fact that almost none of the positive ones have any serious impact on the game, yet it's treated like some massive game balance issue. All of that on top of the fact that you're taking a crippling penalty for the sake for RP and flavour.

Which brings up the second point - if mimes use it to "powergame"... then why not fix that instead of penalizing everyone else? Make an exception through code for it, make it mutually exclusive with anxiety, or tweak how that works so it can actually affect mimes too. This just seems like avoiding the actual issue.

**Comment by Wilchenx** [comment]
add sign language to it and it'll be truly neutral

**Comment by Hardly3D** [comment]
Appreciate the feedback, I have reverted the nerf for social anxiety as Bacon and others suggested and so the PR only contains the addition of the mute quirk now.

@Pirill I'll have to admit that you've got a point and that penalizing everyone isn't quite the way for the balance here, though checking and preventing that might be complicated and best fit for a separate PR.

And for other things..

>make it mutually exclusive with anxiety

They are already mutually exclusive to each other

>or tweak how that works so it can actually affect mimes too.

The quirk makes them fully unable to speak, not even breaking your vow or taking mutadone will allow them to speak.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by Rukofamicom** [comment]
> add sign language

Sign language could be its own quirk, similar to bilingual and foreigner. Bilingual could be changed to "Multilingual" and always include sign language for deaf/mute players. 

It would still usually do nothing, but it also currently does nothing most of the time.

**Pull request merged**
