### PR TITLE
adds in a new maint room, the capitalism room

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request

it adds a new maintroom with lots of bling

## Why It's Good For The Game

https://youtu.be/ULeDlxa3gyc

## Changelog
:cl: Jimmy Brickets
add: a new VERY fancy maintroom
/:cl:

### CODE REVIEW

**Comment by OceanFish1** [comment]
good but that conflict........

**Comment by ghost** [comment]
There are already way too many maint rooms that give you free money, ingame wages and economy are invalidated if you can just find hundreds or thousands of credits walking around in maint. And the sunglasses, which are also way too common in maint rooms

**Comment by ToasterBan** [comment]
I have 0 idea why this is conflicting

**Comment by PowerfulBacon** [comment]
Good PR but stale, feel free to reopen

**Pull request closed without merging**
