### PR TITLE
Batch Of Boxstation Touchups

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
((I meant gravity generator in the first commit, I'm dummy brain.))

Touches up Boxstation and fixes a bunch of scattered issues. Isn't *quite* as polished as, say, fland - but brings it closer to modern standards.

Fixes:
A bunch of rogue /area/space/nearstation placements
Some misplaced (or simply not placed) wiring
The lawyer's office's snowflake APC and /area/ placement
Telecomms only being half-shocked
The gravity generator having a stray wire leading *just* shy of it's SMES unit
Some rogue cyclelinks that weren't removed properly

Noteworthy yet minor changes:
All maintenance /area/s now take priority over the others. In practice, should make radstorms look a lot less weird (And also give breaking / hacking maintenance APCs a use for antagonists other than slowing pursuit)
A lot of firelock windows have been spread around the map. This is mostly used to protect Central Primary, Arrivals, the SM, and Atmos Air Tanks. It *does not* protect Escape, because hijack does not need to be made harder (And it's, arguably, not worth it)
The space bridge under xenobiology has, unfortunately, had to be given firelocks to properly separate the two maintenance /area/ types down there. I couldn't fit in a more elegant solution thanks to the mess of disposal pipes down there.
A lot of abandoned airlocks have been edited to no longer reference their original, non random maint purpose, or simply to no longer be a hassle to use - (Who thought three layers of wooden planks would be good for an airlock when someone can weld through faster? Wack.)

Adds:
The explorer prep room has been remapped, ever so slightly. You can play Unum while the other guy probably dies because he left early!
Gravity Generator has been remapped to get rid of a stray wire and bring it up to speed with the other maps. While it's not on the grid roundstart, it *does* have a PACMAN and plasma ready to go in the event it's ever needed - say, a sneaky EMP.

## Why It's Good For The Game
Box is drifting out of date of the other maps - especially Fland, which is leaps and bounds more modern than some of the other maps still in rotation. This helps bring it partially in line without stripping the soul out... entirely.

## Testing Photographs and Procedure

<details>

<summary>Screenshots&Videos</summary>

image

Lawyer's Fix:

image

Telecoms Fix:

image

Gravity Generator's Fix:

image

Maint Taking Priority:

image

Window Firelocks in relatively sane spots:

image

My regrets (But it had to be done):

image

Saner Abandoned Airlocks:

image

Explorer Office:

image

</details>

## Changelog
:cl:
tweak: The explorer prep room on Box has been altered to be a tad less.. strange.
tweak: The boxstation gravity generator no longer has a stray wire leading just shy of the SMES unit - said wire being removed in favor of a PACMAN on-site, should it ever be needed. It won't - unless someone tampers with the thing.
tweak: The lawyer's office APC has been moved inside, and no longer relies on mapper magic.
balance: Maintenance tunnels now take priority over other areas on Boxstation, meaning all connected airlocks are on the maintenance's power rather than where they lead's - minus a few edge cases in the solars and incinerator.
balance: A few windows on Boxstation now have firelock windows under them, for double window action!
fix: Box's Telecomms' windows now properly shock you wherever you break in.
fix: Box no longer has a bunch of rogue radiation patches where no lattices are.
fix: Box ALSO has had some rogue cyclelinks removed, so that they won't runtime roundstart. Honk.
fix: Aft maintenance on Box no longer has magic power.
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
Screens from map editor will do. Ping me when you add them 👍

**Comment by unit0016** [comment]
@Archanial yea, it's added now.

**Comment by Archanial** [comment]
Those screens are good but in the future try marking the changed areas somehow

**Comment by unit0016** [comment]
Conflicts after I nuked the repository from my machine 💀

**Pull request closed without merging**
