### PR TITLE
Adds request consoles to every department

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
Every department now gets a request console.

## Why It's Good For The Game
Cargo is rarely used unless the gamemode demands it, so this encourages more orders to be made by allowing crew to order things from within their own department.

## Changelog
:cl:
add: Request consoles in every department.
/:cl:

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
@Victor239 can you make them place orders from the department's respectful budget?

**Comment by VictorVow** [comment]
@St0rmC4st3r I'd like it to supplement RP interaction not bypass it completely, they can ask their nearby Head of Staff to borrow the budget card instead.

**Comment by qwertyquerty** [comment]
Fix conflicts

**Comment by VictorVow** [comment]
@qwertyquerty fixed

**Pull request merged**
