### PR TITLE
Nerfs beepsky

### PR DESCRIPTION
**Pull request by imsynthex**
## About The Pull Request
Changes beepsky's damage so that it now does 85 stamina [damage] to the chest each hit, meaning you can take 2 hits unarmored before going down, beepsky's hits will now also respect armor that protects you from stamina damage.

## Why It's Good For The Game
It's become commonplace to see people dragging a beepsky behind them just because of how powerful they are, bots are generally meant to do things worse than humans, not the other way around. Mind you, this does not make them loot piñatas, as they will still take out pretty much anyone in 2 hits.

## Testing Photographs and Procedure

https://user-images.githubusercontent.com/81387903/229309057-eae32f94-7633-4e93-acb6-8434765e4bae.mp4

## Changelog
:cl:
balance: Beepsky now does 85 stamina damage a hit
balance: It will now take 2 hits from beepsky to down an unarmored target and beepsky's hits will now be softened by armor that protects from stamina damage
/:cl:

### CODE REVIEW

**Comment by CydiaLamiales** [comment]
Ided pr?

**Comment by imsynthex** [comment]
I don't remember the last time I got owned by beepsky, not ided

I think you also wholly missed the fact that making beepsky undraggable would not fix the problem, beepsky would still be able to take out anyone, regardless of armor in 1 hit, that is not good game balancing especially considering how cheesy some beepsky hits are

**Comment by WrillWasTaken** [comment]
Projectiles should also not pass over beepsky IMO

**Comment by DarnTheMarn** [comment]
In Bacon's own words:

> Threats and antagonists should take a significant amount of time and effort to deal with. On the flip side, threats and antagonists should have a hard time dealing with the people trying to stop them. Anything that results in instant wins in combat should be heavilly discouraged. 

quoted from [https://github.com/BeeStation/BeeStation-Hornet/wiki/Design-Goals](url)

One by one the the one hit stuns fall.

**Comment by llol111** [comment]
Noooo not beepsky 😢 
something something removing soul and tradition
cringe pr

Joking, mostly.
Personaly dont _realy_ see the need here, though i agree beepsky dragging is supreme cringe.

Thinking about it properly, making it no longer an instant hardstun would be good, that is pretty cringe.
But personaly i'd still like for beepsky to hit ya with it *immediately* as you get in his range, without that delay you seem to have added. 1 hits are cringe, but if im seeing it right in that preview it will be fairly trivial to run away from beepsky now.
Idealy (imo), it should smack you right away with a good chunk of stamina damage to leave you stumbling and slow. So that you dont *totaly* get fucked for being near beepsky as a wanted man, but its still punishing.
Getting hit second time could then be what is now first hit

Just my thoughts 🤷‍♂️ 
Just my thoughts.

**Comment by imsynthex** [comment]
> without that delay you seem to have added

Nothing was changed in that regard, that's just how beepsky AI is, sometimes it'll manage to seemingly hit you from 2 tiles away, sometimes it'll stand next to you for a second without doing anything, I don't plan to touch it either in this PR

**Comment by llol111** [comment]
aight then im just an idiot. Should be fine then.

**Review by itsmeow — APPROVED** [review]
Yeah, beepsky's ability to insta-paralyze is super cringe and completely ruins any chance of beating him. You have to have a ranged weapon AND click directly on beepsky from afar in order to stop any attack, making Beepsky a near-perfect defense, most especially Armsky, who the only decent solution to is using an EMP. You also have no chance of escaping Beepsky because on detain mode he can just chain-stun you into oblivion. Now you can potentially use adrenaline or crawl away ever so slowly rather than being trapped in a chainstun till you die or something.

I've always thought that beepsky was far too powerful for requiring absolutely zero control or modification.

**Review by Penwin0 — APPROVED** [review]
I like the change balance wise, and you are blessed for cleaning up that ugly ass code while you were there

**Pull request merged**
