### PR TITLE
Pubby Improvement: Science

### PR DESCRIPTION
**Pull request by imsynthex**
## About The Pull Request

There was a hallway running right through Science on Pubby which allowed people to easily tide into the RnD lab and Robotics, this PR just makes it more like Meta, Delta and Box

New Science 😳
image

## Why It's Good For The Game

Pubby bad, this makes Pubby slightly less bad

## Changelog
:cl:
tweak: Fixed the hallway running through Science on Pubbystation
add: Added a nanite lab to Pubbystation Science
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
image of path to engineering please

**Comment by imsynthex** [comment]
image

**Comment by PowerfulBacon** [comment]
are the nav beacons moved to account for the hallway not being public?

**Comment by imsynthex** [comment]
They are now

**Comment by imsynthex** [comment]
Thank you Github, very cool

**Comment by williamcll** [comment]
Doesn't really change much does it? people can still break through the front desk which they normally do on pubby. 

I really love the nanite lab addition however.

**Comment by imsynthex** [comment]
If they try and break through the front desk you can just close the shutters on them as opposed to how it used to be where there's no airlock to keep tiders from just walking in and stealing something

**Comment by Sinestia** [comment]
oh, did you fix the door access on the RND door?

**Comment by imsynthex** [comment]
Thought the default pubby access was okay, checked it, really wasn't, should be good now, will try and fix the merge conflict, society 😔

**Comment by Sinestia** [comment]
> 
> 
> Thought the default pubby access was okay, checked it, really wasn't, should be good now, will try and fix the merge conflict, society 😔

Yep, the RD's door was a mere suggestion. 

Tyvm.

**Comment by imsynthex** [comment]
Likely a issue with map diff bot being dumb, closing, if creating a new PR doesn't work, will reopen

**Comment by BrumalLake** [comment]
it says theres a merge conflict cause it checked, it wouldnt mark it if it blocked

**Comment by imsynthex** [comment]
I am dumb and didn't know that

**Comment by imsynthex** [comment]
I have literally no idea what I just did...

**Comment by imsynthex** [comment]
Ah I see, it included every PR from the last 10 days. Scuffed PR moment

**Comment by imsynthex** [comment]
Okay so here's the thing, I'm actually opening another PR for this because I need to delete my whole repository and redo it, and now, for an ad break

**Pull request closed without merging**
