### PR TITLE
Standardizes the medical intercoms to a new subtype

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
Moves the medical intercoms to a new subtype instead of just being map-edited intercoms, adds the medical radio color and a unique descriptor to the frequency

## Why It's Good For The Game
Medical Intercoms are weirdly hacky at the moment, with the same frquency and name being copied between all of them. Standardizing it makes it both easier to spot among common and gives it more professionalness

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image
image

</details>

## Changelog
:cl:
tweak: Medical Intercoms are now a proper subtype, and the frequency for it has a unique name
imageadd: Medical Intercom sprite
/:cl:

### CODE REVIEW

**Comment by etherware-novice** [comment]
to...have the medical intercoms not just be a varedit? i dont get what you mean

**Comment by EvilDragonfiend** [comment]
> to...have the medical intercoms not just be a varedit? i dont get what you mean

How would people use this? Why should we have this?

**Comment by etherware-novice** [comment]
this pr helps the intercom to feel more unique, and stand out against common ones. its really hard to tell sometimes whether a message is from the medcomms, or common looking at them side by side, since unnamed frequencies use the common radio span. it also helps mappers, being able to quickly place down a medradio without having to find an existing medradio and copying the frequency and name. ALSO, if the medradio EVER needs to be changed, or have a new proc or feature added, it would be incredibly frustrating to go through every .dmm and manually vv every. single. intercom. when for any other similar change, you could simply go into the subtype code, and change a FEW LINES to apply it globally. AS WELL, new coders might be extremely confused with how the medical intercoms are coded right now, not following the organizational rules of every single other item in the game. Manual variable editing in maps should be used for one off name changes, pixel shifting, or other similar senarios where the changes should only apply to THAT SPECIFIC ITEM. Even implying that it would be pointless to keep the current system, of just copying the name over, destroys the entire point of map var editing and makes it extremely convoluted for anyone to go and change it, when it shouldnt be. ALSO, new players are way more likely to understand "Medical Interior" immedietly when they're, yk, IN MEDBAY. Suddenly seeing messages from 1485 in chat, especially if they didnt know what custom frequencies are, would confuse that new player into believing those messages are from common due to the similar appearance. Making the distinction clearer also indirectly teaches them about different radio frequencies, letting them learn the game quicker. This pr would be a net positive for literally everyone.

**Comment by etherware-novice** [comment]
also, keep in mind that even the chapel's intercom has a dedicated subtype, and thats far less frequent and also only changes a few variables.

**Comment by itsmeow** [comment]
> How would people use this? Why should we have this? What did you think from adding this? I have zero clue of those from this PR.

This PR is fine, varedits on maps are generally considered bad practice.

**Review by itsmeow — DISMISSED** [review]

**Pull request closed without merging**
