### PR TITLE
Reverts some monstermos-era changes

### PR DESCRIPTION
**Pull request by Tsar-Salat**
## About The Pull Request

Reverts:
- https://github.com/BeeStation/BeeStation-Hornet/pull/1922
- https://github.com/BeeStation/BeeStation-Hornet/pull/2244
- https://github.com/BeeStation/BeeStation-Hornet/pull/3079

Reverts several monstermos-era changes.

## Why It's Good For The Game

All of these changes staked their existence on "cuz monstermos". Well, its 3-4 years later and we don't have that anymore, so any system changes we were "accounting for" back then should not be slipping into the new system we want to transition to.

Whether any of them have merit, they should be in their own pr with good *new* reasoning.

The last one might actually be a fair change, so I've just found a middleground between the old and monstermos values so it actually appears atleast once in player's lifetimes.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Compiles.

image

</details>

## Changelog
:cl:
tweak: reverted change to air pump value set default
tweak: reverted change reducing holodeck plasmafire volume
balance: Upped weight and lowered minimum playercount for Energetic Flux anomaly to appear
/:cl:

### CODE REVIEW

**Review by Rukofamicom — COMMENTED** [review]
> Whether any of them have merit, they should be in their own pr with good new reasoning.

So does this PR.
Why does this PR have merit and what does it do to improve the game?

Please update the PR body with an actual reason this PR is good for the game. Even if the original PRs wouldn't be necessary now, neither is adjusting them back as far as I know.

**Comment by Rukofamicom** [comment]
This will be marked stale in two weeks time if the above question is not answered and the "Why it's good for the game section" not updated.

I'm not strictly against the changes, just the very lacking reasoning given for them. Flux anomalies have genuinely been so rare I've not seen one outside of the one I spawned, but I don't know why making them more common is a good thing necessarily either given how destructive they are. Being admin spawn might be good enough.

**Comment by Rukofamicom** [comment]
image

**Comment by Tsar-Salat** [comment]
Needs more red arrows pls

**Pull request closed without merging**
