### PR TITLE
Makes the telescreen UI activate on examine rather than click

### LINKED ISSUE #4783: Entertainment Monitors can be activated from a distance

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Title. You also need to be next to it to change the channel instead of just doing it telepathically. Closes #4783, I guess. Using them from a distance is intentional, this makes it less shit.

## Why It's Good For The Game

Clicking on it in the middle of combat and having it lag your client is really annoying.

## Changelog
:cl:
tweak: entertainment monitors now need to be examine to toggle the UI instead of clicked
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
Didn't even touch tgui....

**Comment by ivanmixo** [comment]
?tgui rebuild

**Comment by ivanmixo** [comment]
?rebuild tgui

**Comment by AnCopper** [comment]
Certified webedit moment.

**Comment by ivanmixo** [comment]
not webedits though

**Comment by Sinestia** [comment]
> 
> 
> Certified webedit moment.

sometimes verified shows up because they properly had set up their GPG ;) ;) ;)

**Comment by ivanmixo** [comment]
did that 😎

**Review by Sinestia — CHANGES_REQUESTED** [review]
You only apply it to one telescreen, a semi-rare one at that which is in the library and mostly lounge-type rooms IIRC. 

At the very least, you probably want to apply this consistently.

**Comment by ivanmixo** [comment]
> You only apply it to one telescreen, a semi-rare one at that which is in the library and mostly lounge-type rooms IIRC.
> 
> At the very least, you probably want to apply this consistently.

I'm pretty sure it's the only one that opened *on click at any distance*, which was my main issue with it.

**Comment by Sinestia** [comment]
> 
> 
> > You only apply it to one telescreen, a semi-rare one at that which is in the library and mostly lounge-type rooms IIRC.
> > At the very least, you probably want to apply this consistently.
> 
> I'm pretty sure it's the only one that opened _on click at any distance_, which was my main issue with it.

Good point

**Review by Sinestia — APPROVED** [review]

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
