### PR TITLE
Increased nanite program limit

### PR DESCRIPTION
**Pull request by That0nePerson**
## About The Pull Request
Ups the nanite program limit from 20 to 30

## Why It's Good For The Game
The program limit has always felt very low, taking into account the number of triggers needed for advanced things, along with all of the passive healing programs. This cap feels even more limiting with #2047 and without this, many of those programs may go unused

## Changelog
:cl:
balance: nanite program limit changed from 20 to 30
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Nantes are already insanely overpowered, I dont think letting people have even more range of overpowered nanites is a good idea

**Comment by Tamuren** [comment]
This is a good idea. Certain programs are left on the cutting room floor because of the 20 program limit. In my build, I can't have defib, dermal hardening, or dermal refractive surface because there's not enough program slots.

**Comment by MNarath1** [comment]
yeah nanites already have a limiter thanks to nanites beeing used up for most active programms the only thing that would really change is that you could make more complex nanite programms trough those would still be limited naturally by their own nanite consumption rate. I actually made an issue quite some time ago about this as i really wanted to try a certain combination but i hit the program cap so no can do.

**Comment by ghost** [comment]
I think it's a great idea

**Comment by PowerfulBacon** [comment]
> 
> 
> This is a good idea. Certain programs are left on the cutting room floor because of the 20 program limit. In my build, I can't have defib, dermal hardening, or dermal refractive surface because there's not enough program slots.

That would be ridiculous having all of them at once, and personally I really don't think this should be raised.

**Comment by That0nePerson** [comment]
you still couldn't have them all active at once, the person who has the nanites would still be responsible for turning them on/off and managing usage. If anything, we should have a vote due to conflicting opinions

**Comment by Isy232** [comment]
Nanites are beatable by finding the hub they run on and deleting the programs or uploading bad ones.

Or use an EMP.

Almost everything nanites can do something else can do better, nanites are just all of that in one easily distributable package.

A program limit is a stupid way to cap the strength of nanites, almost all nanite programs consume nanites to function and this is already very limiting.

If someone spends 30 minutes programming some nanites they deserve to be as powerful as a mech, shotgun, chem stuffs or some xenobiology stuffs.

Then if you distribute them to everyone you do not have any advantage unless if you slipped in some neural shock program of course.

I agree with putting this to a vote.

**Comment by PowerfulBacon** [comment]
I've seen nanites done 5 minutes into the round that generate a shit ton of research points. I just want to see what ike thinks about this, since nanites are already one if the most powerful things in the game science can do.

**Comment by That0nePerson** [comment]
I've seen servers made 5 minutes into the round that generate a shit ton of research points

**Comment by PowerfulBacon** [comment]
Servers are a lot harder to do and dont have the added benefit of giving you the added benefit of people having changeling level powers such as adrenaline, self healing. The cap is low at 20 for a reason since they already give essentially near antag powers in a few minutes. The only abilities in science that come close to this is xenolings and they only have 3 points and take at least 40-50 minutes to do if you get lucky.

**Comment by That0nePerson** [comment]
servers are very much not harder to do, just turn off xenobio freezer and make some machines, though you do make good points on the antag abilities, but most departments get much better stuff than nanites in endgame, and nanites can _extremely easily_ be subverted by an antag, and used as a killing tool, so they come with a lot of risk and opportunities for traitors

**Comment by Tamuren** [comment]
Nanites are primary limited by their finite volume - more program slots will allow more sophisticated manipulation of that volume, but not give more viability to running multiple concurrent programs.

**Comment by Isy232** [comment]
> Servers are a lot harder to do and dont have the added benefit of giving you the added benefit of people having changeling level powers such as adrenaline, self healing. The cap is low at 20 for a reason since they already give essentially near antag powers in a few minutes. The only abilities in science that come close to this is xenolings and they only have 3 points and take at least 40-50 minutes to do if you get lucky.

It has a 120 second cooldown too, but even then it is somewhat OP. Perhaps nerf this ability individually, like split it into 2 abilities, one overloads your muscles, giving you super speed but brute damaging your legs and one to instantly reboot your nervous system, with the downside of brain damage.

Both of those types of damage could he healed with nanites, but then they would have to spend a fair bit more time programming.

Then the healing. The self healing is like a virologists healing disease except vulnerable to EMP and reliant on you having enough nanites in your system. I'd say its balanced compared to other things.


I think nanites shouldn't be limited by a program cap at all and instead just apply nerfs to certain programs.

Also, what Tamuren said.

**Comment by eLeCtrOssSnake** [comment]
I would like it to be somewhat of top nanite research node, not just value change by default.

**Comment by ike709** [comment]
nanites are overpowered, other things being overpowered is not justification for it to be more overpowered

**Pull request closed without merging**
