### PR TITLE
Changes NanoMed and NanoMed+ stock

### PR DESCRIPTION
**Pull request by Rukofamicom**
## About The Pull Request

This PR is intended to accompany an upcoming PR by @Archanial which will merge the Sleepers and Cryopods into one machine which will begin the round well-stocked with healing chems.  

### NanoMed (Wall Machine)
**Removes**
* Brute Patches
* Burn Patches
* Bicaridine Pill Bottles
* Kelotane Pill Bottles
* Styptic Powder Spray
* Silver Sulfadiazine Spray

**Adds**
* Medical Gauze x4
* Epinephrine Medipen x3
* Dexalin Medipen x3
* Epinephrine Bottle x2

**Changes**
* Charcoal Pills x2 -> Bottle x1
* Contraband Toxin Pills x2 -> Bottle x1
* Contraband Morphine Pills x2 -> Bottle x1

### NanoMed Plus (Vending Machine)
**Removed**
* Brute Patches
* Burn Patches
* Bicaridine Pill Bottles
* Kelotane Pill Bottles
* Psicodine Pill Bottles
* Styptic Powder Spray
* Silver Sulfadiazine Spray
* Synthflesh Spray
* Advanced Medkits *
* Insulin Pills
* Salbutamol Pills * *
* Contraband Morphine Pills
* Contraband Charcoal Pills

**Added**
* Empty Medical Sprays x6
* Empty Pill Bottles x6
* Empty Glass Bottles (30u) x10
* Space Cleaner x1
* Dexalin Medipen * * x8
* Tricordrazine Bottle x1
* First Aid Kit (basic) x3 *
Contraband Chloral Hydrate Bottle

**Changed**
* Epinephrine Medipen x3 -> x8
* Epinephrine Bottle x3 -> x4
* Morphine Bottle x4 -> x2
* Saline Glucose Bottle x3 -> x4
* Toxin Bottle x3 -> x4
* Spaceacillin Syringe x6 -> Bottle x1

### Misc Changes
Adds bottles for Tricordrazine and Spaceacillin
Changes the bottle icon for Saline Glucose to match the other chemical bottles

## Why It's Good For The Game
The sheer volume of good medicine available from these vendors devalues medical staff immensely. Why use a doctor when you can just treat yourself - and why let a doctor treat you when you can scream at them to just grab a patch from that machine over there?

This also greatly increases the stock of available epi pens, which there never seems to be enough of and aren't easy to restock once you run low. 

## Changelog
:cl:
add: Added bottles for Tricordrazine and Spaceacillin
tweak: Both varieties of NanoMed now stock primarily emergency and basic supplies instead of overabundant healing supplies
/:cl:

### CODE REVIEW

**Comment by Rukofamicom** [comment]
## Before someone cries about how much of a nerf this is to miners, I'd like to remind everyone of this: 

image

**Comment by ToasterBan** [comment]
keep the synthflesh please, its pretty much our only way of dehusking corpses

**Comment by Sinestia** [comment]
> 
> 
> keep the synthflesh please, its pretty much our only way of dehusking corpses

making it yourself, cargo, maybe even rezadone

you've got a variety of sources

**Comment by Rukofamicom** [comment]
Synthflesh is the single thing I go to get from cargo almost every round as medstaff. It's quite cheap for how much you get, and it sure beats building a massive factory or manually making it yourself, but even the latter option doesn't take much time with a willing blood donor (or monkey)

**Comment by PowerfulBacon** [comment]
the only stuff thats really useful in there is the disease curing stuff

**Comment by St0rmC4st3r** [comment]
Maybe leave spaceaciline in, or will it be in the cryosleepers?

**Comment by Rukofamicom** [comment]
> the only stuff thats really useful in there is the disease curing stuff

Epi pens are very useful, and usually in short supply - notice how many more there are in it now?
Medkits heal a *lot* of brute/burn and didn't used to be available from the machine
Dexalin pens are quicker to use than pills (but also weaker)
Charcoal heals a small degree of toxin damage and purges chems
Saline Glucose heals brute/burn and restores blood volume
Tricordrazine heals all damage types
Toxin is necessary for niche reasons to chemistry

Everything in the machine is useful, it's just that the "best in class" stuff was removed. No more overstocked ultra-fast acting patches or atropine injectors. 

> Maybe leave spaceaciline

> Also adds a bottle for Tricordrazine and **Spaceacillin**

Spaceacillin is still there, it's just in bottle form instead of syringe.

**Comment by ItsTisme** [comment]
Epi is pretty damn hard to make. Which is why no one bothers to make it. Its more effort then atropine and atropine even heals you out of crit(granted jitter happens)

**Comment by Naevii** [comment]
I really like the proposed changes, especialyl empty pill bottles and sprays.
I think it will be a good improvement for a medical. 
Maybe people will finally stop going straigh to vendor rather than to doctors.

**Comment by ToasterBan** [comment]
i just realised this is a huge miner nerf due to removing a lot of the healing stuff from emergency nanomeds

**Comment by Penwin0** [comment]
This change is long overdue, you shouldnt be able to just go to a vendor and completely bypass the medical doctors job

**Review by ike709 — DISMISSED** [review]

**Comment by francinum** [comment]
It's unclear to me what exactly has been changed, considering you also reordered the lists.

**Comment by Rukofamicom** [comment]
Added a more detailed Changelog

Should note that I forgot to swap the toxin pills in the contraband list for NanoMed Plus - but it's not really that huge of an issue

**Comment by OceanFish1** [comment]
no more spray meta bruh reel nerf times..................

**Comment by FlamePrince** [comment]
>Tricordrazine Bottle x1

_trekmed happy noises_

From my experience there is usually no lack of medical staff available that constitutes the need for NanoMeds to be so stacked. Medical can be boring as is without most ambulatory boo-boos walking in, availing themselves of our supplies and walking out. While all of my medical hours are on Golden, I'm sure this will encourage more roleplay and engagement in MRP.

i also see the makings of making medbay a more prominent target for the greytide on golden as people can no longer get their powergame meds from our doorstep.

**Review by utilbird — APPROVED** [review]

**Pull request merged**
