### PR TITLE
Fixes oversight in explorer medkit loadout

### PR DESCRIPTION
**Pull request by Rukofamicom**
## About The Pull Request

Exploration medics now spawn with their medkit in their hand instead of in a bag it shouldn't fit inside of. 

(This fix has been isolated from what the PR originally was - the first few comments below are not going to make sense)

## Why It's Good For The Game

Fixes unintended behavior that was overlooked when changing the size of medkits

## Testing Photographs and Procedure

image

## Changelog
:cl:
fix: Exploration medics will spawn with medkit in hand instead of in their bag where it shouldn't fit
/:cl:

### CODE REVIEW

**Comment by Rukofamicom** [comment]
Please do not merge this before the linked PR - ideally it should be merged at the same time.

**Comment by Pirill** [comment]
My only issue with this is that the labcoat/jacket's suit slot _is_ a relevant spot to keep a medkit in, the main issue was when you had to take it off (which is addressed by the other PR aiming to make them holdable on a belt) for EVA/explorers/fashion reasons.

If anything I'd like to see both options. Anyone who wants to powergame a medkit can give up their belt slot for it, but medics can have two options that way, especially since they need to juggle potentially 3 belt items this way (surgery kit, med belt and compact defib) on the same slot and it represents an extra bit of tradeoff for those who want to wear non-MD clothing and still be able to carry the kit.

**Comment by Rukofamicom** [comment]
The goal is to limit even medical staff to a single medkit at a time instead of two. Medics should certainly be prepared for their job, but we wanted to move away from players being able to easily have all their bases covered at once remotely. In the medbay you're always a short walk away from med storage or the chemist who can mix something up for you if they haven't already. 

When **not** in the medbay, the medic shouldn't have everything ready to go because they took one of everything from med storage (and in doing so, prevented the rest of medbay from utilizing those items in their absence)

---

I pushed for the extra large medkit to be part of the belt slot items so the actual medical staff would still retain some extra capacity compared to crew that just picked up a medkit, whether they want to use that for surgical tools, or otherwise.

**Comment by Rukofamicom** [comment]
Reopening this for the bundled fix.

**Review by Penwin0 — APPROVED** [review]
I'd say only merge after #9323 is in

**Pull request merged**
