### PR TITLE
Spirit realm ghosts can no longer contribute towards summon nar'sie

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Spirit realm ghosts no longer contribute towards the apocalypse rune, or the summon nar'sie rune.
Also throws in a pretty minor fix to battle of gods (unused). Would do it seperately, but its pretty irrelevant to the game.

## Why It's Good For The Game

5 cultists can win the game by summoning 4 ghosts via spirit realm. This allows cult to summon nar'sie even when their hold on the station is basically non-existant.
This forces cultists to have a decent hold of the station before they can activate their final rune.

## Testing Photographs and Procedure

image
Tested this along with user activating it, and then the updates to the spirit realm. Turns out that the status effect never got applied before, which is great.

## Changelog
:cl:
balance: Spirit realm ghosts can no longer summon nar'sie
balance: Spirit realm ghosts can no longer apocalypse
fix: Fixes battle of the gods ending not summoning nar'sie on clockcult defeat.
fix: Fixes cult ghosts being able to summon more cult ghosts due to a bug in the status effect.
/:cl:

### CODE REVIEW

**Comment by Oscari-pog** [comment]
ided label

Also if you let them draw the Narsie rune when they are at their weakest thats your fault really, you get a huge blaring announcement whenever they start drawing it.

**Comment by PowerfulBacon** [comment]
The announcement means basically nothing, you get like 40 seconds to respond to it and often can't get past the barrier runes.

**Comment by Oscari-pog** [comment]
> The announcement means basically nothing, you get like 40 seconds to respond to it and often can't get past the barrier runes.

Barrier runes take a single buckshot hit to shatter.

**Comment by PowerfulBacon** [comment]
Barrier runes can only be broken with the null rod, the same way regular runes can be destroyed. They are immune to all physical damage.

**Comment by Oscari-pog** [comment]
> Barrier runes can only be broken with the null rod, the same way regular runes can be destroyed. They are immune to all physical damage.

I saw a seccie blast his way through a rune to immediately obliterate the person who was drawing the rune, this is false.

**Comment by PowerfulBacon** [comment]
You can damage the shields that spawn with the rune, but not regular barrier runes (For some reason they are different)

**Comment by PowerfulBacon** [comment]
this is the reason why we force testing

**Review by itsmeow — APPROVED** [review]

**Pull request merged**
