### PR TITLE
Makes the Brig Physician antag eligible, removes security officer specific access and items

### PR DESCRIPTION
**Pull request by bloons3**
## About The Pull Request
- makes brig physician an possible antag role, instead of security's metashielded healer.
- removes their mindshield
- adds the syringe gun for the chameleon kit to copy
- changes paycheck to match civilian paycheck
- removes weapon permit (Civilians don't need guns roundstart)
- removes Detective's office, forensics lockers, security+medical records
- removes keycard auth (Why was this ever added to them?)
- removes Security equipment, security records, gulag item storage, secbots access
- adds surgery access
- adds cloning access
- adds medical mech
- adds ORM access (from Medical Doctor job)
- Modifies the Brig Phys locker to be locked only to the brig physician job, since there are already 2 basic medical kits for security to use when they are not present
- removes security items from the brig physician's locker, since they are a civilian
- changes supervisor

## Why It's Good For The Game

The Brig Physician is a very powerful role for security to have. Instead of having to venture across the station for healing, they never have to leave Brig to receive medical attention from a role that is meta-shielded from being an antag. This means that Security will never have to risk making themselves vulnerable in front of someone that they can't 100% trust.

Another issue is that since the Brig Physician can never be an antag, they are the first person that Security turns to when they need help. They're the first one to be given equipment like guns, armor, and other items. In effect, they are a security officer that is also given surgical equipment and medicine.

For Brig Physician to work, it needs to be more like the Lawyer. The Lawyer can be an antag, but has a job to do in Brig, and is given minimal access to perform their job. Likewise, the Brig Physician is someone with a specific job to do in Brig.

This PR will remove most easy opportunities for the Brig Physician to act as Security (managing prisoners, sentencing people in Brig), while maintaining the mechanic that they are a civilian embedded inside of Security.

## Changelog
:cl:
tweak: Modified Brig Physician access permissions and roundstart items
balance: Made the Brig Physician a proper civilian, which means eligibility for antags
/:cl:

### CODE REVIEW

**Comment by utilbird** [comment]
Sec actually having to leave brig is for heals is good, this won't really reduce their isolation that much but reducing the safety from 100% is a step in the right direction. 👍 

Buttt, this will make brig physician the perfect healing role, they get the trust of security (only really significant on sage) and full access and supervision over brig. Which makes med docs even more irrelevant, brig phys' will have almost the same amount of access as a medical doctor plus brig access ontop of it, it'd be a pretty good antag rolling job for med/sec players too.

Brig physician was never a really good role in the first place, it's job should have been covered by medical doctors, department roles (especially security) shouldn't be able to fully and quickly recover without any outside help or former time investment. Butt that's technically not related to this PR.

That's my take at least xd

**Comment by OceanFish1** [comment]
Leaving possible valid that belongs to the validhunter palace...

**Comment by bloons3** [comment]
> Sec actually having to leave brig is for heals is good, this won't really reduce their isolation that much but reducing the safety from 100% is a step in the right direction. 👍
> 
> Buttt, this will make brig physician the perfect healing role, they get the trust of security (only really significant on sage) and full access and supervision over brig. Which makes med docs even more irrelevant, brig phys' will have almost the same amount of access as a medical doctor plus brig access ontop of it, it'd be a pretty good antag rolling job for med/sec players too.
> 
> Brig physician was never a really good role in the first place, it's job should have been covered by medical doctors, department roles (especially security) shouldn't be able to fully and quickly recover without any outside help or former time investment. Butt that's technically not related to this PR.
> 
> That's my take at least xd

Depending on the discussion in this PR, I might remove their specialized medical permissions (leaving only their general access to medical storage). You'd be right that having a role that supersedes another role entirely might not be the best idea, especially if the better role has access to security comms roundstart.

**Comment by ToasterBan** [comment]
keep the access level changes, it should be a brig physician not an officer with med access, I still feel like they should be antagproof and the pay being lowered doesn't make any sense

**Comment by Naevii** [comment]
I heavily disagree with a change.
Brig physician is often the only person who cares about rescuing officers. He endangers himself saving their asses in maints or saving dangerous prisoners alone. 

He is the only person who actually cares. And often the only person who checks suit sensors. 
The only trusted person. 

I don't see why would they not be treated as part of security and why they wouldn't be mind shielded. 

He needs access to detective office because on some stations brig morgue with body bags is placed there. 

This is huge unnecessary nerf to brig and to security.

**Comment by PowerfulBacon** [comment]
this just makes them into a normal doctor + sec access

**Comment by VictorVow** [comment]
Ah yes, the healer role which gets to RP and work with their patients for the whole round today I will effectively remove. 

Before brig physicians any interaction as sec I had with doctors was minimal, preferring to use medikits or have another seccie do emergency surgery if needed. The very few rare times I was forced into a surgery room I was not RPing with the doctor, I was telling the warden/AI to watch me on sensors and cams, keeping in touch on comms and my finger on the trigger ready to fight back if needed. 

That's the reality as sec. You have to be paranoid to survive and giving them less people to trust means reducing RP opportunities. Ah great fun, another person I'll be watching more for when they likely try to murder me and not interact with unless absolutely necessary. This'll just lead to them getting ignored and shunned in their own department. 

> very powerful role for security

It's just someone with a locker full of meds, these can be ordered roundstart anyway and anybody can do surgery.

Last few weeks have been nothing but nerfs to sec, but you're still angling for more? 

> never have to risk making themselves vulnerable

Like there isn't plenty of opportunities to murder seccies, now you have to be paranoid 24/7 instead of just 23/7.

**Comment by heepox** [comment]
let me remind you that critting a seccie in maint and planting an explosive on them to lure more sec in to die is a very good tactic.

**Comment by utilbird** [comment]
> this just makes them into a normal doctor + sec access

They always were, this just removes the meta immunity they had ontop of it

**Comment by bloons3** [comment]
> It's just someone with a locker full of meds, these can be ordered roundstart anyway and anybody can do surgery.

I might agree with you on that, but the below statement was used as justification to give Brig Physician more healing items and tools to bring them in line with what Medbay has.

```oftentimes Medbay gets taken over by gangs/revs so it makes sense for it to have a variety of items in my opinion.```

I don't think it's very balanced that Security has their own dedicated healer that they can trust implicitly, and also have their own miniature medical wing with supplies and tools that go _beyond_ simply patching prisoners up and giving basic first aid to Security officers.

Having a Brig Physician that is antag-protected means that you have no reason to use Medbay for any reason, and you will never expose yourself to risk.

A lot of SS13 is that departments need to work together, but you have to trust other people. That doesn't mean you can't also take reasonable steps to mitigate that risk.

Worried that a doctor in Medbay might try and off you during surgery, or brainwash you into a felinid? Have another officer observe from the Surgery Observation room in case there's any funny business.

---

When Brig Physician was added, it was sold as Security's specialized medic, who was there to heal prisoners and patch up Security's boo-boos. That would be fine if they were treated as the lawyer was, which is an antag eligible civilian with a specialized purpose and minimal access to Brig. That's not the case however, and the Brig Physician is basically a Security Officer Junior in terms of access, items, and meta-protection.

If you are playing lower-population, it's highly likely that you will be arrested by the Brig Physician and sentenced in a cell for a crime, instead of an actual Security officer. That's pretty strange for someone who's paycheck comes from the civilian Medical Department.

**Comment by Naevii** [comment]
> > this just makes them into a normal doctor + sec access
> 
> They always were, this just removes the meta immunity they had ontop of it

Not true. They are dedicated for security. They are the trusted doctor, paramedic and surgeon. They can give a helping hand and stand with them in case if emergencies.

**Comment by bloons3** [comment]
> > > this just makes them into a normal doctor + sec access
> > 
> > 
> > They always were, this just removes the meta immunity they had ontop of it
> 
> Not true. They are dedicated for security. They are the trusted doctor, paramedic and surgeon. They can give a helping hand and stand with them in case if emergencies.

The problem _is_ that they're trusted because of their antag-metaprotection. When you have a Brig Physician, there's no reason to use Medbay at all, and risk exposing yourself to a stealthy antag. It deprecates an entire department when Security has a better replacement for Medbay tucked away in Brig.

**Comment by Naevii** [comment]
> > > > this just makes them into a normal doctor + sec access
> > > 
> > > 
> > > They always were, this just removes the meta immunity they had ontop of it
> > 
> > 
> > Not true. They are dedicated for security. They are the trusted doctor, paramedic and surgeon. They can give a helping hand and stand with them in case if emergencies.
> 
> The problem _is_ that they're trusted because of their antag-metaprotection. When you have a Brig Physician, there's no reason to use Medbay at all, and risk exposing yourself to a stealthy antag. It deprecates an entire department when Security has a better replacement for Medbay tucked away in Brig.

there is bunch of shit you wont do in brig infirmary or will just be too slow. A lot of officers use medbay regardless of having brig physicians, or they just use medkits instead.

here is my solution:
lock locker to be brig physician only (i dont even know why it isnt in the first place, i hate when someone uses my resources when i can patch them with something smaller)
plus resources in brig infirmary are not unlimited unlike in medbay sleeper. you have to mind how much you use and for what.
there is many reasons to go and use medbay.

being a bring physician often forces you to use meds more thoughtfully, because it means you msot likely wont get replacement. It also forces you to think differently than how normal doctor thinks. because you cant toss peopel to sleeper or on stasis bed. its more demanding and furthermore more fun.

Just because a bunch of people abuses this role doesnt mean it have to be changed from the ground as current balance is sufficient. I dont think it will attract proper people if we just make it a doctor who can roll antag and have sec access. 

And antags already have enough ways to get to officers anyway. how hard it is it to stalk them and ambush them in maint when they patrol. specially that doctors can have pinpointers and crew monitor freely.

**Comment by ItsTisme** [comment]
The 9 tilse that is brig medical is hardly a replacement for medbay

**Comment by VictorVow** [comment]
> risk exposing yourself to a stealthy antag. It deprecates an entire department when Security has a better replacement for Medbay tucked away in Brig.

Stealthy antag doctors have the entire crew to brainwash, I'm not sure why it has to be seccies too. There is additionally far more approaches for a stealth antag than just surgery ambushing, try a sleepy pen in maint (or basically any weapon in maint, seccies are almost always alone).

**Comment by bloons3** [comment]
> Stealthy antag doctors have the entire crew to brainwash, I'm not sure why it has to be seccies too.

I'm not sure why it doesn't have to be seccies too.

The most interesting revs round I saw was when the detective went to medbay while revs were still stealthed. He got ambushed in surgery, had his mindshield removed, and was converted to a rev. The detective ended up leading the charge on Brig with the rest of the revs.

I don't think there was a Brig Physician that shift, since otherwise the Detective would have never gone to medbay.

**Comment by Isy232** [comment]
This is kinda dumb, full on remove the brig phys role, don't pseudo remove them by removing almost everything that makes them different.

The brig phys will just be a medical doctor with brig access.

This wont stop people from being treated in the brig.

I think the brig physician should be an armed member of the security force with the primary job of keeping the security force and prisoners healthy and the secondary job of assisting security operations.

It makes sense to have an officer trained in the medical profession.

Officers still will need to go to medbay, security lacks the ability to cure viruses, make prosthetics, cure husking, cure missing organs or get easy access to chemistry.

Security being able to bandage more basic wounds makes sense to me.

**Comment by bloons3** [comment]
> I think the brig physician should be an armed member of the security force with the primary job of keeping the security force and prisoners healthy and the secondary job of assisting security operations.

We ported Brig Physician from Oracle, but neglected to add the follow-up PR that gave them in-game policy guidance.

image

"You are a doctor for Security, You are not a Security Officer. Do not do their job."

**Comment by Naevii** [comment]
> > I think the brig physician should be an armed member of the security force with the primary job of keeping the security force and prisoners healthy and the secondary job of assisting security operations.
> 
> We ported Brig Physician from Oracle, but neglected to add the follow-up PR that gave them in-game policy guidance.
> 
> image
> 
> "You are a doctor for Security, You are not a Security Officer. Do not do their job."

Then how about porting that instead?
And making the brig physician locker only for brig physician? So officers don't just tend themselves alone

**Comment by bloons3** [comment]
> > > I think the brig physician should be an armed member of the security force with the primary job of keeping the security force and prisoners healthy and the secondary job of assisting security operations.
> > 
> > 
> > We ported Brig Physician from Oracle, but neglected to add the follow-up PR that gave them in-game policy guidance.
> > image
> > "You are a doctor for Security, You are not a Security Officer. Do not do their job."
> 
> Then how about porting that instead?
> And making the brig physician locker only for brig physician? So officers don't just tend themselves alone

It doesn't solve the mechanics problem that the Brig Physician is given a lot of Security access, Security weapons, and a Security meta-shield.

**Comment by Sinestia** [comment]
I like playing brig phys but I think this is kinda warranted

especially on MRP. Brig phys is powerful as FUCK, sec in general has too easy of a time rn. 

 It's already questionable as hell that security officers and heads of staff are completely antag shielded. It's just something that we have to accept for balance reasons.

**Comment by Naevii** [comment]
> > > > I think the brig physician should be an armed member of the security force with the primary job of keeping the security force and prisoners healthy and the secondary job of assisting security operations.
> > > 
> > > 
> > > We ported Brig Physician from Oracle, but neglected to add the follow-up PR that gave them in-game policy guidance.
> > > image
> > > "You are a doctor for Security, You are not a Security Officer. Do not do their job."
> > 
> > 
> > Then how about porting that instead?
> > And making the brig physician locker only for brig physician? So officers don't just tend themselves alone
> 
> It doesn't solve the mechanics problem that the Brig Physician is given a lot of Security access, Security weapons, and a Security meta-shield.

I don't see a real problem here. 

You forget that brig physician essentially is a combat medic. Often gets in danger while saving security or just because it's part of security. I don't see any real reason why deputy baton is too much to have for him.

He can also support officers in bigger actions or when security is not staffed enough. (aka no security)

I don't know why a combat medic would have no means to defend himself or to not be mindshielded for security reasons.

**Comment by Naevii** [comment]
> I like playing brig phys but I think this is kinda warranted
> 
> especially on MRP. Brig phys is powerful as FUCK, sec in general has too easy of a time rn.
> 
> It's already questionable as hell that security officers and heads of staff are completely antag shielded. It's just something that we have to accept for balance reasons.

I don't think sec has too easy time right now. And I don't understand how removing someone who tends smaller wounds would help to improve that. 

And I don't even see in which way brig physician is powerful? He gets medkits, small surgery room, And deputy belt to defend himself if he gets in danger or gets targeted. 

Security is basically being targeted twice a month at least. 

And it's not even near how powerful it was before.

I think security is in a good enough state to leave it finally alone.

**Comment by Sinestia** [comment]
> Before brig physicians any interaction as sec I had with doctors was minimal, preferring to use medikits or have another seccie do emergency surgery if needed. The very few rare times I was forced into a surgery room I was not RPing with the doctor, I was telling the warden/AI to watch me on sensors and cams, keeping in touch on comms and my finger on the trigger ready to fight back if needed.
> 
> That's the reality as sec. You have to be paranoid to survive and giving them less people to trust means reducing RP opportunities. Ah great fun, another person I'll be watching more for when they likely try to murder me and not interact with unless absolutely necessary. This'll just lead to them getting ignored and shunned in their own department.

What's behind this metagaming tho?

 If surgeons are just killing you, then the problem is likely that rule that gives antags free permission to opportunistically kill any seccie. 

There's already that cringe thing of people refusing to go under for surgery, hard to argue that that's a good thing. (that's a separate issue, of course, and should be addressed with failure rates and infections)

**Comment by bloons3** [comment]
> And deputy belt to defend himself if he gets in danger or gets targeted.

https://github.com/BeeStation/BeeStation-Hornet/pull/2522

The Deputy belt and flash were **added** to Brig Physician after the initial PR ( https://github.com/BeeStation/BeeStation-Hornet/pull/1000 ) which ported them, which made the Brig Physician more of a Sec Officer than a Medic or Doctor.

Instead of having a civilian medical person who is assigned to the Brig to treat both prisoner and sec officer alike, it was changed to where they're a junior sec officer because they're given a flash, pepper spray, and a set of handcuffs. Why add these things if they're not expected to be used?

What dangerous situations is the Brig Physician getting into that a normal Paramedic wouldn't be? Why do they need Security specific gear, when they're meant to work _with_ Security Officers and not replace them?

If a Sec Officer drops dead in maint, go with another Sec Officer to retrieve them instead of trying to one-man-army it yourself. Better yet, go with a team of Sec Officers, because someone who kills one Sec Officer probably won't hesitate to kill another.

---

We have had a good amount of PRs that seem to be trying to make Brig Physicians into full on Security Officers.

https://github.com/BeeStation/BeeStation-Hornet/pull/1617

They were even given Keycard Authentication, along with every other Security Officer. Isn't that normally for _Command_ only?

**Comment by Naevii** [comment]
> > And deputy belt to defend himself if he gets in danger or gets targeted.
> 
> #2522
> 
> The Deputy belt and flash were **added** to Brig Physician after the initial PR ( #1000 ) which ported them, which made the Brig Physician more of a Sec Officer than a Medic or Doctor.
> 
> Instead of having a civilian medical person who is assigned to the Brig to treat both prisoner and sec officer alike, it was changed to where they're a junior sec officer because they're given a flash, pepper spray, and a set of handcuffs. Why add these things if they're not expected to be used?
> 
> What dangerous situations is the Brig Physician getting into that a normal Paramedic wouldn't be? Why do they need Security specific gear, when they're meant to work _with_ Security Officers and not replace them?
> 
> If a Sec Officer drops dead in maint, go with another Sec Officer to retrieve them instead of trying to one-man-army it yourself. Better yet, go with a team of Sec Officers, because someone who kills one Sec Officer probably won't hesitate to kill another.
> 
> We have had a good amount of PRs that seem to be trying to make Brig Physicians into full on Security Officers.
> 
> #1617
> 
> They were even given Keycard Authentication, along with every other Security Officer. Isn't that normally for _Command_ only?

I dont agree that single deputy belt that was added for self defence is making them more of a security than doctor. 
its an administrative issue if someone uses this role to play that way. and you can abuse any other role in a similar way, (engineering for free tools and insuls for instance)

they are ofcourse expected ot be used, but not to go after wanted people and to fight them but to defend yourself when you are pretty much enemy of all the antags, having a combat doctor, who is supposed to be part of sec, and not being able to defend himself when he gets ambushed or when he runs into danger while saving someone is just stupid. Also defending yourself from prisoners that you are treating as well.

Having an officer always with you whenever you see officer taking damage is unreal. becuase often the injury is from something stupid than from actual traitor. and officers are busy as it is. you are also often required to act fast, becuase when you see injury it means they might be gone from sensors anytime and gone forever, there is rarely a moment you can afford to ask multiple officers to go with you and hope someone will agree.

Paramedics are regular crew, therefore less frequently get into interactions with traitors, prisoners, so not only they are less targeted, but have less value.


Like seriously, these brig physician changes are completely unecessary.

**Comment by bloons3** [comment]
> The very few rare times I was forced into a surgery room I was not RPing with the doctor, I was telling the warden/AI to watch me on sensors and cams, keeping in touch on comms and my finger on the trigger ready to fight back if needed.

Some people might call that _metagaming_, that you are expecting to be attacked for no In-Character reason in the round.

sec_surgery

Most rounds Doctors aren't antags, and Medbay isn't revs.

**Comment by VictorVow** [comment]
> it's metagaming to not trust people who haven't been through background checks

Literally what?

**Comment by yyzsong** [comment]
CMO still has antag immunity and sec access. Make CMO into antag when????

**Comment by ghost** [comment]
> Make CMO into antag when

As soon as possible, along with every other head besides cap and HOS as it is on LRP

**Comment by eeSPee** [comment]
> Remove brigphys access/security gear

Yes.

> Remove meta immunity.

Eh. Kinda conflicted. Same arguments as to why detective has meta immunity...

**Comment by Archanial** [comment]
Good change because it was my idea

**Comment by DatBoiTim** [comment]
Good PR. Though full removal would be preferred. Sec mains are seething.

I'd even argue removing additional metashields, keeping only HoP(Easy low-risk AA, often fills in for Captain, is literally the easiest job to have as any almost antag), Primary Sec(HoS, Warden, Officer, because sec really needs to be kept on a tight leash), and Captain(Roundstart AA, multiple captain items are steal targets(disk, hand tele, antique gun, medal, Secret Documents/Plutonium Core because Captain in vault isn't unheard of, could probably frame/call for execution of assassination targets).

Paranoia is intended to be felt when doing something risky. While I understand round removal is unfun(fix by making more ghost roles/post death activities), Sec's entire job at this point has become doing just that.

**Comment by bloons3** [comment]
> > Remove brigphys access/security gear
> 
> Yes.
> 
> > Remove meta immunity.
> 
> Eh. Kinda conflicted. Same arguments as to why detective has meta immunity...

Thing is, Lawyer doesn't have meta immunity yet has basic brig access and sec comms.

**Comment by Sinmero** [comment]
Removing brig phys antagshield is a bad change. Sec are protected from antag roles for a reason. Brig phys is a member of sec personnel. They are supposed to be trustworthy.

I would rather remove brig phys role then make them antag eligible.

**Comment by eeSPee** [comment]
I mean, we have med sec officer who has medical access and could act as a brig phys. One can argue there is no reason for brig phys to exist, other than sec to act as a separate station.

Might as well have a sec engineer, sec PACMAN room and sec cargo shuttle.

**Comment by Sapfearon** [comment]
ah yes, let's make brig phys another lawyer, as is guy who you always ignore and tell him to fuck off from brig. The only good thing about brig phys right now is him being sec with mindshield, removing it makes him OP medic antag role, nothing else.

**Comment by BrotherHangyul** [comment]
Gonna make me come out of the woodworks here, aye?

This PR is utter dogshit. I'll say it out loud. It's dogshit.

Today, I will ruin an RP role and unnecessarily nerf a niche role that's not even OP. I will also make this same role completely different despite the fact a number of people regularly play this role and enjoy playing it.

This can be circumvented so easily by a simple non-antag paramedic deciding to become a makeshift brig phys. Fuck this PR.

**Comment by DatBoiTim** [comment]
> Today, I will ruin an RP role

Only RP I see from brig phys fall into the following:
*Join Lawyer/Det getting wasted in bar
*Become another security officer
*Become a generic paramedic who has brig access without much else

Very rarely do I see a brig phys do more than treat some shitsec victim, and even more rarely do they do surgery for stuff like implants/etc. 

Security hunkering in their autism bunker is not only boring, but lame, considering they are armed with powerful tools.

**Comment by BrotherHangyul** [comment]
> *Join Lawyer/Det getting wasted in bar

Hunkering might be a problem on Golden, but in my combined hours of both playing security and observing as an admin, it's rarely happened on Sage, and most players are on sage.

**Comment by DatBoiTim** [comment]
> > *Join Lawyer/Det getting wasted in bar
> 
> 
> 
> Hunkering might be a problem on Golden, but in my combined hours of both playing security and observing as an admin, it's rarely happened on Sage, and most players are on sage.

Still doesn't address how an issue with altering access for an RP role ruins it.

How is RP ruined by no detective office access? How is it(RP) ruined by no equipment room access?

**Comment by BrotherHangyul** [comment]
> > > *Join Lawyer/Det getting wasted in bar
> > 
> > 
> > Hunkering might be a problem on Golden, but in my combined hours of both playing security and observing as an admin, it's rarely happened on Sage, and most players are on sage.
> 
> Still doesn't address how an issue with altering access for an RP role ruins it.
> 
> How is RP ruined by no detective office access? How is it(RP) ruined by no equipment room access?

I'm talking more the antag allowance / removal of the mindshield. The brig phys is an RP role meant to keep the officer safe. Like how you trust the captain, you should be able to trust your brig phys. This basically makes it so that the brig phys is probably a deranged traitor out to gut you. Bad.

**Comment by yyzsong** [comment]
>roleplay role

Its literally medical doctor with access to the brig and validhunting gear. No more of a roleplay role than CMO.

Plus, dying/being injured should put you in a vulnerable position, like having your corpse rotting in maint or in medbay, free to loot, and not just being dragged back to the safety of the brig.

Not dying as security, what a concept.

**Comment by Raven-Industries** [comment]
Some of the best sec RP I've seen has come from the brig physician interacting with prisoners or other sec members. I do agree with the removal of the sec equipment, weapon permit, and so on; they shouldn't really be toting anything except maybe a pepperspray for self-defense, but the mindshield and non-antag status I 'd say keep. In-universe, even a civilian contractor is going to get some extensive background checks if they're working so closely with security. Maybe remove the surgery equipment from the permabrig on maps to balance that out and keep sec from holing up there completely?

**Comment by BrotherHangyul** [comment]
> Some of the best sec RP I've seen has come from the brig physician interacting with prisoners or other sec members. I do agree with the removal of the sec equipment, weapon permit, and so on; they shouldn't really be toting anything except maybe a pepperspray for self-defense, but the mindshield and non-antag status I 'd say keep. In-universe, even a civilian contractor is going to get some extensive background checks if they're working so closely with security. Maybe remove the surgery equipment from the permabrig on maps to balance that out and keep sec from holing up there completely?

What raven said. I'm fine with the equipment changes, even if they're a bit dumb, but the mindshield should remain, especially for somebody who works in such close proximity with sec. Lawyers don't count.

**Comment by Vexylius** [comment]
Brig physicians are not supposed to do security job, yes, but that issue should be handled by people IC and admins. For me brig phys is like a [military combat medic](https://en.wikipedia.org/wiki/Combat_medic) or something, and as such, should have access to [basic self-defence equipment](https://en.wikipedia.org/wiki/Equipment_of_a_combat_medic) as they often have to deal with criminals physically (unlike lawyer, who only needs to talk with people and has to defend them with words), and those criminals like to take advantage of people that come into their cells to help them. This PR will make brig phys pain in the ass to play as, as they'd need constant help from someone, and from my personal experience often there is noone to help you.

**Comment by bloons3** [comment]
> this just makes them into a normal doctor + sec access



> Which makes med docs even more irrelevant, brig phys' will have almost the same amount of access as a medical doctor plus brig access ontop of it, it'd be a pretty good antag rolling job for med/sec players too.

Made access changes in https://github.com/BeeStation/BeeStation-Hornet/pull/3561/commits/c84b694b4eda699a6d975b2efa62acb2e4ad7e8a to hopefully address this.

**Comment by JackieOTheWisp** [comment]
Going to say a firm no on this one, and here's why:

Firstly, making an antag role out of brig physician would undermine Sec's stability. Would Nanotrasen REALLY let someone into the security area without a mindshield, bar the lawyer, who can't even get to anything dangerous anyways, or even open a cell. Sec's been at the bottom of the barrel for the longest time, and I believe we don't need to nerf it anymore.
Secondly, security and medical records being removed makes ABSOLUTELY no sense. Sec, perhaps, but medical? The brig phys is the medic of the sec team, it'd be hell if they needed to check for something in the medical record and then not have access.  It'd make the role completely and utterly useless to take out so much stuff.
Thirdly, surgery and cloning, this is useless. Cloning, nine times out of ten, ends up on emergency access anyways. Surgery is great and all, if you work in medbay, but this is the brig, we have a surgery table, I do surgery with someone strapped to a bed sometimes. 
Finally, removing the gear from the locker. I'd rather keep a pepperspray and flash, it's not the role's fault if someone validhunts. Rather than removing the one way Brig Phys can defend theirself focus more on the tickets, if brig phys is validhunting and not doing their job right, they shouldn't be a brig physician. A flash saved me from being slaughtered like a lamb in a butcherhouse while taking care of a perma'd prisoner.

If you put this PR in I'm removing brig physician via pr and leaving Beestation forever. Because "nerfing" something into oblivion is just a very nice way of saying "fuck you" to everyone that plays the role. It makes the game not fun for anyone.

**Comment by Archanial** [comment]
So, brig physician should be straight upgrade from medical doctor?
Seriously you think nanotrasen would train security person to be a doctor while their station has big, robust medbay?

**Review by utilbird — APPROVED** [review]
Just play medic

**Comment by ghost** [comment]
> If you put this PR in I'm removing brig physician via pr and leaving Beestation forever.

bye lol

**Comment by ike709** [comment]
@YoshimiWasTaken 
> If you put this PR in I'm removing brig physician via pr and leaving Beestation forever. 

image

**Pull request merged**
