### PR TITLE
mainly making a concept - Your mind remembers your original species

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
New variable to Mind that stores roundstart species of a person.

## Why It's Good For The Game
some system is based on your current species, not your real origin species.
for example, if you become ashwalker somehow, you lose your galactic common and get draconic even if you're a human.
in this PR, it didn't change a lot, and mainly refactored to access their original species mind simply 

ID card var renaming refactor was done accidentally.

Q. Shouldn't it be fine to store it into a variable in mob?
A. No. If your brain is replaced into somewhere, your roundstart species will be changed. It MUST be stored in mind.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

ghost spawning is fine

-------------

image

roundstart spawning is fine

-----------

image

latejoin spawning is fine

--------

image

when you admin spawn (*force humanize)

-----------

image

tribal scroll is fine

image

if you change 'roundstart_species` var into not lizard, they can't read tribal scroll

</details>

## Changelog
:cl:
refactor: changed capital C into capital I at id card variable in spawning code
refactor: "is_species" proc can accept type paths too.
refactor: New mind variable "roundstart_species" to remember the real origin you were. Spawning sets your mind species.
tweak: To read Old Tribal Scroll (lizard martial arts), your roundstart species should be lizardperson as well. You can't cheat your origin anymore.
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
I think you need to put 5u~10u of cola at least, since tasting no cola doesn't make sense.

**Comment by EvilDragonfiend** [comment]
I think I got a better solution for this. Going to be updated.

**Comment by EvilDragonfiend** [comment]
well, my idea didn't work, and this is the way, I think.

**Comment by itsmeow** [comment]
If you die and take a human ghost role like ninja, wizard, etc, does it maintain the species, or is mind deleted?

**Comment by EvilDragonfiend** [comment]
> If you die and take a human ghost role like ninja, wizard, etc, does it maintain the species, or is mind deleted?

They'll get their starting species - mostly human.
Player's mind is never delete, so I wrote a code to replace theirs into new.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
I don't think that tribal claw should be limited to only roundstart lizards and as such do we need to track this? I don't see much of a use for it in the future.

**Comment by EvilDragonfiend** [comment]
not really necessary for now. I will close the PR and we can do this later.

**Pull request closed without merging**
