### PR TITLE
Ninja invisibility rework (And consolidates /datum/action cooldowns to a single place)

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Reworks ninja invisibility
- Upon de-activating starts a 30 second cooldown before it can be activated again.
- Upon attacking or teleporting, invisbility will be disabled.

This made me desire better cooldown feedback on the action button, which lead to consolidating the action cooldowns.

Consolidates action cooldowns:
- Action cooldowns were a right mess, spread between /datum/action, /datum/action/cooldown and /datum/proc_holder/spell
- All actions can now be given a cooldown by calling set_cooldown on them.
- Actions with a cooldown will now display the timer animation and show their time remaining

## Why It's Good For The Game

- Ninja shouldn't be able to combat while invisible, since it lets them dodge lasers.
- Ninja stealth shouldn't be able to just be turned on and off during combat, so has a cooldown.
- Actions with a cooldown should be well coded and standardised.

### Test ninja stealth disable on attack

image

image

### Test ninja cooldown

image

### Test Psychoza cooldown

image

image

### Test dragon cooldown

image

### Test spell recharging cooldown

image

image

## Changelog
:cl:
balance: Ninja invisibility now has a 30 second cooldown and disables when teleporting or attacking with the katana.
tweak: Standardises the code for action cooldowns.
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
> Consolidates action cooldowns:
> 
> * Action cooldowns were a right mess, spread between /datum/action, /datum/action/cooldown and /datum/proc_holder/spell
> * All actions can now be given a cooldown by calling set_cooldown on them.
> * Actions with a cooldown will now display the timer animation and show their time remaining

What is the point of this with #11527 ongoing?

Seems like a barrier to that PR.

**Comment by PowerfulBacon** [comment]
That PR is just porting TGs actions and doesn't achieve the cleaning up of actions that I'm doing here.

**Comment by Rukofamicom** [comment]
Is the invisibility indefinite so long as specific actions aren't taken (and power lasts)?

I feel like this would actually be a good time to ask that ninja not be so reliant on draining APCs for charge, as a compensation if sorts for the nerfs. Ninjas run out of power fairly quickly and won't be able to easily access nearly as many APCs with a stealth nerf.

**Comment by SunShine214** [comment]
Regarding ninja stealth: what is the point of it now? not only is it really easy to see (not actually stealthy) the beam and sound emitted from the dash ability gives any ninja away instantly. Now ninjas also leave a wake of emagged doors and broken windows, the only reason to use the stealth ability is either for flavor or as defense against the first shot.

**Comment by PowerfulBacon** [comment]
This is currently blocked by the actions PR. I'll return to it later.

**Pull request closed without merging**
