### PR TITLE
Revolver Crate

### PR DESCRIPTION
**Pull request by Leshens**
## About The Pull Request
Add's crate with Colt Detective Special and holster. 

## Why It's Good For The Game
Sometimes as detective you can lose the gun when your uniform burns down, or you join as second detective and the pain of being striped down from a unique and cool weapon is unbearable. Sadly, at the same time the gun will lose some of its uniqueness, but that's the sacrifice we are willing to make.

## Testing Photographs and Procedure

<details>

Przechwytywanie

</details>

## Changelog
:cl:
add: Revolver Crate
fix: Description of WT-550 Auto Rifle Crate
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
No 🔑 

Revolver is unique to detective and it should remain that way. 
If you want to fix the "missing revolver" for latejoins then make detective spawn with one and remove them from maps.

**Comment by EvilDragonfiend** [comment]
sounds like an cargo contraband item

**Comment by Leshens** [comment]
> No 🔑
> 
> Revolver is unique to detective and it should remain that way. If you want to fix the "missing revolver" for latejoins then make detective spawn with one and remove them from maps.

In my expirence as det,

**Comment by Leshens** [comment]
> No 🔑
> 
> Revolver is unique to detective and it should remain that way. If you want to fix the "missing revolver" for latejoins then make detective spawn with one and remove them from maps.

Do you think if crate was only openable to someone with Forensics locker access, it would let it keep being unique to detective?

**Comment by St0rmC4st3r** [comment]
> > No 🔑
> > Revolver is unique to detective and it should remain that way. If you want to fix the "missing revolver" for latejoins then make detective spawn with one and remove them from maps.
> 
> Do you think if crate was only openable to someone with Forensics locker access, it would let it keep being unique to detective?

I refuse to believe that you never did a gun cargo with no access.
You can:
1. EMP it.
2. PKA it.
3. Dip it into lava.
4. Borrow a shotgun.
5. Borrow a laser gun.
6. Borrow an emitter.
7. Splash it with acid.
8. Steal an ID after all.

**Comment by Fronsis** [comment]
> > > No 🔑
> > > Revolver is unique to detective and it should remain that way. If you want to fix the "missing revolver" for latejoins then make detective spawn with one and remove them from maps.
> > 
> > 
> > Do you think if crate was only openable to someone with Forensics locker access, it would let it keep being unique to detective?
> 
> I refuse to believe that you never did a gun cargo with no access. You can:
> 
> 1. EMP it.
> 2. PKA it.
> 3. Dip it into lava.
> 4. Borrow a shotgun.
> 5. Borrow a laser gun.
> 6. Borrow an emitter.
> 7. Splash it with acid.
> 8. Steal an ID after all.

That pretty much applies to any sort of item that can lead to ''gun cargo'' though, i don't see why they would ''gun-cargo with det revolver'' when they can choose more stronger weapons 


I think this proposal of a revolver crate would be more fitting if we had the ''stock-items cargo'' proposal back in, making it so you can order only **One** Revolver crate for that exceptional case where:

- Gun was completely destroyed/lost on X incident
- It's not Meta where you have a 2nd Closet with a revolver for another detective
- The first Detective cryo'd

As someone who has been late-join Det, there's been a couple of ocassions where the gun was missing, most of the times it's because the previous Detective cryo'd and it's on cryo storage, it's always a pain to have to wait for Captain/Someone with access to retrieve the item for me so i can have the gear back (This also applied before we had Det start with a forensic scanner)

If i were to propose a solution, would be for the cryo storage to take into account the job to see if it's valid to retrieve the item
i.e:
Detective can take the revolver/similar detective items from cryo storage
Warden can take the Krav Maga gloves from cryo storage (this also happens frequently) 

Some players do leave the gear back on the proper locker/closet before they cryo, but some others don't, i think it would be overall better for them to be able to retrieve their unique items from cryo storage without having to wait for Captain/Someone with access to retrieve them, because they're usually busy. (Specially since this scenario only applies on late-joining, meaning the station is probably going through something)

**Comment by Leshens** [comment]
> > > No 🔑
> > > Revolver is unique to detective and it should remain that way. If you want to fix the "missing revolver" for latejoins then make detective spawn with one and remove them from maps.
> > 
> > 
> > Do you think if crate was only openable to someone with Forensics locker access, it would let it keep being unique to detective?
> 
> I refuse to believe that you never did a gun cargo with no access. You can:
> 
> 1. EMP it.
> 2. PKA it.
> 3. Dip it into lava.
> 4. Borrow a shotgun.
> 5. Borrow a laser gun.
> 6. Borrow an emitter.
> 7. Splash it with acid.
> 8. Steal an ID after all.
I) Cargo can't order sec crates without permission.
II) Force opening crates is allowed only to antags(and they have better weapons than revolver)
III) Gun cargo without VERY GOOD reason as non-antags is agains rules
IV) As Fronsis said, there are much better weapons

**Comment by PowerfulBacon** [comment]
I personally think that the revolver should remain a unique item and if it gets lost, then the detective cannot get it back

**Pull request closed without merging**
