### PR TITLE
Removes possible source of ERP

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Equipping pet collar on your neck now gibs you.

## Changelog
:cl:
add: Equipping pet collar on your neck now gibs you.
del: Removed possible source of erp and cringe roleplay.
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
no. abusing camryn hynes is funny.

This also lets you instantly gib anyone you can slip it on.

**Comment by TeomanTheGreat** [comment]
Based pr speedmerge now! (You should just make it un-equipable)

**Comment by Archanial** [comment]
> 
> 
> no. abusing camryn hynes is funny.
> 
> This also lets you instantly gib anyone you can slip it on.

No, the person that equips it gets gibbed, not the one wearing it.

**Comment by TeomanTheGreat** [comment]
> > 
> > 
> > no. abusing camryn hynes is funny.
> > 
> > This also lets you instantly gib anyone you can slip it on.
> 
> No, the person that equips it gets gibbed, not the one wearing it.

Make it so there is a warning. "Are you sure you want to do this?" Then make them choose yes or no. If they choose no then it doesn't get equipped. If they say yes they gib and a message that only they can hear plays "Nanotrasen anti-ERP protocol initiated".

**Comment by Archanial** [comment]
> Make it so there is a warning. "Are you sure you want to do this?" Then make them choose yes or no. If they choose no then it doesn't get equipped. If they say yes they gib and a message that only they can hear plays "Nanotrasen anti-ERP protocol initiated".

No way, they knew what they were doing.

**Comment by DatBoiTim** [comment]
Bro get linters to pass so it can speedmerge

**Comment by PowerfulBacon** [comment]
> uses usr instead of user

**Comment by Archanial** [comment]
> 
> 
> > uses usr instead of user

because user will gib person wearing it, usr will gib person equipping it on someone (if I'm not mistaken)

**Comment by DatBoiTim** [comment]
> because user will gib person wearing it, usr will gib person equipping it on someone (if I'm not mistaken)

I'd reccomend doing testing to ensure functionality is as desired

**Comment by Archanial** [comment]
> 
> 
> > because user will gib person wearing it, usr will gib person equipping it on someone (if I'm not mistaken)
> 
> I'd reccomend doing testing to ensure functionality is as desired

I did test it

**Comment by Naevii** [comment]
Now, people who bought pet collar from beecoin shop for 20k coins and have it equipped will be gibbed roundstart, can't wait.

April's fools was yesterday, you are late.

**Comment by DatBoiTim** [comment]
> Now, people who bought pet collar from beecoin shop for 20k coins and have it equipped will be gibbed roundstart, can't wait.
> 
> April's fools was yesterday, you are late.

Hence why you read the changelog

**Comment by Naevii** [comment]
> > Now, people who bought pet collar from beecoin shop for 20k coins and have it equipped will be gibbed roundstart, can't wait.
> > April's fools was yesterday, you are late.
> 
> Hence why you read the changelog

I paid for my erp privilege. I want my 20k coins back 

We all know that pet collar is a joke.

**Comment by Archanial** [comment]
> I paid for my erp privilege. I want my 20k coins back
> 
> We all know that pet collar is a joke.

no, you paid for pet collar, put in on some pet or something instead.

**Comment by francinum** [comment]
Aha. No.

**Pull request closed without merging**
