### PR TITLE
Skinsuits

### PR DESCRIPTION
**Pull request by ike709**
Ports https://github.com/BeeStation/NSV13/pull/162

Added for #1833 but in its own PR to gather feedback. I did tweak some of the vars.

## Changelog
:cl:
add: Your emergency survival box now contains a skinsuit, which is an emergency spacesuit that protects against low pressure (but not against cold!).
add: Unroll the skinsuit to equip it, roll it back up to fit it back in the box.
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
Pretty cool, but I don't like how they cover your entire head, hiding your identity

**Comment by ike709** [comment]
They don't cover your identity, I tweaked that.

**Comment by ike709** [comment]
~~TODO: Make them foldable like bodybags. Waiting on a sprite.~~

Done.

**Comment by zeskorion** [comment]
Perhaps make this not count as thick clothing so not everyone starts with a syringe defense as well

**Comment by PowerfulBacon** [comment]
> 
> 
> Perhaps make this not count as thick clothing so not everyone starts with a syringe defense as well

Exactly, it is just a thin suit layer too

**Comment by ike709** [comment]
Good idea.

**Comment by Kmc2000** [comment]
If youre making them foldable I highly suggest you nerf them a bit, on nsv it makes IPCS able to spacewalk for free, but at least once you take it out of the box, you have to lug it around

**Comment by ike709** [comment]
@Kmc2000 It's pretty nerfed.

**Comment by MCterra10** [comment]
icons literally don't exist. wtf

**Comment by ike709** [comment]
Yes they do.

**Pull request merged**
