### PR TITLE
More Obsession tweaks and stuff!

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

This adds some neat stuff to obsession:
- Seeing your obsession dead will _completely fuck up_ your mood and sanity
- The obsessed trauma will properly transfer on cloning
- Added random 'insanity' flavor text while obsessed
- The obsession trauma will disguise itself as "monophobia" to scanners at first, and will only begin appearing as "psychotic schizophrenic delusions" after 5 minutes spent near the target. This 'revelation threshold' being passed will show a large, unique message to the obsessed.
- Added new font and text effects to obsession text.
- Your obsession's name will be highlighted for you in chat.
- Admins can now change an obsession target for an existing obsessed.
- Changelings and transform sting victims will no longer be picked as obsession targets, as this can get really confusing.
- Wands of healing/aheals/adminorazine will no longer heal special-cure-proof traumas (as these are explicitly _antag_ traumas, and aheals don't deconvert antags)
- Obsessed is now visible in the ghost orbit list.

## Why It's Good For The Game

Helps build up the flavor for obsession, should in theory help with RD

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

23-08-25-1692974428-dreamseeker

23-08-25-1692974193-dreamseeker
23-08-25-1692973890-dreamseeker
23-08-25-1692973844-dreamseeker
23-08-25-1692973806-dreamseeker

</details>

## Changelog
:cl:
add: Added fancy font effects to obsession stuff!
add: While obsessed, you will see your obsession's name highlighted whenever someone says it, similar to traitor code phrases.
add: Added random 'insanity' flavor text to obsessions.
fix: The obsession trauma should properly transfer on cloning now.
balance: The obsession trauma will disguise itself as "monophobia" to scanners at first, and will only begin appearing as "psychotic schizophrenic delusions" after 5 minutes spent near the target. This 'revelation threshold' being passed will show a large, unique message to the obsessed.
balance: Wands of healing/aheals/adminorazine will no longer heal special-cure-proof traumas (as these are explicitly _antag_ traumas, and aheals don't deconvert antags)
tweak: Changelings and transform sting victims will no longer be picked as obsession targets, as this can get really confusing.
admin: Admins can now change an obsession target for an existing obsessed.
add: Obsessed is now visible in the ghost orbit list.
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
Why is it deep-rooted now? Was it made on the previous PR? I don't see it in the CL.

Unsure about 25 minutes, the average Obsessed spends less than 5 with their target since they end up taking more time trying to murder the co-workers and such.

**Comment by Absolucy** [comment]
> Why is it deep-rooted now? Was it made on the previous PR? I don't see it in the CL.

@Fronsis Yep, previous PR.

>Unsure about 25 minutes, the average Obsessed spends less than 5 with their target since they end up taking more time trying to murder the co-workers and such.

Ah, was going off numbers where I had 25-ish minutes spent with my target, and I saw someone later with 30+ minutes

**Comment by Absolucy** [comment]
@Fronsis I lowered it to 5 minutes.

**Comment by Absolucy** [comment]
Converting to draft as I still want to make some tweaks, such as to chat colors/effects

**Pull request closed without merging**
