### PR TITLE
adds sanity check

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
i made afucky wucky again dont yell at me pwease

## Why It's Good For The Game
fixes a lot of nanites

## Changelog
:cl:
fix: zams fixed antoher fucky wucky with nanites oops
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
The error was because the Dermal Button program for some reason returns null for logic, since it doesnt use logic,.

**Review by utilbird — DISMISSED** [review]
it just works

**Comment by utilbird** [comment]
(build failing)

**Comment by Sinestia** [comment]
Ya girl didn't even get to the
"builds for me lol" 

stage of QC

**Comment by Archanial** [comment]
of course it failing was my fault :smirk:

**Review by utilbird — APPROVED** [review]

**Pull request merged**
