### PR TITLE
[Mapping] Moves Boxstation cargo autolathe behind shutters and moves box science autolathe into Science

### PR DESCRIPTION
**Pull request by bloons3**
## About The Pull Request

Inspired by: https://github.com/tgstation/tgstation/pull/41613
image

image

## Changelog
:cl:
add: Boxstation cargo has a gated autolathe
tweak: moves box science autolathe into Science
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
why remove the sci one tho?

**Comment by bloons3** [comment]
Cargo is where you go to get things that you need, especially minor sorts of things that the autolathe creates.

**Comment by Mat05usz** [comment]
Every other station has 2 autolathes, mostly for convenience. Now you'll have to run across the entire station if you are near sci and need something from lathe.

**Comment by PowerfulBacon** [comment]
Boxstation cargo already has a public lathe, can you title your PR descriptions accurately and not deceptively?

**Comment by bloons3** [comment]
> Every other station has 2 autolathes, mostly for convenience. Now you'll have to run across the entire station if you are near sci and need something from lathe.

resolved


image

**Comment by Isy232** [comment]
I dont see the need to make such a large structure around the autolathe. A shutter on top of the autolathe would suffice.

I also dont see the need to remove the science one. The science one also has a shutter, allowing you to close it down.

**Comment by bloons3** [comment]
You may or may not want to allow public access to the lathe for Cargo while keeping your private access.

Closing the shutters on the science lathe will prevent you entirely from servicing requests at the desk.

**Comment by pickleinjar** [comment]
ngl this is SUPER dumb. tiders will break the fucking windows into cargo. please dont.

**Comment by bloons3** [comment]
> ngl this is SUPER dumb. tiders will break the fucking windows into cargo. please dont.

The shutters can be raised.

**Comment by PowerfulBacon** [comment]
Vote at 11/51, safe to say at this point its not going to pass

**Pull request closed without merging**
