### PR TITLE
Reworks Kilo Station

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
Kilostation is BACK! this has been a collaborative effort, with the initial fix by @Emotions211, more fixes by GizkaFreechman, and being brought up to date by myself

## Why It's Good For The Game
more maps!

## Changelog
:cl: Zeskorion, GizkaFreechman, Emotions211
add: Kilostation has random maint
add: Kilostation is now up to date on monstermos
add: Kilo botany has a botany dispenser
config: Kilo re-enabled
add: Secure Virology airlock added to kilo
del: Maint doors into viro removed on kilo
del: side door into vault removed on kilo
del: Large amount of decals removed for stability on kilo
tweak: replaced glass tables in kilo perma with regular tables
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
oh god oh fuck

**Comment by PowerfulBacon** [comment]
on first glance, wow this is significantly improved

**Comment by zeskorion** [comment]
i'll just slap a label here...

**Comment by Firefox13** [comment]
AI core airlock is non-monstermos as well as north-east derelict.

**Comment by zeskorion** [comment]
> AI core airlock is non-monstermos as well as north-east derelict.

fixed in last commit, derilect one dont matter much

**Comment by Kerbin-Fiber** [comment]
testmerge when?

**Comment by Crossedfall** [comment]
Test merged onto ~~Sage~~ both servers

**Comment by Crossedfall** [comment]
Feedback and bug tracking thread: https://forums.beestation13.com/t/kilo-station-rework-input-thread/5758

**Comment by Crossedfall** [comment]
No longer test merged.

**Comment by Firefox13** [comment]
EVA contains old spacesuits, those with big 13 on the back.

**Comment by Firefox13** [comment]
Freight station(north-east derelict).
изображение
Upper airlock is no access.
Lower requires access.

**Comment by Crossedfall** [comment]
@zeskorion Are ya still working on this.. Or?

**Comment by zeskorion** [comment]
> @zeskorion Are ya still working on this.. Or?

oh shit this was marked stale.

yeah i just took a long break before getting to it again. just finished up

**Comment by PowerfulBacon** [comment]
oof, someone updated kilo and caused you a merge conflict

**Comment by zeskorion** [comment]
> oof, someone updated kilo and caused you a merge conflict

who the fuck even touched kilo olmao

**Comment by PowerfulBacon** [comment]
no idea

**Comment by Sun-Soaked** [comment]
Is kilo xenobio fixed? It was sick nasty inefficient before, with little room for manual upgrades

**Comment by Crossedfall** [comment]
Test merged onto sage

**Comment by PowerfulBacon** [comment]
Not enough job spawns resulting people spawning in cap's office and AI sat

**Comment by qwertyquerty** [comment]
Still working on this?

**Comment by zeskorion** [comment]
closing for now, conflicts and the mysterious 1:30 crash is unresolved

**Pull request closed without merging**
