### PR TITLE
Fixing afterattack to call lighteater_act properly

### LINKED ISSUE #5276: The Nightmare antagonist can't destroy the light sources with the lighteater anymore.
It just can't. Nightmare can hit light emitting objects with the lighteater on the harm intent, this won't damage nor destroy the objects.

### PR DESCRIPTION
**Pull request by rkvothe14**
## About The Pull Request

Closes #5276

## Why It's Good For The Game

Light eater now able to properly destroy sources of light.

## Changelog
:cl:
fix: fixes Nightmare's lighteater so they can destroy light sources again.
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
thankfully the one line fix solution that isn't reverting the whole thing brainlessly

**Comment by rkvothe14** [comment]
> thankfully the one line fix solution that isn't reverting the whole thing brainlessly

It is. Still needs some work as it snuffs out the PDA light but the icon does not get updated. Will add that later today. The rest works correctly.

**Comment by rkvothe14** [comment]
Had to add some code for the PDA light to be actually shorted out and its icon updated, also making the light unusable after it's attacked by the lighteater.

https://user-images.githubusercontent.com/90270186/135736169-9c882868-20c7-4bf9-ac41-edea5af9268b.mp4

If there's a better way of doing this, please let me know.

**Comment by rkvothe14** [comment]
Mechs are still immune to the lighteater. I'm currently working on that + refactoring the shorted out part as it doesn't look great.

**Comment by rkvothe14** [comment]
done! thanks @Archanial for the help

**Review by Archanial — APPROVED** [review]

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
