### PR TITLE
Temporarily disables dynamic.

### PR DESCRIPTION
**Pull request by super12pl**
## About The Pull Request
There's well known about dynamic that lets protected roles so security and command become antagonists.
This PR disables dynamic until someone manages to fix it.

## Why It's Good For The Game
See above

## Changelog
:cl:
config: Temporarily disables dynamic.
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
Fix it yourself instead of disabling it

**Comment by super12pl** [comment]
> Fix it yourself instead of disabling it

I dont know how to fix it though

**Comment by ike709** [comment]
@Crossedfall Config

**Comment by Rukofamicom** [comment]
Multiple Captain/HoS antags over the past few days because of this causing a lot of pretty bad rounds.

**Review by PowerfulBacon — APPROVED** [review]
@Crossedfall config

**Comment by Crossedfall** [comment]
It's already disabled serverside. Going to skip on merging this since it's a temporary change anyways.

**Pull request closed without merging**
