### PR TITLE
REMOVES THE HOTEL STAFF MENACE

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

REMOVES STINKY HOTEL STAFF

## Why It's Good For The Game

AHHHHHHHHHHHHH FUCK HOTEL STAFF FUCK FUCK FUCK

## Changelog
:cl:
del: REMOVED HOTEL STAFF FOREVER
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
elaborate blease

**Comment by ghost** [comment]
remobes slebers for sbawn from hotel mab :DDD

**Comment by ike709** [comment]
better move is to put a bomb in hotel staff that explodes when they leave the zlevel

**Comment by ghost** [comment]
> 
> 
> better move is to put a bomb in hotel staff that explodes when they leave the zlevel

today i will bomb the station with 7 respawns

**Comment by ike709** [comment]
you overestimate the size of the bombs

**Comment by zeskorion** [comment]
I could actually code that in...

**Comment by WhyIsCaeciliusTaken** [comment]
Literally just give hotel staff exile implants

**Comment by ike709** [comment]
This isn't even a proper removal. Literally just search `spacehotel` in the code and you'll find the other bits you need to remove.

**Pull request closed without merging**
