### PR TITLE
Gravity Holoparasites

### PR DESCRIPTION
**Pull request by Toxici11i**
## About The Pull Request
Adds gravity holoparasites because people wanted them and i think they are K E W L 

## Why It's Good For The Game

Listed on /tg/ wiki but never coded in

More holopara variety

## Changelog
:cl:
add: adds gravity holoparas (altclick yourself to manifest a chaotic gravitational anomaly that flings everyone(including you and your master if they are close enough) around chaotically - The syndicate, wizard federation and other paranormal entities are not responsible for any loss of life that results as a consequence of misusing this ability
tweak: tweaks guardian.dm to be compatible
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Is this ported from something or did you write it

**Comment by Toxici11i** [comment]
combination of existing shitcode (explosive homoparas) and my own shitcode.

**Comment by qwertyquerty** [comment]
Is this ready?

**Comment by Toxici11i** [comment]
yes it is, tested it and it w o r k s

**Pull request merged**
