### PR TITLE
Removes the assistants' maint access on Sage

### PR DESCRIPTION
**Pull request by Vexylius**
## About The Pull Request

Removes assistant maintenance access on Sage
on Golden assistants will still have maint access.

## Why It's Good For The Game

image

## Changelog
:cl:
config: Assistants don't have maintenance access on Sage anymore
/:cl:

### CODE REVIEW

**Comment by NickEmbased** [comment]
what

**Comment by super12pl** [comment]
angrybert

**Review by Crossedfall — APPROVED** [review]

**Comment by pickleinjar** [comment]
woah woah woah hold the fucking phone man. let the assistants fucking keep it. assistants arent all fucking newbies. we dont wanna fucking wait in the hop line for maint access.

**Comment by super12pl** [comment]
> woah woah woah hold the fucking phone man. let the assistants fucking keep it. assistants arent all fucking newbies. we dont wanna fucking wait in the hop line for maint access.

fun not allowed

**Comment by Effemu** [comment]
cringe and unfunny
obraz

**Pull request merged**
