### PR TITLE
Port a bunch of tg harddel fix PRs

### PR DESCRIPTION
**Pull request by KubeRoot**
## About The Pull Request

Fixes a variety of (potential?) harddels and ports a client_colour refactor ("if its a decent little refactor may as well")
Ports the following tg PRs:
- tgstation/tgstation#55706
- tgstation/tgstation#57387
- tgstation/tgstation#57736
- tgstation/tgstation#57828
  - Tram changes obviously ignored
- tgstation/tgstation#58779
- tgstation/tgstation#58935
- tgstation/tgstation#54741
  - This one is utilised by the next PR on this list. It was ported because the next PR touched this PR's code, and would otherwise not fix anything.
- tgstation/tgstation#56171
- tgstation/tgstation#54820
- tgstation/tgstation#55295

### Note:
I do **not** know how to test all this properly. Those PRs touch upon a lot of things across the entire codebase, I might not even know what might've gotten broken if I ported something incorrectly. I looked over all the changes multiple times to make sure they make sense, or at least seem to do the same thing as the original PRs. I do not however know the codebase well enough to understand all of them, or know the in-game admin tools to test them properly.
The game does, however, compile, start and initialize without any runtimes, so at least that much is good.

## Why It's Good For The Game

Should hopefully help with some lag spikes.

## Changelog
:cl:
fix: modular computers shouldn't leave behind power cells, id cards, or any knick-knack for that matter, anymore when deleted.
code: Td should spike slightly less, assuming harddels actually go down
code: You feel a great disturbance in the force, mob code has changed. Please report any odd targeting behavior on the issue tracker
/:cl:

### CODE REVIEW

**Review by ike709 — DISMISSED** [review]
Code seems okay, obviously this needs to be tested.

**Comment by ike709** [comment]
Seems okay, will wait for another maintainer to sign off & merge.

**Comment by ike709** [comment]
Some suggestions to add:
https://github.com/tgstation/tgstation/pull/54820
https://github.com/tgstation/tgstation/pull/55295

**Comment by KubeRoot** [comment]
> Some suggestions to add:
> [tgstation/tgstation#54820](https://github.com/tgstation/tgstation/pull/54820)
> [tgstation/tgstation#55295](https://github.com/tgstation/tgstation/pull/55295)

Added both of them, once again only rudimentary testing to make sure no runtimes happen during startup

**Review by utilbird — APPROVED** [review]
Can't see anything out of the ordinary

**Pull request merged**
