### PR TITLE
Clown gets a choice beacon!

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Clown gets a beacon with 3 choices:
* Pie launcher (and some pies)
* 5 arcade tokens to spawn toys
* His very own pet Cakecat

Thought of putting it in his box of toys, but that might end with mime/assistant stealing it. Instead, what about it being a roundstart item? Suggestions welcome.

## Changelog
:cl:
add: Clown gets a beacon
/:cl:

### CODE REVIEW

**Comment by Naevii** [comment]
Isn't Cak, chef's pet rather than clown pet ?

**Comment by eeSPee** [comment]
Chef already has pete.

**Comment by ItsTisme** [comment]
> Isn't Cak, chef's pet rather than clown pet ?

Chef has to bake them with a living persons mind, it could be his pet but I doubt it realisticly happens

**Comment by FortSumter** [comment]
Can you name the Cak "Ginger" for me?

As a trialmin I loved spawning a sentient Cak and naming it Ginger and I'd love it if you did that.

**Comment by eeSPee** [comment]
Reworked into pet beacons.

**Pull request closed without merging**
