### PR TITLE
Refactors / Rebalances some gun stuff

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Other weapons can be picked up and fired with 1 hand, however will be a lot more innaccurate.
Light weapons will have an extra 40 inaccuracy and medium sized weapons will have 60 inaccuracy.

When you pick up a gun you will automatically wield it with both hands.
Unlike other two-handed objects, you can swap hands while wielding a gun and it will automatically unwield, freeing your other hand. When you swap back to the gun, if your empty hand is free then you will wield it again.

image

image

If fired with 1 hand the weapons will be inaccurate:
image

<b>Syndicate weapons have significantly reduced inaccuracy when fired with 1 hand, so nukies can still use guns and shields somewhat effectively.</b>

Duel Wielding is now inherently less effective because 1 hand firing a gun is inaccurate, so the multiplier penalty for duel wielding as been reduced.

## Why It's Good For The Game

Guns are now a somewhat dedicated weapon, to use them most effectively you need both hands to be free and will be only effective at close ranges if held with 1 hand.
Combos such as shield in 1 hand and gun in the other are still possible but significantly less effective due to the inaccuracy gained from firing with 1 hand.

Equipping weapons and having them wield feels very natural and is done automatically making it not a painful button mash for new players to figure out.

## Changelog
:cl:
balance: Heavy weapons require two hands to hold.
balance: Light/medium weapons will be less accurate when fired with 1 hand.
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
Could you make shields block projectiles again? I legit had a nightmare last night about dying because stupid shields wouldnt block taser bolts

**Comment by PowerfulBacon** [comment]
> 
> 
> Could you make shields block projectiles again? I legit had a nightmare last night about dying because stupid shields wouldnt block taser bolts

I wouldn't mind shield blocking bullets anymore after this to be fair, but I think its best to leave for another PR

**Comment by francinum** [comment]
Does this come with a generic system for alternative inhand sets?

**Comment by PowerfulBacon** [comment]
> 
> 
> Does this come with a generic system for alternative inhand sets?

I am not really sure what you mean by this, it adds in new parameters for the two-handed component that allow for:
 - Auto wielding
 - Hand swapping to unwield an item

**Comment by francinum** [comment]
> > Does this come with a generic system for alternative inhand sets?
> 
> I am not really sure what you mean by this, it adds in new parameters for the two-handed component that allow for:
> 
> * Auto wielding
> * Hand swapping to unwield an item

A system for automatically updating the inhand icon used for if a gun is in the wielded or unwielded state.

**Comment by PowerfulBacon** [comment]
Nope, but if someone wanted to sprite that they would just need to add update_icon in the wield and unwield proc

**Comment by ike709** [comment]
Fix conflict for merge, ping for it.

**Comment by francinum** [comment]
Wow. I never actually looked too deep at the code.

*this is awful*

**Pull request merged**
