### PR TITLE
Removes the reddit interaction from the server.

### PR DESCRIPTION
**Pull request by Wilchenx**
It was only ever used for griefing and there's several reddit posts about how to grief with this feature.

https://www.reddit.com/r/SS13/comments/e208b8/how_to_make_weebs_angry/

### CODE REVIEW

**Comment by KingTerrytheTerrible** [comment]
VIRGIN Catfaggot vs CHAD Redditor

**Comment by KingTerrytheTerrible** [comment]
just don't play catgirl since it has a negative... play human instead...

**Comment by zeskorion** [comment]
haha
haha
"CHOCLIT MAKING FELIDS BARF IS REDDIT CUZ I DONT LIKE IT"

**Comment by Wilchenx** [comment]
@zeskorion this feature is used for nothing else than griefing

are you going to argue why we should keep it or keep being a redditor


@ ppstation and hippie player
yeah i'm sure we care a lot about your opinion 😏 
image

**Comment by 123chess456** [comment]
don't forget laser pointers better remove that too.

**Comment by Wilchenx** [comment]
@123chess456 that just a harmless interaction

Cocoa is actually lethal.

**Comment by zeskorion** [comment]
> @zeskorion this feature is used for nothing else than griefing
> 
> are you going to argue why we should keep it or keep being a redditor
> 
> @ ppstation and hippie player
> yeah i'm sure we care a lot about your opinion 😏
> image

>>>>weakness only used for griefing

maybe on tg. bee players are too brainlet to even try lmao

**Comment by Alainx277** [comment]
There was huge drama around this in core /tg/, why would we ever merge this into Beestation.

Different races shouldn't be just cosmetic but also have gameplay effects. 
Moreover, in my time playing bee I've never encountered any kind of mass chocolate genocide.

**Comment by ghost** [comment]
Based Wilchen

**Comment by KingTerrytheTerrible** [comment]
> 
> 
> Based Wilchen

die

**Comment by Wilchenx** [comment]
@Alainx277 there was no drama on /tg/ itself, just reddit.

And people were only angry because they couldn't grief anymore.

You're welcome to prove me wrong.

**Pull request closed without merging**
