### PR TITLE
Cult nerfs (and hearing protection refactor)

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
Nerfs a few cult items:

ritual dagger now has 12 throwforce, as opposed to 25(!!)
cult longsword can now be used by non-cultists, but this deals not insignificant stamina and brain damage per hit
lowers cult armor values across the board
mirror shield significantly nerfed: now no longer stuns, instead doing knockdown, has a lower block chance, can shatter from melee attacks, and now spawns with a fixed amount of non-recharging illusions
cult stun reflavored to occult whispers, can't stun through hearing protection

internal: totally refactored hearing protection, allowing more things to use hearing protection. expect a ling nerf using this in the future. Also fixes two items simply by existing; harm alarm and dance grenade (on socially awkward people) no longer bypass hearing protection

## Why It's Good For The Game

cult is a conversion antag where each cultist can very easily get traitor level gear, if not higher. this brings them a bit more in line (though, they are still exceptionally powerful,even still overpowered- but no longer downright unfair)

## Changelog
:cl:
balance: ritual dagger now has 12 throwforce, as opposed to 25
balance: cult longsword can now be used by non-cultists, but this deals not insignificant stamina and brain damage per hit
balance: lowers cult armor values across the board
balance: mirror shield significantly nerfed: now no longer stuns, instead doing knockdown, has a lower block chance, can shatter from melee attacks, and now spawns with a fixed amount of non-recharging illusions
balance: cult stun reflavored to occult whispers, can't stun through hearing protection
fix: harm alarm now cares about hearing protection
fix: dance grenade socially awkward now cares about hearing protection
code: hearing protection refactor
/:cl:

### CODE REVIEW

**Comment by Bastian0930** [comment]
First off, I fucking love you if you did what I think you did with the hearing protection. However, i feel everyone and their mother is going to powergame hearing prot when cult gets called out. I hope this aint the case, cause that'd fuck cults main conversion.

**Comment by zeskorion** [comment]
> First off, I fucking love you if you did what I think you did with the hearing protection. However, i feel everyone and their mother is going to powergame hearing prot when cult gets called out. I hope this aint the case, cause that'd fuck cults main conversion.

There are other ways to convert. Due to co nverstion healing you, crit-and-convert is a valid strategy

**Comment by qwertyquerty** [comment]
vote passed testmerging soon

**Comment by qwertyquerty** [comment]
so uh why are you decomponentenizing something that was fine as a component?

**Comment by zeskorion** [comment]
> so uh why are you decomponentenizing something that was fine as a component?

as a component, hearing protection works for *only*  flashbangs, and nothing much else. Changing it to a var like this allows it to work like flash protection instead, which allows it to work with varying degrees of intensity and making it easier for effects to rely on hearing protection

**Comment by qwertyquerty** [comment]
I'm pretty sure that can all be done with the component too...

this just seems like a reduction of code quality to me

**Comment by zeskorion** [comment]
> I'm pretty sure that can all be done with the component too...
> 
> this just seems like a reduction of code quality to me

I think the opposite. It's a lot easier to code with this way, can actually have varying degrees of intensity now, and is overall less obtuse- the component quite literally only worked for soundbang_act iirc, but all other ear protection things were already tuned to being a number. It's both easier to wirk with and less obtuse this way

**Comment by Unidentified-Biohazard** [comment]
I like all of this excluding the non cultists being able to use swords. Also I am very interested in what you mean about ling nerfs.

**Comment by zeskorion** [comment]
> I like all of this excluding the non cultists being able to use swords. Also I am very interested in what you mean about ling nerfs.

ss13 combat is largely balanced around being able to take weapons from your opponent and murder them with their own weapons. cultist's ability to bypass this is one of their main power factors

**Comment by eLeCtrOssSnake** [comment]
I am not sure that cult nerfs are needed. Although hearing protection refactor is cool.

**Comment by eLeCtrOssSnake** [comment]
Cult win a by stat is like 30% is this OP? If your crew sucks then everything will be OP. Honestly, these nerfs even lower cult win ratio. Items that I(rarely get!!!#@!) when playing cult and that require tons of work with base and crafting become useless...

**Comment by zeskorion** [comment]
> Cult win a by stat is like 30% is this OP? If your crew sucks then everything will be OP. Honestly, these nerfs even lower cult win ratio. Items that I(rarely get!!!#@!) when playing cult and that require tons of work with base and crafting become useless...

that's because bee players are unrobust and dont know how to play cult, not because cult isn't powerful

**Comment by Crossedfall** [comment]
Re-open when you have your commits figured out. The fact that it's no longer attached to a branch puts this PR in an unmergeable state.

**Pull request closed without merging**
