### PR TITLE
Updates ninja suit armour, increase resistance against lethal projectiles, decreases against melee

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

- Decreases ninja armour melee protection from 60 to 30
- Increases ninja laser and bullet protection both to 50
- Increases ninja energy protection to 60 (to match the stamina flag)

## Why It's Good For The Game

https://github.com/BeeStation/BeeStation-Hornet/pull/11820#issuecomment-2452579277

The ninja mobility nerf hit them quite hard, I don't think they are too weak but I think it is far to compensate them with some high protections considering how difficult it is for them to heal. If the removal of laser alpha passthrough goes through, then there is even more to compensate them for.

## Testing Photographs and Procedure

image

Tree with force of 10 deals 7 damage (previously would have been 4).

image

Laser gun deals 10 damage (previously would have been 14)

## Changelog
:cl:
balance: Ninja melee armour lowered to 30, laser and bullet is now 50, and energy is now 60.
/:cl:

### CODE REVIEW

**Review by Rukofamicom — APPROVED** [review]

**Comment by Rukofamicom** [comment]
We'll have to see how it actually pans out, but this is at least something to make up for the loss of using invisibility to dodge lasers

**Comment by Rukofamicom** [comment]
I would honestly rather see them spawn with a variation of the shield belt, given they very specifically have issues with facing ranged weapons now that they can't as easily run away, and also have major issues with having their shurikens used against them. The shuriken issue is so bad that very few ninjas even try to utilize them.

The shield belt solves both problems, without giving them immunity to ranged weapons.

**Comment by Fronsis** [comment]
I'd have to agree with Ruko, giving them a shield belt is more fitting than buffing their armor, because they can still choose when to engage and disengage thanks to the shield and you can still have a fair chance to get them if you managed to get their shield down

**Comment by MarkusLarsson421** [comment]
Don't think a shield is the ideal solution here as the Ninja is supposed to be sneaky and a shield is VERY visible.

**Comment by Rukofamicom** [comment]
I hate to wreck your view of ninjas, but they aren't sneaky at all anymore. The stealth effect on the suit is way too expensive to use all the time, especially now that it has lost its combat utility. They can still be sneaky to a lesser extent than alien Sentinels, but without the x-ray they have no way of knowing when it is safe to be moving and when they need to freeze in place to avoid detection.

**Comment by PowerfulBacon** [comment]
I kind of wish the stealth actually gave you full stealth and not just some half-assed obvious stealth

**Review by Rukofamicom — COMMENTED** [review]
Feel free to claim out of scope, but having been a while I'd like to bring a few points for consideration on ninja and ask if you're willing to make this a ninja tweaks PR instead of just armor adjustment:

* Spawn with a shield belt
* Keep the dash being unable to go through solid walls, but remove the damage from it
* Return the sword to 40 damage so that ninjas can reasonably delimb again - I think the 25 damage sword + damage on the dash was a net loss for both ninja players and their victims
* Make invisibility fade to full alpha now that lasers ignore alpha pass-through, but cancel as soon as they deal or take damage.

**Review by EvilDragonfiend — APPROVED** [review]
Alpha projectile ignore is nerfed. better to merge this
Since ruko remained a review, not gonna merge this yet

**Comment by PowerfulBacon** [comment]
Ruko's suggestions are just a complete reversion of the nerfs, with some buffs from the original. I don't want them to be able to teleport through walls but I am happy to buff their sword to delimbing again. I was thinking of changing how sharpness and delimbing works anyway

**Comment by Rukofamicom** [comment]
I can settle for what you've described.

Like I pointed out in discord already though, I very explicitly stated I do not want them going through walls again.

**Comment by PowerfulBacon** [comment]
This PR has some very large changes coming that are worthy of a new PR

**Pull request closed without merging**
