### PR TITLE
You can now remove individual recipe recordings from chem dispensers.

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

This just adds a delete button next to chem dispenser recordings, allow you to, well, delete recipe recordings.

## Why It's Good For The Game

Because if I mess up a single recording, it's dumb to have to scrap them ALL to get rid of the one bad recording.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/65794972/233536065-94992a36-c18c-4793-8de1-7bf8388941c2.mp4

image

</details>

## Changelog
:cl:
tweak: You can now remove individual recipe recordings from chem dispensers!
tweak: Made the confirmation for clearing all chem recipes a part of the tgui itself.
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
instant removal seems would cause fat finger issue. I think 'clear recipes' button should go removal mode instead, and I believe we really don't need that 'clear all' button...

**Comment by Absolucy** [comment]
@EvilDragonfiend :)
image

**Comment by EvilDragonfiend** [comment]
that works too

**Comment by Eric-01** [comment]
Perhaps you could take some inspiration from PR #8471 and the comments below it?

**Comment by Eric-01** [comment]
Perhaps you could take some inspiration from the PR #8471 description and the comments below it?

**Comment by Eric-01** [comment]
Perhaps you could take some inspiration from PR #8471 and the comments there?

**Comment by Absolucy** [comment]
@Eric-01 @EvilDragonfiend Alright, I've reworked the deletion to work like what was discussed in #8471 

https://user-images.githubusercontent.com/65794972/233536065-94992a36-c18c-4793-8de1-7bf8388941c2.mp4

**Review by itsmeow — CHANGES_REQUESTED** [review]
Really nice, exactly what I wanted. Last thing it needs is changing the recipe icon to either the trash can or a cross (x) icon

**Review by itsmeow — APPROVED** [review]

**Pull request merged**
