### PR TITLE
Reverts zeskos flash changes.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

reverts the flash changes that make flashes useless trash tier and makes them stun borgs for 3 minutes.

## Why It's Good For The Game
because nerfing non lethal options to the point where they are unplayable trash is not how you make lethal options more accesible, borgs also have literally no way to defend themselves anymore.

## Changelog
:cl:
tweak: reverted the flash changes.
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
If we revert this, we'll need to remove wallstuns because flashes need to get a Nerf one way or another.

**Comment by Isy232** [comment]
Only using a flash DIRECTLY on someones sprite should stun. That's how it is on /tg/ and for all their flaws I do not hear people complaining about flashes over there. Removing the confusion from flashes is all that is needed.

**Comment by Isy232** [comment]
In my opinion, wall stuns should only be on Tasers and Cryptobiolin (the chemical).

**Comment by ike709** [comment]
Closing in favor of either https://github.com/BeeStation/BeeStation-Hornet/pull/1584 or keeping zesko's changes.

**Pull request closed without merging**
