### PR TITLE
Pathology: The Future of Virology (Tim's Code Project Circus)

### PR DESCRIPTION
**Pull request by DatBoiTim**
## Pathology What is it?

Well, the idea behind this PR is it makes virology into Pathology. This means that viruses are not the sole kind of disease that spreads around. This will feature a variety of changes outlined below.
This also will expand on curing diseases, to include multiple possible cure chems for each level. But a disease will only ever have 1 cure.

This will rename most instances of Virology to match.

## Pathogen Types

Perhaps the driving force behind the name of the PR is the new types of pathogens available in game. Think like Plague Inc.(which _heavily_ inspired this) plague types.
Pathogen Types are a feature of Advanced Diseases alone. As such, pathogen types will also have heavy influence on how your diseases are made and function. 

Pathogen types also have unique symptoms which activate only under their determined pathogen type. These can be mutated using **REAGENT TBD** as opposed to the existing virochems(Note it will generate any pathogen specific symptom, not current pathogen type). Pathogen types will _ideally_ have an equal number of pathogen specific symptoms.
Beyond this, pathogen symptoms are symptoms like any other.

Pathogen types themselves can be extracted similar to symptoms, or changed using **REAGENT TBD**.

Pathogen Types may also modify various aspects of diseases including capping certain stats to a maximum. (This May or May Not Be Implemented)

### Pathogen Types
Format -> Pathogen Type: Description | Potentially added stat changes(Good > Better and Bad < Worse).
These are subject to change prior to

- Bacterium: Default. No Upsides or Downsides. No Pathogen Type Symptoms. Useless 9/10 times.
- Viruses: Has access to the pre-existing symptoms (Viral Self Adaptation, etc.) | Better Transmission, Worse Resistance
- Funguses(Fungi? Fungis?): Access to Fungal Symptoms, which focus on unique ways to spread the disease. | Better Resistance, Worse Transmission
- Prions: Access to Prionic Symptoms. | Better Stealth and Resistance(look up prion diseases, they're uncureable, and generally are only noticed when infection reaches an advanced stage). Transmission and Stage Speed capped to 4(Prions are not great at spreading around, and take forever to actually affect you) in addition to Bad rating in those stats.(Stage Advancement chances are: 2% or Stage Speed% whichever is higher so a cap lower than 2 is meaningless) (Transmission cap of 2 limits to blood transmission at best)

(yes I know parasites are missing, but I do not know what I want to do with them, if I even want to bother, and nanomachines would be too similar to nanites.)

And finally a pathogen type I may not implement but include anyways since it's extreme(granted it will be uplink only if I add it)
**Bioweapon** Increases Disease power but has a heavy handed stealth penalty. | Special Symptoms which may require a different reagent to mutate.

#### Necrotic Spore Production
On host death, the body becomes infectious to touch.
Transmission Threshold: Wide area to get infected on death.

#### Fomitic Spore Production: 
Objects touched by the infected will be contagious(doesn't work through gloves) for a period of time determined by the transmission.(this will work similar to that sentient disease symptom).
A negative stealth threshold(Get below this number!) You get a small amount of toxins in your system when initially infected.
Stage Speed Threshold more frequent activation.

#### Lymph Suppressant Spores
Increases Stealth a lot and resistance by a smidge. Purely a buff symptom.

#### Bovine Hysteria Disorder
The infected gain an obsession with cows and just cannot shut up about it. Yes this is a joke about Mad Cow Disease(a prion disease). Has decent stat buffs though.

#### Violence Inhibitor Proteins (considering shitty stats on a debatably ehhh pathogen type)Yes I understand this is probably the dumbest thing here.
Pacifies the infected. Has very bad stats overall, and will probably be weighted as a rare roll. This will either get you lynched once cured(cause they won't be able to hurt you while infected) or awarded a nobel peace prize depending on the opinions of those in charge. Only takes effect on stage 5 and goes away when cured do not rely on this as a quick solution or permanent to your problems. Slow to activate as well, so even when it hits stage five it may take a few minutes to kick in.

#### Neurological Spongiform Necrosis(What Prions are known for)
Less shitty stats, but not good. Does pretty heavy braindamage, with a high maximum. Pretty good for assassinations, but good luck with anything else. At resistance 20 abandons brain damage and heals deep rooted traumas. I doubt it will be used as such, since it is gonna be a pain to do for 1 solo guy who suffers that and doesn't want to fucking die.

## Varied Cures

More Potential Cures Added. Cure Generation will still happen as usual, and will attempt to follow the same sort of idea behind how cures are selected.

I also Rearranged Where Saline Glucose and Spaceacillin are placed in cure tier
### New Cures by Resistance

<1(Harmless Active, available from Chem dispenser): Sugar, Iron, Oxygen, Copper
2(Mildly Harmful from chem dispenser): Welding Fuel, Lithium, Fluorine, Chlorine
3(Simple Chems, Non Harmful): Ash, Ammonia, Lye
4(Simpler Medicinal Chems): Dexalin Plus, Charcoal, Tricord
5(Advanced but Medicinal Chems): Diphenhydramine, Mutadone, Hepaneph
6(Medicinal Chems that may be unpleasant depending on how you ingest them): Styptic, Silver Sulf, Carthatoline
7(Not sure why leporazine is here, not complicated, nor unpleasant. Whatever.): Epinephrine, Psicodine, Corazone
8(Annoying and extremely niche chems, mostly non harmful. Some External Cooperation Needed): Colorful Reagent,  Pax, Spray Tan
9(Mild Poisons): Fentanyl, Weed killer, Sulfonal
10(Unpleasant Medicines): Morphine, Salycilic, Oxandrolone
11+(Somebody is going to have a very bad time being cured, also complex): Bath Salts, Ketamine, Rotatium, Modafnil

## To Do

- [x] Pathogen Types
- [ ] Pathogen Symptoms
- [ ] Rename Things
- [ ] Varied Cures
- [ ] Wiki Changes

## Why It's Good For The Game
Adds more depth, and rewards those who master it. Adds more variety to the job. Creates a new, unique experience with a wide range of possibilities. Lays groundwork for future development on this system.

I know changelog is empty. I do not know quite yet what will be changed. I will be finishing changelog before opening PR fully.

## Changelog
:cl: Dat Boi Tim
add: Added new things
add: Added more things
del: Removed old things
tweak: References to Virology are now Pathology
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by yorii** [comment]
So if I understand this correctly, the pathogen system is complementary to the current virology system and not a replacement?

**Comment by DatBoiTim** [comment]
> So if I understand this correctly, the pathogen system is complementary to the current virology system and not a replacement?

Correct. Pathogen type just changes the usability of a handful of symptoms at the least. At most it does that and some stat changes. Aside from this it is mostly just a difference of text.

**Comment by DatBoiTim** [comment]
Gonna close this for a bit to settle some details.

**Comment by ItsTisme** [comment]
Fungi maby should have high transmition but low resistance/stage speed. Also how would this would with the current sytomps we have?

**Comment by ItsTisme** [comment]
Also Oxandrolone is  a easy chem to make and not a unpleasent chem to ingest. So it has no reason to be on level 9 especialy compared with morphine.

**Comment by yorii** [comment]
Hot tip: use modafinil as a high level cure, it's a pain to make

**Comment by DatBoiTim** [comment]
> Also Oxandrolone is a easy chem to make and not a unpleasent chem to ingest. So it has no reason to be on level 9 especialy compared with morphine.

Honestly the cures are really weird and don't follow a clear gradient of any kind.

Additionally, unless wiki is wrong, it does stamina damage or whatever exhaustion means.

**Comment by ItsTisme** [comment]
Pretty sure thats sulfadine. it still is a very minor setback compared to morphine or even pax and is deffintly harder to make then epi

**Pull request closed without merging**
