### PR TITLE
No shove paralyze

### PR DESCRIPTION
**Pull request by FriendlyContractor**
## About The Pull Request
Shoving will no longer under any circumstance paralyze or cause person to drop items
## Why It's Good For The Game
Shoving is currently horribly broken game mechanic which ruins combat. It leads to ridiculous situation where armed person is often at disadvantage in combat against bare fist as in order to neutralize their opponent they need to hit them multiple times while UNARMED person can in most situations click on them twice to completly paralyse and proceed to kill them with their own weapon. Situation where you start a combat by paralysing somebody bare handed and then pulling out a weapon is equally bad and unfun. Combat should be about attempting to match opponents weapon or landing proportionally more hits - NOT clicking twice to completly disable them. Shoving will remain viable option to slow down your opponent and escape/prevent them from escaping but it will no longer be able to instantly win a fight alone
## Changelog
:cl:
balance: Shoving can no longer paralyse and make others drop their held items
/:cl:

### CODE REVIEW

**Comment by FriendlyContractor** [comment]
I wanted to do this for a looooong time. The time finally has come

**Comment by BrumalLake** [comment]
> 
> 
> I wanted to do this for a looooong time. The time finally has come

oh yeah, cause everything that gets put in a pull request is guaranteed to get merged
maintainers and players have no choice 🤡

**Comment by mcmeiler** [comment]
Diagnosis: Skill Issue. Also massive copium consumption.

Here's how to not get shove stunned: *don't stand next to shit in combat*
I seriously don't get what's so fucking hard about not doing that.

**Comment by FriendlyContractor** [comment]
I have no doubt its going to cause large uproar and large doubt its gonna get merged but i sincerely belive its good for the game and it is worth a try. Also your are basically just salting without any constructive arguments

**Comment by ToasterBan** [comment]
reject shove
return to rng disarm

**Comment by mcmeiler** [comment]
> Also you're* are basically just salting without any constructive arguments

I believe you missed the point. This *looks* and *feels* like a salt PR more than anything.

You didn't even consider the amounts of balance issues this would cause, did you?

Combat should be about tactics, not spamclicking or using a macro/autoclicker to win.

**Comment by FriendlyContractor** [comment]
Its something i wanted to do for well over a year. I fail to see how not being able to bum rush armed traitor/security officer is balance issue

**Comment by mcmeiler** [comment]
I seriously fail to see your point here. The intent is called "disarm" for a reason. Besides, if you have a weapon. *blocking is a thing that completely stops any attempt at shoves but, once again, requires skill to use.*

There is literally no point to doing this as blocking already fulfills this purpose completely, and even better, as bladed weapons will *counter-attack* people who attempt to shove, hit, hug or grab you if you block with them correctly.

I stand by my point. Skill issue.

**Comment by Sinestia** [comment]
> 
> 
> Its something i wanted to do for well over a year. I fail to see how not being able to bum rush armed traitor/security officer is balance issue

🤔 

If you want combat to be less of a joust then slow down movement speeds tbh

Not that I think bee players would want that but hey

Or figure out a more complex way to change how combat works like stances (but holy shit normie players could not handle that.)

**Comment by zeskorion** [comment]
The guy who first reworked shoving away from rng wanted shoving to be like this. Paralysis when shoving was added to appease the /tg/ admins 

I do think shoving should be significantly changed away from shoving into walls tho

**Comment by BrumalLake** [comment]
anyone with hands can shove so why can't security and antagonists do it
there's also adrenals and
you're making anti drop almost pointless
also
>>you're* are

and
>your are

shoving is the equalizer of the unarmed person who doesn't powergame and antagonists that will become zombies because they know that they can just keep clicking while their target can't do anything but punch them or run

fighting will devolve into a matter of who has the bigger number on their weapon and who can click faster

**Comment by OceanFish1** [comment]
Ided pr

**Comment by francinum** [comment]
....Holy shit I have some bad takes on the combat in this game

This is next level copium.

if you have gun, don't get close to people, the problem is right now everyone on the station can close the gap before you can react.

🔑

**Comment by Archanial** [comment]
Ided

**Comment by chizzy376** [comment]
Wew lad. What being horribly unrobust does a mf, keep on injecting that copium or just git gud

**Comment by OceanFish1** [comment]
Beestation is newbie friendly

**Pull request closed without merging**
