### PR TITLE
Removes ability to screwdriver grenades to shorten their fuse to 1 second

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

- Removes ability to screwdriver grenades to shorten their fuse to 1 second

## Why It's Good For The Game

This isn't well balanced on either ends. Security gets an AOE stun which they don't even have to aim and traitors get instakills with their minibombs. Both are one hit kills, essentially. How this is good balance is beyond me. The weakness of these handheld bombs is that they take time to go off, and this just bypasses it.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

https://user-images.githubusercontent.com/22431091/184259120-b0fbc237-1437-48ec-8610-efd1ea5c9a7e.mp4

</details>

## Changelog
:cl:
balance: removed ability to screwdriver grenades to shorten their fuses to 1 second
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
3 seconds is still quite some time. I don't think this is a necessary nerf.

**Comment by Coding-Grape** [comment]
I don't think this is necessary, maybe make flashbangs have a weak explosive component in them that can blow the arm off of the idiot if they're holding it, afterall it's a 
Flash 
**bang**

**Comment by Fronsis** [comment]
I thought using the flashbang in-hand even if you had glasses and sec headset would still put you on the ground, eh idk i always liked customization of timers, specially for people with a little more high ping like me, maybe there should be a SOP that it needs to be idk blue alert for officers to customize timers on nades, cite OSHA or something like that

**Comment by ivanmixo** [comment]
The current "meta" strat is to shorten the fuse to 1 or 3 seconds then throw it instantly. The problem isn't them holding it in their hand waiting to detonate. If you want to cook nades there should at least be some timing and skill involved.

**Comment by Coding-Grape** [comment]
Sure, but IRL you don't cook grenades due to something called fuse variation 

In fact there's a spoon that you are supposed to keep hold of after pulling the pin which is spring loaded and flies off as you throw it, starting the fuse 

Maybe a better solution would be making it so you *can't*  edit the fuse on things like flashbangs, maints smoke grenades, and minibombs instead of nerfing chem grenades which actually take thought to make

**Comment by ivanmixo** [comment]
You couldn't screwdriver the fuse on the chem nades to begin with. Try it right now and it won't let you.

**Comment by DerpiestBruh** [comment]
Make grenades be random so they activate sooner or later

**Comment by FortSumter** [comment]
Personally I'd like to have any PRs related to trying to balance combat to be pit on hold until someone actually fixes the real problem of medical necromancy.

One hit kills are only the meta because it's so fucking hard to kill someone the "right" way and even then it doesn't matter because you'll also have to kill the paramed that showed up to steal your assassination target and the 3 secoffs that got alerted by the paramed yelling over coms and escape the room the AI bolted you in. Even if you manage that, if there's a single drop of blood or if they manage to recover the brain all that was for nothing.

You all cry and bitch and moan about antags being non RP and the good ones being a bunch of fucking tryhards but when you keep removing combat options without addressing or acknowledging the other aspects how do you expect anyone to do anything else but try hard?

When I get antag with a murder objective now I just don't do my objectives. I was a changeling bartender recently and I had a patron who willfully drank themselves to death. Not a second after they did so and I was about to drag them away for some fun times a paramed was already there, almost fighting me for the corpse had I not decided to bring them to med.

**Comment by ivanmixo** [comment]
Odd how I never have such strawmanny issues with murder.

**Comment by FortSumter** [comment]
> Odd how I never have such strawmanny issues with murder. Also this directly removes the sec cheese insta flashbang strat.

I've personally never seen the insta flashbang strat since it also blinds the officers even through sechuds and when I'm antag I'm either so careful never to get sec after me to begin with or go and get my own set of bang-proof gear.

I'm not a robust chad toolboxer. I'm not very good at making players go sideways even when I've got the best gear for it, and for the described reasons and more it is harder than ever to get a clean kill outside the targets own negligence, willful or otherwise. If your target is a member of command staff you are truly fucked outside of bombing them because now they all got their shitty disabler pistols, access to armor, maxed suit sensors, their command batons, and loud mode headsets along with of course locking themselves in their office where you can't reach them or otherwise escaping.

I've played on bee for over 2k hours, I know what the fuck I'm talking about and know how to antag. If I can't feel confident enough to kill so much as an assistant even with all the gear in the world, how do you expect a sub 500 hour player to do it and not give away the game mode in the first 5 minutes? Why do you feel you have to make nerfs like this to some of the only reliable tools you can get without using antag points? Tell me how a BB is supposed to kill a competent and perhaps paranoid captain without bombing them and get away with it? By toolboxing them?

**Comment by ivanmixo** [comment]
How does this have anything to do with my PR? Do BBs get access to minibombs?

Sec being blinded by their own flashbangs hardly matters if it doesn't knock them down + it hardstuns the target, so.

**Comment by possumcontent** [comment]
i think he's tryin to say that maybe instead of grenades people should be staring at medical

**Review by PowerfulBacon — COMMENTED** [review]
Whats the problem with these? You can make instantly exploding grenades, but then you die too. I'm fine with removing the 1 second option though, we should keep the ability to icnrease the timer

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
I'm fine with 3, 5 and instant exploding. 1 second is clearly a problem since you can prime it, throw it and have no time for other people to react without injuring yourself in the process.
At least the longer 2 give the other people time to react too

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
