### PR TITLE
Removes Squidpeople from the codebase

### PR DESCRIPTION
**Pull request by Kapu1178**
## About The Pull Request
AUTH: Crossedfall

## Why It's Good For The Game
image

## Changelog
:cl:
del: Squidpeople, their mutation toxin, and Rlyehian.
/:cl:

### CODE REVIEW

**Comment by Troontjelolo** [comment]
Bay **doesn't** have squidpeople, thus obviously this is plannedemic.

**Comment by Effemu** [comment]
cope, we don't want your furry races

**Comment by francinum** [comment]
I'd request retaining the language for comedy reasons, but it's removal isn't the biggest crime either.

**Review by francinum — APPROVED** [review]

**Comment by Kapu1178** [comment]
> 
> 
> I'd request retaining the language for comedy reasons, but it's removal isn't the biggest crime either.

we're running out of language keys and I'd rather let it's key be used for something useful.

**Pull request merged**
