### PR TITLE
Scavfab and Design Upload Console

### PR DESCRIPTION
**Pull request by Baldir-Odensen**
## About The Pull Request

this adds a special techfab and design upload for said techfab. This is to be used by the scavengers when they are added.

## Why It's Good For The Game

This would when the scavengers are added give them more depth and ability to construct their own gear while not using the stations research.

## Changelog
:cl:
add: A new tech net separate from the science research.
add: The Scavfab a special techfab that is conected to its own science net.
add: The Design upload Console. a rd production console conected to the same net that is to be used to upload designs into so the techfab can produce them.
code: added the scav departmental tag to a whole bunch of items to make sure that it can not build rd consoles, camera consoles among other things. As the other option was letting it be able to build everything
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Fails travis.

**Comment by Baldir-Odensen** [comment]
> Fails travis.

fixed it it passes now

**Comment by qwertyquerty** [comment]
You screwed up line endings in a lot of files. Fix those, and the conflicts.

**Review by qwertyquerty — CHANGES_REQUESTED** [review]
fix line endings and conflicts

**Comment by qwertyquerty** [comment]
@Baldir-Odensen ?

**Comment by qwertyquerty** [comment]
@Baldir-Odensen

**Comment by qwertyquerty** [comment]
stale

**Pull request closed without merging**
