### PR TITLE
Reworks and fixes Ethereals using cyborg rechargers.

### PR DESCRIPTION
**Pull request by dekunutkid**
## About The Pull Request
Before this change, cyborg rechargers were broken and gave Ethereals nothing but charge, when it was supposed to give charge and blood. 
This however, gives them the real ability to generate blood, however at the cost of their own charge while inside, the amount of blood gained per second scaling with the tier of the Manipulator.

## Why It's Good For The Game
Cyborg rechargers used to be broken for Ethereals, not giving any blood at all. without any other way to regenerate blood, it was a death sentence to bleed out, with the Ethereal being forced to clone.
This will prove a vital fix that helps keep Ethereals alive.

## Changelog
:cl:
add: Added messages to Ethereals when entering a cyborg recharger, when at full blood, and when at low charge, for better feedback.
tweak: Cyborg rechargers now remove charge from Ethereals, converting it into blood.
fix: Cyborg rechargers now properly give blood to Ethereals.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
`when it was supposed to give charge and blood.`

lol says who

**Comment by dekunutkid** [comment]
> lol says who

the code. it was originally written to give charge and ethereal blood as a reagent, but that does nothing.

**Comment by ghost** [comment]
whoever added that is an omega chumbis, its not ment to give LE. Just ask for LE from a doctor who should start with LE bags

**Comment by dekunutkid** [comment]
But they don't, so I'm providing a good alternative that actually works all round, instead of once for one person per round. also giving actual use to ethereals sitting in cyborg rechargers.

**Comment by ghost** [comment]
it makes the blood trivial which circumvents the entire difficulty of playing as another race. just make a way to produce LE bags or make them a cargo purchase instead of invalidating the entire challenge.

**Comment by dekunutkid** [comment]
> it makes the blood trivial

Blood is trivial for every race

**Comment by ghost** [comment]
not for ethereals

**Comment by dekunutkid** [comment]
because the code was _broken_

**Comment by ghost** [comment]
yes im making a point about how its a dumb change to begin with.

**Comment by ike709** [comment]
I agree with floyd, borg rechargers shouldn't give LE. Just map some in for medical.

**Comment by dekunutkid** [comment]
Then I’m just wondering, what’s the point of cyborg rechargers for ethereals? When ethereals were made the cyborg rechargers were meant to be their main source of blood gain. I’m trying to keep to the original vision and make them function as intended.

**Comment by ike709** [comment]
> When ethereals were made the cyborg rechargers were meant to be their main source of blood gain.

Uh considering Floyd created Ethereals and said that rechargers giving LE is dumb, I don't think that's the case.

**Comment by dekunutkid** [comment]
Then... why even bother with any of that code about giving ethereals the LE reagent while in the charger...?

**Comment by ghost** [comment]
its not something I added originally so dont ask me someone on this codebase did.

**Comment by dekunutkid** [comment]
How about a simple fix to make LE less trivial?
> H.blood_volume += repairs*2+5

instead:

> H.blood_volume += repairs+5

**Comment by dekunutkid** [comment]
I, at least, want Ethereals to be accessible and at least partially self-sufficient, instead of being forced to rely on cargo for blood bags or medical to know what a bloodbag is.

**Comment by Cornarias** [comment]
Bit of a wall of text, but bear with me. Because I think this is worth considering:

Saw this PR cause I've been getting into the Ethereal race lately. Lots of fun with the changes, but this is a serious issue I've noticed as well. I'm taking dekunutkid's side with the overall idea, but maybe not the values given. Races should obviously be generally weaker than humans, with unique aspects to set them apart. The former to make it so humans are the norm, the latter to actually make them appealing at all.

Issue with what Qustinnus / Floyd is saying is twofold, though.

First, this is Bee, not TG. For TG, yeah, Ethereal's having a downside like this is fine. TG's medical system is a lot more convoluted, and medical is an overall more lengthy process. On TG, _anyone_ losing blood is an issue. Bee's medical is a lot more streamlined, using the older system. So Ethereals stand out a _lot_ more.

Next, Ethereals already have a notable disadvantage. 25% more brute damage taken means that you are basically guaranteed to lose any fair fight that doesn't involve energy weapons. If it *does* involve energy weapons, then you're pretty much going to die anyway because it's likely a desword or some other kind of tot gear. Brute weapons are in abundance and tend to be the weapon of choice.

Add to that, losing blood and _not being able to gain it passively_ isn't good as far as gameplay is concerned. There's no gameplay there for anyone. As an ethereal: Grab an energy bar and bandage yourself. If it's significant, go to medical. For medical? Shove a needle in him and walk off. The only time it's really relevant is when you lose a significant amount of blood and there's no medical staff to help. Because then you're either dead or chowing down on every energy bar you can find.

No other race has a weakness that amounts to "Go to medical or die" for getting some glass stuck in its foot. No other race is bound to a _very limited station-start resource_ with the only option being _more from cargo_.

**Why I like the idea, numbers aside:** The gameplay this offers is actually great. Think about it. Blood upkeep is easier overall, but is going to require a fair bit of time. Losing blood isn't "Find a bunch of energy bars and eat them while walking about", especially early in the shift. It keeps pace with Bee (especially Sage. If it's too slow for Sage I fear for Golden), but **most importantly** it makes the medical process with Ethereals more fun.

Since Ethereals take toxin damage from low charge, bringing an Ethereal back to life for medical isn't just "Shove in a needle, ask Cargo for another blood bag for later, call it a day". Medical will have to account for the toxin damage taken, since the ethereal this low on blood simply won't be able to charge himself. It's also like IPCs and Plasmamen in the sense that medical should know how to treat non-organic races on a case-by-case basis.

I've not tested the numbers, but if they're the issue, tweak them. Maybe make it deal toxin damage once charge is out as it tries to draw power that isn't there. Maybe make going over the blood level short-circuit the nearby area and deal heavy burn to the ethereal (and cause a significant wound that bleeds again). Make it require thought to use.

That's my 2 cents. Good change, regardless of what the original intent of the Ethereals may be. Especially considering it is balanced for what is now a very different server.

EDIT: It just occurred to me you could make the claim that the station-start scarcity applies to Plasmamen. It does not. Plasma is in abundance across the station, and as a Plasmaman almost no one will deny you a tank of the stuff. You can print half the things they need from a lathe, and their envirosuits have alternatives which are also across the station. This isn't accounting for their many benefits such as literally being immune to radiation and disease, among other aspects. (Yes they have other downsides to balance it out overall. But I feel it's in a far better spot than Ethereals.)

**Comment by ghost** [comment]
like i said before, I disagree with this PR not because it adds more way to get LE, I disagree with it because its trivially easy. If you made it atleast take some basic level of communication or interaction to get atleast itd be a good solution. Instead this is just "sit in a can while you go take a piss"

**Comment by Cornarias** [comment]
> 
> 
> like i said before, I disagree with this PR not because it adds more way to get LE, I disagree with it because its trivially easy. If you made it atleast take some basic level of communication or interaction to get atleast itd be a good solution. Instead this is just "sit in a can while you go take a piss"

I agree that if this ends up just being "sit in and wait" it's bad. But I think that comes down to numbers. The idea behind it I really like.

IMO removing the safety net would go a long way. Staying in too long and running out of charge / getting too much blood and overflowing should have repercussions. Would fix that "go take a piss while you charge" issue, and also again be more engaging for medical, _and also_ making a glass shard in your foot not one of the most frustration-inducing things to have happen as an ethereal while still being an issue due to no passive blood gain.

**Comment by ghost** [comment]
on tg it has repercussions, you turn into a dangerous zap bomb. Either way though; making it faster isn't what I see as solution, I'm just saying that this change would just make it a very uninteresitng way to have to get blood back which involves zero interaction with other players

**Comment by Cornarias** [comment]
I will say, in my opinion the speed for Bee is required. I play on both TG and Bee and Bee, even Sage, is **much** faster. But just making it faster by itself isn't a good fix, agreed.

If possible, I think it should be a more engaging process overall.

I wonder if making running dry more dangerous / overflowing could be added to making the use of the cyborg charger more difficult by yourself? A borg can easily open it, of course. But you would have to struggle to get out unless someone opened it from the outside? Might be a bit hamfisted.

Any ideas?

As for dekunutkid would it be possible to make it more dangerous and interactive overall? I like the idea a lot, but I agree there needs to be more interaction or something a bit more dynamic overall. Would help keep that unique feeling of non-human (especially inorganic) races, too.

**Comment by dekunutkid** [comment]
Alright, so, from what I see, Qustinnus, your issues are that it's not interactive enough with other players and too easy to actually do.

I understand your concerns of not wanting to sit and forget, but I think the alternative of using blood bags is boring and doesn't set the ethereal's medical procedure apart from any human. I want to give more ways for ethereals to gain LE but ideally in a unique way.

For the problem going in by yourself, I could remove the limits of the high blood and low charge thresholds, and make you take damage for being inside too long, so that you're not sitting in there for 5 minutes while you go AFK to come back with full LE.

I'm open to suggestions, though.

The main goal was just to give ethereals a significant and unique way to gain LE with its own pros and cons.

Sorry for the misunderstanding, as I thought you were just saying to add more blood bags.

**Comment by Isy232** [comment]
LE mixed in chem?

I know blood + teslium could make sense, just make it produce a fuckton since teslium is hard.

Or LE blood duplication with UM like normal blood.

**Comment by qwertyquerty** [comment]
Have we come to a consensus yet

**Comment by dekunutkid** [comment]
Not really, the people who have commented think I should throw the PR out entirely or entirely rework it. 
However I have yet to receive any feedback on how I can change it into a viable form, and its current state being the best I could come up with on my own.

**Comment by dekunutkid** [comment]
Fixing the conflict did some weird things.

**Comment by dekunutkid** [comment]
No input, so I've given up.

**Pull request closed without merging**
