### PR TITLE
Lower monkey cube production amounts for xenobiology.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Lowers the amount of monkey cubes produced by xenobiology slime extracts.

Industrial grey 5 -> 1
Regular grey 3 -> 1

Part of xenobiology self-sufficiency rework.
https://github.com/BeeStation/BeeStation-Hornet/pull/3831
https://github.com/BeeStation/BeeStation-Hornet/pull/3825

## Why It's Good For The Game

Xenobiology self sufficiency is off the scale, compared to other departments. It requires no interaction with outside world to reach their highest tier products. This change moves xenobiology slightly towards considering the existence of alternative methods for their production line.

## Changelog
:cl:
balance: Lower monkey cube amounts from slime extracts.
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
this change would make xenobio near useless


I like this change

**Comment by BitBite112** [comment]
How will you ever be able to use reproductives in the beginning when you can only get one monkey cube from grey extracts?
The industrial grey change will only result in having to click 5x as more, which is annoying, but will still be able to be self sufficient in monkey cubes, but will lead to more finger pain.

This change has been poorly thought out to the point it can make xenobiology completely impossible to do.

**Comment by Mat05usz** [comment]
Bruh no. What this will do is just annoy the fuck out of people because now they'd have to spend hours in xenobio to get anything useful, experienced xenobio people start getting things at around 40/50 minute mark, rounds usually end 60-90 minutes in, this leaves ~30 minutes of actual FUN (you know, the thing why we're playing spessman simulator). Also you'd make things like reproductive grey nearly useless, because you'd have to use 3 grey slime extract for monkey cubes and in result have a 50% to get less than what you used, 25% of getting the same and 25% of getting one more. 

>  This change moves xenobiology slightly towards considering the existence of alternative methods for their production line.

Like what, botany that you're nerfing too? Seriously, what are the alternative methods of monkey cube production?

**Comment by RDS88-beeman** [comment]
I have a few issues with this
first off all, to get this out of the way
nuuuuu how dare you nerf muh slimes

second of all
if you're going to nerf the self sufficiency at least give us some more boxes of monkey cubes at the start

third of all
there are many ways to improve interaction with the outside world outside of just applying the nerfhammer
taking viro as the holy grail of interaction, which it isn't but lets just say viro was a good change
zesko didn't just take the easy way out and quarter the chance of synaptazine/formaldahyde working because that would be dumb
he added, and shuffled things around, and made the job need to leave it's little corner of the world to get it;'s most advanced functions while still letting it FUNCTION without doing so
and he **added** things, as incentive to leave, rather than just delete delete delete

_**if you want to encourage xenobio to interact, this is not the place to start**_

if you want to ruin xenobio because you dislike people having fun, go right ahead

**Comment by ghost** [comment]
There's plenty of alternative sources for monkey cubes. You can order them from cargo, you can print them at botany in the hundreds with minimal upgrades and effort. But you have to leave your lab.

You can still cheese any resource requirements with multi-use extracts and completely ignore the outside world. It just wont be as easy.

**Comment by RDS88-beeman** [comment]
> Like what, botany that you're nerfing too? Seriously, what are the alternative methods of monkey cube production?

oh and because i gotta play devils advocate you can buy cubes from cargo. But with what cash? What bargaining chip? Sure, the adamantine bounty that you may or may not get and that may or may not pay for itself

**Comment by ghost** [comment]
@RDS88-beeman 

Every department has their budget, science one is never used for anything as they have no need for the outside world besides waiting for miners. Now they have a use.

**Comment by Mat05usz** [comment]
> > Like what, botany that you're nerfing too? Seriously, what are the alternative methods of monkey cube production?
> 
> oh and because i gotta play devils advocate you can buy cubes from cargo. But with what cash? What bargaining chip? Sure, the adamantine bounty that you may or may not get and that may or may not pay for itself

Okay I forgot about cargo. So we have multiple alternatives being botany (that they want to nerf) and cargo, nice.

**Comment by ToasterBan** [comment]
> There's plenty of alternative sources for monkey cubes. You can order them from cargo, you can print them at botany in the hundreds with minimal upgrades and effort. But you have to leave your lab.
> 
> You can still cheese any resource requirements with multi-use extracts and completely ignore the outside world. It just wont be as easy.

1. a job shouldn't be self sufficient but not fucking leaching of another job

2. cargo cubes are stupidly expensive for a single box

3. the biogen is rarely used and having a department that is normally very far away, so unless you expect someone to track halfway trough the station every 10 minutes

**Comment by ghost** [comment]
@bluezorua 

>you expect someone to track halfway trough the station every 10 minutes

That's the idea yes.

**Comment by RDS88-beeman** [comment]
could you answer the rest of my complaints please?
> Why are you doing this in the first place?
> Why aren't you considering any other options rather than just curbstomping the main balance
> Have you considered all of xenobio is balanced around the three cube number?
> Why won't you give us more cubes at roundstart, if this is because Ruko said so he also said that

> **Why are you taking the laziest route instead of doing something interesting and actually fun for literally anyone that actually plays the job**

> > you expect someone to track halfway trough the station every 10 minutes
> 
> That's the idea yes.

have you realised this is terrible for... you know... having fun? Like we're all here to do?

**Comment by ToasterBan** [comment]
also most jobs that require someone else normally only require them once or twice



mining requires 3 or 4 techs

botany requires science upgrades once which require mining

virology requires either maint access and one or two purchases of experimental desease crates

genetics has to go around the station to find mutations

**Comment by ghost** [comment]
You get 0.8 monkey cubes for every recycled monkey. You're using 0.2 monkey cube per a single feed operation. You're using 0.4 monkey cubes to split a slime. You get several slime extracts and can apply multi-use extract on top of it.

You're not even using half a monkey cube to create more several more. With current numbers it's just insane exponential growth, this brings it to sanity.

**Comment by ToasterBan** [comment]
> You get 0.8 monkey cubes for every recycled monkey. You're using 0.2 monkey cube per a single feed operation. You're using 0.4 monkey cubes to split a slime. You get several slime extracts and can apply multi-use extract on top of it.
> 
> You're not even using half a monkey cube to create more several more. With current numbers it's just insane exponential growth, this brings it to sanity.

this is AFTER the monkey recycler has t4 parts, which removes the point if talking to someone else as a scientist could do that

**Comment by ghost** [comment]
Oh no, you mean science has to rely on science to upgrade science machines to be slightly more self reliant?

**Comment by WhyIsCaeciliusTaken** [comment]
Hmm yes feed the grey crossbreed three monkey cubes to get...

three monkey cubes.

Did you even think this through?

Also hello Belone alt. EDIT: You're not a Belone alt. Sorry, my mistake. You didn't need to be so hostile and dramatic over it though.

**Comment by Alfred-Collins** [comment]
> Hmm yes feed the grey crossbreed three monkey cubes to get...
> 
> three monkey cubes.
> 
> Did you even think this through?
> 
> Also hello Belone alt.

sus al-amogus

**Comment by ghost** [comment]
> Hmm yes feed the grey crossbreed three monkey cubes to get...
> 
> three monkey cubes.
> 
> Did you even think this through?
> 
> Also hello Belone alt.

Not sure who you're accusing of being an alt (and I'd appreciate if such offtopic discussion was kept elsewhere), however as to your comment about the PR:

Are you implying that you should get more monkey cubes than you spent? You can apply multi-use extracts on the resulting product for net gain.

**Comment by ToasterBan** [comment]
people will just rush industrial greys like they normally do just with more trouble and still have infinite cubes

**Comment by WhyIsCaeciliusTaken** [comment]
Additionally, while xenobio needs a significant nerf or to be forced to rely on other departments, cooperation should be required for *advanced* parts of the job, such as crossbreeds, not the basic functions of the job. All you've functionally done is make xenobio play RnD for 20 minutes before starting. There is no gain of player interaction or even a significant nerf to the actual overpowered parts of xenobiology. The only thing this does is dick around scientists for a short period.

> Are you implying that you should get more monkey cubes than you spent? You can apply multi-use extracts on the resulting product for net gain.

Yes... that's the entire point of the item.


If you actually want to nerf xenobiology, make crossbreeds require a special resource which xenobio cannot obtain by themselves. Better crossbreeds should require more of said resource.

**Comment by ghost** [comment]
>Yes... that's the entire point of the item.

Then it's a badly designed item.

@bluezorua

>people will just rush industrial greys like they normally do just with more trouble and still have infinite cubes

That's good.

**Comment by Alfred-Collins** [comment]
> > Yes... that's the entire point of the item.
> 
> Then it's a badly designed item

I agree with you, xenobiology is too powerful and requires hard nerfs.

**Comment by ItsTisme** [comment]
Like everyone said, this just makes the xenobio jobs alot more annoying instead of fixing any of its power issues. Not to mention the other PR that increases the monkey cube price to 5k with unupgraded biogen flys in the face of it

If this PR goes and gets merged, they only need supply of cubes at the start of the shift(since they will go for industiral as always). Not only wont science have alot of budget at that point to buy cubes but the other PR that makes bio gen cubes cost a fortune also means they cant provide a meaningfull amount. This will make just everything more frustrating for everyone.

**Comment by ghost** [comment]
@Autisem

It might seem unbelievable to you, but even when xenobiology had to manually drag slimes and monkeys into pens, spray water over them and grind the slimes by dragging into a machine, they were still powerful and fun to play without crossbreeds or insane powers they get now.

The intense feature creep, money being thrown to buff the department further and complete disregard for any sane design, lead to what we have now. A spoiled playerbase used to easy powergaming gear with minimal effort and no outside interaction.

**Comment by ItsTisme** [comment]
>It might seem unbelievable to you, but even when xenobiology had to manually drag slimes and monkeys into pens, spray water over them and grind the slimes by dragging into a machine

I can believe it, because toolbox station still has this. And you can actuely buy upgrade disks to unlock the more advanced features which I think would be a good idea.

But what will this PR do to stop any of that other then making it more annoying? All the slimes are still as OP as ever and getting industrial slimes will have the ininfty production per usual. All this does is move it later into the round(which xenobio already takes long to begin with)

**Comment by WhyIsCaeciliusTaken** [comment]
> > Yes... that's the entire point of the item.
> 
> Then it's a badly designed item.
>

You mean an item designed to produce an item producing an item is bad design? Also I note you've completely ignored all of my other points as to why this nerf is the wrong approach. Please do tell how ignoring all of the issues with xenobio and instead just making them more annoying to play as in the first 20 minutes of a round is a useful fix to the department?

**Comment by ghost** [comment]
>You mean an item designed to produce an item producing an item is bad design?

The bad design comes from getting more of the same item as you invested with no other input required. Especially when said item is the only resource you need to function (not counting negligible plasma/blood costs).

>Please do tell how ignoring all of the issues 

If you believe that everything needs to be fixed this very moment in a single PR, then I have bad news for you. Xenobiology powercreep is a thing of years of accumulation that a single PR will not fix. It's a small step to putting xenobiology on par with other departments.

**Comment by MNarath1** [comment]
The industrial gray nerf while still overboard would be possible but the blood reaction nerf is completly unacceptable and not sustainable for slimes at all why you might ask a slime usually need 2 cubes min to split but the reaction only generates 1 cube. 
Now yes you could ask cargo to deliver metric tons of monkey cubes to science every few minutes but no department has such a heavy relying on cargo at all and cargo would most likely decline after your 20th request cause well you are blowing trough their money.
Seriously some of the stuff in question needs extrem amount of cubes and the blood reaction is one of the main sources you cannot even get to the point where you would get like industrial gray with this kind of setup as you would need way to many slimes for that and your initial 3 slimes won't be enough for that ever.

**Comment by MNarath1** [comment]
Let alone golems would actually not be able to do their science project anymore as no cubes at all

**Comment by ghost** [comment]
@MNarath1 

You're ignoring monkey recycler, which with even minimal upgrades (glass+iron) cuts cube consumption by half.

I'm not even surprised by this irrational backlash, the department has been given god mode for so long that people can't even imagine having to work for things anymore.

**Comment by BitBite112** [comment]
The monkey cube recycler is simply not enough. You can get really unlucky with RNG and blow through all of your monkey cubes in a second, locking you out of doing any xenobio. 0.8 cubes recycled is pretty good, but that takes T5 parts which you won't get until much later into the round. You'll also have to pray that all of the miners are still alive.

Also, you're ignoring what people are saying yourself which is that everything is balanced around greys giving 3 monkey cubes.

Another problem is that you want it to be a time waster, which is bad. There's just not enough time in the round to afford 15-20 minutes extra time. This is speaking from a view point of someone who tries to work as time efficient as possible. For the newer people it might even take 40 minutes to get what I can get in 10 or less.


I had an idea for more interdepartmental interaction myself which involved a new slime idea: tech slimes. Tech slime crossbreeds create tech disks which are very useful to other departments. They usually don't outperform the best tools barring a few exceptions, but they do come close. Slime surgery tools that heal with every step and are faster then regular, but slower than alien tools come to mind as well as a slime mech for robotics which is weaker than a ripley, but has some nifty features that help the station and an enhanced plant dna analyzer that can scan strange seeds in bulk without having to keep loading and unloading the seeds.
Add, don't remove or nerf thoughtlessly.

**Comment by ghost** [comment]
@BitBite112 

>I had an idea for more interdepartmental interaction myself which involved a new slime idea: tech slimes.

I'm sure adding more slime breeds is a solution to xenobiology powercreep. There's already so many slime breeds, crossbreeds and effects that you can't even know at a glance what's happening anymore without having wiki open in the background.

It's ridiculous and needs some serious trimming. You can leave overpowered extracts in the hallway and nobody will understand what to do with them because it's not intuitive at all, it's just esoteric powegaming.

**Comment by BitBite112** [comment]
> @BitBite112
> 
> > I had an idea for more interdepartmental interaction myself which involved a new slime idea: tech slimes.
> 
> I'm sure adding more slime breeds is a solution to xenobiology powercreep. There's already so many slime breeds, crossbreeds and effects that you can't even know at a glance what's happening anymore without having wiki open in the background.
> 
Do you even know what powercreep is? I don't think you really read and took in what I proposed or else you would have made an actual counter argument instead of mocking my concept of how to deal with xenobio job isolation. 

How would these tech disks make the xenobiologist more powerful? They usually don't because these disks are all about helping people that are not the xenobiologist in order to promote interaction with other departments. The ones that do help the xenobiologist are an added bonus to what they're meant to do.

Your concept involves a job that very well may not even have any workers in it, especially on lrp or people that don't want to help or don't even have the resources to help you (cargo money problems or asshole players).

**Comment by ghost** [comment]
@BitBite112

You proposed introducing yet another slime that would add absolutely no incentive for a xenobiologist to make it or leave the lab to share it, as a solution to lacking departmental cooperation for the department. It's absurd.

There's countless things a xenobiologist can already make and share with other departments to help them, but they do not because they have no reason to leave their lab. They can sit in there, buff themselves to be near immortal with multiple lives and superpowers, and never see another player. They have no incentive to open the airlock after walking in. Maybe exactly once, to upgrade their machines after a few minutes once miners return. Even that is just for convenience.

Even if some selfless scientist decides to share the extracts, nobody but them will understand how to use it since it's just "color extract" and you need to read the wiki to get it. The only things people understand and actively ask for is powergaming gear so they can keep their hardsuit and speed at the same time, and cells for borgs so they can completely ignore a part of their role.

Do you know how many buffs xenobiology even received? It's astonishing, imagine if cargo got a console to sit behind entire shift and teleport crates roundstart, being able to remotely stamp papers and make money out of thin air without ever leaving their seat. The whole original design of xenobiology and all associated risk was completely discarded in favour of a streamlined progression towards godhood with no outside help.

Enough.

**Comment by Fronsis** [comment]
> Additionally, while xenobio needs a significant nerf or to be forced to rely on other departments, cooperation should be required for _advanced_ parts of the job, such as crossbreeds, not the basic functions of the job. All you've functionally done is make xenobio play RnD for 20 minutes before starting. There is no gain of player interaction or even a significant nerf to the actual overpowered parts of xenobiology. The only thing this does is dick around scientists for a short period.

And 20 minutes is being generous, between rushing mining tech, nanites people, robotics, etc this would be a pain for everybody

If this goes through , rip wanting to learn xenobio now because i'll have to wait for everything to be updated on the wiki again

**Comment by BitBite112** [comment]
> @BitBite112
> 
> You proposed introducing yet another slime that would add absolutely no incentive for a xenobiologist to make it or leave the lab to share it, as a solution to lacking departmental cooperation for the department. It's absurd.
> 
> There's countless things a xenobiologist can already make and share with other departments to help them, but they do not because they have no reason to leave their lab. They can sit in there, buff themselves to be near immortal with multiple lives and superpowers, and never see another player. They have no incentive to open the airlock after walking in. Maybe exactly once, to upgrade their machines after a few minutes once miners return. Even that is just for convenience.
> 
> Even if some selfless scientist decides to share the extracts, nobody but them will understand how to use it since it's just "color extract" and you need to read the wiki to get it. The only things people understand and actively ask for is powergaming gear so they can keep their hardsuit and speed at the same time, and cells for borgs so they can completely ignore a part of their role.
> 
> Do you know how many buffs xenobiology even received? It's astonishing, imagine if cargo got a console to sit behind entire shift and teleport crates roundstart, being able to remotely stamp papers and make money out of thin air without ever leaving their seat. The whole original design of xenobiology and all associated risk was completely discarded in favour of a streamlined progression towards godhood with no outside help.
> 
> Enough.


You don't often play xenobiology, do you? You haven't got a good idea on why xenobiologists don't often share their stuff. I can tell you out of experience that it's because xenobiology has a lot of filler. This makes it confusing and difficult to tell what people would want. Having to race against the clock to be able to make what you want also gives less incentive to make and share stuff with the crew since that takes even more time. Having a tech slime is something you don't have to mass produce yourself, but that the crew themselves can saving you a lot of time and if some of the better xenobiologists take the incentive to make the disks (which more will since there would be a whole crossbreed dedicated to them making it more visible on the large list of crossbreeds).
Recently I've often been making regenerative extracts for medbay and have often been making slime cigs, zippos and sometimes chocolates for the crew, but other than that there's not a lot else you can make that would be very beneficial on a more passive scale.


Your concept of dealing with this problem is just flat out bad. It nerfs xenobiology to the point you can't begin with it anymore (making monkey cubes with regenerative extracts becomes impossible). Don't shit on my idea and mock it just because I understand the problems of xenobiology better than you do, who has probably only ever played an hour of it.

**Comment by Effemu** [comment]
>relying on cargo

"Hey QM can you buy me an *insert item*?"
"No."
or
"Hey QM.... Hello? Is there anyone working cargo?"
"No."
😕

**Comment by ghost** [comment]
@BitBite112

>lot of filler

You mean all the content that doesn't directly make you into a demigod?

**Comment by BitBite112** [comment]
@githubuser343 
Stabilized's are very handy, but are usually used to make you more powerful with a few exceptions.
Regenerative's are always handy, but only for medical. Any other department would only use them for use in combat or because they're a traitor.

Industrial - Only orange, black and light pink seem to be useful since slime cigs heals, the chocolates provide nourishment and a mood boost and the zippo lights the cigs. The purple autoinjector is handy as well, but can be outdone by recurring purple.
The rest is just stuff you can print at an autolathe such as a fire extuingisher, camera, metal sheets (just use the extracts), adamantine (extracts again), bluespace (outdone by extracts), silver food production (extracts and also the fun of being a cook is making the food yourself so giving it to him is really just mean more than helpful), fireproofing potion (extracts again),  spraypaint (autolathe), plasma (extracts).

Charged - Slime revival (Don't kill your slimes in the first place), purple makes omnizine, but just use regen jelly instead (although now that I think about it might be handy for chem when they never make strange reagent), blue neuters for only one generation, just use the ones from the blue extract for permanent one. Spawn metal, just use extracts. Spawn camera obscura, no real use.
Lavaproofing might be useful for miners, but by that time they already have put all the mats into the ORM or died. Spawn a completed golem shell, just make 11 adamantine bars with extracts.

Self-sustaining - only really useful for getting the holy water + uranium reaction from rainbow because of rare chems.

Chilling is pretty useful, but mostly only for oneself and crossbreeds are difficult to mass produce - Barrier cubes might be handy for sec I just realized. Recharge the APC 50%, just use an inducer or replace the cell with a yellow core cell.
Dark purple removes all plasma in a room which is gamer, but have yet to use it.
Most other chilling extracts like breath mask are good, but only good for you or the individual. Others are really not useful to anyone, but can be for niche uses such as prism glasses for using against nightmares or broken lights and pink corgi puppy to trade AA with.

Consuming - Most of them have weak effects, but purple cookies can be used on even dead people which is handy if you don't have synthflesh or surgery tools. Cookies that cool you down could be used for when a plasmaflood happens, but then the station is usually fucked then including xenobiology.

Warping - Very cool, but most are for defense or annoying people and personal use. Purple rune can be outdone by recurring purple or regenerative cerulean.

Recurring - Basically an extract that can regenerate up to 10 uses as long as you don't use those up. Recurring purple is good for portable healing anywhere anytime with a syringe.

Pyrite - If you want the entire station painted green and pink then give it to the clown, otherwise not much use.

Pink - luminescent effects for non luminescents, but most luminescent effects are lack luster such as infusing with salbutamol (just use oxygen tank or make a breath mask), turning you into a slime or other race, or are mostly for combat situations.

Transformative - The best utility crossbreed for that is ceruleans since adult slimes instantly split into fully grown slimes, all the others are for buffing their combat abilities except for the one where their extracts sell for more credits (I don't know how much).

Adamantine - A pretty useful crossbreed for everyone, but even here is filler. Blue is handy for restoring atmos, metal is handy for a borg if he can't repair himself at all for some reason, silver is great for the botanist, sepia prevents critical condition (so it says, haven't made it yet), pink if you want a place where no one can attack anyone lethally. The other parts are mostly filler or offensive such as the pink one turning you into a random pet or the orange one lighting everyone on fire.


There are a fair amount of uses, but most of it's filler. The ones that are useful are mostly one colour and recurring purple might not be immediately obvious. For a new player all this information can be rather overwhelming.

**Comment by gabrielckc** [comment]
There's an idea in the xenobiology Discord that I believe works better to incentivize xenobiologists to leave their lab, while not making their job super annoying. I'ma paste it here:

How to get xenobiologists out of the lab: the Slime Redemption Machine

The idea is to make xenobiology not ENTIRELY dependant on other departments, but rather partially, by restricting T4 slimes (oil, black, adamantine and light pink) and rainbows with a point system.

There would be several Slime Redemption Machines (SRM for short) scattered through the station, one for every department except science. Each SRM is department based (just like techfabs) and accepts slime cores, stuff made from slime cores, and crossbreeds relevant to said department. Scientists can just put the items into the SRM right from their bio bags, and be rewarded with a number of points. Normal cores give you some points, normal cores with multiple uses give X times some points, and crossbreeds give a shitload of points, considering the effort required to make them and their usefulness (for example, if you give medbay an industrial purple, they're set for the shift). These slime points are then assigned to the scientist's ID, who can use them to buy stuff at a new machine, the Xenobiology Rewards vendor. The primary use of this machine is to sell items that spawn the T4 and rainbow slimes, but it could also dispense booze and stuff like the mining one. The cost of a T4 slime spawner should be equivalent to selling 1-2 crossbreeds, so it's reasonable to get all of them in a shift, if the scientists know what they are doing. The items delivered would either be accessible from the SRM itself by department workers, or redeemable from request consoles.

As for rainbow, they could be acquired the same way, but costing a lot more. To compensate for that, T4 slime cores or crossbreeds that require T4 slimes would be worth more points (consider that a recurring adamantine can give cargo much more money that a recurring dark purple). That way, scientists need to make multiple expeditions to reclaim points if they want their ultimate prize.

WHY IT'S GOOD FOR THE GAME

And why it's specifically better than taking away cube production outright

This gives xenobiologists a very good reason to get out of their lab, probably multiple times, and more importantly than that, to cooperate with the rest of the station directly, rather than just giving Centcomm an arbitrary amount of money and making no difference in the round. This also doesn't block scientists from doing most of the stuff xenobiology is already able to do without going through this process, so they can get started right away like any other job, and have their fun with that if they so desire.

**Comment by MNarath1** [comment]
> @MNarath1 
> 
> 
> 
> You're ignoring monkey recycler, which with even minimal upgrades (glass+iron) cuts cube consumption by half.
> 
> 
> 
> I'm not even surprised by this irrational backlash, the department has been given god mode for so long that people can't even imagine having to work for things anymore.

Irrational? What you are trying to do has litterally effects all over the board as this is one of the core mechanics xenobio builds up to monkey cubes are the basic of every single crossbreed as they are needed either to breed the slime or to generate crossbreeds trough repro slimes this nerf would completely change almost everything making xenobio suddenly completely reliant on anther department to a point no other department has currently.
Also basic cutting it in half what??? The recycle gives back 0.2 monkey cubes per monkey on basic upgrade thats a 1/5 of the original not half.

**Comment by ghost** [comment]
@MNarath1

Even at 2 hour rounds, you will be hard pressed to spend over a 100 monkey cubes. And that's with current numbers where cubes are so numerous that people often don't even bother recycling monkeys. You can get that number from two trips to cargo or botany mid round. If you somehow manage to spend that many, then you have a fridge with hundreds of extracts already.

You have to face the reality that currently you have no concern at all about monkey cubes, you pop down a single industrial grey and have infinite of them, you can get to industrial grey without problems as cubes just rain down on you. This part will not change, but it will be harder to get to that point and you can still do it without leaving your lab. It will be substantially easier to do by leaving your lab though, which is the point.

No matter the nerf, it would be greatly unpopular as people are too used to their powergaming toys requiring minimal effort or interaction. You sitting at a console for an hour straight is bad design.

Compare it how every other department has to wait for miners and science combined, just to get their shiny toys from lathe. All you have to do, is sit in your lab.

**Comment by BitBite112** [comment]
I regularly use over 100 monkey cubes every round and monkey cubes do become somewhat of a concern if RNG has been incredibly bad and hasn't given me a metal slime or a dark purple slime for plasma to use on the industrial.

Science also has backups if miners die. They can set up a few bluespace miners or ask xenobiology to make more materials with a few extracts.
Xenobiologist and scientist are also two very different jobs. The scientist's job doesn't have to be as time efficient to do stuff. Xenobiologists have to get slimes as fast as possible and it will still probably be around the 40 minute mark when they're done, but scientists can leave the console and points will generate themselves. They don't have to be working all the time. If there are no mats they could go mining if they wanted to and either a coworker can take over the simple job or they can just research it all later. It's not a good comparison.

**Comment by ghost** [comment]
>They can set up a few bluespace miners

I suspect you did not play the game recently. Bluespace miners are not a thing anymore (in limited amount on golden at most).

**Comment by MNarath1** [comment]
> > They can set up a few bluespace miners
> 
> I suspect you did not play the game recently. Bluespace miners are not a thing anymore (in limited amount on golden at most).

Trough the bluespace miner are not that much of a thing anymore all the other points mentioned above still stand.

I want to further add again that monkey cubes are the core of xenobio and even if its possible to still get up to a point where you can sustain yourself again it will lock xenobio onto that specific path for the first 10-15 minutes of the round additionally if you get really unlucky with rng or make a mistake you can easily end up with not enough monkey cubes to get to said point.
A way to make xenobio more reliant on other departments might be plasma it is still a fairly common used resource for xenobio and needed in most advanced reactions and or crossbreeds and while beeing annoying will not completly cripple you if you don't have it immidiatly and this could easily make xenobio more reliant on lets say mining like most departments. 
That of course would remove xenobio as a possible solution if miners are not doing their job properly but it would archive the goal you seem to have set. I also would not call this an ideal solution either trough its definitly better then nerfing monkey cubes into the ground. 
Also nerfing monkey cubes would remove the option for free golems to make their own xenobio cause how should they get monkey's to use?

**Comment by francinum** [comment]
I am fine with the change to the industrial extract, I am not alright with the changes to the base extract.

**Comment by jlsnow301** [comment]
you forgot to ask if these changes are fun for anyone, better speed merge it

**Comment by Glcbitj** [comment]
This changes literally make the job more of a drag, why don't you reduce the value of cargo crates by 10? or make plants take x5 as much time to grow unless you have help from some resource from cargo? This makes the game less fun for absolutely anyone who wants to do Xenobiology and you know it. 
Comparing the constant need to get cubes from other departments that are far away to mining requiring 5 clicks from R&D ONCE is beyond retarded if you want to compare dependency on others.

**Comment by LivingBatteryBox** [comment]
The base cube nerf is excessive and encourages people to just dupe grey slimes with plasma and then kill them in the cold room over and over. This will change literally nothing, T2 parts bypasses the whole idea of the nerf because of the grey extract plasma reaction.

**Pull request closed without merging**
