### PR TITLE
Nerfs stabilized light pink extract.

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Stabilized light pink extract now speeds you up by 1.5x rather than 2x.
Stabilized light pink extract now applies pacifism to the user.

## Why It's Good For The Game

Its made to be an ambulance but is used for the high speed combat potential.
This reduces the insane speed of the extract (which is completely passive) and also prevents it from being used in combat directly by giving the user pacifism.

## Changelog
:cl:
balance: Stabilized light pink extract speed reduced from 2x increase to 1.5x increase.
balance: Stabilized light pink extract now applies pacifism to its user.
/:cl:

### CODE REVIEW

**Comment by RDS88-beeman** [comment]
Good. Very good. There's still more speed in xeno, but they have drawbacks. Nerf the "X but better" meta, buff the unique shit.
HIT BURNING YELLOW NEXT

**Comment by yrokhlin** [comment]
The updated no one wanted or asked for.

**Comment by AnCopper** [comment]
> The updated no one wanted or asked for.

"I didn't want or ask for this"

**Comment by Kapu1178** [comment]
the cope is real. 

Good update 👍

**Pull request merged**
