### PR TITLE
Fixes Nightmare outfit oversight

### PR DESCRIPTION
**Pull request by Tsar-Salat**
## About The Pull Request
Allows nightmares to actually be able to use their pocket, belt, and ID slots.

Removes restriction prohibiting nightmares from wearing masks.

## Why It's Good For The Game
Nightmares spawn with several slots blocked off, namely their mask, suit, jumpsuit, gloves and shoe slots. 

However, in both the UI and the code its rather clear that pocket, belt and ID slots are open and able to be used. Yet when you try to put these on, it gives you an error saying you need to be wearing a jumpsuit to equip in these slots. 

Going off the code, I'm guessing Nightmares were meant to have similiar outfit behavior to Golems, so I gave them the nojumpsuit var so they can actually utilize these slots. 

Additionally, I removed the restriction on the masks, as it's generally inconsequential (in my opinion) for a race that doesn't breathe and can't get diseases to be able to smoke a cigar.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl: rkz
fix: nightmares can actually utilize their pocket, belt, and ID slots. It was checking for a jumpsuit on a race that cant wear jumpsuits
balance: removed restriction prohibiting nightmares from wearing masks
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
A nightmare smoking a cigar??? But that would harm them!!!! (actually i'm not sure if a lit cig does enough light to damage them lmao)

Good change, i've had a few nightmare gimmicks where i requested an ID and it was pain to not have it on the id slot

**Comment by Penwin0** [comment]
> I removed the restriction on the masks

Masks might be restricted to make nightmares easily identifiable

**Comment by Tsar-Salat** [comment]
> Masks might be restricted to make nightmares easily identifiable

A naked guy with a jet black body and red lines, with a protruding armblade stretching out in front of him isn't easily identifiable?

**Comment by Penwin0** [comment]
For some reason my brain thought they could wear suits, nevermind

**Comment by Tsar-Salat** [comment]
> thought they could wear suits, nevermind

Nightmares with hardsuits would be terrifying jfc

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
