### PR TITLE
Readd tooltips to the R&D console

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

This re-adds tooltips to the R&D console, showing the user the name+description of a design when hovering over it.

They were apparently removed due to lag _several years ago,_ but presumably from tgui improvements, I did not experience any GUI lag when testing this locally.

## Why It's Good For The Game

So you can see what you're actually researching.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

</details>

## Changelog
:cl:
add: Re-added tooltips to the R&D console, so you can now actually see what you're researching!
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
lovely

**Comment by EvilDragonfiend** [comment]
It can possibly cost too many resources to build data because of desc in DM and TGUI both. I wonder if there's a way to make it static...

**Comment by Absolucy** [comment]
> It can possibly cost too many resources in DM and TGUI both to build data because of desc. I wonder if there's a way to make it static... like storing desc in client side.

That stuff is put together in `ui_static_data`, which means it gets calculated once (per user) and then cached.

**Comment by itsmeow** [comment]
Tooltips were laggy, but I fixed this in the player panel PR so it's fine now

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
