### PR TITLE
Fixes circuits. Finally.

### LINKED ISSUE #367: Circuit printer saying "You need iron to build that" and not building with iron avaliable.
## Round ID: 
6543
## Reproduction:
You can only build assemblies with a circuit imprinter made from a protolathe. Also every time I first tried to make a "gas vent" in Atmospherics.

### LINKED ISSUE #478: Fix integrated circuits
**BELOW**
## Reproduction: just go thru the printer and try to print stuff. Assemblies seem fine tho

Certain Items in the printer wont print even with a full printer

**ABOVE**

### PR DESCRIPTION
**Pull request by St0rmC4st3r**
## About The Pull Request

This fixes circuits. I have no idea how this worked before floydmats and I do not care. One fucking line of 7 characters prevented circuit cost from being calculated properly.
Fixes #367
Fixes #478

## Why It's Good For The Game

Well, we FINALLY, after 4 months have circuits back!

## Changelog
:cl:
fix: fixed the circuits not being printed (finally)
/:cl:

### CODE REVIEW

**Review by MarkSuckerberg — APPROVED** [review]
Finally, fuggin finally.

**Comment by qwertyquerty** [comment]
It worked before floydmats as floydmats has to initialize the instanced mat typelist (which circuits no likey).

My floydmats removal would have also fixed this but this is a better solution.

**Comment by qwertyquerty** [comment]
Please add fixes # for both issues in the body

**Comment by St0rmC4st3r** [comment]
Issues mentioned

**Pull request merged**
