### PR TITLE
Adds laugh sound to IPCs.

### PR DESCRIPTION
**Pull request by super12pl**
## About The Pull Request
Adds 3 new sounds
Laugh sound - stock laugh tape
~~Death sound - ReactOS shutdown sound (https://freesound.org/people/jobro/sounds/244603/)~~
~~Scream sound - generic error sound (http://soundbible.com/1127-Computer-Error.html)~~

## Why It's Good For The Game
New sounds to fully immerse into being a sentient toaster

## Changelog
:cl:
soundadd: Adds new laugh sound to IPCs.
/:cl:

### CODE REVIEW

**Comment by heepox** [comment]
this is funny to me. good job.

**Comment by Isy232** [comment]
Sounds cool, someone should merge this.

**Review by St0rmC4st3r — DISMISSED** [review]
All good to me.

**Comment by utilbird** [comment]
licensing

**Comment by super12pl** [comment]
crossedwindows

**Comment by utilbird** [comment]
Ah neat, have you done that latter though? It sounds pretty normal.

**Comment by PowerfulBacon** [comment]
but you are just using them wholesale

**Comment by super12pl** [comment]
>but you are just using them wholesale

2 isolated sound effects are not wholesale

**Comment by PowerfulBacon** [comment]
yes they are

**Comment by PowerfulBacon** [comment]
They sound like they will be really strange in game and very different to our other sound effects like the cyborg death

**Comment by ike709** [comment]
I agree with Bacon, it's a decent joke idea but it doesn't sound good.

**Pull request closed without merging**
