### PR TITLE
Nerfs basic medicines to make these only effective for minor injuries

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request

Nerfs basic medicines to make these only effective for minor injuries
Bicardine, Kelotane, Dexaline, Antitoxin, Tricordrazine is changed to follow this calculation:

* Calculation:
for every 20 damage you have, the efficiency is decreased by 50%.
0-19: 100% chance for 0.5 (Dexaline as 1.5, Tricordrazine as 1)
20-39: 50% chance for 0.5: effectively 0.25 per tick
40-59: 25% chance for 0.5: effectively 0.125 per tick
60-70: 12.5% chance for 0.5: effectively 0.0625 per tick
...

## Why It's Good For The Game

these chems are too useful to treat most injuries through sleepers. Injecting these chems then say goodbye isn't a good RP and doesn't bring good interaction.

## Testing Photographs and Procedure
no photo, but I will put `world.log` results instead

```
Calc: 100% chance-success, HP: 0
Calc: 100% chance-success, HP: 0
Calc: 100% chance-success, HP: 6.5
Calc: 100% chance-success, HP: 13
Calc: 50% chance-fail, HP: 20
Calc: 50% chance-success, HP: 26.5
Calc: 25% chance-fail, HP: 40.5
Calc: 25% chance-fail, HP: 47.5
Calc: 25% chance-fail, HP: 47.5
Calc: 25% chance-fail, HP: 47.5
Calc: 25% chance-fail, HP: 47.5
Calc: 25% chance-fail, HP: 47.5
Calc: 25% chance-success, HP: 47
Calc: 25% chance-success, HP: 46.5
Calc: 25% chance-fail, HP: 46.5
Calc: 25% chance-fail, HP: 53.5
Calc: 12.5% chance-fail, HP: 67.5
Calc: 12.5% chance-fail, HP: 74.5
Calc: 6.25% chance-fail, HP: 81.5
Calc: 6.25% chance-fail, HP: 95.5
Calc: 3.125% chance-fail, HP: 102.5
Calc: 3.125% chance-fail, HP: 102.5
Calc: 3.125% chance-fail, HP: 102.5
Calc: 3.125% chance-fail, HP: 102.5
Calc: 3.125% chance-fail, HP: 102.5
Calc: 3.125% chance-fail, HP: 102.5
Calc: 3.125% chance-fail, HP: 102.5
Calc: 3.125% chance-fail, HP: 102.5
Calc: 3.125% chance-fail, HP: 102.5
Calc: 3.125% chance-fail, HP: 102.5
Calc: 3.125% chance-fail, HP: 102.5
Calc: 3.125% chance-fail, HP: 102.5
Calc: 3.125% chance-success, HP: 102
Calc: 3.125% chance-fail, HP: 102
Calc: 3.125% chance-fail, HP: 102
Calc: 3.125% chance-fail, HP: 102
```

## Changelog
:cl:
balance: basic medicines (Bicaridine, Kelotane, Anti-toxin, Dexalin, Tricordrazine) are less effective over 20 damage ("if(prob(100/(2**(round(PLAYER_DAMAGE / 20 )))))") 100% chance to heal, but for every 20 damage you have, the chance is halved. (100% / 50% at 20 / 25% at 40 / 12.5% at 60).
balance: Bicaridine/Kelotane/Anti-toxin heals 0.5 (brute/burn/toxin)
balance: Dexalin heals 1.5 (oxy damage)
balance: Tricordrazine heals 1 (4 types), metabolisation rate is 1.2u, max overdose is now 50u.
/:cl:

### CODE REVIEW

**Comment by LodedDiper69** [comment]
Going by your "why it’s good" section, wouldn’t the more effective solution be to remove sleepers?

**Comment by EvilDragonfiend** [comment]
> Going by your "why it’s good" section, wouldn’t the more effective solution be to remove sleepers?

sleepers will not be removed, and chems are still powerful when compared to how easy it's made.

**Comment by EvilDragonfiend** [comment]
need wiki change

**Comment by itsmeow** [comment]
I generally like this, although nerfing anti-toxin is a big deal because it's the only roundstart chem that medical has aside from charcoal for treating major toxin damage. Otherwise cyroxadone or chemist is the only way.

**Comment by EvilDragonfiend** [comment]
> I generally like this, although nerfing anti-toxin is a big deal because it's the only roundstart chem that medical has aside from charcoal for treating major toxin damage. Otherwise cyroxadone or chemist is the only way.

if someone has a big ton of toxin damage, it doesn't mean they should be treated through anti-toxin.

**Comment by itsmeow** [comment]
It's not very common to have competent chemists in my experience but I suppose it's fine

**Review by itsmeow — APPROVED** [review]
I like this although please simplify the CL to something like "X gets less effective over 20 damage, (insert algorithm)" because as it is it's not clear what has been changed.

Also update wiki when merged or slightly before merge (I will have another maintainer do that because this is a balance change)

**Comment by EvilDragonfiend** [comment]
it's too earlier to change wiki, so I will wait for someone who's willing to commit.

**Comment by EvilDragonfiend** [comment]
> Heals brute damage at a rate of 0.5 damage per tick for a 100% chance. The chance is halved for every 20 damage you have. For example, the chance to heal 0.5 damage at 40 damage will be 25%. Better medicines will be needed for a speedy recovery.
Overdoses cause 2 liver damage per tick.

wiki format will be this

**Review by PowerfulBacon — APPROVED** [review]
Apply wiki changes and ping for merge

**Comment by EvilDragonfiend** [comment]
wiki change done

**Comment by DrDuckedGoose** [comment]
Aw wtf

**Pull request merged**
