### PR TITLE
BoxStation remapping pack - Command Edition

### PR DESCRIPTION
**Pull request by Tyranicranger4**
## About The Pull Request
Remaps every 'command' related area on BoxStation.
Including:

Gateway (engineering construction area removed to accommodate this change)
Teleporter
HoP office/line
AI upload
Gravity generator (and the SMES to accommodate this change)
Meeting room
Captain's office/quarters
EVA storage
Bridge
Also adds a new internal Command hallway as an extension of the Bridge.
Also remaps tech storage (pigeon asked for it).
___
***Additionally*** moved some of the atmospheric storage chambers down and to the left by one tile to remove a double wall.
Also swaps some decals around to make things a little nicer, mostly around the above mentioned areas.
Fixed a few mapping errors too, namely the random event spawner in a wall in the bar. And the randomly discolored cables, *I'm going to find who did this*

## Why It's Good For The Game
BoxStation is an older map and it's starting to show. This PR improves the look and general feel of parts of it giving it a more 'modern' look. I do intend to work on other parts of the map in the future, however this PR is complete on it's own. I do not believe the different designs will clash too much with the rest of the map as they are in their own specific areas. Also fixing oversights good.

## Testing Photographs and Procedure
Screenshots are below, but as for actual testing I've ensured that power is setup correctly by depowering the station and then repowering it and checking for non-charging APCs via SDQL. As for atmospherics I've successfully plasmaflooded the map. As for disposals... uh it should:tm: work, I barely touched it outside of the bridge and I do know that *thing* works.

<details>
<summary>Screenshots</summary>
 
Bridge/main 'command' area.

Ingame
image

Editor
Trollering

Infrastructure view (yes Ian is station infrastructure)
Trollering

___
EVA/AI Upload

Ingame
image

Editor
Trollering

Infrastructure
Trollering

___
Gateway/Tech Storage

Ingame
image

Editor
Trollering

Infrastructure
Trollering

___
Gravity generator/new SMES location.

Ingame
image

Editor
Trollering

Infrastructure
Trollering

___
Slightly moved atmospherics chambers (no more double wall)
Trollering

___
Also fixed this shit.
image

</details>

## Changelog
:cl:
add: Added an extension to the Bridge acting as a sort of internal command hallway (BoxStation)
tweak: Remapped the Bridge and general 'command' area (BoxStation)
tweak: Remapped the HoP office/line (BoxStation)
tweak: Remapped the Teleporter room (BoxStation)
tweak: Remapped the Meeting room (BoxStation)
tweak: Remapped the Captain's Quarters (BoxStation)
tweak: Remapped and downsized EVA storage (BoxStation)
tweak: Remapped some parts of maintenance around where the EVA Storage/Engineering construction areas used to be (BoxStation)
tweak: Remapped tech storage (BoxStation)
tweak: Moved the gravity generator to engineering and remapped the surrounding area (BoxStation)
tweak: Moved the engineering SMES batteries and remapped the surrounding area (BoxStation)
tweak: Moved and remapped the AI upload (BoxStation)
tweak: Moved and remapped the gateway room (BoxStation)
tweak: Moved the bottom atmospherics gas storage chambers down and to the left one tile (BoxStation)
tweak: Filled in the small windows in the northern part of the main hall with grass (BoxStation)
tweak: Changed the ID on the detectives office shutters (no more kanyewest shutters) (BoxStation)
tweak: Changed numerous decals around, mostly around the places mentioned in the above changes (BoxStation)
del: Removed the engineering construction room (BoxStation)
del: Removed a generic event spawner inside of a wall in the bar (BoxStation)
fix: Fixes random discolored cabling (BoxStation)
/:cl:

### CODE REVIEW

**Comment by Tyranicranger4** [comment]
Didn't think an underscore in a shutter ID would break everything, funny.

**Comment by WrillWasTaken** [comment]
I'm not a fan of the wonky pipes in atmos, they could easily cause issues when piping in space. Perhaps expand the area in engineering instead of moving the atmos chambers?

**Comment by Tyranicranger4** [comment]
I don't really see why you'd be piping in the area I touched. Also I don't believe expanding atmospherics is at all the solution, it's already a bit too large imo.

**Comment by WrillWasTaken** [comment]
If I'm trying to pipe on all 5 layers at the bottom (IE. 5 layer passive vents to space on the waste) then the pipes will interfere. I also was thinking of the area around the SM, not atmos.

**Comment by Tyranicranger4** [comment]
> I also was thinking of the area around the SM, not atmos.

I didn't touch anything to do with the SM though 🤔

**Comment by WrillWasTaken** [comment]
...I'm saying you *should* expand the area to the top right of the SM, near the AI sat access, not that you did.

**Comment by WrillWasTaken** [comment]
Atmos tanks should remain in the same position and the area down there should be extended to remove the double wall instead
201505662-36e162b4-4166-4a44-909e-49ed8c36e1a4

**Comment by Tyranicranger4** [comment]
While I don't disagree that that's a very good spot to expand engineering that is somewhat out of the scope of this particular PR.

**Review by PestoVerde322 — DISMISSED** [review]
Approved, checked and it's all good.

**Review by PestoVerde322 — APPROVED** [review]
It good yes, re-approved.

**Pull request merged**
