### PR TITLE
[WIP] [DO NOT MERGE] Throatslicing and makes butchering a component(?)

### PR DESCRIPTION
**Pull request by SomeAngryMiner**
## About The Pull Request

This is one of the two features that would prove very interesting in combat: throatslicing, the other being holding people up, wich will be included in another PR.
What does this do, AnYwAy??
When you find someone on the ground asleep, you may slit their throat, or, if they are awake, (sadly), you may do a neckgrab and aim to the head with a sharp object, on harm intent.
Throatslicing gives extreme amounts of bleeding, giving people about 30 seconds to find medical attention (bandages cure the bleeding and the slice, oxygen meds are good too for this.), otherwise theyll just flop off into the ground and die. Good for bloody murder and silently finishing off targets as traitor, not as good for quick combat.
tgstation/tgstation/pull/45299/files For the butchering turning into a component.
tgstation/tgstation/pull/46838/files For the actual throatcutting.

## Why It's Good For The Game

A good way to dispose targets silently, engage on murder and do other traitorous stuff. gives bandages more use besides the rare heparin inyection.
Also an extreme way to prevent a disease to spread through coughing.

## Changelog
:cl:
add: After an update on standard procedure manuals, Crewmembers and syndicate alike will find themselves able to cut each other's throats in a gruesome way. Please do not do so unless its an emergency, but if it is, Be sure to restrain them by the neck and apply a sharp object to the head with malicious intent.
refactor: butchering is now a component.
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
I noticed there were a few bug fix PRs following the original neck slice PR, did you get them too?

**Comment by SomeAngryMiner** [comment]
there was a single one i found, about it not spreading coughing as long as it stayed, wich is added, ill try to see if there are more, though.

**Comment by Cenrus** [comment]
Here are the ones I found

https://github.com/tgstation/tgstation/pull/47001
https://github.com/tgstation/tgstation/pull/47188

**Comment by SomeAngryMiner** [comment]
Aaaand done.

**Comment by SomeAngryMiner** [comment]
one sec, this needs a bit of fixing.

**Comment by SomeAngryMiner** [comment]
i missed out some stuff, ill check on it when i have more time.

**Comment by SomeAngryMiner** [comment]
i think i just broke Travis, again.

**Comment by SomeAngryMiner** [comment]
due how much this fails and my inability to fix it, ill move into something else.
people are free to reopen it if they can make it work, since its an useful mechanic.

**Pull request closed without merging**
