### PR TITLE
Add 2 pens to NutriMax botany vendor

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Adds 2 pens to NutriMax vendor. Pens are used to rename plant seeds and change their descriptions.

## Why It's Good For The Game

Pens in NutriMax vendor will hint at their significance to new botanists, they will also enable lavaland ruin plant vault botanists to name their plants.

## Changelog
:cl:
add: Added 2 pens to NutriMax vending machine.
/:cl:

### CODE REVIEW

**Review by francinum — DISMISSED** [review]
sure whatever

**Comment by francinum** [comment]
🔑

**Comment by utilbird** [comment]
🔑

**Comment by utilbird** [comment]
It's clutter that will almost never be used, a better solution would be to map some pens into the lifebringer room

**Comment by ghost** [comment]
> It's clutter that will almost never be used, a better solution would be to map some pens into the lifebringer room

What do you mean clutter? Pen is an essential tool for botany, as much as a spade or cultivator. It's irreplaceable behavior to be able to rename seeds and change their description.

Your argument makes no sense, even botanist lockers and hydroponics area itself has redundant tools that can be dispensed from NutriMax, it's not an argument to remove them from NutriMax just because they are mapped.

**Pull request closed without merging**
