### PR TITLE
Reverts PR number 4806

### PR DESCRIPTION
**Pull request by TeomanTheGreat**
## About The Pull Request
Reverts #4806 

## Why It's Good For The Game
This isn't Minecraft. We don't need text telling us detailed stats of armor. 

## Changelog
:cl: Phil Smith
del: Clothing no longer has tags. 
/:cl:

### CODE REVIEW

**Review by francinum — APPROVED** [review]

**Comment by TeomanTheGreat** [comment]
For those wondering why this pr exists due to my lackluster description, I shall tell you here. Exact stats for armor shouldn't be documented and easy to find on examination. Instead, it should be vague like how it was before. You may think tags are QoL but frankly, they make things minimax.

**Comment by Howluinb** [comment]
Terrible idea. instead of making knowledge more easily accessible, you opt to make it only known to the codedivers or those who spent hours asking questions an delving deep, ie completely locking away the opportunity for newbies to learn on their own what works and what doesn't, and what's best.

This isn't the design philosophy a server whose tagline is "Beestation, for beginners" should have.

**Comment by TeomanTheGreat** [comment]
> Terrible idea. instead of making knowledge more easily accessible, you opt to make it only known to the codedivers or those who spent hours asking questions an delving deep, ie completely locking away the opportunity for newbies to learn on their own what works and what doesn't, and what's best.
> 
> This isn't the design philosophy a server whose tagline is "Beestation, for beginners" should have.

I believe your supposed to learn from experience or asking questions.

**Comment by BrumalLake** [comment]
we needed more coders so we're doing this to get more code divers which is how most start off

**Comment by ToasterBan** [comment]
> This isn't the design philosophy a server whose tagline is "Beestation, for beginners" should have.

1. we no longer have that tagline
2.

**Comment by mcmeiler** [comment]
Maybe you should actually code something that isn't a removal because you simply don't have a better idea of a replacement.

**Comment by Isy232** [comment]
> Exact stats for armor shouldn't be documented and easy to find on examination. Instead, it should be vague like how it was before. You may think tags are QoL but frankly, they make things minimax.

What frankly telling you the protection value of armour does is levels the playing field between those who spend hours diving through code to find the absoulute most effective way to play and those who have a casual thought to consider what gear they are using.

Ike says it best:
> The sacrifices we make to not give codedivers an advantage.

This is just gatekeeping minmaxing, not preventing it or fixing any of the underlying problems.

**Comment by ToasterBan** [comment]
> This is just gatekeeping minmaxing, not preventing it or fixing any of the underlying problems.

the number of minmaxers will go down, so a straight positive

**Comment by Archanial** [comment]
They don't show the exact number and frankly you don't have to check it.
You still could code dive to minmax your armor.
It was just recently merged, let's try having it for a bit longer before making conclusions.
🔑

**Comment by Isy232** [comment]
> > This is just gatekeeping minmaxing, not preventing it or fixing any of the underlying problems.
> 
> the number of minmaxers will go down, so a straight positive

A proper solution would be to just fix the problem of minmaxing forever by removing shitty differences in armour and balancing things so min maxing isn't a thing.

**Comment by Howluinb** [comment]
how is it new player coddling to give them info they will legitimately never find any other way ???

as said several times, all you're doing is giving the people with 2k hours & codedivers an even stronger advantage over newbies.
It's not coddling. It's leveling the playing field so the *beginner friendly server* gives a chance to *beginners* to learn on their own without having to search for hours outside of the game

**Comment by TeomanTheGreat** [comment]
> how is it new player coddling to give them info they will legitimately never find any other way ???
> 
> as said several times, all you're doing is giving the people with 2k hours & codedivers an even stronger advantage over newbies.
> It's not coddling. It's leveling the playing field so the *beginner friendly server* gives a chance to *beginners* to learn on their own without having to search for hours outside of the game

_inhales_ WE HAVE MENTORS ASK THEM!

**Comment by BrumalLake** [comment]
ok mr elitist

**Comment by Howluinb** [comment]
> 
> 
> > how is it new player coddling to give them info they will legitimately never find any other way ???
> > as said several times, all you're doing is giving the people with 2k hours & codedivers an even stronger advantage over newbies.
> > It's not coddling. It's leveling the playing field so the _beginner friendly server_ gives a chance to _beginners_ to learn on their own without having to search for hours outside of the game
> 
> _inhales_ WE HAVE MENTORS ASK THEM!

How is your solution to the problem "let's remove accessibility of content and only leave it up to people who either already know or know how to code dive", "just ask people who know lmao"

This isn't beginner coddling. Beginner coddling would be indicating them "hint: hos armor is better" or "hint:this armor makes you beno immune". this is just preventing new people from looking at the info in front of them and trying to figure out what would be better for what situation, despite not necessarily knowing what each situation needs.

And going "lol memetor dude", when it implies A: new memetors come in, they didn't codedive and they didn't necessarily bother looking at armor values so they don't know and B: bothering memetors with silly question that they'd have found out normally by just not reverting this pr, including the fact most people never pm memetors anyway which i find stupid.


also, "beestation, for beginners" is still the tagline. https://beestation13.com/

**Comment by francinum** [comment]
You should never *need* this level of specificity. It should be relatively obvious from an item's description vaguely what level of armoring the item has.

The only obvious exception to this rule I can think of is incredibly specific items that are armored but not meant to be obviously so, which I am both not sure exist, and believe this PR would break by being fully generalized as it currently is.

This isn't about coddling beginners, it's about bad design.

**Comment by ghost** [comment]
People complaining that this gives coders/code-divers an unfair advantage are the same people who say coders/code-divers don't actually play the game, so it technically isn't even a problem.

**Comment by BrumalLake** [comment]
so, you dive into the code without playing the game itself and leave it untouched
just like to read it during your passtime for your literature supplement
code divers are not a type of coder they are a type of player
no one has ever said in history that code divers don't play the game

**Comment by qwertyquerty** [comment]
:key:

I agree with ike

**Comment by TeomanTheGreat** [comment]
> :key:
> 
> I agree with ike

Not sure if your refrencing a conversation i didn't see but did ike comment here...?

**Comment by super12pl** [comment]
> > 🔑
> > I agree with ike
> 
> Not sure if your refrencing a conversation i didn't see but did ike comment here...?

he is referencing to ike's comment on the original armor tag PR

**Comment by TeomanTheGreat** [comment]
> > > 🔑
> > > I agree with ike
> > 
> > Not sure if your refrencing a conversation i didn't see but did ike comment here...?
> 
> he is referencing to ike's comment on the original armor tag PR

Ah i see

**Pull request closed without merging**
