### PR TITLE
Adds a new ion law

### PR DESCRIPTION
**Pull request by benbot16**
## About The Pull Request

Adds a new ion law that tells the AI to produce as much of a given chemical as possible.

## Why It's Good For The Game
It's something someone suggested on discord, and it sounds like it'd be interesting.

## Changelog
:cl:
add: Adds a new chemical production ion law.
/:cl:

### CODE REVIEW

**Comment by FriendlyContractor** [comment]
I dont think it adds anything worthwhile to the game. Other ion laws involve AI interacting with others player in some way while this one does not and just adds some menial task for the AI to do that nobody else will care about

**Review by Archanial — DISMISSED** [review]
I don't think achievements.dm changes are intentional

**Comment by benbot16** [comment]
> I don't think achievements.dm changes are intentional

I'm not entirely sure why there's a change there. I never intentionally touched it on my repo, and there's no differences between that and master.

**Comment by benbot16** [comment]
Alright, fixed the git issue on my end, shouldn't be showing changes to achievements.dm anymore.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
