### PR TITLE
Nerfs defensive nanites.

### PR DESCRIPTION
**Pull request by Isy232**
## About The Pull Request

Moves all nanite defensive programs armour increase to 30 instead of 50 or 35.

## Why It's Good For The Game

By combining nanites and good armour, you can stack your armour to a massive amount and essentially become unkillable. This isn't good for the game.

Consider some numbers:

Armoured Jumpsuit: 10 melee, 30 stamina

Syndicate Hardsuit: 40 melee, 50 bullet, 30 laser, 40 energy , 60 stamina

HoS Hardsuit: 45 melee, 25 bullet, 30 laser, 40 energy , 60 stamina

Nanite Armour Programs: 50 melee, 35 bullet, 50 laser, 35 energy.
(consumption per armour program is 0.5/tick, for 1/tick with both of them. You have a constant regeneration of 0.5/tick and a maximum volume of 500. You could theoretically have both armour programs running for 1000 ticks.)

Total Armour (Syndicate Hardsuit): 100 melee, 85 bullet, 80 laser, 75 energy, 90 stamina.

Total Armour (HoS Hardsuit): 95 melee, 60 bullet, 80 laser, 75 energy, 90 stamina.

These numbers are generally absolutely crazy. Combined with the nanite healing programs or some other form of healing through chemistry or even further damage reduction through augmentation and you become nigh-unkillable. I dont intend to make nanites near useless, they will still give significant armour.

Total Armour (Syndicate Hardsuit, Nerfed Nanites): 80 melee, 80 bullet, 60 laser, 70 energy, 90 stamina.

Total Armour (HoS Hardsuit, Nerfed Nanites): 75 melee, 55 bullet, 60 laser, 70 energy, 90 stamina.

## Testing Photographs and Procedure

<details>
Its a variable change.

Put screenshots and Videos documenting testing and execution of intended behaviors here

</details>

## Changelog
:cl:
balance: Nanite armour 50/35 => 30.
/:cl:

### CODE REVIEW

**Comment by Isy232** [comment]
I ate a like 5 rounds of buckshot point blank and didnt even enter crit.

I used nanites to fight sec to prove how broken they were as antag, lets see if more people agree with this PR now.

**Comment by Kapu1178** [comment]
> I ate a like 5 rounds of buckshot point blank and didnt even enter crit.
> 
> I used nanites to fight sec to prove how broken they were as antag, lets see if more people agree with this PR now.

translation: I abused a game mechanic to get it nerfed

**Comment by Isy232** [comment]
> translation: I abused a game mechanic to get it nerfed

yep, quite based, right?

**Comment by Hibabo** [comment]
i reckon you can get over 100 if you get a necropolis cornu virus though not much is stopping sec or anyone really from uploading a bad program to screw you over if you have nanites.

**Comment by Fikou** [comment]
NOOOOOOO NOT MY INVISIBLE I-TAKE-HALF-DAMAGE ARMOR BROS NOOOOOOOO

**Comment by Isy232** [comment]
> i reckon you can get over 100 if you get a necropolis cornu virus though not much is stopping sec or anyone really from uploading a bad program to screw you over if you have nanites.

This happened before, a xeno queen got basically punched to death by an invincible guy.

The counter to the upload a bad thing is that you can disable the updating from remote entirely once your done or just hide the server somewhere.

**Comment by Sinestia** [comment]
In practice, uploading bad nanites never happens. 

/tg/'s stats when they removed them demonstrated that, and we can probably expect /tg/ players to do it even more than we do due to powergaming being perfectly allowed and encouraged

**Comment by Isy232** [comment]
I'm totally fine with nanites being this good IF they didnt stack with overarmour. However they do stack with it so it needs a nerf.

If you want strong defensive nanites, code your own nanite program that takes up your suit and helmet slot or at least wont function with it occupied. However that is beyond me and I dont have the time to do it, so this is the best option for now.

**Comment by AnCopper** [comment]
Bump.

**Comment by williamcll** [comment]
Wait since when did we have nanite armor?

**Review by Archanial — APPROVED** [review]
Yes

**Comment by Jeff-3** [comment]
Judging by the TODO in the nanite code, this is arguably intentional [link](https://tenor.com/view/metal-gear-raiden-senator-armstrong-moneyintr-gif-15988527)

**Pull request merged**
