### PR TITLE
Removes pulse slug shells, meteor slug shells, and frag-12 shells from being made

### PR DESCRIPTION
**Pull request by TeomanTheGreat**
## About The Pull Request
Removes craftable pulse slug shells, meteor-slug, and frag-12 (Ignore my shitty commit history I made a small fuckup that does nothing now)

## Why It's Good For The Game
Who thought giving people easy to craft pulse rounds was a good idea? Also frag-12 and meteorslug are busted too.

## Changelog
:cl: Phil Smith
del: Removes craftable pulse slug shells, meteorslug, and frag-12
/:cl:

### CODE REVIEW

**Comment by mcmeiler** [comment]
Grudgecode. Sounds like a skill issue on your part to be honest.

**Comment by TeomanTheGreat** [comment]
> 
> 
> Grudgecode. Sounds like a skill issue on your part to be honest.

bold of you to assume I've played recently.

**Comment by mcmeiler** [comment]
> bold of you to assume I've played recently.

If you're not playing why are you coding to begin with. You're *literally* removing content from the game without replacement, all while *not even playing the game yourself.*

Technological shells require an exploration disk to be researched to begin with, meaning that 90% of rounds they won't be available anyway since explorers only care about their unga gamer loot and omnilathes.

They still require to be printed at either the security or science department lathe, meaning only certain jobs have access to them by default.

Using/seeking them as a non-antagonist without proper reasoning would be powergaming anyway.

A better solution would be to make tech shells unprintable for science, and make them security-exclusive.

**Comment by TeomanTheGreat** [comment]
> A better solution would be to make tech shells unprintable for science, and make them security-exclusive.

Real talk when is sec going to have a use for fragmentation shotgun shells, pulse slugs, and meteorshot. Heck if its to break down a door I think they have breaching shells already.

**Comment by mcmeiler** [comment]
> Real talk when is sec going to have a use for fragmentation shotgun shells, pulse slugs, and meteorshot.

*ahem*

* Desworder traitors
* Murderboning Changelings
* Cult on halo stage
* Clockcult
* Blob
* Nukies
* Probably a shit ton more antags I forgot to list.


> I think they have breaching shells already.

And they are terrible. Take like 5-6 rounds to break a door.

**Comment by TeomanTheGreat** [comment]
"You're _literally_ removing content from the game without replacement, all while _not even playing the game yourself._"
I mean first of off I didn't gut the framework so if someone wanted to they can code in new shells to replace them that aren't busted. Second of off do I really have to have played the game recently to understand that giving people access to literal deathsquad rounds is bad?

**Comment by TeomanTheGreat** [comment]
>     * Desworder traitors
Use a bola
>     * Murderboning Changelings
Sec has a lot of shit to deal with lings
>     * Cult on halo stage
Again sec has other shit to use against these guys
>     * Clockcult
Same as above
>     * Blob
I believe PKAs work well against blob. Also its quite rare to see a blob win already with the type of shit the crew throws at them.
>     * Nukies
Lets see here. Against nukies you can use
 - laserguns
 - normal shotgun shells
 - ion rounds (if they bought shields)
 - etc.

**Comment by mcmeiler** [comment]
Let's assume they are sec exclusive. Sec lathe can't print the required materials other than the tech shells themselves, meaning that, *god forbid,* sec needs to ***TALK*** to ***OTHER DEPARTMENTS WITHOUT TIDING IN WORDLESSLY FOR NO REASON.***

**Comment by BrumalLake** [comment]
they need to be crafted, take time to fire, need to be loaded, normal slugs do 1.5x the damage, and laser guns can shoot much faster while doing half the damage
i doubt you have seen these in action cause they're a pain to make
frag 12 and meteor have also been nerfed before and you're just removing them cause you don't have a better solution
also when have you seen security ask for corn to make frag 12 it has a really tough recipe

**Comment by mcmeiler** [comment]
> Use a bola

Cool, they're slow now. And? They're still reflecting all of your shots and blocking your attacks.


> Sec has a lot of shit to deal with lings

Like? Handcuffs they can melt off? Lasers and shotguns they can outrun? Batongs they will block in melee?



> Again sec has other shit to use against these guys

Lasers that get reflected by mirror shields, shotgun rounds that don't mean jack shit anyway because they have pylons and revive runes, batongs that will once again get blocked in melee.



> Same as above

Except that you're stuck in Reebe, unable to return to station to get more supplies/ammo/whatever.



> I believe PKAs work well against blob. Also its quite rare to see a blob win already with the type of shit the crew throws at them.

pKAs only deal good damage in a vaccum. If the blob is smart it won't space itself unless it has no choice to.

> Lets see here. Against nukies you can use
> 
>     * laserguns
> 
>     * normal shotgun shells
> 
>     * ion rounds (if they bought shields)
> 
>     * etc.

Let's see here, nukies will use:

* semi-auto shotguns that will crit you in 3 shots
* deswords that deflect your bullets and lasers
* mechs with LMGs
* silicons
* explosives
* superior maneuverability in space
* a shuttle surrounded by turrets that shoot you through rwalls

**Comment by TeomanTheGreat** [comment]
> 
> 
> they need to be crafted, take time to fire, need to be loaded, normal slugs do 1.5x the damage, and laser guns can shoot much faster while doing half the damage i doubt you have seen these in action cause they're a pain to make frag 12 and meteor have also been nerfed before and you're just removing them cause you don't have a better solution

If you land a hit on someone they will be slow which will give you the opportunity to reload quite quickly. 
Also I haven't heard about the nerfs to frag-12 and meteorshot. 
Also you claim these take a while to make. Other than glycerol the other ingredients are quite easy to get in the late game.

**Comment by mcmeiler** [comment]
> Other than glycerol the other ingredients are quite easy to get in the late game.

Congratulations, you've found the purpose of the shells, being a late-game option.

Oddly enough I find myself agreeing with Scrubling for once here.

**Comment by BrumalLake** [comment]
> If you land a hit on someone they will be slow which will give you the opportunity to reload quite quickly.

you know this applies to any gun

> Also you claim these take a while to make. Other than glycerol the other ingredients are quite easy to get in the late game

and no i am not gonna interact with people to get some frag 12 or any other tech shells
security doesn't have access to parts for tech shells
and why would i do that when i could just print a slug that does 1.5x the damage in a fraction of the time

**Comment by BrumalLake** [comment]
you also did say some stuff about how security has other stuff to deal with things so why would they use 15 minutes of their precious time making some slugs they will spend in 2 minutes

**Comment by TeomanTheGreat** [comment]
> 
> 
> > Use a bola
> 
> Cool, they're slow now. And? They're still reflecting all of your shots and blocking your attacks.
Meiler you know how good it is if your opponent is slow. At this point you can do plenty of things to them for instance the billy club since it circumvents blocks. Also if your dealing with a murderboning tot man you should have backup.
> > Sec has a lot of shit to deal with lings
> 
> Like? Handcuffs they can melt off? Lasers and shotguns they can outrun? Batongs they will block in melee?
This implies the ling player is playing perfectly. Also if the ling is in cuffs you should gun them down lol. Lasers and shotguns can be outrunned but not very easily from personal experience. Also when dealing with antags for the love of god get backup. You can deal with antags so much easier and can circumvent their blocks by having one guy go around them. 
> > Again sec has other shit to use against these guys
> 
> Lasers that get reflected by mirror shields, shotgun rounds that don't mean jack shit anyway because they have pylons and revive runes, batongs that will once again get blocked in melee.
Shotgun rounds are fucking deadly against cult man. They shatter mirror shields and can do load of damage. If they have a pylon near them then the sec officer is most likely raiding the cult base alone which is never a good idea.
> > Same as above
> 
> Except that you're stuck in Reebe, unable to return to station to get more supplies/ammo/whatever.
Fair enough but you can just take a bunch with you
> > I believe PKAs work well against blob. Also its quite rare to see a blob win already with the type of shit the crew throws at them.
> 
> pKAs only deal good damage in a vaccum. If the blob is smart it won't space itself unless it has no choice to.
I did mention other shit you can use against blob too you know.
> > Lets see here. Against nukies you can use
> > ```
> > * laserguns
> > 
> > * normal shotgun shells
> > 
> > * ion rounds (if they bought shields)
> > 
> > * etc.
> > ```
> 
> Let's see here, nukies will use:
> 
>     * semi-auto shotguns that will crit you in 3 shots
Only if they are close enough and not being focus fired by a bunch of crew
>     * deswords that deflect your bullets and lasers
deswords are strong and there are counters that I listed above.
>     * mechs with LMGs
Use ions
>     * silicons
Use ions (also ion tech shells still exist btw)
>     * explosives
Bomb suits exist but make you slow so just try to dodge them
>     * superior maneuverability in space
Not sure what your planning on doing to a nukie in space unless your hunting one down into space which usually isn't a good idea
>     * a shuttle surrounded by turrets that shoot you through rwalls
Throw a maxcap at it. Or better yet don't go to their shuttle

**Comment by TeomanTheGreat** [comment]
Im going to bed. Ill continue this conversation in the morning.

**Comment by mcmeiler** [comment]
> Use ions

> Use ions (also ion tech shells still exist btw)

You're saying that as if ion tech shells were available roundstart. You're also saying "oh just use ions" as if there's more than 1 ion gun on a map at roundstart. Oh wait, there isn't. What if that ion gun runs out? You're pretty fucked in that case.

**Comment by mcmeiler** [comment]
I'm done arguing here. This PR is stupid and has literally 0 reasoning behind it. I bet you 98% of the playerbase doesn't even know tech shells exist in the first place.

**Comment by TeomanTheGreat** [comment]
> > Use ions
> 
> > Use ions (also ion tech shells still exist btw)
> 
> You're saying that as if ion tech shells were available roundstart. You're also saying "oh just use ions" as if there's more than 1 ion gun on a map at roundstart. Oh wait, there isn't. What if that ion gun runs out? You're pretty fucked in that case.

Ion carbines can be made ya know. Pretty sure if sci rushes it it can be done. Also you can make DIY emp nades by mixing uranium and iron.

**Comment by TeomanTheGreat** [comment]
> I'm done arguing here. This PR is stupid and has literally 0 reasoning behind it. I bet you 98% of the playerbase doesn't even know tech shells exist in the first place.

Lack of people knowing something busted exists isn't balance.

**Comment by mcmeiler** [comment]
> 
> 
> > I'm done arguing here. This PR is stupid and has literally 0 reasoning behind it. I bet you 98% of the playerbase doesn't even know tech shells exist in the first place.
> 
> Lack of people knowing something busted exists isn't balance.

* nobody knows X exists
* well-known player uses X
* everyone knows X exists

Literally a matter of time. Removal still isn't justified considering the amount of "downsides" tech shells have.



> Ion carbines can be made ya know. Pretty sure if sci rushes it it can be done. Also you can make DIY emp nades by mixing uranium and iron.

also locked behind an explo disk now, oh no!

No, like, honestly, you're completely forgetting that these shells are locked behind a rare tech disk that will never get back to station anyway due to the current explorer mentality.

**Comment by TeomanTheGreat** [comment]
> > Ion carbines can be made ya know. Pretty sure if sci rushes it it can be done. Also you can make DIY emp nades by mixing uranium and iron.
> 
> also locked behind an explo disk now, oh no!

Did you read what i said after I mentioned the stuff about the ion carbine?

**Comment by mcmeiler** [comment]
> Did you read what i said after I mentioned the stuff about the ion carbine?

Grenades are comically easy to dodge or even throw back. Now all your guns are drained of power, while nukies still have their powder-based weaponry.

**Comment by TeomanTheGreat** [comment]
> > Did you read what i said after I mentioned the stuff about the ion carbine?
> 
> Grenades are comically easy to dodge or even throw back.

Run at them while holding it and hope there isn't an ipc nearby. Also mechs and silicons cant throw stuff back

**Comment by mcmeiler** [comment]
> Run at them while holding it and hope there isn't an ipc nearby

Remember how nukies have weapons as well?


> Also mechs and silicons cant throw stuff back

If there's mechs and silicons fighting alone, chances are you're fucked beyond recovery anyway.

**Comment by TeomanTheGreat** [comment]
> > Run at them while holding it and hope there isn't an ipc nearby
> 
> Remember how nukies have weapons as well?

Using emp nades on nukies isnt a good idea. Just shoot the shield until it breaks. Ions was a suggestion to deal with it faster.
> 
> > Also mechs and silicons cant throw stuff back
> 
> If there's mechs and silicons fighting alone, chances are you're fucked beyond recovery anyway.

You would be surprised by the amount of over extending assault borgs I've seen

**Comment by TeomanTheGreat** [comment]
Mfw i forgot to update the prs name

**Comment by Archanial** [comment]
> If you're not playing why are you coding to begin with.

😆

**Comment by Isy232** [comment]
Pulse slugs are kind of a joke as actual ballistic slugs are honestly just as effective or almost as. The only exception is walls. I'm fine with their removal though as they dont really serve a purpose besides breaking walls really well.

Frag-12 require botany and chemistry to work together. I have never in all my time seen them made. If you get a few people to work together to make them, maybe you deserve the handful you can make. A syringe gun can arguably do the same for cheaper.

Meteor slug is a semi-taser round that has already been through a nerf by bacon some time ago. It shouldn't be busted anymore. If it still is just nerf the stun time again.

**Comment by PowerfulBacon** [comment]
Pulse slugs are pretty shit unless someone is wearing armor.
The meteor shells are pretty funny for griefing but not as much for killing.
The laser shells which aren't even removed are the absolutely insane ones although I nerfed them at some point already but they already pretty op.

**Comment by TeomanTheGreat** [comment]
Should I swap out removing frag-12 with the laser shot then?

**Comment by mcmeiler** [comment]
Maybe you should actually code a balance change instead of "coding" a removal because you don't have a better idea.

I honestly don't see why you were removing meteorslug to begin with. They were already gutted in another PR.

**Comment by TeomanTheGreat** [comment]
"Maybe you should actually code a balance change instead of "coding" a removal because you don't have a better idea."
Pulse slug kinda seems unbalancable with its versatility against things. Also I havent heard you give me any alternatives.
"I honestly don't see why you were removing frag12 to begin with. They were already gutted in another PR."
Someone suggested it in the pr discussion channel and i assumed they had more experience with it.

**Comment by ivanmixo** [comment]
>massive argument about something I've never seen used in my almost 2k hours

Never change, please.

**Comment by mcmeiler** [comment]
> Also I havent heard you give me any alternatives.

Because that's not my job. I'm done coding for a while. Find your own ideas instead of making PRs for others. The only reason you made this PR was because Zesko and someone else said "tech shell bad" in the discussion channel.

**Comment by TeomanTheGreat** [comment]
> > Also I havent heard you give me any alternatives.
> 
> Because that's not my job. I'm done coding for a while. Find your own ideas instead of making PRs for others. The only reason you made this PR was because Zesko and someone else said "tech shell bad" in the discussion channel.

Actually i came up with the idea myself in general chat after a discussion about balance. You claim its not your role to come up with alternatives but you've spent all this time complaining atleast you can say something useful.

**Comment by BrumalLake** [comment]
there don't need to be alternatives or nerfs cause they're already balanced

**Comment by TeomanTheGreat** [comment]
Well I may as well close this

**Pull request closed without merging**
