### PR TITLE
Skeleton Ghost Role

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
It has been desired by the Head Dev to include more ghost roles and Doc has desired this one in particular!

It only spawns in the chapel around the existing coffins or newly added coffins. It looks like a normal coffin until it is opened, it can not be interacted with it any other way nor can it be destroyed.

This PR is dependent on #11456.

image

## Why It's Good For The Game
More ways of re-entering the round as someone or something else.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image

image

image

image

</details>

## Changelog
:cl:
add: Added skeletal coffin remains which can be controlled by a ghost to a maintenance room.
imageadd: Another ghost stasis landmarks.
tweak: Added some flavouring bones in the coffins around the skeleton spawner.
add: Readded skeletal coffin remains in the maintenance dorms.
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
I am not 100% sold on this as once you spawn in here, you have no way of getting out except maybe bashing through 10 walls for an hour with a shovel. Should they be given an ID with maintenance access to get out?

**Comment by ColonelOrion** [comment]
A skeleton popped out!
Maybe put them in a room with disposals?

**Comment by MarkusLarsson421** [comment]
> A skeleton popped out!
> Maybe put them in a room with disposals?

There is no maintenance room with disposals.

**Comment by Fronsis** [comment]
Perhaps they could spawn on the Chapel coffin area? you would only need to edit the access of the windoor that protects them and afaik most stations have one, that way the can interact with the Chaplain and the crew faster than spawning and spending X amount of time bashing walls to get out

**Comment by MarkusLarsson421** [comment]
> Perhaps they could spawn on the Chapel coffin area? 

Problem is that I don't want them to be guaranteed. However, I could copy the code from the 25% Ripley spawner and to make it chance based.

**Comment by zeskorion** [comment]
On station ghostroles are usually a terrible idea, asking for people to use them as vengeance respawns

**Comment by JixS4v** [comment]
> On station ghostroles are usually a terrible idea, asking for people to use them as vengeance respawns

borgs are way more dangerous than a random skeleton

**Comment by Nakalon** [comment]
Great PR!

**Pull request closed without merging**
