### PR TITLE
Removes monkey from rotation

### PR DESCRIPTION
**Pull request by super12pl**
## About The Pull Request
Removes monkey from rotation on ~~sage~~ both servers, pretty self-explanatory.
monke

## Why It's Good For The Game
Bad mode

## Changelog
:cl:
config: removes monkey from rotation on both servers
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
good change

**Comment by eeSPee** [comment]
I like momke

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
This mode is shit, do it on both servers

**Comment by ToasterBan** [comment]
this was made surprisingly fast after a monkey round on sage, i wonder why

**Comment by ghost** [comment]
> I like momke

momke mode bad

**Comment by super12pl** [comment]
> this was made surprisingly fast after a monkey round on sage, i wonder why

screenshot

**Comment by r1ks-iwnl** [comment]
Monke may be a good concept but in-game its horrible, in 500+ hours i still didnt see a single monke win. Only reason for this gamemode to be enabled is if it gets fixed soon but for now its just boring both for crew and monkies. By far the worst conversion antag there is

**Comment by ghost** [comment]
> Monke may be a good concept but in-game its horrible, in 500+ hours i still didnt see a single monke win. Only reason for this gamemode to be enabled is if it gets fixed soon but for now its just boring both for crew and monkies. By far the worst conversion antag there is

it was "fixed" but it's just a shit gamemode altogether.

**Comment by PowerfulBacon** [comment]
> 
> 
> Monke may be a good concept but in-game its horrible, in 500+ hours i still didnt see a single monke win. Only reason for this gamemode to be enabled is if it gets fixed soon but for now its just boring both for crew and monkies. By far the worst conversion antag there is

I've seen a monkey win, they literally have to get 1 infected person on the shuttle to win

**Review by PowerfulBacon — APPROVED** [review]

**Comment by Crossedfall** [comment]
Has this been voted on?

**Comment by super12pl** [comment]
> Has this been voted on?

not yet

**Comment by TotallyNotChief** [comment]
looks like sage will eventually have their gamemodes reduced to just traitors and bbs

**Comment by super12pl** [comment]
> looks like sage will eventually have their gamemodes reduced to just traitors and bbs

sir its for lrp as well

**Comment by TotallyNotChief** [comment]
Oh no fuck that, please leave the anprim gamemode on lrp

**Comment by Penwin0** [comment]
Its just bad (and gets bugged with IPC monkey leaders not turning ever)

**Comment by eLeCtrOssSnake** [comment]
fuck removals.

**Comment by ghost** [comment]
> fuck removals.

that's nice constructive criticism.

**Comment by bloons3** [comment]
> Its just bad (and gets bugged with IPC monkey leaders not turning ever)

Monkey mode requires admins to babysit it and fix people that turn into borgs (and IPCs that never turn into monkies)

**Pull request closed without merging**
