### PR TITLE
[PORTS] Basepixels and Pixelshifting

### PR DESCRIPTION
**Pull request by Kapu1178**
## About The Pull Request
Ports:
- https://github.com/Skyrat-SS13/Skyrat-tg/pull/870
- https://github.com/tgstation/tgstation/pull/54652

### PIXEL SHIFTING:

> Adds pixel shifting into the game, enabling you to smoothly shift around on the tile you're in. With a few changes.
> Movement is now smooth, you do not need to spam the key you wish to move in, you may hold it down and watch yourself smoothly move.
Keybind is currently **C.**

_This PR does not contain a savefile Burn, existing users will not have this key bound by default. A burn will be added when it is fullmerge ready._
### BASEPIXELS

> 
> This adds two variables (`base_pixel_x` and `base_pixel_y`) and refactors a little of the pixel-shifting code to support better persistent pixel-shifts that would otherwise get reset by most animation and standard shifting procs.
> 
> As of now it doesn't do much besides allowing admins to shift mobs to a different center, but the long-term use of this is to be able to move the mobs up to give a better sense of depth perspective.

## Why It's Good For The Game
Code improvement good.

Pixel shifting allows for more nuanced character interactions, and cannot possibly be used for anything else due to how slow it is.

## Changelog
:cl: Kapu1178, Azarak, Gandalf2k15, Rohesie
add: You can adjust your current-tile location by "pixel shifting". Default key is C, check your binds.
code: Added base_pixel vars to atom/movable, replaced most uses of initial(pixel).
/:cl:

### CODE REVIEW

**Comment by Pirill** [comment]
Fuck yeah!

**Comment by imsynthex** [comment]
sounds funny and based, no idea what they are though

**Comment by MNarath1** [comment]
> sounds funny and based, no idea what they are though

Seems like it allows you to offset your character pixels a bit on a tile the aka it translates your sprite a bit to the right up down while you technically stay on the same tile

**Comment by BrumalLake** [comment]
it allows for marginally better roleplay

**Comment by PowerfulBacon** [comment]
I'll be honest, I don't like this. The only thing I've seen it used for apart from schooching up to people for some extreme roleplay is people using it to look stupid and merge themselves with walls

**Comment by ike709** [comment]
🔑

**Pull request closed without merging**
