### PR TITLE
Fix my TGUI mistakes & tweak uplink atomized edition

### PR DESCRIPTION
**Pull request by Sinestia**
## About The Pull Request

Don't get sloppy with find at 5 am kids!~

Also tweaks the uplink, it will open at a fitting size and will autofocus for typing
## Why It's Good For The Game

Panel will be right, air alarm will be right, syndicate contractor won't be right but it will look right

## Changelog
:cl:Froststahr
fix: Some TGUI mistakes have been corrected, panel, air alarm, and contractor uplink should look good again. 
tweak: Uplink interface has been modified in looks, and will auto-focus
/:cl:

### CODE REVIEW

**Comment by Sinestia** [comment]
alright damnit, I guess I really do have to make sure I'm doing any tgui on a small 16:9 screen

**Comment by Sinestia** [comment]
My bad, I drafted because it failed to adjust properly when I changed my main monitor from different aspect ratio and a massive larger resolution to a smaller one to be sure it worked on normal cases. It just needed a reconnect

**Review by PowerfulBacon — DISMISSED** [review]
Good, but uplink needs fixing too. The font size has been increased massively and only like 4 items fit on the screen at once now.

**Comment by Sinestia** [comment]
uplink seems same before and after

**Comment by Sinestia** [comment]
Threw it in nonetheless 
https://cdn.discordapp.com/attachments/586312879200927767/861648956105818152/unknown.png

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
