### PR TITLE
Ports the edible component from TG

### PR DESCRIPTION
**Pull request by benbot16**
## About The Pull Request

This ports tgstation/tgstation#48596, as well as a few bugfixes and improvements made in later PRs.
For now this is only applied to organs, but I've seen some people are interested in porting TG's newfood system, and this (in addition to some other components that I'd like to port) is a prerequisite for that.
This also allows you to make pretty much any item edible, which is probably a good thing.

Some features of this component:
- Food takes time to eat when using it, and it'll loop if you're not forcefeeding someone
- you can use the pre_eat callback to add edibility checks
- after_eat and consume_callback allow you to do things when a mob takes a bite and finishes the food.

## Why It's Good For The Game

This allows us to make food items that aren't reagent_container subtypes, and means we don't have to do conversions for things like organs when eating them.
This was also on the list of things to port.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/9423435/223235803-6a467368-c2a4-4da9-9998-e9404b896bce.mp4

</details>

## Changelog
:cl: Ghost, Benbot16
add: Ports the edibility component.
refactor: Organs don't turn into food objects when you eat them anymore, and they take a small amount of time to eat. Taking a bite out of them still makes them unusable. 
/:cl:

### CODE REVIEW

**Comment by imsynthex** [comment]
> Food takes time to eat when using it, and it'll loop if you're not forcefeeding someone

This should be in the changelog

**Comment by Absolucy** [comment]
> Food takes time to eat when using it, and it'll loop if you're not forcefeeding someone

Dumb idea, make it so it still takes time, but you can still eat while moving (the progress bar will just still continue while moving).
It's not very hard to shove food in your mouth while walking.

**Comment by benbot16** [comment]
> > Food takes time to eat when using it, and it'll loop if you're not forcefeeding someone
> 
> Dumb idea, make it so it still takes time, but you can still eat while moving (the progress bar will just still continue while moving). It's not very hard to shove food in your mouth while walking.

Later ports I'd like to make have special handling for that, since it makes sense for some foods but not others, but since this really only effects organs right now I can probably just change it for that.

**Comment by benbot16** [comment]
Okay, apparently bee just doesn't have that sort of do_after functionality right now, but I can probably poke at it anyways.

**Comment by Absolucy** [comment]
> Okay, apparently bee just doesn't have that sort of do_after functionality right now

uninterruptible = TRUE, with a custom extra check to make sure you aren't stunned and such

**Comment by benbot16** [comment]
> > Okay, apparently bee just doesn't have that sort of do_after functionality right now
> 
> uninterruptible = TRUE, with a custom extra check to make sure you aren't stunned and such

Yeah, but that feels hacky. I'll try something else, might take a bit though.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
