### PR TITLE
Borg Radial Menus 

### PR DESCRIPTION
**Pull request by Sinestia**
## About The Pull Request

port of https://github.com/tgstation/tgstation/pull/57827
partial port of https://github.com/tgstation/tgstation/pull/56312
## Why It's Good For The Game
 spinny clicky
more importantly is the preview for what your skin will actually look like. Actually choosing the module is pretty ugly without that nice mouseover text but i went with consistency instead

was gonna add some skins (or even enable some of the ones that exist in our code) but opted not to for this PR as there's better quality versions elsewhere

## Changelog
:cl:froststahr
add: Borgs use radial menus for module and skin selection
/:cl:

### CODE REVIEW

**Comment by bloons3** [comment]
Add dog borg

**Comment by Sinestia** [comment]
> Add dog borg

skyrat dog borgs 2021

**Comment by ghost** [comment]
Add skyrats cyborg skins that AREN'T dogs

**Comment by Sinestia** [comment]
> Add skyrats cyborg skins that AREN'T dogs

Ironically, I think the dogs are about some of the only well-designed ones

aside from maybe a couple roombas, and some of the standard ones a lot of servers had like fancy mediborgs

Any borg sprite should look distinct, some of the skyrat ones look like garbled trash.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
