### PR TITLE
Removes adminheal and instant death bolts from xenobiology magicarps (Chaos + regular).

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Removes the instakill and instaheal carps from xenobiology.

## Why It's Good For The Game

The death magicarp is not really fun for anyone, when spawned by an antagonist you have a carp that can kill you at ranged in a single shot and when spawned to hunt antagonists, you are against a carp that can kill you at ranged in a single shot.

The adminheal carp bolt has been removed too, since it heavily disrupts rounds when someone manages to create it.

Death is a part of the game and instant heals completely disrupts that. Antagonists have an impossibly tough time pulling off their sneaky kills when a carp can come along and instantly do everything the medics could ever dream of. Medical is completely bypassed by the creation of this carp.

As for death, obviously we all know why a carp that can instant kill at range anyone not holding a ~~bible is a bad idea.~~ Literally just the null rod can protect you, even standard wizards get 1 shot by this.

## Changelog
:cl:
balance: Removes the bolt of death and bolt of adminheal from xenobiology space carps (Chaos + Regular)
/:cl:

### CODE REVIEW

**Comment by RDS88-beeman** [comment]
wasn't this done already?

**Comment by zeskorion** [comment]
> wasn't this done already?

Back when peopl used the dumb vote stuff

**Comment by RDS88-beeman** [comment]
we still use the voting system.

**Comment by francinum** [comment]
IMO carps as a whole probably aren't great to keep in the gold slime spawn pool, as even before crossbreeding, they are functionally the crown goal of the subdepartment.

**Comment by BrumalLake** [comment]
> 
> 
> > wasn't this done already?
> 
> Back when peopl used the dumb vote stuff

thought you were thinking of polymorph

**Comment by zeskorion** [comment]
> > > wasn't this done already?
> > 
> > 
> > Back when peopl used the dumb vote stuff
> 
> thought you were thinking of polymorph

nope, i tried removing it from the pool back in the day

**Pull request merged**
