### PR TITLE
Winter Coat Addition - Mail Bag Tweak

### PR DESCRIPTION
**Pull request by Nakalon**
## About The Pull Request

Mailbag is now a type of bagpack.

Mailbag now has inhand sprites bagpack sprites and belt sprites.

Theres now a white winter coat to prepare to add winter coats to the washing machine dying system.

The white winter coat can be bought in the bee shop for now.

## Why It's Good For The Game

Cargo needed some love and mailbags are underused since you had no real place to put them.
And due to not having a inhand sprite or wear sprite there was no real RP reason to decide to carry it around regardless.

Also increases the efficiency of EPS units, which is awesome.

Also the white coat is important for customization. Not only later down the line but also you can paint it with spraycans easily.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image (44)
image (43)
image (42)
image (41)
image
image (47)
image (46)

</details>

## Changelog
:cl: Solene Yoon, RKZ
tweak: Mailbag is now a type of Stachel, so they can be used in the back slot.
code: Repathed Mailbag and all references to it to be a subtype of satchel.
tweak: flipped the sprite for the Mailbag to make it consistent with other duffel bags.
imageadd: Added sprites for the Mailbag, inhand and equipped (backslot and belt slot).
tweak: Added a line to the description of cargo winter coats to make it obvious to players it can carry cargo related items.
add: Added a white winter coat and made it available in the bee shop.
imageadd: Added sprites for the white winter coat.
code: RKZ made the mailbag accepted items list less ugly.
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
can you still wear the mailbag on your belt slot?

**Comment by Nakalon** [comment]
> can you still wear the mailbag on your belt slot?

This makes me feel real bad because the only reason I made this was because I wasn't aware you could put it in the belt slot.

As it is right now no, but I've asked EPS and I'd like to ask other cargo players if they rather:

1 - Have it fit bagpack and cargo winter coat suit storage
2 - Have it only in the belt slot.
3 - Have it in them all.

Due to the sheer size of the mailbag I really thought it should have been a type of duffelbag. But if you rather it be only usable in the belt slot idk if I can make the sprites for that reliably because the bag is so big.

**Comment by Nakalon** [comment]
I'm still working on this bitch

**Comment by Nakalon** [comment]
this bitch done

**Review by Rukofamicom — APPROVED** [review]
👍

**Pull request merged**
