### PR TITLE
Ports "Nanotransen Legal Liability Initiative - Weapon Stats but more RP" from /tg/

### PR DESCRIPTION
**Pull request by BrumalLake**
Part of things to port https://github.com/BeeStation/BeeStation-Hornet/projects/2#card-61676747

## About The Pull Request
ports https://github.com/tgstation/tgstation/pull/58865
ports https://github.com/tgstation/tgstation/pull/59778

modified for zeskoblocking
image
image

nonlethal ballistics don't say how effective they are at paralyzing shh (wyci)
kinda a sister pr to armor tags

## Why It's Good For The Game
now i won't be the only person to know that advanced mops have 12 force and passive blocking + block upgrade walk
and that most armory guns have block upgrade walk while eguns don't
maybe people will stop using stun batons when they realize they do 5 brute which is less than half of what using your bare hands on someone who's down does

## Changelog
:cl: lordScrubling, SpaceDragon00
add: weapon tags showing combat stats on weapons, magazines, guns, casings
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
A bluespace warning label. Couldn't it say something like it looks like there are notes about this on the Nanotrasen database or something generic.

**Comment by francinum** [comment]
cooltext391398127812461

**Comment by zeskorion** [comment]
So players *shouldn't* be given accurate information on what their weapons do?

Edit: and doesnt a pr need two maintainers to approve its closure/merging or is that policy not in place as i was under the impression it was

**Comment by Sylphily** [comment]
yes

**Comment by francinum** [comment]
> So players _shouldn't_ be given accurate information on what their weapons do?

Yes

**Comment by BrumalLake** [comment]
> Edit: and doesnt a pr need two maintainers to approve its closure/merging or is that policy not in place as i was under the impression it was

there was some fine print somewhere exempting francinum
you'll probably see it some day if you stare at this sentence for long enough
image

**Comment by ike709** [comment]
> there was some fine print somewhere exempting francinum

No there isn't and the maintainers have been given a stern talking-to.

**Comment by francinum** [comment]
This resulted in a mildly productive internal discussion into the idea of this PR. The problem is that at the moment this information IS disseminated, just primarily via codediving and other out of game ideas, and while I personally believe it's best that we move towards a gameplay paradigm where the concept of TTK simply doesn't exist, that would involve a substantial change to the way medical works as a whole.

I'm not a fan, but I also didn't handle this at all properly.

The mere fact that this system purports to be 'RP compliant' despite working under the vaguest framework and treating 'RP compliance' as simply 'making you read a paragraph to determine what the fuck its saying' is the main reason I believe it's strictly against the interests of the codebase and our direction.

It, in itself, admits that it has no place in a RP environment.

**Comment by zeskorion** [comment]
> This resulted in a mildly productive internal discussion into the idea of this PR. The problem is that at the moment this information IS disseminated, just primarily via codediving and other out of game ideas, and while I personally believe it's best that we move towards a gameplay paradigm where the concept of TTK simply doesn't exist, that would involve a substantial change to the way medical works as a whole.
> 
> I'm not a fan, but I also didn't handle this at all properly.
> 
> The mere fact that this system purports to be 'RP compliant' despite working under the vaguest framework and treating 'RP compliance' as simply 'making you read a paragraph to determine what the fuck its saying' is the main reason I believe it's strictly against the interests of the codebase and our direction.
> 
> It, in itself, admits that it has no place in a RP environment.

As a person who codedives and is advantaged by this information not being obvious,  i believe this feature is good, and evens the playing field between newbies and people who have an encyclopedic knowledge of the game. I think this should be reopened for that reason

**Comment by francinum** [comment]
I mean, I still blame *your* blocking system for being a perfect example of codedive only information...

**Comment by zeskorion** [comment]
Yes, and this is a good solution for it.

**Pull request closed without merging**
