### PR TITLE
IPC brains appearing as IPC brains inside MMI

### PR DESCRIPTION
**Pull request by Nakalon**
## About The Pull Request

IPC brains no longer look like a human brain inside an MMI.
Now they look like IPC brains, duh.

## Why It's Good For The Game

Immersion... Doesn't make much sense for the IPC brain to be a human brain inside an MMI...

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image
Ignore my little workshop of horrors.
</details>

## Changelog
:cl:
tweak: IPC brains now appear as IPC brains when inside an MMI.
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
> Screenshots&Videos
> image Ignore my little workshop of horrors.

Do they still show the glowing red lines indicating they are "alive brains"? This is usually an indicator if the posibrain/IPC brains are inhabited. 

On posibrains it is blue, on IPC brains it is red

**Comment by Nakalon** [comment]
> > Screenshots&Videos
> > image Ignore my little workshop of horrors.
> 
> Do they still show the glowing red lines indicating they are "alive brains"? This is usually an indicator if the posibrain/IPC brains are inhabited.
> 
> On posibrains it is blue, on IPC brains it is red

yes bad photo on my part!!
Its animated the same as a normal IPC brain! I'll take a different photo later!

**Comment by EvilDragonfiend** [comment]
lol now it makes sense

**Review by Rukofamicom — APPROVED** [review]
Looks a little odd, but not nearly as odd as a fleshbrain does. I'd almost rather IPC brains just be able to insert directly, but this is still a substantial improvement imo. 

Waiting for Pigeon input.

**Comment by Nakalon** [comment]
> Looks a little odd, but not nearly as odd as a fleshbrain does. I'd almost rather IPC brains just be able to insert directly, but this is still a substantial improvement imo.
> 
> Waiting for Pigeon input.

Sadly that involves a lot of complex code I can't exactly wrap my head around.
I'm trying to make a reverse MMI for the time being, if I manage that I can surely manage doing the IPC just working as a posibrain!

**Comment by Nakalon** [comment]
https://github.com/BeeStation/BeeStation-Hornet/assets/94647521/55aeb6e4-8596-4879-a673-b14fb6ef6be3

Heres the brain but in video format

**Comment by EvilDragonfiend** [comment]
MMI code and IPC brain is totally different one, so I don't expect any tweak there can happen. I am fine with this.

**Review by EvilDragonfiend — APPROVED** [review]

**Review by PestoVerde322 — APPROVED** [review]

**Pull request merged**
