### PR TITLE
Unique Heretic Ascension Announcements

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

Port of https://github.com/tgstation/tgstation/pull/82878

Music by @flleeppyy, and you can listen to them out-of-game here: https://flleeppyy.bandcamp.com/album/ss13-heretic-ascension-sounds

Also refactored how heretic ascension announcement works - it's a part of the `/datum/heretic_knowledge/final/on_finished_recipe()` proc now, and each path's subtype just sets the `announcement_text` and `announcement_sound` vars.

## Why It's Good For The Game

Adds extra flavor and spice to the game for important events, much better than the overused generic "space-time anomalies" announcement.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

me when i dig out a 514 build out of the depths of hell for sound effects

https://github.com/user-attachments/assets/07006eb7-7812-4199-855b-49cea17d3c89

</details>

## Changelog
:cl: Flleeppyy, Absolucy
sound: Added unique announcement jingles to each heretic path's ascension, replacing the old "space-time anomalies detected" announcement.
refactor: Cleaned up some repetitive code related to heretic ascension announcements.
/:cl:

### CODE REVIEW

**Review by Tsar-Salat — APPROVED** [review]
I saw the original PR when it was made, it looked really sick.

Glad it's being brought here. Code looks good.

Approved.

**Comment by Fronsis** [comment]
Same as what said above, when you first ported it to Monke i thought it looked super neat, thanks for bringing it up!

**Comment by Absolucy** [comment]
@Rukofamicom https://github.com/user-attachments/assets/07006eb7-7812-4199-855b-49cea17d3c89

**Review by Rukofamicom — APPROVED** [review]

**Review by EvilDragonfiend — APPROVED** [review]
Very obvious code

**Pull request merged**
