### PR TITLE
Science lootdrop changes

### PR DESCRIPTION
**Pull request by Therealdoooc213**
## About The Pull Request

Removes hand teleporters from the lootdrop 'science' and replaces it with a portal gun

## Why It's Good For The Game

Hand teleporters are supposed to be a extremely limited item, it shouldnt be able to be found on space ruins/some maps.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

View code.

</details>

## Changelog
:cl:
tweak: hand teleporters are no longer available via science lootdrop spawners, now replaced with a portal gun
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Replace it with something equally powerful or valuable

**Comment by EvilDragonfiend** [comment]
I like it being there tho

**Comment by Therealdoooc213** [comment]
Updated, it now drops a portal gun instead

**Comment by EvilDragonfiend** [comment]
lame

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
