### PR TITLE
Removes ERP

### PR DESCRIPTION
**Pull request by imsynthex**
## About The Pull Request

Removes ERP

## Why It's Good For The Game

Deep throating sausages is bad

## Changelog
:cl:
del: Removed sausage eatverb "deep throat"
/:cl:

### CODE REVIEW

**Comment by kit-katz** [comment]
ERP bad

**Comment by mcmeiler** [comment]
Do not ERP

**Comment by BrumalLake** [comment]
do not merge
ty

**Comment by eeSPee** [comment]
But how will I know to impress my lady if I don't learn it through ss13?!

**Comment by TeomanTheGreat** [comment]
He did it erp is gone!

**Comment by DatBoiTim** [comment]
About time

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
