### PR TITLE
Lavaland Improvements

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
### Nanite Ruin

Adds a Lavaland Nanite Ruin. Similar to the Animal Hospital it got there through BS reasons.

All possible spawnable nanite programs and their weight. It will spawn five of them and the recently removed mindshield is guaranteed. These do not unlock the research, so overwriting them will make them be lost forever.
hardening = 10
coagulating = 10
glitch = 10
monitoring = 10
regenerative  = 10
metabolic_synthesis = 10
repairing = 8
aggressive_replication = 8
viral = 4
pacifying = 4
spreading = 2
explosive = 1

### Sloth
Made it not annoying WIDE by making it a cube instead.
I'd almost want to delete it but I feel like it does serve somewhat of a purpose of not making ALL ruins beneficial.

### Inactive Swarmer
A crash but intact and working swarmer transport shuttle. It has a syndicate toolbox, a 10% filled plasma canister and an inactive swarmer beacon.

### Nanite Ruin
Allows antagonistic miners to make their own nanite programs without breaking into R&D and allows non-antagonistic miners to get the Scientist folks fancy nanite programs or useless nanite programs. It does include a working camera so if a miner gets power to it the AI can help them unbolt the secure door.

### Sloth
Fuck it. Always so wide, big and unbreakable.

### Inactive Swarmer
Allows miners to find and use a working shuttle. It would have to be refueled with additional plasma sheets or plasma gas and can be used by antagonists for various deeds.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image

image

</details>

## Changelog
:cl:
add: Added random nanite disk spawner.
add: [Lavaland] Nanite Lab ruin.
add: [Lavaland] Two variants of lavaland outposts.
add: [Lavaland] Inactive Swarmer Shuttle.
tweak: [Lavaland] Replaced Science with Atmospherics on lavaland outpost.
add: [Lavaland] Lavaland gas miners.
tweak: [Lavaland] Made the sloth area not painful to simply exist.
add: [Lavaland] Added abandoned Lavaland TEG.
add: [Lavaland] Empty Lavaland (no outpost or fixed structures).
add: [Lavaland] Added Fax machines to the different lavaland departments.
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
The goal is to double the amount of ruins by making abandoned / pristine variants of existing ruins and adding my own ideas along with making different lavaland maps for more variety in where you are.

**Review by Rukofamicom — DISMISSED** [review]
I am strictly against the nanite lab.

I would not be against adding nanites to the syndicate outpost as a place for ghosts to practice doing nanites, but miners should absolutely not gain access to nanites outside of the station scientists doing them on their own.

Nanites as they currently are also do not need a buff making them even remotely easier.

**Comment by Rukofamicom** [comment]
Good, new ruins would be some more actual ruins - ruined structures and/or facilities. Shuttle crash sites would be great flavor to add, especially if they're possible to repair - a spare shuttle being available to miners would better enable asteroid mining.

**Comment by MarkusLarsson421** [comment]
It will spawn five nanite programs, which are just the disks themselves. With a guaranteed mindshield nanite program disk. Its small profile and lack of a GPS signal make it an inconsistant wildcard in whether it is found and if it will be used or not. A normal miner doing their own nanites there would classify as clear powergaming.

**Comment by MarkusLarsson421** [comment]
> Shuttle crash sites would be great flavor to add, especially if they're possible to repair - a spare shuttle being available to miners would better enable asteroid mining for those that like to get into it, but don't have or want to take the time to build their own shuttle for it.

The Swarmer shuttle is a Syndicate shuttle that can very easily be utilized as one wishes. The swarmer beacon inside will emit a GPS signal, but it is not active.

**Comment by Fronsis** [comment]
Agreed with Ruko about nanites, it's already a pain in the ass to fight an antag miner that's full of insta heals and whatever other shit they usually carry, now they're just gonna minmax another half an hour tomake their private cloud to be even more powerful, they should be spending more time antagonizing rather than minmaxing efficiency.

I think the Sloth ruin being a square takes a shitton more space compared to the horizontal one, and yeah.. the point is that it's annoying and has no reward.

Does the inactive swarmer beacon do.. anything if it's inactive?

**Comment by MarkusLarsson421** [comment]
> I think the Sloth ruin being a square takes a shitton more space compared to the horizontal one, and yeah.. the point is that it's annoying and has no reward.

It is less likely to block your path compared when it was like 50m horizontal.

> Does the inactive swarmer beacon do.. anything if it's inactive? 

No, it is more or like only there because it is the swarmer transport shuttle. It's rarely seen, but the swarmer beacon actually spawns on a broken / crashed shuttle. I made it look similar to its crashed variant.

**Comment by Rukofamicom** [comment]
> It will spawn five nanite programs, which are just the disks themselves. With a guaranteed mindshield nanite program disk. Its small profile and lack of a GPS signal make it an inconsistant wildcard in whether it is found and if it will be used or not. A normal miner doing their own nanites there would classify as clear powergaming.

Then they shouldn't have the option presented to them. It is bad design to hand access to a player on a silver platter and then expect staff to punish them for utilizing it. 

If you really insist on keeping the nanite lab ruins, then at least do this:
* Make it so there are not enough functional machines for miners to program and inject their own nanites without, at bare minimum, golem assistance to complete the system via their technology. It should not be possible to make and inject functional nanites from the ruin alone.
* Keep the mindshield program removed. It is not good for the game to have. 
* I'm okay with data disks spawning as long as they can't be utilized by the miners.

**Pull request closed without merging**
