### PR TITLE
Removes Exolocomotive Xenomitosis

### PR DESCRIPTION
**Pull request by francinum**
Reverts a segment of #2358

This symptom is generally considered obnoxious and is overall an administrative headache.

## Why It's Good For The Game
It's ugly and only really causes administrative shitstirs.

## Changelog
:cl:
del: Exolocomotive Xenomitosis has been removed.
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
Do you have an alternative symptom which fills both of the same niches Exolocomotive Xenomitosis fills? 

Honestly, a new Sprite'd fix the larger issues

**Comment by ghost** [comment]
Is this the one that makes you shit pink codersprites everywhere?

**Comment by francinum** [comment]
Yes.

**Comment by bloons3** [comment]
> Do you have an alternative symptom which fills both of the same niches Exolocomotive Xenomitosis fills?
> 
> Honestly, a new Sprite'd fix the larger issues

What _is_ the niche that it is supposed to fill?

**Comment by ghost** [comment]
> > Do you have an alternative symptom which fills both of the same niches Exolocomotive Xenomitosis fills?
> > Honestly, a new Sprite'd fix the larger issues
> 
> What _is_ the niche that it is supposed to fill?

passive healing via envoirmental spreading structures.

**Comment by francinum** [comment]
Passive Healing (Of a damage type as basic as brute) is a niche that is not Virology's to fill, much less one that should ideally exist at all.

**Comment by zeskorion** [comment]
> Passive Healing (Of a damage type as basic as brute) is a niche that is not Virology's to fill, much less one that should ideally exist at all.

It has always been the niche it was originally intended to fill. The symptom is fine mechanically, it just needs better sprites.

**Comment by bloons3** [comment]
It makes sense for Xenos to have it (xenoweed passive healing), since they have no other way to heal mechanically and it gives the station a nice xeno vibe...

But players constantly spewing pink vomit that rapidly overtakes the station is just eye rape, and makes the entire place look like a shithole. Not really something to encourage, especially when there's already enough viro can do to "be helpful" that's just minor grief at best.

**Comment by francinum** [comment]
a magic material spreading over the station rarely looks good, and is usually something the crew is expected to *fight*, not something *helpful*

**Comment by leestriter** [comment]
I do a lot of virology and it is a super useful symptom for transmitting diseases and for its brute healing. I'd be very sad to see it go, but would be ok with a less obtrusive sprite. I'm also not a big fan of just removing features. I'm a big fan of exoloco myself, one of my favorite symptoms.

**Comment by eeSPee** [comment]
Medical can already offer passive regeneration by implanting xeno glands into people.

This isn't even anything different; it's shitty xeno resin that is ugly pink. Why does it have a right to exist?

**Review by zeskorion — CHANGES_REQUESTED** [review]
doesn't completely remove exoloco sprites (the zombies and the macrophages)

**Comment by francinum** [comment]
Considering our dear zesko has exited stage right, I'd like to retable this.

**Comment by leestriter** [comment]
I mean even without zesko this still lost the vote.

**Comment by francinum** [comment]
I also have massive issues with how the vote was ran, it's also been a month and since Zesko has stepped away it's unlikely this feature will see further active maintenance.

**Comment by leestriter** [comment]
I wish we'd replace it with something or fix it but whatever the community thinks is what matters. It's just a nice symptom for spreading beneficial diseases and also healing brute, and I think its only real problem is the ugly fucking sprite. Like I think we are all agreed that the sprite sucks.

**Comment by leestriter** [comment]
Like give me back the old school contagious sneeze and throw together something for a little passive brute healing and I'd be down. I just don't like when things are just removed when they could be fixed or replaced.

**Comment by francinum** [comment]
I maintain my previous position that no sprite change is going to make people tolerate this shit.

Sometimes you just need to access the floor.

**Comment by leestriter** [comment]
I mean I understand that concern, like I said, I think it certainly need to be changed, I just feel straight removal is the laziest way to fix a problem.

**Comment by francinum** [comment]
I see no reason to retain it. If you would like it to be retained, you're welcome to open a PR to attempt to fix these problems.

I'm not wasting my time.

**Comment by Ravellon** [comment]
The symptom fills two niches: very decent brute heal and a vector for spreading other viruses.
There is only two other symptoms that heal brute: regen coma and superficial healing. Superficial healing does not work when there is more than 30 damage and regen coma knocks you out.
Removing this symptom is a direct nerf to virology.
Even if it is never used for its beneficial traits, it still has a right to exist as part of viro's weaponised toolkit.
Removing this virus will not be good for the game. It will detract from virology without adding anything.

**Comment by leestriter** [comment]
Why did this get merged when it lost the vote?

**Comment by Flakkyboo** [comment]
Vote doesn't mean anything and is just a formality

**Pull request merged**
