### PR TITLE
Gun Coolification - Ammo Culling, Fixes, Tweaks and Additions

### PR DESCRIPTION
**Pull request by Nakalon**
## About The Pull Request

# CONSIDER THIS PR CLOSED
I'm only keeping it open to see what I can salvage from it.

<details>
<summary>Rant Explaining why I'm doing this</summary>
I like guns in this game.
I spent most of my in-game time selling, creating, stealing and in general AROUND guns in the Joon Shop.

So I was very excited to hear Vick was working on making guns, specifically more improvised guns.
The PR came and got merged. I couldn't wait to try it out.

It touched a LOT of things about ballistics some I disagree with.
I played with the new guns, wasn't very happy.
Played with toy guns, couldn't pick up ammo.
Player with the lever action, bugged that shit into creating non existing bullets using speedloaders.

A lot of things were added and able to be crafted but crafting them is an absolute quest (for many reasons, not all of them to do with this PR).

So I took a step back, thought a while and I came to inevitable conclusions.
There are too many ammo calibers.

The new SMG uses 9mm, which is used for like only one gun found in explo.
The Single Shot Rifle uses 7.62 which is only used in the Mosin Nagant, and is found only via cargo order (and now you can craft improvised bullets)

The WT Autofire rifle uses 4.6x30mm. Used... only in the WT Autorifle. Where can you find it? Sec Lathe only.

Why can you make 10mm, Stechkin ammo (used only in the stechkin), in the Autolathe when the Security Overide is active?
But you can't make WT ammo?
What?
But you can make 9mm.
Except it costs like 30 Iron.

Fuck that.

</details>

#### Lever Action Pipe Rifle
<details>
<summary>Lever Action Pipe Rifle Details</summary>

I chose to turn the Single Shot Pipe Rifle into a Lever Action Pipe Rifle.

Lever Actions have a good feel and were a great addition, plus, .38 is more easily avaiable than the stupid 7.62.
This is a worse version of the Lever Action orderable by cargo (just as the Single Shot was the same for the Mosin).

It's chambered for .38
Is able to hold 5 bullets (6 if you chamber the last round manually)
Has medium recoil and spread. (more than the Parent Rifle)

The real kicker is, when sawd off it becomes a different gun.

It becomes a Volcanic Pipe Pistol.
Same ammo, same bullet count
BUT, it deals less damage
Has more recoil and spread (inherent to sawing off)
It's a little more quiet
Is considered small (so you can put it in your pocket)
And can be levered with only one hand

image (31)

I also added an overlay for the sling you can make with cable.
And shortened the in_hand sprite a bit.
(You can't see those in this image)

In addition, I fixed a bug regarding Lever Action and Speed Loaders.
So now, using a Speed Loader on a Lever Action will now insert only one bullet at a time, to chamber the extra round you must chamber the bullet itself manually.

</details>

### Multiplier Vars

<details>
<summary>Multiplier Vars Details</summary>

To make the above possible and in order to have more guns chambered for the same ammo type I created a Damage and Speed multiplier var to guns. Which will multiply the values of the chambered bullet.

image (32)

So you can now control how much damage a gun deals almost independent of the bullet's caliber.

</details>

### Ammo Sweep Var

<details>
<summary>Ammo Sweep Var details</summary>

I wasn't happy how I couldn't pick up nerf gun bullets back up easily. Not being able to pick it up makes you have that cringe downtime that happens in real-life where you're like "wait guys let me find my bullets".

Since I didn't want to change the code Vick made I made an Ammo Sweep Var.
Ammo boxes with this var can now pick ammo again.
This is just for Toy guns here.

image (33)

</details>

### Pipe Pistol

<details>
<summary>Pipe Pistol Details</summary>

When I played with the Pipe SMG I thought it was:
A Pistol because of how fucking low it fires and how it looks
Busted for having an upgradeable ammo mag (which is an awesome creation)
Horrible to handle because it is BULKY SIZED

Since I didn't know why this wasn't a pistol I made a pistol.
The numbers still need to be reviewed a bit since I want it to remain a pistol and not something you have to tie to your waist.

I'm still considering changing the SMG to be more like an actual SMG and not just replace it with this.
It's still chambered for 9mm.

image (34)

On the left you can see the Pistol on the right the original SMG.
"But Joon why does the mag go on top"
Don't be silly guys, its a DIY weapon, you need as much help as you can get so now gravity is putting in a little work.

</details>

### The Ammo Caliber Culling

<details>
<summary>Ammo Caliber Details</summary>

You know what isn't cool?
Finding a cool gun and spending the rest of the round trying to find out what ammo it uses and where to get it.
Only to realize its a specific ammo type just for that exact gun.

In short, WT Rifle now uses 9mm.
Stechkin now uses 9mm.
Pipe gun/SMG uses 9mm.
Stechkin deals the most damage.
WT deals the lowest. And has a MUCH HIGHER FIRE RATE (Now you can actually use it full auto instead of semi being faster)

image (35)

</details>

### Ammo Type Expansion

<details>
<summary>Ammo Expansion Details</summary>

You know whats really cool?
Different Ammo types.
You know what fucking cooler?
Lazors.

And why isn't there rubbers for more guns?
Rubbers are really cool, why do you want me to be a murder man.

Only got 9mm so far but here is Rubbers, Laser and Disabler 9mm ammo and mags:

togif-ezgif com-video-to-gif-converter

Yeah it works on the WT also. Lightshow.
I'm also standardising Mag/Ammo naming and colours.
Like rubbers being green (this changes WT rubber mags to green instead of blue also)

</details>

### Laser Colours

<details>
<summary>Laser Colours Details</summary>

Because more ammo types mean more different lasers and more different lasers means we need more colours.

So I made a white sprite for the Laser effects, so it can be coloured (WITHOUT ANY SPRITING) via the Light Colour, which was already in use anyways.

image (36)

Mind you this isn't in use YET. And I may eventually decide its best to cut down on ammo types and give laser colours for players to mess around with due to me being such a champion for costumisation.

</details>

### Rubber Bullets Sound

<details>
<summary>Rubber Bullets Sound Details</summary>

Rubber bullets were always a bit problematic in that you didn't know if you were being shot with lethals or not.

I decided to create a var for bullets that defines wether or not they should display a different sound on fire.
This is what it sounds like.

https://github.com/BeeStation/BeeStation-Hornet/assets/94647521/4a085dbf-c055-4427-82bd-fd4ec509311e

I reused the ricochet sound because that's what rubbers are most known for and I guess it sounds rubbery.

</details>

### What I haven't really done but have planned (for now)

- Add 2 more ways to get Modular Recievers (limited purchase on hacked vendor and step-crafting like grenades or mechs on an assembly made out of iron)
- Add more ammo types specifically laser:
Laser - Ion and Radiation damage
Lasers - Add swappable lenses (internal mags that change the laser gun's laser)
Ballistic - Some sort of small version of shotgun ammo, trash bullets that explode in small fragments that only hurt you when you're very close.
- Add the cool laser gun that fires bullet casings.
- Rework the tesla gun.
- Reduce the size of laser bullets to be cooler. Also make the ball laser bullet hell sprite because that's based?
- Add the Laser Ballistic gun system (its a laser gun which you can rack and mess with)

## Why It's Good For The Game

Honestly, I'm making this because it felt wrong to me while playing.

It felt like Realism over Gameplay. Too many ammo types with weird names, for someone who isn't a gun nut was too much.
I felt like it was deterimental to the enjoyment of the game.

I want this to:
Improve gun gameplay
Improve gun crafting
Add a new NT themed technology that combines the cool things of Ballistics and Lasers
Add more freedom to gun coding

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Look Above for now

</details>

## Changelog
:cl: Joon Tinker
add: Gun
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
Seems interesting, though this certainly touches a lot of things, surprised you haven't touched any values damage-wise or maybe you forgot to post them (9mm laser, rubber, disabler) the general pr with the craftabled made them have decent balance damage, you seem to be standarizing the general ammo, but that's up to the maintainers if it's better for everything to have 9mm or different type of ammo since well.. they are different calibers and hence why they do diferent damage.

Also, from what i've talked and read on the past, there's that thing about having Laser weaponry being far away from the Ballistic guns, the classic example is: NT is mostly focused on Laser weaponry with the ocassional ballistic while the Syndicate is more into ballistic with almost zero laser weaponry, regardless of lore it also has some balance to take into account.

I feel like in order to have WT's laser ammo variant they should be on the same level of Shotgun shells, you need to craft them or order them(though that can be easier to do than craft since money is.. free) and if it's researched it kinda needs to be around mid to late game(since you need research and some mats), practically speaking i don't see how a traitor can benefit from having those type of ammo on the 9mm other than variety, unless you post the exact values of each type of those magazines, they can either be too busted or too weak, same with the WT.

Do you have different sound effects for Sketchin and WT shooting with those different ammo? it's important to have a clear audio cue with what you're being hit with

Hope you make a feedback thread on the discord to see what other players that don't frequent github think.

**Comment by Nakalon** [comment]
@Fronsis 

Okay so, regarding the values, Laser 9mm is 15 damage, Disabler is the same but stam.
For 9mm rubbers i just copied the previous ammo for the WT since their damage was the same as 9mm anyways on the bullet types it already had.

yes I want ammo to be less confusing.
So to reduce the amount of ammo that is used for a single gun I made a damage multiplier and speed multiplier for guns.
So guns may dictate whether or not bullets hit harder or softer.
To be honest, Ive been playing a long while and I thought this was the case already.
I didn't know the damage was based solely on the bullet fired.

Regarding crafting, I really really but REALLY want to avoid it as best I can.
At least for sec related things.
I don't want laser ammo to ever be craftable and for it to be sec only.
What I would like to do if I'm able is for the things I can't avoid not make craftable make it into assembly crafting like robots and avoid the crafting window altogether

I agree with you on the laser bullets, it should be very high tier in research, its supposed to be new technology from NT.
Oh yeah regarding lore.
The idea is not to run away from "NT makes laser weaponry" its actually to go further into it.
Laser Bullets are NT's attempt at NT'ifying ballistic weapons.
Weather it be because they want to go full laser but still have a lot of stock of ballistic weapons or whatever.

"i don't see how a traitor can benefit from having those type of ammo on the 9mm other than variety"
Thats kind of the idea. To get this ammo they'd need to break into sec and printing WT laser mags, emptying the mag, manually insert the rounds into the Stechkin mag. Its a lot of trouble, for something that's actually less deadly.
The laser ammo is there for variety and sec, especially.
Its not a secret that I hate the fact rubbers can't be used on green because they deal damage, disablers can.
Since the WT will have more fire speed i think it will bring a refreshing thing to combat.

Regarding bullets hitting.
Yes Ballistics firing lasers actually sounds awesome just because it still has the ballistic firing sound and the laser sound combined.

https://github.com/BeeStation/BeeStation-Hornet/assets/94647521/1abd323c-4cd9-467c-9072-ca55e1bb7ecb

Here is a small video for reference.

I do plan on expanding on that rubbers situation you mentioned.
I totally agree with you!

I'm avoiding making a thread about this because I've already received enough backlash just by creating the PR.

I want to avoid the idea that I'm working and wasting time on something that wont see the light of day.
Even if that's probably whats going to happen.

Cheeri-ohs

**Comment by DarnTheMarn** [comment]
I already said my piece on discord but I'll recap what I said for anyone who wasn't present at the time. 

>A lot of things were added and able to be crafted but crafting them is an absolute quest

Guns frankly shouldn't be easy to acquire, especially makeshift ones anyone can make. 

>There are too many ammo calibers.

I highly disagree, the variety of ammo calibers provides a lot of value to the game. Damages are per-caliber, whether you have a bulldog or a double barrel you know what damage you'll deal with a 12 gauge shell. This change also severely fucks with detectives and security. A ton of calibers are essentially antagonist only. If you find .357 casings, you know a traitor bought a revolver. If you find 10mm, you know there is a stetchkin around. If you find .45, you know its probably stealth ops. The changes for the stetchkin and WT to fire 9mm means that of the five commonly seen guns, WTs, shotguns, det Revolver, syndie revolver, and stetchkin, two use 9mm. That's going to make sussing out who is doing what where a hell of a lot harder for no real gain.

>Why can you make 10mm, Stechkin ammo (used only in the stechkin), in the Autolathe when the Security Overide is active?
But you can't make WT ammo?

Ammo acquisition is best suited to a PR of its own considering the parallel paths to make security ammo (lathe printing) and antagonist ammo (hacked autolathe). Stay tuned.

>Lever Action Pipe Rifle

This one is good aside from...

>It becomes a Volcanic Pipe Pistol.

Pocket sized weapons aside from the PTSD are antagonist restricted for a good reason. Any gun that can be stored in a bag is going to be amazing no matter how shit the damage/accuracy/ROF/etc is just because of the spammability and the reduced risk of being completely disarmed. Making it pocketable multiples that even more so. You could have two pipe pistols in your boot, two/three in your coat, one in your hat if applicable, and two in your pockets before you even begin to look at your backpack or suit slots.

>Multiplier Vars

The damage multiplier I outlined earlier, it goes against the intent of the PR and makes guns more opaque as a system. Speed multiplier however could have interesting applications. Less barrel length and thus increased storability and vice versa as an exchange for projectile speed is interesting, pocket sized options notwithstanding. 

>Ammo boxes with this var can now pick ammo again. This is just for Toy guns here.

If this only applies to foam darts and not riot darts, its a fine change. Foam force weapons were due for a nerf since you could easily acquire a traitor weapon as a non crewmember. Hack cargo terminal for foam force pistol crate, hack autolathe for riot darts, boom you have a ranged stun weapon. So impacting that while still allowing nerf fights is the best option.

>Pipe Pistol

Non antag pistols are just as terrible for the game as they were before. 

>WT deals the lowest. And has a MUCH HIGHER FIRE RATE (Now you can actually use it full auto instead of semi being faster)

Most full auto weapons are restricted to antagonists or heads, again for a good reason. WTs are already the undisputed king of spam with hot swappable pocketable high capacity magazines. High fire rate is a straight buff all else equal considering how laughably easy it is to print extra ammo. And that's not to mention their other benefits of being able to be worn on the belt and hold a bayonet. 

>Only got 9mm so far but here is Rubbers

This isn't a fault of this PR, but rubber bullets really do not have a place. If someone is able to be taken alive, the armory never needed to be opened in the first place. Once that genie is out of the bottle it's full lethal everywhere, and why not? The AI gets just as mad at you for shooting someone with rubber bullets as lead since both do brute damage and you already have the tools to shoot to kill.

>Laser and Disabler 9mm ammo and mags

Rest in peace laser weaponry, murdered in cold blood by power creep. Infinite ammo disablers are now possible. Ballistics were always the better choice over lasers before, and with this you'd be able to circumvent the two minor weaknesses they had since you can now shoot through glass and deal entirely non-lethal damage from range. Theoretically these could be turned into tech shells like Fronsis said, but then they'd see essentially zero use.

<hr>

To keep it simple, this PR breaks a lot of established norms regarding ballistics, whether they were intentional or not, for what gain exactly? Incredibly increasing the power of both security (laser/disabler ammo) and non-antagonists (pocket sized weapons) while "simplifying" a single aspect of ballistics. Is that good for the game at the end of the day? Not in my totally humble opinion.

**Comment by VickiMorris** [comment]
The ammo especially is something I was going back and forth on a lot when making these firearms, and I settled on each of them for (what I feel) were good enough reasons. Originally the pipe rifle *was* going to use its own bespoke ammo type (.41 cal) that was craft-able only, but it was suggested by Ruko that I avoid exacerbating the issue and use Mosin (a7.62) instead; this had the added benefit of the Mosin now having renewable (if somewhat shit) ammo rather than being tied exclusively to cargo crates. 9mm for the repeater had the right damage, and was printable via autolathe when hacked if you didn't want to craft bullets manually (which is much cheaper in the long-run, iron-wise at least).

> Laser and Disabler 9mm ammo and mags

As I stated before when we were discussing this, I think this is a bad idea, fullstop. Ballistics do not need more versatility. The Syndicate (lore/design-wise) would not develop this, and NanoTrasen is trying to move away from ballistics from what I understand.

> Multiplier Vars

I think this is interesting, but I'd probably ultimately agree with Darn's point he made above for balancing reasons. The only guns that play around with weapon velocity at all are the sniper rifle (0.2 instead of 0.8), and the hotloaded ammo I introduced for the mosin (0.6 iirc instead of 0.8). This is baring any hitscan weapons of course.

> Pipe Pistol

I know we discussed this in DMs about this PR and my own PR, but I am reiterating it here so it is public; it is not a pistol because it was meant to mirror the WT-550, not the Stechkin. Asides from its lower innate ammo capacity and mild innate spread, it is identical, down to size and fire-rate. I was originally going to make it LARGE while a magazine was not attached, but that was too much work, and you could just backpack it and then add the magazine so it would be ready to fire straight out of the bag.

> Lever Action Pipe Rifle

This is your PR, and you are ultimately free to change this how you see fit, but *I would personally prefer the pipe rifle to retain the higher damage ammo of the Mosin while having very slightly higher capacity.* I think single-shot like the improv shotgun might of made it too weak, and it would be fine as a 1+2 lever rifle rifle; even something as simple as making it a double-barreled rifle would be fine IMO. (If I was re-doing my ballistics PR, I would also entirely scrap the low damage-randomization on the improv a7.62 rounds and just give them low innate spread). If you would still prefer to drop it to .38 instead however, you are free to do so.

I agree with Darn's point that he made above though; pocketable guns should not be common, there is a reason why the Det's revolver and syndie .357 revolver can't be stored in pockets

> Ammo boxes with this var can now pick ammo again. This is just for Toy guns here.

Regular ammo boxes should be able to pick up bullets from the floor instantly, like garbage bags do (unless I fucked something else up). Ammo pickup was a change I made exclusively to magazines and I did not include an exception for non-riot foam darts because the consistency across the board felt better to me.

> This change also severely fucks with detectives and security. A ton of calibers are essentially antagonist only.

I don't think this is necessarily a bad thing, a bit of ambiguity would not hurt in terms of who is firing what. I think at the very least, It would be nice if .45 did not instantly spark the cries of "NUKIES!!" over comms just from finding a single bullet casing. This would force security to keep better track of what their officers are doing, and ultimately is a non-issue *if NanoTrasen is supposed to be using little to no ballistics anyway.*

> crafting them is an absolute quest

I think this is a gross exaggeration of what is needed to craft firearms. For almost all of them the recipe follows; modular receiver (hacked autolathe and maintenance), 1 straight atmos pipe (maintenance, RPD prints them for free and the mining outpost always has one), igniter (autolathe), package wrap (autolathe), and a wooden stock (wood from tables, maintenance barricades, asking botany, etc). Asides from the pipe and stock, everything is available at an autolathe (including the screwdriver and welder needed for assembly). If you are batch crafting them, it's a different story, but it's unlikely that you need more than 3-4 firearms unless you are assembling an entire militia (and if you have that power, you are likely station-aligned and can just get guns ordered).

For ammo as well, I see complaints about it being too much to craft it in bulk for use, when the recipe for most of them is; chem grenade casing (1 sheet of iron, can be crafted in-hand), sheet of iron, cable coil, and welding fuel. The only notable exceptions are 9mm & 10mm (requires a sheet of paper, which gets returned when you empty the ammo pouch), Hotload a7.62 and .357 (blackpower instead of welding fuel), and glasspack (glass instead of iron, obviously). Yes, it is slightly more work than clicking a single button on an autolathe, it is not a quest to gather everything though. Asides from specialty or *very strong* ammo, you can throw them together with the starting supplies in tool storage on literally every station.

---

There are some ideas I enjoy but quite a few that I think are unhealthy for the game as a whole (even if I will no longer be playing it). I know we discussed a lot more than this, but I wanted to give my ultimate thoughts on this that could be picked apart by other people as well. Ultimately, I wanted to stray more towards realism for the guns and tweaks that I made in my previous PRs (and wanted to do *alot* more in terms of realism because I hate fun and should probably pick up Receiver some time soon).

**Comment by Fronsis** [comment]
Maybe it's an issue related to the crafting system itself, that i can agree with but i personally, don't mind it, there are things that are time consuming on purpose, it has to do with balance and to not affect the flow of the game negatively, we certainly don't want people speedrunning gun crafting when the officer has barely grabbed his sechud, i believe any criticism to the crafting menu should be made on something like discord on the ideas channel to get a good discussion going, perhaps you're part of the majority or perhaps you're one of the few haters, hard to know without doing a poll, personally i like how it works on Robotics:

You have two paths:

1. Dump everything on the floor, go to crafting menu and assemble a medibot with one click

2.You put piece by piece and you can see how that interacts with the game, if i put the arm on the medkit, the medkit gets the arm, and it give me that satisfaction of ''cool i can craft this manually and it's neat to see how it ''evolves'' in steps, until you get the final product

Sadly not all crafting items work like that due to their different nature, i believe weapons should work similar to this, you can either do it through menu crafting (faster) or if you enjoy the slow assembly you can do it as well.

I don't think we're dissaproving your ideas like ''Nah honestly don't bother this won't be merged at all you don't know what's good for the game'' at least i don't come with that intention! I certainly very appreciate the idea behind the PR and i believe that even if i have some doubts regarding general balance we can slowly reach a point where it'll be in a nice spot, personally i'm curious about what the more experienced maintainers will think about this, i believe Ruko and Bacon are the ones that touched values of damage and armor the most and have a general sense of direction about where should we move forward regarding guns and combat

This PR presents a lot of interesting ideas and they're worth discussing to see what we can implement, what we can improve or tweak and i appreciate you taking the time to try to make a more enjoyable game(though that depends heavily on different aspects but i get the point)

**Comment by DarnTheMarn** [comment]
>While I understand this and I see where you're coming from I would like to avoid the crafting window as much as possible.
>From what I remember, to make use of the gun I had to. (Without mentioning getting the materials)
>Craft a rifle butt in the wood crafting menu, Hack a lathe, steal a station pipe (if I don't want to fuck up piping I need to steal a >Pipe Dispenser from engi). Now, I have to get a liquid container, fill it with welding fuel, go to the iron crafting menu, craft a >grenade casing, craft an unfinished chemical grenade by attaching wire to it then I can craft exactly ONE bullet.

You make it sound way worse than it actually is. If you prepare items in bulk, you avoid the tedium. Fill up one or two large beakers with welder fuel, get a couple of cable coils, spam grenade casings, boom. How many bullets do you actually need? If this is a problem you actually want to solve, I think adding boxes of improvised ammo to the crafting menu is a far better option than this.

>I haven't met one player that said "yeah I use the crafting menu all the time" they don't.

Chef players in shambles right now.

>A lot of what I'm doing is framework.

Maybe there are plans to turn this into an awesome framework. But you haven't justified why you are breaking all these norms now. They are there for a reason. Just saying you'll do something in the future is not a good reason. 

>If anything this may actually push for Security to be full laser weapon. Maybe the laser bullets are ONLY available to sec, and they're the ONLY thing available for ballistics there.

A ballistic that fires lasers is still a ballistic, not laser weaponry. They completely sidestep all of the downsides of energy weapons and ballistics just to get the best of both. If that isn't an insane power boost what is. 

>I may make an energy gun that ejects bullet casings while still being solely and energy gun.

If you really want a ballistics energy gun hybrid, why not a rifle sized railgun? It could require energy to fire, but takes magazines of a metal projectile. It could have some of the strengths and weaknesses of both, it could be vulnerable to EMP like lasers and require clunky loading like a ballistic, while also being able to shoot a bit more than a laser or something like that.

**Comment by Nakalon** [comment]
> Maybe there are plans to turn this into an awesome framework. But you haven't justified why you are breaking all these norms now. They are there for a reason. Just saying you'll do something in the future is not a good reason.

Honenstly, I don't believe I need to justify myself to you on a draft PR.
It's a work in progress, nothing here is final.

> If you really want a ballistics energy gun hybrid, why not a rifle sized railgun? It could require energy to fire, but takes magazines of a metal projectile. It could have some of the strengths and weaknesses of both, it could be vulnerable to EMP like lasers and require clunky loading like a ballistic, while also being able to shoot a bit more than a laser or something like that.

You just described exactly what I was saying but with the added thing that it uses ammo on top of using energy.
I don't exactly want a energy ballistic hybrid, however, I want to bridge the gap and give lasers the possibilities that ballistic code provides.
I want a laser gun able to spew out casings.
Or that you need to pump for whatever reason.

The values or whatever, the gun remains exactly the same, but now it has very specific things that change how the player interacts with the gun, making it closer to ballistic feel wise, because people love ballistic but think lasers are boring.

@Fronsis 
> Sadly not all crafting items work like that due to their different nature, i believe weapons should work similar to this, you can either do it through menu crafting (faster) or if you enjoy the slow assembly you can do it as well.

That sort of crafting is EXACTLY what I want to do.
I would like that for be the case with everything here.
One of my problems with the crafting as it is now is that I have to gather all the resources, transport them into one place, and when things like pipes are involved it becomes a but burdensome easily.

Having an assembly that people can work on as they go would be a great change in my view.
Also, maybe its just me, but i cant remember for shit what weapons need. Specially since the 3 weapons use slightly different things here and there, like the SMG needing planks instead of a rifle butt and iron rods.
How I'd change this?
Lets imagine the Modular Reciever, you use it to open one of those resource crafting windows where you select the gun, so you get an assembly, all guns using the same exact resources, the same exact steps. That would be much more engaging that just gathering item, sit on them and watch a bar fill up.

**Comment by DarnTheMarn** [comment]
>Honestly, I don't believe I need to justify myself to you on a draft PR.>It's a work in progress, nothing here is final

It being a draft pr means it's the best time to ask questions and give opinions, before you spend too much time working on something that'll get thrown out. And you don't have to justify yourself to me, just the maintainers. And I imagine they would be a lot more willing to let you break out and do your own thing if you say hey, I am adding X so in the future I can do Y for Z reasons.
>You just described exactly what I was saying but with the added thing that it uses ammo on top of using energy.

Maybe I wasn't clear enough for my point to get across. A rail gun as I imagined it would not just be a ballistic that shoots lasers like yours would. It would have two types of ammo, external magazines like a ballistic and an internal battery like an egun. Without both, no pew pew. This means you could make it balanced infinitely easier than adding disabler and lethal laser magazines to a WT. If the tailgun has too many shots? Make the magazines rare so you get 2 max, or reduce the internal battery so you cant shoot as much before recharging. You can't do the same adjusting when you add laser features to a WT. Can't make magazines rare without affecting normal ammo, if you make the rounds rare like tech shells they don't get used.

>That sort of crafting is EXACTLY what I want to do.
>I would like that for be the case with everything here.

Unless you want to rewrite or create a whole lot of code that's probably not going to happen in a non janky way. All the makeshift guns use the same parts, so you'd have to do something like activating the modular receiver in your hand opens up a menu to select what receiver you want to make, then slap on the wood, tape, pipe. But that just sounds an awful lot like a crafting menu doesn't it. It also exacerbates the problem you had with crafting to begin with, some things are done in hand, some things are down by touching parts to other parts, some things are done by crafting menu. 

One thing I forgot to mention is that for ammo simplification, it makes balancing things significantly harder since a lot more guns use the same cartridge. Some things like incendiaries that apply fire stacks would be far stronger on a high ROF weapon like the new WT for example.

I am not trying to be mean here, but if you just ignore the many valid grievances people have you're setting yourself up for disappointment.

**Comment by Nakalon** [comment]
@DarnTheMarn 
What I'm trying to do right now is apply these bullets to try and make laserguns more engaging by making them inherit functions from ballistics.

This is a very early WIP and I still haven't managed to do it.

https://github.com/BeeStation/BeeStation-Hornet/assets/94647521/1e91a99c-7a81-4103-9214-ac4afba3e1a8

If i get this working this will allow me to do two things.
One, introduce bolt types to the energy guns, which makes it easier to add different mechanics for energy weapons.
Two, allows me to make cells that change what the gun shoots.

Don't mind the small bullets I'm still testing that. I'm trying to make these ball bullets for high rate of fire laser weapons.

> Some things like incendiaries that apply fire stacks would be far stronger on a high ROF weapon like the new WT for example.

so this just means i should give up messing with RoF and everything should just be the same?

Or do I just remove incendiaries?!

Or do I need to find some convoluted way to make incendiary stacks somehow linked to rate of fire?

Idk, I know you guys think a lot of things should be realistic or should be kept as they are, but I feel like if I don't think a bit outside the box i wont make anything fun or interesting.

I don't know how to solve that incendiary problem, but I also want to see higher rates of fire on the game because its one more thing to mess with to make guns more distinct from one another.

**Comment by DarnTheMarn** [comment]
>so this just means i should give up messing with RoF and everything should just be the same?
>Or do I just remove incendiaries?!
>Or do I need to find some convoluted way to make incendiary stacks somehow linked to rate of fire?

Option D, don't standardize cartridges and you don't have to worry about any of it.

As for the video you posted, when energy weapons were brought up before in ideasguy the general gist people had was that energy weapons already have enough energy for each encounter, so you shouldn't be able to just spam it and activate it in hand or swap out a battery and be back at full charge, but something like overheating or passive charging would be more applicable since it reduces tedium without increasing its power. If you haven't already you should look at those old threads on discord, a lot of good discussion happened in them. Be forewarned though there are a LOT of posts to go through. 

The ideasguy threads are:
explorer gun "nerf"
ballistics weapon discussion
ballistic weapon discussion - laser buff proposal

**Comment by Nakalon** [comment]
> > so this just means i should give up messing with RoF and everything should just be the same?
> > Or do I just remove incendiaries?!
> > Or do I need to find some convoluted way to make incendiary stacks somehow linked to rate of fire?
> 
> Option D, don't standardize cartridges and you don't have to worry about any of it.
> 
> As for the video you posted, when energy weapons were brought up before in ideasguy the general gist people had was that energy weapons already have enough energy for each encounter, so you shouldn't be able to just spam it and activate it in hand or swap out a battery and be back at full charge, but something like overheating or passive charging would be more applicable since it reduces tedium without increasing its power. If you haven't already you should look at those old threads on discord, a lot of good discussion happened in them. Be forewarned though there are a LOT of posts to go through.
> 
> The ideasguy threads are: explorer gun "nerf" ballistics weapon discussion ballistic weapon discussion - laser buff proposal

Yeah I was a part in some of those.
Yes this is mean to be a gun with internal magazine, which means you cant take the mag out.
The reason I'm trying to make it inherit ballistic functions is that I may add things like overeating. Or something like rukos energy lever action.

**Comment by DarnTheMarn** [comment]
>Yes this is mean to be a gun with internal magazine, which means you cant take the mag out.

So its kind of hacky where instead of making stuff from scratch you make a subtype of ballistics and slap an energy overlay on it? That way you can easily hook into things like overheating by reloading the "magazine" or something. Kinda funky and will look confusing when a new person looks at the code but hey if it works it works.

**Comment by Nakalon** [comment]
> > Yes this is mean to be a gun with internal magazine, which means you cant take the mag out.
> 
> So its kind of hacky where instead of making stuff from scratch you make a subtype of ballistics and slap an energy overlay on it? That way you can easily hook into things like overheating by reloading the "magazine" or something. Kinda funky and will look confusing when a new person looks at the code but hey if it works it works.

yeah, gun code is confusing and there's already a similar gun, the one you use in capture the flag, it has a rechargeable mag and shoots lasers.

I'm using that as a template.

**Comment by Nakalon** [comment]
I just realized what a fucking mess I made putting things with other things on top of other things in the same PR.

The things that are usable here I will probably PR them alone.

**Comment by Nakalon** [comment]
Consider this PR as closed. I'm only going to see what I can salvage from this now.

**Pull request closed without merging**
