### PR TITLE
adds a few chems to the abductor chem dispenser

### PR DESCRIPTION
**Pull request by ghost**
their dispenser didn't have carpotoxin, which seemed to be an oversight, as it haad all the other emagged chem dispenser chems

now it has them and a few others-rezadone, for fixing people shot by their decloner gun, and a few rare organ healing chems because...eh, why not tbh.

:cl:
balance: the abductor chem dispenser now has a few extra chems in it
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
hi adam

**Comment by Krysonism** [comment]
If I was more conspiratorial I would say this PR is a thinly veiled attempt at allow the abductors to do the zombification surgery consistently.

**Comment by ghost** [comment]
@Krysonism 

It is absolutely one, given it's under 'alien surgeries.' It should be possible to do so. If admins will -allow- them to is a different story, but I see potential in creating a brainwashed zombie told not to infect people, et cetera.

You shouldn't get a zombie outbreak every round, but if the -possibility- to make a zombie is there, it shouldn't just be left as bait, should it?

**Comment by Krysonism** [comment]
Sure, I am not very familiar with the beestation rules.

I actually like zombie outbreaks a lot, I just think who ever decides if this is merged should be aware this enables easier access to necrotic revival.

**Comment by zeskorion** [comment]
...i remember this round, i was the other abductor. Abductors not being able to get zombification easily is intentional and should remain that way

**Comment by MCterra10** [comment]
most badly broken changelog I've seen to date

**Pull request merged**
