### PR TITLE
BBs start with some non-incriminating station bounceds

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Adds radios on a predefined frequency to blood brothers when they generate.

## Why It's Good For The Game

Makes BBs better.

## Changelog
:cl:
add: roundstart radios to BBs
/:cl:

### CODE REVIEW

**Comment by Flakkyboo** [comment]
Right but don't bloodbrothers have a predefined meeting spot at the start of the game when given their directives

**Comment by bloons3** [comment]
BBs already have a roundstart meeting location, and can use their PDAs.

**Comment by eeSPee** [comment]
> can use their PDAs.

That's instakill cause as soon as sec finds out you're BB, they will validhunt anyone who sent a PDA.

**Comment by Flakkyboo** [comment]
> 
> 
> > can use their PDAs.
> 
> That's instakill cause as soon as sec finds out you're BB, they will validhunt anyone who sent a PDA.

well validhunting is against the rules so

**Comment by bloons3** [comment]
> > can use their PDAs.
> 
> That's instakill cause as soon as sec finds out you're BB, they will validhunt anyone who sent a PDA.

Clear your messages. Don't send incriminating stuff in your PDA messages.

**Comment by PowerfulBacon** [comment]
It should be the job of smart blood brothers to do this themselves if they want comms, and having a station bounced radio will be pretty incriminating but be hard to administrate since sec will obviously know they are blood brothers, but if they use the information would it be considered meta?
I am in favour of https://github.com/BeeStation/BeeStation-Hornet/pull/3023
Also this adds an upper limit on the number of blood brothers

**Comment by eeSPee** [comment]
> It should be the job of smart blood brothers to do this themselves if they want comms, and having a station bounced radio will be pretty incriminating but be hard to administrate since sec will obviously know they are blood brothers, but if they use the information would it be considered meta?
> I am in favour of #3023
> Also this adds an upper limit on the number of blood brothers

There's already a limit of BBs defined by the max number of meeting places, though. I see your point.

**Pull request closed without merging**
