### PR TITLE
Nullcrate rework aka lucky nullcrates 2 (ready and tested)

### PR DESCRIPTION
**Pull request by LordSaladin**
About The Pull Request
This pr adds a super rare chance for nullcates to contain stands(of both kinds) or some role restricted items.
Will you hit the jackpot?
**_disclaimer: you're still more likely to get griefskyed or get trolled by all the other items.Seriously a lot of items don't have any surplus/surplus_nullcrates values so will spawn randomly unless they are game mode restricted or over 30tc_**

Why It's Good For The Game
This pr would give an incentive for traitors/Cargo/anyone with AA to waste all their tc on cash briefcases or make the station broke,i've also increased the rate that beer smokes and cards should appear in surplus and nullcrates to compensate.

Changelog
:cl:
add: Added a 10% chance for stands to spawn in null crates( just like the good old days).
tweak: certain restricted items( banana pie cannon, cult kit and clowncar(honk honk!)) now have a 10% chance to be in null crates since they can be discounted as any role, nullcrates now have 10% chance of partially refunding their purchase via cash briefcases.
tweak: explosive hot potato now has a 40% chance of being in surplus/null crates( you can get c4/x4 bags and rubber ducks which are better anyway).
balance: makes all of the pointless badassery items more likely to spawn in surplus and null crates(excluding balloons and cash briefcases).
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Even more cargo powergame, me no like

**Comment by LordSaladin** [comment]
> Even more cargo powergame, me no like

Did you read the disclaimer? If not I suggest that you could go play tg since they do have no null crates or test ordering a shit ton of nullcrates in a private server to be greeted by several griefskys seeing that the chance you'll get them increases per crate(like I did to test this pr) and you would need an near unobtainable amount of credits for an average round's length (I salute anyone who legitimately manages to order 15+ nulls especially without collaborating with other traitors or the round going to shit)

**Comment by Crossedfall** [comment]
> 
> 
> > Even more cargo powergame, me no like
> 
> Did you read the disclaimer? If not I suggest that you could go play tg since they do have no null crates or test ordering a shit ton of nullcrates in a private server to be greeted by several griefskys seeing that the chance you'll get them increases per crate(like I did to test this pr) and you would need an near unobtainable amount of credits for an average round's length (I salute anyone who legitimately manages to order 15+ nulls especially without collaborating with other traitors or the round going to shit)

You realize that you're talking to a maintainer, right? Like, one of the people responsible for merging this code.

**Comment by LordSaladin** [comment]
> > 
> > 
> > > Even more cargo powergame, me no like
> > 
> > Did you read the disclaimer? If not I suggest that you could go play tg since they do have no null crates or test ordering a shit ton of nullcrates in a private server to be greeted by several griefskys seeing that the chance you'll get them increases per crate(like I did to test this pr) and you would need an near unobtainable amount of credits for an average round's length (I salute anyone who legitimately manages to order 15+ nulls especially without collaborating with other traitors or the round going to shit)
> 
> You realize that you're talking to a maintainer, right? Like, one of the people responsible for merging this code. 

So my pr was dead from the start then.
And I'm just better of removing null crates

**Comment by LordSaladin** [comment]
Or raising their price

**Comment by PowerfulBacon** [comment]
I like nullcrates and dont want them removed, it's just the in their current position I really dont think they need to be buffed, since having members of the crew get access to traitor items alone is insanely powerful let alone holoparasites

**Comment by LordSaladin** [comment]
> I like nullcrates and dont want them removed, it's just the in their current position I really dont think they need to be buffed, since having members of the crew get access to traitor items alone is insanely powerful let alone holoparasites

Oooooh so non of the maintainers are like oranges, feel free to make them more expensive since it would reduce their availability without just being the Ree delete meme that TGS went for.

**Comment by optimumtact** [comment]
bahahaha

**Comment by Mick1299** [comment]
Money isn't a good limiting factor, there are dozens of ways to easily make hundreds of thousands of credits in a round. Griefsky is also easily bypassed with tk and xray. Honestly, even the increased chance of lone ops isn't that worrying, with a moving disk dissipating that risk.

**Comment by bloons3** [comment]
> Money isn't a good limiting factor, there are dozens of ways to easily make hundreds of thousands of credits in a round. Griefsky is also easily bypassed with tk and xray. Honestly, even the increased chance of lone ops isn't that worrying, with a moving disk dissipating that risk.

The current meta is to use the EMP flashlight (since it is a cheap item and you get many of it early on) to fight off Griefsky, then continue looting with ease.

**Comment by PowerfulBacon** [comment]
Going to go ahead and close this PR due to the fact that I don't think its a good idea to make null crates even more overpowered than they already are. They are a good item, and one of the best items for a traitor or non-traitor, and adding holoparasites only serves to make them stronger, which isn't what they need.

**Pull request closed without merging**
