### PR TITLE
Boxstation Medbay 2: Electric Boogaloo

### PR DESCRIPTION
**Pull request by 4rchibald**
## About The Pull Request

Changed medbay on Boxstation according to what was said in comments under #2475 and #2172
Additionaly fixed few issues with box wiring, pipes and mining airlock that was releasing gases from waste pipe every time it was used, causing quite few fires.

med1

med2

## Why It's Good For The Game

I hope for better workflow around medical, people had a habit of stockpiling all bodies around the entrance section of medbay and that's where all action was actually happening.
Other than that some pipes are now actually connected to rest of station, cleaned a lot of wire mess left in maints after APCs were moved inside the rooms, also section around arrivals is not dependent only on one wire

## Changelog
:cl:
tweak: Boxstation medbay received another remoddeling
tweak: Janitor closet and auxiliary tool storage were moved back to their old locations
add: Engineering now has shower
tweak: Cleaned wires around Boxstation
fix: Mining dock airlock on Box is set up correctly,  no more plasma fires
/:cl:

### CODE REVIEW

**Comment by VictorVow** [comment]
Why are the tables in plumbing in the centre of the room? Move them to the sides.

**Comment by St0rmC4st3r** [comment]
> Why are the tables in plumbing in the centre of the room? Move them to the sides.

People complained about a "giant empty room".

**Comment by St0rmC4st3r** [comment]
@4rchibald I generally like the changes, except this one detail.
image
I really don't like additional doors being there for people to enter all the time.

As for mining airlock changes - atomize the PR, please. It is a bad tone to make different unrelated changes in a single PR unless it's an overhaul.

**Comment by 4rchibald** [comment]
@Victor239 
I actually haven't touch plumbing area. People here and in-game playing actual chemists seemed to be fine with it. When medbay was first being reworked I was actually a fan of putting that wall separator like its often done in atmos but I guess tables are a nice solution as well, easier to remove, just one click with wrench and there's at least something in the room, its still a big empty rooms but having something in middle breaks that feeling a little bit.

@St0rmC4st3r 
I'm aware that you weren't a fan of that airlock, I was on edge about it myself. My hope was that it will be used to make leaving the medbay area easier but maybe its too convenient, guess we'll see it once it gets merged. I get your idea of having entrance treatment room for quickly dealing with minor wounds but to get that working we need to get both proper room layout and proper flow of people. Its kinda hard to do anything when people are just coming in and out, constantly bumping into each other, pushing people you are trying to work with etc Not to mention all the other mess we were experiencing with patients being piled up with bodies both with soul and without and catatonic people. I was hoping that we can achieve what you intended by luring people inside the department again, following the path deeper the more severe their condition is, ending with both cloning and morgue. If the airlock won't do its job and will be used as main entrance we can easily remove it in future or maybe think about some solution to make it less convenient to use 

Well, no matter how things will work I'm at least glad that through process of evolution we got that chemlab, plumbing room and med storage combined, people already like plumbing room and I believe it will all work great with storage. Instead of going to storage to check if meds are there, then going to chemlab to see if they are in fridge and once they are not go look for chemist that is not in lab because he's setting up plumbing somewhere you got it all in one place. That should really work great for chemistry-medical cooperation. Pretty sure we just established new standard how those 3 rooms should be placed on future maps

**Comment by zeskorion** [comment]
conflicts

**Comment by 4rchibald** [comment]
@zeskorion Are we able to pinpoint what's the issue? Having information that the conflicting file is the only file in this PR is not really saying much

**Comment by zeskorion** [comment]
> @zeskorion Are we able to pinpoint what's the issue? Having information that the conflicting file is the only file in this PR is not really saying much

if you're using a proper setup you should be able to fix it quite easily

**Comment by PowerfulBacon** [comment]
Ping me when merge conflict resolved for review (before it gets conflicted again)

**Pull request closed without merging**
