### PR TITLE
Dying now connects you to YogStation

### PR DESCRIPTION
**Pull request by qwertyquerty**
Where you can play with fellow unrobust players

### CODE REVIEW

**Review by skull132 — CHANGES_REQUESTED** [review]
\> Not using `link_to` or whatever the macro is

1/4 please try again.

**Comment by qwertyquerty** [comment]
@skull132 there is no such macro, try again

**Comment by skull132** [comment]
How does this codebase even survive.

**Review by alexkar598 — APPROVED** [review]
I approve of this PR as yogs headcoder, we need more people that die for high rp plz

**Comment by francinum** [comment]
Spite

**Comment by Jumps0** [comment]
legendary PR

**Comment by Hopekz** [comment]
Okay, let's make an agreement between codebases. We'll merge our dab PR and you'll merge this death PR

**Review by PowerfulBacon — APPROVED** [review]
yoggers

**Comment by Mqiib** [comment]
As a resident robust shitlord on yog I don't approve of this PR. Please keep your unrobust lads to yourself, we have enough people asking how to unbuckle as is.

**Comment by Cenrus** [comment]
Merge immediately

**Review by Hopekz — APPROVED** [review]
This PR is throwing people in a loop where they can enjoy both servers.

First, they'll die to get sent to Yogs then with yogstation13/Yogstation#8333 they will get sent back because they cannot stop dabbing.

**Comment by qwertyquerty** [comment]
@ike709 we ready for testmerge?

**Review by ZeWaka — APPROVED** [review]

**Comment by TheNeoGamer42** [comment]
This is the greatest thing to happen to beestation, I approve.

**Comment by patpol4** [comment]
speedmerge

**Comment by Moja10** [comment]
Do you hear the people sing?

**Review by alexkar598 — CHANGES_REQUESTED** [review]
We have 25 upvotes, you have 10 
beetards

**Comment by ToGWtF** [comment]
*dab *dab

**Comment by monster860** [comment]
Can confirm, am unrobust

**Comment by Takahiru** [comment]
yes

**Comment by Marmio64** [comment]
i consider myself robust

**Comment by PowerfulBacon** [comment]
Time to join Yog, become robust, get selected to battle.
**A RED SPY IS IN THE BASE**

**Comment by ynot01** [comment]
oh no

**Pull request merged**
