### PR TITLE
Safety Moth(TM) Posters from your friends at Nanotrasen! [Spritework Edition]

### PR DESCRIPTION
**Pull request by AyyRobotics**
## About The Pull Request

Adds _sprited_ Safety Moth posters into the game.

Themoffs
Themoffs2
Thanks to Azlan for giving advice with the sprites and updating the first poster!

## Why it's Good For The Game
1. More Posters _that actually look decent_
2. _Safety Moth_

## Changelog
:cl:
add: Added Safety Moth Posters
imageadd: added _and updated_ the poster images
imagedel: deleted the old image file so it could be replaced with the above
/:cl:
I noticed some of the labels aren't accurate. I'd personally remove "Refactor", "Code Improvement", and "Removal" since I didn't do any of those unless you count removing the old contraband.dmi to replace it with the new one

### CODE REVIEW

**Comment by AyyRobotics** [comment]
Don't know if I have to get original artist permission for these sprites, so if someone could tell me that'd be good.

**Comment by ghost** [comment]
> 
> 
> Don't know if I have to get original artist permission for these sprites, so if someone could tell me that'd be good.

probably should do it either way just to be safe.

**Comment by AyyRobotics** [comment]
> Don't know if I have to get original artist permission for these sprites, so if someone could tell me that'd be good.
> 
> probably should do it either way just to be safe.

Gotcha, I sent the artist a note on deviantart yesterday, so lets hope they respond to that

**Comment by Bastian0930** [comment]
the artist really should do one about a cult
that'd be fuckin hilarious.

**Comment by qwertyquerty** [comment]
If you made these sprites yourself, you should be fine

**Review by qwertyquerty — APPROVED** [review]

**Comment by AyyRobotics** [comment]
> If you made these sprites yourself, you should be fine

Sweet, didn't want to get in any copyright trouble

**Comment by AyyRobotics** [comment]
Yeah, couldn't add new files to a closed PR so I made this new one

**Comment by Crossedfall** [comment]
Not legally kosher. Will re-open while we properly await the artist's OK

**Pull request merged**
