### PR TITLE
Hunts the elusive fland hallway lightswitch to extinction

### PR DESCRIPTION
**Pull request by Tsar-Salat**
## About The Pull Request

image

Kills it ^^^^^^^^^^^^^^

## Why It's Good For The Game

It's been like 8 months pigeon

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl: contributors
del: removes a lightswitch on fland
/:cl:

### CODE REVIEW

**Comment by BriggsIDP** [comment]
😭

**Comment by ClownMoff** [comment]
👎

**Comment by MarkusLarsson421** [comment]
👎

Jokes aside, this is a good change, kill it.

**Comment by DrDuckedGoose** [comment]
Life for lightswitch boy!

**Comment by PestoVerde322** [comment]
Ok, I'll allow the merge on either of those two conditions, you either:

- Make the lightswitch a dumb button, that absoluteley does nothing to prevent potential cheesing.
- Replace it with a plaque, saying how great that lightswitch was.

Flat out removal seems to be a bit eh at this point due to it's cultural impact.

**Comment by Rukofamicom** [comment]
I'm on the meme side for this one

Long live the light switch :key:

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Remove the decals too and then this can be merged. Idk why decals got added in the first place instead of this just being removed.

**Review by itsmeow — APPROVED** [review]
oops

**Comment by Tsar-Salat** [comment]
> Remove the decals too and then this can be merged

the fun has been slain, milord.

image

**Review by Rukofamicom — DISMISSED** [review]
:trollface:

**Comment by MarkusLarsson421** [comment]
Would it be satisfying for the pro-light switch people to add a light switch item in the showroom? As a memeory to the hallway light switch.

**Review by PowerfulBacon — APPROVED** [review]

**Review by PestoVerde322 — APPROVED** [review]
Aside memeability, I think this's an overdue change...

**Pull request merged**
