### PR TITLE
nerfs stamina damage on armor, buffs on everything else

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
stamina damage is now affected far more by armor (1.5 times on projectiles, doubly for stunbatons, borgbatons, and telebatons)
most stamina damage values increased across the board (rubbershot now nets more damage than normal shot on unarmored, rejoice!)
stunbaton now uses melee armor

## Why It's Good For The Game
stunbatons and such are the best weapons in the game net-damage wise. Shotguns overly encourage lethal gameplay. This makes stunbatons and nonlethals less effective on armored (and therefore combat-ready) targets, but also increases their effectiveness on the greytide

## Changelog
:cl:
balance: rubbershot now brings down an unarmored perp quicker than buckshot
balance: stunbatons, telebatons, and borg arms now use double armor values when calculating their damage, but net more damage
balance: projectiles dealing stamina damage are now 50% more affected by armor
/:cl:

### CODE REVIEW

**Comment by RafRoq** [comment]
Multiple security nerfs, I think this PR will make cult unbalanced because they have access to armor themselves, security on bee is always understaffed sounds unnecessary I don't know what this PR is really trying to solve

**Comment by zeskorion** [comment]
> Multiple security nerfs, I think this PR will make cult unbalanced because they have access to armor themselves, security on bee is always understaffed sounds unnecessary I don't know what this PR is really trying to solve

the use of stunbaton as a dedicated melee weapon over being a stick to put a tider on the floor. Stop trying to stunbaton nukies and other loud antags

**Comment by VictorVow** [comment]
Hugeeeee miner buff, they have multiple armours with 60+ melee armour which is effectively 120(!!!) with this change. As if they weren't overpowered enough already.

**Comment by zeskorion** [comment]
> Hugeeeee miner buff, they have multiple armours with 60+ melee armour which is effectively 120(!!!) with this change. As if they weren't overpowered enough already.

Don't stunbaton them, then. They're not the kinda targets you should bring the batons out for to begin wjth

**Comment by ghost** [comment]
zesko unironically hates security.

**Comment by ghost** [comment]
> > Hugeeeee miner buff, they have multiple armours with 60+ melee armour which is effectively 120(!!!) with this change. As if they weren't overpowered enough already.
> 
> Don't stunbaton them, then. They're not the kinda targets you should bring the batons out for to begin wjth

explain why they arent?

**Comment by zeskorion** [comment]
> > > Hugeeeee miner buff, they have multiple armours with 60+ melee armour which is effectively 120(!!!) with this change. As if they weren't overpowered enough already.
> > 
> > 
> > Don't stunbaton them, then. They're not the kinda targets you should bring the batons out for to begin wjth
> 
> explain why they arent?
IMO well-armed targets should be excempt from stupidly powerful stun weapons

**Comment by eLeCtrOssSnake** [comment]
Can this shit be closed because it got literally 6 down votes?

**Comment by eLeCtrOssSnake** [comment]
why is this open?

**Comment by ghost** [comment]
> Can this shit be closed because it got literally 6 down votes?

sorry but this isn't reddit.

**Comment by PowerfulBacon** [comment]
Wouldn't 60 (*2) armour heal them if they get hit with a stun baton?

**Comment by PowerfulBacon** [comment]
This isn't really a good change, if you are going to do something like this add a stun armour value so it can be manually set individually, and different armour that would make sense to reduce the stun can

**Pull request closed without merging**
