### PR TITLE
Synthflesh balance

### PR DESCRIPTION
**Pull request by Sinmero**
## About The Pull Request

Currently synthflesh is the strongest healing medecine in the game. You can bathe and shower yourself in synthflesh to heal huge amounts of damage instantly with no drawbacks and medbay has all the tools to build factories and produce gallons of synthflesh infinitely roundstart!
Basically synthflesh factories make the rest of the medbay obsolete since people can come and just spill synthflesh all over themselves and move along leaving most of medbay personnel uselles.
Since splashing yourself with synthflesh is instant it is possible to outheal tons of damage in combat.

Synthflesh will heal less the more you have it in your bloodstream with 0 healing at 100u in bloodstream making it possible to heal 63 brute and 63 burn splashing yourself with bottles with no drawbacks.
Splashing synthflesh will heal you 1 damage per one volume as it was supposed to considering its description.
description = "Has a 100% chance of instantly healing brute and burn damage. One unit of the chemical will heal one point of damage. Touch application only."
Synthflesh patches will heal you 1.25 per volume (same as it is now) to encourage people use them instead of splashing.
Synthflesh has od threshold at 100u now. Od will deal very minor tox damage.
Od will NOT prevent unhusking people.
Splashing people with Synthflesh/Silver Sulfadiazine/Styptic Powder will add the splash volume to their bloodstream now.
If you got synthflesh od and continue to use it you will be fat.

Synthflesh is still a very powerful medecine that can heal a large amout of damage instantly.
You cant pour gallons of synthflesh on yourself to outheal all the brute/burn damage anymore.
Other healing reagents might see some use along with synthflesh.

## Why It's Good For The Game

Synthflesh is not ridiculously overpowered anymore.
Medbay reagents are more balanced.

## Changelog
:cl:
balance: Synthflesh heals less depending on the amount of it in your bloodstream
balance: Synthflesh has od threshold at 100u
balance: Splashing people with Synthflesh/Silver Sulfadiazine/Styptic Powder will add the splash volume to bloodstream
/:cl:

### CODE REVIEW

**Comment by eeSPee** [comment]
Problem: You can no longer heal bodies with severe trauma using reagents. Other reagents do not tick on dead people, so they do not heal people when dead. Not necessarily a bad thing, but will definitely change the meta.

I suggest having synthflesh deal damage (flesh literally falls of) when ODed, depending on the amount you have inside (130u deals less damage than 160u), so that you can fullheal a body with synthflesh, resuscitate it, and then sustain it with other chemicals.

It's a good idea IMO, this is just something to consider.

**Comment by Sinmero** [comment]
> Problem: You can no longer heal bodies with severe trauma using reagents. Other reagents do not tick on dead people, so they do not heal people when dead. Not necessarily a bad thing, but will definitely change the meta.
> 
> I suggest having synthflesh deal damage (flesh literally falls of) when ODed, depending on the amount you have inside (130u deals less damage than 160u), so that you can fullheal a body with synthflesh, resuscitate it, and then sustain it with other chemicals.
> 
> It's a good idea IMO, this is just something to consider.

Reduced healing reduction for husks x4. Should be able to heal and unhusk them properly now but they will take damage if total volume in bloodstream is above 400. It is also possible to treat them via surgery. (And i believe it is encouraged to do so)

**Comment by yyzsong** [comment]
why have there been so many "nerf synthflesh" prs in the last few weeks
are you all alts of the same guy????

**Comment by zeskorion** [comment]
> why have there been so many "nerf synthflesh" prs in the last few weeks
> are you all alts of the same guy????

No its literally the same guy, samw account

**Comment by zeskorion** [comment]
What's with the styptic powder and silver sulf changes?

I recommend two things:

Make viro recipes not multiply reagents
Make too much synthflesh in excess of what is necessary make you fat

**Comment by r1ks-iwnl** [comment]
Well he made 2 prs on this and i made one too, this a lot more changes than my pr tho.

**Comment by Sinmero** [comment]
> What's with the styptic powder and silver sulf changes?

Currently you can splash yourself and heal with Silver Sulfadiazine/Styptic Powder infinitely with no drawbacks. 
Adding reac_volume on splash to bloodstream will prevent that and will allow to heal from reagent metabolizing if used in moderate amounts.

> Make viro recipes not multiply reagents

Viro recipes?

> Make too much synthflesh in excess of what is necessary make you fat

Done. Now if you got synthflesh od and continue to use it you will be fat.

**Comment by Isy232** [comment]
Make synthflesh require SS to make, I think that is the correct way ot nerf it.

It will be significantly harder to make massive amounts of synthflesh and if someone does, its the endgame of medical, so fair enough.

**Comment by eLeCtrOssSnake** [comment]
Bad change.

**Comment by VictorVow** [comment]
@PowerfulBacon this is the sort of change that people will downvote because they hate nerfs but is a necessary balance fix. Another synthflesh PR got downvoted so this will likely need to just be pushed through regardless.

**Comment by eLeCtrOssSnake** [comment]
Stop nerfing/balancing shit. Just because something exists and you don't like it doesn't mean that you have to create a PR explaining in 200 words how HORRIBLE THIS IS AND WHY WE SHOULD NERF. The thing is, this is a change nobody had requested, wanted or ever thought about. So @Victor239, if people downvote something, that means they don't want these changes if you think, that if you don't like these changes, you immediately start crying about PR being good, but being downvoted. It's downvoted for a reason, not being good, because the majority is what classifies either a thing is good, or bad. There are exceptions, but this is not the one.

So stop cry-baiting votes and saying this is good, this is bad, horrible, in many ways.

**Comment by VictorVow** [comment]
>needing your permission before balancing something
>thinks theres been no discussion on synthflesh anywhere
>groupthink

Moment.

**Comment by Sinmero** [comment]
>So stop cry-baiting votes and saying this is good, this is bad, horrible, in many ways.

Can you explain why is it horrible?

> Make synthflesh require SS to make, I think that is the correct way ot nerf it.
> 
> It will be significantly harder to make massive amounts of synthflesh and if someone does, its the endgame of medical, so fair enough.

I think there is already a pr that does that. Thou i dont think that just adding Silver Sulfadiazine to the recipe would make Synthflesh that much harder to make. You will just have to build several additional chem synthesizers and all the tools are at medbay roundstart.
I think that Synthflesh wasnt made with being able to produce it in infinite quantities in mind. We could remove/change blood+mutagen recipe or add plasma to Synthflesh recipe so it could be produced in limited amounts but i kinda like the od variant more.
Also changing Synthflesh recipe might end up in people not being cloned because nobody bothers to make it. (since cloning needs Synthflesh to function)

**Comment by PowerfulBacon** [comment]
> Stop nerfing/balancing shit. Just because something exists and you don't like it doesn't mean that you have to create a PR explaining in 200 words how HORRIBLE THIS IS AND WHY WE SHOULD NERF. The thing is, this is a change nobody had requested, wanted or ever thought about. So @Victor239, if people downvote something, that means they don't want these changes if you think, that if you don't like these changes, you immediately start crying about PR being good, but being downvoted. It's downvoted for a reason, not being good, because the majority is what classifies either a thing is good, or bad. There are exceptions, but this is not the one.
> 
> So stop cry-baiting votes and saying this is good, this is bad, horrible, in many ways.

What is there to hate about an item that instantly heals all your burn and brute damage? This clearly isn't a PR out of salt.

**Comment by eLeCtrOssSnake** [comment]
> > Stop nerfing/balancing shit. Just because something exists and you don't like it doesn't mean that you have to create a PR explaining in 200 words how HORRIBLE THIS IS AND WHY WE SHOULD NERF. The thing is, this is a change nobody had requested, wanted or ever thought about. So @Victor239, if people downvote something, that means they don't want these changes if you think, that if you don't like these changes, you immediately start crying about PR being good, but being downvoted. It's downvoted for a reason, not being good, because the majority is what classifies either a thing is good, or bad. There are exceptions, but this is not the one.
> > So stop cry-baiting votes and saying this is good, this is bad, horrible, in many ways.
> 
> What is there to hate about an item that instantly heals all your burn and brute damage? This clearly isn't a PR out of salt.

Yes, it is. Dude's literally crying "sad p--p-p-p-pr i-i-s g-ood, b-b-b-utt they-y wi-ll d-d-down vote i-it"
Disgusting....

**Comment by ghost** [comment]
> > > Stop nerfing/balancing shit. Just because something exists and you don't like it doesn't mean that you have to create a PR explaining in 200 words how HORRIBLE THIS IS AND WHY WE SHOULD NERF. The thing is, this is a change nobody had requested, wanted or ever thought about. So @Victor239, if people downvote something, that means they don't want these changes if you think, that if you don't like these changes, you immediately start crying about PR being good, but being downvoted. It's downvoted for a reason, not being good, because the majority is what classifies either a thing is good, or bad. There are exceptions, but this is not the one.
> > > So stop cry-baiting votes and saying this is good, this is bad, horrible, in many ways.
> > 
> > 
> > What is there to hate about an item that instantly heals all your burn and brute damage? This clearly isn't a PR out of salt.
> 
> Yes, it is. Dude's literally crying "sad p--p-p-p-pr i-i-s g-ood, b-b-b-utt they-y wi-ll d-d-down vote i-it"
> Disgusting....

"NOOOOOOOOOOOOOOOOO I CANT MAKE INFINITE BOTTLES OF INSTAHEAL ANYMORE WTF!!!!!!"

**Comment by RafRoq** [comment]
I would rather just have tg synthflash where it gives toxin damaged based on how much you heal with it, sounds better than this

**Comment by RafRoq** [comment]
It still is a big effort PR it is unfair to shitty on you, the truth is, most players like to have synthflash this way due to the freedom it gives you and will shit on any PR attempting to lower it's power, in one round there was a teratoma with a dufflebag with a dozen synthflash bottles in it, I managed to beat it because myself had multiple healing drugs on me, i STILL prefer TG synthflash instead of the one in this PR

**Comment by CarpStation** [comment]
I think tgs version of synthflesh is still better

**Comment by hotimep** [comment]
why not do the legion core method of nerfing it and make it turn you into a flesh monster if you use too much synthflesh

**Comment by zeskorion** [comment]
as i see it, you are making what is essentially a duplicate of a pr already voted out. I'm closing this. adding splashed reagents to bloodstream allows them to be weaponized as well.

synthflesh DOES need a nerf, but not this one- like i said, nerf viro chem recipes (mutagen+blood, etc) to not multiply blood, and that'll fix synthflesh factories handily

**Comment by Sinmero** [comment]
> adding splashed reagents to bloodstream allows them to be weaponized as well.

It is true that people can splash others to od them thou i limited max splash volume that gets in bloodstream to 50u (splashing with 300u bluespace beaker will give 50u) and reagent wont get in the bloodstream if the person already has od to prevent people having huge amounts of reagents in them plus od effects are quite minor (its 0.33 tox/tick). If you want to splash someone to harm them acid should be your choice.

My point with splash to bloodstream is that Silver Sulfadiazine/Styptic Powder are nearly as powerful as synthflesh. People will just splash themselves with those instead of synthflesh.

> nerf viro chem recipes (mutagen+blood, etc) to not multiply blood

Im not sure if making it impossible to easily produce synthflesh is good since cloning needs it to function.

**Comment by ghost** [comment]
> > adding splashed reagents to bloodstream allows them to be weaponized as well.
> 
> It is true that people can splash others to od them thou i limited max splash volume that gets in bloodstream to 50u (splashing with 300u bluespace beaker will give 50u) and reagent wont get in the bloodstream if the person already has od to prevent people having huge amounts of reagents in them plus od effects are quite minor (its 0.33 tox/tick). If you want to splash someone to harm them acid should be your choice.
> 
> My point with splash to bloodstream is that Silver Sulfadiazine/Styptic Powder are nearly as powerful as synthflesh. People will just splash themselves with those instead of synthflesh.
> 
> > nerf viro chem recipes (mutagen+blood, etc) to not multiply blood
> 
> Im not sure if making it impossible to easily produce synthflesh is good since cloning needs it to function.

then kick scientists in the ass to do their job and upgrade the cloner, its easy to manually make synthflesh.

**Comment by VictorVow** [comment]
> synthflesh DOES need a nerf, but not this one- like i said, nerf viro chem recipes (mutagen+blood, etc) to not multiply blood, and that'll fix synthflesh factories handily

A small nerf to synthflesh's healing capability vs making synthflesh mass production much slower for it's various purposes in cloning, healing, synthmeat etc. Which PR is going to cause more outrage.

**Pull request closed without merging**
