### PR TITLE
Beebeeduceus Part 1/X: Category Twos, Base(d) Healers 

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request

Replaces all Category 2's and some Category 3's (with Category 2's)

Establishes Category 2's as a thing not just in the forum/github comments space.

Borgs are now warned with a generic message when selecting medicine that has ill effects within their borg hypo.

Borgs now have perf instead of salbu (missed in my PR? I don't remember)

image

## Why It's Good For The Game

Standardizes Category 2s: Apart from the obvious "someone trying to sabotage the codebase" chems, I tried to minimize the C2 chems into 2 per damage type. As I mentioned in another PR and on the forums, I think the complexity of medbay should be around the decision making process instead of which of the 500 chems I should use with 100 being stackable for the same damage.

I tried to give these straightforward downsides while also trying to make them interesting BUT ultimately "good" healing chems (AKA things I wouldn't mind giving a player ingame).

Category 2's as a general concept are to act as either emergency chems or short/long term trades. The days of popping bicard/tricord/stypic and running off are behind us, I want healing to be as active (see Category 1's) as possible while promoting (not necessarily requiring) outside assistance. Category 2's are a compromise to that.

Removals/Recatagorizations were because they were previously the "base" healing method, which has been replaced with Tend Wounds. They were also pretty strong in their own right not even considering they could be stacked with previous trekchems and such.

Numbers and effects are subject to change Pre-PR. 150 hours of testing but i'm sure someone will probably think of a situation I haven't. Going to try to lock down the chems post merge and certainly try to avoid adding more until the entire rework is completed so people (cough cough) can rest easy with these chems. Same is true for future PRs of the "Beebeeduceus" variety.

Please note some changes were made to replace chems and did not have an immersion aspect considered. For instance, poppies DON'T grow acetaminophen.
## Changelog

:cl:
add: A variety of Category 2 Chems
del: Stypic/Old SilverSulf/Old Synthflesh/Injectables/Thializid/Oxylid have been removed
tweak: Silver Sulf / Synthflesh are now C2s
tweak: Borgs now have perf instead of salbu.
admin: Borgs are now warned when using meds that cause side effects.
code: Category 2 is finally established in code!
code: A comprehensive table can be found @ #45749
/:cl:
### NAME THIS Commit

The names are now more intuitive to what they do with an attached suffix that's unique for the damage type healed.

    Brute = -ibital
    Burn = -uri
    Oxy = -mol
    Tox = iver

Also Properly Readds Thotlizid and Oxilizid (didn't change anything about them except name given the responses below)

(totally not stolen from https://github.com/tgstation/tgstation/pull/45749)

### CODE REVIEW

**Comment by dinnerwoerror** [comment]
quantum of solace is my favorite bond movie

**Comment by MarkSuckerberg** [comment]
papa john would want this

**Comment by zeskorion** [comment]
fails travis

**Comment by dinnerwoerror** [comment]
У нас еда просто класс. Полиненасыще нные жиры и триглицеридыждут вас.

**Comment by ike709** [comment]
Better ingredients. Better pizza. Papa Johns.

**Comment by MarkSuckerberg** [comment]
I JUST GOT IT PASSING TRAVIS AUGH

**Comment by Isy232** [comment]
This is an april fools joke, right?

**Comment by Isy232** [comment]
I wouldn't be opposed to some minor nerfs to the chems we are used to and adding of really powerful healing chems that give some longer term issues, but /tg/ cobby chems are a pain in the ass and feel specifically designed so that chemistry cannot heal everything, no matter how complex or hard the chem is to make.

**Pull request closed without merging**
