### PR TITLE
[WIP] Interstation Cargo Network

### PR DESCRIPTION
**Pull request by ike709**
I'm back, baby. Adds cross-server cargo. NSV13 will be supported once the PR is ported there.

#### Selling to the ICN
1. Set the price and account info in the ICN Tagger.
2. Tag the crate containing whatever you want to sell.
3. Send the crate to CentCom via the cargo shuttle.
#### Buying from the ICN (wip)
1. Open a cargo console.
2. Navigate to the ICN section.
3. Buy a crate.
4. Wait for it to arrive on the next shuttle.

What about content that other servers don't have? The cargo console checks that each type exists and if it doesn't then it won't be included in the content listing. If none of a crate's contents are valid, the crate won't be listed at all.

TODO:
- [ ] Add purchasing from the ICN to the cargo console.
- [ ] Edit the cargo console UI (ugh).
- [x] Write the actual API (ugh, python): https://github.com/BeeStation/Website/pull/30
- [ ] Testing.

## Changelog
:cl:
add: Added the Interstation Cargo Network. You can use an ICN tagger to sell crates to other servers, or buy them from the cargo console.
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
What's stopping people from pulling a smuggler's satchel with 0 credit cost

**Comment by ike709** [comment]
@yyzsong The minimum cost of 1000 credits, for one.

**Comment by ike709** [comment]
Also crates will expire on roundend of the source server.

**Comment by yyzsong** [comment]
Sending back the crate and stamped manifest returns 700 credits to the station, so it's more like a cost of 300 credits and a prerequisite of 1000. Plus securing the budget of like, basically any head of staff allows you to purchase a bunch of these minimal crates.

**Comment by ike709** [comment]
@yyzsong Why do you assume this includes manifests?

Not to mention that players can set whatever prices they want for their crates. If you *really* want to just be sending over effectively "free" stuff to other servers for some reason, go for it.

**Comment by PowerfulBacon** [comment]
wtf this is cool. Interstation ERT assistance next 😉

**Comment by badideaguy** [comment]
Oh boy refreshes the item on transfer

Time for infinite use holopara injectors, and sadly no 69 voice trigger max caps with the trigger as " "

**Comment by BeloneX** [comment]
So what happens when you sell an item that doesn't exist on another codebase?

**Comment by PowerfulBacon** [comment]
Prevent anything with the adminspawned flag from being sold, and preventing indestructible items being sold would probably be a good idea too

**Comment by Archanial** [comment]
Me when I sell armed bomb to other station

**Comment by DatBoiTim** [comment]
Does the level of crate security change on the contents?
IE: If LRP cargonian breaks into armory and sends to ICN. If this is bought on LRP will it just be a standard crate? Will it match the access of the crate sent?

**Comment by ike709** [comment]
@DatBoiTim Secure crates can't be used.

**Comment by DatBoiTim** [comment]
> @DatBoiTim Secure crates can't be used.
> 
> 

Can you buyback from the ICN?

**Comment by ike709** [comment]
No.

**Comment by PowerfulBacon** [comment]
oh yea also dont allow holodeck items to be sold

**Comment by jlsnow301** [comment]
I am intrigued to see your skills in py

**Comment by ike709** [comment]
@PowerfulBacon How would they even get a holodeck item out of the holodeck?

**Comment by ghost** [comment]
> @PowerfulBacon How would they even get a holodeck item out of the holodeck?

If it's emaged.

**Comment by utilbird** [comment]
> NSV13 will be supported once the PR is ported there

Will with work out of the box with other downstream servers
_(i.e austation)_

**Comment by Kmc2000** [comment]
Finally, we can outsource our munitions production to the colonies

**Comment by badideaguy** [comment]
> Finally, we can outsource our munitions production to the colonies

The power gamers won't like this, so uhhh Teslas and a singulo labeled 'torpedo'

**Comment by ike709** [comment]
@TheFakeElon 

To sell on the ICN the server has to be in the bee api's list of servers, to properly purchase from the ICN the server has to have our comms key (you could jury rig an alternative to this that fakes it). Aside from that it'll work out of the box if you port the code.

**Comment by utilbird** [comment]
> To sell on the ICN the server has to be in the bee api's list of servers

sad, wouldn't it be better to just make it 2 way with a separate key that isn't tied with all the other functions associated with the 
comms key

**Comment by ike709** [comment]
@TheFakeElon The webserver polls a list of gameservers for their exports whenever the cache expires. The gameservers aren't actively sending their latest orders to it.

That being said, being included is just a matter of adding a server to a config file on the website.

**Comment by ike709** [comment]
Note to self: Fix setting department accounts, don't have the ICN tagger open the popups when you pick it up.

**Comment by ike709** [comment]
TODO: Fix exports.

**Comment by ike709** [comment]
This will need to be redone after the API refactor.

**Pull request closed without merging**
