### PR TITLE
Makes Oil a subtype of fuel, cause it's flammable.

### PR DESCRIPTION
**Pull request by Tsar-Salat**
## About The Pull Request
Oil is now under the /fuel/ subtype. Literally just a change from `/datum/reagent/oil` to `/datum/reagent/fuel/oil`

This makes it flammable, and be able to be used in place of `/datum/reagent/fuel` in crafting.

## Why It's Good For The Game

I kind of expected this behavior already, but was suprised that oil didnt light on fire like I expected. 

Seriously, oil is stuff like acetone, petrol, benzene, ethanol... all very flammable stuff. Im not sure what "Oil" is supposed to exactly represent in SS13, so Im considering it the catch-all for "Hydrocarbons"

Flammable stuff made in the crafting menu is generally pretty low-grade compared to bombs or the nasty diseases available to more specialized roles. 
Making fuel more accessible should give an alternative option to antags or McGyvers in a tight spot.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/0c89fe3b-931e-43ee-b5df-b06babc93b4c

</details>

## Changelog
:cl: RKz
balance: New Space-OSHA regulations class Oil as an accelerant! You can now use oil wherever you can normally use fuel, in crafting, or more... flammable applications.
/:cl:

### CODE REVIEW

**Comment by theqwat** [comment]
i always viewed oil as like... motor oil which its around cargo and robotics

**Comment by Tsar-Salat** [comment]
> viewed oil as like... motor oil

The current black "Oil" we have now is most reminiscent of Petroleum, that is, crude oil. 

image


It already uses welding fuel as an ingredient to make it, so I think it should inherit the flammability from that.
Hydrogen and Carbon are extremely on the nose to mean Hydrocarbon lmao.

image


The ingame Oil doesn't particularly resemble Motor Oil in my opinion. Motor Oil typically has a lot of additives that wouldnt really make sense with the current recipe or appearance.

image

**Comment by PowerfulBacon** [comment]
> i always viewed oil as like... motor oil which its around cargo and robotics

You can set those on fire

**Comment by Rukofamicom** [comment]
This also makes oil toxic to consume
This makes cigarettes dipped in oil explosive
There are probably other interactions this causes that are potentially less than ideal.

> Seriously, oil is stuff like acetone, petrol, benzene, ethanol

Acetone and ethanol are not oils. Benzene is extracted from crude oil and I'm pretty sure it isn't an oil itself but not nearly so much as the first two.

**Review by Rukofamicom — DISMISSED** [review]
You can make oil flammable without making it a subtype of fuel - ethanol is flammable, for instance.

**Comment by Tsar-Salat** [comment]
> You can make oil flammable without making it a subtype of fuel

Yes. I'm aware. 

My intention is for it to have the same properties welding fuel usually has. This includes the toxicity, as well as being an accelerant used in crafting.

It uses welding fuel as an ingredient already, so it inheriting its properties makes sense.

**Comment by Rukofamicom** [comment]
In that case all I can say is I disagree with the idea that ambiguous oil should be equivalent to explosive/highly flammable fuel.

~~even with the nonsense crafting recipe that says welding fuel is part of it~~

**Comment by Tsar-Salat** [comment]
im taking a break, Semester begins soon and this is affecting my mental health

**Pull request closed without merging**
