### PR TITLE
TGUI now has multiple setting save holders

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
* TGUI now has multiple setting save holders

## Why It's Good For The Game
You'd NOT want to have all the same chat settings for all codebases since the terms and words for each codebase are used differently.
And additionally, chat history will not be shared across codebases too!

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
add: Now you can have multiple TGUI setting saves. There can be unexpected reset due to this.
config: !!VERY IMPORTANT!! 'setting_config.js' is newly added that contains a config key that how a server stores TGUI setting.
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
If no key is present, it should automatically import the TG settings,

**Comment by EvilDragonfiend** [comment]
> If no key is present, it should automatically import the TG settings,

that's nulling.

**Comment by itsmeow** [comment]
TGChat, not TGUI.

**Comment by EvilDragonfiend** [comment]
> TGChat, not TGUI.

It includes all other TG components that use backend storage (i.e. window geometry)

**Comment by EvilDragonfiend** [comment]
gonna change it a bit more

**Comment by EvilDragonfiend** [comment]
image

It's way better now

**Comment by EvilDragonfiend** [comment]
I feel like my code is a bit jank but whatever it's pretty functional

**Comment by EvilDragonfiend** [comment]
Let's do this once it's merged in TG

**Comment by EvilDragonfiend** [comment]
going to do later someday

**Pull request closed without merging**
