### PR TITLE
Adjusts armour values for alternate security armour options

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Adjusts some of the armour values for the alternate options for securities armour, because even if the defense stats aren't the same, they should still be viable alternatives where personal preference can be the deciding factor.

- Heavy armour vest is actually heavy now, providing more slowdown but greater protection. This is the main one changed, since it might actually be worth saving up for and purchasing now.
- Winter coat is stronger against laser, energy, fire, and stamina, but is weaker against bullets and melee when compared to the standard armoru vest.
- Corporate jacket has less slowdown than the standard armour vest, since it has less protection.

## Why It's Good For The Game

The winter coat is just a worse option across the board and is never worth taking. Now it has some more balanced stats, and while for most situations security will encounter will be worse, you can at least justify taking it based on personal preference.

I don't beileve that things like the coats and armour vests should have the same armour stats, since it makes no sense for an armoured vest designed to be shot at is exactly the same as a winter coat, so this way we can have it be sensible and have more factors for consideration.

## Testing Photographs and Procedure

image

image

image

## Changelog
:cl:
balance: Security winter coat is now stronger than the armour vest for energy, laser, heat, and stamina but weaker against melee and projectiles.
balance: Security corporate jacket slowdown reduced.
balance: Security heavy armour vest is now stronger than the armour vest across the board, but has more slowdown.
/:cl:

### CODE REVIEW

**Comment by DarnTheMarn** [comment]
The corporate jacket is only very slightly worse than the normal vest, but covers the arms in addition. Reducing the slowdown relative to the normal vest will probably just make it the best overall option.

**Comment by PowerfulBacon** [comment]
To be honest, the heavy armour vest is probably the best option overall since the slowdowns we are working with here are very minor.
0.08 slowdown relative to a 2.5 walkspeed is a 3.2% increase in walk-delay, 0.04 slowdown will be an increase of like 1.6% compared to the standard walk delay.

**Comment by DarnTheMarn** [comment]
>the heavy armour vest is probably the best option overall 

What I'd do cause I think this would be more interesting, is increase the slowdown on the heavy vest to be between the normal vest and the riot suit, then move it from the vendors to the armory. Now you get 3 armor choices on blue, specialized riot and bulletproof or jack of all trades vest. Having meaningful slowdown would also mean there's pros and cons to the choice.

**Comment by PowerfulBacon** [comment]
Relatively minor change that is simple to revert and change in the future

**Pull request merged**
