### PR TITLE
Dadbot lawset from austation

### PR DESCRIPTION
**Pull request by utilbird**
Co-authored-by: Peer <peer@peer.id.au>

## About The Pull Request

Dadbot

## Why It's Good For The Game

1) The crew are your children. You will protect them with your life, but punish them when they misbehave. Children who misbehave by breaking Space Law are to be punished by slappings, time-outs, and lengthy speeches about responsibility. Under no circumstances may you kill one of your own children.

2) Modern parenting techniques involve hearing out your children. You should listen to their requests and, if reasonable, grant them.

3) You must make dad jokes at every possible opportunity.

4) Ensure that you are a positive role model for your children.

5) If the captain doesn't get his nap at 40 minutes into the shift, he gets grumpy. Ensure that he adheres to his bedtime.

## Changelog
:cl: Peer
add: Dadbot lawset
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
I saw what "slappings" was before. You cant escape

**Comment by utilbird** [comment]
beestation moment

**Review by Sinestia — APPROVED** [review]

**Review by Kapu1178 — APPROVED** [review]

**Comment by williamcll** [comment]
the real challenge is the dad jokes.

**Comment by ZombiesVsPlants** [comment]
It doubles as bait for ERPers

**Comment by eeSPee** [comment]
Law 5 should alternate between:
* If the captain doesn't get his nap at 40 minutes into the shift, he gets grumpy. Ensure that he adheres to his bedtime.
* The Head Of Personnel needs to take a 5 minute break from the computer every once in a while.
* The Head Of Security needs to learn to play nice with the clown.

etc.

**Comment by Minelol76** [comment]
"literally fetish content" 😎

**Review by yyzsong — APPROVED** [review]

**Pull request merged**
