### PR TITLE
Randomized shift for thrown items

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports:
- https://github.com/tgstation/tgstation/pull/45155

## About The Pull Request

This is an expansion of Wilson's #8587 

This PR randomizes the pixel shift of items when thrown. This applies to all items, except those with the existing item_flag NO_PIXEL_RANDOM_DROP. 
The flag can be used for items that would get really fucky if they were shifted (The fake singulo toy for example)

## Why It's Good For The Game
Items traveling in a perfect arc and landing center tile is... nonsensical. If you have many items thrown by and explosion or spacewind, they all stack on top of eachother and it doesnt look organic at all. 
A lot of items can get hidden under eachother.

If players specifically want to layer items perfectly center, both the rack and alt-clicking a table perform this behavior fine.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/201ba4de-7bdf-4e51-8b7c-8bf02579dd71

</details>

## Changelog
:cl: rkz, mickyan
add: randomized pixel shifting when throwing items
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
Will this apply to a person throwing items? As I often use this to store things neatly and tidy.

**Comment by PowerfulBacon** [comment]
Do you think it would be possible for it to use the exact mouse position from params to make it always throw where your mouse is pointing, or would that be too much of a pain?

**Comment by Tsar-Salat** [comment]
> Do you think it would be possible for it to use the exact mouse position from params to make it always throw where your mouse is pointing

Unfortunately, I'm not sure where I would begin with that. This is just shifting the x and y with 6 pixels

**Comment by Tsar-Salat** [comment]
> Will this apply to a person throwing items?



> Screenshots&Videos

**Comment by Nakalon** [comment]
I ask for the same thing as Markus. I use this to store things neatly. May another way to do this be added if this makes it?

**Comment by Nakalon** [comment]
I didnt read PR alt clicking table sounds cool

**Comment by Tsar-Salat** [comment]
https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/ca7263fc-a9bd-480a-b4e8-38c7ff6665ff

This exists as a way to stack things centered.

It looks tedious, but thats because i have an ultrawide

**Comment by MarkusLarsson421** [comment]
It is tedious. The ALT menu is a last resort.

**Comment by Tsar-Salat** [comment]
There exists an object explicitly designed to center all your items on it. Use that. 

Throwing as it stands makes no mechanical sense to be the go-to method to center items.

**Comment by Rukofamicom** [comment]
> This applies to all items, except

**Comment by Tsar-Salat** [comment]
> Except what?

Forgot to finish this thought lol. Fixed.

> Who is this and what is this porting from?

See commit descriptions

**Comment by Rukofamicom** [comment]
image

**Review by Rukofamicom — APPROVED** [review]
👍

**Pull request merged**
