### PR TITLE
[WIP] Harbinger Heretics (rework)

### PR DESCRIPTION
**Pull request by KazooBard**
**Harbinger Heretics**

## About The Pull Request
This is a Work In Progress rework for the heretic antagonist role that focuses on improving stealth, increasing early game escape capabilities, remaking sidepaths into variants to make it simpler in nature, differentiating playstyles and most importantly, decreasing the murderboney nature of heretics. 

## Why It's Good For The Game
There is a lot of controversy and complaints about how much heretics hurt the population of servers or get killed early on and leave the crew a greenshift. A few abilities don't work such as ashen mark, which for some reason also has cooldown decrease upon hitting a marked target. 

## What has been done:
Most things in the ash path, concepts, altered schematics, most robe sprites, some simple ability sprites and a few new items.

The new paths are going to include variants instead of sidepaths as you may know them this day, which means you can pick between two spells instead of adding to a massive arsenal. 

## What's left:
-fixing arcane wards
-changing the way sacrifices work and the related effects
-blade shatter change
-ashen armour sprites
-rust path
-flesh path
-basic path restructuring that the layout is ready for
-the new path 
-balancing

## Credits so far
Reds88#8433 robe sprites
AmiTech#2794 Review, concepts, feedback

this is still a very much subject to change and feedback PR.
## Changelog
:cl:
:add: new spells: executioner's fury, ashen rewind, cleanser's curse, ashen whispering, summon spear of destiny
:add: new items: unique robes for every path, amulet of dampening, arcane ward, spear of destiny(weapon)
/:cl:

### CODE REVIEW

**Comment by Boxlta** [comment]
Every path of heretic should get a jaunt, not just ash

**Comment by KazooBard** [comment]
> Every path of heretic should get a jaunt, not just ash

Every path will get a unique movement option to help escape tough scenarios

**Comment by eeSPee** [comment]
> > Every path of heretic should get a jaunt, not just ash
> 
> Every path will get a unique movement option to help escape tough scenarios

Make sure ash jaunt is mandatory, not a side path.

**Comment by KazooBard** [comment]
> 
> 
> > > Every path of heretic should get a jaunt, not just ash
> > 
> > 
> > Every path will get a unique movement option to help escape tough scenarios
> 
> Make sure ash jaunt is mandatory, not a side path.

sure

**Comment by KazooBard** [comment]
Big update soonTM, just two fixes. Coder no close please

**Pull request closed without merging**
