### PR TITLE
Tweaks xeno hijacking

### PR DESCRIPTION
**Pull request by benbot16**
## About The Pull Request

This changes the xenomorph hijack objective to be in line with all other hijack objectives, meaning: have a xeno on the shuttle, and override the flight computer.

## Why It's Good For The Game

Consistency is good

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image
</details>

## Changelog
:cl:
tweak: Xenomorphs now hijack the escape shuttle by overriding the flight controls.
/:cl:

### CODE REVIEW

**Comment by mystery3525** [comment]
my feeling when the xenomorphs must use their hands to hack into the indestructable shuttle computer to hijack its destination to go to the syndicate outpost

**Comment by benbot16** [comment]
> my feeling when the xenomorphs must use their hands to hack into the indestructable shuttle computer to hijack its destination to go to the syndicate outpost

my feeling when the xenomorphs do not hijack because of the living infected human in a nest inside of the shuttle.

**Review by itsmeow — DISMISSED** [review]
I didn't even know that you couldn't have a living nonalien on the shuttle. Holy shit.

The game should be more consistent. As queen I've tried hijacking via console and been confused as well.

Even if it may not make perfect sense roleplay wise, from a gameplay perspective this is much needed

**Comment by benbot16** [comment]
> Perhaps an alternative would be if the queen and at least 1-2 xenos are alive on the shuttle they win

that'd allow for cheeki strats though, this means you actually have to secure the cockpit for a bit.

**Comment by Rukofamicom** [comment]
> that'd allow for cheeki strats though

When it comes to Xenos this is perfectly valid and makes sense both IC and OOC. The purpose of the game is not to win, it's to RP and be interesting.

Xeno hijack goal amounts to expansion and spreading, not eradication. Sneaking into the shuttle should 100% count as a win in the post game.

The shuttle shouldn't delay or otherwise behave specially for Xenos, it should just arrive and depart, and if the queen is on the shuttle alive when it docks it's a victory.

Please do not make Xeno hijack require Xenos to use computers it is ludicrously immersion breaking @itsmeow

**Comment by benbot16** [comment]
You already need to use the computer to hijack as a xeno, otherwise the shuttle won't leave.

**Comment by itsmeow** [comment]
Then that settles it lol, if someone wants  to fix it they can in a separate PR but as it is, blocking the win because someone was barely alive on the shuttle is stupid.

Maybe check the stat of all living mobs and exclude unconscious instead of just outright winning if xenos hijack, as it could mean one xeno hijacked, but then were wiped out during travel.

**Comment by benbot16** [comment]
>Maybe check the stat of all living mobs and exclude unconscious instead of just outright winning if xenos hijack, as it could mean one xeno hijacked, but then were wiped out during travel.

Alright, done

**Comment by Rukofamicom** [comment]
Does it still require hacking via the console?

Does it still cause a hostile environment?

**Comment by benbot16** [comment]
I'm keeping the objective the same. If you want to change the hostile environment and xenos end objective you can do it in a separate PR, but I for one don't want to touch even more xeno balance right now.

**Comment by Rukofamicom** [comment]
Since this is changing balance it needs a second sign off and to be labeled properly.

**Comment by Fronsis** [comment]
It's true that it sucks when the hijack fails because a random hugged body on stasis-crit is still alive, i've seen cases where the queen ordered to kill everyone (after all once the hug is done they're infected) and on the other side i've seen people just weld off a motor out of the shuttle just to be there and deny the xeno hijack(of course they're just trying to.. survive and board the shuttle though RP wise it's not.. really a smart thing to do), just today had a round where a traitor survived and denied the hijack because he deconstructed a motor and stayed there, zero xenos were able to reach to him because acid wasn't melting the titanium shuttle walls and some parts of the motors seemed almost indestructible even if attacked by queen+prae+a few aliens

It's also true that i've always noticed confusion on players about on how to ''hijack'' per se, from aliens going: ''just kill everyone!'' to: ''moom touch the console!!'' and a few LOOC's saying ''alt click console'' when it.. really doesn't do much afaik, i think it automatically ends the hostile enviroment if the queen does it?

In any case, couldn't there be a check that confirms queen+aliens surpasses the other humanoids in quantity to consider it a hijack? there can be different interpretations on how to make the aliens succeed on the hijack and not lose becuse of some weird stuff like a dude on stasis-crit, cheesing people on the motors or a classic dude with chamaleon mutation, while we're long gone from the idea of ''GET LE GREENTEXT'' and we're encouraging RP stuff, it stills sucks when stuff like that happens mostly on the side of the xenomorphs players that had a half an hour long battle to win the shuttle only to get their victory grasped out of them for stuff like previously mentioned.

**Comment by itsmeow** [comment]
#8039 Is probably the better way, RIP

**Comment by Penwin0** [comment]
I concur, Ruko's PR is preferable

**Pull request closed without merging**
