### PR TITLE
Added, Tweaked: Flypeople (BEES!)

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
- Fly people get a new species selection box. They can choose the default housefly or a hoverfly (a bee lookalike).
- Fly people now like more foods: Meat, raw, and fruit.
- Fly people now move 20% faster and take 30% more damage from brute and burn

Imgur Image
Imgur Image

## Why It's Good For The Game
MORE BEES ON BEESTATION
Imgur Image

## Changelog
:cl:
add: new limbs for flypeople
tweak: damage received increased
tweak: speed increased
tweak: favored foods
removed: no longer use underwear
/:cl:

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
Why flies and not bees?

**Comment by jlsnow301** [comment]
It did not make sense that they would still be considered "flypeople" if they were bees. Unless we rename them to insects

**Comment by St0rmC4st3r** [comment]
No, flypeople are a reference to some ancient movie trope when people go into a teleporter with a fly and their genomes mix. I mean, why don't we just make an entire Bee race?

**Comment by jlsnow301** [comment]
that's the spirit. BEES!

**Review by ike709 — APPROVED** [review]

**Review by MarkSuckerberg — APPROVED** [review]
YUSS

**Pull request merged**
