### PR TITLE
New walls and girders (now with smoothing!) + spare fixes

### PR DESCRIPTION
**Pull request by PestoVerde322**
## About The Pull Request

This PR implements a new style of walls and girders, which now are also smooth when built next to eachother.

## Why It's Good For The Game

Old walls and girders are a relic of the early 2010s era, as much they're dear to everyone, it's time to let go.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

immagine

immagine

*On PowerfulBacon's request*
immagine

</details>

## Changelog
:cl:
add: Girders and their reinforced variant are now a smooth structure.
imageadd: Replaced the outdated Walls and girders icons.
code: Put some order in the indestructible walls and gave them their own folder (excluding the Hilbert hotel's unique turfs)
fix: Wooden walls and Silver walls are now opaque again
/:cl:

### CODE REVIEW

**Comment by Geatish** [comment]
Already making a beecode wallstation

**Comment by RDS88-beeman** [comment]
Muh Sovl!

In all seriousness, this is cool, but what about. All the other walls. Like the paper one, and the wooden one, and the bamboo one, and

**Comment by PestoVerde322** [comment]
> In all seriousness, this is cool, but what about. All the other walls. Like the paper one, and the wooden one, and the bamboo one, and

I plan to do them in a future update, this is just a groundstart for now and I didn't feel to make the PR overextended.

**Comment by Tsar-Salat** [comment]
This is hot

**Comment by Sadboysuss** [comment]
wow that's beatiful

**Comment by RDS88-beeman** [comment]
Fair enough. Is this supposed to nuke Cordons? Since it seems like it nukes cordons.

**Comment by PowerfulBacon** [comment]
These look absolutely excellent

**Comment by ike709** [comment]
Those reinforced walls look awful.

**Comment by Tsar-Salat** [comment]
Reinforced walls could use some touchups on their smoothing

**Comment by PowerfulBacon** [comment]
The smoothing on the R-walls make them look a bit boxed out

image

It would be nice if the lines at the edge of the tiles were somehow changed to make them look like less individual tiles and more like a continuous wall.

image

**Comment by Programs-The-Station** [comment]
I like the style of the normal walls, but I think the smoothing groups need to be expanded a bit.

For instance, the walls should probably smooth to airlocks and windows, because this angling makes it seem like there's a V groove between the window/airlock and the wall.
image

In addition, wall mounts now kinda look out of place, because they cross 2 or 3 sides now. Like the intercom and pepper spray dispenser here.
image
It's like the intercom is stuck on the top surface of the wall, and hanging off the front side.

**Comment by PestoVerde322** [comment]
> I like the style of the normal walls, but I think the smoothing groups need to be expanded a bit.
> 
> For instance, the walls should probably smooth to airlocks and windows, because this angling makes it seem like there's a V groove between the window/airlock and the wall. image
> 
> In addition, wall mounts now kinda look out of place, because they cross 2 or 3 sides now. Like the intercom and pepper spray dispenser here. image It's like the intercom is stuck on the top surface of the wall, and hanging off the front side.

As I've said in the discord, for now this PR focuses on the (iron) walls and girders since i didn't want to overscope the PR; however I'll take those in account for the following PRs.

**Comment by Programs-The-Station** [comment]
> As I've said in the discord, for now this PR focuses on the (iron) walls and girders since i didn't want to overscope the PR; however I'll take those in account for the following PRs.

Yep, I know that you are only focusing on the walls. I just wanted to bring it up because I don't want this to become a Wallening where the project gets left in a half finished state (not saying that you would do that, just making sure the wall mounts were on the radar for the PRs in the future).

**Comment by llol111** [comment]
Im not a fan of changing the wall sprites at all, tbh. Wierd ass sloped triangle looking stuff.
But... these are infinitely more tolerable than the shit TG pulled. Im just whining, these are not _that_ bad.

**Comment by Tsar-Salat** [comment]
> Im not a fan of changing the wall sprites at all, tbh.

12 years.

Bay station has newer walls than us.

**Comment by llol111** [comment]
> > Im not a fan of changing the wall sprites at all, tbh.
> 
> 12 years.
> 
> Bay station has newer walls than us.

neither of those things are an argument

**Comment by ToasterBan** [comment]
it took me 20 minutes of playing to even notice these changes, upgrading the sprites while keeping a very similar look, very well done

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
They are essentially official at this point with how long they've been on

**Pull request merged**
