### PR TITLE
Transparent PDA colorizer for the BeeCoin store

### PR DESCRIPTION
**Pull request by CydiaLamiales**
## About The Pull Request
Adds a new colorizer for PDAs - transparent and adds it to the beecoin shop.

## Why It's Good For The Game
Well someone on the forums wanted it so I added it.
https://forums.beestation13.com/t/clear-pda-added-to-beestore/19536/

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image
https://user-images.githubusercontent.com/110184118/186624694-8d249ca1-51e2-40ca-9c8c-d29f4eac1012.mp4
Note : the typo in the video was fixed

</details>

## Changelog
:cl:
add: Adds a transparent PDA colorizer
add: Adds said colorizer to the BeeCoin store
add: Adds a blacklist to colorizers
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
Restrict it to not-clown, I guess?

**Comment by itsmeow** [comment]
> Restrict it to not-clown, I guess?

Why?

**Comment by itsmeow** [comment]
Also restrict syndicate PDAs

**Comment by CydiaLamiales** [comment]
> > Restrict it to not-clown, I guess?
> 
> Why?

Clown's PDA is slippery so Dragonfiend doesn't want the clown to easily change his PDA's look.

**Review by Crossedfall — DISMISSED** [review]

**Comment by EvilDragonfiend** [comment]
unlicensed isn't syndi pda. It's pda for gimmicks.

**Comment by itsmeow** [comment]
Yeah allow unlicensed

**Comment by EvilDragonfiend** [comment]
But also, IIRC, colorizer does no longer disappear upon using. It can be used by someone else than you - making infinite clear pda on the station. I think it should have one time usable.

**Comment by CydiaLamiales** [comment]
> But also, IIRC, colorizer does no longer disappear upon using. It can be used by someone else than you - making infinite clear pda on the station. I think it should have one time usable.

But they are one time use? I attached a video, you can see it dissapear from my hand once I use it.

**Comment by EvilDragonfiend** [comment]
> > But also, IIRC, colorizer does no longer disappear upon using. It can be used by someone else than you - making infinite clear pda on the station. I think it should have one time usable.
> 
> But they are one time use? I attached a video in the PR's description, you can see it dissapear from my hand once I use it.

Then I remembered it incorrectly, so all good.

**Review by itsmeow — APPROVED** [review]

**Review by ike709 — APPROVED** [review]

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
