### PR TITLE
Removes mob_has_gravity()

### PR DESCRIPTION
**Pull request by park66665**
## About The Pull Request

This soft-reverts tgstation/tgstation#20464 while avoiding tgstation/tgstation#20410. In short, this PR removes weird situations around gravity and movement code.

The magnetic boots have worked in a really weird manner; for example, `update_gravity()` depended on `mob_has_gravity()`, thus magboots could prevent *every* (incl. space; yes, magboots technically caused gravity to the wearer in space) non-gravity situations regarding warnings and float via `mob_negates_gravity()`... except when it comes to `Process_Spacemove()`. Magboots don't cause gravity here, since deep in the `Process_Spacemove()` family tree, `has_gravity()` is the one who checks the gravity; and  `has_gravity()` doesn't call `mob_negates_gravity()`.

So magboots prevent weightlessness when it comes to spacemove? Well, `mob/Process_Spacemove()` looks for backup! The backup finding process is code that is responsible for making you being able to spacewalk safely as long as you move near wall or lattice, and the proc is `get_spacemove_backup()` Magboots can flex its muscles via `mob_negates_gravity()` because it allows any non-space turfs to be its backup: so, as long as it isn't space all around, magboots let you walk!

This PR does a small refactor to remove this inconsistency, by removing `mob_has_gravity()` to make `mob_negates_gravity()` have influence on Spacemove and other stuffs properly; `has_gravity()` is used to check if something is on the floor (or can be on floor when the throwing ends) instead of floating above it, rather than denoting the actual state of weightlessness. But, we can't let magboots and other `mob_negates_gravity()` checks to cause spacewalking most of the time, so I included `isspaceturf()` checks (think the one at the current `get_spacemove_backup()`) in corresponding places to not repeat the mistake of tgstation/tgstation#20303 (i.e. tgstation/tgstation#20410)

I can further rewrite the gravity code to differentiate the gravity-mimicking behaviors and the real actual gravity, but, for now, I see no need for it, so I stop; in my humble opinion, full-blown rewriting of legacy code should be kept at minimum.

## Why It's Good For The Game

Y'know, I could've ignored this. However, while intermittently doing the dreaded `Life()` review, I learnt that a thin wrapper called `mob_has_gravity()` has been causing 10% additional overhead (I still have no idea why) even on cases where it does nothing but returning the return of `has_gravity()` (i.e. simple mobs calls `/mob/proc/mob_has_gravity()`). I decided to fix it.

This solution hopefully improves the movement and gravity code, and reduce overhead caused by `mob_has_gravity()`. This should reduce workload of the server a tiny bit considering `mob_has_gravity()` is quite busy code path.

## Changelog
:cl:
fix: magboots no longer make you feel gravity in space
code: removed legacy mob_has_gravity() to reduce overhead
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — APPROVED** [review]
the expensiveness from this proc probably mostly comes from has_gravity() anyway and will just shift the expansiveness over to has_gravity instead, but yea I don't see anything wrong really

**Comment by park66665** [comment]
Screenshot 2021-01-07 052804

**Comment by PowerfulBacon** [comment]
wow how, might be due to mob_negates_gravity, the only other reason I can see

**Comment by PowerfulBacon** [comment]
fuck it yolomerge

**Comment by park66665** [comment]
> wow how, might be due to mob_negates_gravity, the only other reason I can see

I too have no idea exactly why (and I still doubt whether it is 100% real from time to time): if I had read code correctly, Poly hadn't called `mob_negates_gravity` at `mob_has_gravity`; Poly is a simple_animal, so its `mob_has_gravity` only had called `has_gravity()`... but it doesn't explain any of its c. 10% overhead! (it should be much, *much* less than that... but `has_gravity()` is a rather ~~highly~~ efficient proc, so that *might* really be proc calling and returning overhead) However, I can stop thinking about it.

**Pull request merged**
