### PR TITLE
Adds Deputies and increases security playtime requirements

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request

Adds a new security role: Deputy. Four duffel bags with Deputy gear have been added to the SecTech vendor.

They're not a roundstart role however, which is for a few reasons:
- They're non-mindshielded and we don't need more roles with Brig access who can instantly start deswording security whilst they're still getting their gear on.
- It's bait for people who normally validhunt as an assistant and want extra gear that helps them to tide better.
- It's intended to supplement how deputising currently works IC. 

But they are a job rather than just a gear bag because:
- HOPs have no excuse now for promoting people without background checks to full Security Officer when there's a role designed specifically for these people.
- Allows you to quickly identify Deputies through secHUDs instead of wondering why there's someone who looks like a seccie but weren't roundstart and aren't mindshielded. 

It's intended that the HOS approves people to get promoted to Deputy and buys them the gear bag from the SecTech vendor, then once dressed they go to the HOP and get their ID updated to the same. 

Deputies get a modified security belt with pepperspray, a deputy baton (weaker than detective baton at 15 damage, no knockdown but lower cooldown), handcuffs, cable restraints and a seclite. They have a normal sec headset (not bowmans), a reskinned secHUD (not HUDsunglasses) and no armor. Access to the Brig but not to the Security Office/Gear Room (similarly to Lawyers). 

So they're not really any more dangerous than an assistant with a cakehat and they'll almost always need help to forcibly arrest anyone but they make good extra bodies for patrols and backup.

**Also** the playtime requirements for all security jobs have been changed, they all require playtime as Security Officer first. Now you have to have 10 hours of Security playtime to unlock HOS, 7 for Warden, 3 for Detective and 2 for Brig Physician. Security Officer playtime requirement has doubled from 7 to 14 hours. 

## Why It's Good For The Game
Deputy as a job role give a way for a HOS to easily deputise crew and standardises what access and gear they should have. 

Increased playtime requirement for Security is good because this role can have a huge effect on the round and it's better that slightly more experienced players have this responsibility and power. 

## Changelog
:cl:
add: Adds Deputies, a non-roundstart non-mindshieled security job. Ask the HOS to buy you the deputy bag from the SecTech and the HOP to promote you after. 
tweak: Security playtime requirements increased. 
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
didn't you also make a pr for this that got voted out

**Comment by ghost** [comment]
yes he did

**Comment by VictorVow** [comment]
@zeskorion 99% of complaints were about the Cadet addition, this is another atomised PR.

**Comment by ghost** [comment]
> 
> 
> @zeskorion 99% of complaints were about the Cadet addition, this is another atomised PR.

then why would you do another PR with the cadet addition.

**Comment by VictorVow** [comment]
@BeloneX did you read the PR? There's no Cadets only Deputies.

**Comment by ghost** [comment]
> 
> 
> @BeloneX did you read the PR? There's no Cadets only Deputies.

i don't get the point of deputies, hops shouldnt promote people to sec officers without the hos approval in the first place and any sane hos would make the newly promoted officers completely strip their gear, this just seems like the "solution" to a non-existant problem.

**Comment by VictorVow** [comment]
@BeloneX even if they get the HOS approval they shouldn't be promoted to Security Officer regardless because they haven't had a background check. By becoming a Deputy other Security can instantly recognise on their secHUDs who this person is, why they have sec gear and are not mindshielded.

**Comment by Isy232** [comment]
This is good because now there is an intermediate job that people can be promoted to.
Sometimes there is a large lack of roundstart security, with only 2 or so seccies for a station of 40-50 people.
The issue is if you promote people to full security and they are a traitor or cultists or whatever they can abuse their role.
This just adds the option for a mini-security officer role, its not a roundstart role and needs the HoS or HoP to promote someone to it.

Its not a huge problem but its just a nice addition that does not take away anything at all.

**Comment by VictorVow** [comment]
@ike709 merge

**Comment by qwertyquerty** [comment]
Police brutality time

**Pull request merged**
