### PR TITLE
Adds a bunch of DS items and changes sprites of DS hardsuit

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

gives deathsquad troopers their own, gloves, advanced magboots, combat jumpsuit, combat mask, and changes the DS hardsuit sprite and tweaks the special ops officer/admiral jacket and beret

## Why It's Good For The Game

because why not.

## Changelog
:cl:
add: Added a bunch of new DS gear
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Tons of conflicts.

**Comment by ghost** [comment]
i don't even know why

**Comment by ike709** [comment]
Probably because you didn't rebase master before you made the branch.

**Comment by qwertyquerty** [comment]
F

**Pull request closed without merging**
