### PR TITLE
Changes felinid say verb to "meows"

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Felinids now have the "meows" instead of "says". Yes. I fucked up and pressed enter accidentally when making the title, so the labels are fucky. Sorry.

## Why It's Good For The Game

Makes felinids more distinguishable over comms and speech. Helps AI differentiate humans and felinids without them being on cams.

## Changelog
:cl:
tweak: felinids now have the meows verb
/:cl:

### CODE REVIEW

**Comment by Vexylius** [comment]
Cool, but what the fuck with those labels? lol

**Comment by ivanmixo** [comment]
> Cool, but what the fuck with those labels? lol

I kinda fucked up and I can't remove them, going to have to wait for a maintainer to remove the extra labels

**Comment by TeomanTheGreat** [comment]
Good pr. Now I can id felinids to bully over comms.

**Comment by WhyIsCaeciliusTaken** [comment]
Change it to "Annoyingly meows"

**Comment by Archanial** [comment]
Which maintainer authorized this? If I'm not mistaken you need maintainers approval if you are going to touch races.

**Comment by Septoxide** [comment]
Ooh this is a good one

**Comment by PowerfulBacon** [comment]
Species code needs maintainer approval.

**Comment by PowerfulBacon** [comment]
Once approval is acquired you can reopen this PR>

**Comment by park66665** [comment]
I hereby approve this PR's continued existence.

**Comment by USB3pt0** [comment]
Is there a way to change "whispers" to "purrs" and "yells" to "yowls"?  May as well go all in.

**Comment by Effemu** [comment]
> Change it to "Annoyingly meows"

do that otherwise you're a furry

**Review by utilbird — APPROVED** [review]

**Review by Kmc2000 — CHANGES_REQUESTED** [review]
Beestation, you're better than merging this PR...

**Comment by jupyterkat** [comment]
yes

**Comment by TeomanTheGreat** [comment]
> Beestation, you're better than merging this PR...

This will only help ais differentiate humans from non-humans as well as help crew find which of their crews on comms aren't human.

**Comment by OceanFish1** [comment]
LRP AI can finally instantly see who's non-human on comms thats based

**Comment by PowerfulBacon** [comment]
> 
> 
> Beestation, you're better than merging this PR...

I wish

**Comment by qwertyquerty** [comment]
> Beestation, you're better than merging this PR...

Are we really so sure about that?

**Pull request merged**
