### PR TITLE
Fixes fucking floors

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

MarkSuckerberg and qwertyquerty did an oopsie

This PR fixes a SABOTAGE of our codebase! Someone accidentally(or not) changed a reinforced floor sprite to bay one even if PR was "Without Replacements"!

## Why It's Good For The Game

Bay12 reinforced floors doesnt fit neither old or new style

## Changelog
:cl:
imageadd: Added old engine floor icon_state
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
What are they now?

**Comment by ike709** [comment]
Push an empty commit so IconDiffBot runs again.

**Comment by MarkSuckerberg** [comment]
I'm hurt.

(also qwerty had mentioned this before it was merged, and said it was fine.)

**Comment by Crossedfall** [comment]
Please don't fuck the floors

**Comment by utilbird** [comment]
Smh, Qwerty and his floor fetish

**Comment by utilbird** [comment]
Checks need to be reran

**Comment by francinum** [comment]
:pain:

**Pull request merged**
