### PR TITLE
Ports centcom envirosuits from tg

### PR DESCRIPTION
**Pull request by BrumalLake**
## About The Pull Request
Ports [tgstation/#53042](https://github.com/tgstation/tgstation/pull/53042)
Ports [tgstation/#56987](https://github.com/tgstation/tgstation/pull/56987)
Ports centcom envirosuits and makes ert spawning plasmaman friendly
Moves some loadout items around to make room for plasma tanks
Also adds a plamaman version of the centcom commander outfit
ERT now start with their sechailers on

## Why It's Good For The Game
No more suffocating to death as death commando or getting immolated as a code banana clown or intern

## Changelog
:cl:
add: centcom envirosuits
tweak: moved some job items to left hand
fix: plasmamen dying as certain ert roles
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
I don't know why the heads.dmi file got smaller after adding 6 sprites

**Comment by Sarchutar** [comment]
You need to add `ERT_SPAWN` to `changesource_flags = MIRROR_BADMIN | WABBAJACK | MIRROR_PRIDE | MIRROR_MAGIC` inside plasmamen.dm so they don't get changed into humans upon spawn.

```
if(ertemplate.enforce_human || !(ERTOperative.dna.species.changesource_flags & ERT_SPAWN)) // Don't want any exploding plasmemes
	ERTOperative.set_species(/datum/species/human)
```

Also i don't think adding the jobs to `before_equip_job` will work since the people get made into antagonists with their own outfit.
Example:
```
/datum/antagonist/official/proc/equip_official()
	var/mob/living/carbon/human/H = owner.current
	if(!istype(H))
		return
	H.equipOutfit(/datum/outfit/centcom_official)

	if(CONFIG_GET(flag/enforce_human_authority))
		H.set_species(/datum/species/human)

```

**Comment by BrumalLake** [comment]
oh, i just found out the author of the tg port had another pr to update the antag outfits which they didnt have in the original

**Comment by MCterra10** [comment]
Someone merge this before the poor man has to deal with another icon conflict 😢

**Comment by lordScrubling** [comment]
Works seamlessly now, plasmamen spawn with their masks and internals on

**Comment by BrumalLake** [comment]
Works seamlessly now, plasmamen spawn with envirosuits with internals and masks on

**Comment by BrumalLake** [comment]
The infamous merge conflict, we meet yet again
could've had 5 by now if i fixed this before #4548

**Review by utilbird — APPROVED** [review]
Sorry! 
I know how annoying it can be, speaking from experience 😅

**Pull request merged**
