### PR TITLE
Adds Gamma and Epsilon alert

### PR DESCRIPTION
**Pull request by AnCopper**
## About The Pull Request

Adds the Gamma and Epsilon alert levels from YogStation.

**This will require SoP edits to add the alerts.**
"Code Gamma - Massive Threat
Maximum alert level. There is a massive threat to the station or severe damage. Can only be triggered by Central Command.

Suit sensors are to be turned fully on at all times.
Security can raid departments and arrest any crew member deemed a threat to the station.
All non-essential crew members are to move to a safe position.
Disobedience can be punishable by death."

"Code Epsilon - ██████████
ACCESS TO THIS FILE HAS BEEN RESTRICTED FOLLOWING A CODE NANOTRASEN//PANOPTES//SIGMA ORDER.

REQUESTS TO ACCESS THIS FILE MUST BE PROCESSED BY AI-COM.█████."

https://github.com/yogstation13/Yogstation/pull/12151
https://github.com/yogstation13/Yogstation/pull/12134
https://github.com/yogstation13/Yogstation/pull/9244

## Why It's Good For The Game

I feel like there's a gap between red alert "Yo, there's a threat to the station" and delta "OH GOD OH FUCK" Gamma basically serves as a maximum threat condition, Gamma can be triggered by admins and will be triggered during station-wide threats like War Ops, Blood cult obtaining halos, and the Clockwork cult starting to summon Rat'var (Delta will now sound when Rat'var is spawned)

Epsilon is only triggerable by Admins, it sounds an announcement to the station saying "Consider all contracts terminated", it's basically for Deathsquads.

Both of these also have their own alert sound.

## Changelog
:cl:  swissloaf ynot01 adamsong AnCopper
add: Adds Gamma and Epsilon alert
soundadd: Adds gamma and epsilon alert sounds
tweak: Security level is now set to gamma when cult have halos, war ops are triggered and other high threat antag events.
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
but blue alert is the "we have a threat" alert and red alert is the "oh god oh fuck alert" also what the fuck does epsilon alert mean

**Comment by St0rmC4st3r** [comment]
> but blue alert is the "we have a threat" alert and red alert is the "oh god oh fuck alert" also what the fuck does epsilon alert mean

Epsilon means "Nothing personnel."

**Comment by mcmeiler** [comment]
Do these have corresponding sprites for the fire alarm?

**Comment by r1ks-iwnl** [comment]
This might also need some changes to beebot's ?check and i doubt this will have a easy time getting merged if it wasn't discussed with headmins

**Comment by PowerfulBacon** [comment]
> will be triggered during station-wide threats like War Ops, Blood cult obtaining halos, and the Clockwork cult starting to summon Rat'var (Delta will now sound when Rat'var is spawned)

Don't like auto alert raising since it affects the shuttle

**Comment by PowerfulBacon** [comment]
Also epsilon alert is a meme and gamma is just delta

**Comment by Crossedfall** [comment]
> Maximum alert level.

Isn't actually the maximum alert. 😔

**Comment by Fronsis** [comment]
The ones i liked from other servers where the ones that were ''Engineer emergency'' and ''Medical emergency'' (i don't remember the names) But they were nice to let crew know that ''something's uh oh with engi.. a hull breach? plasma flood? better not walk around careless) or the Medical one that was used for massive casualties or big outbreak of a virus (sentient/viro-released/random event) these ones... eh

**Comment by DatBoiTim** [comment]
> The ones i liked from other servers where the ones that were ''Engineer emergency'' and ''Medical emergency'' (i don't remember the names) But they were nice to let crew know that ''something's uh oh with engi.. a hull breach? plasma flood? better not walk around careless) or the Medical one that was used for massive casualties or big outbreak of a virus (sentient/viro-released/random event) these ones... eh

Like Bays? 
Orange Alert(Engineering): Applicable for plasmafloods, supermatter delaminations, etc. Any time there's a need for engineering personnel to be very active.

Violet Alert(Medical): As you had said. Technically this also covers xenobiological issues.

I think that it works a lot better than this attempt to make alert more gradient.

https://wiki.baystation12.net/Alert_Procedure

Here's Bay's setup for reference.

**Comment by francinum** [comment]
The code for this stuff is kinda nasty and is better off reworked instead of continuing to be direwired in.

Also yeah, both of these alert levels are *sorta meaningless*

**Comment by PowerfulBacon** [comment]
:key:

**Comment by qwertyquerty** [comment]
:key:

**Pull request closed without merging**
