### PR TITLE
Removes bilk

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
Removes all mentions of bilk from the code, besides the changelog logs

## Why It's Good For The Game

image

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
del: bilk is no more (rejoice)
/:cl:

### CODE REVIEW

**Comment by bluezorua** [comment]
I dont think that's what they meant by remove bilk, I think they only wanted to remove the holy bilk from your pr

**Comment by etherware-novice** [comment]
they also closed keyed my pr for the bilkshake :|

**Comment by itsmeow** [comment]
based, remove bilk, literally what is that

**Comment by PowerfulBacon** [comment]
I mean we have drinks from the depths of hell so milk mixed with beer isn't that bad. Meme subject matter too.

**Comment by etherware-novice** [comment]
> I mean we have drinks from the depths of hell so milk mixed with beer isn't that bad. Meme subject matter too.

THE SERVER OWNER
CLOSED 4 OF MY PRS
BECAUSE OF BILK

**Pull request closed without merging**
