### PR TITLE
Updates our layers to get ready for plane cube, and weather effects

### PR DESCRIPTION
**Pull request by dwasint**
## About The Pull Request

Ports:
- https://github.com/tgstation/tgstation/pull/61286
- https://github.com/tgstation/tgstation/pull/57915

## Why It's Good For The Game

Lets us get fancier effects, should be entirely backend changes
 
## Testing Photographs and Procedure

TESTED:
Weather overlays,
Emitters/projectiles,
general walking around,
darkness and openspace interaction,
item rendering on transparent objects,
pipes rendering in contrast to player sprites
player vs various planes,

## Changelog
:cl:
add: Added warping effect to gravitational anomaly
refactor: Refactored the layer and plane system
/:cl:

### CODE REVIEW

**Comment by dwasint** [comment]
Note please test this a fair bit there are alot of things that render and i probably missed a few in my testing

**Comment by PowerfulBacon** [comment]
Complete testing and changelog when this PR is ready to be reviewed

**Comment by dwasint** [comment]
> Complete testing and changelog when this PR is ready to be reviewed

we do changelogs for non player facing changes on bee?

**Comment by itsmeow** [comment]
Oh, you put your testing evidence in the wrong header. Screenshots not strictly necessary if you verify what is working

**Comment by itsmeow** [comment]
https://github.com/tgstation/tgstation/pull/62902

**Comment by itsmeow** [comment]
image

Bug from original PR is also present here

**Comment by itsmeow** [comment]
Also I swear the game looks different
image

**Comment by itsmeow** [comment]
Managed to reproduce the blackness by merging master and using 1589

**Comment by itsmeow** [comment]
Looks like there's a lot we need
https://github.com/tgstation/tgstation/commits/master/code/_onclick/hud/rendering/plane_master.dm

But I think the real bug is this
https://github.com/tgstation/tgstation/pull/69778

**Comment by itsmeow** [comment]
Yep, setting the plane's color to null completely fixed it
image

**Comment by itsmeow** [comment]
Making some tweaks on my side with PRs from upstream, things are looking more correct now

image

**Comment by itsmeow** [comment]
Ignore the HUD being jank on this but here's a comparison of the same area with and without the PR (including my tweaks)

<details>
<summary>Click to expand</summary>

With

image

Without

image


Seems ambient occlusion is a bit fucked up

image
image

</details>

**Comment by itsmeow** [comment]
Update CL and description to include the PRs I ported btw

**Comment by itsmeow** [comment]
Bug with reflectors

**Comment by itsmeow** [comment]
image
Changes in its level of error when you move... not sure what is happening with that, also seems to happen when slashing

**Comment by benbot16** [comment]
Grav anomaly warping doesn't go away sometimes if you neutralize the anomaly.

**Comment by itsmeow** [comment]
Fix above bugs and it should be good

**Review by itsmeow — APPROVED** [review]
Seems good enough. Didn't really notice any other major visual issues, and the bug I found was rare. Everything else looked good

**Pull request merged**
