### PR TITLE
[Port] BSQL Replacement

### PR DESCRIPTION
**Pull request by Crossedfall**
## About The Pull Request

From: https://github.com/tgstation/tgstation/pull/51255

Queries were parameterized as much as possible. Careful code read by someone else also versed in SQL would be a good idea. Things seemed fine spot-testing roundstart, library, bans, and polls, but more stress-testing may be useful.

Also updates rust-g to v0.4.5:

    Improved Linux .so detection
    Perlin noise functions

Also updates Travis script to bionic.

## Changelog
:cl:SpaceManiac
refactor: BSQL has been replaced with rust-g, improving SQL reliability and safety.
/:cl:

---

Ports: 
https://github.com/tgstation/tgstation/pull/51255
https://github.com/tgstation/tgstation/pull/51508 
https://github.com/tgstation/tgstation/pull/51517

### CODE REVIEW

**Comment by Flakkyboo** [comment]
while you are working into the library stuff you might consider making the changes i was looking into.
making a new upload to the library require admin approval before its added to the database.

you are likely to have it done much faster than i would

**Comment by Crossedfall** [comment]
> 
> 
> while you are working into the library stuff you might consider making the changes i was looking into.
> making a new upload to the library require admin approval before its added to the database.
> 
> you are likely to have it done much faster than i would

That's pretty out of scope for what I'm doing. Changes like that would be better in another PR.

**Comment by Crossedfall** [comment]
Missed some stuff

**Comment by Crossedfall** [comment]
Test merged onto both servers

**Comment by MCterra10** [comment]
God I hope this fixes all the undeleted query warnings

**Comment by Crossedfall** [comment]
@MCterra10 I fixed a fair number of them. But if you all notice any more after this let me know.

**Pull request merged**
