### PR TITLE
Ports the ssd indicators from..skyrat

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
https://github.com/Skyrat-SS13/Skyrat13/pull/420 nice
https://github.com/Skyrat-SS13/Skyrat13/pull/615

skyrat may be infamous but it does have a few good ideas
so you get an ssd indicator on you when you go ssd

## Why It's Good For The Game
Useful for telling at a glance wheter someone is actually ssd, INFINITELY useful for the ai as they cant examine people

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
add: ssd indicators
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
Not tweak. It is add.

**Comment by PowerfulBacon** [comment]
Does the indicator remain if you change their clothes?

**Comment by etherware-novice** [comment]
why would changing equips affect this

**Comment by PowerfulBacon** [comment]
Since its based on directly adding to overlays rather than using add_overlay, clothing is all done by overlays which will be updated when using add_overlay or remove_overlay. Directly adding to overlays means it won't be managed by the overlay system which you get if you use add_overlay instead

**Comment by etherware-novice** [comment]
indicator continues towork

**Comment by FortSumter** [comment]
A fine addition to my collection!

If possible, perhaps have different icons depending on how they are disconnected, like green if the player is AFK but is still connected, yellow for a sudden disconnection, red for if the player had properly left the game or if its a case of soul departed/DNR. I know this would be a lot to ask for, but it'd be super helpful to know if there's a possibility of the player comming back or if we are wasting our time by having a catatonic person in med for the purposes of cryoing them as med or how a suspected traitor should be handled if they suddenly go SSD as a security officer.

**Comment by etherware-novice** [comment]
well idk how to test the different disconnects but sure i can do a red for dnr

**Comment by etherware-novice** [comment]
nvm i dont understand this

**Comment by Fronsis** [comment]
Honestly a nice idea, i saw it before and i think it's very useful even in some scenarios where you can go ''oh they're ssd i'll come back later to them''

**Comment by FortSumter** [comment]
It's okay if you can't do what I suggested; I'm not sure if what I suggested is even possible. I just thought it would be insanely helpful if you could use this to tell not only when someone is SSD, but also be able to judge whether they might come back at all depending on how they disconnected. I know the server keeps track of a disturbingly large amount of meta data and so I was hoping it logged disconnects in a way to make my idea possible.

**Comment by Zonespace27** [comment]
you ported the Skyrat Cit versions of our SSD indicators, I recommend checking [1325](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1325) to make sure it matches (along with porting [1801](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1801) and [1908](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1908)) since the skyrat TG version (linked) is slightly more recently made

**Review by itsmeow — APPROVED** [review]
Looks fine

**Pull request closed without merging**
