### PR TITLE
Ports Cannabis

### PR DESCRIPTION
**Pull request by Tsar-Salat**
### THIS PR IS DEPENDENT ON #8351

Ports:
- https://github.com/tgstation/tgstation/pull/59360

## About The Pull Request
This PR replaces all cases of Space Drugs in Weed with a new reagent, Cannabis!

Includes:
- Adds cannabis reagent and replaces space drugs with it in cannabis products
- Adds space drugs to rainbow weed, which fits its theme and might satisfy the people who miss the effect
- Removes lipolicide from cannabis products in favour of the reagent consuming nutrition directly
- Cannabis reagent gives you messages describing symptoms of cannabis intoxication, makes you laugh, makes you hungry, has a chance to couchlock you buckled to a chair and put you to sleep lying down
- Cannabis no longer references hallucinating, can't be overdosed and has no addiction
- Adds Stoned status effect, which is applied by cannabis reagent
- Stoned status effect slows you down, gives you bloodshot eyes, makes you clumsy, boosts your mood and gives you the drugged sound environment
- Adds "stoned" icon state for Stoned status effect screen alert (sprite shamelessly stolen from the Smoke spell)
- Adds BLOODSHOT_EYES trait, which is applied by Stoned status effect
- Adds examine eye descriptions for bloodshot eyes and player-chosen red eyes
- Adds cannabis movespeed modifier, which is applied by the Stoned status effect
- Adds Stoned mood event, which is applied by Stoned status effect and gives the same mood boost as High but doesn't reference tripping

## Why It's Good For The Game
Ok, so, for the years we have had weed, we supplanted "Cannabis" as a reagent with either Space Drugs or Mindbreaker. Both would perform the expected hallucinogenic effects on the user. 

However, with my ongoing addiction rework adding a wide range of addiction to reagents that were either lacking addiction, or buffing the addiction consequences, a change was necessary.

Mostly I wanted to add this because I think it would add more depth to weed as a whole, because at the moment literally all space drugs does is give you a funny swirly effect on your screen and audio, and change your language. 

I think we can add more depth for roleplay by adding better mechanics to weed

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

stoned

</details>

## Changelog
:cl: RKz, Cacogen
del: Removed Space Drug effects from weed
add: New Cannabis reagent, functionally similiar to Space Drugs, but exists to better address its shortcomings.
add: stoned status effect, and related exposure stuff
tweak: The Weed plants have all been tweaked to use Cannabis as the primary ingredient, consuming Cannabis will give you bloodshot eyes, a stoned status effect, a movespeed
fix: Any OD thresholds have been removed from REGULAR weed, go wild. (Wildly consuming the reagents that OD you in Rainbow Weed will still probably kill you)
imageadd: added Stoned screen_alert
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
ugh I made it speed you up, woops

**Comment by Tsar-Salat** [comment]
DNM until https://github.com/BeeStation/BeeStation-Hornet/pull/8351 is merged, please

**Comment by WrillWasTaken** [comment]
This is a nerf to carpet bomb plants

**Comment by CydiaLamiales** [comment]
DUDE WEED

**Comment by BriggsIDP** [comment]
> * Adds space drugs to rainbow weed
> * Adds space drugs to rainbow weed

**Comment by EvilDragonfiend** [comment]
> > * This is a nerf to carpet bomb plants
> > * Adds space drugs to rainbow weed

it's not full removal of space drugs from plants. It exists in another plant.

**Comment by Tsar-Salat** [comment]
this got staled when its dependent on another system, not really sure what you want me to do here.

Codewise, its fine and does what it needs to.

**Pull request closed without merging**
