### PR TITLE
Ports the bilkshake from para

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
Ports the bilkshake from https://github.com/ParadiseSS13/Paradise/pull/18932

## Why It's Good For The Game
bilk bilk

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
add: bilkshake
/:cl:

### CODE REVIEW

**Comment by etherware-novice** [comment]
GO AWSAY MEOW I KNOW OK I KNOW I DONT HAVE AN IMAGE YET GIVE ME 10 MINUTES GEZZUSWANS

**Comment by itsmeow** [comment]
Then don't post the PR :trollface:

**Comment by etherware-novice** [comment]
how do i block someone

**Comment by itsmeow** [comment]
image

**Comment by ZephyrTFA** [comment]
Crime against humanity

**Comment by LiberatedWaveMan** [comment]
original creator seal of approval

**Comment by etherware-novice** [comment]
thanks

**Comment by Crossedfall** [comment]
:key: Feels out of place here.

**Comment by DerpiestBruh** [comment]
how

**Comment by ike709** [comment]
🔑 bloat

**Pull request closed without merging**
