### PR TITLE
Readds the wishgranter spawn datum.

### PR DESCRIPTION
**Pull request by PowerfulBacon**
Reverts BeeStation/BeeStation-Hornet#4263

**!!NOTE: WISHGRANTER WAS ALREADY IN THE RUIN BLACKLIST!!**

Removing a ruin should either be:
 - Full removal from files including map
 - Added to the ruins blacklist.

Removing the datum is a poor solution, since it doesn't remove the large map file and is less helpful for downstream that might want to have it enabled in config.

🆑
code: Readds the wishgranter map file datum since it was blacklisted anyway.
/🆑

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Wait lmao its already blacklisted

**Comment by Penwin0** [comment]
Im having a stroke

**Comment by Penwin0** [comment]
Im pretty sure Archanial already made a PR that resulted in this though

**Comment by PowerfulBacon** [comment]
Im just reverting #4263 because it was a dumb PR that got speedmerged. This doesn't actually change anything since the ruin is blacklisted so doesn't spawn anyway.

**Comment by PowerfulBacon** [comment]
Someone already reverted properly this apparently

**Comment by Penwin0** [comment]
Yeah thast what I was refering to

**Pull request closed without merging**
