### PR TITLE
Each uplink now has 3~6 discount numbers upto its type, and implant in pref option is free now

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
* Each uplink now has its own advantage
* Implant uplink (roundstart) no longer costs 3 TC (unless you buy it from uplink again)

## Why It's Good For The Game
uplink implant sucks because:
You can just buy an uplink implant, then you can get free 3 more discounts with it.
which means, non-implant uplinks basically have 6 discounts when tots try to get additional uplink.

so, I made this free, and instead, less-stealthy uplinks will have more discounts.

PDA has 6 discounts because you should turn on uplink when you want to use TCs and it's very risky, so it's rewarding PDA.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

PDA is actually 6 discounts. I buffed it later.

image

PDA with 5 discounts (later commit buffed it to 6)

image

radio uplink with 4 discounts

image

implant with 20 TC and 3 discounts

</details>

## Changelog
:cl:
balance: uplink implant in character pref no longer costs 3 TC.
balance: uplink types in character pref now advantages the number of discounts up to its exposure disadvantage. For example, PDA will give you 6 discounts, while uplink implant will give you 3 discounts.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I did want to buff the discounts, since most of the buy one get one free offers aren't that good. I think this might make implant way better than the others though, perhaps it should just start with no discounts at all

**Comment by EvilDragonfiend** [comment]
> I did want to buff the discounts, since most of the buy one get one free offers aren't that good. I think this might make implant way better than the others though, perhaps it should just start with no discounts at all

If discounts are not effective due to what you said 'most of the buy one get one free offers aren't that good', making it with discounts would make no difference.
The point I am aiming for those is that the more risk you have, the more gimmick chance (from discounts) you'll get. although I think it's fine to make the implant have 2 discounts since it has less risk.

**Comment by Penwin0** [comment]
Each uplink having different ammounts of discounts is pretty weird, I don't think uplink implant should be free either as it's a straight up upgrade from the others in most cases

**Comment by EvilDragonfiend** [comment]
it seems the majority doesn't like it, but I will keep this open. Feel free to give me a key or tell me any better idea.

**Comment by Job-IDev** [comment]
I'm not much of a fan of increasing the number of discounts per device. Mainly because of the aforementioned reasons, all devices have the same stealth level except for the implant. Therefore the implant costs 3 TC.

I think the 3 TC cost, either way, is worth it. Starting with the implant you will leave behind no traces. When buying the implant, you might get new discounts but you'll also have to dispose of your implanter. While this is just a minor inconvenience, I don't think giving other devices more discounts is the way to combat the problem.

If you don't want people to get a new list of discounts, then you'd have to generate a list of discounts once they join and have the store be linked to the person instead of the device. This comes with its own problems hence it's a difficult issue to combat.

> I did want to buff the discounts, since most of the buy one get one free offers aren't that good.
This totally depends whether you are in an incursion or just solo. I've had rounds where someone had a good discount, but you'd only need 1 item in your round. (Like teleporter or emag) Then we shared the cost and both had said item. But some discounts are just crazy. Like a round yesterday, 6 syndicate hardsuits for 9 tc. (as an excommunicate)
Despite that, I think most discounts are fine as is right now.

**Comment by DatBoiTim** [comment]
> You can argue "oh this is less stealthy then this" but in the end they are all the same, and all pretty stealthy if you close it after use
> And the other way around, if you fuck up / dont lock it, they all can be discoverd easily. It just happens that most people use the standart option of PDA uplink, so sec culture is to check PDAs and forget about pens and earpieces.
> If they checked all three equaly dilligently, then all three options would be the same level of stealthy.

I'm pretty sure pen is actually legitimately the best aside from implant because you always need to put in the code to access the uplink. It effectively autolocks.

PDA/Headset need to be locked manually. Pen is almost definitely the best of the 3 20 TC uplinks, and to my knowledge it still works like a regular pen.

**Comment by PowerfulBacon** [comment]
Yea removing the extra cost is bad since its just objectively better

**Comment by EvilDragonfiend** [comment]
I still don't think adjusting TC is good in general. You always expect you have 20 TC from uplinks, and being reduced to 17 TC means you lose a lot of possibilities to do something because not a few stuff is locked to 18~20 TC.
so, I adjusted the discount amounts while keeping the consistency for 20 TC. Making things cost more TC because it's effectively stealthy shouldn't be a way to go, as it will eventually make everyone use a specific uplink. That's WHY I intended giving advantage instead of putting disadvantages for each uplink.
yeah, pen may be supposed to be 3 TC, then people will not use pen. why the hell would take a pen when you can get murderbone for the chance of using his grace, romerol? it comes to implant too. why would you want it? being stealthy isn't enough reason to use, thus the implant doesn't mean anything to be offered as an option.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Putting the close key on here:

I agree with:
- More discounts (While cool, my new discount options kinda suck in a lot of options)
- Buffing the implant uplink

The buff to the implant uplink is just too good and makes it by far the obvious meta choice. I think a good implant buff would be making it so that its cheaper than buying it from the uplink, but still subtracts some cost which makes you unable to buy some uplink options.

Feel free to reopen if some parts are changed, but atm the balance is too far off

**Pull request closed without merging**
