### PR TITLE
Haloperidol and chloral nerfs

### PR DESCRIPTION
**Pull request by Toxici11i**
## About The Pull Request
Changes Haloperidol and Chloral Hydrate to be more balanced

## Why It's Good For The Game
Makes medibots cease stunlocking you for 9000 years and claiming its "not human harm" with haloperidol, and reducing how long chloral hydrates effects last, nerfing it for its relative ease of production.
## Changelog
:cl:
add: Added OD limit and effects for haloperidol
Tweak: Tweaked chloral hydrate and haloperidol's metab rate.
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Kev what do you think of this

**Comment by CthulhuOnIce** [comment]
no idea

**Comment by Superyodeler** [comment]
This would cut chloral's stun time from 15 ticks to 6.3 ticks. That seems like a drastic change to me.

**Comment by Toxici11i** [comment]
@Superyodeler its not necessarily how long the stun lasts that concerns me, it is the lethality of the chemical and easy availability of it. I bumped it up from 2.0 to 2.3 and still find its useful as a dart. Either way, chemists shouldnt be able to make 200u of chloral hydrate and stunlock people into death using darts/syringes.

**Comment by Superyodeler** [comment]
While it is easy to make, I'd argue that the 5 ingredients to 1 chloral reaction balances it. In addition, it takes a while to kick in and doesn't deal damage itself until more than 2 darts, so someone who got darted has time to run to a populated area or yell for help. I'd be fine with a nerf, but cutting the stun time by almost 2/3 is too much.

**Comment by Toxici11i** [comment]
Fair point, if kev deems it a bit too much he can just edit the value back down to 2.0/1.75. It is mainly to discourage people from using chloral hydrate as much as they do, and especially when it consumes 5u to make 1u. Also, chloral hydrate is RNG based iirc and timing doesnt matter same as dosage, its like a 45%(?) chance to deal oxyloss and toxin.

**Comment by LordZanos** [comment]
I don't think this is necessary. Chemists stunlocking people is already pretty balanced by anyone that should by combating traitors with syringe guns have armor that literally makes them either immune or highly resistant to syringe guns.

Medibots shouldn't be putting people into comas on Asimov without a really good Law 1 reason.

**Comment by qwertyquerty** [comment]
I'll leave this open to public opinion for a bit longer but I'm thinking it's gonna be a no

**Comment by CthulhuOnIce** [comment]
left to public opinion with no opinions given, so

**Pull request closed without merging**
