### PR TITLE
Alternate skirts - Medical edition.

### PR DESCRIPTION
**Pull request by AnCopper**
## About The Pull Request

Adds an alternative state for medical skirts. They're in the shape of the plaid skirts. 

This doesn't replace their current looks, but adds an alt-click version.

## Why It's Good For The Game

The skirts clipping through outer layer clothing bothers me a lot, so I decided to make versions that don't.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

grafik

</details>

## Changelog
:cl:
add: Added alternative versions for medical jumpskirts (alt-click to access)
/:cl:

### CODE REVIEW

**Comment by Nakalon** [comment]
alt click!? so it doesnt replace! this is awesome!!!!

**Comment by PestoVerde322** [comment]
I've a counter proposal, which is to either use the masking system that already exists for female body frames and to apply whenever you're wearing a suit or just hide the undersuit as soon you wear a *full covering* suit, since as it is right now it would cause inconsistency with pretty much any other skirt that's aviable and don't have the tubeskirt setting.
Those icons as is are fine don't get me wrong, but i feel a more "automated" option for it and also adding those alternative skirt would be great!

**Review by DrDuckedGoose — APPROVED** [review]
~~Code looks good. Pigeon will need to go over icons.~~

**Review by DrDuckedGoose — CHANGES_REQUESTED** [review]
Please post screenshots of the outfits working in-game.

**Pull request closed without merging**
