### PR TITLE
Extends cuffing timer by one third

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Extends cuffing timer by one second, for a total of four seconds.

## Why It's Good For The Game

Gets rid of a certain cheese strat of shoving twice then handcuffs/zipties to cuff anyone you want before the stun wears off.
Won't be a problem for security given they can reapply their stuns through batons or disabler, just prevents any unarmed crewmember from being able to shove -> cuff any antag that doesn't have adrenals.

## Changelog
:cl:
tweak: Handcuff timer raised to 4 seconds from 3
/:cl:

### CODE REVIEW

**Comment by Pontenerd** [comment]
Didn't someone already PR this or am I losing my marbles?

**Comment by ZombiesVsPlants** [comment]
#3637 I believe

**Comment by PowerfulBacon** [comment]
4 seconds is way better, 5 seconds is too long and 3 seconds is too short in most cases

**Comment by DatBoiTim** [comment]
Yeah the shove cuffing shouldn't just be an option.

Want to do it? Make a stun prod, get a flash, table em, corner em, light em on fire & wait for them to drop an roll, get someone to back you up, there's a ton of options.

**Review by PowerfulBacon — APPROVED** [review]

**Review by utilbird — APPROVED** [review]

**Pull request merged**
