### PR TITLE
Makes Carbon Cluwnes work, cluwnemute obtainable

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request

-Cluwne clothes now show icons
-Cluwne mutations no longer instantly kill you with 200 brain damage, instead leaving you alive at 199
-the Cluwne mutation is obtainable from genetics, by combining Clumsy and Spacial Instability.

## Why It's Good For The Game

I think it's a fun little addition, makes use of some code that's basically just sitting there doing nothing

## Changelog
:cl:
tweak: cluwne mutation is now obtainable
imageadd: cluwne mask and shoes
/:cl:

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
I think it should be at 100 brain damage, since this :A makes a player valid, so a traitor could easily abuse that, and :B means that you'll die to 1 more point of brain damage, so getting hit in the head a few times is instant death.

**Comment by SomeAngryMiner** [comment]
i hope you know the happy cluwne mask isnt anything near badass or cosmetic: once you pick it up, it wont leave your hand, and when you put it on, it will modify your speech to random gibberish and the cluwne laugh whenever you try to speak.

**Comment by zeskorion** [comment]
> i hope you know the happy cluwne mask isnt anything near badass or cosmetic: once you pick it up, it wont leave your hand, and when you put it on, it will modify your speech to random gibberish and the cluwne laugh whenever you try to speak.

ah, the code on it doesn't work as advertised or intended it seems, and i sure as hell aint gonna bother fixing it. taking that bit out then

**Comment by qwertyquerty** [comment]
Tested?

**Comment by zeskorion** [comment]
> Tested?

Tested and working fine, though i may want to add some auditory feedback to the mutation itself. Lemme do that.

**Pull request merged**
