### PR TITLE
More syringe guns

### PR DESCRIPTION
**Pull request by Isy232**
## About The Pull Request

Adds syringe guns to chemical closets, adds a few syringe guns in other places.

## Why It's Good For The Game

On metastation before this update there were 3 syringe guns on the station, 2 in medbay, 1 in maintenance.
However pubby only had 1 in medbay, for the whole station. (Unless I'm not seeing anything, but I've spent a lot of time looking before). So not even both chemists can have one.
This PR adds 2 more syringe guns to pubby, one in medical maintenance and one on another table in medbay.
This PR also adds syringe guns to chemistry closets (and one was added to the medical closet on delta, not to all medical closets though).
This should bring the total for syringe guns on each station to 4, enough for both chemists with 2 to spare if the CMO wants one or someone is promoted to chemistry. You might even have a spare to give to a nice security officer loaded with some sleepy chems.

## Changelog
:cl:
tweak: Syringe guns can now be found in chemistry lockers.
tweak: Added 2 syringe guns to pubby, one to maintenance and one to medbay.
tweak: Added A syringe gun to the medical closet in chemistry on delta because delta lacks a chemistry closet.
/:cl:

### CODE REVIEW

**Comment by Isy232** [comment]
Whew, broke everything, attempting to unbreak

**Comment by Isy232** [comment]
Okay, think I unbroke it, not sure why adding 2 syringe guns changed 322,514 lines of code but I've tested locally and it all works fine.

**Comment by Isy232** [comment]
Forgot map merger... ooooooohhh

**Comment by Isy232** [comment]
Everything should be fixed

**Comment by Isy232** [comment]
If you want me to not increase the number, just bring all station up to 3 I could also do that, considering meta has 3 without any changes.

**Comment by qwertyquerty** [comment]
Vote failed

**Pull request closed without merging**
