### PR TITLE
Brig Physician access change

### PR DESCRIPTION
**Pull request by bloons3**
## About The Pull Request
access is broken, brig phys needs access to their surgery table, which is placed in the Perma wing.
blame old code for not having granular area permissions
Note that this will give them access again to cell timers, as well as cell doors.

## Why It's Good For The Game
- brig phys having a surgical area is good

## Changelog
:cl:
add: brigphys gets their access back
/:cl:

### CODE REVIEW

**Comment by bloons3** [comment]
Closed https://github.com/BeeStation/BeeStation-Hornet/pull/3605

**Comment by bloons3** [comment]
> They already get brig access, PR is redundant and will not change anything. Perma doors use a different access (security or prison wing access)

Brig doors are 63, ACCESS_SEC_DOORS. Phys kept that in #3561

However, Permabrig doors are 2, ACCESS_BRIG.
Hope this won't lead to BrigPhys acting as Security, but it's better than them not having access to their resources while door permissions are reworked.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by utilbird** [comment]
Just reduce the access requirements for the doors going into surgery

**Comment by bloons3** [comment]
> Just reduce the access requirements for the doors going into surgery

I could just add Brig Phys to those doors with their permission node ACCESS_BRIGPHYS, but that feels... sketchy.

I don't mind giving them a little bit more leeway while permissions being about as granular as a rock gets worked on.

**Comment by utilbird** [comment]
> but that feels... sketchy

You'll get used to it 😆

> I don't mind giving them a little bit more leeway while permissions being about as granular as a rock gets worked on.

I suppose, but with timing/cell access they can essentially do security's job again, they still have a deputy belt in their locker iirc

**Comment by bloons3** [comment]
Will bug TG mappers about their permission granularities.

Brig Phys needs access to these general doors, + Cell access on all maps TODO
image

**Pull request closed without merging**
