### PR TITLE
Newfood: Part 1 of 4

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports:
- https://github.com/tgstation/tgstation/pull/49192
- https://github.com/tgstation/tgstation/pull/53047
- https://github.com/tgstation/tgstation/pull/53225
- https://github.com/tgstation/tgstation/pull/53316
- https://github.com/tgstation/tgstation/pull/53574
- https://github.com/tgstation/tgstation/pull/66257
- https://github.com/tgstation/tgstation/pull/69095
- https://github.com/tgstation/tgstation/pull/71449(we dont have screentips, but the sliceable in this pr is SO much better jfc)

## About The Pull Request
- This is Part 1 of newfood. This is basically the foundational newfood shit that's needed for the rest of the system we want to work. 

- Part 2 will complete all the foundational shit (killing oldfood), with some minor refactors to ready cooking for the upcoming features. This will conclude the development of the edible component and things left in limbo from part 1. Custom food will likely be partly nonfunctional until all the machines are added in part 3.

- Part 3 will contain the cooking features (Griddle, Oven, etc...). It will remove the temporary vars and procs, and customizable food will be fully reenabled.

- Part 4 will change over our icons entirely (with spritetainer and maint approval). Pigeon keeps messaging me about how excited he is for pickle rick.

INCLUDED IN PART 1:
- convert bread to newfood
- convert spaghetti to newfood
- convert cake to newfood
- Adds Dunkable element, which lets you dunk small foods into beakers or bowls (like a chicken nugget)
- Cleaned up the edible component. It should be a lot more consistent going forward, and will basically be completely functional as of part 2's merge.
- Adds Food Storage component, which lets you hide small items in large food. (Stick a shard of glass inside a cake to fuck over someone.)
- Adds FOOD_FINGER_FOOD food flag, which lets you eat food whilst moving. It applies to small food that really shouldnt take your full concentration to consume whilst walking, like lollipops!
- Sets PRAGMATIC weights for as many foods as I could. Seriously this sucked really bad. candycorn and cakes are not the same ducking size.
- food trash is sane, stuff thats clearly eaten on a plate and has a plate underneath it, will spawn a plate rubbish when completely eaten. (you dont eat the plate on cake any more smh)
- Begins the framework of something called Accidental Consumption. Its basically if you end up eating non-food related it will cause you differing effects. This is again very early stages, and will require wounds, full newfood implementation, and bringing over tg's stomach metabolism. The proc exists, but its not getting called until part 2 or 3 is merged. 

## Why It's Good For The Game
Bee's cooking system is falling behind and needs a refresher in the back and front.

Maints said they wanted this. Players said they wanted this.

Its time to take the leap.

No, I cant atomize this more than it is without it being a disaster (which is partly the reason why this has taken a long time to be ported imo)

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Bakin
baking

le cake
a cake

Pound that cake
poundcake

poundcakers

Dunkers
dunkers

dunkers22

Video
https://discord.com/channels/427337870844362753/565330972707651584/1101511988376522762

</details>

## Changelog
:cl: Rkz, Time-Green, SteelSlayer, floyd, Qustinuus, ArcaneDefence, FlowerCuco
add: Food storage! Hide some glass in the captains cake! Fuck his digestive system!!! (Not really, accidental consumption isnt active w/o wounds or stomach refactor, so It doesnt do anything yet lmao)
add: Bread, Cake and Spaghetti to Newfood
add: dunkable element. Dunk yo nuggies in the ketchup.
add: some smaller foods can now be eaten whilst on the run! (This ONLY applies to newfood items thus far!)
add: converted edible component to work with newfood
del: oldfood for Bread, Cake and Spaghetti
tweak: edited a few messed up values
tweak: food trash is sensible now. Finishing stuff like cake will actually spawn a plate rubbish. Instead of you eating the plate, fatso, perhaps properly dispose of it!
fix: Wildly STUPID item weights. Candycorn and cakes are no longer the SAME size
/:cl:

### CODE REVIEW

**Comment by Pirill** [comment]
As a big fan of TG's system, I'm excited to see this brought up. Good luck with the rest of it!

**Comment by Tsar-Salat** [comment]
Needs #8676 for some minor stupid list stuff

**Comment by Tsar-Salat** [comment]
Okay, so all of the features seem to be doing whats expected.

Except for one.
Processable seems to be nonfunctional, ill see if I can get it working

**Comment by Tsar-Salat** [comment]
> Processable seems to be nonfunctional, ill see if I can get it working

It works.

**Comment by Tsar-Salat** [comment]
alright, so apparentely there were issues with microwaves and reagent transfers, this should fix them.

It develops newfood part 1 a little more than I would like, but not much I can do about that.

**Comment by Tsar-Salat** [comment]
fuck

**Comment by PowerfulBacon** [comment]
TM updated. Are there any other issues identified with this during TM that need fixing?

**Comment by Tsar-Salat** [comment]
> TM updated. Are there any other issues identified with this during TM that need fixing?

Thus far, only the pasta duplication. That issue is still unresolved and will require the microwave fix.

The microwave fix splits microwave_act from newfood into its own component and seems to work fine, I just need to make sure it doesnt cause any further issues with oldfood. (just seems to be an unavoidable runtime atm due to snacks.dm)

Otherwise, from watching ingame and asking cook players, Ive seen no other issues.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by Tsar-Salat** [comment]
Shit.

I guess I will include the fix in Newfood pt 2 then

**Pull request merged**
