### PR TITLE
Enables map rotation, turns off auto map vote

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request

Maps will randomly rotate between rounds, instead of our current, flawed system. Maps in the pool depends on server pop. 

## Why It's Good For The Game
This will freshen up the stale status quo, as everyone tends to vote for a single map they are used to, instead of branching out. Which is lame.

## Changelog
:cl:
config: Map rotation yeaaaah
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
@Crossedfall why does the sage config not have auto map vote stuff?

**Comment by qwertyquerty** [comment]
@Crossedfall ?

**Comment by Crossedfall** [comment]
It does, you just didn't look hard enough @qwertyquerty

**Comment by Crossedfall** [comment]
I'll move it to make things more obvious though. But really. CTRL+F my man. 

#1133

**Comment by hotimep** [comment]
finally an end to the hivemind that only votes for metastation holy shit

**Comment by qwertyquerty** [comment]
@zeskorion you didn't turn off automapvote on sage

**Comment by zeskorion** [comment]
> @zeskorion you didn't turn off automapvote on sage

now i did

**Comment by qwertyquerty** [comment]
Fix conflicts

**Review by Crossedfall — APPROVED** [review]
For my part this is all fine. Vote looks to have passed, so I'm going to go ahead and apply this.

**Pull request merged**
