### PR TITLE
Fixes away mission map not loading

### PR DESCRIPTION
**Pull request by OceanFish1**
## About The Pull Request

Read title, also fixed missing subtype someone deleted also added asteroid platings outside the mission to not ruin the immersion for people that using mesons. Also lowered amount of monkeys on the monke engine.

## Why It's Good For The Game

fix good

## Changelog
:cl:
fix: fixed The Factory not loading.
/:cl:

### CODE REVIEW

**Comment by OceanFish1** [comment]
This is a certified mapper moment

**Comment by park66665** [comment]
`/obj/item/soundsynth` is at base game.

**Comment by OceanFish1** [comment]
> `/obj/item/soundsynth` is at base game.

I know but when someone deleted the "ancient" code they didn't delete it from the mission
I mean the map

**Comment by park66665** [comment]
> I know but when someone deleted the "ancient" code they didn't delete it from the mission
I mean the map

Bacon *did*. Did you read the PR: #3576?

**Comment by OceanFish1** [comment]
> > I know but when someone deleted the "ancient" code they didn't delete it from the mission
> > I mean the map
> 
> Bacon _did_. Did you read the PR: #3576?

I see, but I still need to replace it with something in the map or else the universe would get even more broken

**Comment by park66665** [comment]
The away mission currently (i.e. master branch) loads without error. You obviously can remove the soundsynth, but you should know that `/obj/item/soundsynth` isn't and can't be a cause of your unreported error.

**Comment by OceanFish1** [comment]
> The away mission currently (i.e. master branch) loads without error. You obviously can remove the soundsynth, but you should know that `/obj/item/soundsynth` isn't and can't be a cause of your unreported error.

I mean there was a place where ancient sound synth was placed. Then bacon removed ancient synth from the code, but it still remained on the level and I thought it will cause errors. I replaced it with something else and also (I hope) fixed the actual thing why map wasn't loading properly. At least it worked for me last time I tested it.

**Pull request closed without merging**
