### PR TITLE
Rebalances Rubbershot, Beanbag Slugs, .38 Rubber, and 4.6x30mm (WT-550) Rubber Ammunition

### PR DESCRIPTION
**Pull request by VickiMorris**
## About The Pull Request

12ga Rubbershot now fires in a cone of 15 degrees instead of 20
12ga Rubbershot now deals 54 damage (12 brute 42 stamina) pointblank instead of 72 damage (18 brute 54 stamina)
12ga Rubbershot damage drop-off reworked & now *much* lower, higher ricochet chance and angle, and additional ricochet.
Adds -20 AP

.38 Rubber deals 34 damage (7 brute 27 stamina) down from 40 damage (10 brute 30 stamina), reduces negative AP (-15 instead of -30)
Reduces number of ricochets to 5 (down from 6)
Decreases ricochet damage decay to 10% (down from 20%)

Brings WT rubber shot closer in-line with all other rubber ammo;
22 damage (4 brute 18 stamina) per shot (instead of flat 20 stamina)
2 Max ricochets w/ high chance and low decay. No ricochet autoaim.
Adds -15 AP

Tweaks 12ga Beanbag Slug damage, 10 brute and 50 stamina instead of 5 brute and 55 stamina (still 60 damage total).
Adds -20 AP

## Why It's Good For The Game

In regards to riot shotgun's rubbershot and the detective's .38 rubber ammunition, they have *absurdly* high damage compared to their very-lethal counterparts. While they are very mildly counter-balanced by harsher spread and damage drop-off for rubbershot, and negative armor pen for .38 rubber, they should be reigned in from their current state.

As for the changes to the WT-550's ammo, it is the *only* type of legitimate *non-lethal* ballistic ammo in the game compared to all of the other types of rubber ammunition which is merely *less-than-lethal.* Despite that weird quirk, it remains an armory only gun and in a rules-y grey area on green alert when it does legitimately function the same as a disabler. This instead brings it in-line with every other rubbershot ammunition in the game, while also buffing it with *very slightly* higher damage, and the ability to ricochet bullets.

The increase of brute damage to beanbag slugs makes them a bit harsher for the bartender, and should be a good lasting reminder to the crew to avoid jumping the counter while they're on staff. This also puts them closer in-line to the brute damage of the other ammo types while stam-critting a target.

Overall, the negative AP makes less-than-lethal ammunition much better for dealing with unarmored crew, and lets them retain higher damage within each of their ammo types. This will be especially apparent if lethal shotgun damage is reigned in further to prevent them from 2-shotting players.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
I got kinda carried away with this video uhhhh sorry!

https://github.com/BeeStation/BeeStation-Hornet/assets/97719613/d78aac53-7a6a-4d76-a3a4-64e7d870271d

</details>

## Changelog
:cl: Impish_Delights
balance: Lower damage for Shotgun Rubbershot (54 PB down from 72 PB). Additional pellet ricochets, slightly reduced spread, damage drop-off now equal to buckshot. Adds -20 AP.
balance: Beanbag Slugs now deal 10 brute and 50 stamina, instead of 5 brute and 55 stamina. Adds -20 AP.
balance: Lower damage for .38 rubber (34 down from 40). 1 less possible ricochet, reduced damage decay from ricochet. Reduces negative AP to -15 (from -30).
balance: WT-550 rubber bullets are now less-than-lethal (4 brute + 18 stamina) and ricochet similar to other rubber ballistic rounds. Adds -20 AP.
/:cl:

### CODE REVIEW

**Comment by Nakalon** [comment]
So the barman wont be able to 2 shot people into crit anymore, right?

**Comment by VickiMorris** [comment]
> So the barman wont be able to 2 shot people into crit anymore, right?

I haven't touched bean-bag slugs for this at all, they still do 55 stamina and 5 brute. I may look into tweaking it though.

**Comment by Rukofamicom** [comment]
While I think negative AP is pretty ludicrous on most things, I think rubbershot is one of the things that it actually makes a lot of sense on and mechanically works out well for. 

Would you consider giving rubbershot negative AP so armor heavily mitigates them?

**Comment by VickiMorris** [comment]
My main gripe is making rubber ammo have similar damage to lethal ammo with negative AP would see the minor use of it disappear completely. I'll toy around with some values after work today and see if I can get it feeling good.

I am also split on balancing this towards the current level of shotgun lethal round, or towards the numbers that Bacon has pitched in his rebalance PR under the assumption that gets approved.

**Comment by Rukofamicom** [comment]
I like the numbers I'm looking at now, I think this puts them in a good spot for both realism and gameplay - easily mitigated but still fairly strong against zero protection.

**Review by Rukofamicom — APPROVED** [review]
That was supposed to be an approval

**Comment by Rukofamicom** [comment]
Secondary glance from Bacon so merging now

**Pull request merged**
