### PR TITLE
Replaces PTSD with service/officer pistols

### PR DESCRIPTION
**Pull request by PowerfulBacon**
TODO:
- Custom sprite for the ammo clips
- Ability to obtain more ammo clips without stealing from other heads?

## About The Pull Request

Replaces the PTSDs that heads get with service pistols. The sprite is based on the original PTSD sprite with heavy modifications, a stripe to indicate who the weapon belongs to and a more standardised colour palette.

image

image

image

Weapon stats:
- 10 burn (10-12 shots), 18 stamina damage (6-7 shots) (combined, note that 28 damage may seem like a lot, but stamina and damage crits are distinct).
- 10 round magazine which can be recharged at a weapons recharger, keeping multiple magazines allows you to reload without recharging.
- 2.5 shots per second (4 deci-second firerate)

Additional changes:
- Service pistol will always spawn in the head's locker rather than on them (in the case of captain and HOS).
- HOS spawns with a disabler instead of the PTSD.

## Why It's Good For The Game

Reasons why I dislike the PTSD:
- Almost useless as a lethal weapon due to low ammo capacity.
- Incredibly long reload times also make it pretty ineffective as a self-defense tool
- Intended to be used for self-defense only, but fires rounds which deal no damage encouraging fire-first discuss later.

The self defense weapon for heads of staff should be useful in self-defense, but also be specifically designed to be a self-defense tool. Firing rounds which will do some lethal damage on top of the stamina damage forces heads to actually try other methods of getting people to leave before going straight to 'fire disabler'.

With a disabler capable pistol, all procedures boil down to shoot first.
If someone is breaking into your department, you disable them and throw them out or just fire the shots directly at them without saying them.
If someone is attacking you, you fire non-damaging shots at them.
If a simple-animal is attacking you, you fire 5 shots before running out of ammo and do almost nothing.

This new design of using less-lethal rounds instead of non-lethal rounds requires heads to at least consider talking to a target before shooting them, and if it comes to shooting them then their target is going to need to seek medical attention after the fact. With some lethal damage being dealt on top of the stamina damage, you may have to use the aiming mechanics and hold someone at gunpoint. Either way, there are a lot more ways to handle a situation when less-lethal weapons are used compared to when weapons with no consequences what-so-ever are being used and I think that this kind of design should be paramount for a tool designed strictly to serve the role of self-defense.

## Testing Photographs and Procedure

image

image

## Changelog
:cl:
balance: Replaces PTSDs with service pistols, a less-lethal officer's pistol that fires rounds which burn and disable a target simultaneously. It has 10 shots and is reloaded via a magazine that can be recharged.
fix: Fixes weapon rechargers not showing the charge amount of inserted rechargable magazines.
/:cl:

### CODE REVIEW

**Comment by TsunamiAnt** [comment]
I absolutely adore this, but can we have the stripes a bit more clearly distinct?

**Comment by Tsar-Salat** [comment]
I like the idea and the icon sprites.

I think the inhand and magazine sprites need some work though. You can barely see the inhand and it just looks like a stick.

**Comment by PowerfulBacon** [comment]
The magazine sprite hasn't been updated yet and the gun sprite is the sprite used for all non-energy guns. I can spend some time to sprite them

**Comment by ColonelOrion** [comment]
Looks like a fallout alien pistol. Very cute, but seems like something that should be in the hands of abductors rather than NT staff.
The mechanical concept is really needed IMO, though I'd like to hear @Rukofamicom 's take on this after seeing him defend the PTSD in the past.

**Comment by PowerfulBacon** [comment]
image

Magazine added

**Comment by Rukofamicom** [comment]
As the person who actually implemented PTSD from the lost content pile, I approve of this change.

I do think they recharge plenty fast enough for self defense personałly though.

**Comment by Tsar-Salat** [comment]
> Looks like a fallout alien pisto

I don't think so. It looks more like fallout 3 plasma pistol to me imo.

Still cool

**Comment by MarkusLarsson421** [comment]
The soul of the PTSD though! Not gonna lie, I don't like the new sprite, but it'll grow on me. It looks like a weird grainy and HD version of the alien position.

**Comment by PowerfulBacon** [comment]
Not sure what happened to the energy gun sprite

**Comment by PowerfulBacon** [comment]
I'm yolomerging this to see the result

**Review by Rukofamicom — APPROVED** [review]

**Pull request merged**
