### PR TITLE
makes operating computers shows surgery procedures on stasis tables

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

see title

## Changelog
:cl:
fix: operating computers now correctly show surgery procedures on stasis beds
/:cl:

### CODE REVIEW

**Comment by jupyterkat** [comment]
REEEEEEE ELON

**Comment by utilbird** [comment]
what'd I do

**Comment by utilbird** [comment]
holodeck PR is causing errors on master, without any errors on the PR. HMM

**Comment by jupyterkat** [comment]
image

**Comment by jupyterkat** [comment]
espee deleted the description var and added it at the same time

**Review by utilbird — APPROVED** [review]

**Pull request merged**
