### PR TITLE
Removes the ability for the plasmacutter to delimb

### PR DESCRIPTION
**Pull request by JixS4v**
## About The Pull Request

What it says on the tin

## Why It's Good For The Game

I've only ever seen this abused by miners to validhunt, as delimbing is extremely powerful in combat. It's plain unfair. It's expressed purpose (mining/killing xenos) is never what it's used for. There's many better tools to kill xenos. 

## Testing Procedure

1. Shoot someone repeatedly
2. Observe limbs don't fall off

## Changelog
:cl:
tweak: plasma cutters will no longer delimb
/:cl:

### CODE REVIEW

**Comment by JixS4v** [comment]
For perspective, miners aren't even fighting limbed enemies in their work. This ability is almost exclusively used against other players.

**Comment by Howluinb** [comment]
ided

(good pr)

**Comment by PowerfulBacon** [comment]
I don't mind this, every PR made in the name of stopping validhunters hurts the non-uplink antagonists and limits their options on how they can act.

**Comment by JixS4v** [comment]
> I don't mind this, every PR made in the name of stopping validhunters hurts the non-uplink antagonists and limits their options on how they can act.

Miners already get plenty of options to fight, easy remote delimbing doesn't need to be one of them

**Comment by ColonelOrion** [comment]
In case anyone doesn't get the reference:
cut_off_their_limbs_by_donuttk421-d5yoexg-2498058047

**Comment by JixS4v** [comment]
> In case anyone doesn't get the reference: cut_off_their_limbs_by_donuttk421-d5yoexg-2498058047
> 
> (Dead space)

Yeah sure, it's a dead space reference but if it's detrimental to gameplay i don't think this should be factored in.

**Comment by MarkusLarsson421** [comment]
Perhaps it was left in as a Syndicate upgrade to the plasma cutter?

**Comment by JixS4v** [comment]
> Perhaps it was left in as a Syndicate upgrade to the plasma cutter?

Don't think plasma cutters have upgrades, but i could totally make a miner-only uplink item plasmacutter that delimbs

**Comment by AnCopper** [comment]
> > Perhaps it was left in as a Syndicate upgrade to the plasma cutter?
> 
> Don't think plasma cutters have upgrades, but i could totally make a miner-only uplink item plasmacutter that delimbs

This is just going to be another uplink item like the PKA damage module that nobody will ever use.

**Comment by MarkusLarsson421** [comment]
> This is just going to be another uplink item like the PKA damage module that nobody will ever use.

What if it was another emag upgrade for the PKA?

**Comment by PowerfulBacon** [comment]
I dislike uplink upgrades in this capacity, antagonists with no uplinks should have options to be able to perform nefarious deeds on the station based on what they can access with their job role and a bit of creativity.

**Comment by PowerfulBacon** [comment]
I see no reason to remove this feature, it's powerful but its use in combat is somewhat limited due to the short range and armours protecting antags. When we start to see this being used in unfair ways in-game as a prevalent thing then I'll consider it.

**Pull request closed without merging**
