### PR TITLE
Reverts slowdown slot changes

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
Reverts the change that makes slowing equipment slow you even when being carried, as well as the changes to slowdown in anti-gravity
## Why It's Good For The Game

This wasn't the right fix for the tactical equipment removal issue, and it was buggy as all shit. My suggestion, if this is REALLY that bad an issue that needs to be fixed, is to add a timer to applying and removing such equipment

additionaly, the gravity slowdown affects you even without magboots, and whilst wearing a jetpack to boot- which it definitely should not
## Changelog
:cl:

del: reverts slowdown changes
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
ugh why was this a bulk port instead of atomizing i cant just revert the changes in the original PR without breaking shit.

**Comment by zeskorion** [comment]
alright, tested, it's workin good, you no longer get slowed down WHILST USING A JETPACK, IN SPACE...

**Comment by qwertyquerty** [comment]
Don't want to code a solution?

Improve don't remove moment

**Comment by zeskorion** [comment]
> Don't want to code a solution?
> 
> Improve don't remove moment

I dislike the change to begin with, and it was merged as a part of a mass pr instead of a single vote. The buggy-ass side effect of being slowed down in space at all times is just icing on the cake

**Comment by VictorVow** [comment]
This addition has been extremely buggy. Many times for no reason at all I've seen people's speed be reduced by 90%, and even removing all clothes and items doesn't fix it. Other times you'll put on a spacesuit and for a minute or two still be sprinting. Or you might throw away that suit after you've been slowed and you still remain slowed. Remove it all until it can be added in a way that isn't a buggy mess.

**Comment by MCterra10** [comment]
Bro you malformed your changelog bro and it broke the webhook

**Pull request merged**
