### PR TITLE
Fixes missing cable and areas on MetaStation

### PR DESCRIPTION
**Pull request by Cenrus**
replaces cable going into medical storage

### CODE REVIEW

**Comment by 123chess456** [comment]
Why did you remove the cool bedsheet in the maint near security?

**Comment by Cenrus** [comment]
the light is creates was shining through the wall.

**Comment by 123chess456** [comment]
Atomize your changes. You shouldn't be making undocumented changes to maint in a PR meant for adding a single wire.

**Comment by qwertyquerty** [comment]
Agreed, atomize your pr

**Pull request closed without merging**
