### PR TITLE
Savefile Migration to DB

### PR DESCRIPTION
**Pull request by MCterra10**
# About the PR
Moves savefiles for player preferences and loadouts into the database, as well as slightly improves some older prefs code

Sidenote: AffectedArc PR credits removed, as I ended up going in a completely different direction for implementing this (JSON blobs), making the only thing used from para the savefile toggle sanity check, which is so tiny there's no point. I'll give him a co-commit credit instead.

# Why it's good for the game
Easier save fixing/modification for sysadmins, easier save sharing between servers without messy symlinks

# Progress
- [x] Update the toggles to include all prefs booleans instead of just a few
- [x] Integrate snowflake pAI savefiles into the standard preferences system
- [x] Implement JSON (de)serialisation for savefiles and characters
- [ ] JSON savefiles
- [ ] JSON DB saves
- [ ] Create migration script
- [ ] Add a savefile freeze option to prevent savefiles changing during copy on live servers

# Changelog
:cl: MCterra10
sql: moves savefiles to the database
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
wait wrong repo lol
this was meant to go to my fork for testing

**Comment by MCterra10** [comment]
eh whatever I'll just leave it open as a draft

**Comment by ike709** [comment]
OwO

**Comment by ike709** [comment]
TIL how cursed pAI's preference code was.

**Comment by MCterra10** [comment]
the migration tool is working amazing
just make sure not to run it on the actual savefiles, since in the process of performing savefile updates it only partially modifies the savefiles, since I never saved the files fully for performance reasons. basically it nulls out some fields, namely pAI details in the savefiles themselves. it doesn't impact the integrity of copied data though.

I'll probably tweak this anyway to make sure it doesn't change the savefiles themselves

**Comment by MCterra10** [comment]
ckeys
ckeys censored for privacy

**Comment by MCterra10** [comment]
honestly some things here could just be moved off to the client rather than being in the prefs datum

**Comment by MCterra10** [comment]
whoops, git moment

**Comment by MCterra10** [comment]
savefile migration coming 2023 :trollface: 
coming soon though, when I am motivated

**Pull request closed without merging**
