### PR TITLE
fixes a typo in teslacode

### PR DESCRIPTION
**Pull request by MNarath1**
## About The Pull Request
This is a small error i discovered months ago together with KubeRoot when looking on how to optimize tesla code appearently the original coder copy pasted his code and forgot to change this accordingly and  cause it technically never really showed much difference during tests no one ever actually found this probably for quite some years as it technically never made much of a difference except for possible performance problems as the code execution won't stop as intended at this point.

## Why It's Good For The Game
Less Code exectution in a very laggy code is always better
## Changelog
:cl:
fix: small misstype from tesla code
/:cl:

### CODE REVIEW

**Comment by MNarath1** [comment]
Also this is technically untested but i do not expect much problems with a one line change like this especially cause it fixes an obvious typo.
About my ideas to improve tesla performance... well i am still working on that but i figured i might as well put  this out now just in case i don't finish the other project.

**Comment by MNarath1** [comment]
gotta love when checks fail randomly just  to be fine after rerunning them.
And of course it still shows the commit as failed even trough the checks went trough the second time....

**Comment by KubeRoot** [comment]
> gotta love when checks fail randomly just to be fine after rerunning them.

I looked at what the failure was, and get this: it was pun-pun trying to interact with a vending machine and getting a runtime in tgui trying to read its preferences:
```
[13:43:06] Runtime in tgui.dm,54: Cannot read null.prefs
  proc name: New (/datum/tgui/New)
  src: /datum/tgui (/datum/tgui)
  call stack:
  /datum/tgui (/datum/tgui): New(Pun Pun (/mob/living/carbon/monkey/punpun), the Booze-O-Mat (/obj/machinery/vending/boozeomat), "Vending", null, null, null)
```

**Comment by MNarath1** [comment]
> 
> 
> > gotta love when checks fail randomly just to be fine after rerunning them.
> 
> I looked at what the failure was, and get this: it was pun-pun trying to interact with a vending machine and getting a runtime in tgui trying to read its preferences:
> 
> ```
> [13:43:06] Runtime in tgui.dm,54: Cannot read null.prefs
>   proc name: New (/datum/tgui/New)
>   src: /datum/tgui (/datum/tgui)
>   call stack:
>   /datum/tgui (/datum/tgui): New(Pun Pun (/mob/living/carbon/monkey/punpun), the Booze-O-Mat (/obj/machinery/vending/boozeomat), "Vending", null, null, null)
> ```

oh my god thats hillarious on its own.

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
