### PR TITLE
adds a wall of hyperspace around centcom and the recovery ship.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

adds a barrier around CC/recovery ship that once you cross teleports you off the z level to a random space z level.

## Why It's Good For The Game

so you cant traverse the entire z level, you are not intended to do this in the first place so it's more or less a bug fix.

## Changelog
:cl:
tweak: Nanotrasen has added a wall of bluespace around Central Command and Recovery Ships as a layer of extra security. 
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
image
In-game the barrier is not a ugly black box, it looks like just any other space tile.

**Comment by ghost** [comment]
and yes i tested this.

**Comment by ghost** [comment]
booooo fun hater

**Comment by ghost** [comment]
> booooo fun hater

it is my obligation to remove fun.

**Comment by zeskorion** [comment]
can you add one to syndiebase while you're at it? hell, put it around everythin

**Comment by Kerbin-Fiber** [comment]
There goes me being able to use zlevel 1 to spawn in miscellaneous rooms due to invisible teleport barriers.

**Comment by PowerfulBacon** [comment]
All of the rooms use indestructible walls anyway if anyone could get past the 1 thick indestructable walls they will be able to get past a 1 thick wall of hyperspace.

**Comment by PowerfulBacon** [comment]
> 
> 
> There goes me being able to use zlevel 1 to spawn in miscellaneous rooms due to invisible teleport barriers.

The ground turfs of your room would overright the hyperspace floors since they are a turf like space.

**Comment by francinum** [comment]
Time to take the goon approach of invincible instakill walls.

**Pull request closed without merging**
