### PR TITLE
Substantially nerfs maltodextrin

### PR DESCRIPTION
**Pull request by Rukofamicom**
## About The Pull Request

* Nerfs maltodextrin's effect substantially so that it now matches nutriment 1:1 in terms of nutrition taken away, instead of being nearly twice as potent and causing all foods containing it to make players **substantially** hungrier than before they ate. 

* Adjusts the amount of maltodextrin in junk foods so that it will perfectly cancel out sugar, nutriment and hot ramen. Other consumable reagents (with a nutrition power of only 1) were not taken into account so the maltodextrin will not quite cancel out the entirety of nutrition, just the majority of it.   

* Maltodextrin's negative effects are now applied gradually over time instead of all at once - this means players will no longer experience sudden starvation, and in the case of some races, sudden death.

## Why It's Good For The Game

Maltodextrin was a good concept, sold as allowing foods to temporarily make players feel full, but making the foods it contains less desirable than chef food. Unfortunately its current balance made these foods not just less desirable, but outright harmful to consume, and in such a way that results in crippling starvation out of nowhere. 

These adjustments reign maltodextrin in so that it behaves more like it was intended to - discouraging people from eating only junk food by making them short term solutions to hunger rather than long-term, but not outright bad to eat. They will provide temporary satiation and players will experience hunger sooner after eating them than they may expect, but they won't be shocked by sudden starvation. 

## Testing Photographs and Procedure

dreamseeker_qmCxwLFcXM

After Maltodextrin was fully processed (+ a little extra time because I wasn't paying close attention to it)

image

## Changelog
:cl:
balance: Maltodextrin's overall power has been substantially reduced. When fully processed, maltodextrin will leave you with about the same hunger you had before eating junk food instead of substantially hungrier than you were before eating.
tweak: Maltodextrin's effect is now gradual instead of instantaneous and players should no longer experience sudden, crippling starvation as a result. 
tweak: The amount of maltodextrin in junk foods has been adjusted in accordance with the above changes.
/:cl:

### CODE REVIEW

**Comment by DarnTheMarn** [comment]
Making maltodextrin act over time was the way I intended to have it act originally, but due to the small quantities of it in food I wasn't able to tweak it just right due to the fast metabolization of small amounts of chems.

**Comment by Harranhall** [comment]
I'm sure we'll get good feedback on if this is acceptable longer term for the playerbase, and after the previous iteration I'm sure they'll be a little more accepting of this version of maltodex.
Not against the idea of maltrodextrin tbh, the implementation just went way too far.
@DarnTheMarn any chance you could put the donuts back in the sec vendor? That was a really sucky change imo.

**Comment by DarnTheMarn** [comment]
>any chance you could put the donuts back in the sec vendor? That was a really sucky change imo.

I don't see the need, if you want healing, ask the person whose entire job is to heal you, go to medbay like the rest of crew, or ask the bartender for quadsec. All of those involve interaction and are not subject to nerfs like donks and donuts.

**Comment by Rukofamicom** [comment]
> I don't see the need, if you want healing, ask the person whose entire job is to heal you, go to medbay like the rest of crew, or ask the bartender for quadsec. All of those involve interaction and are not subject to nerfs like donks and donuts.

I did directly ask for it in your PR as well, it just got merged yolo style without my comments on mapping being addressed first lol

I really don't like doing mapping, but I would like to see donuts back in sec again. The healing they provide can be nerfed alongside this if necessary because I do agree they shouldn't be chomping donuts like combat stims.

**Comment by DarnTheMarn** [comment]
> The healing they provide can be nerfed alongside this if necessary because I do agree they shouldn't be chomping donuts like combat stims, just some minor passive healing.

The problem is without changing the insane amount of donuts that spawn, any changes to the amount of healing donuts give could be circumvented by just eating more. After all, nutritionally they are 0 value with this change and negative value without it so being fat is only temporary.

**Comment by DarnTheMarn** [comment]
Or you could make it heal below a certain threshold like you did with healing chems that'd work too

**Comment by Rukofamicom** [comment]
You underestimate my capability to balance reagents. 

image

**Comment by Rukofamicom** [comment]
yes, metabolites were what I had in mind. 

Heals a bit and then stops working unless you haven't had a donut in a while.

**Comment by DarnTheMarn** [comment]
It does loop back over to the problem with the self-tending changes. If you just keep up with it each time you get hurt, it never affects you. Eat a donut, sip some quadsec, slap on a patch, there you go fit as a fiddle without going to medbay even with any nerfs

**Comment by zeskorion** [comment]
making maltodextrin directly reduce nutrition is a very odd choice. 

I'd like to propose making it work a different way.

make it work like a nutrient, almost replacing nutriment, and count the amount of nutrient it adds as it adds it. After a certain amount of time, or at the end of processing, it removes nutrient, but no more nutrient than it gave you. similar to amatoxin

**Comment by Rukofamicom** [comment]
> make it work like a nutrient, almost replacing nutriment, and count the amount of nutrient it adds as it adds it. After a certain amount of time, or at the end of processing, it removes nutrient, but no more nutrient than it gave you. similar to amatoxin

That's quite close to how it works now and will result in the same issue as now - players are abruptly starving for seemingly no reason when it expires.

**Comment by zeskorion** [comment]
> > make it work like a nutrient, almost replacing nutriment, and count the amount of nutrient it adds as it adds it. After a certain amount of time, or at the end of processing, it removes nutrient, but no more nutrient than it gave you. similar to amatoxin
> 
> That's quite close to how it works now and will result in the same issue as now - players are abruptly starving for seemingly no reason when it expires.

I have a different idea then

make it hide the hunger alert and replace the moodlet

**Comment by Fronsis** [comment]
> I did directly ask for it in your PR as well, it just got merged yolo style without my comments on mapping being addressed first lol
Yeah i mentioned that day 1, i believe Bacon just surpassed Pigeon approval in the map change and thenit got merged

Both the revert and this one sounds good, if the donuts are back where they belong then i believe it will be in a better state, as for oozelings i think this change will also be benefitial as you said today on the discord ping so no complains on that side

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
