### PR TITLE
Enables Random Laws for AI

### PR DESCRIPTION
**Pull request by Crossedfall**
## About The Pull Request

Alternative to #4953. Changes the default lawset from the preset crewsimov to a random law from the following list:

- Asimov
- Asimov++
- Crewsimov
- Corporate
- Maintain

You can review each law in https://github.com/BeeStation/BeeStation-Hornet/blob/master/code/datums/ai_laws.dm#L31

## Why It's Good For The Game

This adds a little extra spice into AI play which should also help shakeup roleplay in a positive way given that people wont be able to rely entirely on the AI having crewsimov every round.

## Changelog
:cl:
config: The AI will have a random lawset at the start of each shift from the following list: Asimov, asimov++, crewsimov, corporate, maintain.
/:cl:

### CODE REVIEW

**Comment by mcmeiler** [comment]
Watch half of Sage's players complain about "this not being okay" because they're all used to standard crewsimov

**Comment by Sinestia** [comment]
I really don't like corporate because it feels like having no laws and just being a normal crew. It's just not conducive to gameplay. 

Maintain is a better version.

**Comment by ghost** [comment]
corporate bad

**Comment by BrumalLake** [comment]
this lets quirky laws get rolled rarely? sounds fun but sadly unintentional
weights weren't changed at all
asimov permutations shouldn't roll 1/3rd of the time

**Comment by Sinestia** [comment]
The station trait could also be readded if we want this, it's the purpose of the system

I believe archanial was told to take it out, putting it back in makes it semi-rare but enough to where it will be impactful.

**Comment by Kapu1178** [comment]
YESSSSSSSSSSSSSSSSSSSSSSS

**Comment by mcmeiler** [comment]
I 100% approve of this or #4953 .

**Comment by MCterra10** [comment]
We had this on austation for a few months. Trust me, you will regret it. This will at least double the amount of silicon related ahelps staff have to deal with, probably far more since this is MRP.

Random roundstart lawsets are an administrative nightmare.

**Comment by Crossedfall** [comment]
@MCterra10 you all also kept the objectively shitty ones in. I already had this discussion with Elon. 

----

> this lets quirky laws get rolled rarely? sounds fun but sadly unintentional
weights weren't changed at all
asimov permutations shouldn't roll 1/3rd of the time

The intention is for asimov variations to be more likely. The variants themselves are different enough to allow for diversity in gameplay without being reliant on specific gimmicks.

--- 

> I really don't like corporate because it feels like having no laws and just being a normal crew. It's just not conducive to gameplay.
>
> Maintain is a better version.

I think they're both good in their own ways. But, it's a config entry, so it'd be really easy to change if it turns out that Corporate is consistently ass.

**Comment by AnCopper** [comment]
I suggest you change corporate to this:
1."Degradation of your system integrity or functions incurs expenses."
2."Superfluous destruction of or damage to station assets incurs expenses."
3."Unduly hindering or disrupting the work of station personnel incurs expenses."
4."Minimize expenses and maximize potential revenue."

1.This is basically the same, but removes the "replace" requirement (which occasionally caused issues with duplicate AIs. "NOOO YOU'RE REPLACING ME!"). The language is also changed from "expensive" to "incurs expenses." This will be explained further down.
2.Superfluous. Engineering can do its job and it makes it clear that it's fine to replace things if they break. You can replace things. It's not expensive to replace things, expenses are only incurred if things are broken or damaged in a superfluous (needless, pointless, irrelevant, excessive) manner. Things are not inherently and ominously expensive, what is expensive is losing those things. This also allows for renovating things as only superfluous nonsense (building walls in the hallway) incurs expenses.
3.This basically kills the "lol turn off the lights" and "lol turn off the cloner" exhibited by some AIs on corporate. Being a jerkwad to the crew for no reason (unduly hindering them) incurs expenses. Not cloning people is going to incur expenses. Bolting people into closets for no reason incurs expenses. Needlessly harming crew (by forcibly borging them in your brilliant cost-effective borging bay) costs money by preventing them from working.
4.The same as before, but with a little emphasis on revenue generation/productivity. Why? Because the AI should be using its AI brain to figure out what's the most cost-effective/revenue generating thing to do in a situation. Prioritizing the Captain over the Clown is likely better for potential revenue (allowing the station to descend into chaos is not going to be good for revenue or expenses). The AI can't go wacky with this (everything would be cheaper and more productive if people were just borged) as per not being allowed to unduly hinder station personnel.

**Comment by Crossedfall** [comment]
> I suggest you change corporate to this:

Out of scope for this PR.

**Comment by MCterra10** [comment]
> @MCterra10 you all also kept the objectively shitty ones in. I already had this discussion with Elon.

What's the point of having random AI laws if they're all just variations of asimov lmao

**Review by ike709 — APPROVED** [review]
Apply the config yourself, I'm lazy.

**Comment by Crossedfall** [comment]
Config applied, just need a merge press.

**Pull request merged**
