### PR TITLE
Pepperball Pistol - A non-lethal ballistic sec alternative (and fix for pneumatic cannon)

### PR DESCRIPTION
**Pull request by VickiMorris**
## About The Pull Request
**TODO: Crafting/Lathe recipe for ammo, actual acquisition of gun for security officers, balancing shit.**

This adds a new non-lethal weapon as an alternative to the disabler for security (and anyone else who can get their hands on one). A pepperball pistol, more commonly known as a pepperball launcher, is essentially a pepperspray paintball gun meant to disable and disorient people. Unlike other ballistic "non-lethal" weaponary, this is truly non-lethal projectile that deals exclusively stamina damage.

Squaring it up against the disabler, it has slightly higher damage, minor negative AP, and lower capacity. It requires an air tank to function (using 0.025 mol per shot, having ~32 shots in the initially installed tank) and can work with any "emergency-sized" air tank (Emergency, Engi Extended, Engi Double, Mini Air, & Clown). However, as a ballistic gun, multiple magazines can be carried to allow reloading while on the go, and it is completely immune to EMPs.

The sprites for the mini air tank and pepperball pistol were created by me, and are derivative of the emergency oxygen tank sprite, and sec_pistol sprite respectively. The pepperball magazine sprite is a derivative of the deagle magazine sprite.

As for the pneumatic cannon, it previously would continue to fire even when the attached tank was completely empty, as the check it made simply didn't function. This was found after I checked the pneumatic cannon to see how it handled draining an attached air tank to fire objects/projectiles.

<details>
<summary>Hard numbers and comparisons.</summary>

Pepperball Pistol
---

- Magazine holds 14 pepperballs, total capacity is 14+1.
- Uses 0.025 mol per shot, draining the starting air tank in 33 shots (About 2-1/2 magazines).
- For comparison, the disabler can fire 25 shots before needing to be recharged.
- It is a NORMAL sized item when it does not have an air tank installed, becoming LARGE when there is one installed (same as the disabler).
- It can only accept emergency-sized internals tanks, which still grants an absurd shot capacity when utilizing hyper-cooled gas
- It has a fire rate of 3, currently equal to the stechkin (might be lowered to 2.5 in further testing).
- Stats are otherwise identical to the disabler with a 2 second draw time, and LIGHT weapon weight

Pepperball Projectile
---

- 35 base stamina damage (vs. 28)
- -20 Armour Penetration (vs. 0)
- 1 damage drop-off per tile (vs. 0)
- Max range of 22 tiles (vs. 50)

Mini Air Tank
---

- Volume of 1.5 | Slightly larger than emergency oxygen tank (1) but lower than extended emergency tank (2)
- Starts with 1023 kPa of air, chilled to -48.15 C / 225 K. This is about 0.81 mol of air (32.4 shots, 33 rounding up)
- It is otherwise a normal internals tank, and can be filled from canisters or portable pumps.

</details>

## Why It's Good For The Game
As the current "non-lethal" options deal brute damage of some kind, and with the changes to the WT-550 rubber rounds (which were never used even when they were wholly non-lethal due to their status as armory equipment), this adds a proper alternative to the disabler for use by security. While meant to be similar in power, swapping energy for ballistics gives it a couple niche uses-cases; it allows security to actually attempt to non-lethally detain antags with access to EMPs as well, rather than jumping straight to lethals.

As for the pneumatic cannon, stuff working properly is good.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

PP Tanks

https://github.com/BeeStation/BeeStation-Hornet/assets/97719613/ea3f4bab-45f8-4979-84cf-436e8dfa5ff4

https://github.com/BeeStation/BeeStation-Hornet/assets/97719613/15759250-5c0c-4f38-9d7f-765351dd8b0b

</details>

## Changelog
:cl: Impish_Delights
add: Non-lethal ballistic sec alternative; the Pepperball Pistol.
add: Pepperball ammunition, mini air tank, pepperball magazines.
balance: The Pneumatic Cannon actually refuses to fire when the attached tank is empty now.
imageadd: Sprites for pepperball pistol, accessories, and mini air tank.
/:cl:

### CODE REVIEW

**Comment by Nakalon** [comment]
I tried doing a Ballistic non-leahtl for sec before but decided against it.

And I don't think making it a stamina damage weapon is the way to go AT ALL.

If it is, in function, the same as the disabler people will ALWAYS use this instead of the disabler because ballistic weapons are much cooler to use.

Please consider making this different from the disabler other than being ballistic instead of energy-based.

**Comment by DarnTheMarn** [comment]
In addition to what they said above, a pepper ball pistol also just makes no sense as a disabler alternative. Namely, why would anyone get actually stunned from this? They essentially shoot solidified pepper spray. If you wear a mask you should be immune, and pepper spray itself doesn't actually stun people it just disorients them. If the stun is because of concussive force why does it only do stamina damage. I think it's a semi-intentional design choice to have ballistic non-lethal options do permanent harm to people so that the AI gets grouchy about it. 

If this wants to be balanced the magazines better be rare as hell so that you can't magdump and bypass the weakness.

**Comment by VickiMorris** [comment]
It now checks for eye and mouth protection, and does less damage respectively. Eye coverage removes the (newly added) eye blur effect and reduces the damage by 10. Mouth coverage reduces the damage by an additional 15. This means a mask will have it do 5 stamina damage total to the target with no other effects.

**Comment by DarnTheMarn** [comment]
>It now checks for eye and mouth protection, and does less damage respectively

That solves that problem and makes the gun now worthless essentially, but doesn't address that being hit with pepper balls isn't going to stun you by itself. The way I think this item would make sense is acting as a long range option for pepper spray. Meaning wherever you click, the ball shoots there and when it impacts it makes a 1x1 pepper spray cloud. This would make sense and have actual utility as its an unfilled niche right now.

**Comment by Nakalon** [comment]
Again, I will suggest you do something other than stamina damage.

Think of something to complement a disabler or other sec tools instead of being independent. Like, the disabler needs a flash or a baton for example.

My original idea was to make a tazer like weapon. That has very low firerate and mag capacity however has effects based on much stamina damage the target has.

So imagine. If you're over 80 it deals a paralyzing stun. Over 50 just makes you drop your weapon or stops you on your tracks for half a second. And over like 20 something even weaker. And under 20 it does nothing.

Just an idea, because I don't think going stamina damage is the way to go.

**Comment by VickiMorris** [comment]
I hate to be negative, and I know I'm in a brain-funk right now, but a majority of this feedback just feels like "This is a shit idea and you should scrap it and make something completely different that doesn't fill the same role," and "It doesn't make sense logically."

Why do people get stunned from disabler beams? Why do people get stunned from *riot darts*? I really don't want to just make a better version of the peppercloud deployer (something that causes knockdown, blindness, and confusion) because it has no delay and can be used at a massive range.

**Comment by Nakalon** [comment]
> I hate to be negative, and I know I'm in a brain-funk right now, but a majority of this feedback just feels like "This is a shit idea and you should scrap it and make something completely different that doesn't fill the same role," and "It doesn't make sense logically."
> 
> Why do people get stunned from disabler beams? Why do people get stunned from _riot darts_? I really don't want to just make a better version of the peppercloud deployer (something that causes knockdown, blindness, and confusion) because it has no delay and can be used at a massive range.

You must have misunderstood my feedback.

I do not disagree that for the player the best thing one could add is a ballistics disabler which is what this is.
It is in no way different since it deals stam damage except that it's ballistic.

I think that's awesome and would definitely use it exclusively.

But that's the problem.
The disabler already exists and this will replace it because unless we change energy weapons majorly ballistics will feel better and be more fun to play with.

And I think it's better you hear all this now rather than after you've spent more time on it and a maint tells you this:

"NT should use mainly utilize energy weapons, this is I'm the design document. This weapon would have the same effect as the energy based disabler, and would end up replacing it".

I'm telling you what I heart when I went down this road. I even used the same base sprite as you, although I had coloured it differently.

But I can be wrong. Ask a maint to be sure.

Don't take this the wrong way, if I didn't want this to happen I would have not given you ideas.

Cheers

**Comment by DarnTheMarn** [comment]
The way I see it is this: 

Keep it as is, with mask and eye protection checks -> It is useless and won't get used because everyone has eyewear or a mask on
Change it to a more traditional ballistic -> WTs have rubber ammo, it is  now redundant 

The disabler is a really fucking good weapon. If you add the perks ballistics have, namely reloading on the fly, it becomes bonkers good. So maybe you balance it by making people only have one or two magazines so the capacity is the same as a disabler. Well now its just a disabler reskin that is more tedious.

**Pull request closed without merging**
