### PR TITLE
Baton shove now requires disarm intent

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request
atomisation of #11169

## Why It's Good For The Game

> I heard a lot of people disliked baton shoving so making it optional probably a good idea

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

see #11169 
</details>

## Changelog
:cl:
tweak: stunbatons only shove on disarm intent
/:cl:

### CODE REVIEW

**Review by Rukofamicom — APPROVED** [review]
Considering I have heard no arguments against this from either side of the baton's usage, this seems like a fine tweak

**Review by PowerfulBacon — COMMENTED** [review]
I dislike this, I made the shove changes active on all intents on purpose for the following reasons:
- Security would have to position themselves effectively, a chaotic scenario and poor position will result in allies being knocked down.
- It's a buff to the baton's defensive use, and a nerf to the offensive capability. Introducing a tile of space after a stun baton attack makes it so that each attack of the baton by a single person is slower, lowering the DPS without needing to reduce the damage. This reduces the DPS without making it so that the survivability of the security officer is significantly impacted, since its also harder for the opponent to get a rebound attack on the user.

**Comment by DarnTheMarn** [comment]
That is all well and good. But what is the point, the tonfa bypasses all of those and manages to just be a better baton at this point. Yeah it takes a few more hits but it's EMP proof, can paralyze, can disarm, can leg break, you can get pretty much as many as you want, it's all upsides almost. The baton always pushing plus the gun equip slowdown means that unless you snag a bola on someone, they're probably getting away. And bolas are their own can of worms.

**Comment by Fronsis** [comment]
> I dislike this, I made the shove changes active on all intents on purpose for the following reasons:
> 
> * Security would have to position themselves effectively, a chaotic scenario and poor position will result in allies being knocked down.
> * It's a buff to the baton's defensive use, and a nerf to the offensive capability. Introducing a tile of space after a stun baton attack makes it so that each attack of the baton by a single person is slower, lowering the DPS without needing to reduce the damage. This reduces the DPS without making it so that the survivability of the security officer is significantly impacted, since its also harder for the opponent to get a rebound attack on the user.

I've yet to find a single main officer that likes the shove change, as a matter of fact one of the big reasons tonfa started being used more was because of the baton push, eventually people went ''oh right the k.o!!'' and started using that feature other than to mess around.

Now that it's supposedely solved with your own pr ( #11200 ) i don't see why this wouldn't be good, you actually give agency to the Officer, in fact you could even make it that the shove-attack takes more hits to crit because they're sacrificing a heavy blow to keep the assailant away from them, which is something you've talked in the past: give agency on melee combats to both parties.

As the baton currently stands, what you think happens.. doesn't happen.

> Security would have to position themselves effectively, a chaotic scenario and poor position will result in allies being knocked down.

I've never seen someone else be knocked down by the baton-shove ever since it was introduced, mind you i don't play every day multiple rounds but i'm quite active in general and constantly speaking with others and reading stories so yeah.. that never happens, and if it happens it doesn't really matter because people would not be disarmed from it.

You could argue the ''think about your positioning in a fight'' was more relevant when the first iteration of your baton-shove was introduced, where you could shove them into walls and tables, once that was removed to balance it because it was too powerful it just became an annoyance since it was just a husk of what the PR was.

On a regular arrest scenario, that might include a chase, most Officers find it extremely annoying because they don't see the point of it(i've spoken with a couple of sec mains and i agree with their views, feel free to make a Poll) because.. you're chasing someone yet your attacks push them away in a very.. weird way it also feels weird that each attack is strong enough to shove one spessmen one block away, it doesn't feel good nor fun to play with and that's why a lot of folks moved to Tonfa.

With this PR your interests in a more dynamic melee fight remains, given that they can choose to have agency on wether to press the attack or shove them away if they're being attacked and that certainly is more engaging and fun than the current baton.

**Review by PowerfulBacon — APPROVED** [review]
I am willing to concede on this and revisit it later

**Pull request merged**
