### PR TITLE
Added the ability to freely change chat fonts

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

Ports tgstation/tgstation#56575
Makes it so you can change chat fonts, fixed dropdown overflow
image

## Why It's Good For The Game

fonts

## Changelog
🆑 Watermelon914
add: Added chat fonts that can be chosen via settings. You can also input a custom font.
fix: Fixed dropdown overflow if the selected input is too long.
/🆑

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I dont really feel like this is something we should allow the players to change

**Comment by ivanmixo** [comment]
> I dont really feel like this is something we should allow the players to change

Why not?

**Comment by PowerfulBacon** [comment]
> 
> 
> > I dont really feel like this is something we should allow the players to change
> 
> Why not?

Protect the players from their own bad decision-making 😄

**Comment by Chessus** [comment]
Of course you chose Comic Sans for the screenshot

**Comment by jupyterkat** [comment]
*wink*

**Comment by utilbird** [comment]
sans

**Comment by Cartlord** [comment]
Looks good! What fonts will be available?

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
