### PR TITLE
Allow robots to have serial number names

### PR DESCRIPTION
**Pull request by yorii**
## About The Pull Request

This PR is needed so that robots can comply with MRP naming policy. And I made a better, less significant change this time.

## Why It's Good For The Game

Now robots can be named like a model ID in order to comply with MRP naming policy.

## Changelog
:cl:
fix: now robots can actually roleplay as a serial number.
/:cl:

### CODE REVIEW

**Comment by yorii** [comment]
MRP naming policy: https://forums.beestation13.com/t/guide-to-naming-your-character-appropriately-for-mrp/5740

> IPC - Robotic Acronyms, Something that looks like a model ID, or otherwise a name fitting for something mechanical. Human names are not appropriate for IPCs.

**Comment by yorii** [comment]
I found another way of implementing it, is this better?

**Comment by ike709** [comment]
You're just doing https://github.com/BeeStation/BeeStation-Hornet/pull/2150 again.

**Comment by yorii** [comment]
NO IT IS A DIFFERENT CHANGE

**Comment by yorii** [comment]
@ike709 come on please actually read the PR? ;( this is just bullying

**Pull request closed without merging**
