### PR TITLE
Removes "Fourth Wall" antag rolling

### PR DESCRIPTION
**Pull request by Tsar-Salat**
## About The Pull Request

Fourth wall has a chance to give you mild, to severe, to special traumas when Overdosed.

This is a fine mechanic, however what's not fine is that a brain trauma that gives you an *antag datum* is not blacklisted.

As a recompense, I removed imaginary friends fom the blacklist.

## Why It's Good For The Game

Antag rolling bad. People have eaten punishments for doing this in the past, let's just kick it off our plate.

Imaginary Friends arent *nearly* as problematic, and can be pretty fun actually in terms of RP, I think giving them another implementation wont hurt.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

It compiles

</details>

## Changelog
:cl: rkz
tweak: removed an antag rolling method, blacklisted 'Fourth Wall' Overdose from giving you the Obsessed brain trauma. 
tweak: Imaginary friend brain trauma is no longer blacklisted from 'Fourth Wall' Overdose
/:cl:

### CODE REVIEW

**Review by Rukofamicom — DISMISSED** [review]

**Comment by Rukofamicom** [comment]
Alright this one isn't even subjective - This does not affect game balance whatsoever so I swapped it off of balance change.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Blacklist imaginary friend. We don't want it so that people get prompted "do you want to be an imaginary friend for [X]", only to get deleted 20 seconds later. It would just suck for the ghosts and make the role less worth clicking if it comes up legitimately. This list should avoid all ghost roles.

**Comment by Rukofamicom** [comment]
I didn't consider that this was just going to be the same issue as ketamine again and almost fell for thinking it was a good idea all over again

**Comment by itsmeow** [comment]
Yea if this can wear off then there shouldn't be a ghost role.

Ideally we should put a flag on brain traumas that have gameplay implications rather than making a blacklist, that way other things that need to filter brain traumas can do so without duplicating this list.

**Pull request closed without merging**
