### PR TITLE
makes ipcs and other robot races(?) be infectable by the felinid virus

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request

adds the thing that allows ipcs and such to be infected by the felinid virus

## Why It's Good For The Game

this will generally make playing an ipc a bit more hellish and will only make like 1% of ipc players happy, this is generally a very bad pr that pretty much noone except felinid players will like, thats why our 2 felinid main maintainers will 100% speedmerge this

## Changelog
:cl:
tweak: lacking flesh will no longer save you from the disease of meow
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
Im about to replace the shitty jankvirus with a proper symptom that can be combined with biometallic replication anyways

**Comment by Raven-Industries** [comment]
Beestation after this gets merged: 
image

**Comment by TeomanTheGreat** [comment]
Robot furries. Why.

**Comment by zeskorion** [comment]
> Robot furries. Why.

Why not

**Comment by ToasterBan** [comment]
just because your an ipc doesn't mean you shouldn't suffer

**Comment by Effemu** [comment]
no, go away bwickets

**Comment by badlypayedgoon** [comment]
Does not really make sense, logically speaking.

**Comment by ToasterBan** [comment]
> Does not really make sense, logically speaking.

if it can turn a skeleton into a catirl it should turn a robot into a catgirl

**Comment by Ravellon** [comment]
> if it can turn a skeleton into a catirl it should turn a robot into a catgirl

Big true. The suffering must be universal.

**Comment by PowerfulBacon** [comment]
This doesn't make any sense.

**Comment by ToasterBan** [comment]
maintainers speedmerging the joke or of the joke disease 😤

**Pull request closed without merging**
