### PR TITLE
Touches Up Some ION_LAW Fragments to current standards

### PR DESCRIPTION
**Pull request by DatBoiTim**
## About The Pull Request
Changes some of the possible options for ion_law substrings to be more RP friendly.
Fixes spelling for some.

Admins and Maintainers, feel free to request additional modifications for unmodified entries, or request I alter the currently modified entries.

## Why It's Good For The Game
Makes a system more in-line with the environment the server is aiming for. Double checks spelling for entries.

This is merely a word swap within a string.

## Changelog
:cl: DatBoiTim
tweak: Tweaked some Ion Law entries to be more RP friendly.
tweak: Altered the spelling of some Ion Law entries to be correct.
/:cl:

### CODE REVIEW

**Comment by DatBoiTim** [comment]
Requesting a DNM while waiting for DevOps and Administrative review

**Comment by AnCopper** [comment]
Gamer oppression..

**Review by Crossedfall — APPROVED** [review]
I always knew assistants were gamers.

**Comment by DatBoiTim** [comment]
> I always knew assistants were gamers.

I'm glad someone appreciates the substitution.

**Review by Archanial — APPROVED** [review]

**Pull request merged**
