### PR TITLE
Converts typecheck wiremod component into a typecast component

### PR DESCRIPTION
**Pull request by The-Moon-Itself**
## About The Pull Request
This pull request modifies the typecheck wiremod component so that its result pin is typecasted to the selected type and will set it to the input value if the typecheck returns true and sets it to null on false. The typecheck component has been renamed to the typecast component because of this change. If you're wondering why a file was added and deleted in the files changed, apparently renaming a file makes git delete the old file and make a new one with the new name. Thankfully, the file is pretty short, so I hope it's not too hard to review.

## Why It's Good For The Game
Currently the non-specific entity typecheck component options are a bit useless. Yes, you can tell if an any pin is holding a number/string/list/entity, but you can't do anything with that information because you can't put an output any pin into a more specific input pin. This is especially devastating when working with list components, as all indexing components have any pins as an output, meaning that you're very limited in what you can do with the contents of a list. Adding a way to typecast an any pin into something more specific would make both the old typecheck component and list components way more useful.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/51838176/188719773-4f5e5519-7cb5-42c0-991b-cd3043a7ea44.mp4

In this test, noise emitters are used to show that the basic typecheck functionality is maintained, and the results pin is probed to show that it is set to null on false and the input on true.

</details>

## Changelog
:cl:
tweak: The typecheck wiremod component now typecasts as well, and has been renamed accordingly
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Does it have an output to say if it was successful or not or is it only 1 output being null or the object you put in?

**Comment by The-Moon-Itself** [comment]
In the testing procedures, it shows that it maintains the true/false signal pins that typecheck already had, and would pulse the corresponding pin based on whether the input is the correct type or not.

**Comment by PowerfulBacon** [comment]
Oh nice, should have looked there before the code

**Comment by itsmeow** [comment]
Git has a rename function, it just requires some extra work unless your IDE is feeling smart that day.

**Comment by The-Moon-Itself** [comment]
I really should learn how to use git from the terminal, but honestly, I'm still a bit scared that if I make one mistake I'll delete my entire repo or something

**Comment by itsmeow** [comment]
git stuff can be undone fairly easily unless you delete unstaged changes.

Commits, deletes etc can be easily restored with the checkout, reset, and reflog commands

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
