### PR TITLE
Medbot patches

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request
after doing some ingame playing, I've decided to make some changes from my previous medbot pr
could be the first of many

1. Beaker removal is only available on unlocked medbots, for some reason I've seen a lot of people remove the beaker from the medbot and then just leave the medbot, this should help with the issue
2.  Medbot now tells you the name of whatever is inserted in it, to help with knowing what it does
3.  Using a pen on a medbot lets you change its name, for on the fly-naming, to help you label a medbot if you change its function, or if robotics doesn't name it for you
4.  Chemists now start with the robot controller app on their pda, to help with medbot manegement
5. The window name at the top of the medbot UI now tells you the efficiency

## Why It's Good For The Game
mostly explained above, this is mostly QOL to prevent confusion and general ease of use for the medbots

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/54711687/296159e8-9170-4778-8bbb-c5078c837a6d

https://github.com/BeeStation/BeeStation-Hornet/assets/54711687/d169ce8c-c355-4840-85d0-356d559d1180

</details>

## Changelog
:cl:
add: You can now name a constructed medbot using a pen on it
add: Chemist PDA job disks now also contain robot management
add: Medbot UI now tells you the name of the beaker/chembag that is inserted in it
qol: medbot efficiency can now be seen the medbots version number at the top of its UI
tweak: Medbots need to be unlocked to have their beaker/chembag removed
/:cl:

### CODE REVIEW

**Review by EvilDragonfiend — CHANGES_REQUESTED** [review]
Renaming should be available to a person wtih a proper access

**Review by Rukofamicom — COMMENTED** [review]
Agree with dragon, looks good otherwise

**Comment by ToasterBan** [comment]
> Renaming should be available to a person wtih a proper access

it technically requires proper access, it needs to be unlocked.
The medbot could be left unlocked and someone could sabotage it's name which I don't find any worse than the fact that someone could also change out it's reagents in that scenario

**Review by Rukofamicom — APPROVED** [review]

**Review by EvilDragonfiend — APPROVED** [review]
alright then

**Pull request merged**
