### PR TITLE
Inventory.dm optimizations/improvements

### PR DESCRIPTION
**Pull request by utilbird**
## About The Pull Request

Better code performance and quality. 

## Changelog
:cl:
code: inventory helper optimizations
/:cl:

### CODE REVIEW

**Review by ike709 — DISMISSED** [review]

**Comment by ike709** [comment]
Fails CI

**Comment by ike709** [comment]
Getting stale

**Comment by PowerfulBacon** [comment]
How is this an optimization? It's just rewording the exact same thing and makes the else if chain look worse. There won't be any performance benefits, since the only thing that was more performant was the switch which was taken out because it didn't work

**Comment by ike709** [comment]
Yeah if anything this is probably slightly slower, BYOND (hopefully) does internal optimizations for an elseif chain

**Pull request closed without merging**
