### PR TITLE
Disables the roundstart report on sage.

### PR DESCRIPTION
**Pull request by ghost**
### Why It's Good For The Game

It blatantly encourages using metaknowledge and valid hunting for the rounds antags, makes blue alert pretty redundant as the station is on it 90% of the time, and god forbid it tells people that it's a greenshift. Overall this is a terrible feature for a MRP server.

## Changelog
:cl:
config: The Syndicate have purchased new encryption equipment, Central Command can no longer intercept their Communications.
/:cl:

### CODE REVIEW

**Comment by Moccha-Bee** [comment]
i agree with this pr 👍🏻

**Comment by eeSPee** [comment]
Seen it on paradise station and it works quite well.

**Comment by DatBoiTim** [comment]
I like this.

I remember being a new player and being confused about how and why this alert happened.

I do think keeping green alert is useful, but blue alert needs to be triggered manually with valid IC reason(concrete evidence of antagonist actions, not rumors). Especially if a traitor gets their hand on a console, and sets to green after laying low.

**Comment by qwertyquerty** [comment]
@Crossedfall

**Review by Crossedfall — APPROVED** [review]
A bit of a yucky change in my opinion. But I suppose we can give it a go

**Pull request merged**
