### PR TITLE
Replaces the escape pod shuttle

### PR DESCRIPTION
**Pull request by spockye**
## About The Pull Request
This PR replaces the current escape pod shuttle with the one i made for TG  (its the shuttle you go to with the escape pods)
IMO the old one was a little outdated, and i've already replaced TG's with this one, so i might aswell port it over here aswell! (with changes fitting the codebase) 

The new shuttles consists of: 
a docking hallway
a main room, with a bar and medbay
a garden
a bridge
two engines!

it also adds capybaras!
you can purchase them for 10k credits at your nearest cargo console

## Why It's Good For The Game
as i said earlier, i think the previous one is a little outdated, and this new one allows us to have a total of EIGHT escape pods for the larger stations (if one is made that deserves so many)

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

New shuttle:
image

Pod Hallway:
image

Garden:
image

Main Room:
image

bridge:
image

Engine pod: 
image

in editor:
image

Current Shuttle:
image

Capybara!
image
Capybara!
</details>

## Changelog
:cl: Spockye
fix: Remakes the escape pod shuttle
add: Ports Capybaras from Shiptest
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
Only looking at MapDiffBot2 here.

What is this? Is it meant to be an air tank? If so, use the actual air tank instead then.
image

Who's bed is this for? Just any pet?
image

Perhaps uneaten food at the bar to make it more inviting?
image

Perhaps a medbay-bar signs here? Along with Command and Engineering up above where appropriate. 
image

I really like these windows. Also, no distro scrubber and vent in the engines.
image

The docking hallway feels a tad empty. Perhaps add in a turned off and unlocked janitor bot there? Similar to the ones found in Medbay. And perhaps an atmosbot in one of the two engines. If they risk taking unnecessary CPU power then you could leave them turned off by default.

Then an active medibot in Medbay.

I would avoid floorlights unless it is really necessary to have them. Although, this is on the CC-level so it might be "*shrug* whatever".
image

Perhaps add some picture frames to it too? In the docking hallway and or at the bar and garden.

I'd also probably flip the medbay so the entrance is closer to the door and the table-chair is less obstructive.

**Comment by spockye** [comment]
Oh shit i forgot the pet. Taking ideas for a pet

> Only looking at MapDiffBot2 here.
> 
> What is this? Is it meant to be an air tank? If so, use the actual air tank instead then. image
> 
> Who's bed is this for? Just any pet? image
> 
> Perhaps uneaten food at the bar to make it more inviting? image
> 
> Perhaps a medbay-bar signs here? Along with Command and Engineering up above where appropriate. image
> 
> I really like these windows. Also, no distro scrubber and vent in the engines. image
> 
> The docking hallway feels a tad empty. Perhaps add in a turned off and unlocked janitor bot there? Similar to the ones found in Medbay. And perhaps an atmosbot in one of the two engines. If they risk taking unnecessary CPU power then you could leave them turned off by default.
> 
> Then an active medibot in Medbay.
> 
> I would avoid floorlights unless it is really necessary to have them. Although, this is on the CC-level so it might be "_shrug_ whatever". image
> 
> Perhaps add some picture frames to it too? In the docking hallway and or at the bar and garden.
> 
> I'd also probably flip the medbay so the entrance is closer to the door and the table-chair is less obstructive.

**Comment by TsunamiAnt** [comment]
pet should obviously be a xeno maid named spencer

**Comment by MarkusLarsson421** [comment]
If you could make a drone pet, that'd be unique and cool.

**Comment by spockye** [comment]
> Perhaps uneaten food at the bar to make it more inviting?

theres a box of donuts, and donk pockets for the hungry fools!

Thanks for the review <3

**Comment by Fronsis** [comment]
Speedmerge immediatly capybaras are here

**Comment by ClownMoff** [comment]
Babe get in the vagina shaped shuttle

**Comment by PestoVerde322** [comment]
The atmos loop is unnecessary since it's a roundend map.

immagine

Doesn't yield any error?

immagine

Not so sure if it should be this close to the map border.

**Comment by spockye** [comment]
> Doesn't yield any error?

Nope!

thanks for the review <3

**Comment by MarkusLarsson421** [comment]
Do add the pet to the Cargo order so it isn't too exclusive.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
image

Why are there large palm trees inside a small space ship?

**Comment by spockye** [comment]
> image
> 
> Why are there large palm trees inside a small space ship?

thought it was fitting (i dont imagine them being that huge, most likely just plastic props reaching the ceiling)

**Review by PestoVerde322 — APPROVED** [review]

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
