### PR TITLE
BoxStation Medical Trimlined

### PR DESCRIPTION
**Pull request by Lambda-Epsilon**
## About The Pull Request

This PR simply replaces the old square side decals with the newer Trimlines. Some other small aesthetic changes aswell.

(Will be making future PRs for other depts)

_Old Medical:_
image

_New Medical:_
image

## Why It's Good For The Game

Brings us up to par with other codebases, also looks better.

## Changelog
:cl:
add: Added trimlines
changed: medical decals
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
should probably clarify that you changed box stations decals in the CL, it could confuse people

**Comment by PowerfulBacon** [comment]
those arrows look kinda icky imo

**Comment by FlamePrince** [comment]
> 
> 
> those arrows look kinda icky imo

by icky do you mean like covid markers? bc me too

**Comment by yyzsong** [comment]
I liked old box med. Trimlines are fine, but having colour in the centre of every area isn't really needed

**Comment by ItsTisme** [comment]
I like the trimline alot. Looks good

**Comment by PowerfulBacon** [comment]
> 
> 
> > those arrows look kinda icky imo
> 
> by icky do you mean like covid markers? bc me too

Nah I mean ugly af

**Comment by ike709** [comment]
I like it. Fix conflicts and ping for merge.

**Pull request closed without merging**
