### PR TITLE
Adds psychologist as a proper job (DO NOT MERGE TILL SOP IS DONE)

### PR DESCRIPTION
**Pull request by giacomoh**
## About The Pull Request

This adds "psychologist" as a job in the job selection. On all maps with a new office, every round.
I envision them as a crew therapist, who is able to prescribe drugs which the chemist will make.
I'd like for prisoners and crewmembers who received traumatic injuries to attend a mandatory (or recommended, i suppose) meeting with the psychologist.
Pure RP job, no inherent mechanics tied to them. 
I believe this is the best way to introduce this kind of job.

(IMPORTANT!)

- since corg is not done, i don't have access to the map files. The psychologist office is not present on corg!
- fland office is in a temporary solution, new fland will be introduced soon (v5 i believe)
- SOP!!! i'll discuss this with admins but it will be straight forward

## Why It's Good For The Game

Gimmick was a mistake. You should play a character, with a story behind them. Why should their job be completely random? VIP magician or psychologist, why?
Shrink is also complete LRP right now. mostly because they spawn with gamer gear, their office looks like a sex dungeon, and they are hidden in maints.
(i'm also planning to add barber and VIP in the future so that we can finally delete gimmick)

## Testing Photographs and Procedure

<details>

image

image

I kept the offices similar on most maps

image

image

image

</details>

## Changelog
:cl:
add: Added new job, psychologist
add: Added psychologist office
del: Removed shrink and shrink random spawned room
/:cl:

### CODE REVIEW

**Comment by Mat05usz** [comment]
> Gimmick was a mistake. You should play a character, with a story behind them. Why should their job be completely random? VIP magician or psychologist, why?

What gimmick does it add a bit of randomness, the story is up to the player.

> Shrink is also complete LRP right now. mostly because they spawn with gamer gear,

They don't even spawn with the gear, it's in their office and they can pick it up if they think it's fine, gear spawning doesn't inherently make a role LRP.

> their office looks like a sex dungeon

Never had such thoughts about it, it was creepy on the back end but when you enter it, it's fine?

> they are hidden in maints

That's also cool and adds a nice vibe to it.

To actual comment:

We don't need another medical job, especially one that will be not used (yes, noone cares and noone will care about it).
It's place is as a gimmick job, so adding a nice random flavour to a round that doesn't happen every time.

**Comment by giacomoh** [comment]
> What gimmick does it add a bit of randomness, the story is up to the player.

Ok that it's random, but why should my character either spawn as a clown or a psychologist? that doesn't make any sense to me.
These jobs are completely unrelated and attract a completely different kind of players.
Also, "the story is up to the players" well obviously. but if my character has studied med school or whatever, why should it also end up as a barber? or stage magician?

> They don't even spawn with the gear, it's in their office and they can pick it up if they think it's fine, gear spawning doesn't inherently make a role LRP.

Spawning with armor and a syringe gun? why does a psychologist need that?

> Never had such thoughts about it, it was creepy on the back end but when you enter it, it's fine?

Why is it in maintenance, where it's difficoult to access? is there a reason for it?

> That's also cool and adds a nice vibe to it.

that's not "cool". Their office needs to be in medbay, since it should be their department. This is not LRP. There is no reason why it shouldn't be in medbay.

> We don't need another medical job, especially one that will be not used (yes, noone cares and noone will care about it).
> It's place is as a gimmick job, so adding a nice random flavour to a round that doesn't happen every time.

I very much disagree with this.
It's not just another medbay job. It has a completely different task than a medic, or chemist. We need this job for variety, since it offers a LOT of RP value.
Its place is not as a gimmick job, since its potential is vey limited as a random spawn which also gives you the chance to spawn as another completely unrelated job that has no similarity to this one.

**Comment by giacomoh** [comment]
Also, i care? and a lot more people on discord who gave me feedback told me they cared about this. 
I don't know why you are saying this. 
This should be an RP server, it should have RP focused jobs. If you aren't interested in those, that's fine. Other people are though.

EDIT: sorry for constant edits, it's just that it's late at night and i'm very sleepy

**Comment by Mat05usz** [comment]
> Ok that it's random, but why should my character either spawn as a clown or a psychologist? that doesn't make any sense to me.
These jobs are completely unrelated and attract a completely different kind of players.

Then spawn in as a regular doctor and request from CMO/HoP to be made into psychologist. The whole point of gimmick jobs is that they are random and add flavour to the round.

> Also, "the story is up to the players" well obviously. but if my character has studied med school or whatever, why should it also end up as a barber? or stage magician?

If you set up any other job on high priority, it doesn't mean you'll end up as one. I could understand if you wanted to split gimmick into separate jobs with 'yes/no' options, to still make it random. But adding new room for a 'useless' job? Eeh. (also can you provide images for other stations too?)

> Spawning with armor and a syringe gun? why does a psychologist need that?

I guess for unruly patients? The whole 'gimmick' is that this business is kinda sketchy. Also, I don't see mentions of him spawning with armour.

> Why is it in maintenance, where it's difficoult to access? is there a reason for it?

Code-wise: It's supposed to be a random job that spawns sometimes, therefore it spawns in random maint.

'Lore'-wise: NT doesn't really care about it's workers, they must be standing and working, but mental health? Who cares, they are expandable. You can see that attitude in multiple places across the game. (at least how I think about it)

> that's not "cool". Their office needs to be in medbay, since it should be their department. This is not LRP. There is no reason why it shouldn't be in medbay.

See above

> It's not just another medbay job. It has a completely different task than a medic, or chemist. We need this job for variety, since it offers a LOT of RP value. 

> Also, i care? and a lot more people on discord who gave me feedback told me they cared about this.
I don't know why you are saying this.
This should be an RP server, it should have RP focused jobs. If you aren't interested in those, that's fine. Other people are though.

I'm not saying this to insult you, or anyone else. I'm also not saying these things with malicious intent, it all comes from my experience while playing. I have seen maybe one or two psychologists/psychiatrists doing a gimmick, furthermore, I barely see any gimmick job doing their gimmick. Call me a pessimist (altough I think I'm more of a realist but whatever), I just don't think it will work out as a separate job (I'd be glad to be proven wrong, though), therefore I don't think it deserves an actual space on the station (same for the magician, VIP and barber).

> Other people are though.

Yes I'm interested in RP, but also I know that you can't cater to every single person and their vision of RP, otherwise it'd be hell. As I said above, you can already RP as a psychologist while playing a MD, just get your title changed, use one of the unused patient rooms and you're good to go, no need to introduce another useless room when you have these, altough I think you'd get 1/2 people max through the shift, and that's very optimistic.

> EDIT: sorry for constant edits, it's just that it's late at night and i'm very sleepy

It's okay, gn :D

**Comment by tasteofaliar** [comment]
I like this idea, I would unironically love to be a psychologist and think it'd be good fun.

**Comment by ToasterBan** [comment]
> > Ok that it's random, but why should my character either spawn as a clown or a psychologist? that doesn't make any sense to me.
> These jobs are completely unrelated and attract a completely different kind of players.

I think they meant magicians, character consistency bad, look at rant below
> 
> Then spawn in as a regular doctor and request from CMO/HoP to be made into psychologist. The whole point of gimmick jobs is that they are random and add flavour to the round.
> 

But I don't want to take up an entire medical doctor slot for a role that won't do any medical work 

I also hate gimmick jobs, something I hate is forced character inconsistency, if my character is a doctor I don't want them to be an engineer next round and a captain the one after, If my character has a prosthetic right arm I don't want that prosthetic to go on their right leg the next round

this change lets me have a dedicated therapist character
> > Also, "the story is up to the players" well obviously. but if my character has studied med school or whatever, why should it also end up as a barber? or stage magician?
> 
> If you set up any other job on high priority, it doesn't mean you'll end up as one. I could understand if you wanted to split gimmick into separate jobs with 'yes/no' options, to still make it random. But adding new room for a 'useless' job? Eeh. (also can you provide images for other stations too?)
> 

Therapist has just as many uses as bartender, lawyer, curator and chef
not every role has to be purely mechanical

> > Spawning with armor and a syringe gun? why does a psychologist need that?
> 
> I guess for unruly patients? The whole 'gimmick' is that this business is kinda sketchy. Also, I don't see mentions of him spawning with armour.
> 

1. I hate that gimmick, I fucking despise servers that add a therapist role only for the therapist to be one of the most insane people on the station 
2. the maint room therapists spawn in has a "safety helmet" which is just a renamed security helmet, it's funny when therapists use it because they effectively are calling themselves mentally challenged but otherwise it's just shitters powergaming

> > Why is it in maintenance, where it's difficoult to access? is there a reason for it?
> 
> Code-wise: It's supposed to be a random job that spawns sometimes, therefore it spawns in random maint.
> 
> 'Lore'-wise: NT doesn't really care about it's workers, they must be standing and working, but mental health? Who cares, they are expandable. You can see that attitude in multiple places across the game. (at least how I think about it)
> 

1. yeah, gimmick roles my despised
2. nobody gives a shit about lore


> > that's not "cool". Their office needs to be in medbay, since it should be their department. This is not LRP. There is no reason why it shouldn't be in medbay.
> 
> See above
> 

noone is going to go into deepmaint to get therapy 

> > It's not just another medbay job. It has a completely different task than a medic, or chemist. We need this job for variety, since it offers a LOT of RP value. 
> 
> > Also, i care? and a lot more people on discord who gave me feedback told me they cared about this.
> I don't know why you are saying this.
> This should be an RP server, it should have RP focused jobs. If you aren't interested in those, that's fine. Other people are though.
> 
> I'm not saying this to insult you, or anyone else. I'm also not saying these things with malicious intent, it all comes from my experience while playing. I have seen maybe one or two psychologists/psychiatrists doing a gimmick, furthermore, I barely see any gimmick job doing their gimmick. Call me a pessimist (altough I think I'm more of a realist but whatever), I just don't think it will work out as a separate job (I'd be glad to be proven wrong, though), therefore I don't think it deserves an actual space on the station (same for the magician, VIP and barber).
> 

I find that absolutely nothing was lost since noone uses the patient rooms

noone does their gimmick because 
a) it's in fucking deepmaint
b) mostly shitters play gimmick roles


> > Other people are though.
> 
> Yes I'm interested in RP, but also I know that you can't cater to every single person and their vision of RP, otherwise it'd be hell. As I said above, you can already RP as a psychologist while playing a MD, just get your title changed, use one of the unused patient rooms and you're good to go, no need to introduce another useless room when you have these, altough I think you'd get 1/2 people max through the shift, and that's very optimistic.
> 

the last part is sadly something I agree with, our playerbase will almost certainly never get therapy but I believe it's good to have for the future

> > EDIT: sorry for constant edits, it's just that it's late at night and i'm very sleepy
> 
> It's okay, gn :D
>

**Comment by williamcll** [comment]
Problem is most of the targets a psychologist have to deal with is the targets that gets bwoinked aka. RP-ing as insane, such as the now removed debtor.

**Comment by giacomoh** [comment]
> Problem is most of the targets a psychologist have to deal with is the targets that gets bwoinked aka. RP-ing as insane, such as the now removed debtor.

Hello. I'd like to dispel this idea that only "insane" people go to a psychologist.
There are many reasons why you might see a psychologist. 
For example: you might be experiencing anxiety, depression, stressful life events or any other mental health difficulty. 
You might not even know what’s going on, but just feel that you haven’t been ‘right’ or that your life has become more difficult. 
A psychologist is trained to perform a detailed assessment of your mental health and to identify what’s going on for you. 
I strongly believe that in order to legitimize the position in game, giving them an office and a consistent spawn is necessary.

**Comment by giacomoh** [comment]
I agree with everything Bluezorua has said, but to reiterate my position:
- Current psychologist is used only by people who are also interested in stage magician and VIP (all very different jobs): LRP people.
- It creates unecessary character inconsistency, but it also foces you to play jobs you have no interest in.
- Let's be real, the shrink's sex dungeon is never used.
- This will help legitimise the role the psychologist will have in the station ecosystem. Maybe even integrating them into the normal processes of medbay checkups and security.

I'll be writing an actual SOP draft soon, maybe open a forum thread in the meanwhile.

**Comment by PowerfulBacon** [comment]
> Pure RP job, no inherent mechanics tied to them.

All jobs like this currently are generally just considered tider jobs and don't have any meaningful reason to exist on the station: curator, lawyer, assistant, all gimmick jobs, chaplain on any non-cult round.
Why would making the psychologist a full job not follow this convention?
Do we need a psychologist job that doesn't do anything?

> Gimmick was a mistake. You should play a character, with a story behind them.

How does this change or fix that?
What does this PR change, fix or aim to achieve?

> I envision them as a crew therapist, who is able to prescribe drugs which the chemist will make.

Why would players go through them rather than just going straight to the chemist? Sure, it's RP, however currently the best RP comes from the places where mechanics are intertwined with the RP experience. Going outside of just beestation, the only servers I've seen in SS13 as a whole that achieve RP in places where it isn't mechanical are servers with ERP, since the extreme roleplaying adds in a mechanic to interact with people (and we aren't adding that).

**Comment by ToasterBan** [comment]
>Why would players go through them rather than just going straight to the chemist?

if we do the psychologist chems like 💉bay💉, the chems would have 0 effect outside of text in your chat so there's 0 reason to go straight to chemistry since that's just gaining absolutely nothing and not having any interaction 

for this to happen we would need something like bay with its anti-depressants and other medication, I don't want psychologists to feed people narcotics

**Comment by giacomoh** [comment]
> All jobs like this currently are generally just considered tider jobs and don't have any meaningful reason to exist on the station: curator, lawyer, assistant, all gimmick jobs, chaplain on any non-cult round. Why would making the psychologist a full job not follow this convention? Do we need a psychologist job that doesn't do anything?

Psychologist would not have any special weapon (like all the ones you mentioned), and offer no mechanical advantage over any other job (apart from medical access). 
The only reason someone would pick that job, is because they intend to play it. That's not the case with curator (mostly because that's not even a job).
They do something, though? I mean, not strictly trough mechanics. But if you have any ideas i'm open to hear about them. 
I just don't think anything would really work outside of roleplay.

> How does this change or fix that? What does this PR change, fix or aim to achieve?
The character's job no longer is random. Now your character who has a master’s degree in psychology won't have a random chance to be a barber/stage magician/whatever really.

With this PR i would like to turn the psychologist into a real job. It's not ready to be merged yet (i forgot to save it as draft, sorry, but i still said so in the title).

> Why would players go through them rather than just going straight to the chemist? Sure, it's RP, however currently the best RP comes from the places where mechanics are intertwined with the RP experience. Going outside of just beestation, the only servers I've seen in SS13 as a whole that achieve RP in places where it isn't mechanical are servers with ERP, since the extreme roleplaying adds in a mechanic to interact with people (and we aren't adding that).

Obviously the solution is to finally introduce Extreme RolePlay, till then, though...
If it's really necessary, I'll add a mechanical element to the job, but i don't think it would make the interactions feel any better than something that originates from the players.
Currently i'm thinking of introducing ramdom mood debuffs that can be cured by chems prescribed by the psychologist (anti-depressants, or something similar, I'll do some research).

> Why would players go through them rather than just going straight to the chemist?

A chemist should not distribute drugs of any kind to normal crew, they should get a stamped paper from another specialist.

**I will try to introduce a mechanical element to the job, till then it will sit in the drafts. I'm certain, though, that such an element is going to be more annoying than beneficial, but i'll try my best.**

**Comment by PowerfulBacon** [comment]
I think it will be incredibly difficult to implement new jobs well, since they require:
 - An actual purpose to get them going
 - Some depth to them so experienced players still have stuff to do

Basically stuff to get new players started, as well as some complex mechanics that won't restrict new players from learning it.
Almost all jobs fail at this, even explorers which were added in a PR with thousands of changes and entire systems built around them.

**Comment by FriendlyContractor** [comment]
Im strongly against adding new "job" that does not have any objectives or responsibilites. Game needs interesting gameplay and mechanics - useless job that can not do anything beside talking to people is not interesting to anybody and does not improve game in the slightest.

If you really want to add a new psychatrist role you need to come up with some interesting gameplay mechanics. Maybe for example add some sort of sanity meter(i believe we kind of have some sort of sanity mechanic already but it does not really do anything meaningfull at the moment). Have horrors of living in space affect psychique of the crew members causing various negative effects and let psychatrist/psychologist diagnose and help affected crew members. Im sure you can come up with something interesting yourself - best of luck to you

**Comment by Mat05usz** [comment]
> Therapist has just as many uses as bartender, lawyer, curator and chef
not every role has to be purely mechanical

So... none? I mean, chef at least improves mood with food, the rest is straight up pointless and, as a person who played A LOT as a lawyer, I can tell you that RP works maybe in 10%, probably less.

> the maint room therapists spawn in has a "safety helmet" which is just a renamed security helmet, it's funny when therapists use it because they effectively are calling themselves mentally challenged but otherwise it's just shitters powergaming

So the room spawns with it, not person. Means they maybe shouldn't get it if not needed, but if they do well, admin issue?

> nobody gives a shit about lore

Call it lore, RP, whatever - wise. But it's just my opinion.

> noone is going to go into deepmaint to get therapy

I've seen gimmicks with 'psychiatrists' that were regular doctors and guess what, noone cared. 

> the last part is sadly something I agree with, our playerbase will almost certainly never get therapy but I believe it's good to have for the future

We had more RP in 2019 than we have now, what future exactly? In 10 years?

**Comment by giacomoh** [comment]
closing this PR  since i'm deleting this fork. I will make a new PR, with all the changes on another fork. Sorry for the inconvenience.

**Pull request closed without merging**
