### PR TITLE
Removes map verb

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Unusued and not working

## Changelog
:cl:
del: Removed map verb
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
would be nice if it got fixed and used

**Comment by KubeRoot** [comment]
I tried to use it recently only to find out it was broken, I also think it'd be nice to have it fixed.

**Comment by ike709** [comment]
Just replace it with a generic link to affected's webmap.

**Comment by francinum** [comment]
Superceded by #5761

**Pull request closed without merging**
