### PR TITLE
rewrites xenomedes' fusion refactor in auxmos

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

keeps aspects of #2614 instead of just reverting to cit fusion hook

## Changelog
:cl:
fix: fixed fusion
/:cl:

### CODE REVIEW

**Comment by williamcll** [comment]
what game mechanics get changed here?

**Comment by jupyterkat** [comment]
you have eyes right

**Comment by BrumalLake** [comment]
> 
> 
> you have eyes right

damn straight answer 😂
they asked that before as well

**Review by Crossedfall — CHANGES_REQUESTED** [review]
Missing Dockerfile + dependency changes. Also shouldn't be merged before https://github.com/BeeStation/auxmos/pull/6 with the appropriate version bump.

**Pull request closed without merging**
