### PR TITLE
CE and CMO cloak sprite updated.

### PR DESCRIPTION
**Pull request by Naevii**
## About The Pull Request

Updates CE and CMO cloak sprites.
comparisionpng

ce cape

## Why It's Good For The Game

Grande Finale of the great cloak resprite.
Resprites CE cape.
(CE cape will match future CE hardsuit resprite)
Refreshes CMO cape colors.

## Changelog
:cl:
imageadd: Updates CMO cloak sprite
imageadd: Updates CE cloak sprite.
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — DISMISSED** [review]

**Comment by Archanial** [comment]
speedmerge

**Review by francinum — DISMISSED** [review]
yes

**Comment by ghost** [comment]
ew

**Comment by LastCrusader105** [comment]
I don't like the CE white cape if his suits white as well the lights are cool but imma vote no imo keep it brown
but cmo one is nice

**Comment by Naevii** [comment]
Change to white is a bit controversial but will work well once the new hardsuit sprites are out.

**Comment by LastCrusader105** [comment]
> Change to white is a bit controversial but will work well once the new hardsuit sprites are out.

what colour will hardsuit be?

**Comment by utilbird** [comment]
Animated cloak looks weird. White is a bit iffy too

**Comment by Crossedfall** [comment]
The CE's cloak sorta feels like it should be the RD's cloak with how technological it is. I don't hate it, but it doesn't seem to fit the role if I'm honest.

**Comment by Naevii** [comment]
Why rd not a CE if ce is the one working on energy, on machines. And have stuff like advanced magboots.

**Comment by Naevii** [comment]
95669282-8a93cd80-0b55-11eb-85d2-7109ff8d2f45
for reference this is new ce hardsuit

**Comment by Naevii** [comment]
I think along with new hardsuit sprite this could help create CE new image of someone advanced technologicall, rather than keep the bulky green and flashy orange from a decades before.  And anyway would be nice if it was put up to vote.

**Comment by LastCrusader105** [comment]
> I think along with new hardsuit sprite this could help create CE new image of someone advanced technologicall, rather than keep the bulky green and flashy orange from a decades before. And anyway would be nice if it was put up to vote.

that is a nice hardsuit...makes me hard looking at it
but its white on white but cmos is blue and blue and caps is blue and blue but they have a is it brown? outline
do you have images of new CE wearing new cloak? it is a nice cloak but i think white on white no one will notice

**Comment by Naevii** [comment]
All of the capes have smooth outline to blend it better with rest of the game. And takes from original color pallettes. I sadly don't have the new azlanon hard suit sprite with the sizing that would make me able to put cape over it. But if it's going to blend in too much together it's not a problem to make outline a bit darker as I made it with multiple capes.

Even look at the hos cloak. It takes literally same color from old hard suit sprite.

**Comment by LastCrusader105** [comment]
well without seeing it I cant say either way so my final thoughts are nice hardsuit, may clash with white hardsuit but im sure naevii knows what they are doing so they get a dubious thumbs up

**Comment by Naevii** [comment]
I will try to retrace azlanons hardsuit and do a check with cape on it at the morning.

Edit. And do corrects if necessary, but it should be okay. Looking at it now

**Comment by utilbird** [comment]
CE's new hardsuit looks like a med hardsuit. Cloak doesn't fit the role at all either

**Comment by Crossedfall** [comment]
> 
> 
> Why rd not a CE if ce is the one working on energy, on machines. And have stuff like advanced magboots.

I'd expect the engineer to appear more industrial than technological. Something that's really sterile doesn't really suit a station engineer (even the CE), in my opinion anyways.

As for the RD, it makes sense that they'd go for a sleeker more "futuristic" design.

**Comment by Naevii** [comment]
MediBangPaintPro_ghjsMPjeFS
and for reference how would current cape look with new suit... 
MediBangPaintPro_Gw1mgdgDhI

**Comment by SomeAngryMiner** [comment]
looks good to me, great capes, and should fit the overall view we're trying to achieve.

**Review by SomeAngryMiner — DISMISSED** [review]

**Comment by Crossedfall** [comment]
Given that the capes are there to help make heads stand out, I don't think white on white really works either. On top of the other issue I brought up. 

Science fiction lights aside, I just don't see why an engineer would wear white. It's going to get stained and oiled up; it just isn't fitting for a role that's meant to get dirty.

**Comment by LastCrusader105** [comment]
its a nice cape but I prefer the old one
maybe do a colour change?

**Comment by Naevii** [comment]
The best i could add from old colors was yellow. and it's on the collar already.
Orange is too flashy.
And brown (green on old cape actually) is not going to work with anything else on new Azlan's department sprites.

And saying that, i tried multiple times to use other color as base color, but it doesn't work as well as white. 
I even tried to combine yellow with white but it didn't work out well either. 

I think what i proposed here is the best possible outcome to fit updated sprites. 


About cloaks making heads stand out, it has animation, i don't think it needs anything more to make it "stand out" 
Plus Majority of players like the new design.

**Comment by TheRealScarHomie** [comment]
just put the old one in his locker or summin, have both, also CMOs shit is literally just pillow shaded now, try and add some more texture to it.

**Comment by Naevii** [comment]
> just put the old one in his locker or summin, have both, also CMOs shit is literally just pillow shaded now, try and add some more texture to it.

But it literally has new texture??
More would create a pattern.

Can't please them all

**Comment by TheRealScarHomie** [comment]
well I mean there is no texture on it, its flat, the old one had like those two creases on the side see, stopped it looking so bland.

**Comment by utilbird** [comment]
Just don't make CE suit look like that if it's such a issue. I'm going to bump my point that this looks like a medical/research hardsuit. There's nothing really wrong with the current cloak, it fits the clunky industrial theme that most of engineering has.

CE wouldn't really fit in that well with these changes, especially with the flashy RGBs the cape has.

**Comment by utilbird** [comment]
If RD were to ever get their own hardsuit (prototype doesn't count) this would be great

**Comment by Naevii** [comment]
> Just don't make CE suit look like that if it's such a issue. I'm going to bump my point that this looks like a medical/research hardsuit. There's nothing really wrong with the current cloak, it fits the clunky industrial theme that most of engineering has.
> 
> CE wouldn't really fit in that well with these changes, especially with the flashy RGBs the cape has.

There is everything wrong with this cape. Choice of colors, shading, design, orange flashy outline, and it doesn't fit the rest of the capes anymore. 

Plus I am going to remind that majority of the community likes the redesign. 

I have nothing more to say.

**Comment by Archanial** [comment]
To be honest, CEs suit should not be white. White is a color of medbay.

**Comment by LastCrusader105** [comment]
I know it’s hard when you put a lot of love into creating something and I agree it’s a lovely cloak, but I also agree it isn’t the CEs cloak I think it suits the RDs cloak
I trust in your designs and if you insist that’s the CEs cloak then I think we should go with that you say
Is it the CEs cloak?

**Comment by Naevii** [comment]
I am not planning any changes to this capes.
Summoning @PowerfulBacon now because vote passed.

If it will need any more changes in game once new engineers suits are merged i will do it in separate PR. 

But they should work well together.

**Comment by Crossedfall** [comment]
I'm just going to continue to voice my problems with the CE's new cape design. To repeat myself, the coloring is too clean and the effect, while very cool, doesn't fit the chosen role. Several people, most of whom are maintainers, have voiced this concern. To be clear, nobody is saying your design is bad. To the contrary, most of us think it looks great. It just isn't fit for the chosen purpose (being the CE's cloak). 

If feedback isn't going to be considered, then perhaps the pr should be on hold until the CE's suit is actually finalized and put in place.

**Comment by ike709** [comment]
> because vote passed.

This is meaningless.

**Comment by Naevii** [comment]
I cannot think of a better way for ce cape.
New ce hardsuit uses cold shades of white, with blue and purple tones. I pulled up all the new ce hardsuit main colors. And added subtle yellow collar that still goes well with the rest. 

With a CE hardsuit main color being white, in blue and purple tones, there is no better way to make a cape that both doesn't look off while wearing both cape and hardsuit and is not white.

Simply because pulling brown, orange or yellow and mixing it with cold colors such as blue, purple and green is nearly impossible to look good together while still being consistent.(contemplementary colors) 

My main thought about the cape was to fit the new ce hardsuit (as well as new ce image) well.
With ce most of the equipment being white (jumpsuit, magboots, hardsuit,beret, hard hat) i do not understand why not to allow the cape to be consistent with rest too.



> > because vote passed.
> 
> This is meaningless.

I only pinged because its been several days since i published the PR and the vote seemed to pass. I had no idea there had been a real issue with the pr untill you put it on hold. While making a change to something, I expected some negative feedback too but I didn't know it will be a real issue untill now.

**Comment by qwertyquerty** [comment]
I'm going to have to agree with people's criticisms here. I don't think it fits the character.

**Comment by Naevii** [comment]
I will wait for the original Azlan pr to get merged, since the cape should fit the new sprites and main idea for chief engineer well, if it still won't i will consider looking for possible changes to bring to the cape.

**Comment by Naevii** [comment]
dreamseeker_oYRkzQjd6v


new colors (left) vs old (right)

**Comment by qwertyquerty** [comment]
Tempted to just merge this and never look back

**Comment by Naevii** [comment]
> Tempted to just merge this and never look back

If there is still any suggestions what could be changed i will gladly do so. 
For now I changed colors to ivory and orange from sterile white and blue.

**Comment by Sinestia** [comment]
With the new changes it's an easy yes

pls merge

**Review by PowerfulBacon — DISMISSED** [review]
I like the new colours @SomeAngryMiner

**Comment by Naevii** [comment]
Requesting feedback from people who commented on this pr originally, check comment above to see latest changes 

@TheFakeElon @Crossedfall @LastCrusader105 @Archanial @scarwolff

**Comment by Crossedfall** [comment]
To be quite frank, I still don't particularly care for the animation. It continues to feel out of place for the CE in my humble opinion. It's well done it just sticks out to me. Can we have a sample without the animation?

**Comment by Naevii** [comment]
> To be quite frank, I still don't particularly care for the animation. It continues to feel out of place for the CE in my humble opinion. It's well done it just sticks out to me. Can we have a sample without the animation?

This is exact same sprite without animation. (with new hardsuit sprites)
Tho i think the animation fitted that cloak well (not sure if the animation is so well visible on gif, it goes smoothly from bottom to top, but the gif is cut)
ce cape

**Comment by Crossedfall** [comment]
> 
> ce cape

The static version of the cloak is a lot better in my opinion, it resolves a lot of the prior criticisms I've had. Especially with the updated color scheme.  

(The animation looked good, it just doesn't fit in my honest opinion. As myself and others have said, the animation would be a lot more suited towards the RD than the CE.)

**Review by SomeAngryMiner — APPROVED** [review]

**Comment by Crossedfall** [comment]
I'm good to go on this, @ike709 was indifferent. I updated the PR body to include your latest screenshot, but the first one will need to be updated as well before we can merge this.

**Comment by Naevii** [comment]
> I'm good to go on this, @ike709 was indifferent. I updated the PR body to include your latest screenshot, but the first one will need to be updated as well before we can merge this.

Edited.

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
