### PR TITLE
ports embed rework + pellet clouds (yay, sticky tapes and actual frag grenades)

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

ports tgstation/tgstation#49634

and quite a few more supporting prs

## Why It's Good For The Game

yes

## Changelog
:cl:
something should go here any time soon
/:cl:

### CODE REVIEW

**Comment by jupyterkat** [comment]
needs #3883 merged for the named args to work

**Comment by zeskorion** [comment]
Cant sticky tape like
Make sticky grenades you cant remove in time to survive?

**Comment by jupyterkat** [comment]
not my problem
image

**Comment by jupyterkat** [comment]
do note that sticky grenades might stick to your hand after you prime it, 50/50 chance

**Comment by zeskorion** [comment]
> do note that sticky grenades might stick to your hand after you prime it, 50/50 chance

There's always remote grenades.  Same thing really, with no risk.

**Comment by jupyterkat** [comment]
lame excuse, but then you can always throw a non-sticky grenade next to em and detonate it instantly

**Comment by ToasterBan** [comment]
finally, a combat med nerf that doesn't nerf non-combat

**Comment by utilbird** [comment]
Pls include all of the main PRs in the description. tgstation/tgstation/pull/48959 for example

**Comment by jupyterkat** [comment]
Draft pr is a draft pr

**Comment by OceanFish1** [comment]
Epic embed fail

**Comment by PowerfulBacon** [comment]
I know its a draft but haven't seen changes in a while so assuming its dead. Feel free to reopen when you are continuing with the PR.

**Comment by jupyterkat** [comment]
@PowerfulBacon It is functionally done, just need the other pr to merge smh

**Pull request closed without merging**
