### PR TITLE
Powerfist fix

### PR DESCRIPTION
**Pull request by CydiaLamiales**
## About The Pull Request
Makes the powerfist actually WORK.
Adds the gas contents of the mounted tank to the description of the fist.

## Why It's Good For The Game
Items working is good

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/110184118/8349ef73-a030-4742-bb88-9dc6b629b3b9

Insane knockback

image

image-148

</details>

## Changelog
:cl:
add: made examining the power fist show mols and pressure of the mounted tank
fix: fixes the power fist not working
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
I assume damage is reduced upon hitting armored targets right?

And hmm how "hard" is to make a mega pressurized tank that can one shot and launch people backwards

I'm glad to see it finally functioning, just curious about the potential of insta-kills, mostly based on the damage shown in a regular greyshirt

**Comment by CydiaLamiales** [comment]
> I assume damage is reduced upon hitting armored targets right?
> 
> And hmm how "hard" is to make a mega pressurized tank that can one shot and launch people backwards
> 

Here's what cooling down an O2 canister with a standard Thermomachine nets you

image

Each use drains 3 x Level mols of gas and deals 20 x Level brute damage, blocked by armor.
So at max level you'll be using 9 mols of gas per hit and dealing 60 damage. 

Hitting a dummy with a lvl 3 punch in HoS's getup only dealt 37 damage instead of 60

image

**Comment by Pro-gamer-window-vista10** [comment]
was this broken by fastmos since its been like this for like 3 years at this point?

**Comment by Fronsis** [comment]
> > I assume damage is reduced upon hitting armored targets right?
> > And hmm how "hard" is to make a mega pressurized tank that can one shot and launch people backwards
> 
> Here's what cooling down an O2 canister with a standard Thermomachine nets you
> 
> image
> 
> Each use drains 3 x Level mols of gas and deals 20 x Level brute damage, blocked by armor. So at max level you'll be using 9 mols of gas per hit and dealing 60 damage.
> 
> Hitting a dummy with a lvl 3 punch in HoS's getup only dealt 37 damage instead of 60
> 
> image

Does it have any type of cooldown in between punches? or the ''cooldown'' is having to use  wrench to readjust pressure between punches as shown in the evidence? (Not sure if the evidence video was mostly to show the difference between a lvl 1 and 3, hence my question!)

Doesn't look that bad, i'm interested to see how it plays out in antag encounter but it's nice having it work!

**Comment by CydiaLamiales** [comment]
>
> Does it have any type of cooldown in between punches? 

No, it has no special cooldowns.

or the ''cooldown'' is having to use wrench to readjust pressure between punches as shown in the evidence? (Not sure if the evidence video was mostly to show the difference between a lvl 1 and 3, hence my question!)

By using the wrench you cycle through the levels.

**Review by itsmeow — APPROVED** [review]

**Pull request merged**
