### PR TITLE
buffs fungal tuberculosis

### LINKED ISSUE #7794: fungal TB is not the hell disease of doom that it should be
## Round ID & Round Date:
 2022-10-03, 40688

## Reproduction:
it was from a floorpill, supposedly.

HOWEVER, THIS BABY-ASS FUNGAL TB WAS SHIT!!! ALL IT DID WAS MAKE YOU THROW UP ALOT AND GIVE YOU MILD STAMINA DAMAGE!!! WHAT THE FUCK!!! FROM WHAT I REMEMBER IN THE OLD DAYS OF YORE (PRE-GOLDEN) FUNGAL TB IS SUPPOSED TO GIVE YOU NUCLEAR OXY DAMAGE AND SHRED YOUR LUNGS!!! AT THE COST OF BEING EASY TO CURE (AND COMING FROM NUKIES)!!! FIX THIS SHIT!!!

TL;DR IT SHOULD DO THIS
fungal

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
Fungal tuberculosis' stage 4 oxyloss effects now work at stage 5. This makes the virus extremely lethal. I do not think this is intended behaviour, but people are requesting it and it is an extremely easy change. I also made the virus give messages at stage 3 (which it did not do before, only giving messages at stages 2, 4, and 5, which was odd)

this took ~5 minutes to begin killing a control group of infectees on a private server. Accounting for time dilation, this should be around 10-ish minutes in game.

## Why It's Good For The Game
fungal tuberculosis is known to be lethal. This makes reality match expectation
fixes #7794

## Testing Photographs and Procedure
image
infected several humans, allowed virus to do its job

## Changelog
:cl:
balance: fungal tuberculosis is now lethal past stage 4.
/:cl:

### CODE REVIEW

**Comment by hotimep** [comment]
image

**Review by itsmeow — APPROVED** [review]

**Review by PowerfulBacon — APPROVED** [review]
Is this disease properly airbourne? If not it should spread when the cough emote is performed. The problem was it not spreading I think rather than it being not deadly

**Comment by PowerfulBacon** [comment]
eh, thats fine

**Comment by zeskorion** [comment]
> eh, thats fine

are you asking me to boost it, or leave it as is. Ambiguous wording.

**Comment by PowerfulBacon** [comment]
I just thought its spread was removed entirely

**Pull request merged**
