### PR TITLE
tgstation changelog -> BeeStation changelog

### PR DESCRIPTION
**Pull request by CthulhuOnIce**
title

### CODE REVIEW

**Comment by AsciiSquid** [comment]
I mean. yeah.

**Comment by qwertyquerty** [comment]
we dont even have the changelog generator do we

**Comment by qwertyquerty** [comment]
also does the tg changelog automatically popup for players when codebase changes are made like it does on goon, if not it should

**Comment by ike709** [comment]
@qwertyquerty There's a config option to open the changelog automatically for people when there's unread changes.

**Pull request merged**
