### PR TITLE
Standardises ByondUI rendering + Emissive Refactor + Emissive energy guns & Huds & IPCs

### PR DESCRIPTION
**Pull request by PowerfulBacon**
Regarding #9814

## About The Pull Request

Makes energy guns have some emissive elements to them.
While making this PR, I found a huge number of things that were buggy or just didn't work with emissives especially when it comes to blockers.
This PR refactors some parts of emissives, saving a plane while making it so that emissives and blockers can exist on the same item and stack infinitely compared to the previous method which would have
- Emissives
- Emissive blockers
- Unblockable emissives

The above method would not work very well with layered items. This method does work with item layers, meaning you can have loads of different icons stacked on top of each other and they will all correctly block each other or display emissives.

image
An emissive screen blocked by a briefcase, with an emissive energy gun on top of it.

image
With the energy gun removed, the emissive part of the screen shows.

This is great because before, an item with emissives would either have to not block other emissives or would block its own emissive elements.

When items are on the same layer, the emissive part will shine over the non-emissive parts. This means that 2 items on the same layer will have their emissive parts shown regardless of the visual ordering which, as far as I know, is undefined so I have no way to predict that.

## Why It's Good For The Game

See above, we have properly working emissives now with blocking and energy guns will not be emissive. Prior ot this PR, emissive blocking seemed to just not work at all. It seems it was ported however that port never fully completed emissive blockings. I have diverged from the original TG method for an option that works better overall.

## Testing Photographs and Procedure

image

image

image

image

image

https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/c5e64de7-e032-4c15-bc83-f17fbd442dec

## Changelog
:cl:
refactor: Refactors emissive lighting and emissive blockers.
add: Adds in emissive overlays for energy weapons.
add: IPC screens are now emissive.
add: Cult halos are now emissive.
add: HUD glasses are now emissive.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Working on getting emissives working for clothing, along with making clothing able to mask other emissive clothing.
image

**Comment by PowerfulBacon** [comment]
I think that the alpha level isn't being taken into account properly and is always fully white rather than grey if it is half alpha

**Comment by PowerfulBacon** [comment]
To make this work with clothing and limbs will require a pretty decent rewrite of mob icon code. This simple little thing has grown quite significantly from a 1 hour project into a 2 day project.

**Comment by PowerfulBacon** [comment]
image

**Comment by PowerfulBacon** [comment]
image

**Comment by DarnTheMarn** [comment]
This is pretty neat, it would be cool if it was also added to in hand and stowed weapons but those things are like 6x6 pixels max.

**Comment by PowerfulBacon** [comment]
I was going to, but it required editting hundreds of sprites due to the awful setup of gun sprites

**Comment by itsmeow** [comment]
does it work with z mimic

**Comment by PowerfulBacon** [comment]
> does it work with z mimic

I wouldn't imagine so, unless z-mimic added basic support for emissives

**Comment by PowerfulBacon** [comment]
Preferences screen is now fixed along with the starlight camera bug, along with all other bugs related to map view rendering.

**Comment by PowerfulBacon** [comment]
Emissive alpha resets on invisible people, causing the floor to light up.
Emissive worn objects are not affected by height of the mob.

**Review by itsmeow — APPROVED** [review]

**Pull request merged**
