### PR TITLE
Ports TGUI clipboards and notice boards

### PR DESCRIPTION
**Pull request by Dingo-Dongler**
## About The Pull Request

Ports TGUI clipboards https://github.com/tgstation/tgstation/pull/57289 and notice boards https://github.com/tgstation/tgstation/pull/59389 from tgstation.
There have been updates on TG adding more to clipboards, but that requires a few more backend systems.

## Why It's Good For The Game

Makes the clipboards and notice boards actually usable.

## Changelog
:cl:
add: Clipboards and notice boards are now updated to TGUI, with clipboards having much better functionality.
/:cl:

### CODE REVIEW

**Review by francinum — DISMISSED** [review]
Satisfy the linters and I'll push this in, One of the few nice-looking TGUIs and excellent improvements.

**Comment by Dingo-Dongler** [comment]
Does the map test matter?

**Comment by francinum** [comment]
Yes

**Comment by Dingo-Dongler** [comment]
whoever put that thing in pubbystation can go to gay baby jail

**Review by francinum — APPROVED** [review]

**Pull request merged**
