### PR TITLE
Adds a hanked radio for the tators

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
cool tator radior that lets you tune to any frequency and speak into it anonymously

edit: the uplink radio uplink is broken by something else, not my fault this time

## Why It's Good For The Game
Cool dynamic for allowing you to specifically watch one department, and occasionally send anonymized messages which is COOL

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image
image
image

</details>

## Changelog
:cl:
add: hacked sbr for tator
/:cl:

### CODE REVIEW

**Comment by etherware-novice** [comment]
ill be honest this is very ducttaped i am taking suggestions

**Comment by Rukofamicom** [comment]
>it also breaks ... but ill fix that later i just want to get this outttt

Nothing with this should ever be merged. You'll need to address anything a PR breaks first , not promise to address it in a future PR.

**Comment by Rukofamicom** [comment]
This PR is a cool concept, such a cool one in fact that this is pretty much already in the game, except it costs TC to obtain right now. 

Decent idea, but unfortunately it's just power creep over existing gear.

**Comment by etherware-novice** [comment]
wait wdym its in game??

**Comment by Rukofamicom** [comment]
Traitors can buy the ability to disguise their voice over radio.

Anyone can already manually tune radios to any frequency.

**Comment by etherware-novice** [comment]
about tuning to any frequency, theres a lock on almost every radio that prevents it from going past 141.1 or 149.9 i think, while department freqs are in the 130-132 range

**Comment by PowerfulBacon** [comment]
This code is too highly integrated with the core radio code and I don't think the code beign added to the radio core is worth the gain. If you need a comment saying "I hate this code", then you are probably doing something wrong somewhere.

**Pull request closed without merging**
