### PR TITLE
Exploration VIP's *now* have the same flavor text as their memory

### PR DESCRIPTION
**Pull request by HowToLoLu**
## About The Pull Request
Fixes a thing that's been botched up since it was added by an older PR (around a year ago)

## Why It's Good For The Game
Helps avoid confusion like this, which just happened last night:
image

## Testing Photographs and Procedure

<details>
<summary>Before and After</summary>

**BEFORE**:
image

**AFTER:**
image

</details>
<details>
<summary>How I tested it</summary>

I implemented the following temp code.

Mandatory VIP Mission:
image

Mandatory Traitor VIP
image

Started up a test server, joined exploration, selected the mission, and took the shuttle on my way
Then I ghosted and jumped into the newly created antagonistic VIP

</details>

## Changelog
:cl:
fix: Exploration VIP targets now memorize why they have strange abilities, or an uplink in their head.
/:cl:

### CODE REVIEW

**Comment by HowToLoLu** [comment]
It seems like something is wrong with unit testing at the moment.

**Comment by EvilDragonfiend** [comment]
push any commit. that error sometimes happens.

**Review by EvilDragonfiend — CHANGES_REQUESTED** [review]
do the same to `/datum/orbital_objective/assassination`

**Comment by HowToLoLu** [comment]
> do the same to `/datum/orbital_objective/assassination`

Assasinations don't have this problem, it was only VIP recovery that seemed to have this issue

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
