### PR TITLE
removes the cold loop from meta kitchen coldroom

### LINKED ISSUE #2085: [Metastation] Cooling loop in kitchen is very bad with fastmos
image

Please remove the cooling loop from the metastation kitchen, at roundstart it lowers the pressure by so much that going into the backroom will throw you in the room and the pressure is low enough that you are oxygen starved. 

I've never understood this and its got no function other than "le epic half baked flavour" so maybe remove the lethal aspect of the chefs backroom ?

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

removes the coldloop from the kitchen backroom on meta 

fixes #2085

## Why It's Good For The Game

useless half baked flavor that made the atmosphere dangerous in the backroom and activley caused decompression sucking stuff in, no other map has this aswell.

## Changelog
:cl:
del: Removed the cold loop in the kitchen backroom on meta.
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Might just be a TG thing but I think the tiles themselves are also set to have a cold temperature at roundstart. Did you actually check that the cold room is no longer cold?

**Comment by ghost** [comment]
> Might just be a TG thing but I think the tiles themselves are also set to have a cold temperature at roundstart. Did you actually check that the cold room is no longer cold?

look at the vars for the floors they are the same as everywhere else.

**Comment by PowerfulBacon** [comment]
I believe /turf/open/floor/plasteel/kitchen_coldroom/freezerfloor starts cold in the code, might wanna check that to make sure

**Comment by ike709** [comment]
It does: 

```
#define KITCHEN_COLDROOM_ATMOS		"o2=33;n2=124;TEMP=193.15" //-80°C kitchen coldroom; higher amount of mol to reach about 101.3 kpA

/turf/open/floor/plasteel/kitchen_coldroom
	name = "cold room floor"
	initial_gas_mix = KITCHEN_COLDROOM_ATMOS

/turf/open/floor/plasteel/kitchen_coldroom/freezerfloor
	icon_state = "freezerfloor"
```

@BeloneX Please check yourself before you wreck yourself

**Comment by ghost** [comment]
> It does:
> 
> ```
> #define KITCHEN_COLDROOM_ATMOS		"o2=33;n2=124;TEMP=193.15" //-80°C kitchen coldroom; higher amount of mol to reach about 101.3 kpA
> 
> /turf/open/floor/plasteel/kitchen_coldroom
> 	name = "cold room floor"
> 	initial_gas_mix = KITCHEN_COLDROOM_ATMOS
> 
> /turf/open/floor/plasteel/kitchen_coldroom/freezerfloor
> 	icon_state = "freezerfloor"
> ```
> 
> @BeloneX Please check yourself before you wreck yourself

okay fixed

**Comment by ike709** [comment]
...all you did was change it to a parent type with a different icon

The actual fix would be to remove `initial_gas_mix = KITCHEN_COLDROOM_ATMOS`

It's painful when someone *obviously* doesn't test their PR.

**Comment by ike709** [comment]
Closed in favor of https://github.com/BeeStation/BeeStation-Hornet/pull/2177

**Pull request closed without merging**
