### PR TITLE
Button timer countdown effect 

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Adds in a countdown timer effect on spells.

## Why It's Good For The Game

It looks good and provides feedback of how long the cooldown is left.

https://youtu.be/1KUcwG-3Uws (make sure to like comment and subscribe 😳 )

Unfortunately due to the way map text works, the actual text shows up behind the spell icon which is kind of annoying but I don't think I can change that.

## Changelog
:cl:
add: Spells with cooldowns now have a timer effect.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Gathering screenshots and videos

**Comment by PowerfulBacon** [comment]
Wait, I might actually be able to fix the map text by attaching it to the timer instead

**Comment by Tamuren** [comment]
Can this work with nanite dermal buttons?

**Comment by PowerfulBacon** [comment]
> 
> 
> Can this work with nanite dermal buttons?

I don't think they have a cooldown and they don't use procholders, so I don't think so

**Review by zeskorion — APPROVED** [review]
looks solid enough to me. video shows it working and the procs look solid

**Pull request merged**
