### PR TITLE
Allows the AI and cyborgs to join midround

### PR DESCRIPTION
**Pull request by Cenrus**
## About this pull request

The code for midround AI connections was functional, but no midround AI or cyborg positions were available. Now it is possible for the AI and one cyborg to join midround. 

## Why it's good for the game

More job options for players who join the shift late.

## Changelog

:cl:
add: AIs and cyborgs can now latejoin.
/:cl:

### CODE REVIEW

**Review by ike709 — APPROVED** [review]

**Comment by Crossedfall** [comment]
Does this actually make in-game sense? I'm a little skeptical here to be honest. If I can late-join as a cyborg/AI that removes an entire aspect of the roboticist's job does it not? At best this might make sense if there were some 'dusty' spare units placed on the map that players could take over, then once those were full they'd have to be crafted by the science team. 

Also is this change meant only for Golden/Sage or is it meant to be applied to both servers?

**Comment by Cenrus** [comment]
The AI late join makes IC sense, the AI is downloaded into an inactive AI core in the satellite chamber. Due to conflicts, Roboticists should refrain from building additional AIs unless the current one is dead and impossible to revive, or during emergancies such as war operatives. As for the cyborg, the station is supposed to start with one to assist the AI. This is especially important when the AI is malfunctioning as having a cyborg increases the AIs chance of success.

**Review by MarkSuckerberg — APPROVED** [review]
Needed, especially for MRP as usually no one is willing to become an AI midround through IC means, and it's really useful to have one.

**Comment by Crossedfall** [comment]
eeehh... Really nobody is willing to do it midround? I always remember getting tickets from people asking me/admins to make them AI midround or just spawning in as an assistant to be scooped into a robo frame. I guess so long as it's just limited to one of each it might be OK.

**Comment by MarkSuckerberg** [comment]
I'm focusing more on MRP, where everyone who's there actually has to do something instead of 1/2 the station being more or less expendable. I've just had people ask me to open a jobslot or something a lot more than I've seen people signing up to be borged/become an AI while already in round.

**Comment by Crossedfall** [comment]
Alllright. Let's give it a shot. This doesn't really need to be test merged since it's a config change. If it doesn't work I'll revert the config changes.

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
