### PR TITLE
Common typo fixes

### PR DESCRIPTION
**Pull request by imsynthex**
## About The Pull Request

Went through a list of common typos/misspellings and corrected them for the sake of consistency

## Testing Photographs and Procedure

It compiles
image

## Changelog
:cl:
spellcheck: fixed around 350 common misspellings and typos
/:cl:

### CODE REVIEW

**Comment by imsynthex** [comment]
Epic code owner moment

**Comment by itsmeow** [comment]
Giving the golden label to literal find replace typo fixes now are we

**Review by itsmeow — APPROVED** [review]
i painstakingly looked at 400 typos.

It does, indeed, fix the typos.

**Comment by Tsar-Salat** [comment]
There are also multiple misspellings of "Camouflage" (I'm under the impression there's only one correct spelling for it)

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
