### PR TITLE
Moves Adrenaline nanites back to the Augmentation tab

### PR DESCRIPTION
**Pull request by Kapu1178**
## About The Pull Request
Title. This doesnt change the unlock requirements.

## Why It's Good For The Game
It makes absolutely zero sense Adrenaline is in **WEAPONIZED** nanite programs. Its a completely defensive tool, and belongs back where it came from.

## Changelog
:cl:
tweak: Moves Adrenaline Nanites back to Augmentation tab. (Doesn't change unlock requirement)
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
Kapu fails to realize that extreme speed and healing can be used offensively against others like a weapon. Therefore the nanites are weaponized but not against their user.

**Comment by Kapu1178** [comment]
> 
> 
> Kapu fails to realize that extreme speed and healing can be used offensively against others like a weapon. Therefore the nanites are weaponized but not against their user.

"Weaponized"  - to adapt for use as a weapon of war

Adrenaline is extremely useful in combat, yes, but it is not *a weapon*. Fists, guns, and toolboxes are *weapons*. Adrenaline belongs in Augmentation with all the other non-weapon combat programs.

**Comment by TeomanTheGreat** [comment]
> > 
> > 
> > Kapu fails to realize that extreme speed and healing can be used offensively against others like a weapon. Therefore the nanites are weaponized but not against their user.
> 
> "Weaponized"  - to adapt for use as a weapon of war
> 
> Adrenaline is extremely useful in combat, yes, but it is not *a weapon*. Fists, guns, and toolboxes are *weapons*. Adrenaline belongs in Augmentation with all the other non-weapon combat programs.

Fair enough

**Comment by bloons3** [comment]
For balance reasons it was moved to illegal technology, since fuck tiders.

Address the original change reasons: https://github.com/BeeStation/BeeStation-Hornet/pull/4337

**Comment by Kapu1178** [comment]
> 
> 
> For balance reasons it was moved to illegal technology, since fuck tiders.
> 
> Address the original change reasons: #4337

This doesnt undo the balance change. This just changes what tab its under. Its still locked behind Military Nanite tech

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
