### PR TITLE
GlowStation fixes: merge conflict-less edition

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request
This is just https://github.com/BeeStation/BeeStation-Hornet/pull/8469 with extra fixes

## Why It's Good For The Game
Mapping errors = bad

## Testing Photographs and Procedure
See original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/8469

</details>

## Changelog
🆑 spockye
del: Removed autolathe from library (glowstation)
fix: fixed Piping errors (glowstation)
fix: fixed wiring errors (glowstation)
fix: fixed misplaced consoles (glowstation)
fix: fixed missing air alarms (glowstation)
fix: fixed missing walls (glowstation)
fix: fixed tiling under windows (glowstation)
fix: fixed missing disposal bins (glowstation)
fix: fixed missing disposal tubes (glowstation)
fix: fixed wrongly placed disposal tubes (glowstation)
fix: fixed decals inside the mountain (glowstation)
fix: fixed pixelshifted wallmounts (glowstation)
fix: fixed misplaced flooring (glowstation)
fix: fixed wood lining i accidentally placed in the last pr (glowstation)
fix: fixed pixelshifted apc's (glowstation)
fix: fixed random chair on exploration_fland
fix: fixed missing tiny fans on exploration_fland
fix: fixed an "s" in xeno shutters (glowstation)
fix: fixed shuttle floor in SM waste room, burning through the floor
/🆑

### CODE REVIEW

**Comment by Absolucy** [comment]
You can close this PR if https://github.com/BeeStation/BeeStation-Hornet/pull/8469 gets the same fixes

**Comment by itsmeow** [comment]
Confused, did you just copy the PR and address my review?

**Comment by Absolucy** [comment]
@itsmeow yeah, since it didn't seem to be going anywhere, and I was getting annoyed at the issues with glow

**Comment by spockye** [comment]
Totally forgot. I'll close mine

**Review by PowerfulBacon — APPROVED** [review]

**Review by PestoVerde322 — APPROVED** [review]
Doublechecked, everything looks good to go, approved.

**Pull request merged**
