### PR TITLE
mirrors reflect lasers

### PR DESCRIPTION
**Pull request by CommandBlockGal**
## About The Pull Request

it makes mirrors reflect lasers

## Why It's Good For The Game

its intuitive id say, when light hits a mirror the expected reaction is for it to get reflected

## Changelog
:cl:
add: mirrors reflect lasers
/:cl:

### CODE REVIEW

**Review by utilbird — CHANGES_REQUESTED** [review]
This should be handled in `handle_ricochet()`. You should just be able to copy it from wall code and remove the AOA limit

**Comment by CommandBlockGal** [comment]
> This should be handled in `handle_ricochet()`. You should just be able to copy it from wall code and remove the AOA limit

it seems the wall code doesnt work for the mirror, it does get reflected but the way it does it ends up just  shooting back at the mirror, could i instead just use the current code but on handle_ricochet() instead?

**Comment by utilbird** [comment]
weird, not sure why that'd happen. Can you commit it so I can take a look? It should work fine unless you got the angles flipped

**Review by PowerfulBacon — APPROVED** [review]

**Comment by CommandBlockGal** [comment]
guess it was good enough lol

**Pull request merged**
