### PR TITLE
Securitron changes

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
-griefsky is now EMP resistant- emping him only stuns him for 0-4 seconds
-beepsky now does stamina damage, but is also a bit faster
-bots now properly call spacemove() when trying to move in space

## Why It's Good For The Game
beepsky stuns bad, griefsky cheese bad.

## Changelog
:cl:
balance: beepsky now uses stamina damage
balance: griefsky is now EMP resistant
fix: most bots no longer freely move in space 
/:cl:

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
Can you also buff hallucination beepski while you are at it?

**Comment by LordSaladin** [comment]
firebot should should be able to move in space considering it is a fire hydrant on wheels.

**Comment by zeskorion** [comment]
> firebot should should be able to move in space considering it is a fire hydrant on wheels.

...sure.

**Comment by zeskorion** [comment]
firebots have spacewalk set to true already!

**Comment by PowerfulBacon** [comment]
Beepsky nerf 😞

**Comment by Bastian0930** [comment]
I think zesko got cucked by a beepsky so he's nerfing it

**Pull request closed without merging**
