### PR TITLE
Revert "[ready] Pubby Engine Easy Mode"

### PR DESCRIPTION
**Pull request by yyzsong**
## About the PR
Reverts BeeStation/BeeStation-Hornet#4293

## Why it's good for the game
Shitty spaghetti mess, covered in wall pipes and double pipes. Why would you do this, i'm sobbing.
Filter setup isnt even changed from the old, shit version

## Changelog
🆑 
del: The new pubby engine
/🆑

### CODE REVIEW

**Comment by OceanFish1** [comment]
pipes funny

**Comment by BrumalLake** [comment]
image
wow, yeah it just dumps unfiltered sm coolant mixed with waste into the burn chamber
the teg should at this point just be replaced with collectors
both of the filters have to filter something for the mixer to work as well, and its not even the only thing feeding into the vent
even if you filter the presumed plasma and oxygen with both filters, one filter will eventually get clogged unless you have the perfect ratio in the gas mixer, plus again, it doesnt even let you filter out the coolant you're using before attempting to put it into the burn chamber

**Comment by Sinestia** [comment]
You know it'd probably have just been more productive to fix the pubby SM section on the wiki than to remap it

**Comment by KubeRoot** [comment]
> wow, yeah it just dumps unfiltered sm coolant mixed with waste into the burn chamber

As far as I can tell it only dumps the filtered gasses into burn chamber? There's two pipes above that vent. I'm quite confused by what you're saying - while I agree that the filter is dumb and would likely lead to a delamination, the rest seems fine. The filtered gasses are sent to burn chamber, while the rest of the coolant continues. The oxygen and plasma scrubbed from SM burn in the burn chamber, and the exhaust is sent to the TEG.

**Comment by BrumalLake** [comment]
> 
> 
> > wow, yeah it just dumps unfiltered sm coolant mixed with waste into the burn chamber
> 
> As far as I can tell it only dumps the filtered gasses into burn chamber? There's two pipes above that vent. I'm quite confused by what you're saying - while I agree that the filter is dumb and would likely lead to a delamination, the rest seems fine. The filtered gasses are sent to burn chamber, while the rest of the coolant continues. The oxygen and plasma scrubbed from SM burn in the burn chamber, and the exhaust is sent to the TEG.

nevermind the image was low res from the original pr and they do this awful piping where they overlap 2 turns over each other by taking one all the way from the other side and it looked like a 4 way manifold

**Comment by Crossedfall** [comment]
Outside of maybe needing some recoloring on a few of the pipes and  two kind of yucky wall pipes, I don't really see the need for a full revert.

**Comment by SergeiKoralev** [comment]
There are exactly three (3) wall pipes that I can think of without looking at the engine. 

> Why would you do this, i'm sobbing.

Because people couldn't not blow up, that's why.

> Filter setup isnt even changed from the old, shit version

Change it in round. This setup is designed to be sufficient for normal operations, not an engineer's wet dream if they just want to sit on their thumb all shift.

**Comment by SergeiKoralev** [comment]
Alright, time to respond more in full to this. First, I think it's better to have more than a 7x6 picture to show what the engine currently looks like. 

image


With that out of the way let me get on with le points 

> Shitty spaghetti mess,

I believe that the best two reasons to say it looks like spaghetti is due to a few things that realistically could probably be done cleaner, but just in their own right aren't bad.
A: In mapping tools you see every pipe, including the hidden scrubbers and distro pipes.
B: The paid by the meter piping of the plasma injection into the cold loop.
C: The old filter section not having been cleaned up. 

There are a few fixes for this, most have their own specific methods that would likely work out alright but be odd or quirky in some way or another. However, as said before, this isn't really a decisive problem when considering that if you want to make modifications you totally can without any major issues. 

>covered in wall pipes and double pipes.

There are exactly two (2) wall pipes. If you find double pipes (as in there is a tile with two pipes that share a layer and direction of inlet or outlet) I would be more than happy to fix them. 

>Why would you do this, i'm sobbing.

Default engines aren't there to make you happy. They're there to be simple enough and powerful enough that the station doesn't loose power when no engineers sign up. 

>Filter setup isnt even changed from the old, shit version

Not intended to be optimal. Get the plumber to change it.

>while I agree that the filter is dumb and would likely lead to a delamination,

The filtering point actually decreases the delamination risk if people are smart enough to realize that plasma+oxygen+igniter=fire and configure things to do that. It removes the Nitrogen (core gas/coolant) from the burn mix (everything else ideally), before going into the burn chamber, reducing core temperature more effectively with the heat exchanger. 

>overlap 2 turns over each other by taking one all the way from the other side

This is a minor optimization and beautification routing which is actually completely valid for in-game implementation by people building or replacing pipes as well. It provides (marginally) more time for the gasses from the outlet to burn before meeting the scrubber, keeps the vent off the injector (it can't go on the scrubber because that actually isn't mechanically valid), and overall just mirrors most combustion chambers in game more accurately. 

The best solution I see at the moment to slightly de-weird the piping, and I do admit it's a bit of an odd piping setup, is to move the entire core (and by extension emitters) two meters to the left. 

The overall intent of 4293 was to provide a retrofit since things kept exploding consistently. I looked at it more as an engineer designing a retrofit might have, and followed that as my guidance. So does it feel like it wasn't there to start with? Yeah. That was, also, kind of the point. It was a safety measure that got bolted on, not an engine re-design.

**Comment by BrumalLake** [comment]
You didn't really say anything about the gas mixer, and i guarantee that it will cause the coolant to clog once one side gets unbalanced enough and jams, unless you can get the golden ratio which is impossible as the amount of oxygen produced fluctuates depending on temperature

**Comment by SergeiKoralev** [comment]
> and i guarantee that it will cause the coolant to clog once one side gets unbalanced enough and jams,

The mixer on base setting didn't jam during a roughly 90 minute test, nor were pressures in the pipe close to jamming, so this isn't a concern with the current setup. If rounds go long enough that it becomes a concern then the engineering team hopefully has it in their right mind to check the pressures there. It might be a reasonable QOL change to add meters to those pipes.

**Comment by KubeRoot** [comment]
> The mixer on base setting didn't jam during a roughly 90 minute test, nor were pressures in the pipe close to jamming, so this isn't a concern with the current setup. If rounds go long enough that it becomes a concern then the engineering team hopefully has it in their right mind to check the pressures there. It might be a reasonable QOL change to add meters to those pipes.

I will say, while it might take a long time to jam during normal operation, it will almost certainly jam very quickly and need to be removed/cleared up *if* the SM, for any reason, becomes too energetic and the gas is hot. The issue is, if the pressure in any of those pipes goes over 4500kPa, the filter on that pipe will completely stop working which will lead to scrubbers stopping entirely as well.
While I understand the engine should be saboteagable and sub-ideal, this is a case where the cooling system will completely stop working and require reconfiguration for it to be able to continue at all - I don't think there's any other situation where that will currently happen.

**Comment by SergeiKoralev** [comment]
You could always just set the filters to "nothing" if things are going that badly. That would get the gas flowing again quick and easy. After that it's just a matter of putting the fusion fire in the pipes down properly.

**Comment by SergeiKoralev** [comment]
can this get closed as abandoned?

**Pull request closed without merging**
