### PR TITLE
Departmental Skirts: Engineering

### PR DESCRIPTION
**Pull request by Hardly3D**
## About The Pull Request
Adds skirts for Atmos Tech, Station Engineer and CE
hTeLv8lKtO

Sprites made by @Naevii

## Why It's Good For The Game
Variety, and engineering is the only department that lacks jumpskirts.

## Changelog
:cl: Hardly, Naevii
add: Atmos Tech, Engineers and Chief Engineers now have their own jumpskirts.
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
OSHA violation

**Comment by ghost** [comment]
Moving toward "higher roleplay standards", but not enforcing safe work attire? Whether or not this PR gets merged will decide the future of this codebase

**Comment by Howluinb** [comment]
> OSHA violation

suck my cock osha
image

**Comment by Hardly3D** [comment]
Fixed the conflict (I think)

**Comment by Hardly3D** [comment]
Oh my god what the hell have I done, rebasing was a mistake, closing til I figure out.

**Comment by ivanmixo** [comment]
Oh my god why didn't you just ask me for help

**Comment by Crossedfall** [comment]
I'm down for skirts being added as an option for a majority of departments, but this doesn't make IC sense. :key:

**Comment by KubeRoot** [comment]
I haven't tried it, but it seems to me the items don't have a separate sprite from jumpsuits; is this correct?

> this doesn't make IC sense

I don't think that's much of an issue. It's a small lighthearted change to allow players some more customization while fitting the game style. Most of the time you probably wouldn't even notice in-game, and the few times you do, you can laugh it off in-character.

**Comment by Archanial** [comment]
🔑

**Pull request closed without merging**
