### PR TITLE
Re:Readds the headcrab back into the golden slime pool.

### PR DESCRIPTION
**Pull request by Moccha-Bee**
## About The Pull Request
Yeah that's right its back, since lings got nerfed and mrp is just lrp and rounds rarely go over 50 minutes this addition will be more than balanced,
image

## Why It's Good For The Game
Slugs have always been funny creatures and now they can be spawned with the golden slime hostile injection, and since changelings have been nerfed, now is time for the comeback..

## Changelog
:cl:
add: HeadCrab back into the golden slime hostile pool.
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
Headspider you mean

**Comment by LordSaladin** [comment]
now xeno has a reason to go for rainbows.

**Comment by TeomanTheGreat** [comment]
@zeskorion look at this bruh

**Comment by february-ops** [comment]
As a xenobio man, please give me more powergame there isnt enought already

**Comment by zeskorion** [comment]
This has been prd many timss before, reverted and/or closed each tims.

**Comment by Moccha-Bee** [comment]
> This has been prd many timss before, reverted and/or closed each tims.

We all literally agreed that this was only going to be readded if changelings received a nerf and that's what happenend they were nerfed, and now im back with the pr. What do the other maintainers have to say about this

**Comment by Flakkyboo** [comment]
Zesko man bad

**Pull request closed without merging**
