### PR TITLE
Adds all missing pAI inhands, head sprites and several new holochassis!

### PR DESCRIPTION
**Pull request by Pirill**
## About The Pull Request

This PR adds around 200 total sprites to the pAI repertoire to bring them all in line:
- Adds in-hands for every single pAI that was missing them;
- Adds head-worn sprites for every single pAI that was missing them;
- Tweaks the existing monkey pAI inhands to match the chassis better;
- Rearranges the pAI list in alphabetical order in both code, sprites and in-game picker;
- Adds three new pAI chassis! The fierce (but small) carp, the if-you-say-Goon-inspired-I'll-strangle-you bee and the non-copyright infringing phantom! They have full sets of inhands, resting sprites and head-worn sprites and you can see them in the gif below!

Last, but CERTAINLY not least, a good amount of sprites were adapted partially from the amazing work @kit-katz did on the **Pethats PR (#4316)** Absolutely awesome work on that!

## Why It's Good For The Game
- Gives pAIs some much needed love
- Adds like 0.005% more bee to Beestation

## Changelog
:cl:Pirill, kit-katz
add: Adds three new pAI holochassis: carp, bee and phantom!
imageadd: Adds inhands and head-worn sprites for all other pAI chassis that were missing them
/:cl:

### CODE REVIEW

**Comment by Pirill** [comment]
And here's a clearer image of most of the new sprites. Doesn't include the animations for the snake inhands and Bee.
image

**Comment by Crossedfall** [comment]
All look good to me. Only question I have is if the Bee sprites are a derivative of Goon's bees... If so, they need to be moved to the special Goon sprites folder to abide by that license.

**Comment by Pirill** [comment]
> All look good to me. Only question I have is if the Bee sprites are a derivative of Goon's bees... If so, they need to be moved to the special Goon sprites folder to abide by that license.

Nope! They're made by me from scratch based on this plushie design. https://images-na.ssl-images-amazon.com/images/I/71SxeUp7bPL._AC_SL1500_.jpg

**Review by Ivniinvi — COMMENTED** [review]
The phantom_rest sprite's three other directional sprites are hawk sprites, the intent is probably to have it as non-directional.

**Comment by Crossedfall** [comment]
> Nope! They're made by me from scratch based on this plushie design. https://images-na.ssl-images-amazon.com/images/I/71SxeUp7bPL._AC_SL1500_.jpg

Splendid. Had to ask, even if your PR body implied otherwise. 😉

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
