### PR TITLE
fix loading templates in new z-levels being off by one turf, fix loading map template runtime due to atmos

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

tgstation/tgstation#54135
tgstation/tgstation#44885

## Why It's Good For The Game

image

atmos get re-enabled after in inittemplatebounds() anyways

## Changelog
:cl: dennok, thechosenevilone
fix: fixed loading map templates on new z-levels causing them to be off by one turf in the x/y axes.
fix: some runtimes
/:cl:

### CODE REVIEW

**Review by Archanial — DISMISSED** [review]
seems good

**Comment by qwertyquerty** [comment]
@jupyterkat can you explain the logic behind the math in this PR?

**Comment by jupyterkat** [comment]
It finds turfs that the template touches and deletes the air adjacency list on those turfs, so it can’t move and cause trouble while turfs are still spawning in. Then the list is rebuilt later after the spawning is done

**Comment by jupyterkat** [comment]
Included with #5288

**Pull request closed without merging**
