### PR TITLE
MetaStation changes, fixes

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Similar to #637, this changes Medbay a little to include a self-service room with a cryopod, trying to make use of the useless Medbay desk space and incorporate cryopods better. 

https://imgur.com/Usm1LKQ

## Why It's Good For The Game
Medbay desk is 100% useless on Bee, and afk's are still a problem

## Changelog
:cl:
tweak: Medbay guard's office moved to desk area
tweak: Small room added next to Medbay storage with a few medkits and a cryosleeper.
tweak: Medbay central shower changed to no slip.
tweak: Scrubs, MD is now set to "on" at round start, like every other bot in the game. Originally, he could only be accessed by silicons
add: A few line decals in airlocks
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Desk was at least useful for waiting for people to show up. Also, having nothing but a reinforced table between the tiders and a sec locker isn't great.

**Comment by jlsnow301** [comment]
Alternatively, could put reinforced glass facing West at the lobby and the south wall facing medbay would be table/airlock

**Comment by qwertyquerty** [comment]
Just do double thindoors

**Comment by MarkSuckerberg** [comment]
No iconic pepper spray dispenser, recharger and sec locker WAY too accessible, and why are security guards doubling as receptionists? There still should be a reception somewhere, but I don't think the sec checkpoint should be it.
nopepperspray

Just a suggestion, but there are coloured variants of the noslips that fit in better if you want to use them.
noslips

*Please* don't leave those in.
badtiles

I know this was there already, but I've never liked it like that, although since space is an issue, I guess it's fine.
console

As I said with delta, I enjoy the reception area and I'd prefer there was either a new reception or this gets moved somewhere else.

**Review by qwertyquerty — CHANGES_REQUESTED** [review]
Fix the things

**Comment by Fronsis** [comment]
Had to make an account just for this

IMO having a reception office it's classic in all of the maps some doctors DO use it just to stand there waiting for someone to come in/check the vitals of the crew to go run and save them or inform via radio, even if we now have paramedics with their own crew-monitors i mean even CMO office doesn't have that machine.

So yeah and ofc the Sec office need to stay for obvious reasons.

The idea of having a green cryo there it's goo(could be placed somewhere else)since  i could just drag afk doctors/ssd people that got clonned so at least some slots get to be open (Since the HoP never does it and barely anyone use the cryo greens at dormitories) however i don't think it's a neat idea to have a self check i mean the equivalent of the ''self check'' on most of the maps i've seen are seen are on the tables outside. I would prefer having them there rather than this mini rework.
medbay

Also uh is it me or it's the lathe machine gone?

**Comment by jlsnow301** [comment]
meh

**Pull request closed without merging**
