### PR TITLE
Fixes stasis beds not having a surgery success probability 

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
They now have the same surgery success probability, which is 90% (10% higher than that of a surgical table).

## Why It's Good For The Game
Right now trying to do surgery on one of these fails much more than it should. 

## Changelog
:cl:
fix: Stasis beds now have a surgery success probability of 90%, 10% higher than that of an operating table.
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Why are these higher than operating tables? In my opinion they should be lower.

**Comment by VictorVow** [comment]
@qwertyquerty they take research, more materials and effort to construct than surgical tables. How about making them equal to them at least?

**Comment by zeskorion** [comment]
> @qwertyquerty they take research, more materials and effort to construct than surgical tables. How about making them equal to them at least?

make them lower so that they need anaesthetic

**Comment by VictorVow** [comment]
Surgical tables are 80% success so they need anaesthetic, I'm proposing to adjust it to that level also. 

Remember the whole point of having one of these is so that doctors can now use Tend Wounds surgery. Nobody is going to want to do that if it has less than 80% success rate because then even with anaesthetic you'll still get failures.

**Comment by MCterra10** [comment]
It's almost like stasis beds shouldn't be getting fazed in

**Pull request merged**
