### PR TITLE
Nerf venus human trap

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

This motherfucker is INESCAPABLE if you are in space. Literally cannot escape. It's too fucking fast and can instantly pull you anywhere and spacewalk. Why the fuck is this thing so powerful. It does 25 DAMAGE PER HIT already it doesnt need to constantly be performing stuns as well.

HOW DARE you walk within range of one That just HAPPENS to be in your way! HOW DARE YOU!! DIE WITHIN 3 HITS!!! THIS IS FUN GAMEPLAY GUYS!!!!

## Why It's Good For The Game

Not fucking dying for no reason is pretty cool

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

I hate these shits so much I hate them I'm not spawning one fuck you

</details>

## Changelog
:cl:
fix: Fixes venus human traps. (They have been nerfed, these infernal beings)
/:cl:

### CODE REVIEW

**Comment by CydiaLamiales** [comment]
Ghost controlled venus human traps when

**Comment by PowerfulBacon** [comment]
These things have so little health, I've never actually seen any get a kill for how strong they are meant to be considering they are a late-game vine threat

**Comment by itsmeow** [comment]
They can fuckin spacewalk though. WHY

**Comment by PowerfulBacon** [comment]
This PR is mis-labelled as a fix PR instead of a balance and is a clear result of a quick reaction due to dying to one as there is no testing evidence or proper reasoning given for these nerfs. From what I have seen these are way weaker than they should be and I haven't seen anyone die to them yet due to them only taking a few hits to kill. Closing this PR due to not following standard PR protocols.

**Comment by itsmeow** [comment]
??????

**Comment by PowerfulBacon** [comment]
> They can fuckin spacewalk though. WHY

I'm not sure, ideally their AI should stay inside the vines and pull people in.

**Comment by itsmeow** [comment]
The fucker chased me through space, continually stabbing me, and was inescapable

**Comment by itsmeow** [comment]
Maybe they should just not be able to grapple people on space tiles

**Comment by PowerfulBacon** [comment]
Anyone in space they should grapple and pull into the depths of the vines, rather than chase them out. They should act defensively but I don't think should be chasing people out of the vines as that is where they are strong.

**Comment by PowerfulBacon** [comment]
If you want to change their behaviour to make them more defensive then I am fine with that, but all PRs need to follow the pull request standards.

**Comment by DrDuckedGoose** [comment]
1984

**Pull request closed without merging**
