### PR TITLE
Title screens from the lobby art contest of 2022

### PR DESCRIPTION
**Pull request by PestoVerde322**
## About The Pull Request

This PR implement some new splash screens from the 2022 lobby art contest (see: https://forums.beestation13.com/t/the-return-of-the-lobby-art-contest/19215).

This also adds the 2nd and 3rd place winner of the contest, due to the high quality and Crossed's approval, see below for what splashscreens will be implemented.

Due to extreme outside pressure, i've also added Bacon's flying ian and Rac-off's maint disky

## Why It's Good For The Game

it's a long overdue promise, so new screens good.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

The winner of the contest, TonesofBones's “The Robusting Lesson of Dr. Nicolas Tide”

TonesofBones

The 2nd place, Heepox's “GTFO MY ENGINE BITCH” (tweaked in-game to be less flashy)

Heepox

The 3rd place, Naevi's “Peach Fights for Syndicate”

Naevi

EXTRA:

PowerfulBacon's "Flying ian"

PowerfullBacon

Racc-off's "Maint disky"

Racc-off

</details>

## Changelog
:cl: TonesofBones, Heepox, Naevi, Racc-off, PowerfulBacon
add: FIVE brand new Splash screens!
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Ngl I was hoping you'd add all of the good ones and not just the winners.

**Comment by PestoVerde322** [comment]
> Ngl I was hoping you'd add all of the good ones and not just the winners.

which one i should add aside the winners really?

**Comment by ike709** [comment]
All of the ones that look good. Ask on discord about specifics if you're unsure.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
I've added them to the server, but for merging into the repo they need to end with 17x15.dmi in order to get the correct aspect ratios

**Review by Crossedfall — APPROVED** [review]

**Review by PowerfulBacon — APPROVED** [review]

**Comment by Fronsis** [comment]
Have yet to  see the Heepox SM girl or Ian we sure they're in :tragedy:

**Pull request merged**
