### PR TITLE
Moves security techfab to the warden room

### PR DESCRIPTION
**Pull request by DarnTheMarn**
## About The Pull Request

Moves the security techfab from the security gear rooms to the wardens office

## Why It's Good For The Game

Now people can't bypass the warden and HOS' decision on what to give out by simply printing their own mindshield pins, ion carbines, and telescopic shields. 

Warden buff!

## Testing Photographs and Procedure

<details>

https://github.com/BeeStation/BeeStation-Hornet/assets/117550914/65572602-485d-48a8-a897-d56f26a5baef

<summary>Screenshots&Videos</summary>

</details>

## Changelog
:cl:
add: Added a new armory techfab to the armory, and placed the spare board in the HOS locker
tweak: Security techfab board is now in the wardens locker
tweak: Redistributed armory tier equipment to the armory techfab, this includes lethal ammo, weaponry, firing pins, shields, mech weaponry, and the like
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
I like this, but it feels like both techfabs are then quite... barren in terms of amount of items available to be printed. I'd almost just move the entire security techfab to the armoury instead.

**Comment by DarnTheMarn** [comment]
> And if it has to be constructed as you showed in the video

It does not have to be constructed, I was just showing off where I put the spare board. As for the security techfab now lacking substance, yeah it does a little bit. But it still has enough useful things that moving everything to the armory one would be annoying.

**Comment by Fronsis** [comment]
Good change, interesting to see how it's gonna play out! You basically didn't remove anything on armory per se you just stacked the objects to make space?

**Comment by DarnTheMarn** [comment]
> ! You basically didn't remove anything on armory per se you just stacked the objects to make space?

The only thing that got removed was one of the standing flashers, so yeah nothing of use got removed.

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
I don't recommend you act on this immediately and wait for further dev input, but this feels like an overengineered solution - Security equipment should all come from the same fab for simplicity, and that fab should be located ~~in the armory~~ within the warden's purview on all maps. 

Even for the simpler stuff that is printable, security having an extra layer to obtaining more gear than is initially laid out is good. In cases where there is nobody with armory access it sounds like a good excuse to promote existing security to being an HoS.

**Comment by MarkusLarsson421** [comment]
> Even for the simpler stuff that is printable, security having an extra layer to obtaining more gear than is initially laid out is good. In cases where there is nobody with armory access it sounds like a good excuse to promote existing security to being an HoS.

What if they had something like the Robotics Exosuit Fabricator? A Weapon Fabricator. Give it the same icon and such. Maybe require weapons to be assembled similar to Cyborgs and Mechs?

**Comment by DarnTheMarn** [comment]
I'll wait for more feedback, but if splitting the techfab is off the menu I would like to place it in the warden's room not the armory for two reasons, it gives the warden a little more to do, and it prevents it being a free for all on the gaming techfab items as soon as the armory is open for whatever reason.

**Comment by Rukofamicom** [comment]
Already answered this in discord, but posting it here for public visibility:

> I would like to place it in the warden's room not the armory

This is 100% fine with me, near identical level of restriction for all other parties and yet more convenient when it comes to the warden doing their job of controlling how extra equipment is distributed to security.

**Comment by DarnTheMarn** [comment]
I won't include this in this PR whichever way it ends up being, but it would be interesting to add alert level checks to printing specific items. Some items like the Hades mech gun should be red alert since it's a lethally burning, indiscriminate weapon while something like the telescopic riot shield could be locked to blue alert since it's the equivalent of the normal riot shield you can get on blue.

**Comment by PestoVerde322** [comment]
Techfab for guns in armory, techfab for rest in office, and a reloading table for ammos _wyci so you have to manually load your ammos instead of wasting materials by the techfab you greedy secoff/detective/deputized assistant >:(

**Comment by DarnTheMarn** [comment]
I have been convinced. Considering the security techfab will have all of like 3 useful items to print, I'll go ahead and remove the armory techfab and push the security techfab to the wardens room. Having everything on one techfab will still make it a little opaque as to what is armory equipment and what isn't when compared to splitting items across two techfabs, but it'll still be better than how it is now. I'll look at adding alert level checks to the items in question at a later time as I said earlier.

**Comment by MarkusLarsson421** [comment]
The alert check level would be great.

**Comment by Rukofamicom** [comment]
> Having everything on one techfab will still make it a little opaque as to what is armory equipment and what isn't

Ultimately as long as the fab is under the Warden's control I don't see this as an issue at all tbh.

Warden decides who gets what and when and there doesn't need to be a strict "this is allowed and this isn't" checklist.

**Comment by DarnTheMarn** [comment]
Since it got moved to the wardens room, they lose a photocopier on some maps and a table on others.

**Comment by Rukofamicom** [comment]
You've requested my review but this is still conflicting

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
Update changelog to reflect the actual changes and fix the conflicts and I'm 100% good with this change. 

~~I will be seeking admin and other maint input before merging though.~~

Received input from admins and some sec players and it's generally positive with a bit of hesitance for lack of wardens, but agreed it just results in some forced entry by sec themselves (which already has to be done for armory if there's nobody to supply access when it is necessary)

**Comment by DarnTheMarn** [comment]
We love map conflicts. Sorry about that

**Comment by DarnTheMarn** [comment]
Directional lights merge conflicts got me fucked up. Closing this and opening a new PR that does the exact same thing since it's faster than solving all 300+ conflicts manually.

**Pull request closed without merging**
