### PR TITLE
[DRAFT] Library sanitation

### PR DESCRIPTION
**Pull request by Flakkyboo**
PLEASE NOTE THIS IS VERY MUCH A DRAFT. IT IS DIFFICULT TO TEST AS I AM HAVING DIFFICULTY SETTING UP A DATABASE FOR TESTING.

## About The Pull Request

Changes the existing library upload process needing an admin to review and accept your book before it is uploaded to the library.

If your upload request is not accepted after a certain amount of time it will deny automatically.

## Why It's Good For The Game

Once this is implemented we will prevent books like WGW and others to be uploaded.
Allowing us to remove existing explicit titles from the library.

Meaning players wont be banned for downloading explicit titles from the library and narrating them over Comms.

This will also hopefully encourage more serious book titles to be uploaded and added to the games lore.

## Changelog
:cl:
code: changed library upload code to now require and admin review before upload.
/:cl:

### CODE REVIEW

**Comment by BettonnCZ** [comment]
One day while Andy was masturbating, Woody got wood. He could no longer help himself!

**Comment by ACanOpener** [comment]
Almost no non-joke books exist, if we make admins need to review them, no books will ever be contributed.

**Comment by BettonnCZ** [comment]
facts, most of the books are meme autobiography or copypastas.

**Comment by Flakkyboo** [comment]
> 
> 
> Almost no non-joke books exist, if we make admins need to review them, no books will ever be contributed.



> 
> 
> facts, most of the books are meme autobiography or copypastas.

Its not up to me this is what the admins want as a result of the zero tolerance policy for ERP and explicit content

**Comment by Ohagi-Chan** [comment]
Is the grace period a config option?

**Comment by ike709** [comment]
Rather than hard-deny it after a set time, it should simply inform the user that the book is unlikely to be accepted or hasn't been reviewed or something. There should be a Pending Books verb for admins that shows all books that haven't been accepted/denied, and books that are still pending at roundend should simply be ignored as if they were denied.

**Comment by Flakkyboo** [comment]
Sure I'll look into that on the weekend when I get some time to work on it.

I'll need to rebased now that crosseds changes have merged but I hope atleast I have the right idea with how I'm coding it.

As I said it's difficult to test without a database so I'm working a lot slower than. I would like

**Comment by Crossedfall** [comment]
> As I said it's difficult to test without a database so I'm working a lot slower than. I would like

Ping me on discord when you're working on this and I'll help you get a little test environment setup. I can also help go over the changes to queries if needed.

**Comment by Flakkyboo** [comment]
> 
> 
> > As I said it's difficult to test without a database so I'm working a lot slower than. I would like
> 
> Ping me on discord when you're working on this and I'll help you get a little test environment setup. I can also help go over the changes to queries if needed.

thank you. ill likely be working on it over the weekend should get the time then after work

**Comment by ike709** [comment]
Actually, the best thing to do would be to store all uploaded books in the DB, but flag them as "Pending Approval" (or similar). Only _approved_ books can be accessed by players. And admins could have a verb to get a list of "Pending Approval" books and approve/deny them whenever.

**Comment by ike709** [comment]
But still do the message to admins to give them an opportunity to immediately review it for approval/denial.

**Comment by Ohagi-Chan** [comment]
"store all uploaded books in the DB, but flag them as "Pending Approval" (or similar)"

On AuStation, downstream, I'd personally appreciate this.  It's not too uncommon that rounds here are played without a single admin active or even online.

**Comment by ike709** [comment]
Stale.

**Pull request closed without merging**
