### PR TITLE
Ports "Cleans up saycode by removing random hook stubs and using a signal where relevant"

### PR DESCRIPTION
**Pull request by Cenrus**
https://github.com/tgstation/tgstation/pull/44320

Code improvement incoming

## Why it's good for the game

Code improvement, cleanup, better maintainability.

## Changelog

:cl: Naksu
code: Cleaned up saycode
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
Travis appeased, the build error is caused across the board.

**Comment by ike709** [comment]
Conflicts.

**Comment by qwertyquerty** [comment]
Testmerging onto Sage

**Comment by ike709** [comment]
Qwerty said the testmerge went well so I'll murder him if this breaks stuff.

**Pull request merged**
