### PR TITLE
Roboticist jumpsuit + envirosuit resprite

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Resprites the roboticist suit sprites to more closely follow science's color theme.

image

## Why It's Good For The Game

Makes roboticist's suits more in line with the rest of science, while revamping the outdated sprites and keeping the black roboticist color theme.

## Changelog
:cl: Naevi, ivanmixo
imageadd: New roboticist enviro and jump suits
/:cl:

### CODE REVIEW

**Comment by OceanFish1** [comment]
Kinda too purple. I liked old suit more

**Comment by BrumalLake** [comment]
Doesn't that helmet have an uncanny resemblance to miners/chaplains

**Comment by ivanmixo** [comment]
> Doesn't that helmet have an uncanny resemblance to miners/chaplains

It does, but the purple is darker on the roboticist one. The suit will be the main giveaway that they're a roboticist.

**Comment by Sinestia** [comment]
Why? Old suit is v distinct and nice


This is 



Homogenization.

Besides, you don't necessarily see this with other departments. Gene and chemists have distinct colors.

**Comment by ivanmixo** [comment]
> Why? Old suit is v distinct and nice
> 
> This is
> 
> Homogenization.
> 
> Besides, you don't necessarily see this with other departments. Gene and chemists have distinct colors.

The old sprite is very crusty and old. This one has actual shading and all the other goodies. Their old uniforms look more in line with security than sci.

image

**Comment by Naevii** [comment]
> Why? Old suit is v distinct and nice
> 
> This is
> 
> Homogenization.
> 
> Besides, you don't necessarily see this with other departments. Gene and chemists have distinct colors.

Old color palette fitted security more and sprite was really outdated (somehow it got skipped during last science jumpsuit resprite)

I really wanted to keep dark scheme for robotics so i decided to switch red to purple and keep the rest black.
Alternative would be to keep red as a subcolor and use white as main color but this is used by brig physician. and ofcourse black and red is used by majority of security sprites. 

This resprite gives robotics more unique look.

**Comment by Isy232** [comment]
Maybe if you could have kept the original pattern and just made the red purple and added shading it would be a little better, or worse I'm not a spriter.

This is a definite improvement though.

**Comment by Sinestia** [comment]
> 
> 
> > Why? Old suit is v distinct and nice
> > This is
> > Homogenization.
> > Besides, you don't necessarily see this with other departments. Gene and chemists have distinct colors.
> 
> Old color palette fitted security more and sprite was really outdated (somehow it got skipped during last science jumpsuit resprite)
> 
> I really wanted to keep dark scheme for robotics so i decided to switch red to purple and keep the rest black.
> Alternative would be to keep red as a subcolor and use white as main color but this is used by brig physician. and ofcourse black and red is used by majority of security sprites.
> 
> This resprite gives robotics more unique look.

Sec doesn't need a monopoly on black and red 



> 
> 
> > Why? Old suit is v distinct and nice
> > This is
> > Homogenization.
> > Besides, you don't necessarily see this with other departments. Gene and chemists have distinct colors.
> 
> The old sprite is very crusty and old. This one has actual shading and all the other goodies. Their old uniforms look more in line with security than sci.
> 
> image

That is fair that on a technical level it's much better

**Comment by Naevii** [comment]
> Sec doesn't need a monopoly on black and red

they kinda do.
security should be easily distinguished from the rest of the crew, plus any uniform should be unique enough and consitent with department they work for.

**Comment by utilbird** [comment]
I like the red one more 😎. It'd be cool if it got a reshade

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
