### PR TITLE
Adds the old bananium floor sprite

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request
Reverts the bananium floor sprite from https://github.com/BeeStation/BeeStation-Hornet/pull/10276

## Why It's Good For The Game

Bananium is a meme mineral and what produces should be clown themed and not look like gold 

imagen

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

imagen

imagen

</details>

## Changelog
:cl:
tweak: adds the old bananium turf sprite back
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
link what this is a revert of

**Comment by Marshmellow105** [comment]
to be blunt the old one looks kind of shit compared to the new floor sprites, maybe adding bananas to the new one would help it feel more bananium?

**Comment by ClownMoff** [comment]
I think that is kinda the joke

**Comment by ClownMoff** [comment]
@PowerfulBacon Added testing evidence that it works (that's me using StrongDmm inside this branch)

**Comment by PowerfulBacon** [comment]
Opening strongDMM isn't testing, but I guess for this its not the most important

**Review by PowerfulBacon — APPROVED** [review]

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
