### PR TITLE
misc viro fixes

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
WHY DOES NO ONE REPORT FUCKING BUGS TO ME UNTIL A WEEK LATER JESUS FUCKING CHRIST IM FUMING

## Why It's Good For The Game
fixes shit

## Changelog
:cl:
fix: lizards no longer get cockwork tails
fix: macrophage works again
fix: pink macrophages work again
fix: biometallic replication and organic flux induction should scale with pituitary disruption again
fix: antivirus no longer works on humans. (why do biotypes suck ass)
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — COMMENTED** [review]
You sure this doesn't just put the tails on felinids instead of lizards?

**Comment by PowerfulBacon** [comment]
This 100% would just put it on felinids now instead of lizards since its now in the GLOB.human_tails list which felinids uses

**Comment by zeskorion** [comment]
> This 100% would just put it on felinids now instead of lizards since its now in the GLOB.human_tails list which felinids uses

i spawned a buncha felinids and they didnt spawn with it. I don't think they get a choice of tails, ill check again just in case

**Comment by zeskorion** [comment]
hm, you're right, why the fuck does the locked var not work

**Comment by zeskorion** [comment]
Alright:
mutant bodyparts are *fucked* and i aint gonna fix em in this pr. roundstart lists include all possible options (including burnt-off for moths)
i'd rather allow felinids to get em, as their random species tails are uniform, and they dont have spines that screw with the tails. it's purely cosmetic, anyways

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
