### PR TITLE
Resprites surgical equipment

### PR DESCRIPTION
**Pull request by Agameofscones**
## About The Pull Request

Resprites baseline surgical equipment (plus some of the bay12 legacy tool) as per @SomeAngryMiner request.

image

image

The cautery, energy saw and super matter sliver (pulse) are all animated.

Advanced surgical tools have not had their sprites changed.

- [x] SM surgical tools

- [x] Bloodfilter

- [x] associated inhands

## Why It's Good For The Game

TG legacy sprites have no unified palette, inconsistently scaling, and really hard to read inhands, this resolves all of that by redoing them.

## Changelog
:cl:
fix: Added the left hand surgical kit inhand that was missing.

imageadd: resprited the Surgical Saw, Energy Surgical Saw, Hemostat, Cautery, Surgical Drill, and Scalpel, Nuclear Scalpel, Nuclear Tongs, Super Matter Sliver.

/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Pretty sure we don't have bone gel.

**Comment by Agameofscones** [comment]
> Pretty sure we don't have bone gel.

> plus some of the bay12 legacy tool

**Comment by PowerfulBacon** [comment]
That hemostat looks a little bit like a dick

**Comment by SomeAngryMiner** [comment]
looking good.

**Comment by Isy232** [comment]
I like, maybe add some green to the handles of the hemostat to make it look less falice shaped though.

**Comment by PerishedFraud** [comment]
The hemostat being phallic is not a bad thing. Think of all the ERP jokes.

**Comment by eeSPee** [comment]
Why are they so dark?

**Comment by PowerfulBacon** [comment]
The hemostat looks really weird in my opinion and should be changed

**Comment by utilbird** [comment]
They look weird facing downwards

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Consider changing the hemostat

**Comment by Agameofscones** [comment]
> Consider changing the hemostat

image 👍

**Comment by PowerfulBacon** [comment]
I'll put it to testmerge to see howi t looks in game then merge if all is good

**Review by PowerfulBacon — APPROVED** [review]

**Comment by ike709** [comment]
Scalpel is absolutely massive, circular saw is rather small.

**Comment by ike709** [comment]
Retractors are also just kind of ugly.

**Comment by Agameofscones** [comment]
> Scalpel is absolutely massive, circular saw is rather small.

Scalpel is proportionally same to the previous sprite, its just flipped. Trust me it looks a lot weirder when its smaller.

Saw is a bit smaller than the original, proportionally making it larger is going to look strange relative to other tools, just warning.

Do you want me to adjust the saw and scalpel size(s)?

> Retractors are also just kind of ugly.

This isn't feedback, I can't do anything there. Sorry you think that. Do you find the colors, shape, shading, etc ugly? I need to know what specifically your issue raised is so I can address it

**Review by SomeAngryMiner — APPROVED** [review]
should be good to vote, now.

**Comment by ike709** [comment]
> should be good to vote, now.

> review wasn't addressed

wew

**Comment by SomeAngryMiner** [comment]
right, checking over that, now.

**Comment by ike709** [comment]
You were given feedback on discord a while back and I haven't seen any updates since. Plus I'm not fond of change for the sake of change to begin with.

So I'm going to mark this as stale.

**Pull request closed without merging**
