### PR TITLE
Wall-mounted hypospray, wall-mounted machines, minor machine construction refactor

### PR DESCRIPTION
**Pull request by KubeRoot**
## About The Pull Request

Contains the following three changes:

- Adds wall-mounted machines. Those are subtypes of machines, built on a wall placed from a wall frame, the same way normal machines are built. Thanks to being a subtype of machines, they share behavior like upgrading with them. Currently the only one is the wall-mounted hypospray.
- Minor machine construction refactor. Mostly, tool-based construction actions were moved from a giant `attackby` into `<tool>_act` procs. This was done to facilitate overriding individual construction actions in subtypes, right now only wall machines.
- Wall-mounted hypospray, which is the main reason I did all this, described in detail below.

Scroll down for screenshots.

**Second iteration - no more synthesizer, can draw from plumbing and attached chemistry bag**

The wall-mounted hypospray is meant to serve as an alternative to the sleeper, with different advantages and disadvantages. To use it, you set it up with the thing you want to inject, grab the handle using either the UI or ctrl+click, then inject people with the handle.

Main downsides:
- Cannot synthesize chemicals, must be supplied with a chemistry bag
- Cannot pierce through protective clothing
- Chemistry bag can be cut off and stolen with a sharp object [NYI]
- **The hypospray does not tell you what chemicals you're injecting** - you can only see the names of bottles in it, which could be useful for sabotage

Main upsides:
- Can inject chemicals 1u at a time
- Doesn't require people to go into a machine, allowing you to serve more people more quickly
- Has one more tile of range than the sleeper, because you can step away one tile from the mount and inject people standing one tile further away
- **Can inject people from an easily swappable bottle instead of other sources** - I'm hoping this will be used to distribute things like viruses and vaccines
- Can be locked with a medical ID to prevent unauthorised access - starts locked as well
- Doesn't take up floor space or block you from moving - instead uses a wall
- Has a whopping three sources of chemicals it can draw from:
  - Attached chemistry bag can hold a variety of bottled medicines and medicine mixes made by chemistry to easily swap to what's needed
  - Handle can have a single bottle attached to it, so you can quickly swap between things you might not need in the long run, like positive viruses and vaccines
  - Plumbing can be used to supply the synthesizer with an infinite supply of medicine - but only one mix can be supplied at a time

### TODOs:
- [x] Sprite for wall-mount - currently uses defib wall mount sprite as placeholder - sprite by Azlanon
  - Maybe unique sprite for handle
    - [ ] Almost certainly unique sprite for handle, could use visuals for bottle attached to handle
- [ ] Code cleanup
- [ ] More/better feedback (Balloon messages, missing failure messages)
- [ ] Balance, balance, *balance*

### Screenshots

<details>
<summary>Wall-mounted machine frame construction</summary>

Frame crafted from metal:
image

Placed on wall:
image

With cables:
image

With circuitboard:
image

</details>

<details>
<summary>Wall-mounted hypospray</summary>

It starts out locked by default:
image

Unlocked, chemistry bag attached (*codersprite*), handle taken off:
image

Injecting 1u of flu virus from bottle attached to handle, this time with plumbing hooked up:
image

The interface again:
image

Slightly improved interface:
image

</details>

## Changelog
:cl:
add: Wall-mounted machines and machine frames, constructed like normal machines, but on a wall!
add: Wall-mounted hypospray, a new machine for medbay to inject people with chemicals
refactor: Small refactor to machine construction to faciliate wall-mounted machine frame construction
/:cl:

### CODE REVIEW

**Comment by ItsTisme** [comment]
instead of it "making" chems perhaps have it store beakers of chems to inject?

**Comment by KubeRoot** [comment]
> instead of it "making" chems perhaps have it store beakers of chems to inject?

Sounds like the way tgstation sleepers work right now, and I'm not a fan of that. That said, right now the hypospray can hold one beaker to inject from instead of the synthesizer, and I had a suggestion on discord to make it so it can't synthesize anything without some upgrades as well.

If more people agree though, could be changed. tgstation's sleepers use a chemistry bag attached to them, which in turn contains bottles with the reagents that can be injected. I could replicate that behavior or something similar, maybe even linking with a smartfridge to allow you to transfer bottles remotely.

**Comment by ItsTisme** [comment]
> maybe even linking with a smartfridge to allow you to transfer bottles remotely.

Yes please chemistry is a glorified meth cookout right now. Making medicine not auto generate would make it alot better

Propblem with  if it synthesizes is that people dont even *need* to enter the medbay anymore. They simply self service bicardine outside on the wall and leave. Completely removing the point of medbay. This is the reason why sleepers arent self serving

**Comment by francinum** [comment]
I'm not sure how I feel about the hypospray machine. Also yes, No internal synth. Make it require chem to do their jobs.

**Comment by KubeRoot** [comment]
Alright, will remove the internal synthesizer.

Should I make it link with a smartfridge so it can instantly swap out bottles with anything in it? This would allow chemistry (and virology) to supply stuff to the smartfridge for normal use while also having them be available from the hypospray, but leaving the hypospray unlocked would also give people access to any bottles in the linked smartfridge.

Or should I instead give it its own storage? I could make it work like the sleepers, with it holding a chemistry bag, or simply give it an independent limited capacity inventory. I'm don't know how to code either yet, but it shouldn't be too hard.

**Comment by francinum** [comment]
...We need *less* shit with magic range links, in my opinion, Choose from a selection of bottles *and then put them in the machine yourself.*

**Comment by ItsTisme** [comment]
>Should I make it link with a smartfridge so it can instantly swap out bottles with anything in it?

This may be a fun idea for a more advanced bluespace verison of a smart fridge, or even allow that to connect to pluming system. Would encourge chemists to go advanced

Also I like the chemistry bag thingy, makes supplying simple. But giving them there own storage could also work. make sure you can fill from a chem bag though on click instead of manual insertion

**Comment by KubeRoot** [comment]
> or even allow that to connect to pluming system. Would encourge chemists to go advanced

Why the hell did I not think of that. *Of course* you make it work with plumbing, gonna have to code that. The only issue I see is making it connect nicely while being on the wall.

> Also I like the chemistry bag thingy, makes supplying simple. But giving them there own storage could also work. make sure you can fill from a chem bag though on click instead of manual insertion

I'm thinking chemistry bag might be the way to go - I'm thinking of making the bag get locked in place while the machine is locked, but able to be cut away with sharp objects for extra shenanigans with people stealing the bag.

**Comment by francinum** [comment]
~~I really want to discourage interaction with the plumbing system because I'd quite like to send it packing in the future~~
But yeah undeniably this is a good place for plumbing to be used.

**Comment by KubeRoot** [comment]
I'm also thinking the handle should still be usable when the device is locked, only letting you inject whatever was previously selected, as well as swap out bottles attached to the handle. This way it could be used as a faster and more precise syringe by anybody without access, or left on something like epinephrine for first aid.

**Pull request closed without merging**
