### PR TITLE
Removes Soporific Slugs

### LINKED ISSUE #6604: Soporific shells are insanely OP and security has figured it out
## Testmerges: 
The following pull requests are currently test merged:
[#6592: 'New original gamemode: carp ops' by Archanial at commit 34f9004d4f](https://www.github.com/beestation/beestation-hornet/pull/6592)

## Reproduction:
1. Print soporific shells.
2. Fire 2 slugs at anyone, through any armor (both stamina, and armor that blocks syringes usually), no matter their stimulants, immunities, anything.
3. They get put to sleep, and if they wake up before you beat them to death, they are forced to constantly move in random directions for a solid 5 minutes.

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

~~Apparently sopophoric slugs work against targets that cannot be peirced, which I don't think should have been the case.
Additionally makes sopophoric slugs effect depend on the targets armour: If a target has 50 armour the sleeping effect is only 50% effective.~~

Completely removes soporific slugs from the game.

## Why It's Good For The Game

Sopophoric can take out a nukie in 2 shots, despite their armour being penetration resistant. Despite requiring exploration disks, these shells are too strong for an easilly mass-producable shell.

The problem with them isn't necessarilly the fact that they are too powerful, its the fact that they are unfair by design which is why I favour removing them over simply nerfing them.

closes: #6606

## Testing Photographs and Procedure

image

## Changelog
:cl:
remove: Removes the soporific slugs
/:cl:

### CODE REVIEW

**Comment by Oscari-pog** [comment]
THANK **FUCKING** GOD

speedmerge

**Comment by Mat05usz** [comment]
Tbh that shit shouldn't be in game at all. Craftable ranged 'hard stun', one shot is enough to basically win most fights.

**Comment by Oscari-pog** [comment]
> Tbh that shit shouldn't be in game at all. Craftable ranged 'hard stun', one shot is enough to basically win most fights.

Yeah a full-on removal is the best solution here. Soporific slugs just shouldnt exist.

**Comment by PowerfulBacon** [comment]
I am all for removing these, they are unfair and impossible to make fair by design. The only way I can see to balance in a way that makes them fair basically just turns them into beanbag slugs anyway.

**Comment by Mat05usz** [comment]
@Archanial none of us died to it, we just observed a perfect sneak nukie run be ended by this shit and it should've been removed long time ago (along with other hardstuns/RNG shit).

**Comment by TeomanTheGreat** [comment]
CL needs changing since its a removal now

**Comment by FriendlyContractor** [comment]
If we are talking about nuke ops balance i would like to mention there are few things which are comparable or worse and far more easily obtainable than soporific slugs which require techdisk. All of them are guaranteed death - piercing syringe, chemical grenade, TTV, grenade lance.

**Comment by Mat05usz** [comment]
> If we are talking about nuke ops balance i would like to mention there are few things which are comparable or worse and far more easily obtainable than soporific slugs which require techdisk. All of them are guaranteed death - piercing syringe, chemical grenade, TTV, grenade lance.

Piercing syringe - is cringe, but really the only way you can do anything with chems against armoured targets so eeh.

Chemical grenade - come on

TTV - come on, timeless classic

Grenade lance - that's pretty cringe, I agree (one tapping any antag is very unfun and unfair)

**Comment by PowerfulBacon** [comment]
Unfair game mechanics = i ded

**Comment by Mat05usz** [comment]
> Unfair game mechanics = i ded

yeah lmao

was removal of tasers or RNG hardstun ided too?

git gud

**Comment by Oscari-pog** [comment]
Adding a "i ded" label to a PR made by someone who didn't die to it. Soporific user spotted.

**Review by Archanial — APPROVED** [review]
ided

**Comment by OverwatchVoice** [comment]
Yes, THANK YOU

**Comment by Sapfearon** [comment]
is it too late to say that it's a very, very late game tech? That not even researchable by default without exploration disks which are rng? And by the way - slugs do not ignore piercing, i tested it on couple enemies ( ninja, abductor, nukie) - they completly ignore it meaning it works as intended.

so after this exotic ammo will be ammo for detective which he not allowed to use by rules and useless smg ammo for which sec never has guns?

**Comment by Oscari-pog** [comment]
You are either lying or never saw a soporific slug.
I have both been sent to sleep by it, as a nukie, and sent a ninja to sleep with it.

**Comment by PowerfulBacon** [comment]
> is it too late to say that it's a very, very late game tech? That not even researchable by default without exploration disks which are rng? And by the way - slugs do not ignore piercing, i tested it on couple enemies ( ninja, abductor, nukie) - they completly ignore it meaning it works as intended.
> 
> so after this exotic ammo will be ammo for detective which he not allowed to use by rules and useless smg ammo for which sec never has guns?

Exotic ammo includes a lot of upgraded shotgun shells including:
 - Explosive shells
 - Pulse rifle shells
 - Laser scatter shells
 - Meteor shells

All the others take some work to craft, soporific is just free at the lathe. Time and RNG is also not a good balancing factor.

**Comment by DerpiestBruh** [comment]
git gud

**Pull request merged**
