### PR TITLE
Several medkit visual tweaks

### LINKED ISSUE #5544: Medical aid kits have no righthand inhand sprite

### PR DESCRIPTION
**Pull request by Pirill**
## About The Pull Request
**Resolves #5544** 

A small number of visual tweaks to medkits, notably:
- Adds missing right inhands for the "surgical" medkit;
- Changes the alternative toxin medkit biohazard icon to be a bit crisper;
- Fixes a small inconsistency between left and right inhands on the oxygen kits;
- Gives radiation kits their own icon instead of reusing the advanced first aid kit sprite;
- Gives tactical/combat first aid kits two new icons instead of the tinted default one;
- Adds inhands for the radiation and combat medkits;
- Removes several unused or duplicate medkit icons;

image

## Why It's Good For The Game
Better distinction between items good

## Changelog
:cl:
imageadd: New sprites and inhands for radiation and combat medkits, tweaked sprites for the biohazard toxin medkit
/:cl:

### CODE REVIEW

**Comment by r1ks-iwnl** [comment]
The geneva convention breaking red cross 😳

**Review by Archanial — APPROVED** [review]
I love this, we need more inhands, there's plenty of them missing.

**Comment by Naevii** [comment]
Very good looking sprites. 

> 
> 
> I love this, we need more inhands, there's plenty of them missing.

Its hard to make good inhands. and they are absolutely a pain to do. (mainly because of how small they are)

**Comment by Archanial** [comment]
>Its hard to make good inhands. and they are absolutely a pain to do. (mainly because of how small they are)

doesn't change the fact they're the most missing sprite

**Comment by Pirill** [comment]
> I love this, we need more inhands, there's plenty of them missing.

I might fill out some more in future PRs. I wonder if we can get a list of more notable missing content going anywhere...

**Comment by TerryTehCoder** [comment]
Always used to love opening what appears to be an advanced first aid kit, and to my surprise, all you get is a bottle of Vodka and some mutadone pills. 
Good Fixes.

**Comment by BrumalLake** [comment]
write a unit test

> 
> 
> > I love this, we need more inhands, there's plenty of them missing.
> 
> I might fill out some more in future PRs. I wonder if we can get a list of more notable missing content going anywhere...

**Pull request merged**
