### PR TITLE
Ports prisoner role from /tg/

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

Ports the prisoner role from tg

## Why It's Good For The Game

More gimmicks

## Changelog
:cl:
add: Added Prisoner role
imageadd: added plasmaman prisoner envirosuits
/:cl:

### CODE REVIEW

**Comment by Flakkyboo** [comment]
ABSOLUTE MADLAD I OVE IT

**Comment by ike709** [comment]
...I feel like this should just be included in the Gimmick role system, instead of it's own job.

**Comment by ModDownloading** [comment]
Aw yeah, been waiting for this.

If other people are ok with it, it would be nice to have the updated perma wing too since I can say from experience that the expanded permabrig makes Prisoner way more fun to play. Probably better to leave that to a different PR though (since that is a TON of content and not just a map change) if it ends up happening.

**Comment by zeskorion** [comment]
I agree with ike here. Unlike /tg/, bee is full of idiots who will abuse prisoner for muhvalid

**Review by zeskorion — CHANGES_REQUESTED** [review]
As Ike said, this should be a Gimmick job if anything. Beestation players will abuse Prisoner for validing, both as sec and as prisoner

**Pull request closed without merging**
