### PR TITLE
Disables every gamemode besides dynamic

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

I think we're ready to go full dynamic, or at least try it. I know you probably would change is by setting the master_mode to dynamic so I don't expect it merged and it's up to @Crossedfall or our maintainers to make config changes.

## Why It's Good For The Game

People like dynamic, different antagonists are fun and it makes rounds more unique.

## Changelog
:cl:
tweak: We're running dynamic only :sunglasses: 
/:cl:

### CODE REVIEW

**Comment by Penwin0** [comment]
Do we have clockies in dynamic

**Comment by super12pl** [comment]
wizard every other round lets go

**Comment by ToasterBan** [comment]
I like dynamic but don't want 100% dynamic, making it higher would be fine but this will outright remove extended which I like

**Comment by Penwin0** [comment]
> I like dynamic but don't want 100% dynamic, making it higher would be fine but this will outright remove extended which I like

No threat rounds can still happen

**Comment by Archanial** [comment]
> 
> 
> I like dynamic but don't want 100% dynamic, making it higher would be fine but this will outright remove extended which I like

Dynamic has extended rule, it's just set to some high threat so it cannot be rolled.

**Comment by ItsTisme** [comment]
are we up to date on dynamic ports? I havent seen that many swing by. also make sure it works with all antags like clockies or we soft lock them away essentialy

**Comment by williamcll** [comment]
you can't have clockies in dynamic since it doesn't load Reebe.
Of course, you could add an alternative summon methods but that's a lot of coding people can't focus on.

**Comment by ItsTisme** [comment]
> 
> 
> you can't have clockies in dynamic since it doesn't load Reebe.

Dont think we can merge it until thats fixed. Since it would essentialy remove a entire gamemode(beloved by most)

**Comment by Archanial** [comment]
https://github.com/BeeStation/BeeStation-Hornet/blob/cc2016313e6ffcb48574d379424cad4f02b005e8/code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm#L640

:eyes:

**Comment by francinum** [comment]
That implies you can't load reebe midgame.

You absolutely can. It's just totally not balanced around it.

**Comment by PowerfulBacon** [comment]
🔑

**Comment by qwertyquerty** [comment]
🔑

**Comment by ike709** [comment]
🔑

**Comment by Archanial** [comment]
:sunglasses:

**Pull request closed without merging**
