### PR TITLE
Light switch madness, with a side of area tweaks

### PR DESCRIPTION
**Pull request by CydiaLamiales**
## About The Pull Request
Adds a light switch or two to almost all rooms (excluding maintenance).
Adds the Freezer, Medbay Lobby and Surgery areas to Box.
A companion PR to https://github.com/BeeStation/BeeStation-Hornet/pull/9246

## Why It's Good For The Game
Allows for more interactions with lights all around the station.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Before this PR
image

After this PR
image

Box, freezer area and new APC in the kitchen
image

Box, medbay lobby area and new APC
image

Box, surgery area and new APC
image

</details>

## Changelog
:cl:
add: Added a "tcomms server" light switch for mapping
add: Added a light switch to almost every room excluding maintenance
add: Added Freezer, Medbay Lobby and Surgery areas to Box alongside the required APCs
fix: fixed a couple of misplaced areas in Box and Kilo
/:cl:

### CODE REVIEW

**Comment by BriggsIDP** [comment]
hey, there seems to be some light switches missing in box, rad and corg look good!
- perma
- dorms rooms
- freezer
- morgue
- surgery 
- turbine
- emitters (maybe ?)

**Comment by CydiaLamiales** [comment]
> hey, there seems to be some light switches missing in box. Rad and corg look good!
> 
> * perma

It's there
image

> * dorms rooms

The entirety of dorms is a single area, meaning a switch in each room would control the entirety of dorms.
Which exists
image

> * freezer

Freezer on Box isn't a separate area from the kitchen, but I'll add it anyway
> * morgue

Added
> * surgery

Once again, not a separate area from medbay central.
> * turbine

It's there, just hidden by the poster, which is placed on the maint side of the wall.
image

> * emitters (maybe ?)

Not a separate area from Engineering.

**Comment by Eric-01** [comment]
If it has already been informally agreed on that said rooms are separate on all the other maps in rotation, then for the sake of consistency, they should be separated on BoxStation as well. That's my two cents.

**Comment by Eric-01** [comment]
You're right. I started writing that comment before you pushed these changes.

**Comment by CydiaLamiales** [comment]
Changes for rad are missing right now due to merge conflict fuckery

**Review by PestoVerde322 — APPROVED** [review]
All seems good to go, approved and soon-be-merged

**Pull request merged**
