### PR TITLE
Sleeping Carp: Scaled Skin Edition

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
Heavily reworks the martial art to account for the loss of it's paralysing aggro grab. This includes:

**Heavy Resistance To Most Damage and Disables:** 
Basically, the Sleeping Carp user is a tough fucking bastard of a martial artist. They are very resistant to brute, burn, stamina, stun, pressure and cold damage. They are able to spacewalk temporarily as a result, given they take very little damage from brute/burn/pressure/cold. They do have one notable weakness though: increased damage to heat. Cook up some carp filet (if you can). 

**Three Short Brutal Combos:**
All the moves are started with Harm intent. They are:
- Gnashing Teeth (Harm-Harm) - One-Two punch with a potential for a critical hit. Basic damage move.
- Crashing Wave Kick (Harm-Disarm) - A kick that launches people off the screen. Good for keeping anyone off you and really fucking them up in space. 
- Keelhaul (Harm-Grab) - Dropkick that knocks down and disarms. While the person is on the floor, disarms and applies stamina damage. Pretty much your main opener.

**Conditionally Immune To Projectiles:** 
This is now toggleable so you have ranged immunity while you have Throw Mode up and only then. This means people can't validcheck you by shooting foam darts or a random projectile at you, but it also means you can't deflect as well as attack simultaneously. Best for approaching and escaping.

**Higher Vulnerability To Things They Weren't Vulnerable To Before:** 
You can shoot them with guns and it will now work, mostly. Which means Joe Shmoe, Security Officer fresh off the boat, isn't reliant on specialized equipment to fight a sleeping carp user. He's probably still in deep shit if he's fighting them on his own, however. Temp Guns set to bake will work well here too.

**Immunity to Relevant Stuff, Stronger with Armor:** 
If your skin is as thick as scales, then things that could puncture that no longer work. They are immune to syringes, sutures, ninja stars, embedding spears, etc. In addition, armor becomes way more important for Sleeping Carp users to encourage them to really focus in on the defense aspect of their martial art and tank damage.

**Carp Faction:** Carp petting.

## Why It's Good For The Game
Sleeping Carp was a martial art only kept alive by it's aggro grab stun. Now instead:
- All the combos are useful and you can tailor your approach/defence
- Being friendly with carps can make for good memes
- Space walking lite is handy as hell
- Damage resistance is great to have and pairs well with actual armor
- More skill-based, so you can still be seemingly invincible if you're robust
- Security doesn't need specialised equipment to fight as long as they have good group engagement tactics
- Toggleable ranged deflection means people can't validcheck you by shooting you with foam darts or whatever

## Changelog
:cl:
tweak: Completely reworked Sleeping Carp
balance: Sleeping Carp users are really goddamn durable, but are weak to heat damage. 
tweak: Stun batons now uses apply_damage, which gives Sleeping Carp users some resistance to them. 
balance: Sleeping Carp users have less moves but they're all short combos and ultraviolent.
balance: Carp faction. The added durability with this means you can space walk for a while and say hi to the carp.  
balance: Sleeping Carp users can toggle their projectile reflection on/off. They need to be in throw mode to deflect ranged attacks.
balance: Sleeping Carp users are pierce-immune e.g. can't be embedded by spears. 
/:cl:

Ports:
https://github.com/tgstation/tgstation/pull/49524

### CODE REVIEW

**Comment by Lagomorphica** [comment]
### **_Why I, personally, feel this is a bad idea - from a guy with 700 hours of primarily using martial arts as nukie and traitor, along with using them on Central Command whenever I die to practice._**
---
While I can see your attempt at making this a seemingly more skill based martial art, along with the removal of its entire gimmick of deflecting ranged attacks and instead making it more like Plasma Fist in terms of its combo length and complexity, I do not see how this is making it more skill based. 

In exchange, what is effectively a military synth-lite playstyle has been created; rather than simply punching people before they kill you over, you instead become a guy with more punch damage and 25% damage resist or so. In exchange, you are completely gutting Wrist Wrench, Back Kick, Stomach Knee, Head Kick and Elbow Drop for 3 2-hit combos.

Now, while the most common use of sleeping carp is to wrist wrench somebody and then go in, removing the aggro grab is a major loss of engage and disengage potential; if you see two people with carp normally, the adequate response would be to grab one, throw them into the other, get off some good damage, back kick/head kick them, then execute with an elbow drop. Alternatively, you can attempt to run in with wrist wrench, get exposed as a traitor to the entire crew, and have everyone hunt you down.

In regards to Security needing specialised equipment, it is generally quite simple to subdue all but the most beefy of carp users; bola's in the secvendor, flashbangs on those who forget eye and ear protection, spears, ion guns on IPCs or those with implants, flamethrowers, thrown stun batons, pepper spray, etcetera.

The loss of aggro grab also contradicts a previous PR in regards to tabling you made; if one is to effectively use it, why remove it? There's not going to be any point in doing so or using any form of environmental play when you can simply Keelhaul them then spam Gnashing Teeth on them. This also buffs the interaction of Gloves of the North Star with Carp in a similar way to CQC with its Head Kick; a harm-harm combo is an extremely strong thing to give to a traitor that can feasibly get a GotNS discount roll or similar, especially with contracts being added.

Now, onto one of the most important things - the removal of ranged resistance. This would be fine, assuming one still had aggro grabs - you could move people into the firing line and render it impossible for a sec officer to get a good shot. However, the moment that person hits their "Rest" button and there is a second person there, you're going to get shot before you can turn Throw mode on, since it turns off when you attack from what I recall.

To conclude, while I understand the goal and effort behind this PR, the way behind it is not making it more 'complex' in any way, short of limiting the range and usability of the moves to 3 far more basic moves, and completely gutting one of the biggest draws of carp because regular guns don't work. If you get accidentally shot while walking with Carp, it should call you out, since thats one of the risk vs rewards of it - you get a very strong, flexible martial art at expense of the fact you have very few ranged options, cannot easily* fight more than two people due to the length of your combos, while rendering Carp users unable to throw anything during fights due to the fact their whole gimmick is tied to having throw mode on now.

_**TL;DR**_ - destroys the entire soul of the martial art in my opinion and makes it an incredibly simplistic form of design that accomplishes next to nothing and has one effectively useless move since why would you kick somebody away from you when you can just kill them, while also making fighting even more than one person exponentially harder due to constantly having to toggle throw mode on and hoping the person doesn't stun baton you once in the time it takes for you to execute a combo, before having their buddy shoot you after you rest.

Even you yourself said this on the original PR on /tg/ - 

> There's reworks and then there's creating a completely different thing. Add this as a new separate item and later on if desired do a separate PR to remove the old martial art. Trying to use the name Sleeping Carp for this feels like trying to ride off the brand name to get a new martial art merged.

> It's a bit cringe that an item that's supposed to make you godly in melee combat can still end up with you getting dabbed on by a baton user. Before you could hit them once with an aggro grab to stunlock punch to death, now you've got to risk doing two hits to finish a combo, and even more on top of that to kill them.

To finalise, I'd also like to say that from a more personal opinion than what I have said previously - making it reflect instead of deflect in random directions removes that enjoyment of getting that lucky deflect that wipes somebody off the fucking map with a near point-blank buckshot blast in comparison to it being guaranteed against idiots.

### **_CQC_**

While Sleeping Carp was certainly a shit-show in terms of how it was neutered, CQC is getting even more fucked up. These changes will kill almost 3 of CQC's 5 moves, leaving only two really viable ones - CQC kick and Consecutive CQC. One could argue that Pressure is also still slightly useful, but you no longer have grip of the person and it only deals Stamina damage - why bother when you can just use an infinitely larger array of weapons that will kill the person, and deflect both melee and energy attacks?

You can no longer use Chokehold since they'll just move away from you, you can no longer Slam since they'll just move away from you, and you can no longer effectively use Pressure since although it slows them it doesn't open them up to any new moves unless you continue moving towards them, and also lets them continue attacking you for real damage.

As for the Cooks on station, this also heavily removes any aspect of non-lethal removal - you have to angle yourself towards the door and get a good CQC kick off, or just crit them and drag them out, since you can no longer just grab them and throw them out of the kitchen. Why do that when instead you can just hit them with a knife 4 times in comparison to trying to kick them out a tiny ass door, or against a wall twice, only to get a 30 second sleep to throw them out?

**_TL;DR_** - most of CQC is now useless and outclassed by all other traitor gear over the removal of aggressive grabs. Cooks are no longer incentivised to harmlessly throw people out since there is minimal point when you have to CQC kick them against a wall twice or just knife them 4 - 5 times for a reliable crit.

_**### TL;DR for all of it**_ 
---
Completely destroys the entire soul of one martial art while making it a far more dumbed down version instead of the more skilled version, while also making another martial art entirely useless.

While it is certainly frustrating to die to a carp user, you can fight against it with preparation and intelligence - much like many things in this game, the answer should not just be "click at man with energy gun" with extra steps, like having your friend attack him in close range as you fire.

Flame me if you wish but this is how I feel about it.

---
Also, as a quick side note - here is what it does in full.

* You will not be able to use any ranged weapon, as that would be dishonorable.
* If throw mode is active you deflect all ranged attacks, whether energy or physical (but not thrown items).
* You only take 40% brute, 70% burn, 50% stamina, 30% pressure and cold damage. And 30% stun durations. You still take full damage from cellular/suffocation sources.
* You take double damage from fire/heat.
* Immunity to syringes, sutures and ninja stars. (Unconfirmed if piercing syringes work or not).
* Your ordinary punches deal 10-15 brute.
* Space carp won't attack you.**

**_Crashing Wave Kick_** - _Launch people brutally across rooms, and away from you. Deals 15 brute._

**_Keelhaul_** - _Kick opponents to the floor, dealing 10 brute and 4 seconds of knockdown if they are standing. Against prone targets, deal 40 stamina damage and disarm them._

**_Gnashing Teeth_** - _Deal additional damage every second punch, with a chance for even more damage. 20 damage + 10% chance for an additional 20 damage._

**Comment by VictorVow** [comment]
> removal of its entire gimmick of deflecting ranged attacks and instead making it more like Plasma Fist in terms of its combo length and complexity, I do not see how this is making it more skill based.

The ranged deflection isn't removed, it's simply made a toggle. From a SC's user perspective:
- Pro: I can hide that I have martial arts now
- Pro: I'm still invincible from ranged attacks when I'm approaching or escaping
- Con: I'm not invincible from ranged attacks if I'm in the middle of combos, so I need to use careful positioning, timing and striking (AKA skill) to ensure I'm still able to deal with multiple ranged attackers

Overall I'd say it's more skill-based in ranged deflection alone. 

It also doesn't have long combo length because:
1) These aren't viable without stuns, and this rework is another step away from the stun meta to a more fluid combat system which allows counterplay.
2) SC standard punches are much stronger by default it doesn't fit for it to be a martial art with long combos since they'd be near crit from strikes alone anyway.

_But_ I'd be interested in having long combos from old SC and PF (or something similar) in a **new** low-TC-cost martial art, though I'd need to think more on the design of that. 

> Now, while the most common use of sleeping carp is to wrist wrench somebody and then go in, removing the aggro grab is a major loss of engage and disengage potential

99% of people always engage with the aggro grab, as it's a one-hit stun rather than two-hit. I've only seen one or two guys ever use wrist wrench and even then they generally opted to engage with the grab instead. SC is basically a one-hit kill martial art because of that, which isn't interesting gameplay. 

Your perspective includes a much more varied use of combos and I applaud that, but they're overshadowed by aspects of SC which are more powerful which leads to most combos being ignored entirely, which is a shame. Again, I'd like to see a martial art with longer combos be a thing but I don't think it works with the rest of SC's kit. 

> In regards to Security needing specialised equipment, it is generally quite simple to subdue all but the most beefy of carp users; bola's in the secvendor, flashbangs on those who forget eye and ear protection, spears, ion guns on IPCs or those with implants, flamethrowers, thrown stun batons, pepper spray, etcetera.

It's already presumed that the carp user is wearing eye/ear/mouth protection and not an IPC because that's the case 99% of the time, bolas are epic indeed and should be used more, and crafted weapons are an example of specialised equipment that Security needs to go and make. 

> The loss of aggro grab also contradicts a previous PR in regards to tabling you made; if one is to effectively use it, why remove it? There's not going to be any point in doing so or using any form of environmental play when you can simply Keelhaul them then spam Gnashing Teeth on them. This also buffs the interaction of Gloves of the North Star with Carp in a similar way to CQC with its Head Kick; a harm-harm combo is an extremely strong thing to give to a traitor that can feasibly get a GotNS discount roll or similar, especially with contracts being added.

Yeah the tabling stuff doesn't apply to SC to anymore but it does to CQC. I was also thinking of making an Aikido martial art with aggro grabs and the martial counter/melee block of CQC with some other bits. Maybe the longer combos can fit there. 

Anyway back to SC: evironmental play-wise you can Crashing Wave Kick people into others or into walls. I might buff the wall hit effect though either in damage or knockdown length. 

Agreed about that pair being powerful. I'm thinking of making GotNS a martial art, though I'm looking for other ideas of how to balance them together.

> Now, onto one of the most important things - the removal of ranged resistance. This would be fine, assuming one still had aggro grabs - you could move people into the firing line and render it impossible for a sec officer to get a good shot. However, the moment that person hits their "Rest" button and there is a second person there, you're going to get shot before you can turn Throw mode on, since it turns off when you attack from what I recall.

Yes it turns off when you attack, but the added damage resistance should help ensure that when you're in short period in the middle of your two-hit combos that you take little damage, and this can be mitigated through positioning well also. I'm all ears for a better solution but I think this generally rewards skill better than having ranged deflection always-on. 

> To conclude, while I understand the goal and effort behind this PR, the way behind it is not making it more 'complex' in any way, short of limiting the range and usability of the moves to 3 far more basic moves, and completely gutting one of the biggest draws of carp because regular guns don't work. If you get accidentally shot while walking with Carp, it should call you out, since thats one of the risk vs rewards of it - you get a very strong, flexible martial art at expense of the fact you have very few ranged options, cannot easily* fight more than two people due to the length of your combos, while rendering Carp users unable to throw anything during fights due to the fact their whole gimmick is tied to having throw mode on now.

There is another martial art I was thinking of adding which _does_ have an always-on ranged component, but it's_block_ and not deflection. For me the biggest draws of SC are kept - I can assassinate anyone without issue, and if security gang up with guns I'm still invincible. I'm happy to hear about actionable suggestions to improve the gameplay of this, but as a whole I think this is much better balanced than old SC and makes it more fun to play as or against. 

> Quotes

As you can tell I've since changed my opinion on that. SC is mainly about fast brutal takedowns and the ranged immunity rather than aggro grabs, and I think the toggleable ranged immunity + damage resistance is a fair trade for always-on ranged immunity. Also regarding stunbatons I'm in agreement with Zesk that they're just plain overpowered at the moment. If Zesk's previous PR went through despite it taking 3 hits to take down crew, it would take at least 6 to take down a SC user.

> CQC

These changes don't affect CQC at all, they still retain paralysing aggro grabs.

**Comment by qwertyquerty** [comment]
Fix conflicts

**Comment by VictorVow** [comment]
@qwertyquerty fixed

**Comment by VictorVow** [comment]
@qwertyquerty is ready

**Comment by ike709** [comment]
I'm closing this because it's stupidly overpowered and because I disagree with a lot of recent changes to combat overall.

**Pull request closed without merging**
