### PR TITLE
Ports aquariums from tg

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Ports aquariums from tg, together with fish and other stuff related
Ported PRs:
https://github.com/tgstation/tgstation/pull/56343
https://github.com/tgstation/tgstation/pull/56573

It's functional besides fish encyclopedia, which requires TGUI 4.3.
Draft because I'll wait for TGUI 4.3 to be merged.

## Why It's Good For The Game

Very good content, we need fishe

## Changelog 
:cl:AnturK, sprites by tralezab
add: Aquariums, fishes and aquarium accessories.
add: Aquarium starter cargo crate. Random fish cargo crate.
/:cl:

### CODE REVIEW

**Comment by Effemu** [comment]
funny fish time

**Comment by DatBoiTim** [comment]
11/10 PR idea

**Comment by yyzsong** [comment]
Fish reproduction pr
fetish content

**Comment by OceanFish1** [comment]
Le fishe
I approve

**Comment by mat-lap** [comment]
feesh

**Comment by mathis650** [comment]
https://cdn.discordapp.com/attachments/150315577943130112/852911378900582450/unknown-39.png

**Comment by ike709** [comment]
Stale

**Pull request closed without merging**
