### PR TITLE
[Port] Ports the long-ranged atmos analyzer

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

Ports Skyrat-SS13/Skyrat13#2523
With modified sprites
image

## Why It's Good For The Game

Station engineers lacks a way to scan atmos from far away

## Changelog
:cl: NotRanged
add: Added a long range atmos scanner
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
sex station port 😳

**Comment by SomeAngryMiner** [comment]
from the sprite side, this is fine.

**Comment by Blueturbo47** [comment]
A ranged analyzer is good for when you want to view a burning area or trit farm or something and there is no way to get in there without getting super irradiated or burned, +1.

**Comment by OceanFish1** [comment]
Don't we have an analyzer from hilbert hotel that does the same thing? Why do we need to port stuff?

**Comment by jupyterkat** [comment]
Hilbert's hotel scanner isn't actually a ranged scanner, it's extra functions are to tell what rooms are taken. Not telling the atmos from far away

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
