### PR TITLE
Hub Autolink for Exploration Relay

### PR DESCRIPTION
**Pull request by DatBoiTim**
## About The Pull Request
Now it should be properly (auto)linked to allow cross z-level comms.

## Why It's Good For The Game
Was broken. Is fix.

## Changelog
:cl: DatBoiTim
fix: Exploration Relay on Shuttle Not Linked
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
This doesnt fix a thing, exploration comms are seprate

**Comment by DatBoiTim** [comment]
> This doesnt fix a thing, exploration comms are seprate

So why does mining get all the channels then? Makes it more consistent in linkage.

**Comment by PowerfulBacon** [comment]
#5285

**Comment by DatBoiTim** [comment]
@ike709 So we're just superceding PRs now?

**Pull request closed without merging**
