### PR TITLE
Buffs shotgun slugs

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Buffs shotgun slugs.

## Why It's Good For The Game

-60 was way too much, they do essentially 0 damage to armoured targets.

## Changelog
:cl:
balance: Buffed shotgun slugs to -20 armour penetration instead of -60
/:cl:

### CODE REVIEW

**Review by utilbird — APPROVED** [review]
old statistics (shots to kill):

Unarmoured: 2 shots
Sec gear(vest and uniform): 12 shots
Engie Hardsuit: 5 shots
Ninja: cannot be harmed
Cultist armour(unshielded): 18 shots
Miner suit: 9 shots
Riot armour(chappie is the same): 6 shots

**Comment by ghost** [comment]
Shotguns are as of now one of the most powerful commonly available weapons that the stations crew can obtain, I do not think that they require to be made stronger.

**Comment by ghost** [comment]
> Shotguns are as of now one of the most powerful commonly available weapons that the stations crew can obtain, I do not think that they require to be made stronger.

they made slugs essentially useless against armoured opponents

**Comment by utilbird** [comment]
@BeloneX #3152

**Comment by ghost** [comment]
> @BeloneX #3152

Ah, very good.

**Comment by Crossedfall** [comment]
X-post from #development:

https://youtu.be/ute-FFA4XZQ?t=275

In order to get through consumer grade body armor it'd take over 50 slugs from a 12-guage shotgun. Slugs, in reality, are pretty useless against armored targets. My recommendation was to add stamina damage instead of overly buffing the actual damage.

**Comment by utilbird** [comment]
> In order to get through consumer grade body armor it'd take over 50 slugs from a 12-guage shotgun. Slugs, in reality, are pretty useless against armored targets. My recommendation was to add stamina damage instead of overly buffing the actual damage

To get through it yeah, but the amount of physical trauma the wearer would have experienced from 50 slugs would have killed them. One slug would be enough to completely wind you and leave you incapacitated, also doing a significant amount of internal damage to the surrounding area.

Stamina isn't a bad suggestion but brute damage is very realistic

**Comment by PowerfulBacon** [comment]
With a value of -60 weak armour is barely penetrable and strong armour is essentially immortal. Trying to make it more so weak armour does less and strong armour is barely penetrable

**Comment by githubuser4141** [comment]
> X-post from #development:
> 
> https://youtu.be/ute-FFA4XZQ?t=275
> 
> In order to get through consumer grade body armor it'd take over 50 slugs from a 12-guage shotgun. Slugs, in reality, are pretty useless against armored targets. My recommendation was to add stamina damage instead of overly buffing the actual damage.

Yeah, but that's not a security VEST, that's a solid block of steel for a plate carrier. Very different from the security armor vests which in-game are stated to be 'Type I-A' armor vests, probably roughly comparable to a [NIJ Type 1](https://en.wikipedia.org/wiki/List_of_body_armor_performance_standards#NIJ_armor_standard_(United_States)) vest, so realistically it'd be next to useless against slugs.

Also this (not this PR, but #3152) kind of skews up mecha balance IMHO, at least when thought about 'realistically'. Considering that mechas are just blocks of armor but motorized it wouldn't be logical for a armoured vehicle to get destroyed in about six slugs while a man with a kevlar patch on his chest tanks a whole 12 slugs before falling over.

**Review by utilbird — APPROVED** [review]

**Pull request merged**
