### PR TITLE
Makes the boxstation cryotubes space-cooled

### PR DESCRIPTION
**Pull request by yyzsong**
## About The Pull Request
A pal of mine did this and wanted me to PR it. Don't blame me.

## Why It's Good For The Game
It probably isn't

## Changelog
:cl: Ashton5336
tweak: makes boxstation cryo space-cooled
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
....Why?

Also, wallpipe bad.

**Comment by bloons3** [comment]
What mapping tool did you use to do this?

**Comment by TerryTehCoder** [comment]
I recall someone doing something like this a long time ago, not in a actual mapping update, but constructing a spaceloop and connecting it to cryo. I think they realized by the time they had gone through all the effort to set it up, the station already had tier 3 lasers for the cryocell freezer.

**Comment by francinum** [comment]
No other map does this, relies on wallpiping, isn't likely to get it's conflicts fixed, completely unexplained reasoning.

Nah.

**Pull request closed without merging**
