### PR TITLE
Adds (random) maint drones!

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request
simply adds a maint drone random maint room

## Why It's Good For The Game
maint drones are my favourite ghost role, so adds them as a rare room

## Changelog
:cl:
add: Random maint room that has a maint drone spawner!
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
Years of SS13 have taught me that drones are used as nothing more than greytide respawns.

**Comment by ToasterBan** [comment]
> Years of SS13 have taught me that drones are used as nothing more than greytide respawns.

I have (some) faith in our players to not abuse this

**Comment by williamcll** [comment]
Rarely has anyone one bee abused drones.

**Comment by super12pl** [comment]
> Rarely has anyone one bee abused drones.

that's because they are rarely spawned sherlock

**Review by Sinestia — CHANGES_REQUESTED** [review]
This does nothing to fix any of the problems drones have

look at /tg/'s changes, or paradise drones even, imo.

**Comment by francinum** [comment]
Drones need changes before I'm approving this, and I'd rather them be consistently available or unavailable.
🔑

**Comment by Crossedfall** [comment]
Yeah, this is a bad idea. 🔑

**Pull request closed without merging**
