### PR TITLE
Ports glass floors & catwalk tiles

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports Glass Tiles:
- https://github.com/tgstation/tgstation/pull/50831
- https://github.com/tgstation/tgstation/pull/54250
- https://github.com/tgstation/tgstation/pull/62890
- https://github.com/tgstation/tgstation/pull/66301
- https://github.com/tgstation/tgstation/pull/67449

Ports Catwalks Tiles:
- https://github.com/tgstation/tgstation/pull/59773
- https://github.com/tgstation/tgstation/pull/61916
- https://github.com/tgstation/tgstation/pull/61938
- https://github.com/tgstation/tgstation/pull/62236
- https://github.com/tgstation/tgstation/pull/62875
- https://github.com/tgstation/tgstation/pull/63016
- https://github.com/tgstation/tgstation/pull/64355

## About The Pull Request
Ports glass floors, catwalk tile, and transparency element

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: rkz, HowToLu/Dakae, PigeonVerde/PestoVerde, Floria/BriggsIDP, Spockye, made using code from TGcoders(wallem, vincentiusvin, paxilmaniac, tralezab, colovorat, coconutwarrior97, timothymtorres, OrionTheFox, coldud13)
add: Adds glass tiles, a new, craftable tiletype that you can see through!
add: Adds catwalk tiles. They come in multiple different colors and look much like regular lattice catwalks, but you can move their grille for ease of access instead of having to crowbar the whole tile!
code: adds zmimic hooks for tiles and material turfs
balance: Medium buff to floor bot logic making them more discerning when repairing or placing tiles. They will now also actually repair tiles instead of always replacing them, if possible.
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
ok, im gonna need to grab another pr to make this work lol

**Comment by Tsar-Salat** [comment]
Needs:
- https://github.com/BeeStation/BeeStation-Hornet/pull/8865

**Comment by Tsar-Salat** [comment]
im taking a break, Semester begins soon and this is affecting my mental health

**Comment by Tsar-Salat** [comment]
we fuckin back baybeee

**Comment by Tsar-Salat** [comment]
Alright my progression will be Basemats --> Tile Reskinning --> Glass Tiles.

Cant progress one until the other is finished.

In this current build, the appearance is overall fine, however there is layering in the requisite prs that are important to resolve first

**Comment by Tsar-Salat** [comment]
Plasteel to Iron ---> Tile Reskinning 2 ---> Glass Tiles

**Comment by Rukofamicom** [comment]
Has been a month since last update + is still draft + is failing checks across the board. 

Ping for stale removal when this is actively being developed again.

**Comment by Tsar-Salat** [comment]
Not WIP anymore. Just needs sprites from pigeon

**Review by Rukofamicom — APPROVED** [review]
This looks good as far as I can tell, and after going over detailed testing via DM with pigeon I trust that it won't break anything as well.

**Comment by Rukofamicom** [comment]
Frozen tag was missed when it was being updated for most of the other PRs due to this one being closed at the time.

**Pull request merged**
