### PR TITLE
Revert "Gangs Rework - Less Greytide Stationwide, More Territory Control"

### PR DESCRIPTION
**Pull request by PowerfulBacon**
Reverts BeeStation/BeeStation-Hornet#3951

Nothing seems to work here

:cl:
del: Reverts gang rework
/:cl:

### CODE REVIEW

**Comment by Sinestia** [comment]
Primary issue reported was that on deconversion, you would still look like you were in a gang on your own interface.

 Didn't see if the end condition worked either. 


Also a BoH bomb absolutely destroyed the server but that probably wasn't gangs' fault tm.

**Comment by bloons3** [comment]
Broken code + never testmerged in the first place

**Comment by eeSPee** [comment]
Should've been testmerged.

Working on some fixes.

**Comment by eeSPee** [comment]
> Primary issue reported was that on deconversion, you would still look like you were in a gang on your own interface.

I was unable to reproduce this.

**Comment by eeSPee** [comment]
#4416 should adress this.

**Pull request closed without merging**
