### PR TITLE
Adds another extra charslot to the ooc shop

### PR DESCRIPTION
**Pull request by yorii**
## About The Pull Request

Simply another extra charslot, twice as expensive as the first one.

## Why It's Good For The Game

For roleplaying purposes obviously.

## Changelog
:cl:
add: Another character slot can now be purchased for 20k beecoins
/:cl:

### CODE REVIEW

**Review by utilbird — COMMENTED** [review]
The preferable way to do this would be to allow players to purchase it multiple times. The same goes for all current OOC gear now that I think about it, maybe there could be some sort of `allow_multiple_purchases` gear variable.

**Comment by yorii** [comment]
> The preferable way to do this would be to allow players to purchase it multiple times. The same goes for all current OOC gear now that I think about it, maybe there could be some sort of `allow_multiple_purchases` gear variable.

Oh shit oh fuck a maintainer noticed my laziness...

**Comment by yorii** [comment]
> The preferable way to do this would be to allow players to purchase it multiple times. The same goes for all current OOC gear now that I think about it, maybe there could be some sort of `allow_multiple_purchases` gear variable.

I took a gander at it again and it feels like a mission in utter madness to attempt making loadout gear purchasable multiple times... Maybe someone who is actually a competent coder could do it without wrecking the current preferences.

**Comment by ike709** [comment]
Closing since the requested changes can't be done by the PR author

**Comment by yorii** [comment]
I'm pretty certain that the requested changes can't be done, period.

**Pull request closed without merging**
