### PR TITLE
Emoji filtered word fix

### PR DESCRIPTION
**Pull request by Blueturbo47**
## About The Pull Request
The meatball emoji was named the fgt word, now it is named mball.

## Why It's Good For The Game
Filtered word bad

## Changelog
:cl:
fix: renames an emoji away from a filtered word
/:cl:

### CODE REVIEW

**Comment by Blueturbo47** [comment]
I realized I did something wrong, fixing now

**Comment by Blueturbo47** [comment]
I actually don't know how to fix It so I'm gonna just keep with the 3 commits, the first 2 were already merged in [gh#3640](https://github.com/BeeStation/BeeStation-Hornet/pull/3640) which are the map changes

**Review by Archanial — CHANGES_REQUESTED** [review]
Map changes are 99% not intended.

Don't commit to your master smh my head

**Review by park66665 — APPROVED** [review]
All clear. This PR is good to go.

**Pull request merged**
