### PR TITLE
Smooth Movement

### PR DESCRIPTION
**Pull request by qwertyquerty**
## About The Pull Request

Properly calculates glide sizes in order to have good smooth movement.

Port of [yog#8132](https://github.com/yogstation13/Yogstation/pull/8132) - Thanks Monster860!

## Why It's Good For The Game

Hurts the eyes lesser when the movement happen

## Changelog
:cl:
fix: Movement is now smooth
/:cl:

### CODE REVIEW

**Review by ike709 — DISMISSED** [review]
Fix the line endings you fool.

**Comment by qwertyquerty** [comment]
They're already LF @ike709

**Comment by TotallyNotChief** [comment]
god this feels so wrong

**Comment by qwertyquerty** [comment]
@monster860 we're experiencing a bit of jumpiness while walking


https://imgur.com/a/KeeyCK7

**Comment by monster860** [comment]
lower the default fps, 60 is too high

**Comment by ike709** [comment]
@qwertyquerty are you going to give this another go at a lower FPS or what?

**Comment by qwertyquerty** [comment]
Yeah I'm going to give it another go at 40. Shame I have to bump the savefile version yet again.

**Comment by Coolsurf6** [comment]
What happened with this?

**Comment by qwertyquerty** [comment]
testmerging this boy again

**Comment by KingTerrytheTerrible** [comment]
Can we have a toggle in preferences for this please?

**Comment by ike709** [comment]
It's not happening, chief.

**Pull request closed without merging**
