### PR TITLE
Skeletons can also heal by drinking cream

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
It's virtually the same as milk, why drinking cream do nothing?

## Why It's Good For The Game
It's consistent and gives skeletons a source of heals which doesn't force raiding a locked refrigerator. 

## Changelog
:cl:
add: Skeletons can now heal by drinking cream also.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Tested?

**Comment by VictorVow** [comment]
Yup

**Review by zeskorion — APPROVED** [review]

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Tested it with beebot ?compile, I am definitely sure that this doesn't work since the || isnt checking if chem.type == cream, it's just checking if cream

**Comment by PowerfulBacon** [comment]
Closing due to inactivity, feel free to open again if you change this to work

**Pull request closed without merging**
