### PR TITLE
T-ray scanner buffs

### PR DESCRIPTION
**Pull request by CydiaLamiales**
## About The Pull Request
Increases the amount of time the revealed underfloor objects stay on the screen.
Adds the ability to toggle between 'scanner' and 'blueprint' mode for the T-ray scanner. The 'blueprint' mode reveals the normal layout of pipes, wires and disposal pipes, same as the 'view structural data' function of the Station Blueprints.
## Why It's Good For The Game
The T-ray scanner is heavily underused as its 'flickering' its too short and often lags behind when you're moving, and they stay visible for not that long. The increased stay time of the revealed items generally helps with that, and the 'blueprint' mode allows engineers and atmos techs to more easily follow pipes and wires. Also allows for easier reconstruction of destroyed areas, without needing to beg CE for the blueprints or needing to use a map viewer.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/110184118/226894731-9c7d65c2-ad55-4459-86a0-0bee1ec42d89.mp4

</details>

## Changelog
:cl:
add: Added the 'blueprint' mode to the T-ray scanner, which shows the normal layout of pipes, wires and disposal pipes
add: Added the ability to toggle T-ray scanner modes by Alt-clicking it
tweak: Things revealed by the T-ray scanner now stay visible for 16 ticks rather than 8
imageadd: added an icon for the T-ray scanner in the 'blueprint' mode
/:cl:

### CODE REVIEW

**Comment by CydiaLamiales** [comment]
'missing' pipes and such are a mapping issue I'm fairly certain, the station blueprints don't show them too.

**Comment by Pirill** [comment]
This is really cool and would definitely come in handy but...goddamn it looks janky as hell with those invisible pipes on the display, eugh.

**Comment by itsmeow** [comment]
> 'missing' pipes and such are a mapping issue I'm fairly certain, the station blueprints don't show them too.

How could it be a mapping issue, they are just straight up not visible on the blueprints. You should probably find a fix for that as well

**Comment by PowerfulBacon** [comment]
Check their flags to ensure they have the blueprint flag and its not accidentally overriden due to how flag overriding works.

**Comment by CydiaLamiales** [comment]
> Question is why would anyone use "normal" t-ray mode when blueprint is vastly superior?

Normal also shows any invisible entities, wires as they are right now and also satchels hidden under the floors.

**Comment by CydiaLamiales** [comment]
I think I see the issue
image
Manifold pipes don't get icon states, they instead get overlays
image

**Review by itsmeow — APPROVED** [review]
Since the bug is a bug with blueprints and not T-ray itself I'm okay with this. T-ray in generally is a really bad item, and restricting cable/wiring blueprints to the CE has never made sense to me.

**Pull request merged**
