### PR TITLE
Replaces Supermatter engine set ups with Tesla set ups as a temporary measure (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by CydiaLamiales**
## About The Pull Request
Replaces the Supermatter Engine and its surrounding areas with an incomplete Tesla engine.
Maps completed : 

- [x] Box
- [x] Meta
- [x] Pubby
- [x] Corg
- [X] Kilo
- [X] Delta

## Why It's Good For The Game
With the recent atmospherics bugs, starting the Supermatter is a coinflip, with Heads being that gasses don't spread and it delams almost immediately, and tails being that it'll delam eventually. With this PR, engineering won't have to struggle with that anymore.
Pros : Setting up power is no longer an issue of RNJesus being graceful.
Cons : more FUN! rounds with teslalooses

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

The note : 

image

Meta : 

image

Box : 

image

Corg : 

image

Pubby : 

image

Kilo : 

image

Delta SM: 

image

Delta Engine:

image

Roundstart Tesla being quiet while in engineering but getting louder when it goes loose :

https://files.catbox.moe/owqo7v.mp4

</details>

## Changelog
:cl:
del: Removed the Supermatter and the objective to steal the Supermatter sliver
add: Added an incomplete Tesla set up, a crate with the Particle accelerator that explains what happened.
add: Added 'old' Tesla coils that are 15% as effective as regular ones and a 'rusted' Tesla Generator that can't be moved and spanws a 'dampened' Tesla ball that doesn't make as much noise while inside of the SM room.
/:cl:

### CODE REVIEW

**Comment by CydiaLamiales** [comment]
Gah, accidentally hit 'complete' too early. Anyhow, making this before I go to sleep and my internet gets cut during the night,

**Comment by CydiaLamiales** [comment]
Would be neat if someone could make this into a station trait, but I'm too dumb to do that.

**Comment by CydiaLamiales** [comment]
Alright that's all maps done.

**Comment by CydiaLamiales** [comment]
Welp, looks like another solution to the atmos issue was found, oh well. Probably should've been faster with making this.
Actually, might use this for a station trait if I have the time.

**Comment by Penwin0** [comment]
This PR can probably be closed

**Comment by CydiaLamiales** [comment]
Yeah you're right I probably should

**Pull request closed without merging**
