### PR TITLE
New space ambience song "Drifting"

### PR DESCRIPTION
**Pull request by qwertyquerty**
## About The Pull Request

Adds a new space ambience song "Drifting"

listen to it here https://qtqt.cf/player/space5_session.wav

## Why It's Good For The Game

Music is pretty nice

## Changelog
:cl:
soundadd: Space ambience song "Drifting"
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
This sounds awesome, station ambience when

**Comment by Fronsis** [comment]
Add this person 1000PP's to their Osu! profile... NOW

Amazing job as always, super chill stuff

**Comment by LodedDiper69** [comment]
It sounds like minecraft music

**Comment by DerpiestBruh** [comment]
Merge this so my lemonade business keeps running

**Review by ike709 — APPROVED** [review]

**Pull request merged**
