### PR TITLE
[PORT] Bloody Footsteps from paradise

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

title

## Why It's Good For The Game

the old ones look ugly

new: https://gyazo.com/3c571163ebffdf8daa9a08af28cfc2dc

ORIGINAL PR: https://github.com/OracleStation/OracleStation/pull/40

## Changelog
:cl:
imageadd: added new footprints
imagedel: deleted old footprints
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
image

Seeing this along with no code changes is never particularly good

**Comment by ghost** [comment]
> image
> 
> Seeing this along with no code changes is never particularly good

works as intended ingame.

**Comment by qwertyquerty** [comment]
It appears to delete xeno trails?

**Comment by TotallyNotChief** [comment]
this looks infinitely worse than what we currently have

**Comment by ghost** [comment]
cant track down the issue even after manually applying sprites

**Pull request closed without merging**
