### PR TITLE
Removes genders from IPC's

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Title

## Why It's Good For The Game

How does a robot have genders?

## Changelog
:cl:
tweak: IPC's no longer have genders.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
fuck man my repo is dirty as fuck, i have to reset this sometime soon.

**Comment by PowerfulBacon** [comment]
0 and FALSE are the same thing, this wont change anything

**Comment by ghost** [comment]
> 0 and FALSE are the same thing, this wont change anything

well, i looked at etherals which doesnt have genders and its set to FALSE there

**Comment by FortSumter** [comment]
Why can't sentient robots have genders? I hate to side with that freakshow of a community, but gender is not the same as sex. Just because they don't have sex organs doesn't mean an IPC can't identify as a man or a woman. They were made by humans, and spend most their time around humans, It's only natural that they adopt their gender identities to better relate to them. Why don't Etherials subscribe to this policy? No idea, but they're aliens so the concepts of gender and sex may be completely foreign to them.

**Comment by FortSumter** [comment]
I don't really care about this PR one way or another, but I thought I'd bring that up to try to explain why they have genders or to give some food for thought on the subject.

**Comment by ghost** [comment]
> I don't really care about this PR one way or another, but I thought I'd bring that up to try to explain why they have genders or to give some food for thought on the subject.

image

etheral code comment

**Comment by FortSumter** [comment]
I'd like the person who added that comment to explain that. What is a fetish related to lightbulbs having genders besides the obvious moth ERP, and why would them NOT having genders stop that in any capacity? To reiterate, it would make sense lore-wise for IPCs to have genders, but them having/not having them wouldn't matter at all because few players bother to RP anyway. The worst case scenario will always be the FO:NV sex bot reenactment, and they don't need genders to do that.

**Comment by PowerfulBacon** [comment]
Closing, since this PR doesn't change anything since FALSE is exactly the same as 0, just a different way of writing it. The system itself is probably broken if they can have genders dispite it being disabled. If you fix it, feel free to open again

**Pull request closed without merging**
