### PR TITLE
fixing maints

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
maintenance under viro on meta and delta is now traversable without effort again

## Why It's Good For The Game
requested by maintainer

## testing header

image
image

## Changelog
:cl:
tweak: maint under viro is now traversable on meta and delta again
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Testing portion of Pr body should not be removed

**Comment by PestoVerde322** [comment]
Aright, some more things should be fixed:

Metastation:

immagine

Zoning is all wrong, please double check, and the Aft maint should go all the way up to where the airlock is instead of ending abruptly by the chapel office.

immagine

Viro maint leading to an open randomaint, as much I'd like the idea, this may cause some issues if some rooms spawns there (see the clown suit room, which has a slim chance to spawn a floor clown coming for your)

Delta2:

immagine

Wrong zoning here, please fix.

all of those in-between spaces, they kinda look... drab, consider adding some more junk.

Also on my personal take on both, I think you could expand the maintenance a little more by adding an hallway to make it more seamless with the rest of the station, since both box and pubby actually look like continuous maintenance halls instead of being interrupted by storage.

**Comment by zeskorion** [comment]
> Zoning is all wrong, please double check, and the Aft maint should go all the way up to where the airlock is instead of ending abruptly by the chapel office.
> Wrong zoning here, please fix.

fixed, i forgot zoning yesterday morning

> Viro maint leading to an open randomaint, as much I'd like the idea, this may cause some issues if some rooms spawns there (see the clown suit room, which has a slim chance to spawn a floor clown coming for your)

this is so astronomically rare to occur its laughable. regardless, hallway integrated

> all of those in-between spaces, they kinda look... drab, consider adding some more junk.

added

> Also on my personal take on both, I think you could expand the maintenance a little more by adding an hallway to make it more seamless with the rest of the station, since both box and pubby actually look like continuous maintenance halls instead of being interrupted by storage.

added hallways where practical

**Comment by zeskorion** [comment]
> Testing portion of Pr body should not be removed

blehhh i just wanted to quickfix this loading maps is hard, but done

**Comment by PestoVerde322** [comment]
Metastation:

immagine

Zoning still weird.

immagine

Remove the window and center up that door.

Delta:

immagine

Very nasty corner, please move the maints a bit.

immagine

Hehe...

**Comment by zeskorion** [comment]
> Metastation
> 
> Zoning still weird.
> 
> Remove the window and center up that door.
> 
> Very nasty corner, please move the maints a bit.

gosh these are rookie mistakes. apologies, i was half asleep


> Hehe...

10% chance to spawn a melee only cat butcher each round, if the room is entered a certain number of times. will remove if necessary

**Review by PestoVerde322 — APPROVED** [review]
All seems good to go now.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
