### PR TITLE
Span macros

### PR DESCRIPTION
**Pull request by KubeRoot**
## About The Pull Request

Refactors most spans in the DM code into span macros.

- Widespread code changes based on https://github.com/tgstation/tgstation/pull/59645
- Macros based on https://github.com/tgstation/tgstation/pull/59685

Due to the sheer amount of conflicts when trying to cherry-pick, I have redone the work based on the regexes in the initial proc version and the macros in the later refactor.

This PR adds macros in the format of `span_CLASS(CONTENT)`, for example:
```dm
span_warning("It looks slightly dented")
```
As opposed to:
```dm
"<span class='warning'>It looks slightly dented</span>"
```

Most existing spans have been refactored to use the macros, with notable exceptions being:
- Anything using spans for more than classes, primarily anything using inline `style`
- Any spans using multiple classes, notably `greentext big`, `cult italic`, `his_grace big bold`, `message linkify`
  - Most common cases of those could be made into individual classes - notably `cultitalic` exists, though I'm unsure if it's the same as `cult italic`.
  - In other cases, it might be valid to split them up into multiple nested spans, though I'm unsure if that'll always have the same behavior.
- Type definition vars, as those cannot have `[]` in them, because they have to be compiletime constants and BYOND can't handle those
  - Most notably descriptions for golem types
  - With the exception of ones where the whole string is wrapped in a span, in which case using a macro works.
- Code that builds the message out of smaller strings, with the span broken up between them
- Code that decides which class to use dynamically
- Some very rare/specific classes, in particular for debug menus

The main reasoning for this change is:
- tg did it, will be easier to port stuff
- Code with spans will be more consistent
- There will be a place to look for span classes, that is the `code/__DEFINES/span.dm` file.
  - *psst: wouldn't it be nice if we got comments describing each class and what it represents?*
- This will help avoid errors when working with spans - and there were a lot of them. Missing closing tag, malformed closing tag, `style` instead of `class`, typo like `clas`, `span_class='notice'`, `span='notice'`. With this, you either get something wrapped in a valid span, with proper opening and closing tags, or you get a compiler error.

Additionally also fixes various broken spans I have stumbled upon while fixing things. Those are generally the rarer messages, but hey, every bit counts.

Mood events have been slightly refactored, the `\n` is no longer part of every single description and is instead added when printing out the mood events. This allows the usage of span macros in mood event descriptions, since they can now encompass the whole thing without using `[]`

## Why It's Good For The Game

Code improvements, hopefully less broken messages in chat.

## Changelog
:cl:
refactor: Refactor spans in code to use macros instead of being written out directly. If you spot any new broken messages in chat, having missing text, broken tags in the message, or being formatted wrong, make sure to report them.
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
christ

**Review by Sinestia — DISMISSED** [review]
Very pogchamp, lags github forcing this PR to be opened in vsc. 

Actually does look like it will make things a lot more comfy to write and read.

**Comment by PowerfulBacon** [comment]
This seems somewhat pointless when we could find all the spans in the stylesheet folder anyway.
I would be ok with it, but isnt it going to be slower replacing every single string with adding 3 strings together and for no real gain? I know byond converts macros to whatever is in them on compile, but I am pretty sure it converts it literally rather than working out the final value, but dont quote me on that.
If I am not mistaken, every single string is going to be 
```
"Span" + "your text here!" + "/span"
```
As opposed to just "spanyour text here/span".
This will need a profile though to see if there is actually a non-negligible difference.
Also is "span[text]/span" faster than adding them together? Not sure how byond handles it.

I dont suppose tg made sure it wouldnt be slower considering they made them *procs* in the first place.

image

image

(Not really sure how the macro ended up being slower than the straight up adding together strings)
In every single test I performed, the raw string was the fastest, the adding together 3 strings was the second faster and the macro was always the slowest. (This ignores the tests where negative numbers were given, assuming because they overran)

It's not too much in the grand scheme of things and it won't dramatically slow down the game, but it is still something to consider.

**Comment by francinum** [comment]
... But why

**Comment by KubeRoot** [comment]
Uh oh, I think somewhere in there I commited the wrong file and changed `admins.txt` instead of `scanners.dm`

**Comment by PowerfulBacon** [comment]
trying to take over the server

**Comment by KubeRoot** [comment]
How the hell did the tgui build fail, I don't even modify tgui

**Comment by Kapu1178** [comment]
merge please

**Comment by PowerfulBacon** [comment]
This is just annoying imo ando only useful for ports. I see no positive benefit to it. :key:

**Comment by KubeRoot** [comment]
> I see no positive benefit to it.

There is an obvious, indisputable positive benefit based on how many broken spans we have right now. If nothing else, broken spans won't compile when using macros.

That said, I'm generally of the opinion that it's much nicer to use macros than write out the spans manually, primarily because they get autocomplete and it's easier to see where spans begin and end.

In the end though, merged or rejected, at least it'll be some closure. So far it seems like one maintainer is positive about it, two are negative, and I can't be sure what ike means by "christ" but might be negative as well. So 1-2 with possibility of 1-3.

**Comment by PowerfulBacon** [comment]
Its (extremely minor) slowdown and kind of ugly, and will get even uglier very quickly when stacking them when the span classes stack well normally 'big boldannounce'. Personally I think its easier to see when the spans end since rather than trying to see which bracket lines up to what, the </span> is a lot more obvious. Also I don't like how instead of all of them being normal defined spans, some of the code is normal defined spans and some of it is a macro.

I feel like these could be useful for development if you like them but would be better off being ctrl-fed and replaced with the span in full after you are done with it like a VS code plugin.

**Comment by francinum** [comment]
No.

**Comment by Archanial** [comment]
Why though

**Comment by Urumasi** [comment]
`<span='danger>Your pull request has been closed!<span>`

**Pull request closed without merging**
