### PR TITLE
Slaughter demons no longer round remove people

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

This makes it so victims of slaughter demons are not deleted, instead they're kept inside the slaughter demon, and whenever the demon is killed, it'll violently expel all the bodies it's consumed.

Unlike laughter demons though, these bodies will still be very much dead.

## Why It's Good For The Game

Round removal bad.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/65794972/230798788-636191be-4bc2-4b8d-a169-91be0e342d7b.mp4

</details>

## Changelog
:cl:
balance: Slaughter Demons no longer delete people after eating them
/:cl:

### CODE REVIEW

**Comment by imsynthex** [comment]
It is worth keeping in mind that slaughter demons cost twice as much as laughter demons so I'd argue the bodies should at least be husked, though I don't think this change is positive to begin with, since the whole point of having laughter and slaughter demons is that one round removes people and the other doesn't, if you're making the slaughter demon not round remove people, you might as well remove the laughter demon

**Comment by Absolucy** [comment]
@imsynthex Well, the current direction of the codebase seems to be that permanent round removal is almost always a bad thing and very detrimental to player enjoyment - see https://github.com/BeeStation/BeeStation-Hornet/pull/8684 and https://github.com/BeeStation/BeeStation-Hornet/pull/7500

**Comment by Fronsis** [comment]
> It is worth keeping in mind that slaughter demons cost twice as much as laughter demons so I'd argue the bodies should at least be husked, though I don't think this change is positive to begin with, since the whole point of having laughter and slaughter demons is that one round removes people and the other doesn't, if you're making the slaughter demon not round remove people, you might as well remove the laughter demon

I believe a lot of us agrees that RR sucks, you could balance it down by reducing the cost, removing laughter or.. the aforementioned husk, the thing is the slaughter demon in the correct hands can cause, as their name says, a slaughter and the main issue is that all of the wizards summon them the moment they arrive into the station, meaning that people ultimately gets round removed >20 minutes into the shift depending on how quickly the Wiz kills other crewmembers or if the slaughter demon needs to do all the job, which is horrible to experience, because ultimately if the demon gets defeated you have no chance of returning to your character and you're left to observe and wait for a midround.

Lately we've been having balances around RR's so i don't see why this should be an exception:

Space dragon rework.
Morph digestion is no longer a mob-delet, just a husk
Lavaland Megafauna Colossus and Hiero no longer dust, just gibs but it's still recorevable 
And once the heretics rework gets merged even sacrifice victims can be back to station after a minigame without having to wait for doctors to find them and pull back all their organs (IF the heretics don't carry their body on a bs bag which a lot of them have done lately...)

**Comment by Pirill** [comment]
Gotta agree with some of the thoughts here, although I'd propose gibbing as an alternative to husking the bodies. Bonus points if it makes an even bigger blood mess, fitting of the namesake, which would give the demon a tactical benefit to killing people too.

**Comment by PowerfulBacon** [comment]
Instead of husking, how about gibbing them on release

**Comment by Absolucy** [comment]
I'll remake this PR with gibbing later

**Pull request closed without merging**
