### PR TITLE
Corg  brig remake

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request

Corg brig remake

## Why It's Good For The Game

Adapts the map for genpop

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

0-after

https://streamable.com/1o68ec

</details>

## Changelog
:cl: ClownMoff
tweak: CorgStation: Brig is now usable
tweak: removes the cargo dorms and puts the QM office where they used to be
tweak: changes hallways  and maintenance around brig
tweak: moves the public garden next to the chapel
tweak: puts the gravity generator in engineering below the SM
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
Write a more detailed CL of all the changes, especially those outside of the Brig. Things that someone who doesn't hang out on GitHub and only play SS13 once a week might want to know.

And also, why "Fart Smella"?
image

**Review by MarkusLarsson421 — COMMENTED** [review]
Review

<details>

image

Also a full window in a concave corner.

Floating light and camera. Also no distro in this room except the three random waste pipes.
image

This intercom has "free range" set to 1, meaning they can talk and listen to ALL station channels, Security, Command, Science, and so on. Use the intercom found on Rad Station prison.
image

Three soaps, remove two? It's like you hate Security Officers. lol
Also, two air alarms in this room, remove one.
image

Weird light button placed INSIDE a wall. It is placed on the smaller square and can only be reached from the larger square.
image

This room... really shouldn't exist. Small memey rooms are fine when it is a 1x1, but you could definitely fit a maintenance here.
image

image

Spaced tile plus light on door.
image

Same with the Interrogation room which should be set to 63 AND 4.
image

Unpowered windows.
image

Why the hell is this pixel shifted so weirdly?!
image

Light in wall.
image

Pipe in window.
image

Two HoS offices? You only really need one, they have the same equipment
image

There is currently three extra batons on this map, feels a bit overkill. Replace them with a toy variant or remove them.

News caster on top of an APC.
image

You only got four extra Security lockers and no extra spawns for more of them.

APC on top of a news caster.
image

Ignition switch doesn't have the same ID as the igniter, therefore it won't ignite.
Also, don't put distro into this room.
image

Weirdly placed door / table.
image

Access set to 63, it should be set to 1. Unless you want Lawyers to tide into Security.
image

Weirdly placed armoury buttons? Put them on the same tile and as close to the armoury as possible inside the Warden office.
image

Disconnected wire.
image

No distro in the Detectives office.
image

No access requirement on the solitary cell.
image

Use the new Secure floor variant Pigeon added.
/turf/open/floor/prison/dark
image

Three nodes?
image

No anesthetic tank holder, IV does not work with it.
image

No camera should be in the reeducation room.
image

This isn't a problem, but I would move the evidence room to the marked location with a direct access door for Security, Interrogation and Detectives, then rotate the labour shuttle dock 90*.
image

Regular windows!!!!! As soon as the shuttle leaves the room will depressurize!!!!
image

Weirdly close shuttle dock, should be a tile away from the station walls if possible.
image

What is... this?
image

Island area.
image

Disconnected APC.
image

Wire to no where?
image

</details>

**Comment by Fronsis** [comment]
That interrogaton room relocation seems interesting, IMO interrogation rooms should be easy to reach and not too far off, Corg has been the main offender on this due to having to process a prisoner on genpop/old prison and having to walk all the way up there to store evidence, having it where  Markus suggested seems fine, pretty much we swapped the ''Corg has the pro of you can access evidence from space but an unraidable armory'' to the opposity so i'll take that


Screenshot_29
Table feels too empty, i would add two pairs of cuffs on the main one, spread, and then slap two rechargers on the main table corners, and another on the small table, considering we have up to five officers+Hos+Warden the current version you're proposing only has three, one in Warden office and two on that ''meeting room'' so i'd say we could go with three rechargers spread on the gear room for officers to use to keep consistency(maybe HoS could use one)

Remember to add the detective camera and tape recorder to the locker/table of his office

I also agree that three soaps might be too much

Floating APC on brig phys office but i'm sure Markus already pointed it out

And uhmm.. you can add a real chocolate donut on the main table for flavor as well

And remember you can tweak the execution room a little bit to make it more ''fun'' or unique while leaving the default stuff, up to you tbh!

**Comment by MarkusLarsson421** [comment]
> Added a video as an evidence

It isn't being embeded? Is that someone which can be fixed?

**Comment by ClownMoff** [comment]
https://streamable.com/1o68ec

**Review by BriggsIDP — CHANGES_REQUESTED** [review]
https://discord.com/channels/427337870844362753/590714573611597824/1210285316519366716
Required mapping changes above

**Comment by ClownMoff** [comment]
Fixed

**Comment by ClownMoff** [comment]
1.- Fixed
2.- Yeah  
3.- Armory
4.-Added a monitoring screen

**Comment by MarkusLarsson421** [comment]
Why the Clown mask in the evidence room?

**Comment by ClownMoff** [comment]
Funny

**Review by PestoVerde322 — APPROVED** [review]

**Review by PestoVerde322 — APPROVED** [review]

**Pull request merged**
