### PR TITLE
Moves Exploration Shuttle and Adds Exploration Ghost Role

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
Adds an Exploration Ghost role, they will start out in one out of the three roles and are heavily damaged when they emerge from their safe space (a fridge).

## Why It's Good For The Game
Allows people to play as a REAL Explorer and tell everyone how wise you are as you run head first into a cultist infested derelict station with zero regard for your own well being. It's fun.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image

image

image

</details>

## Changelog
:cl:
add: Added Explorer Ghost role
fix: Fixed ghost controllable bodies having a stasis machine they will leave behind, such as the Comms Agent.
imageadd: Added two landmarks for the ghost role.
code: Changed `code\modules\awaymissions\corpse.dm`, too much to list.
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
I haven't touched the original crash site as it is removed by #11383.

**Comment by ColonelOrion** [comment]
- Funny Top Gear reference, based.
- Why are you damaging the explorer round start, you sadist! Goddam! Definitely remove the roundstart injury, that's just going to be infuriating to the benefit of no-one.
- The crashed shuttle was in a great spot already, no need to move it. You're just making it needlessly more complicated to get a shuttle set up, and it ALREADY takes an hour or two on dry land, dealing with role changes, engineering access, and the like.
- All in all, just roll the role addition into the other PR, imo.

**Comment by MarkusLarsson421** [comment]
> Why are you damaging the explorer round start, you sadist! Goddam! Definitely remove the roundstart injury, that's just going to be infuriating to the benefit of no-one.

They are a survivor of the crashed shuttle. That's why they were hiding in the fridge.

**Comment by MarkusLarsson421** [comment]
Going to put this into a larger PR focusing soley on ghost roles.

**Pull request closed without merging**
