### PR TITLE
[PORT] Nanopaste

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Adds Nanopaste as a thing you can research, med borgs and syndie medborg start with them.

## Why It's Good For The Game

So that the medical doctors actually have a way to repair IPC's that doesn't involve destroying their eyes or go hunting for a welding mask, medical borgs also lacked any way to heal IPC's.

ORIGINAL PR: https://github.com/OracleStation/OracleStation/pull/472

## Changelog
:cl:
add: Nanopaste is a thing now. Use it to repair cyborgs, IPCs, or other robotic limbs. Not currently a surgical step.
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
why?
It's not like it's super hard to heal ipcs and cyborgs.
This will make medi borgs unstoppable, since they can heal themselves now.
Also why does it heal pais? They can't be damaged?

**Comment by ghost** [comment]
> This will make medi borgs unstoppable, since they can heal themselves now.

now they can't.

**Comment by Archanial** [comment]
I still see no point of this being in game.
We have engiborgs, standards and even minening borgs who can fix ipcs. 
If you see dead IPC just bring him to robotics.

**Comment by ghost** [comment]
> I still see no point of this being in game.
> We have engiborgs, standards and even minening borgs who can fix ipcs.
> If you see dead IPC just bring him to robotics.

my point is that should be the job of the **medical** borg not the mining or engineering borg, and healing crew should be the job of the doctors, not the roboticists.

**Comment by Archanial** [comment]
I disagree. Medical borgs should treat humanoid races and ipcs should be treated by roboticists or even engineers.

**Comment by super12pl** [comment]
Autolathe at science that can print welding tools and welding mask is about 12 tiles away(or less) from medbay entrance
really not that hard to get

**Comment by felceryan** [comment]
IPCs have no purpose of going medbay anyway they can't be cloned and only repaired which is the job of a roboticist

**Comment by PowerfulBacon** [comment]
IPCs should be taken to robotics not medical, I just think this is an oversimplication and kind of oversteps the line between QoL and removing complexity

**Pull request closed without merging**
