### PR TITLE
Adds Debtor and Assistant traitor item, Bottle of Mystery Pills

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
Adds Debtor and Assistant Role-Restricted Traitor Item, Bottle of Mystery Pills for 3TC. This bottle contains seven maint pills.

## Why It's Good For The Game
Debtor had no traitor items so I wanted to make one thematically appropriate. I also threw it in for assistants because why not.

## Changelog
:cl:
add: Debtors and Assistants can now purchase a Bottle of Mystery Pills for 3TC.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
3 TC seems to be wayyyy too high for shitty non-harmful drugs

**Comment by BrumalLake** [comment]
3 tc for some ephedrine and coffee being the best roll of like 5

**Comment by Ivniinvi** [comment]
I wanted to err on the safe side, I figured if it was 2tc and you bought 20tc of them, one of those 70 pills would contain something busted and usually unavailable.

**Comment by Ivniinvi** [comment]
But, I'll change the cost to 2 and see how the maintainers like it.

**Comment by PowerfulBacon** [comment]
Either you die, get borged or become unstoppable for 5 minutes

**Comment by Rukofamicom** [comment]
unless floorpills were nerfed, this feels like a hell of a bargain, especially since debtors can identify what's in the pills. Why is this given to assistants too though?

**Comment by Ivniinvi** [comment]
The fact that maint pills cannot have their reagents extracted from them seriously limits their offensive use. The item was initially designed for Debtors, but assistants are generally a huge fan of maint pills, so I decided to add it to them as well. Of course, for them it will be significantly worse, as they don't have the appraisal trait.

**Comment by PowerfulBacon** [comment]
This is probably never going to be bought and just bloat the menu, at least its job restricted

**Comment by wraith-54321** [comment]
I would buy it as assistant, could do some fun gimicks

**Comment by spockye** [comment]
> I would buy it as assistant, could do some fun gimicks

chug all of them and hope for the best

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
