### PR TITLE
Kilo Changes and Fixes

### PR DESCRIPTION
**Pull request by Emotions211**
## About The Pull Request

Greatly reduces the decal usage throughout all of Kilo. Airlock are no longer surrounded by stripes decals. Most machines are no longer standing on top of decals that would likely never be seen,  etc. These mainly constitute performance improvements. 
Permabrig has had glass tables replaced with regular metal tables.
Virology no longer has a way into maintenance. A proper airlock as also been added to virology and the door in from Chemistry has been removed. The walls that make up the airlock are now reinforced in case of chemist explosions.
Removes all old mining mobs (Goliaths, Hive Lords). Snakes have been placed in the maint rage cage similar to Pubby. 2 spiders have had their health edited down to about 40 hp.

## Why It's Good For The Game
Reduces the amount of decals allowing Kilo to actually be used without players crashing or low frame rates. If approved, adds a fifth station back into rotation for more map variety.

## Changelog
:cl:
add: Secure Virology airlock added to kilo
del: Maint doors into viro removed on kilo
del: side door into vault removed on kilo
del: Large amount of decals removed for stability on kilo
tweak: replaced glass tables in kilo perma with regular tables
balance: 2 maint spiders have much lower health on kilo
/:cl:

### CODE REVIEW

**Comment by Emotions211** [comment]
Travis failed due to the ~~viro airlock buttons being offset.~~ dirty offsets on a chem heater and intercomm.

**Comment by dekunutkid** [comment]
You should probably edit the changelog so that it isn't so ominously ambiguous when reading the change log in-game, since the in-game changelog needs context.

**Comment by Emotions211** [comment]
That should be better now.

**Comment by dekunutkid** [comment]
Also, according to my atmospherics contact, Kilo gas chambers only store 800 kPA worth of gas at 20C except for Oxygen and Nitrogen, making atmos mixes nigh impossible. Any chance of fixing this too?

**Comment by Emotions211** [comment]
Every time I get merge conflicts with bee bots changelog compiles. Starting to get annoying.

**Comment by qwertyquerty** [comment]
Don't force push like that next time. You need to undo the changelog changes here

**Comment by qwertyquerty** [comment]
@Emotions211 conflicts bro

**Pull request closed without merging**
