### PR TITLE
Smooth Movement

### PR DESCRIPTION
**Pull request by cerebral-314**
## About The Pull Request

Makes movement smooth... uses glide(a thing Byond has had for awhile now)
Examples:https://github.com/BeeStation/BeeStation-Hornet/pull/2364#issuecomment-683518689
Credits: https://github.com/tgstation/tgstation/pull/52515

## Why It's Good For The Game

Smooth is better right?

## Changelog
:cl:
tweak: Movement is now smooth
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
no it's fucking terrible.

**Comment by cerebral-314** [comment]
You haven't even tried it 🤷

**Comment by ghost** [comment]
> You haven't even tried it 🤷

i tried it on TG and it felt like i was teleporting between tiles.

**Comment by cerebral-314** [comment]
Not trying to shit on /tg/ or anything they're cool, but they don't have the best server framerate as it is(constant 40-50% time dilation is a no go).
Get the files and just try it yourself my guy. BeeStation code is much more robust.

[/tg/ with 30 players(I have 150ms)](https://drive.google.com/uc?id=1GiZ2l_SaEMapXM4eItOF6hSpOokn88LN)

[/tg/ basil 85ish players(again bad internet) and with high dilation](https://drive.google.com/uc?id=112gzCQZ6pqxNpX17Mafx5-jIv_sx3LF2)

[best case scenario(local server) 0 dilation on BeeCode<-- was messing with tickrate so alittle sped up.](https://drive.google.com/uc?id=11npeNyJIpSepXI2BMksMJYyEl0LjOe6j)

EDIT:
Turn your FPS up(I play with 60).
https://github.com/tgstation/tgstation/pull/52515#issuecomment-666738357

**Comment by PowerfulBacon** [comment]
I swear someone did this before but was too janky

**Comment by TotallyNotChief** [comment]
This has been done on bee before and nobody liked it

**Comment by ModDownloading** [comment]
Yup, it was #1513 that tried smooth movement for the first time, and everyone hated it because it just made stuff more laggy in the long run. It may work great if you are on your own, but it has been tested on the server already with poor results. I'm sorry, but I honestly don't think it is going to work this time around either.

**Comment by yorii** [comment]
testmerge it and then have a vote?

**Comment by cerebral-314** [comment]
Qwerty did basically the same exact thing I did... if the people didn't like it then they won't like it now.

**Pull request closed without merging**
