### PR TITLE
Plasmaman envirosuits for wardrobes

### PR DESCRIPTION
**Pull request by Sarchutar**
## About The Pull Request

Adds a big Plasmaman internals tank to research and to the autolathe/protolathe.
Adds Plasmaman envirosuits to wardrobes and the mining wardrobe locker.

## Why It's Good For The Game

It is good for Plasmaman who want the department clothing after they got a job change and there is a big oxygen tank, so there should also be a big plasma tank.

## Changelog
:cl:
add: big Plasmaman internals tank in research and autolathe/protolathe
add: Plasmaman envirosuits for wardrobes and mining wardrobe locker
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
the extra plasmaman clothing isn't a bad thing, and would make cloning plasmamen alot easier. 

but the big internals tank it kinda pointless when you could just fill the large oxygen tank with plasma instead of oxygen

Ontop of that plasmamen don't really burn through plasma very fast, one internals tank usually lasts an entire round and then some.

**Comment by Sarchutar** [comment]
> but the big internals tank it kinda pointless when you could just fill the large oxygen tank with plasma instead of oxygen
>
> Ontop of that plasmamen don't really burn through plasma very fast, one internals tank usually lasts an entire round and then some.

I only added the big tank because it was already in the code with an icon/sprite and not used but it could also be good for rounds that go past 1 hour.

**Comment by ghost** [comment]
okay but why not just refill your canister, a single plasmaman internals can last roughly an hour and it's not hard to get it refilled. 

the only thing this does is inadvertantly buff toxin bombs by givin them access to a larger canister for hotter plasma and doesn't really do much for plasmamen over all

**Comment by Sarchutar** [comment]
It isn't a larger canister it is the same size like the big oxygen tank it basically is the same thing with another sprite. 

If the problem is that it is in the autolathe so that everyone can get it i could remove it from there or if it really is pointless then completely remove it.

**Comment by ghost** [comment]
its almost entirely pointless

**Review by ike709 — CHANGES_REQUESTED** [review]
Not sure why qwerty hasn't looked at this yet.

Now that the regular tank and the belt tank are both in use, you'll need to change the name of at least one of them to prevent confusion. Maybe call the regular tank `extended-capacity plasma internals tank`? Otherwise this PR is fine.

**Comment by qwertyquerty** [comment]
Fix what ike said

**Pull request merged**
