### PR TITLE
Overlay lighting

### PR DESCRIPTION
**Pull request by Dejaku51**
## About The Pull Request
Adds Overlay lighting
Ported from downstream of bee which i was working on before https://github.com/aq33/tgstation/pull/551
and TG original PR https://github.com/tgstation/tgstation/pull/52413

image

## Changelog
:cl: Dejaku51, jack-pie, Rohesie
add: Smooth movable lighting system implemented. Projectiles, sparks, thrown flashlights or moving mobs with lights should be much smoother and less laggy.
balance: Light sources no longer stack in range, though they still do in intensity.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
You should credit the people who's work you're porting, and the people they ported the work from.

**Comment by Dejaku51** [comment]
oops forgot

**Comment by Dejaku51** [comment]
done

**Comment by Ivniinvi** [comment]
Add the credits to the changelog

**Comment by Megaddd** [comment]
image
image
image



Lights look weird on sec cams. Can see dorms through walls on MetaStation too.

**Comment by Dejaku51** [comment]
Oh, I'll fix it!

**Comment by imsynthex** [comment]
ethereals' glow is a bit too dark

**Comment by Kapu1178** [comment]
m'lord i desire an update, for my server weeps

**Comment by ike709** [comment]
Lighting is one of the top server killers so I'm willing to merge this even with minor issues as long as it works overall.

**Comment by ike709** [comment]
Survived testmerge, based PR

**Pull request merged**
