### PR TITLE
Lavaland Elites (Free bugfixes included!)

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request

This port took me way less time than it should have.
port of: tgstation/tgstation#46566
and: tgstation/tgstation#47769
*aaannnd*: tgstation/tgstation#46566

if I'm missing any fixes, please tell me.

This PR adds the a pulsating tumor ruin to Lavaland, and along with it a slew of new combat-based content for both novice and experienced miners. With the very minimal explanation out of the way, let's get into the thick of it:

THE PULSATING TUMOR
The pulsating tumor is an odd land deformity which spawns as a ruin on Lavaland. One is guaranteed to spawn in at round start, but it's possible more than one could spawn in. The tumor itself also has a GPS component, which is listed as 'Menacing Signal'. At first glance, the tumor doesn't appear to be much, but it's when you get into the interactions with it that the real girth of content comes to light...

BASE INTERACTION
Upon interacting with the tumor, an ominous message will be put into in chat. After about 3 seconds, the tumor will select one specially-designed mob out of a list to spawn as the tumor's "child". Said mobs are dubbed "Lavaland Elites", and are much harder to fight than common spawn on lavaland, but less lethal than megafauna.
Upon the lavaland elite spawning in, a barrier will be formed around the tumor, similar to the Hierophant's. This barrier only affects the player who interacted with the tumor (henceforth dubbed the activator) and the lavaland elite, letting anything go through it but specifically those two. Should either manage to teleport outside of the arena, they will be teleported back on top of the tumor after at most 10 seconds. From here, the player and the lavaland elite must fight to the death, where whoever loses determining what happens next.

ACTIVATOR WINS
Should the activator win the fight, the barrier surrounding the tumor will vanish and the tumor will make a noise identical to the tendrils and drop a necropolis chest. The tumor then vanishes, and is completely gone from the game. The corpse of the elite remains and depending from mob to mob, can be butchered to achieve whatever results. From this point, all interaction is basically over.

ELITE WINS
Should the lavaland elite win, it is healed to full, and the barrier then goes down. The lavaland elite can roam freely where ever it pleases, and can also be killed during this time. Should this occur, the tumor will vanish as it would have should the activator won, but no loot will be dropped. The tumor also becomes interactable once more during this time, and after a brief warning and time delay, will re-summon the elite back to the tumor, heal it fully, and put up the barrier, basically going right back to as if it were just activated. The same rules apply to this fight as the first, with it being a deathmatch between activator and elite and the same results are achieved when either side wins.

So far this is pretty basic, a ruin which lets you summon middle-ground mob between normal and mega fauna for some basic loot. But, this is not the only interaction the glowing tumor has available to it.

BOOSTING THE PULSATING TUMOR
Should a stabilized legion core be used on the tumor before first activation, it will be dropped into the tumor, boosting it's power. This makes it stronger, empowering the mob which comes out... with sentience.

BOOSTED ELITE
Upon interacting with a boosted tumor, all ghosts with the sentience role will be polled on if they'd like to be a lavaland elite. If no ghost agrees, the tumor will not activate, and the player will be allowed to try again some other time. Should ghosts say yes, they'll be added to a pool of possible candidates and one will be chosen randomly. Upon being chosen, the ghost will receive a sound notification and prompt on what is about to occur, which lasts about 10 seconds. Once this happens, the tumor will put out a unique message, warning the activator that an elite is about to spawn. After the 10 seconds of grace, the mob is spawned in with the ghost in control of it, and the fight advances normally.

DIFFERENCES FROM REGULAR TUMOR
The lavaland elite, outside of being player-controlled, is 100% the same. Its only the outcomes from this point which change, which are mentioned below:

ACTIVATOR WINS BOOSTED
Should the activator win against a boosted elite, the tumor will give a necropolis chest like before, but also has a 50%-50% chance of spawning a unique loot drop based on the elite fought or a tumor shard. The tumor shard functions very similarly to a lazarus injector, only that it only works on sentient lavaland elites. Using it on a corpse with a ghost in it revives the elite, makes it loyal to the user and cuts its health in half. It also adds an extra part to their description to differentiate them from regular elites, and lets them be revived via lazarus injector. After this point, all interactions are over.

ELITE WINS BOOSTED
Should the elite win boosted, the same as a regular elite win occurs, except the elite is notified that it is free but can be called back if someone interacts with the tumor. Along with this, it's health is cut in half, but it can heal by standing on the tumor. Note, this is the only way it can heal, kills and such do it give any health.

SOME THINGS ABOUT ELITES

    Cannot be made sentient or lazurus'd, due to having SENTIENCE_BOSS
    Only deal 5 structure damage, and cannot break walls or rwalls. They can, however, break mineral walls in one hit. This is to prevent sentient elites from taking apart the mining station, which would be very un-fun.
    Will attack targets until they are dead
    Are only a part of the boss faction, meaning they are on the same team as megafauna, not not regular fauna.
    Cannot attack those on their own faction (which includes themselves)
    Can select their attacks with buttons on the top left of the screen
    Cannot talk (unless specifically enabled to, will likely use for the colossus-based elite)
    Can see in the dark

CURRENT ELITES
Goliath Broodmother:

    800 HP
    30 Melee
    2 Speed
    When below 50% health, random tentacles will begin spawning near the broodmother. At 25% health, this effect is doubled. Melee attacks have 30 armor piercing.
    ATTACKS -
    Tentacle Patch: Summon a large patch of tentacles by the target (combination of 3 x 3 and 5 x 5 plus-shape.) These tentacles have less stun time than a normal goliath's, but deal more damage.
    Children Spawn: Summon 2 of its children to its location. These are baby goliaths, with the following stats:
        20 Health
        5 Damage
        2 Speed
        When killed, explodes in a fiery explosion
        At range, will apply a tentacle to the square under their target. Has a cooldown of 4 seconds.
        The broodmother at max can have 8 of them out at a time.
        Rage: Increases in speed for 6.5 seconds, with a cooldown of 7 seconds.
        Call Children: All active children will be summoned around the broodmother upon use.

Unique Loot: Broodmother Tongue
Functions as a crusher trophy. Gives a 10% chance to summon a patch of tentacles at the target on mark detonation.

Pandora:

    800 HP
    15 Melee
    4 Speed
    All attacks have a cooldown of 1 second sans Blast Line, and is decreased by 25% at 50% HP and 25% HP. Blast line has half the normal cooldown of other attacks.
    ATTACKS -
    Blast Line: Fires a line of Hierophant blasts in either a cardinal or diagonal direction.
    Magic Box: Surrounds the target with Hierophant blasts, leaving a 3x3 square in the center. Punishes mindless running away from Pandora, along with fitting the box theme.
    Teleport: Almost identical to Hierophant's teleport, deals damage in a 3x3 at the initial location and at the end location.
    AOE Blast: Does a 5x5 blast, stretching out from the center. Unlike Hierophant, this attack is one done at a range.

Unique Loot: Hope
Functions as a medal. Gives a positive moodlet when pinned on your uniform.

Legionnaire:

    800 HP
    30 Melee
    1 Speed
    Legionnaire's skull initially does 10 damage, but ramps up to 20 at 50%, and 30 at 25%.
    ATTACKS:
    Legionnaire Charge - Charges forward 4 tiles, throwing anyone in its path forward and dealing a whopping 50 damage. Attack is telegraphed for half a second, and legionnaire can slightly adjust the travel path when charging. Don't stand too close!
    Skull Detach - The legionnaire's skull detaches, fighting as its own entity. Will chase targets and deal 10 damage to them, ramping up as the legionnaire's health goes down.
    Bone Bonfire - If no bone bonfire is currently active, places a bonfire on legionnaire's current tile. When used again, the legionnaire will swap places with the bonfire. The bonfire can be destroyed and walked over, and using the ability when standing on the active bonfire destroys it. If a flammable creature walks over the bonfire, they will be set on fire.
    Smoke Spew - Spawns a smoke cloud around Legionnaire. If its head is currently detached, the cloud will be spawned at the head's location instead.

Unique Loot: Legionnaire Spine
Functions as a trophy for the kinetic crusher. Gives the crusher a 20% chance to summon a legion head to attack the target for 10 seconds on mark detonation.

Herald:

    800 HP
    20 Melee
    4 Speed
    Once below 50% health, herald's tri-shot and circular shot will fire twice when used.
    Herald's deathbolts don't break structures immediately and only do 15 damage, with less armor penetration (still pretty high)
    ATTACKS:
    Tri-shot - Fires three bolts at the target position.
    Spread-shot - Herald raises it's arms(?) and shakes before firing a deathbolt in every cardinal and diagonal direction at once. Has longer delay to fire again than tri-bolt.
    Tele-shot - Fires a golden bolt which does no damage. Once it strikes something, the Herald will be teleported to where it hit.
    Mirror - Summons a mirror which reflects yourself. The mirror will replicate all your attacks, firing at the same position as you do. The only effect it doesn't duplicate is doubling it's attack when your health is low. Tele-bolt will teleport the mirror as it teleports the herald.

Unique Loot: Cloak of the Prophet
A cloak based on the appearance of Herald. When attacked, has a 10% chance to do a spread of herald deathbolts around the wearer.

Other elites are in development, but I wanted to put this PR before I finished in case major changes to the base code needed to be changed. As of now, this is 100% merge-friendly, functions as described above, the only thing being the only mobs which can spawn are the mobs above. The planned elites are:

    Elite watcher
    Elite goldgrub
    Bubbles-based Elite
    Ash Drake-based Elite
    ???

## Why It's Good For The Game
This PR hits several good notes in terms of content the game could use. For one, its new mining content, two, it's something accessible to both novice and experienced miners, and three, adds a series of interesting new ghost roles. The content is also miner-choice, as nothing will happen should they not activate the tumor. It also means it's not a free murderbone ghost role either; the miner needs to procure a stabilized core and willingly put it into the crevice for it to allow a ghost to take over. They're also less prone to griefing, as they lack the ability to smash things, lack the ability to heal outside of their tumor(which they must remember its location), and cannot operate consoles to leave Lavaland by themselves. For miners, the mobs will also double as good mining partners, as their attacks also double as mining tools with various uses. Finally, it functions as robustness practice for miners who don't want to get gibbed for losing a fight, letting them use crevices to train to take on megafauna.

## Changelog
:cl: Indie-ana Jones & Meyhazah (Ported by Mark Suckerberg)
add: New lavaland ruin: Pulsating Tumor
add: New lavaland enemies: Lavaland Elites
add: New Lavaland Elite: Goliath Broodmother
add: New Lavaland Elite: Pandora
add: New Lavaland Elite: Legionnaire
add: New Lavaland Elite: Herald
imageadd: Added lavaland elite sprites and pulsating tumor sprites
imageadd: New lavaland loot sprites
imageadd: Elite ability sprites
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
@SomeAngryMiner lookin at you

**Comment by Moccha-Bee** [comment]
very based extremely redpilled +clout

**Comment by Cenrus** [comment]
https://github.com/tgstation/tgstation/pull/48039

**Comment by Cenrus** [comment]
https://github.com/tgstation/tgstation/pull/48139

**Comment by Cenrus** [comment]
https://github.com/tgstation/tgstation/pull/48139

**Comment by eLeCtrOssSnake** [comment]
Nicely done!

**Comment by TWaiK31** [comment]
MINER GANG
MINER GANG
SPEEDMERGE NOW

**Comment by ike709** [comment]
Did you get both of the PRs that cenrus linked?

**Comment by MarkSuckerberg** [comment]
Yes, both merged.

**Comment by Cenrus** [comment]
Neat.
Merge now

**Comment by ike709** [comment]
what could go wrong

**Pull request merged**
