### PR TITLE
Larry

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
Someone pointed out that Roomba was a trademarked name, so, following Intense™ Deliberation™ and Careful™ Consultation™,  we have decided on a new name:

# Larry

## Why It's Good For The Game
Tradestrikes bad.

## Changelog
:cl:
tweak: Due to trademark reasons, the Roomba has been renamed
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
obraz

**Review by Archanial — APPROVED** [review]

**Comment by TeomanTheGreat** [comment]
Larry 👍

**Comment by rkvothe14** [comment]
Larry

**Comment by DatBoiTim** [comment]
Oops

**Review by ike709 — APPROVED** [review]
larry

**Pull request merged**
