### PR TITLE
Adds IPC's [READY]

### PR DESCRIPTION
**Pull request by Toxici11i**
## About The Pull Request
Adds a new species - ICP's (robo bitches)

## Why It's Good For The Game

A new race! 1.2x brute modifier, 1.6x burn and 1.75 fire modifier, but can be repaired easily. They are radiation immune, and can easily have their limbs reattached - but as a result are weaker to dismemberment and dying

## Changelog
:cl:
add: Adds IPCS
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
I don't think this is what lago had in mind

**Comment by Toxici11i** [comment]
im still fixing the tv heads - but he agreed he wanted them to be better than bay/cita ipcs and more balanced aaa

**Comment by Lagomorphica** [comment]
i trust toxics decisions qwerty, as long as they have TV heads

you could make them die from 1 point of damage and i'd still play them for TV head aesthetic

**Comment by Toxici11i** [comment]
closing this PR because cleaning up deprecated code is a sonofabitch and this wouldve broken stuff

**Pull request closed without merging**
