### PR TITLE
Ports typing indicators from tgstation as a pref

### PR DESCRIPTION
**Pull request by optimumtact**
see title
also mutes or silent people don't have typing indicators unless it's an emote
Why It's Good For The Game

should be a pref tbh
Changelog

:cl: oranges
add: added a preference for typing indicators, in the preferences panel
fix: mutes and mimes people can't have say typing indicators
:/cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Good pr

**Comment by ZeWaka** [comment]
bad feature, don't let oranges port bad features to my beloved beestation

some regulars of Sage and I would definitely consider going to another server if oranges spreads his nerf agenda here

**Comment by Kapu1178** [comment]
your typing indicator sucks and has a delay. kuberoot's system is functionally better. also, having it as a pref defeats the purpose.

**Comment by ZeWaka** [comment]
> your typing indicator sucks and has a delay. kuberoot's system is functionally better.

who is kuberoot, is this another dumb tg admin

**Comment by Kapu1178** [comment]
> 
> 
> > your typing indicator sucks and has a delay. kuberoot's system is functionally better.
> 
> who is kuberoot, is this another dumb tg admin

an admin on a fork of a fork of tg. so, yes

**Comment by ZeWaka** [comment]
> > > your typing indicator sucks and has a delay. kuberoot's system is functionally better.
> > 
> > 
> > who is kuberoot, is this another dumb tg admin
> 
> an admin on a fork of a fork of tg. so, yes

hmm i think that's better than oranges because every step away from tg is a good step imo

**Comment by optimumtact** [comment]
> your typing indicator sucks and has a delay. kuberoot's system is functionally better. also, having it as a pref defeats the purpose.

I don't remember asking you a goddamn thing? this PR is for beestatio ncontributors to commetn on only, so stay the frick out.

**Comment by optimumtact** [comment]
> bad feature, don't let oranges port bad features to my beloved beestation
> 
> some regulars of Sage and I would definitely consider going to another server if oranges spreads his nerf agenda here

Ugh shutup zewaka, you play a felinid main on sage anyway

**Comment by Kapu1178** [comment]
> 
> 
> > your typing indicator sucks and has a delay. kuberoot's system is functionally better. also, having it as a pref defeats the purpose.
> 
> I don't remember asking you a goddamn thing? this PR is for beestatio ncontributors to commetn on only, so stay the frick out.

image
orange man bad

**Comment by williamcll** [comment]
Will this stop people who wait for people to start typing and then attack them, thus violating metagaming rules?

**Comment by MCterra10** [comment]
😂

**Comment by MCterra10** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/5419

**Comment by Sinestia** [comment]
This was already attempted and thrown out because people are deadset on it not being a pref

Bee will always violate the privacy of the shy and insecure.

**Comment by Archanial** [comment]
Typing indicator sucks

Just revert it

**Comment by KubeRoot** [comment]
Hello yes it is me kuberoot I have made BYOND clientside and there is no more delay when using chat with typing indcators yes thank you goodbye

**Comment by francinum** [comment]
The only thing worth caring about in this PR are the additional state safety checks.

**Comment by KubeRoot** [comment]
> The only thing worth caring about in this PR are the additional state safety checks.

On a serious note, in my PR I added an argument to `.start_typing` and `.stop_typing` specifying either `"say"` or `"me"` to make that kinda thing easier to add in later

**Pull request closed without merging**
