### PR TITLE
[PORT] Even More TGUI-Next, Browser passthrough

### LINKED ISSUE #783: Various problems with the ORM
By various I mean two.
1: The ORM fails to do anything when it is requested to create (Some? Haven't tested all) alloys.
2: The ORM fails to transfer raw materials to other machines when they request them. 

## Reproduction:
Attempt to create alloys at any ORM. Attempt to draw materials at any linked machine.
This appears to be connected to a recent ORM update that changed the interface and added some quality-of-life changes, but I for the life of me cannot find it.

### PR DESCRIPTION
**Pull request by Cenrus**
https://github.com/BeeStation/BeeStation-Hornet/projects/2#card-29398132
https://github.com/BeeStation/BeeStation-Hornet/projects/2#card-29398140
https://github.com/BeeStation/BeeStation-Hornet/projects/2#card-29398260

Will close https://github.com/BeeStation/BeeStation-Hornet/issues/783

:cl: actioninja and stylemistake
add: laptop vendor TGUI-Next
fix: Personal Crafting UI will no longer reset its state when crafing an item.
fix: Improved table layout of Smart Fridge and Crew Console.
fix: Fix ORM not smelting alloys.
fix: Fix Computer Fabricator.
refactor: Tgui CSS got a massive rework.
add: Improved tgui error reporting.
add: You can now control your character and use hotkeys while tgui windows are open.
add: New Rapid Pipe Dispenser interface.
add: New NtOS theme.
add: New NtOS Menu interface.
add: New Power Monitor interface.
add: New Supermatter Monitor interface.
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
I ran install_dependancies and build_assets, tell me if I missed a step when rebuilding.

**Comment by ike709** [comment]
Clearly not tested locally. Also, you built old tgui. You need to build tgui-next.

**Comment by ike709** [comment]
There's a few issues on this repo that this PR will fix but I'm too tired to find and link them.

**Comment by Cenrus** [comment]
Sorry about that, I'll test things like this in the future.

**Comment by ike709** [comment]
Cenrus claims this was tested locally.

**Pull request merged**
