### PR TITLE
THE GREAT DEMODULARIZATION (in the form of song and dance)

### PR DESCRIPTION
**Pull request by qwertyquerty**
demodding beestation slowly, please review

### CODE REVIEW

**Comment by CthulhuOnIce** [comment]
doesn't even rhyme

**Comment by qwertyquerty** [comment]
Yes it does you're just too smoothbrained to find the rhymes

**Comment by qwertyquerty** [comment]
Actually nevermind that, every commit is a new song

**Comment by qwertyquerty** [comment]
There was a keychange on the word defines

**Comment by CthulhuOnIce** [comment]
Remove the qwerty folder

**Comment by qwertyquerty** [comment]
No

**Comment by qwertyquerty** [comment]
It's there to organize work done by me

**Comment by qwertyquerty** [comment]
Kev imagine how much more simple it will be to develop shart now

**Comment by qwertyquerty** [comment]
now KICK, PUNCH

**Comment by qwertyquerty** [comment]
CHOP AND BLOCK

**Comment by qwertyquerty** [comment]
[https://www.youtube.com/watch?v=Kw-_Ew5bVxs](https://www.youtube.com/watch?v=Kw-_Ew5bVxs)

I would like to thank my family, especially my sister

I would like to thank all my teachers in elementary school, middle school, and high school, especially that one cool janitor

Next I want to thank all the members of beestation (except kev) for helping me through these trying times

This has been a historical moment everyone.

**Comment by CthulhuOnIce** [comment]
I'll review the code when the check passes, don't merge yet

**Comment by qwertyquerty** [comment]
Have fun reviewing all 136 files (what you should really do is bugtest all bee additions)

**Comment by qwertyquerty** [comment]
marge when

**Comment by CthulhuOnIce** [comment]
> Beestation is just tg
> 136 changed files
> pepemsirk

**Review by CthulhuOnIce — APPROVED** [review]
This is cool as long as the dme is organized.

**Pull request merged**
