### PR TITLE
Adds lethal autoturrets to nuke operative uplink

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
Adds semi-automatic rounds (assault pod) and heavy laser autoturrets to nuke operative uplink. Mainly added for custom shuttles in the upcoming operative event but also would be useful weapons in many nuke operative rounds. May add semi-auto turrets to traitor uplink at a later date for traitors building their own shuttles. 

## Why It's Good For The Game
Custom shuttles are easy to attack without robust autoturrets defending it. Normal nuke operatives can also use these for suppressing fire or making parts of the station more hazardous in the same way they might otherwise use explosives, flamethrowers or assault cyborgs. 

## Changelog
:cl:
add: Semi-auto rounds and heavy laser autoturrets added to nuke operative uplink for 8 and 12 TC respectively.
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
considering the fact that this shit is deployable anywhere, please ix-nay the fucking penetrator turrets

**Comment by PowerfulBacon** [comment]
Won't they look really weird though, since they are designed to go on corners?

**Comment by PowerfulBacon** [comment]
Also deploy penetrator round near bridge and it will fucking kill everyone

**Comment by VictorVow** [comment]
They rotate to face the target and start pointed south. 

Hmm I'll see what I can do about making a nerfed subtype. But if the original was available, how much TC should it be?

**Comment by WhyIsCaeciliusTaken** [comment]
Remove the pen turret, one at departures will just kill everyone.

**Comment by Isy232** [comment]
Penetrator turrets were originally designed to be EXTREMELY OP.


I remember a while ago on /tg/ when nuke ops would declare war, a bunch of people would gear up with space suits and jetpacks and attack the operatives in space.

The station jetpacks (especially captains) can hold more gas and go faster, since most operatives do not want to sacrifice a belt slot for a jetpack harness. Its also much easier to loose your back slot as a station person as you have more people you can get help from, while operatives often find themselves alone.

Because of this the operatives would be outmatched in space. Someone with a back jetpack can pretty much effortlessly harass an operative and as long as they dont space lag or make a mistake they can always fly away literally faster than the bullets travel.

I think jetpacks built into hardsuits should have the same speed as back ones and that would have been a good fix instead of surrounding the shuttle with extremely strong turrets.


Penetrator turrets are needed though, without them you can push a locker or crate and use it as a shield to approach a turret and pretty much nullify it.

Penetrator turrets should have their damage nuked and turret health increased, so they are a big pain to kill but do not instantly kill you.

Also, don't make them buy able. Because they penetrate things, even if they are nerfed, shitty things like surrounding them with huge amounts of crates and other shitty tricks will likely be found to abuse them.

**Comment by PowerfulBacon** [comment]
Penetrator turrets are good because if you get to the ship, you have instantly won cause you can steal the nuke. They can go through walls and should not be in the uplink.

**Comment by Isy232** [comment]
Pretty sure the nuke can only be moved once it has the disk in, which if you bring the nuke to the operatives ship your risking a lot. The issue is part the ship next to security or departures and watch the turrets kill anyone by a window.

**Comment by VictorVow** [comment]
Removed penetrator turret, increased price on others to 8 and 12.

**Pull request merged**
