### PR TITLE
Fixes phobia fainting

### PR DESCRIPTION
**Pull request by Shiraizawa**
## About The Pull Request

Buffed fainting from phobias by fixing instantly fainting right after waking up. After fainting, you'll be bumped back to an Uneasy level instead of leaving you on Fainting.
Decreased the snowball effect from stress build-up by half as well. Necessary as being looped back to a lower level gives you more stress as you build up to a fainting level again. This leads to faster heartattack however, since each fainting adds +3 to stress .

## Why It's Good For The Game

Currently having a phobia and fainting once puts you into a fainting loop with only a very little time to get away or say something after waking up. This should make you be able to get away or at least ask someone to pull you away from your fears.

## Testing Photographs and Procedure

<details>

<summary>Screenshots&Videos</summary>

https://www.youtube.com/watch?v=Xvwl8x1hUpM
</details>

## Changelog
:cl:
balance: Decreased the snowball effect of fear build-up from (stress x10)% to (stress x5)%. Your stress levels build up faster with each fainting now, which leads to a higher chance of a heartattack
fix: You wont faint immediately after waking up from a faint caused by a phobia
fix: The message for fainting from a phobia will actually be visible for the one fainting now
spellcheck: fixed a capitalization when fainting from a phobia

/:cl:

### CODE REVIEW

**Comment by Shiraizawa** [comment]
This isnt a nerf, its a buff

**Review by Tsar-Salat — COMMENTED** [review]
Bandaid pr for a system that needs a complete overhaul. Makes sense to have until we have that rework.

**Review by itsmeow — APPROVED** [review]
yea looks good
I wouldn't call this a buff it's just making it less stupid

**Comment by Shiraizawa** [comment]
oh shoot, lets not do that again, now i know how PRs work at least

**Comment by Shiraizawa** [comment]
Closing because I tried to push my main and worried if I make another PR the changes will show up on this one

**Pull request closed without merging**
