### PR TITLE
blood red resprite

### PR DESCRIPTION
**Pull request by 1glitchycent**
get stupid

## About The Pull Request
Resprites the blood-red hardsuit, while still  maintaining the iconic look
Pictures
image

image

## Why It's Good For The Game
better sprite quality, also fuck s*ul

## Changelog
:cl:
add: new bloodred sprites
del: old bloodred sprites
/:cl:

### CODE REVIEW

**Comment by bloons3** [comment]
Embed the images in the PR

**Comment by 1glitchycent** [comment]
> Embed the images in the PR

done

**Comment by TheRealScarHomie** [comment]
no soul 👎🏿

**Comment by Naevii** [comment]
There is still something about the helmet that makes it look weird from afar. 
Did you try maybe switching green pixels with lighter on the outside and darker at the center ? 

Also can you show us version with lights on ? Or does this suit comes with only one light mode ?

**Comment by 1glitchycent** [comment]
> There is still something about the helmet that makes it look weird from afar.
> Did you try maybe switching green pixels with lighter on the outside and darker at the center ?
> 
> Also can you show us version with lights on ? Or does this suit comes with only one light mode ?

eyes have been fixed. 
image
Regarding lights, I can't find the lights-off version in the code, so I'm assuming it doesn't exist, and personally, I think it looks better with the light not showing on the sprite. If you can point me to the lights-off version, or just think a lights-on version is better, I'll be happy to fix it.

**Comment by ivanmixo** [comment]
Combat mode helmet?

**Comment by ItsTisme** [comment]
Hardsuit has 2 modes, combat and EVA. In combat the face is actuely visible(meant to show the syndie gasmask underneath) which makes the iconic red visor. light toggles with combat/EVA mode

**Comment by Effemu** [comment]
it looks fat

**Comment by 1glitchycent** [comment]
> Hardsuit has 2 modes, combat and EVA. In combat the face is actuely visible(meant to show the syndie gasmask underneath) which makes the iconic red visor. light toggles with combat/EVA mode

The current screenshots are of EVA mode. If you wanna see combat mode, check icon diffs. I'll post a screenshot of combat mode with the syndie mask later today.

**Comment by 1glitchycent** [comment]
> it looks fat

I'm guessing your referring to the chest rig part on the stomach, I'll see how a "flat" version of the stomach armor with no details looks later today.

**Comment by PowerfulBacon** [comment]
Lights need to glow at least, +1 points if you put the glow <s>on</s> above the lighting plane as an overlay

**Comment by PowerfulBacon** [comment]
> 
> 
> > There is still something about the helmet that makes it look weird from afar.
> > Did you try maybe switching green pixels with lighter on the outside and darker at the center ?
> > Also can you show us version with lights on ? Or does this suit comes with only one light mode ?
> 
> eyes have been fixed.
> image
> Regarding lights, I can't find the lights-off version in the code, so I'm assuming it doesn't exist, and personally, I think it looks better with the light not showing on the sprite. If you can point me to the lights-off version, or just think a lights-on version is better, I'll be happy to fix it.

there is no lights off version of the syndie hardsuit, only the elite one uses it.

**Comment by ghost** [comment]
This looks like a pillow-halloween-costume version of the current hardsuit. The current one definitely has soul and needs a replacement, however it also looks like it's made of an actually hard material.

**Comment by 1glitchycent** [comment]
image

updated version of the eyes, zoomed out to look close to in-game

**Comment by 1glitchycent** [comment]
here's how the new sprite looks on station tiles, I made it a bit darker so it should (hopefully) look better in-game
image

**Comment by PowerfulBacon** [comment]
that eye glow looks bad

**Comment by Naevii** [comment]
> here's how the new sprite looks on station tiles, I made it a bit darker so it should (hopefully) look better in-game
> image

This suit is way too dark.
One of the great and memorable things about this suit is how it stands out, and screams "i am the danger". 
This suit also stands out for a reason, its supposed to be VERY easily notice-able. 

As Bacon said above the lighning on the helmet looks a bit off.

And i think i would prefer different chest plating (this one look a bit pillow like) but it might be personal preference. 

The suit is improvement of sprite quality of what we have in game but i am unsure if its better enough to exchange existing very memorable, sprite.

**Comment by 1glitchycent** [comment]
> > here's how the new sprite looks on station tiles, I made it a bit darker so it should (hopefully) look better in-game
> > image
> 
> This suit is way too dark.
> One of the great and memorable things about this suit is how it stands out, and screams "i am the danger".
> This suit also stands out for a reason, its supposed to be VERY easily notice-able.
> 
> As Bacon said above the lighning on the helmet looks a bit off.
> 
> And i think i would prefer different chest plating (this one look a bit pillow like) but it might be personal preference.
> 
> The suit is improvement of sprite quality of what we have in game but i am unsure if its better enough to exchange existing very memorable, sprite.

1: I may be biased, but this sounds like a rather arbitrary critique, the sprite is still instantly recognizable as a blood red, with all the clear identifiers that would designate it as such. No other space suit besides the blood-red that's commonly available is fully red, or has the 4 eyes, which are the identifying factors. Also, if it were brighter, it wouldn't fit with tiles, instead of standing out it would just look ugly and and out of place.

2: I totally agree, I'm working on getting a version with better lighting done.

3: I'll run by a few different versions on discord

4: It is a memorable sprite, because it's unique helmet design and color scheme, both of which I am maintaining, while also improving.

**Comment by Naevii** [comment]
> > > here's how the new sprite looks on station tiles, I made it a bit darker so it should (hopefully) look better in-game
> > > image
> > 
> > 
> > This suit is way too dark.
> > One of the great and memorable things about this suit is how it stands out, and screams "i am the danger".
> > This suit also stands out for a reason, its supposed to be VERY easily notice-able.
> > As Bacon said above the lighning on the helmet looks a bit off.
> > And i think i would prefer different chest plating (this one look a bit pillow like) but it might be personal preference.
> > The suit is improvement of sprite quality of what we have in game but i am unsure if its better enough to exchange existing very memorable, sprite.
> 
> 1: I may be biased, but this sounds like a rather arbitrary critique, the sprite is still instantly recognizable as a blood red, with all the clear identifiers that would designate it as such. No other space suit besides the blood-red that's commonly available is fully red, or has the 4 eyes, which are the identifying factors. Also, if it were brighter, it wouldn't fit with tiles, instead of standing out it would just look ugly and and out of place.
> 
> 2: I totally agree, I'm working on getting a version with better lighting done.
> 
> 3: I'll run by a few different versions on discord
> 
> 4: It is a memorable sprite, because it's unique helmet design and color scheme, both of which I am maintaining, while also improving.

It's meant to stand out. It's meant to not "fit the tiles". Because its supposed to stand out as hell, so the second you see this super bright red you know what you are dealing with.

Of course helmet is a huge recognisable factor, but I think tonning down this bright red to maroon is way too far. 

Also, You can't possibly make a sprite that "fits the tiles" because there is too many floor/tiles designs to be able to fit all of them. 

I Personally think blood red suit should stay blood red with bright red instead of maroon.  This suit simply is too dark and melts too much.

**Comment by ghost** [comment]
The original sprite is very memorable and a classic.... Why change it? it's already good.

**Comment by TheRealScarHomie** [comment]
> The original sprite is a classic though..... now it's just shit

no soul 😭

**Comment by ghost** [comment]
> > The original sprite is a classic though..... now it's just shit
> 
> no soul 😭

I'm just stating my opinions man. there is no reason to change the classic sprite. the new one looks like a cartoon of SS13

**Comment by 1glitchycent** [comment]
> The original sprite is very memorable and a classic.... Why change it? it's already good.

it's memorable and classic, but it's also certainly not good. The design is original and striking, but the sprite needs improvement, which is the purpose of this PR.

**Comment by 1glitchycent** [comment]
I'm closing this PR. Regardless of the quality of the sprite, this won't get merged as people will pick a bad sprite over a blatant improvement.

**Comment by OceanFish1** [comment]
> I'm closing this PR. Regardless of the quality of the sprite, this won't get merged as people will pick a bad sprite over a blatant improvement.

:trollface:

**Pull request closed without merging**
