### PR TITLE
[PORT] Changes how weather sends sound to players, reduces sound loop overtime and Weather ztraits

### PR DESCRIPTION
**Pull request by Penwin0**
## About The Pull Request
ports https://github.com/tgstation/tgstation/pull/59284 by LemonInTheDark
ports the weather traits portion of https://github.com/tgstation/tgstation/pull/51090 by Whoneedspace
Ports a PR from the project.

## Why It's Good For The Game
Opens up functionality for playing different looping sounds based on the area you're in.
Removes the overtime caused by looping sounds.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

You'll have to trust me but these gentlemen can hear sounds properly, they start and end when they should.
Screenshot_1239
Screenshot_1238

</details>

## Changelog
:cl: LemonInTheDark, Whoneedspace
code: Weather now handled by ZTRAITS
code: Reduces sound loop overtime
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Sound loop optimisation, nice

**Comment by PowerfulBacon** [comment]
If its based on z-level, then I assume it would

**Comment by itsmeow** [comment]
I'm not sure, but if a storm was happening on lavaland, you could hear it in any pod even if it wasn't on lavaland

**Comment by Penwin0** [comment]
> I'm not sure, but if a storm was happening on lavaland, you could hear it in any pod even if it wasn't on lavaland

Though I haven't checked this specifically this should no longer be an issue with how it's handled now

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
