### PR TITLE
Increases Projectile Speed

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

All that the Title says, increases the speed of all Projectiles.

## Why It's Good For The Game

This is to balance out the increased movespeed, and people don't want it decreased so here's the other option, Hollywood-Style outrunning bullets isn't good.

## Changelog
:cl:
tweak: All projectiles now move 1.25 times as fast.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
weird, what are those commits doing here?

**Comment by zeskorion** [comment]
Iunno chier, this doesnt solve the issue completely, and nerfs already shit melee combat. Perhaps a melee buff to compensate dor the speed as well

Either way, due to server speed differences, i dont think this is a good idea

**Comment by PowerfulBacon** [comment]
PR says it's to balance out movement speed, but movement speed hasn't changed in a long time and nobody has complained about this before or seen it as an issue.

**Comment by ghost** [comment]
> Iunno chier, this doesnt solve the issue completely, and nerfs already shit melee combat. Perhaps a melee buff to compensate dor the speed as well
> 
> Either way, due to server speed differences, i dont think this is a good idea

the issue is people being fast enough to nearly outrun projectiles and just dodge them due to how fast people are.

**Comment by ghost** [comment]
> PR says it's to balance out movement speed, but movement speed hasn't changed in a long time and nobody has complained about this before or seen it as an issue.

just because it's been like this forever doesn't mean it's good.

**Comment by eeSPee** [comment]
Maybe instead of x2.0, try x1.25 instead?

**Comment by ghost** [comment]
> Maybe instead of x2.0, try x1.25 instead?

done, and honestly yeah its better.

**Comment by TotallyNotChief** [comment]
I still think it'd be better at x2 honestly

**Comment by zeskorion** [comment]
have you tried 1.5?

**Comment by RafRoq** [comment]
Can you make a gif comparing 1.25x 1.5x and 2x ? I like projectile speed being increased it's been always to easy to dodge bullets on ss13

**Comment by RafRoq** [comment]
Also what about colossus ?

**Comment by PowerfulBacon** [comment]
I think it should be a config option so it can scale better across the servers with different movespeeds. Anything higher would be too high on MRP due to the decreased speed, although on LRP you can outrun bullets due to the speed.

**Comment by zeskorion** [comment]
> I think it should be a config option so it can scale better across the servers with different movespeeds. Anything higher would be too high on MRP due to the decreased speed, although on LRP you can outrun bullets due to the speed.

or just use config run multiplier

**Comment by ivanmixo** [comment]
Outrunning bullets/disabler lasers is really damn stupid, gotta admit.

Also zesko what the fuck? 

> Iunno chier, this doesnt solve the issue completely, and nerfs already shit melee combat. Perhaps a melee buff to compensate dor the speed as well

Why should a GUN and melee weapon be comparable? You should obviously have an advantage if you have a gun compared to someone who doesn't, considering how hard guns are to come by if you don't powergame.

**Comment by Isy232** [comment]
I HEAVILY agree with this ALMOST.

@BeloneX 
Don't speed up disabler shots!!!!!!!!

Speed up everything else.

Even then, being able to dodge bullets like the matrix is a joke and it makes running away a super effective strategy for combat because inertia does not exist and you have much less time to dodge if your the person chasing. 

If you've ever treid to fight with guns in a large open area, its becomes quite obvious how this is an issue.

You have to aim for places where you think your opponent may move to, instead of aiming at them. This won't remove that fully, but just make it less stupid.

**Comment by RafRoq** [comment]
Don't listen to the guy above, keep disablers in the buff list, thank you

**Review by zeskorion — APPROVED** [review]

**Comment by zeskorion** [comment]
this wont cause any unprecedented odd edge cases i'm *sure*

**Pull request merged**
