### PR TITLE
Departmental Skirts : Service/Civilian

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Adds skirts for service/civilian jobs. This includes: Bartender, Cook, Botanist, Curator, Chaplain, Lawyer and Assistant. Also the HoP skirt since they are the head of the service department.

The assistant skirts are just regular skirts with color variation like the jumpsuits.

image

## Why It's Good For The Game

More uniform variation. 

## Changelog
:cl:
add: Civilian Skirts!
add: base for skirts
imageadd: sprites for the civilian skirts
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
I wonder how many times you need to make same pr to get gitbanned 🤔

**Comment by ivanmixo** [comment]
> I wonder how many times you need to make same pr to get gitbanned 🤔

This is the second PR. The reason for it's existence is because I was told by a maintainer to atomize the original PR, so here we are. The original PR was not closed by a maintainer, but myself.

**Comment by WhyIsCaeciliusTaken** [comment]
Ditch botanist one because of handling stinging plants.

**Comment by Effemu** [comment]
>>uses catgirl as a model to show us the skirts

**Comment by Isy232** [comment]
> > I wonder how many times you need to make same pr to get gitbanned 🤔
> 
> This is the second PR. The reason for it's existence is because I was told by a maintainer to atomize the original PR, so here we are. The original PR was not closed by a maintainer, but myself.

I think the middle horizontal line on the botanist and chef skirts looks really bad, can you just make the skirts 1 pure colour?

Or perhaps keep the horizontal line but also make a version without and you can swap jumpsuit styles by alt clicking it, one of these styles not having the line.

And I dont mean the one at the bottom, the one in the middle.

**Comment by ivanmixo** [comment]
> > > I wonder how many times you need to make same pr to get gitbanned 🤔
> > 
> > This is the second PR. The reason for it's existence is because I was told by a maintainer to atomize the original PR, so here we are. The original PR was not closed by a maintainer, but myself.
> 
> I think the middle horizontal line on the botanist and chef skirts looks really bad, can you just make the skirts 1 pure colour?
> 
> Or perhaps keep the horizontal line but also make a version without and you can swap jumpsuit styles by alt clicking it, one of these styles not having the line.
> 
> And I dont mean the one at the bottom, the one in the middle.

I'll adjust it later. Now that you pointed it out I can't unsee it.

**Comment by ivanmixo** [comment]
I've updated the cook's skirt. Didn't touch the botanist's one since it's basically the same design as the original botany jumpsuit, reason you don't notice it is because it's usually covered by your apron.

**Review by utilbird — DISMISSED** [review]

**Review by utilbird — APPROVED** [review]

**Pull request merged**
