### PR TITLE
Adds new random maintenance rooms

### PR DESCRIPTION
**Pull request by dog132-ss13**
## About The Pull Request

Adds 7 new random maint rooms as well as fixing the config on another one, which was preventing it from spawning.

## Why It's Good For The Game

More variety in maintenance is always a good thing as it offers new opportunities for players to explore.

## Testing Photographs and Procedure
<summary>Screenshots&Videos</summary>
<details>
Kilo Vault, which didn't work previously due to the wrong height-width configuration

image

Cornucopia
image

Free-Range Corgi Burgers
image

The Control Room
image

Library Ritual - while the rune is real, it is nonfunctional
image

The Printing Press
image

Welcome to my offish
image

</details>

## Changelog
:cl:dog132
add: Added seven new random maintenance rooms
/:cl:

### CODE REVIEW

**Comment by PestoVerde322** [comment]
The Printing Press room has some in-wall lights and a light on an airlock.
Library Ritual, while nice and have plenty of details, it's prime estate for any cultist due to the thick walls on the corners.

Other seems fine.

**Comment by dog132-ss13** [comment]
> The Printing Press room has some in-wall lights and a light on an airlock. 

The in-wall light happens to be from the map where the random room spawned. It happens quite a bit with random rooms which add walls.

**Comment by PestoVerde322** [comment]
immagine

Doublewalls bad, please nudge them toward the xeno cell.

immagine

Also random whitedecal?

**Comment by dog132-ss13** [comment]
whoops I forgot to fix the white decals after I tried to convert that area to using the new decals

**Comment by PestoVerde322** [comment]
> whoops I forgot to fix the white decals after I tried to convert that area to using the new decals
> 
> edit: you replied to the wrong pr

Great job me 👏

**Review by PestoVerde322 — APPROVED** [review]
Aright, this one should be fine to go, approved

**Pull request merged**
