### PR TITLE
[Port] holomaps! 

### PR DESCRIPTION
**Pull request by PestoVerde322**
## About The Pull Request

**This PR ports https://github.com/BeeStation/NSV13/pull/2281, which was ported from skyrat, which was ported from Polaris, which was ported from /vg/, done originally by DeityLink**

What this PR ports is an in-game holographical map which is an actual game rendition? (don't know if that's the correct word) of the current map which is taken at round-start.

So far the map looks...well semi-small compared to how big it actually is in-game and so far I've been unable to figure out a way to make it actually bigger.

TODO:

- [ ] Add holomaps on all the maps
- [ ] Add a "Command" variant for the holomap in all bridges and brigs
- [ ] Add a "Syndicate" and "Centcomm" variant respectiveley in the syndicate base and Centcomm
- [ ] Add a way to make it usable without the terminal, maybe add it as an item?

## Why It's Good For The Game

Know the ship's layout for once, and also, No longer an excuse of people getting "lost" on Fland.

## Testing Photographs and Procedure

immagine

</details>

## Changelog
:cl:
add: Added holomaps on board of all the stations, you have no longer an excuse of getting lost on board of any map.
/:cl:

### CODE REVIEW

**Comment by Bobbanz1** [comment]
> Know the ship's layout for once, and also, No longer an excuse of people getting "lost" on Fland.

Maybe change the reference of ship?

**Comment by ike709** [comment]
>  Add a way to make it usable without the terminal, maybe add it as an item?

PDAs?

**Comment by PestoVerde322** [comment]
> PDAs?

Unsure how to do that without making a TGUI app.

**Comment by Bobbanz1** [comment]
> > PDAs?
> 
> Unsure how to do that without making a TGUI app.

https://github.com/BeeStation/NSV13/pull/2281/commits/575f7d7bd6769a889e441c7ad27166b3a71a0cfe

**Pull request closed without merging**
