### PR TITLE
Removes xray from genetics

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

It's not healthy for the game, people use it just to validhunt which we want to actively discourage.
"But it's bad for golden" - no changes towards better roleplay are bad for golden. cope

## Why It's Good For The Game

It's great for the game

## Changelog
:cl:
del: Remove xray from genetics.
/:cl:

### CODE REVIEW

**Review by francinum — APPROVED** [review]

**Comment by Cenrus** [comment]
thanks

**Comment by Sinestia** [comment]
He may succeed where I failed ... 


Low-key, from a meta-perspective, no mutation is more powerful against antags. Especially if you have a gamer geneticist who literally moves his console out to the public to distribute mutations. It's why changing flash protection doesn't really do anything


This mostly leaves x-ray as an augment which is fine as an augment imo, since you need to actually get and trust another human being to implant it.

**Comment by FriendlyContractor** [comment]
While we are at it, how about removing thermal vision and implants as well ? Thermal vision is as much "valid hunty"(hell , i would even say its more validhunty as xray can have some genuine uses for example by engineer while thermal vision sole purpose is to spy on others). Implants on the other hand are slightly more balanced as they require some work and introduce minor vulnerability to EMP but they still ruin any sort of lategame stealth.

Here are some examples of stealth ruined by xray(I made up one):

- Abductors manage to knock out the curator in library without being seen and drag him to a private room. HOS sees them while walking adjacent hallway thanks to xray and comes in gun blazing
- Clock cult - clockies are new and are doing pretty bad but they manage to stay undetected thanks to their low activity on board the station. One of the cultists decides to cog janitors closet APC but little he knows botanist has already paid medbay a visit and is now equiped with xray and telekinesis. Botanist immediately reveals presence of clock cult on comms and proceeds to robust poor clockie with a broom.
- Basically any situation where half of the station is running around the station with xray and who knows what else.

**Comment by Archanial** [comment]
If they become such a problem I will remove them.
They require effort (surgery) and mats to be obtained, instead of genetics printing infite mutators.

**Review by PowerfulBacon — APPROVED** [review]
Can't you still get it nautrally, just rarely?

**Comment by Archanial** [comment]
> 
> 
> Can't you still get it nautrally, just rarely?

No idea, if it's rare fine by me.

**Comment by BrumalLake** [comment]
you can't get mutations you get from combining naturally

**Comment by Kapu1178** [comment]
completely broken from a powergaming perspective and promotes validhunting

i see no reason to not remove it

**Comment by Cenrus** [comment]
Good ending

**Pull request merged**
