### PR TITLE
The name and job of the announcer are now shown in announcements

### PR DESCRIPTION
**Pull request by VictorVow**
## Why It's Good For The Game

Allows you to see who's _really_ sending WGW over announcements.

## Changelog
:cl:
add: The name and job of the announcer are now shown on announcements. 
/:cl:

Ports:
https://github.com/WaspStation/WaspStation-1.0/pull/44 (originally from OracleStation)
https://github.com/WaspStation/WaspStation-1.0/pull/503

### CODE REVIEW

**Comment by ghost** [comment]
Can you perhaps make the announcement input into a box like the central command announcement? it would allow for more structured announcements.

**Comment by VictorVow** [comment]
Good idea.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Should be from the ID logged in / signed with rather than the mob

**Comment by VictorVow** [comment]
Fixed, PR should be ready.

**Pull request merged**
