### PR TITLE
The SnapPop's Greentext is now real.

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
The SnapPop's Greentext will grant actual greentext to whoever makes it to centcom holding the greentext.

## Why It's Good For The Game
Adds a bit more fun to the shuttle.

## Changelog
:cl:
add: The SnapPop's Greentext is now real.
/:cl:

### CODE REVIEW

**Comment by Sarchutar** [comment]
Changing it from `/obj/item/greentext/quiet` to `/obj/item/greentext` won't make it more real because the only difference is that the quiet one does not send a message to every player upon it's destruction.

To make it able to be picked up you need to change `anchored` to `0` in the map file.

**Comment by Ivniinvi** [comment]
missed that, fixed

**Comment by PowerfulBacon** [comment]
:key:

**Comment by qwertyquerty** [comment]
:key:

**Pull request closed without merging**
