### PR TITLE
Nerfs and Tweaks to Debtor

### PR DESCRIPTION
**Pull request by Sinestia**
## About The Pull Request

Removes the martial art

Changes the flavor text to fit someone who is psychotically attached to the station

Adds a crew objective to remain on the station. 
## Why It's Good For The Game

Softer changes than just removing the debtor, this may be insufficient.

I do like some of the gimmick ideas put forth in the removal PR but this is just something quick. 

One problem with outright removal is that the maintenance goblin gimmick is likely inherently bannable under our current ruleset. 

Text and idea by Evelina#3104 on discord

## Changelog
:cl:Froststahr, Evelina
add: A new crew objective has been added for the debtor, which requires them to remain on the station alive. 
balance: Psychotic brawling has been removed from the debtor.
tweak: Debtor has received new flavor text. 
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
i think it's better to just remove it
no one wants to play an awful job with a trauma that makes it nigh-impossible to play with a decent population and have no benefits
this is gonna take the crown from psychiatrist when it comes to worst and most boring gimmick to roll

**Comment by DerpiestBruh** [comment]
> no one wants to play an awful job with a trauma that makes it nigh-impossible to play with a decent population and have no benefits

just like... take off the tin foil hat with someone's help

**Comment by Fronsis** [comment]
> > no one wants to play an awful job with a trauma that makes it nigh-impossible to play with a decent population and have no benefits
> 
> just like... take off the tin foil hat with someone's help

One of the possibles fixes/adjustment was for the trauma to persit even when the hat was off

**Comment by Howluinb** [comment]
the only annoying part of debtor imo is the fact that the tinfoil trauma makes you afraid of lizards.
which can happen even if you yourself are a lizard.
it's dumb

**Comment by PowerfulBacon** [comment]
I think they should just be removed entirely.

**Comment by BrumalLake** [comment]
> > no one wants to play an awful job with a trauma that makes it nigh-impossible to play with a decent population and have no benefits
> 
> just like... take off the tin foil hat with someone's help

against the rules because of these recent transitions towards being an hrp server

**Comment by DerpiestBruh** [comment]
> > > no one wants to play an awful job with a trauma that makes it nigh-impossible to play with a decent population and have no benefits
> > 
> > just like... take off the tin foil hat with someone's help
> 
> against the rules because of these recent transitions towards being an hrp server

Bee is not HRP, and there isn't anything against taking off your tinfoil hat in the rules

**Comment by Sinestia** [comment]
Two maints spoke against it, so I'll prolly just close it

**Comment by Sinestia** [comment]
> > > > no one wants to play an awful job with a trauma that makes it nigh-impossible to play with a decent population and have no benefits
> > > 
> > > 
> > > just like... take off the tin foil hat with someone's help
> > 
> > 
> > against the rules because of these recent transitions towards being an hrp server
> 
> Bee is not HRP, and there isn't anything against taking off your tinfoil hat in the rules

This is wrong btw, asking someone to take it off is against the rules

**Pull request closed without merging**
