### PR TITLE
Expanded Lizard Customization - More Frills

### PR DESCRIPTION
**Pull request by evensmallerguy**
## About The Pull Request

More frills for use by lizards in the character customization window. ~5 new options, may add more if I have time, but for now it'll just be this. I'm gonna be honest with you, I have no idea if I did any of this correctly.

## Why It's Good For The Game

I feel like customization for lizards is a bit limited, so I just wanted to spice things up a bit.

## Testing Photographs and Procedure

<details>

ShortSpines
Spines2
NewDamaged
PoisonAquatic
thank you Dakae for the screenshots 🙏

<summary>Screenshots&Videos</summary>

</details>

## Changelog
:cl:
imageadd: Added sprites for additional lizard frills.
/:cl:

### CODE REVIEW

**Comment by HowToLoLu** [comment]
Welcome to the club of submitting the PR before doing stuff with the title and description.

**Comment by HowToLoLu** [comment]
It's alright, not the first time this has happened by far

**Comment by Tsar-Salat** [comment]
Goober.

We all do it sooner or later.

Maybe you'll even be dumb as me and somehow do it twice. :(

**Comment by ClownMoff** [comment]
I've opened 4 PRs for the same thing

**Comment by ClownMoff** [comment]
In fact sometimes I open PRs before I finish them entirely. Maintainers are not your friend. This is a Fortnite battle royale, scavenge for resources and get the epic victory royale (getting merged). Good luck out there

**Pull request closed without merging**
