### PR TITLE
Bumps hat sprites on IPCs up by 2 pixels

### PR DESCRIPTION
**Pull request by Kapu1178**
## About The Pull Request
Before: 
image

After:
image

## Why It's Good For The Game
looks better

## Changelog
:cl:
tweak: Hats on IPCs are now shifted 2 pixels upwards
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
Can you post more examples of this? Or at least pictures from front?

**Comment by Kapu1178** [comment]
> 
> 
> Can you post more examples of this? Or at least pictures from front?

image
image
image
image
image
image

**Comment by Crossedfall** [comment]
I get the effect, it's sitting on the monitor instead of over it.. But, I got to be honest, I think it looks worse/silly this way. Might be worth doing a vote

**Comment by Kapu1178** [comment]
Democracy

**Pull request closed without merging**
