### PR TITLE
Removes grenade lance

### PR DESCRIPTION
**Pull request by FriendlyContractor**
## About The Pull Request
Removes grenade lance from the game

## Why It's Good For The Game
Item only usable by non-antagonists due to its suicidal nature with exception of revolutionaries. Exclusively used by validhunters to one click gib antagonists. Can be used to instantly kill absolutely everybody including deathsquad and nuclear operatives.

## Changelog
:cl:
del: Removed grenade lance
/:cl:

### CODE REVIEW

**Comment by DerpiestBruh** [comment]
ided

**Comment by Wilchenx** [comment]
>Can be used to instantly kill absolutely everybody including deathsquad and nuclear operatives.

Just click them with your funny gun crybaby

**Comment by ghost** [comment]
Grade S+ Refined copium here boyos. If a nuke op can't take down a guy with an obvious E-lance on his hand. you should die. You can't throw it anyways. it will just embeds in you causing no explosions. you gotta come in close

**Comment by Glcbitj** [comment]
Pure, undiluted copium, mixed with ided. Truly strong is the short-range obvious weapon with one ammo per bulky object you carry. Imagine being a nukie and not being able to run and shoot, plus unless your antags are basically confirmed, sec will not appreciate that you are running around with a gib-machine.

**Comment by Howluinb** [comment]
me when i rush a wizard preoccupied by fighting security/busy roleplaying with an explosive meth grenade lance instantly killing them but it's fair and balanced because i had to be in melee (as if all antags are suddenly melee immune)

**Review by Archanial — APPROVED** [review]

**Comment by RDS88-beeman** [comment]
if you're outed as an antag you better be fucking able to snipe anyone that gets in melee, this also doesn't stop the (in decreasing order of effectiveness) suicide TTV, suicide insta-flashbang, suicide cooked grenade, or suicide stunbatong

**Comment by Howluinb** [comment]
> 
> 
> if you're outed as an antag you better be fucking able to snipe anyone that gets in melee, this also doesn't stop the (in decreasing order of effectiveness) suicide TTV, suicide insta-flashbang, suicide cooked grenade, or suicide stunbatong

>suicide TTV
bannable
>suicide insta flashbang
short hardstun, no one in close enough range to melee you can take ultra effective action and while it does fuck you up there are ways to fight back
>suicide cooked grenade
you hear the beep and are able to know in advance someone is coming with a boomie
>suicide stunbatong
will never work against anyone robust who's not under attack by 20 people at once

A bomb spear is : inaudible, hard to see, instant, one click death, non bannable, no counter.

it should not exist

**Comment by Hibabo** [comment]
> Pure, undiluted copium, mixed with ided. Truly strong is the short-range obvious weapon with one ammo per bulky object you carry. Imagine being a nukie and not being able to run and shoot, plus unless your antags are basically confirmed, sec will not appreciate that you are running around with a gib-machine.

what are you gonna do when someone on meth shows up with one of these

**Comment by utilbird** [comment]
There's 101 other ways to one-hit someone (either effectively or literally) with similar or even less amounts of effort, many of which don't come at the cost of suicide.
If target response time is _really_ an issue, a much better solution would be to add a priming timer with an audible beeping alert.

With that said, I think the severity and impact of grenade lances are being heavily exaggerated. Any issues with G-lances don't go beyond the problems with grenades, which mostly boils down to their availability (we should steal how goon does it tbh) but that's a WHOLE 'nother issue!

**Comment by heepox** [comment]
I'm sorry your Cult Summoning / Ascended Heretic / Wizard / Nuclear Operative / Murderbone Antag nr.666 / Clockwork Cult End siege / Revolution Was ended by the Legendary and rare Explosive lance when anyone with even two braincells could simply wire a grenade with a remote detonator and do the exact same thing but with more control and less hilarity when you hear the warcry nanoseconds before the explosion.

Your Copium supplies must be reaching a critical deficiency for you to make this PR and I hope you receive your daily dose in due time.

**Review by PowerfulBacon — APPROVED** [review]

**Review by ike709 — APPROVED** [review]
Fix conflicts

**Pull request closed without merging**
