### PR TITLE
[Port] Slime Rancher-Ifies Xenobiology

### PR DESCRIPTION
**Pull request by XeonMations**
## About The Pull Request

Replaces basically all of current xenobiology with a new system from monkestation that involves a lot more moving around.

Acquired PRs:
- [x] https://github.com/tgstation/tgstation/pull/83891
- [ ] https://github.com/Monkestation/Monkestation2.0/pull/1442
- [ ] https://github.com/Monkestation/Monkestation2.0/pull/1192
- [ ] https://github.com/Monkestation/Monkestation2.0/pull/1638
- [ ] https://github.com/Monkestation/Monkestation2.0/pull/2139
- [ ] https://github.com/Monkestation/Monkestation2.0/pull/2265

## Why It's Good For The Game

Sitting at a screen for hours without any interactions is bad. This hopefully makes xenobio atleast a tiny bit bearable.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
del: Removed Xenobiology
add: Added Slime Ranching
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
What does this actually do? How does it impact the power of the department?

**Comment by XeonMations** [comment]
> What does this actually do? How does it impact the power of the department?

Instead of having to sit in one place for hours at a time, xenobiology will have to actually move around and request things from the station in order to further progress itself.

**Comment by MarkusLarsson421** [comment]
> Instead of having to sit in one place for hours at a time, xenobiology will have to actually move around and request things from the station in order to further progress itself.
> 
> Also adds in the feature of being able to request things from xenobiology easier.

And how is this PR designed to compliment that goal? What changes? The PR lack concrete information of what it is supposed to change.

**Comment by XeonMations** [comment]
After looking into a lot of code behind this, i'm closing this PR for the time being due to the requirements needed to do all of this. Maybe I'll attempt it at a later date.

**Pull request closed without merging**
