### PR TITLE
Edited sprite for the stacking machine.

### PR DESCRIPTION
**Pull request by BettonnCZ**
## About The Pull Request
I edited the sprite for the stacking machine so you can actually distinguish between the stacking machine and the BS miners.

## Why It's Good For The Game
Asthetics.

## Changelog
:cl:
tweak: Edited the sprite for the stacking machine
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
What do the new sprites look like?

**Comment by BettonnCZ** [comment]
image

**Comment by BettonnCZ** [comment]
they are white now! well, white ish, its between white and sand yellow, i tought it looks neat.

**Comment by xboxnoob** [comment]
It looks good.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Bluespace miner uses the same sprite, so bluespace miner gets changed too

**Comment by xboxnoob** [comment]
Oof

**Comment by BettonnCZ** [comment]
i hope i did it right, dont beat me code monkey

**Comment by TeomanTheGreat** [comment]
Travis failed

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
