### PR TITLE
Makes miscelanious crossbreeds more viable

### PR DESCRIPTION
**Pull request by St0rmC4st3r**
## About The Pull Request

Lowers the required slime cores for crossbreeding from 10 to 5 which allows for more crossbreed projects to be made in the same amount of time.
It also brings the crossbreeds a bit closer in terms of resources to normal slime cores that are sometimes more powerful than some crossbreeds.

## Why It's Good For The Game

Most crossbreeds are actually quite wacky and not that powerful.
Then what's the point of keeping them overpriced? 
Let's calculate the price (in cores) of a crossbreed regardless of colour.

In the case without upgrades to the slime processor:
- One adult slime = 2 baby slimes = 2 cores
- 10 cores = 10 baby slimes
So in the case, of not upgrading equipment, one crossbreed costs 12 baby slimes, or 12 cores.

In the case of maximum upgrades:
- One adult slime = 2 baby slimes = 8 cores
- 10 cores = 2.5 baby slimes
In this case, we are getting a single crossbreed for 4.5 baby slimes, or 18 cores of which 6 are wasted as the adult slime is not subject to processing.

Both seem like a fair price for a crossbreed that lets you cheat death (Chilling Cerulean), fabricate infinite resources (Stabilized Metal), or get free teleportation for both short-range and a recall spell (Gentle Bluespace). 
However, the price seems to be stupidly high for cookies that change your colour (Consuming Pyrite), a Zippo lighter factory (Industrial Orange), Barrier Grenades (Chilling Grey), corgi maker (Chilling Pink), paintbrushes (Any Prismatic), Janitor Job Stealer (Crystalline Dark Blue), A nudist experience for 20 seconds or so (Chilling Cerulean), a glorified microbomb implant (Stabilized Oil), or a plasma fart (Burning Dark Purple).
Regenerative extracts probably can fall in either category, as 50 healing of each damage is very sweet, but the ridiculous core requirements make them stupidly inefficient to mass-produce.
This may (or may not) give us a chance to see whether it is possible to make xenobio actually useful to the station if we soften the factor that makes them say "I spent this much time and resources for this inconsequential thing I made that I would rather hold onto it than give it out to someone."

## Testing Photographs and Procedure

<details>

https://github.com/BeeStation/BeeStation-Hornet/assets/34888552/1c66661d-675b-4ee4-ac3f-064acb5a435c

</details>

## Changelog
:cl:
balance: Xenobiology crossbreeds are now twice as cheap.
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
Agreed. A more tedious xenobio is not a more well-balanced one.

Crossbreeds one their own are not at all more powerful than cores themselves, and I've seen abundantly more altruism from people handing them out rather than cores alone.

Ultimately, lowering the cost is the better option compared to say, increasing the availability of cores.

**Comment by PowerfulBacon** [comment]
> Both seem like a fair price for a crossbreed that lets you cheat death

There is no fair price for unbalanced items. I'm not entirely against but ultimately this is going to lead to
- Xenobiologists being able to have more impact on the round earlier in a round.
- They are going to become an issue (Moreso than they are already).
- Crossbreeds will probably end up being removed as a result.
With the nature of xenobiology, any QOL updated bring it closer to the ultimate end of crossbreeds as their entire point is balance based on being a pain in the ass to make which is just terrible.

Ultimately, crossbreeds in general aren't good for the game and I think this could potentially highlight that issue by making it more accessible in shorter amounts of time as an unintended side effect. Tediousness is a balancing issue, however xenobiology's balanced is entirely based on tediousness and RNG which are huge issues for us.

I do have to argue against some of the points brought up in this PR
> However, the price seems to be stupidly high for cookies that change your colour

Yes, but when all items cost the same regardless of balance we need to balance around the most powerful items rather than the weakest ones.
>cheat death

Simply unbalanced, no way around this if you have to use it.
> fabricate infinite resources

Disruptive
> or get free teleportation for both short-range and a recall spell

This also sounds pretty unbalanced regardless of cost. Anything allowing you to basically become unkillable and have free get aways is simply unfun to play against.
> This may (or may not) give us a chance to see whether it is possible to make xenobio actually useful to the station if we soften the factor that makes them say "I spent this much time and resources for this inconsequential thing I made that I would rather hold onto it than give it out to someone."

This will just result in players finishing what they want to do and leaving xenobiology quicker, rather than deciding to make things that aren't as useful to themselves or are fun instead. Right now we have xenobiology players that finish what they want but rather than going and making the fun things they just leave the department and wander around, either showing off their powers or accidentally running into conflict. In the case where they are antagonist, many of the powers are simply not fun to play against.

> Regenerative extracts probably can fall in either category, as 50 healing of each damage is very sweet, but the ridiculous core requirements make them stupidly inefficient to mass-produce.

We do not want these to be mass producable.

**Comment by PowerfulBacon** [comment]
To show testing evidence create a crossbreed with 5 slime cores instead of 10.

**Comment by Rukofamicom** [comment]
🔑 

I agree with the logic, and even think this is an overall improvement to an otherwise not great system, but this is also direct buff to what is the single most powerful and controversial department currently in the game.

Because of this I cannot accept this as an improvement to the game unless it is coupled with a general Xenobiology overhaul. I can discuss the points of this more in discord and will remove my key vote if this is something you want to pursue.

**Comment by PowerfulBacon** [comment]
I dislike this PR due to the state of xenobiology balancing being entirely based on it being tedious (which is awful) and making it less tedious would just result in the stupid xenobio things being easier to get.

**Pull request closed without merging**
