### PR TITLE
Completely new hos and captain cloaks

### PR DESCRIPTION
**Pull request by AnjelicaChaykovsky**
## About The Pull Request

Nanotrasen was finally able to secure better materials !
 Every captains cloak now is fitted with beautiful checkered goon station textured  textile  and fluffy space buffalo fur around the neck.

The head of security cloak was replaced  with brand new m45 patten guillie style military cloak, criminal scum cant shoot what they cant see. 
This classy green universal look doesnt conflict with any other clothes. 

## Why It's Good For The Game

I recently saw eva suits be completely changed,  i decided to give my go too.    
Hos and captains cloaks were the bottom of all the heads for sure, you cant even compare it to hop or ce, i did my best to redesign them  while making sure they dont stand out too much.
Oh yeah the captain hardsuit helmet was something  i could never wear, but i really liked the look of skinsuit helmet so it has now  a very fancy version of it.
Old caps helmet looked like something out of bdsm. 

## Changelog
:cl:
imageadd: changes hos and captain cloak 
/:cl:

### CODE REVIEW

**Comment by Penwin0** [comment]
I like the change to the Caps cloak it looks much more "prestigious" to say the least, but i think the HoS one doesnt fit well with the Red/Black color scheme of security

**Comment by SomeAngryMiner** [comment]
capes were needing a change since a long, long time, so this is a step on a right direction (my aim was to make them all more like a regal shoulder mantle, but this is fancy as well).
Do note, though:
you have an extra, empty frame on the captain's helmet, making it flash in and out from existance in regular intervals, removing it should fix this issue.
Both capes look fancy, but the shading on the captain's cape is too subtle to be readily noticeable. that can be fixed easily as well, in fact, if you give me a few mins, ill make a commit to recolor that. HoS cape is just missing some colored outlines, but having it be something more than black and red, breaking the edgy emo looks, is a nice change of pace.

**Comment by AnjelicaChaykovsky** [comment]
> you have an extra, empty frame on the captain's helmet, making it flash in and out from existance in regular intervals, removing it should fix this issue.

  i just fixed it and its still there ? 
oop 
To be honest its remnants from where i tried to animate it.

**Comment by AnjelicaChaykovsky** [comment]
> Both capes look fancy, but the shading on the captain's cape is too subtle to be readily noticeable. that can be fixed easily as well, in fact, if you give me a few mins, ill make a commit to recolor that.


yeah when you point that out its really too subtle im bored rn so i will try fixing it, thanks for the feedback

**Comment by SomeAngryMiner** [comment]
image
rough draft of a fix i could pull. As the PR creator, up to you if wanna grab it.
note: just noticed, but you cant see the back line on the front or sides states, might need to fix that too for directional consistency.

**Comment by AnjelicaChaykovsky** [comment]
>  but i think the HoS one doesnt fit well with the Red/Black color scheme of security

Yeah and at the beginning i wanted to make a red or black cloak, but in the end i found it really boring, then i had a cool idea in  mind  since red + green fit beautifully together.
green is  a great  complementary color for red  soo i really would like to see it in game  i love this look personally 

> rough draft of a fix i could pull.

damn i really love the gold but i feel like the style is very different from clothes of ss13

**Review by AnjelicaChaykovsky — COMMENTED** [review]
fixed missing helmet frames

**Comment by AnjelicaChaykovsky** [comment]
i changed the back of the cloak to this but not sure if its final

**Comment by PowerfulBacon** [comment]
The new skinsuit helmets are ugly and are probably going to get changed (if they don't they should), so copying them isn't what I would recommend.
The captain's cloak looks good.
The HOS' one looks ok, but the colours would be better if they matched the red and black theme, the green look seems like it would be better for the Russian gear.

**Comment by AnjelicaChaykovsky** [comment]
> The new skinsuit helmets are ugly and are probably going to get changed, so copying them isn't what I would recommend.
> The captain's cloak looks good.
> The HOS' one looks ok, but the colours would be better if they matched the red and black theme, the green look seems like it would be better for the Russian gear.

skinsuits helmets dont look that bad  



compare it to cmos. 

I will try  adding red to hos cloak

**Comment by AnjelicaChaykovsky** [comment]
adding red to the cloak is possible but completely butchers old design which is ... sad  
early wip so far

**Comment by AnjelicaChaykovsky** [comment]
how does this look ?

**Comment by PowerfulBacon** [comment]
> 
> 
> 
> how does this look ?

This actually looks quite interesting, although the playerbase in general is more who you want to please rather than me so you don't have to listen to me if you don't want to.
How does this look when attatched to a player?

**Comment by AnjelicaChaykovsky** [comment]
> How does this look when attatched to a player?

**Comment by AnjelicaChaykovsky** [comment]
i also added a little bit of red to caps cloak which i will merge tonight

**Comment by SomeAngryMiner** [comment]
> The new skinsuit helmets are ugly and are probably going to get changed (if they don't they should), so copying them isn't what I would recommend.

already have a fix up for that, in fact, NSV already got the new skinsuits.

image

just waiting for their merge for a speed resprite.

**Comment by SomeAngryMiner** [comment]
> 
> i also added a little bit of red to caps cloak which i will merge tonight

i would heavily recommend using a bit of shading on that red stripe, and more hueshift overall on the blue, and should be fine n dandy.

**Comment by Chessus** [comment]
I think the caps uniform change is great, it set's it apart from the HoP's. 

Not too keen on the green colour for HoS though, The brown makes looks similar to the Qm's jacket.

**Comment by AnjelicaChaykovsky** [comment]
final vers i guess because im starting to lose braincells     

Skelly likes it

**Review by AnjelicaChaykovsky — COMMENTED** [review]
added lots of red to hos cloak, fixed patterns on caps cloak and added small animation to it

**Comment by AnjelicaChaykovsky** [comment]
no more changes im doneee with this it has been fun  even if it doesnt make it into the game

**Comment by hotimep** [comment]
bro hos cape looks like half a turtle shell

**Comment by PowerfulBacon** [comment]
Changelog is for just the changes, not for explanations
🆑 
imageadd: adds image
/🆑

**Comment by ActualRory** [comment]
I like the HoS Cloak, but I think the Captain's cloak just doesn't work.
If the vote goes against you: I'd recommend making a new PR, solely for the HoS Cloak.

**Comment by PowerfulBacon** [comment]
The general consensus here is that the helmet of the Captain's suit is not liked, although the capes are good. Maybe if you separated the capes into a different PR, it would have a good chance of being voted for.

**Comment by Bruce-U** [comment]
yo honestly cloaks pretty cool but helm kinda poop
i think something like this would look better
image

**Comment by AnjelicaChaykovsky** [comment]
> The general consensus here is that the helmet of the Captain's suit is not liked, although the capes are good. Maybe if you separated the capes into a different PR, it would have a good chance of being voted for.

 it really looks like deep dark fantasy guy  maybe im the only one who doesnt like it 





soo tell me do you actually like old caps helmet  ? @Bruce-U  @PowerfulBacon

**Review by AnjelicaChaykovsky — COMMENTED** [review]
caps helmet was removed and now the head.dmi is completely free of changes, i  cant remove it though 

old caps helmet still super gay

**Comment by hotimep** [comment]
iirc captain's hardsuit lore-wise is supposed to be a reskin of the swat suits

**Comment by Bruce-U** [comment]
@AnjelicaChaykovsky nope 
 makes my head look big
 exposed mouth allows any mask except welding mask to burn and be destroyed if you are in a plasma fire for too long
 It is not like the other heads hardsuits, which have unique helmets except CE and even his helmet is  slightly different from the normal engi suits, since its the same helm as DS suit and makes sense since its another version of the same suit, but still dont like it

theres room for improvement but making it similar to the CMOs suit doesnt cut it for me, although i would rather have it look like that than what we have rn

**Comment by PowerfulBacon** [comment]
The people have voted down on this one. I think the biggest issue was the helmet looking too similar to the disgusting skinsuit helmet. The cloaks themselves were very nice. Maybe with some tweaks this could be passed.

**Pull request closed without merging**
