### PR TITLE
Adds the ability to "lock" chameleon gear with a multitool

### PR DESCRIPTION
**Pull request by CydiaLamiales**
## About The Pull Request
Adds the ability to hide/show any chameleon abilities of chameleon gear by hitting it with a multitool. This includes the disguise button, individual shape change buttons, tongue disguise button for the gas mask, alt-clicking the mask to turn it on or off, forging the agent ID.
Note that all of them are still vulnerable to EMPs in that state.

## Why It's Good For The Game
Chameleon gear is great for sneaking around, framing other people and plethora of other uses. But it has a dead giveaway - anyone who picks up any piece of such gear can immediately recognize it due to the UI buttons.
Imposing metaprotection and metaknowledge rules for this would honestly be quite silly, so here comes an alternative solution - hiding those buttons! Just be sure not to forget what's a real piece of clothing and what's chameleon.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/110184118/f24fd7f8-ffe5-4a73-ba79-f72fe6cfef82

</details>

## Changelog
:cl:
add: The Syndicate has upgraded its chameleon gear with the ability to completely hide any and all chameleon functionality with a multitool. Be sure not to confuse your own gear for a plain old piece of clothing, agent!
/:cl:

### CODE REVIEW

**Comment by Tyranicranger4** [comment]
Kind of a niche thing, but it may be worth logging when it's disabled. It'd be nice to have if (when) people try to metagame this.

**Comment by CydiaLamiales** [comment]
> Kind of a niche thing, but it may be worth logging when it's disabled. It'd be nice to have if (when) people try to metagame this.

Sure

image

**Comment by Fronsis** [comment]
Hmm this is certainly an interesting change, i can see some RP coming from situations regarding different clothing on a person, but how would Security eventually discover they're indeed carrying chamaleon clothes? (Except of course if they walk with a CHRONO-LEGIONARRIE suit) There should be some kind of traces or something the detective could do to get a case going, or even a limit on the number of lock-ins you can do, because as we know the Syndicate has a lot of experimental technology, because someone could easily swap jobs and identities on the spot without any drawbacks, i believe that's something more proper for the Changeling.

Of course this is a good QoL because those buttons are indeed very used as a ''this is contraband bye'' but i'd like to see some discussion on how will it be seen from the Sec side and some balance to prevent players for being undetectable (See Ex-comms that use this + mulligan)

**Comment by Rukofamicom** [comment]
> but how would Security eventually discover they're indeed carrying chamaleon clothes?

I don't think it is a necessity that they be able to tbh.

**Review by Rukofamicom — APPROVED** [review]

**Pull request merged**
