### PR TITLE
[WIP] Absolutely nothing of any significance. Don't bother looking at this PR.

### PR DESCRIPTION
**Pull request by ike709**
## About The Pull Request
I looked at every PR TG merged between smart cables and now, ported everything to do with smart cables except mapping changes which I'll have to do manually.

## Why It's Good For The Game
Less lag, less tedium.

## Changelog
:cl: TGstation, your oppressive overlords
tweak: Cables have been significantly modified to reduce lag and streamline the wiring process. This is for your own good.
/:cl:

TODO (in order):
- [x] Port all of the code
- [x] Catch a lot of flak because beetards misunderstand most of what this PR actually does
- [x] Catch a lot of flak because beetards hate change
- [ ] Regex to remove cable vars from maps
- [ ] Mapping first pass: Delta
- [ ] Mapping first pass: Meta
- [ ] Mapping first pass: Kilo
- [ ] Mapping first pass: Pubby
- [ ] Mapping first pass: Box
- [ ] Local testing
- [ ] Testmerge the port as-is
- [x] ~~Beetards realize the change isn't so bad, and stop hating me~~
- [ ] Catch a lot of flak because beetards are too stupid to look at the planned compromises
- [ ] Catch a lot of flak because beetards hate change, round 2
- [ ] Inevitable second mapping pass
- [ ] Compromise part 1: Readd colored cables
- [ ] Compromise part 2: Different colors don't connect automatically
- [ ] Compromise part 3: A method of connecting different colors
- [ ] Compromise part 4: Grilles don't automatically get shocked by wires under them
- [ ] Local testing
- [ ] Testmerge the compromises
- [ ] Cry
- [ ] Merge

### CODE REVIEW

**Comment by ghost** [comment]
ah, okay, we had 2 votes, both against it, a huge debate, and then you still have the nerfes to PR this? yeah alright, fuck you too.

**Comment by ike709** [comment]
mapdiffbot died, big sad

**Comment by qwertyquerty** [comment]
I wasn't aware their update removed colored wires

**Comment by ike709** [comment]
qwerty never helped with the regex and I don't have the time anymore

**Pull request closed without merging**
