### PR TITLE
Adds the Grenade Gauntlet

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request
Adds the Grenade Gauntlet, a powerful traitor item that functions similarly to old explosive lances, when loaded with a grenade, anything punched by this gauntlet will have the grenade be detonated right under them.

The gauntlet can also be used inhand to toggle it being NO_DROP

it has a 20 minimum pop before being able to be bought in the uplink

## Why It's Good For The Game
A very high risk- high reward weapon, to encourage risky, flashy plays

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/54711687/b5f7a1bd-f9b5-47f3-8b34-299443a4ca0c

https://github.com/BeeStation/BeeStation-Hornet/assets/54711687/3580780f-8071-4abb-9456-48937de899d0

</details>

## Changelog
:cl:
add: Adds the Grenade Gauntlet, a risky weapon that when loaded with a grenade will cause anyone hit by the gauntlet to get hit point-blank by the grenades effects
add: The Grenade Gauntlet to the traitor and nuclear operative uplinks
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
If we are going to do something like this, then the grenate should prime on impact but be forced to go through the 5 second period before it explodes; with the spear embedding in the victim while it activates giving them some time to either pull it out, realise what is about to happen, or have it deflect from armour if its embed fails.

**Comment by ToasterBan** [comment]
A big part of the balance of this is that if you do something high explosive you'll probably die aswell, better use cases would be something like lube foam with noslips or a plasma flash when your an oozeling. 

but having the grenade not instantly detonate but embed is interesting and I might do that

**Comment by Rukofamicom** [comment]
Agree with bacon - grenade should embed or something to give the other player a moment to react, it should not be a forced instant explosion, or frankly even be possible to make instant - this sort of thing just isn't fun for the receiving player if it is at all.

**Comment by Fronsis** [comment]
> If we are going to do something like this, then the grenate should prime on impact but be forced to go through the 5 second period before it explodes; with the spear embedding in the victim while it activates giving them some time to either pull it out, realise what is about to happen, or have it deflect from armour if its embed fails.
> **Edit:** Just saw that it operates instantly from a fist mounted weapon instead of on a spear or anything. In that case perhaps it should have some kind of property similar to the power fist, where it will hit someone back a few tiles, stun them and drop a grenade underneath their mob. Anything with a few seconds before detonation allows them to be dragged away by a teammate and makes slightly it less of a 1-hit kill punch.
> This needs something to make it not instant or a little more fair to be against. You need to consider how to make it fair for the victim, but also still powerful/fair for the user if someone is able to counter it.


I mean being thrown back, stunned and then exploding isn't better than what's being offered here considering it would make it an insta-win weapon to your targets or anyone that's alone however:

The embed proposal is.. interesting! but then again.. how can a punch embed something to you!? i do like armor having a chance to deflect it though, you could try something along those lines and see what you can come up with, the current version seems like an explosive lance that costs tc(and lets you put other stuff i guess like an emp nade and other explosives) and can equally kill you as wel(since that's intended) so i doubt people would use it  that much given they have a craftable lance as the free alternative for suicide charges, unless they want to make the damage slightly more devastating using a syndiebomb(which you can if you go right next to someone with INSTANT detonation), looking forward for the update

**Comment by Howluinb** [comment]
good job on using the EMP grenade first in your video so that we can't see the gauntlet not working properly, really clever

**Comment by ToasterBan** [comment]
after doing some thinking, this could easily be used as an unfun instawin option, my initial idea would be creative use of grenades but I need to remember that players will always try do a free win if possible

**Comment by PowerfulBacon** [comment]
I do think this could be adapted to be fair and work well if you are interested or have any ideas

**Pull request closed without merging**
