### PR TITLE
arts & canvases update

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

tgstation/tgstation#48834
tgstation/tgstation#53585
tgstation/tgstation#56349
tgstation/tgstation#53994
tgstation/tgstation#59146
and multiple supporting loose commits

reeeeee

## Why It's Good For The Game

artss

## Changelog
:cl: tralezab, AnturK
add: curators can now print paintings
add: persistent paintings
add: AIs can now pick paintings as their screens
add: tgui canvases
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Tgui changes frozen

**Comment by jupyterkat** [comment]
mad

**Comment by jupyterkat** [comment]
map edits are not there so there won't be persistent paintings in the library until the change freeze is over

**Comment by ike709** [comment]
?rebuild tgui

**Comment by ike709** [comment]
?rebuild tgui

**Pull request closed without merging**
