### PR TITLE
Fix Build Mode map generator not working or hiding undertiles

### LINKED ISSUE #9588: [Bug]: Admin Mapgen Repair Tool no longer functions
### BYOND Version

514.1589

### Round Date

N/A

### Round ID

N/A

### Test merges

N/A. Issue persists on a local branch.

### Describe the bug

When attempting to use either the `Repair: Reload Block - Mass Delete` or `Repair: Reload Block - Mass Delete - In Place` generators under the buildmode mapgen tool, the selected area fails to properly regenerate. Instead it remains empty, depending on the option selected that means it'll either just be turf left, or it will be completely empty.

An example of an area undergoing regeneration:
image

*Normally* it would only remain this way for a brief period of time, now it persists indefinitely.
I suspect this issue was caused by #9469 , as it was working up until very recently - and this issue doesn't seem to occur on branches with this PR reverted.

The loss of the Repair tool is quite an unfortunate blow towards our ability to repair damage inflicted by grief.

### What did you expect?

I expected the area to fully regenerate in a timely fashion (or at all) per usual.

### Reproducible steps

1. Attempt to use either the  `Repair: Reload Block - Mass Delete` or `Repair: Reload Block - Mass Delete - In Place` mapgen functions in buildmode on a branch that has #9469 merged.
2. It doesn't work.

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

Fixes #9588 

Nothing else uses "partial" template loading so not even TG encountered this issue, but it was starting from wayy above the max index causing crds to be null and thus nothing to generate.

Also calls COMSIG_OBJ_HIDE to cause undertiles to properly update.

## Why It's Good For The Game

Fixes a bug

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image
image

</details>

## Changelog
:cl:
fix: Fixed build mode's map regenerator not working.
fix: Fixed build mode's map regenerator not properly hiding undertile elements.
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
Fucking shuttle gen I'M NOT EVEN TOUCHING YOUR MAP GENERATOR

**Comment by itsmeow** [comment]
This doesn't make any sense, the proc being modified isn't even RAN on shuttle templates so how could it possibly be causing a generation failure

**Comment by itsmeow** [comment]
I refuse to believe this is my fault because _tgm_load is literally not even called on the science shuttle

**Comment by itsmeow** [comment]
image
Hey wait what the fuck is this

**Comment by itsmeow** [comment]
WHAT
image

**Comment by LemonInTheDark** [comment]
> WHAT image

are you doing underlay posting or something how is that not deprecated

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
Is this PR fine to merge? Is the issue shown above a seperate issue or related to this?

**Comment by itsmeow** [comment]
I think it's unrelated? I don't know why that random test failure happened. also, the science shuttle was spawning with missing turfs. but I think it's unrelated because TG made the same changes to fix that issue after I reported it

**Comment by itsmeow** [comment]
Plus the behavior is random

**Pull request merged**
