### PR TITLE
Clearer secHUD icons

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request

The [new secHUD icons](https://github.com/BeeStation/BeeStation-Hornet/pull/3316) have their letters/symbols enlarged. Also the Monitor icon is now black in the centre like an actual eye. 

## Why It's Good For The Game

Icons were too small and hard to tell what they were before. 

## Changelog
:cl:
tweak: SecHUD icons enlarged for clarity. Monitor icon now looks like an actual eye. 
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
"hudreleased"
image
Looks too close to the revhead icon, perhaps change it to green instead or some other color?

**Comment by VictorVow** [comment]
`hudreleased` isn't actually in-use right now, but I figured I'd update it like I did the other icons. Kind of redundant when there's already "Discharged" really.

**Comment by Archanial** [comment]
I know monitor is supposed to be an eye but simple "M" would look and fit better

**Comment by PowerfulBacon** [comment]
there are way too many in all honesty, patrolled released, discharged should be toned down into 1 and monitor removed

**Comment by VictorVow** [comment]
Released I can remove since it's unused, and paroled/discharged/monitor perhaps should be reduced down. 

I'm probably most in favour of leaving only Monitor, since it can be used for both ex- and potential future criminals to keep an eye on. I'd like to gather more feedback from seccies on that first though, this PR is just intended to make the existing icons clearer.

**Comment by Raven-Industries** [comment]
Personally I like having the different gradations of meaning; there's definitely a bit of overlap in monitor/parole/discharge, but there's still enough difference to influence how I'd interact with them as a sec officer.

**Comment by FortSumter** [comment]
Only things your PR is good for is the addition of search and monitor. The current ones are good the way they are, I'd even vote to remove one or two due to "wanted" being the only one that gets used on either server. Those would be good to have, as they don't sick beepsky on them and sec officers would be always aware that they need to be suspicious of a particular individual. Of course, none of this matters if the person managed to get sec gear.... but that's a separate problem.

**Review by francinum — APPROVED** [review]

**Pull request merged**
