### PR TITLE
Temporary Access Passes

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

The ID console can now print temporary access passes that exist in the world for 5 minutes.

## Why It's Good For The Game

Requested feature. Makes HoP's life easier.

## Changelog
:cl:
add: The ID console can now print temporary access passes
/:cl:

### CODE REVIEW

**Comment by utilbird** [comment]
I can think of very few scenarios where this would be useful

**Comment by Crossedfall** [comment]
What's the difference between this and #3151?

**Comment by eeSPee** [comment]
> What's the difference between this and #3151?

I was gonna make it as an expansion but it works standalone.

This one allows the ID console to print ID passes that exist for a short while.
Whereas the other one starts HoP with access passes that work as passes, can be applied to IDs, and are permanent.

**Comment by utilbird** [comment]
Keyed by Bacon and I. 

if you want to re-open, see how #3151 goes before working on this again :)

**Pull request closed without merging**
