### PR TITLE
NO more blood duplication

### PR DESCRIPTION
**Pull request by DatBoiTim**
## About The Pull Request
Removes the ability to duplicate blood.

## Why It's Good For The Game
Infinite blood for synthlesh bad.

## Testing Photographs and Procedure

<details>

<summary>Screenshots&Videos</summary>

Proof of function

</details>

## Changelog
:cl: DatBoiTim
balance: Removed ability for viro reactions to make infinite amounts of blood.
/:cl:

### CODE REVIEW

**Comment by Naevii** [comment]
how do you do synthflesh factory now then ?

**Comment by AnCopper** [comment]
> how do you do synthflesh factory now then ?

You don't.

**Review by Archanial — APPROVED** [review]

**Comment by Archanial** [comment]
> how do you do synthflesh factory now then ?

you input blood yourself, not a big change.

**Comment by DatBoiTim** [comment]
> how do you do synthflesh factory now then ?

Put in blood manually

**Comment by DatBoiTim** [comment]
There are also other issues related to this(albeit rarer).

You can now no longer create infinite amounts of any blood type(never used to knowledge but now impossible). This infinite blood issue had a few implications: Trivializing transfusions, Trivializing poisoning people with bad blood.

Now if medical needs blood(and a lot of it) they can do blood drives! Cookies and Juice not included.

**Pull request merged**
