### PR TITLE
Unfucks initialize() on disco grenade

### PR DESCRIPTION
**Pull request by Rukofamicom**
## About The Pull Request
Adds the parent call back to the sub grenade Initialize()

## Why It's Good For The Game
Internal server stuff screeching is bad

## Changelog
:cl:
fix: Disco grenade 2, electric boogaloo
/:cl:

### CODE REVIEW

**Review by ike709 — APPROVED** [review]

**Comment by KubeRoot** [comment]
I think this PR might be botched, looks like the merged commit didn't include the change, and the Files Changed on the PR itself looks like the PR includes part of the change from the original PR, but doesn't revert the removal.

**Comment by Rukofamicom** [comment]
The original PR contained two parent call removals because one of them led to exponential recursion to the point of game crash.  The grenade was without both of these calls since it was first added to the game in January 2020, so I removed both seeing them as the problem that turned the grenade into a server crasher 3 days ago. (was when @jupyterkat added these calls.) 

Are you saying the other parent proc call was necessary and my original fix of adding a new variable to block the self-replication was better @KubeRoot?

**Comment by ike709** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/4379

**Comment by KubeRoot** [comment]
> The original PR contained two parent call removals because one of them led to exponential recursion to the point of game crash. The grenade was without both of these calls since it was first added to the game in January 2020, so I removed both seeing them as the problem that turned the grenade into a server crasher 3 days ago. (was when @jupyterkat added these calls.)
> 
> Are you saying the other parent proc call was necessary and my original fix of adding a new variable to block the self-replication was better @KubeRoot?

Sorry, could've been clearer: I'm saying the PR itself is botched, not the change it's meant to introduce. As far as I can tell (and ike making another PR confirms this) this PR fails to change anything in the code - take a look at the changes on the merge commit: https://github.com/BeeStation/BeeStation-Hornet/commit/e24e1fff06b011d85e0997a8ee0aad6a9db4347d

**Pull request merged**
