### PR TITLE
Adds THICKMATERIAL to various armoured exosuits and helmets

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
All current armoured exosuits as well as many helmets are now immune to syringes, parapens and hypos. Use Piercing Syringes or aim at a non-armoured regions when going after an armoured target. 

## Why It's Good For The Game
Feels inconsistent that armour and helmets can block bullets and stab wounds but not a tiny syringe. Chemical warfare currently has few counters, this adds another for one of the more popular tactics. 

## Changelog
:cl:
add: Most armoured suits and helmets' thick reinforced materials now prevent syringes, parapens and hypos.
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — COMMENTED** [review]
Standard security helmets and vests should not be thick material in my opinion, maybe the riot suit sure but something that barely covers the body shouldn't

**Comment by zeskorion** [comment]
> Standard security helmets and vests should not be thick material in my opinion, maybe the riot suit sure but something that barely covers the body shouldn't

I think the helmets should. Some armor should. But these are the *base types* for these

Thickmaterial checks body zone iirc so complete coverage is a non-issue here.

Victor, i'd like you to ctrl+shift+f each of these types, due to how clothijg flags work, and make sure the right armor has the right flags, as well as  adding proper flags to bits that have their own flags

**Comment by VictorVow** [comment]
THICKMATERIAL does indeed check body zone areas, I'll double-check to make sure each armor has the correct flags and move it from the base type.

**Comment by Mick1299** [comment]
Does thick material block self use of survival medipens through hardsuits? If it does, that's actually a solid way to nerf survival pen without trashing them completely

**Comment by VictorVow** [comment]
@Mick1299 no THICKMATERIAL doesn't block survival medipen use, and hardsuits already have THICKMATERIAL. That is a good idea for a survival medipen nerf however.

**Comment by zeskorion** [comment]
> THICKMATERIAL does indeed check body zone areas, I'll double-check to make sure each armor has the correct flags and move it from the base type.

I dont think you understood me. Helmets are A-ok, im just asking you to doublecheck and make sure others don't have defined flags that would make thickmaterial not work, go ahead and keep it in the basetype- spaghet helmets are everywhere

Its ok in the base type of armor as well, just ctrl ***shift*** f for ***all*** subtypes and make sure it isnt applied somewhere it doesnt fit.

**Comment by VictorVow** [comment]
Ah gotcha, that's been fixed now.

**Comment by FortSumter** [comment]
the sprite for the standard armored vest seems to suggest it covers the torso, but not the arms. Helmet also suggests protecting the head, but not the face. From what I understand, syringe only checks if an exosuit is worn and not what it covers (eg. exo slot covers the torso AND the arms from syringes). I'm sure it would be one of the most daunting tasks to code all the exosuits as I suggest, but it would make more sense.

**Comment by VictorVow** [comment]
Each exosuit only covers the appropriate areas (e.g. vest only covers torso), see the previous comments.

**Comment by eLeCtrOssSnake** [comment]
I would rather not do the kind of fuckery this is. So I am saying no.

**Comment by Isy232** [comment]
Now, giving syringe immunity to something like an armoured vest makes sense, until looking into it myself I actually assumed sec vests gave immunity so I would aim for the arms.

However, this gives immunity to the wardens jacket and HoS's cloak. This is a BIG FUCKING NO NO.

The HoS and warden shouldn't be roundstart syringe and xenomorph toxin immune with no drawbacks. IIRC they even have a spare trenchcoat and so does the warden.

There are security biosuits in sec as well as 3 hardsuits, all of which are thick clothing and provide immunity. Those have drawbacks for good reason.

**Comment by VictorVow** [comment]
It's coat not cloak. And warden's jacket doesn't protect legs. Plus their head is unprotected of course. Just use the little body doll at the bottom-right of your screen to aim at an unprotected area, simple.

**Review by zeskorion — APPROVED** [review]
some shit may need new flags

**Pull request merged**
