### PR TITLE
Moth Buff

### PR DESCRIPTION
**Pull request by Sparrowbird611**
## About The Pull Request

I see no better time to do this than now, so lets hop to it. This removes the moth's extremely sensitive eyes, so sunglasses now work for them.

## Why It's Good For The Game

There is literally no justifying a weakness this harsh on a race who's only advantage is a pair of wings that are nigh useless. Makes it so they don't completely suck, with situational weaknesses, and situational advantages.

## Changelog
:cl:
After a long number of moth servants got melted, the great lamp finally realized that the horrible eyes he made for his servants were the issue. Feeling merciful, (and tired of getting drinks spilled on him) he has decided to amend this issue.
balance: Moth people no longer have extremely sensitive eyes. They can no longer be flashed through sunglasses.
/:cl:

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
Yes, I actually did do this right now. Nothing like throwing napalm on a fire.

**Comment by ghost** [comment]
one sec ill show you a power move

**Comment by ghost** [comment]
it wont let me link a pic, but 

instead of removing moth eyes, go to eye.dm and scroll all the way down to moth eyes and change the flash value from -1 to 0, that means if anyone wants to add a recipe with moth eyes, anything to do with cargo bounties, or wants to give them some other kind of functionality then they wont have to readd them back to moff code

**Comment by Sparrowbird611** [comment]
Hmmm... good idea. I'll check that out later.

**Comment by ghost** [comment]
another more autistic approach would be to not change thr ryes at all but give moffs a line that buffs all objects with flash protection when they wear it, so they take more eye damage from flashes as intended but sunglasses and welding gear still work

**Comment by Sparrowbird611** [comment]
Sounds too autistic. I'll see if I can do the first idea though.

**Comment by Sparrowbird611** [comment]
Yo, any one know if there is an easy way to add a new commit, and change a current one? I don't have a lot of knowledge of PRs yet.

**Comment by Sparrowbird611** [comment]
Never mind, I figured it out. Apparently I'm blind and can't see the words that literally say "add more commits by pushing to the mothbuff branch"

I did it deb's way, but the results should be identical so.

**Pull request closed without merging**
