### PR TITLE
Meta & Delta Medbay rework

### PR DESCRIPTION
**Pull request by BriggsIDP**
## Medbay redesign

- [x] Remap meta medbay
- [x] Copy TG code for stasis bed directions

This pull request consists of a complete remake of the medbay area, focusing on the treatment area but also including the security post, virology department, genetics department, and other supplementary departments.

## Why It's Good For The Game

Better layout and design: The updated layout provide a more intuitive and user-friendly experience for players, making it easier for them to navigate, expand, and utilize the medbay facilities.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image

Capture

</details>

## Changelog
:cl:
tweak: tweaked DeltaStation2.dmm
tweak: added a jani room to medbay that CMO can access
add: Custodian zoning
add: Extra Stasis direction
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
Genetics is no longer med-sci hybrid. It might need to be medblue only.

**Comment by EvilDragonfiend** [comment]
What the hell is the jani room in medbay?

**Comment by St0rmC4st3r** [comment]
image
Please, no....

**Comment by BriggsIDP** [comment]
please describe the issue better!
currently layout has changed slightly 
image

**Comment by Rukofamicom** [comment]
> please describe the issue better!
 
 Med storage should not be one door away from public access, that's the issue.

**Comment by St0rmC4st3r** [comment]
>please describe the issue better

The stasis beds most definitely should not be this close to a high intensity passageway. People will swap places with doctors, interrupt their surgery that they do on stasis beds and get their legs sawn off my the mad doctor that got swapped places with 10 times during one surgery.

>currently layout has changed slightly

HOW IN THE SWEET NAME OF ALL THAT IS HOLY HAVE YOU MANAGED TO MAKE IT WORSE?! NOW THE DOCTORS WILL OPERATE WHILE STANDING **DIRECTLY ON THE PASSAGEWAY!**

**Comment by BriggsIDP** [comment]
> HOW IN THE SWEET NAME OF ALL THAT IS HOLY HAVE YOU MANAGED TO MAKE IT WORSE?! NOW THE DOCTORS WILL OPERATE WHILE STANDING **DIRECTLY ON THE PASSAGEWAY!**
image
Does this appease you? Swapped the stasis beds and sleepers so stasis are in lower traffic area, and have more room around them. sleepers have been moved up and a decal added indicating a 'safe' location to stand, though you need only press a few buttons on sleepers so it should never be an issue.

**Comment by St0rmC4st3r** [comment]
> Does this appease you?

My inner Med main is calm now. Off I go to my eternal slumber once more. <3

**Comment by Eric-01** [comment]
If you like redesigning things to improve them, I would suggest focusing on BoxStation first. IMO its medbay is the number one candidate to be thrown in the trash, as it is the worst of all the maps we currently have in rotation.

People here in the comments keep arguing that your new treatment area is too close to the main passage and right at the exit, and that's constructive criticism, I totally agree. BUT they seem to have forgotten for a moment that this is even worse on BoxStation. As a medical doctor, you stand in THE room that everyone has to enter or pass through if they need anything more than basic drugs from a chemist. Not to mention that going to the med storage is quite a journey. Tell your patient, who is vomiting blood and may die from some nasty disease at any moment, that all you have to do is go to the other end of medbay for a new health analyzer, and you will be back in no more than 2 hours 🤡

**Comment by BriggsIDP** [comment]
Someone else was looking into it; in fact that is what sparked me to do delta, and I don't want to step on their toes. But I'll definitely do it if they step down!

**Comment by Rustyfoxb** [comment]
image
Why is jani office now here?, it was fine where it was before.

**Comment by BriggsIDP** [comment]
Both exist at the same time, its just a convince for restocking

**Comment by Fronsis** [comment]
Does CMO office has a quarantine button that can enable shutters across all doors through the deparment? That would be neat

**Review by spockye — COMMENTED** [review]
image

disposals fuckery

image

Atmos fuckery

**Review by spockye — COMMENTED** [review]
image

i'd recommend rotating this one 

image

missing window

image

this corner feels REALLY weird

image

why have you done this


image

missing pipes (Meta)

image

missing disposals (meta)

image

missing disposals (delta)

image

zone fuckery

**Pull request closed without merging**
