### PR TITLE
cat butcher's revenge!

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
makes the cat butcher not lose aggro every 5 seconds 
the cat butcher has his rapid melee back, so he cant be facetanked as soon as he's found again. it still scales up though

## Why It's Good For The Game
the cat butcher isnt threatening anymore and it makes me sad
Also fixes unintentional aggrobloss
## Changelog
:cl:
balance: cat surgeon is a bit scary again.
Fix: cat butcher no longer loses aggro as easily
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
all the maint-rushing powergamers about to mald

**Comment by zeskorion** [comment]
> all the maint-rushing powergamers about to mald

hmmmmm... actually
gimme a sec

**Comment by zeskorion** [comment]
ugh its been a year and i forgot how to mapmerge

**Comment by OceanFish1** [comment]
> all the maint-rushing powergamers about to mald

Just get him behind a door lmao

**Comment by zeskorion** [comment]
> > all the maint-rushing powergamers about to mald
> 
> Just get him behind a door lmao

I could probably change that

**Comment by Tsar-Salat** [comment]
> > Just get him behind a door lmao
> 
> I could probably change that

give butcher aa.

ez fix

**Comment by Archanial** [comment]
How does roundstart threat in maintenance that only exists for the felinid memes help the roleplay?

**Comment by zeskorion** [comment]
> How does roundstart threat in maintenance that only exists for the felinid memes help the roleplay?

The cat butchers is fun and interesting.  By making him threatening, rushing in and powergaming maintenance is discouraged, because there can be a threat within. It also gives security something to do early in a round, and gives medical something to do (that being de-catifying his victims). The cat surgeon in its default states can be dealt with by a lone crewmember, but, in the event it claims a few victims, it becomes a threat that often necessitates a bit of departmental cooperation to deal with. It occupies the same niche an antag does- causing a bit of a snag that spices up a round, withiut totally hijacking it.

And, being an AI simplemob,  he cant just go murderbone. He can be entirely avoided if people dont engage him

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
