### PR TITLE
Portable pump and scrubbers can now be ordered by cargo.

### PR DESCRIPTION
**Pull request by The-Moon-Itself**
## About The Pull Request
This pull request adds two new crates to cargo. One contains two portable pumps, the other contains two portable scrubbers. The can both are large crates that can be ordered under the engineering section on the supply console for 1500 credits.

## Why It's Good For The Game
There is no other way to currently get more portable pumps and scrubbers. Allowing these machines to be ordered at cargo can allow for atmos techs and toxin scientists to get more if they are expanding their pipe networks or somehow lose or destroy the roundstart ones.

## Changelog
:cl:
add: Portable pump and scrubber crates available at cargo.
/:cl:

### CODE REVIEW

**Comment by The-Moon-Itself** [comment]
something went wrong with my source control, let me fix this real quick.

**Comment by KubeRoot** [comment]
The changes in the PR look good to me, what are you saying went wrong?

**Comment by The-Moon-Itself** [comment]
A bunch of random lines in files changed were replaced with identical ones with extra whitespace that I didn't remove gone. I closed the PR quickly to look at that to make sure nothing important broke, and it seems fine now.

**Comment by KubeRoot** [comment]
I suspect it was either your text editor or your git client removing the redundant whitespace, and I'd say that's a good change.

**Pull request merged**
