### PR TITLE
Bluespace SupplyPod no longer destroys contents

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Removes explosion from the upgraded express cargo console bluespace supply pod. The explosion was destroying ordered contents as the pod arrived, it still does this for the default pod without upgrade.

I hope this is not some intended behavior from a master game designer that is just too deep for me to understand.

## Why It's Good For The Game

It makes the supply pod system actually usable as now it doesn't delete/kill contents of crates it's supposed to be delivering. Unupgraded version is still completely unusable and a joke.

## Changelog
:cl:
fix: Upgraded cargo express supply pod no longer destroys ordered items.
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
change the changelog to specificy the upgraded version to not confuse people

**Comment by Cenrus** [comment]
Can you fix the crate contents getting burnt instead? It's a bug.

**Comment by ghost** [comment]
> Can you fix the crate contents getting burnt instead? It's a bug.

So you're telling me that the pods exploding and destroying the very beacons they use to navigate is an intended and purposefully designed feature?

**Comment by ghost** [comment]
> So you're telling me that the pods exploding and destroying the very beacons they use to navigate is an intended and purposefully designed feature?

It is, here is the PR that added this feature.
https://github.com/tgstation/tgstation/pull/33436

It specifically states this:**"The explosion exists to act as a secondary act of balance: the drop pod is intended to be used for a few VIP deliveries. Ordering in bulk will still require use of the shuttle, unless you are prepared to fix the shit out of an explosion-riddled cargo."**

**Comment by ghost** [comment]
> > So you're telling me that the pods exploding and destroying the very beacons they use to navigate is an intended and purposefully designed feature?
> 
> It is, here is the PR that added this feature.
> [tgstation/tgstation#33436](https://github.com/tgstation/tgstation/pull/33436)
> 
> It specifically states this:**"The explosion exists to act as a secondary act of balance: the drop pod is intended to be used for a few VIP deliveries. Ordering in bulk will still require use of the shuttle, unless you are prepared to fix the shit out of an explosion-riddled cargo."**

That's so incredibly stupid I don't even feel like arguing against it.

**Pull request closed without merging**
