### PR TITLE
Contractor Balance Changes

### PR DESCRIPTION
**Pull request by FriendlyContractor**
## About The Pull Request
This pull adds radio jammer to standard contractor loadout, adds chameleon kit and rad laser to their random items starting pool and removes energy dagger, karate scroll, binary encryption key, syndicate sentience potion from it.

As of now contractor is not guaranteed to start with a silencing equipment which means unless you got lucky with equipment your kidnaping victim will yell on the radio as soon as you stun them immediately summoning security, validhunters and AI to your location. Radio jammer being part of standard loadout will help solve the issue and make contractor kit significatly more enjoyable to play.

Energy dagger and karate scroll are largely made obsolete by your contractor baton - why would you use dagger or karate when you have excellent baton which does the job better. Binary encryption has some rare case use to contractor such as when AI is an IAA after you or if you subvert the AI however its too rare to justify keeping it in starting items pool. Syndicate sentience potion can be uselfull however there is a good chance no ghost will take the role and its only uselfull on slimes unless you plan to waste time in xenobiology instead of contracting.

Rad laser is an inexpensive stealthy knockout tool and chameleon kit is and upgrade over your starting chameleon kit allowing you to disguise fully. I belive both items fit the contractor theme well and can somewhat fill the gap after removed items so i decided to add them

## Why It's Good For The Game
Makes contractor kit less RNG dependant and fun to play by adding radio jammer as part of standard loadout and tweaks its starting item pool to make sure you dont get useless items

## Changelog
:cl:
tweak: Radio jammer is now part of contractor kit standard loadout
tweak: Tweaks contractor kit starting items pool by removing useless items and adding some new
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
I don't like this, the contractor kit was added because veteran players had nothing to do, this is meant to be a challange.

**Comment by VictorVow** [comment]
Random items pool changes are good.

>  To compensate for radio jammer being standard loadout contractor kit now only has 2 random items instead of 3.

Fuck that I'd rather have the 3 items. Just add radio jammer to the pool too. It shouldn't be easy captures guaranteed.

**Comment by FriendlyContractor** [comment]
Its still as challenging as it was before. My PR just helps reduce RNG dependency by ensuring contractor starts with a silencing item which is what most contractors would want so you dont have to spend time which is short on bee coming up with alternate solutions such as sabotaging comms or making EMP grenades if you dont get lucky with starting items

**Comment by utilbird** [comment]
As of now, using contractor kit is a death sentence unless you get radio jammer or something else to prevent them from talking when kidnapping them. The only viable strategies without a radio jammer was either using a syringe gun or beating them into crit. The latter had the issue of salty players deathgasping to avoid capture.

Imo this is a great PR, it keeps the contractor as a difficult job that maintains some randomness while also making it significantly more fun to play :)

**Comment by heepox** [comment]
for me it all depends on if miners are mining for uranium fast... getting that mute toxin in them first is usually so goood, but yes RNG item changes are good. Karate is underwhelming as it is and pot is basically useless same with encryption. I would still rather have the 3 RNG items just that each item comes from a sepeare pool 1 for silencing tools (emp flashlight, sleepy pen, radio silencer and such) 1 for deadly tools (hand held weaponry or skills like karate/combat gloves plus) and 1 for consumables like x4/c4/medkit or such.

**Comment by Blueturbo47** [comment]
+1, I usually get stupid stuff like karate and energy dagger when I go, contractor and it really doesn't help at all, though emp flashlight might be better because it adds more of a challenge and can still silence radio, it also uses less tc.

**Comment by PowerfulBacon** [comment]
Should just keep it at 3 random items imo, since you aren't going to use all 3 items and add the radio jammer on top

**Comment by FriendlyContractor** [comment]
> 
> 
> Should just keep it at 3 random items imo, since you aren't going to use all 3 items and add the radio jammer on top

If person who is in charge of accepting pull requests(I must admit i am not very fammiliar with github thing and just wanted to request some balance changes instead of whining on forums for somebody else to do them) is okay with straight forward contractor buff you suggest i would be more than happy with it.

However, it is worth considering that that with contractor kit you are already getting close to 20TC(Thought with some randomness making it less valuable i guess? ) worth of items with ability to earn quite a lot more via contracting. This could potentialy result in players buying contractor kit for its unique items rather than to fulfill contracts. Im mostly playing devil's advocate here and dont belive one cheap item would make any bad impact on the game and straightforward buff would be a good thing but still must mention it here

**Comment by Blueturbo47** [comment]
> If person who is in charge of accepting pull requests(I must admit i am not very fammiliar with github thing and just wanted to request some balance changes instead of whining on forums for somebody else to do them) is okay with straight forward contractor buff you suggest i would be more than happy with it.

Pretty sure you have to request a review using the right bar thing, no idea how though.

**Comment by PowerfulBacon** [comment]
I'd be perfectly fine with just adding it straight up, it's 3 TC and contracting is still difficult but high reward. Almost 20 TC of random items that you can't choose from is significantly less worth than 20 TC of items you can pick from, so I don't think that buying contractor to not contract will become a meta.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
