### PR TITLE
Adds TubeStation

### PR DESCRIPTION
**Pull request by llol111**
## About The Pull Request

This PR adds the long anticipated new map, TubeStation to the Game.
Spawned as a shitty joke in the form of RussianCokes drawing in the acompanying Forums Thread, it has become a real:tm: map.
https://forums.beestation13.com/t/tubestation-development-thread/16229/

i had some help with the decaling from Spockye
which is to say he did the decals

## Why It's Good For The Game
More variety in maps is always good. Though people may not admit it, playing on the same maps forever gets stale.

## Testing Photographs and Procedure
<details>
<summary></summary>

image

</details>

## Changelog

:cl: llol111, Spockye
add: Adds TubeStation
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
image

**Comment by FriendlyContractor** [comment]
While i of course can appreciate the effort that was put into it i unfortunately don't think by looking at it thats its going to be very fun playing. Sorry

**Comment by ike709** [comment]
If you intend for this to be an actual playable map, then there really needs to be non-maintenance hallways connecting most of the station. In addition to... probably a lot of other work.

One of the iterations of asteroidstation was able to pull this off while also being a good and playable map.

**Comment by MNarath1** [comment]
> If you intend for this to be an actual playable map, then there really needs to be non-maintenance hallways connecting most of the station. In addition to... probably a lot of other work.
> 
> One of the iterations of asteroidstation was able to pull this off while also being a good and playable map.

dunno the fact that the hallways of the station are not connected and only maint tunnel connect them(beside the tubes) otherwise is kinda the thing of this map trough i could see this become really annoying especially with any delivery security arresting people pandemic bringing back people and so on.

**Comment by RussianGenCoke** [comment]
Holy shit. It's here.

> If you intend for this to be an actual playable map, then there really needs to be non-maintenance hallways connecting most of the station.

That's... the point of Tubestation though. The main transport is tubes. I get what you mean but the joke was a tube based transport map.

**Comment by llol111** [comment]
We're workshopping it
I may have to make it less funny to make it not CBT to play
but i will not have this tossed asside, put way to much effort in already for that

**Comment by Raven-Industries** [comment]
Look at all these philistines not even giving it a chance before dismissing the glorious work of art that is Tubestation. Shameful, no appreciation for artistry anymore.

**Comment by DerpiestBruh** [comment]
tubestation if real

**Comment by Fronsis** [comment]
Clown and Mime literally spawning on a bathroom instead of a theatre backstage (there's not even a theatre lol)

Sure meme is haha but it gotta follow the classic standards tbh, as i see it most people will hang out to the left and it'll be a pain in the ass if you have to carry injured/prisioners around

**Comment by Mat05usz** [comment]
Looking at it very briefly these are some problems I see:

- Command looks awkard, slightly offset towards north-east with only one real connection to the rest of the station, which for some reason goes to arrivals.
- I'm not a fan of those empty, 4 width hallways. They probably look very empty and boring in-game.
- No SM is a big meh, singulo/tesla are boring and practially maintenance free. It either goes ape and destroyes the station or literally does nothing, also offers no customization, bad choice.
- There is so much unused space in the middle, maybe instead of that weirdly placed command, place a 'hub' in the middle, maybe in a form of an asteroid where all tubes converge?

Edit: I think the station would benefit if you gave it an asteroid vibe, make it into several small asteroids turned into departments that are then connected via tubes etc. Cause now it looks a bit weird and 'weak', like it'd collapse on itself very quickly.

**Comment by williamcll** [comment]
> If you intend for this to be an actual playable map, then there really needs to be non-maintenance hallways connecting most of the station. In addition to... probably a lot of other work.
> 
> One of the iterations of asteroidstation was able to pull this off while also being a good and playable map.

well is asteroidstation in rotation?

**Comment by Fikou** [comment]
as a joke its pretty funny
as an actual map:
the whole map zoomed out looks horrifying, although i guess players wont be seeing it like that
the design of the departments themselves (other than command) is pretty good, they are fine designs.
the map suffers extremely in the other parts though. the maints are really uninteresting and bad, the hallways are meh (4 tiles wide isnt a good choice, makes them feel empty) and tubes are an extremely tedious form of transport, especially if they arent the dispenser ones, and they are uninteresting as well, you can have stuff like tube platforms and hubs in space to make the travel between departments more interesting
i'd say you should lean more into the tube gimmick with stuff like what i noted above, or cut it alltogether and smush it together with remade hallways and make it more of a classical station

**Comment by dragomagol** [comment]
image

https://github.com/BeeStation/BeeStation-Hornet/blob/21179714a589e46016a5bdce827c2e78be6e2e9a/code/modules/mapping/mapping_helpers.dm#L235-L239

Each of these dead body placers will place 2 dead bodies in random morgue trays; having 4 helpers will fill the morgue with 8 bodies.

**Comment by Zenithrium** [comment]
i really like the idea for this map and asteroidstation / cerestation, but i feel like it suffers from weird placement of the different departments. not to overstate the importance of my favorite department, but i think the most accessible and therefore central department should be medical, not command. if not medical, i think it should be civil - botany can do quite a lot, and giving more traffic to the bar, cafeteria and chapel i think would be nice

**Comment by PowerfulBacon** [comment]
Is this a serious map to actually go in rotation?

**Pull request closed without merging**
