### PR TITLE
Doesn't remove circuits

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
A healthy alternative to just effectively killing circuits as a whole
Removes reagent and grenade primer circuits to stop bomb drones
hypo drones were not even a problem but they're doubly gone now too

## Why It's Good For The Game
- Circuits offer a ton of gameplay potential and a huge avenue for advanced players
- Problems should be addressed individually as they come rather than nixing circuits all together
- Removing circuits is generally unpopular despite it being super niche
- People are still working to fix them

## Changelog
:cl:
del: Removed chemistry and grenade functionality from circuits to prevent bomb drones
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
> A healthy alternative to just effectively killing circuits as a whole

no
half measure bad

**Comment by jlsnow301** [comment]
> no
> half measure bad

anything remotely resembling a rework or feature would take actual months just to merge so i disagree

**Comment by aidan-bowman** [comment]
no no pls i'm almost done making a change i made that forces you to have id for the strong modules pls i just need to test it before pring

**Comment by OceanFish1** [comment]
Holy fuck it's a circuit civil war now

**Comment by OceanFish1** [comment]
> Holy fuck it's a circuit civil war now

More like circus actually you better choose between full removal or full rework

**Comment by Rukofamicom** [comment]
Would rather a full removal until a full rework, but honestly I'll take what I can get at this point.

**Comment by MNarath1** [comment]
> Would rather a full removal until a full rework, but honestly I'll take what I can get at this point. 

A full removal would actually make a code review harder honestly why simply cause you suddenly cannot see where the changes are because its all "new" so you cannot distinguish easily between changes and stuff thats already there

**Review by francinum — APPROVED** [review]
The other PRs are staying open.

**Comment by jlsnow301** [comment]
> The other PRs are staying open.

sad. here i was thinking I'd be polite enough not to link the others. that was a mistake.

**Comment by optimumtact** [comment]
lol

**Pull request merged**
