### PR TITLE
Removes lavaland GPS signals.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

It removes the GPS signals from:
Necropolis Tendril.
Blood drunk Miner.
Legion.
Hierophant.
Swarmer beacon.
Elites.
Bubblegum.
Ash Drake.
Colossus.

## Why It's Good For The Game

It was Rukos idea.
image

## Changelog
:cl:
tweak: Removes the GPS signals from: Necropolis Tendril, Blood drunk Miner, Legion, Hierophant, Swarmer beacon, Elites, Bubblegum, Ash Drake, Colossus.
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
i like the not rushing fuana thing but I don't wanna be mining then suddenly I see bubblegum and die when I don't even wanna fight fuana

**Comment by ghost** [comment]
> i like the not rushing fuana thing but I don't wanna be mining then suddenly I see bubblegum and die when I don't even wanna fight fuana

There is a fair amount of time between seeing the Megafauna and it starting to attack you.

**Comment by ToasterBan** [comment]
> > i like the not rushing fuana thing but I don't wanna be mining then suddenly I see bubblegum and die when I don't even wanna fight fuana
> 
> There is a fair amount of time between seeing the Megafauna and it starting to attack you.

i feel a form of "radar" that beeps or something when megafuana are near would be a better alternative to gps signals

**Comment by PowerfulBacon** [comment]
> ## Why It's Good For The Game
>
> It was Rukos idea.

damn sold

**Comment by Moccha-Bee** [comment]
Ah yes maybe you din't actually think about what was going to be the result of removing the gps signals, but miners are just going to avoid mining even more to search for the megafauna wasting more time and getting less resources, It's like every problem is a nail and every solution a hammer jesus fuck.

Also the miners who rush fauna go for the hiero first, as its the best mining tool currently in the gaming, and use it to get to other fauna and mine quicker, so you are just making it harder for good miners to actually mine 
image

**Comment by ghost** [comment]
> Also the miners who rush fauna go for the hiero first, as its the best mining tool currently in the gaming, and use it to get to other fauna and mine quicker, so you are just making it harder for good miners to actually mine

The Hierophant staff isn't good for mining, it has a long cooldown the closer you click to your character, the best mining tool by far is the advanced plasma cutter, nothing even comes close to it.

**Comment by Moccha-Bee** [comment]
> > Also the miners who rush fauna go for the hiero first, as its the best mining tool currently in the gaming, and use it to get to other fauna and mine quicker, so you are just making it harder for good miners to actually mine
> 
> The Hierophant staff isn't good for mining, it has a long cooldown the closer you click to your character, the best mining tool by far is the advanced plasma cutter, nothing even comes close to it.

Holy fuck you just proved my point that people who want this changed have never killed a megafauna in their lives 

The hierophant literally destroyes an 3x3 area , needs not recharging and has a 1 second cooldown, has a large cross shaped attacked which is good for opening channels. Way better than the advanced plasma cutter specially for vein mining, but you wouldn't know that you never killed it or used it in your life 
image

**Comment by ghost** [comment]
> The hierophant literally destroyes an 3x3 area , needs not recharging and has a 1 second cooldown. Way better than the advanced plasma cutter specially for vein mining, 

It is not, the advanced plasma cutter has a longer range while always having the same cooldown, and it allows you to move around and subsequently mine faster due to that.

And if you really care that much, I have over 100 hours on the Shaft Miner role and killed lots of megafauna, and I would appreciate it if you could keep the discussion civil or I'm just going to ignore and block you in the future since I have no interest to discuss things with people like you.

This is also not the topic of this pull request, so we both should drop it, I'm not gonna continue this discussion with you.

**Comment by Moccha-Bee** [comment]
> 
> I have over 100 hours as Shaft Miner if you care that much, and I would like it if you could keep it civil or I'm just going to ignore and block you in the future since I have no interest to discuss things with people like you.

I stated obvious facts about mining and clearly don't even know what you are talking about, 100 hours means nothing if all you did was just use mine rock for all that time. 
> I'm not gonna continue this discussion with you.

Ah yes the i have no arguments move.

**Comment by Ruediger4** [comment]
I'm literally logging in just to say that this would be awful, at least in my opinion.

GPSs already have rather low uses, and at this rate it'd only be left for space exploration (which they ain't even that useful 'cause either one or two space ruins have a GPS signal, or you're gonna print and toss 10 into space and then pray to RNJesus that it's a good ruin.) which people only bother doing to get Whiteship.

Knowing where megafauna is is both good for the miner who likes to mine, and the one who likes to do lil' bossfights against the megafauna. I personally never play miner, but when I do, I just avoid all megafauna signals like it's hot.

> There is a fair amount of time between seeing the Megafauna and it starting to attack you.

_Whoops my plasma cutter beam just straight up accidentally hit bubblegum, guess I die.
Whoops, space lag, ash drake AI processed my presence and now i'm a husk.
Whoops, I literally missed to see (insert megafauna) in the corner of my screen and i wasn't prepared, guess I die._

This is just a weirdly non-thought out fix to a problem no one brought up, who has a problem with miners knowing where megafauna is? Do you wanna make GPS that redundant? 

**Y'all hate megafauna being rushed?** Make them appear after X minute mark, or make it an actual type of treasure hunt, maybe make tendrils have a chance to also drop a pinpointer that points to a specific type of megafauna nearby instead. Make it engaging instead of just a blind hunt.

If you at least don't nudge the miners towards a specific direction if they wish to hunt for ash drake or whatever, they are either gonna go around in circles all day, not mining at all, or they'll just forget about megafauna and get dabbed on by them. It's basic game design. 

**Nudge'em towards the fun. Don't discourage it. Don't make it a tiring scavenge hunt, make it a quest.**

Sincerely, a GPS and exploration fan.

**Comment by utilbird** [comment]
@BeloneX 
image

When did he say remove **every** GPS signal...

**Comment by ghost** [comment]
> When did he say remove **every** GPS signal...
image

**Comment by Dingo-Dongler** [comment]
> **Nudge'em towards the fun. Don't discourage it. Don't make it a tiring scavenge hunt, make it a quest.**

Terraria style items/methods/random events for spawning megafauna?

**Comment by TheFakeElon** [comment]
> image

Ruko moment

**Comment by ghost** [comment]
Mining with advanced plasma cutters, I have often times accidentally hit a megafauna through walls because I was not looking at my GPS. Instead of removing their GPS signals, which would most likely just make miners spend even more time not mining, I recommend a different change:

Add lootbox keys (rename as see fit) into the mining vendor that must be bought for mining points, make the megafauna crates invincible until unlocked. Now miners have to actually mine ores to get their loot.

**Comment by PowerfulBacon** [comment]
> 
> 
> > Also the miners who rush fauna go for the hiero first, as its the best mining tool currently in the gaming, and use it to get to other fauna and mine quicker, so you are just making it harder for good miners to actually mine
> 
> The Hierophant staff isn't good for mining, it has a long cooldown the closer you click to your character, the best mining tool by far is the advanced plasma cutter, nothing even comes close to it.

The hierophant is easily the best mining tool, better than plasma cutters.
Sure plasma cutters can mine at just about the same speed as you can run, but the hierophant mines in a 3x3 area as fast as you can run, tripling the area you mined while still being able to run at speed and mine

**Comment by ghost** [comment]
> The hierophant is easily the best mining tool, better than plasma cutters.
> Sure plasma cutters can mine at just about the same speed as you can run, but the hierophant mines in a 3x3 area as fast as you can run, tripling the area you mined while still being able to run at speed and mine

That is not how mining works, you will always mine slower with a hierophant staff than with a cutter, since you can only collect in a 1x1 area by walking over it. A cutter is a straight line, you run forward and collect ores, the staff you have to first mine out a large area and then walk back and forth again to collect ores.

Using hierophant staff for mining makes no sense.

**Comment by PowerfulBacon** [comment]
> That is not how mining works, you will always mine slower with a hierophant staff than with a cutter, since you can only collect in a 1x1 area by walking over it. A cutter is a straight line, you run forward and collect ores, the staff you have to first mine out a large area and then walk back and forth again to collect ores.
> 
> Using hierophant staff for mining makes no sense.

Hierophant staff is easier to obtain early game.
Hierophant staff can mine as fast as you can move (Essentially as fast as the cutter).
Hierophant staff doesn't require a massive amount of plasma to mine.
Hierophant staff has the added benefits of being able to teleport back to the station to deposit instantly.

**Comment by ghost** [comment]
> Hierophant staff is easier to obtain early game.

Fighting megafauna is not easier than doing literally nothing, that is waiting for science to press a button for mining research in the first few minutes of a round.

> Hierophant staff can mine as fast as you can move (Essentially as fast as the cutter).

It cannot, as you need to click for every tile and unless you're running an autoclicker, you will bump into a rock before mining it due to latency and your own clicking speed. It mines a 2x3 area in front of you, meaning you need to move sideways/backwards/forwards to collect what you mined. With cutter you only move forward and click once per a long line of ores, no backtracking or bumping into stone or frantic clicking required.

> Hierophant staff doesn't require a massive amount of plasma to mine.

Neither does a plasma cutter - 10 sheets of plasma for full charge, which is about 3 plasma tile deposits.

> Hierophant staff has the added benefits of being able to teleport back to the station to deposit instantly.

That can be combined with the efficiency of a plasma cutter and is not an argument for mining speed.

**Comment by katebishop49** [comment]
laughably awfull change lol, megafaunas have gps signals to stay AWAY from them, either make them not attack on sigth or close the request.
edit:nice alt lol

**Comment by FortSumter** [comment]
I'd rather we remove hierophant than remove all the GPS signals, just my unpopular opinion. I don't mind the GPS and gives miners an incentive to pick one up so if they die stupidly they can be recovered by cargo. If you plan on greenlighting this, at least remove the miners being gibbed on death by most megafauna so cargo can potentially recover them, or have their organs, heads and gear remain like when the ash lizard tendril eats corpses.

**Comment by VictorVow** [comment]
I'd like video proof that hierophant staff lets you run at full speed because when I used to get it it was nowhere near as good as advanced plasma cutters.

**Comment by ghost** [comment]
> either make them not attack on sigth.

They don't, you've got about 3 - 5 seconds to run away before it starts attacking you.

**Comment by Ruediger4** [comment]
> > **Nudge'em towards the fun. Don't discourage it. Don't make it a tiring scavenge hunt, make it a quest.**
> 
> Terraria style items/methods/random events for spawning megafauna?

Honestly anything that modifies the mechanic rather than outright removing it. That'd be honestly fun despite me not playing Terraria. Needing certain materials to "summon" a megafauna would actually be nice and fun for a change.

However, this change is basically taking the OPPOSITE route that Fallout NV took for making the world more engaging than Fallout 3's.

**In Fallout 3,** you had a few quests that were extraordinarily fun, but they were hidden in a corner of a map/hard-to-reach places with no apparent path towards them/in a very 'boring' looking part of the map. Many quests which could be resolved in a very fun/interesting way needed you to go to the other part of the map and read ONE note in a building unrelated to the quest, WITHOUT ANYONE TELLING YOU. Without the game **pointing at you towards the fun.** It made the game's world look empty, boring, or mediocre.

**Fallout New Vegas, on the other hand,** has most quests indirectly tied with others; most require you to travel to a new place, or a place you visited but just ignored and dismissed as irrelevant. Going to those places, you get a new quest, new people, and maybe even shit to help you do other quests later on. The map has landmarks, or buildings or stuff that, simply put, **attract players towards the fun.** Even the damn quests guide you to other quests so you can find more quests.

Removing GPS signals for megafauna is literally going to backfire on the **miners**, the megafauna hunters, the **NEW PLAYERS who have NO IDEA what the fuck killed them or how to avoid it**, the GPS is gonna end up even MORE obsolete than it already is, and you basically fixed an issue that never existed by also creating 5 more.

Unga says no.
Unga likey GPS signal.

> They don't, you've got about 3 - 5 seconds to run away before it starts attacking you.

I'ma call BS on that but it probably depends on the player's ping/server delay and other stuff, cause I've had simplemobs jump me like 1.5 seconds after spotting me.

**Comment by ghost** [comment]
> I'ma call BS on that but it probably depends on the player's ping/server delay and other stuff, cause I've had simplemobs jump me like 1.5 seconds after spotting me.

Do not try to misinterpret what I wrote, I specifically stated this about Megafauna, not all simple mobs.

**Comment by LivingBatteryBox** [comment]
I can get the idea behind removing the GPS signals from megafauna (even though it will lead to a lot of miners dying from accidentally hitting a megafauna with a plasma cutter). What I do not understand is why they would remove tendril signals. Tendrils are needed for legion cores and goliath plates. Removing tendril GPS will make resource gathering as a miner annoying.

**Comment by ghost** [comment]
> I can get the idea behind removing the GPS signals from megafauna (even though it will lead to a lot of miners dying from accidentally hitting a megafauna with a plasma cutter). What I do not understand is why they would remove tendril signals. Tendrils are needed for legion cores and goliath plates. Removing tendril GPS will make resource gathering as a miner annoying.

I made this pull request because of suggestions that Ruko made, if you want changes done to it you can create your own pull request, I have no intentions of maintaining this pull request and I do not care what happens to it.

**Comment by hotimep** [comment]
maybe instead of taking away the fun part of mining harder we make the mining part of mining more fun

**Review by francinum — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
Honestly, I think this is a bad idea. The keys for necropolis crates was a much better idea, and the GPS signals are almost vital on many regards.
The problem you are trying to solve here is that miners aren't getting enough materials and only using the job to hunt I assume.
The thing to me that this is going to do, is make it so those miners who only hunt megafauna will just plasmacutter back and forth and never return to the station and make it completely impossible for anyone who doesn't solely focus on hunting to find any loot, in turn encouraging miners that like to mine but also grab tendrils on the side when they are nearby to just either only focus on mining, or only focus on searching for megafauna / tendrils.
Most players miner to the megafauna, collecting resources and then return to the station after they kill what they were going for; depositing materials. Sure, this will force them to collect more materials, however, the materials per second mined isn't changing, the only thing that's changing is the time between depositing into the ORM which will be heavily increased.

If you want my opinion on what I think is a good solution, then some things like nerfing armour and things like the hierophant in high pressure environments like the station would be a good start, or adding the necropolis keys (A good incentive to actually collect resources and bitch at the scientists for not upgrading the ORM 1 hour into the round). Or maybe a way to tell when resources are getting low again, since the biggest problem is miners returning to the station after they have their loot and not going back to lavaland again.

**Comment by Sinmero** [comment]
Removing signals is a bad idea. Megafauna might spawn in places where it would be very hard to find it without gps. Or it can be just behind the wall when you hit it with plasmacutter. Sometimes we have bubblegum ~50 meters from mining base.

Mining is a singleplayer pve experience with nearly nonexistent interaction with other players. Mining itself is repetitive and gets old quick. Main incentive to play miner is exploration, hunting and loot. Make those worse > less incentive to play miner.

> If you want my opinion on what I think is a good solution, then some things like nerfing armour and things like the hierophant in high pressure environments like the station would be a good start, or adding the necropolis keys

Armor nerf = more dead new players. Just regular fauna can kill you if you are not careful or using a crusher. Hiero is not as good in pvp as people make it look like, its fairly easy to evade. Just shoot the user with disabler or face tank it and stunbaton or just shove or slip them.

I like the idea of adding necropolis keys if that means removing the chasms. (i hate chasms)

Overall i dont think that mining is in a bad place rn. Miners do their thing and mine along the way and if they dont mine enough we have bluespace miners as an alternative.

**Comment by Vexylius** [comment]
why did you make a vote for that, you really expected any positive votes?

**Comment by PowerfulBacon** [comment]
> why did you make a vote for that, you really expected any positive votes?

No

**Comment by ghost** [comment]
> > why did you make a vote for that, you really expected any positive votes?
> 
> No

You should have just closed this pull request then.

**Comment by Sinestia** [comment]
I think a better change would be to make every signal have the same label

Meaning you know where things are, but you don't know what they are until you actually check them out. 

might be an amicable compromise to hit the mining speedrunners a bit without making it too much of a hell

**Comment by Bastian0930** [comment]
Ruko, if you are reading these comments, I'm genuinely curious how much you've played miner, if any.  This was your idea, wasn't it? It seems terrible, for the many many reasons people have put out.

**Comment by Bastian0930** [comment]
@Rukofamicom

**Comment by Ruediger4** [comment]
> Ruko, if you are reading these comments, I'm genuinely curious how much you've played miner, if any. This was your idea, wasn't it? It seems terrible, for the many many reasons people have put out.

the PR is dead anyways. Belone already said he wouldn't keep it updated or anything, that he doesn't care, and it has a literal 20/80 positive/negative ratio. 10 positive votes vs 70 negative

shit is dead

**Pull request closed without merging**
