### PR TITLE
Re-Adds Public Autolathes

### PR DESCRIPTION
**Pull request by Isy232**
## About The Pull Request

To those who have never seen them, from what I know until about a year or so ago there used to be autolathes accessible to the public built into R&D. 
https://cdn.discordapp.com/attachments/419192460909215756/694499266407694426/unknown.png
This PR re-adds those, see image for an example of one.

## Why It's Good For The Game

The reason they were removed from /tg/ about a year and a half ago:
> Public autolathes are part of the large amount of resource-creep which became popular with the rise of multiple maps and map rotation. Having an over-abundance of resources, tools, and gear available to the crew stifles meaningful player interaction and conflict.
> 
> Autolathe goods being locked behind cargo's doors would require players, once again, to interact with their fellow crew on cargo duty in order to receive what they want (or to break in and evade security). We survived for years with this mechanically being the case, and I believe it would only be logical to return to it.

Its been about a year and a half and I can say for certainty that this PR does not add any RP value and only forces meaningless and boring interactions. 

Cargo technicians are often busy pulling crates or collecting bounties and do not want to sit at the desk and press a few buttons on a machine to make whatever items you need. Most of the time you have to call a cargo technician over comms to come over to the autolathe to print you what you need or just break in if nobody responds. It is an exceptionally unrewarding job as there is no skill in it at all and everyone knows the person could have just used the autolathe themselves and been done far quicker.

As said by someone else in an argument against the PR to remove them:
>The easy access to low level tools is a lot healthier for a lot of assistant players because it removed the mechanic of making a roundstart 15 second mad dash for x, y, and z before someone else took it, which just caused stagnant interactions and headaches trying to catch back up to the starting point of the gimmick you had in mind

I would also like to add that's its healthier to more than just assistants, its good for almost everyone who wants tools or many of the various other items that can be constructed at the autolathe.

Also, if you want player interaction, the autolathe will create some by itself. Perhaps there will be a security guard standing nearby to make sure nobody hacks it and prints ammo for their syndicate weaponry. Perhaps when waiting in line or for someone from science to add more materials to the lathe you could start a chat with anyone else waiting or standing nearby.

The public autolathe is healthy for the server because it provides players with a lot of convenience when they just need a single quick item to do a job. It should also heavily lower the need to rush tool storage at the start of the shift as now basic tools won't be rare.

## Changelog
:cl:
add: Re-Adds public autolathes to all stations.
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Fix conflicts

**Comment by Crossedfall** [comment]
Can you expand on this?
> forces meaningless and boring interactions.

If the complaint is that they have to talk to someone to get stuff, I don't really see how this is an issue. There's quite a few interesting ways to go about that situation, if the assistant meta is to be boring about it, that says more about assistants than anything else.

**Comment by Isy232** [comment]
> Can you expand on this?
> 
> > forces meaningless and boring interactions.
> 
> If the complaint is that they have to talk to someone to get stuff, I don't really see how this is an issue. There's quite a few interesting ways to go about that situation, if the assistant meta is to be boring about it, that says more about assistants than anything else.

The issue is that there is nothing else to do in the room with the autolathe in cargo other than maybe check the bounty console or pass by the room on your way somewhere. Nobody wants to have the job of just push button on autolathe when someone comes by. This is the needless and boring interaction. 

It is also unlikely for any roleplay to occur during this as the cargo technician will have to be in menus for the usage of the autolathe as well as busy picking up the items and putting them onto the table if they decide to do it themselves.

Most often cargo just lets you in after you mention it to them or you break in because nobody responds to your calls.

There isn't an issue in asking for specialized gear like a bag of holding or a chemical. In both of those cases either science had to choose to spend research points on the bag of holding or the chemist has to use their knowledge of chemistry to create the chemical.

You also have to wonder if you can trust this individual with the bag of holding or a certain chemical, possibly sparking discussion of what they need it for and if they know the dangers of the item and if their reason isn't good, perhaps try to convince them they do not need the item and the materials or time would be better spent elsewhere.

If an assistant wants a crowbar and a flashlight, a scientist wants a welding helmet or an engineer wants a conveyor belt there is nothing interesting about these items. Perhaps you might ask them what they are using them for, but in most cases you likely have no reason to care.

There is also the possibility of someone hacking the autolathe or printing something suspicious. Perhaps you should ask them why then or call security over if you think it is important. This can be an interesting scenario.

Putting the public autolathe in R&D works because there is often a scientist in R&D or one who will be coming there shortly if you need something more added to it.

Its always a pain to realize you need another of some basic item, realize you have to go to cargo and hope there is a technician willing to help you get said item from the autolathe or to break in.

I've been playing for about a year now without public autolathes and I can defiantly tell that the original argument for their removal is crap, there is no meaningful player interaction in asking someone who likely wants to be earning credits by pulling crates to go over to a machine in the corner of their room, press a few buttons and give you a welding tool.

Public autolathes also encourage a healthier type of assistant. I sometimes like to play assistant to do a gimmick because you do not have any responsibilities to worry about. However because assistants have no access they either have to bother people with their requests for non-essential items, which can take a lot of time and ruin your gimmick idea by taking so long that the shuttle is already called and most want to leave the station by the time you are ready to do something fun.

Overall, public autolathes are healthy for assistants and service roles as they no longer have to ask people for very basic items most wouldn't give a shit about and are convenient for many people who just want some of the basic items an autolathe can produce.

Well, this turned into a rant, but overall, I think that public autolathes are healthy for the game.

**Comment by Isy232** [comment]
image
Think I've fixed the merge conflicts and such now, compiled and tested and it worked fine.

**Pull request merged**
