### PR TITLE
arts & canvases update

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

tgstation/tgstation#48834
tgstation/tgstation#53585
tgstation/tgstation#56349
tgstation/tgstation#53994
tgstation/tgstation#59146
and multiple supporting loose commits

reeeeee

## Why It's Good For The Game

artss

## Changelog
:cl: tralezab, AnturK
add: curators can now print paintings
add: persistent paintings
add: AIs can now pick paintings as their screens
add: tgui canvases
/:cl:

### CODE REVIEW

**Comment by heepox** [comment]
epic

**Comment by ItsTisme** [comment]
very cool

**Comment by Vexylius** [comment]
Awesome, even

**Comment by TerryTehCoder** [comment]
When the A.I goes "(<->)_(<->)".

**Comment by Pirill** [comment]
I need this.

**Review by Crossedfall — DISMISSED** [review]
Some notes from my local test:

1. Painting is still pretty terrible. You have to click for every pixel on the canvas, you can't just drag and draw which is sad.
2. You forgot to map the curator consoles in
3. The new app for curators doesn't work and throws a TypeError

```js
TypeError: Unable to get property 'title' of undefined or null reference
   at t.NtosPortraitPrinter (http://127.0.0.1:53833/tmp9448/tgui.bundle.js:1:347263)
   at Ne (http://127.0.0.1:53833/tmp9448/tgui-common.bundle.js:1:227549)
   at Anonymous function (http://127.0.0.1:53833/tmp9448/tgui-common.bundle.js:1:227817)
   at Fe (http://127.0.0.1:53833/tmp9448/tgui-common.bundle.js:1:227795)
   at Anonymous function (http://127.0.0.1:53833/tmp9448/tgui-common.bundle.js:1:227737)
   at Fe (http://127.0.0.1:53833/tmp9448/tgui-common.bundle.js:1:227679)
   at je (http://127.0.0.1:53833/tmp9448/tgui-common.bundle.js:1:234813)
   at ze (http://127.0.0.1:53833/tmp9448/tgui-common.bundle.js:1:235052)
   at Anonymous function (http://127.0.0.1:53833/tmp9448/tgui-common.bundle.js:1:378066)
   at o (http://127.0.0.1:53833/tmp9448/tgui-common.bundle.js:1:245723)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"crossedfall","interface":"NtosPortraitPrinter","window":{"key":"[0x2102a210]-main","size":null,"fancy":1,"locked":1}}
```

**Comment by jupyterkat** [comment]
1 is unfixable, just how tgui works

**Comment by Archanial** [comment]
Maps are missing structure/sign/painting and wallframes to put the paintings in

**Comment by jupyterkat** [comment]
it’s in the library

**Comment by Archanial** [comment]
Paintings persist but don't show up in the curator's app

**Review by Archanial — APPROVED** [review]

**Pull request merged**
