### PR TITLE
New antag objective "Forged Manifest" to Traitor, Incursion, Changeling: Forge a fake person info in Crew Manifest

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
New antag objective to Traitor, Incursion, Changeling: Forge a fake person info in Crew Manifest

## Why It's Good For The Game
More antagging objective is good to lead more conflict

## Testing Photographs and Procedure

image

image

## Changelog
:cl:
add: New antagonist objective "Forged Manifest" is added to traitor, incursion, changeling - You need to make a crew manifest data for a false person. The data should have correct information for the objective.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
What access is required to complete this objective? Is the HOP/captain the only people that can add new people to the crew manifest?
Also what negative impact does this have to the station and what will make it noticable to the crew that someone is doing something bad?

**Comment by EvilDragonfiend** [comment]
> What access is required to complete this objective? Is the HOP/captain the only people that can add new people to the crew manifest?

They need to steal a security access to do this, then use a security console to make a new record.

* Making a new record: need Security Access
* Editing data: need...
  * **Name**: Security 
  * **Age, Gender, Species**: Security OR Medical
  * **Job**: Need to use HoP console
  or when you log in a security console, your card's Job name should be one of these - Captain, HoP, AI, or Central Command, (VERY JANKY CODE)
  This is something difficult to do here. (I am considering removing this part)
  
> Also what negative impact does this have to the station and what will make it noticable to the crew that someone is doing something bad?

If an obj somehow decided to make a fake person with the job "Captain" or something important, that'll be obvious to raise up their attention.

**Comment by EvilDragonfiend** [comment]
I will make HoP console can add a new crew manifest data

**Comment by Fronsis** [comment]
This is an interesting a idea, a shame the base-code/how it works is so.. janky, the other day i was an Officer and  i couldn't add a new record properly and i thought i didn't had access to do it but the Warden was able to do it properly, even uploading a custom photo to the record after struggling for a bit(Your screenshot even shows that the security record photo is still broken even if Kat insists that it gets solved with a reload, which.. doesn't ughhhh security records why!!!)

> If an obj somehow decided to make a fake person with the job "Captain" or something important, that'll be obvious to raise up their attention.

The thing is if that happens it can easily be undone by a click once they realize, though i guess it's nice to add something extra to check for fingerprints on the computers and it seems like it will be an objective of direct confrontation which doesn't seem that bad, the thing is it only really affects Security(and barely since the damage gets undone with a click) since they'll have to get their hands on a security ID or into HoP's console and by that point they're going loud and all their impact gets undone by a click so it's like a mix of ''feels like a stealth objective, but you need to go loud and you really only impact one department'' and if you go the route of sabotaging the entire records it's like ugh, specially with dynameme shenanigans..

**Comment by MarkusLarsson421** [comment]
This feels like it'll encourage killing and stealing someones ID which could be detrimental to low-pop times when there might just be one single acting Captain.

**Comment by EvilDragonfiend** [comment]
I will bring this back after refactoring datacore

**Pull request closed without merging**
