### PR TITLE
Toxins will no longer bomb the MetaStation Exploration Shuttle at roundstart.

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
Moves MetaStation toxins slightly south, so that it isn't pointed directly at the exploration shuttle. Also moves the Explorer spawns to the now-slightly-larger Testing Range.

## Why It's Good For The Game
There were a lot of instances of scientists not checking the camera and maxcapping the exploration shuttle before they started exploring. Also, the Science dock felt cramped with five spawns in there, and now that the testing range is larger, the spawns feel better situated there.

## Changelog
:cl:
fix: Toxins will no longer bomb the MetaStation Exploration Shuttle at roundstart.
/:cl:

### CODE REVIEW

**Comment by williamcll** [comment]
Doesn't the camera only cover the bomb site and not the shuttle itself?

**Comment by Ivniinvi** [comment]
> Doesn't the camera only cover the bomb site and not the shuttle itself?

...I don't think you realize what these changes are

**Comment by rkvothe14** [comment]
> Doesn't the camera only cover the bomb site and not the shuttle itself?

If you launched the bomb and saw in the cameras that it never got to the test site, it meant it was stuck in the exploration shuttle. Then you had to retrieve it and manually take it to the test site.

Love this! I was going to file an issue about this, but seems like it was not needed,

**Review by Archanial — CHANGES_REQUESTED** [review]
Readd deleted lockers from maints and if you can figure out if you can connect the solar room to the maints (not thru the random room).

**Comment by Ivniinvi** [comment]
> Readd deleted lockers from maints and if you can figure out if you can connect the solar room to the maints (not thru the random room).

I can't see a viable connection path for the wires that doesn't go through walls, as the toxins bomb only has a 1-tile wide space between the top of the solars and the bottom of the shuttle, and it has to thread the needle between both.

**Review by Archanial — DISMISSED** [review]

**Comment by OceanFish1** [comment]
This is default supercruise moment

How could that even happen during development exploration on Meta?

**Review by Archanial — APPROVED** [review]

**Pull request merged**
