### PR TITLE
Re-PR HoP Expansion Pack

### PR DESCRIPTION
**Pull request by itsmeow**
## Re-PR of #8113

This PR was near perfect, it just needed a merge conflict fix and some more reviews. My review on it was basically complete, it turns out %s signing works fine in fields, so that's good. I've fixed the merge conflict and Re-PR'd it as is. I think it's good to merge now, we've testmerged it and it worked well. I would like to see better blanks and it seems there is a bit of community interest as I've seen some threads with them, so we can implement those via config change later.

## About The Pull Request
Updates the Paperwork Module to the current version used by TG
This is accomplished by porting the Following PRs from TGstation

- [x] Papercode 
- - [x] https://github.com/tgstation/tgstation/pull/68612
- - [x] https://github.com/tgstation/tgstation/pull/69071
- - [x] https://github.com/tgstation/tgstation/pull/63879 (Something from this, don't remember what exactly)

- [x] Photocopier
- - [x] https://github.com/tgstation/tgstation/pull/52831
- - [x] https://github.com/tgstation/tgstation/pull/61323
- - [x] https://github.com/tgstation/tgstation/pull/63287
- - [x] https://github.com/tgstation/tgstation/pull/69005
- - [x] https://github.com/tgstation/tgstation/pull/69202
- - [x] https://github.com/tgstation/tgstation/pull/69198

- [x] Fax Machine
- - [x] Add Fax Machines to every station
- - [x] https://github.com/tgstation/tgstation/pull/69083
- - [x] https://github.com/tgstation/tgstation/pull/69397 
- - [x] https://github.com/tgstation/tgstation/pull/69554 
- - [x] https://github.com/tgstation/tgstation/pull/69651 
- - [x] https://github.com/tgstation/tgstation/pull/70072 
- - [x] https://github.com/tgstation/tgstation/pull/71262 

- [x] Stamp
- - [x] https://github.com/tgstation/tgstation/pull/55028

- [x] Sanitize.js
- - [x] https://github.com/tgstation/tgstation/pull/56001 (Only the changes done to the Sanitize.js file)
- - [x] https://github.com/tgstation/tgstation/pull/65326 (Only the changes done to the Sanitize.js file)

## Issues
- [x] Stamp indicator can’t be moved around in the paper ui. 
- - Stamp indicator can be rotated around by holding the Shift key and moving the mouse around, however it still fails to follow the mouse around when you move it while not holding the shift key.
- - For some reason stamping the paper puts the stamp at the very bottom of the paper in what seems to be a new box or section rather than in the top left corner where the stamp indicator is stuck.
- [x] Linters issues.
- - Linters bypassed for that one line that was causing an error, the code still functions ingame perfectly fine.
## Why It's Good For The Game
A more up to date version of the Paperwork Module, allows people to see the result of what they're entering on a paper, fax machines to annoy admins with and other fun stuff!

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

https://user-images.githubusercontent.com/59128051/204981727-a34776a5-b0f1-4199-9c5b-33e193984eba.mp4

</details>

## Changelog
:cl: Bobbanz1, Timberpoes, SteelSlayer, twilightwanderer, ShizCalev, timothymtorres, Imaginos16, dragomagol, Jacquerel, Mothblocks, ThePotato97, LemonInTheDark
del: Removed the ability to scan paper directly into the modular computer notes app as part of paper code rewrite.
qol: AIs now see the full paper interface when players show them papers through the camera, exactly what's written on the paper, fully rendered.
refactor: Paper code has been completely refactored.
fix: Fixes signatures not working at all. Signatures now only work when %s or %sign is put into an [___] input field.
fix: Input fields are now fixed and also work again.
fix: Fixes broken command report formatting for station goals.
fix: Fixes markdown paragraphing not working in paper code.
refactor: Photocopiers now use TGUI
tweak: You can insert any type of toner cartridge into photocopiers, and regardless of the currently inserted toner's charge level.
tweak: Toner cartridges can be ejected from photocopiers at any time
add: Added a system of forms and the ability to print them
fix: Hints in bureaucracy forms
add: Added new VOID stamp
fix: Photocopier paperforms
add: Fax Machine
fix: Fixes faxes playing the "fax_contain" animation and makes it actually use the "fax_receive" animation when receiving.
imageadd: Resprites fax machines!
admin: fax messages and book printings are now logged in paper.log
admin: renaming fax machines is logged in game log
add: You can now send photos or trading cards through the fax machine.
add: You can now hack the wires of a fax machine to have it throw items harder or accept additional flat input items such as material sheets, ID cards, and pizza slices.
add: Ability to send and receive administrator fax messages.
admin: Panel for easy viewing and sending messages to faxes.
fix: Fixes a crash of TGUI fax panel when there is no fax in the network
fix: Fixes a crash of the Fax Manager panel when there is no fax machines in the network.
refactor: Rotating stamps on paper by holding shift and moving your mouse.
fix: You can no longer remove the toner cartridge from a printer while it's busy printing.
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
Remember to add yourself to the cl

**Comment by itsmeow** [comment]
Nah I didn't do shit

**Comment by DarnTheMarn** [comment]
🙏 Please speed merge so I can make my paperwork forms even better

**Review by Crossedfall — APPROVED** [review]

**Review by PestoVerde322 — APPROVED** [review]
Re-approved as icons and maps are fine as in the previous version.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by itsmeow** [comment]
DNM downstream without https://github.com/BeeStation/BeeStation-Hornet/pull/9297

**Pull request merged**
