### PR TITLE
boosts disease healing i guess

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
people keep whining about the new healsymptoms not being worth it. so here. you guys decide if you want this shit or not

## Why It's Good For The Game
makes disease healing more worth the downsides i guess?

## Changelog
:cl:
tweak: boosts disease healing
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
holy fuck this is powerful

**Comment by nikk735** [comment]
isnt that too op it was already decent

**Comment by zeskorion** [comment]
some people think new symptoms arent worth it.  I personally dont think this buff is necessary.

though, it's wise to remember diseases tick every 2 seconds, not every 1 second

**Comment by nikk735** [comment]
ah yes thats true i always forget that

**Comment by zeskorion** [comment]
Not even worth a vote.

**Pull request closed without merging**
