### PR TITLE
Salvage Ship fastmos update

### PR DESCRIPTION
**Pull request by Cenrus**
The NT Salvage Ship now has air recycling, border firelocks, and advanced airlocks to prevent catastrophic depressurization under fastmos.

68747470733a2f2f6d64622e616666656374656461726330372e636f2e756b2f46696c65732f3136323335363932372f313234323631353032342f302f61667465722e706e67

:cl:
tweak: The NT Salvage Ship has been adapted for fastmos.
/:cl:

### CODE REVIEW

**Comment by AnjelicaChaykovsky** [comment]
Heyyyy  mate how did you manage to make airlocks work ? When i make them it shows error contact atmos tech 


I dont have yet custom area for that outpost, i just reused one.
 Could that be the issue ?

**Comment by Cenrus** [comment]
Is the entire airlock in the same area?

**Comment by Dennok** [comment]
When you here, can you remove this redundant circle link from airlocks in cargo area?

**Comment by AnjelicaChaykovsky** [comment]
> Is the entire airlock in the same area?

yeah

**Comment by Cenrus** [comment]
Looks like there are windows around it, try swapping them out with walls.

**Comment by AnjelicaChaykovsky** [comment]
> Looks like there are windows around it, try swapping them out with walls.

Oh lol why i never thought of that thanks

**Comment by PowerfulBacon** [comment]
> 
> 
> Heyyyy mate how did you manage to make airlocks work ? When i make them it shows error contact atmos tech
> 
> 
> I dont have yet custom area for that outpost, i just reused one.
> Could that be the issue ?

The outer airlock must be on the edge of an area or it doesn't auto-detect which is stupid and leads to a lot of problems on regular maps

**Review by PowerfulBacon — APPROVED** [review]

**Comment by AnjelicaChaykovsky** [comment]
> > Heyyyy mate how did you manage to make airlocks work ? When i make them it shows error contact atmos tech
> > 
> > I dont have yet custom area for that outpost, i just reused one.
> > Could that be the issue ?
> 
> The outer airlock must be on the edge of an area or it doesn't auto-detect which is stupid and leads to a lot of problems on regular maps

Now it works thankss it was the area after all, also do you know how ghost spawners work perhaps ? Im stuck on that one for days now,  i added new spawner in ghost_role_spawner, and i can place it in map but wont spawn on server 

the first line of the new spawner causes issue i think  /obj/effect/mob_spawn/human/something

**Pull request merged**
