### PR TITLE
Fixes some additional proc references for 515

### PR DESCRIPTION
**Pull request by covertcorvid**
## About The Pull Request
While I was doing compatibility checks for NSV13 I found a couple more unwrapped proc references. This fixes them.

## Why It's Good For The Game
515 is apparently very good, and this is how to be compatible with it

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

voiceofgod

nuke

</details>

## Changelog
:cl:
code: Made 515 compatibility changes for a few leftover proc references
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
there's a TYPE_PROC_REF(/, ) somewhere i fixed in my sendmaps pr, would be better here

**Comment by covertcorvid** [comment]
> there's a TYPE_PROC_REF(/, ) somewhere i fixed in my sendmaps pr, would be better here

I've found a few more just now too, so I'll grab the one from your PR and add those

**Review by itsmeow — APPROVED** [review]

**Review by PowerfulBacon — APPROVED** [review]
Oh damn thats a lot

**Comment by covertcorvid** [comment]
Yeah the regexes really didn't like callbacks for some reason idk

**Pull request merged**
