### PR TITLE
Curator ElementX/Superpower Activator

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Curator exlusive tator item: Element-X. An activator that activates all your current positive mutations. Available to curators for 3 TC. Who knows what you might get?

## Why It's Good For The Game

Nice gimmick and very versatile with mutations.

## Changelog
:cl:
add: Element X - curator exclusive traitor item
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
Why curators?

**Comment by eeSPee** [comment]
Curators >>> read comix >>> superhero gimmick

**Comment by PowerfulBacon** [comment]
Wont this put your instability over 100 and just kill you?

**Comment by eeSPee** [comment]
> Wont this put your instability over 100 and just kill you?

It's an activator, so if I recall the mutations activated won't make you unstable.
And since it's an activator, it won't give you all the mutations, just activate all the positive ones you have.

Edit: Yea, I checked code and it should be the case. Roundstart mutations are considered "normal mutattions" and do not give instability when activated. Injectors give you what is called "extra mutations" that are accounted for when calculating instability. But feel free to check and tell me if I am wrong.

**Comment by LordSaladin** [comment]
Imagine getting it from a null crate.

**Review by PowerfulBacon — DISMISSED** [review]

**Comment by PowerfulBacon** [comment]
@Crossedfall travis broken

**Comment by eeSPee** [comment]
Thanks.

**Comment by eeSPee** [comment]
It occurred to me that the curator has no way to determine what mutations he obtained. I thought of doing superhero kit, which comes bundled with a DNA scanner and a random cape, and is more gimmicky.

**Comment by super12pl** [comment]
DNA scanner doesnt show what mutations you have unless you discover them in gene console first and then sync scanner to console. Making it useless to traitor curator.

**Review by zeskorion — CHANGES_REQUESTED** [review]
i dislike this, to be honest. What i'd like to see is a pill or reagent that activates DNA mutations in the positive mutation list, perhaps as a discount only item. Curator only doesnt really fit the theme

**Comment by eeSPee** [comment]
> i dislike this, to be honest. What i'd like to see is a pill or reagent that activates DNA mutations in the positive mutation list, perhaps as a discount only item. Curator only doesnt really fit the theme

Good idea; that was surprisingly easy to code and implement.

It's Curator only because it's a gimmicky superhero/superpower injector, like in the Comic Books, and who is the most likely to read comic books? Also the only curator item, the magic 8ball, is shit, it's bugged and doesn't even work. This one will still appear in the discounted items pile.

**Comment by FortSumter** [comment]
I like this as a curator only thing. Service roles should have more gimmick items as their very existence is a gimmick. I'm not sure how this item should work however, since it only activating genes they already have is a real gamble. Personally, I'd rather pick one from a random list of positive genes and have it as a mutation. For 3 TC, I'm sure a curator would spam it as many times they need to get what they want. Just a thought, there are also some fun beneficial brain traumas as well....

**Comment by eeSPee** [comment]
> I like this as a curator only thing. Service roles should have more gimmick items as their very existence is a gimmick. I'm not sure how this item should work however, since it only activating genes they already have is a real gamble. Personally, I'd rather pick one from a random list of positive genes and have it as a mutation. For 3 TC, I'm sure a curator would spam it as many times they need to get what they want. Just a thought, there are also some fun beneficial brain traumas as well....

Good idea, but I wanted to give the roundstart mutations some sort of use for traitors. That, and there's very few genetics based taitor items.

**Comment by zeskorion** [comment]
this does not work as it should and the pr seems dead,  please make another pr when you rewrite this in a workable manner

**Pull request closed without merging**
