### PR TITLE
Filters + plane_master atomized

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Ported: 
https://github.com/tgstation/tgstation/pull/55246
https://github.com/tgstation/tgstation/pull/56717
https://github.com/tgstation/tgstation/pull/58291

## Changelog
:cl: actioninja, Floyd, LemonInTheDark 
add: New filter editor for admins + development purposes
/:cl:

### CODE REVIEW

**Comment by jupyterkat** [comment]
#4434

**Comment by Archanial** [comment]
> 
> 
> #4434

your PR doesn't convert our existing filters to this.

**Comment by jupyterkat** [comment]
Yes it does

**Comment by utilbird** [comment]
@jupyterkat You should include the other PRs you ported in your pr desc then

**Comment by jupyterkat** [comment]
> @jupyterkat You should include the other PRs you ported in your pr desc then

The filter converts are in the same pr

**Review by utilbird — APPROVED** [review]

**Pull request merged**
