### PR TITLE
Resprites: Security, Chef, (Most) Suits & Ties

### PR DESCRIPTION
**Pull request by Agameofscones**
## About The Pull Request

Resprites & reshades all security (HOS, Warden, Officer, Detective) uniforms.

Replaces stock Sec helmet (Not Swat, Alt, or Riot, gonna have to work on those later)

Resprites chef & bartender uniforms and all basic civilian suits. Adds alternative chef suit.

dreammaker_2019-10-03_23-53-46
dreammaker_2019-10-03_23-53-43
dreammaker_2019-10-03_23-53-36
Photoshop_2019-10-02_01-15-00
Photoshop_2019-09-25_23-28-25

Also adds the mallcop uniform to sec vendors.

## Why It's Good For The Game

Replaces ugly as hell TG uniforms with palettes based on the pleasing to look at alt-sec armor. Should go hand in hand with the eventual oracle tiles people are working on. Helps make Bee distinct from TG and move towards a more creative design.

## Changelog
:cl: Triiodine
imageadd: NanoTrasen has issued the private security team and the culinary crew new uniforms.
imagedel: NanoTrasen is no longer sewing ties onto uniforms. To compensate, clip-ons can be found alongside the now tie-less uniforms and suits in both cabinets and AutoDrobe variants.
add: There are now enough chef suits in the chef wardrobe vendor.
/:cl:

### CODE REVIEW

**Review by MarkSuckerberg — APPROVED** [review]
Personally love the new clothing, hope they get added!

**Comment by ike709** [comment]
Since ties became an actual separate item after most of these outfits were added, can you remove the ties from the clothing that already has them?

**Review by ike709 — APPROVED** [review]
Aside from the tie thing, these look great.

**Comment by Agameofscones** [comment]
Sure, I'll add ties to the appropriate vendors once I get the icons deconflicted.

**Pull request merged**
