### PR TITLE
autodoc sprite change

### PR DESCRIPTION
**Pull request by Sinmero**
## About The Pull Request

Autodoc sprite now has medbay cross instead of "Fat" on its door, autodoc sprite colors were slightly adjusted.

image

## Why It's Good For The Game

Autodoc looked like a lipid extractor. Now it looks like a medical machine.

## Changelog
:cl:
imageadd: added autodoc sprite dmi
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
Finally

**Comment by Sinmero** [comment]
Is there a way to tell why it didnt pass the checks?

**Comment by TeomanTheGreat** [comment]
Not sure I don't really code I just state my opinion go ask on the discord I guess

**Comment by SomeAngryMiner** [comment]
looks like a good placerholder until someone does the definitive version.

**Review by Kmc2000 — APPROVED** [review]
Sprite looks decent, could do with a slightly darker outline maybe?

**Comment by Sinmero** [comment]
Made outlines darker

image_darker

**Comment by zeskorion** [comment]
ike how the hell am i supposed to do a review on a sprite change

**Comment by PowerfulBacon** [comment]
> ike how the hell am i supposed to do a review on a sprite change

Look at the sprite

**Comment by ike709** [comment]
seems fine

**Pull request merged**
