### PR TITLE
[WIP] Reworks the bluespace artillery

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

Bluespace artillery now has it's own battery and draws power from wire nodes. The cannon's explosive power is scaled based on the amount of power stored

## Why It's Good For The Game

It's on the todos

## Changelog
:cl:
balance: bsa now scales with the amount of power stored and require a wire node connection
/:cl:

### CODE REVIEW

**Comment by Effemu** [comment]
but why

**Comment by ghost** [comment]
Wouldn't be bad if you added more documentation.

**Comment by Blueturbo47** [comment]
> but why

Why not

**Comment by Sinestia** [comment]
> 
> 
> but why

maek fun

**Pull request closed without merging**
