### PR TITLE
Chem macros

### PR DESCRIPTION
**Pull request by yorii**
## About The Pull Request

I already merged this code for another thing, figured maybe you want it, maybe you don't. (I mean you probably don't :D)
It now works in conjunction with the recording function.

## Why It's Good For The Game

Makes life easier for chemistry.

## Changelog
:cl:
add: Chem macros are back
/:cl:

### CODE REVIEW

**Comment by Poly-The-Parrot** [comment]
Also includes the nerf that prohibits "parallel"-processed macros. (If you know you know)

**Comment by yorii** [comment]
Also includes the nerf that prohibits "parallel"-processed macros. (If you know you know)

**Comment by utilbird** [comment]
Why though, chem macros weren’t fun. It allowed you to use OOC files for IC advantages that other chemists might not have. You have an advantage because of something you did in a different round.

This is the same reason old floor satchels and telesci (to a degree) were removed. And before it’s mentioned,  I can kind of understand circuits due to how much longer they take, but they’re still far from balanced. Not everyone knows the instant husk cooking oil circuit script 😔

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Needs TGUI rebuild

**Comment by PowerfulBacon** [comment]
Also, Elon brings up a very good point where it allows for OOC files to just instant make you your death mixes rather than actually working to get them yourself.
Sure you can still follow a list atm, but having it done instantly because you copied and pasted something is kind of bad and one of the reasons circuits needed nerfing.

**Comment by PowerfulBacon** [comment]
Stale

**Pull request closed without merging**
