### PR TITLE
Removes romerol from floorpills

### PR DESCRIPTION
**Pull request by Tyranicranger4**
## About The Pull Request
Romerol no longer has the CHEMICAL_RNG_FUN flag, the flag used by floorpills.

## Why It's Good For The Game

I love Romerol as much the next person, but this isn't the way it should be getting introduced into rounds.
Also potentially encourages people to pop floorpills in hopes of becoming a zombie, which isn't really something we can feasibly prevent via enforcement unfortunately.
## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Spawned a fuck ton of pills, selected their contents with SDQL, control + F'd the list.

Has Romerol.
image
image

No longer has Romerol.
image
image

</details>

## Changelog
:cl:
del: Removes romerol from the floorpill reagent pool.
/:cl:

### CODE REVIEW

**Comment by dwasint** [comment]
Soul removed

**Comment by kit-katz** [comment]
watch out folks. the fun police has arrived

**Comment by St0rmC4st3r** [comment]
ided?

**Comment by itsmeow** [comment]
tempting but also fun removed, cringe

**Comment by EvilDragonfiend** [comment]
well, the fun random reagent list was introduced by me. I put a fuckton of stupid things into the list for fun lol.
although I won't disagree with the removal of the flag.

**Comment by EvilDragonfiend** [comment]
by the way, the full size of CHEMICAL_RNG_FUN is currently 259. this means the chance to get Romerol is 0.386% by a single floorpill

**Comment by itsmeow** [comment]
Wildly unpopular
Also extremely rare

Meh 🗝️

**Pull request closed without merging**
