### PR TITLE
Repaths skinsuits, moves them from boxes to o2 lockers

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Skinsuits are now hardsuits subtype, which basically means they have integrated helmet (no light on the helmet though).
Skinsuits are no longer spawn in roundstart boxes.
2 or 3 skinsuits may spawn in o2 (blue) locker.
Skinsuits are now as big as normal spacesuits which means you cannot store them in your backpack.
You can't roll skinsuits anymore. Icon for rolled skinsuit was removed as well.

## Why It's Good For The Game

Everyone having protection from atmosphere roundstart is bad. Breaches are not dangerous, only downside is that people are a bit slower.

## Changelog
:cl:

tweak: Skinsuits are now a subtype of hardsuits.
del: Skinsuits no longer appear in internals boxes and you cannot fold them.
add: Skinsuits now have integrated helmets.
tweak: Skinsuits are as big as every other space suit now.
tweak: Skinsuits appear in o2 (blue) lockers.
/:cl:

### CODE REVIEW

**Comment by leestriter** [comment]
I agree with taking them out of the starter box, but I don't know about nerfing them to not fit in a backpack/be foldable. And what about starting with a tank of O2 and a mask, shouldn't those be only in lockers as well?

**Comment by bloons3** [comment]
> And what about starting with a tank of O2 and a mask, shouldn't those be only in lockers as well?

The emergency oxygen tank is deliberately inferior but fits in your pocket.

**Comment by leestriter** [comment]
> 
> 
> > And what about starting with a tank of O2 and a mask, shouldn't those be only in lockers as well?
> 
> The emergency oxygen tank is deliberately inferior but fits in your pocket.

So is the skinsuit to a real hardsuit/eva suit. Sure it isn't as good but for its enough for your average player all round. I'd say the emergency oxygen tank being a starter item is more problematic then the skinsuit, the skinsuit slows you down to a crawl and barely does its job, while I can keep my mask on and a tank in my pocket all round and just flick it on when needed without any negatives.

**Comment by Rukofamicom** [comment]
> I agree with taking them out of the starter box, but I don't know about nerfing them to not fit in a backpack/be foldable. 

If they aren't nerfed to not be pocket sized, powergamers will simply hoard them from the start of the round and go unnoticed. It's already somewhat silly that you can fit a full sized body suit sturdy enough to protect you from an absolute vacuum in your pocket.

**Comment by leestriter** [comment]
> 
> 
> > I agree with taking them out of the starter box, but I don't know about nerfing them to not fit in a backpack/be foldable.
> 
> If they aren't nerfed to not be pocket sized, powergamers will simply hoard them from the start of the round and go unnoticed. It's already somewhat silly that you can fit a full sized body suit sturdy enough to protect you from an absolute vacuum in your pocket.

But they already are near useless, the counter part to making them unable to be stored is they won't be used at all. May as well remove them. But I'm not a coder, I've already posted a lot on this pr. A powergamer can already grab an O2 tank at the start, so why stop them only with the skin suit.

**Comment by Cartlord** [comment]
Far as I can see, the purpose of the skinsuit/mask/ox tank is so that, from roundstart, you can survive a breach. I see no issue with them the way they are.

**Review by ghost — DISMISSED** [review]

**Review by francinum — DISMISSED** [review]
Hi, I'm the host of the server who coded these.

I would see them removed if I could. They were a mistake. 

This is a compromise on that position. 

They do not make sense for general ss13. They make sense for NSV where every single crewmember is valuable. 


Not everyone is of inherent value on bee. Sometimes you just die.

**Comment by park66665** [comment]
> Not everyone is of inherent value on bee. Sometimes you just die.

Screenshot 2021-02-22 022832

As I said, this PR is an okay gameplay decision at least.

**Comment by LivingBatteryBox** [comment]
If this merges, I would honestly just grab a skinsuit every round instantly and just deal with only having one hand. Fastmos makes these things nearly always relevant.

**Comment by Cartlord** [comment]
> 
> 
> Hi, I'm the host of the server who coded these.
> 
> I would see them removed if I could. They were a mistake.
> 
> This is a compromise on that position.
> 
> They do not make sense for general ss13. They make sense for NSV where every single crewmember is valuable.
> 
> Not everyone is of inherent value on bee. Sometimes you just die.

I mean, I'd argue everyone is of inherent value when you have 6-14 people online.

**Comment by PowerfulBacon** [comment]
@francinum dont leave stuff testmerged for ages (I used to have a habit of doing this and it makes issues with PRs hard to pinpoint as the merge time =/= time of issue starting)

**Review by PowerfulBacon — APPROVED** [review]
Not bad

**Review by francinum — APPROVED** [review]

**Pull request merged**
