### PR TITLE
Makes brains indestructible

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Makes brains an indestructible item.
When a mob is destroyed the brain will be dropped (if it has a person in it) along with any other indestructible items on them.

## Why It's Good For The Game

Being permanently removed from the round is very dull, especially in cases where it was an accident/grief, gives people always a chance to remain in the game alive (the fun part of the game).
Since the brain is dropped changelings will not be able to just infinitely revive and be immortal due to this.

## Changelog
:cl:
tweak: Brains cannot be destroyed
/:cl:

### CODE REVIEW

**Comment by Sylphily** [comment]
Speed merge

**Comment by Archanial** [comment]
No, bad change, what's wrong with cremating people instead of spacing the brain?

**Comment by Glcbitj** [comment]
Does this mean we can infinitely eat a deepfried brain or can't deepfry them?

**Comment by GoatMonarch** [comment]
This PR is short sighted. 
I am neutral on making brains more easily accessible after someone is permanently killed. Blowing up, thrown into the super matter, so on.  The good part being you can get back in the round as an MMI and later borg/mech, really good! The bad part being it's harder to fully assassinate one of your targets fully, even though you take the risks of killing someone and then bringing their corpse to the incinerator / gibber. Which outweights the fun of being able to turn into a cyborg more often.

Though what I take great issue with is with three points:

> Since the brain is dropped changelings will not be able to just infinitely revive and be immortal due to this.
1. The brain inside of a changeling has no effect uppon the mob. The conscience of a changeling is their body, not brain. You can behead a changeling and nothing happens. You can gib a ling, get their brain and that still does nothing. You've not brought any code to change this as far as I've seen with my minor code knowledge.

2. You've not removed the brain burger recipie. The new meta will just be smacking the body in a gibber, then craft a brain burger, removing them from the round. 

3. If you're removed from the round, just play as one of the lavaland spawns if you really want to continue playing. The odds of you being killed in such a way that you are unable to return to the round due to grief or by "accident"* is not a cause to change the game this much.

*The only way I can really envision this is if a new chef brings a corpse to the gibber, fresh from the medbay lobby. Come on don't water down your argument with this bogus.

**Comment by TeomanTheGreat** [comment]
This is a very shitty pr. Instead of doing stuff like nerfing an antags ability to make kills why don't you add fun things for ghosts to do like the mafia ghost gamemode thing from TG.

**Comment by PowerfulBacon** [comment]
> 
> 
> This PR is short sighted.

true

**Comment by PowerfulBacon** [comment]
> 
> 
> Does this mean we can infinitely eat a deepfried brain or can't deepfry them?

Can't deepfry indestructible items

**Comment by PowerfulBacon** [comment]
> * The brain inside of a changeling has no effect uppon the mob. The conscience of a changeling is their body, not brain. You can behead a changeling and nothing happens. You can gib a ling, get their brain and that still does nothing. You've not brought any code to change this as far as I've seen with my minor code knowledge.

How's that an issue with this PR? I didn't change anything code wise, I was just pointing it out.

> * You've not removed the brain burger recipie. The new meta will just be smacking the body in a gibber, then craft a brain burger, removing them from the round.

True.

> * If you're removed from the round, just play as one of the lavaland spawns if you really want to continue playing. The odds of you being killed in such a way that you are unable to return to the round due to grief or by "accident"* is not a cause to change the game this much.

Most of the time these don't exist.

**Pull request closed without merging**
