### PR TITLE
Ports /TG/ Baton sprite

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request

Ports /TG/ Security sprite baton. 
https://github.com/tgstation/tgstation/pull/52320

## Why It's Good For The Game

It looks better and newer.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

imagen

</details>

## Changelog
:cl: Varo, Sirich96
tweak: Ports baton sprite from /TG/
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
The lack of soul is practically palpable.

**Comment by Nakalon** [comment]
Looks like some fire lantern mace you'd use in medieval times. I like the batong I think it looks good as it is.

**Comment by itsmeow** [comment]
I like it

**Comment by EvilDragonfiend** [comment]
I will delegate my power to @PestoVerde322 
He can close the PR with his key and on behalf of me that includes my key.

**Comment by ClownMoff** [comment]
Our baton sprite looks super dated and bland

**Comment by St0rmC4st3r** [comment]
> Our baton sprite looks super dated and bland

It's not dated. It's a HL2 classic! And if you think that it is bland, why not make our own sprite then, instead of copying /tg/?

**Comment by ClownMoff** [comment]
Ok dont close this PR I will try to make my own version

**Comment by EvilDragonfiend** [comment]
nah, just close and make new one.

**Comment by JixS4v** [comment]
🔑

**Comment by Rukofamicom** [comment]
This looks like a flyswatter

🔑

**Pull request closed without merging**
