### PR TITLE
Removing clwne

### PR DESCRIPTION
**Pull request by SergeiKoralev**
## About The Pull Request

This PR removes the floor clwne random maintenance rooms that give administrators headaches. 

## Why It's Good For The Game

Those rooms cause nothing but pain and misery. They were a mistake.

## Changelog
:cl:
remove: the clwne random maint rooms
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
Fix your changelog.

**Comment by SergeiKoralev** [comment]
Working on it, unfortunately i'm not great at github, advice on how to do so? I use gitkraken.

**Comment by SergeiKoralev** [comment]
Nevermind! I got it!

**Comment by zeskorion** [comment]
> Nevermind! I got it!

you know, it wouldn't be too hard to make it only invokeable by antags and such, or make it far less poor for the round

**Comment by SergeiKoralev** [comment]
> you know, it wouldn't be too hard to make it only invokeable by antags and such, or make it far less poor for the round

Welp, unfortunately I have the coding knowledge of a two year old, and don't have the time to learn. So for now you get a mapper solution to a code problem that should have been fixed before these rooms were created.

**Comment by Rukofamicom** [comment]
The Honkmother is displeased with your decisions.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
This was a joke that was funny the first round we did it, before it went and killed half the server

**Comment by eeSPee** [comment]
Bring it back next halloween!

**Comment by St0rmC4st3r** [comment]
>pain and misery

Intended

**Comment by zeskorion** [comment]
> This was a joke that was funny the first round we did it, before it went and killed half the server

As is, this removal pr wont even work and will generate giant holes in maint. Simply drastically nerfing the rune will work fine. The rooms are atmospheric

**Comment by SergeiKoralev** [comment]
> As is, this removal pr wont even work and will generate giant holes in maint. Simply drastically nerfing the rune will work fine. The rooms are atmospheric

There are other random maintenance rooms in the same categories that these are being removed from.
Edit: in other words implying that this will leave a large hole of empty plating in maint is an outright lie.

**Comment by PowerfulBacon** [comment]
Zesko is right, you didn't remove the datum that loads the map, only the map itself so it will try and load a map that doesn't exist

**Comment by zeskorion** [comment]
If you want the rune fixed without removing it, you can preform any number of simple changes . All this does is remove the maps themselves- not the rune, nor the template that spawns what are now just holes to space.  (code/modules/mapping/random_rooms.dm). the templates can be commented out, or the rune itself in mainttraps.dm can have another invocation requirement (that the user be an antag, or whatever) be added quite easily

**Pull request closed without merging**
