### PR TITLE
Ports Modifies the Mechfab to use the Ore Silo #47619

### PR DESCRIPTION
**Pull request by Cenrus**
https://github.com/tgstation/tgstation/pull/47619/

Some QoL from TG

:cl:
add: Modifications have been made to the Mech Fabricator to allow it to withdraw and deposit to the ore silo (Thanks to alexkar598 from Yogstation for the code!)
/:cl:

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
Will you be able to re-link it to another ore silo?

**Comment by Cenrus** [comment]
Yes

**Comment by MarkSuckerberg** [comment]
Tested locally?

**Comment by Cenrus** [comment]
yes, ready to go

**Review by MarkSuckerberg — APPROVED** [review]

**Pull request merged**
