### PR TITLE
OOC optio n to hide chat badges

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
Preferences toggle to hide the ooc colors and tags if you want

## Why It's Good For The Game
if you want to hide the badges its a nice option to keep ooc chat consistent and especially if you cant see someones name color due to it being too close to the background color, overall giving people the option to hide certain people's high status might help my stress

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

its kinda broken but it will work!!

</details>

## Changelog
:cl:
add: ooc option to hide chat badges
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
> its kinda broken but it will work!!

You are admitting the PR is broken and yet you open it anyway?

**Comment by etherware-novice** [comment]
it will work ok it will work it has to it will wok it will work it will work

**Comment by Archanial** [comment]
> its kinda broken

**Comment by itsmeow** [comment]
seeing as this is a thinly veiled attempt to get around you being jealous of my badge, and it also doesn't work, blocks admins from having their badges (kind of important for differentiating their OOC messages), hides donor badges (which people pay for)

Given, it's all under a preference you have to do, but basically

ided PR

**Comment by etherware-novice** [comment]
why is this such a bad option huh??

**Comment by itsmeow** [comment]
If you can't take the effort to properly test your PR then you shouldn't be submitting it

**Comment by etherware-novice** [comment]
the n i ll go make it work and then post it-

**Comment by Archanial** [comment]
So, I don't think hiding the bagdes are a good idea.
Not everything has to be up to the user and I don't feel like 5 px badges next to OOC messages are any problem for anyone.

But that's not only up to me to judge, you need consensus of two maintainers to close the given pr.
This was closed simply because you literally admitted it's not working, when you test and confirm it working, ping me and I will reopen this.

But still, consider this. I know for a fact that at least two maintainers agree with my opinion voiced above, so I don't really think it's worth going the extra mile just to have it open for a little more.

**Comment by etherware-novice** [comment]
but its not a bad idea!!

**Comment by etherware-novice** [comment]
> I don't feel like 5 px badges next to OOC messages are any problem for anyone.
it is to me

**Comment by EvilDragonfiend** [comment]
> > I don't feel like 5 px badges next to OOC messages are any problem for anyone.
> 
> it is to me

Which problem?

**Pull request closed without merging**
