### PR TITLE
BoxStation map updates, QoL fixes

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
This is a remake of a previous PR that I was working on before monstermos, I scrapped it because monstermos caused conflicts.
BoxStation is aging, it has some updates in certain places but not others, some things are broken and some are outright illogical.
This tries to sew it together and make life on box a little nicer.

- Who would win: One supermatter crystal or one mousey boi? Redundant power lines are added, generally clipping one wire isn't going to cut off an entire section of the station now.
- The blast door sections of the bridge are now 5x3 instead of 3x3, like every other map
- Added a couple light bulbs in the more obvious sections of maint, which were once lit by APCs a long time ago
- Bar now has an APC
- Removed the remaining APCs from maint, which were mostly removed before but they forgot a few
- Removed air alarms in maint that were there to check a bug, but forgotten about
- Added some new vents and scrubbers in main hall which simultaneously make it safer and dangerous, but mostly more dangerous
- More obvious decals to the no slip emergency showers
- New no slip emergency shower in sec near brig physician
- Atmos piping below grav gen was using a manifold where they should've been using a 4w. This is fixed

## Why It's Good For The Game
BoxStation is THE lowpop map
Map wide power outage because of a single mouse on the other side of the map is fun for no one (except maybe mice (sorry mice))
BoxStation needs some TLC

## Changelog
:cl:
:add: Larger blast door rooms to Boxstation 
:add: Boxstation power redundancy
:fix: Atmos pipes below grav gen fixed
/:cl:

### CODE REVIEW

**Comment by jlsnow301** [comment]
Known bugs: Disposals and atmos pipes fight for top visibility depending on which was built last. This is seen near SE solars, but the pipes are still fully functional

EDIT: Resolved

**Comment by St0rmC4st3r** [comment]
>South of viro in maint is now entirely reworked. There are 4 new random rooms there instead of a large, useless network of disposals and atmos pipes, which are now streamlined across.

Aw man! This will conflict so much with my Box medbay PR ::(

**Comment by jlsnow301** [comment]
> Aw man! This will conflict so much with my Box medbay PR ::(

Didn't see your PR but I'm willing to merge, maints changes there are streamlined so it wouldn't be difficult

**Comment by qwertyquerty** [comment]
Conflicts

**Comment by jlsnow301** [comment]
Will address later today￼

**Comment by jlsnow301** [comment]
And I have next to no clue how to properly merge maps together so this is presumably closed

**Comment by jlsnow301** [comment]
:|||||||||||||||||| merge newer map PR's ahead of mine and complained of conflicts

**Comment by St0rmC4st3r** [comment]
Ow

**Pull request closed without merging**
