### PR TITLE
Removes blocking from batongs

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request
title

## Why It's Good For The Game
being practically immune to melee because you held down alt = bad

## Changelog
:cl: Bluezorua
balance: walking while holding a stunbaton no longer causes it to start blocking
/:cl:

### CODE REVIEW

**Comment by KennyBadrige** [comment]
> being practically immune to melee because you held down alt = bad

This applies to every block in the game.

**Comment by ivanmixo** [comment]
This is ridiculous, yeah. Worst part is they "cut" themselves on it and you get a free win.

**Comment by BrumalLake** [comment]
> 
> 
> This is ridiculous, yeah. Worst part is they "cut" themselves on it and you get a free win.

just don't be bare handed 🐒 
reminds me, this dood didn't even remove the block flags

**Comment by BrumalLake** [comment]
also, nerfs your tider cattleprods which i'm pretty sure only someone who would go at a lawman barehanded would use

contractor and telescopic too maybe but i can't be bothered to check all the child objects

**Comment by ToasterBan** [comment]
> also, nerfs your tider cattleprods which i'm pretty sure only someone who would go at a lawman barehanded would use
> 
> contractor and telescopic too maybe but i can't be bothered to check all the child objects

doesn't change contractor/telescopic batongs since they are under classicbaton/ and not baton/ + they never had a block level

**Comment by BrumalLake** [comment]
> 
> 
> > also, nerfs your tider cattleprods which i'm pretty sure only someone who would go at a lawman barehanded would use
> > contractor and telescopic too maybe but i can't be bothered to check all the child objects
> 
> doesn't change contractor/telescopic batongs since they are under classicbaton/ and not baton/ + they never had a block level

they do have block upgrade walk actually not relevant though
still, the cattleprod

so, the block flags?

**Review by PowerfulBacon — COMMENTED** [review]
Alternatively remove blocking_nasty so when it blocks it doesn't attack back

**Review by PowerfulBacon — DISMISSED** [review]

**Comment by ToasterBan** [comment]
> Alternatively remove blocking_nasty so when it blocks it doesn't attack back

still doesn't remove the fact that you can be temporarily near-immune to practically any melee if you are in somewhere like maint, seccies can print/grab riot shields if they want to block

**Review by PowerfulBacon — APPROVED** [review]

**Review by Archanial — APPROVED** [review]

**Pull request merged**
