### PR TITLE
TGUI Say

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

Ports TGUI Say:
- https://github.com/tgstation/tgstation/pull/67116
- https://github.com/tgstation/tgstation/pull/67971

And some needed pre-req PRs:
- https://github.com/tgstation/tgstation/pull/67137
- https://github.com/tgstation/tgstation/pull/67265

Additional changes for BeeStation:
- Added explo, uplink, `:l`, `:r`, and `:h` channel handling
- Added support for `.channel` prefixes
- Tweaked colors
- The entire window is draggable, rather than just parts of it (excluding the textbox, so you can select text)
- The border has been tweaked slightly, it is not animated but has a minor gradient on both the top and bottom
- Added a border around the text input part of the box
- Added LOOC channel
- Legacy support pref, with typing indicators and all
- Typing `;` in Say mode will convert the radio prefix to `;`, and removing it will go back to Say.
- Shift+TAB and r-clicking the button will go back in channels.
- Re-opening the window on a different channel will no longer break the button contents.
- Added "show prefix" mode, which treats `:s ` as text in the input box while still updating the color and button.
- Pressing Esc on the game window with the say unfocused will exit the say.

SQL Update on merge:

```sql
UPDATE SS13_preferences SET preference_value = preference_value | (1<<14) | (1<<15) | (1<<16) | (1<<17) WHERE preference_tag = 2;
```

## Why It's Good For The Game

The "Say" verb is the most used and looks quite awful in my opinion, plus TGUI say is just really cool, and adds some nice features like the thinking indicator and forced-speech (AUGH!!!), as well as more accessibility to new players since the syntax of speech is baked into the say-box.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

**Newest appearance**

image

image

image

https://user-images.githubusercontent.com/10366817/215728897-4abcfa2c-82f2-4dd0-a4ee-5e026f05756b.mp4

image

image

image

image

New prefs

image

Light theme pref

image

</details>

## Changelog
:cl:
add: Added TGUI-Say (can be disabled in prefs, light theme also in prefs) - Tab to switch channels.
add: Added new TGUI Say keybinds - Y for Radio, U for LOOC (not currently rebindable).
add: Added TGUI input preferences (mostly unused currently).
add: Added glorfing to TGUI-Say - if you get hit hard enough, your message will be cut off with "-OW!!!", "-AUGH!!!", "-GLORF!!" or similar.
admin: Added logging to typing indicators.
add: Added OOC Verb "Refresh TGUI".
tweak: Legacy say hotkey macros (Ctrl+T, Ctrl+O) have been replaced with T and O.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Legendary PR

**Comment by llol111** [comment]
Holy smokes that looks awfull.
Ive mostly gotten over my "tgui bad on principle" phase, but man that just looks terrible.
We *have* decent and good looking tgui windows, why's it like this?
cant we just have the normal popup, but made in TGUI?

**Comment by itsmeow** [comment]
> We _have_ decent and good looking tgui windows, why's it like this?

Because it's built on IE11 with no modern CSS features, and no polyfills available to regular TGUIs because it needs to not be dependent on 5000 external dependencies.

**Comment by itsmeow** [comment]
> cant we just have the normal popup, but made in TGUI?

This is like 5x less functional and more likely to break but certainly possible

**Comment by llol111** [comment]
I dont know (or care, if im to be honest) about the technical workings in the background.
Im sure you have decent reasons for replacing what we have now, et cetera. 
Chat breaking all the time like normal tgui tends to do is a verry valid concern, i suppose.

It would, however, look a lot better.
As is, this looks bad.
Im sure you can justify this being a good thing anyways because >muh functionalities and shit 
🤷

**Comment by itsmeow** [comment]
Players will still have the option of old chat, so if you don't like the look you can use that

**Comment by itsmeow** [comment]
TM results:
- Default pref for say engine is wrong
- Add `:h, :l, ;r, :i`
- Add support for `.` instead of `:`

**Comment by BriggsIDP** [comment]
Getting some minor lag between pressing T and typing, resulting in me diving to the floor when I'm trying to emote.
when typing long sentences the jump from small box to large box is a bit jarring, as the last work moves around as you are typing it, not a huge deal but a little annoying.
Also esc doesn't seem to exit the window, meaning once its open you can't close it.

**Comment by Rukofamicom** [comment]
Seems way cooler than I initially thought it would. Chat window doesn't take up nearly as much of the play area and I almost immediately got over my "Blech, change" stage.

Played around with testing the messages being cut short:
* Is it intended for self-damage to cut the messages short? 
* I think it would be cooler if it cut the mid-typing messages shorter when someone gets cut off while talking.
* If the chat window isn't active, as in the player has clicked off of it to perform actions, box should close, or at least completely prevent glorfing to prevent abuse by opening a chat window and pre-typing a message before going somewhere potentially dangerous.

**Comment by itsmeow** [comment]
1. yes
2. it cuts it one character short, if the message is particularly long it trims it to 50 or so characters
3. sounds like overkill tbh, average player will not have time to care about this and you could already do this before

**Comment by Rukofamicom** [comment]
That explains the behavior I saw then, I only ever really noticed it cutting me off when the message was especially long. I think it should cut more of the message off when it's shorter, somewhere between half and a third, rather than sending most of the message.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Noticed the following issues during testmerge
image
Chat bubble is bugged using a small character.

image
Common doesn't change the window to radio correctly.

image
Clicking off the window doesnt allow you to press escape to close it.

image
image
If you enter a radio mode, then press t again, it breaks.

**Overall behaviour feedback**
Right now when you type :s it just changes the window to the security style and there is now no way to back out of it.
Imo the way it should work is:
- As soon as a message starts with :s, the window changes to the security theme but the :s remains in the message. (No need to press space afterwards)
- If you remove part of :s it changes back to normal say window.

**Comment by PowerfulBacon** [comment]
image
Some colour themes are very low contrast

**Comment by itsmeow** [comment]
> Right now when you type :s it just changes the window to the security style and there is now no way to back out of it.
Imo the way it should work is:

you can just hit backspace twice.

**Comment by PowerfulBacon** [comment]
The behaviour feels quite strange when combined with removing your :s tags at the start imo, just discovered you can backspace to go back (its a bit unintuative in that regard, keeping the tag would be an improvement imo).

**Comment by itsmeow** [comment]
> Clicking off the window doesnt allow you to press escape to close it.

This wasn't a thing on the old one either

**Comment by itsmeow** [comment]
image
Not supposed to.

**Comment by PowerfulBacon** [comment]
image
The multiline input isn't quite right

**Comment by itsmeow** [comment]
> The multiline input isn't quite right

What does this mean. How did you even manage to get it to offset like that

**Comment by PowerfulBacon** [comment]
Technically this works very well and looks excellent. With some relatively minor behavioural updates this will be great :+1: Excellent works, thanks for porting this.

**Comment by itsmeow** [comment]
> In the case of me, it shouldn't change the thing. In the case of say when you type :s it shouldn't delete your :s, but should change to the security radio (something like this imo)

I disagree, I think it looks cleaner and is more functional when it hides your radio key after typing it. The `:s` as really just leftovers from not having a proper UI. This retains the functionality and makes it look better.

**Comment by itsmeow** [comment]
> If you enter a radio mode, then press t again, it breaks.
can't reproduce this

**Comment by PowerfulBacon** [comment]
> Not addressable. This would have to be a global BYOND macro, the old one never did this either anyway.

You could just make it so that pressing escape on the game window sends a close message to the window

**Comment by Crossedfall** [comment]
> I mean.. I *could*, but also that wasn't a thing before

The difference is presentation. The old way was a very standard window with a close button and an obvious way to move it around and interact with it. That's not the case anymore. It should have a faster way to be closed to compensate for the reduction in elements.

**Comment by itsmeow** [comment]
> What is the algorithm that determines the position in which this new TGUI say box appears? In my case, it appears in this strange place every round, as shown in the screenshot above.

It starts at the same location as the old say box. It will retain its position for the round.

Determining which pixel the player is at on the screen and moving it would be *quite* the task.

**Comment by Eric-01** [comment]
> It starts at the same location as the old say box. It will retain its position for the round.

Unfortunately, it does not. For comparison, the classic window appeared in the center of my screen both vertically and horizontally.

> Determining which pixel the player is at on the screen and moving it would be _quite_ the task.

I'm not so sure. Since the camera always follows the character you are controlling, you could just position the TGUI say box relative to the viewport. In theory. Are there any corner cases?

**Comment by Eric-01** [comment]
> It starts at the same location as the old say box. It will retain its position for the round.

Unfortunately, it does not. For comparison, the classic window appeared in the center of my screen both vertically and horizontally.

> Determining which pixel the player is at on the screen and moving it would be _quite_ the task.

I'm not so sure. Since the camera always follows the character you are controlling, you could just position the TGUI say box relative to the viewport. In theory. Are there any situations where this is not the case?

**Comment by itsmeow** [comment]
> I'm not so sure. Since the camera always follows the character you are controlling, you could just position the TGUI say box relative to the viewport. In theory. Are there any situations where this is not the case?

Gonna be real with you, this issue I am not concerned with at all. The window will open on your screen somewhere when the game starts, you can move it to the spot you want and it will stay there the rest of the round.

Users can have varying size monitors, varying size game windows, different chat width, pixel scaling, scaling methods. All of these mean that the place where the player is could be anywhere.

**Comment by Eric-01** [comment]
That's fine. It was just a nitpick rather than an actual issue. However, speaking of the strange position of the new TGUI window (see screenshot above), I hope it's still worth fixing. If you need more information, please let me know.

**Comment by itsmeow** [comment]
I've moved it, is this better?

image

image

**Comment by Eric-01** [comment]
I don't see any difference :/

Classic-vs-TGUI-say

**Comment by Absolucy** [comment]
Perhaps whispering (`#` prefix) should appear on the say popup like it does with radio channels/ooc/etc?

**Comment by PowerfulBacon** [comment]
Default 3 talk icon looks pretty bad, I think just remove it and use default0 instead, or a static speech bubble. After that I'm fine with merging this

**Review by PowerfulBacon — APPROVED** [review]

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
