### PR TITLE
the IAA desc change all of you waited for.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
changes the IAA desc to saying that not murderboning is optional.

## Why It's Good For The Game

because it was confusing and dumb that nano IAA could murderbone but not syndie

## Changelog
:cl:
fix: fixed the nanotrasen IAA desc to not be confusing anymore
/:cl:
Unbenannt

### CODE REVIEW

**Comment by CthulhuOnIce** [comment]
There's two periods in that screenshot

**Comment by ghost** [comment]
fixed that shotly after

**Comment by qwertyquerty** [comment]
Yes.... YES...

**Comment by BeloneX** [comment]
ok now merge pls ok thx

**Comment by ghost** [comment]
@qwertyquerty  pls merge

**Comment by hackerjsimon** [comment]
noice
but I figured as an antag you would get the free kill pass memo

**Pull request merged**
