### PR TITLE
Disable jobs.txt loading.

### PR DESCRIPTION
**Pull request by francinum**
This causes bugs related to map job counts, and the differences between the two servers are so incredibly minor
as to practically not matter.

## About The Pull Request
Disables job.txt loading

## Why It's Good For The Game
hopefully addresses a problem related to some jobs spawning on other job's starting points due to a lack of points for them to spawn.

Honestly these should absolutely just be getting sent to the latejoin.

## Changelog
:cl:
config: Jobs no longer load from the txt file, This should hopefully solve some issues related to insufficient spawners.
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
Here is the effective difference between sage and golden right now, with golden being the starting point.


```diff
+ 2 CargoTech (Roundstart)
+ 1 SMiner (RS)
+ 1 Botanist (RS)
+ 1 SEngineer (LateJoin)
+ 1 MDoctor (RS)
+ 2 MDoctor (LJ)
- 1 Viro (RS)
+ 2 Scientist (RS)
+ 3 SOfficer (RS)
+ 2 SOfficer (LJ)
```

**Comment by PowerfulBacon** [comment]
What happens if they dont, the spawners just get maxed out?

**Comment by francinum** [comment]
The job datums themselves have a defined count of slots. The txt is for host redefinement.

We have zero reason to use it as the host and operators of the repo

**Review by Crossedfall — APPROVED** [review]
Config applied

**Pull request merged**
