### PR TITLE
[PORT] Lighting refactors/optimizations and the various fixes

### PR DESCRIPTION
**Pull request by mystery3525**
## About The Pull Request

Ports:
- https://github.com/tgstation/tgstation/pull/49693/
- https://github.com/tgstation/tgstation/pull/60954/
- https://github.com/tgstation/tgstation/pull/61164
- https://github.com/tgstation/tgstation/pull/61304
- https://github.com/tgstation/tgstation/pull/61332
- https://github.com/tgstation/tgstation/pull/61530
- https://github.com/tgstation/tgstation/pull/62042
- https://github.com/tgstation/tgstation/pull/62931
- https://github.com/tgstation/tgstation/pull/63017
- https://github.com/tgstation/tgstation/pull/63171
- https://github.com/tgstation/tgstation/pull/63860
- https://github.com/tgstation/tgstation/pull/64539

*Also adds AREA_USES_STARLIGHT to solars since /tg/ uses nearspace*

## Why It's Good For The Game

While *not necessarily* in [Things to Port](https://github.com/BeeStation/BeeStation-Hornet/projects/2), I believe some refactors and optimizations will be good for us trying to keep up with /tg/. Additionally has some prereqs for my bunch of INIT optimization ports coming soon :tm:

I hope this doesn't break anything

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

There isn't really any visual impact, its all refactors? It compiles all the way through though.

</details>

## Changelog
:cl: spookydonut, TiviPlus, Couls, Wayland-Smithy, GoldenAlpharex, LemonInTheDark, AffectedArc07, Watermelon914, ported by mystery3525
refactor: Initialize now should call parent
refactor: Area based lighting can be varedited and changed now
admin: /area/var/static_lighting proper varedit support
fix: restored lighting to areas that were supposed to have it
fix: Fix space lighting with lattices
fix: fixed lighting bug
fix: Fixed base lighting appearance inheritance.
fix: Areas loaded from map templates should generate their lighting objects upon being loaded, which means that admin or game-spawned map templates will now have functional lights.
fix: Fixed solars and nearstation areas being pitch black, restores the fullbright they ought to have
fix: Fixed some bugged lighting
fix: Fixed having a limited vision whilst in the abductor ship.
fix: fixed new areas over starlight areas not having lighting objects
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Is this the stuff that makes it so there isn't 4 darkness tiles per turf? If so, we seriously need that as a maptick optimisation especially for glow.

**Comment by mystery3525** [comment]
I have no idea what this does but I am trying and learning as I go

Also there's like, a couple optimization ports I want to do after this like https://github.com/tgstation/tgstation/pull/69079

**Comment by itsmeow** [comment]
For stuff like this some good testing evidence is using an image differ, it will render as mostly black if you compare the same area of the station with identical lighting

**Comment by itsmeow** [comment]
> Is this the stuff that makes it so there isn't 4 darkness tiles per turf? If so, we seriously need that as a maptick optimisation especially for glow.

This isn't that I don't think

**Comment by itsmeow** [comment]
> Is this the stuff that makes it so there isn't 4 darkness tiles per turf? If so, we seriously need that as a maptick optimisation especially for glow.

This isn't that I don't think

**Comment by Tsar-Salat** [comment]
Can you also do https://github.com/tgstation/tgstation/pull/60785/

Right now lighting.dm is way too goddamn big, and splitting it up would make tracking changes/bugs a lot easier

**Comment by mystery3525** [comment]
done https://github.com/BeeStation/BeeStation-Hornet/pull/8606

**Comment by itsmeow** [comment]
I would really like some testing evidence on this, use https://www.diffchecker.com/image-diff/ and take screenshots of the same area, especially outside, see if everything renders correctly.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
A PR like this requires testing evidence:
- Screenshot some lighting systems that use old lighting
- Screenshot some lighting that uses new lighting
- Screenshot an area that uses the area based lighting (such as the nukie base or abductor rooms)

**Comment by mystery3525** [comment]
Yeah, lost steam. I won't sit on this if anyone else wants to do it.

**Pull request closed without merging**
