### PR TITLE
ipc buff yeah

### PR DESCRIPTION
**Pull request by despong**
## About The Pull Request
IPCs don't die to heat damage quickly; fires should not kill easily and lasers should not be stupidly powerful

## Why It's Good For The Game
buff good now close those synthetic tear ejection ports

## Changelog
:cl:
balance: change burnmod to 1.7
/:cl:

### CODE REVIEW

**Comment by despong** [comment]
oops my dumb ass accidentalyl made 2 commits to the same fucking file but okay babby first pr
i hit the wrong button fuck i suck dick

**Comment by zeskorion** [comment]
no

**Comment by despong** [comment]
yes

**Comment by despong** [comment]
soon tm

**Comment by despong** [comment]
fuk so i suck at coding

**Comment by qwertyquerty** [comment]
no

**Comment by despong** [comment]
yeah i know i suck

**Comment by despong** [comment]
NO

**Comment by SomeAngryMiner** [comment]
IPC arent meant to be a combat race, but more of an utility asset, able to shrugg off most hazards (chemicals, radiation, lack of oxygen, pressure with simple equipmment, Easy limb repairing) in tradeoff of being unneffective for combat, wich is okay. IMO, this balance is unneeded.

**Comment by despong** [comment]
bruh ok fine dad

**Pull request closed without merging**
