### PR TITLE
Adds a new radio channel accessible from a maint spawn key

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
Adds a new radio channel, labeled as dev_chn, to the game! This channel can ONLY be accessed through a maint-spawn key, so its relatively secure.

## Why It's Good For The Game
Similar to the vacant com, its a blank slate to make into anything. Its a secret club kinda thing for the greytide.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

dev

</details>

## Changelog
:cl:
add: Nanotrasen has accidentily supplied maintenence workers with an older model of encryption keys, maybe you can locate and use them!
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
As cool as this idea is, the game already supports non-standard frequencies. We don't need a labeled greytide channel, since people can already use custom frequencies to communicate. Maybe adding a tunable custom channel where you can set the frequency of the :f channel on your headset?

**Comment by EvilDragonfiend** [comment]
the chat colour should be brighter at the dark theme. recommanded RGB is R120, G100, B140

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
This would need a full radio channel refactor to support custom channels rather than having this as a dedicated radio channel wasting up the :f channel

**Comment by PowerfulBacon** [comment]
If you want to refactor radios in order to let engineering add custom channels and make it so there aren't a limited number of fixed channels then go for it, however in the current state of radios this won't work.
Closing this PR since its just not viable.

**Pull request closed without merging**
