### PR TITLE
Security Rework Part 2 of ?: Red Alert

### PR DESCRIPTION
**Pull request by ike709**
## About The Pull Request

As part of the ongoing sec rework, enabling Red Alert will generally be a major buff to security, which will be nerfed outside of Red Alert. As a result, we need to discourage declaring Red Alert when there isn't an actual need for it.

I am taking suggestions, because I'm not really sure what the best way to do this is.

Proper CL coming when this is done.

## Changelog
:cl:
refactor: Changed Red Alert.
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
Maybe allow swiping when a certain amount of people are revs/cult or dead, or check how intact the brig is or if most of the station is filled with plasma

**Comment by eeSPee** [comment]
>will be nerfed outside of Red Alert

How will security be nerfed outside of red alert?

**Comment by BrumalLake** [comment]
> 
> 
> > will be nerfed outside of Red Alert
> 
> How will security be nerfed outside of red alert?

check part 1

**Comment by ike709** [comment]
and part 3

**Comment by ToasterBan** [comment]
cargo shuttle being delayed makes no real sense, why would centcom make one of their only ways of getting certain supplies take longer if it is blaring an alarm that shows it is in an emergency?

**Comment by ike709** [comment]
Because they don't want to risk losing it.

**Comment by eeSPee** [comment]
> check part 1

Part 1 wasn't a nerf.

> cargo shuttle being delayed makes no real sense

Agreed. How is disrupting cargo and salaries gonna affect security?

You may say, yea but they won't be able to order mindshields, but they will instead just buy them before, and just go full lethal on code red with their roundstart energy guns.

 -

All in all, this 'remake' doesn't really address the biggest problem with security at the moment, and only adds hurdles that are easy for shitsec to overcome, and rewards them with firepower for overcoming them.

So basically, code red now means lethals out, kill everything on sight... I know that code red is not used as much, but is it really a good idea to allow security to 'go to war' with the station and have IC reason to kill as many people as possible? We already have sec officers being overzealous to abuse people, will this not remove the barrier that keeps them from going too far?

The current problem is that security already has an arsenal of strong roundstart weapons and equipment that can easily turn the odds in their favor, with very few 'legal' counters to stamina damage. These fixes address none of that.

**Comment by Sinestia** [comment]
There was talk around part 1 of greatly changing what's available in the armory, I assume that's what the nerf means. 

This seems to move red alert to being more of a martial law situation which seems good to me. Red alerting is something that's pretty policeable by admins

**Comment by BrumalLake** [comment]
Yeah, red alert should be like declaring martial law, as delta alert lasts the last few moments you have on the station before a nuke or blob
Also, delaying the shuttle encourages express pods, which are a nice way to get mindshields for sec when you critically need them

**Comment by eLeCtrOssSnake** [comment]
> Maybe trigger it when a certain amount of people are revs/cult or dead, or check how intact the brig is or if most of the station is filled with plasma

No, shadow caps enabling random stuff is pretty bad and totally not straightforward.
________________________________

**Comment by Rukofamicom** [comment]
Having it act like a lockdown would make red alert pretty inconvenient and only used when necessary, or when antagonists are mid hijack.

* Red alert = all non-public doors change to requiring command access to quickly open. All doors now open with command access.
* Add an "emergency override lever" to air locks which takes 10-15 seconds to open, active only on red alert. 

This will simultaneously put a strain on other players' mobility while also enabling slow emergency access to areas they would not normally have, so long as they aren't actively under attack whilst prying a door open.

**Comment by eLeCtrOssSnake** [comment]
Is red alert access overriding necessary? It should be like a status for authorizing security to do everything, isn’t it?

**Comment by pickleinjar** [comment]
like some unbreakable lockers that wont open before red alert

**Comment by eLeCtrOssSnake** [comment]
> like some unbreakable lockers that wont open before red alert

I don’t know, it’s not really a good solution too, because it’s some extremely capped gear that is like 100% guaranteed and everybody knows when and why it appears, so people could red alert on purpose to get that stuff? Though what’s the problem in red alert? Only one thing that comes up in mind is that maybe security officers could red alert themselves but I am not really sure on that idea too.

**Comment by eLeCtrOssSnake** [comment]
> > check part 1

>

> Part 1 wasn't a nerf.

>

> > cargo shuttle being delayed makes no real sense

>

> Agreed. How is disrupting cargo and salaries gonna affect security?

>

> You may say, yea but they won't be able to order mindshields, but they will instead just buy them before, and just go full lethal on code red with their roundstart energy guns.

>

>

> All in all, this 'remake' doesn't really address the biggest problem with security at the moment, and only adds hurdles that are easy for shitsec to overcome, and rewards them with firepower for overcoming them.

>

> So basically, code red now means lethals out, kill everything on sight... I know that code red is not used as much, but is it really a good idea to allow security to 'go to war' with the station and have IC reason to kill as many people as possible? We already have sec officers being overzealous to abuse people, will this not remove the barrier that keeps them from going too far?

>

> The current problem is that security already has an arsenal of strong roundstart weapons and equipment that can easily turn the odds in their favor, with very few 'legal' counters to stamina damage. These fixes address none of that.

I agree with everything but the roundstart arsenal, like it’s obvious that security should have some kind of upperhand against antags and even non-antags(aka angry assistants) because security will serve no purpose if they won’t have anything, and making them have only like flashes will also render them totally useless. About firearms like shotguns and eguns, shotguns were already nerfed, antags have counters for eguns, non-antags or other non-uplink antags can easily think to overcome security weaponory. The antag and non-antag security defeat game does not only end on security having arsenal. There are a lot of creative ways to outplay security. Security arsenal is pretty straightforward, I wouldn’t call that an issue of somekind.

**Comment by ItsTisme** [comment]
>allow swiping when a certain amount of people are revs/cult or dead

This would make a horrible meta info issue since you can essentialy check the state of a antag.

**Comment by bloons3** [comment]
> > allow swiping when a certain amount of people are revs/cult or dead
> 
> This would make a horrible meta info issue since you can essentialy check the state of a antag.

The other problem is meta-information.

How does the red alert system know (other than suit sensors) that X amount of people are revs/cult/dead.

----

There's functionality for doors to automatically unlock in red alert, maybe extending that to more areas of the station?

**Comment by eLeCtrOssSnake** [comment]
Woudn’t red alert make it worse for the crew to handle antags with lifted access, like even with a more loosey station?

**Comment by ike709** [comment]
Imagine bitching instead of offering decent alternatives.

**Comment by eLeCtrOssSnake** [comment]
I am sorry but I don’t see the real issue in RED ALERT.

**Comment by BrumalLake** [comment]
wah wah meta info cause heads are gonna be swiping for no reason every 10 minutes on sage
just make it a formula based on pop cause you can never be sure how many people are on the station

**Comment by BrumalLake** [comment]
Maybe some areas like toxins grav gen and tcomms should be locked down during red
Hop line too

**Comment by BrumalLake** [comment]
What if silicons also temporarily got robocop or a lockdown law
Or if upload consoles didnt work during alert

**Comment by eLeCtrOssSnake** [comment]
> Maybe some areas like toxins and tcomms should be locked down during red

And what if you happen to be in toxins/tcomms while red alert?

**Comment by Sinmero** [comment]
>I am taking suggestions, because I'm not really sure what the best way to do this is.

Looks like you are trying to find a solution for a problem you invented yourself.

Seccies are encouraged to use nonlethal methods and are equipped accordingly. If there is a serious threat they are supposed to grab proper weapons at armory.
What is the point of nerfing the nonlethal way of detaining people and giving more incentive to use lethals instead?

**Comment by WhyIsCaeciliusTaken** [comment]
How about this:

Once red alert is triggered, the crew is given an alert giving them a short period of time to return to their departments.
Once this is complete, all doors on the edges of departments (leading to maint or a hallway) become brig access only, and a series of lockdown doors (new additions that are bolted open during lower alerts) close in the halls, also requiring brig access to open.

**Comment by eLeCtrOssSnake** [comment]
> How about this:
>
> Once red alert is triggered, the crew is given an alert giving them a short period of time to return to their departments.
> Once this is complete, all doors on the edges of departments (leading to maint or a hallway) become brig access only, and a series of lockdown doors (new additions that are bolted open during lower alerts) close in the halls, also requiring brig access to open.

This sounds more like delta than red.

**Comment by eLeCtrOssSnake** [comment]
>>I am taking suggestions, because I'm not really sure what the best way to do this is.

>Looks like you are trying to find a solution for a problem you invented yourself.

>Seccies are encouraged to use nonlethal methods and are equipped accordingly. If there is a serious threat they are supposed to grab proper weapons at armory.
>What is the point of nerfing the nonlethal way of detaining people and giving more incentive to use lethals instead?

Yes, I totally agree. I am thinking that red alert is more of a security behavior changer, untying their hands accordingly, rather than actually doing something with the station. There’s delta for crazy stuff. But I wouldn’t think about changing delta neither. Both seem pretty logical.

Maybe what I would change, is round-start blue alert. Green never stays for too long unless greenshift(though not guaranteed too).

**Comment by eLeCtrOssSnake** [comment]
Maybe add some prerequisites to blue alert.

**Comment by SergeiKoralev** [comment]
> we need to discourage declaring Red Alert

Can you perhaps force red alert to also generate a reason message? It doesn't have to be provided to crew, but perhaps have it send an automated message to centcom or just admin log and wind up in game.log. That way we can more easily see what reason things are done as admins. It'll make review of conduct significantly easier and reduce the number of HOS's swiping red because uwu gun. 

Additionally if you haven't considered it having a stand-down condition might be good as well, either a timer (like 30 minutes or so) so if a threat doesn't persist the alert level doesn't just get forgotten about. 

> se, why would centcom make one of their only ways of getting certain supplies take longer if it is blaring an alarm

Personally I agree with the sentiment here. Red alert shouldn't delay the shuttle significantly, although it would be interesting if there was additional "processing time" when it reaches CC just to make sure that there is no contraband getting lifted, or fugitives getting off station. (not that that is IC possible, but for the sake of realism)



> code red now means lethals out, kill everything on sight... I know that code red is not used as much, but is it really a good idea to allow security to 'go to war' with the station and have IC reason to kill as many people as possible?

And people who misuse code red or assume that code red means shoot crime on sight will be subsequently removed from security jobs. - JanniAdmin

**To those of you saying that red should be martial law. Read SOP.**

I doth quote from the book of SOP, main page, alert levels
"Code Red - Martial Law
Situational alert level called in the event of imminent threat to the station. This should be performed by two heads of staff in cooperation with one another when there is a clear and present danger to the station."



> Having it act like a lockdown would make red alert pretty inconvenient and only used when necessary, or when antagonists are mid hijack.
> 
> * Red alert = all non-public doors change to requiring command access to quickly open. All doors now open with command access.
> * Add an "emergency override lever" to air locks which takes 10-15 seconds to open, active only on red alert.
> 
> This will simultaneously put a strain on other players' mobility while also enabling slow emergency access to areas they would not normally have, so long as they aren't actively under attack whilst prying a door open.

I love the idea here, Ruko, but as a medical main I can tell you 100% that people are gonna die because of this unless a: normal access requirements do not change to your department/workspace, and B: those levers are useable by anyone. 

Imagine how annying it would be to need a toxins treatment kit from med storage. You go through one (or two) airlocks depending on where they are, get back, and find out that nobody pulled the defib out and now you need it because your patient died from toxins damage while you were messing about with funny levers on doors. 


Alternately you could perhaps (with some struggle) deepen the red alert system and declare specific types of disasters (Medical, Engineering, Security, Station Wide) which grants varying levels of access across the station. (Medical gives paramedic and/or brig phys access to general department areas (excluding high security areas like command, head's offices, toxins, brig, etc... depending on how you want to run it). 

**overall thoughts**
I think this is fairly interesting as an idea. I'm interested to see how it works out depending on the implementation and snowballing that happens. Obviously there's going to be some work on the administrative side with specific regard to policy depending on how things change, and especially in regard to enforcement.

**Comment by utilbird** [comment]
Red alert has been always been (mostly) RP and I believe it should continue to be that way. The best interactions in the game are the ones that players create

Would creating a somewhat-complicated alert mode with deep mechanical tie ins make the game more fun? Or just more complicated? Not a rhetorical question either

**Comment by Sinestia** [comment]
> 
> 
> Red alert has been always been (mostly) RP and I believe it should continue to be that way. The best interactions in the game are the ones that players create
> 
> Would creating a somewhat-complicated alert mode with deep mechanical tie ins make the game more fun? Or just more complicated? Not a rhetorical question either

how do you get rp with no grounding

**Comment by Raven-Industries** [comment]
More of a flavor thing than actual substance, but maybe have red alert push department-specific messages to all crew? For example, engineering gets something like "power down all non-essential systems and prepare for catastrophic station damage", medical could get "begin preparations for mass casualty events", service jobs get "cower like the unimportant plebeian you are" or something like that. Maybe the captain and/or AI is able to specify beforehand what the message is.

**Comment by eeSPee** [comment]
I really don't like the direction this is going.

First of all, this inconveniences other departments so that sec can validhunt better. Do we really need the game to stop so that sec can do its thing?
Secondly, all you need is to press a button, and all disablers turn into energy guns. That's all it takes. For 2 heads to mobilize and push a button.
Finally, code red antags (cult, revs, blob) aren't really that strong to warrant such a big nerf. For example, blob cannot do much if the station was not ravaged by a previous event, and revs/cult require a lot of effort to set up. Would it be fun to work to get lategame cult/revs, just so that sec can turn into killing machines and put the entire station on lockdown?

**Comment by PowerfulBacon** [comment]
One thing I hate the most is just calling the shuttle to avoid fighting off any major threats to the station, guaranteeing a win through preventing anyone from winning rather than through actual skill.
I think delaying the shuttle on red alert, but making it buff security would be an interesting concept (Security checks to prevent shuttle getting attacked or w/e) since it would mean either you are fighting, or fleeing and would give more interesting outcomes from the game since you actually have to play the game rather than not play the game.
If the antags start winning then the alert can be lowered by the command crew, which will weaken security however cause the shuttle to arrive faster, or the command crew can enable red alert and go head-on against the threats of the station.
It's a deep thought, but the only way to ensure that you will win is to not play.
The problems this could encounter is in non-antagonist threats such as meteors, where raising the alert to red will lengthen the emergency shuttle but security aren't the ones dealing with the red alert so raising the alert up will hinder the station.

Stuff that would destroy the station or you can't run from are pretty fun since you are forced to play the game the fun way, but currently not much does this apart from blob, xenos (Recently added and improved xenos a lot) but on gamemodes like cult, the second a tiny cult is found the shuttle is called and everyone is leaving. Command are so inclined to win that they end up making the game less fun and cause everyone to avoid playing the game the fun way.

**Comment by eeSPee** [comment]
>Stuff that would destroy the station or you can't run from are pretty fun since you are forced to play the game the fun way, but currently not much does this apart from blob, xenos (Recently added and improved xenos a lot) but on gamemodes like cult, the second a tiny cult is found the shuttle is called and everyone is leaving. Command are so inclined to win that they end up making the game less fun and cause everyone to avoid playing the game the fun way.

But granting sec more lethals and access on red alert will be a huge nerf, that will make said antags put less of a fight and be less fun to play.

**Comment by PowerfulBacon** [comment]
A huge nerf to sec or antags? To sec its a nerf while not on red alert, to antags even if sec put up a stronger fight having a fight in the first place is more fun than the other team just leaving to screw you over with no punishment or counter.

**Comment by MilkmansWife8291** [comment]
Atrocious change, it's shocking how you people are in charge of what's supposed to be the fun and good version of TGcode when you approve trash like this.
1. Security does not need buffs. Security wins the vast majority of the time on Bee, antags have abysmal success rates, we don't need changes that make it safer and more advantageous for security.
2. ID pin removes fun and options from the game. It prevents an officer from having his gun used against him, it prevents the gun from being stolen and used by someone else. I have no idea what goes through your mind when you approve changes like this.
3. Being called to brig and issued a new gun from the armory when things get serious is one of the most iconic and fun moments of a security officer's shift. With the red alert lethals change, it's likely red alert will be declared and you will automatically have lethals without the armory ordeal, stripping the fun moment from the game.

**Comment by ike709** [comment]
> Atrocious change, it's shocking how you people are in charge of what's supposed to be the fun and good version of TGcode when you approve trash like this.

lol

**Comment by BrumalLake** [comment]
>    Security does not need buffs. Security wins the vast majority of the time on Bee, antags have abysmal success rates, we don't need changes that make it safer and more advantageous for security.

bruh no ones gonna red alert for a normal antag thats not gonna roll the station like blood cult or revs, this doesnt make it impossible to greentext, this makes it even easier because of what happened to enablers

**Comment by BrumalLake** [comment]
I feel like the cargo shuttle delay is enough, hopefully people start ordering things more with #4572 if it gets merged or use express pods on red, haven't seen any unreasonable red alerts on sage since part 1 started testmerge

**Comment by eeSPee** [comment]
> To sec its a nerf while not on red alert

It literally isn't. It's a nerf to every other department, as it inhibits their functionality.

Security gets lethals and the go to kill on sight.

**Comment by BrumalLake** [comment]
Hos should probably get auth access removed since people keep claiming that sec red alerts instead of heads

**Comment by DatBoiTim** [comment]
I think this PR needs to rework alert levels overall.

Delta Alert is uncommon, and lasts a short while, despite being able to have major implications if it lasted more than 1 minute.

Step 1: Make current delta alert just a self-destruct sequence or whatever.
Step 2: Make the new delta alert akin to a General Quarters sort of thing. Used when nukies/blob/xenos/etc. This alert generally means: Everyone is armed and supposed to contain/stop a threat as well as extended access for crew. This would be above red alert.

One thing to account for is alert levels also decreasing evac shuttle time. This is one of the times I see red alert FNR. Bored after a 1 1/2 hour round? Heads red alert and call shuttle.

Step 3: Rethink shuttle times with regards to alert. Probably should be slower to account for sec basically becoming unstoppable.

Unfortunately right now, alert status fuckery is a thing admins have to handle. And there likely isn't a good mechanical solution for making alert levels have cons. Adding pros just adds more temptation for alert level fuckery, which puts more on the admin team to manage.

If you want Bay Smart Smart pistols, it wouldn't be tied to alert level. Usage is based on ID equipped. And lethals are managed through a program.

Thus I conclude that a graceful solution for alert level may not be worth the time, but instead moving closer to how Bay Smart Pistols work

**Comment by wraith-54321** [comment]
not joking, add a constant alarm like firelocks have, it will make it so people dont want to red, fastmostation(icebox) is really bad 30 minutes into the round due to the non-stop firelock alarms, it gets the shuttle called

**Comment by DatBoiTim** [comment]
> not joking, add a constant alarm like firelocks have, it will make it so people dont want to red, fastmostation(icebox) is really bad 30 minutes into the round due to the non-stop firelock alarms, it gets the shuttle called

Klaxons it must be klaxons

**Comment by ike709** [comment]
I don't have time for this and most people are screeching rather than giving ideas like I asked.

**Pull request closed without merging**
