### PR TITLE
Sergei's Map Modernization Project part 2

### PR DESCRIPTION
**Pull request by SergeiKoralev**
## About The Pull Request

This PR tackles the lights and intercomms on Box Station, creating directional paths for instances of each device and including them in this PR. 

Unexpected and unknown side effect: Mapping debug tools will not detect the directional path types for intercomms.

## Why It's Good For The Game

this PR helps mappers not go insane by having to manually pixel step each intercom or light switch that they need to include, and instead simply creates automated versions of each direction that could be required (North, South, East, West).

## Changelog
:cl:
add: light switches to areas that previously did not have them
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
Looks like a small QOL change to me, which is why i didnt put this to vote.  I'm not good with mapping stuff, though, so i'd not know if this had a major issue

**Comment by SergeiKoralev** [comment]
> Looks like a small QOL change to me, which is why i didnt put this to vote. I'm not good with mapping stuff, though, so i'd not know if this had a major issue

It's meant to be QOL for mappers, making directional items for mappers to utilize. As stated in the PR, the biggest issue is that the directional type path for intercomms breaks the map debug check. HOWEVER, the intercom overlay still works, so I see that as mostly small potatoes.

**Comment by zeskorion** [comment]
I gotta ask, what exactly do you mean by breaking the map debug check?
do they make it not work? not render properly?

**Comment by SergeiKoralev** [comment]
Under the mapping debug options in game there is a check along the lines of debug maps(station z levels) that gives you all the rooms without apcs, multiple apcs, no air alarms, lights missing. One of those checks is "does the area have an intercom" and I suspect due to the path change the directional ones are not yet included in that check, so thy don't register in that check and areas with intercoms get listed as not having any.

**Comment by zeskorion** [comment]
> Under the mapping debug options in game there is a check along the lines of debug maps(station z levels) that gives you all the rooms without apcs, multiple apcs, no air alarms, lights missing. One of those checks is "does the area have an intercom" and I suspect due to the path change the directional ones are not yet included in that check, so thy don't register in that check and areas with intercoms get listed as not having any.

should be an easy change to include the intercomms in that check, no?

otherwise, seems good

**Comment by SergeiKoralev** [comment]
In theory it should be. I just need to figure out where the code for that check is. I'll start asking around.

**Comment by zeskorion** [comment]
> In theory it should be. I just need to figure out where the code for that check is. I'll start asking around.

ctrl +f all files, find all. it's a godsend

**Comment by qwertyquerty** [comment]
stale

**Pull request closed without merging**
