### PR TITLE
The Great Resprite: Atomized Edition (Tools volume)

### PR DESCRIPTION
**Pull request by SomeAngryMiner**
## About The Pull Request

Second part of the PR, wich i atomized for mantainer's sake.
the whole set can be seen here: #2339 
This one's toolset and belt,

## Why It's Good For The Game

Unique visuals, color marked equipment as tools and a facelift of some old sprites like toolbelts and inducers, Unified pallete and design if the entire set passes.

I swear this is the only thing that uses so much yellow.

image
image
image
image

## Changelog
:cl:
add: Engineering tools and toolbelts got a complete redesign.
/:cl:

### CODE REVIEW

**Comment by Moccha-Bee** [comment]
yes please.

**Comment by ike709** [comment]
👎 I think the colors need some work. The tools are not nearly as visually distinct as they used to be. More color variety would help.

**Comment by SomeAngryMiner** [comment]
alright, ill add some color variety tomorrow.

**Comment by Isy232** [comment]
I agree with Ike, maybe make the wrench and crowbar be opposite diagonals like the old ones, make the jaws of life red again and in general lower the amounts of yellow.

I really like the new designs, but I would like them even more if you could make them all not yellow.

Also, the new plasma tanks look kinda dumb, like they are laying on a table instead of being held, maybe make it look more vertical.

**Comment by PowerfulBacon** [comment]
I like them, but I find it very hard to tell the difference between these 3
image

**Comment by SomeAngryMiner** [comment]
> I agree with Ike, maybe make the wrench and crowbar be opposite diagonals like the old ones
 
Ill edit wrench, then.

>make the jaws of life red again and in general lower the amounts of yellow.

already doing that, but red jaws of life look incredibly awful, sorry.

> I really like the new designs, but I would like them even more if you could make them all not yellow.

 same point as above. Do note that this is the only set that'll be yellow to match an engineering/tool style, while medbay would be white, cargo equipment would have the copper color, and so on, im not turning everything into butter, chill.

> Also, the new plasma tanks look kinda dumb, like they are laying on a table instead of being held, maybe make it look more vertical.

plasma tank is not included in PR, check icon diffs.

**Comment by SomeAngryMiner** [comment]
> I like them, but I find it very hard to tell the difference between these 3
> image

If you want i can edit them, but do note that they have entirely different screen styles, so gotta see them ingame first.

**Comment by Isy232** [comment]
Perhaps add the little top thing back to the t-ray scanner, but otherwise I can tell the tools apart.

Also, I was being a little picky with the jaws of life, if they look like shit when you make em red keep em yellow.

If I want to be really picky, I would like if the crowbar was at the same angle as before.

I do really like these sprites though, they look a lot less cartoonish and a lot more like something you might really see on a space station. They also look far cooler.

**Comment by SomeAngryMiner** [comment]
image
removed most of the yellow on the three first welders, used white and  purple for jaws of life and hand drill for the advanced tools to fit the ex welder, and added a new sprite for syndicate superglue (it looked awful)

**Comment by qwertyquerty** [comment]
Would you say this is ready?

**Comment by SomeAngryMiner** [comment]
this is ready, yes.

**Comment by SomeAngryMiner** [comment]
updated the awful plunger sprites, should fit the color set and be less terrible overall now.

**Comment by PowerfulBacon** [comment]
Fix the conflicts, ping me, then I'll put it to testmerge then a vote

**Comment by ike709** [comment]
Still conflicting.

**Comment by BitBite112** [comment]
I did a poll and sadly most people don't like the new sprites. IMO it's not only the colors in some, but also the design that aren't great.

**Comment by PowerfulBacon** [comment]
> I did a poll and sadly most people don't like the new sprites. IMO it's not only the colors in some, but also the design that aren't great.

Forum polls aren't properly representative of the thoughts in general, since not all our players use the forums and it's more likely to attract people that really dislike the new icons than the people that thing it's a small improvement

**Comment by BitBite112** [comment]
> > I did a poll and sadly most people don't like the new sprites. IMO it's not only the colors in some, but also the design that aren't great.
> 
> Forum polls aren't properly representative of the thoughts in general, since not all our players use the forums and it's more likely to attract people that really dislike the new icons than the people that thing it's a small improvement

34 people have voted now, that's like the majority or a very large portion of the playerbase at least and I think more will vote.

**Comment by SomeAngryMiner** [comment]
image
Based on feedback, the wirecutters, crowbar and wrench have been adjusted accordingly.

**Comment by BitBite112** [comment]
I like the wrench and the crowbar is a lot better too, but I just don't like the wire cutter and multitool's design, they're not appropriate for what they're supposed to do. 
The multitool looks unfamiliar and too high tech, but would be good if it were the analyzer instead with a darker hue while the wire cutter is too small not because of what you need to click, but it looks like the little cutter I got in my circuitry kit for cutting small cable while it should be more heavy duty. It's not a bad sprite, it looks quite good, but it's not the type of wire cutter I'd want in SS13 where I'd need to cut what I assume are huge cables connected to the solar's and SM/
I'd also go back to the T5 components and make the manipulator and laser more distinct and maybe remove the nuzzle on the matter ban, although the latter isn't too bad.

**Comment by PowerfulBacon** [comment]
I would say the multitool needs a way to be more distinguishable from the t-ray scanner

**Comment by Unidentified-Biohazard** [comment]
I will be honest, I prefer the old tools. These new ones look kind of bland. I wish that we could have both but that is probably asking too much.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
