### PR TITLE
Re-adds separated chemicals to glow berries

### PR DESCRIPTION
**Pull request by USB3pt0**
## About The Pull Request

Adds Separated Chemicals to the list of traits of glow berries.

## Why It's Good For The Game

Gives robust botanists more fun things to do.  Gives unrobust botanists something to aspire to.

## Changelog
:cl:
add: added separated chemicals to glow berries.
/:cl:

### CODE REVIEW

**Comment by MACIEKBAKI** [comment]
When /tg/ removed it the noreact trait might have been removed from the code itself. You should check the compile errors

**Comment by USB3pt0** [comment]
No, it's still in the code as-is.  Strange Seeds can get it.

**Comment by qwertyquerty** [comment]
Nah it compiled, just the dumb checks didn't pass because the dum mariadb 404 thing

**Comment by USB3pt0** [comment]
merge this so i can make mega drug gas tomatoes before the station gets plasmafloodfired for the eightieth time

or don't i'll survive

**Pull request merged**
