### PR TITLE
Gives the det a chem scanner in the PDA 

### PR DESCRIPTION
**Pull request by JixS4v**
## About The Pull Request

Detectives now have access to reagent scans in their PDA, it can now function like a full regular health scanner

## Why It's Good For The Game

Chemical scans are an important part of forensics, and dets already get a physical one. This makes it so det players don't have to get a health scanner and fill up their already pretty full inventory.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image
</details>

## Changelog
:cl:
tweak: Gives the detective a chem scanner in the PDA
/:cl:

### CODE REVIEW

**Comment by Marshmellow105** [comment]
image

**Comment by itsmeow** [comment]
Detectives need chem scans? For what?

**Comment by JixS4v** [comment]
Checking the reagents someone had in their blood upon dying is very helpful for knowing how and if someone got poisoned.

**Comment by Fronsis** [comment]
> Detectives need chem scans? For what?

What Jix54v pointed out, if a det arrives at a scene they can determine if the victim was poisoned and with what reagent, at the moment the only way they can identify reagents it's by scanning syringes/beakers with their det scanner however they've always lacked a health scanner chem module, they only had the default one this just complements the kit a little more, it's fairly better than the det buying/borrowing a health scanner, might as well have their pda cover both health and chemicals.

**Comment by Nakalon** [comment]
Good addition given the recent changes to the death rule!!

**Review by Rukofamicom — APPROVED** [review]
Seems to fit, but wow that is a lot of tools.

**Pull request merged**
