### PR TITLE
Fix checker tiles

### PR DESCRIPTION
**Pull request by DrDuckedGoose**
## About The Pull Request

At some point the new sprite for the checker tiles was replaced with another one. This one doesn't really match our new tile art style, the old one was fine.
How it was
image
What it was changed to
image

## Why It's Good For The Game

Improves sprite

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

Before
image

Fixed
image

</details>

## Changelog
:cl:
fix: Switch checker tiles back to their 'intended' sprite
/:cl:

### CODE REVIEW

**Comment by DrDuckedGoose** [comment]
Holy commits

**Comment by MarkusLarsson421** [comment]
That's a lot of commits for one sprite change. lol

**Comment by DrDuckedGoose** [comment]
I think my master is messed up, I only made one

**Comment by MarkusLarsson421** [comment]
Weird, doesn't seem to have affected the end result being PRd though.

**Comment by PowerfulBacon** [comment]
This probably was accidental, but I do prefer the colours on the bugged sprite even if the depth looks worse.

**Comment by DrDuckedGoose** [comment]
You can achieve the colors with the other checker tiles we have and some decals 👍

**Review by PestoVerde322 — APPROVED** [review]
I don't mind them, also fix good

**Comment by PowerfulBacon** [comment]
I know you can, but I actively dislike the colour of these tiles for being far too exaggerated, leading to a lot of visual noise

**Comment by MarkusLarsson421** [comment]
Why not both?

**Comment by DrDuckedGoose** [comment]
> Why not both?
Sure

**Pull request merged**
