### PR TITLE
Slight shotgun screenshake.

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Gives shotguns some recoil, for a more satisfying kick when firing.

## Why It's Good For The Game

Shotguns are a powerful tool when used in close range, now with a little screenshake on firing too. Bulldog drum shotgun has no recoil along with the toy shotgun, since the toy shotgun has no blast and the bulldog is an advanced shotgun with 'integrated recoil control systems'.

## Changelog
:cl:
add: Adds small recoil to shotguns.
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
Just make it inject skewium into user

**Comment by PowerfulBacon** [comment]
good idea

**Comment by Isy232** [comment]
This is an actual good nerf.

It makes the shotgun cooler to use but a little less practical.

Also very realistic, using a powerful shotgun would jostle you around somewhat.

**Comment by utilbird** [comment]
Implying having ballistic weapons on a space craft is realistic

**Comment by Isy232** [comment]
> Implying having ballistic weapons on a space craft is realistic

I aint no firearms expert but what else would you use?

Sure the concussive effects on the ears are glossed over as well as the ricocheting but I don't see why else they wouldn't work.

**Comment by TheFakeElon** [comment]
@Isy232 realistically speaking, you would not want to use high velocity projectiles in a large metal tin can with fragile windows. 

It doesn't make much sense that a research station would need a large weapons arsenal to defend against the syndicate. Most efforts would be put to making sure they don't get on in the first place.

I'm going off topic and we're lrp anyway lmao, shotgun go clickclack 🔫

**Comment by ghost** [comment]
> > Implying having ballistic weapons on a space craft is realistic
> 
> I aint no firearms expert but what else would you use?
> 
> Sure the concussive effects on the ears are glossed over as well as the ricocheting but I don't see why else they wouldn't work.

Miss your target and you just either hit someone else down the long hallway or ripped a hole into the hull and killed everyone.

**Comment by PowerfulBacon** [comment]
The shake comes after you shoot rather than predicting when you are about to shoot and shaking the screen 1 second before so you can't aim at anything.

**Pull request merged**
