### PR TITLE
Slips rebalance

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request

A few changes:
- No-slip chameleon shoes are now lubeproof. Has been bumped from 3 TC up to 4 TC. 
- Slipocaust cluster grenade filled with lube grenades available for 3 TC to all Syndicate. 
- Lube no longer gives you confusion, but still slips you even if walking unless you have lubeproof shoes.
- Combat galoshes (combat boots with no-slip to water) now available for 2 TC to all Syndicate. Nukies get these by default.
- Several other current shoes upgraded from no-slip to lubeproof including deathsquad SWAT boots, MK-HONK combat banana shoes and MK-HONK prototype banana shoes. Note that the prototype version hasn't got no-slip when they're unpowered. 

## Why It's Good For The Game

Lube can be helpful but without being lubeproof it's not possible for you to take full advantage of the highly lubricated areas you've created. This adds several ways for obtaining lubeproof shoes and a new lube explosive, whilst making lube less cancerous in general. 

## Changelog
:cl:
add: Slipocaust cluster grenade now available for 3 TC.
add: Combat galoshes now available for 2 TC. Nukies get these by default. 
tweak: No-slip chameleon shoes cost +1 TC but are now lubeproof.
balance: Lube no longer confuses.
tweak: Several other no-slip shoes now are lubeproof.
/:cl:

### CODE REVIEW

**Comment by eeSPee** [comment]
Maybe barefoot sliding should still get you stunned?

**Comment by PowerfulBacon** [comment]
The whole point of lube is to be pretty cancerous, I'd say keep the confusion since it was already nerfed enough with the wall slams being removed

**Comment by eeSPee** [comment]
Idea; lube is just a longer lasting water, while space lube+banana juice creates the what is now space lube.

**Comment by VictorVow** [comment]
I'm not a fan of how you can crawl away from a lubed area but then after standing up you still walk into a wall because the confusion lingers. It doesn't make any sense. 

At minimum I'd want to reduce the confusion length to the length you remain knocked down so you walk normally once you're standing on a non-lubed surface again, at which point I still have to wonder what's the point of it in the first place.

**Comment by zeskorion** [comment]
> The whole point of lube is to be pretty cancerous, I'd say keep the confusion since it was already nerfed enough with the wall slams being removed

Lube is too easy to make to remain that cancerous tbh

**Comment by Isy232** [comment]
Nerf the wall slams, but I think part of the point of lube is that it is so slippery it is impossible to be immune to it.

If you want to abuse slipping, use water. Lube should remain too slippery.

**Comment by ghost** [comment]
This is a massive clown nerf

**Comment by Blueturbo47** [comment]
Make advanced magboots lube proof too?

**Comment by GoatMonarch** [comment]
Hello! Downstream residental clown here. I have been active some four to five years by this point, and I wish to give some input to this change.

I'd like to start of saying that lube has a massive problem as it currently stays. Mere days ago, I managed to put a traitor chemist into crit whilst hyped on meth. Merely by throwing down a beaker of frying oil on the floor which he promply slipped and got confused. The only thing left to do after that was to shove him into walls, till he fell into crit. He hit back, did his very best, but confusion wallstuns are still stupidly broken as is.

With that in consideration: You can't just turn lube into more slippy water.
Revert to the old days where lube was non-lethal, and merely slip stunned you for a good few secounds. That'd make lube annoying, but not a cause to go to medbay.
It's **very** mind-boggling how this fork refuses to do anything at all related to stuns anymore. Water I understand, same for botany plants. But a department with access to zombie powder, or hellchems being diferent on this I do not understand.

> > The whole point of lube is to be pretty cancerous, I'd say keep the confusion since it was already nerfed enough with the wall slams being removed
> 
> Lube is too easy to make to remain that cancerous tbh

You can literally make explosives with two chemicals. You can make a meth explosion grenade given two minutes, if the chemist know what they are doing. The godamn point of chemicals, is that the room is very very high security. If anybody sees you in there, they will hawk over you like a schizophrenic uncle. And the moment an assistant/clown walks in, medbay are already yelling for all of security to stop them.

Beestation was clearly created due to disagreements with how /TG/ handled PRs. Absolutely no control what get merged or not, and a bunch of maintainers that are extremely out of touch with their playerbase.
One of the first PRs made here, was returning the clown's ability to slip stun people, since the slip PR on /TG/ fucked over clowns greatly. But now we are at the point where the word "stun" will make some player shit themselves, instead of giving it some consideration.
[#8](https://github.com/BeeStation/BeeStation-Hornet/pull/8)

This is far from a good fix, just kill wallstuns already.

**Comment by VictorVow** [comment]
Whilst I agree confusion causing wallstuns is cringe, I've tried in the past in a PR to remove just that only for it to be voted against. So I'll settle for removing one of the easiest sources of them instead.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Keep the confusion otherwise lube is completely useless, the wallslamming nerf was enough for lube to make it not the worst thing known to man.

**Comment by VictorVow** [comment]
Space Lube is extremely useful because it's a slip which can't be avoided except if you have antag or very rare items. It's only 3 ingredients and can be made in seconds at a chem dispenser.

I'm not going to make the lube meta worse by adding in new lube items and ways to leverage lube without nerfing it, otherwise it's not a rebalance it's just a lube buff. I like eespee's idea, but I'll change it so Space Lube is an unavoidable slip like in this current PR and Super Lube is the current confusion-inducing Space Lube which requires Space Lube + bananas.

**Pull request closed without merging**
