### PR TITLE
Fixes crafting UI not updating after crafting

### PR DESCRIPTION
**Pull request by mcmeiler**
## About The Pull Request
Title.

## Why It's Good For The Game

Not having  the crafting UI update after crafting sucks for items in bulk, i.e. shotgun shells.

## Changelog
:cl:
fix: Crafting UI updates after crafting

/:cl:

### CODE REVIEW

**Comment by Sinestia** [comment]
What's wrong with it?

Seems like a ui_update would be more fitting just skimming this, haven't tested or seen it ingame

**Comment by mcmeiler** [comment]
> What's wrong with it?

Won't let you click after crafting an item, making you have to reopen the menu.

Though in the end you're probably right, this was just a lazy man's solution, I'll look into it

Edit: Yeah after looking into it for 5 seconds I got it working without ``ui.set_autoupdate``, doing some last tests to see if I'm not stupid, though.

**Comment by mcmeiler** [comment]
Just me being dumb and stupid don't mind that

**Comment by PowerfulBacon** [comment]
Put ui_updade at the end of ui_act

**Comment by mcmeiler** [comment]
I'll just close this and do it properly, Git really hates me right now.

**Pull request closed without merging**
