### PR TITLE
Cogscarabs no longer dodge bullets fired over them.

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Cogscarabs will now be affected by bullets fired from non servants if they pass over the top of them.

## Why It's Good For The Game

Despite being made to be extremely weak in combat, cogscarabs are nearly impossible to hit making them incredibly strong in combat. This nerfs their ability to fight by making them get hit by projectiles that aren't shot directly at them.
Their focus should be on repairs, construction and support rather than front-line combat.

## Testing Photographs and Procedure

image

## Changelog
:cl:
balance: Cogscarabs can no longer dodge projectiles that aren't fired directly at them.
/:cl:

### CODE REVIEW

**Comment by Kratairo** [comment]
They are the main defenders clockies have with the rest being underpowered, they already barely win so why would you do that?

**Comment by Oscari-pog** [comment]
As stated above, clockcult usually gets their shit kicked in. They are not even allowed to do mass sabotage before portals, the phase in which they cannot even access the station. This is a non-issue, and this PR will only make clockies lose even more.

**Comment by PowerfulBacon** [comment]
Clockcult get healing spells which don't actually damage cogscarabs due to their inability to take toxin damage.

**Comment by Isy232** [comment]
I completely agree that sacrabs should be hit by projectiles.
Near impossible to hit units are extremely annoying to fight and just feel unfair.

If clock cult is weak, it should be buffed in other areas.

**Comment by Kratairo** [comment]
Except they wont be buffed because no one will bother to. Also scarabs dont get healed by it because they drop in 3 hits anyways.  They are supposed to be the defenders since marauders are insanely high on resources and utter dogshit (they can be soloed by anyone with a fireaxe/spear).

**Comment by PowerfulBacon** [comment]
Scarabs can heal other people with it, with no cost to themselves.

**Comment by Fronsis** [comment]
If you have a single competent cogscarab their base always go for the meta-build of filling it with airlocks or other cancerous tactics, we really shouldn't be having between 5-7 cogscarabs that are imposible to hit with lasers while in the meantime they proceed to slash you, evade with their movement speed and steal everything back deeper into the R eebe

> Futhermore, scarabs cannot work as a support role aside from construction, and even then they have construction speed lower than regular clockies. They cannot use sleepers to heal people too.
You clearly haven't fought a decent or robust cogscarab, they're impossible to hit with a range gun or meelee gun because of the mix of small sprite + movent speed, they're indeed a support role that's focused on construction but seeing the current ''meta'' when the fight stage starts they just abuse their stats to fight instead of trying to repair/sustain the Reebee

Of course that's because what Kratairo said

> Except they wont be buffed because no one will bother to. Also scarabs dont get healed by it because they drop in 3 hits anyways. They are supposed to be the defenders since marauders are insanely high on resources and utter dogshit (they can be soloed by anyone with a fireaxe/spear).

Marauders are only good because they can deflect like 4-5 laser/ballistic shots before taking any damage, they **can** be soloed by anyone with a melee weapon yes, but you need to add to the mix the fact that the Marauder player should have 2 braincells and not face-tank a crewmember but instead kite it using the defenses of Reebe on their favor, i do agree that they're expensive as fuck but they shouldn't be mass spammable since Reeve is supposed to have crewmembers fighting too, but that's an issue with Clockies in general that needs a lot of balancing and QoL stuff that... i don't think any of the coders wants to do

**Comment by Oscari-pog** [comment]
The only repair scarabs could potentially do on Reebe are the ones that will happen on the frontline. Too bad that they cant even do that now.

**Comment by Fronsis** [comment]
> The only repair scarabs could potentially do on Reebe are the ones that will happen on the frontline. Too bad that they cant even do that now.

Eh, even if this wasn't in they need to stand still to do any type of repair/construction even with an RCD(for walls/windows) so i don't think that applies

**Review by ike709 — APPROVED** [review]

**Pull request merged**
