### PR TITLE
Adds pets to a variety of places!

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
Adds the following:
Coffee the Crab to BoxStation Science
Birdboat the Goose to DeltaStation, MetaStation, CorgStation, and PubbyStation maints
Lia the Carp to CorgStation HoS office
Cayenne the Carp to the traitor deployable capsule shuttle
Adds a new pet!
Tom the Turkey is the mascot of the Exploration Crew, and appears on the three exploration shuttles.

## Why It's Good For The Game
Pets are adorable, and the Exploration Crew needs a mascot.

## Changelog
:cl:
add: Coffee the Crab is now present in BoxStation Science
add: Birdboat the Goose is now present in DeltaStation, MetaStation, CorgStation, and PubbyStation maints
add: Lia the Carp is now present in the CorgStation HoS office
add: Cayenne the Carp is now present in the traitor deployable capsule shuttle
add: Tom the Turkey is the mascot of the Exploration Crew, and appears on the three exploration shuttles.
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — APPROVED** [review]
Ew, a turkey

**Comment by St0rmC4st3r** [comment]
Good, now the exploration crew starts with some food!

**Comment by ike709** [comment]
I feel like birdboat should be a random maint room.

**Comment by Ivniinvi** [comment]
That'd open up the possibility of having two birdboats, and birdboat is unique, special, and loved by all.

**Pull request merged**
