### PR TITLE
QoL Map Upgrades v2.1: Boxstation

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
This is a reup of a previous pull request which caused some type of error.
imgur image

Part of an ongoing project to rework some of the maps in rotation. This focuses on Boxstation.
In general it:

- Puts hundreds of new decals down
- Fixes engi maint bug
- Adds a couple new random maint rooms
- Fixes the power grid
- Adds some new atmos piping
- Corrects disposals bugs 

pubby change: forgot 1 decal

## Why It's Good For The Game
Box really needs some TLC, it is pretty much THE lowpop map but it's aging

## Changelog
:cl:
add: Boxstation now slightly better looking, more resistant to mice.
add: Boxstation medbay now gets its own Inspector Johnson. It’s time for mandatory inspection!
fix: Boxstation's engi maint is no longer bugged.
/:cl:

### CODE REVIEW

**Comment by jlsnow301** [comment]
Fixed the absolute dizzying disposals and atmos east of incinerator, which was bugged and shooting trash back into viro:
imgur img
Turned the useless room there (had a couple pipes and a welding tank) into a 10x5 random

**Comment by jlsnow301** [comment]
I believe this error is still caused by random rooms - wondering what's the status on testmerge @qwertyquerty

**Comment by ike709** [comment]
@zeskorion You're our most qualified mapper at the moment, so have fun reviewing this.

**Comment by ike709** [comment]
image
DNM until attempting to crash the server is no longer part of this PR.

**Comment by jlsnow301** [comment]
> DNM until attempting to crash the server is no longer part of this PR.

This is styling it similar to delta station which means I just put lines under doors and squares around trash bins

**Comment by ike709** [comment]
Decals are bad for performance. Other stations having bad mapping practices is not an excuse to apply said practices to more maps.

**Comment by jlsnow301** [comment]
I would argue that difference is negligible, not sure "hundreds of decals" is really anything more than hyperbole. If you want me to delete the decals from Deltastation I can, but even this uses far less

**Comment by ike709** [comment]
Also DNM pending a big incoming mapping PR.

**Comment by PowerfulBacon** [comment]
In my opinion, the black tiles at security look terrible

**Pull request closed without merging**
