### PR TITLE
Butterfly knife

### PR DESCRIPTION
**Pull request by enthethan**
## About The Pull Request
ports  KayeArraye's Butterfly knife PR   from hippie.
https://github.com/HippieStation/HippieStation/pull/2558 

Ports the butterfly knife and energy butterfly knife from hippie ,currently only the traitor version is  currently purchasable, but im gonna add the regular one to some loot or maybe craftable in a different PR.

## Why It's Good For The Game
Adds a fun gimmicky weapon,does 20 damage with 65% armor penetration on nonbackstabs, and
95 damage on backstabs,do note that backstabs are not that easy to land.
In my opinion this is a far more interesting item than an esword and fits in the traitor arsenal.

## Changelog
:cl:
add: butterfly knife
add: energy butterfly knife,available for purchase as a traitor for 8 tc
soundadd: stab sounds and more
imageadd: new icons for the butterfly knives
/:cl:

### CODE REVIEW

**Comment by Sun-Soaked** [comment]
Et tu, Honko the clown.

**Comment by Sun-Soaked** [comment]
Ides of march aside, the backstab seems kinda powerful. Can they be chained together reliably? If so, perhaps it should be a recharging effect that can be triggered like once every 15 or 30 secs.

**Comment by qwertyquerty** [comment]
seems op, plzs nerf

**Comment by eLeCtrOssSnake** [comment]
Spy!!!!

**Comment by CthulhuOnIce** [comment]
kinda on the fence on this one

**Comment by qwertyquerty** [comment]
Seriously these are way too OP, need a nerf

**Comment by enthethan** [comment]
they aren't way too OP,trust me.

**Comment by Crossedfall** [comment]
Please update your description to include a link back to the PR you are porting this from.

**Comment by qwertyquerty** [comment]
Fix conflicts

**Comment by enthethan** [comment]
gonna work on this in a few weeks

**Pull request closed without merging**
