### PR TITLE
Removes Directional Depleted Uranium Windows

### PR DESCRIPTION
**Pull request by ro5490**
## About The Pull Request
Directional DE Windows dont block rads, for some unknown reason.
However, nobody has gotten the hint after multiple radiation leaks.
So, removal it is.
## Why It's Good For The Game

Prevents people from using the wrong windows for radiation proofing.

## Testing Photographs and Procedure
N/A 

## Changelog
:cl:
del: Removed directional depleted uranium windows as they dont block radiation but people keep using them to do so.
imagedel: deleted icons for directional depleted uranium windows
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
Fix it then >:(

**Comment by ro5490** [comment]
> Fix it then >:(

Cant even figure out why its letting rads through
If you can figure that out, I'll fix it

**Comment by Fronsis** [comment]
I mean yeah sadly... improve don't remove is a good motto lol, i mostly say it not because meme but i've confirmed with multiple CE/Engi players when we had brief talks that they enjoyed the existance of that and they allowed to do some other setups (even though some ended up in infinite rads on the hallways)

**Comment by ro5490** [comment]
I'd just like to clarify that this doesnt remove the full-tile radiation proof depleted uranium windows, just the single direction ones that dont actually block radiation like they're meant to for some unknown reason

**Comment by itsmeow** [comment]
:key: We should figure out why they are broken

**Comment by WrillWasTaken** [comment]
I'm fairly certain they're functional. Did fusion, contained it with a box of only directional windows, rads spread in an X pattern instead of going in all directions. 

You just need to put a fulltile window on each corner to stop rads.

**Comment by Tsar-Salat** [comment]
> Directional DE Windows dont block rads, for some unknown reason.
> However, nobody has gotten the hint after multiple radiation leaks.
> So, removal it is.

That's asinine.
If we removed every feature that broke at the first glance, we wouldn't have a server.

**Comment by ro5490** [comment]
> I'm fairly certain they're functional. Did fusion, contained it with a box of only directional windows, rads spread in an X pattern instead of going in all directions.
> 
> You just need to put a fulltile window on each corner to stop rads.

This actually helps a lot, I wonder if theres a way to solve this without full-tiles on the corners

**Comment by Penwin0** [comment]
Cause of this is definetly corners being weird, unsure how you'd fix this in a non roundabout manner

**Comment by PowerfulBacon** [comment]
I only support removing because I looked at rad code and I wouldn't be able to fix this due to rad code

**Pull request closed without merging**
