### PR TITLE
Lowers the movement speed on Sage

### PR DESCRIPTION
**Pull request by St0rmC4st3r**
## About The Pull Request

Does the evil. It lowers the walking (slightly) and running (less slightly) speed on Sage, however not to a crawl like on Paradise.

## Why It's Good For The Game

There are several reasons. Primarily, now you actually have time to say something more or less complex to people that are passing by before they zoom out off the screen.
This is also a buff to methamphetamine, ephedrine, adrenals, and other speed sources, as well as explosions, which you cannot outrun as easily anymore.

## Changelog
:cl:
tweak: Moooovemeeeent speeeed oooon Saaaage iiiis noooow slooooweeeer.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Damn that is pretty slow, that's almost walking speed. (Factoring in depression and other slowdowns too)

**Comment by Isy232** [comment]
This is a 40% decrease, I think current sage movement may be a little fast but this is too slow to even consider.

**Comment by Moccha-Bee** [comment]
slow down mrp more and it becomes a walking and talking simulator

**Comment by St0rmC4st3r** [comment]
> slow down mrp more and it becomes a walking and talking simulator

As it should be ::)

**Comment by St0rmC4st3r** [comment]
Seriously though, what values do you propose?

**Comment by ghost** [comment]
> Seriously though, what values do you propose?

no changes

**Comment by TeomanTheGreat** [comment]
Mrp is slow enough

**Comment by Bestparty** [comment]
Based pr, speedmerge

**Comment by St0rmC4st3r** [comment]
Apparently people don't like evil.

**Pull request closed without merging**
