### PR TITLE
Rad station power cable improvements & more

### PR DESCRIPTION
**Pull request by mystery3525**
## About The Pull Request

- Central Maintenance shouldn't be cut into three pieces because of the service hall, shrinks the service hall to a sane area.
- In fact, re-takes landmass away from hallway areas and gives it back to the more sensible areas (maintenance)
- Shrinks atmos area so that it isn't actually in space
- Creates two brand-new maintenance areas from the absolutely massive scimaint and medmaint (which themselves were both split in two by their respective departments)
- Removes shock grilles from places that really shouldn't have them, such as the Tool Storage, Bridge Maints Glass, Disposals, Chemistry, Medbay.
- Reduces the amount of power cables entering/exiting departments to appropriate amounts, versus every maintenance hatch. There should be *some* redunancy in the power network, but it should **NOT** just be a grid of loops.
- In addition, ensures that power cables prefer to stay within their department, even traveling longer distances. Central Command planners would like for the ability for departments to easily be segmented off, so if 
- Makes it so that power cables prefer to go through doors, rather than harder objects such as glass and windoors, and prefer to go around machines.
- Swaps the position of the xenobio machines for easier access to the slime storage
- Moves the bridge consoles one tile away from the transit tube to be able to access the AI sat
- Gives science showers at both exits
- Gives robotics their missing fuel tank
- Adds a few more intercoms in science
- Removes the surplus SMES in armory
- Absorbs evidence locker area into warden's office, a standard in most maps, to reduce the amount of areas and unneeded wires

## Why It's Good For The Game

- Some more consistency with regards to power cables. Each department should be connected to others/maint via power at **maximum** of 3 points.
- Disposals grinder **really** does not need shock grilles.
- Science QoL
- Armory does **NOT** need it's own SMES backup power source. Regardless, it's pretty cramped in there anyways.
- It makes sense for a serviceability standpoint that at least power cables travel through doors, rather than fulltile windows/thindows.
- I'm all for area flavor and variety, but var-edited area names and enclaves/exclaves is not the way to do this

I understand that this may conflict with https://github.com/BeeStation/BeeStation-Hornet/pull/9143, but this is just some much-needed fixes and QoL that I see must be put into place. I'll deal with merge conflicts eventually.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

After a while unattended (refilling the SMESs though)
image

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
fix: radstation scimaint and medmaint has been split into more separate maintenance areas, these places were massive and non-contiguous.
balance: radstation armory no longer has its own backup SMES
balance: radstation no longer has random shock grilles for lower-security areas such as maintenance, tool storage, chemistry, and medbay (really?)
fix: radstation cables now prefer to pass through doors versus windows and machines.
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
Use mapmerge to fix conflicts https://wiki.beestation13.com/view/Map_Merger

**Comment by itsmeow** [comment]
> In fact, re-takes landmass away from hallway areas and gives it back to the more sensible areas (maintenance)
> Shrinks atmos area so that it isn't actually in space

These aren't in the PR? Is this PR still in progress? Mark it as a draft please

**Comment by BriggsIDP** [comment]
Thanks for making this, some small issues i saw:
Missing cable and floor tile (floor tile is probably my bad)
image
decal funky
image
image
overlapping wall stuff
image
replaced shutter with a blast door, don't do that.
image

Also I saw you didn't split up the service hall, are you still planning on doing that?

**Comment by mystery3525** [comment]
DNM until I get those fixes in (I'll do it around monday)

**Comment by mystery3525** [comment]
no idea why that test failed but it's ready

**Comment by itsmeow** [comment]
Why is MDB-DMM not running

**Comment by itsmeow** [comment]
dammit I broke it

**Comment by itsmeow** [comment]
Can we get an empty commit?

**Review by PowerfulBacon — APPROVED** [review]

**Review by PestoVerde322 — APPROVED** [review]
Should be good to go, approved.

**Comment by BriggsIDP** [comment]
minor feedback on discord!

**Review by Penwin0 — APPROVED** [review]
Sorry for merge conflict, should have done this one first, I'll merge it as soon as conflict is resolved

**Pull request merged**
