### PR TITLE
Ports tg's Holodeck rework

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

the ability to add more holodecks with less suffering involved
also 9x10 decks
tgstation/tgstation#55645 and fixes

## Why It's Good For The Game

yes
image

## Changelog
:cl:kylerace
add: Added a few more holodecks
refactor: Nanotrasen overhauled much of the holodecks programming so that it didnt have to keep physical copies of the simulations anymore.
code: holodeck uses map templates instead of area_copy
/:cl:

### CODE REVIEW

**Comment by jupyterkat** [comment]
map edits pending

**Comment by MitztheKat** [comment]
someone give this fucker meth to speed up production

**Comment by eeSPee** [comment]
Will this remove Emergency Medical holodeck module?

**Comment by jupyterkat** [comment]
> Will this remove Emergency Medical holodeck module?

no, it’ll expand it, even

**Comment by jupyterkat** [comment]
I will not edit corgstation because that map's getting updated daily and map conflicts are the cringiest

**Review by utilbird — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
wait so it just breaks on corgstation lmfao?

**Comment by jupyterkat** [comment]
> wait so it just breaks on corgstation lmfao?

@PowerfulBacon I haven’t updated the corgstation map for it, cause map conflicts

**Pull request merged**
