### PR TITLE
Kilo Medbay Rework 2

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request

This is a v.2 of this PR: https://github.com/BeeStation/BeeStation-Hornet/pull/10080. I have messed up the PR beyond what I can understand and I can't seem to fix it, so I'm just creating this one. 

KiloStation Medbay rework. All areas have been updated to have a better use of the space. OG Kilo just have rooms weirdly shapend and oddly placed for the sake of it. This rework aims to get a cleaner, more satisfying layout while still keeping Kilos theme of being small and cramped

## Why It's Good For The Game

Because medbay people deserve better

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://cdn.discordapp.com/attachments/590714573611597824/1167439370484195438/8mb.video-NJx-Y4h5VY2k.mp4?ex=654e21a3&is=653baca3&hm=89612121f510076b25a9776f845f96fc15c41f5ae9a1c6b9160bc8fc3bbb9272&)

imagen

</details>

## Changelog
:cl: Varo
tweak: Reworks the lobby, changes the front desk position to where cloning was, moves genetics to the big monkey room, moves cloning where genetic was, adds a surgery room, reworks the CMO, storage and chemistry room, removes a big part of virology and places it all below chemistry, tweaks some maintenance areas 
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
Having Viro be open to the public hallway sounds like a disaster waiting to happen. There's a reason why no other map does this.

**Comment by itsmeow** [comment]
Sorry about the conflict again. 
One change request: Genetics should not include purple/sci theming because it is no longer a part of science.

**Comment by spockye** [comment]
please add a screenshot of the area to the PR !!

**Comment by ClownMoff** [comment]
Conflicts again
imagen

**Review by spockye — CHANGES_REQUESTED** [review]
image

wrong maintenance area

image

cloning has no APC

image

no button for these shutters

image

wrongly named button. perhaps "Chemistry shutters Toggle"?

image

no wall decals!!!!

image

this square is kinda iffy.... you should generally try closing walls up. this will leave a akward gap between the two reinforced walls 

image

recommend switching these around 

image

kills u

image

kills u

image

missing decals

image

missing corner ( random white floor? )

image

stacked decal ( leftover black floors? )

image

two cameras / both stacked on lights (try to avoid that!)

image

two cameras in gene

image

flying camera


-------


image

might just be me, but i'd reconcider the decalling here. feels kinda... off?
(also the corner gets moved up for some reason)

**Review by spockye — CHANGES_REQUESTED** [review]
image

medbay central has 3 APC's

cryo has none

**Pull request closed without merging**
