### PR TITLE
Grants Xeno impregnation immunity to Abductors, Androids, IPCs, and Skeletons

### PR DESCRIPTION
**Pull request by YakiAttaki**
## About The Pull Request
Makes IPCs and Skeletons immune to Xenomorph impregnation

## Why It's Good For The Game
IPCs don't have organic tissue and thus would not be valid targets for facehuggers. Skeletons have no organs, and thus no-where for the xeno to grow.

## Changelog
:cl:
add: Added a xeno immunity trait
balance: Made IPCs, Androids, Abductors, and Skeletons immune to facehugger attacks.
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
reee ipc buffs bad


in all seriousness, makes sense, though i think they're already immune? either way, put it on abductors too- no mouth

**Comment by YakiAttaki** [comment]
One moment, I'll see if they already are, but I don't think they are judging from the code.

**Comment by YakiAttaki** [comment]
Huh, it would seem they are immune to being implanted, but not from being leapt at. It doesn't make much sense for the facehugger to attach to something it obviously can't impregnate, though.

**Comment by PowerfulBacon** [comment]
Having them stunned when lept at makes sense, since you do have an alien hitting your sensors with high velocity

**Comment by MNarath1** [comment]
So that means when there are only IPC‘s on a Station Xeno‘s are pretty screwed.

**Comment by eLeCtrOssSnake** [comment]
IPC's are OP even now, EMP is rare - no, that's fucking bullshit

**Comment by Sun-Soaked** [comment]
As much as IPC's are rapidly becoming a gamer meta, it just doesn't make sense for them to _not_ be immune to Xenopreg, and I'd support this on those grounds

**Comment by Sun-Soaked** [comment]
when you really think about it, this is more of an IPC nerf then anything- now aliens will straight up murder IPC's in cold blood instead of trying to collect them like fleshies, denying them the garanteed chance to become a xeno if they fail to defend themselves. Also, in response to @man4fred's earlier comment: monkeys are already the Xeno infection go-to.  Can huggers knock down IPC's, even if they don't attach? I feel that would be fair.

**Comment by qwertyquerty** [comment]
fix conflicts

**Pull request merged**
