### PR TITLE
Fix brain damage not giving traumas (#46582)

### PR DESCRIPTION
**Pull request by Cenrus**
https://github.com/tgstation/tgstation/pull/46582

:cl: JJRcop
fix: Fixed brain damage never giving traumas.
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
Travis mad, re run the checks.

**Comment by Crossedfall** [comment]
> 
> 
> Travis mad, re run the checks.

Donezo

**Comment by ike709** [comment]
Tested?

**Review by ike709 — APPROVED** [review]

**Comment by Cenrus** [comment]
yes.

**Pull request merged**
