### PR TITLE
Meta Exploration Upgrades

### PR DESCRIPTION
**Pull request by dog132-ss13**
## About The Pull Request

This PR is made on behalf of Spockyeye.

## Why It's Good For The Game

Adds a larger exploration dock and a new fancy meta exploration shuttle.

image

image

## Changelog
:cl:Spockyeye
add: Refurbished the Meta Station exploration dock
add: Meta Station exploration shuttle
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
The shuttle is going to get irradiated every time someone does turbine fusion.

**Comment by spockye** [comment]
> 

how far does the radiation go?

**Review by MNarath1 — CHANGES_REQUESTED** [review]
This shuttle has the same problem as the delta exploration shuttle a airlock that clearly was supposed to have an airlock controller but there is non and thus a completly useless air vent that never activates together with a air tank that also never gets drained. So yeah add an airlock controller so it actually does what its supposed to do.

**Comment by dog132-ss13** [comment]
> The shuttle is going to get irradiated every time someone does turbine fusion.

Turbine has been moved slightly up and the shuttle has been modified to mitigate radiation exposure
image

**Comment by dog132-ss13** [comment]
> The shuttle is going to get irradiated every time someone does turbine fusion.

The turbine has been nudged upwards and the shuttle has been redesigned to mitigate radiation exposure
image

**Review by KubeRoot — CHANGES_REQUESTED** [review]
Adds duplicate wire in brig at 113, 169:
<details>
<summary>Screenshot</summary>

image
</details>

And another in bridge at 102, 138:
<details>
<summary>Screenshot</summary>

image
</details>
Reintroduces `harm_intent_damage` on pet spider, removed in #5648

If you didn't make these changes yourself, seems like the PR has had an old version of the map dropped in after changes were made to it. You can see on mapdiffbot that it's trying to render most of the station in the diff, this shouldn't be happening if you only intended to change one area.

Other than that, I spotted a misplaced railing on shuttle:
<details>
<summary>Screenshot</summary>

image
</details>

I'm not great with mapping so I can't really review the quality of the map, but everything else looks good to me.

**Comment by dog132-ss13** [comment]
The wire and railing issues have been fixed. I did remove the `harm_intent_damage` variable in commit **fixes compile error 4 real**, I hope it is no longer an issue.

**Comment by KubeRoot** [comment]
> I did remove the `harm_intent_damage` variable in commit **fixes compile error 4 real**, I hope it is no longer an issue.

That seems to be my bad, it's indeed not the case in the latest version, sorry.

The mapdiffbot is, however, still showing an area bigger than should be affected, which implies there are still invisible changes out there. I would recommend reapplying the changes.
Assuming my suspicion is correct, and you have a map file with the changes that's outdated, you should make a branch from the commit the map was edited on, put the changed map there, then merge master in and resolve any conflicts. Alternatively you could also redo the changes from the current master.

The reason I'm worried about this is, I can spot some things I know about, but there might be other important changes that this PR is removing that aren't clearly visible.

**Comment by ike709** [comment]
Conflicts

**Pull request closed without merging**
