### PR TITLE
Adds Design for Research Disk Locator to Sci Protolathe

### PR DESCRIPTION
**Pull request by DatBoiTim**
## About The Pull Request
Adds Design for Research Disk Locator to Sci Protolathe.
You can now make them at the protolathe as needed!

## Why It's Good For The Game
Research Disk locators are an important item for station progression, since they allow exploration to more easily find research disks.
Now that they are actually obtainable, exploration teams consisting of latejoins will actually be able to find disks for the station.

## TODO

- [x] Lock behind T2

## Changelog
:cl: DatBoiTim
add: Design to Print Research Disk Locator to Sci Protolathe - Requires T2 Research
/:cl:

### CODE REVIEW

**Comment by Isy232** [comment]
Yes please

**Comment by KubeRoot** [comment]
I'm thinking maybe this should be locked behind a T1 or T2 research, otherwise there's no real reason not to have every explorer print it roundstart. It'd still remove the randomness, but prevent accessing it from being too trivial.

**Comment by DatBoiTim** [comment]
> I'm thinking maybe this should be locked behind a T1 or T2 research, otherwise there's no real reason not to have every explorer print it roundstart. It'd still remove the randomness, but prevent accessing it from being too trivial.

Most of the other roundstart kits can be gathered roundstart(exception being the breach charges). Additionally, exploration missions can take time. Combined with the issue that roundstart there's no guarantee anyone on your team has that kit, you'd be looking at a decent amount of lost time.

**Comment by Archanial** [comment]
lock it after t2

**Comment by DatBoiTim** [comment]
> lock it after t2

Done

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
