### PR TITLE
Durathread and loom changes. (#45261)

### PR DESCRIPTION
**Pull request by Cenrus**
https://github.com/tgstation/tgstation/pull/45261

## About The Pull Request

Some durathread recipes can now be made with stackcrafting.
Durathread is no longer a cloth subtype.
The fabric variables have been removed from sheets. They are now exclusive to cotton sheets and it's subtypes.
The loom can now be unwrenched.
Fixed a bug where you get more cloth with the loom than you should have.
## Why It's Good For The Game

Makes the loom and its products just a little less cluncky to use. Slighly improves code quality.
## Changelog

:cl:
add: You can now unfasten the loom.
code: Various changes to the loom and its products.
fix: You can no longer get more cloth from the loom than you should be able to.
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Fails travis.

**Comment by Cenrus** [comment]
strange, I didn't touch any maps.

**Comment by ike709** [comment]
https://i.imgur.com/OzOocpZ.png

**Comment by Cenrus** [comment]
Fixed the thing.

**Pull request merged**
