### PR TITLE
Update health analyzer sprite

### PR DESCRIPTION
**Pull request by sheldoniscool**
image
image

## About The Pull Request
Updates health analyzer sprites to new version.

## Why It's Good For The Game
New animations and look are way better and differentiate it from the genescanner and plant analyzer.

## Changelog
:cl:
Tweak: Updated sprites for health analyzer and advanced health analyzer
/:cl:

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
No, we had the vote for this sprite before and we decided that it is ugly because the sprite is at a wrong angle.

**Comment by sheldoniscool** [comment]
> No, we had the vote for this sprite before and we decided that it is ugly because the sprite is at a wrong angle.

What angle?

**Comment by St0rmC4st3r** [comment]
image
It really annoys me because my brain refuses to percieve it other way than on picrelated, while every other sprite is the other way around:
image

**Comment by sheldoniscool** [comment]
> image
> It really annoys me because my brain refuses to percieve it other way than on picrelated, while every other sprite is the other way around:
> image

I get what you're saying - I actually think I had that the first time I saw that then it went away. 
Hm may I can flip it? Or maybe just flip the screen? I'd have to do some jankness to fix the animation since it'd be fugged.

**Comment by SomeAngryMiner** [comment]
do note that medical equipment is getting a huge resprite after engineering, and adding this scanner sprite back in was down the line.

**Comment by sheldoniscool** [comment]
> do note that medical equipment is getting a huge resprite after engineering, and adding this scanner sprite back in was down the line.

It bothers me - I was also planning on switching the readout on scan because I think TG does a better job. But once I started looking at the code I was like I don't care enough about this and could focus on something else.

Is there an estimate on when this will be done referring to the medical resprite?

**Comment by sheldoniscool** [comment]
I'll close this for now

**Pull request closed without merging**
