### PR TITLE
Redcoat - Sprite-less fix

### PR DESCRIPTION
**Pull request by Nakalon**
## About The Pull Request

While making my previous PR I came upon a very strange thing.

If you put an uniform and a denied rubber stamp in the washing machine you'd get the readcoat. Which exists nowhere else and didn't have a sprite.

Instead of removing this silly thing I added 2 sprites.

Since I didn't know what it was supposed to look like I recoloured a formal assistant uniform in sec red. I then made it look old as described in the description of the item.

I also kept the non oldified version because someone might want to use it for something.

## Why It's Good For The Game

It was a sprite-less item.

RP as an old-timey potion seller, I don't know.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/94647521/d203dd10-cab3-4254-aeae-bcb164cfee32

image

</details>

## Changelog
:cl: PinkSezukey
imageadd: Added sprites to the forgotten Redcoat
/:cl:

### CODE REVIEW

**Comment by Raven-Industries** [comment]
"Redcoat" seems likely to be a reference to the historical uniform of British infantry: 
image

**Comment by Nakalon** [comment]
> "Redcoat" seems likely to be a reference to the historical uniform of British infantry, as they were often referred to as "redcoats" (especially in an American context): image

What an obscure reference!

It already looks SOMEWHAT similar! I could colour the pants different to match this colour, what do you think?

**Comment by Raven-Industries** [comment]
I think that would get pretty close to the right look. It seems that the pants could be a variety of colors too, grey, black, white, khaki, so there's a good range to choose from.

**Comment by Nakalon** [comment]
Forgot to add comment, I'm closing this PR in lieu of doing something cooled with the denied stamp in Pr number #10371

**Pull request closed without merging**
