### PR TITLE
Genetics Tweaks

### PR DESCRIPTION
**Pull request by chloecat0**
## About The Pull Request
Makes a bunch of changes to genetics such as: 
- increased mutation and chromosome storage with better matter bins
- increased instability limit in advanced injectors with better scanning modules
- allowing any chromosome to be taken out of the console (rather than only the last)
- any mutation can be removed from advanced injectors (rather than just the first)
- mutations can be added to advanced injectors from storage
- advanced injector button being grayed out when unusable

## Why It's Good For The Game
Makes genetics less clunky and annoying

## Changelog
:cl:
add: Genetics consoles can store more mutations and chromosomes with better parts
tweak: Lots of other small changes to genetics
/:cl:

### CODE REVIEW

**Comment by 123chess456** [comment]
Objectively based PR.

**Comment by hackerjsimon** [comment]
add it so u can put chromosomes in stored mutations

**Comment by qwertyquerty** [comment]
Voted pass, testmerging soon

**Comment by chloecat0** [comment]
Nice

**Comment by Crossedfall** [comment]
No runtimes or complaints during test merge on Golden

**Pull request merged**
