### PR TITLE
add all soda/booze dispenser reagants to serviceborg shaker

### PR DESCRIPTION
**Pull request by 123chess456**
## About The Pull Request

All reagants in the booze/soda dispenser not currently present in the serviceborg shaker have been added to said shaker.

## Why It's Good For The Game

For far too long serviceborgs have had shitty reagants and been unable to make many cocktails. This all changes today. this is the PR nobody wanted but is sorely needed.

## Changelog
:cl:
add: Nanotrasen has finally updated the Service Cyborg shaker to the standards of Booze and Soda dispensers.
/:cl:

### CODE REVIEW

**Comment by Vexylius** [comment]
Doesn't this make the reagent list awfully long? Might need to update that GUI 👀

**Comment by DatBoiTim** [comment]
> Doesn't this make the reagent list awfully long? Might need to update that GUI 👀

Or make a separate borg item for the soda, we just do not want there to be a huge reagent menu.

Other than this, good PR.

**Comment by 123chess456** [comment]
> > Doesn't this make the reagent list awfully long? Might need to update that GUI 👀
> 
> Or make a separate borg item for the soda, we just do not want there to be a huge reagent menu.
> 
> Other than this, good PR.

I was considering doing this but i have no clue how to make a separate item

**Comment by utilbird** [comment]
@123chess456 Make a subtype of the normal shaker and add move all the alcoholic/non-alcoholic reagents from the parent into it's list

**Comment by park66665** [comment]
There is no problem that warrants a new subtype. This already is a proper subtype: `/obj/item/reagent_containers/borghypo/borgshaker`.

**Comment by utilbird** [comment]
> There is no problem that warrants a new subtype. This already is a proper subtype: /obj/item/reagent_containers/borghypo/borgshaker.

The issue is that it makes the reagent list even more crammed then it originally was. The subtype suggestion would split the reagents up like how the normal bar dispensers work

**Comment by 123chess456** [comment]
Are you fucking kidding me?

**Pull request closed without merging**
