### PR TITLE
[DO NOT MERGE] Pay to win races

### PR DESCRIPTION
**Pull request by Kerbin-Fiber**
## About The Pull Request
This sets the round start races to three races that have little to no downsides and upsides.
Moves other races to the Beecoin shop since races have their own meta, you gotta earn your "haha immune to rads and basically space-worthy roundstart" race.

I also moved this to the github before finishing it because you guys are more experienced than me and can chime in to help get it to work.

- [x] Adds races to the Beecoin shop.
- [x] Adds the bought race to a list of bought races.
- [x] Has the Race Selector pick available races from the Config and the bought races.
- [ ] Makes only the person who owns the race able to use said race.
- [ ] Saves the bought race list to that person.
- [ ] ~actually having good code?~
## Why It's Good For The Game
This should help new players not pick a hard race to play as out of the door, as little as that happens.
~_Ends the moff metagangs._~

## Changelog
:cl:
add: Added species to the Beecoin Shop!
del: Removed a lot of species from the round start species list.
tweak: You now only start with Humans, Lizards, and Ethereals as round start races. You'll have to buy more races from the Beecoin shop.
/:cl:

### CODE REVIEW

**Comment by Kerbin-Fiber** [comment]
The prices are negative currently for testing, since I have 0 beecoins on a local server and wouldn't be able to buy them.

**Comment by 123chess456** [comment]
Possible combinable with Coinhive integration to allow people to mine crypto for Beecoins?

**Comment by Lagomorphica** [comment]
how much do they cost

**Comment by ike709** [comment]
@123chess456 coinhive is dead

**Comment by Agateophobia** [comment]
Oh fuck, I hope IPC not gonna cost bazillions

**Comment by Moccha-Bee** [comment]
Only add species we don't have unlocked to the shop otherwise this is a bad idea. And maybe the teshari if they get added in the future.

**Comment by mehmetipekpatates** [comment]
Don't merge this please, it involves races that have a lot of added benefits to them with the entire purpose of powergaming as well as limiting character customization. The difference between humans, moths, lizards and felinids is so small that it's not even worth making people pay for it. There's nothing good to come out of this.
-Xlyana

**Comment by boy2mantwicethefam** [comment]
wow do something better with your time and remove catg*rls

**Comment by Kerbin-Fiber** [comment]
I can't for the life of me get it to work. Even after a week. Good learning experience though.

**Pull request closed without merging**
