### PR TITLE
Getting batonned makes you shake and stutter

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

- Getting batonned will make you shake and stutter

## Why It's Good For The Game

Would be nicer than your character barely being phased by being electrocuted. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

https://user-images.githubusercontent.com/22431091/185681231-e10ba58e-01e0-473c-8208-c6bc6ac15705.mp4

</details>

## Changelog
:cl:
add: Getting batonned makes you shake and stutter
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Makes sense considering all other shocks do this

**Review by benbot16 — APPROVED** [review]
Looks fine to me.

**Review by Archanial — APPROVED** [review]

**Comment by PestoVerde322** [comment]
wasn't this the default way way back in 2013? Anyway code looks fine to me

**Review by PestoVerde322 — APPROVED** [review]

**Comment by ivanmixo** [comment]
It do be an old feature I wanted back. (much like the attack animations)

**Pull request merged**
