### PR TITLE
Fixes BCI overlay components

### LINKED ISSUE #9597: [Bug]: New BCI update has a lot of bugs
### BYOND Version

_No response_

### Round Date

2023.08.03

### Round ID

45194

### Test merges

[#9124: 'Enable serverside 515.1609 (new)' by Crossedfall at commit 43f695e9a4](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#8776: 'Preferences: Redux' by itsmeow at commit 947fc9ffb1](https://www.github.com/beestation/beestation-hornet/pull/8776)
[#9043: ''Soft'-tracked objectives& Replacement of gimmick objectives' by PowerfulBacon at commit fee83cf66f](https://www.github.com/beestation/beestation-hornet/pull/9043)

### Describe the bug

Zrzut ekranu (15)
Overlay limbo

Zrzut ekranu (16)
Tested circuits

Overlays are imposible to removed once placed despite siganling remove overlay
Overlays persist after removing BCI
Bar overlay lacs half the imputs needed to use it (signal and enity in particular)
Counter overlay lacs a way of removing it, entity input so it can be shown on somthing instead of yourself, and udate overlay doesnt work after using it first time
BCI starts with action butons despite them being seperate components now 
Thougth lisener and target interceptor work well from my expierience so far

### What did you expect?

I expected overlays to work

### Reproducible steps

1. Make BCI
2. Add overlay components and a way to activate them
3. See results I described

### PR DESCRIPTION
**Pull request by Dejaku51**
## About The Pull Request
Fixes BCI overlay components
BCI shell doesn't come with 3 action components by default now
Fixes #9597

## Why It's Good For The Game
Working content good

## Testing Photographs and Procedure

1. Implant yourself with BCI shell with object overlay
2. Using it, make overlay on something
3. Try to remove that overlay
4. You can

Or

1. Implant yourself with BCI shell with object overlay
2. Using it, make overlay on something
3. Remove the BCI shell
4. Overlay is gone

Or

1. Insert Bar overlay into circuit
2. It has all required ports

<details>
<summary>Screenshots&Videos</summary>
No action components:

image

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
fix: Fixed BCI overlays not removing when pulsing signal
fix: Fixed BCI overlays not removing when getting rid of the BCI
fix: Bar overlay now has all required ports to work
tweak: BCI shell doesn't have 3 action components by default now
code: add_alt_appearance proc now returns created alt appearance
/:cl:

### CODE REVIEW

**Comment by Dejaku51** [comment]
actually used fix might be not correct way (even if working)

**Comment by boombaklops** [comment]
mmm yes i want relative position components

**Comment by Dejaku51** [comment]
> mmm yes i want relative position components

it is WIP

**Comment by Dejaku51** [comment]
won't be available for some time so im going to close the PR (it will be still worked on but closed)

**Comment by Dejaku51** [comment]
moff

**Comment by Dejaku51** [comment]
please don't do oopsie please please

**Comment by Dejaku51** [comment]
fuck it we split this shit into multiple PRs

**Review by itsmeow — APPROVED** [review]
Looks good to me. Tested and all.

**Pull request merged**
