### PR TITLE
[PORT] SSD people now actually sleep.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

title

## Why It's Good For The Game

fix

## Changelog
:cl:
fix: SSD people now actually sleep.
/:cl:

ORIGINAL PR: https://github.com/OracleStation/OracleStation/pull/331

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
get put to sleep for a long time you can disconnect, reconnect and only have 4 seconds of sleep

**Comment by ghost** [comment]
> get put to sleep for a long time you can disconnect, reconnect and only have 4 seconds of sleep

fixed now i think.

**Comment by qwertyquerty** [comment]
`player_logged` is rather unambiguous as to whether the player is logged on or off, you should make it more specific

**Comment by ghost** [comment]
> `player_logged` is rather unambiguous as to whether the player is logged on or off, you should make it more specific

i'm not really experienced with this, what should i replace it with instead?

**Comment by qwertyquerty** [comment]
`player_logged_off` `player_logged_on`? Whichever applies

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Just check mind.active

**Comment by ghost** [comment]
> Just check mind.active

done.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
mind.active is already set, remove all things you added that change the value of it

**Comment by qwertyquerty** [comment]
"lmao"

**Comment by PowerfulBacon** [comment]
Stale. Feel free to reopen when you make the changes.

**Pull request closed without merging**
