### PR TITLE
Revert "Revert "Server reboot delay reason will be notified in Status Tab"" and put a default reasoning

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
Revert "Revert "Server reboot delay reason will be notified in Status Tab"" and put a default reasoning

## Why It's Good For The Game
it seems admin wanted to have a default reasoning not that they totally dislike it

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image

</details>

## Changelog
:cl:
add: Server reboot delay reason will be notified in Status Tab 'again'
admin: Server delay reason has now a default value 'Server Administration (handling tickets, coding, etc)'
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
I would love to listen what admins think now

**Comment by itsmeow** [comment]
😭

**Comment by llol111** [comment]
Dont realy see the point in this
though i wasnt aware, im glad the original change was reverted

there is no need for player to know what we type in for delays. I guess it dosnt *hurt* if players get see some reasoning, but it dosnt realy help anyone either. I dont understand why you would spend any time on this.

Honestly, having to enter a reason could probabbly just be scrapped entirely. I have in my entire time here not seen anyone remotely care about the reason, be it in reading or entering it. At verry best you'll have "tickets". More likely, you'll have "a" or "qawsxdcfvgtzhuj". So for all i care just get rid of that and have it *always* say that. 
But again, why would you spend time on that?

**Comment by EvilDragonfiend** [comment]
> Dont realy see the point in this though i wasnt aware, im glad the original change was reverted
> 
> there is no need for player to know what we type in for delays. I guess it dosnt _hurt_ if players get see some reasoning, but it dosnt realy help anyone either. I dont understand why you would spend any time on this.
> 
> Honestly, having to enter a reason could probabbly just be scrapped entirely. I have in my entire time here not seen anyone remotely care about the reason, be it in reading or entering it. At verry best you'll have "tickets". More likely, you'll have "a" or "qawsxdcfvgtzhuj". So for all i care just get rid of that and have it _always_ say that default message. But again, why would you spend time on that?

the point is not showing reasons, just letting people know if it is reboot is delayed or not. sometimes admins say nothing then do tickets, and people have no idea if tickets are being handled, or someone who joined the server in the middle of delaying has the same.
for that part, specifying reasoning isn't actually the point. it's just enough to say 'server reboot is delayed' without specifying reason in the server tab.
and admins are usually busy checking things out, has no moment to just chat 'tickets'

**Comment by Archanial** [comment]
It was reverted by headcoder so he probably had a good reason for it.

**Pull request closed without merging**
