### PR TITLE
Removes absorb changeling objectives and pheromone receptors power

### LINKED ISSUE #2548: "Absorb Another Ling" obj broken

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request
Removes absord ling objective as well as pheromone receptors power.
Closes #2548

## Why It's Good For The Game

Absorb changeling is broken objective which cannot be completed.
Pheromone receptors only exist to find another ling to complete objective I am trying to remove.
Pheromone receptors encourage changeling to teamup with security and hunt down other changelings which completely breaks the gamemode and is just not funny for stealth lings.

## Changelog
:cl:
del: Removed pheromone receptors changeling power.
del: Removed absorb another changeling objective.
/:cl:

### CODE REVIEW

**Comment by Moccha-Bee** [comment]
keep the pheromone receptors its cool to go ling hunting.

**Comment by Archanial** [comment]
> 
> 
> keep the pheromone receptors its cool to go ling hunting.

no

**Comment by VictorVow** [comment]
> Pheromone receptors encourage changeling to teamup with security and hunt down other changelings which completely breaks the gamemode and is just not funny for stealth lings.

Pheromone receptors encourage hunting other lings for personal benefit. Similarly to being able to rob another traitor for their TC/gear, this is a disincentive which helps prevent a team of antags fucking over the whole station together. Removing it encourages lings to work together since they know there's little risk of being backstabbed because they can so easily escape and avoid detection if so.

**Comment by Archanial** [comment]
And that's good. Teamlings were removed but you can still buy communication (which is underused).
You get no benefit from eliminating other lings since they cannot be absorbed.

**Comment by Moccha-Bee** [comment]
> And that's good. Teamlings were removed but you can still buy communication (which is underused).
> You get no benefit from eliminating other lings since they cannot be absorbed.

they can unless someone broke it.

**Comment by Archanial** [comment]
You can just headspider out of absorption

**Comment by Moccha-Bee** [comment]
> You can just headspider out of absorption

thats utter cringe ngl

**Comment by Archanial** [comment]
blame zesko

**Comment by Moccha-Bee** [comment]
> blame zesko

if you make it take some time to be ready like the death button than it probably becomes vaible to absorb a ling.

**Comment by zeskorion** [comment]
i've been hearing issues about lings actually getting an absorption off on another ling, but not getting the objective. perhaps fix that instead. 

for the headcrab issue, simply add headcrab absorption

**Comment by Archanial** [comment]
If this gets merged you are more than welcome to revert it and fix the issues.

**Comment by zeskorion** [comment]
doesn't really fix anything

**Comment by Archanial** [comment]
that's why I called it "Removes...".

**Pull request closed without merging**
