### PR TITLE
A few radiation optimizations

### PR DESCRIPTION
**Pull request by qwertyquerty**
## About The Pull Request

Optimizes radiation a little bit

## Why It's Good For The Game

It was easy for the radiation subsystem to spin out of control

## Changelog
:cl:
fix: Optimized radiation a little
/:cl:

### CODE REVIEW

**Comment by MNarath1** [comment]
Uhh no idea if this is related but the SM on Sage stopped producing Rads at all Round id 14798 if this helps.

**Comment by PowerfulBacon** [comment]
multiple rounds this has stopped the SM from working on sage

**Comment by ghost** [comment]
this completely broke the SME

**Comment by qwertyquerty** [comment]
@Crossedfall ready for testmerge 2

**Comment by qwertyquerty** [comment]
This has only caused problems so far

**Comment by qwertyquerty** [comment]
Appears to be working now

**Pull request merged**
