### PR TITLE
Changes delta station departures.

### PR DESCRIPTION
**Pull request by AnCopper**
## About The Pull Request
image
## Why It's Good For The Game

Makes some shuttles not crash into the station.

We now also have a huge area of unused space that could be used for something useful in the future.

## Changelog
:cl:
tweak: Changed delta station departures to prevent shuttles from crashing into the station.
/:cl:

### CODE REVIEW

**Comment by dog132-ss13** [comment]
where did the sec outpost go?

**Comment by PowerfulBacon** [comment]
sad pipe
image

**Comment by PowerfulBacon** [comment]
Lights on glass :tragedy:

**Comment by PowerfulBacon** [comment]
Floating intercom
image

**Comment by PowerfulBacon** [comment]
image
comfy chairs just in the middle of the hallway? All other chairs are iron

**Comment by francinum** [comment]
This feels a little half-assed, and uh... Why?

**Comment by AnCopper** [comment]
> and uh... Why?

Find out by reading the PR description.

**Comment by francinum** [comment]
You can solve the crashing by slightly shifting the dimensions of the room and not completely refactoring it's design.
Some ships do just crash into the station and there's no great way around that, and the solution isn't this.

That space isn't going to be used considering the only departments with claim to that section are civilian and medical.

**Comment by AnCopper** [comment]
> That space isn't going to be used considering the only departments with claim to that section are civilian and medical.

I could move the exploration shuttle dock to that space, so it isn't across the entire station from science at arrivals.

**Comment by williamcll** [comment]
> That space isn't going to be used considering the only departments with claim to that section are civilian and medical.

PUBLIC CONSTRUCTION SITE WOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by Wilchenx** [comment]
You forgot about the security outpost at escape

**Comment by AnCopper** [comment]
> You forgot about the security outpost at escape

I didn't.

**Pull request closed without merging**
