### PR TITLE
Adds Maintenance drones back to stations with restrictions

### PR DESCRIPTION
**Pull request by Syrox25**
## About The Pull Request

Adds maintenance drones and their dispensers back into the maps with restrictions to access and the suppression of previously noted aggression circuits.

Requires changes to config for hour restrictions (10h in ~~silicon~~ living* was what Ruko originally asked for but up to staff)

## Why It's Good For The Game

Gives ghosts something extra to do in their downtime or those wishing to learn engineering without the pressures of the round weighing them down. ~~Or just people who are insane like me and just like being a drone.~~

## Testing Photographs and Procedure
-Drones have been pacified, Their laws prevent any form of harm so those playing in good faith will not see a change.
-Drone dispensers have been placed on all maps, generally somewhere in science maints
-Cogscarabs and (Badass)Syndrones have the trait removed in their own initialize and thus are left un-pacified
-Drones no longer have built in Captain ID. Their access has been stripped to bare minimum: Maints, APCs and External Maint airlocks

All issues that I pointed out here: https://forums.beestation13.com/t/re-add-station-drones-with-a-massive-barrier-to-entry/13603/39
have been addressed and tested to confirm they work. (Can no longer use Robo console. Can no longer open Head lockers. Can no longer open AI upload terminals. They CAN still ventcrawl the armory but at least can't use them anymore)

<details>
<summary>Screenshots&Videos</summary>

paci

image

image

</details>

## Changelog
:cl:
add: Drone dispensers added to science maintenance 
balance: Stripped drone access down to the bare minimum required.
balance: Drones had their aggression inhibitors installed properly.
/:cl:

### CODE REVIEW

**Comment by Dejaku51** [comment]
what access did you removed?

**Comment by Syrox25** [comment]
Click screenshots and videos.
image

**Comment by Rukofamicom** [comment]
Really excited and hopeful to see this merged. 

> Requires changes to config for hour restrictions (10h in silicon was what Ruko originally asked for but up to staff)

I don't recall requesting this, at least not recently. 
I think 50h living hours (not specifically silicon) might be more apt given their potential for grief, even with that potential reduced through your changes. 

> Removed Command level and lifeform affecting access.

I also want to point out that this is great not because it prevents drones from getting in, but because it prevents drones from letting **others** into places. Drones will still have access to such areas via ventcrawling, but will not be able to open the way for a friend or such.

> Drones have been given chameleon projector hats as celebration of their hardware changes.

While I understand the spirit behind this, it probably needs to go. Not because drones being able to pick their hat is bad, but because other people stealing the drone hat is bad, especially from dead drones. Find some other way to implement choosing appearance if you feel customization is necessary. There's already a few drone bodies to choose from.

**Comment by Dejaku51** [comment]
> add: Drones have been given chameleon projector hats as celebration of their hardware changes.

looks like you forgot to add this lmao

**Comment by Rukofamicom** [comment]
> looks like you forgot to add this lmao

Snowflake drones are what they added, they already come with that hat.

**Comment by Syrox25** [comment]
Thanks Ruko!
>but because it prevents drones from letting others into places

This is why I removed Vault access from them aswell.


>but because other people stealing the drone hat is bad, especially from dead drone

Impossible. You are unable to strip drones of inventory and killing them drops their storage slot and nothing else
hats
image

Edit: Even drones themselves are unable to remove it (Set to wig if you don't want a hat visible)

>looks like you forgot to add this lmao

Negative. This was just a funny way of saying that I placed Snowflake Drone dispensers on station rather than the default one. This was prebuilt code. I'm just using it. Also documented of doing so.

**Comment by AnCopper** [comment]
On /tg/ they fixed the issue of drones interfering by literally just making them shut down when in a certain radius around living players.

**Comment by Rukofamicom** [comment]
> Impossible. You are unable to strip drones of inventory and killing them drops their storage slot and nothing else

Yes I was just looking into and testing that when I realized exactly what you meant by your wording. I forgot snowflake drones existed and came with a special type of chameleon hat. Because of how it was worded, it sounded like you had explicitly given drones the normal chamleon hat.

Then aside from wanting their access almost entirely stripped (since they have access via vents unless explicitly sabotaged) I have no complaints to make. Even with what access you stripped, I don't believe they need to be using doors for most areas.

**Comment by Rukofamicom** [comment]
> On /tg/ they fixed the issue of drones interfering by literally just making them shut down when in a certain radius around living players.

And this was a pretty awful way of doing it. I like a lot of things tg does, but this was not one of their stronger decisions.

**Comment by Crossedfall** [comment]
Going to throw my key on this. Drones are excellent admin spawns. They are terrible standard spawns, even with the modifications. (Also snowflake drones should not be the default, at all)

They're far too powerful without proper moderation and it's rare that drone players actually abide by their given laws. While the proposed changes are a decent attempt at addressing this problem, I don't think it's enough and I don't trust standard drone spawns to behave. 🔑

**Comment by Syrox25** [comment]
Alright... Snowflake were added to no longer incentivise hat theft from people/lockers. They can take whatever form they like to show SOME uniqueness, even if just between each other.

They have about as much shitter potential as a pacified engineer. That's why the request for hour restrictions... Put it to whatever you feel the limit would be for the average person to not abuse a role like this. 500h Living if you feel like it... I'm not asking you to let someone with a new account on their first spawn to play drone.

Thats why I asked it be locked behind silicon hours. A role with just as much potential for grief.

**Comment by Crossedfall** [comment]
Drones don't need to have any level of uniqueness. They're drones. Snowflakes should remain admin spawn only, even if I get overruled on this PR as a whole.

You're underestimating drones if you think they're only as powerful as a pacified engineer. They have a lot more room for problem causing than you're giving them credit for, believe me.

**Comment by Syrox25** [comment]
I can:
-sabotage the SM
-Plasmaflood the station
-Welder bomb
-Activate explosives via detonator
Cripple the station in a thousand ways... but so can a lot of other unrestricted roles...

Access list is laid out in numbered order. I can remove literally all access outside of Maints, External airlocks and the ability to interact with APC If that would make you happier...

Cant fault me for trying to be nice to drones, Will remove Snowflake dispenser if that's such an issue.

**Comment by Pirill** [comment]
Excited for this and I hope it goes through. Always had fun with spawned drones when they were around.

**Comment by Syrox25** [comment]
Snowflake replaced with base drone

Removed all but 3 Access nodes: 
ACCESS_ENGINE_EQUIP (APCs)
ACCESS_MAINT_TUNNELS
ACCESS_EXTERNAL_AIRLOCKS (Not the solar or department specific ones like sec/engi)

**Comment by Syrox25** [comment]
If you cannot trust players with up to 500 hours (as I jokingly asked to no response) on your server to play a non interaction builder role with all of these restrictions... Then I don't know what to say...

YES. Drones have/had incredible potential to grief. I just don't see someone playing X amount of hours fine just to wait for that drone limit unlock to start ruining the server. People are going to grief the server no matter what. They just aren't going to jump through absurd hoops when there are hundreds of easier ways that are available on a 0h join.

Just to 100% clarify, I in no way asked for this role to be free access, even way back in my post last year.

**Comment by TerryTehCoder** [comment]
> YES. Drones have/had incredible potential to grief. I just don't see someone playing X amount of hours fine just to wait for that drone limit unlock to start ruining the server. People are going to grief the server no matter what. They just aren't going to jump through absurd hoops when there are hundreds of easier ways that are available on a 0h join.



I agree, that's also to say that any Hour Restriction at all makes grief prevention leagues more effective. Drones especially.

**Comment by FortSumter** [comment]
As a player with 1,500 hours on beestation I like the idea of drones. We don't have a guarrenteed ghost role, and sometimes I don't want to play a character. With a reasonably high living hours restriction i dont see a problem with this as no one who likes playing on the server would intentionally use the drones to grief. I would expect a drone to still probably screw up the SM, but that's just how it is sometimes. 
The only problem i have with them is if they will make being an engineer obsolete, as you will have a bunch of veteran players playing as drones and doing their job for them.
My middle ground solution would be to place one or two drone spawns on each map and allow the crew to make the choice of constructing the drone printer or not.

**Comment by Syrox25** [comment]
Drones do not have access to coms other than :b which is tied in a one way system with binary. Drones can hear silicon but silicon can't hear back. Lack of communication means that drones are kept less aware of the state of the station (compared to Engi*) unless either the AI alerts via binary or they go out of their way to check alarm pings or monitors.
Their language is also unique with only pAI able to communicate directly... for some reason...

Currently I do not believe there is even a circuit board for drone dispensers. When broken the machine drops nothing.
Would have to place X drones on station in which all would be available round start.

The machine outputs one every 1800 ticks(?) (180s) This number could be tweaked easily to limit drones if they become TOO popular. probably 8-10 min per

**Comment by williamcll** [comment]
Don't edit corgstation because it's being testmerged on my PR, I will add the drone dispenser later on.

Also, both LRP and ERP servers have drones and most rule breaking are still crew players so I don't see the problem about balance. Hell at this point an engineering borg can cause far more damage in a shorter frame of time.

**Comment by Syrox25** [comment]
Noted. Stuck in Merge conflict hell atm anyway... still trying to figure out how resolution works...

I committed the changes in original PR commit... that was probably a mistake thinking about it... altho I think this is still multicorg looking at it in S-DMM
Worst comes to worse I can always redo. For now it can sit and wait I guess, need a greenlight anyway.

**Comment by Rukofamicom** [comment]
> still trying to figure out how resolution works...

For mapping changes it pretty much doesn't. 
* You un map it (in this case deltastation) and commit
* Sync your fork
* Re map it and commit again.

I had to do this in my cyborg PR because mapping changes are "too large to be handled in web editor"

**Comment by PowerfulBacon** [comment]
I agree with crossed

**Pull request closed without merging**
