### PR TITLE
Executioners sword

### PR DESCRIPTION
**Pull request by enthethan**
## About The Pull Request
Ports GuyonBroadways executioners sword, a sword available to traitors that can perform executions
announced to the entire station.

## Why It's Good For The Game
A fun gimmicky item to kill  nonhumans/enemies of the faith with.

Takes 30 seconds to decapitate,announces to the entire station who you're executing and also where you're executing them making this purely a meme item.

## Changelog
:cl:
add: Added the executioners sword, costs 3 tc 
soundadd: Addded nasheed, inshallah brothers
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Looks like a good way to spam priority announcements

**Comment by enthethan** [comment]
today was really bussy,gonna work on this some other day

**Comment by Sun-Soaked** [comment]
You should probably make it so the "Traitor Mcgee has sentenced Clown to summary execution in the Chapel. The sentence will be carried out in 30 seconds." or whatever it ends up being announcement can only play once every minute, to prevent suffering a la PRIORITY ANNOUNCEMENT spam.

**Comment by qwertyquerty** [comment]
Checks don't pass, still working on this?

**Comment by enthethan** [comment]
closing for now gonna reopen later

**Pull request closed without merging**
