### PR TITLE
New wizard ritual - "Advent Ritual of Saint Anarchismea" (Reposted)

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
# Reposted
* #7759 

The original PR of this is from it, but I did something wrong (force-pushed) and I was not able to revive the PR... so I had to repost it.

I cleaned up some codes at this commit.

Note: original PR has a key'ed

---------------------

## About The Pull Request
adds a new wizard ritual and, tweaks knock spell with an additional effect.

It's a reopen PR as I made something bad to the original PR #7457
also, intent change spell needs more touch, so the PR no longer has it.

* "Advent Ritual of Saint Anarchismea"
2 spell points
Seeks the Saint Anarchismea's spirit and summons them onto the station. Access requirement of every electronic in the station will be magically bypassed, but also every ID card gets AA. an ID card without AA will get it again, so latecomers will get the same so that they won't lose their chance to get the blessing of Saint Anarchismea. People will be blessed with AA power
It will bypass even Rat'var or Nar'sie cult door accesses, but It's intentional. It's how magic is.
While this is super helpful to wizards, but the reason why it is 2 Spell points that the station heads and securities will not be happy with the ritual effect.

* and buff to Knock spell
Now it can 'unlock' cuffs that locked people around you (because the ritual is way too useful than knock). 

* adds Lesser Knock spell
identical to knock spell but without uncuff feature.

## Why It's Good For The Game
new feature good
MORE CHAOS BEST

## Testing Photographs and Procedure
<details>

---------------

https://youtu.be/TEIHvJwsfYY
"Advent Ritual of Saint Anarchismea"
It's re-recorded in the middle of capturing. in the video, it allowed you to hang around CentCom, but It's fixed later(no AA to CC area). but also, you can log in the communication console without access

----------------

knock spell uncuffs

image
image

image
image

cooldown time x2 when uncuffs (removed by request)

(I forgot to capture, but it works to multiple people as well)

</details>

## Changelog
:cl:
add: New wizard ritual - "Advent Ritual of Saint Anarchismea". Access requirement of every electronic in the station will be magically bypassed, but also every ID card gets AA. Latejoin people will get AA too. Everyone will uncuff themselves easily, including anything that restrains them.
tweak: Knock spell now has an additional effect - It can release cuffed people around you.
add: Lesser knock spell. It has no uncuff feature, and mostly used by non-wizards holding the spell. (i.e. battle royal participants, servant golem). very identical to knock spell.
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
kat didn't like this

**Comment by Rukofamicom** [comment]
I don't dislike this concept enough to key it, at least not yet, but I do have some major concerns:

Wizards are chaos itself most of the time, and this is generally in good fun for the majority of players that aren't just getting ganked. The chaos introduced by mass AA by comparison, tends to be headache inducing for admins and players alike. Mass access magnifies the negative impact that players with less than stellar RP have on a given round, especially those prone to bending rules. It only takes a small fraction of the current crew to be shitters, valid-hunters, self-antag prone or otherwise to devolve around from fun chaos into just being a nightmare of a round.

I think the ritual should simply give AA to all ID cards that currently exist and all of the additional effects are just excessive. This allows security to still function in at least *some capacity*, and enables the station to regain control.

**Comment by EvilDragonfiend** [comment]
Securities still have a way to jail people. they just should be creative more than before. Bolted doors are still an option. Putting people in a window wall jail (with no exit) is a way too, and deconstruct the window when they need to let people out, or and so on.

but well, I agree with the duration of the effect should be limited, but still it shouldn't be stopped and managed in a short period since wizard paid 2 points and they can take it back. The chaotic effect should last enough to create the chaos.
I will make the ritual is persistent for 1 hours and people will get AA, then once 1 hour duration is over, the AA bless is gone. That'll work.

**Comment by EvilDragonfiend** [comment]
Now it's an hour limited.

**Comment by PowerfulBacon** [comment]
After reading through the conversation I believe that:
- Spells are better when they are localised to the wizard's location and active, rather than passive like rituals as they make the wizard feel powerful.
- Personally, I'm fine with the effects being irreversable, since most of wizard is, but my main thing against is above.

Unfortunately, I have to agree with the keys here.

**Pull request closed without merging**
