### PR TITLE
Crafting fixes (#48541 & 48451)

### PR DESCRIPTION
**Pull request by Cenrus**
https://github.com/tgstation/tgstation/pull/48541
https://github.com/tgstation/tgstation/pull/48451

:cl: Skoglol, Cyberboss
fix: Fixed being able to instantly delete carded AIs by crafting an intelliTater.
fix: You can now only craft strobe shields using proper riot shields.
/:cl:

### CODE REVIEW

**Comment by Flakkyboo** [comment]
tfw you have made the exact same changes to crafting as me nice

**Comment by qwertyquerty** [comment]
Tested?

**Comment by Cenrus** [comment]
Already getting done in another PR

**Comment by Flakkyboo** [comment]
the only thing my pr doesnt add is the fix to intellicards.
so i would still add that

**Pull request closed without merging**
