### PR TITLE
Hackerjsimon bamboo update

### PR DESCRIPTION
**Pull request by hackerjsimon**
## About The Pull Request
Adds Bamboo to botany kinda like an expansion pack

## Why It's Good For The Game
Botany now has the power to grow weaponry/Syringeguns aswell ass Punji stick traps allowing them to do more during antag rounds.

## Changelog
:cl:
add:Punji Sticks(Traps)
add:Blowgun
add:Bamboo Mutation

### CODE REVIEW

**Comment by hackerjsimon** [comment]
MAY need to be updated

**Comment by Toxici11i** [comment]
/obj/item/gun/syringe/blowgun is returning invalid path, meaning it cant find the item you s k i t

**Comment by Toxici11i** [comment]
Found your issue, check under "adds bamboo sheet" - you add a crafting recipe but no actual item. also still no icons it seems

**Comment by hackerjsimon** [comment]
ah i see thanks lemme go fix it

**Pull request closed without merging**
