### PR TITLE
Slows nuka cola and meth down

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Title.

Nuka cola speed bonus decreased by 25%. I also made it give minor rads.

Meth speed bonus deceased by 50%. This is still fast, but shouldn't be as ricidilous. 

## Why It's Good For The Game

The speed bonus is insane. 

This isn't fun or fair to fight in any way, bit too meta. Nuka cola is way too easily accessible and is currently just a free speed boost.

## Testing Photographs and Procedure

<details>

<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/22431091/158041971-253cc449-329c-4687-b4f8-7eb37991f7bd.mp4

Put screenshots and Videos documenting testing and execution of intended behaviors here

</details>

## Changelog
:cl:
balance: Methamphentamine and Nuka cola speedups have been nerfed
balance: Nuka cola now deals minor radiation
/:cl:

### CODE REVIEW

**Comment by Chessus** [comment]
Shh, don't telll everyone about nukacola. Next they'll find out about Greybull's shock immune trait.

Actually giving it rads is cool. The meth change makes it a little faster than Modinfil's 0.7 speed modifier.

**Comment by ivanmixo** [comment]
>The meth change makes it a little faster than Modinfil's 0.7 speed modifier.  

Should probably slow that down too ahh. 4 am brain forgot it existed.

**Comment by PowerfulBacon** [comment]
Technically it was reduced by 33% and 40% :^)

**Comment by Isy232** [comment]
Get rid of nuka cola but meth is generally fine, its easy enough to OD on it if relying on it extensively and counters exist. It doesn't deserve a 40% nerf.

I'd ask you to atomize the meth and nukacola changes because I'd vote yes on the Nuka Cola since its just no effort.

**Comment by ivanmixo** [comment]
You can just microdose on meth at zero risk to yourself. The effort it takes is minimal.

**Comment by Isy232** [comment]
Meth has already been slowed down before, it no longer negates hardsuit slowdowns and there is plenty of equipment to counter speedups. Temperature guns, bolas, energy snares, bear traps.

> You can just microdose on meth at zero risk to yourself. The effort it takes is minimal.

Not really zero risk, just low risk. You can only fight for up until your dose is running low or you risk it running out in the middle of combat. Take another and you risk overdose.

If you'd want to give meth some of its more dangerous side effects back, I would support that along with maybe a 20% nerf, just leave some of the high speed intact.

**Comment by ivanmixo** [comment]
The high speed is cancer and the best part of meth. No. Its unfun to fight as long as it has the stupid speed.

**Review by PowerfulBacon — APPROVED** [review]

**Review by Archanial — APPROVED** [review]

**Pull request merged**
