### PR TITLE
Adds vents,piping and replaces old firelocks with modern ones at centcom

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request

read title, i just added vents and piping to centcom while also replacing the old fulltile firelocks with the modern double directional ones

## Why It's Good For The Game

1. makes it easier to traverse centcom if you can ventcrawl
2.  makes breaches a little more fixable in centcom
3. makes it easier to traverse centcom incase of a breach/plasmfire

## Changelog
:cl:
add: Added pipes, vents and air alarms to more parts of centcom
add: Added directional firelocks to centcom
del: Removed old fulltile firelocks from centcom
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Why would you need to be able to traverse centcom?
If somehow a mob gets onto centcom then they can traverse anywhere and into restricted zones.

**Comment by ToasterBan** [comment]
> Why would you need to be able to traverse centcom?
> If somehow a mob gets onto centcom then they can traverse anywhere and into restricted zones.

it's very unlikely someone is able to manipulate and cause actual harm in said restricted zones if they have ventcrawl, you can also easily get into restricted zones in multiple ways even in the EORG 90 seconds

**Comment by Sinestia** [comment]
Airlocks are w.e

 I think the concern is more people being a pain if they sneak onto centcom on like the ERT shuttle. Who cares what happens during EORG. 

 Not that that's actually going to happen that much but I also don't know why this was necessary/useful either


 If centcom breaches we literally just mapgen it if it matters

**Comment by bloons3** [comment]
Why does Centcom need atmos?

**Comment by utilbird** [comment]
The slight technical burden this adds outweighs the benefit

**Comment by ItsTisme** [comment]
CentCom should not in any case be accasible except for round end and admins. Thats the point. So these kinda gameplay changes are completly moot

**Comment by PowerfulBacon** [comment]
Completely pointless.

**Pull request closed without merging**
