### PR TITLE
Remove decal bolts

### PR DESCRIPTION
**Pull request by DrDuckedGoose**
## About The Pull Request

At some point, bolts were added to the corner of decal sprites. This reverts that.
Personally, I don't it makes sense, since regular tiles don't have bolts, and decals are supposedly just painted on.

If someone wants bolts specifically, I think they should make a seperate decal that can be added to a tile, instead of making all decals bolted.

## Why It's Good For The Game

Corrects styling?

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

with bolts
image

without bolts
image

image
image

</details>

## Changelog
:cl:
tweak: Tweaks decal sprites to look more sensible
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
Not gonna lie, I like those bolts. It was a minor detail to differentiate them from normal tiles.

**Comment by DrDuckedGoose** [comment]
I think we should either go all in on bolts, or have none at all

**Comment by MarkusLarsson421** [comment]
I mean... no reason for it to conform to the norm. Is there? Although if so, all bolts would look better.

**Comment by PowerfulBacon** [comment]
Could you show a comparison between tiles?

**Comment by DrDuckedGoose** [comment]
> Could you show a comparison between tiles from being on a turf?

Done, checkout the testing images.
They're just too faint, and they conflict with the current style logic. I think if we want bolts, they need better contrast and *most* tiles should have them

**Review by PowerfulBacon — APPROVED** [review]
The difference is near impossible to spot anyway and if we have bolts they should be on all tiles and not just painted ones

**Comment by DrDuckedGoose** [comment]
Then we should commit to then, instead of having them exclusively on decals

**Comment by Tsar-Salat** [comment]
image

The duality of man.

As original PR author, I'm fine with removal or a tile change. 
If Racc says its not uniform, I believe him. He set the tiling standard.

**Comment by PowerfulBacon** [comment]
Noticed it in game where there are areas where you can tell, the screenshots do a poor job at showcasing the differences between an area where it makes significant differences.

**Comment by DrDuckedGoose** [comment]
My bad pimp
If you like them, I can try making us bolt station. I'd just like some consistency

**Pull request closed without merging**
