### PR TITLE
EVAC Shuttles Update

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
Added cameras, holopads, extinguishers, foam dispensers, intercoms, news casters and so on to a bunch of shuttles! Most details are in the CL.

Also changes the floors, decals and whatnot to look more modern and have some more details.

## Why It's Good For The Game
Looks good, works better and is an overall improvement.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>
A few of the many changed shuttles.

image

image

image

Fire alarm also works, all the windows all have their own firelock window shutter too.

image

</details>

## Changelog
:cl:
balance: [Box, Meta, Asteroid, Bar, Birdboat, Delta, Tiny] Added cameras, holopads, extinguishers, fire window shutters, and functioning fire alarms to EVAC shuttles.
balance: [Box, Meta, Asteroid, Bar, Birdboat, Delta, Tiny] Added fire alarm to the cockpit.
add: [Box, Meta, Asteroid, Bar, Birdboat, Delta, Tiny] Added intercoms and news casters.
fix: [Meta] Fixed windows on Meta EVAC shuttle.
del: [Box, Meta] Removes defibs due to it being an undocumented change in a recent PR.
tweak: [Box, Meta, Asteroid, Bar, Birdboat, Delta, Tiny] Tweaked decals and floors.
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
Thought this was adorable. :D

image

**Comment by MarkusLarsson421** [comment]
Don't forget the defib.

**Comment by Fronsis** [comment]
> Don't forget the defib.

Doesn't makes sense, you're adding a lot of stuff that are basically ''Hug box'' for the shuttles, fair enough Centcom likes to ensure the crew have all the comodities for their shuttles, yet something as basic that's present everywhere IRL is not present on the shuttle of a futuristic space station?

**Comment by Fronsis** [comment]
By the way, just in case you didn't realize Box and Meta had Shuttle changes merged yesterday made by @ClownMoff on #11189

**Comment by MarkusLarsson421** [comment]
> Doesn't makes sense, you're adding a lot of stuff that are basically ''Hug box'' for the shuttles, 

Not really... Intercoms, news casters, and holopads aren't THAT useful. Cameras, sure. Either way, this is a balance change that wasn't addressed by that PR when it should've. It isn't that hard to bring a defib, especially when you can carry it around your waist mid to late-game. Other paid shuttles tend to include a free defib.

**Comment by MarkusLarsson421** [comment]
> By the way, just in case you didn't realize it Box and Meta had Shuttle changes merged yesterday made by @ClownMoff on #11189 

They do look great!

**Comment by Fronsis** [comment]
> > Doesn't makes sense, you're adding a lot of stuff that are basically ''Hug box'' for the shuttles,
> 
> Not really... Intercoms, news casters, and holopads aren't THAT useful. Cameras, sure. Either way, this is a balance change that wasn't addressed by that PR when it should've. It isn't that hard to bring a defib, especially when you can carry it around your waist mid to late-game. Other paid shuttles tend to include a free defib.

Foam dispensers everywhere, cameras for the AI(i believe there was a reason that AI wasn't supposed to see inside but that might've changed. the discussion i remember was from years ago), firealarm ¿? (Corg library shuttle is the perfect example of firelocks being a pain in the ass for a Shuttle) and window shutters. Not to mention they have an impact on what an antagonist can do on a shuttle.


It's not hard to bring a defib you're right, however not all shifts go as planned and if you follow the basic idea of medbay's shuttles section(they have surgery tools, medicine and some others have more advanced machinery) i see no reason why you would exclude the defibs, like i said, i've seen countless times situations where people was unable to be revived because of the lack of a defib and it suck both for the doctor who spent time trying to save someone and the dead peson waiting to see if they'll make it home alive or not. and boiling it down to ''just bring a defib next time xd'' is.. not cool.

**Comment by Rukofamicom** [comment]
This just needs mapping approval.

**Comment by Rukofamicom** [comment]
> It's not hard to bring a defib

This is going to be reverted due to being undocumented in the original PR as a matter of principle. The defib should have been disclosed and discussed in the original PR.

**Comment by PowerfulBacon** [comment]
The shuttles don't need foam dispensors, since they aren't an area the AI is intended to manage.

**Review by PowerfulBacon — APPROVED** [review]
These look very good overall

**Pull request merged**
