### PR TITLE
Detective rework: Now with your choice of one of three unique kits!

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request

Detective has been a stale job for a long while, too long overlapped by other security roles and lacking ways to contribute to investigatory side of things. No longer.

Quite a few changes so I'll split this into sections:
- A) Base Kit Tweaks
- B) Detective Beacon
- C) Other Tweaks

## A) Base Kit Tweaks

- Forensic scanner now is dual-mode. Secondary mode allows analysing health and reagents. Also unnecesary processing delays removed. 
- No longer starts with a bowman, has a normal security radio headset.
- Starts with sunglasses now. SecHUD sunglasses removed from their office. 
- Detective's glasses - they get a new pair of glasses which includes medical, diagnostic and security HUDs, plus has a meson mode. More information, more investigation. Downside is that it is **not** flashproof. 
- Detective beacon. See section B.
- Detective armour vest only available via a detective beacon kit.
- New vendor (yet to be added to maps yet) for detective's gear, since their locker was totally overflowing. 
- PDA can now scan reagents and atmos. 
- Police baton is now the subtype which allows you to actually trip people. This seems like an oversight from back when the trip/knockdown change was made. 
- Police batons can be stored in a security belt like any other baton. 

## B) Detective Beacon
Joining the chaplain, curator and magician, the detective now gets his own beacon! Choose from one of three unique kits for which suits your detective style best. 

### 1) Paranormal Investigator

Leverage the paranormal for a slower but effective approach to investigating crimes after they've happened. This kit includes a new unique set of detective clothes, a haunted magic eightball, paranormal investigator's glasses and a smelly old detective manual.

- Disco Elysium clothes ported from Fulp which look great and make you feel like a detective who truly leverages the supernatural. 
- Haunted magic eightball is pretty unreliable since ghosts can lie but it fits the theme and may have some utility or fun here.
- Paranormal Investigator's glasses is a subtype of detective's glasses which also grants the ability to see ghosts, like the Curator's ecto-scanner.
- The smelly old detective manual just grants the olfaction spell.

### 2) Undercover Agent

Use disguise and blending in to surprise criminals from an angle they didn't expect. Includes an undercover implanter, assistant disguise card, a plain radio headset with a security encryption key, a concealed carry holster, a voice disguise gas mask, a hand mirror, a set of assistant clothes and a spare detective ID. 

- The undercover implanter simply places a cosmetic indicator on you when seen via SecHUD (it's orange and flashing), which helps other Security easily identify you as an undercover agent. 
- The assistant disguise card just changes your ID card to look like an assistant one, without removing the access. 
- The concealed carry holster is like the normal detective's shoulder holster except it can't be seen on your sprite nor examined. 
- The non-chameleon gas mask matches your voice to your worn ID. 

### 3) Fast Responder

Be quick off the mark by discovering serious crimes as they happen and geared up to survive the inevitable dangerous encounters. Includes a deputy security belt, secHUD sunglasses, a bowman headset, detective armour vest, a portable health monitor, bluespace locator and two .38 TRAC speedloaders.

- Bowman headset and secHUD sunglasses since it's likely that you'll run into flashes or flashbangs if you're one of the first to discover a crime scene. 
- Armour vest and deputy belt so they're a little more geared up than other detective loadouts but not quite as equipped as an actual frontline security officer. 
- Portable health monitor allows detecting people dying as it happens and is key to being a fast responder. 
- TRAC bullets implant a short-lived tracker in targets, which can be tracked via the bluespace locator, enabling a detective to flee and later pursue if they do happen to run into a dangerous threat. 

## C) Other Tweaks

- Adds forensic data disks, for storing data from your forensic scanner permanently. 
- Hand mirrors can now be used to change your hair just like stationary mirrors. 
- Makes a generic recursive movement tracker, mainly needed for spyglasses. 

### TO DO:
- [ ] Add detective vendor to all maps
- [ ] Remove detective office secHUD sunglasses from all maps

## Why It's Good For The Game

New content for the detective which helps further define their unique role in the game. More variety of ways which they can be a threat. New clothes which are dope. 

## Changelog
:cl:
tweak: Various changes made to detective's base kit.
add: Adds the detective beacon! Choose from one of three unique kits to suit your playstyle. 
add: Detective vendor 
add: Detective's glasses
add: Spyglasses
add: Disco Elysium detective outfits
add: Undercover implanter
add: Assistant disguise card
add: Concealed carry holster
add: Hand mirrors can now be used to change your hairstyle
add: Forensic data disk for permanently storing scanner data
code: Adds a generic recursive movement tracker
/:cl:

Includes these ports: 
https://github.com/TheSwain/Fulpstation/pull/270
https://github.com/TheSwain/Fulpstation/pull/306
https://github.com/TheSwain/Fulpstation/pull/307
https://github.com/TheSwain/Fulpstation/pull/319
https://github.com/TheSwain/Fulpstation/pull/332
https://github.com/tgstation/tgstation/pull/46891
https://github.com/tgstation/tgstation/pull/47241

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I like the ideas but I don't really like kit A since it includes 2 traitor items, an item that allows you to summon a ghost to just do nothing and something that should be researched by the geneticist rather than start on people (What's the point of researching genes if Nanotrasen already issues the genetics to people)

**Comment by WhyIsCaeciliusTaken** [comment]
Use necktie roundstart:

Ghost: "AI MALF"

Remove the paranormal investigator kit please. It's a neat idea but it'll be abused to hell by ghosts to out the gamemode as soon as they're called.

**Comment by eeSPee** [comment]
> I like the ideas but I don't really like kit A since it includes 2 traitor items, an item that allows you to summon a ghost to just do nothing and something that should be researched by the geneticist rather than start on people (What's the point of researching genes if Nanotrasen already issues the genetics to people)

Spyglasses are not traitor item (on tg at least).

What if, instead of magic eight ball (which is also kinda glitchy and a tot item) and neck tie you add sec huds that can see ghosts (similar to the curator's goggles). I don't like det being able to gain metaknowledge via ghosts. It can ruin the rounds.

Maybe Paranormal Investigator starts with sechud/ghosthud glasses.
Undercover Agent starts with sechud sunglasses.
Fast responder starts with medsec.

Remove the Detective's glasses. I don't like the idea of 3 HUDs (and mesons). It's a design principle that a human should not be able to have all 3 HUDs; and this item grants them to you at roundstart.

**Comment by VictorVow** [comment]
@PowerfulBacon only the haunted eight ball is one and it's so weak/unreliable it should just be rolled into into this kit and/or curator or chaplain's choice beacons imo. 

Hm true it might make more sense if you could have only a weaker version available through injector so you need to get the full-strength version via genetics. 

But similar to why NT has the Captain's Antique but has SS13 do research for Advanced Energy Guns is the idea that they have _some_ stock of these items from past research but are depending on the station to research how to mass produce them. 

@WhyIsCaeciliusTaken I've not heard of the existing possessed sword being an issue for this however? I can see the potential for abuse but I'm skeptical since the means to do so exists already. 

@eeSPee ghost HUD is a useful ability, could be swapped for the necktie I guess. 

This is a unique item, unlike other HUDs which are mass producable including your recent combined med-secHUD PR. Diagnostic HUD added ontop of that and making it a unique item isn't all that strong. It also leaves the detective easy to flash, which is a unique and significant weakness for a security member.

**Comment by Victor239** [comment]
@PowerfulBacon only the haunted eight ball is one and it's so weak/unreliable it should just be rolled into into this kit and/or curator or chaplain's choice beacons imo. 

Hm true it might make more sense if you could have only a weaker version available through injector so you need to get the full-strength version via genetics. 

But similar to why NT has the Captain's Antique but has SS13 do research for Advanced Energy Guns is the idea that they have _some_ stock of these items from past research but are depending on the station to research how to mass produce them. 

@WhyIsCaeciliusTaken I've not heard of the existing possessed sword being an issue for this however? I can see the potential for abuse but I'm skeptical since the means to do so exists already. 

@eeSPee ghost HUD is a useful ability, could be swapped for the necktie I guess. 

This is a unique item, unlike other HUDs which are mass producable including your recent combined med-secHUD PR. Diagnostic HUD added ontop of that and making it a unique item isn't all that strong. It also leaves the detective easy to flash, which is a unique and significant weakness for a security member.

**Comment by Isy232** [comment]
@Victor239 Most of the ways to get ghost information are not available easily or early on in the round or are only available to traitors. I completely agree with Cae on that the paranormal kit needs a rework or a removal.

Also, the detective getting a multi hud isn't bad. All silicons get them so NT has the tech IC, they just likely don't mass produce them because they are expensive.

Victor, I think you should add the detectives glasses to R&D, but put them at the very end or something, requiring HEP and huds tech. For resources to print maybe include something like a bit of diamond and gold.

**Comment by MitztheKat** [comment]
You'd get a new detective if i could be a paranormal investigator.
Being able to have such a unique trait is really cool! I would personally say you can use your necktie on a corpse and if they agree they possess the necktie/you, so you'd have to find the corpse to learn who killed them. Even if the corpse is unrevivable being able to get a faster and more accurate response than reviving is great.
There'd still be the standard 10/whatever second wait period for the ghost to accept the "Detective's necktie" as it would be called to the ghost so i'd say the detective would have to stand still during that time, not necessarily near the corpse the entire time but still so an antag still has the chance to mute the detective.
This has amazing prospects, **MAKE DETECTIVE GREAT AGAIN!!**

**Comment by eeSPee** [comment]
I don't know; I personally don't like being able to reliably gain meta knowledge is a good idea.

I'm not against the idea itself, but it can be abused to ruin the game.

**Comment by utilbird** [comment]
^ angry ghosts shouldn't be able to directly help security arrest their murderer. 

Put yourself in the shoes of an antag (hopefully), you have flawlessly murdered your target and have managed to successfully dispose of all the evidence that could reveal you, only to have said target rat you out from the meta-realm because the detective picked the ghost kit.

New ""meta"" would lead to the poor det getting murdered every round ;-;

**Comment by VictorVow** [comment]
I've listened to the feedback and adjusted the kits:
- Paranormal Investigator no longer has the Horrific Necktie (which allows ghosts to possess it) nor the spyglasses.
- PI now has a subtype of detective's glasses that allows them to see ghosts, similarly to the curator's ecto-scanner goggles.
- PI's olfaction granter has been changed to a book granter to make more sense flavourwise.
- Fast Responder no longer has advanced detective's glasses, instead just secHUD sunglasses.

**Comment by utilbird** [comment]
Paranormal investigator should just be removed outright imo. Or at least remove all ghost interactions, there's not much detective work in having a ghost fly around and show you who killed them.

_Maybe_ you could give those tools to the curator so they had something to do but even then, it's extremely disruptive for antagonists, especially stealth ones.

**Comment by ike709** [comment]
I still really don't like the paranormal investigator. Remove it and fix the conflicts and this will get a proper review.

If you want to create an alternative so there's still 3 options, I'm all for that.

**Comment by VictorVow** [comment]
I still like the idea of the Paranormal Investigator but I'm open to changing the specific items included. 

The notable items are the magic eightball, PI glasses and detective manual - is one of these okay? Two? Which combination, or does a particular item need an additional nerf?

**Comment by ike709** [comment]
8-ball and glasses will be used for metagaming.

**Pull request closed without merging**
