### PR TITLE
Adds more radiation mutation effects to monkeys.

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Makes monkey mutation have 3 different effects:
 - Gorillize
 - Humanize
 - Dismember random limb.

## Why It's Good For The Game

Geneticists seem to be frequently turning themselves into gorillas roundstart, presumably because they can get a 1 hit kill attack from it. This adds some risk to that, although really its not that much.

## Changelog
:cl:
add: Monkeys now can mutate into humans, gorillas or lose limbs when affected by radiation.
/:cl:

### CODE REVIEW

**Comment by leestriter** [comment]
In my opinion becoming a gorilla already has more downsides then upsides, but if it's becoming a problem I understand the nerf.

**Comment by yyzsong** [comment]
gorrilers cant wear anything (hats, bags, masks), pull anything, or throw

leave the funny monke alone

**Comment by PowerfulBacon** [comment]
> 
> 
> gorrilers cant wear anything (hats, bags, masks), pull anything, or throw
> 
> leave the funny monke alone

I would rather nerf the normal people turning themselves into gorillas roundstart than the gorillas ability to stun on punch, effectively killing in 1 shot since that would negatively effect gorrila cubes and the defunct monkey gamemode.

**Review by utilbird — APPROVED** [review]

**Comment by eeSPee** [comment]
IMO this should be a full system (the same way DNA melt works).

There is still a 33% chance for it to happen, and the side effects are not enough to discourage people from doing it.

**Pull request merged**
