### PR TITLE
[bounty] GAGS

### LINKED ISSUE #4533: [$25 BOUNTY] Port GAGS
TG has a new system called Greyscale AutoGenerated Sprites, which enables advanced greyscale usage and generally reduces icon bloat.

There is a *large* number of PRs to port and icon files to edit, hence this bounty. A mostly (but not entirely) complete list of PRs to port can be found as part of https://github.com/BeeStation/BeeStation-Hornet/projects/2#column-7174998

Upon completion and successful testing a single payment of $25 will be sent directly via Paypal, due to the numerous problems with Bountysource. No alternative compensation options will be provided. Whomever completes it should provide their Discord info in the PR description so we can contact you.

### PR DESCRIPTION
**Pull request by BrumalLake**
Lord Scrubling#7492
## About The Pull Request
closes https://github.com/BeeStation/BeeStation-Hornet/issues/4533
1. https://github.com/tgstation/tgstation/pull/58337
2. https://github.com/tgstation/tgstation/pull/58112
3. https://github.com/tgstation/tgstation/pull/59292
4. https://github.com/tgstation/tgstation/pull/58602
5. https://github.com/tgstation/tgstation/pull/59524
6. https://github.com/tgstation/tgstation/pull/58307
7. https://github.com/tgstation/tgstation/pull/59884
8. https://github.com/tgstation/tgstation/pull/58487
9. https://github.com/tgstation/tgstation/pull/58488
10. https://github.com/tgstation/tgstation/pull/58514
11. https://github.com/tgstation/tgstation/pull/58567
12. https://github.com/tgstation/tgstation/pull/59392
13. https://github.com/tgstation/tgstation/pull/58794
14. https://github.com/tgstation/tgstation/pull/58808
15. https://github.com/tgstation/tgstation/pull/50961
16. https://github.com/tgstation/tgstation/pull/51597
17. https://github.com/tgstation/tgstation/pull/58841
18. https://github.com/tgstation/tgstation/pull/59271
19. https://github.com/tgstation/tgstation/pull/58710
20. https://github.com/tgstation/tgstation/pull/58738
21. https://github.com/tgstation/tgstation/pull/59292
22. https://github.com/tgstation/tgstation/pull/53369
23. https://github.com/tgstation/tgstation/pull/59135
24. https://github.com/tgstation/tgstation/pull/59923
25. https://github.com/tgstation/tgstation/pull/59330
26. https://github.com/tgstation/tgstation/pull/59388
27. https://github.com/tgstation/tgstation/pull/59323
28. https://github.com/tgstation/tgstation/pull/59602
29. https://github.com/tgstation/tgstation/pull/60416
30. https://github.com/tgstation/tgstation/pull/59536
31. https://github.com/tgstation/tgstation/pull/59535
32. https://github.com/tgstation/tgstation/pull/59332
33. https://github.com/tgstation/tgstation/pull/59374
34. https://github.com/tgstation/tgstation/pull/59537
35. https://github.com/tgstation/tgstation/pull/60366
36. https://github.com/tgstation/tgstation/pull/59925
37. https://github.com/tgstation/tgstation/pull/54463
38. https://github.com/tgstation/tgstation/pull/60819
39. https://github.com/tgstation/tgstation/pull/53441

`worn_icon` and `worn_icon_state` vars hold the appearance of an item on a mob now
some belt icons and things may be missing now because of this so they may need fixing
added them for some i could find in a pr

things excluded:
thermomachine and gas meters
pdas
mat datums
sombreros

## Why It's Good For The Game
less icon bloat

## Changelog
:cl: lordScrubling, ninjanomnom, Arkatos1, celotajstg, actioninja, ShizCalev, Thunder12345, Couls, ArcaneMusic, MrMelbert, Krysonism, GoldenAlpharex, RaveRadbury, bobbahbrown, Gandalf2k15
add: GAGS
add: some items can be recolorable in vending machines
add: lizard plushies come in random colors
add: space carp come in random colors
add: wrapping paper is recolorable
add: janicart gets a vacuum mod that sucks things under it into its attached bag
add: vended items go into your hands
imageadd: hue shift on lizard plushies
code: worn_icon and worn_icon_state
admin: vv_edit for gags items to recolor
/:cl:

### CODE REVIEW

**Comment by super12pl** [comment]
All cool but hue shifted lizard plushies look like compressed baystation sprite

**Comment by BrumalLake** [comment]
> 
> 
> All cool but hue shifted lizard plushies look like compressed baystation sprite

i shouldn't have pinged you about your pfp 😔

**Comment by PowerfulBacon** [comment]
Does this work with changelings assuming the clothes of someone with a gags clothes?

**Comment by BrumalLake** [comment]
> 
> 
> Does this work with changelings assuming the clothes of someone with a gags clothes?

it works fine with clings and chameleon outfits, one problem i noticed was that chameleon inhand icon states didn't update until you pick the thing up again, but that's a problem that i'm sure was there before

**Comment by PowerfulBacon** [comment]
cool

**Comment by francinum** [comment]
Not sure how I feel specifically about putting vended items directly into your hands, but that's a super nitpicky complaint.

It feels like there's a lot of unrelated shit in this PR though.

**Comment by ItsTisme** [comment]
doing gods work

**Comment by lordScrubling** [comment]
EVERY DMI FILE WHY

**Comment by BrumalLake** [comment]
image
wasn't actually as bad as i thought it would be to resolve

**Comment by BrumalLake** [comment]
HOW is this test still running
image

**Comment by lordScrubling** [comment]
probably should resolve before i lose track of the changes causing icon conflicts

**Comment by Crossedfall** [comment]
~~Marking this as a draft. Please convert when you think it's review/test ready.~~ Or not because it's been too long. Ping me when it's ready I suppose

**Comment by ike709** [comment]
This seems dead?

**Comment by BrumalLake** [comment]
yeah i'm not sure what's causing this problem with screwdriver icons

**Comment by BrumalLake** [comment]
i'm dropping this
if anyone wants to pick this up the 2 issues i saw were that
1. screwdriver inhands have a none icon over their generated icon
2. jumpsuit normal and adjusted states don't work

**Pull request closed without merging**
