### PR TITLE
Makes oddysseus's syringe gun able to synthetise all basic mutation toxins.

### PR DESCRIPTION
**Pull request by super12pl**
## About The Pull Request
Why would oddyseus be able to make unstable and pod mutation toxin but not the rest?
Makes all basic mutation toxins(non-blacklisted and non-dangerous races) able to be produced via oddyseus syringe gun.

## Why It's Good For The Game
Consistency, ~~you can now turn people into cat girls el masse~~.

## Changelog
:cl:
Balance: makes all basic mutation toxins synthetise-able
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
Can_synth was removed on all of these for a reason, namely, that mass-produceable random chems can make em. Mutation toxin grief is for shitters and species change already fucks with oegans n shit

**Comment by super12pl** [comment]
> Can_synth was removed on all of these for a reason, namely, that mass-produceable random chems can make em. Mutation toxin grief is for shitters and species change already fucks with oegans n shit

Why unstable mutation toxin and pod mutation toxin still have it then?

**Comment by PowerfulBacon** [comment]
Being able to have an infinite amount of a chemical that instantly stuns for a few seconds and can potentially kill if you choose the plasmeme one. As zesko said there is a reason they cant be mass produced, and mutation toxin only really does have its use for shitters.

Unstable mutagen is a very easy chemical to make and base for botany and pod mutation toxin probably should be removed from the pool.

**Comment by super12pl** [comment]
> Unstable mutagen is a very easy chemical to make and base for botany

Unstable mutagen and unstable mutation toxin aren't the same thing @PowerfulBacon

**Comment by PowerfulBacon** [comment]
> > Unstable mutagen is a very easy chemical to make and base for botany
> 
> Unstable mutagen and unstable mutation toxin aren't the same thing @PowerfulBacon

I read it wrong, they should both be removed then really

**Comment by Bastian0930** [comment]
consistency wise, this makes sense.

however why in the fuck is there unstable mutagen in a healing mech?

**Comment by MrHorizons** [comment]
This PR doesn't allow you to synthesize plasmaman mutation toxin, though.

**Pull request closed without merging**
