### PR TITLE
Removes funny words

### PR DESCRIPTION
**Pull request by qwertyquerty**
## About The Pull Request

Removes several instances of slurs from the game

## Why It's Good For The Game

So the git police don't take us down

## Changelog
:cl:
del: Some in-game instances of slurs
/:cl:

### CODE REVIEW

**Comment by KingTerrytheTerrible** [comment]
thats not the reason you brainlet

**Comment by ghost** [comment]
> 
> 
> thats not the reason you brainlet

its still unecessary slurs, so might aswell remove it.

**Comment by qwertyquerty** [comment]
GitHub does remove for slurs, so it's better safe than sorry. What is the reason out of interest @KingTerrytheTerrible

**Comment by nikk735** [comment]
do we really need 
'i hate you' to be you 'youre mean'
or jew to jewish 
or " feminist "," empowered woman "

**Comment by ike709** [comment]
@nikk735 
```
/datum/mutation/human/smile
	name = "Smile"
	desc = "Causes the user to be in constant mania."
	quality = MINOR_NEGATIVE
	text_gain_indication = "<span class='notice'>You feel so happy. Nothing can be wrong with anything. :)</span>"
	text_lose_indication = "<span class='notice'>Everything is terrible again. :(</span>"
```
It only applies when you have the mutation.

**Comment by nikk735** [comment]
@ike709 oh yea weird ive had those happen where it switches kill and sex etc when i dont have that mutation so i assumed it was always that

**Comment by Coolsurf6** [comment]
N

**Comment by PerroCaca2001** [comment]
Iggers

**Pull request merged**
