### PR TITLE
travis test

### PR DESCRIPTION
**Pull request by CthulhuOnIce**
travis maybe

### CODE REVIEW

**Comment by CthulhuOnIce** [comment]
aye travis works again

**Comment by qwertyquerty** [comment]
But checks failed

**Comment by CthulhuOnIce** [comment]
@crossedfall says it's a travis-side issue

**Comment by ike709** [comment]
TG doesn't seem to have this issue though.

**Comment by Crossedfall** [comment]
@ike709 TG's travis tests report that they're using a cached version of Maria so it isn't trying to rebuild the dependencies. https://travis-ci.org/tgstation/tgstation/jobs/548027284#L882

Actually issue is that the hosting mirror removed one of the dependencies listed. 

Edit: Also TG has changed how they deal with this negating the issue entirely. https://github.com/tgstation/tgstation/pull/44079

**Comment by Crossedfall** [comment]
Kali is still hosting the required build dependency: `http://old.kali.org/kali/pool/main/m/mariadb-connector-c/libmariadb-dev_2.3.3-1_i386.deb`

**Comment by optimumtact** [comment]
update your lib mariadb

**Comment by Crossedfall** [comment]
> 
> 
> update your lib mariadb

Update your `j u i c e`

**Comment by qwertyquerty** [comment]
fight fight fight

**Pull request merged**
