### PR TITLE
Globo-slow

### PR DESCRIPTION
**Pull request by AnCopper**
## About The Pull Request

Increased movement delay across the board by 50%.

## Why It's Good For The Game

Everything in Bee is extremely fast-paced, slowing it down a notch will make rounds last longer, fights be less of two people dancing across the screen, and people will be more inclined to stay in one location and talk.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://streamable.com/hw987q
</details>

## Changelog
:cl:
balance: Increased movement delay across the board by 50%.
/:cl:

### CODE REVIEW

**Comment by Penwin0** [comment]
Please do provide a video showing the new speeds

**Comment by DrDuckedGoose** [comment]
Globo slowmo

**Comment by PowerfulBacon** [comment]
50% is huge.
One idea I had was to give people a slowdown during any combat (taking damage, shooting,  attacking etc.) And lessening the damage slowdown.

**Comment by AnCopper** [comment]
50%
https://streamable.com/hw987q

**Comment by FriendlyContractor** [comment]
I thought 50% would feel super slow but it actually looks pretty reasonable seeing the video. You should however definitely go over various sources of slowdown and reduce their effects across the board since things like bola would now practically force you to stand still.

**Comment by Coding-Grape** [comment]
> Everything in Bee is extremely fast-paced, slowing it down a notch will make rounds last longer

Personally I disagree. 
Lowering speed this drastically without compensating for it would have disastrous effects on the round length as a whole, as response time to things which need to be delt with promptly (SM, anomolies, meteors, etc) which aren't necessarily player action based would drastically increase the amount of shuttle calls that aren't via a transfer vote, thereby decreasing the length of the rounds 

Not to mention any slowdown in mining being a fucking death sentence, and no miners means no mats means shuttle call happens sooner 

I do think that the infinite running everywhere thing is a problem, but removing the ability to get places quickly in an emergency situation because you want people to RP is a bad solution for a problem that barely even exists.

**Comment by EvilDragonfiend** [comment]
I think it's huge slowdown even after I see the video. It should have less number. My expectation for the value id 20%.

**Comment by AnCopper** [comment]
Here's 25%

https://streamable.com/pzj3ow

**Comment by CydiaLamiales** [comment]
I agree with Coding Grape's points but I'd also like to add that this massively buffs guns and thrown weapons. I really don't think it's a good idea to lower movement speed. If anything, just make sprinting consume stamina.

**Comment by FriendlyContractor** [comment]
@Coding-Grape
> Lowering speed this drastically without compensating for it would have disastrous effects on the round length as a whole, as response time to things which need to be delt with promptly (SM, anomolies, meteors, etc) which aren't necessarily player action based would drastically increase the amount of shuttle calls that aren't via a transfer vote, thereby decreasing the length of the rounds.

Decrasing movement speed will have minimal effect on most of the tasks as transition time is neglegible in comparasion to time it takes to perform them and there is almost always a lot of leeway.

>Not to mention any slowdown in mining being a death sentence.

This is a valid point and has to be adressed. Either fauna has to be made slower or players faster when on lavaland.

**Comment by CydiaLamiales** [comment]
> Decrasing movement speed will have minimal effect on most of the tasks as transition time is neglegible in comparasion to time it takes to perform them and there is almost always a lot of leeway.

I strongly disagree. Being twice as slow can be the difference between you running to atmos to start pumping cooled N2 into the SM loop in time or a delamination.

**Comment by FriendlyContractor** [comment]
> I strongly disagree. Being twice as slow can be the difference between you running to atmos to start pumping cooled N2 into the SM loop in time or a delamination. Same for anomalies, scientist taking twice as long to reach them will lead to far more burned down rooms and delimbed crewmembers.

Its a good thing if those disasters happen more often(i still stand by the opinion it will not make them happen more often thought) - it generates things for players to do which they are often lacking!

**Comment by Coding-Grape** [comment]
I'm just of the personal opinion that meteor rounds will become an immediate shuttle call no matter the map (especially on fland) and the majority of shuttle calls are because of a reason that isn't related to player movement speed 

> > I strongly disagree. Being twice as slow can be the difference between you running to atmos to start pumping cooled N2 into the SM loop in time or a delamination. Same for anomalies, scientist taking twice as long to reach them will lead to far more burned down rooms and delimbed crewmembers.
> 
> Its a good thing if those disasters happen more often(i still stand by the opinion it will not make them happen more often thought) - it generates things for players to do which they are often lacking!

Yes, but a major part of why it's good for the game in your rationale is that it would make rounds last longer, and rounds won't last longer if central primary hallway is burnt down or has massive holes from meteors (which are already near impossible to defend against on fland)

**Comment by CydiaLamiales** [comment]
Oh right, I completely forgot about how this would impact meteors. A meteor announcement is already very likely to force a shuttle call, this will just solidify that. Which means this can actually make rounds last shorter.

**Comment by itsmeow** [comment]
Most of the game is NOT combat, making the ENTIRE game slower just for combat is dumb

We are an RP server, not a combat server

**Comment by itsmeow** [comment]
:key: Rather than slowing the entire game down to address issues like people leaving RP situations at the speed of light, or combat being hard to click on people, we should seek another solution like adding stamina for running, encouraging walking through other means.

A global slowdown breaks almost all other slowdowns (to the point of being unbearable), makes big maps annoying to navigate, and addresses several non-issues (the rounds being too short? I frequently have rounds hit 90mins, and it's never any fun)

**Comment by Kratairo** [comment]
> > Decrasing movement speed will have minimal effect on most of the tasks as transition time is neglegible in comparasion to time it takes to perform them and there is almost always a lot of leeway.
> 
> I strongly disagree. Being twice as slow can be the difference between you running to atmos to start pumping cooled N2 into the SM loop in time or a delamination. Same for anomalies, scientist taking twice as long to reach them will lead to far more burned down rooms and delimbed crewmembers.

Tbf they really should make stabilising the SM a lot harder, it already is piss easy

**Comment by CydiaLamiales** [comment]
^ be the chad traitor who starts fusion in the SM chamber and makes it basically impossible to stop the delamination.

**Comment by PowerfulBacon** [comment]
I don't think this is the way to go about it, speed needs designing.

**Comment by hotimep** [comment]
mfs have CLEARLY never seen bee LRP's move speed...

**Pull request closed without merging**
