### PR TITLE
Removes deepfriedholder & elementizes deepfrying. Fixes a few frying bugs

### LINKED ISSUE #10125: [Bug]: Deepfrying bluespace capsules seals the contents inside them
### BYOND Version

_No response_

### Round Date

N/A

### Round ID

N/A

### Test merges

_No response_

### Describe the bug

When testing if I could eat "unique" items by deepfrying them inside a BS capsule, I found out you can't eat it after doing so, permanently sealing the contents of the latter inside it, since you can't open it either.

### What did you expect?

I expected the bluespace capsule to be able to be eaten, or it not being able to be deepfried.

### Reproducible steps

1. Put item you want to seal into BS capsule
2. Close BS capsule
3. Deepfry BS capsule
4. Try eating/opening

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports:
- https://github.com/tgstation/tgstation/pull/44128
- https://github.com/tgstation/tgstation/pull/55253
- https://github.com/tgstation/tgstation/pull/64594
- https://github.com/tgstation/tgstation/pull/70787
- https://github.com/tgstation/tgstation/pull/71551

## About The Pull Request

closes #10125 
reverts #10128 since I fixed the source of the issue, and can confirm the problem no longer occurs

PR 1

Fixes cooking oil not respecting reagent permeability. Now the BIO damage resistance on clothing won't be completely ignored by this reagent(among other protections it could bypass). Slightly upped the damage it can deal to account for the average crewmembers jumpsuit BIO protection, bringing it back to around normal levels for the average unarmored player.

Also standardizes permeability on humans and monkeys, because it was snowflaked before, for some reason.

PR 2

Creates a blacklist that should enforce indestructible items not being affected better. Moves all stuff we REALLY dont want getting deepfried to this list. 

The stuff on the previous, lesser blacklist is stuff that technically can be fried, we just don't want to fuck with someone trying to deconstruct the machine.

PR 3

Stops things normally deepfryable that are storing other items from being fried. This should prevent weird edge-cases where frying something and eating it would delete the internal items, irrespective of the internal items flags & destructibility

PR 4

Putting reagents in the deepfryer through a beaker or otherwise will no longer play an attack animation

PR 5

Removes the deepfryholder item completely. Replaces it with an element, as we should have done in #5568

## Why It's Good For The Game

Apparentely I reverted some deepfrying behavior 6 months ago in #8748 that Ive only just recently been made aware of.

Additionally, deepfrying code is pretty ancient and has been causing issues, especially when new features are added such as deployables.

Finally killing it should fix further issues.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/2764841a-fdc0-44b3-9369-057403bdf190

Banana takes longer to eat because my character isnt hungry and it considers cooking oil in the reagents when consuming

</details>

## Changelog
:cl: rkz, timothymtorres, Ghommie, MrMelbert, prodirus
tweak: Cooking Oil damaging mobs now respects that mobs reagent permeability (i.e. clothing BIO damage resistance)
tweak: upped the damage output by Cooking Oil a tiny bit to account for average crewmembers jumpsuit.
refactor: Turned deepfriedholder into an element. Deepfrying stuff is no longer ancient code, and is much cleaner.
fix: Deepfrying respects indestructibility, always.
fix: Adding reagents to the Deepfryer will no longer display an attack animation
fix: Adds a check that prevents normally deepfryable/edible items that also can store items inside them from being fried. Should stop weird edge-cases where consuming said item would qdel indestructible items inside.

code: our file with defined colors looks less terrible
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
Reminder to myself this needs testing evidence for:

- [ ] damaging mobs with fryer
- [ ] deepfrying items
- [ ] deepfrying food
- [ ] frying items with cooking oil spray

**Comment by Tsar-Salat** [comment]
Alright, it works as expected, however it does not account for oldfood at all. Ill put a bandaid in. Hopefully we wont be using it long as oldfood is phased out

**Comment by Rukofamicom** [comment]
Skipping review due to draft

**Comment by Rukofamicom** [comment]
> balance: upped the damage output by Cooking Oil a tiny bit to account for average crewmembers jumpsuit.

It is not a balance change if it is done to preserve the status quo and avoid making actual changes to game balance.

**Review by Rukofamicom — APPROVED** [review]

**Pull request merged**
