### PR TITLE
Fixes the sprites for Medbay and Science jumpskirts

### PR DESCRIPTION
**Pull request by CydiaLamiales**
## About The Pull Request
Fixes the sprites for the medbay jumpskirts and the science one. Apparently some of the new sprites simply got copy-pasted ontop of the old ones which resulted in things like this : 

image

This PR updates the sprites to actually be the ones https://github.com/Naevii made

## Why It's Good For The Game
Actually good looking sprites - good

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

fixed_skirts

</details>

## Changelog
:cl: Naevi
imageadd: Fixed the sprites of Medbay and Science skirts
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I kinda think they looked better before

**Comment by PowerfulBacon** [comment]
oh wait it seems theres an issue with the sprites
image
These pixels go past the outline, if this is meant to be the hand then why is the skin of the arm invisible?

**Comment by ivanmixo** [comment]
Uhh.. no this is how it was in the source files I got when implementing them. 
geneleft

**Comment by CydiaLamiales** [comment]
And here we go, merge conflict because of the engineering skirts

**Review by PestoVerde322 — COMMENTED** [review]
Fix the Merge conflict and its good to go.

**Comment by CydiaLamiales** [comment]
It's still running checks, what the hell

**Comment by CydiaLamiales** [comment]
I swear to god this shit is broken.

**Comment by CydiaLamiales** [comment]
Don't merge yet

**Comment by CydiaLamiales** [comment]
Now it's ready

**Review by PestoVerde322 — APPROVED** [review]

**Pull request merged**
