### PR TITLE
Text-to-Speech

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

Yes hello tis me, here to bring you cool and good stuff tm
Some of my work from https://github.com/tgstation/tgstation/pull/50002 brought here
Generator: https://github.com/TiviPlus/ss13_tts_generator_tg
Porting https://github.com/tgstation/tgstation/pull/48106 would also improve the quality of this but muh atomization

Features: 
-Full TTS for say()
-Toggle for hearing TTS
-Config for TTS
-D O C U M E N T A T I O N
-Potential for expansion to global TTS (i.e. AI vox, adminbus "vox")

Ping me in discord at Tiviplus#7803 if you have any concerns
## Why It's Good For The Game

Yes

https://streamable.com/xzmwr
aeiou
https://streamable.com/76lqt
https://streamable.com/skssz
https://www.youtube.com/watch?v=fPD3nmG4F8A

https://streamable.com/6kepw2

## Changelog
:cl: TiviPlus
add: Text-to-speech! Everything you say now makes you actually play a sound with a dna-linked voice
add: New preference to toggle whether you hear TTS sounds or not
config: New TTS global config
soundadd: New TTS generator
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Everyone is just going to turn it off

**Comment by qwertyquerty** [comment]
The majority of things are just going to be a massive garble of voices. People will find a way to abuse it, and everyone will just toggle if off.

**Comment by PowerfulBacon** [comment]
For the love of all that is holy make it default to off

**Comment by TiviPlus** [comment]
>The majority of things are just going to be a massive garble of voices.

Most player interactions are one on one, and screaming in a crowd is already hopeless (chat is scrolling so fast noone wil notice im gay) so this is a non-issue.

>People will find a way to abuse it, and everyone will just toggle if off.

It's got a spam cooldown and a message length limiter so you're welcome to try.

>For the love of all that is holy make it default to off

Yea sure why not

**Comment by ike709** [comment]
Haven't had time to review the code yet, but I support the idea as long as it's a player pref that defaults to off.

**Comment by Lagomorphica** [comment]
Doesn't this destroy bandwith based off the PR on /tg/station and quotes by ActionNinja?

Plus doesn't it nerf the already near-useless voice changing devices aside from changeling full body shift?

If these issues got fixed disregard it but I just took a moment to read through the original PR you made on /tg/ - and while I understand this is edited I'd rather know if these issues exist.

**Comment by qwertyquerty** [comment]
As actioninja said, this constantly sends files to clienta

**Comment by ike709** [comment]
We're closing this... pretty much for the same reasons TG did.

A potential alternative implementation could work entirely clientside by having goonchat send requests to https://github.com/calzoneman/aeiou then playing the wav file it responds with, though I've spent no more than two minutes thinking about this so there will probably be limitations, even if it'd be feasible.

**Pull request closed without merging**
