### PR TITLE
CorgStation - The BeeForum Smoothening

### PR DESCRIPTION
**Pull request by VickiMorris**
## About The Pull Request
Generally modifying CorgStation based off of requests and suggestions mentioned on [this post on the forums](https://forums.beestation13.com/t/add-some-missing-stuff-to-corgstation/19626/24) with changes so far including!

Security:
-Added: x3 WT-550 rubber mags to armory
-Added: DROPNet beacon to armory
-Reduced size and supplies of Corg Sec Medbay massively
-Added Sec break room and evidence storage in Sec Medbay region
-Moves two security spawns to new sec break room
-Replaced 2 Security lockers in sec office with 1 L3 Locker, and 1 L4 Locker

Cargo:
-ORM moved to internal cargo office wall
-Former ORM location now window to preserve sight-line
-Fixed delivery office cable being missing
-Replaced office airlock with a windowed one
-Unblocked QM's chest drawer in office

Sci:
-Moved Toxins burn chamber air alarm to outside airlock
-Added button for toxins burn chamber shutters
-Slightly expanded toxins burn chamber area to allow placement of air alarm
-Airlocks to toxins and explo given names
-Added: 3x Cable Coils to robotics

Library:
-Added curator console to allow printing paintings
-Added x4 painting mounts. 2 public, 2 private to curator.

Botany:
-Removed botany backroom maintenance
-added all-in-one grinder, chemmaster
-added additional lockers
-Added Backpack sprayer + botany book

Kitchen:
-Added box of donuts to kitchen counter
-Removed botantist ability to enter kitchen

Virology:
-Added two L3 lockers outside of the transit tube on the virology mini-sat

## Why It's Good For The Game
While I do love Corg, it does have a few little things that make it just a little bit rough around the edges. Minor things like missing tools you have across every other station is rather noticeable when you're only on this map one out of ten times, and it's a slight pain to deal with :V

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

~~I will be adding actual photos of the final map when I'm done testing it, so far this represents about 30 minutes of very unfocused work just to get a rough idea of how to change things.~~

image
image
image
image
image
image

</details>

## Changelog - Uhhh I'll get to this when I properly PR this and don't just have it as a draft
:cl:Impish_Delights
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
/:cl:

### CODE REVIEW

**Comment by CydiaLamiales** [comment]
Thanks a lot for doing this. I have my grievances with corg but this'll at least make it bearable.

**Comment by PowerfulBacon** [comment]
Thanks for the PR, I like the changes described in this PR however I have some issues with the armoury ones
image

First of all, the armoury looks very strange with this new smoothing.
Secondly, the shotguns on Corg are purposely removed and have WT auto-rifles instead to replace them and keeping the WT rifles over the shotguns are preferable.

**Comment by CydiaLamiales** [comment]
> Secondly, the shotguns on Corg are purposely removed and have WT auto-rifles instead to replace them

Bacon did you forget that Cargo can have a bounty for two riot shotguns? This usually leads to player interaction, like a secoff coming along with a cargo tech to ensure the shotguns actually get delievered. And ordering them from CC only to send them back feels hacky.

**Comment by PowerfulBacon** [comment]
Yes, but that does not change my position.

**Review by PestoVerde322 — COMMENTED** [review]
Everything seems in check, however I double checked piping/wiring just in case and there's a cable piece missing by the delivery office

immagine 

Also, on my personal opinion both shooties and SMGs are fine, but if Bacon feels off about having both of them, just leave SMGs. Also personally I like the new armoury shape.

**Comment by VickiMorris** [comment]
I'm gonna be working on this PR for a bit to bring in a whole grab-bag of changes to corg, and I'm perfectly fine with removing the shotguns again if there's a legit reason. Considering how cheap riot shotguns are and the fact there *are* actual ballistic weapons, I'll change it back for now.

**Comment by VickiMorris** [comment]
Made some major changes to security and minor ones across the station. This gives botanists a condimaster and grinder at round start, but removes their ability to just walk into the kitchen. I also reverted the original changes to armory, consolidated the riot gear to one rack, added some additional WT-550 rubber magazines, and added a DROPnet beacon. The QM's office is also tweaked mildly to close #7215

The Corg infirmary is still mildly advanced compared to most others by having a defib mount and surplus limbs & blood, but it no longer has twice as many medkits, two stasis bed, three surgical duffels, and two defibs.

<details>
<summary>Screenshots</summary>

Botany Backroom 2 0
Corg Sec Medbay
Reverted Armory Changes
image


</details>

**Comment by FortSumter** [comment]
As an AI enjoyer, the intentionally placed windows to make every single APC visible from a main hallway iirc makes me think you really must hate malf AI as a concept. I'd like to ask you to replace some of these windows with solid walls so that hacking APCs is at least possible without being totally obvious. 

The other part of corg that's pretty asinine if that half of it is a maints area only connected to it via a tube, making it an easy antag base for cult and blob the same as the pubby church. Viro only being connected via tube also tends to have viro get disconnected from the station, preventing the virologist from doing their job at best, imprisioning them at worst.

**Comment by VickiMorris** [comment]
> As an AI enjoyer, the intentionally placed windows to make every single APC visible from a main hallway iirc makes me think you really must hate malf AI as a concept. I'd like to ask you to replace some of these windows with solid walls so that hacking APCs is at least possible without being totally obvious.

I haven't done much in terms of modifying sight-lines in terms of the main hall, and infact the only change I've done that makes things *more* open is a single door in the cargo office area by changing it from solid to windowed. Corg does feel weirdly open with its frank over-abundance of windows in-place of walls across the map, but that's how Corg has always been styled IIRC. I'd would love to start plastering over some windows with walls to see how it feels instead, and might try that out when I open up StrongDMM next time.

The [MapDiff bot](https://mdb2.affectedarc07.co.uk/images/162356927/8171062998/m/0/0-diff.png) that runs on PRs should show every change I've made, with the only major overhauls to the botany back room and the northern part of sec/infirmary

> The other part of corg that's pretty asinine if that half of it is a maints area only connected to it via a tube, making it an easy antag base for cult and blob the same as the pubby church. Viro only being connected via tube also tends to have viro get disconnected from the station, preventing the virologist from doing their job at best, imprisioning them at worst.

I honestly 100% agree with the concept behind the "leisure asteroid" as I call it being more accessible to the public, as it's a cute little outdoor camping area, but virology being regulated to a minisat makes it no different than Xenobio on Meta, or even Viro on Delta with the weird long hallways and mantrap airlocks between their region and the rest of the station. It sucks, but I wouldn't say it prevents them from doing their jobs.

**Comment by FortSumter** [comment]
> Corg does feel weirdly open with its frank over-abundance of windows in-place of walls across the map, but that's how Corg has always been styled IIRC. 

It has always been styled that way, I just assumed you were the one who made Corg or at least that was an intentional design choice you meant to keep as a map maintainer. Corg is heavily designed to make almost every APC that is visible by camera also visible via a window from a main hallway, meaning the AI can only hack one or two APC and remain covert. Being an AI is already a somewhat miserable existence, getting lucky enough to be a malf AI shouldn't be ruined by with map you end up stuck on.

> It sucks, but I wouldn't say it prevents them from doing their jobs.

It very much does. The difference between a shitty-looking hallway like xenobio has on meta and a transport tube is that if the shitty hallway gets broken, a scientist has the tools in their department to replace the window themselves and even if they didn't fix it, they can survive the brief depressurization in order to get into their department.

With the tube, once that breaks the only way viros getting to his lab is via a spacewalk. That requires a space suit from EVA which the Viro may not get access to depending on the whims of command or the AI and the only way to fix the tube is getting an RPD, which is a somewhat uncommon tool since it can only be found in engineering and printed from two protolathes after the research is done. If the tube is broken early into the round, or in some rare cases _roundstart_, the viro looses so much precious time unable to do anything.

While I don't play Viro, it becomes my problem when the tube breaks and viro is stranded in their lab. One time someone with an assassination objective did this intentionally and killed the viro long before anyone could get in there due to the need for a hardsuit and the abysmal airlocks we have. If you still don't agree with Hallway > Tube, then at least put a teleporter beacon in there so if this shit happens we can just give the viro a hand teleporter.

**Comment by PowerfulBacon** [comment]
Regarding the windows point, I don't think it has a higher APC visibility than most other maps.
Engineering is not visible at all from the main hallways, in science only robotics and the R&D lab are visible which is the same as almost all other maps, HOP office is visible which is the same as all maps, security is only partially visible due to short view ranges like most other maps, cargo has visibility into only the security room and the office with the main department being mostly obscured, medical has no windows aside from the entrance into it and most service rooms have visibility on par with other maps. There are a portion of APCs placed only visible to the AI in the core to get them started out and a portion of the departmental windows can be shuttered.

**Comment by PowerfulBacon** [comment]
The connectivity between the asteroid and viro are valid points

**Comment by VickiMorris** [comment]
Gonna be abandoning this for now as I'm stepping away from Beestation, anyone is free to take the changes I've made so far and use them for their own jumping off point. I'll leave the PR draft open for a few more days before closing it myself.

**Comment by Pro-gamer-window-vista10** [comment]
can you fix the supermatter airlock to not require atmos access?

**Pull request closed without merging**
