### PR TITLE
Ports SCP-173

### PR DESCRIPTION
**Pull request by ro5490**
## About The Pull Request
Adds SCP-173 plus its relevent effects, sounds, icons and so on.
Admin spawn only currently.

Original creators - JakeDaBoss and Kachnov / https://github.com/SS13-SCP13/SS13-SCP13
Hippie Port by - Toxici11i / HippieStation/HippieStation#12224
Code adjustments by - Ro5490

## Why It's Good For The Game
Big boi horror factor.
SCP-173 will literally snap your neck for blinking.

## Changelog
:cl:
add: adds SCP-173
add: adds SCP Pry-door code to airlocks
fix: fixed Blindness Spell
fix: fixed Statue-code
soundadd: added soundfiles for necksnaps
imageadd: added some icons for SCPs
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
> Admin spawn only currently.

>currently

😳

**Comment by ro5490** [comment]
> > Admin spawn only currently.
> 
> > currently
> 
> 😳

Might make it a super low chance random event at some point but thats off in the distance

**Review by Crossedfall — CHANGES_REQUESTED** [review]
Will help you fix the line ending issues here in a bit. There's also a lot of excessive white-space that needs to be sorted out before a proper code review can start.

**Comment by ro5490** [comment]
> Will help you fix the line ending issues here in a bit. There's also a lot of excessive white-space that needs to be sorted out before a proper code review can start.

Cool, let me know when, I'll be on til late anyway

**Comment by ro5490** [comment]
I fucked stuff up, gonna have to make a new PR goddamnit

**Pull request closed without merging**
