### PR TITLE
Reduces Multilingual quirk's cost from 2 to 1

### PR DESCRIPTION
**Pull request by super12pl**
## About The Pull Request
Reduces cost of multilingual quirk from 2 to 1.

## Why It's Good For The Game
One random language roundstart (that you probalby never gonna use) for 2 points is absurd when compared to traits like self-aware, freerunning, drunken resilence or skittish. Changing it to 1 point would make it actually worth picking.

## Changelog
:cl:
balance: Multilingual now costs 1 point instead of 2
/:cl:

### CODE REVIEW

**Comment by AnjelicaChaykovsky** [comment]
Such trait exists?

**Comment by super12pl** [comment]
> Such trait exists?

it was added 2 days ago

**Comment by ModDownloading** [comment]
Alternatively, make it so that it uses a menu similar to tg's phobia choice menu to determine which language you start with, so you basically just get a budget version of the curator's starting ability. It would take extra code but would also justify the 2-point cost.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
@Crossedfall broken travis

**Pull request merged**
