### PR TITLE
Makes mining hardsuit ash storm proof but makes it more expensive

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request
title

## Why It's Good For The Game
promotes using the hardsuit on lavaland to mine as the slowdown makes combat harder while the ashproofing allows you to effectively mine 24/7 aslong as you dont die to one of the other many threats of lavaland

## Changelog
:cl:
add: Mining Hardsuit is now ash storm proof
tweak: Mining Hardsuit now costs more to buy and has less stamina armour
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
This is silly.

**Comment by ToasterBan** [comment]
heard some people liked the idea so i tried it

**Comment by Mick1299** [comment]
Bit on the fence about this. Off the top of my head, the CE, atmos, and captains hard suits are the only completely fireproof suits currently available on the station (Yes, there are more, but I'm talking readily available every round). This would add an easily acquired source of fire proof, just to let miners mine during an event that should see them go back to base or huddle in a shelter.

**Comment by williamcll** [comment]
Supporting. 

Problem is there's no incentive to get the mining hardsuit for the sake of mining since we don't mine asteroids like on NSV.

**Comment by BrumalLake** [comment]
> 
> 
> Bit on the fence about this. Off the top of my head, the CE, atmos, and captains hard suits are the only completely fireproof suits currently available on the station (Yes, there are more, but I'm talking readily available every round). This would add an easily acquired source of fire proof, just to let miners mine during an event that should see them go back to base or huddle in a shelter.

actually, this just bumps up its temperature resistance by 5000K, but theres cooler solutions from tg such as the envirobags https://github.com/tgstation/tgstation/pull/59752

**Comment by ike709** [comment]
lol

**Pull request closed without merging**
