### PR TITLE
Cleanup of our worst namelist

### PR DESCRIPTION
**Pull request by francinum**
## About The Pull Request

AI list full of references

squid list reference nervere

## Why It's Good For The Game

rule go brr

### CODE REVIEW

**Comment by Archanial** [comment]
You are literally removing megatron and keeping " S A M"
???

**Comment by francinum** [comment]
I cleaned up names based on a quick google of the name, not my deep and parenthetical knowledge of media.

**Comment by PowerfulBacon** [comment]
image

**Review by ike709 — APPROVED** [review]
No fun allowed.

**Comment by qwertyquerty** [comment]
lame

**Pull request merged**
