### PR TITLE
Mixing meth and mannitol now makes toxin

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Makes mixing meth and mannitol synthesize toxin.

## Why It's Good For The Game

The meta right now for chemists is 9u meth + whatever many u mannitol. This is extremely metagamey and bad, while also sidestepping the main (and only) downside of meth. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/22431091/177198029-9a9679e1-8471-407a-84b5-a39b6cfdb7aa.mp4

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
balance: methamphetamine mixed with mannitol makes toxin
/:cl:

### CODE REVIEW

**Comment by DerpiestBruh** [comment]
based?

**Comment by EvilDragonfiend** [comment]
I think it should be handled in mob metabolisation proc to add/remove something rather than using real chemical reaction.

**Comment by heepox** [comment]
Based?
but it should make an explosion instead hahahaha

**Comment by FortSumter** [comment]
Bad. I like the other PR better.

While we don't really have a proper source of Toxin besides the vending machines, Meth is a very complex drug to make and having the combo of meth +mannitol make Toxin wouldn't be balanced. Chemists job is literally to know how to make drugs and what they do. Rukofam is looking to kill meth anyway.

**Comment by PowerfulBacon** [comment]
Closing in favour of one of the other 2 PRs

**Pull request closed without merging**
