### PR TITLE
[PORT] Improves chem dispenser macros (#45397)

### PR DESCRIPTION
**Pull request by Cenrus**
https://github.com/tgstation/tgstation/pull/45397

Fixes macros in the chem dispenser.

## About The Pull Request

This removes chem dispenser text macros and replaces them with a recording function. This allows you to still use macros, but you must record them yourself. You are no longer able to paste in a pre-written macro.

When the dispenser is recording, trying to dispense chems will record to the in-progress macro instead and won't dispense like normal. You can then save this macro when you're done recording and use it like you would before.

Using an existing macro while recording a new one will record the macro contents to the in-progress macro, and can be done multiple times.

## Why It's Good For The Game

It forces chemists and bartenders to learn the recipes for themselves first if they want to get the macros going quickly.

## Changelog

:cl: JJRcop
del: Removed text macros from the chem dispenser.
add: Replaced with dispenser input recording macros.
fix: chem dispenser macros
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
Have you tested it?

**Comment by Cenrus** [comment]
Yes.

**Comment by eLeCtrOssSnake** [comment]
Am I the only one who is having an issue with the new recording? I never used any,  but this doesn't work at all.

**Comment by ike709** [comment]
Conflicts.

**Comment by MarkSuckerberg** [comment]
Fix the conflicts, please

**Comment by Cenrus** [comment]
Done and done

**Comment by 123chess456** [comment]
this needs a wiki change

**Pull request merged**
