### PR TITLE
Carbons suffer from "appearing faint" instead of pale from bloodloss

### PR DESCRIPTION
**Pull request by Tsar-Salat**
## About The Pull Request
All carbons now "appear faint" from bloodloss.

## Why It's Good For The Game
Skinless species can't really suffer from pale skin, so this made a different baseline for the diagnosis. An individual with low blood will present multiple other symptoms rather than just being pale, including dis-coordination, lethargy, and slurred speech.

These symptoms have been tied up in a catch-all symptom of "appearing faint", which can conveniently be applied to any carbon that operates on blood volume.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

faint1
faint2
faint3
faint4

</details>

## Changelog
:cl: RKz
tweak: Paleness is no longer the presenting symptom for bloodloss. It has now been wrapped up into a catch-all term of "appearing faint", which can be applied to any carbon with a blood level, Organic or Inorganic.
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
oh shit whats the NOT operator again

**Comment by Tsar-Salat** [comment]
> surely you forgot the existence of kapulimbs.

fuck, i forgot for a moment.

And what a blissful moment it was

**Comment by ivanmixo** [comment]
Test this. I'm pretty sure as it is now it'll look like,

`She has appears faint.`

**Comment by Tsar-Salat** [comment]
faint1
faint2
faint3
faint4

**Review by ike709 — APPROVED** [review]

**Pull request merged**
