### PR TITLE
Fixes Bugs with overlay lighting Part 1

### PR DESCRIPTION
**Pull request by Dejaku51**
## Why It's Good For The Game
Bugfixes are good

TODO
- [x] Fix Security Cameras
- [x] Fix Mechs lights
- [ ] ~~Fix skinsuits hardsuits glowing (#5921)~~
- [ ] ~~Black isn't Black enough~~

## Changelog
:cl:
fix: Fixed Security cameras not working properly with Overlay Lighting
fix: Fixed Exosuits having really small light
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Also you can see unlit tiles.
image

**Comment by Dejaku51** [comment]
> Also you can see unlit tiles. image

can't see a problem

**Comment by PowerfulBacon** [comment]
> > Also you can see unlit tiles. image
> 
> can't see a problem

The darkness isn't completely black, high contrast or bright monitors can see in the dark completely

**Comment by BrumalLake** [comment]
can see it
even if you don't have enough gamma you can right click to see the objects on the tile

**Review by ike709 — APPROVED** [review]
I hope you're fixing those other 2 bugs in another PR.

**Pull request merged**
