### PR TITLE
medical wrench makes you glow while suiciding

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
medical wrench makes you glow while suiciding

## Why It's Good For The Game
crossed left a todo for this to be added

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
add: medwrench suicide glows
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
This looks bad in the screenshot provided.

**Comment by etherware-novice** [comment]
BRO

**Comment by etherware-novice** [comment]
JUST TELL ME IT LOOKED BAD I CAN REPLACE THE EFFECTS

**Comment by RDS88-beeman** [comment]
crossed; someone do this later
ether: okay
bacon: no

A comedy in three acts

**Comment by etherware-novice** [comment]
GOD- AT LEAST GIVE ME A CHANCE TO DEFEND MYSELF BEFORE CLOSING IT OUTRIGHT

**Comment by RDS88-beeman** [comment]
closed =/= declined.
but i don't think this is what crossed had in mind

**Comment by etherware-novice** [comment]
@PowerfulBacon can i please just have another chance to make a glow

**Comment by PowerfulBacon** [comment]
I mean, sure I guess

**Comment by etherware-novice** [comment]
@PowerfulBacon so..can you reopen?

**Pull request closed without merging**
