### PR TITLE
Modernises the box labour shuttle.

### PR DESCRIPTION
**Pull request by Absolutely-Steph**
## About The Pull Request

I've recently noticed that the box shuttle is really fucking old, either that or it's dumb. This pulls it out of the stone age with the following changes:
-Oxygen Tanks
-Small first aid station featuring a first aid kit, a bed&IV stand, and 4 random bloodbags
-Tinyfans, so that you can actually use it outside of just ferrying prisoners from lavaland.

The new layout is more generalised to support a wider variety of use-cases, now that supercruise is starting to come along in use. It has a larger general crew area, with a small 2x3 area for passengers/prisoners/cargo.
The windows are placed centrally on both sides, to function as provisional embrasures for officers shooting outside using lasers.

## Why It's Good For The Game

I've noticed that ever since supercruise came out, security has used their labourshuttle more as a general response vehicle than a ferry, this is fine and good on the newer shuttles, but box is just not designed to cope with it.

I'm also debating whether to put a recharger into it, but that might be too much.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
tweak: tweaked the box labour shuttle
/:cl:

### CODE REVIEW

**Comment by Absolutely-Steph** [comment]
is this just mapdiffbot being a goofball or is the map actually broken somehow? Because it works perfectly locally.

**Comment by PowerfulBacon** [comment]
Why does a shuttle used for ferrying people between A and B need an IV stand?
Also theres nowhere for prisoners to sit on their way back to the station.

**Comment by Absolutely-Steph** [comment]
> Why does a shuttle used for ferrying people between A and B need an IV stand? Also theres nowhere for prisoners to sit on their way back to the station.

Because that's no longer their sole use, and security duty often involves being shot at by people, which tends to be quite blood-draining. Having small first aid capability in what is essentially a police transport sounds like a good idea.

I wasn't sure about putting chairs in there, but if that's something you want, I can do that.

**Comment by itsmeow** [comment]
Yeah, I've seen and used the labor shuttle as way more than just "transport between labor camp" (the teleporter exists anyway). It's great for helping explo kill the assassin target that stole the explo shuttle, or for chasing down a criminal with the science shuttle, or for going to recover explo's bodies, etc.

**Comment by itsmeow** [comment]
Also maybe put a second flasher button on the bottom right wall by the windoor, so you can flash the subject before opening it without running up to the console?

**Comment by itsmeow** [comment]
Also MDB is just goofy, try `git commit --allow-empty` to rerun

**Comment by PowerfulBacon** [comment]
The shuttle should remain primarily as a transport shuttle to fulfill its intended purpose, security can outfit it themselves if they want to use it for combat purposes. They shouldn't get an IV drip standard on it.
Also it's now basically free escape from lavaland prison due to the glass

**Comment by itsmeow** [comment]
Lavaland prisoners can already go outside, you can't escape from it.

You also can't fly the shuttle without access.

I agree no IV drip, otherwise the changes are more QoL than anything and imo the holofan is absolutely necessary.

**Comment by Absolutely-Steph** [comment]
I hear ya, here's the new version:

image

We got:
-No more medical bed and IV, first aid kit is kept.
-More secure prisoner containment.
-A chair for the prisoner.

**Comment by PestoVerde322** [comment]
Looks good but there's some room for improvement: first off I'd put three chairs to the back of the shuttle, and move the ORM to where there's the crate+window. Second as much it's a neat tech, the burners+thrusters off grid may cause visibility troubles, aka they would look weird. Lastly, you should swap floor colours, Red for prisoners, grey+dark grey for crew.

**Comment by Fronsis** [comment]
Honestly this labour shuttle should be the standard for all stations i don't see a reason why it should be exclusive to Box (unless "box labour shuttle is just the general name) 

If i were to suggest something would be for that crate to contain pickaxes, i've been in some rescue missions to retrieve dead explorers and we had to comeback because we had no way into the ruins thanks to the asteroid surrounding it

Also 100% agreed on Pesto suggestion but i'd like the extra chairs to remain on sec side too since those rescue missions usually are two-three officers(or a chase of pirate shuttle) so it'll be six chairs in total.

Maybe move the health-kit to the crate too and add some oxygen masks for emergencies and on the table you could have the pair of cuffs and a recharger?

**Pull request closed without merging**
