### PR TITLE
Re-adds mining vendor jetpack upgrade / reverts explorer mask.

### PR DESCRIPTION
**Pull request by PerishedFraud**
## About The Pull Request

 This PR does two things:

1 - It re-adds the old suit jetpack upgrade that was in the mining vendor. I removed this myself back when miners were expected to stick to Lavaland, as it was out of place. Now that miners can go to asteroids for both ores and loot, the upgrade is reasonable. 

2 - It changes the explorer mask to allow eating without cutting off the tank supply. This was already changed once and I'm assuming it was changed back due to copy-pasting. Either that or someone really hates basic convenience. Either way it makes sense considering the deadly atmosphere in lavaland.

## Why It's Good For The Game

 Makes mask less annoying. Brings back an old item that's warranted again. Overall positive change.

## Changelog
:cl:
tweak: tweaked a few things
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
It doesn't make sense eating thru a solid gas mask. Why have it even be toggleable if you can just eat thru it no matter what?

**Comment by PerishedFraud** [comment]
The realism argument never really holds value in a game like ss13. Besides that, we have other masks that allow eating. Just a day ago i found out that the owl mask does, though that's a niche example. More commonly there's the fact that everyone can annoy sci/engi for welding masks after 3 minutes, and those are also solid masks that allow you to eat, not to mention the welding function. On that note, miners and (maybe, arguably) exploration crew are the only ones who truly have reasons to have a mask that lets you eat to begin with, and even then only miners actually both use a mask and encounter food actively during their job.

To recount: while the concept is slightly unreal, we know from other masks that it's something that exists. Thus we give it to players who actually benefit from it. 

The only thing I can agree on is removing the toggle as it becomes pointless. I'll see to it after i deal with merge issues since I forgot how to pass checks due to my absence.

**Comment by KubeRoot** [comment]
`mining_equipment` was replaced with `vendor_equipment`, since mining vendors now share code with explorer vendors. Your code still uses the former.

**Comment by PerishedFraud** [comment]
Oh thanks, I missed that.

**Pull request closed without merging**
