### PR TITLE
Arcade Tokens

### PR DESCRIPTION
**Pull request by Kerbin-Fiber**
## About The Pull Request
Changes the way Arcade Machines dispense their prizes.

## Why It's Good For The Game
Using a token system for redeeming prizes will be better incentive for aspiring Gamers to use arcade machines. Although, it adds some "immersion," very little.

Later, we should be able to save up coins to use them in a prize vendor and choose what prizes we want. For a price.

## Changelog
:cl:
add: Added Arcade Tokens
add: You can get prizes from putting arcade tokens (and bananium coins, if you're into wasting bananium) into an arcade machine to get prizes!
/:cl:

### CODE REVIEW

**Comment by Kerbin-Fiber** [comment]
still very new to ss13 byond code pls no bully

**Comment by SomeAngryMiner** [comment]
ah, yes, good pr, im tired of getting snapops everytime.

**Review by MarkSuckerberg — APPROVED** [review]
Yeah, this is a good idea and I like it, code seems to be reasonable and I trust you've tested it so yeah

**Comment by Kerbin-Fiber** [comment]
Yeah, I tested it to make sure that emagged machines work perfectly fine. You can't just put a token in an emagged machine and get free bomb.

**Comment by Kerbin-Fiber** [comment]
I'm going to test changing the Arcade Coins in delta maint to actual Arcade Tokens, but I'm not a mapper, so wish me luck.

**Comment by Kerbin-Fiber** [comment]
I guess that means I managed to not fuck up the maps. Nice.

**Comment by MarkSuckerberg** [comment]
yeah the maps are merged

**Comment by Crossedfall** [comment]
Added an empty commit so that the map diff bot would render the changes.

**Comment by qwertyquerty** [comment]
Hell yeah

**Comment by Kerbin-Fiber** [comment]
test merge when

**Pull request merged**
