### PR TITLE
TGUI Upgrade

### PR DESCRIPTION
**Pull request by Crossedfall**
## About The Pull Request

Resets and upgrades our current TGUI to the pre-next version. This should help with compatibility and legacy support when we can start bringing over TGUI-next. The actual number of changes is a pretty inflated thanks to removed files and recompiled TGUI assets. 

**Note:** I've gone ahead and ported over the sources for some of the new interfaces TG added. They're not used by anything right now, so they shouldn't have any impact on the game. This will make future porting pretty easy if we want to bring over any of those items.

Edit: I have tested this locally and did not have any problems using the more complicated interfaces.

## Why It's Good For The Game

`s p e e d` and `c o m p a t i b i l i t y`

## Changelog
:cl:
refactor: Re-ports TGUI
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Do you really expect us to review 57 files of code? Just testmerge it.

**Comment by Crossedfall** [comment]
> 
> 
> Do you really expect us to review 57 files of code? Just testmerge it.

No, I expected you to test it locally for like 5 seconds before moving it to production.

**Comment by Crossedfall** [comment]
Got @MarkSuckerberg to test it locally for me and they confirmed that there were no issues during their cursory check. Proceeding with a test merge on Golden.

**Comment by Crossedfall** [comment]
Had a wine user report problems. Not entirely sure why they would have any issues considering this is a direct /TG/ re-port.

**Comment by Crossedfall** [comment]
Alright. Fingers crossed this time. @ike709 confirmed it looked fine locally on his machine so I'm re-test merging it to Golden.

**Comment by ike709** [comment]
Can this be merged?

**Pull request merged**
