### PR TITLE
Abyss Station [Map]

### PR DESCRIPTION
**Pull request by DrDuckedGoose**
## About The Pull Request

image

Abyss Station is a new multi-z map, featuring several unique major features, including-

- [X] The map is submerged under an ocean of *expired* blood. Yes, admins can change this to meth in-game.
- Several jobs have been given unique map specific changes, such as xenobiology & engineering.
  - [X] Xenobiology now features a more manual approach, prompting users to actually engage with the game.
  - [ ] Solar panel equivalent alternate power solutions 
- [X] Themed hardsuits for ocean exploration.
- [X] Doormats! 
- [X] Ocean themed fauna.
- [X] Ocean themed flora. 
- [X] Elevators.

And more!

## Why It's Good For The Game

- More map diversity creates interest in the game. 
- Lowers the chance that I have to play on Kilo.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

These are in-dev shots. There's some fucked up shit going on in maints especially right now.

</details>

:cl:

/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
> '' Xenobiology now features a more manual approach, prompting users to actually engage with the game.''

If you mean doing the old surgery method and not relying on the computers, this was attempted on Fland development iirc and it was very hated by players for multiple points, eventually most maintainers agreed to just keep xenobio as it it since it's balance is a whole nother can of worms.


>Station level resources for mining.
>New incentives to encourage mining to stay on station Z.
Keep in mind that Bacon is currently working on a revamp on mining to making in-station + gateway i suggest you take a look at  the ''Mining rework+lavaland removal'' on the thinktank section of the forums to get an idea

So this is 2 z-levels, what's the aimpop for this map?

**Comment by DrDuckedGoose** [comment]
> If you mean doing the old surgery method and not relying on the computers, this was attempted on Fland development iirc and it was very hated by players for multiple points, eventually most maintainers agreed to just keep xenobio as it it since it's balance is a whole nother can of worms.

It's not too wild of a change. It's pretty close to the vanilla gameplay, with just a little more leg work involved. You can still build the actual console, because this is meant to be an early game solution. It's a little better on space allocation too, so you're not running a marathon.

> Keep in mind that Bacon is currently working on a revamp on mining to making in-station + gateway i suggest you take a look at the ''Mining rework+lavaland removal'' on the thinktank section of the forums to get an idea

I'm trying to keep a theme of smaller changes leading to larger improvements. This won't be a huge change overall, and chances are it'll be done long before Bacon's rework is implemented. Probably worth taking a look at though, yeah.

> So this is 2 z-levels, what's the aimpop for this map?

The Zs are used in a way that doesn't necessarily create more space for population. Rather, I'm trying to use Zs to divide areas / topics. The hope is that security has a longer retreat / assault, so antags aren't as pressured / have more room for silly shit, same for command. Engineering is partitioned off too for no real good reason other than it helps with explosions and offers more project space for engineers.

Recommended pop probably sits around 30-40+, probably fine for much bigger pops too. Minimum could probably sit comfortably low.

**Comment by Rustyfoxb** [comment]
Is the map just one giant iron lung refrence with the blood water?

**Comment by DrDuckedGoose** [comment]
I was originally implementing an 'underwater' map and later thought it'd be neat / interesting to have a non-water ocean.

**Comment by Rustyfoxb** [comment]
Evn if it ain't a refrence, could you add a small ester egg or something, like a some useless deco that looks like the pipes you can find or the monolith?

**Comment by Nosnek199** [comment]
eldritch horror map my beloved. this looks sick as hell so far.
What is your idea behind the enigma matrix?

**Comment by DrDuckedGoose** [comment]
> eldritch horror map my beloved. this looks sick as hell so far. What is your idea behind the enigma matrix?

It was initially gas mixture based engine, but I'm currently reworking it into something more independant & consistent.

**Comment by itsmeow** [comment]
image
inb4 elevator disconnects pipenet

or worse, *connects* pipenet between zlevels through eldritch magic

**Comment by itsmeow** [comment]
Also putting the AI sat on z1 is a huge no no, you can just deconstruct the roof and then boom core access

**Comment by DrDuckedGoose** [comment]
> image inb4 elevator disconnects pipenet
> 
> or worse, _connects_ pipenet between zlevels through eldritch magic

Pipes are blacklisted
image

> Also putting the AI sat on z1 is a huge no no, you can just deconstruct the roof and then boom core access

No worries, easy fix with some elevators.

**Comment by DrDuckedGoose** [comment]
image
hahaha

**Comment by itsmeow** [comment]
I like the map although I wish it had a little more use of multiz than as a "hallway lengthener"
MultiZ can make a station feel *more* connected through the use of balconies, glass floors, and stacking areas cloesly together rather than isolating areas with maintenance

**Comment by MarkusLarsson421** [comment]
I really loooove the design of all the rooms. Though I feel like every room is 50% bigger than it has to be. Unsure if this is a good or bad thing. Feels a bit... off in a way.

**Comment by DrDuckedGoose** [comment]
> I like the map although I wish it had a little more use of multiz than as a "hallway lengthener" MultiZ can make a station feel _more_ connected through the use of balconies, glass floors, and stacking areas cloesly together rather than isolating areas with maintenance

The intention from the start wasn't to use multi-z in the traditional sense. I specifically didn't want something like Glow, a map that felt very open. Maybe It's just not a good map because of the way I've set it up, but that remains to be tested.

> I really loooove the design of all the rooms. Though I feel like every room is 50% bigger than it has to be. Unsure if this is a good or bad thing. Feels a bit... off in a way.

Huh?

**Comment by DrDuckedGoose** [comment]
Worst case scenario, we pull a corg

**Comment by Rustyfoxb** [comment]
> Worst case scenario, we pull a corg

Hope that won't happen as corg is pain

**Comment by Rukofamicom** [comment]
If you pick up development again in the future, ping for stale label removal

**Pull request closed without merging**
