### PR TITLE
remaps viro

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
Remaps virology on delta, meta, pubby, and box.
Virology no longer has private atmos or an airlock
All virology windows are electrified, and viro walls are reinforced

Virology is divided into two sections: testing/quarantine and the lab. The testing/quarantine section includes medical's patient rooms, which can now be bolted from both the outside and the inside. It also includes the general monkey holding pen, walled off from view and with a mounted flasher and handcuffs, and four more monkey pens- one medium one for testing/mutating contagious disease, and three very small ones for isolated testing. The quarantine section includes several beds for sick patients, and panic buttons in several places, including the lab and cmo's office. These buttons lock the quarantine section down with shutters

The Lab section contains an interior section, with viro smartfridges, and two pandemics, as well as materials to make a very limited cure supply. This could be turned down to a single-virologist setup, so one virologist will generally man the exterior section of the virology lab
The exterior section of the virology lab contains two smartfridges, one public and one private, a chemmaster, and another pandemic, as well as a decent supply of viral PPE. This section is primarily for the virologist to distribute care for diseases 

Box
image
Delta
image
Meta
image
Pubby
image

## Why It's Good For The Game
discussion in dev chat is talking about viro's isolation. I'm pretty neutral on this change, but i did it anyways cuz i was bored. this is designed to make viro more visible, and able to do their job of curing and treating viruses far more easily

## Changelog
:cl:
tweak: remaps viro on delta, pubby, meta, and box
imageadd: changes PANDEMIC and virus food dispenser icons
/:cl:

### CODE REVIEW

**Comment by Mat05usz** [comment]
Is that a PANDEMIC in the room that's separated only by a windoor? If so, viros will probably use that room only and I'm not sure if making room with dozens of diseases so available to the outside world is a good idea. Maybe add some shutters?

My other problem is that it kinda makes viro invulnerable from space now, so less potential for antags/xenos/sec fighting cult etc. 
Otherwise, these look nice.

**Comment by zeskorion** [comment]
> Is that a PANDEMIC in the room that's separated only by a windoor? If so, viros will probably use that room only and I'm not sure if making room with dozens of diseases so available to the outside world is a good idea. Maybe add some shutters?
> 
> My other problem is that it kinda makes viro invulnerable from space now, so less potential for antags/xenos/sec fighting cult etc. Otherwise, these look nice.

it does make them vulnerable from maint, instead of space. The department is rendered far more vulnerable, with most workplaces having a door directly to maint, and the department being easily visible meaning attacks on med will now more likely affect viro

**Comment by Mat05usz** [comment]
> it does make them vulnerable from maint, instead of space. The department is rendered far more vulnerable, with most workplaces having a door directly to maint, and the department being easily visible meaning attacks on med will now more likely affect viro

Hmm yeah, but what I meant was vulnerability by having windows to space, now it's just Rwalls or doors, but I guess doors are easier to get through?

Viro also loses that high security by being far away vibe, but maybe it's just me. Overall it's a nice change, but consider adding shutters to the room that's exposed to the public.

**Comment by Fronsis** [comment]
Oh nice, something that i've been also eager to since that only a few maps have it (i think corg and fland) is a full Quarantine button on CMO office that will close medbay if there's a big outbreak (which is usually where it happens rather than only on virology office)

**Comment by PowerfulBacon** [comment]
image
these decals broken

image
These 2 machines look weird next to each other, since they have the exact same sprite

Again here
image

Viro should internally have regular walls, only the maints sections should be reinforced, medbay accessible areas should be regular walls.

Changes seem good to me though

**Comment by zeskorion** [comment]
> image these decals broken

fixed

> image These 2 machines look weird next to each other, since they have the exact same sprite
> 
> Again here image

a new sprite has been added

> Viro should internally have regular walls, only the maints sections should be reinforced, medbay accessible areas should be regular walls.

fixed the interior rwalls. I think viro should keep fully surrounding reinforced walls, though. it's a huge liability if something breaks in from medbay

**Comment by Archanial** [comment]
Conflicts

**Comment by zeskorion** [comment]
> Conflicts

will resolve in a bit. been busy

**Comment by zeskorion** [comment]
FUCK that was a hassle. done.

**Comment by PowerfulBacon** [comment]
image

image

This really needs 3 lights?

There any lightswitches on meta?

**Comment by zeskorion** [comment]
> image
> 
> image
> 
> This really needs 3 lights?
> 
> There any lightswitches on meta?

addressed

**Comment by zeskorion** [comment]
Ugh, fuck me

**Comment by PestoVerde322** [comment]
While I fully support for an expansion of virology, some stuff are a bit odd, first off in all the maps there's this entity:

immagine

which i suppose it popped out whenever you did an update merge, so please address them.

Also all of the virology offices have now maint access doors, not sure if it's acceptable gameplay wise, might need more opinions on that.

There's also this issue with the electrified windows:

immagine

Suggest to change this to the following setup to avoid issues later on:

immagine


And also, Vector doesn't have his bed in any of the new virologies,, cruel.

per-map issues:

### Boxstation

weird wiring :

immagine

This might be a pain, as when it load ingame it might suddenly break, suggest to move the outlet somewhere else:

immagine

### Deltastation

Not a fan of this under-window piping, consider making those pipes to pass trough the door (and in other locations around virology really):

immagine


### Metastation

Tiles under Window and odd piping:

immagine

This is weird, meta is the only station with a more lax quarantine pen, compared to say delta's pen which is a permabrig lite, intended?

immagine

Odd zoning:

immagine

### Pubbystation:

Same as meta, lax quarantine pen, intended?
immagine

Overall, I'd say if this the direction we're going with the viro, I wouldn't really mind it, however it might need further "standardization" on all the maps, like in Delta you could fit another virology room; and personally I feel there might be an issue with contact based transmission due to the nature of those new virologies setup being really tight.

**Comment by zeskorion** [comment]
> While I fully support for an expansion of virology, some stuff are a bit odd, first off in all the maps there's this entity:

fixed

> Also all of the virology offices have now maint access doors, not sure if it's acceptable gameplay wise, might need more opinions on that.

Virology is no longer super fortified. thats the point of this

> There's also this issue with the electrified windows:

fixed

> And also, Vector doesn't have his bed in any of the new virologies,, cruel.

fixed
> per-map issues:
> 
> ### Boxstation
> weird wiring :

not actually an issue for gameplay, is it?

> This might be a pain, as when it load ingame it might suddenly break, suggest to move the outlet somewhere else:

as stated in discord, this is valid, repeatable pipe configuration.


> ### Deltastation
> Not a fan of this under-window piping, consider making those pipes to pass trough the door (and in other locations around virology really):
> ### Metastation
> Tiles under Window and odd piping:

fixed tiles, but the piping isnt that egregious, is it?

> Odd zoning:

fixed

> This is weird, meta is the only station with a more lax quarantine pen, compared to say delta's pen which is a permabrig lite, intended?
> ### Pubbystation:
> Same as meta, lax quarantine pen, intended? 

Due to your issues with consistency, i've added extra barriers to both 
image
image




> Overall, I'd say if this the direction we're going with the viro, I wouldn't really mind it, however it might need further "standardization" on all the maps, like in Delta you could fit another virology room; and personally I feel there might be an issue with contact based transmission due to the nature of those new virologies setup being really tight.

eh. contact isnt a big deal, considering that you should have PPE in the quarantine wards. i dont want viro to take up more space than this already demands

**Comment by PestoVerde322** [comment]
Like i mentioned you directly on discord, aside the stray old remains of the former Virology on Delta and the odd piping on Meta (and also with no outlet outside the station like the other one), everything else seems good to go.

**Review by PestoVerde322 — APPROVED** [review]
All the things are fixed, and even if delta2's piping is terribly cursed, I think it's good to go!

**Review by PowerfulBacon — APPROVED** [review]

**Comment by 4rchibald** [comment]
@zeskorion 

Disposals in maints on Meta are broken by this PR

disposalviro

As you can see you have two pipe segments placed on same tile, one of them is curved and ejects trash on the tile above it. Once it is fixed you should probably still give disposals some testing to see if trash thrown into each bin around changed areas is actually going to disposal room or is it ejected somewhere on the way. They are a pain in the butt to diagnose  

Also some distro pipes are hidden below disposal, same is happening in another spot

disposalviro2

**Comment by itsmeow** [comment]
image
shame

shame

shame upon the merge conflict committer

**Pull request merged**
