### PR TITLE
Explo shuttle redesign A

### PR DESCRIPTION
**Pull request by BriggsIDP**
## About The Pull Request

Sister PR: https://github.com/BeeStation/BeeStation-Hornet/pull/9695
This PR: shuttle redesign A, aims to make the shuttle much more open, removing walls and doors that are unneeded and moving the objects that are away from the center.

## Why It's Good For The Game

The current shuttle's design is old and annoying for many players, these PRs both remove the air lock and replace it with a tiny fan, greatly increasing the room explo have to work with.

## Testing Photographs and Procedure

image

</details>

## Changelog
:cl:
tweak: exploration_shuttle.ddm updated
tweak: added power cabling for station side explo on meta and box
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
Yeah, this is the better one IMO. 

That damn wall just got in the way when it comes to storing materials and just made me want to circumvent the supercruise mechanic and use quantum pads. 

Double-sided shutters is nice too.

**Comment by Fronsis** [comment]
This one looks nice, some bigger ships have that kind of vibe and the default meta-delta explorer ship has always been the one that people complained the most

HOWEVER while i'm also fan of Space Cat DON'T YOU DARE to replace Tom he's a VERY important member of exploration team and has been since day one.. :( AND REMEMBER he's space proof once you add him back in case you forgot

**Comment by Nosnek199** [comment]
TOM IS DEAD! LONG LIVE TOM!

**Comment by BriggsIDP** [comment]
> This one looks nice, some bigger ships have that kind of vibe and the default meta-delta explorer ship has always been the one that people complained the most
> 
> HOWEVER while i'm also fan of Space Cat DON'T YOU DARE to replace Tom he's a VERY important member of exploration team and has been since day one.. :( AND REMEMBER he's space proof once you add him back in case you forgot

Tom lives again!

**Review by PowerfulBacon — APPROVED** [review]
Seems to be the more popular option

**Pull request merged**
