### PR TITLE
Nice job closing 3 PRs I spent hours on

### PR DESCRIPTION
**Pull request by ghost**
image

## About The Pull Request
Good job taking out sheldoniscool
Yeah I spent hours on those PRS yet you couldn't take 3 seconds to confirm if your assumption was correct. Pretty cringe.

### CODE REVIEW

**Comment by TotallyNotChief** [comment]
lol cope

**Comment by WhyIsCaeciliusTaken** [comment]
You're supposed to be repobanned, I don't get what you mean.

**Comment by WhyIsCaeciliusTaken** [comment]
You're supposed to be repobanned, I don't get what you mean.

**Comment by ike709** [comment]
image

**Pull request closed without merging**
