### PR TITLE
Magical / Holy EMP + explosions are protected by anti-magic

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Magical (explosion/empulse) Behaviours:
 - Explosions will not affect turfs with magic protected mobs on them.
 - Empulses will not affect contents of mobs with magic protection.

Holy (explosion/empulse) behaviours
 - Explosions will not affect turfs with holy mobs or bless turfs on them.
 - Empulses will not affect turfs with blessings on them, or mobs with holy protection.

## Why It's Good For The Game

Magic explosions and EMPs can now be blocked by the correct magic sources.
Nerfs cult EMPs by making them blockable by holding a bible, or by the chaplain blessing the station.
Fireball explosion will no longer affect the chaplain

## Testing Photographs and Procedure

I tested this but don't have any screenshots.

## Changelog
:cl:
balance: Magical EMPs no longer affect magic protected mobs
balance: Magic explosions (fireball) no longer affect magic protected mobs
balance: Holy/cult EMPs no longer affect blessed turfs
balance: Holy/cult EMPs no longer affect mobs with holy protection
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
when you say fireball, does it count the firebreath gene too?

**Comment by PowerfulBacon** [comment]
> when you say fireball, does it count the firebreath gene too?

Yes, but I will update that.

**Comment by PowerfulBacon** [comment]
Works fine

**Comment by Isy232** [comment]
> Explosions will not affect turfs with magic protected mobs on them.

Wait, wont think make chaplains grenade/bomb immune, or is it only explosions from magical sources. This could be made more clear.

**Comment by PowerfulBacon** [comment]
> > Explosions will not affect turfs with magic protected mobs on them.
> 
> Wait, wont think make chaplains grenade/bomb immune, or is it only explosions from magical sources. This could be made more clear.

image
This is the behaviour for magical explosion

**Review by Archanial — DISMISSED** [review]
code looks good

**Review by Archanial — APPROVED** [review]

**Pull request merged**
