### PR TITLE
pethats [bugfix] 

### PR DESCRIPTION
**Pull request by kit-katz**
## About The Pull Request
here we are once more
fixes some oversights from the pethatPR namemly
- headsprites of cats not rendering when said cat is laying or sitting (icon_state missmatch WHO KNEW)
- only Ian can be used as a hat
- kittens cannot be used as hats

- there is a function of a prior merge that sets a cat's rest state to false when picked up. but the icon state was not updated.
now it is
- corgies fixed
- kittens fixed

## Why It's Good For The Game

bug bad
fix good

## Changelog
:cl:

fix: when put on your head cats now render 100% of the time
fix: normal corgies can now be put on your head not only Ian
fix: kittens can now be put on your head 

/:cl:

### CODE REVIEW

**Review by Archanial — CHANGES_REQUESTED** [review]
Cat sprites should be visible if the mob is resting.

I did not think about sitting, because you couldn't wear anything that is not pai before. 

See here for previous solution #2725. I highly suggest you modify this parent proc with laying check instead of forcing their icon state.

**Comment by kit-katz** [comment]
resting and sitting very much does fuck up with the headsprites. id assume the var and the icon_state are not linked
also resting and sitting seem to be 1 variable
solution? link the var and the icon_State so your check does work...

**Comment by Archanial** [comment]
This is because headsprites use icon_state and sitting/resting add _resting to it (or something). 

It checks if mob is resting then unrests it changes its sprite

**Comment by kit-katz** [comment]
yes i am aware of the first part and no it does not do the second part.
i checked it and yes there is code to update PAI sprites when updating
but there doesnt seem to be such code for cats.

**Comment by kit-katz** [comment]
ight after some testing and back and forth. i came up with this... basically a simplified version of the PAI's var-held_state "link"
at first i was a bit worried about the janky collars but after testing without those chainges... turns out collars are just janky
is it good ¯\_(ツ)_/¯

**Comment by kit-katz** [comment]
ight after some back and forth i came up with **this**. simplified PAI var-Icon_state "link"
does it work... yes
is it good ¯\_(ツ)_/¯

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
