### PR TITLE
Bluespace Miner complete removal.

### PR DESCRIPTION
**Pull request by francinum**
No compromise on handling terrible game design.

closes #3336
closes #3329

## About The Pull Request
Completely removes the bluespace miner.

## Why It's Good For The Game
I'll say what I said for the autodoc.

*Shortcutting systems is not going to make things better, it's going to result in that system festering and only **GETTING WORSE**.*

I'll have a companion PR out soon with a solution for the problem.

## Changelog
:cl:
del: Bluespace Miner is gone.
/:cl:

### CODE REVIEW

**Comment by nikk735** [comment]
cringe meter 100

**Comment by Rukofamicom** [comment]
Go the route of requiring anomaly cores or move to cargo for exorbitant prices. 

The true problem with bluespace miners is the fact they are self-replicating and provide an unlimited amount of two very rare resources: Bluespace Crystals and Diamonds.

**Comment by VictorVow** [comment]
> I'll have a companion PR out soon with a solution for the problem.

Then add it into the same PR and don't merge until then. BSMs are not the ideal solution but a complete removal is worse than not having one at all.

**Comment by r1ks-iwnl** [comment]
> Go the route of requiring anomaly cores 

Sounds like a job for #2950, i kept it closed because theres not enough uses for the cores and im too lazy to think of anything.

**Comment by Effemu** [comment]
no

**Comment by ItsTisme** [comment]
we remove BS miners when mining is competent and/or shows slightest care for anything else but gamer loot

**Comment by Effemu** [comment]
> 
> 
> we remove BS miners when mining is competent and/or shows slightest care for anything else but gamer loot


"Removes megafauna loot" [REMOVAL][MERGED]

bee is gonna become another tg 😔

**Comment by bloons3** [comment]
> we remove BS miners when mining is competent and/or shows slightest care for anything else but gamer loot

Why would miners have any pressure to do their job when we have a magic box that shits out infinite resources at regular intervals?

**Comment by Effemu** [comment]
> 
> 
> > we remove BS miners when mining is competent and/or shows slightest care for anything else but gamer loot
> 
> Why would miners have any pressure to do their job when we have a magic box that shits out infinite resources at regular intervals?

why should people be forced to do something not fun while playing 2d spessmen game

**Comment by ivanmixo** [comment]
I got a better idea, make them not allow for use of artificial bluespace crystals

**Comment by Isy232** [comment]
Make a fix then and dont remove it with no replacement.

**Comment by Sinestia** [comment]
Not sure what the companion PR is

but if you buff diamond and bluespace crystal spawn rates slightly along with having the miner's tf2 key PR in

then this probably won't be a problem at all 

Either that or someone can rework and reintroduce them as something more balanced

**Comment by jlsnow301** [comment]
> terrible game design.

So, mining as a whole. Basically this pr will make 3ish departments just not have access to the game. Problem isn’t bs miners...

**Comment by ghost** [comment]
Ignore all of the "IMPROVE DONT REMOVE!!!!!!!!!!!!!!!!" comments and "something bee is gonna become/is becoming X something" that don't actually provide any criticism or a solution to tackle the issue, they should be marked as disruptive content or off-topic anyways.

Overall this is a good chance, if you want materials for your crazy science project then someone has to actually go and get them, I don't understand the argument of "mining is not fun" when it's by far the most overpowered role with loot around every corner, you'll accumulate resources just getting to these loot boxes and then you need mining points for all of the stuff in the vendor.

I'm looking forward to seeing most of these autonomous machines that void entire game mechanics that should otherwise be a player interaction removed, as that is not good game design at all.

It's easy to supply the station with enough materials to last the entire round while also getting all of the loot in a reasonable timeframe, I have no idea where the people that think this isn't possible get their opinion from.

The vote should just be skipped on this one because you already know this wouldn't make it through.

Saying "Beestation is a beginner-friendly server" is not a valid argument, it is in fact an argument against the existence of machines like this, new players want to learn the game, and as such should be taught how to actually do the job, mining is a lot of fun, and new players have always existed and learned mining on every server that is was and will ever be, the bluespace miner is a machine that was made for lazy science mains, and as Bloons pointed out, there is no pressure for people to mine because of this machine.

And finally, we even have an entire z-level that consumes a ton of processing power and is rendered obsolete by a single machine that you can always research and build.

Do you know what happens when you replace everything with machines? People get lazy and dumb, this applies to both videogames and real-life too, the less automation there is the better will people become at the game which in turn fixes the very issue that everyone else is complaining about, which is that Miners are unskilled, just like you people say Beestation is a beginner-friendly server, so go on and teach the new players on how to play the game properly.

**Review by ghost — APPROVED** [review]

**Comment by jlsnow301** [comment]
> that don't actually provide any criticism or a solution to tackle the issue

I have a $200 bounty open

So lemme make this clear, considering I bountied the miners too:

Mining is not going to do their gathering job specifically out of sympathy nor any amounts of bugging them over radio. Removing these will simply mean that we won't have mats and a portion of the game will be unfun (robotics unplayable at low pop). 


The whole existence of bsminers doesn't make any department unfun- more specifically, it does not invalidate mining, who frankly are not out to do such a menial task as shooting rocks. Any changes should address what the bs miners address so that we don't need them, because otherwise we're illustrating how badly designed mining is

**Comment by ghost** [comment]
> Mining is not going to do their gathering job specifically out of sympathy nor any amounts of bugging them over radio. Removing these will simply mean that we won't have mats and a portion of the game will be unfun (robotics unplayable at low pop).

This is not true and playing any other server or having played the game before the bluespace miners were added will quickly disprove your hypothesis.

**Comment by ghost** [comment]
> REEE MY UNLIMITED MAT MACHINE IS GONE

> REEE I HAVE ACTUALLY TO DO MY JOB

> REEE I HAVE TO INTERACT WITH PEOPLE

After all this time, I see why votes are not binding. All I can say is that this should be merged _with_ its replacement, instead of _before_ it.

**Comment by bloons3** [comment]
> So, mining as a whole. Basically this pr will make 3ish departments just not have access to the game. Problem isn’t bs miners...

Good god, how did we ever get by without them before!?!

**Comment by bloons3** [comment]
> REEE I HAVE ACTUALLY TO DO MY JOB

More like

>REEE I HAVE TO REEE AT SOMEONE TO DO THEIR JOB AND ACTUALLY MAKE SURE THAT THEY'RE NOT GOOFING OFF

**Comment by jlsnow301** [comment]
> Good god, how did we ever get by without them before!?!

Whole departments not being able to do their job isn't round ending, else you wouldn't have

**Comment by bloons3** [comment]
> > Good god, how did we ever get by without them before!?!
> 
> Whole departments not being able to do their job isn't round ending, else you wouldn't have

A magic box that dispenses wealth is not the solution to a people problem.
If one person refuses to pick up the pickaxe and mine, then another must or the station will slowly die.

The mining conscription kit exists for a reason. Even the lowliest cargo technician can order it and give access to a new miner, while the HoP is preoccupied in dorms with their choice xenomorph.

**Comment by jlsnow301** [comment]
> The mining conscription kit exists for a reason. Even the lowliest cargo technician can order it and give access to a new miner, while the HoP is preoccupied in dorms

This relies on the assumption that you have those. If you haven't a single living miner, this is unlikely 

BS miners were conceived as a crutch for low pop, not a replacement

**Comment by Effemu** [comment]
"People shouldn't doing job outside of their assigned role"
yet the same people who argued that now say
"go mine yourself if you want materials"

**Comment by ghost** [comment]
> "People shouldn't doing job outside of their assigned role"
> yet the same people who argued that now say
> "go mine yourself if you want materials"

Strawman arguments won't get you anywhere here.

**Comment by Effemu** [comment]
> 
> 
> > "People shouldn't doing job outside of their assigned role"
> > yet the same people who argued that now say
> > "go mine yourself if you want materials"
> 
> Strawman arguments won't get you anywhere here.

[img](https://user-images.githubusercontent.com/71228581/104775748-2d716e80-5779-11eb-8952-8804b8df5545.png)

idk if arguing with someone who thinks clicking at rocks is mentally stimulating and skillful job would make sense
or the person who tries to make 2d spessman game more like real life for that matter
https://www.youtube.com/watch?v=FdxEUL18ySY

**Comment by ghost** [comment]
> https://www.youtube.com/watch?v=FdxEUL18ySY

image

**Comment by ghost** [comment]
> > > "People shouldn't doing job outside of their assigned role"
> > > yet the same people who argued that now say
> > > "go mine yourself if you want materials"
> > 
> > 
> > Strawman arguments won't get you anywhere here.
> 
> [img](https://user-images.githubusercontent.com/71228581/104775748-2d716e80-5779-11eb-8952-8804b8df5545.png)
> 
> idk if arguing with someone who thinks clicking at rocks is mentally stimulating and skillful job would make sense
> or the person who tries to make 2d spessman game more like real life for that matter
> https://www.youtube.com/watch?v=FdxEUL18ySY

Ad hominens won't get you anyhwere here.

**Comment by Effemu** [comment]
> Ad hominens won't get you anyhwere here.

its not really ad hominem because you said it yourself...

You claim there are no other solutions, however there's a lot of other ways to make bluespace miners less effective that were posted on github and discord

for example here's 4 out of many solutions that i like the most:
-make bsm mine rare mats only with top tier parts
-remove or severely nerf ability to create artificial bluespace crystals
-bump power usage of bsm while making them more expensive to build
-make them very expensive cargo only item

**Comment by ghost** [comment]
> > Ad hominens won't get you anyhwere here.
> 
> its not really ad hominem because you said it yourself...
> 
> You claim there are no other solutions, however there's a lot of other ways to make bluespace miners less effective that were posted on github and discord
> 
> for example here's 4 out of many solutions that i like the most:
> -make bsm mine rare mats only with top tier parts
> -remove or severely nerf ability to create artificial bluespace crystals
> -bump power usage of bsm while making them more expensive to build
> -make them very expensive cargo only item

Now was it that hard to provide actual criticism? Next time you should post it in your first comment.

**Comment by dinnerwoerror** [comment]
the techweb RnD revolution and its consequences have been a disaster for the human race

**Comment by triplezeta** [comment]
pog!

good PR

**Comment by Sinmero** [comment]
So no resources for low pop lrp most of the time? Maybe making it available for low pop only is a solution that would satisfy most people.

**Comment by Archanial** [comment]
Don't merge this.

Bluespace miner isn't the best thing in the world but it still give science some things to do. I really enjoy mass building them for no reason, and really, it doesn't change much since materials are not hard to get. Even scientist with access can print tools and gather absurd amount of materials in short time.

The solution to this is making this need anomaly core and porting explosion inhibitor from tg (used to make those cores). 
Not only will it keep fun of building those machines, it would also add a lot of depth to toxins, which right now are just 10 minute maxcap speed run. That would also add more departament to departament cooperation since toxins has relatively limited gas supply and probably cargo if you run out of ttvs. 

I agree bluesspace miner has no place in the current game - it was designed for low pop sage without anyone signing up for mining, but it's not unsaveable I think.

**Comment by Sapfearon** [comment]
Autodoc was good and fun, bluespace miners make ghost spawn ( charlie, golems) playable. Removing BSM is bad idea. Try adding something instead of removing.

**Comment by ghost** [comment]
> Autodoc was good and fun, bluespace miners make ghost spawn ( charlie, golems) playable. 

They were playable before the BSM existed.

>Removing BSM is bad idea. Try adding something instead of removing.

This is not criticism.

**Comment by WindowsErrors** [comment]
it's kinda funny when i play on NSV and even with a fully staffed cargo department there's still some micropenis scientist who makes a room full of like 90 bluespace miners and then they still have the gall to try and call security on me when i sell some of their 17 million credits worth of plasma and diamond

**Comment by nikk735** [comment]
playing miner for getting ores just isnt fun, who actually plays that for fun. you are forcing ppl to do stuff in a video game that's not fun while making every other job less fun because they have no ores at all

**Comment by ghost** [comment]
> playing miner for getting ores just isnt fun,

Subjective opinion.
 >who actually plays that for fun.
 
 Quite a lot of people.
>you are forcing ppl to do stuff in a video game that's not fun
  
  Subjective opinion.
>while making every other job less fun because they have no ores at all

Issue caused by miners having no pressure to mine due to BSM's existence, and I don't understand this point, you can say the same about every other role that exists in the game.

**Comment by WindowsErrors** [comment]
belone, don't blame the person, blame the system

i think at this rate, with the way people are reacting, you would be better off renaming the "shaft miner" role to "dragon hunter" instead of doing this whole removal circus

**Comment by ghost** [comment]
> belone, don't blame the person, blame the system
> 
> i think at this rate, with the way people are reacting, you would be better off renaming the "shaft miner" role to "dragon hunter" instead of doing this whole removal circus

But it's extremely amusing to see people trying to use the same 4 arguments for the 10th time.

**Comment by WindowsErrors** [comment]
of all clown shows i could have returned to, it's this one

**Comment by theboy6545** [comment]
> it's kinda funny when i play on NSV and even with a fully staffed cargo department there's still some micropenis scientist who makes a room full of like 90 bluespace miners and then they still have the gall to try and call security on me when i sell some of their 17 million credits worth of plasma and diamond

NSV doesn't do upstream pulls anymore, so this PR would have to be manually ported.

**Comment by nikk735** [comment]
> > playing miner for getting ores just isnt fun,
> 
> Subjective opinion.
> 
> > who actually plays that for fun.
> 
> Quite a lot of people.
> 
> > you are forcing ppl to do stuff in a video game that's not fun
> 
> Subjective opinion.
> 
> > while making every other job less fun because they have no ores at all
> 
> Issue caused by miners having no pressure to mine due to BSM's existence, and I don't understand this point, you can say the same about every other role that exists in the game.

ok put it to vote then see who enjoys clicking on rocks for 40 min to supply everyone with ores

**Comment by triplezeta** [comment]
democracy moment

**Comment by ghost** [comment]
> ok put it to vote then see who enjoys clicking on rocks for 40 min to supply everyone with ores

You can do both at the same time - mine AND go hunt for loot.

**Comment by SynnGraffkin** [comment]
I dunno what changes to BSMs have there been since I ported them, but WS has done some levels of nerfs to the machine. 

[Requiring tiered parts for better materials](https://github.com/WaspStation/WaspStation-1.0/pull/345)
[Requiring powered nodes to work](https://github.com/WaspStation/WaspStation-1.0/pull/346)
[Further part tweak and material requirment](https://github.com/WaspStation/WaspStation-1.0/pull/562)

@BeloneX Not really saying you should keep BSMs, since I don't play on Bee, but giving ya'll potential solutions should they be kept in.

**Comment by Sinestia** [comment]
> I dunno what changes to BSMs have there been since I ported them, but WS has done some levels of nerfs to the machine.
> 
> [Requiring tiered parts for better materials](https://github.com/WaspStation/WaspStation-1.0/pull/345)
> [Requiring powered nodes to work](https://github.com/WaspStation/WaspStation-1.0/pull/346)
> [Further part tweak and material requirment](https://github.com/WaspStation/WaspStation-1.0/pull/562)
> 
> @BeloneX Not really saying you should keep BSMs, since I don't play on Bee, but giving ya'll potential solutions should they be kept in.

These are nice, might have done it a bit differently myself but yeah

I don't hate BSMs as a concept but they should have appreciable costs

**Comment by Effemu** [comment]
> I don't hate BSMs as a concept but they should have appreciable costs

That's what majority of us are saying, but belone (like most coders who dont take into account playerbase opinions) lives in his own little world where only criticism he makes matters 😄

**Comment by ghost** [comment]
> That's what the majority of us are saying, but belone (like most coders who don't take into account player base opinions) lives in his own little world where the only criticism he makes matters 😄

"Infinite resources" is a bad niche for a machine, and if you can't comment PRs without resorting to insults, don't bother commenting, you'll just be ignored.

And I'll gladly listen to criticism as long as it isn't:

"Annoyed, overboard rebuttal to post. Swearing and suggesting that the person who made this post is bad for a variety of reasons. Fair point that is undermined by the sheer amount of profanity in the answer."

**Comment by Effemu** [comment]
> 
> 
> > That's what the majority of us are saying, but belone (like most coders who don't take into account player base opinions) lives in his own little world where the only criticism he makes matters 😄
> 
> "Infinite resources" is a bad niche for a machine, and if you can't comment PRs without resorting to insults, don't bother commenting, you'll just be ignored.
> 
> And I'll gladly listen to criticism as long as it isn't:
> 
> "Annoyed, overboard rebuttal to post. Swearing and suggesting that the person who made this post is bad for a variety of reasons. Fair point that is undermined by the sheer amount of profanity in the answer."


please mention what are those insults i keep using... 🙃

**Comment by francinum** [comment]
> I dunno what changes to BSMs have there been since I ported them, but WS has done some levels of nerfs to the machine.
> 
> [Requiring tiered parts for better materials](https://github.com/WaspStation/WaspStation-1.0/pull/345)
> [Requiring powered nodes to work](https://github.com/WaspStation/WaspStation-1.0/pull/346)
> [Further part tweak and material requirment](https://github.com/WaspStation/WaspStation-1.0/pull/562)
> 
> @BeloneX Not really saying you should keep BSMs, since I don't play on Bee, but giving ya'll potential solutions should they be kept in.

I personally don't believe any of these nerfs solve the core problem here.

A flow of materials is not inherently necessary for game flow, thus there is no need for a magic box to assure that said material flow always exists.

If nobody wants to mine, that's the station's problem to solve. I've heard only vague justifications to why mining should not be expected to perform their job, including but not limited to:
* Mining is incredibly boring
* It takes so long
* Nobody plays miner
* Miners don't want to mine.

**Comment by jlsnow301** [comment]
> A flow of materials is not inherently necessary for game flow

Robotics cannot build bots, science cannot upgrade, engineering cannot build machines, medbay cannot print tools. I believe a more accurate term here would be round flow, because it surely restricts part of the game

**Comment by jlsnow301** [comment]
It probably would completely nullify bs miners if we locked their tools behind points rather than research and lathes, but it wouldn't completely resolve the fact we're relying on the output of a side job to the most combat intensive role in the game on a server for new players

**Comment by francinum** [comment]
> > A flow of materials is not inherently necessary for game flow
> 
> Robotics cannot build bots, science cannot upgrade, engineering cannot build machines, medbay cannot print tools. I believe a more accurate term here would be round flow, because it surely restricts part of the game

Let's assess this in order then.

> Robotics cannot build bots

You can order glass and metal cargopacks.
> science cannot upgrade

Science is not inherently necessary for game flow.
> engineering cannot build machines

You can order glass and metal cargopacks.
> medbay cannot print tools

I assume you mean replacement tools, as upgraded tools are once again not an inherent necessity
For those, you can order glass and metal cargopacks.

Game and round flow are no different, for the flow of the game is the flow of the round.

**Comment by WindowsErrors** [comment]
a good thing to keep in mind about item design is that cargo does not count as a reliable source of anything on any round

**Comment by francinum** [comment]
> a good thing to keep in mind about item design is that cargo does not count as a reliable source of anything on any round

Far more reliable than the mining that is apparently completely dead at the moment.

**Comment by ghost** [comment]
Miners will mine if the bluespace miners are gone though. If it works on every other server, it'll work here.

**Comment by Unidentified-Biohazard** [comment]
the problem I have with this PR is if miners don't wanna mine/ there are no miners the station is screwed for resources. There are still resource shortages fairly consistently even with BSM, removing that will only confound the problem. There either needs to be another way to gain resources (at least basic ones like glass and iron) for basic repairs and builds. That's why I like the trash beacon from Eris, it has a direct route to the recycler for the stuff you don't want and can spawn some nice stuff which encourages assistants (vagabonds) to use it (for those who don't know what the trash beacon is it grabs several piles of random space garbage which can be slowly dug through to find loot/trash/mats. there is a conveyer to disposals right next to it as well so the mats can be recycled from the trash they don't want). You mentioned a PR to address this issue but until it is coded and the specifics of everything is known I can't stomach this PR one bit.

**Comment by ghost** [comment]
> the problem I have with this PR is if miners don't wanna mine/ there are no miners the station is screwed for resources. 

If the Engineers don't set up the engine there will be no power.

**Comment by Unidentified-Biohazard** [comment]
> > the problem I have with this PR is if miners don't wanna mine/ there are no miners the station is screwed for resources.
> 
> If the Engineers don't set up the engine there will be no power.

thing is, setting up power can take less than 5 minutes, there are almost always engis online (or at least people with engine knowledge) and often there are no miners at all, and mining is a constant activity as the station always needs more mats. so super quick one off thing in a high occupancy job that gives incentives to complete it vs a low occupancy job with a job that needs to be done constantly with little to no incentive to do so. In other words: logical fallacy.

**Comment by Unidentified-Biohazard** [comment]
so until miners are given actual incentives to mine prepare for constant lack of resources.

**Comment by bloons3** [comment]
> > the problem I have with this PR is if miners don't wanna mine/ there are no miners the station is screwed for resources.
> 
> If the Engineers don't set up the engine there will be no power.

A better comparison is medical.

The station starts with a certain amount of materials. Every department has a little bit of loose iron, glass, and some other materials around.

The station also starts with a limited number of medkits which can heal very basic damage.

If there are no miners, the materials on the station will be used up and not replaced.

If there are no chemists, no new medicines will be made. If there are no doctors, no one will perform surgery, man the sleepers, or do other essential tasks.

That is, unless someone else in the round steps up to fill the vacant position.

**Comment by ItsTisme** [comment]
>If there are no chemists, no new medicines will be made. If there are no doctors, no one will perform surgery, man the sleepers, or do other essential tasks.

Thing is people will just tide medical, they already do constantly which is annoying as a MD but also kinda makes the whole job moot. BS miners exist so that you dont have to force another player to mine or do it yourself instead of doing stuff you want. Might aswell get yourself AA and do every job on the station otherwise

**Comment by ItsTisme** [comment]
> Miners will mine if the bluespace miners are gone though. If it works on every other server, it'll work here.

this is bee, alot of shit cant happen here that would work well on other servers because its bee

**Comment by Sinmero** [comment]
>If the Engineers don't set up the engine there will be no power.

>A better comparison is medical.
The station starts with a certain amount of materials. Every department has a little bit of loose iron, glass, and some other materials around.
The station also starts with a limited number of medkits which can heal very basic damage.

I dont agree. 
If there are no engineers and noone can setup sm (which takes ~5 min) people always can setup turbine or go eva and wire solars or just use pacman or botany can make potato cells or xenobio can make charged extracts.

Medbay resources are overabundant. Medical storage, med vendors, vendors at patient rooms, if its all gone there is botany with  its earthblood or pretty much any other robust healing chem. You can clone people with pod seeds at botany too. Also robotists can make medibots.

Without bp miners there is no decent alternative to mining.
Mining feels more like a singleplayer pve game with online chat. There are nearly no people to interact with. Mining itself is monotone and gets old very quick. The main attraction of mining is exploring, boss fights and loot. If i feel like fighting bosses or hunting for loot i play miner if not then i dont. I wouldnt count on non miners going to lavaland to mine if they wanted to do other jobs in the first place.

I believe i said that before - you can lock bp miners behind pop limit.

**Comment by AtlasRules** [comment]
if this DOES get merged, please god do not port it to NSV

i can count the rounds that i've gone without resources as engineer/scientist on NSV, and i need a way of getting bluespace and diamond that isn't:
- going mining myself
- waiting for an actual semi competent player to go mining
- crying and shitting and pissing

**Comment by Jalleo** [comment]
@AtlasRules Honestly thats a issue which states that outside of mining there isn't ways to create materials. Slimes or cargo should be able to order them. Bluespace miners are a crutch design that is actually bad for player mentality. 

If materials cannot be ordered from cargo and miners are proven to not be reliable then cargo brings a material cost to ordering them. Slimes would take time to make and not be reliable. I am saying this as a NSV maintainer. I hate the idea of bluespace miners and realized how bad they were when I first saw them. SS13 is a multiplayer game it has to work by using multiple people to get things done. If a machine entirely moots a persons job why should that happen. Mining there does need more work but that is a better point to raise there not here.

**Pull request closed without merging**
