### PR TITLE
broken chameleon kit is purchasable to all agents

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
Removes antag role restriction from Broken chameleon kit at the uplink

## Why It's Good For The Game
actual nukies and clown ops would never use it, and 4 TC is too much for that gimmick.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
tweak: Broken Chameleon kit is available to all types of syndicate agents. traitors and incursionists can buy the kit.
balance: Broken Chameleon kit now costs 2 TC.
/:cl:

### CODE REVIEW

**Review by Archanial — APPROVED** [review]

**Comment by FriendlyContractor** [comment]
Bad idea. This item is purely cosmetic and encourages players to ruin the round by willingly revealing their secret traitor role.

**Comment by EvilDragonfiend** [comment]
> Bad idea. This item is purely cosmetic and encourages players to ruin the round by willingly revealing their secret traitor role.

What's different with the syndi balloon or ancient assistant outfit?

**Comment by FriendlyContractor** [comment]
> What's different with the syndi balloon or ancient assistant outfit?

Hardly anything - would happily yeet them out of the game

**Comment by EvilDragonfiend** [comment]
> > What's different with the syndi balloon or ancient assistant outfit?
> 
> Hardly anything - would happily yeet them out of the game

if they want to yeet, they would try something else, not broken chameleon kit items. also, it is effective to attract security's interests in practical.

**Comment by DerpiestBruh** [comment]
> encourages players to ruin the round by willingly revealing their secret traitor role.

how

**Comment by EvilDragonfiend** [comment]
> secret traitor role

And it isn't that secret, actually.

**Comment by PowerfulBacon** [comment]
Can't you obtain these from space ruins anyway?

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
