### PR TITLE
[PORT] tgui: Communications Console

### PR DESCRIPTION
**Pull request by KubeRoot**
## About The Pull Request

Ports the following PRs:
- https://github.com/tgstation/tgstation/pull/54220
- https://github.com/tgstation/tgstation/pull/54381
- https://github.com/tgstation/tgstation/pull/55524
  - We already had this feature pre-tgui, this is a nicer implementation
- Implements **an alternative for** https://github.com/tgstation/tgstation/pull/56135
  - I didn't like the way the original was implemented - it used `Object.entries` instead of `.map` which converts the indices into strings... because that's what object entries use. Instead of converting the string back to an int again, I just refactored it to use `.map`.

Also implements a few small fixes to the code, including running it through our tgui linters and appeasing them.

After further discussion, the interface has been reworked into a horizontal format - see screenshots in the collapsible section below.

**NOTE:** Might want to testmerge, I particularly couldn't test crossserver communication locally beyond making sure the UI reacts correctly.

<details>

<summary>Screenshots</summary>

image

### Logged in as non-captain:
image

### Logged in as captain:
image

### Shuttle purchase screen after a shuttle has been bought:
image

### Silicon view:

image

</details>

## Why It's Good For The Game

TGUI is nice, and the old code was janky and full of holes. Instead of fixing it, why not kill two birds with one stone?

## Changelog
:cl: KubeRoot, Mothblocks
add: The communications console now uses tgui
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
Why does the communications console need a TGUI menu when it has no updating elements?

**Comment by KubeRoot** [comment]
> Why does the communications console need a TGUI menu when it has no updating elements?

Technically, it does have at least one updating element, but... That's not what TGUI is all about, is it now? It's about separating out the interfaces into separate files so they're not awkwardly jammed in with the rest of the code, it's about making the interfaces look nice and consistent, it's about interfaces reacting well to user input, it's about abstracting away the communication so you don't have to send browsers to the user and serialize lists yourself.

Also, the communications console in its current state is, as I mentioned, *full of holes*, and I'd rather get it up to date with tg making it tgui rather than patch it up and leave this for later.

**Comment by francinum** [comment]
Holy shit this is ugly

**Comment by KubeRoot** [comment]
> Holy shit this is ugly

I have to disagree, the only ugly thing I see here are the modal windows... But those are indeed ugly, and I could try to stylize them a bit and center them. That said, otherwise I don't see an issue, as far as I'm concerned it looks better than the existing console.

**Comment by Crossedfall** [comment]
I would much prefer wide over long for these windows, other than that I think it looks alright.

The thin approach makes it look like you're viewing a phone, not a console.

**Comment by KubeRoot** [comment]
> I would much prefer wide over long for these windows, other than that I think it looks alright.
> 
> The thin approach makes it look like you're viewing a phone, not a console.

I can try to rework it a bit to be wide if you'd like, but from experience it can be problematic with TGUI. Specifically, if you divide the screen into two panels horizontally, and then want to have in one panel something that stretches to the width of the panel, like the action buttons, you might run into issues where things stop behaving reasonably and the button stretches offscreen, taking the panel with it.

I reckon there's a proper solution to this, but I'm no HTML/CSS expert so all I can do is try it and hope it doesn't fall apart.

**Comment by KubeRoot** [comment]
Here are some screenshots of an alternative layout as suggested by Crossedfall:

<details>

<summary>Screenshots</summary>

image

Logged in as non-captain:
image

Logged in as captain:
image

Shuttle purchase screen after a shuttle has been bought:
image

</details>

**Comment by KubeRoot** [comment]
Got (preemptive) approval for the layout change - the code isn't cleaned up properly, linters are failing because of that. Will need to clean the code up before this is ready, but it's available for viewing now.

**Review by ike709 — APPROVED** [review]
Let me know when you've tested it.

**Pull request merged**
