### PR TITLE
Goodbye nanites

### PR DESCRIPTION
**Pull request by JixS4v**
## About The Pull Request

Kills nanites from the techweb and from maps. They'll still be in code since I want to reimplement the cooler programs as bundles for traitors, without cloudsync (nanomachines, son).

## Why It's Good For The Game

Nanites suffer from the same issues as virology. They require a good while to get set up, have almost no downsides to having them, and give crew a passive buff which results in powercreep. Maybe TG's design decisions weren't so bad after all.

## TODO

- [x] EchoStation
- [x] RadStation
- [x] MetaStation
- [x] DeltaStation
- [x] KiloStation
- [x] BoxStation
- [x] Corgstation
- [x] Flandstation
- [x] Kill from techweb

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

MDB has pictures of the mapping changes, and the techweb stuff can't be really tested.

</details>

## Changelog
:cl: Ratón, Jix
del: Nanites are no longer available to science
del: Nanite room
/:cl:

### CODE REVIEW

**Comment by DarnTheMarn** [comment]
🚨🚨 Based Alert 🚨🚨
My biggest gripe with nanites is the passive healing you get, and with all the changes to medbay that have come or are coming nanites were bound to get tapped at one point. It will be sad to lose the other somewhat neat programs but a lot of those were gimmicky at best.

**Comment by williamcll** [comment]
Horrible idea, nanites are one of the few things that stops med incompetence

**Comment by JixS4v** [comment]
Did the minimal work to make it not available from the techweb without pulling it from admins, since nanites can do some pretty cool adminbus honestly.

**Comment by williamcll** [comment]
> > Horrible idea, nanites are one of the few things that stops med incompetence
> 
> Med is already piss easy, it shouldn't be made obsolete by essentially passive autoheals.

Med is already being nerfed towards bay med as we speak

**Comment by JixS4v** [comment]
> > > Horrible idea, nanites are one of the few things that stops med incompetence
> > 
> > 
> > Med is already piss easy, it shouldn't be made obsolete by essentially passive autoheals.
> 
> Med is already being nerfed towards bay med as we speak

Good? I don't understand what your point is. Systems shouldn't be bypassed.

**Comment by Fronsis** [comment]
The Box hallway looks quite.. empty, you could add a firesafety closet or leave a vendor for the maintenance dwellers that pass by

That Delta mini break-room is missing a camera and could use the airlock to have windows seems more approachable that way also the floor-passage is missing light and floortiles, given it's part of sci they should have them

Rest looks good from what i saw

**Comment by EvilDragonfiend** [comment]
🔑 
I believe we are not yet ready for the removal of nanites because our codebase doesn't have much contents to cover the empty area of removed contents.
Although I agree nanites are powerful. It should be toned down instead.

**Comment by Rukofamicom** [comment]
🔑 

With dragon, nanites aren't exactly in a well balanced spot right now but I don't want to see them removed or made antag-only. 

Unlike viro in medbay, science does not have plenty of other meat to the department right now. Nanites also aren't nearly as isolated by design and are an easier system to integrate into healthy gameplay. There's definitely room for improvements and not all of them take a whole lot of work to do.

**Comment by PowerfulBacon** [comment]
I agree, I am against another big removal for the sake of a removal since players aren'g going to like it. I don't think nanites are nearly as bad as virology since they are at least fun for people to use. I think that if any removals are going to be done to nanites, they need to be targeted at specific programs with a preference for balancing changes.

**Comment by PowerfulBacon** [comment]
I'm in complete agreeance with the other posts and I don't want a contraversy about removing something without strong reasons to do so or an alternative on the way.

**Pull request closed without merging**
