### PR TITLE
Modular fabricator interface for exosuit fabs.

### LINKED ISSUE #4212: Cyborg modules don't install correctly
(Creating on the behalf of a player)

## Reproduction:

1.  Have a cyborg with a mining chassis
2. Spawn/print standard mining upgrades (e.g. lavaproof tracks or the drill)
3. Attempt to insert the module into the cyborg

**Expected:** The module gets installed and the cyborgs is upgraded
**Actual:** The module gets rejected and the player is unable to upgrade the cyborg

### PR DESCRIPTION
**Pull request by PowerfulBacon**
closes https://github.com/BeeStation/BeeStation-Hornet/pull/4209
closes https://github.com/BeeStation/BeeStation-Hornet/pull/4208
resolves #4212 

## About The Pull Request

Updates the exosuit fabricator UI to use the modular fabricator system.

image

Adds in an add category and research sync button as optional components to the interface.

image

Adds a base type for modular fabricators so other things can be moved other easier.

## Why It's Good For The Game

Looks nicer than HTML, less laggy than before

## Changelog
:cl:
add: Modular fabricator interface for exosuit fabs.
code: Removed the build queue from the mod fab interface code.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I kind of want to make that queue on the right extend the whole way but TGUI is painful and thinking about editing a TGUI interface makes me want to cry

**Comment by bloons3** [comment]
FYI, if you don't add the borg flags this will break adding modules.

**Comment by PowerfulBacon** [comment]
This doesn't remove them, its based on the current beecode not the reverted one where its broke

**Review by ike709 — DISMISSED** [review]

**Comment by ike709** [comment]
Actually why does this have map diffs?

**Comment by jupyterkat** [comment]
repathed fabricators, ew

**Comment by PowerfulBacon** [comment]
> 
> 
> Actually why does this have map diffs?

Repathed autolathes and exosuit fabs to be under the same fabricator base object, since they both do essentially the same thing with changes to what can be printed and some things with their function.

obj/machinery/autolathe -> obj/machinery/fabricator/autolathe
obj/machinery/mechfab -> obj/machinery/fabricator/exosuit_fabricator

**Comment by ike709** [comment]
mkay

**Comment by PowerfulBacon** [comment]
Fixed ore silo bug, never updated testmerge though so hoping it auto updates or something

**Comment by ike709** [comment]
Been testmerged for a while, people can cope if they cba to report bugs.

**Pull request merged**
