### PR TITLE
Buff heretic blade

### PR DESCRIPTION
**Pull request by yyzsong**
Buffs heretic blade from 17 to 24

## About The Pull Request
Changes heretic blade damage from 17 to 24

## Why It's Good For The Game
Heretic is an underpowered antag. This helps (not by much) (Plus I'm trying to learn to code)
Did you know that the heretic blade that you _need to make yourself_ does about half the damage of the literally free cult blade?

## Changelog
:cl:
balance: The heretic blade now does 24 damage instead of just 17
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
30 damage...

**Comment by VictorVow** [comment]
Cult sword is huge and can't be put in a backpack, whereas heretic blade can. Even fire axe (24) damage would be too much, so maybe like 20 damage instead.

**Comment by Sinmero** [comment]
30 is way too much. give it a chance to dismember instead

**Comment by FriendlyContractor** [comment]
Good quality of life change to help with validhunters. Considering how every security officer has a 35 damage RANGED disabler and 75 damage stun baton i disagree with Victor and Sinmero. Its still waaaaaay too little to give them a fair fighting chance against security

**Comment by VictorVow** [comment]
Edit: retracted

**Comment by yyzsong** [comment]
> Cult sword is huge and can't be put in a backpack, whereas heretic blade can. Even fire axe (24) damage would be too much, so maybe like 20 damage instead.

Cult swords can be stored in spell form and called up at any moment

**Comment by VictorVow** [comment]
After playing this some more I partially retract my statement, 24-25 damage would be fine since you can't hide it as easily as a cult dagger and the dagger can be sharpened multiple times to even higher damage. 

Also since you can break the blade to teleport it has more cost/benefit analysis to whether you want to use it to escape or continue fighting.

**Comment by ivanmixo** [comment]
You underestimate just how insane 30 damage is

**Comment by r1ks-iwnl** [comment]
The heretic blade has a bunch of on hit effects that deal even more damage to your targets so 30 brute combined with those effects is extremely powerful

**Comment by Cenrus** [comment]
Change to 25 damage. I know heretics are limited in combat options, but 30 is a bit over the top.

**Comment by yyzsong** [comment]
Brought down to 24 because even numbers

**Comment by utilbird** [comment]
update PR desc and CL

**Comment by yyzsong** [comment]
Updated

**Comment by PowerfulBacon** [comment]
24 is fine, its not a super OP weapon but definitely good range in whats available to non antags and about mid range for whats available to antags, plus heretics aren't *too* effective in combat right now and are usually better off just asking for their targets to be sacced and then cloning them after.

**Comment by TeomanTheGreat** [comment]
The sprite for the blade is pretty big so this makes sense

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
