### PR TITLE
[PORT] Vending machine costs

### PR DESCRIPTION
**Pull request by bloons3**
## About The Pull Request
- Ports some parts of https://github.com/tgstation/tgstation/pull/48856
- makes insulated gloves expensive in vending machines
- makes multitools more expensive from vending machines
## Why It's Good For The Game

Free insulated gloves in a static location means that the first person to rush item at the start of the round gets a very limited and expensive item.
Along these lines, multitools and insulated gloves are both extremely inexpensive from vending machines. Giving away tiding tools for essentially free doesn't encourage players to interact with each other, and makes any attempt at an economy laughable.

This PR is a draft until review requested

## Changelog
:cl:
balance: Tool storage multitools removed, two added to the youtool premium section at 450cr each.
balance: Insulated gloves in vending machines have a price scaled by command paycheck
/:cl:

### CODE REVIEW

**Comment by bloons3** [comment]
Insulated gloves removed from common and low security areas ^

**Comment by bloons3** [comment]
Note that this doesn't touch multitool crafting from lathes. Cargo can buy insulated gloves at 1600, which when refunding the crate at 700 credits is 900 for 3, or 300 each.

**Comment by PowerfulBacon** [comment]
Damn someone doesnt like insulated gloves, may as well get their price to INFINITY.
Should be noted that insuls are required to do anything with the power net, like fixing wires and that if you want to tide insuls are not required at all

**Comment by PowerfulBacon** [comment]
Also assistants cannot afford them at all due to the massive paychecks imbalance.
Also removing multitool from too storage, what?
Also if you want a better attempt at an economy, make the paychecks amounts closer together, at the moment all jobs apart from assistant get basically infinite money, while assistants cannot afford food.

**Comment by ivanmixo** [comment]
So this basically makes insuls only available to heads of staff roundstart from the vedors. Amazing. This just encourages tiding and nothing else if we're being realistic.

**Comment by bloons3** [comment]
> So this basically makes insuls only available to heads of staff roundstart from the vedors. Amazing. This just encourages tiding and nothing else if we're being realistic.

Beg or borrow a budget card from your Head of Department, or run a few crates for cargo.

Gloves cost 80 credits currently, and multitools cost 20 credits. Both are effectively free and enable no-effort greytiding.

**Comment by ivanmixo** [comment]
> > So this basically makes insuls only available to heads of staff roundstart from the vedors. Amazing. This just encourages tiding and nothing else if we're being realistic.
> 
> Beg or borrow a budget card from your Head of Department, or run a few crates for cargo.
> 
> Gloves cost 80 credits currently, and multitools cost 20 credits. Both are effectively free and enable no-effort greytiding.

I doubt people will do any of that, they'll just tide slightly deeper into engi now and now it won't just be assistants in the insuls race.

**Comment by PowerfulBacon** [comment]
Assistants start with about 20 credits, 80 credits is the whole shift

**Comment by bloons3** [comment]
> Also removing multitool from too storage, what?

Got carried away with Ctrl-F

The goal is to remove multitools from public areas, and to replace public area/tiding target area insulated gloves with cheap insulated gloves

**Comment by ghost** [comment]
Removing multitools from public areas is futile when there's 2 public autolathes.

**Comment by PowerfulBacon** [comment]
Also you can get temporary insuls for basically nothing in every drink vending machine.

**Comment by bloons3** [comment]
> Removing multitools from public areas is futile when there's 2 public autolathes.

Public autolathes require that you interact with the department workers to obtain access to it or materials.

Multitools were also added to YouTool's _because_ public autolathes were added.

**Comment by PowerfulBacon** [comment]
🔑

**Comment by mudzbe** [comment]
excellent timing on my part, pats on the back all around #3710

> > Removing multitools from public areas is futile when there's 2 public autolathes.
> 
> Public autolathes require that you interact with the department workers to obtain access to it or materials.
> 
> Multitools were also added to YouTool's _because_ public autolathes were added.

**Comment by ike709** [comment]
🔑

**Pull request closed without merging**
