### PR TITLE
Xenomorphs Stop Gasping due to atmospheric conditions

### LINKED ISSUE #5826: Xenomorphs gasp for air
## Round ID:
34137

## Reproduction:

Quite an old bug that I'm reporting. Xenomorphs will randomly gasp at any stage of life from chest burster to queen. This can be either just immersion breaking, or life-threatening as it can expose your existence in the pipes, or when hiding under a table.

### PR DESCRIPTION
**Pull request by DatBoiTim**
## About The Pull Request
Fixes Xenomorphs, which don't exactly breathe air, from gasping in low oxy or vacuumed environments.

Good for mobs who can make use of breathing some specific gases, but do not need to breathe to survive(IE: Xenomorphs).

## Why It's Good For The Game
closes #5826 
Xenos no longer gasp despite not needing O2 or otherwise. Still allows xenos to breathe plasma. No more being outed during ventcrawls or other situations where you may be in low O2 or vacuumed environments.

## Testing Procedure

1. Ghost yourself roundstart
2. ensure you have xenomorphs enabled in preferences
3. trigger-event
4. select alien infestion
5. click yes on the ghost role prompt
6. once spawned, ventcrawl into atmos
7. navigate towards the mixing output pipenet(the blank grey pipes)
8. Vibe for a few minutes
9. No Gasp? Working properly.

## TODO

- [x] What Ike Said

## Changelog
:cl: DatBoiTim
fix: Xenomorphs no longer gasp in low oxy/vaccuumed environments
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
I don't know man, the Xenomorphs in the Alien movies constantly gasp and drool all over the place.

**Comment by DatBoiTim** [comment]
> I don't know man, the Xenomorphs in the Alien movies constantly gasp and drool all over the place.

This does not stop drooling. Also this doesn't stop voluntary gasping. Mostly allows xenomorphs to be sneaky, as they can be sneaky and clearly do have control over it to a degree in the movies.

**Review by ike709 — CHANGES_REQUESTED** [review]
This is probably the result of the lungs refactor that came with auxmos. Their lung organs probably just need to be tweaked.

This probably isn't the correct fix.

**Comment by DatBoiTim** [comment]
> This is probably the result of the lungs refactor that came with auxmos. Their lung organs probably just need to be tweaked.
> 
> 
> 
> This probably isn't the correct fix.

TIL

I'll look into that. Would be helpful if you linked the PR that possibly did this.

**Comment by DatBoiTim** [comment]
> This is probably the result of the lungs refactor that came with auxmos. Their lung organs probably just need to be tweaked.
> 
> This probably isn't the correct fix.

Xenomorphs do not have lungs. I cannot fix something that doesn't exist.

**Comment by ike709** [comment]
Okay I looked into cursed mobcode.
What you need to do is:
1. Give the `alien` mob a `breathe()` override that doesn't call parent. 
2. Do the logic to get a breath datum like parent `breathe()` does
3. Call `check_breath()` like `breathe()` does.

No define needed.

**Comment by DatBoiTim** [comment]
> Okay I looked into cursed mobcode. What you need to do is:
> 
> 1. Give the `alien` mob a `breathe()` override that doesn't call parent.
> 2. Do the logic to get a breath datum like parent `breathe()` does
> 3. Call `check_breath()` like `breathe()` does.
> 
> No define needed.

👍

**Comment by DatBoiTim** [comment]
I did as suggested.

**Pull request merged**
