### PR TITLE
Borg Versatility Changes

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Quite a lot of changes that I think will make borg players more versatile

**add: health analyzer module for Security module**
You are able to see the health of humans with your advanced robo hud already. Health analyzer is just the logical next step that allows Security to be a little bit more useful outside combat.

**add: health analyzer and crowbar for Peacekeeper module**
The same as Security, it just adds a little bit more useful. Crowbar prevents it from getting stuck when the station is out of power, as well as aid stuck humans and deal with smaller pests if there's the case. 

**add: robo roller module to standard module**
With the addition of health analyzer to other module, standard is not as standard in medical. Well, not anymore. With the rollerbed module, you no longer need to drag bleeding corpses to medical. Let's face it, mediborgs generally stay around medical, while standards are the ones roaming the station/maints and finding corpses.

**del: cookie synthesizer removed from service**
This should be signature to peacekeeper. Rendered obsolete by Behind The Counter fabricator.

**del: razor removed from service**
This module was not working properly and was generally obsolete.

**del: universal enzyme bottle from service**
Borg shaker synthesizing enzyme renders this module obsolete.

**add: hatchet, cultivator, plant analyzer and portable seed extractor to service**
It's frustrating that service borg cannot tend the garden or interact with it in any meaningful way. This is a very important part of service and helps other service departments in some way or another. 

**add: brand NEW module, versatile service grasper, able to pick up seeds and food items**
VSG can pick up any food items, seeds, drinking glasses and carry around donut boxes, egg cartons and cigarette packs. A great module that allows Service to exceed at its job, the same way Engineer, Medical and Janitor exceed at theirs. 

**add: Behind The Counter Fabricator: service upgrade module capable of synthesizing raw food items**
Service had no upgrades. The BTCF allows you to aid the chef and make food a little bit faster. Not a standard module, because this shit makes the Service super amazing at its job.

**add: Ambidextrous upgrade: equipts service borgs with a SECOND separate versatile service grasper**
It makes sense that the service borg resembles somewhat a humanoid creature, with two working graspers. It cannot pick up meaningful items, but it is still very useful and increases Service's usability.

## Why It's Good For The Game

Gives a few boosts to the lesser used/shittier borg modules so that they can do their jobs better.

## Changelog
:cl:
add: health analyzer module for Security module
add: health analyzer and crowbar for Peacekeeper module
add: robo roller module to standard module

del: cookie synthesizer, razor removed, universal enzyme bottle from service
add: atmosphere analyzers to all cyborgs
add: borg shaker can now synthesize its own universal enzyme, and recharges faster
add: plant analyzer module to service
add: service beaker holder now able to pick up seeds and food items
add: Botany Service Upgrade: equipts service borgs with hatchet, cultivater and seed extractor module
add: Cooking Service Upgrade:  equipts service borgs with kitchen knife, rolling pin to service
add: Casino Service Upgrade: equipts service borgs with card, roulette and a dice cup
/:cl:

### CODE REVIEW

**Comment by eeSPee** [comment]
Change: All blade modules (knife, hatchet, rollerpin) now have the force of 20 for cyborgs, but fail to attack living creatures unless the user is emagged.

**Comment by eeSPee** [comment]
Fixed the BTCF text/prices. 

Added sound to service's blade modules. Good idea? Annoying?

**Comment by Mick1299** [comment]
Hang on, fucking WHAT was that last thing? You're giving emagged borgs a 20 force weapon?

**Comment by Mick1299** [comment]
Also, another minor gripe. I think giving service borgs botany tools by default would over clutter the service Borg modules a little. What if you rolled them Into a modular upgrade? Then service borgs could get the upgrade of they want to garden alongside botany

**Comment by eeSPee** [comment]
> Hang on, fucking WHAT was that last thing? You're giving emagged borgs a 20 force weapon?

Standard borg has a 30 force eblade, no?

> Also, another minor gripe. I think giving service borgs botany tools by default would over clutter the service Borg modules a little. What if you rolled them Into a modular upgrade? Then service borgs could get the upgrade of they want to garden alongside botany

Good idea. I will wait for more feedback, but I think this is the direction that it will take

**Comment by zeskorion** [comment]
>more silicon buffs

Silicon mains have it good enough as is

**Comment by eeSPee** [comment]
> > more silicon buffs
> 
> Silicon mains have it good enough as is

I don't see how adding health analyzer is a buff.

And service is literally useless.

**Comment by Isy232** [comment]
I think these changes are quite good

**Comment by eeSPee** [comment]
I guess @zeskorion has a point. It would be unfair for service to be a jack-of-all-trades able to run all service departments on its own.
I split it into three upgrades now:
Cooking, that adds knife, roller and food synthesizer
Botany, with seed extractor and whatever
Gamblind, that has cards, dice cup and a roulette

**Comment by eeSPee** [comment]
I have an idea.
Close this request.

I will make separate requests treating each issue:
* basic borgs
* service modules
* service speciality modules

**Pull request closed without merging**
