### PR TITLE
So that should fix that plane_master_controller harddel 

### PR DESCRIPTION
**Pull request by Dejaku51**
## About The Pull Request
Port of https://github.com/tgstation/tgstation/pull/61562

this should fix it but not yet sure so go TM it

image

## Why It's Good For The Game
less harddels

## Changelog
:cl:
fix: Fixed plane_master_controller harddel
/:cl:

### CODE REVIEW

**Comment by Dejaku51** [comment]
whoops looks like something else is there

**Comment by Dejaku51** [comment]
huh

**Comment by Archanial** [comment]
I love you lemonman

**Comment by DatBoiTim** [comment]
Excellent PR. This doesn't fix the issue plane_master_controller harddel issue, unfortunately.

Keep open since it provides other optimizations we could use.

**Comment by Dejaku51** [comment]
> Excellent PR. This doesn't fix the issue plane_master_controller harddel issue, unfortunately.
> 
> Keep open since it provides other optimizations we could use.

welp, no hug for me lmao

**Review by Archanial — APPROVED** [review]

**Pull request merged**
