### PR TITLE
Restricts acess to chemical grenades

### PR DESCRIPTION
**Pull request by FriendlyContractor**
## About The Pull Request

- Removes ability to craft chemical grenade casings from iron sheets.
- Removes ability to fabricate chemical grenade casing from lathes and removes relevant research.
- Pre-made chemical grenades can no longer be disassembled to prevent abuse.
- New syndicate item - Box of chemical grenade casings. Contains 6 various chemical grenade casings and costs 8TC.

## Why It's Good For The Game

 Custom grenades are one of the most dangerous/powerful items easily rivaling expensive traitor and nuclear operative equipment. They can be made by everyone and cost no resources.

 First of all, this PR aims to remove irrelevant players' ability to instantly kill important players using various forms of chemical grenades. This, in most cases will mean validhunting but not always and will for example stop players from instantly gibbing nuclear operatives with explosive lance or prevent revolutionaries from doing the same to security officers. Another benefit of this PR will be adding a barrier for griefers as chemical grenades are one of the most commonly used things to grief. And finally, the issue of their low price and ability to mass produce is adressed by putting them behind TC.

## Testing Procedure
<details>

1. Attempted to disassemble pre-made chemical grenade - unsuccessful as intended.
2. Attempted to construct chemical grenade casing using iron sheet - option no longer available as intended.
3. Attempted to buy grenade box from syndicate uplink - sucesfull, box contains intended items.
4. Unable to test if i properly removed relevant research node and lathe entries as i am not fammiliar enough with admin menu - untested.
</details>
## Changelog
:cl:
balance: Chemical grenade casings can no longer be fabricated.
add: Added chemical grenade casings box to uplink.
/:cl:

### CODE REVIEW

**Comment by CydiaLamiales** [comment]
So this stops people from making more cleaning grenades for the janitor and salt grenades to stop the revenant, you alright with that?

**Comment by FriendlyContractor** [comment]
> So this stops people from making more cleaning grenades for the janitor and salt grenades to stop the revenant, you alright with that?

Chemical grenades are never made for any other purpose than combat in reality of ss13. Im removing completly unused feature in order to prevent large amount of abuse and grief.

**Comment by Rukofamicom** [comment]
Even I disagree with this response and grenades are absolutely used for more than you claim, you just don't see outcry or even really hear about cleaning grenades at all unless you directly witness it. Grenades are extremely powerful but restricting them to exclusively uplink antags isn't the answer: Nerfing grenade power in general is.

https://github.com/BeeStation/BeeStation-Hornet/discussions/7099

Take a look at the grenade adjustments in this design proposal, which already has an approval flag for if it gets made.

**Review by Rukofamicom — APPROVED** [review]
While I strongly disagree with the PR, the code looks correct to me.

**Comment by FriendlyContractor** [comment]
> Even I disagree with this response and grenades are absolutely used for more than you claim, you just don't see outcry or even really hear about cleaning grenades at all unless you directly witness it.

Indeed grenades are sometimes used for other purposes such as cleaning or killing weeds. Those grenades however are not made by anyone and are instead available in appropriate vendors roundstart or from cargo. I have not once seen a person make  harmless utility grenade. My changes do not affect availability of pre-made utility grenades.

**Comment by FriendlyContractor** [comment]
> While I strongly disagree with the PR, the code looks correct to me.

Thank you for taking your time to look over my code i appreciate it!

**Comment by FortSumter** [comment]
I'll say this again: stop nerfing or removing antags options for murder. Not all antags in the game are traitors and even if they are,  it's better to have murder tools that don't involve using TC than being caught with traitor items and getting executed.

Antags ability to antag is already nerfed so damn much that outside of using antag only gear/abilities they have to be enabled by non-antag in order to do anything. Antags can't even MAKE chem grenades worth shit unless they're chemists or otherwise got access to potassium or plasma sheets and a grinder. Perhaps people would use them less if antags had more reliable options to kill targets or didn't have to burn down medical every round just so they dont use necromancy to revive their targets.

**Comment by Fronsis** [comment]
> I'll say this again: stop nerfing or removing antags options for murder. Not all antags in the game are traitors and even if they are, it's better to have murder tools that don't involve using TC than being caught with traitor items and getting executed.
> 
> Antags ability to antag is already nerfed so damn much that outside of using antag only gear/abilities they have to be enabled by non-antag in order to do anything. Antags can't even MAKE chem grenades worth shit unless they're chemists or otherwise got access to potassium or plasma sheets and a grinder. Perhaps people would use them less if antags had more reliable options to kill targets or didn't have to burn down medical every round just so they dont use necromancy to revive their targets.

This so much, also... 8TC for... granade CASINGS???? Like you don't even get a nade, you get the EMPTY SHELL of a nade for EIGHT tc i knew Syndicate offered shit deals but... damn. 

Also as they pointedo out RIP the carpet,salt, jani nades

**Comment by EvilDragonfiend** [comment]
Botany gas is still a thing at this point

**Comment by FriendlyContractor** [comment]
> This so much, also... 8TC for... grenade CASINGS????

Its quite cheap actually compared to other things:
- Minibomb alone costs 5TC - **5** equivalent explosives can be made using provided materials.
- Bio terror foam grenade costs 7TC each and is nuke ops only - **6** equivalent grenades can be made.
- You can make much more powerfull grenades than above which have even more hypothetical TC value.
- You can make your own bee grenade!

**Comment by St0rmC4st3r** [comment]
Please don't steal bad ideas from Goon. We do not have such busted stuff as QG Plasma and triple meth or whatever is the goon's current favorite grief chem.

**Comment by Zonespace27** [comment]
This removes a large amount of utility from chems that any role (antag or not) can utilize, restricting it to just traitors. Which reduces the overall versatility of chemistry, as the ability to throw a reaction at someone, regardless of your role, has been kept in mind since they were added. (Also, chem grenades on Goon, where I presume you took the idea from, are absolutely useless and are one of the least bought traitor items)

**Comment by DerpiestBruh** [comment]
bait pr

**Comment by FortSumter** [comment]
Here's how this PR should work:

Make a grenade casing cost 5 metal and only accept the 50u beakers. Add a large grenade casing costing 5 plasteel and allow the 100u beakers, but also require a modular reciver after adding the wire. Add the traitor grenade kit for 12 TC  that have 4 syndicate casings that allow for 3 50u beakers and a syndicate screwdriver. Move the chemical payload to require plastitanium.

By making the grenades more expensive and nerfing the basic iron ones to only allow half of it's original payload, it should solve all the problems with chemical grenades without outright removing them, which is what this PR is doing. Requiring a modular for each 200u made is absurdly expensive and can only can be acquired via maints and a hacked autolathe. Making a large amount of grenades would require a huge amount of oversight by command staff at this point it'd really be their fault for allowing grenade spam to happen.

The main reason chem grenades need to be nerfed at all is because of firebombs mostly, which this PR doesn't fix at all since you can firebomb with just sheets of plasma, an igniter and a proximity sensor, all of which you can get very easily. I implore you for the sake of the downsteams you reject this PR and do my idea instead.

**Comment by PowerfulBacon** [comment]
Closing due to large amount of negative reactions to the PR along with some oversights that chemists can print even better grenade casings from the lathes. This adds an interesting way to do some ghetto explosives which will usually be small scale.

**Pull request closed without merging**
