### PR TITLE
2 hour playtime time requirement for eng/sci jobs

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Adds 2 hour playtime requirement (as any crew) to station engineer, atmospheric technician, scientist and roboticist.

## Why It's Good For The Game

Newly joined accounts will need to play approximately 2 rounds before they can spawn in departments that can easily grief. See all the 10 minute account bans for TTVs/engi sabotage.

Annoying chronic griefers is good.

## Changelog
:cl:
tweak: All engineering and science jobs have a minimum 2 hour playtime requirement.
/:cl:

### CODE REVIEW

**Comment by Mat05usz** [comment]
Based

**Comment by utilbird** [comment]
Science is a really noob friendly job, I wouldn't playtime lock it.
Engineering is also a big attraction for new players, a bit meh about that one too.

A better option for science would be a playtime check with TTVs and their associated signallers/triggers, i.e "You can't figure out how to use this!". Iirc world server implemented something along those lines.

**Comment by leestriter** [comment]
Why engi and science, are they the most grief heavy jobs? I mean botany can grief pretty easily, and of course we don't want medstaff that can't play the game. Sec players should know what they are doing to avoid shitsec. Hm, actually, I guess we should just require two hours play time for every job? I don't like this. If people grief in those jobs ban those people.

**Comment by Mat05usz** [comment]
> Why engi and science, are they the most grief heavy jobs? I mean botany can grief pretty easily, and of course we don't want medstaff that can't play the game. Sec players should know what they are doing to avoid shitsec. Hm, actually, I guess we should just require two hours play time for every job? I don't like this. If people grief in those jobs ban those people.

Yes, because a lot of griefers join engie to: flood the station or delam the SM any%, and join sci to: make maxcaps real quick and destroy large parts of the station.

**Comment by Mat05usz** [comment]
> Science is a really noob friendly job, I wouldn't playtime lock it.
> Engineering is also a big attraction for new players, a bit meh about that one too.
> 
> A better option for science would be a playtime check with TTVs and their associated signallers/triggers, i.e "You can't figure out how to use this!". Iirc world server implemented something along those lines.

I really wouldn't say that both jobs are noob friendly. A noob doesn't understand what both jobs are for, they should stay as an assistant (or jannie, or basically any role that usually doesn't matter and has easy mechanics). I remember being given engie job a lot when I was a noob and I really hated it (I didn't know I can change shit in job preferences).

**Comment by Mat05usz** [comment]
> Why engi and science, are they the most grief heavy jobs? I mean botany can grief pretty easily, and of course we don't want medstaff that can't play the game. Sec players should know what they are doing to avoid shitsec. Hm, actually, I guess we should just require two hours play time for every job? I don't like this. If people grief in those jobs ban those people.

Mmm yes I deleted my reply because I thought my  browser bugged out and placed two replies smh. Science because griefers can make maxcaps really quickly and grief with them. Engie because griefers either plasma flood or delam SM roundstart. Basically 90% of griefers do the things I described above.

**Comment by leestriter** [comment]
> > Science is a really noob friendly job, I wouldn't playtime lock it.
> > Engineering is also a big attraction for new players, a bit meh about that one too.
> > A better option for science would be a playtime check with TTVs and their associated signallers/triggers, i.e "You can't figure out how to use this!". Iirc world server implemented something along those lines.
> 
> I really wouldn't say that both jobs are noob friendly. A noob doesn't understand what both jobs are for, they should stay as an assistant (or jannie, or basically any role that usually doesn't matter and has easy mechanics). I remember being given engie job a lot when I was a noob and I really hated it (I didn't know I can change shit in job preferences).

Idk people I introduced to the game that started as assistant or jani ended up thinking the game was awful. Assistant or jani can be fun once you kinda understand what's going on, but for new person that's 1-2 hours of having nothing to do, cause those jobs are so freeform.

**Comment by leestriter** [comment]
> > Why engi and science, are they the most grief heavy jobs? I mean botany can grief pretty easily, and of course we don't want medstaff that can't play the game. Sec players should know what they are doing to avoid shitsec. Hm, actually, I guess we should just require two hours play time for every job? I don't like this. If people grief in those jobs ban those people.
> 
> Mmm yes I deleted my reply because I thought my browser bugged out and placed two replies smh. Science because griefers can make maxcaps really quickly and grief with them. Engie because griefers either plasma flood or delam SM roundstart. Basically 90% of griefers do the things I described above.

Ok you got me with the sm delam. If we can have less roundstart delams, I'll be very happy.

**Comment by leestriter** [comment]
The people I always have the most trouble with are chemist. They are med but so often they just make bombs, thermite, drugs. But I understand an engi or scientist can cause damage on a far larger scale. I still think botanist have just as much griefing power and botany is easier then engi or sci.

**Comment by Effemu** [comment]
assistant is fun only after you get robust and learn how to tide, before that you're just a deadweight with no access and everyone wanting to kill you

and dont give me the "you play assistant so you should assist people", i havent seen anyone letting greytide anywhere near their projects in those 1000+ hours i spent on this game

**Comment by Effemu** [comment]
> 
> 
> The people I always have the most trouble with are chemist. They are med but so often they just make bombs, thermite, drugs. But I understand an engi or scientist can cause damage on a far larger scale. I still think botanist have just as much griefing power and botany is easier then engi or sci.

Every role has the same amount of griefing power. 2 hour playtime assumes griefer doesnt know how to hack doors, which im pretty sure they know.
People will plasmaflood as assistants and all this pr does is add max 20 seconds of hacking and obtaining tools griefer has to do before dumping plasma all over the station or unwrenching pipes and throwing them into sm

**Comment by Mat05usz** [comment]
This is assuming they can get tools fast (before legit tiders) and that they bother enough. Assistant (or any other job) breaking shit into engie/sci few minutes in is way more obvious than engineer pushin N2 cannisters into the SM shortly before ahelping "any% speedrun" and kissing the crystal themselves.

New players are busy dealing with 'how do I unbuckle' or 'how do I move problems', not that they didn't get engie/sci during their first 2 hours of playtime.

**Comment by Sinestia** [comment]
I don't think this is great

In practice most of the 10 min grief bans are low-pop when no admemes are on, aka you probably have AA or at least no one's really gonna stop you from tiding wherever you need to be. 

I think the most harm with this is with players coming from other servers to play bee. If you're an engi/sci main looking to try other servers and you decide to try bee and see that you're blocked for 2 hours, there's a good chance that you'll just close it and play something else. 

If people actually think this is a good idea though, chemist and botanist realistically should be there too. You can make bombs that are basically maxcaps as chem very easily, and these 10 minute griefer bans are also dedicated griefers IIRC, meaning that they know plenty how to abuse those jobs to similar effect.

**Comment by pickleinjar** [comment]
ok this one actually makes sense. i as a noob played engi and i took on a radsuit and didnt really know what i was doing.
i walked directly into the sm bc i dunno what im doing. an admin said that i couldnt touch the crystal so i walked away.

**Comment by ghost** [comment]
The amount of bikeshedding is amazing. It's not rocket science, nobody new will even notice 2 hours. It's barely 2 rounds.

**Comment by leestriter** [comment]
I don't know enough about engineering to comment there, beyond setting up solars/SM I know very little about it. Science I know more about, and I know its not entirely related, but I think part of it is scientist is multiple jobs wearing a trenchcoat. Xeno biology and toxins should be separate jobs just like robotics and science are. Then you could give toxins, say, 10 hours required playtime and solve this issue without locking out science entirely.

**Comment by R3pID** [comment]
Good pr but you should go back on your main account

**Comment by ghost** [comment]
Closing in favour of https://github.com/BeeStation/BeeStation-Hornet/pull/3853

**Pull request closed without merging**
