### PR TITLE
Randomized engines for meta and box.

### PR DESCRIPTION
**Pull request by Moccha-Bee**
## About The Pull Request
Zesko said he would add randomized engines, but i ain't gonna allow that cringe plasma man to beat me, It's fully working with tesla/singularity room for meta that comes with a spawner that has a 80% chance of spawning a tesla and 20% of spawning a singuloth.
https://imgur.com/gallery/zmGkG7b
the random engines above^
ignore the depressurization, one of the airlocks was missing a tile.

- [x] Finish all the meta engines

- [x] Add random engines to box

## Why It's Good For The Game
It's pretty based and forces engineers to learn the old engines.

## Changelog
:cl:
add: Added randomized engines to meta
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
You still have a debug map in there. You also only mapped this for meta, and only have one engine. Kerbin's pr was better than this and still was not merged.

**Comment by Moccha-Bee** [comment]
> You still have a debug map in there. You also only mapped this for meta, and only have one engine. Kerbin's pr was better than this and still was not merged.

I posted it first before you could it, i can map the rest of the engines quickly so i can get most maps fully covered tomorrow kilo being the exception.

**Comment by zeskorion** [comment]
> > You still have a debug map in there. You also only mapped this for meta, and only have one engine. Kerbin's pr was better than this and still was not merged.
> 
> I posted it first before you could it, i can map the rest of the engines quickly so i can get most maps fully covered tomorrow kilo being the exception.

there is no point in posting the PR first if it's shit

**Comment by utilbird** [comment]
I don’t know who to root for now

**Comment by Moccha-Bee** [comment]
> I don’t know who to root for now

don't root for zesko, he is infamous for destroying fun, here i'm adding fun™

**Comment by Moccha-Bee** [comment]
I think travis is shitting itself because of var edited objects, either way no problems so far.

**Comment by Moccha-Bee** [comment]
branch broke

**Pull request closed without merging**
