### PR TITLE
Adds a blacklist to Pun-Pun's hat & mask saving

### PR DESCRIPTION
**Pull request by benbot16**
## About The Pull Request

This adds a blacklist to punpun's hat/mask saving and loading functionality to prevent certain items from being placed onto him.

This blacklist currently just includes living facehuggers (for obvious reasons) and chameleon gear (because of voice changers), but I can add more things to it if anyone has suggestions. 

## Why It's Good For The Game

No fun allowed.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image

Punpun has a saved facehugger, but it doesn't load.
</details>

## Changelog
:cl:
tweak: Blacklists certain items from Pun-Pun's mask/hat saving functionality (notably facehuggers and chameleon clothing)
/:cl:

### CODE REVIEW

**Comment by DerpiestBruh** [comment]
soulless pr

**Comment by Fronsis** [comment]
The tyranny of griefer Pun Pun is over.... sleep well king

Alternative take: What if instead of loading a hugger it gets replaced with a Toy Alien? would be a funny reference to remember all the chaos he caused in... four-three rounds these pasts months

**Comment by benbot16** [comment]
> The tyranny of griefer Pun Pun is over.... sleep well king
> 
> Alternative take: What if instead of loading a hugger it gets replaced with a Toy Alien? would be a funny reference to remember all the chaos he caused in... four-three rounds these pasts months

I'd rather have it just be a general typecache so that other stuff can get put in easily. With how this is set up, though, you can always just give punpun a toy hugger and it'll stay.

**Comment by hotimep** [comment]
5 minute xenos in shambles

**Review by itsmeow — APPROVED** [review]

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
