### PR TITLE
Metastation science remap

### PR DESCRIPTION
**Pull request by PowerfulBacon**
Closes https://github.com/BeeStation/BeeStation-Hornet/pull/5281

## About The Pull Request

Partially remaps part of metastation science.
Makes the explorers have direct access to the science hallway.

image

image

## Why It's Good For The Game

Explorers no longer need to run through toxins or maints to get to their dock on metastation.

## Changelog
:cl:
tweak: Remapped metastation science so explorers no longer need to maint crawl / go through toxins.
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
Is that room between the launch site and the toxins lab still a public maintenance room?

**Comment by PowerfulBacon** [comment]
> 
> 
> Is that room between the launch site and the toxins lab still a public maintenance room?

Yes

**Comment by AnCopper** [comment]
> > Is that room between the launch site and the toxins lab still a public maintenance room?
> 
> Yes

I don't think it's a good idea to have windows between that and toxins.

**Comment by PowerfulBacon** [comment]
image

**Comment by francinum** [comment]
'partial'

You have remapped a good two thirds of what counts as science.

**Comment by PowerfulBacon** [comment]
Its partial as in all of the right side

**Comment by PowerfulBacon** [comment]
who did this, who conflicted me

**Comment by williamcll** [comment]
Did you make sure the TTV doesn't launch into the shuttle?

**Comment by PowerfulBacon** [comment]
> 
> 
> Did you make sure the TTV doesn't launch into the shuttle?

Yes

**Comment by 4rchibald** [comment]
@PowerfulBacon 

Was thinking about messing with dock on meta myself but I checked here and I see you're tackling it

The issue with current dock location is that both it and shuttle gets irradiated every time someone runs turbine.
I was thinking about moving dock below toxin range and keep laser practice range as buffer 

Other than that, there's missing piping resulting in airlock not cycling without shuttle docked, but that doesn't matter since you're redoing it anyway

**Pull request closed without merging**
