### PR TITLE
Tells roundstart observers what the game mode is.

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
Tells people who are observers at roundstart what the actual game mode is, not just secret.

## Why It's Good For The Game
Observers can already tell what the game mode is by either checking the ghost-visible antagonists in the orbit menu, or using the Observe verb to check antag moodlets. This makes it so that roundstart observers don't have to go through 30 people's moodlets just to figure out what the mode is.

## Changelog
:cl:
add: Roundstart observers are now told what the game mode is.
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
Bad idea

**Comment by Ivniinvi** [comment]
Ghosts can already tell who the antags are by checking moodlets with observe, this just makes it less tedious to find out.

**Comment by Isy232** [comment]
> Ghosts can already tell who the antags are by checking moodlets with observe, this just makes it less tedious to find out.

This is probably a bad idea, let me explain.

Ghosts are generally not completely aware of antagonists until they do something. You can spend the time to go checking every single person on the station and make a list, but its a lot of effort and nobody would really want to.

If ghosts were immediately told it was a blood cult, they would probably all be discussing the blood cult.

Now lets say a security officer dies early due to an accident and overhears this.

By the rules, the security officer should try their best to not let this meta information impact their decisions, but even subconciously it may change their minor decisions to make it more difficult for the cult.

The ideal solution would be minimizing the amount of meta information shared to players who die and get revived while still letting ghosts hang out and observe the current round.

So I dont think increasing the amount of meta information available to ghosts, even roundstart ones, is a good idea.

**Comment by RDS88-beeman** [comment]
Well, ghosts ARE immediately told it's a blood cult, because they can hear cult chat.
This immediately outs, to ghosts, all of the following antagonists
Blood Brothers
Blood Cult
Clock Cult
Incursion
Nukies
In addition, certain antags show up to ghosts on the follow menu.
This outs
Wizard
Nukies (again)
Nightmare
Sentient Disease
Revenant

This leaves
Changeling
Heretic
Revolution
and as always Traitor.
Revolution is an... obvious gamemode to those that know what to look for, and the rest have optional team communications and can be checked for by moodlets. Only a small fragments of antagonists can hide from an unobservant ghost, and if even one brings up in dchat that XYZ is a traitor, any transiently dead people are going to hear.

**Comment by RDS88-beeman** [comment]
oh right i forgot blob and teratoma blob is even more obvious than wizard and literally gets an announcements and tomas have a unique name on the ghost follow menu

**Comment by PowerfulBacon** [comment]
stuff like cult chat should be hidden to dead seccies that can still be revived

**Comment by Archanial** [comment]
This doesn't convince me. I don't think it's a good idea.
🔑

**Comment by BrumalLake** [comment]
might as well give ghosts antag hud
good reason why yogs had it removed several years ago

**Comment by Ivniinvi** [comment]
> might as well give ghosts antag hud

Again, this is just for *roundstart* observers, who have no body to be put into and no way to enter the game save ghost roles. Addtionally, 8/10 antags can just be found via orbit menu/antag-specific comms and the other 2/10 can be found using Observe. The roundstart ghosts will already know who the antags are, but someone who's dead for a total of 40 seconds won't really figure out exactly who the traitors and lings are.

**Comment by BrumalLake** [comment]
instead of going this direction, with the dumb "it's already meta-able so make it even more meta-able" logic what about making those comms not observable
antags that can be orbited are quick to finish rounds, or be discovered

**Pull request closed without merging**
