### PR TITLE
Maploader Update/Optimizations and Atoms Init fix

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

Ports several optimizations and improvements to the maploader and baseturfs from TG:
- https://github.com/tgstation/tgstation/pull/54277
- https://github.com/tgstation/tgstation/pull/54857
- https://github.com/tgstation/tgstation/pull/54860
- https://github.com/tgstation/tgstation/pull/54888
- https://github.com/tgstation/tgstation/pull/62414
- https://github.com/tgstation/tgstation/pull/69632
- https://github.com/tgstation/tgstation/pull/70118
- https://github.com/tgstation/tgstation/pull/70933
- https://github.com/tgstation/tgstation/pull/70966
- https://github.com/tgstation/tgstation/pull/71074

Space reservation subsystem of
- https://github.com/tgstation/tgstation/pull/70729

Atom init (requires maploader optimizations):
- https://github.com/tgstation/tgstation/pull/76179
- https://github.com/tgstation/tgstation/pull/76241

I made sure that this worked with our async map_placer and lava cave generation differences. I think they work.

Most notable deviation from TG is to the mob spawning system, which has been altered to retain old spawning behavior. TG's version does not properly space mobs out causing overspawning megafauna and tendrils. Simplifying or lowering the range requires altering weights and spawn chances - a simpler solution that TG overlooked is storing the list of mobs already created and then iterating over those, checking get_dist, since we only care about other mobs anyway, making urange() a complete waste. This has roughly the same performance as TG while retaining proper spawning behavior.

## Why It's Good For The Game

This supposedly optimizes maploading. I cannot verify this claim fully.

In my testing, I got 65.4sec master init on Meta vs 57sec on this branch, for a 8.4sec reduction.
This is corroborated by several test runs, usually getting the same or close values (2sec margin of error, meaning a worst case 5sec reduction and best case 11sec)

The atom init fixes should fix the random test failures we've been having caused by "maploading while already maploading!!" since it now handles that case just fine.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Shuttle takeoff clears area
image

Flying shuttle
image

Landing on lavaland
image

Caves cannot overwrite lava rivers
image

Ruin and mob gen
image

Old mob gen examples
image
image

image

New mob gen examples
image

image
image

Custom shuttle in action
image

Drydock landing
image
image

Successful takeoff
image

Crowbarring a floor
image

Deleting drydock floor
image

Areas working
image

image

</details>

## Changelog
:cl: LemonInTheDark, itsmeow, Ghommie, Dennok
code: Optimized maploading, ruin generation, and cave generation, saving ~8sec init time.
code: Optimized ChangeTurf.
code: Optimized getting area contents in some cases, although there are still many inefficient `in area` loops to clean up.
fix: Fixed atom init sometimes failing when generating in round or during unit tests.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Only thing is this will only apply to maps loaded at roundstart since the lazy loaded ruins use a different maploader which can run slowly but is largely the same code with heavy modifications to allow for pausing and resuming it through a subsystem. Map placer and map template loader are essentially the same

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
This changes baseturfs in a major way but doesn't properly account for current usecases of baseturfs that exist on bee but not TG, such as custom shuttle designation.
image
image

**Comment by PowerfulBacon** [comment]
Also what code changes does this make to baseturfs, since I have a branch working with baseturfs and will need to update it to support this once it is merged.

**Comment by itsmeow** [comment]
It simply wraps baseturfs in a cached value so ?rebuilding them takes less processing? Baseturfs are still stored as lists, they are simply cached by their value as strings in an associative list. I'm not really sure how or why this is good for performance since it's not really explained anywhere.

**Comment by itsmeow** [comment]
Added more testing evidence of stuff working relating to baseturfs and shuttles

**Comment by itsmeow** [comment]
The reason the Insert changes are needed is because it'd be modifying the cached baseturfs list. So now instead I copy the old list, modify it, then recache it. I believe I have covered all the cases here now.
The most important thing to keep in mind is not to modify cached baseturf lists directly (e.g. insert) since they are shared between anything with the same baseturfs. Also cache baseturfs when doing the final assignment within your proc.

**Review by PowerfulBacon — DISMISSED** [review]
Breaks the arrivals shuttle

**Comment by itsmeow** [comment]
How

**Comment by PowerfulBacon** [comment]
From investigating further it seems like the area var on arrivals shuttles is not being set during mapload, which means that the arrival shuttle cannot tell when mobs are inside of it. Not sure if this affects the shuttle_areas var too on other shuttles.

**Comment by itsmeow** [comment]
Fixed it. Before the first join would fail, here it is working
image

**Comment by itsmeow** [comment]
Seems fine so far

**Comment by itsmeow** [comment]
Explo ruins seem to make oversized baseturfs

**Comment by itsmeow** [comment]
can't reproduce the baseturfs

**Review by PowerfulBacon — APPROVED** [review]
Seems okay

**Pull request merged**
