### PR TITLE
GIVE THE PEOPLE WHAT THEY FUCKING WANT

### PR DESCRIPTION
**Pull request by bloons3**
## About The Pull Request

BREAD AND CIRCUSES

VOTE BLOONS3 HEADMIN 2025 OR I'LL FUCKING BAN YOU

## Changelog
:cl:

refactor: refactored some code
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — DISMISSED** [review]

**Comment by DatBoiTim** [comment]
Panem et Circenses is not enough bloons cmon man

**Comment by Effemu** [comment]
megabased speedmerge immediately

**Comment by DatBoiTim** [comment]
I like to pretend I am immune to propaganda, but this is some great propaganda

**Comment by bloons3** [comment]
image

**Comment by 1glitchycent** [comment]
This PR allows for more interesting conflict between players to be created during a round, thus increasing character interaction. Hence, it can only possibly increase roleplay with the listed changes.

**Comment by ike709** [comment]
image

**Comment by 1glitchycent** [comment]
RIOT. REVOLT. KILL.

**Comment by BrotherHangyul** [comment]
Okay what the fuck this was a genuinely good PR

**Comment by super12pl** [comment]
> Okay what the fuck this was a genuinely good PR

I know right?

**Pull request closed without merging**
