### PR TITLE
Removes racism

### PR DESCRIPTION
**Pull request by francinum**
## Changelog
:cl:
tweak: The pool of syndicate codewords has been adjusted.
/:cl:

### CODE REVIEW

**Comment by OceanFish1** [comment]
I didn't know syndicate was """""""""""""""based""""""""""""" until this PR

**Comment by eLeCtrOssSnake** [comment]
Doesn't matter anyway.

**Comment by Sinmero** [comment]
ANGRY BLACK MEN > racism
NA amrite

**Comment by eeSPee** [comment]
Racism solved. World peace achieved.

**Comment by aidan-bowman** [comment]
Next step: instead of charcoal pills being black, they will be pills of color.

Space isn't black, it's oxyloss of color

Walls aren't black, they're barriers of color

Maints aren't black, they're antag hideouts of color

seriously speedclose this

**Review by Crossedfall — APPROVED** [review]

**Comment by utilbird** [comment]
1984

**Pull request merged**
