### PR TITLE
Bumps Auxmos from 0.2.4 to 1.1.2

### PR DESCRIPTION
**Pull request by dwasint**
## About The Pull Request
NOTE: Version 1.0 and onward requires rust 2021 in order to compile. So if that isn't installed on the machine it will fail to compile

Bumps the auxmos version from 0.2.4 upwards to 1.1.2, following the instructions on https://github.com/Putnam3145/auxmos/blob/master/docs/MIGRATING.md

Note this should probably be test merged intensely as its one of the most important systems, tested on local for a good while while working on downstream with no issues.

Auxmos CL: https://github.com/BeeStation/auxmos/releases/tag/1.1.2

No player facing changes.

## Why It's Good For The Game
More up to date auxmos allows for some of the newer features and the potential for a better fastmos system if need be

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
server: Updates auxmos to 1.1.2
/:cl:

### CODE REVIEW

**Review by Crossedfall — DISMISSED** [review]
Binaries need to come from our own fork added by a maintainer. Please pull your `auxmos.dll`

We'll work to update our fork https://github.com/BeeStation/auxmos and include the binary from there.

**Comment by dwasint** [comment]
> Binaries need to come from our own fork added by a maintainer. Please pull your `auxmos.dll`
> 
> We'll work to update our fork https://github.com/BeeStation/auxmos and include the binary from there.

Addressed in latest commit

**Comment by Crossedfall** [comment]
Very confused on how/why this was closed. It's not even referenced in our github feed as being closed and there's no audit log on why.

**Comment by Crossedfall** [comment]
Enough time has passed where this needs a re-TM. Putting it in the priority queue, though.

**Review by Crossedfall — APPROVED** [review]
Seems fine. Giving it my approval.

**Comment by Crossedfall** [comment]
All good with our extended TM

**Pull request merged**
