### PR TITLE
Makes dynamic and secret extended the default gamemodes.

### PR DESCRIPTION
**Pull request by AnCopper**
## About The Pull Request

Disables all gamemodes but dynamic and secret extended, If this works the way I think it does, then this should make for a 9/1 dynamic - sextended ratio.
## Why It's Good For The Game

Dynamic is all these gamemodes but put into one, seems like everyone wants this too.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
config: disabled all gamemodes but dynamic and secret extended, with a ratio of about 9-1 dynamic/secret extended.
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
O'Mighty Lord Dynameme

**Comment by TeomanTheGreat** [comment]
All hail our lord dynamic

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Dynamic is not ready to be the only gamemode.

1: It doesn't include all gamemodes.
2: There should be a dynamic config
3: It's far too intense. 20% of the station shouldn't be antag, and we shouldn't get gigalowpop wizards and stuff.
4: I think it's fine to have non dynamic modes integrated with it still, it adds some more variety as dynamic tends to merge the same gamemodes in a lot of rounds (If its not nukies then most of the time all the minor gamemodes tend to be played at once)

**Comment by PowerfulBacon** [comment]
If we are going to do this, extended should go too anyway

**Comment by AnCopper** [comment]
Oh okay, I didn't know that.

**Comment by itsmeow** [comment]
Yeah, I'm still working on dynamic. When it's done, and incursion is added (the only missing gamemode atm), we can shift towards it being the main gamemode

And @PowerfulBacon 

> There should be a dynamic config

There is a dynamic config, it's dynamic.json

>It's far too intense. 20% of the station shouldn't be antag

You can lower the average threat curve.

> and we shouldn't get gigalowpop wizards and stuff.

Lowpop wizards are extremely rare.

**Pull request closed without merging**
