### PR TITLE
Changeling Cthinous Armor Buff

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Tweaked the changeling armor defenses to be more anti projectile/melee. Protects you against shoving too, but slows you down. Great for lings who wanna go loud. Also tweaks cost a bit to be more fair.

## Why It's Good For The Game

Changelings really don't have a good way to deal with projectile attackers. Changeling armor was bad altogether, not in the stats that it provided, but in the fact that it provided resistances to damage types lings may not encounter when going loud (fire, melee) makes it kinda obsolete for a "going loud" item.

## Changelog
:cl:
tweak: the cost and resistances of ling armor; it is now a loud anti projectile defense.
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
im looking at this right now, and... nah man. lings are supposed to be a bit weak to ranged. i'm aware that stamshit fucks em up a bit, but that's being handled in another way. looks ided to me

**Comment by eeSPee** [comment]
But the ling armor is useless.

2 birds with one stone?

**Comment by ghost** [comment]
R3move armor

**Comment by PowerfulBacon** [comment]
> im looking at this right now, and... nah man. lings are supposed to be a bit weak to ranged. i'm aware that stamshit fucks em up a bit, but that's being handled in another way. looks ided to me

Dont they have an ability that makes them immune to stamshit?

**Comment by ItsTisme** [comment]
> > im looking at this right now, and... nah man. lings are supposed to be a bit weak to ranged. i'm aware that stamshit fucks em up a bit, but that's being handled in another way. looks ided to me
> 
> Dont they have an ability that makes them immune to stamshit?

Ling adren?

**Comment by PowerfulBacon** [comment]
It's changeling and flesh so it should be weaker to fire/laser damage and more resistant to melee and bullets, the other way around doesn't make much sense

**Comment by ghost** [comment]
> It's changeling and flesh so it should be weaker to fire/laser damage and more resistant to melee and bullets, the other way around doesn't make much sense

Art thou stupid? Chitin isn’t flesh, just like fucking lizards aren’t flammable

**Comment by eeSPee** [comment]
> It's changeling and flesh so it should be weaker to fire/laser damage and more resistant to melee and bullets, the other way around doesn't make much sense

Cthin isn't flesh; think clam and crab shells.

**Comment by Unidentified-Biohazard** [comment]
Like it

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
75 is near-immortality, 80 is the value used for death squad armour. Use something like 50.

**Comment by eeSPee** [comment]
ok.

**Review by qwertyquerty — APPROVED** [review]

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
