### PR TITLE
[Mapping] Gives metastation a fusion room in Atmos

### PR DESCRIPTION
**Pull request by bloons3**
## About The Pull Request
Tries to steal this
image

https://github.com/tgstation/tgstation/blob/master/_maps/map_files/MetaStation/MetaStation.dmm

- [x] Add airlock controller
- [ ] Subarea(?)
- [x] Air alarm
- [ ] Playtest
- [ ] Stub some piping to make it easer for atmos to hook in?
- [ ] setup the space zones
- [ ] Space lattice

## Why It's Good For The Game
- WIP

## Changelog
:cl:
add: Added a fusion room to Metastation
/:cl:

### CODE REVIEW

**Comment by Sinmero** [comment]
Good. Fusion requires reinforced floors thou. Also a separate apc would be nice atmos apc drains really fast as it is.

**Comment by Sinestia** [comment]
Eh.... I dunno how fitting it is with how little space setups consume, this is made for the HFR which mandates an annoying-to-build 3x3 machine with 3 pipes connected to it with freezers or space loops being used for 2 of them. 




> 
> 
> Good. Fusion requires reinforced floors thou. Also a separate apc would be nice atmos apc drains really fast as it is.

It's one of the things you have to build imo
or an entire separate SMES on the origin server because cooling will basically irrevocably shut off if you hit power level 6 without rad collectors and a SMES.

**Comment by bloons3** [comment]
> Eh.... I dunno how fitting it is with how little space setups consume

It is a space where if fusion go boom boom the rest of the station is not immediately compromised.

**Comment by utilbird** [comment]
Seems a bit excessive to have a room dedicated to a gimmick where the incinerator worked fine.

> It is a space where if fusion go boom boom the rest of the station is not immediately compromised.

That's supposed to be a part of the risk. Even then, fusion meltdowns rarely happen and when they do it's usually intentional

**Comment by Ghilker** [comment]
At least give credits by saying the PR where you ~stole~ took this from 

And is very useless for your server since you don't even have the Hypertorus Fusion Reactor (you can even see the boards in the image lol not even trying)

**Comment by bloons3** [comment]
> At least give credits by saying the PR where you ~stole~ took this from
> 
> And is very useless for your server since you don't even have the Hypertorus Fusion Reactor (you can even see the boards in the image lol not even trying)

Thought this had been attributed to TG's meta map. Corrected, thanks.

Even if this is more useful for the torus, Atmos doesn't have many areas without piping shoved under the ground, which makes it a royal pain to do anything. Bee still only has 3 layers, not 5.

**Comment by ike709** [comment]
Stale

**Pull request closed without merging**
