### PR TITLE
More pod docks

### PR DESCRIPTION
**Pull request by St0rmC4st3r**
## About The Pull Request

Remaps the centcom recovery ship to have more pod docks.
image

## Why It's Good For The Game

The old ship is boring and people want to make shuttles with deployable pods, so we might need those.

## Changelog
:cl:
tweak: The pod recovery ship has been replaced with one that supports up to 6 pods.
/:cl:

### CODE REVIEW

**Comment by Wilchenx** [comment]
god that looks absolutely ugly

**Comment by St0rmC4st3r** [comment]
> god that looks absolutely ugly

Would you be so kind to elaborate?

**Comment by Wilchenx** [comment]
> > god that looks absolutely ugly
> 
> Would you be so kind to elaborate?

I really don't like how  it looks, please make it prettier.

**Comment by St0rmC4st3r** [comment]
> > > god that looks absolutely ugly
> > 
> > 
> > Would you be so kind to elaborate?
> 
> I really don't like how it looks, please make it prettier.

If you are talking about the protruding parts, they look better in game. Otherwise this is not constructive criticism. Criticising - propose.

**Comment by May-Rai** [comment]
It looks pretty cool

**Review by francinum — APPROVED** [review]
Whatever. I need to remap this section anyways

**Comment by PowerfulBacon** [comment]
It looks extremely ugly and we don't need more docks since shuttles that can go to centcom (like the whiteship) enter permanent hyperspace rather than going there so it won't be used by them. This is completely pointless and will have 2 doors that open to space unless someone makes a map with 6 docks.

**Pull request merged**
