### PR TITLE
Removed French

### PR DESCRIPTION
**Pull request by ValuedEmployee**
## About The Pull Request
(Before anything, this is a joke PR)
This PR removes any potential for players to don the french beret in-game and begin uttering french word replacements from mechanics.

## Why It's Good For The Game
This is an English speaking server and other languages do not fit the rules requirements. No more oui oui.

## Changelog
:cl:
del: Removed the french language document
del: Removed the french speech calls for the french beret item
/:cl:

### CODE REVIEW

**Comment by Haliris** [comment]
(before anything, this isn't a joke comment)
I didn't laugh.

**Comment by PowerfulBacon** [comment]
Finally

**Comment by Hardly3D** [comment]
Finally, french removal.

**Comment by Socialistion** [comment]
Yeah, get rid of 'em! Fuck the french!

**Review by ike709 — APPROVED** [review]

**Comment by DerpiestBruh** [comment]
I support the removal of the french

**Comment by KennyBadrige** [comment]
> Yeah, get rid of 'em! Fuck the french!

do not the french

**Comment by giacomoh** [comment]
Sure

**Comment by DatBoiTim** [comment]
Glory to Beestation 🫡

**Comment by ToasterBan** [comment]
finally, a pr that solves our roleplaying issues

**Comment by PowerfulBacon** [comment]
hi guys i just wanted to say that i love france and i take back my previous statement and the french are really nice and i cant merge this pr for that reason. i love the french government!

**Comment by DatBoiTim** [comment]
> hi guys i just wanted to say that i love france and i take back my previous statement and the french are really nice and i cant merge this pr for that reason. i love the french government!

Bacon blink once if you were taken hostage by the french

**Pull request closed without merging**
