### PR TITLE
Load example config if no other config is present

### PR DESCRIPTION
**Pull request by ike709**
## About The Pull Request

The example config will be loaded if no other config is present. Fixes localhost autoadmin and who knows what else.

## Why It's Good For The Game

Makes life easier for coders.

## Changelog
:cl: ike709
tweak: Example config files will be loaded if no other config files are present.
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
This just encourages edits to the example config, which is gitignored

**Comment by CthulhuOnIce** [comment]
This is good

**Comment by ike709** [comment]
@qwertyquerty That's arguably a good thing, since it allows people to alter the config for testing/memes/whatever without worrying about accidentally committing changes.

Plus newcoders are confused about why they can't make themselves admin on local test servers, and this fixes that. Who knows what else relies on the config actually, y'know, existing?

**Comment by CthulhuOnIce** [comment]
@ike709 it's of no consequence, as the same thing can be achieved without this PR, but, it doesn't hurt so I'll probs merge it

**Pull request merged**
