### PR TITLE
Ports advanced injector input sanitization, take two

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request

ports https://github.com/tgstation/tgstation/pull/49531
## Why It's Good For The Game
see above pr
## Changelog

:cl:
fix: no more raw html capability in injectors
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
thakes boo

**Comment by zeskorion** [comment]
> thakes boo

yeah no problem.

**Comment by zeskorion** [comment]
well, travis shit himself

**Comment by Crossedfall** [comment]
cl was malformed so it won't be captured by the bot. 

editing it wont save things. :(

**Comment by MCterra10** [comment]
REEEE ZESK

**Pull request merged**
