### PR TITLE
items' illegal tech flag can be identified by RD, scientist, detective, lawyer, captain

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
illegal tech flag can be identified by RD, scientist, detective, lawyer, captain
Security team is excluded except for detective

## Why It's Good For The Game
To be honest, I really can't suggest if it's good, but I hope this can be a good RP source - especially detective and lawyer.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

* **first thing:** maploaded illegal tech emag (or admin spawn) - because these are not made through uplink
* **second thing:** the actual one that's given by uplink

</details>

## Changelog
:cl:
add: illegal tech identifier trait. If you have this, you can check if an item has an illegal tech or not. RD, Scientist, lawyer, det, and captain have this trait.
/:cl:

### CODE REVIEW

**Comment by LodedDiper69** [comment]
Why would a scientist know what technology is legal but not the HOS?

**Comment by EvilDragonfiend** [comment]
> Why would a scientist know what technology is legal but not the HOS?

I wanted to make them ask people if these are illegal or not, and HoS & Securities should depend on other people.

**Comment by DarnTheMarn** [comment]
> Why would a scientist know what technology is legal but not the HOS?

I think it's more about knowing if it can be destroyed for illegal tech than knowing it's contraband. For example, as security you know that a stetchkin is contraband whether it spawns on an exploration ruin or somebody buys it with TC, it'll get confiscated either way. But scientists have a reason to know whether or not said stetchkin is "real" so they can research it.

**Comment by LodedDiper69** [comment]
Perhaps you should reword it into something more logical like "it appears it can be disassembled for illegal technology analysis" then, if detecting contraband wasn't the point here.

**Comment by PowerfulBacon** [comment]
This will make it so that any items in the uplink which are disguised are now entirely useless. If they could be discovered through meta before, it is now not meta and perfectly fine to have someone instantly work out if you are a traitor or not which is not the direction I think antagonists should be going. The main problem with this is that the flag is **only** applied to items purchased from the uplink which instantly outs you as a traitor.

**Pull request closed without merging**
