### PR TITLE
Optimize turf init slightly

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

Uses part of https://github.com/tgstation/tgstation/pull/73261

Saves 2s init

## Why It's Good For The Game

Faster init

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Carpet smoothing
image

Catwalks/lattices
image

yayy smoothing
image

Cameranet working
image

Adding a wall blocks things off.
image

</details>

## Changelog
:cl:
code: Slightly optimized turf init
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Can you include traces before and after this PR so we can see the comparison?

**Comment by itsmeow** [comment]
Removes 200,000 calls to sortTim, saving 1s init
image


Removes all init calls to get_open_turf_in_dir

Cuts mean time of get_adjacent_open_turfs by 10microseconds (saving 39ms)
image

Removes all calls to visibilityChanged during init

Reduces calls to chunkGenerated by 60,000, saving 109ms
image

Adds calls to bareMajorChunkChange, 23,851, costing 152ms (SELF time, not including time spent in chunkGenerated)
image

Total time cost of bareMajorChunkChange: 15.33 microseconds mean time, 23851 calls. 365ms

Total (master) time cost of visibilityChanged: 5.88 microseconds mean time, 136,518 calls, 802ms
image

NET SAVINGS of bareMajorChunkChange vs visibilityChanged : 437ms

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
what about turf/initialise as a whole?

**Comment by itsmeow** [comment]
Saves 2.07s (normalized to call count)
image

**Comment by PowerfulBacon** [comment]
Incredible

**Pull request merged**
