### PR TITLE
Common be gone

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
So im doing the bounty thing because the creator asked me to try
#7458 
- [ ] Removes common from headsets
- [ ] Rename Radio
- [ ] Walkie talkie channel
- [ ] Round spawn walkietalkie
- [ ] No mulitkeys besides syndie and com
- [ ]  #7675 
- [ ] dont touch the ai stupid
- [ ] Only the collaborative jobs get their own channel, others get civ
- [ ] Suit sensors slow

## Why It's Good For The Game
eh??? i like common but this seems fun to code

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
del: common
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
Do NOT wrire a PR title like that. Specify what you made in this PR.

**Comment by EvilDragonfiend** [comment]
Do NOT write a PR body like `eh??? i like common but this seems fun to code`, as it makes you look dumb about what you've made in this PR.

**Comment by EvilDragonfiend** [comment]
Do NOT post a PR as long as you made enough changes in your local, even as a draft. You've shown us that you post and close a PR that you couldn't make, and it is unnecesarily bloat the PR lists in the codebase.

**Comment by PowerfulBacon** [comment]
Be aware that this is the part of the bounty that will require the most work and will need constant redesigning as it is tested.

From the initial tests, I need to know any design changes to overcome some of the issues I brought up in the discussion.

Also note that there is still a very high likelihood that the radio part of the PR won't end up getting in.

**Pull request closed without merging**
