### PR TITLE
[PORT] Delete .dm files in _maps folder

### PR DESCRIPTION
**Pull request by Moccha-Bee**
## About The Pull Request
From the original pr:afaik nobody uses these in earnest, and they are noob traps that I've had to tell people to uncheck at least half a dozen times

From:https://github.com/tgstation/tgstation/pull/47912
https://github.com/BeeStation/BeeStation-Hornet/projects/2#card-29532448

## Changelog
:cl:
add: Removed .dm files from _maps folder
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
I use those...

**Comment by Moccha-Bee** [comment]
> I use those...

Was on the port list

**Comment by ike709** [comment]
@MarkSuckerberg Better solution would be to have all the FORCE_MAP defines in one file, with each one commented out and a comment at the top explaining what the define does. Probably in `_basemap.dm`.

**Comment by ike709** [comment]
In the meantime though, this is getting merged.

**Review by ike709 — CHANGES_REQUESTED** [review]
Missing multiz_debug.dm

**Comment by Moccha-Bee** [comment]
> Missing multiz_debug.dm

https://github.com/tgstation/tgstation/pull/47500
This one?

**Comment by ike709** [comment]
No. As in the `_maps` folder also contains the file `multiz_debug.dm` that you also need to delete.

**Pull request merged**
