### PR TITLE
Revert "Removes miasma, corpseflowers, and the rot component"

### PR DESCRIPTION
**Pull request by MCterra10**
## About The Pull Request
Title

## Why It's Good For The Game
The original PR was merged with very little justification.

The main reason hinged on its impact on server performance through the Life() proc, but the author did not provide any evidence to support this claim (such as profiler tests), nor have I personally heard any anecdotal evidence other than from Kapu themselves about lag caused by miasma.

The only other concern of note was regarding the economy issues caused by miasma farms. I don't believe this is a real issue, considering that the actual frequency with which miasma farms are built is incredibly low, in part due to their potential illegality by creating a workplace hazard, contravening space law, as well as the skills required in multiple departments to procure and sell the gas.

I am open to potentially adding a diminishing returns system to the sale of miasma if the maintainers are adamant this is a real issue (it's not), but I personally see it as unnecessary.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Pending

</details>

## Changelog
:cl: MCterra
add: re-adds miasma, corpseflowers and rot to the game
/:cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
It's been several months since the removal. You're going to need to actually justify the re-inclusion. Claiming that the original removal lacked complete justification isn't going to be enough.

**Review by Crossedfall — CHANGES_REQUESTED** [review]
Incomplete template, missing testing procedures, and lacking justification (see prior comment)

**Comment by MCterra10** [comment]
> It's been several months since the removal. You're going to need to actually justify the re-inclusion. Claiming that the original removal lacked complete justification isn't going to be enough.

The template wasn't included when I clicked the revert button, so I improvised. I'll update it and test this for you.

I think your argument that I need to rejustify this is ridiculous though, especially considering the original lacked ***any*** valid or verifiable justification, and I still don't even know how it managed to be merged in the first place. If I had of attempted to revert this immediately after the original PRs merging it would have simply been closed as a kneejerk revert.

**Comment by Dejaku51** [comment]
image

**Comment by Crossedfall** [comment]
There needs to be at least some justification on why it should be reverted now, three months after the fact. Especially since it's seemingly been a positive change in the best cases and a neutral change in the worst of cases.

**Comment by PowerfulBacon** [comment]
I didn't like the PR, I tried to shoot it down but I clildnt get any evidence that it wasn't bad for performance and that didn't even include the atmos updates it caused.

**Comment by utilbird** [comment]
### **Reverting near merge date:**
"Kneejerk moment, try in a few months"

### **Trying in a few months:**
"It's been several months since the removal. You're going to need to actually justify the re-inclusion"

**Comment by ToasterBan** [comment]
but, is miasma a good feature in the first place? it doesn't provide any RP, uses one of my most despised mechanics in the game (viro) and the frequency of miasma farms were way higher than you say

**Comment by ike709** [comment]
\> shows justification for miasma being terrible for performance
\> "There's no justification for removing miasma!!!"

🔑

**Comment by Mat05usz** [comment]
>  it doesn't provide any RP

So now every feature has to provide RP? 

Also, it kinda does, as it, or at least should, encourage people to clean shit because if they don't, diseases spread across the station.

> the frequency of miasma farms were way higher than you say

This is correct, I think it, if brought back, should be made far less profitable.

**Comment by MCterra10** [comment]
> > shows justification for miasma being terrible for performance > "There's no justification for removing miasma!!!"
> 
> 🔑

My brother in Christ, the only evidence regarding performance was from bacon, who found there was a moderate impact when there's a massive amount in air. I think "miasma being terrible for performance" is massive hyperbole. You definitely aren't going to notice any time dilation with it.

**Comment by MCterra10** [comment]
Does beebot not assign revert tags anymore?

**Comment by Archanial** [comment]
Needs to be talked within the team before merging this.

**Comment by PowerfulBacon** [comment]
> > > shows justification for miasma being terrible for performance > "There's no justification for removing miasma!!!"
> > 
> > 
> > 🔑
> 
> My brother in Christ, the only evidence regarding performance was from bacon, who found there was a moderate impact when there's a massive amount in air. I think "miasma being terrible for performance" is massive hyperbole. You definitely aren't going to notice any time dilation with it.

I didnt take into account atmospheric updates caused by dead body, they trigger turf updates every time it runs the miasma making.

**Comment by PowerfulBacon** [comment]
This PR will not be merged without some changes and strong justification for the good that miasma does for the game. There is nothing in the PR body that suggests anything about why this is good for the game. Why it's good for the game is where you should state why the additions of this PR are good, saying another PR lacked reasoning to be merged doesnt justify reverting it without any reasons.
There was a long conversation in development channels about that PR.

**Comment by MCterra10** [comment]
> This PR will not be merged without some changes and strong justification for the good that miasma does for the game. There is nothing in the PR body that suggests anything about why this is good for the game. Why it's good for the game is where you should state why the additions of this PR are good, saying another PR lacked reasoning to be merged doesnt justify reverting it without any reasons. There was a long conversation in development channels about that PR.

Please see the conversation in the development channel. This PR was opened because I believe there was a policy failure with the original PR, and it was merged with unresolved concerns and issues.

If this is going to be blocked by maintainers, I will just revert it downstream. Generally it's a waste of time to battle with bee maintainers when they have their heart set on something, regardless of how anyone else sees it.

**Comment by PowerfulBacon** [comment]
> There was no conclusion that miasma was contributing to significant lag in bacon's report, even when creating artificially large amounts of it for testing purposes

This is not true, I generously worded the reoprt in favour of miasma since I didn't want it removed, however the performance impact was pretty large without taking into account atmospheric updates required.
For clarity, it would be helpful if the points were summarised in this PR since there were multiple conversations about this in the development channel, the development channel is not public and the only point I can find that supports the reintroduction of miasma is that Austation has some features that use miasma.

**Comment by OverwatchVoice** [comment]
If one of the reasons for removal were the miasma farms, why not just remove the value miasma has, like on any other SSS13 server?

**Comment by ike709** [comment]
My tolerance for Terra's shit-stirring is reaching its limit.

**Pull request closed without merging**
