### PR TITLE
romerol changes

### PR DESCRIPTION
**Pull request by ghost**
This was sent from my Iphone.

### CODE REVIEW

**Comment by qwertyquerty** [comment]
What why

**Comment by ghost** [comment]
1. Its a virus that terns people into zombies, it should be
 virologist and cmo exclusive to begin with

2. took it off surplus because the fact anyone could get it from there was abit absurd imo, as its potentionally one of the strongest items on the item list(assuming the people you infect arent retarded)  and i lowered the price to compensate although i did mess up and ment to make it 18 TC instead of 16.

 This was sent from my Iphone.

**Comment by qwertyquerty** [comment]
Make it 20 and ill put it on vote

**Comment by hackerjsimon** [comment]
Yeah I like this idea alot  but i rather have it to be viro only as they basically have no traitor role items but either way its still a rlly good idea UPVOTED

**Pull request merged**
