### PR TITLE
[PORT] Cap on Supermatter Energy

### PR DESCRIPTION
**Pull request by park66665**
## About The Pull Request

This PR ports yogstation13/Yogstation#6829. Please take time to read the original PR.

## Why It's Good For The Game

This reduces the amount of annihilation in case of fusion on SM.

## Changelog
:cl:
tweak: supermatter has a power-ceiling of 1 million
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Damn, no more killing the entire station including silicons 😞

**Review by PowerfulBacon — APPROVED** [review]

**Comment by Moccha-Bee** [comment]
ngl fusion on the sm is best meme.
image

**Comment by park66665** [comment]
Xenomedes Kills Fun

**Comment by TotallyNotChief** [comment]
NOOOOOOOOO

**Comment by park66665** [comment]
e30 fusion is also on my hit-list. Don't be too surprised when that happens.

**Review by zeskorion — APPROVED** [review]

**Comment by TotallyNotChief** [comment]
stop bro.....

**Comment by TeomanTheGreat** [comment]
Do not merge this its cringe

**Pull request merged**
