### PR TITLE
Kilo Radification

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
Minor and major fixes to Kilo Station, mostly around Exploration. Details in the change log.

## Why It's Good For The Game
Improves the experience of the map.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image

image

</details>

## Changelog
:cl:
add: Added aft security and aft science area.
tweak: [Kilo] Changed the area of auxiliary security to aft security.
tweak: [Kilo] Replaced the Science maintenance hallway outside Exploration to be part of Science Aft. Maintenance now goes through a disposals like on Rad Station.
tweak: [Kilo] Copied the access of the front door of the aux base to the second set of doors inside.
tweak: [Kilo] Moved a light off a fire door by the Science shuttle.
tweak: [Kilo] Removed a double light in dorms.
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
I recommend changing the changelog to specify you're doing kilo changes since otherwise players wouldn't know

**Comment by MarkusLarsson421** [comment]
I'd like the balance, fix and removal tags taken off this PR as it came with the default CL.

**Comment by MarkusLarsson421** [comment]
Forgot I had to actually build it, it has been a while. 

Map works as expected when tested, added some pictures.

**Review by spockye — APPROVED** [review]

**Review by spockye — COMMENTED** [review]
image

not a huge fan of the wallpipes. other then that it looks good!

**Comment by MarkusLarsson421** [comment]
> not a huge fan of the wallpipes. other then that it looks good!

It used to be about the same before, should I try to fix it? It is a bit difficult.

**Comment by PestoVerde322** [comment]
The 4 way airlock is all set to have access only for atmos, maybe consider to make the one to atmos the only one with atmos access and the other 3 with generic engineering access (also add to the :cl: that you added a LOT of paper bins trought all the map).

**Comment by MarkusLarsson421** [comment]
> This zone is without APC and feels redundant.

Wait, did I do that in this PR? Because it currently has power in-game I think.

**Comment by PestoVerde322** [comment]
> > This zone is without APC and feels redundant.
> 
> Wait, did I do that in this PR? Because it currently has power in-game I think.


APCless zones have, for some god know why reason, endless power if they are set to have power. (also accidentally hit edit instead of reply, whoops)

**Review by PowerfulBacon — APPROVED** [review]

**Review by PestoVerde322 — APPROVED** [review]
Guess no other way around for those disposal pipes for now, I'll provvide a solution ASAP. Approved.

**Pull request merged**
