### PR TITLE
[PORT] simply ports better cone sprites

### PR DESCRIPTION
**Pull request by spockye**
## About The Pull Request
thats right. better cone sprites. thats about it
current cones are from 2014 or something, why use old crusty sprite, when we have this new and improved one? 

Ported from: https://github.com/tgstation/tgstation

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

wow.

look at that cone. 

you know. You could wear it. If you wanted to
image

</details>

## Changelog
:cl: Spockye 
add: Replaces current warning cone sprite, with a newer one
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
Man, can't imagine having lived all my life, even before SS13, without these cones.

**Comment by spockye** [comment]
image

heres the current one

**Review by PestoVerde322 — APPROVED** [review]
My god how horrifing the og one is

**Comment by Tsar-Salat** [comment]
> ## Changelog
> 🆑 Spockye add: Replaces current warning cone sprite, with a newer one

@spockye whos the... author? Its a port right?

**Pull request merged**
