### PR TITLE
Chat badges

### PR DESCRIPTION
**Pull request by PowerfulBacon**
Includes database changes.

## About The Pull Request

Adds in chat badges, a system for adding identifiers to chat!

## Overview

Badge ranks have 4 different variables assigned to them in the database.

<b>Badge Name</b><br>
The name of the badge. Duh.<br>
<b>Badge Group</b><br>
The group of the badge. If a user has multiple badges in the same group, only the one with the highest priority will be displayed.<br>
For example someone with 
<table>
<tr>
<th>Rank</th>
<th>Group</th>
</tr>
<tr>
<th>Admin</th>
<th>admin</th>
</tr>
<tr>
<th>Senior Admin</th>
<th>admin</th>
</tr>
<tr>
<th>Maintainer</th>
<th>development</th>
</tr>
</table>
The badges (Admin or Senior Admin) and Maintainer will be displayed.<br>
<b>Icon State</b><br>
The icon state that displays in chat. Pretty obvious.<br>
<b>Priority</b><br>
The priority of the badge. Higher priority badges will overwrite lower priority badges if they are in the same group.

### Creating a badge rank
Anyone with the R_PERMISSIONS right can create and edit badge ranks. Make sure you have this.
Go to Admin > Badges panel.
image
To create a new badge press 'Add New Badge'. This will bring up dialog options.
Enter the name of the rank. This must be unique, or it will not work.
image
Enter the rank group. If a user has multiple badges in the same group, only the highest priority badge will be displayed.
image
Choose a badge icon. These are generated based off of the icon_states in the badges.dmi file.
image
Enter the badge priority. Badges with a higher priority will be displayed instead of other ranks in the same group.
image
Your rank will now appear in the badges section.
image

### Removing badge ranks

Press the delete button next to the rank you wish to remove.
image
Press delete.
image
The rank no longer exists in the database.
image

### Assigning a badge rank to someone

Head to the badge holders tab.
image
Press 'Add badge to ckey' and enter a ckey
image
Choose a badge rank. These are based on the badges that have been created in the edit badges tab.
image
The badge rank has now been assigned and will show up in the chat.
image

### Assigning a badge rank to a permission group

To assign a badge rank to a permission group, simply name the badge rank the same as the rank name as it appears in the permission panel.
 Note 1: This is case sensitive.
 Note 2: This will only apply after admins are reloaded or after server restarts.
image

### Mentors

Mentors will automatically be assigned the badge named 'mentor' (Lower cased). This applies to admins too.
image

### Donators

Donators will automatically be assigned the badge named 'donator' (Lower cased).

### Deadmins / Stealthmins

If an admin is deadminned and just playing, their badge icon will still display, however an admin that is stealthminned will not have a badge icon appear.
image
image

## Screenshots
image

## Why It's Good For The Game

Adds in a new way to identify people in chat, even if they have no permissions.

## Changelog
:cl:
add: Chat badges
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
oh god oh fuck oh git oh hub

**Comment by PowerfulBacon** [comment]
Rebasing, this is a pretty old branch and git has fucked up since the LF thing

**Comment by PowerfulBacon** [comment]
Fuck you github, this is done but will merge conflict the second beebot makes a changelog because checkout wasn't working.

**Comment by ivanmixo** [comment]
make one for mentors or unbased

**Comment by PowerfulBacon** [comment]
> 
> 
> make one for mentors or unbased

There is one for mentors if it is setup

**Comment by Crossedfall** [comment]
I don't see the point of a "badge manager." Which leads me to ask why we would need database changes for this? Seems like it'd be a lot better to just match badges to roles.

**Comment by PowerfulBacon** [comment]
The database stores the badges, which icon they have as well as another table for any manual designations, for when people could need a badge but not a role. Badges with the same name as a permission are automatically assigned however

**Comment by Crossedfall** [comment]
If badges already match permissions then why have a table? The only valid reason I see for having a database table would be for people without permissions, but I don't see why we'd need that.

**Comment by qwertyquerty** [comment]
Donors could have a badge or something

**Comment by qwertyquerty** [comment]
@Crossedfall any more opinions on this?

**Comment by Crossedfall** [comment]
> 
> 
> @Crossedfall any more opinions on this?

What more are you wanting? I think the database bits should be pulled. Donors can be matched from the global list.

**Comment by Blueturbo47** [comment]
Mentor want me badge to make me look like cooler person

**Review by qwertyquerty — CHANGES_REQUESTED** [review]
Crossed is right

**Comment by Blueturbo47** [comment]
Also, I have a good idea for the beecoin shop, if this gets added we should have colored ooc text be purchasable.

**Comment by utilbird** [comment]
Reddit gold badge

**Comment by Blueturbo47** [comment]
ADD THIS ALREADY

**Comment by utilbird** [comment]
*cry

**Pull request closed without merging**
