### PR TITLE
Increases midround morph chance

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
Increases the morph midround event chance to 10 and puts it on the Ghost Visible Antagonists list.

## Why It's Good For The Game
Probability for Morph is now equal to Nightmare. Additionally, it would show up in the living creatures list as "morphling" so no real point in it not being ghost-visible.

## Changelog
:cl:
tweak: The Morph midround event has been increased in probability and is now equal to Nightmare. 
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
It's low because it's incredibly annoying to have a mob that can eat the entire armoury before anyone even notices it, and can vent crawl.

**Comment by PowerfulBacon** [comment]
eh they are kind of weak though especially compared to the likes of swarmers and every other midround

**Comment by francinum** [comment]
Bad idea. 🔑

**Comment by PowerfulBacon** [comment]
I agree with franc, I think 10 is a bit too high for morph. Maybe 5 would be better

**Comment by Ivniinvi** [comment]
Reduced to 5

**Comment by qwertyquerty** [comment]
I think it's fine as is :key:

**Pull request closed without merging**
