### PR TITLE
Staffwho and Mentorwho minor changes.

### PR DESCRIPTION
**Pull request by CydiaLamiales**
## About The Pull Request
Merges the code for Staffwho and Mentorwho (it was literally copy-pasted).
Adds 'an' to ranks in Staffwho where needed.
Adds logging to Mentorwho as well as notifying admins about it.

## Why It's Good For The Game
Seeing 'x is a Admin' was somewhat painful, so this fixes that. Also prevents people from cheating the system to check for current non-stealthed admins without that being logged by using Mentorwho.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
'an' being applied when needed

image
Staffwho and Adminwho messages

image

</details>

## Changelog
:cl:
fix: Fixed staffwho using "a" wrongly in the rank text.
code: Merged Staffwho and Mentorwho's code

/:cl:

### CODE REVIEW

**Review by Archanial — DISMISSED** [review]
Remove mentorwho altogether

**Comment by CydiaLamiales** [comment]
But why

**Review by PowerfulBacon — APPROVED** [review]

**Comment by itsmeow** [comment]
mentorwho was already logged

**Review by itsmeow — APPROVED** [review]
Pretty much exactly what I wanted to do in my logging Who PR without the logging Who part. Looks good and fixes some bad grammar.

**Pull request merged**
