### PR TITLE
Fix laser gatling gun

### PR DESCRIPTION
**Pull request by Rukofamicom**
## About The Pull Request

* Fixes a divide by zero error causing the gatling laser to not play the "laser go pew" sound effect when lasers came out
* Completely overhauls almost all of the mechanics behind the gatling laser that I didn't even know were present (and broken) until looking into fixing the silent laser sounds
  * Gun now properly plays its sound for spinning up before firing, and delays the initial shots while it spins up
  * Gun continually plays firing sounds while it is being fired (although I elected not to use the given firing sounds for this, because the sound clip was too long and also mismatched the gun due to making ballistic gunfire sounds)
  * Gun now properly plays a spin down sound effect when it stops firing and goes on a literal cooldown period based on how hot it was. 
  * Overheat mechanics have been totally refactored from scratch
    * Every consecutive shot fired increases heat by 2
    * Gun overheats when it reaches 80, causing it to forcibly click off and spin down.
    * Gun goes on cooldown equal to its current heat in deciseconds, with a minimum cooldown time of 2 seconds and a maximum of 8 seconds due to the cap of 80 heat.
* Additionally removed the emag functionality on the gun for reasons outlined below. 

## Why It's Good For The Game

Most of the time these changes are going to be completely and utterly irrelevant to the game. This is a weapon that only exists if an admin spawns it in, and there will almost never be a round that it's a good idea to spawn it in. *However, on those exceedingly rare rounds, this will now be a much more immersive and bad-ass weapon than it currently is*.

As for the emag functionality:
1) This gun is already excessively overpowered and doesn't need an emag effect to make it even moreso. It already borders on so powerful that admins will rarely see justifiable reason to introduce it to the round, I don't see a reason to keep a more powerful mode available as an option on the weapon.

2) The emag functionality was largely broken in the literal sense - it attempted to make the gun fire 5x faster, but the gun already fires as fast as the code allows it so this function was broken. It additionally makes the gun fire silently - not because of some bug but because it changes the sound to `null` for no conceivable reason. It increases bullet spread into a 60 degree cone which... without the increased fire rate is just very bad. And finally it removed the overheat mechanics 

## Testing Photographs and Procedure

Shown:
* Fire and stop early, with minimal cooldown
* Fire until forced overheat with maximum cooldown
* Spinning up without firing not triggering any cooldown (no spindown sound effect)

https://user-images.githubusercontent.com/9547572/224371124-469edc99-594b-43a4-9161-e5ee2c600a04.mp4

## Changelog
:cl:
fix: Fixed the laser gatling gun's sounds and intended functionality. It is still only available via admin spawn.
/:cl:

### CODE REVIEW

**Comment by Rukofamicom** [comment]
Still have a couple of minor issues to iron out with it, but it's almost there.

**Comment by Rukofamicom** [comment]
video updated to match the bugfixed version

**Comment by BriggsIDP** [comment]
I thing it would be really cool to slow down the first few shots, before reaching full firing seed. Kind of like this: youtube.com/watch?v=RMPx2sR_gDI

**Comment by Rukofamicom** [comment]
Video updated again to match current iteration after incorporating the above request and getting approval from them. 

> I think it would be really cool to slow down the first few shots,

**Comment by benbot16** [comment]
> Does this affect the syndie simplemobs with gatling? They're so fun when they go full ballistic postal mode shooting mega fast and MELTING everyone on EOR bus, since for the time being(maybe can be implemented with shuttlecruise new ruins/ships as an option by Bacon) they're not in-game and are only adminbus spawn i'm wondering if this affects them or they stay on psycho mode

Those are handled by simplemob code, so unless that specifically is changed it won't have an effect.

**Comment by Rukofamicom** [comment]
There is nowhere in the game that this weapon is referenced except for one away mission where it spawns on a corpse

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
