### PR TITLE
Fixing TGS's send2chat implementation

### PR DESCRIPTION
**Pull request by Archemagus**
## About The Pull Request

After 4 years TGstation fixed that. So you can fix that too
Source: https://github.com/tgstation/tgstation/blob/master/code/__HELPERS/chat.dm#L38

## Why It's Good For The Game

You can use it to make fancy public announcements about Round Start/End

## Testing Photographs and Procedure

N/A

## Changelog
:cl:
code: Updating and fixing send2chat proc. It means nothing for you kiddo
/:cl:

### CODE REVIEW

**Comment by Archemagus** [comment]
Even i can make those announcements into that PR if you want.
Actually i making that for NSV. But because it's "upstream" issue - here, your copy of that fix

**Review by Archanial — DISMISSED** [review]

**Review by Crossedfall — DISMISSED** [review]
If you're making the change, port the full thing including the documentation additions.

**Review by ike709 — DISMISSED** [review]

**Comment by Archemagus** [comment]
> If you're making the change, port the full thing including the documentation additions.

Okay.
That proc now is fully copied from TG (it now has more args on input, but other code has no need to be updated because `admin_only=FALSE` is fine for all usage cases)

source code:

https://github.com/tgstation/tgstation/blob/master/code/__HELPERS/chat.dm#L38

Actually i have no idea what you want from me, @Crossedfall, I hope, I did all things right

**Comment by Crossedfall** [comment]
> Actually i have no idea what you want from me, @Crossedfall, I hope, I did all things right

- https://github.com/tgstation/tgstation/pull/51229
- https://github.com/tgstation/tgstation/pull/52601

I believe these are the only two relevant PRs that you should be porting. Although it would probably be worth checking TG's PR list and/or git-blame to see if any other changes are needed here.

**Pull request closed without merging**
