### PR TITLE
Stun resistance from working out

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Saw a video of police trying to fight a really buff guy and that gave me an idea. Exercising will now provide a temporary status effect which will reduce the amount of stamina damage that you take. This means that there is now actually a reason to exercise beyond having 20 minutes of heart attack protection. The status effect will show a percentage of how exercised you are, at 100% exercise you will have 50% more resistance to stuns, with that number decreasing over time.

You can gain up to 50% stun resistance, each individual exercise grants a 2% bonus, and every second you lose 0.05% of your stun resistance. This means for every individual exercise you do, you will gain 40 seconds of stun resistance, which stacks up to 16 minutes of resistance.

This also adds cleaner code for status effect merging, which will be used in the bleeding PR.

## Why It's Good For The Game

Makes exercise actually have an effect, and introduces a way to gain natural stun resistance for a short time. Allows people who are expecting to get into combat have an edge, without actually nerfing stamina weapons to a point where they are useless. Also adds variation in combat, since some people may be harder to take down than others.

Good luck to the wardens when your prisoners decide to work out instead of work for a way out.

## Testing Photographs and Procedure

image

image

image

## Changelog
:cl:
balance: Exercising now provides temporary stun resistance.
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
It.. really doesn't make much sense, if i follow your IRL example, said dude already had the muscle mass due to training and was probably not exhausted, therefore he has energy to fend off or fight back or whatever you saw plus size difference blabla.

Also if i just finished working out my muscles will, naturally, be fatigued and sore, which in-game would mean i should be **more** susceptible to stamina damage rather than being more resistant, if anything it's after some reasonable time passed that the muscles recover and get stronger and **then** it would make sense to have a temporary stun resistance since they've rested and are "stronger".


I don't know the exact values of stamina armor across every item but having an overall 50% baseline stamina resistance for 16 minutes, even if it decreases with time is insane, anyone who adds any other stun resistance modifier armor(heretic robe, hardsuits, sec gear, etc) would dunk on whoever they want based on their equipment at hand, not to mention baton will be rend useless considering they'll quickly run out of charge and it'll reinforce escalation to Lethals according to SoP, if deemed necessary.

I do believe it's silly and not at all inmersive, leaving IRL comparisions aside it would make an officer go "????" When they don't go down after a full discharge of a stun baton, which would make them assume they have an adrenal implant, changeling or just go " .S we can't stun them proceeding with lethals " or should the officer go ".S HE JUST WORKED OUT I CAN'T STUN THEM HOS!" It's nonsense

Also going back a bit for a second..  A well placed taser shot IRL can make any big boy fall to the ground given it makes you lose control of your muscles so when you're in-game being attacked by a weapon that's supposed to electrify your body to ''stun you" it doesn't make sense for you to just "tough it up" because you just bench pressed a bit. And since we don't have Tasers(Except for whatever thing the HoS weapon has) the Baton and disabler have that function in the game.

There's also...no downside to it, they don't become more fragile after, walk slower, etcetera. They can just wait the 16 minutes and go again or if there's no cooldown constantly refresh it , people are just gonna rush the Gym in genpop or recreation room before each fight and while i'm to assume the officers won't metagame ".S John Greytide is going overdrive at the Recreation Room, prepare lethals" the average gamer antag will take it without a second doubt, specially since it doesn't have any risk the only one is that you might get  lethal'd but that can already happen. 

I can predict some scenarios:

-Antags that rely on armor(Loud heretics for example) will have an easier time defeating Security on non-red alert situations since traditional weapons won't work as effectively and their baseline gear(blade, traitor gear) will just get the upperhand in combat

-Officers will start carrying two baton's(Some already do though) or start immediatly seeking better batteries which is something you rarely see since they don't need it as much but meta will shift to that, also.. as is said earlier it's very much not enjoyable to **feel** like your equipment doesn't do anything, similar to what i've talked with you in the past with the first iteration of holstering delay, no one enjoyed not being able to press click and wait for a cooldown, same logic here.

-Sleeping Carp would be absolutely insane, if they have sec armor or something similar + working out + deflecting laser shots what the heck is an officer supposed to do? The antagonist can already **BYPASS** the only way to defend against the aggresive grab by control-clicking their target so the Shield becomes useless so.. really, what are they supposed to do if they can chain-stun/chain-make them drop their items(i've seen players do that to three officers in a row so even going in numbers won't help as much as you think and any lone officer is good as dead, even with a shield,which it's the only way to fight them(even knowing they can bypass the shield)

- Genpop 
Well, i mean sure.. the Warden has lung punch and the ?shotgun alongside other crowd control tools(even if Flashbang is nerfed and the pepperspray nade is not that effective) so i can just foresee more deaths/crits and a lot of sentences re-started, not to mention the prisoner event will be.. bleh, just more chaotic and deadly than what already is.


Dunno if i'm an officer walking with my basic gear and suddenly a greyshirt comes to me, toolbox or axe in hand and i start clicking them until my stun baton is out of battery and they don't go down it would really make me go.. ????

You're giving resistances to every crewmember without any downsides and without compensating Security gear for it alongside the inmersion breaking i just think this does not add to a fun gameplay loop.

I would greatly appreciate a Testing Evidence video of someone being hit with a baton after working out with no gear, sec gear and something with high stam resistance like an heretic armor or syndie hardsuit.

Lastly, i do find interesting to seek variations in combat even if everyone knows it's hard but this ones has too many holes in it which i hope i could've make my points come across.

**Comment by PowerfulBacon** [comment]
High stam resistance armours from loud antags aren't meant to be dealt with via stam weapons. I want certain individuals to be difficult to take down and require cooperation from multiple members of security.

**Comment by Fronsis** [comment]
> there have been no real ways to effectively become resistant to stuns and security can relatively easily deal with prepared threats in 4-5 hits at times which should not be the case.

I mean...While they might not be widely used for example, the traitors, have access to Adrenals, Chamaleon armor, Hardsuits, Changelings havw adrenals, Heretics have their Jaunt(which we already spoke about it multiple times), non-ability reliant antags have chems and stuff like hulk mutators

What is a "prepared threat"? That is very vague, a prepared threat for me is an heretic with robes, a cultist with armor, a traitor with guns and armor, someone with a Hardsuit with a jetpack, a miner with x50 heals and bs crystals, a botanists with 50 explosive lemons and acid tomatoes

Those are "prepared threats'' and most of the times the only ones that are the mostly affected by being baton'd and brigged are the traitors with TC, because their items gets secured and not many bother to break in

The heretic? If they didn't commit a capital at max they'll be 15 minutes and they can craft blades and runes on genpop

The miner? Just buys more and steal from the lathe

The botanist that might be demoted? They have public garden and use a stash of stored seeds or RP their way with their old botany co-worker

A fight might end in five batons, sure. Sometimes it's a skill issue, sometimes it's a hard fight but it's not the end for the antag.


> I want certain individuals to be difficult to take down and require cooperation from multiple members of security.

Who? John Mcgreytide that just pressed click on a Gym machine and they now have 50% decaying stam resistance which they can always do with no downside and constantly rushes Sec with toolboxes and axes? Because the ones that are already difficult to take down are... well, already difficult to dealt with.


Now Security needs to waste almost an entire baton charge for an obnoxious Clown that just pressed click on a machine while Dynameme's throwing a nightmare, pirates, abductors and the other roundstart antags.

> High stam resistance armours from loud antags aren't meant to be dealt with via stam weapons


Correct, except that Security is encouraged to first try non-lethal arrests, the majority of Officers would still go with baton and disablers as a courtesy against the antag instead of first encounter being lethals, with a few exceptions of course.

Again i bring up Carp users, you're obviously not going to use any range weaponry.. what do you have left? Baton and shield!

Oh.. but they can bypass your shield block thanks to a code moment

Okay doesn't matter i'll go for a baton!

Oh.. they have sec armor and they started the fight with 50% stam resistance, aaaand he just stungrabbed me and my teammate.. 

Okay maybe i'll try a flashbang!

Deafness? Oh they bought a chamaleon bangproof and blindness is negligent

Pepper spray? Oh.. they have a mask

E-bola? They can take it off in three seconds

Uh... billy..club? You'll be stunned again and you'll drop it

The biggest winner with this is anyone with Carp alongside any of the early "loud antags'' that manage to get kills before sec is fully prepared, like Heretics or a traitor that bought armor.

So that's why i would really like to know who is this supposed to help, i understand you've been aiming to make combat "last longer" instead of being decided by one-tap baton stun or 1 flash, but this.. open-for-everyone 50% decayin stam resistance over 16 minutes doesn't convince me, i'd rather see a rebalance on the already stam-resistance items i've mentioned above.

Like i can already imagine a 4-5 team of Revs working out before storming the two officers chatting on the Hallway, just for a mere click they've all earned a high amount of resistance to whatever the unaware officers might have on their kits instead of something more engaging on RP like bribing the chemist/geneticists or converting them to make the stuff for them, it just.. skips stuff for an instant positive without any downside whatsoever.

**Comment by PowerfulBacon** [comment]
It takes a significant amount of time to reach the maximum level of exercise, it takes 1000 individual exercises to reach 50% (Punching bags give 1, weight machines give 10, swimming 25 tiles gives 20)

**Comment by Fronsis** [comment]
Then at that point only people that truly want to min-max would grind it and for the rest it would be negligible stam resistance, since they would never reach any relevant stat, unless someone is permabrigged or a prisoner event spawn, though for anyone that's up for 15 minutes in brig 1000 clicks might be doable(and..  a very bleh gameplay loop, at least the rep machine is more automatic)

Still got my question about your reply above.

**Comment by PowerfulBacon** [comment]
If the question is about "prepared threat", then yes I would say that your definition is accurate. Anyone who is prepared to fight security should be a challenge to deal with, enough for officers to consider calling in backup before dealing with them (although while that isn't easy right now, it will likely be improved in the close future). If you have any other questions, then if you clarify them I will be happy to answer them. I am waiting for use before adjusting the specifics, it will likely end up being brought down to a more reasonable 30% resistance if 50% is too high.

**Comment by Fronsis** [comment]
Fair enough then! 

I was thinking you might wanna check the uh.. audio levels? Of the punching bags, i remember them being a little loud and if someone's gonna go psycho mode on them  i think the prisoner/s/Warden/Officers would appreaciate not hearing a loud cookie clicker non-stop

**Comment by PowerfulBacon** [comment]
Yes, it shows how strong someone is when examined. It will show "They look strong", "They look very strong", or "They look exceptionally strong"

**Comment by JixS4v** [comment]
Me likey very funny

**Comment by DarnTheMarn** [comment]
I will say there is a fine line between making stun weapons a bit weaker so you don't get disablered or batonged immediately and making it so that security just shoots everyone and doesn't even bother with stun weaponry even if that breaks the rules. That being said, it would be a good idea to add a way to build the punching bag and dumbbells somewhere else so people can't meta the fact you stayed in dorms working out for 5 minutes.

**Comment by BlueHNT** [comment]
Doesn't working out give you a small heal over time already?

**Comment by PowerfulBacon** [comment]
It gives you 20 mins of no heart attacks

**Comment by BlueHNT** [comment]
Splendid

**Comment by JixS4v** [comment]
merge this, i wanna become the boss of this gym

**Comment by ColonelOrion** [comment]
This is so cool and I love the idea

**Pull request merged**
