### PR TITLE
Fix heads traitor rolls

### PR DESCRIPTION
**Pull request by yorii**
## About The Pull Request

I timed this

## Why It's Good For The Game

Decided by admin vote.

## Changelog
:cl:
tweak: tweaked a few things
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
Why is clown protected from undercover agent

**Comment by Flakkyboo** [comment]
Bruh wtf no.
Traitor hop is the shit why.
Admin vote can suck it

**Comment by Archanial** [comment]
Who cares about admin vote. 
This change is bad

**Comment by yorii** [comment]
> Why is clown protected from undercover agent

Dude I have no idea, it was already like that, I should remove him from that list right?

**Comment by Mick1299** [comment]
Traitor HoP bad, traitor everything else good

**Comment by Flakkyboo** [comment]
Traitor hop fine. All heads got their special shit that's useful when traitor.
Jaws of life
Teleport vest
Hypo
Id acess

And id acess isn't as powerful when you consider you could just emag or you could just learn the test

**Comment by St0rmC4st3r** [comment]
In that case give them mindshield for lore reasons, I guess?

**Comment by PowerfulBacon** [comment]
This is a config option that needs enabling which will automatically add heads to the list if turned on.

**Comment by PowerfulBacon** [comment]
Nevermind, apparently thats assistants, but you should add it as a config option and have.
restricted_jobs += head_jobs if the config flag is set, using the define for head jobs as the thing

**Comment by PowerfulBacon** [comment]
> 
> 
> Why is clown protected from undercover agent

Clowns can't shoot guns properly

**Comment by Flakkyboo** [comment]
And why just bar them from traitor.
This doesn't bar them from gang or cult or even devils.

What other reason is there to make this change than heads are more powerful compared to other crew.

Feels like arbitrary role gating. don't wanna be a traitor? be a head. Traitor heads are extremely fun to play

**Comment by PowerfulBacon** [comment]
The reason for this (which wasn't put in the PR) is that heads are expected to be the head of a department, and someone that is competent and a leader. Having them as antag makes little sense from an RP and game perspective since if the person giving orders is giving bad orders, how can you trust heads in general, and then if you can't trust that they are properly teaching you and not assasinating why would you follow their orders, making them a normal member of the department with some extra gear.

**Comment by Flakkyboo** [comment]
That's a better reason than the pr is giving. i understand where you are coming from even if i don't necessarily agree. 
Not being an antag though isn't going to make the head good at his job as we all know some heads do kinda just eat glue.

I wonder though if this could be a specifically mrp change, i dont see people listening to heads much on lrp traitor or otherwise.

"if you can't trust that they are properly teaching you and not assassinating why would you follow their orders, making them a normal member of the department with some extra gear."
I will say on this part though. assuming the heads are traitors imo is akin to metagaming.
being suspicious of orders is fine but outright ignoring heads orders becuase you assume they may be a traitor shouldnt be something a person does

**Comment by PowerfulBacon** [comment]
> 
> 
> That's a better reason than the pr is giving. i understand where you are coming from even if i don't necessarily agree.
> Not being an antag though isn't going to make the head good at his job as we all know some heads do kinda just eat glue.
> 
> I wonder though if this could be a specifically mrp change, i dont see people listening to heads much on lrp traitor or otherwise.
> 
> "if you can't trust that they are properly teaching you and not assassinating why would you follow their orders, making them a normal member of the department with some extra gear."
> I will say on this part though. assuming the heads are traitors imo is akin to metagaming.
> being suspicious of orders is fine but outright ignoring heads orders becuase you assume they may be a traitor shouldnt be something a person does

I made a PR for it as a config option and enabled it on MRP only

**Comment by yorii** [comment]
Neato, yes this was always only meant for MRP only, I can close this?

**Pull request closed without merging**
