### PR TITLE
Fixes some issues with the config

### PR DESCRIPTION
**Pull request by MCterra10**
## About The Pull Request
Removes the mob limits from config.txt - duplicate of game_options.txt
Removes DEFAULT_VIEW_SQUARE from config.txt because not only is it a duplicate of DEFAULT_VIEW, it's not even named correctly and gives an error every launch for unknown option

## Why It's Good For The Game
Having a config_error.txt every time you start your server isn't good. Has nobody noticed?

## Changelog
:cl:
fix: fixes config
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
It'd be cool if you removed the dupes from the Sage config too.

**Comment by Crossedfall** [comment]
Noticed but hadn't mirrored the proper changes over yet. Appreciate you pushing that through.

**Comment by MCterra10** [comment]
Oh yeah I forgot you weirdos need two seperate config files. One sec

**Comment by MCterra10** [comment]
@Crossedfall austation configs aren't tied to the github. So the changes are made, they're just not reflected on the repo

**Comment by MCterra10** [comment]
Oddly the sage config.txt didn't have a DEFAULT_VIEW_SQUARE entry

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
