### PR TITLE
Change of chat colors (medical and service)

### LINKED ISSUE #625: The light grey text of the medical radio channel is extraordinarily harder to read against the white background. Is it possible to recolor it?
Title says it all. Light grey text on a white background is hard to read quickly. Recoloring it would be make it much more helpful.

### PR DESCRIPTION
**Pull request by TheGreyDiamond**
## About The Pull Request
Changed the colors of medical and service radio. Medical is still blue, but darker. Service radio is darker too.
Fixes #625 

## Why It's Good For The Game
The medical radio can be read easier. The service radio won't look like general anymore.

## Changelog
:cl:
tweak: changing colors of medical and service radio
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
will this affect dark mode?

**Comment by TheGreyDiamond** [comment]
I don't know didn't test, but it should affect all radio colors (no matter what mode).

**Comment by PowerfulBacon** [comment]
Can you give a screenshot of the new vs the old?

**Comment by TheGreyDiamond** [comment]
Sure: [Before](https://thegreydiamond.de/cdn/img/a001/before1.png) [After](https://thegreydiamond.de/cdn/img/a001/after1.png)
(I don't know how to make them appear in Github, sooo)
**Before:**
before1
**After:**
after1

**Comment by ike709** [comment]
Show a pic of darkmode.

**Comment by TheGreyDiamond** [comment]
Sure: Here is the screenshot of the dark mode (or [Click!](https://thegreydiamond.de/cdn/img/a002/afterDark.png))
afterDark

**Pull request merged**
