### PR TITLE
[PORT] Randomized Lavaland Atmos

### PR DESCRIPTION
**Pull request by Moccha-Bee**
## About The Pull Request
Ports Randomized lavaland atmospherics.

From: tgstation/tgstation#44427

## Why It's Good For The Game
Miasma farming.

## Changelog
:cl:
add: Randomized lavaland atmos generation.
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Once the checks pass, I would like to testmerge this for performance reasons.

**Comment by Moccha-Bee** [comment]
Interesting... I tested it twice and worked fine.

**Comment by MarkSuckerberg** [comment]
Just try pushing an empty commit, make the checks restart as I don't see any errors besides it stalling

**Review by MarkSuckerberg — APPROVED** [review]

**Comment by Kerbin-Fiber** [comment]
bad travis

**Comment by Moccha-Bee** [comment]
so did i do anything wrong?

**Comment by zeskorion** [comment]
>porting a cool feature just to powergame with it

Based but cringepilled


we port this and miasma will become easier to produce, necessitating a drop in price

**Comment by Kerbin-Fiber** [comment]
Implying that atmos techs or the CE or anyone with a RCD is knowledge able or willing to go to lavaland for price-y gas

**Comment by Moccha-Bee** [comment]
I could lower the price of miasma well atleast try to.

**Comment by Moccha-Bee** [comment]
On mrp all cargo techies would start the miasma farming.

**Comment by zeskorion** [comment]
> Implying that atmos techs or the CE or anyone with a RCD is knowledge able or willing to go to lavaland for price-y gas

qm and miners can access aux base, which has an RPD, and can easily hack the autolathe for an RCD

**Comment by Kerbin-Fiber** [comment]
True, I suggest dropping the price, relative to the amount of moles lavaland would ha have if it landed miasma as a gas

**Comment by zeskorion** [comment]
> True, I suggest dropping the price, relative to the amount of moles lavaland would ha have if it landed miasma as a gas

the fact miasma has such a price is a meme anyways. i get trit, but not miasma

**Comment by Kerbin-Fiber** [comment]
I guess Centcom just likes shit a lot.

**Comment by MarkSuckerberg** [comment]
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated
```
Hmm

**Comment by Moccha-Bee** [comment]
The bot had a brain aneurism.

**Comment by MarkSuckerberg** [comment]
Welp

**Comment by ghost** [comment]
how about no

**Comment by ike709** [comment]
I'm pretty sure we're missing at least one follow-up PR.

**Comment by Kerbin-Fiber** [comment]
@Moccha-Bee try and find the follow up pr so this can get ported

**Comment by Moccha-Bee** [comment]
Talked with a few people in the coder chat of TG and dint find anything about a follow up pr to it. Nor in the git.

**Comment by ike709** [comment]
@Moccha-Bee I'm pretty sure they reduced the value of miasma as a result of this PR. Or maybe it wasn't merged, I don't remember.

**Comment by Moccha-Bee** [comment]
> @Moccha-Bee I'm pretty sure they reduced the value of miasma as a result of this PR. Or maybe it wasn't merged, I don't remember.

I will do a follow-up pr to lower miasma prices then.

**Pull request merged**
