### PR TITLE
Hive Reclamation [WIP]

### PR DESCRIPTION
**Pull request by ghost**
#1781  About The Pull Request

Hive Reclamation adds onto the Apid species, steering it close towards its original goal.

## Why It's Good For The Game

I'll admit, apids were a half-ass introduction. They need some love.

## Changelog
:cl:
tweak: Tweaked apids.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I don't really want to see comms filled with 
Drone 415 says, "hello"
Drone 183 says, "hows it going"

**Comment by ghost** [comment]
> I don't really want to see comms filled with
> Drone 415 says, "hello"
> Drone 183 says, "hows it going"

They're an alien species of sentient bees. What else would they make their naming system based on?

**Comment by PowerfulBacon** [comment]
> 
> 
> > I don't really want to see comms filled with
> > Drone 415 says, "hello"
> > Drone 183 says, "hows it going"
> 
> They're an alien species of sentient bees. What else would they make their naming system based on?

They are sentient though, so would have actual names especially if they have been integrated with humans, makes sense they would have human names if it makes it easier for everyone to understand them

**Comment by WhyIsCaeciliusTaken** [comment]
Oh boy I can't wait for every apid to be named "Drone 42069"

**Comment by ghost** [comment]
That's like saying Hispanics would give up putting the last names of every single one of their ancestors in their full name. They have their naming standards based around a _hive_. They are sentient _bees_.  People who care enough to make lore-friendly names won't exactly care about the fact that their name is unique via a number.

**Comment by PowerfulBacon** [comment]
> 
> 
> That's like saying Hispanics would give up putting the last names of every single one of their ancestors in their full name. They have their naming standards based around a _hive_. They are sentient _bees_. People who care enough to make lore-friendly names won't exactly care about the fact that their name is unique via a number.

They aren't bees, they are bee people.
They are human-sized, live in a human-based society, genetically engineered and created by humans, have human-based arms

**Comment by Dingo-Dongler** [comment]
I do love racially different names, and another species that's just moth/squid puns would be kinda lame. Perhaps bees could have names like their roles on the station, because they've progressed past just workers/drones.

**Pull request closed without merging**
