### PR TITLE
Admin verb reorganization + extra

### PR DESCRIPTION
**Pull request by TheTrigg**
Decided to copy paste [this PR of mine](https://github.com/DeltaKris/New-Era-Station/pull/20) for y'all.
I'll also copy paste the PR text. Here goes:

I guess no one ever bothered to organize them before.
Seriously.
I REFUSE to believe they were like that for a reason.

Here's the pattern I tried to follow:
 - Admin: Actual administration - Player Panel, Banning Panel, etc
 - (new) Adminbus: Interactions with the game - spawning items, jumping around, combo HUD.
 - Fun: Mostly the same, just moved some explosion verbs to it.
 - (new) Round:  Control of the "flow" of the round - Events, shuttles, checking and creating antagonists.
 - Server: More actually server related - A good chunk of its verbs were moved to Round.
 - Special Verbs is gone; it was mostly a "if you dunno where to put something, put it here" category.

Mostly didn't touch the others.

## HERE'S SCREENIES:
image
image
image
image
Slightly outdated now; Combo HUD and Check AI Laws have been moved back to Admin, Reboot World has been moved back to Server.

## Changelog
:cl: Trigg
admin: Admin verbs and tabs have been moved and reorganized all around. You should find each tab to be more intuitive and less cluttered with unrelated verbs.
admin: "Delay round end" and "Check Teams" are now admin verbs, instead of options under... Check Antagonists. Seriously, why were they like that?
admin: The "Ticket Manager" verb now works. It's... Identical to the "Open Ticket Browser" verb.
admin: An old and mostly unknown admin verb now features logging.
admin: You can now edit team objectives from the team panel. No more removing and adding!
/:cl:

### CODE REVIEW

**Comment by Lagomorphica** [comment]
are you a god?
an angel?

thank you.

**Comment by CasualKelly** [comment]
I like it a lot. Been trying to switch to hand jamming verbs, but still lean heavily on clicking in tabs. Should offer more clarity for new admins as well.

Any verbs that I could think of being in different panels has arguments for being in either, and don't feel strongly enough to have them in one vs. the other.

**Comment by TheTrigg** [comment]
Thanks y'all. Glad you like em.


btw I go by Trigg#0475 over Discord, in case anyone wants to ask a question or something.

**Comment by OceanFish1** [comment]
It needed to be reorganized a long ago. Thank you for this. 
image

**Comment by PowerfulBacon** [comment]
Check Antagonists being in round is painful

**Pull request merged**
