### PR TITLE
v2 Defib rework, organ damage effects, deja vu and muscled veins port

### PR DESCRIPTION
**Pull request by VictorVow**
Same as [previous PR](https://github.com/BeeStation/BeeStation-Hornet/pull/1289) except also includes:
- Fix to ensure IPC organs don't decay
- Fix to ensure MMIs don't decay
- Formaldehyde prevents post mortem organ decay.
- Epinepherine pens now contain 3u formaldehyde preservative.

## Changelog
:cl:
add: The deja vu effect (previously only used by rewind camera) now resets all your limbs and damage to the point it was added after 10 seconds (as well as the original position reset)
add: The deja vu effect cannot resurrect the dead, but will heal their corpse
add: New limbs fall off, old ones re-attach
add: Regenerative sepia cores add a deja vu effect before healing instead of a timestop
add: The rewind camera rewinds 2 times to distinguish it from the regenerative core
add: Androids, skeletons and zombies no longer metabolize reagents. As such they no longer benefit from healing reagents, nor are affected by poisons and toxins.
add: These species are now also immune to any other form of toxin damage.
tweak: Milk now also heals burn damage for skeletons.
add: Added a new advanced surgery, Muscled Veins: it makes the patient able to survive without a heart.
add: Organ Smartfridges! Store your organs safely. Upgrading the matter bin will give it the ability to heal organs held within- though this does not repair organs that are currently failing, however.
add: Lobectomy! Not lobotomy, but cuts out a damaged lung lobe to make its performance passable. Restores a lung to working order if it was too damaged to work before, but can only be done once. The lobectomy step has a 95% chance of success, so use some form of sterilizer to ensure you don't accidentally get blood inside your patient's lungs!
add: Coronary Bypass! Restores a heart to working order if it was too damaged to work before, but can only be done once. Both incising the heart and grafting the bypass have a 90% chance to succeed, and failing them will cause heart damage and massive amounts of bleeding- so be sure to work with ideal conditions, proper tools, and sterilizer!
add: Organs now decay when not in a living host
add: Severe heart damage increases breathing rate, and causes a heart attack on failure
add: Severe lung damage increases breathing rate, and causes suffocation on failure
add: Stomach damage will likely cause the owner to vomit depending on how injured the stomach is, and how much they've eaten
tweak: Brain damage effects now works similarly to the rest of the organ damage
tweak: Appendicitis will do appendix damage when in stages 3 and 4, which can cause it to burst if left
untreated
tweak: Organs heal faster the healthier the host is
balance: Defib timer has been extended to 15 minutes! Now cloning has a decent alternative. All you have to do is heal or replace failing organs e.g. mannitol on the brain, coronary bypass for the heart etc. 
balance: formaldehyde prevents post mortem organ decay.
balance: epinepherine pens now contain 3u formaldehyde preservative.
/:cl:

Additional ports (see previous PR for full list):
https://github.com/tgstation/tgstation/pull/46042
https://github.com/tgstation/tgstation/pull/47770

### CODE REVIEW

**Comment by VictorVow** [comment]
Reeee why travis mad. I need more info on why it's failing because it compiles fine for me

**Comment by Crossedfall** [comment]
> 
> 
> Reeee why travis mad. I need more info on why it's failing because it compiles fine for me

Travis doesn't allow warnings or errors. You're failing due to the following:

```
code/modules/mob/living/carbon/human/human_defense.dm:837:warning: lentext: lentext is being phased out; replace with length

code/modules/mob/living/carbon/human/human_defense.dm:849:warning: lentext: lentext is being phased out; replace with length
```

**Comment by Cenrus** [comment]
merj

**Comment by Crossedfall** [comment]
Qwert gave me the OK to merge.

**Pull request merged**
