### PR TITLE
Removes stingbangs, dumdum ammo and some unused shrapnel grenades

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Removes unused shrapnel grenades and mines.
Removes dumdum ammo from cargo.
Removes stingbang grenades.

Syndicate frag grenade is the only remaining shrapnel grenade.

## Why It's Good For The Game

Spawning large numbers of projectiles causes projectiles to lag or be delayed. While not too noticeable while the server is fine near roundstart, when used during laggy moments the projectiles will just remain stationary and not move.
Projectiles are not handled well at all when large numbers are created, as I found out when making BSE.
Also the projectile clouds look terrible and look like bullet grenades rather than shrapnel since the sprite isn't changed.
Shrapnel uses embedding which is a terrible system.
Shrapnel uses projectiles which is a terrible system when large numbers of projectiles are created.

## Changelog
:cl:
del: Removes stingbangs
del: Dumdum ammo
del: Removes unused shrapnel mines and grenades.
/:cl:

### CODE REVIEW

**Comment by eeSPee** [comment]
I like the idea of dumdums. If I rework them into Sketchkin ammo, do you think they can make a comeback?

**Comment by utilbird** [comment]
~~I'm working on raycast grenade shrapnel atm~~
edit: it'll probably be a while

**Comment by PowerfulBacon** [comment]
This will probably conflict with embed rework, merge that first

**Comment by PowerfulBacon** [comment]
> 
> 
> ~I'm working on raycast grenade shrapnel atm~
> edit: it'll probably be a while

literally just get closed turfs in view()

**Pull request closed without merging**
