### PR TITLE
Dexalin, Dex+, and two new chems

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Readds dexalin, adds dexalin+, hepanephrodaxon, and carthatoline.

## Why It's Good For The Game
Might as well readd dex, and if I'm gonna do that, I'll readd dex+ too. The other two are needed 1, because an intermediate toxin purging chem is needed, and 2, there's no way (for people that don't grow omegaweed and sentient fucking tomatoes) to heal liver damage besides replacing said liver.

## Changelog
:cl:
add: Dexalin and Dexalin Plus, chems you may or may not recognize. In short, they heal oxydamage.
add: Hepanephrodaxon, a chem for healing liver damage. For when someone hits the hooch a little *too* hard.
add: Carthatoline, an anti-toxin slightly better than charcoal or anti-toxin itself, used for when you don't want to go all out with pen acid.
/:cl:

### CODE REVIEW

**Comment by CthulhuOnIce** [comment]
if this is merged you gotta add these to the wiki

**Comment by MarkSuckerberg** [comment]
yeah, will do.

**Review by ike709 — APPROVED** [review]

**Comment by hackerjsimon** [comment]
merge this may as well be a hotfix

**Comment by ike709** [comment]
Fix your CL.

**Comment by eLeCtrOssSnake** [comment]
Surely yes. I don't like tg idea of most chems having good and bad affection. But I would like to see all organs fully functional in-game. I remember when I played on tg I had a lot of toxy damage so I crafted charcoal and started drinking it a lot and then I died because charcoal also had lungs damage. So that was kinda dumb

**Comment by eLeCtrOssSnake** [comment]
New stuff is always good.

**Review by eLeCtrOssSnake — APPROVED** [review]

**Pull request merged**
