### PR TITLE
Minor spelling mistake

### PR DESCRIPTION
**Pull request by JixS4v**
## About The Pull Request

fixes sulfuric acid being called "sulphuric acid" in code

## Why It's Good For The Game

consistency + spelling mistakes bad

## Changelog
:cl:
fix: sulfuric acid is now properly spelled
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
🔑 soul removed (joke)

**Comment by EvilDragonfiend** [comment]
I will lift my key if you edit the pr contents correctly like this:
* title: makes sulphuric acid spelling incorrect
* body: incorrect spelling for the word is necessary to harass britishes
* cl: sulphuric acid spelling is now more wrong

**Comment by PowerfulBacon** [comment]
Wait but isn't sulphuric correct?

**Comment by JixS4v** [comment]
british spelling vs american spelling, but for consistency's sake and given that the international chemistry association prefers the american version i changed them all to sulfuric

**Comment by Isy232** [comment]
Screw the americans, long live the commonwealth and the correct spelling!

They've already taken armour from us, they shall advance no further!

**Comment by JixS4v** [comment]
Do british people actually exist? I mean, they must be a meme, there is a not a single thing about them. And I mean it.

Let's go through the evidence: Where are they from? Not a single country in the world is named Britain. Some people say they come from England, and England is inside Britain, but if that was the case they would be British they would be Englanders. Also, heard some silly theories about them coming from whales. Guys, no, whale people do not exist. Whales live in the sea.

There is a consensus on British people coming from Europe, but then we are left with a whole continent of possible locations. That's as good as nothing. What do they eat? Every country has at least one main dish. Even the US has their burgers. But these British people, what do they eat? Heard some people associating them with tea, but everyone knows that's an Asian thing. Shouldn't they come from Europe? One of these two points must be wrong them. To me, it looks too sketchy.

What language do they speak? I challenge you, putting all my money and my ass on the line here, to find a supposed ""British"" person speaking their native language. Most of then just speak a broken ENGLISH. Yes, english. Really suspicious, huh? And I even tried to look deeper into it. Maybe british just SOUND like english, just like spanish could sound like portuguese for a non-speaker. So I looked up "british dictionary on google" and what I found was shocking: every word in there was AMERICAN. I kid you not. What this could mean is beyond my capabilities, but I can safely assure you that british people do not exist .

**Comment by Rustyfoxb** [comment]
If most things in game are written in british english then would it be a misspelling to make it american english for the word?, Just asking since i haven't checked all the spelling in the code

**Comment by JixS4v** [comment]
image

i'm seeing other stuff in american english

**Comment by JixS4v** [comment]
i'm literally doing the opposite lol, repo ban this guy :trolled:

**Comment by PowerfulBacon** [comment]
The chemistry authority spells it wrong, so I approve of this PR

**Comment by Tsar-Salat** [comment]
Gentlemen.

I have found the compromise.

Screenshot_20230605_154909

**Review by itsmeow — APPROVED** [review]
Sulfuric is the correct IUPAC spelling and what is used in Fluorosulfuric acid. These two should at minimum be consistent with each other since they're the same words.

**Comment by itsmeow** [comment]
> #8492 I got denied for changing a word between American and British English, this guy should suffer too!
> 
> Deny deny deny!

You didn't get denied, you just closed the PR without finishing it :3

**Pull request merged**
