### PR TITLE
Resprites floor tiles

### PR DESCRIPTION
**Pull request by imsynthex**
## About The Pull Request

Partially reverts https://github.com/BeeStation/BeeStation-Hornet/pull/7995, keeping the catwalks, hazard stripes and yellow decals

Also addressed the criticism of the "old" floortiles being too noisy by bringing down the contrast to some degree

Additionally kept `cafeteria_red`, `floor_light`, `cafeteria_dark` and `smart_checker` for the sake of not making map changes

## Why It's Good For The Game

Surface imperfections make them look like actual tiles that people have walked on as opposed to just squares of color with highlights and shadows (or shiny plastic as some have described them)

## Testing Photographs and Procedure

Current:
198921707-252e5406-cc0c-4238-baa1-4cf5f4abd70f

New:

dreamseeker_ZpD8YRQ5Jm

Comparison:
image

## Changelog
:cl:
imageadd: The floor tiles have been resprited
fix: Shutters and blast doors using new hazard lines show up in game now
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
The screenshot in the PR body just looks way worse and more flat.
image

**Comment by itsmeow** [comment]
show both

**Comment by imsynthex** [comment]
It is clear that this will require many iterations before having any hope of being merged so I will not change all the other tiles (and wont make any commits) until the normal tiles get the go-ahead

**Comment by Tsar-Salat** [comment]
> imagedel: The old floor tiles have been brought back

Fix your cl

**Review by itsmeow — APPROVED** [review]
I like the additional texture of the new sprites. The color of the in-between sprites is better than the old ones, and this keeps that. I think it is an improvement.

**Comment by PowerfulBacon** [comment]
Not really sure how I feel about these, the more I look at them the more the lighter square in the middle looks too blatant

**Comment by imsynthex** [comment]
very cool git, very cool

**Review by PestoVerde322 — APPROVED** [review]
Democracy won, Approved and merged asap.

**Pull request merged**
