### PR TITLE
Removed Xenobio from MetaStation

### PR DESCRIPTION
**Pull request by JikkaJoestar**
## About The Pull Request

Removed xenobiology from MetaStation

## Why It's Good For The Game

Xenobiology encourages players to play in a way that is against what we strive for on bee, encouraging people to get gamer gear instead of RPing

(please don't actually merge this)
## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.
image

</details>

## Changelog

/:cl:

### CODE REVIEW

**Review by PestoVerde322 — COMMENTED** [review]
🔑 

As based as this can be, I know it's a joke, right?

**Comment by DarnTheMarn** [comment]
The only joke here is that it's not every station.

**Comment by Penwin0** [comment]
haha funni

**Comment by EvilDragonfiend** [comment]
cringe

**Comment by JikkaJoestar** [comment]
whenever i get the motivation to be productive, I'll work on an actual removal

**Pull request closed without merging**
