### PR TITLE
Ports hat throwing from TG

### PR DESCRIPTION
**Pull request by Mick1299**
## About The Pull Request
Ports the ability to throw hats onto people and borgs heads. Full credit goes to MMMiracales for the implementation, https://github.com/tgstation/tgstation/pull/45355

## Why It's Good For The Game
Warden being shitsec? Throw a random hat at their head, and steal their priceless beret

This pr adds a harmless new prank to the players repertoire. Before everyone freaks out about knocking hardsuit helmets off, or a potential new way to remove tinfoil hats yourself, there are two new clothing flags that prevent this.

SNUG_FIT is for hats that can't be knocked off. Welding helmets, spacesuit helmets, security helmets etc
EFFECT_HAT is for helmets with a special effect that shouldn't be freely thrown onto other peoples heads. Tinfoil hats, peace flowers, etc

This PR also adds a target_zone variable to thrown objects, potentially allowing for further interactions in future prs

A touch of minor refactoring to obj_flags.dm too

## Changelog
:cl:
add: you can throw hats onto heads, knocking the old hat off
add: SNUG_FIT, and EFFECT_HAT object flags, target_zone var to thrown objects
code: code interaction with head item slot and thrown hats
refactor: adds consistent indentation to obj_flags.dm
/:cl:

### CODE REVIEW

**Comment by Mick1299** [comment]
I'm open to suggestions on which head wear should have SNUG_FIT. At the moment, I've given it to all hardhats and helmets, and a smattering of misc and collectables that cover the whole head.

Not sure if wearable cat and rabbit ears should have it, at the moment they do.

**Comment by WhyIsCaeciliusTaken** [comment]
Let us knock off cat ears so we can deep fry them

**Comment by Mick1299** [comment]
I'm around 90% sure that is all the head slot items in the game accounted for. This is ready for review

**Comment by zeskorion** [comment]
Sleepy, not going to full review, but
-doublecheck you aint deleting subtypes
-doublecheck envirohelms, chameleon envirohelm
-wizard hats

**Comment by Chessus** [comment]
Finally we can throw hats on borgs again

**Comment by Mick1299** [comment]
Alright, all head slot items are now accounted for. Tested a number of interactions, for items with and without clothing flags, its working exactly as intended.

I'm unsure if chameleon hats should be knockable or not. Either way, you could test is a hat is real or chameleon by throwing a hat at the person wearing it. If its disguised as a hat without SNUG_FIT, it would bounce off, revealing it as a cham hat. While its a minor issue, its technically a minor nerf to cham kits

**Comment by Mick1299** [comment]
I might get rid of EFFECT_HAT, and just use SNUG_FIT for the tinfoil hat and envirohelmet. Bit of a waste to define a new bitfield and flag, and only use them twice

**Comment by Mick1299** [comment]
Ignore that last comment, I'm dumb. EFFECT_HAT is to prevent throwing hats with bad effects onto peoples heads. This is ready for review.

**Review by zeskorion — CHANGES_REQUESTED** [review]
-chameleon envirosuit helmet still needs snug_fit, as its not an envirohelm subtype
-athiest's fedora should get effect_hat, due to it being a throwing weapon

**Comment by Mick1299** [comment]
The code already accounted for wearable non-clothing items being the thrown object, but it didn't account for them being on the head of someone thrown at. Since the two new flags are defined under /obj/item/clothing flag, I can't assign it to wearable objects like the bucket or nullrod fedora. This resulted in them always being knocked off by other hats.

Fixed it by narrowing the code to only work on /obj/item/clothing objects, not all /obj/item objects. Not the most elegant solution, but its better than nothing.

Also did another run through. Fixed a few minor things and added two last missed pieces of head

**Comment by Mick1299** [comment]
It's compiling and the running perfectly on my end, Travis error looks to be the consistent error it keeps throwing from monstermos

**Comment by eLeCtrOssSnake** [comment]
Actually, it's useless...

**Comment by hotimep** [comment]
valid checking by throwing hats at people
based

**Review by zeskorion — APPROVED** [review]

**Pull request merged**
