### PR TITLE
Adds the syndicate surgery implant for 12 TC.

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

This adds a new medical/roboticist traitor item - the Syndicate Surgery Implant, or hacked serverlink implant, whichever you wanna call it.

It's only available to traitors, and not nukies or incursion.

It has the following effects:
  - Can do almost any surgery, anywhere, regardless of research or operating surface.
    - Notable exceptions are necrotic revival and abductor organ replacements.
  - Will never (unintentionally) fail surgery steps.
  - Surgery steps are always fast as they would be on an abductor operating table.

It's currently 12 TC, but I'm completely willing to raise the TC price if people think the current price is too low.

## Why It's Good For The Game

Opens up interesting opportunities for medical and roboticist traitors, such as:
  - Being a field medic for your traitor buddies.
  - Brainwashing someone where they normally wouldn't expect it, like on a roller or stasis bed.
  - Just bragging about how amazing of a surgeon you are, and how _you_ should totally get a medal due to your amazing skills.
  - Using a toolbelt your buddy smuggled into perma to give the other guy in perma nerve grounding, so they can smash through the electrified grilles and allow you both to escape.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

23-05-11-1683847239-dreamseeker
23-05-11-1683847254-dreamseeker
23-05-11-1683847271-dreamseeker

</details>

## Changelog
:cl:
add: Added the Syndicate Surgery Implant to the traitor uplinks of doctors, paramedics, roboticists, and brig physicians for 12 TC. It grants the user perfect surgery knowledge, allowing them to do almost any surgery, anywhere, quickly and free of mistakes. It is however, NOT available to either nuclear operatives or incursion members.
/:cl:

### CODE REVIEW

**Comment by WrillWasTaken** [comment]
Necrotic revival should absolutely be treated with caution.

**Comment by EvilDragonfiend** [comment]
Tbh I am not a fan of this in both of balance-wise and maintainability code-wise. The surgery would need refactor for this specifically...

**Comment by Absolucy** [comment]
@WrillWasTaken I've added a hacky fix to prevent this being used for necrotic revival.

**Comment by EvilDragonfiend** [comment]
I suggest you to make anothee subtype of serverlink implant with having its own surgery list, and surgery checks the basic surgery list + syndi surgery list by a proc.

**Comment by Absolucy** [comment]
@EvilDragonfiend I mean, I'd still have to code a check for the implant for the new benefits I've added to TRAIT_SURGEON. I'd rather have 1 hardcoded implant check than multiple.

**Comment by Absolucy** [comment]
actually whatever i just split it into two traits and made it a serverlink subtype lol

**Comment by EvilDragonfiend** [comment]
Okay, I will tell you how I see this.

```
	if(iscarbon(user))
		var/mob/living/carbon/C = user
		var/obj/item/organ/cyberimp/brain/linkedsurgery/IMP = C.getorganslot(ORGAN_SLOT_BRAIN_SURGICAL_IMPLANT )
		if(!isnull(IMP))
			if(replaced_by in IMP.advanced_surgeries)
				return FALSE
			if(type in IMP.advanced_surgeries)
				return TRUE
```this is when a surgery checks your implant.

the part you should replace is:
```
		if(!isnull(IMP))
			if(replaced_by in IMP.advanced_surgeries)
				return FALSE
			if(type in IMP.advanced_surgeries)
				return TRUE
```
This should call a proc from linked surgery implant instead of checking it directly.

```
linkedsurgery/proc/check_surgery_program(target_type)
	if(target_type in advanced_surgeries)
		return TRUE

...

		if(!isnull(IMP))
			if(check_surgery_program(replaced_by))
				return FALSE
			if(check_surgery_program(type))
				return TRUE
```

and then, the subtype syndi serverlink should be like this

```
linkedsurgery/syndicate/check_surgery_program(target_type)
	if(target_type in advanced_surgeries+saved_syndicate_surgeries)
		return TRUE
```

this is better than using traits.

**Comment by Absolucy** [comment]
@EvilDragonfiend No I mean... I just renamed the abductor scientist trait to something else, and turned the implant into an actual serverlink that just gives you all but a few surgeries automatically.

The new trait, `TRAIT_PERFECT_SURGEON`, is for the 100% success rate and speed boost during surgery.

**Comment by EvilDragonfiend** [comment]
yeah, but I really don't like using traits in that way, and ngl, I don't even like how the abductor surgeon trait works too, but it's fine as long as it's only a single trait to bypass everything.

**Comment by Absolucy** [comment]
well doing a whole refactor of surgery is very much out of scope for this PR...

**Comment by EvilDragonfiend** [comment]
I am not asking the whole surgery refactor. I am telling you should do the thing I code-quoted instead of adding new traits.

**Comment by Absolucy** [comment]
tbh refactoring the serverlink is also out of scope... and i'm _not_ using traits for the "all surgeries" functionality currently.

**Comment by EvilDragonfiend** [comment]
If you're adding a feature, a small refactoring or code improvement comes along with it necessarily, and the thing I said is even an easy one which is even difficult to call a refactoring.

Okay, let's say that in design-wise.

You're expected to have surgery programs in a variable from the item, not a trait.
but the surgery check is doen by a trait which is given by an implant that has a list of surgery programs.
This is not a good design flow, and does not contribute a good influence for the code in the future, because someone should understand how this flow goes but they wouldn't expect it's trait related.

So, you should not use traits here.

**Comment by PowerfulBacon** [comment]
This is far too expensive, it should be 1-2TV more than brainwashing

**Comment by EvilDragonfiend** [comment]
> This is far too expensive, it should be 1-2TC more than brainwashing

It's portable brainwash. This shouldn't be a more popular option than brainwash disk since 7 TC (since brainwash disk is 5 TC) is too cheap.
unless they remove brainwash from the surgery list and they should purchase brainwash disk separately to store it into.

**Comment by PowerfulBacon** [comment]
Also imo if you are going to make someone insanely fast at performing surgery just for having it, it should be a toggle. It is very obvious if someone is suddenly very fast at performing surgery

**Comment by Absolucy** [comment]
@PowerfulBacon It's only like a 20% speed bonus compared to an operating table. But yeah, that'd be a good idea.

And are you sure it should be _cheaper_?

**Comment by Rukofamicom** [comment]
It definitely should not be cheaper, Bacon is overlooking something. 
I think 12 is okay, kinda lean with you in thinking that's the lowest it should go but should be open to potentially being more. 

@PowerfulBacon please acknowledge you understand that these can be performed remotely with 100% success rate without a disk or research

* **Cavity Implant** - place bombs or other devices inside of people
* **Dental Implant** - have a reagent mix ready to go at any moment that is undetectable during searches, can be stacked multiple times with different pills. Think along the lines of an adrenal implant, except undetectable but you have to get the reagents yourself. 
* **Plastic Surgery** - Infinite mulligans, change your target's identity, etc.
* **Revival Surgery** - invaluable to have available for team antagonists
* **Tend Wounds at full research speed** - I think this should speak for itself if you're familiar with how quickly it can heal
* **Nerve splicing** - Makes someone permanently more resistant to stuns
* **Brainwashing** - But you can do it anywhere without purchasing the disk

**Comment by PowerfulBacon** [comment]
Compared to the value of other items, that isn't worth 12 TC altogether and won't be purchased for that price.

**Comment by Absolucy** [comment]
@Rukofamicom fwiw, some of those you listed can be performed without a disk or research anyways, like cavity implant, dental implant, and plastic surgery

**Comment by Rukofamicom** [comment]
Yes they can but the success rate sucks in most locations, especially dental implant self-surgerg

**Comment by Absolucy** [comment]
Honestly, we could always just wait and see if it's busted and the price needs to be raised or not. I'd imagine it'd be easier to get a PR raising the price than lowering it merged after-the-fact.

**Comment by Fronsis** [comment]
This item is role-restricted to Medical-doctor and relevant jobs, correct?

I agree with Ruko, the price is correct and could even be higher, this in Incursion team would be, in my opinion, too much.

Incursion lately has shown to be quite powerful and most of the time whenever incursion is not taking their time to take down their ex-comms they end up going for aggresive strategies against command and security, which is fine as long as proper roleplay is done! However... Now we're talking that near round-start a team of up to 5(or 6?) players have bloodloss resistance, stun resistance, electrified resistance, easy revival surgeries without needing to risk to go to medbay, augmentations and the list goes on

And on top of that they get **Brainwashing** that they can pretty much do on anyone considering the other members would have more than spare TC for any type of subdue-like item so suddenly the incursion goes from 5 people to... nine (i've seen it three times) due to a spam of either brainwashing/hypnoflash i don't really think Incursion needs even more manpower it can end up like revs 2.0 but half of them have TC.

There's too much positive things for zero drawbacks, sure you waste 12 TC and you kinda become the ''doc of the incursion'' but that would absolutely end up going to be a meta strat (it has already started with hypno-brainwash in some incursion metas)

IMO it should be restricted to solo-traitors, incursions are already powerful enough, this would just incentivize more min-max.

**Comment by Absolucy** [comment]
@Fronsis 
> This item is role-restricted to Medical-doctor and relevant jobs, correct?

Correct.
```dm
restricted_roles = list(JOB_NAME_MEDICALDOCTOR, JOB_NAME_CHIEFMEDICALOFFICER, JOB_NAME_ROBOTICIST, JOB_NAME_PARAMEDIC, JOB_NAME_BRIGPHYSICIAN)
```

> IMO it should be restricted to solo-traitors, incursions are already powerful enough, this would just incentivize more min-max.

Alright, I've restricted it to solo traitors.

In addition, I've also added a button that allows people to toggle the implant's effects, which should help prevent potential meta-ing of this implant.

**Review by itsmeow — APPROVED** [review]
Honestly a really cool traitor item - it's powerful but not quite destructive/murder-y. I think this makes 12 when considering the constituent items it replaces a good starting price. Having it be role restricted also helps make the case for it. My only concern is it could potentially make brainwashing too easy, giving the traitor effectively infinite minions. However this still requires you to operate on someone's brain without them realizing.

I would like to see how this plays out. 12 is definitely the lowest I would price this at, with 16 being the highest.

**Pull request merged**
