### PR TITLE
add tiny fan to luxury shuttle poor department

### PR DESCRIPTION
**Pull request by Sinestia**
## About The Pull Request
discord pr 

## Why It's Good For The Game
someone always opens the airlock on the poverty department of the luxury shuttle resulting in spacing it

Your wallet may lack value, but You have Value. 

## Changelog
:cl:
add: tiny fan to luxury shuttle poverty department
/:cl:

### CODE REVIEW

**Comment by eeSPee** [comment]
Let the poor die if they can't afford to live.

Less poor to eat the rich.

**Comment by PowerfulBacon** [comment]
do they really deserve it?

**Comment by Sinestia** [comment]
I don't like the filth who can't pay up $500 or prepare in other ways 

But it's a bit of a concession to keep it from being a shitter shuttle to order because otherwise, it's probably my favorite shuttle. multiple people not dying from some random non-antag dude opening the airlock is the exception not the norm.

**Review by Bamhalazam — APPROVED** [review]
yes

**Comment by Bamhalazam** [comment]
> yes

the rich don't deserve to suffer because of the poor. or atleast add a fan to the door separating the poorhouse from the rich mansion

**Comment by ike709** [comment]
The proletariat will rise up.

**Pull request merged**
