### PR TITLE
Adds a Meta-Vendor (dispenses vendor boards)

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
Adds a meta-vendor to dorms and primary storage of every map. This vendor contains machine boards for the various vendors, as well as a purchasable wrench, screwdriver, and cable coil to quickly get started.

## Why It's Good For The Game
Makes it far easier to deck out a secret base, construction, etc with CAPITALISM, plus it's still relatively balanced because you have to obtain the resupply yourself (maint diving or cargo)

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

meta_std

meta_panel

meta_made

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
add: Added a meta-vendor to dorms and tech storage
/:cl:

### CODE REVIEW

**Comment by Dejaku51** [comment]
you know you can use screwdriver on custom vendor board (/obj/item/circuitboard/machine/vendor) and switch it to X type of vendor? so this PR is kinda useless

**Comment by etherware-novice** [comment]
uhh- but this is more accessible for assistants and stuff!

**Comment by FortSumter** [comment]
Assistants can't afford buying from vendors to build a vendor and won't go though the effort unless they themselves can make money from it.

There's also a frighteningly common chance they'll come alive and kill you.

**Comment by etherware-novice** [comment]
hm..if they can make money off it....

**Comment by PowerfulBacon** [comment]
I'm not a fan of this idea, I think if someone wants to deck out a maint base they should be forced to go and interact with science in some capacity (Either breaking in or talking and asking nicely)

**Comment by ike709** [comment]
Same, it makes circuit printers fairly useless 🔑

**Pull request closed without merging**
