### PR TITLE
Adds Doomguy ERT and two new traitor/nukie items: Energy Chainsaw and Super Energy Chainsaw

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
Adds several new things to the game, the first is 'The Juggernaut' - basically a one-man deathsquad, armed with a number of guns including a grenade launcher and pulse destroyer, has Krav Maga and a bunch of new additions. Also coincidentally looks like Doomguy.

The Juggernaut's brand new additions to his loadout includes:
- The Super Energy Chainsaw - an energy chainsaw which does 60(!) brute, has 75% armor penetration and has 75% melee block. Also knocks victims down for half a second per hit and fits in backpacks. Sounds and looks badass. Can also be bought in nukie uplinks for 22 TC. 
- Supersoldier species - has many traits including stun, slip and slowdown immunity, as well as passive health regen in light like podpeople. 
- Hammerspace backpack - basically a Bag of Holding but with much more space. Must-have for any FPS videogame character. 
- Juggernaut armor - is the strongest armor in the game, has a decent shield and it totally looks like classic doomguy.

Lastly we have the Energy Chainsaw - it's a 10 TC traitor item for cooks, bartenders and botanists. Does 40 brute, has 50% armour penetration and has 50% melee block. Quite a bit more powerful than an esword, especially against armoured targets, but it is substantially larger (Huge size class). 

## Why It's Good For The Game
Bit of variation in the ERTs, good for meme events and energy chainsaws are badass.

## Changelog
:cl:
add: The Juggernaut, a one-man ERT with the sole purpose to wipe out every living thing on the station. Coincidentally looks like Doomguy.
add: New nukie/juggernaut item: the Super Energy Chainsaw. Does 60 brute, has 75% armor penetration and has 75% melee block. It also deals a brief knockdown and fits in backpacks. Costs 22 TC for nuke ops. 
add: New cook/bartender/botanist traitor item: the Energy Chainsaw. Does 40 brute, has 50% armour penetration and has 50% melee block. Costs 10 TC.
add
/:cl:

Ports:
https://github.com/tgstation/tgstation/pull/47927
https://github.com/HippieStation/HippieStation/pull/3101

### CODE REVIEW

**Comment by zeskorion** [comment]
Might wanna make energy saw more expensive considering superglue exists

**Comment by qwertyquerty** [comment]
merge dmi file

**Comment by Unidentified-Biohazard** [comment]
The only thing I can suggest is to slightly nerf the melee damage and make it heal the user when they kill something or make them drop ammo.

**Comment by qwertyquerty** [comment]
The new traitor items seem slightly OP to me for their cost

**Comment by VictorVow** [comment]
The basic energy chainsaw is role-restricted, same price as esword and bulky. If anything I was thinking about removing one of those aspects, because I still don't see it getting picked as much as an esword. 

The super energy chainsaw is a nukie item only and even more expensive than the L6 SAW despite you needing to get into melee range to use it on a roundtype that will likely result in the crew being heavily armed.

I think they need some play-testing to determine whether or not they're balanced well in price, though I'm leaning towards them being overpriced at the moment.

**Pull request merged**
