### PR TITLE
[MDB IGNORE] Remove Fastmos Changes From All Maps

### PR DESCRIPTION
**Pull request by MCterra10**
## About The Pull Request
Remove maintenance firelocks, remove small firelocks and replace them with fullsize variants, remove external window firelocks
PR is a component of BeeStation/BeeStation-Hornet#3767 and both PRs should ideally be merged at the same time.

## Why It's Good For The Game
N/A (Component of auxmos PR)

## Changelog
:cl:
del: Remove fastmos changes from all maps
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — APPROVED** [review]
This will be conflict hell

**Comment by BrumalLake** [comment]
i assume they dont have a manual lever and can't be held open with a crowbar like tg

**Comment by SergeiKoralev** [comment]
Is this why there is a mapping freeze?

**Comment by Sinestia** [comment]
> 
> 
> Is this why there is a mapping freeze?

ya

**Comment by SergeiKoralev** [comment]
I have a question, are you doing this? 

image

**Comment by SergeiKoralev** [comment]
Metastation: 
This row of locks should be removed so there is a scrubber and vent in a single unified area. 
image

Same can be said for a lot of the map.

**Comment by mcmeiler** [comment]
Cool, firelocks are now an essentially free hardstun until you die after being shoved.

**Comment by ike709** [comment]
@mcmeiler Welcome back to old firelocks.

**Pull request merged**
