### PR TITLE
Fresh CC Look

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
Changes the CC Evac Dock to look different and use newer assets.

Thank you marshmellow10 for the initial design of the CC Evac Dock. It looks great!

## Why It's Good For The Game
New fresh look and using new assets which CC hasn't gotten since 1945.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog marshmellow10, Markus Larsson
:cl:
tweak: Changed CC Evac Dock
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
I am wondering if I should update more parts of CC or just this one? I am tempted to do more major changes to it.

**Comment by Fronsis** [comment]
The new catwalk-floor (or however it's named) looks.. very hard on the eyes IMO, since they don't look connected they just look like random squares and the N is not centered, that's gonna make some people explode

**Comment by Rukofamicom** [comment]
I don't like the unnecessary use of the yellow and black caution decals. 

These should be used in hazardous areas not around chairs. Their overuse is a big contributor to the visual vomit of kilostation.

**Comment by spockye** [comment]
hmmm. i kinda think your using too much black. All of centcom uses grey tiles, feels a little weird when just the lobby is dark

**Comment by MarkusLarsson421** [comment]
> hmmm. i kinda think your using too much black. All of centcom uses grey tiles, feels a little weird when just the lobby is dark

I think the darker look is amazing. This is what Bombyx did and sent me.

image

This is also why I'm thinking if the whole of CC should be redesigned majorly in order to look more modern as a whole and not clash between dark and light themed areas?

**Comment by MarkusLarsson421** [comment]
> I don't like the unnecessary use of the yellow and black caution decals - they really only need to be by the bulkheads.
> 
> These should be used in hazardous areas not around chairs. Their overuse is a big contributor to the visual vomit of kilostation.

It does highlight very nicely, but I might try to add something else to not be confused with the hazardous decals.

Also, Kilo station looks amazing! >:c

**Comment by Rukofamicom** [comment]
My god it looks even more like decal vomit now. 
Why are their cautionary decals around the chairs?

**Comment by MarkusLarsson421** [comment]
rood

Mightly to highlight.

**Comment by Tsar-Salat** [comment]
> Their overuse is a big contributor to the visual vomit of kilostation.

Oh my god. I see it now. 

Dear god.

Screenshot 2024-07-08 233228

Screenshot 2024-07-08 233218

Screenshot 2024-07-08 233202

This is terrible!

**Comment by Tsar-Salat** [comment]
> I think the darker look is amazing

Aw cmon, I put all that work into the new tiles and y'all dont even use it?



Also, the catwalk tiles dont match. Heres a palette

image

**Comment by TsunamiAnt** [comment]
oooh i like the idea of using the black tiles as a sort of lower floor level maybe with stairs, with the ones that fit the catwalk denoting paths and major thoroughfares.

**Comment by llol111** [comment]
Yea im not a fan of the dark look.
I dont see an issue with the layout as it is in the PR, if it had normal colored tiles.
But i realy dont dig the dark tiles.

**Comment by PowerfulBacon** [comment]
Not a huge fan of the dark tiles

**Pull request closed without merging**
