### PR TITLE
Rancher hat avalibility

### PR DESCRIPTION
**Pull request by EveLed**
Added the rancher hat to the clothesmate and beecoin shop.

## About The Pull Request

Added rancher hats to clothesmates and the beecoin item shop

## Why It's Good For The Game

Figured it should be easier to get a cool looking (but reasonable) hat without having to bother a specific department over it.

## Testing Evidence

image
image

## Changelog
:cl:
add: Added rancher hats to clothesmates and the beecoin item shop
/:cl:

### CODE REVIEW

**Comment by EveLed** [comment]
First time doing this sort of thing. Sorry if it sucks and breaks the entire game. I tried my hardest

**Review by DrDuckedGoose — APPROVED** [review]

**Comment by Marshmellow105** [comment]
nice

**Comment by ClownMoff** [comment]
Based, I like this hat

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
Code looks fine and honestly probably doesn't actually NEED testing evidence, but since this is the first PR it's important you know and remember that you shouldn't just omit entire  sections of the template.

You need a` /:cl:` at the bottom of your changelog as well.

**Review by Rukofamicom — APPROVED** [review]

**Comment by EveLed** [comment]
Shit how do I pass the checks

**Comment by JixS4v** [comment]
> Shit how do I pass the checks 

First PR, so they need approval to be ran. You'd probably have a better chance of getting it approved by pinging over discord

**Comment by Rukofamicom** [comment]
I got it

**Pull request merged**
