### PR TITLE
Adds pools to box and meta

### PR DESCRIPTION
**Pull request by Sinestia**
## About The Pull Request

water

i replaced the budget rage cages, real rage cages are built by hand anyways. 
image
image

I didn't add it to pubby because there wasn't exactly a clean area I thought it'd fit. Maybe in the sandy area of the monastery, or perhaps the pool can replace the SM, who knows.
## Why It's Good For The Game

more pool fun

incase there's concerns about map identity or something, delta is already the largest and most overloaded map so it really doesn't matter that these 2 get swim swims.
## Changelog
:cl:Froststahr
add: Pools have been deployed to Boxstation and Metastation.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
The boxing lockers need swimming gear

**Comment by Sinestia** [comment]
fixe

**Comment by Cartlord** [comment]
Honestly, my issue with this is just that the maps're becoming homogenous. I pretty much always end up on Meta and Box, and I don't see any reason to add something to add something to both, and in the same place.

**Review by PowerfulBacon — DISMISSED** [review]

**Comment by Sinestia** [comment]
> 
> 
> Honestly, my issue with this is just that the maps're becoming homogenous. I pretty much always end up on Meta and Box, and I don't see any reason to add something to add something to both, and in the same place.

Nah, I agree homogenity is an issue. But I think this is still positive due to what I said in the OP, delta is already the most large and featureful map by far. Homogenity should be dealt with elsewhere. 
(Though it doesn't help that players often reject maps that are different but hey what can you do.)


 I think these features actually fit box and meta a little better than delta, especially box, you don't get delta on on any of the long, chill, low-pop rounds.

**Comment by ghost** [comment]
add a coffee vendor so i can spam funny chocolate in the pool

**Comment by Cartlord** [comment]
> 
> 
> > Honestly, my issue with this is just that the maps're becoming homogenous. I pretty much always end up on Meta and Box, and I don't see any reason to add something to add something to both, and in the same place.
> 
> Nah, I agree homogenity is an issue. But I think this is still positive due to what I said in the OP, delta is already the most large and featureful map by far. Homogenity should be dealt with elsewhere.
> (Though it doesn't help that players often reject maps that are different but hey what can you do.)
> 
> I think these features actually fit box and meta a little better than delta, especially box, you don't get delta on on any of the long, chill, low-pop rounds.

Y'know, that's fair, and I agree. To be honest, I've never even been on delta.

**Comment by Sinestia** [comment]
mapdiffbot is somewhere else but its actually resolved now :Shrug:

**Comment by FortSumter** [comment]
Speedmerge

**Review by utilbird — APPROVED** [review]

**Pull request merged**
