### PR TITLE
You can no longer eat thru the miner gas mask

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Title. How does this happen.

## Why It's Good For The Game

More than likely unintended.

## Changelog
:cl:
fix: You can no longer eat thru the miner gas mask
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
its not toggled in the action button?

**Comment by february-ops** [comment]
It's not a bug ruko added it in their miner pr

**Comment by ivanmixo** [comment]
> It's not a bug ruko added it in their miner pr

Why have the mask be adjustable then...

**Comment by r1ks-iwnl** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/2784
intended

**Review by ike709 — APPROVED** [review]
Ruins the point of adjustable masks if you don't need to adjust them.

**Comment by BrumalLake** [comment]
ah yeah, it needs to cover by default like the breath mask

**Comment by mcmeiler** [comment]
This is literally intended though?

**Comment by BrumalLake** [comment]
> 
> 
> This is literally intended though?

its not you're not supposed to be able to eat through the mask if its not adjusted up

**Comment by ivanmixo** [comment]
> > This is literally intended though?
> 
> its not you're not supposed to be able to eat through the mask if its not adjusted up

Apparently it was, but I think this is really stupid. Why have it be adjustable when it literally doesn't make a difference?

**Comment by mcmeiler** [comment]
> its not you're not supposed to be able to eat through the mask if its not adjusted up

#2784
"Other changes: The explorer mask now allows you to eat without cutting off internals."

Idk man seems pretty intended to me


> Apparently it was, but I think this is really stupid. Why have it be adjustable when it literally doesn't make a difference?

Probably just artifact since the change

**Comment by BrumalLake** [comment]
well, i suppose this pr was a mistake then
the mask toggle simply makes the weight class toggle between small and normal now so it should still be kept

**Comment by ivanmixo** [comment]
How do you eat thru a gas mask that is currently connected to a tank anyways...

**Comment by Singularity69** [comment]
intended. it's for miners to eat without suffocating in lavaland atmos

**Comment by githubuser4141** [comment]
> How do you eat thru a gas mask that is currently connected to a tank anyways...

I think the toggle button is supposed to disconnect it

**Pull request merged**
