### PR TITLE
[PORT] Ore silo upgrade for RCDs

### PR DESCRIPTION
**Pull request by Moccha-Bee**
Ports the Ore silo link upgrade from tg.

## About The Pull Request
Adds the ore silo link upgrade to the RCD from tg that's all.

## Why It's Good For The Game
Increases the effiency of building rooms with RCDs

### CODE REVIEW

**Comment by Moccha-Bee** [comment]
I have no idea what i am doing.

**Comment by Kerbin-Fiber** [comment]
mind.dm has no reason to be changed, you should revert it back to normal

**Comment by Moccha-Bee** [comment]
I will try fixing the problems and then redo

**Comment by Crossedfall** [comment]
Please  reference the PR you are porting. Also, was this a direct cherry pick from said PR or are you attempting to manually bring everything over?

Added note, for some reason you're adjusting the changelog. Please remove those changes as well.

Edit: You also didn't add a CL to your description. Please ensure you are following the correct format, otherwise the bot doesn't work.

**Pull request closed without merging**
