### PR TITLE
HoS and Captain's guns now show when they've been blown up

### PR DESCRIPTION
**Pull request by Gilgaxx**
## About The Pull Request
Exploding the HoS and Captain's guns right now has the guns survive because of the `resistance_flags = INDESTRUCTIBLE` but the ammo casings, powercell and firing pin inside (the first two being irreplacable without admin intervention) would get destroyed.
~~Added `flags_1 = PREVENT_CONTENTS_EXPLOSION_1` to both the HoS gun and the Captain gun. And now they work :)~~
Added a check so that when they explode and lose their ammo casings or powercell, they have their name, description and icons to show that they're non functional!

## Why It's Good For The Game
~~I don't think it's intended for the guns to not work permenantly after an explosion, especially with no clear indication on just looking at it.~~
I was convinced by the comments and made it so the guns can still made non-functional to punish people using devastating explosives just for their objectives but also as a possible way to punish/make fun of HoS's and captains.

## Testing Photographs and Procedure

<details>
Exploded with a smallexplosion on the HoS's gun, captain's gun and the scatter captain's gun and they all had their intended effects:
<summary>Screenshots</summary>

dreamseeker_sP50yfvCSb

dreamseeker_bgUwYFwQuC

dreamseeker_Ot5i6DqoLc

</details>

## Changelog
:cl:
tweak: The HoS and captain's guns now show distinctly if they've been blown up to the point of not working anymore.
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
Isn't this mostly for the antag objectives and not to ensure they still work?

**Comment by Gilgaxx** [comment]
> Isn't this mostly for the antag objectives and not to ensure they still work?

Maybe someone could add a special "broken" version of the guns with a changed sprite, name and description, but as of right now, other objective items (hand teleporter, jetpack, adv magboots, etc.) don't stop working when exploded. And the way the guns stopped working seemed unintended, since the power cell and ammo casings in a laser weapon is usually inaccessible unless you're an admin.

**Comment by Fronsis** [comment]
> Isn't this mostly for the antag objectives and not to ensure they still work?

Most likely, yes, but think about it.. the antag explodes the Captain/HoS and they complete their objective! only that instead of gaining a very good weapon to help them they now have a useless item that they have to carry on their bagsince it's broken and its their objective but they can't use in a fight..

A solid fix where everyone wins!

**Comment by MarkusLarsson421** [comment]
> a useless item that they have to carry on their bagsince it's broken and its their objective but they can't use in a fight..

Better than the blackbox! Plus, if you're really worried of it, you should plan according and not rely on their gun.

**Comment by Gilgaxx** [comment]
You know what, give me a bit and I'll edit the whole PR then

**Comment by Fronsis** [comment]
> You know what, give me a bit and I'll edit the whole PR then

What are you thinking? I believe your current idea is nice!! those items should work after all since no other gun has randomly inner parts destroyed after an explosion so it's consistency

**Comment by Gilgaxx** [comment]
> > You know what, give me a bit and I'll edit the whole PR then
> 
> What are you thinking? I believe your current idea is nice!! those items should work after all since no other gun has randomly inner parts destroyed after an explosion so it's consistency

Well see I liked my own comment of adding a broken state to these weapons. They're also the only indesctructible weapons, but I think it'd make sense to punish people a tiny bit for using a devastating explosion on their objective, or as a way to hinder/make fun of HoS's or captains. I've already made most of it including new sprites, just need to get a small problem fixed and then I'll commit.

**Comment by Gilgaxx** [comment]
Tadaaaa, reworked the PR

**Comment by Bydth** [comment]
Assuming it would be feasible to code, why not include an option to repair the guns? Jam a high-tier micro-laser, capacitor, and maybe a material sheet such as diamond to represent a focusing lens, apply screwdriver and replacement firing pin.  Wouldn't need to be "good as new", there could be something like a 1% chance per shot for such a jury-rigged replacement to fail catastrophically, e.g. detonate in the user's hand.

**Comment by Gilgaxx** [comment]
> Assuming it would be feasible to code, why not include an option to repair the guns? Jam a high-tier micro-laser, capacitor, and maybe a material sheet such as diamond to represent a focusing lens, apply screwdriver and replacement firing pin. Wouldn't need to be "good as new", there could be something like a 1% chance per shot for such a jury-rigged replacement to fail catastrophically, e.g. detonate in the user's hand.

If the guns were that easily repaired, it wouldn't make much of in universe sense that they were unique. Hopefully this change prevents antags who already have access to explosives from also having gun if they're too careless while also adding a way for them to hinder or even taunt the HoS and captain by destroying their precious weapon. Bonus points if command gets central command involved to repair one of these weapons.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
