### PR TITLE
Expands the Ethereal colour list

### PR DESCRIPTION
**Pull request by Pirill**
## About The Pull Request
Renames the existing Ethereal colours and adds a whole bunch of new ones! The old colours are marked out in the preview below:

image

> "So why not a colour picker?"

Aside from the code being enough of a mess that I couldn't get it to work after quite a few attempts, it introduces two more issues: First, due to the brightness restriction on character colours a few of the existing Ethereal colours wouldn't be possible and second, white and light brown are used to indicate an Ethereal's health at a glance and restricting those areas of colour would require even more messy code and exceptions. If someone wishes to tackle that in the future or standardize Ethereals to use the mutation colour instead they're more than welcome to.

[Auth by Francinium](https://discord.com/channels/427337870844362753/801432004058939422/896042201111474207)

## Why It's Good For The Game
More customisation for a race that has next to no customisation as is.

## Changelog
:cl:
add: Adds eleven more possible Ethereal colours and renames the existing ones to match
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
rip stellar classification lore
ethereals have lost some of their heritage

**Comment by Pirill** [comment]
> rip stellar classification lore ethereals have lost some of their heritage

I kinda loved that about them and considered integrating it with the new scheme but I couldn't come up with enough good names. 😔

**Comment by francinum** [comment]
I would advise burning a savefile version to convert the changed names.

**Review by Archanial — CHANGES_REQUESTED** [review]
Fran is right, burn savefile to change colors for players

**Comment by Pirill** [comment]
> Fran is right, burn savefile to change colors for players

If I understand the code right, the savefile only saves the Ethereal's hex code, not the colour. The colour names are only used to populate the picker but aren't a part of preferences so it should be perfectly compatible with the new version especially since all the old hex codes are still a part of the new list.

**Review by Archanial — CHANGES_REQUESTED** [review]
There's some stupid define in etheral.dm that does the same thing, either edit it to mirror the changes (and undef it at the end) or make the file use global list

**Comment by Pirill** [comment]
> There's some stupid define in etheral.dm that does the same thing, either edit it to mirror the changes (and undef it at the end) or make the file use global list

Oops, I missed your reply and only saw it today, sorry! That list is technically just a set of bright colours for use in the rainbow EMAG action but now that the global list has so many colours in it I just swapped it over to that. I tested it and it works so that's hopefully good enough!

**Review by Archanial — APPROVED** [review]

**Pull request merged**
