### PR TITLE
Rework of KiloStation

### PR DESCRIPTION
**Pull request by prophed**
## About The Pull Request
Complaints from players (including myself) of simple problems that the map KiloStation has at the moment. Sadly this map is for low population so many people that play in the morning or afternoon do not know about this map. But this map needs to be fixed, specially Engineering. 
This rework needs to be tested by admins. I might have missed something, is kinda hard to work with small boxes and 5+ objects on it.

## Why It's Good For The Game

Because everyone complains about this map, to a point of wanting to delete it.
## Changelog
:cl:
( image of map: https://imgur.com/j6y7z1q )
EXTRAS:
add: 2 trash cans
add: extra layer of walls for grav generator
fix: doors for the aux base
fix: bar
fix: closed gateway
del: mob in maint left to medbay
del: random ass flashbang in maint
del: one of the sec offices from departure

BRIDGE:
fix: closed top main entrance to the cap office with normal walls

MEDBAY:
add: windows for cloning and locker
add: medbay storage locker
add: escape pod
fix: made genetics room bigger
fix: made medbay central  storage bigger
del: terrain and made space BECAUSE PEOPLE WANT VIRO WITH SPACE
del: bushes from vents and scrubbers of monkeys' area from viro
del: maint behind viro

SEC:
fix: move showers from perma to the back
del: removed beautiful vegetation from perma, they dont deserve it
fix: made perma bigger

COMMS:
-add: extra layer of reinforced walls, blocking maint from behind.

AI:
add: exterior entrance, now is ENTRACE- PREANTECHAMBER- ANTECHAMBER

ATMOS:
-fix: replaced turbine walls with reinforced walls.
-fix: relaid orange pipe leading from atmos
-fix: moved floating switch and camera

CARGO:
add: warehouse

ENGI:
fix: literally the sm and power
fix: emitters connected to APC from engi
fix: color of wires, white is the input from the sm, yellow is emitters and APCs
fix: replaced SMES with engineering console
del: Hardsuits and put N2 canisters
add: cameras

XENO:
-fix: missing disposal piper in maint next to xenolab
/:cl:

### CODE REVIEW

**Comment by prophed** [comment]
I changed the map and I get code errors REEE

**Comment by prophed** [comment]
A couple of dirty variables dont hurt anyone :)

**Comment by qwertyquerty** [comment]
You need to replace the step_x/y with pixel_x/y

Also give us a changelog of what you've changed please

**Comment by prophed** [comment]
https://textuploader.com/19szw
I will copy them individually. And yeah I will do that but yesterday me sleep.

**Comment by 4rchibald** [comment]
I looked at screen you provided and I'm curious why did you remove one of the SMES at engineering and why did you remove the ones I added at engine room, and building on that where do emitters take power from now? 
These power storages were placed there just like on Delta to provide power to emitters, if you rewired them to rad collectors they should work once SM got activated but to fire it up for the first time people will need to bring pacman generator

**Comment by prophed** [comment]
I connected the emitters directly to the APC from engineering that have full power. Then those are connected to the SMES that have around half energy. I based this idea on MetaStation. I thought about giving the SM chamber his own APC like in DeltaStation but I ran into complications so I did it this way.

**Comment by prophed** [comment]
I guess to make it more complicated for antags to fuck with the emitters' power, we can connect the APC form engi to another APC that is in the SM chamber and connect this one to the emitters. I just thought that having SMES going to other SMES to power the station was too much.

**Comment by qwertyquerty** [comment]
Thank you for your contributions, I await more in the future

**Pull request merged**
