### PR TITLE
NO GODS NO KINGS ONLY MONKEY 

### PR DESCRIPTION
**Pull request by Oshibkka**
## About The Pull Request

Increases maximum spawned monkeys.
NOTE : did this shit in like 5 minutes in webeditor fuck me if it actually works lol
## Why It's Good For The Game

Removes the cringe monkey cap of 64.
## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Oshibkka** [comment]
if this actually works ill shit my pants

**Comment by Crossedfall** [comment]
First things first, fill out the CL correctly. 

Second, if you prop up a private server and test the implications of this (providing the results) I'll give it an honest consideration.

**Comment by AtlasRules** [comment]
monky

**Comment by ike709** [comment]
While we could probably up the limit.... No, we're not upping it to 350.

**Pull request closed without merging**
