### PR TITLE
PDA is now automatically updated when it takes a card / ghost role spawns now have proper HUDs, card names

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
HUD related tweaks/fix
* PDA is now automatically updated when it takes a card (if it's a syndicate card, manual update is needed)
* ghost role spawns now have proper HUDs

## Why It's Good For The Game
Seeing grey hud is bad
Seeing crews not updating their PDA is not good too. Unless they're syndicate, there would be no practical usage to not-update your PDA.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

captain spare card automatically refreshes your PDA as captain

image

normal cards with no name/incorrect name are rejected. only captain's spare works.

-------------------

image

Otherwise, as long as the card has a name that is same to the PDA's registered name, it is automatically updated.

-------------------

image
image

as long as it's ON mode, it will automatically update your PDA.
chameleon PDA still should do manual update

-------------

(images deleted accidentally...)
syndicate cards are working well too

-------------------
image
image
image

ghost role spawns now properly shows correct HUDs.

--------------

image

ruin VIP gets their card named

</details>

## Changelog
:cl:
tweak: adjusted ghost role spawn character's ID card as it doesn't show grey hud icon. (CentCom commander, Official, etc)
tweak: PDA now has a clickable link to turn on/off PDA auto-update. As long as it's On, PDA is automatically updated when it takes a card (Chameleon PDA still should do a manual update when you change appearance.)
fix: Ruin VIP's card gets their owner's name now.
/:cl:

### CODE REVIEW

**Comment by Dejaku51** [comment]
d

**Comment by EvilDragonfiend** [comment]
> d

too rushed to post it lol

**Comment by Mat05usz** [comment]
Very cool QOL, speed merge please.

**Comment by DerpiestBruh** [comment]
> Seeing crews not updating their PDA is not good too.

I feel like it's intended.

**Comment by EvilDragonfiend** [comment]
> > Seeing crews not updating their PDA is not good too.
> 
> I feel like it's intended.

maybe intentional sometimes, but I think most of them just forgot it, or don't know.

**Comment by EvilDragonfiend** [comment]
I think turning on/off auto-update button would be better.

**Comment by EvilDragonfiend** [comment]
now it's better

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
