### PR TITLE
Removes Deputy from the preferences menu

### PR DESCRIPTION
**Pull request by Penwin0**
## About The Pull Request
Removes Deputy from the preferences menu, as it can't actually be played.

## Why It's Good For The Game
Having a job that isn't actually playable be selectable in the preferences screen could be confusing

## Testing Photographs and Procedure

Screenshot_1877

## Changelog
:cl:
del: Removed Deputy from preferences menu
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
it was that simple the whole time?

**Comment by Penwin0** [comment]
Yes

**Comment by Penwin0** [comment]
Could probably remove the job itself as well

**Review by Rukofamicom — APPROVED** [review]

**Comment by Rukofamicom** [comment]
> Could probably remove the job itself as well

I'm waiting for this to be a coconut.png moment

**Comment by PowerfulBacon** [comment]
The only reason the job exists is a kind of jank way to get it to show on the HOP console.

**Pull request merged**
