### PR TITLE
Syndie Item Changes , Wave 2

### PR DESCRIPTION
**Pull request by enthethan**
## About The Pull Request
*removed the anxiety culture disease bottle from uplink on zeskos request.

𝗔 𝘁𝗼𝗻 𝗼𝗳 𝗰𝗵𝗮𝗻𝗴𝗲𝘀 𝘁𝗼 𝘀𝘆𝗻𝗱𝗶𝗲 𝗶𝘁𝗲𝗺𝘀 

Syndie minibomb explosion buffed.

frag grenade explosion buffed.

Gluon grenade stamina damage removed, rad amount changed from 350 to 1250

removed the "rounddown" aka weed remover clusterbuster

added the "honeymoon" aka beenade clusterbuster

added the bee grenade to regular uplink for 3 tc

buffed syndie magboots to not have slowdown, same as advanced magboots

𝗨𝗽𝗹𝗶𝗻𝗸 𝗞𝗶𝘁 𝗰𝗵𝗮𝗻𝗴𝗲𝘀:

removed the sabotage kit

recon kit :  added 2 minibombs

bloodyspai : added emag and 2 airlock charges

guns : removed c4, added 2 frag grenades, added 1 extra 357 speedloader

screwed : added thermal glasses and syndie magboots

murder : added a pill bottle with some meth pills, they are still dangerous if you take too much.

lordsingulo: added 2 c4

sniper: added 2 extra penetrator magazines and a  very sharp pen that does 16 damage and can be thrown for even more damage.

metaops : added 1 extra shotgun mag

bond : added 1 extra normal mag, 2 hollowpoint  mags, 1 ap mag, noslips and a combat knife

darklord: the dark hoodie is now lightly armoured

carpkit: added 1 extra carp grenade, 2 carp plushies and 2 sentience potions.
madscientist: 2 extra random clusterbusters

bee: the reskinned esword is replaced with "stinger" a 7 brute damage weapon that attacks quickly ( like gloves of the north star) and injects 3-5 units of histamine per hit. Also gets 1 extra bee grenade.

freeze: the temperature gun fires 4 projectiles like  a shotgun and consumes less energy, the esword was replaced with a slightly different one, this one does burn damage.

## Why It's Good For The Game

syndie minibomb : Currently it's as strong as a 100 waterpotassium grenade for 5 tc. This should make it more appealing to buy.

frag grenade :  too weak, needs a bit more kick.

gluon grenade : 350 rads is absolutely nothing, and in the freeze kit you only get 4, now it should be actually quite dangerous and not as easy to shrug off

roounddown : removing bloat in the random pool, a useless payload

honeymoon : should have been added before

syndie magboots : currently just reskinned regular magboots that make you valid salad.

sabotage kit : very similar to screwed and lord singulo kit no reason to have 3 "sabotage" kits.

dark lord: so you have a reason to not ditch the hoodie for regular armour

All of the other kits because people buying these kits is rare, and for good reason, MOST of them are alot weaker than you would imagine for spending 20 tc, this gives most kits more suitable and thematic equipment so that people might actually buy them  rather than just forgetting about them since its a 90% chance to gamble shit with a 10% chance to gamble gold.

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
imageadd: stinger sprites
/:cl:

### CODE REVIEW

**Comment by Lagomorphica** [comment]
The sabotage kit has airlock charges, no?

There's no other way to get them and they were good fun.

Ah well, no point in having redundant kits.

**Comment by enthethan** [comment]
Since bloodyspai kit is still lacking in overall usefulness (no very good weapon, destructive potential or good gimmicky items) I'll give it airlock charges

**Comment by zeskorion** [comment]
>carp kit
carp kit already has one of the most robust guns in the game, doesnt need a buff.

> honeymoon
*profuse sweating*

>beesword
turn that armor penetration down, jesus fuck. histamine injection already bypasses armor. the desc can be changed.

>beenade
the kit with 3 bee grenades costs about twice this iirc. these things can fuck shit up on a massive scale, turn that up to 5!

>minibomb
maybe just lower the cost a bit? upping the boom aint that much, their main use is the 1 tile devastation range

**Comment by enthethan** [comment]
> 
> 
> > carp kit
> > carp kit already has one of the most robust guns in the game, doesnt need a buff.
> 
yeah but it has limited ammo, you can dodge it just like any other gun, its a single shot before reloading and you can rest to not get hit.

> > honeymoon
> > _profuse sweating_
> 
> > beesword
> > turn that armor penetration down, jesus fuck. histamine injection already bypasses armor. the desc can be changed.
> 
it has 7 brute damage, bruh.
> > beenade
> > the kit with 3 bee grenades costs about twice this iirc. these things can fuck shit up on a massive scale, turn that up to 5!
> 
4 tc max because bees are easy to counter 
> > minibomb
> > maybe just lower the cost a bit? upping the boom aint that much, their main use is the 1 tile devastation range

cost was already reduced before, it should just be stronger than a grenade that takes 15 seconds to make.

**Comment by zeskorion** [comment]
> > > carp kit
> > > carp kit already has one of the most robust guns in the game, doesnt need a buff.
> 
> yeah but it has limited ammo, you can dodge it just like any other gun, its a single shot before reloading and you can rest to not get hit.
> 
> > > honeymoon
> > > _profuse sweating_
> > 
> > 
> > > beesword
> > > turn that armor penetration down, jesus fuck. histamine injection already bypasses armor. the desc can be changed.
> 
> it has 7 brute damage, bruh.
> 
> > > beenade
> > > the kit with 3 bee grenades costs about twice this iirc. these things can fuck shit up on a massive scale, turn that up to 5!
> 
> 4 tc max because bees are easy to counter
> 
> > > minibomb
> > > maybe just lower the cost a bit? upping the boom aint that much, their main use is the 1 tile devastation range
> 
> cost was already reduced before, it should just be stronger than a grenade that takes 15 seconds to make.

the beesword brute doest matter, turn down the armor penetration

bees are easy to counter with pierceimmune clothes, but that wont stop someone waltzing into a crowded room and igniting a bee grenade and pumping em all full of intropidril or what hvve you

**Comment by enthethan** [comment]
> 
> 
> > > > carp kit
> > > > carp kit already has one of the most robust guns in the game, doesnt need a buff.
> > 
> > 
> > yeah but it has limited ammo, you can dodge it just like any other gun, its a single shot before reloading and you can rest to not get hit.
> > > > honeymoon
> > > > _profuse sweating_
> > > 
> > > 
> > > > beesword
> > > > turn that armor penetration down, jesus fuck. histamine injection already bypasses armor. the desc can be changed.
> > 
> > 
> > it has 7 brute damage, bruh.
> > > > beenade
> > > > the kit with 3 bee grenades costs about twice this iirc. these things can fuck shit up on a massive scale, turn that up to 5!
> > 
> > 
> > 4 tc max because bees are easy to counter
> > > > minibomb
> > > > maybe just lower the cost a bit? upping the boom aint that much, their main use is the 1 tile devastation range
> > 
> > 
> > cost was already reduced before, it should just be stronger than a grenade that takes 15 seconds to make.
> 
> the beesword brute doest matter, turn down the armor penetration
> 
> bees are easy to counter with pierceimmune clothes, but that wont stop someone waltzing into a crowded room and igniting a bee grenade and pumping em all full of intropidril or what hvve you

Look jimbothy , im not gonna conform to your nerf culture of downsizing every stat because muh TOO STRONG MUH UNBALANCED, you're buying a random kit, you're not minmaxing for the best murderbone setup here, you could just as easily get something that is much harder to utilize not to mention its just a sword, and its just bees and its just a spear, all of which have a counter which i'll list:

Bees die fast(10 hp- single hit from toolbox, fire extinguishers, gas tanks...) , not to mention they aren't guaranteed to spawn with instadeath toxins, even initropidril bees give you a chance to run to medbay to chug charcoal(although a lot smaller chance than say cyanide or some other toxin)

It's just a sword it really is just a sword it suffers the drawback that while yes its a good melee weapon a ranged weapon is just gonna blast you while you can't do anything because you're not 1 tile away from your target, someone sees you with the sword? Hes gonna try to run away.

the Speargun is a single shot, easily dodgable through sidestepping or guaranteed dodge if you rest.

Hold your horses on the STATS TOO HIGH PLEASE NERF jimbus, not everything needs to be nerfed because you think it should and because this is a competitive combat simulator which needs to be balanced accordingly, unless some item or mechanic is just so strong its unfun and opressing to the rest of the playerbase every round it shouldn't be nerfed.

fin.

**Comment by zeskorion** [comment]
> > > > > carp kit
> > > > > carp kit already has one of the most robust guns in the game, doesnt need a buff.
> > > 
> > > 
> > > yeah but it has limited ammo, you can dodge it just like any other gun, its a single shot before reloading and you can rest to not get hit.
> > > > > honeymoon
> > > > > _profuse sweating_
> > > > 
> > > > 
> > > > > beesword
> > > > > turn that armor penetration down, jesus fuck. histamine injection already bypasses armor. the desc can be changed.
> > > 
> > > 
> > > it has 7 brute damage, bruh.
> > > > > beenade
> > > > > the kit with 3 bee grenades costs about twice this iirc. these things can fuck shit up on a massive scale, turn that up to 5!
> > > 
> > > 
> > > 4 tc max because bees are easy to counter
> > > > > minibomb
> > > > > maybe just lower the cost a bit? upping the boom aint that much, their main use is the 1 tile devastation range
> > > 
> > > 
> > > cost was already reduced before, it should just be stronger than a grenade that takes 15 seconds to make.
> > 
> > 
> > the beesword brute doest matter, turn down the armor penetration
> > bees are easy to counter with pierceimmune clothes, but that wont stop someone waltzing into a crowded room and igniting a bee grenade and pumping em all full of intropidril or what hvve you
> 
> Look jimbothy , im not gonna conform to your nerf culture of downsizing every stat because muh TOO STRONG MUH UNBALANCED, you're buying a random kit, you're not minmaxing for the best murderbone setup here, you could just as easily get something that is much harder to utilize not to mention its just a sword, and its just bees and its just a spear, all of which have a counter which i'll list:
> 
> Bees die fast(10 hp- single hit from toolbox, fire extinguishers, gas tanks...) , not to mention they aren't guaranteed to spawn with instadeath toxins, even initropidril bees give you a chance to run to medbay to chug charcoal(although a lot smaller chance than say cyanide or some other toxin)
> 
> It's just a sword it really is just a sword it suffers the drawback that while yes its a good melee weapon a ranged weapon is just gonna blast you while you can't do anything because you're not 1 tile away from your target, someone sees you with the sword? Hes gonna try to run away.
> 
> the Speargun is a single shot, easily dodgable through sidestepping or guaranteed dodge if you rest.
> 
> Hold your horses on the STATS TOO HIGH PLEASE NERF jimbus, not everything needs to be nerfed because you think it should and because this is a competitive combat simulator which needs to be balanced accordingly, unless some item or mechanic is just so strong its unfun and opressing to the rest of the playerbase every round it shouldn't be nerfed.
> 
> fin.

you're tossing these arbitrary armor penetration and such values on everything (i see it on the freeze sword as well!) as well. carp grenades will really fuck a guy up too- those guys do a bout 20 damage and dont care about people running around like autists.

this isn't hippie, where shit gets powercreeped and buffed because "it's fun". most of this shit *is* murderbone gear as well, and not good for much else. in that regard, it being as powerful as it is is not a good thing.

**Comment by enthethan** [comment]
> 
> 
> > > > > > carp kit
> > > > > > carp kit already has one of the most robust guns in the game, doesnt need a buff.
> > > > 
> > > > 
> > > > yeah but it has limited ammo, you can dodge it just like any other gun, its a single shot before reloading and you can rest to not get hit.
> > > > > > honeymoon
> > > > > > _profuse sweating_
> > > > > 
> > > > > 
> > > > > > beesword
> > > > > > turn that armor penetration down, jesus fuck. histamine injection already bypasses armor. the desc can be changed.
> > > > 
> > > > 
> > > > it has 7 brute damage, bruh.
> > > > > > beenade
> > > > > > the kit with 3 bee grenades costs about twice this iirc. these things can fuck shit up on a massive scale, turn that up to 5!
> > > > 
> > > > 
> > > > 4 tc max because bees are easy to counter
> > > > > > minibomb
> > > > > > maybe just lower the cost a bit? upping the boom aint that much, their main use is the 1 tile devastation range
> > > > 
> > > > 
> > > > cost was already reduced before, it should just be stronger than a grenade that takes 15 seconds to make.
> > > 
> > > 
> > > the beesword brute doest matter, turn down the armor penetration
> > > bees are easy to counter with pierceimmune clothes, but that wont stop someone waltzing into a crowded room and igniting a bee grenade and pumping em all full of intropidril or what hvve you
> > 
> > 
> > Look jimbothy , im not gonna conform to your nerf culture of downsizing every stat because muh TOO STRONG MUH UNBALANCED, you're buying a random kit, you're not minmaxing for the best murderbone setup here, you could just as easily get something that is much harder to utilize not to mention its just a sword, and its just bees and its just a spear, all of which have a counter which i'll list:
> > Bees die fast(10 hp- single hit from toolbox, fire extinguishers, gas tanks...) , not to mention they aren't guaranteed to spawn with instadeath toxins, even initropidril bees give you a chance to run to medbay to chug charcoal(although a lot smaller chance than say cyanide or some other toxin)
> > It's just a sword it really is just a sword it suffers the drawback that while yes its a good melee weapon a ranged weapon is just gonna blast you while you can't do anything because you're not 1 tile away from your target, someone sees you with the sword? Hes gonna try to run away.
> > the Speargun is a single shot, easily dodgable through sidestepping or guaranteed dodge if you rest.
> > Hold your horses on the STATS TOO HIGH PLEASE NERF jimbus, not everything needs to be nerfed because you think it should and because this is a competitive combat simulator which needs to be balanced accordingly, unless some item or mechanic is just so strong its unfun and opressing to the rest of the playerbase every round it shouldn't be nerfed.
> > fin.
> 
> you're tossing these arbitrary armor penetration and such values on everything (i see it on the freeze sword as well!) as well. carp grenades will really fuck a guy up too- those guys do a bout 20 damage and dont care about people running around like autists.
> 
> this isn't hippie, where shit gets powercreeped and buffed because "it's fun". most of this shit _is_ murderbone gear as well, and not good for much else. in that regard, it being as powerful as it is is not a good thing.

Random kits are there to spice item choice up with items you can't get individually for people don't want to minmax their 20 tc into most efficient murderbone potential every time, and currently they have no reason to buy random kits as 90% of them are garbage and only 10% are good(metaops,ninja,bee is alright not overpowered tho,darklord,) also metaops,ninja and darklord have a way lower chance to spawn as opposed to other weaker kits.

You really love the "this is not hippie" argument, and i  dont get where you're comign from,  its a   stupid argument im not copying or taking  hippiestation balance as an example or whatever you think im doing, im simply making changes to items that i think should be changed lol.

about the armour pen, on the mr freeze's esword ive reduced the block chance and damage slightly and to compensate added more armour pen, mostly just compensation for the block chance being reduced since its a bad mechanic and the stinger has purely offensive capabilites and almost no defensive capabilities save for the small block chance, it's not like an desword with energy reflection and 3/4 block chance, its stats and shit are weighted entirely into offense.

anyways i would like someone elses input on this rather than this nerf cow

**Comment by Isy232** [comment]
You're trying to balance what I see as pretty much murderbone gear. These objects are interesting and unique but mostly kill indiscriminately.

I would say remove most of the kits that make you go loud and add more that are stealthy items that work well together and fit a theme.

Your changes balance these kits well, its just that the kits are fundamentally broken.

Think about the carp grenade. Your target is the chemist, you get the carp kit. You see your target working in chemistry so you throw both carp grenades in and run.

However the chemist runs out of chemistry, into medbay hallway, the carps still chasing the chemist and they eventually get him. However, this round the medical staff are unrobust or just not able to grab a weapon to fight back and this leads to 2 medical doctors and 2 patients being treated as well as the CMO being killed. **BWOINK**

I do think you could justify it to an admin that you thought to try out a special kit but got one with tools only useful for murderboning, but I think I have proven the point that quite a few of these items are unsuited for MRP.

Also, some kits are still kinda useless just because they are outdated, see lord singulo for an example.

You've gotten me interested now, so if you are not going to keep changing these kits I would definitely be interested in trying.

**Comment by ike709** [comment]
This PR is too many balance changes at once, split it up into multiple PRs for further consideration.

**Pull request closed without merging**
