### PR TITLE
Adds defib(and more!) to syndicate lavaland base

### PR DESCRIPTION
**Pull request by super12pl**
## About The Pull Request
Adds defib to syndicate lavaland base. Why would syndie base have fully equipped medbay with sleepers vendors and medical supplies but not defib?

## Why It's Good For The Game
You can now do more than just saluting when your fellow syndicate scientist/comms agent dies.

## Changelog
:cl:
add: Adds defib, RPED and freezer board to syndicate lavaland base
/:cl:

### CODE REVIEW

**Comment by DatBoiTim** [comment]
Is it an RPED or an RPD?

**Comment by super12pl** [comment]
> Is it an RPED or an RPD?

its RPED - Rapid Part Exchange Device

**Comment by DatBoiTim** [comment]
> > Is it an RPED or an RPD?
> 
> 
> 
> its RPED - Rapid Part Exchange Device

Will they have any tools to do custom piping/atmospherics?

**Comment by super12pl** [comment]
> > > Is it an RPED or an RPD?
> > 
> > 
> > its RPED - Rapid Part Exchange Device
> 
> Will they have any tools to do custom piping/atmospherics?

they have RPD already

**Comment by DatBoiTim** [comment]
> > > > Is it an RPED or an RPD?
> 
> > > 
> 
> > > 
> 
> > > its RPED - Rapid Part Exchange Device
> 
> > 
> 
> > Will they have any tools to do custom piping/atmospherics?
> 
> 
> 
> they have RPD already

Implying I've played lavaland syndicate 😳

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
