### PR TITLE
Optimizes lighting

### PR DESCRIPTION
**Pull request by ike709**
https://github.com/tgstation/tgstation/pull/51546

## Changelog
:cl: bobbahbrown
refactor: Improved performance of lighting code
/:cl:

### CODE REVIEW

**Comment by bobbah** [comment]
hopefully it helps

xoxo,
bobbah

**Comment by ike709** [comment]
Seems to work fine.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by ike709** [comment]
@PowerfulBacon In most cases merge, don't just approve and leave it sitting forever.

**Comment by PowerfulBacon** [comment]
Still pending zesko's review

**Comment by ike709** [comment]
@PowerfulBacon Not anymore.

**Pull request merged**
