### PR TITLE
Always Dynamic

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

This sets Dynamic as the only gamemode.

## Why It's Good For The Game

This is essentially intended to counter the problem of security getting bored and deciding to hunt for antags, by giving them something to do. Dynamic is also at a point where it is a drop-in replacement for our gamemode system, and has most of the same features with far better midround handling. Minor midrounds can be very important for driving rounds, especially if the current traitors or other antags are ineffective or have lost. Overall from experience I think that dynamic plays much better when it's the sole gamemode, for a multitude of reasons resulting from increased midrounds and potential variety.

This is not a catch-all, and will not fix a lot of things, but I overall think this is an improvement to the antag-sec interaction.

Dynamic already includes extended as a gamemode, and it also includes every other currently enabled gamemode. The problems with strange interactions between conversion antags and traitors have been addressed, midrounds not spawning has been fixed, and the midround set has been expanded and rebalanced into a position I am comfortable with. The problem of too many traitors spawning on lowpop has been addressed, and the threat curve has been shifted on lowpop to be less aggressive.

## Testing Photographs and Procedure

N/A

## Changelog
:cl:
config: Set the gamemode permanently to Dynamic. No other gamemodes in rotation.
/:cl:

### CODE REVIEW

**Review by Crossedfall — APPROVED** [review]

**Comment by CydiaLamiales** [comment]
I do hope that dynamic checks for existing security officers before creating syndicate sleeper agents, else this will doom lowpop.

**Comment by itsmeow** [comment]
> The problem of too many traitors spawning on lowpop has been addressed,

**Comment by PowerfulBacon** [comment]
I got a ping like 2 days ago saying it wasn't fixed

**Comment by PowerfulBacon** [comment]
Midround injection override is pretty bad too

**Comment by PowerfulBacon** [comment]
Dynamic good things:
 - merging low threat antags together

Dynamic bad things:
- midround injection
- threat management on more extreme pops

**Comment by itsmeow** [comment]
> Dynamic good things:
>  - merging low threat antags together
> 
> Dynamic bad things:
> - midround injection
> - threat management on more extreme pops

We literally fixed these, that is what all my PRs were attempting to address

Just because it spawned a lot of antags a few times does not mean it is not fixed. The nature of dynamic is that sometimes it will break the rules we set for it. The goal is balancing how often. Which we did.

**Comment by itsmeow** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/7681

**Comment by BarteG44** [comment]
immensely based

**Comment by DrDuckedGoose** [comment]
> Dynamic bad things:
>     midround injection

Huh? That's the best part...

**Review by PowerfulBacon — APPROVED** [review]
I'm happy to go with this temporarilly, config is pretty easy to change if we need to pull it.

**Pull request merged**
