### PR TITLE
[Needs Vote] Ports Reebe Change from YogStation

### PR DESCRIPTION
**Pull request by Cenrus**
https://github.com/yogstation13/Yogstation/pull/6494

Reebe is now a circle, and the crew can attack from all angles instead of just south. Clock cult usually win against the crew, so I have chosen to give them more angles to attack from.

Could be fun, needs a test merge to see if the community like it or not.

newreebe

:cl: Readystorm546
rscadd: >whole new 360 clock cult map.
rscadd: >Changed arrows to a + so it makes more sense with this update.
rscadd: >Changed the clock cult paper to match the new map.
/:cl:

### CODE REVIEW

**Review by MarkSuckerberg — APPROVED** [review]
This is really good. I love the design, and said design would stop the ever-present meta defenses the clock cult always builds. Well, at least reducing them.

**Comment by Cenrus** [comment]
I played a round of clock cult on YogStation as the eminence, and this was the map. There a higher focus on combat than busting down walls, and it got really hectic and fun when the crew started attacking from all sides.

**Comment by ike709** [comment]
Clock cult is terrible and should be removed. TG doesn't even support it anymore, and neither should we.

**Comment by qwertyquerty** [comment]
I like it and think we ought to try it

**Comment by qwertyquerty** [comment]
Someone wanna update the wiki?

**Comment by Cenrus** [comment]
Will do, after it gets merged. I want the community feedback first

**Comment by boodaliboo** [comment]
stealing from my friend :(

**Pull request merged**
