### PR TITLE
replaces ishuman() to iscarbonhuman()

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
* replaces ishuman() to iscarbonhuman()

## Why It's Good For The Game
not a few coders confuse `ishuman()` is a check when they want a thing to human-species only, but the check is for `/living/carbon/human` which means it does to every species.
I see not a few code misused this, and I possibly expect future coders would mistake the same, but having a different name will let them recognise it's what not they're looking for.
Thus, this will decrease our code maintainability resource cost

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

this is basically like var change, and compile is fine

</details>

## Changelog
:cl:
code: ishuman() check is replaced into iscarbonhuman() - because not a few coders think ishuman() is a check to human-species only.
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
I feel like this is just one of those things, where anything more verbose doesn't really help, anything less verbose is confusing (like currently). It's moreso moving the problem and doesn't actually help.

ishuman() being for the type and not the species is just one of those things you find out, it's not super complicated a difference as soon as you see `ishuman_basic()`

**Comment by EvilDragonfiend** [comment]
> I feel like this is just one of those things, where anything more verbose doesn't really help, anything less verbose is confusing (like currently). It's moreso moving the problem and doesn't actually help.
> 
> ishuman() being for the type and not the species is just one of those things you find out, it's not super complicated a difference as soon as you see `ishuman_basic()`

I wouldn't be against what you're saying as long as the project is not open-source. As a contributor that would pay less time to understand codes, they'll have an issue to understand the difference between `ishuman()` and `ishumanbasic()` when they skim.
I know it's more verbose, but at least I am hoping it can make them think `why is there 'ishuman()'?` and lead them to see what they're supposed to use.

**Comment by Tsar-Salat** [comment]
Might as well go the full way and make all `/living/carbon/human` into `/living/carbon/humanoid.

Then, there is no definition confusion. When you want to check all species, use ishumanoid(), when you want to check humans alone, ishuman().

**Comment by EvilDragonfiend** [comment]
> Might as well go the full way and make all `/living/carbon/human` into `/living/carbon/humanoid`.
> 
> Then, there is no definition confusion. When you want to check all species, use ishumanoid(), when you want to check humans alone, ishuman().
> 
> At the present moment, I think a minor change like this won't actually solve the problem, and thus will just be a detriment.

maybe that's a better way to go, but I am not sure yet if maintainers would like to do so or are even happy with this, so I will wait for opinions.

**Comment by itsmeow** [comment]
Humanoid is much better, however, this is one of those legacy things that I'd like to keep consistent with other codebases. It's not so complicated to need to make porting things slightly more annoying, it's only confusing to brand new coders.

🔑

**Comment by EvilDragonfiend** [comment]
well, fair point

**Pull request closed without merging**
