### PR TITLE
New IPC Screens #1

### PR DESCRIPTION
**Pull request by Agateophobia**
Adds 2 new IPC screens and fixes Azlans little fuckup, so there are another 2 IPC screens <3
Ignore .gitignore (basically git ignores changes in beestation.dme) and beestation.dme (deleted it by accident) changes, my lil fuckup, I could do this in another pull but I'm lazy fuck

:cl: Agateophobia
tweak: Fixed two IPC screens
add: Added two IPC screens
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Did you mean to gitignore and remove beestation.dme?

**Comment by SomeAngryMiner** [comment]
before it gets merged, you gotta fix the travis checks, but in this case it appears he's dying about something in the maps, might need qwert or crossed to check that out, that or you forgot to update your branch.

**Comment by qwertyquerty** [comment]
No it's the fact that they deleted the environment file

**Comment by Crossedfall** [comment]
I was going to fix it for you to help out, but....

> Ignore .gitignore (basically git ignores changes in beestation.dme) and beestation.dme (deleted it by accident) changes, my lil fuckup, I could do this in another pull but I'm lazy fuck

If you're willing to take the time to explain the fuck up but unwilling to fix it, I'm unwilling to review your PR. Please re-open this PR or create a new one when you've fixed the issue.

**Pull request closed without merging**
