### PR TITLE
[Bounty] tgui: Version 3

### LINKED ISSUE #1582: Update TGUI
Right now, our UIs are a mixture of old original tgui and tgui-next. TG has announced their latest and greatest refactor for the near future, tgui 3.0: https://github.com/tgstation/tgstation/pull/50497

This is a bounty to bring bee's UIs fully up-to-date with 3.0 tgui and remove old tgui. TGUI 3.0 is significantly faster than old tgui, easier to develop for, and looks better.

Specific requirements to fulfill the bounty:

- Port the tgui 3.0 refactor
- Update/convert *every* tgui/tgui-next UI beestation has to tgui 3.0. Even if TG doesn't have a 3.0 version of it (which should only be 1 or 2 small UIs).
- Any HTML UIs that have been converted to tgui 3.0 by TG must also be converted here. This just consists of porting conversions from TG.
- Every UI must be functional. The bounty PR will be testmerged to ensure this condition is met.
- Old tgui/tgui-next code must be fully removed.

### PR DESCRIPTION
**Pull request by stylemistake**
## About The Pull Request

Ported nearly all UIs to the newest tgui framework.

Read this PR to see what's new in tgui v3: https://github.com/tgstation/tgstation/pull/50497

Closes #1582.

Unique BeeStation UIs were ported to tgui v3 as well: BottleDispenser, PatchDispenser, TurboLift.

I've done some preliminary testing, and a lot of things seem to work!

image
image

## What was not ported

I will most probably not port these UIs as part of this PR and bounty.

- Achievements (it's a lot more than just UI, and you don't have them)
- MedicalKiosk (is being ported by some other guy)
- RemoteRobotControl (Something fucky, don't remember what exactly)
- Bepis (New science machinery and additional content)
- BlackMarketUplink (Completely new item and additional content)
- VaultController (KS13 derelict)
- DnaConsole (It's fukken MASSIVE! https://github.com/tgstation/tgstation/pull/50225)
- NtosShipping (Shipment barcodes)
- Electrolyzer (Hydrogen gas)
- Roulette (apparently you deleted roulette in your codebase)
- MalfunctionModulePicker
- Gateway (touches a lot of files, very hard to port)

Some UIs were cut down to avoid some expensive work:

- NtosArcade
  - Doesn't print tickets which you redeem in the arcade machine.
  - Doesn't level your gamer skills.

Clockwork cult was deleted long time ago in tg, so no UI was ever made for it. I recommend removing this game mode completely.

## TODO

- [x] Include changes from this PR: https://github.com/tgstation/tgstation/pull/50613
- [x] ~~Fix maps: `snowdin.dmm:2907:error: undefined type: /obj/machinery/gateway/centeraway`~~

## Why It's Good For The Game

TGUI 3.0 is significantly faster than old tgui, easier to develop for, and looks better.

**TGUI v2 (tgui-next) and TGUI v1 (ract) are GONE!**

image

## Changelog
:cl:
add: added tgui version 3.
add: lots of new fancy interfaces to discover!
add: check out the new camera console and your modular tablets for cool apps!
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
image

**Comment by PowerfulBacon** [comment]
God damn that security cam viewer is hot

**Comment by ghost** [comment]
travis is kil

**Comment by ike709** [comment]
@BeloneX Read the TODO, nerd.

**Comment by Crossedfall** [comment]
Test merged onto both servers

**Comment by ike709** [comment]
~~Sleepers don't show what reagents people have in them.~~

Resolved.

**Comment by ike709** [comment]
Mining vendor seems to eat IDs with no way to remove.

also says `No registered ID card!` after close & reopen

**Comment by ike709** [comment]
Airlock Electronics board is busted.

**Comment by PowerfulBacon** [comment]
image

**Comment by MNarath1** [comment]
Can't say if it is related but i couldn't even open the Chemmaster UI at all

**Comment by MNarath1** [comment]
The portable air pumps setting  doesn't change the button to out trough it does change the setting to out from portable air pumps so it does pump it in the correct direction but without trying there is no way to know if its on in or out

**Comment by stylemistake** [comment]
> Can't say if it is related but i couldn't even open the Chemmaster UI at all

@man4fred what exactly happens when you try to open it?

**Comment by MNarath1** [comment]
> > Can't say if it is related but i couldn't even open the Chemmaster UI at all
> 
> @man4fred what exactly happens when you try to open it?

@stylemistake Nothing happens it doesn't open at all and no i haven't used the Chemmaster before in that round so its not because i accidentally minimized the window.

**Comment by SomeAngryMiner** [comment]
apparently this PR is breaking the gateway structure generation, for some reason.

**Comment by stylemistake** [comment]
Gateways, I'm afraid, are outside of my competence, they need some map editing.

**UPD:** I decided to remove the gateway rework, since it carries way too many changes to maps and related subsystems, it will take ages to port properly.

**Comment by VictorVow** [comment]
Had an issue using an air pump to fill tanks, it appeared to be set to "In" but despite being on didn't intake any gas. Clicking "In" again kept it as the same word but then started intake. 

Also it looks like canisters don't have a button for maxing output anymore.

**Comment by stylemistake** [comment]
It was fixed yesterday.

**Comment by Sinmero** [comment]
I think new ui broke nanites. Cant insert disk in the console anymore (only cloud), nanites do not replicate (always 100 vol), nanites do not sync with cloud.

**Comment by MNarath1** [comment]
> I think new ui broke nanites. Cant insert disk in the console anymore (only cloud), nanites do not replicate (always 100 vol), nanites do not sync with cloud.

Also things like public nanite chambers don't inject the nanites for some reason as they should do

**Comment by Cenrus** [comment]
Mining Vendor icons are all drinking glasses for some reason.

**Comment by MNarath1** [comment]
> > I think new ui broke nanites. Cant insert disk in the console anymore (only cloud), nanites do not replicate (always 100 vol), nanites do not sync with cloud.
> 
> Also things like public nanite chambers don't inject the nanites for some reason as they should do

Correction Nanites are pretty much completly broken you can write the programms and upload those to the cloud but you can't set a cloud id in the Nanite console and Public nanite chamber refuses to work entirely also even if you inject nanites the console will still say there are no nanites detected even trough a nanite scanner states otherwise but like that its pretty impossible to set a cloud id and you can't put a nanite program disk into the console so you can't even do that manually.

**Comment by Mat05usz** [comment]
There is a problem with sleepers UI. It should be brought back as it was, so general health info, then substances inside a person, and then buttons to give chems. Now it's health, buttons, and then substances which are cut out with a window border and you need to resize it. Please change the order as it was before the change and wrap the content so you don't have to resize anything.

**Comment by nikk735** [comment]
the computer id change console and clockwork thing doesnt work

**Comment by stylemistake** [comment]
> computer id change console

Which one? NTOS id card program?

You login with the card that is in your ID slot, not with the one you've inserted.

**Comment by Crossedfall** [comment]
> clockwork thing doesnt work

We're not supporting clockwork moving forward.

**Comment by nikk735** [comment]
yes no longer works

**Comment by nikk735** [comment]
Whattt everyone loves cock cult

**Comment by Cenrus** [comment]
image

Issues with solar input, this is likely because tg changed how their rotation works.

**Comment by Cenrus** [comment]
Probably going to see about getting clock cult removed from the repo after this, no point in supporting a gamemode which literally crashes the server.

**Comment by MNarath1** [comment]
Ok so public nanite chamber works now and most of nanites in generall but the voice sensor at least does not i can't say if that goes for all sensor programs i only tested it with voice sensors trough you can still manually pulse a code to activate a program with a nanite remote so that part works at least

**Comment by Ikalpo** [comment]
The new camera console does not work with borgs, you can tell if they are alive, but nothing appears on the screen

**Comment by stylemistake** [comment]
This is an oversight of this new camera system, and there is no easy fix for it. Although, people suggest that AI multicam mode might hold the solution.

**Pull request merged**
