### PR TITLE
Ports a few clothing items from Aurorastation and Skyrat

### PR DESCRIPTION
**Pull request by giacomoh**
## About The Pull Request

Ports a few items from Skyrat and Aurora station, and adds them to the loadouts

CREDITS:
medical coat and ordinary clothes made by Azarak (https://github.com/Skyrat-SS13/Skyrat-tg/pull/8524)ù
Watches, armchains, and bracelets made by Wowzewow https://github.com/Aurorastation/Aurora.3/pull/10951
skirtsuit and earrings made by TheStryker https://github.com/Aurorastation/Aurora.3/pull/10294 and https://github.com/Aurorastation/Aurora.3/issues/9390
flannel shirt made by Alberyk https://github.com/Aurorastation/Aurora.3/issues/2633
jackets made by ParadoxSpace https://github.com/Aurorastation/Aurora.3/issues/2633

## Why It's Good For The Game

More character customisation, and slighlty better loadouts. (a full loadout reorganisation will be done in my next PR)

## Testing Photographs and Procedure

</details>
I'm not going to include every piece of clothing, but here's a few. 

image
image
image
image
image
</details>

## Changelog
:cl:
add: Added new clothes
add: Added more categories to the loadout selection
Original authors: Azarak, Wowzewow, TheStryker, Alberyk, ParadoxSpace
/:cl:

CREDITS:
medical coat and ordinary clothes made by Azarak (https://github.com/Skyrat-SS13/Skyrat-tg/pull/8524)ù
Watches, armchains, and bracelets made by Wowzewow https://github.com/Aurorastation/Aurora.3/pull/10951
skirtsuit and earrings made by TheStryker https://github.com/Aurorastation/Aurora.3/pull/10294 and https://github.com/Aurorastation/Aurora.3/issues/9390
flannel shirt made by Alberyk https://github.com/Aurorastation/Aurora.3/issues/2633
jackets made by ParadoxSpace https://github.com/Aurorastation/Aurora.3/issues/2633

### CODE REVIEW

**Comment by giacomoh** [comment]
image
image
i'll fix this minor error.

**Comment by ItsTisme** [comment]
Armchain bit odd but I dont mind. Most stuff looks good but not super quirky or wierd

**Comment by giacomoh** [comment]
> Armchain bit odd but I dont mind. Most stuff looks good but not super quirky or wierd

I honestly added those just as "beecoin sinks". 
I don't like them either and would support not including them.
It's just that I've been told my other PR (lower loadout cost) wouldn't pass unless I were to add more "sinks".

**Review by PowerfulBacon — APPROVED** [review]

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Add port authors into the CL for merge.
🆑 your name, their name, their name, etc.
/:cl:

**Comment by giacomoh** [comment]
can do
EDIT: done

**Comment by giacomoh** [comment]
closing this PR  since i'm deleting this fork. I will make a new PR, with all the changes on another fork. Sorry for the inconvenience.

**Pull request closed without merging**
