### PR TITLE
Hopefully prevents some grief

### PR DESCRIPTION
**Pull request by imsynthex**
## About The Pull Request

Haha lets just give cargo unlocked PA and singulo generator crates, what could go wrong

## Why It's Good For The Game

Prevents griefing, or at least adds a few extra steps to it

## Changelog
:cl:
balance: Particle Accelerator, Tesla generator and Singularity generator crates now have locks on them that need engineering access to open
/:cl:

### CODE REVIEW

**Comment by DatBoiTim** [comment]
TBH why wasn't it like this before? Sensible way to stop Urist McGreytide from fucking something very destructive up, even if secured.

Should probably add an emag act to remove it though, so tater tots can still do it when appropriate.

You need to atomize heavily though. PA changes lumped into this may work under scope of griff prevention, but if hour changes get shot down a sensible change is being denied.

**Comment by imsynthex** [comment]
There, now it's just the crate changes, playtime restrictions can be handled in another PR

**Comment by ItsTisme** [comment]
It honestly should have a lock in the first place. would make sense

**Comment by PowerfulBacon** [comment]
Is ths /obj/structure/closet/crate/secure/engineering not locked to engineering by default?

**Comment by PowerfulBacon** [comment]
oh nevermind they came in a default crate, wow

**Pull request merged**
