### PR TITLE
Syndie Team Leaders start loudmode

### PR DESCRIPTION
**Pull request by TeomanTheGreat**
## About The Pull Request
Syndie nuke op team leaders start on loud mode (They can still toggle it back into normal mode via alt-click).

## Why It's Good For The Game
It is important for people to hear their leaders so this will be a bit of QoL. For those who do not want to be heard, you can just turn it back into normal text size via an alt-click on the headset as usual. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Testing nuke op team leader (Spawned myself as the syndie leader outfit and spoke):

image

</details>

## Changelog
:cl: Phil Smith
tweak: Nukie Team Leaders start on loud mode (can still go into normal mode via an alt-click on the headset)
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
Because they aren't already obnoxious enough.

**Comment by Archanial** [comment]
I'm fine with syndies starting with it but heads are kinda meh

**Comment by Daridine** [comment]
Doesn't this further devalue Loud Mode?
It seems like that should be used for important things, vs the shitposting most heads do with it.

**Comment by TeomanTheGreat** [comment]
> Doesn't this further devalue Loud Mode? It seems like that should be used for important things, vs the shitposting most heads do with it.

I don't see how this pr will affect that other than starting people off in loud mode. If they want to be quiet they can just turn loud mode off via alt-clicking on their headset. The only thing this pr will do is start heads of staff (and nukie team leader) headsets on loudmode (which be honest is what every head sets their headset to roundstart anyways).

**Review by Archanial — DISMISSED** [review]
Make this only apply to syndies

**Comment by TeomanTheGreat** [comment]
> Make this only apply to syndies

That kinda defeats half the pr no? I don't see why heads can't have it too since it is literally them starting loud and can click alt to go silent. Its QoL. If you are upset about heads shitposting with loud comms or something this pr won't exactly do anything about that.

**Comment by Archanial** [comment]
It does, yes. I only agree with half.

**Comment by TeomanTheGreat** [comment]
Allright then ill remove the parts with the heads of staff when I have time today.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
