### PR TITLE
[Port] Gravity fixes that i forgor

### PR DESCRIPTION
**Pull request by XeonMations**
## About The Pull Request

Forgot some fixes.

Ports the following TG station PRs:
- [x] https://github.com/tgstation/tgstation/pull/55037
- [x] https://github.com/tgstation/tgstation/pull/74285
- [x] https://github.com/tgstation/tgstation/pull/76104 ([Fixes runtimes from the forced gravity element being applied more then once](https://github.com/tgstation/tgstation/commit/941d0676114fd455a585f2c65ffc79b81e8438b7))
- [x] https://github.com/tgstation/tgstation/pull/88176
- [x] https://github.com/tgstation/tgstation/pull/88362

## Why It's Good For The Game

Simplemobs should not be floating and players should properly have their gravity updated

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/user-attachments/assets/ee17638f-f5fa-4750-80b8-c5554037535b

https://github.com/user-attachments/assets/d31d1ce7-1cbf-44e4-adf7-24125f649e21

https://github.com/user-attachments/assets/94f35d7d-67c7-4245-8cb6-7ee0c507d9d3

https://github.com/user-attachments/assets/ce553a46-10bc-45b7-ba84-3c36ed11e670

</details>

## Changelog
:cl: XeonMations, timothymtorres
fix: Fixed a lot of oversights related to gravity, such as lavaland not having gravity or simplemobs floating roundstart.
fix: You can no longer defy gravity through the power of love
/:cl:

### CODE REVIEW

**Comment by TwingoI** [comment]
First smooth movement butchers spinning and now I can't do handholding sessions in space? You people disappoint me....

**Comment by XeonMations** [comment]
Why the hell are gravity generators initialized after mobs are?

**Comment by PowerfulBacon** [comment]
> Why the hell are gravity generators initialized after mobs are?

The order of initialisation for atoms in the same map is undefined, it may initialise before or after the mobs placed on the map get initialised.

**Comment by XeonMations** [comment]
> > Why the hell are gravity generators initialized after mobs are?
> 
> The order of initialisation for atoms in the same map is undefined, it may initialise before or after the mobs placed on the map get initialised.

Either way, mob update_gravity will be called properly now then.

**Comment by Tsar-Salat** [comment]
> First smooth movement butchers spinning and now I can't do handholding sessions in space?

Ive had smooth movement fixes up for months.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
