### PR TITLE
Expands Departmental Mech Access for Roboticists

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
Gives the Roboticist and Research Director; Engineering, Medbay and Mining mech access.

## Why It's Good For The Game
Allows Roboticists (and RDs) to lock and conduct maintenance on mechs, similar to bots. No longer do you need to teach every single player how to lock mechs who will most likely just add EVERY single access that there is. This does not give the Roboticist or Research Director access to any doors, consoles or similar and is exclusively used for mechs.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
balance: Added Engineering Mech Access, Medbay Mech Access and Mining Mech Access to the Roboticist and Research Director.
balance: Changed mechs from requiring all the assigned keycodes to only one of them to enter.
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
Toastiest Warmie mentioned that this could be given on the Roboticist and Research Director on low-pop only. What are your thoughts of that?

**Comment by Admiral-Gigaton** [comment]
> Toastiest Warmie mentioned that this could be given to the Roboticist and Research Director on low-pop only. What are your thoughts of that?

the PR adds mech access from those departments, not actual access, so i dont think lowpop only is valid here. mech access is really just like for locking a mech to a department, or making a little mechbay only people with that department's mech access can access. if added to RD and robo, it just lets them use mechs that the [insert role here] locked to engie mech access, or lock it themselves to those departments. a little side note, though, is that RD should have sec mech access, but not robo. i mean, RD has brig access already, right?

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Roboticists and RD should not have unnecessary access to departments outside of their job. MECH_ENGINE is fine, but instead of giving them departmental access, the mechanics of mechs should be changed so that they can access the maintenance modes on them.

**Review by PowerfulBacon — APPROVED** [review]
Actually the CL is just poorly worded, looking at the code this is only giving them the mech access requirements which is fine.

**Comment by Tsar-Salat** [comment]
Removing my -1, your title gives the wrong impression.

Recommend changing it to something like 'Expands departmental mech access for Robotocists'

**Comment by MarkusLarsson421** [comment]
> RD has brig access already, right?

They have Brig access but not Security access, of which gives access to the security lockers and the security techfab.

I am not 100% certain as I write this but I think the RD can not access Beepskies' interace of which requires Security access. 

These chances I am making mirror the similar access the Roboticist and RD has for bots.

**Comment by MarkusLarsson421** [comment]
Would it be controversial and crazy to not give the Research Director these mech accesses during high-pop? It could enable antagonist Roboticists to more securely lock a mech and practically limit its access to only the Captain and themselves. 

This is something a non-antagonist Roboticists could also make use of as a sort of bootleg DNA lock. I don't like the idea of it being used as a bootleg DNA lock. What do everyone else think of it?

**Comment by PowerfulBacon** [comment]
> Would it be controversial and crazy to not give the Research Director these mech accesses during high-pop?

This honestly seems fine to me, the department leads are meant to command their subordinates rather than do all the work themselves.
As for bootleg DNA locking, you could just make it so that its relatively easy to hack mechs and bypass their access requirements with a multitool or something (or make it so that you only need 1 of the access to use the mech rather than all of them).

**Comment by MarkusLarsson421** [comment]
Changed it so you only need one keycode to enter the mech.
https://cdn.discordapp.com/attachments/943311132007997490/1184945126318018650/0001-8325.webm

**Comment by Admiral-Gigaton** [comment]
> Changed it so you only need one keycode to enter the mech.
> 
>  0001-8325.mp4

not gunna lie here mans this seems kinda stuppy to make it only need one keycode, defeats the purpose (that i know of) of the whole thing. its like setting a literal padlock for it, or security pin. i dont enter one number of a code into a lock to open it, but i mean, im not the coder here, let alone is it my PR. do whatchu want, this just seems like it isnt going to go well for it

**Comment by PowerfulBacon** [comment]
> not gunna lie here mans this seems kinda stuppy to make it only need one keycode, defeats the purpose (that i know of) of the whole thing. its like setting a literal padlock for it, or security pin. i dont enter one number of a code into a lock to open it, but i mean, im not the coder here, let alone is it my PR. do whatchu want, this just seems like it isnt going to go well for it

Tbh I would just remove the ability to lock mechs entirely to emphasise the danger and risk of leaving them around

**Pull request merged**
