### PR TITLE
Some orbital map improvements + supercruise code changes

### LINKED ISSUE #6167: Weirdness with Mining Shuttle Console
Pressing the "zoom in" or "zoom out" button on a Mining Shuttle Console, then attempting to scroll down, will cause the window to scroll down to an area without any element. It's just the default background.

Issue reported from  Round ID: 35316 (BeeStation Acacia - Roleplay 2)

Reporting client version: 514.1572

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Takes some of the code improvements and supercruise map updates from the cancelled weapons branch.

 - The orbital map now looks a lot better, with the ability to change how objects on the map are rendered
 - The javascript code is now a component, so can be added to other tgui interfaces with a lot less copy-pasting
 - The orbital vector code has had its procs cleaned up to make more sense
 - Map objects in the autopilot list are now sorted by priority.

The sorting is done in order of:
 - Lavaland
 - SS13
 - Phobos
 - Shuttles
 - Beacons
 - Meteors

**Planets**

image

**Beacons**

(The ring is pulsating at a random interval)
image

**Default**

image

**Shuttles**

image

## Why It's Good For The Game

The map looks a lot nicer now

## Changelog
:cl: PowerfulBacon, KubeRoot
tweak: Changed how the orbital map looks.
tweak: Objects on the orbital map autopilot target list are now sorted by priority.
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Fails CI

**Comment by PowerfulBacon** [comment]
Fixed, bad copy and paste from another branch.

**Review by ike709 — DISMISSED** [review]
Fix the thing

**Comment by ike709** [comment]
image

**Comment by PowerfulBacon** [comment]
TODO: Test this with merge deconflicts

**Review by PowerfulBacon — COMMENTED** [review]
image
image

**Comment by PowerfulBacon** [comment]
Going to remove the really silly reference manager part of this, since it is improved in a follow up PR.

**Review by Archanial — APPROVED** [review]

**Pull request merged**
