### PR TITLE
Re:Readds the headcrab back into the golden slime pool. No zesko edition.

### PR DESCRIPTION
**Pull request by Moccha-Bee**
About The Pull Request
Yeah that's right its back, since lings got nerfed and mrp is just lrp and rounds rarely go over 50 minutes this addition will be more than balanced,
image

Last time zesko closed the pr like the tard he is, let the other maintainers voice their opinions.

Why It's Good For The Game
Slugs have always been funny creatures and now they can be spawned with the golden slime hostile injection, and since changelings have been nerfed, now is time for the comeback..

Changelog
🆑
add: HeadCrab back into the golden slime hostile pool.
/🆑

### CODE REVIEW

**Comment by SomeAngryMiner** [comment]
yike.

**Comment by february-ops** [comment]
i think it would be more interesting with they were slime themed and got abillities that made sense for a thing coming from xenobio instead of being just a normal ling

**Comment by Moccha-Bee** [comment]
> i think it would be more interesting with they were slime themed and got abillities that made sense for a thing coming from xenobio instead of being just a normal ling

they get half the dna points a normal ling does iirc

**Comment by february-ops** [comment]
> they get half the dna points a normal ling does iirc

no like i mean instead of having ling abilities they could have more of a slime theme vibe

**Comment by Moccha-Bee** [comment]
> > they get half the dna points a normal ling does iirc
> 
> no like i mean instead of having ling abilities they could have more of a slime theme vibe

that would have to be an enterily different process

**Comment by ModDownloading** [comment]
Maybe have them only able to get basic ling abilities, like armblade, dna extraction and transform but not stuff like cryosting or ling armor?

**Comment by Isy232** [comment]
It does not belong in the golen slime pool, it belongs in a gold/rainbow crossbreed pool.

**Comment by Moccha-Bee** [comment]
> It does not belong in the golen slime pool, it belongs in a gold/rainbow crossbreed pool.

where did you see golen in the pr?

**Comment by zeskorion** [comment]
If a maintainer closes a pr, and you just reopen it, that is grounds for a repoban should it continue

**Pull request closed without merging**
