### PR TITLE
Separate HIDEJUMPSUIT into 3 types: hide jumpsuit / tail / wings

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
Separate HIDEJUMPSUIT into 3 types: hide jumpsuit / tail / wings

* **hide Jumpsuit:** It is an actual game balance that prevents people to see jumpsuit when examined.
* **hide tail:** This is also an actual game balance but less important, and is mostly related to identifying a person (likely if someone is a lizardperson or a felinid, etc) Mostly flavour related.
* **hide wings:** Nothing different from tail one

NOTE: This mainly affects costums that have no armor features (except for special armors like wiz robe). Actual armors like antagonist robe will still hide your tail and wings.

## Why It's Good For The Game
Because your jumpsuit is hidden, hiding everything (your tail and wings) doesn't make sense.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
tweak: Some equipment now shows your tail & wings. Most important armors (usually antag armors) still don't show your tail & wings not to expose your identity if you're a lizardperson or a felinid.
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
> * Mostly flavour related.

how though.

Usually when people pick moths, lizards, and felinids, its because they want these traits to show.

This is especially true for moth players, who have very little customizability in the first place, choosing stuff like wing colors is very important.

I guess this would make sense in the context of a LRP server, but this really isnt good for RP or letting players express themselves.

**Comment by EvilDragonfiend** [comment]
> I would really consult moth and lizard players before continuing this.

maaaybe voote.

The changes are mostly applied to non-armor suits (including some special armors), so that it changes nothing much.
If a suit shows your armor, it means the suit is for a kind of cosplay, and it fits its purpose.

**Comment by PowerfulBacon** [comment]
This just makes sense. If a suit covers the entire body then it should hide the jumpsuit, tail and wings

**Comment by EvilDragonfiend** [comment]
> This just makes sense. If a suit covers the entire body then it should hide the jumpsuit, tail and wings, although the list needs proper curating

It's at grey area, and that's why I said it doesn't make sense. Hiding your entire body, of course, hides your entire jumpsuit including your tail and wings, and it's how space suits and actual armors work.
BUT hiding your entier jumpsuit doesn't mean it hides youe entire body, thus it doesn't mean it always hides your tail and wings, and most costumes will go into this.

**Comment by Tsar-Salat** [comment]
> he changes are mostly applied to non-armor suits (including some special armors), so that it changes nothing much.

Alright.

Why are hardsuits included though? I feel like space gear and lavaland gear should be excluded, because ashlanders will have no reason to hide their tails, and moths use wings for balance and flight in zero gravity.

**Comment by Pirill** [comment]
Don't care particularly much about the jumpsuit myself but I'd like the mutant parts to be toggle-able as an IC verb instead. That way you can decide when and if you want to hide them and it makes it a lot less annoying to categorize valid equipment for it specifically when it's mostly a cosmetic/RP tool.

**Comment by Fronsis** [comment]
> This just makes sense. If a suit covers the entire body then it should hide the jumpsuit, tail and wings, although the list needs proper curating

Not necessarily it can cover ''the entire body'' but be tailored in a way that they have a space for that race to show their wings, tails, ears, etcetera, think about fantasy armor and how it plays out, sometimes unrealistics allows more ''fantasy'' to show up even if it doesn't necessarily make sense (see for example the famous bikini armor on females or ear slots in helmets)

I'd say it makes sense for hardsuits and those that are supposed to be pressurized to cover them but a regular jumpsuit shouldn't tbh, if this goes to voting most people will choose to want their character fluff to be shown on basic gear

**Comment by EvilDragonfiend** [comment]
> Alright. That explanation is fine for those items.
>
> Why are hardsuits included though? I feel like space gear and lavaland gear should be excluded, because ashlanders will have no reason to hide their tails, and moths use wings for balance and flight in zero gravity.
>
> Antag stuff or cosplay stuff make the most sense with this PR, other stuff not so much

I didn't specify the full list, but the PR suggests:
* space suits that need pressure protection hide your tail and wings (because it makes sense)
* space suits (costume - doesn't actually protect pressure) will not hide your tail and wings
* 90% of costumes will not hide your tail and wings
* some 'special' space suits like debug-min suit will not hide your tail and wings, because the debug space suit is already doesn't make sense.
* Thunderholme armors will not hide your tail and wings, because it's not a standard game armor, only used in CTF
* some antagonist armor wouldn't hide your tail and wings because you'd want your identity hidden. (i.e. ling's chit armor)
* Some armors like drake armor/bone armor/most chaplain armors will not hide your tail and wings, because these are not for pressure protection but also doesn't have to have an identity-hiding feature.


and at this point, I am suggested with Skyrat's way, and I think that'll work, I think. so that you can decide you're going to hide your tail and wings whenever you want or not even if you wear some armor (not space suits), while space suits will forcefully hide your tail and wings because an exposed part to space isn't a thing.

**Comment by EvilDragonfiend** [comment]
Closing for right now. It will need to be improved with these changes:
* You can decide to expose or hide your tail & wings whenever you want while you're wearing a suit.
* You can't hide your tail & wings if you don't wear any external suits.
* You get a mood penalty when your suit is not the proper equipment to hide your tail and wings.
example) space suits have space to hide your tail and wings. jackets are possible to hide your tail and wings, but it needs your effort to hide these, so you get a mood penalty (as it's improper gear)
* Pressure-protection suits (most space suits) will lose its ability to protect you against pressure when you exposed your tail & wings.
so you can reveal your tail in the space, but you'll lose pressure-protection.

someone suggested this can be used to protect yourself from Asimov, and I think it's potential.

**Pull request closed without merging**
