### PR TITLE
Cakehat

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Reduces the cake hat's damage from 15 to 12, a minor decrease to make it less powergaming for people to rush so I don't have to care about it anymore.

## Why It's Good For The Game

if u disagre ban 4 powergaym 

## Changelog
:cl:
balance: nerfs the cake hat to have the equivalent amount of damage as the toolbox
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
How is the 15 damage cakehat traitor tier?

**Comment by PowerfulBacon** [comment]
> 
> 
> How is the 15 damage cakehat traitor tier?

I mean its 3 off the epen, more than a toolbox and can be worn on the head (so transported anywhere without using even backpack space) while being completely free, but people would get mad and be like 'you can't ban for powergame for having a cake' if its not nerfed instead

**Comment by Flakkyboo** [comment]
people will kill eachother over this hat. good change

**Comment by ACanOpener** [comment]
people will kill eachother over this hat. bad change

**Comment by zeskorion** [comment]
> > How is the 15 damage cakehat traitor tier?
> 
> I mean its 3 off the epen, more than a toolbox and can be worn on the head (so transported anywhere without using even backpack space) while being completely free, but people would get mad and be like 'you can't ban for powergame for having a cake' if its not nerfed instead

Cakehat is overrated. While it can be worn, something like a circular saw or surgical drill can fit in a medical belt, and an upgraded welder is just as good as a weapon while fitting in a smaller space

**Comment by Flakkyboo** [comment]
I'm not the biggest fan of it being unlimited uses tbh. Maybe loading it with candles when one runs out as a suggestion

**Comment by Dingo-Dongler** [comment]
> 
> 
> > > How is the 15 damage cakehat traitor tier?
> > 
> > 
> > I mean its 3 off the epen, more than a toolbox and can be worn on the head (so transported anywhere without using even backpack space) while being completely free, but people would get mad and be like 'you can't ban for powergame for having a cake' if its not nerfed instead
> 
> Cakehat is overrated. While it can be worn, something like a circular saw or surgical drill can fit in a medical belt, and an upgraded welder is just as good as a weapon while fitting in a smaller space

Those things require department access. I think making do with what your department provides is better than grabbing random stuff around. Assistants are entitled to nothing.

**Comment by zeskorion** [comment]
> > > > How is the 15 damage cakehat traitor tier?
> > > 
> > > 
> > > I mean its 3 off the epen, more than a toolbox and can be worn on the head (so transported anywhere without using even backpack space) while being completely free, but people would get mad and be like 'you can't ban for powergame for having a cake' if its not nerfed instead
> > 
> > 
> > Cakehat is overrated. While it can be worn, something like a circular saw or surgical drill can fit in a medical belt, and an upgraded welder is just as good as a weapon while fitting in a smaller space
> 
> Those things require department access. I think making do with what your department provides is better than grabbing random stuff around. Assistants are entitled to nothing.

welder costs only 80 creds

**Comment by PowerfulBacon** [comment]
> > > > > How is the 15 damage cakehat traitor tier?
> > > > 
> > > > 
> > > > I mean its 3 off the epen, more than a toolbox and can be worn on the head (so transported anywhere without using even backpack space) while being completely free, but people would get mad and be like 'you can't ban for powergame for having a cake' if its not nerfed instead
> > > 
> > > 
> > > Cakehat is overrated. While it can be worn, something like a circular saw or surgical drill can fit in a medical belt, and an upgraded welder is just as good as a weapon while fitting in a smaller space
> > 
> > 
> > Those things require department access. I think making do with what your department provides is better than grabbing random stuff around. Assistants are entitled to nothing.
> 
> welder costs only 80 creds

How much damage does it do, I thought welder did less than toolbox

**Comment by Arrfur** [comment]
Toolbox does 12 damage, welder does 15.

_le funny coders dont play the game meme has arrived_

EDIT: HOLY SHIT I JUST REALISED YOU CAN PUT WELDERS INTO A POCKET SO YOU DONT NEED TO TAKE UP BACKPACK SPACE!!! AND ALSO THEY ARENT DEPARTMENT LOCKED HOLY SHIT... 

THATS ONLY 3 OFF OF AN EPEN BRO.....

Realshit, dont nerf shit because you got killed by it? SS13 isnt a fucking moba that needs god tier balancing and every department should have a 50% win rate lol.

just let ss13 have its charm. 😐

**Comment by Flakkyboo** [comment]
And cakehat doesn't need to be refueled like a welder. More damage than a toolbox In a convenient hat slot with no fuel requirement.

**Comment by Arrfur** [comment]
god forbid one* (1) person in the server has access to a welder that doesent need to be refuelled!

_*excludes CE, Engineers, Research Staff, and anyone with access to a protolathe_

I mean, its not like the e-pen is supposed to be very weak or anything, it is truely the great milestone for all weapon balance..

**Comment by Archanial** [comment]
I disagree, ban me

**Comment by utilbird** [comment]
removing assistant culture for "balance reasons" it's not even that strong and it prevents people from using something like the welding helmet, a very easy to find source of flash protection. Sure, they could put the cake in their bag but at that point it's just taking up excessive space.

also, epens should be buffed

**Comment by PowerfulBacon** [comment]
Ok I agree with the comments, I am just going to reduce the damage from 15 to 12 instead so its more inline with a toolbox. Having 12 damage will still have good damage but isn't exactly powergaming to rush since there are multiple items easily accessible from anywhere that have the same damage

**Comment by Archanial** [comment]
> 
> 
> Ok I agree with the comments, I am just going to reduce the damage from 15 to 12 instead so its more inline with a toolbox. Having 12 damage will still have good damage but isn't exactly powergaming to rush since there are multiple items easily accessible from anywhere that have the same damage

If the rushing is a problem, remove it from maps.

**Comment by Arrfur** [comment]
100 / 15 = 6.6666
7 Hits to crit
100 / 12 = 8.333333
9 hits to crit

15 down to 12 is a much bigger nerf than it looks.
I've said it before and I've said it again, cakehat doesen't need to be nerfed?

But hey, its not like the entire charm and flavour of ss13 is neat little interactions between funny , quirky objects!

(next you should nerf donk pockets spawning in engineering. Blatant powergame.)

**Comment by Arrfur** [comment]
unless...? hahah.. noo that would never work... but perhaps? ahah! he would never do that hahahaha...... but what if..... maybe.... you just didnt fuck with stuff for no reason?

**Comment by PowerfulBacon** [comment]
Making the hat do as much damage as a toolbox so its not powergaming to rush every round isn't going to completely destroy SS13 and remove the culture from the game. The hat is still there, the hat still does damage, the hat can still be worn on the head. It is now inline with other common items meaning you could either take a toolbox or the hat with the advantage for the hat being that you can wear it. Replacing tasers with disablers for balance reasons and other changes to classic items like that never killed the culture of SS13.

**Comment by zeskorion** [comment]
> Making the hat do as much damage as a toolbox so its not powergaming to rush every round isn't going to completely destroy SS13 and remove the culture from the game. The hat is still there, the hat still does damage, the hat can still be worn on the head. It is now inline with other common items meaning you could either take a toolbox or the hat with the advantage for the hat being that you can wear it. Replacing tasers with disablers for balance reasons and other changes to classic items like that never killed the culture of SS13.

but 15 damage isnt a big balance issue

**Review by zeskorion — APPROVED** [review]

**Pull request merged**
