### PR TITLE
[Ready] Resprites MedSci uniforms & backpacks, sorts icon files internally

### PR DESCRIPTION
**Pull request by Agameofscones**
## About The Pull Request

Feat Azlan.

Resprites all Medical & Science uniforms in the style established by the Security Dept. jumpsuits. Further moves Bee away from the coder-sprite gore that is TG station and more towards a generally agreed upon pixel art style among the active members of the discord's spriter channel.

Internally sorts the affected icon files in the same style that we just sorted them internally on Colonial Marines with 'marker' icons that describe the set of icons immediately proceeding them. Clumps all icons by department and within each marker set, by similarity and type. All adjustable versions of the jumpsuits `_d`,`_l`,`_t`, are placed next to their associated base icon. No more hunting for an icon in a dmi after identifying it in the code. No more disorganized sprite sheets. Makes sprite maintenance far far easier in the future.

Adds a few alternative jumpsuits to the affected departments and changes the descriptions of existing uniforms to better match their actual visual representation.

Icon marker sorting:
image
RD's mad science labcoat:
image
CMO's jumpsuit up close:
image
image
image
image
image
image
image

WIP checklist:
~~Clean up Brig Physician's jumpsuit and add alternative~~Out of scope
- [x] Add object icons for new labcoats
- [x] Replace object icon placeholders for medsci
~~Convert RD's existing alternative uniforms to new style~~ Out of scope
~~Replace roboticist's "anime mech flightsuit" with something more sensible~~ Out of scope
- [x] Icon marker sort ~~(obj) suits.dmi, suit.dmi,~~ (obj)uniforms.dmi
- [x] Make dept. backpacks not clash with new jumpsuits and update their colors
- [x] Make white shoes not clash with new jumpsuits
- [x] Update RD select equipment verb
~~Update locker and vendor contents with new alternate jumpsuits~~ Out of scope
~~Make Travis place nice with the branch~~ Something to do with the catsurgeon, not my problem.

## Why It's Good For The Game

1. '_Further moves Bee away from the coder-sprite gore that is TG station_'
Differentiates Bee visually from similar servers while remaining gameplay readable and generally improves the quality of sprites across the board (hopefully) helping to set a standard for future content.

2. Helps decrease require sprite maintenance and headache on the development side with the .dmi sorting. Fixes some inconsistent visuals with inconsistent sprite names (see bluesuit to blue_slacks) decreasing coder headache.

3. Alternate jumpsuits are usually something people enjoy as long as they're tonally and visually consistent with the rest of the game. Even minor changes can help express character. I think this is especially important in the MRP environment when it comes to establishing a consistent character within the setting and building verisimilitude.

## Changelog
:cl: Triiodine (Feat. Azlan)
add: Added a standard styled Research Director's jumpsuit and associated labcoat. Comes with one free middle school science fair medal.
spellcheck: Changed the name of the purple bartender's jumpsuit to purple bartender's skirt. Lawyer's blue suit to blue slacks. Lawyer's black suit to black slacks
spellcheck: Changed the description of the CMO's labcoat, blue slacks, and black slacks.
imageadd: Resprited the Medical Doctor's, Chief Medical Officer's, Geneticist's, Chemist's, and Virologist's, jumpsuits and labcoats.
imageadd: Resprited the Mad's green labcoat.
imageadd: Resprited the Chemist's, Virologist's, Scientist's, and Geneticist's backpacks and satchels.
imageadd: Resprited the Medical Doctor's backpack.
tweak: Spriters and coders rejoice, the uniforms mob and object sprite sheets have been sorted and match each other in layout.
/:cl:

### CODE REVIEW

**Comment by Coolsurf6** [comment]
Yo these looks really well done.

**Comment by qwertyquerty** [comment]
Conflicts

**Comment by Agameofscones** [comment]
> Conflicts

never were any gamer. Cat surgeon acting up

**Review by qwertyquerty — APPROVED** [review]

**Comment by ike709** [comment]
No reported issues.

**Comment by eLeCtrOssSnake** [comment]
I don't like them, at all, and I belive I am not the only one who hates these DUMB FUCKING DARK OUTLINES, THIS IS NOT COOL

**Pull request merged**
