### PR TITLE
Removes Shadow Sect

### PR DESCRIPTION
**Pull request by Programs-The-Station**
## About The Pull Request

The Shadow Chaplain Sect is basically just used to murderbone. Yes, it requires collaboration with science, but it's fairly easy to do. The sect needs to be reworked to be less murderboney, and should just be disabled until #11766 is merged.

From the antag themselves:
image

(Yes, this is a blatant I Ded PR, please appropriately tag)

## Why It's Good For The Game

This sect needs a rework, and causes lots of problems in dead pop. This last round, the round was held effectively hostage because everyone died to the shadow creatures so nobody could call the shuttle, and it was on green alert. 

I left in all the code so that the sect can be granted, but is not available unless admin bussed (I think). I could strip it out completely if desired.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
tweak: Disabled Shadow Sect from being available. 
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
You need to remove chap traitor item too

**Comment by PowerfulBacon** [comment]
I don't think this is needed, we could just merge the other PR

**Comment by Rukofamicom** [comment]
> we could just merge the other PR

The author of the other PR has placed their priorities elsewhere and it is not ready to merge. It's been weeks without an update:

image

**Review by Rukofamicom — APPROVED** [review]
I will be merging this in a day unless I am explicitly blocked. I will ping @PowerfulBacon if they don't reply here again to be sure they're okay with it and understand why this is a good idea, or can voice further concern if they don't think it is.

**Comment by EvilDragonfiend** [comment]
Well, Let's just remove the code fully. Ro agreed with it the full removal.
Please remove the shadow sect dm.
I believe redesigning the sect will make the situation better.

**Comment by Programs-The-Station** [comment]
> Well, Let's just remove the code fully. Ro agreed with it the full removal. Please remove the shadow sect dm. I believe redesigning the sect will make the situation better.

Done.

**Review by EvilDragonfiend — APPROVED** [review]
Space Matthew 4:10 - "Away from Me, Space Satan!" Space Jesus said.

**Pull request merged**
