### PR TITLE
Random Reagent changes

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
changes up random reagents somewhat. 
-completely removes basic chemistry reagents, drink reagents, food reagents, and some reagents that do barely anything from the random reagent pool, making nearly  every chem at least have an effect.
-there are now two types of random reagent- restricted and unrestricted. Restricted will only spawn synthable chems, while unrestricted can spawn almost anything not mentioned above that isnt a blob toxin. Currently the only unrestricted method is floorpills
-makes a few more chems unsynthable
## Why It's Good For The Game

mostly, no longer going to get a bunch of booze from floorpills, strange seeds, etc. nerfs reagents from farming up strange seeds to compensate for the easier pool

## Changelog
:cl:
tweak: no more booze(and other lame shit) in your stange seeds/floorpills/whatever 
tweak: unrestricted floorpills
balance: restricts several more powerful chems from farmable methods
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
The vote for this is very controversial, I'm not sure how I feel about it.

**Comment by zeskorion** [comment]
> The vote for this is very controversial, I'm not sure how I feel about it.

perhaps testmerge it for a week and hold another vote to see if people like the changes or not

**Comment by qwertyquerty** [comment]
It's hard to get a good player consensus about a running testmerge, since most will likely vote without trying something out for themselves at all.

**Comment by zeskorion** [comment]
> It's hard to get a good player consensus about a running testmerge, since most will likely vote without trying something out for themselves at all.

well, lemme put it this way:

image



I think it's a warranted change. Note i only clicked the bottom corner of this pile, and the majority isnt THAT even, near two thirds

**Comment by Sun-Soaked** [comment]
Idea: Why not keep the more powerful chems on the spawn table, but apply a probability malus to them? That way, their previous rarity is maintained, even among the smaller, more functional chem list. If the fact that this somewhat significant nerf is now a minor buff bothers you, you could calculate their original chance of being spawned and reduce it significantly below that number, balancing out the fact that the chem table is more forgiving with the fact that the extremely valuable chems are harder to find, while still maintaining them as a possibility and thus quieting the complaints of botany mains.

**Comment by eLeCtrOssSnake** [comment]
My vote is no.

**Comment by qwertyquerty** [comment]
fix conflicts

**Comment by zeskorion** [comment]
> fix conflicts

looks like i'm gonna hafta repull this cuz i cloned my master awhile back

**Comment by zeskorion** [comment]
repulled

**Pull request closed without merging**
