### PR TITLE
Fastplosions II: Attack of the Maxcaps

### PR DESCRIPTION
**Pull request by cerebral-314**
## About The Pull Request

This will make explosions almost instant.
Credits: https://github.com/tgstation/tgstation/pull/50594

## Why It's Good For The Game

Hollywood jumping away from explosions is bad. Multiple explosions used to bring the server to it's knees.

## Changelog
:cl:
add: Nuke now creates a proper crater.
balance: No longer can run away from explosions.
refactor: Explosions is now a subsystem.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Does the nuclear bomb still freeze the server for a few seconds?

**Comment by cerebral-314** [comment]
> 
> 
> Does the nuclear bomb still freeze the server for a few seconds?

Yes, it freezes due to the code adding every turf on the station to the explosion list. This really wasn't noticeable for me though due to the timer taking 4ish seconds anyway. When the station goes boom the nuke does so as well. The explosion I've added to make the crater proves that. You can hear the explosion at the same time.

**Comment by cerebral-314** [comment]
Lowered the subsystem's priority... seems to have fixed it.

**Comment by PowerfulBacon** [comment]
Some time tomorrow I'll test this and testmerge if its fine

**Comment by cerebral-314** [comment]
Keep in mind that change most likely will cause some more runtimes due to objects being deleted from explosions while they are being acted on by another subsystem.

**Comment by PowerfulBacon** [comment]
This still results in the station self destruct terminal freezing the server for a few seconds when detonated

**Comment by qwertyquerty** [comment]
Definitely worth a few seconds of freeze if that's all it is

**Comment by Isy232** [comment]
Agreed, a few seconds of freeze is fine in comparison to the massive lag the nuke can often generate until the server restarts.

**Comment by ivanmixo** [comment]
You can't really have a massive explosion and not expect it to lag at least a little

**Comment by Isy232** [comment]
Someone merge this or test it so it can be merged please, I really want this ingame.

**Comment by PowerfulBacon** [comment]
Testmerging onto sage, I'll feedback if things start breaking a lot

**Comment by PowerfulBacon** [comment]
Getting a lot of reports of lags and the server freezing up, explosions making the entire server freeze even for a fraction of a second is bad

**Comment by ike709** [comment]
This PR is massively increasing BYOND's internal tick usage for sending map updates. Should try increasing the MC tick reservation to ~70%.

**Comment by Isy232** [comment]
I hope this PR isn't dead, I seriously want this in the game.

**Comment by zeskorion** [comment]
marking as stale due to a lack of progress. if some is made, label will be removed

**Comment by Moccha-Bee** [comment]
is this pr dead 😿

**Pull request closed without merging**
