### PR TITLE
Turns movespeed down a tiny tad.

### PR DESCRIPTION
**Pull request by TsunamiAnt**
## About The Pull Request
People were talking about this on discord and it seems to be a liked change.
This turns down the movespeed of running and walking by one tick each. It's not that big a change but i like it nonetheless.

## Why It's Good For The Game

Slower movespeed goes hand in hand with less frantic action, which means more thinking, more reacting, and more time to do shit. It's the most direct "calm shit down" slider i know.

Also, less speed means less impact of skill on the game.

## Testing Photographs and Procedure

https://www.youtube.com/watch?v=23dxTXy3baI
## Changelog
:cl:
balance: people move slower now
/:cl:

### CODE REVIEW

**Comment by ColonelOrion** [comment]
If I want to set up a maints surgery, or a donut stand, or anything else that requires initial time investment but that will act as a hub for RP, I already need to walk to and fro from several locations to get the necessary bits and pieces. 

I don't mind this, as it fosters rp with other crew and also serves to let me spread the word that my project is underway.

This change would have an outsized impact on this playstyle. It wouldn't effect people that don't need to leave their department at all (medical bay, xenobio, botany, kitchen) but would absolutely torpedo anyone doing anyhting that's not explicitly planned in the station's shift start setup.

It would also be fucking ruinous for miners.
So hey, it's not all bad! :troll:

**Comment by ClownMoff** [comment]
Make clown shoes slow you less then, please I can't fanthom walking even slower to places I already take like 40% time to reach any place with the shoes on

**Comment by MarkusLarsson421** [comment]
> I already need to walk to and fro from several locations to get the necessary bits and pieces.

You're able to involve others to help setup stands if you think it takes time to walk.

I don't have much of any opinion on this change.

**Comment by Tsar-Salat** [comment]
@TsunamiAnt this needs to be drafted until smooth movement is merged, or show your testing evidence on the smooth movement branch.

The current movement without glide is not indicative of what the end product of this will be.

**Comment by TsunamiAnt** [comment]
you are right!

**Comment by PowerfulBacon** [comment]
This is a reduction of 5 tiles/second to 3.3 tiles/second, which is a 33% reduction in movement speed. Probably a bit more than I would call a 'tiny tad'. I would more describe it as a very significant reduction in movement speed

**Comment by Fronsis** [comment]
The smooth movement TM has made me realize how painfully slow some stuff are, certainly being more slow is not what we need in general terms and there's a shitton of items that make you either extremely fast or extremely slow personally i'm okay with what we currently have.

**Comment by Tsar-Salat** [comment]
@TsunamiAnt It would be sensible to undraft it now and redo testing evidence. Should be clear on the code end 🫰

**Comment by TsunamiAnt** [comment]
https://www.youtube.com/watch?v=23dxTXy3baI

Here's the new comparison for smooth movement. This time side by side too.

**Comment by ClownMoff** [comment]
that is so much slower 😭

**Comment by TsunamiAnt** [comment]
Honestly from watching it, I'd almost agree. But playing it you notice that it really aint that bad.

This might be a test first form opinions later type of thing, it feels totally different when you're actually in game.

**Comment by ClownMoff** [comment]
Bro I think I will notice walking much slower

**Comment by TsunamiAnt** [comment]
Aight

**Pull request closed without merging**
