### PR TITLE
Good riddance, swarmers!

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

kill swarmers

## Why It's Good For The Game

Yeah. They're just... cookie clicker, the antag. They can't even RP much, if at all, and most of the time any interaction ends up with the person getting cuff-teleported into the AI upload or somewhere equally awful.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

23-08-20-1692530563-dreamseeker

</details>

## Changelog
:cl:
del: Swarmers (both station and lavaland variants) can no longer spawn naturally.
/:cl:

### CODE REVIEW

**Comment by CydiaLamiales** [comment]
Question : why delete all of their code instead of simply stopping them from spawning?

**Comment by Absolucy** [comment]
@CydiaLamiales Why leave unused code in? I honestly doubt any reasonable admin is ever going to spawn them in.

**Comment by Tyranicranger4** [comment]
What about an unreasonable admin? I like being unreasonable sometimes.

**Comment by PowerfulBacon** [comment]
My comments were more about changing them into being less annoying and more of an actual threat rather than full removal

**Comment by Absolucy** [comment]
@PowerfulBacon Fair, but honestly, they should go the way of Hivemind: gone until someone actually bothers to rework them into being less awful.

Anyways, I'll un-remove the code and just get rid of the natural spawn events.

**Comment by Tsar-Salat** [comment]
bye felicia

**Comment by Rukofamicom** [comment]
I wanted to work more on inventory this weekend, but I suppose I need to make another counter-PR first to save us from a removal.

**Comment by Absolucy** [comment]
@Rukofamicom can you fix hivemind instead

**Comment by Rukofamicom** [comment]
No, because what the station needs right now in terms of antags is more midround diversity imo.

**Comment by Absolucy** [comment]
port paradox clones or something then

**Comment by CydiaLamiales** [comment]
> port paradox clones or something then
> antag whose sole purpose is to RR one guy

No

**Comment by Fronsis** [comment]
Literally improve don't remove moment lol, we're all aware of how lame the cookie simulator is, hence why we've been discussing in multiple threads different gameplay proposals to change a bit the swarmers as a midround, because it's a cool concept just with some lackluster gameplay, they don't need a removal, and they're still quite rare to spawn, i don't see why they need to be disabled in the mean time.

**Comment by Tsar-Salat** [comment]
> we're all aware of how lame the cookie simulator is, hence why we've been discussing in multiple threads different gameplay proposals to change a bit the swarmers as a midround



> i don't see why they need to be disabled in the mean time.

Terrible gamemodes should be disabled until reworked. You yourself admit how terrible it is. We have done the same thing to hivemind and revs, I don't see the difference here.

**Comment by llol111** [comment]
>They're just... cookie clicker, the antag
aaf

removals bad

**Comment by Rukofamicom** [comment]
This antagonist could certainly use some work, but it's not anywhere near bad enough for the game to warrant a complete removal.

**Comment by itsmeow** [comment]
If anything temporarily lower their weight rather than removing or disabling them.

**Comment by Absolucy** [comment]
What about lavaland swarmers, though? I don't really think I've seen anyone actually like them...

**Comment by Rukofamicom** [comment]
I'm not really a fan of lavaland swarmers and I don't think they improve the game at all, and worse they actively destroy the viability of ghost roles before they have the chance to take off in many rounds. 

I do find it strange that miners don't like them though - they're very easy to kill and provide a shitload of points for the effort taken to kill them given each one always drops a bluespace crystal.

**Comment by Tsar-Salat** [comment]
> I do find it strange that miners don't like them though - they're very easy to kill

It's more that they spread like lavaland's herpes, especially impacting you if you're a latejoiner miner. Once they reach masse singularity, its a bunch of little imps shooting lasers. One is easy, many not so much.

No other mob or role progressively makes your job more impossible as they spread.  That should be the job of antags, not AI.

**Comment by Absolucy** [comment]
> This antagonist could certainly use some work to make it appealing to a wider set of players

@Rukofamicom then we should disable them until someone actually does that (which will likely happen whenever Star Citizen is finished, tbh)

**Pull request closed without merging**
