### PR TITLE
New lizard emote.

### PR DESCRIPTION
**Pull request by Therealdoooc213**
## About The Pull Request

Adds tail swipe as an emote for lizards to use.

Sounds taken from TGMC under the CC-BY-NC-3.0 license. 
https://creativecommons.org/licenses/by-nc/3.0/
(if anyone knows which pr added it, i would be very grateful)

## Why It's Good For The Game

More emotes are great for flavor, personally i think this is a nice one.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

https://github.com/user-attachments/assets/401a9fc5-044a-49df-8d3b-8e8703c8299a

</details>

## Changelog
:cl:
add: New emote for lizards, "swipes"
soundadd: tail_swipe1.ogg & tail_swipe2.ogg
/:cl:

### CODE REVIEW

**Comment by Hardly3D** [comment]
Bee to TGMC pipeline

**Comment by Geatish** [comment]
Got scared for a sec that it was going to be the "weh" emote

**Review by EvilDragonfiend — CHANGES_REQUESTED** [review]
check `/datum/emote/living/carbon/human/wag/run_emote()`.
the current code allows them to swipe their tail regardless they have it really

**Comment by Therealdoooc213** [comment]
> check `/datum/emote/living/carbon/human/wag/run_emote()`. the current code allows them to swipe their tail regardless they have it really

https://github.com/user-attachments/assets/b4c3e425-694b-41ff-a34a-1c6201966e82

Adressed!

**Review by EvilDragonfiend — CHANGES_REQUESTED** [review]
You can run emote but it only makes the sound when you are liz.
check islizard condition.

**Comment by Therealdoooc213** [comment]
> This pull request has conflicts, please resolve those before we can evaluate the pull request.

Caused my own merge conflict... fucked up

**Review by EvilDragonfiend — APPROVED** [review]
I am not sure this being lizard exclusive, but well, someone would say fake lizards do not deserve this.

**Pull request merged**
