### PR TITLE
Removes chainsaw from barber

### PR DESCRIPTION
**Pull request by Rukofamicom**
## About The Pull Request

Removes the chainsaw from barber supplies, replacing it with a hatchet to fulfil the same function for ghetto surgery

## Why It's Good For The Game

Barbers cannot wrap their heads around the fact they shouldn't be valid-hunting. 
It serves *almost* no legitimate purpose for barbers that are not murder-hobos, when compared to the far less lethal hatchet.

## Testing Photographs and Procedure

<summary>Screenshots&Videos</summary>

image

## Changelog
:cl:
del: Replaces the barber's chainsaw with a hatchet because the baboons won't stop valid-hunting with the chainsaw. 
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
please fix the cl

**Comment by Rukofamicom** [comment]
I don't see an issue with the cl, it is quite accurate

**Comment by EvilDragonfiend** [comment]
oh I might have misread the old one

**Comment by JixS4v** [comment]
Yeah I don't understand why barbers had this one in the first place, makes a lot of sense to remove it

**Comment by Nosnek199** [comment]
I think the only reason barbers had the chainsaw was for being a ghetto surgeon. will hatchet work for circular saw stuff?

**Comment by EvilDragonfiend** [comment]
> I think the only reason barbers had the chainsaw was for being a ghetto surgeon. will hatchet work for circular saw stuff?

They don't need a circular saw too. I suggested a hatchet in Discord, and it will work as an alternative if they want **ghetto**.

**Comment by Rukofamicom** [comment]
Yes hatchet will work and is right on par with chainsaw for flavor

**Review by PestoVerde322 — APPROVED** [review]

**Pull request merged**
