### PR TITLE
Removes devils gamemode from rotation on sage

### PR DESCRIPTION
**Pull request by super12pl**
## About The Pull Request
Removes devils gamemode from MRP because its terrible.

## Why It's Good For The Game
It's better to have few good gamemodes than a lot of terrible ones.

## Changelog
:cl:
config: Removes devils from rotation on MRP
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Good, it's a shit mode

**Comment by pixelman77** [comment]
It should be removed from LRP, not MRP, at least on MRP some people RP it properly

**Comment by super12pl** [comment]
> It should be removed from LRP, not MRP, at least on MRP some people RP it properly

It's not about rping it properly, it's just terrible gamemode. I'm removing it only from MRP because i don't play on LRP and i don't know how devil rounds are being held there.

**Comment by BettonnCZ** [comment]
add something else tho, diversity is good

**Comment by TeomanTheGreat** [comment]
> add something else tho, diversity is good 

Add hivemind back

**Comment by super12pl** [comment]
> add something else tho, diversity is good

We already got Insursion team and clock cult will be soon test merged.

**Comment by ike709** [comment]
Vote is exactly tied. But we're introducing two new modes so I say why not give it a whirl.

**Comment by BettonnCZ** [comment]
so clock cult bacc?

**Review by Crossedfall — APPROVED** [review]
Config changes applied.

**Pull request merged**
