### PR TITLE
[PORT] ports the shark plushie

### PR DESCRIPTION
**Pull request by spockye**
## About The Pull Request
This PR ports the adorable shark plushie from TG, thats about it!
its a pretty nice looking plushie, and i just dont see a reason not to add it. 
Original PR: https://github.com/tgstation/tgstation/pull/76206

image

Updated sprite from PigeonVerde!

## Why It's Good For The Game
more cute plushies!

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl: Spockye, TheVekter, INFRARED_BARON, PigeonVerde
add: Ports the shark plushie
/:cl:

### CODE REVIEW

**Comment by Howluinb** [comment]
This is a vital, critical PR that should be speedmerged as fast as possible. Bee can't continue without this

**Review by PowerfulBacon — APPROVED** [review]
The sprite doesn't really fit the style of the other plushies and is a bit big but seems fine regardless.

**Comment by spockye** [comment]
waiting on new sprites from Pigeon

**Comment by zeskorion** [comment]
haha sharkie

**Review by PestoVerde322 — APPROVED** [review]

**Pull request merged**
