### PR TITLE
Changes volume pumps to normal pumps in meta's SM

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Title

## Why It's Good For The Game

You are supposed to upgrade them yourself. 

## Changelog
:cl:
tweak: Volume pumps has been replaced by normal pumps in meta's SM.
/:cl:

### CODE REVIEW

**Comment by bloons3** [comment]
The station is supposed to start unoptimized, good PR

**Comment by ItsTisme** [comment]
It used to be like this, we did this because people simply didn't know you had to do it. Bad change IMO this hurts only noobs who don't know any better yet

**Comment by Archanial** [comment]
> It used to be like this, we did this because people simply didn't know you had to do it. Bad change IMO this hurts only noobs who don't know any better yet

? 
SM can run on normal pumps just fine. How does optimizing station roundstart hurt new players? 
Also it was the only station to get that treatment and it was truly a terrible idea.

**Comment by ItsTisme** [comment]
> 
> 
> > It used to be like this, we did this because people simply didn't know you had to do it. Bad change IMO this hurts only noobs who don't know any better yet
> 
> ?
> SM can run on normal pumps just fine. How does optimizing station roundstart hurt new players?
> Also it was the only station to get that treatment and it was truly a terrible idea.

its *barely* able to work with just gas pumps with fastmos and all and usualy results in a delem. You can read the orginal PR but thats the point of it. Its not like its optmized anyhow you use straight pipes instead of any kind of pump so

**Comment by ItsTisme** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/2054 the orginal PR, incase you wana read over it. Should give some insight

**Comment by Sinestia** [comment]
Every Map Must Be The Same

the meta isn't even to use volume pumps, but if you're upgrading chances are you're doing more than replacing every normal pump with a volume pump.

**Review by utilbird — APPROVED** [review]

**Pull request merged**
