### PR TITLE
Temporarily nuke the ore silo from orbit

### PR DESCRIPTION
**Pull request by ike709**
Don't worry about it.

### CODE REVIEW

**Comment by Dejaku51** [comment]
funny

**Comment by Chirynnn** [comment]
This change will drastically and positively impact Beestation Sage for the many years to come

**Comment by Tsar-Salat** [comment]
who broke it

**Comment by DingleFlop** [comment]
What if it just WASN'T temporary!!!

**Comment by Crossedfall** [comment]
Superseded by https://github.com/BeeStation/BeeStation-Hornet/pull/8638

**Pull request closed without merging**
