### PR TITLE
The Great Radio Rework: NTNET Part 1 of many. - second try

### PR DESCRIPTION
**Pull request by Dejaku51**
## About The Pull Request
Second try porting https://github.com/tgstation/tgstation/pull/54462
First try here: https://github.com/BeeStation/BeeStation-Hornet/pull/5352 (separate PR because i force-pushed and im too lazy to fix github bullshit)

## Why It's Good For The Game
Brings NTNET up to date and makes it easier to work with

## Testing Photographs and Procedure

Only basic testing as its hard to check everything so TM is required
Ntnet works:
image
When trying to use the door remote with Remote System Control disabled:
image

## Changelog
:cl: Dejaku51, WarlockD
add: Turning off ntnet remote system control makes it so you can't use door remotes
code: updated ntnet code
/:cl:

### CODE REVIEW

**Comment by Dejaku51** [comment]
after that PR is merged im working on circuits

**Review by PowerfulBacon — DISMISSED** [review]
Include authors names and your own name after the :cl: tag (should also probably test that radios and door controllers work)

**Comment by Dejaku51** [comment]
> Include authors names and your own name after the 🆑 tag

done

**Comment by Dejaku51** [comment]
> (should also probably test that radios and door controllers work)

wdym by radios and door controllers

**Comment by Archanial** [comment]
Did you resolve runtimes that came with testmerge or is it just copy of the pr?

**Comment by Dejaku51** [comment]
> Did you resolve runtimes that came with testmerge or is it just copy of the pr?

resolved

**Comment by FortSumter** [comment]
I'm not a coder, but I'm interested in this. Is the end goal to just remove the spaghetti code for how certain items function, or will this completely change some aspect of the game for the players?

NTNET makes me think of the Ipads some roles start with like the HoP and CE or the error message I get when the related consoles bug out. Will this PR make more items function like the Ipads?

**Comment by Dejaku51** [comment]
> I'm not a coder, but I'm interested in this. Is the end goal to just remove the spaghetti code for how certain items function, or will this completely change some aspect of the game for the players?
> 
> NTNET makes me think of the Ipads some roles start with like the HoP and CE or the error message I get when the related consoles bug out. Will this PR make more items function like the Ipads?

this PR just makes code better, only player facing feature is the door remote change
Yes, modular tablets/laptops/consoles use ntnet.
I'm planning on expanding use of modular devices and NTnet in future PRs

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
