### PR TITLE
Readds Viral aggressive metabolism

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request

This re-adds a virus symptom that was removed awhile ago (improve dont remove lmao, https://github.com/tgstation/tgstation/pull/36349 ), with nerfed stats. The symptom makes a virus start at full power, but get cured by itself quite fast (If i am reading this right, it should take about 10 ticks to cure per point in stage speed or resistance, whichever is higher. this is doubled if stealth is over four.

## Why It's Good For The Game

This symptom was around before the great virology nerf. I don't know much about the history of that time.

The 1 transmittable stat of this disease allowed it to spread deadly plagues at their most lethal state, which, considering the power of high- tier symptoms, was very easy and deadly, rather than working as intended, which, i assume, was to make a powerful, lethal disease designed to affect only a single target. The stats have been changed to reflect both this and its function, and, due to the deadliest symptoms being moved to level nine, this is no longer as big an issue, [s]and gives viro a way to safely validhunt without killing everyone[/s]

this should be my last addition to viro for awhile, hopefully, until i spot a new shiny that isn't op ass oldviro healing symptoms
## Changelog
:cl:
add: Readds Viral aggressive metabolism
/:cl:

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
He's buffing his own department reeeeeeeeeeeeee.

Nah, this looks interesting.

**Comment by enthethan** [comment]
>saltcoded out by tg
conceptualize my amazement

**Review by qwertyquerty — APPROVED** [review]

**Comment by ATH1909** [comment]
Heyo, guy who used to do some coding for some of the semi-recent /tg/station virology updates here.

> The 1 transmittable stat of this disease allowed it to spread deadly plagues at their most lethal state

You still use the transmission stat for your killplagues? Just dump it and add sneezing to your virus. Dump stage speed too, since this symptom brings you to stage 5 right away anyway (you could alternatively dump resistance to take advantage of the stage speed INCREASE that this symptom gives your virus). This symptom was removed (instead of improved) for a REASON, and just lowering its base transmission stat isn't going to fix all of its problems.

**Comment by ATH1909** [comment]
... Mm, after going through some theorycrafting, this symptom _might_ not be as broken as I thought. This is still a bad idea, though, IMO.

This is pretty much the best killvirus I could come up with that uses this symptom in around 30 minutes of theorycrafting:

VAM virus stealthy:
VAM
sneezing
ARDS
vitiligo
eternal youth
necrotic metabolism

stealth: 4
resistance: 1
stage speed: 10
transmission: -4
cure: salt
stealthy: yes
spread: blood, sneezing

This stealthy virus (which does not appear on medHUDs or health analyzers) will give you a message 14-30 seconds after you catch it from an infected person sneezing near you. 20 seconds after you receive this message, you will be chainstunned (until the virus is cured) and also knocked out (you should get a few moments where you're stunned but not unconscious occasionally, though). The virus will then slowly kill you by suffocating you and dealing oxyloss damage to you. After it kills you, the virus will then deal brain damage to your corpse's brain and continue to occasionally spread the virus to anyone nearby. After this virus has been in your system for 200 ticks (400 seconds), it will begin to cure itself.

**Comment by ATH1909** [comment]
As for meme viruses:
near-instant meme virus:
VAM
sneezing
inorganic biology
VEA
alopecia

stealth: -3
resistance: 3
stage speed: 9
transmission: 11
stealthy: no
cure: salt
transmission: airborne(!) and below (including contact), sneezing

You can inject yourself with this virus, then run around and hug people for 3 minutes. Everyone who you infect with this virus will become black within 14 seconds after being infected and will become bald (and beardless) within 90 or so seconds after being infected.

**Comment by ATH1909** [comment]
(near-)instant romerol tumor:
VAM
sneezing
autophago
eternal youth
fever
vitiligo

s (need 2): 2
r: 4
ss (need 12): 14
t: -2

(near-)instant romerol tumor (with necrotic metabolism):
VAM
sneezing
autophago
eternal youth
fever
necrotic metabolism

s (need 2): 2
r: 2
ss (need 12): 12
t: -3

These two viruses will only work (properly) after your autophagocytosis necrosis zombie fix goes through. These viruses will give their victims a romerol tumor almost immediately after infecting them (via sneezes) and also will kill their victims quite quickly. The latter virus uses the VAM symptom's self-purging aspect to its benefit, allowing the corpses of its victims to spread the virus for a little longer (with the sneezing+necrotic metabolism wombo combo) while still (eventually) allowing the zombies from the virus to not keep redying to the virus that turned them in the first place.

I just realized that I've been forgetting to mark which symptoms have been neutered in these viruses, but I'm too lazy to go back and edit them all. Eh, just neuter the stuff that looks like it should be neutered and you should be fine.

**Comment by zeskorion** [comment]
> ... Mm, after going through some theorycrafting, this symptom _might_ not be as broken as I thought. This is still a bad idea, though, IMO.
> 
> This is pretty much the best killvirus I could come up with that uses this symptom in around 30 minutes of theorycrafting:
> 
> VAM virus stealthy:
> VAM
> sneezing
> ARDS
> vitiligo
> eternal youth
> necrotic metabolism
> 
> stealth: 4
> resistance: 1
> stage speed: 10
> transmission: -4
> cure: salt
> stealthy: yes
> spread: blood, sneezing
> 
> This stealthy virus (which does not appear on medHUDs or health analyzers) will give you a message 14-30 seconds after you catch it from an infected person sneezing near you. 20 seconds after you receive this message, you will be chainstunned (until the virus is cured) and also knocked out (you should get a few moments where you're stunned but not unconscious occasionally, though). The virus will then slowly kill you by suffocating you and dealing oxyloss damage to you. After it kills you, the virus will then deal brain damage to your corpse's brain and continue to occasionally spread the virus to anyone nearby. After this virus has been in your system for 200 ticks (400 seconds), it will begin to cure itself.


> Heyo, guy who used to do some coding for some of the semi-recent /tg/station virology updates here.
> 
> > The 1 transmittable stat of this disease allowed it to spread deadly plagues at their most lethal state
> 
> You still use the transmission stat for your killplagues? Just dump it and add sneezing to your virus. Dump stage speed too, since this symptom brings you to stage 5 right away anyway (you could alternatively dump resistance to take advantage of the stage speed INCREASE that this symptom gives your virus). This symptom was removed (instead of improved) for a REASON, and just lowering its base transmission stat isn't going to fix all of its problems.

Sneezing doesnt spread shit on beecode. Thats the first thing i ever coded, cuz sneezing was bullshit

We also dont use recent /tg/ viro buffs like how coughing also spreads, or their lower transmission thresholds

**Comment by ATH1909** [comment]
Ah, I missed that sneezing change because you implemented it in a really weird way.

I already knew that you don't use my coughing buff or my updated transmission vector system (I understand why you didn't port the former, but if you've nerfed sneezing, why didn't you port the latter, if I may ask?); the instant meme virus that I outlined above already accounted for that.

Knowing that sneezing doesn't spread viruses on beecode without a transmission stat of 9 definitely makes me feel much less uneasy about this symptom, and it's _probably_ okay to add to the game? I'm just not quite sure why you'd spend all that time creating a custom deathmix virus with this symptom to apply to people directly instead of just making lexorin with a chem dispenser or something.

**Comment by Sparrowbird611** [comment]
The only thing I can think of is making a zombie virus quickly. Otherwise, it's just the virologist's version of chemical weaponry.

**Comment by zeskorion** [comment]
> Ah, I missed that sneezing change because you implemented it in a really weird way.
> 
> I already knew that you don't use my coughing buff or my updated transmission vector system (I understand why you didn't port the former, but if you've nerfed sneezing, why didn't you port the latter, if I may ask?); the instant meme virus that I outlined above already accounted for that.
> 
> Knowing that sneezing doesn't spread viruses on beecode without a transmission stat of 9 definitely makes me feel much less uneasy about this symptom, and it's _probably_ okay to add to the game? I'm just not quite sure why you'd spend all that time creating a custom deathmix virus with this symptom to apply to people directly instead of just making lexorin with a chem dispenser or something.

because viro "deathchems" are easier to apply and produce, and harder to deal with for the recipient

your updated transmission vector stuff essentially makes it *really fucking easy* to spread a virus, so i don't like it. i like it being quite difficult to make a virus spread while airborne. it makes it so a good plague has to be well made if it wants to meet thresholds,  and so people wont hate viro cuz newbies wont release dumb shit every round. sneezing already has the highest transmission stat in the game at a 4, and doesnt need further representation of the contagion it spreads. it's still a _really fucking good_ symptom literally required on every plague

additionally, using a symptom like pierrot's with this to temporarily render someone clumsy so you can avoid a lynching? priceless!

**Comment by imsxz** [comment]
hey im the guy that originally removed this. i used to play viro a lot and abused the hell out of this symptom. i can assure you the stats were NOT the issue. the issue  was the idea of the symptom in general. "improve dont remove" is applied in a very awful way in the ss13 community because it only works on ideas that arent fundamentally shitty. this symptom is one of those fundamentally shitty ideas. it is NOT fun to play with. it is not interesting. it makes death viruses that are already unfun to play against even MORE unfun.

**Comment by zeskorion** [comment]
> hey im the guy that originally removed this. i used to play viro a lot and abused the hell out of this symptom. i can assure you the stats were NOT the issue. the issue was the idea of the symptom in general. "improve dont remove" is applied in a very awful way in the ss13 community because it only works on ideas that arent fundamentally shitty. this symptom is one of those fundamentally shitty ideas. it is NOT fun to play with. it is not interesting. it makes death viruses that are already unfun to play against even MORE unfun.

The thing is, i agree with you in that this wouldn't work with how /tg/ viro currently is- transmitting a virus is easy.  Here, you can't just make a spreading death virus with it- it's essentially single-target exclusive. Spending 30 minutes on your deathmix, with only a currently 60% chance of having an effective active symptom for it every round, is satisfactory. 

And i agree with you on that "improve dont remove" bit. But i dont think you should ever straight remove small shit like this from the code either, when you can just set level to -1

**Pull request merged**
