### PR TITLE
Bulk fixes/code improvements/etc

### PR DESCRIPTION
**Pull request by ike709**
Fixes a couple bugs and also ports a _ton_ of fixes/improvements from TG (29 PRs to be exact).

~~Full list of ports here: https://github.com/BeeStation/BeeStation-Hornet/projects/2#column-9445115~~ EDIT: See my last comment on this PR for list of PRs ported.

**This PR is completely untested, I am very sleepy. Don't merge it.**

## Changelog
:cl: ike709 and a bunch of TG coders
fix: MONSTERMOS IS NO LONGER JANKY, IT SHOULD WORK PERFECTLY NOW
refactor: Moved the pixel scaling and zoom methods from the menu bar to the Game Preferences window. You'll need to reset them.
fix: Yellow slime power cells will charge SMES units.
fix: Fixed a monstermos runtime.
fix: Fixed a ton of other runtimes.
add: Simple mobs will now receive an alert about being in too hot/cold environment.
add: Simple mobs will now receive an alert about choking to death.
fix: A bunch of visual fixes related to multi-z.
tweak: Multi-Z power relays can repaired but must be manually updated with a multi-tool when reinstalling/moving around.
fix: You can now place cables on catwalks that go over openspace.
fix: AI can now look up/down zlevels on multi-z.
add: Added railings for multi-z.
fix: Tank Dispensers, Ore Boxes and Coin Presses are no longer usable by ghosts
refactor: Refactored client.view into a datum, changed some zoom values to work properly
add: Fully adds widescreen support to zooming
fix: Pixel size will now automatically update on zoom, so you won't end up with ui buttons you can't see.
tweak: Most input windows now have sorted lists of choices.
fix: walking downstair won't show the falling visible message anymore.
fix: Mechs can now go down (stairs)
fix: Mechs can't push (non-anchored) objects and mobs with move resistance greater than "very strong" anymore.
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Ugh, line endings messed up the DME

**Comment by PowerfulBacon** [comment]
> This PR is completely untested, I am very tired. Don't merge it.

oh god

**Comment by ike709** [comment]
All line endings should be fixed now.

**Review by Crossedfall — APPROVED** [review]
Test merged for a couple of rounds on Sage. No major issues as of the latest test- going ahead with the merge.

**Comment by ike709** [comment]
The list of PRs has been moved to the Done section of the project board, however I took the liberty of leaving cards to mark where this PR's contents start and stop: https://github.com/BeeStation/BeeStation-Hornet/projects/2#card-39466872

**Pull request merged**
