### PR TITLE
Adds melee aiming (From a Beestation PR)

### PR DESCRIPTION
**Pull request by ghost**
# About The Pull Request
"Adds melee aiming. meant to go with #2430

while on Walk and Harm intent, your melee attacks will hit mobs that are outside of softcrit if they are in the targeted tile, regardless of if you click their sprite or not"
(From PR https://github.com/BeeStation/BeeStation-Hornet/pull/2444/files)
## Why It's Good For The Game
"speedcombat is still cancer, this accompanies my earlier goal of slowing it down a bit"

## Changelog
🆑
add: you can now hit mobs in melee easier if you are on harm intent and walking (you only need to click the tile, not the sprite itself)
/🆑

### CODE REVIEW

**Comment by ghost** [comment]
Wrong fucking repo im so retarded

**Comment by zeskorion** [comment]
who are you trying to port this to? not here, I hope

kehehe

**Comment by ghost** [comment]
@zeskorion i'm just doing a dumb beestation fork for my friend and i thought your pr was cool

**Comment by ghost** [comment]
sorry if it seems weird

**Pull request closed without merging**
