### PR TITLE
Removes Gang and Devil from Sage Rotation

### PR DESCRIPTION
**Pull request by WhyIsCaeciliusTaken**
## About The Pull Request

Removes both Gang and Devil from the gamemode rotation on the Sage server, making Devil an admin only gamemode now.

## Why It's Good For The Game

Both gamemodes sucked on Sage, and devil is bad in general.

Gangs is just chaos. People getting shot all over the show and no encouragement to do anything interesting other than "shoot everything that moves".

Devil is bugged and bad. The Codex, centrepiece of the gamemode, is bugged and doesn't work, as are employment contracts, swinging the mode massively in the favour of the devils, and the powers they give out are used invariably to just greytide everywhere. The voluntary nature of the contracts also makes it frustrating for the devils. It's no fun for anyone.
## Changelog
:cl:
del: Removed Devil from rotation
del: Removed Gang from Sage rotation
/:cl:

### CODE REVIEW

**Comment by hackerjsimon** [comment]
improve don't remove we need these game modes without them its basically revs and cult tator and lings() so u might as well do balancing prior.

**Comment by WhyIsCaeciliusTaken** [comment]
Gang simply doesn't fit Sage. If we changed it so that it did, it wouldn't fit Golden.

Devil is fundamentally broken as a concept as it relies on people willingly helping the antagonists.

**Comment by Crossedfall** [comment]
> Devil is fundamentally broken as a concept as it relies on people willingly helping the antagonists.

It relies on people role-playing. Or, in other words, willingly giving up meta-knowledge for the sake of roleplay. I think it's reasonable to say that IC, people would fall for devils and willingly go along with their ploys. 

Not saying that Devil is perfect, but I also wouldn't say that it's broken as a concept.

**Comment by Sparrowbird611** [comment]
You can potentially improve both modes, however, I don't see any one stepping up to do that right now. It's easier to remove gangs on MRP, and rework it at a later date, if we even want it back.

I agree with devil being a flawed concept. The issue is that it's an antagonist that more or less revolves around you begging people for souls, instead of antagonizing the station. The mode leads to self antagging that causes more harm than the devil himself (you could argue this is the devil working, but breaking rules on MRP to antagonize the ship sure seems flawed). I don't even think the mode would work on HRP, because currently, the devil has no way to force people to sell their souls, so it's basically just hoping these players would do so.

**Comment by qwertyquerty** [comment]
I'm going to run an in game vote on sage itself, since this is a rather significant change.

**Comment by PowerfulBacon** [comment]
I don't agree with removing the gangs, but Devil definitely needs to go. People can say 'improve dont remove' all they want but no one wants to improve it, and its a terrible gamemode. I don't like playing this mode, since it is painful walking around while getting validhunted for being a demon while nobody wants to sign the contracts that give some shitty powers. Then on top of that half the people who get powers either self antag or get validhunted for no reason making it awful to admin on.

**Comment by qwertyquerty** [comment]
Screenshot_20200216-174158

50 to disable gang
49 to keep gang

33 to disable devil
66 to keep devil


Make a new atomized PR to disable gang. @WhyIsCaeciliusTaken

**Pull request closed without merging**
