### PR TITLE
Creates an access request program

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
This is going to take quite a bit of time.
I'm opening a draft to get feedback and stuff, because i am very not familiar with tgui.
This will be a learning experience though, right?

Anyways,

This will be a program for requesting and getting access for your id. You can request anyof the accesses a standard ID machine can grant, and that request is sent to the head of that specific region, the HoP, and captain. Command accesses are only sent to captain. You can request a certain amount of time to have that access. 

- [ ] Learn tgui
- [ ] Request submission system
- [ ] Adding access
- [ ] Notifying the relevant heads
- [ ] UI

## Why It's Good For The Game
Moves some of the "just need access to an area for a quick thing" requests away from the ai and more to the HoP, Cap, and heads, since they should be more in control of their own departments

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
add: access request program
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Is this temporary access or permanent access? 

Since the main point of SS13 is about how players interact to work towards their goal, with these interactions and actions having consequences that build up leading to disasters unfolding, how does this stick to this theme? If the access is permanent this this basically kills any need for the HOP going against this goal, since interactions have been removed in favour of convenience.

**Comment by itsmeow** [comment]
I really like the scale and ambition of this PR but I'm not sure allowing the HoP to remotely give out access etc is a good idea.

Maybe you could make some type of requests console replacement for the tablets instead?

**Comment by etherware-novice** [comment]
> Is this temporary access or permanent access?
> 
> Since the main point of SS13 is about how players interact to work towards their goal, with these interactions and actions having consequences that build up leading to disasters unfolding, how does this stick to this theme? If the access is permanent this this basically kills any need for the HOP going against this goal, since interactions have been removed in favour of convenience.

temporary

**Comment by etherware-novice** [comment]
> I really like the scale and ambition of this PR but I'm not sure allowing heads to remotely give out access in their dept etc is a good idea.
> 
> Maybe you could make some type of requests console replacement for the tablets instead?

you mean the NTIRN from tg?

**Comment by itsmeow** [comment]
We have NTIRN already. I mean a replacement for the DEPARTMENT request consoles, the ones that no one uses.

**Comment by etherware-novice** [comment]
i mean technically heads of staff use it

**Comment by etherware-novice** [comment]
well im trying to make another pda pr like you-

**Pull request closed without merging**
