### PR TITLE
[PORT] Shooting a BSA beam at the SM will make it delaminate

### PR DESCRIPTION
**Pull request by Kerbin-Fiber**
## About The Pull Request
Adds a BSA beam blocker element that blocks bluespace artillery beams. SM and singulo have it.
The SM will also call explode() when shot, so maybe don't do that.
Keep in mind these are talking about the beam the artillery launches that goes to the edge of the map that destroys everything in its path. After it hits the edge, it's supposed to explode on what you aimed it at (a gps, normally). It didn't do that before, now it does. That explosion is a regular old explosion, nothing special happens if you blow stuff up with that.

See: tgstation/tgstation#47748

## Why It's Good For The Game
ike pinned it in discord.

## Changelog
:cl: MrPerson
add: If you shoot the supermatter crystal with bluespace artillery, you're gonna have a bad time.
fix: Bluespace artillery will blow its targets up properly instead of doing nothing.
/:cl:

### CODE REVIEW

**Comment by Kerbin-Fiber** [comment]
Still need to test it

**Comment by qwertyquerty** [comment]
Notify us when tested

**Comment by ike709** [comment]
Conflicts

**Comment by ike709** [comment]
Stale.

**Pull request closed without merging**
