### PR TITLE
Ports construction bags

### PR DESCRIPTION
**Pull request by Cenrus**
https://github.com/tgstation/tgstation/pull/44875/

Adds construction bags for engineers (starting in the engineering personal closets).
They can hold stock parts, other common machine components, circuits, misc electronics and cable coils.
## Why It's Good For The Game

Lets engineers do construction without having to dedicate half their inventory on components for a single machine. Made half-obsolete later by RPEDs, but being able to store multiple circuitboards is still useful.
I really want to encourage machine construction from engineering, since they even have access to advanced machinery like quantum pads but i never see them make use of it.
## Changelog

:cl: XDTM
add: Engineering closets now start with a construction bag, which can hold machine components, circuits, electronics, and cable coils.
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
Bags already do this, just carry around a duffel bag full of stuff. I don't see why this is needed at all

**Comment by SomeAngryMiner** [comment]
i like this, since having the ability to pocket a handful of APC circuits, stock parts and firelock electronics as engineer is really useful.

**Comment by SomeAngryMiner** [comment]
without taking backpack space, that is. Think this thing can hold up to 50 of those in a single pocket, mind you.

**Comment by SomeAngryMiner** [comment]
Why'd you close this?

**Comment by Cenrus** [comment]
would like to port this first https://github.com/tgstation/tgstation/pull/44109/files

**Pull request closed without merging**
