### PR TITLE
PubbyStation Atmosia changes [First PR]

### PR DESCRIPTION
**Pull request by DingleFlop**
## About The Pull Request

Made some changes to PubbyStation atmosia for cleanliness and such.

Allow access to Pubby East Atmos tanks.
Engine pipe no longer uses pipe layers.
Filter loop no longer uses pipe layers.
Moved Turbine room SMES.

## Why It's Good For The Game

Pubby's atmosia was frustrating to work with due to layered pipes being strewn about. Pipe layers should be reserved for mid-round changes by techs, to prevent spaghetti piping and allow for more complex setups without having to undo the issues caused by roundstart pipes just being a general nuisance.

## Testing Photographs and Procedure

Booted up a test server, checked to make sure SMES power was flowing properly in Turbine room
checked the engine pipe is receiving gas properly
checked Distro is running properly
checked the mix loop is moving gases throughout its entirety, properly.

<details>

<summary>Screenshots&Videos</summary>

DISTRO

image

TURBINE

image

image

ENGINE PIPE

image

image

MOVED WALLS

image

image

</details>

## Changelog
:cl:
tweak: Toxins Storage and Turbine area walls moved to allow tank access
tweak: Atmosia main no longer needlessly uses layered pipes
fix: Atmosia burn chamber no longer lacks a vent pump, and can be entered again
/:cl:

### CODE REVIEW

**Comment by SergeiKoralev** [comment]
image
The literal reason why I remapped the entire pubby atmos was because of wall pipes. I **strongly advise** that this not me merged while it utilizes bad practices, such as running pipes under walls.

Edit: Additionally, the white striping is to indicate sub-floor pipes. If you remove the pipes you should remove that as well.

**Comment by SergeiKoralev** [comment]
image
Additional location where markings were not updated to reflect pipenet changes.

**Comment by DingleFlop** [comment]
Thankyou, I really appreciate the input! I will try to work it through again to avoid those issues but keep the increased simplicity of the area. I think I have just the spot for that vent pipe!

Do you mind the under-wall pipe to the engine airlock area? I could run that through the airlocks and it wouldn't change the goal of this PR.

I personally don't mind under-wall pipes so long as it is a single wall that it's run through, accessible on both sides, but I see now that sentiment is not common. I will see what I can do about this, and the decals tomorrow!

**Comment by DingleFlop** [comment]
> Thankyou, I really appreciate the input! I will try to work it through again to avoid those issues but keep the increased simplicity of the area. I think I have just the spot for that vent pipe!
> 
> Do you mind the under-wall pipe to the engine airlock area? I could run that through the airlocks and it wouldn't change the goal of this PR.
> 
> I personally don't mind under-wall pipes so long as it is a single wall that it's run through, accessible on both sides, but I see now that sentiment is not common. I will see what I can do about this, and the decals tomorrow!

In fact, I see now that moving the distro pipe outside was a misstep on my part. The way I see atmos being used in general, that one specifically was never in the way. Thankyou for pointing that out ^^

**Comment by SergeiKoralev** [comment]
Yup, when I reworked the pipes before I was as careful as possible to keep those pipes out of the way, in other words right next to the windows, and perpendicular to the atmos tank inlet and outlet. As well I made the decision to not run a scrubber out from the turbine airlock, the purpose being to keep layer 3 free (as it's the safest non-2 layer to work on) to provide a good amount of flexibility.

**Comment by DingleFlop** [comment]
Updated some piping based on suggestions!

MIX CHAMBER

image

ENGINE PIPE

image


Added a fix, the burn chamber lacked a vent pump, and as such could NOT have its doors cycled.

image

Tested and working properly with the door controller!

**Comment by DingleFlop** [comment]
image

Scooted the Distro for the turbine one tile east, so it isn't under the filter!

**Review by Archanial — APPROVED** [review]

**Pull request merged**
