### PR TITLE
Updates gitattributes to normalize line endings

### PR DESCRIPTION
**Pull request by Crossedfall**
## About The Pull Request

This tells git to set `dm`, `sh`, and `dme` files' line endings to LF automatically while automatically normalizing all other files based on the preexisting endings.

This should be merged after #2319 

## Changelog
:cl:
code: Git will automatically try to normalize line endings. LF is now the default line ending for dm, sh, and dme files.
/:cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
Passes the sniff test of compiling and running. I'm open to talking about setting explicit line endings for other file extensions. Forcing it for everything though would be needlessly obtuse. (e.g. `txt` files don't need to be explicitly set to use LF)

**Comment by Crossedfall** [comment]
Actually, I've decided to split this into two PRs. This one will be for updating the gitattributes file, the next one will be for updating existing line endings.

**Comment by francinum** [comment]
Hey. Thanks for this.

Not really.

**Comment by Crossedfall** [comment]
> 
> 
> Hey. Thanks for this.
> 
> Not really.
> 
> 

❤️ ❤️ ❤️

**Pull request merged**
