### PR TITLE
Removes Any Reference to Mech Pilot Suits

### PR DESCRIPTION
**Pull request by DatBoiTim**
## About The Pull Request
Removes in code references to Mech Pilot Suits. Their sprites don't exist, or at least, aren't in the correct DMI.

File history for them also isn't helping with finding them.

I am not making sprites for these.

## Why It's Good For The Game
Missing Sprite items should not be regularly available.

## Testing Photographs and Procedure

Searched for all references to the suits, highlight+backspace

## Changelog
:cl: DatBoiTim
del: Removed Mech Pilot Suits and Associated Crate
/:cl:

### CODE REVIEW

**Comment by DatBoiTim** [comment]
Apparently the sprites for these MFs were butt ugly, so good riddance!

**Comment by Fikou** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/5820
this pr adds new sprites for them

**Comment by Wilchenx** [comment]
since #5820 got merged this can be closed

**Comment by DatBoiTim** [comment]
> since #5820 got merged this can be closed

Ew Anime references

**Pull request closed without merging**
