### PR TITLE
Morphs now husk victims on digestion instead of dusting

### PR DESCRIPTION
**Pull request by AgentCitrus**
## About The Pull Request

Previously, upon digestion, morphs would dust corpses and spit out their items. Now, morphs husk their victims and expel their corpse - stripping them of all nutritional value and leaving behind the waste, like changeling absorption. Morphs can't digest husks or simplemobs they've already digested as well, to prevent infinite healing.

## Why It's Good For The Game

An antag like the morph being able to delete a target forever with little effort (digesting after critting/downing the target) is odd. The corpse can still be held by the morph until the morph dies or spits it out, anyway.

## Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

image
_Message delivered upon attempting to digest a husked corpse_

</details>

## Changelog
:cl:
balance: Morphs now husk digested corpses instead of deleting them outright
/:cl:

### CODE REVIEW

**Review by itsmeow — APPROVED** [review]
Very nice. This does do damage to the body typical of husking? Like 200-400 brute/burn?

**Comment by LemonLimeSoda** [comment]
> Very nice. This does do damage to the body typical of husking? Like 200-400 brute/burn?

It does not, similar changeling absorption. Should it?

**Comment by Absolucy** [comment]
Yeah, I'd personally deal like 400 burn, and also apply acid to all their clothes (because that'd make sense for being digested)

**Comment by itsmeow** [comment]
No I think that's fine, just the damage the morph did

**Comment by itsmeow** [comment]
> Yeah, I'd personally deal like 400 burn, and also apply acid to all their clothes (because that'd make sense for being digested)

Absolutely not, that is horrible and their clothes already get stripped anyway

**Comment by LemonLimeSoda** [comment]
> No I think that's fine, just the damage the morph did

At your request digestion now deals an additional 50 burn damage

**Review by itsmeow — APPROVED** [review]

**Review by Penwin0 — APPROVED** [review]

**Pull request merged**
