### PR TITLE
Tweaks cargo values and contents

### PR DESCRIPTION
**Pull request by RemervKeberb**
## About The Pull Request

Does what it says on the tin. Used to avoid infinite money in cargo.

## Why It's Good For The Game

Infinite money bad

## Changelog
🆑
Fix: Tweaks cargo pack prices and some contents to match the change in pricing in order to avoid infinite money.
/🆑

### CODE REVIEW

**Comment by jupyterkat** [comment]
don't need the nsv edit comments

**Comment by RemervKeberb** [comment]
Removed them.

**Comment by PowerfulBacon** [comment]
How much is manifest worth?

**Comment by RemervKeberb** [comment]
IIRC it is 200 credits

**Review by Archanial — APPROVED** [review]
Fix changelog, rest is good

**Comment by RemervKeberb** [comment]
Done. At least I think

**Review by utilbird — APPROVED** [review]

**Pull request merged**
