### PR TITLE
Some balance changes on Factory away mission

### PR DESCRIPTION
**Pull request by OceanFish1**
## About The Pull Request

Deleted some ammo and contraband spawners, added griefsky somewhere. Also some minor mapping moment changes like adding more access cards so people don't need to use conveyor belts that much.

## Why It's Good For The Game

Mission event happened, some feedback accepted.

## Changelog
:cl:
balance: Replaced some things on The Factory away mission.
/:cl:

### CODE REVIEW

**Comment by OceanFish1** [comment]
Gamers
map

**Comment by OceanFish1** [comment]
ye it loads now with proper size

**Comment by OceanFish1** [comment]
@francinum dud

**Comment by francinum** [comment]
I don't have enough knowledge on this section of mapping to have an opinion beyond wanting to remove the entire map.

**Comment by utilbird** [comment]
Uhh, mapping isn't exactly my strongpoint either. @WhyIsCaeciliusTaken and @PowerfulBacon had a few notable issues with the original map, if any of you would like to weigh in on these changes

**Comment by OceanFish1** [comment]
> Uhh, mapping isn't exactly my strongpoint either. @WhyIsCaeciliusTaken and @PowerfulBacon had a few notable issues with the original map, if any of you would like to weigh in on these changes

Anyone else had notes maybe?

**Comment by OceanFish1** [comment]
understandable

**Comment by Sapfearon** [comment]
Speed merge access fix. God it's annoying to hack all those doors. I would suggest adding some NW/mesons on map too, since you can get fucked without them.

**Comment by OceanFish1** [comment]
> Speed merge access fix. God it's annoying to hack all those doors. I would suggest adding some NW/mesons on map too, since you can get fucked without them.

Mesons will reveal all the secrets fast. Also the factory isn't supposed to be a mining thing so it doesn't fit there as for lore

**Comment by OceanFish1** [comment]
@TheFakeElon merge speed speed merge

**Review by utilbird — APPROVED** [review]

**Pull request merged**
