### PR TITLE
[BOUNTY] Bluespace Mining Machine

### LINKED ISSUE #706: [Bounty] Space Mining Machine
I'm tied up with school and can't decipher the ore network for materials.
Thus, the ($50) request:

A craftable machine that requisitions a small amount of all materials over time and sends them over the network. An automatic, but slow ore refinement machine. 
The theme behind this was that it creates them out of bluespace or is mining nearby asteroids, and provides some income of materials. It requires only power to run, and functions as a replacement for the undoubtedly dead or missing miners that Bee has every round. This prevents low-pop and new miners from ruining the round of three other departments (or more).

My thoughts on the balance were this:
Iron: 1
Glass: 1
Copper: 0.7
Silver: 0.7
Gold: 0.7
Plasma: 0.5
Titanium: 0.3
Uranium: 0.3
Diamond: 0.1
Plastic: 0.1
Bluespace: 0.1

Tickrate: Trickling in at what one brand new miner would provide

**Itemized list of requested items:**
One machine board to build space miner.
One space mining machine that functions as above.
[optional] upgradeable parts increase total gain.
[optional] interface that requires fine tuning to optimize output, ie solar array directional output

edit: I don't know why beebot knocked off the payment on this

### PR DESCRIPTION
**Pull request by ike709**
Closes #706 

Video demonstration: https://streamable.com/wb4u0

## Changelog
:cl:
add: New researchable machine: Bluespace Miner. Slowly creates materials out of nothing and adds them to a linked ore silo.
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Rates subject to change for balance reasons.

**Comment by ike709** [comment]
@jlsnow301

**Comment by ike709** [comment]
For anybody who thinks this is invalidating miners:
1. It's fairly lategame research.
2. It's slow.
3. It requires bluespace crystals, which it does not generate.

**Comment by jlsnow301** [comment]
> 3. It requires bluespace crystals, which it does not generate.

This req alone puts a decent gate on it. "Late game" lrp is practically 25 minutes in, and by then the station is on fire. Sometimes bluespace is not even mined. I approve of this.

**Review by qwertyquerty — APPROVED** [review]

**Comment by ike709** [comment]
Self-merge is gross but qwerty approved the code and the bounty creator approved on discord.

**Pull request merged**
