### PR TITLE
Synthflesh recipe now has silver sulfadizine in it.

### PR DESCRIPTION
**Pull request by r1ks-iwnl**
## About The Pull Request
Changes synthflesh recipe by adding silver sulfadizine to it in order to make synthflesh slightly harder to create.

## Why It's Good For The Game
Synthflesh is stupidly effective and has a very simple recipe, synthflesh recipe also has no chem in it that heals burn damage, only the styptic powder that heals brute damage.

## Changelog
:cl:
balance: Adds silver sulfadizine to synthflesh recipe.
/:cl:

### CODE REVIEW

**Comment by Isy232** [comment]
> results = list(/datum/reagent/medicine/synthflesh = 3)

It requires 4u of chems to make, it should give 4u of synthflesh.

100% agree otherwise

**Comment by r1ks-iwnl** [comment]
Im also thinking of replacing blood with liquid gibs but it's probably not gonna be very appreciated

**Comment by eeSPee** [comment]
> Im also thinking of replacing blood with liquid gibs but it's probably not gonna be very appreciated

Not as easy to obtain

**Review by zeskorion — APPROVED** [review]

**Comment by zeskorion** [comment]
technically passing

**Pull request merged**
