### PR TITLE
More tgui-next

### PR DESCRIPTION
**Pull request by ike709**
Atmos machines use NumberInput now.

Also, the build script now includes the `--check-files` arg to prevent a repeat of the last broken TGUI pull.

🆑 
add: Atmos machine UIs now accept number inputs
add: Crew console and operating computer now use tgui-next
/🆑

### CODE REVIEW

**Comment by ike709** [comment]
Tested locally.

**Comment by ike709** [comment]
Added crew console + operating computer interfaces.

**Comment by qwertyquerty** [comment]
CL

**Comment by ike709** [comment]
@qwertyquerty done

**Pull request merged**
