### PR TITLE
Boxstation - miscellaneous stupid changes

### PR DESCRIPTION
**Pull request by Vexylius**
## About The Pull Request

Moved AI sat access and AI sat so that it can be accessed by RD rather than CE.
Added more of those stupid firelocks so that the atmos won't get killed so easily.
Moved cryo closer to the main hallway so it's more easily accessible.
Changed the bar like completely.
Kitchen window doesn't face the hallway anymore.
There is a proper service hall now.
Added a gaming lounge - the cool kid place. (It doesn't have lights on purpose)
Moved the clown/mime place.

_Can't fix the Box completely, but can try to make it slightly more playable._

## Why It's Good For The Game

CE has his Tcomms next to engineering, let RD have his stupid AI in an accessable place.
Also, miscellaneous fixes are very good.

## Changelog
:cl:
add: Gaming lounge on Boxstation
tweak: Moved some stuff around on Boxstation
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
Can you put a screenshot of the map changes?

**Comment by Vexylius** [comment]
Wait, I'm still doing those changes
for example now I'm completely fucking up the bar and adding arcade place

**Comment by Vexylius** [comment]
AI sat is now connected to Science - that's the initial thing I wanted done
image

**Comment by Vexylius** [comment]
Also, I've moved cryo
image

**Comment by Vexylius** [comment]
Also, changed bar and added a "Gaming lounge" or Arcade
image
image

**Comment by Vexylius** [comment]
aaand there's service hall now instead of that part of maint, because why would you hide service autolathe in some random maint room
image

**Comment by Vexylius** [comment]
And the chef can just say fuck you and close the shutters
image
image
and hydroponics biogenerator is now useable by chef so that botanists won't have to carry 100 flour bags to kitchen window again

**Comment by Vexylius** [comment]
Ping me if and when it will be possible to testmerge it

**Comment by TeomanTheGreat** [comment]
I like these changes. Good work.

**Comment by PowerfulBacon** [comment]
image
this sprite is unbearable to look at

Borders look a little weird
image

image

image
The super long table looks a bit weird, I'd replace the center of it with the food processor

image
The borders look very strange and inconsistent. Also turf decal borders on top of delivery turf decals looks off
Also I don't personally like the changing length of the hallway.
Also is that room maint access?

The AI sat placement is *really* bad and with a super long pipe too.

**Comment by Vexylius** [comment]
All is cool and I'm willing to change it, except the arcade carpet. It's not supposed to be looked at with darkness disabled. Check the screenshot, it looks good in that dimly lit room

**Comment by PowerfulBacon** [comment]
It still looks stroke inducing and is a pretty bad texture overall. Alone it looks ok, but it does too good a job at hiding the objects on top of the turf.

**Comment by ike709** [comment]
this is not getting merged with those sprites.

**Comment by Vexylius** [comment]
Actually nah

**Pull request closed without merging**
