### PR TITLE
Adds "Garbage timer" subsystem to replace the usage of timer from qdel_in()

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
Adds "Garbage timer" subsystem to replace the usage of timer from qdel_in()

`qdel_in()` uses timer subsystem, but its dedicated timer is a target of delete as well.
`garbage timer` does the timer thing, but it won't create timer datum, thus qdel gets faster.

I think this can possibly improve z-mimic?

### NOTE
There are some temp visual with `duration = 0`. It's kinda old sin from older coders. I don't want to fix it right now since the primary aim of this PR is to replace qdel_in(), not refactoring temp visual.

## Why It's Good For The Game
Performance good

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

## Test case: Old timer as qdel_in() with 60000+ qdel

image

Yes, this is awful. You can see spikes

## Test case: New garbage timer (qdel_in() with 60000+)

image

## Some codes that uses qdel_in()

image

Tentacle is fine

(Missing screenshot)

Resonator effect is fine

## Multi z qdel_in() (Used conveyor belts)

image

It's good

</details>

## Changelog
:cl:
code: qdel_in() no longer uses timer subsystem. Garbage timer subsystem is newly added for qdel_in()
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
image

I changed the Garbage Timer logic.
1. The first version of the PR
2. Current
3. addtimer (old `qdel_in()`)

Current version uses assoc with a time key when to delete.

image

So, It doesn't have to compare everything since you only need to check a group's time key.

**Comment by EvilDragonfiend** [comment]
```DM
GLOBAL_LIST_EMPTY(qdel_timers)
/proc/qdel_in(datum/D, time, force=FALSE, ...)
	if(!time)
		qdel(D, force=force)
		return

	var/timer_key = "[time + world.time]"
	if(!GLOB.qdel_timers[timer_key])
		GLOB.qdel_timers[timer_key] = list()
		addtimer(CALLBACK(GLOBAL_PROC, GLOBAL_PROC_REF(_mass_qdel), timer_key), time, TIMER_STOPPABLE)

	GLOB.qdel_timers[timer_key] += D
	return timer_key

/proc/_mass_qdel(timer_key)
	var/list/target_entry = GLOB.qdel_timers[timer_key]
	while(target_entry.len)
		qdel(target_entry[target_entry.len])
		target_entry.len--
	if(!length(GLOB.qdel_timers[timer_key]))
		GLOB.qdel_timers -= timer_key

/proc/qdel_timer_cancle(datum/item, timer_key)
	if(QDELETED(item))
		return

	if(!timer_key)
		for(var/each in GLOB.qdel_timers)
			var/list/each_entry = GLOB.qdel_timers[each]
			var/index = each_entry.Find(item)
			if(index)
				each_entry.Cut(index, index+1)
				return
	else
		var/list/specified_entry = GLOB.qdel_timers[timer_key]
		var/index = specified_entry.Find(item)
		if(index)
			specified_entry.Cut(index, index+1)
			return
```

This is a solution to go with timer that Bacon suggested, but I am not certain if it's really optimal.

**Comment by EvilDragonfiend** [comment]
image

I found the horrible source of qdel_in() with a stupid timer.
I feel the garbage timer is better than Timer subsystem to diagnose timed qdels.

**Comment by EvilDragonfiend** [comment]
The new commit is now more optimised with less CPU and tick usage.

**Comment by PowerfulBacon** [comment]
While it aleviates some problems with spawning 60000 timers, this is not the best solution and it is far preferred if things just batch their qdel timers together in 1 go instead.

**Pull request closed without merging**
