### PR TITLE
[PORT] Filter Blood Surgery + it's updates 

### PR DESCRIPTION
**Pull request by Chessus**
## About The Pull Request
Part 2-Now not from my master

This pr ports the Blood filtering surgery and the Blood filter from nightred [#pr53228](https://github.com/tgstation/tgstation/pull/53228) and [#pr54168](https://github.com/tgstation/tgstation/pull/54168/files).  All sprites belong to the creator of them from the previous pr.
- [x] Add blood filter to maps :
- [x] Adds blood filter to medical toolbelts and kit from [pr53442](https://github.com/tgstation/tgstation/pull/53442):
- [x] Makes it so surgery can not be performed when no regeants are present or on husks. There's code for it but it doesn't fire:
- [x] Make it similar to Tend wounds whereby it is automatically repeatble:  
 

## Why It's Good For The Game

Currently the only way to remove reagents from a player is through chemicals. This pr makes it so you use the Blood filter during Filter Blood surgery remove reagents. Each reagent is remove by reagentvolume*0.22 so large volumes will have more removed. 
 

## Changelog
:cl:
add: Filter Blood Surgery 
add: Adds item Blood filter
add: Added Blood filter to maps in surgery area and Med surgery duffle bag and sec surgery duffle bag. Removed from sec deptuty bag from original pr. 
add: Added Blood filter to tool debug item
add: Can be created in prolathe. Removed from autolathe inline with no surgical tools in autolathes
tweak: The blood filter can now be put in medical belts, medical aid kits and backpacks
tweak: The surgery is automatically repeatable similar to tend wounds  
/:cl:

### CODE REVIEW

**Comment by Chessus** [comment]
So everyting is working so far except:
The check to see if the body is husked or has no reagents doesn't fire----So surgery can be performed
Just compling tg version to see if this occurs there also
```
/datum/surgery/filter_blood/can_start(mob/user, mob/living/carbon/target)
	if(target.reagents.total_volume == 0)
		return FALSE
	if(HAS_TRAIT(target, TRAIT_HUSK)) //You can't filter Husks or zero reagents
		return FALSE
	return ..()

```

**Comment by Chessus** [comment]
Got nowhere asking the same question on 3 discords. Mentioned the issue to the creator of surgery and they are looking for a solution. I'm trying to find one also but to no success so it's back to debugging. I'm thinking of even putting in eye surgery code to see if the canstart is even being checked.

**Comment by Chessus** [comment]
Issuse solved with the can_start() not being checked. NightRed found it, turns out can_start had the surcial step i nthe name, not the surgery 
```/datum/surgery/filter_blood```
 not 
```/datum/surgery/blood_filter```

**Review by qwertyquerty — DISMISSED** [review]

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Unintentional changes to advanced airlock controllers in maps

**Comment by Chessus** [comment]
Yeah no idea what that was. Was hoping you guys would pick it up.

**Comment by qwertyquerty** [comment]
We've fixed the issue with fastdmm that caused it to happen. Just go ahead and remove those changes.

**Comment by Chessus** [comment]
I reverted the chanegs manually via notepad++. Should I have just replaced my modified map files with the current ones then do my changes in fastdmm again?

**Comment by Chessus** [comment]
I'll update the wiki also if this gets merged.

**Review by PowerfulBacon — APPROVED** [review]
Update wiki for merge

**Comment by Chessus** [comment]
Done, [Guide to medicine ](https://wiki.beestation13.com/view/Guide_to_medicine#Toxins), [Guide to surgery](https://wiki.beestation13.com/view/Surgery#Filter_Blood) added to medical tools also

**Comment by felceryan** [comment]
ok but why did u have to remove the drapes

**Comment by Chessus** [comment]
> ok but why did u have to remove the drapes

I'm not sure, where did i remove them from? The deputy bag?

**Pull request merged**
