### PR TITLE
Remove Felinids from Roundstart Races

### PR DESCRIPTION
**Pull request by OptimalSpoon**
## About The Pull Request
I am very new to github, so this code may not work even in the slightest. This simply removes Felinid as a roundstart race.

## Why It's Good For The Game

Felinids have long been a dividing factor in the community. There are several discussions right now on the forum about either removing or merging them with humans. I know a lot of people spend rounds just hating on Felinids, and some Felinids just spend all round being as annoying as possible to garner a reaction.

Felinids as a species have little to no reason to exist in the first place. They are all but Human with a few downsides. Removing Felinids would have little change on gameplay but positively impact community, and either side can no longer pick on each other due to their chosen race. Also, when around a quarter of the station is made up of Felinids, it makes the AI defunct for a lot of people if the AI has the Asimov lawset, further removing interaction from the round. Felinids have also started to create metagangs where they feel safe and can't be as easily bullied. I think this negatively impacts RP and the community as a whole, as people are starting to be separated into friend groups, and no interaction between said groups happens.

Perhaps in the future they could be added as a mutation in genetics, or merged with humans. But for now this is simply a PR to gain attention to the issue which is dividing the community and causing a lot of hate on both sides.

## Changelog
Removed Felinids from the roundstart race list
Removed Felinid related code from the repository
/:cl:

### CODE REVIEW

**Comment by DerpiestBruh** [comment]
based

**Comment by zeskorion** [comment]
Im giving this a thumbs up for comedy value. (Everyone knows the thumbs dont matter)

**Comment by ToasterBan** [comment]
probably going to get instaclosed due to some obscure git policy but it will be nice to see the fireworks

**Comment by DatBoiTim** [comment]
You do know it's against contribution policy to touch species without explicit permission from maintainers right?

And said permission should be screenshotted and included in PR body

**Comment by OptimalSpoon** [comment]
Yeah I have no expectations for this to get actually merged, I just did it to bring attention to the issue

**Comment by mcmeiler** [comment]
> I just did it to bring attention to the issue


To the issue only you percieve. You have a massive grudge against felinids and their players, as evident by the multiple bad-faith reports you've written, and your blatent admission to ick ocking in the discord, blatantly disregarding any rules in the community.

**Comment by DatBoiTim** [comment]
> Yeah I have no expectations for this to get actually merged, I just did it to bring attention to the issue

In be4 repoban

**Comment by Tsar-Salat** [comment]
Screenshot_20220314-133942_Discord
Your time to shine, Archanial!

**Comment by Archanial** [comment]
I gave my auth for removing felinids from the code not from the roundstart races. 
If you edit your PR to remove felinids completely from code ping me for reopen.

**Comment by lmenvs** [comment]
https://github.com/Monkestation/MonkeStation/pull/66

If you're serious, for your consideration

**Comment by ToasterBan** [comment]
> https://github.com/Monkestation/MonkeStation/pull/66
> 
> If you're serious, for your consideration 

we already have the code for starting with alt organs this is just sinful and  even worse

**Comment by lmenvs** [comment]
> > [Monkestation#66](https://github.com/Monkestation/MonkeStation/pull/66)
> > If you're serious, for your consideration
> 
> we already have the code for starting with alt organs this is just sinful and even worse

But you get to watch the weebs literally mutilate themselves to become anime

**Comment by OptimalSpoon** [comment]
Ok, I think i have done it.

I have removed all the code I can find relating to Felinids

@Archanial 

I just gotta figure out how to update the PR. Can it not be done when its closed?

**Comment by TeomanTheGreat** [comment]
> 
> To the issue only you percieve. 


I mean you're wrong lol. I've seen other people (including myself from time to time) complain about this too. I would prefer tighter restrictions on the cringe factor of felinids for rp reasons rather than a removal tho (pretty sure Meiler's comment is bait anyway which i completely fell for 😔)

**Comment by TeomanTheGreat** [comment]
> 
> I just gotta figure out how to update the PR. Can it not be done when its closed?

You have to push your code to the branch that you made for this (I would reccomend asking the coder monkeys in the code channel of the discord for any other help since github aint the most fast paced place to get responses for actual questions)

**Comment by TeomanTheGreat** [comment]
> 
>  You have a massive grudge against felinids and their players, as evident by the multiple bad-faith reports you've written, and your blatent admission to ick ocking in the discord, blatantly disregarding any rules in the community.

Oh and one more thing. I might be a bit forgetful but if i recall correctly for the most part Xeapor has been fairly polite in his reports. Not sure about the ick ock tho since i dont really recall him doing that (unless you mean the one about the felinid conga? Since that was one incident)

**Comment by OptimalSpoon** [comment]
Hm, it seems no matter how much I push it, the commits aren't adding to this PR

**Comment by Archanial** [comment]
Try pushing now @Xeapor

**Comment by OptimalSpoon** [comment]
Ayo thanks chief, that should be it.

If anyone sees anything I missed please say

**Comment by Wilchenx** [comment]
>There are several discussions right now on the forum about either removing or merging them with humans.

I'd like to ask how many of them were by your authorship.

>I know a lot of people spend rounds just hating on Felinids,

Are you saying here that the people are the problem or the felinids?

>Felinids as a species have little to no reason to exist in the first place.

This could be said about a lot of features in the game, things get added because people want them.

>They are all but Human with a few downsides. 

Nearly all non-humans are that.

>Removing Felinids would have little change on gameplay but positively impact community, and either side can no longer pick on each other due to their chosen race.

This is just a bad faith attempt to feign ignorance on your part.

>Also, when around a quarter of the station is made up of Felinids, it makes the AI defunct for a lot of people if the AI has the Asimov lawset, further removing interaction from the round.

This is not a ""issue"" exclusive to felinids?
This is not even an issue in the first place, AI is not just a door opener you know.

>Felinids have also started to create metagangs where they feel safe and can't be as easily bullied.

lol

>I think this negatively impacts RP and the community as a whole, as people are starting to be separated into friend groups, and no interaction between said groups happens.

If your ""interactions"" and ""RP"" is related to the sentence then I don't know what you're trying to say here.


yeah i bit the bait so what

**Comment by Naevii** [comment]
This again... will this ever be gone.

**Comment by Wilchenx** [comment]
> This again... will this ever be gone.

image

**Comment by nednaZ** [comment]
Don't forget "Purrturbation" buttons under admin secrets and I believe the variable editor

**Comment by yyzsong** [comment]
I can't believe we're having our annual felinid removal PR only 3 months in

**Comment by OptimalSpoon** [comment]
>I can't believe we're having our annual felinid removal PR only 3 months in

The fact it is an annual thing shows how much a large part of the community wants it removed

**Comment by Wilchenx** [comment]
> > I can't believe we're having our annual felinid removal PR only 3 months in
> 
> The fact it is an annual thing shows how much a large part of the community wants it removed

Why did they lose the vote 8 times then?

**Comment by yyzsong** [comment]
> > I can't believe we're having our annual felinid removal PR only 3 months in
> 
> The fact it is an annual thing shows how much a large part of the community wants it removed

Beestation's only really been a thing for what, three years? Schizo felinid PRs are always gonna be a thing

**Comment by ivanmixo** [comment]
He really thinks removing felinids will fix anything pfft

**Comment by OptimalSpoon** [comment]
This always happens, Felinid mains come in and start making arguments without any basis. If you are actually against this, then please write a few sentences on the pros of Felinids

**Comment by Crossedfall** [comment]
Alright. So, here's the basic deal. This is the exact same removal PR that we get every year and it's losing its luster. We get the same arguments from both sides and inevitably nothing changes. The only thing that actually comes out of these PRs is animosity and people yelling at each other. 

To try and appeal to both sides of the table I'm doing the following..

Firstly, I'm closing this PR. Rug pull species removal PRs are unequivocally a dick move when said species is actively being used by a decent enough portion of our community.

Secondly, I am giving my open approval to port over the necessary changes needed to disable a round start race without actually purging preexisting characters. Once those changes are migrated over and we confirm that they're working (rip squids), _**then**_ we can talk about disabling Felinid as a round-start species and talk about long-term changes.  The port **must be separate** from the PR seeking to disable them. If someone tries to do both in one PR I'm going to block or close it until it's done properly.

Thirdly, I am going to openly give my support to the idea of migrating Felinids from being their own species into being a subset of humans. I personally think that option gives way to a lot of interesting customization options to not only humans, but paves the way for added options for the other round-start picks as well. There's a lot of talk to be had on the best way to implement this, but that's a discussion to be had elsewhere.

**Pull request closed without merging**
