### PR TITLE
kelotane now has 3 ingredients

### PR DESCRIPTION
**Pull request by boolsrealm**
the other 2 basic healing medicines have 3 ingredients so why doesn't this have 3, annoying as fuk, it needs water now

makes tricordrazine easier to mass produce haHAA

### changelog:

(i was busy doing other shit sorry this shit took a week bruh bruh)

change: kelotane now needs water
change: kelotane now produces 3 units, to account for the 3 chemicals needed

will change the chem wiki once/if this gets merged

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Is this solely to ease your plumbing life

**Comment by St0rmC4st3r** [comment]
No CLs too

**Comment by boolsrealm** [comment]
yes its soley to ease my plumbing life

**Comment by WhyIsCaeciliusTaken** [comment]
Merging master branch moment.

**Review by ike709 — CHANGES_REQUESTED** [review]
Needs a changelog.

**Comment by Isy232** [comment]
REEEEEEEEEEEEEEEEEEE THIS WILL MAKE MAKING MY EPIC HEALING MIX HARDER
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
Still voting yes though...

**Comment by ike709** [comment]
Still needs a changelog. And you need to update the guide to chemistry on the wiki.

**Comment by boolsrealm** [comment]
k lol

**Comment by ike709** [comment]
That's not how you format a changelog. See literally any other PR. Otherwise it won't get parsed.

**Pull request closed without merging**
