### PR TITLE
Makes crewsimov the default lawset on golden.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Titles.

## Why It's Good For The Game

There is no reason for asimov to be the norm since all it's used for is give the AI a reason to grief non-humans, but even shittier it forces the AI to protect human antags like wizards and nukies (you'd be suprised by how often they dont change the laws), and makes security being able to de-crew people a redundant feature.

## Changelog
:cl:
tweak: Crewsimov is now the default lawset on golden.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
yeah fuck, can someone remove the labels?

**Comment by ghost** [comment]
i did some fucky shit.

**Comment by Moccha-Bee** [comment]
yes

**Comment by ghost** [comment]
alright lets try this again

**Pull request closed without merging**
