### PR TITLE
Removes bolt of change from Chaos Carp

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Removes bolt of change projectile from Chaos Carp.

## Why It's Good For The Game

No more rounds ruined by non antag xenobiologists creating non antag chaos carp to create "non antag" syndie borgs, dragons and other random round destroying mobs.

## Changelog
:cl:
balance: Removed bolt of change from Chaos Carp.
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
Sad, but this has to go. It's been abused a lot lately.

**Comment by yyzsong** [comment]
Cant normal magicarp still roll Bolt of Change?

**Comment by Sinestia** [comment]
This was probably inevitable

even if it's a bit sad 2 see 



> Cant normal magicarp still roll Bolt of Change?

wym?

**Comment by ItsTisme** [comment]
Its still rare and pretty fun, if wabajacked borgs and dragons kill peeps its still self antagging. Might aswel remove the wabajack shuttle at that point

**Comment by Sinestia** [comment]
> Its still rare and pretty fun, if wabajacked borgs and dragons kill peeps its still self antagging. Might aswel remove the wabajack shuttle at that point

this is a pretty bad equivalence when that shuttle is at the end, requires multiple people to cooperate, etc.

**Comment by yyzsong** [comment]
> wym?

Chaos magicarp are just a version of magicarp that have all of the bolts and spew them randomly instead of just having one bolt

**Comment by Sinestia** [comment]
> > wym?
> 
> Chaos magicarp are just a version of magicarp that have all of the bolts and spew them randomly instead of just having one bolt

`/mob/living/simple_animal/hostile/carp/ranged/chaos/Shoot()
	projectiletype = pick(allowed_projectile_types)
	..()`

derived from the normal magicarp list, so both lose it in this PR

**Comment by utilbird** [comment]
It was fun while it lasted

**Comment by Archanial** [comment]
To be honest, magicarps should be removed as a whole.

**Comment by Cenrus** [comment]
While you're at it, bolts of death and resurrection should go. Death is self explanatory, resurrection is a literal aheal intended for wizards and makes medical totally redundant

**Comment by yyzsong** [comment]
> derived from the normal magicarp list, so both lose it in this PR

if that's the case the changelog needs changing

**Comment by Sapfearon** [comment]
why bother with xenobio then? xenolings removed, carps removed, literally nothing to do there now. Removing bolt from chaos carp is okay, removing HOLY GRAIL OF XENOBIO (change carp) is not.

**Comment by Sinestia** [comment]
> why bother with xenobio then? xenolings removed, carps removed, **literally nothing to do there now.** Removing bolt from chaos carp is okay, removing HOLY GRAIL OF XENOBIO (change carp) is not.

image

**Comment by Rukofamicom** [comment]
> why bother with xenobio then?

The absolute ignorance of this statement baffles me. Xenobiology has more cool toys and things to do/make than are ever possible to do in a single round, even if it goes on for several hours.

My opinion of the PR is that shitters should be banned rather than taking away what is, in the grand scheme of things, not that abusable of a function.

**Comment by Sinestia** [comment]
> My opinion of the PR is that shitters should be banned rather than taking away what is, in the grand scheme of things, not that abusable of a function.

 its hard to think of a more abusable function

but im a bit ambivalent on this, practically change hasn't really been a problem admin-side i don't believe. Those carps aren't made terribly often and the only shitter carp I can remember ever seeing was a door boi. 

heal is probably the biggest problem since it actually gets used and might be pretty OP. And I'm biased as I have fond memories of being saved by a based carp from a validhunting HoS catgirl 
death maybe as well

**Comment by Sinmero** [comment]
Dont remove it from magicarp. It takes significant amount of luck to get bolt of change magicarp so we dont get to see it so often.
No fun allowed.

**Comment by ghost** [comment]
no fun allowed.
make it so that chaos carp wizard still have change bolt?

**Comment by PowerfulBacon** [comment]
Remove death too

**Comment by OceanFish1** [comment]
remove xenobio too

**Comment by ghost** [comment]
> Remove death too

If it's required to merge this, then sure. My line of thinking is that if fireball and other lethal effects can remain, death bolt and resurrect bolt are similarly justified. Their effects are immediate and only apply to who they are used on, it does not gunk the whole round as a megafauna or a crew turned into syndicate borg that exists in a grey area rules-wise.

Nevertheless, if you make it a requested change for this PR then I don't really feel strongly about removing it and will do so.

**Comment by PowerfulBacon** [comment]
a barely counterable ranged instakill is a lot worse than turning someone into an overpowered borg

**Comment by ghost** [comment]
Alternative solution https://github.com/BeeStation/BeeStation-Hornet/pull/3570

**Comment by ItsTisme** [comment]
> > Its still rare and pretty fun, if wabajacked borgs and dragons kill peeps its still self antagging. Might aswel remove the wabajack shuttle at that point
> 
> this is a pretty bad equivalence when that shuttle is at the end, requires multiple people to cooperate, etc.

It needs only 1 guy with some money to buy and it its especialy bad because people tend to be more ass at round end especialy on such a small and crowded shuttle

**Comment by Sinestia** [comment]
> > > Its still rare and pretty fun, if wabajacked borgs and dragons kill peeps its still self antagging. Might aswel remove the wabajack shuttle at that point
> > 
> > 
> > this is a pretty bad equivalence when that shuttle is at the end, requires multiple people to cooperate, etc.
> 
> It needs only 1 guy with some money to buy and it its especialy bad because people tend to be more ass at round end especialy on such a small and crowded shuttle

i've never seen it be a problem or even annoying


better phrasing would be that way more people are involved instead of a xenobiologist in his autism corner

**Comment by MNarath1** [comment]
Chaos magicarps are probably one of the most weakest xenobio mobs of all cause while they do have access to all the bolts its impossible to determine what they are gonna roll seriously like its as likely to get bolt of death as bolt of healing really not unlikely for a carp to just heal his enemy instead of killing him and bolt of change is rarely used for chaos magicarp cause of rnd

**Comment by MNarath1** [comment]
Also magicarps are most likely the only thing you can use to reverse polymorph from wizards as simplemobs do not process chems so you cannot use things like mutation toxin

**Comment by ItsTisme** [comment]
>better phrasing would be that way more people are involved instead of a xenobiologist in his autism corner

Yes instead of it taking 1 captain to walk to every heads office and get there budget card to buy a shuttle thats available literally every round is infact much more difficult then the autistic RNG grind.

**Comment by ItsTisme** [comment]
I have seen this magi-carp trick done only a rare handfull of times and usualy it works quite well. If people change bolt into a simple mob and grief then that sounds more a admin problem if anything.

Also a very RNG based change bolt that wont even let you pick what you become is not nearly as bad as nullcrate spam, I have seen more indirect griefing by nullcrates then change meme

**Comment by Sapfearon** [comment]
As someone who mains xenobio your only goal is to get change carp and nothing else. What "cool toys" you have aside from it? Pointless armor? Useless and broken shield? Crappy random knife? 90% of crossbreeds are pointless crap that you never make. 
Like standart xenobio round is - reproductive grey, industrial grey, repro blue/dark blue/yellow/dark purple/gold/light pink/red.
Maybe repro bluespace if station needs it. THAT'S IT. Golems are not exicted thing to make, making sentient mob is not interesting given that only interesting mob here is carp. 
Change carp is goal you will work sooner or later, it's literally one of 2 ways to get ling ( aside from lazarus+mind transfer on dead headspider). There are already rules about not being antag if you got race change. Instead of nerfing last fun sci job you better port goon geneticist instead of most boring crap we have right now.

**Comment by OceanFish1** [comment]
remove science its too op!!1

**Comment by ghost** [comment]
> As someone who mains xenobio your only goal is to get change carp and nothing else.

Thank you for making an excellent point. Xenobiology and botany are the two departments with the most content in this entire game, it's rarely possible to do most of it in any single round. If dedicated players such as yourself perceive a department in this way, having only a singular worthy goal despite all this content that's seen as just an obstacle to the end game, then it may be pointing to a flaw in design.

I would personally not have an issue for a department to have a singular end game goal. My issue is entirely on the effect of this goal on the rest of the round. Chaoscarp (or even magicarp) is such a strong force in a round that it's actually more intimidating than antagonists. It doesn't just have the ability to kill you in one hit, it can permanently destroy your round should the player so much as accidentally click in your way, transforming you into an otherwise irreversible state that only it can fix.

It can create actual antagonists in form of syndicate borgs, it can create megafauna, it can create xenomorphs, it can effortlessly revive the dead into a perfect state, it can instantly kill you, it's just so far out there in the powerscale compared to anything else but wizards or other round ending gamemodes.

When I see a chaoscarp wander the hallway, I run out of sight as fast as possible because I actually enjoy playing the game instead of risking spending it as a mob whose only interaction with the environment is left click smashing walls. The second I see that xenobiology rushed their carp in the first 20 or so minutes of a round, I already know the round will be utter gunk from the unending chaos that comes with such powerful entity existing. It's no longer about being a spaceman in space, it's about a bunch of people following a carp around so it can blast them with their magic so they get more gameplay power, or so they can spam everything purple as xenos. Then they spend the rest of their round patrolling the station looking for a fight to use their newly gained power on.

**Comment by MNarath1** [comment]
> > As someone who mains xenobio your only goal is to get change carp and nothing else.
> 
> 
> 
> Thank you for making an excellent point. Xenobiology and botany are the two departments with the most content in this entire game, it's rarely possible to do most of it in any single round. If dedicated players such as yourself perceive a department in this way, having only a singular worthy goal despite all this content that's seen as just an obstacle to the end game, then it may be pointing to a flaw in design.
> 
> 
> 
> I would personally not have an issue for a department to have a singular end game goal. My issue is entirely on the effect of this goal on the rest of the round. Chaoscarp (or even magicarp) is such a strong force in a round that it's actually more intimidating than antagonists. It doesn't just have the ability to kill you in one hit, it can permanently destroy your round should the player so much as accidentally click in your way, transforming you into an otherwise irreversible state that only it can fix.
> 
> 
> 
> It can create actual antagonists in form of syndicate borgs, it can create megafauna, it can create xenomorphs, it can effortlessly revive the dead into a perfect state, it can instantly kill you, it's just so far out there in the powerscale compared to anything else but wizards or other round ending gamemodes.
> 
> 
> 
> When I see a chaoscarp wander the hallway, I run out of sight as fast as possible because I actually enjoy playing the game instead of risking spending it as a mob whose only interaction with the environment is left click smashing walls. The second I see that xenobiology rushed their carp in the first 20 or so minutes of a round, I already know the round will be utter gunk from the unending chaos that comes with such powerful entity existing. It's no longer about being a spaceman in space, it's about a bunch of people following a carp around so it can blast them with their magic so they get more gameplay power, or so they can spam everything purple as xenos. Then they spend the rest of their round patrolling the station looking for a fight to use their newly gained power on.
> 
> 
> 
> 
> 
> 

Interresting that you would only think about gold extract as a worth goal that is pretty dam simplistic if you just happen to read trough the wiki you will realize that gold slimes are just the tip of the ice of worth endeavors to actually act upon and i am not talking about shields and stuff you can make a camera that rewinds injuries teleportation beacon that work like quantum pads just better replicating matter and a lot of other stuff honestly saying just that is useful is kinda ridiculous there is so much more you can do then just making magicarps

**Comment by ghost** [comment]
> Interresting that you would only think about gold extract as a worth goal that is pretty dam simplistic if you just happen to read trough the wiki you will realize that gold slimes are just the tip of the ice of worth endeavors to actually act upon and i am not talking about shields and stuff you can make a camera that rewinds injuries teleportation beacon that work like quantum pads just better replicating matter and a lot of other stuff honestly saying just that is useful is kinda ridiculous there is so much more you can do then just making magicarps

I hope you realize who you quoted and who you responded to.

**Comment by MNarath1** [comment]
> > Interresting that you would only think about gold extract as a worth goal that is pretty dam simplistic if you just happen to read trough the wiki you will realize that gold slimes are just the tip of the ice of worth endeavors to actually act upon and i am not talking about shields and stuff you can make a camera that rewinds injuries teleportation beacon that work like quantum pads just better replicating matter and a lot of other stuff honestly saying just that is useful is kinda ridiculous there is so much more you can do then just making magicarps
> 
> 
> 
> I hope you realize who you quoted and who you responded to.

Yes i decided to quote you to adress him and your response too just to say there is more to xenobio then making mobs even trough i sadly see that very much overused especially by new xenobiologists instead reading trough the actual wiki seeing that there is a lot more you can use especially now that we finally get new crossbreeds.

**Review by utilbird — APPROVED** [review]

**Comment by utilbird** [comment]
There's plenty more xeno loot to powergame, we'll be fine without the borderline admin smite one

**Pull request merged**
