### PR TITLE
makes the Syndicate base a little "safer" while also adding minor QoL

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request

its a simple change, adds a couple turrets, an extra syndicate intercom and railings alongside one of the "exits"

## Why It's Good For The Game

1.Dakka=gud
2.prevents cheesing
2.Qol is Qol

## Changelog
:cl: Jimmy Brickets
add: More Dakka to the Lavaland Syndicate base
add: Railings to a part of the Lavaland Syndicate base
add: an extra Syndicate intercomm to the Lavaland Syndicate base

/:cl:

### CODE REVIEW

**Comment by DatBoiTim** [comment]
Syndicate now OSHA compliant???????? BASED???????

**Review by utilbird — APPROVED** [review]

**Comment by ToasterBan** [comment]
my baby, my child, my pr, on pr-player-input


it's beutiful

**Review by PowerfulBacon — APPROVED** [review]

**Comment by ToasterBan** [comment]
mergemyfuckingpr.gif

**Comment by utilbird** [comment]
Oh right, I forgot I put this up to vote

**Pull request merged**
