### PR TITLE
Adds AI_Detect to Observer Data Huds

### PR DESCRIPTION
**Pull request by ro5490**
## About The Pull Request

Adds Toggle AI HUD verb for observers, allowing observers to see where the AI is looking without having to seperately observe or orbit the AI-Eye

## Why It's Good For The Game

No clue, It'd just be really nice to have.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

aihuds

</details>

## Changelog
:cl:
tweak: Observers can now see the AI Detection HUD by using the Toggle AI HUD verb in the ghost tab.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
This seems like it would get quite annoying since it is very extreme in the highlighting. This should be a toggleable preference that is disabled by default.

**Comment by EvilDragonfiend** [comment]
how about using a peacekeeper borgo's blue box?

**Comment by ro5490** [comment]
> This seems like it would get quite annoying since it is very extreme in the highlighting. This should be a toggleable preference that is disabled by default.

I was planning on doing this instead, but I was lazy tbh

**Comment by ro5490** [comment]
> > This seems like it would get quite annoying since it is very extreme in the highlighting. This should be a toggleable preference that is disabled by default.
> 
> I was planning on doing this instead, but I was lazy tbh

finally got round to it

**Comment by ro5490** [comment]
pls no stale

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
