### PR TITLE
Better communication ability to revenant and AI holopad, with a new holocall chat format

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
* AI holopad will show runechat
* revenant will show runechat as long as they're not incorporeal
* revenant telepathy now uses runechat that is only visible to you and your target + ghosts
* revenant now can understand all languages (only understand those)
* adds holopad radio channel, actually not a real radio channel, mimics it, but better to read.

## reminder
It has three fixes
* https://github.com/BeeStation/BeeStation-Hornet/pull/9482
* https://github.com/BeeStation/BeeStation-Hornet/pull/9496
* https://github.com/BeeStation/BeeStation-Hornet/pull/9517

## Why It's Good For The Game
No runechat is bad for RP

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image

image

image

image

this holocall radio channel is only visible to ghosts and AI, so holocall users will read chat logs very normally.

image

</details>

## Changelog
:cl:
add: Revenant telepathy now shows runechat
add: Revenant say (runechat) will be visible to nearby ghosts & revs. Living people still need revenant telepathy to hear them.
tweak: Revenant say will not be transmitted to all revenants. They should be within say range.
add: Revenant can understand all languages
add: AI hologram from holopad now shows runechat (note: ai holopad is available by ':h') - You must be within the hearing range from holopad, not hologram, because holopad is the actual source of sound, but runechat over hologram is QoL.
add: Holocall mimic-radio channel for AI/ghosts
code: cleaned up some weird AI code
code: improved some say code, and updated say_readme.md
/:cl:

### CODE REVIEW

**Comment by bluezorua** [comment]
did you test to see if runechat still appears if runechat is disabled in preferences?

**Comment by EvilDragonfiend** [comment]
> did you test to see if runechat still appears if runechat is disabled in preferences?

ah, now it makes sense for some lines. I will fix that.

**Comment by EvilDragonfiend** [comment]
> did you test to see if runechat still appears if runechat is disabled in preferences?

Rev runechat was the only problem, and now it's fixed with more improvement

**Comment by EvilDragonfiend** [comment]
Prioritise this please: https://github.com/BeeStation/BeeStation-Hornet/pull/8829

**Comment by EvilDragonfiend** [comment]
Sets to draft until the essential system is merged.

**Comment by EvilDragonfiend** [comment]
TODO:
change rev language to meta
change rev runechat range to specific area

**Comment by EvilDragonfiend** [comment]
image

now it's perfect

**Comment by EvilDragonfiend** [comment]
adding this to other stuff like BB or something else will be done later since it's a bit out of scope for now.

**Review by itsmeow — APPROVED** [review]
This looks fantastic. Great work!

**Pull request merged**
