### PR TITLE
Reverts circuitry components nerf and adds ID locking

### PR DESCRIPTION
**Pull request by aidan-bowman**
First PR I've made, so tell me if I've made mistakes, or if you think i should add more components to the list of blocked components. Should revert #3975.  

## About The Pull Request

Re-adds in the reagents tab as well as the grenade primer. A circuit imprinter starts locked, and by swiping an ID with bridge access you can unlock it/lock it again. Some components require this ID locking to be unlocked to be printed.

## Why It's Good For The Game

Allows more complex circuiting as well as integrating it more in the game, which is always a good thing when it comes to circuits. Balancing issues avoided by making all the "dangerous" components (for example, the grenade primer), to require an ID.

## Changelog
:cl:
add: re-adds the reagent tab as well as the grenade primer and gun circuit
balance: dangerous components require ID
/:cl:

### CODE REVIEW

**Comment by aidan-bowman** [comment]
Ah, nevermind. If someone knows how fixing conflicts works, tell me, 'cause there's not many resources on coding that I can find.

**Comment by Sinestia** [comment]
update ur local master

type git merge master from ur branch

and then use whatever tool to fix the collisions 


you can also do it on github if you want to get bullied

**Comment by bloons3** [comment]
Does chemistry require the CMO to swipe their ID on the chemistry dispenser in order for them to make meth grenades?

**Comment by aidan-bowman** [comment]
> Does chemistry require the CMO to swipe their ID on the chemistry dispenser in order for them to make meth grenades?

i thought it was a stupid nerf to begin with but i assumed if i just reverted it it would be denied



> update ur local master
> 
> type git merge master from ur branch
> 
> and then use whatever tool to fix the collisions
> 
> you can also do it on github if you want to get bullied

github way isn't working

as for the command thing, i really don't understand what you mean. i'm absolutely clueless about github and i've never used it before this project

**Comment by PowerfulBacon** [comment]
So you have to get a head to scan the machine before you can unlock broken circuit components? Bad idea.

**Comment by aidan-bowman** [comment]
> So you have to get a head to scan the machine before you can unlock broken circuit components? Bad idea.

hey if i just reverted the change it would get denied instantly lol

**Comment by PowerfulBacon** [comment]
> 
> 
> > So you have to get a head to scan the machine before you can unlock broken circuit components? Bad idea.
> 
> hey if i just reverted the change it would get denied instantly lol

and this wont?

**Comment by Sinestia** [comment]
> > Does chemistry require the CMO to swipe their ID on the chemistry dispenser in order for them to make meth grenades?
> 
> i thought it was a stupid nerf to begin with but i assumed if i just reverted it it would be denied
> 
> > update ur local master
> > type git merge master from ur branch
> > and then use whatever tool to fix the collisions
> > you can also do it on github if you want to get bullied
> 
> github way isn't working
> 
> as for the command thing, i really don't understand what you mean. i'm absolutely clueless about github and i've never used it before this project

What client? 

 You can do it with any, but the same principle is there
you gotta 
1. update your master branch
2. checkout your feature branch and
3. Merge master into your feature branch

**Comment by aidan-bowman** [comment]
I think i'm figuring it out. I had to set my master as upstream. now i just gotta figure out how to edit my PR

i use GitKraken btw

**Comment by Sinestia** [comment]
You just push to your github fork's branch once you've fixed it locally. it'll automatically update this PR

(also. Add beestation as a remote if you havent)

**Comment by aidan-bowman** [comment]
Figured it out

**Comment by utilbird** [comment]
Reagent circuit power is greatly exaggerated for almost all of the components. Even moreso with circuit cloning disabled

**Comment by TheFakeElon** [comment]
How to spot a bad PR ((#3975) working 2021) 
image

**Comment by utilbird** [comment]
(Esports ready PR moment)
image

**Comment by aidan-bowman** [comment]
err... how long is this pr gonna take to get merged/closed

**Comment by aidan-bowman** [comment]
the faster this pr gets merged/closed the faster i can fix the issues/get cracking with more pr's

**Comment by ike709** [comment]
> the faster this pr gets merged/closed the faster i can fix the issues/get cracking with more pr's

Learn how to branch

**Comment by ike709** [comment]
Anyways circuits, without a groundup rewrite, are on the way out.

**Pull request closed without merging**
