### PR TITLE
[READY] Repipes BoxStation

### PR DESCRIPTION
**Pull request by Cenrus**
## About this PR

Completely changes the box piping network. Scrubbers and air supply pipes are now on different layers and run alongside eachother.

Old medical pipes
old

New medical pipes
new

## Changelog

:cl:
tweak: Improved piping in BoxStation
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
Am still unsure on whether or not multi-layered pipes working roundstart, have heard people saying they don't work (kilostation)

**Comment by Cenrus** [comment]
Do not merge just yet, there are a few things that I need to address.

**Comment by Cenrus** [comment]
issues fixed, ready to merge now

**Comment by Cenrus** [comment]
> 
> 
> Am still unsure on whether or not multi-layered pipes working roundstart, have heard people saying they don't work (kilostation)

I did tests. Air is being distrbuted and the scrubbers are working fine

**Comment by Crossedfall** [comment]
Conflicts need to be resolved before I can test merge.

**Comment by Cenrus** [comment]
I have no idea how to fix map merge conflicts. I believe the xeno egg added in 790 is the cause, but it's still failing after adding it. You could merge it regardless, and I'll readd the egg later.

**Comment by Cenrus** [comment]
There should be absolutely no conflicts but the check doesn't like me.

**Comment by Cenrus** [comment]
@crossedfall are you able to merge this regardless? I've resolved the conflict.

**Comment by MarkSuckerberg** [comment]
You sure? You need to merge the updated master branch into this branch for it to work properly. It still shows merge conflicts, at least from what I can tell.

**Comment by Cenrus** [comment]
How do I merge the master branch to here?

**Comment by MarkSuckerberg** [comment]
If you're using git kraken, first, make sure your master branch is updated to the upstream master branch, then, make sure you have the branch the PR is on checked out (repipebox), and then, finally, right click the latest commit on the master branch and hit merge master into repipebox. That should work, if memory serves.

**Comment by Cenrus** [comment]
all is well.

**Comment by MarkSuckerberg** [comment]
Oh, it worked. Wonderful!

**Comment by Crossedfall** [comment]
Test merged onto Golden

**Review by Crossedfall — APPROVED** [review]
All good!

**Pull request merged**
