### PR TITLE
Round will not end the instant all heretics are dead

### PR DESCRIPTION
**Pull request by Sinmero**
## About The Pull Request

Heretics are not conversion antags so the round should not end when they die.
Prevents the round ending the instant all heretics are dead.
Also adds heretics to the endgame credits.

## Why It's Good For The Game

The round wont end prematurely because the sole heretic died somewhere at maints.

## Changelog
:cl:
tweak: Round will not end the instant all heretics are dead
tweak: Adds heretics to the endgame credits
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
Just make it not end the round when they all die

**Comment by february-ops** [comment]
But thats their only way to win tho

**Comment by Sinmero** [comment]
Why was is made to end the round when all heretics die in the first place? Is there a reason behind that?
The round usually ends prematurely when all antags that can convert die (cult, monky, revs) or if it is wiz or nuckies.
As far as i know heretics cant convert and dont end the round by achieving their objective.

**Comment by PowerfulBacon** [comment]
It should be continuous since it's not a conversion antag gamemode and a spinoff of traitors

**Comment by PowerfulBacon** [comment]
Also this should be done via the config

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Make it continuous in the config, and if you still want to raise the min number, do it via config also

**Review by PowerfulBacon — DISMISSED** [review]
@Crossedfall config changes

**Review by qwertyquerty — DISMISSED** [review]
Need to change the sage config too

**Comment by Sinmero** [comment]
Done

**Review by Crossedfall — APPROVED** [review]
Config applied.

**Pull request merged**
