### PR TITLE
Adds TG's felinid tail wag as an alternate selectable tail type.

### PR DESCRIPTION
**Pull request by Kapu1178**
hNhaYD4o67

## About The Pull Request
TG's tail wag animation is on a new tail type named "Cat Smooth", selectable in prefs.
[src](https://github.com/tgstation/tgstation/pull/56750)

## Why It's Good For The Game
Customization good. People were and still are split on this sprite, and I think this is a good compromise. 

## Changelog
:cl:EikoBiko
add: New selectable Cat tail type, nya! Sprite by EikoBiko
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
This is race change, did anyone authorized it?

**Comment by Kapu1178** [comment]
> 
> 
> This is race change, did anyone authorized it?

Bacon

**Comment by PowerfulBacon** [comment]
The sprite looks pretty bad and is very furry 🔑

**Comment by PowerfulBacon** [comment]
Show the sprite in game transitioning from normal to wag

**Comment by Crossedfall** [comment]
> Show the sprite in game transitioning from normal to wag

Also link to the original PR and give proper credits in the CL.

**Comment by Kapu1178** [comment]
Will do both of those when I return from work.

**Comment by Kapu1178** [comment]
> 
> 
> Show the sprite in game transitioning from normal to wag

done

**Pull request closed without merging**
