### PR TITLE
Radio beeps per department but I learned how to make usable sfx

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
Repost of #7401 that doesn't have as grating sounds and also a cooldown
Each department plays a small radio tone when recieving a message from it

The way the cooldown works is every department radio message resets the timer, and if 20 seconds pass without a departmental message, the next message triggers the dept chime. This greatly helps reduce spam, as the long delay helps it not get exhausing

AND ALSO THERES A TOGGLE UNDER GAME PREFS

## Why It's Good For The Game
Quickly gets your attention about a new message, charm, little easter eggs and also **IT HAS A COOLDOWN THIS TIME**, it wont spam, it will work, its F I N E

AN D YOU CAN DISABLE IT

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/73374039/181898426-78dc204c-2937-4e93-8e8a-4f5b64e2abec.mp4

https://user-images.githubusercontent.com/73374039/182070685-7f1a9c39-78e9-40a0-ab06-50b4c71c4e07.mp4

(the cooldown was disabled for the showcase video)

</details>

## Changelog
:cl:
soundadd: department chat gets new tones
add: toggle to disable department tones
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
Maybe make it as a toggleable option? that way if someone really dislike it they can keep it disabled either as a game preference or in the headset

Now that's not constantly spammed it's an interesting feature to have

**Comment by Crossedfall** [comment]
Provide a demonstration for all of the sounds so we don't have to download the files again. If they're the exact same sounds from the last PR.

**Comment by etherware-novice** [comment]
just realized it runtimes on poly..

**Comment by etherware-novice** [comment]
hey presto it finally stopped runtiming on poly

**Comment by etherware-novice** [comment]
@Crossedfall theres your showcase ^^

**Comment by PowerfulBacon** [comment]
It scares me that this has been labelled as sql

**Comment by etherware-novice** [comment]
> It scares me that this has been labelled as sql

it just edits the savefile stuff to add a toggle thats why its sql

**Comment by Miliviu** [comment]
May we know where are all this sounds from?
The Security one sounds like the Half Life 2 Metropolice radio and I really don't know what's the Licensing of it

**Pull request closed without merging**
