### PR TITLE
JaniDrobes now have equipment for two janitors

### PR DESCRIPTION
**Pull request by Cenrus**
About The Pull Request

Janitors angry.

Why It's Good For The Game

Janitor is a popular role on BeeStation, so the amount of equipment they get needs to be increased.

Changelog

:cl: Cenrus
add: JaniDrobes now have equipment for two janitors.
/ :cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
It looks like the changelog script script is skipping over your merged prs. I think it's because you're using a copied version of the PR template that has the CL unicode character (🆑) instead of using markdown version `:cl:`. When creating your PRs can you please use the correctly formatted template? Or at least replace the unicode characters with `:cl:`?

**Comment by Cenrus** [comment]
Sure, can you get me a link to the template?

**Comment by Crossedfall** [comment]
> 
> 
> Sure, can you get me a link to the template?

Yup, you can see it here: https://raw.githubusercontent.com/BeeStation/BeeStation-Hornet/master/.github/PULL_REQUEST_TEMPLATE.md

**Review by ike709 — APPROVED** [review]

**Review by MarkSuckerberg — APPROVED** [review]
About time.

**Pull request merged**
