### PR TITLE
Orbit panel now tracks antag team correctly + Minor tweak

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
* Orbit panel now tracks antag team correctly
Abductors/ERTs will not be in separated category

* changes some code to display antag category pretty
* eldritch horrors are now displayed in orbit antag panel (they're obvious already)

## Why It's Good For The Game
fixing old shit + improve orbit panel

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
add: Orbit panel tracks antag team rather than individual antag name (i.e. ERTs, Abductors)
fix: job icon in orbit panel no longer looks horrible
tweak: some antagonists/teams will display some different name in orbit panel
tweak: eldritch horrors are now tracked in antag category in orbit panel
/:cl:

### CODE REVIEW

**Comment by Eric-01** [comment]
While you are at it, could you also replace the `ml` attribute of the Box component in Orbit.js with `mr` (since the job icon is now displayed to the left of the character name)?

**Comment by EvilDragonfiend** [comment]
> While you are at it, could you also replace the `ml` prop of the Box component in Orbit.js with `mr` (since the job icon is now displayed to the left of the character name)?

uh I don't know tgui well. what does that do?

**Comment by Eric-01** [comment]
It allows you to set margins of a particular element, where `ml` = left margin, `mr` = right margin.

**Comment by itsmeow** [comment]
Yes please fix the margin it's horrible

**Comment by EvilDragonfiend** [comment]
image

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
