### PR TITLE
Mask/jetpack PR. Jetpacks pending. Mask is now new PR.

### PR DESCRIPTION
**Pull request by PerishedFraud**
## About The Pull Request

 

- Update: Check this poll out and let's see if we can reach a consensus on jetpack availability. 

- https://forums.beestation13.com/t/jetpacks-for-exploration-mining-opinions-needed/14661

This PR used to have two things in it but there was some controversy over jetpacks and who exactly should have them. The link above leads to a relevant poll and the fate of jetpack upgrades is pending. Meanwhile the first part of the PR can be found here:
https://github.com/BeeStation/BeeStation-Hornet/pull/5369

## Why It's Good For The Game

 

Pending.

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
The jetpack upgrade and mask thing were both reverted on purpose at some point for whatever reason but it was a pretty legit enough reason.

**Comment by PerishedFraud** [comment]
> The jetpack upgrade and mask thing were both reverted on purpose at some point for whatever reason but it was a pretty legit enough reason.

Jetpack: False. After **I** removed it initially, it was not reverted, in fact this is the PR that is reverting it. Because miners are actually going to space thanks to new shuttle commands and asteroids. My original reasons for removing it were that lavaland had no use for a jetpack.

Mask: While your argument can seem more pleasible here, I fail to see the reason someone would actually revert letting a mask allow you to eat. Curious, I investigated myself. The reversion was done by Ivanmixo and no reason was given. Interestingly Ivan replied to an earlier version of this PR and his argument for the mask was out of realism alone, and he was the one who reminded me to also remove the toggle.

**Comment by mcmeiler** [comment]
Yeah, I don't get why Ivan removed it to begin with, it just cucked miners trying to eat lavaland flora for health.

**Comment by PowerfulBacon** [comment]
> Jetpack: False. After I removed it initially (yes, the jetpack was always there originally), it was not reverted, in fact this is the PR that is reverting it. Because miners are actually going to space now, thanks to new shuttle commands and asteroids. My original reasons for removing it were that lavaland had no use for a jetpack. Space does.

It was purposely removed from the vendor because it was some CE upgrade or something

**Comment by PerishedFraud** [comment]
> > Jetpack: False. After I removed it initially (yes, the jetpack was always there originally), it was not reverted, in fact this is the PR that is reverting it. Because miners are actually going to space now, thanks to new shuttle commands and asteroids. My original reasons for removing it were that lavaland had no use for a jetpack. Space does.
> 
> It was purposely removed from the vendor because it was some CE upgrade or something

No. This PR by me removed it and no other PR afterwards ever mentioned it. 

[https://github.com/BeeStation/BeeStation-Hornet/commit/eb1f932148c5b3108c1c8be023d0490f88b57d9b#diff-320129d83a40d7bfff5d6b39d31502898b1f43aa03789ed2fc5c2630f960d1fc](url)

What you're thinking of is the CE starting with a jetpack upgrade (identical item) instead of simply having an inbuilt jetpack in his advanced hardsuit like some others. I don't know why it's like this either.

**Comment by BrumalLake** [comment]
the description change about melee is stupid pointless and useless since armor tags were merged

**Comment by PerishedFraud** [comment]
> the description change about melee is stupid pointless and useless since armor tags were merged

Fair.

**Comment by Mick1299** [comment]
would be nice to have the jetpack upgrade in the explorers vendor too

**Comment by OceanFish1** [comment]
> would be nice to have the jetpack upgrade in the explorers vendor too

actually why the fuck job that supposed to be on a planet with gravity had jetpack upgrade when the job that usually is somewhere in the space doesn't have one?

**Comment by PerishedFraud** [comment]
Beats me. There's no explorer conscription kits either, and explorers don't get P-KAs even though they fight in space. On the other hand explorer is a new job.

**Comment by PerishedFraud** [comment]
PR will likely be either separated into two or expanded upon. I want to see what you think about jetpacks specifically so I've made a poll thread. Please participate if you care.

https://forums.beestation13.com/t/jetpacks-for-exploration-mining-opinions-needed/14661

**Comment by Isy232** [comment]
> What you're thinking of is the CE starting with a jetpack upgrade (identical item) instead of simply having an inbuilt jetpack in his advanced hardsuit like some others. I don't know why it's like this either.

The CE jetpack by default gets thrusters. The spare jetpack upgrade exists to be given to an engineer who wants to use it for solars. Its not used 95% of rounds.

More thoughts in the forum thread to avoid double posting

**Comment by PerishedFraud** [comment]
Separating now while the more easily-visible poll does its thing.

**Pull request closed without merging**
