### PR TITLE
lowers synthflesh dehusk to 40u

### PR DESCRIPTION
**Pull request by BrumalLake**
## About The Pull Request
takes dehusk requirement from 100u down to 40u
someone is going to speak out about rezadone

untested by the way

## Why It's Good For The Game
i hate dehusking, it's way more efficient and easier to clone, no matter what stage the game is in
saw some cmo make 2 40 unit patches with a carton, left the other 20 units that was needed for dehusking, and threw it onto the table in cloning, smashing the carton, so the medics ended up transplanting the brain
100 is a shitty number cause with synthflesh farms you most of the time have 40 unit patches and 100 isn't divisible by that so you need 5x 20u patches or to set and rename the output to 20 units for one patch
getting synthflesh is also a pain when people won't order it, and even then you need to asks the chemists which are most of the time outside of their lab to put it into 2 40u patches and 1 20u patch which is really painful and instead just becomes the cloner fund
on top of dehusking you have to tend wounds since they'll have a ton of burn damage causing the husking and probably brute too since it was most likely caused by atmos
plus if you use 3 40u patches it should overdose them at 120u
and synthflesh is gone from the nanomed plus

## Changelog
:cl:
balance: dehusk threshold is now 40u
/:cl:

### CODE REVIEW

**Comment by Absolutely-Steph** [comment]
I may or may not have been said CMO, and i approve of this change.

**Comment by FriendlyContractor** [comment]
I would honestly prefer cloning removed as its killing the medical job rather than this, but hey its a good small change

**Comment by williamcll** [comment]
> I would honestly prefer cloning removed as its killing the medical job rather than this, but hey its a good small change

Medics are already too busy most of the time.

**Comment by Sinestia** [comment]
Synthflesh ODs at 125, not 120.

**Comment by BrumalLake** [comment]
> 
> 
> Synthflesh ODs at 125, not 120.

oh no, pr's gonna get closed now cause my entire rant is based on that one fallacy

**Comment by Sinestia** [comment]
> 
> 
> > Synthflesh ODs at 125, not 120.
> 
> oh no, pr's gonna get closed now cause my entire rant is based on that one fallacy

>fallacy

🤔 

as if that's not an important detail to why this could be a good change or not, lmao.

**Review by Archanial — CHANGES_REQUESTED** [review]
I'm fine with 60, 40 is just too low.

**Comment by BrumalLake** [comment]
> 
> 
> I'm fine with 60, 40 is just too low.

not budging, it gets outdone by tier 3 by far and i'm not making it anything that isn't divisible by 40

**Comment by Crossedfall** [comment]
> not budging, it gets outdone by tier 3 by far and i'm not making it anything that isn't divisible by 40

Not trying to be rude, but you don't really get a final say on that. 

> I'm fine with 60, 40 is just too low.

I think 60 or 80 is reasonable for this. I'm inclined to agree that lowering it to 40 is too much. Really comes off as a kneejerk change.

**Comment by BrumalLake** [comment]
none of these numbers make this easier to do than cloning

**Comment by Archanial** [comment]
🔑 then

**Comment by Absolutely-Steph** [comment]
bro its all easier than 100, just fucking take 60 damn it.
can we haggle it down to 50? since it comes in 100u containers.

**Comment by Crossedfall** [comment]
> can we haggle it down to 50? since it comes in 100u containers.

They made it clear that they weren't willing to do anything that isn't divisible by 40.

---

Given that you seem unwilling to work with us on this, I am inclined to 🔑 as well. If you change your mind on that I will gladly re-open this PR and revisit the issue.

That all being said, sticking with the 3x40u patches should be workable within the current limits, since as @Sinestia pointed out, that will not put the patient over the OD threshold.

**Pull request closed without merging**
