### PR TITLE
Moves input bar under the chat and removes 3px border

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

obraz

This moves the input to under the chat and removes 3px border from the left side of the screen

Ported:
https://github.com/Skyrat-SS13/Skyrat-tg/pull/1604
https://github.com/Skyrat-SS13/Skyrat-tg/pull/1366

## Why It's Good For The Game

2021 ready

## Changelog
:cl:
add: Chatbar is now under the chat.
add: Removed 3px screen border.
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
looks weird and uncomfy


I may hate soul but I hate this more

**Comment by Archanial** [comment]
> looks weird and uncomfy
> 
> I may hate soul but I hate this more

It's because you are used to bond's shit ui. It actually looks really good in the game and you'd get used to it pretty quickly.

**Comment by PowerfulBacon** [comment]
I really don't like this

**Comment by Archanial** [comment]
> I really don't like this

Why

**Comment by Archanial** [comment]
Some nicer screenshots
obraz
obraz
I looks really good in game, there is not reason we need super long input bar.
Time to move on.

**Comment by Chessus** [comment]
A shame this was even put to a vote and then the results were honoured. Good idea archanial.

**Pull request closed without merging**
