### PR TITLE
Unfucks cloning

### LINKED ISSUE #2577: Cloning is fucked. Reagent display 0/0.
Discovered on round 21966. Happened before too but waited for this round to test. Persisted during 2 rounds at time of writing, will report if it goes away.

Cloning is just fucked. The clone pod has 0/0 reagents. Rebuilding, upgrading, replacing or even using experimental cloner does not fix this.

It is completely unusable. Whatever caused this just basically disabled cloning.

Found on LRP. Perhaps MRP doesn't have this issue atm.

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request
cloning requires beakers again

## Why It's Good For The Game

me when someone changes sprites as well as 1500 lines of code
closes #2577

## Changelog
:cl:
fix: Cloning works again.
/:cl:

### CODE REVIEW

**Review by PerishedFraud — APPROVED** [review]
yes

**Review by PowerfulBacon — APPROVED** [review]
Tested?

**Comment by Archanial** [comment]
yesss

**Comment by Archanial** [comment]
obraz

**Pull request merged**
