### PR TITLE
Adds Clerical Cyborg

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
Adds the Clerical Cyborg to the game. Its primary purpose is to be a member of Cargo, and it also has the ability to act as the HoP.
It has the following modules:
Pen
Hand Labeler
Granted Stamp
Denied Stamp
Wrapping Paper (operating in a similar way to the engineering cyborg's iron fabricator)
Package Wrapping (operating in a similar way to the engineering cyborg's iron fabricator)
Clerical Grabbing Apparatus, which can hold the following: IDs, paper, PDAs, PDA cartridges, pens, Ian, small parcels, folders, holochips, cash, and origami.
Destination Tagger
Flash
Cargo Budget
Clerical Fabricator, which can produce the following: ID Cards, Pens, Paper, PDAs, Folders
Power Connector
Cargo Megaphone
When emagged, it gains the following:
Electrically Charged Arm
Chameleon Stamp
Additionally, when emagged, the Clerical Fabricator will produce Sharpened Paper Planes
When converted to be a Servant of Ratvar, it gains the following:
Kindle
Abscond
Sigil of Submission

image

## Why It's Good For The Game
With the changes to the Corporate lawset, in addition to it having a possibility of being a roundstart lawset, I thought that a supply borg would be very interesting, and help further the goals of maximizing profit. Additionally, if there is no HoP, the Captain or Acting Captain can assign this borg to do the HoP's job. One important thing to note is that **the borg cannot independently become the HoP, someone must give it an ID with ID console access for it to be able to modify IDs.**

## Changelog
:cl:
add: The Clerical Cyborg has been added to the game, working primarily in Cargo.
/:cl:

### CODE REVIEW

**Comment by KubeRoot** [comment]
I feel like it should have two grabbing apparatuses (apparati? apparatodes?) so it can simultaneously hold both the ID-console-access ID and whatever it's working on, be it an ID it's giving access to or some paperwork.

**Comment by Vexylius** [comment]
How does it look though?

**Comment by BrumalLake** [comment]
they didn't add any icons so i assume default cyborg

also cargo budget 🤯 make it unable to withdraw from it

**Comment by Ivniinvi** [comment]
It previously used the old Captain-borg sprite, but I created a new sprite for it.

**Comment by KubeRoot** [comment]
Here's the current sprite yoinked from icondiffbot for those interested:

image

**Comment by Ivniinvi** [comment]
Thanks for the bigger version

**Review by Archanial — CHANGES_REQUESTED** [review]
Cyborgs shouldn't have cargo budget cards available to them and also I am unsure if giving a cyborg (who's easily manipulated) access to HoP consoles is a good idea.

**Comment by PowerfulBacon** [comment]
Law 2 give me AA

**Comment by Archanial** [comment]
Also this would be administrative headache since heads are held to higher standards cyborgs are not.
I'm not saying you should scrap that idea as whole but cyborg hop doesn't work.

**Comment by mcmeiler** [comment]
> 
> 
> Law 2 give me AA

This

Also these sprites don't fit the current borg theme we've got going and it's kind of off-putting for me personally

**Comment by ghost** [comment]
This was pretty useless on Baystation12, which is where I assume you got the idea from, and its additional uses as a spare hand in cargo and pseudo-HoP do raise some questions.

**Comment by AlinaStarkova** [comment]
this is the most unbalanced borg ive ever witnessed. 

1. Has AA
2. Has to follow orders
3. Can give other people AA
4. when emagged gets sharp paper planes (ranged attack) AND an instant hardstun arm

"Borg, I order you to walk into the hops office with my ID, give me AA, and give my ID back and not tell anyone"

**Comment by Ivniinvi** [comment]
First off, it **cannot give other people access without the captain or hop giving it an id console card first**. Secondly, if they leave it on the default lawset the borg cannot grant access to AI Upload, AI Sat, Atmospherics, Toxins, or the Armory per silicon policy. I generally think that a captain or hop enabling it to be a hop without changing its laws to be a really bad idea. Secondly, it cannot throw the paper planes it creates, only generate them. Finally, its purpose is to act as supply. The HoP functionality is a backup, it cannot do it on its own. Also, spritewise I can't sprite to save my life, so if this one is a problem I'll probably end up stealing one of the five service borg sprites.

**Comment by AlinaStarkova** [comment]
> 
> 
> First off, it **cannot give other people access without the captain or hop giving it an id console card first**. Secondly, if they leave it on the default lawset the borg cannot grant access to AI Upload, AI Sat, Atmospherics, Toxins, or the Armory per silicon policy. I generally think that a captain or hop enabling it to be a hop without changing its laws to be a really bad idea. Secondly, it cannot throw the paper planes it creates, only generate them. Finally, its purpose is to act as supply. The HoP functionality is a backup, it cannot do it on its own. Also, spritewise I can't sprite to save my life, so if this one is a problem I'll probably end up stealing one of the five service borg sprites.

this assumes the borg needs to be *given* a card, it can be law'd to steal it, or emagged and told to steal it, either way this borg *is* objectively unbalanced, way more than any other borg type so far. borgs have AA, they shouldnt be capable of potentially giving it to others as well

**Comment by Fikou** [comment]
image

**Comment by BrumalLake** [comment]
needs an icon state for when it's disabled or dead
pretty sure it'll turn invisible or something

think the above comic is supposed to be a beetard or something

**Comment by Crossedfall** [comment]
Supply borg good. Bureaucrat borg bad.

I would much rather see a borg variation of the MULE which can load bulky items onto itself for transport. I *really* don't like the idea of a borg which: 

A.) Has the capacity to fully replace an important head
B.) Is so wildly unbalanced and powerful

**Review by Crossedfall — COMMENTED** [review]
Supply borg good. Bureaucrat borg bad.

I would much rather see a borg variation of the MULE which can load bulky items onto itself for transport. I *really* don't like the idea of a borg which: 

A.) Has the capacity to fully replace an important head
B.) Is so wildly unbalanced and powerful

🔑

**Comment by ike709** [comment]
🔑 

MULEBorg good, HoPBorg bad

**Pull request closed without merging**
