### PR TITLE
Ports species-specific greyscaled blood & damage_overlays

### PR DESCRIPTION
**Pull request by Tsar-Salat**
## About The Pull Request

PR title.

Converts most blood decals to greyscale. We datumize species blood color and applies it to the aforementioned blood decals

Additionally, converts some species with hardcoded non-blood "blood" to actually use blood. (IPCs)

Species blood colors are as such:
- humans | CC0000 red
- lizards | 009696 teal
- IPCs | dddeff light grey
- Ethereals | 7fff7f green
- Xenos | RGB 0, 255, 0 puke green

_**If anyone has any other color recommendations, post them with the hex**_

Ports:
- https://github.com/tgstation/tgstation/pull/61610
- https://github.com/shiptest-ss13/Shiptest/pull/1882

## Why It's Good For The Game

Not every species is hemoglobin-based red blood, or uses motoroil. Motoroil itself is more of a meme than actually making sense. Blood is a very dated system, especially with hardcoding like https://github.com/BeeStation/BeeStation-Hornet/pull/5627

Instead of snowflaking certain species to spread one reagent or another, we make all species spread *subtyped* blood. Theres a lot less shitcode

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Screenshot 2024-07-13 171814

</details>

## Changelog
:cl: rkz, thgvr, Fikou
add: Greyscales all blood decals.
add: Species now all have different blood colors, which will show in the footprints, blood trails, and damage overlays when they get hurt
add: Gave some species their own bloodtype 
add: new footstep sprites
/:cl:

### CODE REVIEW

**Comment by Rukofamicom** [comment]
I have only two requests:

#1 can you make Ethereal blood glow faintly in the dark
#2 can you make Ethereal blood match the color of the ethereal it came from

**Comment by Tsar-Salat** [comment]
> 1. can you make Ethereal blood glow faintly in the dark

Ok ruko, you fished your wish


> 2. can you make Ethereal blood match the color of the ethereal it came from

We talked about this in discord, and the mutcolors would just be too fucky

**Comment by Rukofamicom** [comment]
👍 

Will get to a proper review eventually™️

**Comment by h42-real** [comment]
Since psyphoza have space drugs as blood, do you think it would make sense to have their blood be the same color, #60a584?

**Comment by Tsar-Salat** [comment]
> Since psyphoza have space drugs as blood

This is nitpicking, but they don't have spacedrugs for blood. They have a reagent "Mushroom Hallucinogen", under the color E700E7.

Overall... Im kinda on the edge? Pink is I assume a meme reference to Noita or something, and I really don't think it would look good with a wet & dry state like the other bloods.

All in all, I am satisfied thus far with the species we are at.

**Review by Rukofamicom — APPROVED** [review]
Code looks sane, conflicts with a TM we currently have running and would like to keep running so I'm going to trust it with a full merge.

**Pull request merged**
