### PR TITLE
Maint airlocks

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Adds in airlocks into maints.

## Why It's Good For The Game

Currently, if 1 window or walls gets broken in maints, all of maints gets depressurised, leading to the station being depressurised. This adds in firelocks into maints to help prevent that.

## Changelog
:cl:
add: Firelocks into maints
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Ah fuck, I have changelog shit

**Comment by PowerfulBacon** [comment]
Ready for review

**Comment by PowerfulBacon** [comment]
nevermind, looks like there are some issues with directions

**Comment by PowerfulBacon** [comment]
Ok all of the airlock controllers have had their directions fucked which is annoying

**Comment by PowerfulBacon** [comment]
Fixed, now it is really read for review.

**Review by ike709 — APPROVED** [review]

**Comment by ike709** [comment]
MDB changes look fine.

**Pull request merged**
