### PR TITLE
Reworks CorgStation BRIG

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request 

Shapes CorgStation brig into a more comfy and evenly shapped structure.

## Why It's Good For The Game

Now that genpop its out mappers can focus on refining the layouts originally made to merge it

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

imagen
imagen
imagen
imagen
imagen

</details>

## Changelog
:cl:
add: KiloStation: General Station: A dog park with dogs. Genpop brig: prison frog, shower room, half a basketball court , arcade machines
tweak: General Station: replaces the hallway going north next to cargo with a maintenance hallway, moves the public garden above the courtroom, push the indent above medbay to move all the hallway one tile lower. Genpop brig: layout, removes the visitors centre from the empty room in the hallways below security to where the public garden used to be. Reduces the amount of entrances to medbay from the lobby from 4 to 2
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
Could you post a full screenshot of the brig area+medbay? i'd like to compare the before-after specially the medbay entrance lobby that went from 4 to 2, prison looks a little more comfy

**Comment by ClownMoff** [comment]
68747470733a2f2f616666656374656461726330372e626c6f622e636f72652e77696e646f77732e6e65742f6d6462322f696d616765732f3136323335363932372f32303533393832353537312f6d2f5f6d6170735f6d61705f66696c65735f436f72675374617469

**Review by MarkusLarsson421 — COMMENTED** [review]
Unsure if two warrant consoles are needed.
image 

Full black decal and red decal looks odd next to red decal without any full black decal.
image 

Wires are expensive, use the double knot trick.
image 

Like so.
image 

Prison area is creeping weirdly along the wall here, might as well just make it maintenance area. Minor nitpick though.
image 

Weird decal here pointing signaling... nothing? Also, weird wiring again.
image 

Wall inside a window. 
image 

Prisoner management interface should be nudged to prevent it from being viewable from the opposite side.
image 
image 


Disconnected wire.
image 

I like the plushies and smokes details.
image 

Workshop opening is 3-wide.
image 
image 
image 

Incorrect knot wires here.
image 

Wire leading into a wall.
image 

This space feels a bit barren. Potted plants can only do so much.
image

Pipe leading into a bed any nothing else.
image

Camera linked to the Medbay network?
image 
image 

Two very close cameras, a tad over kill for such as small area.
image 

Light switch inside wall and severe lack of other light switches.
image

Two lights right next to each other. Looks a bit odd.
image 

Red decals continuing from up above, might want to skip it continuation due to the basketball court and keep the floor plain or add something else.
image 

A few too many directional windows. 
image 

A little bit lack in posters.

Has no trash bins (/obj/structure/closet/crate/bin).

Has no botany corner.

Intercomm should be like the ones in old perma.
image 
image 

Lamp is blue, might've used a weird variant of it.
image 

Cute snek.
image 

No flooring.
image 

Three air alarms.
image 

Corner window here is a bit odd.
image 

Decals should continue along the windows.
image

**Comment by MarkusLarsson421** [comment]
Floating firelock and weird wiring.
image 

Disconnected waste pipe and wire.
image 

Missing floor tile.
image 
image 

Pixel edited sink, use nudge.
image 

Workshop area not inside the actual workshop.
image 

Floating camera.
image 

Workshop entrance is a tad off. I'd move the maintenance route along the drawn arrow and expand the prison slightly.
image 

Three wide doorway doesn't look or feel that good, I'd stick a pillar in the middle similar to Fland.
image 
image

**Review by MarkusLarsson421 — COMMENTED** [review]
Might be some repetition from previous reviewers or reviews.

As Flora on Discord mention you got a lattice under/over the grass here.
image 

Also, regarding your error you need to delete this line using any text editor.
image

No decals or fire locks under the door.
image 

I'd shift the entire room to line up with the doors to the court room and move the camera on the door onto a full wall.
image 

Plating, decals and piping under windows.
image

10 seats to sit but no tables or other furniture.
image 

Decal errors.
image

Disconnected wire and no firelock or decal.
image 

Lacking wood corner decals.
image 

Disconnected pipe and wire.
image 

Spaced tile.
image

A lot of overlapping wall mounts, AI hell.
image

Missing wooden corner decals.
image

Maybe expand the carpet a tile?
image 

Extreme lack of decals. 
image 

This room could and probably should be rotated clock-wise by 90 degrees.
image

One single decal and floating camera.
image 

Disconnected pipes and wiring.
image 

Same here.
image 

Wire into nothing.
image

Regular windows, they are not air tight.
image

**Pull request closed without merging**
