### PR TITLE
Bumps Auxmos from 1.1.2 to 2.2.1 and BYOND to 514.1589

### PR DESCRIPTION
**Pull request by Crossedfall**
## About The Pull Request

Bumps auxmos to 2.2.1 to support newer BYOND versions and to bring in a handful of improvements. 

Changes made per: https://github.com/BeeStation/auxmos/blob/master/docs/MIGRATING.md#11-to-20

Complete list of changes and release binaries are found here: https://github.com/BeeStation/auxmos/releases/tag/2.2.1

## Why It's Good For The Game

The main reason for the bump is to support newer BYOND versions since we've fallen pretty far behind. This'll allow us to take advantage of the latest improvements & features added into the engine. 

## Testing Photographs and Procedure

1. Compiled using 514.1583
2. Loaded up a test server running 514.1583
3. Confirmed there were no runtimes during init
4. Tested atmos by spawning toxins containers and releasing them
5. Tested fires by overloading an APC to ignite the plasma
6. Clean compiled using 514.1589
7. Loaded up a test server running 514.1589
8. Repeated steps 3-5

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
server: Bumps auxmos to 2.2.1
server: Bumps the maximum BYOND version to 514.1589
/:cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
Seems like the Linux binary needs some extra work. Converting to draft for now.

**Comment by ike709** [comment]
> Seems like the Linux binary needs some extra work. Converting to draft for now.

Presumably this is missing https://github.com/willox/auxtools/pull/61

**Review by ike709 — DISMISSED** [review]

**Comment by Archanial** [comment]
Consistently breaks atmos.

**Review by Archanial — APPROVED** [review]

**Review by itsmeow — APPROVED** [review]
Works fine now from my playtime with this TMd

**Pull request merged**
