### PR TITLE
Chemical factories: Medical usage edition

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

- Removes the pill press
- Removes the patch dispensor
- Bottle dispensor renamed to bottle filler and will now only fill open containers on interact
- Chemical synthesisers now use power
- Chemical synthesisers no longer require matter

## Why It's Good For The Game

Chemical factories were essentially soft-removed by the requirement for a huge amount of matter to be effective. After some recent discussion in general, and consolidating on some of my own experiences playing chemist, the main thing I dislike about chemistry is having to produce large amounts of a certain reagent as it is often time consuming and not fun. Chemical factories are perfect for producing chemicals which need to be created on-masse throughout a round, so why not encourage them to be used for that purpose.

I specifically remove the pill press, bottle dispensor and patch dispensor since I don't want people making factories that just pump out self-healing medicine in-front of medbay. I want these to be used by doctors, or chemists to pass on to other people, to refill medbots, or to keep sleepers full.

## Testing Photographs and Procedure

image

image

## Changelog
:cl:
balance: Chemical factories now use power instead of matter.
del: Removes pill presses and patch dispensors.
tweak: Bottle dispensors no longer produce glass bottles out of nowhere, they now require a bottle to fill.
fix: The plumbing RCD can now print bottle fillers.
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
While this is done, could the player collision of the pipes be removed so they can be walked over?

**Comment by PowerfulBacon** [comment]
They can be walked over, I put the pipes first and then set the synthesisers afterwards

**Comment by MarkusLarsson421** [comment]
> They can be walked over, I put the pipes first and then set the synthesisers afterwards

Has this always been the case? Could've sworn you couldn't.

**Comment by PowerfulBacon** [comment]
Presentation

**Comment by Rukofamicom** [comment]
Would you consider adding a way to link medbots directly to the filler?
 
 > Presentation. And also I don't know if output gates can dispense into containers, only syringes
 
 They can dispense into containers.

**Comment by EvilDragonfiend** [comment]
In favour of temporary(?) revert of bioscanner, it should be on hold.

Also, this PR will conflict with #https://github.com/BeeStation/BeeStation-Hornet/pull/10619

**Comment by PowerfulBacon** [comment]
It shouldn't conflict, the other PR is simply moving the plumbing stuff to its own locker rather than changing anything about it. This can work alongside the bioscanner and comes about as a result of feedback on the medbot changes, rather than the bioscanner; however not merge conflicting the bioscanner revert is critical

**Comment by ColonelOrion** [comment]
The evil has been defeated

**Comment by PowerfulBacon** [comment]
Despite git claiming that there are no changes from master to my branch, there are a ton of changes to the map. No clue why the diffs are so large.

**Comment by Nanimies** [comment]
please it's been three months when this first got opened, i just want my meth factory back

**Review by PestoVerde322 — COMMENTED** [review]
Good on the mapfront, but, is it really necessary to keep a void as a stark reminder of what it had? place a good ol' fulltile window!

**Comment by MarkusLarsson421** [comment]
I'd say remove all those things should be removed to allow the chemist to put in whatever they want.

**Pull request merged**
