### PR TITLE
Makes the spam filter a little more forgiving

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

The amount of messages to get warned for too quick messages upped to 10, automute to 15.
The timer resets after 3 seconds instead of 5.

## Why It's Good For The Game

It's a bit too harsh right now and people just can't seem to comprehend you can put more than one sentence into the say box at a time.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
tweak: made the spam filter a little more forgiving 
/:cl:

### CODE REVIEW

**Review by ike709 — APPROVED** [review]

**Comment by Crossedfall** [comment]
I think the new values are fine, but I'm going to TM just to be safe and so we don't end up with 30 PRs tweaking the values

**Comment by Rukofamicom** [comment]
> so we don't end up with 30 PRs tweaking the values

There was a discussion about this in discord last night and I'd like to propose an alternative before I potentially add to this problem:

> I think the new values are fine

I don't think the values are a problem necessarily, I think the issue lies with the the timer being reset on every message instead of being a rolling timer. 

This doesn't mute for 10 messages in 5 seconds, it mutes for 10 messages in 45 seconds and at the same time it's possible to spam 9 messages with 6 second delays between bursts and not get muted.

**Comment by ivanmixo** [comment]
What? No. The delay is currently 5 seconds, 3 with this PR. Just don't talk for 5 (or 3 with this PR) and your count resets.

**Comment by Rukofamicom** [comment]
Yes I know this PR changes it from 5 to 3 seconds, I was referring to old 5 second value because 5 seconds is fine, what is not fine is this:
> Just don't talk for 5 (or 3 with this PR) and your count resets.

**and that is the god damn problem and annoying as fuck for people who type fast and this also means the spam filter doesn't actually stop intentional spam either**

With your setup using new values since I seem to have confused you:
* Sometimes 10 messages in 30 seconds causes a mute
* At the same time sometimes 70 messages in 30 seconds won't cause a mute, if they're timed appropriately.

Your setup does not stop spammers *and* punishes normal people. **That is bad**.

~~Please consider using https://github.com/BeeStation/BeeStation-Hornet/pull/6937~~ over this @Crossedfall 
Actually that PR still isn't a rolling counter. It solves the issue of punishing normal folks while still allowing large scale spam with brief delays.

**Comment by ivanmixo** [comment]
The other pr doesnt solve that either for the record so, if anything its easier with the other pr, just pace your messages and you can consistently keep spamming.

**Comment by Rukofamicom** [comment]
Yes, I know, the other PR didn't do what I thought either, I had already editted my comment to acknowledge that well before you responded to it. 

A rolling timer also won't totally resolve it, but it does better protect against *actual* spam even if tuned to a speed that doesn't interfere with normal typing.

**Comment by Rukofamicom** [comment]
Here's my improvment to the timer: https://github.com/BeeStation/BeeStation-Hornet/pull/6942

Here's @MNarath1 : https://github.com/BeeStation/BeeStation-Hornet/pull/6937

**Comment by PowerfulBacon** [comment]
Closed in favour of #6937

**Pull request closed without merging**
