### PR TITLE
Ignore this.

### PR DESCRIPTION
**Pull request by Rukofamicom**

### CODE REVIEW

**Comment by Rukofamicom** [comment]
WRONG BRANCH. I wonder if there's a way I can disable it always defaulting to Bee.

**Comment by TeomanTheGreat** [comment]
We will never know what this means.

**Comment by itsmeow** [comment]
ROYALE STATION!!!

**Comment by Rukofamicom** [comment]
@TeomanTheGreat yeah, I've been working on making bacon's battle royal adminbus button into its own full game mode, the branch this was meant for is a fork dedicated to running battle royale

I'm gonna need to ping crossed to wipe this.

**Comment by Fronsis** [comment]
I do not know what Ruko is doing... and we might never fully know (unless you read the code) but i say.. LET HIM COOK!

**Pull request closed without merging**
