### PR TITLE
little pings for quick messages

### PR DESCRIPTION
**Pull request by CthulhuOnIce**
## About The Pull Request

When a small message comes up, for example a pda message or requests console alert, a little alert to catch your eye

## Why It's Good For The Game

Helps immersion for very small ingame messages

## Videos

https://gfycat.com/DapperSoreAtlanticblackgoby

https://gfycat.com/SlowInsistentAfricanclawedfrog

## Changelog
:cl:
add: Added small alert popups
/:cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
Not a fan personally. Adds to the visual clutter.

**Comment by ike709** [comment]
Gross.

**Comment by CthulhuOnIce** [comment]
I mean it's only half a second

**Comment by qwertyquerty** [comment]
I think a visual indicator that some machine is making noise would be a cool idea, but I do not like it in the form of text.

**Pull request closed without merging**
