### PR TITLE
Makes deaf people unable to be sound-stunned

### PR DESCRIPTION
**Pull request by covertcorvid**
## About The Pull Request
This makes sound-based stun effects not work on people who are deaf. They will still be knocked down and receive deafness ticks from the loud noise if applicable.

## Why It's Good For The Game
Blind people already can't be flashed. Deaf people can't hear the loud thing, so it only makes sense.

## Testing Photographs and Procedure

<details>
<summary>Testing Procedure</summary>

1. Become deaf
2. Activate some sonic powder
3. Don't be stunned

</details>

## Changelog
:cl:
balance: People can no longer be paralyzed by sonic effects while deaf
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — COMMENTED** [review]
Ear damage should still be applied while deaf.
I assume the balance changes to flashbangs that this will cause is intentional, since getting flashbanged will make you immune to flashbangs for a good amount of time afterwards. Perhaps with a high enough intensity it should still stun people that are deaf due to ears ringing and affect people who are entirely deaf differently.

**Comment by covertcorvid** [comment]
> Ear damage should still be applied while deaf. I assume the balance changes to flashbangs that this will cause is intentional, since getting flashbanged will make you immune to flashbangs for a good amount of time afterwards. Perhaps with a high enough intensity it should still stun people that are deaf due to ears ringing and affect people who are entirely deaf differently.

Ear damage is indeed still applied.

I'm open to changes that you all feel are appropriate. The original context for this was people getting stunlocked by being too close to some noisy machinery while it was operating, so for my own purposes I'd rather not have the protection be genetic-only.

At the moment, a flashbang's intensity is only 1, so the balance effect would essentially be the same even if higher intensities worked differently. We could raise the intensity of the flashbang, but would have to also change all the protection values for headsets.

Other potential reductions in the severity of the balance change that I can think of would be actually not applying the additional ear damage, or reducing a flashbang's deafen_pwr. Both would reduce the amount of time spent deaf after the bang.

Edit: naturally I can also just keep the change downstream, I was just looking through our end to see what might make sense to port back to you guys.

Edit 2: the immunity period from a single flashbang should be 15 ticks without changing values.

**Comment by AnCopper** [comment]
It's not loud sounds that incapacitate people, it's the concussion wave.

**Comment by SergeiKoralev** [comment]
> It's not loud sounds that incapacitate people, it's the concussion wave.

While concussive force does play a factor it's important to remember that it's also significantly aided by being extremely loud and extremely bright.

Edit: If you're utilizing enough concussive force to incapacitate someone but not kill them by shredding their internal organs with the shockwave you'd probably just want to apply confusion to them.

**Comment by ike709** [comment]
Might be worth keeping the knockdown but not paralyzing them if they're deaf.

**Comment by SergeiKoralev** [comment]
> Might be worth keeping the knockdown but not paralyzing them if they're deaf.

Probably similar to a flash, just due to blindness.

**Comment by covertcorvid** [comment]
> Might be worth keeping the knockdown but not paralyzing them if they're deaf.

This would work for NSV's purposes, I'll update when I get home

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
