### PR TITLE
Turtle_buff

### PR DESCRIPTION
**Pull request by francinum**
## Changelog
:cl:
balance: Frank has had their health returned, and their damage further nerfed along with a slowdown
/:cl:

### CODE REVIEW

**Comment by Vexylius** [comment]
You wanna create an absolute monster out of my boy...

**good**

**Comment by Crossedfall** [comment]
https://user-images.githubusercontent.com/26130695/129494957-d936c867-5f99-43ee-ac0c-b374713350a7.mp4

**Comment by KubeRoot** [comment]
I agree, nerfing damage sounds fine, but then why do you have to nerf health? Is it an issue that you can turn yourself into a very weak but tanky simplemob?

**Comment by PowerfulBacon** [comment]
you can still buff damage with that purple thing

**Review by Crossedfall — APPROVED** [review]
🐢

**Comment by BrumalLake** [comment]
fuck this turtle, had some dude kill me cause he was doing some sheer heart attack high roleplay and ordered his sentient frank to do it for whatever reason and i couldn't do shit about it being on a scooter
marked as ic issue
get this turtle out of here

**Pull request merged**
