### PR TITLE
AI Vox sound effects, alarms, a chime, etc.

### PR DESCRIPTION
**Pull request by TsunamiAnt**
## About The Pull Request
I was also gonna put TGs 250+ vox expansion in here but kinda lost track. The pr itself was done though so i figured i'd just PR it and do the others later.

## Why It's Good For The Game
I wanna go BLOOP and BEEP as ai, and the whole swhitenoise scensor thing sounds bad.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://youtu.be/4p8saPxf9k8

</details>

## Changelog
:cl:
tweak: Changed the vox guide around a bit to make sound effects better sorted
soundadd: added a new vox chime to enhance vox announcements
soundadd: added two new vox alarm sounds
/:cl:

### CODE REVIEW

**Comment by TsunamiAnt** [comment]
how do i make checks rerun again..? This should be okay now.

**Review by PestoVerde322 — APPROVED** [review]
More sounds good, approved

**Comment by MarkusLarsson421** [comment]
Best PR 2024.

**Comment by TsunamiAnt** [comment]
huh, i really thought people would find this annoying.

If it turns out to **be** annoying, we could turn down the amount of allowed words per vox message. Nobody ever hits 50 words, it'd be a 2 minute long sprawl.

15 would be more reasonable, since it's only intended for shortish announcements anyways.

**Comment by MarkusLarsson421** [comment]
What is annoying is having to find words which doesn't exist! Also, no one ever abuses it like this, leave it available who is able to effectively make use of it.

**Comment by ClownMoff** [comment]
These all sound incredibly annoying if you do them enough

10/10

**Comment by ColonelOrion** [comment]
Awesome pr

**Review by Rukofamicom — APPROVED** [review]

**Pull request merged**
