### PR TITLE
Ports the fixed version of TG felinid tailwagging

### PR DESCRIPTION
**Pull request by TsunamiAnt**
## About The Pull Request

Same as the last time, just not the butt-ugly thin version that was ported here before anyone cared to look at the fixed version.

port from https://github.com/tgstation/tgstation/pull/56750

## Why It's Good For The Game

Good looking things look good. Good things are good for the game.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Here is the old version we had(ew, someone cage that rat):

107166321-a4b6ae80-6983-11eb-80c6-f1d0ea05f9fa

Here is the fixed version(wow so nice, so dynamic, yes):

107305796-a484e480-6a51-11eb-85d0-432534a07d8f

Here's a screenshot from ingame(very nice wow, who is that? the model looks amazing!):

image

And a video cuz its requested:

https://github.com/BeeStation/BeeStation-Hornet/assets/153900881/78cd1f66-ea79-429c-a021-a11c5f6221a9

</details>

## Changelog
:cl: EikoBiko
tweak: tweaked the felinid tailwag sprite
/:cl:

### CODE REVIEW

**Comment by PestoVerde322** [comment]
Fine by me IMO, even if yeah needs video proof.

**Comment by TsunamiAnt** [comment]
> This needs a video of how it looks in game. Ngl I'm not a huge fan of it, it just whips way too fast and doesn't look great in the screenshot.

Video added

**Comment by PowerfulBacon** [comment]
Yea, not a huge fan of it. At the bare minimum though the issues with it clipping into the side of the player model needs to be resolved.

image

**Comment by TsunamiAnt** [comment]
> Yea, not a huge fan of it. At the bare minimum though the issues with it clipping into the side of the player model needs to be resolved.
> 
> image

what are you talking about, It's reaching around the side. That's part of why it's so much better than our current ~~twitching~~ wag. there is actual dimension to it.

**Comment by PowerfulBacon** [comment]
it doesn't look like its wrapping around the body in a 3rd dimension, it just looks like its clipping in a visually weird way. The tail doesn't seem long enough in its standard position to be wrapping around the sides in the way that it does

**Comment by TsunamiAnt** [comment]
Dunno what to tell ya, only the tip of it reaches past the elbow, It's quite obvious that this is intentional.

At the end of the day, I just did this cuz I saw people asking for it, I like how it looks, and because the one we previously ported and reverted was the broken thin version. Most of the complaints I've seen back then were that it was too thin and just having it a bit thicker would be perfect. This is that.

Current tail wag sprites are like the epitome of coderspriting, like a three year old wanted to learn animation levels of ugly. Anything at all is better than keeping them imo.

You can also see it in action on NSV, though their hair colors seem to not match up perfectly with the tails. Dunno why that happens over there but not here. I had quite the backlash when it was ported there, but at the end of the day everyone came out liking it after all.

**Comment by PowerfulBacon** [comment]
The sprite is growing on me, but the wrapping around the side just doesn't work. Especially considering that the tail clearly isn't long enough to wrap around the side from the back perspective.

**Review by Miliviu — CHANGES_REQUESTED** [review]
Add original author name in the CL!

**Comment by TsunamiAnt** [comment]
Woops, done!

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Side facing clipping needs to be removed, or the sprite needs to be improved to reflect its ability to go round the side of the humanoid mob.

**Comment by TsunamiAnt** [comment]
image

I'm sorry I just genuinely cannot see what you mean. This seems like such a hyper-specific hangup to have even if it were true.

Would it be okay to throw it at the community in some way and then ask via vote? Let's say a merge/testmerge or something? I really doubt(know for a fact) that anyone would have a problem with this.

**Comment by PowerfulBacon** [comment]
Number of boxes doesn't matter if it still looks wrong, when you are looking at from the side you still need to consider the z-axis. Fix the side sprite clipping forward and I'll consider it for merge.

**Review by PestoVerde322 — APPROVED** [review]

**Review by PowerfulBacon — APPROVED** [review]
This is fine now

**Pull request merged**
