### PR TITLE
Admins now see if the objective is currently completed in traitor panel

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

The text is green if it is currently completed.

## Why It's Good For The Game

QOL for admins

## Changelog
:cl:
admin: Admins can now easily see if the objective is currently completed in TP (objective's text will be green).
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
Image, please.

**Comment by Vexylius** [comment]
send pics

**Comment by Archanial** [comment]
Uncompleted objective:
obraz
Objective currently completed:
obraz

**Comment by Sinestia** [comment]
noice

**Review by qwertyquerty — APPROVED** [review]

**Pull request merged**
