### PR TITLE
[GOON] Mob properties

### PR DESCRIPTION
**Pull request by ike709**
CONTAINS CODE FROM GOONSTATION: https://github.com/goonstation/goonstation/pull/722 and some follow-up fixes.

Code authors:

1. Naksu/vuonojenmustaturska
2. pali6

Authors gave their consent on discord but I'll ask them to comment on this PR.

Ports mob properties from goon. Currently unused, but at some point I'll use them to clean up `Life()`.

### CODE REVIEW

**Comment by pali6** [comment]
Ye, this PR has my blessing.

**Comment by vuonojenmustaturska** [comment]
👍

**Comment by ZeWaka** [comment]
PR rubber stamped by the actual original contributors above, and by me I guess, at the request of the author

**Comment by vuonojenmustaturska** [comment]
if you want to break compatibility with tg, these were envisioned as a better version of traits and could easily be moved to whichever level traits are in tg code (atom?), then you could just make trait defines an alternative for simple property defines.

e: actually it wouldn't even break tg compatibility, you'd just have to #define the properties used in traits

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
