### PR TITLE
More Metacoins for BYOND Members

### PR DESCRIPTION
**Pull request by ro5490**
## About The Pull Request

Gives BYOND Members more metacoins per round, its that simple really

## Why It's Good For The Game

I've noticed the BYOND monthly goal not being met year after year, and I realised that there isnt much to motivate people to help support BYOND via membership, This should hopefully help with that. (We can also adjust this to include donators too maybe?)

## Testing Photographs and Procedure

Couldnt get metacoins to work on a generic dream-daemon without a database, and I'm not re-setting up my server enviroment to test this, but in theory it should work, hopefully...

## Changelog
:cl:
tweak: BYOND Members now gain extra metacoins at round-end
/:cl:

### CODE REVIEW

**Comment by williamcll** [comment]
Bruh Pay to Win smh

**Comment by Oscari-pog** [comment]
Make it 5 coins and its ok

**Comment by DatBoiTim** [comment]
Bruh Pay to Win smh

**Comment by Rukofamicom** [comment]
@LummoxJR thanks you for your attempts I'm sure. 
Doesn't seem like a bad idea to me, given the use of the coins is fairly limited anyhow.

**Comment by PowerfulBacon** [comment]
I dislike this idea, making the shop 10% cheaper for donos and byond members could be fine

**Comment by Archanial** [comment]
Also dislike it. Doesn't feel like a right approach to me.

**Pull request closed without merging**
