### PR TITLE
Adds a confirmation check for aheals

### PR DESCRIPTION
**Pull request by Tsar-Salat**
## About The Pull Request

This PR adds a confirmation check for ahealing by querying the admin who sent it.

converts a few admin topic inputs/alerts to tgui

I took a little from this guy https://github.com/tgstation/tgstation/pull/58419 for the last part

## Why It's Good For The Game

Simple check to prevent fuckups

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

</details>

## Changelog
:cl: celotajstg
admin: added a check to confirm adminheals
admin: tguified a few admin topic procs
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
I also considered forcing a input query "Are you sure you want to aheal? Y/N" but this seems simpler for effectively the same value.

**Comment by PowerfulBacon** [comment]
testing muscle memory destroyed

**Comment by Miliviu** [comment]
Add testing evidence pls

**Review by PowerfulBacon — APPROVED** [review]

**Review by EvilDragonfiend — APPROVED** [review]
Hmm, my debug muscle memory will hate this, but preventing admin mistake is important

**Pull request merged**
