### PR TITLE
Port from Citadel Station for the Ore Redemption machine and vendor icons.

### PR DESCRIPTION
**Pull request by PestoVerde322**
## About The Pull Request

This PR Port the sprites from the Citadel Station's PR (Credits to Citadel-Station-13/Citadel-Station-13#9678), Which finally harmonizes the Ore Redemption machine and Vending machine sprites with the rest of the ore machines and the overall feel of the station.

Mining oreredemptionmachinevarab

_Original Ore Redemption Machine currently in Citadel_ : https://user-images.githubusercontent.com/75247747/139541325-f0e257fa-57b0-4e7a-beb2-20b61dde61fd.gif

## Why It's Good For The Game

As mentioned before, harmonizes the sprites related to the Ore Redemption machine and ending machine sprites with the rest.

## Changelog
:cl:
imageadd:  harmonizes the sprites related to the Ore Redemption machine and ending machine sprites with the rest.
/:cl:

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
Thanks, I hate this. For some reason it looks like covered in soap.

**Comment by PestoVerde322** [comment]
> 
> 
> Thanks, I hate this. For some reason it looks like covered in soap.

Sureley better than the 45° vending machine and the devsprite for the ORM :V

**Comment by ghost** [comment]
> 
> 
> > Thanks, I hate this. For some reason it looks like covered in soap.
> 
> Sureley better than the 45° vending machine and the devsprite for the ORM :V

it is better

**Comment by francinum** [comment]
It's better, but not all that much better, ORM has a massive fucking forehead, the vendor looks fine.

**Comment by ToasterBan** [comment]
I don't see a point in making only a certain group of machines use a specific artstyle if we don't even have an art style of our own, closest thing to an artstyle we could have gotten was azlons sprites but he left bee so we don't really have a general artistic direction to go towards

**Comment by PestoVerde322** [comment]
Aright, first update on the Ore redemption machines because indeed, they look bland more than being close to the original sprites.

oreredemptionmachinevarab

while still faithful to the port, this edit makes it so that it actually looks less boring and stick out better to the eyes.

> 
> 
> It's better, but not all that much better, ORM has a massive fucking forehead, the vendor looks fine.

soapredemptionmachine

_NOTE: not in the file._

> 
> 
> I don't see a point in making only a certain group of machines use a specific artstyle if we don't even have an art style of our own, closest thing to an artstyle we could have gotten was azlons sprites but he left bee so we don't really have a general artistic direction to go towards

It's still better than this:

ugly

And hey, slowly but steady old heavy-border, 45° sprites will get replaced, so like this sprites in a distant future.

**Review by Archanial — APPROVED** [review]

**Comment by ike709** [comment]
Jesus these are awful why did you merge these?

**Pull request merged**
