### PR TITLE
Bullet primer x screwdriver

### PR DESCRIPTION
**Pull request by utilbird**
## About The Pull Request

Hitting bullets with a screwdriver gives a chance to fire it in the direction you're currently facing! Albeit extremely inaccurately 

However, there's a 25% chance your hand will slip and ends up firing the cartridge into you (don't ask how), it also hurts your hand ;-;

## Why It's Good For The Game

I think it's funny

## Changelog
:cl:
add: Adds the ability to (inaccurately) shoot projectiles by using a screwdriver on bullet casings
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
how do you aim it?

**Comment by utilbird** [comment]
you pray

**Comment by theboy6545** [comment]
> 
> 
> you pray

admemes plz make boolet hit vuhlid
All jokes aside, good PR

**Comment by PowerfulBacon** [comment]
what about spent bullet shells? Are they a different type of object or do they still damage

**Comment by utilbird** [comment]
@PowerfulBacon they don't work

**Comment by ToasterBan** [comment]
but like does it shoot the direction your facing?

**Comment by utilbird** [comment]
It does

**Comment by Effemu** [comment]
does it work with tech shells?

**Comment by utilbird** [comment]
It works with every non-caseless ammo type

**Comment by utilbird** [comment]
🚀

**Comment by AtlasRules** [comment]
hmm yes, 50 BMG blowback rifle time

**Pull request merged**
