### PR TITLE
Adds a confirmation for using OOC chat mid-round if you're able to

### PR DESCRIPTION
**Pull request by CydiaLamiales**
## About The Pull Request
Adds a confirmation for using OOC chat mid-round if you're able to

## Why It's Good For The Game
Less admin slip ups and accidental icky ockys.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image

image

Normal users still can't send OOC messages.

</details>

## Changelog
:cl:
add: Added a confirmation for sending OOC messages mid-round if the user is able
/:cl:

### CODE REVIEW

**Comment by CydiaLamiales** [comment]
Yes I am making this after my slip up today. Just wanna make sure it's harder to do so.

**Review by Crossedfall — APPROVED** [review]
Good change

**Comment by EvilDragonfiend** [comment]
Please relocate the warning to before even writing. Even players sometimes try to chat even if they know they can't ooc

**Comment by EvilDragonfiend** [comment]
actually, nevermind. I found it's difficult to fix it actually.

**Review by Penwin0 — APPROVED** [review]

**Pull request merged**
