### PR TITLE
Reverts TG instruments

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

TG instruments are better and more advanced, however are extremely poorly optimised and cause performance issues when played even in relatively small crowds, using the same amount of CPU as other intense (and actually useful) systems like lighting and turf changing.
The main reasons for the lag where:
 - A subsystem with a delay of 0.5 and an extremely high priority
 - Constantly calling SEND_SOUND to hearers every single time the subsystem ticked. This would result in SEND_SOUND being called thousands of times a second when a song was being played.

The code would require a pretty large refactor to get an optimised version with feature parity, and it isn't worth the effort for the relatively little gain the new instruments bring.

## Why It's Good For The Game

The new songs are very laggy.

## Testing Photographs and Procedure
tested in game on the structure piano and one of the musical things in the bar with a song from the wiki.

## Changelog
:cl:
del: Reverts advanced instruments due to performance issues.
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Needs a TM to make sure this doesn't break any of the other instruments.

**Comment by Archanial** [comment]
I understand it was ported from tg.
Didn't they make any optimizations?

**Comment by PowerfulBacon** [comment]
> I understand it was ported from tg. Didn't they make any optimizations?

Just checked and no, they have the same implementation of the proc that resulted in the server being lagged (Subsystem tick delay 0.5 -> song/process -> process_decay -> SEND_SOUND to all mobs in range)

**Comment by ike709** [comment]
https://github.com/tgstation/tgstation/pull/59284

**Pull request closed without merging**
