### PR TITLE
Increase monkey cube cost in biogenerator.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Increases monkey cube cost in biogenerator the the same amount as strange seeds.

Part one of balancing the monkey cube economy, monkey spam, and coming soon even xenobiology.

Part of xenobiology self-sufficiency rework.
https://github.com/BeeStation/BeeStation-Hornet/pull/3831
https://github.com/BeeStation/BeeStation-Hornet/pull/3826

## Why It's Good For The Game

Botany can produce hundreds of strange seeds once they get basic upgrades for their biogenerator, which is fine. Previously, one strange seed had the cost of 20 monkey cubes. This lead to obscene monkey spam and devaluation of the monkey cube economy without any upgrades needed.

Now botany can still spam hundreds of monkey cubes, but they will have to spend the same effort as for strange seeds - which is really not much.

## Changelog
:cl:
balance: Monkey cubes in biogenerator now cost as much as strange seeds.
/:cl:

### CODE REVIEW

**Comment by RDS88-beeman** [comment]
first of all to get it out of the way
>>>>>>>>>>>monkey cube economy

second of all
there's already an in game mechanism to stop monkey spam
there's a cap on how many monkeys can exist at one time
it's 100
if you hate monkey spam
just drop the cap to 75, or even 50

**Comment by ItsTisme** [comment]
Monkey cubes exist to supply the chef with meat. Making the price this high makes it alot more difficult to give basic amount of meat supply to kitchen. Like was already said if you want to curb monkey spam lower the max amount of monkeys.

**Comment by ghost** [comment]
@Autisem

Botany can grow meat wheat, which serves the same purpose as meat.

**Comment by ItsTisme** [comment]
> @Autisem
> 
> Botany can grow meat wheat, which serves the same purpose as meat.

Its more effort, and there is little reason for "the monkey economie" to be like this. THis only makes a huge inconvenience for the few times genetics or xenobio needs monkey cubes. I dont see the point that its problomatic other then monkey spam(which this prop wont even prevent it from happing)

**Comment by ghost** [comment]
It's almost as if botany will have more on their plate than just sitting on their butts and growing insta-kill plants.

**Comment by ItsTisme** [comment]
> It's almost as if botany will have more on their plate than just sitting on their butts and growing insta-kill plants.

If you see it this black and white, then adding this only adds "grow 3 water melons" to your previous vision of hydro. If you even seen a botanist get strange seeds they buy them by the 50. Again like in the other PR this doesnt change anything other then making it more inconvenient.

**Comment by ghost** [comment]
@Autisem

I'm not sure you even read your own posts, you explained the change in your own post and still don't get it.

**Comment by pickleinjar** [comment]
just let botany be botany

**Comment by leestriter** [comment]
I have never seen a botanist make a monkey cube for the chef, and I see monkey spam all the time. I support this.

**Comment by sircope** [comment]
> I have never seen a botanist make a monkey cube for the chef, and I see monkey spam all the time. I support this.

this change will just make it more unlikely lmao, 5k roundstart for a single cube

**Comment by leestriter** [comment]
Why make xeno need monkeys from botany then make sure botany doesn't have monkeys? Now that I understand the purpose of this pr I have changed my mind.

**Comment by USB3pt0** [comment]
This just dicks on the chef.  I've made monkey cubes for him before since it's more efficient to let him make and butcher what he needs unless he's specifically asked for prosciutto wheat. 

If you really need to nerf it bump it to 500 or 1000 but it's wholly unnecessary to begin with.  As soon as better parts come in xenobio wouldn't bother botany for their biogen cubes anyway.

**Comment by utilbird** [comment]
Not sure how I feel about this

**Comment by utilbird** [comment]
Keyed by Francium and I.

If you really want to rework xenobio, you'll want to combine a lot of the changes in a single PR, as they do nothing besides cause inconveniences by themselves.

**Pull request closed without merging**
