### PR TITLE
Dropper QoL

### PR DESCRIPTION
**Pull request by JixS4v**
## About The Pull Request

Couple of dropper-related QoL fixes. Makes the dropper only have three possible transfer amounts (1u, 2u, 5u) and makes the dropper able to be stored in the botany belt.

## Why It's Good For The Game

It's tedious to switch between 1u and 5u transfer in the dropper, furthermore the intermediate transfer amounts are barely used (EDIT: botany needs 2u) and can be replaced by just using the dropper several times.

On the botany belt side, botanists also use droppers and being able to put them in the botany belt is nice.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image

https://github.com/BeeStation/BeeStation-Hornet/assets/61665800/c2593300-9c3a-4360-ae6d-a88992ba57be

</details>

## Changelog
:cl:
tweak: botany belts are now able to hold droppers
tweak: droppers can now only transfer 1u 2u, or 5u
/:cl:

### CODE REVIEW

**Comment by WrillWasTaken** [comment]
What kind of botanist uses droppers? Bottles can do that job much better- the fertilizer bottles from the vendor can all transfer in 1/2/3/4/5u doses.

Also, 2u doses are very important to botany, you should not remove that functionality if you intend on botanists using them.

**Comment by JixS4v** [comment]
> What kind of botanist uses droppers? Bottles can do that job much better- the fertilizer bottles from the vendor can all transfer in 1/2/3/4/5u doses.
> 
> Also, 2u doses are very important to botany, you should not remove that functionality if you intend on botanists using them.

dunno, was suggested on the forums so I guess some botanists do, and you can always just do 1u twice

**Comment by JixS4v** [comment]
> 1u twice isn't the same as 2u in botany

ah, i'll amend it then, is there a need for 3u too? It's just 'cause it's annoying to have to go through all of them if you're doing stuff like viro

**Comment by BriggsIDP** [comment]
> > 1u twice isn't the same as 2u in botany
> 
> ah, i'll amend it then, is there a need for 3u too? It's just 'cause it's annoying to have to go through all of them if you're doing stuff like viro
I don't believe so. only 1u, 2u, 5u, and 100u is really need

**Comment by JixS4v** [comment]
> > > 1u twice isn't the same as 2u in botany
> > 
> > 
> > ah, i'll amend it then, is there a need for 3u too? It's just 'cause it's annoying to have to go through all of them if you're doing stuff like viro
> 
> I don't believe so. only 1u, 2u, 5u, and 100u is really need

alright thanks for the input!

**Comment by WrillWasTaken** [comment]
> > > 1u twice isn't the same as 2u in botany
> > 
> > 
> > ah, i'll amend it then, is there a need for 3u too? It's just 'cause it's annoying to have to go through all of them if you're doing stuff like viro
> 
> I don't believe so. only 1u, 2u, 5u, and 100u is really need

50u too.

**Review by Penwin0 — APPROVED** [review]
Changing the dropper settings is a bit strange no? I can see them having legitimate use cases

**Comment by Nosnek199** [comment]
Dont remove any of the transfer amounts, but make the dropper start on 1u.

**Comment by JixS4v** [comment]
> Changing the dropper settings is a bit strange no? I can see them having legitimate use cases

I'd say there is, but there's a point where you can just use multiple of one as opposed to having to go through all the possible settings to find the one you want. It's a bit of a pet peeve of mine, especially when playing something like viro.

**Comment by JixS4v** [comment]
PR has been updated with evidence.

**Review by EvilDragonfiend — APPROVED** [review]

**Pull request merged**
