### PR TITLE
[Port] Non temp workaround for admins matching stickybans because of a byond bug.

### PR DESCRIPTION
**Pull request by Crossedfall**
From https://github.com/tgstation/tgstation/pull/46462

Workaround for the byond bug with stickybans causing the admin whitelist code to not get called.

How does it work? when an admin is connecting, just before byond asks the hub about the current stickybans, we remove all of the stickybans from byond's database. later, when either 5 seconds have passed, or the admin's client/New is called, we restore the stickybans we deleted earlier.

### CODE REVIEW

**Review by qwertyquerty — COMMENTED** [review]
Seems like this could be a bit ehhh, because if anything goes wrong between removing and re-adding the sticky bans, boom no one is sticky banned

**Comment by Crossedfall** [comment]
> 
> 
> Seems like this could be a bit ehhh, because if anything goes wrong between removing and re-adding the sticky bans, boom no one is sticky banned

It is the only way to let admins who are ghost sticky banned into the server. We _hope_ to have a way to better understand the bug with the next version, but this is all we got for now.

**Comment by PowerfulBacon** [comment]
Wait, so if you join within 5 seconds of an admin or something goes wrong and server crashes within 5 seconds of an admin joining all sticky bans are lost?

**Comment by Crossedfall** [comment]
> 
> 
> Wait, so if you join within 5 seconds of an admin or something goes wrong and server crashes within 5 seconds of an admin joining all sticky bans are lost?

No. The bans are stored in the database. This clears and re-applies what amounts to a cache of the sticky bans with the admin forced into a whitelist.

**Review by PowerfulBacon — DISMISSED** [review]

**Review by PowerfulBacon — DISMISSED** [review]

**Comment by PowerfulBacon** [comment]
oh it still conflicts

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
