### PR TITLE
Cleans up numerous duplicate objects on multiple maps

### PR DESCRIPTION
**Pull request by Tyranicranger4**
## About The Pull Request
Does what it says in the title. Every map has countless duplicate objects, this removes ***most*** of them.

## Why It's Good For The Game
Fixing unintended mapping errors is good.

## Testing Photographs and Procedure

Due to the nature of what's being changed here it's nearly impossible for me to provide useful testing evidence, apologies.

## Changelog
:cl:
del: Removes various duplicate objects on ALL maps.
/:cl:

### CODE REVIEW

**Comment by Tyranicranger4** [comment]
Guh

**Comment by Tyranicranger4** [comment]
Fuck it, just going to redo this.

**Comment by Fronsis** [comment]
What are some examples of duplicated objects?

**Comment by Tyranicranger4** [comment]
> What are some examples of duplicated objects?

Delta station morgue maintenance has multiple doors and cables, Pubby has 2 stacked APCs in medical, an absolute fuck ton of duplicate wiring and disposals pipes on every map.

**Review by PestoVerde322 — COMMENTED** [review]
There's still duplicate Content in Box and Delta2, also nothing for Kilo?

**Comment by Tyranicranger4** [comment]
> also nothing for Kilo?


Like I remember Kilo exists lol

**Comment by Tyranicranger4** [comment]
Remade this under #7845 since I had removed some grilles here that I shouldn't have. Yes I know I could have reverted the commits, I forgot about that until now 😔

**Pull request closed without merging**
