### PR TITLE
Ports the Clarke Mecha from TG

### PR DESCRIPTION
**Pull request by Tsar-Salat**
## About The Pull Request

Ports the Clarke mech from tg.

The Clarke is a replacement of the ripley subtype, Firefighter APLU. 
Adds:
- Refactored wreckage salvaging. A lot less ugly, you can salvage more mechs now.
- The Clarke. Stormproof. Fireproof. Lavaproof. Built-in ore storage. Pretty quick but shit armor.
- PKA mecha equipment. Just the regular kinetic gun but for mechs. Better recharge and damage than the base pka, because its a mech weapon.
- Cool new toy sprites for mechs
- New job figurines.
- New collectable element, for collectable figurines and hats and the like.

Deletes:
- Firefighter mech and wreckage. Its pretty garbage resprite of the Ripley, which already has a subtype. It felt like it was trying to be a cargoloader, engineering rig, and mining tool all at once. All three of these it wasnt good at, as its slower than the ripley, more boring than a gygax, and no miner in their right mind would use this slow piece of shit.

Ports:
- https://github.com/tgstation/tgstation/pull/45904
- https://github.com/tgstation/tgstation/pull/49563
- https://github.com/tgstation/tgstation/pull/50129
- https://github.com/tgstation/tgstation/pull/50138
- https://github.com/tgstation/tgstation/pull/55463
- https://github.com/tgstation/tgstation/pull/57964
- https://github.com/tgstation/tgstation/pull/60384
- https://github.com/tgstation/tgstation/pull/63809 (Im keeping the diagnostic huds on Clarke's, though. The name means FOR engineers AND miners right? Like the DS character?)

Toys port:
- https://github.com/tgstation/tgstation/pull/59754

## Why It's Good For The Game

The Clarke is a replacement of the ripley subtype, Firefighter APLU. It is intended to fulfill a niche in mining specifically that has, in the past, made it so mining mechs really arent a thing or "the meta". When miners think of mechs, they dont think of them nearly as variable or flexible enough for their needs.

In comes the new mech, the Clarke. It, like regular miner gameplay, is about mobility and versatility rather than pure raw defense. Instead of tanking hits like a durand and being slow as shit, we want to be quick and not get hit in the first place.

Considering the titular character the Clarke is named after (or I think thats why TG named it that atleast), I want both usecases for Engineers and Miners to be considered. As the Clarke is replacing the only stationside fireproof mech that exists, we want it to atleast retain some use for them rather than just getting a ripley. So I broke from TG a bit and included a diagnostic HUD somewhat like the Odysseus gets being a medical exosuit.

Footnotes:
- The new mech weapon is a PKA for mechs, trying to add a little bit more blob and mining gameplay. I know it is also a favorite for a lot of miners against megafauna.
- Clarke is lower on the techweb than the other mechs to be more similiar to where the firefighter is, and give it a fighting chance to actually be received by miners before they are all gamer-geared out.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Clarke use

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/85bc263f-988b-4090-ac48-c7f3f657d761

Look at my cool collection

Screenshot 2024-05-21 003234

</details>

## Changelog
:cl: rkz, haukeschuemann, Fikou, RealestEstate/ValkyrieSkies, zxaber, MLGTASTICa, InvalidArguement3, 
add: clarke mecha. An agile mech that's lavaproof and comes with a built in ore-storage system, but is only above the odysseus in armor rating.
add: PKA equipment for mechs
add: new mecha & figurine toys and sprites
del: Firefighter ripley subtype.
tweak: Mech Firefighter armor moved to the Ripley MKII, Fireproof ability moved to Clarke.
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
fuk this was meant to be my local. Guess Im making the pr here now

😄

**Comment by Tsar-Salat** [comment]
Hm, I need to ensure the movespeed is correct lmao

**Comment by Fronsis** [comment]
> Hm, I need to ensure the movespeed is correct lmao
Yeah, the movement speed and the resistanece were the only two interesting things of the fire-extinguisher mecha, from the video the speed on the new one seems nice
> its slower than the ripley
So true, that thing was SO slow in pressurized areas

But yeah, you're right tbh. the only times i've seen the firefighter mecha ''shine'' were due to their speed (which became irrelevant tbh since why would you use a firefighter in lavaland if you have far better mechas, and using it on station was dumb because thanks to the pressurized station slowdown you would never reach an area that's on fire or spaced unless it happened in front of you) and their ability to withstand high temperatures like, for example, a plasmaflood however... they were pretty useless against dealing with the plasmaflood itself since their only tool was a super fast fire extinguisher so if the damage was done it was just a glorified atmos suit.

In another ideal world they would have tools to be able to stabilize an area temperature better than doing it with the default tools(RCD, Holofans, a heater feature, remote access to alarms, something like that) but since that won't happen i embrace the new mecha, it will see far more use than the poor green boi. 

I remember one of the few times i used one was in a BR where someone plasmaflooded the entire station and i won because i was moving extremely fast and just stood in the middle of the plasma while the rest died lol and that was months ago so yeah.. RIP, thanks for the fortnite win, rest easy now.

**Comment by Tsar-Salat** [comment]
> I like this change, but would this delete the old Firefighter toy?

Look at my second image.

**Comment by githubuser4141** [comment]
> > Hm, I need to ensure the movespeed is correct lmao
> > Yeah, the movement speed and the resistanece were the only two interesting things of the fire-extinguisher mecha, from the video the speed on the new one seems nice
> > its slower than the ripley
> > So true, that thing was SO slow in pressurized areas
> 
> But yeah, you're right tbh. the only times i've seen the firefighter mecha ''shine'' were due to their speed (which became irrelevant tbh since why would you use a firefighter in lavaland if you have far better mechas, and using it on station was dumb because thanks to the pressurized station slowdown you would never reach an area that's on fire or spaced unless it happened in front of you) and their ability to withstand high temperatures like, for example, a plasmaflood however... they were pretty useless against dealing with the plasmaflood itself since their only tool was a super fast fire extinguisher so if the damage was done it was just a glorified atmos suit.
> 
> In another ideal world they would have tools to be able to stabilize an area temperature better than doing it with the default tools(RCD, Holofans, a heater feature, remote access to alarms, something like that) but since that won't happen i embrace the new mecha, it will see far more use than the poor green boi.
> 
> I remember one of the few times i used one was in a BR where someone plasmaflooded the entire station and i won because i was moving extremely fast and just stood in the middle of the plasma while the rest died lol and that was months ago so yeah.. RIP, thanks for the fortnite win, rest easy now.
> 
> Good reference name tbh

The port on TG copies over the extra integrity and armor the firefighter has, but not the lavaproofing btw

This isn't super correct, the FF is better then clarke as it's better armoured and only a bit slower then Clarke on lavaland which makes it the most _stress free_ mining mech. Clarke is faster, but less armor means you need to be constantly on the ball because once integrity on a working mech sinks below 50% you are at risk for random roll of the dice malfunctions which can be debillating, FF with it's better armor *and* fireproofing is mostly immune to this. FF is also able to strafe, which helps avoid danger and attacks better then the clarke imho.

**Comment by Tsar-Salat** [comment]
Are you going to merge conflict with every mapping pr?

Oh, of course you are

**Review by Rukofamicom — APPROVED** [review]

**Comment by Tsar-Salat** [comment]
> The port on TG copies over the extra integrity and armor the firefighter has, but not the lavaproofing btw

I walked through the lava fine in the video, wdym?

**Pull request merged**
