### PR TITLE
Change brig timer to use real time instead of server time

### LINKED ISSUE #6107: Brig timer should run on a separate physics clock so it's always in real time.
High time dilation is standard on BeeStation, so a 15 minute brig time ends up being more like a 20-30 minute timer.

### PR DESCRIPTION
**Pull request by Jeff-3**
## About The Pull Request
Closes #6107 Changes brig timer so that the time entered is counted in real world minutes. This effectively makes it ignore time dilation, so server lag will no longer extend your time in the brig.

## Why It's Good For The Game
This pr is arguably beneficial, but I just write the code, I'll let the maintainers decide on whether or not it's good for the game. Best case scenario it has no effect or cuts down on some annoyance, worst case an antag is let out before their mess has been cleaned up.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
refactor: Brig timers are more accurate and no longer lengthened by lag
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Begging you to stop putting issue numbers in brackets so github will actually autoclose the issue when the PR is merged. Just do `Closes #6107`

**Review by ike709 — CHANGES_REQUESTED** [review]
Use `REALTIMEOFDAY` instead of `world.timeofday` so midnight rollover is accounted for.

**Comment by Jeff-3** [comment]
k

**Review by ike709 — CHANGES_REQUESTED** [review]
`REALTIMEOFDAY` is a macro, you don't need to access anything to be able to use it.

`world.time` -> `REALTIMEOFDAY`

**Comment by Jeff-3** [comment]
hamster stole my keyboard ignore that

**Review by ike709 — APPROVED** [review]

**Comment by FriendlyContractor** [comment]
While i agree that having your sentence take 50% longer because of dilation is annnoying this effectively means sentence is less severe on high time dilation as you lose smaller chunk of your round time being brigged. If this change is to be implemented shift time should be made unaffected by time dillation(crew transfer, shuttle transit time etc) to make game consistent otherwise this change is gonna feel wrong

**Comment by FriendlyContractor** [comment]
To further clarify what i mean - currently brig sentence means you are being taken out of the round and prevented from doing evil for a certain percent of the round time. For example if you get brigged for 20 minutes you loose about 20% of the round and can do this less actions(remember time dilation dictates how many actions you can perform in a real time period). With the proposed changes we find ourselves in a weird situation when if time dillation is high you lose smaller percentage of the round and therefore less "actions" which means sentence is "less effective"

**Comment by Jeff-3** [comment]
> To further clarify what i mean - currently brig sentence means you are being taken out of the round and prevented from doing evil for a certain percent of the round time. For example if you get brigged for 20 minutes you loose about 20% of the round and can do this less actions(remember time dilation dictates how many actions you can perform in a real time period). With the proposed changes we find ourselves in a weird situation when if time dillation is high you lose smaller percentage of the round and therefore less "actions" which means sentence is "less effective"

Being realistic, this will mostly affect the clown

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
