### PR TITLE
Floor resprite - Desouling

### PR DESCRIPTION
**Pull request by DrDuckedGoose**
## About The Pull Request

Resprites most of the commonly used floors, covering catwalks too. Updates decals respectively.
Pallet swaps hazard-stripes and all other common indicator-yellows to a more saturated / warmer alternative.

Apparently I forked this from the xenoarch fixes branch, so there's just a bunch on nonsense in the branch history from that, I guess.

## Why It's Good For The Game

Current floors have subtle noise, which is quite distracting / annoying. Removing this reduces noticeable mental strain.
New floors absorb color better, emphasizing cold & warm rooms.

## Testing Photographs and Procedure
<summary>Screenshots&Videos</summary>

<details>
Old

image

New

image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image

</details>

## Changelog
:cl:
tweak: Resprite floor.dm
tweak: Resprite decals.dm - turf variant
tweak: Changes hazard color in- disposal.dmi, shutters.dmi, catwalk.dmi
add: Add mapping-option tiles- Cafeteria-Dark, Cafeteria-Red, DarkBlueFull, SmartChecker
tweak: Change mapping instances of bar floor with red decals to Cafeteria-Red - BoxStation & MetaStation
tweak: Change regular tiles with decals to light-ish tiles with decals where necessary - MetaStation
/:cl:

### CODE REVIEW

**Comment by Tyranicranger4** [comment]
I don't know how to feel about this. It looks good, but it *feels* wrong.

**Comment by DrDuckedGoose** [comment]
> I don't know how to feel about this. It looks good, but it _feels_ wrong.

image
image

**Comment by EvilDragonfiend** [comment]
Tiles look cleaner as new, but I am not sure since it is way too far cleaner.

**Comment by itsmeow** [comment]
I don't like the new catawalks, they look too real

**Review by itsmeow — CHANGES_REQUESTED** [review]
tile_side turf decals anticorner sprites were shifted up/down one pixel. You can see it in the diff and on the picture with the scrubber in botany

**Comment by DrDuckedGoose** [comment]
> tile_side turf decals anticorner sprites were shifted up/down one pixel. You can see it in the diff and on the picture with the scrubber in botany

Fixed 👍

**Comment by ike709** [comment]
Sufficiently soulless 👍🏻

**Comment by PowerfulBacon** [comment]
I like if, these look a lot better

**Comment by itsmeow** [comment]
I like it, but what is this weird bendy stuff on the sideways catwalks? It looks wrong

image

**Comment by itsmeow** [comment]
Actually it looks like it might be a compression artifact

**Comment by PowerfulBacon** [comment]
> I like it, but what is this weird bendy stuff on the sideways catwalks? It looks wrong
> 
> image

It triggers me that these aren't the same proportion (like 3 pixels yellow for 4 pixels black)

**Comment by itsmeow** [comment]
> Apparently I forked this from the xenoarch fixes branch, so there's just a bunch on nonsense in the branch history from that, I guess.

`git rebase -i 0f32710b9f997699d8d068a4c4c3a2b82b087e42`
change `pick` for all of the commits you do not want to be there anymore to `drop`

**Comment by DrDuckedGoose** [comment]
Addressed catwalk issues
image

**Review by itsmeow — CHANGES_REQUESTED** [review]
The name of the new turf icons should use underscores not dashes

**Comment by itsmeow** [comment]
image
This is my issue with the catwalk, it doesn't line up sometimes. The one on the left is bad, the right is what it should be

**Comment by Bokkiewokkie** [comment]
Can you make sure the hazard stripes line up with the catwalks like they used to?
I also feel like the colors should stay the same for both of them.
image

Also looks like something went wrong here 
image

**Comment by DrDuckedGoose** [comment]
> Can you make sure the hazard stripes line up with the catwalks like they used to? I also feel like the colors should stay the same for both of them for consistency. (The lines on the catwalks _are_ hazard lines) image
> 
> Also looks like something went wrong here image

I'll see how matching the colors affect the look in space, the current colors are chosen to look fine in full-bright. I don't really feel like fucking around with the textures again, you can always make a follow-up PR :trollface: 

The other image, misaligned overlay, has been addressed.

**Comment by DrDuckedGoose** [comment]
Catwalks have been fixed btw, for real this time.

**Comment by itsmeow** [comment]
I really liked it in the TM, it looks great

**Comment by itsmeow** [comment]
image

Vertical catwalks are still a bit screwy. It looks fine horizontal though.

**Comment by PowerfulBacon** [comment]
These looked amazing in game

**Review by PestoVerde322 — DISMISSED** [review]
Everything is a-ok, soul is vanquished, approved.

**Comment by DrDuckedGoose** [comment]
Ah fuck

**Review by itsmeow — CHANGES_REQUESTED** [review]
image
No

turf-decalening changed these to new names and reformatted them entirely

**Comment by dwasint** [comment]
i can feel it, the soul. Its being removed.

**Comment by Pirill** [comment]
Honestly I like the resprite but the one thing that jumped out at me looking at the screenshots is that the tiles are really high contrast with the lines between them. I feel like floor tiles in general should be lower contrast, seeing as they're a background item that shouldn't distract from what's on top.

**Review by PowerfulBacon — APPROVED** [review]

**Review by itsmeow — APPROVED** [review]

**Comment by Penwin0** [comment]
The ravenous spriters feasting on soul :(

**Comment by ro5490** [comment]
These feel too clean for ss13 ;-; they're great but also aaaaa my eyes feel wrong

**Comment by ro5490** [comment]
image

general feel for them is good/strange
Nice work!

**Pull request merged**
