### PR TITLE
I made an oopsie

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
in my gun rebalance pr, i was under the impression this was set to MEDIUM on eguns, but apparently it's not? or someone changed the default gun value. Either way, this shit is fixed

## Why It's Good For The Game
see original gun pr

## Changelog
:cl:
fix: energy guns no longer dual-wield by default
/:cl:

### CODE REVIEW

**Review by qwertyquerty — DISMISSED** [review]

**Comment by eLeCtrOssSnake** [comment]
No

**Comment by eLeCtrOssSnake** [comment]
Eguns are light so they shouldn't be hard to wield.

**Comment by PowerfulBacon** [comment]
You can still fuel wield on harm intent right?

**Comment by zeskorion** [comment]
> You can still fuel wield on harm intent right?

dual wielding still works, just not with these

**Comment by PowerfulBacon** [comment]
I don't really see how removing the duel wield function from energy guns is a fix, and I don't really see a good reason for this balance-wise either

**Comment by zeskorion** [comment]
> I don't really see how removing the duel wield function from energy guns is a fix, and I don't really see a good reason for this balance-wise either

it was voted in in my gun fire rate refactor PR, or was at least intended. Reason was dual-wield disabler meta (which i believe is even mentioned in changelog). dual wielding was intended to be relegated to small-arms only

**Comment by PowerfulBacon** [comment]
Disablers are a small arms. Duel wielding disablers isn't even effective due to the massive inaccuracy and I have never actually seen anyone do it in game.

**Comment by zeskorion** [comment]
> Disablers are a small arms. Duel wielding disablers isn't even effective due to the massive inaccuracy and I have never actually seen anyone do it in game.

 It's actually quite a frequent meta i've seen a bit too often. Dual wielding is an esoteric tactic that shouldnt be common anyways

**Comment by r1ks-iwnl** [comment]
I have litterally never seen someone dual wield eguns or disablers, and yeah the innaccuracy just makes them useless unless you are right next to your target

**Comment by PowerfulBacon** [comment]
Failed vote, inaccuracy is too high when duel wielding to make it meta anyway

**Pull request closed without merging**
