### PR TITLE
Small flash refactor

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Removes unneeded var and makes code slightly better

:cl:
refactor: slightly refactored flash code.
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
changelog?

**Comment by Archanial** [comment]
Does not affect the game at all, I don't see a reason to make a changelog.

**Comment by aidan-bowman** [comment]
doesn't matter if it doesn't affect in-game, you have to add a changelog. there's even a couple special tags for code refactors.

**Comment by aidan-bowman** [comment]
besides, from what i can tell it does look like it affects the game.

**Comment by Archanial** [comment]
> 
> 
> besides, from what i can tell it does look like it affects the game.

How would this affect the game? This is really minor refactor (~3 lines swapped), I don't think there is a need for changelog, unless a maintainer specifically requests it.

**Comment by PowerfulBacon** [comment]
add a changelog anyway, its easier to track issues when things fuck up

**Review by utilbird — APPROVED** [review]
🙏

**Pull request merged**
