### PR TITLE
Plasmamen flash/welding protection is now a toggleable visor

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
Plasmamen helmets are no longer flashproof/nor have welding protection by default. Instead there's a built-in visor which acts like a welding helmet and gives protection. The helmet sprite changes by darkening the eyes and the helmet screen.

## Why It's Good For The Game
Plasmamen can be turned into revs easily now like every other race. Also like every other race they need to make an effort in order to get always-on flash protection which doesn't impair their vision. 

## Changelog
:cl:
balance: Plasmamen helmets no longer have flash/welding protection by default. Instead they have a toggleable visor which acts like a normal welding helmet. It being active can be noticed on the sprite. 
/:cl:

Ports:
https://github.com/tgstation/tgstation/pull/45369
https://github.com/tgstation/tgstation/pull/45606

### CODE REVIEW

**Comment by boolsrealm** [comment]
idk about this. plasmamen are already the most cucked race in existence, now you're cucking them even more.  can we just let them have one good thing without nerfing it into hell because "other races are supposed 2 be weaker!!" yeah i think we get that, dude has to fucking breathe plasma how more cucked can he get

**Comment by dekunutkid** [comment]
>how more cucked can he get

It used to be that plasmamen were objectively better than humans. spaceproof and flashproof roundstart with none of the penalties from either, immune to disease, no need to breathe. The only downsides being death if you lost your suit, and you were a bitch to clone. 
This fixes the problem of them being flashproof roundstart for free, just like they're no longer spaceproof.

**Comment by boolsrealm** [comment]
> It used to be that plasmamen were objectively better than humans. spaceproof and flashproof roundstart with none of the penalties from either, immune to disease, no need to breathe. The only downsides being death if you lost your suit, and you were a bitch to clone.
This fixes the problem of them being flashproof roundstart for free, just like they're no longer spaceproof.

ok? what was the point about saying any of this? this is no longer the case. you could've removed everything but "this fixes the problem of being flashproof roundstart for free" and your comment wouldn't have changed, because once again, this no longer applies. not only that, but they take an extra 50% damage to brute, fire, and laser attacks, headwounds cannot be healed by brute patches or ointment without having to take their helmet off (which causes them to burn), and surgery is a pain in the ass on a plasmaman

its a nerf, is what this is. and the only reason i could possibly imagine why someone would go in make this is that they got killed by a plasmaman while they tried to convert them. the original PR for this implied that plasmamen are used for POWERGAMERS, because of how powerful flashes were. guess what, flashes don't do shit anymore. he also said "taking 50% extra damage isnt significant", despite something like head-slamming a plasmaman into the table doing 60% of his health. i personally don't think this needs to be added, i don't see the point.

**Comment by zeskorion** [comment]
victor does like conversion antags and hates it when they aint gettin converted

**Comment by nikk735** [comment]
plasma men are already fucked yea let them be flash proof

**Comment by ike709** [comment]
Conflicts.

**Review by zeskorion — APPROVED** [review]

**Comment by VictorVow** [comment]
Conflicts resolved

**Pull request merged**
