### PR TITLE
KILO. IS. BACK.

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
THE MEMORY LEAK IS FIXED
THE STARS HAVE ALIGNED
KILO IS BACK

## Why It's Good For The Game
the prodigal son has returned

## Changelog
:cl:
add: kilostation
/:cl:

### CODE REVIEW

**Comment by Moccha-Bee** [comment]
Nice amount of commits also i'm bashing your skull in if this gets merged

**Comment by PowerfulBacon** [comment]
I thought you removed all the rusted walls

**Comment by zeskorion** [comment]
> I thought you removed all the rusted walls

Is that necessary?

**Comment by Unidentified-Biohazard** [comment]
Just one question: why?

**Comment by PowerfulBacon** [comment]
I'll stuff it on testmerge

**Comment by PowerfulBacon** [comment]
@zeskorion THERE ARE STILL HEAVY FIRELOCKS!

**Comment by PowerfulBacon** [comment]
Not up to date at all

**Comment by Blueturbo47** [comment]
> Just one question: why?

Why not?

**Comment by zeskorion** [comment]
its ready, merge just fucked

**Comment by PowerfulBacon** [comment]
Merge conflicts, warden's office room has normal sec access, The brig physician needs a proper area

**Comment by TeomanTheGreat** [comment]
What ever happened to this?

**Pull request closed without merging**
