### PR TITLE
Multitool for Tcomms and Arcade machine replacement on Deltastation

### PR DESCRIPTION
**Pull request by Vexylius**
Added multitool to telecomms room and replaced one arcade machine in abandoned arcade to Mediborg's amputation adventure on Deltastation.

## About The Pull Request

Just a quick PR to check if I'm doing it right.

## Why It's Good For The Game

You don't need to look for a multitool, if you wanna fix telecomms, anymore and you have a cool way to lose your arm in maints.

## Changelog
:cl:
tweak: minor map changes to Deltastation
/:cl:

### CODE REVIEW

**Comment by Vexylius** [comment]
is it cool or not cool?

- _**huh?**_

**Comment by zeskorion** [comment]
Oh hey i was planning on making use of the amputation machine. Couldja put that in the fuckin uh random maint arcade?

**Review by ike709 — CHANGES_REQUESTED** [review]
Conflicts and also it looks like you didn't mapmerge.

**Comment by qwertyquerty** [comment]
Still got conflicts @Vexylius

**Pull request closed without merging**
