### PR TITLE
Lets slow this dance down

### PR DESCRIPTION
**Pull request by Crossedfall**
## About The Pull Request

Brings the movement speed in line with Sage after popular demand

## Changelog
:cl:
config: Movement delay on Golden is changed to 1.5, making it the same as Sage.
/:cl:

### CODE REVIEW

**Comment by Nosnek199** [comment]
Movement speed going down? Thank god.

**Comment by Goblinu** [comment]
but my what about my latency reliant melee combat 😔

**Comment by Vexylius** [comment]
It's finally here! One-line PR that changes it all

**Comment by ivanmixo** [comment]
Sideward step in my opinion. On one hand fast combat makes strategy more important, but the other hand BYOND is bad at registering clicks on fast targets.

**Comment by ghost** [comment]
I'd like to see sage slower eventually, or walking made usable instead of everyone running all shift.

**Comment by Crossedfall** [comment]
Based on the feedback I've been given and the lack of any massive revolt, this seems good to go.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by REALALFREDCOLLINS** [comment]
*looks at you like you should play COH2 with me

**Pull request merged**
