### PR TITLE
Canister sprite update

### PR DESCRIPTION
**Pull request by iamthesilly**
## About The Pull Request

Adds a bunch of canister sprites that I thought looked much better than the current grayscale one. 

Ports canister sprites from yogstation13/Yogstation#9715 and the portable pump sprites from yogstation13/Yogstation#9496

Sprites were made by Tex and Partheo.
image

Examples of the sprites in context:
image
image
image
image
image
image
image
image

## Why It's Good For The Game

The canister sprites currently in use look very out of place, an update is long overdue in my opinion.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image
image
image
image
image
image
</details>

## Changelog
:cl: Tex, Partheo, SapphicOverload
add: New sprites for canisters and pumps
/:cl:

### CODE REVIEW

**Comment by DrDuckedGoose** [comment]
Very nice. Shame it isn't GAG'd.

**Comment by PowerfulBacon** [comment]
The perspective on these is absolutely horrible

**Comment by DrDuckedGoose** [comment]
> The perspective on these is absolutely horrible

Looks fine in testing. What perspective should it be anyway?

**Comment by CydiaLamiales** [comment]
Why though

**Comment by imsynthex** [comment]
imo they are not an improvement on what we have now

**Comment by PestoVerde322** [comment]
honestly, if you can tweak the perspective a little and it should be good to go

**Comment by kit-katz** [comment]
with every day that passes we are becoming more and more goon... not bad per say

**Comment by Naevii** [comment]
some of the colors don't match our colors. The outlines seem lighter and darker depending on the canister. I would also prefer more hue shifting.  the contrast between shades also varies. But the perspective is 3/4 and seems fine to me.

**Comment by Tsar-Salat** [comment]
> some of the colors don't match our colors

To be fair, when we GAG'd the canisters the color got fucked up on several of the cans, such as the Plasma can which is Red right now for some reason.

It's original color is orange, which is the correct color.

**Comment by SapphicOverload** [comment]
here's some examples of how they look in context

image
image
image
image
image
image
image
image

**Comment by SapphicOverload** [comment]
fixed

**Comment by Penwin0** [comment]
These look really strange, clashes hard with everything else.
I'd rather we kept current sprites on these.

**Review by ike709 — CHANGES_REQUESTED** [review]
Terrible 🔑

**Comment by itsmeow** [comment]
:key: They don't match our current perspective and style

**Pull request closed without merging**
