### PR TITLE
Renames 'Delimber' anomalies to 'Bioscrambler' anomalies + fixes unintended behavior

### PR DESCRIPTION
**Pull request by Tyranicranger4**
## About The Pull Request

Fixes Delimber anomalies having incorrect defines leading to them deleting the wrong limbs.
It's supposed to replace a limb and then delete the old limb. Instead it was replacing a limb, dropping it on the floor, and then in some cases (if it was an arm or a leg) it would delete a different, incorrect limb. Delimber anomalies (contrary to their name) aren't supposed to actually *remove* limbs, just alter them.

Additionally renames 'Delimber' anomalies to 'Bioscrambler' anomalies.
Also slightly improves Delimber anomaly logging.

## Why It's Good For The Game
Fixing unintended behavior is often a good thing, and I believe it will be in this case.
Following this PR it hardly makes sense for them to be called 'Delimber' anomalies anymore.
Improved logging is always good.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Renamed anomaly.
image
image

Limb gets replaced properly, no incorrect limbs get deleted.
image

Improved logging message ingame.
image

New logging message in-file.
image
image

Further testing evidence can be found here:
(Logging messages are slightly out of date in this clip)
https://streamable.com/7kj0b0

</details>

## Changelog
:cl:
fix: Fixed Delimber anomalies actually delimbing people, despite their name this was not their intended behavior
admin: Slightly improved Delimber anomaly logging
tweak: Renamed 'Delimber' anomalies to 'Bioscrambler' anomalies
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
> Fixes delimber anomalies actually delimbing people.

Why do we still have this name if it's a misnomer. Seems a bit silly lmao

**Comment by Tyranicranger4** [comment]
> Why do we still have this name if it's a misnomer. Seems a bit silly lmao

That's a fair point, I'll look into a replacement name.

**Comment by Tyranicranger4** [comment]
TG ended up renaming them to 'Bioscrambler' anomalies, I think that's a fine replacement.

**Review by mystery3525 — COMMENTED** [review]
It would be a good idea to port /tg/'s bioscrambler though if it's too much to handle that's fine

**Comment by Tyranicranger4** [comment]
> It would be a good idea to port /tg/'s bioscrambler though if it's too much to handle that's fine
 
It's something that I'd like to do. However I'm not familiar with how to properly port things, so I'd rather get this through first and then look into it.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
