### PR TITLE
Removes the staff of instant death from the game.

### PR DESCRIPTION
**Pull request by AnCopper**
## About The Pull Request

Removes the instant death bolt and the staffs.

## Why It's Good For The Game

Do I even need to explain why instant death weapons are horrible for the game?

## Changelog
:cl:
del: removed the instant death staff
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
For debugging?

**Comment by AnCopper** [comment]
> For debugging?

Yeah hold on, I'll re-add the debug one.

**Comment by PowerfulBacon** [comment]
I agree it should be removed from rightandwrong, but I don't think it should be removed from magicarp or the wizard themselves. (Its already removed from xenocarps iirc, the chaos carps are only spawned by wizard events)

**Comment by AnCopper** [comment]
> I agree it should be removed from rightandwrong, but I don't think it should be removed from magicarp or the wizard themselves. (Its already removed from xenocarps iirc, the chaos carps are only spawned by wizard events)

It makes the Wizard, an already horrible and overpowered antag, even worse.

**Comment by DerpiestBruh** [comment]
> > I agree it should be removed from rightandwrong, but I don't think it should be removed from magicarp or the wizard themselves. (Its already removed from xenocarps iirc, the chaos carps are only spawned by wizard events)
> 
> It makes the Wizard, an already horrible and overpowered antag, even worse.

Wizard is supposed to be OP tho

**Comment by AnCopper** [comment]
> > > I agree it should be removed from rightandwrong, but I don't think it should be removed from magicarp or the wizard themselves. (Its already removed from xenocarps iirc, the chaos carps are only spawned by wizard events)
> > 
> > 
> > It makes the Wizard, an already horrible and overpowered antag, even worse.
> 
> Wizard is supposed to be OP tho

Ah yes, it's okay because it's shitty by design.

**Comment by PowerfulBacon** [comment]
> It makes the Wizard, an already horrible and overpowered antag, even worse.

1 tap validhunters gives a strong satisfaction

**Comment by TeomanTheGreat** [comment]
> > I agree it should be removed from rightandwrong, but I don't think it should be removed from magicarp or the wizard themselves. (Its already removed from xenocarps iirc, the chaos carps are only spawned by wizard events)
> 
> It makes the Wizard, an already horrible and overpowered antag, even worse.

Did you know that the only way to get deathbolt as wiz is with the staff of chaos which can rng fire bolts like fireball and healing? Because this defeats the whole rng gimmick of the weapon. Just remove it for everything but the chaos staff

**Comment by BrumalLake** [comment]
🤯 magic proofing holy melons (included in wizard validhunt kit) full counter to death stick
stop fist fighting the wizard expecting great returns
doesn't even recharge on its own

**Comment by AnCopper** [comment]
> > It makes the Wizard, an already horrible and overpowered antag, even worse.
> 
> 1 tap validhunters gives a strong satisfaction

Validhunters? What do you want them to do, just let the Wizard go and murder everyone? Ignorning the Wizard is like ignoring nuke ops.

**Comment by AnCopper** [comment]
Instant death weapons outside of the hands of the Admins are just terrible for the game, you're required to do some hardcore mental gymnastics to justify it.

**Comment by BrumalLake** [comment]
so you are gonna ignore the fact that magic resistance is pretty easy to get through botany and the few charges the death stick has

**Comment by Mick1299** [comment]
You can remove it from active play without completely removing it from the game. I wont debate the gameplay implications, but I will debate the execution of it.

**Comment by Wilchenx** [comment]
> > > > I agree it should be removed from rightandwrong, but I don't think it should be removed from magicarp or the wizard themselves. (Its already removed from xenocarps iirc, the chaos carps are only spawned by wizard events)
> > > 
> > > 
> > > It makes the Wizard, an already horrible and overpowered antag, even worse.
> > 
> > 
> > Wizard is supposed to be OP tho
> 
> Ah yes, it's okay because it's shitty by design.

image

I DIED IN A VIDEO GAME WAAAAAAAAAAAAAAAAAAAAH

**Comment by Sinestia** [comment]
> 
> 
> > > > I agree it should be removed from rightandwrong, but I don't think it should be removed from magicarp or the wizard themselves. (Its already removed from xenocarps iirc, the chaos carps are only spawned by wizard events)
> > > 
> > > 
> > > It makes the Wizard, an already horrible and overpowered antag, even worse.
> > 
> > 
> > Wizard is supposed to be OP tho
> 
> Ah yes, it's okay because it's shitty by design.

If you want to change the intent of wizard you probably need to do a full spell rework or just disable the gamemode tbh. I dunno if it has a place on RP servers as it's a gamemode that demands heavy powergaming from the crew to work. 

At least that to me always seemed like how it's designed to work.

**Comment by PowerfulBacon** [comment]
:key: Honestly if it were somewhat common are actually accessible in normal gameplay it would absolutely have to go, but it's only available to the wizard and on a gamemode that's super old. If you want wizard combat to be longer, the wizard needs to start with items that mean they cant get killed in a single hit too

**Comment by PowerfulBacon** [comment]
> Do I even need to explain why instant death weapons are horrible for the game?

Yes please do, we arent mind readers and the reasons people want to bring stuff in is important.

**Comment by AnCopper** [comment]
> > > > > I agree it should be removed from rightandwrong, but I don't think it should be removed from magicarp or the wizard themselves. (Its already removed from xenocarps iirc, the chaos carps are only spawned by wizard events)
> > > > 
> > > > 
> > > > It makes the Wizard, an already horrible and overpowered antag, even worse.
> > > 
> > > 
> > > Wizard is supposed to be OP tho
> > 
> > 
> > Ah yes, it's okay because it's shitty by design.
> 
> image
> 
> I DIED IN A VIDEO GAME WAAAAAAAAAAAAAAAAAAAAH

Redditor spotted.

**Comment by ghost** [comment]
Wizard entire point is for an overwhelmingly overpowered solo antag to battle the entire station. crew need to band up and unite to kill the wiz. if you nerf the wizard so fucking much they could get robusted by one guy. that's not a real wiz gamemode.

**Comment by AnCopper** [comment]
> Wizard entire point is for an overwhelmingly overpowered solo antag to battle the entire station. crew need to band up and unite to kill the wiz. if you nerf the wizard so fucking much they could get robusted by one guy. that's not a real wiz gamemode.

Yeah, it's bad by design.

**Comment by PerishedFraud** [comment]
It's rare, you can dodge it or cpunter it, and you can be revived easily, and probably will be in a wiz round. Yeah its bland mechanically but this makes no effort to fix it and just removes. -1.

**Comment by PowerfulBacon** [comment]
> 
> 
> It's rare, you can dodge it or counter it, and you can be revived easily, and probably will be in a wiz round. Yeah its bland mechanically but this makes no effort to fix it and just removes. -1.

It is so rare it has a probability of 0

**Comment by qwertyquerty** [comment]
:key:

**Pull request closed without merging**
