### PR TITLE
Allow fugitives to spawn if more than 4 people sign up

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

I made a mistake in the spawning logic that meant if more than the max amount sign up nothing could spawn. This limits it to anything under the maximum as intended. Also adds minimum logic if anything ever wants to use that.

## Why It's Good For The Game

Fugitives not spawning when people want to play it is baad

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Untested since i don't have 5 alts but it should work

</details>

## Changelog
:cl:
fix: Fixed fugitives being unable to spawn if more than 4 people signed up for it.
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
Running the event and spawning as Walton to show it works basically would be enough for testing

**Comment by itsmeow** [comment]
Yea but I didn't actually touch that part, it wouldn't actually test the thing I'm fixing

**Comment by PowerfulBacon** [comment]
You still refactored the way that the rules are chosen so should run the event to ensure that you at least get that behaviour that you expect. PRs that can't be tested are fine, but you should go as far as you possibly can to show that the previous behaviour at least still works. If Wally can't spawn then we know that the event has to be broken.

**Comment by itsmeow** [comment]
i like that you keep changing what you call Waldo it's entertaining

**Comment by PowerfulBacon** [comment]
My phone auto corrected the first one

**Review by PowerfulBacon — APPROVED** [review]
Running through logic again and again and it seems fine. I'll let this slide for now

**Comment by itsmeow** [comment]
maintainer privelege

**Pull request merged**
