### PR TITLE
Updates Emergency Luxury Shuttle

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
The shuttle is made by Randal the Vandal. I'm only PRing it.

image

## Why It's Good For The Game
Improves a very outdated shuttle.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>
Shuttle works but has some quirks which will be ironed out.

image

image

image

</details>

## Changelog
:cl: Randal the Vandal
tweak: Remade the Luxury shuttle.
balance: Gave it fully stacked Medical and a Brig section.
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
Post the full sizs map image of the dmm

**Comment by MarkusLarsson421** [comment]
> Post the full sizs map image of the dmm

Added it.

**Comment by Rukofamicom** [comment]
This is legitimately failing checks.

**Comment by EvilDragonfiend** [comment]
I don't feel this is really luxury. You need to redesign, I suppose.

**Comment by Rukofamicom** [comment]
The recreational areas have a pool and a fully stocked dining area with a piano, as well as a fully stocked and functional bar
The medbay has a cryopod and is stocked with supplies
All of the seating is extra fancy, even in the security holding area. 
There's a fully stocked garden

What isn't luxury about this?

**Comment by MarkusLarsson421** [comment]
> What isn't luxury about this?

Think he means it is functional luxury, not aesthetical luxury

**Comment by Fronsis** [comment]
Couldn't they break the window to pass to the other area?

 I do agree a redesign could help a bit, perhaps remove the botany area to make space to more luxury stuff?

**Comment by MarkusLarsson421** [comment]
Currently it is using an indestructable window. Although this window has no plating.

**Comment by Rukofamicom** [comment]
If this gets fixed up I like how it looks far better than our current eyesore of a shuttle.

**Review by spockye — CHANGES_REQUESTED** [review]
image

missing floors

image

whats going on with the carpets here?

image

thats a shit ton of medkits for a shuttle. do you really need that many?

image

lattices and catwalks get left behind whenever the shuttle launches

image

not really a fan of the use of pool borders... 

image

no floors under the windows + clipping with the showers

image

light on fire extinguisher

image

the bridge is really akward. specifically the chair placement and locker placement. the walls are also clipping.  

image

pool bugs out due to the lack of dirs. mabye think of another way of handling it? 

image

consider removing the tree or changing the pixelshifting. 

image

poorboys access doesnt align

image

dont pixelshift the chargers!

---------------

image

personally this area doesnt really give me high class vibes? mabye try using wood/carpets more than cargo decalling.

**Comment by EvilDragonfiend** [comment]
yeah this doesn't feel like really luxury and have no high class vibe. spcokye pointed it out.
it's just a Bar shuttle MK-2 with extra space.

the original luxury shuttle has the indestructible green walls and some magical payout gates with runes.
I don't really think this suceeded the original luxury shuttle. It's just another shuttle.

**Comment by Rukofamicom** [comment]
> the original luxury shuttle has the indestructible green walls

And this one has indestructible walls and windows that don't look like vomit. 

> and some magical payout gates with runes.

And so does this one.

**Comment by MarkusLarsson421** [comment]
Will be closing this due to lack of updates, failures and increase in complexity. They will have to PR it themselves when they feel like the time is right. I do like this shuttle more than the old one though.

**Pull request closed without merging**
