### PR TITLE
Roundstart Arrivals Shuttle Spawn!

### PR DESCRIPTION
**Pull request by TsunamiAnt**
## About The Pull Request
This makes it so that people no longer spawn at their workplaces or spawners at roundstart, but instead always spawn with the arrivals shuttle.

Basically like that one station trait. I removed that by the way, since it's now the default.

**This would be much nicer if the following config entries were changed by the way:**
**ARRIVALS_SHUTTLE_REQUIRE_UNDOCKED / uncommented**
**ARRIVALS_SHUTTLE_DOCK_WINDOW / set to something longer, maybe 200 or so.**

## Why It's Good For The Game
I like the concept of everyone starting in the same space and being held there for a bit. NSV also frequently spawns people near each other, and the command team used to give the roundstart announcement right then and there using megaphones.

I think it adds a sort of camaraderie. Instant feedback with whom you'll be working today. It's very comfy I think.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
tweak: Roundstart spawns now use the arrivals shuttle.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
This is a bad idea, I am already against the arrival spawn station trait since new players get screwed over by being forced to hobble around and find their workplace which may be hidden in maintenance. Also on anything above 50 pop this will just not work at all and will be an absolute nightmare.

**Comment by TsunamiAnt** [comment]
remember this is only ever the readied up part of the players, even at 50-70 pop  that's only gonna be like 30 or something. Also if new players spawn in with everybody else, they'll naturally group up with their colleagues and just follow them along.

**Comment by EvilDragonfiend** [comment]
🔑It'll be fine as long as it's small pop, but it'll be uncontrollable chaotic if it becomes high pop.

**Comment by MarkusLarsson421** [comment]
> they'll naturally group up with their colleagues and just follow them along.

Sort of doubt this as those who know the map and game will just rush towards their department, while the newbies will still be buckled to their seat. It does help the Fland lines to make sense, though.

Perhaps if the arrival shuttle was big enough to fit 60 players...? Hell, what if there were two 30-seat shuttles? It might look cool.

**Comment by MarkusLarsson421** [comment]
While I like this and have wanted it together with my Locker Room PR (WIP, not yet PRd). Look at the current rounds where it randomly happens. It's like the inverse of a train in Tokyo where 60 people have to get out of four doors, and everyone wants to be at the front.

**Comment by TsunamiAnt** [comment]
Y'all have some damn lack of faith in your players smh. I bet people will get used to it.

**Comment by ClownMoff** [comment]
I love this don't listen to the haters

**Comment by ClownMoff** [comment]
Starting the shift standing in the middle of your place, standing, is weird

**Comment by EvilDragonfiend** [comment]
> I love this don't listen to the haters

ye I am not gonna listen to haters haters, no worries haha

**Comment by PowerfulBacon** [comment]
🔑 Seems like it will be extremely annoying without actually adding anything. There is a big difference between everyone spawning in a meeting room, ready for a meeting, and everyone spawning on a cramped shuttle where they have to fight their way to their department. The start of every battle royale game is how this will turn out to be on higher pops, people shoving and swapping places to get out of the ship while new players wander lost since the janitor closet is hidden in maints on most maps. I was already on the verge of removing the station traits that spawn people away from their departments for the same reason with forcing new players to be lost so this probably won't make it into the game.

**Comment by Tsar-Salat** [comment]
> forcing new players to be lost

#10158 

We were so closd

😢

**Comment by TsunamiAnt** [comment]
The institutions are silencing me, listen people and heed me well, I am a martyr on bloody soil.
but yeah you're prolly right.

**Pull request closed without merging**
