### PR TITLE
Adds the ability to insert screwdrives into autolathes

### PR DESCRIPTION
**Pull request by Bokkiewokkie**
## About The Pull Request

Lets you insert screwdrivers into autolathes when using help intent. Using a screwdriver on a screwed-open autolathe will still close it no matter the intent.

## Why It's Good For The Game

Finally we will have a way to deposit the ten extra screwdrivers we accidentally printed back into the autolathe.

## Changelog
:cl:
tweak: Made it possible to insert screwdrivers into autolathes with help intent.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
This seems very annoying

**Comment by Bokkiewokkie** [comment]
> This seems very annoying

I've heard a lot of people complain about not being able to put screwdrivers into lathes on NSV, and this seems like the least annoying way to do it to me.

**Review by itsmeow — CHANGES_REQUESTED** [review]
How about instead, it opens a prompt asking if you want to "Open the panel" or "Insert the screwdriver"

**Comment by PowerfulBacon** [comment]
Help intent would be the intent I'd use to want to open the panel though, rather than insert it in.

**Comment by Bokkiewokkie** [comment]
> How about instead, it opens a prompt asking if you want to "Open the panel" or "Insert the screwdriver"

Yeah that's a good solution as well. ~~Besides mass-inserting things into autolathes is already annoying enough that this won't affect the experience much.~~

**Comment by ike709** [comment]
This would get annoying so fast.

**Comment by itsmeow** [comment]
I personally have never tried inserting a screwdriver into an autolathe, but I would like the ability to. I do not see a reason to close this.

**Comment by Tsar-Salat** [comment]
> Help intent would be the intent I'd use to want to open the panel though, rather than insert it in.

Intents being the form of "use" has precedence however. AFAIK you have to be on harm intent to dismantle a non-reinforced table with a wrench

**Comment by DrMacCool** [comment]
I'd just flip it around. Make the autolathe eat the screwdriver on 'harm', as opposed to 'help'. The potential of fat-fingering it is inevitable, but much fewer people just run around on harm, so it's probably the easisest fix, short of totally overhauling the PR.

**Comment by PowerfulBacon** [comment]
I think this would get annoying and isn't worth the minor inconvenience of not being able to insert them back in

**Pull request closed without merging**
