### PR TITLE
Makes IPCs slightly faster

### PR DESCRIPTION
**Pull request by Toxici11i**
Balance changes aaa

### CODE REVIEW

**Comment by Lagomorphica** [comment]
why do they need to be faster though

**Comment by ondrej008** [comment]
> 
> 
> why do they need to be faster though

Why do they need to be faster though?

**Comment by Toxici11i** [comment]
Its a minor speedbuff (to account for damage and EMP vulnerability, plus some changes that will be coming to them soon, like higher electrical damage taken and other things)

**Comment by Lagomorphica** [comment]
make dismemberment work first luhmayo

or give them higher brute i donno

or make them not able to space walk

otherwise you just have plasmeme + +eventually

**Comment by ondrej008** [comment]
> 
> 
> Its a minor speedbuff (to account for damage and EMP vulnerability, plus some changes that will be coming to them soon, like higher electrical damage taken and other things)

What does higher electrical damage taken even do? More damage from shocked doors? There is like 1 and a half things that use electrical damage.

**Comment by Lagomorphica** [comment]
also also they already take 157.5 damage from a shocked door at max charge

**Comment by Toxici11i** [comment]
Dismemberment already works (i bugfixed this earlier), spacewalking will be resolved, higher electrical damage applies to weapons. I am also planning on changing how stamina damage affects IPCs etc.

**Comment by Lagomorphica** [comment]
i just don't want them to become unbalanced for

_obvious reasons_

**Comment by Toxici11i** [comment]
yes i know, and im planning nerfs after this

**Pull request merged**
