### PR TITLE
Adjusts requirements to unlock jobs (Take two)

### PR DESCRIPTION
**Pull request by Rukofamicom**
## About The Pull Request

This PR adjusts the hours required to play Medical, Engineering and Science jobs. All of these jobs have a purpose to fulfil on the station that a legitimately new player will not be able to grasp. Additionally adds a minor barrier to make griefers much more apparent to admins observing them when they first connect, as well as players appropriately attempting to uphold access restrictions to their department. 

Additionally tweaks a small amount of other jobs:
* Virologist now requires ten hours of medical, due to how dangerous it is when mishandled. Players should be familiar with medbay in general before moving into the virology lab. This places it at half of the requirement for Chief Medical Officer, much like the Warden requires within Security. 
* Head of Personnel now requires ten hours played as **command** instead of service. The HoP is not just the Supply/Civilian head, but also in charge of handing out access across the station and the second in command, one step down from the Captain. Giving players such an elevated position as their first Head of Staff has caused a staggering amount of problems and this is the best solution to ensuring HoP are less inclined to hand out access they shouldn't.
* AI now requires ten hours as cyborg instead of just four. AI is probably the single most powerful entity on the station, and should be vetted with a bit more experience in silicons before being granted the level of power and responsibility they are.
* Brig Physician's requirements have been reduced to just two hours as normal crew, like the rest of the medical jobs. 

## Why It's Good For The Game

Keeps 100% new players out of important areas, and also makes things a little more difficult for potential griefers. 

## Changelog
:cl:
tweak: Medical, Engineering and Science jobs now require two hours played
tweak: Brig Physician now only requires two hours as normal crew
tweak: AI now requires 10 hours as a cyborg
tweak: HoP now requires 10 hours as a different Head of Staff
/:cl:

### CODE REVIEW

**Comment by ItsTisme** [comment]
TBH too many hours for viro, and detective should still be locked behind hours just because of how powerfull he is, it will only give new player incentives to act a sec officer since they dont know any better

**Comment by Rukofamicom** [comment]
> it will only give new player incentives to act a sec officer since they dont know any better

Or perhaps it won't because they won't already be forced into the normal security officer mindset.

**Comment by PowerfulBacon** [comment]
I dont think it will change anything with the detective, the only reason they are good for validhunting is because they have basically the most powerful roundstart weapon in all of security. Needing more hours for the more complex roles is good though.

**Comment by Rukofamicom** [comment]
Bribe someone to change detective from Noire flavored to Sherlock Holmes flavored and we solve that problem pretty handily while keeping a pretty nice and fitting flavor ¯\\\_(ツ)_/¯

**Comment by williamcll** [comment]
Honestly no, Det should stay that high because chances are that you might be turned from a private investigator to police inspector  when the situation gets bad.

**Comment by Rukofamicom** [comment]
Reverted the detective change to how it was. It now requires three hours as an officer again.

**Comment by PowerfulBacon** [comment]
Jesus, 10 hours as cyborg is a lot

**Comment by williamcll** [comment]
> Jesus, 10 hours as cyborg is a lot

that's just seven rounds.

**Review by ike709 — CHANGES_REQUESTED** [review]
Virologist is too high

**Comment by Rukofamicom** [comment]
Forgot to keep up with this - it was previously three hours, do you want me to just remove the change entirely?

**Review by Archanial — APPROVED** [review]

**Pull request merged**
