### PR TITLE
Admins can rightclick mobs to assumedirectcontrol

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
You can now assume direct control of a mob by rightclicking it

## Why It's Good For The Game
Admins can now easily body hop, also makes it 10% easier to local test with multiple bodies

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
admin: right click to assume direct control
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
this is already a thing in the debug verbs, imo just make debug verbs auto enable if you have localhost priveleges

**Comment by etherware-novice** [comment]
oh uh how do you check if youre running localhost?

**Comment by PowerfulBacon** [comment]
Dragging your own ghost into a body. The hard part is dragging someone else in. But there's a button in varedit for that

**Comment by etherware-novice** [comment]
wait what

**Comment by etherware-novice** [comment]
you know what

**Pull request closed without merging**
