### PR TITLE
Heretics Objective Revision

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Revises heretics' objectives:
* Heretics have a chance to get hijack/ascend objective
* No longer get protect objective
* Heretics no longer automatically greentext when ascending

## Why It's Good For The Game

Heretic objectives were a little weird or confusing, and didn't make much sense. Greentext ascension meant heretics had literally no reason to follow their objectives and would just ascend.

## Changelog
:cl:
add: Heretics have a chance to get hijack/ascend objective
add: Heretics no longer get protect objective
del: Heretics no longer automatically greentext when ascending
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
honestly I think the auto-greentext for ascending is better than an ascending objective since ascending is near impossible

**Comment by eeSPee** [comment]
> honestly I think the auto-greentext for ascending is better than an ascending objective since ascending is near impossible

Yea but, then, Heretics have no real reason to follow their objectives and, instead, will just roam around hunting the tears in reality, and die when they need to make sacrifices and can't, cause all their spells are shit.

**Comment by Sinestia** [comment]
> > honestly I think the auto-greentext for ascending is better than an ascending objective since ascending is near impossible
> 
> Yea but, then, Heretics have no real reason to follow their objectives and, instead, will just roam around hunting the tears in reality, and die when they need to make sacrifices and can't, cause all their spells are shit.

This isn't without problems itself tho

since the power curve for heretics encourages you to work towards ascensions, instead of just being a mediocre assassinate tator.

**Comment by eeSPee** [comment]
> since the power curve for heretics encourages you to work towards ascensions, instead of just being a mediocre assassinate tator.

Why do we give them objectives then?

**Comment by Sinestia** [comment]
> > since the power curve for heretics encourages you to work towards ascensions, instead of just being a mediocre assassinate tator.
> 
> Why do we give them objectives then?

because antags get objectives in general despite it being a pretty poor system 

Also bcuz on the server it was ported from, antags are free to ignore their objectives and do their own thing (even on the rp server, with limits) so it doesn't really matter there I guess?

**Comment by eeSPee** [comment]
> Also bcuz on the server it was ported from, antags are free to ignore their objectives and do their own thing (even on the rp server, with limits) so it doesn't really matter there I guess?

That's not an argument...

**Comment by Sinestia** [comment]
> > Also bcuz on the server it was ported from, antags are free to ignore their objectives and do their own thing (even on the rp server, with limits) so it doesn't really matter there I guess?
> 
> That's not an argument...

You asked for an explanation not an argument

 The actual argument was already made, crap objectives don't make heretic more fun than just ignoring them and going for actual heretic mechanics.

**Comment by VictorVow** [comment]
>  > honestly I think the auto-greentext for ascending is better than an ascending objective since ascending is near impossible
>
> Yea but, then, Heretics have no real reason to follow their objectives and, instead, will just roam around hunting the tears in reality, and die when they need to make sacrifices and can't, cause all their spells are shit.

How about instead objectives to get certain achievements along the paths? E.g. create 3 flesh ghouls, inflict 4 mask of madness, craft 2 eldritch water etc.

This way it's less of a choice between ascending vs objectives and instead more about encouraging variety in which ascension path you choose.

**Comment by heepox** [comment]
Protect objective removal good as it does not even work right now.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
