### PR TITLE
Removes one way road

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

This trait is poorly implemented due to existing in base damage procs and is unbalanced as hell.

## Why It's Good For The Game

Removes a poorly coded, overpowered trait.

## Testing Photographs and Procedure

image
image

## Changelog
:cl:
del: Deletes one way road trait and absolution holoparasite ability.
/:cl:

### CODE REVIEW

**Comment by Absolucy** [comment]
my shenanigans have caught up to me 😭

**Comment by CydiaLamiales** [comment]
Make it adminbus only and improve the code smh

**Comment by PowerfulBacon** [comment]
> Make it adminbus only and improve the code smh

No

**Comment by JixS4v** [comment]
would be cool as adminbus only, especially if you wanna bus a godlike creature in to deal with issues IC

**Comment by CydiaLamiales** [comment]
> > Make it adminbus only and improve the code smh
> 
> No

1984, headdev confirmed funhater

**Comment by PowerfulBacon** [comment]
The effort required to refactor this code quality isn't work it. It's existence is also just a crappy reference.

**Comment by JixS4v** [comment]
It's actually "its" in this context. Owned. Now close this PR.

**Comment by imsynthex** [comment]
> It's actually "its" in this context. Owned. Now close this PR.

Actually "Its" capitalized because it's at the start of a sentence

**Comment by EvilDragonfiend** [comment]
HEADCODER TYRANNY!!!!

**Comment by JixS4v** [comment]
At least let the discord vote on it

**Comment by EvilDragonfiend** [comment]
> At least let the discord vote on it

It's not how tyranny works you silly

**Review by itsmeow — APPROVED** [review]
Tyranny.

**Pull request merged**
