### PR TITLE
Removes miasma, corpseflowers, and the rot component

### PR DESCRIPTION
**Pull request by Kapu1178**
## About The Pull Request
title

## Why It's Good For The Game
Miasma is hooked into the life loop not once but *twice*, y'know, one of the most expensive procs in the game over the course of a round.

It's also commonly used to generate unreasonable amounts of money for very little effort, which also, causes a ton of lag, because hee-hoo atmos updates.

## Changelog
:cl:
del: Miasma
del: Rot component
del: Corpseflowers
balance: Atmosbot EMAG now generates CO2
/:cl:

### CODE REVIEW

**Comment by KoboldCommando** [comment]
Why not find a more efficient and/or simpler way to calculate rot?  I'm sure there are ways you can check for rotting gibs and corpses and create miasma with less performance demand.  That and a price adjustment seems like it would achieve what you're doing here without removing mechanics from the game.

This approach removes motivation for people to take care of corpses and gibs, so I would expect them to start simply allowing them to rot in the hallways.  It also removes a lot of vectors for disease making the virologist's already debatable supportive duties even less wanted and making general station health easier to maintain and less unpredictable.  It seems like an overall negative to me, even if it comes with a performance improvement.

**Comment by Merlin1230** [comment]
> It's also commonly used to generate unreasonable amounts of money for very little effort

why dont you just lower how much it sells for then?

**Comment by Kapu1178** [comment]
> > It's also commonly used to generate unreasonable amounts of money for very little effort
> 
> why dont you just lower how much it sells for then?

doesn't fix the issue of its a lag generator

**Comment by Kapu1178** [comment]
> Why not find a more efficient and/or simpler way to calculate rot? I'm sure there are ways you can check for rotting gibs and corpses and create miasma with less performance demand. That and a price adjustment seems like it would achieve what you're doing here without removing mechanics from the game.
> 
> This approach removes motivation for people to take care of corpses and gibs, so I would expect them to start simply allowing them to rot in the hallways. It also removes a lot of vectors for disease making the virologist's already debatable supportive duties even less wanted and making general station health easier to maintain and less unpredictable. It seems like an overall negative to me, even if it comes with a performance improvement.

I guarantee people will clean up corpses. Bay doesn't have miasma and people on bayforks clean up corpses.

We have failed as a roleplay server if there needs to be a mechanical reason to not leave a dead body in the hallway.

**Comment by Fronsis** [comment]
improve don't remove tm

On a serious note actually the other day i was thinking it would be nice to port over the rat-king and his stinky of miasma to add some fun in maints...

Can't there be a way to fix that? It's not like we have an on-going meta of miasma farms EVERY round, we had a couple of weeks like that a year ago but nowadays i barely see it tbh, how did TG handle the ''miasma=lag'' issue? considering they have stuff like Rat king and so on.

**Comment by Kapu1178** [comment]
> improve don't remove tm
> 
> On a serious note actually the other day i was thinking it would be nice to port over the rat-king and his stinky of miasma to add some fun in maints...
> 
> Can't there be a way to fix that? It's not like we have an on-going meta of miasma farms EVERY round, we had a couple of weeks like that a year ago but nowadays i barely see it tbh, how did TG handle the ''miasma=lag'' issue? considering they have stuff like Rat king and so on.

they didnt. tg runs like shit and part of the reason is their refusal to drop their terrible bloat mechanics

**Review by francinum — APPROVED** [review]

**Comment by nednaZ** [comment]
One "sub-feature" that will be lost by hard removing miasma is the ability to smell a corpse in a room, leading players to find a hidden body due to the rot.

**Comment by KoboldCommando** [comment]
> > Why not find a more efficient and/or simpler way to calculate rot? I'm sure there are ways you can check for rotting gibs and corpses and create miasma with less performance demand. That and a price adjustment seems like it would achieve what you're doing here without removing mechanics from the game.
> > This approach removes motivation for people to take care of corpses and gibs, so I would expect them to start simply allowing them to rot in the hallways. It also removes a lot of vectors for disease making the virologist's already debatable supportive duties even less wanted and making general station health easier to maintain and less unpredictable. It seems like an overall negative to me, even if it comes with a performance improvement.
> 
> I guarantee people will clean up corpses. Bay doesn't have miasma and people on bayforks clean up corpses.
> 
> We have failed as a roleplay server if there needs to be a mechanical reason to not leave a dead body in the hallway.

I don't feel like you really addressed my points.  You expect players to carry on acting as if a mechanic exists even when it's removed, and you didn't mention the other points I made.  Plus, SS13 exists as a hybrid of roleplay and mechanics, both should encourage and reinforce one another, not work at odds or in isolation.

Here's a spitball alternative concept: remove most/all processing from the rot component, leave the component or create a global list of "rottables".  And process miasma production as an atmos reaction.  A turf with rottables converts oxygen to miasma.  At an initially very low amount but heavily catalyzed by the number of rottables and the amount of miasma.  Creating the same effect of ramping rot but without having to have every single chunk process something constantly.  Making morgues chilled would both inhibit the reaction and also be rather realistic.

Not sure why outright removal is being treated as the only possible solution to this, or why the multiple negative impacts it would have are being dismissed without discussion.

Improve don't remove, unironically.

**Comment by Archanial** [comment]
🎊

**Comment by mcmeiler** [comment]
Was about time.

**Comment by BrumalLake** [comment]
be real who has ever thought about maisma when cleaning especially new players who are slaves to the hegemony that janitor is for them while knowing nothing about miasma
if td actually goes down significantly that'd be nice
suggested idea above is wrong claiming all turfs have to process constantly

**Comment by MCterra10** [comment]
oh boy here comes kapu with another pointless change that just gives the feel-good vibes of "improving" the codebase quality when in reality it just rips out a feature for little benefit

do you have any actual hard numbers to back up your "lag" argument?

**Comment by Sinestia** [comment]
image
a ghost has left us his blessing. Praise be. 


This proc seems laggy on principle but yeah, that should be provable.

 Provide a simple map-based benchmark to prove it perhaps? Shouldn't take too long.

**Comment by ivanmixo** [comment]
Are we genuinely arguing people cleaned up corpses and gibs because of the miasma they made and not because it's messy/ugly? :3c

**Comment by Sinestia** [comment]
Also, is killing miasma as a whole necessary?

 Actual flower miasma farms take enough effort and don't spit out unnerfable amounts of money. 

 It's very niche but so are a lot of gases.

**Comment by Archanial** [comment]
This is your chance improve gang.
Propose better solution in pr.

**Comment by PowerfulBacon** [comment]
I feel like the argument of simply existing in the life loop isn't particularly strong when its only 1 of many gasses in it and it only actually does anything if there is miasma in the air (except from the clearing moods every life() it isn't which is just bad but extremely easy to optimise with 1 or 2 lines at most). I also feel like you put a lot more emphasis on how expensive life is than it actually is in reality, and even if it was removing this would have a very small impact.

> balance: Atmosbot EMAG now generates CO2

Make it do plasma or something funny, CO2 is pointless.

I agree with MCTerra that if you are going to use performance as a reason to do a change, you should either provide a clear indication of what specifically is causing performance issues and how your changes resolve that, or provide actual tests showing an improvement in a non-biased environment. Split the life() components down into its own procs and see how long it takes to execute each part, I highly doubt the changes made here will have much effect.

The point for miasma making too much money is a valid argument, however I don't see it being strong enough to completely remove miasma, rotting and corpseflowers when removing miasma from being sellable, reducing the price or making the price dynamic would achieve the same result with less impact. Also would prefer to see some evidence backing up the fact that corpse flowers are causing lag as a result of atmos updates if its being used as an execuse to remove them.

**Comment by francinum** [comment]
Sufficient justification here is that even TG managed to get their act together enough to purge miasma, at the very least from corpses and gibs. On similar grounds.
https://github.com/tgstation/tgstation/pull/57957

**Comment by MCterra10** [comment]
> 

This means nothing, tg are dumbasses with an incredibly unbalanced and shitty codebase, filled with tgui bloat

**Comment by ike709** [comment]
My only complaint is that the atmosbot emag is lame.

**Comment by PowerfulBacon** [comment]
> My only complaint is that the atmosbot emag is lame.

I agree, I totally approve these things starting plasma fires so they are actually dangerous

**Comment by francinum** [comment]
> > 
> 
> This means nothing, tg are dumbasses with an incredibly unbalanced and shitty codebase, filled with tgui bloat

Isn't that my line?

**Comment by Sapfearon** [comment]
"corpse plant farm is easy to make" No it's fucking not? You literally need competent botany and help/access to engineering and atmos to make it.  How often you see corpse plant farms at all? 1 per 2 months?

**Review by Archanial — APPROVED** [review]

**Comment by utilbird** [comment]
Thank you kapu, very cool!

**Pull request merged**
