### PR TITLE
Optimises /datum/gas_mixture/copy_from_turf

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Updates copy_from_turf so that instead of using the expensive parse_gas_string method, it instead creates a gas template from the string and copies that using the much faster rust_g implementation of copy_from.

This isn't going to make an enourmous impact, especially if you have a fast PC, but it is an improvement none the less.

## Why It's Good For The Game

**Previous:**
image
As you can see, the majority of CPU usage on this proc was from child calls, which was the call to parse_gas_string.
image

This call is very expensive. With the new method, the profile looks like this:
image
It is more expensive if we don't consider the child calls as we are doing more work inside the proc, however we avoid calls to the very expensive gas parse proc so the overall total CPU usage is lower.

Master initialisation took a total of 69.922 CPU, this new copy_from_turf implementation saves around 1 total CPU.

image

image

Note that self CPU should be consistent across both of these as nothing specific to it has changed. That means for whatever reason, or due to slight inaccuracies, my computer was running slower in the second example however we still observe a non-insignificant improvement.

## Testing Photographs and Procedure

image

image

image

## Changelog
:cl:
tweak: Optimises copy_from_turf to use the faster rust_g implementation of copy_from. This should slightly improve initialisation times of open turfs.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
image
Verification that the method is working as intended

**Review by Crossedfall — APPROVED** [review]

**Comment by Crossedfall** [comment]
Worth noting the `copy_from` is an auxmos hook, not from rust_g.

**Comment by PowerfulBacon** [comment]
Ah whoops, thats what I meant

**Comment by itsmeow** [comment]
It might be worthwhile taking TG changes here instead
image
https://github.com/tgstation/tgstation/pull/69697/files#diff-9c1990cc53ae34f2f9f6b72f7fd76164b3b4a408ca7f271bd275c0f2bdddb71b

They also moved parse_gas_string to SSair which caches the results.

**Comment by PowerfulBacon** [comment]
The rust g parse is probably faster than can be coded in byond.
I'm not even sure this is faster with the removed double of this proc

**Pull request closed without merging**
