### PR TITLE
New advances in trash-disposaling efficiency: a janitorial blob strain (#43958)

### PR DESCRIPTION
**Pull request by Cenrus**
https://github.com/tgstation/tgstation/pull/43958

## About The Pull Request

This PR adds a new blob strain into the game that mainly eats garbage and spits it out when attacking. I have some ideas on how to expand on this but I don't know how strong the current mechanic is, so I'm opening the PR up for comments.
## Why It's Good For The Game

More blob strains = More better
## Changelog

:cl: Naksu
add: Added a new blob strain that grows inside the station and eats garbage
/:cl:

### CODE REVIEW

**Comment by grimmmy** [comment]
I'm the Trash Man! I come out, I throw trash all over the- all over the ring! And then I start eatin' garbage!

**Comment by hackerjsimon** [comment]
is this gonna function like the circuit thrower where it throw like 40 items at once if so make it selectable where u can throw 1 or all items.

**Comment by Angustmeta** [comment]
This blob strain has been broken on tg since implemented:
tgstation/tgstation#44414

Unless it was fixed without me noticing.

**Comment by Cenrus** [comment]
Thanks for the heads up. I did a brief test and it seemed fine but I'll check for any more follow up PRs.

DNM for now.

**Comment by ike709** [comment]
Status on this?

**Comment by Cenrus** [comment]
seems to be broken, and I can't find a fix. close this if you want to.

**Pull request closed without merging**
