### PR TITLE
Replace "Red Dead Redemption Two" and "Yanye Kest" from clown random name gen.

### PR DESCRIPTION
**Pull request by MatiAvanti**
Replace "Red Dead Redemption Two" and "Yanye Kest" with "Bonkers" and "John Nanotrasen"

## About The Pull Request

Red Dead Redemption 2 and Yanye Kest is removed from clowns random name generator.

## Why It's Good For The Game

RP and shit I guess.

</details>

## Changelog
:cl:
config: Replace "Red Dead Redemption Two" and "Yanye Kest" with "Bonkers" and "John Nanotrasen"
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
The changelog doesn't need to be doubled up. Just mark it as config:, add:, or delete:

**Comment by ClownMoff** [comment]
We cant have nice things

**Review by Rukofamicom — APPROVED** [review]

**Review by PowerfulBacon — APPROVED** [review]

**Comment by Hardly3D** [comment]
Soul is gone, millions must kill clowns.

**Review by itsmeow — APPROVED** [review]
Looks good to me

**Pull request merged**
