### PR TITLE
hahelamo

### PR DESCRIPTION
**Pull request by ghost**
cat girls are bad mnnnnnnnky

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
this es co0l

**Comment by St0rmC4st3r** [comment]
Mate, make a proper description and people will vote for this bloody thing!

**Review by MarkSuckerberg — CHANGES_REQUESTED** [review]
get icons for it and I mean people would vote for this legit

**Comment by ghost** [comment]
i wasnt sober when I wrote this but i am now so heres the gist

its a belt

that holds heads

a trophy belt.

Traitors can buy it for like 7, changing it to 10, tc and it looks like a normal belt, but can only hold 3 severed heads. Nothing else.

**Comment by qwertyquerty** [comment]
What's the point though

**Comment by ghost** [comment]
its under pointless badassery in the uplink for a reason qwerty

**Comment by Crossedfall** [comment]
If this is still being considered, can the description be updated to follow our standard format please?

**Comment by ike709** [comment]
Stale.

**Comment by ike709** [comment]
Very stale.

**Pull request closed without merging**
