### PR TITLE
+1 GBP

### PR DESCRIPTION
**Pull request by Kapu1178**
## About The Pull Request

[19:24:57] Skipped 531168 runtimes in human_movement.dm,46.

## Why It's Good For The Game
531168 less potential runtimes

## Changelog
:cl:
code: adds a dna check to human/move() to prevent 531168 runtimes
/:cl:

### CODE REVIEW

**Comment by GregTheEgg42069** [comment]
ML60

**Comment by Archanial** [comment]
obraz

**Comment by PowerfulBacon** [comment]
mate why is there a human without dna in the first place pain

**Comment by KubeRoot** [comment]
This is hiding an issue instead of removing it; if humans should always have dna, this just makes it harder to spot when a human is in an obviously bad state by removing an indication that something's wrong.

**Comment by ike709** [comment]
We should investigate how you can have a human without DNA, but also runtimes have a performance cost and this is... quite a lot of runtimes.

**Pull request merged**
