### PR TITLE
Mobility Atomization 2: Incapacitation

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports:
- https://github.com/tgstation/tgstation/pull/50270
- https://github.com/tgstation/tgstation/pull/50321
- https://github.com/tgstation/tgstation/pull/50327

## About The Pull Request

atomization of #8965 

Turns incapacitation into a status effect. Includes clean ups from subsequent 2 prs.

`check_immobilized` is removed, as it is unused in code.

The trait will be applied only during incapacitations like stuns, unconciousness, or paralyzing, the same behavior as before.

## Why It's Good For The Game
Simplifies checks by turning long procs into traits. Moves to making mobility more event based

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Disabler incapacitating someone due to stamcrit. The stamina damage calls the incapacitation status effect and applies the trait.

`/mob/living/incapacitated` remains valid so long as the trait is applied

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/ddb8e80a-683a-42f6-a0f3-7cf15e20b5e1

Lol, get incapacitated, nerd.

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/5ee07fae-e6f6-4009-9735-5e068a8b0eda

</details>

## Changelog
:cl: RKz, Rohesie, Cobby
refactor: makes incapacitation into a trait
/:cl:

### CODE REVIEW

**Review by itsmeow — APPROVED** [review]
Niiice

**Comment by itsmeow** [comment]
your commits are name wrong

**Comment by Tsar-Salat** [comment]
> Niiice

Bro let me test it first

I dun want this shit to break

😭

**Comment by itsmeow** [comment]
I didnt merge it

**Comment by Tsar-Salat** [comment]
amended commit message to be the correct one

**Review by itsmeow — APPROVED** [review]
yolo (ill just revert it if it breaks, or let you make a fix :3)

**Pull request merged**
