### PR TITLE
Removes C*der

### PR DESCRIPTION
**Pull request by utilbird**
## About The Pull Request

The in game rank for maintainers refers to them as mere c\*ders, changes it to "C*de Maintainer"

(because according to our marketing team, "High Overseer" was too condescending)

## Why It's Good For The Game

More diplomatic power for me, more review rations for thee

## Changelog
:cl:
config: renames "coder" rank to "code maintainer"
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
should rename it to professional femboy

**Comment by ItsTisme** [comment]
Maby keep it so you can temp give coder role to coders who test merged certain code that needs debugging

**Comment by PowerfulBacon** [comment]
We already have maintainer as a role. This file is more of an example. Changes to the thing should be made through the actual proper role management thing rather than on the repo.
Will this break the system for anyone who has the coder rank atm if its not renamed through proper means (permissions panel)?

**Comment by francinum** [comment]
This PR is meaningless.

**Pull request closed without merging**
