### PR TITLE
Slight changes to retro theme

### PR DESCRIPTION
**Pull request by imsynthex**
## About The Pull Request

Title

## Why It's Good For The Game

The retro theme is outdated, some buttons are the wrong size

## Changelog
:cl:
fix: Fixed some of the retro theme's icons to fit
imageadd: Changed some of the retro theme's icons
/:cl:

### CODE REVIEW

**Comment by KubeRoot** [comment]
I'm not sure about making changes to the retro theme - isn't it supposed to be the original look of SS13? (This isn't a rhetorical question either, I'm genuinely not sure, but it definitely resembles the classic soul)

**Comment by imsynthex** [comment]
I thought that too initially, but the icons have already been changed around to match the other themes, and besides, I didn't change the color palette or the action buttons, just made it more usable and _slightly_ more uniform with the other themes

**Comment by BrumalLake** [comment]
why did some have 4 states

**Comment by francinum** [comment]
Gonna need pics

**Comment by ike709** [comment]
> Before you ask about what the 2 new themes are, I don't know

If you don't actually know how you're going to finish this PR then can you just do them in a follow-up PR instead?

**Comment by imsynthex** [comment]
Probably a better idea, will remove it from this PR

**Comment by francinum** [comment]
IIRC it was intended to be the original design, but minor tweaks in the interest of making it actually usable, namely fixing the fact that it's the only theme with cutout icons, makes sense.

**Comment by imsynthex** [comment]
Okay, so the first time around I didn't notice that I had left in segmented intent icon code, removed that now and tested it, works as intended

**Comment by PowerfulBacon** [comment]
Does this remove the 4 buttons on all other themes and make it only a single button?

**Comment by imsynthex** [comment]
Yes, and if you click that single button, it cycles intents

**Comment by PowerfulBacon** [comment]
thats kind of annoying, most likely the reason it was removed in the first place.

**Comment by imsynthex** [comment]
What's annoying about it? The quadrant intent wheel's icons are so small it'd probably just be faster to have it cycle intents anyway

**Comment by ike709** [comment]
Keep the quadrant intents

**Comment by imsynthex** [comment]
Alright, removed all the intent icon changes, should be good to go now

This is how the retro theme looks now:
image

**Review by Archanial — APPROVED** [review]

**Pull request merged**
