### PR TITLE
fixes a bug i didnt know about for like 2 bloody months

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request

do_mob on legion cores now does something
## Why It's Good For The Game

YOU GUYS SUCK AT REPORTING BUGS

## Changelog
:cl:
fix: legion cores no longer apply if you fail the do_mob
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — COMMENTED** [review]
If you cancel the heal isn't this going to qdel(src) and add the mood effect anyway?

**Comment by zeskorion** [comment]
> If you cancel the heal isn't this going to qdel(src) and add the mood effect anyway?

one sec

**Comment by zeskorion** [comment]
> If you cancel the heal isn't this going to qdel(src) and add the mood effect anyway?

done

**Review by PowerfulBacon — APPROVED** [review]

**Review by PowerfulBacon — COMMENTED** [review]
Hang on I noticed something I want to test

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
