### PR TITLE
Makes the exploration HUD icon less bad

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request
simply changes the previous exploration crew hud icon from a weird green-blue "E x" into a purple magnifying glass

## Why It's Good For The Game
because the old one looked pretty shit

## Changelog
:cl: Bluezorua
imagedel: old exploration crew hud icon
imageadd: new exploration crew hud icon
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
picture

**Comment by ToasterBan** [comment]
> picture

just use the icon dif bot, it's just the dets HUD icon but with sci colours

**Comment by Raven-Industries** [comment]
It looks a bit too similar to the search status with sechuds.

**Comment by BrumalLake** [comment]
> 
> 
> It looks a bit too similar to the search status with sechuds.

the way it was meant to be, got my envirosuit taken off by sec yesterday for joking that i was a nukie while pulling the nuke into the bridge looking for the code with someone

**Comment by PowerfulBacon** [comment]
Looks better before imo

**Comment by ike709** [comment]
🔑 
Downgrade

**Comment by mcmeiler** [comment]
> 
> 
> It looks a bit too similar to the search status with sechuds.

I second this.

**Comment by PowerfulBacon** [comment]
I agree with Ike.

**Pull request closed without merging**
