### PR TITLE
Room templates

### PR DESCRIPTION
**Pull request by ike709**
## About The Pull Request

Adds the ability to load room templates. Currently this is pretty limited because my understanding of the map loader is pretty limited. Ideally in the future this would also support directional loading, and template sizes wouldn't be hardcoded subtypes. But I'm sleepy so this is all you get.

Includes two examples, the room spawner isn't mapped in though.

## Why It's Good For The Game

Random map rooms.

## Changelog
:cl: Robustin, ported and modified by ike709
add: Added the ability to load room templates. Not currently utilized by any map.
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Awesome. How do we utilize this?

**Comment by qwertyquerty** [comment]
"Five-by-Four" delet dis

**Comment by qwertyquerty** [comment]
Travis dide

**Comment by qwertyquerty** [comment]
Also github is kinda dead right now too, I have to reload to see my comments after I post them. Cringe cringe

**Comment by qwertyquerty** [comment]
These aren't used in any current maps right?

**Comment by ike709** [comment]
Correct. Mappers haven't done anything with them yet.

**Pull request merged**
