### PR TITLE
Halves the time needed to open firelocks

### PR DESCRIPTION
**Pull request by Hardly3D**
## About The Pull Request
This PR halves the time needed to open firelocks with a crowbar from 10 seconds to 5, making them a reliable option again rather than pressing fire alarms to deactivate them.

## Why It's Good For The Game

Firelocks currently takes ages to pry open and is currently unreliable, it is twice as long compared to prying open a door with a jaw of life and can be longer depending on how bad the lag is.

While you can open firelocks with an ID, that won't work with these that has a pressure alarm or access required and you'll likely be dead before you can get a firelock open within 10 seconds in case there's actually a fire, or something hostile.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: Hardly
tweak: Halved the time needed to open firelocks from 10 seconds to 5.
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
>While you can open firelocks with an ID, that won't work with these that has a pressure alarm or access required and you'll likely be dead before you can get a firelock open within 10 seconds in case there's actually a fire, or something hostile.

That's the point.

**Comment by EvilDragonfiend** [comment]
I am fine they take ages to open. It's annoying they're instantly closed.

**Comment by Tsar-Salat** [comment]
> That's the point.

The point is irrelevant when its easier to disengage the fire alarm and open ALL of the hallway to the hazard rather than open one. 

9 times out of 10 that person is going to value their own life over the consequences of opening all the doors.

**Comment by francinum** [comment]
> > That's the point.
> 
> The point is irrelevant when its easier to disengage the fire alarm and open ALL of the hallway to the hazard rather than open one.
> 
> 9 times out of 10 that person is going to value their own life over the consequences of opening all the doors.

And anyone doing that is well within the rights to have the shit beat out of them by the engineering department for violating damage control.

I have no horse in this race anymore, but I coded this and I'll be frank about the design behind this change.

Individual players can be cloned or stabilized after getting dragged out by engineering, and are infinitely easier to fix than station damage.

The crux of your complaint is that the doors are doing their job. Containing the problem.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
Do the testing part of the PR body

**Comment by Rukofamicom** [comment]
Please don't merge this, this is fine.

**Comment by Sapfearon** [comment]
honestly most other servers have little to no delay on opening firelocks so i kinda agree with this.
right now firelocks are here to kill you instead of saving - not to mention moment when you pry firelock off only for it to instantly lower itself again. Fastmos airlocks were actually 10 times better then what we have now.

**Pull request closed without merging**
