### PR TITLE
Map QoL: Round 3

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Fixes some problems with Metastation and Deltastation.

Meta:

- Fixed some dead-end piping caused by random maints
- Removed maint-only APC's, in keeping with boxstation
- Moved Medbay deliveries closer to cryo as random maint will bug a mule
- Fixed two disposals in Medbay
- Medbay areas now consolidated so there needn't be 8 apcs and air alarms
- Added decals around the map
- Sec gains new tiling + new emergency shower
- Fixed the bugged nav beacons in engi hall which were causing bots to get stuck

Delta:

- Chemistry equip moved slightly to fix the fridge being bugged
- Removed maint-only APC's
- Added some decals
- Rotated ORM so it now properly accepts input
- Moved SM piping around slightly
- SM emitter room now works without needing shuffling
- Moved items (like plants) that were sitting on the same tile as supply consoles, which were hastily added in a previous PR

## Why It's Good For The Game
Map QoL tweaks to make life in space a little less tedious and more visually appealing for you to bleed on while you're being mauled by an assistant

## Changelog
:cl:
add: Meta+Delta: New decals, tiling
del: Meta+Delta: Maintenance APC's removed 
fix: Metastation: 2x Disposals fixed
fix: Metastation: Bots no longer get stuck in engi hall
fix: Metastation: Deliveries to medbay no longer glitch
fix: Deltastation: Chemistry fridge fixed, couldn't access it without opening windoor previously
fix: Deltastation: ORM fixed
tweak: Deltastation: SM no longer requires reflectors to be moved before starting
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
Note that many airvents were kept in random maint due to xeno spawns

**Comment by jlsnow301** [comment]
> Note that many airvents were kept in random maint due to xeno spawns

o
edit: this next commit means I readded the piping that were there for benos

**Comment by jlsnow301** [comment]
Okay what the FUCK is that error

**Comment by KingTerrytheTerrible** [comment]
You're fine, random maints just caused a runtime or two. We really need to make the seed static for Travis

**Comment by ike709** [comment]
@zeskorion You're our most qualified mapper at the moment, so have fun reviewing this.

**Comment by ike709** [comment]
> Added decals around the map

*How many decals?*

**Comment by jlsnow301** [comment]
> _How many decals?_

Both meta and delta already have this styling so probably 10 each, if I forgot a trash bin or moved a door etc

**Comment by zeskorion** [comment]
> @zeskorion You're our most qualified mapper at the moment, so have fun reviewing this.

...this fact is frightening

**Comment by ike709** [comment]
DNM pending a big incoming mapping PR.

**Pull request closed without merging**
