### PR TITLE
Increases the rate at which welders burn fuel

### PR DESCRIPTION
**Pull request by yyzsong**
## About The Pull Request
Did you know it took 24 seconds to take one unit of fuel from a welder? Fucking wild.
Decreases this time to nine seconds, which means a standard welder can burn for three minutes straight.

## Why It's Good For The Game
Muh welding fuel economy. Plus it gives advanced welders a greater use.

## Changelog
:cl:
balance: Welders now burn through one unit of fuel per nine seconds, down from twenty-four.
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
balancing something that doesn't need to be balanced
your cl doesn't match

**Comment by yyzsong** [comment]
> your cl doesn't match

Fixed CL

**Comment by MNarath1** [comment]
So basically you nerf welder so that your welderfuel backpack PR makes any sense at all?
Well at least we get a stealth blob buff i guess.

**Comment by Absolutely-Steph** [comment]
I like this, I dislike the backpack. I am always in favour of limiting available supplies.
Scarcity is good.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
