### PR TITLE
New admin only gamemode: traitorchan with no protected roles

### PR DESCRIPTION
**Pull request by Cenrus**
:cl:
add: new admin only gamemode where anyone can be a traitor/changeling.
/:cl:

### CODE REVIEW

**Comment by Moccha-Bee** [comment]
bro the admins are going to aboose it....

**Comment by ike709** [comment]
Not a fan, personally.

**Comment by honkhonkclown** [comment]
>traitorling captain
oh god oh fuck

**Comment by Cenrus** [comment]
This might have been a huge mistake.

**Comment by hackerjsimon** [comment]
make a wizard ops a gamemode no tc just spellbooks

**Comment by eLeCtrOssSnake** [comment]
@ike709 Agree

**Comment by ike709** [comment]
The people have spoken, and welcome the adminbus.

**Pull request merged**
