### PR TITLE
Bluespace Satchels collect ores in a wider range

### PR DESCRIPTION
**Pull request by Shiraizawa**
## About The Pull Request

Added a feature for bluespace satchels to grab ores around the tile the player steps in. Can be varified by changing bs_range (1 by default).

Also changed how messages are handled when scopping up ores from both perspectives.

## Why It's Good For The Game

Makes strip-mining with a drill/pickaxe much better by not requiring you to move up a tile, down two, then up one when you are mining 3 columns.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
https://youtu.be/P03JxG3RHM0

</details>

## Changelog
:cl:
add: Added a feature for bluespace satchels to collect ore in a wider range
add: Bluespace satchels now collect ore around you as well as below you
/:cl:

### CODE REVIEW

**Comment by Nakalon** [comment]
Extremely based

**Review by EvilDragonfiend — DISMISSED** [review]
this is a bit expensive logic. AoE collection should be only doen when storing ores happened, instead of checking 9 tiles for every movement.

**Comment by MarkusLarsson421** [comment]
Perhaps the mech ore collection, does it better? If not, it should probably also be improved.

**Review by Shiraizawa — COMMENTED** [review]
Mech ore collection DOES make it better. Ill switch to that instead of checking a bunch of tiles on every move

**Review by Shiraizawa — COMMENTED** [review]
oh now that I thought about it, it handles the same but instead of orange it uses just range

**Review by Shiraizawa — COMMENTED** [review]
Now it should do a lot less calculations because it doesnt check for every item in a turf, only handles obj/item/stack/ore objects.
Also doesnt bother to try and put stuff in the satchels if they were already put in an ore box

**Comment by Shiraizawa** [comment]
> this is a bit expensive logic. AoE collection should be only doen when storing ores happened, instead of checking 9 tiles for every movement.

Now i have some time to write down why that's an issue: 

Let's say you are standing in the cartesian coordinate (1;1) and there are ores around you at (0;0),(0;2),(2;0) and (2;2), so diagonal tiles from you.
Towards which cardinal direction do you step collect any ores? You can pick any, no ores will be collected sunce those tiles were empty, even though there are ores right next to you at this point.


You are strip-mining with a diamond drill in either cardinal direction by clicking on the tiles ahead of you and right besides that tile clearing 3 tiles per movement, but there are 0 ores in the middle column/row in the direction you are mining in. This results in you constantly either leaving all the ores behind or having to step out of the middle column/row to collect the ore. This is already what you do with normal ore satchels. 

I could limit this to only check for the tile you are moving to and directly adjacent tiles, but that would still mean id have to check the direction the player moved to every time the player moves.

**Review by Rukofamicom — APPROVED** [review]
Power creep moment, but I don't think this is negative overall. 

It'll be helpful for AoE mining mods on PKA too.

**Pull request merged**
