### PR TITLE
WIP New surgery, Blood Filtering

### PR DESCRIPTION
**Pull request by Chessus**
## About The Pull Request
This WIP pr ports the Blood filtering surgery and the Blood filter from [#pr53228](https://github.com/tgstation/tgstation/pull/53228).  All sprites belong to the creator of them from the previous pr.
- [x] Add blood filter to maps :
- [x] Adds blood filter to medical toolbelts and kit from [pr53442](https://github.com/tgstation/tgstation/pull/53442):
- [ ] Makes it so surgery can not be performed when no regeants are present or on husks:
- [ ] Make it similar to Tend owunds whereby it is automatically repeatble :  
 

## Why It's Good For The Game

Currently the only way to remove reagents from a player is through chemicals. This pr makes it so you use the Blood filter during Filter Blood surgery remove reagents. Each reagent is remove by reagentvolume*0.22 so large volumes will have more removed. 
 

## Changelog
:cl:
add: Filter Blood
add: Added more things
tweak: The blood filter can now be put in medical belts and medical aid kits
/:cl:

## WIP/Code not done

### CODE REVIEW

**Comment by r1ks-iwnl** [comment]
Good change, now you wont have to keep defibbing people so reagents slowly metabolise because you ran out of calomel from toxin kits and chemists are only making grenades.

**Comment by ghost** [comment]
why are you merging from your master

**Comment by Chessus** [comment]
> why are you merging from your master

I don't know, it's my first time trying it from git desktop and it's gotten me this far ha. If I don't change my current master, will it be okay?

> Good change, now you wont have to keep defibbing people so reagents slowly metabolise because you ran out of calomel from toxin kits and chemists are only making grenades.

Yeah mate, I'm all for chemistry analogues and it removes the reliance on those meth cooks

**Comment by ghost** [comment]
> > why are you merging from your master
>  I don't know, it's my first time trying it from git desktop and it's gotten me this far ha. If I don't change my current master, will it be okay?

normally you don't touch your master besides from pulling from your upstream and creating branches where you should normally do your stuff.

there is nothing inherently wrong with merging from your master but it's gonna be a massive pain in the ass to maintain for yourself

**Comment by Chessus** [comment]
Dun goofed, won't merge from master

**Pull request closed without merging**
