### PR TITLE
Fixes Mask of Madness recipe 

### PR DESCRIPTION
**Pull request by yyzsong**
## About The Pull Request
See title

Mask of madness recipe was supposed to be [Mask + Candle + eyes]
but the guy who changed it from curse of blindness forgot to change the recipe!!!
so it's [Blood + Eye + Screwdriver]

## Why It's Good For The Game
fixes a bug

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.
image
image
image

</details>

## Changelog
:cl:
fix: Fixes mask of madness recipe
/:cl:

### CODE REVIEW

**Comment by Rukofamicom** [comment]
You should post testing screenshots and/or videos to prove this functions or this may be rejected or closed.

(I know it's a minor thing, but these keeps happening with seemingly minor fixes not even being tried once and then breaking things)

**Comment by PowerfulBacon** [comment]
Do the recipes accept subtypes?

**Comment by yyzsong** [comment]
> Do the recipes accept subtypes?

I believe it does, yeah

**Comment by yyzsong** [comment]
I added some screenshots of some tests I did, if that's what you're looking for. It does work.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
