### PR TITLE
Nerf hierophant melee facetank

### PR DESCRIPTION
**Pull request by Sinestia**
## About The Pull Request
https://github.com/tgstation/tgstation/pull/50857
port 

## Why It's Good For The Game
just facetank it lol

## Changelog
:cl:froststahr
tweak: Hiero no longer skips its main attack if you're in melee range
/:cl:

### CODE REVIEW

**Comment by hotimep** [comment]
im still going to facetank it

**Comment by ghost** [comment]
Unbased

**Comment by Sinestia** [comment]
> 
> 
> Unbased

im not the one defending a crutch oversight

**Comment by NickEmbased** [comment]
based :+1:

**Comment by PowerfulBacon** [comment]
Cool, hierophant is way too easy

**Review by ghost — APPROVED** [review]

**Comment by Goblinu** [comment]
finally, now reduce its cooldowns by half

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
