### PR TITLE
Status Subsystem

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
Adds Status subsystem - AKA buff & debuff subsystem

## Why It's Good For The Game
Managing everything your temporary condition by ADD_TIMER() is disrupting to code most things
also, when you need to remove something in specific time, it makes us feel bad to code because ADD_TIMER() is necessary.
This will make things better.

currently there's a sample code for how to heal.
If I suggest another example,
`on_add()` can give you a trait, and `on_remove()` can take the trait upon its expiration.

`atom_list` list structure seems to be complicated, but there are many reasons why it is made as so.
1. It doesn't make every type. individual information is stored in list() - saves type memory because you don't make `/datum` type with unnecessary variables
2. you can put customisable variables by doing like `data["something special"]`. 
3. It can handle multiple atom types in a single system (THIS can be expanded to handling datum as well, but I don't see any precise case to handle datum yet... but changing it will be easy.)

note: I am not sure which one is best between using SSprocessing and Fire()

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

this is sample chemical
if you drink this, you get 15 seconds buff for each metabolisation

image

this is the buff code

image

MC works fine

image
image
image

healing is fine

</details>

## Changelog
:cl:
add: Added Status subsystem
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
This is currently not the final version. It is posted to show maintainers how it works.
(90% made)

**Comment by PowerfulBacon** [comment]
> Managing everything your temporary condition by ADD_TIMER() is disrupting to code most things
also, when you need to remove something in specific time, it makes us feel bad to code because ADD_TIMER() is necessary.
This will make things better.

Could you elaborate on this? Wanting to understand the purpose for the implementation to think about the best way of doing this

**Comment by EvilDragonfiend** [comment]
> > Managing everything your temporary condition by ADD_TIMER() is disrupting to code most things
> > also, when you need to remove something in specific time, it makes us feel bad to code because ADD_TIMER() is necessary.
> > This will make things better.
> 
> Could you elaborate on this? Wanting to understand the purpose for the implementation to think about the best way of doing this

This is an example of a (not existing) botany code to give you a temporary bluespace teleport protection:

```
/datum/plant_gene/trait/teleport/proc/activate_effect
	if(HAS_TRAIT(L, TRAIT_BOTANY_IMMUNE_TELE))
		return
	ADD_TRAIT(L, TRAIT_BOTANY_IMMUNE_TELE, TRAIT_GENERIC)
	addtimer(CALLBACK(src, .proc/handle_mob_trait, L), 30 SECONDS)
	teleport_mob(L)

/datum/plant_gene/trait/teleport/proc/handle_mob_trait(mob/living/L)
	REMOVE_TRAIT(L, TRAIT_BOTANY_IMMUNE_TELE, TRAIT_GENERIC)
```

like this, having temporary status should be done like this weird way. I wanted something that can handle temporary stuff generally.

**Comment by EvilDragonfiend** [comment]
also, the issue of add timer thing is that you can't adjust its timer while it's on already.
this can change its timer.
```
var/instance = SSstatus.grab_status_instance(victim, /datum/atom_status/bluespace_protection)
instance["duration"] -= 5 // additional attack will shortens its duration.
```

**Comment by ivanmixo** [comment]
Why does this need to be a subsystem instead of a few extra vars/procs on atom? Seems youre offloading all the work onto `ssprocessing` anyways so what gives?

**Comment by EvilDragonfiend** [comment]
> Why does this need to be a subsystem instead of a few extra vars/procs on atom? Seems youre offloading all the work onto `ssprocessing` anyways so what gives?

like I said yesterday, It's not appreciated to add new vars/proc on atom usually (and this can be used to datum actually)
and yes, it might be supposed to not be mixed with SSprocessing, and should be fire() thing, but I wasn't sure about those, so I just coded it anyway.

**Comment by ivanmixo** [comment]
> > Why does this need to be a subsystem instead of a few extra vars/procs on atom? Seems youre offloading all the work onto `ssprocessing` anyways so what gives?
> 
> like I said yesterday, It's not appreciated to add new vars/proc on atom usually (and this can be used to datum actually if I tweak it a little bit, but I see no actual usage to use it on datum but possible) and yes, it might be supposed to not be mixed with SSprocessing, and should have its own fire() thing, but I wasn't sure about those, so I just coded it anyway.

And as I said, I'm pretty sure adding stuff to atom is more tolerated than making a whole new subsystem.

**Comment by EvilDragonfiend** [comment]
I believe it fits a subsystem but I don't know the whole code well. maintainers will tell me their opinion.

**Comment by EvilDragonfiend** [comment]
since Bacon said having no runtime error would suck, I think making every key as DEFINE would work by standising those.
```
#define ST_KEY_DURATION "duration"
#define ST_KEY_PULSES "pulses"
#define ST_KEY_POWER "power"

data[ST_KEY_DURATION] -= delta_time
data[ST_KEY_PULSES] += 1
mob.adjust_brute(-data[ST_KEY_POWER])
```
like this. it would less cause errors that might overlook

**Comment by EvilDragonfiend** [comment]
turning to draft since it should be better in presentation...

**Comment by EvilDragonfiend** [comment]
closing right now. will open later

**Pull request closed without merging**
