### PR TITLE
Remove all var/ from proc definitions

### PR DESCRIPTION
**Pull request by KubeRoot**
## About The Pull Request

This is considered a hint from the language server/dreamchecker, and is thus included polluting the diagnostics with hundreds of hints.

This is pretty much the entire reason I decided to do this:

image

Done by repeatedly replacing `^((?:/\w+)+\([^\n]*)var/` with `\1` to remove the `var/`s.

## Why It's Good For The Game

Doesn't affect the game, is considered to be a minor code quality issue by the repository configuration.

## Changelog
:cl:
code: Purged var/ from proc definitions.
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
good thing you don't need all 3 code owners to approve now eh

**Comment by KubeRoot** [comment]
> good thing you don't need all 3 code owners to approve now eh

Honestly... Not my problem. I'll leave it to maintainers to decide if they want it and review the code. Worst case I'll have to redo the changes from master, which is really only a few minutes of work.

**Comment by ike709** [comment]
Honestly I personally *like* seeing `var/` in proc definitions, but I don't care enough either way if other maintainers want to merge this.

**Comment by Archanial** [comment]
> 
> 
> Honestly I personally _like_ seeing `var/` in proc definitions, but I don't care enough either way if other maintainers want to merge this.

It's picked up by spaceman

**Comment by ike709** [comment]
> It's picked up by spaceman

So disable it: https://github.com/SpaceManiac/SpacemanDMM/blob/master/CONFIGURING.md
```
[diagnostics]
var_in_proc_parameter = "off"
```

**Comment by ike709** [comment]
I'd like to clarify that I'm not saying we should close this PR and disable the lint, I'm saying that we have the option of either going with this PR or disabling the lint.

I am of the opinion that we should disable the lint, but I'm open to whatever the maintainer consensus is.

**Comment by Kapu1178** [comment]
I don't really know the implications of disabling the lint, but I for one find procs easier to work with with var in args. It also makes showing people how procs work easier.

**Comment by ike709** [comment]
The maintainers have decided that it would be better to disable the lint. Ideally in the future we'll modify the linter to have the option to complain when you _don't_ put `var/`.

I'll disable the lint myself probably tomorrow if nobody beats me to it.

**Pull request closed without merging**
