### PR TITLE
Adds New Barsign

### PR DESCRIPTION
**Pull request by Raven-Industries**
## About The Pull Request
This PR adds a single new bar sign option: "The Blue Note". 

## Why It's Good For The Game
While current bar signs offer a wide range of tonal variety to choose from, none of them quite fit the theme of numb despair,  despite regular opportunities for such an emotion within the average SS13 round. This hopefully fills that hole. 
<details>

<summary>Disclosure: the name is a reference.</summary>

https://github.com/user-attachments/assets/e8a5d2c7-f45c-461e-8e9e-b07b2e860823

</details>

## Testing Photographs and Procedure

<details>

<summary>Screenshots&Videos</summary>

evidence

bluenote

</details>

## Changelog
:cl: 
imageadd: added new bar signage
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
This looks like it will be really hard to read with any level of bloom enabled

**Comment by MarkusLarsson421** [comment]
Blue Oyster bar, when?

**Comment by ClownMoff** [comment]
Yeah the sprite is hard to read I cant even tell what it says from my phone

**Comment by Raven-Industries** [comment]
> This looks like it will be really hard to read with any level of bloom enabled

Here's what it looks like with in-game bloom set to 0% and 100%, respectively:
image

> Yeah the sprite is hard to read

As far as readability concerns, is it something like color or font size that seems to be the issue, or something else?

**Comment by MarkusLarsson421** [comment]
Colour I'd say, it is dark blue on black. They sort of blur together a tad too much.

**Comment by Raven-Industries** [comment]
I lightened the blue and the background, yea or nay?
<details>

<summary>Images</summary>

image
bluenote2

</details>

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
The contrast on the sign is too low. Notice how most neon lights are a bright white core with a coloured glow.

I'd also prefer if the name splits away from the reference a bit with some kind of space-twist.

**Comment by Raven-Industries** [comment]
Updated the colors to a higher-contrast version. Name is still the same because I couldn't think of anything to give it a space twist (open to suggestions if that's a non-negotiable). 
bluenote3

**Comment by ClownMoff** [comment]
> Updated the colors to a higher-contrast version. Name is still the same because I couldn't think of anything to give it a space twist (open to suggestions if that's a non-negotiable). bluenote3 [ bluenote3 ](https://private-user-images.githubusercontent.com/76715855/380004642-c0e44049-01f4-4f58-ac31-840807d4da80.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTI5NTEsIm5iZiI6MTcyOTg1MjY1MSwicGF0aCI6Ii83NjcxNTg1NS8zODAwMDQ2NDItYzBlNDQwNDktMDFmNC00ZjU4LWFjMzEtODQwODA3ZDRkYTgwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDEwMzczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyOTY5YjBhMDQ4NGEyZGExY2Q1M2M1MjllYzExZjE4NmI2ZjZiNWQ2ZGE5ZWM2NzhhYTczMWU1NTM4ZThjYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DDS9ywtmoHvIi0rIs5bedoN2eDaVhYrLmT96iECFiJk) [ ](https://private-user-images.githubusercontent.com/76715855/380004642-c0e44049-01f4-4f58-ac31-840807d4da80.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTI5NTEsIm5iZiI6MTcyOTg1MjY1MSwicGF0aCI6Ii83NjcxNTg1NS8zODAwMDQ2NDItYzBlNDQwNDktMDFmNC00ZjU4LWFjMzEtODQwODA3ZDRkYTgwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDEwMzczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyOTY5YjBhMDQ4NGEyZGExY2Q1M2M1MjllYzExZjE4NmI2ZjZiNWQ2ZGE5ZWM2NzhhYTczMWU1NTM4ZThjYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DDS9ywtmoHvIi0rIs5bedoN2eDaVhYrLmT96iECFiJk)

I would make it slightly faster I think the animation is too slow and not so fluid

**Comment by Raven-Industries** [comment]
Like so? I cut the times in half for the initial on-sequence. Timing ratio between frames is still the same though because it's meant to match the lengths of the respective notes. 
bluenote4

**Comment by ClownMoff** [comment]
That one looks good

**Review by PowerfulBacon — APPROVED** [review]
The original is a reference to jazz, so I can accept it making sense

**Pull request merged**
