### PR TITLE
Adds an evidence storage room to the Corg Brig + tweaks Brig Medical

### PR DESCRIPTION
**Pull request by Tyranicranger4**
## About The Pull Request
Adds an evidence storage room to the Corg Brig.
Modified the brig medical area to make more sense when taking the new evidence room into consideration.

Redo of #7697 but in a less shitty spot.

## Why It's Good For The Game
Security needs a place to store evidence.
Brig med adjustment is needed to create space for it.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

It exists.
</details>

## Changelog
:cl:
add: Adds an evidence storage room to the Corg Brig.
tweak: Redoes the Medical area in the Corg Brig to better accommodate the new evidence room.
/:cl:

### CODE REVIEW

**Comment by Tyranicranger4** [comment]
Probably should have made this a draft instead, still trying to make this right. Not sure if it's possible to change that now though.

**Comment by Tyranicranger4** [comment]
Lowkey forgot about this.

**Comment by Fronsis** [comment]
praying this gets in

**Review by PestoVerde322 — APPROVED** [review]
Everything good to go, the mapdiffbot may have marked the extended area for error.

**Pull request merged**
