### PR TITLE
Kilo Medbay Rework

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request

KiloStation Medbay rework. All areas have been updated to have a better use of the space. OG Kilo just have rooms weirdly shapend and oddly placed for the sake of it. This rework aims to get a cleaner, more satisfying layout while still keeping Kilos theme of being small and cramped

## Why It's Good For The Game

Because medbay people deserve better

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>
The things I point in the video were minor stuff I noticed that I already changed. Ready to pass review!

https://cdn.discordapp.com/attachments/590714573611597824/1167439370484195438/8mb.video-NJx-Y4h5VY2k.mp4?ex=654e21a3&is=653baca3&hm=89612121f510076b25a9776f845f96fc15c41f5ae9a1c6b9160bc8fc3bbb9272&

</details>

## Changelog
:cl: Varo
tweak: Reworks the lobby, changes the front desk position to where cloning was, moves genetics to the big monkey room, moves cloning where genetic was, adds a surgery room, reworks the CMO, storage and chemistry room, removes a big part of virology and places it all below chemistry, tweaks some maintenance areas 
/:cl:

### CODE REVIEW

**Review by spockye — CHANGES_REQUESTED** [review]
image

unconnected wires / missing wires / unconnected apc's

image

disposals fuckery

image

atmospherics fuckery

image

should be a wall here

image

corner windows are iffy

image

should be a wall here

image

viro area here / reinforced wall

image

wall decal

image

wall decal

image

decal weirdness

image

decals intended?

image

might be best to continue with showroom floors here

image

area weirdness

image

area weirdness

**Comment by BriggsIDP** [comment]
wall missing
image
image
news caster on wrong tile and off centre (a lot of wall mounts are)
image
lights on glass, and glass looking at wall. odd.
image
two air alarms and no fire alarm 
image
no intercom
image
you forgot these in maintance 
image
plating under glass 
image
not reinforced  
image
atmos issues:
image
image
image
image
image
image
image
missing node
image
image
image
non of the glass is electrified
image
image
image
circled disposal should go to space.

other then that it seems good! make sure to check the mapping debug in game and see if any apcs and stuff are broken

**Review by ClownMoff — COMMENTED** [review]
Thanks for the feedback! I changed it

**Comment by BriggsIDP** [comment]
image
this fire alarm can't be used
this apc is using the wrong type
image
these objects are inside the wall:
image
image
image
image
image
image
image
image
put a firealam here 
image
missing wall
image
intercom missing from these areas
image
image
image
image
missing wall safe 
image
i would add a maintance door here 
image
disposals loop has been broken, add pipeing here in blue to keep the loop going 
image
this area should look like this 
image
look needs connecting here, but also chem has no sorting pipe, the code for chem is "11"
image
this is still broken, but also both are under the table, please move
image
inside the door way still 
image
please connect these three together 
image
wire goes under table, please go under door
image
Cmo's and the sec post's glass is not electrified
image
do it like this 
image
 this area should be medbay lobby
image

image
all doors leading to maint should have areas that look like this for code reasons
image
other then that great job on the map it looks so much better!

**Comment by BriggsIDP** [comment]
need to run mapping debug testing in game: pipes, apcs, alarms ect before merging

**Review by Rukofamicom — DISMISSED** [review]
Update PR body with exactly what was changed and how, as well as the changelog. 

Your description says nothing.

**Comment by Rukofamicom** [comment]
> [ClownMoff](https://github.com/ClownMoff) requested review from [Rukofamicom](https://github.com/Rukofamicom) and [spockye](https://github.com/spockye) [15 hours ago](https://github.com/BeeStation/BeeStation-Hornet/pull/10080#event-10933551766)

Can't really review a PR with a merge conflict.

**Comment by ClownMoff** [comment]
@Rukofamicom No more merge problems

**Review by PestoVerde322 — COMMENTED** [review]
I'd add some extra grime (dirt and whatnot) to emulate the old version if it, but it seems good to go. Approved.

**Comment by ClownMoff** [comment]
bump

**Comment by ClownMoff** [comment]
bump

**Pull request closed without merging**
