### PR TITLE
Adds a new roundend sound

### PR DESCRIPTION
**Pull request by Kmc2000**
## About The Pull Request

We as a species are not ready for this roundend sound. Meet hot cross buns 2: better than ever.

Performed by myself and BadminJenkins

## Why It's Good For The Game

https://cdn.discordapp.com/attachments/610144699575173143/784795862190260234/hot_cross_buns.ogg

## Changelog
:cl: Kmc2000 with BadminJenkins
add: Added a new roundend sound
/:cl:

### CODE REVIEW

**Comment by SharkeeByond** [comment]
Overwhelmingly based.

**Review by francinum — APPROVED** [review]

**Comment by MitztheKat** [comment]
oh dear god that's loud
Maybe turn it down a bit and maybe crop it to just the hot cross buns part

**Comment by SharkeeByond** [comment]
> oh dear god that's loud
> Maybe turn it down a bit and maybe crop it to just the hot cross buns part

Heresy!

**Comment by theboy6545** [comment]
> oh dear god that's loud
> Maybe turn it down a bit and maybe crop it to just the hot cross buns part

Is that the one?

**Pull request merged**
