### PR TITLE
Crate animation fixes and refactoring

### PR DESCRIPTION
**Pull request by MNarath1**
## About The Pull Request

This is a follow up PR to https://github.com/BeeStation/BeeStation-Hornet/pull/2917 in this i refractor the animation code to use a spherical coordinate system and fix a small oversight of a crate sprite that caused a small but still existing visual bug where the icon on the electrical engineering crate was differently aligned during the animation and mirrored afterwards. https://streamable.com/oyn5my

## Why It's Good For The Game

small sprite fixes and better coordinate system for crate animation

## Changelog
:cl:
fix: fixes a back sprite icon that was not properly mirrored
fix: minecart beeing animated
refactor: refactored some code regarding the crate animation to use actual sphere coordinates instead
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
ITT: Ike pretends to remember geometry.

**Comment by MNarath1** [comment]
still got to fix something i found just now(i accidentally put the 3 axis into the wrong spot oops) to translation instead of scew that is completly overriden anyways so it did no harm but also served no purpose

**Comment by MNarath1** [comment]
ok ammending after making a PR is pretty useless noted

**Comment by MNarath1** [comment]
ahh this makes my head hurt using the third axis is actually useless as i found out the sphere coordinate x and y do fine without it so i will keep it like that and not worry how to implement a 3 axis into a two dimensional matrix

**Comment by MNarath1** [comment]
@ike709 ok now it should be fine

**Comment by MNarath1** [comment]
also to wrap my head around this i used this as a reference https://www.geogebra.org/m/FzkZPN3K
well this and a calculator heh

**Pull request merged**
