### PR TITLE
Extend Lobby Time

### PR DESCRIPTION
**Pull request by MatiAvanti**
## About The Pull Request
Changes the lobby time to <s>450</s> 300 seconds.
## Why It's Good For The Game

If you crash you can rejoin in time to ready up and dont miss round start.
Small breaks between rounds are good for You, go get some water and drink it.
Did I mention more time for admins to play music to chill to?
Feedback thread for this PR to measure playerbase approval:
https://forums.beestation13.com/t/extend-time-to-start-the-round-by-a-factor-of-3/25738

## Testing Photographs and Procedure

bruh
</details>

## Changelog
:cl:
tweak: changed LOBBY_COUNTDOWN from 180 to 300 seconds
/:cl:

### CODE REVIEW

**Comment by DrDuckedGoose** [comment]
[I'm in favour of Dragon's suggestion for 5 minutes](https://forums.beestation13.com/t/extend-time-to-start-the-round-by-a-factor-of-2-5/25738/5?u=racc-off)

**Comment by PowerfulBacon** [comment]
7.5 minutes is insane, especially since the majority of players simply need to join and press "ready". Anything over like 4 minutes I think will be way too long by itself. A more dynamic solution that starts high but speeds up as players from the previous round rejoin could be acceptable.

**Comment by BriggsIDP** [comment]
it requires at least 5 mins to make a cup of tea, I like 7.5mins, hell you could just talk about the last round a little longer if you'd like, or do a few pushups

**Comment by PowerfulBacon** [comment]
As much as I respect that some players may want a quick break between rounds, I don't want new players who just joined to wait 7.5 minutes before the round can start, especially since previous round has upwards of 2 minutes from end to a point where it starts counting down. I've had situations in the past where I've thought the round timer was long, although it did used to be longer I think (and this was before it was reduced).

**Review by Crossedfall — CHANGES_REQUESTED** [review]
300 is the highest I'd be willing to let this get to, and even that is a pretty long wait. Especially for someone joining for their first round of the day.

To be frank, I'm not really sure how much of a difference this will ultimately make. Consider that when a player sits in the lobby to take a break after a long round, it's generally for a lot longer than the proposed 7.5 minutes. I will often see players sitting in the lobby from round-start for up to 10-15 minutes after the round started before joining.

**Comment by Crossedfall** [comment]
I'll give it a "test merge" (You can't TM config changes, but I can make the alteration for a short while)

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
