### PR TITLE
Stat panel updates

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Updates the stat panel to make Ike hopefully like it a bit better.

Stat panel background now fills the whole area, tickets show on stat panel.

Standard Stat:

image

Buttons:

image

Light Mode MC:

image

Bwoink:

image

Improves the traitor message thing:

image

## Why It's Good For The Game

Its nicer.
Makes adminhelps even more imporatnt

## Changelog
:cl:
tweak: Improves stat panel background design.
tweak: Stat panel will now display adminhelp messages for the bwoinkees.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Can yolotestmerge if needed

**Comment by PowerfulBacon** [comment]
This is pretty nice, functioning decent in testmerge

**Comment by ike709** [comment]
Fix conflicts and ping for merge.

**Comment by ike709** [comment]
YOLO

**Pull request merged**
