### PR TITLE
Adds ticketmachines

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports:
- https://github.com/tgstation/tgstation/pull/45095
- https://github.com/tgstation/tgstation/pull/45417
- https://github.com/tgstation/tgstation/pull/45813
- https://github.com/tgstation/tgstation/pull/45979
- https://github.com/tgstation/tgstation/pull/55468
- https://github.com/tgstation/tgstation/pull/69406

## About The Pull Request
The devil has come to beestation...

This adds ticketmachines to the HOPline, for the bureaucratic HoPs and to encourage the use of paperwork.
I discussed this with an admin and he thought it would help RP as well.

This includes minor code for /tg/ wallening, but doesnt utilize it

## Why It's Good For The Game
More mechanical ways to RP are always good. If the HoP is chickenshit enough to not use it, it doesnt really make a difference if its there or not in the end.

## Testing Photographs and Procedure
tickets1
tickets2
tickets5
tickets3

## Changelog
:cl:
add: Added Ticketmachines to the HoPline. HoPs rejoice! All else shall suffer...
add: Though it comes with an emag function if you want to make his life hell instead...
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
can we make the console not inside a glass window, or have it so its a wall mounted machine?

**Comment by Tsar-Salat** [comment]
> 1. Do you think this will be used?

Yes. I've seen paperwork HoPs before with forms upon forms of getting access. Plus getting a ticket is useful if an event happens that forces a crewmember out of line.

This is an easy addition to promote RP that can be simply disregarded if they dont want to engage with it.



> 2\. somewhere that doesn't have a linear line (Like the kitchen for example)?

IMO a linear queue is where it would work best. Besides, in places like the kitchen cooks are rarely made-to-order, and will instead create random assortments of food from whatever botany gives them, or stick to a themed gimmick.



> 3\. How does the construction work and is it consistent with other wall items?

There is no construction. There is a system in place to relink the button if needed, but theres no circuitboard or any building steps. Its intended to be a roundstart machine and thats it.

**Comment by PowerfulBacon** [comment]
> IMO a linear queue is where it would work best.

Whats the point of a linear queue with a ticketting system? Why not just queue?

**Comment by Fronsis** [comment]
> > IMO a linear queue is where it would work best.
> 
> Whats the point of a linear queue with a ticketting system? Why not just queue?
> 
> There should definitely be a construction for it.

I agree that this being a construction would be benefitial, this could encourage our most creative players to come up with gimmicks related to ''tickets'' as well as having the chance to repair it in case random explosion/tider happens

The ticketing system alongside queues would generate small RP situations on HoP line for the more strict paperwork-hops mains alongside preventing dumb fights for cutting the line that could easily be solved if sec arrives by showing who had the priority in the line, and if some HoP's don't want to use it they can ignore it, same logic as how many hop's don't go super strict paperwork mode

Does the HoP have a place where to store all the tickets? It would be nice if the HoP had like a inverted sharp pin with a base or something like that to dispose of them

**Comment by EvilDragonfiend** [comment]
I think it needs a machine board

**Comment by EvilDragonfiend** [comment]
> Do you think this will be used?

to be honest, I think this will be used somewhere rather than in HoP line lol

**Comment by Tsar-Salat** [comment]
> to be honest, I think this will be used somewhere rather than in HoP line lol

I guess I could make it buildable (make the building sprites myself i suppose) 

I'm not sure if I really want to give the cook their own machine, though. Perhaps just give him a board and button electronics and let them build it if they want to?

**Comment by Rukofamicom** [comment]
Looks fantastic 👍

**Pull request closed without merging**
