### PR TITLE
BREAKING NEWS FROM GLORIOUS BEESTATION

### PR DESCRIPTION
**Pull request by SofterStone**
## About The Pull Request
some dude made the game lag with spaghetti code 

## Why It's Good For The Game
yiff decreased by 100%
no more usual 1027 ping 

## Changelog
:cl:
add: Added fun
del: removed messy spaghetti code 
fix: fixed beestation a bit
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
hilarious

**Review by bloons3 — CHANGES_REQUESTED** [review]
fails linter

**Comment by MCterra10** [comment]
lmao

**Comment by SofterStone** [comment]
haribo
**R O U L E T T E**

**Comment by TeomanTheGreat** [comment]
Great PR. Speedmerge now

**Comment by ike709** [comment]
Pretty funny, also indirectly got a guy muted on discord and he's seething as a result which just makes it more funny.

**Pull request closed without merging**
