### PR TITLE
Port chat reliability subsystem from /tg/

### LINKED ISSUE #9050: a chat message sometimes doesn't appear on TGUI chat, but appears on runechat
title.

It's not reproducible.

When you say a chat message, a runechat appears on you, but you see no chat log in your TGUI chat log. It's unsure if it's only applied to your chat, or it happens to other people's chat too.

It happens rarely but sometimes happens.

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

Ports https://github.com/tgstation/tgstation/pull/79479, https://github.com/tgstation/tgstation/pull/79819, and https://github.com/tgstation/tgstation/pull/79821.

Fixes https://github.com/BeeStation/BeeStation-Hornet/issues/9050

## Why It's Good For The Game

Should get rid of that annoying bug where random chat messages rarely get "swallowed" and never appear for certain people.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

2023-12-21 (1703144126) ~ dreamseeker

</details>

## Changelog
:cl: ZephyrTFA, Absolucy
add: Chat Reliability Layer
code: TGUI chat messages now track their sequence and will be resent if the client notices a discrepenency
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
eh, mistake. it really didn't pass.
            
image
image
image

**Comment by itsmeow** [comment]
https://github.com/tgstation/tgstation/pull/79821/

**Comment by Absolucy** [comment]
@itsmeow this already has that lol

**Comment by PowerfulBacon** [comment]
Is this good to go?

**Comment by PowerfulBacon** [comment]
@itsmeow Mandatory review

**Review by itsmeow — APPROVED** [review]

**Pull request merged**
