### PR TITLE
Updates red alert status panel display

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Updates the red alert status panel display. The current one ported from TG looks very shodilly sprited.

The green and blue alerts still look kinda bad but I had no ideas for improving them.

## Why It's Good For The Game

The status alert panel just looks a bit nicer

## Testing Photographs and Procedure

https://github.com/user-attachments/assets/1e4d79ff-35a5-4579-b6d0-c984d5a876dd

## Changelog
:cl:
tweak: Changes the red alert status panel display sprite
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
Got to disagree here, the old one does look better in this case.

**Comment by PowerfulBacon** [comment]
image

The old one is literally this

**Comment by MarkusLarsson421** [comment]
> The old one is literally this

It's a lot clearer and with less clutter. Which is nice when it takes up like 1/100th of the screen.

**Comment by Rukofamicom** [comment]
This looks way better than your blood anomaly sprite. Why couldn't you put this effort into that!

**Review by Rukofamicom — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
Anomalies are meant to look weird

**Comment by MarkusLarsson421** [comment]
The anomaly does look good.

**Comment by PowerfulBacon** [comment]
I agree with ruko

**Pull request merged**
