### PR TITLE
Removed surgical drapes

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Like many other codebases, I thought we should just remove surgical drapes altogether. Takes code from OracleStation. Fully tested.

## Why It's Good For The Game
Removes the need for surgical drapes, which although have alternatives and can be created in a techfab, it would be a lot simpler just to use a sharp tool to start the surgery.

## Changelog
:cl:
del: Removed surgical drapes
add: Can now start surgery with any sharp object (think ghetto surgery)
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
shoot why is it throwin an error

**Comment by ike709** [comment]
```
_maps/map_files/Donutstation/Donutstation.dmm:43108:error: undefined type: /obj/item/surgical_drapes
_maps/map_files/Donutstation/Donutstation.dmm:43116:error: unknown type
loading map_files/KiloStation/KiloStation.dmm
_maps/map_files/KiloStation/KiloStation.dmm:29526:error: undefined type: /obj/item/surgical_drapes
_maps/map_files/KiloStation/KiloStation.dmm:29535:error: unknown type
_maps/map_files/KiloStation/KiloStation.dmm:36707:error: undefined type: /obj/item/surgical_drapes
_maps/map_files/KiloStation/KiloStation.dmm:36718:error: unknown type
_maps/map_files/KiloStation/KiloStation.dmm:94911:error: undefined type: /obj/item/surgical_drapes
_maps/map_files/KiloStation/KiloStation.dmm:94914:error: unknown type
```

**Comment by MarkSuckerberg** [comment]
Forgot I gotta fix them too...

**Comment by despong** [comment]
finally i can fucking screw my chest to do ipc surgery without needing a fucking bedsheet

**Review by qwertyquerty — CHANGES_REQUESTED** [review]
Fix the maps

**Comment by Crossedfall** [comment]
Why not leave the drapes in and penalize surgeries done without them?

**Comment by MarkSuckerberg** [comment]
I guess I could do that

**Comment by MarkSuckerberg** [comment]
Closing this since Crossed's idea is better and I don't want to manually revert all the map changes

**Pull request closed without merging**
