### PR TITLE
Subsystems are no longer allowed to sleep within fire()

### LINKED ISSUE #7070: weird delay bug
## Round ID:
around 38710

## Reproduction:

I think we have very weird delay bug. I can't exactly tell how it is...
- when you climb up on a table(or operation table), round time is frozen and you can't likely walk even if enough time is passed. (I was stopped like 60 seconds over)
- In that case, if you go rest, you can't get up. at 5% progress gauge, it's cancelled and it says 'you failed to get up'
- in that time, other people reported that they can't get up (they were resting too)
- once round time goes, the weird freezing issue solved.

```
OOC: EvilDragonfiend: people, have you ever noticed some weird delay bug? like that you can't get up for 30~60 seconds after climbing up a table or resting
OOC: Bebes_Kidz: Evildragonfiend
OOC: Bebes_Kidz: SAME
 OOC: Chiryn: yes sometimes @evildragonfiend
OOC: Bebes_Kidz: I had that happened last round
OOC: Sumianhi: Yes Ignites.
OOC: Bebes_Kidz: I'm not even sure what causes it
```

--------------------

image

this might be related
my character has no name on examine
arrival shuttle deson't dock
my chat name tells 'my name (as my name)'

### LINKED ISSUE #7189: Crew Pinpointers randomly stop updating for several minutes
## Reproduction:
Again, a bug report after the fact, but on multiple rounds, I've had the crew pinpointers just stop updating. Turning them off then on and picking a target will point towards them, but that reading will never update again. This seems to last a few minutes before they magically work again.
image

This might POSSIBLY be related to a similar issue where atmos devices like pumps or canisters don't seem to work for filling tanks. I've had that happen several times as well and it fixes itself after a few minutes.

### PR DESCRIPTION
**Pull request by PowerfulBacon**
fixes https://github.com/BeeStation/BeeStation-Hornet/issues/7070
fixes https://github.com/BeeStation/BeeStation-Hornet/issues/7189 (I think)

## About The Pull Request

SSair.unpause_z was called by SSzclear, however it contained a CHECK_TICK. This introduced a CHECK_TICK into the master controller cycle, which would cause all subsystems to be frozen during high tick loads until that function could complete.

This updates the function to instead command the air subsystem to unpause the z-level during its fire() call. It now also runs off the MC_TICK_CHECK instead. If it takes a super long time to run for whatever reason, rather than freezing the entire MC, only atmos will be paused for some time.

We also ignore space turfs for atmos reactivation, since it uses a static atmosphere anyway so shouldn't ever contain gas even if the ChangeTurf retains the initial atmos state.

Subsystem fire calls are no longer allowed to sleep at all. This should prevent this ever happening in the future.

## Why It's Good For The Game

No more TICK_CHECK within the master process call chain. This should fix all subsystems suddenly freezing up during high server load.

## Testing Photographs and Procedure

<details>

image

Frozen subsystem

image

Variables are fine

image

Only runtime was fixed

image

Unpausing triggers atmos updates

image

Variables are fine

image

Still no relevant runtimes.

image

Nightshift functionality still works.

image

Overlay functionality still works

image

Queued player joining works.

Shuttle call vote: ~~**failed**~~ Nevermind, this was because not enough time had passed in the round.

image

Access buttons working

image

Wishgranter Dark Working

image

Salvation working

image

Shuttle scrambler working

image

Food processor working

image

Beebox works

</details>

**Haven't tested:**
Mobs having an invalid client being sent to TGS (No TGS setup on local)

## Changelog
:cl:
fix: Timers, orbit updates and other subsystem related processes will no longer freeze when a z-level is unpaused from atmospherics.
fix: Improved the performance of atmospheric unpausing by ignoring updates on space turfs.
code: Subsystems are no longer allowed to sleep during their fire process.
del: Removes the delay from getting employment contracts out of the lawyers office thing. (No player facing changes, this was bugged anyway)
/:cl:

### CODE REVIEW

**Review by ike709 — DISMISSED** [review]

**Review by PowerfulBacon — COMMENTED** [review]
This didn't fix the issue, I managed to replicate it with 60 monkey spawns. Still better code though

**Comment by PowerfulBacon** [comment]
Lighting is bugged and never loads

**Comment by PowerfulBacon** [comment]
> isnt this literally what `ignite()` is for? Working on TG, sleeping subsystems are fine, as long as the subsystems themselves are capable of handling sleeping.

Looking at it, yes. Something somewhere might still be massively fucky then

**Comment by PowerfulBacon** [comment]
I still think the issue was related to unpause_z and pause_z, so this probably still fixes it

**Comment by PowerfulBacon** [comment]
Man I hate MC stuff, this is a real pain in the backside. The only other thing I can think of this being is something within the atmos DLL which is even more difficult to debug and fix.

**Comment by nednaZ** [comment]
We have it testmerged downstream (Monkestation) and I did not get any reports tonight about the subsystem freezing, nor did we see any odd activity.
Population was around 40-50 on average to give you an idea of the load.

**Comment by nednaZ** [comment]
Had the issue at 67 pop, Atmos SS hang and Mood SS hang.
Unsure if it's connected, but reporting it in case it's relevant.

**Pull request closed without merging**
