### PR TITLE
nerfs pituitary disruption's disruption

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
pituitary disruption tumors no longer appear at all on monkeys
teratomas now only appear from changelings
pituitary disruption's size boost is now far smaller

## Why It's Good For The Game
pituitary disruption is a bit too flashy and disruptive, i've been intending to tone this down for awhile

## Testing Photographs and Procedure
image
this is the max size boost now. the blood in monkey cages is them trying and failing to vomit organs

## Changelog
:cl:
del: random organ drops no longer create teratoma spawners. this means maint and mail tomas no longer exist, either
tweak: pituitary disruption no longer makes you grow nearly as large
balance: pituitary disruption no longer drops random organs from monkeys
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Unpushed commits?

**Comment by zeskorion** [comment]
> Unpushed commits?

yeah. sorry, im  moving and busy

**Comment by zeskorion** [comment]
> Unpushed commits?

done!

**Comment by Kratairo** [comment]
Didnt you already murder viro with the transmission removal since you moved it into useless symptons like cough and sneezing?

**Comment by zeskorion** [comment]
> Didnt you already murder viro with the transmission removal since you moved it into useless symptons like cough and sneezing?

im the one who added this symptom and i am the one who will nerf it

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
