### PR TITLE
[PORT] Changes the CC Jumpsuit to the not 8-year old one.

### PR DESCRIPTION
**Pull request by ghost**
### Why It's Good For The Game

It was pretty disgusting honestly. The updated black and gold ones from Paradise are much better.

The CC-Commander also now gets the Central Command beret and sunglasses instead of an eye-patch.

CC-Commander with bulletproof armor
https://gyazo.com/44f5be6db19ef6c3ca65e7b3a97adaac

CC-Commander without bulletproof armor
https://gyazo.com/4ee32ccd9da08de51b5008d57e874935

This change only affects the CC-Commander and the Deathsquad as they're the only ones that wear this jumpsuit, not sure if it would fit Officials.
## Changelog
:cl:
imageadd: The Commander of Central Command decided to buy new Clothes.
imagedel: The Commander of Central Command decided to burn his old Clothes.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
This is the normal CentCom Official with the new sprites, opinions?
image

**Comment by VictorVow** [comment]
NT logo is blue so it makes more sense their uniforms would be blue tbh. 

Green is a better fit for [SolGov/TerraGov](https://github.com/WaspStation/WaspStation-1.0/pull/151), if we were to add it.

**Comment by ghost** [comment]
> NT logo is blue so it makes more sense their uniforms would be blue tbh.
> 
> Green is a better fit for [SolGov/TerraGov](https://github.com/WaspStation/WaspStation-1.0/pull/151), if we were to add it.

Blue is already reserved for the stations command though.

**Comment by ghost** [comment]
This new sprite looks terrible what crack were you smoking

**Comment by ghost** [comment]
Ah yes, make the unique centcom jumpsuit look like something you’d find in the HOS closet

**Comment by PowerfulBacon** [comment]
That new Sprite looks fucking terrible, no offense to the original creator.

Terrible for centcom, it looks too similar to the really black suit

**Comment by qwertyquerty** [comment]
Ugly

**Pull request closed without merging**
