### PR TITLE
Cuffs no longer make you a helpless baby

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request

You can now take actions while cuffed. It takes three seconds to take any action, and you must be standing still. This doesn't mean much if you're grabbed and someone is pulling you, but it's a start. Additionally, the way the time is defined makes it incredibly easy to change universally. 
Overall, this is an indirect balance to stuncombat by making the 4-second win condition a slight bit less of a win condition

I wanted to balance it so you stand a bit more fighting chance, but that'd make arresting people nonlethally totally unviable. I also failed to make it possible to kick unimpeded while cuffed. it'd need a fuckload of spaghetti to do so.
A side-effect of this pr is that aggro grabs no longer cause item droppage (they use the same effect cuffs do)

Idea credit goes out to Freeman
## Why It's Good For The Game

cuffs now feel a slight bit more like handcuffs, instead of magical paralysis bands that take only 4 seconds to apply

## Changelog
:cl:
balance: handcuffs no longer make you a helpless baby
code: define for cuff action time
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
"what if we made sec just crit people instead of cuffing them" the PR

**Comment by qwertyquerty** [comment]
I kind of agree with belone on this one.

**Comment by qwertyquerty** [comment]
I'm not a fan of how this is implemented either

**Comment by zeskorion** [comment]
> I kind of agree with belone on this one.

I think it should be put to vote regardless, see if people want it for a testmerge. the way cuffs currently work honestly make no sense to me.

I do plan to make some sec progression additions if this is merged, however, to compensate

**Comment by qwertyquerty** [comment]
Yes but it's also a terrible code implementation, so I don't even want to put it to vote then have to close it because of bad code.

**Comment by ike709** [comment]
Bad PR.

**Comment by zeskorion** [comment]
is there a better way to implement it, then? handcuffs are hardcoded into all these items

**Comment by qwertyquerty** [comment]
Conflicts, bad implementation, (might even say CRINGE), 3 thumb down

**Pull request closed without merging**
