### PR TITLE
disables mood, again. (dammit qwert)

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
passed multiple votes, but qwerty put in a rework option even though nobody wants to rework this fucking shit. disables mood.

## Why It's Good For The Game

AIGHT LEMME LAY IT DOWN FOR YA:
-MOOD IS BAD FOR ROLEPLAY. NOT GOOD FOR ROLEPLAY. I DECIDE HOW MY CHARACTER IS. HUMAN MOOD IS TOO FUCKING NUANCED TO EMULATE IN A GAME, ESPECIALLY A GAME THAT ISN'T ABOUT AUTISTIC MANAGEMENT. IF I WANTED TO PLAY RIMWORLD, I'D PLAY RIMWORLD (which i dont cuz it is boring and because it has a shitty mood system)
-ALL MOOD IS IS A WAY FOR CODERS TO LAZILY PUNISH PLAYERS FOR RANDOM SHIT. THAT IS HOW IT'S USED, AT LEAST.
-WHY THE FUCK CAN BEING A BIT HUNGRY FOR ABOUT A HALF HOUR DRIVE YOU INSANE?
-HOW CAN FEELING SLIGHTLY SHITTY AT ALL DRIVE YOU INSANE
-WHO THE FUCK THOUGHT MAKING A QUIRK THAT ALLOWS MOOD TO BE CHECKED, AND GIVING ANTAGS A MOODLET AT THE SAME TIME WAS A GOOD IDEA? 
-im too lazy to add moodlets to shit i code and everyone else is too
-MECHANICAL MOOD IN A GAME WHERE YOU PLAY A SINGLE CHARACTER, ESPECIALLY A ROLE-PLAYING GAME, IS GENERALLY A BAD IDEA. 
-MOOD IS VERY POORLY DONE. I DONT WANNA FIX IT BECAUSE, EVEN THOUGH I COULD DO BETTER, I WOULD NOT BE SATISFIED AND IT WOULD BE A LOT OF WORK FOR SOMETHING THIS GAME DOESNT NEED
-MOOD MAKES GAMEPLAY INCONSISTENT. 100 HP TO CRIT, DAMMIT. DONT MAKE IT ALL FANCY N SHIT
-MOOD BROKE MY CAPSLOCK KEY

## Changelog
:cl:
config: MOOD IS GONE 
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Bad change

**Comment by zeskorion** [comment]
> Bad change

got a better idea?

**Comment by PowerfulBacon** [comment]
> 
> 
> > Bad change
> 
> got a better idea?

No, but just outright disabling it is worse than having it.

There are multiple ways you could do it.
Buff the mood fixing chems, make sanity go down when you are alone or hallucinating instead of being based off your mood, have moods and quirks work better and have a more pronounced effect than slowdown, IE depression could dim the colours of the game making it look more depressing etc.
Social anxiety could cause your mood to go down when you are in a large group but still go up while in a small group and stuff like that.
Idk but its kind of a core system at this point cause its been in for so long and just removing it would be removing a pretty significant part of the game.

**Comment by PowerfulBacon** [comment]
Also a lot of items use mood as a way for minor balancing

**Comment by zeskorion** [comment]
> > > Bad change
> > 
> > 
> > got a better idea?
> 
> No, but just outright disabling it is worse than having it.
> 
> There are multiple ways you could do it.
> Buff the mood fixing chems, make sanity go down when you are alone or hallucinating instead of being based off your mood, have moods and quirks work better and have a more pronounced effect than slowdown, IE depression could dim the colours of the game making it look more depressing etc.
> Social anxiety could cause your mood to go down when you are in a large group but still go up while in a small group and stuff like that.
> Idk but its kind of a core system at this point cause its been in for so long and just removing it would be removing a pretty significant part of the game.

sanity is a mood thing and is part of the problem. quantifying sanity is also terrible


mood should have LESS effect, not more. you know me bacon. i dont give a fuck about how long something has been around. I can make a more in-depth mood deletion later

**Comment by ghost** [comment]
>IF I WANTED TO PLAY RIMWORLD, I'D PLAY RIMWORLD (which i dont cuz it is boring and because it has a shitty mood system)

die

**Comment by Archanial** [comment]
Good change

**Comment by eLeCtrOssSnake** [comment]
Ridiculously bad change, no. Mood system is okay, just should have more things to consider, and less bouncy so it won't make you slip and be insane.

**Comment by Archanial** [comment]
> 
> 
> Ridiculously bad change, no. Mood system is okay, just should have more things to consider, and less bouncy so it won't make you slip and be insane.

Mood system is okay because?

**Comment by ToasterBan** [comment]
should do what (forgot what server did this) did and make it toggle-able in the character settings, tough it does need a re-work I feel like deletion shouldn't be done, tough I feel it should be deleted in lrp

**Comment by yorii** [comment]
???????????????????????????????????????????

did you get griefed by your own mood this time??????????????????

**Comment by zeskorion** [comment]
> ???????????????????????????????????????????
> 
> did you get griefed by your own mood this time??????????????????

 No i just hate mood

**Comment by yorii** [comment]
I sincerely don't think many others do though..?

**Comment by TeomanTheGreat** [comment]
Fuck mood all my homies hate mood

**Comment by Mick1299** [comment]
Might as well remove hunger and quirks, they become pointless without mood

**Comment by hotimep** [comment]
>slips once, is slightly hungry
>damn bro, guess i'll kill myself

**Comment by ike709** [comment]
i ded

**Comment by PowerfulBacon** [comment]
Disable mood, disable hunger, remove quirks, remove the showers, remove being unclean, remove traumas. I am not really sure a deathmatch game needed them in the first place, they really get in the way of combat and make it very annoying when I am trying to kill the other players.

**Comment by Archanial** [comment]
> 
> 
> Disable mood, disable hunger, remove quirks, remove the showers, remove being unclean, remove traumas. I am not really sure a deathmatch game needed them in the first place, they really get in the way of combat and make it very annoying when I am trying to kill the other players.

no, just disable mood, fuck mood

**Comment by ivanmixo** [comment]
Eh I wouldn't remove it completely, just cut out the dumbass aspects of it like how being mildly hungry makes you go asylum level insane in 15 minutes, also kinda stupid how slipping gives you a negative mood penalty, while being injured severely or sick has no effect.

**Comment by imw-Oculus** [comment]
"MOOD IS VERY POORLY DONE. I DONT WANNA FIX IT"
This is hands down the worst logic for a PR, besides "I don't like the thing".
Yes, Mood could be better implemented. No, I don't think it should be removed.

**Comment by eLeCtrOssSnake** [comment]
Why is this open?

**Comment by Archanial** [comment]
Why is it not merged?

**Comment by Sun-Soaked** [comment]
I gotta say, the way this pr is written kind of makes me dislike it, despite not entirely disagreeing. C- for evocative tone, see me after class

**Comment by Sun-Soaked** [comment]
steps to turning a pr into a confrontational nightmare:
1: write in all caps(even if ironically)
2: insult a game popular with the audience of the pr
3: explicitly write "I don't like this and I can't be bothered to fix it"
4: sit back and watch the comments devolve into cancer

**Comment by Crossedfall** [comment]
Was waiting on more feedback on this before chiming in myself. The mood system is way too deeply integrated for it to be disabled at this point. The config option is honestly a bit of a ruse, because it doesn't actually do anything to disable the numerous systems that tie into moods (E.g. hunger, hygiene, specific quirks, etc.), so this moot.

Personally, I don't really like the moods system. But I can recognize that this is a bad change to make.

**Pull request closed without merging**
