### PR TITLE
Applies unused races to NT ERT and Deathsquad

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

ERT are now the Corporate Agent race.
Deathsquad are now the Military Synth Race.
## Why It's Good For The Game

I always felt like ERT are a bit weak because of their meh-tier guns if they weren't code red ERT, with the Corporate Agent race.
Corporate Agents stats:
2 Times Faster than normal.
Takes 0.7 Times the Brute Damage
Takes 0.65 Times the Burn Damage
Takes no Cold Damage
Takes 0.5 Heat Damage
Does 25 Punch Damage (wtf, i will probably nerf this to normal if someone asks me to)
Immune to: Radiation, Viruses, Piercing, Dismemberment, Can't disable their Limbs via Damage, Doesn't Hunger.

For the Deathsquad i just thought Military Synths fit for their Role and that they aren't really supposed to be Balanced, Military Ontop of the buffs that normal Synths have already, Military Synths have +25 armor to everything and deal 14 punching damage.

## Changelog
:cl:
tweak: ERT now spawn as the Corporate Agent Race, takes less damage Overall.
tweak: The Deathsquad now spawns as the Military Synth Race, +25 armor to everything and 14 punching damage.
/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
Don't synths can heal only with synthflesh? Feels like a downgrade honestly.

**Comment by ghost** [comment]
> Don't synths can heal only with synthflesh? Feels like a downgrade honestly.

What about leaving ERT untouched and applying corp agent to DS, seems like it would fit better especially with the absurd punching damage.

**Comment by Isy232** [comment]
@BeloneX Give an option to spawn the ERT as corperate or whatever or just plain humans. I don't think every ERT should be this strong.

**Comment by PowerfulBacon** [comment]
I don't like this PR because admins don't want to send in super OP instant game winning things, if an ERT is guaranteed to win a round then there is no reason in sending it since it just ruins the round. Making them strong makes them worse since it limits the amount they can be used

**Comment by ghost** [comment]
yeah this is dumb

**Pull request closed without merging**
