### PR TITLE
Fix the incursion antag info UI

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

Forgot to make the members `<Stack>` vertical. Whoopsie daisy.

## Why It's Good For The Game

fixes a fucky wucky, a buggy wuggy if you will

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

</details>

## Changelog
:cl:
fix: Fixed the Incursion antag info UI displaying the team member list horizontally.
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
Use a vertical `<Tabs>`, it looks way better

**Comment by itsmeow** [comment]
Oh it's just a list not tabs

**Comment by itsmeow** [comment]
It still looks really bad, it doesn't fill the width so the candystripe looks bad

**Comment by Absolucy** [comment]
@itsmeow I removed the candystripe shortly after taking the screenshot

**Comment by itsmeow** [comment]
hmm ok

**Review by itsmeow — APPROVED** [review]

**Pull request merged**
