### PR TITLE
telecommunications SMES and the gravity gen SMES are now both wired to the wirenet [boxstation]

### PR DESCRIPTION
**Pull request by athena413**
## About The Pull Request

see title.

## Why It's Good For The Game

because they aren't wired to the wirenet, they will eventually run out of power and go down. while in practice this wouldn't really happen during an average round, this is still a problem that could happen on very not-average rounds

## Changelog
:cl:
add: grav gen and tcomms SMESes are now wired
/:cl:

### CODE REVIEW

**Comment by athena413** [comment]
friend made this:

image
image

**Comment by ike709** [comment]
@zeskorion

**Review by zeskorion — APPROVED** [review]

**Comment by 4rchibald** [comment]
@zeskorion @ike709 @FLME 

Why was that merged? 
It's not a bug but a concious design decision not to wire grav generator, tcomms and AI Sat to the grid. Its done to counter powersink so it won't cut power to these vital parts of station since its bad enough that all departments lose their power which prevents them from doing any work and makes them vulnerable for breaking into, things would be even worse if powersink would also turn off gravity, power down AI and cut radio communication

**Comment by ike709** [comment]
That's not at all how a SMES/powersink works. SMES units have an input, and an output. The input is now wired to the grid, not the output. No power will leave from the SMES to the grid or a powersink, unless the powersink is on the output powernet or the output powernet is manually wired to the grid.

**Pull request merged**
