### PR TITLE
 tinfoil envirosuit helmet, aka ghetto plasmaman hat

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request

Adds the tinfoil envirosuit helm, a weaker plasmaman envirosuit helmet craftable with (inhale):
a tinfoil hat
a hard hat
a set of mesons
sunglasses
fifteen wire 
ten package wrap
one flashlight
one sheet of glass
It also uses wirecutters, a screwdriver, and a crowbar.
It functions as a tinfoil hat, and, unlike normal envirohelmets, can be burnt off.

The tinfoil hat is now craftable with 3 iron sheets and a crowbar (it used to be only obtainable through 2.5 iron sheets in a hacked autolathe)

## Why It's Good For The Game

adds a shitty meme improvised envirohelmet (this functions as a tinfoil hat as well)
tinfoil hats cannot be removed (by the wearer) after being put on, and give the wearer the Paranoia phobia. it makes the wearer immune to the Mind Reading mutation, as well as abductor baton's sleep function, abductor thought transmission, and being scanned by an abductor console.

tinfoil hats shouldn't require advanced tech to make, so they can now be made by hammering metal out with a crowbar

image

## Changelog
:cl:
add: blasma tinfoil hat
tweak: tinfoil hat can now be crafted without an autolathe
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Is there supposed to be a full flashlight in that one icon state?

**Comment by zeskorion** [comment]
> Is there supposed to be a full flashlight in that one icon state?

I was under the impression i uploaded the fixed version

**Review by qwertyquerty — CHANGES_REQUESTED** [review]
fix the icon

**Comment by zeskorion** [comment]
> fix the icon

Yeah ill do it later today

**Comment by zeskorion** [comment]
alright i did it

**Comment by qwertyquerty** [comment]
You added a random hats.dmi

**Comment by zeskorion** [comment]
God i have no idea what's going on here, i'll take care of it when j get home or something...

**Comment by zeskorion** [comment]
alright, figured out where i made a doody.

**Comment by qwertyquerty** [comment]
some random map rooms have crept in now. Gosh learn git branch control

**Comment by zeskorion** [comment]
> some random map rooms have crept in now. Gosh learn git branch control

god fucking....

**Pull request merged**
