### PR TITLE
Teratomas can no longer be humanized or have their brain removed

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Teratoma to human = ban
Stops teratoma to human

Makes teratomas also unable to create chests from necroseed virus.
Teratomas brain will be deleted upon removal.
Teratomas like all basic foods.
Teratomas has bad / no DNA.
Teratomas cannot use guns.

## Why It's Good For The Game

People getting banned for something that seems innocent is pretty silly imo

image

image

## Changelog
:cl:
tweak: Teratomas can no longer have DNA and cannot be humanized through mutadone or radiation.
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
isnt humanizing them supposed to be about transplanting their brains

**Comment by r1ks-iwnl** [comment]
Using their brains in surgery is especially bad because you can use the bodies to farm necropolis chests.

**Comment by PowerfulBacon** [comment]
> 
> 
> Using their brains in surgery is especially bad because you can use the bodies to farm necropolis chests.

Necropolis chest disease is a mess and needs to be removed imo

**Comment by Goblinu** [comment]
The issue still pertains that tomas are antags that can be infinitly manifactured, it would be better if virology couldnt make them at all

**Comment by MNarath1** [comment]
> 
> 
> The issue still pertains that tomas are antags that can be infinitly manifactured, it would be better if virology couldnt make them at all

not really all of them pretty much mainly the changeling ones have an antag datum and are allowed to act as an antag i am not sure if the same goes for the disease but the random ghost spawn toma definitly has no antag datum and are not allowed to actually act like an antag.

**Comment by Sinestia** [comment]
> 
> 
> > The issue still pertains that tomas are antags that can be infinitly manifactured, it would be better if virology couldnt make them at all
> 
> not really all of them pretty much mainly the changeling ones have an antag datum and are allowed to act as an antag i am not sure if the same goes for the disease but the random ghost spawn toma definitly has no antag datum and are not allowed to actually act like an antag.

This isnt true and the datum issue was fixed awhile ago

they are antags without murderbone (unless a ling toma)

**Comment by MNarath1** [comment]
> 
> 
> > > The issue still pertains that tomas are antags that can be infinitly manifactured, it would be better if virology couldnt make them at all
> > 
> > 
> > not really all of them pretty much mainly the changeling ones have an antag datum and are allowed to act as an antag i am not sure if the same goes for the disease but the random ghost spawn toma definitly has no antag datum and are not allowed to actually act like an antag.
> 
> This isnt true and the datum issue was fixed awhile ago
> 
> they are antags without murderbone (unless a ling toma)

even the ghost spawner ones?

**Comment by MNarath1** [comment]
ok i read over the pr that changed it again could swear only traitor spawned tomas got an antag datum but its true the others have one too trough its different from the one that lings have so from what i understand maint tomas as well as the one spawned by disease both use the same datum and that one also pretty much tells them they are not allowed to kill except in self defense so yeah

**Review by utilbird — APPROVED** [review]

**Pull request merged**
