### PR TITLE
Every hydro now gets BEES

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request
title

## Why It's Good For The Game
were beestation why not add some BEES

## Changelog
:cl:
add: Bees to almost every single hydroponics bay! 
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
this is probably gonna get shut down by maintainers but arconomy will make ordering them easier

**Comment by r1ks-iwnl** [comment]
Yeah the last roundstart bee pr understandably didn't fare well

**Comment by PowerfulBacon** [comment]
Screenshot corg changes upper deck

**Comment by St0rmC4st3r** [comment]
What about pubby?

**Comment by ToasterBan** [comment]
> What about pubby?

it already has bees in the chapel garden

**Comment by ToasterBan** [comment]
> Screenshot corg changes upper deck

https://media.discordapp.net/attachments/736919570190696460/884521800552288256/unknown.png

**Comment by ivanmixo** [comment]
I suggest you make the botanist lockers start with the bee equipment instead of manually putting it there

**Comment by BrumalLake** [comment]
heh these botanists are in for a surprise when they spawn in

**Review by PowerfulBacon — APPROVED** [review]
Code ownership

**Comment by francinum** [comment]
Order them.
🔑

**Pull request closed without merging**
