### PR TITLE
Adds white and black decal colors along with flat decal patterns for monotiles

### PR DESCRIPTION
**Pull request by BarteG44**
## About The Pull Request

First PR that simply adds #ffffff and #000000 decal colors along with a flat decal sprite.

## Why It's Good For The Game

Adds more decoration options for mappers 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

obraz

</details>

## Changelog
:cl:
add: Added black and white decal colors
add: Added flat floor decals for monotiles

/:cl:

### CODE REVIEW

**Comment by PestoVerde322** [comment]
As far as i know, monotiles are in a bit of a weird spot regarding the design philosophy, since they got shunned by Crossed afaik.

Other than that, black and white decals might be a good tool for further customization.

**Comment by BarteG44** [comment]
> As far as i know, monotiles are in a bit of a weird spot regarding the design philosophy, since they got shunned by Crossed afaik.
> 
> Other than that, black and white decals might be a good tool for further customization.

I mean since we have the monotiles then we might as well have the decals for them

**Comment by BarteG44** [comment]
me when i click funny close button becouse i don't know what it does

**Review by PowerfulBacon — APPROVED** [review]
Seems fine

**Pull request merged**
