### PR TITLE
Gives Botanists a bee crate and beekeeper outfits by default.

### PR DESCRIPTION
**Pull request by USB3pt0**
## About The Pull Request

Adds Beekeeper Outfits to the locked Hydroponics closets, and replaces the backroom hydroponics crate that usually has a few vendable tools with a Beekeeper Starter Crate on all maps but Kilo.

## Why It's Good For The Game

Beestation is woefully underpopulated by bees.  Most people forget they're even in the game.  For a name like Beestation, that simply will not do.  This aims to change that with an optional large influx of bees each round by giving botanists the gear they need to keep bees from roundstart.

## Changelog
:cl: Nova Remnant
add: Added beekeeper hat and suit to hydroponics closets.
tweak: Changed hydroponics backroom crate to beekeeper starter crate.
/:cl:

### CODE REVIEW

**Comment by jupyterkat** [comment]
time for amanitin bees

**Comment by eeSPee** [comment]
On the one side, yes.

On the other side, kinda defeats the purpose of cargo packs.

**Comment by Archanial** [comment]
No, this is bad idea. Just order them from cargo.

**Comment by DatBoiTim** [comment]
Similar to eespee

On the one hand, this is BEEstation, why not add the option to have some bees for botany to start with?

On the other bees can get pretty crazy.

**Comment by KennyBadrige** [comment]
QOL cargo out of existence, sick.

**Comment by USB3pt0** [comment]
I can't believe cargo has existed for all this time exclusively to order bees for botany

**Comment by francinum** [comment]
No.

**Pull request closed without merging**
