### PR TITLE
[WIP] Adds royal cloak to beecoin shop attempt 2

### PR DESCRIPTION
**Pull request by Sinmero**
## About The Pull Request

There is only the masculine hat at beecoin shop for 100k coins so i thought to add something cool to choose from.
Added royal cloak to the beecoin shop for 100000 beecoins. The cloak comes in four colors and you can switch its colors by using it in your hand.
red, blue, purple and black

## Why It's Good For The Game
Beecoin shop has more cool items now.

## Changelog
:cl:
add: Added royal cloak to beecoin shop
imageadd: added royal cloak sprites
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
This needs to be consulted with Naevi, our lead cloak designer

**Comment by february-ops** [comment]
> This needs to be consulted with Naevi, our lead clock designer

Clock

**Comment by Naevii** [comment]
I dislike the idea for a few reasons :
1. for something that anyone can obtain by playing it's a bit too much and takes away that "special" factor from having heads of staff cloak. i would suggest making it a bedsheet instead. 
2. Pattern is too vibrant/ catches too much attention in my opinion, it should be more blending in with the rest of the game. 
3. Blue cloak seems too similar to captain cloak. 
EDIT. In fact all of this cloaks seems like they could belong to captain.

**Comment by ike709** [comment]
Good idea, bad sprites.

**Comment by Naevii** [comment]
I was thinking about making some capes for donors instead of beecoin shop.

**Comment by Bestparty** [comment]
> I was thinking about making some capes for donors instead of beecoin shop.

that will get the donator minority persecuted even more

**Pull request closed without merging**
