### PR TITLE
Enables extended in Sage config

### PR DESCRIPTION
**Pull request by Cenrus**
Extended is a fine mode, and a lot of people on Sage like longer shifts where they have time to build huge projects and such.

:cl:
config: Enabled extended mode on BeeStation Sage
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
Any shift longee than two hours is bad

**Comment by qwertyquerty** [comment]
Huh I thought it was already on

**Comment by Cenrus** [comment]
Also, all the station goals are unlocked on extended, and not on secret extended.

**Comment by qwertyquerty** [comment]
@Crossedfall configgies

**Pull request merged**
