### PR TITLE
FluoroSulphuric Acid and Water/Holywater now explode

### PR DESCRIPTION
**Pull request by DatBoiTim**
## About The Pull Request
Adds a an explosiong that is between water/potassium and methsplosion in power, in exchange for requiring slightly more effort to make.
It has a holy variant too.

## Why It's Good For The Game
Adds a new level of effort:explosion power ratio. Placed somewhere between water/pot and methsplosion. Helps people really choose what exactly they need for an explosion (lower effort:small boom vs. higher effort:big boom).

## Changelog
:cl: DatBoiTim
add: Added a reaction for water and fluorosulphuric acid that explodes
add: Added holy water variant of the water fluorosulphuric explosion
/:cl:

### CODE REVIEW

**Comment by utilbird** [comment]
flurosulf isn't really high effort though, it's much much less than meth. It shouldn't be halfway imo

**Comment by DatBoiTim** [comment]
> flurosulf isn't really high effort though, it's much much less than meth. It shouldn't be halfway imo

Big thing is there's not exactly much room between halfway and methsplosion and vice versa.

Also, never said high effort, just more than: dispense 50u water, 50u pot and bang presto a(weaker, relative to others) explosion.

**Comment by zeskorion** [comment]
But meth isnt effort at all

**Review by Archanial — COMMENTED** [review]
This is stupid, doesn't make much sense and is direct counter to cult for some reason.

**Comment by DatBoiTim** [comment]
> This is stupid, doesn't make much sense and is direct counter to cult for some reason.

It's a real thing(sort of); apparently what I was told vs. reality is quite different. IRL the "explosion" of water and acid is not the kinetic kind, it more so sprays acid everywhere.

Finding this out now I'll model it better.

Also the counter to cult requires holy water.

**Comment by utilbird** [comment]
> It's a real thing

It should be less powerful than potassium water if you're going for realism

**Comment by DatBoiTim** [comment]
> > It's a real thing

As I said how it was described initially and my research into the phenomena to prove it I discovered it's far weaker. Also I'm closing this for a different PR that will supersede this

**Pull request closed without merging**
