### PR TITLE
Updates Hos Coat.

### PR DESCRIPTION
**Pull request by Naevii**
## About The Pull Request

So noone wanted to wear this coat, i decided i could give it a small refresh.
dreamseeker_boPW0Q6Vtl
hvrAxoYwcN

MediBangPaintPro_K9dj5OGgkm

## Why It's Good For The Game

Updates Hos coat to current standards. 

## Changelog
:cl:
imageadd: Updated HoS greatcoat.
/:cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
I will die on this hill. Greatcoats have two rows of buttons. If we're sticking with one, just rename the jacket.

**Comment by Naevii** [comment]
> I will die on this hill. Greatcoats have two rows of buttons. If we're sticking with one, just rename the jacket.

is it that important ? 
the other row of buttons is hidden >:(

**Review by francinum — APPROVED** [review]

**Comment by Raven-Industries** [comment]
I wholeheartedly agree that only a double-breasted coat deserves the name greatcoat, but it's very difficult to pin down what else it could be. After 30 minutes of looking at coats, I think it could be either  a Chesterfield coat or an Over-frock coat. As a Chesterfield coat, it has the proper length down to the knee, and sort of the right collar for it. As an Over-frock, it has the hourglass figure that a properly tailored Over-frock would have, and it looks bulky and heavy enough for it. Personally, I'd lean towards calling it an Over-frock, but either could work. Or we could call it a greatcoat and thereby water down the tradition and style of what it truly means to be a Greatcoat. 
Regardless of the name though, it looks fabulous.

**Review by park66665 — APPROVED** [review]
1. Greatcoats can have a single row of buttons: definition of greatcoat is simply "heavy" overcoat.
2. Chesterfield coats don't look like that.
3. Over-frock coats also don't look like that.

**Pull request merged**
