### PR TITLE
EMT

### PR DESCRIPTION
**Pull request by hackerjsimon**
A job where your duty is to both work on medical in terms of building new machines and advancing its technology while also monitoring the halls for corpses. The right-hand men for the CMO

## About The Pull Request

Adds EMT
Other files include EMT hardsuit

## Why It's Good For The Game
Adds more depth to medical where it has its own two workers who operate best at emergency.

## Changelog

add EMT
add New job
change spawn position
add EMT hardsuit

### CODE REVIEW

**Comment by qwertyquerty** [comment]
I would say move the total and spawn slots down to 2 or 1. Also please edit your post to reflect the changes in the changelog section.

**Comment by qwertyquerty** [comment]
It looks like you didn't even add your file to the dme. A clear sign you didn't test this. Also your flag variable is invalid, you'll actually have to add a flag for it.

**Comment by ike709** [comment]
Also you should lowercase `EMT` in the typepath so the syntax highlighter doesn't confuse it for a define.

**Comment by hackerjsimon** [comment]
Im on a Chromebook I cannot test this so I basically ran this through I will edit tho thank you


For now just ignore this ill update it when i get my pc ill test and properly be able to edit it

**Comment by qwertyquerty** [comment]
...no keep the file a DM. But you do need to include the name of the file in beestation.dme. Tou should probably just drop development until you get your PC. Closing this now.

**Pull request closed without merging**
