### PR TITLE
Locks squidpeople behind paywall

### PR DESCRIPTION
**Pull request by Wilchenx**
Originally I wanted squidpeople to be a special race, hopefully this change will let the playerbase feel the _**sense of pride and accomplishment**_ for supporting the server.

## Changelog
:cl:
config: Squids are now paywalled
/:cl:

### CODE REVIEW

**Review by qwertyquerty — CHANGES_REQUESTED** [review]
Your indentation is messed up and you haven't corrected formatted your pr, nor do you have a CL. If you're gonna meme, do it right.

**Comment by qwertyquerty** [comment]
Checks fail

**Comment by qwertyquerty** [comment]
Closing as I'm moving the system to config

**Comment by TeomanTheGreat** [comment]
Wilchen upset cats were going to be paywalled so they tried to paywall the species they made themselves a while back. Lol

**Pull request closed without merging**
