### PR TITLE
radio hiss, once again from IS13

### PR DESCRIPTION
**Pull request by CthulhuOnIce**
Adds radio hiss, which is a static-y noise you hear when hearing people talk on the radio

### CODE REVIEW

**Comment by qwertyquerty** [comment]
I very much so do not want this

**Comment by ghost** [comment]
this is dumb

**Comment by CthulhuOnIce** [comment]
Why?

**Comment by CthulhuOnIce** [comment]
Also it's not dumb, radios make noise

**Comment by ghost** [comment]
annoying

**Comment by ghost** [comment]
this is advanced space radios not your pas radio from ww2 in the basement

**Comment by CthulhuOnIce** [comment]
Still a radio

**Comment by qwertyquerty** [comment]
can confirm annoying

**Comment by MACIEKBAKI** [comment]
add  player-side option to turn it on/off

**Comment by qwertyquerty** [comment]
Agreed

**Pull request closed without merging**
