### PR TITLE
[Port] Hands up, clown! Hold people at gunpoint.

### PR DESCRIPTION
**Pull request by SomeAngryMiner**
## About The Pull Request

This PR is simple: Ports Gunpoint holding from /TG/.
what does this do, anyway?
Well, if you click someone on grab intent with your gun selected, youll start to hold them at gunpoint, and any movement or attack will trigger a shot from the holder.
If you hold someone at gunpoint between 3-10 seconds, the damage will be increased to x2, and even more time (more than 10 seconds), it will deal 2.5.
The holder can roam freely two tiles away from the hostage, but being away from that range or breaking visual contact will take them out of gunpoint.
PRs used are:
tgstation/tgstation/pull/47677
tgstation/tgstation/pull/45843 for compatibility with TG code.
## Why It's Good For The Game

Adds a good strategy, and makes holding people hostage more dangerous, allowing people to actually be compliant to not get domed, not it being only "pull big gun faster and shoot before he does"

## Changelog
:cl: Ryll/Shaps/nemvar
add: After a quick instruction onboard training camp 11, All crewmembers will be able to profficiently hold people at gunpoint, with increased lethality if you hold them for enough time. For doing this, use a gun on someone while having drag intent.
/:cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
Remember to give credit to the original authors in your CL. Added them in this time around.

Test merging onto golden.

**Review by Crossedfall — CHANGES_REQUESTED** [review]
Kills the MC. Didn't actually cause a crash, but testing with Bass we managed to get things into defcon 3.  This tends to happen if you aim too many times on a target or if you aim at someone who is already aiming at you.

**Comment by Bastian0930** [comment]
Actually, we hit defcon 1 at one point. Shits fucked.

**Comment by Ryll-Ryll** [comment]
I fixed it in the original PR, and also limited you to one hold-up at a time (even if that wasn't what caused this)

**Comment by ike709** [comment]
This is why you don't port PRs that haven't been merged yet.

**Comment by ike709** [comment]
You need to fix the conflicts and also get the commits you missed from TG's pull.

**Comment by SomeAngryMiner** [comment]
problems adressed, should be ready for a second testmerge.

**Comment by SomeAngryMiner** [comment]
checks out, on travis.

**Comment by ike709** [comment]
It doesn't work very well. Also, clicking people initiating it when clicking is also the key to fire the gun is just bad design.

**Comment by Ryll-Ryll** [comment]
I'm confused because you don't seem to have ported all the fixes that I made in the original PR, specifically the "point_of_no_return" var that prevents the race conditions that was causing the lockups you guys pointed out earlier

either way, happy trails!

**Comment by SomeAngryMiner** [comment]
well, ill try again, sometime, not today, though.

**Pull request closed without merging**
