### PR TITLE
Two new traitor items: Energy Saw Arm Implant for MDs/CMO and Laser Arm Implant for robos/RD

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
Adds two new traitor items: the Energy Saw Arm Implant for MDs/CMO and the Laser Arm Implant for robos. Both come in a suspicious autosurgeon for self-implanting. 

Energy Saw Arm Implant is basically the same one Syndicate Medical Cyborgs use. Does the same damage as esword but unlike the esword it's no-drop and is cheaper, though it doesn't have the melee block chance. Also being an implant it's better hidden than an esword, though that does also mean a vulnerability to EMPs.

Laser Arm Implant is basically the Captain's Antique Laser but in an arm implant, though it has a bit less energy capacity. 

## Why It's Good For The Game
More traitor items, more based. 

## Changelog
:cl:
add: New MD/CMO traitor item: Energy Saw Arm Implant. Costs 8 TC.
add: New robo/RD traitor item: Laser Arm Implant. Costs 12 TC.
add: Syndicate implants now come in a suspicous autosurgeon
/:cl:

Ports:
https://github.com/tgstation/tgstation/pull/49398

### CODE REVIEW

**Comment by zeskorion** [comment]
> ## About The Pull Request
> Adds two new traitor items: the Energy Saw Arm Implant for MDs/CMO and the Laser Arm Implant for robos. Both come in a suspicious autosurgeon for self-implanting.
> 
> Energy Saw Arm Implant is basically the same one Syndicate Medical Cyborgs use. Does the same damage as esword but unlike the esword it's no-drop and is cheaper, though it doesn't have the melee block chance. Also being an implant it's better hidden than an esword, though that does also mean a vulnerability to EMPs.
> 
> Laser Arm Implant is basically the Captain's Antique Laser but in an arm implant, though it has a bit less energy capacity.
> 
> ## Why It's Good For The Game
> More traitor items, more based.
> 
> ## Changelog
> 🆑
> add: New MD/CMO traitor item: Energy Saw Arm Implant. Costs 8 TC.
> add: New robo traitor item: Laser Arm Implant. Costs 10 TC.
> add: Syndicate implants now come in a suspicous autosurgeon
> /🆑

laser arm implant should either be more expensive or have a different charging method

**Comment by Isy232** [comment]
Would 2 laser arm implants dual wielded work?
That sounds bad ass.

**Comment by VictorVow** [comment]
No, currently it only fits in the right arm via autosurgeon. You'd need to screwdriver out the implant and have someone else implant you. I think autodoc also defaults to right arm only.

**Comment by qwertyquerty** [comment]
I think this still needs nerf

**Comment by VictorVow** [comment]
Which one, and in terms of cost or something else? Bumped the laser arm up to 12 TC already.

**Pull request merged**
