### PR TITLE
Re-adds the best quirk ever. Of all time.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

AAAAAAAAAAH, I love people that I can't swap places with. We will now have the Physically Obstructive quirk.

## Why It's Good For The Game

This quirk is so good. Removing it was the worst decision TG has made in the last 3 years.

## Changelog
:cl:
add: Added the "Physically Obstructive" quirk.

/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
what the fuck this was removed?

**Comment by PowerfulBacon** [comment]
probably because its a dumb perk where the biggest negative is on other people rather than yourself.

**Comment by Sinestia** [comment]
this perk

and walking around on not help-intent

should make you valid 


(it should cost 1 point its a perk that makes you an obnoxious cunt. or make it a feature of being fat if it isn't so you have to be an uggo lardass)

**Comment by ghost** [comment]
The downside should be that you can't get up without someone else helping you up.

Why is a positive trait for the user like this even granting points?

**Pull request closed without merging**
