### PR TITLE
(Partial) Revert "Improves player security checks for Cyborg and Mechs"

### PR DESCRIPTION
**Pull request by Crossedfall**
## About The Pull Request

Partially Reverts BeeStation/BeeStation-Hornet#8610

## Why It's Good For The Game

The offending PR changed all of the role time requirements without documented it. 

## Testing Photographs and Procedure
N/A

## Changelog
:cl:
tweak: Undocumented role time requirement changes have been reverted
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
Can you just revert the hours stuff?

**Comment by Crossedfall** [comment]
> Can you just revert the hours stuff?

That's what I'm doing

**Review by itsmeow — APPROVED** [review]

**Comment by Rukofamicom** [comment]
image

image

image

image

image

**Comment by Crossedfall** [comment]
We went over this in discord. There was no documentation on the actual modifications that took place. Just saying you, "tweaked" the times to be more consistent was woefully inaccurate for multiple roles.

**Pull request merged**
