### PR TITLE
[Ruko PR recoup] Mining progression overhaul (this one is the nerf)

### PR DESCRIPTION
**Pull request by PestoVerde322**
## About The Pull Request

_**This pr is a recoup of https://github.com/BeeStation/BeeStation-Hornet/pull/6812, all the details are in there, as fundamentally it's all the same save for some tweaks within the code.**_

## Why It's Good For The Game

_See the original PR for why it's good._

## Testing Photographs and Procedure

<summary>Screenshots&Videos</summary>

_See the original PR for screenshots._

</details>

🆑 Rukofamicom(recouped and updated by PestoVerde322)
tweak: basic mining satchel now holds up to 250 ores, 5x more than it previously could
tweak: Mining vendor now has both varieties of plasma cutter as well all but three of the PKA mods, including most which were previously only available through tendril loot
tweak: ORM gives substantially more points per ore, but upgrades only increase efficiency for the station instead of miner payouts for handing ores in.
balance: Mining research no longer includes plasma cutters. Mining AoE PKA mod is now part of basic research instead of advanced, and the repeater and complete AoE mods are now part of advanced research.
balance: Tendril chests now have a much higher chance to award desirable loot - all PKA mods except the lifesteal crystal have been removed from tendril chests. Overall these mods made up 40% of the drop table, so keys have been increased about 40% in price to compensate.
tweak: PKA Lifesteal crystal no longer has a capacity cost to equip - no more rearranging mods to make room for it
tweak: Megafauna now drop locked chests with their primary loot inside of it, in addition to their pile of ores. Ash Drake armor is now included in the Ash Drake drops, and crafting it is only possible for Ashwalkers who stumble onto the corpse.
tweak: Megafauna now always drop one crusher trophy, regardless of how they were killed, as a part of their chest loot.
add: Staff of storms and Staff of lava are now available as tendril loot, but they may only be used on lavaland.+
code: add future infrastructure for weighted lavaland loot, for now it's unused.
/🆑

### CODE REVIEW

**Comment by Kratairo** [comment]
Though that begs the question as to why you increased the key cost with the logic of removing useless drops while readding more useless drops balancing it out? (The staffs are utterly useless cant tell me otherwise, even when mining wasnt nerfed no one ever bothered using them because of how bad they are lol)

**Comment by Rukofamicom** [comment]
> The staffs are utterly useless cant tell me otherwise

*Watch me*

Get over your self-centered way of thinking. Not every miner can kill an ash drake no-sweat like the seasoned explorers can. If you lack the experience and knowledge of how to down then consistently, ash storms are a significant roadblock and hazard. Staff if storms is a nice boon for this.

Lava staff has to compete with the RCD, but the RCD is also a tool miners don't explicitly have access to. Being able to create lava can have niche uses against Ashwalkers when not just outright raiding their nest fullstop. Definitely less useful than the staff of storms overall.

> while readding more useless drops balancing it out?

Even if you think both staffs are useless and refuse to accept what I said above as factual, adding two staves is not equivalent to the mountain of things removed. The odds are still substantially improved because the pool is much smaller.

**Comment by Kratairo** [comment]
You seem to forget that the staffs are BULKY items meaning that you can carry it around, unless you think people should carry it for 30 minutes to get rid of 2 storms? Maybe if you made them smaller they would have some niche uses (seriously though if you can defeat a tendril you can defeat a dragon just do that)

**Comment by Rukofamicom** [comment]
> seriously though if you can defeat a tendril you can defeat a dragon just do that

I see I have failed to remind you of the time you weren't very good at the game either. 

You raise a good point about the size of the items, though that is the case for all magic-on-a-sticks including the heiro club.

**Review by PowerfulBacon — APPROVED** [review]

**Review by itsmeow — APPROVED** [review]

**Pull request merged**
