### PR TITLE
Removing Unecessary Ducting Timer

### PR DESCRIPTION
**Pull request by DatBoiTim**
## About The Pull Request
Ductnets, on removal of a duct piece, would iterate through a list of ducts, and call timers to reconnect and generate the contents of the duct. These timers had a duration of 0. LITERAL SPAGHETTI CODE.

## Why It's Good For The Game
SPAGHETTI CODE IS BAD AND YOU SHOULD FEEL BAD FOR WRITING IT

## Changelog
:cl: DatBoiTim
refactor: Removed 2 Absolutely Useless Timers from ductnet code
refactor: Now uses asynchronous invocation of the procs
/:cl:

### CODE REVIEW

**Comment by DatBoiTim** [comment]
I didn't reset my master branch to upstream/master but whatever

**Comment by PowerfulBacon** [comment]
This timer is actually very important as it prevents the 2 called procs from blocking the execution of the list. However addtimer with 0 should not be used, instead INVOKE_ASYNC should be used instead.

**Comment by DatBoiTim** [comment]
> INVOKE_ASYNC

Gonna get that rolling

**Comment by DatBoiTim** [comment]
> This timer is actually very important as it prevents the 2 called procs from blocking the execution of the list. However addtimer with 0 should not be used, instead INVOKE_ASYNC should be used instead.

9fc2e12 now compliant

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
I think this breaks it, the timer is very important and delays the call until after the qdel(src) line.

**Pull request closed without merging**
