### PR TITLE
Red lights and alarm in red and delta!

### PR DESCRIPTION
**Pull request by Dejaku51**
## About The Pull Request
Adds new sound alarms and red lights on red and delta alarms. Videos showing them are in Screenshots&Videos. Alarms can be muted by toggling admin MIDIs
Also includes minor code change for lights

Original pr: https://github.com/aq33/tgstation/pull/510

## Why It's Good For The Game

Everyone should know that station will soon explode or if there is something scary on station that they should watch out for

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Red alert:

https://user-images.githubusercontent.com/40302913/173552210-3b0a3a0e-5892-4ed0-9571-323bf436ed1a.mp4

Delta alert:

https://user-images.githubusercontent.com/40302913/173552347-f342a0a8-f989-4f89-89cb-463106ec804b.mp4

</details>

1. Use the Set-Security-Level to change security level to red or delta
2. You can hear the alarm and see the lights change to red

## Changelog
:cl:
add: Added sound alarms in red and delta
add: Added red lights in red and delta
soundadd: Added sounds for red and delta alarms
code: minor lights code cleanup
/:cl:

### CODE REVIEW

**Comment by Dejaku51** [comment]
Removal? what

**Comment by PowerfulBacon** [comment]
Doesn't this cause a massive lag spike? I tried to do something similar when doing my lighting stuff

**Comment by Dejaku51** [comment]
like during changing to red/delta or what?

**Comment by Dejaku51** [comment]
doesn't looks like it causes massive lag spikes, it **might** act differently during highpop tho

**Comment by AnCopper** [comment]
Is that the fucking Among Us reactor alarm?

**Comment by Dejaku51** [comment]
> Is that the fucking among us reactor alarm?

omfg i didn't noticed that
lmaooo

**Comment by DerpiestBruh** [comment]
sus

**Comment by Howluinb** [comment]
The idea's good. The choice of sound effects... really isn't. It sounds so dumb

**Comment by mcmeiler** [comment]
The delta alert sound is *hella sus*

Otherwise this is really minor.

**Comment by EvilDragonfiend** [comment]
I am fine with delta one sound, but I am afraid that red alert sound is consistently noisy which isn't sane, I believe.

**Comment by PowerfulBacon** [comment]
Considering one of the sounds is literally the among us reactor alarm, sound effect source and licenses?

**Comment by itsmeow** [comment]
I wasn't able to find ANY information about the among us reactor sound effect, but I did see a youtube comment that said it was the soviet EAS sound - not sure if this is true or not, couldn't find anything to back that up.

Also, red alert sound should only play once or twice.

**Comment by PowerfulBacon** [comment]
> I wasn't able to find ANY information about the among us reactor sound effect, but I did see a youtube comment that said it was the soviet EAS sound - not sure if this is true or not, couldn't find anything to back that up.
> 
> Also, red alert sound should only play once or twice.

Watch delta.mp4 and then watch this
https://www.youtube.com/watch?v=o1416gXg1Fc&t=3s

**Comment by itsmeow** [comment]
No, I'm aware it IS the among us sound, I'm trying to see if among us got it from somewhere else

**Pull request closed without merging**
