### PR TITLE
FOV Test

### PR DESCRIPTION
**Pull request by DrDuckedGoose**
## About The Pull Request

DO NOT MERGE

This is a test for Point of View, which will occlude certain parts of the screen next to and behind the player mob.
The code here probably isn't the best, it's just to help us understand what works and how players *feel* about FOV
Also adds 'combat mode' mouse facing. Being on the harm intent will make your character face the mouse cursor.

## Why It's Good For The Game

Maybe it isn't

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image
image
image
image

</details>

## Changelog
:cl:
add: FOV
add: harm-mode mouse following
/:cl:

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
Even if not used for the crew, it would still be useful to have in the code

**Comment by Nakalon** [comment]
could be used for some masks or equipment.

**Comment by TsunamiAnt** [comment]
would it be possible to have the new blind sound visualisations appear in that area? would be cool to see steppies and such happening behind you.

**Comment by DrDuckedGoose** [comment]
Absolutely
The code for this, looking at it now, isn't the best.

I just want to know if players can cope with this effect before I implement it fully.

**Comment by PowerfulBacon** [comment]
I do like the idea of POV, although there are some caveats that come with this implementation:
- Mobs will always be on top of objects, no matter their intended layering. This would probably need to have the filter applied directly to the objects that should be masked, rather than storing them on a different layer although I'm not sure if that will come with troubles in of itself
- defining /atom/MouseEntered is not ideal, however this could be mostly mitigated by having a mouse enter catcher that determines which direction the player should be facing.

We can always testmerge this in its current state though

**Comment by DrDuckedGoose** [comment]
> I do like the idea of POV, although there are some caveats that come with this implementation:
> 
> * Mobs will always be on top of objects, no matter their intended layering. This would probably need to have the filter applied directly to the objects that should be masked, rather than storing them on a different layer although I'm not sure if that will come with troubles in of itself
> * defining /atom/MouseEntered is not ideal, however this could be mostly mitigated by having a mouse enter catcher that determines which direction the player should be facing.
> 
> We can always testmerge this in its current state though

The first point is kinda the result of my shitty implementation, I think there's another way I could implement this without that problem.
Second point is a thinker, for sure. I personally like my way, because we can use it to implement pop-up and tooltip shit

I honestly just want to see how players react before I invest legitimate time into it.

**Review by PestoVerde322 — COMMENTED** [review]
Iconwise good, but i'll hold untill TM for approval, even if personally this is great for future implementation of stuff like dirlighting and whatnot.

**Comment by llol111** [comment]
Im not a fan of this conceptualy, at least for it being default for evryone. I cant provide a better reason for why that is, besides "i dont like it" and "its annoying". I just dont super see the point in restricting vison like this, people can turn their head without needing to physicaly turn around, yes?
I would however absolutely like to have this in game as an option for adminbus or for events or something, could be good for annoying people or horror themed event rounds

**Comment by Crossedfall** [comment]
Bugs found in the TM:

- The view cone for mechs is locked 
- Cameras that act as eyes have a locked view cone (e.g. AI cameras and Xenobio slime cameras)

**Comment by Fronsis** [comment]
Bugs/Issues i found during the TM:

1- The Mecha thing that Crossed reported

2- An issue with.. sprite updating? I don't know how to describe it but:

I disconnected this AI camera and when looking at it it still showed it as an active camera(examine showed it was in fact disabled) when i turned around, the FOV showed it correctly disabled
Screenshot_54
Screenshot_55

This might apply to any type of ''tube'' but it would be nice to not have the FOV when inside a nanite machine/gene machine/sleeper/cryotube/etcetera or at least tweak it to make it have a FOV facing a very specific direction, otherwise you end up with angles like this which are.. weird, i mean most of those machines are transparent after all but yeah, it's a little off putting, i haven't tried with the rest of the machines
Screenshot_56

I already mentioned on discord but leaving it here so you just don't forget! the CTF lightning is pretty much broken
Screenshot_58


That's all for now, hope it helps!

**Comment by Crossedfall** [comment]
CTF lighting would be unrelated, looks like there's already a fix #10798

**Pull request closed without merging**
