### PR TITLE
Revert "Chemical Synthesizer rework #6281", but nerfs the plumbing with extreme delay instead (+plumbing investigate log)

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
* Reverts #6281
* And nerfs the plumbing that it processes chem at a miserable rate instead
chem will be processed about 1u per 5 seconds (approximately)

## Why It's Good For The Game
the gamer chemists bypass the nerf through input gates by manual chem injection, eventually they can make synth factory anyways.
reverts the nerf so that they can make a factory anyways, but chem processing is now at a miserable speed than before so you need to manage medical resources.

Plus, I really don't like examining every chem synthesizer and filling it with a cartridge. It's not the right way to nerf it.

Note: the chem process delay can be even slower than this if it makes a lot of medicines still.

## Testing Photographs and Procedure
https://youtu.be/pskFb0-bFBE

<details>
<summary>Screenshots&Videos</summary>

image
`[2022-07-21 21:26:40.176] GAME: a factory medicine factory bottle has been created. chem list: Bromine, Copper, Phosphorus, Lithium and Potassium`

Investigate log

</details>

## Changelog
:cl:
tweak: reverts "Chemical Synthesizer rework #6281" that you need compressed matter cartridges to charge synthesizers
balance: Chem synthesizer only can produce 1u of a chemical
balance: plumbing now processes chemical transference by 1u per 3 seconds (approximately)
add: Plumbing tank can pull chemicals at a double speed than other plumbing machines do.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Can we put a huge power cost onto he synthesisers as a replacement to needing matter?

**Comment by EvilDragonfiend** [comment]
> Can we put a huge power cost onto he synthesisers as a replacement to needing matter?

I think it will eventually enable spamming medicines that the current coders wouldn't want it. but also, I don't know how `a huge power` would exactly be. there might be something exclusive (like xeno artifact?) to make it rare.

**Comment by Pro-gamer-window-vista10** [comment]
> Can we put a huge power cost onto he synthesisers as a replacement to needing matter?

yeah make them be wired like emitters and use something really high like 50-150kw each so that if you make a synthflesh factory/any kind of factory really roundstart you will cause a blackout

**Comment by ivanmixo** [comment]
Can we just remove it completely instead already holy shit.

**Comment by EvilDragonfiend** [comment]
> Can we just remove it completely instead already holy shit.

unless you're giving them another toy or another candy, I believe removing isn't good.

**Comment by mcmeiler** [comment]
No, being able to create things which replace entire departments, for free, without any user input are absolutely fucking stupid and should not exist in the game to begin with. This PR changes nothing as they will just spam synths instead.

> Can we put a huge power cost onto he synthesisers as a replacement to needing matter?

This also changes nothing. Power is free. There has to be a tangible resource cost, not an arbitrary number which skyrockets above what the entire station needs combined about 3 minutes into a round.

**Comment by PowerfulBacon** [comment]
Power isn't free, someone has to setup and maintain the power grid. If you mean that the chemist's don't have to do anything for that then matter cartridges are free and that doesn't matter, this is a game about interactions and working together, so there isn't a problem with depending on something else.

**Comment by EvilDragonfiend** [comment]
> This PR changes nothing as they will just spam synths instead.

You sure?

https://youtu.be/mG2aYiNollY

This is the result when you make 40u mannitol. It took approximately took 5:40, which is 340 seconds.
When considering synthflesh needs a lot of setups, it would take more time than 340 seconds to produce a single 40u synthflesh patch.
So, you can hardly spam medicines with this.

> Power isn't free, someone has to setup and maintain the power grid. If you mean that the chemist's don't have to do anything for that then matter cartridges are free and that doesn't matter, this is a game about interactions and working together, so there isn't a problem with depending on something else.

The current concern about plumbing is not to spam medicines, not to prevent doing plumbing.

**Comment by EvilDragonfiend** [comment]
okay, with some calculation result, 40u synthflesh patch will likely be produced at 300 seconds at a current value (I buffed a bit from the last pull) This means you will get total 480u synthflesh for an hour. I think it's at a reasonable rate than before.

**Comment by Coding-Grape** [comment]
This is ass 
Not because of the chem synth nerf, that's valid
But because it just utterly fucks with me using a reaction chamber to set exact reagent ratios for pills because we have no other way other thsn doing mind numbing math and making 10 at a time with the chemmaster 

So many reagents work best at certain amounts or ratios

Perflurodecalin should be mixed with twice as much antitoxin, and should really only be dosed at 2u, more is overkill
Salicylic acid and oxand heal 100 brute/burn at 6.6u pills, over that is overkill
Hell, making styptic powder and silver sulf patches for general first aid is just a fucking pain with the chemmaster because you have to set the name the exact same every. Single. Time.

I would be all for this if there was a major chemmaster rework that let me actually fucking set how much of each reagent I want in a pill or patch, along with a name instead of how many pills I want to get

**Comment by PowerfulBacon** [comment]
> This is ass 

Use reaction Chambers. They can be used on chems that don't react to set exact proportions.

**Comment by mcmeiler** [comment]
> this is a game about interactions and working together

Then why do we have plumbing, a mechanic that actively discourages interaction, in the code

**Comment by EvilDragonfiend** [comment]
btw, honestly, I am not sure the delay value. I believe this should be testmerged than actual merge then see the exact value in actual playing environment

**Comment by EvilDragonfiend** [comment]
Plumbing should be refactored after we have sane chem/metabolisation/medical system. Doing it at this time won't be that helpful to the game. Closing.

**Pull request closed without merging**
