### PR TITLE
Refactors disease properties

### LINKED ISSUE #4192: [Refactor] Rename Transmittable In Assoc List for Advanced Diseases to Transmission
Feature requests are handled in the repository, but you could also discuss your ideas on beestation discord or forums here: https://forums.beestation13.com/

This would save many people sanity. This is mostly a tedious thing I do not want to do since I have other things to work on.

Literally change the name and any references to it. Please double check that all symptom thresholds match this(cause some use a different name for the transmission stat).

If nobody does this I'll eventually do it myself. I just do not want to prioritize a tedious rename.

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Changes name of severity to danger.
Removes properties, each property has its own var now.
Renames transmittable to transmission.
Also removes some useless functions and move some ifs in diseases.

closes: #4192

## Changelog
:cl:
refactor: Disease properties are removed, each property has its own var.
refactor: Disease severity is renamed to danger.
refactor: Disease transmittable is renamed to transmission.
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
Shouldn't affect the game besides severity renamed to danger in tgui

**Comment by zeskorion** [comment]
Why is severity changed? Severity causes no issues. The problem is Transmittable and Stage_rate being those names instead of Transmission and Stage_speed, which causes confusion when coding

**Comment by Archanial** [comment]
Because there is severity of the disease (defined) and severity in stat. Two of those names were colliding.

**Comment by DatBoiTim** [comment]
Bounty Paid, good to see some extra refactor was put in as well.

While I wish stage_rate was changed as a standalone VSC should recognize it with predictive code.

**Comment by zeskorion** [comment]
> Because there is severity of the disease (defined) and severity in stat. Two of those names were colliding.

But those are the same thing?

**Comment by Archanial** [comment]
I am not sure what you mean by this but old severity is a strong define, new one is their statistic (number).

**Comment by Archanial** [comment]
we like tgui conflicts

**Comment by DatBoiTim** [comment]
TGUI conflicts my beloved ❤️

**Review by utilbird — APPROVED** [review]

**Pull request merged**
