### PR TITLE
Randomizes Box and Meta's Roundstart Engine

### PR DESCRIPTION
**Pull request by Kerbin-Fiber**
## About The Pull Request
BoxStation and MetaStation will be given a random engine type roundstart. It can either spawn with the typical Supermatter setup, or have a Particle Accelerator with either a singularity generator xor tesla generator.

As of now, the SM and PA setups are 50/50 chance. In the case of the PA setup being chosen, the singulo/tesla generator is also a 50/50 chance. I'm not great at math but I think it's technically 50% for SM and 25% for either Singulo and Tesla.

## Why It's Good For The Game
Fun engineering variety.

## Changelog
:cl:
add: BoxStation and MetaStation no longer only have a Super Matter crystal. You may find yourself having to setup a Singularity engine, or even a Tesla to generate power. All three engine types can spawn at roundstart, but only one WILL spawn.
/:cl:

### CODE REVIEW

**Comment by Mick1299** [comment]
Interesting use of the random maints tool, didn't even think of this

**Comment by ACanOpener** [comment]
But what if nobody on the station knows how to make the engine

**Comment by Kerbin-Fiber** [comment]
https://wiki.beestation13.com/view/Singularity_and_Tesla_engines

Not to mention, this doesn't remove Solars, so in the rare case no one knows and doesn't use the wiki, they can do that instead.

**Comment by ike709** [comment]
Lord singuloth should be a bit rare to prevent instant singuloose.

**Comment by PowerfulBacon** [comment]
Super cool, hopefully we can port to lobby and remove the godawful teg

**Comment by Crossedfall** [comment]
> 
> 
> Super cool, hopefully we can port to lobby and remove the godawful teg

Just adjust the power usage of heaters. Like honestly. The TEG isn't that bad, just needs minor balance changes.

Alternatively, lower its overall power output

**Comment by Dallen999** [comment]
But when the SM delams it doesn't end the round.. (unless done on purpose)

**Comment by zeskorion** [comment]
Try to make this a standardized template to make it easier to port to other maps

~~may be fun to add some rare gimmick engines~~

**Comment by Kerbin-Fiber** [comment]
Tried to figure out how to standardize it, no fuckin clue.
But I had already planned to do it myself, as MetaStation is halfway done at this point. But I also have no idea how it'll work for Delta since Delta has the SM in Atmos and already has an area for a PA in Engie

**Comment by Kerbin-Fiber** [comment]
So, what I'm seeing is that a fuckton of pipes are full of nothing. null. I don't have this problem at all on my end and I have no idea why it's happening here.

**Comment by MrHorizons** [comment]
How about do what Yog does and have both the singulo AND tesla generators as well as the needed stuff for both for the PA engine setup?

**Comment by Kerbin-Fiber** [comment]
That's how I originally planned it to be but that would *almost* render cargo useless for power needs unless someone just wanted to order something for the sake of it. That's why I randomized one of the three.

**Comment by YakiAttaki** [comment]
i think maybe the singulo should have a lower chance than the tesla due to the fact that the singulo is fucking annoying for everyone and has to be constantly babysat

**Review by zeskorion — CHANGES_REQUESTED** [review]
What i'd really hope to see here is a sort of uniformity to the size of engines and the pipe layouts across maps, so as to make these engines universal. 

I think out of the normal three engines, tesla ought to be the least common, being the most destructive.  Due to the bee playerbase, these should be easy to set up on a minimum capacity. 

I'd really like to see some more esoteric engines here as well- if you do so, though, you should probably have a paper guide to engine setup spawn.

ALSO: to the real review shit. random rooms MUST be atmos sealed- your setup here is going to depressurize engineering before the room spawns in, on both maps

**Comment by Kerbin-Fiber** [comment]
Reopening because
> ALSO: to the real review shit. random rooms MUST be atmos sealed- your setup here is going to depressurize engineering before the room spawns in, on both maps
^ This is false. Atmospherics doesn't actually move until the round starts.

and this
> What i'd really hope to see here is a sort of uniformity to the size of engines and the pipe layouts across maps, so as to make these engines universal.
This is bad spaceman game and almost nothing is perfect. I'm not spending weeks to redo atmospherics on a bunch of stations for some easy work later down the road. I want my engines randomized NOW

**Comment by Kerbin-Fiber** [comment]
ah yes

**Pull request closed without merging**
