### PR TITLE
small fire rate refactor, truly automatic guns, dual wielding

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
-Guns that should be automatic are now automatic, and it is bloody fun. Sec autorifle, l6 saw, etc. burst fire to represent fire rate is no longer necessary
-Fire Rate is now a var guns have, which is measured by shots per second. Guns no longer all operate on the 2.5 shot per second mode. Some fire very fast, some do not fire fast at all
-dual wielding code fixed up slightly, and the weapon_weight var on guns has finally been used, giving guns a weight that makes sense
-applies fire rate to most guns

EDIT: i aint gonna spell out every single gun i changed fire rates on, cuz it's a fucking lot. Click the fancy "files changed" button to learn more
image

## Why It's Good For The Game
guns in this game all feel kinda samey. They're either burst fire or not, and do different damage, but all have pretty much the same fire rate, this fixes that. Automatic guns are also really satisfying when fire rate isn't fixed at 2.5 per second

also, shotguns at the moment blow anything away in a second. (quite literally- they fire 2.5 shots per second, enough to crit any unarmored person and many armored people as well). Whilst shotguns SHOULD be lethal, and i will not nerf their damage, fire rate is excessive for them (as well as in a lot of other places

## Changelog
:cl:
add: new fire rate var for guns
tweak: phases out burstfire on guns that don't specifically need it in favor of true automatic fire
tweak: universal fire rate changes
balance: buffed plasma cutter damage
balance: detective gun blowing up in your hand is now actually quite dangerous, but not lethal, and doesnt destroy the gun
balance: lowered energy cost of temp gun projectiles by 60%
balance: fixed up dual wielding, it's now mostly only useful for handguns and miner's guns
fix: dual wielding now takes both offhand and main guns into account, instead of just offhand. 
code: fire rate is now tied to gun, and not ammo casing
/:cl:

### CODE REVIEW

**Comment by Lagomorphica** [comment]
For people unwilling to read the  files changed, this is what I have surmised - 

- Energy cost of the temperature gun to fire freeze bolts has been dropped from 250 to 100 - I will calculate how many extra shots it has in a minute.
- Nanotrasen SMG has a firerate of 5 bullets per second, full auto. SABR.
- UZI shoots 4 bullets per second and is full auto.
- Tommy gun has a fire rate of 5 shots a second and is fully automatic.
- L6 Saw and Syndicate Assault Borg LMG fires 6 shots per second, full auto.
- Laser gatling gun shoots 10 shots per second, full auto.
- Break action syndicate grenade launcher has a firerate of two nades per second, discounting reload time.
- Colt 1911 I believe fires 3 shots per second, semi auto.
- All revolvers except the Detectives shoot 1.5 shots per second.
- Unmodified detective revolver is 2 shots per second.
- Modified Detective Revolver shoots 1 shot per second - slower than its syndicate variant.
- Shotguns now shoot one shot per second, disregarding pump time.
- Bulldog shotgun is fully automatic and fires two shots per second.
- Double barrel can unload its mag in a second.
- Head of Security's lasergun shoots 3 shots per second and is fully automatic.
- Hybrid turret cannon shoots 5 shots per second and is automatic.
- Pulse rifles shoot 3 shots a second and are fully automatic.
- Pulse pistols are 1.5 shots a second, semi auto.
- Temperature gun is fully automatic and can fire 4 shots per second.
- Reagent dart gun fires 1.5 syringes a second.
- Rapid syringe gun is fully automatic and can fire two per second.

Outside of fire rate changes, you are also unable to dual wield weapons with a weight class of medium - you can hold them but not fire them. Light classed weapons can be dual wielded and fired. These weapons can no longer be dual wielded:

- Energy guns.
- Shotguns.
- Mosins.
- Grenade launchers.

If I am wrong on any of these please correct me - I will update this as I find more.

**Comment by VictorVow** [comment]
Change dual-wielding to prevent doing this with bulky sized weapons and above, not normal. Normal-sized weapons like disablers and energy guns should be able to be dual-wielded.

Most of these will need testing further, but my initial thoughts are that rapid syringe gun, temp gun and uzi sound OP now.

**Comment by Lagomorphica** [comment]
Temp gun and UZI I can see, but not the rapid syringe gun. Keep in mind that it is a traitor item and that each syringe is carrying your death chem mix - its best to make say a bluespace syringe that one shot kills somebody than to just riddle them with multiple, unless you're going for a one two punch of water and potassium or something.

**Comment by VictorVow** [comment]
Rapid syringe gun is crew tech not a traitor item.

**Comment by Coolsurf6** [comment]
Spicy. Seriously this sounds fun as hell, need to try this.

**Comment by zeskorion** [comment]
> Change dual-wielding to prevent doing this with bulky sized weapons and above, not normal. Normal-sized weapons like disablers and energy guns should be able to be dual-wielded.
> 
> Most of these will need testing further, but my initial thoughts are that rapid syringe gun, temp gun and uzi sound OP now.

rapid syringe gun fire rate has actually gone down

the temp gun is nowhere near viable even with this boost
image

due to how its burst fire worked, uzi should, by all rights, have its fire rate increased by one

not compromising on the dual wielding thing

**Comment by SomeAngryMiner** [comment]
making the plasma cutter auto would help miners, and it doesnt have enough damage to count as an actual threat, something about 1-0.75 shot per second should suffice to make it better of an utility.

**Comment by nikk735** [comment]
exosuit lmg was very lame at a 3 round burst not sure if you saw that

**Comment by zeskorion** [comment]
> exosuit lmg was very lame at a 3 round burst not sure if you saw that

exosuit weapons aren't factored in here.

**Comment by zeskorion** [comment]
> making the plasma cutter auto would help miners, and it doesnt have enough damage to count as an actual threat, something about 1-0.75 shot per second should suffice to make it better of an utility.

made it auto, with a fire rate of 3, and doubled plasma cutter damage, so advanced cutters do 14 damage now

**Comment by zeskorion** [comment]
travis be drungk

**Comment by MarkSuckerberg** [comment]
I'm going to ~~steal~~ port this so hard it isn't funny

**Pull request merged**
