### PR TITLE
Gives Brigs Phys Crewmonitor

### PR DESCRIPTION
**Pull request by WigLiz**
## About The Pull Request

Makes it so Brig Phys start with a handheld crewmonitor and pinpointer.
Removes the seclinte from their gear, (it's a lot easier to get a seclite over a crewmonitor).

## Why It's Good For The Game

Ensures the Brig Phys are able to monitor the sec team's sensors/do their job without having to rush to medbay every time. 
Paramedics get crewmonitors so it only makes sense Brig Phys would too. 

First ever PR, shouldn't have any issues just a tiny change.  :)
## Changelog
:cl: WigLiz
add: Gives Brigs Phys a handheld crew monitor
/ :cl:

### CODE REVIEW

**Comment by mcmeiler** [comment]
Unsolicited opinion, but why would the brig phys need a pinpointer/monitor? They're not a paramedic, rather a doctor for security and prisoners.

**Comment by WigLiz** [comment]
> Unsolicited opinion, but why would the brig phys need a pinpointer/monitor? They're not a paramedic, rather a doctor for security and prisoners.

Brig Phys are often out of the brig saving sec officers whenever they need help. They need to be able to find the officers efficiently. Pinpointer in particularly are useful in finding sec bodies left in maintance lockers and portable monitors allow them to be able to see when vituals drop on officers can call backup to the last known location. 

They're played as a mixture between Doctor and Paramedic (latter more than the former in my expeience) and they are expected to meet both roles in the brig.

**Comment by yyzsong** [comment]
Why?
CMO doesn't get both, Paramed doesn't get both. Brig phys is probably gonna have to run to medbay anyways, and let em. Brig has sensor monitors, and I think adding monitors to the brig phys room would be a better solution.



> portable monitors allow them to be able to see when vituals drop on officers can call backup to the last known location.

NGL
warden's job

**Comment by WigLiz** [comment]
> CMO doesn't get both, Paramed doesn't get both. Brig phys is probably gonna have to run to medbay anyways, and let em. 

CMO and Paramedics are able to get both right at roundstart very easily, by the time the Brig Phys runs to medbay there isn't any pinpointers or monitors left. I can see having both items as being too much though. I would at least think having a portable monitor would be better than not having either. 

>Brig has sensor monitors

Brig Phys can't access the warden's office to check those sensors so what's the point?

>warden's job

Yeah that's a fair point. 

>I think adding monitors to the brig phys room would be a better solution.

I would agree but I still think Brig Phys should at very least have their own portable monitor. 

Overall, I can see the points being made and agree that letting them have both items is a little too much. I guess I could make another PR that just adds the monitor. I'll close this, thanks for taking the time to discuss it here though :)

**Comment by Sapfearon** [comment]
paramedic has both pinpointer and crew monitor shift start, cmo instantly vends one. Brig phys can't use monitor console, warden always too busy to use one - so right now brig phys forced to speedrun to medbay and hoping that there is still crew monitor left in vendors. Medic on other hand doesn't need monitor and has easy access to crew monitor console.
Good change.

**Comment by Archanial** [comment]
Don't think he needs either

**Comment by WigLiz** [comment]
>paramedic has both pinpointer and crew monitor shift start, cmo instantly vends one. Brig phys can't use monitor console, warden always too busy to use one - so right now brig phys forced to speedrun to medbay and hoping that there is still crew monitor left in vendors.

This is exactly the issue I'm trying to fix with this PR. If a brig phys doesn't speedrun to medbay every round to a vendor their job becomes absolutely harder. 


> Don't think he needs either

Brig Phys don't need a secilte either but they spawn with one anyways. Surely giving them a tool that would actually be useful to role would be better than something they are going to get rid of straight away for something more useful.
It would be like having a sec officer spawn without a disabler. They are necessary tools to do their job.

**Comment by Archanial** [comment]
No, the issue is that brig physician exists, when everything he does should be done in a medbay.

You are meant to heal people inside of brig not to hunt for the bodies.

**Comment by WigLiz** [comment]
> You are meant to heal people inside of bridge not to hunt for the bodies.

This confuses me, how do these bodies appear in the brig? One of the brig phys main requirements is to heal **sec officers** and prisoners. How are they expected to heal officers that are crit or dead if they don't know were they are? Are they expected to wait till someone drops a body off at the brig instead of the medbay? Why are brig phys given maints access if they're suppose to stay in the brig all the time?

The issue here is that there's no clear idea of what the Brig Phys role is. 
Brig Phys, as I see it, is someone that makes it their duty to heal prisoners and sec officers that need it ASAP. They're expected to save officers that need it and bring them to the brig for healing.

**Comment by Crossedfall** [comment]
I mirror the sentiment of others here. This doesn't feel needed. If they really want/need those items, they can always get some from medical. 🔑

**Pull request closed without merging**
