### PR TITLE
[WIP] Babylon a new map for a new beestation.

### PR DESCRIPTION
**Pull request by Moccha-Bee**
## About The Pull Request

Adds babylon a map made when bee lrp used to pass 100+ almost everyday. The map was orignally created by leader245 but discontinued after he left, decided to pick it up and finish it. Also needs alot of feedback specially for maint and the space usage.

Images of the map -> https://imgur.com/gallery/ikIY0bf

Todo list: [Babylon.xlsx](https://github.com/BeeStation/BeeStation-Hornet/files/5255245/Babylon.xlsx) [Updated]

## Why It's Good For The Game
A map to challenge the dominance of Meta and Delta.

## Changelog
:cl:
add: Added Babylon
add: Tesla/Singuloth spawner 50% for one of each to spawn each round.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
this isn't feasable with our max pop being 70.

**Comment by Moccha-Bee** [comment]
> this isn't feasable with our max pop being 70.

Well things could change for mrp who knows, and lrp might make a comeback so it would be good to finish the map in the mean time.

**Comment by ghost** [comment]
> > this isn't feasable with our max pop being 70.
> 
> Well things could change for mrp who knows, and lrp might make a comeback so it would be good to finish the map in the mean time.

mrp has a popcap of 70 because the server literally dies above that.

**Comment by Moccha-Bee** [comment]
> > > this isn't feasable with our max pop being 70.
> > 
> > 
> > Well things could change for mrp who knows, and lrp might make a comeback so it would be good to finish the map in the mean time.
> 
> mrp has a popcap of 70 because the server literally dies above that.

lrp doe...

**Comment by TeomanTheGreat** [comment]
Phil like

**Comment by yyzsong** [comment]
this map is fucking amazing, speedmerge and force it

**Comment by Moccha-Bee** [comment]
> this map is fucking amazing, speedmerge and force it

dosent have disposals doe, and no church, most spawners aren't even in...

**Comment by 4rchibald** [comment]
It actually looks nice, which you can't often say about maps. Even though it is big it seems to be quite simple to navigate.
Tiles under each tcomm section are a good idea. Personally I'm all for more realistic, crude design that wouldn't get any indication which machine is handling specific department channel but I see value in that since most players seem to be intimidated by tcomms, maybe such visual indication would encourage them a little bit more to attempt repairing channels that are down and to sabotage them in some more precise way than just smashing APC or random machines. 
Also like the fact that you're trying something new with SM but maybe limit it to 2 crystals and instead of having their loops separated make waste from 1st crystal go into 2nd crystal and then get filtered and cooled down only to return to 1st one. What you got currently is literally just 3 separate standard setups. Spicing things and making engineers fiddle a little bit more with it to make sure 1st crystal won't get too hot and heat up 2nd one would make things more interesting. 

But as it was said by others, we don't have those pop numbers any more. On Sage we'll never have them.
Also, my blood pressure literally jumped from looking at those big rooms, Every big space is a problem since we got fastmos. 

You think you could rework it? Try to keep this general layout but just make things smaller, resize rooms, remove those additional things like multiple cryos to make it more reasonable for smaller population. I think I would actually like playing on something like this

**Comment by Moccha-Bee** [comment]
> It actually looks nice, which you can't often say about maps. Even though it is big it seems to be quite simple to navigate.
> Tiles under each tcomm section are a good idea. Personally I'm all for more realistic, crude design that wouldn't get any indication which machine is handling specific department channel but I see value in that since most players seem to be intimidated by tcomms, maybe such visual indication would encourage them a little bit more to attempt repairing channels that are down and to sabotage them in some more precise way than just smashing APC or random machines.
> Also like the fact that you're trying something new with SM but maybe limit it to 2 crystals and instead of having their loops separated make waste from 1st crystal go into 2nd crystal and then get filtered and cooled down only to return to 1st one. What you got currently is literally just 3 separate standard setups. Spicing things and making engineers fiddle a little bit more with it to make sure 1st crystal won't get too hot and heat up 2nd one would make things more interesting.
> 
> But as it was said by others, we don't have those pop numbers any more. On Sage we'll never have them.
> Also, my blood pressure literally jumped from looking at those big rooms, Every big space is a problem since we got fastmos.
> 
> You think you could rework it? Try to keep this general layout but just make things smaller, resize rooms, remove those additional things like multiple cryos to make it more reasonable for smaller population. I think I would actually like playing on something like this

That's the plan, there is alot of big rooms and i fear that the map would both feel empty and unnecesseraly big at the same time.
And also each SM shard has its own loop.

**Comment by 4rchibald** [comment]
Yeah I noticed, that's why I'm recommending spicing it up a little bit by connecting them have same gas go to first chamber, then as coolant to 2nd one or something like this. Otherwise you have just 3 regular SM engines with pipes just spread out a little more than usual

**Comment by Moccha-Bee** [comment]
> Yeah I noticed, that's why I'm recommending spicing it up a little bit by connecting them have same gas go to first chamber, then as coolant to 2nd one or something like this. Otherwise you have just 3 regular SM engines with pipes just spread out a little more than usual

oh alright i misread you then. Thanks for the feedback.

**Comment by qwertyquerty** [comment]
> > > this isn't feasable with our max pop being 70.
> > 
> > 
> > Well things could change for mrp who knows, and lrp might make a comeback so it would be good to finish the map in the mean time.
> 
> mrp has a popcap of 70 because the server literally dies above that.

Nah it's just to improve quality of rp. We can run 100+ players

**Comment by qwertyquerty** [comment]
@Moccha-Bee could you add a todo list to your pr desc?

**Comment by Moccha-Bee** [comment]
> @Moccha-Bee could you add a todo list to your pr desc?

Yes

**Comment by Moccha-Bee** [comment]
> @Moccha-Bee could you add a todo list to your pr desc?

added

**Comment by Blueturbo47** [comment]
I wish pop was lower, I like new maps because it allows me to do more but with pop being high its just useless code sitting there and not doing much. Or you could lower the pop of other maps and make this the highest pop map. The map looks cool though.

**Comment by eLeCtrOssSnake** [comment]
Based ngl.

**Comment by Moccha-Bee** [comment]
Finished doing cargo, bridge is mostly done, remade the Engine area for engineering and removed all the step-x and ys for better performance.

**Comment by Blueturbo47** [comment]
Reason for closing?

**Comment by ghost** [comment]
> Reason for closing?

moccha went on a gay baby rage after being demoted from mentor for getting caught mute evading on discord.

**Comment by TotallyNotChief** [comment]
mmmmmmmmmmmmmm

**Comment by Moccha-Bee** [comment]
> > Reason for closing?
> 
> moccha went on a gay baby rage after being demoted from mentor for getting caught mute evading on discord.

Shut the fuck up retard. I atleast wasn't caught alt keying to try and kill the antag who killed me lole.
I closed my prs because git kraken shat itself and i needed to redo the branch, and seeing how i din't have much will to continue the projects i decided to close them, better then leaving them getting stale and clogging the git.

also, if anyone wants the map files dm me.

**Comment by ghost** [comment]
> > > Reason for closing?
> > 
> > 
> > moccha went on a gay baby rage after being demoted from mentor for getting caught mute evading on discord.
> 
> Shut the fuck up retard. I atleast wasn't caught alt keying to try and kill the antag who killed me lole.
> I closed my prs because git kraken shat itself and i needed to redo the branch, and seeing how i din't have much will to continue the projects i decided to close them, better then leaving them getting stale and clogging the git.
> 
> also, if anyone wants the map files dm me.

i actually wasn't caught i admitted to it in discord.

**Pull request closed without merging**
