### PR TITLE
Siege - New Gamemode

### PR DESCRIPTION
**Pull request by mudzbe**
## About The Pull Request

Siege is split into 2 phases, preparation and invasion. Preparation makes up 2/3 of the round and is essentially a normal SS13 round with crew doing their job and syndicate agents being syndicates. The number of syndicate agents are halved and they don't have an advantage with gear, including the fact they have no TC. This should organically increase RP as they will have to rely on RP and teamwork to stand a chance, taking the entire station head on isn't a good idea. RP is created by the discord between departments, every department thinks they are important, but does the station have the resources to defend all of them? Each department has their own competing interests. Further the development of the defense is complicated as you don't know who is secretly sabotaging it. This all adds to the RP as the crew and command debate the best course of action whilst external actors seek to cause confusion. New roleplay scenarios can be organically created, do you accept the prisoner who bargains for freedom in exchange for fighting against the syndicates? How can conflicting interests lead to a fractured defense and what lengths will command do to stop this, what levels of armament are safe without them falling into the wrong hands?

In the preparation phase crew are alerted that they should prepare for a syndicate invasion by performing their job, as basically all jobs revolve around combat progression there is no fundamental change. Likewise the syndicate agents perform the same fundamental job. They will have to come up with their own objectives to prepare for the invasion, with no TC and the station armed and very alert syndicates will have to work as a team to complete meaningful objectives.  They are fitted with Bloodbrother radios. Even if they decided to kill twice as many people as they would in a normal round (ignoring their capacity to do so - some people struggle to kill one person even with TC), the level of destruction in this phase would be equal to a standard round. 

The invasion phase makes up only a 1/3 of the round, whilst this period will be very destructive, on balance the gamemode should produce more RP and have less time in TDM mode than Wizard, Clock cult, Blood cult, Gangs and Revolutionaries, which are all still in the code. The negative impact of death will also be minimized as everyone has the chance to get back into the game. After (60 minutes?) the nukeop's shuttle arrives but the nuke is replaced with a spawner. Ghosts can spawn as several unique classes with the aim of destroying the station/killing the crew. The ghosts are given 3 options chosen from the class pool. After a period of time (20 minutes?), elite classes are added to the pool of selectable, there is a 15% chance of having this option. There is a 10 minute respawn cooldown (from spawn). The nukeop's shuttle has buffed turrets and the normal entrance is impassible by crew. Attackers can arm and defenders disarm the nuke without the disc, this prevents the round from dragging on and gives a central focus to both sides. This could be moved by admins, or otherwise can stay in the vault.

The syndicates have access to the normal nukie gear on the shuttle, some bombs and syndie suits. Admins can choose to move the shuttle away from the syndie base to prevent them from getting that gear. The standard classes have about 15tc worth of gear.

The classes are:
[Class Template] - Syndie uniform, space suit, antidrop implant, dusts on death, combat knife
Engineer - Shotgun, Syndi PDA which can construct a turret, quantum pads, and a dispenser which supplies ammo, 50 metal. The engineer can build a turret, teleporter and dispenser. The dispenser supplies bullets, armour and an energycore which fully recharges a energy gun but also disappears after a short period of time like a legion core.
Specialist - 12 TC uplink (Change?)
Pirate - 2 laser guns, c4, x4, pirate uniform, is a skeleton (space immune)
Grunt - .45 SMG - 4+1 mags
Zombie - Romerol zombie (doesn't dust)
Intruder - Esword, stealth implant
Brawler - Syndi hardsuit, Esword
Infiltrator - Chameleon uniform, emag, supressed stetchkin - 3+1 mags
Bomber - 2x X4, minibomb, nukie explosion implant
Medic - Medic beam gun, egun, medkit

Elite classes
Nukeop - Standard nukeop loadout - (25 TC uplink), stetchkin
Wizard - 5/10 spell points, wizard uniform, space adaptation
Abductor - Abductor armour, teleportation scroll, esword, space adaptation
?Nightmare?

Admins can change the respawn delay of the siege controller, what outfits are available for example you could add deathsquad (idk why), or remove a class. They can manually change the phase of operation, so the machine can function even outside of the siege gamemode.

 This gamemode was inspired by the Dwarfs Vs Zombies gamemode for minecraft.

## Why It's Good For The Game

A fundamental problem with SS13 is job progression revolves around combat, but combat is discouraged; you are not allowed to attack other people if you aren't an antagonist, not even other antagonists. Enormous amounts of content are locked behind these restrictions, furthermore this encourage poor behavior as players are artificially locked from performing their jobs, so they seek to break the rules. A large percentage of SS13 players can be considered disruptive in this context. This gamemode aims to solve these issues by providing structure and meaning to every job; it's not powergaming if command want's you to make weapons.

The progression of almost every class relies on combat. But whether this combat materializes is uncertain, you could say that's what the point of nukeops is, but nukeops doesn't have a large preparation stage and so is largely removed from standard gameplay. Other gamemodes like gangs, revolutions, and cults can be criticized for not following standard gameplay. Siege's preparation stage is essentially normal SS13 but without restrictions. Siege provides a motive and removes your restrictions to actually do your job as it is designed.
- Botany - deadly plants factory
- virology - literally a bio weapons lab
- robotics - literally a mecha factory
- Toxins - literally bomb making
- Xenobiology, nanites, genetics - combat buffs
- chemistry - grenades, combat drugs
- cargo - make money to buy cool stuff (only guns and armour)
- engineering - build stuff - but why? everything the station needs already exists, repair stuff (from damage caused in combat) 
- atmos - deadly gasses
- medical - heal people (from damage caused in combat)

Every department has a purpose, most will be performing their usual duties but on steroids on top of defending the station
Security - Usual duties, oversee the armament of the station
Cargo - Usual duties
Engineering - Usual duties, ensure power for the invasion and help fortify the station
Medical - Usual duties, Upgrade medical/ move it to somewhere more defendable, 
Science - Usual duties
Service - Usual duties, Floaters
Command has an enormous role, they will likely be choosing the central location that will be defended, where the nuke will be moved to, their task is to coordinate their department's resources into an effective defense. I don't imagine everywhere could be defended at once.

## Testing 
I may have had a youtube video running in the background so I didn't record sound, just use your imagination.

https://user-images.githubusercontent.com/60084963/170263201-7fced397-5e80-4398-80cb-32531a189847.mp4

https://user-images.githubusercontent.com/60084963/170263689-02032de1-6536-4607-8a40-5e9fff695c72.mp4

https://user-images.githubusercontent.com/60084963/170263130-1c698b1f-7831-4243-a09b-b50cf7517427.mp4

There may be some issues relating to the selection of roundstart antags etc, I wasn't completely able to test this cause that requires lots of people, this PR should be testmerged. The fonts on the custom UI are weird but functional. I've tried like 10 different fonts/formatting and all of them are bad. This PR is also PRed at austation since we don't have enough server pop for the mode (sad!) so it has been tested once in the server and worked fine.

## Changelog
:cl:
add: Siege gamemode
add: SyndPDA (admin/gamemode spawn) which can spawn teleporters, dispensers and turrets
add: Energycore (admin/gamemode spawn) which fully recharges energy weapons
add: 13 new outfits (admin/gamemode spawn)
/:cl:

### CODE REVIEW

**Comment by Ivniinvi** [comment]
Complete TDM and LRP mode, not a fan if it's not admin only, and even then it'll rarely be run and just be bloat.

**Comment by mudzbe** [comment]
how have you read the PR so fast its been a minute

**Comment by Ivniinvi** [comment]
> how have you read the PR so fast its been a minute

It's obvious from the first few sentences alone, and I read the whole thing hoping I'd be disproven, and I wasn't.

**Comment by mcmeiler** [comment]
No. We don't need a literal TDM gamemode. We have 3 of these already.

**Comment by mudzbe** [comment]
> It's obvious from the first few sentences alone, and I read the whole thing hoping I'd be disproven, and I wasn't.

The comment was pretty vague, how am I supposed to make a response in a minute? First off it's obviously not complete TDM, the first phase of the gamemode is essentially just normal SS13 for an hour, you perform your job, sec hunts syndies. It's not necessarily LRP either, it's just that there's more pressure to perform your job?

**Comment by Ivniinvi** [comment]
A game mode where murderboning, powergaming, and validhunting are optimal strategies sounds like a game mode that isn't great for Bee. Honestly, if there wasn't this much effort put in, I'd think this was a meme pr.

**Comment by mcmeiler** [comment]
> Put simply your potential is limited. Enormous amounts of content are locked behind this limitation. This gamemode aims to solve these issues. Further it will probably increase pop because who wouldn't want to play this amazing mode where these are not frowned upon, but optimal:
>
>- Murderbone
>- Power Game
>- Valid Hunt

This has to be a shitpost. You can't be serious with this.

**Comment by mudzbe** [comment]
> A game mode where murderboning, powergaming, and validhunting are optimal strategies sounds like a game mode that isn't great for Bee. Honestly, if there wasn't this much effort put in, I'd think this was a meme pr.

Clearly that's a joke?

**Comment by mudzbe** [comment]
You blokes... You want me to be more serious?

**Comment by RDS88-beeman** [comment]
The admins want to discourage the whole
- powergame
- validhunt
- murderbone
gameplay loop of LRP ss13.
your creating this gamemode to like. do. all those things. kind of goes against what the admins want for the server.

**Comment by mudzbe** [comment]
> The admins want to discourage the whole
> 
> * powergame
> * validhunt
> * murderbone
>   gameplay loop of LRP ss13.
>   your creating this gamemode to like. do. all those things. kind of goes against what the admins want for the server.

Copypasting comments and not actually addressing what I've actually said is counterproductive. Where did I say everyone can validhunt? The syndicates spawn at half the rate of normal traitors so if there were 6 traitors normally, then they'd have 3. Normally they enjoy a gear advantage but there is none here, which only leaves surprise. They don't have the strength to randomly kill everyone. Even if they chose to kill twice the people they would normally as traitor (some people struggle to kill a single unarmed target, with 20TC) the amount of death would be equal to a normal round. Powergaming is by definition excessive, I've stated that job progression revolves around combat so how is it powergaming if you're performing your job and with the approval of command? If you don't like how jobs work then delete them or play a different game I guess.

**Comment by zeskorion** [comment]
This gamemode isn't quite what bee needs, or any server in general needs. 

I could write a few paragraphs about why this sucks, but i wont. why should i. it wont get merged.

**Comment by mudzbe** [comment]
>This gamemode isn't quite what bee needs, or any server in general needs.
>
>I could write a few paragraphs about why this sucks, but i wont. why should i. it wont get merged.

No one has been able to give a single fact/reason to back up their opinions and it seems most people like/are interested in the PR, so you should try explaining how the majority of people are wrong. It seems like a knee jerk reaction, it didn't help the people complaining about the PR cant tell what jokes are.

> > A game mode where murderboning, powergaming, and validhunting are optimal strategies sounds like a game mode that isn't great for Bee. Honestly, if there wasn't this much effort put in, I'd think this was a meme pr.
> 
> Clearly that's a joke?

I don't understand how this response can be considered off topic and the original isn't, when he's literally quoting a joke and I'm explaining it was a joke, iirc their comment was marked off topic too before but not anymore. What is the logic behind this?

**Comment by zeskorion** [comment]
> > This gamemode isn't quite what bee needs, or any server in general needs.
> > I could write a few paragraphs about why this sucks, but i wont. why should i. it wont get merged.
> 
> No one has been able to give a single fact/reason to back up their opinions and it seems most people like/are interested in the PR, so you should try explaining how the majority of people are wrong. It seems like a knee jerk reaction, it didn't help the people complaining about the PR cant tell what jokes are.

I can't be bothered, as this gamemode will be disabled within a week or a month if it gets merged.

**Comment by ToasterBan** [comment]
there are some flaws, the sand golem+ttv strat will still work against the shuttle 

also when does the round end? either nuke going off or escape shuttle? should have some way of destroying the ship

**Comment by mudzbe** [comment]
> there are some flaws, the sand golem+ttv strat will still work against the shuttle

This is irrelevant because all classes spawn with space suits and internals equipped. They'd just have to turn on internals. The spawner is indestructible.

> also when does the round end? either nuke going off or escape shuttle? should have some way of destroying the ship

Every syndicate activates the nuke when they tap it (except roundstart syndies who are counted as crew) crew can also deactivate the nuke by tapping it.

**Comment by PowerfulBacon** [comment]
If you are going to add in major systems including new gamemodes, please fill out the testing portion of the PR body. It's up to pull request authors to locate and prevent bugs, a PR of this nature will probably get a testmerge round at best.
The only way I can see a chaos round like this being implemented would be through refactoring and improving the end of round battle royale system to be a minigame system instead, adding an entire gamemode for something that can't be run seems a bit bloaty (Especially since it comes with a subsystem too).

**Comment by mudzbe** [comment]
> ...a PR of this nature will probably get a testmerge round at best. The only way I can see a chaos round... 

If you really wanted to you could set less vague objectives for the saboteurs if you're scared of what they'll do. The crew otherwise act relatively normally in the preparation phase which is most of the round chaos round sounds a bit extreme.

> The only way I can see a chaos round like this being implemented would be through refactoring and improving the end of round battle royale system to be a minigame system instead

What do you mean?

> adding an entire gamemode for something that can't be run seems a bit bloaty (Especially since it comes with a subsystem too).

"Can't be run", do you mean wont be run? It would be nice if it didn't require a subystem for an accurate timer.

**Comment by Lambda-Epsilon** [comment]
Of all the comments here, there has been nothing brought up against the author other than "its le TDM and LRP" and vague notions of it not being merged because, reasons I suppose.

Does anyone actually have criticism for his PR? The premise is not bad, it is indeed true that most players see most satisfaction in clicking-until-horizontal. Might as well make a gamemode so RP can indeed happen and that its not considered rule-breaking behaviour.

**Comment by Lambda-Epsilon** [comment]
> I can't be bothered, as this gamemode will be disabled within a week or a month if it gets merged. 
@zeskorion 


Then don't create a comment here. If youre not going to put the minimum effort of explaining why you disagree, simply click one of the reaction buttons or never participate in this PR. It just wastes peoples' time when you do.

**Comment by zeskorion** [comment]
> > I can't be bothered, as this gamemode will be disabled within a week or a month if it gets merged.
> > @zeskorion
> 
> Then don't create a comment here. If youre not going to put the minimum effort of explaining why you disagree, simply click one of the reaction buttons or never participate in this PR. It just wastes peoples' time when you do.

i'll actually participate in criticism/arguments if maintainers support this PR. non maintainer opinions honestly don't mean all that much. they're nothing to worry about, and this PR isnt a threat

**Comment by Lambda-Epsilon** [comment]
> > > I can't be bothered, as this gamemode will be disabled within a week or a month if it gets merged.
> > > @zeskorion
> > 
> > Then don't create a comment here. If youre not going to put the minimum effort of explaining why you disagree, simply click one of the reaction buttons or never participate in this PR. It just wastes peoples' time when you do.
> 
> i'll actually participate in criticism/arguments if maintainers support this PR. non maintainer opinions honestly don't mean all that much. they're nothing to worry about, and this PR isnt a threat

What a terrible view to hold knowing that this is an open-source project of a community driven game. Everyone's point is valid even if they do not hold the permissions to merge PRs. 

You are simply wasting our time by making these comments, and derailing the potential for others to contribute to the development of the author's addition.

**Comment by mudzbe** [comment]
> i'll actually participate in criticism/arguments if maintainers support this PR. non maintainer opinions honestly don't mean all that much. they're nothing to worry about, and this PR isnt a threat

Why have I had to read 3 comments of your opinion then if you admit it's disruptive and irrelevant? Kinda arrogant and why do you have to announce this to everyone, why are you still commenting? Stop seeking attention.

**Comment by zeskorion** [comment]
> What a terrible view to hold knowing that this is an open-source project of a community driven game. Everyone's point is valid even if they do not hold the permissions to merge PRs.
> 
> You are simply wasting our time by making these comments, and derailing the potential for others to contribute to the development of the author's addition.

not everyone's point is valid. maintainers are maintainers because they are at least supposed to know a bit more than the common rabble.

players do not know squat about game design. and it shows. this perspective, where everyone's contributions and ideas are valid and deserve thought and discussion, is impractical. it is no one's job to teach players exactly how to  design stuff well, and expecting anything but a "no" on a project like this is hubris. 
If i think an idea has merit, or a person would be good at design (from my own biased opinion about how games should be designed) given the opportunity to grow, or i am bored, i'll be helpful. but i see no reason to do so now

anyways, im gonna can it for now, cuz I don't like being a holier than thou arsewipe, and discussions like this bring out the worst of that in me.

**Comment by ItsTisme** [comment]
This is cool and I appreciate the effort that you put into this. But this is a gamemode that goes quiet opposite into what bee wants to be. More RP friendly. Nukies,revs and cults are already gamemodes that are far from optimal and something we almost rather not have because it hurts RP. And this feels like an addition. It is already more or less an unspoken rule that on war ops people "can powergame" but this is not desirable and this is a gamemode that will bring more confusion. This would be fine as a one of event but I dont think this should be added in normal rotation as bee is right now.

**Comment by Rukofamicom** [comment]
Sounds like a great game mode for Austation, hope it succeeds there and everyone has fun with it. This is a terrible game mode to introduce to Beestation, a server that is facing calls to scrap Revs because of how one-dimensional and TDM it is to most players.

> Of all the comments here, there has been nothing brought up against the author other than "its le TDM and LRP"
...
Does anyone actually have criticism for his PR?

A purely TDM game mode is an **immense** detriment to add to this server, and calling it out for that *is feedback* - expecting an in-depth code review for something that is such an obvious and terrible mismatch for this server is kind of absurd if that's what you're getting at @Arbanon-Epsilon. 

If people don't like what a PR claims to be/do, they aren't going to waste their time reviewing whether the code is good.

**Comment by DerpiestBruh** [comment]
based tbh

**Comment by mudzbe** [comment]
> Sounds like a great game mode for Austation, hope it succeeds there and everyone has fun with it. This is a terrible game mode to introduce to Beestation, a server that is facing calls to scrap Revs because of how one-dimensional and TDM it is to most players.
> 
> > Of all the comments here, there has been nothing brought up against the author other than "its le TDM and LRP"
> > ...
> > Does anyone actually have criticism for his PR?
> 
> A purely TDM game mode is an **immense** detriment to add to this server, and calling it out for that _is feedback_ - expecting an in-depth code review for something that is such an obvious and terrible mismatch for this server is kind of absurd if that's what you're getting at @Arbanon-Epsilon.
> 
> If people don't like what a PR claims to be/do, they aren't going to waste their time reviewing whether the code is good.

The problem is no one criticizing the PR has explained why they don't like it beyond "it's purely TDM and LRP", which I take issue to this characterization. No one has quoted the "why is it good for the game" section (or other parts, unless you consider jokes) despite that's the only thing people are talking about. I don't understand how people keep calling it "purely TDM" and LRP when 2/3 of the round would have fundamentally similar gameplay to normal gamemodes. How could this part be considered TDM unless you consider blood brothers or incursion a TDM mode too? Especially with half the number of syndies, their victims and security should be able to handle them without the need to conscript all the crew, like a normal round. It being LRP is an assumption too, everyone assumes the crew getting gear would be LRP and TDM, because in normal rounds when this happens because the crew is bored because of these rules and break them to do their own thing. If this behavior was allowed it could be less chaotic and could be controlled. "I don't like your PR because I think it would be bad" isn't feedback, feedback is "used as a basis for improvement." no one was asking for an "in depth code review".

**Comment by Rukofamicom** [comment]
Alright then, let me take a crack at it:

> A fundamental problem with SS13 is job progression revolves around combat, but combat is discouraged;

I fundamentally disagree with this, and anywhere this is actually potentially true should be changed, not embraced. Every department has some combat available to it for antagonists to take advantage of, or players needing to defend themselves but the gameplay does not revolve around combat unless that's the only thing you are seeking or care about. 

Players that are only seeking or care about combat while ignoring the rest of the game here are problems on this server. This game mode attracts *more* of those people we want to be rid of. Security is the only department that fundamentally revolves around combat and is supposed to revolve around it. Even antagonists have so much more available to them than *just* combat.

**Comment by Rukofamicom** [comment]
In fact, let me go one step further and read this server's goal and some of its rules for you, all taken [from here](https://wiki.beestation13.com/view/Rules)

> The goal of our server is to immerse players in a fictional universe, enabling them to roleplay with each other. Your character is a grown adult working on a research station for a major company. You are a professional; act like it. Have a sensible name, construct a character for yourself and behave as the character would, and avoid breaking the immersion.

> Good roleplaying means that you have to embrace the possibility of "losing" for the sake of roleplay and/or preserving immersion. You should not be seeking gear you have no roleplay justification for having, nor should you ever generally be rushing into danger unless it is part of your job.

> You should generally attempt to flee from combat or dangerous situations.

Players that strongly disagree with these notions and think this makes for boring gameplay are playing on the wrong server. Making changes that cater to these players *is backwards progression of our codebase relative to where it is supposed to be heading towards*. Again, there is already some pretty strong pushback against Revolution still being part of our regular rotation because it doesn't really meld well with the above.

**Comment by mudzbe** [comment]
> Alright then, let me take a crack at it:
> 
> > A fundamental problem with SS13 is job progression revolves around combat, but combat is discouraged;
> 
> I fundamentally disagree with this, and anywhere this is actually potentially true should be changed, not embraced. Every department has some combat available to it for antagonists to take advantage of, or players needing to defend themselves but the gameplay does not revolve around combat unless that's the only thing you are seeking or care about.

How can you disagree with the list I gave which revolve around combat which included basically every job except service? Basically every job makes stuff that only has combat value, no value is otherwise added to the station.

> Players that are only seeking or care about combat while ignoring the rest of the game here are problems on this server. This game mode attracts _more_ of those people we want to be rid of. 

There's a reason why there's so many people who break the rules on SS13, it's because the game incentivizes them to but the servers don't. 

>Good roleplaying means that you have to embrace the possibility of "losing" for the sake of roleplay and/or preserving immersion. You should not be seeking gear you have no roleplay justification for having...

Your quoting of the server's goal doesn't go against this PR. There is a RP justification. 

RP is about the interaction between players and this PR would add much more cases where players will have to interact to be successful. Further the PR incentivizes it I edited the about section with this: RP is created by the discord between departments, every department thinks they are important, but does the station have the resources to defend all of them? Each department has their own competing interests. Further the development of the defense is complicated as you don't know who is secretly sabotaging it. This all adds to the RP as the crew and command debate the best course of action whilst external actors seek to cause confusion. New roleplay scenarios can be organically created, do you accept the prisoner who bargains for freedom in exchange for fighting against the syndicates? How can conflicting interests lead to a fractured defense and what lengths will command do to stop this, what levels of armament are safe without them falling into the wrong hands?

**Comment by Rukofamicom** [comment]
> Basically every job makes stuff that only has combat value, no value is otherwise added to the station.

I addressed this and you more or less ignored my points to repeat yourself. Yes every job including service gets **access** to some stuff that has a purpose in combat; having options to be able to defend yourself later doesn't equate to that being the purpose of the job like you're trying to claim it does.

> There's a reason why there's so many people who break the rules on SS13, it's because the game incentivizes them to but the servers don't.

The solution to the problem of our game code encouraging undesirable behavior is to fix the code so that it doesn't, not add a game mode that incentivizes *more* bloodthirsty valid-happy players to start playing here in the hopes of taking part in it. You're either a troll or daft if you think that's the way to solve the problem. 

The puzzle to solve here is that antagonists need varied options available regardless of their assigned job in order to not be bland, and regular players need options to defend themselves available in cases where shit absolutely hits the fan... but those same regular players need to be disincentivized or unable to engage in these mechanics when it's not appropriate to do so at a code level.

The game mode sounds like a ton of fun for a server that actually wants to be combat oriented, but that isn't what Bee is or strives to be regardless of what hasn't yet been adjusted to be in line with the puzzle I mentioned above. There's not really anything else I can say. If you still believe my thinking is flawed we aren't going to get anywhere productive with this.

**Comment by ghost** [comment]
The community seems to be pretty split. well the coders part anyways. Why don't you guys just test-merge it? If the playerbase responds well it might merit something. if it doesn't? just throw it in the trash.

A proper one too. with announcement, gamemode explanation and handpicked players for the antags. not just a botched one during lowpop with no one knowing what the gamemode means

**Comment by Rukofamicom** [comment]
> The community seems to be pretty split. well the coders part anyways. Why don't you guys just test-merge it? If the playerbase responds well it might merit something. if it doesn't? just throw it in the trash.

It was already tested on Austation, an LRP server, where it met pretty negative criticism which was completely blown off by the person making the PR. 

image

This is why I have a hard time believing this isn't just a troll to have ported it to us after the negative response there. 
"The crew isn't supposed to win and it was only unfair because they didn't powergame anywhere near as hard as they should have"

**Comment by ghost** [comment]
> > The community seems to be pretty split. well the coders part anyways. Why don't you guys just test-merge it? If the playerbase responds well it might merit something. if it doesn't? just throw it in the trash.
> 
> It was already tested on Austation, an LRP server, where it met pretty negative criticism which was completely blown off by the person making the PR.
> 
> image
> 
> This is why I have a hard time believing this isn't just a troll to have ported it to us after the negative response there. "The crew isn't supposed to win and it was only unfair because they didn't powergame anywhere near as hard as they should have"

Why didn't you quote my whole text? I said a proper one. I played the test round back in austation. The round situation wasnt ideal. 10 pop (Recomended pop is 25+ btw), no one knew how to play and the antags were newbies it was more of testing the code works fine. A proper testmerge what I meant was with bee playerbase mentality in highpop with everybody clued up on what to do

Not sure what you mean by received poorly. The round was bad and there was too much syndies since ya know. 10 people or so tested it when there's supposed to be 30 or so. Also don't called Mudzbe a troll. He's actually serious about this PR and calling him a troll without anything of substance to add is frankly a horrible thing to do

**Comment by mudzbe** [comment]
> > The community seems to be pretty split. well the coders part anyways. Why don't you guys just test-merge it? If the playerbase responds well it might merit something. if it doesn't? just throw it in the trash.
> 
> It was already tested on Austation, an LRP server, where it met pretty negative criticism which was completely blown off by the person making the PR.

Completely blown off would be not responding to it? That was light criticism for Australian standards - not one swear in sight. It’s constructive criticism.

> image
> 
> This is why I have a hard time believing this isn't just a troll to have ported it to us after the negative response there. 

Its still test merged and no one’s said anything about closing/untestmerging stop talking smack.

>"The crew isn't supposed to win and it was only unfair because they didn't powergame anywhere near as hard as they should have"

The crew isn’t supposed to win, it’s to see how long they can last. Kindly ignore the part where I said it was the first time it was tested, people were unfamiliar with the gamemode and that there was half of the *minimum* pop *required* for the gamemode to even start. Ruko quite frankly you have no idea what you’re talking about and this whole thing seems disingenuous.

**Comment by Rukofamicom** [comment]
> this whole thing seems disingenuous.

That's how this entire PR felt to me from the start - your twisted logic for justifying it as good for the game is completely absurd. As someone else said above, the only reason I can't convince myself to write this off as an elaborate troll is the sheer amount of wasted effort you're pouring into something that has pretty much no chance in hell of being merged here.

My best guess is that you do recognize the issues and you just want to utilize Bee's population to test your code.

**Comment by Crossedfall** [comment]
Several people already went into detail why this is a bad fit for Bee, so I wont spend much time elaborating on that front.

You pointed out some of the present flaws in progression in your PR description; but, rather than seeking to address them, it seems like this PR aims to give them an excuse to persist. I can't speak to the quality of the code as I only did a cursory glance, nor can I speak to how the mode itself actually plays out. I can, however, say that what has been demonstrated simply doesn't align with our goals as a project.

I appreciate the effort put into designing the game mode, but I'm going to have to slap down my 🔑 on this one.

**Comment by mudzbe** [comment]
@Crossedfall 
> You pointed out some of the present flaws in progression in your PR description; but, rather than seeking to address them, it seems like this PR aims to give them an excuse to persist.

I believe these flaws are so inherent that to address them would require a complete redesign of the jobs system. The job closest you could say that functionally benefits the station in a non combat way would be science upgrading parts, chefs, engineering and miners providing the bare minimum effort for power and mats but these are small jobs. The only utility most jobs provide are for combat which I’ve said creates issues with motivation and administration. I don’t think you can name a game that has bigger issues with this than SS13, not even GMOD dark rp which is renowned for it aha. So that’s why I chose to work with the system rather than fix it, it’s not an excuse, it’s the way the game’s designed intentional or not. It will persist to be a problem and I don’t think it’ll ever be fixed since the task is massive, certainly not by one person in one PR.

> I appreciate the effort put into designing the game mode, but I'm going to have to slap down my 🔑 on this one.

Oh well I didn’t code it for bee. I spent several more times effort talking here.

**Comment by Howluinb** [comment]
Honestly, I feel it's worth at least test merging it/trying it out before throwing it in the trash, since it's already pretty fully completed. It's not like this is a draft.

**Comment by ItsTisme** [comment]
Reading some of the comments and aswel as the original PR description. You see an issue that jobs "only provide benefits for combat"(for some jobs you can make this argument but engineering?) and instead of solving this issue directly you bassicly reinforce them by designing a gamemode around only combat and abusing jobs for combat potential.

Yes some jobs have some stupid things that are too useful for murder but justifying them is really not the answer to fix the issue. As many including myself have pointed out. The fact we dont even really like revs, nukies, etc in rotation should hint that adding a new even more combatative gamemode just simply does not work.

"So that’s why I chose to work with the system rather than fix it, it’s not an excuse"

This really does fly in the face of everything everyone has been working on for the last several years on both development and adminstrative staff. Have your fun with this on a server thats combat heavy but that server is not bee.

**Comment by mudzbe** [comment]
I tell ya what you merge this PR and I will port my PR that overhauls the surrender emote so it's not trash and now functional (do people even know the emote exists?)

**Comment by athena413** [comment]
> I tell ya what you merge this PR and I will port my PR that overhauls the surrender emote so it's not trash and now functional (do people even know the emote exists?)

if this pr doesnt get merged i'll port it

**Comment by PowerfulBacon** [comment]
I think I'm going to have to side with crossed here and close this PR.
While some fun event gamemodes may be accepted to be testmerged for a single round for fun, some of the design decisions seem questionable (Romerol zombies in the classes, having a new subsystem that will never be used) and it seems like it would be better suited as a post-game event like battle royale rather than an entire gamemode. Gamemodes added specifically for some event round to be one once should be unique and probably should get approved to not waste the effort coding it.
Additionally, since this wasn't designed for bee specifically and has already been played on other servers, I think it's best if it remains as a gamemode for that server.

**Comment by mudzbe** [comment]
Exadv1 said true SS13 wouldn't be realized within our lifetimes. The people's PR will live on.

**Pull request closed without merging**
