### PR TITLE
Makes a new CTF map

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request

I know what you think when you play SS13. "Man, I wish I could play ctf_turbine right now". I got you. This PR replaces the old and overplayed CTF with a brand new one, more compacted and hopefully it will make you feel like you are at home. Also ports containers from https://github.com/tgstation/tgstation/pull/68235 and https://github.com/tgstation/tgstation/pull/78444

## Why It's Good For The Game

It's an update to an overplayed map that's also a reference to a beloved game from the community.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

imagen

imagen

imagen

</details>

## Changelog
:cl: ClownMoff, EOBGames,CoiledLamb
add: Adds a new CTF map! 
add: Ports containers from /TG/
imageadd: Adds a custom sprite for red/team spawn icons
/:cl:

### CODE REVIEW

**Comment by ClownMoff** [comment]
374693813-0d1a79e0-453d-47db-8f5b-243d900bcbf1

**Comment by Tsar-Salat** [comment]
FYI TG has a maploader that lets you pick the map

- https://github.com/tgstation/tgstation/pull/57230

May or may not be relevant to you, but something to keep in mind.



> "Man, I wish I could play ctf_turbine right now"

Funny you say that...

- https://github.com/tgstation/tgstation/pull/73824

**Comment by ClownMoff** [comment]
Hmmm I could take a looksie, thanks!

**Comment by ClownMoff** [comment]
We played a couple test rounds! The map seems to be nice for playing. Maybe a little cramped, but it's definitely fun.

**Review by Rukofamicom — APPROVED** [review]

**Comment by Rukofamicom** [comment]
Only one small complaint - why are we porting all the containers but only using two of them?

**Comment by ClownMoff** [comment]
Because it's red vs blue and they don't have much use on their own, our stations aren't build around these huge containers. NovemberStation will feature them scattered around the snow

**Pull request merged**
