### PR TITLE
[port] you now always face the direction you're crawling

### PR DESCRIPTION
**Pull request by VictorVow**
https://github.com/tgstation/tgstation/pull/47141

## About The Pull Request

When crawling your head will always face the direction you're crawling in
## Why It's Good For The Game
 
More immersive, less people crawling with their legs first
ezgif com-video-to-gif
## Changelog

:cl: 81Denton 
tweak: people now crawl in the direction their heads are facing
/:cl:

### CODE REVIEW

**Review by ike709 — APPROVED** [review]

**Review by MarkSuckerberg — APPROVED** [review]

**Comment by Cenrus** [comment]
https://github.com/tgstation/tgstation/pull/47494

get this one too

**Comment by Crossedfall** [comment]
Test merged onto Golden

**Comment by ike709** [comment]
This doesn't actually seem to work, judging by the testmerge.

**Comment by Crossedfall** [comment]
Didn't work in the test merge 
GIF

**Comment by VictorVow** [comment]
Added the commit Cenrus mentioned, from the video it looks like it fixes the non-working direction.

**Comment by ike709** [comment]
Video clearly shows that north/south don't work either.

**Comment by VictorVow** [comment]
Intended behaviour, see the first GIF. You roll onto your back when going south, rolling onto your belly for north. Your head still remains left/right.

**Comment by ike709** [comment]
Fair enough. 

Time for another go @Crossedfall

**Review by Crossedfall — APPROVED** [review]
Confirmed working within the test merge

**Pull request merged**
