### PR TITLE
Revert "Makes a fake all-access card dispenser (#7393)"

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

This reverts commit 5a2e97478d36b3a6b6eb3bf6cc3d5304b8acb9b9 of PR #7393

## Why It's Good For The Game

People spam the shit out of it, it's super annoying and I don't feel like trying to fix it with a cooldown or something, the original creator is repobanned.

image

## Testing Photographs and Procedure

It no longer exists

## Changelog
:cl:
del: Removed fake AA dispenser machine.
/:cl:

### CODE REVIEW

**Comment by mystery3525** [comment]
>it's super annoying and I don't feel like trying to fix it with a cooldown or something

"Remove don't improve"

**Comment by itsmeow** [comment]
It's a useless feature. Why would I bother improving it when I do not care about it and nor does anyone else.

**Comment by mystery3525** [comment]
image

**Comment by bluezorua** [comment]
there is such thing as featurebloat

**Comment by itsmeow** [comment]
> image
> 

We are allowed to change our minds

**Comment by Tyranicranger4** [comment]
> "Remove don't improve"

Removing something can be an improvement at times.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
