### PR TITLE
R-Wall Purge - MetaStation

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
Removes a majority of reinforced walls from MetaStation. Surviving r-walls are in yellow in this image:
image

## Why It's Good For The Game
Reinforced walls have no consistency in their placement, which is often not commensurate with the difficulty involved in destroying or bypassing them. In combination with the changes to airlock hacking, the level of difficulty involved in breaching an area was made much more difficult than it should be.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image

</details>

## Changelog
:cl:
del: Due to budget cuts, Nanotrasen has removed a majority of the Reinforced Walls from Metastation
/:cl:

### CODE REVIEW

**Comment by Ivniinvi** [comment]
If this PR is merged I'll do the same with the other maps in rotation.

**Comment by itsmeow** [comment]
Toxins storage needs rwalls

**Comment by Tsar-Salat** [comment]
SM Chamber, cap office, and AI upload needs rwalls.

Give AI upload at least 1 layer of rwalls. Otherwise its trivial.

Everything else I agree with.

**Comment by Ivniinvi** [comment]
> SM Chamber, cap office, and AI upload needs rwalls.
> 
> Give AI upload at least 1 layer of rwalls. Otherwise its trivial.
> 
> Everything else I agree with.

All of those do have RWalls

**Comment by Tsar-Salat** [comment]
> > SM Chamber, cap office, and AI upload needs rwalls.
> > Give AI upload at least 1 layer of rwalls. Otherwise its trivial.
> > Everything else I agree with.
> 
> All of those do have RWalls

miseread, you said yellow was remaining. My bad

**Comment by Ivniinvi** [comment]
Re-added rwalls to tox storage

**Comment by Tsar-Salat** [comment]
If you are going for consistency, can you also remove the rewalls from turbine?

Both Pubby and Kilo have metal walls instead of reinforced, and its so much less CBT to not have to knockdown 10 walls to do basic burnchambers

**Comment by Ivniinvi** [comment]
> If you are going for consistency, can you also remove the rewalls from turbine?
> 
> Both Pubby and Kilo have metal walls instead of reinforced, and its so much less CBT to not have to knockdown 10 walls to do basic burnchambers

R-walls are there because the chambers are often filled with crazy burns, I don't want someone to do a regular turbine startup then have a small meteor or other accident flood adjacent areas with plasma fires. For consistency I'll be making those walls on all stations reinforced.

**Comment by Fronsis** [comment]
> > If you are going for consistency, can you also remove the rewalls from turbine?
> > Both Pubby and Kilo have metal walls instead of reinforced, and its so much less CBT to not have to knockdown 10 walls to do basic burnchambers
> 
> R-walls are there because the chambers are often filled with crazy burns, I don't want someone to do a regular turbine startup then have a small meteor or other accident flood adjacent areas with plasma fires. For consistency I'll be making those walls on all stations reinforced.

I do remember an atmosian having to turn down like four walls just so they could reach something related to turbine (which i think it's near gulag ship of sec?) and they complained about the amount of walls and reinforced, so i think there might be a little annoying placement but of course i understand that there needs to be a protection against funny meteors and such

**Comment by Tsar-Salat** [comment]
> For consistency I'll be making those walls on all stations reinforced.

Wow.

I really shouldn't have mentioned it if you were going to do an eff you here.

**Comment by Ivniinvi** [comment]
> > For consistency I'll be making those walls on all stations reinforced.
> 
> Wow.
> 
> I really shouldn't have mentioned it if you were going to do an eff you here.

They should be reinforced anyway, per the reasons mentioned above.

**Comment by Tsar-Salat** [comment]
> > > For consistency I'll be making those walls on all stations reinforced.
> > 
> > 
> > Wow.
> > I really shouldn't have mentioned it if you were going to do an eff you here.
> 
> They should be reinforced anyway, per the reasons mentioned above.

The reason being what? A meteor? Thats what a meteor is supposed to do. If we are trying to prevent burn leaks or do engineering's job in map design, it severly compromises the job's whole point. 

Making the turbine all rwalls is just fucking over atmosians. 

I don't really understand why you are trying to make this more hugbox. But if you want a way to do so and **not** fuck over atmosians, simply add a rwall shield on the outside, like what protects the gas chambers.

image

**Comment by Ivniinvi** [comment]
If a single r_wall is screwing over your job and turning the station into a hugbox, it may be time to reevaluate your priorities in map design.

**Comment by PestoVerde322** [comment]
Why it skips MDbots?

Also some removals within science may cause either artifact shittery or mobs shittery.

As for the whole turbine debacle, https://github.com/BeeStation/BeeStation-Hornet/pull/8296

**Comment by zeskorion** [comment]
should viro really be losing rwalls? the testing area at least should have them

**Comment by Ivniinvi** [comment]
> should viro really be losing rwalls? the testing area at least should have them

the testing area is for monkeys, not hulks.

**Comment by mystery3525** [comment]
> the testing area is for monkeys, not hulks.

The Xenomorph queen acid spit:

**Comment by Ivniinvi** [comment]
> > the testing area is for monkeys, not hulks.
> 
> The Xenomorph queen acid spit:

the testing area is for monkeys, not xenomorph queens.

**Comment by Isy232** [comment]
Xenomorph testing can be done in xenobiology, which according to the yellow is not loosing its R-walls

**Comment by zeskorion** [comment]
> > should viro really be losing rwalls? the testing area at least should have them
> 
> the testing area is for monkeys, not hulks.

rwalls are to keep dumb crew from welding in and getting infected. 



> > > the testing area is for monkeys, not hulks.
> > 
> > 
> > The Xenomorph queen acid spit:
> 
> the testing area is for monkeys, not xenomorph queens.

xenomorph queens can spawn there, so it must be ready for them. you're being a bit overzealous in the more high security research areas

**Comment by mystery3525** [comment]
> > > the testing area is for monkeys, not hulks.
> > 
> > 
> > The Xenomorph queen acid spit:
> 
> the testing area is for monkeys, not xenomorph queens.

> rwalls are to keep dumb crew from welding in and getting infected.

And as a possible balance against an alien queen just, acid spitting the wall and letting the monkeys walk to the facehuggers

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Heads of staff's offices should be reinforced from outside the department, but not from the inside (CE's office should be reinforced from wall that touches the main hallway)

**Pull request closed without merging**
