### PR TITLE
Repipes metastation's distro and scrubber network to use layers 1 and 3

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Title. This PR also converts all the airlocks to space to use the dual-port vent system.

Old piping seems to have been done by a true intellectual, so I couldn't resist showing just how smart it was:

image

image

image

These are all fixed now and I've cleaned up all the stupid decisions made. 

## Why It's Good For The Game

Brings Meta's piping up to date.

I suggest a test merge before a proper merge since there are likely mistakes.

## Changelog
:cl:
tweak: Metastation's pipes now use layers 1 and 3 instead of all the pipes being on a single layer.
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
Those are some cursed images.

**Comment by ivanmixo** [comment]
Pain.

**Comment by MCterra10** [comment]
Look at what they need to mimic just a fraction of austation's power....
https://github.com/austation/austation/pull/1968

**Comment by ivanmixo** [comment]
haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by SergeiKoralev** [comment]
1: is this still alive
2: are you currently working on any other station's pipe nets?

**Comment by PowerfulBacon** [comment]
image

**Comment by PowerfulBacon** [comment]
image

**Comment by PowerfulBacon** [comment]
image

**Comment by PowerfulBacon** [comment]
image

**Comment by PowerfulBacon** [comment]
Why was this piping moved to go over space?
image

**Comment by PowerfulBacon** [comment]
<s>Put lattices under these </s>
image


Wait why is xenobiology being connected to the main air supply? It has its own air supply so experiments can't escape.

**Comment by PowerfulBacon** [comment]
Viro has its own air supply system to prevent viruses getting into the air. (yes, I know thats not a thing)
image

**Comment by ivanmixo** [comment]
image

Ain't like this on local. 🤔 

image

What's wrong here?



> Why was this piping moved to go over space?
> image

It's better than wallpiping or spaghetti thru atmos. Also these pipes were already in space. I just connected the sci dock to them so it's neater.

Both viro and xenobio have their own air supplies

image

image

**Comment by ivanmixo** [comment]
Tell me when there's actual interest in merging this so I can fix the conflict.

**Comment by ike709** [comment]
There is no interest.

**Pull request closed without merging**
