### PR TITLE
Removes all pixel_x/y = 0 vars

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Why it added newlines after some of the deleted vars, I don't know, if it's bad, so be it, I'll try to fix it again. Anyways, this solves a lot of the problems that travis throws over "dirty" pixel_x/y vars. Just want to point out, most of the vars were from Kilostation.

## Why It's Good For The Game
More for coder/mapper QoL than actual gameplay as far as I know

## Changelog
:cl:
code: removed a lot of dirty vars from maps(mostly kilostation)
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
The mad man did it.

Was this done with strongdmm or manually?

**Comment by MarkSuckerberg** [comment]
Find and replace, tried it three different ways and it finally worked. Thank god it's over (hopefully)

**Comment by qwertyquerty** [comment]
Some things aren't by default at 0,0 and people may have purposefully placed them there. Please use the strongdmm method.

**Comment by MarkSuckerberg** [comment]
Still can't open Kilostation with strongDMM

**Comment by MarkSuckerberg** [comment]
Anyways, going to bed. I double checked the mapdiffbot and it seems that there aren't any changes, but I could (and I'm probably am) wrong. Do what you will with the PR, but I can't do anything at the moment

**Pull request merged**
