### PR TITLE
Bluespace emag avaible in traitor uplink

### PR DESCRIPTION
**Pull request by Moccha-Bee**
## About The Pull Request
Adds the bluespace emag to the traitor uplink with a cost increase of 2TC.

## Why It's Good For The Game
For a higher price traitors can get a emag that can emag machines and things remotly.

## Changelog
:cl:
add: Added Blue Space Emags to traitor uplinks.
/:cl:

### CODE REVIEW

**Comment by Kerbin-Fiber** [comment]
Needs a higher tc count

**Comment by Moccha-Bee** [comment]
> Needs a higher tc count

Maybe i think that maybe 9TC would be better considering how its just an emag with a added feature.

**Comment by SomeAngryMiner** [comment]
I like the idea of an advanced emag, but is making it only *2tc* more is really good? you can still buy most equipment you want such as eswords, ebows, epens and such with this, so i would suggest either locking it behind a gate (research, role restrictions, exploration?) for it.

**Comment by SomeAngryMiner** [comment]
how much is the range of the bluespace emag, anyways?
Besides, yeah, bluespace goes all together, not blue space.

**Comment by Kerbin-Fiber** [comment]
Bluespace emags can be used from any distance

**Comment by Kerbin-Fiber** [comment]
Including increased range from binocs or camera consoles

**Comment by SomeAngryMiner** [comment]
definitively a higher cost then, since you can do things as "EMAG BORGS FROM BOX LIBRARY DURING A BATTERY CHANGE" possibly.

**Comment by Kerbin-Fiber** [comment]
This wasn’t put in the uplink because traitors can buy a camera bug along with it and do just that

Edit: camera bugs cost 1 TC

**Comment by Moccha-Bee** [comment]
Well its now 11TC

**Comment by ike709** [comment]
Emag is too universal and overpowered as it is.

**Comment by Moccha-Bee** [comment]
Considering how broken i learned this is i will close this pr.

**Comment by zeskorion** [comment]
> This wasn’t put in the uplink because traitors can buy a camera bug along with it and do just that
> 
> Edit: camera bugs cost 1 TC

camera bugs dont even work

**Comment by Arrfur** [comment]
They're called BUGS for a reason smh my head

**Comment by Moccha-Bee** [comment]
smh.

**Comment by despong** [comment]
just make it cost an unreasonably high amount of tc just to mock traitors

**Pull request closed without merging**
