### PR TITLE
Lavaland Ghost Spawners are More Heavily Weighted

### PR DESCRIPTION
**Pull request by Programs-The-Station**
## About The Pull Request

Round after round, the only ghost spawners that are available on Lavaland are the Beach Bums, Lavaland Veternarians and Hermit roles. These roles are very rarely selected by ghosts and are more heavily RP focused. With small mining teams, there is not a lot of people down on Lavaland to interact with, so these roles are very limited.

I have simply increased the cost of the Hermit, Biodome and Vet spawns to 15, above the weight of Lifebringers, but below Ashwalkers and Free Golems. This should at least decrease the rate of spawn, allowing for ghost roles which can actually enhance Lavaland or act as better areas to mess around in without impacting the station. This weight still allows them to spawn at a decent rate.

I selected a weight which I think would be an okay compromise, but I could see adjusting it more.

## Why It's Good For The Game

These three ghost spawners are rarely used, and do not have much potential due to their limited gear and reason to stick to Lavaland (plus fairly unclear rules in the Wiki).  Golems, Ashwalkers, Syndicate base, and Lifebringers infrequently spawn due to their cost, and these are the roles which are the most replayable and useful if you want to mess around with other things without impacting the round.

## Testing Photographs and Procedure

It builds... not sure what other testing you would like to see on a 3 character change.

## Changelog
:cl:
balance: CC has dispatched "Recruitment Patrols" to Lavaland to recruit more Beach Bums, Vets and Hermits. There should be fewer of them near where you are mining.
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
~~Doesnt higher cost decrease the weight? Or at the very least cost and weight are 2 completely different things.~~
Nevermind, the issue with this is that there aren't only ghost role spawns. You are increasing the weight of these ghost roles but that doesnt make the other ones that much more likely to spawn, it makes just those ghost roles less likely to spawn. Keep in mind that this is seeded with all ruin maps, and not just maps that spawn ghost roles. ALl this PR will do is decrease the chance of there being any ghost roles at all

**Comment by Programs-The-Station** [comment]
> ~Doesnt higher cost decrease the weight? Or at the very least cost and weight are 2 completely different things.~ Nevermind, the issue with this is that there aren't only ghost role spawns. You are increasing the weight of these ghost roles but that doesnt make the other ones that much more likely to spawn, it makes just those ghost roles less likely to spawn. Keep in mind that this is seeded with all ruin maps, and not just maps that spawn ghost roles. ALl this PR will do is decrease the chance of there being any ghost roles at all

Yep, I went back and forth between reducing the weight of the higher weight spawns, or increasing the weight of the lower tier ones.  I figured that making ghost spawns less accessible in general would be more likely to be accepted than decreasing the weight of the higher impact spawns. It would at least be a step in the right direction. 

Plus, usually the combo I see is Beach Bums + Lavaland Vet + Hermit, all in one round, which means there was at least 15 weight to throw around.

If acceptable, I would be more than willing to drop the weights of Ashwalkers / Golems / etc to make them spawn more often, I won't complain about that. Do you want me to lower them instead of raising them?

**Comment by PowerfulBacon** [comment]
There are ruins with no ghost role spawners which will still take up most of the cost, which will not make the other lavaland spawners more heavily weighted.
This PR does not make any ghost spawners more heavily weighted except by an extremely minor amount (Take into account all the lavaland ruins that don't have ghost spawners.)
This PR simply increases the cost of some common lavaland ghost spawners, which overall will decrease the amount of ghost roles that can spawn

**Comment by Programs-The-Station** [comment]
> There are ruins with no ghost role spawners which will still take up most of the cost, which will not make the other lavaland spawners more heavily weighted. This PR does not make any ghost spawners more heavily weighted except by an extremely minor amount (Take into account all the lavaland ruins that don't have ghost spawners.) This PR simply increases the cost of some common lavaland ghost spawners, which overall will decrease the amount of ghost roles that can spawn

Yes, I am aware of that and understand that logic I explained my reasoning, so I just wanted to make sure that it was acceptable to lower the higher impact weights. I'll do that probably on Sunday. Gonna close this for an unrelated reason temporarily.

**Pull request closed without merging**
