### PR TITLE
Updates spaceman DMM to 1.1

### PR DESCRIPTION
**Pull request by Crossedfall**
## About The Pull Request
Bug fixes and such for the parser. Also enables the `-e` flag for defining different dme files during travis checks.

## Why It's Good For The ~~Game~~ Codebase

Might help find new errors, but really this is for downstreams that need the `-e` flag..

### CODE REVIEW

**Review by eLeCtrOssSnake — COMMENTED** [review]
Well, that's insane work. I thought there were more changes than a version change.

**Comment by eLeCtrOssSnake** [comment]
How it works btw?

**Comment by Crossedfall** [comment]
> 
> 
> How it works btw?

If you have a downstream that uses its own dedicated `.dme` file, you either need to ensure that it alphabetically comes before ours (`beestation.dme`) or you can use the new `-e` flag to force your DME file during the linting (first) test in Travis. You can add that flag within the below script. Changing `~/dreamchecker` to `~/dreamchecker -e your-dme-file.dme`

https://github.com/BeeStation/BeeStation-Hornet/blob/e93abf58cad3f9862618f26f173bdb16bbbb57a9/.travis.yml#L21-L28

**Comment by eLeCtrOssSnake** [comment]
Oh yeah, I referenced this thing in other PR.

**Pull request merged**
