### PR TITLE
You can no longer bypass the paraplegic or light drinker quirks

### PR DESCRIPTION
**Pull request by ike709**
The point of the quirk is that it can't be fixed.

## Changelog
:cl:
code: The point of negative quirks is that you shouldn't be able to bypass them. You're taking a permanent handicap in exchange for other perks. Multiple fixes have been made to reflect this.
fix: You can no longer augment a paralyzed limb. No more bypassing being paraplegic.
fix: Light drinkers will treat alcohols with negative booze power as positive booze power.
balance: Motorized wheelchair now uses 1/4th of its previous power usage.
balance: Brain Tumor quirk now starts with mannitol.
/:cl:

### CODE REVIEW

**Comment by katebishop49** [comment]
"yea we could fix paraliced limbs 100 years ago but we cannot now sadly"
coders mad x30

**Comment by Effemu** [comment]
> "yea we could fix paraliced limbs 100 years ago but we cannot now sadly"

**Comment by eeSPee** [comment]
> fix: You can no longer augment a paralyzed limb. No more bypassing being paraplegic.

This should come with a buff to automated wheelchairs.

I was thinking to buff them because they're so costy. They consume 10x more than a cyborg that is actively using their tools.

> fix: Light drinkers will treat alcohols with negative booze power as positive booze power.

This will be a unnoted change that could end up killing people, and nobody would know why they die.

Reduce their efficiency instead.

**Comment by ike709** [comment]
@eeSPee It's noted in the descriptions of everything relevant. Antihol will still purge ethanol, it just doesn't remove the effects like dizziness.

**Comment by eeSPee** [comment]
Ah ok.

Edit: You should probably atomize Brain Tumor starts with mannitol

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
