### PR TITLE
Revert "Increases Projectile Speed"

### PR DESCRIPTION
**Pull request by ghost**
This is no longer needed due to #3524

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I mean we've had it on Sage for ages and nobody has complained about projectiles being too fast

**Comment by Cenrus** [comment]
I think projectiles are a bit too fast right now, I support this revert

**Comment by OceanFish1** [comment]
> I mean we've had it on Sage for ages and nobody has complained about projectiles being too fast

"Nobody asked" moment

**Comment by BeloneX** [comment]
> > I mean we've had it on Sage for ages and nobody has complained about projectiles being too fast
> 
> "Nobody asked" moment

I asked for this, people contribute because they asked for it, I don't care if "you didn't ask"

**Comment by ike709** [comment]
Is 0.01 seconds even a noticeable difference?

**Comment by ghost** [comment]
> Is 0.01 seconds even a noticeable difference?

It is a 25% speed up.

**Comment by ike709** [comment]
Dogecoin going from $0.01 to $0.02 is a 100% increase. Percentile increases are nothing when the actual value is nothing.

**Comment by ike709** [comment]
Also it's a ~14% increase not a 25% increase.

**Comment by ghost** [comment]
Also it is a 0.1 difference, not 0.01

**Comment by ike709** [comment]
ITT: Belone misunderstands units. Assuming the comment on the code is accurate, it is going from 0.7 to 0.8 deciseconds, which is a difference of 0.01 seconds.

**Comment by ghost** [comment]
Alright Ike, yes it is a considerable difference.

**Comment by ike709** [comment]
> 0.01 seconds
> considerable difference

🤔

**Comment by ghost** [comment]
> > 0.01 seconds
> > considerable difference
> 
> 🤔

I do not have time to make a side by side comparison right now, however you can ask anyone else and they will most likely yell you the same thing as I did.

**Comment by francinum** [comment]
I'd be surprised if this didn't just get lost in the rounding error.

**Comment by PowerfulBacon** [comment]
> 
> 
> Is 0.01 seconds even a noticeable difference?

Its 0.1 seconds because beyond uses deciseconds.
Increases time to travel 10 meters by 1 second.

**Review by utilbird — APPROVED** [review]
Meh. Not a huge deal. I don't care either way

**Pull request merged**
