### PR TITLE
Derelict shuttle ruins (Custom shuttles save and appear as ruins)

### PR DESCRIPTION
**Pull request by PowerfulBacon**
Todo List:
- [x] Create a tool that shows what typepaths are allowed to save and which ones aren't.
- [x] (Important) Make it so the server can identify and remove map files with outdated typepaths in them.

## About The Pull Request

Implements derelict shuttle ruins, an ancient shuttle made by adventures from long ago.
Whats special about the derelict shuttles? I didn't make them, you did!

This PR implements a new system that auto saves custom shuttles at the end of each round (with limitations of course).
Upon the beginning of a new round, abandoned signals can spawn which contain derelict shuttles, crashed into asteroids.

This PR also makes the saving proc a lot more robust.

### Administrator Notes

All saved atoms include the 'fingerprintlast' variable. This means that if someone has build a large naughty word, you can right click and use varedit to locate who was the last person to touch that thing.

There are also 3 new adminverbs for managing shuttles:
Shuttle download - Downloads the .dmm shuttle files the way you can download normal logs.
Shuttle view - Spawns the shuttle preview in the world the same way you can preview normal shuttles.
Shuttle delete - Deletes the .dmm shuttle file from the server.

These all require R_ADMIN when the save directory of the shuttles is in a safe location, if its been configured to be in a place thats not safe then it will require R_SERVER.
The config entry is protected from editting to prevent unauthorised access and deletion of server files.

### Saving Safety

To add a bit of safety to the saving, any string variables influenced by the player are not saved. This prevents someone from adding /obj/item/supermatter_sword as the name of something and spawning in something ridiculous. Everything written to the text file is done by the code or is checked to make sure its something safe.
Objects that are var editted or spawned by admins are not saved.
Objects that are indestructible are not saved.
Objects that were spawned by an uplink are not saved.
Objects that has the NO_DROP trait are not saved.
Abstract objects are not saved.
Holograms are not saved.
Objects that do not have the SAVE_SAFE_1 flag will not be saved. (This is a manual whitelist that applied to almost all items). (This was painful to do).
Effects will never be saved.

### Config Settings / Filesize usage

The entire thing is coded into the config and can be adjusted:

```
SAVE_SHUTTLE_RUINS - Flag - If commented out shuttles will not be saved at the end of a round.
SHUTTLE_RUIN_FILEPATH - String - The director that points to where shuttle files should be saved to.
SHUTTLE_TOTAL_FILESIZE_MAX - Number - The maximum filesize of all shuttles in bytes. Currently set to 1MB
SHUTTLE_FILESIZE_MAX - Number - The maximum filesize of a single shuttle in bytes. Currently set to 40kB,
```

The maximum file size for all shuttles will never exceed 1 MB, and old shuttle ruin files will be deleted in a random order if this limit is exceeded.
Shuttles will not be saved if they are more than 40kB in size or larger than 35x35.

### Saving system robustness improvements

The system for saving maps has existed for a long time, but has always been a little bit dodgy at times and fails with a lot of basic tasks.
This expansion allows for variables of things to be modified before saving, vars with custom values to be saved and for items to be processed in groups before saving: This means that custom shuttle consoles will link to the dock, which has an auto generated ID, communication setups and conveyor belts will have the same links they were saved with.

Additionally the administrator map save that can be accessed through build mode now has multiple options. It can be used to save shuttles or stations and can be ran with normal checks or in adminmode which doesn't care about overpowered items that shouldn't be transfered between rounds.

A lot more things have been added to add custom saving behaviour to different objects. Suit storage units will always spawn with the contents that were inside them when saved, presuming the thing inside it is safe to be saved.

### Spawned shuttles

Spawned shuttles have a 20% chance to spawn as it was, and an 80% chance to get a random ruin generator settings. (This means that you can get ruins with the same disasters that occur on ruined stations.)
image

(This shuttle was saved because I force converted it into a custom shuttle using build mode, only custom shuttles are saved by default)

Anyone on the shuttle when it was saved will be saved as a pile of bones, signifying that they were there.

### In action
image
image
image
image
**NOTE: This shuttle looks broken because half of it was cheated and cheated items will not be saved for safety.**

(Size limit reached on purpose)
image
image
image
Shuttle save files are deleted randomly until the size is below the limit again.

image
image
image

image

## Why It's Good For The Game

Hard work can persist across multiple rounds, new ruin types that are **truely** random and you never know what you might come across!

## Changelog
:cl:
add: Adds in derelict shuttle ruins, custom shuttles from previous rounds
code: Significantly improves the map save proc.
config: Adds in new config options related to shuttle saving.
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
Good stuff! It's nice to see the return of this mini-project here's for more supercruise stuff ! Now crew can be encouraged to make shuttles and have a chance to see the abandoned-version of it

**Comment by PowerfulBacon** [comment]
image
Save analyser completed

**Comment by PowerfulBacon** [comment]
This is an awesome PR and is complete, but won't ever happen due to it being hard to get reviews as a maintainer and this PR conflicting with every other PR in existance.

**Comment by itsmeow** [comment]
quit your whining i'll review it

**Comment by PowerfulBacon** [comment]
I still would need a work to figure out the new things

**Comment by Isy232** [comment]
I want this, it'd be awesome

**Pull request closed without merging**
