### PR TITLE
CMO Belt

### PR DESCRIPTION
**Pull request by Chessus**
## About The Pull Request

Adds a medical belt to the CMO at round start. Similar to The Chief Engineer, the CMO now starts with advanced surgery tools, cautery, drapes, an advanced analyser, sterilized medical gauze and sterilizine. The advanced health analyser and compact defib was removed from the CMO locker and the first aid kit removed from the CMO at round start. 

Due to the Sprite overhaul I'm going to leave it as a basic medical belt. 
## Why It's Good For The Game
- The CMO has their own medical belt now. Due to their role as a head, they will now have access to advanced tools like the CE. 
- The Advanced tools encourage early game surgery over clonning. They are much faster and successful than tier 1 tools. 
- The Sterilized medical gauze- Hey this exists! An 'advanced' version of the medical gauze that is unknown. I want to improve this as it has no benefits except for the self-use delay of 5 instead of 20. Might buff it and add a 5 heal to burn as it already has a 5 brute heal.
- The Advanced health analyser is already available to the CMO in their locker, this change takes it out of there and onto the player from the start. Thus, it's removal from the locker.
- The first aid kit is removed as the belt contains most items.
- Compact defib removed from the locker for bacon balance. [Use Strange Reagent instead, Seriously](https://wiki.beestation13.com/view/Chemical_recipes#Strange_Reagent). It's available rouund start and only requires brute/burn to be under 100 (and not husk/suicided). Doesn't need a functional heart or any at all. Heals ALL organ damage, yes all organ damage. Why this isn't made within the first 5 mins of every game is mind boggling.   

~~The CMO's job is not just to heal, they are a Department head/manager therefore having less healing items on them round start re-enforces this idea that they can delegate doctors while they manage other branches of Medical. The advanced tools can be sacrificed for an autodoc later, if the player chooses or they can keep them if materials are tight and now better tools can be made.~~   

## Changelog
:cl:
add: a medical belt specific to the CMO
add: Populated the belt with Surgical Drapes, Laser Scapel, Mechanical Pinchers, Cautery,  Sterilized Medical Gauze, Sterilizine bottle and Advanced Health Analyser.
del: Removed Advanced Health Analyser from CMO locker
del: Removed First Aid Kit spawn from CMO
del: Removed Compact defib from cmo locker (Use Strange Reagent, it's much better.):   
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I don't really like that they start with the advanced tools, since for the CE he has no other particularly useful things that can be obtained through research while the CMO already starts with a few things like the combat defib and the medhud implant. Just feels like it gives the CMO everything possible to be researched from the start.

**Comment by DatBoiTim** [comment]
> I don't really like that they start with the advanced tools, since for the CE he has no other particularly useful things that can be obtained through research while the CMO already starts with a few things like the combat defib and the medhud implant. Just feels like it gives the CMO everything possible to be researched from the start.

CE gets a very good hardsuit, advanced magboots, jet pack module. Also, much like CEs tool belt, the tools aren’t but there’s only 1 set until RnD unlocks them.

**Comment by Chessus** [comment]
@PowerfulBacon I get what you mean but as @DatBoiTim says they have access to a lot more at round start like their own pair of Insuls, engi googles ect. Medical don't get any of the advanced chem stuff and are at basically tier 1 at round start except for the cmo items. 

I think having the advanced tools will also encourage sugery ower clonning.

I'm willing to compromise on the Laser drill though, if I need to. this would gate the auto doc. I'd replace with with either a Bottle of Sterilizer and maybe the Virus extroplater. Something that isn't healing items, something from a different branch of medical. Or something that isn't used as much. 

edit: But i'd like to get as much feedback on it as I can

**Comment by yyzsong** [comment]
> del : Removed First Aid Kit spawn from CMO

I think you should keep the First Aid Kit. The white kit with the red cross that doctors and the CMO start with have wayyyy more storage space than then brute kits and burn kits. A good CMO can use that to carry around a shitload of healing chems, for instance.

**Comment by AnjelicaChaykovsky** [comment]
adv tools for cmo is a good idea i like it

**Comment by Chessus** [comment]
> I think you should keep the First Aid Kit. The white kit with the red cross that doctors and the CMO start with have wayyyy more storage space than then brute kits and burn kits. A good CMO can use that to carry around a shitload of healing chems, for instance.

Yeah I love that kit, I think it can even store a chemist bag within it like a medical belt can. My reason to remove it was that the CMO is not just a healer but works as a manager for all branches, not just healing. They are not just a healer but a viro/chemist/geneticst and someone to suppoourt and ensure the branches are upgraded and have more machines.

**Comment by Chessus** [comment]
@PowerfulBacon The CE has almost every item in enigneering. They have multiple RCDs and RPDs, Engineer scanning googles, holofans, the mag boots, insuls, inducers, jet pack upgrade, welding hard hat and light replacer. Only the advanced tools are on the CE if there is one. Deltastation has a copy of the advanced tools in secure storage. The only thing left be printed are force field projectors, welding gas mask and night vision mesons.  Medbay starts off much weaker and this PR could have included much more op items like the syringe gun and bluespace beakers. 

The belt only spawns with the CMO and this is a role not as popular as other heads. I see nothing wrong with the CMO having access to this gear and the gear within the locker as there's only 1 copy of each and no one hardly breaks into the cmo's officer for those items. It arguable that the cmo is now OP with the items it would currently spawn with. The medhud implant is the weakest of all the implants, the wall mount is similar and only locked behind basic research. The advanced health analyser onw only spawns with the cmo, so it's not there if there's no cmo.  The compact defib is also more of an efficiency item like the medhud implant. The tools themselves aren't as useful until better surgery and surgery comp boards are researched, there's a minor speed increase and success chance but you're sitll doing basic surgeries. 

This Pr will update medbay and bring it closer to the round start potential Engineer has. There's still a lot more to be reaserach like Bluespace body bags, advanced syringes, beakers, syrineg gun, shells and a plethoria of implants.

**Comment by Penwin0** [comment]
>holofans 
CE has no holofans roundstart, only the cringey ass engineering projector

**Comment by Penwin0** [comment]
>welding hard hat and light replacer

Truly essential items

**Comment by Chessus** [comment]
> > holofans
> > CE has no holofans roundstart, only the cringey ass engineering projector

Try another 3 atmos holofans 

> > welding hard hat and light replacer
> 
> Truly essential items

Light replacer is locked behind research and not available to be printed at round start. Welding hard hat is a unique item. 

The argument is not the usefulness but rather what's available round start

**Comment by PowerfulBacon** [comment]
Holofans are printable on mass at a lathe, light replacer is mainly for the janitor and the welding hard hat is essentially useless. The CMO has a bunch of extra items that aren't really used on the level of the CE's special rarely used items

**Comment by Chessus** [comment]
Can you think of any else that might fit? 

I'm trying to think of items that are either underused, aren't healing items or contribute to medical without being healing items (like the holofan).

**Comment by Chessus** [comment]
To keep the scapel and pincher I'm thinking of replacing:

- Searing tool with either a synthflesh patch (synthflesh bottles are being removed) or Sterilizing spray. Although I want to move away from healing items. 

- Holofan with Crew monitoring device

- Removing the compact defib from the locker (Maybe add it to the Paramed so it's still in game). 

- Extractporlator's there so it could replace something.

- Add surgery computer board or stasis/sleeper board

- Other item to add, fluff items like beaker, dropper, mask, gloves.

**Comment by ike709** [comment]
I don't really like buffing heads because heads are usually incompetent, from personal experience.

**Comment by Chessus** [comment]
> I don't really like buffing heads because heads are usually incompetent, from personal experience.

That says more to the the criteria behind unlocking the role. Regardless, the CMO spawns with the same gear as a medical doctor except with the crew pinpointer. Compared this to the CE whom starts off with adanced tools. This PR attempts to start it with gear suited to a head and balances what is already in the locker. 

I'm now actively seeking input of what should be added/removed in order to get this put to a vote.

**Comment by Chessus** [comment]
> Holofans are printable on mass at a lathe, light replacer is mainly for the janitor and the welding hard hat is essentially useless. The CMO has a bunch of extra items that aren't really used on the level of the CE's special rarely used items

Yet they're available at roundstart when they are locked behind research, which was my point.  Well the implant and defib aren't special. The implant just frees up an eye slot or the cmo can grab med adanced glasses from sec. The compact defib is belt worn defib, you just have to  free you belt item. The mount, same thing. Not very special. 

But in saying so, I'm open to ideas to balance that locker gear around this pr which at a minium, should allow the cmo to spawn with better surgical tools than a medical doctor. So I'm keeping the scapel, pinchers and advanced analyser (which would only spawn with the cmo now). I'm open to change everything else in order to get this put to a vote. 

What would you want the cmo to spawn with @ike709 and @PowerfulBacon?

**Comment by Fronsis** [comment]
As a CMO main, i would like to start with a medical belt with the advanced surgery tools, as you mention he also a head of staff after all, while he will never get glasses i'll be alright with this addition, in my personal experience very few CMO carry the defib belt and they usually give it to paramedics or throw it inside the medbay storage for any doctor that feels like using it

- If medbays were revamped to have a little paramedic room having the portable defib there would be perfect
- Synthflesh patch/bottle ehh i don't think it suits the CMO, i mean yeah i would honestly save it to heal myself on emergencies, since the sprays are getting nerfed which i used to buy to heal myself

And well the rest of the stuff you listen well.. i can just walk up to the printer and get them. but yeah CMO's in need of some extra love he's one of the most vulnerable heads and sometimes it lacks having stuff to put medbay in place (I.E needing something like the famous QUARANTINE button on his office so Medbay can get lockdown)

**Comment by Chessus** [comment]
I'll look at code and see if I can come up with something like a Quarentee shitter system. I"ll do it in another PR.

But yeah a few things to consider with the Medicine changes, I think TW will be a more popular options thus having the advanced tools would be great. Yeah that too @Fronsis, I almost forgot about the meta revamping. It just got marked stale

**Comment by Rukofamicom** [comment]
> I don't really like buffing heads

I mirror this. CMO already has plenty of useful stuff at roundstart, they don't need more, all this does is provide further incentive to take the role for extra gear when you aren't actually fit to be the head of medical.

I question the necessity of the CE having equipment that shouldn't even exist yet because no research has gone into creating them. Their belt is also not necessary and greatly motivates people to take the role just for gear when they aren't actually a capable head of staff.

**Comment by ike709** [comment]
Closing due to consensus that this is a bad idea.

**Pull request closed without merging**
