### PR TITLE
 BoxStation Areas Reworks and Fixes

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request

Reworks and fixes some outdated Box shenanigans:

Second attempt of https://github.com/BeeStation/BeeStation-Hornet/pull/10942

- Service area rework
- Medbay rework 
- Captain quarters
- Floating cameras and doble pipes and cables
- Stool errors from https://github.com/BeeStation/BeeStation-Hornet/pull/11281

## Why It's Good For The Game

BoxStation is old and clunky

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

</details>

## Changelog
:cl: Varo, Bombyy, PigeonVerde
tweak: BoxStation: Reworked the service area and maintenance
tweak: BoxStation: Reworked the medbay area and maintenance
add: BoxStation: a room for the psychiatrist in medbay
tweak: BoxStation: fixed chaplain backroom having a weird shape
add: BoxStation: Added a new area, apc and air alarm for the captain room
fix: BoxStation: Fixes floating cameras and doble pipes and cables errors 
fix: BoxStation: Fixes stools directions and types
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
Morgue might need the external door into the hallways for Cooks/Dets/Chaplain IMO

**Comment by ClownMoff** [comment]
> Morgue might need the external door into the hallways for Cooks/Dets/Chaplain IMO

If you think about it, why would a station have the room where they put corpses with a door for the open public

**Comment by Fronsis** [comment]
> > Morgue might need the external door into the hallways for Cooks/Dets/Chaplain IMO
> 
> If you think about it, why would a station have the room where they put corpses with a door facing the open public

I mean, on one side.. it's not a see-through window, it's a door behind access if you nitpick with that thinking a lot of things will be very "???" 

On the other side, a lot of stations already have that style of morgue, Box being one of the most iconic ones where you can access from the hallway, others share that while others use a backroom in maintenance

Finally, i believe it's intended gameplay for the aforementioned jobs and to give antags an opportunity to do things without being caught immediatly but without being necessarily "free" either, they still need to hack in, all in all just consistency pretty much!

**Comment by MarkusLarsson421** [comment]
A surprising amount of roles has Morgue access. I recently learnt that the RD has it for whatever reason...

**Review by spockye — CHANGES_REQUESTED** [review]
image

cabling errors

image

disposals error

image

light clipping into the boxes here. do try to avoid having lights on wallmounts!

image

conflict marker (chairtable)

image

double trouble

image

it floats

image

avoid stacking wallmounts

image

light + stacked mounts

image

now, whats going on here? (i wont comment on all the lights on wallmounts but. you get the gist)

image

double trouble

image

it floats

image

double trouble

image

oh me oh my


image

stacked mounts, two cameras, in walls

image

triple trouble plus double trouble
AND NO APC!!!

image

stray cabling. already a apc in here.

these issues are everywhere, though i understand why :p just thought i'd point out a couple to help out

**Comment by MarkusLarsson421** [comment]
image

**Comment by ClownMoff** [comment]
> > these issues are everywhere, though i understand why :p just thought i'd point out a couple to help out

The issues are there because the freeze fucked everythign up, most of the stuff that is pointedo ut by @spockye is product of the many merge conflicts, even missplaced disposals and stuffl like that.

**Comment by PowerfulBacon** [comment]
Are you using mapmerge to merge the maps?

**Comment by ClownMoff** [comment]
nO

**Comment by PowerfulBacon** [comment]
You should be, otherwise you will have a terrible time with things being merged incorrectly. You can find it in the tools subfolder of the repo

**Review by spockye — CHANGES_REQUESTED** [review]
image

use the new directional wallmounts!

image

image

move this light. people WILL burn their hands, using the machine and storage

image

two wallmounts stacked

image

posters should ALWAYS be +-32

image

image

apc under poster. i dont like the diskette box being on the computer. try moving the maint door one down, and adding another table or something.

image

random decal

image

image

mabye break this up with a wall? not a huge fan of a all glass wall going into maintenance. 



didnt check everything. look it over one more time pretty please.

**Comment by spockye** [comment]
Cameras are broken all across the map, due to a faulty merge probably. please fix this. 

image

image


(there are atleast thirty instances of this on the map. search by [/obj/machinery/camera/autoname]

**Review by spockye — CHANGES_REQUESTED** [review]
1. Fix the broken decalling
2. fix the holodeck
3. replace ALL the autoname cameras with directional
4. fix the overlapping wallmounts
5. fix the broken viro posters
6. fix the broken flooring at the theatre stage
7. fix floating light in kitchen

Look in discord for the rest of the review.

**Review by spockye — COMMENTED** [review]
[ignore]

**Review by spockye — CHANGES_REQUESTED** [review]
<details open>
<summary>The Review</summary>
<br>
image

image

these decals are set to layer 1 and dont appear ingame


image

this door cant be opened by the chef. use `"req_one_access_txt 28;25;35"` instead

image

looks a lot better if you have one of the windoors going in the other direction. 


image

should be windoors here!

image

floating comms

image

this table feels a little empty... perfect place for a cookbook!

image

put some donkpockets  and a desk bell on this table! pretty please :-)

image
two apc's in one room.

image

stacked wallmounts. try to avoid

image

apc under poster

image

not really a fan of the disk box ontop of the computer. mabye give them another table?

image

light switch ontop of fire cabinet. same side of the wall.

image


stacked decalling in here.


</details>


Just get the final issues ironed out and it'll be good!

**Comment by ClownMoff** [comment]
Great, more conflicts!

**Comment by ClownMoff** [comment]
Great, more conflicts!

**Comment by ClownMoff** [comment]
imagen

**Review by spockye — CHANGES_REQUESTED** [review]
image

floating wires, bar

image

floating wire, med storage


image

broken wallmounts

image

table intercom?

image

floating air alarm

**Comment by PestoVerde322** [comment]
immagine

This door has weird accesses

immagine

Floating firelock

Other than that all good.

**Review by PestoVerde322 — APPROVED** [review]
Hopefully it should be all good to go, approved!

**Review by spockye — COMMENTED** [review]
two small decal oddities. other then that, its good to go! 

image
image


image

**Review by spockye — APPROVED** [review]

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
