### PR TITLE
readds 2viro

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
increases viro slots by 1

## Why It's Good For The Game
our viro is mapped for 2 virologists, and we had 2 slots in config at one point, but now we dont. this reenables that, so now two people can do virology at once

## Changelog
:cl:
config: adds an extra virologist slot
/:cl:

### CODE REVIEW

**Comment by r1ks-iwnl** [comment]
Double trouble

**Comment by Archanial** [comment]
Not every viro is mapped for two iirc

**Comment by AnCopper** [comment]
But how am I going to know which one I should lynch for a sentient disease?

**Comment by St0rmC4st3r** [comment]
> But how am I going to know which one I should lynch for a sentient disease?

Kill them all, God will know His own.

**Comment by zeskorion** [comment]
> Not every viro is mapped for two iirc

Every one on maps in active rotation is

**Comment by zeskorion** [comment]
> But how am I going to know which one I should lynch for a sentient disease?

This is intentional

**Comment by francinum** [comment]
Jobs.txt is not used on production servers. This edit does nothing.

**Pull request closed without merging**
