### PR TITLE
Makes new players struggle to light cigarettes for others

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

Anyone with under 5hrs living playtime or less than 10d byond account age is simply bad at lighting cigarettes for others (Get more creative lmao, 0 effort tactic honestly). This means they get a little 1.5sec progress bar and a visible message if they fail, hopefully giving notice to the lightee.

Also anyone meeting this criteria's explosions have no light range, instead only setting the person on fire.

## Why It's Good For The Game

I know in the past we have said that we won't change gameplay simply to stop griefers... buuuuut this one doesn't affect non-0hrs chads (of which, the real noobs shouldn't even need or use this feature) and also doesn't significantly change gameplay, as it's still *possible*, it's just harder and gives notice to the person you are doing it to.

Generally I think this is a decent compromise between not limiting the potential of this feature and giving the griefers a hard time

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Lmao noob, you have a 1sec do_after

image

Oooonly flames
image
image

Literally weak
image

</details>

## Changelog

No CL :trollface:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
Cringe Slipperly slope. less cringe than #8182 

dont really care though, i cant think of a better solution lol

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Just change this for everyone and remove the playtime check. If it's an instant win unexpected strategy then it's bad either way. Plasma cigars should be stealthy and a trap rather than something you can light on somebody else.

**Comment by Fronsis** [comment]
Good riddance

Does this also cover the "lit the ciggie underneath their feet for insta boom?" That was mostly used rather than lighting it to someone in their mouth

**Comment by Antops12** [comment]
you could make it so that when a player taps you with a lighter, the same interaction as when someone offers an item pops up, but instead, it's to accept them lighting your cig

**Comment by itsmeow** [comment]
> Good riddance
> 
> Does this also cover the "lit the ciggie underneath their feet for insta boom?" That was mostly used rather than lighting it to someone in their mouth

Hm, no timer but it would still be a weaker explosion

**Comment by hotimep** [comment]
idk guys this is super funny because for new players lighting cigarettes is a monumental task that requires all of their previous knowledge in this game and is a test to see how truly robust they are +1 good change

**Comment by PowerfulBacon** [comment]
Does an explosion range of 1 light actually do that much damage?

**Comment by itsmeow** [comment]
> Does an explosion range of 1 light actually do that much damage?

If you're on the tile, enough to make it hurt.

**Comment by Rukofamicom** [comment]
> Just change this for everyone and remove the playtime check. If it's an instant win unexpected strategy then it's bad either way. Plasma cigars should be stealthy and a trap rather than something you can light on somebody else.

I second this for the record.  
The issue isn't so much that it's common griefman strat, it's how cheap of a trick it is in the first place.

**Comment by PowerfulBacon** [comment]
In terms of griefing strategies, this one really isn't that bad. If we don't like it then this should be applied to everyone

**Comment by itsmeow** [comment]
I'm going to make changes to this, don't close yet

**Comment by PowerfulBacon** [comment]
If we are deploying a player age check then it should be a proc for querying if a user account is suspicious and should have certain activities restricted and should be applied to the major grief things like triggering maxcaps or BOH's and should have a variable to allow it to happen if the account is an antagonist.

**Comment by itsmeow** [comment]
Finally. I can add /client/var/sus.

**Comment by PowerfulBacon** [comment]
Feel free to reopen if changes are made. Closing due to no activity and not being mergable in this state.

**Comment by DrDuckedGoose** [comment]
Is that standard procedure?

**Comment by Tsar-Salat** [comment]
> Is that standard procedure?

For 2 out of 3 keys on a maints pr? Nothing standard applies really.

Interested to see what angle the changes take though. I've seen blanket checks, reworks of lighting, antag checks, playertime checks...

Like 5 PRs have tried to resolve this, so I guess it makes sense if the current immediate solution isn't liked for it not to be open

**Pull request closed without merging**
