### PR TITLE
New plasma Sprite

### PR DESCRIPTION
**Pull request by Flakkyboo**
## About The Pull Request

New sprite to make plasma nice and distinct for bee.
Permission for sprite to be used given by Gidgee Sheep

## Why It's Good For The Game

newPlasma-revised

I mean just look at that makes it look all esoteric and spooky 

## Changelog
:cl:
imageadd: New sprite for plasma provided by Gidgee Sheep.
/:cl:

### CODE REVIEW

**Comment by gidgeesheep** [comment]
:)

**Comment by WarRage333** [comment]
how it look on fire

**Comment by Flakkyboo** [comment]
> 
> 
> how it look on fire

the same fire sprite doesnt change

**Comment by Mick1299** [comment]
Now people wont freak out when scrubbers eject glitter

**Comment by Flakkyboo** [comment]
They should still freak out but now glitter will look a bit odd with the lightning

**Comment by Sinmero** [comment]
The lightning effect is too hard on the eyes and doesnt blend between tiles very well.

**Comment by Flakkyboo** [comment]
> 
> 
> The lightning effect is too hard on the eyes and doesnt blend between tiles very well.

i think thats going to be an issue with any atmos tile that has hard color differences.
that being said i think its an overall upgrade on what we have gas tiles overall are very bland.
i would direct feedback into the discord however and ping the spriter gidgee sheep 

im unsure if they read this

**Comment by gidgeesheep** [comment]
> The lightning effect is too hard on the eyes and doesnt blend between tiles very well.

I acknowledge this problem. I will be willing to make any changes to the plasma if it really becomes more of a problem. Thats the fun part of editing.

**Comment by nikk735** [comment]
make glitter the old sprite lmao

**Comment by TeomanTheGreat** [comment]
Testmerge now hnnng

**Comment by eLeCtrOssSnake** [comment]
Negative.

**Comment by MCterra10** [comment]
no newlines in changelogs please, thanks

**Comment by Flakkyboo** [comment]
I just woke up and seen this, it's updated

**Pull request merged**
