### PR TITLE
Bans Eris sprites

### PR DESCRIPTION
**Pull request by ike709**
## About The Pull Request

The color palette is awful and having like 20 Eris sprites creates an awful style mishmash on top of our already awful style mishmash.

## Changelog
:cl:
add: Updated the contributing guidelines.
/:cl:

### CODE REVIEW

**Comment by utilbird** [comment]
based

**Comment by maikilangiolo** [comment]
I don't make PRs i am the commenter of PRs and you broke the rules buddy, https://wiki.cev-eris.com/Content_GuidelinesEn you should try reading these. This PR is useless and you should be ashamed you ever made it, get out of my sight.

**Comment by thedarkcrusader** [comment]
I don't make PRs i am the commenter of PRs and you broke the rules buddy, https://wiki.cev-eris.com/Content_GuidelinesEn you should try reading these. This PR is useless and you should be ashamed you ever made it, get out of my sight.

**Comment by ValoTheValo** [comment]
Firstly there is absolutely no reason for this to be made, secondly it will screw up loot and make all these items more common, thirdly, one and possibly more items price changes are direct violation to contributing guidelines, you should try reading them.
https://wiki.cev-eris.com/Content_GuidelinesEn

meming aside thanks for banning stealing our sprites since they seem to get stolen every 5 minutes

**Pull request merged**
