### PR TITLE
Ports new overlay lighting component and opacity refactor from tg

### PR DESCRIPTION
**Pull request by Sinestia**
## About The Pull Request
**Yorii created the original PR and did the work https://github.com/BeeStation/BeeStation-Hornet/pull/4357 however, they're extremely busy, so I will adopt this.**

Ports tgstation/tgstation#52881 and tgstation/tgstation#52413

also
tgstation/tgstation#53317
tgstation/tgstation#54520
tgstation/tgstation#57058

I also moved a couple defines to color.dm
## Why It's Good For The Game

No more laggy broken flashlights.

Big lag reduction, especially late in the round if the TiDi is ramping up. 

## Changelog
:cl:Yorii, Adopted by Froststahr
add: Smooth movable lighting system implemented. Projectiles, sparks, thrown flashlights or moving mobs with lights should be much smoother and less laggy.
add: Directional lighting is in, applying to certain things like flashlights, headlamps, etc.
balance: Light sources no longer stack in range, though they still do in intensity.
balance: Mechs no longer block sight. It's a non-trivial cost for the lighting system with little to no gain.
/:cl:

### CODE REVIEW

**Comment by Sinestia** [comment]
oh, huh. lil more than just the merge conflict. 
o well ill get around to it

**Comment by mcmeiler** [comment]
Isn't this a duplicate of #4357 ?

**Comment by Archanial** [comment]
I know circuit shells had some of it, did you reimplement it?

**Comment by PowerfulBacon** [comment]
did you fix the overlay bug?

**Comment by Sinestia** [comment]
Nope and Nope


Guess there's some work to do to get this up to date which will be completed in exactly One Business Day

**Comment by Sinestia** [comment]
ok did circuiterino and the right click bug didnt exist for me

**Comment by PowerfulBacon** [comment]
> 
> 
> ok did circuiterino and the right click bug didnt exist for me

When you right click on an atom that emits light the icon is a black circle

**Comment by Sinestia** [comment]
> 
> 
> > ok did circuiterino and the right click bug didnt exist for me
> 
> When you right click on an atom that emits light the icon is a black circle

OH i thought it applied to everything, whoops

**Pull request merged**
