### PR TITLE
Adds the old gas mask back.

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Old gasmask is back.
It is part of maint loot and new one has been removed from the loot table.
It's part of the greytide trauma.
It spawns with the emergency space suits.

## Why It's Good For The Game

greytide

## Changelog
:cl:
add: Old mask is back.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Inconsistency bad.

**Comment by Sinestia** [comment]
half-measure is worse than either removing it or keeping it

**Comment by Archanial** [comment]
> 
> 
> half-measure is worse than either removing it or keeping it

This is not half-measure. You get choice between 2 of them, if you wish to wear the new one feel free, most of them will have newer sprite.

**Comment by BitBite112** [comment]
We should only have the old one in.

**Comment by ike709** [comment]
@SomeAngryMiner

**Comment by SomeAngryMiner** [comment]
people like the old gasmask, and this isnt holding back anything or changing much of the direction we planned, so fine by me.
At one point we'll have to touch it up, but thats for the far future.

**Review by SomeAngryMiner — DISMISSED** [review]

**Comment by ToasterBan** [comment]
grey tide station wide 😔✊

**Comment by PowerfulBacon** [comment]
Dont make it a probability, put the old ones in maints and the new, more modern looking ones in engineering / fire closets

**Comment by Sinestia** [comment]
> Dont make it a probability, put the old ones in maints and the new, more modern looking ones in engineering / fire closets

That sounds a lot better and would change my minimally-valuable opinion to a +1

**Comment by Effemu** [comment]
greytide surplus crate when?

**Review by PowerfulBacon — APPROVED** [review]

**Comment by Isy232** [comment]
I think this is totally fine to have both.

Older ones found in old maint tunnels.

New ones found stocked in places meant for them.

**Comment by Sinestia** [comment]
Very good change now

**Pull request merged**
