### PR TITLE
Buffs the chaplain's null rod

### PR DESCRIPTION
**Pull request by bloons3**
## About The Pull Request

-removed the barber's roundstart snowflake weapon

## Why It's Good For The Game
-reduces powergame potential of random maint spawns
-buffs the value of the chaplain's null rod

## Changelog
:cl:
tweak: made the chaplain's nullrod more valuable
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
how does removing a chainsaw make the chaplain more powerful???

**Comment by Rukofamicom** [comment]
I think he's joking about how Chaplain is the only role that gets a (semi) justifiable roundstart chainsaw after this.

**Comment by bloons3** [comment]
> how does removing a chainsaw make the chaplain more powerful???

The chaplain's nullrod gains more value as being the only thing that can become a chainsaw, instead of a chainsaw starting on the station.

There is precedent that chainsaws are null-rod only or gateway loot. It doesn't make sense for such a powerful weapon to start unsecured in maint.

**Comment by Penwin0** [comment]
You can craft a chainsaw instantly roundstart in robo

**Comment by bloons3** [comment]
> You can craft a chainsaw instantly roundstart in robo

I'd rather it requires some slight effort than simply being given to a player

**Comment by OceanFish1** [comment]
You can literally craft a chainsaw out of metal scrap and plasteel and ask a random doctor to attach it

**Comment by eeSPee** [comment]
Oversight: The chainsaw was in there so that barber can perform 'ghetto' surgery with the tools he had. He can't do that if you remove that. You should replace it with a hatchet, at least.

**Comment by eeSPee** [comment]
Oh yea:

>/datum/crafting_recipe/chainsaw
>	name = "Chainsaw"
>	result = /obj/item/twohanded/required/chainsaw
>	reqs = list(/obj/item/circular_saw = 1,
>				/obj/item/stack/cable_coil = 3,
>				/obj/item/stack/sheet/plasteel = 5)
>	tools = list(TOOL_WELDER)
>	time = 50
>	category = CAT_WEAPONRY
>	subcategory = CAT_WEAPON

And changelog doesn't describe what it does.

**Comment by bloons3** [comment]
> Oh yea:
> 
> > /datum/crafting_recipe/chainsaw
> > name = "Chainsaw"
> > result = /obj/item/twohanded/required/chainsaw
> > reqs = list(/obj/item/circular_saw = 1,
> > /obj/item/stack/cable_coil = 3,
> > /obj/item/stack/sheet/plasteel = 5)
> > tools = list(TOOL_WELDER)
> > time = 50
> > category = CAT_WEAPONRY
> > subcategory = CAT_WEAPON
> 
> And changelog doesn't describe what it does.

I'm not interested in removing or changing the crafting recipe for a chainsaw, I'd simply like to remove one that starts in maint.

**Comment by Fronsis** [comment]
> Oversight: The chainsaw was in there so that barber can perform 'ghetto' surgery with the tools he had. He can't do that if you remove that. You should replace it with a hatchet, at least.

This, since he has all the ghetto kit, might as well replace chainsaw with something like hatchet or relevant ghetto

**Comment by bloons3** [comment]
> > Oversight: The chainsaw was in there so that barber can perform 'ghetto' surgery with the tools he had. He can't do that if you remove that. You should replace it with a hatchet, at least.
> 
> This, since he has all the ghetto kit, might as well replace chainsaw with something like hatchet or relevant ghetto

Might replace with the butcher knife or botany hatchet.

**Comment by PowerfulBacon** [comment]
what does this have anything to do with the chaplains null rod. Name the PR about what you are actually doing rather than what it could potentially do

**Comment by eeSPee** [comment]
> > > Oversight: The chainsaw was in there so that barber can perform 'ghetto' surgery with the tools he had. He can't do that if you remove that. You should replace it with a hatchet, at least.
> > 
> > 
> > This, since he has all the ghetto kit, might as well replace chainsaw with something like hatchet or relevant ghetto
> 
> Might replace with the butcher knife or botany hatchet.

I vote for hatchet, simply because the success rate is 50% higher than that of the butcher knife's.

**Comment by DatBoiTim** [comment]
Yeah CL and PR description need to be more accurate.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Make the PR title and the changelog not deceptive

**Pull request closed without merging**
