### PR TITLE
Revert "Food Supply Changes and Food Fillers"

### PR DESCRIPTION
**Pull request by Liver-1**
## About The Pull Request
Reverts BeeStation/BeeStation-Hornet#9704

## Why It's Good For The Game

1- This PR had a massive effect on the security, explorer and miner teams, creating impossible situations where they get hit by a massive movespeed debuff with no warning, sometimes in mid-combat.
2- The security team now has much less access to a thematic, funny, and historically respected method of healing; namely donuts. The removal of donuts from sec vendors, as well as many other valuable locations, has resulted in an unexpected nerf to security, compounded by the recent storage nerfs.
3- The changes to food in rest areas of various departments has made those areas now have no use. 
4- The changes to donk pockets has reduced the amount of omnizine available in those items, leading to reduced healing potential for jobs that rely on a warm donk to save them from death (explorers).
5- This change has resulted in a hard nerf to races that eat normal food, thereby buffing plasmamen, moths, lizards and ethereals.

This was a massive overreach that aimed to improve the relevance of chef, but massively overcompensated, resulting in a QoL detriment to all.

## Changelog
:cl:
del: Reverts Food Supply Changes and Food Fillers (Begone, Maltodextrin!) (BeeStation/BeeStation-Hornet#9704)
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Yea, the problem with making the chef more relevant through punishing players for not going through the chef is when there is no chef around. I'd rather eating food just gave people buffs rather than not eating giving debuffs at this point tbh.

**Comment by Rukofamicom** [comment]
> but massively overcompensated

Then how about we try tweaking how it works first?

**Comment by Rukofamicom** [comment]
## What I do dislike about the original PR and think need to be fixed:

> The security team now has much less access to a thematic, funny, and historically respected method of healing; namely donuts.

I don't like mapping changes, but I actually requested this not be done on the original PR so I'd be really happy if someone else mapped these back in. I left the mapping approval to a secondary maint and it was instead merged as-is.

image



> where they get hit by a massive movespeed debuff with no warning, sometimes in mid-combat.

Now that I'm not working on the Halloween event anymore, I'm cooking up some tweaks to how maltodextrin applies its negative nutrition so the latter will stop happening because I fully agree that going from satisfied to instantaneous starving is an issue. 

I'm also looking at exactly how much nutrition maltodextrin drains so it's closer to breaking even rather than actually being a net loss - junk food will fill you up for a while, and then make you hungry again but not hungrier than you were before you ate it.

**Comment by Rukofamicom** [comment]
Finished #10102

I really don't like mapping but I'd appreciate and approve re-adding donuts even if it's a full reversion instead of what I asked exactly. It's worth noting that maltodextrin was actually a buff to donuts though.

**Comment by Harranhall** [comment]
> Finished #10102
I assume you meant to link  #10103

**Comment by Rukofamicom** [comment]
Yes, that's a typo lol

**Comment by DarnTheMarn** [comment]
>The security team now has much less access to a thematic, funny, and historically respected method of healing; namely donuts.

They had a frankly insane amount of donuts available before hand. 12 donuts in the sec tech, 6 donuts in the brig, plus a box of donk pockets, plus they were able to swipe donuts from the public areas and their assigned departments. If you want free healing without going to medbay, ask the bartender to make you quadruple sec. That requires interaction with other crewmembers compared to chomping on donuts which prevent interaction.

The movespeed complaint is valid, look at Ruko's tweaking PR for that.

> The changes to food in rest areas of various departments has made those areas now have no use.

Rest departments didn't have their donk box spawns removed, the only food that was removed was the odd full meal sitting on tables and the multitude of donk pocket boxes. 

> The changes to donk pockets has reduced the amount of omnizine available in those items, leading to reduced healing potential for jobs that rely on a warm donk to save them from death (explorers).

Omnizine was not removed or reduced from donk pockets

>This change has resulted in a hard nerf to races that eat normal food, thereby buffing plasmamen, moths, lizards and ethereals.

It probably should be added to moths eating clothes with Ruko's changes, As for plasmamen/lizards/ethereals, what can you really do. Plasmamen don't eat, IPCs and Ethereals don't "eat" either. Lizards can eat organs and raw meat but at that point you could have made yourself food anyway.

Not to say the PR did not have the intended effect and should not be changed, but I did have a reason and method for the changes even if it was not implemented in the most perfect manner.

**Comment by Fronsis** [comment]
> > The security team now has much less access to a thematic, funny, and historically respected method of healing; namely donuts.
> 
> They had a frankly insane amount of donuts available before hand. 12 donuts in the sec tech, 6 donuts in the brig, plus a box of donk pockets, plus they were able to swipe donuts from the public areas and their assigned departments. If you want free healing without going to medbay, ask the bartender to make you quadruple sec. That requires interaction with other crewmembers compared to chomping on donuts which prevent interaction.

Depends, on a fully staffed shift, by the hour and a half most of the donuts are gone, because you have Warden+5 officers + HoS eating the donuts, not because they need the heal but because some officers just eat a few roundstart and through the shift, even with a chef present, that's just personal preferences, i like to go to the chef when there's food and some other times we just joke around and play with the ''meme'' of ''ah yes we love donuts'' and so on, it has it's own culture more or less.

In fact most of the time in maps like Fland you rarely see the donk pockets being eaten, but yeah this PR does makes some solid points, sec is the lesser affected tbh, i'll check on Ruko PR and see what's up with it.

**Comment by Harranhall** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/10103 takes care of this in a way I am happy with.

**Pull request closed without merging**
