### PR TITLE
[Port] Big Moth Pref Update and fixes

### PR DESCRIPTION
**Pull request by Tsar-Salat**
## About The Pull Request
Port of: 

- https://github.com/tgstation/tgstation/pull/45575 
- https://github.com/tgstation/tgstation/pull/53928 
- https://github.com/tgstation/tgstation/pull/71243
- https://github.com/tgstation/tgstation/pull/54051

1. Removes the antennae part of the original moth wing sprites and adds them back as a mutant bodypart.
They are now under player preferences.

2. Some of the moth_wing sprites have transparent elements, meant to change the body's coloration, that are completely covered by the player's body and are thus unseeable. I moved the sprites to their own file, fixed the layer they were on, and allowed them to be picked by players during moth character creation.

3. Fat sprites that slow down stuff suck

## Why It's Good For The Game

1. image
Mothpeople have always had atrocious dismemberment, because their antennae and markings are present only on the torso.
Here you can see the antennae and facial markings floating over where their head would be, post decapitation.
This is before my changes.

image image

This is after, with the original carbon present for comparison.
The antennae are affected by fire the same way that their wings are, and have no mechanical function outside of that.
Their antennae are visible again if their head is reattached, and are restored when ahealed just like burnt off wings are.

2. Lizards and humans have a great degree of customizability, something less present in mothpeople. This change opens up possibilities for moth customization, as the uniform body color was rather uninteresting.

3. EDIT: Moth wings are a really weird 45x34. It's not obvious why, as they all stay within 32x32 bounds. Crops them all to 32x32 and saves the very expensive Crop cost in the preference icon generation for moth wings.

</details>

## Changelog
:cl: ArcaneDefence, tmtmtl30, Mothblocks, and RKz
rscadd: Added Mothperson markings.
add: Mothpeople now have a preference to choose their antennae type from.
fix: Mothpeople will no longer have floating antennae when decapitated.
fix: The markings on mothpeople will not show over missing or augmented limbs any more.
fix: cut initialization time by 0.18s due to unecessary crop size of moth_wing.dmi
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
think i borked player preferences lol, cant open character setup

**Comment by itsmeow** [comment]
We use a database for preferences now, you would need a local one to test it

**Comment by Tsar-Salat** [comment]
> We use a database for preferences now, you would need a local one to test it

confirmed working now
image

**Comment by Tsar-Salat** [comment]
image
https://cdn.discordapp.com/attachments/565330972707651584/1042160235634229388/decapped.png

**Comment by Tsar-Salat** [comment]
Including: https://github.com/tgstation/tgstation/pull/71243 in pr at pigeon's request

**Comment by PestoVerde322** [comment]
good stuff.

**Comment by itsmeow** [comment]
wow, saving me 0.18s. instant merge

**Comment by Tsar-Salat** [comment]
Merge, Tatakae!

**Comment by Tsar-Salat** [comment]
Including: https://github.com/tgstation/tgstation/pull/54051 in pr at pigeon's request

**Comment by itsmeow** [comment]
Wing preview does not work on local at all
image

**Comment by Tsar-Salat** [comment]
> Wing preview does not work on local at all

My PR does not affect that. It is an inconsistent codebase issue that I cannot account for. 
codebase issue

As can be seen here, it happens on current version aswell, it is not limited to my branch.

**Comment by itsmeow** [comment]
bruhh

**Comment by Tsar-Salat** [comment]
what, never make a moth character before? lmao

i dunno what causes it but its been here long as I can remember. Pre-kapulimbs even

**Review by PestoVerde322 — COMMENTED** [review]
Can confirm, the moth wings/addition on the character just breaks and disappear in the character editor even pre-kapu.

**Review by PestoVerde322 — APPROVED** [review]
All seems good after testing, approved!

**Review by itsmeow — APPROVED** [review]

**Pull request merged**
