### PR TITLE
[Grug PR] Realigns Beemos to Citmos. 

### PR DESCRIPTION
**Pull request by Sinestia**
## About The Pull Request

**I legit sat on this for like an hour wondering if I hated it enough to avoid submitting it I am not proud of this at all.** 

What's the laziest way to fix some of our auxmos problems
Just change our atmos to match the server it was made for LMAO.

https://github.com/BeeStation/BeeStation-Hornet/pull/700
The changes in this and park's atmos and radiation ball have been nuked (latter one def ought to be readded in)

This also includes unit tests. Nice bonus. I hope CI doesn't explode. 

## Easily describable mechanical differences for players:
Nitryl is much easier to make, requiring nitrous instead of pluox and much less heat.
Hypernob is much easier as well, using n2 and tritium with less heat.
N2O no longer decays (Note for me: Check SM code, although N2O was never terribly strong in the first place.)

On citadel open turf was disabled, I reenabled it. It works okay. 
I would say that generally, the changes they made were aimed at making fusion an end in itself, instead of something you do SO that you are able to do *other things*

**I tested this insofar as I did some funny reactions on a test server, basic reflow etc.**
## Why It's Good For The Game

The value is dubious, I did it because Ike mentioned reverting park's fusion changes and I thought "Why not just change the whole thing."

This allows for fusion_hooking to be reenabled and in my testing, it fixes a good amount of our absolute heap of runtime and GC errors. People might like these changes too.

The dll is if a testmerge is desired instead of this just being closed lol. 

If I were to argue for this as a long-term idea -- I'd say that no one has been developing beemos or even expressed any consistent interest in doing so. Also any time i talk about porting the HFR people dislike it as well. Putnam has multiple plans with atmos and is actively developing it, with multiple PRs open at this moment even. Both of my suggestions have pretty much been to hitch it to an actively-developed atmos system.  
## Changelog
:cl: Froststahr
tweak: Atmospherics code has been realigned to match the server auxmos came from, citadel.
/:cl:

### CODE REVIEW

**Comment by Sinestia** [comment]
This is technically ready but it's in draft because it's dumb and I mostly just threw it up to see if there was actual interest

Would necessitate a revert of https://github.com/BeeStation/auxmos/pull/1

**Comment by BrumalLake** [comment]
nob already uses n2 and tritium

**Comment by Sinestia** [comment]
> 
> 
> nob already uses n2 and tritium

**Technically** the only thing I noted as a difference was the reduced heat 
GIGA

**Comment by BrumalLake** [comment]
n2o also no longer seems to decay

**Comment by Sinestia** [comment]
added, did forget to mention as it's not something players seek out.

**Comment by BrumalLake** [comment]
this gets rid of the stimulum ball reaction as well and nuclear particle strength levels which is an unnecessary regression

**Comment by Sinestia** [comment]
Stimball is unused so I didn't think it was worth saving. 

 Both would be easy to return though tbh 

edit: there are plans for nitrous decomp on their side too

edit2: In any case, another part of the motivation for me doing this was to frankly just investigate what the fuck is different and why our runtime log is so massive. I got what I originally wanted basically

**Pull request closed without merging**
