### PR TITLE
Reload mentors on edit

### PR DESCRIPTION
**Pull request by francinum**
## About The Pull Request
This system is awful and needs a core refactor that I don't want to try again to do.

## Why It's Good For The Game
mentor edits are now made live immediately instead of requiring waiting until next round.

## Changelog
:cl:
admin: Mentor panel edits now take effect immediately.
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
I smell web edit

**Comment by francinum** [comment]
boy I love github

**Comment by francinum** [comment]
It wasn't even github.

It was hippie

**Comment by PowerfulBacon** [comment]
Holy fuck, this reminds me of the time I tried to edit 1 line of a mentor file and the ENTIRE thing was spaces

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
