### PR TITLE
Greentext is dead. Long live Greentext.

### PR DESCRIPTION
**Pull request by Rukofamicom**
## About The Pull Request

Removes literal greentext in its entirety. 
Antagonists are no longer declared dead/surviving and no longer have their objective completion shown on the end report. 

This does not touch any of the systems *except* the display at the end of the round. Functional objectives are still tracked for other backend purposes. 

## Why It's Good For The Game
Removes the remaining incentive to minmax for the sake of objectives by both removing the stigma for failing and removing the show-off value for succeeding. Antagonists should be judged based on how much fun everyone had, not based on whether some text validates them for being so sneaky nobody even knew they existed or had a chance to interact with them. 

> Antagonists exist for the purpose of inciting conflict and roleplay, not for the purpose of greentexting.

> While antagonists are supposed to be the enemies of the station, above all you should seek to make the round more engaging and fun as the star of the show. Succeeding as an antagonist is not the "goal" of SS13, the goal is for all players to have fun.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

### Extensive testing will not be done until after I have gauged reception.
There are a *lot* of antags to test, so I'd appreciate knowing the effort of testing it isn't going to be wasted before putting the time into that. 

image

</details>

## Changelog
:cl:
del: Removes greentext from round end reports
/:cl:

### CODE REVIEW

**Comment by Rukofamicom** [comment]
Better and/or more open ended objectives across the board will be miles better than this alone, but even this alone is a step in the right direction.

**Comment by Effemu** [comment]
ruko on his way to singlehandedly start civil war and breakup of beestation (very based)

> Antagonists should be judged based on how much fun everyone had, not based on whether some text validates them for being so sneaky nobody even knew they existed or had a chance to interact with them.

this sounds like participation trophies with extra steps

**Comment by Howluinb** [comment]
...okay, but you forget the fact round end reports of objectives allows to see whether the antag acted properly or just griefed.

Also, no, this is stupid. People will just say after round end "hey well i greentexted this shift" no matter if others can or cannot confirm.

RP will not be improved because you removed a funny green. 

If you want to improve RP via objectives, make it something like all the HRP servers, where you pick your own objectives and get rewards in such a way.
This is just a bad idea.

**Comment by Rukofamicom** [comment]
> ...okay, but you forget the fact round end reports of objectives allows to see whether the antag acted properly or just griefed.

did you even look at the example image? You can still see this, I only removed the literal greentext/redtext part of the report. 

image

**Comment by Wilchenx** [comment]
>Antagonists should be judged based on how much fun everyone had, not based on whether some text validates them for **being so sneaky nobody even knew they existed or had a chance to interact with them.**

This is what you get for removing murderbone.

**Comment by Howluinb** [comment]
> > ...okay, but you forget the fact round end reports of objectives allows to see whether the antag acted properly or just griefed.
> 
> did you even look at the example image? You can still see this, I only removed the literal greentext/redtext part of the report.

Fair enough, my other points still stand. You're not improving RP in any capacity, people will still claim greentext or not in ooc (this time without needing to provide proof), and people will still play the exact same way.

On the other hand, you're removing a feature a bunch of people find fun to see, and something that's quite iconic to most ss13 players.

I see no positives to this change, only negatives, and I have 0 idea how you thought this would improve anything at all.

**Comment by DerpiestBruh** [comment]
This doesnt make sense. Bad PR.

**Comment by Howluinb** [comment]
If anything, I'd argue it'd make traitors do even less. If now they don't feel like they have to accomplish any objectives, they'll skip over any objective they find annoying/too hard and rounds will be even more boring than they currently are as a result

**Comment by Rukofamicom** [comment]
I'm also open to suggestions that do any of the following:
* Chase away people who don't want to RP to leave the community and stop diluting the player quality with sweaty tryhards
* Encourage antagonists not to care about winning and instead prioritize making rounds fun for more than themselves
* Encourage security not to care about winning and instead prioritize making rounds fun for more than themselves
* Chase away people who only care about themselves in general, particularly those that want to make an inflexible plan and then hole up in one place largely alone for the entire shift. 
* Preferably all without negatively impacting the fun for people who aren't causing these problems. 

@Howluinb @Wilchenx @DerpiestBruh @Effemu 
Toss me some suggestions to work with that do any of the above and actively encourage players to follow rules

**Comment by DerpiestBruh** [comment]
>Toss me some suggestions to work with that do any of the above and actively encourage players to follow rules

revert shove nerf PR

**Comment by Howluinb** [comment]
> I'm also open to suggestions that do any of the following:
> 
>     * Chase away people who don't want to RP to leave the community and stop diluting the player quality with sweaty tryhards
> 
>     * Encourage antagonists not to care about winning and instead prioritize making rounds fun for more than themselves
> 
>     * Encourage security not to care about winning and instead prioritize making rounds fun for more than themselves
> 
>     * Chase away people who only care about themselves in general, particularly those that want to make an inflexible plan and then hole up in one place largely alone for the entire shift.
> 
>     * Preferably all without negatively impacting the fun for people who aren't causing these problems.
> 
> 
> @Howluinb @Wilchenx @DerpiestBruh @Effemu Toss me some suggestions to work with that do any of the above and actively encourage players to follow rules

as i said, the funny choosing your own objectives from hrp servers like aurora, where you get a low amount of tcs early on, but you get either gimmicky objectives or normal full on ones that give you more in game rewards for the more you do

Maybe give a random choice between them, so that you can't just target someone you dislike every round

Incentivizing you to diversify your antag approach and be an antagonist to many different aspects of the station without needing to come up with a gimmick
(because. once again. gimmicks are NOT something most people can come up with on the spot at any time)

While still allowing for more gimmicky objectives, maybe even an in game interface to submit your own to the "syndicate" (admins) for which they can approve and give you extra tc in advance for.

This is one (1) idea.

It has a LOT of flaws and issues with it, but it'll certainly have more of an impact than whatever this pr does (as it does nothing, except maybe make antags do even less)


Please stop phrasing people who want to only do their objectives as "sweaty tryhards no RP" too, as i said, not everyone can find the inspiration for gimmicks every round, and I personally choose how i'll roleplay through my antag shift depending on the objectives i've acquired. Only steal objs ? time to try and approach things pacifically. Only sec targets ? Maybe a cosplay of a russian soldier going around with twenty mosins on him oughta be a fun time.

**Comment by DerpiestBruh** [comment]
Okay, jokes aside, the thing is

Tots should have objective updates, so that they are less encouraged to hide forever or act as if nothing happened? Might be worth to check out.


Unrelated to the PR, maybe it should be nice to give every job their own skills so everyone isn't a professional robot? Perhaps some sort of implant for antagonists so that they arent thrown away.

**Comment by Rukofamicom** [comment]
> Unrelated to the PR, maybe it should be nice to give every job their own skills

Already bountied this over a year ago. Was rejected unless skills meant newly abilities. The thought of preventing players from doing things they can currently do but should be leaving to people with specific jobs was apalling. 

Person who did the PR tried to revive it, opinion is still pretty much the same. If random schmoes can't operate a chemistry dispenser, how will they ever get their chems? *Asking a chemist? Preposterous!*

here's what remains of the PR if you want to take a look for yourself #3242
I kinda disowned it because the restrictions placed on it made the entire system completely arbitrary. Skills/skillchips would provide no meaningful benefits.

**Comment by Wilchenx** [comment]
> @Howluinb @Wilchenx @DerpiestBruh @Effemu Toss me some suggestions to work with that do any of the above and actively encourage players to follow rules

Allow people to rate antags at the end for meaningless internet points

**Comment by Archanial** [comment]
Objectives are meant to be completed.

By giving people greentext we indicate that this one particular objective has been completed and someone did his job.

It's not toxic, antagonists are meant to min max to some degree in order to effectively complete their objectives.

Not a fan of this without some bigger antagonist rework or at least design doc.

**Comment by Rukofamicom** [comment]
wait, why did you add balance/rebalance to this @Archanial? 
This does nothing to balance whatsoever, the only thing it changes is public information at round end.

**Comment by Patternseeker** [comment]
you will never be lifeweb

**Comment by ToasterBan** [comment]
I like the concept, but I feel like this will solve the bad player issue by removing the bad players 


good pr +1

**Comment by ToasterBan** [comment]
remove objective tracking, they don't really serve any point with this change no?

**Comment by Rukofamicom** [comment]
I'm not doing anything else with this PR until I get a green light from @PowerfulBacon or maintainers as a whole. Right now it looks like a dead idea despite being maintainer requested as "Something we wanted to do for the last six months" before I started on it. 

At least we're heading toward a more unified direction in the near future and this will hopefully be the last time something like this happens.

**Comment by PowerfulBacon** [comment]
I don't think this PR solves anything.
I find that most of my antagonist rounds end up being spent just hunting sec or getting some loot that you don't need for the objectives at all so that when you get into fights you can win them, before doing all the objectives on the side in passing or in the last 10 minutes.
If you think people that play like me are the problem, then nothing changes.
I dislike this style of play since its unfun for the security that die to it, however there is a problem that lies not just with antags and objectives but with the things it interacts with like security. Security will be so well equipped to deal with every single threat the second it jumps on them that they will never be caught off guard unless you attack them out of the blue and they never saw you there in the first place, making it so as an antagonist you can only ever lose by taking the RP route, and then this is topped off with none of security caring about self-preservation and that they have no reason to actually be scared of dying (especially since they have a good chance of being recovered 5 minutes after their death due to them being tracked most of the time by the warden).

**Comment by Rukofamicom** [comment]
> I find that most of my antagonist rounds end up being spent just hunting sec or getting some loot that you don't need for the objectives at all so that when you get into fights you can win them, before doing all the objectives on the side in passing or in the last 10 minutes.

So what you're saying is that objectives have little or no bearing on what you do as an antagonist, right? And yes I do have some issue with what you do, but it has to do with the vicious cycle of security wanting to force redtext in any way they can as well as antagonists wanting to force greentext to show off when this isn't the point of either role. 

Objectives are not engaging, or expected to be completed by staff. They only serve two mechanically good purposes on the server:
* Gatekeep antagonists from doing stationwide murderbone
* Give uncreative players who don't have a gimmick something to work toward. 

Negatively they cause:
* Antagonists (especially newer ones) to feel like they must complete them at any cost
* Security to want to force them to fail at any cost. You see it regularly with most (but not all) that they will go out of their way to ensure the player is removed from the round if they can find any reason to justify it. 

> I dislike this style of play since its unfun for the security that die to it, however there is a problem that lies not just with antags and objectives but with the things it interacts with like security. Security will be so well equipped to deal with every single threat the second it jumps on them that they will never be caught off guard unless you attack them out of the blue and they never saw you there in the first place, making it so as an antagonist you can only ever lose by taking the RP route, and then this is topped off with none of security caring about self-preservation and that they have no reason to actually be scared of dying (especially since they have a good chance of being recovered 5 minutes after their death due to them being tracked most of the time by the warden).

If you think the problem is that security is too well equipped to deal with every possible threat, then how about we take some of that capability away? There's a number of ways this can be achieved without totally disrupting game balance.

**Comment by Rukofamicom** [comment]
1) Is this PR the best solution to this problem? No it definitely could be better, like an entire overhaul of objectives to be more vague and/or gimmick oriented. Not like the current optional objectives which are almost universally awful.  Additionally the sec/antag dynamic needs to be totally changed. 
2) Does this PR move in the right direction? Yes it does in my opinion, but that's only agreeable if you think greentext should stop being a motivator for antagonists and redtext should stop being a motivator for sec.  
3) Does this PR take anything away from the game? No it does not, in fact it doesn't even edit or remove any current objectives which will still be assigned as they have been, just without the global notification of "HEY LOOK, THIS GUY FAILED".

**Comment by FortSumter** [comment]
Honestly getting rid of green text would give me more of a reason to be a shitter rather than less. My only goal as traitor would be to find a way to kill all of sec and command regardless of what my objectives were; every single person on the station if I got die a glorious death.
I barely have a reason not to do that now considering I get no beecoins for a green text anyway. 
There is no room to roleplay as a traitor when security is as powerful as it is. Once you do anything suspicious enough to be set to arrest your antag game is effectively over.
If you want to get traitors to roleplay, I like the suggestion of progressive objectives to sabotage the station or steal things like what someone else suggested. This makes them a constant active threat and would allow for a level of roleplay to complete the objectives.

**Comment by Rukofamicom** [comment]
Nah

**Pull request closed without merging**
