### PR TITLE
Medikit Rework

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
TL,DR: Most medikits have more meds and higher total healing, yet there's a greater diversity of meds which encourages doctors to think more about the optimal treatment for each patient. 

IV bags - We now have plastic IV bags that can be easily filled with custom chemicals, the bag can then be sealed for spill proofing and tamper resistance.

Empty spray bottles, blood packs and IV bags have also been added to the med lathe and a special suspicious spray bottle in the chemdrobe contraband section.

Chemistry changes and additions:
- Charcoal - has been changed to require ingestion, since injecting or externally applying an insoluble granular substance makes no sense.
- Probital - a brute healer that when taken by mouth additionally turns nutriment in your body into healing peptides for some time, makes the chef feel appreciated and allows for reagent efficient self healing.
- Hercuri - a burn healer that also helps you cool down, chills and extinguishes a burning patient if applied with a spray bottle.
- Syriniver - a mixable toxin healer with a high healing potential especially if applied using an IV drip, but can be harmful if the patient has poor liver health.

_Note: comparison to tg meds:_
Despite having the same names as some /tg/ meds these don't have the strong downsides that make them basically poisons, all that's similar is the unique application method. Also there are more meds per medikit so the kits don't feel gimped. 

NanoMed vending machine contents are unchanged, but the medbay storage kits have new contents:
- Burn kit: 4 burn patches, 2 hercuri sprays and 1 oxandrolone injector.
- Brute kit: 3 brute patches, a bottle of probital pills, 1 salicyclic acid medipen and gauze.
- Toxin kit: A bottle of charcoal pills, a bottle of potassium iodide pills, 3 syringes of syriniver and a pentetic acid medipen.
- Oxygen kit: 3 syringes of perfluorodecalin, 1 dexalin medipen, 1 salbutamol medipen, 2 epipens and a bottle of iron pills.
- First-aid kit: 2 stacks of sutures, 2 stacks of regenerative mesh and 1 epipen. 

I may have overdone it by adding too much meds but I predict there will still be some downvoters just because it's a change, we'll see though. 

Sutures and regen mesh: 
They have a larger stack size, heal a little per application and auto repeat if there are stacks left however application time has increased. These new medical devices replace maint first-aid meds as well.

Doctors starting medikit has a new sprite, slightly increased capacity and starts with the basics needed for Tend Wounds surgery (drapes, scalpel, hemostat).

Additionally the new spray bottles and a couple of the old ones have new sprites, and new medipens have sprites also.

## Why It's Good For The Game
Tend wounds should be the go-to for treatment by medical doctors, having the tools from roundstart helps with that.

A variety of meds in each kit encourages doctors to think more about the right type of med for each patient rather than just slap on whatever is inside 

Medical devices are more efficient for treating smaller injuries because of the larger stack size, where before you might want to save them until you got more hurt. Bruise packs/ointment having instant big healing also was OP, this scales it to the same levels as other medikits which takes a bit longer to heal the same amount.

## Changelog
:cl:
add: Medical staff now spawns with a first-aid kit with increased capacity and basic surgery tools
add: Regenerative mesh, a new burn healing medical device.
add: Sutures, a new brute healing medical device.
add: Medicated sutures, a new medical device created by a chemical reaction.
add: Cellulose reagent, used to make the new sutures, can be heated to produce carbon.
tweak: Most bruise packs and ointments have been replaced with the new devices.
add: Adds 4 new pill types, 4 new pill bottle types, a spray type, three medipen types & four syringe types.
tweak: Changed burn, brute, oxygen, toxin and first-aid kit contents.
add: Probital - a new hearty brute medicine.
add: Hercuri - a new chilly burn medicine.
add: Syriniver - a new liquid tox medicine.
add: IV medicine bags, blood packs amd spray bottles are available in the medlathe.
add: Suspicious spray bottles have been added to the ChemDrobe contraband compartment.
imageadd: Added sprites for spray bottles, IV bags and medipens.
code: trans_to can now react the reagents if you want.
/:cl:

Ports:
https://github.com/tgstation/tgstation/pull/44531
https://github.com/tgstation/tgstation/pull/45216

### CODE REVIEW

**Comment by zeskorion** [comment]
gah, more of this piggyback stuff... i'll put it to vote, with a description

**Comment by VictorVow** [comment]
Why with a description?

**Comment by VictorVow** [comment]
Travis I'll fix you.....later

**Comment by mehmetipekpatates** [comment]
why yes literally nobody likes the medbay reworks in tg so let's follow their example

**Comment by St0rmC4st3r** [comment]
Can you.... Bloody atomize it?!

**Comment by triplezeta** [comment]
bruh at least add the not awful unnerfed versions from the original PR

**Comment by qwertyquerty** [comment]
Conflicts and vote failed

**Pull request closed without merging**
