### PR TITLE
Lings can spend chems while in regen coma to unhusk

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Lings can spend <s>30</s> 100 chems when husked to unhusk. Price can be changed.

## Why It's Good For The Game

Husking lings should never be a valid option. The point of lings was to not die/be really hard to kill. They're really easy to kill as is. No need to add "set them on fire, electrify, or just deal a lot of burn damage to render them unrevivavble".

Last resort/headcrab is not a solution and is a pretty bad ability on its own.

## Changelog
:cl:
add: lings can now unhusk with regen coma
/:cl:

### CODE REVIEW

**Comment by TotallyNotChief** [comment]
lol

**Comment by PowerfulBacon** [comment]
whole point of lings is to be hard to kill because they are hard to catch / work out who it is (although most lings suck at doing this) not be hard to destroy

**Comment by eeSPee** [comment]
Hmm. Fair enough.

But I still don't like the idea of permanently destroying a ling by husking them. Bodies are so easy to husk.

What if this stays in, but it's ridiculously expensive? Like 100 total DNA. So husking lings disables them a long while.

**Comment by AnjelicaChaykovsky** [comment]
They were weak to fire in the movie  so it's silly to make them some kind of unkillable machine for little reason.
Their goal was to absorb and fit in with people, on bee they are just murderhobos in maints

**Comment by Isy232** [comment]
> They were weak to fire in the movie so it's silly to make them some kind of unkillable machine for little reason.
> Their goal was to absorb and fit in with people, on bee they are just murderhobos in maints

Thats because killing people is easier than fitting in with people.

If anything lings need a buff to their stealthy abilities.

**Comment by eeSPee** [comment]
Remove CBZ from the game.

**Comment by eeSPee** [comment]
Closing this PR. Maybe in the future it will be meta or someone comes up with a better application.

**Pull request closed without merging**
