### PR TITLE
Medibot Buff

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
Gave the Chemist and their preloaded fridges a TriaMed bag with 40u Bicaridine, 40u Kelotane and 20u Epi.

Medibots now also start with a TriaMed bag.

Adds a Medibot to each Medbay which is missing one.

## Why It's Good For The Game
Gives medibots some much needed attention as currently they are basically just set dressing.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

Kind of blew shit up. lol

image

image

image

</details>

## Changelog
:cl:
add: TriaMed bag (40u Bicaridine, 40u Kelotane, 20u Epi).
balance: Chemists start with a TriaMed bag and also one in their preloaded fridges.
balance: Replaces all Medbay Medibots with filled (TriaMed) variants.
fix: [Echo, Box, Corg, Fland] Adds a Medibot to Medbay.
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
Apparently there was already a bicaritane beaker, but I think changing it to a bag is better as that's most likely what would be used by a chemist.

**Comment by Rukofamicom** [comment]
would be nice if the spawned medibots still also had epi in them so they're better equipped to deal with crit patients too. Even if it's not an even split, a little bit of epi will help a lot.

**Comment by Rukofamicom** [comment]
> balance: Chemists start with a 100u Tricordrazine bag.
balance: Roboticist start with a 100u bicaridine bag.
balance: Spawned Medibot start with a 100u bicaritane (50u bicaridine, 50u kelotane) bag now.

Not blocking as maintainer, but I'd really rather roboticists not start with a random chemical bag, even if producing medbots is on them. 

May I instead suggest that chem fridges contain a bag of 80/20 Tricordrazine/Epi, and this also be the mix that the bots start with? I would really like the bots to retain epi because of how useful it is for players in crit. Tricordrazine still backs it up with a decent punch too.

**Comment by MarkusLarsson421** [comment]
Sounds good, Roboticists can simply fetch it on round start if they so desire. I will only add it to the filled Chemistry fridge variant.

**Comment by Therealdoooc213** [comment]
> Gives the Curator a 10u meth pill in the library on Echo and Rad for the funny.
The greybull in rad gives shock protection, Why on echo?

**Comment by MarkusLarsson421** [comment]
> The greybull in rad gives shock protection, Why on echo?

No, no, it's not for anything practical. It's just what I imagine someone playing this role really could need. Mostly because their libraries are literally rundown like hell and if they aren't addicted to meth, they certainly will be after taking the pill.

**Review by Rukofamicom — APPROVED** [review]

**Comment by ColonelOrion** [comment]
> 80/20 Tricordrazine/Epi, and this also be the mix that the bots start with?

Common Oozeling L
(Do we want this PR to negatively affect oozelings?)

**Comment by Rukofamicom** [comment]
> (Do we want this PR to negatively affect oozelings?)

They're already stocked with epi which is incredibly toxic to them.

**Comment by MarkusLarsson421** [comment]
Oh...

**Comment by Rukofamicom** [comment]
Secondary approval on the balance change received from @PowerfulBacon via discord. 

Further buffs, or even a reversion of swapping to a reagent system may be in the future of medbots since the nerf ended up being so strong they are largely ignored.

**Pull request merged**
