### PR TITLE
Implements Captain's spare bridge safe from TGStation

### PR DESCRIPTION
**Pull request by bloons3**
https://github.com/tgstation/tgstation/pull/56910
https://github.com/tgstation/tgstation/pull/57460

## Changelog
:cl:
add: Adds a safe in the Bridge for the captain's spare. It cannot be destroyed, except by explosion or acid. Heads of Staff are given the code to it at the start of the round.
add: Adds a chain of succession enforced via code for Acting Captain
remove: Removes the captain's spare from the locker
/:cl:

### CODE REVIEW

**Comment by Mat05usz** [comment]
So does it close #3832? And if yes, what about this #3838?

**Comment by bloons3** [comment]
> So does it close #3832? And if yes, what about this #3838?

Archanial was first to market, so their PR will satisfy the bounty.
I am doing this out of personal interest.

**Comment by leestriter** [comment]
What's the difference between this version and Archanial's version?

**Comment by bloons3** [comment]
> What's the difference between this version and Archanial's version?

Didn't realize that they'd updated it. These would have almost identical functionality in that case.

**Comment by jupyterkat** [comment]
make the lock dual custody, as like you need more than one code from multiple staff to open?

**Comment by leestriter** [comment]
> make the lock dual custody, as like you need more than one code from multiple staff to open?

Then it won't work with only one head and requires two heads not doing their actual intended jobs, I think its best it doesn't need two heads. We want it to be easier for a head to get the spare then a tider, while still leaving it possible for tiders in the absence of any heads.

**Comment by jupyterkat** [comment]
It makes it so staffs have to vote for who gets the ID, not two staffs not doing their jobs, all they have to do is enter a code. Tiders can have an option of trying to crack the safe with a stethoscope or a multitool instead

**Comment by leestriter** [comment]
> It makes it so staffs have to vote for who gets the ID, not two staffs not doing their jobs, all they have to do is enter a code.

They are intended as is to either vote or default to CoC. Tiders will need to use acid or explosives.

**Comment by jupyterkat** [comment]
90% of the time tops of chains will get it without voting anyways. This gives other staffs at least a chance to get it.

**Comment by PowerfulBacon** [comment]
Failing checks, stale

**Comment by bloons3** [comment]
Favor https://github.com/BeeStation/BeeStation-Hornet/pull/3838

**Pull request closed without merging**
