### PR TITLE
the noob body bag, the greatest item ever made

### PR DESCRIPTION
**Pull request by boolsrealm**
hey guys. god came down from the heavens above in a massive beam of glowing, amazing light and told me to make this. you'll understand why after giving this bad boy a read

## About The Pull Request

removes syndie balloon

adds noob body bag, it is in the "pointless badassery" category

## Why It's Good For The Game

its funny

## Changelog
:cl:
add: the syndicate body bag, it's a normal body bag with the word "noob" drawn on it in MS paint. street name is the noob body bag. made to demoralize your targets, costs 20 tc and makes farting noises because it's extra demoralizing. 

del: the syndicate balloon, as the noob body bag is a clear upgrade
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
> removes syndie balloon

Why?

**Comment by pixelman77** [comment]
Don't remove the balloon, instead pack them in one bundle or leave the balloon be

**Comment by ike709** [comment]
Don't remove the balloon.

**Comment by boolsrealm** [comment]
> > removes syndie balloon
> 
> Why?

ok bro, if you really want it that bad we can keep it, just hold on

**Comment by Mick1299** [comment]
> ok bro, if you really want it that bad we can keep it, just hold on

The issue here is you tried to sneakily remove it for seemingly no reason.

**Comment by PowerfulBacon** [comment]
> > ok bro, if you really want it that bad we can keep it, just hold on
> 
> The issue here is you tried to sneakily remove it for seemingly no reason.

I wouldnt say it was a secret removal, just no reason to remove it. Also they failed to account for the space ruins and the other places this is used in the game

**Pull request closed without merging**
