### PR TITLE
Dynamic: Block hivemind/traitors/heretics combo

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

An extension of https://github.com/BeeStation/BeeStation-Hornet/pull/7658
Hivemind was merged slightly after my PR so it wasn't included.

## Why It's Good For The Game

Hivemind assimilation onto a traitor can hijack the round and create weird interactions, see original PR for more details.

## Testing Photographs and Procedure

N/A

## Changelog
:cl:
balance: Dynamic: Traitors, Changelings, and Heretics can no longer spawn alongside hivemind (assimilation).
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Hivemind should be a minor mode if it wasn't for the interaction with 2 hivemind ascended vessels potentially having other vessels as their targets. Its not a round hijacking antag like the others

**Comment by Penwin0** [comment]
Could probably just exclude antagonists from being controlled by hive hosts

**Comment by PowerfulBacon** [comment]
> Could probably just exclude antagonists from being controlled by hive hosts

I think that would be the best solution, hivemind aren't powerful/impactful enough to be a major mode and it makes sense since most antagonists have the mental resiliance/training to resist the effects of mindshields implying they could probably resist the effects of hivemind control.

**Comment by Fronsis** [comment]
> > Could probably just exclude antagonists from being controlled by hive hosts
> 
> I think that would be the best solution, hivemind aren't powerful/impactful enough to be a major mode and it makes sense since most antagonists have the mental resiliance/training to resist the effects of mindshields implying they could probably resist the effects of hivemind control.

Well, Hiveminds have a spell exclusively to by-pass mindshields so they can add command/sec to their hive so technically you could argue that a strong hivemind (since that power is unlocked very late) can corrupt an agent, but yeah leaving that aside it kinda makes sense what OP is proposing

**Comment by itsmeow** [comment]
I think just making it hard block traitors is a better solution

**Comment by PowerfulBacon** [comment]
Its not the better solution, but its the easier solution, so maybe its the best for worth/effort

**Review by PowerfulBacon — APPROVED** [review]

**Review by Archanial — APPROVED** [review]
not a fan,  but since revs, clock etc are blocked already let's stay consistent

**Pull request merged**
