### PR TITLE
Ports Tail Entwining from /TG/ Station

### PR DESCRIPTION
**Pull request by amidoingitright**
(Original PR)
https://github.com/tgstation/tgstation/pull/54991
(Technically a port of a port but potato potato)
## About The Pull Request

If you can pull on Felinid/Lizard tails, why cant you then wrap them around the people you hate?

## Why It's Good For The Game

More options of RP for all tailed creatures

## Changelog
:cl:
add: Tail Entwining, just aim groin and passive grab them
/:cl:

I just want to set the world on fire

### CODE REVIEW

**Comment by BrumalLake** [comment]
i think you misunderstood, this is an erp action where you wrap your tail around someone else's tail
not the ability to wrap someone in your tail

**Comment by amidoingitright** [comment]
> i think you misunderstood, this is a erp action where you wrap your tail around someone else's tail
> not the ability to wrap someone in your tail

i know exactly what i'm doing

**Comment by Sinestia** [comment]
yourenotdoingitright

**Comment by amidoingitright** [comment]
> yourenotdoingitright

i'm doing it **Very right**

**Comment by r1ks-iwnl** [comment]
This was already ported and closed twice

**Comment by amidoingitright** [comment]
> This was already ported and closed twice

i have my methods.
The main method being having this actually work.

**Comment by AnCopper** [comment]
Hey, I've seen this one before.

**Comment by amidoingitright** [comment]
> Hey, I've seen this one before.

sometimes i wanna go back to the future

**Review by Kapu1178 — COMMENTED** [review]
This is bad code, and completely removes my tail grabbing PR.
steal the refactor part of #4160 and adjust accordingly

**Pull request closed without merging**
