### PR TITLE
Removes the random resin floors and used eggs in Corg.

### PR DESCRIPTION
**Pull request by AnCopper**
## About The Pull Request

Removes the random resin floors and used eggs in Corg.

## Why It's Good For The Game

This causes more trouble than it's worth it.

## Changelog
:cl:
del: Removed the Xeno maintenance room on Corg.
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
Trouble as in, people are thinking there are xenos on the station?

**Comment by AnCopper** [comment]
> Trouble as in, people are thinking there are xenos on the station?

Yeah.

**Comment by ghost** [comment]
False positives are a good thing

**Comment by ghost** [comment]
neutering the chaos part of SS13 😔

**Comment by francinum** [comment]
🔑 

False positives and bad information are part of the game. No.

**Comment by PowerfulBacon** [comment]
I am in favour of keeping them

**Pull request closed without merging**
