### PR TITLE
Remove Station Toxin Test Site

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
Removes toxins test site from the station side. Scientists has multiple options of delivering the payload. They can ask Command or an AI to teleport it directly with the beacon there, they can ask a Miner to deliver it for them or they can head down there themselves using the Science shuttle if it is available.

Test sites has been deleted except on Kilo and Echo where it remains for variety and because it has actual rocks to blow up, not just empty space. If desired, it can be removed too.

## Why It's Good For The Game
It is done once and then forgotten about. It doesn't take much room but think it's better to encourage Science to coordinate with the miners to deliver the payload (and maybe blow it up while it is in their hands). 😉 

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

It is entirely possible to get a maxcap whilst on lavaland.

33% tritium, 66% oxygen, 43K.
100% plasma, roughly 260 000K I think.
Detonated on the beacon on Lavaland. Don't forget to fix the power so that the Tachyon can record the data.

image

Box

image

Corg

image

Delta

image

Fland

image

Meta

image

Rad

image

</details>

## Changelog
:cl:
del: [Meta, Box, Corg, Delta, Fland, Rad] Removed Toxins Test site.
balance: Moved Toxins Test Site down to Lavaland.
tweak: Moved test site materials down to lavaland.
tweak: [Lavaland] Added station-bounced radio next to tachyon-doppler research array.
del: [Kilo] Removed extra air alarm in toxins.
del: [Corg] Removed the two spare RD hardsuits.
tweak: [Lavaland] Added RD hardsuit to their office on Lavaland.
balance: [Lavaland] Expanded high resource rock around the test site.
tweak: [Meta, Delta, Box, Fland, Rad, Corg] Added toxins telescreen in toxin rooms.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I don't see the reason for this change. It doesn't really make sense to just convert the room to maintenance because it is only needed once with the alternative being using the teleporter to teleport the bomb to the target location. Don't get me wrong, inter-department cooperation is good, but removing the departments only effective way of doing something doesn't improve inter-department cooperation.

**Comment by MarkusLarsson421** [comment]
I forgot to mention it, but the RDs hardsuit includes a tachyon doppler array. Meaning they can use that to test the bomb on station. Sometimes alone depending on the position of the RDs hardsuit. Some maps also still include the launcher itself in case someone wishes to use it for a gimmick or actual bomb launch. It would be more difficult, but still possible.

**Comment by Therealdoooc213** [comment]
This seems really unnecessary and just makes toxins more tedious than it already is.

**Comment by Nakalon** [comment]
Why not instead of removing the room you turn the room into a teleporter to the lavaland site?

**Comment by MarkusLarsson421** [comment]
> Why not instead of removing the room you turn the room into a teleporter to the lavaland site?

I mean... a functioning teleport like the one AI and Command has? Feels a bit iffy. Maybe if it was only for items, but that'd increase the scope of this. Maybe.

**Comment by MarkusLarsson421** [comment]
Seems to not be going anywhere, I will perhaps reopen it in the future.

**Pull request closed without merging**
