### PR TITLE
Remove Wallshoves, Disarm counter

### PR DESCRIPTION
**Pull request by Rukofamicom**
## About The Pull Request
Removes wallshoving as a cheap and easy way to immediately flip the tide of battle. 
Re-introduces disarm intent as a way to cause someone to drop items without factoring direct positioning into the mix. 

## Why It's Good For The Game
It makes those who have dangerous equipment more of a threat and discourages unarmed validhunters from challenging dangerous people. It mechanically encourages unarmed players to act believably and in accordance with the server's rules. 

## Testing Photographs and Procedure

I have not had time to meaningfully test yet. I covered the basic initial testing but I have run out of time for the moment and am more interested in getting immediate feedback on what will be a very controversial change. 

## Changelog
:cl:
add: Disarm intent can now force someone to drop their held item if performed three times in five seconds.
del: Shoving someone into a wall will no longer produce an immediate knockdown and item drop. 
/:cl:

### CODE REVIEW

**Comment by mcmeiler** [comment]
This has the same issues as #6863. Encourages validhunting as shoving someone 3 times produces, for example ,a highly dangerous individual suddenly dropping their highly dangerous weapon and losing it to the unarmed man who clicked them 3 times.

**Comment by Mat05usz** [comment]
> It makes those who have dangerous equipment more of a threat and discourages unarmed validhunters from challenging dangerous people

It gives an artificial advantage to people who have skill issues, causing them to think much less during combat.

> It mechanically encourages unarmed players to act believably and in accordance with the server's rules.

So now you want to be coding also according to rules? That's dumb, because rules are there to stop people from using certain aspects of code/game in situations that do not warrant it, not to 'force' coders to remove mechanics. Maybe make grenades unusable by non antags, because 'why the hell would they anyways', right?

**Comment by PowerfulBacon** [comment]
Being able to click someone 3 times to instantly win any fight is bad. If you think something like dropping items on shove is bad then why not just remove that instead of replacing it with something even worse?
Basically a duplicate of #6863, closing for the same reasons.

**Comment by PowerfulBacon** [comment]
Actually, I'll keep it open for at least 24 hours or another maintainer closes it otherwise its a bit unfair.

**Comment by VictorVow** [comment]
I think the whole point of the PR is to gather feedback on how should shoves be, so shouldn't be immediately closed. I've suggested two tweaks already on the forum so that RNG isn't the only factor (ie positioning and stats). Others will probably suggest different changes.

**Comment by Archanial** [comment]
🔑

**Pull request closed without merging**
