### PR TITLE
Troublemakers - Midround Space Assholes

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Troublemakers, a idea inspired by goon's miscreants, that gives them a objective that is not just roleplay, but can actually be completed.

Troublemakers are not proper antagonists, in the sense that they cannot sabotage the station and attack security/witnesses, but they are exempt from the rules 'Be nice to eachother' or 'Follow SOP'. They have a goal, and can break any laws to complete it. 

Possible objectives are:
* Steal Ian (have a pet item for Ian on yourself)
* Steal Renault
* Steal Llamar
* Steal Captain's Flask
* Have [an absurd amount of credits] on yourself at the end of your shift
* Have the main AI purged of laws at the end of the shift
* Escape the station with [number] strange objects
* Escape with another identity
* Make sure there are n corpses in hallway
* Steal Runtime
* Make it away with an absurd amount of units of a certain drug (space drugs, meth, etc)
* Escape with an absurd amount of flesh organs
* Make a newsletter to compete with the curator
* Fake prophet (basically, you gain the rank of high priest and need to get away with X everburning candles, or become a robot)
* Make sure there are no more than X amount of functional cameras at the end of the shift (disabling them works)
* Escape with a fireaxe
* ~~Steal and escape with a stunbaton~~
* ~~Steal and escape with a disabler~~
* ~~Steal and escape with a sechud~~
* Make sure there are no prisoners in ~~brig~~ perma at the end of the shift
* Make sure there are XX number of living monkeys at the end of the shift (on the station)
* Steal a department prolathe board
* Steal someone's heirloom

## Why It's Good For The Game

Adds a little spice to the rounds and makes the game a little less boring.

## Progress

* [ ] Objectives
* [ ] Antag datum?
* [ ] Random antag event
* [ ] Admin interactions

## Changelog
:cl:
add: TODO changelog
/:cl:

### CODE REVIEW

**Comment by eeSPee** [comment]
I clicked close by mistake with my fat fingers...

**Comment by super12pl** [comment]
> I clicked close by mistake with my fat fingers...

Why make clone PR instead of reopening the original?

**Comment by Sinestia** [comment]
> 
> 
> > I clicked close by mistake with my fat fingers...
> 
> Why make clone PR instead of reopening the original?

This, you can reopen your own.

You just can't if someone else closes it

**Comment by Sinestia** [comment]
Anyways, worth mentioning that this doesn't fit the spirit of miscreants at all.

Miscreant objectives aren't about winning, they're basically pre-packaged gimmicks that you play the round with, very very few of them are as simple as "Do X, X is now done."

 Most of these are just dumb minor antag objectives. 

 Like the "steal X pet" objectives under a system taking proper inspiration would be something like this IMO

> "Create a zoo using the pets of the station as centerpieces"

 You have a reason to take ian, but it's a wide gameplay opportunity which engages multiple people. 

Most of these can be rewritten in similar ways, e.g. "Protect the freedom of silicons" which again, is round-long and creates opportunities for fun should you choose to pursue it. (That one could probably work with our silicon policy, but eeh, probably wouldn't make it in.)

**Pull request closed without merging**
