### PR TITLE
Pipebow balance

### PR DESCRIPTION
**Pull request by Flakkyboo**
## About The Pull Request
Reduces the material costs to make a pipe bow and reduces the time to make silk from cotton.
 
## Why It's Good For The Game

Currently you need 320 cotton to make the 80 cloth needed to make a pipebow.

Ive reduced the cost of the pipebow recipe making it so you need a total of 32 cloth or 128 cotton to make the silk necessary to craft the pipebow.

making it so a determined botanist or assistant can make the bow without investing the entire round 

## Changelog
:cl:
tweak: Reduced loom time for cloth to silk.
balance: Reduced Material cost and buildtime for the pipebow making it easier to make.
imageadd: edited unloaded bow sprites to make reloading easier by giving you more valid space to click
/:cl:

### CODE REVIEW

**Comment by Flakkyboo** [comment]
once again travis causes errors i dont have a hand in

**Comment by Ohagi-Chan** [comment]
Rather than harvesting cotton, wouldn't a stationside player just print cloth from the biogenerator?

**Comment by Mick1299** [comment]
You can also use a sharp object, like a knife or glass shard, to cut bed sheets into cloth

**Comment by Flakkyboo** [comment]
> 
> 
> Rather than harvesting cotton, wouldn't a stationside player just print cloth from the biogenerator?

that would be a viable option for someone yes but even then its still a significant time investment compared to other improvised weapons stationside. ashies have the bone bow recipe they can use which i think is fine in terms of material cost

**Comment by Flakkyboo** [comment]
> 
> 
> You can also use a sharp object, like a knife or glass shard, to cut bed sheets into cloth

I've had someone do this rather than use cotton and they could only get 6 silkstrings using bedsheets, linen cart and medkit materials for cloth. that result was the original catalyst for this change

**Comment by Mick1299** [comment]
Had a go at making it myself, you're right that the material cost is far too high. I had to scavaneg every bedsheet and bandage from med and perma to make a single bowl and more than 1 arrow. 

The crafting time for the bow itself it also far too high, it's like 40 seconds

**Comment by Flakkyboo** [comment]
> 
> 
> Had a go at making it myself, you're right that the material cost is far too high. I had to scavaneg every bedsheet and bandage from med and perma to make a single bowl and more than 1 arrow.
> 
> The crafting time for the bow itself it also far too high, it's like 40 seconds

yeah ive also reduced the time its around the same time to make as an improvised shotgun now.
the original recipes for the bows are 1/1 from the original pr but ive been observing lots of instances of people trying to make it before making the changes

**Comment by Flakkyboo** [comment]
> 
> 
> > Had a go at making it myself, you're right that the material cost is far too high. I had to scavaneg every bedsheet and bandage from med and perma to make a single bowl and more than 1 arrow.
> > The crafting time for the bow itself it also far too high, it's like 40 seconds
> 
> yeah ive also reduced the time its faster to make than an improvised shotgun now.
> the original recipes for the bows are 1/1 from the original pr but ive been observing lots of instances of people trying to make it before deciding on reducing the amount

**Review by zeskorion — APPROVED** [review]

**Pull request merged**
