### PR TITLE
makes the firefighter radproof

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

tritium fires, fusion fires fighter

## Why It's Good For The Game

more use for the ol firefighter

## Changelog
:cl:
balance: firefighters are now radproof
/:cl:

### CODE REVIEW

**Comment by williamcll** [comment]
yes please

**Review by utilbird — APPROVED** [review]

**Comment by St0rmC4st3r** [comment]
Maybe better make it an optional upgrade?

**Comment by DatBoiTim** [comment]
Ah yes, easy to obtain radproofing. 

These suits already do a lot, so I think a buff like this is already unnecessary.

Additionally, part of the danger of trit/fusion fires is the rads, making those an immediate ignore for people who aren't trained to manage atmos fires is absolutely unneeded.

As a final note: Modern Fire PPE(like one finds in lockers) is not resistant to the kind of radiation that these fires would emit.

As for the rad suits in engineering, probably some futuristic version of the Demron radiation resistant fabric.

**Comment by jupyterkat** [comment]
> Ah yes, easy to obtain radproofing.
> 
> These suits already do a lot, so I think a buff like this is already unnecessary.
> 
> Additionally, part of the danger of trit/fusion fires is the rads, making those an immediate ignore for people who aren't trained to manage atmos fires is absolutely unneeded.
> 
> As a final note: Modern Fire PPE(like one finds in lockers) is not resistant to the kind of radiation that these fires would emit.
> 
> As for the rad suits in engineering, probably some futuristic version of the Demron radiation resistant fabric.

firefighters are slow as shit, and isn’t meant for combat at all. plus you have to convince a roboticist to build it at all. what do you mean the only mech that can walk on lava and withstand temperatures hotter than the sun can’t take a few rad counts. this adds a way for other peeps to clean up the mess after some bozo pumped fusion into supply pipes and not just the ce who can fix it

**Comment by DatBoiTim** [comment]
> > Ah yes, easy to obtain radproofing.
> 
> > 
> 
> > These suits already do a lot, so I think a buff like this is already unnecessary.
> 
> > 
> 
> > Additionally, part of the danger of trit/fusion fires is the rads, making those an immediate ignore for people who aren't trained to manage atmos fires is absolutely unneeded.
> 
> > 
> 
> > As a final note: Modern Fire PPE(like one finds in lockers) is not resistant to the kind of radiation that these fires would emit.
> 
> > 
> 
> > As for the rad suits in engineering, probably some futuristic version of the Demron radiation resistant fabric.
> 
> 
> 
> firefighters are slow as shit, and isn’t meant for combat at all. plus you have to convince a roboticist to build it at all. what do you mean the only mech that can walk on lava and withstand temperatures hotter than the sun can’t take a few rad counts. this adds a way for other peeps to clean up the mess after some bozo pumped fusion into supply pipes and not just the ce who can fix it

Oh you mean the mech? Fuck I thought this was the locker firesuits that literally anyone can just wear.

**Comment by jupyterkat** [comment]
> > > Ah yes, easy to obtain radproofing.
> > 
> > 
> > > 
> > 
> > 
> > > These suits already do a lot, so I think a buff like this is already unnecessary.
> > 
> > 
> > > 
> > 
> > 
> > > Additionally, part of the danger of trit/fusion fires is the rads, making those an immediate ignore for people who aren't trained to manage atmos fires is absolutely unneeded.
> > 
> > 
> > > 
> > 
> > 
> > > As a final note: Modern Fire PPE(like one finds in lockers) is not resistant to the kind of radiation that these fires would emit.
> > 
> > 
> > > 
> > 
> > 
> > > As for the rad suits in engineering, probably some futuristic version of the Demron radiation resistant fabric.
> > 
> > 
> > firefighters are slow as shit, and isn’t meant for combat at all. plus you have to convince a roboticist to build it at all. what do you mean the only mech that can walk on lava and withstand temperatures hotter than the sun can’t take a few rad counts. this adds a way for other peeps to clean up the mess after some bozo pumped fusion into supply pipes and not just the ce who can fix it
> 
> Oh you mean the mech? Fuck I thought this was the locker firesuits that literally anyone can just wear.

lmao it’s the mech dum dum

**Comment by DatBoiTim** [comment]
> > > > Ah yes, easy to obtain radproofing.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > These suits already do a lot, so I think a buff like this is already unnecessary.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Additionally, part of the danger of trit/fusion fires is the rads, making those an immediate ignore for people who aren't trained to manage atmos fires is absolutely unneeded.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > As a final note: Modern Fire PPE(like one finds in lockers) is not resistant to the kind of radiation that these fires would emit.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > As for the rad suits in engineering, probably some futuristic version of the Demron radiation resistant fabric.
> 
> > > 
> 
> > > 
> 
> > > firefighters are slow as shit, and isn’t meant for combat at all. plus you have to convince a roboticist to build it at all. what do you mean the only mech that can walk on lava and withstand temperatures hotter than the sun can’t take a few rad counts. this adds a way for other peeps to clean up the mess after some bozo pumped fusion into supply pipes and not just the ce who can fix it
> 
> > 
> 
> > Oh you mean the mech? Fuck I thought this was the locker firesuits that literally anyone can just wear.
> 
> 
> 
> lmao it’s the mech dum dum

To be fair it rarely gets made so when I see firefighting shit I assume the locker stuff.

Yeah I have no issues giving a thing that requires cooperation to even acquire stuff to allow more protection for something it may well encounter filling its niche

**Comment by francinum** [comment]
The firefighter ripley is a sluggish box that really has no special purpose at the moment.

This gives it a rather niche one that nothing besides extremely limited hardsuits really fulfil.

**Pull request merged**
