### PR TITLE
Adds a variable in spellbook that can bypass a threat lock for rituals/spell compatible

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
Adds a variable in spellbook that can bypass a threat lock for rituals/spell compatible

if you set `bypass_lock` TRUE, You'll be capable of casting the crazy rituals.

## Why It's Good For The Game
Rituals are actually not possible to happen. Wizards will need to beg admeme so that it can actually happen.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image

</details>

## Changelog
:cl:
add: spell book now has bypass_lock variable. Admin can set it TRUE to bypass dynamic threat lock for some rituals.
/:cl:

### CODE REVIEW

**Comment by JixS4v** [comment]
I don't see why this is a thing. Wizards are a high threat antag, rituals are supposed to mess with people, why would they need approval? It might mess with someone's wizard round to not be able to cast a ritual if no admins are online.

**Comment by zeskorion** [comment]
nah, leave them permalocked, dont trust admins with this

**Comment by EvilDragonfiend** [comment]
> nah, leave them permalocked, dont trust admins with this

they can actually bypass it by increasing the threat to the required value already.

**Comment by JixS4v** [comment]
I don't think it's a matter of trusting admins but of having your gimmick ruined because you rolled wiz with no admins online

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
