### PR TITLE
Bamboo fixes and improvements

### PR DESCRIPTION
**Pull request by SomeAngryMiner**
## About The Pull Request

Probably a handful of yall saw the unused bamboo assets inside some parts of the code, this is an unfinished /tg/ port, so i went ahead and completed it, adding a few extras:

-Bamboo is a mutation from sugarcane, you can also get it from the exotic seeds crate.

-Bamboo behaves similarly to a towercap, with a few different uses. It also has perennial crops, if you find this information useful.

-You can make Punji stick traps from bamboo, these work as makeshift traps that stun and harm anyone who walks over them, unsurprisingly.

-You can make a bamboo spear from a hefty amount of bamboo, for the botnis guards.

-Bamboo can be used to make a blowgun, a makeshift syrine gun that takes a windup time to shoot and deals a bit of stamina/oxygen damage when used.

-To pair the blowgun, you can make a bamboo syringe that can only hold a single unit of reagents, for the cheap price of 5 cuttings.

the beautiful sprites are made by ThatGuyThere03, cheers to them.

## Why It's Good For The Game

finishing unfinished things good.

## Changelog
:cl:
add: Bamboo! make blowguns, spears and punji traps from this!
/:cl:

### CODE REVIEW

**Review by MarkSuckerberg — APPROVED** [review]
Seems good to me.

**Comment by hackerjsimon** [comment]
Increase units on the syringe to like 10-units.

**Comment by MarkSuckerberg** [comment]
I think 5 at most would be reasonable.

**Comment by SomeAngryMiner** [comment]
i guess 5 is enough.

**Comment by qwertyquerty** [comment]
Fix the icon conflictos

**Comment by SomeAngryMiner** [comment]
alright.

**Comment by SomeAngryMiner** [comment]
i resolved the conflicts, but now map diff says its bad?

**Comment by SomeAngryMiner** [comment]
i have 0 idea why this is happening, i used the new DMIs from master and added the new items,  yet the conflicts still pop up @qwertyquerty

**Comment by qwertyquerty** [comment]
You need to merge master into your branch.

**Comment by SomeAngryMiner** [comment]
alright, ill just remake the PR branch.

**Pull request closed without merging**
