### PR TITLE
Departmental Intercoms

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
Adds department specific and non-station intercoms. This includes NO mapping changes. Can be used whilst telecoms is down but can not have its frequency changed.

## Why It's Good For The Game
Allows people to talk over coms for their given department even if telecoms is down. 

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image

image

image

image

</details>

## Changelog
:cl:
add: Adds department specific intercoms (including non-station intercoms).
/:cl:

### CODE REVIEW

**Comment by kiekatz** [comment]
breaking into a secure frequency has never been easier.
now just as easy as getting into the department and stealing an intercom

**Comment by MarkusLarsson421** [comment]
Yep! But you have to stay around it, which tends to be harder. It'll let you taunt Security easily or even calling for security and similarly. It also allows people who are not on the Medbay comms to ask for help in Medbay via their comms. Instead of yelling "MEDICAL DOCTOR TO MEDBAY!" over common comms.

**Comment by EvilDragonfiend** [comment]
This removes AI's ability to eavesdrop crews converstaion through adjusting intercom's channel to AI private.
I personally prefer more elegant way to control intercoms.

**Comment by Nakalon** [comment]
I like this idea but agree with what was said. No one uses intercoms as it is now except when power goes out

**Comment by MarkusLarsson421** [comment]
> I like this idea but agree with what was said. No one uses intercoms as it is now except when power goes out

If you were in Medbay or Security lobby and you needed their help but you don't have Security coms, you can now do that. Instead of yelling out onto common coms "MEDIC TO MEDBAY!!!". Also, it allows for the department to talk to each other when coms is out. Say you're a Doctor and you need something from Chemistry, now you'd be able to ask for it. Assuming they have an intercom nearby. It's not a major change, but it is one that I think will benefit the game.

**Comment by MarkusLarsson421** [comment]
This is ready for reviewing, didn't change much in the time but I did decide to not do any mapping changes at all. I will leave that for future mappers to do as they wish.

**Review by EvilDragonfiend — CHANGES_REQUESTED** [review]
I don't like that it's not possible to rebuild one.
I think there should be a kind of minour version of radio key that is only allowed to go into intercom.
or /area should have a radio channel freq, and it should enable the department frequency.

**Comment by EvilDragonfiend** [comment]
It seems you're not sure what to do. Try this approach

```DM
/obj/item/radio/intercom/recalculateChannels()
	..()
	var/area/intercom_area = get_area(src)
	if(!intercom_area)
		return
	
	for(var/each_channel in intercom_area.intercom_radio_channels)
		channels[each_channel] = TRUE

/area
	var/intercom_radio_channels

/area/chief_medical_officer_room
	intercom_radio_channels = list(RADIO_CHANNEL_COMMAND, RADIO_CHANNEL_MEDICAL)
```

**Comment by Rukofamicom** [comment]
Due to personal circumstances, author has requested that all PRs be treated "as-is" for the time being. 
Closing this one due to outstanding changes requested

**Pull request closed without merging**
