### PR TITLE
removes security cyborgs via config, refactors security borg transformation module into a research node

### PR DESCRIPTION
**Pull request by bloons3**
## About The Pull Request

Removes https://youtu.be/3SM0khChXxQ

W+M1 is not engaging gameplay. This removes W+M1.

- Allows research via config
- Hides items from tech tree
- Moves Security Borg module / Disabler cooling module to a research node
- 
image

## Why It's Good For The Game

> Nobody thinks it's fun to play again a nigh-unstoppable robocop with all access and all the remote control abilities that cyborgs get, infinite cuffs and if paired with a good cell, infinite disabler and baton charges that can be killed in 1 hit by a flash or disabled with easilly accessible EMPs.

https://github.com/BeeStation/BeeStation-Hornet/pull/2799#issuecomment-715908952

>Secborgs are dumb, but for different reasons- they encourage players to validhunt and break silicon policy, as well as let people who want the perks of power hungry control sec gets play that without being easy to robust with a single shove

https://github.com/BeeStation/BeeStation-Hornet/pull/2799#pullrequestreview-517418789

## Changelog
:cl:
config: Disables security borgs
config: Security borg transformation modules are handled via a techweb, and gated via config
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
Instead of complaining about infinite disabler, make it not infinite?

**Comment by bloons3** [comment]
> Instead of complaining about infinite disabler, make it not infinite???

Doesn't address that Security borgs are encouraged to act as members of Security first, Silicons second. Being validhunted isn't fun, especially when the validhunter can only be stopped in a single extremely situational way (EMP).

The other issue is borg powercreep with upgraded energy cells and yellow slime cores. There is even an upgrade that allows a security cyborg to shoot their lasers _faster_ .

**Comment by MCterra10** [comment]
Sounds like an issue of rule enforcement rather than a code problem

**Comment by ghost** [comment]
No limitations short of removal are going to ever stop secborgs from being awful; other borg modules are already bad enough when they validhunt and they have none of the special equipment secborgs are given.

**Comment by Effemu** [comment]
just remove the disabler so secborg cant safely spam it from the distance

**Comment by Mat05usz** [comment]
One of the rare cases I agree with complete removal. Sec borgs are only fun for the validhunter silicon player :vomit:, infinite disabler, baton, and when emagged, laser can't really be improved. Even if, just the incentive of being red, called 'security borg', AA (plus a lot more options that regular sec cannot use) make it so it's just a shit, unfun module.

**Comment by PowerfulBacon** [comment]
We have downstreams, even if this was accepted doing the config option is better than removing it entirely.

**Comment by bloons3** [comment]
> We have downstreams, even if this was accepted doing the config option is better than removing it entirely.

@PowerfulBacon Please review change in how config functions for techwebs

**Comment by DatBoiTim** [comment]
Wait wasn't secborg already a research node?

Edit: I misunderstood, this makes it a standalone techweb node.

**Comment by bloons3** [comment]
> Wait wasn't secborg already a research node?
> 
> Edit: I misunderstood, this makes it a standalone techweb node.

Makes it a standalone node that can be hidden, since it makes no sense to be able to print/craft a module that is disabled and has no use.

**Review by francinum — APPROVED** [review]

**Pull request merged**
