### PR TITLE
Adds a boot knife for security

### PR DESCRIPTION
**Pull request by BlueHNT**
## About The Pull Request
Adds a small backup weapon to security which they can carry in a boot.

## Why It's Good For The Game
During green, security is unable to carry anything lethal at all. With this they would at least have a knife for when shit hits the bucket. It would also make sec be able to help with vines and a plethora of situations where they just need to cut something. Be it a wire or person or a grotesquely oversized spider even.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image

</details>

## Changelog
:cl:
add: added sec knife to security vendor
balance: added a sec knife. An inferior cargo knife.
imageadd: added sprite for secknife
:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
> add:

This is a balance change

**Comment by BlueHNT** [comment]
Also got a smaller version but I can't really choose. 
image

**Comment by MarkusLarsson421** [comment]
There is already the survival knife which looks a lot better, also, this feels a bit too much for mall cops. Perhaps if this item was placed in the armoury?

**Comment by BlueHNT** [comment]
Taken down due to @scezrbryn whatever the fuck was his name

**Pull request closed without merging**
