### PR TITLE
Antag Rep Changes

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

If you have an antag disabled, you will automatically use 0 tickets on it (lowering your chance if there are not enough players in game) and no antag rep will be used if you get picked.

## Why It's Good For The Game

Gone are the days of losing 175 antag rep for being the only person in the server.

## Changelog
:cl:
fix: Players who don't want to be antag, won't lose rep for being said antag.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Seemed to work good on a private server, will need some bigger scale tests though, since it changes a vital mechanic

**Comment by PowerfulBacon** [comment]
Has this been put into #pr-player-input yet? I cannot seem to find it in there

**Comment by Sun-Soaked** [comment]
I'd say this is more of a quality-of-life change then a contentious issue, we're just removing a quirk of the rep system that punishes unwitting lowpop antags for existing.

**Comment by eLeCtrOssSnake** [comment]
Agreed.

**Pull request merged**
