### PR TITLE
Reworks PASSGLASS

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Reworks PASSGLASS to PASSTRANSPARENT.
Lasers will now pass through objects with low alpha values, with probability according to the alpha value.
This means that someone with chameleon, who is invisible, will have projectiles pass through them.

Directly targetting a transparent person will still hit them however.

## Why It's Good For The Game

Lasers will now pass through more transparent objects rather than just glass.

## Testing Photographs and Procedure

image

image

image

image

image

image

## Changelog
:cl:
tweak: Lasers can now pass through anything that has a low alpha value rather than just glass.
/:cl:

### CODE REVIEW

**Comment by Dejaku51** [comment]
i believe xeno hunters can be invisible. will it pass through them?

**Comment by Rukofamicom** [comment]
Sentinels, not hunters. They can't quite go full invisible, but that would certainly be a neat trait for them to have since they are so rarely chosen compared to hunters.

**Comment by LodedDiper69** [comment]
This makes chameleon go from already very robust to basically undefeatable. How are you meant to take someone down like this nonlethally?

**Comment by Rukofamicom** [comment]
Chameleon fades when they move, even if forcibly, no?

**Comment by PowerfulBacon** [comment]
Chameleon instantly disables if the person is moves, or if they attack. Also if you click on the target directly, the projectile will always hit

**Review by itsmeow — APPROVED** [review]

**Pull request merged**
