### PR TITLE
Removes auto punctuation

### PR DESCRIPTION
**Pull request by imsynthex**
## About The Pull Request

This doesn't remove auto capitalization, just auto punctuation

## Why It's Good For The Game

It was a bad idea to begin with and doesn't really add anything

## Changelog
:cl:
del: Removed auto punctuation
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
why though?

**Comment by ToasterBan** [comment]
what's wrong with punctuation?

**Comment by imsynthex** [comment]
> why though?

Some people may want to write out each word as a separate message and auto punctuation just makes it look weird

And then there are all the situations where auto punctuation adds a full stop even though you don't want it to (like when you use quotation marks)

I think you should either be able to turn it off or it should be removed entirely so people can decide for themselves whether they want a full stop at the end of something or not

I see this will get closed but I still think auto punctuation should be removed

**Comment by imsynthex** [comment]
image
like what the fuck is this

**Comment by TeomanTheGreat** [comment]
> 
> I think you should either be able to turn it off or it should be removed entirely so people can decide for themselves whether they want a full stop at the end of something or not
> 

Then why don't you code that?

**Comment by imsynthex** [comment]
> > I think you should either be able to turn it off or it should be removed entirely so people can decide for themselves whether they want a full stop at the end of something or not
> 
> Then why don't you code that?

Because making everything togglable isn't a real solution

**Comment by ToasterBan** [comment]
> image
> like what the fuck is this

it would be just as easy to put " into the list of proper punctuation as to remove it

**Comment by imsynthex** [comment]
> > image
> > like what the fuck is this
> 
> it would be just as easy to put " into the list of proper punctuation as to remove it

It's an example I brought out to emphasize a point, even if this 1 issue was fixed I still think auto punctuation should go

**Comment by Kapu1178** [comment]
make it a preference toggle

**Comment by ike709** [comment]
Don't make it a preference toggle.

**Comment by ike709** [comment]
🔑

**Comment by Kapu1178** [comment]
> Don't make it a preference toggle.

There's legitimate reason someone would not want to capitalize a given message. For emphasis on monotone voices, talking in all lowercase is a subtle but effective way to communicate that.

**Comment by imsynthex** [comment]
> > Don't make it a preference toggle.
> 
> There's legitimate reason someone would not want to capitalize a given message. For emphasis on monotone voices, talking in all lowercase is a subtle but effective way to communicate that.

This PR doesn't touch capitalization, it just removes forcing a full stop at the end of every message no matter if it makes any sense or not

> 🔑

I'll save you the effort

**Pull request closed without merging**
