### PR TITLE
Surplus Implant Duffelbag & Minor Changes to all Surgical areas

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request

Adds a duffelbag containing a bunch of unused, underappreciated or fancy implants to all Medbay surgery rooms. 

The bag may contain the following:
- organ/cyberimp/arm/janitor
- organ/cyberimp/arm/botany
- organ/cyberimp/arm/surgery
- organ/cyberimp/chest/nutriment
- organ/cyberimp/mouth/breathing_tube
- organ/eyes/robotic/glow
- organ/eyes/robotic/shield

## Why It's Good For The Game

Medbay always complain how they have nothing to do, especially early game. Now I wish to bring to their attention that they can do implants for people and give them a select few various implants to give them not only the opportunity to implant the standard toolset and surgical implants but also the almost never used janitorial and botanical toolset implants!

I didn't even know Medbay could print and do implants until I had like 2 000 hours in the game and that's after 600 hours being spent in Chemistry.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>
Surplus implants duffelbag.

image

</details>

## Changelog
:cl:
add: Surplus Implant duffelbag.
balance: [Box, Delta, Corg, Kilo, Echo, Meta, Fland, Rad] Added surplus implant duffelbag and reorganized surgery. Swapped tools with a surgical duffelbag.
tweak: [Delta, Meta, Box, Rad, Kilo, Corg] Tweaked the position of objects in Robotics surgery and swapped tools for surgical bags with tools.
tweak: [Corg] Added an anesthetic closet to Robotics surgery.
add: Cargo order for surplus implant crate.
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
> tweak: [BoxStation] Added surplus implant duffelbag and reorganized surgery. Swapped tools with a surgical duffelbag and did minor design changes to Robotics,
> tweak: [DeltaStation] Added surplus implant duffelbag and reorganized surgery. Swapped tools with a surgical duffelbag and did minor design changes to Robotics,
> tweak: [CorgStation] Added surplus implant duffelbag and reorganized surgery. Swapped tools with a surgical duffelbag and did minor design changes to Robotics,
> tweak: [KiloStation] Added surplus implant duffelbag and reorganized surgery. Swapped tools with a surgical duffelbag and did minor design changes to Robotics,
> tweak: [MetaStation] Added surplus implant duffelbag and reorganized surgery. Did minor design changes to Robotics,
> tweak: [RadStation] Added surplus implant duffelbag and reorganized surgery. Minor design changes to Robotics,
> tweak: [FlandStation] Added surplus implant duffelbag and reorganized surgery. Did minor design changes to Robotics,

Balance tag should be used here

**Comment by DarnTheMarn** [comment]
Isn't performing elective implant surgery more of a robotics thing than a medical thing. Doctors should be installing hearts/lungs/livers not tool sets and eyes.

**Comment by MarkusLarsson421** [comment]
> Isn't performing elective implant surgery more of a robotics thing than a medical thing. Doctors should be installing hearts/lungs/livers not tool sets and eyes.

Believe it or not, they are properly equipped to handle implants on organics. Plus, Roboticists already have so much on their plate and would use half the implants I put in for themselves. Excluding the surgical toolset is not the point unless you're an antag. Getting a toolset implant as a non-antagonist doctor is the same, if not worse, than getting a full toolbelt and get you bwoinked for powergaming.

**Comment by Fronsis** [comment]
> > Isn't performing elective implant surgery more of a robotics thing than a medical thing. Doctors should be installing hearts/lungs/livers not tool sets and eyes.
> 
> Believe it or not, they are properly equipped to handle implants on organics. Plus, Roboticists already have so much on their plate and would use half the implants I put in for themselves. Excluding the surgical toolset; this is not the point unless you're an antag. Getting a toolset implant as a non-antagonist doctor is the same, if not worse, as getting a full toolbelt and will get you bwoinked for powergaming.

Then it isn't like some sort of unintentional note-bwoink bait? since people will think that ''it's here so we can put it to anyone/myself'' instead of going ''Hey, any engineers/jani/botanist/med want this?'' i feel like the more controversial ones are the surgery and the toolset

**Comment by Rukofamicom** [comment]
This doesn't really address any issue including what it claims to be helping, it's just marginal power/progress creep. 

These implants are readily available and rarely utilized in most rounds though, so making them a bit more available might lead to more people requesting them and interacting with med at for reasons other than "Oof ouch an antag happened"

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
I have small conditions for approval though

* Make the surplus bag have a random assortment instead of always the exact same
* Remove the generic toolkit from the assortment
* Move all of the implants available at random in the surplus bag available at roundstart via lathe as well, so that doctors can make more whenever materials become available without dedicated research.

**Comment by DarnTheMarn** [comment]
>Believe it or not, they are properly equipped to handle implants on organics. Plus, Roboticists already have so much on their plate and would use half the implants I put in for themselves. 

Uhh what? Roboticists don't have anything to do. Once you have a cyborg body ready and waiting for anyone who wants to get borged you can... Make an army of bots, augment yourself, make a RIPLEY, or beg the captain to let you build cooler stuff. Medbay has the tools but it's not their field of expertise. The warden has a full toolbox in his lair but that doesn't mean he can go fiddling with the supermatter engine.

**Comment by MarkusLarsson421** [comment]
> The warden has a full toolbox in his lair but that doesn't mean he can go fiddling with the supermatter engine.

Medbay can print all implant robotics can  print from their techfab.

**Comment by DarnTheMarn** [comment]
>Medbay can print all implant robotics can print from their techfab

And I don't think they should, outside of the necessary organs. Implants are robotics job, that's why they've got a set of surgical tools and an exosuit fabricator. They're a content starved job and this change steals content from it to give to medbay who usually has more than enough to do once the round gets going.

**Comment by MarkusLarsson421** [comment]
> And I don't think they should, outside of the necessary organs. Implants are robotics job, that's why they've got a set of surgical tools and an exosuit fabricator. They're a content starved job and this change steals content from it to give to medbay who usually has more than enough to do once the round gets going.

This is a separate issue that you are welcome to bring up in your own PR.

**Comment by DarnTheMarn** [comment]
>This is a separate issue that you are welcome to bring up in your own PR.

Said PR would also involve removing this if it gets merged which is kind of pointless.

**Comment by Rukofamicom** [comment]
> Said PR would also involve removing this if it gets merged which is kind of pointless.

Just move it to robotics in that PR

**Comment by DarnTheMarn** [comment]
>Just move it to robotics in that PR

Tell that to Markus, he's the one making it a thing in the first place

**Comment by Rukofamicom** [comment]
This PR is fine as-is, except for the merge conflict - I'm suggesting you to "fix" it in a separate PR so it can be addressed separately. Cybernetics are not and have never been explicitly the domain of robotics, if you want them to be that deserves its own PR to change.

**Review by Rukofamicom — APPROVED** [review]
Still waiting for second approval due to balance change

Not holding the PR hostage over the request to make the items already researched - a second maint can decide whether this is necessary or not when they come to approve.

**Comment by MarkusLarsson421** [comment]
*sighs*

**Comment by MarkusLarsson421** [comment]
Unsure how to handle the current situation with health analyzers, I've assumed they are to be removed.

**Comment by Rukofamicom** [comment]
Bacon has absolutely refused to have them removed so they won't be unless he changes his mind.

**Comment by Fronsis** [comment]
> > Medbay can print all implant robotics can print from their techfab
> 
> And I don't think they should, outside of the necessary organs. Implants are robotics job, that's why they've got a set of surgical tools and an exosuit fabricator. They're a content starved job and this change steals content from it to give to medbay who usually has more than enough to do once the round gets going.

After seeing the recent thread that suggested stuff around Robotics [Seen here](https://forums.beestation13.com/t/future-of-robotics/25572/16) Darn comments seems accurate and it makes me bring three points:

. The first one being that a better solution in the long run would be to separate all type of implants/upgrades/etcetera between Medbay and Robo, what i mean with this is that something like a robotic heart makes sense to be in medbay but something like a wing or tool implant should be only printable on Robotics, after all.. in terms of ''upgrading a space man'' Medbay can already do so with a lot of surgeries that are researched late into the game

. Again, the bag seems more fit for robotics, as we've discussed here and on the forum thread, doctors being ''content'' starved is very anecdotical and changes from shift to shift, besides.. they don't need to have something to do 100% of the time, they can have breaks too where nothing is happening to have a chance to experience some other type of RP(like going to the bar and chat with someone for example)

. I'm still worried about the contents of the duffelbag **specially** if all of those get made roundstart, leaving the whole ''powergaming bait'' since that's moreof a player-administrative issue.. I feel like this is a bypass of some stuff just to acquire a literal roundstart mindmax, for example a traitor doctor, or someone that knows this is present can come up roundstart and ask to get shielded eyes and a tool implant anytime from the start and that would allow them to do a lot of things without leaving any evidence or impacting the round other than for their own benefit

If i could get picky i could say that even the nutriment implant bypasses interacting with the chef or just buying stuff on the vendor, same with the breathing tube to an extent, since @Rukofamicom suggested all of those to be researched roundstart.. then if said doctor encourages those implants or a player comes asking for them, the interactions get reduced because... They no longer need to steal/lurk maint/buy a toolbelt, same with a welding mask/goggles, they can ignore wearing a mask, they have more efficient ways to do surgeries with the surgical arm, they bypass interactions with the chef by having the nutri implant, etcetera.

The idea of having a couple of roundstart implants is fine, but i strongly believe it's more fitting for Robotics than for Medbay and that in a longer run the implants should be separated more thematically so the interested player would need to interact with two departments rather than one, and also i need to bring out the issue of having them roundstart available might not be as good as it sounds.

**Comment by DarnTheMarn** [comment]
I'll throw in another thing, roboticists have fuck all to do round start. Make a cyborg if people want to be borged, make a couple bots, woop-de-doo you now have fuck all to do until materials and research comes in. But only after the important stuff gets researched first! Meanwhile medical has to build machines, beg for chems, get tools, organs, they have a lot more to do. Giving the bag to robotics means they have one actual thing they can do round start. As for what Fronsis said, organs should be printable at medbay but I don't think any non-essential implants or augments are the domain of medbay. Medbay heals, not enhances. Science enhances both machines and body when you think about it.

**Comment by MarkusLarsson421** [comment]
> I'll throw in another thing, roboticists have fuck all to do round start. 

I don't know about you, but I tend to make a mining mech round start as a roboticist to prevent being unable to do anything. While I wait on resources, I may make servers for Science, do some R&D for T3 parts, and then finally make a bunch of bots and throw 'em at people who might want or need 'em. And by this point, the Miners will have gotten their initial load or two, and I can then make Cyborgs, spam people to get implants, or if they want a mech, maybe make loke three spare shells and so on. Robotics has a lot to do. Typically, I am personally never given a break in Robotics.

**Comment by MarkusLarsson421** [comment]
> Meanwhile medical has to build machines

You should report this as they are not Engineers and only when Engineers have been asked and ignored or said 'no' should they do it themselves.

> organs should be printable at medbay

What if someone wants to become a bootleg IPC and get a full augmentation? Meaning all organs and body parts are replaced.

> Medbay heals, not enhances. 

Virology (now removed), Genetics (previously part of Science), Chemistry drugs, and surgical modifications would disagree with this statement.

**Comment by DarnTheMarn** [comment]
>You should report this as they are not Engineers and only when Engineers have been asked and ignored or said 'no' should they do it themselves.

Maybe, but that never stops them from doing it. 

>What if someone wants to become a bootleg IPC and get a full augmentation? Meaning all organs and body parts are replaced.

You know, IPCs are robots. I wonder if there is a job that involves robots and has the means to help this hypothetical person.

>Virology (now removed), Genetics (previously part of Science), Chemistry drugs, and surgical modifications would disagree with this statement. It's for the same reason I want Nanites to be part of Medbay. They work with organics, not machines. Everything that has a direct effect on organic bodies should be in Medbay, that's their field after all.

If you remove implants and nanites from science, what will science even have? Toxins that gets done in 5 minutes and never gets touched again, exploration crew that have 0 impact on the station and xenobiology that can only have one person working unless you want to deal with a toddler tantrum?

**Comment by Rukofamicom** [comment]
Just gonna cut in and say nanites aren't going anywhere.

**Comment by DarnTheMarn** [comment]
I like the utility nanite programs I just dont like the healing ones, its bullshit that if you're lucky enough and the nanites are made well they can defibrillate you and heal you from crit.

**Comment by MarkusLarsson421** [comment]
> You know, IPCs are robots. I wonder if there is a job that involves robots and has the means to help this hypothetical person.

Reread it.

> what will science even have?

R&D. Finally, we might get to see some Scientists outside Science doing upgrades and assisting with the construction of some machines. Make some servers, communicate with your peers, offer things to departments, and so on. Make things FOR people with Xenobio. Fetch things FOR people with Exploration. Construct things FOR people with Robotics. 

Hell, swap to Engineering, I bet the server still has a chronic lack of Engineers. Go Engineer and make some machines people might want or need.

**Comment by Rukofamicom** [comment]
I've sent a ping to maints to get the balance approval or denial of this handled. I'll come back soon with either a 👍 or closing due to more than three giving it 👎 so you can stop fixing map conflicts for eternity

**Comment by Rukofamicom** [comment]
Alright, get these conflicts handled one last time and ping me for merge before someone does a mapping change again. 

Don't forget to include changes to Echo!

**Comment by Rukofamicom** [comment]
Quick question: What does this blurb mean? 

> Did minor design changes to Robotics

**Comment by MarkusLarsson421** [comment]
Let me get to it, I'll ping you on Discord within an hour or so.

**Review by PestoVerde322 — APPROVED** [review]

**Review by Rukofamicom — APPROVED** [review]
@PestoVerde322 you're free to merge whenever the current mapping crisis is resolved.

**Pull request merged**
