### PR TITLE
Balance: Baseball Bat Target_Throw Reduction

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Reduces the distance baseball bats launch players

## Why It's Good For The Game
I don't think it's fun or fair that a common melee item out-robusts everything in the game, launching players across the room with one hit. I will probably want to remove the mechanic altogether, but I'm just reducing the throw distance here.

## Changelog
:cl:
balance: Baseball bat throw distance reduced substantially
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
That's a very heavy reduction.

**Comment by jlsnow301** [comment]
It definitely is. However, it's still 100% prob of a tile move, which is strong for a basic melee weapon, just not launch-you-across-room strong (in my op)

**Comment by qwertyquerty** [comment]
I say make it 4-6

**Comment by qwertyquerty** [comment]
Putting this up to vote

**Comment by qwertyquerty** [comment]
Vote failed

**Pull request closed without merging**
