### PR TITLE
Disable gangs on MRP

### PR DESCRIPTION
**Pull request by yorii**
## About The Pull Request

Disables gangs on sage until it has been fixed.

## Why It's Good For The Game

Gangs is bugged to the point of being way too imbalanced since gang leaders often spawn without their gear, combined with the MRP ruleset makes for a very bad game experience overall.

## Changelog
:cl: evil jannie
config: disabled gangs on sage
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
> until it has been fixed.

It's not broken, its just not fun

**Comment by super12pl** [comment]
We removed the devils we can remove the gangs

**Comment by yorii** [comment]
> It's not broken, its just not fun

It is also broken, people with mindshields can roll gang boss and not receive gear or hud, and sometimes a random non-mindshielded gang boss just spawns without any gear or HUD.

**Comment by zeskorion** [comment]
The broken shit can be fixed but its not a fun gamemode

**Comment by yorii** [comment]
Regardless of which reason, it should probably be disabled on MRP for now.

**Comment by eLeCtrOssSnake** [comment]
Should be. And should be in the future. No. Gangs are staying where they should be, on both servers.

**Comment by RafRoq** [comment]
instead of removing why dont you rework it to be fun ? why are you following the removal path ?

**Comment by ike709** [comment]
@uBadush Well we're bringing in 2 new modes so it balances out.

**Comment by eLeCtrOssSnake** [comment]
> @uBadush Well we're bringing in 2 new modes so it balances out.

Add, not remove. Still no.

**Comment by eLeCtrOssSnake** [comment]
Also, merge conflict because somebody deleted something already

**Comment by Sapfearon** [comment]
Gangs are very buggy and not funny gamemode that also against MRP server rules. Now that we got heretics and clock cult, i think it's time to remove this from MRP. If you ever fix and balance it, feel free to add back. For now - no.

Also it's literally the only gamemode where you can't counter conversion by any means and the only antag that can deconvert mindshielded people. 

It's literally nations, but with random nations ( gangs) and with weapons. Nations are not a gamemode, so why gangs are?

**Comment by eLeCtrOssSnake** [comment]
Shouldn't need a vote. Add, not remove. Make a pool of questions where you ask what people don't like in particular about the game mode. Then make changes to the game mode and get them merge guaranteed. Don't be zeskorion, don't go UHH ME MONKEY 🐵 DELETE WHAT I DONT LIKE UHHH I CRY BECAUSE OTHER PEOPLE HAVE THEIR OWN OPINIONS.

**Comment by ike709** [comment]
To be merged once clock cult 3 is in.

**Comment by PowerfulBacon** [comment]
Its more like clockcult 2 2

**Comment by eLeCtrOssSnake** [comment]
Don't merge

**Comment by Isy232** [comment]
This isn't removal, its a disable. If someone make a PR to fix it, they can just change the line to readd it.

**Review by ike709 — APPROVED** [review]
@Crossedfall Config.

**Comment by PowerfulBacon** [comment]
Why only on MRP?

**Comment by Crossedfall** [comment]
Repo is deleted, so this can't be fixed.

**Pull request closed without merging**
