### PR TITLE
Kills spawn() usages almost entirely, in favor of timers

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports:
- https://github.com/tgstation/tgstation/pull/45429
- https://github.com/tgstation/tgstation/pull/46629
- https://github.com/tgstation/tgstation/pull/46837
- https://github.com/tgstation/tgstation/pull/47634
- https://github.com/tgstation/tgstation/pull/50562

## About The Pull Request
Replaces nearly all instances of spawn() with timers in the way of ASYNC.

## Why It's Good For The Game
Cleaning up ancient code. We *really* shouldnt still be structuring our code this way

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
code: removed most instances of spawn() in favor of timers
/:cl:

### CODE REVIEW

**Comment by Rukofamicom** [comment]
> Cleaning up ancient code. We really shouldnt still be structuring our code this way

Are you able to explain why/what issue it is causing?  I expect it to be something related to optimization and am asking purely for the sake of my own code quality.

**Comment by Tsar-Salat** [comment]
> Are you able to explain why/what issue it is causing?

It's functionally inferior to timers, & forces hard deletion among other things. 


Going forward, there will likely be max 4 of these left that I cannot remove.

**Comment by Tsar-Salat** [comment]
This is likely the conclusion of this PR. Ive killed exactly 59 uses of spawn() across the codebase, either bypassing the need for the proc in certain areas, or converting it to timers.

The rest are rather deeply embedded, and will need their own specific PRs. Ive labeled each instance as such where I plan to do so in the future.

**Comment by itsmeow** [comment]
If this is no longer a draft, mark it as such

**Comment by Tsar-Salat** [comment]
dont really care about this anymore

**Pull request closed without merging**
