### PR TITLE
Adds in unholstering delay + slowdown

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

When equipping a weapon to the hand slot, the weapon will not be able to be fired and you will be slightly slowed down until it is fully equipped. Unequipping or dropping the weapon cancels this.
- Light weapons: 1.5 seconds
- Medidum weapons (Basically all of them): 2 seconds
- Heavy weapons (Shotguns, snipers, LMGs): 2.5 seconds
- Disabler: 2 seconds
- Magic wands and other non-guns: 0 seconds
- Skektchkin: 1 seconds
- Infiltrator pocket pistol: 0 seconds

## Why It's Good For The Game

https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/984f6732-d10f-498a-9f63-002669d27da4

Even when comparing energy swords and arm blades, these weapons are around 3-5 seconds each. This equip cooldown significantly levels the playing field when catching a gun wielder off-guard in melee range. It also means that equipping a gun like a disabler gives you a brief period where someone may be able to give you the slip.

There is a risk reward element between carrying your gun at all times and being shoved/slipping vs keeping your gun away but being caught off guard.

## Testing Photographs and Procedure

https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/6e9e7433-4e83-47f8-9b41-8e5f05b15020

## Changelog
:cl:
balance: Equipping guns will now provide a brief period where you are slowed and cannot fire the gun, represented by teh crosshair timer. (This is 2-4 seconds depending on the gun).
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
This PR also contains the fire rate crosshair.

**Comment by Tsar-Salat** [comment]
Fingerguns?

**Comment by PowerfulBacon** [comment]
Fingerguns do still have the cooldown, including the mime revolver

**Comment by Sapfearon** [comment]
felt awful to play due to delay and i started to hate crosshair after 10 minutes. It's so clanky.
Also 3 second delay when 1 second is IRL standart for taking gun out of holster? And then there are people who can shoot 6 shots in 1 second with gun starting in holster.
Slowdown makes sense for ballistic due to safety you need to trigger, but we don't have safety on guns unlike 90% of other servers.

This could work if bee had skills, with security having reduced timer on all of this while normal crew had to suffer. As right now, taking out bombs out of your bag has 0 slowdown, but to shoot bomber you have to suffer.

**Comment by Fronsis** [comment]
> felt awful to play due to delay and i started to hate crosshair after 10 minutes. It's so clanky. Also 3 second delay when 1 second is IRL standart for taking gun out of holster? And then there are people who can shoot 6 shots in 1 second with gun starting in holster. Slowdown makes sense for ballistic due to safety you need to trigger, but we don't have safety on guns unlike 90% of other servers.
> 
> This could work if bee had skills, with security having reduced timer on all of this while normal crew had to suffer. As right now, taking out bombs out of your bag has 0 slowdown, but to shoot bomber you have to suffer.

Indeed this is a massive buff for bombs and insta-kill throwables

4 seconds for shotguns? What about the variants of shortend or sawn off shotgun, they should be ''lighter'' to aim


Anyway i played a round with it, It feels very frustrating to add a mechanic that forces the player to.. just stand there and getting hit in melee range while spamming left click imagine you're talking face to face with someone who's insulting you one tile away and they decide to pull out a shank, you basically have three seconds where you just get stabbed, unable to do anything (how fun!) and even trying to retreat gives you a slowdown, now instead of a shank imagine if it's a d-esword, a sharpened cult sword,a ninja sword, heretic combo of mansus hand/any other spell + blade... They will absolutely devastate you and in **most** situations against those antags you already **currently lose** the 1v1 using a disabler or even a basic energy gun, this just adds more frustration.

Also i agree the crosshair feels very clanky and.. just doesn't feel like it works since our mouse movement is already fast, so you barely see that ''cooldown''

**Comment by PowerfulBacon** [comment]
Slowdown time has been reduced and the crosshair has been removed from normal gun fire (Will be looked at in the other PR). Bumping TM

**Comment by mudzbe** [comment]
This should only affect things taken from your backpack or pockets. Holsters and belts are setup for quick access

**Comment by PowerfulBacon** [comment]
> This should only affect things taken from your backpack or pockets. Holsters and belts are setup for quick access

That would defeat the point of this PR since almost all guns are in the holster or belt. I did consider making the time longer for guns stored in the backpack but decided against it. I could allow picking a gun up off the floor give no equip delay.

**Comment by mudzbe** [comment]
> That would defeat the point of this PR 

Well what is the point of this PR? Nerf sec because that’s who it’s effecting the most, sec is already outnumbered and susceptible to ambushes, why is this necessary?

> There is a risk reward element between carrying your gun at all times and being shoved/slipping vs keeping your gun away but being caught off guard.

There is already in effect a drawing period as the player has to decide what to equip.

**Comment by PowerfulBacon** [comment]
The purpose of this PR is to decrease the time to kill that guns have in order to make them more difficult to use in close quarter encounters (You shouldn't be able to out-damage someone with an e-sword with a laser gun at melee range if neither party is moving)

**Comment by mudzbe** [comment]
Lasers are useless against eswords because of deflection though. You only measured the ttk of a kitchen knife which is the lowest tier melee weapon I bet eswords are at least double that, and when you factor in reaction and organic draw speed this isn’t an issue.

First result: “Our research tells us a standing suspect can draw a pistol from their waistband, point, and shoot in an average of . 25 seconds”, again this would effect sec the most which would have quicker reaction

**Comment by mudzbe** [comment]
Esword has 30 damage, laser has 20 damage, esword has higher dps

**Comment by PowerfulBacon** [comment]
> Esword has 30 damage, laser has 20 damage, esword has higher dps

That's not how DPS works. The laser gun fires faster than the e-sword can hit.

**Comment by PowerfulBacon** [comment]
> Lasers are useless against eswords because of deflection though.

E-Swords don't deflect, that's de-swords

**Comment by mudzbe** [comment]
> > Esword has 30 damage, laser has 20 damage, esword has higher dps
> 
> That's not how DPS works. The laser gun fires faster than the e-sword can hit.

I tested this with syndiearmour, lazer takes 2 seconds extra, unarmoured esword is 1 second extra

**Comment by mudzbe** [comment]
Yea I said lazers are better at killing the younglings however eswords are better at killing syndies, I think they’d be better against sec armour too. But wouldn’t a simpler solution be increasing esword damage so it’s better against no armour?

**Comment by PowerfulBacon** [comment]
We don't really want to make combat shorter. The easier solution would be lowering gun damage, to match melee damage.

**Comment by Fronsis** [comment]
> We don't really want to make combat shorter. The easier solution would be lowering gun damage, to match melee damage.

A dangerous approach, remember you'll eventually have to balance out the melee damage since many of them already have a high damage or a way to make it higher, which would mean that the officer, even with armor would get outdamaged and a single dead officer is all it takes for the antag to snowball.


Cult can sharpen their sword, Ninja Sword, Heretic blade seems in a okay-ish state(though they can combo with magic.. and at that point shooting is impossible), Ling blade (it's a joke atm and we all know it) then both e-sword and d-esword dominate against range laser-guns

In the current state without this PR, most of the time a sec loses the 1v1, using a ranged weapon **if** the antagonist has a basic gear to give them protection or just a weapon that can outdamage the laser-gun security officer, it is certainly intended for an officer to not be able to beat someone 100% of the time and ambushes do play a big part in it, so in that sense the PR makes sense, but it already happens.

For example a Security officer can easily be ganked by an heretic with a decent gear but if more officers approach the heretic most likely will have to flee

I do agree that combat should last longer but it doesn't need to thread the vecinity of cat and mouse games which are just.. tiresome but it doesn't seem to be steering that way

I'll play a few rounds with the new values and return with some feedback, though from the vibes i got yesterday it seems the meta would be to unholster before going to face any threat to prevent any of the downside stats

**Comment by DarnTheMarn** [comment]
> A dangerous approach, remember you'll eventually have to balance out the melee damage since many of them already have a high damage or a way to make it higher, which would mean that the officer, even with armor would get outdamaged and a single dead officer is all it takes for the antag to snowball.

If only security had a very high damage melee weapon that can only be beat by super expensive weapons all else being equal...

>Cult can sharpen their sword, Ninja Sword, Heretic blade seems in a okay-ish state(though they can combo with magic.. and at that point shooting is impossible), Ling blade (it's a joke atm and we all know it) then both e-sword and d-esword dominate against range laser-guns

If cult/heretics/lings/desworders are out and about, why not walk with your gun out so you don't have to deal with the delay? Just be careful where you walk so you don't slip. 

>In the current state without this PR, most of the time a sec loses the 1v1, using a ranged weapon if the antagonist has a basic gear to give them protection or just a weapon that can outdamage the laser-gun security officer

You conveniently neglect to mention that you don't see laser guns nearly as much as shotguns, which will win you the 1v1 as it is now.

>I'll play a few rounds with the new values and return with some feedback, though from the vibes i got yesterday it seems the meta would be to unholster before going to face any threat to prevent any of the downside stats

Sounds like its working as intended then? If you have someone with their gun out, you know shit is about to go down, you won't get the un holster-double tap out of nowhere. It also prevents people from just repetitively holstering and un holstering their gun to stop from losing it while being shoved.

**Comment by PowerfulBacon** [comment]
> Cult can sharpen their sword, Ninja Sword, Heretic blade seems in a okay-ish state(though they can combo with magic.. and at that point shooting is impossible), Ling blade (it's a joke atm and we all know it) then both e-sword and d-esword dominate against range laser-guns

Increasing security survivability is something I am for, or at least being able to call out after they die. Some ideas I had were:
- Officer down system that will report over comms if an officer goes down 60 seconds after they start lying down.
- Some kind of radio system where security can send quick comm commands such as requests for backup. It was something I was against initially since security was very strong at the time and the meta and thinking was that security should die all the time, but now we have more lower pop rounds where 1 security officer dying can take out a good portion of security's manpower and leave someone out of the game for a long time.

**Comment by Rukofamicom** [comment]
Removed from testmerge purely because the merge conflict prevented fixing a Psyphoza bug

**Comment by PowerfulBacon** [comment]
Seems to be okay after the effect was reduced.

**Review by Rukofamicom — APPROVED** [review]

**Comment by Rukofamicom** [comment]
Hoping someone else can bump this as well because it is a really good change.

**Comment by JixS4v** [comment]
Good change, melee has been held back for far too long by people instantly unholstering their weapons.

**Comment by DarnTheMarn** [comment]
One thought, I think the timers are fine as-is but it would be interesting to increase delays depending on the storage location. It'd make sense to make pulling a gun out of a backpack take longer than taking a gun off suit storage or your belt slot.

**Comment by PowerfulBacon** [comment]
That was something I considered initially, having backpack stored guns take an extra long time to pull out, but ultimately it leads to a lot of annoyances when coding due to:
- Pull gun out backpack
- Drop gun to clear timer
- Pickup gun to get quick timer

**Pull request merged**
