### PR TITLE
Removes devil and associated shitcode

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports:
- https://github.com/tgstation/tgstation/pull/53612

## About The Pull Request
Removes devils, devil spells, devil weapons, devil contracts, devil imps, devil laws, devil bodyparts, devil chemical interactions, and devil living vars.

Theres only 2 notable code changes outside the mass-deletion. 

As checking for a soul really only has 1 implementation now (liches), it has been turned into a trait applied during the lichdom ritual instead of a var on the mind.

Additionally, soul linking was only used for devils and AI's connecting to their shells. As the former was deleted, I removed soul-linking entirely and just turned it into a signal for the AI.

## Why It's Good For The Game
Old, pretty much unused code that touches a lot of things. 

As we've moved towards an exclusively-dynamic gamemode, this approaching 5-year-old gamemode has become even more obsolete. The majority of its code is unused and only becomes more annoying to account for as the years go on. Untangling ourselves from it is a good step.

I deleted no sprites, so those can still be reappropriated in the future if we want to.

I received headdev permission before making this PR.

### TODO

- [x] intial
- [x] development permission
- [x] traitify having no soul
- [ ] Lich ritual works correctly
- [x] Papercode unaffected outside of contracts
- [ ] AIs can properly switch to and inhabit their shells

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
del: removed devil gamemode
del: removed devil mobs and living code
del: removed all spells and magical contracts relating to devils
code: moved imp code to slaughter demon file
refactor: as checking for a soul only has one implementation(lich), it has been turned from a var to a trait and applied during the ritual
refactor: soul-linking with regard to the AI and its shells, has been changed to a signal

/:cl:

### CODE REVIEW

**Comment by CydiaLamiales** [comment]
Good night, sweet prince

**Comment by Rustyfoxb** [comment]
Im suprised it took this long to happen.

**Comment by Tyranicranger4** [comment]
Damn. No more hellbound variable for adminbus, sad.

**Comment by JixS4v** [comment]
> Damn. No more hellbound variable for adminbus, sad.

Pretty sure hellbound is used in places other than demons, like with lichdom

**Comment by Tsar-Salat** [comment]
man the merge conflicts on this are gonna be so damn annoying

**Comment by Absolucy** [comment]
does the curator still get some sort of funny occult book?

> Pretty sure hellbound is used in places other than demons, like with lichdom

@JixS4v Also used with the Necropolis Seed chestgib threshold, annoyingly enough.

**Comment by Tsar-Salat** [comment]
im taking a break, Semester begins soon and this is affecting my mental health

**Comment by Tsar-Salat** [comment]
> does the curator still get some sort of funny occult book?

It isnt deleted.

**Comment by itsmeow** [comment]
Still a draft?

**Comment by Tsar-Salat** [comment]
> Still a draft?

It breaks every other day due to merge conflicts and I redo my ingame tests.

I guess I can get around to undrafting it eventually

**Comment by Tsar-Salat** [comment]
needs more prerequisite work before its viable

**Pull request closed without merging**
