### PR TITLE
Allows people to create crucifixes with wood

### PR DESCRIPTION
**Pull request by TeomanTheGreat**
## About The Pull Request
Adds a new thing for chaplains and basically everyone else to craft. The crucifix! It is basically just a reskinned meatspike from the kitchen with a few differences. Here is a picture of the sprite with and without a person on it. 
image
image

## Why It's Good For The Game
Now you can crucify the clown for his many sins and watch as the station's inhabitants start worshipping him as the messiah. 

## Changelog
:cl:
add: Crucifixes can now be made with 5 wood. Now the clown can finally pay for his many crimes such as slipping security and farting. 
/:cl:

### CODE REVIEW

**Comment by DatBoiTim** [comment]
Chaplain when Felinid image

**Comment by Effemu** [comment]
good but the sprite is too big and looks out of place

**Comment by TeomanTheGreat** [comment]
> good but the sprite is too big and looks out of place

Should I make it shorter then?

**Comment by francinum** [comment]
No.

This is *only going to be abused*

**Comment by super12pl** [comment]
literally 1984

**Comment by TeomanTheGreat** [comment]
> 
> 
> No.
> 
> This is _only going to be abused_

uhhh meatspikes and nooses already exist and are easy to make

Edit: I can increase the cost if you want and it already takes a while to put someone on one.

**Comment by francinum** [comment]
> uhhh meatspikes and nooses already exist and are easy to make

I'd quite like the latter to go as well.

**Comment by TeomanTheGreat** [comment]
Should I try to add logging to nooses, meatspikes, and this then so it is easier to catch people?

**Comment by francinum** [comment]
I don't believe either of them have a place outside of their home codebases, namely Fallout and Hippie.

**Comment by TeomanTheGreat** [comment]
I may as well delete this branch then.

**Comment by Sinestia** [comment]
spikes n such are fine

and I'd like this change


But nooses are real obnoxious due to the sound.

**Comment by TeomanTheGreat** [comment]
Atleast the poles like my change

**Pull request closed without merging**
