### PR TITLE
Minor changes to the config file to make local development easier.

### PR DESCRIPTION
**Pull request by Crossedfall**
Switches the admin/mentor system to their legacy counterparts and enables the localhost rank. The former isn't needed for the localhost rank to work, but it's unlikely people are using a database for local testing.

Hosting should grant the local user full admin access automatically now. This should address @qwertyquerty 's concerns in #380 

_Also removed the invalid config option `BAN_LEGACY_SYSTEM`_

### CODE REVIEW

**Comment by qwertyquerty** [comment]
The think the migration to an org broke travis

**Comment by Crossedfall** [comment]
> 
> 
> The think the migration to an org broke travis

Fixed it

**Comment by qwertyquerty** [comment]
how

**Comment by Crossedfall** [comment]
> 
> 
> how

It just needed org access as an authorized app.

**Comment by qwertyquerty** [comment]
Oh well it had access, I removed it, and you beat me to adding it back

**Pull request merged**
