### PR TITLE
adds a pref for typing indicators

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

see title
also mutes or silent people don't have typing indicators unless it's an emote

## Why It's Good For The Game

should be a pref tbh

## Changelog
:cl:
add: added a preference for typing indicators, in the preferences panel
fix: mutes and mimes people can't have say typing indicators
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Doesn't this pretty much invalidate the entire point?

**Comment by jupyterkat** [comment]
> Doesn't this pretty much invalidate the entire point?

no, pretty much just giving people a choice

**Comment by ike709** [comment]
I'll assign Fran so he can go on an angry rant and close it.

**Comment by jupyterkat** [comment]
*insert 1984 joke here*
plus the typing indicators are on by default anyways

**Comment by francinum** [comment]
Yeah no. Not right now.

Wait until the other PR is done. I don't want them to have to clean up conflicts.

**Pull request closed without merging**
