### PR TITLE
Adds gas miners to atmos

### PR DESCRIPTION
**Pull request by M0rtgage**
## About The Pull Request

Adds gas miners to atmos, now also deletes old cans.

## Why It's Good For The Game

With the fusion "fix" demanding high amounts of gasses, there's a strong possibility that some atmosians in training can use up all the stored gasses as I have done once before. This leaves the station fighting for air. this change makes running out of gas impossible and indirectly encourages more experimentation in atmos (infinite resources to play with).
Also just realized CL = Change Log i'm not a grandpa I swear
## Changelog
:cl:
add: Puts Gas miners into their respective gas chambers.
del: Deletes the old gas cans from the chambers.
/:cl:

### CODE REVIEW

**Comment by M0rtgage** [comment]
Lemme know if anything needs to get changed, this is muh 1st map pr

**Comment by Archanial** [comment]
The miners should be placed where the canisters are, and canisters should be removed.

Also didn't they lag the server or something?

**Comment by park66665** [comment]
IMO, gas miners aren't very much needed considering rounds won't go on forever, but I do think that gas miners are fairly good thing to have since people possibly can run out of gases.

> Also didn't they lag the server or something?

I am sure that gasminer code is pretty alright.

**Comment by ghost** [comment]
The gas turbine uses up all of the oxygen quickly if you run an optimal burn mix, thank god

**Comment by Sinestia** [comment]
Definitely, haven't done fusion since the change but before I'd only do it on maps w/ miners because you would run out if you left the turbine going.

**Comment by M0rtgage** [comment]
I removed the cans and put the miners in their place

**Comment by M0rtgage** [comment]
Lemme know if anything else ought to be done

**Comment by VictorVow** [comment]
Add [gas label decals](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/11753) to the floor inside the supply rooms if the canister-as-visual-indicator is being removed.

**Comment by M0rtgage** [comment]
I'm not stealing shit from ERP furries nor am I willing to cite them in a pr.

**Comment by M0rtgage** [comment]
Metamos is a good spot to look if u want to know what this pr will look like

**Comment by M0rtgage** [comment]
Anyone with basic reading skills should be able to tell what is what in roughly a second on their first trip to atmosia

**Comment by VictorVow** [comment]
If you'd read the PR you'd see it's ported from vg, so port it from there if you really care that much about "muh furries".

**Comment by M0rtgage** [comment]
Ok buddy well nobody is stopping you from making your own pr. I see nothing wrong with giving a lil redundancy to make atmos a lil more forgiving.

**Comment by VictorVow** [comment]
Pretty childish to remove the visual indicator for no reason, then when someone gives you an alternative solution then reply "make your own PR". Either do the PR properly or don't do it at all.

**Comment by Archanial** [comment]
> 
> 
> Pretty childish to remove the visual indicator for no reason, then when someone gives you an alternative solution then reply "make your own PR". Either do the PR properly or don't do it at all.

oh shut up.
There are lots of other indicators. No need to add decals for babies.

**Comment by VictorVow** [comment]
Ah yes, let's make atmos even more difficult for newbies to get into. No need to concern yourself that this is explicitly a beginner's server. Nah, only a baby would find a visual indicator helpful here.

**Comment by Archanial** [comment]
meta already has gas miners and it was not an issue before :thinking: 
Not only the gas miners have different names, computers have different names, the fucking floors have names.
If you really thing we need those decals:
> well nobody is stopping you from making your own pr

**Comment by utilbird** [comment]
Bad CL

**Comment by Sinestia** [comment]
> Ah yes, let's make atmos even more difficult for newbies to get into. No need to concern yourself that this is explicitly a beginner's server. Nah, only a baby would find a visual indicator helpful here.

Being able to read the pumps, computers, or miners is really low fruit compared to doing anything else in atmos. 

 It's a pretty artistic thing but idk if it really increases accessibility.

**Comment by M0rtgage** [comment]
Id like to make it a lil more clear when I talk about resource limits. If you speedrun reactor creation with the double trit burn setup you'll crank thru the stations 02 supply around the 1 hour mark. Without sun God atmos skill it is nearly impossible to ramp the fusion up to maximum power in that time frame. Arguing that this pr makes atmos harder to get into is the complete opposite of the truth. After the fusion adjustments this is the lower skill floor atmos needs.

**Comment by park66665** [comment]
> I'm not stealing shit from ERP furries nor am I willing to cite them in a pr.

This is not reasonable *at all*. This behavior is, by definition, incompetence. I will happily port from and cite Vorestation if I discover something that is worthwhile enough to port.

> oh shut up.
There are lots of other indicators. No need to add decals for babies.

Atmos *should* be open for "babies." Atmos should be *friendly.* The prevalence of Dunning-Kruger effect and curse of knowledge at atmos is *stunning.* (I am not very sure if I will do something significant about it, though)

> Being able to read the pumps, computers, or miners is really low fruit compared to doing anything else in atmos.
It's a pretty artistic thing but idk if it really increases accessibility.

It *does.* You don't understand how much freshly-mined salt I have at the amount of time and energy I wasted to examine the gas pumps, this, that, and so on and so forth, and read that damn thing from the horrible UI, *just* to know which chamber is which because I don't want to fuck up. And, obviously no one wants to fuck up, do you?

The tank *was* the greatest and most accessible indicator; gas miner has overlay colors but they are barely helpful, so it is no wonder why the author is *expected* (but *not* required since it technically *breaks nothing*) to mend the currently unsatisfactory accessibility of atmos since this PR does negatively effect that accessibility. To elaborate further, changing something itself hurts accessibility, so things that seems neutral to accessibility actually hurts accessibility: You changed one indicator from canister to gas miner, and while it hurts accessibility since gas miners are worse in terms of accessibility, the change itself hurts them too since the wiki images will be out of date for months; the people working at atmos will need time to adjust; it will add confusion to whoever used to be at using canisters for the go-to indicator; old information will be out-of-sync and will confuse newbies; etc etc.

> Id like to make it a lil more clear when I talk about resource limits. If you speedrun reactor creation with the double trit burn setup you'll crank thru the stations 02 supply around the 1 hour mark. Without sun God atmos skill it is nearly impossible to ramp the fusion up to maximum power in that time frame. Arguing that this pr makes atmos harder to get into is the complete opposite of the truth. After the fusion adjustments this is the lower skill floor atmos needs.

Well, actually, it isn't about waiting to ramp up the fusion to "maximum", but continuing the fusion that already has achieved equilibrium. I meticulously did math so the time it takes for fusion to reach its mature temperature (which depends on constant plasma input. Remind you, the e30 fusion "strategy" where the time is the only thing really matters is *no more.*) stays <10 min. (Unless you are doing canister fusion, of course. Canister fusion has abysmal growth potential so it is meaningless to talk about the time a fusion canister takes to "grow" or reach the "maximum".) Anyways, doing fusion for more than one hour really does use up stored gas if one is careless at gas spending or wants to max up everything; I, too, support having gas miners. 

And, of course, fusion shouldn't be even considered when one talks about the "skill floor". The skill floor here is knowing that oxygen keeps people alive, where the oxygen is, and how to supply oxygen. Please, don't be out of touch and know what atmos *really* is.

**Comment by M0rtgage** [comment]
can yall stop pretending canisters were the second coming of christ? The real noobs are the ones who would even right click the canisters anyways. And u dont need to spam examine btw, it is much easier to hover over shit and look near the bottom left. Im no sun god but whether it ramps up or not doesn't matter, what matters is the station running out of 02 at the 1 hour mark because newb atmos billy wanted to do try this fusion thing he heard about. Most noob atmos techs I've talked to have been there for fusion. People 90% of the time aren't playing atmos just to sit around a setup that is completed when the map generates and do nothing. Even if they aren't doing fusion the current state of things means if an immovable rod or tator spaces 02 the round is over.I.K. the round one sounds stupid but I've had it happen twice now, but both times have been on meta and one time it was the C02, but both times I fixed them by holofanning the holes and letting the miner replenish them. Looking past my fusion fetish there are even more reasons for this change than I realized before. Ex. Atmos can supply decent amounts of power with the incinerator, but if the round goes too long then suddenly there's no 02 or power, cucking the station into hell. Ofc a good atmos would find a way around this but noobs seem to be the focus of this pr. I hope to god people know what oxygen is before they even touch a video game. I dont get why this pr has ruffled so many feathers.

**Comment by M0rtgage** [comment]
p.s. who the fuck said im not going to fix wiki after this?

**Comment by park66665** [comment]
Please be friendly. My wall of text would have not happened if you had the courtesy. People suggesting things aren't here to slit your throat. If you have to decline them, please decline *politely*, and please try to understand *why* the suggestion was made.

Nor every people playing SS13 plays (or should play) exactly the same way you do. I, for example, almost always use right-click context menu, and resort to Alt-click only when I really have to.

**Comment by M0rtgage** [comment]
I get that, tbh a sizable part of the discussion that got me pissy isn't up here but I'm just surprised at the pushback ngl.

**Comment by Archanial** [comment]
@M0rtgage fix CL

**Comment by M0rtgage** [comment]
Me monke how do I fix cl

**Comment by M0rtgage** [comment]
Also y do I, github says muh only neutral check is "diffs", and that the only reason it's not merged is due to no review yet.

**Comment by Archanial** [comment]
> 
> 
> Me monke how do I fix cl

make it
add: thing you've added

**Comment by MrLostman** [comment]
bee station people

**Review by ike709 — CHANGES_REQUESTED** [review]
Fix the CL.

**Comment by Rukofamicom** [comment]
We had gas miners before, they were reverted due to causing massive server issues. What's different now?

**Comment by M0rtgage** [comment]
Well for starts im p sure fastmos made it way less laggy. Also meta has these and I essentially copied meta here so I'm p optimistic bout it. I think a testmerge would go a long way with this just in case tho.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by zeskorion** [comment]
Only put the miners in gasses required to live

**Comment by M0rtgage** [comment]
The few big reasons every gas has a miner is so that if admin fuckery/ idiots break a gas chamber a robust atmos can go out and fix it, without a retarded amount of plasma atmos tech is just axe assistant why I even made this pr. Another is to encourage experimentation among noobs, as most gasses interacts with fusion it allows noobs to try various amounts of said gas while still being able to give it to people who ask for it. Tbh with old fusion I get not having gas miners but current fusion makes you use dumb amounts of plasma. Sry for ramble but TLDR other gas miners good until fusion gets "fixed" again. Also the same guys nerfing death rads so plz lemme have this

**Comment by ike709** [comment]
I don't like your attitude and I'm not convinced this is actually a good change. Atmos already has near-infinite gas, they don't need actually-infinite.

**Pull request closed without merging**
