### PR TITLE
fix spacemanDMM build error

### PR DESCRIPTION
**Pull request by Tsar-Salat**
## About The Pull Request

how did it even happen

## Why It's Good For The Game

local build error bad (though it didnt cause anything to fail ig)

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

not applicable

</details>

## Changelog
:cl:
fix: resolve build error
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — APPROVED** [review]

**Comment by EvilDragonfiend** [comment]
ohh, I see.. I didn't know it showed build error. sorry lol
no point of keeping 24h rule for this one, right?

**Review by EvilDragonfiend — APPROVED** [review]

**Comment by EvilDragonfiend** [comment]
btw, is line 180 alright?

**Comment by Tsar-Salat** [comment]
> btw, is line 180 alright?

It wasn't problematic on local.

I'll be honest. I'm clueless why SpacemanDMM hates the multiline comments, only that once I changed these two lines, the error stopped appearing.

Just putting up the PR because the error was getting annoying, I am not experienced with it.

**Comment by EvilDragonfiend** [comment]
> > btw, is line 180 alright?
> 
> It wasn't problematic on local.
> 
> I'll be honest. I'm clueless why SpacemanDMM hates the multiline comments, only that once I changed these two lines, the error stopped appearing.
> 
> Just putting up the PR because the error was getting annoying, I am not experienced with it.

I think I got why it blamed that so, but let's be consistent. would you delete the ! too please?

**Comment by EvilDragonfiend** [comment]
well, I am going to merge this. it's annoying.

**Pull request merged**
