### PR TITLE
removes botanies ability to turn everyone into a simplemob with no way of getting back

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request

(hopefully) removes advanced mutation toxin from the strange seed pool

## Why It's Good For The Game

removes fetish content
nerfs botany
stops me from turning into a slime every other fucking round
idedplznerf

## Changelog
:cl: Jimmy Brickets
del: Advanced mutation toxin from the strange seed list, and any other way to duplicate it (outside of xenobio)
/:cl:

### CODE REVIEW

**Comment by ItsTisme** [comment]
>removes fetish content

bruh

**Comment by super12pl** [comment]
> > removes fetish content
> 
> bruh

gotta make maintainers merge it somehow

**Comment by ToasterBan** [comment]
> > removes fetish content
> 
> bruh

I added it as a joke but someone probally has a fetish for turning into a slime

**Comment by USB3pt0** [comment]
Advanced mutation toxin is far too important for freeing the skeleton inside to be removed.

**Comment by leestriter** [comment]
I mean its rng, pretty unlikely for a botanist to get it. But its easy to get it consistently from xenobio. Also, admins should be banning botanist that just go around turning people into slimes anyway.

**Comment by Glcbitj** [comment]
ided

**Comment by leestriter** [comment]
I've thought on this a lot more. and actually I think this pr is a good idea. Getting turned  into a simple mob with no way to turn back is not fun.

**Comment by eeSPee** [comment]
> > > removes fetish content
> > 
> > 
> > bruh
> 
> I added it as a joke but someone probally has a fetish for turning into a slime

Guilty.

But maybe make it a disease, the same way gondola works?

**Comment by zeskorion** [comment]
> But maybe make it a disease, the same way gondola works?

it is a disease already, cured by frostoil. nerfing reagent disease administration'd fix this better whilst letting botnis still use this as an ingredient





> > > removes fetish content
> > 
> > 
> > bruh
> 
> I added it as a joke but someone probally has a fetish for turning into a slime

yeah there are de-





> > I added it as a joke but someone probally has a fetish for turning into a slime
> 
> Guilty.

case in point

**Comment by ToasterBan** [comment]
> > > > removes fetish content
> > > 
> > > 
> > > bruh
> > 
> > 
> > I added it as a joke but someone probally has a fetish for turning into a slime
> 
> Guilty.
> 
> But maybe make it a disease, the same way gondola works?

it is a disease, the cure is frost oil

I wonder what department.normally is able to create frost oil

**Comment by ToasterBan** [comment]
> Advanced mutation toxin is far too important for freeing the skeleton inside to be removed.

botany shouldn't have access to such powerful mutation toxins in the first place

**Comment by eeSPee** [comment]
> botany shouldn't have access to such powerful mutation toxins in the first place

Xenobio has far more OP shit, to be bothered with this.

**Comment by yyzsong** [comment]
> Advanced mutation toxin is far too important for freeing the skeleton inside to be removed.

pretty sure skeletong toxin is available as its own thing in Strange Seeds



> > botany shouldn't have access to such powerful mutation toxins in the first place
>
> Xenobio has far more OP shit, to be bothered with this.

I mean xenobio can't exactly make portable mutation toxin autoinjectors that are created 13 at a time in literal minutes
or store 100 of them in a single tiny-sized bag

**Comment by zeskorion** [comment]
> > Advanced mutation toxin is far too important for freeing the skeleton inside to be removed.
> 
> pretty sure skeletong toxin is available as its own thing in Strange Seeds

No. I removed that

**Comment by sircope** [comment]
this is outrageous, it's unfair! it will break the upcoming balance change of moving botany to xenobio!

**Comment by ToasterBan** [comment]
ahem, code jannies, this is a nerf??? why no speedmerge?

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
