### PR TITLE
Reverterino Soft Crit

### PR DESCRIPTION
**Pull request by Sinestia**
## About The Pull Request

Thankfully no wiki changes are needed because the original PR didnt edit the wiki hehehehehehe bee coders be like~ 

Reverts the new new soft crit system in #2997 

I didn't test too much also I should really review the revert results but it was functional in the 3 minutes I did test. 

## Why It's Good For The Game

I like the ideas behind new new soft crit so someone else has to argue this  

then again its pretty gimped now and bee players are gonna be bee players

## Changelog
:cl:Froststahr
del: The new soft crit system has been reverted
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
I dont remember being able to use you hands

**Comment by Sinestia** [comment]
> 
> 
> I dont remember being able to use you hands

fair that was more a bacon removal

**Review by Archanial — APPROVED** [review]
based

**Comment by PowerfulBacon** [comment]
The is concious change is a good one and one that should be retained imo

**Review by PowerfulBacon — APPROVED** [review]

**Comment by eeSPee** [comment]
My biggest grievances with soft crit:
* You can still talk when crit.
* It's standard for SS13 that crit people to be horizontal. Many new players don't know how to tell a person is in crit.

**Pull request merged**
