### PR TITLE
Baytiles without the replacements

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
see #486.
Credit again to baystation and whoever designed the tiles, they look good. I just didn't resprite the already existing tiles, merely added tiles that bay has and bee doesn't.

## Why It's Good For The Game
Adds more variety for mappers, at the very least.

## Changelog
:cl:
add: Added baytiles that weren't in before
imageadd: new sprites for tiles
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
I mean, there are still some modifications but the ones you modified are probably fine.

**Comment by qwertyquerty** [comment]
Also you haven't made any subtypes for these so mappers will have to manually set icon states to use em

**Comment by MarkSuckerberg** [comment]
Yeah I left one or two replacements that I believe still have enough texture or whatever, and I probably can add subtypes at some point.

**Comment by MarkSuckerberg** [comment]
Also the stairs modification is just me adding the directional sprites since they previously didn't exist

**Comment by qwertyquerty** [comment]
I'd like the subtypes before this is merged.

**Comment by MarkSuckerberg** [comment]
Hold up a minute I never pushed floor.dmm, I'm stupid

**Comment by MarkSuckerberg** [comment]
there, subtypes and floor tile obj sprites

**Comment by qwertyquerty** [comment]
The map uses undefined types

**Comment by MarkSuckerberg** [comment]
Uhm, hopefully fixed what you were talking about

**Comment by qwertyquerty** [comment]
You must put newlines between type declarations.

**Comment by MarkSuckerberg** [comment]
apologies, it seemed everywhere else that subtypes were grouped together like that, but I'll fix it

**Comment by MarkSuckerberg** [comment]
there, done

**Review by qwertyquerty — APPROVED** [review]

**Review by ike709 — APPROVED** [review]

**Pull request merged**
