### PR TITLE
Adds Psyphoza to TGUI Prefs

### PR DESCRIPTION
**Pull request by DrDuckedGoose**
## About The Pull Request

image

Testing for psyphoza, works with the preference change

https://github.com/BeeStation/BeeStation-Hornet/pull/9501

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
Wake up babe, it's conflict season.

**Comment by DrDuckedGoose** [comment]
don't need this anymore

**Comment by Tsar-Salat** [comment]
`Adds Pysphoza to TGUI Prefs`

Atleast I dont feel bad anymore about always mispelling the name haha 😄

**Comment by DrDuckedGoose** [comment]
> > Adds Pysphoza to TGUI Prefs
> 
> Atleast I dont feel bad anymore about always mispelling the name haha 😄

We're taking Kat to HR for this mistake

**Pull request closed without merging**
