### PR TITLE
replaces the glass in the gulag security outpost with reinforced plasma glass

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

title

## Why It's Good For The Game

Alternative to #2355 , makes the gulag useful.

## Changelog
:cl:
tweak: replaces the glass in the labor camp with reinforced plasma glass.
/:cl:

image

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
They hated him becase he told them the truth.

**Comment by PowerfulBacon** [comment]
The security post interior ones don't really need plasma glass, prisoners shouldn't be in there only security

**Comment by ghost** [comment]
> The security post interior ones don't really need plasma glass, prisoners shouldn't be in there only security

but it looks odd if it isn't all the same glass.

**Review by zeskorion — APPROVED** [review]

**Comment by Moccha-Bee** [comment]
mfw this was reverted and there is no plasma glass in gulag 
image

**Pull request merged**
