### PR TITLE
BlackBox Fits in Backpack

### PR DESCRIPTION
**Pull request by BetaCentari**
## About The Pull Request
Makes the blackbox fit in backpacks

## Why It's Good For The Game
Allows traitors to conceal the blackbox, a very difficult item to steal let alone hide, on their person. 

## Testing Photographs and Procedure

Capture

<details>
<summary>Screenshots&Videos</summary>

</details>

## Changelog
:cl:
tweak: Tweaked size of blackbox
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
Yeah, always thought it was stupid that a little station blackbox couldn't fit in a bag.

**Review by itsmeow — CHANGES_REQUESTED** [review]
It should fit in a bag, but it should be HEAVY

**Comment by BetaCentari** [comment]
> It should fit in a bag, but it should be HEAVY

Those are the same thing according to var flags. Weight Class determines whether something can fit inside a bag or not.

**Comment by itsmeow** [comment]
There is one between bulky and normal, is there not?

**Comment by ivanmixo** [comment]
Yeah encourage stealthy traitor, taking any possible nuance out of the objective.

**Comment by itsmeow** [comment]
good point though, we don't really want to enable stealthing so much

**Comment by FriendlyContractor** [comment]
Entire point of black box objective is that it is bulky and cannot be easily concealed. You should remove it rather than do a full circle and make it possible to put in in storage. Original PR -  #https://github.com/BeeStation/BeeStation-Hornet/pull/3517

**Comment by EvilDragonfiend** [comment]
I think the blackbox was meant to be used by bluespace compresser which is traitor item or find another way to conceal it.

**Comment by Fronsis** [comment]
I mean, the argument of ''stealthing traitor'' doesn't apply too much, most of th  traitors just teleport in there, grab it and dip, very few go as far as to make an explosion just to grab it and if it's done on a +1hour long shift they can just stuff it on a BS Bag and call it a day. Otherwise it just forces the traitor to go on a pod with the blackbox, i've encountered a few lockers that randomly had a BB inside, put by the traitors on there to retrieve later.

However a  good **alternative** that i can think off that could be interesting is if the blackbox steal required an item to be able to be put on a bag,  kinda like how nuke core and SM shard have their own box roundstart, you could say it could contain ''A one-use BS Compressed designated to only shrink NT SS13 BlackBox'' and they can carry it around, you can even go as far as to add ''be aware the BS Compressed BlackBox version is very experimental and it will make you walk as i you were carrying something heavy''(duffelbag slow for example), make sure that the BlackBox recorder-holder can catch prints from the forensic scanner(it most likely detects prints, unsure) and bam, doable for both parts to do their thing.

**Comment by BetaCentari** [comment]
I'm from NSV. And this was a suggestion from one of the players. This was a formality for NSV, it needs to be either approved so we can downstream it or denied so the PR can be allowed on our server. I appreciate the formality.

**Comment by Fronsis** [comment]
Fair enough, however i still think it's a discussion worth having so i appreciate the pr

**Pull request closed without merging**
