### PR TITLE
Removes patreon lock on species

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Removes the patreon lock on species.

## Why It's Good For The Game

The PR itself bought some coding issues in the implementation, and Patreon lock on species shouldn't be a thing, even on a species disliked by the majority of people (in my opinion).

Additionally, the PR itself went around most of the standard procedures for merging, the vote was only 4 hours long so a lot of people (myself included) didn't even have a chance to see the PR was made, and it was merged by the PR creator.

## Changelog
:cl:
del: Removed patreon lock on species.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Github damn it

**Comment by ghost** [comment]
Now this, this is cringe

**Comment by thelaughingbomb** [comment]
It was inevitable

**Comment by park66665** [comment]
> 
> 
> It was inevitable

Indeed

**Comment by qwertyquerty** [comment]
The changes to make it configurable are coming later today. Hold off on merging this as we can still use the framework, and if we dont wan't the change we can turn it off in the config

**Pull request closed without merging**
