### PR TITLE
Balance Power Usage

### PR DESCRIPTION
**Pull request by qwertyquerty**
## About The Pull Request

In response to DurrHurrDurr's want for a power usage curved with upgrades. This aims to increase power usage across advanced machinery that makes the game a lot easier or more simplified. The idea is that as the station becomes more advanced, engineering will have to pump out more power to support it, actually giving a reason for complicated engine setups.

Basic list of things affected so far, and I'd love suggestions for things to edit.

- Sleepers use power when you inject chems
- Cloners use more power the more upgraded they are
- Portable turrets use more power
- Cryo cells use power at all, and it correlates with their efficiency
- Gas miners use more power
- All plumbing machinery uses more power
- Emitters use more power
- Nanite chambers use more power
- Autodoc
- Mass Driver
- Recylcer
- Stasis Beds
- Rechargers
- Teleporters

## Why It's Good For The Game

Balance is good and it's good to have a reason to do things at all.

## Changelog
:cl:
balance: Power usage gameplay difficulty curve
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
Nice

**Comment by PowerfulBacon** [comment]
I really like this idea, needs to be well communicated to the engineers though and have an overall good balance or I can see this being confusing. Like how factorio has their power graphs where it is easy to tell usage is going up rather than output going down.

**Comment by qwertyquerty** [comment]
> I really like this idea, needs to be well communicated to the engineers though and have an overall good balance or I can see this being confusing. Like how factorio has their power graphs where it is easy to tell usage is going up rather than output going down.

It's pretty easy to see this using the power monitoring console

**Comment by Kerbin-Fiber** [comment]
Cell Chargers should be added too.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by bloons3** [comment]
> Cell Chargers should be added too.

TG had some recent PRs about cell chargers not conserving energy. Should probably look at their solution to it.

**Pull request merged**
