### PR TITLE
misc Kilo fixes

### PR DESCRIPTION
**Pull request by spockye**
## About The Pull Request
fixes the following:
missplaced disposals
missplaced fire cabinets
missplaced station CHUNKS
missplaced zoning
missing zoning
redundant wiring
missing wires
changes the camera version in virology containment from Medsec to Viro pen. 
moves the ai upload tube camera

## Why It's Good For The Game
errors = bad

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

</details>

## Changelog
:cl:
add: KiloStation: Added grilles on some walls in space south of the station
fix: KiloStation: Fixed some incorrect nearstation areas in space south of the station
fix: KiloStation: Fixed maints above chapel being incorrectly labelled as Chapel Office
del: KiloStation: Removed Starboard Bow solar grilles and nearstation area classifications
fix: KiloStation: Fixed incorrect nearstation areas in space by xenoarch
tweak: KiloStation: Moved cam in room between upload transit and captain's office
tweak: KiloStation: Moved floating extinguisher cabinet in dorms
del: KiloStation: Removed extinguisher cabinet behind washing machine in dorms
tweak: KiloStation: Moved camera in virology
del: KiloStation: Removed useless cable dead end in medical maints
del: KiloStation: Removed useless cable dead end in perma
tweak: KiloStation: Connected cable dead end between vault and botany maints
del: KiloStation: Removed duplicate scrubber underneath rack in xenoarch
del: KiloStation: Removed random disposal pipe in departures
fix: KiloStation: Fixed disconnected power cables to window grilles in xenobio
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
I think your change logs should be descriptive than it is. Like `del: kilo station - misplaced wires`

**Comment by spockye** [comment]
there are currently multiple places with wires randomly placed around, or wires missing to complete the loop, some examples would be :
**
image
**

image

image

**Comment by dog132-ss13** [comment]
In my defence I will say that those trailing wires are Kilo's signature run-down style which made me spare their lives, but yeah those missing cables that don't complete loops are an oopsie on my part.

**Comment by Fronsis** [comment]
Could this change include the missplaced cameras? Medbay security post shows a virology one(zams oopsie) and Ai upload transits shows a weird command door very zoomed in

**Review by PestoVerde322 — COMMENTED** [review]
Please update your CL to point exactly what changed thanks.

**Comment by spockye** [comment]
quick refresh

**Comment by itsmeow** [comment]
MDB is mad at our repo because I did an oopsy and made a huge PR without MDB ignore

**Comment by itsmeow** [comment]
@spockye Push an empty commit please

**Comment by itsmeow** [comment]
My review: why did you remove the grilles around the northeast (starboard bow) solars? I suppose they're already protected by the asteroid, so fair if that's why

CL (now possible thanks to MDB-DMM!):

Added grilles on some walls in space south of the station
Fixed some incorrect nearstation areas in space south of the station
Fixed maints above chapel being incorrectly labelled as Chapel Office
Removed Starboard Bow solar grilles and nearstation area classifications
Fixed incorrect nearstation areas in space by xenoarch
Moved cam in room between upload transit and captain's office
Moved floating extinguisher cabinet in dorms
Removed extinguisher cabinet behind washing machine in dorms
Moved camera in virology
Removed useless cable dead end in medical maints
Removed useless cable dead end in perma
Connected cable dead end between vault and botany maints
Removed duplicate scrubber underneath rack in xenoarch
Remove random disposal pipe in departures
Fixed disconnected power cables to window grilles in xenobio

**Comment by itsmeow** [comment]
Also undo the dirt please

**Review by itsmeow — APPROVED** [review]

**Review by PestoVerde322 — APPROVED** [review]
Everything seems good to go, approved.

**Pull request merged**
