### PR TITLE
Changes Dynamic Config, round 2.

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
Raises the following dynamic threat levels per admin discussion:
Wizard 20->35 (Wizard's weight has been increased to make it more likely to roll at high threat levels.)
Nukies 20->30
Blob 10->20
Xenos 10->20
Cult 20->25

Now using the config and not the base code.

## Why It's Good For The Game
Admins decided that round ending and team antags should be higher cost. Additionally, following internal discussion, it has been decided that Wizard the mode will not be returning.

## Changelog
:cl:
config: The cost of the following rulesets for Dynamic have been increased: Wizard, Nuclear Operatives, Blob, Xenomorphs, Blood Cult.
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
but why would you open a separate pr to accomplish the same thing

**Comment by Ivniinvi** [comment]
> but why would you open a separate pr to accomplish the same thing

Because it scraps all of the actual editing I did in the first PR and starts again, because I did them in the wrong place.

**Comment by BrumalLake** [comment]
it gets squashed anyways and that's escapism from someone requesting changes and gets rid of the history
you can hard reset to master and force push instead

**Comment by Ivniinvi** [comment]
I don't get why you're so annoyed by how I organize my pull requests. I had no intent to hide the changes requested (which was the whole point of this new PR, to address the requests for changes). If anyone would like to view the previous PR, it is linked here: #5377. (In which you call me boring, and say that I'm "sucking up to admins".)

**Comment by BrumalLake** [comment]
your wigftg says that admins said so and i don't see why else you would want this merged other than to suck up to them

**Comment by Ivniinvi** [comment]
> your wigftg says that admins said so and i don't see why else you would want this merged other than to suck up to them

I was in the meeting where these changes were discussed, and proposed some of them myself.

**Comment by PowerfulBacon** [comment]
Weight and cost are completely different, this PR is absolutely insane and will (probably) mess up the dynamic config a lot.

Weight - The chance of the antag spawning
Cost - How many antags can spawn per round.

By increasing the cost you make it so that midrounds will be rarer and having other things spawn on that gamemode along side it will be rarer. This alone will not reduce the spawn rate, only the midrounds and traitors that can spawn along side it.
By increasing the weight you make the antag spawn more commonly, which is why I think its kind of insane that you made wizard weights 5 from 1.

Cult, nukies and wizard were already the heighest cost at 20, their weight should be lowered and cost maybe upped to 25 or 30 on wizard due to them not being very compatable with other antags.

Midrounds generally don't get a lot of cost left over so blob and xenos will likely become insanely uncommon with a cost of 20. I guess thats a good thing but it because almost nothing when factoring in that other midrounds also take from the cost. (and afaik dynamic gets a set cost at the start rather than builds it over time which is kinda dumb imo)

> Admins decided that round ending and team antags should be higher cost.

Just cause admins said to do it doesnt make it a good idea lol, section should be used to show that you understand what you are doing and that you know how this will impact how it functions.

**Comment by PowerfulBacon** [comment]
In my opinion wizard should be brought back into rotation and removed from dynamic instead.

**Comment by Ivniinvi** [comment]
> By increasing the cost you make it so that midrounds will be rarer and having other things spawn on that gamemode along side it will be rarer. This alone will not reduce the spawn rate, only the midrounds and traitors that can spawn along side it.
> By increasing the weight you make the antag spawn more commonly, which is why I think its kind of insane that you made wizard weights 5 from 1.

The point of this was to make it require a high threat level and also prevent Wizard and Blob and Xenos at the same time. Clockwork Cult is at 35 threat and 3 weight, and it hasn't rolled in at minimum the past two weeks (during which time I've overseen multiple high threat rounds, 93 threat and 87 threat among them), in which time there were TEN midround wizard injections, (not even roundstart) and to my knowledge zero clockwork cult occurrences. I am waiting on someone with advanced logging access to confirm this statistic (and may post a fancy graph). The point is to:
A. restrict wizard to high threat rounds (cost 35 means minimum ~60 threat budget total, 70 for roundstart)
B. Severely diminish stacking multiple high impact antags. Cost 35 means that Wizard and Nukies and Xenos is going to be a very rare occurrence, if at all.
C. Ensure that Wizard isn't elevated to a legendary level of rarity. At weight five, there's a higher chance of wizard being rolled when the threat level allows it.

> Cult, nukies and wizard were already the heighest cost at 20, their weight should be lowered and cost maybe upped to 25 or 30 on wizard due to them not being very compatable with other antags.
> 
> Midrounds generally don't get a lot of cost left over so blob and xenos will likely become insanely uncommon with a cost of 20. I guess thats a good thing but it because almost nothing when factoring in that other midrounds also take from the cost. (and afaik dynamic gets a set cost at the start rather than builds it over time which is kinda dumb imo)

Dynamic does roll a threat budget at the beginning determined by a special sauce bell curve, and splits it into roughly half of the budget for roundstart, and half for midround, donating the leftovers from roundstart to midround (generally less than 8 threat). Some but not all midrounds take from the threat, for example Ninjas and Space Dragons are rolled as normal, and if they roll within a certain time window, will be added without affecting the budget. Blobs and Xenos will be more common than Wizard currently is (that being, ten times in the past two weeks), as they have higher weights, at 4 and 3 respectively. _Also, xenos can spawn from supercruise without affecting the budget at all, and this doesn't even mention the Supercruise Changelings or Insane VIPs._

> > Admins decided that round ending and team antags should be higher cost.
> 
> Just cause admins said to do it doesnt make it a good idea lol, section should be used to show that you understand what you are doing and that you know how this will impact how it functions.

By that I meant that I brought it up in a meeting, and would say that we talked a bunch about how the weights are now vs what we want them to be.

> In my opinion wizard should be brought back into rotation and removed from dynamic instead.

Per Crossed this is not an option.

**Comment by qwertyquerty** [comment]
:key:

**Comment by PowerfulBacon** [comment]
I'll put a 🔑 in too, this is absolutely not the way to go about doing the changes that its seemingly intended to do. I don't believe that what the PR does is the same as what you want it to do.

**Pull request closed without merging**
