### PR TITLE
Nullcrate **fun**

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
The Syndicate is tired of their gear falling into Nanotrasen hands. When  NULL_ENTRY crates are ordered, the Lone Operative event becomes slightly more likely.

Additionally, the syndicate may send their most deadly enforcers inside the crates instead of loot. The first crate has a 0% chance for this, but every time crates are ordered, the chance goes up by 1% per crate. The chance applies to each item, but onlly one beepsky can spawn per crate, and once one spawns, the crate stops spawning items

## Why It's Good For The Game
Improve don't remove: solves the nullcrate party issue without removing the crates or the utility they give to individual antagonists.

also, a way to get a General Beepsky without needing 2.25 uplinks

## Changelog
:cl:
balance: Nullcrates now have a downside other than an easily-gameable cost, which can also be used against the crew by a creative traitor
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
sorry for the mess of commits, made a dumb move and did shit in master by mistake again

**Comment by triplezeta** [comment]
this has already been brought up in the discord, but this seems awfully weaponizable by cargo. Just wrap crate, tag with desired destination using the deliveries system, and then send it to your location of choice. Tada, very angry and very hard to kill esword-wielding beepsky is now in the warden's office, or medbay, or robotics, or anywhere you want to send an esword wielding beepsky.

**Comment by zeskorion** [comment]
> this has already been brought up in the discord, but this seems awfully weaponizable by cargo. Just wrap crate, tag with desired destination using the deliveries system, and then send it to your location of choice. Tada, very angry and very hard to kill esword-wielding beepsky is now in the warden's office, or medbay, or robotics, or anywhere you want to send an esword wielding beepsky.

they would need to open it up first.

and this being a possibility is an intent; but you don't KNOW  a beepsky is in there unless you order 10 nulls, and you cant close it up once you open it

**Comment by dinnerwoerror** [comment]
zesko, what in the seven hells are you smoking, because i want some of it too

**Comment by zeskorion** [comment]
note: there is another way this can be implemented, where the beepsky is calculated during item rolling, so some items still spawn in the crate with the beepsky, meaning you can still get items, you just gotta fight a robot for it

**Comment by zeskorion** [comment]
Gonna change this to the aforementioned method when i get home. Its a bit funner

**Comment by zeskorion** [comment]
changed the mechanism 3 days later

**Comment by qwertyquerty** [comment]
Fix conflicts @zeskorion

**Comment by zeskorion** [comment]
> Fix conflicts @zeskorion

Those'd not happen if you didnt leave the pr sitting for 2 weeks

**Comment by qwertyquerty** [comment]
You still have to fix them

**Comment by zeskorion** [comment]
> You still have to fix them

yeah i know.. this should do it

**Comment by qwertyquerty** [comment]
I still am not sure how I feel about this balance-wise, but I guess I'll let the wise players decide with a vote

**Comment by zeskorion** [comment]
changing the mechanism slightly after feedback so the chance resets and increases slightly whenever a beepsky spawns, making beepskys harder to use offensively

**Comment by qwertyquerty** [comment]
Looks like some drugs changes snuck in

**Comment by zeskorion** [comment]
> Looks like some drugs changes snuck in

fixed it

**Comment by qwertyquerty** [comment]
There's still some bath salts and stimulum stuff

**Comment by qwertyquerty** [comment]
@zeskorion

**Comment by zeskorion** [comment]
> @zeskorion

ima close and re-pr this cuz it's sat so long

**Pull request closed without merging**
