### PR TITLE
Replaces all windows in the gulag with walls

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Replaces the windows in the gulag medbay and security outpost with walls and rwalls

## Why It's Good For The Game

You shouldn't be able to break out of there so easily.
## Changelog
:cl:
fix: fixed the gulag to be actually secure.
/:cl:

### CODE REVIEW

**Comment by BeloneX** [comment]
image

**Comment by ghost** [comment]
image

**Comment by ghost** [comment]
if any maintainers dont like it an alternative is to replace the windows with reinforced plasma windows as @Wilchenx  suggested

**Comment by eeSPee** [comment]
Yeah but on the other side, there's supposed to be a loophole/escape option from lavaland.

**Comment by ghost** [comment]
> Yeah but on the other side, there's supposed to be a loophole/escape option from lavaland.

on the northern most section of the prison camp side of lavaland there is a only a single laval tile seperating the prison side from the main lavaland one, you can survive that with some luck.

alternativley. if the fire extinguisher hasnt been snagged from the mining base you can quickly run trough the few tiles of lava and extinguish yourself.

or ask a miner to break you out, there are tons of ways to escape the prison camp that dont involve breaking a window, but i guess people got used to the window and forgot anything else existed.

**Comment by PowerfulBacon** [comment]
Breaking out was pointlessly easy before

**Comment by PowerfulBacon** [comment]
Put to vote

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
Failed the vote unfortunately, the gulag shall remain useless

**Comment by MCterra10** [comment]
Lmao, the democratic experience:tm:

**Pull request closed without merging**
