### PR TITLE
Removes Skewium

### PR DESCRIPTION
**Pull request by francinum**
## About The Pull Request

Having a chemical that causes meta-effects like client crashes is bad design.

## Why It's Good For The Game

Don't intentionally crash clients.

## Changelog
:cl:
del: Skewium has been removed.
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
Bro just make it unobtainable so i can use it in the exolocomotive xenomitosis replacement later

**Comment by ghost** [comment]
> Bro just make it unobtainable so i can use it in the exolocomotive xenomitosis replacement later

God no, now I especially want it removed because of what you said.

**Comment by Archanial** [comment]
> 
> 
> Bro just make it unobtainable so i can use it in the exolocomotive xenomitosis replacement later

disease that crashes your game
very good idea

**Comment by bloons3** [comment]
> > Bro just make it unobtainable so i can use it in the exolocomotive xenomitosis replacement later
> 
> disease that crashes your game
> very good idea

It's an IC chemical that OOC kills you

**Comment by jlsnow301** [comment]
(Genuine curiosity) when does this crash games? I've thought it was broken for some time. Hasn't been working in botany at all for me.

**Comment by PowerfulBacon** [comment]
Made my screen go black and froze my entire computer, heard of someone having to restart their entire PC after getting this.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
Goodbye old friend

**Comment by St0rmC4st3r** [comment]
Bruh

**Comment by jlsnow301** [comment]
So is rotatium aok or

**Comment by Archanial** [comment]
salute

**Pull request merged**
