### PR TITLE
Adds enhanced chameleon bowman, glasses and gloves to traitor uplink

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
For 2 TC each you can now buy a Chameleon Bangproof Headset (flashbang proof) or Chameleon Flashproof Glasses (welding flashes proof), and for 1 TC you can get Chameleon Combat Gloves (fire and shock resistant). 

## Why It's Good For The Game
High utility items for various traitor activities, very useful if you're unable or unwilling to procure the non-chameleon versions of these items especially. 

## Changelog
:cl:
add: Adds 3 new chameleon items to the traitor uplink: Chameleon Bangproof Headset, Chameleon Flashproof Glasses and Chameleon Combat Gloves. 
tweak: Chameleon plasmaman envirohelmet is no longer permanently flashproof.
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — COMMENTED** [review]
3 TC each is kind of expensive in my opinion, especially since the entire set of chameleon gear costs 2 TC. I would only really consider buying them if they were 1 TC each, and the glasses + bowman had 1 more bang/flash protection than they needed so they work for all species.

**Comment by VictorVow** [comment]
I'll bump up the protection, forgot about the other species' weaknesses. 

Normal chameleon gear lacks bangproof/flashproof/insuls, so it can't be compared to the plain chameleon kit in my opinion. Chameleon Flashproof Glasses and Bangproof Headset are the kind of items which let you escape or win an encounter by having an immunity someone didn't expect, so those I don't think should be lower than 2 TC. 

The Chameleon Combat Gloves could arguably go as low as 1 TC though, since you can get the Syndicate Toolbox for 1 TC also, so you'd be trading the Syndicate tools for making the combat gloves have chameleon.

**Comment by PowerfulBacon** [comment]
If you wear a helmet you can't see if someone is wearing glasses or headset anyway, 2 TC for flash and bang protection without them knowing you have them is a decent deal, better than 6 TC in my opinion

**Comment by ghost** [comment]
sec wont ever arrest you for wearing combat gloves.

**Comment by VictorVow** [comment]
What the hell, chameleon plasmaman helmet shouldn't be that robust. Normal plasmaman helmet has a welding visor at least rather than permanent flashproofing. Zesko...

**Comment by r1ks-iwnl** [comment]
This would encourage use of stamina weapons by sec and even lethals, so no more click antag with flash and win, this would make it a bit more fun and challenging for sec but im not so sure about it being chameleon.

**Comment by VictorVow** [comment]
- All species now sufficiently protected with flash or bangproofing.
- Chameleon plasmaman envirohelmet is no longer permanently flashproof. If someone wants to add in a welding visor to it later it should be okay balance-wise, but already it's an upgrade over plain chameleon kit due to the helmet being bangproof. 
- Prices adjusted to 2 TC each for headset or glasses, 1 TC for gloves.

**Comment by FortSumter** [comment]
Why not bundle the gloves together with the bowman and the glasses for 2-4TC? I don't feel like the gloves need to be a separate purchase, and would be in line with the other chameleon items. 
No-slips are 2TC and are arguably better because the only other way you get no slips is magnetic boots or galoshes which are obvious and slow you down. The items you are suggesting on adding are things any robust traitor can get without much trouble. Sec glasses and bowman from a checkpoint locker, and insuls from engineering. Granted you can't disguise them, but you also get the added benefit of the sec channel and to see your own wanted level all without having to spend 3TC.
The traitor who is unrobust enough to buy these items is the one that's going to be caught and disabled by sec. At this point I dont get why we don't just make a secret agent bundle that has agent card, chameleon kit, your PR, and maybe emag fro 10-15TC.

**Comment by VictorVow** [comment]
No-Slips are 3 TC not 2 TC so your price comparison is off. And I'm not adding free insuls to the existing cham kit which is already pretty robust for only 2 TC. 

Engineering rarely has spare insuls, you're usually going to have to rob someone for them. Robbing a sec checkpoint means possibly getting seen by security, crew or the AI. It's a risk getting caught, so this is a cheap, risk-free alternative. And once you get it anyway you need to wear an obvious mask or other paid chameleon gear to hide that you have them. Might not fit your spending preferences but many people who roll traitor aren't as robust or they just prefer a stealthier approach at times.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
