### PR TITLE
Nugget Smite

### PR DESCRIPTION
**Pull request by TheTrigg**
## About The Pull Request

Dismembers every limb. Kinda speaks for itself.

## Why It's Good For The Game

[Admins can do this to very naughty people.](https://cdn.discordapp.com/attachments/661715227452112932/729438027910217739/nice.mp4)

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
yes

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Add a check to make sure the target is actually a carbon, since its innevitable some smoothbrain (me) uses these things on borgs and ghosts.

**Comment by PowerfulBacon** [comment]
ay yo nevermind, I see it now in the list above

**Review by PowerfulBacon — APPROVED** [review]

**Comment by zeskorion** [comment]
dammit, i wanted to suggest making them flip and making it toss the limbs everywhere to be cooler

**Pull request merged**
