### PR TITLE
[Port] Security (SecHUD) Arrest Permissions \ Detective SecHUD Changes 

### PR DESCRIPTION
**Pull request by bloons3**
## About The Pull Request

- [x] https://github.com/tgstation/tgstation/pull/51600

Arrest option through SecHUDs is now only available to people with Security access (instead of Brig access), restricting it roundstart to Captain, HoS, HoP and Security Officers. Previously, roles such as Lawyer, CMO, Detective, etc; could set arrest status through SecHUDs.

Additionally, Security access is now also required to operate portable turrets (from Brig access).

---
~~Future: Give the Detective some nice gimmick items to use instead of SecHUDs~~
- [x] ~~https://github.com/tgstation/tgstation/pull/46891 - Add SpyGlasses~~
- [x] ~~https://github.com/tgstation/tgstation/pull/56883 - Turn the camera into an accessory~~
- [x] ~~https://github.com/tgstation/tgstation/pull/53355 - Merge the Det's Sunglasses into their Spy Glasses~~

See https://github.com/BeeStation/BeeStation-Hornet/pull/3973
## Changelog
:cl: 
del: Detective gets roundstart normal sunglasses instead of SecHUDs ~~at PubbyStation~~.
balance: Balanced access to arrest option through SecHUDs, now requiring Security access instead of Brig access.
balance: Balanced access to portable turrets, now requiring Security access instead of Brig access.
/:cl:

### CODE REVIEW

**Comment by ItsTisme** [comment]
I would think detectives could use the set arrest option still.

**Comment by Effemu** [comment]
yeah detective should keep it

**Comment by ta3370** [comment]
Detective's whole thing is figuring out who needs arrested and having somebody else do the arresting. Not being able to set them is a bit jank if even standard officers can.

**Comment by bloons3** [comment]
The Detective is meant to be an investigator for Security, not a foot soldier.

They recommend arrests, not make them.

> The detective's entire point is that they investigate crime scenes to figure out who should be arrested, not look at people who are already wanted and arrest/shoot at them. That's a security officer's role.

The Detective is _not_ a security officer with the best ballistic lethal gun on the station.



> I would think detectives could use the set arrest option still.

Detectives can still use their console to set people to arrest, this is to stop their _fieldwork_ of chasing criminals down and arresting them.

It's  the same reason why the detective doesn't have a security bowman headset, instead they just have a basic headset.

**Comment by VictorVow** [comment]
To reiterate the two big issues with removing detective SecHUDs I've mentioned elsewhere: 
1) **Detectives will be unaware of the criminal status of individuals standing next to them** e.g. murderer wanted for arrest in their sight and they don't even know it to be able to report it to an officer to go arrest them.
2) **Their ability to quickly adjust criminal statuses is being removed for no justifiable reason** e.g. they see suspicious individual, they mark them as Search and ask for an officer over comms to come here to search them. Or they set someone to Monitor who's acting suspicious and add a comment to their record before going to investigate for more info using forensics.

If Spyglasses are added they should either have SecHUDs built-in or they should be in addition to their SecHUDs.

**Comment by bloons3** [comment]
1. The detective will not start with secHUDs, instead they will start with shielded sunglasses. This does not prevent them from asking for SecHUDs from the Warden, HoS, or a Security Officer.
- This is to encourage them to play as a Detective, not as a Security officer with a lethal sidearm
- Arresting is the job of Security, investigating is the job of the Detective. The forensic analyzer starts in their locked cabinet and not Security for a reason.
2. Detectives are still able to mark people to arrest or investigate using the security console in their office or around the station.
- The issue with basing Sec HUD arrest access off of Brig Access is that many non-Security Officer jobs have that access. It wouldn't make much sense for the CMO or Brig Physician to be able to set people to Arrest nor remove them from Arrest.


---
https://wiki.beestation13.com/view/Detective
```The Detective's job is to investigate the remains of any crime, identify the perpetrator, and then ask Security to arrest them for you. That's right, you have limited security access because you're supposed to be an evidence collector and hunter of monsters, not a god damn beat cop or warden.```

---

**Comment by VictorVow** [comment]
> Arresting is the job of Security, investigating is the job of the Detective

Being aware of criminal statuses **is not arresting**. A Detective without a SecHUD can make random arrests all they want because removing their SecHUDs does nothing to solve that issue. If you instead remove their primary arresting tools - their police baton and cuffs - then that would actually have a meaningful impact on reducing arrests they make without having significant unrelated downsides.

The fact that this prevents them from recognising wanted criminals standing next to them hasn't been addressed. They're supposed to find evidence of a crime, update a criminal's security record yet then still be unable to visually detect their reported criminal later on doesn't make any sense. 

> The issue with basing Sec HUD arrest access off of Brig Access is that many non-Security Officer jobs have that access. It wouldn't make much sense for the CMO or Brig Physician to be able to set people to Arrest nor remove them from Arrest.

Similarly to Brig Physicians getting a new access level recently this instead shows that a new access level should be made for using SecHUDs. It doesn't make sense that a Detective should be prevented from updating a security record via a SecHUD if they can already update them at a console.

**Comment by bloons3** [comment]
> Similarly to Brig Physicians getting a new access level recently this instead shows that a new access level should be made for using SecHUDs.

The HoP console is already crowded, I don't see any reason to make it more crowded with a pretty much useless permission.

**Comment by DatBoiTim** [comment]
Listen, I do not like wide-sweeping access to sec and appreciate many of these PRs, but I agree with @Victor239 .

While Det _**cannot**_ carry out an arrest in most cases, updating and working around records and hud status is critical to their job. Additionally, security records and arrest status are a way to communicate suggestions of arrest, which can be backed up with documented evidence.

Perhaps making the sechuds a part of a choice beacon for Det, under a specific kit. Would work if you really don't want guaranteed roundstart access.

**Comment by DatBoiTim** [comment]
@bloons3 Can you review #4015 to ensure I'm not getting crazy with that sechud thing to ensure that design is palpable given your philosophy?

**Pull request closed without merging**
