### PR TITLE
Replaces kilostation with an absolutely excessive use of yellow decals

### PR DESCRIPTION
**Pull request by Tsar-Salat**
## About The Pull Request

Replaces with a the vast majority of yellow decals

## Why It's Good For The Game

Kilo can actually shine as a great small map now that it's 500% piss colored.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Screenshot 2024-09-18 112421

</details>

## Changelog
:cl:
add: Replaced KiloStation with KiloDecal
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
failed lint

**Comment by Geatish** [comment]
Finally some good shit

**Comment by Rukofamicom** [comment]
I'm not sure whether to tip my hat or tell you to kindly go fuck yourself.

Make this stable so we can TM it at least once as a joke.

**Comment by Tsar-Salat** [comment]
> I'm not sure whether to tip my hat or tell you to kindly go fuck yourself.
> 
> Make this pass checks so we can TM it at least once as a joke.

I will accept both. :>

**Comment by Tsar-Salat** [comment]
> Make this pass checks so we can TM it at least once as a joke.


well, the other got merged and this never got TM'd so...

oh well, it would have been funny.

**Comment by Rukofamicom** [comment]
It didn't get merged, I closed it. 
I cba to fix mapping conflicts, I'll just continue disconnecting whenever kilo rolls.

**Pull request closed without merging**
