### PR TITLE
Nerfs brain-related detection from medical stuff (analyzer, sleeper), Adds CMO-only health analyzer

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request

* Brain damage scan
Now brain damage should be more than 100 to detect abnormality

* Non-Health analyzer health scan
scan power 1. 100/1 = needs more than 100 brain damage to detect
Won't tell the list of a patient's trauma list anything
(i.e. nanite)

* Normal Health Analyzer
scan power 1.25.
100/1.25 = needs more than 80 brain damage to detect
Will tell you the list of "permanent" traumas

* Advanced Health Analyzer
scan power 2.
100/2 = needs more than 50 brain damage to detect
it will tell you the list of "permanent", and "lobotomy" level traumas

* Nanotrasen Neurotrauma Health Analyzer
scan power 5.
100/5 = needs more than 20 brain damage to detect (it still won't say the exact level of brain damage anymore)
it wIll tell the full list of a patient's trauma list.
CMO closet has this

* Sleeper
It will only say your brain is abnormal when your brain damage is damaged more than 80. 

## Why It's Good For The Game

Touch your patient with the device and instantly evaluate your patient that what you need to do for them is a kind of bad design for medical playing. They need to assume more than relying on a single broken tool.

I am expecting this PR can make more interactive RPs between doctors and their patients to hear which problem they have, not just doing a treatment instantly. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

new CMO analyzer. I am not good at sprite, so I hope someone can retouch it someday

--------

case:
brain damage 70
5 traumas to each cure level

image
image

normal analyzer
can scan perma

------------

image
image

advanced
scan scan perma and deep rooted

-----------

image
image

CMO
scan scan chemical-neurine one and severe level of surgery

</details>

## Changelog
:cl:
balance: Sleeper won't tell you your brain damage is damaged unless you have more than 80 brain damage
balance: Health Analyzers will not say the exact level of brain damage. It will only say 'your brain is abnormal' based on the brain damage scanning power that each analyzer has. 1 power will detect 100>damage, 2 power will detect 50>damage, 5 power is 20>damage.
balance: Non-health analyzer method health scan has 1 brain scan power (scans 100 damage), and can't detect any traumas
balance: health analyzer has 1.25 scan power (scans 80 damage), and can only detect permanent traumas
add: advanced health analyzer has 2 scan power (scans 50 damage), and can only detect perma-lobotomy level traumas
add: Nanotrasen Neurotrauma Health analyzer, and adds it to their closet, but also will tell you the full list of traumas. also, it has 5 scan power (scans 20 damage), and can detect the full list of traumas
imageadd: Nanotrasen Neurotrauma Health Analyzer sprite
tweak: Medical ERT now starts with CMO health analyzer
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I don't like the random chance to display, since it encourages just spamming the scanner a few times and seeing if any of them display abnormalities

**Comment by EvilDragonfiend** [comment]
> I don't like the random chance to display, since it encourages just spamming the scanner a few times and seeing if any of them display abnormalities

then maybe complete removal from the non-CMO analyzer, I guess

**Comment by bluezorua** [comment]
random chance bad, maybe do something like bay and add a full body scanner machine in medbay?

**Comment by EvilDragonfiend** [comment]
> random chance bad, maybe do something like bay and add a full body scanner machine in medbay?

I don't like "full" scanning one that can witness all solutions from it. and, yeah, I am going to remove random chance.

**Comment by EvilDragonfiend** [comment]
okay, I added normal analyzer to scan 'perma' traumas since it's not good to waste their time for what they can't cure.
analyzers can detect traumas based on its power and trauma's severity.

**Comment by FortSumter** [comment]
The health scanners I believe are based on the tricorders from star trek. Personally the scanners were never the part of medical I had a problem with; it's just about everything else.

There are too many medical staff jobs for the amount of work they get in a regular round, paramedics tend to show up to a murder in progress instead of helping to prevent deaths as intended and actively risk their lives fighting the murderer for the corpse of their victim, genetics majorly breaks game balance the way it's currently implemented, and the biggest problem of all is the way medical functions more like necromancy in the way they can bring someone back to life that's been dead OVER AN HOUR with relative ease.

You want to fix medical? I think there are bigger problems that should be addressed than nerfing the only useful medical tool normal crew can get.

**Comment by EvilDragonfiend** [comment]
> The health scanners I believe are based on the tricorders from star trek. Personally the scanners were never the part of medical I had a problem with; it's just about everything else.
> 
> There are too many medical staff jobs for the amount of work they get in a regular round, paramedics tend to show up to a murder in progress instead of helping to prevent deaths as intended and actively risk their lives fighting the murderer for the corpse of their victim, genetics majorly breaks game balance the way it's currently implemented, and the biggest problem of all is the way medical functions more like necromancy in the way they can bring someone back to life that's been dead OVER AN HOUR with relative ease.
> 
> You want to fix medical? I think there are bigger problems that should be addressed than nerfing the only useful medical tool normal crew can get.

Actually, It's related to RP side even, not only about the medical job. like, scan your patient, and do the treatment without hearing which problems they have. Well done doctor, you cured a patient.

**Comment by FriendlyContractor** [comment]
> There are too many medical staff jobs for the amount of work they get in a regular round.

Absolutely agree here. Antagonist/escalation policy( and rules overall) are at fault here explicilty banning antagonists from creating patients for the medical staff despite there being no other reliable source of injuries( sure we have random events but they are not guaranteed to fire and be dangerous and medical should have a steady flow of patients every round, otherwise what is the point of playing medical roles?)
> paramedics tend to show up to a murder in progress instead of helping to prevent deaths as intended and actively risk their lives fighting the murderer for the corpse of their victim.

Why does every character have remote health and location monitoring in what is essentialy murdery mystery game again ?
> genetics majorly breaks game balance the way it's currently implemented

Honestly i think genetics is not so bad compared to other things you can do. Would you expand on this topic ?
> the biggest problem of all is the way medical functions more like necromancy in the way they can bring someone back to life that's been dead OVER AN HOUR with relative ease.

Also fully agree with you here. In my opinion the best solution here would be to simply remove all means of bringing back person from the dead( IE when they can no longer be revived by defib). This would also make doctors job more interesting and exciting because of the time pressure and hard choices that would have to be made.

> You want to fix medical? I think there are bigger problems that should be addressed than nerfing the only useful medical tool normal crew can get.

You want medical fixed and complain about somebody trying to make it more interesting ?????

**Comment by 12Oreos** [comment]
Yeah this seems unnecessary, i could understand if it was a slow full body scanner in medbay though like others have said.

**Comment by FortSumter** [comment]
> Honestly i think genetics is not so bad compared to other things you can do. Would you expand on this topic ?

The most common mutations geneticists usually get are hulk, TK, X-ray, thermal vision, and space adaption. None of these have downsides and most can be taken along with others (Hulk + TK for example). Each and every one of these break game balance horrendously when distributed amongst the crew, and genetics has no reason not to. Hulk and TK are basically licenses to fail RP, the visions make it so there is nowhere you can escape and nowhere you can hide and when combined with TK give people the ability to harm or kill others from behind walls. Even space adaption breaks the game balance by allowing anyone to go space walking without a suit or fear the vacuum of space.

There should at the very least a crippling downside to taking these mutations, if we should keep them at all.

> Actually, It's related to RP side even, not only about the medical job. like, scan your patient, and do the treatment without hearing which problems they have. Well done doctor, you cured a patient.
I wanted to make more interactions between paitents and doctors from this.

The problem is that a lot of people who play med doctor are either inexperienced or suffer from some IRL mental disorders. I've seen some really shitty work in my time that almost goes beyond malpractice and into self-antag territory. There are also times where game bugs have caused what appears to be a medical problem and not being able to confirm that there is something medically wrong with your character will lead to more ahelps. I've also have had cases where I've been blinded and deafened and/or muted before, which makes it quite difficult to explain what the problem is. You also can't explain what your problem is when you're... y'know... dead.

It'd be more RP friendly at least for the staff themselves if stasis beds were removed and putting the patient under or at least restraining them was required to do significant surgeries, or do anything else than nerf the casuals tool of telling you what the fuck is killing you. I'd be more on board with this if you also did what others suggested and added the full-body scanner but until then all this does is unreasonably complicate the first step of treatment.

**Comment by itsmeow** [comment]
How does this affect The Obsessed trauma?

**Comment by EvilDragonfiend** [comment]
> How does this affect The Obsessed trauma?

You'll have hard time to identify now. Unless obsessed is changed, it still needs brain surgery. You just don't evaluate instantly.

**Comment by itsmeow** [comment]
Awesome. Obsessed shouldn't just be a *scan person* "Oh, VALID!!! FORCE SURGERY!!!"

**Comment by EvilDragonfiend** [comment]
I think we need more medical treatment methods for various diseases/wounds/traumas, and this will be changed later.

**Pull request closed without merging**
