### PR TITLE
Makes the sec beret have the same armor value as the helmet

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

removes snowflake armor stats on the beret

## Why It's Good For The Game

I don't know why this is even a thing, or why a beret has more brute protection than a helmet, alternative clothing should be purely cosmetic.

## Changelog
:cl:
tweak: tweaked the sec beret armor values to be the same as the helmet.
/:cl:

### CODE REVIEW

**Comment by eLeCtrOssSnake** [comment]
Makes 0 sense.

**Comment by PowerfulBacon** [comment]
Isn't the beret for only warden or hos? Or is it just in the vendor

**Comment by ghost** [comment]
> Isn't the beret for only warden or hos? Or is it just in the vendor

yes its in the sec uniform vendor

**Comment by ghost** [comment]
> Makes 0 sense.

you know what else makes 0 sense? literally everything in ss13

**Comment by yorii** [comment]
wow I always assumed it was worse than the helmet, I only wore it for style lol...

**Comment by zeskorion** [comment]
Tbh it should have way worse stats, especially for melee protection

**Comment by yorii** [comment]
Nah it's a SECURITY beret, they probably made it with durathread or something 😄

**Comment by TeomanTheGreat** [comment]
The hos beret is quite robust so it makes sense for the normal beret to be armored somewhat too

**Comment by zeskorion** [comment]
ill make a pr for that later

**Review by zeskorion — APPROVED** [review]

**Pull request merged**
