### PR TITLE
Removes one-time use on holoparasite resetting

### PR DESCRIPTION
**Pull request by ghost**
Why is this even a thing?

:cl:
tweak: You can now reset holoparasites as many times as you'd like.
/:cl:

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
Give it a cooldown at least.

**Comment by TeomanTheGreat** [comment]
Finally thanks steamed hams man

**Comment by zeskorion** [comment]
dunno what i feel about this.

**Comment by ghost** [comment]
i've added a cooldown

@zeskorion hm?

**Comment by enthethan** [comment]
Hey sdimbort port lcass chems

**Comment by zeskorion** [comment]
> i've added a cooldown
> 
> @zeskorion hm?

limited uses exist for a reason.

**Comment by ghost** [comment]
@zeskorion Yes but it's still entirely possible to reset and get another incompetent/dumb user.

**Comment by Isy232** [comment]
I think the thing was so that you would only reset it if your user completely refused to follow your orders instead of just being dumb.

I do think this is good though, it makes holoparasites more viable if you can reset the user multiple times and do not have to worry about the chance of being screwed if you get someone who knows nothing about the game twice in a row.

**Comment by ghost** [comment]
i wouldn't mind someone incompetent initially, that's how you learn.

but if your holopara goes afk for a while and you're hiding a locker while half the station is hunting you down, you can't really afford an incompetent user.

**Review by zeskorion — COMMENTED** [review]
Instead of removing the limited use entirely, give it a significant cooldown, and make it not take a use /start coodlown if the guardian is ssd

**Comment by ghost** [comment]
@zeskorion done - cooldown is now 5 mins, but cooldown is ignored if the guardian has no client or is afk.

**Review by zeskorion — APPROVED** [review]

**Pull request merged**
