### PR TITLE
kromer

### PR DESCRIPTION
**Pull request by mcmeiler**
## About The Pull Request
adds kromer

## Why It's Good For The Game
kromer
it isn't

## Changelog
:cl:
del: credits
add: kromer
/:cl:

### CODE REVIEW

**Review by ike709 — APPROVED** [review]

**Comment by LordSaladin** [comment]
swede station 13
also this is a [BIG SHOT]  pr

**Review by Kapu1178 — APPROVED** [review]

**Review by Ivniinvi — APPROVED** [review]

**Review by Archanial — APPROVED** [review]

**Comment by mcmeiler** [comment]
Literally 1984

**Comment by mcmeiler** [comment]
1984

**Comment by DerpiestBruh** [comment]
Remember what they took away from you

**Pull request closed without merging**
