### PR TITLE
adds OSHA violations (nerfs floorlength bedhead)

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
having long hair is now dangerous around industrial machinery. (if the hair is not covered)
chainsaws, unsafe doors, portable scrubbers, the gibber, the recycler, and mass drivers all have interactions, and new ones are quite easy to add. These interactions are tailor-made to feel like they're out of a gory workplace safety PSA- stand next to a mass driver door? you get sucked in! mass driver activates and pulls you in as well, and you've been spaced! turn on a chainsaw, hair is stuck in? you fall on the saw! etc. New interactions are very easy to add, as simple as calling the proc

comprehensive list is as follows:
normal osha violation hair (very rare for a mishap to occur): "Long Bedhead", "Very Long Hair 1", "Very Long Hair 2", "Long Hair 1", "Long Hair 2", "Long Hair 3", "Long Side Part", "Hime Updo", "Hime Cut", "Hime Cut 2", "Drill Hair (Extended)"
super osha violation hair (5x chance for mishap): "Braid (Floorlength)", "Floorlength Bedhead"

## Why It's Good For The Game
it's midnight and i felt like making this pr. it's funny

plus, only shitters use floorlength bedhead

Edit:
To put a bit more in, this addition is incredibly fitting for the vibe and atmosphere of ss13. Workplace negligence leading to terrible bodily harm? Tell me that doesn't fit! 

## Changelog
:cl:
balance: long hair is now dangerous around industrial machinery
/:cl:

### CODE REVIEW

**Comment by AtlasRules** [comment]
the price to pay for being a snowflake on a research station

**Comment by despong** [comment]
but then the players will complain so if you have a long hairstyle you will spawn with a rubber band to tie your hair down lol

**Comment by St0rmC4st3r** [comment]
> but then the players will complain so if you have a long hairstyle you will spawn with a rubber band to tie your hair down lol

Nah, just add rubber bands to a workplace clothes vendor, because it is the problem of workers to care about their own safety.

**Comment by TeomanTheGreat** [comment]
Make this work with tails too  😳

**Comment by CommandBlockGal** [comment]
why the fuck, just why dude, why,hair, YOURE GONNA NERF FUCKING HAIR?

**Comment by eLeCtrOssSnake** [comment]
Dude, doing shit because you don't like and even accusing that you don't like it? Hell no. This just sounds stupid. Make your hairy ass monkeys be able to be sucked into machinery, not just accessory. Imagine deleting accessories. Should be closed.

**Comment by ghost** [comment]
good change

**Comment by eLeCtrOssSnake** [comment]
It's actually more stupid, you make accessories to be able to kill you? Doesn't that change the accessory purpose? So dumb.

**Comment by Bestparty** [comment]
No conveyor belt interaction? sad.....

**Comment by VictorVow** [comment]
Yet another zesko PR where he can't even name one valid reason "Why It's Good For The Game".

**Comment by DatBoiTim** [comment]
> Make this work with tails too 😳

This mans on to something

**Comment by MrHorizons** [comment]
I think this fills a similar role to toe-stubbing.

**Comment by MrHorizons** [comment]
Now I'm tempted to make a mechanic where if you have long hair, you have a chance to have "hairs" get in food that give the person eating them a negative moodlet and one bite of disgust. Unless you have a hairnet or chef hat.

**Comment by super12pl** [comment]
why

**Comment by zeskorion** [comment]
> Make this work with tails too 😳

I could. 



> No conveyor belt interaction? sad.....

Due to how conveyor belts work, it's impractical to do so without lagging the game

**Comment by katebishop49** [comment]
i aprove

**Comment by zeskorion** [comment]
When i get home from work:
Add tails to the check (no chance multiplier)
(Maybe) add a clothing check as well (realistically,  i'd make this damage or tear clothing off, but jumpskirts are already fetish content and i dont want to buff the horny levels)
Rename the proc to safety_compliance_check cuz qwert's picky as fuck
Add a hair net or scrunchee or some shit
(Maybe) modify the proc to be usable as a check as well, for cooking and chem and shit
Add the proc to all-in-one blender (no special interactions here really, but it *is* usually on a glass table, so that oughtta be sufficient)
Add the proc to other things where suggestions arise

**Comment by eLeCtrOssSnake** [comment]
This is so cursed. If this gets merged I am out.

**Comment by qwertyquerty** [comment]
Not funny enough to excuse the questionable code and annoyingness of it

**Comment by Flakkyboo** [comment]
How to drive people away from bee a zesko tale

**Comment by ghost** [comment]
> This is so cursed. If this gets merged I am out.

good we don't need raging children.

**Comment by ike709** [comment]
This will annoy me once every blue moon when I actually play the game.

**Comment by zeskorion** [comment]
> This will annoy me once every blue moon when I actually play the game.

Yes. The same can be said for toe stubbing, though.

**Comment by ike709** [comment]
It can but I wear shoes.

**Comment by Flakkyboo** [comment]
Rip those of us with digigrade legs

**Comment by ghost** [comment]
PR it again but add scrunchies and protection methods. Let people find out the hard way.

**Comment by zeskorion** [comment]
Will reopen with changes to hair list and qol tonight

**Comment by eLeCtrOssSnake** [comment]
If you delete hairstyles, you're going to die.

**Comment by AtlasRules** [comment]
@eLeCtrOssSnake have you tried not having long hair on a research station with dangerous machinery

**Comment by JackieOTheWisp** [comment]
Lol imagine being salty about what's generally common sense. Didn't your science lab teacher ever tell you to "put your hair up" in the labs to avoid catching fire from bunsen burners?

A useless change to add sure, but a small detail that I find charming, it's the little things in life after all :)

**Comment by ItsTisme** [comment]
IRC commen sense also dictates to not call your boss a bitch for not giving you acces to departments your not qualified to be in

**Comment by Flakkyboo** [comment]
We really out here reviving old pulls

**Comment by JackieOTheWisp** [comment]
@Autisem "Give me access" "No" "Bitch"
_You have been promoted to assistant_

**Pull request closed without merging**
