### PR TITLE
Reverts to old cat tail

### PR DESCRIPTION
**Pull request by Pontenerd**
This reverts commit 6386c045a3b2aaae453f0b54d774c9abf784f8b5.

## About The Pull Request

Reverts to the old felinid tail sprite, the new one looks worse
permission for race change given by @TheFakeElon 

image

## Why It's Good For The Game
Makes felinids tails look worse
## Changelog
:cl:
add: Added the old animation for felinid tails
del: Removed the new tail animation

/:cl:

### CODE REVIEW

**Comment by ItsTisme** [comment]
fight me on ctf_2fort you bitch ill have you know I have a australium bot killer sniper wiht over 300 confirmed kills and have partaken in many 6v6 competatives games and have become the highest rank of the-

**Comment by Pontenerd** [comment]
> 
> 
> fight me on ctf_2fort you bitch ill have you know I have a australium bot killer sniper wiht over 300 confirmed kills and have partaken in many 6v6 competatives games and have become the highest rank of the-

no

**Comment by Sinestia** [comment]
Please

It's way too smooth

**Comment by Sinestia** [comment]
If you want, I can make an image that compares them side-by-side to be put up for polling in discord

**Comment by Pontenerd** [comment]
> If you want, I can make an image that compares them side-by-side to be put up for polling in discord

That would be helpful, thank you

**Comment by Archanial** [comment]
I don't like felinids but new sprite looks worse

**Comment by OceanFish1** [comment]
I don't like felinids but I haven't noticed any differences between old and new sprites

**Review by PowerfulBacon — APPROVED** [review]
New sprite is pretty bad, the thickness doesn't line up very well so wagging looks like the tail is replaced with a completely different tail.

**Comment by MCterra10** [comment]
Catg*rls

**Comment by Pontenerd** [comment]
> Catg*rls

OI the PR's been closed shoo I don't want more emails about this shitty PR

**Comment by Rukofamicom** [comment]
Would be a shame if someone necro'd this more than a year later then.

**Comment by Crossedfall** [comment]
Agreed, that would be a shame

**Pull request merged**
