### PR TITLE
SImplemob Limiters

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
a port of OracleStation/OracleStation#581, which sets a maximum cap for monkies, chickens, and slimes. Currently set to 100 for each by default.
and a fix for catsplosions. Tested and seems to be working.

## Why It's Good For The Game
lag is bad

crashing the server is bad

## Changelog
:cl:
tweak: There is now a cap on the number of chickens, slimes, and monkeycube monkeys that can be alive at once. No more crashing the server with 200 monkeys/chickens.
/:cl:

### CODE REVIEW

**Comment by man4fred** [comment]
Sooo while i don‘t claim to know perfectly well about how to code in byond (i never did actually code in this language but thats not needed for looking over the code) there are some things that might be problemstic:
First why is the maxcap for cube monkeys calculated from only the monkeycubes spawn effectively counting + 1 to the initial monkeycube variable while it does count the deaths by subtracting ok sooo is it impossible in byond to check the current amount of monkeys once a tick of a timer and updating that value like this ? Then also what happens if you transform a critmonkey into a human and then kill it will it still subtract it from the cubemonkey variable or is the monkey not counted anymore giving a way to prevent spawning more monkey even if you kill the old ones. 
Next it deletes the old max spawned at once cap for monkeycubes soo you can actually spam 100 monkeys in one go and prevent anyone else to spawn more monkeys(crippling xenobio).

I know this is a port just think it might be important.

**Comment by man4fred** [comment]
Sorry for making anyone read trough this😅.

**Comment by Cenrus** [comment]
I believe we already have this, the lag yesterday was caused by an issue with butchering. it's fixed now.

**Comment by ike709** [comment]
@Cenrus This is future-proofing. A couple months ago someone lagged Golden by spamming monkey cubes.

**Pull request merged**
