### PR TITLE
Adds new naming system for air alarms, fixes duplicate names

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports:
- https://github.com/tgstation/tgstation/pull/52398
- https://github.com/tgstation/tgstation/pull/53230

## About The Pull Request
This PR introduces a new naming system for Air Vents/Scrubbers. This should fix events where they are ordered oddly in the air alarm, and should make distinguishing between them much simpler.

## Why It's Good For The Game
This should make air vents/scrubbers a lot more distinguishable, and prevent duplicate naming.

This is particularly helpful for atmosians, or new players still learning the system.

It will especially work well when adding new devices to the air alarm, which has a chance of duplicating the entry ( i.e. Atmospherics Air Pump #2) in the current system.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

airscrubber

ventpump

</details>

## Changelog
:cl: RKz, SpaceManiac, Nightred
tweak: new unique naming system for air vents/scrubbers. Should prevent duplicate entries and decrease confusion.
/:cl:

### CODE REVIEW

**Comment by bluezorua** [comment]
how is this in any way or form more helpful or readable than a single digit number

**Comment by Tsar-Salat** [comment]
> how is this in any way or form more helpful or readable than a single digit number

Because when you have list of 25 vents, locating based on a number is extremely difficult. Moreso when you are using multiple rooms, or when the area to which that air alarm applies is hard to discern.

With this, you examine, copy the name, search for it in the alarm and immediately find what you are looking for with no margin for error.

Plus the current system will literally give you a duplicate vent if you build an extra vent sometime (two duplicate #5 vents for example)

**Comment by Dejaku51** [comment]
It was part of NTnet PR, people were against it (I believe even maints told me to remove it)

**Comment by Tsar-Salat** [comment]
> It was part of NTnet PR

Did you not quote the original PR? I didn't see a link to any beestation pr on it.

**Comment by Dejaku51** [comment]
not sure but heres bacons request to remove it https://discord.com/channels/427337870844362753/943311132007997490/1007629749562114108
image

**Comment by Tsar-Salat** [comment]
> not sure but heres bacons request to remove it https://discord.com/channels/427337870844362753/943311132007997490/1007629749562114108 image

Was it due to being an undocumented change?
I'm not seeing anything in your original pr besides mentions of NTnet, of which this code is not a part of.

**Comment by Dejaku51** [comment]
> Was it due to being an undocumented change?

*shrug, i just remember people wanting old naming system

**Comment by itsmeow** [comment]
:key:
Yeah I hate this system, it's no better than numbers.

**Comment by Tsar-Salat** [comment]
this is definitely just gonna sit for a month, only to get another key, so lets just skip to the end

**Pull request closed without merging**
