### PR TITLE
Adds biting

### PR DESCRIPTION
**Pull request by That0nePerson**
## About The Pull Request
When aggressive grabbed, if your mouth is free and you target arms, you will bite your grabber. This has different effects based on the species you bite, such as ethereals shocking you, IPCs/golems shattering your teeth, and oozelings/slimepeople giving you toxin damage. You will also transfer all diseases (that are able to be transferred) to whoever you bite.
This bite does 3 more damage than a normal attack, but this damage can be changed depending on what you are biting.
Alternative to #4159

## Why It's Good For The Game
I believe the idea of a rabid assistant biting sec while being arrested is extremely funny, and all races can get funny effects for being bitten if people want more. It shouldn't be OP, as you can just not target arms to not incur the bite effects.

## Changelog
:cl:
add: Added biting! While grabbed, target arms to bite your attacker. Could have side effects, based on what you bite...
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
fetish content

**Comment by ghost** [comment]
this pr nerfs humans

**Comment by ItsTisme** [comment]
Seems accurate lets do it

**Comment by yorii** [comment]
Does it not circumvent pacifism?

**Comment by PowerfulBacon** [comment]
> 
> 
> Does it not circumvent pacifism?

No

**Comment by badlypayedgoon** [comment]
" You will also transfer all diseases (that are able to be transferred) to whoever you bite.
This bite does 3 more damage than a normal attack"

Why? That is way too strong.

**Comment by ilikesaying** [comment]
what if the grabber has a hardsuit? you can't really sink your teeth the metal on the grabber's arm

**Comment by Jacksquib** [comment]
If you cant inject the arm with a syringe then you shouldn't be able to bite them

**Comment by PowerfulBacon** [comment]
Biting just kind of makes less sense than punching are kneeing your grabber back, especially since it would have to handle literally everything from hardsuits, species etc.
Also it will be super annoying for players to be grabbed, try to fight back by punching and then bite instead breaking their teeth.

**Comment by Sinestia** [comment]
I like it but it has the big problem of "why"

there's a lot of cases and interactions that will be weird that are brought up, and it's extremely obtuse and poorly communicated that its an option, relying on following git or the wiki (if its even added to the wiki, not that people read the controls+combat page for new servers either.) 


 Maybe make it more natural by just being something you do randomly when struggling/resisting.

**Comment by That0nePerson** [comment]
I'm gonna be honest I don't really care that much if this makes it in, I just made it so #4159 wouldn't be exclusive to felinid. If a maintainer thinks this is bad/finnicky/doesn't fit, they can close it

**Comment by PowerfulBacon** [comment]
In its current state it is too uncontrollable for the major side effects of damaging yourself instead if you are being grabbed by a robot / golem etc. If it was purely a message and some extra damage then it would be fine, however when players are clicking harm on people, only to injure themselves then it starts to get a little unfair.

**Comment by eLeCtrOssSnake** [comment]
Well right now this is very unbalanced if ethereal will shock you or any other specie that has a unique action. Makes little sense to me as if it is really necessary nor funny. Maybe I am wrong

**Pull request closed without merging**
