### PR TITLE
golems no longer exist in game

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
removes adamantine slimes from the pool, as well as adamantine extracts
removes the free golem ship

## Why It's Good For The Game
fran asked me too
also, ghost roles are terrible

## Changelog
:cl:
del: adamantine slimes and free golems
/:cl:

### CODE REVIEW

**Comment by Howluinb** [comment]
you could leave the golem ship alone but just prevent their ability to make shells other than ones they can use to change bodies?

That way golems would still exist but golem spam would be impossible

**Comment by zeskorion** [comment]
> you could leave the golem ship alone but just prevent their ability to make shells other than ones they can use to change bodies?
> 
> That way golems would still exist but golem spam would be impossible

fran's orders, kill golems.


and im happy to oblige, ghostroles suck

**Comment by Kapu1178** [comment]
The problem is their existence is a massive code debt problem for not only KapuLimbs, but any large refactors in general.

**Comment by Fronsis** [comment]
ah yes i delete stuff because fran said so, you see, the thing is that even Fran himself admitted he has bad takes

that aside

I **CAN** understand where  this come from after seeing the screenshots Kapu provided where he showed the way golems limbs are coded and both him and Fran agreed it was a MESS, obviously the KapuLimbs is an amazing idea, it's a healthy code and a healthy addition and i can see why the golems should be guillotine'd but.. this is unironically a **Improve don't remove** moment

I like Golems and their uniqueness(except slow te-hee) all the different perks, the golem gang in lavaland, the xenobio golem army potential all of that is part of the flavour and i would say most of the players will agree with this.

if you're making such an important decision pr as removing something a lot of players use, please do a better ''Pull Request'' and ''Why it's good for the game'' description. so at least the few people that care to check on github can give a proper input(and if it eventually reachs #pr-player-input too)

If all the higher ups decides this is better for server performance, better code, better compiles, refactors and more code words i don't know about sure go ahead i like my game smooth as everybody else but **PLEASE** don't put them on the bottom of the list to never be touched again their limbs could also be a good part for KapuLimbs.

As for ''ghostroles sucks'' Yeah, a lot of servers have way better ghostroles but Golem Ship is the best one to practice constructions and small team adventure, i would like for zams to elaborate on why they suck, but once again i can't do much since the pr alredy looks like a shitpost.

**Comment by Pirill** [comment]
Hoo-boy. Now I will say Kapu has some valid reasons for this removal NONE of which, I should add, are mentioned or explained anywhere in the PR for people who might not follow development channels closely to give input on or suggest alternatives or any sort of discussion. Instead the PR's explanation boils down to "Remove feature because I want to. Get fucked community, your input doesn't mean shit", which is a stance maintainers _smugly_ reiterate time and again as being the truth, but I can guarantee that doesn't make you any more endearing in anyone's eyes.

Rather than trying to minimize the removal of a ghost role people enjoy playing, or figure out an alternative that isn't as disruptive, your answer is to just nuke an entire crossbreed along with every other unrelated effect associated with it like the pylons. And when it comes to ghost roles, the attitude comes across as the typical "remove, don't improve" mentality where instead of moderating a feature with a mild chance of abuse, you instead nuke the whole thing from orbit because you can't be bothered to slap the hand of the people who abuse it, or even better put in a minimal amount of effort to improve said ghost roles to make them less abusable.

In the end it's not even so much the removal I'm upset about but the attitude towards it and the community. Free Golems were one of the better ghost roles for learning stuff about how a station works since you had to build everything you needed from scratch while also having some neat features to coordinate and teach through the adamantine vocal chords. Since Charlie station is basically dead and Lavaland syndies can mostly only do chem and viro (if a miner hasn't blown them up already for fat loot) this is a pretty unfortunate removal in my eyes to say the least.

**Review by Crossedfall — CHANGES_REQUESTED** [review]
Yeah, I'm not even going to consider this until the PR body is sorted out. I was going to write out my own reasoning on why it's terrible, but thankfully other people did that for me.

**Comment by zeskorion** [comment]
*ahem*
The free golems do function as a good tutorial role, yes.
However, they also have access to some of the most powerful gear available to the station, and its players abuse that access often.

I was asked to make this pr in a few minutes whilst working on another PR. I dont believe free golems have a place in lavaland,  where they can easily interact with the round. Ghost tutorial roles should be just that- tutorial roles to learn an aspect of the game. I believe the only ghost role on mining should be the Hermit, perhaps with somewhat different objectives (those being,  build a base with only stuff from lavaland, as opposed to escaping)

I'm sure we can all agree on why xenobio golems suck- they're worse. They are easy to mass produce and place salty, dead players in a body with high armor and punch damage, right on the station and ready to greytide and either be or destroy the valid.

I cant be bothered to design a z-level entirely for ghostroles in the time it took me to make this pr last night. I don't want to get sucked into the rework trap. This is a simple PR to make way for much larger things

And on pirill's post:
I'm not a maintainer 
What you percieve as smugly shoving the community aside is just me not wanting to put the effort into explaining why im doing what i'm doing. Game design is a passion for me, and i hate listening to players who dont know what they're talking about because all they care about are features and short-term enjoyment, not the longevity and design of a game as a whole.  In my time developing ss13, i have learned you can never please players without taking an approach that actively detriments the game. Players dont know what they want, because their ideas dont form anything cohesive- they're just features to tack on to a game that already suffers from feature bloat.

**Comment by Archanial** [comment]
Lol
🔑

**Comment by MNarath1** [comment]
if you want to remove golems what has that to do with adamantine slimes yes they do have crossbreeds to make golems but thats by far no their only use.

**Comment by MNarath1** [comment]
> 
> 
> if you want to remove golems what has that to do with adamantine slimes yes they do have crossbreeds to make golems but thats by far no their only use.

not to forget that i am pretty sure there  are a other non adamantine crossbreeds that interact with golems that would break obviously too.

**Comment by francinum** [comment]
image

**Comment by francinum** [comment]
...Next time I'll just do the PR myself instead of farming it out.

**Comment by PerishedFraud** [comment]
This is not the way. Culling a role (or department) because of its playerbase is a terrible move. We have admins. We can enforce rules. Just make a golem rule page and leave them alone.

That said, the above goes for the free golems. Xenobio needs to die.

**Pull request closed without merging**
