### PR TITLE
combat glove sprite, if this doesnt work im going to kill myself

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

yes new combat gloves sprite

## Why It's Good For The Game

gives combat gloves their own sprite

## Changelog
:cl:
add: Added combat gloves sprite.
/:cl:

credit to azlanon for the sprite.

### CODE REVIEW

**Comment by CthulhuOnIce** [comment]
Did you test it

**Comment by ghost** [comment]
yes

**Comment by ghost** [comment]
unknown

**Comment by ike709** [comment]
baby's first working PR

they grow up so fast

**Comment by ghost** [comment]
> 
> 
> baby's first working PR
> 
> they grow up so fast

do i get my scooby snack now.

**Pull request merged**
