### PR TITLE
[PORT] examine-code refactor (#44636)

### LINKED ISSUE #593: Can’t read papers on airlocks
## Round ID:

Multiple

## Reproduction:

Place a bounty paper or contract, then try to read it with shift click.

### LINKED ISSUE #828: [Bounty] Port TGs new examine code, and convert all current examine procs to it
You can get most of the conversions from their followup PRs but some you'll have to do yourself.

### PR DESCRIPTION
**Pull request by Cenrus**
https://github.com/tgstation/tgstation/pull/44636

Closes #828 
Closes #593

## About The Pull Request

Refactor examine() to build a list that examinate() then joins and to_chats in one go, rather than examine code sending 100 individual to_chats for every knob on the thing.

:cl: Naksu
refactor: Refactored examine-code
/:cl:

### CODE REVIEW

**Review by MarkSuckerberg — CHANGES_REQUESTED** [review]
Resolve the conflict, and make sure it works as intended.

**Comment by Cenrus** [comment]
merge #867 first, it includes the examinate define.

**Comment by ike709** [comment]
This is also a bounty.

**Comment by ike709** [comment]
Doesn't pass travis.

**Comment by Cenrus** [comment]
fixed

**Comment by qwertyquerty** [comment]
Expect a lot of broken examines after this that will require you to do followup PRs to fix em

**Comment by Cenrus** [comment]
Will close issue #593

**Comment by Kerbin-Fiber** [comment]
did this ever get a testmerge

**Comment by ike709** [comment]
No, I've been gone for finals week. It'll get a trial by fire tomorrow or the next day.

**Comment by ike709** [comment]
Seems to be fine. Remember to claim the bounty.

**Pull request merged**
