### PR TITLE
Removes hatecrimes

### PR DESCRIPTION
**Pull request by yorii**
## About The Pull Request

Removes offensive language from code.

## Why It's Good For The Game

Conformity.

## Changelog
:cl:
spellcheck: fixed a few "typos"
/:cl:

### CODE REVIEW

**Comment by badideaguy** [comment]
Fun fact
Idiot, moron, and imbecile 
Were all words that predate the r word and meant the same thing as it
Then the r word replaced them for some reason
So the r word with this has just ouroboros itself

**Comment by ike709** [comment]
Fun fact
I've seen someone get banned from github for saying "okay r-"`[CENSORED BY THE MINISTRY OF TRUTH]`

**Review by ike709 — APPROVED** [review]

**Comment by Effemu** [comment]
the words you used instead of rword as considered hate speech and offensive

cya in court 😎

**Comment by yorii** [comment]
> the words you used instead of rword as considered hate speech and offensive
> 
> cya in court 😎

The words I selected for the intellectual disability are all that exact word, all the comments that do not literally refer to the disability were changed to "stupid", and as long as stupid isn't listed by the oxford dictionary as being taboo it should be fine using it instead.

**Comment by aidan-bowman** [comment]
language is offensive to me

checkmate libs

**Comment by Sinestia** [comment]
Using intellectual disability in place of that seems like borderline satire.
It's still using disability for mockery's sake, it's just sanitized. 

Just weird lol but I think this complies with github's TOS and the rules better so hey.

**Comment by Effemu** [comment]
> 
> 
> > the words you used instead of rword as considered hate speech and offensive
> > cya in court 😎
> 
> The words I selected for the intellectual disability are all that exact word, all the comments that do not literally refer to the disability were changed to "stupid", and as long as stupid isn't listed by the oxford dictionary as being taboo it should be fine using it instead.

checkmate liberal! 😎 
https://www.anti-bullyingalliance.org.uk/sites/default/files/field/attachment/Ato-Z-of-Offensive-language-FINAL.pdf

**Comment by yorii** [comment]
> > > the words you used instead of rword as considered hate speech and offensive
> > > cya in court 😎
> > 
> > 
> > The words I selected for the intellectual disability are all that exact word, all the comments that do not literally refer to the disability were changed to "stupid", and as long as stupid isn't listed by the oxford dictionary as being taboo it should be fine using it instead.
> 
> checkmate liberal! 😎
> https://www.anti-bullyingalliance.org.uk/sites/default/files/field/attachment/Ato-Z-of-Offensive-language-FINAL.pdf

I don't really care what the "anti bullying alliance" in the UK has to say on the matter, this PR is to make the repo comply with already existing guidelines, both by github and by our own beestation administration.

**Review by utilbird — APPROVED** [review]
I've never had much issue with the r-word but I'd rather stay on the safe side of github. TG got nuked for having `[alternative word for cigarette]` in their code

**Pull request merged**
