### PR TITLE
Autolathe economy v3

### PR DESCRIPTION
**Pull request by mudzbe**
### About The Pull Request
You know what they say third time's the charm. This PR is mostly the same as the previous version except now autolathes can have their panel's reinforced with metal sheets and act similar to airlocks which have been reinforced. Registered accounts can be removed by pulsing the wire twice, with a delay inbetween, allowing the owner to run back and smack anyone. Autolathes with a registered account also cannot be disassembled.

- Printing items from the autolathe costs money depending on the amount and type of mats it uses to print
- An ID or department budget can be linked to the autolathe. 70% of the fee will go to the linked account, 10% to the civilian budget and 20% disappears to NT, the syndicate or maybe somewhere else? Your guess is as good as mine.
- The linked account can be cleared by pulsing a new wire.
- The autolathe can be set to "free mode" where everything is free, if the autolathe spawns/is built offstation, it will be set automatically to this.
- The autolathe can be emagged to be set to free mode.
- All autolathe item's material value have been changed to properly balance the costs.

Mat costs/prices have been set to reflect their individual value rather than realistic mineral cost. Generally if an item can already be bought at a vendor, it is cheaper at that vendor by a factor of 2.5. Basic tools like crowbars and screwdrivers have been set to 50c, multitool is 67c, welding tools are around that price too. I haven't changed part mat requirements and as such they are cheaper, ranging around 20c for basic parts. Weapons and ammo are more expensive, shotgun shells range at 50c. All of these prices are negotiable and I don't expect them to be perfect, even so, insignificant pricing is better than no pricing.

My reinforced autolathe coder sprite: 
image

### Why It's Good For The Game
This adds another avenue of balancing items rather than is there enough mats yes/no? I saw some people wanted to change prices in vendors and this supports that ability by not having a free source of items that is objectively better than those vendors.
Money has long been near useless and I aim to change that. Fining people as a means of punishment has more weight now. Items like shotguns can also be buffed as their ammo will now normally cost money.

What about assistants, they have no money? They wont be able to buy anything! Good. Those lazy parasites should do something productive instead of getting free handouts and committing crimes with those handouts. Next, if this is merged I will add pricing to items from protolathes, that too is a case of is it researched Y/N? Is there enough mats Y/N? I can also tie in the ability for the HOP being able to change the percentage of tax to the civ budget and for the price to inflate because of that, hooray.

Let's talk stats. I counted 45 possible sets of tools roundstart on boxstation:

- 10 sets were in public areas.
- 10 sets purchasable from youtools.
- 20 sets were in restricted areas, these can be negotiated for and otherwise serve as a reserve for respectable individuals.
- 5 misc sets of tools spread around both.
- +any I missed

There is an abundance of tools roundstart and if all else fails money can be gained by:
- 24 bounties + 5 extra bounties for enterprising assistants. Any of which can buy several sets of tools from an autolathe several times over.
- Every crew member can be convinced through a loan, an odd job, or something else creative.
- 7 department budgets with an abundance of money, talk to the heads
- Assistants can pitch in together and share a set of tools

Later on into the round the autolathe would be upgraded and tools printed from there will be cheaper than purchasing them from youtools, youtools can also be restocked. Simply put assistants getting tools wont be an issue, if they make an effort. Why should assistants get handouts if they disproportionately commit more crime?

"But we have no economy" well yea, this PR is like a 500 line change, you want me to write another 500? Rome wasn't built in a day, quite simply this is better than nothing and nothing is what bee has. Standalone this PR is fine, credits are accessible, it's just people aren't using all avenues currently available. Tools are also widely available and aren't that expensive regardless.

Changelog
:cl:
add: Autolathe items cost money
add: Accounts can be linked to autolathes
add: New wire for the autolathe
add: Autolathe freemode for communists and ghost roles
add: Emagged autolathes enter freemode
add: Autolathes can be reinforced with metal to prevent hacking
balance: rebalanced mat costs for autolathe items
/:cl:

### CODE REVIEW

**Comment by pickleinjar** [comment]
bro putting a price on protolathes is cringe. fx miners need plasma cutters if they want to mine many ore. if that gets a cost thats cringe.

**Comment by mudzbe** [comment]
> bro putting a price on protolathes is cringe. fx miners need plasma cutters if they want to mine many ore. if that gets a cost thats cringe.

autolaths m8, bro my PR even has a picture of an autolathe, what you doin?

**Comment by ItsTisme** [comment]
>if this is merged I will add pricing to items from protolathes

I dont like the idea as much that you "pay" for protolathe stuff since science will have to pay a fortune for all the parts for upgrading stuff that isant even there's 

I also add that 50 credits for 1 tool is a bit steep, even for non-assistants. This will encourge tiding into areas more since they cant pay for the things they need.

**Comment by ivanmixo** [comment]
>50C for basic tools

Might as well remove them from the game

**Comment by PowerfulBacon** [comment]
oh god not this again

**Comment by eeSPee** [comment]
Here are my main points:
* Autolathes are mostly required by assistants and service; people with small salaries.
* There's already a solution where you can trade tools for money; they're called Youtools.
* This addresses a problem that doesn't exist.

**Comment by mudzbe** [comment]
> oh god not this again

Yes god this again, actually why do I even bother I don’t play :trollface: 

> * Autolathes are mostly required by assistants and service; people with small salaries.

So they can ask for loans from heads or other crew in exchange for their services 

> * There's already a solution where you can trade tools for money; they're called Youtools.

Yes and they cannot be balanced properly because of the existence of autolathes which are objectively better and this has been tried. The sole point of youtools is to vend tools so why shouldn’t it be better than the thing that does everything?

> * This addresses a problem that doesn't exist.

Economy is shit, the autolathe is apart of the economy

>50c tools

I can easily lower it, but the impact is speculation as to what it would actually be like.

**Comment by PowerfulBacon** [comment]
> Economy is shit, the autolathe is apart of the economy

This doesn't address to the problem of the economy being shit, it adds to it by putting more stuff based on the shit.

**Comment by ike709** [comment]
The entire economy system needs an overhaul and this PR doesn't seem viable until that has occurred.

**Comment by mudzbe** [comment]
grr merge conflict awake me from my slumber. Also I might port the TG bounty thingo so assistants can get money, but honestly idc

**Comment by mudzbe** [comment]
An anonymous party paid notorious GitHub Assassin “PowerfulBacon” 10 Bitcoin to kill me, my family and my PR

**Pull request closed without merging**
