### PR TITLE
Modernisation (19x15 widescreen mainly + Some other features)

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Changes many old features with the game to make it more in-line with modern standards.

#### Added a new 19x15 title screen
Doesn't remove the old title screens, they will still not cover the whole screen and need to be updated. Originally I was highly against changing the screensize, but just try it out in game, it's not bad when you try it out

#### Darkmode is now default
Many poor souls don't find the change to darkmode button when they join.

#### Darkmode colour tweaked slightly
Made to be slightly more of a very dark blue.

#### Hotkeys mode is now enabled by default
Simple as that, hotkeys are enabled by default

#### The arrivals shuttle is now immune to explosions and meteors
New players spawning on a death shuttle sucks.

#### Default stat panel window size has been reduced slightly, with the chat taking up more space
The stat panel takes up slightly less space and the chat window is larger.

#### Prefs-admins has been integrated into preferences
This tab was very rarely used and removing 1 tab made all the stat buttons remain on a single line making it not painful for admins to use. Maybe when we get TGUI stat panel when TG does it this can be changed to be better.

#### Starting area changed to accommodate 19x15
The title screen area now accommodates 19x15 screen size. (Although the old title screens won't be updated)

## Why It's Good For The Game

So we don't look outdated and old.
19x15 is something that many people (including myself) absolutely despise the idea of, but when implemented it is actually pretty great.

image

## Changelog
:cl:
add: Added a new 19x15 title screen
tweak: Darkmode is now default
tweak: Darkmode colour tweaked slightly
tweak: Hotkeys mode is now enabled by default
tweak: The arrivals shuttle is now immune to explosions and meteors
tweak: Default stat panel window size has been reduced slightly, with the chat taking up more space
tweak: MOTD formatting updated so the header is centred, not underlined and in a not-terrible font.
del: Prefs-admins has been integrated into preferences
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
good changes

**Comment by francinum** [comment]
May have balance implications and usability issues on small or laptop displays.

**Comment by zeskorion** [comment]
Please atomize widescreen

**Comment by OceanFish1** [comment]
We wide and it's cool.

**Comment by PowerfulBacon** [comment]
> Please atomize widescreen

Sure

**Comment by BeloneX** [comment]
> Please atomize widescreen

fuck you widescreen is great.

**Comment by ghost** [comment]
widescreen is great

**Comment by ike709** [comment]
This should include setting viewport sizing to auto by default.

**Comment by PowerfulBacon** [comment]
> This should include setting viewport sizing to auto by default.

I am pretty sure it is, cause I checked them settings

**Comment by Isy232** [comment]
Widescreen gives those who use it an advantage. Some think it looks better but some like it the older way and I do not think we should give players disadvantages based on their preferences.

If you are playing on 15x15 and doing traitor stuff in R&D, the chemist playing on 19x15 can see you but you are unable to see them.

If you are in a gunfight in a horizontal hallway the player on 19x15 has an advantage of 2 tiles of range.

If you want to remain robust it will almost become necessary to play on 19x15.

The best possible way to balance this is to just leave it at 15x15.

**Comment by eLeCtrOssSnake** [comment]
Not based, everybody will lose the sense of chat, which is in my and probably not the only opinion is one of the main aspects of the game, so I would say no, Maybe make the screen a bit wider, to not crush chat window, but I would rather not do it at all. I kinda hate tg for this too, people are dumb fucks who can't even read the chat for a message that I said 10 sec ago that faded, so for the sake of people being capable of not only reading from game pop-ups(which are bad for the same reason), but the chat, I would not do it.

**Comment by PowerfulBacon** [comment]
> Widescreen gives those who use it an advantage. Some think it looks better but some like it the older way and I do not think we should give players disadvantages based on their preferences.
> 
> If you are playing on 15x15 and doing traitor stuff in R&D, the chemist playing on 19x15 can see you but you are unable to see them.
> 
> If you are in a gunfight in a horizontal hallway the player on 19x15 has an advantage of 2 tiles of range.
> 
> If you want to remain robust it will almost become necessary to play on 19x15.
> 
> The best possible way to balance this is to just leave it at 15x15.

This makes 19x15 only so there will be no issue with players having different viewsizes, another option could be 17x15

**Comment by eLeCtrOssSnake** [comment]
The best way is 15x15. It's just how it works and probably should, filling space that you really won't be able to interact with much for a cost of making people retarded and forget about chat completely, I would just leave it as it is.
edt: Even Colonial Marines have 15x15, which probably stays for the same reason.

**Comment by eLeCtrOssSnake** [comment]
The new colour looks crappy, and the invincible shuttle is a shit idea because you're making it a safe place. No concepts like this were ever seen in the game, thus shouldn't be added, and also it's a dumb idea. Also never died in a spawn shuttle. It's a just station part, which can and should be just fixed, so I again see no reason in easying engineers lives, they aren't doing shit anyway, but changing the game is not an excuse.

**Comment by PowerfulBacon** [comment]
> 
> 
> The new colour looks crappy, and the invincible shuttle is a shit idea because you're making it a safe place. No concepts like this were ever seen in the game, thus shouldn't be added, and also it's a dumb idea. Also never died in a spawn shuttle. It's a just station part, which can and should be just fixed, so I again see no reason in easying engineers lives, they aren't doing shit anyway, but changing the game is not an excuse.

It's a part of the station where people spawn, and if damage will cause players to spawn in and instantly die, ruining their round as of something not their fault. Making the engineers lives easier by making like a 10x7 area safe is not going to change much in the long run and is a good QOL change compared to having people instantly die in the shuttle.

**Comment by PowerfulBacon** [comment]
> edt: Even Colonial Marines have 15x15, which probably stays for the same reason.

A lot of servers have widescreen and have it stay for a reason too. The chat being smaller isn't much of an issue, in game it is still very readable (Obviously except from standard times when you aren't really looking at it such as in combat or when talking to people nearby since you are reading their overhead chat), but the colours still stand out enough to be noticed in your peripheral vision. The amount of space more you will have to look over is this much.
image


And additionally, most servers that are more focused on roleplaying already have this feature without issue, goon even has theirs at 21x15 and people still talk on the radio and to each other fine, NSV has 17x15 I believe and is much more focused on roleplay than bee and citadel has theirs widescreen and is heavily focused on a different kind of chat based roleplay. Chat being smaller and not read isn't much of an issue you will have to worry about it, the issues come from with what Francium pointed out and the decision really would be down to rather than is it worth it to have the potential that someone is reading the chat less and more to the issues with users of 4:3 monitors as they will have black bars on the top and bottom of the screen.

As for the colour, the background looks nice but the border on the stat panel looks kind of off and I could probably look into changing it if people actually like the colours and want it.

**Comment by Isy232** [comment]
19x15 gives widescreen players an additional 2 tiles of range in combat. This is a huge advantage in many common combat situations.

I agree with pretty much everything here with the exception of this.

**Comment by PowerfulBacon** [comment]
> 19x15 gives widescreen players an additional 2 tiles of range in combat. This is a huge advantage in many common combat situations.
> 
> I agree with pretty much everything here with the exception of this.

It gives all players 2 extra tiles of range.

**Comment by Isy232** [comment]
> > 19x15 gives widescreen players an additional 2 tiles of range in combat. This is a huge advantage in many common combat situations.
> > I agree with pretty much everything here with the exception of this.
> 
> It gives all players 2 extra tiles of range.

Wait, so its not optional?

**Comment by sheldoniscool** [comment]
Thank god - how is bee tighter than all the other servers it's awful

**Comment by francinum** [comment]
17x15 is what NSV13 uses, We find it an acceptable compromise.

We also don't touch the screen width at lobby time, and use the autofit system to cover over the issue.

**Comment by sheldoniscool** [comment]
> Widescreen gives those who use it an advantage. Some think it looks better but some like it the older way and I do not think we should give players disadvantages based on their preferences.
> 
> If you are playing on 15x15 and doing traitor stuff in R&D, the chemist playing on 19x15 can see you but you are unable to see them.
> 
> If you are in a gunfight in a horizontal hallway the player on 19x15 has an advantage of 2 tiles of range.
> 
> If you want to remain robust it will almost become necessary to play on 19x15.
> 
> The best possible way to balance this is to just leave it at 15x15.

Show me one player who isn't using widescreen. Thanks.
It's so funny to me that bee MRP is so hardcore yet they're also they least robust players I've seen on any server.

**Comment by qwertyquerty** [comment]
I think 17x15 is a good compromise. You mentioned 4:3 monitors but you've forgotten the poor souls who have a 5:4 monitor (a lot more than you think).

The other more ambitious option is to make it so chat and the verbs panel can be a popout window.

**Comment by alxmra** [comment]
> The other more ambitious option is to make it so chat and the verbs panel can be a popout window.

I don't think that's really possible in byond without taking too much effort.

**Comment by ModDownloading** [comment]
I would be fine with having wider screens as long as we can opt out, and have an option to just use the 15x15 screen again (since that looks way better on my square monitor). I know that this means that I won't be able to see as far as people using widescreen, but honestly I don't think it will make too much of a difference in the long run, just as long as I have the option to use 15x15 still.

**Comment by zeskorion** [comment]
widescreen may look good but widescreen is not how ss13 is meant to be played. Most shit is coded for a screen range of 7

**Comment by francinum** [comment]
A fair amount of stuff IS based around a view range of seven, however a majority of it was coded to adapt, and what hasn't is within acceptable boundaries.

**Comment by VictorVow** [comment]
After playing on a bunch of servers with widescreen, I far prefer it. The effect on chat is minimal, plus we already have runescape chat which already minimises the emphasis on the chat box. Prefer 19x15 over 17x15 because it just looks more modern that way. 

With SS13 successors like Unitystation and SS14 going for full-screen and having the chat in just a small overlay box it's easy to see why this is a must-have to at least have widescreen.

**Comment by PowerfulBacon** [comment]
I am not working on this at the moment, when TGUI4 eventually gets finished (I have some local issues that prevent me from testing it that need fixing) I'll open another PR and see what people think about 17x15 along with the more modern chat style

**Pull request closed without merging**
