### PR TITLE
Tweaks the Glowshrooms sprite

### PR DESCRIPTION
**Pull request by ro5490**
## About The Pull Request

Just tweaks the glowshroom sprite to remove the floor gunk

## Why It's Good For The Game

I was recently told by multiple people that the shroom sprite sucks ass and that part of why current shroom floors suck is they cover almost the whole tile so you can't click on the floor through them....

So this fixes that by removing the gunk on the floor below shrooms

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

BEFORE
image

AFTER
image

</details>

## Changelog
:cl:
imageadd: Glowshrooms now have a slightly altered sprite so you can click the floor below them a lot easier
/:cl:

### CODE REVIEW

**Comment by ro5490** [comment]
Yes I forgot how to clean up my commits

**Comment by PowerfulBacon** [comment]
I think it looks significantly better with the gunk.

**Comment by mcmeiler** [comment]
The better option would be to remove them entirely in my honest opinion

**Comment by PowerfulBacon** [comment]
Better option would be to make a system for giving atoms a custom passthrough map so that you can define which areas of the sprite should be passthrough.

**Comment by Isy232** [comment]
I think this is an improvement but ideally the amount of gunk wouldn't be totally removed just largely reduced

**Comment by PowerfulBacon** [comment]
I wonder if anyone voting actually opens the PRs

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
