### PR TITLE
Flash and sunglasses less cancerous

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
This stops how cancerous flashes currently are. Now wallslams won't happen, you'll merely start walking in random directions. No longer is there a one-click AOE attack which makes it easy to stun multiple people at once and instead it's better suited for self-defence only. 

It also swaps Meta and Delta maint sunglasses with non-flashproof versions. All other sunglasses spawns have been renamed as "advanced sunglasses" and still offer flash protection.

## Why It's Good For The Game
"Are sunglasses powergaming" is a hot topic right now and there are some arguments against it despite it making you measurably better in combat. 

First, the reasoning that they look cool. This PR keeps the common sunglasses spawns for just looking cool and these glasses don't offer any combat advantage.

Second, the rebuttal that they are "necessary to survive". Which, I get in a way. Flashes are overpowered as hell currently, and we're the *only* server that has them like this. Even VOREStation who originated this bit of wallslam code removed it over a year ago. 

It's still powergaming by preparing for combat when there's no reason to. However, flashes are long overdue a nerf so that's been done here. 

## Changelog
:cl:
balance: Meta and Delta static maint sunglasses have been swapped with dynamic loot spawns.
balance: Wallslams from confusion are gone, the randomised movement is kept. 
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
Yes, please, yes.

**Comment by GoatMonarch** [comment]
I like the idea of the flash interaction change, but I think removing maint sunglasses are kind unecessary.
Being immune to a short blind and unpredictable movement isn't something being immune to will cause too much of a gameplay change.

**Comment by VictorVow** [comment]
Upvote on discord #pr-player-input as well people @Cenrus 

@GoatMonarch people can still get flash protection but they now need to take some risk in order to get it. Meta and Delta are the only two stations which give you that loot risk-free, I think it's better that all stations follow similar loot tables. And it statically spawning in the same place every shift is a bad mechanic which rewards the same people rushing it every round.

**Comment by Bastian0930** [comment]
Split the PR into two. Maint sunglasses not being flashproof, and the flash debuff.

**Comment by VictorVow** [comment]
@Bastian0930 wouldn't work. Replacing maint sunglasses wouldn't be accepted if flashes remain OP. And I've tried to weaken flashes by itself before, and the PR didn't pass.

**Comment by ike709** [comment]
Flash changes are good but sunglasses changes are not.

Better move would be to replace any static maint loot with lootspawners so you have to actually explore maint rather than just run to the same tile every round. Not sure how up-to-date bee is on lootspawners.

The vote is slightly failing but I'll still merge if you split it into just flash changes.

**Comment by zeskorion** [comment]
> Flash changes are good but sunglasses changes are not.
> 
> Better move would be to replace any static maint loot with lootspawners so you have to actually explore maint rather than just run to the same tile every round. Not sure how up-to-date bee is on lootspawners.
> 
> The vote is slightly failing but I'll still merge if you split it into just flash changes.

the flash changes remove wallstuns as a whole actually, something that people have been against every time it's brought up.

I'll make a separate flash pr soon, like, tommorow or something, that brings em more in-line without totally removing that mechanic from confusion

**Comment by VictorVow** [comment]
@ike709 I'm sympathetic to the people who just want sunglasses for the aesthetic rather than the flashproof aspect. Could the non-flashproof ones be added to the ClothesMate if the static spawns are replaced with dynamic lootspawners?

**Comment by ike709** [comment]
@Victor239 Go for it, but change the desc of non-protecting sunglasses to say they don't block flashes. And do it in a separate PR from flash changes.

**Comment by zeskorion** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/1556

Alternative pr to totally removing the wallstun mechanic, which is a terrible move

**Comment by ike709** [comment]
Defeated by #1556 

Make a separate PR with just the sunglasses changes.

**Pull request closed without merging**
