### PR TITLE
Allows IPCs to wear underwear

### PR DESCRIPTION
**Pull request by Hardly3D**
## About The Pull Request

This PR allows IPCs to wear underwear by removing NO_UNDERWEAR trait from them.

(Bacon sorta approved it so yeah)

## Why It's Good For The Game

Allows IPCs to have more drip, there's no reason why they should be unable to wear underwear as there seems to be no clipping issues.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

dreamseeker_vyytEb7dr8

</details>

## Changelog
:cl: Hardly
tweak: IPCs can finally wear underwear.
/:cl:

### CODE REVIEW

**Comment by DerpiestBruh** [comment]
theyre robots

**Comment by St0rmC4st3r** [comment]
sexy robots

**Comment by Pirill** [comment]
NEKO UNDERWEAR IPCS ARE JUST THE NEXT STEP TOWARDS FELINID IPCS LET'S GOOOO!!!!!!!

**Comment by Crossedfall** [comment]
but-why-wtf

**Review by ike709 — APPROVED** [review]

**Comment by DerpiestBruh** [comment]
this is the end

**Pull request merged**
