### PR TITLE
Various improvements to multi-Z travel

### PR DESCRIPTION
**Pull request by covertcorvid**
## About The Pull Request
This PR fixes a lot of things about multi-z travel. (Port of https://github.com/BeeStation/NSV13/pull/1418 and https://github.com/BeeStation/NSV13/pull/1894)
It contains several improvements to using stairs, especially with pulling, buckling, and vehicles. Buckled things will stay buckled while transiting stairs, vehicles can go down stairs, and being in a wheelchair no longer makes you immune to fall damage.

It changes travel_z so that moving upwards into space or openspace is okay even if you start on a floor, and moving downwards onto a turf is okay as long as you're starting on space or openspace. It also allows the Move-Upwards and Move-Down verbs to be used for travel_z.
It adds handing for some incorporeal beings - the blob overmind (prior to placement), and most things that use jaunt movement, including revenants and the Eminence. Ninja jaunting (unused?) was deliberately excluded because gravity should still apply to ninjas most of the time.

It adds power cables that go up and down in place of multi-Z power relays. https://github.com/discordia-space/CEV-Eris/pull/2032 was used as a reference.

## Why It's Good For The Game
It makes multi-z much more functional and allows more intuitive multi-z movement.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://streamable.com/t2fawo

</details>

## Changelog
:cl:
add: Added stairs to multi-z debug station
add: Power cables that go up and down. Use 2 pieces of cable on an open space to create one.
remove: multi-deck power adapters
fix: Buckles are no longer cancelled when using stairs
fix: Vehicles are now able to go down stairs
fix: Pulling someone in a roller bed or wheelchair on stairs now acts the same regardless of whether you grabbed the person or the object
fix: Fireman carrying people up and down stairs works now
fix: Being buckled to a wheelchair or other vehicle no longer makes you immune to damage from falling through open space
fix: Non-observer ghosts (revenants, eminence, poly's ghost) no longer need to hitch a ride in an elevator to get off their starting level.
tweak: Blob overmind can use Move-Upwards and Move-Down verbs to find a location to place itself
tweak: Upwards movement from a floor tile in zero gravity will work as long as the tile above you is open or space
tweak: The Move-Upwards and Move-Down verbs from the IC tab can be used by more than just observers
tweak: Revenants and Eminences can use the up-down radial menu
tweak: A shuttle that can choose its landing site can land on any level of a multi-Z station
code: Stair travel uses Move or doMove now to better handle pulling and buckling
code: Allow_z_travel now indicates whether a turf is a valid start location for downwards travel, or a valid destination for upwards travel
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Ninja movement uses jaunting?

**Comment by covertcorvid** [comment]
> Ninja movement uses jaunting?

The code comments around the shadow jaunt define seem to think so, but now that I'm actually trying to look at the ninja module code I'm not seeing where it gets used. It's possible it's obsolete code.

https://github.com/BeeStation/BeeStation-Hornet/blob/f52b7be06e31863de4a98b8eff5438b0ebd511b4/code/modules/mob/living/living_defines.dm#L42

**Comment by zeskorion** [comment]
I've noticed an issue where multiz disposal adapters tend to shit themselves and not work

**Comment by williamcll** [comment]
Did you fix how multi-Z cable layers don't work on bee?

**Comment by covertcorvid** [comment]
Haven't looked into disposals or cables but I'll do so later today. Bee *appeared* to already have the changes from the PR that says it fixes multi-z disposals but I'll do a closer comparison of the code.

**Comment by zeskorion** [comment]
> Haven't looked into disposals or cables but I'll do so later today. Bee _appeared_ to already have the changes from the PR that says it fixes multi-z disposals but I'll do a closer comparison of the code.

All i know is disposals dont properly connect on what im mapping

**Comment by williamcll** [comment]
> Haven't looked into disposals or cables but I'll do so later today. Bee _appeared_ to already have the changes from the PR that says it fixes multi-z disposals but I'll do a closer comparison of the code.

Run corgstation and you'll see all the issues that comes up. If you get it to work I might cancel my corgstation PR because I love multi-Z

**Comment by covertcorvid** [comment]
@williamcll @zeskorion Can you elaborate on what's happening with the disposals? Is it all multi-z transfers that cause problems, or is it the delivery/tagging system? Does it happen every time or only sometimes? Just riding one pair of chutes up and down didn't immediately create issues, and the 50 toy swords I dumped in the trash seemed to arrive in the package room okay.

**Comment by zeskorion** [comment]
> @williamcll @zeskorion Can you elaborate on what's happening with the disposals? Is it all multi-z transfers that cause problems, or is it the delivery/tagging system? Does it happen every time or only sometimes? Just riding one pair of chutes up and down didn't immediately create issues, and the 50 toy swords I dumped in the trash seemed to arrive in the package room okay.

i have had disposals work sometimes, but only with one specific direction- multz trunks only work in one direction from what i can see

**Comment by covertcorvid** [comment]
https://user-images.githubusercontent.com/17987483/165646937-1f917fe9-536a-4e6f-91e6-75e7014adb6c.mp4

The simple version seems like it's doing alright.

Flushing stuff down the engineering and library garbage chutes on Corg ends me to cargo as it should. I have noticed that tagging a package and sending it into the delivery office's chute bounces back and forth between the two sorting flip pipes before going to waste disposal, no matter which Z they're tagged for though.

Edit: I have fixed cables though

**Review by PowerfulBacon — APPROVED** [review]
Good testing section

**Pull request merged**
