### PR TITLE
Detective adjustments

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

 - The detectives gun now spawns in a secure locker, which unlocks with armoury access, emagging or when the alert level raises to or above blue.
 - The forensics scanner no longer spawns in the detectives locker, it is accessible without a detective through cargo.
 - The armour values of the detectives armour values have been altered. It is now weaker overall but better than the trenchcoat against melee attacks and bullets.
 - The armour values of the detectives trenchcoat have been altered. It is stronger against energy based weaponry than the regular armour vest, but weaker against projectiles and melee weapons.
 - The detective no longer has security mech access, prison cell access or mineral access.
 - They no longer spawn with a police baton.
 - Their offices no longer have batons, cuffs or sechuds on all maps.

## Why It's Good For The Game

The detective is a role whose primary function is to investigate crimes and relay them to security. They shouldn't be given roundstart arresting gear, if security wants to promote them then that is the point in which they should be given their arresting capabilities.

They are also an investigative role, once they have figured out who they are after, they can then relay their evidence to security and need self defense or offensive tools. They should be avoiding uncesseary combat, and as such have had their weapons and arresting tools removed from roundstart accessible gear. Their revolver is available to them when the alert raises to blue. Once a threat is confirmed, they can have some combat capability however while on green they have none.

Their armour values have been adjusted to be weaker overall, the regular security vest is slightly stronger than the detective's vest. The detective's overcoat has had its armour values adjusted to make it not strictly weaker than the vest.

Access to the detective's scanner has been made more restrictive. This means that security needs the work of the detective and can't enter their office to steal the scanner themselves. If there is no detective, however, the scanner can still be purchased through cargo to prevent investigation from being entirely impossible.

Was going to increase their job count to 2, however keeping it as a unique role won't have poor consequences in the case that the detective is an antagonist; if the detective doesn't perform their duties, then they risk being looked into by the rest of security (mainly the HOS) and can be fired or replaced once their scanner is confiscated from them.

## Testing Photographs and Procedure

image

image

image

image

image

## Changelog
:cl:
balance: The detectives armour has been weakened. It is stronger against melee and bullets when compared to the detective's overcoat, but is still weaker when compared to a regular armour vest.
balance: The armour values of the detective's overcoat have been modified. It is stronger against energy based weapons when compared to the detective's vest.
balance: The detective no longer spawns with arresting tools or weapons of any kind. Any weapons or tools on maps in their office have been removed.
balance: The detective's revolver is now stored in a weapon closet and is unlocked when the alert level raises to blue, or when the HOS swipes their ID and unlocks the case. If the alert level lowers, the detective should result their revolver and then shut the door when it will then automatically lock.
balance: The forensics scanner now spawns solely on the detective's body. This means there is no spare scanner at roundstart, meaning that security need to rely on the information provided by the detective. If there is no detective, the scanner can be purchased from cargo instead.
tweak: Gun closets now have slightly stronger armour than secure closets and will start shut by default. A close door button has been added to their 'UI'.
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
I hate the locker sprite and UI

**Comment by PowerfulBacon** [comment]
Thought the locker sprite was quite good. The UI is ugly, but thats the way of the gun case

**Comment by zeskorion** [comment]
them having sechuds to access records and mark people should be fine

**Comment by PowerfulBacon** [comment]
If they want to update records they can use their PDAs or a security records console imo

**Comment by CydiaLamiales** [comment]
I do disagree with the removal of the baton but I like the gun being restricted.

**Comment by Fronsis** [comment]
> I do disagree with the removal of the baton but I like the gun being restricted.
That particular baton is pretty useless in almost every ocassion, it's way worse than the telescopic baton (or it gives me that feel and same according to wiki) and since the detective is not usually carrying a flash (besides the one some stations gave you now zero chances with this PR) you can't really do much, it's pretty much a novel item at the current meta.

The thing about removing the single extra det scanner is that it heavily damages low-pop shifts, i've been playing a lot of Detective lately and i've noticed that ever since the forensic scanner got removed from the lathe there has been more ''respect'' into letting the detective do his job, instead of having an officer being a ''one-man-army'' doing everything to catch a criminal, the only times i've seen HoS/Warden use the extra one is when there's no detective present (obviously) and in a lot of lowpop shifts the amount of people maning every cargo-heads of staff-sec job is very tiny and you'll have the one-two sec officers playing with their thumbs for a reasonable time.

In all honestly, this will develop into a meta of ''semi-rushing'' a purchase of essential goods security wise from cargo for the sake of having enough of everything on high-pop which is understandable and not a bad thing per se, because you'll have the RP interactions with cargo and related parties but i also think it will lead to a lot of detrimental low-pop shifts (lack of detective, qm, warden, hos, captain, etc if any of the cogs is missing the whole thing is over or delayed) And.. as someone who plays on quite a few low-pop shifts the mindsets of antagonists on that hour is... far from ideal, that's why i don't think we need to remove the extra det scanner **just yet** As i've experienced and observed myself there's been given a lot of breathing room for the detective to do his job instead of having a HoS/Warden/Officer do it all themselves ever since it got removed from the seclathe but on lowshifts having that extra scanner for crimes commited early on is very handy (and it's not like an instant ANTAG CATCHER if you happen to use it on a crime scene, there's still ways to play around it)

There won't be ''many'' ocassions where the forensic kits gets purchased by sec, but at the same time that can be said for a bunch of other items cargo offers from their catalogue, it's a good thing to have as an option but it shouldn't be as mandatory as you propose, that of course is just my opinion as someone who's been playing detective a lot ever since the lathe got that option removed.

As for the removal of the sechud eeeh mixed feelings, i reckon that most detective mains will ask for a sechud the moment the alarm gets raised to Blue just because it's an important tool to identify suspects and to aid with their location, it would be very sad passing by next to a person set to arrest who murdered seven people just because you have regular sunglasses (obviously you won't arrest him but you can at least notify sec since you're an extra pair of walking legs with eyes) Same reason some Captains also get Sechuds it's just the ''meta'' and again it's not like we're in a need to handhold the antags, they're in a very strong state and most of the cases depends on the players and their individual skills.

For the balances about the coat and armor seems nice to have a reason to choose wisely what you'll be wearing!

Since you're revisiting the items for the detective, i've noticed some Det's office lack Cameras would it be possible to add them? While of course you can just go to a lathe and print it i just think it's a nice thing to offer round-start to encourage their usage!

(Another thing the Detective might need is the ''wheel-menu''(picking borg module for example) to choose the skin for the revolver, at the moment you get an ugly preview of the image of the revolver skin on a 1x1 but that's okay since it's not that big of a priority :p )

**Comment by PowerfulBacon** [comment]
Will address these comments next weekend, will make scanner spawn in locker if no detective spawns on the map.

**Comment by Denesta** [comment]
I have always seen the baton as a defensive tool do to the leg sweep, rather than an arresting tool. If an antag tries to take you out while you are investigating, leg sweep, run, report to the rest of sec. I guess other people may using it as a beating stick but I have only ever used it for the handy leg sweep.

Also for the sec hud, you still need to keep an eye out for people marked to be watched or arrested. So you can call out to the rest of sec if you see them. Especially people marked to be watched. That's part of investigating.

**Comment by itsmeow** [comment]
Update Fland

**Comment by CydiaLamiales** [comment]
Also I'm still against the removal of the batong.

**Comment by PowerfulBacon** [comment]
Tested and working on 515

**Comment by CydiaLamiales** [comment]
Don't new UIs need to be TGUI? That's what I was told with the martial art combo window PR.

**Comment by PowerfulBacon** [comment]
It isn't a new UI

**Pull request closed without merging**
