### PR TITLE
You need 90 seconds before ghostize yourself

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
You need 90 seconds before ghostize yourself
Once you become `soft-crit`/`unconscious`, a timer preventing force-ghost starts.
After 90 seconds passed, you are allowed to ghost yourself with no penalty.

(Check conversations for the suggested change)

## Why It's Good For The Game

Attacked by someone then go ghost instantly after you become crit.
Ghostize yourself when xeno disables you but before they hug you.

Quite metagaming, isn't it?

At least you're allowed to do that if you have antag datum.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image

image

</details>

## Changelog
:cl:
add: ghost(=succumb) verb needs 90 seconds timer once you fall into soft-crit or unconscious. If you dare it, it would work the normal ghost verb, and it's round-removal of yourself. Antagonists will ignore this timer, so they can use this to frame someone when they fall into crit.
code: changed some ghost & succumb verb logic
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
> ## Why It's Good For The Game
> Attacked by someone then go ghost instantly after you become crit.

This isn't really a reason. I can see it's use in xenos because they have a mechanic that directly utilizes it, but what's the point of applying it to regular people?

If someone is in crit and just wants to leave, you should let them ghost.

If it's stuff like contractors or abductors, it's the contractors fault for letting them get hurt enough to go into crit.

**Comment by EvilDragonfiend** [comment]
> If someone is in crit and just wants to leave, you should let them ghost. Keeping options like DNR and Ghostizing open are important features to making people comfortable playing imo

normal ghostize option comes as doublecheck if they really want it

**Comment by EvilDragonfiend** [comment]
hmm I need to make the logic cleaner...

**Comment by EvilDragonfiend** [comment]
So, let's say you need to capture someone. You want to brainwash them or have them as a captive, but it's incredibly frustrating when they instantly ghostize themselves. I don't think it's contributing RP conflict very well.
With this, Antags at least can prepare cuffs and medicines, then take their target as captive, instead of reviving them because they force-ghostized themselves.

If they don't want to play any longer, they just can ghost anytime, then their body will automatically die then set DNR. If they want to play, they should just wait for some seconds giving an antag some chance.
even if the ghost time isn't enough but they whisper last words when they're near death, they'll automatically die without DNR feature.

**Comment by Tsar-Salat** [comment]
> So, let's say you need to capture someone. You want to brainwash them or have them as a captive, but it's incredibly frustrating when they instantly ghostize themselves. I don't think it's contributing RP conflict very well

I don't understand why we are attaching this to every death now though. I suppose it makes sense in the context of capture, but that's a really small occurence in the grand scheme of things.

95% of deaths are completely unrelated to capture. Having to wait over a minute just to die seems really excessive.

**Comment by Tsar-Salat** [comment]
As an alternative, maybe make this a trait. 

If someone enters the `UNCONCIOUS, SOFTCRIT` state and has the trait, they follow the `NO_GHOSTIZE` timer.

You could then attach this trait to something like being attacked by carbons. 

This would exclude all deaths unrelated to carbons, and thus let people killed by fire, space, or lavaland or most other methods play fine.

**Comment by EvilDragonfiend** [comment]
That's a good idea

**Comment by Fronsis** [comment]
> So, let's say you need to capture someone. You want to brainwash them or have them as a captive, but it's incredibly frustrating when they instantly ghostize themselves. I don't think it's contributing RP conflict very well. With this, Antags at least can prepare cuffs and medicines, then take their target as captive, instead of reviving them because they force-ghostized themselves. 90 seconds are fairly enough to wait to ghostize for themselves, and to apply medicines to their captive for antags.
> 
> If they don't want to play any longer, they just can ghost anytime, then their body will automatically die then set DNR. If they want to play, they should just wait for some seconds giving an antag some chance. even if the ghost time isn't enough but they whisper last words when they're near death, they'll automatically die without DNR feature.

Wouldn't this fall as an administrative/player issue? It mostly happens with Xenomorphs, the early succumbs and sooometimes with Abductors(though all iterations that i've seen led to a ban) i don't really remember people going DNR/ghost when they're in crit most of the time it's with antags trying to get the last laugh against sec after performing something

**Comment by Tsar-Salat** [comment]
> Wouldn't this fall as an administrative/player issue?

Sure. I don't see why this would exclude us from enforcing it through code though.

**Comment by githubuser4141** [comment]
Isn't it a bit weird to try to accept crit as being a thing that: IRL, would require ICU support + immediate surgery for any attempt of survival, but also accept crit being a thing that an antagonsit can casually put you in, then heal you out of with some basic bruise packs? It's already immersion breaking to go into lethal crit because you scratched at an itch, or stubbed your toe, there's basically no immulsions left over once an antag's critted you (via e-sword or gunshot) then un-crits you by using sutures or a glorified bandage.

**Comment by Tsar-Salat** [comment]
> Isn't it a bit weird to try to accept crit as being a thing that: IRL, would require ICU support + immediate surgery for any attempt of survival, but also accept crit being a thing that an antagonsit can casually put you in, then heal you out of with some basic bruise packs? It's already immersion breaking to go into lethal crit because you scratched at an itch, or stubbed your toe, there's basically no immulsions left over once an antag's critted you (via e-sword or gunshot) then un-crits you by using sutures or a glorified bandage. A lot of the time when you crit, there's not even any major disruption to the body's systems, and when you un-crit there's no reason that it'd actually un-crit you.

This is bee. We don't have sutures or wounds.

**Comment by EvilDragonfiend** [comment]
I need to investigate this but my mental resource isn't sufficient to consider all situations that would count as engaging combat. I will close this for right now, and going to open when I find out the logic to be made.

**Pull request closed without merging**
