### PR TITLE
Flashbang changes (Nerf? Rebalance?)

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Flashbangs are now brighter.
Flashbangs blindness will blind you with an intensity of 2. This means that sunglasses alone won't protect from the bright light.
The knockdown and paralysis caused by the light is protected by a flash protection of 1 however. (Sunglasses).

The effect of flashbangs is now directly proportional to the distance.
This means that rather than dividing by the distance, when you are 0m away from the flashbang you will get 100% of the effect and when you are 7m away you will get 0% of the effect.

## Why It's Good For The Game

Security (And anyone else just wearing glasses) will now be affected by the flashbang blindness too, meaning you can't just drop one in the middle of a fight and continue attacking while everyone around you falls defenseless.
Instead, to use them effectively you will have to throw them into a room and wait for detonation before breaching in, or throw it and run away which also gives the person its being used against more time to fallback. They will be a lot less effective when used in open spaces where its easier to run away from and more of a tool to fight against people hiding away in their base or against large crouds of people.
Considering it applies up to 20 seconds of knockdown when up close and requires hard to obtain items to counter it is incredibly powerful.

Going to go ahead and say this is a nerf since despite blinding crims with glasses, it will blind uncoordinated members of security and is much more difficult to use in a whim in the middle of combat.

Also there is no minimum time on the effect of the flashbang, meaning at the border of the flashbang you will get knocked down for proportional times rather than a minimum of 6 seconds.

As a side effect to the distance calculations, flashbangs stunning effect will have a circular radius of 7m rather than a 15x15 cube around it meaning that being on the very corner of the flashbang . The flash effect still acts in a square radius, but the bang and stun effects are in a circular radius.

Distance: 0
Paralysis: 2 seconds
Knockdown: 20 seconds

Distance: 1
Paralysis: 1.7 seconds
Knockdown: 17 seconds

Distance: 2
Paralysis: 1.4 seconds
Knockdown: 14 seconds
etc..

Distance: 7
Paralysis: 0 seconds
Knockdown: 0 seconds

## Changelog
:cl:
balance: Flashbangs now blind with an intensity of 2 meaning wearing glasses alone will still blind you. (You will not get stunned while wearing glasses).
balance: Flashbangs effect is directly proportional to the distance away.
/:cl:

### CODE REVIEW

**Comment by Mat05usz** [comment]
Good change, sec mains cope

**Comment by AnCopper** [comment]
Fun fact: the part of flashbangs that incapitate people is neither the flash or the bang, it's the concussion wave.

**Comment by githubuser4141** [comment]
> Fun fact: the part of flashbangs that incapitate people is neither the flash or the bang, it's the concussion wave.

I hope this still lets mechs give you some protection as an armored, sealed vehicle should protect block the concussion wave completely.

**Comment by ghost** [comment]
You should also get rid of the adjustable timers. You can set them to 1 second, activate and toss at someone to get the maximum effect without them having any chance of escaping.

**Comment by DatBoiTim** [comment]
> Fun fact: the part of flashbangs that incapitate people is neither the flash or the bang, it's the concussion wave.

Well the flash and bang add to the utility of them. Yeah they get disoriented by it, but its the blinding and deafening that also helps.

**Review by qwertyquerty — DISMISSED** [review]

**Review by qwertyquerty — APPROVED** [review]

**Pull request merged**
