### PR TITLE
Nar'sie now plays music

### PR DESCRIPTION
**Pull request by Therealdoooc213**
## About The Pull Request
When Nar'sie is summoned, it will now play awesome music for everyone to hear.

Beautiful music by Bolgarich
https://www.youtube.com/watch?v=NqNHKfTAvcw
image
(Creative Commons Attribution license)

## Why It's Good For The Game
Nar'sie is incredibly rare and its weird that it doesnt have its own music. Bolgarich's music perfectly encapsulates the feeling of dread and a need to run the crew would be feeling as nar'sie is summoned.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

https://github.com/user-attachments/assets/69b856ff-f92d-4923-bdf0-b44f86504d08
(MEGA COMPRESSED VIDEO! ONLY TO SHOWCASE HOW LONG IT LASTS AND HOW IT SYNCS UP WITH THE NUKE)

https://www.youtube.com/watch?v=NqNHKfTAvcw

</details>

## Changelog
:cl: Bolgarich
soundadd: Nar'sie now plays music when it spawns in
/:cl:

### CODE REVIEW

**Comment by Therealdoooc213** [comment]
> > 🆑
> 
> 👁️ 👁️

oops

**Comment by Therealdoooc213** [comment]
> how did he know
> 
> image

No comment.

**Review by Dejaku51 — APPROVED** [review]
has the atrributions, looks good

**Review by EvilDragonfiend — APPROVED** [review]
Dejaku is fully responsible with this approval :trollface:

**Comment by Dejaku51** [comment]
> Dejaku is fully responsible with this approval :trollface:
image

**Review by Crossedfall — APPROVED** [review]
Attribution seems good to me

**Pull request merged**
