### PR TITLE
[SOUND] Improves ambientation

### PR DESCRIPTION
**Pull request by Kmc2000**
## About The Pull Request

Hey hey beeple, Kmc here. This PR utilises a BYOND system that's been around since like, 2005, but /tg/code never seemed to use (I believe bay and goon do use it, though I haven't taken a look at their systems). Areas can now be assigned soundscapes via the sound_environment variable, which will give them a different feel based off of the presets provided.

Example (This shows some common areas both our servers share, no NSV specific ones):
https://streamable.com/nh08ge

Notable examples:
Engineering now sounds vast and metallic
Maintenance now sounds cold and cramped
Hallways sound large and echoey
When drunk , asleep, or drugged though, your perception of sound is altered:
https://streamable.com/ycg91p

## Why It's Good For The Game

Improves IMMERSHUN at very little cost.

## Changelog
:cl: Kmc2000
add: Different areas (rooms) now have unique soundscapes, try walking down a hallway!
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Leave a comment in the code about the BYOND issue to avoid.

**Review by ike709 — DISMISSED** [review]

**Comment by ike709** [comment]
DNM pending investigation of weirdness.

**Comment by PowerfulBacon** [comment]
Ah awesome, maybe we can have distant sounds muffled too in the future somehow

**Comment by ike709** [comment]
That's already a thing.

**Comment by ike709** [comment]
It seems to work, dunno what players are talking about.

However, players complain that there's *too much* echo still.

**Review by ike709 — APPROVED** [review]

**Comment by ike709** [comment]
YOLO

**Review by ike709 — CHANGES_REQUESTED** [review]
Apparently this runtimes like crazy. Once you fix that it'll be good for merge.

**Comment by ike709** [comment]
```
[05:56:46] Runtime in sound.dm, line 47: Cannot read null.sound_environment
proc name: playsound local (/mob/proc/playsound_local)
src: Aurelius Fulton (/mob/living/carbon/human)
src.loc: the floor (65,39,5) (/turf/open/floor/plasteel)
call stack:
Aurelius Fulton (/mob/living/carbon/human): playsound local(null, 'sound/effects/space_wind.ogg', 10, 1, null, null, 0, 1, /sound (/sound))
Aurelius Fulton (/mob/living/carbon/human): experience pressure difference(0.238457, 4, 0, null)
the floor (65,39,5) (/turf/open/floor/plasteel): high pressure movements()
Atmospherics (/datum/controller/subsystem/air): process high pressure delta(0)
Atmospherics (/datum/controller/subsystem/air): fire(0)
Atmospherics (/datum/controller/subsystem/air): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
```

**Comment by PowerfulBacon** [comment]
There is a serious problem with this, nearing the end of the round, suddenly all reverb went to the fucking max or something and everything was insanely echoey

EDIT: The testmerge was over at this point, if this gets de-testmerged the echoing doesn't stop

**Comment by ike709** [comment]
I don't think this PR is worth it honestly.

**Pull request closed without merging**
