### PR TITLE
Adds a tip about "Supermatter SLIVER" for random individual vocabulary

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
Adds a tip about "Supermatter SLIVER" for random individual vocabulary
* There is no supermatter SILVER. There is only supermatter SLIVER.

## Why It's Good For The Game
This word is easy to mistake.

## Testing Photographs and Procedure

No need

## Changelog
:cl:
add: Added a tip to sillytips.txt: There is no supermatter SILVER. There is only supermatter SLIVER.
/:cl:

### CODE REVIEW

**Comment by githubuser4141** [comment]
> is it actually spelt sliver? That's definitely a mistake lmao

It shouldn't be a mistake, it matches up with the word's irl definition 
image

**Comment by DrDuckedGoose** [comment]
It's definitely meant to be 'sliver', 'silver' wouldn't make sense.

**Review by PowerfulBacon — DISMISSED** [review]
This should be a meme tip

**Comment by EvilDragonfiend** [comment]
> This should be a meme tip

Well, I am not witty enough to write something funny for that. Any suggestion?

**Comment by PowerfulBacon** [comment]
just move it to the meme tips file

**Comment by EvilDragonfiend** [comment]
> just move it to the meme tips file

I figured. it's `sillytips.txt`. It has only 5% chance to appear, and it has 48 lines, which means 0.1% chance to see this message.
When there are not a few people who knows the word incorrectly, including Bacon, I still think it's worth it to be the standard tips. Actual helpful tips are 284 lines(including this tip), and 95% chance to appear. It's still 0.3% chance to appear.

but also, silly tips don't do anything. Correcting people's vocabulary is a positive thing, right?

I will move it to the silly tips if you still think it belongs to there.

**Review by Rukofamicom — APPROVED** [review]
I feel like this is gonna make some people feel bad when they first see it.

**Comment by PowerfulBacon** [comment]
Silly tips are for meme tips which this is. This doesn't actually give any advice

**Comment by PowerfulBacon** [comment]
I still stand by my last review, meme tips go in the meme tips file.

**Comment by EvilDragonfiend** [comment]
addressed

**Pull request merged**
