### PR TITLE
changes resolution of debug window in Windows 11 environment

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
changes resolution of debug window in Windows 11 environment

## Why It's Good For The Game
windows 11 is cringe

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

# before

-----

image

# after

</details>

## Changelog
:cl:
code: debug window (creation game pannel) has a better resolution in windows 11 environment
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
This just changes the resolution of debug window in all environments

**Comment by EvilDragonfiend** [comment]
> This just changes the resolution of debug window in all environments

that's a minor change. it won't be that different in other environments.

**Comment by EvilDragonfiend** [comment]
I asked Byond forum to fix that, but It'll take ages or might not be possible to fix on their side, so I beg this, please.

**Comment by itsmeow** [comment]
Mine does not have this issue on win11

**Comment by EvilDragonfiend** [comment]
image

shit. I think it explains why

**Pull request closed without merging**
