### PR TITLE
Adds 16 random maintenance rooms

### PR DESCRIPTION
**Pull request by Agameofscones**
## About The Pull Request

Adds 16 random maintenance rooms that I told Zesko I would like, half a year ago.

image

image

## Why It's Good For The Game

Variety is cool I guess. Random maintenance only gets better the more maps ya got because of the potential adjacency combinations on maps with denser maintenance. Most of these are aimed at breaking  up pathing in maintenance instead of being big open rooms, without being too intrusive so as to block entire areas off.

All maps have an entrance on each side, so they shouldn't block anything layout wise.

## Changelog
:cl: Triiodine
add: Added 16 new random maintenance rooms, 8 10x10s, and 8 10x5s
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Not sure if i'm a fan of the tesla generator there, should probably replace it with a showcase/cardboard cutout.

**Comment by Cenrus** [comment]
My favorite is the six sectors one.

**Comment by Archanial** [comment]
okay ratburger is based

**Comment by Agameofscones** [comment]
> Not sure if i'm a fan of the tesla generator there, should probably replace it with a showcase/cardboard cutout.

sure, I can make it cardboard

**Comment by utilbird** [comment]
Pffft, sad

**Review by qwertyquerty — DISMISSED** [review]
sk

**Comment by PowerfulBacon** [comment]
I never saw this PR, restarting checks

**Review by PowerfulBacon — DISMISSED** [review]

**Comment by PowerfulBacon** [comment]
Fails checks

**Comment by ike709** [comment]
`/datum/map_template/random_room/sk_rdm132` has a turf decal in nullspace, according to the runtime.

**Comment by Agameofscones** [comment]
> `/datum/map_template/random_room/sk_rdm132` has a turf decal in nullspace, according to the runtime.

Embarrassing, not even one of my maps, but ok. will fix

**Comment by ike709** [comment]
YOLO

**Pull request merged**
