### PR TITLE
ports 5 piping layers from tg

### PR DESCRIPTION
**Pull request by BrumalLake**
## About The Pull Request
mappers shouldn't use 1 & 5 they're already for areas which have a lot of distro
https://github.com/tgstation/tgstation/pull/53278
https://github.com/tgstation/tgstation/pull/53382
https://github.com/tgstation/tgstation/pull/53829
https://github.com/tgstation/tgstation/pull/57273
increases amount of piping layers to 5 but excludes heat exchange if you try
image

image

multi-z demonstration on layers 1 & 5 (plasma & air were spawned filled and nob and no2 canisters were empty relabeled canisters)
image
image
image

## Why It's Good For The Game
more room to work with

## Changelog
:cl: lordScrubling, Ghilker, nicbn
add: atmospherics now has 2 additional layers; excludes HE pipes
add: multi-z adapters can now be placed with rpds
tweak: layer manifold has its volume increased from 280L to 350 to compensate for increase in layers
/:cl:

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
Owie. Something I never knew I wanted!

**Comment by Tsar-Salat** [comment]
Beautiful. Glad they found a way to fix the mixer bug through pixel-shifting.

**Comment by BrumalLake** [comment]
image
the fate of every other pr with this label

**Comment by Archanial** [comment]
Code looks mostly fine.
Still needs testmerge.

**Comment by PowerfulBacon** [comment]
:key:

**Review by PowerfulBacon — COMMENTED** [review]
Plasma refinery is invisible

**Comment by BrumalLake** [comment]
oh hell

**Comment by BrumalLake** [comment]
> Plasma refinery is invisible

resolved

**Review by Archanial — APPROVED** [review]

**Comment by williamcll** [comment]
this doesn't bring it the color connection that /tg/ has right?

**Comment by Tsar-Salat** [comment]
> this doesn't bring it the color connection that /tg/ has right?

This pull request does not include the bullshit that is Smart Pipes, no.

Here is the original smartpipe pr: https://github.com/tgstation/tgstation/pull/58038

Bee players are pretty reactionary with wires and pipes anyway.

**Review by Archanial — APPROVED** [review]

**Pull request merged**
