### PR TITLE
Desynchronizer rebalance

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

You can't do anything while desynced anymore

## Why It's Good For The Game

desync op

## Changelog
:cl:
balance: you can't do anything while desynced now
/:cl:

### CODE REVIEW

**Comment by eLeCtrOssSnake** [comment]
Are you dutch?
Nice pr though.

**Comment by utilbird** [comment]
Desync is already _extremely_ powerful when used in the right hands, there are few ways to force them out/kill them. Removing this allows someone to grab like 3 desyncs and chain up to 1500 seconds of complete invulnerability

**Comment by ike709** [comment]
I like it blocking you from doing stuff but dislike it protecting you from all damage. It's already OP.

**Comment by zeskorion** [comment]
couldnt you just make this use the same proc handcuffs do, cuz handcuffs are magic anti-action bands

**Pull request closed without merging**
