### PR TITLE
Removes the Skinsuit from everyones survival box, places them into Emergency air lockers instead.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This removes the Skinsuit & Helmet from the standard survival box and places them into the Airtank version of Emergency Oxygen Lockers.
## Why It's Good For The Game

I think by now we are way past the point where we constantly need skinsuits to hold our hand because of fastmos, having a pressure-proof suit available to you all the time screws with balance and makes hullbreaches a minor nuiscance at worst, this is especially broken for IPC's since they already don't take cold damage.

## Changelog
:cl:
balance: Skinsuits are no longer in the standard survival box, instead they spawn in airtank emergency air lockers.
/:cl:

### CODE REVIEW

**Comment by eLeCtrOssSnake** [comment]
Why?

**Comment by ghost** [comment]
> Why?

i explained why.

**Comment by felceryan** [comment]
there is no reason for this.

**Comment by Effemu** [comment]
do you enjoy being ridiculed?

**Comment by ike709** [comment]
Why are all of your PRs bad?

**Comment by ghost** [comment]
> Why are all of your PRs bad?

because i do what i want.

**Comment by zeskorion** [comment]
> > Why are all of your PRs bad?
> 
> because i do what i want.

You're like me without the cool shit

**Comment by Vexylius** [comment]
you're like zesko, but your PRs are not getting merged

**Pull request closed without merging**
