### PR TITLE
Adds Unum deck

### PR DESCRIPTION
**Pull request by Dingo-Dongler**
## About The Pull Request

Adds a new deck type to the game, Uno. Placing stuff face up is still a bit of a mess, so some work might still be needed there (overlay of top card on hand or some way to flip decks).

## Why It's Good For The Game

Probably one of the simplest card games, so it might actually be possible to play during a round.

## Changelog
:cl:
add: Added the card game Uno! Get a deck from your local Good Clean Fun vendor.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Isn't UNO copyrighted so it would have to be something else?
I dunno, crossed needs to say about this

**Comment by Dingo-Dongler** [comment]
IDK about legality, I just assumed that if tabletop simulator could get away with it I could too.

**Comment by qwertyquerty** [comment]
@Crossedfall verdict?

**Comment by qwertyquerty** [comment]
Call it Odin, one in German.

**Comment by Crossedfall** [comment]
Would be preferable to have a genericish sounding name. Similar to how the Cards Against Humanity game was renamed to Cards Against Spess

**Review by Crossedfall — CHANGES_REQUESTED** [review]
Would be preferable to have a genericish sounding name. Similar to how the Cards Against Humanity game was renamed to Cards Against Spess.

Relevant trademark: http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4804:64lxyl.3.1 | https://trademarks.justia.com/730/15/uno-73015277.html

**Comment by Crossedfall** [comment]
> 
> 
> Call it Odin, one in German.

Einer?

**Comment by Dingo-Dongler** [comment]
How does Unum sound? I can change the card back design too, even though it's my proudest sprite :(

**Comment by Crossedfall** [comment]
> Unum

The insurance company? Also yeah, please do remove their logo. Sorry :(

**Review by Crossedfall — APPROVED** [review]
Changes are fine by me.

**Pull request merged**
