### PR TITLE
Revert "Tourettes can combine with voice of god for an... interesting effect"

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

Reverts BeeStation/BeeStation-Hornet#9081

## Why It's Good For The Game

yeah this was kind of just an impulsive idea i coded in like 10 minutes, on further thought it'd not a very good idea, bc it's just gonna get annoying and spammy most likely.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

23-05-24-1684964902-dreamseeker

</details>

## Changelog
:cl:
del: Tourettes no longer combines with voice of god.
/:cl:

### CODE REVIEW

**Comment by JixS4v** [comment]
Nah leave it, it'll be like a cool easter egg

**Comment by Rukofamicom** [comment]
I think it's funny to have, players were bound to jump on board with seeing it right after it merged. It'll fall into obscurity as an occasional funny soon enough.

**Comment by itsmeow** [comment]
Yea... whatever :trollface:

**Review by PowerfulBacon — APPROVED** [review]
If this has no cooldown then I can see why it would get annoying. I also dislike poor modularity so I'm happy to accept a revert.

**Pull request merged**
