### PR TITLE
Witch Wing Wing Sprite Port

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request

Ports the Witch Wing moth wing from /TG/ wtih a new sprite for the open wings version.

## Why It's Good For The Game

The more the merrier! More customization for your character is always good. Also now you can cosplay as the moth that says "You look very mothable"

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

back
front
side
imagen

https://github.com/BeeStation/BeeStation-Hornet/assets/148357670/be90e452-41fd-4365-906c-f030db95431d

</details>

## Changelog
:cl:  Varo; @FuryMcFlurry 
add: new moth wing sprites
add: new moth open wing sprites
/:cl:

### CODE REVIEW

**Comment by CydiaLamiales** [comment]
You should credit the original spriter in the changelog

**Comment by ClownMoff** [comment]
Done, thanks

**Comment by HowToLoLu** [comment]
> Done, thanks

Slight formatting issue- put the author name here:

🆑 Varo, OG spriter name here
add: new moth wing sprites
add: new moth open wing sprites
/🆑

**Comment by ClownMoff** [comment]
Thanks!!

**Comment by Penwin0** [comment]
What's the change to m_moth_wingsopen_moonfly_BEHIND?

**Review by Penwin0 — APPROVED** [review]

**Pull request merged**
