### PR TITLE
Added Heretics from /tg/station

### LINKED ISSUE #2004: [Bounty] Merge the Eldrich Cultist/Heretic antag from TG
There's a cool antagonist that was recently added to the TG branch called heretic, which is kinda like a less OP version of shadowlings. I've played a couple rounds of this in the past and had a lot of fun, and it'd be cool to see this gamemode here too.

https://hackmd.io/@tgstation/r1tDpqEsI https://github.com/tgstation/tgstation/pull/51199

### PR DESCRIPTION
**Pull request by xboxnoob**
## About The Pull Request

This PR port heretics from TG to Beestation, a new type of antag (huge thanks for Zesko for helping me port this shit)

## Why It's Good For The Game

It adds new antag type which makes things less stale

## Changelog
:cl:
add: Added new heretics
soundadd: added sounds for heretics
imageadd: added icons needed for heretics
code: added heretics and tweaked it so it would compile
/:cl:
Credits to @EdgeLordExe

---------

Resolves #2004

### CODE REVIEW

**Comment by xboxnoob** [comment]
fuck i need fix my map

**Comment by xboxnoob** [comment]
#2004 this is the related bounty

**Comment by xboxnoob** [comment]
anyone know anything about interfaces

**Comment by WhyIsCaeciliusTaken** [comment]
You should probably credit the original creator of the PR.

**Comment by xboxnoob** [comment]
idk why the mapdiff is getting fucked up but this the final commit, for some stupid reason i cant figure out items dont spawn when the heretics spawn and i cant fix it so i am gonna open the pr and hopefuly someone else can figure out whats wrong

**Comment by PowerfulBacon** [comment]
Database changes and travis changes

**Review by Crossedfall — CHANGES_REQUESTED** [review]
You need to either merge in or rebase ontop of the latest master before we can begin review.

**Comment by TeomanTheGreat** [comment]
This PR is gonna be epic if it gets merged when fixed

**Comment by TeomanTheGreat** [comment]
Lmao the guy who made the code itself made a pr for it too. rip this pr.

**Comment by zeskorion** [comment]
closing this, as it has grown stale and a pr from the original creator is open

**Pull request closed without merging**
