### PR TITLE
[PORT] Anonymizes chapel intercom, so chaplain doesn't know who's talking.

### PR DESCRIPTION
**Pull request by KubeRoot**
## About The Pull Request

Ports the following PR:
- https://github.com/tgstation/tgstation/pull/54476

When using the confessional intercom, your name now shows up as "Unknown". Note that you can still change the frequency of the intercom to talk on other non-encrypted channels anonymously.

Replaces the intercoms on maps with a new subtype that doesn't require varedits on the map level. Adds intercoms and a grille to corg's confessional, which didn't have either unlike other maps.

I could also integrate this with wires, to let you, for example, enable anonymization by cutting a specific wire or temporarily enable it by pulsing it. This PR doesn't do that (right now) though, because I'm not sure how to integrate that with mapped anonymization and if the maintainers would want it.

## Why It's Good For The Game

Mostly roleplay fluff for the rare case somebody uses the confessional, with potential miscellaneous use-cases.

## Changelog
:cl: KubeRoot, EdgeLordExe
add: Radios now have code support for anonymization
tweak: The intercoms in chapel confessionals will now hide your name
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
I'd like this more if it wasn't a magic variable and was actually controlled by some part of the intercom as an addin.

But this is so minor and specific I'm fine with it, how does it interact with AI tracking?

**Review by Archanial — APPROVED** [review]

**Comment by KubeRoot** [comment]
> I'd like this more if it wasn't a magic variable

As I mentioned in the PR body, I could try to make it use a wire, similar to the prison intercoms that start with the TX wire cut.

> how does it interact with AI tracking?

I forced a human standing next to the intercom to say `;test`, then tried to track them by both the messages from their headset and the intercom:

image

From what I can tell, the AI does not know who was speaking through the intercom and cannot track them. That said, I'm no AI expert so I might be missing something.

**Comment by francinum** [comment]
The problem with making it a wire is it makes it super easy to get.
It'd work best if it was some sort of addin board or something, but again this is good enough.

**Review by qwertyquerty — APPROVED** [review]

**Comment by qwertyquerty** [comment]
@PowerfulBacon code owner

**Review by Crossedfall — APPROVED** [review]
Bypassing Bacon's approval while he's out. Merging per Qwert's review.

**Pull request merged**
