### PR TITLE
(PORT) Recolors the computer circuit boards and machine circuit boards into department-based colors.

### PR DESCRIPTION
**Pull request by r1ks-iwnl**
## About The Pull Request
Ports tgstation/tgstation#44738 made by Nickkoranda and sprites by Onule

## Why It's Good For The Game
image
Screenshot_4
Makes circuit boards far easier to recognize as they now have a specific department-based color.

## Changelog
:cl:
imageadd: Adds 8 new icons for circuit boards, based on department colors
refactor: Reorganizes computer_circuits.dm and machine_circuitboard.dm
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
This updates the extra machine boards that we have that TG doesn't, such as shuttle computers etc?

**Comment by r1ks-iwnl** [comment]
"fixes copypasting the tg code" does that

**Comment by r1ks-iwnl** [comment]
I just fixed all the undefined path errors that popped up so im not sure if it's 100% perfect but i did get it to compile without any errors and it seems to be working out, i may have missed something tho

**Comment by PowerfulBacon** [comment]
Yea checked, shuttle stuff has been done so new bee stuff is added

**Comment by SomeAngryMiner** [comment]
great concept and something we needed, but there's not enough words in god's green earth to utter the undescribable pain these boards give me.

**Comment by zeskorion** [comment]
> great concept and something we needed, but there's not enough words in god's green earth to utter the undescribable pain these boards give me.

shh shh shhh shhhhh, its ok azlan, at least its not the tinfoil envirohelm

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
