### PR TITLE
TGUI Core Updates

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

Updates to Inferno 8.2, providing better typescript support and fixing some weird inconsistencies with JSX.Element.

Do note: the flex basis PR has potential to break a lot of UIs. I checked quite a few but it's likely I missed some. Probably testmerge this.

Ports:
- https://github.com/tgstation/tgstation/pull/60961
- https://github.com/tgstation/tgstation/pull/61499
- https://github.com/tgstation/tgstation/pull/72279 (only the TS tweaks, we already have updated deps)
- https://github.com/tgstation/tgstation/pull/73457 (just the idea to update webpack, we're already updated later than that)
- https://github.com/tgstation/tgstation/pull/65686
- https://github.com/tgstation/tgstation/pull/69459
- https://github.com/tgstation/tgstation/pull/69527
- https://github.com/tgstation/tgstation/pull/71453
- https://github.com/tgstation/tgstation/pull/56721 (only the Tab changes, Section was already ported)
- https://github.com/tgstation/tgstation/pull/60208 (fixes changes added in 56721)
- https://github.com/tgstation/tgstation/pull/58483
- https://github.com/tgstation/tgstation/pull/42606
- https://github.com/tgstation/tgstation/pull/62930
- https://github.com/tgstation/tgstation/pull/64757
- https://github.com/tgstation/tgstation/pull/64885
- https://github.com/tgstation/tgstation/pull/69219

## Why It's Good For The Game

Makes our TGUI more consistent with TG and function better.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image

image

image

List wrapping

image

flex basis

image

image

image

image

image

image

image

image

image

image

image

image

image

Loading screen

image

</details>

## Changelog
:cl:
code: Updated some TGUI dependencies.
tweak: TGUI now supports DPI scaling, provided you use a BYOND version modified to use a modern browser.
tweak: TGUI LabeledLists should now wrap text by default instead of overflowing.
fix: TGUI Number inputs modals now accept negative numbers.
fix: TGUI Number inputs modals can now accept decimals and not round them.
tweak: Tabs can now have customized colors. They should also function better inside Section boxes, and have better padding and margins.
tweak: Arrow keys are grabbed by TGUI for keyboard navigation, won't move your character unless you have hotkeys off.
tweak: Improved TGUI's handling of static data on refresh, now a Loading prompt will be shown while static data is on cooldown instead of just straight up not sending it.
tweak: Multiline TGUI inputs now support line breaks, accessible via shift-enter! A maximum of two consecutive line breaks is allowed, any more than that will be automatically stripped. This only applies to input boxes that start with the multiline view enabled, and will thus not work on input boxes that aren't meant to support it.
/:cl:

### CODE REVIEW

**Review by Crossedfall — APPROVED** [review]
The editor config change is kind of irrelevant since it's handled by git already. If there are file extensions not being converted by gitattributes, then they should be added to the file. https://github.com/BeeStation/BeeStation-Hornet/blob/master/.gitattributes

The new extension looks to be fine. I'm also good with the build file changes.

**Review by PowerfulBacon — DISMISSED** [review]
The loading bar on the PDA is the wrong theme and is incredibly annoying to deal with. Please remove it, or make it on power up only instead of on shutting down programs.

**Comment by itsmeow** [comment]
I didn't even notice there was one. That's the static ui refresh bar, it only happens when you timeout on static data updates.

**Comment by itsmeow** [comment]
TM seems good

**Pull request merged**
