### PR TITLE
Removes completely unfit away missions.

### PR DESCRIPTION
**Pull request by francinum**
## About The Pull Request
Factory is just horribly unstable, the rest aren't particularly intriguing besides the two I left.

The others are just kinda eh loot balloons.

## Changelog
:cl:
del: Most of the away missions have been outmoded.
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Is the gateway even enabled?

**Comment by francinum** [comment]
> Is the gateway even enabled?

No, but this means we never need to care about these maps ever again.

**Comment by Sinestia** [comment]
I think caves, moon outpost 19 and snowcabin should stay


They're "EH" but aren't bad. The others have huge core issues

**Comment by ike709** [comment]
MO19 has a special place in my heart and lacks gamer loot.

**Comment by PowerfulBacon** [comment]
MO isnt particularly broken, you should just remove the ones that break the game if admins load them or fundamentally dont work IE factory and the syndicate death trap mission. (Keep the bad ones, just get rid of the ones that actually fuck the server if loaded)

**Comment by ghost** [comment]
space battle is getting removed? Next pr they're gonna remove the og snowdin :pensive:

**Comment by francinum** [comment]
Sure

**Comment by francinum** [comment]
OceanFish you have no place to downvote this when your away mission literally grinds the server to a goddamn halt.

**Comment by OceanFish1** [comment]
> OceanFish you have no place to downvote this when your away mission literally grinds the server to a goddamn halt.

But I did downvote it didn't I? :trollface: 
Also never seen server been breaking when mission loaded successfully

**Comment by PowerfulBacon** [comment]
Because it breakingt he server =/= insta crash. It means massive subssystem lag, lighting stops updating then the admins do absolutely stupid things like turn off critical subsystems thinking they are saving the day

**Review by PowerfulBacon — COMMENTED** [review]
Update the config to only remove removed maps.

**Comment by OceanFish1** [comment]
> Because it breakingt he server =/= insta crash. It means massive subssystem lag, lighting stops updating then the admins do absolutely stupid things like turn off critical subsystems thinking they are saving the day

I didn't mean insta crash. I saw server breaks only when mission fails to load, but I didn't get the lags you're talking about when it loaded without issues.

**Comment by PowerfulBacon** [comment]
It causes an big spike in the time it takes for some subsystems to execute. While at low load like on a private server or early in a round the effect is minimal, in longer rounds or on higher populations the effects of this can end up causing lighting to take multiple seconds to update, mobs updating at a slower rate (slimes not breeding, hostile fauna not seeing etc.) and can slow down atmospherics.

**Comment by PowerfulBacon** [comment]
@Crossedfall config

**Comment by FortSumter** [comment]
I thought the plan was to disable away missions so coders could fix the problems with them. Now we are just going to remove them, huh? Fun.

**Comment by sircope** [comment]
> I thought the plan was to disable away missions so coders could fix the problems with them. Now we are just going to remove them, huh? Fun.

remove, don't improve

**Comment by francinum** [comment]
Please tell me how code has any involvement in the fact that the maps removed here are terrible.

That's a map design issue, not a code one.

**Comment by OceanFish1** [comment]
> > I thought the plan was to disable away missions so coders could fix the problems with them. Now we are just going to remove them, huh? Fun.
> 
> remove, don't improve

remove, don't improve

**Review by ike709 — APPROVED** [review]

**Pull request merged**
