### PR TITLE
Allows you to place the tiny electronic assemblies into PDAs

### PR DESCRIPTION
**Pull request by MACIEKBAKI**
## About The Pull Request
what it says on the tin

## Why It's Good For The Game
becouse.

## Changelog
:cl:
tweak: Tiny electronic assemblies fit into PDAs.
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
But why

**Comment by MACIEKBAKI** [comment]
Becouse it makes sense that a tiny assembly - specifically the one that looks like a fucking pen - fits in a PDA like pens do

**Comment by MACIEKBAKI** [comment]
bump

**Comment by MACIEKBAKI** [comment]
@qwertyquerty

**Comment by qwertyquerty** [comment]
Don't bump PRs.

**Comment by MACIEKBAKI** [comment]
bump

**Pull request merged**
