### PR TITLE
Dynamic Midround Non-Ghost Blob

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

Ports https://github.com/tgstation/tgstation/pull/59574
Includes tweaks from https://github.com/tgstation/tgstation/pull/65997 and https://github.com/tgstation/tgstation/pull/68571

Players can now be "infected" with blob pustules and burst into a blob as part of midround dynamic.

## Why It's Good For The Game

This gives non-ghost players the chance to finally play as blob!

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

Ignore the extra objectives, I was originally a traitor and force-blobbed myself.

image

</details>

## Changelog
:cl: itsmeow, Watermelon914, JJRcop, Mothblocks, Kylerace
add: Added midround non-ghost blob dynamic ruleset - living players can now burst into a blob!
add: Added a sound for when you start as a blob.
add: Added a new role preference for blob infection. Be sure to enable it if you want it!
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Imagine going happily about your day then being forced to explode into blobs

**Comment by itsmeow** [comment]
Imagine happily going about your day and then being forced to go disable blob in the game preferences

**Comment by itsmeow** [comment]
I should clarify, when you are infected, you gain a "Pop" action that lets you turn into a core, but remain human until the 6 minutes is up or you hit Pop.

**Comment by PowerfulBacon** [comment]
Ghost blob and normal blob share the same preference, so people aren't going to disable it. I can see many people leaving it enabled anyway even if it is, which can then lead this to be very disruptive to roleplay situations if someone is in one.

**Comment by EvilDragonfiend** [comment]
It's fine for me to roll blob while I am ghost, but no to it when I am playing. So, yeah, Bacon said the point.

**Comment by RDS88-beeman** [comment]
Word of warning, disable IPC's for this roll. They can still pop, but AFAIK they don't increment the timer so they can really just sit as an IPC for however long they want.

**Comment by itsmeow** [comment]
I can just add a new preference.

**Comment by itsmeow** [comment]
> Word of warning, disable IPC's for this roll. They can still pop, but AFAIK they don't increment the timer so they can really just sit as an IPC for however long they want.

The timer is species independent.

**Comment by itsmeow** [comment]
Also, 6 minutes is quite a while to wrap up any roleplay. Given a new preference for this, I'd much prefer having this as I would rather have my round interrupted than have to sit and observe to finally be a blob. Ghost roles are extremely inaccessible to people who don't just sit and observe.

**Comment by Crossedfall** [comment]
> Also, 6 minutes is quite a while to wrap up any roleplay. Given a new preference for this, I'd much prefer having this as I would rather have my round interrupted than have to sit and observe to finally be a blob. Ghost roles are extremely inaccessible to people who don't just sit and observe.

I don't really see this as a problem, if I'm being honest.

**Comment by itsmeow** [comment]
> I don't really see this as a problem, if I'm being honest.

What? Not being able to get ghost roles without observing? I think it sucks, and having to sit and observe for hours just to have the CHANCE to play one antag once is not fun. I've got like 500 hours and the only ghost role I've ever played is space dragon and a nukeop, and that was THIS WEEK.

**Comment by EvilDragonfiend** [comment]
> What? Not being able to get ghost roles without observing? I think it sucks

If you want this, don't make it blob only. Make a system like "Roll ghost roles while playing" pref that can let you 'automatically' roll those roles while you're playing. Once you're chosen, you should be notified that you need to cryo within 5 minutes, and once you're done with it, you become the chosen antag.

**Comment by PowerfulBacon** [comment]
There are some roles that are only obtainable by being a ghost, there are some that are only obtainable by being alive. There's nothing wrong with that, especially since the ones that are only obtainable to one are only designed to be obtainable by one.

**Comment by itsmeow** [comment]
I think in this one specific case, for this one specific antag, having it be an infection that happens to players works just fine and makes the game more interesting for those who want it and have the preference enabled. That's my case.
I don't think that having 6 minutes to go find a place to burst and place your core is disruptive to RP. That's plenty of time to wrap something up, break into maintenance and find a spot.
If you want to RP it, you could even run to medical and have them be confused about this "infection" you have.

Some roles are ghost only, this one doesn't *have* to be.

**Comment by itsmeow** [comment]
Closing this. It's not sensible IC and while yes not being able to get ghostroles when playing is a problem, this is not the answer.

**Pull request closed without merging**
