### PR TITLE
(recoup) Spatial gridmap take 3

### LINKED ISSUE #11319: [Bug]: Can't enable/disable Headset's channels
### BYOND Version

515.1614

### Round Date

2024/08/11

### Round ID

49607

### Test merges

[#9124: 'Enable serverside 515.1633' by Crossedfall at commit 3e63a01a0a](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#10730: '(recoup) Spatial gridmap take 3' by Tsar-Salat at commit 79ade99393](https://www.github.com/beestation/beestation-hornet/pull/10730)

### Describe the bug

When I wanted to enable channels on captain's headset (As an Acting Captain) they just reset to the default enabled channels when I closed the pop-out window.

### What did you expect?

I expected channels to be enabled.

### Reproducible steps

> Take any headset with channels (For example, captain's headset)
> Activate it in hand to open pop-out with channels
> Try to enable/disable any channels
> Close the pop-out and reopen it

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports:
- https://github.com/tgstation/tgstation/pull/61422
- https://github.com/tgstation/tgstation/pull/63660
- https://github.com/tgstation/tgstation/pull/63765
- https://github.com/tgstation/tgstation/pull/63877 (fix roundstart runtime with client_contents)
- https://github.com/tgstation/tgstation/pull/64763
- https://github.com/tgstation/tgstation/pull/65771
- https://github.com/tgstation/tgstation/pull/67056

## About The Pull Request

closes #11319 

This PR optimizes the radio and searching through areas through the implementation of a new subsystem, SSspatial_grid.

This PR is a recoup of Mato0sz's #6582 2021 pr, with my own additional fixes and more tg fixes.

## Why It's Good For The Game

bacon said it was good

kills massive radio overtime. Speed for our server ~~(I need it for storage and smooth movement too)~~

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Screenshot 2024-07-09 182848

2 milliseconds pretty good!

</details>

## Changelog
:cl: rkz, Kylerace, LemonInTheDark, Tastyfish, Mat05usz
code: Adds new subsystem to optimize radio and searching areas
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
Dammit

**Comment by Tsar-Salat** [comment]
oh my jod

**Review by Rukofamicom — APPROVED** [review]
No apparent issues during testmerge, but I would like a secondary code review by Bacon before slapping merge.

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
Extended TM uncovered a problem with camera listening, RKZ is already aware of it but making sure someone doesn't slap merge until it's fixed.

**Comment by Tsar-Salat** [comment]
> Extended TM uncovered a problem with camera listening

issue with eye_obj listening, fixed now.

Tested through spamming events and seeing if I could hear relayed speech "New announcement!" from the newscasters.

**Comment by Tsar-Salat** [comment]
image

There we go

**Review by Rukofamicom — APPROVED** [review]

**Pull request merged**
