### PR TITLE
Updates tracked playtime menu 

### PR DESCRIPTION
**Pull request by r1ks-iwnl**
## About The Pull Request
Ports tgstation/tgstation#54681
Updates the playtime menu to use TGUI and changes its style.
This should be testmerged first since i can't test it very well without records on a local server.
image

## Why It's Good For The Game
TGUI good
HTML bad

## Changelog
:cl: Mothblocks, r1ks-iwnl
add: Updates view tracked playtime menu to TGUI.
/:cl:

### CODE REVIEW

**Comment by r1ks-iwnl** [comment]
ofc i compile just fine and this fails

**Comment by PowerfulBacon** [comment]
There isn't really a reason for that menu to be TGUI, it doesn't have any updating components and doesn't need any

**Comment by r1ks-iwnl** [comment]
Perhaps, still looks much better though.

**Comment by OceanFish1** [comment]
oh damn fast hide it from francicum or he instaclose it because tgui bad!

**Comment by imsynthex** [comment]
makes playtime alot more readable, good.

**Comment by ItsTisme** [comment]
Auto-Close every TGUI PR that isant mine because I cant be fucked to recompile it

**Comment by PowerfulBacon** [comment]
oh looks pretty good actually

**Comment by Archanial** [comment]
> There isn't really a reason for that menu to be TGUI, it doesn't have any updating components and doesn't need any

Eventually every ui should be remade in tgui Just for consistency, imagine still using html uis.

**Review by francinum — APPROVED** [review]
This is fine.

**Comment by francinum** [comment]
> > There isn't really a reason for that menu to be TGUI, it doesn't have any updating components and doesn't need any
> 
> Eventually every ui should be remade in tgui Just for consistency, imagine still using html uis.

Not every UI benefits from TGUI, and not every UI should involve the process cost of doing TGUI stuff.

This UI is non-critical and made far more usable and legible by being converted to TGUI, thus it has purpose.

**Pull request merged**
