### PR TITLE
Security Checkpoint Capsule #2

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request

Adds a checkpoint capsule to be used by Security when they want to search or restrict movement for personnel on the station to a specific area. Every armoury is given three of these and also given one regular Security Barricade capsule.

Thank you Aramix and Dakae for the help. Idea by Liver_dm.

## Why It's Good For The Game

It allows Security Officers to RP having a checkpoint almost where ever they wishes and can force antags to use alternative routes rather than the front door. Currently, as Liver_dm explained, a Security Officer will tell someone to stop and they will just keep running by as if nothing happened. This checkpoint will force the person to wait for the Security Officer to open the gate for them, conduct the search if they wish and then let them through the other gate. Or they can go inside, knock the Seccie over the fence out of the checkpoint and then run off.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image 

</details>

## Changelog 
:cl: @MarkusLarsson421, @Nakalon, @XeonMations 
add: Security Checkpoint capsule
tweak: [Security Barrier] Changed it to include a fancy floor and directional windows instead of full glass windows.
imageadd: Added security themed rail and windoor variant.
/:cl:

### CODE REVIEW

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
## Ignore the changes requested in this comment, in favor of the later one - Everything below this was left as-is for posterity. 

While I like the idea of sec being able to easily set up checkpoints, I do not like the solid glass variant and would like to see it removed. I am open to being talked out of this by others, but here's my reasoning:

* Most maps have halls that are 3-wide, which allows these barricades to completely seal an entire hall in one go. Railing variant can be climbed over with some delay, but glass cannot and must be broken.
* Because it is made of glass, nothing stops security from using the majority of their weaponry unhindered. 

I give hesitant approval of the idea in general because I forsee players utilizing the checkpoints as a combat tool rather than their intended purpose - there is a delay on the checkpoints activation, but nothing says the player has to throw it immediately. "Cook" the capsule for part of its duration, then throw and suddenly you have a fish in a barrel situation.

I'd rather have faith in the players not to abuse them though, so I'm okay with the railing variant because it's much less of a hard barricade than reinforced windows.

**Comment by MarkusLarsson421** [comment]
> I do not like the solid glass variant and would like to see it removed

The barricade currently exists in the game and can only be obtained via Cargo orders. Based on its description it is specifically to be used against nukies. I've only replaced its solid windows with reinforced directional windows and changed the floor of it to look nicer. While I initially wanted to replace the barrier with the checkpoint this decision was questioned on the original PR and I kept it.

> but glass cannot and must be broken.

The barricade has no access requirement and can be walked right through unlike the checkpoint.

> but nothing says the player has to throw it immediately. "Cook" the capsule for part of its duration, then throw and suddenly you have a fish in a barrel situation.

You will have a limited supply of them, initially I am thinking of having three but this could be lowered. Meaning using this offensively will ruin for other Officers planning to use this for its intended purpose. 

If you wish to get more checkpoints or barriers you'll need to buy it from Cargo for 1000 credits or 2000 credits for 3 of them respectively.

**Comment by DarnTheMarn** [comment]
I have to agree with Ruko that this has potential for abuse, the glass version especially is essentially a sec pokeball. Throw it and trap them, sure its only glass but that means they can't shoot or melee back at you immediately while you can shoot them immediately. 

It would be better served as a static thing you have to deploy like the engie traitor turret instead of being able to throw it like bluespace capsules, that would most of the issues with it. I mentioned it on discord but I'll repeat it here, making it decay would be very beneficial since this could easily clog up hallways fast if security decides to use more than one or two of them in a round.

**Comment by MarkusLarsson421** [comment]
> sure its only glass

As previously mentioned.

> The barricade [full glass one] has no access requirement and can be walked right through unlike the checkpoint.

The barricade is designed to be used against Nukies and until this PR seemed like no one knew of it. It is in the game right now and you can get three of them for 2 000 credits.

> making it decay would be very beneficial since this could easily clog up hallways

Depending on how many free ones you give, maybe. Initially I had in mind to give them three checkpoints and one barricade in the armoury. Then you have a risk (not a guarantee) of four 3x3 clogging up any of the hallways. 

These points feels very insignificant and fictitious to me. In worst case this free number can be dropped to one each or such. I don't quite see the issue with Security using them, the point is for them to use them. If Security were to spam it by getting a ton of money (1 000 credits for three checkpoints or 2 000 credits for three barriers assuming there is stock for it) through any of the Head of Staff (who are held to a higher standard). Then Security will piss off and disturb the crew and create conflict that way. The current barrier practically does not exist and people tend to think of getting more laser guns rather than utility.

**Comment by DarnTheMarn** [comment]
>These points feels very insignificant and fictitious to me.

What is the downside of making it so its got to be deployed by hand? It prevents any abuse and still gets the job done. I think spacing is a real concern because on a lot of maps there's only really one central hallway that connects everything. Plop one of those down and walk away and you've just inconvenienced the entire crew by making the hallway a 1x1.

**Comment by MarkusLarsson421** [comment]
> What is the downside of making it so its got to be deployed by hand? 

> I think spacing is a real concern because on a lot of maps there's only really one central hallway that connects everything. Plop one of those down and walk away and you've just inconvenienced the entire crew by making the hallway a 1x1. 

No, you've inconvenienced the first and next crew member to pass by.

**Comment by DarnTheMarn** [comment]
You just equated it to flashbangs so you essentially admit that it will be a problem. Not a fan of those either, for the record.

**Comment by MarkusLarsson421** [comment]
Currently, it is a bit awkward to fight here as the railing and windoor theme are the same but you can't shoot through the windoor with regular weaponry. It does make you into a fish in a barrel, assuming you get caught in it.
image 

Catching someone in this is difficult. Xeon and I tested this out by throwing capsules at each other, we probably activated 10 checkpoints and only I was caught in it twice, once from catching the thrown capsule in mid-air and not letting go of it or deactivating it by running into a wall. It has strategies and counter plays if this would be used offensively. Which I still doubt. You're better off using your disabler to stun crit a criminal.
image 
image 

One worry it does have is that bots will get stuck on them. However, if there is no Officer the next person will destroy the railing and allow bots to go through.
image

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
## Updated changes requested, after various discussions in and out of PR

* Remove the ability to throw the capsules and make it deploy on-person only with a do-after delay.
* Still add access checks to the railing based version

**Comment by PestoVerde322** [comment]
Also, since i am at, i'd like to see potentially new icons for this, since it somewhat looks off currently.

**Comment by MarkusLarsson421** [comment]
> Also, since i am at, i'd like to see potentially new icons for this, since it somewhat looks off currently.

The capsule itself?

**Comment by Rukofamicom** [comment]
My paranoia and past traumas strike again. 

As I've gone back over this and everything that was said I've realized that I was requesting a loss of cool factor for the sake of balance that wasn't even necessary. Sometimes I need to take a step back and stop paranoid worry about how something can be abused and realize it's not worth the cost outside of those abuse cases. 

Now that all the work I requested has been met I've more or less reversed the requested changes - throwable capsules are and always have been fine - the potential for abuse was minor and would have already been widespread if it was going to become widespread. do_after capsules is definitely far more balanced, but also far less cool than click and throw capsules and I think the cool factor being lost outweighs the potential for abuse. 

I'm deeply sorry for wasting your time here, as I said in Discord. This was in a fine state for approval before my requested changes and I'm going to do what I can to ensure I'm making reasonable requests regarding narrow and unlikely scenarios.

**Review by Rukofamicom — APPROVED** [review]

**Comment by Rukofamicom** [comment]
Actually, this doesn't affect balance at all right now.

**Pull request merged**
