### PR TITLE
[PORT?] Reworks lighting overlay

### PR DESCRIPTION
**Pull request by park66665**
## About The Pull Request

Ports: tgstation/tgstation#44164 (Kinda unrelated, but... why not?)
Ports: tgstation/tgstation#52389
Ports: tgstation/tgstation#55561
And then I overhauled the lighting overlay code *again*; this PR is three reworks on top of each other.

Light overlays now use a non-unique (i.e. shared) mutable appearance instead of creating a new mutable appearance on-the-fly every update.

tgstation/tgstation#44164 is a small fix for tgstation/tgstation#44122, hence, also for #2456.

## Why It's Good For The Game

I trust using non-unique mutable appearances much more than creating a mutable appearance on-the-fly every time.

## Changelog
:cl: nemvar, Dennok, Azarak, park66665
fix: recolored lights now preserve their color on nightshift
fix: emergency lighting and vacuum lighting now have lighting overlay
code: light fixture now uses a non-unique mutable appearance for its lighting overlay
/:cl:

### CODE REVIEW

**Comment by Sinestia** [comment]
> ## About The Pull Request
> 
> Ports: [tgstation/tgstation#44164](https://github.com/tgstation/tgstation/pull/44164) (Kinda unrelated, but... why not?)
> Ports: [tgstation/tgstation#52389](https://github.com/tgstation/tgstation/pull/52389)
> Ports: [tgstation/tgstation#55561](https://github.com/tgstation/tgstation/pull/55561)
> 
> Light fixtures now use a pre-baked non-unique (i.e. shared) vis overlay instead of creating a new mutable appearance on-the-fly every update. I re-baked nightshift lighting mode overlay icon since Bee uses different `light_power` for nightshift.
> 
> [tgstation/tgstation#44164](https://github.com/tgstation/tgstation/pull/44164) is a small fix for [tgstation/tgstation#44122](https://github.com/tgstation/tgstation/pull/44122), hence, also for #2456.
> ## Why It's Good For The Game
> 
> I trust using non-unique vis_overlay much more than creating mutable appearance on-the-fly every time. ~and ike wanted this~
> ## Changelog
> 
> cl nemvar, Dennok, Azarak, park66665
> fix: recolored lights now preserve their color on nightshift
> code: light fixtures now use non-unique vis overlays for its lighting overlay
> /cl

sick

nice work

**Comment by park66665** [comment]
Holy moly everything is broken DNM

**Comment by park66665** [comment]
Now things are no longer broken ~but at what cost?~

**Comment by Chessus** [comment]
@park66665 hey does this fix the issue with smoke and lighting? You know how lights stay black after a smoke grenade?

**Comment by park66665** [comment]
> @park66665 hey does this fix the issue with smoke and lighting? You know how lights stay black after a smoke grenade?

That bug is not related with PR at all.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
