### PR TITLE
Blocks netspeak

### PR DESCRIPTION
**Pull request by ike709**
## About The Pull Request

Blocks any netspeak in IC chat from sending. 

If this is too severe, I'd be willing to change it to a confirmation popup like the "Meant for OOC?" check. It'd definitely say something like "Are you sure you want to broadcast your stupidity?"

Suggestions welcome.

## Why It's Good For The Game

>muh immershun

Tired of seeing Heads of Staff walking around saying "lol" and "wtf".

## Changelog
:cl: ike709
add: Blocked netspeak in IC chat.
/:cl:

### CODE REVIEW

**Comment by CthulhuOnIce** [comment]
> can't say "lollygagging" or "lollipop" 

😠

**Comment by ike709** [comment]
I knew there were words that started with "lol" but I couldn't for the life of me remember what.

**Comment by ike709** [comment]
Made the regex great again.

**Comment by qwertyquerty** [comment]
But we're lrp

**Comment by ike709** [comment]
Netspeak is one of the easiest and most common ways of completely ruining the atmosphere, and it costs a player literally nothing to use big boy words instead. None of the blocked words offer any advantage over talking normally.

**Comment by LordZanos** [comment]
>low RP
>half assed filter with condescension for maybe 1/100th of all the netspeak terms

bruh

**Comment by ike709** [comment]
>Suggestions welcome.

I put the most common offenses that I saw on the server on a daily basis.

**Comment by k-k-karma** [comment]
WAAAAAAAAAAAAAH MY IMMERSION

**Comment by qwertyquerty** [comment]
Sorry I dont think this is meant for bee

**Pull request closed without merging**
