### PR TITLE
removes random abductor organs from pubby station

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Removes the abductor organs from pubby's abandoned surgery room.

## Why It's Good For The Game

The crew shouldn't have access to abductor organs just like this.

## Changelog
:cl:
del: Removed the random abductor organs in pubby maints.
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
might wanna change the random maint room marked "pubby surgery" then

you know the organ types arent just all abductor organs though, right

**Comment by ghost** [comment]
> 
> 
> might wanna change the random maint room marked "pubby surgery" then
> 
> you know the organ types arent just all abductor organs though, right

every time i went into that room it was always abductor organs.

**Comment by zeskorion** [comment]
> > might wanna change the random maint room marked "pubby surgery" then
> > you know the organ types arent just all abductor organs though, right
> 
> every time i went into that room it was always abductor organs.

nah, i mean, it doesnt have all abductor organs, it is actually a somewhat small pool of mostly negative ones

**Comment by qwertyquerty** [comment]
Conflicts

**Comment by ike709** [comment]
Conflicts

**Pull request closed without merging**
