### PR TITLE
making goof zombies recipe actually make sense

### PR DESCRIPTION
**Pull request by Agateophobia**
## About The Pull Request

changes food poisoning to liquid gibs in goof zombie toxin 

## Why It's Good For The Game

sense is cool very

## Changelog
:cl:
code: Food poisoning changed to liquid gibs in goof zombie toxin
/:cl:

### CODE REVIEW

**Comment by Agateophobia** [comment]
me stoopid why travis no build

**Comment by St0rmC4st3r** [comment]
Hm. It looks like Travis runtimed on LINDA atmos. Try reverting Beestation.dme changes since they shouldn't have existed in the first place and it is most likely not your fault.
If that doesn't work and continues failing - push a couple of empty commits untill it works.

**Comment by Agateophobia** [comment]
me am smart travis build travis smart, stormcaster smart very he

**Comment by Agateophobia** [comment]
me am gonna make new one cause those 3k changes are not supposed to be here

**Pull request closed without merging**
