### PR TITLE
Nerfs the Firelock Deathtraps

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

3 Simple Nerfs To Firelock Deathtrap
* Makes firelocks open 60% faster by reducing the sleep time when operating (opening/closing) the doors. 
* Halved the time it takes to open firelocks with crowbar. 
* You can open firelocks by using an empty hand. This is thanks to the manual lever that is applied on each and every firelock.

(EDIT) Reduced the time firelocks need to close. This often overrode their automatic close timers, meaning they wouldn't close in time/work properly and caused gas to escape.

## Why It's Good For The Game

So many times have I died to atmos fuckery because firelocks just don't open fast enough, and you have to go through 10 of them to get into a safe area. Sometimes they don't open at all. Whoops! Sometimes they just don't have power so if you don't have a crowbar, you fucked. Even if you do have a crowbar, it takes literal ages to open 10 series of parallel firelocks to get to a safe area. Needless to say, firelocks have killed hundreds and are one of the biggest threats in SS13 at the moment. 

I don't think not having a crowbar should be an absolute death sentence in SS13. In real life, fireproof doors alyways (and I do mean, ALWAYS) have a way to be operated/opened by a human. Don't know why it should not be the same in SS13. They don't have to be a workplace hazard,

## Changelog
:cl:
tweak: firelocks open 60% faster.
tweak: halved the time it takes to open a firelock by crowbar.
tweak: reduced the time it takes for a firelock to close automatically
add: You can now pry open the firelocks with your bare hand.
/:cl:

### CODE REVIEW

**Comment by Moccha-Bee** [comment]
Based pr, speed merge it please code janitors.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
open_speed should start at 5 and be set to 8 on the firedoor rather than just having 5 added to it no matter what

**Comment by eeSPee** [comment]
> open_speed should start at 5 and be set to 8 on the firedoor rather than just having 5 added to it no matter what

Ok. Also should be 5 default, 2 on firedoor, since it's calculated as sleep(5+open_speed). Setting it to 8 would just make it slower.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by hotimep** [comment]
it's been like almost a year and broken firelocks still take up a full tile when broken smh!

**Comment by eeSPee** [comment]
Thanks

**Pull request merged**
