### PR TITLE
Reminds shitters to not be shitters.

### PR DESCRIPTION
**Pull request by ghost**
🆑 ike709 BeloneX
add: Some roles now have reminders of what not to do.
/🆑

Ports: https://github.com/OracleStation/OracleStation/pull/544

Examples of a special notice (EDIT: Different words in the latest version):
image

### CODE REVIEW

**Comment by Naevii** [comment]
Brig physician is allowed to do security job if security doesn't have many sec officers tho.
and i would say brig physician is mainly more responsible for prisoners health.

**Comment by ghost** [comment]
> Brig physician is allowed to do security job if security doesn't have many sec officers tho.
> and i would say brig physician is mainly more responsible for prisoners health.

Common sense applies, this just serves as a general reminder.

**Comment by PowerfulBacon** [comment]
I hate the wording on these, basically just saying 'you are a shitter, stop being a shitter' to everyone and gives a really negative impression. Also, it's highly contextual and most of these are frankly wrong in a lot of situations.

**Comment by ghost** [comment]
>  'you are a shitter, stop being a shitter' 

It's true though, have you seen how people play these roles?

**Comment by PowerfulBacon** [comment]
> 
> 
> > 'you are a shitter, stop being a shitter'
> 
> It's true though, have you seen how people play these roles?

Yea, but its even more shitty to just go out and blanket everyone in the codebase as a shitter, when there are people who play them properly.

**Comment by PowerfulBacon** [comment]
As I see it, this is completely pointless for all jobs except the brig physician, is worded horribly and extremely passive-aggressive and just gives an incredibly negative impression, which isn't what we are going for since when you treat people like a shitter, they are going to act like one.

**Comment by ghost** [comment]
> when there are people who play them properly.

Good for them, most don't.

**Comment by Goblinu** [comment]
This is how you turn bee sage into fulpstation

**Pull request closed without merging**
