### PR TITLE
Cult Resprite by Naevi

### PR DESCRIPTION
**Pull request by DrDuckedGoose**
Co-Authored-By: Naevii <60577525+Naevii@users.noreply.github.com>

## About The Pull Request

Resprites a majority of cult items, featuring appeal and weapons.

## Why It's Good For The Game

Updates crust cult sprites to a modern standard. 
Emphasizes cult flamboyance. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
Green hair poking out

image

image

image

image

image

image

image

image

image

image

image

image

Yes, the shield is animated.

image

image

image

</details>

## Changelog
:cl:Naevii
tweak: Change most sprites in cult.dmi
tweak: Change bloodspear sprites in polearms_(lefthand & righthand).dmi
tweak: Change cultblade sprites in swords_(lefthand & righthand).dmi
tweak: Change cultrobe sprites in suit.dmi
tweak: Change cultrobe sprites in clothing_(lefthand & righthand).dmi
tweak: Change cultrobe sprites in suits.dmi
tweak: Change mirror-shield in shields.dmi
tweak: Change mirror shield in shields_(lefthand & righthand).dmi
/:cl:

### CODE REVIEW

**Comment by Naevii** [comment]
unknown-10
Old vs new

**Comment by Naevii** [comment]
unknown-10

**Comment by Rukofamicom** [comment]
Don't forget to 🆑 Naevi

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
icons/obj/clothing/suits.dmi
icons/obj/clothing/hats.dmi

These files are for the icon state when they are on the ground, rather than when they are worn. They need to be single direction

**Comment by Naevii** [comment]
My bad forgot to supply those.  But changing to keeping only one direction should work good enough

**Comment by DrDuckedGoose** [comment]
Indeed, I didn't want to ask them to put in extra work, so I just used what i was given.

**Comment by PowerfulBacon** [comment]
image
Center these

**Comment by PowerfulBacon** [comment]
image
Can you double check this sprite? Make sure its an issue with the icondiff bot

**Comment by DrDuckedGoose** [comment]
> image Can you double check this sprite? Make sure its an issue with the icondiff bot

issue with bot 👍

**Review by PowerfulBacon — DISMISSED** [review]

**Comment by Naevii** [comment]
I will supply sprite for the shield (because I forgot it existed) soon tm

**Review by PestoVerde322 — DISMISSED** [review]
Everything seems good to go, aside the soon-to-be updated shield sprite.

**Review by PestoVerde322 — APPROVED** [review]
Shield has been added, re-approved.

**Review by Archanial — APPROVED** [review]
Ping me when you make wiki changes

**Comment by DrDuckedGoose** [comment]
> Ping me when you make wiki changes

Do you want them down now, or post merge?

**Comment by Archanial** [comment]
Now

**Pull request merged**
