### PR TITLE
The great resprite: Atomized edition (soup matter volume)

### PR DESCRIPTION
**Pull request by SomeAngryMiner**
## About The Pull Request

Another part of the big wave of resprites, taking a break from tools and stuff everyone uses, i took a look at something that somehow was left unchecked for long: supermatter,
It served its job, yeah, but i think you could convey the "crystal" part better, so i did a twitchy, 48x32 crystal, more readable than the other, besides respriting the shard and the causality field (for those who are too much of a coward to look the crystal delaminate, its a field that appears on the last 60 seconds of the supermatter's life)
Think its good, but feedback is always appreciated.

As always, no soul.

## Why It's Good For The Game

it super matters!

image

## Changelog
:cl:
add: New supermatter sprites!
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
Sparkly rock

**Comment by Moccha-Bee** [comment]
Tasty bright yellow rock yummy

**Review by PowerfulBacon — DISMISSED** [review]

**Comment by ghost** [comment]
mmmm let me eat it

**Comment by Archanial** [comment]
Can you show an example how it looks in game?

**Comment by Sinmero** [comment]
Can you make the animation slower and smoother? The way it blinks is hard on the eyes

**Comment by SomeAngryMiner** [comment]
slightly crunchy image, forgot to add the glow before the screenshot

image

**Comment by TeomanTheGreat** [comment]
Nice but a bit too tall

Edit: It also looks somewhat out of place.

**Comment by Archanial** [comment]
Too tall

**Comment by axpov** [comment]
Travis sure does bug out a bunch

**Comment by ghost** [comment]
> Nice but a bit too tall
> 
> Edit: It also looks somewhat out of place.

It looks out of place right now because it's 3/4 unlike the majority of the game which is 1/4, but azlan is soon converting everything else to 3/4 too which should make it fit more.

**Comment by MNarath1** [comment]
thislookscursed
You might want to look into that if you try to go behind the crystal the player sprite will still be infront.

**Comment by SomeAngryMiner** [comment]
oh shoot, fixing that.

**Comment by SomeAngryMiner** [comment]
people shouldnt walk over the spicy poprock anymore, and it should properly hide people behind it.
making travis rerun the checks also unfucked the map docker, somehow.

**Comment by KubeRoot** [comment]
I think it looks great as a sprite, but... I think it really doesn't look like a mysterious dangerous new form of matter, more like a gold sculpture.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
> 
> 
> I think it looks great as a sprite, but... I think it really doesn't look like a mysterious dangerous new form of matter, more like a gold sculpture.

In game it is animated and pulses

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
