### PR TITLE
Signal jammer movement

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Adds in some new signals which can be used to implement entities which need to be jammed actively rather than passively. This is used for cameras to make them switch off when a jammer comes close by, rather than when they randomly decide to update and a jammer is near.

Cameras will also visably disable when a jammer is nearby.

## Why It's Good For The Game

Improves the speed at which jammers will jam cameras and the consistency of that. Allows other people to implement things that receive jams but don't constantly want to check is_jammed.

## Testing Photographs and Procedure

https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/18fb7443-6a8c-4961-a8c8-9892b68556d8

## Changelog
:cl:
code: Implements a new system for determining when a jammer moves into range of an object.
balance: Cameras will now visibly turn off when a singal jammer is nearby.
/:cl:

### CODE REVIEW

**Review by Rukofamicom — APPROVED** [review]
Looks and sounds great

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
Ah, just saw your changelog

Please include the addition of signal jammer working on cameras within the changelog.

**Comment by PowerfulBacon** [comment]
Signal jammer already works with cameras

**Review by Rukofamicom — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
PR needs merging as has dependencies

**Pull request merged**
