### PR TITLE
Revert "Removes the assistants' maint access on Sage"

### PR DESCRIPTION
**Pull request by Archanial**
Reverts BeeStation/BeeStation-Hornet#3849

Assistants are not new player characters. If you think that you are not playing the game. This is cringe and unnecessary + was speedmerged for literally no reason.

:cl:
config: Reverts assistant changes on sage.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
image

The previous pull request was merged by Crossedfall, there is nobody that is gonna override his decision.

**Comment by Archanial** [comment]
> The previous pull request was merged by Crossedfall, there is nobody that is gonna override his decision.

there is me

**Comment by ghost** [comment]
> > The previous pull request was merged by Crossedfall, there is nobody that is gonna override his decision.
> 
> there is me

You didn't understand what I typed.

**Comment by BitBite112** [comment]
Wait, maint access for assistants got changed on Sage? What the actual fuck?

**Comment by eeSPee** [comment]
Y'all assistant mains better stop complaining, if you still want to keep your roundstart limbs.

**Comment by pickleinjar** [comment]
> Y'all assistant mains better stop complaining, if you still want to keep your roundstart limbs.

nah fam

**Comment by Crossedfall** [comment]
We don't do instant reverts.

**Comment by BitBite112** [comment]
I can get behind that, but when will it be appropriate to propose a revert?

**Comment by Crossedfall** [comment]
> 
> 
> I can get behind that, but when will it be appropriate to propose a revert?

Reverts are _usually_ reserved for cases of an emergency (e.g. the change is so broken it's causing server stability issues or catastrophic errors), it's far preferable to improve the feature than to rip it back out. But for stuff like this, I usually recommend waiting at least a week to see how things settle before considering a revert. That just gives everyone time to get a little used to the change and for us to see how it actually holds up.

**Comment by zeskorion** [comment]
wait you guys seriously removed maints from assistants in my absence? wheeeew!

**Comment by OceanFish1** [comment]
> wait you guys seriously removed maints from assistants in my absence? wheeeew!

No fun allowed

**Pull request closed without merging**
