### PR TITLE
Ports Tarot Cards, for Thematics:tm:

### PR DESCRIPTION
**Pull request by WhereAmO**
## About The Pull Request
This is a port of Tarot Cards from TG, with some new sprites, names, descriptions, aaand a single runtime fix. That's about it! Cards can be shuffled, pulled, can come out as reversed, flipped, etc. Sprites are also coloured depending upon the individual suit, card number. I didn't touch the Major ones though. Tarot cards are also added to the Fun Vendor and the Loadout options, for 10 and 600 respectively.

Huh, I also accidentally ported radial card menus. Those are nice too!

Ports:
https://github.com/tgstation/tgstation/pull/50729
https://github.com/tgstation/tgstation/pull/51318
https://github.com/tgstation/tgstation/pull/74160

Also helped a LOT by Dakae and RKz

## Why It's Good For The Game
Thematics are cool, Halloween is coming near, and can add some fun RP/gimmicks. Also radial menus for cards makes it easier to navigate, was ugly before.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>
Cool Demo:tm:
Accidental Copy-pasting of Radial Menu Code, works?

Screenshot (102)

Screenshot (103)

toy

Demo where I show off as much as I can think of

https://github.com/BeeStation/BeeStation-Hornet/assets/81683771/5d255490-32bc-4c0c-959d-e6f128cfc14d

</details>

## Changelog
:cl: WhereAmI, RaveRadbury, Inept, softcerv
add: Adds Tarot Cards, for any thematic fortune tellings you might require! Find them in the General loadout tab or Fun Vendor.
add: Radial Menu for Cards, easier to navigate while playing!
/:cl:

### CODE REVIEW

**Comment by WhereAmO** [comment]
I may be an idiot.

**Comment by WhereAmO** [comment]
Cards are, also, apparently Tiny now, but I forget if we have a different storage system from TG and if that makes more or less sense, input would be appreciated! Also fix(ing) Syndicate Throwing Cards now.

**Comment by Fronsis** [comment]
The Psyphoza agenda is being pushed... good

**Comment by WhereAmO** [comment]
Totally didn't make this specifically due to Psyphoza inspiring me no whatever do you mean.

**Comment by WhereAmO** [comment]
Oops I deleted Unum again. Will fix tomorrow! Also need to find out how to fix the deprecated thingy, apparently?

**Comment by WhereAmO** [comment]
Should be all fixed now, still need an opinion on if TINY or SMALL would be better.

**Comment by Penwin0** [comment]
Credit the people whose PRs you are porting in the changelog, just put their names (and yours) after the first :cl:

**Comment by WhereAmO** [comment]
Uploaded a new video as evidence that Unum is still working, embedding, etc. Also apparently cards spawn in perfect order? Who knew! (This isn't a change I did it's just how they are)

**Review by itsmeow — APPROVED** [review]

**Comment by WhereAmO** [comment]
Potentially got some new sprites incoming for the tarot deck itself, will update the DMI with that if/when!

**Review by Rukofamicom — APPROVED** [review]

**Comment by Rukofamicom** [comment]
You can update them with another PR because I didn't read that comment until the button was pushed!

**Pull request merged**
