### PR TITLE
Allows StockParts to be Created by Medical and Cargo

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Allows StockParts to be Created by Medical and Cargo

## Why It's Good For The Game
It's never made sense to me that medical has access to certain circuits but is unable to build them themselves. Forcing medical staff to go back and forth from science to retrieve stock parts.

This will now allow medical and Cargo to customize their workspace.

## Changelog
:cl:
add: Allows StockParts to be Created by Medical and Cargo
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
The idea is inter-department cooperation.

**Comment by ghost** [comment]
> The idea is inter-department cooperation.

I get that but I think that it would give medical more to do, I think the part system is already a pain in the ass.
What does a sleeper bed need? Well unless you put the circuit in and examine you better have it memorized.

Should Sci do multiple upgrades whenever a new tier of stock parts come out?
I think the fact it's rare to see anything built in medical along with chem dispensers upgraded is evidence that the current inter-department cooperation is too heavy.

Compared to botany and chemistry working together where it's a one time thing and always the same need I think this puts too much of a strain on medical.

**Comment by Mick1299** [comment]
I can understand giving medical basic parts, since they can print some basic machine boards. But why give parts to cargo? Or, alternatively, why not give basic parts to all departments.

Giving all tiers of parts to medical and cargo just removes one of the main sources of interaction for science.

**Comment by Isy232** [comment]
They should be able to print basic parts and powercells, nothing more I think.

**Comment by AyyRobotics** [comment]
> The idea is inter-department cooperation.

True, though botany running to chemistry every 5 minutes for mutagen is also inter-department cooperation, and now botanists get their own chem dispenser, and people asking cargo for things from the autolathe could also be argued for that, but alas I believe that public autolathe PR was merged.

**Comment by Axanthic** [comment]
Closing - Was PermaBanned

**Pull request closed without merging**
