### PR TITLE
Removes gangs

### LINKED ISSUE #11591: Completely remove gang code.
Gangs are not in use and their code should be completely remove.

### PR DESCRIPTION
**Pull request by Szyszkrzyneczka**
Keeps their outfits though

## About The Pull Request

Removes gangs from the game
All that remains are the sprites and the outfits
hippie gang is dead

## Why It's Good For The Game

closes #11591 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
del: Removes gang code
/:cl:

### CODE REVIEW

**Comment by Szyszkrzyneczka** [comment]
merge-my

**Comment by Dejaku51** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/10828 revive

**Comment by DrDuckedGoose** [comment]
I believe we should aim to improve our content instead of removing it, under certain circumstances. In this particular case, I'd really like to see gangs improved and brought into the roleplay context of Bee, instead of outright being removed.

**Comment by Rukofamicom** [comment]
Gangs is just a better concept than revolution outright. I agree with @DrDuckedGoose

I don't know who's going to work on it specifically though, so a removal in the meantime isn't exactly bad since the mode is and has been disabled for a long time anyway.

**Comment by PowerfulBacon** [comment]
> I believe we should aim to improve our content instead of removing it, under certain circumstances. In this particular case, I'd really like to see gangs improved and brought into the roleplay context of Bee, instead of outright being removed.

You are welcome to do so

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
