### PR TITLE
[Bounty] Add an icon to brainwash victoms adminhud

### LINKED ISSUE #1423: [Bounty] Add an icon to brainwash victoms adminhud
Feature requests are not handled in the repository. The best place to discuss these ideas would be on the /tg/station 13 forums here: https://tgstation13.org/phpBB/viewforum.php?f=9&sid=5153c1c704a4fb1006bf7a265e45e03f

### PR DESCRIPTION
**Pull request by PowerfulBacon**
resolves https://github.com/BeeStation/BeeStation-Hornet/issues/1423

## About The Pull Request
Brainwashing shows up on the antag hud now.
 - Antags who are brainwashed will keep their normal antag hud icon.
 - Non antags who are brainwashed will gain the antag hud icon
 - If someone somehow gets antag while they are brainwashed, removing the brainwash won't remove their antag hud icon and the normal antag hud will overwrite the brainwashing hud icon :)

Normal person brainwashed
image

Brainwashed cultist
image

## Why It's Good For The Game

Admins can quickly see people who are brainwashed.

## Changelog
:cl:
admin: Antag hud now shows brainwashed victims
sprite: Added brainwashing hud icon (pink traitor icon)
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Hang on, doesn't work for brainwashing on all antags as some don't get assaigned special role like cultists, so if they lose the brainwashing status they lose their hud icons too

**Comment by PowerfulBacon** [comment]
Tested by giving antags, giving brainwash, removing brainwash and it seems to be working good. Ready for review

**Comment by bloons3** [comment]
Do other brainwash'ees see it, or is it just antag hud/end of round ghost hud?

**Comment by PowerfulBacon** [comment]
Should be only admins with combo hud, since it uses the same type of hidden hud as traitors

Edit: Tested, nobody sees it, not even yourself

Using adminhud in ghost
image

Brainwashed person (No adminhud)
image

**Comment by Crossedfall** [comment]
resolves #1423

**Pull request merged**
