### PR TITLE
Allows mentors to use the msay hotkey

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Title. Line 26 is the only one that matters, rest is just a reformat of the sinful one line if statements.

Yes this is tested. 

## Why It's Good For The Game

Admins can't flex their hotkeys on mentors anymore.

## Changelog
:cl:
add: Mentors now may use the F4 hotkey to speak in msay
/:cl:

### CODE REVIEW

**Review by Archanial — APPROVED** [review]
admin/mentor code is so cursed

**Comment by ivanmixo** [comment]
yes this is dreadful

**Comment by mcmeiler** [comment]
Bad PR, doesn't let me bully mentors anymore.

**Comment by KubeRoot** [comment]
Wait wait wait

This should already be fixed by https://github.com/BeeStation/BeeStation-Hornet/pull/5672

**Comment by ivanmixo** [comment]
> Wait wait wait
> 
> This should already be fixed by #5672

Oh yeah it does, hmmmm.... I'll leave a review with a nitpick though.

**Pull request closed without merging**
