### PR TITLE
Removes monkey from rotation(again)

### PR DESCRIPTION
**Pull request by super12pl**
## About The Pull Request
My last PR removing monkeys(#2600 ) got rejected in favor of jungle fever buff (#2542 ) however buff didn't make gamemode any better but instead monkey rounds became even slower because of larger number of gorrilas.

## Why It's Good For The Game
Bad mode in both gameplay and code(ipc monkey leaders eh). See above

## Changelog
:cl:
config: Removes Jungle Fever from rotation.
/:cl:

### CODE REVIEW

**Comment by Penwin0** [comment]
yes? yes

**Comment by AnjelicaChaykovsky** [comment]
yes monkeys are really weak and no one so far is willing to fix it.
however it could be midround event, fits much better

**Comment by BrotherHangyul** [comment]
Speedmerge

**Comment by Sinestia** [comment]
Sad


 but needed

**Review by PowerfulBacon — APPROVED** [review]

**Comment by ike709** [comment]
@Crossedfall config

**Review by Crossedfall — APPROVED** [review]
Config applied

**Pull request merged**
