### PR TITLE
Adds monkey sentience helmet to Pun Pun's hat blacklist

### PR DESCRIPTION
**Pull request by Penwin0**
## Why It's Good For The Game
This is an item that probably shouldn't be transferable

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Screenshot_1713
Screenshot_1715
Second Pun Pun was Pun Pun II confirming it had properly read the files, testing this was a pain in the ass.

</details>

## Changelog
:cl:
tweak: Pun Pun can't keep sentience helmet between rounds anymore
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
Lmao reminds of the alien incident.... good change, a shame because it could be a funny gimmick but persistance through rounds is icky, i still think we should've moved it as a gimmick job but that's out of the scope

Good catch, griffman punpun is once again denied

**Review by EvilDragonfiend — APPROVED** [review]
Hmm, okay, that doesn't look right.
I am fine with pun pun having this persistently, but their helmet will not be possible to take off permanently which is not good.

**Comment by Penwin0** [comment]
Testing Evidence added

**Comment by PowerfulBacon** [comment]
I think this just makes sense

**Pull request merged**
