### PR TITLE
Adds confirmation to Adminhelp verb

### PR DESCRIPTION
**Pull request by KubeRoot**
## About The Pull Request

image

The adminhelp verb now displays the following confirmation prompt:

image

Clicking either the "Adminhelp" or "Mentorhelp" button triggers the input prompt for the appropriate action.

## Why It's Good For The Game

This is what gets triggered when you press F1, or press the Help button from the top bar. Considering justified ahelps shouldn't be that common, adding another click to them shouldn't be a big issue, and allows us to throw useful information at new players seeking help.

## Changelog
:cl:
add: The adminhelp verb now displays a confirmation prompt suggesting the use of mentorhelp
/:cl:

### CODE REVIEW

**Review by ike709 — DISMISSED** [review]

**Review by Sinestia — DISMISSED** [review]
Looks good skimming this, ty for implementing it. Should help with new players who often do ahelp things first.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Pre adminhelp needs to be skipped if they already have a ticket open and are replying to it.

**Comment by ike709** [comment]
This is a pretty gross way to implement this.

**Comment by KubeRoot** [comment]
> This is a pretty gross way to implement this.

Could I get some feedback for why it's bad? I mainly did it this way to keep compatibility with any existing/ported code by not modifying the original `adminhelp` verb other than turning it into a `proc`, and only swapping out references to `adminhelp` where the action is initiated by the user to go through a prompt.

**Pull request closed without merging**
