### PR TITLE
Removes unarmed hardstun

### PR DESCRIPTION
**Pull request by FriendlyContractor**
## About The Pull Request
Removes ability to paralyse a knocked-down person by shoving them. Additionally shoving will not cause a person to drop their  held items under any circumstance. Also removes some old commented-out code

## Why It's Good For The Game
Moves game away from bad meta revolving around stealing weapons better than yours with a single click unarmed and paralysing person in the process allowing you to kill them with their own weapon while they are unable to do anything. This also prevents ambush where person is paralysed and killed before having any chance to react. Droping a soap or emptying fire extinguisher which is impossible to dodge no longer can be used to completly overpower a person. It does not remove shoving completly and it can still be used to knock down a person and for example get away or press your advantage over them but it cannot completly disable a person and win a fight alone.

**Example situations showing why existing shove is bad for the game**

- Traitor decides to pull out energy sword and attack his target in two tile wide maintenance tunnel. "Victim" moves one tile diagonaly and shoves the traitor paralysing him before he can react and then beheads him with his own blade.
- Security officer finds a suspicion person in maintenance tunnel and starts questioning them. Suddenly suspect shoves the officer paralysing him and then pulls out energy sword killing the officer who is unable to fight back in any way.
- Head of security is chasing a minor criminal across the main hallway with their stunbaton because their disabler is out of charge. When they finally catch up to the person they drop a bar of soap, paralyse downed hos with a shove and run away with their baton.
- Group of validhunters is fighting experienced traitor with double energy sword who is in 1 tile wide maintenance tunnel so he cannot be shoved into a wall and his block can not be bypassed. All of this does not save him because validhunters can shove other validhunters into him to incapitate him anyway

## Changelog
:cl:
balance: Shoving can no longer paralyse or disarm a person
/:cl:

### CODE REVIEW

**Comment by FriendlyContractor** [comment]
Uh oh ruko made another PR while i was writing mine ;-;

**Comment by Mat05usz** [comment]
> Traitor decides to pull out energy sword and attack his target in two tile wide maintenance tunnel. "Victim" moves one tile diagonaly and shoves the traitor paralysing him before he can react and then beheads him with his own blade.

Skill issue, also you don't have to kill the tot, wall shove give you enough time to simply escape, calling security, which is a perfectly normal thing to do and you shouldn't be taking almost the only thing regular crewmember has for self-defense in these kinds of situations

> Security officer finds a suspicion person in maintenance tunnel and starts questioning them. Suddenly suspect shoves the officer paralysing him and then pulls out energy sword killing the officer who is unable to fight back in any way.

Skill issue

> Head of security is chasing a minor criminal across the main hallway with their stunbaton because their disabler is out of charge. When they finally catch up to the person they drop a bar of soap, paralyse downed hos with a shove and run away with their baton.

Guess what

> Group of validhunters is fighting experienced traitor with double energy sword who is in 1 tile wide maintenance tunnel so he cannot be shoved into a wall and his block can not be bypassed. All of this does not save him because validhunters can shove other validhunters into him to incapitate him anyway

Mm guess again, also what even is this situation, I don't think I've seen the dreaded 'validhunter group' on the server in years.


I'll be honest, both this and Ruko's PR seem like a classic 'ided', altough knowing Ruko it's not like that, but here? Idk

**Comment by FriendlyContractor** [comment]
Thank you for taking your time to write very in-depth and helpfull feedback. Knowing that being unable to respond to something with superhuman reflex in game with most simple and intuitive controls is a skill issue will greatly help me to enhance my pull request. Please continue your hard work reviewing other pull requests and providing equally valuable and constructive feedback

**Comment by Mat05usz** [comment]
> Thank you for taking your time to write very in-depth and helpfull feedback. Knowing that being unable to respond to something with superhuman reflex in game with most simple and intuitive controls is a skill issue will greatly help me to enhance my pull request. Please continue your hard work reviewing other pull requests and providing equally valuable and constructive feedback

Gave you feedback to 1/2 of the points you're making, another half is a skill issue and there is nothing to give feedback to.

> Droping a soap or emptying fire extinguisher which is impossible to dodge

You're not even trying to cover the fact why you want to remove it. I know it hurts to be robusted, but it sometimes is like that.

> win a fight alone

One wall shove winning a fight against you? There's plenty of other things that actually can win fight for you alone, and can't be mitigated simply by having spatial awareness and not standing against a wall.

Also, your own PR from about half a year ago, there is your feedback: https://github.com/BeeStation/BeeStation-Hornet/pull/5543

image
Giving your own PR thumbs up, really?

**Comment by Syrox25** [comment]
Ad Hominem moment. They made a fair point about shoves leading to hardstun and you called it a skill issue and made fun of them... even pulling up something from the past.
The single half point I will give you is that "There's plenty of other things that actually can win fight for you alone" 
Fair... but this requires no prep and can still win fights yet you want this shut down. So we should fix none of them?

Wanna try again or stick with your snarky take?

**Comment by Mat05usz** [comment]
> They made a fair point about shoves leading to hardstun and you called it a skill issue

Because that's what all these points boil down to, skill issue because someone wasn't spatially aware/skilled enough 

>  even pulling up something from the past.

I literally pulled the same PR he's doing right now so they/you may check the comments below, where you'd find that multiple people, including maintainers, are saying what I'm saying now. If you actually bothered to check it out. 

>  but this requires no prep and can still win fights yet you want this shut down.

Again this requires the one being shoved down to have skill issues. It's basically the only self-defense tool for an unprepared crewmember. 

Given how regular, non-antag crew is already underpowered and can't gather shit because of powergaming, do you really want to take this last resort defense too?

> Ad Hominem moment.
> Wanna try again or stick with your snarky take?

Also my second response was to his passive-aggressive one, so no, I don't wanna try again and I uphold that, in my opinion, main reason behind this PR is skill issue.

**Comment by Syrox25** [comment]
So skill is the only thing we should care about?
Its not self defence when it can turn the tables fully.
Why WOULD this even hard stun? What fun is there in clicking someone twice to make them stop moving then clicking them 5 times to kill. It should be a desperate struggle and a tug of war. not: "He hard stun, I win"

Constantly tripping each other as one tries to crawl away, the other bearing down on them with a weapon that will likely outclass anything the victim has and not really being able to take the weapon from them.
This will actually require those without weapons of their own to get the fuck out and promotes planning, placement and timing for the Antag over a pure skill contest... especially when most Antags are meant to be trained soldiers (or atleast stronger) when the average crew aren't, yet all hardstuns promote are the random crew member overpowering said Antag because the PLAYER is better.

So I ask you a question, should player skill should take priority in this case?

**Comment by Mat05usz** [comment]
> So skill is the only thing we should care about?
> So I ask you a question, should player skill should take priority in this case?

When it actually comes to a fight? Yes, skill and preparation. If you are shit at combat and think that esword will solve all your problems then well, sorry, but it's still a game after all.

> Its not self defence when it can turn the tables fully.

Again, it can only turn tables fully if you don't know how to fight and came unprepared, and when both of these happen, why should you win? Because you're big bad antag and should be able to robust any non sec crew at will?

> Why WOULD this even hard stun?

Lie on the floor, someone kicks you really hard in the stomach/head/anywhere else. You're not coming up as if nothing happened. And yes, I realize that this is a game, not real world, but also the analogy is made simpler and easier for the one being kicked since you actually **DO** get up after a very short while, unlike IRL.

> What fun is there in clicking someone twice to make them stop moving then clicking them 5 times to kill. It should be a desperate struggle and a tug of war. not: "He hard stun, I win"

Fun is not in the act, fun is that you actually managed to pull it off against a vastly more powerful opponent. Also again, all it takes to nullify the 'shove advantage' is to not stand against a wall like a dumbass, mindlessly slashing your victim. You should think what you're doing.

And yes, if both opponents skill + preparation are comparable, it is a 'desperate struggle and a tug of war', as it should be when things are balanced. 

> especially when most Antags are meant to be trained soldiers (or atleast stronger) when the average crew aren't, 

This is a funny part cause when you think about most antags, they are regular crew but somehow 'converted' to be soldiers now. The only actual soldiers are nukies, rest is either sleeper agents (which means they forgot they even were trained or had any connections to the syndicate) or are straight up converted from the regular crew. Unless you think that upon conversion, crewmember suddenly gains combat skill.

> yet all hardstuns promote are the random crew member overpowering said Antag because the PLAYER is better.

You realize that antag can also hardstun? It's not limited to regular crew, what's more, if you actually want to kill someone with a melee weapon, part of your plan should be trying to corner them in such a way to let you shove them, not fucking chase them into hallways and get bonked by sec. This is a double-edged sword.

**Comment by Syrox25** [comment]
> When it actually comes to a fight? Yes, skill and preparation. If you are shit at combat and think that esword will solve all your problems then well, sorry, but it's still a game after all.
Again, it can only turn tables fully if you don't know how to fight and came unprepared, and when both of these happen, why should you win? Because you're big bad antag and should be able to robust any non sec crew at will?

Losing combat should very much be a thing. What shouldn't be is someone being fully disarmed and killed because shoved once during a scuffle. Shoving them without the hardstun would still give anyone unarmed ALOT of time to run while the attacker picks themself up as they slowly crawl.

Lets do a hypothetical...
The unarmed assistant ganked in maints (unrealistic currently but still)
Situation A (Hard stun): Attacker is somehow slipped and the assistant shoves them, Attacker drops his weapon in the span of half a second.
          A1. Attacker is killed by his own weapon.
          A2. Assistant runs off with weapon. Severely reducing the attackers options aswell as being reported.

A1 is just promoting opportunistic valid hunting/baiting and needs policed 24/7
A2 is better.... but only just. Antag is now limited and on the run. To them their round may as well have ended there if it was anything powerful. All because of in theory a single click.

Situation  B: (No stun): Again, attacker is slipped and shoved, they are knocked a tile away (if able) and the weapon is still held and actively dangerous despite being on the ground.
          B1. Assistant can attempt to kick/punch or pull out a weapon of their own. They still have a minor advantage due to 
                mobility but this might only make things equal, not tip the scale. Attacker can still take swings if the victim is 
                bold/foolish enough to approach. Things could go either way but should still on average lean towards Antag IMO if 
                victim chooses to re-engage
          B2. Assistant, seeing no way to fight. chooses to flee empty handed and manages to get out the alert. Antag still has their weapons.
          
B1. While still opportunistic and valid hunty... does not instantly reward them with gear before the fight is won and is still a huge risk, even after knock down. Not a near instant win / scale tip

B2. Random crew are not rewarded for fighting on the spot. Antag, despite messing up, still has an opportunity to fight back against sec should they track them.

Moving on..

> nullify the 'shove advantage' is to not stand against a wall like a dumbass

Whats this got to do with wall shoves? Unless it was changed and AFAIK... The only requirement for hardstun is that the one shoved already be slipped/knocked down... there are MANY ways to get someone into this state. Soap/Water/Banana/Foam etc

I did say "most antags" Somewhat of a hyperbolic statement sure... Traitors are likely to be the most populous antag and the most affected by this. I would 100% say they are trained, even if its by brainwashing or prior to implantation, not the point. Antags aren't JUST regular crew outside of revolution. There is either training or higher influences.

>You realize that antag can also hardstun?
Yes. What I also realized is that Antags have something else called gear.
Focusing in on traitors again. They still have a major advantage, with tools capable of stunning/incapping/locking down their target. Avoidance of such should be priority. not using it against them because you won a minor scuffle once.

Everyone being capable of hardstun disarm at all times shifts the power way too much and promotes the worst in people. (IMO)


As for another point. This would also in turn, buff security as SlipShoveSwipes are now no longer a thing, they might actually be able to stand up to an unarmed rowdy mob for atleast a few more second and requires actual weapons when going toe to toe with an armed guard.

I could go on but I think I'm done.. Feeling burned out just explaining this... hope I argued Contractors point enough.

**Comment by Mat05usz** [comment]
> Losing combat should very much be a thing. What shouldn't be is someone being fully disarmed and killed because shoved once during a scuffle. Shoving them without the hardstun would still give anyone unarmed ALOT of time to run while the attacker picks themself up as they slowly crawl.

That only works if someone is robust enough to shove you into hardstun before you land any attack. Slash a person once in the legs/twice in the body and you can very easily get to them if you are just knocked down without the stun.


> Whats this got to do with wall shoves? Unless it was changed and AFAIK... The only requirement for hardstun is that the one shoved already be slipped/knocked down... there are MANY ways to get someone into this state. Soap/Water/Banana/Foam etc

Because it's all about the same thing, you didn't see the soap/water/foam/bananan or stood next to a wall. I'm sorry if I introduced confusion, I just treat them the same. You lie down, you get shoved again and voilla, hardstun.

> Everyone being capable of hardstun disarm at all times shifts the power way too much and promotes the worst in people.

No, this is just making it so regular crew isn't completely helpless, as you want it to be.

> As for another point. This would also in turn, buff security as SlipShoveSwipes are now no longer a thing, they might actually be able to stand up to an unarmed rowdy mob for atleast a few more second and requires actual weapons when going toe to toe with an armed guard.

Oh boi, security if anything, needs more nerfs not fucking buffs. 
Wear a riot armour if you want to handle a riot

> Situation A (Hard stun): Attacker is somehow slipped and the assistant shoves them, Attacker drops his weapon in the span of half a second.
A1. Attacker is killed by his own weapon.
A2. Assistant runs off with weapon. Severely reducing the attackers options aswell as being reported.

There is an option 3 that me, and I think a lot of other people, practice too, being hardstun/wallshove -> run away

> A1 is just promoting opportunistic valid hunting/baiting and needs policed 24/7
A2 is better.... but only just. Antag is now limited and on the run. To them their round may as well have ended there if it was anything powerful. All because of in theory a single click.


A1: How is this promoting anything but self-defense? You fucked up, someone's gonna use your weapon against you. Unless you think that every assistant in maint is validhunting.

A2: You lost, but you are still alive so that's not the end. You can try and find another way to completeing your shit instead of relying on a weapon of your choice fully.

> Situation B: (No stun): Again, attacker is slipped and shoved, they are knocked a tile away (if able) and the weapon is still held and actively dangerous despite being on the ground.
B1. Assistant can attempt to kick/punch or pull out a weapon of their own. They still have a minor advantage due to
mobility but this might only make things equal, not tip the scale. Attacker can still take swings if the victim is
bold/foolish enough to approach. Things could go either way but should still on average lean towards Antag IMO if
victim chooses to re-engage
B2. Assistant, seeing no way to fight. chooses to flee empty handed and manages to get out the alert. Antag still has their weapons.

B3: Again, assistant runs away and calls sec when he feels safe.

But answering your points:

B1: There is no follow up, they are as dangerous as they were before, only slighlty slower. But if you were hit before, they can easily get back up and finish you off. That's where the stun shove comes in.

Let's make it into another situation, which is far more likely. Antag rushes into atmos/medbay/robo, manages to hit you in the right leg and a chest with an esword, you as a player with 500/1000/2000h see an opportunity and shove them against the wall, you make sure to kick them on the ground and try to run away. When usually it would be enough to get to atmos/medbay/robo doors, open them, and close behind, suddenly the murderer comes back/ pulls out a ranged gun and kills you. Amazing and very satisfacting ending. Not at all punishing regular crew who are more skilled than the non thinking antag.
B2. 

Edit:
In addition to everything above, that's where the preparation comes in. You are free to make any drugs that help you in combat (also making you unstunnable), while a regular crewmember doesn't.

**Comment by Syrox25** [comment]
Yeah. I'm done. Yes,  I did leave out the "just run" option because in both cases I see little difference in outcome.... hence my point... Hell Increase slip times if you are so worried that they just spring back up 0.1 seconds later to win.
you claim that shove stun is the "only" defence that the crew have left and removing it will make everyone defenceless but don't seem to have a problem with people acting in bad faith because they are ABLE to pull it off.

To me it feels like all you cared about while arguing your case is winning the encounter. Person who shove stunned wins. And that's exactly my problem with the system. I don't believe its as hard to pull off as you claim.
Getting bad faith argument vibes but I'm probably just biased.... I've said my peace, ill leave this for others to make that judgement*

God... if this is the path bee is going....
Good luck Contractor and goodnight.

**Comment by DerpiestBruh** [comment]
ided

**Comment by PerishedFraud** [comment]
The big issue, I think, is that a lot of our crew will rather fight the antag than run away/call sec.

Nerfing crew won't fix this. It's purely a playstyle issue. We all know we're secretly LRP. This change will just result in more crew death and that's cringe af.

**Comment by Lambda-Epsilon** [comment]
This is Skill Issue: The PR

**Comment by Rukofamicom** [comment]
> It's purely a playstyle issue

Playstyles are enabled by code. If it becomes unfeasible to fight back when unarmed, it will happen a lot less. And if it's unfeasible it will also matter a lot less when it does happen. Regardless of what anyone says, an unarmed player should absolutely be losing a fight against an armed one. Don't bring a knife to a gun fight as they say, and definitely don't show up empty handed. 

Also @FriendlyContractor I'll still be making one more PR with all of the feedback and discussions in mind - the initial ones are primarily to garner attention and get the conversation going so a more reasonable solution could be found. Sorry if I genuinely scared you or anyone else - I did not actually expect or intend for the total gutting to get merged (Though I also wouldn't complain if it had tbh). 

If the actual version I try to submit doesn't meet your expectations, this one will still be a huge improvement over how it currently works. I really appreciate I managed to motivate someone else to make their own PR as a result of this 😆

**Comment by hotimep** [comment]
i thought that it was common sense that fighting next to a wall was a deathtrap

**Comment by Archanial** [comment]
You could try removing it hardstun from first shove and making second consecutive shove hardstun.

**Comment by FriendlyContractor** [comment]
> i thought that it was common sense that fighting next to a wall was a deathtrap

Yes its very much a deathtrap at the moment and makes for degenerate situation where person using a weapon is at disadvantage against unarmed opponent. This also leads to a very bad situation where rather than engaging in a combat using weapon and trying to score enough hits to put the person down, you first try to paralyse your victim often by suprise and only pull out weapon once they are unable to fight back or run away. In short unarmed hardstuns are not fun for the traitors nor for their victims

**Comment by Rukofamicom** [comment]
> i thought that it was common sense that fighting next to a wall was a deathtrap

Sure it is @hotimep. The argument is that it's nonsensical for it to be a deathtrap given how cramped maps are and that this isn't supposed to be a skill-based combat server. 

Also as promised, here is my actual take on this issue: https://github.com/BeeStation/BeeStation-Hornet/pull/6893

Still removes stuns, but doesn't entirely remove the disarm.

**Comment by PowerfulBacon** [comment]
Closed in favour of https://github.com/BeeStation/BeeStation-Hornet/pull/6893

**Pull request closed without merging**
