### PR TITLE
TGUI Panel Stat Hotpatch #1

### LINKED ISSUE #3361: [TGUISTAT] Scrolling requires focus on the contents of the tab.
## Reproduction:
Change to a tab you have to scroll. Be unable to scroll the contents of the tab until you explicitly give focus to the tab content pane.

### LINKED ISSUE #3362: [TGUISTAT] Design
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Have eyes. View the stat panel.

Here's what TG's looks like.

### LINKED ISSUE #3363: [TGUISTAT] Incompatible with WINE/Linux
Stat panel is completely missing with this test merge. Chat box itself still visible/

### LINKED ISSUE #3365: [TGUISTAT] MC panel issues
1. SSair seems to be missing from the list? I haven't checked for any other missing subsystems.
2. The rate the MC tab updates is quite slow. Can it be increased?

### LINKED ISSUE #3373: [TGUISTAT] Commands tab for Sandbox missing
## Reproduction:
Start a sandbox round, Commands tab is missing therefore can't access Sandbox Panel

### LINKED ISSUE #3379: [TGUISTAT] Instability/Performance
TGUISTAT causes server stability issues, resulting in frequent soft locks and 'lag-spikes.'

Profiling the server reveals that `cmp_verb_des` has a very high callrate and overtime.

image

### LINKED ISSUE #3391: New TGUI doesn't properly show pipe on floor orientation
## Round ID:

https://i.imgur.com/l4fLuxG.png
image

New TGUI doesn't properly show pipe on floor orientation

Those pipes were to the right of me in the SM chamber

### LINKED ISSUE #3392: new status panel doesn't show round ID, regression
## Reproduction:
image

### PR DESCRIPTION
**Pull request by PowerfulBacon**
resolves https://github.com/BeeStation/BeeStation-Hornet/issues/3365
resolves https://github.com/BeeStation/BeeStation-Hornet/issues/3363
resolves https://github.com/BeeStation/BeeStation-Hornet/issues/3362<-- this one is very opinionated though, but I do see large issues with light mode. (Especially since the TG one linked looked even worse)
resolves https://github.com/BeeStation/BeeStation-Hornet/issues/3361

Also need to update branch from master now that it is merged

## About The Pull Request

Hotpatch to fix some of the more glaring issues with the TGUI stat panel.

This PR aims to address some of the larger and simpler to fix issues with the TGUI stat panel.
 - [x] Light Mode design adjustments
 - - [x] Higher contrast on the colours
 - - [x] Remove custom colours of buttons
 - - [x] Improve the look of the tabs at the top
 - - [x] Use style to do pretty much all of this.
 - [x] IE8 Support (IE8 does not support flex)
 - [x] Mouse entering the stat panel should focus the stat.
 - [X] Increases the update rate of the stat panel

This PR will not address the more time-consuming issue of high ping making switching tabs delayed, I will handle that in a future PR.

## Changelog
:cl:
fix: Fixes TGUI Stat Panel not working on Linux
fix: Fixes TGUI Stat Panel light mode buttons being near invisible
fix: Fixes TGUI Stat Panel not being scroll focused when hovered over
fix: Fixes TGUI Stat Panel having a very slow update rate on certain tabs
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
going to be honest here, still not happy with the design 100% but its actually usable in light mode

**Comment by PowerfulBacon** [comment]
When I get more detailed things of exactly which parts of the thing should be changed, ill change it to the best of my ability

**Comment by Crossedfall** [comment]
TM removed due to stability issues.

**Comment by PowerfulBacon** [comment]
Stability issues should be resolved. Working on implementing caching of verbs to speed up changing tabs for players with high ping. Not sure how long this is going to take, but shouldn't be too difficult

**Comment by PowerfulBacon** [comment]
instability from sorting is fixed, GSI still has a bit of overtime

**Comment by Crossedfall** [comment]
Currently test merged onto Sage. Stability issues seem to be resolved. Only lingering issue I've detected thus far would be the following warnings from Dream Seeker:

```
Connecting to byond://sage.beestation13.com:7878...connected
winset: Parameter browseroutput.on-close not found.
winset: Element stat not found.
winset: Element stat not found.
winset: Element stat not found.
winset: Element stat not found.
winset: Element stat not found.
winset: Element stat not found.
```

**Pull request merged**
