### PR TITLE
Tgui strip window from /tg/

### PR DESCRIPTION
**Pull request by BrumalLake**
## About The Pull Request
Ports
- https://github.com/tgstation/tgstation/pull/57889
- https://github.com/tgstation/tgstation/pull/58007
- https://github.com/tgstation/tgstation/pull/58012

Strip panel now uses tgui
Panel doesn't reopen when you finish an action now
Toggle internals button wont be having an icon until svg fonts get fixed
Adjusting jumpsuit function changed to our adjusting suit sensors function, as uniforms still cover your chest/arms while visually exposing your chest/having your sleeves rolled up
Small note, animated icons don't look very good

- [x] suit sensors button

## Why It's Good For The Game
More responsive, well organized hud

## Changelog
:cl: lordScrubling, Mothblocks
add: tgui for stripping window
code: strippable element
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
I'd rather we just modernize what we have now, it's what most of the playerbase is comfortable with.

**Comment by BrumalLake** [comment]
> 
> 
> I'd rather we just modernize what we have now, it's what most of the playerbase is comfortable with.

"don't make things better because people use the current versions"

**Comment by Cenrus** [comment]
Our strip menu is the same except for the Set sensors button, has it been implemented here

**Comment by BrumalLake** [comment]
> 
> 
> Our strip menu is the same except for the Set sensors button, has it been implemented here

damn, i have to figure out how to do that now

**Comment by Cenrus** [comment]
Shouldnt be too hard, look at how they made the adjust jumpsuit toggle on their UI.

**Comment by BrumalLake** [comment]
> 
> 
> Shouldnt be too hard, look at how they made the adjust jumpsuit toggle on their UI.

well, i'm gonna have to figure out how to place it somewhere else

**Comment by ivanmixo** [comment]
> > I'd rather we just modernize what we have now, it's what most of the playerbase is comfortable with.
> 
> "don't make things better because people use the current versions"

I don't think this is better, is the thing.

**Comment by BrumalLake** [comment]
probably gonna scrap adjusting uniforms for suit sensors, since it doesn't actually do anything except be cosmetic

**Comment by AnCopper** [comment]
> probably gonna scrap adjusting uniforms for suit sensors, since it doesn't actually do anything except be cosmetic

It's for surgery.

**Comment by BrumalLake** [comment]
> 
> 
> > probably gonna scrap adjusting uniforms for suit sensors, since it doesn't actually do anything except be cosmetic
> 
> It's for surgery.

adjusting it doesn't change what parts it covers

**Comment by KubeRoot** [comment]
> > > probably gonna scrap adjusting uniforms for suit sensors, since it doesn't actually do anything except be cosmetic
> > 
> > 
> > It's for surgery.
> 
> adjusting it doesn't change what parts it covers

I want to mention, it does do that on tg and it'd probably be a good thing to port. Because of this, I think it shouldn't be removed from the UI.
I think defining a second `alternateAction` that appears in another corner, or maybe turning it into a list of alternate actions that are stacked in a corner, would work fine.

**Comment by BrumalLake** [comment]
> 
> 
> > > > probably gonna scrap adjusting uniforms for suit sensors, since it doesn't actually do anything except be cosmetic
> > > 
> > > 
> > > It's for surgery.
> > 
> > 
> > adjusting it doesn't change what parts it covers
> 
> I want to mention, it does do that on tg and it'd probably be a good thing to port. Because of this, I think it shouldn't be removed from the UI.
> I think defining a second `alternateAction` that appears in another corner, or maybe turning it into a list of alternate actions that are stacked in a corner, would work fine.

I don't think adjusting is a feature worth doing, different jumpsuits have different adjusting sprites, spriters haven't been consistent in alternate sprites, some have their sleeves just rolled up
the only thing keeping it will do for now is fool people
how about readd it when you code it

i don't know tgui myself really

**Comment by francinum** [comment]
...This is incredibly fucking ugly.

**Comment by ike709** [comment]
Yeah this is pretty ugly, visually.

**Comment by BrumalLake** [comment]
i see it now, seems like a good time for me to try to learn tgui

**Pull request closed without merging**
