### PR TITLE
adds unused borg item(tested)

### PR DESCRIPTION
**Pull request by Toxici11i**
## About The Pull Request
Adds the "power connector" item - allowing borgs to directly charge from cell chargers/rechargers/etc and charge guns using their cells!

## Why It's Good For The Game
already coded and having to find a cyborg recharger or get one built is plain inconvenient

## Changelog
:cl:
add/tweak: adds unused item that allows cyborg to charge themselves and other chargable items.
/:cl:

### CODE REVIEW

**Comment by Toxici11i** [comment]
tfw accidentally put flash nerfs in here. will just m i r r o r them

**Comment by qwertyquerty** [comment]
No no no I mean't remove all the things you accidentally pushed here

**Comment by qwertyquerty** [comment]
Imagine not knowing how to revert commits

**Comment by Toxici11i** [comment]
i hit revert but it dont work

**Comment by qwertyquerty** [comment]
It's called using git cli

**Pull request closed without merging**
