### PR TITLE
[PORT] [READY] Syndicate Contracts

### PR DESCRIPTION
**Pull request by Cenrus**
https://github.com/tgstation/tgstation/pull/44420/

## About The Pull Request

Ports syndicate contracts from /TG/station.

## Why It's Good For The Game

More fun for traitors

## Changelog
:cl: Akrilla
add: Syndicate Contracts. Use the new contract uplink to select a contract, and bring the assigned target dead or alive to the designated drop off. Call for the extraction pod and send them off for your TC payment, with much higher rewards for keeping them alive. A high risk, high reward choice for a traitor who wants a real challenge.
add: New 20 TC contract kit - supplies you with your contractor loadout and uplink.
add: Targets successfully extracted will be held for ransom by the Syndicate after their use to them is fulfilled. Central command covers the cost, but they'll be taking a cut out of station funds to offset their loss..
add: Contract kit's specialist space suit now has its custom sprite.
soundadd: Assigning to tablet plays greeting soundclip
add: Contract kit comes with a contractor baton - a unique, lightly electrified weapon to help complete your contracts
/:cl:

### CODE REVIEW

**Comment by Kerbin-Fiber** [comment]
Very good

**Comment by ike709** [comment]
I know for sure this has follow-up PRs.

**Comment by Cenrus** [comment]
I'll need #739 for the followup.

**Comment by Cenrus** [comment]
I'll do the contractor hub in a separate PR.

**Comment by Cenrus** [comment]
https://github.com/tgstation/tgstation/pull/44705
https://github.com/tgstation/tgstation/pull/44767
https://github.com/tgstation/tgstation/pull/44869

Will get these after the baton PR is merged.

**Comment by Cenrus** [comment]
Ready to go.

**Comment by ike709** [comment]
Fix conflicts and I'll merge.

**Comment by Cenrus** [comment]
conflicts are no more.

**Comment by Cenrus** [comment]
Seems to be working within the test merge

**Pull request merged**
