### PR TITLE
Blood cult Nerf (should work this time)

### PR DESCRIPTION
**Pull request by Sparrowbird611**
## About The Pull Request

Rebalances mirror shield so that the throw deals knockdown instead of stun, (duration is still three seconds) and removes electromagnetic pulse from the blood cultist spell pool.

## Why It's Good For The Game

The Mirror shield change is so that victims of the mirror shield throw actually have a chance of retaliating, instead of just hoping the shield misses (you can't catch the shield or it stuns you).

EMP removal is so that laser weapons and silicons can actual contribute in the fight against blood cultists.

Considering the fact that blood cultists can mass production night vision medihud sunglasses, magic armor that completely blocks damage, incredibly powerful melee weapons, and possess instant stun abilities, this isn't a huge nerf, but it does bring some of the more versatile items down a bit.

## Changelog
:cl:
del: Removed Electromagnetic Pulse from the blood cult's spell list
balance: rebalanced mirror shield, the throw now inflicts knockdown instead of paralyze
/:cl:

### CODE REVIEW

**Comment by eLeCtrOssSnake** [comment]
Uh, I'd say no.

**Comment by eLeCtrOssSnake** [comment]
Considering the fact that cult gets rekt in 9 of 10 rounds it sounds stupid.

**Comment by Sparrowbird611** [comment]
I've seen pretty consistent success in every cult game I've been in, so I don't know what you're talking about, but alright. I'm mainly bringing their gear into line with other antagonists with similar equipment (the only other antag with an item similar to mirror shield is clown ops, and they have significantly lower killing power than cultists). Considering cultists can convert everything, including silicons, they shouldn't have a free, undodgable AoE stun (which is basically what the EMP spell does).

**Comment by Cenrus** [comment]
Cult EMP is important, especially when we still have security cyborgs in the game. Is there any way you can make it weaker against IPCs instead of removing it entirely?

**Comment by honkhonkclown** [comment]
I would say nerf it against IPCs especially considering the fact that it also claps CULT ALLIED IPCS so if you get converted to cult as IPC you'll probably die to an EMP collateral damage but yea it should still work the same on borgs since otherwise secborgs exist

**Comment by honkhonkclown** [comment]
EMP is needed as an option against mechs since otherwise something like a H.O.N.K or durand can pretty quickly rape a cult base with no counterplay other than hoping enough people can wack it with swords and not get stunlocked by the honk and its allies or the durand activating shield and just mowing people down

**Comment by Sparrowbird611** [comment]
I want to point out flashbulbs exist, and they're still great items, even as a cultist. The EMP spell really is not so integral that removing it would demolish cult (it's really not that hard to acquire flashbulbs, and actually making an EMP grenade is as simple as grabbing some metal, uranium, and heading to the holodeck).

As for making it weaker against IPCs, I'm not entirely sure if that's possible, but that's honestly not the main reason I suggested this (though it is a great side benefit). I suggested it because I feel mirror shield should be the main way to negate lasers, and the default cultist should have to dodge them, not have an insta disable spell.

**Comment by Sparrowbird611** [comment]
The H.O.N.K. mech has been in play like, two times in all of my 100s of matches (excluding clown ops). I don't really even consider that a factor.

The durand answer is again, make your own EMP devices and crush it. They're easy to make.

**Comment by hackerjsimon** [comment]
EMP is quite important tbh its basically their only counter for sec and cyborg also cult loses like majority of the time tbh no nerf is needed

**Comment by Sparrowbird611** [comment]
> EMP is only counter to security
> mirror shield, instant stun ability, literally two forms of ranged disables, powerful armor that blocks everything, teleporting constructs, magic missile turrets, magic sunglasses...... ETC.

You get the point. I've watched cult win more than it's lost every time I've played, but I also realize that's not great evidence on either of our part. Cultists already have plenty of magic powers that can disable people, NOT TO MENTION they have access to all the default counters to these things (metal and uranium makes EMP, flash bulb is easy to acquire, ETC).

**Comment by eLeCtrOssSnake** [comment]
Yeah, many people see EMP very important. I agree with most of the people. No nerf is needed.

**Comment by Cenrus** [comment]
removing an important spell because of a single, optional race isn't a good idea. If IPCs are suffering from EMPs, then you should make them have a higher resistance to them. Almost all antagonists have access to EMPs and that's not going to change.

I doubt this change will affect cult winrates at all.

**Comment by Sparrowbird611** [comment]
Guys. This has nothing to do with IPCs, I wasn't even thinking of them when I made it. I'm honestly not sure why everyone thinks this is why I'm making this PR.

**Comment by Sparrowbird611** [comment]
I made this one because I felt the cult having both a way to guarantee a stun and kill against a cyborg, and being able to disable laser guns was ridiculous. Considering the fact that they walk around with nukie level weaponry, I honestly don't think this is a bad change. And again, EMPs are braindead easy to make, along with flash bulbs.

**Comment by Sparrowbird611** [comment]
I never really thought this would change their winrate. Cultists are a powerful antagonist with conversion abilities reaching further than any other conversion antag, a nerf like this really doesn't hurt them too badly. If this really is a big deal, (and it doesn't already exist) I can go and figure out how to make the stun hand blast cyborgs.

**Comment by eLeCtrOssSnake** [comment]
What is this reopen?

**Comment by Sparrowbird611** [comment]
Well uhhhh, I accidentally hit the close button.

**Comment by Sparrowbird611** [comment]
So I had to reopen it.

**Comment by hackerjsimon** [comment]
Actually their conversion sucks ass as you need 2 people to convert 1 person vs all the other v=conversions where its a 1 on 1, also the emp should still fuck cyborgs as it was made with the intention

**Comment by ike709** [comment]
The vote ever so slightly passed, but considering how split it is and how contentious this issue is, I'm going to close it.

**Comment by Sparrowbird611** [comment]
Thats cool. I started to have some doubts near the end any way.

**Pull request closed without merging**
