### PR TITLE
Ports Hippie Stands

### PR DESCRIPTION
**Pull request by Toxici11i**
## About The Pull Request
Adds hippie holoparasite changes

## Why It's Good For The Game
They are much better, customisable, and rework a bad system. Also, removes wizard timestop because this will eventually replace it

## Changelog
:cl:
add: Ports hippie holoparasites
del: Removes wizard timestop but keeps it a spell
soundadd: Adds hippie sounds
server: Now a new hippie modularisation folder, kept here temporarily and ""could"" be removed - I dont recommend it as all of their stands have unique sounds that would be a headache to change.
/:cl:

### CODE REVIEW

**Comment by Toxici11i** [comment]
The travis CL "errors" are just warnings - they dont actually affect gameplay in testing.
http://prntscr.com/pbe0kf

**Comment by Toxici11i** [comment]
infact, just to be safe ill recompile it from scratch after redownloading

**Comment by Toxici11i** [comment]
Yeah, just warnings and no errors here

**Comment by Arrfur** [comment]
fun fact: people dont use holo paras

fun fact: holoparas are fun as h*cc

fun fact: hippie holo paras are more fun

conclusion? mhm

**Comment by qwertyquerty** [comment]
Fix the warnings and errors

**Comment by ghost** [comment]
make sure it functions with holocarps

**Comment by qwertyquerty** [comment]
1188 changed files are you kidding me

**Comment by Toxici11i** [comment]
Thats for all the effects and noises

**Comment by Toxici11i** [comment]
also tracking down the errors, it compiled fine with 0 warnings on my side this time. not sure what broke it

**Comment by Toxici11i** [comment]
Removing deprecated organ code because that doesnt apply here.

**Comment by Toxici11i** [comment]
It seems to be travis autism, check where its erroring "no definition of proc harm" or whatever - its literally defined under the harm proc
send help travis autistic

**Comment by qwertyquerty** [comment]
Travis is working perfectly fine.

**Pull request closed without merging**
