### PR TITLE
Flandstation - Service Pack 5 (AKA Flandstation 2.0)

### PR DESCRIPTION
**Pull request by PestoVerde322**
## About The Pull Request

Here it's the Fifth Service pack for Flandstation, this version will radically change how the map is constructed, with a brand new Science and Medical, it also renew some high-travel areas, like the service area, departures, and the removal of the permaroid (now located within security) and the holyroid (now located where there was the gravity engine. Maintenance is also radically changed, with the engineering maintenance being exclusive only to engineers, and with more expanded maintenance all around for your less lawful and totally not cult related acts.
Also, the shutters are gone in favour of a holobarrier that let people trough.

This new version also includes a shuttle construction yard, fixes plenty of  bugs in the previous version, and adds plenty of QoL changes that where very much needed.

thanks to @spockye for the additional fixes regarding broken piping and whatnot!

[reminder to myself to actually go more in depth later on, I'm kinda short on time right now]

## Why It's Good For The Game

The long awaited sequel to Sp4, This is gonna radically change how Flandstation works.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

flandstationsp5

(soon-ish for more content)

</details>

## Changelog
:cl:
add: Changed radically flandstation, the whole map is radically different now
add: New area defining drydocks.
imageadd: added holoshutters icons
/:cl:

### CODE REVIEW

**Comment by Programs-The-Station** [comment]
Does this fix some of the issues in #6442?

**Comment by PestoVerde322** [comment]
> Does this fix some of the issues in #6442?

I have addressed the one related to the QM security, but not the one for tech storage, will fix.

**Comment by 21Unigoats** [comment]
I did some sleuthing around and found a few minor discrepancies:
<details>
<summary>mapping issues</summary>
Bottom left rad collector isn't wired. Perhaps this is the reason as to why Fland never seem to have any power.

Screenshot (261)

Disposal connects up with the main network instead of straight up ejecting it. Also engineer spawn in turbine?
Screenshot (262)

Left airlock has no controller or vent. Right one has no controller
Screenshot (263)

This hallway below science has firelocks yet no alarms
Screenshot (264)

Medbay lockdown shutters don't properly cover maints. Also misplaced pipe junction
Screenshot (265)

This shutter will cut off the secondary front desk from the rest of med should it go down. I suggest moving it to the lower door or getting rid of it.
Screenshot (266)

Morgue doesn't have any lockdown shutters. There's also no camera in there but idk if it's intentional
Screenshot (267)

Weird zoning
Screenshot (268)

Science shuttle dock conveyor isn't lined up properly
Screenshot (269)

Airlock below escape is missing a controller
Screenshot (270)
</details>

Overall, this looks like a really good overhaul and I can't wait for this to get merged. I can tell you put blood, sweat, and tears into the design from both a gameplay and aesthetic standpoint.

**Comment by PestoVerde322** [comment]
> I did some sleuthing around and found a few minor discrepancies:
> [Lodsa of issues]

First off thanks for pointing it out, to answer some of those issues:

-There's an engineer spawn as the turbine is shared access between Atmosians and Engineers, since the whole engineering area is engineering staff only
-There's no camera in morgue to design, since any alien/blob/slime/any critter that spawn there would get either noticed IMMEDIATELY by the AI or by a bored secoff and, on many maps there's no camera in there
-The odd zoning by the docking area is intentional since it was supposed to mimick a realistic rock formation, but I've opted to straighten it up instead and line it up with the rusted up walls.

Other than that, anything else is being fixed/has been fixed.

**Review by itsmeow — APPROVED** [review]
YOLO

**Pull request merged**
