### PR TITLE
Plague Doctor hat no longer covers the face, is no longer a subtype of the bio hood.

### PR DESCRIPTION
**Pull request by Penwin0**
## About The Pull Request
Makes the Plague doctor hat not cover the face, as it does not in the sprite and makes it a subtype of costume instead of bio hood
## Why It's Good For The Game
The sprite very clearly doesn't cover the face and the sprite should not look like a bio hood when held

## Testing Photographs and Procedure

Screenshot_2521

## Changelog
:cl:
fix: Plague Doctor hat no longer covers the face and doesn't look like a biohood when held.
/:cl:

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
But rule of cool!

**Comment by MarkusLarsson421** [comment]
> But rule of cool!

Are you going to use it because it looks cool or because it is an alternative bio-hood with all the gameplay benefits that offers?

**Comment by Rukofamicom** [comment]
This is a balance change not a fix, you are removing intended functionality from a piece of equipment. A fix would be updating the in-hand sprite to be accurate.

While this is primarily a costume piece there is no harm in having it also serve a flavorful purpose and I'm against removing this because while it does give the costume an advantage to have this, it is hardly a game breaking or immersion breaking level of function.

:key:

**Comment by PowerfulBacon** [comment]
I would agree if it wasn't for the fact that its just a hat and isn't actually the mask

**Review by Rukofamicom — APPROVED** [review]

**Comment by Rukofamicom** [comment]
I expected mask and so I read mask. 

That explains the testing evidence picture being seemingly unrelated.

**Comment by Penwin0** [comment]
> But rule of cool!

> Are you going to use it because it looks cool or because it is an alternative bio-hood with all the gameplay benefits that offers?

There are no Mechanical changes in this PR it just unfucks the icon when held and makes it not cover your face.

**Comment by Penwin0** [comment]
> Wait fuck, I completely misread this.

Happens to us all :P

**Pull request merged**
