### PR TITLE
Removes Gluttony Ruin

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Removes Gluttony ruin from lavaland, the one that gives a morph injector.

## Why It's Good For The Game

Morphs when they exist, hold entire rounds hostage by being able to ventcrawl to vital station infrastructure and wordlessly delete it. The lavaland ruin enables non-antag miners to spend a few minutes running around lavaland, grab the morph injector and then effortlessly return back to station to become a round destroying morph - all without any interaction with anyone, just wordlessly ruining a round without any objectives.

Without this ruin, there will be substantially less non-antag morphs being spawned by metagaming miners and ghost-roles, that just happen to know where the injector is located. Self made antags are bad for the game.

## Changelog
:cl:
del: Removed Gluttony ruin.
/:cl:

### CODE REVIEW

**Comment by eeSPee** [comment]
Why?

**Comment by february-ops** [comment]
>non-antag miners to spend a few minutes running around lavaland, grab the morph injector and then effortlessly return back to station to become a round destroying morph 

if you are a non antag you are a non antag, becoming a morph does not change that

**Comment by pickleinjar** [comment]
just no man.
just no. let my miners fucking be antags. dont be cringe.

**Comment by Sinestia** [comment]
You should probably give it another effect instead of just wiping it, or you just gutted a thematic lavaland thing.

**Comment by RDS88-beeman** [comment]
like yeah morphs are cringe
but so is just deleting things without providing a replacement
give us something else gluttony-wise

oh oh also
>lavaland
>effortless

bruh

**Comment by Emiliapains** [comment]
I have one change, Remove the ruins but instead make it a Miner only item for 20 tc like the clown car

**Comment by FortSumter** [comment]
Imagine wanting to remove something fun from the game simply because miners will use it to self antag which is already against the rules. Next you'll want to remove the lesser drake transform or the hive core. I wish coders  understood we don't remove things here and stop trying to kill the game...

**Comment by PowerfulBacon** [comment]
god yea the lesser drake transformation and hive core should definitely go.
but...
the morph ruin?
😕

**Comment by ghost** [comment]
> Why?

Are you incapable of reading PR descriptions?

**Comment by ItsTisme** [comment]
Removing a feature because people break the rules with it is dumb. Might aswell remove insulated gloves or TTV's while your at it

**Comment by eeSPee** [comment]
> > Why?
> 
> Are you incapable of reading PR descriptions?

They may sound bad on paper (everything does) but they were unique ways of making rounds more interesting.

Morphs are a shit antag; their stats are awful and they can be easily destroyed when found out. Best they can do is misplace some items, which is a mild annoyance at best.

**Comment by super12pl** [comment]
> Morphs are a shit antag

Im pretty sure they can qdel most things and eat vertical humans

**Comment by ghost** [comment]
@PowerfulBacon

Neither of those two exist with the sole purpose of destroying everything. The morph ruin is an antithesis to the mining job, you have players that just rush it the second they can and then go for ore silo and every lathe. Ruining the round for rest of the station as there will be no more materials for rest of the shift.

There's nobody else involved, only one player left clicking things for rest of round, ruining the round for everyone else just because they can. The morph event still exists, there's no reason to allow players to turn themselves into one as non-antags. It doesn't require any effort unlike the wishgranter self-antag machine.

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
Unbased PR

**Comment by OceanFish1** [comment]
just qdel lavaland becaus miners too strong lol :trollface:

**Comment by Mick1299** [comment]
The sin ruins are thematic to lavaland. Why not change the item inside the ruin, instead of removing the ruin all together.

Maybe a piece of food with unlimited bites, or the slime crossbreed that spawns food in.

Improve, don't remove.

**Comment by ghost** [comment]
Alternative solution https://github.com/BeeStation/BeeStation-Hornet/pull/3823

**Comment by sircope** [comment]
> Removing a feature because people break the rules with it is dumb. Might aswell remove insulated gloves or TTV's while your at it

they already did that, null crates 😛

**Comment by DatBoiTim** [comment]
> > Morphs are a shit antag
> 
> Im pretty sure they can qdel most things and eat vertical humans

Morphs are a shit antag from a code and execution standpoint. I mean FFS morphs used to be able to turn into the AI eye. If that doesn't scream shitcode, nothing does. 

Also, yeah, ventcrawling makes it very easy to gimp the station with minimal risk, doubly when you can run around as an item. But tbh, I would prefer reworking the morph in general to better fit it's "Prop Hunt" vibe than removal.

That said, this PR isn't really the best direction, since rules already handle the stuff that this PR wants to stop. Sure, there are definitely times where yeah stuff used for self-antag needs to be limited. But this is more so brainlet miners who think "Hee hoo, I am morph now, free antag time" rather than an item which has a pure focus of killing with little challenge or exploration required(Hence why any syndicate or other strong loot from gateway felt way more kosher than nulls).

**Comment by wraith-54321** [comment]
this is what current TG does, please dont be current TG

**Comment by zeskorion** [comment]
ah yes. ided.

**Comment by sircope** [comment]
> ah yes. ided.

zesko came to save us all??? epic???

**Comment by Glcbitj** [comment]
If you want to remove or nerf things because your bad at the game, may i suggest you go code to /tg/station? I'm sure you'd be appreciated there :)

**Comment by PowerfulBacon** [comment]
no author, unlikely changes will be made

**Pull request closed without merging**
