### PR TITLE
Screentips!

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports:
- https://github.com/tgstation/tgstation/pull/56729
- https://github.com/tgstation/tgstation/pull/65963
- https://github.com/tgstation/tgstation/pull/63567
- https://github.com/Monkestation/MonkeStation/pull/505

## About The Pull Request
Adds hoverable screentips from tg, lets you see what you hover over

TODO

- [x] Finish base pr
- [x] confirm working
- [ ] fix preferences errors FUCK
- [ ] testing pictures 
- [ ] ready to review

## Why It's Good For The Game
Makes the game easier for newer players by informing them of what they are looking at

Bee is a bit behind on accessibility for new players compared to other TG forks. This is one of a few features that should help.

## Testing Photographs and Procedure
image
cellcharger

## Changelog
:cl: dwasint, Mothblocks, Qustinnus, apynnonen, ghost, and RKz
add: screentips, lets you see what you are hovering over
add:preference for enabling screentips and determining color
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
so far, it has full functionality in game. All thats missing is cleaning up preferences

**Comment by llol111** [comment]
didnt we already have this PR a good long while ago? Or was that some other obnoxious on screen text thing?

**Comment by St0rmC4st3r** [comment]
> didnt we already have this PR a good long while ago? Or was that some other obnoxious on screen text thing?

We did. iirc, we decided against it for performance reasons.

**Comment by St0rmC4st3r** [comment]
#4645 it was. Deemed expensive and unnecessary, since this already exists in the bottom left corner and we don't have combat mode. Also doublekeyed, so unless some drastic changes happened over a year, this is unlikely to be merged.

**Comment by Tsar-Salat** [comment]
> we decided against it for performance reasons.

- https://github.com/tgstation/tgstation/pull/63567

**Comment by Archanial** [comment]
I don't like it personally

but it can be turned off

so if it doesn't cost us much, it's fine

**Comment by PowerfulBacon** [comment]
I dislike these and think they look horrible.
I'm not against adding in some text that shows what you are hovering over, but the giant text at the top center of the screen is a pretty bad style choice and needs improvement.

**Comment by PowerfulBacon** [comment]
I'd be fine with them if you can provide a design that has a bit of a nicer style (assuming the mouse entered doesn't provide dramatic performance issues on higher pops, which it *shouldnt*)

**Comment by Tsar-Salat** [comment]
> but the giant text at the top center of the screen is a pretty bad style choice and needs improvement.

Can you tell me what exactly is off-putting about it, specifically?

I am fine with making changes to fit the stylistic choice of the server, however it is rather difficult to try to address others concerns about it when the maximum depth I've gotten so far is "it looks bad".

Is it specifically the font? Placement? Functionality? How can I improve it to fit expectations?

**Comment by PowerfulBacon** [comment]
Kinda of hard to pinpoint, since its one of those ones that just feels wrong, any video I've seen with it feels wrong and it just seems out of place on all servers I've seen.

I think it needs to fit more with the rest of the UI primarilly, having some kind of background with the UI style might make it look nicer and having the font colour as something else might help. There are probably more fitting fonts too.
Perhaps the position of it could be moved.

The one I like the most that I've seen is the one in the bottom left of TG (Got this screenshot from this video https://www.youtube.com/watch?v=XqFDpmyar7w)
image

Perhaps you could try making it only appear after you are hovered over an element for like 1/2 seconds, so it isn't always visible too

**Comment by Tsar-Salat** [comment]
> having some kind of background with the UI style might

That is the opposite of this features intemded function. It is intended to stand out and be visible from the periphery.

People seem to have the wrong idea and seem to have misjudged my intentions, so I will clear it up.

Screentips as a whole are meant to provide VISIBILITY for new players and others who have yet to fully learn the UI. It is intended to look highly visible for these new players and people who have it on by choice.

Ss13 as a whole has a incredibly steep learning curve, such as its entirely unique UI and hand system unlike any other game, which can put off a lot of people.

If WE can provide 1 more feature to make it easier for these new players, it's worth it.
 If one more player decides to stay because they can *actually* see what that object is and don't have to look at a tiny little 2 point font in the bottom left of their screen, it's worth it.

Sure, for people who are very familiar with the UI, they may find this new artifact useless or distracting, but that I feel is because long-time users already have the knowledge. 
But for a new player? The more we can cushion the awkward feeling from this Janky ass 20 year old engine that we all love to make it easier for a new player, the better.

If you feel comfortable on your knowledge of the UI, feel this artifact is distracting or ugly or any other reason, that is entirely valid decision and I respect that. The choice to remove or add this feature will always be there.

However, I urge you to consider the perspective of other people in this pr. I personally do not plan on using these myself.

Thanks for listening to my TED talk

**Comment by llol111** [comment]
>Screentips as a whole are meant to provide VISIBILITY for new players and others who have yet to fully learn the UI.
This will not help anyone learn the exsisting UI, it will just be the Ui that new players use instead. Just like how runechat has made people, espechaly that started ss13 after it was introduced, barely ever look at the actual chat.

That dosnt need to be a bad thing of course, despite the negative i just listed i do like runechat for instance. 
Theres an argument to be had on wether or not this is good UI, of course. 

Personaly i think its not. But thats just feelings, no debate to be had there realy.

Important point here is that is disablable, so you can just turn it off and forget it exsists.

**Comment by Tsar-Salat** [comment]
> Just like how runechat has made people, espechaly that started ss13 after it was introduced, barely ever look at the actual chat.

How is runechat comparable to this? I agree with the point you are making, runechat has made people not look at chat which can be annoying.  I do not see how that is comparable to screentips though.

I dont see how screentips would make players overlook anything, it is supposed to magnify them.

**Comment by PowerfulBacon** [comment]
These definitely won't replace the chat in any way, since I suspect most new players will use the right click menu to see what things are, since it comes with icons too.
At the same time, how would having them designed to fit with the rest of the UI make them not useful for new players?

This kind of ends up existing as something to just look nice and modern for people watching on YT videos and stuff, so I think it should fit with the game and look nice & modern. I doubt this will have a significant effect, but its hard to tell without watching someone new play the game

**Comment by Tsar-Salat** [comment]
> At the same time, how would having them designed to fit with the rest of the UI make them not useful for new players?

I don't disagree that it should fit the design. I disagreed with your example that put it as a miniscule 2 font text on the bottom of the screen. 

> The one I like the most that I've seen is the one in the bottom left of TG (Got this screenshot from this video https://www.youtube.com/watch?v=XqFDpmyar7w) image
> 
> Perhaps you could try making it only appear after you are hovered over an element for like 1/2 seconds, so it isn't always visible

**Comment by Sinestia** [comment]
> Kinda of hard to pinpoint, since its one of those ones that just feels wrong, any video I've seen with it feels wrong and it just seems out of place on all servers I've seen.
> 
> I think it needs to fit more with the rest of the UI primarilly, having some kind of background with the UI style might make it look nicer and having the font colour as something else might help. There are probably more fitting fonts too. Perhaps the position of it could be moved.
> 
> The one I like the most that I've seen is the one in the bottom left of TG (Got this screenshot from this video https://www.youtube.com/watch?v=XqFDpmyar7w) image
> 
> Perhaps you could try making it only appear after you are hovered over an element for like 1/2 seconds, so it isn't always visible too

The problem with that small thing in the corner is that it doesn't accomplish one of the big things that screentips do, which is making the game more playable on 1440p and 4k monitors especially.

 The text in the corner is utterly tiny at those resolutions, the screentip is much more comfortable. Adding a delay would make it horrible to use.

**Comment by Tsar-Salat** [comment]
Alright, the preferences in this continue to be broken despite what I've tried, I am going to close this until I learn how to fix it. Clearly, I am lacking the knowledge and experience at the moment.

**Comment by PowerfulBacon** [comment]
I should also note that defining MouseEntered on everything adds additional overhead as it makes it so byond sends additional communications every time you hover something

**Comment by Tsar-Salat** [comment]
> I should also note that defining MouseEntered on everything adds additional overhead as it makes it so byond sends additional communications every time you hover something

This PR ports MouseEntered queues.

**Comment by PowerfulBacon** [comment]
It doesn't matter, there is no possible optimisation that you can do on that as it is byond-level. I should also note that from experimentation MouseEntered() doesn't seem to work about 30% of the time

**Comment by Penwin0** [comment]
In addition to what bacon said optimization wise, I think these just look horrible

**Comment by Tsar-Salat** [comment]
> In addition to what bacon said optimization wise, I think these just look horrible

How would you like me to improve them?

**Comment by PowerfulBacon** [comment]
I wonder if we could do something like more modern games where hovering over it for a certain amount of time causes the name to appear above the object you are hovering. (I should note that I created a system that did this, in order to display interaction tips like welding tool for construction, but MouseEntered and MouseExitted were unreliable and didnt always get captured for some reason)

**Comment by PowerfulBacon** [comment]
This PR is drafted but inactive. Closing.

**Pull request closed without merging**
