### PR TITLE
Supercruise Update 2 (Technology Refactoring, Exploration Job Removal, Cargo Refactoring)

### PR DESCRIPTION
**Pull request by PowerfulBacon**
This will likely need a lot of testing to refine the numbers and get the balancing correct.

## TODO

 - [ ] Find a way to implement something that cargo can send to science to make a profit, putting them in a mutually beneficial relationship.
 - [ ] mapping changes
 - [ ] Give scientists the exploration shuttle and dock back
 - [ ] General polishing
 - [ ] Make it so the research disks contain data the station has to analyse so it makes sense lorewise
 - [ ] Add a sell all button to the cargo console, so cargo ops can be done without the use of the shuttle flight console.
 - [ ] Restrict cargo shuttle from going to lavaland.

## About The Pull Request

Removes the exploration job role, exploration comms and exploration access.
Removes the VIP extraction missions.
Removes assassination missions.
Removes research disks.
Removes discovery research.
Implements 4 new research types: Physics, Biomedical, Military and Bluespace.
Physics, biomedical and military research disks can be purchased from cargo with a limited supply.
Bluespace research can be obtained by putting artifact fragments in the destructive analyser. Artifact fragments can be found at ruins, on lavaland, on a new special type of asteroid that spawns randomly and by managing to break an artifact.
Physics, biomedical and military research disks can also be located on ruins.
The cargo shuttle is no longer timed, but pilotable.
The cargo shuttle no longer docks at Z-Level 2 (Centcom), but instead gets its crates when it is docked with the Phobos map object.
Supercruise shuttles can undock from locations even after initiating docking.
You can now view the locations of shuttles on shuttle consoles at all times by using the local map options.
The cargo tablet app no longer can control teh supply shuttle.
The pirate event now scales with the cargo budget amount.
Express supply consoles now have a cooldown of 120 seconds rather than 10.

Cargo now sells items by docking with centcom and using the communication tab located on shuttle consoles. It can now collect orders by using the 'Collect Orders' button in the communications menu on shuttle consoles. If the supply shuttles departs from centcom, it will automatically pick up all orders when being controlled by a cargo supply console.
If any shuttle other than the cargo shuttle attempts to pick up orders from centcom, it will only pick up orders placed on the account of the person who attempts to pick up the orders from centcom.

These monitors now display distance instead of time.
image

<details>
<summary>Flight control map changes</summary>

image
image
image

</details>

## Why It's Good For The Game

Currently there are a lot of complaints related to the exploration job, and technology disks in general. I have made the decision to remove the exploration job role since its the only feasable way to fix a lot of these issues and exploration is starting to run out of unique content.

The main issues raised where:
 - Exploration job powergaming
 - Research disk collection being unreliable and exploration crews having no incentive to collect them
 - Discovery research was disliked by a lot of people
 - VIPs don't get removed from the round, so just exist to screw about after being rescued

I wanted something to exist that limits research so that building a couple of servers can't get the whole tech-tree done in 25 minutes.

Another design goal which was requested was that science shouldn't be entirely dependant on a single job / department. This PR implements the cargo science packs, which are the most effective way to obtain the new research types, however there are other ways to obtain it to. Science can use their shuttle to travel to ruins and locate them.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
todo
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
The research station gets researched things delivered to it?

**Comment by Effemu** [comment]
flying shuttles is boring tho

**Comment by PowerfulBacon** [comment]
> flying shuttles is boring tho

The supply console can control the shuttle remotely via an autopilot functionality

**Comment by Mat05usz** [comment]
What if megafauna, tendrils and shit spawned on meteors, so cargo could send artifacts and stuff found by miners to science? Or make lavaland spawn in parts rather than a big ass empty wasteland that sometimes spawns stuff

Edit: I'm saying this because my biggest letdown with supercruise is basically removing everyone but explorers from space exploring. I'd be super nice if exploring with just a jetpack and suit was possible again, so a volunteer could just go to space and try to mine stuff.

**Comment by williamcll** [comment]
Ah yes more ways to make T4 parts harder to get. Even austation gave up on that recently.

**Comment by Fronsis** [comment]
So... if i understood correctly this will make Science/rest of the station to bother cargo to prioritize a rush on buying the Physics/biomedical/military research disks making science reliable on Cargo knowing how to make money, this could've come in handy with the rewards of credits by explo missions

Also
>  exploration is starting to run out of unique content.

Didn't we had a couple of threads with suggestions? I mean of course someone needs to code them and such but, the ideas are there from what i've seen

I'll prolly write up a little more later on some extra opinions on this

**Comment by Daridine** [comment]
>The cargo shuttle no longer docks at Z-Level 2 (Centcom), but instead gets its crates when it is docked with the Phobos map object.  
>Cargo now sells items by docking with centcom and using the communication tab located on shuttle consoles. It can now collect orders by using the 'Collect Orders' button in the communications menu on shuttle consoles. If the supply shuttles departs from centcom, it will automatically pick up all orders when being controlled by a cargo supply console.  
===
Can we make up a different name for the place the shuttle docks to sell things and pick up crates? To avoid confusion and perhaps embrace lore more?
Like, Central Command is where everyone escapes to and ERT's come from. But this shuttle isn't going to CENTRAL Command right? I might be misreading this or missing something, but if the shuttle is pilotable they aren't going to the Z-Level 2 right?

**Comment by Mat05usz** [comment]
> Like, Central Command is where everyone escapes to and ERT's come from. But this shuttle isn't going to CENTRAL Command right? 

Technically it does, and it even says on cargo console it goes to 'Centcom'.

> I might be misreading this or missing something, but if the shuttle is pilotable they aren't going to the Z-Level 2 right?

I think that's just a typo an Bacon meant Z-level 1

**Comment by PowerfulBacon** [comment]
Personally I'm having doubts about this PR, not sure if this is the right way to go about it.

**Comment by PowerfulBacon** [comment]
I think this could do with rethinking

**Pull request closed without merging**
