### PR TITLE
Ovulogenesis bugfix

### PR DESCRIPTION
**Pull request by DatBoiTim**
## About The Pull Request
Ovulogenesis Didn't Spawn the Eggs in the Appropriate Location. I fixed that. Also they didn't have the sprites setup right in the code. I fixed that as well.
I had to adjust how the thresholds were tracked due to some runtimes during testing. Those are staying for fear it will break without it.

## Why It's Good For The Game
fixes bugs

## Changelog
:cl: DatBoiTim
fix: Ovulogenesis actually spawns eggs
fix: Ovulogenesis Eggs have their sprites setup correctly in code
/:cl:

### CODE REVIEW

**Comment by DatBoiTim** [comment]
I hate working with sprites in code

**Comment by DatBoiTim** [comment]
To elaborate on the sprite issue. The iconstate was meant to be the name of the specific icon, while icon was the file containing a bunch of them. I just had it file path to the specific icon. I am dumb

**Comment by DatBoiTim** [comment]
HUEVOS

Actual Screencap of testing the disease for functionality at checksum 4dfe3b3 with no varedits

**Comment by zeskorion** [comment]
test 👏 ur 👏 stuff

**Comment by DatBoiTim** [comment]
> test 👏 ur 👏 stuff

I developed a lot of code during that period of time on a Mac laptop(because it's also my school laptop), so testing wasn't an option.

I was also juggling multiple other projects like some sort of code project circus clown.

Anyways I fixed the issue as soon as I got confirmation.

I'm going to sleep now because it's 1am and I have an 8 o'clock opener at my desk

**Comment by leestriter** [comment]
Please speed merge.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
