### PR TITLE
Satchel sprite fix

### PR DESCRIPTION
**Pull request by imsynthex**
## About The Pull Request

Satchel sprites have that weird thing where they were only made for jumpsuits and so when jumpskirts got added they started looking wack

bottom - before
top - after
image

## Why It's Good For The Game

Fix

## Testing Photographs and Procedure

Shown in the first section

## Changelog
:cl:
fix: fixed some rogue pixels on satchel sprites that made them look bad with jumpskirts and the alternate state of jumpsuits
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I can't really tell the difference since the images are kind of blurry

**Comment by Penwin0** [comment]
> I can't really tell the difference since the images are kind of blurry

The random ass black dots are gone

**Comment by Tsar-Salat** [comment]
Can you show us the difference with a colored departmental satchel on the grey jumpskirt?

**Comment by imsynthex** [comment]
before
before_sci_jumpsuit_up
before_sci_jumpsuit_down
before_engi_jumpsuit_up
before_engi_jumpsuit_down

after
after_sci_jumpsuit_up
after_sci_jumpsuit_down
after_engi_jumpsuit_up
after_engi_jumpsuit_down


The pixels I removed are dark grey on pretty much all satchel sprites so the difference while wearing a jumpsuit is not really noticable

**Comment by Penwin0** [comment]
Why tf is IDB not running on this

**Review by PestoVerde322 — APPROVED** [review]
Seems all good, Approved.

**Review by itsmeow — APPROVED** [review]

**Pull request merged**
