### PR TITLE
Ports tgui lists

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

Ports tgui lists from tgstation/tgstation#56065

## Why It's Good For The Game

Reactive UIs are always good

## Changelog
:cl:Watermelon914 
add: Added tgui lists
/:cl:

### CODE REVIEW

**Comment by jupyterkat** [comment]
UIs not opening, fix soon:tm:

**Comment by Crossedfall** [comment]
> 
> 
> UIs not opening, fix soon™️

Converting this to a draft. Mark it as ready for review when things are fixed up.

**Comment by jupyterkat** [comment]
Working correctly now
image

**Comment by Crossedfall** [comment]
If it works, why close the PR?

**Comment by jupyterkat** [comment]
woops, pressed that by a mistake

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
image

**Comment by jupyterkat** [comment]
tgui bluescreens if you type “]” or “[“ into the search box, fix soon

**Comment by jupyterkat** [comment]
problem boils down to it handling duplicate item names very poorly, should be working now

**Comment by PowerfulBacon** [comment]
Seems alright in testmerge

**Review by PowerfulBacon — APPROVED** [review]

**Comment by francinum** [comment]
Wow, this is actively less useful.

Enter no longer selects the currently selected item.
Movement keys are no longer eaten and thus you will change selection while moving and vice versa.

**Comment by bloons3** [comment]
Perhaps not everything should have been made a TGUI list until their underlying issues were worked out

**Comment by jupyterkat** [comment]
@bloons3 I'll fix it soon enough:tm:

**Pull request merged**
