### PR TITLE
More xeno toxins

### PR DESCRIPTION
**Pull request by St0rmC4st3r**
## About The Pull Request

Adds Squid mutation toxin upon the requests of squid mains being transformed into something else as well as a Zombie mutation toxin, that has a catch. Right. Krokodil.

Squid toxin = 1 Unstable Toxin + 20 Water + 10 Salt
Zombie toxin = 1 Advanced toxin +10 Krokodil + 10 Bad food

## Why It's Good For The Game

Squid mains can now turn back and "The walking Dead" fans can become a walker wanna be without harming the crew physically.

## Changelog
:cl:
add: Squid and Zombie Xenobio toxins
add: Squids added to the Unstable Mutation Toxin pool
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
Sweet. Will you update the wiki with the chemical recipes for these?

**Comment by zeskorion** [comment]
i told you already that zombie toxin aint good.

**Comment by St0rmC4st3r** [comment]
Zesko, _THIS_ zombo toxin is good. I would like to see some holopara ghost enraged when they realize that it was a Krokodil Zombie toxin, hehe.

**Comment by St0rmC4st3r** [comment]
@Cenrus, wiki updated for the previous PR and for this one too

**Review by MarkSuckerberg — APPROVED** [review]
I like it

**Review by ike709 — APPROVED** [review]

**Comment by hackerjsimon** [comment]
if its high functioning I say yes

**Pull request merged**
