### PR TITLE
Antag toks

### PR DESCRIPTION
**Pull request by qwertyquerty**
tentative numéro deux

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Somehow the merge broke my PR

**Comment by qwertyquerty** [comment]
Why do we have broken code in master

**Comment by qwertyquerty** [comment]
Please build this time please

**Comment by qwertyquerty** [comment]
Why do travis have to be so slow

**Comment by qwertyquerty** [comment]
hell yeah travis

**Comment by CthulhuOnIce** [comment]
**This branch has conflicts that must be solved!**

**Comment by CthulhuOnIce** [comment]
I'll just manually merge it

**Pull request merged**
