### PR TITLE
Removes very sus plush code

### PR DESCRIPTION
**Pull request by TeomanTheGreat**
## About The Pull Request

Removes the sus plush toy code
## Why It's Good For The Game

Read the lines I have deleted and tell me why they should stay. 
If you are wondering how this code even got into the codebase the answer is TG.
## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: Phil Smith
del: Plush toys can no longer procreate (this is not a sentence I imagined myself writing this morning)
/:cl:

### CODE REVIEW

**Comment by Mat05usz** [comment]
What the fuck is that and why did I not know it exists lmao

**Comment by Liidero** [comment]
I don't see why this should be removed. It's such a niche thing that makes duplicating plushies possible which is a funny little detail. The texts -in game- are PG enough but the only thing I would understand removing is the comments in the code and or changing the line `[Kisser] passionately embraces [src] in your hands.` to be a little less "passionate" lol
(or some other piece of code I missed that's weird)

**Comment by Liidero** [comment]
Maybe I am biased since I like duplicating my plushies 👎

**Comment by TeomanTheGreat** [comment]
> What the fuck is that and why did I not know it exists lmao

Do you think God stays in heaven because he too lives in fear of what he's created?

**Comment by PowerfulBacon** [comment]
> I don't see why this should be removed. It's such a niche thing that makes duplicating plushies possible which is a funny little detail. The texts -in game- are PG enough but the only thing I would understand removing is the comments in the code and or changing the line `[Kisser] passionately embraces [src] in your hands.` to be a little less "passionate" lol (or some other piece of code I missed that's weird)

erper

**Comment by Mat05usz** [comment]
Wait so it makes possible to reproduce nar'sie plushies?

**Comment by PowerfulBacon** [comment]
this is more complex than half the code integral to the entire game lol

**Comment by Mat05usz** [comment]
> this is more complex than half the code integral to the entire game lol

Yeah, and the fact that I literally never seen it happen in-game just makes me regain some, very little, respect to SS13 players

**Comment by Pirill** [comment]
Plush code is such a cute easter egg though, why would you remove it??

**Comment by PowerfulBacon** [comment]
find and replace /obj/item/toy/plush with /mob/living/carbon/human :trollface:

**Comment by AnCopper** [comment]
This is used for if a Nar'sie and Ratvar plushies are next to each other, they either create another plushie or blow up.

Don't remove it, it's hilarious.

**Comment by Mat05usz** [comment]
> This is used for if a Nar'sie and Ratvar plushies are next to each other, they either create another plushie or blow up.
> 
> Don't remove it, it's hilarious.

I don't think that's the code? This is when you attack plushie with another, not place them near each other

**Comment by AnCopper** [comment]
> > This is used for if a Nar'sie and Ratvar plushies are next to each other, they either create another plushie or blow up.
> > Don't remove it, it's hilarious.
> 
> I don't think that's the code? This is when you attack plushie with another, not place them near each other

Oh, oh okay.

**Comment by TeomanTheGreat** [comment]
This pr has 5 dislikes at the moment of me posting this. I am losing my faith in you people. If your problem is not being able to get more plushes you can just order them from cargo.

**Comment by Mat05usz** [comment]
> This pr has 5 dislikes at the moment of me posting this. I am losing my faith in you people. If your problem is not being able to get more plushes you can just order them from cargo.

Giving it a like, have some faith restored

**Comment by Pirill** [comment]
> This pr has 5 dislikes at the moment of me posting this. I am losing my faith in you people. If your problem is not being able to get more plushes you can just order them from cargo.

But that's not as funny as making a plushie army out of Orion Trail rewards.

**Comment by TeomanTheGreat** [comment]
Can someone give me a reason for this code to stay other than "uwu cute plush erp wholesome!!~"

**Comment by Syrox25** [comment]
because its a childish spite PR to remove something funny and inconsequential because... it reminds you how kids are made and you cant handle it? If you are calling this ERP or some sort of fetish content.. then I don't know what to tell you...

**Comment by TeomanTheGreat** [comment]
> because its a childish spite PR to remove something funny and inconsequential because... it reminds you how kids are made and you cant handle it? If you are calling this ERP or some sort of fetish content.. then I don't know what to tell you...

Its weird code that really doesn't serve a purpose. I'm not calling it erp but im saying it's very weird and doesn't really have a place here. If it's about this being a niche feature then we shouldn't remove any bad code at all.  And as I said before you can still get a lot of plushes it just involves walking to cargo and ordering a plush crate.

**Comment by mcmeiler** [comment]
If we're gonna start removing all the hilarious jokes in the code, you might as well delete the entire repository.

**Comment by Mat05usz** [comment]
When people want the code to be more RP friendly but then funni haha sex between plushies is suddenly a core feature that cannot be deleted, even though probably noone has ever used it anyways lmao

> because its a childish spite PR to remove something funny and inconsequential because... it reminds you how kids are made and you cant handle it? If you are calling this ERP or some sort of fetish content.. then I don't know what to tell you...

Sex between inanimate objects isn't exactly RP friendly, also if it's funny for you then well, cool

**Comment by TeomanTheGreat** [comment]
Why is this the pr that starts a flame war. Seriously guys what the fuck.

**Comment by Pirill** [comment]
> Why is this the pr that starts a flame war. Seriously guys what the fuck.

Probably because you're trying to turn an obscure easter egg mechanic into an unironic issue and implying it's a sinister underhanded reference to ERP, which makes me worried for your thought process to begin with.

This has nothing to do with RP quality, those arguments are disingenuous. It's just an easter egg with little practical consequence and much like anything else of this sort it just adds a tiny bit of depth or an amusing interaction for players.

> Why not remove it then?

You could ask the same for any other easter egg, joke or reference in the code and the answer would be the same. There's nothing stopping you from removing all wacky content but the game thrives on the myriad little references and hidden interactions people can find out about.

Honestly, given your comments here and in the Discord, I can't help but think you're doing this in bad faith either to get a reaction or to point and laugh at _le epic ERP enjoyers_ who get off on smushing pixelated plushies together somehow. I feel silly even having to write this comment on this dumb topic so I'm going to leave it at that.

**Comment by Mat05usz** [comment]
> This has nothing to do with RP quality, those arguments are disingenuous.

So, what's your though process when it comes to that? Is it fine that plushies have sex? Does that improve/degrade immersion?

**Comment by TeomanTheGreat** [comment]
> > Why is this the pr that starts a flame war. Seriously guys what the fuck.
> 
> Probably because you're trying to turn an obscure easter egg mechanic into an unironic issue and implying it's a sinister underhanded reference to ERP, which makes me worried for your thought process to begin with.
> 


I'm saying the code is really weird and has no place here

> This has nothing to do with RP quality, those arguments are disingenuous. It's just an easter egg with little practical consequence and much like anything else of this sort it just adds a tiny bit of depth or an amusing interaction for players.

>

I haven't said a thing about rp lol. My entire argument is that this has no place here. 
 
> > Why not remove it then?
> 
> You could ask the same for any other easter egg, joke or reference in the code and the answer would be the same. There's nothing stopping you from removing all wacky content but the game thrives on the myriad little references and hidden interactions people can find out about.
> 

Since when does mass producing plushies with questionable code count as a wacky code feature. Why does this hold so much importance to people. As I said earlier plushies can literally be bought if you go to cargo and buy some crates. This isn't locking away plushes.


> Honestly, given your comments here and in the Discord, I can't help but think you're doing this in bad faith either to get a reaction or to point and laugh at _le epic ERP enjoyers_ who get off on smushing pixelated plushies together somehow. I feel silly even having to write this comment on this dumb topic so I'm going to leave it at that.

Thats not what I said at all. Lol. It is funny seeing the importance people place on a feature they have never even heard of or even bothered reading the code to. People are acting like its the end of the world if the questionable plush code is removed.

**Comment by TeomanTheGreat** [comment]
You know what I think I'm closing this. I have a headache right now trying to figure this out. I have no idea why you guys want to keep this shit. Its interesting how many people came to this pr to argue why plush reproduction is an important part of the game but to each their own I suppose.

**Comment by DerpiestBruh** [comment]
WHAT IS THIS MADNESS

**Pull request closed without merging**
