### PR TITLE
Prevents a military coup

### PR DESCRIPTION
**Pull request by bloons3**
## About The Pull Request
Removes keycard authentication from Security officers and removes the authentication device from the Warden's office.

## Why It's Good For The Game

Security should not have arbitrary control over the station's alert level. Heads of Staff have access to keycard authentication devices inside of their offices, as well as Bridge.

Security Officers, the Detective, and the Warden do not have access to Bridge because they are not station leadership. It follows that since they are not station leadership, they should not make decisions for the station as a whole.

This change will prevent Security from unilaterally seizing control of the round, and will instead keep control of the round with the Command Staff.

## Changelog
:cl:
del: Removed keycard authentication access from Security
del: Removed keycard authentication device from Warden's office
/:cl:

### CODE REVIEW

**Comment by RDS88-beeman** [comment]
someone make a PR called "military coup" that gives seccies, det, and warden bridge access.
but yeah good change

**Comment by bloons3** [comment]
> someone make a PR called "military coup" that gives seccies, det, and warden bridge access.
> but yeah good change

Keycard Authentication was given to security under the pretense that if every single command staff were dead or otherwise incapable, that Security should be able to red alert or set Emergency Access stationwide.

**Comment by Cenrus** [comment]
Good change, never liked how the brig could just red alert on their own without help from anyone else in command

**Review by ike709 — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
Now command does commands jobs

**Pull request merged**
