### PR TITLE
Spaced Atmospherics

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
Spaces Atmospherics and partly optimizes piping.

### Details
- The overall size of Atmospherics has been slightly increased.
- Each chamber has their own port and pump with an already filled canister present to signify which chamber has what gas.
- It is possible to set up the turbine or send any chambers' given gas to the turbine and or the SM as an AI.
- All pipe networks can be sent to waste.
- The spaced area can be used to make easy and sinple vacuum chambers for all the fusion needs.
- The area can be used to make a singularity or tesla engine, no additional equipment has been provided for this.
- Most window pipes now have a layer adapt under them!!

## Why It's Good For The Game
There is a lot of clutter in Atmospherics which is never ever used. I've removed it and spaced the main area of Atmospherics to make it cooler, more practical and also newbie friendly so plasma leaks aren't as devastating.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image

https://github.com/user-attachments/assets/852ef60e-ccf4-4601-bbab-6d6d410f3354

</details>

## Changelog
:cl:
tweak: (Meta) Spaces Atmospherics.
balance: (Meta) Optimizes piping.
balance: (Meta) Adds two extra Atmospherics hardsuits (three in total).
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
The APC is dead in the video, which makes the area look a lot less pleasing to look at without lights.

Is there a missing wire?

**Comment by MarkusLarsson421** [comment]
Was hanging around for too long before I started recording. It works, SMES just drained immediately.

image

**Comment by MarkusLarsson421** [comment]
A better picture of it.

image

**Review by mystery3525 — CHANGES_REQUESTED** [review]
Because you're using the shiptest holofields, you need to also copy the blast doors they use at every holofield. Wasteful as NT is, it makes no sense to leave a holofield on if no one is going to be passing through.

Also: Please route the cables and pipes THROUGH the middle of the holofield, under solid objects bad unless absolutely necessary

**Comment by PowerfulBacon** [comment]
This is just a bad idea, it makes atmospherics completely inaccessible to anyone without a hardsuit trying to enter from space. Workplaces on the station shouldn't just be spaced

**Comment by MarkusLarsson421** [comment]
> This is just a bad idea, it makes atmospherics completely inaccessible to anyone without a hardsuit trying to enter from space. 

Well, there are three atmospherics hardsuits, one by the turbine and two by the gear area. 

> Workplaces on the station shouldn't just be spaced

I guess, but it is neat and unique. We're in space after all, why not make use of those unique properties of space?

**Comment by Rukofamicom** [comment]
I mirror Bacon's opinion already stated above.

**Comment by Rukofamicom** [comment]
Due to personal circumstances, author has requested that all PRs be treated "as-is" for the time being. 
This one is remaining open due to no outstanding issues that a discussion can't overcome.

**Comment by Archanial** [comment]
🔑 
sorry but this isn't a good idea

**Pull request closed without merging**
