### PR TITLE
Ashwalker camp overhaul

### PR DESCRIPTION
**Pull request by Marshmellow105**
## About The Pull Request

Fresh coat of paint for the ashwalker camp, considering I was already doing the syndicate base and this also looks like it needs TLC

## Why It's Good For The Game

The old camp was a bit of a mess, this new one cleans it up a little and introduces some more starting gear so the ashies can have a variety of things to play with on the getgo, from a bone sword and shield to a new alchemy area for curious lizards to brew evil potions (that they can use with a blowgun!)

This also gives them a second gate, so the entrance to and from the camp isn't just some random hole.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

(there is a mortar and pestle in here too, the mushrooms just covered it for some reason)

ash-med

ash-botany

ash-gear

ash-meat

ash-full

</details>

## Changelog
:cl:
tweak: Ashwalker camp overhaul
/:cl:

### CODE REVIEW

**Review by Tsar-Salat — APPROVED** [review]
Looks alright. Seems to have everything the former base had.

**Comment by MarkusLarsson421** [comment]
They get five corpses for extra spawns, it is quite a lot of free eggs for respawning or spawning new ashwalkers. I'd trim it down to probably one, ashwalkers can find more corpses out in the wastes.

You're missing a Syndicate toolbox and an experimental welder. It might be important to have a reliable welding fuel source, hence the experimental welder. But I am not too experienced with ashwalker gameplay to know for sure.

I don't think including `/obj/item/reagent_containers/cup/glass/waterbottle/random` is ideal. It can contain almost ANYTHING and isn't used anywhere else. Same thing with the relic water bottle, however this one can be found in necropolis chests. So it is debatable. 

image

There is a lot of items which I am unsure if they are different from the original ashwalker camp. Might look into it further at a later date.

**Comment by Marshmellow105** [comment]
> You're missing a Syndicate toolbox and an experimental welder. It might be important to have a reliable welding fuel source, hence the experimental welder. But I am not too experienced with ashwalker gameplay to know for sure.

In my experience these tools are almost exclusively used for surgery and instead of them I gave the lizards the full suite of ghetto surgery tools in the shaman hut

**Comment by Marshmellow105** [comment]
> They get five corpses for extra spawns, it is quite a lot of free eggs for respawning or spawning new ashwalkers. I'd trim it down to probably one, ashwalkers can find more corpses out in the wastes.

> I don't think including `/obj/item/reagent_containers/cup/glass/waterbottle/random` is ideal. It can contain almost ANYTHING and isn't used anywhere else. Same thing with the relic water bottle, however this one can be found in necropolis chests. So it is debatable.

Regarding these, I am pushing the following changes:
- Changed: Location of lizard plushie to the 'armoury' and its name to 'Sharpens-the-Spears'
- Changed: The random waterbottle to be a second relic version
- Removed: Two of the five corpses, leaving them with three which I believe is close to if not one more/less than the old camp
- Added: A second empty glass bottle (for evil potions) and a blowgun with one syringe (to get them kickstarted and guide them as to what the alchemy area can be used for)

**Comment by Programs-The-Station** [comment]
> They get five corpses for extra spawns, it is quite a lot of free eggs for respawning or spawning new ashwalkers. I'd trim it down to probably one, ashwalkers can find more corpses out in the wastes.

It's important to have at least two corpses, because that gives one egg. If you are the first ashwalker part way through the round, the quick extra egg notification helps alert ghosts that more ashwalkers are up and about, so you are more likely to get a buddy.

> Removed: Two of the five corpses, leaving them with three which I believe is close to if not one more/less than the old camp

That is in fact, one more than the previous camp.

**Comment by Rukofamicom** [comment]
> In my experience these tools are almost exclusively used for surgery and instead of them I gave the lizards the full suite of ghetto surgery tools in the shaman hut

They are also used for construction, and the welding tool for starting the bonfire that they used to smelt metals and cook.

**Comment by Marshmellow105** [comment]
I did give them some of the previous tools they had with the bonfire and some ghetto surgery steps in mind.

What tools do you see them using in construction? I could add a mechanical toolbox, I just didnt think they needed it as I hadnt seen that.

**Comment by Rukofamicom** [comment]
As much as I want to be involved in this I'm struggling to find the time right now. My wife is going to look at making some sprites for Ashwalkers to use but it's looking like it'll be a couple weeks

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
