### PR TITLE
[PORT] TG's Trasen-Knox HUD

### PR DESCRIPTION
**Pull request by imsynthex**
## About The Pull Request

Ports: https://github.com/tgstation/tgstation/pull/70474

## Why It's Good For The Game

Looks quite nice

## Testing Photographs and Procedure

image

## Changelog
:cl: Imaginos16, imsynthex
imageadd: added TG's Trasen-Knox HUD
code: human HUD active hand icons can now be separate for each hand
tweak: midnight is now the default theme instead of clockwork
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
Sexy.

You may be the guy to finally make me change ui after 4 years

**Comment by imsynthex** [comment]
Updated the PR body to show the latest iteration, hopefully addressing all concerns (also ended up porting over separate active hand icons)

**Review by PestoVerde322 — DISMISSED** [review]
Code seems fine, icons too, Testing it with this HUD or other didn't collapse everything, approved.

**Comment by imsynthex** [comment]
The packpack issue wasn't a thing afterall, I'm just dumb

**Review by PestoVerde322 — APPROVED** [review]

**Pull request merged**
