### PR TITLE
Ports "Pointing at something will rotate the arrow and you can pixel-perfect point"

### PR DESCRIPTION
**Pull request by CydiaLamiales**
## About The Pull Request
Ports [this PR from Sandstorm, NSFW warning](https://github.com/Sandstorm-Station/Sandstorm-Station-13/pull/324)
(That PR has an NSFW gif as its testing evidence)
Makes the point arrow be pixel-perfect rather than centered on a tile, and makes it rotate based on where it's being pointed at.

## Why It's Good For The Game
Allows people to more accurately point in a direction, and also allows people to see where the point came from. Plus it just looks nice.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/110184118/0216b02e-fc5f-430a-8313-b75402e7a561

</details>

## Changelog
:cl:SandPoot,CydiaLamiales
tweak: Pointing will make the arrow face it and you can also pixel-perfect point.
/:cl:

### CODE REVIEW

**Comment by Rukofamicom** [comment]
There's lizard dong on the other side of that link

**Comment by CydiaLamiales** [comment]
... yes, that's why I contemplated including it in tbe first place and why I put an NSFW warning over it

**Comment by Tsar-Salat** [comment]
Lizard dong pr 👍

**Comment by itsmeow** [comment]
imo this removes the charm of pointing. I've always liked that it centers on the tile

**Comment by CydiaLamiales** [comment]
Well, other people clearly like it, a lot
image

**Comment by CydiaLamiales** [comment]
The vote seems to be mostly in favor
image

**Comment by PowerfulBacon** [comment]
I like the pixel perfect nature of the pointing but I dislike the rotation

**Comment by EvilDragonfiend** [comment]
I think there should be a pref option if you want to see the pointer rotated or not

**Comment by CydiaLamiales** [comment]
There, I made it only rotate mid 'flight', it becomes downward pointing when it gets to the thing you're pointing at.

https://github.com/BeeStation/BeeStation-Hornet/assets/110184118/d6a86c25-f0d4-49ff-85e9-d90a68bbf698

**Comment by itsmeow** [comment]
That effect looks more like a bug than a feature tbh

**Comment by CydiaLamiales** [comment]
> That effect looks more like a bug than a feature tbh

Should I just remove the rotation completely?

**Comment by Tsar-Salat** [comment]
> That effect looks more like a bug than a feature tbh

Kinda agree.

We should either have the full rotation, or no rotation at all.

Because of how quickly the pointer moves, the directional aspect kinda looks like the pointer is bugging out.

Overall it's the same issue that we have with throwing stuff where some items look like they are teleporting rather than moving.

I'm not a maint, but I think the fill rotation deserves a TM. It could be the superior option and we are just not used to it.

**Comment by CydiaLamiales** [comment]
Yeah imma just remove the rotation.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Remove the rotation from the arrow at least once its landed and ping for merge

**Review by PowerfulBacon — APPROVED** [review]
as long as this doesnt start popping up on the profile, I am happy

**Pull request merged**
