### PR TITLE
BoxStation remapping pack - Science Edition (with some minor bonus improvements)

### PR DESCRIPTION
**Pull request by Tyranicranger4**
## About The Pull Request
See the dropdown under testing evidence for images.

Does what it says in the CL, which I'll add onto here.
___
> Made significant visual and structural changes to the Science Department and it's surrounding area on BoxStation

The most notable of which are: Expanded the hallway outside Robotics, nudged the West side of the department down one tile to accommodate the expansion, squished the firing range down into a xenoarch room (the practice lasers can be found in maintenance still), swapped the Toxins Storage Room, Research Director's Office, and Nanite Room around, and finally - the Nanite Room is now it's own separate room.

> Replaces all cameras in the Science Department on BoxStation with cameras on the RD camera network.

We're probably going to need to go through and replace most of the cameras on this map, but that's for another day.

> Replaces some absolutely terrible disposals piping in Maintenance near the service lathe room on BoxStation.
<details>
<summary> Image </summary>

Before:
image

After:
image

</details>

> Adds wiring under the grilles in the Science/Cargo department Security posts on BoxStation

More consistency with the rest of the map.

> Removed an invalid space credit item from the Exploration Dock on MetaStation 
> Adds reinforced walls to the Research Director's office on MetaStation 

These were both caused by me, so I'm fixing them here. *I swear the credit one worked when testing it before 😔*
This is all I've touched on Meta this PR.

## Why It's Good For The Game

BoxStation is a dated map, and it shows both visually and in it's design in a lot of cases. This PR seeks to make the Science Department look a little more interesting and make it's layout a bit more sane. The bonus changes are all minor, overall good tweaks.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

SDMM Screenshot:

Trollering

Ingame:
image

Testing screenshot. Shows camera display + rooms flooded with N20 using atmos to ensure that atmos was piped correctly:
***Vents and scrubbers have since been added to the Explo side room and the room connecting toxins launch to actual toxins.***

image

</details>

## Changelog
:cl:
tweak: Made significant visual and structural changes to the Science Department and it's surrounding area on BoxStation
tweak: Made somewhat minor - yet still notable changes to maintenance, station infrastructure (piping, wiring, disposals), and the exterior of the station near the Science Department on BoxStation
tweak: Replaces all cameras in the Science Department on BoxStation with cameras on the RD camera network.
tweak: Replaces some absolutely terrible disposals piping in Maintenance near the service lathe room on BoxStation.
tweak: Adds reinforced walls to the Research Director's office on MetaStation
tweak: Adds wiring under the grilles in the Science/Cargo department Security posts on BoxStation
fix: Replaced a couple of strangely off-color lights on BoxStation
fix: Adds an air alarm to the Medbay Lobby/Medbay Central areas on BoxStation
fix: Removed an invalid space credit item from the Exploration Dock on MetaStation.

/:cl:

### CODE REVIEW

**Comment by Tyranicranger4** [comment]
That seems like way too many line deletions. I wonder if I fucked up my mergetool hook when I had to fix my testing environment recently.

**Comment by Tyranicranger4** [comment]
Yes, so does the xenoarch console - just barely though.

**Review by spockye — COMMENTED** [review]
image

piping errors

image

only plating under windows!

**Comment by Tyranicranger4** [comment]
Drafting this until I find the time to make requested changes

**Comment by Tyranicranger4** [comment]
Lost interest in finalizing this.

**Comment by BriggsIDP** [comment]
😔

**Pull request closed without merging**
