### PR TITLE
FIXES HEARING FOR THE 17TH TIME

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

CALL PARENT ON ENTERED() AND EXITED() DAMN YOU

## Why It's Good For The Game

NO

## Changelog
:cl:
fix: fixed hearing AGAIN
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
I want this testmerged for a solid few days.

**Comment by jupyterkat** [comment]
> I want this testmerged for a solid few days.

do it I dare you

**Comment by Sinestia** [comment]
Why is this bit a problem? /tg/ doesn't do it.

**Comment by jupyterkat** [comment]
> Why is this bit a problem? /tg/ doesn't do it.

their mechs work different, they don't have sleepers or pet carriers

**Comment by Sinestia** [comment]
> 
> 
> > Why is this bit a problem? /tg/ doesn't do it.
> 
> their mechs work different, they don't have sleepers or pet carriers

Well, if you're right then that means lava, sleepers (which exist but arent mapped) and pet carriers are broken on /tg/ without anyone noticing. 

Which hey, is certainly possible. Definitely worth a TM, I was just curious and thought it was worth asking.

**Comment by francinum** [comment]
I'm going to give this one round to not explode. If it explodes, I'm going to actually go through with just cleaning up the mess so we can test some more important PRs.

**Comment by francinum** [comment]
Needs more than one round of testing, but the one round did in fact not catch fire.

**Comment by MCterra10** [comment]
@francinum merge this for god sake

**Review by utilbird — APPROVED** [review]
tfw still have merge perms.

Downstream(s) need this fix so stop dragging it out

**Pull request merged**
