### PR TITLE
Rare Ruko mining buff spotted!

### PR DESCRIPTION
**Pull request by Rukofamicom**
## About The Pull Request
* Ports the concussive gauntlets from TG!
  * Partially ports: https://github.com/tgstation/tgstation/pull/51044
  * Fully ports: https://github.com/tgstation/tgstation/pull/59988
  * Does not port the final tweak by @Fikou which causes the gauntlets to fling miners away from gibtonite because I disagree with its necessity. If miners can use sonic jackhammers without murdering themselves, they can use these gloves without murdering themselves. 

* Standaridizes the capacity values of PKA modkits! All modkits will now take up either 0%, 25% or 50% mod capacity so that an a clean 100% is always possible.
  * All mods that cost 30% now cost 25%. Not bothering to list them all
  * Lifesteal crystal now costs 0% down from 10%. Due to the rarity of the mod this will not cause issues
  * The antag modkit that enables pka in pressurized environments went from 35% to 50%. This is not a nerf as it appears to be and simply preserves the status quo - you can still only use this mod with two other mods. 
  * Trigger guard now costs 0% down from 20%. This means Golems (and by extension ashwalkers if supplied by golems) can use the trigger guard mod at no opportunity cost. 
  * Cleans up unnecessary minebot modkit code and removes the minebot exclusive cooldown mod in favor of allowing normal cooldown mods to be installed. Minebots were already compatible with all pka mods except the single cooldown mod, so this normalizes their PKA to match the cyborg and player PKA. 

* Basic damage mods have had their damage increase halved, this was overlooked in #8067 where everything on lavaland had its HP halved, and miners had all of their weapon damages halved.

* Cleans up AoE modkit code. A maximum of any two AoE modkits may be installed at any point in time, with no regard for the fact that turf AoE modkits don't have a stacking effect (this should be apparent to players)

* AoE damage modkits now do 40% damage per mod, up to a maximum of 80% of the weapon's original damage. This is a substantial increase from the inconsistent 20% or 25% depending on which AoE damage mod was being used, but has an upper limit to ensure the mods do not enable full damage within an AoE. 
  
* Mod0ifies the tumor shard so that it polls ghosts in the event the original player is not present to be revived. 

* Removes the slight RNG from gibtonite fuses to make the risk/reward from deactivating gibtonite more worthwhile. 

* Cleans up variable names to make more sense across the kinetic accelerator file in general. 

* Expands explorer webbing to be able to hold more mining tools. Namely it can now hold a shovel, their survival knife (instead of a kitchen knife), Emergency oxygen tank, kinetic accelerator, and plasma cutter. 

## Why It's Good For The Game

Concussive gauntlets are just an outright better reward than the diamond pickaxe, one of the final remaining rolls that could be potentially useless for the people scouring the planet for treasures. They function on par with a sonic jackhammer, but work even while your hands are empty or filled with something else (such as a kinetic crusher!). 

Modkit capacity has bothered me for a long time because achieving 100% capacity was almost never possible. The changes do present a slight uptick in maximum power for miners, but the adjustments have carefully worked around the traitor item and will have negligible impact on the game outside of the largely isolated PvE content on lavaland. This does also mean miners have been slightly buffed against blobs, however. 

And finally, there was a recent complaint (and others in the past) about lavaland elites that don't want to stick around and be subservient to the player which fought them. By polling ghosts for a candidate after the fight we maximize the chances for a miner to receive a new companion. 

Most of the other changes were just motivated by cleaning up code, and I noticed the damage mod seemed abnormally high and investigated. Fixing that damage value is critical to the overall buffs I have provided to the PKA. 

## Testing Photographs and Procedure

Mod capacity working as expected
image

Doesn't work on station:
image
image

Works fine on lavaland
dreamseeker_rH14ctNAM4

Drone modding is good:
image

## Changelog
:cl: Rukofamicom, Fikou
add: Concussive gauntlets have arrived! Shaft miners will find that the diamond pickaxe can no longer be found in tendril chests, and instead they may find concussive gauntlets!
tweak: Tumor shards will now poll ghosts for control of lavaland elites if the original player has left the body. There is still no guarantee of having a new pet if alternatives are not available. 
tweak: Gibtonite fuses are no longer variable so that miners with good timing are more consistently rewarded for risking life and limb to try and defuse it. 
balance: PKA modkits have been standardized to cost either 0%, 25%, or 50% capacity. This means it is now possible to utilize 100% of the weapon's potential and up to four impactful mods may now be installed!
balance: PKA modkits that do AoE damage have had their power doubled, but still have an upper limit of 80% normal power. It is now far more practical to install AoE damage mods, but will still weaken the power of the weapon overall in exchange for versatility. 
balance: Damage increasing modkits have had their power halved. This was overlooked during the major lavaland rebalance that halved the HP of all fauna and halved the damage of mining tools. Damage modkits are supposed to increase damage by 25% of base power, not 50%.
tweak: All modkits are now compatible with mine bots, and the special cooldown reduction mod has been removed since the normal cooldown mod works on them now. Mine bots have the same capacity for mods as a PKA.
tweak: Explorer webbing can now hold additional mining tools and items: shovel, survival knife, emergency oxygen tank, PKA and plasma cutters. It can no longer hold kitchen knives. 
code: Cleaned up some variable names and unnecessary code within the kinetic_accelerator file. 
/:cl:

### CODE REVIEW

**Comment by Rukofamicom** [comment]
The balance implications of this PR are negligible, but it didn't feel right not to include the tag.

**Comment by Tsar-Salat** [comment]
the rare ruko port

**Comment by Rukofamicom** [comment]
If it doesn't I'll be more than a little disappointed that those turfs aren't part of `ismineralturf()`

**Comment by Rukofamicom** [comment]
Yep works on both.

**Comment by Rukofamicom** [comment]
Alright, this should be considered in its final state now.

**Review by PowerfulBacon — APPROVED** [review]
Seems fine by my mobile review

**Pull request merged**
