### PR TITLE
2 pets for the best jobs on the station

### PR DESCRIPTION
**Pull request by Pill-U**
## About The Pull Request
Ports two pets, Silent Meow and Honkers from hippiestation, ports a feral kitten simplemob, and makes runtime emagable.
https://github.com/HippieStation/HippieStation/pull/6675
https://github.com/HippieStation/HippieStation/pull/6754

## Why It's Good For The Game
You have to ask? Pets and more funny abilities for the emag are always good!
Also there was a thread on the forums about how a clown pet should be added, so atleast one person likes this pr.

## Changelog
:cl:
add: clown cat and mime cat
tweak: clowncat has a 10% chance to puke bananas instead of 5%
add: feral cat (to make the mime cat emagable)
add: runtime is now emagable, doing so makes it explode
add: clown and mime cat to all maps
soundadd: scream_cat.ogg
soundadd: clownCatHonk(1-3).ogg
soundadd: mimeCatInitialScream.ogg
soundadd: mimeCatScream(1-2).ogg
imageadd: clown and mime cat sprites
/:cl:

~~I'd appreciate it if someone could explain to me why spawning 2 mobs on some maps apparently deletes 800k lines of code and or help me fix it.~~ - fixed

### CODE REVIEW

**Comment by Flakkyboo** [comment]
−833,430 lines OH

**Comment by PowerfulBacon** [comment]
Use map merge
or
Go to https://fastdmm2.ss13.io/
open your local codebase
press export
export the map to the location
(fastdmm auto map merge)

**Comment by Crossedfall** [comment]
This is not a good start given our policy on Hippie ports

https://github.com/BeeStation/BeeStation-Hornet/blob/master/.github/CONTRIBUTING.md#hippiestation

**Comment by ghost** [comment]
image

**Comment by Dingo-Dongler** [comment]
Removes the game
Good pr, I was sick of it anyways

**Comment by Pill-U** [comment]
image
Well thats more reasonable

**Comment by zeskorion** [comment]
urge... to close... hippie port.... rising.....

**Comment by yorii** [comment]
why would runtime be emaggable? I thought hippie just made the mime's cat emaggable since it's invisible?

**Comment by TeomanTheGreat** [comment]
The joke is they are robot cats.

**Comment by ike709** [comment]
Hippie port + bad code = close

**Pull request closed without merging**
