### PR TITLE
Keeps felinids and adds monkeymen

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
The non-grudge coding PR for adding monkeymen. This keeps the popular felinid race whilst adding a new humanoid monkey one. 

This race has two unique features:
- You have to wear a special helmet to talk Galactic Common or use complex machinery. If you wear a skinsuit or EVA helmet you'll be unable to do either. 
- They heal when they eat bananas.

## Why It's Good For The Game
More race additions means greater player choice. Also deletes the unnecessary felinid removal from the original PR that should have never been attempted to be tied to it. If you want them gone then make a proper vote. 

## Changelog
:cl: Zeskorion, thatguythere03
add: monkeymen. Monkeymen must wear a special helmet, or they are unable to speak common, and cannot use [some] complex machinery. When not wearing the helmet, they are able to yell very loudly.
tweak: removes tail_human preferences. they're unecessary and get in the way of having multiple tail styles for different species
imageadd: monkeyman sprites and helmet sprites by the amazing thatguythere03
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
Cat bad momki good

**Comment by TeomanTheGreat** [comment]
@zeskorion bruh

**Comment by AtlasRules** [comment]
imagine keeping in f*linids

**Comment by ItsTisme** [comment]
I think this is better overall imo. Cant wait to get lynched for this

**Comment by zeskorion** [comment]
Making prs modifying racial features or availability without approval from a maintainer violates contribution guidelines

Also you took my code.

**Comment by AtlasRules** [comment]
LOL

**Comment by VictorVow** [comment]
@zeskorion your code is attributed within the commit and changelog. All the code is already approved - after all, it's all yours. 

@Crossedfall @ike709 @qwertyquerty @PowerfulBacon one of you please give approval for this, since Zesk is trying to go all dictator mode and only have [his original PR](https://github.com/BeeStation/BeeStation-Hornet/pull/2490) which additionally removes felinids.

**Comment by FargothUr** [comment]
mfw filthy felinid erper can't handle their uwu character being obsoleted in a game called SS13 and not "OC Simulator" 

https://www.youtube.com/watch?v=p5CjmHLUQQI

**Comment by BloodyHuggable** [comment]
Please i can only bruh hard i beg of you

**Comment by ike709** [comment]
@Victor239 It'll be resolved by player vote. If this PR wins it'll be reopened at the other one closed.

Both of you keep the squabbling off of github.

**Comment by zeskorion** [comment]
> @Victor239 It'll be resolved by player vote. If this PR wins it'll be reopened at the other one closed.
> 
> Both of you keep the squabbling off of github.

you'd need me to update the config in my pr, this one is outta date

**Comment by CommandBlockGal** [comment]
WHAT CAN I SAY EXCEPT DELETE THIS

**Comment by sircope** [comment]
i don't know, seems to me like you took his code

**Comment by Isy232** [comment]
Felinid Vote Fail

Felinids shall remain so we can continue to genocide and oppress them.

**Comment by ike709** [comment]
This PR won the vote but I'm not going to reopen it unless @zeskorion or @Victor239 commit to maintaining the race regardless of the vote outcome.

**Comment by zeskorion** [comment]
> This PR won the vote but I'm not going to reopen it unless @zeskorion or @Victor239 commit to maintaining the race regardless of the vote outcome.

The code in this pr is incomplete anyways,  i'll update my branch and push some of the todo changes later. Some.

**Pull request closed without merging**
