### PR TITLE
Ports a pile of greps from TG

### PR DESCRIPTION
**Pull request by Zonespace27**
## About The Pull Request
Ports:
https://github.com/tgstation/tgstation/pull/67374
https://github.com/tgstation/tgstation/pull/67447
https://github.com/tgstation/tgstation/pull/66672
https://github.com/tgstation/tgstation/pull/64599
https://github.com/tgstation/tgstation/pull/67173
https://github.com/tgstation/tgstation/pull/69448

There are more greps in /tg/ that'd be good here but those are to be atomized out to other PRs
Please TM this first, I cannot guarantee my find & replace didn't fuck up a map

## Why It's Good For The Game
Not making simple mistakes is good.

## Testing Photographs and Procedure

<details>
<summary>How I did it</summary>

No regexes were used due to the issues being spread about maps in no coherent manner, VSC's find&replace function was used instead.

</details>

## Changelog
:cl:
code: Added a variety of new greps to the Github and corrected map issues that failed the greps
/:cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
You still need a changelog, even if the changes aren't player facing.

**Comment by Zonespace27** [comment]
> You still need a changelog, even if the changes aren't player facing.
> 
> Testing procedures should include how you made the changes.

Done

**Comment by Crossedfall** [comment]
Cycling to get a map diff

**Comment by Zonespace27** [comment]
I'll resolve conflicts on this prior to a TM

**Review by PowerfulBacon — DISMISSED** [review]
This PR needs merge priority due to map changes

**Comment by PowerfulBacon** [comment]
@Zonespace27 checks fail

**Review by itsmeow — APPROVED** [review]
Basically impossible to verify this didn't introduce any bugs, but if checks pass it's fine and the greps themselves look fine.

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
