### PR TITLE
Remaps a large portion of the Science department on MetaStation, notably moving xenobio into the station

### PR DESCRIPTION
**Pull request by Tyranicranger4**
## About The Pull Request
Modifies a large amount of the Science department.
This started as me trying to move xenobio into the station and toxins out to where xenobio used to be.
From there spawned a bunch of other smaller changes to facilitate the move and to make things look a bit more 'modern' and nicer looking while hopefully still keeping the feel of MetaStation.

For a full list of changes see below.

Xenobio is notorious for being a job heavily isolated from the rest of the station, this aims to bring them closer to and put them in line of sight of the rest of Science. (I'm fully aware that the core issue here is a design one, not a mapping one. But having them isolated in their small space fortress compounds the issue even further.) The actual mapping changes outside of moving it aim to give it a slightly more 'modern' and unique feel.

> Remaps Toxins and the Toxins storage room, moving them from the middle of the Science Department towards the edge where Xenobio used to be (MetaStation).

This change isn't particularly 'good' for the game, nor is it bad for it. It however does make room for the aforementioned xenobio change, which I *do* believe to be good for the game. (I do think it looks a bit nicer though.)

> tweak: Remaps the 'science maintenance' hallway, moving it further to the right, adding additional decals and expanding it slightly (MetaStation).
tweak: The toxins 'launch' room is now part of the 'science maintenance' area instead of the 'mixing' area. It also been visually changed slightly, although it's function remains the same. (MetaStation)
tweak: The toxins 'launch' room, the toxins 'test area', the exploration dock and the 'starboard aft' solars have been moved down and to the right slightly. (MetaStation)
tweak: Remaps the maintenance area surrounding parts of the Science Department (MetaStation)
tweak: Remaps wiring/piping/disposals throughout the Science Department. (MetaStation)
tweak: Makes the experimentor room slightly smaller on the bottom (MetaStation)
tweak: Makes various visual changes to parts of the Science Department, mostly consists of replacing floor tiles/decals. (MetaStation)

Done to accommodate the Xenobio/Toxins changes. Visual changes were done to (yet again) give it a slightly more 'modern' feel, and to make things look a bit prettier.

> tweak: Remaps the science exploration area (MetaStation)

Done at the request of pigeon. The current exploration room is pretty bad if I'm being honest, this is a bit less so.

> tweak: Remaps the R&D server room, moving it next to the Research Director's office where Toxins storage used to be. (MetaStation)
tweak: The Research Director's office now directly connects to the R&D server room. Additionally the floor tiles in the RD's office now use decals. (MetaStation)

Creates a new potential area of attack for people looking to break into the RDs office. Moving the server room was necessary to make room for Xenobio. The floor tiles are now white with decals instead of the 'cafeteria tiles' as I believe this looks slightly cleaner.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
Overview

Guh
GuhArea

RD's office/server room.
image

Exploration
image
Xenobio
image
image
image

Toxins
imageimage

Sci maint hallway
image

Toxins launch room
image

</details>

## Changelog
:cl:
tweak: Remaps Xenobio, moving it from the edge of the station towards the middle of the Science Department (MetaStation).
tweak: Remaps Toxins and the Toxins storage room, moving them from the middle of the Science Department towards the edge where Xenobio used to be (MetaStation).
tweak: Remaps the 'science maintenance' hallway, moving it further to the right, adding additional decals and expanding it slightly (MetaStation).
tweak: The toxins 'launch' room is now part of the 'science maintenance' area instead of the 'mixing' area. It also been visually changed slightly, although it's function remains the same. (MetaStation)
tweak: The toxins 'launch' room, the toxins 'test area', the exploration dock and the 'starboard aft' solars have been moved down and to the right slightly. (MetaStation)
tweak: Remaps the maintenance area surrounding parts of the Science Department (MetaStation)
tweak: Remaps the science exploration area (MetaStation)
tweak: Remaps wiring/piping/disposals throughout the Science Department. (MetaStation)
tweak: Makes the experimentor room slightly smaller on the bottom (MetaStation)
tweak: Remaps the R&D server room, moving it next to the Research Director's office where Toxins storage used to be. (MetaStation)
tweak: Makes various visual changes to parts of the Science Department, mostly consists of replacing floor tiles/decals. (MetaStation)
tweak: The Research Director's office now directly connects to the R&D server room. Additionally the floor tiles in the RD's office now use decals. (MetaStation)
/:cl:

### CODE REVIEW

**Comment by PestoVerde322** [comment]
immagine

The APC might be an issue to access to.

immagine

Floating light switch and glass-wall

immagine

may clear those wall-doors?

Other than that everything else seems fine.

**Review by PestoVerde322 — COMMENTED** [review]
See comment above, have to comment due to git screaming at me to leave a review here.

**Comment by Tyranicranger4** [comment]
> The APC might be an issue to access to.

It's accessible, although it's probably still a bad spot tbh.
New location (and new wiring)
image

> Floating light switch and glass-wall

Fixed

> may clear those wall-doors?

image

**Comment by Tyranicranger4** [comment]
Also changed the exploration dock to this.
(Yes I like Fland's use of decals, how can you tell?)
image

**Review by PestoVerde322 — APPROVED** [review]
Doublechecked, everything seems all good, Approved.

**Pull request merged**
