### PR TITLE
Adds Tsukihime inspired outfits

### PR DESCRIPTION
**Pull request by Patternseeker**
## About The Pull Request

Adds two new jumpskirts to hacked ClothesMate and one to hacked ChapDrobe.
Sprites by me.

**_Insane type moon reference._**

## Why It's Good For The Game

More stuff to wear. ~~You can now annoy the fucking shit out of people as Neco Arc. Burunyaaaaaa~~

## Testing Photographs and Procedure

<details>
<summary>Screenshots</summary>

iconic
display
ARC
ezgif-3-1a45c636d0
for reference

</details>

## Changelog
:cl:
add: Added "vampire hunter suit", available in hacked ChapDrobe.
add: Added "cardigan", available in hacked ClothesMate.
add: Added "silk shirt", available in hacked ClothesMate.
/:cl:

### CODE REVIEW

**Comment by Pirill** [comment]
Yes. Absolutely. Merge immediately!

**Comment by williamcll** [comment]
Now give the captain Arthur's outfit.

**Comment by ItsTisme** [comment]
I smell new donator items

**Comment by Patternseeker** [comment]
> I smell new donator items

Never intended for these to be donator only.

**Comment by zeskorion** [comment]
🙄

**Comment by Crossedfall** [comment]
I appreciate the effort and the style, but this is way too much of a meme to actually bring in.

**Pull request closed without merging**
