### PR TITLE
Mask of Madness replaces Blindness Curse

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Ports the mask of madness from TG, replacing the blind curse for the path of ash.

 [tgstation/tgstation#54252](https://github.com/tgstation/tgstation/pull/54252)

Mask of Madness deals stamina damage to all humans around the heretic. Becomes cursed to you if you are not a heretic. 

## Why It's Good For The Game

A unique idea. Is it good? We will see...

## Changelog
:cl:
add: Mask Of Madness, replacing blind curse for path of ash heretics.
/:cl:

### CODE REVIEW

**Comment by park66665** [comment]
1. Fix you branches, revert ab6226cca280b43442d2a10f917bc78a3b6035b2 or do something else; like merging everything to #2827
2. Link to the original tg PR; is it tgstation/tgstation#54252? Or are you just taking inspirations from it?

**Comment by eeSPee** [comment]
> 1. Fix you branches, revert [ab6226c](https://github.com/BeeStation/BeeStation-Hornet/commit/ab6226cca280b43442d2a10f917bc78a3b6035b2) or do something else; like merging everything to #2827
> 2. Link to the original tg PR; is it [tgstation/tgstation#54252](https://github.com/tgstation/tgstation/pull/54252)? Or are you just taking inspirations from it?

Done.

I will slowly try to update the code on bee to match the one on tg. Then I will revisit the big heretics revision.

**Comment by park66665** [comment]
> Done.

Sadly, this PR still is not at a reviewable state. This PR is about Mask of Madness. Yet, it contains a large portion of #3344. You should deal with it.

> I will slowly try to update the code on bee to match the one on tg. Then I will revisit the big heretics revision.

It'll be a difficult path of resolving multiple conflicts as master slowly drifts away from the base of #2827. I wouldn't recommend it.

**Comment by eeSPee** [comment]
> Sadly, this PR still is not at a reviewable state. This PR is about Mask of Madness. Yet, it contains a large portion of #3344. You should deal with it.

Shall I close these series of PRs?

**Comment by park66665** [comment]
> Shall I close these series of PRs?

All in all, no matter what you do, each of those three PRs should have only the changes that are described by said PRs. If #3345 and #3346 depend on the code changes from #3344, you have to close two depending PRs, wait for #3344 to be merged, and open PRs correspondingly. You also can combine them into a single PR, preferably to #3344. (remind you, you can merge your own branches  one another)

If three PRs can be reasonably atomized from each other, you can use not-very-common git commands like revert, force-push, and other dangerous commands to fix the branches, or abandon the branches and open new branches (and corresponding PRs) with *only* the changes for each PR. It also seems that #3344 isn't to be closed.

**Comment by eeSPee** [comment]
It just occured to me that this causes conflicts with #3344. It was supposed to be a continuation of #3344, but it doesn't display that way.

**Pull request closed without merging**
