### PR TITLE
Antag Tokens in DB

### PR DESCRIPTION
**Pull request by qwertyquerty**
So we don't have to use notes anymore. Now stored in db, and editable through player panel. I might even make it so that players can redeem the tokens themselves instead of having an admin do it in the future.

### CODE REVIEW

**Comment by CthulhuOnIce** [comment]
You pushed a merge conflict

**Comment by qwertyquerty** [comment]
Oh did I mention this also revamps the player panel because I'm pulling a cthulhu and shoving multiple things into a PR

**Comment by CthulhuOnIce** [comment]
Or not?

**Comment by CthulhuOnIce** [comment]
Oh you removed them lol

**Comment by qwertyquerty** [comment]
Look at the commits that show up on the timeline nerd

**Comment by qwertyquerty** [comment]
image

**Comment by CthulhuOnIce** [comment]
> revamps player panel
> Popup instead of browse()
> Honk

JK good job keyboard man

**Comment by qwertyquerty** [comment]
Come on get with the times man

**Comment by qwertyquerty** [comment]
I changed WAY more than that

**Comment by qwertyquerty** [comment]
If you would actually look at it nerd

**Comment by qwertyquerty** [comment]
Had to remove all the icky [] and all the | and I sectioned things better, and I separated things better nerd

**Comment by CthulhuOnIce** [comment]
I c

**Comment by CthulhuOnIce** [comment]
I'll merge this tomorrow if the checks pass

**Comment by qwertyquerty** [comment]
Arguing in PRS is my favorite way to pass time

**Comment by qwertyquerty** [comment]
Why does travis always be so slow

**Comment by qwertyquerty** [comment]
tf is an mdme 
image

**Comment by qwertyquerty** [comment]
image
Bruh moment

**Comment by qwertyquerty** [comment]
How did this even get in my PR I'm so confused

**Comment by qwertyquerty** [comment]
just gonna close this and try again, I don't remember mergin with master but ok

**Pull request closed without merging**
