### PR TITLE
Lizardpeople can wear underwear again.

### LINKED ISSUE #7612: The character setup preview doesn't work properly for lizards.
Hello.

I'm not a Beestation regular, and i've never even connected to the server before today, but i noticed this issue when i was setting up my character, and i felt like i needed to report it.

I'm using BYOND 514.1585, if that matters.

Apologies if this has been reported before, i couldn't seem to find any relevant issues when i searched.

## Round ID & Round Date:

40236, 9/3/2022

## Testmerges:

#6718: '[New Science Sub-Department] Xenoarchaeology - Xenoartifact Research. ' by DrDuckedGoose at commit 73484a97c5](https://www.github.com/beestation/beestation-hornet/pull/6718)

## Reproduction:

.1: Select a lizard in the species menu.
.2: Notice how the underwear doesn't show up, and it uses the male body sprite, regardless of selected gender.

Screenshot_14

I changed the species around to human, moth, ethereal, and IPC, and the underwear and gender specific body types showed up on all of them. It just seems to be lizards that are affected.

I don't know if it affects your appearance once you're actually in-game, i never left the lobby screen.

### PR DESCRIPTION
**Pull request by sergeirocks100**
## About The Pull Request

Crossedfall approval:
Screenshot_18

This takes the NO_UNDERWEAR flag off of lizards that #5611, for some reason, added.

It also readds the separate male and female lizard chest sprites. I'm pretty sure they were removed inadvertently at some point, since the lizard body markings still have separate male and female sprites.

Closes #7612.

## Why It's Good For The Game

There's pretty much no reason that lizardpeople can't wear underwear, when every other species can.

It also brings Bee in line with other codebases, such as /tg/ and Yog, in this regard.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

Screenshot_19
Screenshot_16

</details>

## Changelog
:cl:
add: Lizardpeople can wear underwear again.
imageadd: The separate male and female chest sprites for lizardpeople have been readded.
/:cl:

### CODE REVIEW

**Comment by sergeirocks100** [comment]
> How does this work with digigrade legs?

From what i can tell, it works pretty much the same as it does on /tg/.

Namely, socks don't show up on digitigrade legs. They don't stop you from wearing underwear or shirts, though.

**Comment by hotimep** [comment]
erp nerf

**Review by itsmeow — DISMISSED** [review]

**Comment by Hardly3D** [comment]
It may be worth noting that some of the underwear (especially boxers) will look off for lizards who have digitigrade legs, here's an example of what I mean:

image

**Comment by sergeirocks100** [comment]
> It may be worth noting that some of the underwear (especially boxers) will look off for lizards who have digitigrade legs, here's an example of what I mean:
> 
> image

I don't really know how i could fix this, aside from trying to draw separate digitigrade variants for underwear

**Comment by PowerfulBacon** [comment]
Is it possible to disable underwear for digigrade legs only?

**Comment by sergeirocks100** [comment]
> Is it possible to disable underwear for digigrade legs only?

I could try to add in a variable that stops certain articles of underwear (like underwear with long legs) from showing on your character if you have digitigrade legs selected, but i'm very DM illiterate, so i can't promise anything.

**Comment by sergeirocks100** [comment]
I couldn't figure out how to do what i wanted (My attempts either didn't compile, or failed to stop digitigrade lizards from wearing underwear that they weren't supposed to be able to), so i just decided to do what PowerfulBacon suggested.

**Comment by dwasint** [comment]
> Is it possible to disable underwear for digigrade legs only?

yes it is, both options are available to do but i'd recommend just looking at a server with digi variants and just nabbing those

**Review by itsmeow — APPROVED** [review]

**Pull request merged**
