### PR TITLE
Turns off mood on Golden

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request

This turns off mood

## Why It's Good For The Game

Mood is a poorly made system. It is *designed* to discourage greytide and encourage roleplay, but it's so easily powergameable and so negligable it does nothing to discourage greytide, and the way mood works largely detracts from roleplay as well, making your character's personality a slave to the game, instead of to the whims of the player

## Changelog
:cl:
config: disables mood
/:cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
Your config changes only apply to Golden. If you want it to also apply to Sage make sure you add those changes. I updated the title to reflect the current changes.

**Comment by qwertyquerty** [comment]
Since this is a rather substantial change, I'm going to run a player poll on golden for it.

**Comment by CthulhuOnIce** [comment]
@qwertyquerty results on the player poll?

**Comment by qwertyquerty** [comment]
Screenshot_20200216-174717
The beeple would rather it be reworked

**Pull request closed without merging**
