### PR TITLE
Some more BoxStation fixse

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request

There were some mapping errors that got left behind unnoticed and I fixed them. I also added some missing stuff , like missing mulebot beacons and also reorganized some rooms. For a full list check the changelog

## Why It's Good For The Game

Because it fixes stuff that aren't working properly

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: ClownMoff
add: Adds MuleBots destination for medbay and bar
add: BoxStation: Added new decals in medbay
del: BoxStation: Deleted an extra crew sensors computer
tweak: BoxStation: Put the correct beacons in kitchen and botany
tweak: BoxStation: Adjusts the coldroom MuleBot dock a little 
tweak: BoxStation: Changed a wall stuck inside a desk for a floor
tweak: BoxStation:  Changes the medical records laptop for a computer to replace the duplicate crew sensors computer
tweak: BoxStation: Puts the chemistry fridge for medbay staff in an place that can be accessed inside chemistry
del: BoxStation: Deletes the floating intercom in cryotherapy room
tweak: BoxStation: Moves a NanoMed in the treatment center to a better location
tweak: BoxStation: Organizes the treatment center in medbay around for a better layout.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Please fill out the body text of the PR adequately in order to get considered for review.

**Comment by ClownMoff** [comment]
Done?

**Comment by PowerfulBacon** [comment]
Testing evidence still needs to have something, if there's something important then show it working otherwise show a screenshot of the changes

**Comment by ClownMoff** [comment]
imma close this and open another one

**Pull request closed without merging**
