### PR TITLE
Removes the absolutely excessive use of yellow decals from kilostation

### PR DESCRIPTION
**Pull request by Rukofamicom**
## About The Pull Request

Removes the vast majority of yellow decals from Kilo

## Why It's Good For The Game

Kilo can actually shine as a great small map now that it isn't 50% piss colored. 

## Testing Photographs and Procedure

Before and After example:
https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExbGQybm15M2pxcXF4bzg5ZnVldDNwZXg3dWdtMWJpdDJuNXNheXdicSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/cWTfShrcFVZxn4R3nP/giphy.gif

## Changelog
:cl: Floria, Ruko
del: Removed MANY decals from kilostation
/:cl:

### CODE REVIEW

**Comment by ClownMoff** [comment]
Shit PR leave KinoStation alone 🔑🔑🔑🔑🔑🔑🔑🔑🔑🔑🔑🔑🔑🔑🔑🔑

**Comment by Geatish** [comment]
You literally just removed every decal???? I can agree that there was maybe a lot of decals, but even those that made sense are gone. Very anti-SOVL, do not touch kilo. 🔑🔑

**Comment by ClownMoff** [comment]
imagen

**Comment by Wueue** [comment]
i dont like this pr at all.
it removes a lot of the charme Kilo has as a station and makes it looks bland.
not a fan

**Comment by MarkusLarsson421** [comment]
Space OSHA would not approve.

While I agree that it is exessively, I think it adds to the charm of it being a unique visually distinct map. You know it's Kilo you are looking at and not some other map. Unless there is some other factor in play, such as performance, I don't think this is a good idea.

**Comment by Nakalon** [comment]
I don't see the problem with this PR, kilo can go fuck itself

**Comment by Rukofamicom** [comment]
Alright, lets try that again but this time with what is currently up.

**Comment by Rukofamicom** [comment]
We have oopsied, but the current version is still an accurate representation of what we want the end goal to look like now

**Comment by Geatish** [comment]
Yea this is way better, though i think the squares around the holoprojectors should remain

**Review by PestoVerde322 — APPROVED** [review]

**Comment by MarkusLarsson421** [comment]
It does feel a bit bland. I'd rather see the netural corner tiles on top of other coloured tiles gone and have the full neutral hallway tiles in the centre remain. Much like other maps.

**Comment by Rukofamicom** [comment]
We'll that didn't go right.
Do not merge right now.

These conflict resolution tools fuck me every time because I cannot get conflicts to show on my machine

**Comment by Rukofamicom** [comment]
How the fuck did this cause ten commits

**Comment by Rukofamicom** [comment]
Yeah, I'm not fixing this. 

I hate mapping too much.

**Pull request closed without merging**
