### PR TITLE
Dynamic gamemode [READY BUT CHECK WITH CAUTION]

### PR DESCRIPTION
**Pull request by Toxici11i**
## About The Pull Request
Adds the dynamic gamemode from /tg/ and /vg/

## Why It's Good For The Game
half of the community wants this, basically replaces every other gamemode

## Changelog
:cl:
add: Added dynamic gamemode
server: Messes with admin.dm and roundend.dm so make sure to port any recent changes in
/:cl:

### CODE REVIEW

**Comment by Toxici11i** [comment]
it... pushed metacoin why

**Comment by Toxici11i** [comment]
probably ready, merge at own peril

**Comment by Toxici11i** [comment]
it ran my side just fine but then again it tried to revert metacoin so

**Comment by ike709** [comment]
Definitely warrants a testmerge first.

**Comment by jlsnow301** [comment]
Metacoin change trolls me every time

**Comment by ike709** [comment]
That's because you need to rebase your master branch @jlsnow301

**Comment by qwertyquerty** [comment]
I was about to testmerge this but then I realized you didn't actually make any way for us to open the admin panel. Make sure that you got everything from https://github.com/tgstation/tgstation/pull/44639

**Comment by Toxici11i** [comment]
/tg/ did some magic autism, ill add something equivalent to ours (fuck /tg/ they changed their admin panel and added shit)

**Comment by Toxici11i** [comment]
by that I mean only take the section thats been changed and probably undo some of /tg/s perm changes

**Comment by Toxici11i** [comment]
ok should be admeme panel now, notify me if it breaks since this was rushed

**Comment by Crossedfall** [comment]
> 
> 
> ok should be admeme panel now, notify me if it breaks since this was rushed

What's the purpose of rushing it? Do some proper testing and notify us when it's ready for review and a test merge.

**Comment by ike709** [comment]
>Toxic
>Proper testing

Nice meme @crossedfall

**Comment by Crossedfall** [comment]
> 
> 
> > Toxic
> > Proper testing
> 
> Nice meme @crossedfall

No better time than now to break bad habits, right? (:

**Comment by Toxici11i** [comment]
Literally I do not have the time to test fully yet

**Comment by Toxici11i** [comment]
Also sent via phone

**Comment by Toxici11i** [comment]
ok at desktop now, time to test

**Comment by Toxici11i** [comment]
http://prntscr.com/p1jnlh works

**Comment by Crossedfall** [comment]
You've tested all the other functions as well? Also please update your description. It doesn't follow our current formatting guidelines for CLs and tells us nothing about this PR.

**Comment by Toxici11i** [comment]
yes I have

**Comment by qwertyquerty** [comment]
During the testmerge, threat level 85

```
[23:15:03] Runtime in dynamic_rulesets_roundstart.dm, line 207: Division by zero
[23:15:03] Runtime in dynamic_rulesets_roundstart.dm, line 265: Division by zero
[23:15:19] Runtime in dynamic_rulesets_roundstart.dm, line 397: Cannot read null.objectives
[23:15:19] Runtime in dynamic_rulesets_roundstart.dm, line 403: Cannot execute null.head revolutionaries().
[23:15:21] Runtime in dynamic_rulesets_roundstart.dm, line 397: Cannot read null.objectives
[23:15:21] Runtime in dynamic_rulesets_roundstart.dm, line 403: Cannot execute null.head revolutionaries().
[23:15:23] Runtime in dynamic_rulesets_roundstart.dm, line 397: Cannot read null.objectives
[23:15:23] Runtime in dynamic_rulesets_roundstart.dm, line 403: Cannot execute null.head revolutionaries().
[23:15:25] Runtime in dynamic_rulesets_roundstart.dm, line 397: Cannot read null.objectives
[23:15:25] Runtime in dynamic_rulesets_roundstart.dm, line 403: Cannot execute null.head revolutionaries().
[23:15:27] Runtime in dynamic_rulesets_roundstart.dm, line 397: Cannot read null.objectives
[23:15:27] Runtime in dynamic_rulesets_roundstart.dm, line 403: Cannot execute null.head revolutionaries().
[23:15:30] Runtime in dynamic_rulesets_roundstart.dm, line 397: Cannot read null.objectives
[23:15:30] Runtime in dynamic_rulesets_roundstart.dm, line 403: Cannot execute null.head revolutionaries().
[23:15:32] Runtime in dynamic_rulesets_roundstart.dm, line 397: Cannot read null.objectives
[23:15:32] Runtime in dynamic_rulesets_roundstart.dm, line 403: Cannot execute null.head revolutionaries().
[23:15:34] Runtime in dynamic_rulesets_roundstart.dm, line 397: Cannot read null.objectives
[23:15:34] Runtime in dynamic_rulesets_roundstart.dm, line 403: Cannot execute null.head revolutionaries().
...
...
```

**Comment by qwertyquerty** [comment]
During the testmerge ^

**Comment by Toxici11i** [comment]
checking this out rn

**Comment by Toxici11i** [comment]
Maybe work? recopied and pasted from /tg/s master branch for roundstart again, let me actually commit so there were differences

**Comment by qwertyquerty** [comment]
Your commit didn't change anything

**Comment by qwertyquerty** [comment]
I'm gonna do one more testmerge then this is merged

**Pull request merged**
