### PR TITLE
Updated bishop outfit sprites, added bishop cloak and black bishop outfit

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
New sprites hot off the press from the lovely @Naevii. Firstly the existing bishop suit and mitre from chaplain vendor has brand new sprites:
 
As well as a matching cloak! Cloak can be obtained by hacking the chaplain vendor. 

In addition a black version of the same full outfit is now available in the Beecoin shop as chaplain restricted items.

## Why It's Good For The Game
Better sprites and more variety.

## Changelog
:cl:Naevi, Victor239
add: Adds black bishop suit,mitre and cloak to beecoin shop
add: Adds bishop cloak to hacked chaplain vendor
tweak: Updates bishop suit and mitre
/:cl:

### CODE REVIEW

**Comment by Naevii** [comment]
capes
MediBangPaintPro_l0XtT3jEbf
old one on left side, new one to the right side and on middle.
MediBangPaintPro_AnE2Qo7gFK

**Comment by OceanFish1** [comment]
Finally some epic chaplain's stuff

**Comment by Crossedfall** [comment]
Protip. You can properly attribute an artist/author by adding them as a co-author on your commit(s).

https://docs.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors

Also, you really should credit them on the CL line as well so they get attributed in the historic change log.

**Comment by VictorVow** [comment]
Thanks, never knew that

**Comment by Crossedfall** [comment]
@SomeAngryMiner sprites review pls

**Comment by Naevii** [comment]
https://discord.com/channels/427337870844362753/586014397177004074/800711423939838002

**Comment by heepox** [comment]
hades pope of sin rework time maybe soon i dunno but he was funny

**Review by francinum — APPROVED** [review]

**Review by ike709 — APPROVED** [review]

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
