### PR TITLE
Adds service and cargo techfabs instead of protolathes on Corg

### LINKED ISSUE #4628: Corgstation cargo and service have protolathes instead of techfabs
## Reproduction:
Can't print an express console board with it or any other cargo circuits cause its not a hybrid techfab

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Title.

closes #4628

## Why It's Good For The Game

Being unable to print everything service/cargo needs is not good. Example is the express supply console.

## Changelog
:cl:
tweak: Cargo and service now have techfabs instead of protolathes on corg
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
Title is misleading. You should say it is mapchange for corg.

**Comment by BrumalLake** [comment]
closes https://github.com/BeeStation/BeeStation-Hornet/issues/4628

**Comment by PowerfulBacon** [comment]
wait what they are 2 different things?

**Comment by KubeRoot** [comment]
> wait what they are 2 different things?

Techfab is protolathe+circuit imprinter, letting you print both items and boards

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
