### PR TITLE
Adds gas ignitor setups for Box/Delta Xenobio

### PR DESCRIPTION
**Pull request by Tyranicranger4**
## About The Pull Request
Adds a gas connector + ignitor setup to Box/Delta Xenobio. Similar setups exist on every other map.
Also shuffles things around a little bit to make room for it.

## Why It's Good For The Game
Consistency is good. Similar setups exist on every other map in rotation.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
Delta

image

Box
image

</details>

## Changelog
:cl:
add: Added gas ignitor setups to Box/Delta Xenobio
/:cl:

### CODE REVIEW

**Comment by Tyranicranger4** [comment]
Let me know if I fucked anything up here, first time using Git.

**Comment by EvilDragonfiend** [comment]
Don't post images outside of the open/close section. It is made to prevent a lost siphoning someone's data who is data poor.

**Comment by PestoVerde322** [comment]
immagine

move this igniter here in Box and it good to go, Delta is fine.

**Review by PestoVerde322 — APPROVED** [review]
Checked and good to go, approved.

**Review by Crossedfall — APPROVED** [review]
Merging per Pesto's review.

**Pull request merged**
