### PR TITLE
Reduced plant HP, remove tree shadows

### PR DESCRIPTION
**Pull request by BriggsIDP**
## About The Pull Request

reduce the hit points of foliage from 150, to 20 (about 2 hits), and removed the sprite shadow from the trees as it was causing layer issues with using items next to it

## Why It's Good For The Game

lots of maps now use these items, but they are really annoying to remove it someone wants to redecorate.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/107176252/18326a36-456f-494f-979a-23f715b602be

</details>

## Changelog
:cl:
tweak: Foliage HP decreased
tweak: Tree sprite shadows removed
/:cl:

### CODE REVIEW

**Comment by Nosnek199** [comment]
keep tree stump at 2 hit. all other foliage at 1 hit?

**Comment by BriggsIDP** [comment]
> keep tree stump at 2 hit. all other foliage at 1 hit?

amount of hits depends on the tool, you can quiet easy find a tool that does 20 damage, and kill it in one hit. the only reason i hesitate to make to 10 hp for example is someone might remove it with a accidental hit.

**Comment by itsmeow** [comment]
Noooo... the shadow looks goood

**Comment by BriggsIDP** [comment]
> Noooo... the shadow looks goood

It did look alright, but we have AO and it's one of the only sprites with a shadow. Consistency!

**Review by itsmeow — APPROVED** [review]
Yea OK no shadow :(

**Pull request merged**
