### PR TITLE
[PORT] Gives Revenant the ability to orbit adjacent things with double click or pull key

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
* port of https://github.com/tgstation/tgstation/pull/60200

## Ported body

Leverages right click to give Revenant something I felt it should have had when first implemented, but I can understand now it's not a low effort undertaking with the snowflakeness of incorporeal jaunt code that only runs on Move() 🤮

I put a lot of care into making sure this won't break or bypass jaunting counters like holy water and salt.

## Why It's Good For The Game
Grief ghost can orbit potential victims between hauntings. Telepathic broadcast targets can not move out of sight while you are composing a message if you can just orbit them.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://youtu.be/sZ5aF1HwTBY

salt / holywater tiles cancels rev orbitting. if the haunted victim goes to salt tiles, rev instantly is revealed and stunned. (I tested it after this recording)

</details>

## Changelog
:cl: Wayland-Smithy (EvilDragonfiend ports, and a tweak)
add: Revenants can orbit adjacent people and things with Double-Click or Ctrl+Click(pull), unless they are stunned, revealed, blocked by salt etc..
code: Improved Jaunt Move checks a little bit.
tweak: revenant can no longer use phase shift to hide back to ethereal phase on consecrated tiles
/:cl:

### CODE REVIEW

**Comment by bluezorua** [comment]
>add: Revenants can orbit adjacent people and things with Double-Right-Click, unless they are stunned, revealed, blocked by salt etc..

might want to change "double-right-click" to just "double-click" since this does not appear to use TGs right click?

**Comment by EvilDragonfiend** [comment]
> > add: Revenants can orbit adjacent people and things with Double-Right-Click, unless they are stunned, revealed, blocked by salt etc..
> 
> might want to change "double-right-click" to just "double-click" since this does not appear to use TGs right click?

my mistake, left click.

**Comment by EvilDragonfiend** [comment]
hmm, actually rev comming out from wall is funny I think. I will revert the restriction.

**Comment by EvilDragonfiend** [comment]
added the feature to pull key as well. incorporeal rev has no meaning to use ctrl+click so it'd be good to be another key for them.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
