### PR TITLE
Add Gear Harnesses (& Minor Janibelt Tweak)

### PR DESCRIPTION
**Pull request by VickiMorris**
## About The Pull Request
Adds new accessories that gives your uniform storage slots, similar to the shoulder holster or pocket projector! The gear harness is a non-job specific accessory that grants its user two additional small storage slots on their jumpsuit, and the engineer's and janitor's harnesses grant three additional normal sized (but job-specific) storage slots similar to belts. 

The harnesses are available in their respective vendors; two jani harnesses in the JaniDrobe, two engi harnesses in the EngiDrobe and AtmosDrobe (In addition to two being added as premium items to the YouTool vendor, same price as a toolbelt), and two regular gear harnesses being available as contraband in the CargoDrobe vendor. This one can also be crafted using three pieces of leather in the same manner you would make a wallet/botany gloves/toolbelt.

This also adds the rust-removing wire brush to the list of what the janitor belt can hold, as it was not included for some reason.

## Why It's Good For The Game
Accessory slots have very few items that can be applied, and _most_ of them are mechanical in nature; the poppy pin grants a positive moodlet, the miner's talisman and codpiece grant additional protection, the pocket protector and holster grant specific storage options.

For Janitors and Engineers, this grants a bit of extra storage to hold the myriad of tools they usually need to carry to do their jobs while not taking up backpack space, or possibly in place of the normal belt to allow carrying other gear in that slot. For all other crew, the two additional pocket-sized pockets it gives a bit of extra storage, either for flavor items or gear they might need. The generic gear harness might be removed if it's deemed unneeded to give crew _even more_ storage options however. To prevent too much item/storage cheese, harnesses are the same size as tool belts (normal sized).

The engineer's harness has the same items restrictions as the toolbelt, and the janitor's harness the same as the janibelt (sans pushbroom).

The main inspiration was a mixture of the harnesses that are available on other servers, and to alleviate the minor gripes experienced by #9337 and my own experiences with janitorial work while it was test merged.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

the runway

Video of harnesses being used for storage; https://github.com/BeeStation/BeeStation-Hornet/assets/97719613/d8069a8e-4dd5-4635-86d0-c4d3335e938f

</details>

## Changelog
:cl:
add: Added gear harness, engineer's harness, and janitor's harness
add: Adds harnesses for purchase in JaniDrobe, Atmos/EngiDrobe, YouTool, and CargoDrobe
add: Adds crafting recipe for gear harness; three leather in hand.
tweak: Allows janibelt to hold wirebrushes now
imageadd: Adds icon and worn sprites for harnesses
/:cl:

### CODE REVIEW

**Comment by VickiMorris** [comment]
I'm not sure what that comment on the janibelt is talking about, the light replacer is a small item so it doesn't need to have bulky as the largest allowed item size to have it fit in the belt. Not tweaking it as it's not exactly hurting anything to leave as is.

**Comment by VickiMorris** [comment]
I will be removing the janibelt tweak to allow the wirebrush if #9658 gets merged, for the obvious reason that it makes the exact same change.

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
Generic harnesses with pocket sized items and no restrictions sound cool, however I do not like the speciality harnesses at all and think they should be removed as they are in direct opposition to part of the intended changes implemented by #9337

Do not make the toolbelt-type situation *even worse* by adding a secondary, albeit slightly lesser toolbelt that doesn't take up the belt slot to the game please.

**Comment by Rukofamicom** [comment]
I would like to invite you to re-read over #9337 as well, as it has dramatically changed since the testmerge.

**Comment by VickiMorris** [comment]
Nah, that's a fair dig and I'm not sitting too well on this change now anyway; this was during the starting step of the storage adjustment PR that you made and it was made with that in mind. Between the changes on that, and the ones in Cydia's janitor overhaul, the janiharness really isn't needed.

Toolboxes are also, under utilized for engineers (also the default gear harness would still net two additional tool slots as most are small as it is), but now I'm mildly apprehensive about even those as I feel like it's going to be. Most people don't wear them unless they want to exacerbate the "hoarding all the gear" issue on certain jobs.

**Comment by VickiMorris** [comment]
I'm gonna close this for now, there's no incentive to not have a gear harness for most people with accessories as they are right now, and maybe we need more _fluff_ accessories for jumpsuits before I wedge in more mechanical-only ones.

**Pull request closed without merging**
