### PR TITLE
Departmental Wires

### PR DESCRIPTION
**Pull request by KitsuneQueen**
A lot of files. I don't know what I'm doing.

## About The Pull Request

It makes departments have their own unique wires.

## Why It's Good For The Game

Hacking a single door no longer gives you AA.

## Changelog
Me explaining the changes below.

### CODE REVIEW

**Comment by ToasterBan** [comment]
did you even test this?

**Comment by Cenrus** [comment]
If you're doing this then delete the cringe ass nae nae reinforcement on command airlocks

**Comment by Pontenerd** [comment]
Unironically using a catgirl gif on the github

**Comment by KitsuneQueen** [comment]
> Unironically using a catgirl gif on the github

It was a real pic of me and I felt cute. I'll delete it later, better save it 😳

**Comment by TeomanTheGreat** [comment]
> ## Changelog
> Me explaining the changes below.
> 
> 

Where is your changelog also why are there 9000 changes

**Comment by PowerfulBacon** [comment]
None of the code is in the code folder lol

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Everything is in the base directory.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Also you need a proper changelog

**Comment by yyzsong** [comment]
Is this a port of something else?

**Comment by ike709** [comment]
Closing because this has already been voted against and also it's a bad port job.

**Comment by pickleinjar** [comment]
heresy against the assistants united

**Pull request closed without merging**
