### PR TITLE
New map: AlphaStation

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request

This is a new map aimed for those pops with 1-10 people on them. The map should work well up to 15-18. After that I think the lack of space and avaiable jobs will make it feel small. There are no head of staffs beside captain. Cargo and service are combined. Medbay and science are combined. Maintenance is for the most part avaiable for everyone. There is no engine, just solars. There isn't any mining shuttle either, anyone can grab a space suit and go to the asteroid next to the station for materials

68747470733a2f2f616666656374656461726330372e626c6f622e636f72652e77696e646f77732e6e65742f6d6462322f696d616765732f3136323335363932372f33313239303932313332302f612f5f6d6170735f6d61705f66696c65735f416c70686153746174

<details>
<summary>Missing jobs</summary>

- Exploration Crew
- Geneticist
- Bartender
- Brig physician
- Chief Medical Officer
- Head of Security
- Head of Personnel
- Chief Engineer
- Research Director
- Roboticist
- Shaft miner
- Chemist
- Lawyer
- Quartermaster
- Station Engineer
- Paramedic

</details>

This doesn't mean you can't do what these jobs usually do. Robotics exists, but there is no Roboticist. Chemistry exists, but there is no chemist. It will all be done by general staff with access to everything on the department.

<details>
<summary>Size comparation to other maps </summary>

EchoStation
imagen

CorgStation
imagen

BoxStation
imagen

</details>

To do list

- [ ] Finish maintenance
- [ ] Add a public shuttle in case it's needed for anything
- [ ] Put doors 
- [ ] Put cameras
- [x] Make a place for the AI
- [ ] Fix atmos

## Why It's Good For The Game

We currently have a problem on lowpop rounds where people will go play stuff that's either being in a room sniffing glue 2 hours or leaving the station. This map creates an enviroment where a lot of jobs are combined, some are straight not avaiable and tries to make lowpop more enjoyable. You can roam more freely without super restrictive access and the station is small.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

</details>

## Changelog
:cl: ClownMoff, XeonMations
add: Adds a new map: AlphaStation
/:cl:

### CODE REVIEW

**Comment by Rukofamicom** [comment]
I'm not sure I like this as a concept for a station in general, some people definitely do use extreme lowpop to fuck around instead of being involved on a greater level, but this map will very likely cause those players to simply not play at all. Reduced interaction is better than not having them at all in many cases, especially when it comes to the overall health of the server. 

Extremely low population is going to feel the same, but because we have actually fewer people connected it is likely to remain lower pop for much longer. This map is designed with too low of an upper ceiling in mind to be healthy for the game. 

🔑

**Comment by Rukofamicom** [comment]
Moving aside the key and my reasons for it, in the event other maints like and want this map:
* What purpose does an AI serve on this map? I think the satellite should be cut just like the other head positions were tbh. 
* Why are there two full sets of chemistry equipment? The chemistry lab could be cut down, or allow for more open space to set up plumbing. The core machines don't really need to be two of on such a small map
* image Why is this even here, you already have all the bar equipment in the kitchen, and this is pretty self-serving to include on such a small map.
* Why is Xenobio still here? Including it seems contrary to your stated goals
* Why is there such massive open space in atmos, likewise seems contrary to your stated goals. 
* The vault should not be adjacent to space
* I see an armory and security lockers, but I'm not seeing an area for criminals to be held for their sentences.

**Comment by PowerfulBacon** [comment]
Some of the job choices are strange. Station engineer is one of the few that are almost mandatory on lowpop maps, since someone needs to do station maintenance. They should be the ones with free reign over engineering.

Arguably mime and clown should take lower priority over some over jobs like QM and HOP, since HOP serves as the second in command of the station.

Some objectives will be impossible on this map unless heads have lockers, as those lockers are required on maps.

**Comment by PowerfulBacon** [comment]
Also without the shaft miner who is meant to be the one dedicated to mining the asteroid?

**Comment by ClownMoff** [comment]
> I'm not sure I like this as a concept for a station in general, some people definitely do use extreme lowpop to fuck around instead of being involved on a greater level, but this map will very likely cause those players to simply not play at all. Reduced interaction is better than not having them at all in many cases, especially when it comes to the overall health of the server.
> 
> Extremely low population is going to feel the same, but because we have actually fewer people connected it is likely to remain lower pop for much longer. This map is designed with too low of an upper ceiling in mind to be healthy for the game.
> 
> 🔑

Did you really have to wait until this was PR'd to instantly key it? It seems like everything gets a key nowadays without even giving it a try lmao, I've poured a lot of time into this and your first comment wasnt even like maybe we could make this work it was directly "thanks, fuck you" and then after that the questions on a separate comment

**Comment by ClownMoff** [comment]
Responding to the questions:

1.- I havent thought about it very deep, I guess AI can be scrapped.

2.- Agree, we can cut it down to one

3.- Because I thought it was a funny and harmless thing to add. Strange thing to point about.

4.- Because I've talked with people about what science stuff is mandatory for research. Being this small and being on the same room as the majority of other research means you won't get much out of it and also people can interact with you without being locked in your own powergaming room. I would gladly remove it if it didn't cost a huge chunk of possible research

5.-Atmos was being done by Xeon. It's fairly easy to figure out is just not done yet :/

imagen

6.- We can figure that out

7.- imagen

There is a prison. I don't know how you missed it, but there is noe right there.

**Comment by ClownMoff** [comment]
> Some of the job choices are strange. Station engineer is one of the few that are almost mandatory on lowpop maps, since someone needs to do station maintenance. They should be the ones with free reign over engineering.
> 
> Arguably mime and clown should take lower priority over some over jobs like QM and HOP, since HOP serves as the second in command of the station.
> 
> Some objectives will be impossible on this map unless heads have lockers, as those lockers are required on maps.

I wanted to put atmos instead of engineer out of personal preference just cuz I liked it more having atmosian people and there is no engine, and they could also fix the station parts too, but I can swap it for engineering. Yes, mime and clown are expendable, I also thought about if they are really needed and thought about not including them. If we remove the theatre itself it gives more space for needed stuff. The good thing about them 2 is that they only need a room with a crate and spawnpoints.  I thought about adding HoP too and QM is just... that he doesn't have a very clear role on this map. If you have a HoP you don't need a QM on this map, and also makes more sense having a hop since it oversees cargo and service, and those are combined on this map. We could put the "steal this" objectives in other places. Blueprints on captains office, the hos gun for the warden instead. About minerals, I was thinking that anyone in cargo/service could just pick up the pickaxes and go to the asteroid, maybe even an assistant. If you leave miner open as a job people will join expecting the solo experience of going down to lavaland and not being seen the entire shift. With this approach, people will go do mining as a necessary hussle and will go back to their old tasks. "Can someone go and grab some minerals?" "For sure"

**Comment by ClownMoff** [comment]
> I'm not sure I like this as a concept for a station in general, some people definitely do use extreme lowpop to fuck around instead of being involved on a greater level, but this map will very likely cause those players to simply not play at all. Reduced interaction is better than not having them at all in many cases, especially when it comes to the overall health of the server.

This map came out of this thread on discord: https://discord.com/channels/427337870844362753/1287025282301169705

Here Bacon said that he would like lowpop to be more free and with way less jobs on a smaller map. So I agreed and went and made one exactly like that. This map gives everyone more job to do. I dont see how it will make people go "oh man I gotta be in charge of all medbay alone and have more responsabilities? fuck this imma go sit in the bench on the central hallway"

**Comment by PowerfulBacon** [comment]
There was an attempt to do a map very similar to this in the past, which never made it past testmerging. You are doing a very untraditional map which doesn't benefit from common map knowledge so are really in the realm of the unknown. This will need to be testmerged and you need to be prepared for some substantial change requests that come out of that.

Some things are issues that need to be resolved immediately before that.
- Station engineer needs to exist as a job role. They are probably one of the more important roles for a lowpop station.
- Most job content should still generally exist. People don't like maps where things are just missing completely.
- Mandatory content such as antagonist objectives need to be included in some form. When I suggested removing heads on lowpops, this really was a suggestion that would have needed a large amount of code-work to be viable.
- It seems like you have forgotten to add half the doors

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
I don't agree with designing a map quite this small and restricted, but my key can be ignored as long as others don't agree with me.

I just have two blocking requests to make beyond generally disagreeing with the concept.
* Remove the second bar from maints. Nobody gets to add their own special, personalized room on a station, especially one this small. Add it (or something similar) as a random maints room rather than a static spawn
* Move the vault to a location that has no walls on the outer edge of the station (exposed to open space and easily breached)

**Comment by ClownMoff** [comment]
> * Mandatory content such as antagonist objectives need to be included in some form. When I suggested removing heads on lowpops, this really was a suggestion that would have needed a large amount of code-work to be viable.

Can't I just put the objective stuff on other places? :S captain can have the blueprints, warden the X-01 MultiPhase Energy Gun and the Reactive Teleport Armor can be put in the armory. Am I missing something?

**Review by EvilDragonfiend — COMMENTED** [review]
Job change is deprecated now. Check `map adjustment` of Echo Station.

**Comment by Tsar-Salat** [comment]
is this still being developed

**Comment by ClownMoff** [comment]
Probably not for the time being

**Pull request closed without merging**
