### PR TITLE
ports tg's projectile rework, passflags rework

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

ports
tgstation/tgstation#54924
tgstation/tgstation#48659
and other fixes

## Why It's Good For The Game

old code begone

## Changelog
:cl: silicons, ninjanomnom
refactor: projectiles now use a new hit detection system that doesn't rely on quirks in movement code to work, and is easier(?) to work with
refactor: pass_flags_self now handles determining if something with specific pass_flags can cross something, by default.
fix: piercing projectiles (see: penetrating snipers) work again
tweak: projectile permutated/impacted list is reset on ricochets, meaning reflected projectiles can potentially hit something again if it pierced it the first time.
/:cl:

### CODE REVIEW

**Comment by jupyterkat** [comment]
image
.50 penetrators works great

**Comment by utilbird** [comment]
addition of a crossed() call. #4454

**Comment by jupyterkat** [comment]
merge this first or that first and I'll update it

**Comment by KubeRoot** [comment]
Note: implements the "Can pass refactor" card on the "Things to Port" project

**Comment by KubeRoot** [comment]
Seems like https://github.com/BeeStation/BeeStation-Hornet/pull/5132 was an incomplete port, missing two lines of code:
```dm
			if(obstacle.pass_flags_self & LETPASSTHROW)
				continue
```
in ` code/controllers/subsystem/throwing.dm` on line 119 (see https://github.com/tgstation/tgstation/pull/60604/files#diff-7012ec3cdcedc1dbedb3f0def763e426c904897835026aea3fc2b5a97862f475R122 versus https://github.com/BeeStation/BeeStation-Hornet/pull/5132/files#diff-7012ec3cdcedc1dbedb3f0def763e426c904897835026aea3fc2b5a97862f475R119). The code uses `pass_flags_self`, which is implemented in this PR.

Might want to readd the missing code in this PR, which should fix thrownthings stopping on tables.

**Comment by 4rchibald** [comment]
@jupyterkat 
We are testmerging it right now, we just had blob and emitter beams were passing through it

**Comment by KubeRoot** [comment]
Might need this added to fix issues with things passing through blob: https://github.com/tgstation/tgstation/pull/55495

**Review by Archanial — CHANGES_REQUESTED** [review]
Blobs don't work

**Pull request closed without merging**
