### PR TITLE
Adrenaline Nanites gets moved to weaponized tech (now requires illegal tech)

### PR DESCRIPTION
**Pull request by TeomanTheGreat**
## About The Pull Request
Puts the adrenaline nanites in the research category they belong in. Adrenaline nanites are very robust at their current state. Literally better than meth because of no OD side-ffects or brain damage. Also this
image

## Why It's Good For The Game
Nerfs the nanite meta. 

## Changelog
:cl: Phil Smith
balance: Adrenaline nanites are now under weaponized tech which means you now need illegal tech to get it!
/:cl:

### CODE REVIEW

**Review by francinum — APPROVED** [review]

**Review by Archanial — APPROVED** [review]

**Comment by aidan-bowman** [comment]
oh god oh fuck they're gonna speedremove nanites now 😔 

goodbye nanites we'll always remember you

**Comment by eeSPee** [comment]
> oh god oh fuck they're gonna speedremove nanites now 😔
> 
> goodbye nanites we'll always remember you

* Relay nanites removed for lagging the server
* Dermal ID nanites removed cause they are OP
* Weaponized nanites grudgecoded away because a maintainer got robusted by them
* Healing nanites removed because fuck you

Edit: Don't worry, you will be able to do everything and more with the new Viro symptom. It will also manifest a deblade at 5 resistance.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by Sinestia** [comment]
How will nanites recover?

**Comment by Kapu1178** [comment]
Dont move it to weaponized, its not a weapon. Keep it in Augmentation and just move it to Military Tech.

**Comment by DatBoiTim** [comment]
> Edit: Don't worry, you will be able to do everything and more with the new Viro symptom. It will also manifest a deblade at 5 resistance.

When Viro becomes more powerful then xenobio, I can rest easy.

**Comment by TeomanTheGreat** [comment]
> Dont move it to weaponized, its not a weapon. Keep it in Augmentation and just move it to Military Tech.

It may not be a weapon but its used with weapons in combat situations

**Pull request merged**
