### PR TITLE
Adds 'Modern Announcement System' announcer pack

### PR DESCRIPTION
**Pull request by Kapu1178**
## About The Pull Request
Baystation Torch announcer pack because why not lol.

Shuttle Recalled and Intercept are just "attention" due to a lack of splicable voice lines.

## Why It's Good For The Game
its funny lol

## Changelog
:cl:
add: Modern Announcement System rare announcer pack.
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
~~ngl the torch announcer's kinda shit and has less soul than the original bay lines, which is why I didn't bother cleaning it up~~

**Comment by qwertyquerty** [comment]
:key:

**Comment by mcmeiler** [comment]
Plannedemic

Also me like torch announcer

**Comment by ghost** [comment]
> Also me like torch announcer

~~Torch announcer hurts my soul. Forcing Bee players to listen to them is bad faith.~~

**Comment by francinum** [comment]
Look. Even the Plannedemic has limits.

This announcer's just *not good*

**Pull request closed without merging**
