### PR TITLE
Removes murderbone items from surplus crates

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
The following items can no longer be found in surplus crates: His Grace, Romerol, Syndicate Balloon.

## Why It's Good For The Game
His Grace and Romerol are high cost items that are nigh-unusable without murderbone objectives.
The Syndicate Balloon taking up 20 of the TC in the crate is awful when it happens.

## Changelog
:cl:
tweak: The following items can no longer be found in surplus crates: His Grace, Romerol, Syndicate Balloon.
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — APPROVED** [review]

**Comment by ghost** [comment]
Random should be random. you gotta spinnnn da wheel

**Comment by Ivniinvi** [comment]
It should be random items that you can actually use, not items that are 25tc and unusable because of OOC rules and not IC rules.

**Comment by francinum** [comment]
I agree with removing the >20TC items as they are intended to result from rare instances of TC theft or traitor cooperation, not be a product of pressing the random button and getting lucky.

His Grace is actually a terrible thing to have happen to you and is nigh unusable and I was considering snipping it from the uplink entirely.

The only one I do not approve of being removed is the balloon. Sometimes you just get fucked.

**Comment by Ivniinvi** [comment]
> The only one I do not approve of being removed is the balloon. Sometimes you just get fucked.

The fun part of a lot of things that would be normally useless is the option of counterplay. Things like the 14tc Blast Cannon, which is pretty dumpster tier if you're not a scientist, will once in a blue moon have someone actually utilize it. Unlike the blast cannon or other such items, the balloon has exactly zero options for counterplay. 70% of HoSes will arrest you on sight and perma/execute you just for holding it. The other high value, specific purpose items will screw the average traitor but leave some option of interactability and counterplay, which makes them fun, but getting a balloon in a surplus crate is straight up unfun.

**Pull request merged**
