### PR TITLE
KiloStation Medbay Rework 4 PR and FINAL

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request
First of all I would like to apologize for so many opened and closed PRs but things get out my control real quick and its way easier to open another PR and copypaste the map into the most recent version of the map than dealing with all the map merging problems and merge problems in general. Past PRs: https://github.com/BeeStation/BeeStation-Hornet/pull/10481, https://github.com/BeeStation/BeeStation-Hornet/pull/10327, and https://github.com/BeeStation/BeeStation-Hornet/pull/10080 (OG).

KiloStation Medbay rework. All areas have been updated to have a better use of the space. OG Kilo just have rooms weirdly shapend and oddly placed for the sake of it. This rework aims to get a cleaner, more satisfying layout while still keeping Kilos theme of being small and cramped

## Why It's Good For The Game

Because medbay people deserve better.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

68747470733a2f2f616666656374656461726330372e626c6f622e636f72652e77696e646f77732e6e65742f6d6462322f696d616765732f3136323335363932372f32303532383332353034332f6d2f5f6d6170735f6d61705f66696c65735f4b696c6f5374617469
</details>

## Changelog
:cl: Varo, MarkusLarsson421
tweak: Reworks the lobby, changes the front desk position to where cloning was, moves genetics to the big monkey room, moves cloning where genetic was, adds a surgery room, reworks the CMO office, storage and chemistry room, removes a big part of virology and places it all below chemistry, tweaks some maintenance areas 
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
Testing evidence machine broke

**Comment by MarkusLarsson421** [comment]
Odd wrenched girther requring you to have a wrench to pass unless you can go through the side room.


Still Science themed floor and also missing one blue floor tile colouring at the bottom.


Feel a bit... weird about the pattern on the floor here. Previously, I described this as an intersection, and it still is, and I now noticed the darker floor signifying it to be the treatment area, but it doesn't seem to have any consistant pattern to it. It is a large room with a darker corner.

**Comment by ClownMoff** [comment]
68747470733a2f2f616666656374656461726330372e626c6f622e636f72652e77696e646f77732e6e65742f6d6462322f696d616765732f3136323335363932372f32303532383332353034332f6d2f5f6d6170735f6d61705f66696c65735f4b696c6f5374617469

**Review by PestoVerde322 — APPROVED** [review]

**Comment by MarkusLarsson421** [comment]
Feel a bit... weird about the pattern on the floor here. Previously, I described this as an intersection, and it still is, and I now noticed the darker floor signifying it to be the treatment area, but it doesn't seem to have any consistant pattern to it. It is a large room with a darker corner. The rest of medbay is almost all white except that void of a corner.
 

There are too few air alarms (0, need 1) in the morgue.
 

There are too many air alarms in viro.
 

No slip-proof tile under shower and random dark themed corner?
 

Missing light switch for the front lobby and the medical treatment area. Having one by each main door is a good rule of thumb (or as close as possible).

Treatment area could use another light or two, I think?

Warning stripes of the old morgue door? Also, a slight warning stripe corner under the table on the opposite side.
 

Two random reinforced walls.
 

Dirt on two walls? Might not matter.
 

It is next to impossible for Cyborgs to put in a body or brain into the cloner. They would have to destroy the vending machine or a wall to get them in if no one else is available.

Random plating, odd floor decals outside chemistry, and a floating light? 
 

Decals trace the wall on top-left, but they trace the consoles on the right? Tracing the wall tends to be preferable. The same difference can be found in CMO-Genetics. Where you follow one pattern and then another one. 
 

Two missing decals. Plus, missing a decal to the reception.
 

Missing camera in genetics. Can an AI see it?

Two lights next to each other.
 

What happened to maints here?!
 

Reinforced wall stretching too far.
 

Generic spawn inside a wall. I'd place a maintenance door at the circle. And random warning stripes.
 

Missing wall.
 
 

Are all these walls supposed to be missing?
 

Two lights at the bottom, none at the top.

**Comment by ClownMoff** [comment]
imagen
what version are you using? current one looks like this. Also I'm not going to make major changes this has been on the works since october i can't wait to forget about this. Minor changes can be adressed later

**Comment by MarkusLarsson421** [comment]
> what version are you using?

The image you provided earlier.

> Also I'm not going to make major changes this has been on the works

I think half of maintenance missing walls is a good reason to make more changes.
image

**Review by PestoVerde322 — CHANGES_REQUESTED** [review]
immagine

Wrong window

immagine

This maint door should be on req_one_access_txt "5;6;22"

immagine

Certified broken tile icon classic (there's more scattered around the station)

immagine

Move the disposal beneath the door instead of the table

immagine

Unsure if this this generic spawner will work...

immagine

Floating posters and fixtures

immagine

Odd cabling, go around the plant rather than beneath it

immagine

Odd zoning

immagine

Might be too cramped, also acces straight to the operation theather is a bit convoluted

immagine

randomaint without walls surrounding it?

immagine

those two posters aren't nudged, so they will show from any direction

**Comment by PestoVerde322** [comment]
immagine

Pipe should go beneath the door

immagine

Odd spawner location and extra wall beneath the poster, and also overall decal weirdness

immagine

lots of floating fixtures and decals

immagine

unusual cabling

immagine

Blockade

**Comment by MarkusLarsson421** [comment]
@ClownMoff , you're not gonna use the fixed dmm I sent you?

**Review by PestoVerde322 — APPROVED** [review]
Seems all good, Approved.

**Pull request merged**
