### PR TITLE
fixes get hearing yet again

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

we don't have area sensitive components, that screwed over the port since the overrides do not exist

## Changelog
:cl:
fix: fixed get hearing again
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Someone else can handle this

**Review by Archanial — APPROVED** [review]

**Comment by ike709** [comment]
Does this even fix all of the `null.Hear()` runtimes?

**Comment by Archanial** [comment]
> Does this even fix all of the `null.Hear()` runtimes?

What do you think? I'm 99% sure it won't.

**Comment by jupyterkat** [comment]
> > Does this even fix all of the `null.Hear()` runtimes?
> 
> What do you think? I'm 99% sure it won't.

this clears the recursive contents list after the atom exits the other mover. obviously it’s gonna help because if it’s not removed, when the atom gets qdeleted or something it’s gonna contain null references

**Pull request merged**
