### PR TITLE
Adds stand arrow to necropolis chests

### PR DESCRIPTION
**Pull request by yorii**
## About The Pull Request

Adds stand arrow to necropolis chest loot rotation, this is not my PR but belongs to Phil/TeomanTheGreat.

## Why It's Good For The Game

Because it's fun.

## Changelog
:cl: TeomanTheGreat
add: added stand arrow to necropolis chest
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
Thank you very cool

**Comment by TeomanTheGreat** [comment]
It also adds the stand ruin into rotation on lavaland

**Comment by zeskorion** [comment]
let's see....

the item that unlocks unbalanced admin-only stands, a ruin that gives you that item for free, AND adding it to necrochests?


i dont think so

**Comment by TeomanTheGreat** [comment]
> the item that unlocks unbalanced admin-only stands

the whole point is that its not supposed to be admin only and i dont see how they are unbalanced.

**Comment by yorii** [comment]
now it only adds the stand arrow as possible loot to necropolis chests

**Comment by zeskorion** [comment]
unless another maintainer thinks requiem stands could be in any way balanced for player use, i'm closing this. miner loot doesn't need a buff, and steamport stands are already hippie bullshit that are liable to be removed

**Comment by TeomanTheGreat** [comment]
@PowerfulBacon @qwertyquerty mind putting your opinions in? (you're the only other maintainers I know off the top of my head )

**Comment by qwertyquerty** [comment]
Bad

**Comment by TeomanTheGreat** [comment]
have a better idea qwerty for how the arrow should be put in the game?

**Comment by PowerfulBacon** [comment]
Bad

**Comment by yorii** [comment]
😂

**Pull request closed without merging**
