### PR TITLE
Slight brain trauma refactor - nanites and viruses can no longer cure obsession or hypnosis

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

This does a slight refactor of brain trauma, merging some stuff into a bitflag field and also adding a "special cure immunity" flag. For now, nanites and viruses are considered "special cures".

As a result, obsession and hypnosis are now special-cure-proof, meaning that nanites and viruses _will not_ cure them no matter what (nor will they trigger the brain healy nanite programs in the first place).

Note that only hypnosis obtained through hypnoflash is special-cure-proof; hypnosis obtained thru oneiric feedback loop can still be cured by special means.

## Why It's Good For The Game

Nanites/viruses shouldn't be able to take away antag.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

23-04-26-1682500341-dreamseeker

</details>

## Changelog
:cl:
refactor: Slightly refactored brain trauma.
balance: Nanites and viruses can no longer cure an obsession or hypnosis.
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
maybe mind resto virus too

**Comment by Absolucy** [comment]
@EvilDragonfiend done.

**Review by EvilDragonfiend — CHANGES_REQUESTED** [review]
* remove callback. `trauma_can_be_specially_cured` has no reason to exist for this
* rename `custom_check` into `cure_method_special=FALSE`
* give `cure_method_special` TRUE when it's necessary
* and in `if` statement...
  * remove `&& (!custom_check || custom_check.Invoke(BT))` 
  * add `if(cure_method_special && (BT.trauma_flags & TRAUMA_SPECIAL_CURE_PROOF)) continue`

**Comment by EvilDragonfiend** [comment]
> add `if(cure_method_special && (BT.trauma_flags & TRAUMA_SPECIAL_CURE_PROOF)) continue`
in case you saw that earlier I tell you - I slightly miswrote this and edited it correctly. It shouldn't be `if(!(cure_method_special && (BT.trauma_flags & TRAUMA_SPECIAL_CURE_PROOF))) continue`, my mistake...

**Comment by Absolucy** [comment]
Alright. I've made the proper changes.

**Review by itsmeow — APPROVED** [review]

**Pull request merged**
