### PR TITLE
Removes debtor

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Removes debtor

## Why It's Good For The Game
removes debtor

## Testing Photographs and Procedure
removes debtor

<summary>removes debtor</summary>

removes debtor
removes debtor
</details>

## Changelog
:cl:
del: removed debtor
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
also removed hangover icons because they are not used

**Comment by rkvothe14** [comment]
i'm under the suspicion that this pr might want to remove debtor

**Comment by DatBoiTim** [comment]
TBH they wouldn't be terrible if they had the random attack thing removed.

**Comment by ACanOpener** [comment]
I feel like I'm getting conflicting information, what does this pr do?

**Comment by zeskorion** [comment]
The debtor has committed suicide by strangulation followed by three gunshots to the back of the skull

**Comment by Archanial** [comment]
> The debtor has committed suicide by strangulation followed by three gunshots to the back of the skull

4 actually

**Comment by DerpiestBruh** [comment]
I may be wrong, but I think this PR removes the debtor

**Comment by 4rchibald** [comment]
So yeah, gimmick roles didn't really work out as some intended
Partially because there wasn't a clear idea what they should do and partially because of how they are grouped as one role in occupation preferences menu-if someone wants to play psychiatrist they won't enjoy being a hobo living in maints, when someone wants to be a debtor and has some idea on how to play it they won't enjoy becoming psychiatrist.

Stage magicians are somehow most disappointing since I have never seen a magician who actually tried to entertain people 

**But I don't believe removing any of those is a good move**
Especially not debtor since we really need someone like them from both gameplay and roleplaying reasons.
They benefit RP since they are introducing interactions you wouldn't expect from any other person and is a way to introduce weirdest ideas like conspiracies to regular boring round.
For gameplay reasons...ever since assistants lost their access to maints there is almost no one who walks in them, and surely almost no one searches them thoroughly. It's really easy for antag to just hide body in maint locker and such person will almost never be recovered by anyone (back in the day chances of someone opening locker were quite high)

We should look into improving gimmick roles, not simply remove them

**Comment by zeskorion** [comment]
> So yeah, gimmick roles didn't really work out as some intended Partially because there wasn't a clear idea what they should do and partially because of how they are grouped as one role in occupation preferences menu-if someone wants to play psychiatrist they won't enjoy being a hobo living in maints, when someone wants to be a debtor and has some idea on how to play it they won't enjoy becoming psychiatrist.
> 
> Stage magicians are somehow most disappointing since I have never seen a magician who actually tried to entertain people
> 
> **But I don't believe removing any of those is a good move** Especially not debtor since we really need someone like them from both gameplay and roleplaying reasons. They benefit RP since they are introducing interactions you wouldn't expect from any other person and is a way to introduce weirdest ideas like conspiracies to regular boring round. For gameplay reasons...ever since assistants lost their access to maints there is almost no one who walks in them, and surely almost no one searches them thoroughly. It's really easy for antag to just hide body in maint locker and such person will almost never be recovered by anyone (back in the day chances of someone opening locker were quite high)
> 
> We should look into improving gimmick roles, not simply remove them

Gimmick roles were a dumb idea. I am not against removing any or all of them. I did not think them through when i added them

**Comment by Fronsis** [comment]
improve don't remove

**Comment by 4rchibald** [comment]
@zeskorion 
They are not dumb idea, if anything the way they got implemented didn't work out. Other servers with success have psychiatrists or other roles that are not necessary every round and probably shouldn't appear every round so it wouldn't get stale like some sort of inspectors etc 

Instead of straight up removing we should look into how to improve, especially not remove probably the only gimmick role that seems to be somehow regularly doing what it should. 

Just from top of my head

1. Allow people to enable which gimmick roles they like to play (either in occupation preferences window, treat gimmick like a department or something, or in place where you enable antags)

2. Make new roles like inspectors, journalists, dare I say move detective to gimmick instead of regular role (that should be a private investigator, not fancy looking sec officer which sadly both players and maintainers are trying to make it into, just yesterday they gave det rubber bullets to encourage him arresting people, not as last ditch weapon to defend themselves if attacked)

3. Roles that run official business like barber, psychiatrist etc shouldn't have their place of work in maints, half of crew can't even access these tunnels, how can we expect people to actually go there for their therapy? We really shot ourselves in the foot with this one, I dare say that gimmick roles didn't get a fair chance by banishing them to restricted areas. We should have standardized size for gimmick role room, and make it policy for new map to include spot for them connected straight to hallways, just like bar or lawyer office. For existing maps we should use vacant office which is included on every map in rotation

**Comment by Raven-Industries** [comment]
Farewell to the perpetual jailbird and occasional cult-leader, we'll miss you.

**Comment by zeskorion** [comment]
> @zeskorion They are not dumb idea, if anything the way they got implemented didn't work out. Other servers with success have psychiatrists or other roles that are not necessary every round and probably shouldn't appear every round so it wouldn't get stale like some sort of inspectors etc
> 
> Instead of straight up removing we should look into how to improve, especially not remove probably the only gimmick role that seems to be somehow regularly doing what it should.
> 
> Just from top of my head
> 
> 1. Allow people to enable which gimmick roles they like to play (either in occupation preferences window, treat gimmick like a department or something, or in place where you enable antags)
> 2. Make new roles like inspectors, journalists, dare I say move detective to gimmick instead of regular role (that should be a private investigator, not fancy looking sec officer which sadly both players and maintainers are trying to make it into, just yesterday they gave det rubber bullets to encourage him arresting people, not as last ditch weapon to defend themselves if attacked)
> 3. Roles that run official business like barber, psychiatrist etc shouldn't have their place of work in maints, half of crew can't even access these tunnels, how can we expect people to actually go there for their therapy? We really shot ourselves in the foot with this one, I dare say that gimmick roles didn't get a fair chance by banishing them to restricted areas. We should have standardized size for gimmick role room, and make it policy for new map to include spot for them connected straight to hallways, just like bar or lawyer office. For existing maps we should use vacant office which is included on every map in rotation

The current implementation of gimmick roles is poorly done and wasnt properly thought out. They're just assistant+


1. They originally worked this way in-development. This was veto'd by ike.
2. Wyci. If gimmick jobs *are* reworked by someone other than me, i'd *love* lawyer, chap, curator, and the detective to be folded into them
3. Wymi.

**Comment by Archanial** [comment]
> improve don't remove

in that case I am improving the game by removing debtor

**Comment by ToasterBan** [comment]
I understand the removal but I had way more problems with shitter magicians than shitter debtors tbh

**Comment by DatBoiTim** [comment]
> I understand the removal but I had way more problems with shitter magicians than shitter debtors tbh

Yeah, most issues with debtor arise from their stupid martial art thing where they have RNG intents that can hurt people a lot when they do not intend to.

Magicians? I've seen many times where they stop by some where and steal shit you are working on, in some cases even doing so while space walking, spacing whatever stuff you were working on.

**Comment by ToasterBan** [comment]
personally i wouldn't mind seeing the gimmick system gutted and keeping the psychiatrist as a real role and maybe also VIP

**Review by PowerfulBacon — APPROVED** [review]

**Comment by DerpiestBruh** [comment]
remember what they took away from you

**Pull request merged**
