### PR TITLE
Removes the syndicate surgery implant

### PR DESCRIPTION
**Pull request by PowerfulBacon**
Reverts BeeStation/BeeStation-Hornet#9011

## About The Pull Request

Removes the syndicate surgery implant added by #9011

## Why It's Good For The Game

The syndicate surgery implant allows for brainwashing but has many of the elements that make brainwashing fun to be against removed, mainly the evidence left behind from setting up a surgery station in maints or the risk of using it in the middle of medical. This PR removes brainwashing from the syndicate surgery implant, requiring that the brainwashing surgery disk be used instead.

In another PR (#9300) I replaced the brainwashing with the ability to create non-infectious zombies however there are still concerns with the item being raised. I'm still neutral on whether or not a full revert is necessary, I'll try and keep the PR up to date with the concerns but if all else fails this solves the problem without the additional concerns raised from necrotic revival changes (mainly balance of the zombie).

Unfortunately, when it came to implementation in game the item has caused a lot of issues and significantly increased the amount of frustration expressed over brainwashing.

## Testing Photographs and Procedure

image

## Changelog
:cl:
del: Removes the syndicate surgery implant
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
I am going to approve this in one or two days as long as there is no strong opinion in regard to this.
I believe people enjoyed this enough.

**Comment by EvilDragonfiend** [comment]
Attach a note to this:
We've discussed about brainwash for enough amount of time, but we have found none of the best or any better solutions. I believe the brainwash should be reverted to where it used to be. We aren't going to detect brainwashes, but we're going to detect brainwash operations.

**Comment by PowerfulBacon** [comment]
The kind of nail in the coffin for traitor surgeries attached to this item is that no matter the idea, it will always be better as a surgery disk due to the same reasons brainwashing is better as a surgery disk and not an implant. (Time to setup, evidence left behind, risk)

**Review by EvilDragonfiend — APPROVED** [review]

**Review by Rukofamicom — APPROVED** [review]

**Comment by Rukofamicom** [comment]
I've been swayed after internal discussion and believe it is best for the game that this implant be removed after all. 

Brainwashing is the main concern for me, but the limitations of the disk handily keep the issues with brainwashing in check.

**Pull request merged**
