### PR TITLE
Port reproductive extract refactor and fix from tg

### LINKED ISSUE #4566: Bio bags broke
## Round ID:
30627
## Testmerges:
#4415: 'Let's see if this helps anything at all.' by francinum at commit 41b343ce2c
#4380: 'Security Rework Part 1 of ?: Energy pistols' by ike709 at commit c10d3a13cb
#4454: 'ports removal of crossed() and uncrossed(), also checkexit()' by jupyterkat at commit bad28ed38f
## Reproduction:

Bio bag compatability with reproductive extracts is broken
Using a bio bag with monkey cubes in it will attempt to pick up all items on the tile instead, even if done via alt-click
The expected result would be removing a monkey cube from the bio bag and feeding the extract

### LINKED ISSUE #4701: bio bag interaction with reproductives is broken
## Round ID:
30977

## Reproduction:
Using a bio bag with monkey cubes in it on a reproductive extract causes it to attempt to pick up everything on the tile instead of autofeeding the reproductive.

### PR DESCRIPTION
**Pull request by MNarath1**
## About The Pull Request

This Ports https://github.com/tgstation/tgstation/pull/60345 from TG.
I already tried once to fix biobags in https://github.com/BeeStation/BeeStation-Hornet/pull/4894 but that PR was closed by a maintainer now i understand this was done cause of the snowflake code so i am now porting this fix from TG that refractors reproductive extracts a bit too.
Now this Port is not exactly a 1:1 of the TG PR as i had to adjust it slightly thanks to span and some other differences also i changed the max feed amount back to 1 cause i don't see why it should be more honestly.
I also changed the layer of reproductive extracts to be on the lower item layer so that the extracts spawn above the reproductive extracts and can easily be picked up.
closes: #4566
closes: #4701

## Why It's Good For The Game

Its an annoying bug and should be fixed.

## Changelog
:cl: MNarath1, JustANormalHooman
tweak: Reproductive extracts are now on the lower item layer
fix: you can feed reproductive extracts with the biobag again
refactor: refractors reproductive extract and biobag interaction
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
Ugh

**Comment by MNarath1** [comment]
> Ugh

Ugh cause of the way this is handled in the port or cause of a fix for this bug itself or my changes to the original port PR?

**Comment by MNarath1** [comment]
oh god

**Comment by MNarath1** [comment]
this is i only commited a single god dam change from the merge of the master why tf did it commit all here ahhhhhhh

**Pull request closed without merging**
