### PR TITLE
Ports new overlay lighting component and opacity refactor from tg

### PR DESCRIPTION
**Pull request by yorii**
## About The Pull Request

Ports https://github.com/tgstation/tgstation/pull/52881 and https://github.com/tgstation/tgstation/pull/52413

## Why It's Good For The Game

No more laggy broken flashlights.

## Changelog
:cl:
add: Smooth movable lighting system implemented. Projectiles, sparks, thrown flashlights or moving mobs with lights should be much smoother and less laggy.
balance: Light sources no longer stack in range, though they still do in intensity.
balance: Mechs no longer block sight. It's a non-trivial cost for the lighting system with little to no gain.
/:cl:

### CODE REVIEW

**Comment by yorii** [comment]
I have a bit more code cleanup to do, but I'll get on it soon

**Comment by Sinestia** [comment]
Poor bacon, he'll have to deal with the merge conflicts if this is merged.

Though, this isn't a bad interim thing since we aren't quite sure when his lighting will be done, and this helps avoid those situations where lighting stops.

**Comment by yorii** [comment]
> Poor bacon, he'll have to deal with the merge conflicts if this is merged.
> 
> Though, this isn't a bad interim thing since we aren't quite sure when his lighting will be done, and this helps avoid those situations where lighting stops.

There shouldn't really be much of any merge conflicts, this adds a completely separate component for movable lights, it should be able to run in parallel with any changes to the regular lighting system, and all it takes is editing the value of a single atom var to make it use a different light system.

**Comment by utilbird** [comment]
#4597

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Breaks icon of objects on right-click menu. This used to happen on the lighting refactor I did, but was fixed somehow so if you can't figure anything out check there.

**Comment by yorii** [comment]
> Breaks icon of objects on right-click menu. This used to happen on the lighting refactor I did, but was fixed somehow so if you can't figure anything out check there.

Yeah it's a known issue that is mentioned in the original PR as well, but if there's a fix out there I'll see if I can find it.

**Pull request closed without merging**
