### PR TITLE
Adds cargonia uniforms to hacked cargo wardrobe

### PR DESCRIPTION
**Pull request by Jake-Wheal**
## About The Pull Request
This is a port of https://github.com/tgstation/tgstation/pull/48131 by RyverStyx. It adds a cargonian military style uniform to the hacked cargo wardrobe that is intended for times of war such as nations or when a conversion antag has swept through cargo. There are 6 uniforms in the vendor which is enough to give to all the cargo techs one.

## Why It's Good For The Game
Cargo always has a strong sense of patriotism so in times when they must stick together it would be cool if they could have a more military style uniform (and the original PR is on the things to port page so Ike thinks its good for the game as well).

## Changelog
:cl:Alt_Alpha9
add: Added cargonia military uniforms to the hacked cargo wardrobe
/:cl:

### CODE REVIEW

**Comment by SirBrown69** [comment]
This is really fucking cool

**Comment by Agameofscones** [comment]
image
I know this is just a port, but this sprite is uh, kinda hideous with the purple shoulder pads, though that's just my personal take and not objective

**Comment by Jake-Wheal** [comment]
> image
> I know this is just a port, but this sprite is uh, kinda hideous with the purple shoulder pads, though that's just my personal take and not objective

Some people on the original PR also had that impression but when you put it into the game you kinda need it to have that to stand out at all when all the pixels are smaller and surrounded by the rest of the game, especially when the cargonia uniform is so similar to the standard cargo jumpsuit

**Comment by AyyRobotics** [comment]
A resprite to a more of a military uniform with a yellowish camo color could help it stand out a bit more while keeping the "This is Cargo" message

**Comment by qwertyquerty** [comment]
paging @Naevii 

also conflicts

**Comment by Naevii** [comment]
> > image
> > I know this is just a port, but this sprite is uh, kinda hideous with the purple shoulder pads, though that's just my personal take and not objective
> 
> Some people on the original PR also had that impression but when you put it into the game you kinda need it to have that to stand out at all when all the pixels are smaller and surrounded by the rest of the game, especially when the cargonia uniform is so similar to the standard cargo jumpsuit

I think we as spriters try to avoid such linearts on those arm pads. 

I see two ways for it. 
Either change entirely cargonian suit to make it stand out more. 
Or replace purple outline on the arm pads with matching orange

Edit. Yellow and purple conflict a lot with each other and are not cohesive. I would stick to warm colors such as yellow, orange, brown. And try to shift away from purple

**Comment by Naevii** [comment]
Sprite looks okay after the changes

**Comment by PowerfulBacon** [comment]
what does it look like in game?

**Review by qwertyquerty — APPROVED** [review]

**Comment by qwertyquerty** [comment]
Fix conflicts

**Comment by ike709** [comment]
Fix conflicts and preferably make the sprites not ugly I'll merge. Marking stale until then.

**Pull request closed without merging**
