### PR TITLE
Qlighting

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## Todo
 - [x] Update to master
 - [x] Test on master version
 - [ ] Remove references to affecting lights on turf, instead make it a number that we add and subtract to.

## About The Pull Request

Its like lighting but its q.
Basically my lighting PR but with shadows ripped out and light sources are only visible if you can see the source. This works well only for light sources that have an extremely small radius.

Right clicking on an object shows fine, the light sources are smooth and at least 5% less laggy. etc. etc.

Fires are beautiful, bullets are beautiful, Glowsticks are beautiful, everything is beautiful.

https://user-images.githubusercontent.com/26465327/129238446-dcedd463-2b01-4124-bb3c-41ba3a62bc20.mp4

## Why It's Good For The Game

Much less intensive than the current lighting system.

## Changelog
:cl:
refactor: Significant lighting refactor that makes small radius lights use a more efficient method of lighting.
del: Deletes the factory away mission code.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
me no understand

**Comment by PowerfulBacon** [comment]
cool?

**Comment by PowerfulBacon** [comment]
uhhhh fuck I want to just rip the factory out entirely

**Comment by ike709** [comment]
christ the commits

**Comment by Sinestia** [comment]
> 
> 
> uhhhh fuck I want to just rip the factory out entirely

The actual away mission was removed awhile ago, the supporting .dm file was just left in by mistake I believe

Wouldn't hurt anything to rip it out, made an issue awhile ago

**Comment by PowerfulBacon** [comment]
This worked really well, but some things are way too big and theres a light speed debug verb available to all.

**Comment by PowerfulBacon** [comment]
image

**Comment by PowerfulBacon** [comment]
image
(Vis contents most likely)

**Comment by PowerfulBacon** [comment]
Apart from hard dels this works fine

**Comment by ike709** [comment]
Fix the harddels then 😎

**Comment by qwertyquerty** [comment]
qwerty lighting 😎

**Comment by PowerfulBacon** [comment]
I am very close to removing all lag from light sources even when used on all station lights.
https://cdn.discordapp.com/attachments/565330972707651584/883446103243116584/Desktop_2021.09.03_-_21.18.45.02.mp4

After:
https://cdn.discordapp.com/attachments/565330972707651584/883447501921873970/Desktop_2021.09.03_-_21.24.38.03.mp4

**Comment by ike709** [comment]
Now that supercruise is largely done for the moment, how's this going?

**Comment by PowerfulBacon** [comment]
its going nowhere pretty much

**Pull request closed without merging**
