### PR TITLE
[MDB IGNORE] Replace PDAs with tablets

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

PDAs are removed in their entirety.

All function of cartridges has been moved to storage disks with pre-installed programs (notekeeper, messenger, etc) per-job.

All crew start with a PDA-subtype tablet with their relevant storage disk and programs installed.

**SPRITE CREDIT: @Pirill**
Tweaks by @PestoVerde322 

### Things to address in later PRs

- ~~Curator Newscaster app (this will be another PR, it requires porting the newscaster to TGUI)~~ Done, see #7779
- Chat Client, NIRN, and other apps with very wide layouts should be rewritten to switch to a vertical form factor on PDAs
- ~~TGUI should update instead of closing and reopening a window per-program.~~ (#8639)
- Lifeline needs to be nerfed
- Nerfing the health integrated scanner is probably a good idea, but it will likely be part of a larger med rework.
- The mime emoji menu should have a corresponding text box that matches the emoji input, and allows inputting emoji text codes.
- It would be nice if there was a photo management app that would allow you to scan and save photos, then attach them to messages - this would also apply to silicons
- Tons of NTChat improvements
     - Chat Client right side is WAY too large
     - UI should be reworked on PDAs
     - You can message password locked channels and also view them by enabling Admin Mode..
     - Scientist has Admin mode for some reason?
     - chat client log save should support hitting enter (this is actually an issue with deprecated use of 'keyCode' and is a TGUI issue)
- ~~Rewrite the message monitor in TGUI, readd the fake messaging, add emoji support, improve the photo support.~~ (#8094)

### Ports

- https://github.com/tgstation/tgstation/pull/53996
- https://github.com/tgstation/tgstation/pull/57351
- https://github.com/tgstation/tgstation/pull/59180
- https://github.com/tgstation/tgstation/pull/65035 (only the multi-access tweaks)
- https://github.com/tgstation/tgstation/pull/65942
- https://github.com/tgstation/tgstation/pull/65755
- https://github.com/tgstation/tgstation/pull/66334
- https://github.com/tgstation/tgstation/pull/66358
- https://github.com/tgstation/tgstation/pull/66367
- https://github.com/tgstation/tgstation/pull/66376
- https://github.com/tgstation/tgstation/pull/66434
- https://github.com/tgstation/tgstation/pull/66443 (drastically improved)
- https://github.com/tgstation/tgstation/pull/66470 (this removes roundstart tablets, bad PR title)
- https://github.com/tgstation/tgstation/pull/66921
- https://github.com/tgstation/tgstation/pull/67057
- https://github.com/tgstation/tgstation/pull/67164
- https://github.com/tgstation/tgstation/pull/67223
- https://github.com/tgstation/tgstation/pull/67315
- https://github.com/tgstation/tgstation/pull/68171
- https://github.com/tgstation/tgstation/pull/68206
- https://github.com/tgstation/tgstation/pull/68355
- https://github.com/tgstation/tgstation/pull/69498

### Additional BeeStation changes

- Added the spam cartridge rework
- Improved the ringtone setting code a lot
- Added themes to the Settings app
- Renamed Hardware Configuration to Settings
- Heads start with secondary ID slots installed
- Improved UX with Imprint ID and the imprinted name fields
- Added the old default ringtones (clown = honk, etc)
- Sprites remain the same as the old, plus some custom overlays provided by @Pirill 
- Made the note scan function actually work like it used to
- Fixed uplinks
- Reworked program initialization so that `computer` isn't null.
- Added cartridges and PDAs for jobs that we have and TG doesn't
- Detomatix works like it used to
- Eject Pen verb was copied over since people depend on it
- Actually copied over the description and custom notes for each PDA
- Resized windows to make more sense
- Reworked radar apps on PDAs
- Chameleon PDA actually works
- The identifier module (PDA-YourName (Job)) actually has a prefix, and actually updates when it should
- Sending photos actually shows the (Photo) button in chat
- Emagging has a cool console popup and changes the OS theme to syndicate
- The mime has a custom emoji entry TGUI
- Added general info to medrecords
- The physical scanner operates using attack instead of rclick, plus atmos and rad scanners were added to the app
- Photo scanning provides feedback
- Hitting "Reply" from chat doesn't close the app you have open and then open the messenger, instead, it opens the app in the background.
- The AI and pAI messengers open directly to the app instead of opening a useless tablet menu with one button
- AI and pAI tablet menus no longer erroneously show the flashlight controls.
- A runtime introduced by https://github.com/tgstation/tgstation/pull/66358 was fixed
- Fixed the server error sound
- Silicons can actually attach images
- Added an image selection TGUI
- Improved the image descriptions, fixed a bunch of bugs with them
- Added back the `CART/DISK_REMOTE_CONTROL` (remote airlock control) for nukie PDAs
- Scanning papers stores a copy of the paper, and then shows the paper UI instead of trying to strip HTML and all that wacky stuff.
- The notekeeper app is less stupid and is a full text area instead of a single-line input combined with a loop between act and ui_data
- Re-added the ore silo logs, made a separate cargo tech cartridge that doesn't have access, only the QM does.
- Added a Log Viewer program that can view saved NTChat logs as well as view/download the ore silo logs.
- Fixed modPC visible_messages
- Status Display app now has alert images
- CMO cartridge has DISK_MED properly
- Added auto updating
- Science PDAs start with signaller hardware
- Cartridges can be hotswapped
- Added cartridge insert sound
- Added the PDA auto-update from #7253 
- Sending photos properly shows in the receiving client's "Show Messages" view.
- HoP starts with ID modification, crew manifest, and job management apps
- Emojis display properly inside the View Messages panel
- Renamed more references to cartridges
- Improved some UI handling of the View Messages panel and removed the quotes and italics from said menu.
- Fixed AI messenger job names not using JOB_NAME defines
- Fixed pAI messengers not updating the name properly

## Why It's Good For The Game

https://github.com/BeeStation/BeeStation-Hornet/discussions/7458

PDAs as they are use bad ancient href browser and look absolutely terrible, and also have extremely dated code.

Tablets can do almost everything PDAs can, so this PR merges them into one, adding a subtype of tablet with pre-installed programs for messaging.

This also replaces cartridges with storage disks that come pre-loaded with the programs needed for said job.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

**I have tested this PR extensively, anything that is not done I expect is working as expected.**

THEMES!!!
image

NtOS Hackerman
image

NtOS Clown Pink (Comic Sans Edition)
image

Retro
image

**Thinktronic Classic**
image

The first testing screenshot
image

Janitor app
image

All PDAs and their carts

image

image

image

</details>

## Changelog
:cl:
del: Removed PDAs.
del: Removed round-start backpack tablets.
refactor: Due to a buyout and massive restructuring of Thinktronic Systems, all crew now start with tablets containing pre-installed programs for messaging, and programs for tasks previously done by PDAs.
tweak: PDA sprites have been slightly changed to account for the new program overlays. Wide PDAs have normal sized screens, and PDAs start off with a black screen.
add: Added themes to tablets in the Settings app.
tweak: Renamed Hardware Configuration to Settings.
code: Improved tablet flashlight UI interaction with cyborg code.
admin: Added logging to PDA bombs.
tweak: Brig physician now starts with a cartridge.
add: Added a locator app for janitors to find mops, cleanbots, and janicarts with.
fix: Improved ModPC behavior with sechuds showing the wrong HUD.
tweak: You can now use holochips directly on a PDA/tablet to insert credits to the ID inside.
tweak: Tablet flashlight now uses movable lighting instead of jumping around
tweak: Tablets can be used while inside lockers.
code: Changed tablet program access requirements to support lists.
code: Added an emoji entry TGUI interface. For use with the mime PDA.
add: Emagging a modPC now opens a console window with flavor text and sets the theme to syndicate.
fix: Fixes PDA sent photos opening an undersized window.
tweak: Cyborg integrated tablet now has a button background.
tweak: AI now has a small integrated tablet only for sending messages.
tweak: Added an improved photo selection TGUI menu, mainly for use by silicons.
fix: Photos now describe their dimensions properly.
fix: Photo descriptions no longer randomly place periods around.
fix: Photos can no longer describe invisible things.
add: Nukie tablets now start with the Remote Airlock Control program, for remotely interfacing with the infiltrator's blast door.
tweak: Regular cargo techs no longer have the Ore Silo logs in their PDA Cartridge. It's now locked to the QM.
add: Added a new Cargo Technician cartridge with its own icon.
add: Added a Log Viewer program for viewing ore silo and NTChat logs on the filesystem.
fix: Modular computers now correctly show visible_messages to the user if they are holding it.
del: Removed the messaging console's system message capability.
add: The Status Display modPC app can now update status alert images.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I haven't seen the changes TG made to these UIs so some or all of these light be met already which is good, but I think these should be met in order to have quality TGUI PDAs. (Current modPCs need a bit of work. They are 90% of the way there but lack a bit of polish)

UI needs to be updated to be embedded rather than create new windows. Will require updating ui_data of tablet UIs. This means it won't close and open new UIs when you change programs.

UI needs to have a consistent resolution. Different apps should not resize the PDA.

PDA background colour functionality should remain.

All current features of PDA should be retained.

Some kind of hardware should determine what programs are accessible. (Cartridges)

Powerful tablet programs like the suit monitor should not be accessible in PDAs.

Retain current sprites, make them more of a compact phone window rather than a huge tablet that covers half the screen

**Comment by dwasint** [comment]
blessed pr

**Comment by Crossedfall** [comment]
I prefer the PDAs, if I'm perfectly honest. It feeds more into the future-retroism aesthetic. Tablets by their nature are visually boring and sterile.

**Comment by itsmeow** [comment]
the item sprites will stay the same

I will be adding the background color function back and more personalization options

**Comment by Crossedfall** [comment]
I'm aware that the pda sprites aren't changing. I'm referring entirely to the ux.

**Comment by CydiaLamiales** [comment]
Does the notekeeper app stay?

**Comment by itsmeow** [comment]
Yes, this adds a notekeeper app to tablets.
The paper scanning functionality is not yet added, but I will be porting more additions from TG, which includes that feature.

**Comment by itsmeow** [comment]
Okay so, important note

**You won't be able to set ANY arbitrary color as your background**

I have to do a list of presets, because TGUI and SCSS do not like dynamic coloring. At all. But, your PDA will still be personalizable!

**Comment by itsmeow** [comment]
@PowerfulBacon considering this PR is mostly done, I will address your points here:

> UI needs to be updated to be embedded rather than create new windows. Will require updating ui_data of tablet UIs. This means it won't close and open new UIs when you change programs.

I will do this in another PR. It requires massive changes.

> UI needs to have a consistent resolution. Different apps should not resize the PDA.

Same as above.

> PDA background colour functionality should remain.

Somewhat implemented, you can pick most colors through preset themes. It's not feasible to allow any color.

> All current features of PDA should be retained.

Implemented. The only removal after this PR would be the curator newscaster, which needs to also be addressed in a separate PR, because we lack two TG PRs that ported the newscaster to TGUI in the first place.

> Some kind of hardware should determine what programs are accessible. (Cartridges)

Straight from the parent PR. TG did end up removing these and replacing them with "portable job disks", and removing most redundant cartridges (instead opting for ID-access for most things), but I don't think we should port that quite yet.

> Powerful tablet programs like the suit monitor should not be accessible in PDAs.

This has always been a thing in modPCs. Tablet's can't use certain laptop-only programs, plus most programs are ID-locked so only those with relevant access can download them.

(Aso, there is no app for monitoring suit sensors in tablets, the closest thing is Lifeline which is a pinpointer and only available to command/med)

> Retain current sprites, make them more of a compact phone window rather than a huge tablet that covers half the screen

Done, plus added the tablet program overlays. Thanks @Pirill

**Comment by PowerfulBacon** [comment]
I'm fine with everything being basically ignored, but the window UIs should be consistent. Any of the radar apps can be dumbed down for PDA and made into text versions, with the tablets remaining a viae upgrade if you purchase them instead.

**Comment by itsmeow** [comment]
You are asking me to rewrite every TGUI app to fit a tiny vertical form factor.

**Comment by itsmeow** [comment]
I can do it, but it should really be its own PR due to the sheer scale.

**Comment by PowerfulBacon** [comment]
Only ones that are reasonable to have on a PDA. They shouldn't have suit sensors and the radar apps

**Comment by itsmeow** [comment]
I am proud to announce the release of a new theme for NT-Thinktronic branded PDA devices.

The "Thinktronic Classic" theme has come to remind users of the foundations of Thinktronic Systems.

Now with the classic ability to set your own background color!

image

(ignore the typepath in the above prompt, I fixed it)

image

It feels just like 2467 again!

**Comment by itsmeow** [comment]
Radar apps have been tweaked on PDAs to not be so large.
image

I also made the sizing of the messenger app and notepad app consistent with the main menu, meaning less frustrating UX.

**Comment by Isy232** [comment]
> I prefer the PDAs, if I'm perfectly honest. It feeds more into the future-retroism aesthetic. Tablets by their nature are visually boring and sterile.

I like the future retro aesthetic as well, however as of now almost all of the future-retro interfaces have been fully replaced. The PDA is the weird one out right now, being the only retro interface in a sea of sleek, modern ones.

I'd be down for a rework of most interfaces such as APC's, security camera consoles, air alarms, basically everything to change their aesthetics to being more retro, however as of now PDA's are just the weird odd ones out.

**Comment by itsmeow** [comment]
https://youtu.be/Fn0gp77QFBE

**Comment by itsmeow** [comment]
Video showing ModPC emag
https://www.youtube.com/watch?v=cxV4Ur4nfJg

Video of emagging other things
https://www.youtube.com/watch?v=y-pwvwduzgA

**Comment by itsmeow** [comment]
New image selection TGUI.
image

New airlock control
image

**Comment by itsmeow** [comment]
New Log Viewer program. Also supports NTChat logs (these were literally unviewable before!).

image

image

image

Can locally backup logs with the download button, (it prompts for a filename)

image

**Comment by itsmeow** [comment]
Alright, I've done everything I wanted to do. Anything else will just be fixes.

**Comment by itsmeow** [comment]
Ready for review.

**Comment by PowerfulBacon** [comment]
In my opinion the UI is a lot more annoying to use, since every button causes it to close and then open in a different location on the screen with a different resolution.
The order of the buttons is also extremely weird, the less important settings are above everything else.

Should be notepad, direct messenger, then the fluff stuff.
image

image
image
image
image
image

Something needs to be done about these UIs bouncing around the screen and changing sizes, preferably the modcomp code would be updated so that they can all be embedded into a commanding UI that opens the correct display.

Some other minor things:
image
These buttons extend too far, clicking on the right side of the screen causes them to open.

image
This doesnt seem to do anything.

Sprite looks very nice, I like that.

image
Can we change this top bar and scroll bar of the UI? It would look much better if there wasn't 2 top bars but im not sure if thast possible.

**Comment by itsmeow** [comment]
Scientist PDA doesn't start with the signaller module

**Comment by itsmeow** [comment]
Imprint ID is the "Update PDA Info" button from the old PDA.

It doesn't do anything because your PDA is not updated. Notice how when you try to click on it, it doesn't have a response when hovering (it's greyed out on the normal theme)

The top-down UI flows are necessary because the size of the "details" are variable, so you want the static stuff at the top so it's not affected by cumulative layout shift.

Putting the flashlight into the top bar would probably be more confusing than anything.

I can re-order the default programs, I suppose.

Once again the UI changes you want are huge and will need to be in a separate PR as this one is already huge.

**Comment by CydiaLamiales** [comment]
Here's a couple of things I've noticed : 
you can't quickly swap the PDA cartridges (now job disks)
the sound when ejecting/placing a job disk is replaced with the disk insert one (please return the old one)
you need to manually imprint the ID into the PDA
direct messenger doesn't display photos/emojis properly (emojis don't show at all, photos show only on the sender's side)
image
image
Status Display app lacks functionality
image
compared to the old one
image
Some job disks lack descriptions, like FRAME and Detomax 
FRAME and Detomax are still referred to as "cartridges" in the uplink menu

**Comment by itsmeow** [comment]
Idea: Move the settings app out of the apps menu and into a small gear icon by the flashlight settings

**Comment by Chessus** [comment]
Wow this is cool! Great work!

**Comment by Crossedfall** [comment]
Somehow this PR keeps breaking checks. Need to cycle it to get it going again

**Comment by PowerfulBacon** [comment]
> I disagree with making the scrollbar extend up, the power button is supposed to occupy that space and I think it looks better how it is.

I meant it should be styled rather than default, but its fine

**Comment by itsmeow** [comment]
Styling the scrollbar to match the Thinktronic color is... not really plausible. It uses a lot of SCSS variables which are static, and IE doesn't support CSS variables so I'd have to hardcode it somehow.

**Comment by itsmeow** [comment]
Requested changes implemented.

**Comment by itsmeow** [comment]
image
pAI messengers show as this

**Comment by itsmeow** [comment]
image
some minor issues

overflowing + apostrophe rendering wrong

**Comment by itsmeow** [comment]
image
fixy

**Comment by itsmeow** [comment]
image
yay

**Comment by itsmeow** [comment]
image
UI fixes

**Comment by itsmeow** [comment]
Labels weren't updated, but it was TM'd again and this is how I found those bugs. All fixed now.

**Comment by JohnFulpWillard** [comment]
> (Current modPCs need a bit of work. They are 90% of the way there but lack a bit of polish)

Don't overestimate us. there's a lot of work to be done lol

**Comment by PowerfulBacon** [comment]
yea, I know you are correct

**Review by ike709 — APPROVED** [review]
YEET

**Pull request merged**
