### PR TITLE
ports tgui cloning console from cit, removes maint cloning code copypasta

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

ports Citadel-Station-13/Citadel-Station-13#14606
makes cloning console board retain cloning records
experimental cloning is no longer a copypasta of cloning
experimental cloning cannot retain records and may have unintended behaviour as intended

unknown

## Why It's Good For The Game

yes

## Changelog
:cl: SandPoot, Jupyterkat
add: Adds a fancy TGUI interface for the cloning computer.
add: Cloning console boards now retain records
del: Destroys the old cloning interface.
tweak: Alt-Click now removes disks from the cloning computer.
refactor: Replaced way too much code for the cloning computer.
refactor: Cloning scan's implant now outputs a list if desired.
refactor: Experimental cloning is no longer a copypasta of cloning
/:cl:

### CODE REVIEW

**Comment by KubeRoot** [comment]
Does the new UI show mutations on the scanned data? Currently it can be useful for geneticists, since you can look for mutations you're researching in the cloning machine before bruteforcing/scanning random people.

**Comment by bloons3** [comment]
The fact that there is a TGUI cloner UI speaks volumes as to the current state of Bee

**Comment by jupyterkat** [comment]
currently untested for non-body-only clones, needs testmerge

**Review by utilbird — APPROVED** [review]

**Comment by SandPoot** [comment]
cool

**Pull request merged**
