### PR TITLE
[CRITICAL BUGFIX] You can no longer get stuck upon late join: Antag Rollers edition

### LINKED ISSUE #9399: [Bug]: lobby area stuck bug
### BYOND Version

_No response_

### Round Date

2023/07/12

### Round ID

44877

### Test merges

_No response_

### Describe the bug

```js
runtime error: Cannot read null.len
 - proc name: remove from single hud (/datum/atom_hud/proc/remove_from_single_hud)
 -   source file: code/datums/hud.dm,105
 -   usr: [REDACTED] (/mob/dead/new_player)
 -   src: /datum/atom_hud/alternate_appe... (/datum/atom_hud/alternate_appearance/basic/everyone)
 -   usr.loc: the plating (8,174,1) (/turf/open/floor/plating)
 -   call stack:
 - /datum/atom_hud/alternate_appe... (/datum/atom_hud/alternate_appearance/basic/everyone): remove from single hud(HUMAN_NAME (/mob/living/carbon/human), [REDACTED] (/mob/dead/new_player))
 - /datum/atom_hud/alternate_appe... (/datum/atom_hud/alternate_appearance/basic/everyone): remove from hud([REDACTED] (/mob/dead/new_player))
 - /datum/atom_hud/alternate_appe... (/datum/atom_hud/alternate_appearance/basic/everyone): remove from hud([REDACTED] (/mob/dead/new_player))
 - /datum/atom_hud/alternate_appe... (/datum/atom_hud/alternate_appearance/basic/everyone): remove from hud([REDACTED] (/mob/dead/new_player))
 - /datum/atom_hud/alternate_appe... (/datum/atom_hud/alternate_appearance/basic/everyone): unregister mob([REDACTED] (/mob/dead/new_player), 0)
 - [REDACTED] (/mob/dead/new_player):  SendSignal("parent_qdeleting", /list (/list))
 - qdel([REDACTED] (/mob/dead/new_player), 0)
 - [REDACTED] (/mob/dead/new_player): transfer character()
 - [REDACTED] (/mob/dead/new_player): create character(1)
 - [REDACTED] (/mob/dead/new_player): AttemptLateSpawn("Medical Doctor")
 - [REDACTED] (/mob/dead/new_player): Topic("src=\[mob_1129];SelectedJob=Me...", /list (/list))
 - [REDACTED] (/client): Topic("src=\[mob_1129];SelectedJob=Me...", /list (/list), [REDACTED] (/mob/dead/new_player), null)
 - [REDACTED] (/client): Topic("src=\[mob_1129];SelectedJob=Me...", /list (/list), [REDACTED] (/mob/dead/new_player), null)
 - [REDACTED] (/client): Topic("src=\[mob_1129];SelectedJob=Me...", /list (/list), [REDACTED] (/mob/dead/new_player), null)
 - 
```
This appears to be where the lobby stuck bug happens.
It seems this is because a signal qdeling tries to qdel signal itself, causing recursive issue? I am not quite sure about this.

### PR DESCRIPTION
**Pull request by HowToLoLu**
## About The Pull Request
This resolves the longstanding issue of people being trapped in the lobby as a living mob.

The title of #9399 describes the issue- however it details a runtime that seems to be possible happen when joining (so this by no mean closes that)

**A great deal of thanks to `potentiallytaylor` on the bee-cord for helping find the cause of this issue!**

## Why It's Good For The Game
Other people shouldn't suffer because someone didn't roll an antag they wanted.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
Apparently, all you need to do is this to block anyone from making it on the shuttle:

Just put a bunch of naked people on the shuttle :trollface:
image
**Note: All occupants must be unbuckled, and on top of a seat for this to happen.**

And the fix? ~~Removing an `if` statement~~ Moving some code around which results in even simpler code, because sanity checks are already handled lower down.

This is a video of the fix working in action:

https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/54ce89d6-7e3e-4bdd-939c-86b63a32751c

</details>

## Changelog
:cl:
fix: You can no longer get stuck in the lobby upon latejoining if someone unbuckled and stayed on top of a seat.
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — APPROVED** [review]
Code seems fine and testing seems adequate

**Comment by Crossedfall** [comment]
CL entry doesn't actually describe the change. Please update it before the merge.

**Review by EvilDragonfiend — CHANGES_REQUESTED** [review]
Buckle parameter is useless now. Do something there.
`if (buckle && isliving(M))` this if condition will be still wanted

**Comment by HowToLoLu** [comment]
> Buckle parameter is useless now. Do something there. `if (buckle && isliving(M))` this if condition will be still wanted

`isliving` is checked by the chair itself already, making it a pointless check. I'm currently looking into refactoring the code since at the moment, you never even needed all seats to be full to have this happen; which means the game isn't even prioritizing seats properly.

**Comment by HowToLoLu** [comment]
Okay, I'm leaving the refactor for later since this bug can get annoying quick.

@Crossedfall is the CL good now?

**Review by EvilDragonfiend — APPROVED** [review]

**Review by itsmeow — APPROVED** [review]

**Pull request merged**
