### PR TITLE
Bulk Fixes 2: Electric Boogaloo

### LINKED ISSUE #1880: advanced airlock controller flooding chat as ai
## Reproduction: click on advanced airlock controller as ai

3eff5c7ee30d1c59ad5b1c2361a59cba

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/91548159-advanced-airlock-controller-flooding-chat-as-ai?utm_campaign=plugin&utm_content=tracker%2F120077027&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F120077027&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #2017: Advanced airlock controller broke for AI
Issue reported from  Round ID: 17453 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1524

Probably old issue, AI get "too many clicks" message when trying to interact with it.
Also the one in AI sat (meta) is badly configured.

### PR DESCRIPTION
**Pull request by ike709**
Here we go again. 19 PRs of fixes/improvements plus also holodeck restricted program logging.

You can find a list of PRs here: https://github.com/BeeStation/BeeStation-Hornet/projects/2#column-9770876

## Changelog
:cl: Tons of TG coders and one or two Yogs coders, with a bit of effort from ike709
add: Holodeck plasmaflood is now logged. We can't have nice things.
fix: Airlock controller no longer spams AIs.
fix: A bunch of code cleanup.
add: TGUI turret control panel.
add: Intercoms now tell you about the speak-into feature when you examine them.
fix: Intercom code cleanup.
fix: Various minor TGUI issues fixed.
add: TGUI tachyon-dopper array.
tweak: You shouldn't actually notice this difference, but the random roundstart books you see on bookshelves are now only an illusion until you interact with the bookshelf.
fix: Various runtime fixes.
add: You can now rip your own arms off. ;)
fix: Coders will no longer be spammed by lone ops alerts while on their local test server.
/:cl:

Fixes #1880 
Fixes #2017

### CODE REVIEW

**Comment by TotallyNotChief** [comment]
>TTVs still not fixed

**Comment by ike709** [comment]
TODO: Fix map issues

**Comment by ike709** [comment]
Maps fixed.

**Comment by ike709** [comment]
Seems fine.

**Pull request merged**
