### PR TITLE
Removes donutstation

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Removes donutstation from the game.

## Why It's Good For The Game

It's not part of the rotation, it's not maintained, it's not updated. Corg will fill "the void" this causes just fine

## Changelog
:cl:
del: Removed donutstation.
/:cl:

### CODE REVIEW

**Comment by Effemu** [comment]
donut good :(

**Comment by Cenrus** [comment]
the donut escape shuttle can stay, right? It's one of the better escape shuttles

**Comment by PowerfulBacon** [comment]
might as well keep the shuttles since they are actually used

**Comment by Sinestia** [comment]
I disagree with what people are saying, I think it's fine to remove the shuttle.

 The shuttle list is fairly bloated, might actually be worth removing a couple in another PR (who knows the difference between delta meta and box shuttle being buyable.)

 You still have Cere's shuttle if you want a really big shuttle, which is also (imo) prettier too. Also corg's shuttle. In practice I see people buy them more than donut's as well. 

Not the biggest deal if it stays ofc

**Comment by Archanial** [comment]
> 
> 
> might as well keep the shuttles since they are actually used

Where are they used?

**Review by utilbird — DISMISSED** [review]
Less map maintenance for me, more code reviews for thee

keep the shuttle though 😔

**Review by ike709 — DISMISSED** [review]
Whomever merges this needs to apply the config changes.

**Pull request merged**
