### PR TITLE
QoL Map Upgrades v2: Boxstation

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Engi maint had a strange atmos bug, so I snooped around to see how others overcame it. I came across a _nice_ pull request that I was a bit inspired by:
https://github.com/tgstation/tgstation/pull/50740

I incorporated the PR's theme into this rework, nice meta change.

**Boxstation**
- Huge facelift, decals and tiling
- Inspector Johnson is now in medbay
- Two tile firelock+firelock door combos removed. Get crushed less! Burn more!
- Fixed engi maint's atmos bug 
- Maintenance APC's and air alarms now fully removed
- Power grid improved somewhat
- AI is relocated south of upload!
- Grav gen is moved to engi maint.
- New random rooms!

**Pubbystation**
I forgot a single decal on a trash bin

## Why It's Good For The Game
Boxstation is like THE lowpop map and it's really overdue for some TLC

## Changelog
:cl:
add: Boxstation now slightly better looking, more resistant to mice.
add: Boxstation medbay now gets its own Inspector Johnson. It’s time for mandatory inspection!
fix: Boxstation's engi maint is no longer bugged.
tweak: Boxstation AI relocated below the upload, center of station.
tweak: Boxstation grav gen relocated west of tcomms.
/:cl:

### CODE REVIEW

**Comment by jlsnow301** [comment]
Imgur album with some screen shots https://imgur.com/a/HePWtiS

**Comment by SomeAngryMiner** [comment]
nice.

**Comment by ghost** [comment]
did this fix the fact that you can destroy the entire power grid by cutting 1 wire.

**Comment by jlsnow301** [comment]
> did this fix the fact that you can destroy the entire power grid by cutting 1 wire.

the engi main side of me wants to just rewire the station entirely. I added some redundant wires in the last QoL fix, but it's still Box, the worst threat is mice

EDIT: Added more redundant wires and cleaned their directions up a little

**Review by St0rmC4st3r — CHANGES_REQUESTED** [review]
Do you realize that you have undone half the random maint with this PR? I mean, yeah, the AI being moved is a nice shake to the meta, but I would like to ask you to either expand/rework maint tunnels so that there would be the large random room and stuff or revert the gravgen part and put it elsewhere. (The first option would be very cool.)

**Comment by jlsnow301** [comment]
I did tile and retile maint a dozen times to fix the leak, so yes, I’m aware. I’m still not 100% sure where it was.
Gas mixer room below theater would need to remain or have the disposals setup (properly) removed, as it was just broken off previously

**Comment by VictorVow** [comment]
Don't delete random maint rooms to fit in your rework, simply shift them elsewhere or add new ones. 

Whilst you're at it can you change the 3x1 area between bridge doors to 3x3? Looks nicer with decals and fits the space better.

**Comment by jlsnow301** [comment]
Fine, this is on hold, will add random maints

EDIT: Added random maints. 

I didn’t delete them to fit the grav gen specifically- it was for the atmos issue

**Comment by jlsnow301** [comment]
Really making me want to redo sec here also but just going to cool it and make it a separate pr

**Comment by jlsnow301** [comment]
By adding random rooms I have now reintroduced the atmos bug to engi maint.

EDIT: Resolved

**Comment by jlsnow301** [comment]
> either expand/rework maint tunnels so that there would be the large random room 

Done + added new random rooms elsewhere in maint. There is now a 10x10 located ~somewhere~

>  can you change the 3x1 area between bridge doors to 3x3?

Done and done

**Comment by Coolsurf6** [comment]
Hey definitely better than removing Box.

**Pull request merged**
