### PR TITLE
[BOUNTY] More logging

### LINKED ISSUE #1424: Merge Bounties
Merge these items.
If unable to merge a specific item, please explain why.
You will still likely qualify for bounty.

https://github.com/tgstation/tgstation/pull/47802 Agent ID logging
https://github.com/tgstation/tgstation/pull/47802 Atmos tank logging
https://github.com/tgstation/tgstation/pull/47525 Specific logging of door bolting
https://github.com/tgstation/tgstation/pull/46333 Better grenade logging 
https://github.com/tgstation/tgstation/pull/46330 Tomato logging (seen 2x of them used to grief)
https://github.com/tgstation/tgstation/pull/45677 Logging of door crushing

### PR DESCRIPTION
**Pull request by Bastian0930**
# About The Pull Request
I've done what bloons asked for in his bounty issue.  I merged all required things for said bounty. However, the random name thing seemed needed for it to work. So I merged that too, as more of a requirement then a want. I still wanted it anyways, so it works out.

Closes #1424 , pay me bloons if this gets merged.
## Why It's Good For The Game
You know, logs are great! They allow admins to realise "hey that man shot a grenade in someones hand and it blew up what the fuck" instead of just banning the fucker who had it in his hand. Also, random names are nice due to how I can never think of one on the spot.
## Changelog
:cl:
add: The syndicate has loaded names onto the agent ID! By putting in no name, the ID will fabricate a random name!
admin: A lot of shit related to grenades, killer tomatos, and doors is now logged.
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
This should be atomized

**Comment by Bastian0930** [comment]
I mean I'm just doing what I was told to port, which was this. Not too familiar on atomizing shit, however.

**Comment by Bastian0930** [comment]
Resolved the merge error, I'll split it into another bounty in a bit. Got some stuff to do.

**Comment by Bastian0930** [comment]
We'll see if it works.

**Comment by Bastian0930** [comment]
SHOULD work now. Also, I'm using the browser cause my fucking desktop won't register that changes exist. Don't even know why, not tryna figure out rn.

**Comment by qwertyquerty** [comment]
Fix conflicts

**Comment by Bastian0930** [comment]
The other ones been merged, I'll readd it

**Comment by Bastian0930** [comment]
https://cdn.discordapp.com/attachments/605191081361014814/697237328103735347/unknown.png

What the fuck? This file didn't even exist at the time! AAAAAAAAAA

**Pull request merged**
