### PR TITLE
Full-auto firemode

### PR DESCRIPTION
**Pull request by Kmc2000**
## About The Pull Request

Original PR:
https://github.com/BeeStation/NSV13/pull/501

This PR adds a "full auto" firing system for guns with their automatic var set to TRUE. Click and drag to shoot all over the place.

## Why It's Good For The Game

https://i.gyazo.com/b5549ee907d69f6c354d924c5565ef37.mp4
(You can also drag your mouse around and the bullets go to where you shoot)

Also, stops people from getting rate-limited and kicked by the anti-spam protection for violating the per minute click limit by using fullauto.

## Changelog
:cl: Kmc2000
add: Ported full auto from NSV. Guns will continue firing at your cursor's location while you hold left click, assuming they have a full auto mode.
/:cl:

### CODE REVIEW

**Comment by Kmc2000** [comment]
We've had this on NSV for a little while now and it hasn't broken horribly

**Comment by MarkSuckerberg** [comment]
Asking from an outsider perspective, well, uhm... what's the differences between this PR and #1702?

**Comment by MarkSuckerberg** [comment]
Oh, it's a firemode, I should have looked at the code first. Disregard...

**Review by ike709 — APPROVED** [review]

**Comment by ike709** [comment]
Seems to work fine.

**Pull request merged**
