### PR TITLE
Disables chair ghost spinning, why we can't have nice things

### PR DESCRIPTION
**Pull request by mystery3525**
## About The Pull Request

Disables chair ghost spinning in CONFIG for default playing.

## Why It's Good For The Game

dreamseeker_K1onw7oEoJ

This is why we can't have nice things. We do not have the admin staff to be able to allow players to use these nice little features without abusing it.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Spinning chairs doesn't work on local, I forgot to take a screenshot but I checked.

</details>

## Changelog
:cl:
config: Disables ghost chair rotation by default, why we can't have nice things.
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
This is something that people rarely do, i've seen a few magician, mimes or curators try these gimmicks every once in a while(most of the ouijas are rather done when Wizards summon ghosts) and it's usually just to entertain or do something silly for a bit, the mime there didn't probably had the intention of "Spin to the right if you got murdered'' i've never seen it used to pinpoint towards a valid but rather i've seen it to create a small RP of "being haunted" or have a chair spin for a bit as random sillyness, idk why this needs to be removed it's a small feature that has enhanced RP from what i've witnessed that doesn't get abused like you think.

**Comment by PowerfulBacon** [comment]
I think instead the ability should have a longer cooldown and spin the chair around for a short while by a random amount. Maybe it should be an active/targetted ability.

**Comment by kiekatz** [comment]
aka how goon does it?

**Comment by ClownMoff** [comment]
Players having harmless fun is le bad... 😔

**Comment by PowerfulBacon** [comment]
I don't want to disable features because it was close to being abused one time, maybe it might get used to metagame an antag one time but this is removing it in 200 rounds for every 1 round where it almost reaches the point where it is considered 'abused'

**Comment by BarteG44** [comment]
"This is why we can't have nice things" *shows the nice thing as the reason*

**Comment by Tsar-Salat** [comment]
This is entirely able to be controlled by config. I do not see the purpose of this pr.

If it was an administrative issue, it will be handled by admins. If its a config issue, it will be handled by those with config access.

I think its moreso the former, in which case this should be a report, not a pr.

**Comment by PowerfulBacon** [comment]
I think I've said what needed to be said, if this becomes something to care about I'll flip the switch in the config

**Pull request closed without merging**
