### PR TITLE
Completely re-maps metastation medbay.

### PR DESCRIPTION
**Pull request by ghost**
🆑
add: Metastation: has a new Paramedic closet and office.
add: Metastation: Quarantine Blastdoors to medbay.
tweak: Metastation: Major tweaks to medbay and its surrounding area.
/🆑

Remaps the whole of medbay, this is a port of https://github.com/OracleStation/OracleStation/pull/1170

Requesting thoughts on:
*Reducing round start medbay supplies and remove the grenade building stuff from chemistry, to encourage chemistry to actually focus more on medicine.

This completely reworks the layout of metastations medbay from the ground up.

Descriptions: 

Medbay overall: Shows the connection of all pipes and wires
image
More spacious and less cluttered, it has quarantine blast doors added to it to all exits and windows out of medbay.

Auxiliary Storage
image
Only the CMO has access to the room. It has spare supplies, two medical hardsuits. It also has a closet with spare plasmaman tanks, along with a couple spare sets of plasmaman suit and helmet.

Breakroom
image
Its a break room, its a room you take breaks in.

Chemistry
image
Less isolated, hopefully, and without grenade parts that may hopefully encourage on making medicine instead.

Genetics
image
Nothing significant, besides less public.

CMO Office
image
Less isolated, and more secured. Has privacy shutters and a button to activate the quarantine blastdoors, needs CMO access.

Cryogenics
image
Less cluttered and a bit more secured.

Limb Grower
image
A limb grower to encourage surgery over cloning.

Medbay Lobby
image
Has the security outpost moved there to be less isolated and forgotten.

Morgue
image
More isolated, otherwise nothing significant.

Reception
image
A more dedicated area for doctors to stay at, it has buttons controlling both of the airlocks.

Restroom
image
A restroom in medbay, for restroom usage. Anyone can enter it.

Medbay Storage
image
One extra doctor locker, but with less medkits.

Surgeries
image
Two surgery rooms with the limb grower room in the middle.

Treatment Center
image
Has the usual sleeper, along with three stasis units.

Virology
image
Less isolated and more attached to medbay. The atmospheric system its connected to could have any tank attached to it to poison the virology atmosphere.

Waiting Area
image
A big waiting area for patients or visitors waiting for patients.

Paramedic
image
Has their own office. With a standard medical locker.

Maintenance
image
image
image

### CODE REVIEW

**Comment by LastCrusader105** [comment]
its nice, I like the spare plasmeme suits

the scrubbers in viro look like they are layer 1 and pipes look layer 3 so they dont connect

**Comment by ghost** [comment]
> the scrubbers in viro look like they are layer 1 and pipes look layer 3 so they dont connect

You're right, i fixed it.

**Comment by LastCrusader105** [comment]
the old medical for comparison
Meta Medical

**Comment by ghost** [comment]
I'm requesting a test-merge on this before full out merging.

**Comment by LastCrusader105** [comment]
@BeloneX where is the plasmemes shower in cloning?
dont make me do a PR for it

my bad you already done it
though just a plasmeme thought, i hate those glass door things cause they never strip me inside the shower room, thats if they even strip me so i go to strip my stuff and door closes and have to start all over again, you think id of learnt to drag my body in with me but in my panic i forget

**Comment by ghost** [comment]
> @BeloneX where is the plasmemes shower in cloning?
> dont make me do a PR for it
> 
> my bad you already done it
> though just a plasmeme thought, i hate those glass door things cause they never strip me inside the shower room, thats if they even strip me so i go to strip my stuff and door closes and have to start all over again, you think id of learnt to drag my body in with me but in my panic i forget

Clicking on a windoor keeps it open.

**Comment by LastCrusader105** [comment]
It stays open? Damn learn something new all time

Not that I get any say in the matter but I agree to test merge, it looks good but you never know till players get hands on it

**Comment by LastCrusader105** [comment]
@BeloneX is it manual APC or automatic?

**Comment by ghost** [comment]
> @BeloneX is it manual APC or automatic?

The APC's are all automatically named.

**Comment by LastCrusader105** [comment]
> > @BeloneX is it manual APC or automatic?
> 
> The APC's are all automatically named.

rest of metastation is manual though, personally i think while time consuming its worth the effort cause you can do some neat tricks with manual
also i was playing a round earlier where my friend was in crit and I realised, your "trauma center" is quite far back, maybe a idea to switch staff area with trauma center?

**Comment by heepox** [comment]
viro needs 2 viro stations and viro clothing vendor (where are the monkeys). chef has mourge access so he needs a way in. storage missing medical clothing vendor. CMO office is propably missing a console or two and the medical hardsuit SSU that is allways in his office on every map. Surgery is missing observation room.

Just move moruge so it has a door to main hallway. also where do mule bots drop their crates off at?

**Comment by ghost** [comment]
>(where are the monkeys)

image

>also where do mule bots drop their crates off at?

image

**Comment by heepox** [comment]
just noticed... sec officer assigned to medical spawns where?

**Comment by ghost** [comment]
> just noticed... sec officer assigned to medical spawns where?

image

**Comment by LastCrusader105** [comment]
@BeloneX wheres vector? I didnt pay £5 a month for 9 months for nothing
good job though

**Comment by ghost** [comment]
> @BeloneX wheres vector? I didnt pay £5 a month for 9 months for nothing
> good job though

Done.

**Comment by Sarchutar** [comment]
Either i am completely blind or the protolathe/techfab is missing.

**Comment by ghost** [comment]
> Either i am completely blind or the protolathe/techfab is missing.

Oh yeah, you're right.

**Comment by ModDownloading** [comment]
This seems to remove a lot of random maint rooms, maybe the area near viro could get some of those back?

**Comment by LastCrusader105** [comment]
> This seems to remove a lot of random maint rooms, maybe the area near viro could get some of those back?

I thought that as well when i first seen it but if you look closely you can see most are still there, medical is now slightly further past the abandoned bar and belone as taken the space tiles that was there, by my count we are minus one random room (unless the side bar is blocking more) But I think it has a better more random layout now

**Comment by Fronsis** [comment]
Alright, Medbay main reporting in for feedback:

Feedback on: 

-**Aux Storage:** Good stuff, while i've always enjoyed the idea of having spare supplies this won't encourage much interaction with Cargo (althought nowadays we don't have any, since most players knows how to do synthflesh factory instead of ordering synthflesh boxes like on the early days, i personally like the idea and the plasmeme suits are 100% needed and i appreciate them A LOT

-**Breakroom** it's just a breakroom, can't go wrong on that 

-**Chembay:** I like the fact that's less isolated, but i don't see the locker with the plumbing stuff, maybe put an extra box of beakers and, 100% agree on granade casings gone, in any case they should be under  Aux Storage or something only the CMO can access so at least they have to ask their boss before making a random nade.

-**Genetics**: It's fine for me, nowadays we're encouraging more tend-wound -> defib meta rather than straight cloning, it's a little far for dragging bodies but eh could get used to it, monkeys have a pool? based.

-**CMO Office:** Eh, i think i feel it's way more big since it's so.. in the middle, i just like a layout like Delta where it's not in the way and you still have plenty of vission, i could get used to it

-**Quarantine Blast doors for medbay**: Absolutely based and it's 100% needed, sometimes with the door remote control you can't lock everything to avoid a virus getting out and people start hacking the doors/asking AI to open this is 100% needed for Medbay specially since we have quite a variety of virus that needs different treatments.

-**Cryogenics:** Good change, really like the details of the windows i really like this idea of having the Doctors be the one in control on what's done instead of tiders running around taking stuff to cloning, breaking into storage, using cryo without need, let the doctors do their job.

-**Limb Grower:** I usually when i decide to upgrade medbay with extra stasis beds and autodocs i always add one because it's a neat machine that's barely used

-**Sec outpost:** On one side i like he fact that they have a neat vision around the hallway but it might be.. too far from medbay? Bah, if we compare it with all the security offices from the other areas this one seems like it would be way more prevalent to stay than the others (Science it's also usually a good one to stay as well, althought most of secs tend to patroll or just stay on brig would be interested on security officers feedback

-**Reception** Just today i was talking with a friend and we agreed that there's not enough places for the docs to just.. wait in besides the two chairs and the crew monitor machine, this at least have enough space for more people to chill and not just... stand on one tile in the middle of medbay.

-**Restroom** Eh, not a big fan of it, seems kinda pointless, for showers we already have the ones that are around near the stasis bed and chembay to be honest i would rather prefer this to be repurposed somewhere else, not necessary in that place for a **plumbing area**

-**Medbay storage** Seems fine, and having less medkits at least makes the CMO go to the aux storage to drop new ones so.. i agree, that extra locker always come in handy, as long as we have enough Med-huds for every doctor-paramedic

-**Surgery rooms**: Hmm i'm not sure about two surgery rooms... this would lead up for a revamp for delta as well depending on how much is needed, but yeah sometimes on 70pop medbay surgery gets SUPER cramped so.. i can see this working.

-**Treatment center**: I like the layout, it has even extra space to add more beds/sleepers i would prefer if the top one had walls though since in the current ''medbay meta'' having the wall defib mount it's a MUST for the sleepers.. So think about that. 

-**Virology**:I will let viro mains speak out about it, althought i personally always liked it to be isolated and far since.. you know virology and having the view to the space was always a nice touch.

-**Waiting area**: While i understand the idea and it's suits for aesthetic i think it takes a lot of space that could be used for somewhere else, this could be nice for a HRP server but for MRP/LRP doubt we have that many people using the chairs in fact i would bet doctors while quickly shift towards deconstructing and doing plumbing there, i'll speak about placement in a bit.

-**Paramedic**: Love the idea they definetly need their space and own access to their basic supplies without affecting the doctor stuff.



Now about the **Placement**

As i mentioned earlier we definetly need a **plumbing area** that's not in the way and it, being isolated depends.. if it's kinda in a corner or near chembay that would definetly finish killing off that bad ''meta'' that we had of people just coming, grabbing a synthflesh bottle and then leaving which would be nice. less self heal and let doctors do their job.

Waiting room it's kinda unneeded IMO if everything gets moved a little bit more i would also rather have the morgue in the original place and move the paramedic room to somewhere else so, like they mentioned above, chef can come and have his human flesh

where this new morgue is could be repurposed for something else, and well.. while the breakroom is a classic area i just think being on the middle it's.. eh, no one really uses it that much besides from eating a donk pocket or two and grabbing the cleaning spray so.... not worth taking a top priority placement like the middle i would rather **Move the treatment center there** considering that it's.. too far from the entry, consider we have people at crit coming every once in a while and.. just thinking about walking them towards there (where you even reach cryo first, possibly influencing new doctors to put the crit victims there instead of a proper treatment with stasis) already seems like a pain in the ass.. I would put the treatment center right where the break area is and hell i could even suggest swapping it to the right and put CMO office to the left, so CMO could oversee the treatment area from his office and that would be a neat touch. but yeah just think about it, you're almost at crit thanks to a bomb,limbs missing, blood loss, dragging yourself towards the medbay door.. you think you did it THEY WILL SAVE YOU! But no, you see how they drag you almost 30 tiles away before you finally reach a basic stasis bed/cryo so... yeah, definetly needs to swap places and have more priority.

So overall with a little bit of juggling you could save a lot more space by removing innecessary stuff and optimizing rooms for better gameplay experience.

**Comment by heepox** [comment]
Aaaa just noticed cloning is missing a shower and personal closet and mirror.

**Comment by Sinmero** [comment]
No chem factory room? Cmon bruh

**Comment by patpol4** [comment]
Not bad

**Comment by BitBite112** [comment]
It's pretty good! Although a plumbing room would have been nice. I suppose you could use the waiting room, but it makes it a bit ugly and in the way. I'd also prefer to have viro more in space. I kind of like the isolation and it's always fun to see a nukie float by. It also makes it a great base for cult or revs because of it's isolation.
Other than that I think it's a pretty good map!

Edit: 
The treatment center could use some table to gold medicine on them, though. 
And for the love of god, please remove the see through doors in the restrooms or else there will be some major voyeurism going on.

**Comment by ghost** [comment]
> It's pretty good! Although a plumbing room would have been nice. I suppose you could use the waiting room, but it makes it a bit ugly and in the way. I'd also prefer to have viro more in space. I kind of like the isolation and it's always fun to see a nukie float by. It also makes it a great base for cult or revs because of it's isolation.
> Other than that I think it's a pretty good map!
> 
> Edit:
> The treatment center could use some table to gold medicine on them, though.
> And for the love of god, please remove the see through doors in the restrooms or else there will be some major voyeurism going on.

They aren't see trough, that's just what airlocks look like in strongdmm.

**Comment by qwertyquerty** [comment]
rare based belone pr, +1, fix conflicts

**Comment by BeloneX** [comment]
> rare based belone pr, +1, fix conflict

**Comment by ghost** [comment]
I don't know what i did... but it seems to have worked?

@qwertyquerty Conflicts fixed!

It's ready... i think.

**Comment by Fronsis** [comment]
Oof travis

Still, check my suggestions again when you can since i've shared it around on discord and some people agree on some rebalance regarding space.

**Comment by ghost** [comment]
image

YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAAAAAAAAAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHH

**Comment by Chessus** [comment]
I just noticed that the Blood filter tool wasn't added to the surgeries.

**Comment by PowerfulBacon** [comment]
I don't like the distance everything is, I don't like that there is no foyer, the security post isn't actually in medical itself, the morgue is in a bad position for genetics, if you are healing someone in surgery and need to quickly grab a medkit you have to run all the way to the other side to get to the tool storage, I don't even see a lathe in the screenshot of the medbay as a hole and the double thick walls in the toilets are very triggering. Medbay should be clean and open in the main halls since there is going to be a lot of people that need to be moved and dragged around, and minimising the distance is the most optimal way to do it.
Personally I think metastation medbay was a pretty good medbay before, so you either need to leave it or make one that's better than the already good medical they have, and I don't really think this cuts it compared to what we had before. Also the maintenance is a little missed up with decals suggesting there will be a door with no actual doors and a 3x3 maint room with open walls (most maint rooms use the walls for posters so there will be a poster floating in the air sometimes)

(All of this is based off the image you provided and not the map diffs)

**Comment by PowerfulBacon** [comment]
Also I don't like the thin windows being overused, especially in that sleeper area. And medical shouldn't really have a meeting area right in the middle of it

**Comment by PowerfulBacon** [comment]
Also there is no more spare oxygen tank for cryo, no mirror in cloning

**Comment by PowerfulBacon** [comment]
Also the medical hardsuit should probably be reserved for the CMO, since it's a good hardsuit with low slowdown and unique on every other map

**Comment by PowerfulBacon** [comment]
Chemistry has no chemistry closets or clothes vendors

**Comment by jlsnow301** [comment]
I like the positioning of the security post + limb grower room is new

Requested: 
- Cryo sleeper in the cloning room (needs the console, put this on the same tile)
- Cryo sleeper alternate: replace one stasis machine. Lot of people get revived AFK
- High traction floors with emergency showers 
~~- lathe in storage somewhere~~
- pepper spray in sec

**Pull request closed without merging**
