### PR TITLE
Aristocrat coats for the law office

### PR DESCRIPTION
**Pull request by Malgover**
## About The Pull Request

This PR adds 4 new coats to the law office's wardrobe.
coats

Orange:
orange

Red:
red

Brown:
brown

Blue:
blue

## Why It's Good For The Game

The more clothes the better, and the law office's wardrobe is lackluster compared to other wardrobes. This PR aims to provide our beloved lawyers with more customization. Now they can truly look like lawyers!

## Changelog
:cl:
Adds aristocrat coats to the law office's wardrobe.
/:cl:

### CODE REVIEW

**Comment by RDS88-beeman** [comment]
i love it
speedmerge

**Comment by zeskorion** [comment]
> sudden influx of vanity prs

Time for me to code my own vanity set for the funy

**Comment by R3n3h** [comment]
Lawyer wardrobe genuinely needed an update, and this one looks amazing.

**Comment by merrgear2** [comment]
Only if red coat lawyers are valid for being DIRTY LOBSTERBACKS GOD BLESS MURICA

**Comment by pickleinjar** [comment]
i wanna look fancy in coat :)

**Pull request closed without merging**
