### PR TITLE
Tgui bounty console and NTOS bounty program

### PR DESCRIPTION
**Pull request by KubeRoot**
## About The Pull Request

Ports the following PR:
- https://github.com/tgstation/tgstation/pull/51509
- https://github.com/tgstation/tgstation/pull/51910
  - This PR is a fix to unintentional icon state deletion from the first PR

Updated to match modern tgui, and added dependency to modular computer printer for NTOS bounty app printing function.

Note: This completes a card on the "Things to Port" project

<details>
<summary>Pictures</summary>

image

image

</details>

## Why It's Good For The Game

As usual, tgui is much nicer

## Changelog
:cl:
add: Bounty console now uses a tgui interface
add: There is a new "Bounty Hunter" program available for modular computers and tablets 
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
> As usual, tgui is much nicer

TGUI windows are a lot worse for performance on static windows due to the fact they auto update constantly. Disable auto updating on the UI.
Also what's with the json changes?

**Comment by PowerfulBacon** [comment]
(In my opinion the old UI looks better than the TGUI one)

**Comment by KubeRoot** [comment]
> Disable auto updating on the UI.

Isn't auto-updating disabled by default? Or was it enabled in the changes I ported?

> Also what's with the json changes?

For some reason they seem to have CRLF line endings, which makes git very angry because our .gitattributes says json files **have** to have LF, and git refuses to behave unless I commit them. I tried asking around but couldn't get it to work nicely.

> (In my opinion the old UI looks better than the TGUI one)

I think this one looks better, but could be more compact. That said, if you have specific suggestions, I'd be happy to try them out.

**Comment by PowerfulBacon** [comment]
> 
> 
> > Disable auto updating on the UI.
> 
> Isn't auto-updating disabled by default? Or was it enabled in the changes I ported?
> 
> > Also what's with the json changes?
> 
> For some reason they seem to have CRLF line endings, which makes git very angry because our .gitattributes says json files **have** to have LF, and git refuses to behave unless I commit them. I tried asking around but couldn't get it to work nicely.
> 
> > (In my opinion the old UI looks better than the TGUI one)
> 
> I think this one looks better, but could be more compact. That said, if you have specific suggestions, I'd be happy to try them out.

Its enabled by default, I have a PR open that changes that

**Comment by PowerfulBacon** [comment]
I think TGs looks better with the brown background and being closer to the original

**Comment by KubeRoot** [comment]
> I think TGs looks better with the brown background and being closer to the original

They didn't update their PR description, if you scroll down they changed it later, this is exactly how it should look in the final PR :^)

**Pull request merged**
