### PR TITLE
Fixes Fatal Flaw of Fusion While Making It Not That Boring

### PR DESCRIPTION
**Pull request by park66665**
### Fusion and Heat

Fusion creates or deletes heat, and it depends on delta_plasma (i.e. the change in amount of plasma). When fusion removes plasma, it creates heat (i.e. exothermic), and when fusion creates plasma, it removes heat (i.e. endothermic)... when it doesn't. Fusion heat-eating is averted when instability is below certain point, which is 2 at this codebase. But how it actually happens?

It happens by making fusion supposedly heat-neutral, and technically speaking, it is done by setting reaction_energy to 0. And what happens when reaction_energy is zero? It *bypasses* thermal energy preservation, for `if (reaction_energy)` blocks also when reaction_energy is purposefully set to 0.

### Why Bypassing Thermal Energy Preservation is Bad

It is a common sense that a reaction shouldn't be fiddling with temperature sloppily, and every reaction complies so by preserving thermal energy of a gasmixture. When it doesn't, shit can hit the fan, and in case of fusion, it really did.

As I stated earlier, the bypass happens when fusion creates plasma while having lower than 2 instability. Thusly, we can safely assume that majority of bypass happens with net increase in heat capacity; decrease in carbon_dioxide is unlikely to be able to counter the increase in plasma (which has higher heat capacity) and production of waste gases. And, it really does:

Screenshot 2020-10-04 030548
_Fig 1. A small part of a collection of cases where thermal energy preservation was bypassed. First line: changes in heat_capacity. Second line: changes in plasma. Third line: changes in carbon dioxide_

So what happens is there are oft-happening cases where

1. Fusion creates plasma while instability is <2...
2. Therefore setting reaction_energy to 0,
3. Which disables thermal energy preservation by literally not touching the temperature.
4. And, since cases like this often happens with net increase in heat capacity,
5. _It creates more thermal energy proportional to current temperature more often than otherwise._

And do you know what 5 means? It means exponentially increasing temperature. Per aspera ad astra!

Screenshot 2020-10-04 024932
_Fig 2. Temperature(upper graph, **log scale**) and delta of temperature(lower graph)_

### What Happens When This is Fixed

This PR fixes aforementioned fatal flow which happens through bypassing the preservation of thermal energy. What are the implications of fixing it? Here are my observations:

1. Since it removes the ability of fusion to heat up exponentially, the fusion heat production becomes... rather... underwhelming. _I strongly advise fixing stim_ball further by restricting its plasma consumption, If you want it to be less boring. (and I guess you probably do?)_
2. I also advise continuously supplying plasma to the mix.
3. No more "e30" (i.e. fusion mix of e+30 Kelvin) fusion canisters.
4. On a side note, a cursory examination revealed that _most_ fusion v6 implementations are affected by this flaw, so atmos coders from other codebases are recommended to take a loot at it.

### What I did after fixing the flaw

Everyone guessed it right, fixing the flaw made fusion unbearably boring and ridiculously difficult. For example, a single tile open turf fusion required 270 moles per tick just to stay alive, and you know such large numbers are not sustainable. So what if I tweaked the math to make it less boring?

After hours and hours of math, number crunching, testing and pure pain, I somehow managed to rebalance it to make not that boring, but not e30-interesting; say goodbye to your e30 fusion canister. (I am nerfing canister fusion to hell but I am not removing it lol) Therefore, this PR is a compromise between 'gamer number' e30 fusion madness we are having right now and the unbearably boring fusion that'll ensue if I do only the bugfix. Also, I am going to skip my usual wall of text here for the sake of everyone's sanity (including mine) so I am going to post a graph in lieu of it:

AHHHHH__
_Fig 3. This PR in a nutshell. However, real numbers won't follow the graph very well, because of usual fusion V6 chaos. Note that numbers here apply to single tile open turf fusion._

And, to help your fusion career, (if you somehow are not banned by admins after failing to resist the temptation to grief,) I also made rads (and nuclear particles strength) scale with thermal energy and fusion nuclear particles color-coded:

Screenshot 2020-10-19 012310
_Fig 4. Weak yellow-green nuclear particles. You certainly won't like being hit by them, though. More pics are available [here.](https://github.com/BeeStation/BeeStation-Hornet/pull/2614#issuecomment-712299446)_

Finally, I am going to list some real-world effects of this PR:

1. Your fusion mix's temp will depend on plasma input. See Fig 3 for more data.
2. For example, fusion will end up lingering on around 1e6K if you fail to feed them.
3. And you will have a hard time going past 1e12K.
4. I am going to be perfectly honest. Fusion canisters are nerfed to hell, and won't make a big (remind you, a dead fusion canister still contains hundreds of moles of plasma heated to a few thousand Kelvin) nuisance. I didn't choose to remove it entirely, though.
5. A 'mainstream' fusion, like 1e9K ones, won't have bright and flashy fire effects at this moment. I will grab fire hotspot code and stitch it to the fusion if you really want to keep that one.
6. I said rads scale with temperature? If you manage to keep a robust and strong fusion, you can get more rads than before.
7. Waste gases are a bit different now. They will still be difficult to harvest, sadly.
8. Okay, one last detail before devolving into word-gore. Fusion will have a hard time cooling down after throttling input. You have been warned.

Feel free to ask me to rebalance this thing further. Numbers a bit ~~extremely~~ tight, ~~oh boy do you even understand how fragile the math is~~ but I can work towards changing the numbers ~~and break everything horribly before giving up only to disappoint you~~ since that's the point of making a PR, right?

## Why It's Good For The Game

No more e30 fusion, but your fun is (kinda) preserved.

## Changelog
:cl:
fix: no more with exponential thermal energy, fusion now correctly produces heat: supply plasma to your nuclear fusion 'reactor', dammit!
balance: in an attempt to preserve fun, I tweaked some numbers and logics in fusion to create some healthy fun
del: e30 fusion
balance: rad now scales with fusion temperature, which means that you will get meager rads if you are bad at fusion (e.g. canister fusion), or stronger rads than before if you manage to keep a strong and robust fusion
add: in order to help you gauge the strength of your fusion, fusion-derived nuclear particles (aka radballs) are color-coded; and adjective-coded, so you can also gauge how damned you are after being hit by a radball
refactor: lightly refactored fusion code in general
/:cl:

### CODE REVIEW

**Comment by park66665** [comment]
> a cursory examination revealed that most fusion v6 implementations are affected by this flaw

Fusion is complete

Imma head to bed sleep tight folks

**Comment by Archanial** [comment]
what

**Comment by ghost** [comment]
Mathematics behind this assertion is partially correct but fails to grasp the larger design of fusionv6 and will guarantee fusion endothermality across all toroidal sizes.

The endothermality threshold does cause the major amounts of energy gain at the higher magnitudes when mass is created out of nowhere, but to get there first, you need to score a few exothermic ticks and those exothermic ticks are balanced out by the fact that high instability reactions generate so much waste gas and sap so much energy they outweigh the ticks where the plasma rotor ticks up. This is where the endothermality threshold kicks in and creates a net positive of energy. Removing this guarantees that fusion will always eventually end up endothermic, making actually getting to the point (roughly around e10) where this bug actually matters. This will kill fusion entirely. Do not merge in its current state.

**Comment by ike709** [comment]
Why does this PR description have more effort put into it than most of my actual research papers?

**Comment by park66665** [comment]
I am not sure the side-effects are the same as decribed by @AutisticFroggy (e.g. The exponential heat does dominate far before e10 level AFAIK) but I do agree that this PR sets off so many parts of balance -- including the fusion initiation hardship. And, well, to be honest, in retrospect, fixing fusion v6 wasn't a good idea in the first place. We can port tgstation/tgstation#47073 for a simpler fix of e30 fusion.

**Comment by park66665** [comment]
Okay, let me do a small ~~postmortem~~briefing because I have some free time for this ~~well actually no I have eight TODOs about SS13 coding atm why did I start coding SS13 AHHHHH~~ and I actually have thought about it last few days. I have no idea how Bee atmosians are thinking about this, but whatever.

As you can see, this PR indeed is going nowhere. _Removal of exponential heat turned fusion into a game of plasma supply_. Although I do like it a little: You can control the growth fusion in a barely predictable matter by controlling the rate of supply of plasma into the fusion mix. And, you *need* to supply plasma (and tritium, of course) if you want to keep the fusion mix alive and ongoing.

So I am sure that everyone will *not* like this because it will kill canister fusion really quickly since people don't like supplying something to a fusion mix canister in the first place. But, again, numbers change everything.

You can safely disregard Froggy's comment because nothing in it is right. I feel really, *really* sorry to say this but I have to tell you folks the truth about fusion. Endothermicity threshold is the threshold you shouldn't be crossing, for going past it means losing energy, but you really can't control it, so you are going to lose energy anyways. (Or, good luck removing nearly all of  multi-million Kelvin nitryl and oxygen and other waste gases from the fusion mix haha you can do it if you are crazier than me I dare ya) Initial few ticks *are* important since free plasma will nonetheless increase the heat capacity and the temperature will drop accordingly if this fix happens -- and it obviously can kill fusion because AFAIK no one in Bee prepares a mix that has thousands of moles of plasma in it. So you need to prepare a mix that has at least a few thousands of moles in it -- and more that that if you are trying to make a multitile open turf fusion.

But, the math, and the numbers determines balance. At this state of PR, a single tile open turf fusion needs constant supply of around *200~250 moles of plasma per tick* just to *stay alive*. This is really, *really* bad number. But as this just a number, we can change it. Whether will the fusion will stay alive by having a long-term trend toward exothermicity or endothermicity entirely depends on toroidal size, and there *is* a threshold where going above (by higher volume) means long term trend toward endothermicity (and death) and vice versa. ~~Froggy rightly calculated it as somewhere around 6.62 (Froggy didn't say 6.62 but [I think that was what Froggy meant](https://www.wolframalpha.com/input/?i=%28integrate+sqrt%28x%29+from+0+to+j-2%29%3Dj))~~ 2020-10-18-EDIT: The threshold was 5.73 because instability. which means that fusion mixes with toroidal size larger than ~~6.62~~ 5.73 _(Subject to variations because WASTE GASES DAMMIT)_ will eventually kill themselves without further interventions to save it. And that particular intervention mostly is, you guessed right, constantly supplying plasma. (I am not going to tell you how it works exactly, but as fusion deals with binding energy of plasma, adding plasma is always a good thing in terms of energy. And, again, no, Froggy, there is no way out of the curse of being higher than ~~6.62~~ 5.73 other than supplying a fuckton of plasma)

And you now start to see why open turf tile fusion demands that much plasma just to stay alive. It has toroidal size of 7.266 because of open turfs volume, and its dwindling energy can only be counteracted by adding *that* many plasma and supplying the mix with fresh plasma that will be translate via binding energy.

Therefore you can now see logic in fusion, and that logic is clear, mostly, but a bit more disappointing. But *now* we got the logic, so we can tweak numbers, and that's the reason why I'd like you get your input because I really am touching the balance of fusion *for fucking real this time* (Another Fusion V7 attempt is ongoing at tg, but I am not willing to close this until I actually port that thing here) 

So at this moment, I have a few... problems?

0. Fusion mix management will become the boring game of 'just maximize the supply of plasma haha lol'
1. Mixes with toroidal size larger than ~~6.62~~ 5.73 will die without supplying plasma.
2. Mixes with toroidal size smaller than ~~6.62~~ 5.73 will just create energy out of nowhere, just like before fixing it, albeit not exponentially. Remind you, ~~canister~~ pipe manifold fusion has toroidal size of ~~6.28~~ 5.55.
3. And the balance is bonkers. Can you really supply hundreds of moles of plasma per tick? It is theoretically possible, (and I actually did it for testing,) but at what cost?
4. You will need to prepare a fusion mix that has right amount of moles depending on where your fusion mix will be living -- canister? At least around 3000 moles of 10000K plasma. An open turf? About 8000 moles is safe. Nine tiles? It'll be around 70000 moles of plasma but can you afford it? And the amount *is* going to be crazy.
5. Fusion's energy fluctuations are inherently boring, and this PR will remove everything except that boring part. They are mostly around tens of thousands of Kelvin if we disregard the false fluctuations due to heat capacity. (So e6 K is where exponential energy bug takes off and at e8 is the point where nothing else than exponential energy bug does anything)

But again, these are just numbers, so we can figure out how to change them.

1. We can fix the toroidal size to be around ~~6.62~~ 5.73 -- that will create long term and mildly exothermic or endothermic trend depending on the number, and those can be in terms of tens of moles of plasma per tick. No more plasma black hole or ridiculous amount of free energy.
2. Or we can tweak the numbers responsible for the long term trend to be dependent on features other then instability, like temperature or thermal energy -- thereby soft-capping the fusion temperature... or make instability a bit saner than it currently is?
3. We can keep baby's first fusion mix of [barely above the thresholds] moles of plasma by giving a young mix an initial boost, safeguard and/or some leeway. That way fusion can be easy to start and keep, but hard to grow to a useful temperature like hyper-noblium threshold.

So you folks might want to give me some opinions on this by saying "fusion should be yadda yadda" before letting me decide by myself and then yelling at me to make another PR to rectify it. Give me crazy ideas around it; I will try to push numbers around for you.

**Comment by Crossedfall** [comment]
> As you can see, this PR indeed is going nowhere. 

The PR is marked as a Draft, so none of the maintainers are actively looking to review this. If you're properly done with the PR, be sure to click the `Ready for review` button towards the bottom of the page.

**Comment by park66665** [comment]
Well, I expected this PR to naturally go somewhere via some sort of discussion and various opinions on what fusion should become. But such rosy future didn't happen, obviously, and such lack of discussion now seems natural considering that Ghilker's fusion V7 also isn't attracting much discussion about its math on GitHub -- it has one of the most *terrible* math I've ever seen.

> So you folks might want to give me some opinions on this by saying "fusion should be yadda yadda" before letting me decide by myself and then yelling at me to make another PR to rectify it. Give me crazy ideas around it; I will try to push numbers around for you.

This is the reason why I posted the comment instead of blitzkrieg-ing through multiple rebalances without much discussion; I can make this PR go anywhere I like, but I always fear that people will come to yell at me after doing that. Therefore I consciously delayed making choices which arose after I made this PR, but I guess my previous comment was also an ultimatum.

So I am going to say this: I'd like to get some input from Bee atmosians. However, if I don't get any input within about three days, I will rebalance fusion *by myself* and turn it into a proper PR again.

**Comment by zeskorion** [comment]
I'm not an atmos wizard, i'm just a layman here. However, fusion is capable of insane gamer numbers and mass destruction- and not much else.  it's a cool thing you can do to get big numbers, as far as I know. 


the best way to improve fusion would be curtailing  gamer numbers and instead giving fusion more gameplay- fusion's only purpose is gas harvesting, which is never really done. adding either reasons to want these gasses or uses for fusion itself other than HOLY FUCK SUN IN A CAN YEAAAAAAAA is the best idea. but i'm talking out my ass here, cuz i dont do atmos

**Comment by park66665** [comment]
> curtailing gamer numbers

It sounds great, and it is easy: this is the scope of this PR, mostly.

> giving fusion more gameplay

It kinda isn't easy, sadly. But I think we can manage to do that. Maybe I should start considering a radiation collector that also collects radiation from radball.

**Comment by park66665** [comment]
This PR is kinda mostly done, it only needs some additional testing and love. The PR contains the following changes right now:

1. Fusion now needs plasma to reach high (>1e8 K) temperatures, and *more* plasma for *higher* temperatures. Realistically you shouldn't be reaching 1e13 K level. The requirements are supposed to quadruple every order of magnitude.
2. In order to aid that, I color-coded the nuclear particles (aka radballs) and made rads by radballs and the fusion itself *scale with the thermal energy.*
3. Tweaked the waste gases to make fusion compliant with my math.

**Comment by park66665** [comment]
Screenshot 2020-10-19 015913
Screenshot 2020-10-19 015856

If things go as planned, this PR will be un-drafted (and be ready) within a day. Sad part is that this PR doesn't add many features.

**Comment by park66665** [comment]
I currently am chasing a bug only affecting some extreme situations, e.g. **FUSION ON SM**, so un-drafting will be delayed considering it'll take another round of testing and others.

**Comment by park66665** [comment]
It finally seems that things are okay, so I will be un-drafting this PR with some pics produced during testing sessions:

Screenshot 2020-10-20 010037
_Fig 1. Fusion on Supermatter. SM obviously didn't last for so long. Fusion on SM is generally is not encouraged since SM's oxygen production often chokes young fusions. Note: the highest energy production by SM rad collectors was around 92 MW per collector._
Screenshot 2020-10-18 060302
_Fig 2. Magenta and purple nuclear particles, i.e. the strongest of the radballs, multiple times stronger (or hundreds of times; the scaling stops at magenta, so who knows.) than old nuclear particles. Sustainably creating magenta nuclear particles are not thought to be feasible, though. If you *somehow* manage to supply hundreds of moles of plasma per tick, you will be seeing these too, though. The fire effect is absent since all of oxygen created by fusion has already been converted to pluoxium because of rads the fusion creates._
Screenshot 2020-10-18 045511
_Fig 3. Blue nuclear particles. They generally are stronger than old nuclear particles, and they are supposed to be the casual limit for very-well-catered fusion._
Screenshot 2020-10-20 003255
_Fig 4. Green nuclear particles. Probably the most common one I've seen. The temperature range where green nuclear particles occur is a some sort of snowflake-y transition region for my math which things are prone to get stuck and slow, so you too will be seeing them quite often. Ballpark estimates are around a dozen to a few dozens of moles of plasma per tick._
Screenshot 2020-10-19 011055
_Fig 5. Red nuclear particles. If you are bad at taking care of fusion (or you are just neglecting it: lone fusion canisters will inevitably reach a point where it does nothing but emitting mostly deep-red nuclear particles before suddenly dying) the fusion will emit red to orange nuclear particles which is laughably weak compared to other horrors fusion can cause. Prolonged exposure won't be a good idea, though, especially since fusion without any help might still be able to muster some yellow nuclear particles, which is a considerable threat to your health, because of pure chaos. Note the presence of fire effect which means insufficient oxygen removal by fusion rads._

**Comment by park66665** [comment]
Aaaaaand the travis bugged *again*?

**Comment by park66665** [comment]
I guess the code is done; it only needs some review at this point

**Comment by nikk735** [comment]
>e30 fusion madness we are having right now

I have yet to see more then 2 people make fusion on sage 

>air.set_temperature(clamp(thermal_energy/new_heat_capacity, TCMB, INFINITY)) 

kinda ruins the who point of exponential fusion which seems more realistic than just linear growth also fusion was pretty much just a "haha big number go brrr" kinda thing no one really used it for anything else.  

>(I am nerfing canister fusion to hell but I am not removing it lol) 

canister fusion was the only viable fusion during a 1 hour round it takes too long to set up any other fusion set up and actually use it for anything, also there are no walls or floors that can withstand temps that canisters can so you limit the max temp to like e10 where plasma glass breaks or e30 where reinforced floors break. 

this is cool and all but no one is gonna do fusion including myself after this is merged because it is just too time-consuming to be enjoyable 

if the canister fusion was left viable then this would be a really cool pr but removing the more realistic less time-consuming option for fusion ruins it for anyone who wants to do it during a normal round that's not a 2 hour extended

**Comment by park66665** [comment]
1. Austation has around 2 highly competent miners. The influence they are exercising on some rounds *define* said rounds. Fusion makers are as influential as them; I am sure that on Bee fusion makers are disproportionately influential.
2. Growth *is* exponential. I told you the PR is the compromise between e30 (uncontrolled exponential growth) and boring controlled linear growth. *The PR implements controlled exponential growth that'll stop way before `INFINITY`* and where it stops *depends* on plasma supply. Please look at Fig 3 closely.
3. Canister fusion is where I should disagree with you. I don't intend to make canister fusion a mainstream one.

**Comment by nikk735** [comment]
ah alright good pr overall though good shit

**Comment by utilbird** [comment]
I like your funny words magic man

**Review by PowerfulBacon — APPROVED** [review]

**Comment by park66665** [comment]
Welp, it happened a bit faster than I expected. Anyways, I finally can now
~~run away from SS13 and live in the woods~~ start another "project" and
fix(?) shit in general. If I only had my laptop charger...

**Pull request merged**
