### PR TITLE
Revert "Refactors reagent exposure code, makes exposure methods bitflags"

### LINKED ISSUE #8466: Can't repair husked bodies with Synthflesh/Strange Reagent
RKZ Said a reagent pr they did fucked it up, please fix, so many rounds of players that tried to dehusk people...

### PR DESCRIPTION
**Pull request by Rukofamicom**
Bad port that introduced completely gamebreaking bugs
Synthflesh can't unhusk bodies
Touch-based reagents, such as Brute, Burn and Synthflesh patches seemingly fail to work at all. 

expose_mob() isn't even being called when I attempted to debug the issues. None of my breakpoints shown triggered at all when attempting to apply a patch:

image

Closes #8466

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
@Tsar-Salat

**Comment by Rukofamicom** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/8479

He is attempting to fix it here, but I don't think this is something that should be waiting on a fix-in-progress due to its impact on the game.

**Comment by Tsar-Salat** [comment]
TM this until I figure out a way to fix it, please

**Review by Tsar-Salat — APPROVED** [review]

**Comment by Tsar-Salat** [comment]
merge please

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
