### PR TITLE
mechs, megafaunas and bosses no longer get tossed around by explosions

### PR DESCRIPTION
**Pull request by jupyterkat**
## Why It's Good For The Game

these things shouldn't be thrown around, yet they are

## Changelog
:cl:
balance: mechs, megafaunas and bosses no longer get tossed around by explosions of any size
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
so i looked at the why its good for the game section
and i still cant figure out why you would do this

**Comment by jupyterkat** [comment]
use common sense, does a huge dragon or a towering mech get blown away by a tiny explosion?

**Comment by BrumalLake** [comment]
but you said of any size
and any decent sized explosion would

**Comment by jupyterkat** [comment]
a decent enough explosion would just destroy the mech. plus the point of these mobs and mechs is that they're not pushed around **easily**

**Review by utilbird — CHANGES_REQUESTED** [review]
Please provide reasoning as to why this change is beneficial in the PR description. It's there for a reason 😛

**Comment by RDS88-beeman** [comment]
dropping sorium grenades to move megafauna onto the mining shuttle?
is bad, to clarify

**Comment by jupyterkat** [comment]
> Please provide reasoning as to why this change is beneficial in the PR description. It's there for a reason 😛

everyone with a brain will know anyways

**Comment by BrumalLake** [comment]
> 
> 
> dropping sorium grenades to move megafauna onto the mining shuttle?
> is bad, to clarify

ok tell me who has the balls to do this and has pulled this off

**Comment by RDS88-beeman** [comment]
do you want  me to
is that a challange

**Comment by BrumalLake** [comment]
> 
> 
> do you want me to
> is that a challange

so no one has then thank you for confirming
i don't see why you would do this over luring them

**Comment by githubuser4141** [comment]
> use common sense, does a huge dragon or a towering mech get blown away by a tiny explosion?

mechs aren't 'towering', they can squeeze past an airlock and pieces of them can be carried in your hand so they're probably closer to power armor then anime mecha.

**Comment by jupyterkat** [comment]
but they're still really heavy you wanker

**Pull request closed without merging**
