### PR TITLE
Forced emote shows an icon

### LINKED ISSUE #10633: [New Feature]: Forced emote should show a flag sign
### Describe the feature request

an emote message shows `※ laughs`
but if it's a forced emote, it should be like `▣ laughs` so that we can notice if it's a forced emote.
Maybe forced speech too?

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
Forced emote shows an icon

* Closes #10633

## Why It's Good For The Game
Forced emotes can inherently bait players OOCly and it can make people piss off to themselves.
This is a strong sign of metainformation that their emotes are forced, but this will never be any bad for IC.
For mindless mobs, they won't show the forced emote icon
(but in the testing evidences, they show it because it's better to test there, but they won't show it.)

## Testing Photographs and Procedure

image

image

## Changelog
:cl:
add: forced emote now shows ▣ icon at Runechat and TGUI chat. (mindless mobs won't show it)
admin: forced emote is now logged with "(force)" so that you won't be baited.
/:cl:

### CODE REVIEW

**Comment by Howluinb** [comment]
I think it's part of the intended purpose that having a drug making you laugh would cause awkward conversations or severely worsen them.

If I'm shitfaced drunk/super high and my boss comes up to me to yell at me, having a forced *laugh will actively worsen the situation and give me IC consequences for being *extremely drunk on the job*
Being able to tell so meta-wise will actively change the way those drugs/illnesses affect how we interact with players IC, consciously or not

**Comment by Rukofamicom** [comment]
:key:

Meta-information is bad, this prevents players from faking conditions and eliminates certain minor conflicts from being possible.

**Comment by Rukofamicom** [comment]
Also it's kind of odd to make a feature request, and then immediately make a PR closing the issue that feature request created. 

This looks like patting yourself on the back almost.

**Comment by EvilDragonfiend** [comment]
> 🔑
> 
> Meta-information is bad, this prevents players from faking conditions and eliminates certain minor conflicts from being possible.

As how I answered to Howluinb, **_not every_** metainformation is bad. You disagreed with removing the language icon before, and it sounds metainformation isn't bad, meanwhile now you're disagreeing here with saying metainformation is bad.
It's bad and not bad up to how it affects players. metainformation can be a good RP tool for players if properly implemented, and now I believe it's good here.

and tell me, what can be a case that a player can fake people with a forced emote?
I don't expect any good RP can be made with a forced emote.


> Also it's kind of odd to make a feature request, and then immediately make a PR closing the issue that feature request created.
> This looks like patting yourself on the back almost and artificially inflates the number of issues dealt with.
>
> If you want to add a feature and are intending to code it yourself, just make a PR without the suggestion.

Isn't that how it works? Basically it's posting what's to be made whoever does it.

**Comment by Penwin0** [comment]
I share Ruko's opinion here, players shouldn't be able to see any meta-info like that, breaks immersion

**Comment by PowerfulBacon** [comment]
Agreed with comments above.

**Pull request closed without merging**
