### PR TITLE
Adds qwerty's onlyfans to the end credits

### PR DESCRIPTION
**Pull request by qwertyquerty**
## About The Pull Request

Adds a link to my onlyfans in the end credits

## Why It's Good For The Game

Heavily requested by community

## Changelog
:cl:
add: Added qwerty's onlyfans to the credits
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
This is the pr that will save beestation 13 dot com

**Comment by giacomoh** [comment]
Why is this here

**Comment by Dejaku51** [comment]
speed merge please

**Comment by qwertyquerty** [comment]
guys please I need the money to buy food I literally weigh 97 pounds

**Comment by ValuedEmployee** [comment]
Someone help support my homie they're really going through it right now

**Comment by Pirill** [comment]
Are you really just going to close this PR and let them starve?!

**Comment by mcmeiler** [comment]
😢😢😢 GUYS!!! Qwerty can't afford to live anymore without OF subscriptions!!! 😢😢😢

**Comment by PowerfulBacon** [comment]
They can't click on that link tho

**Comment by zeskorion** [comment]
> guys please I need the money to buy food I literally weigh 97 pounds

but i weigh 95 pounds i need it more

**Comment by PowerfulBacon** [comment]
if you have £95 just go buy some food, get more pounds and then buy more

**Comment by Archanial** [comment]
So true

**Comment by qwertyquerty** [comment]
Close with 13 upvotes? Mad

**Pull request closed without merging**
