### PR TITLE
wabbajack_act no longer allows xenobiologists to become antags or megafauna

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request

wabbajack_act no longer allows players to become antags or megafauna

## Why It's Good For The Game
easy access to changeling or lesser ash drake is somewhat bad balance wise

## Changelog
:cl:
del: xenobio can no longer become changelings in any way, shape, or form
del: xenobio can no longer become megafauna
/:cl:

### CODE REVIEW

**Comment by VictorVow** [comment]
Lesser ash drake isn't a megafauna.

**Comment by Moccha-Bee** [comment]
Lesser ash drake is weaker than a magical dragon. And iirc it dosen't even get the abilities a normal ash drake gets.

**Comment by PowerfulBacon** [comment]
but it's funny and can only be created on shuttle right? (actually transform bolt uses this doesn't it)
Also it can spawn xenos anyway which are given hijack objective

**Comment by zeskorion** [comment]
> but it's funny and can only be created on shuttle right? (actually transform bolt uses this doesn't it)
> Also it can spawn xenos anyway which are given hijack objective

This is the bolt of change, which xenobio can get. I can remove xenos too if you want, though

**Comment by zeskorion** [comment]
> Lesser ash drake is weaker than a magical dragon. And iirc it dosen't even get the abilities a normal ash drake gets.

It still has megafauna immunities and high resistance, damage, and gibbing/healing

**Comment by PowerfulBacon** [comment]
To be fair, it is a 0.5% chance to roll lesser ash drake

**Comment by Moccha-Bee** [comment]
> > Lesser ash drake is weaker than a magical dragon. And iirc it dosen't even get the abilities a normal ash drake gets.
> 
> It still has megafauna immunities and high resistance, damage, and gibbing/healing

sure it has the defenses but none of the special attacks a weaker biting attack and a easy to avoid fire breath overral leave lesser ash drakes they are funny.

**Review by Archanial — APPROVED** [review]

**Comment by zeskorion** [comment]
> To be fair, it is a 0.5% chance to roll lesser ash drake

currently, changebolt is also quite easy to spam if you roll a carp

**Comment by MNarath1** [comment]
> > To be fair, it is a 0.5% chance to roll lesser ash drake
> 
> currently, changebolt is also quite easy to spam if you roll a carp

if your role a carp that actually has it that also depends heavily on luck i wouldn't call it easy access only time i see people actually use it is on that escape shuttle with the change bolt shooting statue but rarly (i do not say that it never happens trough) in xenobio i mean yes you can do it but you probably  going to take a long time getting a carp with changebolt and then that carp has to shoot you until you role the right one.
But yeah that shuttle statue is kinda broken as this thing actually allows kinda easy access to it

**Comment by MNarath1** [comment]
As a little reference i do rememeber one time a player tried to get a carp with changebolt (i was said carps) but even trough he got magicarps even after like 30 minutes and a xenobio lab so overfilled with gold slimes spawns that you can barly walk in it he still did not get changebolt

**Comment by Moccha-Bee** [comment]
Since xenolings got closed , fuck this pr getting xneolings already takes 1 hour longs and you still need a body to bite, since you lose yours.

**Comment by ghost** [comment]
this blows

**Comment by WhyIsCaeciliusTaken** [comment]
noooo you can't have fun in the last 5 minutes of a round with crew consent noooooooo

**Comment by zeskorion** [comment]
> noooo you can't have fun in the last 5 minutes of a round with crew consent noooooooo

this affects changebolts, not just the wabbajack emitter that shoots them

**Comment by Blueturbo47** [comment]
> > noooo you can't have fun in the last 5 minutes of a round with crew consent noooooooo
> 
> this affects changebolts, not just the wabbajack emitter that shoots them

Still doesn't change the amount of time to get a carp with only change bolt to "spam it"

**Pull request closed without merging**
