### PR TITLE
Adds a new curator restricted traitor item: Energy whip

### PR DESCRIPTION
**Pull request by TeomanTheGreat**
## About The Pull Request
Adds a new weapon to the traitor curators arsenal. It acts exactly like a normal whip except it does extra damage when turned on (however its knockdown effect for the trip attack is half of the normal whip in order to balance the weapon). It is 18 tc because of how potentially robust it could be considering you can disarm people and kill them from 3 tiles away. 

## Why It's Good For The Game
New weapon for traitor curator players. 

## Changelog
:cl:
add: Energy whip for traitor curators
imageadd: Energy whip icons
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Isnt this a straight copy paste of a normal whip? Also shouldn't work when active

**Comment by yyzsong** [comment]
Add a chance to fuck up and accidentally whip your own eye out

**Comment by TeomanTheGreat** [comment]
> Isnt this a straight copy paste of a normal whip? 

It is mostly a straight copypaste. 

> Also shouldn't work when active

Its intentional hence why its 18 tc

**Review by PowerfulBacon — COMMENTED** [review]
Not requesting changes since this is more opinionated
 - Attack shouldn't work when the whip is off.
 - Targetting chest should deal more damage (the 15?)
 - Targetting others should deal less damage or none (5?)
 - the arm targeting could be a lot better

**Comment by TeomanTheGreat** [comment]
I am currently waiting for Kapu to fix the whip shitcode before i continue this pr

**Comment by Kapu1178** [comment]
> 
> 
> Not requesting changes since this is more opinionated
> 
>     * Attack shouldn't work when the whip is off.
> 
>     * Targetting chest should deal more damage (the 15?)
> 
>     * Targetting others should deal less damage or none (5?)
> 
>     * the arm targeting could be a lot better

#4253

**Comment by Kapu1178** [comment]
#4253

**Comment by pickleinjar** [comment]
based

**Pull request closed without merging**
