### PR TITLE
Adds cerestation

### PR DESCRIPTION
**Pull request by qwertyquerty**
because why tf not

### CODE REVIEW

**Comment by CthulhuOnIce** [comment]
i'm quite certain that objects have been removed and added since cerestation was removed

**Comment by qwertyquerty** [comment]
ok then if it doesnt compile ill revert ez

**Comment by CthulhuOnIce** [comment]
"omg cthulhu never tests his PRs"

"if it breaks it production we'll just revert it lol"

**Comment by qwertyquerty** [comment]
giving you a taste of your own medicine

**Comment by qwertyquerty** [comment]
nerd

**Comment by CthulhuOnIce** [comment]
taste this

**Comment by qwertyquerty** [comment]
taste this

**Pull request merged**
