### PR TITLE
Revert "Revert "Add's a reddit moment""

### PR DESCRIPTION
**Pull request by utilbird**
Reverts BeeStation/BeeStation-Hornet#4353

tfw kneejerk revert merged

### CODE REVIEW

**Review by MCterra10 — APPROVED** [review]

**Comment by aidan-bowman** [comment]
keanu reeves approved this (wholesome 100)

**Comment by Rukofamicom** [comment]
The war of Chungus is on.

**Comment by aidan-bowman** [comment]
shuttle ping pong 2: now it's redditor

(would make this joke on the forums but i ate a month long mute 😔)

**Comment by francinum** [comment]
clearly the solution to this edit war is a separate codebase for golden

**Comment by TeomanTheGreat** [comment]
Wholesome 100 😳

**Comment by mat-lap** [comment]
reddit gold

**Comment by ike709** [comment]
I'm fairly tempted to speedmerge this to enable a "Revert Revert Revert big chungus" PR.

**Comment by OceanFish1** [comment]
Ruko pr speedmerge cringe no wholesome revert revert keanu reeves big chungus moment

**Comment by ike709** [comment]
Once again we're hampered by the inability to separate LRP/MRP content in the code in a decent way.

**Comment by OceanFish1** [comment]
literally 1984

**Comment by MCterra10** [comment]
literally 1984


> 
> 
> Once again we're hampered by the inability to separate LRP/MRP content in the code in a decent way.

just add a config for disabling LRP content, EZ, done.

**Comment by Troontjelolo** [comment]
add "the chungus config"

**Comment by ike709** [comment]
> just add a config for disabling LRP content, EZ, done.

Vetoed by crossed.

**Comment by PowerfulBacon** [comment]
tfw stupid pr merged in the first place

**Comment by imsynthex** [comment]
"stupid pr" there are no words to express how wrong you are.

**Pull request closed without merging**
