### PR TITLE
Reduces riot suit slowdown from 50% to 20%

### PR DESCRIPTION
**Pull request by VictorVow**
https://github.com/tgstation/tgstation/pull/45656

## About The Pull Request
 
Removes the slowdown from riot suits in an effort to make them more useful to security.
## Why It's Good For The Game

Riot suits have for a while firmly sat in the "garbage-tier" for experienced players because slowdown more or less completely obstructs security from doing their jobs as any perp can outrun them. Given Oranges recently expressed a desire for coded changes that make sec less ridiculously vulnerable to tiders and easy to loot, particularly with hallway shoves, I believe making riot armor an actually useful tool to deal with tiders via its innate shove/knockdown immunity could help.
## Changelog

:cl: Dawson1917 & AWalton
balance: Riot suit slowdown is now 20%, down from 50%.
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
Just my opinion, but the suits need a slowdown REDUCTION, not a complete removal.

**Comment by ike709** [comment]
I agree that it shouldn't be a complete removal. I'd be fine with something as small as 10% slowdown, but riot gear is too OP to not have a downside.

**Comment by VictorVow** [comment]
It's a tradeoff of reduced protection vs other damage types, and the only gamemode that it really benefits against is revs. But voters can decide.

**Comment by Arrfur** [comment]
Reminder that melee is 90% of the damage types you will face as sec. You could argue with a complete slowdown removal that there would be no reason to not jsut be walking around is riot gear as opposed to their standard armour. 

Bullet proof vests are justified in having no slowdown because they are so niche

I think Ike is right in a 10%~ slowdown, that way they arent useless, but still wont be able to pursue people.

**Review by qwertyquerty — CHANGES_REQUESTED** [review]
Slowdown can be lessened but should not be removed.

**Pull request merged**
