### PR TITLE
Locking reagent system

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
Makes reagents not transfered when it's locked
and some minor change

## Why It's Good For The Game
because vomit is powergamy

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

---------------------

image

basic sleeper.
16u used. 4u duplicated.
you get 20u, but 4u is locked.
(This lock message is only visible to `bypass_reagenthide` trait holder)

---------------------

image
normal vomit
it removes 10% of reagents

---------------------

image
you don't vomit locked reagents

---------------------

image
floor pill information
this is only visible by `bypass_reagenthide` trait holder
I failed to let admins to see this, so It's visible by the trait holder which is debug outfit

</details>

## Changelog
:cl:
add: reagent - locked volume system - specific amount of reagent now can be locked that wouldn't be transferred via some methods. For example, you can vomit reagents, and the vomit will contain reagents, and if you scoop it up, you won't scoop up the locked volume of a reagent.
balance: duplicated amount of a chemical by sleeper will be locked (if you get 10u bicaridine, it consumes 8u, and 2u is duplicated. this 2u will not be vomitable)
add: floorpills are no longer vomitable
add: added admin trait that can check hidden reagent (i.e. floorpills)
fix: fixed some missing global trait list data
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
> Reagent can be locked not to be transfered

What does this mean?

Please include your changelog info in your pr body.

**Comment by EvilDragonfiend** [comment]
> > Reagent can be locked not to be transfered
> 
> What does this mean?
> 
> Please include your changelog info in your pr body.

add: reagent - locked volume system - specific amount of reagent now can be locked that wouldn't be transfered via some methods. (i.e. vomit)

**Comment by PowerfulBacon** [comment]
> because vomit is powergamy

?
Its a valid way to clear chems from your system

**Comment by EvilDragonfiend** [comment]
> > because vomit is powergamy
> 
> ? Its a valid way to clear chems from your system

You have charcoal or pentetic acid to clear chems from your system and it's way more standard.
vomit is usually used to get rare random reagents. For example, you can duplicate Adminordrazine.

**Comment by EvilDragonfiend** [comment]
> this seems unintuitive, how about just making vomit un-scoopable?

people will yell at me for that rather than for having this

**Comment by PowerfulBacon** [comment]
Removing the ability to take reagents from vomit sounds like a better solution, I didnt even know you could do that in the first place

**Comment by EvilDragonfiend** [comment]
image

I changed it a bit. scooping up vomit will still scoop reagents without locked ones.

**Comment by EvilDragonfiend** [comment]
I kinda want to refactor the chem system greatly. I still want this, but maybe doing this after refactorimg the chem system will be the best timing.

**Pull request closed without merging**
