### PR TITLE
Tritium no longer creates energy out of nothing

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Tritium burn reaction will no longer create extreme amounts of energy from nothing. All energy created will be based on amounts of gases consumed during reaction.

## Why It's Good For The Game

Tritium fires will not create miniature suns.
TTVs still function as before, science is not being nerfed in this PR.

## Testing Photographs and Procedure

<details>
Created a tritium fire, gases were consumed appropriately.
Energy created was according to gases consumed.
</details>

## Changelog
:cl:
tweak: Tritium fire no longer creates energy out of nothing.
/:cl:

### CODE REVIEW

**Comment by williamcll** [comment]
>Potential implications for science research TTV rushes.

Have you tested how this impacts making TTVs?
Furthermore, have you tested how this impacts fusion?

**Comment by ghost** [comment]
>Have you tested how this impacts making TTVs?

TTVs that were relying on non-existent tritium being burned up will not function as well, since only tritium that exists will count towards energy creation.

Following https://forums.beestation13.com/t/ganima-s-comprehensive-to-guide-maxcaps-with-video/17285 still provides the same maximum 25k research 50k credits yield.

>Furthermore, have you tested how this impacts fusion?

It has no effect on fusion as it doesn't change how fusion works.

**Comment by Tsar-Salat** [comment]
Nice

**Comment by BrumalLake** [comment]
this doesn't change anything because it's handled by the auxmos hook which proves this is untested as well

**Comment by ghost** [comment]
> this doesn't change anything because it's handled by the auxmos hook which proves this is untested as well

It seems I have much to learn.

**Pull request closed without merging**
