### PR TITLE
Medical Analyzer Implant!

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
Adds a new medical analyzer implant for medical doctors, researchable under Cybernetic Implants

## Why It's Good For The Game
A medical doctor should always have an analyzer on hand, and this implant helps save an inventory slot. It is also extremely handy for tend wounds/burn surgery, as if you get the surgical tools implant as well, you can do maximum efficiency while taking up no item slots.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

medd_exam

medd_scanning

</details>

## Changelog
:cl:
add: New Medical Analyzer impant
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
No sprite preview for the implant?

**Comment by etherware-novice** [comment]
> No sprite preview for the implant?

it just reuses the default arm implant sprite

**Comment by EvilDragonfiend** [comment]
I am not a fan of this single item as an implant.

**Comment by etherware-novice** [comment]
> I am not a fan of this single item as an implant.

maybe i could just add it to surgery tools?

**Pull request closed without merging**
