### PR TITLE
Makes sunHUDs need advanced sunglasses to be crafted.

### PR DESCRIPTION
**Pull request by r1ks-iwnl**
## About The Pull Request
Changes sunHUDs crafting recipe from being able to use normal (not flash-proof) sunglasses to advanced sunglasses and its subtypes.

## Why It's Good For The Game
Using the normal sunglasses in the sunhud crafting recipes allows you to get flash protection in less than 1 minute from roundstart by gathering the 2 tools required, 5 cable coil and buying sunglasses from the clothes vendor in dorms, you can skip the buying sunglasses step completely by buying sunglasses in the beecoin shop so you spawn with them roundstart. I don't consider being able to craft a flashproof item with stuff as easy to get as this very good.

## Changelog
:cl:
balance: HUD Sunglasses now need advanced sunglasses or its subtypes to be crafted instead of normal sunglasses.
/:cl:

### CODE REVIEW

**Review by park66665 — COMMENTED** [review]
I think you missed `/datum/crafting_recipe/beergogglesremoval`'s `result`

**Comment by r1ks-iwnl** [comment]
Yeah i did, fixed now

**Review by ike709 — APPROVED** [review]

**Comment by OceanFish1** [comment]
This is more like a fix than a rebalance

**Comment by r1ks-iwnl** [comment]
> 
> 
> This is more like a fix than a rebalance

We'll never know if this is intended or not

**Comment by PowerfulBacon** [comment]
oops I should read the comments

**Pull request merged**
