### PR TITLE
DeltaStation2 New Brig (and minor fixes/adjustments)

### PR DESCRIPTION
**Pull request by PestoVerde322**
## About The Pull Request

This PR overhauls completely the brig for Delta2, and also rearrange some stuff to fit more the overall aesthetic and functionality of the brig, this also modifies the crew quarters a bit and the cargo dock, while also fixing some leftovers from other PRs.

## Why It's Good For The Game

Better map good?

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

immagine

</details>

## Changelog
:cl:
add: [DeltaStation2] Rearranged essentially amost all of the brig surroundings and the brig itself
fix: [DeltaStation2] Removed some misc leftovers
/:cl:

### CODE REVIEW

**Review by MarkusLarsson421 — COMMENTED** [review]
<details>
<summary>DeltaStation Review, MEGA edition!</summary>
Forgot "closeup" stripes here.

image

image

And maybe here?
image

Here you only have halfway through the door. Is this intentional?
image

Why these tiles under the doors? It looks off.
image
Also missing "closeup" stripes, unsure if it matters here.
image
I'm looking around and even dorms is missing a lot of closeup stripes, might be insignificant.
Grey floor tiles is sticking out here to the right half a tile, but not to the left. And above and bellow they are sticking inwards half a tile. Is this intended?
image
Armoury looks odd. Squeeze it down a tile in both X and Y so its "hallway" length is varying. Also, is the different coloured tile decals intended here?
image
The red floor tile decal probably shouldn't go against the wall here and should instead go along the stripes.
image
Are the ten "bot" decals here worth the 20 pixels it gives?
image

Lacking AI holopad in HoS office, and MAYBE armoury, personal preference.

HoS cameras are not part of the Security Network.

Processing room camera should probably be part of both the security and prison network.

Feel like this camera has a bit too good of vision on the visitation windows? Unsure.
image

Random court room wires and neutral floor tile decal.
image

Cameras outside armoury are not on the Security Network.

Preferably don't put vents and scrubbers under objects if you can help it due to it causing difficult with welding them.
image

I feel like these tiles under the floors are sticking out weirdly. Being the same red colour, only darker. Also, corner decal missing.
image

I feel like this is an overreliance on dark tiles. I'd suggest making it a tad lighter. Perhaps even different decal colour?
image

What are these decal tiles trying to communicate?
image

The room is quite barren in terms of decal details.
image

Unelectrified windows and why not center the door?
image

Why does these center hallway tile decals stop after the fire lock?
image

Doesn't even continue here.
image

These decals are only going along the edge of the room on one side. Why not both?
image

No delivery decal on the delivery spot?
image

Double decal.
image

Why isn't the chute decaled red like everything else against the wall?
image

I like these catwalks for some reason, it feels thematically fitting.
image

Move in the right window like the left window?
image

Space feels a tad barren and uniform. Make the reinforced walls a bit shorter segments and add more lattice.
image

Guaranteed window break every round.
image

Two event spawns next to each other?
image

Detectives Office, Lawyer Office, Courtroom and the exterior Security Hallway are not part of the Security network. Should they? Detectives Office should at the very least.

Weird tiles here too.
image

Random crate with no purpose?
image

Incorrect IDs.
image

Poorly named buttons. From left to right.
"Privacy Shutters" activate the "Space Shutters".
"Armoury Shutters" suggests there are multiple shutters.
image

These buttons can be moved down south once step.
image

Non-electrified window.
image

Prison blast doors aren't in these locations, is this intentional?
image
image

The Brig blast doors are only in the red marked out areas but not the yellow, is this intentional?
image
</details>

**Comment by Geatish** [comment]
The contraband storage being in the hearth of brig will make it extremely hard for tots to get back their confiscated items. Would recommend putting it closer to space / public space / maints, so tots will have a fighting chance to get back their stuff. 
Otherwise this is a great new layout and it looks beautiful

**Comment by MarkusLarsson421** [comment]
Having next to no non-Brig pressurized rooms other than the courtroom may make breakouts from within the prison difficult.

**Comment by PestoVerde322** [comment]
I had a Git moment, Closing it to reopen a new PR.

**Pull request closed without merging**
