### PR TITLE
QUIRK REBALANCES AND CHANGES

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request

This PR changes some quirks  points and effects and remove some other. You start with a free -1 instead of 0 points so you get a free small ability without having to change your character for the worse (your character should be able to have a free trait that gives them something like giving good hugs without punishing the player with a negative trait).

## Why It's Good For The Game

The current points for the quirks are bad. Some nonsense quirks cost 2 points with no effect and then some other points make the game so much worse to play and give so little points in return.

<details>
<summary>REASONING</summary>

POSITIVE QUIRKS
(NEW, 2 POINTS) Alcohol Enjoyer: Combining alcohol tolerance + drunkhealing: We don't really need 2 different alcohol boost quirks and it's a buff since combined it should be 3
(2 -> 1 POINTS) Empath: Being able to tell how people feel doesn't warrant 2 points
(2 -> 1 POINTS) Freerunning: Being able to climb tables slightly faster doesn't warrant 2 points
(REMOVED) Plushie Lover: What this trait gives can be an item in the BeeCoin shop
(REMOVED) Musician: What this trait gives can be an item in the BeeCoin shop

NEUTRAL TRAITS
(+1 -> 0 POINTS) Linguist: You are able to know what language people are talking but not what they are saying. Wow. Arguably should be like this by default

NEGATIVE QUIRKS 
(0 -> -1) Mute: The only reason this isn't -2 points is because mimes could abuse it. Being mute considerably hinders your ability to communicate
(-1 -> -2) Alcoholic: Alcohol takes a kick out of your liver. Also -2 points means you can do the ultracombo and combine it with the new combined alcohol tolerance + drunkhealing to become an absolute alcohol unit, given that you start at -1
(-1 -> -2) Foreigner: You don't understand anyone and they can't understand you. Significantly alters the game for the worse.
(-1 -> -2) Poor aim: I think -2 points suits this better than -1 because of the implications it has. It's like having clumsy for weapons, and if clumsy was a trait it would probably be either -2 or -3 points.
(-2 -> -3) Trauma: Traumas can really affect your ability to play the game, can put you to sleep instantaneous without any counterplay, can even directly kill you.
(-3 -> -4) Paraplegic: I think the wheelchair and the annoyance of being someone at the mercy of everyone at all times it's 
(REMOVED) Deafness: I've never seen anyone use this trait. Is anti-rp, forces people to emote with you and is just too much of shooting yourself in the foot.

</details>

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

SOON
</details>

## Changelog
:cl: ClownMoff
add: Adds the plushie delivery beacon in the BeeCoin Shop, under the misc section
add: Adds the plushie instrument beacon in the BeeCoin Shop, under the misc section
del: Removes the plushie lover trait
del: Removes the musician trait
del: Removes the deaf trait.
tweak: The drunken resilience and alcohol tolerance traits have been combined for a +2 trait point called "alcohol enjoyer"
tweak: Freerunning is now a +1 trait instead of +2
tweak: Mute trait is now a negative trait that gives -1 point
tweak: Disabled trait now gives -4 points instead of -3
tweak: Linguist trait is now a neutral 0 points trait
tweak: Empath trait is now +1 point instead of +2
tweak: Phobia trait is now -3 points instead of -2 
tweak: Alcoholic trait is now -2 points instead of -1
tweak: Poor aim trait is now -2 points instead of -1
tweak: Foreginer trait is now -2 points instead of -1
/:cl:

### CODE REVIEW

**Comment by Rukofamicom** [comment]
Before I get too deep into this while I don't have the brainpower yet though I honestly do think the point system should just go away entirely after hearing various arguments and input from folks. 

The quirk system should have positive, neutral and negative quirks, but rather than keeping an exact score and trying to balance good with bad, it should just be a limit of like 2 positive quirks for everyone without forcing negatives to choose positives. This fosters the best use of the system for character creation instead of forcing yourself into negatives purely so you can access positives. 

Some people will still choose positives without regard for character and *that's just fine.* It's not worth worrying ourselves over, just let them have it. That goes for the heirloom stuff too, I just haven't gotten back to editing or closing my PR yet.

**Comment by Rukofamicom** [comment]
Moving certain quirks that just give you an item to the beecoin shop is a 100% solid change though. 👍

**Review by EvilDragonfiend — CHANGES_REQUESTED** [review]
linguistic trait is intentionally made to fool people not giving any hint if they're talking in a foreign language.
Thus the trait can bring impact to the game, it shouldn't be zero point.
For other quirks, I am fine with adjusting values, but I am not certain for removing.

**Comment by ClownMoff** [comment]
> linguistic trait is intentionally made to fool people not giving any hint if they're talking in a foreign language. Thus the trait can bring impact to the game, it shouldn't be zero point. For other quirks, I am fine with adjusting values, but I am not certain for removing.

It's kind of a dumb trait then, we should just combine it with the other language trait or something.

> but I am not certain for removing.
The "lovers" traits are just items, except musician which gives a mood boost

**Comment by EvilDragonfiend** [comment]
🔑Putting key due to the free linguist quirk.

**Comment by ClownMoff** [comment]
What about combining it as I said? You can speak one language and recognize other languages

**Comment by EvilDragonfiend** [comment]
> What about combining it as I said? You can speak one language and recognize other languages

No. Like I said, that's not what I intended there.

* https://github.com/BeeStation/BeeStation-Hornet/pull/7982

this is where the system was discussed. you can check how that came out.
This is something a big fire that everyone likes and dislikes
I do not intend giving people any hint about which language they're talking about.

**Pull request closed without merging**
