### PR TITLE
Ports non-binary from /tg/

### PR DESCRIPTION
**Pull request by 123chess456**
## About The Pull Request

Original PRs at tgstation/tgstation#44773 and tgstation/tgstation#44530. This makes it possible to be a gender-neutral for all species on SS13 (some species are already agender by default) with the following effects:

Gender-neutral spacepeople default to male sprite which is more androgynous than the female sprite. They can use facial hair and all types of underclothing, both male and female. They're also referred to as "they" when pronouns are used. Randomly generated people still default to either male or female. You must manually choose gender-neutral in prefs to enable it. Also gender-neutral changelings get the prefix "Mx." instead of "Ms." or "Mr." as that is the most commonly used gender-neutral honorific today.

## Why It's Good For The Game

Non-binary people deserve representation in-game and there's no real reason for declining this PR, even if you think it's made in "bad-faith" this code doesn't impact gameplay and adds representation for non-binary people, which is a laudable goal regardless of the motives of the author.

## Changelog
:cl: Shaps/Ryll
tweak: NT has updated its personnel policies and allowed for employees to register as gender neutral, with standard support for they/them pronouns.
/:cl:

### CODE REVIEW

**Comment by Oshibkka** [comment]
you do realize these are literally biologically immortal death machines that survive on the DNA of other living things right.

**Comment by ike709** [comment]
Doesn't even pass travis.

**Comment by St0rmC4st3r** [comment]
I remind that we had the pronouns and they were removed according to player votes.
I don't think we need stuff that players do not want and which doesn't even work.

**Comment by Sparrowbird611** [comment]
I use the same logic on this as I use on felinids. If this were already in the game, and this was a removal PR, I would say no to removing it, since it's already being used. However, since it's not in the game, and it adds nothing of value, I will vote no on adding this.

**Pull request closed without merging**
