### PR TITLE
[Port] Updates potted plant behavior

### PR DESCRIPTION
**Pull request by XeonMations**
## About The Pull Request

Instead of having snowflake code, makes kirbyplants use the brand new tactical component.

The tactical component just replaces the user's appearance with that of the parent item when equipped. Also the name.

Ports the following TGstation PRs:

- [x] https://github.com/tgstation/tgstation/pull/44044 (Partial, only tactical component)
- [x] https://github.com/tgstation/tgstation/pull/67083 (Partial, only /mob/proc/get_slot_by_item)
- [x] https://github.com/tgstation/tgstation/pull/70303 (Partial, only TRAIT_UNKNOWN parts.)
- [x] https://github.com/tgstation/tgstation/pull/70650 
- [x] https://github.com/tgstation/tgstation/pull/73745
- [x] https://github.com/tgstation/tgstation/pull/81570
- [x] https://github.com/tgstation/tgstation/pull/85567
- [x] https://github.com/tgstation/tgstation/pull/85852

## Why It's Good For The Game

Snowflake code bad, plus giving additional things features is nice.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/user-attachments/assets/ac294165-cf26-48ad-ad27-13470ef8a8bc

Talking with the plant also hides the message, even if wearing an ID and not covering your face.
image

</details>

## Changelog
:cl: ninjanomnom, Ghommie, Metekillot, MrMelbert, necromanceranner, Sealed101, XeonMations
tweak: Potted plants now hide your name when equipped.
add: Added TRAIT_UNKNOWN, when you have this trait, people will not be able to make out anything about you.
refactor: Potted plants are no longer snowflake code, instead uses the tactical component. 
/:cl:

### CODE REVIEW

**Comment by ColonelOrion** [comment]
Do they still allow you to hide a small thing?

**Comment by Rukofamicom** [comment]
Is this actually still a draft? Your to-do seems complete

**Comment by XeonMations** [comment]
> Is this actually still a draft? Your to-do seems complete

Yes, i am experiencing an issue with plant naming being done incorrectly.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
Works fine in basic testing.

**Pull request merged**
