### PR TITLE
MC Diagnostic Mode

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Adds in a diagnostic mode and subsystem tick reporting into the stat panel.
When the MC is in diagnostic mode, it will report all tick information to metrics so that it can be parsed in kibana. Note that this is a huge amount of data and should only be turned on when necessary.
Uses a circular queue so that it won't destroy performance.

We will probably need a kibana index in order to properly process the key'd data https://stackoverflow.com/questions/74989241/elastic-search-json-field-query-with-number-key

## Why It's Good For The Game

This will be really handy for finding out which subsystems are choking out the MC.

## Testing Photographs and Procedure

image

image

[message.txt](https://github.com/BeeStation/BeeStation-Hornet/files/13060294/message.txt)

## Changelog
:cl:
code: Adds in a diagnostic mode to the master controller.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Json output looks like this.
image

This might feed to kibana as master_controller.diagnostic_report.1128 but I'm hoping its smart enough to be able to filter those

**Comment by PowerfulBacon** [comment]
Testmerging without config changes, do not apply config changes until we get the all clear from crossed that the kibana stuff should be fine

**Review by EvilDragonfiend — DISMISSED** [review]
I think there should be an in-game fast toggle button to access this since changing config takes time but you might miss the moment while reconfiguring live servers (in case we set this system disabled in default.)

**Comment by PowerfulBacon** [comment]
> I think there should be an in-game fast toggle button to access this since changing config takes time but you might miss the moment while reconfiguring live servers (in case we set this system disabled in default.)

The toggle button simply changes if the data is being written to kibana or not, which I don't want people to activate unless they actually know what they are doing so making it highly acccessible would have people pressing it without knowing what it actually does.

**Comment by PowerfulBacon** [comment]
The tick proportions should be based on the tick time rather than relative to other systems, otherwise we cannot compare across ticks.

**Comment by EvilDragonfiend** [comment]
I still believe there should be a fast button to diagnose such critical issues when it's necessary, but if you think it's not necessary, whatever

**Review by itsmeow — APPROVED** [review]
Yeah this is fine

**Comment by PowerfulBacon** [comment]
image

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
