### PR TITLE
Adds Depleted Uranium Windows - For Rad-proofing areas

### PR DESCRIPTION
**Pull request by ro5490**
## About The Pull Request

PR adds a new window type, Depleted Uranium Windows (fulltile and directional)
These new windows have RAD_FULL_INSULATION and *should* fully block radiation from passing through them.
I however, suck at fusion and all things radioactive, so I couldnt test specific things really, but I managed to get a decent enough radioactive enviroment to test it.

## Why It's Good For The Game

All it takes is a couple sheets of uranium, and a moment.
Then?
Your fusion setup is *safe-ish*!
No more flooding the station with lethal amounts of radiation from your fusion setup!

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image
image
image
Screenshot_2
Screenshot_7
Screenshot_8

</details>

## Changelog
:cl:
add: Added Depleted Uranium Windows - created by using uranium in-hand
add: DU Windows block all radiation, make sure you've secured your setup with either fulltiles or two layers of directionals!
imageadd: added some icons for the above windows

/:cl:

### CODE REVIEW

**Comment by MNarath1** [comment]
First how about making them lead instead also don't make it windows but more like walls and don't make it a complete blocking maybe create an even higher blocking define for rads instead i don't think there should be any perfect protection against anything in the game especially not for rads

**Comment by LodedDiper69** [comment]
I don't like this change. There should be consequences for fucking up your fusion setup. Not every problem should be able to be easily countered.

**Comment by WrillWasTaken** [comment]
I was told diamond walls already did this

**Comment by Isy232** [comment]
> First how about making them lead instead also don't make it windows but more like walls and don't make it a complete blocking maybe create an even higher blocking define for rads instead i don't think there should be any perfect protection against anything in the game especially not for rads

Lead doesn't exist as a material right now and would require adding a whole new ore.

**Comment by MNarath1** [comment]
> > First how about making them lead instead also don't make it windows but more like walls and don't make it a complete blocking maybe create an even higher blocking define for rads instead i don't think there should be any perfect protection against anything in the game especially not for rads
> 
> 
> 
> Lead doesn't exist as a material right now and would require adding a whole new ore.

Just in name guess what the endproduct of uranium decaying so put it just in name and make it use uranium.

**Comment by Tyranicranger4** [comment]
> There should be consequences for fucking up your fusion setup. Not every problem should be able to be easily countered.

You need to consider the fact that round ending radiation leaks can happen from fusion even *if* it's properly setup. Right now high tier fusion is a dice roll on whether or not it's safe or causes an #INF radiation wave to sweep the station and get you bwoinked.

**Comment by MNarath1** [comment]
> > I was told diamond walls already did this
> 
> 
> 
> Diamond walls dont seem to have any rad protection, however diamond doors have the Extreme protection rating, which seems to only be 50%, so an INF rad would still irradiate the entire station unfortunatly
> 
> 
> 
> I might make this more expensive, as currently its 5 sheets for a directional, and 10 for a fulltile window
> 
> Maybe 15 for a directional and 30 for a fulltile as these grant complete rad protection

Caugh caugh isnumsafe macro

**Review by PowerfulBacon — APPROVED** [review]

**Comment by ro5490** [comment]
Approved almost a month ago, any chance of a merge <3

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
