### PR TITLE
Resprites lollipop.dmi

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
Resprites lollipops and gumballs

## Why It's Good For The Game
More color helps make the game feel vibrant

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
imageadd: replaces lollipop sprites
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
Eh, i'm personally a fan of regular lollipops with the different colors and this lollipop sprite is a little eh, though i do like the Gumballs, reminds me of the Jawbreakers from Ed, Edd & Eddie

**Comment by etherware-novice** [comment]
yea the gumball was based off a jawbreaker since all the gumball images i found were plain and i like the cool jawbreaker patterns

**Comment by BrumalLake** [comment]
isn't there still grayscale code

**Comment by PowerfulBacon** [comment]
Your testing evidence clearly shows its broken
image
image
If you find a problem in testing, you need to actually fix it, testing is for you, the evidence is for us

**Comment by itsmeow** [comment]
Lollipops use grayscale to do different coloring (like Dum-Dums), they should use the old sprite. I like the gumball though.

**Comment by itsmeow** [comment]
Maybe use the jawbreaker sprite for another item since gumballs usually implies "brightly colored gumball in a gumball machine"

**Pull request closed without merging**
