### PR TITLE
Corg Compact Medbay

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Replaces the mini dome with a compact medbay.

image

Contains
* Rad and burn kit
* Two Medkits
* Surgery Tools (scalpel, hemostat, retractor and searing tool)
* Roller Bed
* One epi bottle, one charcoal bottle, one syringe
* One mediborg

## Why It's Good For The Game

* The Minidome has no purpose
* Engineering is far away from medbay
* The station is spread out 

## Changelog
:cl:
add: Compact Corg Medbay
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
1. Why is it in space
2. The map is not in the correct format.
3. This is one of my favourite parts of the map and why would there be a mini medbay there randomly to circumvent medical entirely?

**Comment by PowerfulBacon** [comment]
This part of the map is a recreational, all access area and won't be made into a mini-medbay for reasons above.

**Comment by eeSPee** [comment]
> 1. Why is it in space

Those are fake space floors.

> 2. The map is not in the correct format.

Working on it.

> 3. This is one of my favourite parts of the map and why would there be a mini medbay there randomly to circumvent medical entirely?

The area usually goes ignored completely.

The compact medbay is not there to circumvent medbay entirely, it's a place where you can treat people who are in crit or heal smaller wounds.

Trying to overcome Corg's flaw that it's wide and the departments are far apart. If the main hall gets plasmaflooded/breached, the only way to get from engineering to medbay is through outer space.

**Comment by bloons3** [comment]
Tiders do not need additional medical supplies.

If you want emergency medical supplies for players to use, stick them in a wallsafe tied to red-alert, like how escape pods do it.

**Pull request closed without merging**
