### PR TITLE
Fixes cybernetic hearts turning into regular hearts

### PR DESCRIPTION
**Pull request by RDS88-beeman**
## About The Pull Request
Cybernetic hearts would formerly (permenantly) swap icon states into normal, ordinary person hearts whenever they stopped beating. This mostly affected IPCs, as they start with cybernetic hearts by default. This fixes that bug. Now cybernetic hearts will properly show up like cybernetic hearts, even when the person they're in is reduced to a fine paste.

This entire feature could use a refactor but I am NOT the man for the job.

## Why It's Good For The Game
Bug bad. This is a bug that annoyed me and only me, but bug bad.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

in this video you can see me gib an IPC, and watch their heart stop beating. On the current server, this would cause their heart to take on a normal appearance. As you can see, it no longer does.

https://github.com/user-attachments/assets/88e8ef30-dfd9-4f4f-a92f-d0703f803e97

</details>

## Changelog
:cl:
fix: IPCs no longer contain fleshy human hearts in disguise.
/:cl:

### CODE REVIEW

**Comment by RDS88-beeman** [comment]
wait shit this doesn't work give me a minute

**Comment by PowerfulBacon** [comment]
Describe the testing process and include screenshots/videos.

**Comment by Rukofamicom** [comment]
You can open the `View Variables` screen with a right click on yourself, and then in the drop down box in the upper right there is a `Manipulate Organs` option. Use this to drop your heart on the ground and it will beat for a while until it stops and you can record that.

**Comment by RDS88-beeman** [comment]
testing evidence added

**Review by Rukofamicom — APPROVED** [review]

**Pull request merged**
