### PR TITLE
Tgui list fixes

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

keys are now locked up when using the list
pressing space or enter will select the thing you selected

## Why It's Good For The Game

yes

## Changelog
:cl:
code: improved tgui list
/:cl:

### CODE REVIEW

**Review by stylemistake — COMMENTED** [review]
Backport to tg please.

**Review by francinum — APPROVED** [review]
Better.

**Comment by francinum** [comment]
I still think this is far more obnoxious to use than standard calls to input, but I also don't have the energy or shits to give to bother tearing out your changes.

**Comment by francinum** [comment]
Fuck it yes I do.

**Pull request closed without merging**
