### PR TITLE
Tail entwinement but it actually compiles and has credits.

### PR DESCRIPTION
**Pull request by ghost**
## Changelog
:cl: MCterra10, Optimumtact
add: Added Tail entwinement.
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
*clap

**Comment by Blueturbo47** [comment]
Now we add it for the meme?

**Comment by Flakkyboo** [comment]
Going for the hattrick

**Comment by Naevii** [comment]
Is it april fools again ?

**Comment by PowerfulBacon** [comment]
can we ban the next person that makes one of these prs? @ike709

**Comment by Flakkyboo** [comment]
Another one bites the dust

**Comment by ike709** [comment]
@PowerfulBacon sure

**Pull request closed without merging**
