### PR TITLE
Adds unused clothing to drobes and brig phys winter coat to loadout

### PR DESCRIPTION
**Pull request by Hardly3D**
## About The Pull Request
Partial revival of #6978, but without the map changes seeing they're added by #8434 

This PR adds some unused clothing found in the code into the clothesdrobe and autodrobe, allowing them to be obtained through normal means.

New clothing include:

Clothesmate

    Moved autodrobe's beret to clothesmate (not to be confused with mime's french beret)
    Black beret

Autodrobe

    Pharaoh hat
    Gothic coat
    Dracula coat
    Draculass coat

Brig Phys' winter coat can also be bought from the loadout shop now for the cheap price of 5000 beecoins
Same for Gothic coat but for 8000 beecoins like every other jacket

## Why It's Good For The Game

More variety on drip to wear and consistency as brig phys coat is the only one that can't be bought with beecoins (afaik)

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

Z3s1oUryUY
PWUR49OLz6
kzCzKKyyue

</details>

## Changelog
:cl: Hardly
add: Added black beret to clothesmate
add: Added unused clothing such as pharaoh hat, gothic coat, dracula coat and draculass coat to autodrobe
tweak: Moved the beret from autodrobe to clothesmate
add: Brig Physician's Winter Coat can now be bought for 5000 beecoins.
add: Gothic Coat can now be bought for 8000 beecoins.
/:cl:

### CODE REVIEW

**Comment by Nakalon** [comment]
OH MY GOD THANK YOU!?

**Comment by Nakalon** [comment]
gOTHIC COAT TO BEESHOP MAYBE PRETTY PLEASE WITH SUGAR ON TOP?

**Comment by Harranhall** [comment]
Maintainers please look at this when convenient!

**Comment by Hardly3D** [comment]
Gothic coat slaps so I'm adding it as well

**Comment by Harranhall** [comment]
Are jackboots able to be added? They're in the costumedrobeand maints spawn list so they're not security only.

**Review by Penwin0 — APPROVED** [review]

**Pull request merged**
