### PR TITLE
Modern Dynamic

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

Ports:
- https://github.com/tgstation/tgstation/pull/56869
- https://github.com/tgstation/tgstation/pull/59463
- https://github.com/tgstation/tgstation/pull/59468
- https://github.com/tgstation/tgstation/pull/60281
- https://github.com/tgstation/tgstation/pull/60669
- https://github.com/tgstation/tgstation/pull/60988
- https://github.com/tgstation/tgstation/pull/61370
- https://github.com/tgstation/tgstation/pull/61704
- https://github.com/tgstation/tgstation/pull/61869
- https://github.com/tgstation/tgstation/pull/62258
- https://github.com/tgstation/tgstation/pull/63305
- https://github.com/tgstation/tgstation/pull/63759
- https://github.com/tgstation/tgstation/pull/63810
- https://github.com/tgstation/tgstation/pull/65417
- https://github.com/tgstation/tgstation/pull/65997
- https://github.com/tgstation/tgstation/pull/67295
- https://github.com/tgstation/tgstation/pull/67538
- https://github.com/tgstation/tgstation/pull/67615
- https://github.com/tgstation/tgstation/pull/67823
- https://github.com/tgstation/tgstation/pull/67882
- https://github.com/tgstation/tgstation/pull/68137
- https://github.com/tgstation/tgstation/pull/68571

If this goes well I need to port some more dynamic rulesets (roundstart malf ai, midround non-ghost blob (it makes pustules on a random player basically), space dragon, space ninja)

## Why It's Good For The Game

Dynamic is great, but it can be better. It should be the main gamemode. It just needs some work. Now it will actually do midrounds instead of not spending its ridiculous amounts of threat, the weights are better balanced, etc.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

The game loads if you set it to dynamic. That's the best I can do. Needs some testmerging.

</details>

## Changelog
:cl: itsmeow, Mothblocks, Y0SH1M4S73R, IndieanaJones, Iamgoofball, wesoda25, Watermelon914, tf-4, Ghommie, JohnFulpWillard, Mooshimi, MrMelbert
balance: Changed most dynamic weights, threats, and minimum player requirements. They will all be different and hopefully more balanced now.
fix: dynamic will no longer spawn abductors if there aren't enough applicants for a proper 2-person abductor team
add: Revenant, Space Pirates, and Obsessed have been added to dynamic mode.
fix: Fixes the lone operative event hardly ever rolling even if the disk is left on the same place for hours on dynamic.
server: Dynamic now has an extra configuration value, max_threat_level. Defaults to 100 threat.
balance: Makes wizard a high impact ruleset.
fix: A lack of candidates for certain antags will no longer runtime
balance: Midround rolls will now happen more frequently, with their power scaling up over time.
fix: Fixed midrounds not logging properly.
qol: Ghosts will now see the name of who rolled a midround instead of the new midround's character name.
balance: Winning dynamic revs no longer adds midround threat. Instead, it'll force a heavy ruleset to spawn, and barring that, will spawn a dangerous random event.
server: Added more dynamic logging
/:cl:

### Traitor Midround (Sleeper)
Lower cost
Higher weight
Now requires minimal threat / players

### Malf AI Midround (Ion)
Lower cost
Lower weight
Now requires 25 players minimum

### Wizard Midround (Ghost)
Lower cost
Now requires VERY high threat / players

### Nukeops Midround (Ghost)
Lower cost
Now requires 70min into round
Now requires VERY high threat / players

### Blob Midround (Ghost)
Lower cost
Lower weight
Now requires 35min into round
Now requires 25 players minimum

### Xeno Midround (Ghost)
Higher weight
Now requires 40min into round
Now requires 25 players minimum

### Nightmare Midround (Ghost)
Lower cost
Now requires 15 players minimum

### Abductor Midround (Ghost)
Lower cost
Now requires 25 players minimum

### Revenant Midround (Ghost)
Added
Low cost/weight (similar to nightmare)
Requires 15 players minimum

### Pirates Midround (Ghost)
Added
Medium cost/weight (slightly more common than blob)
Requires 27 players minimum

### Obsessed Midround
Added
Low cost/weight (lower than revenant)

### Traitor Roundstart
Lower player/threat requirement

### Blood Brothers Roundstart
Lower cost
Lower weight

### Heretics Roundstart
Now requires 18 players

### Wizard Roundstart
Is no longer a "lone" ruleset, but still considered "high impact" and will be one of few high impact spawns
Made less common on lowpop

### Traitor Latejoin
More common in general, especially lowpop

### Revolutionary Provocateur Latejoin
Lower cost (still considered high impact and won't spawn with other high impact stuff)

### Heretic Latejoin
Lower cost
More common on ultra-highpop/ultra-highthreat

### CODE REVIEW

**Comment by giacomoh** [comment]
wow, thank you kat

**Comment by itsmeow** [comment]
basically ided because i was observing a round with **30 midround threat**

it spent none of it

thanks dynamic

**Comment by Crossedfall** [comment]
Round two lets goooo

- https://github.com/BeeStation/BeeStation-Hornet/pull/3797

**Comment by itsmeow** [comment]
CL fixed

**Comment by Mat05usz** [comment]
Unfathomably based, thank you <3

**Comment by Fronsis** [comment]
Bless you, the change we needed!!!

**Comment by FortSumter** [comment]
If this is what it takes to get dynamic as the main game mode I'm all for it!

**Comment by itsmeow** [comment]
First two TM rounds

```
Round Number: 39760
Duration: 1 hour and 30 minutes and 8.8 seconds
Players: 36
Survivors: 7
Escapees: 0
Integrity: 99.6
Gamemode: dynamic mode
Threat level: 79.4
Threat left: 10.4
Executed rules:
Roundstart - Traitors: -8 threat
Roundstart - Heretics: -24 threat
Roundstart - Changelings: -16 threat
Midround - Syndicate Sleeper Agent: -3 threat
Midround - Syndicate Sleeper Agent: -3 threat
Midround - Syndicate Sleeper Agent: -3 threat
Latejoin - Syndicate Infiltrator: -5 threat
Midround - Nuclear Assault: -7 threat
```

```
Round Number: 39762
Duration: 1 hour and 11 minutes and 36 seconds
Players: 25
Survivors: 14
Escapees: 12
Integrity: 97.8
Gamemode: dynamic mode
Threat level: 48.8
Threat left: 27.8
Executed rules:
Roundstart - Blood Brothers: -12 threat
Midround - Syndicate Sleeper Agent: -3 threat
Midround - Syndicate Sleeper Agent: -3 threat
Midround - Syndicate Sleeper Agent: -3 threat
```

Seems to actually be doing its job and spawning midrounds. This is great!

**Comment by itsmeow** [comment]
Highpop highthreat

```
Round Number: 39771
Duration: 1 hour and 9 minutes and 50 seconds
Players: 62
Survivors: 40
Escapees: 30
Integrity: 98.5
Gamemode: dynamic mode
Threat level: 88.8
Threat left: 7.8
Executed rules:
Roundstart - Changelings: -26 threat
Roundstart - Nuclear Emergency: -20 threat
Roundstart - Traitors: -8 threat
Latejoin - Heretic Smuggler: -7 threat
Midround - Nightmare: -5 threat
Midround - Syndicate Sleeper Agent: -3 threat
Latejoin - Syndicate Infiltrator: -5 threat
Midround - Abductors: -7 threat
```

Looking really great. The crew is even escaping despite these super high threats. Seems pretty balanced.

```
Round Number: 39768
Duration: 1 hour and 10 minutes and 28.3 seconds
Players: 49
Survivors: 42
Escapees: 28
Integrity: 93.6
Gamemode: dynamic mode
Threat level: 65.2
Threat left: 1.2
Executed rules:
Roundstart - Blood Cult: -20 threat
Roundstart - Traitors: -8 threat
Roundstart - Heretics: -15 threat
Midround - Syndicate Sleeper Agent: -3 threat
Latejoin - Syndicate Infiltrator: -5 threat
Midround - Blob: -8 threat
Midround - Revenant: -5 threat
```

**Comment by FortSumter** [comment]
Mid round nuclear assault  got me like 0.0

**Comment by itsmeow** [comment]
```
Round Number: 39782
Duration: 2 hours and 19 minutes and 58.9 seconds
Players: 41
Survivors: 33
Escapees: 32
Integrity: 99.2
Gamemode: dynamic mode
Threat level: 4
Threat left: 4
Executed rules:
```

**Comment by itsmeow** [comment]
Other than missing logging, no runtimes or major issues.

**Review by PowerfulBacon — APPROVED** [review]
Spawned every single gamemode except clockies and revs and 0 runtimes

**Comment by Isy232** [comment]
Nukies could definately cost more points. Since its only worth 20 it tends to spawn a dozen antags on the station who's round gets cut short very early.

Its fine if it happens sometimes, however just from experience it seems to be happening quite a lot recently.

Sometimes you do just loose through no fault of your own, and thats fine in a roleplaying game, but when it happens too much it gets really annoying.

**Comment by heepox** [comment]
What if Black orbit (100 threat) from TG that you can set with ninja glove interaction with comms console.

**Comment by itsmeow** [comment]
> Nukies could definately cost more points. Since its only worth 20 it tends to spawn a dozen antags on the station who's round gets cut short very early.
> 
> Its fine if it happens sometimes, however just from experience it seems to be happening quite a lot recently.
> 
> Sometimes you do just loose through no fault of your own, and thats fine in a roleplaying game, but when it happens too much it gets really annoying.

The threat cost scales based on player counts and how many nukies accept as far as I can tell, so in this case a lot of changelings spawned artificially scaling their threat. 20 is actually an insanely high threat.

**Comment by PowerfulBacon** [comment]
Add the missing logging you mentioned and ping me when ready

**Comment by itsmeow** [comment]
Logging was already added @PowerfulBacon 367128f5ffc9f6fdc7a16f6f0f73a56a85183ae5

**Comment by itsmeow** [comment]
Nukeops have the same midround weight as xenos, but lower cost and require at least 70mins into a round with very high threat requirement.

Nukeops roundstart has the same weight and requirements as blood cult - and you can't have both.

I'm going to say the server just got unlucky and rolled nukeops a bit much.

**Pull request merged**
