### PR TITLE
auto punctuation

### PR DESCRIPTION
**Pull request by CthulhuOnIce**
a

<hr>

b

### CODE REVIEW

**Comment by CthulhuOnIce** [comment]
the fuck is wrong with travis?

**Comment by qwertyquerty** [comment]
Examine indication? Auto punctuation? What are we genesis

**Comment by qwertyquerty** [comment]
Also if I say "Where's muh laser pointer" it goes to "Where's muh laser pointer."

**Comment by ike709** [comment]
It should check if the first word is who/what/when/where/why/how and use a question mark instead.

**Comment by ike709** [comment]
Bonus points if it puts an exclamation mark if the message is all caps.

**Comment by ike709** [comment]
Gotta make sure say() is as bloated as possible.

**Comment by qwertyquerty** [comment]
This is highly dumb

**Comment by qwertyquerty** [comment]
For one I can't say things like

"Wh-"
"What?"

For two it's just dumb, not something we need

**Comment by CthulhuOnIce** [comment]
@qwertyquerty now you can

**Comment by CthulhuOnIce** [comment]
> 
> 
> Examine indication? Auto punctuation? What are we genesis

genesis has neither of these things

**Comment by qwertyquerty** [comment]
Yeah but they are both HRP'y things and we are NOT HRP.

**Comment by ike709** [comment]
Nobody is forcing you to be LRP. But since you closed https://github.com/BeeStation/BeeStation-Hornet/pull/81 I'm going to use that closure as justification for closing this.

**Comment by CthulhuOnIce** [comment]
I didn't close that shid

**Comment by CthulhuOnIce** [comment]
also since when is a period HRP? the same could be said for the auto capitalization

**Comment by qwertyquerty** [comment]
It's simply unneeded. There will be times where people want to say something without punctuation I garentee it. Also last time I checked it takes about 0.1 seconds to add a period.

**Comment by qwertyquerty** [comment]
#81 was downvoted too

**Comment by ike709** [comment]
#81 was downvoted by *one person* other than you. And it was upvoted by one person.

For a server of bee's size, it's not enough to be indicative of what the community wants. Bee players suck at leaving feedback on PRs.

**Comment by CthulhuOnIce** [comment]
> Also last time I checked it takes about 0.1 seconds to add a period.

shame no one ever does it

**Comment by qwertyquerty** [comment]
My comment on us being LRP was upvoted though.

Also I might make an announcement telling players how to feedback on PRs

**Comment by CthulhuOnIce** [comment]
the thing is this PR doesn't actively prevent you from saying things, it just adds one character if needed

**Comment by CthulhuOnIce** [comment]
this PR is much more unobtrusive

**Comment by Tumesuo** [comment]
Are things like :) gonna get a punctution mark too or are they too much ock in ick

**Comment by CthulhuOnIce** [comment]
They'll get punctuated, but don't use emoticons, even though we're lrp it makes people look dumb

**Comment by CthulhuOnIce** [comment]
@Tumesuo

**Comment by qwertyquerty** [comment]
@CthulhuOnIce I don't think there is a need to punctuate custom emotes, that's just dumb

**Pull request merged**
