### PR TITLE
Decreases non-traitor mime forcewall duration. Traitor mime forcewall is still very good.

### PR DESCRIPTION
**Pull request by Isy232**
## About The Pull Request

This decreases the time of the mimes forcewall from 300 to 100.
In effect it should go from 30 seconds to 10 seconds.

The forcewall traitorish mimes can get is unchanged.
It lasts 60 seconds and is a 3x1 instead of 1x1 wall.
So if a mime does invest TC into forcewall it becomes much better.

## Why It's Good For The Game

A 30 second forcewall is far too strong for a non-antag roundstart power.

In the age of tasers dropping you in 1 shot and combat often taking half a second this power was balanced.

Now with stamina combat fights last much longer and are more dynamic. Many things have been nerfed but one of the things that was never nerfed was the mimes forcewall.

The issue with this power is that if you're loosing a fight you can just drop a wall behind you and nobody can chase. This gives you near infinite power to choose fights as long as you are in 1 tile wide hallways.

In the time of old it was hard to escape using this power as you'd have to use it before you got hit once with a taser.

Now they have to shoot you 3 times with a disabler or melee you twice with a stun baton. Then even when you enter stamcrit you are not immediately knocked down. This makes the mimes forcewall exceptionally overpowered, especially when combined with other antagonist types. Combining an antagonist with plentiful escape abilities like changeling with with this forcewall makes 

Now, this does not entirely remove the wall, but just lowers its duration so that its more decently balanced and while still powerful isn't a fix all for loosing a fight in maint anymore.

Note: I have not nerfed the mimes advanced forcewall they can get from the traitor mime book. That is still a 3v1 forcewall that lasts for a full minute. If the mime invests TC into it they can still get an eqivalent of the wizards forcewall spell.

## Changelog
:cl:
balance: Mime forcewall duraction from 30 seconds to 10 seconds.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
make the traitor advanced mimery book gives you the prenerf forcewall?

**Comment by Isy232** [comment]
> make the traitor advanced mimery book gives you the prenerf forcewall?

The traitor forcewall is better than the normal forcewall.

The traitor forcewall is 1x3 instead of 1x1 so you can block off an entire hall and lasts an entire minute.

**Comment by super12pl** [comment]
> Decreases non-mime forcewall duration. Traitor mime forcewall is still very good.

You are sure about that?

**Comment by Rukofamicom** [comment]
seems this title should have said "non-traitor forcewall"

**Comment by Isy232** [comment]
> > Decreases non-mime forcewall duration. Traitor mime forcewall is still very good.
> 
> You are sure about that?

> seems this title should have said "non-traitor forcewall"

Lol, spelling mistake, fixed it.

Yes, this only decreases the non-traitor mime forcewall duration.

**Comment by VictorVow** [comment]
Good change. Instantly placed, invisible, indestructible, infinite charge forcewall shouldn't also last ages.

**Comment by Unidentified-Biohazard** [comment]
very nice

**Review by qwertyquerty — APPROVED** [review]

**Comment by ItsTisme** [comment]
Finally its not a free escape in maints

**Pull request merged**
