### PR TITLE
Remove hardcoded beepsky wizard discrimination

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

This makes it so wizard+witch clothes don't piss off beepsky

## Why It's Good For The Game

Kinda dumb being beepskied over fashion choice

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Can't really show this easily, as my experience on the server is that beepsky targeting you over this is... _very_ inconsistent

</details>

## Changelog
:cl:
del: Wizard/witch clothes no longer piss off beepsky 4noraisin.
/:cl:

### CODE REVIEW

**Comment by VickiMorris** [comment]
Is Beepsky still racist? Where non-humans have an automatic +1 to their threat?

**Comment by Absolucy** [comment]
@VickiMorris yep!

**Comment by hotimep** [comment]
> Is Beepsky still racist? Where non-humans have an automatic +1 to their threat?

feature keep it in

**Review by EvilDragonfiend — APPROVED** [review]
Either removal of this or making it standard code works to me, and this is fine.

**Comment by PowerfulBacon** [comment]
I don't see why these shouldn't set beepsky off

**Comment by tontyGH** [comment]
wizard buff????

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Give a convincing reason as to why this is good for the game

**Comment by Absolucy** [comment]
@PowerfulBacon because it's just... not very fun when beepsky decides to fuck you up because you decided to wear a witch hat from the autodrobe?

**Comment by PowerfulBacon** [comment]
I mean, in the eyes of beepskys and turrets, if you look like a threat then the machines will treat you like a threat. I would argue that more things like replica space-suits should cause false positives on machines like beepskys so that they can be wrong

**Comment by PowerfulBacon** [comment]
The reason this may feel inconsistent is because of the way that threat takes into account small variables that stack up. Simply wearing wizard clothes isn't enough to get you arrested as it needs at least 4 to mark you as being a beepsky target. If you wear wizard clothes and are marked as incarcarated then it will attack you. If you wear wizard clothes, are a felinid and are marked as search then it will attack you.
Removing this check doesn't make much sense, its part of the clothes and part of the gimmicky nature of both the toy clothes and beepsky (to emulate the real thing).

**Pull request closed without merging**
