### PR TITLE
Adds laughing gas clown internals

### PR DESCRIPTION
**Pull request by Jake-Wheal**
## About The Pull Request
This is a port of https://github.com/tgstation/tgstation/pull/47342 by genessee596 that adds a unique emergency oxygen tank called the emergency prank tank. The tank contains a very small quantity of N2O which is just enough to make the clown (or whoever steals it) giggle a bit without making them fall asleep. The tank also has its own unique sprite -
image

On a final note, the commits of this PR show changes to rust_g.dll but there aren't any changes to it in the final pull. I am new to all this GitHub repo business and I somehow screwed it up, it should be back to whatever it was before.

## Why It's Good For The Game
Clowns already get a bunch of unique clown items in their bag so its no big thing to give them another one with a simple purpose, its better then the clown breaking into atmos to get laughing gas. Also the original TG PR is is on the things to port list so clearly one of you maintainers already thinks this is good for the game

## Changelog
:cl: genessee596
add: Added emergency prank tank in the clowns emergency box
/:cl:

### CODE REVIEW

**Comment by MNarath1** [comment]
Sometimes stuff like rust_g seems to happen i recommend looking trough the file changes you want to make a commit for before and discharge any superficial file changes that pop up like rust_g

**Comment by Jake-Wheal** [comment]
> Sometimes stuff like rust_g seems to happen i recommend looking trough the file changes you want to make a commit for before and discharge any superficial file changes that pop up like rust_g

I normally do but I must've miss clicked or something, I should really be more careful

**Comment by utilbird** [comment]
did you have DD open in the background? That can sometimes lead to the rust anomaly

**Comment by utilbird** [comment]
I've had it happen to me with the DME too

**Comment by Jake-Wheal** [comment]
> did you have DD open in the background? That can sometimes lead to the rust anomaly

umm, I may well have done

**Comment by ike709** [comment]
Try pushing an empty commit to get IconDiffBot to run.

**Review by utilbird — DISMISSED** [review]
honk

**Comment by TheFakeElon** [comment]
I'll get you someday.. green tick

**Review by park66665 — APPROVED** [review]
CL and icons are fixed and checked. Good to go.

**Pull request merged**
