### PR TITLE
get_hear and get_hearers_in_view optimisations

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Optimises get_hear and get_hearers_in_view.
After doing a quick profile it turned out these procs were quite expensive, and looking into both of them there was something both of them had in common: they both altered turf luminosity before doing a simple view (which alone shouldn't be expensive).
After creating a quick testing verb and running it, it turns out dview() in all cases ran quicker than changing the lum count and calling view().
This replaces the lum changing get_hear and get_hearers_in_view with a dview call instead.

## Why It's Good For The Game

Optimisation

## Changelog
:cl:
tweak: Optimises get_hear and get_hearers_in_view to use dview instead of changing the luminosity of the turf beneath it.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Ironically I haven't tested the tests since I don't know how, but we will see if they pass

**Comment by PowerfulBacon** [comment]
Not sure why that's failing, its not the test failing but something else.

**Comment by PowerfulBacon** [comment]
I can't get the tests working

**Comment by PowerfulBacon** [comment]
Alright thats not my fault, someone run the tests again later

**Comment by PowerfulBacon** [comment]
This works in game but needs more conclusive tests to determine if the performance increase is significant. In testing / theory it was.

**Comment by PowerfulBacon** [comment]
actually I can't tell if this is better or not, someone needs to do proper tests.

**Review by Archanial — APPROVED** [review]

**Pull request merged**
