### PR TITLE
replaces the normal sunglasses in the detectives office with a sechud

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

gives the detective a sechud instead of normal sunglasses

## Why It's Good For The Game
theres no reason why they shouldnt have one.

## Changelog
:cl:
add: replaced the normal sunglasses in the detectives offices with a sechud
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
The reason they don't have them is because they are intended to investigate crimes rather than hunt down criminals, and thus don't need to know whether or not someone is wanted.

**Comment by ghost** [comment]
> 
> 
> The reason they don't have them is because they are intended to investigate crimes rather than hunt down criminals, and thus don't need to know whether or not someone is wanted.

they are still security and are capable of making arrests, also invesigating is like 10% of your time as detective.

**Comment by Cenrus** [comment]
I don't like detcurity very much

**Comment by ghost** [comment]
> 
> 
> I don't like detcurity very much

bruh literally every detective gets a sechud from security anyway, this will only change that he now gets it roundstart.

**Pull request merged**
