### PR TITLE
ChemMaster can now input a target volume and preset packaging name + chat filter check

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

You can now switch the output mode from "auto" to a specific volume amount, allowing for more precise creation of pill dosages.

Doing a bunch of division just to get the right dosage is a pain, nobody likes it, and it doesn't make the game any better or more fun/balanced.

Created in response to this comment @Coding-Grape

https://github.com/BeeStation/BeeStation-Hornet/pull/7324#issuecomment-1192060234

You can also set the naming mode to Manual and it will bypass the name input and use the name in the text box - it's also persistent and shared state, so the name will stay if you close the UI.

## Why It's Good For The Game

ChemMasters are more usable, as dosages can be set more precisely.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image

image

image

image

image

</details>

## Changelog
:cl:
tweak: ChemMasters now have an exact output units mode for pills/patches/bottles.
tweak: ChemMasters can now have a set name input to use for all pills, instead of prompting every time.
admin: ChemMaster packaging names are now subject to the IC filter.
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
Blessed

**Comment by itsmeow** [comment]
image

**Comment by EvilDragonfiend** [comment]
can we have a `u` in the label?

**Comment by EvilDragonfiend** [comment]
also, how does it fill when it has `10u water, 10u ethanol, 10u oxygen` and exact mode is `6u`?

**Comment by itsmeow** [comment]
Good question, I forgot to test that.

**Comment by itsmeow** [comment]
> can we have a `u` in the label? so it becomes `10u`

Last commit added that, I just didn't include screenshot

**Comment by itsmeow** [comment]
10u tox, 10u charcoal in buffer.

Created 2x 7.5u pills. Grinding result is in the beaker.

Works perfectly.
image

**Comment by Coding-Grape** [comment]
Simply incredible, will actually give us a reason to upgrade the beakers in the chemmaster and not do dumb shit with chem factories to avoid using the chemmaster at all costs.

Can we also make it so we can set a custom name for the chemical bottles/pills/patches without having to paste it in that god awful pop up and hope you didn't mess up every batch? That would fix like all of the reasons I prefer using chemical factories for bulk complex pills
 (reaction chamber that grabs specific amounts of each reagent from a tank and passes them to a press)

**Comment by itsmeow** [comment]
> Simply incredible, will actually give us a reason to upgrade the beakers in the chemmaster and not do dumb shit with chem factories to avoid using the chemmaster at all costs.
> 
> Can we also make it so we can set a custom name for the chemical bottles/pills/patches without having to paste it in that god awful pop up and hope you didn't mess up every batch? That would fix like all of the reasons I prefer using chemical factories for bulk complex pills
>  (reaction chamber that grabs specific amounts of each reagent from a tank and passes them to a press)

I can make the name a tgui text input field, but the problem is players like the auto population part. An auto toggle for the name as well?

**Comment by Coding-Grape** [comment]
> I can make the name a tgui text input field, but the problem is players like the auto population part. An auto toggle for the name as well?
Yeah, sometimes it's good (single chem pills)

But when you're mass producing stuff like 1/2 or 2/4 perflurodecalin/antitoxin pills and have to constantly select and paste over the name it wants to give it (something like 6u of antitoxin) it's just a chore, especially if you mess up while going fast and name 10 pills something ever so slightly different and they don't stack now

**Review by Penwin0 — APPROVED** [review]

**Pull request merged**
