### PR TITLE
Adds another space ambience track.

### PR DESCRIPTION
**Pull request by AnCopper**
## About The Pull Request

Adds another space ambience track.

## Why It's Good For The Game

More ambiance is cool I guess.

## Testing Photographs and Procedure

<details>

<summary>Screenshots&Videos</summary>

Put screenshots and Videos documenting testing and execution of intended behaviors here

</details>

## Changelog
:cl:
add: added another space ambience track.
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
Credits and source of the track?

**Comment by AnCopper** [comment]
> Credits and source of the track?

I took a random piece of music and slowed it down in audacity.

**Comment by Archanial** [comment]
Doesn't change the fact you need to credit original author and the song piece has to compatible with our license

**Comment by AnCopper** [comment]
> Doesn't change the fact you need to credit original author and the song piece has to compatible with our license

Song: Fires of Hokkai.
Composer: Jun'ya Ōta

It's taken from Touhou, which is borderline public domain.

More on that here: https://touhou-project.news/guidelines_en/

I however don't think that Space Station 13 constitutes as "Fan Content".

**Comment by Raven-Industries** [comment]
Using music straight from a game is not exactly the same as creating a fan work based upon certain characters or a theme. I think it's reasonable to say that this would fall afoul of copyright law, unless you can find some source which indicates the track was released under a creative commons license (or similar) which allows redistribution and derivative works. 
Edit: slowed down version has some great 'I just woke an eldritch being' vibes.

**Comment by AnCopper** [comment]
> 
image

image
You're right.

**Pull request closed without merging**
