### PR TITLE
Removes a certain d20's ability to be refreshed.

### PR DESCRIPTION
**Pull request by mystery3525**
## About The Pull Request

Removes the ability for the Anomalous Crystal's refresh ability to "refresh" the die of fate.

## Why It's Good For The Game

We've heard from the griefers themselves that the 1 in 7 chance of refreshing the single-use die of fate is able to be abused, also why CAN this be refreshed?

Alternative to https://github.com/BeeStation/BeeStation-Hornet/pull/8654

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
balance: Anomalous crystal can no longer refresh the die of fate
/:cl:

### CODE REVIEW

**Comment by mystery3525** [comment]
Fat-fingered VSC's built in create-pull request feature. oops.

**Comment by mystery3525** [comment]
- every label except balance

**Comment by Rukofamicom** [comment]
As stated on my PR and the handful of times I was asked to change my PR to do this instead:

I much prefer the ability to refresh the die for its other multitude of effects than keeping it truly single use with one of the options still including wizard

Removing the ability to refresh this item results in far less fun opportunities all around, and keeping it allows two facets of lavaland rewards to interact with each other.

**Comment by itsmeow** [comment]
🔑 both other solutions are better

**Review by PowerfulBacon — APPROVED** [review]
I think this is my favourite solution considering other magic items are already immune

**Review by Penwin0 — APPROVED** [review]
Definetly shouldn't be refreshable, even past wizard rolling, even if wizard rolling were impossible it'd still be an issue

**Pull request merged**
