### PR TITLE
Goliath Taming

### PR DESCRIPTION
**Pull request by TeomanTheGreat**
## About The Pull Request
Adds Goliath taming from TG and my own creation Gold Grub meat to tame them 
Heres the TG PR https://github.com/tgstation/tgstation/pull/49003

## Why It's Good For The Game
Now miners and ash lizards can vibe around on goliaths

## Changelog
:cl:
add: Gold grub meat
add: Goliath riding and taming
add: The Lasso and Saddle from TG
add: Adds code that allows you to ride goliaths with a lasso and saddle
imageadd: Gold Grub meat sprites courtesy of Azlan and the Lasso and Saddle sprites from TG
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
This is my first PR so keep that in mind if i dont get some of your comments

**Comment by Flakkyboo** [comment]
merge conflict you'll need to make sure your branch matches the main branch

**Comment by TeomanTheGreat** [comment]
I'll fix it tommorow unga bunga

**Comment by AnjelicaChaykovsky** [comment]
based i recently saw the saddle in sprites now its getting added

**Comment by MCterra10** [comment]
fetish content.

**Comment by TeomanTheGreat** [comment]
Whenever flakky teaches me how to fix this I'll fix it

**Comment by TeomanTheGreat** [comment]
Closed because of the big fuck up I made ill fix it and open a new pr when I get to it

**Pull request closed without merging**
