### PR TITLE
WIP: adds a Dr Bright esque amulet

### PR DESCRIPTION
**Pull request by CthulhuOnIce**
https://i.imgur.com/FH6frFs.gifv

### CODE REVIEW

**Comment by qwertyquerty** [comment]
cool

**Comment by CthulhuOnIce** [comment]
THIS WAS WIP YER NOT SUPPOSED TO MERGE IT REE

**Comment by qwertyquerty** [comment]
Why would you make a PR if it was WIP nerd

**Comment by Arrfur** [comment]
> Why would you make a PR if it was WIP nerd

They hated jesus because he told them the truth

**Comment by CthulhuOnIce** [comment]
It's a very common process.

It's meant so people can suggest features and code improvements ***before*** it's merged, rather than on a private branch no one looks at.

I didn't just open it for no reason

**Comment by qwertyquerty** [comment]
Then add the tag DO NOT MERGE

**Comment by CthulhuOnIce** [comment]
I made that tag in response to this PR

**Pull request merged**
