### PR TITLE
Lavaland science outpost

### PR DESCRIPTION
**Pull request by St0rmC4st3r**
## About The Pull Request

Adds the lavaland science outpost with some pointless rooms and a science shuttle. Everything is unpowered, so be prepared to burn some hands.
By lore, the outpost was abandoned and barred in the middle of construction, so don't expect to move around easily.
The science shuttle can dock to all 4 main maps. ~~Sorry Kilo, not sorry.~~
The outpost is also required by #2497, which has no space for the bomb testing area.

## Why It's Good For The Game

There are some movements to add archeology and other departments to science, but after the experience with medbay remapping I came to the conclusion that adding more than one subdepartment will be a major spacing problem because any of the departments will require to either make new rooms in space that will interfere with maintenance or delete something that already exists. By having an outpost, many of the problems with expanding science are solved.

## Changelog
:cl:
add: The lavaland outpost construction project has been postponed due to misuse of funding by the previous research director.
/:cl:

### CODE REVIEW

**Comment by AnjelicaChaykovsky** [comment]
Nicee,  got any screenshots of the outpost?

**Comment by St0rmC4st3r** [comment]
Yep! Here you go. 
image
Bomb testing site.
image
And a proper look of the (repowered) shuttle.
image

**Comment by Moccha-Bee** [comment]
speed merge

**Comment by AnjelicaChaykovsky** [comment]
Ohh so its connected to the minning base?  
Damn thats very cool overall. 

Miners are being shitters? 
I guess i will mine myself.. 
(Goes to science shuttle)

**Comment by St0rmC4st3r** [comment]
@AnjelicaChaykovsky except you have to get down on their shuttle first to power the science shuttle, heh. But in the future - yep, you can do that.

**Comment by february-ops** [comment]
xenobio room? pwease? i dunno why theere is a an experimentor there tho no shit to research

**Comment by St0rmC4st3r** [comment]
@february-ops, it is written in the "Why is it good for the game". Currently, the outpost is nearly useless. It is made so that when you want to add something to sci, you wouldn't need to map the entire outpost and the shuttle. Just put it in the existing outpost instead of one of the rooms and put the shuttle consoles on the stations.

**Comment by PowerfulBacon** [comment]
image
Second image fucked up:
Point across would be in first image
+ There should be 2 plastic flaps rather than 3
image
image

**Comment by CommandBlockGal** [comment]
make the shuttle an actual shuttle, bacon's shuttles

**Comment by qwertyquerty** [comment]
conflicts

**Comment by PowerfulBacon** [comment]
Testmerged onto sage

**Comment by PowerfulBacon** [comment]
Maint doors have incorrect access

**Comment by Mails-z** [comment]
I thing this should have a Telescience room by default, like the clasic Telescience room

**Comment by PowerfulBacon** [comment]
I'd consider this ready, add your board to the new circuit board system and it should be good to go

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
