### PR TITLE
Actually removes circuits. 

### LINKED ISSUE #138: Circuit tank slots cause damaging the assembly on tank insertion.
So, I was debugging my machine and inserting/ejecting the tanks, and with each insertion attempt, there was a hit sound. At some point, the assembly just disappeared with all the inserted tanks. I have no idea if this issue only occurs with the tanks slots though.

### LINKED ISSUE #2265: Regex error? String exploder circuit does not output properly with null delimiter
https://github.com/BeeStation/BeeStation-Hornet/blob/ed661d41b3f2964bc0be39418e49d964d4c8d37f/code/modules/integrated_electronics/subtypes/text.dm#L237-L238

Intended behavior of the above:
If the delimiter of the string exploder is set to null, it should turn the given string into a list of each individual character, IE a string `"joey"` would become a list like `{"j", "o", "e", "y"}`

The bug:
Instead, the string exploder circuit outputs a list of empty strings that is one longer than intended if the delimiter is null. The same `"joey"` string from before becomes a list like `{"", "", "", "", ""}`
This is possibly because the regex here is bad:
https://github.com/BeeStation/BeeStation-Hornet/blob/ba40cb637d38cb9520b7a23c1cc0de53433dbf8d/code/__HELPERS/text.dm#L550

### LINKED ISSUE #4105: Camera Circuits on any form of assembly seem to be broken.
## Round ID: 
N/A, Happened across multiple rounds of testing on golden
## Testmerges:
N/A
## Reproduction:
Using a camera component on any form of Circuit Assembly seems to be broken. When checking a assembly's camera via camera consoles, it shows in the list, but shows a black screen apon using the camera.
Untitled

### PR DESCRIPTION
**Pull request by Sinestia**
## About The Pull Request

Removes the hippie code port, stopping half-assed random fixes and non-solutions (circuits should be borderline remade. they're sick af)

Currently a draft because I realized that there's some various extraneous shit I missed by simply reverting our "ports circuits from hippie" pr
closes https://github.com/BeeStation/BeeStation-Hornet/pull/3968
closes https://github.com/BeeStation/BeeStation-Hornet/issues/2265
closes https://github.com/BeeStation/BeeStation-Hornet/issues/138
closes https://github.com/BeeStation/BeeStation-Hornet/pull/4298
closes https://github.com/BeeStation/BeeStation-Hornet/issues/4105

edit: partial revert of https://github.com/BeeStation/BeeStation-Hornet/pull/3762
## Why It's Good For The Game
Numerous issues, and none of the coders/maints seem to really care to fix, so yeet it is. 

Improves compile times. 

i dont have too much stake in demanding it to be removed but hey the work's done for ppl who do and i was bored and needed something mindless

## Changelog
:cl:Froststahr
del: Integrated circuits have been removed to enable replacing them with TG's new Wiremod circuits
/:cl:

### CODE REVIEW

**Comment by Sinestia** [comment]
i have no idea what the deal is with that lint

**Comment by MNarath1** [comment]
Thats actually a total no go for me honestly fanc's PR actually would allow a readd after some extensive changes this just plainly removes all the files and would make reworking them actually a hassle. As the one who is currently working on rebalancing circuits i would rather not have to completly readd the code.

**Comment by Sinestia** [comment]
> 
> 
> Thats actually a total no go for me honestly fanc's PR actually would allow a readd after some extensive changes this just plainly removes all the files and would make reworking them actually a hassle. As the one who is currently working on rebalancing circuits i would rather not have to completly readd the code.


It's one git command

in exchange a heap of fat and debt is cut off, and any attempt to re-add them can be evaluated with fresh eyes instead of a "we threw a bandaid on something"

**Comment by BitBite112** [comment]
If it gets removed entirely people will eventually forget about them despite how cool they are and that's going to be the last we will ever see of them again. If we keep them in then maybe someday a coder is going to notice some of the issues it has and fix it or completely replace it with a very similar, but less buggier and more extensive system

**Comment by ItsTisme** [comment]
Inferior PR compared to what franc's doing. just close this we aint no TG cringe

**Comment by OceanFish1** [comment]
Remove don't improve (tm)

**Comment by Sinestia** [comment]
> 
> 
> Remove don't improve (tm)

You sure post this a lot

Improve it yourself 

> 
> 
> Inferior PR compared to what franc's doing. just close this we aint no TG cringe

This is one of the mockable things about bee, that there's huge amounts of garbage just laying around 

And it forces any reintroduction of circuits to be higher quality, since no sane maintainer is gonna look at one bandage and go "yeah this is worth the weight."
You can even add in the removed stuff in that situation, which there's a lot of.

(Which I would be happy with, I don't like gutted circuits, i think combat bots, jamming, chemistry/bombs and the like should straightup be doable and good, ideally)

**Comment by utilbird** [comment]
Bad, circuits are fun. Cloning is the main problem

**Comment by MNarath1** [comment]
> Bad, circuits are fun. Cloning is the main problem

Currently working on a major rework trough if you are fine with a simple cloning fix that involves save files i can provide that already.
- Also a total removal would make hell for anyone making a code review after it gets reworked.

**Comment by Sinestia** [comment]
> Also a total removal would make hell for anyone making a code review after it gets reworked.

maybe thats how tg merged it in the first place

**Comment by MNarath1** [comment]
> > Also a total removal would make hell for anyone making a code review after it gets reworked.
> 
> maybe thats how tg merged it in the first place

the point i am having here is keeping track of changes from before will be way harder

**Comment by OceanFish1** [comment]
> Bad, circuits are fun. Cloning is the main problem

No fun allowed :trollface:

**Comment by utilbird** [comment]
#3975

**Comment by Sinestia** [comment]
Doesn't want to modularize eh >;) >;) >;)

**Comment by Archanial** [comment]
good pr reopen :trollface:

**Comment by aidan-bowman** [comment]
damn my remaining vestigial urge to ever play ss13 is forever gone, at this point even i have to throw in the towel

guess you won't be seeing me after this, i'll just get out of your hair

**Comment by ike709** [comment]
@cheesePizza2 damn guess you'll have to cope with not being able to use the old shitty 2004-looking circuits which were broken as hell in favor of the nice new wiremod circuits that are based af

**Comment by aidan-bowman** [comment]
> @cheesePizza2 damn guess you'll have to cope with not being able to use the old shitty 2004-looking circuits which were broken as hell in favor of the nice new wiremod circuits that are based af

wdym wiremod circuits?

**Comment by ike709** [comment]
https://github.com/tgstation/tgstation/pull/59232

**Comment by aidan-bowman** [comment]
> [tgstation/tgstation#59232](https://github.com/tgstation/tgstation/pull/59232)

ngl that's pretty sick, i guess ping me if it gets ported

that said, i find it unlikely that our maintainers are gonna merge it, no matter how well-done it is. considering their hatred for all circuit-related, they'll just make up a reason to deny it

**Comment by Archanial** [comment]
> that said, i find it unlikely that our maintainers are gonna merge it, no matter how well-done it is. considering their hatred for all circuit-related, they'll just make up a reason to deny it

You do realize ike is headdev?

**Comment by Sinestia** [comment]
> 
> 
> > [tgstation/tgstation#59232](https://github.com/tgstation/tgstation/pull/59232)
> 
> ngl that's pretty sick, i guess ping me if it gets ported
> 
> that said, i find it unlikely that our maintainers are gonna merge it, no matter how well-done it is. considering their hatred for all circuit-related, they'll just make up a reason to deny it

the maints were simping really hard for it


its a lot more restricted than old circuits (mercifully) but has a similar spirit

**Pull request merged**
