### PR TITLE
Mechs will now knock people down on melee, rather than make them unconcious.

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

ports https://github.com/BeeStation/BeeStation-Hornet/pull/2785/files from beestation

thanks to the epic powerfulbacon for making this PR which I ported.

## Why It's Good For The Game

Stun combat has long been considered one of the poorer aspects of the game. Mechs go one step up and have sleep combat, so if you get hit by a mech you don't even get the chance to run or react, you are just immediately put to sleep.

## Testing Photographs and Procedure

image

## Changelog
:cl:
del: Removes unconciousness from mech brute attacks
/:cl:

### CODE REVIEW

**Comment by PestoVerde322** [comment]
I suppose tonight i smacked the wrong person with my durand...

**Comment by Howluinb** [comment]
ided
(deserved, mechs are too busted)

**Review by PestoVerde322 — APPROVED** [review]
literally remove the uncouncious status and the obscenely long knockdown, approv'd

**Comment by MarkusLarsson421** [comment]
Would you still be able to kill someone with this? Currently, it is next to impossible to hit someone once if they are not obstructed with slowdowns. Much less to actually kill them too.

**Comment by PowerfulBacon** [comment]
Yes, it still knocks them down so you can probably chain the attacks if you have some melee skill.

**Comment by kiekatz** [comment]
the best way to balance bee is to throw OP bullshit at a coder...

**Review by Rukofamicom — APPROVED** [review]

**Pull request merged**
