### PR TITLE
4 new lobby screens

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request

Adds 4 new lobby screens 

## Why It's Good For The Game

It's cool as FUCK

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/148357670/cbd9baa5-1083-437c-9104-3ac207c4ebe3

https://github.com/BeeStation/BeeStation-Hornet/assets/148357670/8c6f7a7b-660e-4a0b-ab38-7907c2b0a71d

imagen

https://github.com/BeeStation/BeeStation-Hornet/assets/148357670/f822a98c-8b12-4d62-b0f2-b6c11076c707

</details>

## Changelog
:cl: ClownMoff
add: Adds 4 more cool lobby screens
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Preferably, new lobby screens will adopt the 17x15 resolution instead of 15x15 as that is our current view port size.
I'm not a huge fan of the clown one, but I like the bar and sunset one. Neutral on the engineering party one. I do think that adding all of them would result in this style of lobby screen showing up with a disproportionate amount though, so really we should stick to a small number of high-quality title screens rather than adding many at once. For this, I would say that only the bar and sunset images should be added but it will need discussion with maintainers and Crossed

**Comment by ClownMoff** [comment]
With these 4 added, the total amount of screens goes up to 18, which means one of these styles has only 5.556% to roll, 22.22% combined, which means roughly one every 4 games or so, which is twice every 10. Is it really that disproportionate? Also, people loved these screens and they take time to make, it is quite frustrating to see half of them  initially declined for these reasons

**Comment by PowerfulBacon** [comment]
I guess the probability isn't that high, I didn't think we had that many title screens although we may have less on the server since the server is separate from the github in terms of title screens.
I am fine with all of the title screens except for the clown lifting one, since I don't think it fits the vibe or theme of the server compared to the other ones.

**Comment by ClownMoff** [comment]
I removed the clown one

**Comment by PowerfulBacon** [comment]
Is there any way to crop these or extend them so that they fit a 17x15 aspect ratio? If not then its fine, but 17x15 is preferable since it removes the screen resizing at the start of the round.

**Review by ike709 — APPROVED** [review]
I like them all. Make these 17x15 if it's not too much trouble, otherwise just ask for merge.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
Config was never applied on this PR. Also, we should be rejecting 15x15 lobby screens imo.

**Pull request merged**
