### PR TITLE
Allow for Scanner Gates to be used with Voice Analyzers

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
This is my first PR and hopefully the first of many on the project.
Gates will now say 'BUZZZ!' allowing for them to be used with voice analyzers!
I've tested and it works as intended.
I'm unsure if 'exclaims', is the correct thing to use here please let me know!
image
bGLooTyMVR

## Why It's Good For The Game
Adds a bunch of possibilities when using scan gates, perhaps automatically locking doors or detonating bombs!

## Changelog
:cl:
add: Added the ability to use voice analyzers with scanner gates!
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Would be cool if you could put a remote signaling device into them and have that trigger when passed

**Review by PowerfulBacon — APPROVED** [review]
Code is good, just waiting for other input considering this could get a little annoying and sending a signal on a set frequency would work too

**Comment by ike709** [comment]
Bad idea. Instead you should add a wire that people can attach a signaller to, like airlocks.

**Comment by zeskorion** [comment]
I agree with ike here. You could make it even simpler, if you cant grasp wires, by making it send a signal, changeable by slapping it with a signaller or something

**Pull request closed without merging**
