### PR TITLE
Adds the split personality trait (neutral)

### PR DESCRIPTION
**Pull request by Rukofamicom**
## About The Pull Request

It's pretty much all in the title. It adds a 0-cost neutral trait for players who wish to play with a split personality. 
Companion PR to #6827 because it is wildly immersion breaking for someone to demand a drug overdose at roundstart for the sake of enhancing their round. 

## Why It's Good For The Game
It's a much better alternative to Ketamine granting the trauma. No more of players without previous drug addictions choosing to randomly overdose on ketamine at the start of a round when they want a buddy in their head. 

## Testing Photographs and Procedure

Not tested yet. Will update as soon as I can figure out how to connect multiple instances to a vscode server. 

## Changelog
:cl:
add: Split personality may now be selected as a neutral trait. No ketamine addiction required. 
/:cl:

### CODE REVIEW

**Comment by RDS88-beeman** [comment]
the voices

**Comment by PerishedFraud** [comment]
New trait to main every round woo

**Comment by PowerfulBacon** [comment]
I don't like this, for one split personality requires another person so it would need roundstart ghosts. The other split personality person will also generally try and escalate a lot more than a regular player, so making it super common is a bad idea.

**Comment by EvilDragonfiend** [comment]
It should be ghost role spawnable, and their second personality should be able to leave anytime they want, then open a new ghost role to accept another personality.

**Comment by EvilDragonfiend** [comment]
> The other split personality person will also generally try and escalate a lot more than a regular player

kinda true

**Comment by Rukofamicom** [comment]
> so making it super common is a bad idea.

Then ketamine enabling players to grant themselves this ability is a bad idea because that's all it does.

I have no qualms if this gets closed, I simply made it as a much better fitting alternative to ketamine having an effect that drives people to using it for OOC reasons.

**Comment by PowerfulBacon** [comment]
:key: Reason: I think making it free to everyone and overly common is a bad idea.

**Comment by Rukofamicom** [comment]
No reason to leave this open. Made as an alternative solution to ketamine, but apparently there really is a perceived problem in easy access to split personality, not just an OOC push for hard drugs to get it. 

I won't miss it, but sorry to those that did enjoy it while it lasted.

**Pull request closed without merging**
