### PR TITLE
Beestation Balance Patch 2022

### PR DESCRIPTION
**Pull request by Ivniinvi**
# ATTENTION BEESTATION GAMERS
## THIS PR AIMS TO LEAD US NOT INTO TEMPTATION, BUT DELIVER US FROM SIN ([EXODUS 22:19](https://www.biblegateway.com/passage/?search=Exodus%2022%3A19&version=NIV))

# HENCEFORTH

## Changelog
:cl: The Redeemer, the Everlasting and Faithful, the Alpha and Omega, Father of Mercies, Our Provider, Most Gracious Shepherd, Almighty God + MrDoomBringer and Ivniinvi and Haliris
del: People have been complaining about being "unlucky", therefore all probability checks are now guaranteed to succeed.
spellcheck: The Emergency Meeting feature has been added, allowing the Captain to summon everyone to the bridge and sus out those traitors.
admin: Felinids now have a 5% chance to be gibbed when their tail is pulled. I will not elaborate.
sounddel: Clown gets a chemical synthesizer, because asking the chemist for lube is forced RP, and forced RP is bad RP.
soundadd: 🦀 🦀 🦀 Xenobio is gone 🦀 🦀 🦀 
server: Patrons now get stechkins, to encourage donations.
imageadd: Mime gets syndicate minibombs on spawn, to defend against the clown.
refactor: The supermatter has been replaced with PACMANs, because the supermatter wasn't childproof enough.
refactor: The Gulag Teleporter now sends you to Acacia (no player facing changes)
imagedel: Felinids are now added to a metagang on spawn, and can communicate via a Discord Implant
add: The ai now has legs
/:cl:

### CODE REVIEW

**Comment by Ivniinvi** [comment]
It's april 1st in east asia don't @ me

**Comment by TeomanTheGreat** [comment]
By the power invested in me by Allah i praise this pr

**Comment by nednaZ** [comment]
I am stealing the emergency meeting section and making it a permanent admin secret.

**Comment by Ivniinvi** [comment]
> I am stealing the emergency meeting section and making it a permanent admin secret.

It's a tg port, credit MrDoomBringer

**Comment by Crossedfall** [comment]
It's not the first @Ivniinvi

**Comment by Ivniinvi** [comment]
I'll just leave this and reopen it in a few hours when server time hits apr1 then

**Comment by ike709** [comment]
Bad PR. Reuses a TG joke and also has bad code.

**Pull request closed without merging**
