### PR TITLE
[PORT] Brings in multi-directional sprites to the arcade machine and 80s style floor. 

### PR DESCRIPTION
**Pull request by Moccha-Bee**
## About The Pull Request
Adds multiple directions to the arcade machine sprite, and an 80s style floor to complement it.

image
image

https://github.com/tgstation/tgstation/pull/53088
https://github.com/tgstation/tgstation/pull/51313

## Why It's Good For The Game

Will be used in babylon.

## Changelog
:cl:
add: multi-directional sprites to the arcade and 80s floor.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
To fix it download the new version of the icon file and copy and paste your sprite into the new file

**Comment by Moccha-Bee** [comment]
Fixed the conflct error mesagge yay.

**Comment by TotallyNotChief** [comment]
having a stroke looking at that floor sprite

**Comment by Moccha-Bee** [comment]
> having a stroke looking at that floor sprite

its the old one this port uses a newer less stroke inducing floor lol.

**Comment by zeskorion** [comment]
may as well just redo the pr at this point

**Comment by Moccha-Bee** [comment]
> may as well just redo the pr at this point

why?

**Pull request closed without merging**
