### PR TITLE
Stand customization

### PR DESCRIPTION
**Pull request by Cenrus**
https://github.com/tgstation/tgstation/pull/45111/
https://github.com/tgstation/tgstation/pull/49342/
https://github.com/tgstation/tgstation/pull/43846/

Relevant PRs

Guardians can now change their name and colour

## Why it's good for the game

Holoparasites are boring. at least let them choose stupid names and a hot pink colour palette.

:cl: fikou, nemvar, tralezab
add: You can now choose your name and color as a holoparasite/guardian/holocarp!
tweak: Gravitokinetic stand type improved.
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
Due to the dme being stupid, I wasn't able to correctly commit the authors, sorry

**Comment by qwertyquerty** [comment]
Fix conflicts

**Comment by Cenrus** [comment]
I did it, yus

**Comment by bloons3** [comment]
BUG: everytime the mob is entered it asks for color and name

**Pull request merged**
