### PR TITLE
The great Material resprite + Material stacks code refactor

### PR DESCRIPTION
**Pull request by PestoVerde322**
## About The Pull Request

This PR finally resprites the grand majority of ores and (almost) all the ores with a more sleek, modern artwork, rather than being stuck to 10 or so years ago.

Alongside this, it also makes the code for almost all stacks to be more readable compared to the mess it used to be.

Also it's likely i've done some changes to other stuff that are not mentioned in the CL, so please if you see them point them out.

some icons where done by @Imaginos16 over to /TG/station (if i recall right the BSC and the re-re-reworked ore icons)

## Why It's Good For The Game

Major overhaul of the material system, paving the way for further materials adjustment and better icon drip

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

matrefinedfor2

</details>

## Changelog
:cl: Pigeonverde322, Imaginos16
imageadd: new icons for materials and ores.
refactor: refactored how the material code is sorted out.
imagedel: removed some unused material and ore icons that they where just bad.
/:cl:

### CODE REVIEW

**Comment by DAKKA-WAAAGH** [comment]
AWWWW YEAAAHH!!!

Let's fucking GO!

**Comment by PowerfulBacon** [comment]
I like 'em, but somethinga bout the glass is off. It seems... smooth

**Review by PowerfulBacon — DISMISSED** [review]
I'm good with these including the glass after further discussions on discord and seeing the current glass sprite. Will probably test merge these as usual just to see how it looks in game and gather optinions.

**Review by itsmeow — APPROVED** [review]
yolomerge swag

**Pull request merged**
