### PR TITLE
makes spacevines threatening

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
-spacevines now spawn in maint, not in exposed hallways
-spacevines now slowly break structures in their way. They won't break fuel tanks, external airlocks, firelocks, or SMES units, however, as to avoid hullbreaches.
-spacevines now start with random mutability between 1 and 6%, instead of a fixed 1% chance per spread
-ports https://github.com/tgstation/tgstation/pull/52116

## Why It's Good For The Game
spacevines is boring and kudzu is super easy to contain

## Changelog 
:cl: Zeskorion, Angustmeta
tweak: spacevines now spawn in maint, not halls
tweak: spacevines now break shit that's in their way
tweak: spacevines spawn with random stats and a single mutation
fix: fixed space vines / kudzu growing slower from better (lower) production speed
balance: random event space vines buffed to have 1-6 production instead of 5-10 to compensate
/:cl:

### CODE REVIEW

**Review by yorii — DISMISSED** [review]
epic

**Comment by Angustmeta** [comment]
Consider doing this as well https://github.com/tgstation/tgstation/pull/52116

**Comment by Angustmeta** [comment]
Consider https://github.com/tgstation/tgstation/pull/52116 as well

**Comment by yorii** [comment]
> Consider [tgstation/tgstation#52116](https://github.com/tgstation/tgstation/pull/52116) as well

Hahahaha kudzu speed is reversed? that is absolutely abusable right now 😄

**Comment by zeskorion** [comment]
> Consider [tgstation/tgstation#52116](https://github.com/tgstation/tgstation/pull/52116) as well

thanks, i'll port this as  part of this pr

**Comment by Angustmeta** [comment]
> Hahahaha kudzu speed is reversed? that is absolutely abusable right now

Been all these years, which is tragic

**Comment by hotimep** [comment]
next step is to turn kudzu into a playable antag

**Review by PowerfulBacon — APPROVED** [review]

**Comment by Ohagi-Chan** [comment]
Hang on, wouldn't these new kudzu now destroy cables and pipes, which are not blacklisted machinery?

**Comment by yorii** [comment]
yes, very epic, kudzu is now as dangerous as people pretend it to be

**Pull request merged**
