### PR TITLE
Adds maint robotics to Box and Pubby

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
Adds an exosuit fabricator and mech charging to Box and Pubby. These are both already present on Meta and Delta. 

## Why It's Good For The Game
Secretly building a mech, flashes, cyborg or whatever else is commonplace for both bored assistants as well as antags. This should be possible on all maps instead of just half of them as it makes this activity not map-dependent and easier to balance around by being universal.

## Changelog
:cl:
add: Adds maint robotics machines to Box and Pubby.
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
#1554

**Comment by VictorVow** [comment]
I've asked if there's a maint robotics room in that PR, but either way a maint robotics room on the maps will be good in the meantime since it's likely not to be mergeable for a while knowing Zesk.

**Comment by zeskorion** [comment]
> I've asked if there's a maint robotics room in that PR, but either way a maint robotics room on the maps will be good in the meantime since it's likely not to be mergeable for a while knowing Zesk.

actually, the only real problem with that pr is the fact ike doesnt like the jobs not all working under one role preference and the fact that, thus far, it only covers box station

maybe also the fact that the amount of maps in it breaks the map bot

**Comment by ike709** [comment]
Conflicts. Also, should probably be a random room.

**Pull request closed without merging**
