### PR TITLE
RNG generator app for pdas

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
You can now use a rng generator inside your pda! its counted as a base app too, so anyone can access it

## Why It's Good For The Game
basically gives you a miniature dice set and an ic way to roll dice, if you want to

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

rtd_lower

rtd_upper

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
add: Nanotrasen has installed a dice app into your work pdas
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
I'm going to remove PDAs. Make this a tablet app.

**Comment by etherware-novice** [comment]
huh? uh..im not sure how to code those or where the code even is

**Comment by EvilDragonfiend** [comment]
> huh? uh..im not sure how to code those or where the code even is

get a tablet and see how it works, and codedive it.

**Comment by itsmeow** [comment]
programs are in code/modules/modular_computers/software/programs

Then you need to make a TGUI for the program (see other programs for examples)

You use React to make tguis, so you should learn React or look at and modify other programs. It should be much easier than a PDA app, in general.

**Comment by itsmeow** [comment]
You can copy the signaller app from my Modular PC Update V2 PR

**Comment by itsmeow** [comment]
Not particularly useful and is also adding to PDAs which are near-defunct. I'm pretty sure there's dice in the game, the use case for this is limited.

**Comment by etherware-novice** [comment]
wait what the ehck how did you add a tag

**Comment by BelkistLake** [comment]
they became a trialtainer today lil bro 💀

**Comment by etherware-novice** [comment]
congrats. on. all. your. accomplishments. meow.

**Pull request closed without merging**
