### PR TITLE
Adds autodrobes to several maps.

### PR DESCRIPTION
**Pull request by CydiaLamiales**
## About The Pull Request
Adds Autodrobes to Box, Meta and Pubby.

## Why It's Good For The Game
More clothing options good, as it allows crew to engage in more gimmicks.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
Box:

image

Meta : 

image

Pubby:

image

</details>

## Changelog
:cl:
add: Added Autodrobes to Box, Meta and Pubby.
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
Were they not already in the Bar?

**Comment by CydiaLamiales** [comment]
> Were they not already in the theatre?

Theatre yes, but it's not publicly accessible and the one in the theatre has increased pricing for those that don't have theatre access.
Also it's an inconsistency how some maps have public autodrobes while some don't and IMO it should be the thing that's consistent across all maps.

**Comment by CydiaLamiales** [comment]
Oh whoops, forgor to switch branches moment

**Review by itsmeow — CHANGES_REQUESTED** [review]
fine but you saved your editor on kilo and it did a bunch of reformatting for no reason, just undo the changes with `git checkout origin/master _maps/map_files/KiloStation/KiloStation.dmm`

**Comment by CydiaLamiales** [comment]
There, have no idea how that happened even.

**Review by itsmeow — APPROVED** [review]

**Comment by itsmeow** [comment]
If you open a map, make no changes, and save it, the editor will correct any minor formatting differences from its normal save format

**Pull request merged**
