### PR TITLE
[WIP] Smooth movement Pt. 3, 2023

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports:
- https://github.com/tgstation/tgstation/pull/66628
- https://github.com/tgstation/tgstation/pull/62567 (stealin the glide)
- https://github.com/Monkestation/MonkeStation/pull/393 (A port of our port, which is itself a port. Portception.)
- https://github.com/yogstation13/Yogstation/pull/8132
- https://github.com/tgstation/tgstation/pull/66567 (still trying to figure this shit out

## About The Pull Request
This PR adds smooth movement.
"Brings over the buttery movement, and makes mobs with slow movement speeds glide instead of jump from tile to tile"

This has quite a few irritating dependencies, so those will have to be merged prior to this one in order to complete this properly.
## TODO

- [x] Base work done
- [ ] Testing 
- [ ] Spatial Grid dependency fulfilled
- [ ] Opacity refactor dependency fulfilled
- [ ] resolve conflicts with parallax
- [ ] pr ready to merge

## Why It's Good For The Game
"Movement feels a lot smoother and moving things wont be as stupid hard to click"

Bacon said he would be open for a new PR if it was better than the last one. This one incorporates changes from the movement loop system among other things, which should make it function a lot better than the old versions. 

This isn't a recoup of the pr two years ago. I would like to port the modern smooth movement for the ebet experience.

Also, I think its been around long enough on the other servers that there will be less backlash.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: RKz, Dwasint, Brumalake, LemonInTheDark, monster860
add: Smooth movement from yogstation
fix: Jetpack and space pulling fixes
fix: Parallax fixes (tentative)
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
I expect this to be a buggy hellhole for a bit, need to fix up jetpack stuff and (tentatively) see if I can get the parallax subsytem working. 

Parallax isn't something I am familiar with, so its likely that I will have to cut that out for someone more competent in it to look at.

**Comment by PowerfulBacon** [comment]
This will feel weird and different when first implemented, people will complain while they adjust but I want to put out that I do approve of these changes overall in order to make movement feel more smooth.

**Comment by Tsar-Salat** [comment]
> This will feel weird and different when first implemented, people will complain while they adjust

Mhm. I'd rather avoid a half-baked port for this pr specifically, as that is what I promised. It's not in an acceptable state right now with parallax.

Still working on the parallax bugs ATM, I'll try to get back to this within the month.

**Comment by Tsar-Salat** [comment]
oh great, a spatial grid dependency.

fuuuuuuuck

**Comment by Tsar-Salat** [comment]
> Can we get a side-by-side of old vs new?

Not at this moment, unfortunately. When it's ready, I'll show it off.

**Comment by Tsar-Salat** [comment]
It's not stale, but okay.

**Pull request closed without merging**
