### PR TITLE
Cryo rework, sleeper deletion

### LINKED ISSUE #3921: Medical Cryopod Rework ($40 Bounty)
Forum discussion here: https://forums.beestation13.com/t/medical-cryopod-rework-bounty/11897

### Bounty payout details:
* $40, payable via Steam or PayPal preferably. (Price and platform Negotiable)
* Will pay for finished code even if not merged on Bee

### Machine specs and info:
* **Machine functions like a fusion between current cryopod/sleepers, as a resource efficient chemical treatment machine, but no longer *infinite* chem treatment machine**
  * Machines require reagents to be manually added, but may accept any reagents instead of being restricted to only select medicines. Roundstart machines should have a crate near them with assorted bottles of basic medical reagents (detailed further down)
  * Sleeping patients (either drugged or cryo) inside of the pod will receive boosted chemical efficiency based on the machine's part upgrades. *This gives an actual, functional use for morphine, even if somewhat marginal compared to cryo-mode*
  * "Cryo-mode" is a feature that can be toggled anytime the machine is stocked with Cryoxadone. While this is active, patients are put to sleep, then chilled and constantly micro-dosed (add 1u any tick that less than 3u is present in patient) with Cryoxadone until the machine ejects the patient. Cryo-mode automatically disables when the machine runs out of Cryoxadone, which will also allow the patient to wake up.
  * "Auto Eject" will dump patients (unceremoniously on the floor if unconscious) out of the machine when their health is full, just like current cryopods. 
  * Patients may exit the machine at any time if they are conscious - there is no locking function on the machine so intentional entrapment will be at least somewhat difficult. Naturally patients may only be injected with chems after being closed in the machine as well. 
  * Does not require the arbitrary atmos setup that current cryopods do to function - just needs to be loaded with chemicals and be in a powered room. 
  * When emagged, Cryo-mode will operate without injecting or requiring any cryoxadone, slowly killing the patient via freezing and ejecting their corpse after they have died. Additionally, trying to inject any chems into a patient will result in a 50/50 chance of attempting to add 30u or destroying 30u of a randomly selected chem. 

* **Three part UI**
  * Control buttons for: Initiate Cryo-mode, Auto-eject (On/Off), Open/Close, 
  * Display patient's vitals and current reagents (like sleepers currently do)
  * Display currently stored reagents in a way similar to ChemMaster3000 - Buttons for dosing at 1, 5, 10u (and an X which will destroy 10u of that reagent)

* **Stock Parts:**
  * Four beakers - maximum reagent storage (200u roundstart, 1200u max upgrades)
  * One Manipulator - Controls reagent efficiency while patients are asleep. 25% Boost at T1 and 70% at T4 with a linear upgrade path (25, 40, 55, 70)
  * One Scanning Module - Controls how quickly cryo-mode puts patients to sleep, should not be instantaneous at T4 to prevent easily weaponizing the machine. 
  * One Micro Laser - Controls how quickly cryo-mode chills patients, being near instantaneous at T4. 
  * The difference between T1 and T4 Scanning Modules/Micro Lasers should be noticeable but not huge. The total initiation process should not feel especially sluggish with T1 parts. 

### Other changes to include in the PR:
* Cargo: Add a somewhat pricey "Cryo-chem crate" to the medical tab. It should contain:
  * 2 Bottles of Cryoxadone
  * 1 Bottle of Morphine
  * 1 Bottle of Bicaridine
  * 1 Bottle of Kelotane
  * 1 Bottle of Epinephrine
  * 1 Bottle of Charcoal
* Mapping: Replace all sleepers with stasis beds in all station medbays
* Mapping: Remove unnecessary atmos leftovers from old cryopods (O2 canister, atmos piping and freezer) from all medbays
* Mapping: Replace the glass table with four, partially filled beakers of cryoxadone with a Cryo-Chem Crate that has double the stock of the ones you order from Cargo (since there are two pods to fill)
* Other: Make sleeper  circuit boards unobtainable via conventional means

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Old sleepers ~will be~ are deleted from maps.

Cryo is now built from:

- 4 beakers (it can hold 400 units of chemicals roundstart and 1600u at 4 bluespace beakers, and before you get any funny ideas, not the chemicals don't react inside the cryo)
- 2 matters bins (they affect heat capacity and conduction coefficient, which means the machine will lower the temperature of the occupant faster)
- 1 scanning module (the occupant will be sleeping longer)
- 2 manipulators (they will affect efficiency of the machine, making it use less cryoxadone per tick (from 1u to 1/4u per tick at t4) and make the multiplier from cryosleep bigger (1.5 to 3 at t4) and how much of the chemical we can inject per tick (1u to 4u at t4) but will also make the machine draw more power))
- 4 sheets of glass
- 3 cable coils

When emagged machine will deal 0.5*efficiency heat damage to the occupant, have a chance to randomize chemicals added to queue and has a chance to not inject and effectively lose some reagent per tick (50% to have 0 multiplier).
Also the numbers in queue will flicker and I have yet to understand why this happens but it's 100% feature now.

Cryo will now not accept and hold beakers instead it will take and store reagents (like cloner does).
Cryosleeping patients will receive boost to the amount of chemicals the will be injected with (1.5 minimum, 3.5 maximum at tier 4). Cryosleep is defined as sleeping while being continuously being injected will small amounts of cryoxadone (1/efficiency per tick, which will be 1 or 1/4 at tier 4).
UI will be changed to accompany those changes (will post images of it after I finish UI).
Auto-eject is gone - medical doctors have to actively operate the machine to heal patients instead of pressing a few buttons and then going somewhere else.
I now requires different (and more) stock parts and beakers.
Also as a part of this PR cryoxadone will get nerfed, it will only heal cloneloss per tick.

UI:
obraz
obraz
obraz

- [x] finish UI
- [x] add cargo crate
- [x] add emag effects
- [ ] listen to feedback :trollface: 
- [x] revert all debug changes
- [x] remove sleeper from all maps
- [x] make changelog

## Why It's Good For The Game

closes: #3921
Sleepers gone, medbay saved.

## Changelog
:cl:
del: Sleepers has been removed from all maps.
add: Cryo was reworked. It has built in reagent container (similar to cryo). You use chemicals you load to inject them into patient.
add: Cryo now uses cryoxadone as it's "fuel".
tweak: Cryoxadone only heals clone damage.
add: Cryo can now put people in "cryosleep" which will boost amount of chemicals you inject into patient (1.5 at t1 parts to 3). This feature requires patient to have some cryoxadone and the machine will automatically microdose the patient with it.
add: Cryo is now built from 4 beakers, 2 matter bins, 2 manipulators. 1 scanning module, 4 sheets of glass, 3 cable coils.
add: Cryo has now unique emag effect.
add: Cryo resupply crate. All maps start with one crate (which has double the contents of cargo crate). Crate contains 2 bottles of cryoxadone, a bottle of bicaridine, kelotane, epinephrine and charcoal. It costs 4000 credits.
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
You say sleeper and cryo rework but then you get rid of sleepers. It should be titled "cryo rework with no more sleepers"

**Comment by Mat05usz** [comment]
> Cryo will now not accept and hold beakers instead it will take and store reagents (like cloner does).

Leave beakers (or some sort of container), noone cares about adding harmful shit to cloners but if you make cryotube the primary source of healing there will be a lot of shit being added, and emptying ALL contents from the tube will just halt medbay to a stop.

**Comment by Rukofamicom** [comment]
Just wanted to verify that I gave @Archanial creative freedom within the bounty to tweak things as they saw fit as long as the core concept and key points remained the same: 
* Sleeper and Cryopods merged into one machine 
* Machine requires manual chem inputs  
* Map comes with a roundstart basic stock of chems  
* Orderable cargo crate to replace that basic stock as needed in the absence of chemists.

Coincidentally this is the companion PR I mentioned in #3944.

**Comment by LivingBatteryBox** [comment]
Nerfing cryoxadone is really uncool. Now people are going to have to make overcomplicated healmixes to make any use out of cryo,

**Comment by Rukofamicom** [comment]
> Nerfing cryoxadone is really uncool. 

Cryoxadone is already primarily used for healing fresh clones and not much else, it still heals this with no issues.

> Now people are going to have to make overcomplicated healmixes to make any use out of cryo

A roundstart crate of chems and cargo added crate of chems are going to be part of this. The five basic staples of healchems are also hardly difficult to memorize or make.

**Comment by OceanFish1** [comment]
Oh yes people getting stuck in cryo meta lets goooooo

**Comment by Archanial** [comment]
> Oh yes people getting stuck in cryo meta lets goooooo

I'll make 45 second do after to open it if you are stuck. 



> Nerfing cryoxadone is really uncool. Now people are going to have to make overcomplicated healmixes to make any use out of cryo,

That's the point? Right now cryoxadone heals EVERY damage, I want to make it a "fuel" to cryo and not make rest of chemicals useless.

**Comment by That0nePerson** [comment]
>Display currently stored reagents in a way similar to ChemMaster3000 - Buttons for dosing at 1, 5, 10u (and an X which will destroy 10u of that reagent)

Is this part of the bounty planned to be added? The only good part of sleepers currently is easy and simple application of chemicals without feeding, pills, patches, or syringes. I would hate to lose that functionality. I understand if you're not willing to put in the effort to code all of that UI, I feel the same way about UI code.

**Comment by Archanial** [comment]
It's already there, I just need to fix a few bugs and align stuff in ui.

**Comment by Absolutely-Steph** [comment]
Well if people are looking for an easy way to apply chemicals, then you could go the aurorastation route, and make a hypospray that can only apply chemicals(with slight delay like the syringe), but not take blood. that keeps some of syringes usefulness, but gets doctors a faster way to apply chems to people. Maybe you can even toggle modes of the hypospray, between a topical spray mode for synthflesh type stuff, and an injection mode for everything else.

**Comment by MCterra10** [comment]
my man doesn't know that there's already a chemical you make from cryoxadone called clonexadone, that does exactly what you're making cryoxadone do. You should probably rebalance this, swap them so you make cryox from clonex or something and keep the omni healing on cryox
image

**Comment by Archanial** [comment]
Clonexadone heals clone damage much faster, it's still somewhat useful.

Still even now it's not used because clone damage is rare and cryoxadone is just better.

**Comment by Archanial** [comment]
It's ready

**Comment by Vexylius** [comment]
you wanna replace sleepers and make cryopods actually require chemists to both exist, and make useful chemicals (which is not going to happen most of the time)? why cryo? could have reworked sleepers to be something like a quick cryo or something

**Comment by Rukofamicom** [comment]
> why cryo? could have reworked sleepers to be something like a quick cryo or something

If you take sleepers and make them require manual chemical input, they're basically cryopods with more precision control at that point. **The best points of both machines have been combined into one** (excluding infinite chems). Please read everything the machine does instead of skimming and prematurely passing judgement. 

> you wanna replace sleepers and make cryopods actually require chemists to both exist, and make useful chemicals (which is not going to happen most of the time)? 

Don't need chemists. There's a crate of chems by the machine which can be re-ordered from Cargo. Chemists existing to produce better-than-basics will make the machine run better, but they are not required.

**Comment by Isy232** [comment]
@Archanial Why nerf cryoxodone?
Its a hard chem to make and requires the case of low temperatures to function.
It is a very situational chem generally not abusable in combat but a useful tool for doctors.

I do not see any reason to nerf it.

Rather, buff clonexodone, maybe make it heal clone loss without cryo or something.
Or just remove clonexodone due to it being a pointless chem

**Comment by Chessus** [comment]
For balance, nerf Pyroxadone also. That way they'll be no more temp-dependant healing chems.

Or forgot about cryo nerfs and rename and rework Cloneoxadone since it's basically useless.

**Comment by Sinestia** [comment]
> For balance, nerf Pyroxadone also. That way they'll be no more temp-dependant healing chems.
> 
> Or forgot about cryo nerfs and rename and rework Cloneoxadone since it's basically useless.

pyrox is very unwieldy so its not necessary

**Comment by ike709** [comment]
Not a fan without a more comprehensive medical rework.

**Pull request closed without merging**
