### PR TITLE
Service Borg Speciality Modules

### PR DESCRIPTION
**Pull request by eeSPee**
##  About The Pull Request

Add 1 research node, Borg Service. Requires borg utility and costs 1500RP.
Adds 3 new modules; Kitchen Speciality, Garden Speciality and Casino Speciality.
"Specialty" modules can only be installed 1 at a time, and will uninstall the previous specialty.
Botany comes with hatchet, spade, cultivator, analyzer and portaseeder.
Kitchen comes with roller, knife and food fabricator (fabricates basic foods, like meat, buns, etc)
Casino comes with dice, playing cards and a sort of slot machine
Don't worry, non-emagged service cannot use its knives/hatchets to hurt living organisms.

## Why It's Good For The Game

Engineering cyborg can substitute engineering, when all engineers are dead.
Medical cyborg can substitute medicine, when all medix are dead.
Janitor cyborg can substitute janitors, when all janitors are tiding.
But service can barely replace a bartender. Why shouldn't service get proper upgrade to substitute a failing department?

Feels like service is just leftover code for some scrapped ideas that nobody now knows in which direction was supposed to go and what the end result was supposed to be, so it just kinda is in an unfinished state.

## Changelog
:cl:
add: new tech tree, cyborg service research
add: three new modules for service; kitchen, garden and casino. service may have only one of these "speciality" modules at a time
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Checks fail

**Comment by eeSPee** [comment]
>beestation.dme, line 3092, column 1:
>error: got EOF, expected one of: anything

Hmmm

**Comment by zeskorion** [comment]
still fails travis

**Comment by eeSPee** [comment]
beestation.dme EOF error?

**Comment by PowerfulBacon** [comment]
Conflicts

**Comment by eeSPee** [comment]
Should I revisit them? Or remake them as proper upgrades?

**Comment by eeSPee** [comment]
Revised in https://github.com/BeeStation/BeeStation-Hornet/pull/2862

**Pull request closed without merging**
