### PR TITLE
Updates/Buffs Space Pirates

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request
As title says, it all around updates space pirates so they are slightly stronger, changes include:
space pirate ship now contains a cow and milk for healing
space pirate ship now requires syndicate access
space pirates now spawn with agent IDs
space pirates now spawn with bangproof headsets
space pirate captain now spawns in with a loud mode headset
space pirates no longer spawn with a breath mask and air tank
space pirate ship now uses a different type of turret, damage should be roughly the same but giving a stronger syndicate vibe
space pirate ship no longer has space suits
space pirate ship now has some RTGs for power generator 
space pirates now have a spacepoof cow as a pet
space pirates now have both a drinks and a beer dispensor
space pirates now have a cigs dispensor instead of a pile of cig cartons and a cheap lighter on a table

second commit:
all doors have ai connection wires cut
turret controller now requires syndicate access and is inside of armoury

a picture:
image

## Why It's Good For The Game
Space Pirates, at their current state feel unfinished and underwhelming, so I updated them 

## Changelog
:cl:
tweak: Space Pirates have been made slightly stronger all around
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
why does this annnoying midround need a buff? they're here to steal money, not directly assault the station

**Comment by ToasterBan** [comment]
> why does this annnoying midround need a buff? they're here to steal money, not directly assault the station

ive seen almost every single round with pirates that the shuttle almost instantly gets found, validhunters rush it and the pirates die, this is mainly due to pirates not having any non-station gear outside of e-sabers and they also completely lack meds and good armour, this pr intends to make them go from "free loot to minor annoyance" to "minor station threat that validhunters shouldn't run at for free gamer gear"

**Comment by Howluinb** [comment]
"space pirate ship no longer has space suits"

a wee bit annoying considering my pirate gimmick usually is to capture people to sell them off

otherwise this is great, pirates really needed to be freshened up

**Comment by PowerfulBacon** [comment]
<s>Why does it get syndicate access, the doors have pirate access.
Wait maybe they don't but they should.</s>

Nevermind the PR that did that was never reviewed and got closed for being stale

**Comment by ToasterBan** [comment]
merge conflicts happened, going to close this PR and make a new one because map merge conflicts are a pain in the ass

**Pull request closed without merging**
