### PR TITLE
Adds crew objectives

### PR DESCRIPTION
**Pull request by CthulhuOnIce**
c

### CODE REVIEW

**Comment by CthulhuOnIce** [comment]
also qwerty if you could do some beecoin shid with this it would be quite sexy

**Comment by CthulhuOnIce** [comment]
also for anyone wondering, you dont have to do these, but doing them will give you beecoins

**Comment by CthulhuOnIce** [comment]
hold on last touches

**Comment by CthulhuOnIce** [comment]
@ike709 did i do you proud?

**Comment by CthulhuOnIce** [comment]
also this is ported from interstation13 with modifications by me

**Comment by qwertyquerty** [comment]
I can do some beecoin s h i d with this, does it check completion?

**Comment by CthulhuOnIce** [comment]
It should already give beecoins on completion, but can you make sure I'm doing it right?

**Comment by qwertyquerty** [comment]
Looks fine

**Pull request merged**
