### PR TITLE
Nerfs the cyborg *spin to be a knockdown instead of a paralyze

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Title. Cyborgs doing *spin while someone is buckled to them now knocks down for 6 seconds instead of paralyzing.

## Why It's Good For The Game

Cyborgs being able to instawin against anyone whose hands aren't full is bad.

## Changelog
:cl:
balance: cyborg *spinning someone now knocks down instead of paralyzing
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I thought it only did this if emagged

**Comment by ivanmixo** [comment]
Nope, every module emagged or not can do this.

**Comment by BrumalLake** [comment]
then you get an emagged cyborg, enjoy the 5 second knockdown, kick them onto their side at the very end for a 4 second paralyze to top it off
if only there was a form of knockdown that couldn't be punished with shoving but wici

**Comment by ghost** [comment]
Emagged cyborgs should be able to paralyze with that

**Comment by ivanmixo** [comment]
> Emagged cyborgs should be able to paralyze with that

Why? Emagged borgs get their emagged modules. Use those instead.

**Review by qwertyquerty — APPROVED** [review]

**Pull request merged**
