### PR TITLE
Fixes Revolutionary antag preferences being in legacy

### PR DESCRIPTION
**Pull request by Therealdoooc213**
## About The Pull Request

In the title

## Why It's Good For The Game

Revolutionary isn't legacy anymore, its in rotation.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image
image

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:Therealdoooc
fix: Revolutionary now appears in the correct section in antag preferences
/:cl:

### CODE REVIEW

**Comment by XeonMations** [comment]
afaik revs are infact not in rotation

**Review by PowerfulBacon — APPROVED** [review]
This really should be determined by the config and not hardcoded

**Comment by Therealdoooc213** [comment]
> afaik revs are infact not in rotation

They are, just insanely rare lol

**Comment by Nakalon** [comment]
I just recently read a ban from this year for revolutionaries, I can't believe they are in

**Pull request merged**
