### PR TITLE
Adds an Conveyor Belt Armoury

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
Replaces the armoury with a looping conveyor belt, circling the weapons, tools and other armoury equipment around in a circle.

## Why It's Good For The Game
It's needless, but fun and cool. lol

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
add: Makes the armoury cool with a fancy conveyor belt to find the perfect tool for the right job.
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
I mean, can't it be test merged for a few days just for fun? Hell, can't it be genuinely merged? Or do you think it absolutely won't ever be?

**Comment by EvilDragonfiend** [comment]
> I mean, can't it be test merged for a few days just for fun? Hell, can't it be genuinely merged? Or do you think it absolutely won't ever be?

Bribe an admin

**Comment by ClownMoff** [comment]
This is a good idea, but sadly is lacking something.

RNG.

Make everything in the armory be inside a wrapped container, so security has to play opening lootboxes to get gear

**Comment by Fronsis** [comment]
As other have said, this would've been a good april's fool PR, on any serious round this ain't it, i've already shared my opinion on the forum post.

**Comment by PowerfulBacon** [comment]
Just in case the food conveyor belt on corg wasn't enough evidence that conveyor belt rings with items on them are a bad idea

**Comment by MarkusLarsson421** [comment]
> Just in case the food conveyor belt on corg wasn't enough evidence that conveyor belt rings with items on them are a bad idea

What if conveyors were slower? As in slow enough to be able to react and pick stuff up.

**Comment by Fronsis** [comment]
Well, the conveyors being slower could be good for general usage, still don't think it fits for an armory.

**Comment by PowerfulBacon** [comment]
Slow conveyors are a good idea, but I still don't think a meme armoury layout will be good for the game.

**Comment by PowerfulBacon** [comment]
This is a meme layout and will be annoying because:
- Picking items on a conveyor belt is annoying
- You can't manage the inventory of the armoury anymore
- You can't organise the armoury anymore.

**Pull request closed without merging**
