### PR TITLE
Remove devils and like 3 more things

### PR DESCRIPTION
**Pull request by derpymcfuckwit**
Devils not in rotation instead Wizard was increased to Devils chance. Extended and Clown ops activated

## About The Pull Request
Enables clown ops and extended and increases Wiz chance in turn disabling Devils

## Why It's Good For The Game
Devils is broken and isn't really fun to play. 

## Changelog
:cl:
tweak: made wizard more common removed devils and activated extended and clown ops
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
Extended is already turned on with a weight of 4

**Comment by derpymcfuckwit** [comment]
> Extended is already turned on with a weight of 4

das secret extended doe?

**Comment by zeskorion** [comment]
It has already been said multiple times that devil is not gonna be removed from the MRP pool. Likewise, wizard should **not** be at the weight devil used to be. It derails rounds severely

**Comment by qwertyquerty** [comment]
no

**Pull request closed without merging**
