### PR TITLE
Corporate sponsorship

### PR DESCRIPTION
**Pull request by ike709**
## About The Pull Request

Makes code changes in accordance with our new sponsorship. As a byproduct, closes #1448 for being against the morals and values of said sponsor.

## Why It's Good For The Game

Better ingredients. Better pizza.

## Changelog
:cl:
add: Adds various Papa Johns-related code changes. Including, but not limited to:
add: All players will be given a valid Papa Johns promo code when they spawn in*
add: *Some conditions apply. See the Discord announcement for details
add: Nanotrasen has been bought by Papa Johns Intergalactic, Inc. and is now a subsidiary
add: Pizza Hut has taken over the Syndicate
add: Every player now starts the round with a complementary pizza slice
add: All pizzas have been tweaked
add: New station goal to bake a lot of pizzas
add: Assistants have had their job title changed to Papa Johns Delivery Boy
add: New lobby images and sounds
add: Various other code changes
add: Better ingredients. Better pizza. Papa Johns.
add: Disclaimer: Happy April Fool's. We're not actually sponsored by Papa Johns. Though we did attempt to get a real affiliate link by reaching out to Papa Johns. Seriously, I'm not kidding. Sadly, they couldn't understand what Space Station 13 was and we gave up.
/:cl:

### CODE REVIEW

**Comment by Victor239** [comment]
Bruh you closed [my totally real and based PR](https://github.com/BeeStation/BeeStation-Hornet/pull/1448)....

**Comment by MCterra10** [comment]
is this reverted yet, so I can close the PR downstream

**Comment by eLeCtrOssSnake** [comment]
Cringe

**Comment by AnCopper** [comment]
We need to step up our game, get a sponsorship from Microsoft!

**Pull request merged**
