### PR TITLE
New midround join screen (#44193)

### PR DESCRIPTION
**Pull request by Cenrus**
https://github.com/tgstation/tgstation/pull/44193

Mostly a code improvement.

## About The Pull Request

This pull request adds in a new join menu, ported from Oracle F. It categorises jobs into departments and enlarges the buttons.

:cl: AffectedArc07
tweak: The jobs menu has been given a new coat of paint. Yay.
/:cl:

### CODE REVIEW

**Comment by Moccha-Bee** [comment]
Don't we already have this?

**Comment by Cenrus** [comment]
we do, it's primarily a code improvement.

**Comment by ike709** [comment]
Tested?

**Comment by Cenrus** [comment]
Yes.

**Comment by CthulhuOnIce** [comment]
tested on beecode?

**Comment by Cenrus** [comment]
yes, it seems to be working.

**Pull request merged**
