### PR TITLE
Grave Robber Kit for the Chaplain's armaments beacon

### PR DESCRIPTION
**Pull request by Malgover**
## About The Pull Request

This PR adds a set of Grave Robber clothes inspired by Darkest Dungeon to the Chaplain's armaments beacon and fixes an issue with the witch hunter hat.

grave1
grave4
grave2
grave3

## Why It's Good For The Game

As always, the more clothes the better, and it looks badass. 

## Changelog
:cl:
add: Grave Robber Kit for the Chaplain's armaments beacon & witch hunter hat fix
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
That looks really good

**Comment by Malgover** [comment]
Second update:

grave1
Notable changes:
The patchwork on the pants was improved.
The gloves are fingerless botanist leather gloves with significantly weaker stats (30 fire prot., 20 acid prot.).
The hat now has some sort of golden buckle on its front and is placed one pixel lower on the head of the wearer.
The coat was re-adjusted to be slightly higher in the inventory and the edges of the arms are no longer white to fit the leather gloves better.

grave2
grave3
grave4

**Comment by Malgover** [comment]
(Hopefully) last update:

The hat is again one pixel higher on the head of the wearer because the side view blocked the nose and looked silly.
grave4

The buckle on it was also modified to be less tacky. 
grave2
grave1

**Comment by eeSPee** [comment]
Have it include a shovel?

**Review by ike709 — DISMISSED** [review]
Approved. Fix conflicts and you'll have one (1) ping pass on Discord to get this merged and avoid future conflicts.

**Comment by Malgover** [comment]
Huh, weird. I updated the icon files and it still conflicts?

**Comment by Malgover** [comment]
if there is a God in heaven please let this fix do what I think it does

**Pull request merged**
