### PR TITLE
Styleguiding

### PR DESCRIPTION
**Pull request by qwertyquerty**
## About The Pull Request

Changes a ton of things to abide by the styleguide I'm currently writing. I obviously couldn't get everything since I was doing this all by hand but I am certain I got a big chunk. SpaceManiac please implement styleguiding in DreamChecker.

## Why It's Good For The Game

Makes code have more consistent style.

## Changelog
:cl:
code: styleguiding
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
So far fixes spacing for the follow operators:
```
+=
*=
-=
/=
|=
&=
%=
>>=
<<=
^=
~=
&&
||
==
!=
<=
>=
>>
<<
<>
--
++
%
^
```

And a few ternary operators. Those were harder to do and I don't think I got them all.

It also makes sure that `if` `else if` `switch` `for` `while` and `spawn` all don't have a space before the `(`

**Comment by CthulhuOnIce** [comment]
Removing unnecessary `src.`'s would also be cool

**Comment by qwertyquerty** [comment]
In a lot of cases, src improves readability. I don't want to enforce that.

**Comment by qwertyquerty** [comment]
What I'm worried about is this making porting things a lot harder due to a polluted history. What do you think @ike709 

Should we do this or should we just enforce the styleguide in future commits?

**Comment by ike709** [comment]
There's no performance gain so I don't really see much benefit to this.

**Comment by qwertyquerty** [comment]
Ok then I will just enforce this in the future when I finish writing the styleguide.

**Pull request closed without merging**
