### PR TITLE
3x3 Maint templates

### PR DESCRIPTION
**Pull request by SergeiKoralev**
## About The Pull Request

This is a series of ten (10) maintenance templates intended for use with the random maint spawners that are being implemented. 

## Why It's Good For The Game

Having diversity in maps keeps things fun and entertaining for those insane enough to dive around maint like a true maniac. 

## Changelog
:cl:
add: new 3x3 maint rooms for the random generator.
/:cl:

### CODE REVIEW

**Comment by SergeiKoralev** [comment]
Note to self: Shift around file names to be descriptive, use 001, 002... for numbering.

**Comment by qwertyquerty** [comment]
Not a fan of the gas rooms, and some of these are just bland. Can be fixed though.

**Comment by SergeiKoralev** [comment]
> Not a fan of the gas rooms, and some of these are just bland. Can be fixed though.

Not every room has to be interesting. It's maintenance. There will be interesting areas, and bland areas. Having only interesting areas sort of defeats the point of making them specifically interesting.

**Comment by zeskorion** [comment]
> Not a fan of the gas rooms, and some of these are just bland. Can be fixed though.

We need most of them to be bland, like vesily said. Especially for 3x3, the most common variant

**Pull request merged**
