### PR TITLE
Delta Exploration shuttle tweaks

### PR DESCRIPTION
**Pull request by St0rmC4st3r**
## About The Pull Request

Changes the Delta exploration shuttle layout to be less cramped.
image

Also adds lights to the exploration office on Delta.

## Why It's Good For The Game

Current Delta Exploration shuttle for some reason feels even more cramped than the default one despite being bigger.

## Changelog
:cl:
tweak: Changed the layout of the Deltastation exploration shuttle.
fix: Added lights to Deltastation exploration office.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I don't think there should be sofas on a shuttle

**Comment by PowerfulBacon** [comment]
also looks like they get a sci GPS > an exploration GPS

**Comment by St0rmC4st3r** [comment]
> also looks like they get a sci GPS > an exploration GPS

They had a regular mining GPS when I came, so I thought that sci might look better.

**Comment by St0rmC4st3r** [comment]
Why did it break again?....

**Comment by St0rmC4st3r** [comment]
Whyyyy?!

**Review by Archanial — APPROVED** [review]

**Pull request merged**
