### PR TITLE
Squids 2 electric boogaloo

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Squid language should work this time, i stg i'm gonna shoot myself if it doesn't

## Why It's Good For The Game

Squid language

### CODE REVIEW

**Comment by ghost** [comment]
Travis is broke because I have this open and it's working perfectly fine and I have no idea how or why.

**Comment by qwertyquerty** [comment]
You messed something up nerd. Travis is fine

**Comment by qwertyquerty** [comment]
```
code/modules/mob/living/carbon/human/species_types/squidpeople.dm:37:error: /datum/language/rlyehian: undefined type path
code/modules/surgery/organs/tongue.dm:21:error: /datum/language/rlyehian: undefined type path```

**Comment by ghost** [comment]
well fuck you diffs

**Comment by ghost** [comment]
why diffs no work 

@qwertyquerty fix dis!!

**Comment by qwertyquerty** [comment]
You probably messed up the dmi somehow

**Comment by qwertyquerty** [comment]
Wait naw somethings just messed up with diffs

**Comment by ghost** [comment]
@qwertyquerty should i repull or what???

**Pull request merged**
