### PR TITLE
Fixing a shitty merge that i thought qwerty did but didn't appearently cause i'm smoothed brained

### PR DESCRIPTION
**Pull request by ghost**
Removes the recoil from the shotgun, given it already has an accuracy debuff this isn't really needed, especially considering the recoil causes you to miss almost every shot with a slug based projectile when it's more then about 3 tiles away, there was no need for this nerf at all, don't stealth merge shit just because you don't get your way qwerty and if you do atleast add some sort of balance.

## Why It's Good For The Game

Makes the sidegrade for the bartenders shotgun actually useful again.

## Changelog
:cl:
fix: fixed the sawn-off shotgun.
/:cl:

### CODE REVIEW

**Comment by SomeAngryMiner** [comment]
last time i checked, the recoil isnt that much of a big deal to make an entire PR for it, does it? not like you need to unload 5 beanbags on someone to knock em, 2 do just fine, or 1 if you are one tile away.

**Comment by ghost** [comment]
The recoil makes you miss almost every second shot you make with it, meaning you'll need about 3-5 shells to stam someone when you use the shotgun sawn off given it already has an accuracy penalty

On top of that this PR got a -20 when we voted on it, he shouldn't stealth merge stuff just because he doesn't get his way 
image

.

**Comment by Crossedfall** [comment]
What are you talking about? Qwerty didn't "stealth merge" anything, this has been in for months.

image


image

image

**Comment by ghost** [comment]
I've never seen the recoil for this before yesterday, i just assumed it was him because he talked about adding recoil.

**Comment by ghost** [comment]
I have a better idea I'm taking this down

**Comment by qwertyquerty** [comment]
🤦‍♀

**Comment by qwertyquerty** [comment]
You literally cannot stealthmerge

**Pull request closed without merging**
