### PR TITLE
[DRAFT] Job eligibility now requires each role instead of department (with a single sample)

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
Job eligibility now requires each role instead of department
This PR is currently a draft for the code review, not the detail of job requirement.

This PR only has CMO as a sample for the code.

- [x] Coding the basic system
- [ ] Get reviews for the basic system
- [ ] Code clean up - removes old exp check system
- [ ] Get suggestions from people (mainly admin team) for the playtime requirement for each job

## Why It's Good For The Game
Advance for the higher RP standards

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image

CMO requirement for 6000 minutes of living is an example. I wouldn't really put that.

</details>

### what happens if I add `combined_playtime_req = 600` in the last requirement that needs 120m for each job?

You need to pass 120 minutes for each job first, then the sum of playtime from those job should be 600 minutes.

### What would this format mean?
image

(`checks_sum` is renamed to `combined_playtime_req` in the code)

1. Required job eligibility is 2.
You should have 120 minutes of playtime for 2 of `Chemist, Geneticist, Virologist`
For example, If you have `chemist 120 minutes` and `virologist 120 minutes`, you pass.
Since other three jobs `Medical Doctor, Paramedic, Brig Phys` have no time, these don't count for that.

2. Required total time is 600
Your total playtime for all given jobs should be more than 600
For example, If you have `medical doctor 550 minutes` and `chemist 50 minutes`, you pass.
BUT if the first condition isn't satisfied(120 minutes from two jobs), you don't get a pass.

* So, if you have `Chemist: 120m / Geneticist: 120m / Medical Doctor 360m`, then you get the eligibility.

## Changelog
:cl:
add: Each job now requires different playtime requirement.
/:cl:

### CODE REVIEW

**Comment by Absolucy** [comment]
should probably grandfather in people who already unlocked stuff?

**Comment by EvilDragonfiend** [comment]
> should probably grandfather in people who already unlocked stuff?

If they see something locking in the future with this system, they wouldn't really deserve the jobs.

**Comment by Pirill** [comment]
> If they see something locking in the future with this system, It wouldn't mean they really deserve the jobs.

Absolutely disagree. I know how to cure viruses as a CMO and review them, but I dislike the job itself and have no interest in ever doing it. This PR would lock me out of it until I AFK as Viro enough to get the hours. This needs to be thought out a bit more imo.

**Comment by EvilDragonfiend** [comment]
> > If they see something locking in the future with this system, It wouldn't mean they really deserve the jobs.
> 
> Absolutely disagree. I know how to cure viruses as a CMO and review them, but I dislike the job itself and have no interest in ever doing it. This PR would lock me out of it until I AFK as Viro enough to get the hours. This needs to be thought out a bit more imo.
> 
> I know your example only requires 2/3 in this case, but I can see this cropping up as an issue in other departments or combos potentially depending on final implementation, even if I don't entirely disagree with the basic premise.


> Heads of Staff are held to higher standards than regular crewmembers. You are expected to be a competent person and competent at all the jobs that work under you.

This is what our rule says. We discussed that in discord dev channel, and most of us agreed that some roles should be behind advanced time lock rather than simple department timelock, especially since some jobs are not really for newbies.

But also, we couldn't reach a consensus on the amount of each job's time requirement.
Ruko wanted harsher requirement like viro 5h, chem 5h, gen 5h, doctor 10h, etc
while I am really not a fan of setting such high numbers on the requirement, and some players already know how to play a role when they might have practiced a job already in their local or be from other codebases. and that's why I set the time requirement as 2h in the sample.
I might even wanted to put the eligibility count as 1 for viro/gen/chem jobs, so that you can be CMO with `10h-18h as doctor + 2h-10h as one of viro/gen/chem` (in combination of total 20h med department time req before), since unlocking CMO with 20h chemist doesn't make sense and it wouldn't really prove the competence as CMO for new players.
But that thought was even before I noticed the existence of the rule `competent at all the jobs that work under you` which means a CMO as a new player might need to play a job at least once. That's why I eventually set the eligibility count to 3 for 3 jobs later.

Let's say another example. Becoming CE with full atmos engi time - not knowing how to do any shit to SM. It shouldn't be a thing.

For HoP, this job really doesn't have to play all service/civilian jobs, I believe. I really don't want HoP to have 2h for every job requirement 

Let's say about Shaft miner. It shouldn't be a job that can be accessible by new players. It counts Brig Physician, Security Officer, Exploeration Crew, or more so. I am going to suggest these jobs have `Living 5m` as a minimal time requirement. You are an already veteran from other codebases? Sorry, please play a round as normally once. You are new player? Sorry, no difficult job for you. Try easy jobs first.


Anyway, I know people's concerns, but it shouldn't be an excuse not to put a limitation on some roles, but also I know what people would feel when they see a shitton of time required for some roles, but you wouldn't really see that much.
The main goal after the basic code review is to find an agreeable point where most people wouldn't be pissed off.

**Comment by Absolucy** [comment]
I still think it should grandfather people in who already have a certain amount of head hours: i.e I have 121h of CMO, but very little genetics or virology hours, even though I very much do know how those two jobs work - I just don't find them enjoyable enough to play on their own.

**Comment by tontyGH** [comment]
Basically just repeating what everybody else said, but the problem with this is that it completely ignores how dynamic SS13 inherently is and how often jobs overlap

It's not uncommon for atmos techs and engineers to do eachother's jobs, the medical staff often have to fill in for eachother (because of absent chemists, geneticists, MDs, viros, etc), science is literally entirely interchangeable and this doesn't even take into account the silicon roles which requires experience in EVERY job

Just because I don't have 2 hours as geneticist doesn't necessarily mean I have never ever touched genetics once in my 20-40 hours of medical playtime

Just because I have most of my hours in atmos tech doesn't necessarily mean that I don't know how to set up or fix an SM (on some maps, the SM is on atmos's side too)

If your concern is that new players might stumble onto a head role without the proper experience, then just... make the department experience requirement higher? This system is very short sighted

**Comment by tontyGH** [comment]
If you really really REALLY want this system, I'd suggest making it so that you can still unlock head roles if you have a large amount of hours in a department regardless of how the time is distributed between roles, and just have the experience requirement for that be higher than if you had equal experience in every role

**Comment by EvilDragonfiend** [comment]
I got an another idea to implement more. This will be opened later.

**Pull request closed without merging**
