### PR TITLE
Telescopic riot shield can be equipped in security belt

### PR DESCRIPTION
**Pull request by yorii**
## About The Pull Request

Makes the telescopic riot shield in its inactive state equippable in a security belt.

## Why It's Good For The Game

Pretty self-explanatory, just gives you another place to put the telescopic riot shield.

## Changelog
:cl:
tweak: telescopic shield can be held in security belt
/:cl:

### CODE REVIEW

**Comment by Dingo-Dongler** [comment]
Does this required the shield to be collapsed? Because I feel like it should

**Comment by yorii** [comment]
> Does this required the shield to be collapsed? Because I feel like it should

Yes it does, since an extended riot shield has the weightclass bulky and the belt is limited to holding items of normal weightclass or lower, it will require it be to collapsed.

But I will admit I have not tested this PR at all 😄

**Review by PowerfulBacon — APPROVED** [review]
I mean, it should be fine but testing it first would be fancy

**Comment by yorii** [comment]
well okay then... I tested it now, works as expected 😄 
image

**Pull request merged**
