### PR TITLE
Posted on phone - Adds IPC check to monky leader

### PR DESCRIPTION
**Pull request by Toxici11i**
About The Pull Request
Fixes monky for ipc

Why It's Good For The Game
fixes shit

Changelog
🆑
fix: technically the same issue as plasmamen monky leaders, but that apparently doesnt need to be fixed so /shrug/ - Automatically transforms monky leaders into humans.
/🆑

### CODE REVIEW

**Comment by qwertyquerty** [comment]
I think they also don't turn into monkeys when bit

**Comment by Toxici11i** [comment]
yes thats intentional. its the same as plasmemes

**Comment by Toxici11i** [comment]
I have some sort of autism, please stand by

**Review by Crossedfall — CHANGES_REQUESTED** [review]
Please update the description to use the standard PR template.

For the metacoin issue, you'll need to remove the duplicate entry. If you update from master this issue should already be fixed for you.

**Comment by qwertyquerty** [comment]
He doesn't need to update to master, I just need to rerun the checking, doing now.

**Comment by Toxici11i** [comment]
Yeah its failing because the monkey leader greet() targets a mind datum instead of a body. bruh. ill add a work around I guess

**Comment by Toxici11i** [comment]
ill fix dis when back from colleg

**Comment by Crossedfall** [comment]
Going to close this for now. Please re-open it when you are back from college and are able to work on this. 👍

**Pull request closed without merging**
