### PR TITLE
Makes MindSwap No Longer Affect Mindshielded Targets

### PR DESCRIPTION
**Pull request by DatBoiTim**
Does what it says on the tin.

## About The Pull Request

Adds a single if() statement to check for a mindshield, will inform user of reason of failure apropriately.

## Why It's Good For The Game

No clue why this didn't exist before. Doesn't make much sense. Mindshields seem to stop various magical effects from affecting the brain. Check keeps in line with how Nar'Sie cult conversion handles mindshields. Being implanted will not undo the spell retro-actively. Will only stop spell from being able to target you.

Makes them more consistent.

## Changelog
:cl: DatBoiTim
tweak: Mindshields protect against mindswap spells
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
ah yes of course. mindshield is anti magic. even disables fireballs!

**Comment by DatBoiTim** [comment]
> ah yes of course. mindshield is anti magic. even disables fireballs!

_Don't tempt me_

**Comment by Bestparty** [comment]
Mindshields stop nar'sie because it stops the lies of narsie getting in the brain of the user
Mindswap switches the soul of the 2 people so i cant see any consistency there  with mindshields stopping it

**Comment by PowerfulBacon** [comment]
this is stupid, why nerf the wizard and make a good and expensive spell that is designed to be powerful incredibly situational. The spell itself already stuns the wizard for a good amount of time on use (longer than the other person).

**Comment by DatBoiTim** [comment]
> Mindshields stop nar'sie because it stops the lies of narsie getting in the brain of the user
> 
> Mindswap switches the soul of the 2 people so i cant see any consistency there  with mindshields stopping it
> 
> 

If it targets the soul, shouldn't it be called soulswap? 

Would even keep more consistent with the logic given via text unable to swap with megafauna(soul is non existent/too powerful), dead bodies(soul is fading/gone/why even do this), catatonic(soul is disconnected from the still-living body), and while suiciding(logic is unchanged for this cause you'd still be occupied). And then it would make sense to ignore mindshields.

Especially for megafauna, like I understand why, but saying it's mind is too powerful seems a little odd. Renaming to soul swap would purely be cosmetic/description based.

**Comment by PowerfulBacon** [comment]
Rename it to soulswap then, probably only called mindswap because souls are called minds in code

**Comment by PowerfulBacon** [comment]
This PR seems like a needless change and windshield really doesn't need to be nerfed particularly. I don't really like this vote and I doubt that it will pass if put on vote, so closing.

**Pull request closed without merging**
