### PR TITLE
Changeling tweaks

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request

Alright it's been some time since the last changes to changelings, for the most part the changes were good but there's some things that needed some readjustment:

- Organic Flesh Suit now costs only 1 point since everyone has a skin suit, additionally it has reduced slowdown and is lightly armoured.
- Fleshmend is now quick, short duration heal rather than passive again. Compared to it's previous iteration it heals more damage types (adds toxin and cloneloss healing) but healing is about as half as much as it used to be in each type so that it's not overpowered. 
- Reverts changes made to benefits for absorbing other changelings, now absorbing fellow lings is more rewarding. Helps discourage team lings, and gives the super stealthy antag a natural predator. 
- Augmented Eyesight regains it's flash protection whilst x-ray vision mode is off. 

## Why It's Good For The Game
A number of abilities just suck in it's current state, and absorbing other changelings is in a bad state at the moment. 

## Changelog
:cl:
balance: Absorbing another changeling made more rewarding again. 
tweak: Fleshmend is now an active ability rather than passive heal again. 
tweak: Augmented Eyesight now blocks flashes again. 
tweak: Organic Flesh suit now only costs 1 point, has less slowdown and is armoured. 
/:cl:

### CODE REVIEW

**Comment by TotallyNotChief** [comment]
how about nerfing or making last resort a non-default ability again? absorb another changeling obj is nigh impossible cuz anyone can just headspider at any given moment during the absorption

**Comment by St0rmC4st3r** [comment]
Me no like. It basically changes lings back into killing machines, while they should be stealth oriented. It is unlikely to be merged after all the work that made lings be more stealthy.

**Comment by Sinmero** [comment]
> Last Resort is no longer free, it costs 1 DNA point now. This made the "absorb another changeling" objective almost impossible, so good riddance.

Its true that absorb another ling is basically a 'you wont get greentext' objective but i dont think that making last resort a 1 dna point power will fix that (im not saying that it should be more expensive). 
Here is a good solution of that problem - make it possible to absorb dead headcrabs. 
Basicaly it is impossible to absorb another ling because lings can use last resort when they are dead now. You dont get stunned when lings use last resort near you thou so if you are prepared to kill headcrab you could complete your absorb ling objective.

I think its a good idea to make ling chat free again (nobody ever buys it cmon). Or maybe make it so you need to absorb a certain amout of humans before you unlock it for free.

**Comment by VictorVow** [comment]
@St0rmC4st3r what? Please explain how exactly you interpreted this as a massive combat buff.

@Sinmero absorbing dead headcrabs would be decent, not sure how to add that personally however. Ling chat I might decrease the price by 1 but not make it free, since competition over cooperation is back at normal levels with this PR. And I don't want to encourage mass husking of crew.

**Comment by PowerfulBacon** [comment]
> now absorbing fellow lings is more rewarding.

Won't the other lings spend all their points so you will get 0 for absorbing another ling?

**Comment by VictorVow** [comment]
It's reverted to the reward structure it was before the nerf, so you still get points even if that changeling spent all theirs.

**Comment by zeskorion** [comment]
> @St0rmC4st3r what? Please explain how exactly you interpreted this as a massive combat buff.
> 
> @Sinmero absorbing dead headcrabs would be decent, not sure how to add that personally however. Ling chat I might decrease the price by 1 but not make it free, since competition over cooperation is back at normal levels with this PR. And I don't want to encourage mass husking of crew.

either add an attack_hand check to the dead headcrab that checks if the attacker is a ling, or dont allow last resort to be used while being absorbed. i echo this statement

**Comment by RafRoq** [comment]
I don't like the flesh mend change, I prefer the passive heal version

**Comment by TotallyNotChief** [comment]
yeah i agree, keep the fleshmend as it is

**Comment by eLeCtrOssSnake** [comment]
This fucking shitty pr is a disguise of 'me make no last resort cuz I am salty'

**Comment by VictorVow** [comment]
Reverted regenerate/last resort changes, was struggling to implement zesk's proposed alternative solution so I'll just leave that fix for a separate PR.

**Comment by eLeCtrOssSnake** [comment]
These are bad unthoughtful changes.

**Comment by PowerfulBacon** [comment]
Tentacle costing 1? That is one of their best abilities, it's an instant ranged aggressive grab

**Comment by VictorVow** [comment]
It's virtually never bought because it's easy to dodge mid-combat, wasting your slow-regenerating chem supply. And with Zesko's aggro grab nerf it's no longer a stun so you can shove or melee them whilst grabbed (or even piggyback). I'd like to see it being used more to give some variety to assassination rather than the typical shriek+armblade combo.

**Comment by VictorVow** [comment]
@PowerfulBacon this has been open forever reeee

**Comment by Unidentified-Biohazard** [comment]
Yes. Good.

**Comment by ghost** [comment]
This deserves a PR vote, I'm curious how the community at large feels about this

**Comment by PowerfulBacon** [comment]
Organic Space Suit renamed Organic Flesh Suit. Since it's been made useless by skin suits, it now additionally has similar properties to a riot suit except slower and spaceproof. Still costs 2 DNA points.

I think it would be better as low armour, low slowdown and spaceproof for only 1 point.

    Chitinous Armor rebalanced to instead reduce energy damage more, and melee damage less.
    Fleshmend is now 3 points, but is a quick, short duration heal rather than passive again. Compared to it's previous iteration it heals more damage types (adds toxin and cloneloss healing) but healing is about as half as much as it used to be in each type so that it's not overpowered.

I think it should stay as 2 points but be a weak active ability. At the moment it does literally nothing.

    Reverts changes made to benefits for absorbing other changelings, now absorbing fellow lings is more rewarding. Helps discourage team lings, and gives the super stealthy antag a natural predator.

Good change.

    Augmented Eyesight is now 3 points, but regains it's flash protection whilst x-ray vision mode is off.

I have no idea why the flash protection was removed from it personally, flash combat is cringe and antags should have an accessible way to counter common tiding combat.

    Tentacle now costs 1 point.

Tentacle is one of the best, for only 10 chemicals you can instantly disarm someone and bring them out of laser range and into combat range (your most optimal state)

**Comment by VictorVow** [comment]
Changes made, should be ready.

**Comment by Trash0077** [comment]
Where can i see the full changes list? People are talking about changes to the ling tentacle despite him not writing anything about it, do you guys look it up in the code?

**Comment by Isy232** [comment]
> Where can i see the full changes list? People are talking about changes to the ling tentacle despite him not writing anything about it, do you guys look it up in the code?

I think that means they are no longer considering the changes.

If the PR makes more changes than in the description the maintainers wouldn't let it be voted on I think.

**Comment by VictorVow** [comment]
Correct, the tentacle changes were reverted.

**Review by PowerfulBacon — DISMISSED** [review]

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
