### PR TITLE
Removes beecoin reward for greentexting.

### PR DESCRIPTION
**Pull request by Kapu1178**
## About The Pull Request
Title.

## Why It's Good For The Game
Old design philosophy. This doesn't fit the server's current view on antagonists existing to drive rounds and create fun, it encourages hyper-optimization and playing in the most boring way possible.

## Changelog
:cl:
tweak: Greentexting no longer awards beecoins.
/:cl:

### CODE REVIEW

**Review by ike709 — APPROVED** [review]
I would have preferred this being done alongside an ambitions port, but one step at a time I guess.

**Comment by PowerfulBacon** [comment]
200 beecoins is nothing, people value the greentext not the coins. Also if antagonists exist to drive the round, surely they should be rewarded for surviving or something.

**Comment by Kapu1178** [comment]
> 200 beecoins is nothing, people value the greentext not the coins. Also if antagonists exist to drive the round, surely they should be rewarded for surviving or something.

Having survived the entire round doesn't equate to having contributed much to it. Antags should be encouraged to go out in interesting ways.

**Comment by PowerfulBacon** [comment]
> Antags should be encouraged to go out in interesting ways.

lmao they get banned for going out in interesting ways half the time

**Comment by rkvothe14** [comment]
>lmao they get banned for going out in interesting ways half the time

Not really, look at the bans page, most bans are about griefers/selfantags.

**Comment by SergeiKoralev** [comment]
> 

they're talking about antag bans. 

And normally antags wind up getting banned for burning the station down. Not for being interesting and fun.

**Comment by rkvothe14** [comment]
> > 
> 
> they're talking about antag bans.
> 
> And normally antags wind up getting banned for burning the station down. Not for being interesting and fun.

Most of the antag bans that occured since I'm adminning for the server are:

- Plasmaflooding the whole station (obviously bad, and shouldn't be considered going out in an interesting way)
- Team antags throwing the game for their team
- Lings literally baiting people to create witnesses/enable more reasonless murder

(I'm agreeing with you here, just adding my experience)

**Comment by Mat05usz** [comment]
Are you familiar with what surivior bias is? Most antags, who follow rules, are only quietly doing their objectives because they are afraid that if they kill one too many people they will get punished. You only ban those who blatantly disregard rules and therefore you use them in arguments by looking at the bans page.

**Comment by rkvothe14** [comment]
> Are you familiar with what surivior bias is? Most antags, who follow rules, are only quietly doing their objectives because they are afraid that if they kill one too many people they will get punished. You only ban those who blatantly disregard rules and therefore you use them in arguments by looking at the bans page.

I always check on antags when I'm online, which is a lot of time when I have the time, and I've seen my fair share of loud antags who had no issues with me or other admins.

**Comment by Mat05usz** [comment]
> I always check on antags when I'm online, which is a lot of time when I have the time, and I've seen my fair share of loud antags who had no issues with me or other admins.

And how do those instances of rare antags compare to all others that don't do shit? I know that there is one antag per 2/3 games that goes wild, but that's pure statistics and them going loud ends on killing sec, because they can't do much else.

Edit: That's gonna be marked as off topic anways. 
So, no, that PR is not gonna do anything. Noone cares about beecoins just about the sweet green text on the round end report, and if you think otherwise then we're probably playing on two different servers.

**Comment by rkvothe14** [comment]
> So, no, that PR is not gonna do anything. Noone cares about beecoins just about the sweet green text on the round end report, and if you think otherwise then we're probably playing on two different servers.

Probably not, but I feel like this helps at least a tiny bit in the end. With that mentality, we wouldn't change anything ever, I feel like.

**Comment by Mat05usz** [comment]
> > So, no, that PR is not gonna do anything. Noone cares about beecoins just about the sweet green text on the round end report, and if you think otherwise then we're probably playing on two different servers.
> 
> Probably not, but I feel like this helps at least a tiny bit in the end. With that mentality, we wouldn't change anything ever, I feel like.

Problem is that this PR promises how good it is for the RP, how it will kill the powergaming aspect etc. While when you look at it, it does neither, it's a boilerplate that has good intentions but will do shit.

**Comment by rkvothe14** [comment]
> Problem is that this PR promises how good it is for the RP, how it will kill the powergaming aspect etc. While when you look at it, it does neither, it's a boilerplate that has good intentions but will do shit.

This is just a tiny step until we get ambitions, the actual system that's supposed to be good for RP.

**Comment by Mat05usz** [comment]
> > Problem is that this PR promises how good it is for the RP, how it will kill the powergaming aspect etc. While when you look at it, it does neither, it's a boilerplate that has good intentions but will do shit.
> 
> This is just a tiny step until we get ambitions, the actual system that's supposed to be good for RP.

It's not a step, it's a pointless PR based on an assumption that people care about beecoins rather than RP, which is crazy. It gives nothing but a safe feeling that something has been done for the 'RP', while effectively nothing has changed.

**Comment by ta3370** [comment]
Personally, when I get antag I go for story/adventure to the point of even actively doing stuff I'm almost certain will not work on the off chance something interesting will come of it.
I think this is a good PR, as it removes incentive to not do that/perceived loss for doing that. Encouraging more interaction focused on other players instead of ""winning""

**Comment by ta3370** [comment]
Next step is to make roundend text not display as green/red.

**Comment by Mat05usz** [comment]
> Next step is to make roundend text not display as green/red.

If anything, that should be THE step to stop people from trying to win at any cost, as it's literally what I said in the response above.

**Comment by ta3370** [comment]
Both are the same "Monkey get dopamine" result. Both are the issue.

**Comment by ta3370** [comment]
> > Next step is to make roundend text not display as green/red.
> 
> If anything, that should be THE step to stop people from trying to win at any cost, as it's literally what I said in the response above.

Both are the same "Monkey get dopamine" result. Both are the issue.

**Comment by Mat05usz** [comment]
> Both are the same "Monkey get dopamine" result. Both are the issue.

One of them actually matters as it is seen by everyone involved in the round so you can flex, other is seen only by said person and doesn't matter at all as noone cares about bee coins.

**Comment by ike709** [comment]
Since the only discussion is whether or not to remove greentext, which is something we've already decided to do, I'm going to go ahead and merge this.

**Comment by utilbird** [comment]
That was a short discussion

I'd say you guys are severely overestimating how much people care about metacoins lmao. It's a nice thing to throw in for those who actually did their objectives. This is a pedantic change that makes saving up for shop items even more slow

**Comment by ike709** [comment]
It was already discussed during the last meeting.

**Pull request merged**
