### PR TITLE
TGUI Secrets Panel

### PR DESCRIPTION
**Pull request by TheTrigg**
## About The Pull Request

Not too happy with how it looks. A bit too bland IMO. Meh. Still much better than that html one.
Finished this while recovering from anesthetics. Pretty sure everything works, though.

## Why It's Good For The Game

image

## Changelog
:cl: Trigg
add: TGUI admin Secrets Panel
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
The categories/buttons definitely shouldn't be the same color as the background.

**Comment by PowerfulBacon** [comment]
If the secret datum is global, wouldnt this UI be shared and you would be able to see other admin interactions with it?

**Comment by TheTrigg** [comment]
> The categories/buttons definitely shouldn't be the same color as the background.

That's kinda just the problem with the "admin" css theme, almost everything's this shade of gray. I wanted to make a pickable theme but it would have to be persistent between rounds, meaning saved in player preferences, meaning too much work for my smol brain. Maybe I'll change the theme to ntos or something, it's just some colors after all.

> If the secret datum is global, wouldnt this UI be shared and you would be able to see other admin interactions with it?

`useLocalState` isn't shared, according to its own comments. Should be fine.

**Comment by ike709** [comment]
so just edit the theme css

**Comment by TheTrigg** [comment]
hot
image

**Review by ike709 — APPROVED** [review]

**Pull request merged**
