### PR TITLE
Paper now uses markdown

### PR DESCRIPTION
**Pull request by ike709**
https://github.com/tgstation/tgstation/pull/51534 and https://github.com/tgstation/tgstation/pull/51731

EDIT: Now includes https://github.com/tgstation/tgstation/pull/51863 and https://github.com/tgstation/tgstation/pull/51862

## Changelog
:cl:
add: Paper has been completely revamped to use markdown instead of pencode.
add: Use %sign to sign the new paper or [______] to create a field. Everything else is just normal markdown.
del: All of the pencode forms on the wiki are now outdated.
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Bacon said he'd add a help tab with markdown examples.

**Comment by PowerfulBacon** [comment]
Oh yea, I'll do that now so I can procrastinate doing other stuff

Gimme like an hour or two to find out how this works and plop a little button somewhere on the TGUI (It uses TGUI right?).

**Comment by PowerfulBacon** [comment]
It looks kind of ugly and is very long in terms of lines, but it works. 
image

**Comment by ike709** [comment]
DNM until TG merges some fixes and I include them.

**Comment by eLeCtrOssSnake** [comment]
I always wanted it to be that way, so you can write stuff on the fly, not creating big tags.

**Comment by eLeCtrOssSnake** [comment]
Also, we finally gonna get devil's papers to work properly I guess.

**Comment by ike709** [comment]
This is ready.

**Comment by MCterra10** [comment]
inb4 buggy mess because no players reported anything during the testmerge

**Pull request merged**
