### PR TITLE
[Draft] Makes Lizardmen a bit more unique

### PR DESCRIPTION
**Pull request by CydiaLamiales**
## About The Pull Request
This PR aims to make Lizardmen a more unique race by giving them gameplay differences from humans.

- [X] *squeal and *tail thump emotes
Ports https://github.com/shiptest-ss13/Shiptest/pull/2159
- [x] make organic mobs rely on their heart for body heat production, make lizard hearts produce no bodyheat
- [ ] make lizards be clumsy if they're tailless
- [ ] allow them to regrow their tail by "shedding their skin", costs lots of hunger and makes them vulnerable for a period after that
- [ ] make lizard (possibly felinid) stomachs give immunity to gaining viruses when eating rats
- [ ] make the shower's normal temperature adjust the body temperature to the normal one
- [ ] add "chemical heating packets" that can be ordered through cargo or made in chem
- [ ] give lizards an emergency chem heating packet
- [ ] add a science made gizmo that can regulate body heat but runs on a battery, can be attached to a jumpsuit like a pocket protector
- [ ] add some sort of ghetto craftable thermal stone that can absorb heat from the atmosphere when on the floor and exchange its heat with the body when held/in pockets
- [ ] make digitigrade legs not have the "stub toe on a table" thing

## Why It's Good For The Game
Lizardmen, aside from their quirky speech, don't currently differ much from humans, gameplay-wise. This PR aims to rectify that by imposing new challenges on them as well as giving them new possibilities.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Emotes

https://github.com/BeeStation/BeeStation-Hornet/assets/110184118/3e7435a2-7c2e-4751-83ff-e3f551d3e217

Bodyheat testing

image

image

</details>

## Changelog
:cl:
add: Added two new Lizard emotes - "squeak" and "thump"
balance: Made hearts be the organ that maintains the body heat in ORGANIC humanoids
balance: Made hearts generate less body heat the more damage they are
balance: Made failing and not beating hearts generate no body heat
balance: Made lizardmen hearts generate no body heat and be fully dependent on the atmosphere's temperature
balance: Made the advanced cybernetic heart be 1.5 as good at maintaining body heat as the organic one
/:cl:

### CODE REVIEW

**Comment by bluezorua** [comment]
the emotes are honestly just annoying and removing virus gain from rats is just a bad idea

otherwise I love the body heat mechanics

**Comment by CydiaLamiales** [comment]
> the emotes are honestly just annoying

Subjective, several lizard players requested them to be ported

> removing virus gain from rats is just a bad idea

Could you elaborate?

**Comment by bluezorua** [comment]
> > removing virus gain from rats is just a bad idea
> 
> Could you elaborate?
rat viruses infecting lizards and felinids was an intentional design choice and gives medbay something to do. giving them snowflake immunity just makes it hugbox

**Comment by CydiaLamiales** [comment]
> > > removing virus gain from rats is just a bad idea
> > 
> > 
> > Could you elaborate?
> > rat viruses infecting lizards and felinids was an intentional design choice and gives medbay something to do. giving them snowflake immunity just makes it hugbox

For one, Lizardmen and felinids are highly more likely to have a dormant virus, which gives Viro a reason to seek them out.
For two, maint rat virus generation is rather weird and can sometimes give the mice a virus with more symptoms that's normally possible.
For three, plenty of tickets have happened because a virus gained from a maint rat spread and caused too much havoc.
And I'm not proposing a snowflake code with species handling, instead having unique stomach organs that would handle the infection instead, which could be transplanted into other species' bodies.

**Comment by itsmeow** [comment]
If you want per-species body temp, you can yoink the code from the frostwings PR

**Review by Rukofamicom — COMMENTED** [review]
Gonna go ahead and put this here instead of in discord DM: Any species innate traits that are not directly related to an organ function should not be tied to an organ.

Tying body heat to hearts is bad. This should be tied to individual species innately and not possible to change with an organ transplant.

**Comment by Rukofamicom** [comment]
Coincidentally I did not mean to uncheck your checkbox - it's wild that I can just do that on accident while scrolling.

**Comment by CydiaLamiales** [comment]
Gonna have to pit this in the "I'll do it later" foreverbox because I have too many open PRs and too little time.

**Pull request closed without merging**
