### PR TITLE
Food Supply Changes and Food Fillers

### PR DESCRIPTION
**Pull request by DarnTheMarn**
## About The Pull Request
This pull request adds a new reagent, maltodextrin, to most junk food and donk pockets. It has no nutritional value on it's own, is almost tasteless, and metabolizes very slowly. After fully metabolized, it reduces satiety to slightly below the level of satiety you were before you ate the food. In short, it's like lipolicide but slow acting and without the toxin damage. 5u of maltodextrin takes roughly five and a half minutes to fully metabolize. One unit of maltodextrin roughly eliminates one unit of nutriment and two units of sugar hunger-wise. The goal being to make junk food into a snack rather than a full meal. Energy bars were excluded because honestly when was the last time you saw a chef make an empowered burger for an ethereal. 

## Why It's Good For The Game

The abundance of good food in each station renders the chef largely redundant. A large amount of people never visit the kitchen since they can stuff their face with nigh infinite amounts of junk food, donuts, and the donk pockets in their department. And I don't blame them, they are actively incentivized to do so as warm donks contain omnizine and donuts heal security. 

By reducing the efficacy of round start food, the chef will become a far more important and appreciated member of the station. It also has the pleasant side effect of forcing people who would otherwise turtle in their department to leave to acquire food, creating an opportunity for roleplay as well as action against them. Food related gimmicks will also be much easier to pull off now that food is harder to come by, so maybe the forgotten second kitchen in Fland will finally get some use.

## Testing Photographs and Procedure

<details>

Just before feeding test subject a candy bar with maltodextrin

Maltodextrin in the system and metabolizing very slowly

Hunger level after being fed but before maltodextrin kicks in

Hunger level after maltodextrin has been fully metabolized.

<summary>Screenshots&Videos</summary>

</details>

## Changelog
:cl:
add: Adds a new reagent, maltodextrin.
add: Adds maltodextrin to donk pockets and vendor food.
del: Removed donuts and their references from the SecTech
/:cl:

### CODE REVIEW

**Comment by CydiaLamiales** [comment]
Donk pockets also server as a ghetto source of omnizine, this has a fair impact on chemistry and ghetto healing sources.

**Comment by DarnTheMarn** [comment]
> Donk pockets also serve as a ghetto source of omnizine, this has a fair impact on chemistry and ghetto healing sources.

If you have a chem master you can easily filter it out since it doesn't replace any existing chems. Ghetto healing is ghetto, you already have impurities from the nutriment and flavorings from the donks already, whats another 5u. And if you have the means to turn your ghetto mix into pills or patches, you have the ability to filter out the maltodextrin too.

**Comment by CydiaLamiales** [comment]
> > Donk pockets also serve as a ghetto source of omnizine, this has a fair impact on chemistry and ghetto healing sources.
> 
> If you have a chem master you can easily filter it out since it doesn't replace any existing chems. Ghetto healing is ghetto, you already have impurities from the nutriment and flavorings from the donks already, whats another 5u. And if you have the means to turn your ghetto mix into pills or patches, you have the ability to filter out the maltodextrin too.

I'm saying that this greatly reduces the amount of omnizine you can get from roundstart spawning donks.

**Comment by DarnTheMarn** [comment]
> 



> > > Donk pockets also serve as a ghetto source of omnizine, this has a fair impact on chemistry and ghetto healing sources.
> > 
> > 
> > If you have a chem master you can easily filter it out since it doesn't replace any existing chems. Ghetto healing is ghetto, you already have impurities from the nutriment and flavorings from the donks already, whats another 5u. And if you have the means to turn your ghetto mix into pills or patches, you have the ability to filter out the maltodextrin too.
> 
> I'm saying that this greatly reduces the amount of omnizine you can get from roundstart spawning donks.

I think greatly is a bit of an overstatement. At the very high end with unflavored classic donks you lose a grand total of 6u of omnizine per box, but with flavored boxes you only lose 2u of omnizine per box. Omnizine is still readily available at botany, every round they rush for earthsblood and along the way can pick up omnizine extremely easily and provide you with far more than donk grinding ever could.

**Comment by CydiaLamiales** [comment]
> > 
> 
> > > > Donk pockets also serve as a ghetto source of omnizine, this has a fair impact on chemistry and ghetto healing sources.
> > > 
> > > 
> > > If you have a chem master you can easily filter it out since it doesn't replace any existing chems. Ghetto healing is ghetto, you already have impurities from the nutriment and flavorings from the donks already, whats another 5u. And if you have the means to turn your ghetto mix into pills or patches, you have the ability to filter out the maltodextrin too.
> > 
> > 
> > I'm saying that this greatly reduces the amount of omnizine you can get from roundstart spawning donks.
> 
> I think greatly is a bit of an overstatement. At the very high end with unflavored classic donks you lose a grand total of 6u of omnizine per box, but with flavored boxes you only lose 2u of omnizine per box. Omnizine is still readily available at botany, every round they rush for earthsblood and along the way can pick up omnizine extremely easily and provide you with far more than donk grinding ever could.

I'm just saying that this does reduce the availability of roundstart omnizine.
Also no botanist worth his own salt bothers with growing Ambrosia Deus for the seeds, it's always skipped in favor of Gaia.

**Comment by DarnTheMarn** [comment]
> > > 
> > 
> > 
> > > > > Donk pockets also serve as a ghetto source of omnizine, this has a fair impact on chemistry and ghetto healing sources.
> > > > 
> > > > 
> > > > If you have a chem master you can easily filter it out since it doesn't replace any existing chems. Ghetto healing is ghetto, you already have impurities from the nutriment and flavorings from the donks already, whats another 5u. And if you have the means to turn your ghetto mix into pills or patches, you have the ability to filter out the maltodextrin too.
> > > 
> > > 
> > > I'm saying that this greatly reduces the amount of omnizine you can get from roundstart spawning donks.
> > 
> > 
> > I think greatly is a bit of an overstatement. At the very high end with unflavored classic donks you lose a grand total of 6u of omnizine per box, but with flavored boxes you only lose 2u of omnizine per box. Omnizine is still readily available at botany, every round they rush for earthsblood and along the way can pick up omnizine extremely easily and provide you with far more than donk grinding ever could.
> 
> I'm just saying that this does reduce the availability of roundstart omnizine. Also no botanist worth his own salt bothers with growing Ambrosia Deus for the seeds, it's always skipped in favor of Gaia.

It does, but it's not the primary goal of the PR, and it barely does at the end of the day. Most of the food I deleted from maps  were donut boxes, they spawned absolutely everywhere on some maps. Donk boxes also haven't been removed from maint loot tables, they spawn pretty frequently in there and are still viable as a source of omnizine. Gathering multiple boxes might be easier now that you can't subsist solely off of them.

**Comment by LodedDiper69** [comment]
This will change nothing as long as starvation has no gameplay effects. The speed penalty is so minor you barely even notice it. A good portion of people just never eat.

**Comment by DarnTheMarn** [comment]
> This will change nothing as long as starvation has no gameplay effects. The speed penalty is so minor you barely even notice it. A good portion of people just never eat.

This is true. I'd be willing to make the move penalty for being starving as debilitating as the one for being fat. Another thing that would help would be removing insanity as if you just ignore mood for long enough, it stops being a problem. But the mood changes are out of scope for the PR, and I'll wait to see what the maint has to say before changing any speed penalties.

**Comment by PestoVerde322** [comment]
I find removing all the donut box is a bit *too* harsh, I think.

**Comment by DarnTheMarn** [comment]
> I find removing all the donut box is a bit _too_ harsh, I think.

The way the PR is right now, donuts have the most reason to be removed since they were excluded from maltodextrin additions, have more food items than donk boxes, and heal security. I would be willing to meet in the middle though and replace non-security donut box spawns with a lesser food item so people can still tide themselves over until the chef gets rolling without making the chef entirely redundant.

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
Donut boxes should remain but have maltodextrin just like the other junk food items.

**Comment by CydiaLamiales** [comment]
Crafted donuts should probably be a subtype that doesn't have maltodextrin.

**Comment by DarnTheMarn** [comment]
> Donut boxes should remain but have maltodextrin just like the other junk food items.

Alright, when I have the time I will re-add donut spawns, combined with: 

>Crafted donuts should probably be a subtype that doesn't have maltodextrin.

**Comment by DarnTheMarn** [comment]
To summarize changes, donut boxes now spawn a special subset of donut, premade donuts. They are the same as normal donuts except with maltodextrin added. I tweaked the amount of maltodextrin in donk pockets and donuts so that eating them is now eventually a net negative nutrition wise since they are healing foods. I also reverted the reduction in donk spawns per box with this in mind.

I'm still not particularly fond of the amount of free donut spawns, it doesn't really make sense to me to have that amount of food just lying around, healing food at that. But I might address that in another PR another time.

**Comment by Rukofamicom** [comment]
I'm not going to be the best judge of boxes being added and removed from maps so I'm going to leave exact review of those to @PestoVerde322, but I want to give a basic opinion real quick:

* Some amount of pre-made donuts should be available in at least security areas if only for the memes (Sec outposts instead of main sec area would be funny for this, so other departments can mock officers raiding the donuts)
* Donk pockets should remain available anywhere there's a microwave *outside* of the kitchen, just because they're thematically appropriate "easy" food for a break room and you're already toning them down some.
* Vending machines for other food should remain available to everyone. 
* Maltodextrin should be what motivates people to seek out better food from the cook, or to seek someone to be a cook in the absence of one, rather than a forced scarcity of junk food.

**Review by Rukofamicom — APPROVED** [review]

**Comment by Rukofamicom** [comment]
With approval for final mapping changes, this can be merged

**Pull request merged**
