### PR TITLE
Metastation SM used Neutrogena and has volume now

### PR DESCRIPTION
**Pull request by Mick1299**
## About The Pull Request
makes a few alteration to #2002. Engineers will have to turn on the pumps again during SM setup. Replaces the two final gas pumps in chamber itself.

## Why It's Good For The Game
While I agree with @xboxnoob 's choice to replace the gas pumps with volume pumps, they did it in a messy way. This fixes a few things with it.

**1. Fixes a decal that was deleted.**
Minor, but consistency is key

**2. Replaces two final gas pumps in and out of the SM chamber with volume pumps.**
The first gas pump after the scrubbers was the major cause of delam after fastmos was added. Replacing the rest of the pumps with volumes does little when this was the problematic one. 

**3. Replaces most instances of the on variant of volume pump with off variants.**
On variants of volume pumps were used, essentially trivialising the SM setup. This turns them off, meaning engineers have to do the same work to setup the SM as they did previously.

NOTE
This was a web edit with FastDMM2, point anything out if I missed it

## Changelog
:cl:
tweak: Metastation SM pumps
/:cl:

### CODE REVIEW

**Comment by Mick1299** [comment]
Don't merge, some weird interaction with Metastation and FastDMM2 reset all the airlock controller directions to 2

**Comment by zeskorion** [comment]
> Don't merge, some weird interaction with Metastation and FastDMM2 reset all the airlock controller directions to 2

not directions per-se, but offsets

**Comment by Mick1299** [comment]
These are the exact same airlock

Box:
Box

Meta:
Meta

**Comment by Mick1299** [comment]
Manually fixed all the airlock controller directions. That might also solve the FastDMM2 issue, but it'll need to be merged to find out

**Review by zeskorion — APPROVED** [review]
looks good to me...

**Pull request merged**
