### PR TITLE
bullets now need gunpowder

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
-bullets and shotgun shells printed from protolathes now need gunpowder. Rubbershot is excempt
-basic autolathe shotgun shell types are now crafted, using a special empty hull type, which is also craftable
-autolathe no longer prints most ammo. Most is relegated to the seclathe, but it does print empty shells

## Why It's Good For The Game
lethal ammo is way too easy to produce. Making it require inter-departmental cooperation should discourage shotgun shitsec- because shitsec doesnt know how to ask chem for gunpowder

## Changelog
:cl:
del: Removed most ammo from autolathe, moved to seclathe
tweak: basic shotgun ammo is craftable
balance: printing ammo from lathes uses black powder
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
what the fuck is gunpowder and how do you make-
oh
you mean blackpowder?

**Comment by ghost** [comment]
time to literally never print ammo again.

**Comment by zeskorion** [comment]
> what the fuck is gunpowder and how do you make-
> oh
> you mean blackpowder?

yes

**Comment by RafRoq** [comment]
You know this is a shit PR and people will never print ammo again do you ?

**Comment by ivanmixo** [comment]
Make nobody ever use shotguns again, the PR? 

Why would a super futuristic space station require it's employees to manually make gunpowder for their ammo? Kinda stupid if you ask me.

**Comment by zeskorion** [comment]
> Make nobody ever use shotguns again, the PR?
> 
> Why would a super futuristic space station require it's employees to manually make gunpowder for their ammo? Kinda stupid if you ask me.



> You know this is a shit PR and people will never print ammo again do you ?

it's the best way to make shotguns no longer the end-all be-all to combat, as well as make the lethal ammo locker actually matter.

**Comment by RafRoq** [comment]
It is not the best way, forced departmental cooperation is not good, people never cooperate, people will never fabricate ammo again, if the >>players<< are unhappy with shotguns they will agree with you and maybe it should be merged, but no one agreed yet and maybe none will, it will just switch people to lasers that are easier than shotguns to recharge

**Comment by zeskorion** [comment]
> It is not the best way, forced departmental cooperation is not good, people never cooperate, people will never fabricate ammo again, if the >>players<< are unhappy with shotguns they will agree with you and maybe it should be merged, but no one agreed yet and maybe none will, it will just switch people to lasers that are easier than shotguns to recharge

nanotrasen personnel should have a reason to prefer lasers to bullets anyways. shotguns are bullshit cuz of how fucking fast they kill- there is no factor, other than scarcity, to balance that out. The locker of lethal ammo points to scarcity of ammo being an intended factor- but it never actually comes into play. The fact that, as an assistant, i can just hack a public autolathe and fill my belt trash bag with shotgun slugs for my improvised shotgun- which is a strategy i employ often- is bad. Making it take a bit of effort to get shotgun ammo (honestly, black powder is not super hard to make) gives it the balance factor it deserves. Combined with my other buff to rubbershot, i think this is a good change

**Comment by RafRoq** [comment]
People will never make gunpowder for that purpose and I highly doubt people agree with you with this pr

**Comment by yyzsong** [comment]
NGL, im in favor of merging this so i can make sec grovel at my chemist feet

**Comment by VictorVow** [comment]
Ballistics are necessary due to the presence of EMPs, especially vs cult. Being reliant on a box or two each of ammo max then running out because Chemistry is never going to make black powder for you even if they weren't already cult is dumb as hell. 

No other ammo is reliant on that department so it just makes this suggestion a clear "I ded" PR.

**Comment by zeskorion** [comment]
> Ballistics are necessary due to the presence of EMPs, especially vs cult. Being reliant on a box or two each of ammo max then running out because Chemistry is never going to make black powder for you even if they weren't already cult is dumb as hell.
> 
> No other ammo is reliant on that department so it just makes this suggestion a clear "I ded" PR.

Ballistics should be used sparingly, and the game is not balanced around shotguns and such. This isn't an ided, shotguns are just insane compared to all other roundstart weapons.

**Comment by RafRoq** [comment]
balance balance balance balance balance

Bro this is not a esports game, @victor239 made a very good point.

>Ballistics should be used sparingly

Why? You are probably the only one who thinks that

**Comment by TotallyNotChief** [comment]
what the fuck zesko

**Comment by zeskorion** [comment]
> what the fuck zesko

Funy

**Comment by zeskorion** [comment]
I'll close this, but let it be known

I'm right.

**Comment by ghost** [comment]
> I'll close this, but let it be known
> 
> I'm right.

no you are batshit crazy

**Pull request closed without merging**
