### PR TITLE
makes all wall-mounted machines/signs show up above windows

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

no more ugly below the window switches or posters

## Why It's Good For The Game

it is

## Changelog
:cl:
tweak: all wall-mounted machines now show up above windows
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
May result in a few specific issues but overall looks good.

**Review by francinum — APPROVED** [review]

**Comment by Mick1299** [comment]
How about, instead of a code based fix, we stop mapping wall mounted machines on windows. Seems like bad mapping practice ot have wall mounted machines on windows in the first place.

**Comment by francinum** [comment]
We probably ought to have a style guide about this, yeah.

Still a good safety though. It's entirely valid for things to end up in this state.

**Comment by jupyterkat** [comment]
with things that are forced to spawn in windows in random maints and it just clips under the window. nothing wrong with putting stuff on the windows tbh, it's just the broken layers

**Comment by Mick1299** [comment]
Forgot about random maints, thats a great point

**Comment by francinum** [comment]
You can actually get objects into this state rather easily as I'm like 90% sure wallframes aren't even notified if their parent wall deconstructs.

Sounds like a feature request for the backlog though.

**Pull request merged**
