### PR TITLE
Box Station Showers: Final

### PR DESCRIPTION
**Pull request by LastCrusader105**
## About The Pull Request
Moves fireclosets to engineering lobby and replaces them with showers from blastdoors

## Why It's Good For The Game
stops player getting crushed

## Changelog
:cl:
add: Showers and fire closets (closets have items I checked)
del: Showers and fire closets
/:cl:

### CODE REVIEW

**Comment by LastCrusader105** [comment]
@Crossedfall as promised done 9h later

**Comment by qwertyquerty** [comment]
conflicts

**Comment by LastCrusader105** [comment]
was it cause i didnt complie it and add the dmb file?

**Comment by LastCrusader105** [comment]
ah cause im pulling from my master

**Comment by LastCrusader105** [comment]
i will close it and start a new one my apologies, unless @qwertyquerty knows a way to edit where I pull it from?

**Comment by qwertyquerty** [comment]
Make a new one

**Comment by LastCrusader105** [comment]
in my hubris i made a boo boo

**Pull request closed without merging**
