### PR TITLE
Add dermal button icons

### PR DESCRIPTION
**Pull request by Tamuren**
## About The Pull Request

Grabs the latest icons/mob/actions/actions_items.dmi from tgstation and replace's beestation's  icons/mob/actions/actions_items.dmi

## Why It's Good For The Game

It's got dermal button icons so the dermal buttons will have icons.

## Changelog
:cl:XDTM
imageadd: Adds dermal button icons for nanites
/:cl:

---

Ports icons from https://github.com/tgstation/tgstation/pull/47071

### CODE REVIEW

**Comment by Crossedfall** [comment]
Always include information on where you're porting from. I've added in the information for you this time, but in the future please be more mindful.

**Comment by Tamuren** [comment]
Thanks

**Comment by zeskorion** [comment]
this appears to only add the icon file- does the dermal button code already reference these icons?

**Comment by PowerfulBacon** [comment]
> 
> 
> this appears to only add the icon file- does the dermal button code already reference these icons?

Yes

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
wait maybe not, let me check code
Edit: They are referenced but not included

**Pull request merged**
