### PR TITLE
Ports C++ monstermos

### PR DESCRIPTION
**Pull request by ike709**
Ports C++ monstermos, created by monster860.

TODO:

- [x] Fix walls not updating atmos when they're deleted
- [x] Investigate airlocks & firelocks seemingly not updating sometimes when opened
- [x] Fix the `Cannot read null.min_requirements` runtime
- [x] Port firelock code
- [x] Port cycling airlocks code
- [x] Test firelocks
- [x] Test cycling airlocks
- [x] Meta mapping changes
- [x] Delta mapping changes
- [x] Box mapping changes
- [x] Pubby mapping changes
- [x] Lavaland base mapping changes
- [x] Fix lavaland atmos (see _atmosphere.dm)
- [x] Proper CL

## Changelog
:cl:
add: Monstermos from yogs, which significantly improves atmos performance.
tweak: Firedoors are no longer full-tile. This means you can walk though a pair of firedoors without depressurizing a room.
tweak: Space wind is faster and deadlier.
tweak: Windows are significantly stronger, with most having 4x as much health.
tweak: Windows bordering space now have firelock windows to seal breaches.
tweak: You can automatically walk through a closed firedoor if doing so isn't likely to kill you.
tweak: Did I mention atmos is faster? It's way faster. Gas will quickly flood a room.
server: Improved linux support for extools. This means nothing for players, but might be useful for downstream server owners. Some of the code was created by SpaceManiac.
tweak: Air alarms will turn the lights blue in areas with hazardous atmos.
tweak: Lavaland atmos has a higher minimum pressure.
add: Cycling airlocks that don't suck. Ported from Yogs.
add: Players can now easily construct cycling airlocks.
tweak: To make repressurizing airlocks faster, the default distro pressure has been increased to 500 kPa. Atmos Techs can increase repressurization speed further.
tweak: Lavaland scrubbers will scrub BZ and other harmful gasses by default.
tweak: Mechs can open firelocks in some cases. Credit to MacHac at yogs.
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
https://github.com/yogstation13/Yogstation/pull/7510

This could be useful

**Comment by boodaliboo** [comment]
i truthfully do not recommend porting monstermos until you can remap your stations to compensate for it

**Comment by ike709** [comment]
> i truthfully do not recommend porting monstermos until you can remap your stations to compensate for it

image

🤔

**Comment by boodaliboo** [comment]
i dont read words

**Comment by Cenrus** [comment]
https://github.com/yogstation13/Yogstation/pull/7649
https://github.com/yogstation13/Yogstation/pull/8553

**Comment by ike709** [comment]
already got the first one

**Comment by ike709** [comment]
~~Issue: Meta escape still has old firelocks.~~

The actual issue is that they're using the fulltile assemblytype, which is presumably intended.

**Comment by ike709** [comment]
~~Issue: Blue lights aren't blue enough.~~

Forgot about Toggle Darkness. Lights are fine.

**Comment by ike709** [comment]
~~Issue: Dangerous firelock opening should be included on mob log too.~~

Fixed.

**Comment by ike709** [comment]
~~Issue: Gases seem to break and act funky in an area that an admin has used Stabilize Atmos on.~~

Fixed I think? Needs further testing.

**Comment by ike709** [comment]
~~Issue: border firelocks need an assemblytype subtype~~

Addressed. They don't have a unique sprite though.

**Comment by ike709** [comment]
~~Issue: A higher distro pressure is needed so airlocks can repressurize quickly. Remap atmosia to compensate.~~

Addressed. Distro pump now defaults to 500 kPa.

**Comment by ike709** [comment]
~~Issue: Lavaland scrubber needs to automatically scrub BZ and other harmful gasses.~~

Addressed.

**Comment by 4rchibald** [comment]
You said yesterday you needed a new gas for system to work properly so you created new unobtainable one. Is there any reason for not getting [hydrogen from TG](https://github.com/tgstation/tgstation/pull/50510)? That looks like fairly good PR and I haven't heard any complains about it

**Comment by ike709** [comment]
Effort, mostly. This PR is really bloated as-is @4rchibald

**Comment by 4rchibald** [comment]
@ike709 
Yeah, its a substantial PR and I'm impressed with your work. Just thought its worth bringing it up, don't know if hydrogen was considered and if so if there's a reason it was decided to omit it. 

Both PRs are in the same category, you actually needed a new gas and so far I haven't seen any problems or even community opposition to it, both on TG and while talking to people about it on OOC on our servers (if anything your PR seems to be more controversial so maybe adding new gas would actually make it more acceptable for people opposing it, sure as hell it would spark new interest in experimentation with gases. Also c'mon, we could have finally have a water cooled SM! Its not possible nowadays, not without constant supply of water vapor since its being used up to make chamber floor slippery)

I know its always this way, someone's working on PR and every single person has some ideas but I'm asking you to consider combining both PRs, take a look at it, ask others about their opinion etc
As you said, you have a major PR and that one is as complex, combining them would surely cause some issues and require extra work but they really seem to be compatible with each other, they go hand in hand and I believe introducing them both together would benefit our servers greatly

**Comment by ike709** [comment]
~~Issue: Stabilize Atmos still breaks fastmos where it's used.~~

Addressed.

**Comment by ike709** [comment]
~~Issue: Window firelocks need their own assemblytype too.~~

Addressed.

**Comment by ike709** [comment]
~~Issue: Syndicate lavaland turbine could probably be used to cook the entire zlevel.~~

Addressed but needs testing to ensure I didn't break the turbine.

**Comment by ike709** [comment]
~~Issue: Border firelock and window firelock assemblies need sprites.~~

~~I bugged spriters about it.~~

Fixed courtesy of Az.

**Review by qwertyquerty — APPROVED** [review]
I quick scrolled through, nothing seems glaringly out of place. If the testmerges went well, merge + forget

**Review by qwertyquerty — CHANGES_REQUESTED** [review]
I revoke my approval:

`## WARNING: Invalid research design with ID airalarm_electronics detected in node Industrial Engineering[engineering] removed. in code/controllers/subsystem/research.dm at line 181 src: Research usr: .`

Is a warning in CI. This seems to be related to your stuff. Look into it

**Pull request merged**
