### PR TITLE
better hallucinations

### PR DESCRIPTION
**Pull request by CthulhuOnIce**
https://i.imgur.com/dMDTntY.gifv

This happens when you get really high on hallucinogens, not when you take a puff or two of the old mariweedy

### CODE REVIEW

**Comment by CthulhuOnIce** [comment]
Oh yeah this is WIP

**Comment by qwertyquerty** [comment]
Too scary -2

**Comment by Superyodeler** [comment]
The issue I have with this is that most of the hallucinations are things that could actually happen. Making stuff flash on screen like this would rob the hallucinations of their paranoia factor, making higher levels of hallucinations arguably less effective but more annoying.
Adding a higher level that makes stuff happen sounds like a good idea to me, but I don't like the idea of a dead giveaway like this.
Also seizure warning.

**Comment by CthulhuOnIce** [comment]
yeah but like i said, it only happens when your hallucination var is very high (50 and above), there gets to a point where you know shit's fucky

**Comment by CthulhuOnIce** [comment]
fuck it, back to the drawing board

**Comment by ghost** [comment]
Considering I have done some much lsd I overdosed and still never seen one before yes you need better ones

**Pull request closed without merging**
