### PR TITLE
[PORT] Ports new station goal: Bluespace mining tap from Paradise station

### PR DESCRIPTION
**Pull request by Penwin0**
## About The Pull Request
ports https://github.com/ParadiseSS13/Paradise/pull/12062

What does this PR do:
This PR adds a new station goal into rotation, based on an old idea of mine. I've talked to Neca about it and he liked the idea.

Short Overview:
So, what is the Bluespace Mining Tap Harvester (renamed)? It is basically a device that reaches into other dimensions thanks to the power of bluespace, mining them for neat stuff. To do so, it requires a LOT of power. Not only that, the more power you supply, the more rewards it generates. This is intended to give engineering a reason to optimize power production, run multiple engines, etc.

In more details:
The Power Tap needs to be built on a wire knot, as an apc would not nearly have enough power to keep it supplied. It has 20 mining levels, each mining level requires an order of magnitude more power than the previous one. It is impossible to actually reach the highest level, as far as I can tell.

Depending on your mining level the tap accumulates points, which are spent on generating various benefits. The station goal is to accumulate a reasonably large amount of such points (though you can spend them, they only need to have been earned at some point)

After reworking the reward list, it now provides: Collectable hats, luxury food, as well as various mostly fluffy items with a very small chance for high-tier/rare loot.

At high enough mining levels, there is of course a chance for things to go wrong. What, you thought tapping other dimensions for power and resources was risk-free? The tap has a chance to spawn portals spawning further nasties at a high enough level, so better have sec on stand-by or keep it on a low setting. Emagging it significantly increases the chance of such malfunctions. The portals leave behind bluespace crystals when destroyed, as a small 'reward'.

I have removed the holoparasite reward and changed some of the rewards in general as some of them are not in our codebase
## Why It's Good For The Game
More variety in Station Goals, gives some value to energy and serves as a benefitial machine giving some incentive for the crew to build it past "it's the goal"

## Testing Photographs and Procedure

Tested it out in-game and it works, had to work out some things with tgui from the original PR but appears to be functioning fine.
<details>
<summary>Screenshots&Videos</summary>

Screenshot_1094

</details>

## Changelog
:cl: Penwin, TDSS
add: A new station goal, the bluespace tap. Feed it power for fantastical rewards!
/:cl:

### CODE REVIEW

**Comment by Penwin0** [comment]
God damnit linters

**Comment by AnCopper** [comment]
So basically, this is just the old BS miner but way harder to make and maintain?

**Comment by DerpiestBruh** [comment]
>So basically, this is just the old BS miner but way harder to make and maintain?

BS miner but awesome!

**Comment by FriendlyContractor** [comment]
**Glorified high-maintenance trash generator**. It does not add anything meaningfull to the game with its current loot tables and im very strongly against adding it to the game. Reading the title i thought it would generate uselfull materials for the station but instead it spews out hot garbage in form of collectible hats and mildly exotic food.

My suggestion would be to either simply make it generate ores in simmiliar fashion to old bluespace miners or completly revamp the loot tables to make it actually provide uselfull items players will feel rewarded with for their efforts. Collectible vanity items are **NOT** the loot players want to get for their efforts

**Comment by Penwin0** [comment]
Yeah the tooltable Is kept from Paradise, I do infact find it underwhelming as well and am open for suggestions on that end

**Comment by FriendlyContractor** [comment]
Some stuff i think could work as rewards

1. **Ores**. Nobody is going to complain about more materials even if its not something unique
2. **Abductor stuff** - Engineering and surgical tools (i think would be best if they came in sets rather than getting random tools even if expensive but maybe its just my OCD). Their unique chemical dispenser. Some of the beneficial experimental glands. Their gun(already obtainable via exploration and it did not ruin the game so why not, its fun) Maybe we could even add some new abductor themed items unique to this machine ?
3. **Anomalies** - anomaly cores, strange items, exploration artifacts
4. **Magical/Fantasy/Mysthical Items** - Im thinking items from mining such as wand of asclepicus or memento mori. Could include other appropriately themed items such as karate and maybe some spell scrolls(would require coding in spells that do something else than wreck havoc)

**Comment by Fronsis** [comment]
Eh, tbh FriendlyContractor most station goals/objectives usually gets done (or they don't get done at all) very late into the shift so having gimmicky funny items is fun, since by that point any relevant Ores wouldn't help much since if it's done late game it's most likely that miners did their job, i think it needs to be a mix of what it's already on the loot table and what you suggest

**Comment by williamcll** [comment]
Yes, a reason to build fusion TEGs.

**Comment by ItsTisme** [comment]
TBH as an bored engineer id be willing to setup autistic engines to get drip to flex with. But prop should be exclusive stuff

**Comment by Rukofamicom** [comment]
Sprite looks... out of place. 
Aside from that sounds neat.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
