### PR TITLE
Make Medbay Great Again - Replaces roundstart sleepers with stasis beds. Sleepers can still be built as normal

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
Note: the [Tend Wounds buffs PR](https://github.com/BeeStation/BeeStation-Hornet/pull/1294) is a pre-requisite for this change. 

Now doctors actually have a job other than clicking one button on a sleeper, hooray!

## Why It's Good For The Game
Current state of Medbay is that although Tend Wounds surgery is actually viable now (and even moreso once the TW buff is merged), no-one is gonna use it when there are sleepers already available, no matter how much TW is buffed. Sleepers are just too powerful and familiar to go for the alternative, and there's no downsides to them. 

This doesn't remove sleepers from the game, it just means that they need to be built first. So there will at least be a small period of time where doctors can actually do their job of healing. And their 2-step TW surgery can be enhanced through using medikits and other chems if there's a lot of patients (and if further research points are allocated to it to get the better versions).

Furthermore note that before making this PR I've made changes to ease this transition including:
- Giving Chemistry roundstart plumbing equipment so they can make fucktons of meds from roundstart
- Buffing Tend Wounds including making it only two steps
- Defib/organ decay rework which makes it far easier to revive dead bodies if they don't get healed out of crit quickly enough

This is completely different to when tg removed sleepers since we still have sleepers buildable, we have plumbing to mass-produce chems, and we have tend wounds surgery. They also made cobbychem at the same time which made medbay pretty damn difficult at the time having all the unbalanced changes at once. This change simply cannot be made even easier now. 
## Changelog
:cl:
add: Replaced all roundstart sleepers with Lifeform Stasis Units.
/:cl:

Ports:
https://github.com/tgstation/tgstation/pull/43075
https://github.com/tgstation/tgstation/pull/44665

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
No offense, but what reagent are you smoking and where can I get some?

**Comment by VictorVow** [comment]
Imagine thinking sleepers is interesting gameplay

**Comment by derpymcfuckwit** [comment]
what if i slapped your nuts and called you gay for making this

**Comment by Cenrus** [comment]
Medbay is boring as hell and doctors don't have many reasons to exist. I would like a little more difficulty.

**Comment by Oshibkka** [comment]
/obj/machinery/sleeper/Initialize()
/obj/machinery/sleeper/Initialize(mapload)
    . = ..()
    if(mapload)
        component_parts -= circuit
        QDEL_NULL(circuit)
YOU AINT SLICK NIGGA

**Comment by VictorVow** [comment]
@derpymcfuckwit pretty gay you wanna touch my balls
@Cenrus my thoughts exactly
@Oshibkka part of the original ported PRs, just means you can't steal _syndie_ sleeper boards

**Comment by derpymcfuckwit** [comment]
> @derpymcfuckwit pretty gay you wanna touch my balls
scared of cock and ball torture?

**Comment by 4rchibald** [comment]
@Victor239 I can see where you are coming from but we need to keep in mind that many in our medical staff are incompetent, its not uncommon to be treated with improper meds, its not uncommon to get them to the point that you OD, its not uncommon for dead body to be brought straight to morgue (especially plasmaman, many people don't know how to handle them). Since synthflesh is required for cloning you can often see piles of bodies that won't be ever cloned because no one knows how to make it.
Not to mention that any kind of surgery is really not an option for plasmaman, gotta be realistic that noone will build operating room with inert atmosphere during 40-80 minute round.

I really got mixed feelings about this PR
I see why that could be a great thing once we have competent doctors but is it even possible?
We swapped sleepers for stasis beds few months ago and it didn't work out, can't tell if with current changes it will be any different. 
Maybe instead of 'shock therapy' we could try implement that in 2 stages and first leave one sleeper with one or two stasis beds next to it. Also how hard would it be to make sleepers require power cell just like chem dispensers, that could be another obstacle that would encourage people to slowly try out surgery. Once we'll see how people adjust to that we would remove roundstart sleepers completely

**Comment by VictorVow** [comment]
@4rchibald doctors are never gonna get competent if all they have to do is the 1-click sleeper routine and honestly I've very rarely seen wrong meds/overdoses given from sleeper meds. Dead bodies being morgued should be reduced by my other defib/organ rework PR. 

Hmm having one sleeper and one stasis bed might be a better transition. I think power cells are still too powerful for chems which take a good few mins to make and apply otherwise but I'll consider it.

**Pull request closed without merging**
