### PR TITLE
Stage Magician gets their own name

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
Magician gets their own name

## Why It's Good For The Game
Magician's comedian fellows have their own names already. why not Stage Magician?
Their naming policy follows the way of Magician - something like "Alexander The Magnificent", not wizard's way.
This needs to update the naming policy at the wiki however.

Note:
Magician.txt contains only titles and you get a random name as "[human name] [magician title(from magican.txt file)]"
also I am not sure how it would work to appearance-ban accounts since I can't test it on my own server.

## Changelog
:cl:
tweak: Stage Magicians can have their own name now. Their naming policy follows to be 'magician-like', not 'wizard-like', so don't pick names like Gandalf the Necromancer.
/:cl:

### CODE REVIEW

**Comment by DatBoiTim** [comment]
Should definitely be more flexible than FirstName the Adjective format, allowing for styles other real world magician/other performers have used such as The Adjective Name (ex: The Great Houdini).

**Comment by EvilDragonfiend** [comment]
> Should definitely be more flexible than FirstName the Adjective format, allowing for styles other real world magician/other performers have used such as The Adjective Name (ex: The Great Houdini).

the current version is just giving a name to them, not putting a title to their real name. so the way you want is possible by setting 'their name' as to how you'd like to do. (Alex The Great, The Great Alex, whatever.)

**Comment by DatBoiTim** [comment]
> > Should definitely be more flexible than FirstName the Adjective format, allowing for styles other real world magician/other performers have used such as The Adjective Name (ex: The Great Houdini).
> 
> the current version is just giving a name to them, not putting a title to their real name. so the way you want is possible by setting 'their name' as to how you'd like to do. (Alex The Great, The Great Alex, whatever.)

I was referring policy wise.

**Comment by EvilDragonfiend** [comment]
> > > Should definitely be more flexible than FirstName the Adjective format, allowing for styles other real world magician/other performers have used such as The Adjective Name (ex: The Great Houdini).
> > 
> > 
> > the current version is just giving a name to them, not putting a title to their real name. so the way you want is possible by setting 'their name' as to how you'd like to do. (Alex The Great, The Great Alex, whatever.)
> 
> I was referring policy wise.

ooh, gotcha

**Comment by EvilDragonfiend** [comment]
This is more randomie upon the character creation. I am not sure how it would work to appearance-ban accounts since I can't test it on my own server.

**Comment by ike709** [comment]
🔑

**Comment by Archanial** [comment]
🔑

**Pull request closed without merging**
