### PR TITLE
Makes advanced circuit boards cost Fluorosulfuric acid to be printed.

### PR DESCRIPTION
**Pull request by CydiaLamiales**
## About The Pull Request
Makes certan circuit boards require 5u of Fluorosulfuric Acid to print.
Makes the H.O.N.K. mech boards require both Fluorosulfuric Acid and Laughter to print.
Also adds a new cargo packs under the Science category, which has two 50u bottles of Fluorosulfuric Acid.
<details>
<summary>List of Advanced boards</summary>
AI Core
Security Camera console
AI Upload console
Cyborg Upload console
Communications console
ID console
Robotics Control console
Exosuit Control console
Telecommunications Monitoring console
Telecommunications Sever Monitoring console
AI Integrity Restorer console
APC Control console
Advanced Camera console
Teleportation Station 
Teleportation Hub
Quantum Pad
Bluespace Launchpad
Bluespace Launchpad Console
Teleporter Console
Protolathe
Circuit Imprinter
Gygax modules
Durand modules
H.O.N.K. modules (also require Laughter)
Phazon modules
</details>

## Why It's Good For The Game
It promotes cross-department interactions and gives Chemistry more stuff to make for departments that aren't Medbay. As it is right now, they only really make Plastic for Engineering and sometimes Science, Colorful Reagent for Botany and some drink ingredients for the Bartender.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image

image

image

image

</details>

## Changelog
:cl:
add: Added a cargo pack in the Science category, containing two 50 unit bottles of Fluorosulfuric Acid
tweak: Made some circuit boards require 5 units of Fluorosulfuric Acid to print
tweak: Made the H.O.N.K. mech boards require 5 units of Fluorosulfuric Acid and 5 units of Laughter to print
/:cl:

### CODE REVIEW

**Comment by CydiaLamiales** [comment]
Main current concern are lowpop rounds where there are no medical personnel available.
Perhaps a ghetto way of acquiring sulphuric acid could be added?

**Comment by Tsar-Salat** [comment]
> Perhaps a ghetto way of acquiring sulphuric acid could be added?

Blend all of techstorages circuits

:trollface:

**Comment by pricklytomato** [comment]
A concern I have is how this will impact the golem shuttle ghost role. Though I think that could be solved by adding a chem dispenser board to the box of circuits that golems get through their vender

**Comment by qwertyquerty** [comment]
:key: name one time shoving department interactions down players throats has ever improved gameplay

**Comment by PowerfulBacon** [comment]
I think this could work well if the dependency wasn't forced on the low tier boards and wasn't super expensive. I also think that it should be 1 chemical type per print rather than 3, for the advanced boards it should just be a chemical that is more difficult to make.

**Comment by PestoVerde322** [comment]
> I think this could work well if the dependency wasn't forced on the low tier boards and wasn't super expensive. I also think that it should be 1 chemical type per print rather than 3, for the advanced boards it should just be a chemical that is more difficult to make.

Seconding this, Low tier board should not need really chemicals, on the other hand, more complex stuff might need it.

**Comment by CydiaLamiales** [comment]
> > I think this could work well if the dependency wasn't forced on the low tier boards and wasn't super expensive. I also think that it should be 1 chemical type per print rather than 3, for the advanced boards it should just be a chemical that is more difficult to make.

There, I changed it to have only advanced boards require 5u of Fluorosulfuric Acid each
> Seconding this, Low tier board should not need really chemicals, on the other hand, more complex stuff might need it.

Removed the chem requirement from basic boards
> However, what's gonna be the cost for Chem Masters boards? As in, if all Chem Master are gone, what's the cost for them? Do they use basic materials or if you don't have access to chemicals you're screwed? if that's the case, is there a way to order a backup trough cargo?

Actually, I didn't make the Chem Masters cost acid. Should I?
And yes, cargo does get a crate with some acid inside.

**Comment by PowerfulBacon** [comment]
The problem I see with this is:
- There is no basic/ineffective way to do it without going through chem
- There is no difference in the type of chems needed and no different effect they have.
I fear this would become a tedious interaction like botany/chem without the 2 things above.

**Comment by Tsar-Salat** [comment]
> * There is no basic/ineffective way to do it without going through chem

Make tech storage actually useful?

I barely see it used outside of raiding it for insuls, it could be a place where you can salvage the flurosulf from

**Comment by PowerfulBacon** [comment]
Hm this would be much easier without the mapping edits, since it makes instant revert impossible

**Comment by CydiaLamiales** [comment]
Well I've removed all the mapping edits, but the Metastation file still stuck around for some reason, I've even tried replacing it with the latest version from the master branch.

**Comment by CydiaLamiales** [comment]
Meh, I'll work on this later when I'll get better ideas.

**Pull request closed without merging**
