### PR TITLE
Repipes Kilo to be less cancer.

### PR DESCRIPTION
**Pull request by SergeiKoralev**
## About The Pull Request

This PR is another standardization that puts scrubbers on layer 3, distro on layer 1, and does its best to remove any wall pipes that aren't otherwise required. 

## Why It's Good For The Game

Standards are good to have.

## Testing Photographs and Procedure

Testing included mapping debug pipe check, cycle checks, and checks to ensure that scrubbers and distro aren't crossed anywhere.

https://cdn.discordapp.com/attachments/590714573611597824/949528505119559690/kilopipe.png

## Changelog
:cl:
refactor: Kilo pipes are standardized. Distro on layer 1, Scrubbers on layer 3.
add: Kilo: The airlock in the engine room now serves as a non-public passage between atmos and the rest of engineering. 
tweak: A few Kilo airlocks are now larger, so things may be dragged through them.
/:cl:

### CODE REVIEW

**Comment by SergeiKoralev** [comment]
OH COME ON! Map merge conflicts are cancer.

**Comment by SergeiKoralev** [comment]
Cool, figured out how to do it.

**Comment by Chessus** [comment]
Good to see the Port bow solar air pipe has been fixed with this update

**Comment by 4rchibald** [comment]
@Vasily2013 @Archanial 
Sadly this PR killed important feature of Kilo piping, probably the only positive that came out of Kilo maintenance. Across maints there are small rooms named Atmospherics Connector, inside them is a set of 2 pumps-Distro to Connector and Connector to name of department they are connected to. 
It not only added a lot of character to Kilo and differentiated it from rest of stations but it actually had practical use, you could limit access of ventcrawling creatures, you could limit damage of flooding by contaminating disstro, set up a filtering station or quite opposite, use it to selectively flood a department which actually could be used to bring back some of atmos cunning back to game
Now not only the pumps have no names but they are completely useless since they are bypassed right away by pipe laying outside Connector room
Just yesterday we had nasty xeno infestation, I tried to limit their ability to spread by disconnecting some departments from distro only to find out it didn't do anything

kilopipes

This is how the same spot used to look

kilopipesoriginal

**Comment by SergeiKoralev** [comment]
It's possible to reintegrate that as a feature, but I was under the impression they were more intended to be a small area to serve as an air reserve for if distro pressure got to low. I can look at altering the pipes around these areas to properly isolate sections of the station better. It won't be as it was, but there will be shutoff valves.

**Comment by SergeiKoralev** [comment]
I've added shutoff valves around the station. They'll likely be less convenient than the prior junctions, but they are there for those knowledgeable in the way of atmospherics.

**Review by Archanial — APPROVED** [review]

**Pull request merged**
