### PR TITLE
Nerfs sawn off shotgun

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

increases the spread of sawn off shotguns by 60%.

Sawn off shotguns have all the advantages of a shotgun + the ability to put it in a bag essentially making it so you can't if someone has a shotgun on them until they suddenly pull it out of nowhere.

Currently, there is no downside to sawing off a shotgun.

## Why It's Good For The Game

Adds in a downside to sawnoff shotguns, making them not just a normal shotgun that you can hide.

## Changelog
:cl:
balance: Sawn off shotguns have increased spread
/:cl:

### CODE REVIEW

**Comment by Penwin0** [comment]
Sawed off shotguns have no inhand sprite, fun

**Comment by Rukofamicom** [comment]
Is this +60% over what they had or over the new shotgun spread?

**Comment by Vexylius** [comment]
There is a downside, and that is your screen shakes a lot when you shoot

**Comment by PowerfulBacon** [comment]
> 
> 
> There is a downside, and that is your screen shakes a lot when you shoot

the screenshake is the same as normal shotguns (not like screen shake on a semi-auto weapon matters)

**Comment by PowerfulBacon** [comment]
> 
> 
> Is this +60% over what they had or over the new shotgun spread?

60% over whatever it is at the time in code, if the spread gets decreased it will still be 60% more, if it gets increased it will be 60% more of the new value

**Comment by nikk735** [comment]
the downside is that the accuracy goes down, you shoot sideways sometimes and its annoying as hell. especially with slugs

**Comment by PowerfulBacon** [comment]
> the downside is that the accuracy goes down, you shoot sideways sometimes and its annoying as hell. especially with slugs

That doesnt affect shells
This PR will affect shells.
Slugs are not affected and already reduced in accuracy

**Review by qwertyquerty — APPROVED** [review]

**Comment by ike709** [comment]
For posterity: 

image

**Pull request merged**
