### PR TITLE
Labor Camp Supervisor

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Adds a new security department; Labor Camp. The purpose of this officer is to process prisoners on station, and supervise (bully) prisoners and prevent escape on lavaland labor camp. This officer will travel to gulag via shuttle more often and should even stay there if there are prisoners there and will meet his demise by getting robusted and thrown into lava by escaping traitors.

Adds the labor access and labor dept spawn positions on Meta, Box, Delta and Pubby.

## Why It's Good For The Game

Incentivizes people to use gulag more, and takes some of the burden from the warden who has to manage the station, instead of supervising lavaland. 

## Changelog
:cl:
add: Added new security department; Labor Camp.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
most of the time they are going to be sitting there doing nothing. Its not a particularly interesting or useful job role sitting in the gulag for an hour while 80% of the time nobody is there. Also this is the warden's job, so this role is just a warden but instead of being on a station is on an uninhabited station.

**Comment by eeSPee** [comment]
They are also officers, and can do the regular officer's job when there is nothing to supervise on lavaland.

Initially I had the idea to make it a standalone job but I refrained because of the issues you highlighted.

**Comment by Archanial** [comment]
It's not interesting nor is it needed

**Comment by utilbird** [comment]
> They are also officers, and can do the regular officer's job when there is nothing to supervise on lavaland.

Neat but, what's the point of a separate department if they're functionally identical to a security officer. What's stopping security from monitoring gulag, new roles aren't really needed for tasks this specific imo

**Comment by eeSPee** [comment]
But it's not a separate job/thing, it's just a sec officer with gulag access.

**Comment by utilbird** [comment]
in that case, just give sec officers gulag access

**Comment by eeSPee** [comment]
They kinda already do; they just can't use the machine.

This guy can use the machine.

**Comment by sircope** [comment]
give them shotguns with buckshot and explosive collars and i'm sold

**Comment by ike709** [comment]
🔑

**Comment by eeSPee** [comment]
Not enough likes to merge, not enough dislikes to speedmerge :C

**Pull request closed without merging**
