### PR TITLE
Better signal logging

### LINKED ISSUE #2357: Signalers do not log persistently
$ grep -i "lastsignalers" -r
code/game/objects/items/devices/PDA/radio.dm:   GLOB.lastsignalers.Add("[time] <B>:</B> [usr.key] used [src] @ location [AREACOORD(T)] <B>:</B> [format_frequency(frequency)]/[code]")
code/modules/admin/secrets.dm:                  list("Show last [length(GLOB.lastsignalers)] signalers", "list_signalers"),
code/modules/admin/secrets.dm:                  var/dat = "<B>Showing last [length(GLOB.lastsignalers)] signalers.</B><HR>"
code/modules/admin/secrets.dm:                  for(var/sig in GLOB.lastsignalers)
code/modules/admin/secrets.dm:                  usr << browse(dat, "window=lastsignalers;size=800x500")
code/modules/assembly/signaler.dm:              GLOB.lastsignalers.Add("[time] <B>:</B> [usr.key] used [src] @ location ([T.x],[T.y],[T.z]) <B>:</B> [format_frequency(frequency)]/[code]")
code/_globalvars/logging.dm:GLOBAL_LIST_EMPTY(lastsignalers)    //! keeps last 100 signals here in format: "[src] used [REF(src)] @ location [src.loc]: [freq]/[code]"
code/_globalvars/logging.dm:GLOBAL_PROTECT(lastsignalers)

Signalers don't log to disk, which makes investigating hard.

### PR DESCRIPTION
**Pull request by PowerfulBacon**
fixes #2357

## About The Pull Request

Signallers now log to files, as well as the secrets signal list.

## Why It's Good For The Game

'Signalers don't log to disk, which makes investigating hard.'

## Testing Photographs and Procedure

image

I've sinced removed the \<B> tags from the log and the timestamp (They are redundant, and the timestamp is in the wrong timezone)

## Changelog
:cl:
admin: Signallers now log to the disk.
/:cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
I wonder if this would be better in its own log file or not... That way we could also tie it into one of the investigation options in-game for admins as well.

**Comment by PowerfulBacon** [comment]
Up to you

**Comment by Crossedfall** [comment]
On one hand, it would be better in terms of log organization and integrations. On the other hand, it removes the immediate context from the logs if you're viewing them raw. Hmmm. 

I'll think on it some more and get some quick feedback from some of the admins. I'm leaning towards having it split off and then adding a new entry into the investigate verb for signals. I feel like that'd be helpful for in-round investigations.

**Review by Crossedfall — CHANGES_REQUESTED** [review]
After getting some added feedback, the consensus is that it'd be better in its own file and for there to be an added option in the `Investigate` verb for signals.

**Comment by PowerfulBacon** [comment]
I won't be continuing work on this PR. Feel free to take over

**Comment by ivanmixo** [comment]
I kind did this in my maxcap PR

**Pull request closed without merging**
