### PR TITLE
Adds two new station traits concerning silicons. Roundstart AI is now a positive trait.

### PR DESCRIPTION
**Pull request by St0rmC4st3r**
## About The Pull Request

Adds two new positive traits for the station:

- Experimental AI (roundstart AI)
- Additional roundstart borgs (3 instead of 1)

The AI is no longer a default roundstart omniscient entity.
Borgs can latejoin again.

## Why It's Good For The Game

I will divide this section into two parts: borgs and AIs.

**Borgs**
Some borg players said they would like to be a part of a borg team from the start and solve the dilemma when several departments need a borg. While increasing the default number of borgs would be a problem, the trait system provides some inconsistency for it to be a fun changer for a round.

**AIs**
This is a whole another can of worms. We all constantly rely on the AI. It opens doors for us, calls the shuttle for us, tracks our vitals (when we don't forget to max our sensors) and it is a priceless tool when chasing down criminals, _very few of whom can evade_ an **omniscient** highly protected creature locked away under three locks and seven chains.... Oh, wow. Good game design. Especially after #6795 was merged. Now to subvert this omniscient being as an antag, you need to either go really loud or murder one of 3 people who could get upload codes, and only after that can you access the upload itself, that nobody wants anyone to enter.
I am not even talking about what a single assistant with a bag full of analyzers can do to an AI camera network. You will never hide from it after that. Not unless you are a traitor with an agent card or a changeling.
The guaranteed omniscient and omnipresent AI makes SS13 less of a murder mystery and more of a Hollywood action movie.
Besides, the station has all the resources to build an AI should they really need one.
To compensate for the lack of your favorite doorknob, the station will get one guaranteed borg whether roundstart or latejoined. A player that needs to actually come over to open a door also improves interaction with the personnel, with whom you will need to negotiate/come up with an excuse instead of Law 2ing.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
Default state of the AI sat.

image

AI getting appointed roundstart when the trait is present - successful.
AI latejoining when the trait is present - successful.
AI cores absent when trait is not present - successful.
Unable to start round as AI when trait is not present - successful.
Multiple cyborgs available for latejoin when trait is present  - successful.

</details>

## Changelog
:cl:
add: Added a positive trait that increases the number of possible roundstart cyborgs.
add: Added a positive trait that enables a roundstart AI.
del: Roundstart AI is no longer a default feature.
tweak: Cyborgs can latejoin again.
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
bad change ruins my life as AI main and makes me very sad 👎

**Comment by EvilDragonfiend** [comment]
> bad change ruins my life as AI main and makes me very sad 👎

When an corporate law AI refuses to corporate with another AI :trollface:

**Comment by Dejaku51** [comment]
how about no

**Comment by ivanmixo** [comment]
Very good, but will unfortunately never go through because the players whose favorite role is AI won't ever realise how bad it is for the game.

**Comment by PowerfulBacon** [comment]
As much as the AI is the biggest fun killing role in the game and often ruins rounds by immediately outingnthe threat before any gameplay can develop, I highly doubt this will get in.

**Comment by TeomanTheGreat** [comment]
This pr doesnt stop ais from existing at all since RD can just make one so im not sure why people are complaining.

**Comment by St0rmC4st3r** [comment]
> As much as the AI is the biggest fun killing role in the game and often ruins rounds by immediately outingnthe threat before any gameplay can develop, I highly doubt this will get in.

I can up the weight to 10 if you think that 5 is too rare.

**Comment by Isy232** [comment]
As Teoman says, the RD starts with all of the things to make a roundstart AI in his office. AI players will merely be inconvenienced by 5 minutes.

This also leaves the now empty AI satellite as a large but useless part of the station.

I think this PR needs more changes if it's to even be considered, I'm completely fine with removing the roundstart AI, AI satellite, and AI resources from roundstart. However changes need to be made to compensate, such as the gravity generator APC being unaffected by power blackouts, probably some others I havent thought about.

I also think Bacon's more moderate approach of merely nerfing the AI's anti-antag abilities will mostly solve this problem.

**Comment by PowerfulBacon** [comment]
It delays the all powerful being from being created, however it will still get created after 10-15 minutes and then the problems will continue from there. Also removes malf AI from the game.

**Comment by itsmeow** [comment]
Technically midround malf on dynamic with an ion event is still possible, but rarer than it already is (extremely rare)

**Comment by FortSumter** [comment]
It may come as a surprise but I like this one. Instead of knee capping the AIs ability to function, let's just not have one at round start. This would make some traitor objectives easier while not getting rid of the role entirely. We could also use the AI sat for something else and put the AI in the upload or something.

What the AI really needs is a major rework. I plan on making a list of things I'd like to see as an AI player and see what other people on the forum think about it.

**Comment by St0rmC4st3r** [comment]
> It delays the all powerful being from being created, however it will still get created after 10-15 minutes and then the problems will continue from there. Also removes malf AI from the game.

No, it doesn't, just makes it quite rare. Maybe I could crank the malf chance up, since it is an "experimental" AI?

**Comment by FortSumter** [comment]
You can't do that either because the crew will start being paranoid and meta game when an AI exists round start. You'd also have to hide law 0 on the intellicard and add a blurb somewhere saying borgs shouldn't snitch on their AI if their brain gets removed from their body. If you want to do that then fine, but that's a lot of work.

**Comment by FortSumter** [comment]
We already don't see malf AI that often and quite frankly it's busted. Malf is limited by what the crew does or does not do, and once its found out it can be relatively easy to deal with if you know how. The AIs round could also be ruined by an overly enthusiastic Borg who tries to go on a killing spree simply because it has law 0.

**Comment by llol111** [comment]
AI is an important part of the game. If there is someone willing to play it, it should be present.
Having it roundstart ensures evryone gets an equal shot as with all other jobs, instead of who can convince the roboticist the fastest. (ingoring why their character would choose to be come an enslaved metal box in the first place)

**Comment by Nosnek199** [comment]
Like llol111 had said, having a roundstart AI always gives everyone who wants to play AI a fair chance. Please don't make a round-start AI rare.

**Comment by FortSumter** [comment]
I'm almost of the opinion AI should be whitelisted considering how people abuse the role. Sometimes I strongly consider killing the AI myself as non human command because the asimov AI devides to be antagonistic.

**Comment by Megaddd** [comment]
Replace trait type with negative and this has a mild chance in hell of passing.

**Comment by Rukofamicom** [comment]
> If there is someone willing to play it, it should be present.

Then why don't we have Nukies, Golems and Ashwalkers as 100% spawns at the start of every round? These certainly are fun and bring a great dynamic to the game in their own way.

**Comment by FortSumter** [comment]
Imo as an AI player I'd just like to see the AI just removed completely. While it's a fun role, it's not necessary for one to exist and actually causes more problems than most any other role on the station.

The pros to removing it would greatly outweigh the cons and make the rounds more interesting. It would also end the eternal debate on how to balance it without making the AI unfun or useless. 

We can even replace the role with "beebot" an NPC AI that sits in the sat for stealing purposes and says things automatically like the AI does in CSM.

**Comment by zeskorion** [comment]
remove silicons entirely tbh, they're more trouble than they're worth

**Comment by FortSumter** [comment]
No no, cyborgs are manageable more or less. It's the AI that poses major balancing problems. Cyborgs are fun to interact with occasionally and if we didn't have an AI we'd have to have someone who's be able to enable our hijinks.

I had an interesting idea of having a cyborg dock similar to the recharger that would allow a cyborg to act as an AI so long as its docked. That way any Borg could "be" the AI or take turns while also being able to be mobile.

**Comment by ivanmixo** [comment]
That would literally change nothing except you now have multiple AIs

**Comment by FortSumter** [comment]
Things would change significantly. For one, subverting the "ai" would simply require accessing a borg as it runs around. Dealing with a subverted "ai" would be much simpler, and this would allow the "ai" player the ability to personally solve problems across the station rather than relying on the crew or other borgs that refuse to obey you. We'd also be able to do a malf borg antag instead of AI which we'd be able to start talking about implementing once the AIs gone.

**Comment by St0rmC4st3r** [comment]
This goes nowhere. I hoped people would suggest actual changes I could implement, but it is just sitting here, collecting dust.

**Comment by Rukofamicom** [comment]
The server just got some new trial maintainers to help keep things moving. Might be worth asking one of them.

Things definitely aren't going to move fast anytime soon though.

**Comment by Coding-Grape** [comment]
I personally think that AI in its current state is a problem 

If there's nothing going on, you can do nothing but be a doorknob unless the crew triesto actually RP with you

But if there's shit going down, it's sensory overload of trying to micromanage your shell, doorknobbing, tracking people because sec can't do it themselves, and checking on your core from time to time to avoid fucking dying to some idiot with some EMP grenades and a few beakers or thermite

**Comment by itsmeow** [comment]
> I personally think that AI in its current state is a problem 
> 
> If there's nothing going on, you can do nothing but be a doorknob unless the crew triesto actually RP with you
> 
> But if there's shit going down, it's sensory overload of trying to micromanage your shell, doorknobbing, tracking people because sec can't do it themselves, and checking on your core from time to time to avoid fucking dying to some idiot with some EMP grenades and a few beakers or thermite 

This is exactly why I enjoy playing AI. The suffering is fun.

**Comment by Megaddd** [comment]
> This goes nowhere. I hoped people would suggest actual changes I could implement, but it is just sitting here, collecting dust.

@St0rmC4st3r then you missed an actual unironic change suggested

> Replace trait type with negative (station has no AI) and this has a mild chance in hell of passing.
> 
> Otherwise you're removing AI from any round that isn't in EU waking hours full stop.

**Pull request closed without merging**
