### PR TITLE
Patron popcap bypass + overflow redirecting

### PR DESCRIPTION
**Pull request by ike709**
## Changelog
:cl:
add: Patrons can bypass the popcap.
add: Players can be redirected to another server if the popcap is reached.
/:cl:

### CODE REVIEW

**Review by Crossedfall — APPROVED** [review]
Hard and extreme restrictions both seem to be correctly bypassed. Should be good to go.

**Comment by MCterra10** [comment]
wait so you need to manually update a patrons.txt file? bruh. I saw this and thought you did some cool shit with the Patreon API

**Comment by ike709** [comment]
@MCterra10 qwerty has a python script to update it, which runs every hour. Ask him about it on discord

**Comment by MCterra10** [comment]
Interesting. No way to incorporate it into the actual codebase itself?
Also I'm personally not worried about it, because austation doesn't have a patreon, I'm just curious

**Pull request merged**
