### PR TITLE
Revert "Changes felinid say verb to "meows""

### PR DESCRIPTION
**Pull request by Archanial**
Reverts BeeStation/BeeStation-Hornet#3862

😳 

https://discord.com/channels/427337870844362753/586312879200927767/822606281029189642

🆑
tweak: felinids no longer meow. 
/🆑

### CODE REVIEW

**Comment by Naevii** [comment]
This was actually cool and minor change. Why would you need to revert that even

**Comment by Archanial** [comment]
Because I don't like it
They don't meow, they speak.

**Comment by park66665** [comment]
A kind reminder that #3862 has been merged only about 4 days ago and therefore now is not an appropriate time for a revert. Unless there is a widespread support for it, this PR shall be marked DNM until the end of the March.

**Comment by PowerfulBacon** [comment]
😢

**Comment by utilbird** [comment]
Race change and maintainer approval was not included in the PR description.

Also this was a good change, a felinid without a tail and ears or just cover clothing was a non-human that could not be told apart from a human.

**Pull request closed without merging**
