### PR TITLE
Adds Pepper Sprays to Box Brig and Adds a Shortcut for Atmospherics

### LINKED ISSUE #11056: Boxstation has no pepperspray fillers accessible to security in brig
There should be pepperspray fillers in brig.

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
Check change logs for a detailed list of changes.

Fixes #11056.

## Why It's Good For The Game
Officers can refill their pepper spray in more than two places in the Brig.

Atmospherics Technicians don't need to go on an adventure for 10 hours (~20 seconds) to get to the burn chamber, quality of life change.

i ded change: Added paper bins (where appropriate) so I and others don't have to run around all over the place to find one.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: Markus Larsson
add: [Box] Added a bunch of pepper spray dispensers to the Brig.
add: [Box] Added a shortcut for Atmospherics to get to the burn chamber easier.
add: [Box} Added a ton of paper bins all over the station.
tweak: [Box] Minor decal tweak.
tweak: [Box] Added window to Construction.
tweak: [Box] Rerouted Mix to Engine pipe for Atmospherics.
fix: Fixed insuls not properly spawning in Engineering lockers.
/:cl:

### CODE REVIEW

**Review by spockye — CHANGES_REQUESTED** [review]
image

stacked disposal pipes

couldnt find anything else missing, seems good once you fix that!

**Comment by spockye** [comment]
image
one small thing. not a fan of the carpet continuing after the hazard lining. mabye use another floortile there?

**Review by spockye — APPROVED** [review]
looks good to me!

**Comment by PestoVerde322** [comment]
The 4 way airlock is all set to have access only for atmos, maybe consider to make the one to atmos the only one with atmos access and the other 3 with generic engineering access.

**Comment by MarkusLarsson421** [comment]
> The 4 way airlock is all set to have access only for atmos, maybe consider to make the one to atmos the only one with atmos access and the other 3 with generic engineering access.

Left the one to the left atmospherics access and set the other three to external airlock access.

**Review by PestoVerde322 — APPROVED** [review]

**Pull request merged**
