### PR TITLE
makes advanced health analyzers work like surgical processors

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

uses code from:
yogstation13/Yogstation#11571
ya gotta hold it on your other hand to be able to begin the surgeries tho

## Why It's Good For The Game

adds some use to adv health analyzers
the ability to do life-saving surgeries where there isn't any operating computer sure is helpful.

## Changelog
:cl:
add: advanced health analyzers now work like surgical processors
/:cl:

### CODE REVIEW

**Comment by ItsTisme** [comment]
I do like this for the sole reason it makes field surgery for wound tending(defaults painfully slow)

**Comment by Sapfearon** [comment]
Can we finally merge this? This is such a quality of life change..

**Comment by ghost** [comment]
Not sure if the fix for [that PR I made](https://github.com/yogstation13/Yogstation/pull/11571) will work here, [but it may be worth checking.](https://github.com/yogstation13/Yogstation/pull/11603)

**Comment by Bibby0110** [comment]
> Not sure if the fix for [that PR I made](https://github.com/yogstation13/Yogstation/pull/11571) will work here, [but here it is.](https://github.com/yogstation13/Yogstation/pull/11603)

It won't, they've already accounted for it in this PR 🤗

**Comment by nmajask** [comment]
yoggers

**Comment by Archanial** [comment]
:key:

**Review by utilbird — APPROVED** [review]

**Review by ike709 — CHANGES_REQUESTED** [review]
I don't mind the idea of some surgeries, but currently this just makes operating computers irrelevant and removes the need to go to medbay for quality surgeries.

**Comment by jupyterkat** [comment]
> I don't mind the idea of some surgeries, but currently this just makes operating computers irrelevant and removes the need to go to medbay for quality surgeries.

you can just…make another surgery console. cmon ike, and the analyzer doesn’t show the actual steps to the surgery anyways

**Pull request closed without merging**
