### PR TITLE
[TESTMERGE] Syndicate Contracts

### PR DESCRIPTION
**Pull request by Cenrus**
Mirrored from /tg/ PR: https://github.com/tgstation/tgstation/pull/44420

:cl: Akrilla
add: Syndicate Contracts. Use the new contract uplink to select a contract, and bring the assigned target dead or alive to the designated drop off. Call for the extraction pod and send them off for your TC payment, with much higher rewards for keeping them alive. A high risk, high reward choice for a traitor who wants a real challenge.
add: New 20 TC contract kit - supplies you with your contractor loadout and uplink.
add: Targets successfully extracted will be held for ransom by the Syndicate after their use to them is fulfilled. Central command covers the cost, but they'll be taking a cut out of station funds to offset their loss...
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Make sure you get all of the followup bugfix PRs

**Comment by Cenrus** [comment]
needs review. I don't know why the check is failing

**Comment by Kerbin-Fiber** [comment]
Dunno if this will help but Travis says
```
code/modules/modular_computers/file_system/programs/antagonist/contract_uplink.dm, line 32, column 59:
warning: field access requires static type: "status"

- code/modules/antagonists/traitor/datum_traitor.dm:17:30: add a type annotation after /list here
code/modules/modular_computers/file_system/programs/antagonist/contract_uplink.dm, line 62, column 59:

warning: field access requires static type: "status"
- code/modules/antagonists/traitor/datum_traitor.dm:17:30: add a type annotation after /list here

**Comment by Kerbin-Fiber** [comment]
So something is wrong with the `assigned_contracts` list and the line that sets it to active.

Also I think the new conflicting files are the TGUI-next stuff

**Comment by Crossedfall** [comment]
This will likely need to be tested again and possibly re-cherry picked to make sure everything is working with TGUI-Next.

**Comment by ike709** [comment]
Conflicts.

**Pull request closed without merging**
