### PR TITLE
ports screentip

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

tgstation/tgstation#56729

image

## Why It's Good For The Game

eyeing the bottom left of your screen for objnames is kinda annoying
if you make that "balloon alert bad" argument again i'm just gonna invalidate that by saying you can disable it through prefs
it's even disabled by default, like c'mon

## Changelog
🆑 Qustinnus, mothblocks
add: Hovering your mouse over things now shows their name on the top of the screen
/🆑

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
god, not this

**Comment by ike709** [comment]
It's a pref.

**Comment by PowerfulBacon** [comment]
It's a pref, but that doesnt change the fact that
 - It already exists, hovering over times already displays the name of it in the bottom left. What's the difference from looking bottom left and top?
 - I dont think it would be possible to make this look more out of place.
 - It uses a mouse over override on **everything**
Sure it's not super expensive, but when this is going to be called constantly on every single item, even cheap prices like client mousemove become insanely expensive.
Is it worth it for something that already exists and is entirely pointless?
There is no difference to looking at a message bottom left, and looking at the same message but more out of place an obnoxious in the top of the screen.
In any case the message for hovering shouldnt appear twice, and I personally think we should stick with the byond internal one because it will perform better in any case.

**Comment by jupyterkat** [comment]
isn't runechats and balloon alert's existence entirely based on making you not looking at a corner of the screen instead of the combat that's happening right now too? You can just completely write them off as "It already exists" too. plus they're not performant too so why fucking keep them at all.

**Comment by BrumalLake** [comment]
cause they're integral to gameplay unlike hovering over things

**Comment by jupyterkat** [comment]
> cause they're integral to gameplay unlike hovering over things

knowing the name of what your looking at is not integral? are you fuckin blind.

**Comment by PowerfulBacon** [comment]
> 
> 
> > cause they're integral to gameplay unlike hovering over things
> 
> knowing the name of what your looking at is not integral? are you fuckin blind.

Exactly, im not blind so I can see what im looking at. If I want a description I can shift click and get a nice description. This doesn't exactly make it so im not looking at the edge of the screen since now im looking at the top as well as the bottom left.

**Comment by BrumalLake** [comment]
image
on the original pr indicating that its probably for combat mode

**Comment by Sinestia** [comment]
This is basic accessibility for people with high res monitors like me 


 Don't close it, even if you make the default off I don't mind lmao

**Comment by Sinestia** [comment]
> 
> 
> image
> on the original pr indicating that its probably for combat mode

That's dumb. Shift-right click is how you bring up that menu which is pretty much a similar amount of time.

**Comment by PowerfulBacon** [comment]
> 
> 
> This is basic accessibility for people with high res monitors like me
> 
> Don't close it, even if you make the default off I don't mind lmao

Having the default as off isn't too bad, since the people who want it can use it and new players won't be joining to a tacky looking UI that is all over the place by default.

**Comment by Sinestia** [comment]
> 
> 
> > This is basic accessibility for people with high res monitors like me
> > Don't close it, even if you make the default off I don't mind lmao
> 
> Having the default as off isn't too bad, since the people who want it can use it and new players won't be joining to a tacky looking UI that is all over the place by default.

It's kind of bad in that people won't know it's there who may want it, because it's /tg/ so we're deviating from the standard of /tg/ downstreams for no reason other than being very conservative. Fulp, skyrat, etc. have it, so if it's not default people will assume it doesn't exist

Whereas for those who are truly bothered by it, they're used to the idea of turning it off

**Comment by PowerfulBacon** [comment]
🔑

**Comment by francinum** [comment]
I'll tolerate this with the default off.

I want this profiled though, because this is liable to be expensive.

**Comment by ike709** [comment]
Per the BYOND docs, just defining MouseEntered() on a type generates overhead.

**Comment by Archanial** [comment]
:key:

**Comment by Archanial** [comment]
If we ever end up getting combat mode, this could be reopened

**Comment by Sinestia** [comment]
> 
> 
> If we ever end up getting combat mode, this could be reopened

wtf does that have to do with anything

**Pull request closed without merging**
