### PR TITLE
[WIP] The Forgotten One and The Aeon, a new lavaland boss

### PR DESCRIPTION
**Pull request by ghost**
:cl: steamp0rt, sprites and mapping by Azlan
add: Added a new boss, The Forgotten One and The Aeon, to lavaland.
add: You must attack The Forgotten One while avoiding attacks from The Aeon in order to defeat it,
add: If you best The Forgotten One, you shall claim the Stand Arrow from his corpse.
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
Steamparp

**Comment by TeomanTheGreat** [comment]
I dub this pr kek

**Comment by Mastergodown** [comment]
steamport go back to fucking hippiestation you tranny

**Comment by zeskorion** [comment]
iunno....

**Comment by TeomanTheGreat** [comment]
Steamp0rt how long till this done

**Comment by ike709** [comment]
steamport gone

**Pull request closed without merging**
