### PR TITLE
tgui notes 2: electric boogaloo

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

shut up elon, it's not bloat. i made it so the objectives update on the notes too and it literally uses the same ui as notes.
admins can change people's objectives so it does updates, and the window is just better

readds #4498

## Changelog
:cl:
fix: fixed tgui notes
/:cl:

### CODE REVIEW

**Comment by OceanFish1** [comment]
Opened 29 seconds ago
So I can ask why do we need this?

**Comment by Sinestia** [comment]
> 
> 
> Opened 29 seconds ago
> So I can ask why do we need this?

read the OP lol


also lets you use markdown for IC notes for the few who actually edit it.

**Comment by Archanial** [comment]
> tgui bloat

eventually every UI should be tgui

**Comment by PowerfulBacon** [comment]
> 
> 
> > tgui bloat
> 
> eventually every UI should be tgui

static UIs that rarely change and gain no additional functionality from TGUI don't need to be TGUI. (Stuff like secrets panel is a prime example of stuff that never had to be TGUI)

**Comment by jupyterkat** [comment]
it’s for a better user experience overall, not just fast updating uis 😔

**Comment by utilbird** [comment]
it's also less performant than a static web panel and I BELIEVE (don't quote me on this) that the more stuff that's in the bundle the slower it runs

**Comment by jupyterkat** [comment]
this doesn't even add any shit to the bundle, it's not even a separate ui, literally the same js as paper. also stop considering that **one** ui is gonna cause the entire server to slow to a crawl

**Comment by utilbird** [comment]
_Said the contributor who slowed the server to a crawl with one robofab UI_

**Comment by jupyterkat** [comment]
*said the maintainer who made checks on master fail*

**Comment by PowerfulBacon** [comment]
This was too bodged being the paper UI and current UI doesn't need to regularly update. The paper UI is also *really* bad in the first place and regularly deletes edits.

**Pull request closed without merging**
