### PR TITLE
Departmental skirts

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
Adds skirts for each job, nukie and a preference for them. 

## Why It's Good For The Game
More customisation for your character.

## Changelog
:cl:
add: Departmental skirts in wardrobes.
add: Preference to spawn with jumpsuit or jumpskirt. 
/:cl:

Ports:
https://github.com/tgstation/tgstation/pull/44776
https://github.com/tgstation/tgstation/pull/44883
https://github.com/tgstation/tgstation/pull/45244

### CODE REVIEW

**Comment by BeloneX** [comment]
OH GOD NO

**Comment by qwertyquerty** [comment]
This again

**Comment by BeloneX** [comment]
> 
> 
> This again

whats the point of votes when people are gonna make the same pr several times until they get the result they want

**Comment by ike709** [comment]
@BeloneX Skirts actually won the vote originally. qwerty reverted because people complained.

Still believe in democracy?

**Comment by ghost** [comment]
> 
> 
> @BeloneX Skirts actually won the vote originally. qwerty reverted because people complained.
> 
> Still believe in democracy?

democracy was a mistake

**Comment by BeloneX** [comment]
> 
> 
> @BeloneX Skirts actually won the vote originally. qwerty reverted because people complained.
> 
> Still believe in democracy?

also when people complained back then why would they suddendly like it now, it's the definition of insanity, doing the same thing over and over and expecting a different result.

**Comment by SomeAngryMiner** [comment]
the security ones dont use the new sec colors and jumpsuit styles, please fix, if you are going to get this merged.

**Comment by BeloneX** [comment]
nobody will maintain this if its going trough.

**Comment by ghost** [comment]
to put it perfectly

grafik

**Comment by WhyIsCaeciliusTaken** [comment]
Yes, nuclear operatives charging in with their TACTICAL BATTLE SKIRTS isn't at all ridiculous.

**Comment by qwertyquerty** [comment]
> tactical battle skirts

😳

**Comment by MarkSuckerberg** [comment]
for the love of all that is holy why this again

**Comment by Isy232** [comment]
Half of these skirts look so horrible I doubt anyone with any sense of decency would ever wear them.
- Skirts with 2 or 3 stripes near the bottom look horrid. Especially the engineering one and atmospherics.
- Chief Engineers skirt's bottom colour is off.
- Prisoners shouldn't have a skirt, they're fucking prisoners.

I have no other issues other than PLEASE make these sprites look better before merging or at least give the option for ones that look decent.

**Comment by BeloneX** [comment]
i think people sometimes forget that we don't have the same community as tg does

**Comment by Cenrus** [comment]
prisoner skirt is funny, I want to force it on some brigged greytider

**Comment by BeloneX** [comment]
this is purely bloat.

**Comment by Isy232** [comment]
@Cenrus 
https://cdn.discordapp.com/attachments/419192460909215756/703713792231604285/Do_not_ERP_ERP_is_bad.mp4

**Comment by enthethan** [comment]
Victor is a tg fag

**Comment by BeloneX** [comment]
bee isnt tg, hush with this fetish content.

**Comment by VictorVow** [comment]
- Changed the skirts with 2/3 stripes to have 1, they do indeed look better that way
- CE skirt bottom colour tweaked 
- Security skirts darkened to better match our sprites

**Comment by ike709** [comment]
image

Vote is split and I'm amused by how much this PR angers people.

**Comment by BeloneX** [comment]
> 
> 
> image
> 
> Vote is split and I'm amused by how much this PR angers people.

fuck you, you only did this to anger people, and you have succeded with it.

**Comment by ike709** [comment]
@BeloneX Yes, which is why I had Victor work on the sprites before merge.

**Comment by BeloneX** [comment]
grafik
@ike709  also why did you use a way too old screenshot, the current vote is AGAINST it

**Comment by BeloneX** [comment]
> 
> 
> @BeloneX Yes, which is why I had Victor work on the sprites before merge.

its not the sprites being shitty, its literally everything else.

**Comment by ike709** [comment]
Screenshot was taken at the same time as merge. Nice try though.

Let the hate flow through you. It brings me enjoyment.

**Comment by BeloneX** [comment]
> 
> 
> Screenshot was taken at the same time as merge. Nice try though.
> 
> Let the hate flow through you. It brings me enjoyment.

great, more bloat that nobody wants to maintain, because this is what this game needs.

**Comment by MarkSuckerberg** [comment]
this is some funny shit I stg

**Comment by BeloneX** [comment]
for the love of god atleast make this a LRP only thing, this is not at all MRP friendly.

**Comment by BeloneX** [comment]
@ike709  why did you merge a split PR?

**Comment by MarkSuckerberg** [comment]
For funsies, that’s why

**Comment by MCterra10** [comment]
Why

**Comment by MCterra10** [comment]
Revert this crap

**Comment by MCterra10** [comment]
Come to austation, I'm modularizing it out

**Comment by BeloneX** [comment]
> Come to austation, I'm modularizing it out

i would play on austation if it wasnt on the other side of the world.

**Comment by MarkSuckerberg** [comment]
AUstation US when

**Comment by Isy232** [comment]
Thanks for fixing the sprites Victor, these look decent now.

**Pull request merged**
