### PR TITLE
Golem resprites, fixed and back from the grave

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request

adds new golem sprites, making normal golems, capitalist golems, and communist golems have updated sprites. Bananium and Alien alloy golems have their own sprites now as well

image

## Why It's Good For The Game

golems look coolerer

## Changelog
:cl:
tweak: capitalist golems now spawn with sunglasses instead of a tophat and monocle, to fit their new, more executive-style look
imageadd: new capitalist, communist, bananium, alien alloy, and normal golem sprites
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
I have no idea why travis shit himself. Shit compiles fine.

**Comment by SomeAngryMiner** [comment]
mmm
LONG A L I E N *L E G*
I think the outlines and maybe a bit of the coloring require a bit of work, and maybe de-chunkify the alien alloy golem, but certainly look better than the ones we have now.

**Comment by qwertyquerty** [comment]
I swear you'll never have a clean PR. You added a random icon file to the root directory

**Comment by zeskorion** [comment]
god.... fucking dammit

**Pull request merged**
