### PR TITLE
Departmental Skirts : Security 

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

- Adds the head of security, warden, brig physician, grey and brown detective skirt and adds them to their respective lockers
- Adds the jumpsuits into their respective lockers

image

All of these are by: @Naevii besides the detective and security officer ones.

No prisoner skirt because it looks bad. 

## Why It's Good For The Game

More uniform variety. There is already an officer skirt, so why not for everyone?

## Changelog
:cl: Naevii, ivanmixo
add: Head of security, warden, brig physician and detective skirts
add: Sec members' uniforms to their respective lockers
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
No security officer formal uniform skirt
kinda cringe

**Review by utilbird — APPROVED** [review]

**Comment by WhyIsCaeciliusTaken** [comment]
Now we're in silly territory. I will add department togas if this is merged.

**Comment by ivanmixo** [comment]
Do it.

**Comment by RDS88-beeman** [comment]
do it

**Comment by utilbird** [comment]
Do it

**Comment by WhyIsCaeciliusTaken** [comment]
Revert time. Togas are on the way.

**Pull request merged**
