### PR TITLE
Security records and turrets permission changes

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request

Alternative to #3964 and #3973

Updating security records via SecHUDs and Security Records Console is now only available to people with the Security Records permission. Previously you only needed Brig access to be able to use SecHUDs and only Forensic Lockers access to able to use the Security Records console. 

Additionally, Security access is now also required to operate portable turrets (from Brig access).

## Why It's Good For The Game

For consistency if you're able to use the console to update security records then you should be able to be able to update them via SecHUDs if you have them too since they're the exact same underlying records. 

Compared to the other PRs the Detective's SecHUDs aren't removed here because there is no reason to do so, plus it hampers their informational and investigatory Security duties whilst doing nothing to prevent the potential unauthorised arrests.

## Changelog
:cl:
balance: Updating security records now requires a single access permission, and this is the same requirement whether it be via console or SecHUDs.
balance: Portable turrets require Security access instead of Brig access.
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
Have you fully tested the new access including the relevant consoles:
modular computer ID, legacy ID, HoS minor ID, so on?

**Comment by Archanial** [comment]
Imagine being so salty someone is removing roundstart sechuds from detective.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by VictorVow** [comment]
@francinum yup all working as expected.

@Archanial

**Comment by bloons3** [comment]
Needs wiki changes

**Pull request merged**
