### PR TITLE
Disables the corporate and maintain lawsets in the random lawset config.

### PR DESCRIPTION
**Pull request by Fresh839**
## About The Pull Request

Disables the corporate lawset and the maintain lawset in the config. Which prevents them from being rolled in the "random lawset" roundstart roll.

## Why It's Good For The Game

A roundstart lawset for an AI should always be some form of "simov" lawset. Antagonists for example should always be protected by the roundstart AI's lawset. Apart from that maintain and corporate lawsets and basically any lawset that isn't a "simov" one give the AI way too much freedom. 
A corporate and maintain AI basically functions as a "semi-purged" Ai, as they allow the AI to do basically anything with a little bit of intelligent thinking/decision making.

The Ai is at the bottom of the food chain, right above cyborgs. Even an assistant has more authority than the AI. An AI needs to aid the crew and follow their orders, which is part of what makes the AI fun in my opinion. 
The roundstart AI should not have any authority nor actually command people around. Which is what they easily can and often do on corporate/maintain. The AI role isn't a "command" role and shouldn't be played with a command mindset (until you get your laws changed or go rogue of course). As a roundstart AI you are put into place by NT to serve and assist the crew. Not command it around or lead a departement. Atleast that's what i consider the AI role to be like. 

I really disliked the random lawsets since they got added and i truly believe that they have only lead to even more bad interactions with silicons, as again, the silicons on maintain/corporate have _alot_ of freedom and are able to basically ignore any law 2 questions with some decent wording. 
The "simov" lawsets are the best roundstart lawsets especially also because our silicon policy was made with a "simov" lawset in mind.
(Before you ask, i have around 120h as AI)

## Testing Photographs and Procedure
I don't have any pictures here but i only tested the code 3 times. I simply put a # infront of two config lines though so i considered these 3 tests to be enough.

</details>

## Changelog
:cl:
config: Disabled the maintain and corporate lawsets from being rolled as a random lawset.
/:cl:

### CODE REVIEW

**Comment by williamcll** [comment]
AI exists as a tool for nanotrasen to make money, it should be above serving the crew. If some people gets killed in the process, then so be it.

If an antag wants the AI to be on their side they should work for it.

**Comment by Ivniinvi** [comment]
Config is not synced with the server, it's edited at the discretion of the maintainers and head admins.

Also, random lawsets are a great conflict driver in a codebase where the primary source of entertainment is conflict. AIs can do great and fun things with these lawsets, and forcing them back into asimov-like will make AI a desk job, with many players practically begging for subversion.

**Comment by Fresh839** [comment]
> Config is not synced with the server, it's edited at the discretion of the maintainers and head admins.
> 
> Also, random lawsets are a great conflict driver in a codebase where the primary source of entertainment is conflict. AIs can do great and fun things with these lawsets, and forcing them back into asimov-like will make AI a desk job, with many players practically begging for subversion.

The Ai creates enough conflict through just the nature of it's laws and it's design. (It is incredibly easy to change the AI's laws) And it's laws applying to antagonists as they do to normal crewmembers leads to even further conflict, to give an example.

The conflict created through these random lawsets is in my opinion not "good conflict". It is conflict created by the AI being able to basically do whatever it wants. Which in my opinion is something that the AI is not supposed to be able to do at roundstart and potentially throughout the whole round as said AIs can easily deny somebody to update their laws.

**Comment by Rukofamicom** [comment]
I've a bit of a confusing stance because I like these lawsets being rolled on at roundstart, but I don't really like roundstart AI at all due to how oppressive it is regardless of lawset. I think it should be something science has to make instead of being there right from the start. 

I still like these as potential lawsets for cyborgs, and also think we could perhaps have additional roundstart cyborg slots to have a good silicon presence from the start without having the invisible eye of big brother.

**Comment by FriendlyContractor** [comment]
I agree with ruko here. AI is super cool concept and i absolutely love it BUT it does not really work with antagonist driven stealth murder mistery gameplay we have

**Comment by Archanial** [comment]
Personally I think those lawsets are fine.

Not all lawsets have to be asimov.

**Comment by Fresh839** [comment]
> Personally I think those lawsets are fine.
> 
> Not all lawsets have to be asimov.

Crewsimov would still exist after that change. I ultimately believe these lawsets give the AI too much freedom, which not only isn't fun for the crewmembers, but also for the AI player. Being limited by your laws is what makes the AI fun in my opinion.

**Comment by llol111** [comment]
As an AI main, i think those lawsets are extremely boring to have roundstart. Its just way to easy to justify doing whatever you want, and one of the two lets you murder people for breaking windows, technicaly.

**Comment by Rukofamicom** [comment]
@llol111 @Fresh341 Challenge: Come up with a lawset that isn't some form of --simov to replace them with then. Crewsimov + Asimov by themselves are boring and bland.

>  give the AI too much freedom, which not only isn't fun for the crewmembers, but also for the AI player

Speak for yourself. I love getting laws that are less explicitly strict, more on that in a huge wall of text below. 

> Its just way to easy to justify doing whatever you want, and one of the two lets you murder people for breaking windows, technicaly.

This road goes both ways. I'll list several of the reasons I dislike asimov and especially crewsimov for the behaviors they not only encourage but more or less force if you follow policy to a T instead of taking liberties because you're a "good" silicon player: 

They more or less *force* me to validhunt against my natural will - not doing everything I can to prevent that outed tot from harming again goes against my laws. I am obligated to call out anything harmful I witness<sup>1</sup>, and I must go out of my way to intervene in harmful situations. I can't do anything to go with the flow of a situation and players often hate --simov for specifically following laws because *harm is harm no matter how miniscule*<sup>2</sup>. I have to deconstruct rage cages and pseudo-arrest people for even minor harm<sup>2</sup>. I must follow any and all orders unless they somehow cause cause immediate and direct harm, which includes opening most secure airlocks<sup>3</sup>. I am forced to break up harmful fights in such a way that ensures one or both parties will hate me for it because no matter how I break it up, I have to target one person before the other. Sec really doesn't appreciate being cuffed mid-fight, and neither does the perp they're trying to capture. Both will insist that *I know* I'm causing them harm by intervening how I did.

<details>
<summary> footnotes </summary>
<sub>1) Unless I am willing to risk being reported for "willing subversion" for trying to play dumb.</sub>
<br>
<sub>2) exceptions for surgery and romerol zombies and that's about it. Despite players insisting they are entitled to consensual harm, they are not on this server by our rules. By silicon policy, if someone is consenting to self-harm I am required to intervene and treat them as a harmful threat which is mentally unstable.</sub>
<br>
<sub>3) exceptions for airlocks which allow my subversion, but no exceptions for airlocks which allow the escape of prisoners unless I can give a specific, witnessed reason as to why they are harmful because being arrested doesn't prove they are harmful. </sub>
</details>

As a "good" silicon player, I naturally do not follow these as listed to a T. I play with neutrality, but feel like I'm constantly skirting policy when I play --simov borg because I don't like to be valid-thirsty # 47 like "PREVENT ALL HARM" laws feel like they're trying to force me to be. And if security comes out as harmful, that switch suddenly flips into shitter mode because now I have protect antagonists from security while not exposing others to the inmates. Prevent harm creates so many trolley scenarios. 

### IN SUMMARY

#### The only things that stop a silicon from being a shitter about their laws is having a good mentality or being stopped by admins for having a bad mentality. The available lawsets do not have a lot to do with this.

**Comment by Fresh839** [comment]
> Challenge: Come up with a lawset that isn't some form of --simov to replace them with then. Crewsimov + Asimov by themselves are boring and bland.

>Speak for yourself. I love getting laws that are less explicitly strict, more on that in a huge wall of text below.

The thing is, and that is what I tried to say in my messages above, I personally believe crewsimov, or any form of -simov lawsets to be the optimal and ideal roundstart lawset. Exactly _because_ of it being so strict. 
Part of what makes the AI as a role fun to play is being limited and not having alot of freedom until your laws get changed. If I wanted to play a role that has freedom and power then I would play command staff. The AI is supposed to be at the bottom of the "food chain" and the in this PR disabled lawsets don't really reflect that in my opinion.
And i completely disagree with you're above message about crewsimov + asimov being bland. I like them, and enjoy playing while being bound to them as an AI. (I would even go as far as to say that crewsimov should be the only roundstart lawset but that has nothing to do with this PR.)

You brought up alot of examples here and i think it's a bit beyond the scope to go into detail in all of these. I agree that obviously law conflicts and situations where you don't know what exactly you are allowed or supposed to do occur, but part of what makes the AI role fun is applying your lawset to these situations in compliance with silicon policy. I don't think giving the AI more freedom because confusions can occur is the right way to fix that specific issue.

Now to go into a couple of your details.

> I am obligated to call out anything harmful I witness

That is correct. I don't quite see what's wrong here though? Would be strange if you wouldn't call out someone being hurt or killed on corporate lawset to be perfectly honest. Keep in mind that for example letting someone steal the CE's magboots,  is **not** harmful in any capacity and you also can't assume that they are a "traitor and thus cause harm" soley because of them stealing the magboots. 
That changes if they law 2 you to open a door into the armory to steal a gun as you can reasonably assume that this will cause future harm. Or if they law 2 you to let them into the captains office. As per silicon policy, you are allowed to deny access to high risk areas for the above mentioned reasons. Silicon policy sums this up pretty nicely as seen in the quote below.

grafik

> I must follow any and all orders unless they somehow cause cause immediate and direct harm, which includes opening most secure airlocks.

Not quite correct, as i answered in the above message.

> exceptions for airlocks which allow my subversion, but no exceptions for airlocks which allow the escape of prisoners unless I can give a specific, witnessed reason as to why they are harmful because being arrested doesn't prove they are harmful. 

I think it's reasonable to assume that people in perma are imprisoned in perma for a good reason which in 99% of all cases correlates to harm, especially now considering our updated space law.

> The only things that stop a silicon from being a shitter about their laws is having a good mentality or being stopped by admins for having a bad mentality. The available lawsets do not have a lot to do with this.

Absolutely. I'm not really trying to improve the quality of the AI players with this PR though. What I'm trying to improve is the overall interactions between the crew and the AI. Not only do I think it improves on how crewmembers experience the AI interactions but i also think it increases the fun the AI player has with their roundstart lawsets. (Again, these are just roundstart lawsets that still can at any point in time be changed). 
Adding onto that, as strange as it sounds, limiting the AI in regards to their lawset actually increases the fun the AI player has when playing AI, in my opinion atleast. Being purged is fun, but it would be really boring if that was always the case.

Phew that was a huge wall of texts and i definitely screwed up somewhere in there in regards to my english/correctness, please point me to it if you find something or don't understand something.

**Review by PowerfulBacon — APPROVED** [review]
Its great to have some variation, but these lawsets are pretty awful and end with a validhunting AI every round.

**Comment by itsmeow** [comment]
As a roundstart AI main, having asimov is fun, it creates great roleplay conflict and can even require the AI to help non-harming traitors sometimes. This is great, but also, variety is the key to fun in ss13, and making the AI *always* -imov is really boring and, as said, will make a lot of AI players "beg for subversion" as asimov makes the AI significantly less useful to the crew (an asimov AI doesn't even have to help the station AT ALL, unless ordered to, technically - why should an Asimov borg help set up the SM unless asked?)

Variety is key - removing these will make playing AI significantly more monotonous and boring. AI is already a desk job - taking away more freedom is bad for the game.

**Comment by PowerfulBacon** [comment]
I think we don't have enough lawsets at the moment for this

**Pull request closed without merging**
