### PR TITLE
Patrons will always greentext

### PR DESCRIPTION
**Pull request by qwertyquerty**
## About The Pull Request

I have been receiving reports that my recent felinid paywall PR has been seen as "pay to win" content. I would like to demonstrate that, this is simply not the case. Here I have implemented REAL pay to win.

## Why It's Good For The Game

Makes winning take less effort (for rich people) (massive QOL change)

## Changelog
:cl:
balance: Patrons always greentext
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
:((((((((

**Comment by ike709** [comment]
Let people point and laugh for a little while.

**Comment by qwertyquerty** [comment]
:))))))))))

**Comment by eeSPee** [comment]
Are we gonna see this thread bumped 3 months from now, with a different title, and 500 posts?

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
you should make the probability of greentext the amount of money someone spends as a percentage

**Pull request closed without merging**
