### PR TITLE
Fugitive fixes & ports

### PR DESCRIPTION
**Pull request by Crossedfall**
## About The Pull Request

Ports: 
https://github.com/tgstation/tgstation/pull/43941 
https://github.com/tgstation/tgstation/pull/44285
https://github.com/tgstation/tgstation/pull/44706
https://github.com/tgstation/tgstation/pull/44802
https://github.com/tgstation/tgstation/pull/47508

From 44802 (biggest adjustments):

- Waldo is less common. He's kind of immersion breaking.
- Waldo is actually waldo now. Whoops
- Yalp Elor is removed. Veeeery broken implementation.
- Removed the "armed" part of the hunter's arrival announcement. It riled security up and so this will hopefully encourage more interesting interactions
- The russian ship has some big changes. No more ripley, everyone gets a space suit, and less welding tanks. I should really redo this whole thing (and I might still) but this at least fixes the biggest problems with the ship.
- Russians now get a mosin, and have a 50/50 to spawn with either the bear hat or a ushanka.
- Hunters and fugitives get their own hud:
image
- Space cops get handcuffs instead of an extra mag.
- Bounty Hunters are a new hunter! They get some exotic tools to catch their prey.
- Pictures soon!

## Why It's Good For The Game

Fugitives are fun and it'd be nice if they actually worked.

## Changelog
:cl: Denton, Traelezab, and Fikou
add: Ghosts will now be notified whenever fugitive hunters are ready to spawn
fix: Added missing destinations for refugee hunter shuttles.
tweak: Added two EVA crates to the space cop shuttle.
add: There is a new fugitive hunter, the bounty hunters! They're barely better than space pirates!
add: The russian shuttle has undergone some changes, namely the removal of the ripley, and the addition of space suits.
del: The cultists have lost their god, RIP yalp elor.
tweak: Other various improvements like different huds for the hunters and fugitives, a less threatening announcement message, and more.
/:cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
~~Fugg, messed up the sprites~~ Fixed the icons

**Comment by Crossedfall** [comment]
Test merged onto Sage.

**Comment by Crossedfall** [comment]
Tests passed.

There is some potential for map adjustments and maybe a new bounty complete message in the future. For now though, the event is working again.

**Comment by ike709** [comment]
What could go wrong?

**Pull request merged**
