### PR TITLE
Emitters that don't use power will no longer warn about wires.

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
See title

## Why It's Good For The Game
The CTF energy cannons will now actually work (this has been broken for three years has no one actually used the energy cannons in that time)

## Changelog
:cl:
fix: Emitters that don't use power won't warn about powernets.
/:cl:

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
I remember them working before the CTF remap, no?

**Comment by Ivniinvi** [comment]
*shrug* They don't work at the moment, and this fixes that. There probably was an actual powernet before the remap or something, before my time.

**Comment by GregTheEgg42069** [comment]
This will make wabbajack not need sacrifices

**Comment by Ivniinvi** [comment]
> This will make wabbajack not need sacrifices

No it won't? Wabbajack uses a special, automatic active_tables list.

**Review by Archanial — APPROVED** [review]

**Pull request merged**
