### PR TITLE
Buffs paperwork

### PR DESCRIPTION
**Pull request by ike709**
## About The Pull Request
Pencode now supports several new commands, now we (more or less) have parity with http://ps.ss13.net/#instructions minus the baycode image commands. The help button also works now.

## Why It's Good For The Game
Paperwork is a fun and enjoyable experience.

## Changelog
:cl: ike709
add: Paper now has a help button to show you all of the pencode commands.
add: Paperwork is now more robust, with "new" features such as tables.
/:cl:

I'm 82% sure this won't somehow be used to crash the server.

### CODE REVIEW

**Comment by ike709** [comment]
Help menu:

image

**Comment by qwertyquerty** [comment]
I think we gonna have to testmerge this bad boy first

**Comment by ike709** [comment]
Go for it.

**Comment by qwertyquerty** [comment]
Actually, naaah what's the worst that could happen

**Pull request merged**
