### PR TITLE
Updates FPS Setting

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
This updates the default framerate for new players and adds a better description.

The default setting should be the best setting for most users. Why 60 specifically?
-Most users likely have a 60hz Monitor, and 60 is devisible by 20 ticks so ideally every tick frametime should be as  stable as possible. 
-From my measurements 60 Fps Frametime seems more stable than 20 Fps. 
-60 FPS to avoid frame tearing.
-Byond seems to only pump out about 64 FPS Max.

20 FPS
https://drive.google.com/uc?id=1kAu4ngM29c2w7U8XKsc6LDepFIjFVOy7

60 FPS
https://drive.google.com/uc?id=1DlKAL3qxu8gYaiDKbTUCzoojA9cyhlZe

20 FPS Jumping test
https://drive.google.com/uc?id=1OptrWMXsPVY7RQtIiyiYEc30FRRoIti2

60 FPS Jumping test
https://drive.google.com/uc?id=1ustaQB2RIDr0U45I7QQVZoAupJ0BIa-g

Please Vote after watching all 4 videos!

## Why It's Good For The Game

I personally think the difference is day and night - This will make the game more attractive to new players and more enjoyable to users who didn't manually specify the 20 FPS limit.

I think this change is important since I and I'm sure many other users saw the fps_max = 0 setting in-game and assumed it meant 'uncapped' as it does in every other game. To be honest I played like this for years.
## Changelog
:cl:
tweak: Default Framerate is now 60 FPS.
tweak: 0 now gets changed to the actual framerate in the menu.
tweak: Framerate menu gives a better description and shows the proper number.
/:cl:

### CODE REVIEW

**Comment by yorii** [comment]
tweak: 0 now gets changed to the actual framerate in the menu.

What no, revert this, a setting of 0 means your framerate literally gets synced with the server tickrate.

You're removing a feature.

**Comment by PowerfulBacon** [comment]
One thing I noticed is setting the FPS is complete bullshit anyway, a setting of 60-80 works best for me, anything higher makes it lag more and setting it to 1 FPS doesn't actually make the game run at 1 FPS

**Comment by ghost** [comment]
> tweak: 0 now gets changed to the actual framerate in the menu.
> 
> What no, revert this, a setting of 0 means your framerate literally gets synced with the server tickrate.
> 
> You're removing a feature.

You can still type in 0 and it will change to synced with the server tickrate, it's just that it's represented by 20 instead of showing 0.

**Comment by ghost** [comment]
> One thing I noticed is setting the FPS is complete bullshit anyway, a setting of 60-80 works best for me, anything higher makes it lag more and setting it to 1 FPS doesn't actually make the game run at 1 FPS

It's the way the check functions from my understanding, you can't go lower than the world.fps but you can go higher.

**Comment by Axanthic** [comment]
Closing - Was PermaBanned

**Comment by yorii** [comment]
https://en.wiktionary.org/wiki/if_it_ain%27t_broke,_don%27t_fix_it

**Pull request closed without merging**
