### PR TITLE
Removes LAssailant

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Removes LAssailant. I was going to remove it but this logic on slimes makes literally no sense. If someone attacks the silmes food the slime becomes friends with them? How does that make any sense.

## Why It's Good For The Game

Cleans up the code.

## Testing Photographs and Procedure

image

Compiles and runs. See code.

## Changelog
:cl:
code: Cleans up the code by removing LAssailant from mobs. Attacking something that a slime is feeding on will no longer cause it to become your friend.
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
> code: Cleans up the code by removing LAssailant from mobs

Player facing changes?

**Review by EvilDragonfiend — APPROVED** [review]
LAssailant is only used for slime codes. We have no reason to keep this when it makes codes annoying to read.

**Comment by Rukofamicom** [comment]
This will prevent slimes from becoming friendly to Xenobio won't it? 

Slime "friends" can issue commands to slimes such as ordering them to attack and it's a really cool, if underutilized, mechanic. I've seen it used against halo cultists to flip what otherwise was a landslide cultist victory in a really funny way.

**Comment by PowerfulBacon** [comment]
> This will prevent slimes from becoming friendly to Xenobio won't it?
> 
> Slime "friends" can issue commands to slimes such as ordering them to attack and it's a really cool, if underutilized, mechanic. I've seen it used against halo cultists to flip what otherwise was a landslide cultist victory in a really funny way.

The logic for someone becoming a friend is used elsewhere, although it seems just as bizarre and unintuitive in other places. The code quality for slimes is absolutely dreadful and seems to have been written when space station 13 was in its infancy.

**Comment by Tsar-Salat** [comment]
> The logic for someone becoming a friend is used elsewhere, although it seems just as bizarre and unintuitive in other places. The code quality for slimes is absolutely dreadful and seems to have been written when space station 13 was in its infancy.

https://github.com/tgstation/tgstation/pull/82176

This should probably be a long-term goal

**Pull request merged**
