### PR TITLE
Adds a few items to exploration shuttles.

### PR DESCRIPTION
**Pull request by AnCopper**
## About The Pull Request

Adds the following to every exploration shuttle:
One Microwave.
Two packs of Donkpockets.
An oxygen tank dispenser.

## Why It's Good For The Game

So the Exploration crew doesn't have to go loot moldy food from the abandoned stations, and so they aren't immediately fucked when they forget their oxygen tanks on the station, or need a new one.

## Changelog
:cl:
add: added microwaves, donk pockets, and oxygen tank dispensers to exploration shuttles
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
The microwave placement is really bad. Also I like forcing them to go back for food and supplies.
image
image

**Comment by AnCopper** [comment]
> The microwave placement is really bad. Also I like forcing them to go back for food and supplies.

God, why are you so unbearably nitpicky with everything, where else do you even want me to place the microwave?

**Comment by PowerfulBacon** [comment]
its not that nitpicky, theres a microwave in front of a chair

**Comment by ghost** [comment]
>So the Exploration crew doesn't have to go loot moldy food from the abandoned stations

Watching unprepared explorers having to fight xenomorphs to loot a bag of chips from a janitor's closet is exactly the kind of emergent gameplay I want to see

**Review by qwertyquerty — APPROVED** [review]

**Pull request merged**
