### PR TITLE
Medical belt resprite

### PR DESCRIPTION
**Pull request by imsynthex**
## About The Pull Request

image
image
image

## Why It's Good For The Game

I'm garbage with sprites but this turned out pretty well so might as well upload it

## Testing Photographs and Procedure

Man testing the drip:
image
image

## Changelog
:cl:
imageadd: Changed the medical belt sprite
/:cl:

### CODE REVIEW

**Comment by Isy232** [comment]
Looks great, might just be personal preference but the darker blue colour looks so much better then the light stuff.

**Comment by Naevii** [comment]
Looking sharp 👌

**Comment by Kapu1178** [comment]
Really doesnt fit our rustic artstyle imo. Looks straight out of a glossy codebase like Eris or Skyrat.

**Comment by ike709** [comment]
Looks fine to me.

**Comment by ike709** [comment]
I was hoping another maintainer would also sign off but I'll just go ahead and merge this.

**Review by ike709 — APPROVED** [review]

**Pull request merged**
