### PR TITLE
Adds lighting to xenobiology on Boxstation and Metastation

### PR DESCRIPTION
**Pull request by 123chess456**
## About The Pull Request

Every slime breeding chamber on Boxstation now has a small light fixture in it. The xenobiology test chamber on Box remains unchanged. On Metastation, the xenobiology test chamber has had it's small light replaced with a regular sized light.

## Why It's Good For The Game

I can't see anything half the time when I'm playing xenobiology on Box. Badly lit rooms make it impossible to tell certain slime colors apart. Adding lighting at roundstart makes it possible for people to actually see what they're doing when playing xenobiology on Box.

The test chamber on Meta is also sort of poorly lit. So I added a more powerful light in the exact same place as the old tiny lightbulb.

## Changelog
:cl: 123chess456
add: Every xenobiology slime chamber on Box Station now has an individual light, making it easier to see slimes. MetaStation has also gained a more powerful lightbulb in the Xenobiology test chamber.
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
man map merges on his first try? this is unprecedented

**Comment by qwertyquerty** [comment]
God bless mapdiffbot, never once works

**Comment by ike709** [comment]
@qwertyquerty Wdym? It worked.

**Comment by qwertyquerty** [comment]
image

**Comment by ike709** [comment]
@qwertyquerty 

image

Bottom right corner shows the only change, the lightbulb being replaced with a lighttube.

**Review by qwertyquerty — APPROVED** [review]

**Pull request merged**
