### PR TITLE
Pill shinanigains

### PR DESCRIPTION
**Pull request by ghost**
i care little for your documentation, qwert. 

In this PR, i added radiation medkits, partially stolen from Citadel. 

They contain charcoal, mutadone, potassium iodide, and some other types of anti-radition meds. 

This is good because alot of people who work on the SM on our server tend to be bald, stupid, or both, and get hella irradiated, i figured putting a few of these in the radiation lockers in engineering and maybe one or two in medical would help cut down on people dying of fucking radiation and spreeding it around to other people like the plague.

### CODE REVIEW

**Comment by ghost** [comment]
wait i made a mistake don't merge this

**Comment by qwertyquerty** [comment]
Things like this don't need documenting anyway

**Comment by qwertyquerty** [comment]
Shouldn't these be added to all the maps?

**Comment by ghost** [comment]
azzy said they would do it.

**Pull request merged**
