### PR TITLE
Survival Pod Walls Tweaks

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
Makes survival pod walls craftable out of a girder and plastic. 

## Why It's Good For The Game
I wanna repair my shuttle and make good looking shuttles without relying on titanium.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image

image

</details>

## Changelog
:cl:
add: Added survival pod walls to be crafted using plastic.
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
Forgot the door.

image

**Comment by MarkusLarsson421** [comment]
Not gonna lie, I am not happy with this either, but it is better than what we currently have.

image

A more experienced spriter could most likely convert the necropolis walls into sandstone and make them all connect nicely.

**Comment by PowerfulBacon** [comment]
Tbh they still look pretty horrible with that purpley colour

**Comment by MarkusLarsson421** [comment]
Yeah, we'll see if I try to make them look good or skip them entirely. The current ones just looks God awful though. Looks like lego bricks.

**Comment by Rukofamicom** [comment]
I really don't like the new sandstone look.

**Comment by MarkusLarsson421** [comment]
Going to remove the sandstone part of this PR when I have the time.

**Comment by Rukofamicom** [comment]
Due to personal circumstances, author has requested that all PRs be treated "as-is" for the time being. 
Closing this one due to failed checks.

**Pull request closed without merging**
