### PR TITLE
[READY] Clothing /under repath (#45548)

### LINKED ISSUE #1824: Blue Lawyer Slacks not Working
## Reproduction:

Try and put on the Lawyer's blue slacks. They can be worn but have been reported to show no sprite and say suit or something behind the head.

/obj/item/clothing/under/lawyer/bluesuit

### PR DESCRIPTION
**Pull request by Cenrus**
Closes #1824

https://github.com/tgstation/tgstation/pull/45548/

Still need to fix some issues but most of the it is done.

## Why It's Good For The Game

Better maintainability, files organization, saner /under paths.

:cl: actioninja
refactor: repathed all under clothing, keep an eye out for errors.
/:cl:

### CODE REVIEW

**Comment by SomeAngryMiner** [comment]
i hope you know that the medsci resprite PR is also reorganizing uniforms.
image

**Comment by Cenrus** [comment]
That's fine. This changes the filepath, icons aren't changed in any way.

**Review by Crossedfall — APPROVED** [review]
Approving the map script file.

**Comment by qwertyquerty** [comment]
@Cenrus conflicts

**Comment by ike709** [comment]
Conflicts again.

**Comment by Cenrus** [comment]
conflicts are no more, hopefully for the last time

**Comment by ike709** [comment]
QM's outfit has no icon: `/obj/item/clothing/under/rank/cargo`

**Comment by ike709** [comment]
One of the lawyer's suits was also reported broken but I don't know which one.

**Comment by ike709** [comment]
QM suit was busted while worn too.

**Comment by ike709** [comment]
Several medical sprites were reported broken in OOC.

**Comment by Cenrus** [comment]
Merging master seems to have broken things, feel free to remove the testmerge

**Comment by ike709** [comment]
I already did, the round is still going.

**Comment by ike709** [comment]
Black slacks reported broken.

**Comment by ike709** [comment]
`/obj/item/clothing/under/rank/medical` is broken while *not* being worn as well.

**Comment by Cenrus** [comment]
Fixed all issues as stated.

**Comment by ike709** [comment]
Seems fine.

**Pull request merged**
