### PR TITLE
Retro jacket and retro chicken head - new donator items

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request
Add those two donator only items.

Sprites made by Naevi (https://campsite.bio/naevi)

## Changelog
:cl: Naevi
add: Retro jacket and retro chicken head, 2 new donator items inspired by hotline miami.
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
I don't know if I like the idea of roundstart Hotline Miami on MRP, but these are cool items for maybe maint loot or something.

**Comment by Archanial** [comment]
We have jojo roundstart items

**Comment by ike709** [comment]
One bad idea doesn't justify more bad ideas, but if the other maintainers think it's fine I don't mind.

**Comment by Naevii** [comment]
> 
> 
> I don't know if I like the idea of roundstart Hotline Miami on MRP, but these are cool items for maybe maint loot or something.

I will just more or less sumarize what i said on discord :
- Donor shop is a great way to thank people who donate their money to us. 
- I don't think putting regular looking items to donor shop would be fair towards our regular (non-donor) players. Because donor content is solely made out of new items, with new sprites and ideas, (which are better than most of already existing items in game and that would leave bad after taste for players who can't afford to donate but still wanted the drip). 
- When i thought of donor shop i decided it will be based on things that are mostly silly references to popculture and things that are generally liked by players, but also something that you can't use on regular basis. (also obviously it should include items that are cosmetics only, without any real advantage)
- Most of the stuff existing in donor shop is obvious jojo reference,But I never noticed and i never heard anyone complaining about players behavior. or players who abuse the items to play not respecting the roleplay. I think our playerbase can be trusted enough with references to use them carefully. 

- hotline miami is based, and both of those items alone won't look like obvious reference. 

EDIT.
- This game is made out of so many references i can't count.

**Comment by ike709** [comment]
eh fair

**Review by ike709 — DISMISSED** [review]

**Pull request merged**
