### PR TITLE
Removes game and server crashing stand power

### PR DESCRIPTION
**Pull request by YakiAttaki**
## About The Pull Request
Removes the pocket dimension stand power, since it crashes the game when it's used for both players and the server.

## Why It's Good For The Game
Abilities that cause the game to crash aren't very good, especially when they affect the server as a whole.

## Changelog
:cl:
del: Removed the pocket dimension stand power.
/:cl:

### CODE REVIEW

**Comment by YakiAttaki** [comment]
goddamn atmos runtimes

**Comment by MCterra10** [comment]
unknown
just fyi, this is what happens when the power is used. it completely locks up the server in this state requiring a manual reboot through TGS/dream daemon. test your code please.

**Comment by ike709** [comment]
Another issue courtesy of @qwertyquerty merging something 🤔

**Comment by ghost** [comment]
WHY WAS I NOT TOLD ABOUT THIS

**Pull request merged**
