### PR TITLE
Makes RCDs rare-ish again.

### PR DESCRIPTION
**Pull request by Kapu1178**
## About The Pull Request
Removes the 3 RCDs from the Engivend.
Adds an RCD to the Chief Engineer's locker.

Removes the RCD from Cargo's protolathe.

**RCDs are still available in engineering protolathe**

## Why It's Good For The Game
1. The reason for the addition to the Engivend was a MASSIVE cope. "Engineers need to carry around materials". Yeah, no fucking shit. Construction is a mechanic for a reason.

2. RCDs are EXTREMELY powerful, being able to space tiles or create walls in seconds. Having 5 of these fuckers roundstart trivializes engineer gameplay.

3. Why the hell can Cargo print these things? Ask engineering for one.

## Changelog
:cl:
del: Engivend no longer stocks RCDs.
del: Cargo can no longer print RCDs (Engineering still can)
add: Chief Engineer starts with an RCD in their locker.
/:cl:

### CODE REVIEW

**Comment by RDS88-beeman** [comment]
Upside is now people actually need to learn to construct fucking doors because lord knows nobody does
Downside is custom shuttles become harder

**Comment by St0rmC4st3r** [comment]
>custom shuttles become harder
Not really. The shuttle kit still has one.

**Comment by Naevii** [comment]
Overall good idea but I dislike it mainly because without rcds rebuilding or patching up Station after bombing will take significantly longer and in most cases people won't bother now.

**Comment by PerishedFraud** [comment]
>Why the hell can Cargo print these things? Ask engineering for one.

Miners use RCDs to bridge lava and abyss. I suggest moving it to the mining vendor for like 2500 if you want them to be less abused. That'll stop mass printing without nerfing them _again_.

That said, this just reads like another general crew nerf PR. Can't say I really support it though your intentions seem good. Anyone can build things but only engis actually start with RCDs right now. It's entire possible that the solution here is overkill even though the idea isn't. That's just my input on it anyway.

**Comment by Glcbitj** [comment]
Why can you only space tiles with RCDs only really? It's useful for emergency removal of gasses in a room, but you can only do so with that somewhat rare tool, fucking why can't you just remove the tile with tools?

**Comment by Kapu1178** [comment]
> 
> 
> Why can you only space tiles with RCDs only really? It's useful for emergency removal of gasses in a room, but you can only do so with that somewhat rare tool, fucking why can't you just remove the tile with tools?

venting an entire room should be considered a last resort and not something that every engineer does in responses to an atmospherics problem.

**Comment by williamcll** [comment]
This nerf will highly favor nuke ops because building defenses will take far longer since you don't have a lot of resources at the start to print RCD or get materials for walls/windows.

**Comment by francinum** [comment]
> This nerf will highly favor nuke ops because building defenses will take far longer since you don't have a lot of resources at the start to print RCD or get materials for walls/windows.

If RCDs are the deciding factor between warop and station balance there's bigger problems at hand.

**Comment by Archanial** [comment]
I don't think it solves a larger issue of our economy being just shit.

They could remain in vendors if their price was reasonably high and you couldn't get them straight away.

**Comment by williamcll** [comment]
> > This nerf will highly favor nuke ops because building defenses will take far longer since you don't have a lot of resources at the start to print RCD or get materials for walls/windows.
> 
> If RCDs are the deciding factor between warop and station balance there's bigger problems at hand.

Well, some of the recent crew nerfs aren't helping either.

**Comment by PerishedFraud** [comment]
You gotta realize that this won't nerf crew, it'll do the following...

-Crew that benefit greatly from RCDs will now be forced to cope, tide or ask for an RCD. When they do tide, people will call it powergaming.

-In a state of emergency and/or mass station repair, engi will routinely be broken into to get the crew RCDs.

Might as well say what I said the first time. The idea is good but the execution here will add nothing of value.

Also go buff build times at least.  Building is not fun at all. Fix it.

**Comment by Glcbitj** [comment]
Me when engineers use all the iron on the silo to make RCDs with their Protolathe.

**Review by Archanial — APPROVED** [review]

**Pull request merged**
