### PR TITLE
Juke Build Reforged

### PR DESCRIPTION
**Pull request by Sinestia**
## About The Pull Request

Adds juke build, handles your tgui, handles your DM, concurrently so-as to not increase compile times. 

This PR was created by reverting parts of the last large tgui PR and adding juke onto it. 
## Why It's Good For The Game

The conflict github action is actually, legit, dumb, no one involved indicates that they even remotely are happy with it. Plus it doesn't even fix half of the issue which is getting extraneous emails/notifications for no reason, instead of the bot you literally may as well just write a PS script for yourself to auto-tgui and push.  

All of this to dodge 70 mb of Bootstrappin and a now widely tested build system. 

Additionally, /tg/ TGUI PRs often have juke in mind now. TGFont is completely unusable right now on bee due to that fact, in addition to problems with webpack and CSS, while these not unfixable, it's a pain when no one here really wants to put in any more work on the TGUI backend than necessary. This harms repo maintainability as well, which Bee already struggles with to put it mildly. 

## REMINDER: You need to enable the precompile hooks on TGS.
I have not reinstalled tgs to test this, but I swear I remember it being quite obvious on how to do so. Still, I should probably reinstall it to double check and provide braindead steps. 

The cost to the user:
If you have node installed, it uses it.
If you don't, it downloads a binary into tools\bootstrap\.cache
Your yarn dependencies (to build tgui itself) are checked, if they are absent, they will be fetched to tgui\.yarn\cache.

Nothing is permanently installed, but what was downloaded will persist through branch changes due to gitignore. 

This is a completely fresh repo pull, nothing local, no node installed on my computer beforehand. 70 sec
JUKEVIRGIN

This is tgui --clean, and the dmb deleted. 40 seconds
(For some reason invoking the compiler in dreammaker itself alone for comparison's sake took... a minute and 9 seconds. Strange. I had even less running on my PC at the time too. But safe to say that in ordinary circumstances this isn't bloating your compile times)
JUKEREUSE

## Changelog
:cl:Stylemistake, Various /tg/ Coders, Froststahr port
code: TGFont is now working again
code: Juke build is now used when compiling the server, the BUILD.bat must be used
server: TGS instances will require the precompile scripts to be added
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
This is more tempting than it was a month ago

**Comment by Sinestia** [comment]
I tested docker

And it didn't work. HOWEVER! It doesn't break in a unique way to running it on master, and apparently docker support is no longer required. 

edit: Docker doesn't work testing on windows and fedora on master. But the concern here is with CBT, which doesn't spit out any problems. Auxtools and extools just seem real PICKY about your docker host setup or something, because tgstation images function fine.

**Comment by Sinestia** [comment]
Docker should be functional now.

 I think there's an unresolvable problem with using beestation's dockerfile, which is that the base beestation:byond seems to be explicitly a 32-bit OS image, instead of a 64-bit with multilib packages. That results in the bootstrap not being able to pull in a usable binary due to [only offering 64 bit linux executables](https://nodejs.org/download/release/v12.20.0/) on their website. 

To restore the old image as of https://github.com/BeeStation/BeeStation-Hornet/pull/4861/commits/89a0d8bb8754c3f6996a887d7a97ed6cfc1330e9 the original would either need to be changed to a 64 bit OS, or it'd have to switch to Ubuntu 21.04 since only that offers a new enough node. 
~~Alternatively base the image on arch~~

**Comment by ike709** [comment]
YOLO

**Pull request merged**
