### PR TITLE
Ports Intern Auto-Flags from TG

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
Ports parts of and the idea of tgstation/tgstation#58236
IDs will now auto flag themselves as belonging to an "Intern Cook" or "Intern Curator" and so on if the player holding them has less than 20 living hours (that's the default, editable in config).

## Why It's Good For The Game
There's a lot of players who love teaching new players and showing them the ropes, and this would help them figure out who likely needs that bit of extra attention.

## Changelog
:cl: Ivniinvi, Timberpoes
add: Players with less than 20 living hours (editable in config) will now have their ID cards display as Intern (job)
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
adding alt job titles could work better tbh

**Comment by mcmeiler** [comment]
> 
> 
> adding alt job titles could work better tbh

That would require the player to set an alt job title which I doubt many new players know how to do.

**Comment by Archanial** [comment]
Why not play assistant and actually assist?

**Comment by BrumalLake** [comment]
improves new player performance by 150%

**Comment by DerpiestBruh** [comment]
> Why not play assistant and actually assist?

At some point newbies don't want to play Assistant and rather wanna learn some jobs easier than struggle for the lack of access and department designation

**Comment by Ivniinvi** [comment]
> Why not play assistant and actually assist?

The open-ended nature of the Assistant job makes it difficult for very new players to do this, especially if they don't know what the HoPline is and how to get a job or door access there. This makes it so that they can take a job *(and actually have something to do besides running around beating up vending machines)* and the more experienced players/heads of staff will be able to recognize that they are new and help them out if needed.

**Comment by FriendlyContractor** [comment]
Are we certain its not gonna have opposite effect and players abusing plus discriminating new players instead ?

**Comment by Sinestia** [comment]
> 
> 
> Why not play assistant and actually assist?

No one wants assistants

**Comment by BrumalLake** [comment]
play beestation for the first time and have "Noob" stapled onto your id

**Comment by francinum** [comment]
dude.


This code is fucking *nasty*

**Comment by Archanial** [comment]
I don't oppose the idea but the code is truly awful.

It should be called only once, during equip, any signals are absolutely unnecessary here.

🔑

**Comment by francinum** [comment]
Not a terrible idea, But flawed execution, and I have no idea why TG would approve something like this.

🔑

**Comment by Kapu1178** [comment]
holy mother of code bloat batman, my code isnt this bad!

**Pull request closed without merging**
