### PR TITLE
Aristocrat coats & Hastur Robes

### PR DESCRIPTION
**Pull request by Malgover**
## About The Pull Request

This PR adds 4 new coats to the law office's wardrobe and reworks the Hastur robes. 
coats

hastur2

Orange:
orange

Red:
red

Brown:
brown

Blue:
blue

Hastur robes:
hastur

Just like all hoods in the game, it only looks good if your character's hairstyle is short or nonexistent due to it clipping through the sprite.

## Why It's Good For The Game

The more clothes the better, and the law office's wardrobe is lackluster compared to other wardrobes. This PR aims to provide our beloved lawyers with more customization. Now they can truly look like lawyers!

As for the Hastur robes, I thought the original sprite was quite ugly and needed a change (no offense to the original spriter). I used the Eldritch armor as a base for the sprite to be more coherent with the server's artstyle. 
The robe is now available to purchase from the Chaplain's wardrobe.

PS: I closed my previous PR because I don't understand how anything works on GitHub.

## Changelog
:cl:
Adds aristocrat coats to the law office's wardrobe and reworks the hastur robes.
/:cl:##

### CODE REVIEW

**Comment by ItsTisme** [comment]
Isant there a clothing flag you could apply to the hood part to hide hair?

Winter coats already do this

**Comment by TeomanTheGreat** [comment]
My man is making a pr from master 😳

**Comment by Malgover** [comment]
> My man is making a pr from master 😳
> 

I don't understand GitHub at all, sorry.

**Comment by TeomanTheGreat** [comment]
> > My man is making a pr from master 😳
> > 
> 
> I don't understand GitHub at all, sorry.

Its okay. I had the same problem when I started out.

**Pull request closed without merging**
