### PR TITLE
IPC upload traitor item

### PR DESCRIPTION
**Pull request by chloecat0**
## About The Pull Request
Adds a 10 TC role restricted traitor item for roboticists and RDs that brainwashes IPCs with the laws from lawboards.
When the laws are uploaded they'll say over the radio where the upload is and be given asimov plus whatever the laws on the board are as brainwash objectives, what this means is that for proper brainwash objectives to be added a syndicate lawboard is needed which is another 9 TC.

Also makes it so brainwash objectives can be replaced rather than added.

## Why It's Good For The Game
It's an interesting way to brainwash IPCs that makes sense

## Changelog
:cl:
add: Adds the IPC upload traitor item for roboticists/RDs 
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
IPCs are already underpowered as hell, a remote upload console is way too much. there's a reason the brainwash surgery is a surgery

**Comment by chloecat0** [comment]
I could probably make it so it only works on ipcs within a few tiles

**Comment by PowerfulBacon** [comment]
10 TC to instantly convert any IPC with no counter, unlimited uses and currently unlimited range seems a <i>tad</i> op

**Comment by chloecat0** [comment]
I don't think people fully understood what this pr does so I've updated the description

**Comment by chloecat0** [comment]
https://wiki.beestation13.com/view/Syndicate_Items#IPC_Upload

**Comment by qwertyquerty** [comment]
I'm not really sure how I feel about basically silicon laws existing but in the form of objectives

**Comment by ike709** [comment]
I'm not a fan either. Sorry for wasting your time with the wiki changes, crossed shouldn't have applied that label yet.

**Pull request closed without merging**
