### PR TITLE
we dont talk about these

### PR DESCRIPTION
**Pull request by LastCrusader105**
## About The Pull Request
fixes boxstations piping issues
example
image
to
image
from 
image
to
image
deleted these
image

fixed all pipe errors on bees box ( one has been around since monstermos because the layer adapter was set to 8 rather than 4)
tidied up all of airlocks pipes
image

 
## Why It's Good For The Game
give Beestation some mapping standards and stops the server being a laughing stock for your poor maps

## Changelog
:cl:
tweak: tweaked airlocks pipe layout thanks to francium for showing me
fix: fixed pipe errors
/:cl:

### CODE REVIEW

**Comment by LastCrusader105** [comment]
image
only errors left are from mining and ransom maint rooms and ruins

**Comment by LastCrusader105** [comment]
hmmm i seem to have fucked up

**Comment by LastCrusader105** [comment]
or maybe not who knows

**Comment by qwertyquerty** [comment]
make a new pr on the right branch

**Pull request closed without merging**
