### PR TITLE
Makes lasers hitscan.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This makes all Lasers (EXCEPT THE DISABLER!!!!) instantly travel to where they were fired at.

## Why It's Good For The Game

muh realism for lasers, this also further differenciates lasers from just being guns that deal burn damage.

## Changelog
:cl:
balance: Every Laser except the disabler instantly travels to it's target now.
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
Does this mean all the lasers hitscan unless they were shot by the disabler or that the blue lasers dont hitscan?

**Comment by ghost** [comment]
> Does this mean all the lasers hitscan unless they were shot by the disabler or that the blue lasers dont hitscan?

disabler projectiles are not hitscan

**Comment by PowerfulBacon** [comment]
This is a stupid PR and like most changes for realism, isn't good for balance nor gameplay

**Comment by MACIEKBAKI** [comment]
kind of dumb ngl

**Comment by MACIEKBAKI** [comment]
even more so when you remember pulse rifles exist which, albeit rarely seen, are decently powerful and would be autistically powerful if hitscan

**Comment by ghost** [comment]
> even more so when you remember pulse rifles exist which, albeit rarely seen, are decently powerful and would be autistically powerful if hitscan

pulse rifles arent supposed to be balanced

**Comment by PerishedFraud** [comment]
What we needed: Rename lasers to beams

What we got:

**Comment by Krysonism** [comment]
I don't play on bee, but i think this is a bad idea.

I think it will tempt 13 yo scriptkiddies to install aimbot.

Currently i think cheating is kept under control because of how easy it is to get robusted despite cheats.

**Comment by PowerfulBacon** [comment]
Closing the PR on the basis that I don't really see anyway of this getting merged for multiple reasons.
1. Changes a significant factor of the game which has been designed around for years (Also its a significant factor of the game that has no problems at all)
2. Changes something that doesn't really need changing, which will inevitably create a whole host of new problems on something with no/ very few problems
3. Realism isn't fun, nor balanced most of the time. hence why we are on a space station producing a magical gas and using a magical dimension to make near-infinite storage.

**Pull request closed without merging**
