### PR TITLE
Random engines for meta and box minus kilo

### PR DESCRIPTION
**Pull request by Moccha-Bee**
## About The Pull Request
Zesko said he would add randomized engines, but i ain't gonna allow that cringe plasma man to beat me, It's fully working with tesla/singularity room for meta that comes with a spawner that has a 80% chance of spawning a tesla and 20% of spawning a singuloth.
https://imgur.com/gallery/zmGkG7b
the random engines above^
ignore the depressurization, one of the airlocks was missing a tile.

- [x] Finish all the meta engines

- [x] Add random engines to box

## Why It's Good For The Game
It's pretty based and forces engineers to learn the old engines.

## Changelog
:cl:
add: Added randomized engines to meta
add: Added randomized engines to box
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
lol

**Comment by LastCrusader105** [comment]
How did you do it? Like random Maint rooms, just made few templates? And job done?

**Comment by Moccha-Bee** [comment]
> How did you do it? Like random Maint rooms, just made few templates? And job done?

yes, i added new spawners for specific map templates. so each engine is unique and better fitted for the map they are going to be used

**Comment by Moccha-Bee** [comment]
> How did you do it? Like random Maint rooms, just made few templates? And job done?

i added new spawners for specific map templates. so each engine is unique and better fitted for the map they are going to be used

**Comment by Archanial** [comment]
okay but why would we want engines that lag the server be obtainable outside of cargo?

**Comment by Sinmero** [comment]
I dunno. Lrp antags that completed their objectives could easily wreck the station with this.

**Comment by Moccha-Bee** [comment]
> okay but why would we want engines that lag the server be obtainable outside of cargo?

>lag the server
????????? never heard any issue about either tesla or singuloth being laggy in any meaningful way.

**Comment by Moccha-Bee** [comment]
> I dunno. Lrp antags that completed their objectives could easily wreck the station with this.

just valid hunt and kill them like all good lrp players

**Comment by Archanial** [comment]
> > lag the server
> > ????????? never heard any issue about either tesla or singuloth being laggy in any meaningful way.

check this out https://github.com/tgstation/tgstation/pull/52930

**Comment by Moccha-Bee** [comment]
> > > lag the server
> > > ????????? never heard any issue about either tesla or singuloth being laggy in any meaningful way.
> 
> check this out [tgstation/tgstation#52930](https://github.com/tgstation/tgstation/pull/52930)

it only lags if its looose on the nooose, just contain it better 
image
And besides both the singuloth and tesla engines are rare in relation to the super matter. So them going loose will be a rare occurance.

edit: the random engines is also supposed to be complemented with the rbmk reactor if it get's merged, which will be the second most common engine making tesla/singuloth even more rarer.

**Comment by LastCrusader105** [comment]
> I dunno. Lrp antags that completed their objectives could easily wreck the station with this.

I dunno even with normal Sm I can singulo/Tesla it in about 5 mins
So while you are correct I don’t think it will really have any effect on gameplay
I’d be more worried about new engies than I would antags, pubby Sm delams every round

**Comment by Archanial** [comment]
> And besides both the singuloth and tesla engines are rare in relation to the super matter. So them going loose will be a rare occurance.

SM gets delamed pretty othen, if you decide to bring back old engines they will break out every round.

**Comment by Moccha-Bee** [comment]
> > And besides both the singuloth and tesla engines are rare in relation to the super matter. So them going loose will be a rare occurance.
> 
> SM gets delamed pretty othen, if you decide to bring back old engines they will break out every round.

The problem is, the engines will be sabotaged either way, atleast the most destructive ones are very rare in relation to the least one.

**Pull request closed without merging**
