### PR TITLE
tgui: Abductors

### PR DESCRIPTION
**Pull request by Sarchutar**
## About The Pull Request

Ports https://github.com/tgstation/tgstation/pull/51920 and a small part of https://github.com/tgstation/tgstation/pull/52085.
It is on the Things to Port list https://github.com/BeeStation/BeeStation-Hornet/projects/2#card-41056606

Also changes it so that only someone with the `TRAIT_ABDUCTOR_TRAINING` can open the abductor console. (Had previously only an `isabductor` check (can revert it if not wanted))

Original description:
> This PR converts all 3 Abductor related machinery (Gland Dispenser, Probing Console and Abductor Console) to tgui from their former html based interfaces. Comparison images further below.
> 
> Functionality remains basically the same, however some changes should be noted - Abductor Console now uses uplink-like interface for dispensing Abductor gear, and new abductor gear datum is used to achieve that, which means you can now easily add a new item by simply creating new /datum/abductor_gear subtype.
> 
> Messages regarding experiments were cleaned up to be showing properly in the UI, and a new one was added for invalid specimen processing.
> 
> Lastly, all new abductor interfaces use a newly created Abductor theme, as using Nanotrasen logo and colors would probably not be very thematic for a supposedly highly advanced alien race.

<details>
  <summary>Old Gland Dispenser
</summary>

GlandDispenserOLD

</details>

NEW:
GlandDispenserNEW

<details>
  <summary>Old Probing Console
</summary>

ProbingConsoleOLD

</details>

NEW:
ProbingConsoleNEW

<details>
  <summary>Old Abductor Console
</summary>

AbductorConsoleOLD

</details>

NEW:
AbductorConsoleNEW

## Why It's Good For The Game

Better UIs.

## Changelog
:cl: Arkatos, Sarchutar
add: All Abductor machines now use tgui.
tweak: Only the abductor scientist/agent can now interact with the abductor console (not the camera console)
/:cl:

### CODE REVIEW

**Comment by ItsTisme** [comment]
Pretty sure this also fixes #3161 so thats nice

**Comment by Sarchutar** [comment]
> Pretty sure this also fixes #3161 so thats nice

The camera console still only has the `isabductor` check so if you are not an abductor, the species, then you still cannot use it. If wanted i can also additionally add the check for the trait.

**Review by utilbird — APPROVED** [review]

**Comment by francinum** [comment]
Is there a way to trigger the emergency teleportation system without being an abductor?

**Comment by Sarchutar** [comment]
> Is there a way to trigger the emergency teleportation system without being an abductor?

Yes, because of 
```
/obj/machinery/abductor/console/attack_hand(mob/user)
	. = ..()
	if(.)
		return
	if(!HAS_TRAIT(user, TRAIT_ABDUCTOR_TRAINING) && !HAS_TRAIT(user.mind, TRAIT_ABDUCTOR_TRAINING))
		to_chat(user, "<span class='warning'>You start mashing alien buttons at random!</span>")
		if(do_after(user,100, target = src))
			TeleporterSend()
```
So if you don't have the abductor trait, try to use the console and stand on the pad you get teleported to the release point after the `do_after`

**Pull request merged**
