### PR TITLE
Gang Hotfix

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

* Fixed some gang items not working properly
* Fixed gang spray/territory takeover bugging out
* Fixed reinforcements not working
* For balance reasons, implant breaker no longer fullheals

## Why It's Good For The Game

Gang needs an overhaul. 
Hopefully everything works properly now.

## Changelog
:cl:
fix: Fixed some gang items not working properly
fix: Fixed gang spray/territory takeover bugging out
fix: Fixed reinforcements not working
balance: Gang revival implant no longer aheals/revives
/:cl:

### CODE REVIEW

**Comment by bloons3** [comment]
> For balance reasons, implant breaker no longer fullheals
Why did it EVER fullheal

**Comment by eeSPee** [comment]
> > For balance reasons, implant breaker no longer fullheals
> > Why did it EVER fullheal

It was an expensive way to bring your guys back, or convert dead people. Sort of like cult.

**Comment by DatBoiTim** [comment]
There also was a timer issue during a gangs round with a BoH. Please investigate.

https://discordapp.com/channels/427337870844362753/605179594617782302/848897890030059550

https://discordapp.com/channels/427337870844362753/605179594617782302/848941261117194241

Messages for reference

**Comment by bloons3** [comment]
> There also was a timer issue during a gangs round with a BoH. Please investigate.
> 
> https://discordapp.com/channels/427337870844362753/605179594617782302/848897890030059550
> 
> https://discordapp.com/channels/427337870844362753/605179594617782302/848941261117194241
> 
> Messages for reference

Out of scope for this, unless gang refactor added something with a timer interaction

**Comment by DatBoiTim** [comment]
> Out of scope for this, unless gang refactor added something with a timer interaction

Why I said investigate.

**Comment by eeSPee** [comment]
Could have been some bad arguments causing timer functions to not conclude and never forward the timers.

I tried replicating the deconversion bug and I couldn't see the problem.

And besides the constant territory/swag check, the gang game mode is not very reliant on timers. I was not able to pinpoint the issue accurately as of now.

**Comment by utilbird** [comment]
I really don't like seeing balance changes in a PR labled as a "hotfix" atomize pls

**Comment by bloons3** [comment]
> I really don't like seeing balance changes in a PR labled as a "hotfix" atomize pls

Gangs has been disabled in config, and will likely be for the substantial future because of the changes in this PR and the rework PR, which were never testmerged and have major issues.

**Comment by eeSPee** [comment]
Idea; revert gangs remake (#4413) and then I'll propose this and gang rework into one complete PR.

**Comment by utilbird** [comment]
> Gangs has been disabled in config, and will likely be for the substantial future because of the changes in this PR and the rework PR, which were never testmerged and have major issues.

It was never enabled in the config. It only ran because an admin ran it

**Review by utilbird — APPROVED** [review]

**Pull request merged**
