### PR TITLE
Add new greeting sounds for some antags

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

Adds some new greeting sounds for antags that didn't have any, or didn't have their own:

### Credits:

- `abductee.ogg`: https://freesound.org/people/Breviceps/sounds/453391
- `brainwash.ogg`: https://freesound.org/people/_NOMINAL_/sounds/124602
- `hypnosis.ogg`: https://freesound.org/people/Sclolex/sounds/342103
- `incursion.ogg`: https://github.com/OracleStation/OracleStation/pull/1122 (made by FeiH)

## Why It's Good For The Game

Flavor is nice for the game

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
soundadd: Added a greeting sound for abductee victims. (credit: https://freesound.org/people/Breviceps/sounds/453391)
soundadd: Added a greeting sound for brainwashing victims. (credit: https://freesound.org/people/_NOMINAL_/sounds/124602)
soundadd: Added a greeting sound for hypnosis victims. (credit: https://freesound.org/people/Sclolex/sounds/342103)
soundadd: Added a unique greeting sound for incursion members. (credit: FeiH, OracleStation)
tweak: Antagonist greeting sounds now use their own sound channel, ensuring they don't overlap in the (extremely rare) case where you get multiple antags in a short period.
/:cl:

### CODE REVIEW

**Comment by Absolucy** [comment]
Alright, have to find a different sound for `hypnosis.ogg`, as it's under a NC license. Gimme a bit.

**Comment by Absolucy** [comment]
Alright, replaced hypnosis.ogg with a CC0 sound, and added a unique abductee sound, which is also CC0

**Comment by itsmeow** [comment]
Wizard sound is just some fantasy chiptune - I don't think it's very good flavor, you can probably find some better magicy or other fantasy sound

**Review by PowerfulBacon — APPROVED** [review]

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
actually the wizard sound is terrible and a 30 second ear-peircing song. Either remove it or find a replacement

**Comment by Absolucy** [comment]
@PowerfulBacon @itsmeow wizard sound removed (unless someone finds a better one)

**Review by PowerfulBacon — APPROVED** [review]
Fine with the rest, checks are failing

**Comment by PowerfulBacon** [comment]
Okay checks were cancelled for some reason, I'll rerun them

**Review by Penwin0 — APPROVED** [review]

**Pull request merged**
