### PR TITLE
Excommunicates can't purchase syndicate comms anymore

### PR DESCRIPTION
**Pull request by Penwin0**
## About The Pull Request
Removes the ability for excommunicate traitors to buy syndicate comms, which would otherwise allow them to hear their hunters and thus removing all sense of paranoia and suspense.

This also seems to have been the original intent of the creator considering the comment already present, but must have stopped working at some point.

## Why It's Good For The Game
It's very common for excommunicates to inmediatly purchase a syndicate key, getting the names of all their hunters instantly, even if this is optimal gameplay I feel like it takes away from the experience for both sides

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Screenshot_1895

</details>

## Changelog
:cl:
balance: Excommunicates can no longer purchase syndicate communication keys or implants
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Oh yea, this is what the incursionist flag was meant to be for, although it got broke somewhere along the way.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by mystery3525** [comment]
I feel like this is a bad change as this will now allow incursions to have essentially a risk-free, entirely private, always operational, and meta-protected method of communication when we were explicitly denied removing it to begin with. https://github.com/BeeStation/BeeStation-Hornet/pull/9180

**Comment by Penwin0** [comment]
I'm out of the loop with those and this PR isn't about how strong or weak incursion comms are, it's about excommunicates not being able to instantly know all their hunters

**Comment by Fronsis** [comment]
Yeah, one issue is the comms of the incursionists that we tried to tackle on multiple discussion threads both in github and forums

However another one is what this PR tackles, which is an EX-Comm instantly buying the radio just to know their hunters and either kill them pre-emptively  or just snitch to security and ask for protection

We should look in the near future to tackle again the comms of the incursions, but that's out of the scope of this particular PR.

**Comment by PowerfulBacon** [comment]
> I feel like this is a bad change as this will now allow incursions to have essentially a risk-free, entirely private, always operational, and meta-protected method of communication when we were explicitly denied removing it to begin with. #9180

https://github.com/BeeStation/BeeStation-Hornet/issues/9183

**Pull request merged**
