### PR TITLE
Tend Wounds buffs and related tweaks port

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request

TL,DR: tend wounds is quicker, more effective and is a viable alternative to sleepers:
- Tend Wounds is now only 2 steps (Scalpel > healing with Hemostat. Hemostat step is repeatable. Cautery when you're finished)
- More research means that you can unlock more advanced versions than the basic surgery and eventually it can even heal both brute/burn at once
- It can be done through clothing
- Success chances and fail damage tweaked
- Medibots now tend wounds
- TW heals more scaling with missing health

See changelog at bottom for full info.

## Why It's Good For The Game
Tend wounds is currently so weak and long-winded that it's a waste of time to try to heal someone with it. This makes it a viable alternative to sleepers, and gives doctors something to do rather than spend 5 seconds putting someone in a sleeper and clicking a button. 

## Changelog
:cl:
balance: Tend Wounds is now only 2 steps (Scalpel > healing with Hemostat. Cautery when done)
fix: Borgs can now perform Tend Wounds
add: Anti-spam on Tend Wounds (Starting Message only, Result Message untouched)
add: Keep their pants on! Now Tend Wounds can be done through clothing! However it is 60% less efficient this way
tweak: You can upgrade both Tend Wounds Burn/Brute trees via techwebs
add: Advancing far enough into the tree enables Mixed Tend Wounds surgery, which heals less of each but is considerably faster. Get alien tech for the best of the best!
balance: TW fail chance when using improvised tools decreased. Hooray for ghetto surgery!
balance: Medibot no longer works off chems and instead performs a lesser equivalent to Tend wounds
balance: They still heal all 4 base damages and use same clothing restrictions as previously
del: Medibot Beaker Holding / Virus Treating no longer exists
add: Medibots scale with Tend Wound research (1 tend wound surgery researched = 50% more healing)
add: Medibots heal more of a specific damage if the medkit used to make them was oriented around that damage (a tox medkit medibot will heal toxin better)
tweak: Emagged Medibots now pretend to tend your wounds, actually damaging you and applying 5u chloral per step.
add: Surgery steps are now shown in detail only to the surgeon and anyone standing adjacent to them; the patient and people watching from further away get a more vague/ambiguous description.
add: Operating computers can now be built to sync with all nearby stasis beds within it's LoS and provide them with advanced surgeries.
balance: Failing TW now give 80% damage (based off normal healing) instead of flat 5 brute
add: Tend Wounds now scales with missing health!
tweak: All Tend Wound Upgrades (bar Alien Tech Combo Surgery) do same base healing but scale with missing health differently. They should all heal more than they usually do in most cases though.
code: Medibots were NOT changed and will continue to NOT scale with missing HP to make humans more desired.
add: Operation tables and stasis beds now link to operation computer when built
/:cl:

Ports: 
https://github.com/tgstation/tgstation/pull/44088 
https://github.com/tgstation/tgstation/pull/45457
https://github.com/tgstation/tgstation/pull/44483
https://github.com/tgstation/tgstation/pull/45765
https://github.com/tgstation/tgstation/pull/45773
https://github.com/tgstation/tgstation/pull/45953
https://github.com/tgstation/tgstation/pull/46139
https://github.com/tgstation/tgstation/pull/46223
https://github.com/tgstation/tgstation/pull/46319
https://github.com/tgstation/tgstation/pull/46512
https://github.com/tgstation/tgstation/pull/46976
https://github.com/tgstation/tgstation/pull/47663
https://github.com/tgstation/tgstation/pull/48859

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
Yes

**Comment by qwertyquerty** [comment]
Fix conflicts, this will have to be testmerged because I am not heavily reviewing 40 files

**Comment by VictorVow** [comment]
fugg that rebase didn't go well

**Comment by VictorVow** [comment]
Travis prefers my [new PR](https://github.com/BeeStation/BeeStation-Hornet/pull/1294)

**Pull request closed without merging**
