### PR TITLE
Improves Life again

### PR DESCRIPTION
**Pull request by ike709**
Completely untested.

### CODE REVIEW

**Comment by sheldoniscool** [comment]
👀 When whenever ike makes or is related to a pr the description is 3 words long and gives no info?

**Comment by ike709** [comment]
image

**Review by zeskorion — APPROVED** [review]
this looks good to me

**Comment by cerebral-314** [comment]
> 
> 
> 👀 When whenever ike makes or is related to a pr the description is 3 words long and gives no info?

It improves life that's literally the clearest description he could have given.
[Here's how I know](https://drive.google.com/uc?id=13inaO5ANjJoDW2GUnYeKir_XxdU9a80I)

**Comment by PowerfulBacon** [comment]
Testmerging onto sage, if there are no issues will merge

**Pull request merged**
