### PR TITLE
Makes the nuclear operative ship turrets normal instead of instakill penetrators.

### PR DESCRIPTION
**Pull request by Isy232**
## About The Pull Request

Merely changes all of the turrets on the nukie ship to normal ones. Also adds 2 more to the back in a blindspot.
image

## Why It's Good For The Game

As it is now, the nuclear operatives ship near instantly kills any non-nukies that get even remotely near it.

Its possible to land the nuclear operatives ship right next to the brig and the penetrator turrets will shoot through the glass and walls and kill everyone inside.

The ship is still powerful with normal turrets and can be landed further away from the station so it is not easy to find either.

## Changelog
:cl:
balance: Nuclear operative ship gets normal syndicate turrets instead of instakill penetrator ones.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
> As it is now, the nuclear operatives ship near instantly kills any non-nukies that get even remotely near it.

This is intentional to prevent the ship from being boarded.
If you can get on the ship, its game over for the nukies and leaving someone to defend it constantly is not fun.
The ship is intentionally overpowered specifically so that boarding it is not an option.

**Comment by PowerfulBacon** [comment]
🔑

**Comment by ghost** [comment]
This is stupid. it's intentional. just look at an average nuke round in yogstation. the nukies shuttle get maxcapped and the nuke stolen every single round. and all of this while they still have the OP turrets. imagine how easy it would be with normal turrets

**Comment by francinum** [comment]
I am actually going to have a dissenting opinion on this one.

~~The turrets were originally added to deal with the fact that the opshuttle's old, static area based destinations were getting consistently metagamed.~~ NOPE I AM WRONG THEY ARE ACTUALLY INCREDIBLY FUCKING NEW. (2019)

I still believe that getting your shuttle tracked down and raided is your own fucking fault.

**Comment by Pontenerd** [comment]
> INCREDIBLY FUCKING NEW. (2019)

Fran, that was 2 years ago

**Comment by hotimep** [comment]
don't make me feel old

**Pull request closed without merging**
