### PR TITLE
Fixes a few issues with the Tablet PDAs

### LINKED ISSUE #7904: Regular tablets get PDA programs
image

### PR DESCRIPTION
**Pull request by Bobbanz1**
## About The Pull Request
fixes #7904

Also addresses some issues that were made in the PR-Discussion channel relating to the Wiki Uplink Program. 

What this PR does in detail: 
Makes the Notepad Program undeletable and removes it from existing on the NTNet for download.

Moves the default installed PDA programs from the SSD that's installed by default on EVERY tablet, into a sub-type version that's only installed on PDAs, pAI, AIs and Cyborgs by default. 

Also moves the Wiki Uplink Program to only being installed by default on the PDA, not absolutely everything. 

## Why It's Good For The Game
Bug fixes good.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/59128051/213990241-418ad059-b4da-4d84-a375-e7c1a433e955.mp4

</details>

## Changelog
:cl:
code: Changed the default installed PDA programs to only being installed on the PDA subtype instead of the default Tablet SSD.
code: Changes the size of the Notepad to 0 and makes it undeletable and unavailable on NTNet.
code: Moves the Wiki Uplink Program to only being installed by default on the PDAs
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
Try `* fixes #1234` instead of just `fixes #1234` (closes works too)
Once it is merged, merging automatically closes the issue.

**Comment by Bobbanz1** [comment]
> Try `* fixes #1234` instead of just `fixes #1234` (`closes` works too) Once it is merged, merging automatically closes the issue.
Done

**Review by Penwin0 — DISMISSED** [review]
Looks good but testing proof would be nice

**Comment by itsmeow** [comment]
> Namely making NTMessengers require NTNet functionality to work in the first place, which they now do.

The Messaging Server should be the only determinant of PDA function. NtOS Relays are specifically not required because it runs on a different network.

**Comment by Bobbanz1** [comment]
> > Namely making NTMessengers require NTNet functionality to work in the first place, which they now do.
> 
> The Messaging Server should be the only determinant of PDA function. NtOS Relays are specifically not required because it runs on a different network.

Right well, I don't have much of an idea on how to make it require the Messaging Server in order to function and terminate the application when the Telecomms goes down so I did the next thing I could.

**Comment by itsmeow** [comment]
No, it already does. Just remove the change

**Comment by itsmeow** [comment]
The app needs to work if the server is down anyway, you wouldn't be able to view local messages otherwise.

**Comment by Bobbanz1** [comment]
> No, it already does. Just remove the change

Right, removed the change I made in that file

**Review by itsmeow — CHANGES_REQUESTED** [review]
Testing evidence

**Comment by Bobbanz1** [comment]
> Testing evidence

I have now uploaded a video showing testing evidence

**Review by itsmeow — APPROVED** [review]

**Pull request merged**
