### PR TITLE
Gygax mech costs gold instead of diamond.

### PR DESCRIPTION
**Pull request by Isy232**
## About The Pull Request

Changes the diamond cost on Gygax mech parts to gold.

## Why It's Good For The Game

Gygax mechs are far weaker than Durands because they have close to half the armor and maximum health and are only slightly faster than a Durand.

I will admit though, the special ability of the Gygax is quite good, it also does cost a lot of energy.

Gygax mechs cost 40,000 material units of diamond or 20 sheets of it which makes it even more expensive than a durand. This PR changes the diamond cost to gold, so it costs 20 units of gold. This is on top of the metal and titanium needed too.

/tg/ already did this, I would mention their PR but, well, y'now, their git did a die.

Actual stats:
Gygax:
max_integrity = 250
armor = list("melee" = 25, "bullet" = 20, "laser" = 30, "energy" = 15, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 100, "acid" = 100)

Durand:
max_integrity = 400
armor = list("melee" = 40, "bullet" = 35, "laser" = 15, "energy" = 10, "bomb" = 20, "bio" = 0, "rad" = 50, "fire" = 100, "acid" = 100)

## Changelog
:cl:
tweak: Gygax mech diamond cost changed to gold.
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
so, you're changing the only thing making gygax (a less powerful but still incredibly deadly combat mech) somewhat hard to make into a relatively easy to get mineral?

also, what's with the map changes?

**Comment by Isy232** [comment]
Wrong thing mixed in with it, removing those map changes

**Comment by Isy232** [comment]
Materials is far from the only thing making mechs hard to make, they need a lot of research, advanced weapons tech which is 20,000 points alone, then you need to research the weapons to go on the mech and you need to research the mech itself.

Then you need to print the parts to it and follow the steps to make the mech, which  I admit an experienced person can do in about 3 minutes. 

If R&D upgrades the ore silo, robotics upgrades their fabs and mining does their job you can shit out about 10 durands at least.

This PR just makes the Gygax cost less diamond and more gold so its fairly equal to the cost of a Durand.

**Comment by Isy232** [comment]
Edit, I was wrong, the Gygax costs 20 sheets of diamond at its base, again, I just changed diamond to gold so its still the same.

**Comment by MCterra10** [comment]
Honestly, if you're doing this, remove the bullshit wall crushing ability like we did downstream. Its removal was one of the only things I agreed with tg on.

**Comment by Isy232** [comment]
I mean, if you remove the speed ability this mech is utter dogshit, I could get behind nerfing its ability to remove walls and removing the stun from it being used on people in return for less power use of the ability. This mech having a bump melee stun is a bit cheap.

Or just remove the ability and make Gygax have same speed as someone not in a mech, that would also be pretty fair. I think I like this second option more but its late tonight.

**Comment by Isy232** [comment]
Closing, holy shit Gygax's are OP when used right

**Pull request closed without merging**
