### PR TITLE
Newfood: Ovens

### PR DESCRIPTION
**Pull request by Tsar-Salat**
## About The Pull Request

Ports Ovens from TG.

Ovens are a replacement for a lot of remaining microwave_results, including cakes, pizzas, and breads.

A few recipes are being adjusted so they make sense with the new system. You no longer add raw ingredients on a microwaved pizzabread to make a pizza, you now put the raw ingredients on, make the raw pizza, then put it in the oven to bake.

Several Other changes:
- New food ingredient sprites (dough, piedough, etc.)
- New Pizza sprites
- Fixed a bad recipe from griddle pr
- Reorganized kitchen icon folders & files

Ports:
- https://github.com/tgstation/tgstation/pull/60515
- https://github.com/tgstation/tgstation/pull/62538

## Why It's Good For The Game

Move the cooking medium away from overreliance on microwaves. Add more fun and depth to cooking overall.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/user-attachments/assets/bb196e93-f002-4c71-8505-aabe610c1830

</details>

## Changelog
:cl: rkz,  AMonkeyThatCodes, Kryson, Ghommie
add: Adds Ovens, a new way of cooking.
add: Does mapchanges to accommodate new oven machines
add: Converts cakes, pies, bread and pizza all to baking cook method.
rscadd: New sprites for pizza and some cooking ingredients
fix: fixes some recipes
code: kitchen icon file & folder reorg
tweak: minor repathing of knife code
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
yay

**Comment by PowerfulBacon** [comment]
The issue with DeltaStation disposals is that you moved the kitchen disposal unit outside of kitchen, so it now fails the check as its not arriving in the correct destination. Move the disposal unit to kitchen, or some other place where the chef can reasonably collect their deliveries and then add that new area to the list of disposal valid area destinations if it isn't already. Any deliveries to the kitchen will arrive in the bar, which make the chef unable to collect them since the table is in the way, meaning that they have to drag it all the way around.

**Comment by PowerfulBacon** [comment]
Will look at this at some point, have to say that the oven sprite kinda sucks though

**Comment by Tsar-Salat** [comment]
> that the oven sprite kinda sucks though

Huh? Because its big?

Its not an oven you would find in your kitchen, its more like a commercial oven you would see at a Italian Pizza joint. They are not waist-height, they are pretty big.

When Stoves are added, I will be combining these machines into one (mostly for space reasons), but hopefully that should address your misgivings.

**Review by PowerfulBacon — COMMENTED** [review]
Needs an update path for the shiv changes

**Comment by Tsar-Salat** [comment]
> Needs an update path for the shiv changes

@PowerfulBacon Done

**Review by PowerfulBacon — APPROVED** [review]

**Review by Rukofamicom — APPROVED** [review]

**Comment by ColonelOrion** [comment]
Hiya! Thanks for making this wonderful PR @Tsar-Salat ! I found out about this PR when I tried to make donuts with a microwave yesterday! Haha
The oven looks great! I have a couple points of feedback though:

1- It would be nice if the baking tray worked the same as the existing tray item, allowing rapid pickup of specific, single, or all ingredients on a tile, and rapid emptying with click/drag for more efficient unloading. Right now it is incredibly fiddly to move about my batch of prepared dough!

2- It would be nice if there was any indication of how long the oven was taking to cook something. like at least a glass front like the microwave? Right now, with lag making timing imprecise, it feels like a bit of a crapshoot.

3- This one is a bug: When the baking tray goes into the oven with stuff on it, and it's full, the oven will accept all the items on it but not the tray, leading to the tray looking like it's been left on top of the oven, but when you pick up the baking tray, the ingredients will all come with it, leaving the oven empty.

4- The recipe for the oven seems anemic. the laser makes sense, but why not a bin, too? and perhaps some wire or glass?

Again, thanks for making the PR! it's going to make the experience of baking much more rich. If you need my help with any more testing I'm happy to report back!

**Pull request merged**
