### PR TITLE
Ports wing reconstruction surgery from /tg/

### PR DESCRIPTION
**Pull request by BrumalLake**
## About The Pull Request
Ports wing reconstruction surgery, a surgery that lets you fix ruined moth wings with synthflesh
Magical heals and aheals also restore wings with this
Ports [tgstation/tgstation#51963](https://github.com/tgstation/tgstation/pull/51963)
Ports [tgstation/tgstation#55672](https://github.com/tgstation/tgstation/pull/55672)
disclaimer: I didn't test this code
Also part of Things to Port apparently

## Why It's Good For The Game
Another way to fix moth wings without stealing them from another moth and replacing them

## Changelog
:cl:
add: Ports moth wing reconstruction from tg
add: Healing moths magically restores their wings if burnt
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
alright nevermind just tried to compile and already have an undefined variable

**Comment by zeskorion** [comment]
this is not gonna work. tg moth wings arent organs- they're mutant bodyparts on moths

**Comment by Mat05usz** [comment]
Why would you not test something you port?

**Comment by BrumalLake** [comment]
> 
> 
> this is not gonna work. tg moth wings arent organs- they're mutant bodyparts on moths

well that makes this a lot more difficult and i doubt ill have time for this

**Pull request closed without merging**
