### PR TITLE
Buffs changeling combat ability + removes absorb requirements

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

- Buffs the arm blade to 30 damage, from 20
- Removes the slowdown from changeling armour (which made it pretty useless)
- Removes the toxin damage on the adrenaline, since it's just a pointless insult to the player.
- Reduces space suit slowdown to 0.1
- Removes absorb requirements

## Why It's Good For The Game

Changelings need to tools to stand on their own feet, antagonists need to be powerful so that we can tone down the number that dynamic is spawning.

Absorb requirements were just kind of silly, especially considering that antagonists have a hard time killing bystanders. I have some other ideas I want to implement with changelings, but they will take a long time and that is a much bigger project.

## Testing Photographs and Procedure

image

image

## Changelog
:cl:
balance: Changeling armblade buffed to 30 damage
balance: Changeling armor no longer slows you down
balance: Teratoma and changeling armour no longer require absorbs to use.
balance: Adds a limit of 2 living teratomas to changelings.
balance: Teratomas will now share DNA with the person that made them, which opens the way for detective work and changeling confusion counter-play.
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
If teratoma no longer requires absorbs to use that's gonna end up with them being spammed a lot more, round 50825 had a single ling spawn 19 teratomas through the shift and i saw them as a gang of five-six at one point killing everyone, to top it all since they can just go unga bunga griff chaos + dynameme antags it's a bad combination, they should be capped on how many babies there can be.

**Comment by Hardly3D** [comment]
^
It should probably work like heretic ghouls where they can only have a few living at a time, otherwise you'll be met with this
image

**Comment by TwingoI** [comment]
The combat abilities (especially the armblade) are the last thing needed to be buffed on changelings, it already isn't that hard to wipe sec with a single ling. If you want to buff them you should instead be buffing the disguise, evasion and stealth abilities, since that's what changelings are supposed to be masters of.

**Comment by PowerfulBacon** [comment]
<details>

image

image

image

</details>

**Comment by kiekatz** [comment]
to be fair regarding that one round with tomas. sec is still on the mindset that lings are those little pathetic weaklings and tomas are hardly a hazard so in the opening part they didnt take the tomas seriously. mostly ignoring or just "arresting and pr'ing them as some wierd babies..." not saying that's a bad thing it was pretty fun. but still its on them

also it was actually the space pirates who wiped out sec that shift including HOS, CE CAP and 4 officers

**Comment by PowerfulBacon** [comment]
It's always the space pirates

**Comment by Pro-gamer-window-vista10** [comment]
it was a combo i think? only like 2 officers responded on the radio and we were sort of picked off one by one because they decided to go alone

**Pull request merged**
