### PR TITLE
Greatly increases the amount of points you get from ballmer's peak

### PR DESCRIPTION
**Pull request by super12pl**
## About The Pull Request
Increases the "ballmer points"(which is the amount of points you get when you achieve the perfect peak unless im reading the code wrong) value to 2000.

## Why It's Good For The Game
Fun mechanic, should be somewhat useful.

## Changelog
:cl:
tweak: increased the reward of ballmer's peak by 39900%.
/:cl:

### CODE REVIEW

**Comment by ItsTisme** [comment]
Mechanic is the more drunk science department is the more science they do(but not too drunk)

**Comment by Raven-Industries** [comment]
for anyone confused about what the heck this is: 
image

**Comment by yyzsong** [comment]
>Captain detonates beer nuke
>science point production spikes tenfold

based and sciencepilled

**Comment by PowerfulBacon** [comment]
This happens on life not as a 1 time thing

**Pull request closed without merging**
