### PR TITLE
Ports circuits from hippie

### PR DESCRIPTION
**Pull request by MACIEKBAKI**
## About The Pull Request
ports hippie circuits, im p sure ready now
## Why It's Good For The Game
Yknow its circuits, everyone loves circuits

## Changelog
:cl:
add: ports circuits from hippie
/:cl:

### CODE REVIEW

**Comment by MACIEKBAKI** [comment]
im still adding to this dont scream at me that its incomplete

**Comment by MACIEKBAKI** [comment]
i hope it works

**Comment by MACIEKBAKI** [comment]
Oh boy thats alot of Xs

**Comment by qwertyquerty** [comment]
Are you even testing before you commit?

**Comment by MACIEKBAKI** [comment]
yeah I think I am. I mean it did compile on my end, perhaps I fricked up a commit or all of them

**Comment by MACIEKBAKI** [comment]
goteem

**Comment by Toxici11i** [comment]
you failed to compile again negro

**Comment by MACIEKBAKI** [comment]
It passed all checks didnt it?

**Comment by Toxici11i** [comment]
image

**Comment by MACIEKBAKI** [comment]
but theres a checkmark at the end

**Comment by qwertyquerty** [comment]
You managed to fix whatever the problem was, did you extensively test this?

**Comment by MACIEKBAKI** [comment]
No, not yet - I've been busy, but I have some free time now, and shall do so. I did give it a quick test earlier and found it worked
I'll look for any potential bugs and for fixes for said bugs

For the record the problem was me not editing beestation.dme so that it acknowledged the added files

**Comment by MACIEKBAKI** [comment]
For some reason I regret making this PR

**Comment by qwertyquerty** [comment]
Why

**Comment by CthulhuOnIce** [comment]
Yeah why lol

**Review by CthulhuOnIce — APPROVED** [review]
Fat

**Comment by qwertyquerty** [comment]
Kev I bet you 20 bucks you didn't clone the branch and test it

**Comment by qwertyquerty** [comment]
@MACIEKBAKI don't we need to add circuit s h i d to the maps

**Comment by catmanpop** [comment]
Isn't it craftable?

**Comment by ike709** [comment]
Time to bring back circuit labs.

**Comment by CthulhuOnIce** [comment]
@qwertyquerty it's on techweb retard bruh moment cringe normie

**Comment by catmanpop** [comment]
On most stations, there is a room you can use, its the firing range thing

**Comment by CthulhuOnIce** [comment]
not this one

**Comment by MACIEKBAKI** [comment]
I wont add a circuit room to the map due to Kevs bitching

**Comment by MACIEKBAKI** [comment]
Btw if you find any bugs then bug me about it no pun intended so I can possibly fix them

**Comment by MACIEKBAKI** [comment]
merge this already

**Comment by MACIEKBAKI** [comment]
Debonaircorsiar gave me some feed back and hey mentioned circuit cloning, from what I see its enabled in the config, I dont think the circuit removal touched that so I won't add anything regarding that.  Its
>#IC_PRINTING

by the way

**Review by qwertyquerty — APPROVED** [review]

**Pull request merged**
