### PR TITLE
Removes away missions

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
Removes away missions from the game. The gateway remains but does not activate without admin intervention. Also, removes the  deepstorage space ruin, because it was full of away mission stuff and no one used it anyway.

## Why It's Good For The Game
These have been unsupported, unmaintained, and unused for years. They straight up didn't work for the past year and no one noticed.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

The things I expected to break (CTF, Error Room, Exile Implants) still work.

image

</details>

## Changelog
:cl:
del: Away missions have been removed.
del: The deepstorage space ruin has been removed.
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
For "they didn't work for the past year" what do you mean? Say if an admin wanted to spawn one something wacky happened? I'm certain we just disabled them because they were broken(in the sense of balancing, completion, op stuff, etc)  but they were still on the code for an admin to use for special events or bus(which iirc i saw 2 or 3 times)

**Comment by Ivniinvi** [comment]
> For "they didn't work for the past year" what do you mean? Say if an admin wanted to spawn one something wacky happened? I'm certain we just disabled them because they were broken(in the sense of balancing, completion, op stuff, etc) but they were still on the code for an admin to use for special events or bus(which iirc i saw 2 or 3 times)

The admin spawn button was broken between #5695 and #8446.

**Review by PestoVerde322 — DISMISSED** [review]
Code and the maps (or rather the lack of in this case) seems a-ok to me, Approved.

However, I can't shake the feel that also some space exploration maps are currently unused, which is pretty much anything under RandomRuins/SpaceRuins, which afaik is pretty much legacy content; so unless i'm wrong, i'd say also check those in a later date.

Edit: in fact, there's an error related to some away mission content being removed from one map which is, in fact, under said folder.

**Comment by Fronsis** [comment]
> Code and the maps (or rather the lack of in this case) seems a-ok to me, Approved.
> 
> However, I can't shake the feel that also some space exploration maps are currently unused, which is pretty much anything under RandomRuins/SpaceRuins, which afaik is pretty much legacy content; so unless i'm wrong, i'd say also check those in a later date.

I wouldn't personally agree about removing the old space ruins, in fact some of them are iconic and are not as broken compared to the mess of away mission, having visited most of them at best some of them are missing a cryopod-spawner, etc but alas that discussion is for another PR if it happens since i have some arguments about it.

Though the gateway idea is nice these ruins have been broken since forever(the plasmaflood atmos planet lmao) and i don't think /tg/ ever did a fix to port that would be worth it compared to the removal

**Comment by Nosnek199** [comment]
Deep Storage is nice to find, though. is there any way that it can remain without the "away mission" stuff?

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
Stale for extended period of time. Ping on discord for reopen.

**Pull request closed without merging**
