### PR TITLE
Xenolings are back + a nerf.

### PR DESCRIPTION
**Pull request by Moccha-Bee**
## About The Pull Request
Readds Xenolings to xenobiology and they come with a nerf, xenolings can't gain dna points form absorbing other xenolings pretty much making them hunter dogs for real lings. The only reason they were removed in the first place was that along time ago lings were broken as fuck, and could kill the entire station, now they are "stealth" antags who are weak as shit and can be easily cucked, literally no one fears lings anymore lol. The point of this pr is to bring xenolings back allowing skillful traitor xenobiologists, trade 50 minutes of build-up aka getting gold and rainbow slimes in exchange for a chance to getting ling. Or for xenobiologists to go ling hunting. 

Also remember that getting xenoling is pretty much going to cost you an entire shift since it's behind multiple layers of rng + risks to get it. And you won't ever see them in lrp since rounds end in 30 minutes lol, and in mrp even less since people there don't know how to xenobio and rounds generally end at the one hour mark.

https://www.youtube.com/watch?v=WzfFdHUg-78

## Why It's Good For The Game
Xenolings are always fun, and are stacked up upon multiple layers of rng, making them very hard to get and very dangerous as well since they are present in the golden slime hostile pool, meaning that the scientist needs to kill a bunch of hostile mobs first before getting the headslug.

## Changelog
:cl:
add: Added xenolings back
nerfed: xenolings so they won't be able to get dna points from absorbing other xenolings.
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
Yes

**Comment by Moccha-Bee** [comment]
Also i know that somewhere in da code, xenolings started with 3 dna points instead of 10 so i'm also adding that

**Comment by zeskorion** [comment]
stop opening xenoling prs

**Comment by Moccha-Bee** [comment]
> stop opening xenoling prs

Just you wait 😏

**Comment by qwertyquerty** [comment]
Why are we insta closing this

**Comment by Effemu** [comment]
me when zesko said xenolings will return after ling ban :vibecheck:

**Comment by zeskorion** [comment]
> Why are we insta closing this

because we've been doing that for xenoling prs. we've already established that there won't be any xenoling shit, ever. it's not an intended feature and only encourages shittery.

**Comment by Moccha-Bee** [comment]
> > Why are we insta closing this
> 
> because we've been doing that for xenoling prs. we've already established that there won't be any xenoling shit, ever. it's not an intended feature and only encourages shittery.

Same for all the shit you ever added to virology. And your only reasoning for removing xenolings was "xenobiology is too powerful and i'm going to nerf that shit", besides that you said it yourself only way xenolings are coming back is after a ling nerf. Lings have been nerfed and here i am nerfing them as well.

**Comment by TeomanTheGreat** [comment]
zesko just doesn't want another department to compete with the powergame of viro. soon he will go for the rest of xenobio.

**Comment by qwertyquerty** [comment]
See above, leaving this open for further input

**Comment by zeskorion** [comment]
> > > Why are we insta closing this
> > 
> > 
> > because we've been doing that for xenoling prs. we've already established that there won't be any xenoling shit, ever. it's not an intended feature and only encourages shittery.
> 
> Same for all the shit you ever added to virology. And your only reasoning for removing xenolings was "xenobiology is too powerful and i'm going to nerf that shit", besides that you said it yourself only way xenolings are coming back is after a ling nerf. Lings have been nerfed and here i am nerfing them as well.

the ling nerf is not sufficient to justify adding xenolings. being able to call revive() on yourself alone is a fucking huge power- lings cannot die unless people know they are a ling and intentionally kill them. way more than anything any other stationside job can get

**Comment by Moccha-Bee** [comment]
> > > > Why are we insta closing this
> > > 
> > > 
> > > because we've been doing that for xenoling prs. we've already established that there won't be any xenoling shit, ever. it's not an intended feature and only encourages shittery.
> > 
> > 
> > Same for all the shit you ever added to virology. And your only reasoning for removing xenolings was "xenobiology is too powerful and i'm going to nerf that shit", besides that you said it yourself only way xenolings are coming back is after a ling nerf. Lings have been nerfed and here i am nerfing them as well.
> 
> the ling nerf is not sufficient to justify adding xenolings. being able to call revive() on yourself alone is a fucking huge power- lings cannot die unless people know they are a ling and intentionally kill them. way more than anything any other stationside job can get

Bullshit lol, you can revive yourself as a slime person. And the regeneration stasis from virology also gives the death gasp which for anyone around you makes you seem dead while regenerating your body. There is also revivers from medbay which revive you 😳

**Comment by qwertyquerty** [comment]
I agree with moccha here

**Comment by zeskorion** [comment]
> > > > > Why are we insta closing this
> > > > 
> > > > 
> > > > because we've been doing that for xenoling prs. we've already established that there won't be any xenoling shit, ever. it's not an intended feature and only encourages shittery.
> > > 
> > > 
> > > Same for all the shit you ever added to virology. And your only reasoning for removing xenolings was "xenobiology is too powerful and i'm going to nerf that shit", besides that you said it yourself only way xenolings are coming back is after a ling nerf. Lings have been nerfed and here i am nerfing them as well.
> > 
> > 
> > the ling nerf is not sufficient to justify adding xenolings. being able to call revive() on yourself alone is a fucking huge power- lings cannot die unless people know they are a ling and intentionally kill them. way more than anything any other stationside job can get
> 
> Bullshit lol, you can revive yourself as a slime person. And the regeneration stasis from virology also gives the death gasp which for anyone around you makes you seem dead while regenerating your body. There is also revivers from medbay which revive you 😳

regenerative coma is a stupid fucking symptom, which is overrated, and i fucking hate it. make a pr to remove it and ill put that shit to vote no problem

but self revival from everything short of gibbing? naah

**Comment by Effemu** [comment]
zesko why do you hate fun

**Comment by Moccha-Bee** [comment]
> > > > > > Why are we insta closing this
> > > > > 
> > > > > 
> > > > > because we've been doing that for xenoling prs. we've already established that there won't be any xenoling shit, ever. it's not an intended feature and only encourages shittery.
> > > > 
> > > > 
> > > > Same for all the shit you ever added to virology. And your only reasoning for removing xenolings was "xenobiology is too powerful and i'm going to nerf that shit", besides that you said it yourself only way xenolings are coming back is after a ling nerf. Lings have been nerfed and here i am nerfing them as well.
> > > 
> > > 
> > > the ling nerf is not sufficient to justify adding xenolings. being able to call revive() on yourself alone is a fucking huge power- lings cannot die unless people know they are a ling and intentionally kill them. way more than anything any other stationside job can get
> > 
> > 
> > Bullshit lol, you can revive yourself as a slime person. And the regeneration stasis from virology also gives the death gasp which for anyone around you makes you seem dead while regenerating your body. There is also revivers from medbay which revive you 😳
> 
> regenerative coma is a stupid fucking symptom, which is overrated, and i fucking hate it. make a pr to remove it and ill put that shit to vote no problem
> 
> but self revival from everything short of gibbing? naah

Lings when husked can't revive, same applies to xenolings. Besides you made lings weak as fuck yourself. And self reviving has been a thing for other departments for a long time. And since your only point against is "it can revive itself after death, too op remove" would also mean you would have to remove revivers from medbay and robotics, with the ability to make clones of yourself as slime person.

**Comment by zeskorion** [comment]
> > > > > > > Why are we insta closing this
> > > > > > 
> > > > > > 
> > > > > > because we've been doing that for xenoling prs. we've already established that there won't be any xenoling shit, ever. it's not an intended feature and only encourages shittery.
> > > > > 
> > > > > 
> > > > > Same for all the shit you ever added to virology. And your only reasoning for removing xenolings was "xenobiology is too powerful and i'm going to nerf that shit", besides that you said it yourself only way xenolings are coming back is after a ling nerf. Lings have been nerfed and here i am nerfing them as well.
> > > > 
> > > > 
> > > > the ling nerf is not sufficient to justify adding xenolings. being able to call revive() on yourself alone is a fucking huge power- lings cannot die unless people know they are a ling and intentionally kill them. way more than anything any other stationside job can get
> > > 
> > > 
> > > Bullshit lol, you can revive yourself as a slime person. And the regeneration stasis from virology also gives the death gasp which for anyone around you makes you seem dead while regenerating your body. There is also revivers from medbay which revive you 😳
> > 
> > 
> > regenerative coma is a stupid fucking symptom, which is overrated, and i fucking hate it. make a pr to remove it and ill put that shit to vote no problem
> > but self revival from everything short of gibbing? naah
> 
> Lings when husked can't revive, same applies to xenolings. Besides you made lings weak as fuck yourself. And self reviving has been a thing for other departments for a long time. And since your only point against is "it can revive itself after death, too op remove" would also mean you would have to remove revivers from medbay and robotics, with the ability to make clones of yourself as slime person.

reviver implants don't revive you back from death. Slime person cloning is something i've been planning on fucking with for a long while (capped clones, range limit)

**Comment by Moccha-Bee** [comment]
> > > > > > > > Why are we insta closing this
> > > > > > > 
> > > > > > > 
> > > > > > > because we've been doing that for xenoling prs. we've already established that there won't be any xenoling shit, ever. it's not an intended feature and only encourages shittery.
> > > > > > 
> > > > > > 
> > > > > > Same for all the shit you ever added to virology. And your only reasoning for removing xenolings was "xenobiology is too powerful and i'm going to nerf that shit", besides that you said it yourself only way xenolings are coming back is after a ling nerf. Lings have been nerfed and here i am nerfing them as well.
> > > > > 
> > > > > 
> > > > > the ling nerf is not sufficient to justify adding xenolings. being able to call revive() on yourself alone is a fucking huge power- lings cannot die unless people know they are a ling and intentionally kill them. way more than anything any other stationside job can get
> > > > 
> > > > 
> > > > Bullshit lol, you can revive yourself as a slime person. And the regeneration stasis from virology also gives the death gasp which for anyone around you makes you seem dead while regenerating your body. There is also revivers from medbay which revive you 😳
> > > 
> > > 
> > > regenerative coma is a stupid fucking symptom, which is overrated, and i fucking hate it. make a pr to remove it and ill put that shit to vote no problem
> > > but self revival from everything short of gibbing? naah
> > 
> > 
> > Lings when husked can't revive, same applies to xenolings. Besides you made lings weak as fuck yourself. And self reviving has been a thing for other departments for a long time. And since your only point against is "it can revive itself after death, too op remove" would also mean you would have to remove revivers from medbay and robotics, with the ability to make clones of yourself as slime person.
> 
> reviver implants don't revive you back from death. Slime person cloning is something i've been planning on fucking with for a long while (capped clones, range limit)

Reviver implants act as defribilators, if you have nanites + revivers (nanites are avaible every single round in mrp since people build a public chamber infront of medbay) so it virtually allows people to come back from the dead. 

Edit: There is also nanites that allow you revive.

**Comment by Blueturbo47** [comment]
> > > > > > > > > Why are we insta closing this
> > > > > > > > 
> > > > > > > > 
> > > > > > > > because we've been doing that for xenoling prs. we've already established that there won't be any xenoling shit, ever. it's not an intended feature and only encourages shittery.
> > > > > > > 
> > > > > > > 
> > > > > > > Same for all the shit you ever added to virology. And your only reasoning for removing xenolings was "xenobiology is too powerful and i'm going to nerf that shit", besides that you said it yourself only way xenolings are coming back is after a ling nerf. Lings have been nerfed and here i am nerfing them as well.
> > > > > > 
> > > > > > 
> > > > > > the ling nerf is not sufficient to justify adding xenolings. being able to call revive() on yourself alone is a fucking huge power- lings cannot die unless people know they are a ling and intentionally kill them. way more than anything any other stationside job can get
> > > > > 
> > > > > 
> > > > > Bullshit lol, you can revive yourself as a slime person. And the regeneration stasis from virology also gives the death gasp which for anyone around you makes you seem dead while regenerating your body. There is also revivers from medbay which revive you 😳
> > > > 
> > > > 
> > > > regenerative coma is a stupid fucking symptom, which is overrated, and i fucking hate it. make a pr to remove it and ill put that shit to vote no problem
> > > > but self revival from everything short of gibbing? naah
> > > 
> > > 
> > > Lings when husked can't revive, same applies to xenolings. Besides you made lings weak as fuck yourself. And self reviving has been a thing for other departments for a long time. And since your only point against is "it can revive itself after death, too op remove" would also mean you would have to remove revivers from medbay and robotics, with the ability to make clones of yourself as slime person.
> > 
> > 
> > reviver implants don't revive you back from death. Slime person cloning is something i've been planning on fucking with for a long while (capped clones, range limit)
> 
> Reviver implants act as defribilators, if you have nanites + revivers (nanites are avaible every single round in mrp since people build a public chamber infront of medbay) so it virtually allows people to come back from the dead.
> 
> Edit: There is also nanites that allow you revive.

wow, this is getting to be a long message, also before zesk keeps getting his feeling hurt why don't we just vote on it.

**Comment by ItsTisme** [comment]
I can agree xeno lings are OP. But for the hoops you have to jump trough to get them your either extremly lucky or its well deserved. Many other departments have these OP abilitys if you spend autistic amount of time to get it done

**Comment by Archanial** [comment]
this is so cringe
grudge against lings is real bruh

**Comment by WhyIsCaeciliusTaken** [comment]
Complaining about xenobio getting something that calls revive() when they already have items that do so that they can get in half the time, that also autoactivate on crit, have no cooldown and teleport to back to xenobio is a pretty dumb argument.

That said, xenolings are incredibly stronk, and may need additional nerfs to be balanced.

**Comment by VictorVow** [comment]
> The point of this pr is ... for xenobiologists to go ling hunting.

And why is encouraging scientists going validhunting supposed to be a good thing?

**Comment by Moccha-Bee** [comment]
> > The point of this pr is ... for xenobiologists to go ling hunting.
> 
> And why is encouraging scientists going validhunting supposed to be a good thing?

You realize that all the other departments get incentives to validhunt as well? Medbay can make syringe guns that can act like killer queen and blow up antags on the spot, cargo can buy a wide array of weapons and protecting gear. And science already has other incentives to go validhunting, so unless you want remove them all complaining about it here won't change anything.

**Comment by PowerfulBacon** [comment]
The problem I have with this PR isn't that they are being brought back, it's that xenolings have almost no utility potential outside of combat, and are entirely build to kill and validhunt other changelings / antagonists, which isn't something that we particularly want to be encouraging.
I would totally be happy with some kind of lesser species that has healing, but in the state that they are they really shouldn't be just a big time to unga bunga in the heads of the valids.
Leaving open for some further discussion.
I think a good point to go for would be to give them no genetic points when they transform, or be given random abilities from the pool of something like fleshmend, cure radiation etc.

**Comment by ghost** [comment]
> The problem I have with this PR isn't that they are being brought back, it's that xenolings have almost no utility potential outside of combat, and are entirely build to kill and validhunt other changelings / antagonists, which isn't something that we particularly want to be encouraging.
> I would totally be happy with some kind of lesser species that has healing, but in the state that they are they really shouldn't be just a big time to unga bunga in the heads of the valids.
> Leaving open for some further discussion.
> I think a good point to go for would be to give them no genetic points when they transform, or be given random abilities from the pool of something like fleshmend, cure radiation etc.

Remove nanites, since they can also bring you back from death and also give you armor and also heal you

**Comment by VictorVow** [comment]
> You realize that all the other departments get incentives to validhunt as well? 

No. They get generic items that can be used for antag purposes. Xenoling on the other hand has an ability which allows you to **immediately find the stealthiest antag in the game**, with no drawbacks and for all existing antags of that type. That is not comparable to buying gun crates. 

> I would totally be happy with some kind of lesser species that has healing, but in the state that they are they really shouldn't be just a big time to unga bunga in the heads of the valids.

Some new slimeperson race which gets higher healing in light than plantpeople do perhaps.

**Comment by PowerfulBacon** [comment]
Alright, we talked in discord for a while and on this PR comments, in it's current state I dont think it is reasonable really and would need changes to the point where they aren't even Lings anymore to be reasonable. Closing

**Comment by Flakkyboo** [comment]
Xeno headslugs instead 😳

**Comment by Moccha-Bee** [comment]
> The problem I have with this PR isn't that they are being brought back, it's that xenolings have almost no utility potential outside of combat, and are entirely build to kill and validhunt other changelings / antagonists, which isn't something that we particularly want to be encouraging.

That's a structural problem with any department that has any access to tools that can kill other players, the worst excesses being cargo and science. And you can already get ling or 

> Alright, we talked in discord for a while and on this PR comments, in it's current state I dont think it is reasonable really and would need changes to the point where they aren't even Lings anymore to be reasonable. Closing

Zesko is already removing the only other way you can become a xenoling, all this pr does is replace that with a more rng focused method to getting one.

**Comment by dinnerwoerror** [comment]
balancing something that's obscenely overpowered by making it incredibly rare doesn't actually balance it
just look at the space ninja

**Comment by Blueturbo47** [comment]
> balancing something that's obscenely overpowered by making it incredibly rare doesn't actually balance it
> just look at the space ninja

The pr doesn't just make it rare but decreases the amount of dna points, and making something rare does make it less powerful because the later in the shift the more powerful crew is. And space ninja is meant to be powerful because it is a hard midround antag hired by the syndicate as a family of mercenaries while changeling is just a parasite that got lucky and is trying to survive.

**Pull request closed without merging**
