### PR TITLE
Removes unused armor flag

### PR DESCRIPTION
**Pull request by Tsar-Salat**
## About The Pull Request

Removes an unused armor flag, MAGIC, and all its references. No armor in the game actually uses it.

To nip it in the bud before someone says it as goofball says it on the TG pr, but all magic proj that even interact with mobs already have 100 armor_penetration, so uhhh... this flag is still useless.

Credit goes to JohnFulpWillard. I found his PR when making a branch for armor subtyping:
- https://github.com/tgstation/tgstation/pull/62594

## Why It's Good For The Game

This fooled me when I converted armor strings to defines, and it seemingly fooled bacon when he refactored armor tag listings

One less armor to worry about

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

There is no way to meaningfully test it. Its bloatcode from some pre-bee refactor or project that never got finished.

Heres some testing evidence to show I give a damn though, I guess. Not sure what else to put.

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/e11cf87d-f610-4a12-b532-68969a91b80a

I guess armor would bug the fuck out and not display in a list if I wrote the args wrong? idk 

Screenshot 2024-05-29 231805

</details>

## Changelog
:cl: rkz, Johnfulpwillard
code: removes an unused armor flag. Not player-facing
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
Semi-addressing #10967, by way of unused define removal (Though he spells armor it wrong there hehe :3 )

**Comment by PowerfulBacon** [comment]
Is no armour even ever given this stat at all?

**Comment by Tsar-Salat** [comment]
> Is no armour even ever given this stat at all?

Nope! Just given to projectiles.

**Review by PestoVerde322 — APPROVED** [review]
Seems all good, unused thing gone good, surprisingly there's not many mentions of this armor flag; approved.

**Comment by PowerfulBacon** [comment]
oh actually this will conflict with my TM in an annoying way, will hold for a bit until I got that branch up

**Comment by EvilDragonfiend** [comment]
Putting DNM flag for Bacon just in case to prevent blind merge

**Comment by Rukofamicom** [comment]
Update and ping for merge when it is.

**Comment by Tsar-Salat** [comment]
@Rukofamicom

**Review by Rukofamicom — APPROVED** [review]

**Pull request merged**
