### PR TITLE
Datum-based poll creation and vote handling

### PR DESCRIPTION
**Pull request by ike709**
https://github.com/tgstation/tgstation/pull/50843

Crossed asked me to port it. DNM until he tests it.

I haven't personally tested it since I don't have a DB setup.

🆑
add: haha poll go brrrr
/🆑

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
The UI is kind of confusing, and the buttons are in different areas when associated with each other
image

Polls do not show up in the manager, and only show up for a split second on the main menu for me too.

```
proc name: poll parse href (/datum/admins/proc/poll_parse_href)
usr: PowerfulBacon/(PowerfulBacon)
usr.loc: (start area (8, 174, 1))
src: powerfulbacon\'s admin datum (... (/datum/admins)
call stack:
powerfulbacon\'s admin datum (... (/datum/admins): poll parse href(/list (/list), /datum/poll_question (/datum/poll_question))
powerfulbacon\'s admin datum (... (/datum/admins): Topic("admin_token=[redacted]...", /list (/list))
PowerfulBacon (/client): Topic("admin_token=[redacted]...", /list (/list), powerfulbacon\'s admin datum (... (/datum/admins))
PowerfulBacon (/client): Topic("admin_token=[redacted]...", /list (/list), powerfulbacon\'s admin datum (... (/datum/admins))
PowerfulBacon (/client): Topic("admin_token=[redacted]...", /list (/list), powerfulbacon\'s admin datum (... (/datum/admins))
```

Selecting None as the minimum play time creates this error:
```
[2020-06-16 16:32:44.407] SQL: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' minimumplaytime' at line 1 | Query used: SELECT id, polltype, starttime, endtime, question, subtitle, adminonly, multiplechoiceoptions, dontshow, allow_revoting, IF(polltype='TEXT',(SELECT COUNT(ckey) FROM SS13_poll_textreply AS t WHERE t.pollid = q.id AND deleted = 0), (SELECT COUNT(DISTINCT ckey) FROM SS13_poll_vote AS v WHERE v.pollid = q.id AND deleted = 0)), IFNULL((SELECT byond_key FROM SS13_player AS p WHERE p.ckey = q.createdby_ckey), createdby_ckey), IF(starttime > NOW(), 1, 0) FROM SS13_poll_question AS q WHERE NOW() < endtime AND deleted = 0, minimumplaytime
```

**Review by Crossedfall — CHANGES_REQUESTED** [review]
Runtimes during testing and UI changes needed. Provided logs in discord.

**Comment by ike709** [comment]
image

**Review by Crossedfall — APPROVED** [review]
DB changes applied, everything looks good in staging.

**Pull request merged**
