### PR TITLE
Pet holding update + Walter

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Ports: 
https://github.com/tgstation/tgstation/pull/53148
https://github.com/tgstation/tgstation/pull/53609
https://github.com/tgstation/tgstation/pull/49439

You can now scoop and hold pets (and pais).
Bullterriers and breadcats now exist.
Warden has new pet - Walter.

## Why It's Good For The Game

They look cool, warden has a real pet (sorry McGriff) and holding pets is cool.

## Changelog
:cl:
add: Bullteriers!
add: Breadcats! Ask your local chef for one!
add: You can now scoop and hold pets.
add: Warden has a new pet - Walter!
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
known issues: bullteriers don't have collar sprite

**Comment by TeomanTheGreat** [comment]
Walter

**Comment by ToasterBan** [comment]
you cant just add walter and not add firetruck and monster truck

**Comment by eeSPee** [comment]
> Walter
> 

Firetrumk

**Review by qwertyquerty — CHANGES_REQUESTED** [review]
Replace the removed items in metastation

**Review by qwertyquerty — CHANGES_REQUESTED** [review]
Fix PAI conflicts

**Comment by Archanial** [comment]
that should do it?

**Review by qwertyquerty — APPROVED** [review]
walter

**Pull request merged**
