### PR TITLE
Tripled the amount of starting monkeys in jungle fever

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
I'm not maintaining this gamemode but this single character change should somewhat help the rounds ending in less than 5 minutes.

## Why It's Good For The Game
EEEEEEEEE EEE EEE

## Changelog
:cl:
balance: Tripled the amount of starting monkeys in Jungle Fever
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
The reason why monkeys get utterly destroyed every round is because of wall slams, tripling monkeys won't have much of an effect I'm afraid.

**Comment by zeskorion** [comment]
i was gonna do something that fixes them up a litttle bit, but this wont hurt

**Comment by 4rchibald** [comment]
@zeskorion No idea what changes you got in mind but once you're working on jungle fever could you implement similar thing that is in revolution that treats rev heads (in our case that would be monkified people) as dealt with not only when they die but also when they leave stations z level? Since that thing exists in other gamemode that shouldn't be hard to add but in theory it would allow us to have other way to deal with problem than just killing monkeys, maybe even would divide crew for people killing monkeys on sight and others pulling them away only to send them to lavaland, through gateway or take to some construction in space to exile them

**Comment by zeskorion** [comment]
> @zeskorion No idea what changes you got in mind but once you're working on jungle fever could you implement similar thing that is in revolution that treats rev heads (in our case that would be monkified people) as dealt with not only when they die but also when they leave stations z level? Since that thing exists in other gamemode that shouldn't be hard to add but in theory it would allow us to have other way to deal with problem than just killing monkeys, maybe even would divide crew for people killing monkeys on sight and others pulling them away only to send them to lavaland, through gateway or take to some construction in space to exile them

monkeys are hard to space and easy to kill

**Comment by 4rchibald** [comment]
@zeskorion Yeah, I imagine that it would be barely used, even with revs it happens very rarely that someone leaves the station but the fact that it is a possibility may divide crew and at least cause some to try catching them or at least argue with captain and security about that. I have no idea how complex and hard to implement that change would be (as posted before since it already exists in revs mode I believe it shouldn't be that hard since the code is there) but I think that would be a good change since it allows for some variability in how this round at least in theory can play out

**Pull request merged**
