### PR TITLE
Nanite Program Hub UI Improvement

### PR DESCRIPTION
**Pull request by jlsnow301**
Co-Authored-By: St0rmC4st3r <34888552+St0rmC4st3r@users.noreply.github.com>

## About The Pull Request
By suggestion.
Old tabs
Imgur img
New tabs
Imgur img
New compact screen
Imgur img

The interface receives some other upgrades:
- the actual nanite details list is now fixed height and scollable so you don't have to leave the tabs to see the bottom of the screen
- the loaded disk description is now a set height so that the rest of the screen isn't moving when you change programs/disks
- it is also overflow scrollable in the edge case that someone uploads a disk with an extremely verbose description
- compact view now uses margins
- ~~most buttons are now larger for the easy clicky-clicky~~
(updates after 01-17):
- now properly reads "no program installed" when you press the delete program button
- compact view now has dividers for easier viewing
- eject and delete program buttons are now disabled when there is no disk and/or no program

## Why It's Good For The Game
nanite screen was a little difficult to use, blank tabs aren't ideal really

## Changelog
:cl:
tweak: Nanite program UI is made easier to use.
/:cl:

### CODE REVIEW

**Comment by jlsnow301** [comment]
Small change coming to this later today

**Comment by jlsnow301** [comment]
Ok. Logic was a bit strange on the disk contents. Deleting a program with the disk in would cause it to blank the name and description but not display "no program installed". This has been fixed, although I'm not super proud how I did it.

The buttons for ejecting and deleting a program are no longer infinitely clickable, and should disable when there isn't a disk to eject, no program to delete, etc.

The compact list is now a bit better thanks to @stylemistake with the hint on dividers.

**Comment by PowerfulBacon** [comment]
The double height buttons look kind of ugly

**Comment by jlsnow301** [comment]
> The double height buttons look kind of ugly

adjusted 

Imgur img

**Review by utilbird — DISMISSED** [review]

**Comment by stylemistake** [comment]
This layout is cringe and full of hacks. E.g:

- You should not put various elements directly into Flex, they should follow this hierarchy: Flex > Flex.Item > Button
- Putting a redundant Flex in Button when it has an "icon" string prop.
- Setting width/height to constant %-based values instead of using grow, etc.

It's the reason why it looked so janky in the first place, throwing in more width/height hacks won't fix the root problem.

**Comment by jlsnow301** [comment]
> * You should not put various elements directly into Flex, they should follow this hierarchy: Flex > Flex.Item > Button

i'll try to work these out but often I have issues with scaling
> * Putting a redundant Flex in Button when it has an "icon" string prop.

did this to add margin to the icon, which I don't think is natively possible
> * Setting width/height to constant %-based values instead of using grow, etc.

will resolve
> It's the reason why it looked so janky in the first place, throwing in more width/height hacks won't fix the root problem.

i think previously the code looked "okay" but it didn't translate to being really usable

**Comment by jlsnow301** [comment]
actually just readding the icon and label into the buttons would remove the extra usage of flex but it will look quite different

**Comment by stylemistake** [comment]
Use `<Button fluid>`, also why do you even need to right-align text on buttons

**Comment by jlsnow301** [comment]
> Use `<Button fluid>`, also why do you even need to right-align text on buttons

it looked more like labels

**Comment by jlsnow301** [comment]
few of the issues I was having in using grow:
Imgur img
1. couldnt widen buttons
2. this expands with the loaded program description, causing it to clip
 2a. the buttons also were not fixed, widening based on selected label
3. wanted this locked so that scrolling would not move the rest off screen, as seen here
Imgur img

**Comment by jlsnow301** [comment]
without height and width props:

**Comment by stylemistake** [comment]
Ask for someone to port tgui 4.3, then you'll have a straight path to making nice looking scrollable sections, see here: https://github.com/tgstation/tgstation/blob/2b4dcafbee068d376ae69bf6606b736b7cabb968/tgui/packages/tgui/interfaces/FishCatalog.js#L28-L70

You can still try this approach in your UI, but with Flex instead of Stack, and with added margins. Looks like this:

image

**UPD:** Oh, but since you'll have two nested sections (Program list section -> Program entry section) you'll have a bug that makes the inner section inherit the scrollbar from a parent section. There is an easy fix for it, though.

**Comment by jlsnow301** [comment]
> You can still try this approach in your UI, but with Flex instead of Stack, and with added margins. Looks like this:

this is ideally what I was looking for, tyty. also looking at this makes me want to refactor it now

**Comment by stylemistake** [comment]
```
<Stack fill> == <Flex height="100%">
<Stack vertical> == <Flex direction="column">
```

**Comment by jlsnow301** [comment]
This has been entirely refactored but some of the same css bugs persist, so I'm circumventing them with static height props.

**Comment by jlsnow301** [comment]
lol

**Pull request closed without merging**
