### PR TITLE
Echo fixes 2

### PR DESCRIPTION
**Pull request by BriggsIDP**
## About The Pull Request

Fixes some issues with echo and adds a a little polish.
Changes SM piping and atmos piping, moves the atmos tube closer to entrance and separates it from engi more, adds more glass walk ways, adds a shuttle maker on the surface with explo remains, allows shuttles to be made on the surface, acting like a drydock, and moves some areas around.

Also adds a lone_ops spawner landmark that takes precedent over the carp spawner!

## Why It's Good For The Game

people asked me to fix them

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
add: [echo] adds more glass to echo.
add: [echo] adds ai foamers to echo.
add: [echo] adds a DIY Explo crash site to echo's surface. Make your own shuttle!
change: [echo] fixes some issues with engi on echo.
add: [echo] adds solar panels to echo surface .
add: [echo] You can now build shuttles on echo's surface!
fix: [echo] lone-ops will no longer spawn in and ganked by carp
/:cl:

### CODE REVIEW

**Comment by ClownMoff** [comment]
imagen

Why is this here

**Comment by Therealdoooc213** [comment]
The walkway that goes over the holodeck needs corner railing pieces, it looks strange

**Comment by BriggsIDP** [comment]
> The walkway that goes over the holodeck needs corner railing pieces, it looks strange

not possible unless i change the side the railing is on, but i might!


> imagen
> 
> Why is this here

it's cute and easy to remove

**Review by Rukofamicom — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
image

Is this meant to serve as the public garden?

**Review by PowerfulBacon — APPROVED** [review]

**Comment by BriggsIDP** [comment]
> image
> 
> Is this meant to serve as the public garden?

It's more of a bandage fix for a complaint from botany player about the lack of hydroponics. That room is basically a copy of a random maint that can generate i've just opted to make it permanent, but i see no reason why it could not be used a public garden!

**Comment by PowerfulBacon** [comment]
Sure, I guess thats fine

**Pull request merged**
