### PR TITLE
Makes abductors slightly less frequent

### PR DESCRIPTION
**Pull request by Megaddd**
## About The Pull Request

Reduces the frequency of abductors butting into every other round.

## Why It's Good For The Game

Abductors are frustratingly common, this makes them slightly less so.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

N/A

</details>

## Changelog
:cl:
config: slightly reduced abductor spawn rate
/:cl:

### CODE REVIEW

**Comment by mcmeiler** [comment]
...PR template?

**Comment by EvilDragonfiend** [comment]
you need to write a change log anyways.

**Comment by Megaddd** [comment]
babbis' first PR. Vscode just made a blank PR and changed vscode settings by itself for some reason 🙃

**Comment by Oscari-pog** [comment]
Just for reference
This decreases their weight by 1/4, and ups the amount of minimum players to 24.

Not criticism, just pointing out.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
