### PR TITLE
silicons are now less suffered from stating laws spam

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
silicons are now less suffered from stating laws spam

## Why It's Good For The Game
stating laws isn't spam, but the game thinks it's spam. This PR fixes it.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

tried with `spam count = 0` thing, and stating laws spam was possible.
This PR didn't bring `count = 0`, instead it minuses by -1.

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
add: silicons no longer can state laws while they're stating laws.
fix: stating laws counts to the spam filter less than before. But do not spam stating laws, it still counts, but less.
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
I have no idea why it fails the check

**Comment by ivanmixo** [comment]
I don't think this is the way to do it. Make the filter not care about forced speech properly instead of making this very specific bandaid.

**Comment by EvilDragonfiend** [comment]
> I don't think this is the way to do it. Make the filter not care about forced speech properly instead of making this very specific bandaid.

checking forced say exists in say proc, but if I implement it into forced_say_stating_laws, it will remove how to mute them when they're going crazy. I have not that better idea for now.
Because **this isn't forced speech at all.**

**Review by PowerfulBacon — APPROVED** [review]

**Comment by ivanmixo** [comment]
Painful pain pain

**Pull request merged**
