### PR TITLE
Updated RD cloak sprite

### PR DESCRIPTION
**Pull request by Naevii**
## About The Pull Request

Updated RD cloak sprite 

## Why It's Good For The Game

Makes RD cloak match rest of the updated cloaks.

## Changelog
:cl:
tweak: Updated RD cloak sprite
/:cl:

### CODE REVIEW

**Comment by SomeAngryMiner** [comment]
this gets a :+1: from me.

**Comment by Isy232** [comment]
Yes

**Comment by heepox** [comment]
yes

**Review by PowerfulBacon — APPROVED** [review]
Good sprite

**Pull request merged**
