### PR TITLE
Hides syndie implants from health scans

### PR DESCRIPTION
**Pull request by chloecat0**
## About The Pull Request
Sets syndicate_implant to true on a bunch of illegal implants so they don't show up when someone is examined while wearing a medhud or when a health scanner is used on them.
Also changes the energy saw to use it's own icons rather than the normal circular saw icons.

## Why It's Good For The Game
Examining someone to instantly out them as a traitor isn't very fun and this variable seems to have just been forgotten about when the implants were made.

## Changelog
:cl:
add: Syndicate implants are now hidden from health scans
imageadd: Added inhand icons for the energy saw
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
wait this is a thing?? lmao why wasn't this done 2 years ago.

**Comment by BrumalLake** [comment]
chip implants are but cybernetics aren't

**Comment by ike709** [comment]
Conflicts. Fix them for a merge.

**Comment by chloecat0** [comment]
> Conflicts. Fix them for a merge.

Done.

**Review by Archanial — APPROVED** [review]

**Pull request merged**
