### PR TITLE
This mothroach fixes turned into a basic mobs port

### PR DESCRIPTION
**Pull request by mystery3525**
## About The Pull Request

Ports the basic mobs AI controllers, and some fixes/pre-requisites I've found along the way:
- https://github.com/tgstation/tgstation/pull/55725
- https://github.com/tgstation/tgstation/pull/58340 (fixes the squashable component)
- https://github.com/tgstation/tgstation/pull/58912
- https://github.com/tgstation/tgstation/pull/59008 (fixes the squashable component again)
- https://github.com/tgstation/tgstation/pull/60694 (**MAIN ONE**)
- https://github.com/tgstation/tgstation/pull/61455 
- https://github.com/tgstation/tgstation/pull/70728 (Partially, rats and mice haven't been converted yet)

Other changes include fixing `COMSIG_LIVING_DEATH` not being called, buffing the mothroach to 25 health (which was the original health in /tg/), and adding a new "eat webs" hunting behavior for the mothroaches with a 25 second cooldown.

As of this PR, the only real mobs turned into basic mobs are the cockroach and mothroach. Others will have to be ported later on.

## Why It's Good For The Game

Basic mobs (datumized AI controller) is *so much more better* than what we are using for simple_mobs, and this PR lays the groundwork for bringing more advanced (in terms of outcome) and simpler (code-wise) AI manipulation.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

dreamseeker_UdU8VNMwmq

dreamseeker_6KVm48mVEF

dreamseeker_9yvVYsKg0e

#### Note: I have since turned down the frequency of the mothroach's emotes
https://github.com/BeeStation/BeeStation-Hornet/assets/30960302/db843ada-7d2d-42f7-aac1-b9e2a6ad9f57

</details>

## Changelog
:cl: AMonekyThatCodes, Kylerace, tralezab, Ryll/Shaps, Melbert, ported by mystery3525
add: Basic Mobs. Newer, better simple_mobs now with datumized AI behavior, allowing more interesting behavior.
add: Mothroach web eating mechanic, with a 25 second cooldown
code: Refactored petting certain pets into a general element, atmos_requirements element, and death_drops element
/:cl:

### CODE REVIEW

**Comment by Rukofamicom** [comment]
> As of this PR, the only

I feel like you lost some text here.

**Comment by mystery3525** [comment]
> How is this PR affecting lavaland mobs and AI controlled spiders?

Unchanged, as they haven't been converted to basic mobs. This will be a gradual process requiring porting more things, but this PR sets up the framework for the basic mobs, and makes the cockroach and mothroach basic mobs in the process

**Comment by Rukofamicom** [comment]
👍

Sadly I don't think I can actually review this reasonably, but I will when back home if someone else hasn't already.

**Review by Rukofamicom — COMMENTED** [review]
Looks functional to me, so I'm slapping this with a TM to uncover issues before going right into merge. 

*At least when the merge conflict is handled*

**Comment by Rukofamicom** [comment]
Yolo for lack of a good TM time . 

Agreement to fix issues if they present themselves has been given.

**Review by Rukofamicom — APPROVED** [review]

**Pull request merged**
