### PR TITLE
Adds Lord Singulo to SyndieKit Tactical

### PR DESCRIPTION
**Pull request by DatBoiTim**
## About The Pull Request
Was doing a wiki update, and decided to do a top to bottom page edit. Started with SyndieKit Tactical, noticed 1 kit was not spawning. Despite existing in the wiki. Checked code, saw it was not added as a possible pick, despite existing in code.

This fixes that.

## Why It's Good For The Game
Fixes what I presume was an oversite in the code.

## Changelog
:cl: DatBoiTim
fix: The LordSingulo kit from TacticalKits actually spawns now, albeit rarely.
/:cl:

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
I think it was disabled due to the fact that singulo is barely used nowadays, so the beacon, the centre of this kit is nearly useless, so this kit will just screw the syndie over in most cases.

**Comment by zeskorion** [comment]
This was removed from possible spawns due to singulo not being a primary engine anymore. The wiki was simply not updated

**Comment by TotallyNotChief** [comment]
adding it to syndiekit special would make more sense now as its description states that it could "contain discontinued items"

**Comment by zeskorion** [comment]
> adding it to syndiekit special would make more sense now as its description states that it could "contain discontinued items"

shouldnt even add it at all cuz it sucks ass

**Comment by ghost** [comment]
Please dont add this. I got singulo kit so many fucking times when I buy A kit

**Pull request closed without merging**
