### PR TITLE
makes death nettles traitor exclusive

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request
the title says

## Why It's Good For The Game
botany too stronk

## Changelog
:cl:
add: Death Nettle seeds to botanists syndicate uplinks
balance: Death nettles can no longer be mutated from nettles
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
whatever, just use nova flowers then

**Comment by FriendlyContractor** [comment]
I really dont think locking everything dangerous behind TC is a good idea. We have syringe guns, TTV, grenades and i dont see how this particular item is more powerfull than them and why it should be only available to traitors(remember we also have revs, lings, cults and what not)

**Comment by ItsTisme** [comment]
> i dont see how this particular item is more powerfull than them

Because, unlike the TTV. You can carry a 100 of them in 1 plant bag and you can propably carry 6 bags in your backpack alone. they are also MUCH easier to make. Very low effort for a plant that when thrown can 1 shot hardsuits, armor clothing weapons and possible crit you.

**Comment by jupyterkat** [comment]
> > i dont see how this particular item is more powerfull than them
> 
> Because, unlike the TTV. You can carry a 100 of them in 1 plant bag and you can propably carry 6 bags in your backpack alone. they are also MUCH easier to make. Very low effort for a plant that when thrown can 1 shot hardsuits, armor clothing weapons and possible crit you.

do you know there's already a 1 devastation bomb that you can mass produce and bring everywhere since it's normal sized already besides botany bombs

**Comment by ItsTisme** [comment]
> do you know there's already a 1 devastation bomb that you can mass produce and bring everywhere since it's normal sized already besides botany bombs

Yes xenobio sucks we all know this, its not nearly as the same scale though compared to hydro

**Comment by jupyterkat** [comment]
> Yes xenobio sucks we all know this, its not nearly as the same scale though compared to hydro

no, there's another way. this one uses literally things you have lying around

**Comment by PerishedFraud** [comment]
I want to approve this but not for the expected reasons. Botany has capabilities to create incredibly powerful weapons but deathnettle is pretty much a shortcut to victory in this regard. Big power should be harder to obtain. 

Due to circumstances this is a neutral vote though.

**Comment by GregTheEgg42069** [comment]
death nettles are the most boring plant that almost all botanists make. you can also nerf the trait it posses and the ammount of chlorosulphuric acid it contains as 50% does not equal 50% of the capacity but instead 50 units which is basically insta kill no matter what. [my bad idea is either remove the injection of chems or tone down the DMG{ or remove it } so the chem injection is the main purpose of the perk]

**Comment by Isy232** [comment]
Making it "traitor exclusive" is a direct nerf to every other antagonist who might try to make use of botany.

This is a crappy way to nerf nettles, enough stuff is already only available to just traitors.

Decrease the amounts of reagents death nettles can put into you in 1 hit and decrease damage and I'd vote yes. Traitor-locking them is dumb.

**Comment by Kapu1178** [comment]
> 
> 
> Making it "traitor exclusive" is a direct nerf to every other antagonist who might try to make use of botany.
> 
> This is a crappy way to nerf nettles, enough stuff is already only available to just traitors.
> 
> Decrease the amounts of reagents death nettles can put into you in 1 hit and decrease damage and I'd vote yes. Traitor-locking them is dumb.

do something other than kill people

**Pull request closed without merging**
