### PR TITLE
[Port] MODSuits

### PR DESCRIPTION
**Pull request by DatBoiTim**
## About The Pull Request

Port of https://github.com/tgstation/tgstation/pull/59109

Adds Modular Suits, a 1+ year old project of replacing hardsuits with suits you can completely customize with different modules, read https://hackmd.io/@tgstation/SypLCs4jU for more information.

I'm here from testmerge! How do stuff!
Print parts from exosuit fabricators, buy a pack of cores from cargo in the science category. (alternatively you can scour maint, craft it with an ethereal heart or pray to gods)
Examine the shell for instructions, build the suit.
Screwdriver to open the suit, put power cell in, put any modules in, crowbar to take modules out.
Put on back, extend parts with action buttons and activate.
Good luck!

cool guy here:
image
showcasing the ui with the dynamic configuration system:
image

## Why It's Good For The Game
It allows more customization, adds a more robust system for special hardsuit stuff, lets us do much more creative things and encourages the players to be more creative

## Changelog
🆑 Fikou; Sprites: PositiveEntropy, Azlan, Infrared_Baron, Thunder12345, Yeeye; Code: Waltermeldron, Goof, Armhulen, ArcaneMusic, DatBoiTim; Descriptions: Nerevar
add: Adds Modular Suits. Printable at robotics.
del: Removes Hardsuits.
balance: Almost all Hardsuits have been replaced with MODsuits.
balance: HECKsuit, Berserker Hardsuit, Cult Hardsuit and Carp Hardsuit became hoodies, the first 2 losing their spaceproofness
del: Cybersun, Combat Medic and Owl Hardsuits didn't make the cut.
refactor: Changes how mob gravity checks are made. Uses a gravity negation trait. As part of this, space wind pushing you is handled by gravity negation, not noslips.
balance: Hardsuits no longer defend from tackles, but negating gravity does.
code: Adds support for digitigrade compatible shoes.
qol: Piercing syringes now pierce when used from hand, not just as projectile.
code: Removes the unused outside of admin shenanigans cult hardsuit requirement for spells.
/🆑

### CODE REVIEW

**Comment by DatBoiTim** [comment]
Some files will be cleaned up but I am keeping them atm to grab their stuff and put in the right place.

**Comment by zeskorion** [comment]
> ## About The Pull Request
> Port of [tgstation/tgstation#59109](https://github.com/tgstation/tgstation/pull/59109)
> 
> Adds Modular Suits, a 1+ year old project of replacing hardsuits with suits you can completely customize with different modules, read https://hackmd.io/@tgstation/SypLCs4jU for more information.
> 
> I'm here from testmerge! How do stuff! Print parts from exosuit fabricators, buy a pack of cores from cargo in the science category. (alternatively you can scour maint, craft it with an ethereal heart or pray to gods) Examine the shell for instructions, build the suit. Screwdriver to open the suit, put power cell in, put any modules in, crowbar to take modules out. Put on back, extend parts with action buttons and activate. Good luck!
> 
> cool guy here: image showcasing the ui with the dynamic configuration system: image
> 
> ## Why It's Good For The Game
> It allows more customization, adds a more robust system for special hardsuit stuff, lets us do much more creative things and encourages the players to be more creative
> 
> ## Changelog
> 🆑 DatBoiTim; Fikou; Sprites: PositiveEntropy, Azlan, Infrared_Baron, Thunder12345, Yeeye; Code: Waltermeldron, Goof, Armhulen, ArcaneMusic, DatBoiTim; Descriptions: Nerevar add: Adds Modular Suits. Printable at robotics. del: Removes Hardsuits. balance: Almost all Hardsuits have been replaced with MODsuits. balance: HECKsuit, Berserker Hardsuit, Cult Hardsuit and Carp Hardsuit became hoodies, the first 2 losing their spaceproofness del: Cybersun, Combat Medic and Owl Hardsuits didn't make the cut. refactor: Changes how mob gravity checks are made. Uses a gravity negation trait. As part of this, space wind pushing you is handled by gravity negation, not noslips. balance: Hardsuits no longer defend from tackles, but negating gravity does. code: Adds support for digitigrade compatible shoes. qol: Piercing syringes now pierce when used from hand, not just as projectile. code: Removes the unused outside of admin shenanigans cult hardsuit requirement for spells. /🆑

we already have said piercing syringe change

**Comment by Fikou** [comment]
i would wait until the initial fixes are pushed, but good luck!

**Comment by DatBoiTim** [comment]
> i would wait until the initial fixes are pushed, but good luck!

Well, I'll probably pull those into this too. But I want to at least get the base set to go.

**Comment by DatBoiTim** [comment]
@zeskorion I copied PR description. So that's likely a holdover.

**Comment by KubeRoot** [comment]
I would recommend drafting the PR until it's ready for review.

**Comment by DatBoiTim** [comment]
> I would recommend drafting the PR until it's ready for review.

Yeah I kinda forgot to make it into a draft. And I don't see the button for it

**Comment by ta3370** [comment]
Am I the only one seeing that this is just Bay's Rigsuits in TGcode?
The Planedemic continues to flow nicely.

**Comment by ta3370** [comment]
Though I do wonder why it deletes Hardsuits. I'm used to Rigsuits being limited supply while Hardsuits are the normal (but still relatively limited) availibility but very slow and clunky.

**Comment by DatBoiTim** [comment]
> Am I the only one seeing that this is just Bay's Rigsuits in TGcode? The Planedemic continues to flow nicely.

Shhhhhh. Don't say it too loudly.

**Comment by ToasterBan** [comment]
like ta said, I would prefer if we kept old hardsuits as weaker but stronger softsuits while having modsuits be a step above

**Comment by ta3370** [comment]
> like ta said, I would prefer if we kept old hardsuits as weaker but stronger softsuits while having modsuits be a step above

Basically the method Bay uses, is Hardsuits make you mega-slow you can count the seconds between tile steps.
But considering this is a (as far as I can tell) from-scratch system, Modsuits might be entirely different than the Rigsuits I'm used to when it comes to how they actually effect gameplay. But if they are super-modular-buffable-suits, probably best for them to be kept to "each department gets 1 or 2 for their staff, plus maybe one for the head if appropriate", with Hardsuits being 10% movespeed so you're *heavily* discouraged from just using them all the time, with the alternative of Modsuits that take your backpack slot ontop of the clothing slots.

**Comment by ta3370** [comment]
One question I have is: How are the powercells/energy handled? Are they scaled with everything you have on it exponentially increasing the battery usage like one might expect, or is it just weirdly always the same?

**Comment by PortableSeedExtractor** [comment]
can you believe it guys, modsuits! only a week away!

**Comment by DatBoiTim** [comment]
> One question I have is: How are the powercells/energy handled? Are they scaled with everything you have on it exponentially increasing the battery usage like one might expect, or is it just weirdly always the same?

Power use should be based on what the Suit has equipped:

So from my experience contributing to the original PR.

There is a base power drain from just having the suit active.

There are then passive modules (always active) that also constantly drain power as long as the suit is active.

There's then active modules. These are either a draining certain amount per activation(ninja sword recall), draining for the duration of activation(ninja invis), or draining per use+initial activation(plasma cutter).

Experience with bay Rigsuits is limited for me, but I believe that's almost the same system for power management.

Also ModSuits have a complexity value(think like circuits). So no GODSuits without adminbus and other code fuckery.

**Comment by DatBoiTim** [comment]
And while yes some of your suggestions are great ideas. This is a raw port for a system I intend to heavily tweak after the fact.

Such things are very much out of scope for now.

**Comment by ta3370** [comment]
> Power use should be based on what the Suit has equipped:
> 
> So from my experience contributing to the original PR.
> 
> There is a base power drain from just having it active.
> 
> There are then passive modules (always active) that also constantly drain power as long as the suit is active.
> 
> There's then active modules. These are either a draining certain amount per activation(ninja sword recall), draining for the duration of activation(ninja invis), or draining per use+initial activation(plasma cutter).
> 
> Experience with bay Rigsuits is limited for me, but I believe that's almost the same system for power management.
> 
> Also ModSuits have a complexity value(think like circuits). So no GODSuits without adminbus and other code fuckery.

Aighty, sounds good.

**Comment by BrumalLake** [comment]
cl needs a little adapting such as tackles and the combat medic hardsuit which we don't have

**Comment by DatBoiTim** [comment]
> cl needs a little adapting such as tackles and the combat medic hardsuit which we don't have

Yeah, that'll come when I get a compiling version. So I can really see what's what.

**Comment by DatBoiTim** [comment]
Wait
I am in the changelog 2x

**Comment by DatBoiTim** [comment]
We should really port those span procs, or at least have common span types set as defines.

**Comment by DatBoiTim** [comment]
My goal is to get this finished before 2023. Because then I will have graduated from college and who knows what the fuck is gonna happen.

**Comment by BrumalLake** [comment]
guess those overlay lighting fixes on hardsuits are gonna be started in 2023

**Comment by DatBoiTim** [comment]
> guess those overlay lighting fixes on hardsuits are gonna be started in 2023

I told Dejaku to do em now, don't wait on this to be done smh

**Comment by DatBoiTim** [comment]
Won't let me fix merge conflicts!

Sad!

**Comment by DatBoiTim** [comment]
I do not want to maintain this shit. Someone else can do this if they feel up to the task, I will keep the branch if someone wants it.

**Pull request closed without merging**
