### PR TITLE
Removes atmos techs.

### PR DESCRIPTION
**Pull request by ghost**
## Changelog
:cl: BeloneX
del: Atmospheric Technicians.
tweak: Station Engineers have Atmospherics Access now.
tweak: More Station Engineer slots.
/:cl:

## Why It's Good For The Game

It's a redundant role, everything they are supposed to do is already done by Station Engineers, so instead Station Engineers now just get full Engineering access.

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
lol

**Comment by xboxnoob** [comment]
nice build failed

**Comment by xboxnoob** [comment]
lemme guess this is gonna get _S P E E D M E R G E D_

**Comment by BettonnCZ** [comment]
this is stupid

**Comment by TotallyNotChief** [comment]
petition to ban belonex from github

**Comment by ghost** [comment]
> petition to ban belonex from github

image

**Comment by TotallyNotChief** [comment]
> 
> 
> > petition to ban belonex from github
> 
> image

yes and?
name one PR that was made by you and liked by the community that isnt purely cosmetic

**Comment by ghost** [comment]
> > > petition to ban belonex from github
> > 
> > 
> > image
> 
> yes and?
> name one PR that was made by you and liked by the community that isnt purely cosmetic

https://github.com/BeeStation/BeeStation-Hornet/pull/2861
https://github.com/BeeStation/BeeStation-Hornet/pull/1415
https://github.com/BeeStation/BeeStation-Hornet/pull/2201
https://github.com/BeeStation/BeeStation-Hornet/pull/2362
https://github.com/BeeStation/BeeStation-Hornet/pull/2826
https://github.com/BeeStation/BeeStation-Hornet/pull/2430
https://github.com/BeeStation/BeeStation-Hornet/pull/1681
https://github.com/BeeStation/BeeStation-Hornet/pull/1576
https://github.com/BeeStation/BeeStation-Hornet/pull/1555
https://github.com/BeeStation/BeeStation-Hornet/pull/160
https://github.com/BeeStation/BeeStation-Hornet/pull/2388
https://github.com/BeeStation/BeeStation-Hornet/pull/2366

Liked by the community =/= good.

**Comment by BettonnCZ** [comment]
yea ban he

**Comment by ghost** [comment]
> yea ban he

You'd wish, but a maintainer wanted this.

**Comment by BettonnCZ** [comment]
maintainer can fuck off. removing jobs is just removing fundementals of the game, there are many redundant things that arent removed, removing a whole fucking job is just stupid.

**Comment by ghost** [comment]
> maintainer can fuck off. removing jobs is just removing fundementals of the game, there are many redundant things that arent removed, removing a whole fucking job is just stupid.

Sure, a maintainer still wanted this.

**Comment by r1ks-iwnl** [comment]
Soo remove sec when ? It's a redundant role, everything they do can be done by an assistant.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Don't just stop at atmos tech there are still a few other roles that should go imo, captain, hos, warden, detective, officer, chief engineer, engineer, robotisist, AI, cyborg, brig physician, deputy, research director, scientist, chemist, cmo, medic, genetics, virologist, paramedic, hop, bartender, botanist, cook, janitor, curator, QM, cargo tech, miner lawyer, chaplain, clown, mime, and all the gimmick roles. Just keep assistant

**Comment by ghost** [comment]
> Don't just stop at atmos tech there are still a few other roles that should go imo, captain, hos, warden, detective, officer, chief engineer, engineer, robotisist, AI, cyborg, brig physician, deputy, research director, scientist, chemist, cmo, medic, genetics, virologist, paramedic, hop, bartender, botanist, cook, janitor, curator, QM, cargo tech, miner lawyer, chaplain, clown, mime, and all the gimmick roles. Just keep assistant

Funny.

**Comment by ghost** [comment]
the STATE of bee c*ders

**Comment by PowerfulBacon** [comment]
ok its been up long enough, this is just a bad idea frankly and is merging 2 jobs that have separate mechanics and do separate things.

**Pull request closed without merging**
