### PR TITLE
Ports tg's *kiss

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Ports tg's *kiss emote. This turns it from a simple emote into a fingergun-esque projectile launcher in the shape of a heart which you can shoot at other people with. People with the socially awkward trait get really flustered if they have a blown kiss hit them. Does not include kiss of death. 

PORTS: https://github.com/tgstation/tgstation/pull/56698

## Why It's Good For The Game

Flat out superior than what we have now, plus it's a fun feature. 

## Changelog
:cl: Ryll/Shaps, ivanmixo
add: Ported tg's *kiss emote, blowing kisses at people is enhanced
soundadd: kiss sound
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
someone here is gonna say fetish content I'm certain

**Comment by ToasterBan** [comment]
I also realised this makes chaplain and anyone else who's magic immune, immune to kisses

**Comment by zeskorion** [comment]
You can use kisses as a decent weapon against socially awkward people 
Nice

**Comment by TeomanTheGreat** [comment]
I'm sure this will end well

**Comment by Cenrus** [comment]
> 
> 
> I also realised this makes chaplain and anyone else who's magic immune, immune to kisses

jeebus2

**Comment by Effemu** [comment]
i will actually ban you

**Comment by aidan-bowman** [comment]
oh god the felinid metagang is coming

**Comment by 1glitchycent** [comment]
not halal :( don't let them have a mechanical reason to do this

**Comment by aidan-bowman** [comment]
at this point you might as well add *sex

**Comment by KazooBard** [comment]
> 
> 
> at this point you might as well add *sex

you realise we have merged birthing plushies code.

**Comment by ivanmixo** [comment]
> at this point you might as well add *sex

Obviously you can't blow kisses at people in a non sexual manner, god what was I thinking?

**Comment by Sinestia** [comment]
Please make this assault under space law


 Then it's all good.

**Comment by aidan-bowman** [comment]
> > at this point you might as well add *sex
> 
> Obviously you can't blow kisses at people in a non sexual manner, god what was I thinking?

"but mr admin, we were only spam hugging each other naked in dorms in a non-sexual way. why are we being banned?"

99.99% of *kiss usage will be in the erp way

**Comment by PowerfulBacon** [comment]
now add visual blushing

**Comment by PowerfulBacon** [comment]
You can stunlock people with kisses.

**Comment by bloons3** [comment]
> You can stunlock people with kisses.

Good

**Comment by Raven-Industries** [comment]
> You can stunlock people with kisses.

Excellent, I have justification for brigging people for it. You get an assault charge, and you get an assault charge, and YOU get and assault charge!

**Comment by OceanFish1** [comment]
literally fetish content
now add virginity shield that deflects kisses (like sleeping carp)

**Comment by DatBoiTim** [comment]
Yeah no bad PR.

This is literally adding yet another mechanical ERP feature.

**Comment by ilikesaying** [comment]
> now add virginity shield that deflects kisses (like sleeping carp)

chastity belt

**Comment by TeomanTheGreat** [comment]
Allow shields to block kissing.

**Comment by bloons3** [comment]
> Allow shields to block kissing.

image

**Comment by zeskorion** [comment]
> Allow shields to block kissing.

If it's a projectile, they will

**Comment by Absolutely-Steph** [comment]
> Please make this assault under space law
> 
> Then it's all good.

I think this falls under sexual assault, which is actually a capital fuckin crime, punishable by death.

**Comment by ike709** [comment]
This is a terrible idea.

**Comment by Sinestia** [comment]
Make it a vote


**Let the people decide the appropriate level of hell.**

**Comment by ToasterBan** [comment]
> This is a terrible idea.

that's why we should merge it 😘

**Comment by ike709** [comment]
No

**Comment by AtlasRules** [comment]
image

**Pull request closed without merging**
