### PR TITLE
Sophie's Sounds Service

### PR DESCRIPTION
**Pull request by BetaCentari**
## About The Pull Request
Adds interaction sound effects to many items and surgery sound effects for every step along the gruesome process of reconstituting or breaking down organic and inorganic material! 

Ports Sound Effects from TG and SR
OG Authors Authors Floyd & ActionNinja
https://github.com/tgstation/tgstation/pull/46677

Picking up items like tools, paper, materials, dawning clothes, surgery steps now all have sound effects.

## Why It's Good For The Game
Makes the game more immersive by adding more sound effects to the game! 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/17231562/202932151-7d410c95-8f0d-4b4e-8805-933f9c9cf746.mp4

</details>

## Changelog 
:cl:Floyd,ActionNinja,BetaCentari
soundadd: added a TON of new sounds under sound/surgery and sound/items/handling
code: Changed some inventory handling to configure picking up and putting down and dropping items
/:cl:

### CODE REVIEW

**Comment by kit-katz** [comment]
as some tg contributor once said
neat

**Comment by Crossedfall** [comment]
And we all float on, OK

**Comment by Crossedfall** [comment]
I'd prefer if we properly attributed action ninja by adding them as a co-author to the pr and CL.

**Comment by BetaCentari** [comment]
> I'd prefer if we properly attributed action ninja by adding them as a co-author to the pr and CL.

Sure thing, I'm not used to proper procedure when it comes to Ports and such, as far as I was told you just link the original PR.

**Comment by BetaCentari** [comment]
> I'd prefer if we properly attributed action ninja by adding them as a co-author to the pr and CL.

Done (I think)

**Comment by AnCopper** [comment]
You need to add their name next to the first 🆑 box.
Like this:


🆑actioninja (optionally your name too)

soundadd: added a TON of new sounds under sound/surgery and sound/items/handling
code: Changed some inventory handling to configure picking up and putting down and dropping items

/🆑

**Comment by BetaCentari** [comment]
> You need to add their name next to the first 🆑 box. Like this:
> 
> 🆑actioninja (optionally your name too)
> 
> soundadd: added a TON of new sounds under sound/surgery and sound/items/handling code: Changed some inventory handling to configure picking up and putting down and dropping items
> 
> /🆑

Fixed, thank you!

**Comment by Crossedfall** [comment]
You can either rebase your changes to attribute action ninja to the specific items or you can add an empty commit with them as the co-author to attribute them to the PR as a whole.

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

Feel free to reach out if you need help with this.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
DNM: Requiring the review of crossed before this gets merged

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
