### PR TITLE
More moth customization

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request
Ports 3 antennaes and wings from Fulp, adds the open wing version, fixes some oopsies I did the last time I fixed the wings and adds a brand new antennae and wing.

## Why It's Good For The Game

More customization

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

imagen

imagen

imagen

imagen

</details>

## Changelog
:cl: Varo, Naevi for helping me make the bluespace wings, PapaporoPaprito for the ported wings from Fulp
add: Added 4 new Moth wings and antennae: Rosy, Plasmafire, Brown, and Bluespace.
fix: Fixed Luna moth's open wing sprites having the fluf misplaced.
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
typo in wingsopen.dmi: `m_moth_wingsopen_thunder_FRONT` should be `m_moth_wingsopen_bluespace_FRONT`

Otherwise looks good and removed a duplicate `witchwingsi` typepath.

**Comment by itsmeow** [comment]
Please credit the original PRs in the description as well as including the author in your changelog

```
:cl: (authors)
add: ...
/:cl:
```

**Comment by ClownMoff** [comment]
Haven't credit no one as this PR is still on draft, but I will do once I get all wings in here

**Comment by Nakalon** [comment]
I'm very interested in "adds boykissing"

**Comment by itsmeow** [comment]
For the Fulp thing, it's also standard to credit with a link to the original PR.

This took some deeeep digging but here it is:
https://github.com/fulpstation/fulpstation/pull/43

The original PR doesn't exist, period, it was added as a commit on the ancient repo: https://github.com/vlggms/fulpstation/commit/1cbba12babaabe2e76ba4a124f5fe94698fd348f

**Review by itsmeow — APPROVED** [review]

**Pull request merged**
