### PR TITLE
Removing arbitrary map rotation 

### PR DESCRIPTION
**Pull request by Mat05usz**
## About The Pull Request

Now rotation will pick a new map after every round, instead of just randomly picking whenever it feels cute.

I thought that with #6776 there is going to be a config change that will let people vote after each round for the next map. There was no such thing, so nothing changed. Me, and a lot of other people, are really tired of playing the same map for 8 hours straight, so I think that this is a good way of changing things.

## Why It's Good For The Game

People who play a lot may notice that current rotation system tends to pick the same map over and over again until everyone is fucking tired, then it picks some more until RNG feels cute and decides to spare us, that is no more. Without this shitty `if`, every round will roll for another map, to ensure diversity and make it so people don't vomit when playing the same map over again.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
tweak: Map rotation no longer randomly chooses to pick the same map over and over again.
/:cl:

### CODE REVIEW

**Comment by Mat05usz** [comment]
I'm open to suggestions to maybe restrict this so people don't early call, but for the love of fuck, make those quick and let us finally enjoy something that isn't Fland for the 8th time in a row.

**Comment by Rukofamicom** [comment]
Regarding: https://github.com/BeeStation/BeeStation-Hornet/pull/6776

A config change can't be part of the PR, that's pretty much exclusively up to @Crossedfall who I never actually poked to ask about it.

**Comment by Crossedfall** [comment]
> Regarding: https://github.com/BeeStation/BeeStation-Hornet/pull/6776
> 
> A config change can't be part of the PR, that's pretty much exclusively up to @Crossedfall who I never actually poked to ask about it. 

To the contrary. I mandate that config changes/requests must be made as prs.

**Comment by Rukofamicom** [comment]
Yes, as I stand corrected
🤡

**Comment by PowerfulBacon** [comment]
I dislike that it always rotates, since it means people are more encouraged to early call on the maps they dislike. I think it would be best as a time limit pr map, with it rotating after, say, 3 hours or something, so you always get a couple of rounds on that map

**Comment by Mat05usz** [comment]
> Regarding: https://github.com/BeeStation/BeeStation-Hornet/pull/6776
> 
> A config change can't be part of the PR, that's pretty much exclusively up to @Crossedfall who I never actually poked to ask about it.

> To the contrary. I mandate that config changes/requests must be made as prs.

Oh, got it.

> I dislike that it always rotates, since it means people are more encouraged to early call on the maps they dislike. I think it would be best as a time limit pr map, with it rotating after, say, 3 hours or something, so you always get a couple of rounds on that map

I thought about maaybe lowering the percentages so it ends up being, for example, 100% to map rotate after 60/90 minutes, rather than 133 minutes that is now.

On the other hand, if the config change does get through, #6958 is a much better alternative.

**Comment by Crossedfall** [comment]
Closing in favor of https://github.com/BeeStation/BeeStation-Hornet/pull/6958

**Pull request closed without merging**
