### PR TITLE
Removes 3 stray pixels on the TTV sprite

### PR DESCRIPTION
**Pull request by r1ks-iwnl**
## About The Pull Request
removes 3 barely visible pixels because they hurt my soul

## Why It's Good For The Game
Less pixels = massive performance increase

### CODE REVIEW

**Comment by r1ks-iwnl** [comment]
hello, linters ?

**Comment by yyzsong** [comment]
Soul dead

**Comment by r1ks-iwnl** [comment]
third time's the charm

**Comment by r1ks-iwnl** [comment]
maintainers pls fix

**Comment by r1ks-iwnl** [comment]
oh nevermind

**Review by utilbird — APPROVED** [review]

**Pull request merged**
