### PR TITLE
Adds a whitelist for station traits + Disables intern announcer

### LINKED ISSUE #7749: Remove intern announcer - Station trait config option
As much as I love the intern announcer, it is detrimental to the atmosphere of the game, which in turn is determintal to roleplay. Considering atmosphere and environment is a huge factor towards encouraging roleplaying out situations, it only makes sense to remove this.
Its much harder to build up the serious station atmosphere when the intercom is being blasted with someone being locked in a room.

This should be left in code, but should be done as a config edit. If there isn't already a way to blacklist traits via the config, then there should be.

### PR DESCRIPTION
**Pull request by tontyGH**
## About The Pull Request
closes #7749

All station traits now have an internal id
Adds a whitelist for which station traits are able to be selected in game_options.txt
Disables the intern announcer

## Why It's Good For The Game

> As much as I love the intern announcer, it is detrimental to the atmosphere of the game, which in turn is determintal to roleplay. Considering atmosphere and environment is a huge factor towards encouraging roleplaying out situations, it only makes sense to remove this.
Its much harder to build up the serious station atmosphere when the intercom is being blasted with someone being locked in a room.
>
> This should be left in code, but should be done as a config edit. If there isn't already a way to blacklist traits via the config, then there should be.

## Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Only the scarves, blackout and glitched pda traits are enabled in the configuration
image

And they were the only ones that were picked for rolling
image

</details>

## Changelog
:cl: tonty
config: Added configuration options for choosing what station traits are enabled
del: The intern announcer has been disabled. I'm so sorry
/:cl:

### CODE REVIEW

**Comment by CydiaLamiales** [comment]
> Disables the intern announcer
Blessed 🙏

**Comment by WrillWasTaken** [comment]
> Disables the intern announcer

soul removed

**Comment by tontyGH** [comment]
> > Disables the intern announcer
> 
> soul removed

It hurts me too but that's what he asked for

**Comment by Tsar-Salat** [comment]
> > Disables the intern announcer
> 
> Blessed 🙏

Cursed 😠

**Comment by itsmeow** [comment]
Absolutely not, we are not disabling the intern

**Comment by tontyGH** [comment]
@PowerfulBacon Need your input on this

**Comment by PowerfulBacon** [comment]
Personally I am not a fan of the intern announcer

**Comment by EvilDragonfiend** [comment]
soul removed

**Comment by EvilDragonfiend** [comment]
I think configurable chance will be better if you should enable/disable one by one

**Comment by LodedDiper69** [comment]
I also like roleplaying but how the hell is the intern announcer bad for RP???

**Comment by Pirill** [comment]
The soul destruction on display.... :( Sure, he's flawed, but he TRIES!

**Comment by tontyGH** [comment]
Yeah this sucks

**Pull request closed without merging**
