### PR TITLE
Sniper rounds no longer paralyze for 10 seconds.

### PR DESCRIPTION
**Pull request by VickiMorris**
<details>

NoStunPlz
</details>

## About The Pull Request

Regular sniper rounds no longer paralyze targets for upto 10 seconds, instead causing 0.5 seconds of knockdown from the punch of getting hit by a .50 cal bullet. Penetrator and Utility (EMP, Soporific, Explosive, etc.) do not cause knockdown, as they did not previously cause paralyze.

## Why It's Good For The Game

Even though it is a nuke-op item, it can be obtained by regular tots through the syndie kits in the uplink. 70 damage w/ 50 AP is already insanely strong, *10 seconds* of hard stun ontop of that is absolutely absurd, and it just unfun to play against. Doubly so against a weapon that can tag you from off-screen with little to no notice.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Accidentally gave utility rounds a dismember chance for this video. Double-checked and made sure to fix it so I didn't have another oopsie.

https://github.com/BeeStation/BeeStation-Hornet/assets/97719613/f3a3937c-f645-4a0c-a6ce-9ed816f04cd1

</details>

## Changelog
:cl: Impish_Delights
balance: Sniper rounds no longer paralyze for 10 seconds, causing half a second of knockdown instead.
/:cl:

### CODE REVIEW

**Comment by VickiMorris** [comment]
Not even "pretty much" a death sentence. That's a guarenteed follow up shot (another 7 follow up shots tbh). The knockdown still gives it some punch but not anything, that's extremely OP.

**Comment by Howluinb** [comment]
10 seconds is really long, yes, but on the other hand you get a single free magazine of 5 rounds and have to spend *4 tc* (or 2, which is still huge) to get a single bullet

It's meant to be a "Fuck that guy" button, very limited in amount basically. I think the sleep is good, but yeah the damage looks way too insane

**Review by itsmeow — APPROVED** [review]

**Comment by VickiMorris** [comment]
> I think the sleep is good, but yeah the damage looks way too insane

The soporific rounds are a utility ammo subtype; they only deal 20 damage per shot, cannot penetrate anything, and cannot dismember. Soporific rounds still have their sleep (40 seconds, some MGS shit)

**Comment by Howluinb** [comment]
> > I think the sleep is good, but yeah the damage looks way too insane
> 
> The soporific rounds are a utility ammo subtype; they only deal 20 damage per shot, cannot penetrate anything, and cannot dismember. Soporific rounds still have their sleep (40 seconds, some MGS shit)
> 
> The ammo boxes give you 6 for standard ammo (2 tc), 2 bullets for soporific (3 tc) and penetrator (2 tc), and a single for EMP (1 tc), explosive (3 tc), inferno (2 tc), and antimatter (14 tc). I think some of their prices should be looked at and tweaked, but that's not something I'm touching in this PR.

I misread the PR, my apology, very good change

**Pull request merged**
