### PR TITLE
Medical staff spawn with a unique first-aid kit

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
CMO, med doctor and brig phys spawn with a medical aid kit, a higher capacity version of a first-aid kit which also contains the few surgical tools needed in order to perform Tend Wounds surgery.

## Why It's Good For The Game
Tend Wounds is a great free healing procedure and it should be made possible for any medical staff to do anywhere from roundstart. 

## Changelog
:cl:
add: Medical staff spawn with a unique first-aid kit with surgical tools needed for Tend Wounds.
/:cl:

### CODE REVIEW

**Comment by Mick1299** [comment]
What about paramedics?

**Comment by VictorVow** [comment]
Oof good point, adding now.

**Comment by MarkSuckerberg** [comment]
the capacity this thing has is insane

**Comment by ike709** [comment]
12 items is insane?

**Comment by ike709** [comment]
Admittedly it'd fit better with the sprite of a proper EMT duffel bag but... meh.

**Comment by MarkSuckerberg** [comment]
for a roundstart item that fits in bags? yeah, it's insane to me at least

**Pull request merged**
