### PR TITLE
Revert harmbaton nerf

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request

I was wondering why stunbatons only do 5 brute damage here unlike other codebases (which is even less than punches lol), and lo and behold realised it got [stealth nerfed](https://github.com/BeeStation/BeeStation-Hornet/pull/295) by Toxic ages ago. This increases the brute damage back to 8, which is less than as billy clubs (and doesn't do stamina damage when unpowered like it either).

## Why It's Good For The Game

It's dumb that whacking someone with a metal stick does less damage than punches. Also gives sec a weapon that they spawn with that can actually be used to fight simplemobs.

## Changelog
:cl:
balance: Harmbaton damage increase from 5 to 8. No more doing less damage than punches. 
/:cl:

### CODE REVIEW

**Comment by FriendlyContractor** [comment]
Just wait till somebody complains this is more than tiny a bugfix and encourages shitsec etc ect ;-;

**Comment by Archanial** [comment]
The nerf wasn't stealth, it I don't believe it was hidden anywhere.

**Comment by VictorVow** [comment]
> The nerf wasn't stealth, it I don't believe it was hidden anywhere.

It was never mentioned in the changelog, or anywhere in the PR. It absolutely was stealth.

**Comment by zeskorion** [comment]
This nerf wasnt stealth. It's there to stop people from being shitsec and beating people to death. Its a dumb mechanic to begin with anyways

**Comment by VictorVow** [comment]
> This nerf wasnt stealth

Are we rewriting history here? What's the definition of "stealth nerf" then in your reality? 

It's always been referred to when a mechanic has been changed but it isn't mentioned in the changelog, PR body or replies. I mean you should know, you tried to insert them in PRs all the time.

**Review by PowerfulBacon — DISMISSED** [review]
Good, but maybe it should be 8 damage (still more powerful than regular punches which deal 7 I believe) or at least less than the billy club.

**Comment by PowerfulBacon** [comment]
Also I wouldn't exactly call it a stealth nerf when its been in the codebase since almos the very beginning 😄

**Comment by PowerfulBacon** [comment]
I think the damage should be lowered to 8.

**Comment by VictorVow** [comment]
Reduced to 8. I think 9 is sufficient though personally, since it doesn't do stamina damage unlike the billy club as well.

**Review by Archanial — APPROVED** [review]

**Pull request merged**
