### PR TITLE
Removes circuits (Via config)

### PR DESCRIPTION
**Pull request by francinum**
Makes circuits a config, clarifies the existing config

## About The Pull Request
Finally does what should have been done ages ago

## Why It's Good For The Game
Adding them was a mistake.

Circuits, while adding depth, are both incredibly cheap, incredibly dangerous, practically untraceable, and logged *terribly.*

They are an endless source of confusing cornercases and can be mass produced from a single text string and a stack of iron.

## Changelog
:cl:
del: Removes Integrated Circuits by default
config: They can be reenabled by server operators.
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
bad idea, just remove them

**Comment by MitztheKat** [comment]
keep em, they're fun and strain my brain to learn for once in my life

**Comment by MNarath1** [comment]
Well ok a config file change like that is fine i am currently working on some rebalances for circuits trough if this gets merged expect another PR to change the config file in around a month or two

**Comment by BitBite112** [comment]
No, circuits have so much potential I don't want to see wasted.

**Comment by ToasterBan** [comment]
circuit cloning is the bad part really

**Comment by Glcbitj** [comment]
ided by meme circuit

**Comment by jlsnow301** [comment]
The fun of ss13 is in its range of possibilities and each you remove sterilizes the game

**Comment by utilbird** [comment]
Horrible PR description for such a large removal.

**Comment by utilbird** [comment]
Circuits are fun for a lot of people. The main problem with them, cloning, has (mostly) been addressed. This'll upset way more people long term than it'll please.

**Comment by OceanFish1** [comment]
> Circuits are fun for a lot of people. The main problem with them, cloning, has (mostly) been addressed. This'll upset way more people long term than it'll please.

no fun allowed :trollface:

**Comment by optimumtact** [comment]
lol

**Comment by utilbird** [comment]
PR looks ded, I'll close it for now to cut down on the backlog. Feel free to re-open it if you want further discussion or a vote.

**Pull request closed without merging**
