### PR TITLE
Makes Deadly Nanite Technology Easier to Research

### PR DESCRIPTION
**Pull request by Isy232**
## About The Pull Request

Makes a new technode, dangerous nanites, which I've moved chain detonation, meltdown, pyro and viral nanites to.

Note: Viral nanites allows this specific blend of nanites to infect other nanite users, can not spread to people with no nanites.

## Why It's Good For The Game

Nanites rarely get uploaded with negative programs, I think this is partially due to the fact that many of the powerful negative programs require illegal technology which prevents most antagonists from being able to effectively sabotage nanites.

Now this large barrier to entry is no longer present, your average traitor doesn't need to expend telecrystals to sabotage nanites and your cult/revolution/nukeops can have fun remotely detonating whomever thought nanites were "free heals with absolutely no risks".

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
new: Dangerous nanite technode with the previous combat nanite designs except nanite sting and amphetamine nanites.
/:cl:

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
Finally, some way to get the nanites in those damn luddites.

**Comment by Isy232** [comment]
> Finally, some way to get the nanites in those damn luddites.

Imagine the potential of setting up a nanite program that automatically stings anyone nearby whenever possible, spreading the nanites, as well as chain detonating when they reach a certain threshold.

Honestly cant wait to see whatever shit people get up to with this.

**Comment by PowerfulBacon** [comment]
Nanite sting will just be used by non antags to spread their craopy nanites. Nanites should be optional and you face the consequences for your choice rather than a sting. That specific one should still require illegal tech

**Comment by Isy232** [comment]
> Nanite sting will just be used by non antags to spread their craopy nanites. Nanites should be optional and you face the consequences for your choice rather than a sting. That specific one should still require illegal tech

Alright, I've readded a syndicate nanites node that now contains nanite sting and amphetamine nanites that requires illegal tech.

**Comment by Sapfearon** [comment]
chain detonation is literally round removal tool, what the fuck? reason why illiegal tech is uplink only is partially due to chain detonation being researched every round. And when it was avaliable every round, it was fucking used a lot, 90% of time by NON antags. If you add chain det to nanites that's it EVERYONE WITH NANITES DEAD. Literally. There is 0 counter to it even if you remove it 1 second later. Literally only possible way to somehow survive it is to instantly remove all nanites from your body or pray you have like minimum amount of nanites. At 500 it's insta gib.
Last time i used chain det i killed 85% of station, without even force injecting nanites into anyone.

Not to mention is very easy to simply add paralyze/sleep/mute and lots of other bad stuff without any illiegal tech. I killed lots of people as tot by simply remote stunning my target. I killed as many antags doing same too. 

Completly disagree with this until we get some kind of protection for nanites against random people hacking 1 door and deleting/overriding your shit. At least allow us to lock clouds with id, force traitors to either be super sneaky with nanites or using nanite cloud overrides while hiding in maints in hidden lab.

Adding chain detonation needs 0 understanding how nanites work to kill everyone who uses them.
That's like placing in toxins lab pre-made maxcaps shift start. This will go wrong.

**Comment by FortSumter** [comment]
Nanites are dumb IMO for reasons described. Its OP when used for good or bad. I personally never get them due to the minuscule chance they become explosive.

**Comment by Isy232** [comment]
> chain detonation is literally round removal tool, what the fuck? reason why illiegal tech is uplink only is partially due to chain detonation being researched every round. And when it was avaliable every round, it was fucking used a lot, 90% of time by NON antags. If you add chain det to nanites that's it EVERYONE WITH NANITES DEAD. Literally. There is 0 counter to it even if you remove it 1 second later. Literally only possible way to somehow survive it is to instantly remove all nanites from your body or pray you have like minimum amount of nanites. At 500 it's insta gib. Last time i used chain det i killed 85% of station, without even force injecting nanites into anyone.

>And when it was avaliable every round, it was fucking used a lot, 90% of time by NON antags. 

I admit, I've had an entirely different experience. I've only seen chain detonation used once in EORD a while ago and beyond that never any other nanite sabotage besides the time I accidentally uploaded paralysis to my own nanites while trying to make a stun program for security.

> If you add chain det to nanites that's it EVERYONE WITH NANITES DEAD. Literally. There is 0 counter to it even if you remove it 1 second later.

Its possible to disconnect from the nanite cloud controller, albeit it requires use of the nanite implanter and console and cannot just be done in the public nanite chamber. This would make it so that even if a death program was uploaded you would not be updated to include it.

This does come with the downside that EMP's corrupt programs and since your programs are no longer being updated, these EMP'ed programs would stay and continue to cause damage.

There are counters even within nanites to this, or just avoid taking nanites in the first place.

>At 500 it's insta gib. Last time i used chain det i killed 85% of station, without even force injecting nanites into anyone.

I think once people understand the dangers of nanites they would be less likely to take public nanites from the hallway so I doubt this would happen repeatedly.

> Not to mention is very easy to simply add paralyze/sleep/mute and lots of other bad stuff without any illiegal tech. I killed lots of people as tot by simply remote stunning my target. I killed as many antags doing same too.

To some degree, yes, current programs do allow for a significant amount of sabotage. However, since I rarely see them get sabotaged I think increasing the potential power of nanite sabotage is fine for now. 

> Completly disagree with this until we get some kind of protection for nanites against random people hacking 1 door and deleting/overriding your shit. At least allow us to lock clouds with id, force traitors to either be super sneaky with nanites or using nanite cloud overrides while hiding in maints in hidden lab.

I think this is somewhat of an IC issue. Its possible ingame to reinforce the nanite lab as things are now. If nanite sabotage proves to be wayyy too common I'd be fine to make a PR to upgrade the security of the nanite lab.

**Comment by FortSumter** [comment]
>  think this is somewhat of an IC issue. Its possible in-game to reinforce the nanite lab as things are now.

IMO it's fail RP when anyone outside of engineering makes significant changes to their departments. There aren't many scientists out there that know how to build a house. It's also entirely pointless to reinforce departments like that because if someone wants to get in the lab, they are going to get in the lab.

> If nanite sabotage proves to be wayyy too common I'd be fine to make a PR to upgrade the security of the nanite lab.

That isn't how this works. Address the obvious problem with your PR in the PR. The Headcoders aren't going to approve something that heavily unbalances the game like this without any counter.

One thing that might be helpful is the ability to lock nanite clouds to crew Ids similar to how mechs can be locked to DNA. This way only the person working on the nanites (or someone who had stolen their ID) can lock/unlock the cloud and add/delete programs to it.

**Comment by Fronsis** [comment]
> One thing that might be helpful is the ability to lock nanite clouds to crew Ids similar to how mechs can be locked to DNA. This way only the person working on the nanites (or someone who had stolen their ID) can lock/unlock the cloud and add/delete programs to it.

That would be a nice addition, another step would be to make those specific machines works as Genetics one currently do, only sciencist and RD would be able to access them

I agree that chain detonations needs to be for antag only use it shouldn't be available for everyone for no particular reason, hell maybe you could even put the stun/mute ones in a separate disk inside RD locker so they could be used only with their authorization(or someone breaking into RD locker) to be used for emergencies

**Comment by Isy232** [comment]
>IMO it's fail RP when anyone outside of engineering makes significant changes to their departments. 

Well, you can have that opinion, however the rules allow it provided your not metagaming dangers.

>That isn't how this works. Address the obvious problem with your PR in the PR. The Headcoders aren't going to approve something that heavily unbalances the game like this without any counter.

I'm making this PR because I belive the game is currently unbalanced in the way that nanites are too positive and this PR would bring it to balance.

If nanites get sabotaged too much after this PR is merged, I'd be fine to make it harder to do so, however I dont believe that is likely to be a problem as currently nanite sabotage is extremely uncommon.

>One thing that might be helpful is the ability to lock nanite clouds to crew Ids similar to how mechs can be locked to DNA. This way only the person working on the nanites (or someone who had stolen their ID) can lock/unlock the cloud and add/delete programs to it.

I feel that would be too secure, as it is now there's tradeoffs for the various security methods. You can unlink from the cloud which takes time and renders you vulnerable to EMP, you can increase security for the server room, which may not keep out a saboteur.

The goal of this PR is to make nanites less secure, not more secure.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
PR body is incomplete

**Comment by Isy232** [comment]
dont have time

**Pull request closed without merging**
