### PR TITLE
Admin proc call rustg warning tells proc name

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
Minour improvement of 
* https://github.com/BeeStation/BeeStation-Hornet/pull/11863

Admin proc call rustg warning tells proc name
We'd need to know which sorcery they're trying

## Why It's Good For The Game
better investigation

## Testing Photographs and Procedure

image

## Changelog
:cl:
code: minor notification for proc call warning
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Can you HTML inject the proc name?

**Comment by EvilDragonfiend** [comment]
> Can you HTML inject the proc name?

If I am right, there's no href interpreter in DM that allows you to call a customised proc name.

**Comment by EvilDragonfiend** [comment]
Hmm, I think one thing is possible... hang on

**Comment by EvilDragonfiend** [comment]
> Can you HTML inject the proc name?

Hmm, I guess there isn't such thing.

**Comment by PowerfulBacon** [comment]
Does capped input strip away html tags? It wouldn't matter if the proc exists or not if you typed "rustg <h1>test</h1>"

**Comment by EvilDragonfiend** [comment]
> Does capped input strip away html tags? It wouldn't matter if the proc exists or not if you typed "rustg
> 
> # test
> "


> Does capped input strip away html tags? It wouldn't matter if the proc exists or not if you typed "rustg
> 
> # test
> "

image

funnily it says so

image
image

It appears it strips well.

**Comment by PowerfulBacon** [comment]
Oh that's because the / symbol is the splitter for the text, so it's treating anything to the left of </a> as the typepath and not the proc name. Try to do
`rustg<a href='google.com'>`
There's definitely ways to get dangerous scripts without the / symbol since you can use JS to replace the / by char code

**Comment by EvilDragonfiend** [comment]
image
You are right. It was not safe. now done by `rustg_test<a href='www.google.com'>this_is_google`

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
The other ones are vulnerable, but those ones send it to your own chat. Was particularly concerned about this one since it sends to all

**Comment by EvilDragonfiend** [comment]
> The other ones are vulnerable, but those ones send it to your own chat. Was particularly concerned about this one since it sends to all

As long as we are careful of this, it will be good to identify which sorcery they're trying, and will be a good chance to research.

**Pull request merged**
