### PR TITLE
Cult balancing updates

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

- EMP no longer disables channels on the radio headset, instead having the temporary 20 second disable effect like other EMP effects.
- Cult stun will now disable worn headsets for 20 seconds.
- Cult sword reduced from 30 to 23 damage.
- Cult sharpen maximum damage reduced from 40 to 30 damage.
- Cult sword damage reduced to 16 against holy empowered individuals.
- Mirror shield no longer blocks attacks from holy empowered individuals.
- Removes TRAIT_ANTIMAGIC and TRAIT_HOLY and replaces it instead with the component.
- The holy component will now show when you have a holy aura, and will show other people with a holy aura. (Allowing players to see that a bible actually protects them).
- Cultists can now see people with a holy aura by their glow.
- Flagellant's robes armour buffed and speed bonus slightly reduced.

## Why It's Good For The Game

- Makes it a lot more clear why people aren't being affected by magic.
- Allows people to see that something like a bible will actually protect them, rather than being a niche mechanic that few people are aware of.
- Gives the bible reduced damage when attacked by a cult sword, making it an effective replacement for a shield.
- Nerfs cult sword damage, due to its insane power and the fact that cult will likely get a buff to survivability with the upcoming shield update.
- Makes flaggelent robes actually somewhat usable.
- Makes it so that cult won't get called out via cult-slurs on comms early game, making the round pretty boring by disable radio headsets upon stun.
- Negative armour should not be used.

Note that the holy aura will show up to anyone with holy or magic immunity, meaning that while the wizard can see the chaplain glow with magic immunity, they will also see regular people holding bibles glow, despite them not being affected by wizard spells.

This may not seem like much, but the more communicative bibles will hopefully lead to more players realising that bibles protect you from a significant number of cult attakcs which will lead to them having wider use during cult rounds. Even IPCs aren't aware of the bibles granting EMP immunity from cult EMPs, meaning that its probably something that isn't communicated well.

## Testing Photographs and Procedure

image

image

(Note that this doesn't show mindshields, only holy protection)

image

image

image

image

## Changelog
:cl:
balance: Lowers damage of cult sword from 30 to 23. Maximum damage from sharpening reduced from 40 to 30.
balance: Cult stun now EMPs the target's headset.
balance: Holy protection is now visible to anyone with holy protection themselves, and is also visible to cultists.
balance: Flagellant's have postiive armour rather than negative armour, making them somewhat viable.
balance: Holy protection will now allow you to bypass the mirror shield's blocking, and will result in taking reduced damage from cult swords.
balance: EMPs will no longer disable all your channels on radio headsets, instead temporarilly disabling them for 20 seconds similar to other EMP effects.
/:cl:

### CODE REVIEW

**Comment by BlueHNT** [comment]
Holiness should mess with the EMP a bit more, I think. It is such a potent tool that it changes the entire fight advantage to be a near free win for cult every single time.

As in holy people don't get affected as much or at all by them or holy areas disable some certain spells like the EMP.

**Comment by PowerfulBacon** [comment]
Holyness already disables the EMP effect, and blessed tiles are immune to the effects of the EMP. It's just not clear when you have holiness (with a bible, it must be in your hands, it cannot be on a suit slot or in the bag)

**Comment by MarkusLarsson421** [comment]
> Cult stun will now disable worn headsets for 20 seconds.

Cult stun is already long enough to zip-tie and remove their headset with some margin of error unless they are wearing a full face mask. Is it really needed?

**Comment by PowerfulBacon** [comment]
It lowers the chance that they get outed early on by making it harder to fuck up, so I think so

**Pull request merged**
