### PR TITLE
Nature Sect Fix - Stops the orb from replacing open-space tiles and blocking off stairs

### PR DESCRIPTION
**Pull request by ro5490**
## About The Pull Request

Fixes an issue regarding open-space tiles getting replaced

## Why It's Good For The Game

Fix good yes

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

N/A

</details>

## Changelog
:cl:
fix: fixed openspace tiles being replaced by a nature orb
/:cl:

### CODE REVIEW

**Comment by ro5490** [comment]
afaik this should fix the bug, ready for review <3 <3

**Review by PestoVerde322 — COMMENTED** [review]
I'd suggest to also add the following:
- `/turf/open/floor/plating/beach` (may override Echostation's water turfs and sand/shore tiles)
- `/turf/open/indestructible` (obvious reason, only actual indestructible turf in the station is `/turf/open/indestructible/sound/pool`, but for good measure let's add also all the other indestructible ones)
- `/turf/open/floor/prison` (potential Genpop cheeseing?)

**Comment by ro5490** [comment]
> I'd suggest to also add the following:
> 
> * `/turf/open/floor/plating/beach` (may override Echostation's water turfs and sand/shore tiles)
> * `/turf/open/indestructible` (obvious reason, only actual indestructible turf in the station is `/turf/open/indestructible/sound/pool`, but for good measure let's add also all the other indestructible ones)
> * `/turf/open/floor/prison` (potential Genpop cheeseing?)
Good idea, ill add them in, same for the shadow sect update

**Review by PestoVerde322 — APPROVED** [review]
All good then, Approved!

**Pull request merged**
