### PR TITLE
Fixes issue where some items had `ABSTRACT` while they shouldn't

### LINKED ISSUE #10962: [Bug]: Cannot Throw/Store into bags Poppies
### BYOND Version

514.1589

### Round Date

2024\05\13

### Round ID

48627

### Test merges

#9124: 'Enable serverside 515.1633' by Crossedfall at commit 3e63a01a0a
#10811: 'Revolution 2.0: Now the gamemode works' by Miliviu at commit c224c494fc
#10912: 'Temp Revert "Updates the hub entry"' by Crossedfall at commit 2268617730

### Describe the bug

Trying to put poppies into a bag does nothing except keeps them in your hand. No announcement is given nothing. Also throwing them does work not either.

I did not try this with other flowers,.

### What did you expect?

They were to be more functional, rather than plain block of nothing.

### Reproducible steps

1. Pick up a poppy
2. Try putting it in your bag
or
3. Throw them.

### LINKED ISSUE #10963: [Bug]: Cannot put Pets in bagpack (IMPORTANT)
### BYOND Version

_No response_

### Round Date

_No response_

### Round ID

_No response_

### Test merges

_No response_

### Describe the bug

Basically you're unable to put pets/animals on a bagpack, according to @Tsar-Salat it's because they have a flag of ABSTRACT, making the issue so it's recorded

### What did you expect?

I expected to be able to secure the loyal pet into my Bagpack to protect them from threats and take them to CC 

### Reproducible steps

1. Pick Runtime/Walter/Ian/Corgi/Kalo/Ect
2. Try to put it on your bag
3. You can't!!!!

### PR DESCRIPTION
**Pull request by BlueHNT**
## About The Pull Request
I am pretty sure this shouldn't be here; it caused all flowers/pets to be unable to put into bags.

Fixes: #10962 
Fixes: #10963 

## Why It's Good For The Game
Makes flowers baggable again. Same for pets.

## Changelog
:cl:
code: fixes known ABSTRACT issues
:cl:

### CODE REVIEW

**Comment by BlueHNT** [comment]
Hm, im stupid

**Comment by Fronsis** [comment]
I think the issue with Pets is the same they have a random abstract flag

**Comment by PowerfulBacon** [comment]
Ah, seems like a case where someone misunderstood abstract to not be a non-physical item but instead abstract in programming

**Comment by BlueHNT** [comment]
Damn, my spellchecking is almost as shoddy as my code.

**Comment by Fronsis** [comment]
Someone that doesn't have a GH account wanted me to add that apparently beakers(large beaker was used) that have activated black powder(or maybe it's with any reagent) also makes you unable to throw them, perhaps they somehow also got this abstract flag

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
