### PR TITLE
QoL remapping to turbine and toxins

### PR DESCRIPTION
**Pull request by Tsar-Salat**
## About The Pull Request
This PR remaps all 7 map's turbine and toxins area. Included are the repiping of distro and waste pipes, replacing the airlock viewports with radproof glass, and misc QoL changes.

Anticorners were properly utilized during all decal changes, in compliance with " the turf-decalening"

## Why It's Good For The Game

Incinerator airlocks (present in both toxins and the turbine) have long been a feature that haven't properly worked as intended. The controller has limited control over its airlock and necessitated additional unnecessary features like a dual-port vent to be present, else the player attempting to cycle the airlock would be stuck in an infinite airlock cycle. This has generally been seen as a code issue thus far, but by replacing the incinerator-specific airlock controller with the generic "advanced airlock controller", the airlock system has become much more customizable and has reduced dependencies. The airlock now quickly cycles in under a second, and allows the user to define airlock override times as well as specific pressures during cycling.

While this was my primary goal, gutting the obsolete features of the old airlock controller allowed me to make several additional Quality of Life changes to the turbine and toxins:

- The airlock viewports have been replaced with radproof glass, especially in turbine where tritium and fusion burns are often done, reducing their potential radiation spread. (Generally considered an unwanted and sometimes ban-worthy byproduct)
- Several awkward pipe formats for the distro and waste system have been repiped in much more clean manner now that the dual-port vent has been removed.
- The Turbine's r-wall's have all been replaced with standard iron walls, allowing greater customizability. Toxins was exempt from this change to preserve it's structural integrity.
- Decals, buttons, and apcs/air alarms have been remapped to fit the new system

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl: rkz
add: Added generic-airlock system
add: Added iron walls and radproof glass to replace viewports
del: Removed incinerator-specific airlock system
tweak: streamlined distro and waste system in toxins and turbine

/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
> Anticorners were properly utilized during all decal changes, in compliance with " the turf-decalening"

Unbelievably based

**Comment by itsmeow** [comment]
```
 _maps/map_files/CorgStation/CorgStation.dmm:"tid" = (
/obj/structure/lattice,
/obj/structure/lattice/catwalk,
/turf/open/space/basic,
/area/space/nearstation)
```

**Comment by Tsar-Salat** [comment]
DNM

**Comment by Tsar-Salat** [comment]
merge! Tatakae!

**Comment by Tsar-Salat** [comment]
uhhh wut

**Comment by Tsar-Salat** [comment]
uhhhh rkz did a fucky

**Comment by Tsar-Salat** [comment]
wow, well thats funny

**Comment by Tsar-Salat** [comment]
kabam, saved from the abyss

**Comment by Tsar-Salat** [comment]
gonna need to atomize this, sorry. Dont really know how to fix the AAC frankly. I'm just going to make the remap pr separate from the AAC fix and go from there

**Pull request closed without merging**
