### PR TITLE
Revises Eldritch Knowledge Tech-Tree

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Requires #3506
Revises the Heretic Knowledge Tech, to look more like this:

image

* Void Cloak Available to Rust and Ash
* Carving Knife available to Flesh and Ash
* Crubicle available for rust and Flesh
* Eldritch Vial of Water is now available at start for all heretics
* Paralysis/Corrosion Curse removed
* Alteration Curse now available roundstart for all Heretics

## Why It's Good For The Game

Heretics are in a weak state right now. They lack a lot of gear and are generally really weak when compared to any other antag.

### Void Cloak
This is a nice stealth item that allows you to hide your items. It allows you to hide items in it, and the item itself is invisible when worn.
Naturally, available for Rust and Ash as an alternative to Heretic Armor, because these paths are the ones that should try stealth/silently.

### Carving Knife
This item is a neat for dealing with validhunters. It has tracking runes (which alert you when they are crossed), block runes and stun runes. They are a great way to deal with validhunters and are overall powerful items. Not so great as weapons.
Available for Ash and Flesh Path, because these are the most likely to deal with validhunters.

### Crubicle
Another great addition for the agressive heretics. Allows you to enhance your vision, pass through walls and enhance your combat abilities. Definitely worth investing 1 point into it.
Great overall item for solo heretics who want to go loud. (Might be too good for flesh, that is why they are not available to them.)

### Eldritch Water
This item was quite weak and generally not worth investing a point in it. It offers quite little for the point and is generally disregarded/skipped and ignored entirely. The bottle is super obvious.
Made free because heretics are usually weak 1 on 1 and the healing really benefits them. 

### Curses
Newbie trap and waste of points. They require a rare to find item, are hard to prepare and definitely not worth it. Usually ignored completely and rushed past. Removed entirely. 
Replaced instead with alteration curse, which combines all the past 3 curses. Available roundstart because it really is not very powerful on its own, requires quite some setup (harvesting limbs, organs and, worst of all, obtaining an item your target has touched). The mechanic is neat and expands on heretics. It's also a nice gimmick mechanic.

## Changelog
:cl:
add: Void Cloak Available to Rust and Ash
add:  Carving Knife available to Flesh and Ash
add:  Crubicle available for rust and Flesh
add:  Eldritch Vial of Water is now available at start for all heretics
del: Paralysis/Corrosion Curse removed
add:  Alteration Curse now available roundstart for all Heretics, which combines all the three curses
/:cl:

### CODE REVIEW

**Comment by eeSPee** [comment]
Waiting for feedback/input. If this gets favorable reviews/approval, I will fix conflicts.

Also, I don't like the Void Path. I thought about porting it, but it's everything ash wanted to be, and more! The grasp mutes your target so they can't instantly shout "YOURNAME is heretic in maints!", which is already part of all mansus grasps. No breath requirement, the blink and blink-on attack already puts it on top of all other paths. The fact that both crubicle and carving knife are available to it, while ash gets 2 shitty curses, makes it 'Ash Path, But Better'

**Comment by eris-webserv** [comment]
im thinking of getting into playing BeeStation, and I would love to see this

**Comment by Cenrus** [comment]
Eldritch water is one of the better heretic items, easy to get, with some modest stamina healing too

**Comment by ike709** [comment]
"Requires" a closed PR.

**Pull request closed without merging**
