### PR TITLE
515 Compat [DRAFT]

### PR DESCRIPTION
**Pull request by dwasint**
## About The Pull Request
https://github.com/tgstation/tgstation/pull/71161
https://github.com/tgstation/tgstation/pull/71333
gets us ready for 515

uses 
Update all /type/.proc/name and /type.proc/name to TYPE_PROC_REF(/type, name)
`(/[^\s]*?)/?\.proc/(.*?)([,)])`
`TYPE_PROC_REF($1, $2)$3`

Remaining .proc/name to PROC_REF(name)
`\.proc/(.*?)([,)])`
`PROC_REF($1)$2`

moving standalone /proc/name to GLOBAL_PROC_REF(name)
`, /proc/(.*?)([,)])`
`, GLOBAL_PROC_REF($1)$2`

for regex
and manually cleaned the missed ones

## Why It's Good For The Game
bigger number means better server

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Holy crap, how did 515 screw up so many things

**Comment by dwasint** [comment]
> Holy crap, how did 515 screw up so many things

they changed how calling proc works thats the bulk of these changes lol

**Comment by dwasint** [comment]
also i'm 90% sure this is done and auxtools is the reason it don't run atm

**Comment by itsmeow** [comment]
Yes auxtools is what is stopping us from bumping.

**Comment by itsmeow** [comment]
Closing without keys due to both being 4 months stale, a draft, and superseded

**Pull request closed without merging**
