### PR TITLE
Ports Radial Janicart Menu

### PR DESCRIPTION
**Pull request by Isy232**
## About The Pull Request

Ports https://github.com/tgstation/tgstation/pull/50806

Credit to Arkatos1 for the original code.

I had to change a few things around because bee has no broom or light replacer to be attached to the cart.

> This PR replaces a janitorial cart HTML UI with a radial menu, which is used for taking various janitorial items out of it.

https://user-images.githubusercontent.com/43862960/80849806-26b9c000-8c19-11ea-89d1-652192124800.png

Tested locally, it works fine.

I should be studying, but instead I saw this and thought to port it instead... shit.

## Why It's Good For The Game

> Better handling of the janitorial cart.

## Changelog
:cl:
add: Janitorial cart now uses a radial menu
/:cl:

### CODE REVIEW

**Comment by Isy232** [comment]
Right, ignore all the other attached commits it says, this doesn't change those files.

**Comment by knacker48** [comment]
I skimmed the title and thought that the Janicart would now be all cool with a backwards cap and sunglasses

**Comment by Isy232** [comment]
Sadly, no, just radial like an RCD

**Comment by ike709** [comment]
> or light replacer

We do have a light replacer, though?

Also, you seem to have removed the code for putting wet floor signs on the cart.

**Comment by Isy232** [comment]
Right, a few issues, this is broken more than I thought it was, perhaps I will fix it but closing for now since I likely wont be able to for a while.

**Pull request closed without merging**
