### PR TITLE
Makes a new subtype of labcoat that can store medkits, makes medkits bulky

### PR DESCRIPTION
**Pull request by Rukofamicom**
## About The Pull Request
* Adds a new subtype of labcoat capable of storing medkits in the suit slot, utilized by CMO, Doctors, Paramedics and Brig Physician
* Makes all medkits bulky items except for the syndicate one
* Makes the beecoin EMT Labcoat available to paramedics, because for some reason it wasn't. (I will make a separate PR for this if this one gets closed)
* Removes access to the EMT Labcoat from Geneticist and Chemist

## Why It's Good For The Game
**Bulky Medkits** - Strongly encourages normal crew to seek medical items only after they are needed instead of stashing entire medkits in their bags for later "just in case". I expect the availability of the normal white medkits will go up with this change since they are substantially more likely to remain in their initial spawn locations - crew with a habit of swiping medical supplies are not likely to dump the entire kit into their bags. 
**Suit Storage** - To minimize the impact of this change on medical staff which are actually expected to make extensive use of medkits throughout their shifts. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

CMO
image

Doctor
image

Paramedic
image

Brig Physician
image

Two sizes of medkit;
image
image
</details>

## Changelog
:cl:
code: Added a new subtype of labcoat used by doctors, and shifted the CMO, paramedic and brig physician typepaths into this subtype
tweak: All doctor labcoats can now store medkits in their suit storage slot
tweak: Medkits are now bulky items that cannot be stored in bags, with exception to the syndicate combat medkit. 
fix: Paramedics can now add the EMT Labcoat from the beecoin shop to their loadout. Geneticists and Chemists have lost access to this loadout option. 
/:cl:

### CODE REVIEW

**Comment by DarnTheMarn** [comment]
I don't see this addressing the behavior, anyone with a brain will just dump it and grab the bruise packs and ointment. You have basically infinite space for tiny items like that since you can put them in boxes in your bag as well as inside boots and armor. Maybe changing bruise packs and ointment to not be stackable?

**Comment by Rukofamicom** [comment]
> I don't see this addressing the behavior, anyone with a brain will just dump it and grab the bruise packs and ointment.

I think you might be overestimating the power of intuitive gameplay, or potentially attributing malice where there is simply ignorance for most. Players who just casually pick up a medkit and stash it do so because they're able to, not necessarily realizing the fact it's something they shouldn't do because is an item acceptable and available for public use. Add onto this that it's often done without anyone (like staff) noticing to tell them they shouldn't unless they're being actively inspected later or watched at the moment they have done so.

The point of the PR isn't to rebalance medkits - it's to make it more intuitive that they aren't supposed to be swiped and carried around immediately (except by doctors) by adding a low barrier to doing so. A barrier antagonists (and by extension, powergamers) can overcome if they wish with a little bit of extra effort (obtaining cardboard, assuming they are already utilizing their box). Powergamers taking those extra steps are bypassing what is intuitive - and no matter what we change with code, powergamers will still find a way to powergame in the end.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by lowwy** [comment]
@Rukofamicom possible to add "The Mad's labcoat" to the special medkit wielding labcoat list aswell?

**Comment by Rukofamicom** [comment]
Can you give justification to why @lowwy ? 

It's not a medical labcoat in any sense (Mad scientist) and is available from costume vendors. Chemists and Scientists do not have access to medkit storage and this seems like a coat primarily aimed for use by them.

**Comment by lowwy** [comment]
> Can you give justification to why @lowwy ?
> 
> It's not a medical labcoat in any sense (Mad scientist) and is available from costume vendors. Chemists and Scientists do not have access to medkit storage and this seems like a coat primarily aimed for use by them if anyone.

For me when I think of "Mad scientist" I think of Doctor Victor Frankenstein, Turning humans into abominations. (2 parts felind, 1 part lizard, 4 parts apid)

_Also i'm biased because I sometimes want to style myself in maddening green as MD._

**Pull request merged**
