### PR TITLE
Ports sects, addiction rework and some stuff

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Ported:
https://github.com/tgstation/tgstation/pull/56923
https://github.com/tgstation/tgstation/pull/57826
https://github.com/tgstation/tgstation/pull/57638
https://github.com/tgstation/tgstation/pull/57854
https://github.com/tgstation/tgstation/pull/58170
https://github.com/tgstation/tgstation/pull/58172
https://github.com/tgstation/tgstation/pull/57820
https://github.com/tgstation/tgstation/pull/48994
https://github.com/tgstation/tgstation/pull/53023
https://github.com/tgstation/tgstation/pull/56717
https://github.com/tgstation/tgstation/pull/55246
https://github.com/tgstation/tgstation/pull/58291

Requires #4219 to be merged first.

Addiction rework:
Removed existing addictions. Add 6 new addictions Stimulants, Opioids, Alcohol, Hallucinogens, Maintenance drugs, Nicotine. 
Read more about them in original PR.

New sects (main focus of this believe it or not):
- Greedy God - pay money for rites, make more money.
- Honorbound God - you cannot attack anyone. You can deem someone evil to attack them, or he can be deemed evil if he attacks you.
- Burdened God - stack up bad effects (such as being blind, addicted, bad mutations etc) to gain powers.
- Maintenance God - eat mold, live in maint, become addicted to drugs.
Also includes small re-theme to existing sects (such as renaming puritans to Nanotrasen Approved God and other stuff).

Vend-a-tray and card reader stock part:
card reader - doesn't really do anything on its own, but is part of vend a tray.
From original pr:
"The Vend-A-Tray is the real jewel here, it requires a Card Reader and it functions as a subtype of the Display Case. It's currently meant as a chef/bartender/service exclusive feature, as it by default requires kitchen access to use. First, using an ID on the structure will register your ID to the tray. Then, using a multitool on the machine will allow you to set a custom price for the contained item. Food items go into the Vend-A-Tray, and are visible from the outside. Once closed, Ctrl-Clicking the item will dispense the object into your hands, and gives money to the registered user's account, NOT the department's budget."

Filters:
Refactors filters and adds new VV option "Edit filters".
68747470733a2f2f66696c652e686f7573652f634d64332e706e67

## Why It's Good For The Game

More sects.
Better addictions.
Stuff

Wikichanges when approved.

## Changelog
:cl: floyd, tralezab, prodirus, Time-Green, ArcaneMusic, actioninja, LemonInTheDark
add: All drug addictions are now put into 5 categories: Stimulants, Opiods, Alcohol, hallucinogens, maintenance drugs and nicotine. There is no longer an addiction threshold and becoming addicted is done by gaining addiction points from doing drugs in a specific category, if you become addicted you can stop being addicted by lowering your addiction points until it reaches a low enough value.
 add: Added four new sects to the altar of the gods, for some very unique deities.
add: Nanotrasen's Customer Service Division has developed a new, shielded product cage to better allow for sale of food and drink items on station, called the "Vend-A-Tray".
add: Vend-A-Trays are made with display case frames and a Card Reader stock part, now available at all protolathes.
add: New filter editor for admins + development purposes
/:cl:

### CODE REVIEW

**Comment by eeSPee** [comment]
Atomize?

Edit: Seriously, if the vent fail and have to be reverted, the sects and other stuff will be reverted as well.

**Comment by PowerfulBacon** [comment]
this is like 5 completely unrelated PRs bundled into 1 shitshow

**Comment by Archanial** [comment]
They are all related to each other.

**Comment by PowerfulBacon** [comment]
A filter TGUI menu for admins, 4 new sects, reworked addictions and a new vendor for the chef shouldn't be in the same PR

**Comment by eeSPee** [comment]
> A filter TGUI menu for admins, 4 new sects, reworked addictions and a new vendor for the chef shouldn't be in the same PR

The maints sect relies on addictions, and the money sect relies on the vendors.

I think this PR should be atomized into:
* TGUI menu
* addictions + maints sect
* vendor + money sect
* the remaining 2 sects

Or port the sects after.

**Comment by tralezab** [comment]
hahaha i see you're a fan of my work, or at least 1/6th of your pr is! thank you!

**Comment by Kylerace** [comment]
did you make a bet for largest PR or something?

**Comment by Fikou** [comment]
me and my pr are not credited for the sect altar sprites youre going to JAIL buddy

**Comment by Archanial** [comment]
> me and my pr are not credited for the sect altar sprites youre going to JAIL buddy

😳

**Comment by Sinestia** [comment]
god what is this abomination

**Pull request closed without merging**
