### PR TITLE
Makes crewsimov the default AI lawset on golden.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Title.

## Why It's Good For The Game

There is no reason for asimov to be the norm since all it's used for is give the AI a reason to grief non-humans, but even shittier it forces the AI to protect human antags like wizards and nukies (you'd be suprised by how often they dont change the laws), and makes security being able to de-crew people a redundant feature.

## Changelog
:cl:
tweak: Crewsimov is now the default lawset on golden.
/:cl:

### CODE REVIEW

**Comment by VictorVow** [comment]
Add a crewsimov board to the AI upload chamber also, useful when needing to reset the AI.

**Comment by ghost** [comment]
> Add a crewsimov board to the AI upload chamber also, useful when needing to reset the AI.

done

**Comment by TeomanTheGreat** [comment]
Fuck non-humans all my homies hate non-humans besides having the ai on your side is one of the few upsides of being human.

**Comment by ghost** [comment]
> Fuck non-humans all my homies hate non-humans besides having the ai on your side is one of the few upsides of being human.

the upside of being human is that you dont have to deal with any damage multipliers that other races have.

**Comment by VictorVow** [comment]
Also medbay has the easiest time healing and reviving you, plus can use Hulk mutators, and the race has no distinct flaws.

**Comment by PowerfulBacon** [comment]
The asimov borg is a crewsimov borg since you can rename it, so it's in there anyway

**Comment by Blueturbo47** [comment]
As a Non-Human I still don't support these changes, ai's on crewismov make shifts more boring.

**Comment by ghost** [comment]
> As a Non-Human I still don't support these changes, ai's on crewismov make shifts more boring.

you can change them.

**Comment by TeomanTheGreat** [comment]
> > As a Non-Human I still don't support these changes, ai's on crewismov make shifts more boring.
> 
> you can change them.

Lol laws are only really changed to either subvert ai or make meme laws ive never seen someone change laws just because they like the lawset.

**Comment by eLeCtrOssSnake** [comment]
Yeah, it should be the norm, even on both servers. As an alternative I would make a possibility on NT lawset, cuz it seems logical to do from NT's perspective.

**Comment by eLeCtrOssSnake** [comment]
Also speaking from non-human perspective.

**Comment by Crossedfall** [comment]
Crewsimov tends to make more sense in chiller role-play settings where cooperation tends to be the focus. That doesn't _really_ fit in here.

**Pull request closed without merging**
