### PR TITLE
Nymph Swarm midround event

### PR DESCRIPTION
**Pull request by Therealdoooc213**
## About The Pull Request

Adds a new event, 'Nymph Swarm' that spawns 5 nymphs across the station, always next to vents

## Why It's Good For The Game

New way for people to get into the round if they're dead, or round removed in one way or another

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.
image

</details>

## Changelog
:cl: Therealdoooc
add: Adds the Nymph Swarm event, a new way for ghosts to get into the round (or a new food source)
/:cl:

### CODE REVIEW

**Comment by Nakalon** [comment]
cool!

**Comment by MarkusLarsson421** [comment]
> New way for people to get into the round if they're dead, or round removed in one way or another

Haven't played around with nymphs yet, but they aren't exactly the most interesting species to play as. Right? Aren't you just another simple mob?

**Comment by Fronsis** [comment]
> > New way for people to get into the round if they're dead, or round removed in one way or another
> 
> Haven't played around with nymphs yet, but they aren't exactly the most interesting species to play as. Right? Aren't you just another simple mob?

Nymphs start as a simplemob that can't speak but they start growing until they become a fully adult Dionae, thus a ''respawn'' mechanic

Though, if i remember correctly.. Wouldn't those nymphs grow to adult and be limb-less Dionaes since they have no other nymphs to get their limbs? that would be kinda annoying or i guess they can grow next to botany(if there's botanists)

**Comment by Therealdoooc213** [comment]
> 
> Though, if i remember correctly.. Wouldn't those nymphs grow to adult and be limb-less Dionaes since they have no other nymphs to get their limbs? that would be kinda annoying or i guess they can grow next to botany(if there's botanists)

I forgot the specific timer, but fully grown diona can make their own nymphs after a period of time, They'd just have to wait a bit or ask other diona for a spare nymph

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
Have this event check for the existence of nymphs beforehand. This will water down random events in cases where nymphs are already available on the station!

**Comment by Therealdoooc213** [comment]
> Have this event check for the existence of nymphs beforehand. This will water down random events in cases where nymphs are already available on the station!



> Have this event check for the existence of nymphs beforehand. This will water down random events in cases where nymphs are already available on the station!
I'm unsure about this, nymphs wont always be in habitable locations, they also might be off-station on lava-land, + more nymphs the better :)

**Comment by Rukofamicom** [comment]
> more nymphs the better :)

This is not always the case. If there's more than 10 or 20 nymphs already, this event probably does not need to fire.

**Comment by Therealdoooc213** [comment]
> This is not always the case. If there's more than 10 or 20 nymphs already, this event probably does not need to fire.

Good point, I'll see what i can do for this

**Review by Rukofamicom — APPROVED** [review]

**Pull request merged**
