### PR TITLE
Changed the health analyzer icon back to the original one

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
So many people want this changed. I'm just doing what a load of people and I think is best.

## Why It's Good For The Game
The icon fits in a lot better. The new one looks like it's outta starbound, and many people think it looks like a toy.

## Changelog
:cl:
change:Changed Health Analyzer back to it's original icon.
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
No

**Comment by GreenTea988** [comment]
do it u won't @qwergy

**Comment by MarkSuckerberg** [comment]
ples qwerty

**Comment by qwertyquerty** [comment]
new one is far better

**Comment by ike709** [comment]
@qwertyquerty New one looks terrible.

**Comment by prophed** [comment]
oh oh

**Review by ondrej008 — APPROVED** [review]

**Comment by ike709** [comment]
image

**Pull request merged**
