### PR TITLE
Allow AI and IPC to start their name with a number or special char

### PR DESCRIPTION
**Pull request by yorii**
## About The Pull Request

Just a simple fix to allow AI and IPC to start their names with a number or the short list of allowed special chars, instead of arbitrarily enforcing a letter for the first character.

## Why It's Good For The Game

Roleplaying a serial number.

## Changelog
:cl: yorii
tweak: AI and IPC can begin their name with a number or certain allowed special characters.
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
inb4 html injection

**Comment by yorii** [comment]
I'm sure name strings are used in a perfectly sanitized manner.... right?

**Comment by yorii** [comment]
I think " would be needed to break out of a string in BYOND? Or maybe backslash is bad too since you could maybe do text macros  in namestrings? I'll test it later. Forwardslash should be fine since it's not used by anything except math in byond.

**Comment by yorii** [comment]
Yeah uhm.. I was sort of right, the strings are sanitized, thus removing all forwardslashes and backslashes even if they were to be allowed here :) so I removed the additional special chars.

**Comment by yorii** [comment]
speedmerge plz this is a good roleplay change!

**Comment by PowerfulBacon** [comment]
> 
> 
> I'm sure name strings are used in a perfectly sanitized manner.... right?

Nope!

If there is a HTML injection, this won't make it come out since you would already be able to do it just putting an a at the start.

**Review by PowerfulBacon — COMMENTED** [review]
Doesn't this allow everyone to start their name with numbers or a special char?

**Comment by yorii** [comment]
Nope, only races/mobs with allow_numbers set to TRUE will be able to have numbers or special chars in their name whatsoever.

Essentially not much difference from how it is today, except it will not deny names starting with a number or special char for mobs with allow_numbers set to TRUE.

And yeah trying to add slashes was a complete brainfart, it would probably result in horrible things happening if it was accepted 😄

**Comment by yorii** [comment]
this time I tested it btw :)

**Comment by ike709** [comment]
Violates naming policy for IPCs and I think it's a bad idea.

**Comment by yorii** [comment]
@ike709 I only did this specifically because of the naming policy for IPCs, why would a serial number always start with a letter and not start with a number?

**Pull request closed without merging**
