### PR TITLE
Moves input bar under the chat

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Try two. Because Crossed said he liked it. 
It doesn't remove 3px border from the left.

## Why It's Good For The Game

obraz
obraz

ported:
https://github.com/Skyrat-SS13/Skyrat-tg/pull/1366

## Changelog
:cl:
tweak: Input bar is now under chat.
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
I like

**Comment by ike709** [comment]
Didn't this already fail a vote?

**Comment by Archanial** [comment]
> 
> 
> Didn't this already fail a vote?

This + 3px border was 50/50 when you said it failed the vote.
This pr was made 100% because Crossed himself said he likes it.

**Comment by francinum** [comment]
Affects literally nothing on a technical level but does make 2x mode slightly better at my DPI.

**Review by francinum — DISMISSED** [review]

**Comment by Crossedfall** [comment]
This seemingly was fine during TM. It'll take some getting used to, though.

**Comment by Crossedfall** [comment]
Another wave of testing just to give people a longer chance to see how it all looks

**Comment by Crossedfall** [comment]
The following was formed from 78 in-game votes (had to have at least 1-hour of playtime to vote)

image

**Review by Crossedfall — APPROVED** [review]

**Comment by thatguythere03** [comment]
Really not a fan of this. I'd be fine if it was something you could toggle on and off in preference however.

**Pull request merged**
