### PR TITLE
makes felinids say_mod "annoyingly meows"

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

makes felinids have "annoyingly meows" infront of their text instead of "says"

## Why It's Good For The Game
it isn't

## Changelog
:cl:
tweak: felinids now annoyingly meow when talking.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
grafik
what made me do this in the first place

**Comment by PowerfulBacon** [comment]
> 
> 
> grafik
> what made me do this in the first place

this doesn't make it a good idea 😑

**Comment by ghost** [comment]
´

> 
> 
> > grafik
> > what made me do this in the first place
> 
> this doesn't make it a good idea 😑

grafik

**Comment by qwertyquerty** [comment]
Unfunny

**Comment by ghost** [comment]
Funny

**Comment by PowerfulBacon** [comment]
Unfunny

**Comment by boolsrealm** [comment]
Funny

**Pull request closed without merging**
