### PR TITLE
new useful traitor-drink for bartenders

### PR DESCRIPTION
**Pull request by boolsrealm**
so i got a drink here thats pretty hard to make, requires access to a chem dispenser, ground-up plasma, and alot of mixing. 

what it does is set you on fire but heals you for the fire damage you take, and it metabolizes decently fast. 

requires napalm, plasma, tequila, and demons blood (the drink)

its intended for melee combat, since if you wear a firesuit before drinking this you can safely set people on fire without having to worry about taking any damage yourself. the downsides are that you'll eventually start taking actual burn damage from it due to the rising heat if you take too much, it has a decently high alcohol content, you aren't extinguished when the healing wears off, and you have to wear something like a firesuit that slows you down or else all your clothes burn off.  

i think that bartenders don't have enough when it comes to what they can do as a traitor. they have like, neurotoxin and bacchus' blessing for decent poisons, but that's all i can actually think of. something like this will give them something for a more direct approach to combat instead of just shotgunning.

sprite looks like this:
https://i.gyazo.com/6e8803e9e3ddd1ed47a0e20ba42872e3.png

### CODE REVIEW

**Comment by ghost** [comment]
wtf are those commits?

**Comment by boolsrealm** [comment]
i changed the alcohol_reagents file like 5 times hehe xd

**Comment by St0rmC4st3r** [comment]
The description has a typo. "not reccomend" -> "not recommended"

**Comment by boolsrealm** [comment]
ok i should probably fix the commits and then that typo so hold on

**Pull request closed without merging**
