### PR TITLE
Ports sushi and adds seafood crafting tab

### PR DESCRIPTION
**Pull request by PatienceStPim**
## About The Pull Request
Ports several sushi-related things from tg and adds seafood to the crafting tab.

- https://github.com/tgstation/tgstation/pull/66380 Seaweed sheets added to the bio-generator, two types of sushi rolls that can be cut up into smaller sushi slices.
- https://github.com/tgstation/tgstation/pull/67239 Ingredients can be added to a seaweed sheet to create custom sushi
-  https://github.com/tgstation/tgstation/pull/77516 Two more types of sushi roll
- https://github.com/tgstation/tgstation/pull/68390 Adds onigiri, which can be customized, and nigiri
- https://github.com/tgstation/tgstation/pull/71914 Changes how rice works, making the water/rice reaction no longer need a bowl. Foods that make use of rice bowls now instead require boiled rice and a bowl.

Additionally, seaweed sheets can be picked up using the plant bags in botany, and added to the smart fridge.
Sprites are from the original prs made by [MidoriWroth](https://github.com/MidoriWroth)

## Why It's Good For The Game
More cute food! Opens up more gimmicks for chefs.
Rice changes make sushi not eat all 20 bowls (which I don't think are renewable), and make rice easier to make overall.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Screenshot 2024-08-22 183559
Screenshot 2024-08-22 183516
Screenshot 2024-08-22 183534
Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
Patience, [MidoriWroth](https://github.com/MidoriWroth)
add: Sushi & Seafood crafting tab
add: Seaweed sheets added to biogenerator
imageadd: Sprites for sushi
balance: Uncooked rice is now made from mixing 10 units rice/water in any container, no longer requiring a bowl to do so. Recipes that previously used bowls of rice now need boiled rice and a bowl, instead.
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
Cool stuff

**Review by Rukofamicom — APPROVED** [review]
I love seafood

**Comment by BriggsIDP** [comment]
I see food, i heart it

**Review by PowerfulBacon — APPROVED** [review]
Oh sick, we should start thinking about the amount of food categories and organisation on the crafting menu at some point since its starting to get out of hand

**Comment by PatienceStPim** [comment]
I can shove them into the meat/misc categories if you prefer

**Review by Rukofamicom — APPROVED** [review]

**Pull request merged**
