### PR TITLE
makes approaching sound better

### PR DESCRIPTION
**Pull request by nikk735**
chad bee station sound vs old approaching tg sound 
New sound: https://cdn.discordapp.com/attachments/605179594617782302/769652161730576434/ApproachingTG.ogg

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I like the sound as a whole, but I think the robotic / AI voice works better for the context. Also are we even allowed to use this?

**Comment by nikk735** [comment]
we are allowed to use this ya @nathan_does_voices on ig said it.

**Comment by nikk735** [comment]
Put it to vote imo

**Comment by katebishop49** [comment]
i made the sound better if someone wants. added a radio crak and a robotic voice

just dm me for it

**Comment by nikk735** [comment]
> i made the sound better if someone wants. added a radio crak and a robotic voice
> 
> just dm me for it

send it here

**Comment by qwertyquerty** [comment]
sounds like cum zone

**Comment by nikk735** [comment]
> sounds like cum zone

thats kinda why I liked it ngl

**Comment by nikk735** [comment]
Archanial made a better pr use that one instead https://github.com/BeeStation/BeeStation-Hornet/pull/2821

**Pull request closed without merging**
