### PR TITLE
removes replacement envirosuits

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
let's see:
fireproof jumpsuits with auto-extinguishers
spaceproof helmets with hearing protection
considering skinsuits are a thing, replacing plasmaman suits is no longer as hard now. these things are a bit powerful for people without the downsides blasmen have

## Why It's Good For The Game
the replacement suits was always a bad idea

## Changelog
:cl:
del: removed replacement envirosuits
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Why not just remove the hearing protection from non security plasma suits

**Comment by Isy232** [comment]
And their auto extinguishers, its not hard to keep a pocket fire extinguisher with you.

**Comment by zeskorion** [comment]
cuz i think replacement envirosuits were a bad concept to begin with

**Comment by PowerfulBacon** [comment]
How would you get a new suit in case you lost it via death or any way like that?

**Comment by ghost** [comment]
> How would you get a new suit in case you lost it via death or any way like that?

cargo

**Comment by zeskorion** [comment]
> How would you get a new suit in case you lost it via death or any way like that?

a skinsuit will suffice, an emergency firesuit and helmet will suffice, etc

**Comment by ike709** [comment]
Just block humans from using them. They should be plasmamen-only.

**Comment by zeskorion** [comment]
> Just block humans from using them. They should be plasmamen-only.

tell me when you think of a practical way of doing so. I've toyed with the idea of adding an "envirosuit painter" that can change envirosuit colors, though

**Comment by thelaughingbomb** [comment]
A human who wears a enviro suit wont benefit from the self extinguisher anyway, so if replacement helmets had no hearing protection then its just a space helmet with a lamp and welding mask.

**Comment by ike709** [comment]
@zeskorion have `mob_can_equip()` return false if they're not a plasmaman and give `to_chat()` feedback. Easy.

**Comment by eLeCtrOssSnake** [comment]
I would like them to be plasmamen only. Ike is pretty right on this one.

**Pull request closed without merging**
