### PR TITLE
Winter echo

### PR DESCRIPTION
**Pull request by BriggsIDP**
## About The Pull Request

A small makeover of echo for the winter season, adds some snow, ice, charismas cheer, and a bit of décor.
Should be TMed, then removed after winter 🙏 

## Why It's Good For The Game

just a bit of temporary fun

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
tweak: [echo] makes echo winter!
/:cl:

### CODE REVIEW

**Review by EvilDragonfiend — DISMISSED** [review]
Do not change the map directly. Make a new map, and a new json.
This is not identical to echo at all.

**Comment by PowerfulBacon** [comment]
I requested that this remain as changes to Echostation and be either testmerged or just merged for the month. If the changes never get reverted, then it won't really be bad.

**Comment by EvilDragonfiend** [comment]
alright then. we will see how we will manage this.

**Comment by BriggsIDP** [comment]
Commits are out of order, checks pass below

**Review by PowerfulBacon — APPROVED** [review]

**Comment by EvilDragonfiend** [comment]
ranndom fail. redoing.

**Comment by EvilDragonfiend** [comment]
hmm weird queue..

**Pull request closed without merging**
