### PR TITLE
Adds Shower to boxstation

### PR DESCRIPTION
**Pull request by LastCrusader105**
## About The Pull Request
Adds Showers to Boxstation

## Why It's Good For The Game
keeps people clean, and helps with rads and slimes etc etc

## Changelog
:cl:
add: Showers to Boxstation
/:cl:

### CODE REVIEW

**Comment by LastCrusader105** [comment]
16 changes?

@qwertyquerty mad? seething?

**Comment by ghost** [comment]
Based, perhaps even soulpilled.

**Comment by ghost** [comment]
The myth, The Man, The Legend, he finally figured it out.

**Comment by qwertyquerty** [comment]
Mad, definitely mad

**Review by qwertyquerty — APPROVED** [review]

**Comment by Crossedfall** [comment]
Shower heads between blast doors? 🤮

**Comment by LastCrusader105** [comment]
No? It’s between the 2 main doors like on meta

But thank you all for the advice, special thanks goes to open source ss13 for the handy guide

**Comment by Crossedfall** [comment]
> 
> 
> No? It’s between the 2 main doors like on meta
> 
> But thank you all for the advice, special thanks goes to open source ss13 for the handy guide

f

**Comment by LastCrusader105** [comment]
Oof I will re arrange it then
Prehaps where the plants are between the 2 fire locks?

**Comment by LastCrusader105** [comment]
@Crossedfall I will redo it after work 9h ish Maybe move the lockers, or put in lobby I will look
While we are on subject Of maps any reason why Ai in meta isn’t connected to station mains? Blue wire by the transit?
I will solve that too

**Pull request merged**
