### PR TITLE
100% free lag

### PR DESCRIPTION
**Pull request by ike709**
Ports https://github.com/yogstation13/Yogstation/pull/6685

## Changelog
:cl:
fix: We did it boys. Lag is no more.
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
I'm having stuttering issues and issues with chat not working, but I've already been having these problems with BYOND so I can't blame it on this PR.

Also, not comfortable merging this until yogs merges their PR, but I'd like to see it testmerged for a round or two.

**Comment by qwertyquerty** [comment]
Aw sick

**Comment by qwertyquerty** [comment]
I'll do a testmerge as soon as I can

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
you can remove dmdis.dll, it's not used. You'll probably want to wrap it in a define that will disable it if it's being compiled on Travis, since it won't be able to load the dll.

**Comment by qwertyquerty** [comment]
Why did travis never complain about the duplicate define before

**Comment by ike709** [comment]
Pretty sure travis shouldn't be failing anymore. But it still is...

**Comment by ike709** [comment]
Yeah travis failing is somehow qwerty's fault.

**Comment by qwertyquerty** [comment]
You merged the wrong master

**Comment by ike709** [comment]
Indeed I did.

**Comment by ike709** [comment]
Dreamchecker is turning this PR into a real mess.

**Comment by qwertyquerty** [comment]
I like how my commit appeared before all of yours because you have messed up times

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
what the fuck is going on here

**Comment by ike709** [comment]
Don't question it.

**Comment by ike709** [comment]
This is testmerged now though.

**Comment by ike709** [comment]
Or rather the testmerge will be applied next round.

**Comment by ike709** [comment]
This doesn't work very well @1fbff5f83b23d39d38b1dfcb4cac8d9b 

Everything runs slower *and* there's still lagspikes.

**Comment by actioninja** [comment]
If you genuinely think that there should be zero lagspikes or noticable lag ever running this you fundamentally do not understand what this does or what would still cause them.

**Comment by ike709** [comment]
@actioninja Title and PR desc are a joke reference to the time TG "fixed all lag forever".

This PR was closed because it was slowing the subsystems down to the point where SStimer committed seppuku and all of the players were stuck laying down perpetually.

There's definitely tweaks and improvements that could be made (such as capping the tick reservation, reducing the headroom, etc) that could potentially make this feasible, but bee's players don't appreciate a PR's _potential_, they just get really mad when something doesn't work. The additional testmerges to tweak this until it's functional aren't worth all of the angry rants.

**Comment by optimumtact** [comment]
you'll want to keep at least 20% of a tick, maybe even 30% for game code, so that SStimer and SSinput will run, otherwise you'll see the things you describe

**Pull request closed without merging**
