### PR TITLE
Makes Thermal Vision (the mutation) no longer obtainable

### PR DESCRIPTION
**Pull request by TeomanTheGreat**
## About The Pull Request
Thermal vision (the mutation) is no longer obtainable 

## Why It's Good For The Game
Gene having the ability to mass produce the ability to see people through walls is kinda cringe. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Not really sure how i would test locking something as a mutation
</details>

## Changelog
:cl: Phil Smith
balance: Thermal vision (the mutation) is no longer obtainable
/:cl:

### CODE REVIEW

**Comment by FortSumter** [comment]
Genetics in general is kind of cringe and fucks with game balance.

**Comment by DerpiestBruh** [comment]
Based???

**Comment by EvilDragonfiend** [comment]
it isn't **thermal** actually... make it actual thermal?

**Comment by Oscari-pog** [comment]
Blessed PR

**Comment by Isy232** [comment]
I'd say make it DNA vault only and rework the DNA vault to be less shit in general but thats a lot of work and this is a fine temporary measure.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
