### PR TITLE
Removes priority_overlays from the code

### PR DESCRIPTION
**Pull request by Penwin0**
## About The Pull Request
Overlays one of the bigger things causing overtime so I went in to look if something could be improved, running into priority_overlays in the process, this really has no reason to exist, you should always go through the MC with these and add a bunch of unecessary checks and variable declarations on procs/macro that get called hundreds or thousands of times per round.

I'm also quite certain priority_overlays could cause some weird issues/lag if you spam a ton of them.

ports a fair bit from: https://github.com/tgstation/tgstation/pull/51018

I have not benchmarked/profiled this yet as Im opening this PR just before closing down the computer for the night, Ill expand on PR body tomorrow.

## Why It's Good For The Game
Less lag is quite good, and better code is good too

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Overlays work fine
Screenshot_1278

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: Penwin, AnturK
code: removes priority_overlays from the code
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
So what does priority_overlay actually do?

**Comment by PowerfulBacon** [comment]
Oh its a way for coders to be lazy and not have the overlay removed with cut_overlay, this will probably cause visual issues with guns

**Comment by PowerfulBacon** [comment]
I don't see how this would improve performance that much tbh

**Comment by Penwin0** [comment]
> Oh its a way for coders to be lazy and not have the overlay removed with cut_overlay, this will probably cause visual issues with guns

I don't think removal of this should cause issues with that at all but I'll check tomorrow.



> I don't see how this would improve performance that much tbh

It removes a bunch of checks that shouldn't be there to begin with from procs that are run thousands of times

**Comment by Penwin0** [comment]
> this will probably cause visual issues with guns

Seems to be working fine
Screenshot_1279

This PR also solves "ghost" fire/acid on clothes that are no longer acided nor burning.

**Comment by PowerfulBacon** [comment]
This 100% feels like anything that uses cut_overlays to remove all overlays but doesn't re-add its priority overlay should break, theres no way this makes sense to be working (Do energy guns cut all overlays or only the charge overlay?).

**Comment by Penwin0** [comment]
> doesn't re-add its priority overlay should break

Going to go through all the removals and make sure they work

**Comment by Archanial** [comment]
oh shit I was just doing that myself

**Comment by ike709** [comment]
Stale, ask for reopen if you're still working on this.

**Comment by Penwin0** [comment]
Ready for review

**Comment by Penwin0** [comment]
Screenshot_1315

Fire being removed from clothes properly, I've also tested eguns, PKA, acid, glass bottles and SM

**Review by itsmeow — APPROVED** [review]
Honestly I do not understand a single bit of this but given the substantial testing evidence and the fact that it improves performance and fixes that stupid fire bug, approved

**Comment by itsmeow** [comment]
yolo

**Pull request merged**
