### PR TITLE
MetaSec brig retiling

### PR DESCRIPTION
**Pull request by Tsar-Salat**
## About The Pull Request

Minor retiling of MetaStation's Brig and departmental stations.

I mostly stuck with the decal theme of MetaSec, I just expanded the design across the entirety of brig. All of my modifications were with the new tiles in mind. 

Themed Tiles used:
- The hallway into security & genpop are standard Grey.
- Brig proper is black.
- Officer Equipment Storage is techmaint
-  Armory is Techgrid
- Penal Shuttle uses smoothed tiles

## Why It's Good For The Game

Meta is starting to show its age and lack of variety. I noticed that theres really not a lot of tile variety on meta, so here is a showcase of applying 'modern' mapping practices on the default map.

This design is based off something I actually did ingame during a round, and I received a lot of positive feedback from both security and other crew visiting. My own displeasure with the current setup and that blueprint led me to this pr.

Hopefully it will inspire others to make similiar interesting design choices.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Screenshot 2024-07-12 200720

Screenshot 2024-07-12 200637

</details>

## Changelog
:cl: rkz, spockye
add: Adds some tile variety to MetaStation Security
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
It sounded neat, but I don't entirely vibe with the large floor squares yet. I kind of like the light theme just because it feels more themeatically accurate compared to a dark theme. Similar to how the dark theme on my CC PR wasn't too well enjoyed.

**Comment by Tsar-Salat** [comment]
> I kind of like the light theme just because it feels more themeatically accurate compared to a dark theme.

I dont like it when the whole station is grey. Its ugly as hell.

**Comment by Rukofamicom** [comment]
image

Please provide the screenshots here instead of a message about how to get them.

**Comment by Tsar-Salat** [comment]
> Please provide the screenshots here instead of a message about how to get them.

Ok. I will save two clicks.

> Please provide the screenshots

OK.

**Comment by MarkusLarsson421** [comment]
I was about to defend the bot, but it seems a bit fucky wucky right now. Normally it would be fine, wouldn't it?

**Comment by Tsar-Salat** [comment]
Drafting because Spockye would like to make a few additions

**Review by PestoVerde322 — APPROVED** [review]

**Pull request merged**
