### PR TITLE
removes all roundstart races except human

### PR DESCRIPTION
**Pull request by CthulhuOnIce**
:fire:

### CODE REVIEW

**Comment by CthulhuOnIce** [comment]
it's merging time

**Comment by Lagomorphica** [comment]
bruh moment
just ban them from command roles lmao headass

**Comment by Oshibkka** [comment]
just ban non humans from command roles. 
who am I going to bully now?

**Comment by KainVirtue** [comment]
Ban Kev

**Comment by mattmatterson111** [comment]
I'm two weeks late to this, but this is a config option :mistake:
https://github.com/BeeStation/BeeStation-Hornet/blob/master/config/example/game_options.txt#L440

**Comment by hackerjsimon** [comment]
Plans to make all other non-human races cost beacons initiate

**Comment by Bestparty** [comment]
Make the poopy races slaves

**Pull request merged**
