### PR TITLE
Lets nukies buy the Chameleon kit

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
See title

## Why It's Good For The Game
War mode isnt the only nukies gameplay, stealthies exist and are fun too

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
tweak: Nukies can buy the Chameleon Kit now
/:cl:

### CODE REVIEW

**Review by EvilDragonfiend — APPROVED** [review]
honestly why not

**Comment by MarkusLarsson421** [comment]
It should be a balance change and not a tweak.

**Comment by Rukofamicom** [comment]
>  stealthies exist and are fun too

I have a favorite lone-op loadout. It's taking CQC, an emag and some C4. 
The first thing I do when I get on station is try to be as sneaky as possible and ditch the red suit for a greytider outfit and stash the bulldog somewhere in maints along with the suit. I then try to be as sneaky as possible to acquire the nuke, bomb the station and crew never has any idea who or what hit them until they only have 90 seconds to react. Sound's like great fun for the crew right? 

It isn't. That's why the last part isn't true - I set the nuke for ten minutes and then go as loud as possible while keeping the disk on myself and throwing an active pinpointer outside the vault. Crew has to chase and fight me to get the disk back and the nuke timer lasts long enough to make it an actually engaging challenge. 
 
I fully understand why nukies intentionally do not have chameleon enabled and it is a bad idea to make this strategy any easier than it currently is - if it isn't coupled with a strong desire to make the game more fun for the crew, it is just unfair and extremely unfun outright.

This is not a good idea. 🔑

**Comment by Rukofamicom** [comment]
I will say that if the minimum nuke timer was increased **significantly** I'd be okay with this.  If crew actually had time to react to and do something about successful stealth ops, I'd be a lot more okay with enabling them. 

This feels like an out of scope request for this PR and something to be discussed separately though (and probably good for the game in general since fully stealthy ops are not really fun regardless of chameleon)

**Comment by Ivniinvi** [comment]
Ruko essay comment received, not gonna even bother reading it

**Pull request closed without merging**
