### PR TITLE
[port] Increases the accuracy of the photocopier

### PR DESCRIPTION
**Pull request by 1393F**
## About The Pull Request
https://github.com/tgstation/tgstation/pull/54336

## Why It's Good For The Game
more variety to photocopying your ass

## Changelog
:cl:actioninja
add: Increases the accuracy of the photocopier
/:cl:

### CODE REVIEW

**Comment by Effemu** [comment]
erp pr

**Comment by super12pl** [comment]
Literally fetish content

speed merge please

**Comment by Sylphily** [comment]
Why is this a thing

**Comment by ghost** [comment]
speedmerge
Bee coders could STILL have fun

**Comment by PowerfulBacon** [comment]
I am not being responsible for merging this.

**Comment by utilbird** [comment]
same

**Comment by PowerfulBacon** [comment]
I dont think this is a good idea

**Comment by DatBoiTim** [comment]
I think it's a little soon for Maggot Incident part 2

**Comment by super12pl** [comment]
> I think it's a little soon for Maggot Incident part 2

I disagree

**Pull request closed without merging**
