### PR TITLE
Saves 1.03s on asteroid plating initialisation

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Removes variants from open turfs and replaces it with an icon state selection implemented manually. This saves around 50 microseconds per asteroid turf initialisation, which is roughly 1 second saved while initialising lavaland.

## Why It's Good For The Game

Our init times are getting a bit too high.

## Testing Photographs and Procedure

image

image

## Changelog
:cl:
tweak: Saves 1.03s on init times by altering asteroid plating initialisation logic.
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
Does no other subtype of /turf/open/floor use the auto_gen_variants system? lol?

**Comment by PowerfulBacon** [comment]
Nope

**Comment by itsmeow** [comment]
And nothing else uses the variants list? You removed the pick logic from the main floor type, so the variants list should be removed? Or no?

**Comment by PowerfulBacon** [comment]
Oh I thought I removed it

**Comment by PowerfulBacon** [comment]
oh yea others do use it, it just wasn't picked up by dreamchecker for some reason

**Comment by PowerfulBacon** [comment]
Even more savings coming right up

**Comment by PowerfulBacon** [comment]
image

Its a bit hard to compare the others since they didn't previously have an initialize proc

**Comment by PowerfulBacon** [comment]
This broke wood

**Review by Rukofamicom — APPROVED** [review]

**Pull request merged**
