### PR TITLE
Disables buying oh hi daniel and the asteriod with engines strapped to it on sage.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Oh hi Daniel and the Asteroid with engines strapped to it can no longer be bought via the comms console.

## Why It's Good For The Game

There's no reason for this to be even a choice, it's against the rules to buy this as non-antag and i have yet to see an antagonist buy this as a shuttle, so in the end everyone wins, admins have less work, players will not get banned for stupid reasons, and the ban page lurkers won't scratch their head about why someone got banned for buying a shuttle.

## Changelog
:cl:
config: [SAGE] You can no longer buy Oh hi Daniel and the Asteroid with engines strapped to it.
/:cl:

### CODE REVIEW

**Review by ike709 — APPROVED** [review]

**Review by Archanial — CHANGES_REQUESTED** [review]
Make someone be able to buy them if he emags the console. Daniel is god tier for hijack.

**Comment by St0rmC4st3r** [comment]
Maybe make it so that you need to find the asteroid first before being able to buy it?

**Comment by PowerfulBacon** [comment]
Oh hi Daniel is used a lot for hijack attempts

**Comment by ghost** [comment]
Closed in favor of #2841

**Pull request closed without merging**
