### PR TITLE
Mac Space Restaurant

### PR DESCRIPTION
**Pull request by Vorak2**
## About The Pull Request

Adds a fast food restaurant space ruin to the game. it includes allot of food and toys but no weapons
https://cdn.discordapp.com/attachments/590714573611597824/646282424753324042/unknown.png

## Why It's Good For The Game

it adds another space ruin to the game witch is good as currently there is not much variety with the space ruins and it would alleviate it somewhat.

## Changelog
:cl:Vorak
add: Adds a Fast Food restaurant in space

/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
This is pretty big for a space ruin, not to mention kind of fancy for a fast food restaurant.

**Comment by Cenrus** [comment]
Make sure you convert it with mapmerger.

**Comment by Vorak2** [comment]
at first I was going to use basic chairs and tables but pepole convinced me to use the fansy things but I have not changed the name or such.
I could remove 6 tiles on the y axis without removing annything but other than that I would say it is quite standard size for the Little bigger ruins (like lissening post and Gondola)

**Review by MarkSuckerberg — CHANGES_REQUESTED** [review]
Make sure you mapmerge. Since it's a new map entirely, you should be able to run /tools/mapmerge2/mapmerge.bat or whatever and make sure you enter the number for your map, it will show up when you run the program.

**Comment by Vorak2** [comment]
I Think I fixed it. thogh would be nice if annyone tested it to se if there are any problems I dont see

**Comment by ike709** [comment]
@MarkSuckerberg Is this good?

**Review by MarkSuckerberg — APPROVED** [review]
Shite, I believed I had approved this already...

**Pull request merged**
