### PR TITLE
Disables all Gateway Maps

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This disables all Gateway maps in the config, not removing the maps from the games files.

## Why It's Good For The Game

Unmaintained content that has been left festering for years and the terrible quality (and very questionable balance of some), of the maps honestly goes to show that, until someone actually wants to update these maps they should be disabled because they will only get worse the longer time goes on.

## Changelog
:cl:
config: All Gateway maps have been disabled.
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
This is better done by disabling away mission loading.

**Comment by ghost** [comment]
> This is better done by disabling away mission loading.

i don't know where.

**Comment by zeskorion** [comment]
did you edit MRP config as well

**Comment by francinum** [comment]
Comment out `ROUNDSTART_AWAY` in game_options of both servers.

**Comment by Effemu** [comment]
uncool man

**Comment by ghost** [comment]
> Comment out `ROUNDSTART_AWAY` in game_options of both servers.

alright im gonna close this PR and do that instead.

**Pull request closed without merging**
