### PR TITLE
Port attempt of /tg/ deadchat control

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports:
- https://github.com/tgstation/tgstation/pull/47110
- https://github.com/tgstation/tgstation/pull/52761 (partial)
- https://github.com/tgstation/tgstation/pull/55314
- https://github.com/tgstation/tgstation/pull/56888
- https://github.com/tgstation/tgstation/pull/57926
- ~https://github.com/tgstation/tgstation/pull/58419~ (someone else is doing it #8080)
- ~https://github.com/tgstation/tgstation/pull/59645~ (maybe one day....)
- https://github.com/tgstation/tgstation/pull/65195
- https://github.com/tgstation/tgstation/pull/66621

## About The Pull Request
This ports the entirety of /tg/'s deadchat_control.dmi functions for beestation! Included are a partial implementation of TG's signal_handling tweak(tgstation#52761), applied only to deadchat_control, which I will remove if it proves problematic.

## Why It's Good For The Game
Frankly this VV feature is rather underdeveloped and underwhelming on our codebase. This PR should give administrative staff more opportunities using deadchat_controls for entertaining dchat and themselves other than the usual CTF and Battle Royale.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: RKz
add: added very basic support for signal callback unblocks in helpers.dm, thus far only applied to deadchat_controls.dm
add: more dchat stuff!
spellcheck: added more specific 
code: complete rewrite of dead_chat control VV
admin: expanded VV deadchat_control options including controlling an immovableRod, birdboat, and whatever the admin chooses
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
god for my next pr I am simplifying <spans> man

**Comment by itsmeow** [comment]
#8080 already addresses the tgalert thing, and in fact supersedes it, so don't worry about that

**Comment by Tsar-Salat** [comment]
yea I saw, I'll take it out of the ports list for now. Thanks

**Comment by Tsar-Salat** [comment]
Alright, I'll just pin future development of this pr under 8080 then

**Comment by itsmeow** [comment]
Confused why you stopped this, you don't need 8080 for this to work.

**Pull request closed without merging**
