### PR TITLE
Disables Lavaland Swarmers

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request

Disables Lavaland Swarmers from the config

## Why It's Good For The Game

Me no like zappy bugs in rock >:(

## Changelog
:cl:
config:Lavaland Swarmer Space Ruin has been removed from the config (still in game files)
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
**About The Pull Request**
Disables megafaunas from the config

**Why It's Good For The Game**
Me no like dying in rock >:(

**Comment by OceanFish1** [comment]
**About The Pull Request**
Disables lava from the config

**Why It's Good For The Game**
Me no like burning in lava >:(

**Comment by r1ks-iwnl** [comment]
I ded pr

**Comment by eeSPee** [comment]
Grudge Code good.

If it hits 10 dislikes, maintainers may speedmerge.

**Comment by RDS88-beeman** [comment]
Lavaland Swarmers: Exist as a broken nothing ruin for... idk years probably
The community: cool okay nice
Lavaland Swarmers: get restored to intended behavior
The community:

**Comment by utilbird** [comment]
I ded

**Pull request closed without merging**
