### PR TITLE
Adds Several New Ruin Modules + Minor Maintenance On Others

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Remakes and curates a handful of new randomroom modules as I hinted I was working on in [#6182](https://github.com/BeeStation/BeeStation-Hornet/pull/6182)
Some are quite involved and different compared to other available modules, others fit right in.

Other (broken) modules have been removed and or remapped.

## Why It's Good For The Game
Static space ruins don't exist ~~(Good)~~, so these are the main source of space content offstation. Thus, they need as much pumped into them as possible, I've not even played explorer and just by ghosting I'm already familiar with the possible modules...
That just won't do.

## Changelog
:cl:
add: 5 new ruin modules are possible for Explorers (Or, quite possibly, their targets) to stumble across.
fix: Updated a bunch of object typepaths in ruin modules. Also got rid of a few occurrences of landmark/start in them.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
This is cool, can you turn the shuttle into an actual shuttle though? (It would require an area that is whitelisted in shuttle_creator item, or be a space area)

**Comment by PowerfulBacon** [comment]
Some of these rooms are sizes that would mess up the generator, it can only handle rooms with 4n+1 sizes. (5, 9, 13, 17, 21 etc.)
The connection points also need to be in specific positions (4n-1 along an axis) otherwise the generator could be weird.
It *shouldn't* be too hard to make the generator work with 1x1 chunks rather than 5x5 chunks, but currently it only supports them sizes due to how it works.

<details>
<summary>
Generator Details
</summary>

Firstly the generator creates a random room and records any created connection points.
image

Next the generator looks at one of the connection points and analyses which rooms would fit in this position.
image

It picks a random room which would be valid for that position.
The rules for validity are as follows:
 - The room must not overlap with any other rooms
 - If the room borders with another room, any existing connection points must link to a connection point in that room.

The second point is the reason why the rooms need to be a specific size, since it is built on the room sizes being 3x3 + borders when it checks the edges, if the room sizes are not to standard then there will be a space gap.
image

If a 4x5 room generates where it should be 5x5 this can happen:

image
The highlighted point needs to connect to something, but since the room is not on the grid, that point isn't actually checked to see if it lines up with what it should, meaning this room would be valid despite an adjacent room having a doorway that leads to nothing.
When the generator gets around to generating a room attached to the unconnected doorway, there will be no rooms that fit in that position (since only 1x5 rooms would fit and there are none) so the generator will fail and a doorway to space will exist.

The doors also need to be in specific positions to line up with the center of the conceptual grid, otherwise rooms can become offset from this creating situations where the generator can't find any rooms that fit in a certain place.

Making the generator work on a 1x1 grid rather than a 5x5 would be possible however it would require mapping every possible connection point with 1x1 rooms so that all possible positions are covered (the same reason there are so many hallways).

</details>

Some rooms fake weird sizes by having noop around the borders (having a 9x5 room but the 2 sides are noop so the room is actually 5x5)

**Comment by unit0016** [comment]
> This is cool, can you turn the shuttle into an actual shuttle though? (It would require an area that is whitelisted in shuttle_creator item, or be a space area)

I've messed with shuttlecode enough on /tg/ to not immediately break my skull trying, I'll do that when I can. As of right now it's a space area.

EDIT:
I'm a doofus, I thought you meant that I should rather than that be a question. Or maybe it is. I dunno. Point is: Yes, you can.

**Comment by unit0016** [comment]
> Some of these rooms are sizes that would mess up the generator, it can only handle rooms with 4n+1 sizes. (5, 9, 13, 17, 21 etc.)
> The connection points also need to be in specific positions (4n-1 along an axis) otherwise the generator could be weird.
> It *shouldn't* be too hard to make the generator work with 1x1 chunks rather than 5x5 chunks, but currently it only supports them sizes due to how it works.
> 
> <details>
> <summary>
> Generator Details
> </summary>
> 
> Firstly the generator creates a random room and records any created connection points.
> image
> 
> Next the generator looks at one of the connection points and analyses which rooms would fit in this position.
> image
> 
> It picks a random room which would be valid for that position.
> The rules for validity are as follows:
>  - The room must not overlap with any other rooms
>  - If the room borders with another room, any existing connection points must link to a connection point in that room.
> 
> The second point is the reason why the rooms need to be a specific size, since it is built on the room sizes being 3x3 + borders when it checks the edges, if the room sizes are not to standard then there will be a space gap.
> image
> 
> If a 4x5 room generates where it should be 5x5 this can happen:
> 
> image
> The highlighted point needs to connect to something, but since the room is not on the grid, that point isn't actually checked to see if it lines up with what it should, meaning this room would be valid despite an adjacent room having a doorway that leads to nothing.
> When the generator gets around to generating a room attached to the unconnected doorway, there will be no rooms that fit in that position (since only 1x5 rooms would fit and there are none) so the generator will fail and a doorway to space will exist.
> 
> The doors also need to be in specific positions to line up with the center of the conceptual grid, otherwise rooms can become offset from this creating situations where the generator can't find any rooms that fit in a certain place.
> 
> Making the generator work on a 1x1 grid rather than a 5x5 would be possible however it would require mapping every possible connection point with 1x1 rooms so that all possible positions are covered (the same reason there are so many hallways).
> 
> </details>
> 
> Some rooms fake weird sizes by having noop around the borders (having a 9x5 room but the 2 sides are noop so the room is actually 5x5)

I'll convert everything to this styling.

**Comment by PowerfulBacon** [comment]
> I'll convert everything to this styling.

One day I should probably make it so rooms can be any size and empty space gets filled with maints.
One day...

**Comment by unit0016** [comment]
> One day I should probably make it so rooms can be any size and empty space gets filled with maints. One day...

Is what it is, I was gonna go in and add in the ability for modules to have preferred connected themes (Department cohesion) to be honest, but I'm saving my attempt at that for another time.

**Comment by unit0016** [comment]
It was jank but it should all be compliantish now.

**Comment by unit0016** [comment]
Might draft this if it isn't merged soon-ish, I feel like going back into the code to see if two other choice ideas I had would be possible.

**Comment by PowerfulBacon** [comment]
Bad door position in this room
image

(Blue marker needs to be moved left by 1)

image

Bad door position here, room markers need to be moved left or right by 2

**Comment by PowerfulBacon** [comment]
I think box tool storage is the wrong size, linters should pick it up. Its a pain I can't give you automatic linter runs until a PR from you gets merged

**Comment by unit0016** [comment]
Aghgh

I'll address those and honestly will probably just delete tool storage, it's the least. Good. Anyways.

**Comment by unit0016** [comment]
Done my fixes and I *have* decided to move to draft. A few of the modules already in the codebase are making me raise my brow a bit, plus I want to see if I can get away with some other shenanigans while I'm in here.

**Comment by unit0016** [comment]
Having trouble reverse engineering the code here to slot in the ideas I had (Preferred 'Departments' to keep similar modules clustered together and 'Themes' so that not every single ruin were generic ruined NT stations.)

So, guess I'll stick to my normal bounds and just map a bunch more.

**Comment by unit0016** [comment]
Aghghgh.
Got runtimes blasting now.

Screw it, I'll return to this some other time, maybe, I dunno. Sorry for the time-waste on this one.

**Pull request closed without merging**
