### PR TITLE
Ports candy cigs from TG STATION

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
Ports candy cigar from tg station (https://github.com/tgstation/tgstation/pull/47143)

## Why It's Good For The Game
mmmm candy cigar

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

sigfix

</details>

## Changelog
:cl:
add: Imports candy cigars from the tg sector
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
Please include testing screenshots

**Comment by etherware-novice** [comment]
@itsmeow ok

**Comment by mcmeiler** [comment]
That testing screenshot shows nothing. Generally, you'll want to showcase the features you're implementing/changing in that section, and showcasing that they work.

**Comment by PowerfulBacon** [comment]
I don't see how this is good for the game

**Comment by etherware-novice** [comment]
makes a new strategy for replenishing hunger

**Comment by ike709** [comment]
🔑 bloat

**Comment by etherware-novice** [comment]
hey!

**Comment by PowerfulBacon** [comment]
I have to agree with Ike, there's nothing explicitly wrong with it, but it serves no greater purpose and introduces no meaningful content to the game which will lead it to likely being a bloat item that won't be used.
All interactions with this item involve getting it from a vending machine and then using it; unlike other food content it doesn't create interactions with the chef as they can't produce this and it doesn't create interactions for the user.

**Comment by PowerfulBacon** [comment]
Discord is always open for discussions about ideas and what would make good content

**Pull request closed without merging**
