### PR TITLE
Removes stun from spraycans 

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
Removes the stun from spraycans, they blur the eyes, flash the color sprayed, and make the person jitter instead.

## Why It's Good For The Game
It's a roundstart item with quirks, it should not be able to stun. 

## Changelog
:cl:
balance: The spraycan no longer stuns.
/:cl:

### CODE REVIEW

**Comment by hackerjsimon** [comment]
No...its a emergency item and can be avoided with legit any form of eye protection

**Comment by CthulhuOnIce** [comment]
Sorry, this is cringe and nerfs a cool feature

**Comment by eLeCtrOssSnake** [comment]
Kring, hell no.

**Comment by eLeCtrOssSnake** [comment]
Who the fuck is gonna be relying on a spray can picking an unrobust quirk.

**Pull request closed without merging**
