### PR TITLE
Fixes Antag Tokens Coins being invisible

### LINKED ISSUE #9998: Antag token from arcade machine invisible?
Issue reported from  Round ID: 46165 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

antag token from arcade machine is invisible for some reason, even when in the player's hand
image

### PR DESCRIPTION
**Pull request by Miliviu**
## About The Pull Request

fixes #9998
I think #9386 broke it, now I fix it!

## Why It's Good For The Game

Invisible stuff is not coolio :)

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/45698448/8f6d40d8-2aa8-40a8-ac0a-730ef756967e

</details>

## Changelog
:cl:
fix: Antag Token coin is now visible
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
nuh uh

**Comment by Miliviu** [comment]
> nuh uh

Find someone to blame

**Review by EvilDragonfiend — DISMISSED** [review]

**Review by EvilDragonfiend — DISMISSED** [review]
image

even tho the testing evidence video shows no different, but I feel uncomfortable from inconsistency lol
but this can be fine, I guess??

**Comment by Tsar-Salat** [comment]
Yea I edited it like that just to mess with you

**Comment by Miliviu** [comment]
> image
> 
> even tho the testing evidence video shows no different, but I feel uncomfortable from inconsistency lol but this can be fine, I guess??

I will change it yeah

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
