### PR TITLE
Stun baton rework

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
First off, stun batons now no longer bypass armor. If you're unarmored it still takes two hits to stamcrit, but if you're wearing an armor vest/helmet then it takes three hits, or if you're wearing the captain's hardsuit then it's four hits.

Next, you can limb target with batons. This allows more tactical play that simply unga dunga with a baton. Limb disabling has also been tweaked so that disabling each limb deals more total stamina damage, so you only have to disable three limbs instead of four to stamcrit. 

Finally it uses apply_damage instead of adjustStaminaLoss. This means that the knockdown may be slightly delayed in some instances (but they won't be able to take any actions except walk during this time) or the knockdown may be shortened, but a final baton hit when they're in either state will make the knockdown instant or lengthen the knockdown.  

## Why It's Good For The Game
Batons now have a counter in the form of good armor. It encourages more tactical play by limb targeting. More counterplay if you're getting batoned. 

## Changelog
:cl:
tweak: Stun batons now do 75 apply_damage instead of 90 adjustStaminaLoss. This means you can do limb targeting, damage is reduced by armor and it may take a moment to knockdown once in stamcrit.
tweak: Limb disabling total damage increased, now only requires disabling three limbs to stamcrit not four. 
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
The delayed knockdown is due to current stamina code

**Comment by mehmetipekpatates** [comment]
this was already closed?? allo???

**Comment by zeskorion** [comment]
> this was already closed?? allo???

The closed one had different numbers and also removed telebaton knockdown

**Comment by enthethan** [comment]
How much  damage does a limb take to get disabled 45?

**Comment by VictorVow** [comment]
50

**Pull request merged**
