### PR TITLE
Removes the Yiff Decal and adds delay to 3 Tile Decals sprays

### LINKED ISSUE #7132: Remove "Yiff In Hell" decal
I got noted for saying "clean the yiff" on common instead of "clean the yiff in hell decal" and I am now annoyed this ever happened and want it removed for "ERP". Funni not allowed.

### PR DESCRIPTION
**Pull request by Miliviu**
## About The Pull Request

closes #7132 
Removes the Yiff in hell Decal and adds a long delay to spraying 3 tiles Decals

## Why It's Good For The Game

The Yiff Decal is LRP as hell and spamming big decals is also annoying

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

The Decal is no longer available for drawing and other Decals from the same DMI are working
image

Spraying small Decals has no delay, large decals do
https://user-images.githubusercontent.com/45698448/175832748-d96b8a1d-5e94-4729-bac0-6a018242e01d.mp4

</details>

## Changelog
:cl:
remove: Yiff in Hell Decal
tweak: spraying big decals has delay
/:cl:

### CODE REVIEW

**Comment by DerpiestBruh** [comment]
how

**Review by itsmeow — APPROVED** [review]

**Comment by evermore9932** [comment]
Guy with the "fursona" pfp on discord removes the "yiff in hell" decal, of course.
Beestation needs this, speedmerge asap!

**Comment by Miliviu** [comment]
> Guy with the "fursona" pfp on discord removes the "yiff in hell" decal, of course. Beestation needs this, speedmerge asap!

Are you talking bout me???
I'm no furry lmao

**Comment by DerpiestBruh** [comment]
He is actually going through the stage of furry denial.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
