### PR TITLE
Kilo Decal Fix

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request

The following rules has been created and followed as closely as possible when decaling Kilo. The names referred to are the path names of the decals, more of the path will be included if there are duplicates.

- Doors or firedoors has closeup decal.
- Plating has no decals on them.
- All doors and firedoors have dark tile.
- Tables and computers has no extra decal.
- Shutters has delivery decal.
- If shutters has no table or window, it also has a closeup decal.
- Trash chutes and bins has bot decal.
- Racks, lockers and other moveable things has bot decal.
- Vendors has delivery decal.
- Ore silo linked machines has stripes/box decal.
- Public hallway holopads has bot decal.
- Public hallway vents and scrubbers has box decal.
- Front desk tables have plating.
- Fridges have plating.
- Delivery / Plastic flaps has dark tile and delivery decal.
- Atmospherics ports use box decal.
- Disposals inlet and outlet has no decal.
- Mass driver has close up parallel with its direction.
- Airlocks into space uses catwalks in between the doors.
- Docking areas may be except from the no decals on plating rule.
- Fire foam dispensers has a box decal.
- Holopads has a bot decal in AI related areas.
- Avoiding decals on wood and carpet.
- SMESs has plating.

The new maintenance room includes a dead Engineer body with insulated gloves, a few variants of decal painters and a free portable flasher. :troll:

## Why It's Good For The Game

Less decals, good? Less spammy decal is good.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

Map

StrongDMM-2024-10-02 15 50 16

Cargo shuttle

image

Ferry shuttle

image

Arrivals shuttle

image

Exploration shuttle

image

Emergency shuttle

image

Mining shuttle

image

Labour shuttle

image

New maintenance room.

image

</details>

## Changelog
:cl:
fix: [Kilo] Removed spare AutoDrobe in Theater backstage, replaced it with an airlock painter instead.
tweak: [Kilo] Tweaked decal placement, patterns and quantity.
del: [Kilo] Removed the sovl.
del: Removed unused maintenance room details.
fix: Fixed maintenance room incorrect path name.
add: Added Kilo themed maintenance room. 
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
Just to clarify, this is a memey CL. Because I know people will complain its soul has been removed. :P

image

**Comment by Rukofamicom** [comment]
You spelled sovl wrong

**Comment by MarkusLarsson421** [comment]
🤓

**Comment by MarkusLarsson421** [comment]
Still need a review...

**Comment by Rukofamicom** [comment]
Now failing checks

**Comment by Rukofamicom** [comment]
With the balance changed removed and this being a purely visual update that nobody has any strong opinions about, I'm gonna merge this so my eyes can stop bleeding on Kilo

**Review by Rukofamicom — APPROVED** [review]

**Pull request merged**
