### PR TITLE
Stool changes and fixes

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request

Makes all stools buckeable. Also fixes the direction and type used on the bars. Since the merging of the new directional types for stools, a lot of them in current maps face the wrong direction. This PR doesn't fix the stools in BoxStation, that will be done in https://github.com/BeeStation/BeeStation-Hornet/pull/11219 since fixing it here would fuck that PR for the third time

<details>
<summary>Examples of errors</summary>

imagen

imagen

imagen

</details>

## Why It's Good For The Game

It's mad annoying when you are sitting on the bar and people move you around, a chair is a chair, makes no sense making this distinction. It also looks so much better because it looks like you are actually sitting when looked from behind

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

imagen

imagen

</details>

## Changelog
:cl: Varo
tweak: You can now buckle to stools
tweak: Fixes the direction and the type of stools in all maps except BoxStation
add: Missing stools in maps
/:cl:

### CODE REVIEW

**Comment by ClownMoff** [comment]
No, you need to unbuckle them

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
Is it too much to ask that it be possible to shove people out of stools since you are not literally buckling yourself to them?

**Comment by ClownMoff** [comment]
I'm adding a 50/50 chance of getting shoved off

**Comment by ClownMoff** [comment]
I screwed up the PR, lovely.

**Pull request closed without merging**
