### PR TITLE
Adds trailing newlines to all DM files and linting for it

### PR DESCRIPTION
**Pull request by Urumasi**
## About The Pull Request

Fixes a lot (221) of DM files not having a newline at the end of the file, as is standard in unix.

To do this in the future you can use this command (requires `pcregrep`):
```
pcregrep -LMr '\n\Z' . 2>/dev/null | grep "\.dm$" | while read file; do echo "" >> $file; done
```

In addition, ports trailing newline linting from tg to a github CI action

After a suggestion I decided to also remove things like double newline at file end in addition to random indentation (VSCode thought it would help a little too with some trailing spaces)

## Changelog
No front-facing changes

### CODE REVIEW

**Comment by Crossedfall** [comment]
If you're doing this, can you also update our check_grep linting test to check for new lines?

For example:
https://github.com/tgstation/tgstation/blob/bfe0fcc60122f9cfea94e01c80304b4b5782b96b/tools/ci/check_grep.sh#L65-L73

**Comment by Urumasi** [comment]
~~I sure hope whatever is using `check_grep.sh` has `jq` installed like on tg~~
Edit: Nevermind, I didn't touch that part

**Review by ike709 — DISMISSED** [review]

**Comment by ike709** [comment]
@Crossedfall

**Review by KubeRoot — APPROVED** [review]

**Review by Archanial — APPROVED** [review]

**Review by Crossedfall — APPROVED** [review]
Perfecto. This is going to cause a bit of chaos, but it's definitely going to be a solid gain ~~also helps with linux shiz~~.

**Comment by Urumasi** [comment]
> This is going to cause a bit of chaos

:trollface:

**Pull request merged**
