### PR TITLE
Exploration Crates and Atmospherical and Electrical systems

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request

All Exploration shuttles now have a standard sets of supply crates of equipment.

image
<details>
<summary>Supplies Details</summary>

**Shuttle Supplies Crate**
`/obj/structure/closet/crate/science/shuttle`
For supplies relating to keeping the shuttle operational.
- Solid Plasma (x10)
- Exploration Radio Headset (x3)
- Multitool
- Mechanical Toolbox
- Exploration Shuttle console

**Mining Supplies Crate**
`/obj/structure/closet/crate/science/mining`
For supplies relating to restoring the plasma supply.
- GPS
- Manual Mining Scanner
- Pickaxe
- Mining Satchel

**Exploration Contraband crate**
`/obj/structure/closet/crate/secure/science/contraband`
For contraband found during missions.
- Syndicate beer (x2)

</details>

All maps and shuttles has been given a working air, waste and electrical connection to the Exploration shuttles and Science shuttle.

All shuttles has been given the same standardized crates with equipment. With extra plasma for larger shuttles.

Minor redesigns has been made on all stations and their related shuttle docks.

A Pipe Dispenser machine has been added to (or nearby) all Exploration preparation departments. No longer will they steal the Toxins RPD!

Examples of one on Fland.
image 

A decent amount of changes has been made to the shuttles, either to accommodate the mentioned changes or because of personal design preferences.

All magical tiny fans on Exploration and Science shuttles are gone.

## Why It's Good For The Game

Gives the Explorers consistent crates no matter what shuttle they are on.

Allows a shuttle to not be permanently depressurized if you were to leave your door open for 0.5 seconds and encouraging you to return to the station in between missions with your shuttle.

The Contraband crate can be opened by BOTH Security Officers and Explorers alike. It is meant to encourage Exploration to safely deliver any contraband they stumble upon during their missions (like donuts and Stechkin pistols).

No more magical tiny fans. You now need to use the airlock system, forcefully break it or give in and request a Holofan from Atmospherics.

## Testing Photographs and Procedure
<details>
<summary>Docks and Shuttles</summary>

Meta Station
image 
image 

Box Station
image 
image 

Rad Station
Don't mind the blood and such.
image 
image 
image 

Kilo Station
image 
image 
image 

Delta Station
image 
image 
image 

Fland Station
image 
image 
image 

Corg Station
image 
image 
image 

Science Shuttle & Lavaland
image 
image 

</details>

## Changelog
:cl:
add: Added an Exploration Contraband, Shuttle and Mining crate preset.
add: Pipe Dispenser to all Exploration preparation rooms.
balance: Deleted all tiny fans on Exploration shuttles and Science shuttle.
tweak: Redesigned all Exploration shuttles in minor and major ways.
fix: Atmospherics and electrical systems on all shuttles to connect to their dedicated port.
add: Firelock system on all Exploration shuttles.
fix: Cursed lightning on Fland Exploration shuttle.
balance: Exploration shuttle now has common comms.
balance: Exploration has been given on some maps various additional equipment like a jetpack.
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
Frozen by genpop

**Comment by PestoVerde322** [comment]
Needs TM due to how the shuttles are hooked to the station to avoid potential Atmos/Runtime issues.

**Comment by Penwin0** [comment]
> Needs TM due to how the shuttles are hooked to the station to avoid potential Atmos/Runtime issues.

No issues popped up in TM, feel free to merge imo

**Comment by MarkusLarsson421** [comment]
I was told the Exploration shuttle comms was messed up, I will investigate this.

**Comment by EvilDragonfiend** [comment]
Airlocks between the storage part and the cockpit in the science shuttle should have a button to boltdown for a safety measure.

**Comment by MarkusLarsson421** [comment]
> Airlocks between the storage part and the cockpit in the science shuttle should have a button to boltdown for a safety measure.

Feels a bit outta no where, but it seems appropriate. I'll add it.

Fixed the issue with the default Exploration shuttle having a Mining relay instead of the Exploration one.

Fixed the disposals issue on Corg, and swapped the disposals dispenser with an intended pipe dispenser.

Unless more errors pop up, this is ready to be merged.

**Review by PestoVerde322 — APPROVED** [review]

**Review by PestoVerde322 — APPROVED** [review]

**Review by spockye — APPROVED** [review]

**Comment by PestoVerde322** [comment]
Currently frozen due to the non-station mapfreeze, will merge ASAP.

**Comment by MarkusLarsson421** [comment]
Map merger moment. 
image

**Comment by MarkusLarsson421** [comment]
The day this PR is merged, humanity will achieve immortality.

**Pull request closed without merging**
