### PR TITLE
Adds traitorous cloner

### PR DESCRIPTION
**Pull request by eLeCtrOssSnake**
This is not going to be a bounty claim anymore, because I am tired of shit spitting. This PR is not affiliated with #795 in any way.

WIP!

To be made:
Custom antag datum for a defective clone, because @PowerfulBacon asked for it because of some admin menu fuckery.

Feedback is pretty much needed, but excluding @zeskorion because of the word of democracy.

## Changelog
:cl:
add: Added traitorous cloner that is 4 TC for Geneticist/CMO only that allows you to manipulate clones.
/:cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
You can't pick and choose which maintainer you listen to. Not that you were really listening to anyone to begin with. Your PR was closed by Zesk because the quality didn't match up to our standards and you were refusing to adjust based on feedback provided; trying to claim that you knew better. Zesk didn't close it just to spite you or to block someone from adding this kind of change.

Even in this attempted new PR, you **STILL** have code that you haven't fixed. Most notably,

```dm
if(defect_chance < 100)
	defect_chance = defect_chance + 10
```

Which shows that you still aren't listening to people. I am closing this PR as a duplicate of #2193 and because it's obvious that you still aren't interested in listening. Do not open another duplicate of that PR. You are welcome to try and fix everything there. Then _maybe_, you can try to have it re-opened after you've applied all of the feedback you've been given and after you convince one of the other maintainers to give you another crack at it.

**Comment by eLeCtrOssSnake** [comment]
Ahahahahahahaha, WIP pr closed

**Comment by eLeCtrOssSnake** [comment]
@Crossedfall The admins' drama, the kevster drama, I had enough of shittery in here, in the end, everything that maintainers and other high-ranked people do is just shit occasionally making everything worse, and when somebody proposes something better, the whole army of chief boys come and shit everything not to make anything but they want. Overall, If I were maintaining the server, I wouldn't even think about treating people like that. To me, I will probably never understand what's on your mind. And because of the influence of big boys now we have a dude who's been kicked for sending a minecraft pig picture, absolutely zero respect in player's side, perma ban increasage, shit admins and previous staff leaving because of this. And to me this is once again, as I said in my pre-NY ban "It's very sad and I like beestation a lot" but in the end if I am getting shat on, why would I support or like something like this. I lost any hope and this will probably one of my last occurancies in beestation, because I am done.

**Comment by WhyIsCaeciliusTaken** [comment]
Local man gets butthurt he doesn't know how to code properly and has a tantrum when maintainers won't merge his code for being bad.

**Comment by eLeCtrOssSnake** [comment]
> Local man gets butthurt he doesn't know how to code properly and has a tantrum when maintainers won't merge his code for being bad.

Think of it whatever you want, if you don't understand what I am really talking about, go on, it wasn't written for braindead.

**Pull request closed without merging**
