### PR TITLE
Species that aren't able to heal cellular damage in any way are now immune to cellular damage.

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Zombies, androids and skeletons are now immune to cloneloss/cellular damage.

PORTS : https://github.com/tgstation/tgstation/pull/47976

## Why It's Good For The Game

Non organic beings/beings unable to heal cellular damage taking cellular damage is not nice. 

It's also in Ike's port list, I would assume it being on the list is permission to change it even if it's tehnically species code.

## Changelog
:cl:
tweak: Skeletons, androids and zombies are now immune to cellular damage
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
when #4336 is merged add it to the synth parent too

**Comment by yorii** [comment]
Should probably add it to IPCs as well?

**Comment by Kapu1178** [comment]
> Should probably add it to IPCs as well?

actually, cant check, but, MOB_ROBOTIC might be immune anyway

**Comment by ivanmixo** [comment]
Yes, IPCs are immune already.

**Comment by zeskorion** [comment]
> ## About The Pull Request
> Zombies, androids and skeletons are now immune to cloneloss/cellular damage.
> 
> PORTS : [tgstation/tgstation#47976](https://github.com/tgstation/tgstation/pull/47976)
> 
> ## Why It's Good For The Game
> Non organic beings/beings unable to heal cellular damage taking cellular damage is not nice.
> 
> It's also in Ike's port list, I would assume it being on the list is permission to change it even if it's tehnically species code.
> 
> ## Changelog
> 🆑
> tweak: Skeletons, androids and zombies are now immune to cellular damage
> /🆑

Our zombies and skeletons can process reagents.

**Review by utilbird — APPROVED** [review]

**Pull request merged**
