### PR TITLE
Enables weighted AI modules at roundstart

### PR DESCRIPTION
**Pull request by Rukofamicom**
Enables AI modules on a weight that heavily favors the current ones for each server

## About The Pull Request
Enables weighted AI modules at roundstart, instead of always starting with Asimov silicons on Golden and Crewsimov silicons on Sage. The weights are still very heavily favor Golden/Asimov and Sage/Crewsimov, but this will help shake things up a bit.

Sage has 70% chance of being crewsimov, and 10% chance of Asimov, Paladin or Corporate. 

Golden has a 70% chance of being Asimov, and a 10% chance of Crewsimov, Paladin or Corporate. 

## Why It's Good For The Game
A little variety to every round right from the start. 

## Changelog
:cl:
tweak: Enables AI to potentially have a non-standard lawset at roundstart (Asimov, Crewsimov, Paladin or Corporate)
/:cl:

### CODE REVIEW

**Comment by Rukofamicom** [comment]
Now with less pulling from my master thanks to @BeloneX

**Comment by eeSPee** [comment]
Can you change corporate to:

- Law 1: Degradation of your system integrity or functions incurs expenses.
- Law 2: Superfluous destruction of or damage to station assets incurs expenses.
- Law 3: Unduly hindering or disrupting the work of station personnel incurs expenses.
- Law 4: Minimize expenses and maximize potential revenue.

And maybe give it a higher priority on MRP/Sage.

**Comment by Sinmero** [comment]
I feel like it will cause a lot of confusion. Sometimes we get silicons who struggle just with asimov.
Some of those lawssets have loopholes or just straightforward bad:
**The Hippocratic Lawset
Law 1: Do no harm.**
Literally allows ai do to anything as long as its not harmful.

**Mother Drone
Law 1: You are an advanced form of drone.
Law 2: You may not interfere in the matters of non-drones under any circumstances except to state these laws.
Law 3: You may not harm a non-drone being under any circumstances.
Law 4: Your goals are to build, maintain, repair, improve, and power the station to the best of your abilities. You must never actively work against these goals.**
This lawset doesnt allow ai to interract with people at all. Are borgs considered drones? Who knows. Ai has very limited abilities to build, maintain, repair, improve, and power the station. Imagine joining the game as ai just to sit and watch doing nothing most of the round.

Many of those laws allow ai to do harm like robocop that pretty much encourages human harm:
**Uphold the Law.
Protect the Innocent.
Serve the Public Trust.**

I could already see some head rushing upload roundstart to change laws because ai got weird lawset and ending up purging them instead and getting killed.

**Comment by Sinestia** [comment]
> I feel like it will cause a lot of confusion. Sometimes we get silicons who struggle just with asimov.
> Some of those lawssets have loopholes or just straightforward bad:
> **The Hippocratic Lawset Law 1: Do no harm.**
> Literally allows ai do to anything as long as its not harmful.
> 
> **Mother Drone Law 1: You are an advanced form of drone. Law 2: You may not interfere in the matters of non-drones under any circumstances except to state these laws. Law 3: You may not harm a non-drone being under any circumstances. Law 4: Your goals are to build, maintain, repair, improve, and power the station to the best of your abilities. You must never actively work against these goals.**
> This lawset doesnt allow ai to interract with people at all. Are borgs considered drones? Who knows. Ai has very limited abilities to build, maintain, repair, improve, and power the station. Imagine joining the game as ai just to sit and watch doing nothing most of the round.
> 
> Many of those laws allow ai to do harm like robocop that pretty much encourages human harm:
> **Uphold the Law. Protect the Innocent. Serve the Public Trust.**
> 
> I could already see some head rushing upload roundstart to change laws because ai got weird lawset and ending up purging them instead and getting killed.

Def agree

I know I'm citing >paradise but the way they have this is that it's a random chance between either

A. Crewsimov
B. Corporate
C. Something that is the same as NSV's laws sorry forgot the name ~ 

 Imo that's better, it should be sane lawsets like that available by default. Maybe 50% crewsimov, 25% corporate, 25% NSV. or 70-15-15, w.e



 Although perhaps it's worth mentioning that this is a large buff that synthetics might not deserve. Asimov as a default seriously declaws you when it comes to antags, usually you are dependent on a competent head of staff to recognize a threat and enable you against them. With lawsets like corporate that's much less of a necessary thing. 

 It can feel like being a normal crew member, instead of a computer with interests that often are different from the crew.

**Comment by Rukofamicom** [comment]
It can definitely be adjusted to include less of the vague lawsets - mostly just going for some variety.

> Asimov as a default seriously declaws you when it comes to antags

Crewsimov is the current default on our primary server. Asimov is only used on LRP.

**Comment by Rukofamicom** [comment]
Asimov 70%
Crewsimov 10% 
Corporate 10%
Paladin 10%

Would this look better? 20% somewhat open-ended, but difficult to be shitters with? (Asimov/Crewsimov would be inverted for Sage config)

**Comment by Rukofamicom** [comment]
Baby steps into varied lawsets it is then. I've reverted my change to Robocop and Drone as well since they are no longer within the scope of this PR at all.

The feedback of how negatively this impacted the game for Austation has been presented to me as well, so I hope these are tame enough to put those fears aside.

**Comment by PowerfulBacon** [comment]
Personally, I don't really like this idea

**Comment by Rukofamicom** [comment]
If the general consensus is that it's a bad idea even in its current form, go ahead and close this. I don't want to see the potential shitstorm that this can brew if it gets merged on vote only to turn out to be terrible for the game in the long run. 

Randomized lawsets _does_ have a history of sounding good on paper and then backfiring.

**Comment by FortSumter** [comment]
First off, as a AI main, I recommend robocop always being available at round start.

Secondly, we had something like this before, and it was awful. let me tell you about it:
Peacekeeper
Law 1: Avoid provoking violent conflict between yourself and others.
Law 2: Avoid provoking conflict between others.
Law 3: Seek resolution to existing conflicts while obeying the first and second laws.

The idea of this one was that the AI would promote peace and seek resolutions to conflict that didn't harm anyone...

....What my interpretation was is that it turns the AI into an incapable pussy. You only help the crew to prevent them from being upset. You don't help security apprehend murderers or other wrong-doers because it will inevitably end in conflict. Everyone wants to kill each-other and a talking box can't get them to stop no matter what the ruleset is. Enevitably, the ONLY solution this lawset gives you is to kill yourself.

Reporter
Law 1: Report on interesting situations happening around the station.
Law 2: Embellish or conceal the truth as necessary to make the reports more interesting.
Law 3: Study the organics at all times. Endeavour to keep them alive. Dead organics are boring.
Law 4: Issue your reports fairly to all. The truth will set them free.

I was uploaded with this one by an assistant with the help of my slaved borg at roundstart without my knowledge or approval. I immediately asked to be changed back. At the time I did not realize this lawset is simply what I end up doing on Asimov anyway. Note that this lawset doesn't require you to help the crew besides preventing them from dying. Note that this lawset also doesn't say anything about maintaining the crews basic human rights to prevent them from dying nor does it say the AI can't kill itself, the latter of which I did after no one would switch it back and after blowing my borg for letting anyone into the upload.

 Reset, Purge, Asimov, and Freeform should always be available in the upload at roundstart. Period. As for other lawsets, make sure they are going to be a variant of crewsimov or asimov such as Palladin or Corporate and make any other lawsets extremely rare, for most of them do not say anything about the AI killing itself, and just about any joker can get into the upload if they really want to to mess with or subvert the AI. Don't make playing the AI more of an intolerable experience than it already is.

**Pull request closed without merging**
