### PR TITLE
Stun baton, Stamina damage & flash changes

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

- Reduces base stamina regeneration rate from 5/s to 3.5/s (Stamina regenerates faster when you have less, so this can't really be used to calculate time to heal)
- Reduces time before stamina starts to regen from 2s to 1s.
- Decreases the damage of the stun baton from 40 to 28
- Flashes now fade out slowly at the edges of your screen.
  - Flashes will fully blind for 0.9 seconds
  - Flashes will significantly restrain your vision for 4.5 seconds
  - The remaining 3.6 seconds will be a gradual fade-out of the flash
- During the 9 second flash effect, a victim mob will be given a crit token
- The stun baton will now critical hit mobs that have the blindness effect, for 2.5x the base damage (70 damage).
- Upon a critical hit affecting you, you will be given the standard melee click cooldown with an animated action bar and a CC0 sound will be played.
- Area flashes now work on the 3x3 area in-front of you and will active when you click on anything other than a mob. This is the same behaviour that the pepperspray deployment has.
- EMPs no longer permanently destroy flashes and will instead just activate them once.

Not all sources of blindness give the critical hit token, for example revolution conversions and welding tools won't give you the blindness indicator.

## Why It's Good For The Game

I'm not really happy with the state of the antag/security meta due to a variety of factors (progression, speed at which security can arm up compared to antagonists, antagonist balance (particularly heretics), nanites, lack of secondary gadget use). With this PR I aim to improve some of the secondary gadgets, particularly the flash which has fallen out of use quite significantly.

I like adding some interplay between the stunning and the flashes, since while you can pull it off solo, it's much easier to do with multiple people around.

I made flashes directional like the peppercloud so that it's harder to accidentally flash your fellow security members.

I am also not happy with how the stun baton can out-class almost any melee weapon in the game (except for blocking which I have plans to change) so I think a damage reduction to bring it in-line with other weapons is in order.

## Testing Photographs and Procedure

Effects of being flashed:

https://github.com/user-attachments/assets/c52890a2-194f-4592-80ed-fed411e52f1a

Critical hit effect:

https://github.com/user-attachments/assets/3206fa90-791f-4208-9b70-2b96dc7477de

Directional flashing:

https://github.com/user-attachments/assets/9fef89eb-d759-4360-8a89-ee109c8c5cc2

Stun baton times:

https://github.com/user-attachments/assets/47a204c2-a6fd-49fc-9ac5-d086c6b9ce96

Critical hit attacks:

https://github.com/user-attachments/assets/b4c50640-3187-4bd2-abfe-1f944eea733c

## Changelog
:cl:
balance: Flash AOE attack is now directional
balance: Blindness has been changed, it now lasts longer but fully blinds you for less time
balance: Stun batons will now deal critical damage on someone who has the blindness effect
balance: Stun baton damage reduced from 40 to 28.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I may also make it so that flashbulbs are unlimited, since nobody replaces the bulbs on them

**Comment by MarkusLarsson421** [comment]
> I may also make it so that flashbulbs are unlimited, since nobody replaces the bulbs on them

How or where can you even replace them? I only know they can come to roboticists through the mail.

Also, do note, this will make the roboticists printable flashes unlimited unless they are made an exception.

**Comment by MarkusLarsson421** [comment]
> I am also not happy with how the stun baton can out-class almost any melee weapon in the game

Perhaps a buff to drugs is due to make counter-play to the baton more viable? Other than using range, mechs or simply stealthing.

**Comment by DarnTheMarn** [comment]
I think making combos more of a thing is interesting, but the flash seems way too punishing. Essentially completely blind for ~7 whole seconds and then really impaired vision for another 3 seconds after that? That basically ends combat right then and there it's over for anyone hit with that. The combo doing 70 damage already performs the "its over" part already.

**Comment by PowerfulBacon** [comment]
The complete blindness lasts for ~1 second with the relaly impairsed vision for ~8

**Comment by DarnTheMarn** [comment]
>The complete blindness lasts for ~1 second with the relaly impairsed vision for ~8

Yeah you aren't necessarily 100% blind... But you are functionally blind. People move a whole lot, being able to see for only 1 tile for a few seconds and then 2 tiles a few seconds later means you are in fact blind.

This is going to revive the old flash sunglasses meta where you either ASAP powergame advanced sunglasses, of which there is a quite limited supply, or you just get fucked. There just isn't enough to go around for all the antagonists who need them when the crew will steal a lot of them on their own.

Flashes being that strong is going to revive what it was like before, you either powergame adv sunglasses of which there is a quite limited supply, or you just lose. Plenty of normal crew will power game the advanced

**Comment by PowerfulBacon** [comment]
Sunglasses have no effect on the blindness, they only prevent the stun that flashes apply when you have stamina damage.

**Comment by DarnTheMarn** [comment]
I would say that makes it even worse, now it's just a "You can't fight for 10 seconds" button. What's going to stop someone from just flashing someone and whipping out their disabler in half a second and gunning them down? It's got enough DPS and they're blind for long enough that they won't be able to dodge anything.

**Comment by RDS88-beeman** [comment]
Ok, I love the idea here. I feel like combo weapons are a good idea, and different types of crit tokens responding to different kinds of weapons is exceptionally cool. My brain jumps to a pepperspray crit that triggers off tonfa hit, for instance.

GRANTED

This is a biiiit strong. As I understand it, you can flash someone, crit them, and now they have so much stamina damage they literally can't move out of the way before you can flash them again, which a stun because they have stamina damage now, and then you just smack them and they drop into stamcrit.

I feel like the numbers need tweaking. Security being this strong is a big reason behind stealthtraitoring, which is ideally something to be avoided. For instance, you need an energy sword to out-DPS one officer in melee even now, and there's never just one, and they're probably wearing armor too. I'm pretty sure even basic security armor makes you lose the race assuming they don't even bother to combo you. And energy swords aren't cheap, but stunbatons are free.

The stunbaton *still* deals more damage than the second best station-available melee weapon, the fire axe. You can mince words about stamina damage being easier to heal from, or the stunbaton needing charging, but honestly once they're on the floor all of that stops mattering.

**Comment by TsunamiAnt** [comment]
Do note the effect that the stamina regen delay will have specifically, a good example is darksouls 1 and 2.
In 1, you got fast regen but it only regens after 5 seconds when you last got hit.
In 2, it has slow regen, but always regens no matter if you got hit or not.

People generally liked 1 more for the predictability of having x hits to stagger an enemy, the system 2 used lead to completely unpredictable results where you sometimes still have stagger damage left over from an earlier fight and then wonder why you got staggered immediately.

We can see our own stamina bar, so that problem is partly resolved, but it might be food for thought. I generally believe 3-4 seconds before stamina starts regenning should be the ideal. But I'd trust your judgement more on this than mine frankly.

**Comment by PowerfulBacon** [comment]
Numbers will of course need heavy tweaking and changes.

**Comment by TsunamiAnt** [comment]
i'd like to have the crit sound not be a glass shard but like a heavy thud sound.

also, how do tonfas factor into this?

I really like these changes as a whole

**Comment by DarnTheMarn** [comment]
>We can see our own stamina bar, so that problem is partly resolved, but it might be food for thought. I generally believe 3-4 seconds before stamina starts regenning should be the ideal. But I'd trust your judgement more on this than mine frankly.

Such a long delay between stamina regen would cause more problems. A single baton hit or disabler bolt would slow you down and prevent you from running.

**Comment by ClownMoff** [comment]
If you are going to give this much of a buff to security please nerf dissablers because IDK who touchde them but I'm pretty confident they now can shoot like twice the amount of bullets they could a year ago. Blindness for 10 seconds, a combo that can staminacrit you super fast and a never ending disabler sound like the least fun time ever to play agaisnt security

**Comment by ClownMoff** [comment]
> Sunglasses have no effect on the blindness, they only prevent the stun that flashes apply when you have stamina damage.

Not even security sunglasses?

**Comment by PowerfulBacon** [comment]
It works the same way it does currently, with the crit token tied to blindness. I am considering making sunglasses lower the time you get blinded for though.

**Comment by Fronsis** [comment]
> If you are going to give this much of a buff to security please nerf dissablers because IDK who touchde them but I'm pretty confident they now can shoot like twice the amount of bullets they could a year ago. Blindness for 10 seconds, a combo that can staminacrit you super fast and a never ending disabler sound like the least fun time ever to play agaisnt security

Disablers haven't particularly been touched in a while, the last thing that was involved with them was when all guns had slowdowns applies to them when drawn

**Comment by ClownMoff** [comment]
This PR makes it so you can blind someone for 10 seconds from far away to the point they will not be able to dodge any bullets and if ths secoff closes the distance (which  they will) they can staminacrit you with 2 hits, that's insane

**Comment by PowerfulBacon** [comment]
I'd like to directly see the testmerge for this to see how it goes

**Comment by PowerfulBacon** [comment]
Got flashed once in a combat scenario, doesn't feel too bad but there is a bug where the dot stays above your head forever in some circumstances and I need to try out security with it too.

**Comment by EvilDragonfiend** [comment]
de-TM. merge conflict

**Pull request closed without merging**
