### PR TITLE
Ash Walker Tools

### PR DESCRIPTION
**Pull request by Cenrus**
## About The Pull Request

Adds a rake (reskinned cultivator) and a wooden hatchet to the ashwalker base. Replaces their bucket with a wooden bucket. Replaces the water tank with a puddle.

Added crafting recipes for the rake and wooden bucket.
## Why It's Good For The Game

It looks more flavourful (inb4 where did they get the wood from) and adds a bit of functionality to unused content (i.e. ashwalker farming).
## Changelog

Mirrored from PRs:

https://github.com/tgstation/tgstation/pull/44388
https://github.com/tgstation/tgstation/pull/44359

:cl:
add: Added wooden farming implements to the ashwalker base.
add: Makes rakes and wooden buckets craftable.
/:cl:

### CODE REVIEW

**Comment by Toxici11i** [comment]
ashwalker farming was 100% possible with current content, bloat PR that adds useless items that not even botany (nor ashwalkers) would use.

also farming is dependent on  how fast you become an ashwalker, due to automatically degrading soil quality

**Comment by MarkSuckerberg** [comment]
I mean, the novelty is cool and all, but I kinda agree with toxic on this one. There isn't really a need for improvised botanical equipment as (if I remember correctly) you can print more on any autolathe. But, if it gets merged, that would also be fine with me, as it isn't really removing or changing anything.

**Comment by qwertyquerty** [comment]
Conflicting DMIs

**Comment by ike709** [comment]
Stale. Fix the DMI conflicts.

**Pull request closed without merging**
