### PR TITLE
Asteroids Spawn Like Random Rooms

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Added a new spawner for random rooms outside the stations. These asteroids generally contain materials for the station to harvest.

Added 5 spawners for each map.

## Why It's Good For The Game

Makes the station no longer 100% reliant on mining/lavaland for resources. 

## Changelog
:cl:
add: Added randomly generating asteroids outside the station
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Asteroid spawns are 12x12 from the bottom left so the ones on the right wall are too far across.
Also the asteroids should be at least 5 units away from the edge in all directions because changing z-levels only works on space turfs.
Also this is mainly for what extended space is for with the asteroids spawning in space outside the station (Albeit a low chance)

**Comment by eeSPee** [comment]
> Asteroid spawns are 12x12 from the bottom left so the ones on the right wall are too far across.
> Also the asteroids should be at least 5 units away from the edge in all directions because changing z-levels only works on space turfs.
> Also this is mainly for what extended space is for with the asteroids spawning in space outside the station (Albeit a low chance)

IIRC space asteroids were removed due to memory limitation?

Is there a chance or any way we can bring those back? IE reducing the number of zlevels?

EDIT also shouldn't 'centered' spawn them from the center?

**Comment by PowerfulBacon** [comment]
space ruin budget was decreased for performance especially with the old atmos. Was never increased with new atmos.

**Comment by eeSPee** [comment]
> space ruin budget was decreased for performance especially with the old atmos. Was never increased with new atmos.

Should we give it a try and try to increase back to what it used to be?

**Comment by ivanmixo** [comment]
Using StrongDMM?

**Comment by heepox** [comment]
no longer will i have to build space hideouts from absolutely nothing. now i can just mine them out.

**Pull request closed without merging**
