### PR TITLE
pulse rifle flavor text

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

pulse rifle flavor text

## Why It's Good For The Game

pulse rifle flavor text

https://github.com/tgstation/TerraGov-Marine-Corps/pull/3124/files

## Changelog
:cl: XSlayer300
add: pulse rifle flavor text
/:cl:

### CODE REVIEW

**Review by Archanial — APPROVED** [review]

**Comment by francinum** [comment]
??

**Comment by ghost** [comment]
> ??

It's pretty self explanatory, no?

**Comment by ghost** [comment]
An actual PR made by belone that ISNT a nerf? this is revolutionary!

**Comment by PowerfulBacon** [comment]
??

**Comment by francinum** [comment]
It really isn't. Where did this come from for instance.

**Comment by ghost** [comment]
> It really isn't. Where did this come from for instance.

TGMC.

**Comment by Archanial** [comment]
If you are porting this credit original author

**Comment by PowerfulBacon** [comment]
DNM: Fails to credit original authors.

**Comment by ghost** [comment]
> DNM: Fails to credit original authors.

Credits added.

**Comment by Archanial** [comment]
> 
> 
> > DNM: Fails to credit original authors.
> 
> Credits added.

Add link to PR you are porting too.

**Comment by WhyIsCaeciliusTaken** [comment]
Not changing the description to "Point away from face" smh.

**Comment by PowerfulBacon** [comment]
The gun names look out of place.
Energy Gun, disabler, beam marksman rifle, Laser gun, Laser scatter shotgun, M19C Pulse Carbine.

**Comment by Archanial** [comment]
> The gun names look out of place.
> Energy Gun, disabler, beam marksman rifle, Laser gun, Laser scatter shotgun, M19C Pulse Carbine.

Okay so
Pulse riffle is admin only spawn and if we like new more lore friendly names we can change rest in future.

**Comment by PowerfulBacon** [comment]
Change all or none at once. I have never seen anything actually happen from someone using 'It can be done in the future' as an excuse to get something in now.

**Comment by PowerfulBacon** [comment]
Going to assume this PR wont be changed at all considering the authors account is deleted

**Pull request closed without merging**
