### PR TITLE
Traitor Items based off #3181

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Adds two new traitor items, based off #3181.

* Invisible Ink: Curator item, invisibilium disguised as a regular ink bottle. 1 TC, curator specific
* Alchemy Kit: A alchemy manual, with a bottle of alchemic precursor hidden inside of it. Contains all the recipes, and plenty of material to make your own. 3 TC, available to chem, CMO, bartender and curator.

## Why It's Good For The Game

Alchemy is fun.

## Changelog
:cl:
add: Invisible ink, curator specific uplink item available for 1 TC
add: Alchemy Kit, chemist/CMO/bartender/curator item available for 3 TC
/:cl:

### CODE REVIEW

**Comment by bloons3** [comment]
What does invisible ink actually _do_?

**Comment by eeSPee** [comment]
> What does invisible ink actually _do_?

Turns you invisible after you drink it.

**Comment by OceanFish1** [comment]
Get alchemic precursor - add raw meat - turn the station into gold - ??? - thats how cargo works

**Comment by Goblinu** [comment]
> 
> 
> > What does invisible ink actually _do_?
> 
> Turns you invisible after you drink it.

If theres something the reactive stealth armor has taught me, invisibility is beyond broken

**Comment by ike709** [comment]
🔑

**Comment by francinum** [comment]
🔑 @TheFakeElon @francinum @ike709

**Pull request closed without merging**
