### PR TITLE
Revert "Makes scrubbers filter BZ out of the air by default."

### PR DESCRIPTION
**Pull request by 4rchibald**
Reverting PR that was solving non existing issue. 
BZ is produced by combining plasma and n2o, both gases normally are not present in air around the station, what's more conditions like low pressure and certain amount of moles must be met. 
Since PR was merged I was checking (just to be sure I'm not missing something) waste pipe and mixing tank (where all waste not filtered into other tanks is dumped) and I haven't detect even trace amounts of BZ during most, even long round. And every single time I found some BZ in there it always had a source in either atmos or toxins or someone running around with BZ tank from xeno.

Whatever situation caused Bacon to make that PR I believe it was something local. Its simply not possible for BZ to be created on its own, especially in amounts he claimed, during anything that we can reasonable expect to happen during each round. If BZ is created its in artificially made setups, atmos experiments that make it as product or byproduct. 
The only gas I would say is always being produced during natural live of station is miasma, mostly in medbay, but I don't think its in amounts that would justify setting scrubbers to filter it either. BZ is in the same boat as tritium or stimulum and I don't think anyone believes they should be scrubbed by default. If we're not scrubbing gases that we actually have incredible amounts of in tanks and canisters (like n2o or plasma) around station why would we do that for gases that are artificially and purposely made by players?

Its not a big issue but I believe it should be reverted. I would also like to point out that maybe we should give each other some time for discussion before merging anything since BZ creation circumstances could have been discussed and reverting it all now could be prevented but PR was merged just within few hours and apparently nobody cares to talk about things that are already merged, I expressed same thought few days ago but nobody cared to revert the PR nor reply to explain why it should stay, that's why i'm making this reverting PR now

### CODE REVIEW

**Comment by Chessus** [comment]
I think the having the entire station is a bit much but definitely the Lavaland base should as BZ is always present there and those gases seem to always seep in past the airlock.

**Comment by PowerfulBacon** [comment]
Where does the bz come from is a good question

**Comment by zeskorion** [comment]
as i see it, there is no reason bz should not be scrubbed by default

**Comment by 4rchibald** [comment]
@zeskorion 

Is there any reason why BZ should be scrubbed? And if so why doesn't that reason apply to other gases?
The only gas that is always produced no matter what is CO2, where are players there is carbon dioxide and that was for longest time the only gas we were scrubbing by default.
The only other gas next in line that we could assume appears fairly natural would be miasma, cause sooner or later people will get hurt or even die. But as said, I don't think it usually happens in amounts that would justify scrubbing it by roundstart. Let atmos technicians handle removing that and other gases when its needed.

BZ? We don't even have BZ on station except for one canister in fairly secure place which is xeno lab. When it comes to gases we have, there's plenty of n2o and plasma in both canisters and huge tanks with gas miners in each one giving us basically unlimited amount of those gases. So why not set scrubbers to remove them? They pose a bigger threat when it comes to accessibility, ease of putting them in distro pipe and damage they could cause.
To get BZ you need to build a special set up, create it on purpose. How is that gas different from tritium, nitryl or stimulum? Why aren't those scrubbed? 

I don't really get what's happening here. Sorry, I know nothing about local politics so I may be missing something. I'm not trying to revert it because I have anything against @PowerfulBacon or anything like that. I just don't think the original reason for that PR holds up. We should either revert to scrubbing only CO2 or go further and basically start scrubbing all gases cause the same reasoning that applies to removing BZ from air applies to other ones (Which seem to also be in line of making atmosians completely irrelevant, just like adding gas miners did). I'm really confused with the push back I get here since all arguments are on the table and at the same time, the original PR got merged just within hours without anyone asking a single question

**Comment by Moccha-Bee** [comment]
i agree, bz is a rare gas and is never found inside the station, and its a pain for people filtering tritium having to uncheck other gasses that don't even need to be checked in air scrubbers.

**Comment by eLeCtrOssSnake** [comment]
Of course revert.

**Comment by Chessus** [comment]
Does this change the lavaland base air alarms? They really only need the thiswell set to contaminated?

**Pull request closed without merging**
