### PR TITLE
Adds maint-dead-assistants into crew manifest

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
Adds maint-dead-assistants into crew manifest

## Why It's Good For The Game
Although dead assistants in maint are something that can be interesting, we already know they are not a real player because they aren't in crew manifest - They don't create any story. By adding them to the crew manifest, people will be capable of using them actively - especially cheating people with their identity.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
code: adjusted some manifest related codes
code: added 'skip_error' parameter in job subsystem
tweak: dead assistants spawned in maints are now added to crew manifest
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
I like this idea but I feel like it might cause more confusion and random manhunts than anything

**Comment by Dejaku51** [comment]
why would "previous crew" be in crew manifest

also only assistants? there are dead clowns too

**Comment by EvilDragonfiend** [comment]
> why would "previous crew" be in crew manifest
also only assistants? there are dead clowns too

I don't want them to be just not-a-part-of-station. They're pretty featureless.
and as far as I know, the clown is just a mob, not a real human mob. lavaland clowns are real humans but they're difficult to be seen as as a previous crew even.

**Comment by EvilDragonfiend** [comment]
> I like this idea but I feel like it might cause more confusion and random manhunts than anything

manhunt seems to be a far gone decision if someone is going to do so. they might be dead due to floorpills or suicided. who knows. some confusion from them is intentional though.

**Comment by St0rmC4st3r** [comment]
Could we, maybe, also get it as a mapping helper? You know, for slapping it over other corpse spawners where necessary.

**Comment by EvilDragonfiend** [comment]
> Could we, maybe, also get it as a mapping helper? You know, for slapping it over other corpse spawners where necessary.

helper will be not necessary. set corpses' `inject_crew_manifest` variable to FALSE in dmm.

**Comment by Fronsis** [comment]
> > why would "previous crew" be in crew manifest
> > also only assistants? there are dead clowns too
> 
> I don't want them to be just not-a-part-of-station. They're pretty featureless. and as far as I know, the clown is just a mob, not a real human mob. lavaland clowns are real humans but they're difficult to be seen as as a previous crew even.

There's a maint room which usually containes a blood trail, sandbags, bullet cases a dead assistant and an actual dead clown next to a Germ and i think insulated gloves, it spawns from time to time.

**Comment by EvilDragonfiend** [comment]
> > > why would "previous crew" be in crew manifest
> > > also only assistants? there are dead clowns too
> > 
> > 
> > I don't want them to be just not-a-part-of-station. They're pretty featureless. and as far as I know, the clown is just a mob, not a real human mob. lavaland clowns are real humans but they're difficult to be seen as as a previous crew even.
> 
> There's a maint room which usually containes a blood trail, sandbags, bullet cases a dead assistant and an actual dead clown next to a Germ and i think insulated gloves, it spawns from time to time.

now I can recall of that specific maint room. since it has only one clown type, I will change a single data in dmm instead of making a subtype.

**Comment by Tyranicranger4** [comment]
This seems like it'll get annoying really quickly.

**Comment by Fronsis** [comment]
I'll have to agree, as someone whos sec-medbay main it'll get tired very quickly and we'll go back to a similar ''it's a maint body/from a previous shift'' If on top of that we had the syndicate fake empty boxes on maint it'll lead to unecessary man-hunts

**Comment by EvilDragonfiend** [comment]
guys, the point is not to direct players to chase an unknown murderer who might have killed those assistants. It's allowing to use dead assistants' identity when someone is going to decide using theirs.

>  especially cheating people with their identity.

the PR body said it already.

**Comment by itsmeow** [comment]
🔑 
I think the manifest should largely be accurate to actual players at roundstart and not include random bodies. I'm not convinced this is a good idea.

**Comment by EvilDragonfiend** [comment]
> be accurate to actual players

but datacore doesn't work like how you said. you can add/remove anyone crew manifest.

**Comment by Archanial** [comment]
I agree, also mail to npcs is stupid

**Comment by EvilDragonfiend** [comment]
> also mail to npcs is stupid

This isn't how mail works. It picks minds, not dead bodies.

**Pull request closed without merging**
