### PR TITLE
Nanotrasen brand IPC kits

### PR DESCRIPTION
**Pull request by St0rmC4st3r**
## About The Pull Request
First of all, I would like to make something clear. Yes, these kits are supposed to be as overpriced as overpowered. The cables actually run out faster when used on little burns, and plates are actually useful only when you need to get the IPC up FAST or you are a moth. The injectors are actually giant multi-usable medipens, which make them not rechargeable.

This PR adds powerful, yet fairly expensive IPC repair kits. 
Each kit have enough stuff to repair brain and toxin damage to an acceptable level to 5 IPCs and quickly fix 2000 brute and burn. When you count in that IPCs usually come with over 500 damage total, it is not that much. 

Maybe cranking the cargo price up a bit would be a good idea. Perhaps 5000 will be good?

I have absolutely no idea how to map stuff, so please, someone add one or two of these in robotics on the maps if this PR will ever be merged.

Also someone should sprite a good kit sprite and maybe the modular plates sprite, since I have no idea how to sprite properly and the current plate sprite is my reskin of some cock cult thing.

## Why It's Good For The Game

These kits are for roboticists that hate to repair that IPC with 150 brute and 350 burn after whatever situation they've been through.

## Changelog
:cl:
add: Added IPC repair kits.
code: Changed how medicines check for limbs (not) being robotic.
/:cl:

### CODE REVIEW

**Comment by Toxici11i** [comment]
Today with nanotrasen flex tape, we instantly repair IPC's!

This literally removes the point of having them have to manually repair, rather than chug meds like normal people.

pricing for this is gay too, considering how people can just sell tritium tanks from atmos for around >400K a piece, and they arent hard to mass produce

**Comment by St0rmC4st3r** [comment]
Fair enough. Nerf, nerf, nerf, nerf and stop coding when undersleped.

**Comment by St0rmC4st3r** [comment]
Nerf to hell/remove the flex tape, remove from cargo and leave only to robo men roundstart. Because the injectors might be actually cool.

**Comment by St0rmC4st3r** [comment]
Balancing things never was my strong side.

**Pull request closed without merging**
