### PR TITLE
Removing clwne

### PR DESCRIPTION
**Pull request by SergeiKoralev**
## About The Pull Request

This PR removes the floor clwne random maintenance rooms that give administrators headaches.

This time also removing them from the random_rooms.dm! 

## Why It's Good For The Game

Those rooms cause nothing but pain and misery. They were a mistake.

## Changelog
:cl:
remove: the clwne random maint rooms
/:cl:

### CODE REVIEW

**Review by zeskorion — DISMISSED** [review]
just... comment out the code that allows people other than cultists to invoke it? the rooms themselves arent terrible

**Comment by SergeiKoralev** [comment]
> just... comment out the code that allows people other than cultists to invoke it? the rooms themselves aren't terrible

I'm a mapper, not a coder. I'm offering a mapping solution. If you want to make a coding solution then make a coding solution.
Edit: As well, yes, it is terrible, because it's a random shuttle-calling spawn.
Edit 2: If it's so easy to do then why don't you fix the thing that you created?

**Comment by Archanial** [comment]
The room doesn't look good so just remove it

**Comment by SergeiKoralev** [comment]
As well, in PR #2733 you specifically referenced multiple possible solutions, to include removing both the map files and random_rooms.dm entry, which this PR does, so you're also moving the goal post and not offering a proper solution to the problem.

**Comment by zeskorion** [comment]
> As well, in PR #2733 you specifically referenced multiple possible solutions, to include removing both the map files and random_rooms.dm entry, which this PR does, so you're also moving the goal post and not offering a proper solution to the problem.

no, i told you the pr would not work as you made it due to the fact that the room would still try to appear, just without a valid map

**Comment by SergeiKoralev** [comment]
And then closed it before I could correct it as my schedule has been extremely busy. Now I have corrected the issue and am re-submitting the mapping solution to the issue that you refuse to solve with a coding solution.

**Comment by zeskorion** [comment]
> And then closed it before I could correct it as my schedule has been extremely busy. Now I have corrected the issue and am re-submitting the mapping solution to the issue that you refuse to solve with a coding solution.

because it's quite easy to do. observe:
image
a few lines in mainttraps.dm

**Review by PowerfulBacon — APPROVED** [review]

**Comment by SergeiKoralev** [comment]
Once again. I am a _**mapper.**_ I **_do not code._**
Edit: If it's so easy then you do it and merge a PR, link it here and I'll close this one myself!

**Review by francinum — APPROVED** [review]
Removing the maps is a suitable solution.

**Pull request merged**
