### PR TITLE
Removes stalk from heretics and increases the chance of hijack/ascend from 5 percent to 10

### PR DESCRIPTION
**Pull request by TeomanTheGreat**
## About The Pull Request
As of right now, Heretics is not exactly the best-made antag for this server however I think we can all agree that sitting around for 5 minutes and stalking someone isn't fun especially if it doesn't even tell you how long you've been staring at them for. In order to make up for the lack of this objective, the percent of hijack/ascend is now 10 instead of 5 (if requested I can remove the increased chance for hijack and ascend).

## Why It's Good For The Game
Removes a really really really boring objective.

## Changelog
:cl: Phil Smith
tweak: Heretic hijack and ascend percent chance is now 10 percent instead of 5.
del: Removes stalk from heretics.
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
bad pr, makes heretics even more murderboney

**Comment by qwertyquerty** [comment]
:key:

**Comment by TeomanTheGreat** [comment]
If the increased bone chance is the problem i can remove it as said in the pr description

**Comment by PowerfulBacon** [comment]
:key: They really need a full rework to become a not murderbone antag rather than make them more murderboney

**Comment by PowerfulBacon** [comment]
> 
> 
> 🔑 They really need a full rework to become a not murderbone antag rather than make them more murderboney

Or a full removal since they are poorly designed for servers that aren't TG

**Comment by OceanFish1** [comment]
No fun allowed

**Pull request closed without merging**
