### PR TITLE
Adds a craftable shank

### PR DESCRIPTION
**Pull request by Arrfur**
## About The Pull Request
Allows for crafting of a [Shank.](https://gyazo.com/1f9ee891750a01a3e1d31f5dad56c74a) The shank is simply some cable wrapped around a shard of glass to be used as a handle. It does slightly more damage than a shard of glass, is small, and wont cut your hand.
However, when thrown at someone it has a 40% chance to embed into them.

## Why It's Good For The Game
The shank fills the role of a 1-handed, craftable meele weapon; but also as a disengage or chasing tool (tho really you should just use bolas tbh)
The idea is that you can throw it at someone chasing you, and they will have to stop chasing you or risk taking more damage.
Honestly im just practising BYOND stuff but I thought this would be neato still.

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by CthulhuOnIce** [comment]
FUCKING MODULARIZE REEEE

**Comment by Arrfur** [comment]
oh sorry, could you teach me how to?

**Comment by CthulhuOnIce** [comment]
Just move your code to a file in the `beestation` folder, then if it's a new file, tick it in `beestation.dme`

**Comment by Arrfur** [comment]
i addeded the commit to make it do the modularbingbong :)
thank for the big brian learning thooloo

**Comment by CthulhuOnIce** [comment]
np dad

**Pull request merged**
