### PR TITLE
Makes the syndie medical cyborg use the cyborg defib so it might actually work

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

changes 1 line of code

## Why It's Good For The Game

yes

## Changelog
:cl:
fix: Syndicate medical defib padels can now be equipped
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
Poggers

**Review by zeskorion — DISMISSED** [review]

**Comment by TeomanTheGreat** [comment]
Merge when

**Comment by PowerfulBacon** [comment]
ah did someone to some CRLF shit, my entire file is merge conflicted which is annoying

**Comment by TeomanTheGreat** [comment]
Jeez this is old

**Pull request merged**
