### PR TITLE
[READY] Adds Cadets and Deputies

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request

Adds two new security jobs: Cadets and Deputies (on the left and right accordingly in the pic above).

Deputies have no roundstart job positions but Cadets have four slots (one for each department) and the HOP can open more if necessary.

**Cadets**
This is basically a support role for Security, like an Officer but less high-stakes so it's suited to beginners to Security.

Deal with people committing minor crimes whilst leaving the bigger stuff to Officers, stick to your assigned post rather than aggressively patrolling, etc. You're expected to be newer to Security or just wanting an easier time.

Equipment-wise they lack a disabler but are otherwise the same as Security Officers including in access. Like Officers they're also assigned to a department.

**Also** the playtime requirements for all security jobs have been changed, so cadet is the first sec role that crew will have access to. Now you have to have 10 hours of Security playtime to unlock HOS, 7 for Warden, 5 for Security Officer, 3 for Detective and 2 for Brig Physician.

**Deputies**
Deputies are not available as a roundstart role because:
- They're non-mindshielded and we don't need more roles with Brig access who can instantly start deswording security whilst they're still getting their gear on
- It's bait for people who normally validhunt as an assistant and want extra gear that helps them to tide better

But they are a job rather than just a gear bag because:
- HOPs have no excuse now for promoting people without background checks to full Security Officer when there's a role designed specifically for these people
- Allows you to quickly identify Deputies through secHUDs

It's intended that the HOS approves people to get promoted to Deputy and buys them the gear bag from the SecTech vendor, then once dressed they go to the HOP and get their ID updated to the same. 

Deputies get a modified security belt with pepperspray, a deputy baton (weaker than detective baton at 15 damage, no knockdown but lower cooldown), handcuffs, cable restraints and a seclite. They have a normal sec headset (not bowmans), a reskinned secHUD (not HUDsunglasses) and no armor. Access to the Brig but not to the Security Office/Gear Room (similarly to Lawyers). 

So they're not really any more dangerous than an assistant with a cakehat and they'll almost always need help to forcibly arrest anyone but they make good extra bodies for patrols and backup.

## Why It's Good For The Game
Cadets provide an option for people who avoid picking Officer for whatever reason but still want to help with the station's wellbeing in an easier role. 

Deputies give a way for a HOS to easily deputise crew and standardises what access and gear they should have. 

## Changelog
:cl:
add: Adds Deputies, a non-roundstart non-mindshieled security job. Ask the HOS to buy you the deputy bag from the SecTech and the HOP to promote you after. 
add: Adds Cadets, a roundstart mindshielded security job intended to be good for beginners to security or those wanting a slower pace than Officer.
tweak: Security playtime requirements changed. All security jobs except Cadet now require Security playtime instead of general crew hours and the amount of hours is increased.
/:cl:

Ports:
https://github.com/TheSwain/Fulpstation/pull/108

### CODE REVIEW

**Comment by ghost** [comment]
i dont know i feel like cadets are just gonna be easy targets for brig acces

**Comment by PowerfulBacon** [comment]
My issue with this is that cadets are exactly the same as normal officers, they get an assigned department etc. but they don't have a disabler so there isn't much reason to be one, deputies require you to trust someone enough to not be a traitor (since you are just giving non confirmed people access to security).

Also with cadets, what's to stop them just going and grabbing a disabler from the security lockers anyway?

**Comment by VictorVow** [comment]
Disablers aren't in security lockers, they spawn on Officers and in the Armory. The reason to be a Cadet is in the OP, it's not about having less gear it's about RP having different responsibilities and expected competence, and you're literally not allowed to be anything other than Cadet when you have little sec playtime. 

Command often deputises people but they trust them too much, and have to give them the full Security Officer job because there isn't a lesser form of security job available to pick from. Deputy gives them that option, standardises what they should have and gives a reminder to Security who *do* have background checks that this person hasn't had a background check and is thus someone to keep an eye on still.

**Comment by VictorVow** [comment]
@zeskorion ready for a vote

**Comment by Lagomorphica** [comment]
ah good, more lootbags to munch on

**Comment by qwertyquerty** [comment]
Vote failed and I don't like it either

**Pull request closed without merging**
