### PR TITLE
crew transfer requests now take a bit longer to start so people can do more roleplay or whatever

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request

makes the crew transfer request only happen at 2hours 30 minutes

## Why It's Good For The Game

people should NOT call the shuttle because they are bored, its an EMERGENCY SHUTTLE, not a "im bored" shuttle, if you are bored you can either cryo or try and do something fun, random events also exist to spice up the round, i see no reason why a relaxed roleplay server even has something like this, ive had many occassions where ive been cucked by this because Grey Mcshit ran out of valids to hunt

## Changelog
:cl: 
config: an extra hour passes before crew transfer request start to happen on sage
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
should mention its a kinda revert of #1855 while also keeping the feature

**Comment by ToasterBan** [comment]
i added a single fucking # how did i break

**Comment by VictorVow** [comment]
It's a reasonable feature - for example say the first one instead came 6 hours in, surely it's fair to ask the crew then? 

It's just a matter of adjusting the time. Perhaps moving it from 1:30 to 2:30 for the first alert.

**Comment by ToasterBan** [comment]
> It's a reasonable feature - for example say the first one instead came 6 hours in, surely it's fair to ask the crew then?
> 
> It's just a matter of adjusting the time. Perhaps moving it from 1:30 to 2:30 for the first alert.

actually that doesn't sound so bad ill change it to that

**Comment by ToasterBan** [comment]
requested changes done, if a maintainer prefers the older changes ill change em to the older changes I guess, but crossed words are final

**Comment by ToasterBan** [comment]
how did this make the checks succeed?

**Comment by francinum** [comment]
The failure is a known spurious runtime in turf decals, unrelated to your changes.

**Comment by heepox** [comment]
its a crew transfer tho... not an emergency shuttle call.

**Comment by ToasterBan** [comment]
> its a crew transfer tho... not an emergency shuttle call.

it uses the emergency shuttle, everything related to the emergency shuttle and it litterly is just an emergency shuttle vote

**Comment by heepox** [comment]
> > its a crew transfer tho... not an emergency shuttle call.
> 
> it uses the emergency shuttle, everything related to the emergency shuttle and it litterly is just an emergency shuttle vote

ye but it isint tho... its a crew transfer not some head asking for Y/N and deciding to call or not.

**Comment by ToasterBan** [comment]
> > > its a crew transfer tho... not an emergency shuttle call.
> > 
> > 
> > it uses the emergency shuttle, everything related to the emergency shuttle and it litterly is just an emergency shuttle vote
> 
> ye but it isint tho... its a crew transfer not some head asking for Y/N and deciding to call or not.

it still a "I'm bored call the shuttle", doesn't matter if it's reskinned, this makes almost every round end at around the 2 hour mark even if nothing is happening, there are many things to do if you are bored, and if you want a fresh new round go play on golden or something

**Comment by Rukofamicom** [comment]
Servers begin to show signs of instability by the 2-hour mark when population is above 50. OOM and/or other crashes are usually inevitable by 3 hours at standard population.

The reason the shuttle call occurs first at 1:30 is because the (current) longest amount of time a round is planned to last is 2 hours, and rounds should be wrapping by the 1:30 shuttle call anyway. So long as the station is at peace (green alert) the round won't actually end until just before 2:00 even if the vote to call is made at 1:30. 

Remember to adjust alert levels back down appropriately after threats have been dealt with instead of staying on blue permanently after the first threat is identified. You find evidence of one problem and catch that problem, lower the alert again.

**Comment by Rukofamicom** [comment]
Having a vote to leave is also a really healthy way to determine if the majority of players want a new round, because the current round is at or past its endgame

If you want slower rounds, some of these departmental buffs and "QoL" changes that removed player interaction and push the endgame earlier and earlier need to go. So long as community focus and desire remains on buffs and speeding up round progression, round conclusions will be reached sooner and sooner.

**Comment by utilbird** [comment]
^ crew transfer exists for a reason, if the majority of people aren't enjoying, why make them? Removing it or dragging it out to unreasonable times will just make players leave instead, making the round even less fun for those who are still playing.

**Comment by Sinestia** [comment]
Terrible

If you can't outvote the living people (not even dead can vote) then the round doesn't deserve to continue, 1 hr 30 minutes is already quite a long time. 

Bringing up it being "an emergency shuttle" in the OP is pedantic as hell and is literally just a consequence of calling the function with that string, and would be easy to change if it was that much of a bother to you. Actual good gimmicks are few and far between and most events that proc are just nothing, they aren't a replacement to an exhausted gameplay loop. 

take it to a discord dm for rp or local server for autism engineering if you gotta hold the game hostage.

**Comment by francinum** [comment]
This is not the solution.

The crew transfer vote is *explicitly* an I'm bored vote.

**Pull request closed without merging**
