### PR TITLE
Xeno Acid Adjust

### PR DESCRIPTION
**Pull request by ro5490**
## About The Pull Request
This pull makes it possible for Xenomorph acid to melt through Reinforced Walls.

## Why It's Good For The Game
Xenos can now escape R_Wall'ed areas with enough time and effort

## Changelog
:cl:
code: removed acid power decrease on r_walls
:cl:

### CODE REVIEW

**Comment by bloons3** [comment]
This will let xenos out of their chamber in xenobio...

**Comment by ro5490** [comment]
its set so it takes a while to melt through, so if they're in xeno containment and they try to escape by doing that, the R&D guys can bust em up
if they're paying attention.

**Comment by grimmmy** [comment]
It makes it nigh impossible to make a xenomonopoly, though.

**Comment by ro5490** [comment]
Shield wall generators...theres always extra on the station to be used wherever, nd if you're containing xenos you should have a generator and a spare set of shields anyway... but I get it

**Comment by Bestparty** [comment]
But xenos can already melt Rwalls

**Comment by ro5490** [comment]
Nope, there was a line of code that pretty much nerfs acid into oblivion if its used on r_walls

**Comment by PowerfulBacon** [comment]
So, containment is impossible?
If you get xeno and spawn trapped it's your own fault, if you spawn as the xeno one from xenobiology then the point is that its contained (until a power breach or moron let's you out) and someone already purposely ran into it.
Just seems kinda pointless to me having the xeno chamber not being able to contain them and makes the xeno egg event pointless for the scientists since it pretty much guarantees an infestation and early round end unless they are just outright killed

**Comment by ike709** [comment]
Vote technically passed but it was highly controversial.

**Pull request closed without merging**
