### PR TITLE
Defib can no longer be emped to disable safeties

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Removes the ability of EMP toggling safeties on defibs.

There's many possible ways to go about nerfing this. I've chosen to remove only the EMP part as it still leaves options for antags with their emags. There's no reason for non-antag doctors to have better melee weaponry than security straight from their lathe.

It's not even logged, and I regularly see doctors "coincidentally" having safeties off every round despite not being antags.

## Why It's Good For The Game

No more powergaming doctors stealthily mixing some EMP reaction (uranium+iron, both from their own lathe) for a guaranteed instant stun melee weapon that can also easily kill. Instant stuns should be harder to get.

## Changelog
:cl:
balance: Defib safeties can no longer be changed with EMP.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
clings cant get emp defibs
 anymore. everyday cling get nerfed and nerfed :(

**Comment by WhyIsCaeciliusTaken** [comment]
Defib is not an instant stun anymore. It knocks down and causes convulsions (random item dropping).

**Comment by ivanmixo** [comment]
> Defib is not an instant stun anymore. It knocks down and causes convulsions (random item dropping).

Still superior to the stunbaton in every way. At least the compact one.

**Comment by PowerfulBacon** [comment]
I had a major issue with this, however things like this need to exist for things like blood brothers who are smart.
The issue comes from CMOs and the like powergaming it to have an instant knockdown at all times.
But also at the same time, I do not think its intentional at all, since in the code it references the variable for safeties as being the ability to kill people that are alive and the combat var should be for stunning.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
While this does reduce powergaming CMOs, it comes at a cost of reducing the options available for budget antags such as BBs, lings or anyone without an emag.
If you are going ahead with this, change it so the safety variable does what it says and the combat var is checked for stunning, while safety is checked for killing on harm intent.

**Comment by ghost** [comment]
> If you are going ahead with this, change it so the safety variable does what it says and the combat var is checked for stunning, while safety is checked for killing on harm intent.

I will do that, can you word exactly how you imagine defib should interact so there's no ambiguity?

What I think you mean:
Combat = can stun, can kill
Safety = no stun, can kill

**Comment by ItsTisme** [comment]
>What I think you mean:
Combat = can stun, can kill
Safety = no stun, can kill

I think combat can stun but not kill, and safety can kill but not stun

Should you want it you can turn on both or only 1 of the 2

**Comment by ghost** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/3503

Alternative solution.

**Comment by VictorVow** [comment]
Instead of instant knockdown just make it do a lot of stamina damage like stunprods.

**Comment by nikk735** [comment]
the stun is already weak dude

**Comment by PowerfulBacon** [comment]
Closing in favour of #3503

**Pull request closed without merging**
