### PR TITLE
Hygiene is now tied to mood

### PR DESCRIPTION
**Pull request by francinum**
## About The Pull Request
No more miasma generation
Stank visual only appears at 0 hygiene
Neat quirk removed, Now standard behavior
Tweaked the values of the relevant moodlets

## Changelog
:cl:
balance: Neat moodlet integrated into standard behavior
balance: To go along with that, the relevant moodlets have been adjusted.
tweak: Hygiene visual effect only happens when you can't get any dirtier
code: Hygiene no longer generates miasma
/:cl:

### CODE REVIEW

**Comment by eeSPee** [comment]
I don't know... This will reduce the amount of random diseases overall, and give people even less of a reason to shower/clean.

**Comment by francinum** [comment]
> I don't know... This will reduce the amount of random diseases overall, and give people even less of a reason to shower/clean.

The miasma amount was *literally worthless* besides waking up the atmos system. This won't affect that at all.

And I honestly don't find the act of completely interrupting game flow just to find one of the 5 or so points on the station with shows very engaging.

**Comment by Archanial** [comment]
Make gamer trait that let's you ignore hygiene

**Comment by OceanFish1** [comment]
> Make gamer trait that let's you ignore hygiene

discord mod trait 😳

**Pull request merged**
