### PR TITLE
Changeling fix

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request

changelings shouldnt have to impersonate ipcs anymore

## Why It's Good For The Game

fixes
## Changelog
:cl:
fix: changeling impersonate objective now checks is_valid_target
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
is_valid_target needs to be added to the cult sacrafice I believe

**Comment by PowerfulBacon** [comment]
A better fix be having find_target pick a valid target so that if it doesn't choose a valid target they still get the objective, just someone else as a target

**Comment by zeskorion** [comment]
> A better fix be having find_target pick a valid target so that if it doesn't choose a valid target they still get the objective, just someone else as a target

yeah but I prefer impersonate objectives being rarer, as they're far harder to pull off

**Comment by PowerfulBacon** [comment]
> > A better fix be having find_target pick a valid target so that if it doesn't choose a valid target they still get the objective, just someone else as a target
> 
> yeah but I prefer impersonate objectives being rarer, as they're far harder to pull off

But then bugs with blood cult valid target would be fixed too, and everything in the future.

**Comment by zeskorion** [comment]
> > > A better fix be having find_target pick a valid target so that if it doesn't choose a valid target they still get the objective, just someone else as a target
> > 
> > 
> > yeah but I prefer impersonate objectives being rarer, as they're far harder to pull off
> 
> But then bugs with blood cult valid target would be fixed too, and everything in the future.

this is just a quick fix for lings that ike requested. I am not going to expand the scope of this pr to encompass cult's bug as well. You're the cult guy.

**Comment by PowerfulBacon** [comment]
> 
> 
> > > > A better fix be having find_target pick a valid target so that if it doesn't choose a valid target they still get the objective, just someone else as a target
> > > 
> > > 
> > > yeah but I prefer impersonate objectives being rarer, as they're far harder to pull off
> > 
> > 
> > But then bugs with blood cult valid target would be fixed too, and everything in the future.
> 
> this is just a quick fix for lings that ike requested. I am not going to expand the scope of this pr to encompass cult's bug as well. You're the cult guy.

It's not a bug with cult specifically, it's a bug with ALL objectives that use is_valid_target, since is_valid_target is never called

**Pull request closed without merging**
