### PR TITLE
Felinids purring heals those nearby also fixes felinid shitcode

### PR DESCRIPTION
**Pull request by Sinestia**
## About The Pull Request
https://github.com/Skyrat-SS13/Skyrat-tg/pull/6381

when a kitty purrs it heals the wounds of those adjacent to them elon asked for this and i couldnt say no i was too enthralled in the curse to not PR this also I noticed that the race check for felinids was really dumb it has no reason to be distinct (probably has to do with them being a weird split back in tg days nothing seems to break from fixing it) also iscatperson is a bad name for it it should really be isfelinid also one bee-unique problem is that we basically dont have a reasonable cooldown on emotes so nerfing it to like 0.25 damage heal still makes it extremely OP this sentence is finally over. 

## Why It's Good For The Game

it isnt

## Changelog
:cl:Froststahr
add: Felinid purrs now heal those around them. 
add: Oh yeah, purr is now an emote with a sound!
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
Now this is epic

**Comment by yyzsong** [comment]
Now this is epic

**Comment by fighterslam** [comment]
now this is epic

**Comment by Septoxide** [comment]
Now this is epic.

**Comment by ToasterBan** [comment]
did you get maintainer approval to touch species code?

**Comment by ivanmixo** [comment]
Should implement a cooldown so people don't get instaheals with ctrl+c ctrl+v

**Comment by WhyIsCaeciliusTaken** [comment]
Hmm yes no cooldown AoE heals that make absolutely 0 sense and break contribution guidelines.

**Comment by PowerfulBacon** [comment]
Needs maintainer approval, also this is a stupid idea and would be closed anyway probably.

**Comment by Sinestia** [comment]
image


take that illiterate duymmie

also >ignoring blatant code improvement cyka

**Pull request closed without merging**
