### PR TITLE
Fixes a battle royale typo

### PR DESCRIPTION
**Pull request by yyzsong**
## About The Pull Request
image

## Why It's Good For The Game
Typo bad

## Changelog
:cl:
spellcheck: Fixes a typo in battle royale supply drops
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
feature

**Comment by yyzsong** [comment]
Then add the removal tag

**Review by utilbird — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
ahhhhhh this could have been bundled in with the actual BR update and now will conflict it

**Comment by yyzsong** [comment]
> ahhhhhh this could have been bundled in with the actual BR update and now will conflict it

haha coder 😏

**Pull request merged**
