### PR TITLE
[READY] The great resprite: Suits! engineering ones.

### PR DESCRIPTION
**Pull request by SomeAngryMiner**
## About The Pull Request

its that time of the year again.
another part of the resprite wave, last one from the original pr: suits!
hardsuits are cool, pretty cool, but... they are variations of the same deadspace reference, so decided to spice that up.
You can see some of the differences here.

also changed: uniforms of the engineering department.

removed a duplicate riot armor icon, dunno what it was doing there.

gasmasks got a new groove, as seen in the picture below.

great engineering backpacks by @Agameofscones , inhands included!.

sec hardsuit resprites by @thatguythere03 , now they look more heavy duty than before, and overall more intimidating.

as per requested, the atmos suit was changed, as well.

skinsuit codersprite replaced.

*every* snowcoat got replaced.

honestly check the icon diffs  i might have forgotten something

im mentally prepared for travis to eat my face off with 1000 conflicts :).

image
image
image
image
image

## Why It's Good For The Game

new suits, visual distinction of bee, wiping codersprites, what i always say on these kind of PRs.

## Changelog
:cl: Azlan, Thatguythere03, Triiodine
imageadd: resprites engineering suits, radsuits, gasmask, engineering uniforms, workboots, sec hardsuits, snowcoats, skinsuits, engineering backpacks, insuls and magboots.
imagedel: no more duplicate riot armor on the icon files.
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
I dunno about this one. Some of the sprites look good but others don't fit in with the artstyle of the rest of the game.

**Comment by SomeAngryMiner** [comment]
this bundle of PRs is literally for giving the game a cohesive style, bruh.

**Comment by SomeAngryMiner** [comment]
image
image

top is the new backpacks, second image (bottom row) is the new sec hardsuits.

**Comment by ghost** [comment]
You good mate? I think you got those two images reversed

Edit: ohhhh you are probably Australian that makes a lot more sense

**Comment by SomeAngryMiner** [comment]
shshshsh, im not crazy (yet), fixed it.

**Comment by AnjelicaChaykovsky** [comment]
new sec hardsuits. 

Hardsuits ? So both of them, hos too ? 
Which are the coolest on station ? 
current hardsuits  have much better quality and better clarity than  ones you want to add... And even the kinda bad hardsuits which could use a upgrade cmo for example ? You dont upgrade them.

You shouldnt add new sprites to add like you said yourself " muh style" But instead make them actually better..

**Comment by SomeAngryMiner** [comment]
> Hardsuits ? So both of them, hos too ?

both of them, yeah. The HoS one looks like an upgraded, more plated version of sec hardsuits as well.

> Which are the coolest on station ?

could argue that with the standard security hardsuit, but HoS does have a strong quality

> current hardsuits have much better quality and better clarity than ones you want to add... And even the kinda bad hardsuits which could use a upgrade cmo for example ? You dont upgrade them.

To easily keep track of all changes im making, im doing it by "modules", example, a PR with all tools, then one with all stockparts, and now, one with all *engineering* suits, Medical is later down the road. Reason why sec hardsuits are there is because thatguy 
did them, and had no way to PR them, so i slapped them in, less work for the future.

If you have a problem with the new sec hardsuits, give us a list of what's wrong and we'll get it fixed before the merge, its pretty easy.

> You shouldnt add new sprites to add like you said yourself " muh style" But instead make them actually better..

Yeah, i thought that engineer suits were aging, and since they were just carbon copies of each other but with different base colors, a good twist could be good. Style is secondary, but still an objective of the PRs.

**Comment by AnjelicaChaykovsky** [comment]
> > Hardsuits ? So both of them, hos too ?
> 
> both of them, yeah. The HoS one looks like an upgraded, more plated version of sec hardsuits as well.
> 
> > Which are the coolest on station ?
> 
> could argue that with the standard security hardsuit, but HoS does have a strong quality
> 
> > current hardsuits have much better quality and better clarity than ones you want to add... And even the kinda bad hardsuits which could use a upgrade cmo for example ? You dont upgrade them.
> 
> To easily keep track of all changes im making, im doing it by "modules", example, a PR with all tools, then one with all stockparts, and now, one with all _engineering_ suits, Medical is later down the road. Reason why sec hardsuits are there is because thatguy
> did them, and had no way to PR them, so i slapped them in, less work for the future.
> 
> If you have a problem with the new sec hardsuits, give us a list of what's wrong and we'll get it fixed before the merge, its pretty easy.
> 
> > You shouldnt add new sprites to add like you said yourself " muh style" But instead make them actually better..
> 
> Yeah, i thought that engineer suits were aging, and since they were just carbon copies of each other but with different base colors, a good twist could be good. Style is secondary, but still an objective of the PRs.

Basically what  you did with old crappy parts   was great, the same with some of the tools - that needed an upgrade.
But hardsuits are  already cool unlike the outdated parts or tools.


this wintercloak for example is amazing from color palette to its balance, its very crisp, i could surely say thats cool.
And i wish the hardsuits would follow its example.
And the sec hardsuit, first one could replace regular one, but hos ? Hos one should be 10 times cooler like it currently is. 
Dont just add slight color difference and call it done

**Comment by SomeAngryMiner** [comment]
that security hardsuit up there in the sheet aint the HoS hardsuit, its a color variation of the sec hardsuit (didnt make it ingame)
image
this is the actual HoS hardsuit.
If more people seem to have a problem with the new sec hardsuits, ill ask thatguy to tweak them.

**Comment by r1ks-iwnl** [comment]
I don't like last 2 images of the sec and hos hardsuit since the helmet looks like it points towards the ground and sticks out in the back too much.

**Comment by zeskorion** [comment]
I really, really dont like changing the gas mask. rest is fine though

**Comment by TeomanTheGreat** [comment]
> I really, really dont like changing the gas mask. rest is fine though

This

**Comment by PowerfulBacon** [comment]
CE jumpsuit looks more like virology

**Comment by thatguythere03** [comment]
We're working on modifying the helmet and overall palette for the new security hardsuit sprites.
For some reason when I originally made the sprites, I used the existing hardsuit palette for the standard sec suit on the new ones, and the made some super dark black palette for the HOS variant.
I have no idea what I was thinking, but Az is taking care of the colors and I handed him a modified helmet design, so it should be handled.

**Comment by SomeAngryMiner** [comment]
image

final product of the tweaks on regular sec hardsuit, we are still working on HoS so far.

**Comment by Moccha-Bee** [comment]
speed merge?

**Comment by VictorVow** [comment]
- New sec hardsuit looks much better than the original
- HOS hardsuit I'd like to see with the new HOS cloak as well to see how it suits
- Engi and CE hardsuits stick out too much on the front and back, very chunky. 
- Engi and CE hardsuit screen on their arm looks too big on the side view. 
- Atmos hardsuit looks like they're leaning forward since the front is flat and the back doesn't stick out at all, but other than that I love the colour pattern. 
- Winter coat changes good though it's a bit shiny. 
- New skinsuit good
- Gas mask changes bad
- Show magboots with normal assistant uniform. Also show screenshots of the other sprite changes please.

**Comment by SomeAngryMiner** [comment]
image
image
here's a photo of a tider with the magboots, insuls and future grey jumpsuit n spear.
With Thatguy we reworked the HoS hardsuit as well.

**Comment by AnjelicaChaykovsky** [comment]
Since you are doing a resprite yog has really great canisters  that fit  well  with your new tools https://github.com/yogstation13/Yogstation/pull/9715

**Comment by SomeAngryMiner** [comment]
partheo did a great job with those, yeah, im considering them if our own canister style fails.

**Comment by SomeAngryMiner** [comment]
image
new advanced atmos firesuit, to pair with the new emergency firesuit.
PR should be ready, now.

**Comment by utilbird** [comment]
Ehh, the engi hardsuit change.. could you at least keep the dead space feel :p

**Comment by MCterra10** [comment]
why do the cans look blurry lol

**Comment by utilbird** [comment]
> Since you are doing a resprite yog has really great canisters that fit well with your new tools

isometric icons this large look horrible in 2d spessman game

**Comment by SomeAngryMiner** [comment]
time to get yelled at, boys.
testmerge worthy now.

**Comment by Isy232** [comment]
To be honest I like all of them

However I do not think the yog canisters fit our asthetic as well, they look a little too 3D.

**Comment by TheFakeElon** [comment]
Port bee station to unreal engine

**Comment by Penwin0** [comment]
The new CE jumpsuit does not fit the engineering asthetic at all looking more like a virologist, additionally the sprites for the advanced magboots and the CE hardsuit legs are exactly the same meaning if you have both on you can not tell if the boots are on or off something that was visible before

**Comment by Trash0077** [comment]
Whenever you make hardsuits widen at the top (engi and ce) it looks like they are leaning forward in an unnatural way, looks very bad.

**Comment by utilbird** [comment]
space arthritis :pensive:

**Comment by Crossedfall** [comment]
Currently test merged on Sage

**Comment by PowerfulBacon** [comment]
I'd merge this but I really don't like how the CE jumpsuit looks like a virology suit

**Comment by Crossedfall** [comment]
Re: CE - I think a more cream color would probably look a bit better. The current coloring is just a bit too... Sterile.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by BitBite112** [comment]
OOOOOI REVERT THE GASMASK!

**Comment by BitBite112** [comment]
No one liked the gas mask, would you please revert it? We all agreed it was iconic and should be untampered with.

**Comment by Vexylius** [comment]
those new sec hardsuits looks like kinda like they were syndie

**Comment by hotimep** [comment]
do not resprite the gas mask
it is like removing assistant from the game

**Comment by ike709** [comment]
I'm tired of seeing gas mask replies when the old ones are already being re-added in a separate open PR.

**Pull request merged**
