### PR TITLE
Harddel fix & optimization

### PR DESCRIPTION
**Pull request by ike709**
## About The Pull Request

See CL.

## Why It's Good For The Game

Code go brrrrr

## Changelog
:cl:
refactor: Maybe fixed a harddel with proximity checkers
refactor: Optimized /mob/log_message()
/:cl:

### CODE REVIEW

**Comment by celotajstg** [comment]
So I talked this over in /tg/, and we came to the conclusion changes in code/modules/mob/mob_helpers.dm are not necessary with this reasoning:

> Are you sure this works?
> 
> logging[smessage_type] is now going to be null, and null + x == x, meaning you're just going to be concatenating the strings > together. This doesn't make any sense to me.

If you can explain it, that would be nice.

Also there were some other changes to some of your code improvements that have been merged previously, feel free to check the PR.

**Comment by ike709** [comment]
Pretty much the only real issues there are `LAZYADD()`, which I'll have a look at later. Hell, using `as()` instead of `anything` is intentional until we've dropped support for versions prior to whatever fixes `anything`.

**Comment by TheVekter** [comment]
Hey, so we merged this along with a few other fixes on /tg/ and it looks like this breaks the hell out of Peacekeeper Borg's dampening field projector.

image

It doesn't actually delete them, so whenever you move you just leave a bunch of ghosts behind.

There might be something in your guys' code that fixes this but I figured I'd let you know just in case.

**Comment by celotajstg** [comment]
I'm pretty sure that's unrelated

**Comment by ike709** [comment]
Will revisit when I have time

**Pull request closed without merging**
