### PR TITLE
Rare HOS balance!!! (replaces the stun mode on the X-01 with a ion mode)

### PR DESCRIPTION
**Pull request by Therealdoooc213**
## About The Pull Request

replaces the stun mode on the X-01 with a ion mode

Ports:

- https://github.com/tgstation/tgstation/pull/44216

## Why It's Good For The Game

The X-01's stun mode is bad and not used often, the ion mode can be used for more things and is overall better.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

https://github.com/user-attachments/assets/7b0a8b8d-a650-4d33-be24-de995d707ec8

</details>

## Changelog
:cl: 4dplanner, therealdoooc

tweak: HOS gun now cycles disabler > kill > ion
balance: Due to budget cuts and several complaints from our civilian employees, the X-01 MultiPhase Energy Gun has been altered to fire silicon-destroying EMP bolts, and its taser function has been removed.
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
I'm not sure I like TG's direction on this. 

TG does not have to consider species like IPCs. If a HOS runs into them, the ion is very accessible and already in their pocket.

I like that the ion gun is a very specific weapon that can be targeted by those it threatens. Theres why we did not let security carry multiple armory guns on them in the past, and later modified their size so you couldn't carry a bunch.

Making it already be in the HoS's pocket just makes them more of an ideal candidate to be on the frontlines. They can quickly react to unique scenarios like MALF AI or hacked borgs with no little issue. I think we have enough of that kind of HoS player.

**Comment by MarkusLarsson421** [comment]
Sounds like an IPC issue. Concerns regarding IPCs severe weakness has already been brought up countless times. Perhaps this could be merged after an IPC buff is happening?

**Comment by DarnTheMarn** [comment]
>I like that the ion gun is a very specific weapon that can be targeted by those it threatens. Theres a reason why we did not let security carry multiple armory guns on them in the past, and later modified their size so you couldn't carry a bunch.

Yeah, I agree 100%. It's not like security can get multiple ions and get ions that fit in their backpack. Oh wait...

**Comment by DarnTheMarn** [comment]
I looked at the original port hoping to see some reasons for/against and it turns out [this was attempted before.](https://github.com/BeeStation/BeeStation-Hornet/pull/1067)

Not much info on it there, nor was there much info on the player input vote from back in the day. Never change, old bee.

Screenshot 2024-09-14 101043

Maybe if someone wants to dig a bit more they can find the reasons why it was so heavily downvoted.

**Comment by MarkusLarsson421** [comment]
Because the taser is OP as fuck.

**Comment by ClownMoff** [comment]
A buff would be adding the ion version too instead of changing something so good as the stun mode for something so situational.

**Comment by Geatish** [comment]
Honestly, the taser bolts are kinda op, but they at least work against everyone, the ion will seriously fuck over people with any robotic limb and sec has already access to flashes that disable borgs. This will basically be a lethal option against ipc's and ethereal's, so I expect a ton of salting when a HoS eventually murders or seriously fuck up one on green.  
IF someone gets around and buffs prosthetic arms so they don't hardstun you when emped, I probably would tip over to support this pr, otherwise I'm on the fence about this.
Also the avg HoS aim fucking sucks so I expect that multiple rooms will be spaced due to an air alarm getting emped

**Comment by Fronsis** [comment]
I do agree that this could be revisited if there are prs that adress the prosthethic limb issues + ipc's? (The biggest one people are talking about is the prosthetic limbs atm) 

Then again the HoS isn't supposed to be the first responder and charge right into battle, specially on Green alert or whatever, they're supposed to stay behind and coordinate officers unless they lack the manpower to deal with the present threat.


Two shots seems like a good enough amount and it would certainly be far more useful than the current "stun mode" it also has its downsides since you could EMP yourself/other officers and pay a high price

**Comment by MarkusLarsson421** [comment]
I'd almost say this is quite OP, as one shot against even someone who doesn't suffer consequences directly can still be bolted in by doors being hit by it.

**Comment by Rukofamicom** [comment]
Until / unless we get to making EMP substantially worse against the targets it's strong against, this is an absolutely terrible idea for game balance to make it so that one member of security nearly always has EMP available.

**Comment by Therealdoooc213** [comment]
Right, I'm going to close this PR until ion's are nerfed since I don't feel like diving into shitcode and doing it myself

**Pull request closed without merging**
