### PR TITLE
Removes auto punctuation from radio and say messages.

### PR DESCRIPTION
**Pull request by Chirynnn**
## About The Pull Request
Removes auto punctuation from say messages, radio messages but not emotes.

## Why It's Good For The Game
I'll be frank. Auto punctuation sucks for conveying your tone and attitude. Sure, you can use exclamation marks, tildes, quotation marks, whatever, but... I'm of the opinion that removing the dot at the end of your messages can leave your tone more.. up for interpretation, or relaxed, instead of forcing the other person to imagine your character talking in a deadpan tone. You could make a case for grammar here, but really, it's not worth the downsides in my opinion.
Sure, this could be just my interpretation, but I'm surely not the only one out there with this opinion, so if possible, put this up for a poll.

Small coder note: **/mob/proc/treat_message_min(message)** was left there because otherwise it breaks a whoooole lot of other stuff, and I don't think it's worth it since everything works as intended from the testing I have done.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/77589317/223802579-7033b0c1-0404-4242-884e-7785450ecf7b.mp4

</details>

## Changelog
:cl:
tweak: Removes auto punctuation from radio and say messages

/:cl:

### CODE REVIEW

**Comment by Chirynnn** [comment]
Uhh whoops, sorry about that

**Comment by imsynthex** [comment]
- https://github.com/BeeStation/BeeStation-Hornet/pull/5909

Round 2

**Comment by itsmeow** [comment]
I'm gonna have to agree with kapu, it should be a preference toggle

**Comment by Crossedfall** [comment]
🔑 

Even as a prefs toggle, I'd be against this.

**Comment by Chirynnn** [comment]
Okay sure, I can ask around on how to make it a pref toggle. But... is anybody going to elaborate on why exactly this is bad?

**Comment by Chirynnn** [comment]
I didn't do shit how did it suddenly conflict

**Comment by Crossedfall** [comment]
Your reasoning conflicts with itself. You mentioned that punctuation is terrible for conveying tone, all the while, saying that no punctuation makes it more ambiguous (which is somehow better?).

Ambiguity, with respects to tone, is a terrible change for roleplay. Tone should be conveyed as clearly as reasonably possible to facilitate more natural interactions. Unlike in-person or over-mic conversations, the reader has to do a lot of extra work in determining the overall meaning for each message so that they can respond in turn. Adding ambiguity into the mix just leads to needless misunderstandings for little-to-no gain.

**Comment by Chirynnn** [comment]
> Your reasoning conflicts with itself. You mentioned that punctuation is terrible for conveying tone, all the while, saying that no punctuation makes it more ambiguous (which is somehow better?).
> 
> Ambiguity, with respects to tone, is a terrible change for roleplay. Tone should be conveyed as clearly as reasonably possible to facilitate more natural interactions. Unlike in-person or over-mic conversations, the reader has to do a lot of extra work in determining the overall meaning for each message so that they can respond in turn. Adding ambiguity into the mix just leads to needless misunderstandings for little-to-no gain.

What I meant is that not forcing people to have periods at the end of their message means their tone won't sound deadpan in people's minds. Punctuation itself is fine, but forcing periods at the end of all messages isn't for that reason alone. If people really want it, it can be a toggle I suppose, which I'm still working on (pref code is alien-like). But personally this is detrimental in imagining how certain people's attitudes are like and their overall tones, because nobody speaks in the same manner.

**Comment by Crossedfall** [comment]
When you read a book does every character have the same voice and tone regardless of how they've been built up or the context surrounding the discussion?

**Comment by itsmeow** [comment]
I do think that some of the ways people talk can't be conveyed if there is automatically a period inserted at the end of every message. for example, if somebody were to split their message into multiple separate statements and having punctuation inserted in between, those might mess with their pacing or tone a little bit

**Comment by PowerfulBacon** [comment]
I am also against this, I have seen videos on Goon and it looks awful since 90% of players don't care about adding punctuation themselves.

**Pull request closed without merging**
