### PR TITLE
Removes public autolathes, adds extra youtools and service lathes

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

* Removed public autolathes, they are now behind one set of doors.
* Rebalanced prices of youtools, and added two of them on each map
* New items for games vendor, to make up for the lack of autolathes
* Added service lathe to all maps

image
image
image
image
image
image
image

### Removed public autolathes, they are now behind one set of doors
Less greytide, stationwide. Tools require a little bit of money to obtain, are available in limited supply, and an ID. Das rite, I went there. 

### Rebalanced prices of youtools, and added two of them on each map
Rebalanced the prices of youtools, so that they are more affordable to medics and assistants.
Added a couple on each map to make up for the lack of tools on each map. The removal of autolathes will be a drastic change that will have a large impact on the game. This change will somewhat mitigate that impact.

### New items and prices for some vendors, to make up for the lack of autolathes
Added spray cans, recorders and cameras to fun vendors.
Added basic parts to Vendomats across the station, to substitute the lack of basic parts.

### Added service lathe to all maps
Service needs a lot of items from lathe (glasses, beakers, botany tools). The lack of public lathes may impact service the most. This is a solution.
This PR will also change the meta against heretic's favor, which are already a shitty antag.

## Changelog
:cl:
refactor: Removed public autolathes, they are now behind one set of doors.
add: Rebalanced prices of youtools, and added two of them on each map
add: New items and prices for some vendors, to make up for the lack of autolathes
add: Added service lathe to all maps
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
this is fucking stupid, why so people hate public lathes so much? is riding really such a big fucking issue that requires removing every almost single roles access to autolathes

**Comment by yorii** [comment]
Why would you even consider doing this PR... it's a complete waste of time.

People will just move it out into a public hallway every single round for weeks until someone reverts the change.

**Comment by ivanmixo** [comment]
Just encouraging tiders to break in to the engi/sci lathe for tools, there is no point to this.

**Comment by USB3pt0** [comment]
What you think will happen:
Tiding will be stemmed or stopped

What will actually happen:
Tiders throw spears at airlocks and windows to break in to lathes or tool storage, or print an autolathe board at a protolathe and convert the public garden biogenerator into an autolathe.

Absolutely pointless.

**Comment by githubuser4141** [comment]
> What you think will happen:
> Tiding will be stemmed or stopped
> 
> What will actually happen:
> Tiders throw spears at airlocks and windows to break in to lathes or tool storage, or print an autolathe board at a protolathe and convert the public garden biogenerator into an autolathe.
> 
> Absolutely pointless.

I'm not a contrib/maintainer, but should tiders really be making spears and B&E'ing into departments to powergame tools on MRP? Sounds like they should be told off by the admins imo.

**Comment by PowerfulBacon** [comment]
The science positions are bad they shouldnt be where the tables are meant to be, it looks weird

**Comment by mudzbe** [comment]
> Das rite, I went there.

Cringe

My PR was not motivated to remove greytide. I was meming about kneecapping assistants but idc, I think you’re all reading too much into that. My PR was motivated to balance the economy. I added a new system to make the economy more robust, people could still greytide they just had to do at least one thing of value for the station like complete a bounty or possibly RP for the tools. This may seem ironic or hypocritical but to me the this just seems purely anti-fun and uncalled for.

**Comment by Sinestia** [comment]
It's fine if players bring the lathes out, still better if a player is doing it willingly


 This doesn't really change much but the original shouldn't have been merged

**Comment by eeSPee** [comment]
> The science positions are bad they shouldnt be where the tables are meant to be, it looks weird

Would they be better of in the hallway? Or laboratory?

**Comment by eeSPee** [comment]
> My PR was not motivated to remove greytide. I was meming about kneecapping assistants but idc, I think you’re all reading too much into that. My PR was motivated to balance the economy. I added a new system to make the economy more robust, people could still greytide they just had to do at least one thing of value for the station like complete a bounty or possibly RP for the tools. This may seem ironic or hypocritical but to me the this just seems purely anti-fun and uncalled for.

But YouTools are already the machine that exchanges money for tools.

Having autolathe require money to operate is just obsolete, since this solution already exists.

**Comment by eeSPee** [comment]
image
image
image

I removed the lathe windows.

**Comment by francinum** [comment]
The only lathe that really needs to exist roundstart is Cargo's, as science is capable of producing it's own, along with engineering.

Why are the youtools not in tool storage?

Why does the vendomat have massive stocks of stock parts?

**Comment by heepox** [comment]
I remember when we had no public autolathes... greytide was every round every time just to get tools, but everyone else who just wanted spraycans could not get them without doing the same thus encouraging greytide.

**Comment by eeSPee** [comment]
> The only lathe that really needs to exist roundstart is Cargo's, as science is capable of producing it's own, along with engineering.

I'm pretty sure science still uses its autolathe to print tools.
Service uses its autolathe for anything including kitchen supplies, glasses, janitor and botany tools.

> Why are the youtools not in tool storage?

To compensate for the removed autolathes from the specific departments.
 
> Why does the vendomat have massive stocks of stock parts?

The public autolathe were also a easy way to obtain stock parts for basic machines.

This change is to compensate for the public availability of stock parts. A machine uses on average 2 parts, so anything under 10 would not be enough,

**Comment by Knuff-les** [comment]
What about detectives that need more ammo? This feels like one of those /tg/ changes to “stop tiding” that just end up bringing more tedium to the game and never actually fix the “problem” in the first place.

**Comment by eeSPee** [comment]
I should close this since autolathe removal isn't happening.

**Comment by bloons3** [comment]
@eeSPee Weak

**Comment by eeSPee** [comment]
> @eeSPee Weak

Sorry, this PR only got 10 dislikes.

Needs 11 for speedmerge :S

**Pull request closed without merging**
