### PR TITLE
Adds more emojis

### PR DESCRIPTION
**Pull request by CydiaLamiales**
## About The Pull Request
Seeing how Kat's adding an app that allows you to select emojis for texting in her PDA replacement PR https://github.com/BeeStation/BeeStation-Hornet/pull/7550 I thought it'd be neat to add a couple more of them, specifically for roundstart races. So I ~~painstakingly handcrafted~~ quickly stitched them together using in-game assets and images from the wiki.

## Why It's Good For The Game
More emotes is nice.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

emotes_test

</details>

## Changelog
:cl:
add: Adds 9 new emojis
fix: Centers the green face emojis
/:cl:

### CODE REVIEW

**Review by ike709 — DISMISSED** [review]

**Comment by itsmeow** [comment]
~~grod when~~

**Review by Crossedfall — DISMISSED** [review]
Looks good to me. Update the emote list on the wiki and I'll merge.

https://wiki.beestation13.com/view/Emoji_cheat_sheet

**Comment by CydiaLamiales** [comment]
Did that. To be honest, I didn't even know we had an emoji page on the wiki.

**Comment by itsmeow** [comment]
While you're touching emojis, can you fix the uncentered green face icons?

These ones
image

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
