### PR TITLE
Slight refactor to an emp event

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
title

## Why It's Good For The Game
code looks cleaner

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
refactor: refactored emp effect
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
what if severity is 0

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
> what if severity is 0

Emp severity can only be 1 or 2, where 1 is heavy and 2 is light.

**Comment by PowerfulBacon** [comment]
Got to enforce the testing stuff lest we slowly have it phase out

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
PR body is incomplete, testing procedure is not an optional section. (It is enforced on even small PRs, as code that the changes depend on may not even work in teh first place leading to a fix not actually fixing something)

**Pull request closed without merging**
