### PR TITLE
Reorders the items and weapons dmi

### PR DESCRIPTION
**Pull request by Cenrus**
reorder of dmi files. items_and_weapons.dmi was a clutter of unorganized sprites.

Reorders the items and weapons dmi and moves some of them in new icon files.

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Port?

**Comment by Cenrus** [comment]
Yes, I forgot the link again. https://github.com/tgstation/tgstation/pull/45128

**Comment by qwertyquerty** [comment]
Possible issues, will address when I can

**Comment by ike709** [comment]
@qwertyquerty ?

**Comment by ike709** [comment]
@qwertyquerty

**Comment by qwertyquerty** [comment]
It likely has icons we don't have and doesn't have icons we do have.

**Comment by ike709** [comment]
So just... compare the files in icondiffbot?

Regardless, this conflicts now @Cenrus

**Comment by Cenrus** [comment]
Will fix the conflicts later.

**Pull request closed without merging**
