### PR TITLE
Fixes the default zone_selected from null to the chest

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

title

## Why It's Good For The Game

You can now do surgery and hug people with the roundstart intent. It really should not have been set to null.

## Changelog
:cl:
fix: You now actually target the chest roundstart
/:cl:

### CODE REVIEW

**Comment by eeSPee** [comment]
Epic.

**Comment by PowerfulBacon** [comment]
Since it is only a 1 line change, I'd prefere if there was only 1 line changed rather than 10

**Comment by ike709** [comment]
@PowerfulBacon Whitespace trimming is automatic and also fine.

**Comment by ivanmixo** [comment]
Yeah I tried to fix it, but whenever I pressed revert change on an empty line it just made a new change on another empty line.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
