### PR TITLE
Area lighting colours

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Allows different areas to have different lighting colours attatched to them, allowing you to set the tone/mood of specific areas.

Medical has a clean light blueish feel white engineering uses warm, industrial light colours.

image

image

image

image

image

image

## Changelog
:cl:
add: Areas can be set to have different lighting colours
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
what about perfomance impacts?

**Comment by ike709** [comment]
@BeloneX there are none

**Comment by ike709** [comment]
You need to handle this when the light is powered on, in case a light tube is moved to a new area or a broken tube is replaced.

**Comment by PowerfulBacon** [comment]
oh I totally forgot about this let me make the changes

**Comment by PowerfulBacon** [comment]
@ike709 This sets the colour of the frame itself, so taking out the tube and moving it to a different area shouldn't be an issue, just testing this now.

**Comment by PowerfulBacon** [comment]
Yea just tested it, moving a light tube to another light doesn't change the colour and light constructs are a different type so its fine

**Comment by Crossedfall** [comment]
I thought @qwertyquerty already had something like this built into it? 🤔

**Comment by qwertyquerty** [comment]
Planned but never implemented

**Pull request merged**
