### PR TITLE
Gender pay gap

### PR DESCRIPTION
**Pull request by Pill-U**
## About The Pull Request
Ports the gender wage gap from hippie 
https://github.com/HippieStation/HippieStation/pull/12476

## Why It's Good For The Game
1.Men take more damage from groinkicking, so they should have an advantage too.
2.Realism.
3.Women aren't real.
Next step: Race pay gap.

## Changelog
:cl:
add: Wage gap
/:cl:

### CODE REVIEW

**Comment by nikk735** [comment]
dont add ur politics to a 2d space man game no one cares

**Comment by ike709** [comment]
There are no girls on the internet.

**Comment by nikk735** [comment]
based ike

**Comment by Pill-U** [comment]
ok. remove females then?

**Comment by TeomanTheGreat** [comment]
wtf ike,,,,,, this was the most based pr ever why close it?

**Pull request closed without merging**
