### PR TITLE
Ports emote keybindings

### PR DESCRIPTION
**Pull request by Tsar-Salat**
## About The Pull Request

This PR ports emote keybindings, allowing users to edit their preferences to make a keypress associated with an emote.

As a consequence, emotes now follow a standardized cooldown, with audio emotes having their own separate cooldown. Specific emotes can have this cooldown lengthened through redefining the var.

Includes several fixes for audio emotes as well.

Ports:
- https://github.com/tgstation/tgstation/pull/47750
- https://github.com/tgstation/tgstation/pull/47868
- https://github.com/tgstation/tgstation/pull/53430
- https://github.com/tgstation/tgstation/pull/59479
- https://github.com/tgstation/tgstation/pull/62206 
- https://github.com/tgstation/tgstation/pull/68954
- https://github.com/tgstation/tgstation/pull/86846
- https://github.com/tgstation/tgstation/pull/87210

## Why It's Good For The Game

With the addition of the TGUI emote menu, I don't really think theres anything stopping us from adding keybindings for emotes. The menu allows for just as quick access to the emotes, this PR should assist people who use the emotes regularly.

The cooldowns are focused more on audio emotes than emotes in general, and I was a *lot* more generous with the length on them than TG was. My intention is just to limit excessive audio spam within the span of a few seconds. I would be open to further cooldown changes if others think it is too short.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/user-attachments/assets/f90ee220-f788-441b-8d2c-ae27732a9cca

</details>

## Changelog
:cl: rkz, ninjanomnom, ModDownloading, Mothblocks, IndieanaJones, Timothymtorres, Ghommie, grungussus
add: Emotes can now be bound to keybindings
tweak: emotes now have a set amount (5) you can do before that emote is on cooldown
tweak: audio emotes besides scream will no longer pierce walls
tweak: *me custom emotes are no longer forced lowercase
tweak: jump emote now costs minor stamina
tweak: lowered cost of stamina from F jumping
/:cl:

### CODE REVIEW

**Comment by Rukofamicom** [comment]
A suggestion and some thoughts regarding emote spam in general - I have not looked at the code itself yet, just leaving my thoughts in a place you can see them when you're not as busy. 

---

When it comes to emote spam, there are real cases where players may want to use emotes in rapid succession with good reasoning, just like there are cases where it would be bad, I wanted to suggest a moderately complex but immersive logic for them that divides emotes into three categories:
* Sound emotes
* Visual emotes (spinning/flipping)
* Purely flavor emotes with nothing except text above the user's head

---

A simple cooldown on these is good to prevent stacking of sounds, but certain emotes like coughing and sneezing (when it eventually gets a sound) should be possible to use a few times in a row before going on cooldown. What I'd suggest is adding a variable that increments each time an emote is used within a cooldown period, reseting the cooldown timer. If you reach the limit then it goes on cooldown for the full duration.

As an example, say sound emotes hypothetically have a 20 second cooldown:
* Farting is set to 1 use per cooldown period, so if you fart you are locked out of farting again until the sound timer resets
* Coughing is set to 3 uses per cooldown period, so you could cough, and if you try to again before the 20 seconds is up, the cooldown timer resets to 20 and your sound emote count climbs to 2. You can cough a third time, and cooldown resets to 20 but you are unable to cough again until 20 seconds have passed. 

In that same example, with the cooldown shared among all sound emotes, if you cough, you will be unable to fart for 20 seconds because your "sound emote" count is already set to 1. You can set the more disruptive emotes to lower limits and the less disruptive ones to higher limits. 

---

As for motion emotes, I'm only especially familar with spin and flip, but these are emotes very prone to spamming. Rather than enforcing a strict cooldown on these emotes I think they should cause stacks of dizziness with a chance to fail based on the user's dizziness, resulting in a hardstun, brain damage and head injury if failed. Doing a spin-flip or rapidly spinning will just result in hurting yourself which is more immersive than a cooldown. 

The catch here is that it needs to affect non-carbons too - they can't have head injuries but they can still take damage in general if they fail such a check. 

---

Text emote really only need a simple 0.5-2 second cooldown since they're not nearly as disruptive as others and players rarely have a chance to spam them.

**Comment by llol111** [comment]
Already said these oppinions in admin channels, but ill say them here for coders and such.
Some sort of code side spam prevention is definitely a good thing, i approve.

Im not to particular on how its done in detail, anything that prevents [emote]x79! in 2 seconds from happening is cool with me.
my personal choice would still be a system like TF2 has for MEDIC!! spam, if i remember that right - you can spam it *a little bit* but if you go nuts it applys the spam prevention to you.
Like i said though, i dont mind to much aslong as spam is prevented at the end of the day.

**Comment by ClownMoff** [comment]
>>tweak: jump emote now costs minor stamina

We can't have ANYTHING

**Comment by ClownMoff** [comment]
How's the sound emote cooldown? How many *scream can I make in a row?

**Comment by Rukofamicom** [comment]
> How's the sound emote cooldown? How many *scream can I make in a row?

One, ideally. 
Players spamming scream and jump are part of the reason the limit is necessary.

**Comment by Tsar-Salat** [comment]
> How many *scream can I make in a row?

What do you think a cooldown is

**Comment by ClownMoff** [comment]
> > How's the sound emote cooldown? How many *scream can I make in a row?
> 
> One, ideally. Players spamming scream and jump are part of the reason the limit is necessary.

You shouldn't limit the players to a single scream or emote, somtimes I like screaming several times in a row to express a bad reaction, this is literally

image

**Comment by ClownMoff** [comment]
I think the sound emotes should use either the same or a very similar system like the chat spam limit does, it allows you to be able to do *scream a couple of times which is pretty fun but it doesn't allow you to continue it as long as you want

**Comment by PowerfulBacon** [comment]
This cooldown system seems perfectly fine and works as I have previously requested. I see no reason for a cooldown system to need to be anything more than a simple time since last emote.

**Comment by Rukofamicom** [comment]
> Alright this is just irritating. Ruko is just going off without actually having read what the code is, and other players are coming in with big reaction images to it.

I will refrain from leaving general ideas/input unless I am doing a full code review in the future. I've hidden the original comment as outdated.

**Comment by ClownMoff** [comment]
> I see no reason for a cooldown system to need to be anything more than a simple time since last emote.

I don't really sea a reason to put a cooldown on something like this. Being able to do a sound emote a couple times in a row it's a form of expression that is used, I don't see why add a 2.5 cooldown, maybe I do want to clap 2 times in a row. In fact I find kind of amusing to do the *clap emote a couple times in a row since the overlap of sounds adds to the comedic timing. And now I won't be able to do it because..... 🤷????, I really am agaisnt this system

**Review by PowerfulBacon — APPROVED** [review]
The amount of bloat this adds to the control preferences is ridiculous, but I guess its fine for now

**Comment by Tsar-Salat** [comment]
A 1 line code comment was apparentely too much for the git autoresolver, and caused the queue to fail. Im calling it a git moment and invoking the maint policy

**Pull request merged**
