### PR TITLE
Fix headmin not being able to ban 3 admins

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

The check that was originally there is broken, this fixes said check.

## Why It's Good For The Game

Headmins should be able to ban more than 1 admin.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Tested as local debug user which has R_EVERYTHING and can edit all perms

image

</details>

## Changelog
:cl:
fix: Headmins can now ban more than 1 admin.
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
Since you're here, would you make the bancount include when the ban is sourced by themselves? (Self-ban)

**Comment by itsmeow** [comment]
It is? it's shown in the screenshot me banning myself

**Comment by itsmeow** [comment]
oh excluded

**Comment by itsmeow** [comment]
Ehhh too complex, since bans can be based on key, ids, cids etc i don't wanna do that in this pr

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
