### PR TITLE
Adds a extra check to running into walls

### PR DESCRIPTION
**Pull request by thelaughingbomb**
## About The Pull Request

This PR adds a extra check to make sure you are actually standing
## Why It's Good For The Game

If you become confused someone can just shove you indefinitely into a wall which stun locks you until you fall into crit. Sure you can just go into walk mode but people dont consider that in combat. Now to actually run into a wall you have to be standing.

## Changelog
:cl:
tweak: Wall slamming now checks if you are standing
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — APPROVED** [review]
Putting to vote

**Comment by Archanial** [comment]
lube nerf oh shit

**Comment by thelaughingbomb** [comment]
Its more to stop instantly dying as you can shove confused people who are laying down, into walls and have them die fairly easily with no effort.

**Comment by Archanial** [comment]
> 
> 
> Its more to stop instantly dying as you can shove confused people who are laying down, into walls and have them die fairly easily with no effort.

no it's time to nerf confusion. Noone likes that mechanic and it's hard to know when it stops. 
Instead it should be reduced to like 3-4 bumps.

**Comment by FortSumter** [comment]
Can we expand this to the xenos as well? When the queen dies, the larva xenos just kill themselves by constantly running into a wall.

**Pull request merged**
