### PR TITLE
Burn and brute patch balance

### PR DESCRIPTION
**Pull request by Sinmero**
## About The Pull Request

Styptic Powder and Silver Sulfadiazine are probably the most powerfull and broken chems that are easily obtainable in the game atm. 
When in your bloodstream they heal for 2 brute/burn damage per tick just like Kelotane/Bicaridine.
And you can have unlimited amount of Styptic Powder/Silver Sulfadiazine in you!
Those chems are accessible roundstart and now with chem factories it makes it even easier to abuse them.

List of changes:

Styptic Powder and Silver Sulfadiazine now have overdose threshold at 40u.
When overdosed the reagent will not heal you passively while in bloodsteam.
Reagent will not heal on touch if total reagent volume in bloodstream is greater than 40. (Note that it will still apply touch healing you if you are overdosing but the volume is less that 40)
If you have more than 50u of reagent in you it will do minor toxin damage untill there is less than 50u in your bloodstream.

Brute/burn patches are still powerfull healing items, you can safely apply two patches in a row and overdose process is mostly safe by itself (if you dont chug it like madman).
You cant have 1000u of Styptic Powder and Silver Sulfadiazine in you and heal for the whole round.

## Why It's Good For The Game

Compared to other chems Styptic Powder and Silver Sulfadiazine are more balanced now.

## Changelog
:cl:
balance: Added overdose to Styptic Powder.
balance: Added overdose to Silver Sulfadiazine.
/:cl:

### CODE REVIEW

**Comment by Sinmero** [comment]
Red text makes me sad

**Comment by ike709** [comment]
This red text isn't your fault.

**Comment by Isy232** [comment]
A 40u Styptic Powder patch will heal you for 40 (instant) + 200 (over time) brute damage.
This PR does not change that.

I like your effort here, but I think it would be better just to entirely remove the over time healing component or drop its healing down to 0.5 per tick.

As it is now idiots are just going to OD themselves on brute patches. Styptic is a good noob chem that is hard to go wrong with, its far too powerful thought and should just be a better bruise pack in my opinion.

**Comment by Mick1299** [comment]
Removing the heal over time would just makes them shitty versions of synthflesh. Reduce their heal over time from 5 to 1 or 2 a tick alongside the OD thresholds would reduce their effectiveness without completely killing their viability.

**Comment by Sinmero** [comment]
People dont like nerfs so if i reduce the healing values it wont pass the vote.
I think that current changes are soft enough not to affect most people but will prevent the abuse.
Well if i was to reduce the healing i would have changed the tick healing from 2 to 1 or half the touch healing or both.

**Comment by ike709** [comment]
image

Vote is split and as a medical main I think this is a good change, so I say it passes.

**Comment by ike709** [comment]
Also the reason we can't nerf it further is that there will be riots.

**Comment by ike709** [comment]
Also I took care of the wiki changes.

**Pull request merged**
