### PR TITLE
Makes implants Medbay exclusive

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
Removes implants from being printable in Exosuit Fabricators and removes surgical tools from being printable at the Science techfab. Removes Robotics surgery room/corner. Replaces the Robotics R&D console with a production console same as Construction has.

To compensate for their removal, I've given Robotics a 25% chance to spawn with a working T1 Ripley MK1 to hopefully encourage fellow Roboticists to play around with mechs more.

TODO

- [ ] Decrease implant tier unlock by one.
- [ ] Decrease implant material cost by 25 to 50%.

I am only doing Corg until I get to hear what people think of this possibly controversial change. 

## Why It's Good For The Game
Roboticists are a jack-of-all-traits. Being capable of making general machines, mechs, bots, cyborgs and handling the AI (without an RD) in addition to doing basic surgery and implanting powerful implants. All while avoiding being bwoinked by an admin. Despite being a Roboticist enthusiast, I think they should be nerfed. This was the most elegant design solution I came up with.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image

image

image

image

image

</details>

## Changelog
:cl:
balance: Implants are now Medbay exclusive.
balance: [Corg] Surgical tools are no longer found in Robotics nor printable in Science.
balance: [Corg] Replaces R&D console with a production console same as Construction has.
del: [Corg] Removed Robotics surgery room/corner.
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
I dislike the removal of surgery, robotics kind of needs to do borgification

**Comment by MarkusLarsson421** [comment]
> I dislike the removal of surgery, robotics kind of needs to do borgification

They can get assistance from Medbay. Both departments can still print MMIs.

**Comment by Tsar-Salat** [comment]
This is pretty weak. You removed a good 50% of their job and Roboticists get a token "here's a mech neither mining, engineering, or medical will want." and only a 25% of the time?

That's nonsensical. If you want to commit to making Roboticists mech builders and cyborgs you should actually commit to it. Here's a few ideas.

1. Give Roboticists starting mech structures in the same way they have starting cyborg structures. 
2. Remove the wall between robo proper and the mech recharge bay.
3. If robo and medical are supposed to be communicating directly, why did you choose the map to try this on where they are FURTHEST from each other? Chem & Botany on Boxstation is an example where they have synergy and are right next to each other.

**Comment by MarkusLarsson421** [comment]
> here's a mech neither mining, engineering, or medical will want.

It's typically because they don't know how good they are. They may use the mech for 10 seconds and feel it is extremely slow on the station side. 

As Huk said.

image

image

> Remove the wall between robo proper and the mech recharge bay.

I like the separation, and it allows mech users not associated with Robotics to come charge their mech there. I sometimes even leave a mech there locked to their department with the shutters wide open.

> If robo and medical are supposed to be communicating directly, why did you choose the map to try this on where they are FURTHEST from each other? Chem & Botany on Boxstation is an example where they have synergy and are right next to each other.

I'm not going to change a whole map to make it ideal for this situation, I mostly did Corg first because I had already opened the map. Robotics is rarely in an ideal location and that shouldn't be a requirement to whether this is a good change or not. Look at Box or Delta Station with Mining being 10 miles away from Robotics. Enjoy walking with a Firefighter Ripley through that normal pressurized hallway. 

> If you want to stick with this whole "robo needs to talk to surgery" bit, you need to change medbay as well to be better at receiving.

What do you mean by "receiving"?

**Comment by MarkusLarsson421** [comment]
I forgot to also make two changes where implants are somewhat cheaper to print and also researched a tier earlier in the tech tree. Gonna update this once I'm back from work.

**Comment by MarkusLarsson421** [comment]
Generally, I think the average player are not used to mechs and think they should be more widely used and encouraged so that people will get used to their presence and not too surprised when there is a hostile mech piloted by an experienced mech user.

Not many people knows how to fight hostiles mechs.

**Comment by MarkusLarsson421** [comment]
> Cool. Doesn't apply. You said mk1 mech. People don't take Ripley's, they take Firefighters.

Firefighter is not that slow on Lavaland. It's the station atmosphere which makes them slow.

> Robotics is now reliant on help from medical surgery.

Aah, I understand now. Well, what is wrong with being dependent on another department?

**Comment by Tsar-Salat** [comment]
> Firefighter is not that slow on Lavaland. It's the station atmosphere which makes them slow.

This is completely not what I was saying. I said mk1 Ripley's are shit and no one is going to want it. You then post about mining mechs and Huk's spiel in support of mining mechs. That spiel however, was about *firefighters* not the mk1 Ripley mech. It has *zero* relevance to our conversation. Ripley's and Firefighters are different and at no point did I say Firefighters are bad on lava land or discuss the traits of firefighter mechs. I have no idea why you are defending firefighters here.



> Aah, I understand now. Well, what is wrong with being dependent on another department?

Restating this for the third time. The main point of this pr is the moving of surgical MMI/borgification so that robo is dependent on medical, no? I'm specifically pointing out you have made no changes to facilitate that exchange in a better way.

The first time I said this, you said something to the effect that it was out of scope. It is not, this is the entire focal point of this pr. The second time I said this, you made it seem like I was arguing "well what is wrong with them working together?" Implying that I take an issue with that. I do not.

**Comment by Gilgaxx** [comment]
IMO, roboticists shouldn't be given more incentives to make mechs without a mech rework. I don't think mechs are in that healthy of a state for the server.
If you just want to increase inter-departmental interactivity of roboticists, why not make mechs require help from engineering, for example? Maybe make the boards for them printable only at the engineering circuit imprinter?

**Comment by PowerfulBacon** [comment]
I don't see what's wrong with robotics doing borging surgery, augments and implants. Medbay does medical surgerys, while robotics handles the scientific ones.

**Comment by Okram0** [comment]
I can no longer easily create a horrific combination between a moth and a lizard using surgery tools as scientist, thumbs down

**Comment by MarkusLarsson421** [comment]
> I can no longer easily create a horrific combination between a moth and a lizard using surgery tools as scientist, thumbs down

Yes you can, just go Medical Doctor and ask for the parts from Robotics.

**Comment by DarnTheMarn** [comment]
It should be the other way around imo. Basic replacement organs at medbay only, the cool implants and upgraded organs at robotics. They don't have a lot to do in robotics. Sure you can make a RIPLEY and put a RCD on it or a plasma cutter on it, but at that point you should have become an engineer or a miner if thats what you're going to do.

**Comment by PowerfulBacon** [comment]
I think this just takes too much away from the roboticists, who are intended to be the ones dealing with implants. Without implants, they have too little content especially with how restricted the production of mechs are. I don't think this PR will be merged in this state, so closing. 🔑 🔑 🔑

**Pull request closed without merging**
