### PR TITLE
Removes the teratoma changeling power

### PR DESCRIPTION
**Pull request by WhyIsCaeciliusTaken**
## About The Pull Request

Removes the teratoma changeling power. The random maint ones still exist.

## Why It's Good For The Game

It's an obnoxious ability that results in dozens of annoying, spammed monkeys with the explicit purpose to grief, yet doesn't give them an antag datum, resulting in them getting unfairly banned whenever they get DNA stung by a changeling (This has happened before just today where a player got permabanned wrongly because of this).

## Changelog
:cl:
del: Removed teratoma ling ability
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
I agree.

**Comment by SpinnerMaster** [comment]
i ded

**Comment by Archanial** [comment]
DNA sting is logged though

**Comment by ItsTisme** [comment]
Wait teratoma isant meant to grief? I thought that was the whole point make sec deal witht hem while ling does other stuff

**Comment by qwertyquerty** [comment]
Just give them an antag datum dude

**Comment by ghost** [comment]
Beestation: “We are better than tg we don’t remove stuff like orange man”

Also Beestation:

**Comment by ghost** [comment]
> Beestation: “We are better than tg we don’t remove stuff like orange man”
> 
> Also Beestation:

Then tell us how to fix a shitty role, go on i'm waiting for your answer, this is a administrative issue.
Also the only people that ever claimed that are redditors, so go figure.

**Pull request closed without merging**
