### PR TITLE
Strange seeds are now lavaland-only resource

### PR DESCRIPTION
**Pull request by Goshagosha**
## About The Pull Request

Added structure 'strange plant' to lavaland\ash_flora
Strange seeds removed from biogenerator designs
Strange plant icon in 4 duplicates added to ash_flora.dmi. It's slightly edited hydroponics strange plant icon.
Strange seed is removed from Biogenerator designs, you can no longer print it there.
Strange plant added to lavaland mapgen flora pool. It emits weak light, and has a glowing halo, to be spotted easily.
On harvest it produces 1-2 fruits, which can be used by botany as per usual.
Also, unlike other ash flora, the original plant is destroyed on harvest.

## Why It's Good For The Game

~~Because I hate fun~~
It makes strange plants more unique, and less of a "grind through 300 seeds and make WMD under 60 minutes". It levels out botany with other departments, as in, it finally nerfes it.
Finding a strange plant with a flight potion or umt will now be 1 in 20 shifts experience, at best.
'Botany made plasmaflood bombs' will be a unique ~~fun~~ event, instead of a regular headache for command, security, and admins.

https://user-images.githubusercontent.com/33848913/130841903-d3daf24e-3c30-4e37-945a-2b01dab79b9d.mp4

## Changelog
:cl:
add: Added structure (plant) 'Strange plant' to code/modules/mining/lavaland/ash_flora.dm
add: Added boolean flag destroy_on_harvest (FALSE) to plants in ash_flora. If it is on, plants will not regrow.
del: Strange seeds removed from biogenerator
imageadd: xpod[1-4] added to icons/obj/lavaland/ash_flora.dmi (2,3,4 are placeholders for better art variety)
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I actually really like this idea. Biggest problem will be botanists having a way to get to lavaland though.

**Comment by AnCopper** [comment]
> I actually really like this idea. Biggest problem will be botanists having a way to get to lavaland though.

They'll have to cooperate with Miners or Explorers, this is a good way to pressure inter-department work.

On Pubby they can use the pubby shuttle to get there.

**Comment by Goshagosha** [comment]
> Biggest problem will be botanists having a way to get to lavaland though.

I know we all like strange seeds, but let's be honest, they are absolutely not critical for botany to function. Meaning - if something happens to mining, botany will still have something to do.
We have far more critical departments than mining sometimes unstuffed: science, engineering, and the crew still manages.

**Comment by PowerfulBacon** [comment]
True that and they can get it from cargo too

**Comment by EvilDragonfiend** [comment]
I like this idea to make them be cooperative with other departments.
To have this, since you nurfed the drop chance of Strange Seeds significantly, I believe you should buff the RNG reagent chance.

Current Strange Seed RNG is
 - 60% Chance to get 1~3 reagents. (60% chance 0, 20% chance 1, 20% chance 2, 20% chance 3.)
 - 50% Chance to get 1~2 traits (I really don't care about this. gas is not my favorite.)

What I concern about is the reagent part.

My chance suggestion is
 - 100% chacne to get 1 basic reagent. (like water, hydrogene)
 - 100% chance to get 1 random reagent.
 - 80% chance to get 1 random reagent.
 - 60% chance to get 1 random reagent.
 - 40% chance to get 1 random reagent.
 - 20% chance to get 1 random reagent.

You might think this is high, but nope. even if botanists make them seeds, you just get a lot of seeds from them, not get each of randomized seeds from the output.

**Comment by ivanmixo** [comment]
I disagree. Even having the chance of getting infinite traitor chems is powerful enough, you don't need a higher chance to get it.

**Comment by Goshagosha** [comment]
> I disagree. Even having the chance of getting infinite traitor chems is powerful enough, you don't need a higher chance to get it.

I would say tator chems themselves are not that powerful,
but im gonna just implement long coming chem blacklist to strange seeds once I get home

**Comment by ivanmixo** [comment]
> > I disagree. Even having the chance of getting infinite traitor chems is powerful enough, you don't need a higher chance to get it.
> 
> I would say tator chems themselves are not that powerful,
> but im gonna just implement long coming chem blacklist to strange seeds once I get home

Was moreso referring to the comment above me. Your PR itself is fine.

**Comment by francinum** [comment]
The PR is fine and chances do not need to be adjusted along with this PR. I'd quite prefer they be proposed as a separate issue after this PR has been properly considered and merged.

One variable at a time, no need to overdo it.

**Comment by ToasterBan** [comment]
this finally gives miners a reason to grab the plant bag in their locker lmao

**Comment by dwasint** [comment]
I like this idea and dislike it at the same time. I personally think spitting the strange seeds into 2 items is nicer on botanists basically the strange seed in the vendor has a limited pool of reagents that it can pull from and for the more potent ones think high end healing chemcials, high end explosives, and things like flight potions. This gives botany some freedom if they are understaffed or miners died early on but not as much as they currently have.

**Comment by Glcbitj** [comment]
Might as well remove the seeds, miners have 0 incentive to grab the and they almost always have shit reagents and traits, this will just kill Strange Seeds usage.

**Comment by ivanmixo** [comment]
Good.

**Review by qwertyquerty — APPROVED** [review]

**Pull request merged**
