### PR TITLE
Removes nothing

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Aight so I removed 4 zeroes. 4x0 is still 0, so I removed nothing

## Why It's Good For The Game

Here at Bee, we HATE our playerbase. 

## Changelog
:cl:
ballance: Debug uplinks start with 90 TC, instead of 9000TC
/:cl:

### CODE REVIEW

**Comment by ItsTisme** [comment]
Its a debug item, why do this? mechs cost more then 90 TC so it cant even do the job of debugging

**Comment by That0nePerson** [comment]
What autisem said. This is a debug item, you're unable to test some things with 90 tc.

**Comment by ToasterBan** [comment]
i know you only want to do this because of the Christmas tree, if you dont want it to be at the christmas tree REMOVE IT FROM THE DAMN TABLE

**Comment by zeskorion** [comment]
> i know you only want to do this because of the Christmas tree, if you dont want it to be at the christmas tree REMOVE IT FROM THE DAMN TABLE

It has no table


However christmas is over

**Comment by DatBoiTim** [comment]
> i know you only want to do this because of the Christmas tree, if you dont want it to be at the christmas tree REMOVE IT FROM THE DAMN TABLE

Honestly if you are lucky enough to get a debug uplink more power to you. But maybe there should be a policy that you do not get antag license.

**Comment by ItsTisme** [comment]
> > i know you only want to do this because of the Christmas tree, if you dont want it to be at the christmas tree REMOVE IT FROM THE DAMN TABLE
> 
> Honestly if you are lucky enough to get a debug uplink more power to you. But maybe there should be a policy that you do not get antag license.

That already is a thing, not sure what your saying here

**Comment by Socialistion** [comment]
hoes mad

**Comment by SaltyPenguin** [comment]
hoes mad

**Comment by PowerfulBacon** [comment]
This is a dumb PR, it's a debug item for a reason. It's not meant to be obtained. Its purpose is to debug, so therefore it has infinite credits the point of it isn't to be balanced or fair, its a debug item. Don't nerf the debug item, nerf the thing that supplies it.

**Pull request closed without merging**
