### PR TITLE
Autolathes can no longer print surgical tools

### PR DESCRIPTION
**Pull request by Dingo-Dongler**
## About The Pull Request

Removes the autolathe's ability to print surgical tools.

## Why It's Good For The Game

Public access to saws and scalpels is a bit much. I agree with the reasons stated in https://github.com/BeeStation/BeeStation-Hornet/issues/2011

## Changelog
:cl:
tweak: Autolathes can no longer print surgical tools.
/:cl:

### CODE REVIEW

**Comment by theXDkidoflol** [comment]
Wouldn't this also remove it from the protolathe? That seems like something fairly big to leave out, especially considering how on LRP at least, surgical tools go missing quite frequently.

**Comment by Pill-U** [comment]
> Wouldn't this also remove it from the protolathe? That seems like something fairly big to leave out, especially considering how on LRP at least, surgical tools go missing quite frequently.

I checked. Yes, yes it does.

**Comment by Dingo-Dongler** [comment]
whoopsie, that was not intended. I'll change that now.

**Comment by Isy232** [comment]
Agreed, public access to circular saws is a bit much and ghetto alternatives exist.

**Comment by WhyIsCaeciliusTaken** [comment]
Hmm yes today I will indirectly buff the cakehat

**Review by zeskorion — APPROVED** [review]

**Pull request merged**
