### PR TITLE
Departmental skirts : new sprites edition

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Adds jumpskirts as an alternative for jumpsuits.

Credit for the medical, engineering, science and security (excluding the sec officer one) sprites goes to: @Naevii 

This PR does not include the nukie skirts, as funny as the idea of them may be. 

Picture:

Also features snazzy new roboticist jumpsuits and envirosuits

Ports :

tgstation/tgstation#44776
tgstation/tgstation#44883
tgstation/tgstation#45244
tgstation/tgstation#53171

## Why It's Good For The Game

They look nice and it allows for more customization.

## Changelog
:cl: naevi
add: Departmental skirts
add: Preference to spawn with jumpsuit or jumpskirt
add: Labor camp is influenced by the prisoner's preferences of jumpsuit or jumpskirt
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
this wack PR again?

**Comment by r1ks-iwnl** [comment]
Oh boy it's time for round 3

**Comment by PowerfulBacon** [comment]
Entirely opinionated post here:
Captain - Yes, although the skirt is pretty ugly.
HOP - Again, somewhat of an ugly and lazy sprite.
CE / Engineer / Atmos - I am pretty meh on this one, they don't make too much sense from a practical standpoint, although then it is a game
RD / Sci - Yea, pretty cool
Robotics - Ugly sprite
Whatever is on the left, that top and bottom sprite is quite possibly the ugliest and flat looking sprite ever.
I assume the one under cap is a bartender skirt, and I think it looks quite nice and bartender is a job that makes sense to have skirts.
Chaplain one is fine
Chef one is fine.

**Comment by PowerfulBacon** [comment]
Also add the other sprites to the PR body for ease of access

**Comment by Naevii** [comment]
> Entirely opinionated post here:
> Captain - Yes, although the skirt is pretty ugly.
> HOP - Again, somewhat of an ugly and lazy sprite.
> CE / Engineer / Atmos - I am pretty meh on this one, they don't make too much sense from a practical standpoint, although then it is a game
> RD / Sci - Yea, pretty cool
> Robotics - Ugly sprite
> Whatever is on the left, that top and bottom sprite is quite possibly the ugliest and flat looking sprite ever.
> I assume the one under cap is a bartender skirt, and I think it looks quite nice and bartender is a job that makes sense to have skirts.
> Chaplain one is fine
> Chef one is fine.

I would resprite the rest but its quite a lot of work, and unless we know for sure they will get merged there is no point in doing that. 

All sprites except engi, sci and med, are sprites that were added to game previously. 

Reason engi, sci, med got resprite is because Azlan made uniform resprite and they didn't fit their jumpsuit equivalent.

I understand the complaint altho the complaint should go not for jumpskirts but for departamental jumpsuits in general. Most of them are ugly and outdated. 

And the jumpskirts dont differ much from the jumpsuits. Since they were created to fit jumpsuits.

**Comment by PowerfulBacon** [comment]
Could atomize the PR into departments to give it a higher chance of getting in. If 1 sprite is ugly it kind of kills the whole PR, so reducing the amount of sprites in a single PR would increase the likelihood of being accepted.

Opinion on updated sprites:
image

**Comment by Archanial** [comment]
That was denied before I think.

**Comment by ivanmixo** [comment]
> That was denied before I think.

It was voted for by the community, but the maintainers still removed them. Keep in mind it has been close to a year at this point.

**Comment by utilbird** [comment]
IMO. The atmos/engi skirts from the original PR looked a bit nice, the black stripes don't really fit well

**Comment by Naevii** [comment]
> IMO. The atmos/engi skirts from the original PR looked a bit nice, the black stripes don't really fit well

It got changed to fit new engi, atmos jumpsuits.

Old jumpskirts doesn't match the reworked suits anymore.

**Comment by OceanFish1** [comment]
Felinid mains are striking again oh god oh fuck

**Comment by Lagomorphica** [comment]
> Opinion on updated sprites:
> image

I have to agree with Bacon here that the Engineering skirts don't really make much sense. At least with other departments it isn't going to get caught in a piece of machinery and fucking kill you like bedhead hair. _It'd be funny if that was coded though._

It is a game though so I digress, but one thing that I will say is going to be weird is the prisoner skirt.

**_Why would you add a prisoner skirt._**

**Comment by ghost** [comment]
> > Opinion on updated sprites:
> > image
> 
> I have to agree with Bacon here that the Engineering skirts don't really make much sense. At least with other departments it isn't going to get caught in a piece of machinery and fucking kill you like bedhead hair. _It'd be funny if that was coded though._
> 
> It is a game though so I digress, but one thing that I will say is going to be weird is the prisoner skirt.
> 
> **_Why would you add a prisoner skirt._**

What's wrong with a prisoner jumpskirt? Are you that horny or something? I thought bee already has rules against ERP-ing

**Comment by Naevii** [comment]
> > Opinion on updated sprites:
> > image
> 
> I have to agree with Bacon here that the Engineering skirts don't really make much sense. At least with other departments it isn't going to get caught in a piece of machinery and fucking kill you like bedhead hair. _It'd be funny if that was coded though._
> 
> It is a game though so I digress, but one thing that I will say is going to be weird is the prisoner skirt.
> 
> **_Why would you add a prisoner skirt._**

It's almost like everything in this game makes perfect sense 🤔 because it's so reasonable that we have cult, clock cult, wizards, heresy, space dragons and ninja. That makes perfect sense. But we have to question skirts that are just variable of the suit.

**Comment by Effemu** [comment]
obraz

**Comment by PowerfulBacon** [comment]
> obraz

I haven't been there so cant confirm this myself, but there is no gravity on the ISS so they cannot wear skirts.

**Comment by Lagomorphica** [comment]
> It's almost like everything in this game makes perfect sense 🤔 because it's so reasonable that we have cult, clock cult, wizards, heresy, space dragons and ninja. That makes perfect sense. But we have to question skirts that are just variable of the suit.

I did say it was just a game. Would be funny if it had the bedhead interaction where it pulls you along conveyor belts or can get caught but thats a wyci.

> What's wrong with a prisoner jumpskirt? Are you that horny or something? I thought bee already has rules against ERP-ing

me when get arrested and the warden puts jumpskirt on me

😢

**Comment by super12pl** [comment]
> image

time to remove 90% of the game because irl astronauts dont do it

**Comment by ItsTisme** [comment]
space isant cold either, yet we use it to cool our super matter engines. aethestic cosmetic stuff should be fine in most cases unless the cosmatic item itself is ugly or REALLY doesnt fit. "it doesnt make sense" is kinda moot considering we  also have maid outfits and can rip off coworks tails to make a whip with it

**Comment by Effemu** [comment]
okay but why you need a skirt in 2d spessman game

**Comment by Archanial** [comment]
> okay but why you need a skirt in 2d spessman game

Because it's fetish content. 
Why do we need pet collar to be equipable?

**Comment by Effemu** [comment]
> 
> 
> > okay but why you need a skirt in 2d spessman game
> 
> Because it's fetish content.
> Why do we need pet collar to be equipable?

my exact thoughts

**Comment by yyzsong** [comment]
feet are a fetish dipshit
why *cant* we have skirts?

**Comment by Effemu** [comment]
> 
> 
> feet are a fetish dipshit
> why _cant_ we have skirts?

because feet have a purpose dipshit
skirts are just reskinned jumpsuits

**Comment by yyzsong** [comment]
Every jumpsuit is just a reskin of another jumpsuit dipshit
Gonna remove the nurse suit? Engineering hazard jumpsuit? Assistant formal jumpsuit?
Sec already has like six fucking jumpsuits in their vendor, what's another?

**Comment by WhyIsCaeciliusTaken** [comment]
Merge the ones that make practical and logical sense, toss the ones that don't:

Ones that make sense:
- Service Jobs
- Cargo Jobs
- Formal Uniforms of all kinds
- HoP
- RD

Ones that definitely don't:
- Engineering Jobs (because engi suits are supposed to protect against rads and engine heat)
- Sec jobs (because they give armour protection)
- Virologist and CMO (hmm yes let's expose my legs to a contact spreading lethal virus)
- Chemist (chemical spill protection)

Ones that could be argued either way:
- Prisoner (They have to work on lavaland after all)
- Scientist/Roboticist (Technically sci is supposed to give spill protection, but they don't actually work with chemicals)
- MD/Paramedic (They sometimes have to do surgery but the nurse outfit already exists, albeit mostly as a meme)

**Comment by Effemu** [comment]
> >Prisoner (They have to work on lavaland after all)
> >Scientist/Roboticist (Technically sci is supposed to give spill protection, but they don't actually work with chemicals)
> MD/Paramedic (They sometimes have to do surgery but the nurse outfit already exists, albeit mostly as a meme)

prisoners shouldnt ever get a skirt literally why would they
sci/robo have to work with oil, acid, electricity, bombs and bluespace so it doesnt make any sense for them to wear skirts
MD+Paramedics should go under **(hmm yes let's expose my legs to a contact spreading lethal virus)** and space aids transmitted by blood
cargo has to maintcrawl, sec has to fight

they only skirts you can argue make sense is formal stuff for command and maybe service (still dunno about chef maybe a really long one)

**Comment by Effemu** [comment]
> 
> 
> Every jumpsuit is just a reskin of another jumpsuit dipshit
> Gonna remove the nurse suit? Engineering hazard jumpsuit? Assistant formal jumpsuit?
> Sec already has like six fucking jumpsuits in their vendor, what's another?

why are you so combative when it comes to skirt (fetish) PR dipshit
do you really need them for erp that badly?

**Comment by PowerfulBacon** [comment]
are skirts fetish content? I kind of considered them normal for people to wear in society

**Comment by WhyIsCaeciliusTaken** [comment]
> prisoners shouldnt ever get a skirt literally why would they
> sci/robo have to work with oil, acid, electricity, bombs and bluespace so it doesnt make any sense for them to wear skirts
> MD+Paramedics should go under **(hmm yes let's expose my legs to a contact spreading lethal virus)** and space aids transmitted by blood
> cargo has to maintcrawl, sec has to fight
> 
> they only skirts you can argue make sense is formal stuff for command and maybe service (still dunno about chef maybe a really long one)

Cargo techs wear shorts already, wiring is something that requires hand rather than leg protection, scientists don't work with acid or oil, bluespace isn't a hazard when exposed to people (you can hold the crystals fine) and jumpsuits aren't going to protect from bombs either.

Also how is this fetish content? The problem with the PR is that 90% of these make absolutely no sense/don't fit the theme, not because "muh fetish content" as a catch-all "I don't like this in my spessman game".



> are skirts fetish content? I kind of considered them normal for people to wear in society

*Time to undermine my own viewpoint by making a joke about feet.*

**Comment by ToasterBan** [comment]
ss13 players explaining how clothing is fetish wear because women wear it

**Comment by super12pl** [comment]
ss13 players that have never seen a woman in their life explaining how skirts are fetish content

**Comment by ToasterBan** [comment]
women are a fetish

**Comment by ghost** [comment]
This level of customization is not worth the extra bytes in the rsc and code. They all look the exact same as their suit counterparts and have nothing unique about them besides "it's a skirt". Maybe if there were formal job uniforms for every role and skirts to go with them, I'd agree.

**Comment by WDebon** [comment]
Why do we need skirts we already have a fuck ton of clothing, besides why would you want to wear skirts on a space station

**Comment by Sylphily** [comment]
I would like to see this merged it gives some more department specific clothing, but the prison one makes do sense for obvious reasons, and the engineering one kinda don't make much sense either. But other than that I think it would be a good thing to add.

**Comment by francinum** [comment]
These look like shit.

**Comment by francinum** [comment]
🔑 


@qwertyquerty

**Comment by francinum** [comment]
Sure whatever.

Awaiting resprites for the more egregious ones.

**Comment by PowerfulBacon** [comment]
Atomise, atomise, atomise.
Keep the service skirts for a start (Not the mime one, that looks shit) and put them in vendors instead of in prefs.

**Comment by Minelol76** [comment]
Femboy pr

**Comment by imsynthex** [comment]
> Femboy pr

this tbh

**Comment by ToasterBan** [comment]
people talkin about the engi skirts ignoring the fact you used to be able to remove your shirt and keep all the bonuses

**Comment by Sylphily** [comment]
> people talkin about the engi skirts ignoring the fact you used to be able to remove your shirt and keep all the bonuses

That sound like a good idea to implement

**Comment by PowerfulBacon** [comment]
Stale

**Comment by ivanmixo** [comment]
Guess I'll ask for it to be reopened once I get the remaining sprites.

**Comment by ItsTisme** [comment]
>This PR does not include the nukie skirts

Wack

**Comment by utilbird** [comment]
lawyer blue is a bit too bright imo, not sure about the black stripes on the engi skirts either. Everything else looks good though!

**Comment by WhyIsCaeciliusTaken** [comment]
I am fine with these so long as the skirt versions of items like sec suit or viro suit lose their stat bonuses. You gotta pay with a gameplay disadvantage if you choose to wear a silly outfit.

**Comment by ivanmixo** [comment]
> I am fine with these so long as the skirt versions of items like sec suit or viro suit lose their stat bonuses. You gotta pay with a gameplay disadvantage if you choose to wear a silly outfit.

They do have a mechanical disadvantage, your legs are exposed. I don't see why the top part would get weaker just because it's a skirt.

**Comment by ToasterBan** [comment]
> I am fine with these so long as the skirt versions of items like sec suit or viro suit lose their stat bonuses. You gotta pay with a gameplay disadvantage if you choose to wear a silly outfit.

you can remove the top half of most outfits and still get 100% of their protection tho

**Comment by ivanmixo** [comment]
dreamseeker_Gc4wzOAH6w

The mime jumpsuit and jumpskirt sprites have been updated to not look absolutely horrible.

**Comment by ivanmixo** [comment]
Time to atomise this.

**Pull request closed without merging**
