### PR TITLE
Reformats lungs: check_breath()

### PR DESCRIPTION
**Pull request by Ohagi-Chan**
Adds the variable breath_depth, used in carbon/life: breathe() to multiply the depth of a breath (default is 0.5L).

Breaks most of check_breath() down into modular parts that can be overwritten by children of /organ/lungs.  This allows greater freedom to create lungs which can process gases in new ways, without re-writing the whole check_breath for every child.

## About The Pull Request
I've had an urge to design some quirkier lungs downstream that can work in much wilder ways than existing lungs.  The biggest inconvenience in doing so was that the check_breath() proc is so unwieldly and needed to be rewritten for every child of lungs.
With this change, children of lungs can define individual interactions with gases without rewriting the entirety of check_breath().

While I was at it, I also added a new integer that is used in /carbon/life to multiply the volume of a breath.  The default value is 1, so all existing lungs will still breathe in the same 0.5L they always have.  Changing this value can lead to lungs that breath and interact with more gas per breath, affecting relative minimums, maximums and scaling effects such as with Miasma.

## Why It's Good For The Game
Allows coders to add small differences to individual lungs' gas interactions, with less code.

## Changelog
:cl:
add: lungs can now have different breath volumes defined
refactor: parts of check_breath() are now modular.  it now calls a separate proc to handle each gas individually
/:cl:

### CODE REVIEW

**Comment by Ohagi-Chan** [comment]
Apologies.
I forgot to add @MrLostman as a co-author, for helping me work out the big gulp feature.

**Comment by Ohagi-Chan** [comment]
lol, wtf is this?
`[20:13:30]` Runtime in tables_racks.dm,40: undefined variable /mob/living/simple_animal/pet/hamster/vector/var/wear_suit

edit:
nah dog, that ain't me:
/obj/structure/table/Bumped(mob/living/carbon/human/H)`
	. = ..()
	**var/feetCover = (H.wear_suit && (H.wear_suit.body_parts_covered & FEET)) || (H.w_uniform && (H.w_uniform.body_parts_covered & FEET))**
	if(!istype(H) || H.shoes || feetCover || !(H.mobility_flags & MOBILITY_STAND) || HAS_TRAIT(H, TRAIT_PIERCEIMMUNE) || H.m_intent == MOVE_INTENT_WALK)
		return ..()

**Comment by Ohagi-Chan** [comment]
Any thoughts?

At all?

**Comment by qwertyquerty** [comment]
This is kind of a dumb and unorganized method of doing this in my opinion

**Comment by Ohagi-Chan** [comment]
> This is kind of a dumb and unorganized method of doing this in my opinion

I've copied the organisation, as it was before my pr, fairly closely.  How things are arranged is mostly not my fault.

Keeping in mind that my goal is to have all the gases handled individually, rather than one after another in a single, very long proc: how would you like me to do this differently?

**Comment by PowerfulBacon** [comment]
Personally I prefer having it in procs to be more organised, however, it adds more proc overhead and I don't really think it's worth the increased readability since the comments can handle this pretty effectively anyway.

**Pull request closed without merging**
