### PR TITLE
Updates three Lavaland ruins slightly - Hermit, seed vault, Animal Hospital (TAKE 2)

### PR DESCRIPTION
**Pull request by Mick1299**
## About The Pull Request
Gives a few atmospheric tools to inhabited lava land ruins so they can survive for longer alone.
Hermit - Adds an oxygen canister
Seed vault - Adds a vent and scrubber network, and an air tank
Animal Hospital - Adds a vent and scrubber network, plumbs them into the existing air tanks behind the hospital

## Why It's Good For The Game
Animal hospital and seed vault had no way to repair their atmos in the event of a breach. A vent and scrubber network lets the inhabitants breath inside in the event of a miner or mob smashing down a wall or window.

Props to @Ohagi-Chan for the original Idea and implementation, I'm just doing the PR for them.

## Changelog
:cl: - Ohagi-Chan
tweak: Adds a few Atmos components to Inhabited lavaland ruins
/:cl:

### CODE REVIEW

**Comment by Mick1299** [comment]
There we go, Travis is happy now

**Comment by zeskorion** [comment]
can you give the hermit about ten sheets of iron so he can patch holes in his walls without using only sandstone doors as well?

**Comment by Mick1299** [comment]
Done, added a stack of 20 iron sheets to Animal and Hermit.

**Comment by yorii** [comment]
Can you also add botany gloves to the seed vault?

**Review by zeskorion — APPROVED** [review]

**Comment by Mick1299** [comment]
Sorry torii, didn't see your comment fast enough

**Comment by zeskorion** [comment]
if you wanna make another pr to do that, charlie station and syndie lavaland need fastmos shit

**Pull request merged**
