### PR TITLE
HUD icons sorted into it's own folder

### PR DESCRIPTION
**Pull request by PestoVerde322**
## About The Pull Request

This massive PR moves almost all the HUD elements into it's own dedicated folder, that's all.

## Why It's Good For The Game

QOL for developers and contributors.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

immagine

</details>

## Changelog
:cl:
refactor: Moved (almost) all the HUD elements into it's own folder.
/:cl:

### CODE REVIEW

**Comment by PestoVerde322** [comment]
I *STRONGLY* suggest a TM, just in case something breaks here.

**Comment by EvilDragonfiend** [comment]
This is good to go with
* https://github.com/BeeStation/BeeStation-Hornet/pull/10741

highly recommended because my PR can catch misplaced cases.

**Comment by PowerfulBacon** [comment]
It doesn't seem to add any more testing or lints

**Review by PowerfulBacon — APPROVED** [review]
Seems good to me, we really ought to lint against mutable appearance, image and icon being used with invalid icon states

**Comment by PowerfulBacon** [comment]
> I *STRONGLY* suggest a TM, just in case something breaks here.

If a PR like this needs testmerging then you haven't tested it locally well enough

**Comment by EvilDragonfiend** [comment]
> > I _STRONGLY_ suggest a TM, just in case something breaks here.
> 
> If a PR like this needs testmerging then you haven't tested it locally well enough

image

**Comment by EvilDragonfiend** [comment]
(nvm. I was sleepy atm lol)

**Pull request merged**
