### PR TITLE
adds bloodedge

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request

adds an edgier katana
blame @PerishedFraud for the sprite that made me actually PR this
## Why It's Good For The Game
it's not
## Changelog
:cl:
add: edgy katana and two toy versions
tweak: GAR sunglasses now appear in arcade prize pool
/:cl:

### CODE REVIEW

**Comment by katebishop49** [comment]
why

**Comment by zeskorion** [comment]
> why

i dont want to

**Comment by Firefox13** [comment]
Also: Every GAR glasses has *surprisingly* high throw force.
Make it optional weapon for space ninja.

**Comment by zeskorion** [comment]
AAUfgh i dont wanna do i con conflicts

**Pull request closed without merging**
