### PR TITLE
Syndicate teleporter rework

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

- The syndicate teleporter now costs 7 TC instead of 8 TC
- The syndicate teleporter can no longer teleport through solid objects or walls
  - The syndicate teleporter will deal 150 structural damage to any solid objects, if it is broken, then you can travel through them.
- The syndicate teleporter's damage has been upped to 25, however it now respects armour blocking
- The syndicate teleporter's paralysis time has been reduced to 1 seconds from 3, but now deals 4 seconds of knockdown additionally, which will be reduced proportional to the armour rating of the target
- Wearing a BOH or being EMPed will now result in a random direction teleport rather than allowing the user to be gibbed.

## Why It's Good For The Game

The syndicate teleporter was created as an item to be used in combat, however it has significant design flaws:
- Gameplay issues: The syndicate teleporter can be used as a stealth item, which has the positives of an emag (free entry to almost all locations) without leaving behind any evidence. This has lead to them being severely over-used on lowpop rounds in order to quickly break into the captain's office without anyway to stop it.
- 'Insta-win' combat issues: The syndicate teleporter can randomly gib its user if the (really bad) emergency teleport fails to save the user. This is surprisingly common and a source of frustration for the users.
- Useless in combat: you have to land exactly on the target in order to get the weak telefrag effect to apply. This is surprisingly difficult when the teleport distance is entirely random.
- Lore continuity issues: The syndicate only have access to worse, stolen, or remodified nanotrasen tech and not their own teleportation devices (otherwise why would they be stealing them).

## Testing Photographs and Procedure

https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/8a6d4dd3-e209-4f38-9981-e89285fc4f6d

## Changelog
:cl:
balance: Syndicate teleporter has been reworked. It will no longer teleport through solid walls but will be more effective at knocking down targets in a combat scenario, as it will knock down any targets passed through during a teleport. It can be used to jump through windows without being shocked. The price has been reduced from 8 TC to 7.
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
I had *no* idea this thing could be used in combat tbh

**Review by EvilDragonfiend — CHANGES_REQUESTED** [review]
Current logic does the pre-teleport thing that breaks stuff & frags people even if bluespace anchor blocks the actual teleport.

**Comment by PowerfulBacon** [comment]
image
Bluespace anchors will now prevent this from working

**Review by EvilDragonfiend — DISMISSED** [review]

**Comment by EvilDragonfiend** [comment]
oops, misclick

**Review by Rukofamicom — APPROVED** [review]

**Review by EvilDragonfiend — APPROVED** [review]

**Pull request merged**
