### PR TITLE
The dreaded auxmos port

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

Map edits are hold off until the cit pr is merged

ports parts of Citadel-Station-13/Citadel-Station-13#8236
and obviously Citadel-Station-13/Citadel-Station-13#13991

## Why It's Good For The Game

compatibility with later byond vers

## Changelog
🆑deathride58, putnam3145
add: FDA, LINDA without the bookkeeping.
add: Putnamos, a simpler replacement for Monstermos. If I can get Monstermos to work, this will be Monstermos instead.
del: LINDA, the old active-turfs-based atmos subsystem.
del: Monstermos? I would rather not get rid of this, but I can't get it to work correctly.
server: Extools has been removed, and loading extools alongside auxtools will cause massive problems. If this is tested or merged, remove extools from the static files.
refactor: Added unomos, which is basically listmos except gas mixtures only use one single list for handling their gasses.
/🆑

### CODE REVIEW

**Comment by jupyterkat** [comment]
Closed for some working needed, wait for the cit pr.

**Comment by utilbird** [comment]
One of the PRs you are porting is still open

**Comment by jupyterkat** [comment]
I don’t get it

**Comment by utilbird** [comment]
You should wait until PRs are merged before porting them

**Comment by jupyterkat** [comment]
That’s why it’s drafted, duh

**Comment by utilbird** [comment]
yeah but.. it would have been much easier just to wait and then do it, rather than copy pasting every commit that it gets

**Comment by jupyterkat** [comment]
same amount of work, just different times....

**Comment by Crossedfall** [comment]
Unless you are familiar with rust and the current implementation of extools you should not attempt to port this. 

Edit: Closing since I haven't really been given any indication that you're familiar with either of those requirements. We'll port it when we're in a place to do so and when it's actually ready to be ported.

**Comment by jupyterkat** [comment]
I made it work, if that’s not enough then I don’t know what is. If you don’t want me to work on it, fine then.

**Pull request closed without merging**
