### PR TITLE
adds bluespace miners to old statino (you know the one with hivebots and shit)

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request

adds bs miner board and some bs crystals +astroid filled with bs crystals to ye old station

## Why It's Good For The Game

no more whining from people

## Changelog
:cl:
add: bluespace miners were actually found from hivebot assault ships, they normally have a board hidden in those ships, tough a hivebot assault hasnt happened to a NT ship in 100 years
/:cl:

### CODE REVIEW

**Comment by Rukofamicom** [comment]
just add some resources to the asteroid instead of adding infinite resource capability to the spawner.

**Comment by ToasterBan** [comment]
I am only doing this because people wanted, not because I actually care

**Comment by OceanFish1** [comment]
> I am only doing this because people wanted, not because I actually care

Belone you picked the wrong account

**Comment by francinum** [comment]
Charlie is supposed to be outdated as fuck. Their entire joke is working in a horribly subpar environment.

No. 🔑

**Comment by Sinestia** [comment]
> 
> 
> just add some resources to the asteroid instead of adding infinite resource capability to the spawner.

Adding more can also encourage people to raid it more
less of an issue with resources, definitely an issue with guaranteed BSMs


its fine as is tho imo

**Comment by Sinestia** [comment]
> 
> 
> I am only doing this because people wanted, not because I actually care

you're supposed to stamp your boot on the face of the suggestion-haver and say "WYCI" not do it for them wtf

**Comment by utilbird** [comment]
> you're supposed to stamp your boot on the face of the suggestion-haver and say "WYCI" not do it for them wtf

This.

**Comment by eeSPee** [comment]
Can we stop accusing random accs of being Belone?

It's only coincidental that 1 day accounts make 10 dislike PRs that get merged the day after (by Belone).

**Comment by ike709** [comment]
🔑

**Pull request closed without merging**
