### PR TITLE
OSHA violations (plus hair ties)

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
(see https://github.com/BeeStation/BeeStation-Hornet/pull/2588, with issue that this was closed over rectified)

having long hair is now dangerous around industrial machinery. Hair ties have been added to compensate- make one out of wire and wear it in the head slot to tie hair back into a hairstyle that wont get in the way 

image

chainsaws, unsafe doors, portable scrubbers, the gibber, the recycler, and mass drivers all have interactions, and new ones are quite easy to add. These interactions are tailor-made to feel like they're out of a gory workplace safety PSA- ~~stand next to a mass driver door? you get sucked in! mass driver activates and pulls you in as well, and you've been spaced~~! turn on a chainsaw, hair is stuck in? you fall on the saw! etc. New interactions are very easy to add, as simple as calling the proc

comprehensive list is as follows:
normal osha violation hair (very rare for a mishap to occur): "Long Bedhead", "Very Long Hair 1", "Very Long Hair 2", "Long Hair 1", "Long Hair 2", "Long Hair 3", "Long Side Part", "Hime Updo", "Hime Cut", "Hime Cut 2", "Drill Hair (Extended)"
super osha violation hair (5x chance for mishap): "Floorlength Bedhead"

## Why It's Good For The Game
To put a bit more in, this addition is incredibly fitting for the vibe and atmosphere of ss13. Workplace negligence leading to terrible bodily harm? Tell me that doesn't fit!

also, only shitters use floorlength bedhead

## Changelog
:cl:
add: hair ties! make them out of cable like cablecuffs, and wear them in the head slot to tie your hair back, into a style safe to work around machinery with. they come in multiple colors!
balance: long hair is now dangerous around industrial machinery
imageadd: new codersprites for hairties, and more icon conflicts
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
for the sake of mister headdev, floor length braid is no longer an OSHA violation, instead being the style used when tying back floor length bedhead

**Comment by zeskorion** [comment]
note: waggingtails are a considered addition to the proc, but
A) i dont feel like it right now
B) ill save that for a later pr to exclusively piss off felinid players

**Comment by r1ks-iwnl** [comment]
Is this RNG i smell

**Comment by VictorVow** [comment]
Make this a negative trait otherwise it pointlessly discourages appearance variety.

**Comment by super12pl** [comment]
Stop trying

**Comment by ghost** [comment]
codersprite

**Comment by eLeCtrOssSnake** [comment]
I am going to die... I don't even need to explain why this is so stupid.

**Comment by eLeCtrOssSnake** [comment]
It doesn't even fit ss13 atmosphere? Like with what? With certain accessories possibly affecting your game in the bad direction? How?

**Comment by ike709** [comment]
Bad code for a bad meme

**Comment by zeskorion** [comment]
> Bad code for a bad meme

Bitch.

**Comment by Moccha-Bee** [comment]
code better next time lol

**Comment by Archanial** [comment]
not funny didn't laugh

**Comment by ta3370** [comment]
> It doesn't even fit ss13 atmosphere? Like with what? With certain accessories possibly affecting your game in the bad direction? How?

NT is a dystopian megacorp that doesn't care about it's employees, it totally makes sense according to 90% of server's lore. They go for the cheapest possible bidders machines. Safety features cost money.

**Comment by zeskorion** [comment]
shitcode (and some functions) gone

**Comment by Archanial** [comment]
Doesn't change the fact it's cringe

**Comment by PowerfulBacon** [comment]
This is still a bad PR even with some shitcode removed, having the chance to be gibbed simply because you chose a hairstyle is too far and people shouldn't have to worry about the insanely over the top effects of choosing the _wrong_ hairstyles.

**Comment by zeskorion** [comment]
> This is still a bad PR even with some shitcode removed, having the chance to be gibbed simply because you chose a hairstyle is too far and people shouldn't have to worry about the insanely over the top effects of choosing the _wrong_ hairstyles.

dont use a gibber with dumb hair then. in a roleplay game, purely cosmetic options dont quite fit, i think


regardless, not contributing anything till this is put to a proper vote

**Comment by zeskorion** [comment]
Said dumb shit late night. Cant just take it back though?

**Comment by ghost** [comment]
> Said dumb shit late night. Cant just take it back though?

lol

**Comment by PowerfulBacon** [comment]
> 
> 
> Said dumb shit late night. Cant just take it back though?

why not?

**Pull request closed without merging**
