### PR TITLE
Proto-Mentorhelp

### PR DESCRIPTION
**Pull request by Cw3040**
-Mentorhelp verb in its own tab
-It's just an ahelp with a different face

### CODE REVIEW

**Comment by CthulhuOnIce** [comment]
This is w o r k a b l e

**Comment by Cw3040** [comment]
Kev is big gay

**Comment by CthulhuOnIce** [comment]
Closing because of booly

**Comment by Cw3040** [comment]
<3 you kev

**Comment by CthulhuOnIce** [comment]
Are you gonna add more to this or should I take it from here?

Either way is fine

**Comment by Cw3040** [comment]
Eh, the big thing to do is to make a proper mentor role and have the mentorhelps give a distinct ticket to both mentors and admins

**Comment by CthulhuOnIce** [comment]
Why not just a mentor permission for admins, a mentor would **only** have that perm

**Comment by CthulhuOnIce** [comment]
But still, should i take over or will you continue?

**Comment by Cw3040** [comment]
You take over, I've got other things to do

**Comment by CthulhuOnIce** [comment]
kk

**Pull request merged**
