### PR TITLE
adds minor amount of miasma to Lavaland, reduces amount of rare gases

### PR DESCRIPTION
**Pull request by bloons3**
## About The Pull Request
- adds minor amount of miasma to Lavaland
- reduces amount of BZ that can spawn
## Why It's Good For The Game
BZ

## Changelog
:cl:
add: Adds miasma to Lavaland atmos, make sure to wear internals or you'll get sick!
tweak: Reduced available amount of BZ on Lavaland
/:cl:

### CODE REVIEW

**Comment by pickleinjar** [comment]
bro can u just do a 180 on dat pr? we need the exact opposite.

**Comment by OceanFish1** [comment]
> bro can u just do a 180 on dat pr? we need the exact opposite.

me when fun but it's 180

**Comment by utilbird** [comment]
#3504 is/was better for a gas cargo nerf if that's what you're trying to achieve. Otherwise I don't see why BZ would need to be reduced with the addition of miasma. Only one restricted gas can spawn per atmosphere

**Comment by bloons3** [comment]
Why cargo gas mining is a problem: 
image
image

**Comment by bloons3** [comment]
> #3504 is/was better for a gas cargo nerf if that's what you're trying to achieve. Otherwise I don't see why BZ would need to be reduced with the addition of miasma. Only one restricted gas can spawn per atmosphere

I'm not trying to nerf the sell price of BZ in cargo, I just want cargo to find a place that isn't Lavaland to get their BZ from. Perhaps they could work with the Atmos department.

**Comment by ike709** [comment]
Irrelevant now.

**Pull request closed without merging**
