### PR TITLE
Ports winter coats from TG

### PR DESCRIPTION
**Pull request by tasteofaliar**
## About The Pull Request
(from original tg pull request)
Winter coats!
image

Adds winter coats for:

- Centcom
- HoP
- Janitor
- HoS
- CMO
- Chemists
- Virologists
- RD
- Roboticists
- Geneticists
- CE
- QM
- Mining*

All with unique descriptions, and adding descriptions to those that didn't have them before!
(end of original tg pull)

Note: also gives mining 1 coat in each locker no matter the map, with the exception of an extra as a spare*

Original TG Pull: [Winter coats #56854](https://github.com/tgstation/tgstation/pull/56854)
**SPRITE WORK BY:** @Seris02 [from source](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/9823)

idea to port by Gatling#0079 on Discord and @Hardly3D 

special thanks; Kyumi, for helping me with coding and learning and also being my emotional support when I started turning into Heath Ledger's Joker trying to fix sprite issues due to inexperience alongside several bumps along the way.

## Why It's Good For The Game

Nothing wrong with some more cosmetic options, I quite enjoy using the winter coat to look nicer.

## Changelog
:cl: Bluedisc
add: Adds 13 winter coats covering all departments and most jobs.
/:cl:

### CODE REVIEW

**Comment by tasteofaliar** [comment]
realized that the miscellaneous file has *all* of its code showing as changed, thats a first time coder issue and is my bad. i didnt want to just copy paste everything i changed so i thought replacing the file would be fine, didnt think it would make it an obnoxious read on github

all i did was add the coats from the original TG port and adjusted its code to fit bee's

**Comment by Rukofamicom** [comment]
It shows them all changed... because they are all changed. 

What program did you edit this file in?  Every indentation has been replaced with multiple spaces instead.

**Comment by tasteofaliar** [comment]
I use VSC to code, and have the goon pack extensions and such. I'm not sure why that's happend, if needed I can fix it (unless maintainers do that or somethin, not familiar with how this side of bee works)

edit: just realized what you meant by 'they are all changed', I assume you mean cause the indentations got replaced somehow. Really odd.

**Comment by Rukofamicom** [comment]
I pushed a fixed version of the file to your fork, merge it and it should show up here.

**Comment by ToasterBan** [comment]
a lot of our winter coats have a completely different artstyle, might want to ask a spriter or try to update the sprites yourself

**Comment by Fronsis** [comment]
I think some of them are way too bright compared to the ones we have(specially the whites), i believe the ones we have are more fitting color-wise to what our sprites and general color palette are aiming for, i'm not an expert though so i'd rather leave that to Naevi or Pigeon to comment

**Comment by tasteofaliar** [comment]
BRUH

~~Going to ask before doing anything, is it causing conflicts cause my fork isn't up to date with the current Bee?~~

nevermind, changelog issues Apparently?

**Comment by tasteofaliar** [comment]
> a lot of our winter coats have a completely different artstyle, might want to ask a spriter or try to update the sprites yourself

All, if not most of our current winter coats are originally from TG if I recall

> I think some of them are way too bright compared to the ones we have(specially the whites), i believe the ones we have are more fitting color-wise to what our sprites and general color palette are aiming for, i'm not an expert though so i'd rather leave that to Naevi or Pigeon to comment

I do agree on this, I found the research coats to be the worst but I have no experience in spriting so I decided not to mess with it and leave it as-is

**Comment by Rukofamicom** [comment]
God dammit, I hate trying to merge out of sync forks. 

Revert my "fix" it made it 10x worse because I tried to bring my fork back into sync with yours 😔

**Review by Crossedfall — CHANGES_REQUESTED** [review]
Remove the changes to the changelog files

Best way to do this would be to simply checkout the file from upstream. Assuming you have our repo set as a remote with the name `upstream` you can run the following from the repo's root directory:

```
git checkout upstream/master -- html/changelog.html
git checkout upstream/master -- html/changelogs/.all_changelog.yml
```

**Comment by tasteofaliar** [comment]
Trying to fix now, if I make this even worse somehow I'm just gonna reopen the PR instead of trying to salvage this

**Comment by tasteofaliar** [comment]
Starting from scratch because this shits a fuckin mess, yo.

Will have it back tomorrow or the day after. gonna focus on helping my friend with something code-wise instead

**Comment by Rukofamicom** [comment]
apologies for my part in making the issue even worse

**Comment by tasteofaliar** [comment]
> apologies for my part in making the issue even worse

Honestly, don't blame yourself. Judging from what I saw code-wise your code did fine but something either on my part or yours unintentionally fucked the changelog. No one's really to blame. I do appreciate your fix though cause that probably would've caused trouble later on

Also I have an absurd amount of free-time and know what I have to do to add the coats so it'll be done way quicker

edit: also I'm absurdly inexperienced and only picked up coding a few days ago, so that probably didn't help hahahaha

**Pull request closed without merging**
