### PR TITLE
Adds Yatzy

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Adds Yahtzee to the curator toy vendor.

## Changelog
:cl:
add: You can now buy games of yatzy at toy vendors.
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
I don't think we have the rights for that name, do we?

**Comment by ToasterBan** [comment]
rename it to like "yaspace" or something like that

**Comment by amidoingitright** [comment]
the name yatzy is public domain if that helps

**Comment by eeSPee** [comment]
Yatzy it is.

**Comment by eeSPee** [comment]
> the name yatzy is public domain if that helps

Most likely the game Yahtzee --ripped off-- coppied.

**Comment by ike709** [comment]
Notzy would be funnier and safer.

**Comment by francinum** [comment]
> Notzy would be funnier and safer.

Are you sure about that

**Comment by ike709** [comment]
> Are you sure about that

Absolutely 😎

**Comment by ike709** [comment]
But yeah no I still don't think Yatzy is different enough.

**Comment by eeSPee** [comment]
> But yeah no I still don't think Yatzy is different enough.

https://en.wikipedia.org/wiki/Yatzy

Yatzy is a public domain dice game similar to Yacht and Yahtzee (trademarked by Hasbro in the United States).

**Comment by ike709** [comment]
Good enough then, I suppose.

**Comment by ike709** [comment]
Post a picture of the paper formatting. If it looks good I'll merge.

**Comment by ike709** [comment]
Image never loaded but whatever.

**Pull request merged**
