### PR TITLE
(Recoup) Ports superior environmental handlers & species-specific temperature handling. Adds warm hugs!

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports:
- https://github.com/tgstation/tgstation/pull/48569
- https://github.com/tgstation/tgstation/pull/48920
- https://github.com/tgstation/tgstation/pull/49594

## About The Pull Request

atomization of #8992, without needing the mobility pr to be merged first. Completely independent.

### PR number one
- Base human default temperature range is a bit more reasonable, (+30, -40 vs +/- 50) you would cook or freeze without taking damage before.
- Split up species handle_environment, it was a single massive proc, now each species has handle_environment, handle_body_temperature, handle_environment_pressure.
- Each species can now have their own body temp, and hot/cold damage ranges.
- Removed checks that we have an environment in many of the classes, this is handled at the base mob class.

**Species:**
All the species modified will survive the normal range of temperature range on station.

- Ethereals core body temp is hotter and can stand higher body heat, but they take damage in cold areas faster.
- Lizard people are cold blooded and do not stabilize body temperature normally, because of they do not take damage as fast as a human. They still stabilize to the room temp.
- Plasmamen like it cold and can survive colder temps better, but take damage when it is hot faster and they can stabilize body temp slower at times.
- Zombies do not stabilize body heat naturally, they are dead. Heat damage is equal to fire spread temp, and cold temp is equal to min temp to move. They still stabilize to the room temp, like lizards
- All other species use base human heat, I was thinking something unique for moths/apids, but we can do that later

### PR number two
- Hugs transfer heat between the two participants and give a moodlet for someone who is cold. Hug your local walking light bulb to heat up!

### PR number three
- fix fever stuff

## Why It's Good For The Game

fulfills two of #1469

1. Makes mobs reacting to temperature code a lot less shit. Pulled apart a few large procs and optimized them
2. Species having different heat capacities make a lot more sense. Species like ethereals and plasmamen can be a whole lot cooler if we consider temperature changes

3. Who doesnt like warm hugs?

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

The room isnt that cold, I just put it down to freezing and burst the can for visual effect ;)

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/c0e9206d-bdfd-4b8a-af56-c1fc5983e7a3

</details>

## Changelog
:cl: RKz, nightred
add: Species body temperature handling
balance: Plasmamen, Lizardpeople, Ethereal have custom body temperatures to deal with
fix: natural body temp stabilization now returns proper values
refactor: clean up of the environment handles for mobs and species
add: Hugs transfer heat between the two participants and give a moodlet for someone who is cold. Hug your local walking light bulb to heat up!
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
One thing

I can port this balance change if maints/admins think its too much of a weakness, or I won't if they think lizards/ethereals are better with a weakness to the temp gun.
1. https://github.com/tgstation/tgstation/pull/48912

**Comment by WhereAmO** [comment]
Would an IPC run hotter or colder than a human?

**Comment by itsmeow** [comment]
Can you also take a look at #8452 and see if any changes there are of use? I basically did a similar thing but from scratch.

**Comment by Tsar-Salat** [comment]
> Can you also take a look at #8452 and see if any changes there are of use? I basically did a similar thing but from scratch.

Sure. I can grab a few, I just don't want to make too many changes to system in one pr

**Comment by CydiaLamiales** [comment]
> One thing
> 
> I can port this balance change if maints/admins think its too much of a weakness, or I won't if they think lizards/ethereals are better with a weakness to the temp gun.


Temp gun needs a nerf overall to be honest, it's kinda OP.

**Comment by Tsar-Salat** [comment]
bump

**Review by PowerfulBacon — APPROVED** [review]

**Comment by Tsar-Salat** [comment]
fixed issue, last test ran before CLAMP macro removal.

**Pull request merged**
