### PR TITLE
Fixes shuttle thrusters

### PR DESCRIPTION
**Pull request by benbot16**
## About The Pull Request

Atomized version of  #8198 because that's been sitting there for 2 weeks and I want my shuttle engines back.

## Why It's Good For The Game

Invisible objects bad.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

See DMI Diff

</details>

## Changelog
:cl:
fix: Fixes shuttle thrusters not having icons.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
This issue is fixed by #8233 and #8198

**Comment by benbot16** [comment]
> This issue is fixed by #8233 and #8198 (This isn't blocking for #8233 since it won't conflict as I changed the icon path entirely)

I can close this if you want, it's just been at least a few weeks and it's a really annoying issue to deal with.

**Comment by PowerfulBacon** [comment]
I'm hoping #8233 won't take too long to get merged, but it probably will. #8198 has a blocking review since it has a larger scope than necessary.
I'm fine to merge this if pigeon is good with it (it will conflict them)

**Review by itsmeow — APPROVED** [review]
I would really like to get this fixed and since holidays and stuff maintainers don't have as much time to do maintaining. Let's get our shuttle thruster sprites back, Pigeon can use iconmerge or something

**Comment by PowerfulBacon** [comment]
Yolomerge my PR

**Review by Penwin0 — APPROVED** [review]

**Pull request merged**
