### PR TITLE
Erp verbs

### PR DESCRIPTION
**Pull request by CthulhuOnIce**
Checks playercount requirements before adding a map to the map vote.

### CODE REVIEW

**Comment by qwertyquerty** [comment]
imagine needing 3 commits for an 11 line change

**Comment by ike709** [comment]
`TRUE`/`FALSE`

**Comment by CthulhuOnIce** [comment]
> imagine needing 3 commits for an 11 line change

"cthulhu why you no code for us 😢 "

**Comment by qwertyquerty** [comment]
Kev your coding is so disgusting this proc can literally be two lines

```
/datum/map_config/proc/is_votable()
	return votable && (config_max_users && GLOB.clients.len <= config_max_users) && (config_min_users && players >= config_min_users)
```

**Comment by ike709** [comment]
qwerty is right tbh

**Comment by ike709** [comment]
half of that proc is returns

**Comment by CthulhuOnIce** [comment]
"haha look i made your code smaller but also harder to read for no reason, i bet you feel dumb now"

image

**Comment by ike709** [comment]
how often do people seriously need to read this proc though? it's pretty straight-forward

**Comment by CthulhuOnIce** [comment]
you're right, so why go through the extra trouble to make it less readable at no benefit?

**Comment by qwertyquerty** [comment]
Coding conventions, follow them

**Comment by ike709** [comment]
2-line helper proc memes

**Comment by qwertyquerty** [comment]
Kev it's really not harder to read my way. Seriously not at all

**Comment by CthulhuOnIce** [comment]
honestly do it yourself then, asshole

**Comment by Crossedfall** [comment]
If we're bringing up coding conventions then you should be splitting the lines to make it more readable for debugging and future alterations.

This is a compiled program, there's little gain in making it difficult to read. The original method is generally preferable

**Comment by qwertyquerty** [comment]
There is everyone happy yet

**Comment by ghost** [comment]
no. it needs more pazzazz. Make the voting window thingy rainbow colored.

**Comment by CthulhuOnIce** [comment]
I don't care about the code, if you made your own pr with that i wouldn't care. What I care about is **you** hijacking **my** PR to fit your dumbass "coding conventions". And then you say things like "I'm a bit miffed you don't work on bee anymore".

**Comment by qwertyquerty** [comment]
What is wrong with me editing your PR

**Comment by CthulhuOnIce** [comment]
Because

1. You rewrote it, i'm not even writing the code that gets merged
2. It's my PR, and the code was fine, you had no reason to "make" me change it
3. you made it **worse**

**Comment by qwertyquerty** [comment]
Local jannie still mad

**Comment by CthulhuOnIce** [comment]
yeah, i'm mad because i can't work on my own server

**Comment by qwertyquerty** [comment]
You worked on it, I made some changes, merge

**Pull request merged**
