### PR TITLE
Sets cyborg total positions to 1

### PR DESCRIPTION
**Pull request by someone543**
## About The Pull Request
Sets the cyborg jobs total position to 1, allowing one late joining cyborg if there is no round start cyborg.

## Why It's Good For The Game
If there isn't a round start cyborg, players should be able to late join and take the vacant slot.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

LateJoinCyborg

</details>

## Changelog
:cl:
tweak: Cyborg total positions set to 1
/:cl:

### CODE REVIEW

**Comment by CydiaLamiales** [comment]
So how does it spawn? On the Arrivals shuttle like all other jobs?

**Comment by someone543** [comment]
> So how does it spawn? On the Arrivals shuttle like all other jobs?

Yep

**Comment by St0rmC4st3r** [comment]
Iirc it already works this way, unless something was changed recently.

**Comment by someone543** [comment]
> Iirc it already works this way, unless something was changed recently.

It doesn't? I observed rounds where there are no round start borgs, and there wasn't any option on the Choose Profession menu. 
Here is a screenshot of the menu from a local test without the changes. 
LateJoinCyborgMenu1

**Comment by PowerfulBacon** [comment]
This is overriden in the config anyway I'm pretty sure

**Comment by someone543** [comment]
> This is overriden in the config anyway I'm pretty sure. Check jobs.txt
> 
> https://github.com/BeeStation/BeeStation-Hornet/blob/7fd314f473baf7ce60aff00c393edf31170af84e/config/jobs.txt#L49
> 
> It already works this way due to the config in jobs.txt
> 
> I checked in game and there doesn't seem to be a late join cyborg, so we might have a different config on the server

I can't know this for sure because I don't know what the official servers config is, but jobs are only loaded from jobs.txt if the config option LOAD_JOBS_FROM_CONFIG is enabled. 

https://github.com/BeeStation/BeeStation-Hornet/blob/7fd314f473baf7ce60aff00c393edf31170af84e/config/config.txt#L316

**Comment by Crossedfall** [comment]
I'd prefer midround cyborgs come from robo to be honest.

**Comment by CydiaLamiales** [comment]
> I'd prefer midround cyborgs come from robo to be honest.

How about posibrains showing up in the job selection menu when latejoining? If that's even possible

**Comment by someone543** [comment]
> I'd prefer midround cyborgs come from robo to be honest.

If roboticists want to make more than one cyborg, then they should be free to do so. This PR only allows for a single late join cyborg, and that's only when nobody got chosen for a round start cyborg.

**Comment by PowerfulBacon** [comment]
Positronic brains showing up on the latejoin menu would be a good compromise actually

**Comment by someone543** [comment]
> Positronic brains showing up on the latejoin menu would be a good compromise actually

While it's an interesting idea that could be looked into, I think that would be better for another PR. This PR is for situations where a round start cyborg is not chosen, and should be allowed to have a single late join slot opened for consistency.

**Comment by itsmeow** [comment]
Considering roundstart cyborgs aren't always around and posibrains being taken is a huge gamble, I think that this is a good change if it's only in the case where the roundstart slot isn't taken.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
