### PR TITLE
port tg's machine_stat and is_processing() refactor

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

nuclear warhead pr
ports tgstation/tgstation#53150

## Why It's Good For The Game

yes

## Changelog
:cl:rohesie
refactor: refactored machine_stat and is_processing
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
What does this actually do apart from rename a variable?

**Comment by jupyterkat** [comment]
adds a proc for changing machine stats so we can do on_change_machine_stats() or something like that. wouldn’t it be annoying if machine stats and mob stats are both named “stats”

**Comment by jupyterkat** [comment]
needs #4401 to be done first

**Comment by ike709** [comment]
The prerequisite is merged, but this is becoming stale.

**Comment by jupyterkat** [comment]
hold on for a bit, on a tight schedule here

**Review by utilbird — COMMENTED** [review]
It seems strange having to put the variable assignment operation inside the proc argument itself.
Imo it'd be better to have `on_set_machine_stat` react to the new value rather than the old value too.

Regardless, looks fine operationally speaking. readability might take a bit of a hit though 😆

**Review by PowerfulBacon — DISMISSED** [review]

**Comment by ike709** [comment]
🔑

**Pull request closed without merging**
