### PR TITLE
Adds a bunch of DS items

### PR DESCRIPTION
**Pull request by ghost**
this time i followed what qwerty said

### CODE REVIEW

**Comment by ike709** [comment]
and look where that got you

**Comment by qwertyquerty** [comment]
travis mad x24

**Comment by qwertyquerty** [comment]
oh wait it's mapdiffbot

**Comment by ghost** [comment]
i want to see whats wrong aight.

**Comment by ondrej008** [comment]
> 
> 
> i want to see whats wrong aight.

merge conflicts, that's whats wrong aight

**Comment by Toxici11i** [comment]
map diff bot is fucking autistic and is broken, please commit ass blast, it literally said my old merges were now incompatible, what a 🇧🇷 bot

**Comment by qwertyquerty** [comment]
Map bot doesn't work because of your cringe merge conflicts

**Pull request closed without merging**
