### PR TITLE
Allow movement when getting up from the ground

### PR DESCRIPTION
**Pull request by XeonMations**
## About The Pull Request

Allows you to move around while getting up from the ground.

## Why It's Good For The Game

finally stops me from going insane from moving one tile by accident and having the rest timer reset.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/dc955c6c-2d0b-485b-9d6f-8d62b57f1d9b

</details>

## Changelog
:cl:
balance: Spacemans can now move when getting up from the ground without their legs giving out.
/:cl:

### CODE REVIEW

**Comment by HowToLoLu** [comment]
I thought this change would've classified as more of a tweak, but I can't seem to find if the code that's being changed actually intended against or for this type of thing. In fact; it's as if this specific line just appeared out of the blue and has no origin in the timeline at all.

In commit 0bf96243c1954f6ea391e12f7c25c165d8cc45f3 it wasn't there.

And then in 8f7b1425978e2577985350c414fe9993afcca5ab it appeared, but isn't apart of that commit's changes.

**Comment by Rukofamicom** [comment]
This has always been how getting up from resting works. In what situation are you trying to rest while actively moving exactly?

Asking to ensure it isn't because you're using resting mid-combat and trying to buff it's usage mid-combat.

**Comment by Rukofamicom** [comment]
Are you aware of the combat implications this change has?

**Review by Rukofamicom — APPROVED** [review]

**Comment by EvilDragonfiend** [comment]
It's likely a fix to me since it's weird that you can't get up yourself with moving when you intentionally crawl while you can do that when you're shoved. but all good anyways.

**Review by EvilDragonfiend — APPROVED** [review]

**Pull request merged**
