### PR TITLE
HOS gun is full-auto again

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
Fixes HOS full-auto regression

## Why It's Good For The Game
HOS gun is pretty mediocre without full-auto.

## Changelog
:cl:
add: HOS gun is full-auto again.
/:cl:

### CODE REVIEW

**Comment by Moccha-Bee** [comment]
HoS gun has the tase option, have a full auto taser would be gay as fuck no please

**Comment by VictorVow** [comment]
Unless they're clicking directly on your sprite rather than past you then the second shot will miss, so the full-auto isn't very useful for tasing.

**Comment by Archanial** [comment]
Buffing hos - bad idea. HoS gun is already overpowered as fuck with his bullshit stun.

**Comment by VictorVow** [comment]
It hasn't been a stun for months.

**Comment by Archanial** [comment]
> 
> 
> It hasn't been a stun for months.

Yeah only knockdown, confusion and slowdown, yeah not stun.

**Comment by PowerfulBacon** [comment]
I'd say make the stun mode not full auto personally

**Comment by AnjelicaChaykovsky** [comment]
https://github.com/BeeStation/BeeStation-Hornet/issues/2563  can u close my issue with your pr victor,  good work btw

**Comment by AnjelicaChaykovsky** [comment]
It wont even make you drop your item in hand or give stam damage  + its only 3 rounds

Its pretty shit,  its knockdown for 2 sec basically that 
takes all your ammo absolutely ridiculous

> Buffing hos - bad idea. HoS gun is already overpowered as fuck with his bullshit stun.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
