### PR TITLE
Cryopod Maps take 2

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
This better merge right. Also, this is just the map files that contain all of the individual station's cryo lounges. THANK GOD IT CAN AUTOMERGE

## Why It's Good For The Game
AFK despawn, opening job slots. You've heard it all before.

## Changelog
:cl:
add: Cryo lounges to Delta, Meta, Box, Pubby, and Kilo
/:cl:

### CODE REVIEW

**Review by ike709 — APPROVED** [review]
Just get qwerty to sign off on the mapping changes. I like them.

**Comment by qwertyquerty** [comment]
Why did mapdiffbot have to die

**Comment by ike709** [comment]
He posted pics on discord.

**Comment by qwertyquerty** [comment]
I'll update all the maps on the site soon

**Comment by MarkSuckerberg** [comment]
nice

**Pull request merged**
