### PR TITLE
Removes all the useless job reskins, balances the game.

### PR DESCRIPTION
**Pull request by super12pl**
## About The Pull Request
Removes all the job slots from the station with exception of one hop slot and 69 assistant slots.

## Why It's Good For The Game
In the end every job is just an useless reskin of assistant
Engineer? assistant with toolbelt
Doctor? assistant with medkit
Security? assistant with baton
This PR removes all this bloat and makes the game truly balanced and enjoyable:tm:
If you want to play the job just ask the hop for access suh!

## Changelog
:cl:
balance: removes job bloat
/:cl:

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Resolve the merge conflicts.

**Comment by Sinestia** [comment]
Dumb


Clowns have very specific properties limited to roundstart clowns, so it's clearly a distinct job.
I think chaplain also has specific stuff


fix that and im on board. i think the rest is ok like the gimmick roles and chef stuff since that'll be a skillchip

**Comment by Archanial** [comment]
git ban he
not funny didn't laugh

**Review by utilbird — CHANGES_REQUESTED** [review]
Remove job spawn landmarks

**Comment by TeomanTheGreat** [comment]
Your telling me that gitbans are handed out to off-topic comments but joke prs are alright? Mfw

**Comment by ghost** [comment]
speedmerge!

**Comment by ike709** [comment]
didn't laugh, try harder

**Pull request closed without merging**
