### PR TITLE
Nitryl gas reaction now uses pluoxium as a catalyst

### PR DESCRIPTION
**Pull request by Chessus**
## About The Pull Request
Replaces N20 with Pluoxium

## Why It's Good For The Game
N20 now decomposes rapidly when exposed to the temperature required for Nitryl to form. This change makes it possible to produce more than a mole of Nitryl without needing a Fusion canister on the station. Pluoxium as a catalyst does not decompose therefore the amount of Nitryl you create is equal to O and N2 moles. 

-Nitryl now is gated behind Pluoxium.

-I'd also suggest BZ as a catalyst. Would require less work to obtain than Pluoxium

## Changelog
:cl:
del: N2O removed as ingredient for Nitryl Gas
add: Added Pluoxium in place of N2O as Catalyst for Nitryl
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
that changelog is very undescriptive, doesnt inform the player of what actually happened in the game

**Comment by Chessus** [comment]
It's a one word line change I'm sure people can figure it out...

Edit: is that clearer?

**Comment by Fikou** [comment]
yeah thats epic

**Comment by MCterra10** [comment]
tgstation/tgstation#46900
Thanks for porting this, I clean forgot about it when I rebased

**Comment by Chessus** [comment]
Np daddy terra

**Comment by AgentStriker** [comment]
"makes it possible to produce more than a mole of Nitryl without needing a Fusion canister on the station."  But you dont need a fusion can to make nitryl....

**Comment by Chessus** [comment]
> "makes it possible to produce more than a mole of Nitryl without needing a Fusion canister on the station." But you dont need a fusion can to make nitryl....

That's true, though this change makes it easier to acquire more than single digit mole count of nitryl with an easier set up.

**Pull request merged**
