### PR TITLE
Sanity gradually moves towards a neutral state

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Makes sanity gradually move towards a neutral state, with speed varying depending on how low/high your sanity is.

I tweaked the speed so that it prevents you from losing more sanity without having a worse mood. Same applies for happiness, you won't love life because you took a shower anymore, but it's easier to be happy than it is to go insane.

To be more specific, you need _at least_ a mood of -18 to reach 0 sanity, and _at least_ a mood of 8 to reach maximum.

## Why It's Good For The Game
Bottoming out on sanity over very tiny moodlets is silly and honestly immersion breaking imo. It's ridiculous that taking a shower makes your mind a temple, or mild inconveniences make you go insane. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
Not really sure how to show it works, since the only testing videos I made are too big for github. I did test it though.

image

</details>

## Changelog
:cl:
tweak: Sanity constantly moves towards a neutral state.
tweak: Sanity change speed from mood is no longer capped. Extremely low moods will make you go insane extremely fast, and vice versa.
/:cl:

### CODE REVIEW

**Comment by tontyGH** [comment]
> It's ridiculous that taking a shower makes you love life

lies.

**Comment by WrillWasTaken** [comment]
> lies.

I took a shower in real life and did not immediately become the happiest I've ever been. 

Also that was a typo and I've fixed it.

**Comment by LodedDiper69** [comment]
No, we shouldn't reward people for totally ignoring their mood and hiding in their xenobio autism fort or whatever. We should instead try and make sanity actually matter, and give real consequences when it bottoms out. Here is my unofficial key 🔑

**Comment by WrillWasTaken** [comment]
> No, we shouldn't reward people for totally ignoring their mood and hiding in their xenobio autism fort

You will still go to low sanity and suffer slowdowns from hunger. If you want the effects to be more severe then I can tweak the numbers accordingly to allow lower sanity from hunger alone, but as it is currently you'll still suffer penalties for ignoring it entirely. Starving will also still make you reach _near_ minimum sanity.

> try and make sanity actually matter,

If we want sanity to matter, it has to be a more immersive and less frustrating system.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
