### PR TITLE
[MDB IGNORE] Deprecates Auxmos in favour of LINDA [PORT]

### PR DESCRIPTION
**Pull request by JixS4v**
## About The Pull Request

What it says on the tin. Crossed requested this.

Progress:

- [x] https://github.com/tgstation/tgstation/pull/55604
- [x] https://github.com/tgstation/tgstation/pull/56081
- [x] https://github.com/tgstation/tgstation/pull/56317
- [x] https://github.com/tgstation/tgstation/pull/56556
- [x] https://github.com/tgstation/tgstation/pull/57381
- [x] https://github.com/tgstation/tgstation/pull/57478
- [x] https://github.com/tgstation/tgstation/pull/57511
- [x] https://github.com/tgstation/tgstation/pull/57634
- [x] https://github.com/tgstation/tgstation/pull/57933
- [x] https://github.com/tgstation/tgstation/pull/58418
- [x] https://github.com/tgstation/tgstation/pull/58829
- [x] https://github.com/tgstation/tgstation/pull/59493
- [x] https://github.com/tgstation/tgstation/pull/60853
- [x] https://github.com/tgstation/tgstation/pull/60855
- [x] https://github.com/tgstation/tgstation/pull/61557
- [x] https://github.com/tgstation/tgstation/pull/61904
- [x] https://github.com/tgstation/tgstation/pull/62320
- [x] https://github.com/tgstation/tgstation/pull/63270
- [x] https://github.com/tgstation/tgstation/pull/63785
- [ ] https://github.com/tgstation/tgstation/pull/65591
- [ ] https://github.com/tgstation/tgstation/pull/69269
- [ ] https://github.com/tgstation/tgstation/pull/69479

Maints, feel free to add or remove PRs on this list to taste. Ping me on discord to request changes to the list otherwise.

Good news though, a lot of the work was in that initial commit.

Reverts https://github.com/BeeStation/BeeStation-Hornet/pull/8264/ (Sowwy bacon)
## Why It's Good For The Game

Auxmos? It's terrible. Just terrible. You know who's behind it? A real bad guy. Kicked out of Beestation! Can you believe it? Total loser!
And lemme tell you, it's causing us nothing but trouble. Big trouble. The biggest! But LINDA? Now that's a system. So good. The best system, maybe ever in the history of systems.
TG - smart people, very smart - they're handling LINDA. They know their stuff, not like those Auxmos bozos. Trust me.
We're gonna throw Auxmos in the garbage, folks. Toss it out like a rotten orange. And we're bringing in LINDA. It'll be amazing. So amazing. We'll fix atmospherics like you wouldn't believe!

## Testing Photographs and Procedure

<details>
Currently untested since it's a WIP
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
remove: auxmos
add: LINDA
/:cl:

### CODE REVIEW

**Comment by JixS4v** [comment]
It's normal that this is failing, it's literally less than half done

**Comment by JixS4v** [comment]
After the PR run is finished this still needs to actually be made to work
screaming-baby-made-of-ash-v0-6740zeldjc6c1

**Comment by JixS4v** [comment]
wtf how is this shit not failing checks, this is the worst code ever

**Comment by JixS4v** [comment]
Got some good work done today, errors are down to around 200, from 700 just today

**Comment by JixS4v** [comment]
This has been sitting for a while due to me going on vacation, work should resume on and off through the second half of August and September

**Comment by JixS4v** [comment]
At only a measly 81 problems, it's time to introduce more.

**Comment by JixS4v** [comment]
image

https://github.com/user-attachments/assets/c04d5511-625c-4797-8c71-2b55ee43a4e8

**Comment by JixS4v** [comment]
got too fucking greedy, never cherrypicking big PRs again

**Comment by JixS4v** [comment]
Aand we come to a new development pause™  for at least a week.

**Comment by JixS4v** [comment]
Ratón is doing some good work but there's a good bit remaining

**Comment by JixS4v** [comment]
Ripped out all the auxmos related scripts

**Comment by JixS4v** [comment]
Also it compiles

**Comment by JixS4v** [comment]
PR porting is halted till I get rid of most runtimes

**Comment by JixS4v** [comment]
Progress is actually coming pretty smoothly. Need to fix all the bullshit with tanks I probably misported.

**Comment by JixS4v** [comment]
So apparently the atmosphere isn't breathable I probably broke something ngl

**Comment by JixS4v** [comment]
:(

**Comment by JixS4v** [comment]
Development will probably slow down from this point on. Uni is starting again and I won't be able to dedicate as much time to this PR.

**Comment by JixS4v** [comment]
Seriously

**Comment by JixS4v** [comment]
It's not fucking compiling for some reason

**Comment by JixS4v** [comment]
Seriously

**Comment by Nakalon** [comment]
Wait, will you be the man to dust auxmos? the fuck? are you jesus?

**Comment by EvilDragonfiend** [comment]
mapping is killing this guy, I suppose.

**Comment by EvilDragonfiend** [comment]
image

You need to check the error details.

**Comment by JixS4v** [comment]
> image
> 
> You need to check the error details.

I know about this yeah. I haven't had time to get to this. These are trivial to deal with anyways

**Comment by JixS4v** [comment]
> mapping is killing this guy, I suppose.

Barely, everytime a mapping PR gets merged I weep a little

**Comment by XeonMations** [comment]
Not on my watch you dont, bot!

**Pull request closed without merging**
