### PR TITLE
Exempt Fusion From Hotspot Reaction

### PR DESCRIPTION
**Pull request by park66665**
## About The Pull Request

Hotspot effect is great. It contributes to faster open turf fire, and it creates... fire-like graphics. But it fucks quite a lot with fusion, because the hotspot might try to call fusion (via react proc) on a _part_ (via remove_ratio proc) of an open turf's gasmixture and fusion doesn't act very cooperative with it. This PR fixes it by simply exempting fusion from called by hotspot.

Screenshot 2020-10-06 200252
_This graph shows what this PR tries to fix_

## Why It's Good For The Game

A tiny bit less jitteriness at fusion.

## Changelog
:cl:
tweak: fusion is no longer caused by hotspot react()
fix: fire probably became a tiny tiny bit faster
/:cl:

### CODE REVIEW

**Comment by park66665** [comment]
After a discussion with an atmos coder from another codebase I am considering a solution that's quite different than this one. I will turn this PR into a draft.

**Comment by park66665** [comment]
tgstation/tgstation#54213 is horribly stuck at this moment, I will go to a quick fix option instead and un-draft it.

**Comment by zeskorion** [comment]
is this pr ready

**Comment by park66665** [comment]
The PR is ready.

**Comment by PowerfulBacon** [comment]
Testmerging onto sage

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
