### PR TITLE
Fabrications Rebalance

### PR DESCRIPTION
**Pull request by francinum**
## About The Pull Request

Remind me to rewrite this at not-3am

The Ore Silo has been made adminspawn only
The department techfabs have been made adminspawn only
Science has been given back it's full access protolathe
Science has been given back it's full access circuit printer

## Why It's Good For The Game

Encourages departmental interaction and cooperation through tying of production chain.

Talk to eachother holy shit.

## Changelog
:cl:
add:stuff
del:stuff
balance:fuck
tweak:holy shit yes
/:cl:
bitch at me to write a better changelog tomorrow

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I have a feeling nobody is going to like this, its so much easier to add convenience than to take it away, and building anything is already painful enough without having to run down to science 3 times instead of popping into the engie window.
I like the interaction between science and mining that will be forced from this, but literally everything else other than this seems like it would be awful in game.
Science can now make everything and gets all the power making science traitor super easy since you can make as many guns as you like as long as you have a mindshield.
Roboticists can now make their powergaming mechs without cooperation from security.
Engineers can no longer build basically anything without walking all the way to science and back, since the maps are not well designed for this at all.
Medbay the changes aren't too bad since they dont need the lathe as often and can stock up.
The only thing I can see coming from this is science or everyone else opening a big hole in the side of science so anyone can use the lathe, resulting in all access to restricted items like printable guns, less communication since you just got to let people in since rather than asking to have stuff its 10x more worth it to just let them do it themselves and an immense amount of pain for engineers making expansion of the station or coinstruction of anything fun near impossible.

**Comment by Archanial** [comment]
holy shit this is belone tier pr

**Comment by bloons3** [comment]
> Science can now make everything and gets all the power making science traitor super easy since you can make as many guns as you like as long as you have a mindshield.
> Roboticists can now make their powergaming mechs without cooperation from security.

I'm actually kinda concerned about this. Security being physically hard to get into is what helps STOP guns from being proliferated across the station. We already have issues with Robotics arming up their mechs and being nuisances with them. I can't wait for Robotics to start loading missile racks with no one in security being the wiser.

Considering how easy it would be to purchase unrestricted firing pins from cargo, then print a gun from Science, this would really encourage tiding and powergaming.

**Comment by ghost** [comment]
Did everyone forget the game used to be like this? And it was perfectly fine.

**Comment by St0rmC4st3r** [comment]
> Did everyone forget the game used to be like this?

Old != Good

**Comment by ghost** [comment]
> > Did everyone forget the game used to be like this?
> 
> Old != Good

In this case it was a superior system.

**Comment by francinum** [comment]
@St0rmC4st3r News is not necessarily any better.

Just ask TG.

**Comment by B4CKU** [comment]
god tier pr, but i think that ore silo should be eventually researchable, just really expensive and should really be a lategame thing

**Pull request closed without merging**
