### PR TITLE
No roundstart alarm

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Removes the roundstart communication intercepted.
## Why It's Good For The Game

It makes blue alert redundant, and also confuses people into thinking the messages actually mean something and blatantly encourages metagaming, it would be overall better if they weren't there.

## Changelog
:cl:
tweak: You will no longer intercept communications.
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
> disabling something so ubiquitous and commonplace it is taken for granted, disrespecting the entirety of the game

100% support

**Comment by PowerfulBacon** [comment]
Personally, I think it would be better if it was a probability of being intercepted and the other chance of just staying on green alert until command raises it.

**Comment by ike709** [comment]
They do actually mean something. There's a 65% chance that the actual gamemode is included in the report.

It also reports the flavor of dynamic if it's dynamic, or extended if it's extended.

And it includes the station goals.

**Comment by ghost** [comment]
> They do actually mean something. There's a 65% chance that the actual gamemode is included in the report.
> 
> It also reports the flavor of dynamic if it's dynamic, or extended if it's extended.
> 
> And it includes the station goals.

you act like station goals are ever done, if someone would truly want to make them they could just check a supply console.

**Comment by ike709** [comment]
> ignoring the other points

**Comment by eeSPee** [comment]
Idea: make it conditional? 

My idea is to make it only appear if pop>50. There's a lot of people to check and hipop rounds can be chaotic and hard for sec to manage.

**Comment by Crossedfall** [comment]
Repo/Branch was removed and this isn't a popular feature. Closing.

**Pull request closed without merging**
