### PR TITLE
Fixes Particle Accelerators being unable to activate tesla/singulo engine.

### LINKED ISSUE #9887: [Bug]: Tesla Generator - Particle Accelerator doesn't work
### BYOND Version

515.1613

### Round Date

2023/09/24

### Round ID

45977

### Test merges

- #9124 
- #9845 

### Describe the bug

-> Build tesla as i always do
-> I fire the particle accelerator
-> I make sure everything works and particles went through the generator
-> Tesla doesn't produce anything even if i wait 20 minutes
-> This is the tesla that i build, it was a working build until recently.
Screenshot 2023-09-24 at 17 45 24
Screenshot 2023-09-24 at 17 46 07

### What did you expect?

I expected to get a tesla 

### Reproducible steps

1. Build Tesla
2. Run it
3. It doesn't work

### PR DESCRIPTION
**Pull request by HowToLoLu**
## About The Pull Request

Fixes #9887

This fixes a bug that prevented players from making singulos/teslaballs, due to some bad projectile code. So I touched it up and made it so that Piercing behaviour comes before Phasing behaviour- since they're identical but one hits and the other doesn't.

So now the game will try to hit something while passing through before doing nothing while passing through.

```dm
projectile_piercing = PASSMOB | PASSANOMALY | PASSMACHINE
projectile_phasing = (ALL & (~PASSBLOB))
```
as opposed to 
```dm
projectile_piercing = PASSMOB | PASSANOMALY | PASSMACHINE
projectile_phasing = (ALL & (~PASSMOB) & (~PASSBLOB) & (~PASSANOMALY) & (~PASSMACHINE))
```

## Why It's Good For The Game

Touches up some bad code behaviour so that's it's less so, *and* fixes a feature that is supposed to work.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/35765038-00ea-4d62-afb3-cce28adc2eb3

https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/db4f7064-3bbf-4cf3-92e6-09a59f48a344

https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/0e66211f-9b69-45f9-9f31-ba11d170d979

https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/852038f6-6cb1-412b-8643-bc88e293d71d

Also touched the sniper penetrating rounds while cleaning up too- so here's evidence that it still works:

https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/45176f65-134a-4c84-97cf-7d5670942893

</details>

## Changelog
:cl:
fix: The Particles shot out of the Particle Accelerator no longer phase through machines
code: In Projectiles, Piercing behaviour is now prioritized over Phasing behaviour (the difference between the two is whether it deals damage as it's passing through)
/:cl:

### CODE REVIEW

**Review by itsmeow — APPROVED** [review]
I had no idea this was even broken

**Comment by PowerfulBacon** [comment]
Not sure how I feel about the solution, I feel like the phasing flag should have more emphasis than the peircing one, since if something has piercing: ALL and phasing: ALL, then it should phase through things rather than peirce them. This could lead to some knock on effects.

Either way the projectiles need to be configured such that their piercing and phasing don't overlap, otherwise its going to lead to confusing. The sniper rifle shouldn't have ALL on both otherwise it will be confusing as to which one should act.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Projectiles need to maintain an xor property between phasing and piercing, we don't want a flag enabled on both of them as this leads to confusion as to whether the projectile will pierce or phase when reading the code.

**Comment by HowToLoLu** [comment]
> Projectiles need to maintain an xor property between phasing and piercing, we don't want a flag enabled on both of them as this leads to confusion as to whether the projectile will pierce or phase when reading the code.

Unfortunately when #9700 was ported it introduced a new flag that posed a problem to this logic since it's by default on all machines. You'd have to memorize that this flag exists in certain niche scenarios which doesn't seem like a great way to do it, for example all machines have it by default. In addition it's vague and you wouldn't be easily able to tell what has it in the future, given the name is `LETCLICKPASS`

**Comment by HowToLoLu** [comment]
Which could mean that you'd have to keep track of everything that has `LEFTCLICKPASS`, and if more of these technical flags are added you have to go back and know where to add them because it breaks potentially breaks phase first XOR logic. 

As for the confusion, we could just add a comment describing the behaviour since I don't think it's actually described at all currently.

**Comment by HowToLoLu** [comment]
Perhaps I can make it so the code can get a list of technical pass flags like `LETPASSCLICKS` and have that automatically be canceled out? The only reason I didn.t do it earlier is because it felt like it was going to make this harder to maintain.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
