### PR TITLE
[TG PORT] New titanium tile sprite and titanium tile reskinning

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

- Using titanium tile in hand allows you to change the color and type
- Doesn't replace default titanium sprite with new sleek 'alt' sprite because it looks bad on most shuttles
- Variant floors will produce their own floor tile when crowbared
- Removes `icon_regular_floor` in favor of `base_icon_state` (we don't use this nearly as much in bee but it still appears to be convention
- Adds object path keys to radials
- Adds a generic tile reskinning system via `tile_reskin_types` var on `/obj/item/stack/tile`

Port of https://github.com/tgstation/tgstation/pull/54184 and https://github.com/tgstation/tgstation/pull/54233

Credit to https://github.com/tgstation/tgstation/pull/53154 for changes to radial code that allow https://github.com/tgstation/tgstation/pull/54233 to work

## Why It's Good For The Game

Can make cool gaming floors now on shuttles or construction projects

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image

image

image

No longer affects existing tiles

</details>

## Changelog
:cl:
add: The ability to change what type of titanium floor tiles you wish to place via shift-clicking your stack of titanium floor tiles.
add: New smooth titanium floor sprite as an option
code: Added object path keys to radials
code: Added generic tile reskinning system
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
image

This looks disgusting and should default to the original tile

**Comment by itsmeow** [comment]
Fixed that, I agree just wasn't sure since upstream already had this as the default

**Comment by PowerfulBacon** [comment]
> Fixed that, I agree just wasn't sure since upstream already had this as the default
> 
> Screenshot of it restored to its former glory
> 
> image

What happened to the corner decals though? They seem to be missing in the second screenshot.

**Comment by PowerfulBacon** [comment]
image

**Comment by itsmeow** [comment]
Not sure, I think that's a mapping issue though with the decals having improper heights or something, this code doesn't touch decals at all, it only changes the icons of the tiles

**Comment by itsmeow** [comment]
image

New screenshot, appears just fine. Seems to just be a random issue

**Comment by itsmeow** [comment]
GTM

**Comment by itsmeow** [comment]
Been two weeks, just needs a basic review. Still GTM

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
