### PR TITLE
Ports "Shotguns blow people away at point blank"

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Original PR: https://github.com/tgstation/tgstation/pull/47443
Also ports part of https://github.com/tgstation/tgstation/pull/48268 related to guns

## Why It's Good For The Game

Another thing off the list

## Changelog
:cl:
add: Shotguns now blow people away at point blank.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
HERE I GO KILLING

**Comment by TeomanTheGreat** [comment]
Ah yes shotguns are now more op at close quarters

**Comment by ghost** [comment]
> Ah yes shotguns are now more op at close quarters

they are supposed to be.

**Comment by Archanial** [comment]
> 
> 
> Ah yes shotguns are now more op at close quarters

You need to be tile next to someone and click on them to blow them away.
If anything this is a nerf since it would be easier to escape or hide behind something.
But you would be probably in crit anyway if you took all the pellets so does it really matter?

**Comment by Isy232** [comment]
This is epic, its also not really a buff as if you shoot them away it makes a follow up shot harder, unless if you shoot them into a wall stunning them.

**Comment by ghost** [comment]
what mobs does this effect?

**Comment by Archanial** [comment]
All mobs

**Review by zeskorion — APPROVED** [review]

**Pull request merged**
