### PR TITLE
Removes hulk from genetics.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

title

## Why It's Good For The Game

Stun immunity in a combat system based around stuns is a bad idea.
## Changelog
:cl:
del: Removes hulk from genetics.
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
this dude got killed by hulk

**Comment by ghost** [comment]
> this dude got killed by hulk

never

**Comment by Effemu** [comment]
bilary meeting his daily quota of bad prs be like

**Comment by TeomanTheGreat** [comment]
Remove xray instead

**Comment by PowerfulBacon** [comment]
This doesn't even remove it from genetics though is the funny thing

**Comment by ghost** [comment]
grug brain

**Pull request closed without merging**
