### PR TITLE
Update science_outpost.dmm

### PR DESCRIPTION
**Pull request by Antops12**
## About The Pull Request

changes the design of the science cargo shuttle

## Why It's Good For The Game
The original science shuttle design was bad imo. I believe that every time someone used the shuttle, they ended up breaking or dismantling the windows to reach the other side.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image

</details>

## Changelog
:cl:
tweak: designed science cargo shuttle
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
Why the extra air canister?

**Comment by Antops12** [comment]
I have no idea

**Comment by Rustyfoxb** [comment]
The door is really nice, now i don't have to break a wall down each time i want to use it.

**Comment by Antops12** [comment]
which is why this needs to be done

**Comment by itsmeow** [comment]
Removes moth plush soul.
Also I don't like the way the wall stretches. Maybe move the door to the edge and then have 3 windows?
or
DOOR
WALL
WINDOW
WALL

**Comment by Antops12** [comment]
image
eh

**Comment by Antops12** [comment]
image
this seems better

**Comment by itsmeow** [comment]
Add back the moth plush :(

**Comment by itsmeow** [comment]
If you're gonna go with two doors, might as well just put two windows instead of walls so you can still see the back.

**Comment by Antops12** [comment]
alright, thanks for your suggestions
Please note the doors are glass doors

**Comment by MarkusLarsson421** [comment]
I like the first image where the door is to the right, beside the APC. As you don't want to block neither the APC or door. And it creates a nice area where you can have several machines, lockers, tables or otherwise around the 3x3 in the bottom left of the shuttle.

**Review by itsmeow — APPROVED** [review]
Good enough for now. if you wanted to tweak it more the doors imo are still a little weird looking but we can just go with this

**Pull request merged**
