### PR TITLE
New implant case sprites

### PR DESCRIPTION
**Pull request by PestoVerde322**
## About The Pull Request
This pull requests adds new implant cases and implanter syringes sprites made by AmiTech on the Beestation Discord channel.

## Why It's Good For The Game

Old 45° devsprites bad, new 3/4 sprites good.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

New icons

</details>

## Changelog
:cl:
add: Added new implants and implanter sprites by AmiTech.
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
image

**Comment by FriendlyContractor** [comment]
In my humble opinion they look worse than existing ones

**Review by Archanial — APPROVED** [review]

**Comment by RDS88-beeman** [comment]
my prime concern is that, at a glance, the implanter looks too close to a syringe, and could probably do with a darkening

**Comment by williamcll** [comment]
> my prime concern is that, at a glance, the implanter looks too close to a syringe, and could probably do with a darkening

It should be the other way around, let us put implanters in syringe guns.

**Comment by Wilchenx** [comment]
image

**Pull request closed without merging**
