### PR TITLE
Revert "Changes the description of the Hotdog to something a bit more ontopic"

### PR DESCRIPTION
**Pull request by Archanial**
Reverts BeeStation/BeeStation-Hornet#4992

### CODE REVIEW

**Comment by KubeRoot** [comment]
How dare you.

**Comment by Urumasi** [comment]
ided PR

**Comment by MNarath1** [comment]
oh god so much colors ahhh

**Comment by KubeRoot** [comment]
Thanks for adding the DO NOT MERGE label. I appreciate you clearing up your intentions in regard to this change and wholeheartedly agree this issue requires much more discussion.

**Comment by AnCopper** [comment]
tenor

**Comment by KubeRoot** [comment]
image
😢

**Comment by Urumasi** [comment]
ike bipolar

**Comment by mcmeiler** [comment]
1984

**Comment by R3pID** [comment]
unwholesome chungus

**Comment by francinum** [comment]
In a year nobody is going to actually notice or care.

This is arguably how you do a half decent joke PR.
🔑

**Comment by Sinestia** [comment]
Fetish content

**Comment by francinum** [comment]
Actually as of right now you're literally turning it into a reference that violates our rules.
Fetish content.
francgun

**Pull request closed without merging**
