### PR TITLE
operating computer uses alldirs

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports:
- https://github.com/Monkestation/MonkeStation/pull/630

## About The Pull Request
The operating computer only used the cardinal directions for finding its table, so this changes it so it uses the other inter-cardinal directions so you layout the operating and stasis tables in different orientations around them on maps.

## Why It's Good For The Game
More options for operation layouts

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: DoctorSquishy, RKz
tweak: Operating Computers placed NE,NW,SE,SW from operating tables can find the table now
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
It's done like this on purpose

**Comment by itsmeow** [comment]
Why is your CL crediting other people for this change?

**Comment by Tsar-Salat** [comment]
> Why is your CL crediting other people for this change?

apologies, it is a port. Included in the pr body now

**Review by itsmeow — APPROVED** [review]
Looks fine, I have no problem with this since it allows you to have a computer facing you on the diagonal, which makes sense that you could see it. "It's done like that for a reason" (what is said reason, and why does it matter)

I don't see a reason *not* to have this, MAYBE someone could put one behind a wall in the way and it would be a bit weird, but the chances of this are kinda low

**Comment by Tsar-Salat** [comment]
image

**Review by Penwin0 — APPROVED** [review]

**Pull request merged**
