### PR TITLE
Punch damage is now consistent

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
living/carbon/humans always deal their punch damage (default is 6) when attacking mobs. there is no knockdown, no extraneous effects. just your damage
pacifists can no longer attack aliens
bees have lower hp, letting you still punch them in one hit (why the FUCK did they have 10 anyways)

## Why It's Good For The Game
the damage you deal with your unarmed strikes is now consistent. This also allows races- or, with kapulimbs becoming a factor- limbs with their own special punchdamage- to deal their damage consistently as a weapon even against non-human mobs.
also, humans having a 10% chance to knock a xenomorph out with a punch is stupid

## Changelog
:cl:
tweak: humans always deal normal punch damage to mobs, instead of having weird damage calcs depending on the mob subtype
tweak: attacking borgs with a punch that deals over 10 damage damages them
balance: bees now have 6 hp
fix: pacifists can no longer attack aliens
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
(modifies a map due to the fact a mob has a specially defined harm intent damage somewhere on metastation?)

**Comment by Mat05usz** [comment]
> (modifies a map due to the fact a mob has a specially defined harm intent damage somewhere on metastation?)

It's the HoS's spooder, but why was it done like this idk, maybe so prisoners can't kill it so easily, doesn't really matter.

**Comment by BrumalLake** [comment]
huge sergeant araneus nerf

**Comment by francinum** [comment]
Incomplete PR body.

**Comment by zeskorion** [comment]
> Incomplete PR body.

fixed

**Comment by francinum** [comment]
Atomize out `fix: pacifists can no longer attack aliens` into it's own PR.

**Comment by francinum** [comment]
Okay no, after looking at this again the existing code is hot fucking garbage and this isn't about randomness, outside of xenos.
It's about the fact that simplemob code fucking sucks.

Ideally you'd have atomized it in the first place, but I'm fine with just throwing this in.

**Review by francinum — APPROVED** [review]

**Review by Archanial — APPROVED** [review]

**Pull request merged**
