### PR TITLE
Improve TGUI ui_data sleeping + Cache metabalance locally

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

When the player panel was closed, it would sometimes trigger a bluescreen with "config" being null. This was caused by get_payload runtiming with `null.tgui_shared_states`. This is a really patch on fix for src_object randomly becoming null in the middle of this proc. ~~I'm not sure why or how, but it does indeed fix the bug.~~

~~My guess is it's a race condition caused by a ui_act from the search bar when it's closed, since it gets unfocused and then updates the text inside. This action message is sent at the same time the suspend message is sent, meaning two concurrent executions of ui updating and ui closing occur. This means that while the UI is closing, it's building a message to be sent, and then the UI finishes closing and sets src_object to null, causing said runtime. I'm not sure how or why, or how to properly fix this, but this solution works well enough that I'm just gonna leave it there and hope TG fixes it upstream or something. I did search for related PRs or changes but found nothing of the sort.~~

If ui_static_data or ui_data sleep at all, they can become null during the proc, so this should be handled.

ui_data and ui_static_data now also enforce SHOULD_NOT_SLEEP. In order to meet this I added a local metabalance cache, but it's only used for display purposes and not involved in balance calculations. Admins also cannot edit it.

Antag tokens were also cached locally.

Fixes a bug where you can only purchase items that are less than your metabalance rather than less than or equal to.

## Why It's Good For The Game

Fixes a bug

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image

image

image

image

image

image

</details>

## Changelog
:cl:
fix: Fixed admin player panel bluescreening/runtiming when closed.
tweak: Metabalance is now cached on the player's client datum to reduce database use.
fix: You can now purchase items that cost exactly your metabalance.
tweak: Antag token count is now cached on the player's client datum to reduce database use.
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Make ui_static_data and ui_data have `SHOULD_NOT_SLEEP(TRUE)`

**Comment by PowerfulBacon** [comment]
also surely that would only cause issues if they have `set waitfor = FALSE` in them?

**Comment by itsmeow** [comment]
> Make ui_static_data and ui_data have `SHOULD_NOT_SLEEP(TRUE)`

They are allowed to sleep, it just needs to handle the case. I looked over with that enabled and there's only two sleepers, they're both not really important and easier if they do sleep

**Comment by itsmeow** [comment]
> also surely that would only cause issues if they have `set waitfor = FALSE` in them? Or is this because of a javascript side request timing out instead of a byond function returning null due to a sleep?

It's because in the time where it's waiting the ui is deleted (due to being closed)

**Comment by itsmeow** [comment]
web or db request as part of its data. in the player panel case it's that metacurrency isn't cached locally. it's not exactly valid but it's useful enough to keep around or at least handle the case

**Comment by PowerfulBacon** [comment]
I guess for anything where you send a request to the server and expect a response back, like getting the data for a specific user when pressed and TGUI admitadly doesn't seem to be very good when supporting communication patterns like that. In ui_static_data I could see it being somewhat userful but use ui_data seems like it could just easilly result in unresponsive UIs and is a slight indicative of something funny in the code. For something like this, I feel like it might be better to be on the side of caution just to protect coders from doing something like making an SQL request every single ui update but I do see that specific use case.

**Review by PowerfulBacon — APPROVED** [review]

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
