### PR TITLE
Giving items shortcut

### PR DESCRIPTION
**Pull request by yorii**
## About The Pull Request

Ported from https://github.com/tgstation/tgstation/pull/50710

Just a keyboard shortcut (G) to quickly offer the item in hand to the person nearest to you.

## Why It's Good For The Game

Uses onscreen alerts instead of a window popup, might be reasonable to also change the old style item giving to a similar? Or should I perhaps change this to also be a classic popup?

## Changelog
:cl:
add: added item giving to keyboard shortcut G.
/:cl:

### CODE REVIEW

**Comment by axpov** [comment]
How would this affect people who already have G bound to something? Would it be a duplicate or just not bound?

**Comment by axpov** [comment]
Also the old way should definitely be converted to this way (in this pr too), the onscreen alert is way better than the popup

**Comment by yorii** [comment]
> How would this affect people who already have G bound to something? Would it be a duplicate or just not bound?

It would probably duplicate, but as far as I know there has never been any default bind to G, so it seemed like a nonproblematic choice.

> Also the old way should definitely be converted to this way (in this pr too), the onscreen alert is way better than the popup

That can be arranged :)

**Comment by yorii** [comment]
Oh shit, I accidentally PR'ed this from my master branch lol

**Comment by yorii** [comment]
Hmm.. I need to close and reopen this if I want to change the branch?

**Comment by ivanmixo** [comment]
This PR literally does not do anything, I suggest closing and opening a new one with the correct branch.

**Comment by PowerfulBacon** [comment]
0 changes PR

**Comment by zeskorion** [comment]
merging from master, wrong change.

**Pull request closed without merging**
