### PR TITLE
More Detective Office ambience

### PR DESCRIPTION
**Pull request by Raven-Industries**
## About The Pull Request

This adds 2 new tracks for the detective's office ambience, and updates the relevant portions of the licensing and area info to accommodate the addition. The two tracks are excerpts from Kevin Macleod's "Cool Vibes" and "I Knew a Guy", both licensed under [CC-BY 4.0](http://creativecommons.org/licenses/by/4.0/), and compatible with the [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/) license used by Beestation assets. 

## Why It's Good For The Game

Increases hardboiledness by 100% and gives detective players a bit more variety in tunes as they drown their sorrows in drink and/or candy corns. 

## Changelog
:cl:
soundadd: adds 2 new ambience tracks for detective's office
/:cl:

### CODE REVIEW

**Comment by That0nePerson** [comment]
[Cool Vibes](https://www.youtube.com/watch?v=GY398jlSJmg&ab_channel=EricArchive) and [I Knew a Guy](https://www.youtube.com/watch?v=MTkAwk6mnD0&ab_channel=EricArchive)

both are good and seem fitting

**Comment by OceanFish1** [comment]
This is good

**Comment by ike709** [comment]
Technically we're supposed to provide a link to the license. Could you include that at the top of the file as well as a link to CC BY 3.0 while you're at it?

**Comment by ike709** [comment]
Actually, the songs seem to be 3.0 not 4.0

**Comment by Raven-Industries** [comment]
> Technically we're supposed to provide a link to the license. Could you include that at the top of the file as well as a link to CC BY 3.0 while you're at it?

Do you mean include a link in the license.txt file? 


> Actually, the songs seem to be 3.0 not 4.0

They're listed as under 4.0 on Macleod's website, so I don't know what's up with that.

**Comment by ike709** [comment]
> Do you mean include a link in the license.txt file?

Yes. 

> They're listed as under 4.0 on Macleod's website, so I don't know what's up with that.

Site clearly says 3.0

**Comment by Raven-Industries** [comment]
I've updated the license.txt file to include links to the licenses for both the new files and all the old ones that didn't have them for some reason. I don't know if we're looking at different versions of the same website or something, because I'm 99% sure it's a 4.0 license for the new tracks: 
license

**Comment by ike709** [comment]
image

**Comment by Raven-Industries** [comment]
I have no idea what's up with that, but I'll go ahead and change it to 3.0.

**Review by ike709 — APPROVED** [review]

**Comment by theboy6545** [comment]
Could you just have it under both to avoid lawyers?

**Comment by Raven-Industries** [comment]
> Could you just have it under both to avoid lawyers?

I'm not sure if you're able to list something under 2 different licenses at once. After slogging through a few pages of legalese on the differences between CC-BY 3.0 and 4.0, I'm pretty sure we should be in the clear (and a lawyer would have to be insane and/or truly desperate to go after something as miniscule as this), but I'm not a lawyer and this is not a substitute for legal advice, so grain of salt and all that.

**Review by qwertyquerty — CHANGES_REQUESTED** [review]
If these are fullout songs they should use ambient_music not ambient_effects

**Comment by Raven-Industries** [comment]
> If these are fullout songs they should use ambient_music not ambient_effects

They aren't full songs, just 30 to 35 second long excerpts, in line with the other 2 tracks currently used for detective office ambient effects.

**Review by qwertyquerty — APPROVED** [review]

**Pull request merged**
