### PR TITLE
[PORT] Lesser Summon Bees

### PR DESCRIPTION
**Pull request by Howluinb**
## About The Pull Request

Add a new Wizard spell : Lesser Summon Bees, which summons a horde of bees hostile to EVERYBODY.
https://github.com/tgstation/tgstation/pull/53297

## Why It's Good For The Game

We're named beestation, and we don't even have a spell to summon bees. Also it's hilarious.

## Changelog
:cl: ghost
add: New Wizard Spell : Lesser Summon Bees.
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
Combining the worst antagonist with one of the worst features in this game.

**Comment by Howluinb** [comment]
> 
> 
> Combining the best antagonist with one of the best features in this game.

ftfy

**Comment by DrMacCool** [comment]
[Do I even need to say it?](https://www.youtube.com/watch?v=PYtXuBN1Hvc)

**Comment by Archanial** [comment]
Ghost is a nickname for github users that deleted their accounts so you probably don't need to credit him.

**Review by Archanial — APPROVED** [review]

**Pull request merged**
