### PR TITLE
Actually for sure fix roundstart surgery computer linking this time

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

This actually fixes roundstart surgery computer linking, because before it was broken due to... idk how to explain it. Shenanigans.

## Why It's Good For The Game

aagagagagh bug bad

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

23-07-21-1689921850-dreamseeker

</details>

## Changelog
:cl:
fix: Actually, for sure this time, fixed linking roundstart surgery computers.
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
How does LateInitialize not work?

**Comment by Absolucy** [comment]
No clue, but it doesn't. I just want it to work.

**Comment by Absolucy** [comment]
Alright, back to using LateInitialize, but this time it actually works!

23-07-21-1689921850-dreamseeker

**Review by Rukofamicom — APPROVED** [review]

**Review by itsmeow — APPROVED** [review]
two way reference moment

**Pull request merged**
