### PR TITLE
Lower BZ on lavaland

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Lowers the amount of BZ on lavaland to 1% of original amount. Instead of cargo making millions of credits for a few minutes of gas mining once it's setup, they will now make only tens of thousands of credits for the same amount of effort.

## Why It's Good For The Game

Cargo department will no longer trivialize economy by making millions of credits with minimal setup at start of round.

## Changelog
:cl:
balance: lowered BZ on lavaland to 1% of previous amount
/:cl:

### CODE REVIEW

**Comment by pickleinjar** [comment]
just no

**Comment by PowerfulBacon** [comment]
doesn't this make lavaland relatively safe to go out without internals? 
Actually its random anyway, so it will be only sometimes

**Comment by ghost** [comment]
> doesn't this make lavaland relatively safe to go out without internals?

It is never safe as there is always a high percentage of co2 on lavaland, which is what knocks you out after seconds.

**Comment by Effemu** [comment]
cargo barely ever uses bz to make money

**Comment by FortSumter** [comment]
Personally, I'd have you remove BZ completely from lavaland. I don't see why it exists there besides for cargo to gamer it. You can argue for lings, but we already removed concentrated BZ, and no ones going to flood the station with normal BZ unless they want to be lynched.

**Comment by Effemu** [comment]
> 
> 
> Personally, I'd have you remove BZ completely from lavaland. I don't see why it exists there besides for cargo to gamer it. You can argue for lings, but we already removed concentrated BZ, and no ones going to flood the station with normal BZ unless they want to be lynched.

i think it also exists so some lavaland roles and non miners dont steamroll the whole map without internals

**Comment by ItsTisme** [comment]
A note also that lavaland air is alot hotter then normal atmos which means it will do burn damage over time, also the CO2, plasma and much lower levels of O2

**Comment by Sinestia** [comment]
> cargo barely ever uses bz to make money

you what



> Personally, I'd have you remove BZ completely from lavaland. I don't see why it exists there besides for cargo to gamer it. You can argue for lings, but we already removed concentrated BZ, and no ones going to flood the station with normal BZ unless they want to be lynched.

Flavor?

**Comment by Sinestia** [comment]
Anyways, is there enough per tile to cause the effects?

if not it might be better to do a more moderate change and include elasticity for gasses

**Comment by ghost** [comment]
> Anyways, is there enough per tile to cause the effects?
> 
> if not it might be better to do a more moderate change and include elasticity for gasses

What do you mean cause the effects? Even without this change, atmosphere on lavaland is over 20% co2, if you breathe on lavaland without internals the first thing to happen is you get knocked out and never wake up.

These aren't guaranteed gases.

**Comment by Ohagi-Chan** [comment]
> > Anyways, is there enough per tile to cause the effects?
> > if not it might be better to do a more moderate change and include elasticity for gasses
> 
> What do you mean cause the effects? Even without this change, atmosphere on lavaland is over 20% co2, if you breathe on lavaland without internals the first thing to happen is you get knocked out and never wake up.
> 
> These aren't guaranteed gases.

What they mean is you didn't do your homework.
BZ requires at least 1pp to induce the effects, as can be seen at the top of the definition of lungs.
https://github.com/BeeStation/BeeStation-Hornet/blob/518af87a0bf9b3859cdd2ab7aa34c03dc35c8a69/code/modules/surgery/organs/lungs.dm

0.1pp of BZ is functionally ignored by lungs that don't have  BZ_trip_balls_min set to less than 0.1 (spoiler, there are none set that low).

**Comment by ghost** [comment]
> What they mean is you didn't do your homework.
> BZ requires at least 1pp to induce the effects, as can be seen at the top of the definition of lungs.
> https://github.com/BeeStation/BeeStation-Hornet/blob/518af87a0bf9b3859cdd2ab7aa34c03dc35c8a69/code/modules/surgery/organs/lungs.dm
> 
> 0.1pp of BZ is functionally ignored by lungs that don't have BZ_trip_balls_min set to less than 0.1 (spoiler, there are none set that low).

You can't survive breathing lavaland atmosphere with the heavy co2 concentration, whatever effect BZ has at whichever concentration is purely cosmetic as you die anyway, it's not even guaranteed to spawn on lavaland.

**Comment by Ohagi-Chan** [comment]
Ever used cybernetic lungs? 10pp CO2 is no problem whatsoever.
It won't kill the average person instantaneously either, just quickly.

**Comment by utilbird** [comment]
> Ever used cybernetic lungs? 10pp CO2 is no problem whatsoever.
It won't kill the average person instantaneously either, just quickly.

Lucky no one starts with cybernetic lungs, if someone gets them so they can breathe lavaland atmos, I don't see any problem with that.

It's way more work than just using internals

**Comment by utilbird** [comment]
> Cargo department will no longer trivialize economy by making millions of credits with minimal setup at start of round.

If that's your intention, why not just lower the value of BZ? It's not like atmos techs make any for cargo

**Comment by Sinestia** [comment]
> 
> 
> > Cargo department will no longer trivialize economy by making millions of credits with minimal setup at start of round.
> 
> If that's your intention, why not just lower the value of BZ? It's not like atmos techs make any for cargo

It'd be a one-line copy paste to port elasticity for gasses from /tg/ unironically, would be very simple for someone to do

edit: actually slightly more I was mistaken and it'll require changing for our atmos [but yeah](https://github.com/tgstation/tgstation/pull/55192/files) 


EDIT 2: https://github.com/BeeStation/BeeStation-Hornet/pull/3504 done

**Comment by ghost** [comment]
> If that's your intention, why not just lower the value of BZ? It's not like atmos techs make any for cargo

It's not that simple, cargo can still order BZ canisters and then the cost would have to be adjusted too if they chose to sell it back. Creating BZ may not be popular, but that is due to ignorance of players and not because BZ production for sale is not viable.

**Comment by utilbird** [comment]
> It's not that simple, cargo can still order BZ canisters and then the cost would have to be adjusted too if they chose to sell it back. Creating BZ may not be popular, but that is due to ignorance of players and not because BZ production for sale is not viable.

It's not due to the ignorance of players, it's due to their common sense. Making BZ is not worth the effort for what you get, BZ production is a pain and the only reward it gives, money, can't really be used for anything interesting besides guns.

**Comment by ghost** [comment]
> It's not due to the ignorance of players, it's due to their common sense. Making BZ is not worth the effort for what you get, BZ production is a pain and the only reward it gives, money, can't really be used for anything interesting besides guns.

That is not true, you can max out research with BZ creation in first few minutes of a round if you know what you're doing. Creating BZ, just like creating hyper noblium, gives research points to science and can be sold for money as a bonus.

**Pull request closed without merging**
