### PR TITLE
Positronic Brain spawns limited to 1/round.

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
Any given user may now only spawn as a positronic brain once per round.

## Why It's Good For The Game
"Hmm, this new borg has the exact same custom/static name as the previous one, I'm sure nothing bad happened to them"
Adds weight to dying as a borg, instead of "time for my next free respawn lol", and curbs chaining posis and instantly avenging your death/killing antag/etc.

## Testing Photographs and Procedure

Tested and functional.

## Changelog
:cl:
tweak: Players are now limited to one positronic brain per round.
/:cl:

### CODE REVIEW

**Comment by Mat05usz** [comment]
Maybe add a message to the player when they try to use posibrain again? Might help to avoid some headache for mentors/admins/coders with people thinking something's bugged.

**Comment by Tsar-Salat** [comment]
> "Hmm, this new borg has the exact same custom/static name as the previous one, I'm sure nothing bad happened to them"

Is this the only reason? You could simply randomize cyborg names to the same effect.

**Comment by Ivniinvi** [comment]
> > "Hmm, this new borg has the exact same custom/static name as the previous one, I'm sure nothing bad happened to them"
> 
> Is this the only reason? You could simply randomize cyborg names to the same effect.

It adds weight to dying as a borg, instead of "time for my next free respawn lol", and curbs chaining posis and instantly avenging your death/killing antag/etc.

**Comment by FriendlyContractor** [comment]
Very good change as cyborgs are already cancer to deal with as antags and them being able to die with practicaly no consequences is just too much

**Comment by Tsar-Salat** [comment]
> It adds weight to dying as a borg, instead of "time for my next free respawn lol", and curbs chaining posis and instantly avenging your death/killing antag/etc.

Cool. Put that as the reason.

Using "static names" as the reason makes no sense when that could just be resolved by forcing random names on the Posi

**Comment by PerishedFraud** [comment]
As much as I want to cry that this is another crew nerf, it is fully justified. A posi can be recovered from a fallen borg very easily unless they are dusted. Currently that player can just become the exact same bo rg while their old body and brain rot somewhere, instead of having to be recovered. It is stupid. Dying as a borg is not permadeath. So yeah, this change is really good.

**Review by ike709 — APPROVED** [review]

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
