### PR TITLE
Stun baton is more likely to have a large affect from EMPs.

### PR DESCRIPTION
**Pull request by PowerfulBacon**
**This PR is redundant and will be replaced by a follow-up PR.**

## About The Pull Request

Stun batons have a 100% chance for heavy emps and a 50% chance for light EMPs to have their power fully drained.

## Why It's Good For The Game

Currently stun batons have almost no effect to EMPs, it drains 1000 power from the heaviest EMP which is the equivilent of hitting someone a single time.
This makes it so stun batons are more likely to be affected by EMP blasts. Considering the strength of the stun baton and with changelings no longer being able to block stun baton attacks, an EMP taking a single charge from the baton definitely needs changing.

## Changelog
:cl:
balance: Stun batons are now more affected by EMP attacks.
/:cl:

### CODE REVIEW

**Comment by VictorVow** [comment]
To be clear this makes it so that there's a 100% chance that a roundstart baton will be 100% drained.

This changes the balance so that in most cases if a ling or cultist finds a seccie without a shotgun, it's a guaranteed kill since every other way of them fighting back can be negated. 

The reason why stun combat was removed is because it's no fun there being situations where "if you don't have X item, you're dead". It's the same here - "if you don't have shotgun, you're dead". It leaves no room for skill to outrobust your opponent despite the odds being against you. 

There's a middleground between 100% of charge being depleted and 10%. If it instead reduced 50% of charge that's more reasonable - you might not still not have any chance if your batons were already depleted or they decide to EMP twice, but it's at least not an instant "you lose" button.

**Comment by Howluinb** [comment]
> This changes the balance so that in most cases if a ling or cultist finds a seccie without a shotgun, it's a guaranteed kill since every other way of them fighting back can be negated.
> 
> The reason why stun combat was removed is because it's no fun there being situations where "if you don't have X item, you're dead". It's the same here - "if you don't have shotgun, you're dead". It leaves no room for skill to outrobust your opponent despite the odds being against you.
> 
> There's a middleground between 100% of charge being depleted and 10%. If it instead reduced 50% of charge that's more reasonable - you might not still not have any chance if your batons were already depleted or they decide to EMP twice, but it's at least not an instant "you lose" button.

cult emps are getting nerfed with the bibles. You will completely bypass any cult emp if you dual wield batong/bible

**Comment by PowerfulBacon** [comment]
Cultist EMP is nerfed in an upcoming PR and will be blockable by holding a bible or having the chaplain bless turfs.
A changeling or traitor with the EMP kit will be stop the securities stun baton from working, which at the moment has almost no effect from EMP. It will be very effective against unprepared seccies, but anyone who knows they are up against a changling or someone with EMPs will already have prepared for them.

having the stun baton have the ability to immediately attack afterwards, even if its 90% charge rather than 10% will still make the EMP almost useless against it unless there is a timer that disables the stun baton's activation for a few seconds. This solution is simpler however and definitely deserving for a weapon that can down someone in 2 hits.

**Comment by VictorVow** [comment]
> cult emps are getting nerfed with the bibles. You will completely bypass any cult emp if you dual wield batong/bible

"if a ling or cultist"

> having the stun baton have the ability to immediately attack afterwards, even if its 90% charge rather than 10% will still make the EMP almost useless against it unless there is a timer that disables the stun baton's activation for a few seconds. This solution is simpler however and definitely deserving for a weapon that can down someone in 2 hits.

You haven't addressed the middleground, instead making it a choice of 100% or 10%. Disabling activation for a few seconds is also a good idea.

**Comment by PowerfulBacon** [comment]
> You haven't addressed the middleground, instead making it a choice of 100% or 10%. Disabling activation for a few seconds is also a good idea.

I'm happy to go with disabling the activation for somewhere between 30 seconds and 2 minutes instead of fully draining, just something to force its non-use in combat / force a retreat until you get stuff that isn't affected by EMPs.

**Comment by VictorVow** [comment]
I think it's a pretty boring trying to make the combat meta based around gear rock-paper-scissors, since it's also why people hate the flashes vs sunglasses meta. It gives no leeway for skill, just who hoards the most gear, and encourages people powergaming the items which give them the best chances in combat. "Oh you don't already have powergamer item #232? Sorry you failed the check, you die". The game wouldn't significant benefit from a shotgun-check, as opposed to simply fixing that EMPs don't drain enough battery as opposed to all of it.

**Comment by PowerfulBacon** [comment]
Changelings already had their ability to block removed which made stun batons overly affective against them, so it's only fair. As for security having little emp resistant tools, #6125

**Comment by VictorVow** [comment]
> Changelings already had their ability to block removed which made stun batons overly affective against them, so it's only fair. 

You're proposing that they can use that one spell to disable flashes, batons, disablers, energy bolas, headsets AND suit sensors. Even if battery drain was 50% all a ling has to do is pop Adrenals or Tentacle and that little bit of baton battery is negated too. Changelings were one of the strongest antags even before Zeskoblock, adding more benefits to EMP isn't how they need to be rebalanced currently. 

> As for security having little emp resistant tools, #6125

An item that's worse than combat knives already, and if you have to order a crate you'd just get ballistics instead? 

I don't think if 3 seccies encounter an antag their only option should be to run away until they get better gear. 3 seccies with base kit should be able to overpower 1 cultist even when EMP'd - since the bread and butter of antags should be ambushing them solo. In your proposed scenario they'd only be able to punch, or hope that they haven't got flashbang immunity. Which reminds me, harmbaton does even less damage than punches lol.

**Comment by PowerfulBacon** [comment]
The stun baton is a 2 hit win weapon which, unlike all other electronic equipment, is barely affected at all by EMPs. This change is fair.

**Comment by VictorVow** [comment]
Me when you don't address any of my points :|

**Comment by PowerfulBacon** [comment]
Still, stun batons are an electronic device that are basically not affected at all by EMPs and can down someone in 2 hits. Security have roundstart access to billy clubs which deal 10 damage and 15 stamina damage, which against an unarmoured opponent would be 4 hits. 3 security officers using equipment available roundstart to them could easilly take down a cultist with EMP spells, even in the unlikely situation where a cultist manages to get the jump on 3 unprepared seccies together that are completely unaware of changelings or cultists, and even if the security decide to run, the game is up for the changeling / cultist since preparations will be taken to fight them in the future.
I get that you think EMPs are overpowered against security officers due to their random effects, but security can handle them using just roundstart gear.

Why should the stun baton be allowed to bypass EMPs, when all other electronic gear is affected by it?
I think with the nerf, we get put in the place we want to be: the stun baton is the optimal weapon but there are other, weaker, options to fight with such as flashbangs, billy clubs, pepperspray or even just picking up something in the environment such as a toolbox or fire extinguisher.

**Comment by VictorVow** [comment]
> Still, stun batons are an electronic device that are basically not affected at all by EMPs 

I've agreed with you on this already, just not that it should be 100% drain. There's a middleground between 100% and 10% where it's still a significant effect but not the perfect one-click counter. 

> Security have roundstart access to billy clubs which deal 10 damage and 15 stamina damage, which against an unarmoured opponent would be 4 hits. 3 security officers using equipment available roundstart to them could easilly take down a cultist with EMP spells,

Then this #3739 should be reverted if billy clubs are supposed to be the intended counter that all seccies have equipped to deal with random EMPs. 

> I get that you think EMPs are overpowered against security officers due to their random effects

If anything it's the opposite, they're consistent and reliable in defeating most sec equipment and by making them ALSO affect stunbatons and energy bolas they become one of the most dependable anti-sec weapons available. 

> Why should the stun baton be allowed to bypass EMPs, when all other electronic gear is affected by it?

Bro who's saying bypass lol. Surely you can think of a number or range between 100 and 10 that's reasonable? 

If anything now I'm thinking every other electronic weapon shouldn't be instantly useless, and should instead just drain a significant amount of charge, considering you want it to affect even more sec items.

**Comment by PowerfulBacon** [comment]
> I've agreed with you on this already, just not that it should be 100% drain. There's a middleground between 100% and 10% where it's still a significant effect but not the perfect one-click counter.

Problem with the batons is that you either have enough to crit someone, or you don't; either you go all the way or none of the way.
Having it as a set number of charge lost means that you can just simply get a bigger battery and then bypass the EMP effect.
Having it as a percentage means that you will be in 2 conditions: Either your stun baton is still effective, or yoru stun baton is useless. Even if it drains 90% of the power, you can still either upgrade the battery to a bluespace power cell and bypass EMP effect or just have your stun baton made useless by the EMP. We might as well just take all of the power out of it, to make it so that you will consistently disable it when using the EMP at close range.

> Then this #3739 should be reverted if billy clubs are supposed to be the intended counter that all seccies have equipped to deal with random EMPs.

Just use a vendor, security don't get given all of their gear at spawn to deal with random threats that could happen, they have to get their glasses from a locker to deal with flashes, their bolas from the vendor to deal with people and their billy clubs from the vendors to deal with EMPs.

> If anything it's the opposite, they're consistent and reliable in defeating most sec equipment and by making them ALSO affect stunbatons and energy bolas they become one of the most dependable anti-sec weapons available.

I don't see a problem, although EMPs are more of a utility weapon since alone you won't be able to do anything against anyone with an EMP grenade unless they are an IPC. You still won't be able to wipe out the entirity of sec with a single EMP, even if you are attacking a group if just 1 of them gets away they can come back more prepared, grab something from the environment, or just by having a bunch of them being there 1 of them probably has a way to deal with it. Sure, your 20 damage blade arm might be able to take down a lone seccie who lost his 75 damage baton, but you are going to have a lot more of a rough time when fighting against 2 or more seccies, since at that point anything that does 10 or more damage makes you outmatched in a raw click to win contest. I agree that the cultist EMP is too powerful however, since they get ridiculous gear on top of the easilly available EMP, hence the other nerfs for that, but as for changelings the best you get is a 20 damage sword that cannot block meaning in theory you would only need N number of seccies with something that does 20 / N damage.

**Comment by kit-katz** [comment]
removing a lone officer's last resort weapon in the event of an emp leaving them practically disarmed.
briliant

lings are gonna love this one

**Comment by VictorVow** [comment]
> Problem with the batons is that you either have enough to crit someone, or you don't; either you go all the way or none of the way.

Not anymore since stamina now constantly regenerates. So you can just dodge/shove/block/any other way delay the time between hits and then it absolutely does matter since you'll have regenerated it away. 

Plus you can just EMP more than once, which makes the choice between percentage and flat reduction significant. 

> Just use a vendor, security don't get given all of their gear at spawn to deal with random threats that could happen, they have to get their glasses from a locker to deal with flashes, their bolas from the vendor to deal with people and their billy clubs from the vendors to deal with EMPs.

Having enough available for all seccies and it being default in belts goes a long way to ensuring their usage, and since you want to make EMPs far more debilitating with even less counters then it's warranted here. Otherwise it just turns into another weapon you need to run to the Brig for, which realistically will be prioritised as shotguns if it's a ling/cultist. And I've already discussed at length why "run away to get specific-needed-counter item" is bad design. 

> but as for changelings the best you get is a 20 damage sword that cannot block meaning in theory you would only need N number of seccies with something that does 20 / N damage.

Problem is currently they only have a 5 damage wet fish of a baton since no-one carries billy clubs and are unlikely to unless that revert happens, so I wouldn't be surprised to see multi-kills still.

**Comment by FriendlyContractor** [comment]
I hate stunbaton in its current state but change you propose means EMP degrades officers into using their fist to fight unless they were resourcefull enough to have grabbed a shotgun before hand. I would prefer nerfing stunbaton to a more reasonable damage(i believe its currently higest damage weapon obtainable) rather than having emp turn security officer into a nugget

**Comment by PowerfulBacon** [comment]
**I plan to refactor this PR to make the stun baton and energy based weapons disabled for a certain amount of time rather than remove all their charge.**

**Comment by Naevii** [comment]
This pr means you are left with basically no choice than lethals. 
This means changeling will now win every fight because you remove the only thing left that sec officers had in their non lethal load out. (even when changelings couldnt block stunbaton anymore, it was a good chance, a slight nerf to already powerfull antag. they also could click security officer faster with their armblade than sec officer with a stunbaton) This means changelings will be even stronger. And changelings are already top as most powerfull solo antagonist.

**Comment by PowerfulBacon** [comment]
Changelings almost always had the ability to block stun batons anyway until it was stealthnerfed recently. (Sayings its a stealthnerf since it was very difficult to find the PR and CL explaining the changes, it was written as ` blocking has been nerfed on many items`. In reality the blocking was completely removed from the armblade.). In fact the PR nerfing it was a balance PR solomerged by a single maintainer without any input from anyone else.

**Comment by PowerfulBacon** [comment]
PR is redundant and will be replaced by a follow-up PR.

**Pull request closed without merging**
