### PR TITLE
Removes offensive slurs from game

### PR DESCRIPTION
**Pull request by 123chess456**
## About The Pull Request

In some parts of the game there are offensive words. I have removed as many as I could find. Specifically:

"Gay" is now removed from the politeness mutation as it implies there is something wrong with being gay.

"A robust mongoloid" is removed from the CAS white deck, as "mongoloid" is a highly offensive ethnically related slur used to reference people with Down's syndrome.

All references to "THAT GRIEFING FAGGOT GEORGE MELONS" are purged.

"Illegal immigrants" has been changed to "undocumented immigrants" when used to generate AI ion laws.

"Angry black men" has been removed from the AI ion law generation, as it would make the AI racist in numerous circumstances.

The station name can no longer include the word "aspie"

Random gibbering can't call someone an "autist"

Removes emag message from security gas mask as it was a long copypasta insulting people based on their sexuality. Instead emagging a security gas mask just randomly selects from shitsec lines.

## Why It's Good For The Game

It's not but you might as well be consistent.

## Changelog
:cl:
del: Ethnic slurs, racist content, and insults based on sexuality are now removed.
del: slurs for intellectual disabilities are also gone.
/:cl:

### CODE REVIEW

**Comment by honkhonkclown** [comment]
cringe and qwertypilled

**Comment by Wilchenx** [comment]
BASED

**Comment by boodaliboo** [comment]
Imagine having more censors then fucking yogstation lol

**Comment by ghost** [comment]
me, 3 months ago when i left admin: "Bee is gonna go down the fulp/yog path and i want nothing to do with it." 

The other admins/coders: "We are never gonna go down that path"

123chees456, 8 hours ago: "Hold my soy, non-gmo, estrogen infused martini." 

also imagine trying to remove the george melons meme, thats basically ss13 history youre trying to erase lmao

**Comment by 123chess456** [comment]
It's funny to PR logical consequences of social justice crap because it makes people realize how ludicrous some of the stuff is. E.g. on /tg/ when someone merged in NB players I made the changeling honorifics non binary as well :^)

**Comment by ghost** [comment]
I mean, not really

most of the changes in this are either pointless, removing age old memes, etc

seems more like accelerationism to me.





fuck it merge this badboy i give it my seal of approval

**Comment by ghost** [comment]
> The station name can no longer include the word "aspie"
> 
> Random gibbering can't call someone an "autist"

as someone diagnosed with Asperger's, I officially grant all of SS13 the A-word pass.

**Comment by karmaisblackandbluepilled** [comment]
unbased and bluepilled

**Comment by ike709** [comment]
Some of these might get unironically removed in the future, most won't, but your meme PR is being closed since some people are taking it seriously.

**Comment by Oshibkka** [comment]
me when bad word in my gore-filled violence fest space game :(

**Comment by honkhonkclown** [comment]
bro ike not helping his case with the playerbase here by threatening to remove more shit off his personal politics

**Pull request closed without merging**
