### PR TITLE
adds curbstomping

### PR DESCRIPTION
**Pull request by qwertyquerty**
## About The Pull Request

adds curbstomping, deals 36 brute to the head

## Why It's Good For The Game

curbstomping

curbstomping

## Changelog
:cl:
add: curbstomping
/:cl:

### CODE REVIEW

**Comment by vyzk** [comment]
very based. please add

**Comment by ghost** [comment]
You absolutely butchered a feature I wrote with love. Pathetic in every way.

**Comment by Militaires** [comment]
woross is right you cucked it.

**Comment by bruhmomento5** [comment]
how'd you fuck it up so much?

**Comment by ghost** [comment]
hoes mad

**Comment by Oshibkka** [comment]
well yeah but does it give brain damage? also credit woross

**Comment by ghost** [comment]
https://i.imgur.com/no41Esq.gif

Here is the original curbstomping feature as written by me. Notice that this guy did not even add any credit, even though over half of this code is straight copied from PP Station 13. The only parts that are not copied made it worse.

**Comment by qwertyquerty** [comment]
If you guys insist.

Uhhhhhh thanks to ppstation. I heavily modified their little animation thing and used that.

**Comment by ghost** [comment]
Just write the damn credit in the file. You cut it from the code.

**Comment by bruhmomento5** [comment]
credit woross

**Comment by qwertyquerty** [comment]
Not giving any more credit than I already have given. End of story.

**Comment by ghost** [comment]
No credit? Imagine stealing content. Bee is truly just a bunch of parasites.

**Comment by ike709** [comment]
To be fair, literally nobody ever credits in the code. Ever. On any codebase. There's only a handful of mentions of code authors in the code, and that's typically only really old code people originally wrote themselves, like Carn shuttles or some stuff Errorage did.

It is courteous to mention credit in the PR, though.

**Comment by Militaires** [comment]
im more mad about him removing the gib

**Pull request merged**
