### PR TITLE
BeeShop Bug Fixes - White Hoodie and Dope necklace

### PR DESCRIPTION
**Pull request by Nakalon**
## About The Pull Request

The white hoodie you can buy in the beecoin shop is actually just the hood.

This PR fixes that.

There are two instances of the dope necklace.

I created another item called gold cross necklace to replace one of them.
Since the only thing different was the name being mentioned as "old necklace" I thought it would be interesting to make it one of those necklaces with the cross of christ you see old people wear.

I did NOT remove the duplicate necklace because I am fairly certain some people have bought one or the other for 25k BEECOINS which is a huge amount.

If I were to remove them they would lose their 25k investment that's that's not cool.
But we can't have duplicates because that makes no sense.

## Why It's Good For The Game

Its a bugfix

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image
This is as is on the live server right now.

With the fix:
image

Necklace on live server:
image

With this fix:
image

Ingame:
image

</details>

## Changelog
:cl: Pink Sosokey
fix: Fixed a bug involving the Beecoin Shop and white hoodies where only the hood would be purchasable.
add: Added the gold cross necklace to fix the duplicate instance of gold necklaces on the bee shop. This means anyone who owns 'necklace, gold' will now have the cross necklace, with 'dope necklace' remaining the old version.
imageadd: Created sprites for the cross necklace.
/:cl:

### CODE REVIEW

**Review by itsmeow — CHANGES_REQUESTED** [review]
Changing the display name of a gear effectively changes what it is, since gear in the database is stored by gear ids. Gear ID is `md5(display_name)`. You would have to either manually set the ID back or make a query to update the database.

**Comment by Nakalon** [comment]
> Changing the display name of a gear effectively changes what it is, since gear in the database is stored by gear ids. Gear ID is `md5(display_name)`. You would have to either manually set the ID back or make a query to update the database.

So if I keep it "necklace, gold", it will be fine?

**Comment by itsmeow** [comment]
You could do that. Or you could just assign an ID manually by overriding Initialize.

**Comment by Nakalon** [comment]
> You could do that. Or you could just assign an ID manually by overriding Initialize.

I'm not really sure how to do that, its the first time I'm hearing of this...

**Review by itsmeow — APPROVED** [review]
Looks good to me. Players with `necklace, gold` will now receive crosses.

**Comment by Nakalon** [comment]
> Looks good to me. Players with `necklace, gold` will now receive crosses.

yeah, I have faith that if they rather have the Dollar one they would Ahelp or something. If we were to delete the item they'd just be itemless if they bought it in the past... something had to be done haha

**Review by PowerfulBacon — APPROVED** [review]
Why did we choose do do it by display name and not type path...

**Pull request merged**
