### PR TITLE
New Hygiene Sprite

### PR DESCRIPTION
**Pull request by Cenrus**
## About The Pull Request

Changes the hygiene sprite.
## Why It's Good For The Game

I think a huge issue most players have with hygiene is the obnoxious green clouds. This still conveys the "smell" factor, but I think in a more mild way. You guys said you want to improve hygiene, and this is how I'll go about doing it.
Mirrored from https://github.com/tgstation/tgstation/pull/44347

## Changelog

:cl:
imageadd: New Hygiene Sprite
/:cl:

### CODE REVIEW

**Comment by Agameofscones** [comment]
For reference, this is the sprite in question.

**Comment by MarkSuckerberg** [comment]
Just my opinion, but that seems to convey bad hygiene worse than the green cloud

**Comment by Agameofscones** [comment]
The flies would be great for dead bodies, but I'd personally stick the green clouds with the living. Reads better visually imo.

**Comment by qwertyquerty** [comment]
Just looks worse.

**Pull request closed without merging**
