### PR TITLE
Fixes the preserve virus and synthmeat chemical recipe conflict

### LINKED ISSUE #1882: cryoxadone + blood in plumbing makes more blood instead of popping out synthmeat

### PR DESCRIPTION
**Pull request by Mick1299**
## About The Pull Request
Changes the recipe for preserve_virus to cooling Blood to 250k (-20 celsius) in the presence of  Nitrogen. Also comments and cleans the virus recipe code a little

## Why It's Good For The Game
The old preserve_virus recipe required 1u Blood and 1u Cryoxadone. As the Synthmeat recipe requires 5u Blood and 1u Cryoxadone, the reactants will always react via the preserve_virus recipe when in plumbing machines.

This change enables the use of plumbing to make synthmeat factories, and also solidifies preserving a virus as a final virology step.

Did a little code cleaning while in there

Issue: #1882

## Changelog
:cl:
tweak: small change to preserve_virus recipe
fix: #1882 
refactor: changed some spacing, added comments
/:cl:

### CODE REVIEW

**Comment by Mick1299** [comment]
One little side note. This technically allows the replication of blood with only nitrogen and cooling As this is currently possible via unstable mutagen, I feel this isn't to large of an issue. Cooling the chems to 250 is just as difficult as mixing some Chlorine, Phosphorous, and Radium.

however, If maintainers feel that this would unbalance the blood replication meta, I can reduce the reaction temperature to something like 200k (-70c), or change the catalyst chem required

**Comment by zeskorion** [comment]
The reason cryoxadone was chosen is due to the fact that it is an easy chem for viro to get. This requires the virologist to bust into chemistry, or give irresponsible chemists their virus

**Comment by Mick1299** [comment]
Fair enough. What if I removed the temperature component, and changed Nitrogen to Cryostylane. That fixes the synthmeat factory issue, keeps the reaction thematic with preservation, and makes it an easy chem for chemists to cook up

**Comment by hotimep** [comment]
poggers

**Comment by Mick1299** [comment]
Alright, changes made. Cryostylane instead of Nitrogen, and no temperature requirement.

**Comment by zeskorion** [comment]
> Fair enough. What if I removed the temperature component, and changed Nitrogen to Cryostylane. That fixes the synthmeat factory issue, keeps the reaction thematic with preservation, and makes it an easy chem for chemists to cook up

nah, it has to be like all other virus chems- something out in medical. Change the synthmeat recipe instead. Though, i dont think a synthmeat factory should be easy to make either

**Comment by MCterra10** [comment]
if zesko is going to whine about cryostylane being inaccessible, just add a bottle or two to the viro fridge @Mick1299

**Comment by MCterra10** [comment]
if we follow that logic, synaptizine shouldn't be a valid chemical for virology either

**Comment by Mick1299** [comment]
>Though, i dont think a synthmeat factory should be easy to make either

The current synthmeat recipe is pretty complex from a chemfactory perspective. 

I'll add a bottle to the virology fridges. If they somehow use 30u, they can leave their little fort and actually talk to another player.

**Review by zeskorion — APPROVED** [review]

**Pull request merged**
