### PR TITLE
Adds weapon powercells

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
Adds the ability to switch out special weapon powercells in energy weapons, similar to ballistic weapons with magazines. Basic and upgraded weapon powercells are made researchable.

Also changes firing pin removal from crafting to simply clicking on the gun in-hand with a welder/screwdriver/wirecutters.

## Why It's Good For The Game
Better than carrying around multiple energy guns and gives late-game security a much needed boost. And using crafting to remove firing pins was unnecessarily long-winded.

## Changelog
:cl:
add: Weapon powercells. Basic and upgraded powercells can be researched and swapped out of energy weapons similarly to ballistic weapon magazines. 
tweak: Hacking a firing pin out of a gun is no longer done via a crafting menu - you can now do it by simply holding the gun in your hand and clicking it with a welder/screwdriver/wirecutters.
/:cl:

Ports:
https://github.com/WaspStation/WaspStation-1.0/pull/24
https://github.com/WaspStation/WaspStation-1.0/pull/41
https://github.com/WaspStation/WaspStation-1.0/pull/88
https://github.com/tgstation/tgstation/pull/48461

### CODE REVIEW

**Comment by zeskorion** [comment]
what research are the upgraded cells locked behind

**Comment by BeloneX** [comment]
cant wait to put a slime power cell into the hos gun for infinite taser

**Comment by VictorVow** [comment]
Advanced weapons dev tech so pretty late game.

**Comment by Isy232** [comment]
This is good since if science wants to make big stompy mechs they have to research powercells for security.

**Comment by MarkSuckerberg** [comment]
don't do this

**Comment by VictorVow** [comment]
@MarkSuckerberg why? It's even a port from your codebase so I don't get it.

**Comment by MarkSuckerberg** [comment]
if there was one thing I wish I had never coded it was this

**Comment by qwertyquerty** [comment]
Care to elaborate

**Comment by MarkSuckerberg** [comment]
It was something I only really added because of a dare. It breaks the ballistic vs. laser dichotomy by allowing people to carry around a load of power cells and never having to stop and recharge, except for the short amount of time it takes to screwdriver the cell out and slam another cell in. Also some credit to zeta for the sprites would be nice.

**Comment by Baldir-Odensen** [comment]
As the person who coded the actual powercells they aren't really truly finished as they still fit in a rped, don't fit in sec belts and I don't think the concept is ant good to begin with. I only did it to prevent people putting stuff like blusepace powercells in them which is completely broken

**Comment by VictorVow** [comment]
@ike709 vote

**Comment by MarkSuckerberg** [comment]
don't

**Comment by triplezeta** [comment]
hey, these sound familiar....

**Comment by CthulhuOnIce** [comment]
I like the idea of this but in practice it sounds like hell

**Comment by qwertyquerty** [comment]
Vote failed

**Pull request closed without merging**
