### PR TITLE
Improved Syndicate Lavaland Outpost

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
I think it looks better and it also replaces the old almost removed virology with a new recently reworked field. 
~~The autolathes are placeholders until #10906 is finished and merged. Do not merge it until then.~~
Destroyed Xenoarch to look rundown and without any of the fancy computers and such, it can still be used to learn current day Xenoarch.

## Why It's Good For The Game
Allows people to learn and try out this new field in relative peace and quiet. 

The atmospherics changes will help fixing stuff such as when a fire bomb is tested in the chemistry grenade testing room.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image

image

I'll playtest it some other day. I want feedback for these balance changes and such first.

</details>

## Changelog
:cl:
add: (Syndicate Outpost) Added a Xenoarch section.
del: (Syndicate Outpost) Removed Virology section.
tweak: (Syndicate Outpost) Added a hacked autolathe.
tweak: (Syndicate Outpost) Repositioned a few turrets.
tweak: (Syndicate Outpost) Added an atmosfan, full toolbelt and a heater.
fix: (Syndicate Outpost) Added some buffer walls to prevent turrets from shooting inwards through the station.
tweak: (Syndicate Outpost) Added another minor maintenance hallway.
tweak: (Syndicate Outpost) Minor tweaks all around.
tweak: (Syndicate Outpost) Expanded the bar and added an additional entrance.
tweak: (Syndicate Outpost) Did a bunch of decal work.
tweak: (Syndicate Outpost) Added a disposals input chute for the testing range.
fix: (Syndicate Outpost) Changed the atmos gas chambers to be filled with the respective gas on round start (O2, N2, Plasma).
fix: (Syndicate Outpost) Fixed so that the kitchen can actually cook food now.
fix: (Syndicate Outpost) Changed air distro to use layer 2 instead of 3.
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
I think this will reward the station instead of them by research...

**Comment by MarkusLarsson421** [comment]
Probably... Is _that_ big of an issue? Once the PR is merged I might try to make a subtype which prevents all discovery related things.

**Review by spockye — CHANGES_REQUESTED** [review]
image

missing pipe, unfitting white tile

image

missing outlet


image

new kitchen seems a little weird. dont really like the table here, and the lack of flooring under. also, mabye add some wooden borders around the wood?

image

a lot of wall decals around. intentional?

image
something seems to be wrong with the stairs

image
move up the layer of the railing

image
something seems wrong with the decalling under the closets

image
turrets target the pet. update its faction if your keeping it!

-------------

it shouldnt affect the stations research points :p  
the syndicate wouldnt help the station

**Comment by spockye** [comment]
image

Dont give them the easter bunny. it spawns error eggs that can give you some pretty broken things

**Comment by MarkusLarsson421** [comment]
> a lot of wall decals around. intentional?

image

**Comment by Rukofamicom** [comment]
> Once the PR is merged I might try to make a subtype which prevents all discovery related things.

All PRs should be treated as final with no follow-ups expected, regardless of trust and/or history. 

If you intend to do something as part of this PR, it should be included as part of this PR
If it is going to be two separate PRs, they should be functionally complete additions as separate PRs.

**Comment by MarkusLarsson421** [comment]
I meant once the Xenoarch PR is merged. Making additions to their code would require me to make a fork of their code and deal with any up coming issues, so I wait until the Xenoarch PR is merged and try to add the additions myself to this PR then.

**Comment by MarkusLarsson421** [comment]
Where Xenoarch?

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
Don't forget to rename the virology area since it isn't virology anymore.

**Review by Rukofamicom — APPROVED** [review]

**Comment by Rukofamicom** [comment]
None of these changes constitute any real balance change for the capabilities of the outpost against intruders:
They still have sniper rifles and stechkins, and the turrets are still the same power as they were even if relocated.

**Pull request merged**
