### PR TITLE
Adds beating vending machines for free stuff/getting crushed to death

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
https://github.com/BeeStation/BeeStation-Hornet/projects/2#card-29398209
port:tgstation/tgstation#47799

You can attack vending machines with objects to try and knock free things loose! You have a chance of getting a few trinkets for free for each whack! You also have a chance of the vendor falling over on your cheapass head and squish you and anyone else on the tile for 75 brute (or something like that, I'm open to interesting/funny ideas)

Might be balance implications to this? If there's any machines that really shouldn't be giving stuff away unauthorized I can turn it off for them

Here's your odds:
5% chance to get 3 goodies
10% chance to get 2 goodies
10% chance to get 1 goody
50% chance for nothing
15% chance for tilt
10% chance for tilt with CRIT

There are 5 crit effects:
1- Shattered/pulped legs: Smashes both your legs and removes 150u of blood along with them
2- Pinned: You are stuck under the machine until someone else untilts it and moves it off you
3- Glass candy: You are shredded by glass shards
4- Paralyzed: You have fully severed your control over your legs!
5- Skull squish: Your head explodes! Obviously this is instantly fatal

this is an amazing sentence you gotta admit

## Changelog
:cl: Ryll/Shaps, Mark Suckerberg
add: You can now beat on vending machines to try and knock loose free stuff! You can also almost kill yourself doing it, so it's your call if your life is worth ten bucks.
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Fails travis.

**Comment by ike709** [comment]
On second thought, this isn't potentially harmful enough to necessitate a testmerge. I assume you tested locally?

**Comment by MarkSuckerberg** [comment]
Yes, I did. It all works as far as I can see, I got every outcome.

**Comment by ike709** [comment]
Fix conflict and I'll merge.

**Comment by Cenrus** [comment]
https://github.com/tgstation/tgstation/pull/48134

**Comment by ike709** [comment]
@MarkSuckerberg ^^

Also conflict.

**Comment by MarkSuckerberg** [comment]
Yes, yeah, yes, forgot to do this

**Comment by MarkSuckerberg** [comment]
Updated, and will merge the fix into it when it gets merged on /tg/.

**Comment by ike709** [comment]
Fix is merged on TG.

**Comment by ike709** [comment]
Conflict.

**Comment by ike709** [comment]
Stale.

**Comment by MarkSuckerberg** [comment]
fixed

**Pull request merged**
