### PR TITLE
Removes felinids from roundstart races

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request

Removes felinids from roundstart races

## Why It's Good For The Game

[Insert memes here] No one but felinid players like felinids. they tend to be played by the worst people. fanatics can still cut up runtime and become felinids via surgery, praying for purrbation, or by xenobio.

## Changelog
:cl:
config: felinids no longer available roundstart
/:cl:

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
No offense, but I feel this is an idiotic thing to do, and this is as some one who's never played felinid. If they enjoy the race, there isn't a reason to remove it unless there is a severe balance issue (and there sure as hell isn't, since they lack any advanages).

The only reason reasons you gave were everyone dislikes them, and that they're played by terrible people. Guess what else people dislike, being arrested by security. Doesn't matter, security still does it. Disliking a cosmetic race with zero advantages isn't a reason for removal. As for terrible people, every race has shitler. I can just as easily say humans are played by the worst people and be right, because every race has it's idiots.

**Comment by Cenrus** [comment]
time to remove plasmapeople from the roundstart race list because they are played by the worst people.

**Comment by ghost** [comment]
ascended-34831974

**Comment by Sparrowbird611** [comment]
We literally have more reason to remove plasma men because of their power game potential than we do felinid, honestly. It's basically a meme at this point.

**Comment by ghost** [comment]
> We literally have more reason to remove plasma men because of their power game potential than we do felinid, honestly. It's basically a meme at this point.

Or you can pretend to have more then 3 braincells for a second and delete anime

**Comment by zeskorion** [comment]
Every time a vote has been made, it has been in favor of disabling cats. Players obviously dislike them. It's a step away from the hugbox /tg/ is as well

**Comment by Oshibkka** [comment]
catfags seething. also cenrus your opinion literally does not count because you play MRP 😎

**Comment by Oshibkka** [comment]
and yes most plamamen players tend to be massive faggots

**Comment by zeskorion** [comment]
> and yes most plamamen players tend to be massive faggots


Bro i thought you said you wouldnt tell anyone bro

**Comment by Sparrowbird611** [comment]
I don't get how removing them makes it less of a hug box. Your logic is basically removing a race with literally zero advantages from play, because some people who rarely have to deal with them dislike them for the meme, and removing them from the people who do like them.

It's quite literally "Hey yall, I dislike this, lemme remove real fast because uh.... reasons." To put it bluntly, this meme is cringe, not kek.

**Comment by Oshibkka** [comment]
i said most you illiterate shit flinging monkey

**Comment by ike709** [comment]
I dislike them because they're literally just humans. Races should be unique.

**Comment by ike709** [comment]
But I will put this up to one final vote.

**Comment by KingTerrytheTerrible** [comment]
+1

**Comment by Guestratem** [comment]
pretty cringe ngl, but If you're up for it ill try to create more variation to at least make them more distinguishable. other than the ears, chocolate allergy, tail and laser pointer mechanics

**Comment by KingTerrytheTerrible** [comment]
image

**Comment by ghost** [comment]
Last I remember it was 24 hours or so

**Comment by qwertyquerty** [comment]
## Official Qwerty Stance

I believe that most races are simply bloat content and serve no purpose. I will likely speak against the addition of any more races that are similar to felinids (as in they don't have many distinguished characteristics)

HOWEVER, we do have felinids and some degenerates actually enjoy playing as them, so I'm not just going to take it away from them.

I simply wish that content like felinids is never added in the first place so we don't get stuck with it.

**Comment by braincrab** [comment]
dew it. remove them. dew it now.

**Comment by honkhonkclown** [comment]
aaand now cringe mf is ddosing server and kev is too skulldent to just reboot eet

**Comment by CthulhuOnIce** [comment]
reboot it to be taken down again?

**Comment by TWaiK31** [comment]
1 Catgirl removal happens to rile people up
2 It is immideately reverted and speedmerged in secret
3 Slurs get banned to distract us and make people leave
4 Dimas leaves, now the 2 empty council Spots are going to be filled by Oranges(who is a jewish sleeper agent)/Zoey/Wilchen
5 Nervere joins and gets all perms in secret (actually happening RN)
6 Bee slowly turns into tg by the time we go 513

ITS LIKE FUCKING POETRY. SPREAD THE WORD LADS. THE NIGGER REMOVAL IS ONLY THE BEGINNING. 

FUCK TG
FUCK TRANNIES
FUCK BEE
FUCK ORANGES
FUCK NERVERE
LONG LIVE DIMAS
LONG LIVE LUMMOX
HAIL KARMA
THIS WILL NOT STAND

**Comment by Sparrowbird611** [comment]
I pretty much follow the qwerty stance on this.

**Pull request merged**
