### PR TITLE
Removes unused code from engineering.dm

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Removes the unused Roboticist & Engineer skirt code someone left in there.

## Why It's Good For The Game

You won't notice this unless you're a coder, and even then you probably won't notice it.

## Changelog
:cl:
code: Removed unused code from engineering.dm
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Travis bugged.

**Comment by PowerfulBacon** [comment]
I wonder who put robotics in the engineering clothes folder.

**Comment by ghost** [comment]
> I wonder who put robotics in the engineering clothes folder.

I mean, robotics has more to do with Engineering than Science.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Remove the icons too

**Comment by PowerfulBacon** [comment]
Stale

**Pull request closed without merging**
