### PR TITLE
Synthflesh nerf, Tend wounds buff (READ THE PR!!!!!!!)

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This completely removes all healing properties from Synthflesh and makes it only useful for cloning/limb growing, this also reverts the recipe back to normal so silver sulf is no longer required to make it.

It also buffs all tend wounds surgeries to heal atleast twice as much as before.

Reverts #2411

## Why It's Good For The Game

Synthflesh is literally cheating, it's a insta-heal that you can carry multiple bottles around of, that heals a ton of damage and has no downsides or even OD, it outshines every other healing chem and makes medbay gameplay unfun as it boils down to 
Person walks into medbay -> splashes synthflesh onto himself from a factory that consistently pumps bottles of it out -> leaves medbay.

To compensate for this, Tend wounds has been HEAVILY buffed.

Basic Brute Healing: 10 (up from 5)
Advanced Brute Healing: 15 (up from 5)

Basic Burn Healing: 10 (up from 5)
Advanced Burn Healing: 15 (up from 5)

Dual Healing: 5 (up from 3)
Advanced Dual Healing: 7.5 (up from 3)

## Changelog
:cl:
balance: Synthflesh no longer heals and is only useful for cloning and limb growing anymore, to compensate tend wounds surgery has been heavily buffed.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
wtf travis?

**Comment by Sinmero** [comment]
What about synthflesh patches in the advanced medkit? I think its a good idea to put 20/20 Silver Sulfadiazine Styptic Powder patches there instead.

**Comment by ghost** [comment]
> What about synthflesh patches in the advanced medkit? I think its a good idea to put 20/20 Silver Sulfadiazine Styptic Powder patches there instead.

didnt know these existed, gonna replace them.

**Comment by Naevii** [comment]
Honestly, I don't know if you ever play medbay, but medical is overloaded with work even now. This 2-3 people who heals themselves alone is not a problem and it's not boredom factor. We would need entire new medical rather than synth nerfs

Plus synthflesh is also used to unhusk bodies.

**Comment by ghost** [comment]
> Honestly, I don't know if you ever play medbay, but medical is overloaded with work even now. This 2-3 people who heals themselves alone is not a problem and it's not boredom factor. We would need entire new medical rather than synth nerfs
> 
> Plus synthflesh is also used to unhusk bodies.

i too want a new medical system, perferably TG's, but i don't have the experience for this, so do it if you want.
you can also unhusk bodies with tend wounds, or do a brain swap, or fully upgrade the cloner.

**Comment by Naevii** [comment]
Honestly tg system is even worse than what we have now. And won't make medbay more enjoyable.

**Comment by Naevii** [comment]
"Typically a victim of heavy burn damage. It can be unhusked with 100u synthflesh or 5u rezadone."

**Comment by Naevii** [comment]
Rezadone is never to be find in medbay.

**Comment by Isy232** [comment]
I think many people came here because we don't want /tg/'s shitty medbay system where its a pain in the ass to fix people.

Remove the effect of splashing synthflesh, silver sulfazadine and styptic powder, so they will only be usable in patches.

That is the best way I think, no more mid combat megaheals but it keeps the simplicity of these chems.

Listen to Naevi, they play med a lot.

**Comment by 4rchibald** [comment]
No idea how things will go with synthflesh and rest of medical stuff from here, to be honest don't have much experience with that department. But I always felt like synthflesh is a bit overpowered substance and keeping it only for machines like cloning pod sound actually quite reasonably. 
But someone mentioned husked people, that clicked in my head, if we can have synthflesh doing body growing thing in cloning pod why can't we have it unhusking bodies in for example cryo cell. Maybe within different temp range than they are set usually, maybe with different gas connected to them. 
It seems like a negligible addition but it fits in the general idea of limiting synthflesh as miracle drug but not making it completely useless. It would encourage some cooperation between departments to get additional cryo cell with proper set up, which can be achieved with early technologies and would actually improve quality of life of doctors who can pop husked body into cryo cell and work on other patient while husk is getting recovered to some 'workable' condition. What's more we got basically all elements there, we don't need new sprites, we're using mechanics that are known and understood by players so it won't create any confusion.

Just throwing an idea out there

**Comment by eLeCtrOssSnake** [comment]
Makes zero sense at all.

**Comment by zeskorion** [comment]
i'm not even going to bother putting this to vote, it's not going to pass and we all know it

**Pull request closed without merging**
