### PR TITLE
Adds currency symbol for credits

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
Changes the credits symbol from $ to ₡ (Costa Rican Colon) to match things like budget cards.

image

## Why It's Good For The Game
Standardizes the Credits symbol across sprites and text, makes it less Space America

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
tweak: Credits now use the ₡ symbol.
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
This should be a define which takes a text input, so it can be changed to be before or after. Also isn't there a config setting for this and isn't most uses cr?

**Comment by itsmeow** [comment]
missing quite a few uses in TGUI. I know for a fact my bounty boards have a "cr" in them.

**Review by itsmeow — CHANGES_REQUESTED** [review]
see above

**Comment by EvilDragonfiend** [comment]
Sorry for my nitpick but I think the define name "CREDIT_SYMBOL" might be more intuitive

**Comment by Ivniinvi** [comment]
not going to make tgui changes with this pr, let me know if you want it without tgui changes

**Pull request closed without merging**
