### PR TITLE
Adds a sugar sack option to the biogenerator

### PR DESCRIPTION
**Pull request by ZombiesVsPlants**
## About The Pull Request

It adds the option to print a sack of sugar for 200 biomass

## Why It's Good For The Game

If the Chef runs out of sugar you don't have to spend 10 minutes making an ungodly amount of sugar
More importantly, it lets prisoners in perma make cakes and other pastries, as well as letting them grow more weeds for more plants.

So far in perma, the best you can really do is grow some carrots to eat and grow ambrosia to get high despite the microwave and chef gear. The main barrier to making food perma is sugar since you can't make it and a lot of recipes demand it. Now, prisoners can stick around and have fun making food instead of instantly disconnecting or cryosleeping.

Sugar Option
Sugar Printed

## Changelog
:cl:
add: Sugar sack option to the Biogenerator
/:cl:

### CODE REVIEW

**Comment by ZombiesVsPlants** [comment]
thanks Travis

**Comment by Krysonism** [comment]
chef resource creep.

**Comment by PowerfulBacon** [comment]
But botanists can just grow sugarcane anyway, why would they be able to just spawn it when they can grow it?

**Comment by ZombiesVsPlants** [comment]
Sometimes there isn't a botanist and a chef doesn't want to baby a sugarcane plant for ages.

Also, it lets people in Perma to make pastries that require sugar, something they can't get normally.

**Pull request merged**
