### PR TITLE
Assistant modules category concept + lag handler module

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
### Assistant modules
(from readme)
Assistant modules are modules that can help coding like how _HELPERS procs do.
The difference between those is that assistant modules need to be a form of module because of its behaviour.
While helpers are only a single proc, these modules should be a datum type, and should be an object type individually.

#### candidates to add:
* DMM handler
* Random Number Generator

### Lag Handler module
Lag Handler module is the first assistant module to introduce.
This module can be used to reduce excessive lags when a code has been ran to spam something specific, especially runechat, effectively controls lags.

## Why It's Good For The Game
Modular concept for the code will be good to maintain
Lag management is also good

## Testing Photographs and Procedure

https://youtu.be/04CpnDM0eJw

## Changelog
:cl:
code: Assistant modules readme file which describes its concept why it exists
code: Assistant module - lag handler . When a code can possibly cause a lot of lag when it's spammed, it can be used to suppress the lag.
code: Hysteria's effect area has been change to 7 from 4, with the lag handler module.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Isn't this just a more complicated CHECK_TICK?

**Comment by PowerfulBacon** [comment]
We should either use check tick for stuff like this since it sleeps only when the server is lagging (althpugh that can cause MC freezing), or the enumerables system since that ties loops to the MC and so won't cause MC freezes. Any case of a laggy list enumeration is better of being on the enumerable system like singularities

**Comment by EvilDragonfiend** [comment]
I personally don't like how TICK_CHECK works. It only starts to work when you start to get lags, but it should handle when it's going to cause lag.
the main purpose of this is to handle when it's likely to cause lag so that we don't let it excessive delays.
although I kinda agree the current version of this is a bit poor, but I believe it can be used to track/log where it causes most lags as well. I mean, I am more interested in improving this modularisation way rather than just putting `CHECK_TICK` and doesn't care those.

**Comment by PowerfulBacon** [comment]
If something should stop when its going to start causing lag then the enumeration system is what it should go on. That will run until running more would cause other things to not be able to run. Simply running 4 times per tick is going to be horribly slow and will be slow regardless of if the server is not lagging at all and can easilly process additional data. In addition, unlike the enumeration system, this will run synchronously and so will introduce sleeps into places that previously wouldn't and maybe shouldn't have sleeps.

**Comment by EvilDragonfiend** [comment]
> Simply running 4 times per tick 

this module is not related to ticker tho. It's basically loop count based sleep.

**Comment by itsmeow** [comment]
`__assistant_modules` is what `code/modules/x` folders already do. 

If you want a more generalized folder name, make it `code/utils/`. This is standard convention in many programming spaces.

But you can also just do `code/modules/lag_handler/lag_handler.dmm`. It can have its own folder. If you want to segment it more, `code/modules/utils/lag_handler.dmm` could also work.

**Comment by itsmeow** [comment]
Also bacon's right, this is basically the same thing as check tick. If you absolutely *have* to long operations like this, it should be handled by a subsystem. This is what the enumerable subsystem is intended to address.

The specific case you are applying it to can already be optimized through other means - by checking mob/carbon_list and checking the range (as oview() includes all atoms in the given range, for larger ranges this is a huge list). We can also just port TG's spatial grid system.

**Comment by EvilDragonfiend** [comment]
aight. I need to make this more elegant to make sense.

**Pull request closed without merging**
