### PR TITLE
Revert "Revert "Blindness refactor and cleanup + monochrome sight"" + fixes

### PR DESCRIPTION
**Pull request by Tsar-Salat**
## About The Pull Request

Reverts BeeStation/BeeStation-Hornet#9435

Per the information I was given on the round, players experienced blurriness that wouldn't dissipate, and one player was stuck in an unending state of unconsciousness.

I have adjusted the PR to handle reducing blurriness, like it was before. 

I was unable to reproduce the endless sleeping issue, which leads me to believe it's a tick/MC server-specific issue. Likewise, I will show my reproduction in the testing evidence.

## Why It's Good For The Game
fix

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Spraying the eyes

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/431fa875-e67a-407f-abac-952dbf4bda46

Stabbing the eyes

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/71955349-9c3a-4010-8dda-24396ffadaf9

In both cases, the eyes recovered from blurriness.

Additionally, I tested the scenario I was given. I was unable to reproduce the unending sleep under the exact circumstances it was described, which leads me to believe it was an MC issue.

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/d2d312bd-ed44-47a7-9246-273f84b4a80e

</details>

## Changelog
:cl: RKz, nightred, Couls, Arturlang, GoblinBackwards
fix: no more temporary blindness when spawning in!
refactor: refactored blindness code to be less redundant and poorly applied.
fix: no more perma-blindness if blindness is improperly applied to you! Update_stat should actually do its job now.
code: removed duplicate method 'blind_eye', replaced in favor of 'adjust_blindness'
add: The Blind and Unconcious will now have monochromatic vision, because they don't know what colors are. This change is made in anticipation of adding blind-vision in the near-future.
/:cl:

### CODE REVIEW

**Comment by CydiaLamiales** [comment]
Reverting the revert, how deep can we go?

**Comment by Tsar-Salat** [comment]
> Reverting the revert

I might kill myself out of embarrassment if the reverted revert is reverted.

**Comment by Tsar-Salat** [comment]
AI eyes commit makes it so AIs handle blurriness too. Not a problem from my previous pr, but something important to have.

**Comment by HowToLoLu** [comment]
> Reverting the revert, how deep can we go?

The Revert to Revert that Reverts a Reversion for Reverting some controversial thing

**Comment by Tsar-Salat** [comment]
> Reverting some controversial thing

It's not controversial blindness sucks

I just forgor a single if statement in the previous pr

😭

**Comment by HowToLoLu** [comment]
> > Reverting some controversial thing
> 
> It's not controversial blindness sucks

That's what makes it even funnier

**Review by itsmeow — APPROVED** [review]
im so sick of this bug, the code looks OK, please fix this shit speedmerge time

**Pull request merged**
