### PR TITLE
Adds Pingles, a chefmade variety of chips

### PR DESCRIPTION
**Pull request by LodedDiper69**
## About The Pull Request

Adds the aforementioned ~Prongles~ Pingles, which requires 1 cardboard tube, 1 potato wedge, 1 onion slice and 10 cream to craft. The cardboard tube ends up as trash again after being eaten.

## Why It's Good For The Game

Letting chef cook a non-junkfood version of chips allows for more gimmicks. Plus more food variety is always good.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image

image

</details>

## Changelog
:cl:
add: Added a new type of food, Pingles
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
I like it.

**Review by Miliviu — CHANGES_REQUESTED** [review]
Sadly Prongles is a real thing :(
[prongles](originalprongles.com)
I would suggest changing the name to avoid Copyright issues!

**Comment by PowerfulBacon** [comment]
I like the idea someone came up with of pingles where they give you more food the higher your ping is

**Comment by LodedDiper69** [comment]
How the fuck is prongles a real thing. That doesnt even sound like a real food.

But sure, Ill change it to pingles. Give me a day.

**Comment by ike709** [comment]
@Crossedfall Does this PR pass the copyright vibe check? Cards Against Humanity already has a fake Prongles product / website.

**Review by Archanial — APPROVED** [review]

**Review by itsmeow — APPROVED** [review]

**Pull request merged**
