### PR TITLE
Adds Custom Beer Nukes

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
The Beer Nuke can now be loaded with custom reagents, and the foam from the subsequent event will contain those reagents.

## Why It's Good For The Game
If you can get your hands on both the nuke disk and the beer stained note, the world deserves some high tier pranking.

## Changelog
:cl:
add: The Beer Nuke can now be loaded with custom reagents, and the subsequent foam event will contain those reagents.
/:cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
Terrible idea. 🔑

**Comment by mcmeiler** [comment]
Come on Crossed, let me flood the station with Oozeling mutation toxin...

**Comment by Ivniinvi** [comment]
It's a high risk high reward item. You need *both* the nuke disk (the most heavily guarded item in the game) AND the quite rare beer stained note to do it, and on top of that there's an enormously obvious 90-second windup. The only thing I think it could use is an admin cancel button, but aside from that I think it's fine.

**Comment by Archanial** [comment]
Not a fan either
It's only griefing tool

**Comment by qwertyquerty** [comment]
Retroactive :key:

**Comment by zeskorion** [comment]
Retroactive 🔑 pretend it's a year ago and im still a maintainger

**Pull request closed without merging**
