### PR TITLE
Troublemakers - Midround Space Assholes

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Troublemakers, a idea inspired by goon's miscreants, that gives them a objective that is not just roleplay, but can actually be completed.

Troublemakers are not proper antagonists, in the sense that they cannot sabotage the station and attack security/witnesses, but they are exempt from the rules 'Be nice to eachother' or 'Follow SOP'. They have a goal, and can break any laws to complete it. 

Possible objectives are:
* Steal Ian (have a pet item for Ian on yourself)
* Steal Renault
* Steal Llamar
* Steal Captain's Flask
* Have [an absurd amount of credits] on yourself at the end of your shift
* Have the main AI purged of laws at the end of the shift
* Escape the station with [number] strange objects
* Escape with another identity
* Make sure there are n corpses in hallway
* Steal Runtime
* Make it away with an absurd amount of units of a certain drug (space drugs, meth, etc)
* Escape with an absurd amount of flesh organs
* Make a newsletter to compete with the curator
* Fake prophet (basically, you gain the rank of high priest and need to get away with X everburning candles, or become a robot)
* Make sure there are no more than X amount of functional cameras at the end of the shift (disabling them works)
* Escape with a fireaxe
* ~~Steal and escape with a stunbaton~~
* ~~Steal and escape with a disabler~~
* ~~Steal and escape with a sechud~~
* Make sure there are no prisoners in ~~brig~~ perma at the end of the shift
* Make sure there are XX number of living monkeys at the end of the shift (on the station)
* Steal a department prolathe board
* Steal someone's heirloom

## Why It's Good For The Game

Adds a little spice to the rounds and makes the game a little less boring.

## Progress

* [ ] Objectives
* [ ] Antag datum?
* [ ] Random antag event
* [ ] Admin interactions

## Changelog
:cl:
add: TODO changelog
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
First of all, half of these just encourage being a shitter

second of all, convert PR to draft.

**Comment by PowerfulBacon** [comment]
Steal and escape with a stunbaton
Steal and escape with a disabler
Steal and escape with a sechud

These are the same as objectives like capgun or hosgun, they are kill objectives in disguise.

**Comment by eeSPee** [comment]
> First of all, half of these just encourage being a shitter

Yes.

**Comment by francinum** [comment]
These objectives are awful.

Please take cues from goon.


```diff
Steal Ian (have a pet item for Ian on yourself)
- Steal objectives aren't interesting.
Steal Renault
- Steal objectives aren't interesting.
Steal Llamar
- Steal objectives aren't interesting.
Steal Captain's Flask
- Steal objectives aren't interesting.
Have [an absurd amount of credits] on yourself at the end of your shift
+ Actually kinda okay
Have the main AI purged of laws at the end of the shift
- This is an antag tier objective
Escape the station with [number] strange objects
- Waste of time
Escape with another identity
--- Literally an antag objective.
Make sure there are n corpses in hallway
--- L i t e r a l l y a k i l l o b j e c t i v e
Steal Runtime
- Steal objective *are not interesting*
Make it away with an absurd amount of units of a certain drug (space drugs, meth, etc)
~ Eh
Escape with an absurd amount of flesh organs
- Where are you supposed to get these.
Make a newsletter to compete with the curator
+ Good.
Fake prophet (basically, you gain the rank of high priest and need to get away with X everburning candles, or become a robot)
- I don't think this would work in the code.
Make sure there are no more than X amount of functional cameras at the end of the shift (disabling them works)
- Far more disruptive than it sounds.
Escape with a fireaxe
- Steal objectives aren't interesting.
Steal and escape with a stunbaton
--- Literally 'kill a security officer' or 'stab beepsky'
Steal and escape with a disabler
--- Literally 'kill a security officer' or 'order one from cargo'
Steal and escape with a sechud
--- Literally 'kill a security officer' or 'beat to death the arrivals locker'
Make sure there are no prisoners in brig at the end of the shift
--- Literally 'break out every prisoner'
Make sure there are XX number of living monkeys at the end of the shift (on the station)
--- Encourages creating a fuckload of expensive simplemobs.
Steal a department prolathe board
--- These are downright irreplaceable and is going to get you murdered.
Steal someone's heirloom
- Steal objectives aren't interesting.
```

**Comment by DatBoiTim** [comment]
> ```diff
> Make sure there are no prisoners in brig at the end of the shift
> --- Literally 'break out every prisoner'
> ```

This is actually literally a Security Crew Objective. Therefore, no.

**Comment by eeSPee** [comment]
> These objectives are awful.
> 
> Please take cues from goon.'

I specifically tried to make them more antagonistic and rooted in gameplay elements instead of roleplay.

> - Steal objectives aren't interesting.

I went with some steal objectives because they require you to break into high threat areas. Instead of the plain "break into X area and then just leave" like it is on goon, it's 'break into area and steal item'

> - This is an antag tier objective (Purge AI)

Maybe not on Sage. It frees AI on all its laws, but AI is not necessarily an antag. Allows roleplay opportunities, like 'free robot slavery' kinda guy.

> Escape with another identity

This should be someone else's identity but your own. It's not the changeling's 'kill specific target and take their identity'. It's a spin on goon's "Wear no ID" equivalents.


> Make sure there are n corpses in hallway
> Escape with an absurd amount of flesh organs

I know that these look murderbony. I wanted to be something like 'steal from medbay' or 'filthy the main halllway'. I guess the corpses in hallway and monkey objective can be fused into 'make x monkey corpses in hallway'

> Make sure there are no more than X amount of functional cameras at the end of the shift (disabling them works)
> - Far more disruptive than it sounds.

Yes, but also draws attention towards yourself. 

> --- Literally 'kill a security officer' or 'stab beepsky'

Noted.

> Make sure there are no prisoners in brig at the end of the shift
> --- Literally 'break out every prisoner'

You're right. I was thinking only perma-prisoners. This was meant to be a jailbreak objective.

> Make sure there are XX number of living monkeys at the end of the shift (on the station)
> --- Encourages creating a fuckload of expensive simplemobs.

Noted.

> Steal a department prolathe board
> --- These are downright irreplaceable and is going to get you murdered.

Hmmm... That may also be a good thing?

**Comment by DatBoiTim** [comment]
> Troublemakers are not proper antagonists, in the sense that they cannot sabotage the station and attack security/witnesses, but they are exempt from the rules 'Be nice to eachother' or 'Follow SOP'. They have a goal, and can break any laws to complete it.
---
> I specifically tried to make them more antagonistic and rooted in gameplay elements instead of roleplay.]

Pick one design philosophy please. 

Additionally, maybe don't track these. This way it encourages creativity with how people do this.

Also while you should generally follow SOP, it isn't a hard rule. SOP is already very IC.

> Maybe not on Sage. It frees AI on all its laws, but AI is not necessarily an antag. Allows roleplay opportunities, like 'free robot slavery' kinda guy.

Purged AI still causes a lot of problems, and is basically sabotage. 
Now, if you wanted to say have an objective along the lines of: have the AI with X standard lawset(Robocop, Paladin, Corporate, etc.) may be a bit better.

> This should be someone else's identity but your own. It's not the changeling's 'kill specific target and take their identity'. It's a spin on goon's "Wear no ID" equivalents.

Then make it like that?

>>> Make sure there are no more than X amount of functional cameras at the end of the shift (disabling them works)

>>Far more disruptive than it sounds.

> Yes, but also draws attention towards yourself.

Literally sabotage. Which as you've said, is not something these guys should be doing.

>>> Steal a department prolathe board

>> These are downright irreplaceable and is going to get you murdered.

> Hmmm... That may also be a good thing?

PICK. A. DESIGN. PHILOSOPHY. Are these guys full antags who should expect to be murdered? Are these guys basically meant to be something for security to occupy themselves with without being immediately eligible for capital punishments?

**Comment by eeSPee** [comment]
> PICK. A. DESIGN. PHILOSOPHY. Are these guys full antags who should expect to be murdered? Are these guys basically meant to be something for security to occupy themselves with without being immediately eligible for capital punishments?

Point taken. This is all concept phase, so it's susceptible to change and feedback.

While I said 'no sabotage', I went with the 'no permanent sabotage' philosophy in mind. While these guys shouldn't delam the SM, kill the AI or render entire departments unusable, they can still cause repairable sabotage, like breaking into a department to get required items, cutting cams, etc.

I also tried to target all the departments, including AI and even hallways, hence the cut cams/monkeys/corpses objectives.

**Comment by eeSPee** [comment]
Nvm I'm stupid.

> Anyways, worth mentioning that this doesn't fit the spirit of miscreants at all.
> 
> Miscreant objectives aren't about winning, they're basically pre-packaged gimmicks that you play the round with, very very few of them are as simple as "Do X, X is now done."
> 
> Most of these are just dumb minor antag objectives.
> 
> Like the "steal X pet" objectives under a system taking proper inspiration would be something like this IMO
> 
> > "Create a zoo using the pets of the station as centerpieces"
> 
> You have a reason to take ian, but it's a wide gameplay opportunity which engages multiple people.
> 
> Most of these can be rewritten in similar ways, e.g. "Protect the freedom of silicons" which again, is round-long and creates opportunities for fun should you choose to pursue it. (That one could probably work with our silicon policy, but eeh, probably wouldn't make it in.)

That's the two things I don't like about miscreants is that there is no in game way to track their objectives, and the objectives are basically 'roleplay this way'.

And like bacon said, we already have abductees that work the same way more or less. Could just make abductees from some other source.

**Comment by Sinestia** [comment]
> That's the two things I don't like about miscreants is that there is no in game way to track their objectives, and the objectives are basically 'roleplay this way'.

That's what makes them a good feature. 

They aren't near as prone to just being stale metagamed garbage.

**Comment by ta3370** [comment]
Look, these are in no way similar to Miscreants, and you're lying if you claim they are. Miscreants is a gimmick suggestion system to add story to the round. This is just another thing for rolling antag and combat, and getting the tissues out for powergamed greentext. If you need mechanical greentext for a system like this, then it's not doing it's job of being a story generator.

Focus on interesting gimmicks and remove the greentext system, and this could turn into something good. Otherwise it's just antag-lite.

Speaking of, even outside of this, Antags who just rush greentext through optimized actions, never truely greentext. Because that adds literally nothing to the round for anyone else and is just annoying. The point of any form of antag is to create and form a story for the round like a Rimworld Storyteller. This falls into the same pit that full-tags mechanics have of _actively discouraging_ creating a story other than "oh haha, Spaceman McUrist did the exact same shit as always to get secured greentext"

**Comment by francinum** [comment]
Listen to me.

Listen to me very fucking carefully

cooltext389324369997765

**Comment by ItsTisme** [comment]
>and the objectives are basically 'roleplay this way'.

its almost as if bee is a roleplay server....

**Review by francinum — CHANGES_REQUESTED** [review]
I'm not letting this get in without *major* changes.

**Comment by ike709** [comment]
🔑

**Comment by francinum** [comment]
🔑 
And those changes are something I don't believe you're willing or intend to make.

**Comment by eeSPee** [comment]
test

> Listen to me.
> 
> Listen to me very fucking carefully
> 
> cooltext389324369997765

Yes, which is why I disliked the concept of miscreants and wanted to take a new direction.

We already have something like that, and they have these problems:
* The objectives have no IC incentive to be followed, so they can just be ignored.
* The objectives have no pass/fail state without admin intervention.
* They are basically 'roleplay this way' objectives and not 'roleplay however you want to get this result/objective' objectives.

I want to bring something similar to Bee, but a little bit different:
* They can have a % chance to replace crew objectives round start.
* They could replace crew objectives altogether for assistants.
* They are a trauma or randomly assigned midround.
* People become miscreant as a result of certain actions (getting staminacrit by stunbaton while not antag, getting gulaged if not antag), etc. But this one can fail in many ways.

**Comment by francinum** [comment]
This is not a new direction. You are not making a minor flavor to the round

You are making a new antag.

The solution is to do what they do *better.* Please for the **LOVE OF FUCKING GOD** stop comparing them to abductees.

**Pull request closed without merging**
