### PR TITLE
fixes extrapolators again

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
fixes another bug related to isolating multiple symptoms at once

## Why It's Good For The Game
bugfix

## Testing Photographs and Procedure
try replicating the bug. failed to replicate bug

## Changelog
:cl:
fix: really fixes extrapolators this time
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — DISMISSED** [review]

**Comment by PowerfulBacon** [comment]
What bug?

**Comment by zeskorion** [comment]
> What bug?

if fast enough, you could isolate multiple symptoms at once

**Comment by zeskorion** [comment]
I tested it, and it works. 🤷

**Comment by zeskorion** [comment]
the bug involved bringing up multiple input menus to bypass the check and then executing these menus. this fixes that

**Review by Archanial — APPROVED** [review]

**Pull request merged**
