### PR TITLE
Converts decals from components to elements.

### PR DESCRIPTION
**Pull request by ike709**
Ports the following PRs in an attempt to improve memory usage:

https://github.com/tgstation/tgstation/pull/53922
https://github.com/tgstation/tgstation/pull/53954
https://github.com/tgstation/tgstation/pull/53967

Needs to be tested.

### CODE REVIEW

**Comment by Moccha-Bee** [comment]
based

**Comment by ike709** [comment]
Survives a round on the staging server but it still needs a proper testmerge.

**Comment by PowerfulBacon** [comment]
Couldn't testmerge due to conflicts with another PR (#2869) will testmerge a bit later

**Comment by PowerfulBacon** [comment]
Testmerged onto sage

**Comment by Cenrus** [comment]
Decals appear invisible to me

**Comment by ike709** [comment]
@Cenrus Be more specific.

**Comment by Cenrus** [comment]
image

They're not showing up, here's an image of my perspective
I've tried clearing my cache, to no results.

**Comment by ike709** [comment]
Very weird because they definitely show up to me. Do you have hardware acceleration enabled?

**Pull request closed without merging**
