### PR TITLE
Ports "Better Slappin Animations"

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Ports [#52517](https://github.com/tgstation/tgstation/pull/52517)
No need to include before (since we all play the game, right?)
After:
68747470733a2f2f66696c652e686f7573652f724c4a7a2e676966

## Why It's Good For The Game

They look better

## Changelog
:cl: actioninja 
add: New slapping animations
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Include a link to original PR and if possible a before and after

**Comment by Archanial** [comment]
> 
> 
> Include a link to original PR and if possible a before and after

Done. I would really recommend a tm then a vote since it's visual mostly.
I also have no idea why is travis mad.

**Comment by Mick1299** [comment]
It looks like you headbutt the thing you're hitting

**Comment by ivanmixo** [comment]
I don't think this looks better tbh. It looks really janky.

**Comment by qwertyquerty** [comment]
No reason for the item to be popping out at the camera

**Pull request closed without merging**
