### PR TITLE
Change die of fate single use for per person

### PR DESCRIPTION
**Pull request by selinayess**
## About The Pull Request

Change the die of fate reward from greed slot machine so that it can be used per person used and another person can use it again but per person could only do single roll

## Why It's Good For The Game

So the reward of the greed machine could be worth it and more engaging and people would do the slot greed machine more

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
tweak: tweaked the dice so more people could use it
/:cl:

### CODE REVIEW

**Comment by Dejaku51** [comment]
you fucked up

**Comment by AnCopper** [comment]
Lol.

**Comment by EvilDragonfiend** [comment]
So, A PR that Monkestation being as upstream of Beestation?

**Comment by St0rmC4st3r** [comment]
Formula of probability of event A happening at least once per n tries with probability of each individual try = p, where q = 1 - p (i.e. q = probability of event not happening)
image
The probability of a Wizard spawn from the die of fate = 1/20, or 5%.
Let’s assume the rolling is happening at peak hours, when there is 50 living crew members, each of which rolls the die.
Then image
Are you sure you want it to create at least one wizard with 92% probability each time the ruin is found?

**Comment by Rukofamicom** [comment]
> Consider redoing the PR

Also please consider not redoing the PR. Single-use dies of fate do not need to become multi-use unless wizard is removed from the pool.

**Comment by PowerfulBacon** [comment]
image
lmao

**Pull request closed without merging**
