### PR TITLE
Fixes alien eggs being deleted before hugger is spawned

### LINKED ISSUE #5666: Xeno Eggs not hatching properly
# Round ID:33724

# Testmerges: #5442

# Reproduction:
Laid some eggs as Queen in virology, openned them manually and nothing came out, I cannot think of anything that could have caused it

### PR DESCRIPTION
**Pull request by UmbralMoth**
## About The Pull Request
Fixes #5666 
Should prevent the Queen from spam-clicking the egg and causing it get deleted before the hugger has the chance to spawn in by adding an extra status to the egg called "BURSTING", followed by a message to notify that the egg is in process of hatching.

## Why It's Good For The Game
Fixes the possibility of alien egg being deleted before a hugger spawns.

## Changelog
:cl:
fix: fixes alien eggs from disappearing before hugger spawns
/:cl:

### CODE REVIEW

**Review by MNarath1 — CHANGES_REQUESTED** [review]
as the other defines also get undefined at the end of the file i suggest you add your new additional define to that too

**Comment by UmbralMoth** [comment]
Done, just forgot about that bit, been a fair bit since I fiddled with the code so forgot to actually undefine it.

**Comment by MNarath1** [comment]
> 
> 
> Done, just forgot about that bit, been a fair bit since I fiddled with the code so forgot to actually undefine it.

honestly i think its a bit silly to use defines for a object if they are only used locally anyway but i guess its consistent with the original code

**Comment by UmbralMoth** [comment]
> honestly i think its a bit silly to use defines for a object if they are only used locally anyway but i guess its consistent with the original code

Well originally I wanted it to be a boolean variable, but it would just look out of place with the rest of the code, so I decided to just include it as another defined stage instead.

**Comment by MNarath1** [comment]
> 
> 
> > honestly i think its a bit silly to use defines for a object if they are only used locally anyway but i guess its consistent with the original code
> 
> Well originally I wanted it to be a boolean variable, but it would just look out of place with the rest of the code, so I decided to just include it as another defined stage instead.

yeah having that 3 defines and then suddenly one local var doing the exact same would look strange and be inconsistent.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
