### PR TITLE
[Port] Makes the BSA more stylish

### PR DESCRIPTION
**Pull request by SomeAngryMiner**
## About The Pull Request

Direct port of tgstation/tgstation/pull/44911 , wich changes the sprite of the BSA beam and adds a splash to its start. nothing big, but its nicer than the MS paint beam it had before for such an expensive objective.
## Why It's Good For The Game

Looks better
## Changelog
:cl:
imageadd: Nanotrasen Shipped new Bluespace Lenses for their artillery, "supposedly" increasing explosive capacity. Hey, atleast it looks nicer.
/:cl:

### CODE REVIEW

**Review by MarkSuckerberg — APPROVED** [review]
looks good

**Comment by qwertyquerty** [comment]
Not 100% sure why we need separate icon states for west and east, doesn't dir cover that?

**Comment by MarkSuckerberg** [comment]
That's a good point, they look exactly the same, just flipped

**Comment by SomeAngryMiner** [comment]
ill give it a quick modification and test, then.

**Comment by SomeAngryMiner** [comment]
apparently, DIR doesnt like to handle this.

**Pull request merged**
