### PR TITLE
Fixes Radstation's Airmix so that it isn't completely borked

### PR DESCRIPTION
**Pull request by HowToLoLu**
## About The Pull Request
Thanks to some broken mapping icon helpers, RadStation's atmospherics air mixer doesn't work at all roundstart due to poor configuration. This corrects the air mixer- and I'm working on a PR for fixing the poor state of some atmos devices in mapping (currently mixer icons are broken references).

## Why It's Good For The Game
Unoptimal setups are one thing- setups that outright just don't work are another, and should be avoided.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

## Before:
image
*Image Provided by Snackbar on the discord.*

## After:

image

</details>

## Changelog
:cl:
fix: RadStation's Air Mixer no longer requires roundstart attention due to being improperly setup
/:cl:

### CODE REVIEW

**Comment by HowToLoLu** [comment]
Closing this branch because I've noticed that a label was added to this that I don't think should've been added, which probably hints to trouble with the branch.

**Comment by PowerfulBacon** [comment]
No it's fine, it's cause you used the word config somewhere

**Comment by PowerfulBacon** [comment]
fix: RadStation's Air Mixer no longer requires roundstart attention due to being improperly **configured**

**Comment by HowToLoLu** [comment]
Thanks bacon for pointing that out. I honestly thought something was with the files and was close to nuking my fork for the 3rd time.

**Comment by PowerfulBacon** [comment]
The tags are really simple searches, if the files aren't actually changed then you don't need to worry about it

**Review by PestoVerde322 — APPROVED** [review]
Should be good to go, approved.

**Pull request merged**
