### PR TITLE
auto map voting

### PR DESCRIPTION
**Pull request by qwertyquerty**
## About The Pull Request

Adds a config option where a map vote will be automatically triggered at round end. The map will also automatically switch when the vote ends.

Kev or CF plees add the following to the config:

```
## Automatic Map Vote
## Whether a map vote will be triggered at roundend.
AUTOMAPVOTE
```

## Why It's Good For The Game

Democracy FTW.

## Changelog
:cl:
add: Automatic map vote
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
I could've sworn this already existed. Maybe it was on bay. ¯\\\_(ツ)_/¯

**Comment by qwertyquerty** [comment]
APPROVE OR DISAPPROVE NERD

**Comment by ike709** [comment]
TRAVIS HADN'T FINISHED YET.

**Comment by ike709** [comment]
YOU GOT ME KILLED IN TF2 TYPING THAT RESPONSE AND MERGING THIS.

**Comment by qwertyquerty** [comment]
AHAHAHAHAHAHA NERD

**Pull request merged**
