### PR TITLE
Frostwings

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

The Frostwing is a bird-like creature native to GlowStation's ice plains. They are agile and able to climb and fly, using their powers to steal resources and technology from the station in order to build their base on the ice plains. They are intelligent, but not technologically advanced (anymore), having lost their civilization after the station was constructed, and have been scavenging resources from the station in order to build their own base on the ice plains. They are not inherently hostile, but will defend themselves if necessary. However, they are not above using deception and stealth to achieve their goals.

The Frostwings have a hierarchical society, with a single leader at the top. They are organized into small groups, each with their own tasks and responsibilities. The leader is responsible for making decisions for the group and ensuring that their objectives are met.

### Objectives

- Steal resources and technology from the station to build their base
- Avoid being killed or captured by the crew
- Use their abilities to evade capture and escape with their stolen goods

### Abilities

- Flight: Frostwings are able to fly using their wings, allowing them to quickly move around the station and access areas that may be difficult for the crew to reach.
- Cold resistance: Frostwings are adapted to the cold climate of their home planet, and are able to withstand the freezing temperatures outside the station. However, they take damage when inside the station's warm atmosphere, and must use hardsuits to remain inside for extended periods of time.
- Cold healing: When at their regular body temperature, Frostwings can slowly heal burn damage, allowing them to safely make multiple short trips into a warm environment without accumulating excessive damage.

### Weaknesses

- Damage from warm atmosphere: Frostwings take damage when inside the station's warm atmosphere, and must use hardsuits to remain inside for extended periods of time. However, hardsuits prevent them from using their flight abilities and slow them down, thus weakening them.
- Vulnerable to attacks: Frostwings are physically weak and can be easily killed or captured by the crew if they are caught.
- Limited time inside the station: Without a hardsuit, Frostwings can only remain inside the station for a few minutes before taking significant damage.

### Possible interactions with crew

If the Frostwings are successful in acquiring enough resources and technology, they will construct a larger base on the ice plains and continue to advance their own technology. This could potentially pose a threat to the station and its crew in the future. It is up to the crew to decide how to handle the Frostwings and their actions.

- Friendly: Crew may choose to be friendly with the frostwings, offering to trade goods or technology in exchange for labor or materials scavenged from the ice plains.
- Neutral: Frostwings may choose to remain neutral, simply stealing resources and technology without interacting with the crew.
- Hostile: Frostwings may become hostile if provoked or if their efforts to steal resources are thwarted, attacking crew members and causing chaos on the station.

### Reproduction

Frostwings are the last of their species, so they need to be able to make more frostwings. They can make more frostwings using the modified clone pod, "avian egg synthesizer" that spawns in their base. They have 3 to start, and if they are broken they are permanently lost and cannot be rebuilt. They can be repaired using a welder and cannot be deconstructed.

The egg synthesizer works as such:
- Put in 100u synthflesh
- All synthflesh is instantly consumed, incubation starts
- During incubation, power use increases drastically. If power is lost or it breaks, the incubation cycle is lost and you do not regain your synthflesh.
- Incubation takes 3.5 minutes
- At the end of incubation, a frostwing egg is spawned that ghosts can click on to take the spawn, and a new frostwing is created.

The requirement of synthflesh further mechanically encourages engineering prowess and tech thievery, as frostwings will want to steal things like plumbing materials, lathes, chemistry boards, etc and build them at their base. They will also need a reliable way to power the pods, since they only start with a partially charged SMES and an APC, with no other way to generate power.

### Admin Policy

Frostwings should not be killing crew except in self defense, and even then should avoid doing so. They are smart and know what technology is AND how to use and acquire it- they simply lack that technology and want to recover their civilization from the impact NT's new space station had on them.

**Escalation To Follow: Normal**
**Station Response: Lavaland-ish (they should however, not kill on sight if there is no justification for doing so)**

Due to the inability to restrict this game wise, they can read UIs but they should not be using UIs to communicate with crew like paper etc, that is not in the spirit of the antagonist. The curator or a translator circuit are the best options here.

Frostwing's main goal, and overall what their administration should be based around, is expanding their home base and acquiring resources.

The last few frostwings that survived (the players) are quite smart, and know their way around departments, they are adequate engineers and doctors.

Knowledge of the station: Frostwings have been studying the place for a while, so they are familiar with its general layout and function. Human culture, however, is a mystery.

## Frostwing Lore :tm:

Frostwings are native to the ice planet, and existed for a long time before the station was constructed.

The station's construction interfered with their natural hunting grounds and drove away their food sources, summoning dangerous spiders drawn to the heat. The station was also built upon a natural cold fissure where they would store their eggs for hatching, meaning they no longer had a suitable way to reproduce.

The last frostwings came across an abandoned ship from Nanotrasen's initial scouting missions and refitted it to be a home, and modified cloning technology aboard to create an egg synthesizer and incubator, so they could continue their species in the event of their death.

They died, and now it's up to the new frostwings to build a home and grow their numbers, using the resources available on the station and their unique abilities suited to the environment.

## Concept Art

Generated by DALLE 2

image

image

image

## Credits

Myself: Idea of ice birds (inspired by dudes that steal), Code, Frostwing egg and incubator sprites
kit_katz: Sprites: Frostwing, Frostwing meat, Frostwing feather
Spockye: Frostwing base
ChatGPT: Idea of dude that steals, writing design doc
DALLE 2: Concept Art

Sounds (all CC0):
- Wing open/close: https://freesound.org/people/ani_music/sounds/244978/
- Caw 1&2: https://freesound.org/people/basedMedia/sounds/548106/
- Caw 3&4: https://freesound.org/people/nigelcoop/sounds/75162/

## Why It's Good For The Game

They add more variety and potentially interesting situations to the round, as well as giving ghosts another role to play, or potentially being a role that is seeked out by players specifically, similar to ashwalkers.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Sound demo

https://user-images.githubusercontent.com/10366817/218295615-2872839a-47d5-4005-b462-8b245dc91e60.mp4

Sprite

image

image

image

image

image

image

Frostwing base (by Spockye)

image

Language

image

Names

image

Incubator

image

image

Egg

image

Body temp

image

Healing after body temp restored

image

Roundend report

image

</details>

## Changelog
:cl: itsmeow, kit_katz, Spockye, ChatGPT
add: Added Frostwings, and ice planet exclusive bird antagonist that steals from the station.
refactor: Species now support custom body temperature settings.
tweak: Fluff papers no longer have absurd amounts of health and can be broken easily.
add: GlowStation: Added combustion/rocket jetpacks to the armory, for use against flying threats.
/:cl:

### CODE REVIEW

**Comment by llol111** [comment]
I like the *idea* here, but i forsee this being a nightmare for admins. Theres good reason ashies are not allowed to go to the station. 
Might be diffrent if they're not allowed to just murder like ashies are allowed to, but i still forsee a big headache.

also -1 for not making them look like pingu

**Comment by itsmeow** [comment]
They aren't really supposed to murder except in self defense. Their primary goal is petty resource/tech thievery and expanding their numbers/home. Killing humans preemptively is really against their nature, they're intelligent and not the kind to just kill without reason.

**Comment by llol111** [comment]
Right, but even if we put them just on antag or even self-defense escalation, they will have the potential to introduce *signifcant* chaos and disturbance to the round.
Now, i get that thats kind of the idea here. Like i said, i do like the idea. It sounds fun.

But maybe this'd be better off being a full-fleged antag rolle instead of just a ghost role?

imo always-avaiable ghost roles like ashies or this should be a minor impact on the round if any, a side piece to the actual action of the gamemode running. 
I think having security chase around a clan of thiving birds on the station **in additon to lings and traitors or a cult or whatever** might be a bit much.
This would be aliviated by having them be proper antags. 

We'll have to see how it turns out in testmerges i suppose though, maybe im just worrying to much. 
Concept should be fun.

**Comment by itsmeow** [comment]
I think that's a fair argument- I've considered having them be a round
start option in the jobs menu if they were supposed to spawn that round.

There's a couple considerations here:
- GlowStation will not always be the map, so that reduces their chances of existing to >40 players, making it already restricted to very specific periods
- Making a fake job pref for these would probably be a medium amount of effort
- Making this a ghost role gives players who specifically want to play it the chance to just hit observe instead
- We could make, say, 50% of glowstation rounds spawn a frostwing base
- Mechanically, a ghost role is identical as long as we make it clear from a rules perspective that it's an antagonist - we could change it from using spawners to using polls like most other midrounds, but again they are not really midrounds, and they need a way to reproduce
- Overall, mechanically, the easiest way to implement it is as a ghost spawn. People who died will still have to wait three minutes to have the chance to take a spawn - and even then the chances of an open one existing are low as I expect most spawns will be taken quickly.
- They *are* an antagonist, they just aren't controlled by a random event or dynamic. They have an antag datum, objectives, etc.
- Making them controlled by dynamic's midround system is not very useful, since they are not midrounds
- Having them part of dynamic's roundstart system would severely limit their spawn chances - I doubt we would see them often at all, since they already depend on a specific map being active and highpop.


Overall, I still think the best course of action is keeping them as a roundstart available ghost role, that has a flat chance to exist on glowstation.
- This gives players who want to play as it a chance to grab the role roundstart, or observe and wait for more to be created
- It gives a known, consistent chance they will spawn
- It doesn't muddle the existing dynamic threats with something that won't usually be able to occur outside of glow
- It is technically simple to implement

Downsides:
- Because it doesn't cost threat, it could could potentially overwhelm the crew, however this is probably balanced by the fact that it's highpop only, and that they aren't directly killing anyone

**Comment by WrillWasTaken** [comment]
Their base could probably use some clothes or bags or something besides firesuits. The majority of the round was just a hunt for clothes and a backpack.

**Comment by Fronsis** [comment]
> Right, but even if we put them just on antag or even self-defense escalation, they will have the potential to introduce _signifcant_ chaos and disturbance to the round. Now, i get that thats kind of the idea here. Like i said, i do like the idea. It sounds fun.
> 
> But maybe this'd be better off being a full-fleged antag rolle instead of just a ghost role?
> 
> imo always-avaiable ghost roles like ashies or this should be a minor impact on the round if any, a side piece to the actual action of the gamemode running. I think having security chase around a clan of thiving birds on the station **in additon to lings and traitors or a cult or whatever** might be a bit much. This would be aliviated by having them be proper antags.
> 
> We'll have to see how it turns out in testmerges i suppose though, maybe im just worrying to much. Concept should be fun.

After the test-round i can 100% agree that llol made a perfect prediction.

Overall having them roundstart it's very detrimental to the round(considering antagonists rolls as well) because you quickly get too many busted windows that they use to get in, meaning a lot of room get depressurized, and once the future ''frostwing mains'' realize where exactly the synthflesh is (chemistry, cmo office, cloning) they will just start to meta-target those areas to quickly get their hands on funny juice to produce more of them

If i have to define what i witnessed firsthand and observed: They're a mix of a greytider+pirate with absolutely massive movement speed that surpasses the hit & run tactics of Pirates

I encountered a hostile one (who, funnily enough attacked first, but that's okay because people needs to slowly adapt to the ''lavaland escalation'' relevant to them) and, fighting them outside in their ''home turf' it's impossible, considering that players need to still learn how to ''aim/look up and down'' but they can basically attack, fly up, lay on top of your head, repeat and if they get a grab on you they can grab you and drop you to your demise, i feel like they should have an inner cooldown on that otherwise it would be impossible to stop them

The non-hostile ones were weird, they just tried to hack into chemistry, rushed tool storage, deconstructed windows everywhere to escape making a lot of areas lose O2 and they even tried to communicate with the crew to try and bargain for synthflesh in exchange of the dead body of someone, until they realized they couldn't understand common

Having their presence early on disrupts a lot of plans of everyone, because your department is suddenly hit with a random tider-thief that can dissapear once they reach a window, has security focusing on them 15 minutes into the round, etc

They should either be an antagonist exclusive to Glow or have their spawner be enabled after a certain time on the shift passed 

At the same time people are still, understandably, getting used to glow, to the z-level mechanics, learning where everything is.. i feel like on top of that you add an antagonists thief with high mobility will make a lot of chaos unfold and the station will not be prepared or they'll just rush lethals and reduce any potential RP

They certainly need a good written text when they spawn on what they can and can't do to prevent headaches and random frostwing going gamer mode

One final thing is that there should be a clear precedent on how smart they are and what they can and can't do, i believe in that round when i ahelped they replied to me that they're like a ''third-world pirate'' so they know a little bit of tech, but it should be clear.. Do they know how to operate a stun-baton? Do they know how to deconstruct machines, Do they know how to flight shuttles, operate pda's, using radios, etc i'm just giving examples i understand they can at least make chem-factories of synthflesh(?) and some basic deconstruction but they shouldn't reach the point where they can just rush a random sec officer or a crewmember with a teleprod, and suddenly have access to a lot of areas.

I just think the synthflesh thing should be changed for something else, having this species dependant of a specific reagent will mostly end up causing them to rush the same areas everytime to optimize the amount of Frostwings they produce, maybe they could have some weird biogenerator that accepts certain materials to slowly produce synthflesh(or designated frostwing juice) so they're not locked down by having to ultimately raid the same areas every time.

**Comment by itsmeow** [comment]
> Overall having them roundstart it's very detrimental to the round(considering antagonists rolls as well) because you quickly get too many busted windows that they use to get in, meaning a lot of room get depressurized, and once the future ''frostwing mains'' realize where exactly the synthflesh is (chemistry, cmo office, cloning) they will just start to meta-target those areas to quickly get their hands on funny juice to produce more of them

It's not really meta the way they are intended. They lived on the ice plains before the station existed and know a fair amount about the station and its tech.

> If i have to define what i witnessed firsthand and observed: They're a mix of a greytider+pirate with absolutely massive movement speed that surpasses the hit & run tactics of Pirates

Entirely countered by the fact that they slowly die within the station unless they completely forgo their flight abilities.

> I encountered a hostile one (who, funnily enough attacked first, but that's okay because people needs to slowly adapt to the ''lavaland escalation'' relevant to them) and, fighting them outside in their ''home turf' it's impossible, considering that players need to still learn how to ''aim/look up and down'' but they can basically attack, fly up, lay on top of your head, repeat and if they get a grab on you they can grab you and drop you to your demise, i feel like they should have an inner cooldown on that otherwise it would be impossible to stop them

Fighting a frostwing outside is a death sentence. If you piss one off, that's your fault. This one in particular was not really acting as intended.

> The non-hostile ones were weird, they just tried to hack into chemistry, rushed tool storage, deconstructed windows everywhere to escape making a lot of areas lose O2 and they even tried to communicate with the crew to try and bargain for synthflesh in exchange of the dead body of someone, until they realized they couldn't understand common

I was one of them - we deconstructed maybe two windows. One was in a main hall, so I guess fair but the rest were pretty isolated.

We know we can't understand common, in fact, I was arrested and had no idea what was being said until the Curator showed up.

> Having their presence early on disrupts a lot of plans of everyone, because your department is suddenly hit with a random tider-thief that can dissapear once they reach a window, has security focusing on them 15 minutes into the round, etc

The things is they don't really work as a full on midround. They were however intended to have a 5 minute delay or so, I have now added that.

> One final thing is that there should be a clear precedent on how smart they are and what they can and can't do, i believe in that round when i ahelped they replied to me that they're like a ''third-world pirate'' so they know a little bit of tech, but it should be clear.. Do they know how to operate a stun-baton?

I have just added the admin policy section a few hours ago. Mega was mistaken and did not know the full details for that ahelp.

> I just think the synthflesh thing should be changed for something else, having this species dependant of a specific reagent will mostly end up causing them to rush the same areas everytime to optimize the amount of Frostwings they produce, maybe they could have some weird biogenerator that accepts certain materials to slowly produce synthflesh(or designated frostwing juice) so they're not locked down by having to ultimately raid the same areas every time.

This is probably a good idea, but encouraging robbing a wide variety of spaces is kind of hard to encourage mechanically.

They are already incentivized to rob engineering for tools, power, and construction material. They may also want to rob cargo for synthflesh, and medical for chemistry and medical supplies for other frostwings.

Robbing science is unlikely, robbing security could be a part of a "war".

> They certainly need a good written text when they spawn on what they can and can't do to prevent headaches and random frostwing going gamer mode

This does exist, one of them just ignored it, ran off, and went gamer. Me and wrill however were the peaceful ones.

> They should either be an antagonist exclusive to Glow or have their spawner be enabled after a certain time on the shift passed

They are glow exclusive, start after ~5 mins into the round, and will not spawn on every glow round.

**Comment by itsmeow** [comment]
- Caw emote
- Flap emote

**Comment by itsmeow** [comment]
God they are an absolute blast to play, truly something

**Comment by itsmeow** [comment]
There was a bug where a nameless frostwing spawned in roundstart. May be related to pressing "No" on the "Do you want to spawn" prompt? Also, incubators need to use polls, big time. Aggregating the polls might prove difficult though. I guess three polls at once is manageable if not ideal.

**Comment by itsmeow** [comment]
Dragged down by the death of GlowStation. Another day, Frostwings. You were too ambitious for your own good.

(I will not let this idea die, they will live on somehow. If I have to redesign Glow or port icebox...)

**Comment by itsmeow** [comment]
LIVE ON MY DEAREST!! SAVED BY LUMMY!!!! GLOWSTATION WILL RUN ONCE MORE SOMEDAY!!!

**Comment by itsmeow** [comment]
Okay from what I understand people don't want Glow back so this will have to wait

**Pull request closed without merging**
