### PR TITLE
Pubby Improvement: Science

### PR DESCRIPTION
**Pull request by imsynthex**
## About The Pull Request

Pubby

## Why It's Good For The Game

Pubby bad, this makes Pubby slightly less bad

## Changelog
:cl:
tweak: Made it so there is no hallway running through Science on Pubbystation
add: Added a nanite lab to Pubbystation Science
/:cl:

### CODE REVIEW

**Comment by imsynthex** [comment]
In my honest opinion this should be merged preferably before something new breaks it.

**Review by AnCopper — CHANGES_REQUESTED** [review]
image
Don't make pipes go trough walls, this is really bad practice and looks ugly.

**Comment by imsynthex** [comment]
Made it into this, I agree on the older one looking ugly, but by default pubby has a some pipes running through walls and on normal pubby supply and scrubber pipes already run through walls so this is up to pubby standard
image
image

**Comment by BrumalLake** [comment]
atmos techs get boned

**Comment by jupyterkat** [comment]
don’t do it, there’s a holodeck expansion pr on pubby that will break this

**Comment by williamcll** [comment]
> don’t do it, there’s a holodeck expansion pr on pubby that will break this

Merging this seems a lot more important than holodeck fixes

**Comment by jupyterkat** [comment]
sure, if you really want the plasma simulation holodeck to fill the entire hallway next to it with plasma too

**Comment by BrumalLake** [comment]
if someone does that they're gonna open the airlock anyway

**Comment by jupyterkat** [comment]
i don’t know, maybe an ai mistakenly presses that button? people make mistakes? it’s buggy behavior and every holodeck program is cut in fucking half?

**Comment by ivanmixo** [comment]
It just looks like meta sci slightly reordered. Ew. Try at least __something__ different rather than just modeling every map after meta.

**Comment by imsynthex** [comment]
The only similarity is has with Meta sci is the fact that the R&D lab is to the left of the entrance airlock, other than that there's no similarities?

**Comment by ImSynthex** [comment]
I mean left (of the entrance airlock) 😳

**Comment by ivanmixo** [comment]
Took away everything that made pubby sci unique

**Comment by imsynthex** [comment]
I made this PR for 2 reasons:

1. Pubby sci doesn't have a nanite lab
2. There is no airlock protecting RnD lab or robotics, which is just a clear oversight and a flaw that I saw pointed out on a Pubby feedback thread

If you have any suggestions on how to fix those 2 problems and make it unique at the same time, I'd love implement them. Just general blanket statements about "It's bad" and "It's not unique" don't help me in any way to make the PR any better

**Comment by ImSynthex** [comment]
jk i knew that would work

**Comment by imsynthex** [comment]
ok so for the 12907035th time, im closing this because im an idiot and did a thing on my local master, i'll just reference this in my new and not improved PR, not sorry for the lack of inconvenience on your end (yes, this can technically be fixed, no, im not going to)

**Pull request closed without merging**
