### PR TITLE
Removes alpha passthrough on laser projectiles

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Removes alpha passthrough on laser projectiles.

## Why It's Good For The Game

It just doesn't work, and its a bit annoying with how many combat roles get invisibility.

## Testing Photographs and Procedure

https://github.com/user-attachments/assets/10a37440-553a-4fe2-a12f-62d9798af3e0

## Changelog
:cl:
balance: Removes alpha passthrough on laser projectiles
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
IIRC, correct me if i'm wrong this should affect.. The invisible xenos, the genetic mutation and ninjas?

Or maybe the invisible box from stealth implant?

**Comment by PowerfulBacon** [comment]
It will, yea

**Comment by Rukofamicom** [comment]
Rip ninja

**Comment by MarkusLarsson421** [comment]
What if it is a percentage of it going through instead? Say 50% by default, this could be tweaked for each situation.

**Comment by PowerfulBacon** [comment]
Maybe the ninja suit just needs more than 30 armour against lasers.

**Review by Rukofamicom — APPROVED** [review]

**Comment by Rukofamicom** [comment]
Let their sword deflect (not reflect) shots similar to sleeping carp while costing stamina like blocking and they'll feel balanced for the power level ninja is supposed to be.

**Comment by Rukofamicom** [comment]
Mobile misclick moment

**Review by EvilDragonfiend — APPROVED** [review]

**Comment by Rukofamicom** [comment]
Why was this merged

**Comment by Rukofamicom** [comment]
Ninja now defenseless because this merged ahead of adjacent changes

**Pull request merged**
