### PR TITLE
Shuttle code cleanup (Dependency: #6113)

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Performs some minor code cleanup on shuttles, moves autopilot and docking functionality to the shuttle object rather than the shuttle console.
Uses signals for better communication between objects and to prevent hard-dels.

## Why It's Good For The Game

Cleaner code, less hard-dels.

## Changelog
:cl:
code: Cleans up supercruise shuttle code.
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
instead of marking procs as private use PRIVATE_PROC() or PROTECTED_PROC() lints

**Comment by PowerfulBacon** [comment]
Do not merge pending https://github.com/BeeStation/BeeStation-Hornet/pull/6113 merge

**Comment by PowerfulBacon** [comment]
Fuck, whatever conflict that was is going to bubble up into all the PRs that depend on this PR

**Comment by PowerfulBacon** [comment]
Might as well just use the child PR at this point, this will be in PR hell anyway.

**Pull request closed without merging**
