### PR TITLE
Brig Medical Reduction

### PR DESCRIPTION
**Pull request by DarnTheMarn**
## About The Pull Request

It's been over a day without a medbay change, so they are long overdue for one, and a reduction at that! In reality though this is a very simple PR that fixes what I believe to be an oversight from PR#7861, it reduces the amount of medkits spawns in the brig physicians locker and within security on maps that have more than one loose medkit spawn in security.

This means security has a single first aid kit sitting out in the brig physicians room, and a brute and burn specialized kit in the brig physicians locker. This is a net loss of a regular first aid kit, toxin kit, and O2 kit.

Per a recommendation on discord, the defibrillator and surgery bags have been moved to the brig physician locker. Duplicate equipment has also been removed. Quite a few maps had so many surgical kits in the brig. 

## Why It's Good For The Game

We can hopefully all agree the brig having more medkits in it round start than medbay is more than a little ridiculous. One medkit left sitting out in the open means that it's still possible to heal yourself in a pinch or on low pop while encouraging players to interact with the brig physician on high pop as one loose kit will run dry pretty quickly when five people are using it. It also gives the brig physician something to do which is sorely needed, they don't have enough content right now to really justify being their own job. Now they can have fun asking chemistry for things! Or power gaming their own chemistry lab like they always do! 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Capture

</details>

## Changelog
:cl:
balance: Slightly reduced med kit count in the brig, now each map has 1 first aid, 1 brute kit, and 1 burn kit.
del: Removed excess medkit spawns, removed first aid/toxin/O2 kits from brig physician locker, duplicate equipment from brig infirmary
tweak: Placed defib and surgical duffelbag in brig physician locker instead of on tables
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
With current stockpiles RNG, most of the time medbay doesn't get all of them so that's fair, maybe i can suggest adding the small medical wall vendor? iirc it sells just a couple of dexalins, epiepn and charcoal bottles nothing extreme compared to the big one,  which would be enough to cover some basic treatment on an emergency, but anything that would require higher treatment will need to get the brig phys to go to Medbay, or alternative you can just add a basic charcoal bottle and dexalin epipens(The locker next to surgery in Box has that and other stuff for some reason), again this would run out very quickly and it would be used for emergency treatments compared to having a full medkit of oxy and toxi

**Comment by Tsar-Salat** [comment]
> It's been over a day without a medbay change, so they are long overdue for one, and a reduction at that!

Cool. This isn't a medbay change. 

This doesn't change medbay.

**Comment by MarkusLarsson421** [comment]
I'd keep the toxin kit and get rid of the other two. Currently, the first aid kit can treat both burn and brute, so if someone has toxin damage from drinking too much, you'll have to get down to Medbay.

**Comment by DarnTheMarn** [comment]
>I'd keep the toxin kit and get rid of the other two. Currently, the first aid kit can treat both burn and brute, so if someone has toxin damage from drinking too much, you'll have to get down to Medbay.

True, but brute and burn are the most common damage types. Basic kit + epipens + toxin kit would cover all your bases though. I'll consider it when I go to fix the merge conflict.

**Comment by Fronsis** [comment]
> I'd keep the toxin kit and get rid of the other two. Currently, the first aid kit can treat both burn and brute, so if someone has toxin damage from drinking too much, you'll have to get down to Medbay.

The default kit can run out very quickly in my experiece, Dynameme can be quite unforgiving.
I'd say it's fine having both brute and burn specislized +the default as it's originally on the PR, If anything like i mentioned  as suggestion, having the wall medvendor or a bottle of charcoal/dexalin pen on the locker can cover emergency treatments but anything beyond that would need going to medbay

Also agree with Tsar, the title of the PR should be edited to reflect the actual changes, specially since you made clear on the forum this was done as part of the bandwagon of ''medbay nerfs",  even if meme or not.. Clarity good 👍

**Comment by DarnTheMarn** [comment]
>The default kit can run out very quickly in my experiece

I don't see this as a downside strictly speaking, brig physician is pretty starved for shit to do 90% of the time. But at the same time, I don't want them to have so little that people just run to medbay instead of the brig like they already do. What's even the point of a brig physician if thats the case. Really, what is the point of one now? No meta protection. Shit man.

**Comment by williamcll** [comment]
Does this mean I don't have to fully heal injured prisoners then? It's not like there's space law in regards to criminal treatment.

**Pull request closed without merging**
