### PR TITLE
Plumbing sprites update

### PR DESCRIPTION
**Pull request by Sinmero**
## About The Pull Request

Current plumbing sprites dont fit well in the game.
Updated plumbing sprites to fit better in medbay and chem.

plumbingGood2

plumbingGood

Here are the old ones for comparison:
t5456uy

## Why It's Good For The Game

Plumbing machines look cool and good now.

## Changelog
:cl:
imageadd: added new plumbing sprites
/:cl:

### CODE REVIEW

**Comment by eLeCtrOssSnake** [comment]
Uh, idk, in my opinion old ones are kinda based in a good way.

**Comment by Sinmero** [comment]
I think that original plumbing sprites are too dark especially input and output ones (you can barely see the arrows on the sprites).
Tanks are very low on details. Reaction chamber and pill press are ok. Synthesizer is kinda dark and low on details too. Filters look bad and low on details.
Its all subjective i guess.

**Review by zeskorion — DISMISSED** [review]
holy shit, removing these codersprites? yes please

**Comment by PowerfulBacon** [comment]
damn they are sexy

**Comment by qwertyquerty** [comment]
Why keep the old sprites in the file?

**Comment by Sinmero** [comment]
> Why keep the old sprites in the file?

I remember seeing some old hardsuit sprites in the files so i thought that i was supposed to keep the old plumbing ones.

**Review by zeskorion — APPROVED** [review]

**Pull request merged**
