### PR TITLE
New Carpets

### PR DESCRIPTION
**Pull request by Cenrus**
## About this pull request

Ports multiple new tables and carpets from TauCetiStation.

Mirrored PR: https://github.com/tgstation/tgstation/pull/46850

## Changelog

:cl:
imageadd: 8 New carpets and fancy tables
add: Exotic carpet crate
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
the check passed the first time, what changed?

**Comment by Crossedfall** [comment]
Hoped that would have forced the diffs bot to reset, but nope.

**Comment by Cenrus** [comment]
How can I force the check?

**Comment by Crossedfall** [comment]
~~Doesn't seem that I have permission to push anything to your branch. Not sure if something changed between qwert's push or not. Best course would be to create an empty commit and to push that. You can use the following commands to do that...~~ Edit: Take that back, worked after I tried again. I'll leave the steps though for reference. 

```git
git commit --allow-empty -m "Force checks"
git push
```

**Review by ike709 — APPROVED** [review]

**Comment by Cenrus** [comment]
needs a final review, then it's good to go

**Pull request merged**
