### PR TITLE
Reverts changes to chat, limits number of messages that can be displayed in one location

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Reverts what bacon did to the runechat.

Oldest message will delete itself instead of translating if you have more than 2 messages above this location.

When testing I found out that it is translating that causes *most* of the overhead.
It happens because the subsystem doesn't delete messages in time, when high dilation happens, this means messages stack and more of them have to be translated.

## Why It's Good For The Game

Simpler solution, better solution.
Also messages don't get weirdly translated anymore.

## Changelog
:cl:
add: Runechat messages amount has been limited to a maximum of 3 per loc.
fix: Fixed runechat messages sometimes translating themselves upwards when there was no message underneath.
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
THANK GOD.

This made the say ports CBT because the code was unreadable.

**Comment by PowerfulBacon** [comment]
> It happens because the subsystem doesn't delete messages in time, when high dilation happens, this means messages stack and more of them have to be translated.

But the overtime happens when the subsystem isn't deleting messages in time and when running as usual while on high-pops. My guess to what would be causing lag would probably be the power operation or something like animate. Even with a cap on how many messages are being shown, you are still going to be calling the method to show the message viewer* more. It caused lag on high-pop since if you have say 20 ghosts and 5 people nearby, you are creating 25 overhead chat instances and all of them need translating into place, putting into the runechat subsystem and handling. With the instanced messaging you only need 1 which significantly reduces the calls to showing the image and reduces the stress on the runechat subsystem. The weird message stacking can probably be easilly fixed, since you can't see regular messages and radio messages at the same time, they could just be put on top of each other.

**Comment by Archanial** [comment]
> easily fixed

you had *some* time to propose fixes.

This is much easier and more convenient solution. Yes this will increase the number of messages generated but since we handled this before we will be able to handle them now.

Again, the overhead came mostly from translating messages upwards and it had avalanche effect when server started slowing down and not deleting messages in time. This both limits number of messages above one person's head and quickly deletes any additional ones, thus putting less stress on the subsystem overall (and during this slow downs). 

I like this solution because it is MUCH easier to work with this system and create message and, as kapu already said, it makes it a bit easier to port things from tg that touch saycode.

**Comment by ike709** [comment]
I have a radical idea: What if we simply collect actual profiler data on the server with and without this PR?

**Comment by PowerfulBacon** [comment]
> I have a radical idea: What if we simply collect actual profiler data on the server with and without this PR?

Probably a good idea, the lag only happens at high pops though so would need to be done in peak time.

**Comment by ike709** [comment]
Your own profiling on Sage shows significantly worse overtime at highpop.

**Pull request closed without merging**
