### PR TITLE
Increases likeliness of extended and secret extended on MRP

### PR DESCRIPTION
**Pull request by super12pl**
## About The Pull Request

Zesko didn't change his PR #2088 so im doing it myself. Increases probability of extended and secret extended to 6.

## Why It's Good For The Game

Mrp is now more mrp.

## Changelog
:cl:
config: extended and secret extended is more common on sage.
/:cl:

### CODE REVIEW

**Review by Crossedfall — CHANGES_REQUESTED** [review]
Same feedback for Zesk. Keep the list ordered. If you increase the probability, also move it up in the list

**Comment by super12pl** [comment]
Moved extended and secret extended to 2nd and 3rd place on the list

**Comment by Tamuren** [comment]
Do not want

**Comment by ike709** [comment]
Zesko updated their PR, this is redundant.

**Pull request closed without merging**
