### PR TITLE
Adds another funny round end..ogg

### PR DESCRIPTION
**Pull request by ghost**
THE HULL HAS BEEN BREACHED AND THE SCIENCE IS LEAKING OOOOOOOOOUUUUUUUTTT.

## About The Pull Request

It fits perfectly.

## Why It's Good For The Game

SCIENCE.

https://www.youtube.com/watch?v=5cVsPPszvJM

## Changelog
:cl:
soundadd: added a new sound thingy
/:cl:

### CODE REVIEW

**Comment by Bastian0930** [comment]
100% gonna get a error, it's not your fault, you'll be fine.

**Comment by ghost** [comment]
i made it an ogg, what error?

**Comment by Bastian0930** [comment]
spiked skin will not work, it's a error from zeskos pr that slipped through

don't cry yourself to sleep even know you only added oggs

**Comment by Bastian0930** [comment]
spiked skin will not work, it's a error from zeskos pr that slipped through

don't cry yourself to sleep even know you only added oggs

**Comment by qwertyquerty** [comment]
Fellow you are going to have to change that file name

**Comment by ghost** [comment]
> Fellow you are going to have to change that file name

hmm yes how do I actually edit something in a pull request without remaking it completely is the question now

**Comment by ike709** [comment]
Make whatever changes you want locally, commit, push.

All on the same branch as the PR.

**Comment by ghost** [comment]
think i got it

**Review by ike709 — APPROVED** [review]

**Comment by MCterra10** [comment]
somebody forgot to add this to ticker.dm

**Comment by MCterra10** [comment]
smhsmh

**Comment by ike709** [comment]
@MCterra10 Having it be a hardcoded list is lame, I'm boutta just change it to use `flist()`.

**Pull request merged**
