### PR TITLE
Fixes energy chainsaws reverting to normal chainsaws when implanted

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
See title

## Why It's Good For The Game
It's a bugfix

## Changelog
:cl:
fix: Energy chainsaws no longer revert to normal chainsaws when implanted
/:cl:

### CODE REVIEW

**Review by ike709 — CHANGES_REQUESTED** [review]
See discord ping.

**Comment by VictorVow** [comment]
Alternative code was tested but found to not work correctly unfortunately.

**Comment by qwertyquerty** [comment]
@ike709 so uh wuss happening with this one

**Comment by ike709** [comment]
@qwertyquerty I needed to test something but I forgot about it.

**Comment by ike709** [comment]
I'm pretty sure there's cleaner ways to do this but I don't have the time to investigate.

**Pull request merged**
