### PR TITLE
TOTAL STASIS BED REMOVAL (almost) 

### PR DESCRIPTION
**Pull request by DarnTheMarn**
## About The Pull Request

This PR ABSOLUTELY DEMOLISHES ALL STASIS BEDS*

Namely, stasis beds are no longer available round start on any map, nor are they available through research. They are still present on the emergency shuttle since there's likely to be an abundance of dead bodies and there isn't a way to really put morgue trays in them. Mining pods have had their stasis beds replaced with morgue trays, which stop body decay like a stasis bed does. Doesn't do anything for the dying though so watch out! They have largely been replaced with normal beds, however stasis beds that were next to an operating computer have been replaced with an operating table. I am not without mercy!

## Why It's Good For The Game

Stasis beds are to medbay what shotguns are to security. A wonder item that does everything you could ever want and can solve any problem you see.  Dead bodies piling up? Strap em into stasis beds! Someone dying of toxin? Strap em into a stasis bed! Need to do surgery? Strap em into a stasis bed! Someone literally missing all of their organs? Strap em into a stasis bed and its a-okay! 

This do-it-all nature really stifles some mechanics in medbay. When was the last time someone injected a corpse with formaldehyde? Or gave a patient calomel? Or someone died on the operating table? By removing stasis beds we will bring these practices back. And it is quite important to note that everything stasis beds do can be done by other means!

Bleeding out? Bandages and IV.
Toxin damage/toxic reagents? Calomel, charcoal, blood filtering, maybe even all three at once!
Imminent death? Cryo tubes!
Surgery? Use the damn OPERATING ROOM!
Overwhelmed with patients? Triage!
Dead people? Morgue trays halt organ decay!

They also fuck over antagonists! ~~Xeno larvae? Who cares! Zombie tumors? I'll get around to it eventually!~~ Oh my assassination target? I dosed em up with morphine and locked 'em into a stasis bed. They're literally never getting out! 

And before someone complains that it's going to be too hard, I play plasmeme. I know exactly what this entails. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

no tech
box
corg
delta
echo
fland
kilo
meta
rad
Screenshot 2024-10-21 190255

</details>

## Changelog
:cl:
del: Removed stasis bed boards from techweb and tech storage
tweak: Replaced round start stasis beds with operating tables if they were near an operating computer, and regular beds if not
tweak: Mining pods now have a morgue tray instead of a stasis bed
balance: Stasis beds are no longer obtainable nor present on the station and mining pods
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
Add formaldehyde bottles to the med vendors and you have a deal.

**Comment by DarnTheMarn** [comment]
I asked about that and I was told I didn't need to, but I don't see why not so I'll do it

**Comment by DarnTheMarn** [comment]
> You can't make a PR like this minutes after being informed that organ decay exists bro...

Screenshot 2024-10-21 181326

A. I knew organ decay was a thing
B. I'm just following orders
and... I what I said is different from how it is so it's not exactly one to one ya know?

**Comment by TwingoI** [comment]
Stasis beds don't slow/stop xeno larvae and zombie ooze progression

**Comment by DarnTheMarn** [comment]
The fact checkers are in, that is correct it was changed a year ago

**Comment by Fronsis** [comment]
A morgue tray for mining pods is.. very strange, like to be honest i don't know why a miner needs a stasis bed on the first place, the only thing that helps them is to probably halt the legion disease? If it even works like that, in most ocassions they don't really need a stasis bed so adding a morgue tray just seems out of place, might as well just add some random comfort flavor item instead of a morgue tray, if another miner is alongside a dead one they might as well epi them and wait for the storm to clear before retrieving the body, the morgue trail/stasis has really never been used.

As for the things you pointed out here

> Bleeding out? Bandages and IV.
Toxin damage/toxic reagents? Calomel, charcoal, blood filtering, maybe even all three at once!
Imminent death? Cryo tubes!
Surgery? Use the damn OPERATING ROOM!
Overwhelmed with patients? Triage!
Dead people? Morgue trays halt organ decay!

Except for morgue trays, all of the above are always used, the only difference is that the patient is on a  stasis bed  yes, but if they want their iv blood trasnplant, calomel, charcoal, etcetera they will need to be unhooked from the stasis and will still have a chance to die due to reagent progression.


I'd like to see this play out on a test merge, because i've been hearing a lot of comments from general crew/player that medbay is a hit or miss, and we've also been getting a lot of **new players**, while we may have all those tools, reagents, technologies that experiences players with 1000hs know off, how is the **ordinary or new player** going to find out about it? It is been known that Medbay has been one of the most picked jobs that new players usually pick after Janitor/Assistant that has some ''hard mechanics'' so ultimately we would need to think how these things are presented so players are aware of it, since as far as i remember Bacon himself and other coders have voiced that having the wiki open on another tab is not a good game design, not to mention the already known fact that dynameme sometimes completely collapses medbay EVEN with two stasis bed, so i'm certainly interested on this change being TM'd on high and midpop.

I always thought that having at least one stasis bed helped to relieve some pressure and to teach new players(something i've done and i've witnessed other doctors do with new players), i don't support the idea of fully removing them, at the very least it would make sense to be moved to the last tier of medicine in the tech tree, otherwise you just take the feeling of ''progression and advanced'' that the station brings, where ultimately if everyone works together they can acquire better QoL machinery or items for the spessmen job and life, since it would be moved to the last tier it would also still rely on someone building it and getting components from sci, so the inter-deparment relationship remains exactly as it is now.


Also as you mentioned, this will be very detrimental to plasmapeople and it would certainly feel weird to do a surgery on the floor under a shower, so it would be nice to consider an alternative for the plasmapeople.

> Oh my assassination target? I dosed em up with morphine and locked 'em into a stasis bed. They're literally never getting out!

That is extremely horrid and bad sport, that breaks rule 1, i'd say that whole sentence should be deleted because you admitted to being misinformed.

Lastly i would like to suggest to move an organ-storage next to the main bay for convience, the only reason the organ fridge is rarely used it's because is pushed waaay back on surgery room and it would be neat if it would be in a more visible place where doctors could easily retrieve or keep organs for example: Someone had a chest-burst, well just pick up the organs and keep them safe in the fridge! instead of letting them slowly rot.

**Comment by Therealdoooc213** [comment]
This is stupid. Instead of doing something different, such as making the 'invulnerability' scale with the parts it has you're just completely removing it. 
Lets say at T1, it barely halts the progression of organ decay, death, chemical processing, etc. And the halting of... everything could've increased with how upgraded it is. You could've done what i just said. And I think a dramatically larger amount of people would agree with that being a Okay change. 

>Bleeding out? Bandages and IV.
Toxin damage/toxic reagents? Calomel, charcoal, blood filtering, maybe even all three at once!
Imminent death? Cryo tubes!
Surgery? Use the damn OPERATING ROOM!
Overwhelmed with patients? Triage!
Dead people? Morgue trays halt organ decay!

Removing stuff just because "Well you could do this!" is stupid. Maybe you could've also made it so surgery couldnt be done on    stasis beds? Just a few alternatives to (almost) completely removing stasis beds.

**Comment by MarkusLarsson421** [comment]
> That is extremely horrid and bad sport, that breaks rule 1, i'd say that whole sentence should be deleted because you admitted to being misinformed.

Sometimes you need a victim to be in the dark for a little bit, just don't leave them there for too long.

> it would certainly feel weird to do a surgery on the floor under a shower

Use a roller bed.

**Comment by DarnTheMarn** [comment]
> A morgue tray for mining pods is.. very strange, like to be honest i don't know why a miner needs a stasis bed on the first place, the only thing that helps them is to probably halt the legion disease? If it even works like that, in most ocassions they don't really need a stasis bed so adding a morgue tray just seems out of place, might as well just add some random comfort flavor item instead of a morgue tray, if another miner is alongside a dead one they might as well epi them and wait for the storm to clear before retrieving the body, the morgue trail/stasis has really never been used.

I figure it could be useful since you could find a fellow miner dead on lavaland and stick em in there for a paramedic to get if you don't have a Fulton. Is it probably ever going to be used? Probably not. But there's a space and it performs a similar function so it's the best replacement I could think of. 

> Except for morgue trays, all of the above are always used, the only difference is that the patient is on a stasis bed yes, but if they want their iv blood trasnplant, calomel, charcoal, etcetera they will need to be unhooked from the stasis and will still have a chance to die due to reagent progression.

I see that as a point against stasis beds. Letting you blood filter someone of all the toxic chems and dosing them up with charcoal and antitox before unhooking them absolutely does remove the chance to die. 

> I'd like to see this play out on a test merge, because i've been hearing a lot of comments from general crew/player that medbay is a hit or miss, and we've also been getting a lot of **new players**, while we may have all those tools, reagents, technologies that experiences players with 1000hs know off, how is the **ordinary or new player** going to find out about it? It is been known that Medbay has been one of the most picked jobs that new players usually pick after Janitor/Assistant that has some ''hard mechanics'' so ultimately we would need to think how these things are presented so players are aware of it, since as far as i remember Bacon himself and other coders have voiced that having the wiki open on another tab is not a good game design, not to mention the already known fact that dynameme sometimes completely collapses medbay EVEN with two stasis bed, so i'm certainly interested on this change being TM'd on high and midpop.

It should be test merged yes. Even dedicated medbay players can be overwhelmed during regular rounds so what's really the purpose of pointing it out. That's why they're moody fucks. 

> I always thought that having at least one stasis bed helped to relieve some pressure and to teach new players(something i've done and i've witnessed other doctors do with new players), i don't support the idea of fully removing them, at the very least it would make sense to be moved to the last tier of medicine in the tech tree, otherwise you just take the feeling of ''progression and advanced'' that the station brings, where ultimately if everyone works together they can acquire better QoL machinery or items for the spessmen job and life, since it would be moved to the last tier it would also still rely on someone building it and getting components from sci, so the inter-deparment relationship remains exactly as it is now.

I don't get this, medbay has some of the best tech progression with tools, boards, surgeries, implants galore. 

> Also as you mentioned, this will be very detrimental to plasmapeople and it would certainly feel weird to do a surgery on the floor under a shower, so it would be nice to consider an alternative for the plasmapeople.

Race with downside should have downsides. Cloning them is less gamey and with post mortem memory loss occurring for all deaths there no real reason not to. 

> That is extremely horrid and bad sport, that breaks rule 1, i'd say that whole sentence should be deleted because you admitted to being misinformed.

You are an old head you knew it happened, it doesn't happen frequently anymore but it still can if someone chose to. 

> Lastly i would like to suggest to move an organ-storage next to the main bay for convience, the only reason the organ fridge is rarely used it's because is pushed waaay back on surgery room and it would be neat if it would be in a more visible place where doctors could easily retrieve or keep organs for example: Someone had a chest-burst, well just pick up the organs and keep them safe in the fridge! instead of letting them slowly rot.

Good idea I can add one

**Comment by DarnTheMarn** [comment]
>Removing stuff just because "Well you could do this!" is stupid. Maybe you could've also made it so surgery couldnt be done on stasis beds? Just a few alternatives to (almost) completely removing stasis beds.

I did ask about that and I was told that doing it would be essentially removing it.

**Comment by DarnTheMarn** [comment]
For people complaining about stasis beds being used for teaching, I will remind you the morgue spawns a few dead bodies without organs. Those cadavers can be a very good tool for teaching if you are willing to use them. Practice tending wounds, amputation, augmentation, manipulation, experimental surgeries, patches, injections, sleeper injections, you name it you can try it. Aside from genetics I think you need to be alive for those.

**Comment by St0rmC4st3r** [comment]
I love this PR! Finally!

**Comment by ClownMoff** [comment]
Amazing gambit removing one of the few actual scifi parts of medbay in the scifi futuristic themed videogame. Also remove the crypods and sleepers so we have to go back to using syringes to inject chems into people.

**Comment by DarnTheMarn** [comment]
> Amazing gambit removing one of the few actual scifi parts of medbay in the scifi futuristic themed videogame. Also remove the crypods and sleepers so we have to go back to using syringes to inject chems into people.

Bro cryo pods are just bacta tanks. Can't get more Sci fi than that. Sleepers could be removed tbh they are mostly convenience and chemical efficiency. Jabbers that use 1u to inject 3u would basically be the same

**Comment by Fronsis** [comment]
> > Removing stuff just because "Well you could do this!" is stupid. Maybe you could've also made it so surgery couldnt be done on stasis beds? Just a few alternatives to (almost) completely removing stasis beds.
> 
> I did ask about that and I was told that doing it would be essentially removing it.

Not really, they would still be effective, even you(i think) mentioned that you could even restrict it to only tending wounds or mega basic ones and the surgery table would have all the others(even linked with the surgery computer)

The other points of Doc are stil valid and maintain that sense of progression without removing the sci-fi tool.

**Comment by DarnTheMarn** [comment]
The main problem is removing all sense of urgency, if it was slowed enough to be useful it would have the same problem as stasis beds do now. If it wasn't slowed down enough to be useful, why even bother you might as well remove them.

**Comment by Therealdoooc213** [comment]
Freedom from the tyranny

**Pull request closed without merging**
