### PR TITLE
Removes the Security item spawner and captain spawner from random-maintenance

### PR DESCRIPTION
**Pull request by spockye**
## About The Pull Request
in rdm_captain_quarters.dmm there are two things that stick out

a Captain spawner

and a security item spawner.
the security item spawner can contain:
image

thats a little silly, isnt it.

this PR removes the captain spawner, and replaces the item spawner with a collectable captain hat, and a captain figurine.

## Why It's Good For The Game
i dont think the captain should spawn in maintenance :p   
i dont think those items should spawn in maintenance

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
del: removes Captain spawner from rdm_captain_quarters.dmm
tweak: replaces item spawner in rdm_captain_quarters.dmm
/:cl:

### CODE REVIEW

**Comment by ColonelOrion** [comment]
finding sec items in maints as crew is a great way to have an ic reason to head to sec ("Hi! I found this contraband in maints") and may result in early round interrogations and stuff. I love it.
As antag it's great too.

**Comment by spockye** [comment]
i suppose theres less risk of someone just abusing it since we arent a LRP server but. personally i dont like it. 
if people in general are against removing them i'll close the PR

**Comment by Fronsis** [comment]
> i suppose theres less risk of someone just abusing it since we arent a LRP server but. personally i dont like it. if people in general are against removing them i'll close the PR

I did point out the sillyness of having Captain spawning on Maintenance, even if it's an ''interesting random WHAT THE!??'' moment it might get old fast, same with the contents of the Locker, originally i had captain gear and a pinpointer, though IIRC that was fixed and the locker didn't had much content.. But if it got replaced by what you showed yeah.. no bueno

I do 100% agree that loot table is busted even if not all of them spawn, the classic jackboots and armor-vest one can find in maintenace are good enough of a loot, the tiders and antags don't need bulletpoor armor, implants and a random bottle of chloral hydrate, good change.

**Comment by DarnTheMarn** [comment]
Schrödinger's bulletproof vest, weak enough it's useless against traitors, strong enough it should be removed from maints.

**Comment by MarkusLarsson421** [comment]
Wow, I just had this be merged yesterday. Anyway, this particular Security loot is inside a Captain-locked locker. You'd have to break it open to get it, which a non-antag probably wouldn't do considering the effort needed.

**Comment by PowerfulBacon** [comment]
Captain definitely shouldn't spawn in maints, I kind of like being able to find loot in maintenance since it has opportunity to inject contraband into regular crew activities and is an opportunity for antags to find some stuff that they can work around. If anything, I think we should hold back less on what you can find in maintenance

**Comment by spockye** [comment]
> Wow, I just had this be merged yesterday. Anyway, this particular Security loot is inside a Captain-locked locker. You'd have to break it open to get it, which a non-antag probably wouldn't do considering the effort needed.
> 
> Has the Captain spawned in there where it became an issue or did someone steal something from it since the time it was merged yesterday?

my issue was noticing that it spawns Uplink items, rather the suspicious bulb that instakills anything that uses it :p

**Comment by MarkusLarsson421** [comment]
Oh yeah, uhhh, could you probably just safely remove that or make a subtype of it with different things?

**Comment by spockye** [comment]
i've gotten 50/50 responses on keeping it. leaving it up to you @PowerfulBacon

**Comment by MarkusLarsson421** [comment]
Hell, would be neat if Captain clothes spawned in it, in case someone wants to do some gimmick with his clothes without breaking into his actual office. Maybe not all of 'em but a few.

**Comment by ColonelOrion** [comment]
Hell yeah! Blue beret and captain carapace for that blueshield swagger.
Turn up at the hopline saying "congratulations! You have a blueshield now."

**Comment by Fronsis** [comment]
Captain's clothing have one of the best armor, if anything they should be "replicas" just like how you can find the HoP hat replica.

Still sustain that if it doesn't get removed the locker needs the loot table adjusted.

**Comment by ColonelOrion** [comment]
Maybe the replica could be equivalent to a normal armor vest, seeing as how it's a similar find.

**Comment by MarkusLarsson421** [comment]
> the locker needs the loot table adjusted.

It has no loot table, or do you mean the security maintenance spawn?

**Comment by Fronsis** [comment]
> > the locker needs the loot table adjusted.
> 
> It has no loot table, or do you mean the security maintenance spawn?

The Sec item spawner that Spockeye mentions on the PR.

**Review by PestoVerde322 — APPROVED** [review]

**Pull request merged**
