### PR TITLE
BoH rework: attempt two

### PR DESCRIPTION
**Pull request by SomeAngryMiner**
##About The Pull Request

see the original PR: #601 

## Why It's Good For The Game

also see the original PR
## Changelog
:cl:
add: Bag of Holding bombs have been reworked: instead of spawning a tear in reality chasm, it spawns a stationary singulo wich sucks things in with absurd amounts of force, closing after a short while.
admin: BoH bombs can now be reverted by admins if it isnt older than 10 minutes.
/:cl:

### CODE REVIEW

**Comment by SomeAngryMiner** [comment]
and here we go again.

**Comment by Crossedfall** [comment]
The double whammy. I would recommend setting up the git hook for automating the map merge process. Instructions can be found here: https://tgstation13.org/wiki/Map_Merger#Use_as_a_Git_Commit_Hook_.28preferred.29

Make sure you're using python 3.6, newer versions **will not work.**

**Comment by ike709** [comment]
@Crossedfall The problem is that these changes shouldn't be affecting the map anyways. I think he messed up his master.

EDIT: Nevermind I'm dumb, he's removing an area.

**Comment by SomeAngryMiner** [comment]
i have no idea on how to undo the map diffs, so ill remake the PR again, not very code extensive.

**Pull request closed without merging**
