### PR TITLE
1% chance for Todd-Sie to spawn instead of Nar-Sie when summoned

### PR DESCRIPTION
**Pull request by TeomanTheGreat**
## About The Pull Request
It's basically what's said in the title.

## Why It's Good For The Game
The crew needs to be reminded to sink cash into our favorite person in the whole wide world.

## Changelog
:cl: Phil Smith
tweak: 1% chance for Todd-Sie to spawn instead of Nar-Sie when the blood cult completes the summoning ritual.
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
please stop

**Comment by Tsar-Salat** [comment]
> ## Why It's Good For The Game
> The crew needs to be reminded to sink cash into our favorite person in the whole wide world.

We are expecting to summon Todd and we don't even need any money?!

Make it so it requires every budget card.
Only the best for Todd.

**Comment by TeomanTheGreat** [comment]
> 
> 
> > ## Why It's Good For The Game
> > The crew needs to be reminded to sink cash into our favorite person in the whole wide world.
> 
> We are expecting to summon Todd and we don't even need any money?!
> 
> Make it so it requires every budget card. Only the best for Todd.

Todd isn't here to accept your money. He is here to steal the money from your mortal frame and turn you into harvesters. Also uhh I kinda want this to be a rare funny thing that can happen very rarely instead of whenever someone decides to dump budget cards on the circle.

**Comment by MNarath1** [comment]
if you do this make sure it globally plays https://www.youtube.com/watch?v=YPN0qhSyWy8 if tood-si gets summoned
chances are an admin will play it anyways so lets hardcode it in.

**Comment by TeomanTheGreat** [comment]
> 
> 
> if you do this make sure it globally plays https://www.youtube.com/watch?v=YPN0qhSyWy8 if tood-si gets summoned chances are an admin will play it anyways so lets hardcode it in.

i don't know the first thing about copyright law so I'm not sure if ill be butchered if I add it in.

**Comment by MNarath1** [comment]
well the chance for this to play if an admin is on is pretty much 70-90 % if tood-si actually shows up best idea would probably be to ask for permission from the copyright holder aka the youtube channel it was published on but yeah i guess it can be a hassle.

**Comment by TeomanTheGreat** [comment]
> well the chance for this to play if an admin is on is pretty much 70-90 % if tood-si actually shows up best idea would probably be to ask for permission from the copyright holder aka the youtube channel it was published on but yeah i guess it can be a hassle.

Probably better to just let an admin play it. Im not really in the mood to ask a YouTube channel if i can use their music in a 2d spessman game.

**Comment by OceanFish1** [comment]
Speedmergespeedmerge

**Comment by ghost** [comment]
Yes this is good PR.

**Comment by Crossedfall** [comment]
🔑 Honestly, these are starting to verge into spam.

**Comment by TeomanTheGreat** [comment]
> 🔑 Honestly, these are starting to verge into spam.

I didn't intend it to be spam. I just thought it would be cool if todd would appear every once and a while.

**Pull request closed without merging**
