### PR TITLE
Ninja dojo newfood

### LINKED ISSUE #11726: [Bug]: Ninja Dojo has no Newfood Oven or Griddle
### BYOND Version

_No response_

### Round Date

2024/10/17

### Round ID

50352

### Test merges

_No response_

### Describe the bug

I'm starving in the Ninja Dojo and just want to eat.
image

### What did you expect?

I expected proper cooking utensils.

### Reproducible steps

_No response_

### PR DESCRIPTION
**Pull request by Therealdoooc213**
## About The Pull Request

fixes #11726

Adds a oven and griddle to the ninja dojo (dead corpse not included)

## Why It's Good For The Game

People should be able to cook food at the ninja dojo, getting the blood drained out of you by a ninja usually hurts.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

image

</details>

## Changelog
:cl:
add: ninja dojo now has newfood oven & griddle
/:cl:

### CODE REVIEW

**Comment by Therealdoooc213** [comment]
"This pull request has conflicts, please resolve those before we can evaluate the pull request.", god said, for i am a fool.

**Comment by Therealdoooc213** [comment]
fak

**Comment by Fronsis** [comment]
Soul

**Review by Tsar-Salat — APPROVED** [review]
Griddle not adjacent to a table is a sin...

Looks fine though.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
