### PR TITLE
reverts autofire revamp

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
reverts the buggy-ass autofire revamp. automatic guns work fine without it, and have way too many bugs with it. We don't have the same gun needs NSV does

## Why It's Good For The Game
simple is usually better

## Changelog
:cl:
fix: automatic guns should no longer be buggy as fuck
code: de-factors autofire code
/:cl:

### CODE REVIEW

**Comment by ivanmixo** [comment]
We /tg/ now, boys. Just remove it instead of even trying to fix it.

**Comment by ghost** [comment]
> We /tg/ now, boys. Just remove it instead of even trying to fix it.

if its a feature that nobody needs and a pain in the ass to fix then fucking remove it instead of "HURR DURR FIX HURR!!!"

**Comment by Mick1299** [comment]
> We /tg/ now, boys. Just remove it instead of even trying to fix it.

#1868 
#1993 

#1944

Fixing was attempted, bugs keep popping up. The bugs also aren't minor, they're REALLY bad. Things like firing in crit, inability to interact with items without shooting said item, inability to throw automatic guns, etc

Sure, bookmark is for a later date. But for now, its broke

**Comment by ivanmixo** [comment]
I think we should try merging #1993 before completely giving up

**Comment by zeskorion** [comment]
> I think we should try merging #1993 before completely giving up

this doesn't fix all the issues though. it's like whack-a-mole

the reason nsv has this is because all of their guns fire much faster, at least, i believe they do (10 rounds per second or so?). ours have different guns as automatic, and dont fire as fast.

**Comment by ivanmixo** [comment]
Which issues does this not fix if you count in my suggested changes too?

**Comment by zeskorion** [comment]
note: autofire works without the revamp pr, both click-dragging and normal fire rate shit.

**Comment by francinum** [comment]
~~I'll be honest I don't think *we* need it either~~

**Comment by PowerfulBacon** [comment]
Closing in favour of https://github.com/BeeStation/BeeStation-Hornet/pull/2279

**Pull request closed without merging**
