### PR TITLE
Ports SSspeech_controller

### PR DESCRIPTION
**Pull request by ike709**
## About The Pull Request

Ports https://github.com/tgstation/tgstation/pull/63118 (with the changes from https://github.com/tgstation/tgstation/pull/64537)

Also https://github.com/tgstation/tgstation/pull/59813 as a bonus.

## Changelog
:cl: Kylerace & MSO, ported by ike709
refactor: Say/Me verbs are now handled by the Master Controller.
fix: Fixed subsystem postpones.
/:cl:

### CODE REVIEW

**Review by Archanial — COMMENTED** [review]
Looks good but we should testmerge it

**Comment by Archanial** [comment]
@ike709 fix 😠

**Comment by Archanial** [comment]
@ike709 fix 😠

**Comment by ike709** [comment]
eventually:tm:

**Comment by PowerfulBacon** [comment]
What was wrong with this?

**Comment by Archanial** [comment]
Split personality was broken iirc

**Pull request closed without merging**
