### PR TITLE
Removes natural virus spawns

### PR DESCRIPTION
**Pull request by XeonMations**
## About The Pull Request

Makes the level 7 biohazard admin only (I believe), removes rats from having diseases.

image

## Why It's Good For The Game

With the virology soft removal, viruses have been a pain in the ass to deal with now that new doctors don't know how to deal with them. Also modern dynamic viruses have a billion symptoms that basically make them death plagues each time, not to mention their cures always changing, which does not help the situation at all.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

I do not really know what to put here, saying it'd be like asking for a picture of a missing item.

</details>

## Changelog
:cl:XeonMations
del: Nanotrasen's joint health association has declared all nanotrasen employees disease free once more. Virus outbreaks should no longer happen on modern nanotrasen space stations.
balance: Mice no longer contain viruses.
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
Hmmm, i do believe medical should face the ocassional challenge of virus outbreaks, that however doesn't mean the doctors(and the station) need to suffer a level 7 virus that has +15 symptoms where if you don't react fast enough it's joever.

Iirc @zeskorion could give a hand because i remember talking about it with them when the first virus appeared and they mentioned it was ''intended'' but if it was necessary it could be dialed back to work as old level 7 virus.

I'd like for it to stay with a cap on symptoms so they  can keep Medbay with their guard on whenever they appear.

**Comment by EvilDragonfiend** [comment]
i figured it gets +6 symptom was a code error, and it's from virus event code. for every 5 minutes a game goes(every 3000), it gets extra +1 symptom without a cap.
so, if a round was played for 120 minutes(2 hours), it means 22 symptoms. funny.
it is easy to fix. (some) people just thought this is somewhat interesting.

**Comment by EvilDragonfiend** [comment]
image

I am more interested to see adjusting this value.

**Comment by Fronsis** [comment]
> i figured it gets +6 symptom was a code error, and it's from virus event code. for every 5 minutes a game goes(every 3000), it gets extra +1 symptom without a cap. so, if a round was played for 120 minutes(2 hours), it means 22 symptoms. funny. it is easy to fix. (some) people just thought this is somewhat interesting.

I do believe from what i recall speaking with Zams, it was supposed to be like that to make it ''interesting'' unfortunately from what me and many have experienced once we reach the treshold of 22 symtomps you can get some VERY nasty combos that wipe a station really quick, specially because they end up requiring advanced cures like Concentrated Barber's aid and such, it's a lowpop killer as well, it would be nice to tweak it so the threat of the event is still there but nowhere near THAT powerful.

**Comment by EvilDragonfiend** [comment]
> > i figured it gets +6 symptom was a code error, and it's from virus event code. for every 5 minutes a game goes(every 3000), it gets extra +1 symptom without a cap. so, if a round was played for 120 minutes(2 hours), it means 22 symptoms. funny. it is easy to fix. (some) people just thought this is somewhat interesting.
> 
> I do believe from what i recall speaking with Zams, it was supposed to be like that to make it ''interesting'' unfortunately from what me and many have experienced once we reach the treshold of 22 symtomps you can get some VERY nasty combos that wipe a station really quick, specially because they end up requiring advanced cures like Concentrated Barber's aid and such, it's a lowpop killer as well, it would be nice to tweak it so the threat of the event is still there but nowhere near THAT powerful.

* Zamms comment: https://github.com/BeeStation/BeeStation-Hornet/issues/10850#issuecomment-2040801693

image

I believed myself that I heard that so, but It appears that they didn't intend that much.

I think we can change it a bit more affordable. I see there is medical challenge like this, but it is hard to defeat when it has +10 symptoms.

**Comment by JixS4v** [comment]
👎 Viruses make for good conflict, doctors not knowing how to deal with them is understandable, but I still think we should have the occasional virus outbreak.

**Comment by zeskorion** [comment]
i started a PR to fix the issue awhile back, buthave been too busy. its a bit more in depth than I thought,  but i can look into it later today with fresh eyes

**Comment by zeskorion** [comment]
> Most of the conflict that has happened whenever a virus outbreak happens is that people will be forced inside medical to prevent the spread of the virus and sit there for until the virus is cured, sometimes dying and just generally not being able to interact with the round at all. (In the worst of cases and most often cases with dynameme's viruses, ~30-40min)
> 
> Even viruses that aren't made from the L7 Biohazard are still rather... Too strong. I had a round a day or so ago where the virus spread was caused by a lizard using a dirty needle. I spent ~45min in medical stuck to a stasis bed because the medical doctors couldn't figure out how to cure it with the cure changing every 5s or so. (Not to mention apparently there were three viruses going around, in total.)
> 
> I believe that fixing the max_severity issue won't really fix the overall problem, but rather make it less common.


I'll look into the cure changing issue. im not sure why this happens, but the most likely reason is continued re-infect procs

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
Rat diseases are fine, medbay can and should be able to handle these diseases fine, and a bump in the road is a good interaction for them

Level 7 biohazard should not be entirely removed for the same reason, though I do admit it should definitely have some tweaks and not spawn monstrous diseases. 

Meant to mention that I'm applying a key for now only because this is a straight removal instead of addressing the actual problem

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
For this to get in, simply the disease outbreak event needs changing in order to reduce the level of shittery that it is capable of.

**Pull request closed without merging**
