### PR TITLE
Changes Bee Infestation Thresholds

### PR DESCRIPTION
**Pull request by Dingo-Dongler**
## About The Pull Request

This changes what happens when both thresholds are met in the bee infestation symptom. Before, it was supposed to synthesize honey if the resistance threshold was met, overriding the effects of the transmission threshold. Now, the transmission threshold overrides the reagents of the resistance one, but the bees remain friendly and do not sting the infected. Also this makes the resistance threshold make honey bees properly.

"Fixes" https://github.com/BeeStation/BeeStation-Hornet/issues/1753

## Why It's Good For The Game
Meeting both the transmission and resistance thresholds is a big undertaking. Instead of having one override the good effects of the other, they now both work together to make the infected a toxic bee slinging god. Also there's a bug fix in here (heh, bug). 

## Changelog
:cl:
tweak: the resistance threshold of bee infestation will no longer override the reagents of the transmission threshold.
fix: meeting the resistance threshold of bee infestation will now properly spawn honey bees, if the transmission threshold is not met
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
Doesn't quite do what it says on the cover. All you do here is make res14 bees have honey in them

**Comment by Dingo-Dongler** [comment]
Oh god I forgot some stuff hold on.

**Comment by Dingo-Dongler** [comment]
Wait no I didn't. I mean, maybe I should word it differently. This basically just makes the description of the disease say what it already did, because what it did was better than the intended effect. I could change it so it doesn't synthesize honey in the infected.

**Comment by zeskorion** [comment]
> Wait no I didn't. I mean, maybe I should word it differently. This basically just makes the description of the disease say what it already did, because what it did was better than the intended effect. I could change it so it doesn't synthesize honey in the infected.

The disease actually used to work like you made it work right now,  but i changed it

**Comment by Dingo-Dongler** [comment]
I'm confused. So honey should override toxins like the original description said?

**Comment by zeskorion** [comment]
what i mean is, the bees should not contain honey at the moment. however, i'll put it to vote and see if people want it

**Review by zeskorion — APPROVED** [review]
eh, vote was a majority

**Pull request merged**
