### PR TITLE
Disables the Gateway

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This disabled the Gateway in the config.

## Why It's Good For The Game

Unmaintained content that has been left festering for years and the terrible quality (and very questionable balance of some), of the maps honestly goes to show that, until someone actually wants to update these maps they should be disabled because they will only get worse the longer time goes on.

## Changelog
:cl:
config: Disabled the Gateway roundstart
/:cl:

### CODE REVIEW

**Comment by Hibabo** [comment]
delete this pull request

**Comment by ghost** [comment]
> delete this pull request

update the gateway maps then

**Comment by Hibabo** [comment]
> > delete this pull request
> 
> update the gateway maps then

The gateway is a dice roll, sometimes you get shitty locations, other times they're good, and sometimes you dont get any at all. If your problem is with the balance of the gateway locations then I assume your next pull request will be deleting lavaland megafauna and tendrils since they also give out good gear.

as someone who frequently does gateway its an enjoyable experience and I feel as if majority like it more than dislike it.

thats my stance on this anyway.

**Comment by ghost** [comment]
> > > delete this pull request
> > 
> > 
> > update the gateway maps then
> 
> The gateway is a dice roll, sometimes you get shitty locations, other times they're good, and sometimes you dont get any at all. If your problem is with the balance of the gateway locations then I assume your next pull request will be deleting lavaland megafauna and tendrils since they also give out good gear.
> 
> as someone who frequently does gateway its an enjoyable experience and I feel as if majority like it more than dislike it.
> 
> thats my stance on this anyway.

no my issue with the gateway is that the maps havent been updated in about 6 years and horribly outdated and otherwise just terrible.

i do not have the nerve, will, experience or time, neither do i want to update the gateway maps, if something is just a complete hassle to improve then by all means it should be removed.

**Comment by Hibabo** [comment]
which gateways maps do you not like?

**Comment by ghost** [comment]
> which gateways maps do you not like?

the only map that is semi-decent is snowdin, wild west is just straight up garbage, and the other maps are severley outdated.

**Comment by Hibabo** [comment]
i'm not even sure what you mean by severely outdated, do you not like them because they're old?? i see nothing wrong with them other than firelocks being old, point out some of the flaws on some of them so i can get an idea of why you hate em so much

**Comment by ike709** [comment]
The only "good" gateway missions are the ones that give epic gamer loot. There hasn't been an interesting and effort-filled gateway mission since MO19 was added like five years ago.

**Comment by Hibabo** [comment]
> The only "good" gateway missions are the ones that give epic gamer loot. There hasn't been an interesting and effort-filled gateway mission since MO19 was added like five years ago.


in my opinion the only gateway that should be removed is the shitty plasma station one due to the fact that people will immediately grab the omnilathe and leave the mission without any sort of danger involved. i think its much better than deleting the whole gateway.

just because they're old doesn't mean they automatically become bad, i've yet to see any flaws pointed out in the individual gateways other than the one i just pointed out.

**Comment by ghost** [comment]
> i'm not even sure what you mean by severely outdated, do you not like them because they're old?? i see nothing wrong with them other than firelocks being old, point out some of the flaws on some of them so i can get an idea of why you hate em so much

SnowCabin: Never seen this map before until i looked at the files, decent i suppose.

Beach: Unfinished from what i can tell, was supposed to have an entire underwater section (As it has on paradise station) but instead it's just a tiny beach with a few buildings and no real loot, except the random captain sabre in the north east corner of the map.

Syndicate Cruiser: Get past 4 turrets and 2 simple mobs and you're rewarded with a L6, Mateba, Mech Gun, and if you kill another 2 4 microbomb implants, looking at it, the countless emitters there were actually supposed to constantly fire, so if those would actually do their job it would be enough risk to warrant the loot.

MoonOutpost19: The entire station plus the syndicate outpost has really nothing noteworthy, the only valuable thing is the xenomorph hive (which has been copy pasted into a lavaland ruin already)

Research: Loot is meh-tier, the vault contains a bunch of genetic mutations that by the time you get there genetics already has, only worthwhile thing here is the reflector vest for traitors, otherwise the loot is not worth having to fight off dozens of syndicate and NT security simplemobs.

Snowdin: Despite us having elevators as a thing, the "Elevators" here are shuttles, and it also doesn't make use of multi-z when it could really benefit from that, in other words, its outdated.

Spacebattle: This is the map that gets people banned because the BSA is used for nothing else but to grief, otherwise it's alright.

Undergroundoutpost45: Pretty okay map but i heavily suspect it's unfinished due to the fact there is a elevator with buttons but it's actually unusable.

Wildwest: Horrible design, and overall everything about this is terrible, plasmafire mines everywhere and for some reason the person that made this put the parent type for guns instead of an actual stetchkin pistol as guns, as result you have a bunch of guns that were never meant to be seen ingame with bugged sprites, also the way out is behind a maze with 3 million faithless and at the end of it is a wishgranter.

**Comment by ivanmixo** [comment]
Aren't you banned for multikeying? 

Nevermind that, why not just update them or make a thread on the forums making suggestions? 

I really dislike just removing shit without even trying to make it better.

**Comment by ghost** [comment]
> Nevermind that, why not just update them or make a thread on the forums making suggestions?

> i do not have the nerve, will, experience or time, neither do i want to update the gateway maps, if something is just a complete hassle to improve then by all means it should be removed.

**Comment by Hibabo** [comment]
Beach - Never seen beach in my many hours of gateway dwelling, you sure it isn't disabled?

Syndie Cruiser - this is actually one of the worse gateways when it comes to loot, the L6 has a syndie firing pin installed which means you gotta either get cargo to buy you firing pins or get sec to give you some, mech gun is rarely ever used, the unica is the only good item from the place together with the microbombs, both of these items getting outshined by many other gateways.

Moonoutpost - This is one of the ways to get a facehugger and let ghost players back into the game by starting your own xeno farm, unlike the lavaland area which does not have facehuggers.

Research - This is one of the better places for loot actually, the room with genetic information? yeah that place also has a bunch of OP mutation syringes, we're talking laser eyes, hulk, x-ray, tele, dwarfism, chameleon and those are the ones i remember of the top of my head, its also got a hidden stash of randomly generated spellbooks in the bottom left side of the map inside of a plasma walled room thats hidden away in some rocks.

Snowdin - I can't deny that the elevators are outdated, but does it really matter? they serve their purpose and are a minor thing.

Spacebattle - People that use the BSA aren't the brightest bunch, lootwise its also one of the better places as its got dark gygaxes which are easy to ion gun and steal using the gygax and the ion mech gun that are located in the big area with crates, its also got a hidden gem encrusted hardsuit in the bottom right corner. not to mention the captain locker that has budget, spare ID, and all the normal captain locker items.

undergroundoutpost - shitty plasma station that you're more than welcome to remove, pretty sure everyone hates this shit hole.

wildwest - You can escape the starting area with mines completely by taking one of the miner bags in the area with the 3 dead miners grabbing  a PKA and shooting a hole to space, you can then go to the area with the DE sword and easily clear the maze of faithless, the wishgranter is also one of the only ways for players to get wishgranter other than lavaland which is pretty much only used by miners.

**Comment by ghost** [comment]
> Beach - Never seen beach in my many hours of gateway dwelling, you sure it isn't disabled?
> 
> Syndie Cruiser - this is actually one of the worse gateways when it comes to loot, the L6 has a syndie firing pin installed which means you gotta either get cargo to buy you firing pins or get sec to give you some, mech gun is rarely ever used, the unica is the only good item from the place together with the microbombs, both of these items getting outshined by many other gateways.
> 
> Moonoutpost - This is one of the ways to get a facehugger and let ghost players back into the game by starting your own xeno farm, unlike the lavaland area which does not have facehuggers.
> 
> Research - This is one of the better places for loot actually, the room with genetic information? yeah that place also has a bunch of OP mutation syringes, we're talking laser eyes, hulk, x-ray, tele, dwarfism, chameleon and those are the ones i remember of the top of my head, its also got a hidden stash of randomly generated spellbooks in the bottom left side of the map inside of a plasma walled room thats hidden away in some rocks.
> 
> Snowdin - I can't deny that the elevators are outdated, but does it really matter? they serve their purpose and are a minor thing.
> 
> Spacebattle - People that use the BSA aren't the brightest bunch, lootwise its also one of the better places as its got dark gygaxes which are easy to ion gun and steal using the gygax and the ion mech gun that are located in the big area with crates, its also got a hidden gem encrusted hardsuit in the bottom right corner. not to mention the captain locker that has budget, spare ID, and all the normal captain locker items.
> 
> undergroundoutpost - shitty plasma station that you're more than welcome to remove, pretty sure everyone hates this shit hole.
> 
> wildwest - You can escape the starting area with mines completely by taking one of the miner bags in the area with the 3 dead miners grabbing a PKA and shooting a hole to space, you can then go to the area with the DE sword and easily clear the maze of faithless, the wishgranter is also one of the only ways for players to get wishgranter other than lavaland which is pretty much only used by miners.

the lavaland xeno hive does have facehuggers, and i know this for a fact since ive brought one to xenobio before, also the only disabled map is the wiz academy.

**Comment by Hibabo** [comment]
Im looking at the lavaland xeno hive in a game right now and i cant find a single egg that hasn't been opened, mind you it has yet to be breached so its not because someone went inside and took the supposed hugger, unless its random there is no facehugger on lavaland.

perhaps a admeme spawned one in during the round you got it?

my point still stands with the beach, i've never seen it and i'm one of the more frequent gateway explorers, so im pretty sure its disabled in some way or another. your list also didnt mention BMP asteroids/narsian ruins/whatever the name is.

**Comment by Fronsis** [comment]
> Im looking at the lavaland xeno hive in a game right now and i cant find a single egg that hasn't been opened, mind you it has yet to be breached so its not because someone went inside and took the supposed hugger, unless its random there is no facehugger on lavaland.
> 
> perhaps a admeme spawned one in during the round you got it?
> 
> my point still stands with the beach, i've never seen it and i'm one of the more frequent gateway explorers, so im pretty sure its disabled in some way or another. your list also didnt mention BMP asteroids/narsian ruins/whatever the name is.

The gateway xeno hive if it's the one that has a queen i've went there an sucesfully retrieved a monke with a face hugger on it and made the xenos spawn on the xenobiology container, as far as i remember i only saw three eggs with facehuggers all to the left, possibly passing the queen, i can't tell if they were more or not since i went kinda late into the gateway and almost all except the queen and a beno were already dealt with

Edit: Replaced lavaland xeno hiev for gateway, i thought you meant that one, but yeah i think lavaland xenos has no facehuggers, besides with their atmos it's kinda impossible to get an ssd body/monke to get there, get a facehugger on him and come back and reach xenobio, with the gateway i did it on box

**Comment by Sapfearon** [comment]
Please no. Gateway is fun and instead of removing it you should just rework and re-balance it. 
Also remove plasma garbage station.

What we really need is gateway explorer role ( curator+ maybe?) and couple new maps, while updating old ones.

**Comment by r1ks-iwnl** [comment]
> Please no. Gateway is fun and instead of removing it you should just rework and re-balance it.

Yeah that's why it's a good idea to disable the gateway entirely, nobody is currently reworking the missions and they are just sitting there getting more and more outdated and unbalanced.

**Comment by Effemu** [comment]
local man becomes bee version of oranges and removes gateways because he no like

**Comment by ghost** [comment]
> local man becomes bee version of oranges and removes gateways because he no like

hello reddit!

**Comment by Effemu** [comment]
> hello reddit!

whats a reddit

**Comment by francinum** [comment]
Every map's quality is going to be directly tied to how bad of a loot balloon it is, unless they're created and stored serverside for secrecy. Which while not a terrible idea, is infeasible at the current time.

**Comment by Hibabo** [comment]
> Every map's quality is going to be directly tied to how bad of a loot balloon it is, unless they're created and stored serverside for secrecy. Which while not a terrible idea, is infeasible at the current time.


Just to clear things up, most of the current gateway maps that have loot are in the same vein as lavaland, at first you're gonna get shit on because you dont know what to do until you learn them and they become easy loot balloons, this doesn't mean they should be removed though as any content can be learned and be made easy. 

Lavaland has some degree of procedural generation but not enough to stop people from learning it and making it easy.

I personally think removing the gateway has more detriments than benefits in terms of player enjoyment.

**Comment by PowerfulBacon** [comment]
As much as I don't like this PR, the gateway missions are just straight up unmaintained, haven't been updated for years and most of them are just broken. People only really consider the missions for their loot value and just game the missions by ghosting to find ways to the loot with no danger in other rounds. As cool as the gateway is, it just is outdated and would need to include some form of randomness or be stored serverside because nobody cares for the story when there is loot to be had by skipping the entire thing.
Some of them, like the syndicate killbox cruiser aren't even good to begin with, the syndicate cruiser hasn't even got atmos set up properly and is literally just a hall of turrets and then some nuke op loot.

**Comment by Hibabo** [comment]
> As much as I don't like this PR, the gateway missions are just straight up unmaintained, haven't been updated for years and most of them are just broken. People only really consider the missions for their loot value and just game the missions by ghosting to find ways to the loot with no danger in other rounds. As cool as the gateway is, it just is outdated and would need to include some form of randomness or be stored serverside because nobody cares for the story when there is loot to be had by skipping the entire thing.
> Some of them, like the syndicate killbox cruiser aren't even good to begin with, the syndicate cruiser hasn't even got atmos set up properly and is literally just a hall of turrets and then some nuke op loot.


Is the only solution really to remove it all together? cant the worst offenders just be disabled with some of the good ones being left in?

**Comment by qwertyquerty** [comment]
Disable or remove the worst offenders, update the ones that need updates

**Comment by ike709** [comment]
The gateway was a good concept that went completely ignored and unmaintained for a decade and nobody is willing to change that.

**Comment by qwertyquerty** [comment]
Then just remove it entirely

**Comment by ike709** [comment]
That's fine with me, though I do think it should stay in for events/adminabuse.

**Comment by qwertyquerty** [comment]
The maps can be left for admins to load in

**Comment by ghost** [comment]
@ike709 @qwertyquerty 

so? decision?

**Review by Crossedfall — APPROVED** [review]
Disabling them roundstart but leaving them open for admins to load in seems like a good compromise.

**Pull request merged**
