### PR TITLE
Removes necrotic metabolism's ability to have diseases act inside dead bodies.

### LINKED ISSUE #9606: Wizarditis causes NPC mobs to talk in dchat
### BYOND Version

_No response_

### Round Date

04/08/2023

### Round ID

45206

### Test merges

_No response_

### Describe the bug

It makes dead monkeys talk in dchat even when NPCs.

### What did you expect?

It shouldn't talk in dchat.

### Reproducible steps

_No response_

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Fixes #9606

- Removes Necrotic Metabolism being able to have the virus stage_act inside dead hosts, as almost all symptoms are fundamentally incompatible with this concept.
- Viruses will no longer spready from dead bodies via airbourne transmission. (Instead it will spread via contact with infected bodies.)
- Necrotic Metabolism will allow for viruses to spread airbourne with the origin being dead bodies.

## Why It's Good For The Game

This symptom causes a lot of issues, I was going to remove it from specific symptoms but then I found myself removing it from the majority of symptoms as processing disease symtpoms while dead is incompatible with the majority of symptoms. Instead, this makes it so viruses won't spread airbourne from dead bodies and instead gives this symptom the ability to allow for dead mobs to spread the disease.

Also this is a virus nerf which is immediately good for the game due.

## Testing Photographs and Procedure

image

image
No dchat talking

## Changelog
:cl:
balance: Necrotic Metabolism will no longer allow symtpoms to process in dead hosts, instead it will allow dead bodies to spread the disease via airbourne transmission which no longer happens by default.
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
was airborne transmission re-added at some point?

**Comment by PowerfulBacon** [comment]
I have no idea

**Comment by Absolucy** [comment]
> Removes Necrotic Metabolism being able to have the virus stage_act inside dead hosts, as almost all symptoms are fundamentally incompatible with this concept.

So Pituitary Disruption being able to regrow your head (which isn't unintended, _it specifically pulls your mind back into your body_) is now useless?

**Comment by zeskorion** [comment]
gosh, if i realized you were doing that i'd have called out a lot more issue here. If you want to remove virus spread from corpses (which isn't the best idea IMO, corpses should be hazardous), just target spread symptoms. 

(Sneeze, Cough, Vomit, Xenosymb, macrophage, bubonic infection, derm-ovu)

**Comment by PowerfulBacon** [comment]
Originally I had a flag that made it so specific symptoms could stop processing inside dead bodies if they do stuff only alive people should be doing, but then I was activating that flag on almost all of the symptoms so just made it a global thing. The majority of them trigger some kind of action or do something that shouldnt be something dead people have happening to them

**Comment by zeskorion** [comment]
> Originally I had a flag that made it so specific symptoms could stop processing inside dead bodies if they do stuff only alive people should be doing, but then I was activating that flag on almost all of the symptoms so just made it a global thing. The majority of them trigger some kind of action or do something that shouldnt be something dead people have happening to them. This will nerf some symptoms and remove some interactions between symptoms.

this... doesn't do anything good at all, and some symptoms actively require it to function as intended. it's the realism argument again

there are things about viro that deserve nerfing, but this is not one of them. Necrotic Metabolism is one of the symptoms that's there to allow for interesting interactions and creativity, and is one of the symptoms that makes the job a bit more interesting than just "get a cool set of powers"

it adds a lot of depth, and isn't extremely powerful.

if you really wanna nerf viro, look at the 5 severity symptoms instead

**Comment by PowerfulBacon** [comment]
As much as I dont mind nerfing viro, this PR isn't about nerfing and is just dealing with a symptom that causes broken interactions with other symptoms

**Comment by zeskorion** [comment]
> As much as I dont mind nerfing viro, this PR isn't about nerfing and is just dealing with a symptom that causes broken interactions with other symptoms (Almost all symptoms called some proc that should only be called when alive and has absolutely no checks for the mob's state).
> 
> Virology is a department that almost entirely functions on complexity and obscurity in order to make the powerful diseases 'balanced' which leads to it being completely useless to all but the players who learn the specific interactions or create viro spreadsheets. Its one of the few departments along with xenobiology where I am perfectly happy to make changes that are destructive for the top virologist players if they are better for everyone else on the station (There are no fun viruses to play against).

I dont think necrotic metabolism makes virology any more unfun for non-viro players. can you tell me what procs were called, exactly?  I can fix this stuff myself in a less destructive way if you're unwilling.

**Comment by PowerfulBacon** [comment]
|Symptom|Severity|Issue|
|-|-|-|
|Autobrewery Syndrome|Minor|to_chat calls related to feelings on dead/unconcious mobs|
|Autobrewery Syndrome|Minor|This symptom should not work with dead mobs|
|Facial Hypertrichosis|Minor|to_chat calls related to feelings on dead/unconcious mobs|
|Beesease|Minor|to_chat calls related to feelings on dead/unconcious mobs|
|Beesease|Major|Can spawn bees on dead mobs, resulting in infinite bees able to be produced.|
|Beesease|Major|Injects mobs with reagents despite reagent processing being disabled while dead.|
|Blob Spores|Minor|to_chat calls related to feelings on dead/unconcious mobs|
|Blob Spores|Major|Causes dead mobs to vomit|
|Blob Spores|Major|Causes dead mobs to cough blood|
|Brain Damage|Minor|to_chat calls related to feelings on dead/unconcious mobs|
|Brain Damage|Minor/Outside scope|Brain traumas need checking to see if these handle being applied to dead mobs properly|
|Asphyxiation|Minor|to_chat calls related to feelings on dead/unconcious mobs|
|Biometallic Replication|Minor|to_chat calls related to feelings on dead/unconcious mobs (Ignored from this point onwards)|
|Cockroaches|Major|Infinite cockroaches produced on dead mobs, despite intentionally spawning cockroaches on death|
|Cough|Major|Silently spreads the disease when the mob is dead/unconcious|
|Alkali|Major|Dead mobs are capable of producing infinite epxlosions|
|Flesh Death|Major|Adds reagents to dead bodies despite dead bodies not processing reagents|
|EMP|Major|Adds reagents to dead bodies despite dead bodies not processing reagents|
|EMP|Major|Allows for infinite EMPs while dead|
(I'm not going further than healing.dm down the list)

Looking through the symptoms I don't really want to go any further, the majority of the symptoms should not be able to process while dead. Dead mobs should not be able to work with symptoms that produce anything from the mob otherwise you get infinite mob/explosion/EMP/chat spam.

Looking further through this further cements my belief that we should just remove this symptom rather than fixing the actual issues with it, since even the non-issues that could be argued as being intentional (EMPs, Explosions, Bees spawning) aren't behaviours that we want. Any disease that works properly with death doesn't need necrotic metabolism, blob spores will do its thing properly on death itself.

I'd rather not have diseases like radiation and stuff like that continuing to function after the mobs dies.

**Comment by Absolucy** [comment]
Couldn't we just have a flag that's set for diseases that should proc while dead?

**Comment by PowerfulBacon** [comment]
No symptoms bother to care about checking for mob stat inside of Activate despite calling procs that assume the player is alive, so a mob that lets Activate be called on dead mobs is a bad idea.

**Comment by PowerfulBacon** [comment]
> Couldn't we just have a flag that's set for diseases that should proc while dead?

This exists for diseases, I added it for symptoms early on in this rework and then just turned it off for every single symptom so removed it

**Comment by zeskorion** [comment]
> No symptoms bother to care about checking for mob stat inside of Activate despite calling procs that assume the player is alive, so a mob that lets Activate be called on dead mobs is a bad idea.

i'll take care of these on a case by case basis. some of this,  though (things like EMP on dead mobs) are intended and not really a balance issue.

**Comment by PowerfulBacon** [comment]
Even if intended, I don't see a good reason to ever allow any of these symptoms to run while on dead bodies. I don't see the benefit of not removing this symptom

**Comment by zeskorion** [comment]
> Even if intended, I don't see a good reason to ever allow any of these symptoms to run while on dead bodies. I don't see the benefit of not removing this symptom

the benefit is that this allows for interesting, out of the box ideas for both normal and traitor viros. the issue with to_chats and explosions and reagents and mob spawns, i understand.  but things such as turning monkeys into intermittent EMP mines is an interesting interaction that causes no real harm to the game. Can you offer a reason that it's a *bad* thing?

**Comment by PowerfulBacon** [comment]
At least if someone spams infected monkeys across the station, the crew can just kill them and be done with it (although I guess you could butcher them assuming they dont turn them into humans)

**Comment by zeskorion** [comment]
> Viruses are plainly annoying and never fun for anyone to deal with, especially combined with the interaction of turning a load of dead monkey bodies into constantly detonating EMPs/Explosions/Fireballs/Spike traps/whatever that are so numerous they are essentially impossible to get rid of unless someone goes round and feeds every single one the vaccine (which only the viro can make usually). You should not be able to make infinite mob factories with virology by just having a bunch of dead monkies inside virology pumping out blob spores. All of these interactions are horrible and only make the experience of having the virus in the round more annoying for everyone else involved. This is not a good interaction for the game, whether a normal or traitor virologist gets their hands on this symptom and these effects (More so the traitor, since there is basically nothing useful you can do as a non-antagonist once a mob is fully dead, but virology is basically for antagonists only since distributing good viruses is against the rules anyway)

actually,  the best uses of necrotic metabolism are for non-traitors. It's a really useful symptom for medical viruses (that no one really seem to make). my primary use for this symptom as a viro player is to help revive corpses which would otherwise be asspain to care for

however,  monkey trap things are far better than, say, a contagious death plague. 

also, blob spore monkeys wont become mob factories. all the spores are spawned on-death.

some symptoms,  like hemetophagy, also *require* necrotic metabolism for some intended functions. As i said, i'll take care of this on a case-by-case basis. blob spore monkeys aren't due to this symptom (and i would definitely support nerfing those). 
Other annoying interactions with this symptom rarely happen, if ever, because there's just... better options to be annoying.

**Review by Rukofamicom — APPROVED** [review]

**Comment by zeskorion** [comment]
i still think this is unecessary, especially with customizable viruses destined for the bin

that said, I'm also making it a config option in the currently WIP viro removal pr

**Pull request merged**
