### PR TITLE
The corporate jacket is now a jacket.

### LINKED ISSUE #6018: The corporate security jacket is not actually a jacket.
I added this thing quite some time ago, but because I was lazy I made it an armor vest subtype instead, paradise has the sprite for an opened jacket, if anyone cares.

### PR DESCRIPTION
**Pull request by AnCopper**
## About The Pull Request

The corporate security jacket has its type-path changed to be a jacket, it also covers the groin now because it's a jacket.

It also has the ability to be unzipped now.

Sprites were taken from [Paradise Station.](https://github.com/ParadiseSS13/Paradise/pull/4899)

## Why It's Good For The Game

A jacket should behave like a jacket.
closes #6018

## Testing Photographs and Procedure
<details>

<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/82319489/150681556-7663f920-6001-4621-8ac6-86989d0c7405.mp4

Ignore the weeb music in the background.
</details>

## Changelog
:cl: FlattestGuitar AnCopper
add: Added a functionality to unzip the corporate security jacket.
fix: The corporate security jacket actually is a jacket now.
imageadd: Added a sprite for the unzipped corporate security jacket.
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
can you still put weapons in its suit storage?

**Comment by AnCopper** [comment]
> can you still put weapons in its suit storage?

Good question. I'll test that.

**Comment by AnCopper** [comment]
> can you still put weapons in its suit storage?

https://streamable.com/hp923i

It can now.

**Comment by hotimep** [comment]
drip buff

**Comment by Archanial** [comment]
Please credit Paradise Station's original contributor.

**Comment by AnCopper** [comment]
> Please credit Paradise Station's original contributor.

I have no idea who it is.
The earliest mention I could find of the jacket on their github page is 7 years old, so it must've been part of their code since the start.

**Comment by AnCopper** [comment]
> Please credit Paradise Station's original contributor.

Meaning, it's impossible to find.

**Comment by AnCopper** [comment]
@Archanial

**Comment by AnCopper** [comment]
> Please credit Paradise Station's original contributor.

Done.

**Comment by AnCopper** [comment]
Yeah no, fuck this.

**Pull request closed without merging**
