### PR TITLE
Standardizes pAI device count

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
Standardizes the pAI device count on in-rotation stations to four public, three non-public, in the following locations:
Library
Bar
Robotics
RnD Lobby
Dorms
RD Office
Command Area (Corporate Showroom, etc)
This increases the pAI device count on Box, Meta, and Pubby, and lowers it on Delta.

## Why It's Good For The Game
The count on Box and Pubby at present is two, with only one public. Bee has an increasing number of pAI mains, and a low pAI device count means that there's a hard limit on how many of them can play the game until at least the twenty minute mark or so.

## Changelog
:cl:
add: pAI device count increased on Meta, Box, Pubby
del: pAI device count decreased on Delta
/:cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
I somewhat think the number of round-start PAIs should be reflective of the station's size. Low-pop maps shouldn't have as many round-start PAIs as larger maps.

**Comment by Ivniinvi** [comment]
I removed the Command Area and Library devices on Box and Pubby, which still ends up increasing the totals vs master on those maps.

**Comment by KubeRoot** [comment]
Ivanmixo pointed out that there are *way too many* changed lines for pubby. I noticed they were introduced when merging master into your branch. Do you have the merge hooks installed on your local repository?

Could you redo the changes to pubby using the file on master to avoid unnecessary changes?

**Comment by ike709** [comment]
Conflicts

**Comment by ike709** [comment]
Also Pubby looks FUBAR

**Pull request closed without merging**
