### PR TITLE
Rewrites and refactors ninja code

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Balance changes:
- sword with teleport on cannot attack people anymore
- smokes and adrenaline boosts don't have set amount anymore, instead they are on cooldown and cost power, this also means that you can't regenerate them with chemicals
- costs and cooldowns has been rebalanced
- you can now upload tech datums directly onto your suit (more fix than a rebalance
- ninja boost no longer injects you with the radium

Rebalanced costs and cooldowns:
- initialize suit: no cost, no cooldown, initializes probably faster since it sleeps not calls timers 
- smoke: costs 300 energy has 30 second cooldown
- boost: costs 600 energy, 1 minute cooldown
- pulse: costs 250, 1 minute cooldown
- star, 50 power, 3 seconds
- net, 600, 1 minute
- recall flat 150, 30 seconds
- stealth 0 activation, 5 seconds between toggles, 25 energy per tick

Ninja starts with 9000 power, this means he can use his steals for 6 minutes straight, use his boost 15 times etc.

Ninja's allegiance has been removed. That means ninjas can get kill/protect and debrain/capture objectives together.
Ninjas have 10% chance to hijack if there's more than 30 players and they don't have protect objective (it's like 2 or 3% realistically).

The code was so stupid it was painful

- [x] rewrite clothing
- [x] rewrite actions to be datums instead
- [x] look into antag datum and objectives
- [ ] rewrite capture objective to not remove players from the round and be overall clearer
- [ ] test

## Changelog
:cl:
refactor: ninja code has been refactored
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
holy shit someone's doing it

**Comment by williamcll** [comment]
Does this change any mechanics?

**Comment by Archanial** [comment]
Most likely yes, but won't change much.

**Comment by Archanial** [comment]
Gonna reopen this when I actually get around to finish it.

**Pull request closed without merging**
