### PR TITLE
Adds Chess Crates and a Maints Chess Room

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Standardizes chess pieces (for holodeck too), adds chess crates at cargo and a chance for a 10x10 space chess room to spawn in maints.

image

## Why It's Good For The Game

Adds people more minigames/stuff to do.
Added crates so I can add them to the changelog.

## Changelog
:cl:
add: Standardized space chess, added space chess cargo crates
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
why does it have syndicate cutouts box in it though?

**Comment by eeSPee** [comment]
> why does it have syndicate cutouts box in it though?

I figured it's a large room, so it needs to have something. And the cutouts are worthless. 

I can remove them if needed.

**Comment by Sinmero** [comment]
Would be nice to have actual chess piece sprites

**Comment by eeSPee** [comment]
> Would be nice to have actual chess piece sprites

In a future PR, perhaps.

Anyway, removed syndicate box (replaced with festive paper hat) and made holodeck chess a minichess variant.

**Pull request merged**
