### PR TITLE
Removes the Sleeper.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Removes the Sleeper from the game entirely.

My motivation that made me do this.
image

## Why It's Good For The Game

Face it, it's a piece of hugbox machinery and makes the game worse by existing.

## Changelog
:cl:
del: Removed the Sleeper.
/:cl:

### CODE REVIEW

**Comment by Unidentified-Biohazard** [comment]
Madlad, +1

**Comment by Lexen74** [comment]
This one's on me folks, i said "code it yourself" as a jab but Belone went ahead and did it. Certified madlad.

**Comment by Naevii** [comment]
No.

**Comment by LastCrusader105** [comment]
Why have you got to be a discount zesko for belone?

**Comment by r1ks-iwnl** [comment]
Atleast zesko adds stuff in his PRs

**Comment by Unidentified-Biohazard** [comment]
I like, remove cloning next please

**Comment by ghost** [comment]
Don't worry guys, I'll recompile TGUI later.

**Comment by TeomanTheGreat** [comment]
░░░░▄▄▄▄▀▀▀▀▀▀▀▀▄▄▄▄▄▄
░░░░█░░░░▒▒▒▒▒▒▒▒▒▒▒▒░░▀▀▄
░░░█░░░▒▒▒▒▒▒░░░░░░░░▒▒▒░░█
░░█░░░░░░▄██▀▄▄░░░░░▄▄▄░░░█
░▀▒▄▄▄▒░█▀▀▀▀▄▄█░░░██▄▄█░░░█
█▒█▒▄░▀▄▄▄▀░░░░░░░░█░░░▒▒▒▒▒█
█▒█░█▀▄▄░░░░░█▀░░░░▀▄░░▄▀▀▀▄▒█
░█▀▄░█▄░█▀▄▄░▀░▀▀░▄▄▀░░░░█░░█
░░█░░▀▄▀█▄▄░█▀▀▀▄▄▄▄▀▀█▀██░█
░░░█░░██░░▀█▄▄▄█▄▄█▄████░█
░░░░█░░░▀▀▄░█░░░█░███████░█
░░░░░▀▄░░░▀▀▄▄▄█▄█▄█▄█▄▀░░█
░░░░░░░▀▄▄░▒▒▒▒░░░░░░░░░░█
░░░░░░░░░░▀▀▄▄░▒▒▒▒▒▒▒▒▒▒░█
░░░░░░░░░░░░░░▀▄▄▄▄▄░░░░░█
Hello there oranges alt (joke)

**Comment by Unidentified-Biohazard** [comment]
speedmerge please

**Comment by Unidentified-Biohazard** [comment]
Medical is too stupid with sleepers.

**Comment by jupyterkat** [comment]
hi orange

**Comment by zeskorion** [comment]
Another quality belone pr

**Comment by Blueturbo47** [comment]
Improve dont remove 
image

**Comment by ike709** [comment]
Not happening unless it's part of a much larger medical rework, and even then it's unlikely.

**Comment by MitztheKat** [comment]
Sleepers are essentially required for how braindead some doctors can be.
Some doctors literally only know cloning and sleeper chems. sometimes only cloning. It's absurd how low brainpower medical is... but when you high brainpower it it's good (especially with the new chems update soon that someone posted)

**Pull request closed without merging**
