### PR TITLE
The revival of Dullahans! + Ventriloquism!

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports:
- https://github.com/tgstation/tgstation/pull/48633
- https://github.com/tgstation/tgstation/pull/63696
- https://github.com/tgstation/tgstation/pull/63939
- https://github.com/tgstation/tgstation/pull/63143

## About The Pull Request
Fixes Dullahans! Makes them actually sorta kinda usable!

### PR 1
- Mostly issues with regenerating limbs, or hearing things

### PR 2

I cant summarize this shit, have the wall of text.

> I present to you a partial unfuckening of the Dullahans, in that I made them fully functional once again:
> 
> - They only hear speech through their head (not sounds, sadly, someone else would have to tell me how to do that because I otherwise really wouldn't know how to do it in a sane way), they speak through their head, runechat-included.
> - When you spawn a Dullahan, you're set to look through the Dullahan's eyes (so from their head), and that doesn't reset when you log off and back in, or admin-ghost and come back in your body.
> - When you're looking through your head, your view will no longer be reset to your body upon entering a locker, which is nice to avoid not being blind while looking through your body.
> - Dullahan heads no longer look completely lifeless and without organs. They have eyes that don't look dead and that even match the player's intended eye color.
> - Dullahan can now properly examine things from their head, which was intended and 100% not functional.
> - Dullahan heads now speak with the proper name of their owner, instead of having a random name attached to it at round-start.
> - Dullahan heads are also now properly named too.
> - Dullahans can now properly whisper, sing and do all these funny things that they were unable to do before.
> - Dullahan whispers will now properly respect the range of the whisper.
> - Dullahans can now succumb in hardcrit by whispering, as intended. This potentially fixes other species that worked similarly not being able to succumb, like abductors, although I didn't test if they normally could, I just know they absolutely will be able to now.
> - When switching from Dullahans to a different species, your old head will no longer stay behind.

### PR 3
- Goofus broke something in the previous pr

### PR 4
- Alas, poor Yorick! You cant speak into your hand holding a head to speak with its voice (Kinda sorta, it DOES say Head of [corpse])

### Additionally
I made Dullahans Undead, to match the other Halloween races

## Why It's Good For The Game
This race is now kinda sorta usable. Probably. Mostly.

The ventriloquism doesnt have *terrible* balance implications, mostly because it adds a prefix of "Head of-". I think its very Halloweeny too.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Dullahan

Uploading dreamseeker_U3ioQyOyCz.mp4…

Hamlet lmao

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/29e416fb-f79d-4724-b0bf-1437ae6abd2e

</details>

## Changelog
:cl: rkz, Ghommie, GoldenAlpharex, Sealed101
tweak: makes Dullahans undead, like the other halloween races.
add: Added ventriloquism to disembodied heads.
fix: Dullahans won't gib when their head is thrown in a recycler, ahealed or have their limbs regenerated somehow.
fix: Dullahans' heads can now be picked up.
fix: Fixes dullahans being unable to receive visible/hearable messages (excluding chat messages)
refactor: Refactored Dullahans in many areas to fix many, many of their bugs and glitches and ensure an actually functional experience playing as one, while also improving as much code as I could along the way.
fix: Dullahans only hear speech through their head (not sounds, sadly, someone else would have to tell me how to do that because I otherwise really wouldn't know how to do it in a sane way), they speak through their head, runechat-included.
fix: When you spawn a Dullahan, you're set to look through the Dullahan's eyes (so from their head), and that doesn't reset when you log off and back in, or admin-ghost and come back in your body.
fix: When you're looking through your head, your view will no longer be reset to your body upon entering a locker, which is nice to avoid not being blind while looking through your body.
fix: Dullahan heads no longer look completely lifeless and without organs. They have eyes that don't look dead and that even match the player's intended eye color.
fix: Dullahan can now properly examine things from their head's view.
fix: Dullahan heads now speak with the proper name of their owner, instead of having a random name attached to it at round-start.
fix: Dullahan heads are also now properly named too.
fix: Dullahans can now properly whisper, sing and do all these funny things that they were unable to do before.
fix; Dullahan whispers will now properly respect the range of the whisper.
fix: Dullahans can now succumb in hardcrit by whispering, as intended. This potentially fixes other species that worked similarly not being able to succumb, like abductors.
fix: When switching from Dullahans to a different species, your old head will no longer stay behind.
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
Well, it appears Halloween came and went.

Not much point to this now.

**Comment by Tsar-Salat** [comment]
hope this is in time for this halloween, atleast

**Comment by Rukofamicom** [comment]
Will this conflict with monkeys?

**Review by Rukofamicom — APPROVED** [review]
What's the worst that could happen.

**Comment by Tsar-Salat** [comment]
> Will this conflict with monkeys?

species.dm will probably throw a single line conflict because this pr adds a var there, and that pr adds a var there.

**Pull request merged**
