### PR TITLE
Nerfs brute kit and ointment self-tending

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Brute kit and ointments will now only self tend until you have 35 damage, at which point you will need to get someone else to treat the wounds.
- Does not affect any other forms of treatment which can be harder to find
- Does not affect healing applied to other people (only self-tending)

## Why It's Good For The Game

An experimentation with making it more difficult to heal without performing some form of player interaction, whether that be asking another player to heal you, asking someone for more advanced healing patches/pill that work on yourself or getting surgery.

We have discussed the potential impacts this may have on many different areas of the game and want to see the impact this has on players when deployed via testmerge (No time today, will do tomorrow).

## Testing Photographs and Procedure

image

image

## Changelog
:cl:
tweak: brute kits and ointments will now only self-tend until you have 35 damage, at which point you will need to seek alternative treatment or have someone else apply it on you.
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
I thought about this quite a bit and I do like actually like it. 

Brute and Ointments shouldn't really be able to heal life-threatening injuries by oneself.

This is a good stop-gap until we port https://github.com/tgstation/tgstation/pull/50558

**Comment by PowerfulBacon** [comment]
> How about antags? I suppose you could just get some pills at med before any antagging but this still feels stinky.

We have thought about antags and I believe that this change is still positive for them. If they want to heal they will be forced to interact with people in some capacity, either collecting pills or forcing/asking someone to heal them. Obviously murderboning gamer antags will be affected negatively, however that's okay.
The main one to watch would be wizard as their healing and balance already sucks.

**Comment by Fronsis** [comment]
> > How about antags? I suppose you could just get some pills at med before any antagging but this still feels stinky.
> 
> We have thought about antags and I believe that this change is still positive for them. If they want to heal they will be forced to interact with people in some capacity, either collecting pills or forcing/asking someone to heal them. Obviously murderboning gamer antags will be affected negatively, however that's okay. The main one to watch would be wizard as their healing and balance already sucks.

Indeed, it's very common for Wizards/Ninjas and sometimes Nightmares to have the med storage as one of their first targets to raid (not counting wizards with apprentices with healing or.. i don't think we have self-targeting wand effects fo healing) 

It will be interesting how this will play out though i hope it doesn't lead to some people (antags in medbay department) to steal a lot in preparation for their business or just people demanding them under vague excuses, though at that point it'll be up for the CMO or medical personnel to be aware of what's going on 

I assume the ones that will be a little on top on this would be miners and explorers, depending how this goes a special tot healthkit similar to the nukie exclusive(but weaker) could be introduced if it goes too much out of hand

**Comment by wikimody** [comment]
Anyone forgeting abaut one job which neds a lot of healing and is alone 90% of the time? How will this work for miners? They get hurt all the time have limited acces to advance meds (legion cores only if the find them) and their chance of liveing depends on their HP the most. Aditionaly gruping up as miners is inefietient and not used against anything other that lavaland bosses and they cannot return back to station each time they get hurt. For this to work miners eyther have to get pass for self healing as a part of a job or they have to get cheap and good way to heal small amounts of damade. Side note can we eyther change superfitial healing syptom from viro or change the amount of damade being cap here so this syptom is actualy usfull? I feel like it woudl par greatly with this change if the numbers are changed

**Comment by PowerfulBacon** [comment]
I did not forget about miners, they will either have to use legion cores or return to the base/find another person to heal them using communication tools.
Hopefully in the future we can move to a full rework where mining is more team based and closer connected to the station.

**Comment by wikimody** [comment]
How often do you play miners? Often there are only 2 alive and in totaly difrent parts of lavaland at that. It is realy tedios to go all the way to the base especjali since it is preaty easy to get lost if you dont look at your GPS which is somthing that is preaty comon from my expierience. And caling miner to find  you on lavaland is even harder especialy is somone doesnt have GPS. untill some kind of rework to make it team based its only ads risk that you shoudl be able to avoid (less health) and tedium of searching for somone to heal you. Also legion cores, yes the are most powerfull  healing item in the game but there is finate amant of them unless you find legion tendrill and none destroes it and aditionaly they are completly luck depended. I remember rounds where i coudnt find even one for first 30 minuts and even then i found 3 for entire rest of the round. Dont make mining luck dependend even more that its alredy is.
Side note making first aid kits bulky is only efective against newbies. I saw i coudnt put it into bag so i just made a boxs and put all the items inside it. Any veteran knows how to do this so this change only hits the new players and they have hard enof time even now

**Comment by wikimody** [comment]
To put all my problems with this idea in one pacet here are they: Miners job ismuch more eyther dangerus or tedius (choice betwen runing araund with up to 70 untreted damade or hunting legion cores or other miners which both can be youst not exist) and second problem is much biger strain on medbay since the most comon way to heal smal damades is now gone and even if you have 3 points of damade you now need to go to medbay or pester somone with a medcit. Adytionaly if there is some kind of disaster and medbay is ocupied with dead and dying you cannot realy heal yourself and have to wait on dangures levels oh HP until dead are revived (that is unles we have competend chemistry which isnt given). 3 thing with paches nerf some time back which stoped pathes from aksuali healing on aplication this nerf removes all comonly used ways of instantanius healing which isnt good in my opinion. I thing the delay with using it on yousrself is alredy incentive enof to ask somone else to do it acomplishing exacly what we talk abaut here without forcing you to do it if you are in situation when it is not posible or just not worth doing (for example going from enginiering to medbay to heal 3 burn damade gained from toching a ligtbublb without glowes). 4 thing and what i think is the bigest flaw of this system is the fact that this mostly hits new players. As a veteran i know how to secure beter healing suplies i know how to cheat biger size of first aid kit by using boxes and know alternative wais of healing (lavaland fruit, nanits, donk pocets for example) but new player doesnt know that and this change increses knowlege neaded to play SS13 even more which i dont think is a good thing. If you can adres this points and fixs this problems or give good alternative ways of healing that fixs them (giving miners automenders from parastation comes to mind) i thing this coudl be good change to the station. Othervise it is at best unesesary and at worst activly harmful.

**Comment by Kratairo** [comment]
Miners aren't really affected if you are somewhat competent so not really an issue. But either way I disagree with this pr heavily because all it does is fuck over antags because...? Not sure why honestly. Not sure how adding meaningless medbay interaction makes the round more interesting except for valid hunters since any injuries are basically permanent with this 

Also why not a balance tag, it has heavy implications.

**Comment by PowerfulBacon** [comment]
I disagree,

**Why have interactions when players can do it themselves?**

SS13 is all about interactions, its what makes the game so interesting even after so many rounds.
- Interactions often leads to more interactions.

**Will this mess with the antag meta?**

Yes, of course this will affect the antag meta, however I don't think it will have a huge impact.
Basic meds will be less effective if you cannot find someone to interact with, however this only affects basic meds.
The hope is that antagonists will still be able to find ways to get people to heal with them, or find alternative healing methods.
It should also be noted that the limit to healing is quite high.

**Comment by Kratairo** [comment]
> I disagree,
> 
> **Why have interactions when players can do it themselves?**
> 
> SS13 is all about interactions, its what makes the game so interesting even after so many rounds.
> 
While agree with you on that to a certain degree, I do not believe this isn't really an interaction and more a hurdle. Just waiting someone to finally fix you isn't exactly meaningful interaction. 

Also 35 health is pretty significant considering that it's effectively a third of your health and means the next instance of damage will slow you (or is that enough damage to be slowed already?)

**Comment by Tsar-Salat** [comment]
> Just waiting someone to finally fix you isn't exactly meaningful interaction.

The whole point is to decrease overreliance on the ointment and brute packs. Any competent chemist is going to have tricord/Silver Sulf ready by the 15 minutes mark. Which you can freely take wherever you want. You don't need someone else to apply it.

Chems actually respect game ticks, ointment and packs do not.

**Comment by wikimody** [comment]
> The whole point is to decrease overreliance on the ointment and brute packs. Any competent chemist is going to have tricord/Silver Sulf ready by the 15 minutes mark. Which you can freely take wherever you want. You don't need someone else to apply it

There are many shifts both lowpop and not in wchich eyther there are no hemists or they arent doing their job properly. It is not given that there will be beter chealing metods and hemists are alredy relied upon for healing anything more complicated that base damade.

> Chems actually respect game ticks, ointment and packs do not.

The same game tics that break prety oftem making cheling with hems extreamly slow until they fixs themself? Also self healing with brute pacs is slowed down and even with somone else healing you finding all the damaded body parts takes time.

**Comment by PowerfulBacon** [comment]
You could consider it a hurdle to anyone trying to avoid interactions entirely by carrying around meds with them everywhere, as intended.
This PR seemed to have the intended, positive, impact I was looking for during testmerge, will put it on some more and watch how it goes.

**Comment by wikimody** [comment]
> I do agree that this hurts miners quite a lot, and until a miner rework is done (how many months will that take) will just force miners to stop mining, use legion cores and wait out the debuff so they can use a new one when needed. A simple suggestion to help alleviate this would be to remove (or almost completely remove) the nutrition/sugar from cactus fruits, so they can be used as a reliable small healing and not a death sentence after 3 of them.

Agried but it also shoudl be done to the healing shrom since it does the same thing. Making them not make you fat woudl fixs a lot of problems with miner healing

**Comment by Rukofamicom** [comment]
I've taken this idea and incorporated it into the above PR

**Comment by CydiaLamiales** [comment]
> How often do you play miners?

Miners also have legion cores and survival medipens. Hell, those are the main sources of healing for them I'd say.

**Comment by BriggsIDP** [comment]
> > How often do you play miners?
> 
> Miners also have legion cores and survival medipens. Hell, those are the main sources of healing for them I'd say.

You have a lot more hours in miner than I do, but I think cores and pens are only useful in dire circumstances, because they are *so* good at helping, you want to save them for when you need them. Pens are a little expensive to be used for every yellow arm, and cores can be hard to get sometimes, not to mention have a long cooldown on using them. When mining I take a bruise pack with me to heal the damage from one Goliath. Some limbs are yellow-orange causing a lot of slowdown on your first 1 or 2 mobs

**Comment by Rukofamicom** [comment]
>  you want to save them for when you need them.

Cores have a pretty damn short cooldown. If you are in "dire need" of healing more often than this, you're playing poorly. Miners also have access to cactus for minor wound healing. 

All in all though, I really don't think miners should be totally exempt from needing to visit medbay now and then anyway, even if this PR isn't going to make them need to - they should have access to their own healing, but it shouldn't be 100% self-sufficient healing if they're engaging in non-stop combat. You **can** choose to avoid most mobs instead of mowing them all down. They're slow and not all that aggressive unless you just idle near one for an extended period of time or get pretty unlucky.

**Comment by Isy232** [comment]
I like ruko's solution a lot more

**Comment by PowerfulBacon** [comment]
Supersceded by https://github.com/BeeStation/BeeStation-Hornet/pull/8572

**Pull request closed without merging**
