### PR TITLE
Heads of Staff are visible to Revolutionaries

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Adds a flashing Nanotrasen N next to the heads of staff.

## Why It's Good For The Game

Heads can no longer hide as a random assistant on revs round, and avoid being killed due to the rules about killing innocent people.
This will prevent heads from hiding and delaying the rounds by being among us.

## Testing Photographs and Procedure

(As HOP)
image

(As head rev)
image

(As normie)
image

## Changelog
:cl:
add: Heads of staff are now visible to revolutionaries via a flashing N.
/:cl:

### CODE REVIEW

**Comment by Rukofamicom** [comment]
While this makes the mode a little more cheese-proof at a glance, this also highlights the fact this game mode often boils down to just "whack the valid, he's over here". I also think this actively encourages that sort of play.

**Comment by PowerfulBacon** [comment]
Yes

**Comment by Penwin0** [comment]
> While this makes the mode a little more cheese-proof at a glance, this also highlights the fact this game mode often boils down to just "whack the valid, he's over here". I also think this actively encourages that sort of play.

Revs really isn't going to change from that without a rework,  this will probably help with rev rounds taking ten years, which is nice

**Comment by Rukofamicom** [comment]
My point was Revs should be disabled rather than *further enabling* the worst aspects of it just so the rounds conclude faster. 

Making it easier to hunt and wack the valid instead of encouraging people to to take the time to communicate isn't the way forward if we're keeping it.

**Comment by PowerfulBacon** [comment]
I mean, at the same time the chaotic situations often tend to lead themselves to some level of roleplay and at the very least, some more interesting gameplay. Security will communicate and work with each other and you can get regular crew working together.
Rounds where nothing happens almost never leads to good RP and the game is a lot more boring.

**Comment by llol111** [comment]
Not a fan

**Comment by FriendlyContractor** [comment]
I completly disagree with ruko. As it is revolution is one of the best if not the best of the gamemodes we have.

- **Its engages everyone** - gamemodes such as traitors or changelings involve only very small percent of players. Rest of the players are obliged by rules to do repetetive and meaningless tasks, assuming they get any at all during the round. Also rules largely forbid players and antagonists from interacting with each other and completly ban those antagonists from challenging the station as a whole
- **Roles on the station become important and get meaningfull work to do** - As it stands every role on the station from the lowly janitor to captain rely on antagonists causing trouble and chaos which generates meaningfull work for them to do. As rules which are **against the common sense and game design** mandate that they do not generate work for others players , gameplay for them falls flat and ends up extremely boring and repetetive most of the time. Janitor has no mess to clean up. Doctors have nobody to treat for injuries. Roboticist can construct thousands of cyborgs but they are going to be as bored as everyone else. On the other hand during the revolution medical staff is sure to have their hands full and their work plays important role in ultimate goal which is their teams victory. Captain becomes extremely important team leader and gets a crisis to manage. Xenobiologist finally gets a reason to come out of his department and distribute fruits of his work.
- **It has objective players are united to work towards** - There is a clear goal which in case of revolution is eliminating opposing side. Players are encouraged to work together towards their side victory. There is a clear end goal to achieve. This gives player actions ultimate purpose and goal other gamemodes can lack. As a side bonus it also helps eliminate unwanted grief as there are no players with nothing else to do.

**Comment by Kapu1178** [comment]
this is how revs have been on goonstation for years

**Comment by EvilDragonfiend** [comment]
I think it should be done in two ways.
* [This PR] Heads can be identified by rev heads.
* [another way] Revs no longer recognise their comrades visually. maybe code phrases can be given.

**Comment by Rukofamicom** [comment]
Alright your arguments have convinced me. Let's give antagonists a literal "valid detector" with the hope that this will somehow lead to better RP and less charging at and whacking valids wordlessly. 

> Revs no longer recognise their comrades visually. maybe code phrases can be given.

This is actual way to improve rev rounds and slow down the slaughterfest of it a bit.

**Comment by DatBoiTim** [comment]
> I think it should be done in two ways.
> 
> * [This PR] Heads can be identified by rev heads.
> * [another way] Revs no longer recognise their comrades visually. maybe code phrases can be given.

Both??? Maybe just a great way to ensure heads don't hide but also make revs less kill happy.

**Comment by EvilDragonfiend** [comment]
> > I think it should be done in two ways.
> > 
> > * [This PR] Heads can be identified by rev heads.
> > * [another way] Revs no longer recognise their comrades visually. maybe code phrases can be given.
> 
> Both??? Maybe just a great way to ensure heads don't hide but also make revs less kill happy.

Both? oh, maybe. maybe it can be way better.

**Comment by EvilDragonfiend** [comment]
So, speaking of code phrase...
Once there was an event round where I had to be a rev head, but the goal isn't just killing heads, instead, achieving something as my goal. It was every crew gets AA.
At the round, the catchphrase was 'For AA', not viva shit.

I think rev heads should decide their own catchphrase and use it as a code phrase.
~~and revolutionaries should get their mood as "something catchphrase" instead of saying viva la revolution.~~
Maybe, just letting them know from checking their memories like traitor does.

**Comment by FortSumter** [comment]
I don't know how I feel about revs. Personally I like antags that work individually with an option to cooperate like traitors and changelings, with the lone exception being nuke ops. Game modes like revs and blood cult assume that the people who initially roll for starting cult or headrevs know what they're doing, then also assume that the people they convert _also_ know what they're doing.

What it ends up boiling down to is how many important/robust people can you convert before security/command get alerted to your activity. If you get found out early or only convert useless idiots, you lost as security mass mindshields everyone. If you happen to recruit the one god-like veteran player, you won as he beats the HoS to death with a toolbox followed by everyone else who dares to try and stop him.

I find it pretty rare for revs to get to the point where they've taken over. I wouldn't mind this if the symbol only appeared once the large majority of the crew have either been killed or converted. I've had more rounds go wrong because the last headrev hid somewhere to prevent the escape shuttle from leaving than a head of staff though....

**Comment by PowerfulBacon** [comment]
The goal of this PR is to prevents heads from abandoning their position as a head of staff and being undetectable. Ideally hiding as a head would count as being overthrown since you gave basically given up at that point but it's easier to mark them on the hud.
It's a 3 line change and any other reworks that don't change what I intend to change are out of scope.

**Comment by PowerfulBacon** [comment]
> So, speaking of code phrase...
> Once there was an event round where I had to be a rev head, but the goal isn't just killing heads, instead, achieving something as my goal. It was every crew gets AA.
> At the round, the catchphrase was 'For AA', not viva shit.
> 
> I think rev heads should decide their own catchphrase and use it as a code phrase.
> ~~and revolutionaries should get their mood as "something catchphrase" instead of saying viva la revolution.~~
> Maybe, just letting them know from checking their memories like traitor does.

The problem with thatvis deconversions

**Comment by mcmeiler** [comment]
I'd rather have revs play a 60 person game of Among Us than this

**Comment by PowerfulBacon** [comment]
With the rules banning anyone who attacks regular crew, this is needed as you can dress as an assistant and essentially gain meta immunity if you don't attack

**Comment by AnCopper** [comment]
I'm getting conflicting information here. Is this only for revheads or all revs?

**Comment by PowerfulBacon** [comment]
> I'm getting conflicting information here. Is this only for revheads or all revs?

All revs, there is no easy way to do it for only heads due to the HUD being shared

**Comment by zeskorion** [comment]
this should let heads see headrev icons as well, perhaps at a certain time/conversion benchmark

**Comment by mcmeiler** [comment]
> With the rules banning anyone who attacks regular crew

When the headcoder doesn't know the rules.

The rules will ban anyone who murders people instead of attempts at conversion if it's possible. Not for killing people in general.
For example, a headrev flashing someone without flash protection, realizing they can't be converted, then murdering them wouldn't get you banned. Straight up killing people with no attempts at conversion, if available, *will* get you banned.

**Comment by PowerfulBacon** [comment]
> Straight up killing people with no attempts at conversion, if available, will get you banned.

It's almost as if only 3 people on the entire station can convert, making them effectively have some level of meta protection to everyone else. You just describe exactly what I was saying.

**Comment by Sinestia** [comment]
> My point was Revs should be disabled rather than _further enabling_ the worst aspects of it just so the rounds conclude faster.
> 
> Making it easier to hunt and wack the valid instead of encouraging people to to take the time to communicate isn't the way forward if we're keeping it.

That's a separate convo tho


While the gamemode is here you may as well make it the best it can

**Comment by Rukofamicom** [comment]
I don't consider this an improvement over no change

**Comment by PowerfulBacon** [comment]
> I don't consider this an improvement over no change

It does improve the gamemode though due to the problem being that the target knows they are a target.
There are 3 gamemodes that I can think of right now that have a target who knows they are the target of someone: Nuke ops, Revs and Incursion.
Nuke ops handles this by giving the antagonists something that points them to their target, meaning it cannot be hidden in some place to screw over the antagonists and ruin the mode.
Revolution doesn't handle this, the targets can hide as someone else and become basically impossible to defeat. This PR solves that.
Incursion is the other one, incursion also handles it quite poorly as the targets know they are being hunted but can hide as someone else. The only thing stopping them from doing that is that they have to stay on top of their existing objectives, but should probably have some change to it too.
Other gamemodes like cult get around it by having it so the targets could come from a pool of people, so its not always the chaplain. This solution isn't possible for revs because of the nature of the gamemode, so a nuke op style approach is the best solution for now.

**Review by Crossedfall — CHANGES_REQUESTED** [review]
Turn it into an actual item, like sechud glasses, and make it so there is only a single pair. 

Item description can be something like, "Provided by an unknown benefactor. These glasses utilize advanced active recognition technology to identify Nanotrasen heads of staff."

Making it an item means that there's at least _some_ counterplay. It means that the glasses can be stolen or destroyed. It can also be used to loosely identify rev members.

**Comment by PowerfulBacon** [comment]
Revs don't get communications or items from unknown benefactors since they are an uprising on that specific station against command. (I guess they have their modified flashes, but they can make them themselves by just using any flash).
In addition, having the glasses able to just be destroyed means that if they get destroyed, then what?
It could be a crafting item and give heads a custom crafting menu I guess but then its a lot more effort for basically the same solution, if not for probably not being ever used since heads only ever just give up acting as heads in a small minority of rounds, so it only actually affects the more rare cases of just someone purely gaming the system.

**Comment by Crossedfall** [comment]
> Revs don't get communications or items from unknown benefactors since they are an uprising on that specific station against command. (I guess they have their modified flashes, but they can make them themselves by just using any flash).

The implication is that the Syndicate pushed the crew into revolting and provided them with some basic gear (the flashes and the glasses) to get the job done. It's just a bit of flavor.

> In addition, having the glasses able to just be destroyed means that if they get destroyed, then what?

Then they're back to having to rely on spotting heads out themselves.

**Comment by FortSumter** [comment]
It's not so much the problem that heads blend in with the crew, rather that they have the access to move about the station that many of the crew don't have. Perhaps a compromise would be to give the revheads an implant that points in the direction of the closest head of staff like the IAA target tracker implant used to do.

**Comment by FortSumter** [comment]
It wouldn't be as reliable as being able to just look at a disguised head of staff, but it'd be helpful for what this PR is trying to do while also being more general use.

**Comment by Sapfearon** [comment]
people in comments think that revs get banned for murderboning crew - you guys all wrong. Literally every single rev round in last months revs murder most of crew without trying to convert and like never ever get banned for it despite several active admins. Not only that, but we also recently learned that rev viro releasing virus killing 70% of all crew is totaly fine (hello aeder). It's so common that everyone ignores it and accepts it at this point.
Meanwhile if loyalist have no cash/mindshields they have no way of deconverting and literally only option of getting out is to murder everyone without mindshields. (anyone checked if hitting people to head with blunt object even works as deconversion method?)
So to fix this you give revs...valid detector? Really? This should work both ways then and only for headrevs/heads, not normal people. Right now it's just buff for revs.

**Comment by FortSumter** [comment]
> Literally every single rev round in last months revs murder most of crew without trying to convert and like never ever get banned for it despite several active admins. Not only that, but we also recently learned that rev viro releasing virus killing 70% of all crew is totally fine (hello aeder). It's so common that everyone ignores it and accepts it at this point.

This is a staff issue not a gameplay one. Most players who've played here a while are aware that killing is only acceptable on crew that cannot be converted or deconverted. Any admin who allows this short for a roleplay reason is a bit bald and should be set straight by a seniormin. 

> anyone checked if hitting people to head with blunt object even works as deconversion method?

Yes, it does work. I've accidentally deconverted someone via toolbox to the head before, but it does take a lot of hits before it works and they could always be converted again, and easily due to advanced sunglasses being so rare.

> So to fix this you give revs...valid detector? Really? This should work both ways then and only for headrevs/heads, not normal people. Right now it's just buff for revs.

I believe that was kind of the point. If they made these glasses/sunglasses, the headrevs would be identifiable by security which may make this a bit more balanced? I think the main problem I have is the lack of roleplay this mode allows as the Revs basically go straight for murdering the heads and security's response is basically standard procedure to mass purchase mindshields and makes the mode rather shitty for everyone involved.

**Pull request closed without merging**
