### PR TITLE
Changes airlock bolt noises.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Title

## Why It's Good For The Game

Makes them sound more mechanical, they also sound cooler imo.

They are from Alien Isolation / Tau Ceti Station.

## Changelog
:cl:
tweak: Airlock bolt/unbolt now sounds different.
/:cl:

### CODE REVIEW

**Comment by MrHorizons** [comment]
What if you added the "chimes" at the beginning of the original sounds to these ones? That way, I think it'd be easier for people to adapt to them and they'd be more noticeable.

**Comment by ghost** [comment]
> What if you added the "chimes" at the beginning of the original sounds to these ones? That way, I think it'd be easier for people to adapt to them and they'd be more noticeable.

good idea, although i dont know how to edit sound im gonna try it.

well i tried what i can do and it ehh doesnt sound very good.

**Comment by ghost** [comment]
[noises.zip](https://github.com/BeeStation/BeeStation-Hornet/files/5283970/noises.zip)


@MrHorizons this was the result

**Comment by MrHorizons** [comment]
> [noises.zip](https://github.com/BeeStation/BeeStation-Hornet/files/5283970/noises.zip)
> 
> @MrHorizons this was the result

Hmm. I'm going to try to make some.

**Comment by PowerfulBacon** [comment]
Can we even use shit from alien isolation?

**Comment by ghost** [comment]
> Can we even use shit from alien isolation?

i mean, Tau Ceti station uses it, and they are fine.

**Comment by Cenrus** [comment]
Bay12 uses the same sound and it's a huge improvement imo

**Comment by MrHorizons** [comment]
[newairlocksounds.zip](https://github.com/BeeStation/BeeStation-Hornet/files/5286827/newairlocksounds.zip)

@BeloneX Here's what I did.

**Comment by ghost** [comment]
> [newairlocksounds.zip](https://github.com/BeeStation/BeeStation-Hornet/files/5286827/newairlocksounds.zip)
> 
> @BeloneX Here's what I did.

sounds good, i'm gonna add those.

**Comment by Crossedfall** [comment]
> 
> 
> Can we even use shit from alien isolation?

Not unless their sounds were openly sourced and free to use.

**Comment by ghost** [comment]
> > Can we even use shit from alien isolation?
> 
> Not unless their sounds were openly sourced and free to use.

Other servers like baystation and tau ceti use them aswell though.

**Comment by MrHorizons** [comment]
> > > Can we even use shit from alien isolation?
> > 
> > 
> > Not unless their sounds were openly sourced and free to use.
> 
> Other servers like baystation and tau ceti use them aswell though.

Also consider that I've somewhat onto them, which should put it closer to the area of fair use.

**Comment by PowerfulBacon** [comment]
> 
> 
> > > > Can we even use shit from alien isolation?
> > > 
> > > 
> > > Not unless their sounds were openly sourced and free to use.
> > 
> > 
> > Other servers like baystation and tau ceti use them aswell though.
> 
> Also consider that I've somewhat onto them, which should put it closer to the area of fair use.

Adding to copyrighted sounds, doesn't make it fair use and some license specifically disallow the altering of licenced sounds

**Comment by Crossedfall** [comment]
Closing since the repo/branch no longer exists and I honestly don't feel comfortable bringing this in.

**Pull request closed without merging**
