### PR TITLE
[Port] Cyborg Module Reset wire always revealed on hacking interface.

### PR DESCRIPTION
**Pull request by bloons3**
## About The Pull Request

Ports https://github.com/tgstation/tgstation/pull/53277 along with non-skillchip trait assignment (booo)

## Why It's Good For The Game

image

## Changelog
:cl: Mothblocks
add: The Research Director and Roboticist gain a trait that lets them identify robot wires
tweak: When hacking cyborgs, the Module Reset wire is now far more obvious.
/:cl:

### CODE REVIEW

**Comment by eeSPee** [comment]
image

Just remove the star and have this be the default for anyone?

**Comment by PowerfulBacon** [comment]
it straight up tells you which one is the reset wire anyway, I'd say make the text more obvious at the bottom "There is a star symbol above the [get_color_of_wire(WIRE_RESET_MODULE)] wire."

**Comment by bloons3** [comment]
You still have to Wiki-Dive to know that

This is more explicit

**Comment by bloons3** [comment]
no desire to maintain

**Pull request closed without merging**
