### PR TITLE
Moves Xenoarchaeology on Kilo Station

### PR DESCRIPTION
**Pull request by dog132-ss13**
## About The Pull Request

This PR moves xenoarchaeology above the exploration dock on Kilo Station.

## Why It's Good For The Game

The old xenoarchaeology room had no access restrictions and was slapped onto the science shuttle dock, which is in an area which can be cumbersome to access (I know, I mapped the dock myself). The new location is much more accessible, being an offshoot of the hallway leading to exploration. It is not a perfect spot, but it is much easier to find. The solars have been moved back to their original place - where the old xenoarch room was - which makes them easier to access by engineers.

## Testing Photographs and Procedure
<details>

<summary>Screenshots&Videos</summary>

Before:
image

After:
image

</details>

## Changelog
:cl:dog132
tweak: Kilo Station - the Xenoarchaeology Lab has been moved to above the Exploration Docks.
/:cl:

### CODE REVIEW

**Comment by CydiaLamiales** [comment]
I don't see a medkit in the picture.

**Comment by dog132-ss13** [comment]
When has science ever advanced when it was tied down by silly things like health and safety? (but I'll add one)

**Comment by CydiaLamiales** [comment]
Add a health analyzer too since those no longer spawn in thr medkits.

**Review by PestoVerde322 — APPROVED** [review]
All seems good, approved.

**Pull request merged**
