### PR TITLE
Holodeck Fixes

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

* Moved holodeck templates from _maps/template to _maps/holodeck.
* Fixed some maps that were not ported properly.

## Why It's Good For The Game

Better directories, and now some holodecks work properly.

## Changelog
:cl:
tweak: Moved holodeck templates from _maps/template to _maps/holodeck.
fix: Fixed some maps that were not working properly.
/:cl:

### CODE REVIEW

**Comment by jupyterkat** [comment]
isn’t it restricted because it has a full surgery toolset and a surgery table now, and any assistant can just do surgery now?

**Comment by eeSPee** [comment]
> isn’t it restricted because it has a full surgery toolset and a surgery table now, and any assistant can just do surgery now?

Was like that before; had entire surgery kit, including circular saw and surgery drapes.

Will leave up to debate,

**Comment by jupyterkat** [comment]
what do you mean it was? it still is
image

**Comment by eeSPee** [comment]
> what do you mean it was? it still is

I mean, the Emergency Medical program was available without safeties, and had a full surgery kit and operating computer, before the holodeck PR.

**Comment by utilbird** [comment]
surprise surprise eeSPee putting balance changes in "fix" changelogs/PRs 😏

**Comment by eeSPee** [comment]
> surprise surprise eeSPee putting balance changes in "fix" changelogs/PRs 😏

PR #4333 did not state that some programs (emergency medical) are now restricted, when they previously were not.

I assumed it was an oversight.

**Comment by eeSPee** [comment]
Removed medbay change; it's restricted again.

**Comment by bloons3** [comment]
> surprise surprise eeSPee putting balance changes in "fix" changelogs/PRs 😏

mood

**Review by utilbird — APPROVED** [review]

**Pull request merged**
