### PR TITLE
Gasses and fire resprite

### PR DESCRIPTION
**Pull request by kiekatz**
## About The Pull Request
resprites fire and gasses. more precicely the resprited gasses are

tritium, plasma, nitrous oxide, water vapor, nitryl and feron
alongside the 3 states of the fire sprite

nitrous oxide, water vapor, nitryl and feron have the  same recolored sprite
## Why It's Good For The Game
desoulifying sprites

less dev sprites. now you can burn to death in style
## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

top to bottom tritium, generic smoke(in this case N2O),plasma

https://github.com/user-attachments/assets/40c82cfa-48e2-4df9-aa24-3df13bb57f5e

https://github.com/user-attachments/assets/27e77270-05e7-47be-b4a6-1d7f84d169ab

https://github.com/user-attachments/assets/a543cb82-32d8-4489-9186-16e0624639b9

</details>

## Changelog
:cl:kit-katz
imageadd: changed sprites for tritium, plasma, nitrous oxide, water vapor, nitryl, feron and fire
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
The fire needs a bit more intensity to it, some parts look more like gas than fire, particularly here. 

image

**Comment by kiekatz** [comment]
the reduced transparency effects that are applied on the fires tricked me a bit... i'll up the intensity of the sprite

**Comment by MarkusLarsson421** [comment]
I love this! Perhaps now people won't open airlocks to seemingly empty rooms only to be showered with 100 000 000K hot plasma which instantly fills the hallways.

**Comment by JixS4v** [comment]
Ngl i'm not a fan of the way they tile, honestly think the old ones looked better in that aspect.

**Comment by kiekatz** [comment]
fire sprites have some feature that rotates them randomly. and that's the thing that causes the poor tiling. in truth the fire is tiled

**Comment by kiekatz** [comment]
upped 1 and 2 fire intensity. there's still some low intensity fire but that's fire tiles with very low opacity

https://github.com/user-attachments/assets/810d98a2-1800-4579-9208-c16eb5b5f319

aand it checked the tiling part. removing the 4dir seems to work without breaking anything

https://github.com/user-attachments/assets/621f8c9e-686d-46fd-b64c-9ae704b4d926

**Review by Rukofamicom — APPROVED** [review]

**Review by PestoVerde322 — APPROVED** [review]
Approved, altought i wanna see more screens with all the gasses and overlapping gasses (plasma+nitril or tritium)

**Pull request merged**
