### PR TITLE
Removes don't Improves X-ray mutation

### PR DESCRIPTION
**Pull request by Sinestia**
## About The Pull Request

Removes the ability to combine mutations to make x-ray

## Why It's Good For The Game

It's something that comes up often, was bored, thought i may as well do it real quick

and imo, is probably the strongest mutation. Especially if distributed and absolutely massacres a lot of antags, especially ones who play remotely stealthy (not talking just passive bois either)

**There are other ways to get x-ray too**, it's just that they require actually getting someone to surgically implant something. So a lot higher effort if you want this same power, more fitting for how powerful the reward is. 

## Changelog
:cl:Froststahr
del: X-ray is no longer a possible reward from genetics. 
/:cl:

### CODE REVIEW

**Comment by utilbird** [comment]
Why remove one of the last relevant things in genetics. It's definitely one of the strongest mutations, but that doesn't make it overpowered, removing something because it's the strongest of it's kind is possibly one of the worst reason you could have listed. 

Genetics is outshined by most other (reward based) jobs. Hulk, x-ray and space adaption are for the most part, the only worthwhile mutations to obtain. x-ray being the only one of those that are passively useful for a non-antag.

I ded

**Comment by OceanFish1** [comment]
Ah yes lets make genetics even more castrated as a job and less fun as a thing to do. Literally the most boring job on the station and you want to make it less helpful.
If you think it's op there's also instabillity for this so,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

**Comment by Sinestia** [comment]
> Why remove one of the last relevant things in genetics. It's definitely one of the strongest mutations, but that doesn't make it overpowered, removing something because it's the strongest of it's kind is possibly one of the worst reason you could have listed.
> 
> Genetics is outshined by most other (reward based) jobs. Hulk, x-ray and space adaption are for the most part, the only worthwhile mutations to obtain. x-ray being the only one of those that are passively useful for a non-antag.
> 
> I ded

I haven't played antag in awhile, more of a "heded" especially if we want to have stealthy antags that utilize maints. 


Anyways. Those other mutations are incredibly strong, genetics isn't really lacking in fitting rewards for the time you put into it, it's lacking in good gameplay to reach its ends. It's the worst "rewards based" job out there.

In fact maybe it's not a miracle that people don't use x-ray more often, maybe it's because no one's willing to play genetics.

For alternatives, i thought of making flashes even more effective if you had it. But that doesn't really do anything, and stacking it with other mutations isn't what I care about so instability doesn't matter either.

**Comment by Effemu** [comment]
>Anyways. Those other mutations are incredibly strong, genetics isn't really lacking in fitting rewards for the time you put into it,

when someone says genetics is rewarding

**Comment by ghost** [comment]
Stealthing as an antag is already a mostly hopeless endeavor given how many players in a given round have maint access and an AI's ability to instantly jump its camera to anybody who types ;HELP. Players having literal x-ray vision just throws the idea of stealth out the window entirely. Thermal/x-ray implants are also overpowered and will have to get nerfed eventually, there just aren't that many people installing it on themselves every single round (yet).

Genetics has been a scuffed job for years, the only improvements to it that can be made short of a total rework is to nerf the powerups they create.

**Comment by yyzsong** [comment]
How does instability make X-ray not OP lol

**Comment by TheFakeElon** [comment]
:trollface:

**Comment by utilbird** [comment]
I love democracy

**Comment by Sinestia** [comment]
> I love democracy

You didn't give me enough time to set up the bots

**Comment by Rukofamicom** [comment]
> Genetics is outshined by most other (reward based) jobs. Hulk, x-ray and space adaption are for the most part, the only worthwhile mutations to obtain. x-ray being the only one of those that are passively useful for a non-antag.

*Someone doesn't know genetics has access to fireball*

**Comment by TheFakeElon** [comment]
> Someone doesn't know genetics has access to fireball

If you're talking about the lizard one feel free to rebalance that.

**Pull request closed without merging**
