### PR TITLE
Nukie Shuttle Rebalance

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
Armour has been changed to favour explosives, melee and acid while lasers are less efficient at dealing damage to them.
Range has decreased from 9 to 7 (view range is at 6).
Bullet type is the same as the Syndicate outpost now instead of being a literal sniper bullet.
Turrets can no longer see into the shuttle either.

Added some misc medical aid, posters, mech recharger and weapon rechargers.
Removed a few of the extra medkits.

Added shutter windows to each shuttle section.

## Why It's Good For The Game
Gives the crew a fighting chance to be able to engage the Nukie Ship and makes the shuttle look cooler and have some more neat things.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

### Turret testing.

Range of where it can see you. 

image

2-3 shots will kill someone without any armour.

image

4 shots will crit someone with a captains hardsuit.

https://github.com/user-attachments/assets/47fbe4ce-59f1-485a-ac06-4ed30c164f17

3 shots will crit someone with body armour (not the ones Security spawns with but the armoury one).

https://github.com/user-attachments/assets/cc30035d-70bb-4d36-8bc0-fe53b4d8384d

### Shuttle

image

https://github.com/user-attachments/assets/c984728c-c663-430e-a1c3-c493e9ec5dd4

</details>

## Changelog
:cl:
balance: [Nukie Shuttle] Nerfed turrets.
balance: [Nukie Shuttle] Added mech recharger, weapon recharger and cell recharger.
balance: [Nukie Shuttle] Added various medical equipment and removed three (out of four) First Aid Medkits.
tweak: [Nukie Shuttle] Redecorated the design of the shuttle.
add: [Nukie Shuttle] Added Syndicate intercoms.
fix: [Nukie Shuttle] Changed location of pod door button to ensure Station Cyborgs can't freely enter.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
The turrets could never shoot inside the ship, it only does that because it fires a burst of 3 shots that trace you through walls

**Comment by MarkusLarsson421** [comment]
Try it. The lavaland turrets on the syndicate outpost also shoot inwards.

**Comment by MarkusLarsson421** [comment]
ready

**Comment by MarkusLarsson421** [comment]
> The turrets could never shoot inside the ship, it only does that because it fires a burst of 3 shots that trace you through walls

Odd, I can't replicate it anymore. Must've been fixed. I specifically remembered these turrets digging through the walls of the syndicate outpost by shooting inwards. But I guess not. 

image

**Pull request closed without merging**
