### PR TITLE
Removes the ability to make romerol in virology

### PR DESCRIPTION
**Pull request by Rukofamicom**
## About The Pull Request
Removes the hidden and undocumented effects of Autophagocytosis Necrosis. Specifically it removes the ability for non-uplink antags to trigger zombie outbreaks. 

## Why It's Good For The Game
This was previously "balanced" by being relatively unknown, but this has gradually become less and less true. 

Overpowered features kept secret for the sake of balance so that only those who wrote the code, code dive, or are told about it by one of the prior two types of people is garbage design. 

## Testing Photographs and Procedure

<details>

Var editted for quicker testing. Virus behaves as you would expect. 
image

image

</details>

## Changelog
:cl:
del: Removed undocumented and very powerful effect from viral symptom Autophagocytosis Necrosis. 
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — DISMISSED** [review]
This is really stupid now that I think about it, why did we even let this in

**Comment by Rukofamicom** [comment]
Technically we didn't. It's actually been in for longer than Bee has existed.

image

This is the PR that added it.

**Comment by Rukofamicom** [comment]
(also I was wrong, one small bit wasn't working as intended but I checked it right after the PR was made when I remembered to. Severity wasn't updating for some reason)

**Comment by PowerfulBacon** [comment]
Zesko 100% added this

**Comment by EvilDragonfiend** [comment]
zesko didn't add this. they only added the symptom name.

**Comment by EvilDragonfiend** [comment]
> Zesko 100% added this



https://github.com/EvilDragonfiend/BeeStation-Hornet-Evildragon/commit/1247d1292022168ff8f4092a3de4ce2d2b3c6008

it appears so

**Comment by Rukofamicom** [comment]
Okay, so coder in 2017 tried and failed to add it and Zesko finished it. That's kinda funny lmao.

**Comment by RDS88-beeman** [comment]
The best part is
> This was previously "balanced" by being relatively unknown, but this has gradually become less and less true.

**This was on the wiki for most of its history**
On previous versions of the viro wiki, you could mouse over some symptoms to get extra notes on them, and lo and behold:
image

**Comment by Rukofamicom** [comment]
It was still somewhat hidden because most the information about virus thresholds belongs in the far right column.

**Comment by zeskorion** [comment]
i'd been intending forever to make the zombies not transmissible. dont care much, tho viro transmission is currently mostly balanced by rules :/

**Review by ike709 — APPROVED** [review]

**Pull request merged**
