### PR TITLE
adds the mothroach

### PR DESCRIPTION
**Pull request by Miliviu**
## About The Pull Request

Ports https://github.com/tgstation/tgstation/pull/68763
Adding the Mothroaches!
## Why It's Good For The Game
Having a new Neutral animal can't hurt, and they are REALLY cute

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image
In this image you can see that I have tested moving them, killing them, crafting a moth plushie and putting them on the head and hands!

</details>

## Changelog
:cl: ValuedEmployee Justice12354
add: Added Mothroaches
/:cl:

### CODE REVIEW

**Comment by Justice12354** [comment]
I might still add 1 or 2 more features, such as the patting boost thing, so don't merge this yet, if you want the full deal

**Comment by Fronsis** [comment]
I see moth agenda being pushed i give thumbs up

One step closer to the port of *chitters

**Comment by Crossedfall** [comment]
Don't use hyperlinks in the changelog, please. It'll cause problems with the parser

**Comment by Miliviu** [comment]
> I might still add 1 or 2 more features, such as the patting boost thing, so don't merge this yet, if you want the full deal

Awesome, thanks! I'll wait then!

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
