### PR TITLE
ports removal of crossed() and uncrossed(), also checkexit()

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

ports

- tgstation/tgstation#58188
- tgstation/tgstation#58340
- tgstation/tgstation#59299
- tgstation/tgstation#59223
- tgstation/tgstation#59200
- tgstation/tgstation#59199
- tgstation/tgstation#59196
- tgstation/tgstation#59065
- tgstation/tgstation#58945
- tgstation/tgstation#58507
- tgstation/tgstation#58276
- tgstation/tgstation#58269
- tgstation/tgstation#59658
- tgstation/tgstation#59608
- tgstation/tgstation#59010
- tgstation/tgstation#59185
- tgstation/tgstation#59154
- tgstation/tgstation#59432
- tgstation/tgstation#57773
- tgstation/tgstation#59303
- tgstation/tgstation#59919
- tgstation/tgstation#60026
- tgstation/tgstation#59894
- tgstation/tgstation#60678

and other supporting prs

## Why It's Good For The Game

lots of overhead calling snapped out of existence
it's not fucking broken anymore

## Changelog
:cl: kylerace, ninjanomnom, mothblocks, jupyterkat, lemoninthedark, rohesie, wayland-smithy
refactor: make things faster in general
code: improves components code
/:cl:

### CODE REVIEW

**Comment by super12pl** [comment]
Can't believe they removed crossed

**Comment by Archanial** [comment]
Based

**Comment by KubeRoot** [comment]
Fun fact: If you put the PRs in a list, like this:

- tgstation/tgstation#58188

It looks f a n c y and displays the PR title inline

**Comment by jupyterkat** [comment]
> Fun fact: If you put the PRs in a list, like this:
> 
> * [Remove Uncross() and CheckExit(), add connect_loc element to cover the cases we used it for tgstation/tgstation#58188](https://github.com/tgstation/tgstation/pull/58188)
> 
> It looks f a n c y and displays the PR title inline

no

**Pull request closed without merging**
