### PR TITLE
YADCB & Forensic Chemistry

### PR DESCRIPTION
**Pull request by DatBoiTim**
# Yet Another Detective Choice Beacon & Forensic Chemistry

## About The Pull Request
Adds a detective choice beacon.
Also Adds Forensic Chemistry, to play into a detective kit.
Some mission-critical components remain accessible. This is most importantly the forensic scanner.

#### The Detective We Know and Love
Sunglasses with No Sechud
He got his regular looking revolver as usual
All the equipment for alcoholism and tobacco addiction
Chalk for ~~writing obscene messages~~ corpse outlines
Binoculars

#### The Detective we know and love but grey
See above but grey

#### Forensic Chemistry and Autopsies
Sunglasses with Medhud
Basic Surgical Tools for autopsies
Basic Medanalyzer for autopsies and forensic medicine
Bodybag for obvious reasons
Scrubs, gloves, white shoes
Labcoat

#### Professional Intervention
Sunglasses no sechud (Ideally also the **YEAHHHHHHH** thing whenever equipped, but copyright : / )
CSI Uniform
CSI Jacket
Latex Gloves(Whichever medical ones are white)
Belt Holster (goes in belt slot)
Slock Special(Space Glock, uses mags that aren't printable, otherwise holds identical ammo and same amount per load)
No alcoholism/tobacco
Yellow chalk instead of chalk
Binoculars

#### Who the fuck are you?
Sechud Sunglasses to help track and update sec records of your "accomplices"
Voice changer
A generic headset
ID, PDA, Outfit not included

#### ~~The meme choice~~
~~No other equipment, you get a a revolver reskin that has a massive fuck off sprite. Named "The Biggest Iron".~~

## Forensic Chemistry
Reagents Metabolize into Metabolites, Metabolites are slow metabolizing, harmless reagents. Many reagents may share the same metabolites but with different ratios.
Basic Health Scanners Read the Metabolites, Advanced Read the Reagents.
Creates 2 different reagent containers in beings, so that there isn't any interference, 1 should only take metabolites.

## To Do

- [x] Noir Kit
- [x] Grey Noir Kit
- [x] Coroner Kit
- [ ] CSI Kit
- [ ] CSI Sprites
- [ ] CSI Belt Holster
- [ ] Slock Special and "Magazines"
- [ ] Deep Cover Kit
- [ ] Yellow Chalk
- [ ] Voicechanger
- [ ] Reagent to Metabolite
- [ ] Metabolite Container for Carbons
- [ ] Method to Scan metabolites with basic medanalyzer
- [ ] Metabolites themselves
- [ ] Wiki Updates

## Why It's Good For The Game

I think offering some options for detectives to play differently or have neat roleplay options will be good for depth.
Additionally, forensic chemistry is a neat addition of depth for medical systems without making it completely esoteric.

Additionally, I think choice beacons are a good way to offer "loadouts" for jobs that have a handful of ways that job can be carried out, in addition to their current function.

## Changelog
:cl: DatBoiTim
add: Detective Choice Beacon Put in Inventory Roundstart
add: Noir kit to DCB
add: Grey Noir kit to DCB
add: Coroner kit to DCB
add: CSI kit to DCB
add: Forensic Chemistry
add: Basic Medical Analyzers have a Reagent Mode that looks at metabolites
add: Slock Special, Mags, and Holster
add: A reskin of Detective Revolver, named The Big Iron
del: Some Gear and Clothing From Det Wardrobe Now Available through DCB
imageadd: CSI Outfit Sprites
imageadd: Slock Special and Related
imageadd: The Big Iron
code: Metabolite Container for Carbons
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
They should just have all the scanning equipment and uniforms in a vendor for choice rather than on a beacon

**Comment by DatBoiTim** [comment]
> They should just have all the scanning equipment and uniforms in a vendor for choice rather than on a beacon

The scanner is staying in the wardrobe/vendor along with other mission-critical items.

Specifically this includes the forensic scanner, baton, as well as other items I've yet to review.

**Comment by bloons3** [comment]
> Sechud Sunglasses to help track and update sec records of your "accomplices"

Only chameleon clothing can look like something it isn't (and chameleon clothing is cheap plastic that has no abilities).

Knowing that someone else is wearing SecHUDs is very useful for you in case you suspect that you've been set to wanted.

**Comment by DatBoiTim** [comment]
> Only chameleon clothing can look like something it isn't (and chameleon clothing is cheap plastic that has no abilities).
> 
> 
> 
> Knowing that someone else is wearing SecHUDs is very useful for you in case you suspect that you've been set to wanted.

These are gonna be the real deal though, and you can easily obscure them so they won't be known if you're wearing them or not

**Comment by yyzsong** [comment]
Can we get a cowboy variant with a bigger iron

**Comment by DatBoiTim** [comment]
> Can we get a cowboy variant with a bigger iron

Fuck it why not. No other equipment but you get a silly revolver reskin

**Comment by DatBoiTim** [comment]
Worth noting the slock specials "mags" are also reskins of the speedloaders

**Comment by Raven-Industries** [comment]
The Coroner option sounds cool, especially if there is some improvement to forensics to accompany it, but I will note that unless things have changed recently, some maps come with an autopsy area attached to the detective's office already. It does seem like it would be more ideal as an addition to more maps rather than as a sort of character class. 

While we're on the topic of forensics, perhaps some sort of explosives analysis character type would be interesting. That may be difficult to implement in practice, be it some sort of 'explosive device fragments' being left behind/imbedded in walls or maybe a 'explosive chemical residue', but some sort of forensics analysis for bombings other than 'hmm, yes, this hole in the station was not here before' would be nice.

**Comment by DatBoiTim** [comment]
> forrensics to accompany it, but I will note that unless things have changed recently, some maps come with an autopsy area attached to the detective's office already.

Forensic Chemistry is being added in this PR. Detective Scanner can also scan reagents as well. The autopsy area is what actually inspired the coroner choice.

**Comment by DatBoiTim** [comment]
332825a is Merge Conflict Resolution

**Comment by DatBoiTim** [comment]
Closing since I have other priorities, will reopen later with more progress.

**Comment by PowerfulBacon** [comment]
forensics is cool but I think its enough without the detective kits

**Comment by DatBoiTim** [comment]
> forensics is cool but I think its enough without the detective kits

Well idea is we push detective closer to a gimmicky role without removing too much.

**Comment by TeomanTheGreat** [comment]
tragedy.

**Comment by TeomanTheGreat** [comment]
nice

**Comment by Tsar-Salat** [comment]
based, even

**Pull request closed without merging**
