### PR TITLE
Azlan's Radsuit/Hazard Vest Sprite Update

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Adds Azlan's new sprites for both the radsuit and the hazard vest.

## Why It's Good For The Game
The radsuit and hazard vest look better.

## Changelog
:cl:
imageadd: Azlan's new sprites for radsuit and hazard vest
/:cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
Can you post some screenshots of characters wearing the new suits in your description?

Also, looks like you have a merge conflict.

**Comment by MarkSuckerberg** [comment]
Err, I'll look into it. The confilict was likely due to Deb fixing the plasmaman helmets, and here's a screenshot I was given a while ago by Azlan: 
unknown
(Again, these aren't my sprites, I was just asked to PR them)

**Comment by qwertyquerty** [comment]
Fix icon conflicts (you can do this easily if you have their icon merger hook installed, just merge master into azlanfixes)

**Comment by MarkSuckerberg** [comment]
oy, forgot to do that

**Comment by MarkSuckerberg** [comment]
Fixed, hopefully

**Pull request merged**
