### PR TITLE
[PORT] Mafia, a minigame for ghosts to sign up for while dead

### PR DESCRIPTION
**Pull request by Moccha-Bee**
## About The Pull Request
thanks to anturk for the base of all of this, i just polished things up for the ball and again for master
it's town of salem, it's werewolf, it's mafia. you got people in a funny little town trying to find out who is killing people every night using special town powers.

uh... what else... i moved the joining system off of the signups and onto a ghost button to join the game, and when enough people are in it starts. people who disconnect or rejoin the game while signed up are removed from the list when it thinks there are enough players (but not enough valid players)
## Last Thing:
Reason why I put it up earlier than I'd normally like to is because any reviews to improve the code off of rushed-summer-ball-hoohah is super appreciated

## Why It's Good For The Game
approved by oranges, mafia is a really fun and based minigame, and now we have something more than just CTF. lot of potential to work off of here and anturk's amazing work making this possible should be realized

## Changelog
🆑 Anturk + Arm + other summer ball contributors code, trollbreeder + fikou + jerryderpington mapping
add: Mafia minigame added for ghosts
/🆑

### CODE REVIEW

**Comment by Moccha-Bee** [comment]
needs some testing couldn't get it to run on my private server because not enough players

**Comment by Moccha-Bee** [comment]
man i don't know how tgui's even work

**Comment by AnjelicaChaykovsky** [comment]
why its called mafia

**Comment by Moccha-Bee** [comment]
> why its called mafia

Who knows, it basically works like salem town.

**Comment by ike709** [comment]
Does this include the 3 or 4 follow-up PRs?

**Comment by Moccha-Bee** [comment]
> Does this include the 3 or 4 follow-up PRs?

I will do them seperatly.

**Review by super12pl — APPROVED** [review]

**Comment by TeomanTheGreat** [comment]
Is this ded?

**Pull request closed without merging**
