### PR TITLE
Forensic scanners can no longer be printed

### PR DESCRIPTION
**Pull request by Wilchenx**
## About The Pull Request

Removes the forensic scanner from techwebs

## Why It's Good For The Game

This long overdue change makes the unique detective's toy actually unique

## Changelog
:cl:
balance: forensic scanner is no longer printable in techfabs
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
I reccomend making the tool indestructible incase it gets destroyed making the detective even more useless

**Comment by Wilchenx** [comment]
> I reccomend making the tool indestructible incase it gets destroyed making the detective even more useless

No

**Comment by AnCopper** [comment]
Make it orderable from cargo for an obscene price so there is at least some way to recover it.

**Comment by Wilchenx** [comment]
> Make it orderable from cargo for an obscene price so there is at least some way to recover it.

I like the idea of antags being able to GET RID OF IT more.

**Comment by Fronsis** [comment]
I think i would be happy with a forensic scanner + a spare (in case the det cryo's or random stuff) since it makes sense to have at least 2 while also giving antags a possibility to not get tracked by prints 

Unless we go the route Chaplain and Curator are atm in which they arrive with one, alternative the forensic scanner should be marked as one of those items that can be retrieved from cryostorage

**Comment by Wilchenx** [comment]
>I think i would be happy with a forensic scanner + a spare

That's really funny cause it shows that you never played the role
Detective spawns with a scanner and there's a spare in the locker.
If a new detective comes onto the station he already has the scanner.

image
30 seconds of codediving btw

**Comment by Fronsis** [comment]
> > I think i would be happy with a forensic scanner + a spare
> 
> That's really funny cause it shows that you never played the role Detective spawns with a scanner and there's a spare in the locker. If a new detective comes onto the station he already has the scanner.
> 
> image 30 seconds of codediving btw

Oh you're correct, for some reason i forgot about the spare one in the locker and thanks for using 30 seconds to codedive, since i haven't looked into that, i thought for sure new Detectives didn't arrive with one, still leaving that aside making the scanner to show as a retrievable object from cryo would be a nice thing to have for emergencies.

Being away from the forums does wonders on you Wilchen!

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Fix CL.
Indicate this affects balance.

**Comment by Sapfearon** [comment]
so if detective locker is stolen/exploded and det lost his scanner you out of job? amazing. Currently det whole job is using this scanner - making it irreplaceable is bad.

**Comment by Wilchenx** [comment]
> so if detective locker is stolen/exploded and det lost his scanner you out of job? amazing. Currently det whole job is using this scanner - making it irreplaceable is bad.

Congratulations you can't read

**Review by PowerfulBacon — APPROVED** [review]

**Review by PowerfulBacon — DISMISSED** [review]
Fix CL (Also, please try to avoid being aggressive/insultive in the comments, it adds nothing to the discussion and derails conversations quickly)

**Review by Archanial — APPROVED** [review]

**Pull request merged**
