### PR TITLE
Optional, customisable inventory outline

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Outlines items in your inventory when you hover over them.
Includes options for toggling on and off and changing the colour.

Makes sure the object is only outlined when it should be, so checks for dragging and storage interactions are included, and from testing, it has been robust so far.

Additionally, the effect applies when you hover over the item, or when you hover over the inventory slot.
Especially for smaller items, this provides a lot of visual feedback and makes the game generally more accessable (Not that that is a huge focus of SS13).

## Why It's Good For The Game

Makes it look more modern and provides a nice effect.

image
image
image
image
image
image

(I have 2 videos that I can supply in discord)

## Changelog
:cl:
add: Optional and customisable outlining on inventory items.
fix: Fixes a bug with storages on the ground not removing IN_STORAGE flag from items taken out of them.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
This probably needs a testmerge, since there might be obscure ways to remove items from inventories that I haven't thought about

**Comment by PowerfulBacon** [comment]
- [x] Items that spawn in an inventory dont have the IN_INVENTORY flag

- [x] Taking something out of a backpack on the floor does not remove the IN_STORAGE flag

**Comment by PowerfulBacon** [comment]
Ok I can't seem to break it anymore, I think it's ready

**Comment by ike709** [comment]
This is pretty nice. You should consider making it apply to everything if you can get it to only show for the player mousing over it.

**Review by ike709 — APPROVED** [review]

**Pull request merged**
