### PR TITLE
you can no longer put food in iv drips (1984)

### PR DESCRIPTION
**Pull request by Therealdoooc213**
## About The Pull Request

you can no longer put food in iv drips

i don't consider this a bug fix because there was a code comment on it

## Why It's Good For The Game

it causes runtime errors and makes zero sense as to why i can put a cake into a IV drip

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

https://github.com/user-attachments/assets/5811dcf9-c11b-480c-a677-2bfd4c61f369

</details>

## Changelog
:cl:
tweak: you can no longer put food in iv drips
/:cl:

### CODE REVIEW

**Comment by Therealdoooc213** [comment]
Fail echo checks and im closing this PR

**Comment by Therealdoooc213** [comment]
image

**Comment by Dejaku51** [comment]
just fix the runtiime.

**Comment by Therealdoooc213** [comment]
> just fix the runtiime.

The  runtime isnt the only issue??? it makes no sense for people to put fucking cakes inside of IV drips

**Comment by Tsar-Salat** [comment]
wall-e-wall-e

If I cant have my diabetes then whats the point

**Comment by Therealdoooc213** [comment]
This is why we shouldn't have hired (kidnapped) new maintainers

**Comment by DrDuckedGoose** [comment]
image

**Pull request closed without merging**
