### PR TITLE
Bananium tree

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
* Adds bananium tree

## Why It's Good For The Game
Kat's request
```
Kat:
- an easier way to get bananium
- removing bananium from air horn recipe
- removing air horn from cake recipe

it makes my gimmicks impossible since theres no fucking way to get bananium
Bananium (you will never get it because explos, miners, and xenobio are all useless pieces of shit who would rather powergame) 
```
I won't touch other stuff. Only adding bananium tree.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image
image
image
image
image

</details>

## Changelog
:cl:
add: Added bananium tree
/:cl:

### CODE REVIEW

**Comment by bluezorua** [comment]
the point of bananium is that it is rare

**Comment by EvilDragonfiend** [comment]
I can make it less common from harvesting those... like the maximum 2 ores per harvest.

**Comment by EvilDragonfiend** [comment]
> Do you have wiki changes ready?

You don't have to notice that to me

**Comment by Rukofamicom** [comment]
> the point of bananium is that it is rare

This is where I sit. Bananium and everything made from it should be rare occurrences so they aren't gimmicks that get done into the ground.

**Comment by itsmeow** [comment]
Unfortunately the solution here is probably removing air horn from the tall/popout cake recipe

**Comment by ike709** [comment]
🔑 Bananium is intentionally rare.

**Comment by EvilDragonfiend** [comment]
> Unfortunately the solution here is probably removing air horn from the tall/popout cake recipe

image

I am offended

**Comment by itsmeow** [comment]
I was not aware of the anti-bananium community at the time of writing

**Comment by PowerfulBacon** [comment]
Even though its an issue with bananium crafted items and not necessarilly bananium itself, bananium is intentionally rare because of how stupidly annoying the items made with it are. Making them any more accessible will probably just drive people to insanity enough to just outright remove bananium and all the stupid things you can make with it

**Pull request closed without merging**
