### PR TITLE
Removes effect from splashing Synthflesh, Silver Sulfazadine and Styptic Powder

### PR DESCRIPTION
**Pull request by Isy232**
## About The Pull Request

All this does is remove the effects of splashing synthflesh, sliver sulfazadine and styptic powder.
Patches of these chems are unchanged.

Also removes styptic powder, silver sulfazadine and synthflesh medsprays and instead adds more patches of these chems.

## Why It's Good For The Game

A beaker of synthflesh can be applied instantly for a total of 125 brute and burn healing mid combat. This is kinda bullshit.
You can also just negate the OD effects of styptic powder and silver sulfazadine by splashing bottles of them.

Now you must apply patches of these chems to have any effect. Splashing them won't do anything.

Now you must actually consider using chems other than styptic powder and silver sulfazarine for all brute and burn damage.

Some of you may believe that synthflesh and styptic powder should be nerfed harder, I kinda agree with you but these PR's are extremely controversial so best to atomize.

I personally disagree with #2501 so I made this one to give another option, this one also does not involve reverting #2411

## Changelog
:cl:
balance: Splashing styptic powder, synthflesh and silver sulfazadine now does nothing, use patches instead.
/:cl:

### CODE REVIEW

**Comment by Naevii** [comment]
Spraying will still work? If not it entirely removed medical sprays from usage

**Comment by Isy232** [comment]
> Spraying will still work? If not it entirely removed medical sprays from usage

... shit, didn't think about that

**Comment by Isy232** [comment]
Alright, dealt with that, sprays are no longer found in medical but I have added additional patches to replace them.

**Comment by Naevii** [comment]
Don't think additional patches will be good exchange for sprays. You need like 5 patches to compansate for one spray you had in your inventory

**Comment by Sinmero** [comment]
> Don't think additional patches will be good exchange for sprays. You need like 5 patches to compansate for one spray you had in your inventory

you can put patches in a pill bottle to save space

**Comment by Bestparty** [comment]
Improve dont remove, leave sprays be ffs nerfing chems is enough

**Comment by ghost** [comment]
> Improve dont remove, leave sprays be ffs nerfing chems is enough

this is improving.

**Comment by Isy232** [comment]
> Improve dont remove, leave sprays be ffs nerfing chems is enough

I can leave sprays but they will just be useless

**Comment by Isy232** [comment]
> Don't think additional patches will be good exchange for sprays. You need like 5 patches to compansate for one spray you had in your inventory

Sprays have 60u of chems in them, patches have like 20 or 30, so its not a horrible decrease.

**Comment by Isy232** [comment]
The goal of this PR is to put a more moderate opinion out there, instead of just one that says pretty much make synthflesh useless.

**Comment by Blueturbo47** [comment]
More patches does not equal sprays, if 5patches = 1 spray 5 patches takes way longer to apply then 1 spray. And sprays are very useful to miners who are mid battle and need meds.

**Comment by Blueturbo47** [comment]
And you didn't remove them from miner pods

**Comment by Isy232** [comment]
> More patches does not equal sprays, if 5patches = 1 spray 5 patches takes way longer to apply then 1 spray. And sprays are very useful to miners who are mid battle and need meds.

This PR only exists as a far more logical nerf than #2501 and honestly I don't mean to push it too hard, just suggest what we should nerf instead of making synthflesh useless.

I'm quite apathetic to which side wins, I personally use splashing beakers to my advantage quite commonly.

**Comment by Chessus** [comment]
I'd be down for it if you could add a  touch_protection/get_permeability_protection() modifer for them. That modify's the amount it heals based on the protection the person is wearing I believe. I've never personally seen anyone heal using those basic chems with splash. 

It's found here https://bit.ly/35X9WUy . Also here https://bit.ly/3mItt1c, the 2nd explains the fucntion as it was added. Also here shorturl.at/ioCT5
```
if(method == VAPOR) //smoke, foam, spray
   if(M.reagents)
     var/modifier = CLAMP((1 - touch_protection), 0, 1)
     var/amount = round(reac_volume*modifier, 0.1)
   if(amount >= 0.5)
    M.reagents.add_reagent(type, amount)
```

**Pull request closed without merging**
