### PR TITLE
Adds a room for Singularity/Tesla to MetaStation

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request

New room east of the SM with space for Tesla/Singularity, like Delta

## Why It's Good For The Game

Right now trying to make Singularity or Tesla in any station but Delta results in spending most of the round making the space for it and getting all the parts from Cargo, which is pretty lame if I say so myself. This PR is (hopefully) the first to give all of the rest of the  maps to receive an extra engine room.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

imagen
imagen
imagen

</details>

## Changelog
:cl:
add: An engine room to MetaStation with basic equipment for Singularity Tesla
add: Tesla, the Space Cat. Don't forget to move him before starting the tesla/singularity!
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
It is sticking out like a very, very sore thumb! Is this the least obstructive implementation possible?

**Comment by Nakalon** [comment]
> It is sticking out like a very, very sore thumb! Is this the least obstructive implementation possible?

It makes sense design wise you'd keep the very dangerous power source far away from other things.

I also like the cat.

**Comment by MarkusLarsson421** [comment]
> It makes sense design wise you'd keep the very dangerous power source far away from other things.

It looks ugly with how much it is sticking out. Plus, I don't think it is a good justification for having power sources far away from the station? If not, then why isn't the SM extruded out further in space than what it already is? You could definitely make a super safe SM, which might just be a 5x5 room with a ton of space around it.

**Comment by itsmeow** [comment]
Frozen by genpop

**Comment by Nakalon** [comment]
> > It makes sense design wise you'd keep the very dangerous power source far away from other things.
> 
> It looks ugly with how much it is sticking out. Plus, I don't think it is a good justification for having power sources far away from the station? If not, then why isn't the SM extruded out further in space than what it already is? You could definitely make a super safe SM, which might just be a 5x5 room with a ton of space around it.

Markus, you can see clearly the idea is having it in space, varo did this on purpose I assume. It even has a space cat.

**Comment by JixS4v** [comment]
🔑

**Comment by ClownMoff** [comment]
https://www.cope.es/

**Comment by CydiaLamiales** [comment]
image
Space cooling loop is missing a part and isn't functional.

**Comment by Tsar-Salat** [comment]
> add: An engine room to MetaStation with basic equipment for Singularity Tesla
> add: Tesla, the Space Cat. Don't forget to move him before starting the tesla/singularity!

CL tags just change the symbol used, which can be confusing for non-coders looking at the changelog. It will look like:
```
An engine room to MetaStation with basic equipment for Singularity Tesla
Tesla, the Space Cat. Don't forget to move him before starting the tesla/singularity!
```

This looks like an incomplete sentence without the prefix, make sure it communicates what you did. Recommend something like:
```
add: Expands engine room on MetaStation with basic equipment for Singularity Tesla
add: Gives Engineering a new pet, Tesla, the Space Cat. Don't forget to move him before starting the tesla/singularity!
```

I've seen this in multiple of your PRs lately, and it makes the Changelog ingame look very strange. If you could start applying this going forward, it would be appreciated.

**Comment by ClownMoff** [comment]
Okayyy

**Pull request closed without merging**
