### PR TITLE
Convert erroneous uses of `useSharedState` to `useLocalState`

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

This converts erroneous uses of `useSharedState` in tgui to `useLocalState`.

`useCombinedState` will dynamically use either local state or shared state, based on whether the user is an observer or not.

## Why It's Good For The Game

Lets ghosts can see more stuff, plus slightly reduces load on the server.

23-06-12-1686628480-Discord

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/65794972/df66d9eb-d0a1-48ec-a454-adae6033c84a

</details>

## Changelog
:cl:
fix: Converted some erroneous use of shared state in tgui to local state. As a result, ghosts can now look at the bounty board on newscasters, and flick between tabs in several UIs, such as the operating computer.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Note that this changes all of these UIs to be separate for every person looking at them (Currently cargo console is the same for all viewers)

**Review by EvilDragonfiend — CHANGES_REQUESTED** [review]
My no list:
* Cargo console: I like people being interrupted
* Robotics console: absolutely no. I prefer to leave this as evidence that someone touched the console by looking its interface.

otherwise, I am fine with others.

**Comment by Absolucy** [comment]
@EvilDragonfiend Alright, reverted those two.

**Review by EvilDragonfiend — APPROVED** [review]
I guess it's okay

**Pull request merged**
