### PR TITLE
Reverts 6893 "easy disarm stun bad"

### PR DESCRIPTION
**Pull request by Wilchenx**
## About The Pull Request

A very controversional PR was merged without a proper community vote, this is a PR to revert it.

## Why It's Good For The Game

I don't think a PR like this should've passed without a community vote. A lot of people are unhappy with it.

It was said that the changes would "improve RP" but I've seen no genuine evidence of that happening.

</details>

## Changelog
:cl:
balance: shove changes were reverted
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
You make it out like the PR was yolomerged and wasn't on testmerge for multiple days before being merged.
The reason for merging wasn't to 'improve RP', we are well aware that this isn't going to change anything related to RP. The thing this PR prevents is less robust players that haven't quite learnt position yet from being taken down in 1 shove by someone who is more robust. It is still possible to overpower an attacker, however is a lot more difficult as you need to get a wallshove on them, and then another shove afterwards (although once you get the initial shove isn't too hard).

Tried a poll in game, however the majority of players haven't actually got to use it in combat. I would like the opinions of players who have been on both the recieving end and giving end of this change, as the majority of players still haven't had the chance to use it yet. (Also for this reason, this will not be merged for a good amount of time).

image

The feedback I would be looking for in order to make a decision about reverting this is something along the lines of:
```
Since the changes:
Have you had wallshoves used against you?
How did the combat change as a result of the changes in this scenario?
Have you used wallshoves against someone else?
How did the combat change as a result of the changes in this scenario?
What are you overall opinions on the changes, what do you dislike about the new changes over the old ones?
```

**Comment by Wilchenx** [comment]
>The thing this PR prevents is less robust players that haven't quite learnt position yet from being taken down in 1 shove by someone who is more robust.

Removing the learning curve doesn't make the game interesting, it just takes away from it.
If we went around with the same mindset and simplified other aspects of the game it would quickly make the game boring.

>It is still possible to overpower an attacker, however is a lot more difficult as you need to get a wallshove on them, and then another shove afterwards (although once you get the initial shove isn't too hard).

That's not true.
Its impossible to overpower an attacker with shoves
Its impossible to use shoves defensivesly too because of the long cooldown
The pr made shoves very weak

>The feedback I would be looking for in order to make a decision

You should make a server poll.
Or maybe a PR vote?

**Comment by mcmeiler** [comment]
> I would like the opinions of players who have been on both the recieving end and giving end of this change

I've been on both ends of this.

## The receiving end
NOTE: I am saying this out of the perspective of a security officer, as they were most affected by this

I can describe these changes in a few, simple words, which can be understood by a majority of the playerbase:
"lol why are you shoving lmao"

**It's completely and utterly pointless to shove in combat for a few reasons:**

* The knockdown is irrelevant now, as the stun component is gone, and you can still attack them just the same as before.
* The disarm component is completely irrelevant, as the disarm action cooldown is vastly longer than it takes you to pick up your item again.
* You're still fast enough to somewhat chase an injured opponent after they knock you down, making the "hit and run" argument irrelevant to me.

In conclusion here, *this completely trivializes combat for security while taking all risk from fighting antagonists.* There is absolutely _zero_ risk to having your weapons out at all times, ready to blast whoever enters your field of view.

## The giving end
NOTE: I am saying this out of the perspective of an antag as they are the other side affected by this change.

The rage I feel when uttering the words here is indescribable in English vocabulary. Once again, here are simple words to summarize the changes:
"why even bother doing anything loud, you're fucked in combat either way lol"

And here's why:

* No stun component makes ambushes impossible without explosives.
* Melee weapons are completely non-viable against any other melee opponent, as combat is now reduced to "who can spamclick the other the fastest", due to positioning being 100% irrelevant, and disarming being actively worse than attacking.
* Security is completely impossible to fight, without exception. *Even with antagonist equipment.* You have an esword? Too bad, the baton/shotgun/disabler/bola still kills you faster (Note, with "kill" in this case, I refer to stamcrit, as it's essentially the same thing as dying as an antag.)

Some people will just say "get anti stuns then" - Which is a fair argument -- *IF* you haven't played here in the last few weeks.
Security will, and I mean *will* grab armory equipment at first sign of antagonist activity, no matter how tiny, even an unimportant B&E, including lethals, which they will immediately magdump you with as soon as you pop your anti-stun implements.

In conclusion here, this change *forces* every antagonist to fully stealth their objective and avoid combat and detection at all costs as there is no meaningful way to win against security any longer. Antagonists doing their objectives and nothing else is not only extremely boring, it also creates no interesting situations for any department members that may have been affected by the antagonist.

**Comment by PowerfulBacon** [comment]
> That's not true.

Shoving someone on the ground does cause them to drop their items, meaning 2 shoves will cause them to lose their items.

I am happy to remove the cooldown and add a shorter stun to shoving while on the ground (like 2 seconds at most), but this isn't being reverted as a whole at least for some time.

image

**Comment by Wilchenx** [comment]
>meaning 2 shoves will cause them to lose their items.

You have a cooldown delay and there's no stun meaning there's almost a 2 second window for someone to just pick the items back up.

Unnerfing the cooldown and reducing the paralyze to 2 (from 4) is a reasonable nerf to shoves.

**Comment by Rukofamicom** [comment]
> You have a cooldown delay and there's no stun meaning there's almost a 2 second window for someone to just pick the items back up.

There is a 0.8 - 1.6 second window, minus that player's ping. 
Completely removing the 0.8 second cooldown increase more or less guarantees the disarm will always be successful. 

Wallshoving a player should not reliably decide the outcome of combat by itself. It should have a minor impact on combat at best because it's an ability that is available to everyone at all times regardless of their preparedness for combat. A knockdown with potential for disarm is an appropriate minor effect, and one that can primarily be used defensively instead of offensively.

**Comment by Wilchenx** [comment]
> > You have a cooldown delay and there's no stun meaning there's almost a 2 second window for someone to just pick the items back up.
> 
> There is a 0.8 - 1.6 second window, minus that player's ping. Completely removing the 0.8 second cooldown increase more or less guarantees the disarm will always be successful.

#define CLICK_CD_DISARM 16
Its a static 1.6s + ping and not 0.8s to 1.6s - ping

**Comment by PowerfulBacon** [comment]
> Unnerfing the cooldown and reducing the paralyze to 2 (from 4) is a reasonable nerf to shoves.

Open a PR with the specified changes and it will be considered.

**Comment by Wilchenx** [comment]
> > Unnerfing the cooldown and reducing the paralyze to 2 (from 4) is a reasonable nerf to shoves.
> 
> Open a PR with the specified changes and it will be considered.

Just changed one number in this pr lol

**Comment by Rukofamicom** [comment]
>  The knockdown is irrelevant now

@mcmeiler are you saying being slowed in combat is totally irrelevant? Because a knockdown slows by quite a lot. Being slowed means you can't evade attacks, run away or pursue someone.

> The disarm component is completely irrelevant, as the disarm action cooldown is vastly longer than it takes you to pick up your item again.

0.8 seconds is not vastly longer when you factor ping and reaction speed. Not everyone plays on good ping, and this window allows for the disarmed player a chance to pick their item up first so the disarm isn't guaranteed to succeed - only if the disarmed player fumbles picking it up, *which does still happen in my experience with shoving*.

> You're still fast enough to somewhat chase an injured opponent after they knock you down, making the "hit and run" argument irrelevant to me.

That's.. completely absurd to me to be frank. That said, I'm more than willing to compromise on this point, I believe there's a  proc that actually prevents movement without full paralysis which could be used instead of or in tandem with knockdown. Still much better than being stunned, and better accommodates this complaint without too much being lost. 

> No stun component makes ambushes impossible without explosives.

I can only see this as a good thing. Being killed without so much as a chance to respond to your attacker is not the way, I think this point could again be resolved by swapping or compounding the knockdown proc with one that prevents movement, but completely taking control away is dumb and shouldn't come back. 

> Melee weapons are completely non-viable against any other melee opponent, as combat is now reduced to "who can spamclick the other the fastest", due to positioning being 100% irrelevant, and disarming being actively worse than attacking.

This.. is already what melee felt like before except you would autowin/lose if a shove happened. I still find that getting a shove off gives me a substantial advantage because it's now 10x easier to click the person I'm fighting. *(it might be worth noting that I'm one of the higher ping players. Full speed running around combat is next to impossible for me. I often actively give up if I find I'm not able to get a shove off because getting a shove is the only possible way for my clicks to connect with someone as they're always in a different tile by the time my clicks register otherwise)*

> Security is completely impossible to fight, without exception. Even with antagonist equipment. You have an esword? Too bad, the baton/shotgun/disabler/bola still kills you faster

What you are asserting is that security was impossible to fight before unless you got a successful wall shove, something they could either completely negate by wearing a riot suit or greatly mitigate by being robust enough to avoid walls. If their gear is really so powerful that a shove is required to beat them, **then security's equipment is too strong period, and it has nothing to do with the shove PR.**

**Comment by PowerfulBacon** [comment]
> > > Unnerfing the cooldown and reducing the paralyze to 2 (from 4) is a reasonable nerf to shoves.
> > 
> > 
> > Open a PR with the specified changes and it will be considered.
> 
> Just changed one number in this pr lol

That's not the changes, these changes will still drop weapons on the first shove.
The diffs should be:
 - Just removal of the disarm cooldown timer
 - Adding of a stun line thats <=2 seconds

**Comment by mcmeiler** [comment]
> @mcmeiler are you saying being slowed in combat is totally irrelevant? Because a knockdown slows by quite a lot. Being slowed means you can't evade attacks, run away or pursue someone.

What you're describing is a stun. Which doesn't exist currently.

> 0.8 seconds is not vastly longer when you factor ping and reaction speed. Not everyone plays on good ping, and this window allows for the disarmed player a chance to pick their item up first so the disarm isn't guaranteed to succeed - only if the disarmed player fumbles picking it up, _which does still happen in my experience with shoving_.

Once again, `#define CLICK_CD_DISARM 16`

16 deciseconds = 1.6 seconds. I have no clue where you are pulling the 0.8 seconds from. 1.6 seconds is an absurdly long time in fast-paced combat, and well exceeds the reaction time most humans have, which averages around 500-700 *milliseconds*.

> That's.. completely absurd to me to be frank. That said, I'm more than willing to compromise on this point, I believe there's a proc that actually prevents movement without full paralysis which could be used instead of or in tandem with knockdown. Still much better than being stunned, and better accommodates this complaint without too much being lost.

Even if such a proc exists, it doesn't prevent the fact the person who was shoved over is still impossible to disarm.

> I can only see this as a good thing. Being killed without so much as a chance to respond to your attacker is not the way, I think this point could again be resolved by swapping or compounding the knockdown proc with one that prevents movement, but completely taking control away is dumb and shouldn't come back.

No. The stun should remain, period. What's the point of having a tactical "advantage" in combat when said tactical "advantage" yields no rewards in the slighest, but actually *worsens* your combat outcome?
By the way, when I first started playing, shove paralysis was ***6 seconds*** long, enough to cuff someone. Yet nobody complained about that.

> This.. is already what melee felt like before except you would autowin/lose if a shove happened. I still find that getting a shove off gives me a substantial advantage because it's now 10x easier to click the person I'm fighting. _(it might be worth noting that I'm one of the higher ping players. Full speed running around combat is next to impossible for me. I often actively give up if I find I'm not able to get a shove off because getting a shove is the only possible way for my clicks to connect with someone as they're always in a different tile by the time my clicks register otherwise)_

So you... Admit to shoves being a part of combat players rely on? Additionally, nothing in your PR makes players easier to click on, so I have no idea where you're pulling that from.

Either way, you make it seem like a shove is _**always**_ an instant win. It wasn't, *if you weren't prepared correctly.* If you had prepared for combat beforehand, it very well was an instant win, ***which you deserve for preparing.*** The risk of the whole thing? _Someone can do the exact same thing to you with enough preparation_. Your PR claimed its purpose is to encourage players to prepare for combat instead of running in unarmed. Yet, preparation is completely and utterly useless as a result, and has turned combat into a mindless slog of clicks on harm intent, *as disarming actively puts you at a disadvantage,* until one person goes horizontal.

> What you are asserting is that security was impossible to fight before unless you got a successful wall shove, something they could either completely negate by wearing a riot suit or greatly mitigate by being robust enough to avoid walls. If their gear is really so powerful that a shove is required to beat them, **then security's equipment is too strong period, and it has nothing to do with the shove PR.**

Which is what I plan to do during my trip. If I can't create PRs remotely, I'll bulk create them when I get back. I'll have more than enough time to code changes and possibly even balance test them, as I won't be alone there.

**Comment by DerpiestBruh** [comment]
based

**Comment by Rukofamicom** [comment]
> That's not the changes, these changes will still drop weapons on the first shove. The diffs should be:
> 
> * Just removal of the disarm cooldown timer
> * Adding of a stun line thats <=2 seconds

#6969 (nice)

A stun that lasts long enough to get an attack off will just result in the same issue as old wallshoves. 
stun -> attack -> stun -> attack 

I made a PR going as far in this direction as I think it should, and also addressed hit and run apparently not being viable.

**Comment by Rukofamicom** [comment]
> So you... Admit to shoves being a part of combat players rely on? 

What the fuck? Yes, I *never* said it wasn't.  

Not only was it relied upon, it was damn near the only thing that has ever mattered in our combat. It mattered more than guns, more than energy swords, more than any amount of preparation or **actual** skill at aiming or otherwise. Combat revolved almost 100% around your ability to not stand next to a wall when 70% of available space is next to a wall. Almost nothing else about combat mattered because getting shoved meant you lost your weapon, had it used against you and ultimately lost entirely before the stun ended because a four second stun is enough time to be hit **FIVE times** before you can get up. Even a god damn toolbox or the welder inside (75 damage in five hits) is strong enough to decide a fight with a 4 second stun. The only time I've ever seen a successful wallshove not result in an immediate death is when *neither* person had weapons or they were just messing around and not actually fighting at all. 

That's the entire basis of this tangentally helping to improve RP - you actually **need** equipment to fight now, instead of just a quick and dirty stun. Random joe isn't even remotely inclined to fight nukie because they now don't stand a chance against them - there is no motivation to run up and shove for the epic win because you don't get an epic win for that *nor should you*. 

Traitor with an Esword can no longer be reliably beaten with their own esword, or even just a toolbox, because fighting them with a shove results in you getting esworded down faster than you can toolbox them down. You can still try and indeed make a dent in their health, but you can't single-handedly win alone. *This is good to me*.

> Additionally, nothing in your PR makes players easier to click on, so I have no idea where you're pulling that from.

Slower movement speed = easier to click on, I'm not even sure you're debating in good faith at this point because you're continuing to act like a substantial slowdown isn't relevant at all. Perhaps it isn't if the only thing you consider to be an advantage is a full and complete stun.

**Comment by LemonInTheDark** [comment]
Imagine having democracy, couldn't be me

**Comment by ZeWaka** [comment]
since when should coders merge PRs based on player/community votes? player-democratized code contributions - laughable.

controversial changes always [rile up](https://xkcd.com/1172/) the hornet's nest of the vocal 1% of players (most players probably don't even notice the change) who then forget about it in a week because they got angry at something else
image

**Comment by Howluinb** [comment]
leaving it up to vote, sure, i agree, most of the time shit idea (unless for things like art or whatever), but here, after testing out ruko's amazing (no) nerf pr, if most of the people who actually do a lot of combat complain about it, then it's probably good enough to change.

Yes, 20% of players make 80% of complaints about something, but that still doesn't mean that, when problems arise, and they start being vocal about it, they are necessarily wrong.


Anyways, the shove v4 pr has ruined the entirety of the disarm intent, with its increased click cooldown not even making its new "disarming instead of stun" function impossible to use due to how you can't even pull it off without being blasted many times/hit many times back, and can't even pick up the weapon you were trying to get

Imaginary scenario : bad guy, you want to shove him because the weapon he has is better than yours and you also don't want to be left near death while other people are coming along soon to help him out.
Let's say you take all your actions at the exact same time, same ping.

You disarm him. He shoots.
You wait. He shoots again, because x2 cooldown on action for you
You disarm again. He shoots then drops his weapon, or drops it before shooting.
You wait. He grabs his gun.
You disarm again, He shoots then drops his weapon, or drops it before shooting.
Repeat ad infinitum. You will have no way of fighting back against his attacks, and no way of actually turning the tables, while he still will able to take pot shots at you. Even in the best of scenarios, you might have him not react for nearly a full second and forget to grab their gun, but you already still took 2-3 shots to the face, which is a lot. And if he does grab his gun, you're just gonna get shot even more, downed at one point or another.

It also feels really inconsistent (which is the worst thing you could have in gameplay). It's one of the rare combat actions with a cooldown that's not the usual standard one. It makes it painful to utilize, and really counter intuitive to any new players who tries it out "why do i have to wait so long for this when i take so fast to hug/grab/harm ?"

You have more chances of downing someone with a weapon by punching them repeatedly than actually trying to disarm them. If boiling combat down to just punch punch shoot shoot with no other strategical thing to think about sounds fun, i don't know what you're on about.


Ruko opening another pr shove v5 to quickly counter this one (which was told by bacon it had chances of being merged), with ruko going "actually not as good of an idea as i thought" despite vehemently defending it moments prior, is also disingenuous, as it's clearly just a way to keep the nerf ruko fights so hard for while minimizing the actual change.

I don't know. There's nothing to like about "shove v4", and i don't see any benefit it actually gave to combat on bee. it's not more fun, it's not more interesting to play with or to watch, it's not more tactical or complicated to plan around, it didn't make the fighting that much fairer on bee or buffed antags or nerfed crews, it's just, a complete removal of a mechanic which either doesn't get noticed (because a lot of players don't actually fight that much), or is absolutely hated, due to all of the downsides it brings.

I really hope this pr gets merged, and not just forgotten.

**Comment by Rukofamicom** [comment]
> You disarm him. He shoots.
You wait. He shoots again, because x2 cooldown on action for you
You disarm again. He shoots then drops his weapon, or drops it before shooting.
You wait. He grabs his gun.

Did you know: Even before my PR the cooldown on doing anything other than melee, including shooting a gun, was already shorter than disarm intent

`#define CLICK_CD_MELEE 8`
`#define CLICK_CD_THROW 4`
`#define CLICK_CD_RANGE 4` <- Gun fire rate also matters here with regards to consecutive shots
`#define CLICK_CD_CLICK_ABILITY 6`

(regardless, the issue you described *has been brought to the extreme* and is what v5 tries to fix)

**Comment by PowerfulBacon** [comment]
This PR won't be merged in favor of #6969 as it addresses the changes I requested here properly

**Comment by Wilchenx** [comment]
> since when should coders merge PRs based on player/community votes? player-democratized code contributions - laughable.
> 
> controversial changes always [rile up](https://xkcd.com/1172/) the hornet's nest of the vocal 1% of players (most players probably don't even notice the change) who then forget about it in a week because they got angry at something else image

Yeah okay fascist/commie.

Nice anecdotal argument I guess?

**Comment by PowerfulBacon** [comment]
@Wilchenx Our github should be a place for friendly discussion, silly things like name calling, passive aggressive responses and comments that are counter productive will not be tolerated.
All sides of any argument should be allowed and accepted even if you disagree with them.

**Pull request closed without merging**
