### PR TITLE
GlowStation fixes

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

Fixes various parsing errors caused by "s" in the dmm file.

Fixes arrivals shuttle being misaligned and having no roof on the "bridge" area.

## Why It's Good For The Game

Fixes bugs

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
fix: Fixed GlowStation arrivals.
fix: Fixed GlowStation parsing errors.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
How did this get past the linters

**Comment by itsmeow** [comment]
> How did this get past the linters

The syntax is technically allowed by BYOND, but SpacemanDMM doesn't support it

**Comment by Crossedfall** [comment]
> How did this get past the linters

MDB2 called out the error, but it was merged regardless.

https://github.com/BeeStation/BeeStation-Hornet/runs/11175591608

**Comment by itsmeow** [comment]
Okay but tbh MDB2 breaks all the time

**Comment by itsmeow** [comment]
> > How did this get past the linters
> 
> MDB2 called out the error, but it was merged regardless.
> 
> https://github.com/BeeStation/BeeStation-Hornet/runs/11175591608

Wasn't spockye's fault - the original PR had MDB IGNORE so there was no chance for the error to appear. The issues were part of the original map

**Review by ike709 — APPROVED** [review]

**Pull request merged**
