### PR TITLE
If i did everything right, it should add a new endround OGG.

### PR DESCRIPTION
**Pull request by BettonnCZ**
## About The Pull Request
Its from the new doom game, where Hayden tells you you can't just shoot a hole in to the surface of the mars. Fuck you Hayden, WE CAN.
Original source: https://www.youtube.com/watch?v=nD6lT5JM9gI
I edited it a bit so its shorter.

## Why It's Good For The Game
New endround sounds are cool and funny and don't affect the game when it comes to gameplay.

## Changelog
:cl:
add: Added a new endround song

/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
>add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know

**Comment by ivanmixo** [comment]
that changelog is disgusting

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Bruh fix the changelog

**Comment by ghost** [comment]
fix the changelog you poo poo brain

**Comment by BettonnCZ** [comment]
stop shaming me for the thing :,(

**Comment by ghost** [comment]
@ike709 changelog is fixed

**Comment by ike709** [comment]
This PR is cringe.

**Pull request closed without merging**
