### PR TITLE
Bluespace Artillery tweaks

### PR DESCRIPTION
**Pull request by Dejaku51**
## About The Pull Request

BSA now has internal battery and uses power from cables
B
- [x] has internal battery instead of APC
- [x] uses cable instead of APC
- [ ] make it connect to powernet after construction

## Why It's Good For The Game
BSA using cables and having internal battery have much more sense than just taking power from APC

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

WIP

## Changelog
:cl:
tweak: BSA now uses cables connected to back of the BSA generator
balance: BSA now has internal battery which needs to be full to be able to shoot
/:cl:

### CODE REVIEW

**Comment by Dejaku51** [comment]
still need to connect to powernet after construction and make it solid (for whatever reason i can now pass through it)

**Comment by ike709** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/7004

**Comment by Dejaku51** [comment]
oh, i didn't see ability to fire at shuttles

**Comment by AnCopper** [comment]
RIP pirates

**Comment by FortSumter** [comment]
Muhahahaha! Time to be antag engi and blow those fucking explorers out of the sky while also cutting the station in half!

**Comment by Dejaku51** [comment]
> Muhahahaha! Time to be antag engi and blow those fucking explorers out of the sky while also cutting the station in half!

remember that now its part of bacons supercruise update

**Comment by ike709** [comment]
Stale, ask for reopen if you're still working on this.

**Pull request closed without merging**
