### PR TITLE
Adds new moth plushies

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request

Adds 5 new moth plushies for the new moth types.

## Why It's Good For The Game

More plushies = more fun

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

imagen
imagen
imagen
imagen

</details>

## Changelog
:cl:Varo
add: rosy moth plushie, bluespace moth plushie, plasmafire moth plushie, brown moth plushie, witchwing moth plushie
/:cl:

### CODE REVIEW

**Comment by ClownMoff** [comment]
It's on draft since I dont know if the among us sound effect will get me in trouble until maintainers respond on discord

**Comment by AnCopper** [comment]
https://github.com/BeeStation/BeeStation-Hornet/assets/82319489/78e2432d-e56a-4d99-91fb-eb7a0e5d2bc3

**Comment by EvilDragonfiend** [comment]
Rename it into Spessman Gondola or something like it.

**Review by PestoVerde322 — APPROVED** [review]
everything seems good to go, approved.

**Review by EvilDragonfiend — APPROVED** [review]
Yeah it's fine to go, but let's make sure. Need another maint for this since it's a lil critical. *wink*

**Comment by llol111** [comment]
can we not add dead memes into the game please

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
I am strictly against any blatant/direct references to among us. Please remove that plush.

To quote our design direction

> Features that are strictly references to other games are disliked. Taking inspiration from other sources is fine, but there should be some work to make it fit within the SS13 universe and gameplay style.

**Comment by EvilDragonfiend** [comment]
We are not the subject to interpret the policy. For example, calling it `Astronaut Gondola` makes sense enough and validates `there should be some work to make it fit within the SS13 universe` in my interpretation, but not everyone will agree with it.
That's why I pinged Bacon here. He or at least Crossed should judge this finally.

Calling it `Astronaut Gondola` is funny enough for me to accept this since it really makes sense. We already have enough amount of **"strictly references"** for such kind, but we pretend not to know it.

**Comment by PowerfulBacon** [comment]
Space gondola plushie needs to look like a gondola, among us references are just something that I can see as being only used to break immersion

**Comment by ClownMoff** [comment]
It looks like a gondola. I changed the sprite to have a face on it of a gondola, now it's a mix of a outside refence mixed with the SS13 universe
imagen

**Comment by Rukofamicom** [comment]
Personally I'm strongly against a direct and blatant among us reference at all. People already break immersion with references to it as it is and I don't think we need anything in-game that validates or causes this to happen more frequently than it already does. 

I'm not willing to concede unless the reference is more subtle and isn't apparent at first glance, among us memes IC only serve to bring the game down.

**Comment by Rukofamicom** [comment]
Personally I'm strongly against a direct and blatant among us reference at all. People already break immersion with references to it as it is and I don't think we need anything in-game that validates or causes this to happen more frequently than it already does. 

I'm not willing to concede unless I'm completely outvoted by other maints or the reference is more subtle and isn't apparent at first glance. Among us memes IC only serve to bring the game down.

**Comment by ClownMoff** [comment]
For anyone wondering the sprite now looks like gondola (old pic so it doesnt have the backpack)
imagen

**Comment by Rukofamicom** [comment]
This should get re-approval from Pigeon and/or a spriter in general who better knows exactly how to criticize shading because the sprite looks a bit wrong, but as I said in discord I do approve of the general concept/shape and I like it a lot more than the very blatant one.

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
Ping me when the new sprite is spriter quality approved - this is a placeholder for requested changes so someone doesn't accidentally yolo-merge.

**Comment by ClownMoff** [comment]
@Rukofamicom done

https://media.discordapp.net/attachments/586014397177004074/1189720230176493698/image.png?ex=659f304e&is=658cbb4e&hm=4696254c21c7f9d62d60e63ee3014dcb7c37c4f3e47ae9226e458ba53379eb27&=&format=webp&quality=lossless

**Review by Rukofamicom — APPROVED** [review]

**Comment by Rukofamicom** [comment]
Seeking some additional opinions before I'm personally willing to hit merge, but lifted my block with confirmation of pigeon approval.

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
Alright the shadow council has spoken and wants and strongly prefers the nuclear operative gondola far moreso than the amogus suit. The shadow government dictator himself says we really need nuclear gondola.

Nuclear Gondola can still have the backpack to maintain the slight reference.

**Comment by ClownMoff** [comment]
It pains me that after I've grow so attached to this silly guy I'm being forced into changing it
imagen
Amongusdola, my beloved. You smoke too tough. Your swag Too different. Your bitch Is too bad. They’ll unmerge you.

**Comment by ClownMoff** [comment]
You guys won

https://github.com/BeeStation/BeeStation-Hornet/assets/148357670/de2f7055-c50e-4ecd-9265-5d6756981453

**Comment by ike709** [comment]
If you want to keep the amogus reference you could give the nukie a nukie-themed backpack.

**Review by Rukofamicom — APPROVED** [review]

**Comment by Rukofamicom** [comment]
Costume Gondolas™️ will make a return

**Pull request merged**
