### PR TITLE
Ports Miscreants

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Ports miscreants to the game from goon.

## Why It's Good For The Game

Miscreants are small antagonist like roles that are meant to cause a little chaos or RP a little. They have objectives reliant on annoying others, and can generally disregard the 'be nice to eachother' rule. They can't kill or outright sabotage, tho!

##Progress

* [x] Objectives
* [ ] Datum
* [ ] Event that assigns miscreants
* [ ] Custom miscreants made by admins

## Changelog
:cl: eespee ZeWaka pali6 TTerc F-OS
add: Miscreants
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
> Ports miscreants to the game from goon.

I'm nuking this PR until you follow the actual rules for goon ports.

**Comment by BrumalLake** [comment]
license brrr

**Comment by eeSPee** [comment]
I'll be bak...

**Comment by ike709** [comment]
Also IIRC citadel has a non-license-violating ripoff that you could port.

**Comment by PowerfulBacon** [comment]
just give people abductee roundstart lmao, its already coded for you

**Pull request closed without merging**
