### PR TITLE
 An extra 5 ooc coins if your body gets to cc

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
If you die, but your corpse makes it to cc, then you get an extra 5 ooc coins

## Why It's Good For The Game
Its right inbetween straight out dying, and living, meaning you get no benefit from suiciding
IC it makes sense, because nanotrasen has the most advanced medcare in the universe, so if they salvaged a body they can revive you inbetween rounds.
Also gives more benefit to attempting revive on the shuttle medbay

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
tweak: Nanotrasen issues bonus beecoins if your corpse is recovered and sent back to centcom
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
That looks weird, but can encourage medicals(and people) to take people's bodies, I guess.

**Comment by Archanial** [comment]
We already have too much coins in economy 🔑

**Comment by itsmeow** [comment]
Did we not just remove greentext coins?

If anything, coins are at an all time low

**Comment by EvilDragonfiend** [comment]
> We already have too much coins in economy 🔑

It is only 5 coins difference and we no longer have greentext coins. If you want to remove beecoins, it should be done from crew objectives which unfairly gives beecoins differently based on jobs.

**Comment by EvilDragonfiend** [comment]
I mean, the opinion to close this PR should be like 'your body being taken to CC for rewarding 5 more beecoins is too pasive game play that you can't make yourself. You should do it yourself.'

**Comment by EvilDragonfiend** [comment]
I mean, an opinion to close this PR should be like 'your body being taken to CC for rewarding 5 more beecoins is too pasive game play that you can't make yourself. You should do it yourself.'

**Comment by etherware-novice** [comment]
ok what if its for dying in a pod or shuttle

**Comment by PowerfulBacon** [comment]
> We already have too much coins in economy 🔑 

We don't have an economy, they are just a reward to get some extra fluff items. It's meaningless if you have a million or a thousand of these coins and they can't be transferred

**Comment by etherware-novice** [comment]
ok make them transferrabke

**Pull request closed without merging**
