### PR TITLE
ports tgui dna consoles

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

ports tgstation/tgstation#50225

image

## Why It's Good For The Game

upgrades, people. upgrades

## Changelog
:cl: timberpoes
tweak: DNA Consoles have received hardware upgrades and have a shiny new interface as a result.
tweak: New hardware has dropped legacy support for reading the genetic sequences of the dead and has only limited support for reading the genetic sequences of monkeys.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Sleep seems 100x better than times for animation based things like monkeyize()

**Comment by jupyterkat** [comment]
don't timers do the same thing but more performant? And tg is very determined to remove any 
unnecessary sleep() calls because of that?

**Comment by aidan-bowman** [comment]
speedmerge speedmerge speedmerge speedmerge aaaaaaaaa

**Comment by utilbird** [comment]
> don't timers do the same thing but more performant

No

In most cases, timers are much less performant relative to a simple sleep. They can sometimes be cleaner but in the case of animation and simple wait stuff like this, ideally sleep() should be used

**Comment by jupyterkat** [comment]
gimme an argument of why sleep is better in animations

**Comment by utilbird** [comment]
because it's faster, timers have a lot of overhead

**Review by utilbird — APPROVED** [review]

**Pull request merged**
