### PR TITLE
Revert "Revert "Revert "Adds cerestation"""

### PR DESCRIPTION
**Pull request by CthulhuOnIce**
begone cuck

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Too late nerd I already pulled changes

**Comment by CthulhuOnIce** [comment]
uh-huh

**Comment by qwertyquerty** [comment]
reverting this anyway nerd

**Comment by qwertyquerty** [comment]
hey removing collab ain't cool kid

**Comment by CthulhuOnIce** [comment]
speedmerging 2 year old maps through the web editor aint cool kid

**Comment by qwertyquerty** [comment]
shutup nerd it compiled anyway so gimme my perms back

**Comment by CthulhuOnIce** [comment]
it compiled because the maps arent processed at compile-time

**Comment by qwertyquerty** [comment]
shhh

**Comment by qwertyquerty** [comment]
giv parms

**Comment by CthulhuOnIce** [comment]
download this, test it, and make a PR with the fixed map

**Comment by qwertyquerty** [comment]
You deleted my branch you nerd

**Comment by qwertyquerty** [comment]
kinda rude of you

**Comment by qwertyquerty** [comment]
I give up because youre making me put in too much effort no cere

**Pull request merged**
