### PR TITLE
‎CMOs spawn with their own unique belt with advanced tools

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request

‎CMOs spawn with their own unique belt with advanced tools

imagen

## Why It's Good For The Game

Chief Engineers spawn with advanced tools. This PR makes it so CMOs do the same. Heads should get better equipment than the people under their wing, at least roundstart or at spawn.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

this screenshot has the old sprite 

imagen

imagen

</details>

## Changelog
:cl:
add: Adds Chief Medical Officer belt
tweak: Replaces the belts in Chief Medical Officer's locker for empty Chief Medical Officer belts 
balance: Chief Medical Officers spawn with their own belt with a kit of advanced tools.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
> Heads should get better equipment than the people under their wing

Incorrect, heads should be a leader, not someone who is better at the job than their subordinates. They shouldn't be doing the job, they should be coordinating the department.

**Comment by HowToLoLu** [comment]
> > Heads should get better equipment than the people under their wing
> 
> Incorrect, heads should be a leader, not someone who is better at the job than their subordinates. They shouldn't be doing the job, they should be coordinating the department.

While I agree with this; there is the Chief Engineer who also gets an advanced set of tools by default as well. Which brings into question why shouldn't the CMO get such a set if the CE gets one.

**Comment by PowerfulBacon** [comment]
CE only has them because they've always had them and nobody has taken the time to give an overhaul of heads, so we kind of just stay in the status quo

**Comment by ClownMoff** [comment]
> > Heads should get better equipment than the people under their wing
> 
> Incorrect, heads should be a leader, not someone who is better at the job than their subordinates. They shouldn't be doing the job, they should be coordinating the department.

So whats your ideal situation? CMO just giving orders for the entire shift and not treating anyone?

**Comment by Tsar-Salat** [comment]
> While I agree with this; there is the Chief Engineer who also gets an advanced set of tools by default as well. Which brings into question why shouldn't the CMO get such a set if the CE gets one.

Why are we comparing Medical to Engineering and not Medical to Medical?

Engineers get a full lineup of tools at roundstart, enough to do full construction acts. The CE has the same capabilities as SEs in the advanced tools, they just take half as much space. They also get additional shortcuts like the RCD earlygame.

Doctors get half of the required tools at roundstart, enough only to do tend wounds. The CMO atm gets the same capabilities in their roundstart medkit. They get additional shortcuts like the hypospray and defibbelt roundstart.

I get where you are coming from, but we really should be comparing apples to apples here. Measure how the heads look compared to their underlings, not eachother.

**Comment by Rukofamicom** [comment]
> Chief Engineers spawn with advanced tools.

And this is already bad. There's no reason to expand it. 

Heads exist to be leaders, not to be more powerful at the job. Giving them substantially better equipment is how we get CEs that aren't actually qualified or interested in being a CE.

:key:

**Comment by PowerfulBacon** [comment]
Everything that needs to be said has been said already. The reasoning behind this logic is flawed and conflicts with the design goals.

**Pull request closed without merging**
