### PR TITLE
Brighter and Whiter Lighting

### PR DESCRIPTION
**Pull request by Cenrus**
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/10414

Ports Citadel's changes to their lighting which makes the station look a little brighter.

Before: before

After: after

:cl: CameronWoof
tweak: lighting is brighter
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
this is pretty good. however, qwert may have something to say about the light color being changed back (though i prefer the old nonqwert color myself), so i'll leave this one to him

**Comment by Cenrus** [comment]
qwert gimmie your opinion

**Comment by qwertyquerty** [comment]
As zesko suspected, I'm not really a fan

**Comment by CthulhuOnIce** [comment]
edited to show before and after

**Comment by CthulhuOnIce** [comment]
I like it.

**Review by CthulhuOnIce — APPROVED** [review]
Looks pretty nice, slightly more powerful lights can't hurt.

The drawback as it doesn't show off the fancy lighting as well.

**Comment by qwertyquerty** [comment]
It doesn't show off the fancy lighting nearly as much at all. I don't think the station should be brighter than it already is

**Comment by zeskorion** [comment]
I think it should be put to vote. The station should look like a sterile hospital, not cozy and nice

**Comment by eLeCtrOssSnake** [comment]
No

**Comment by qwertyquerty** [comment]
salute emoji

**Pull request merged**
