### PR TITLE
Removes old clothes closets, moves all the secure job equipment clothes into one file instead of serveral

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Title. Also adjusted it all on the maps. The clothes closets were largely unused and basically legacy since clothes vendors are a thing.

## Why It's Good For The Game

Removes code bloat, also they have some semblance of organization.

## Changelog
:cl:
refactor: old clothes closets are no longer a thing since we have clothes vendors
/:cl:

### CODE REVIEW

**Comment by bloons3** [comment]
Why do you hate clothing closets so much?

**Comment by ivanmixo** [comment]
> Why do you hate clothing closets so much?

Largely unused and made obsolete by clothes vendors. Why do we need them?

**Comment by bloons3** [comment]
> > Why do you hate clothing closets so much?
> 
> Largely unused and made obsolete by clothes vendors. Why do we need them?

Closets are good for stashing items and bodies, especially when they don't look out of place in the department.

**Comment by ghost** [comment]
> > Why do you hate clothing closets so much?
> 
> Largely unused and made obsolete by clothes vendors. Why do we need them?

I use it all the time as a nukie, wizard and sometimes changelings. it's good for easy disguises. why remove it?

**Comment by PowerfulBacon** [comment]
I'm sorry what, you are reducing code bloat by moving everything into 1 super bloated file, making the problem worse?

**Comment by PowerfulBacon** [comment]
Clothing closets are nneeded for people with no money, or no ID who need clothes.

**Comment by ivanmixo** [comment]
Okay, so it's not like those red/blue/gray whatever closets. It's the job specific ones like science which I'm removing. The grey/other color variant clothes closets still exist.

Also alright I'll do something better with the organisation. Having hydroponics.dm or bar.dm for the closets as we currently do is very stupid.

**Pull request closed without merging**
