### PR TITLE
Shuttle hacking + Fixes ports breaking when shuttle console is deconstructed

### PR DESCRIPTION
**Pull request by PowerfulBacon**
…tructed

## About The Pull Request

Implements the ability to hack shuttle computers. Shuttles can be hacked by using a multitool on their circuitboard to disable ID checks. The syndicate infiltrator cannot be hacked.
Also fixes a bug where if a shuttle console was deconstructed and rebuilt while a custom location was designated the shuttle would permanently be stuck.

## Why It's Good For The Game

Fixes a bug, allows hacking of otherwise unhackable shuttles

## Testing Photographs and Procedure

it just works yo
image

## Changelog
:cl:
balance: Shuttle computers can now be hacked by using a multitool on their circuitboard to disable ID checks.
fix: Deconstructing shuttle computers will no longer break shuttle docking if the shuttle has a custom dock defined.
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
can you hack centcom ferry shuttles?

**Comment by PowerfulBacon** [comment]
> can you hack centcom ferry shuttles?

not anymore

**Comment by AnCopper** [comment]
I think that hacking should take a very long time, like 30 seconds.

**Comment by PowerfulBacon** [comment]
> I think that hacking should take a very long time, like 30 seconds.

You have to deconstruct the entire computer, multitool the circuitboard and then rebuild it. It takes a while to do.

**Pull request merged**
