### PR TITLE
Disables cult gamemode [Config proposal]

### PR DESCRIPTION
**Pull request by Wilchenx**
## About The Pull Request

Disables the cult gamemode in config

Please discuss the config change below.

## Why It's Good For The Game

Cult is a horrible gamemode for beestation

It constantly revolves to lethals being given out like candy, stalling the round with 20-30 people dead and cult using extreme amounts of cheese and powergaming.

It usually creates no interesting RP scenarios and ruins the round completely for many players.
</details>

## Changelog
:cl:
config: Probability to roll cult as gamemode on secret reduced to 0
/:cl:

### CODE REVIEW

**Comment by PepegaSandwich** [comment]
Its supposed to be TDM. Some people enjoy it. Looks like ided PR. Cringe in other words

**Comment by PowerfulBacon** [comment]
:key:

**Comment by PowerfulBacon** [comment]
Use the forums if you want to create discussions about changing a particular gamemode.

**Comment by ToasterBan** [comment]
should be lowered down to 1 like other LRP gamemodes tbh

**Comment by Wilchenx** [comment]
> Its supposed to be TDM. 

Noone questioned that?

>Some people enjoy it. 

Emotional argument

>Looks like ided PR. 

Elaborate?

>Cringe in other words

Ease up with reddit buzzwords

**Comment by williamcll** [comment]
Maybe when we're HRP

**Pull request closed without merging**
