### PR TITLE
[PORT] BSA works (with interactions included), minor QoL stuff, Rad Collectors can be upgraded.

### PR DESCRIPTION
**Pull request by SomeAngryMiner**
## About The Pull Request

After doing the autismo BSA station goal and realizing it shot beams of doom to nullspace instead of some miner's gps, i found this deeply outrageous, so i decided to find the PR that fixed that, and slapped some extra stuff from Ike's todo list in. Supposed to be 10 PRs but i decided to not push my luck once i saw the 6 i have here worked perfectly.

-https://github.com/tgstation/tgstation/pull/48277
QoL, very nice, saves time, once you use a screwdriver on a headset, the key you pop out will attempt to be on your hand first, before going to the floor.

-https://github.com/tgstation/tgstation/pull/48362
Self Explanatory. Prevents your RCD building animation to be dragged away while building near a singulo.

- https://github.com/tgstation/tgstation/pull/48317
Santa is now SANTA. regenerates presents properly, cant open them, but can see what's inside.

- https://github.com/tgstation/tgstation/pull/47748
BSA now fires properly at targets instead of trying to make a hole in nullspace. Supermatter will explode if aimed at with the BSA. Singulos caught in the BSA blast radius will be destroyed. (good luck with that, but adds a pretty interesting way to counter a destructive force: another destructive force)

~~- https://github.com/tgstation/tgstation/pull/48220
Radiation collectors can now be upgraded to be more sensitive to radiation, increase power output and research point/bitcoin mining. Ghetto uranium room + collectors engine is now viable, i suppose.~~

- https://github.com/tgstation/tgstation/pull/47823
The title. Ghost spawner females no longer start with long, manly dwarven beards.

## Why It's Good For The Game

fix stuff, add stuff, nice stuff. Also shortens Ike's todo list by like, 5 prs.

## Changelog
:cl: Swindly, Wesoda25, Kriskog, MrPerson, Buggy123, Firecage
add: BSA can now delete singularities if you land a hit on it.
fix: RCD animations no longer will be sucked by the singulo while operating. Scientists Amazed.
tweak: removing encryption keys will now attempt to put them in your hand before dropping to the floor.
fix: Santa got their Santa school diploma (again). it will now properly spawn presents on its bag, be able to tell whats inside, but not open them. No more pulse rifle santa.
fix: spawner female characters no longer start with gorgeous dwarven beards.
/:cl:

### CODE REVIEW

**Comment by SomeAngryMiner** [comment]
tested locally, all features work as intended on a moderately deep test.

**Comment by ike709** [comment]
Are any of these things in https://github.com/BeeStation/BeeStation-Hornet/projects/2

**Comment by SomeAngryMiner** [comment]
every single thing except the RCD and beard stuff, yes.
EDIT: the RCD stuff is also in the todo list, yup

**Comment by ike709** [comment]
Please note that next time in the PR desc.

Also, I think the radiation collector upgrades are a bad idea, considering how broken and terrible radiation is already. Having it on the list of things to port was a mistake. Please remove those changes.

**Comment by SomeAngryMiner** [comment]
i think they are a neat feature, but maybe the power scaling is too strong, we can halve that and the sensibility thing you want, but they are good upgrades for what they cost, besides making the science mode of the collector *actually useful*.

**Comment by SomeAngryMiner** [comment]
removed the rad collector stuff, for now, since we need those fixes merged.

**Pull request merged**
