### PR TITLE
Adds TGUI Recompile Action

### PR DESCRIPTION
**Pull request by MCterra10**
## About The Pull Request
For the record, I hate this lmao.
Adds two things:
firstly, a command (`?rebuild`) that maintainers and the PR author can use on a PR to resolve the TGUI conflicts and rebuild the bundle.
secondly, an automatic tgui rebuild on pushes to master that modify tgui files.

This solution has a few shortcomings:
It runs every time there is a comment on an issue or PR (although no jobs will actually run unless the command is invoked)
it will also not update the tgui code files on the PR in question, only the bundles. This means a full master merge will be required to update all the code files, and requires a second rebuild to run once the PR is merged to update the bundle again.

## Why It's Good For The Game
It's not, and I fully expect crossedfall to shut this down and use it as leverage for his C*** and B*** Torture (CBT) agenda, but ike asked me to make this.

## Changelog
:cl:
add: TGUI conflict resolution action
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
?rebuild

**Comment by ZeWaka** [comment]
the automatic rebuild is dumb and bloaty af (why do you even need to rebuild lmao), the rest isn't

**Comment by Cyberboss** [comment]
> Doing this instead of just porting CBT

**Comment by ZeWaka** [comment]
> > Doing this instead of just porting CBT

CBT is literally CBT
also someone can't meme arrow properly

**Comment by ike709** [comment]
@ZeWaka is working on a better version, so let's give them a chance.

**Comment by PowerfulBacon** [comment]
> > Doing this instead of just porting CBT

cbt

**Comment by ZeWaka** [comment]
^ did it /my way/

**Comment by Crossedfall** [comment]
I'm still not sold on the need for a comment trigger at all, but ZeWaka's methodology is quite a bit cleaner.

**Comment by ZeWaka** [comment]
> I'm still not sold on the need for a comment trigger at all, but ZeWaka's methodology is quite a bit cleaner.

You can do a manually triggered action, via button press. You can set up the input parameters. That requires more work on the user side though.

**Comment by MCterra10** [comment]
Closing, going to make a PR with an improved version later tonight.

**Pull request closed without merging**
