### PR TITLE
 Adds Circuit apparatus and beaker holders as cyborg upgrades

### PR DESCRIPTION
**Pull request by Cenrus**
## About this PR

Adds a new upgrade for engiborgs, a circuit apparatus that works the same as the mediborgo beaker holder, but with circuit boards. Requires iron and titanium. Under the Cyborg utility research node.

Adds an upgrade for mediborgs to get a second beaker holder. Costs metal plus glass (exactly enough for the new large beaker that comes with it).

## Why It's Good For The Game

Gives engineer borgs a new upgrade, and allows them to build computers and machines. Helpful if they'd like to repair after a breach or just work on an expansion project. Still requires a human to install, and is locked behind both tech and titanium being acquired. Does not allow for picking up or using AI law boards, or other borg upgrades.

Gives medical borgs the ability to hold two beakers, allowing them to carry two separate chems. Useful for carrying a beaker of brute-healing juice and another of burn-healing juice, or keeping a beaker of your healing chems while also carrying the cure to that virus around. Caps at the second beaker; you cannot give the borg three.

Mirrored from /TG/station, tested and seems to be working fine. Original PR: https://github.com/tgstation/tgstation/pull/46286

## Changelog

:cl:
add: Added a new engineer cyborg upgrade: the circuit manipulator apparatus.
add: Added a medical cyborg upgrade: the supplemental beaker storage apparatus.
/:cl:

### CODE REVIEW

**Review by MarkSuckerberg — APPROVED** [review]
Was thinking of adding something like this a while ago, but mine got picked apart so much I just kinda gave up on it, but hopefully this goes through. Code looks sound and if it works, it works

**Comment by Cenrus** [comment]
awaiting qwertys approval

**Review by qwertyquerty — APPROVED** [review]

**Comment by Cenrus** [comment]
awaiting testmerge

**Comment by qwertyquerty** [comment]
Did you test this yourself locally @Cenrus

**Comment by Cenrus** [comment]
Tested in localhost and seemed all good for both upgrades.

**Pull request merged**
