### PR TITLE
Box Rework

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
Reworks major parts of Science, Engineering and minor reworks of Medbay. Medbay has been colour coded with dark floors to indicate it is a staff-only area. Whether players follow this or not is up to them but can be used to teach new people.

Currently I still need a tiny bit of extra work around Engineering, Departures, Exploration and the Chapel. Otherwise this is all done and good to go.

There may be undocumented changes that I've missed. If you see any, please inform me. I will update the CL as I or others find them.

TODO:

- [ ] Rework all of Engineering.
- [ ] Fix up Chapel.
- [x] Fix up Exploration, perhaps relocate it?
- [ ] Fix up Departures, don't relocate it.

Medbay fixes:
Removed window air alarm in Medbay storage.
Fixed Genetics maintenance door being glass and not a maintenance door.
Fixed windows in and out of different air alarms areas being regular and not air tight reinforced windows.
Added Morgue door to the public hallway.
Removed 75% of the Virology space.
Removed floating intercom in cryo room.
Removed spare crew monitor.
Made the lobby area air tight.
Rearranged Medbay centre to be more natural.
Removed all white decal tiles.
Removed one stasis bed.
Fixed Chemistry being inaccessible from either Medbay storage or Chemistry. 
Added the second chemistry fridge.

## Why It's Good For The Game
Fixes the many issues of Medbay, mostly undocumented issues.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

Medbay
image

Science - WIP
image

Engineering - WIP
image

Departures and Chapel - WIP
image

</details>

## Changelog
:cl:
add: Chemistry door.
add: Service Maintenance area.
tweak: (Box) Redecalled most of Medbay.
fix: (Box) Fixed all Medbay issues. Detailed list on the PR.
tweak: (Box) Reworked Science.
tweak: (Box) Reworked Engineering hallway.
tweak: (Box) Swapped Tech storage and gateway rooms.
tweak: (Box) Flipped Telecoms control room.
tweak: (Box) Split service maintenance into two sections.
tweak: (Box) Relocated Botany maintenance door.
tweak: (Box) Expanded maintenance by Robotics-Chemistry and Virology.
tweak: (Box) Changed Gravity generator access to CE access.
tweak: (Box) Changes up Departures a tad.
tweak: (Box) Reworked Chapel.
balance: (Box) Removed one stasis bed and added two stasis boards to the tech storage.
balance: (Box) Protecting Nanites server slightly more.
tweak: (Box) Library and Chapel maintenance now needs their respective access to use and not maintenance access.
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
Server label...?

**Comment by BarteG44** [comment]
the only good box rework is a removal PR but still, i applaud your effort

**Comment by MarkusLarsson421** [comment]
I mean... true, but Box is too popular. :/

So instead, it'll at least be updated a tad to not look and play as poorly as it used to.

**Comment by PowerfulBacon** [comment]
Not a huge fan of the dark plumbing area but I like the rest of the medbay changes

**Comment by MarkusLarsson421** [comment]
> Not a huge fan of the dark plumbing area but I like the rest of the medbay changes

I'm not either, but I'd prefer it to be consistent with the other rooms. I could play around with a different set of tiles entirely.

**Comment by Rukofamicom** [comment]
Due to personal circumstances, author has requested that all PRs be treated "as-is" for the time being. 
Closing this one due to merge conflicts

**Pull request closed without merging**
