### PR TITLE
Player Panel: Redux

### PR DESCRIPTION
**Pull request by itsmeow**
## About The Pull Request

Completely rewrites the F6 player panel in TGUI, with additional features and 100% feature parity.

Also adjusts the base admin theme to match the one in the panel screenshot (yellow accent, generally darker, added the bee background).

For TM purposes the legacy panel is still around, when you hit F6 or the verb it will prompt asking which one you want to open. This will be removed before merge.

Edits some of the antag HUD icons (traitor, bloodbro, obsessed, clockcult) to fit the TP crop window (9x9)

Includes popper fixes from:
- https://github.com/tgstation/tgstation/pull/61313
- https://github.com/tgstation/tgstation/pull/61783

## Why It's Good For The Game

Makes administration easier, with more usable tools. The new panel is much easier to view information about a player at a glance, including things like sorting by hours, showing telemetry alert levels, and antagonist status / type directly in the panel.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
refactor: Redesigned the admin player panel completely.
tweak: Re-themed admin TGUIs.
fix: Fixed tooltip related popper component lag in TGUI.
fix: Fixed TGUIs with buttons in the titlebar having their drag box set incorrectly.
tweak: Tweaked some antag HUD icons to fix a 9x9 pixel form factor.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Pretty nice, the colour theme of the button needs nicening I think

**Comment by EvilDragonfiend** [comment]
I think this should be sorted by `player ckey+mind reference` so that it can track a person in multiple minds, or a mob that had swapped a player.

**Comment by itsmeow** [comment]
Previous names are searchable so that is not an issue, you can see them in the bottom left

**Comment by Crossedfall** [comment]
The viewport kind of seems pointless. I feel like it'd be better to drop it and expand the two surrounding panes slightly. Especially since they both deal in information that's slightly longer than what they're currently sized for.

**Comment by itsmeow** [comment]
> The viewport kind of seems pointless. I feel like it'd be better to drop it and expand the two surrounding panes slightly. Especially since they both deal in information that's slightly longer than what they're currently sized for. 

I could add a setting to hide it completely as well. It's a lot more useful if you enable Live View, I just have it off by default because it lags the client (not the server at all, I tested and it's fine)

**Comment by Megaddd** [comment]
I've already mentioned this in the design phase, but I feel like it would look slightly more appealing to the eye if the buttons in the main player table were not visible until moused over, currently I fear with a populated list it would look too "excel-like".

**Comment by Megaddd** [comment]
It might be slightly more convenient if clicking on the name was FLW, analogous to the current ghost "Orbit" window that dchat has, doing FLW could also select that player in the Player Panel as well

**Comment by itsmeow** [comment]
Crash all the admins challenge (easy mode)

Adding a cooldown with equation `max(population / 5, 5)` seconds between updates

**Comment by itsmeow** [comment]
- Needs further optimization (search via DM, fix props layout)
- Hour sorting breaks for 0hrs accounts
- Add a way to deselect player without finding their row again. Just an X button by their CKEY would work

**Review by PowerfulBacon — DISMISSED** [review]
GetFlatIcon is causing huge lag issues, selecting and deselecting on the client is extremely slow and crashes the client for some time.

**Review by PowerfulBacon — COMMENTED** [review]
Lag issues seem to be resolved. Before this is fully merged, the old panel needs to be deleted and the debug dialogue popup removed

**Comment by PowerfulBacon** [comment]
oh wait its already done

**Review by Crossedfall — APPROVED** [review]
It can be a bit of an information overload and takes some getting used to, but, an overall improvement to the current system.

**Comment by PowerfulBacon** [comment]
I should also mention that the UI theme has ugly buttons and the background is a little too intense, but we can sort it out later if needs be

**Comment by itsmeow** [comment]
I think the buttons look fantastic sooo
/shrug

**Pull request merged**
