### PR TITLE
golden has the same movespeed as sage

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
you no longer run at hyperspeed on golden

## Why It's Good For The Game
fucks balance and shit up

## Changelog
:cl:
config: golden no longer has faster movespeed
/:cl:

### CODE REVIEW

**Comment by VictorVow** [comment]
Good PR. Like I've said elsewhere regarding Golden's hyperspeed:

> It’s easy mode for fighting mobs, megafauna, dodging projectiles, avoiding explosions, dodging melee attacks, escaping deadly atmos, etc.

**Comment by ivanmixo** [comment]
Do you even play on golden? Genuine question

**Comment by Archanial** [comment]
I do, sometimes, and this is good change

**Comment by TotallyNotChief** [comment]
something something esports 2d spessmen balance

also https://github.com/BeeStation/BeeStation-Hornet/pull/2430

loling rn!!!!!!!!!!!!!!!

**Comment by ghost** [comment]
> something something esports 2d spessmen balance
> 
> also #2430
> 
> loling rn!!!!!!!!!!!!!!!

i'm sorry that you rely on your hyperpseed so much it just makes you unrobust.

**Comment by FortSumter** [comment]
Downvote. LRPers don't want MRP's disgustingly slow movement speed. Author didn't even give a valid reason why it would be necessary. If you don't want our LRP ideas on MRP, don't push one of your servers most stupid features onto LRP.

**Comment by Blueturbo47** [comment]
Lrp has a smaller pop, by reducing the speed the rounds just become boring especially when it gets to 10 pop, you can't do anything and get anywhere. Also golden is technically the server "For Beginners" high speed will help them while allowing more skilled players to have traits to help increase mood and such for more speed adding more to the game keeping people engaged and just makes round boring if we reduce it.

**Comment by Blueturbo47** [comment]
> > something something esports 2d spessmen balance
> > also #2430
> > loling rn!!!!!!!!!!!!!!!
> 
> i'm sorry that you rely on your hyperpseed so much it just makes you unrobust.

I'm pretty sure he's saying that decreasing speed and increasing projectile speed makes it easy to stun and kill people, not that the speed makes anyone unrobust.

**Comment by zeskorion** [comment]
Pr is cuz people asked for it

**Comment by aguyiguess** [comment]
certified sage moment. just because you got booted off from a population cap doesn’t mean you need to make golden more like sage

**Comment by hotimep** [comment]
mfw run so fast that you outrun bullets

**Comment by Moccha-Bee** [comment]
wtf is even this shit ? another effort to kill lrp ? jesus fuck the fun of lrp is that the rounds are quick and the combat dynamic not because of some bullshit rp reason this is a bad pr and shouldn't be merged.

**Comment by Moccha-Bee** [comment]
> mfw run so fast that you outrun bullets

Just make bullets faster LOL

**Comment by r1ks-iwnl** [comment]
Tfw every exosuit slot clothing has next to no speed disadvantage, every single npc and megafauna is easy-mode to beat, ranged weapons become almost useless, you can run thru entire depressurized departments without even getting to 50% health and grenades become useless too if they don't instantly detonate.

**Comment by r1ks-iwnl** [comment]
And that's just a few things wrong with the movespeed that i can think of right now

**Comment by ivanmixo** [comment]
lmao you don't even play on lrp what are you on about?

> every exosuit slot clothing has next to no speed disadvantage

blatantly false, they make you move slow compared to having no exosuit, skinsuits especially

> every single npc and megafauna is easy-mode to beat

fair enough, you have to use your brain a bit more, but they aren't that much easier

> ranged weapons become almost useless

that's just cuz you're bad at predictions if your enemies aren't moving at slug speed

> you can run thru entire depressurized departments without even getting to 50% health

maybe with old atmos, sure but with fastmos nah, also depends on which dept on what map

> grenades become useless too if they don't instantly detonate

yeah fair enough, but that makes it more skill based to use them since you have to actually time your nades instead of just throwing them and hoping the slow ass speed makes them eat your nade

**Comment by PowerfulBacon** [comment]
Making the servers more consistent with each others is nice, especially when it comes to balancing certain things like megafauna being very easy on LRP compared to MRP.

**Comment by Moccha-Bee** [comment]
> Making the servers more consistent with each others is nice, especially when it comes to balancing certain things like megafauna being very easy on LRP compared to MRP.

there is literally no difference whatsoever between megafauna in mrp and lrp in fact i think that its easier to kill them in mrp

**Comment by leestriter** [comment]
I play a lot of lrp and I think this is much needed. Honestly dont know why so many people are mad about this. The main argument seems to just be against making lrp any more like mrp while the argument for is to allow balance and make things more consistent/easier for the people actually coding the game.

**Comment by leestriter** [comment]
I know this lost the vote, but I wanna implore people to just merge it anyway. Not my decision of course, but technically votes don't really mean anything. Won't be the first or last thing merged without a vote or after a lost vote anyway.

**Pull request closed without merging**
