### PR TITLE
Mechs will now knock people down on melee, rather than make them unconcious.

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Removes unconciousness from mech brute attacks.

## Why It's Good For The Game

Stun combat has long been considered one of the poorer aspects of the game. Mechs go one step up and have sleep combat, so if you get hit by a mech you don't even get the chance to run or react, you are just immediately put to sleep.

## Changelog
:cl:
del: Removes unconciousness from mech brute attacks
/:cl:

### CODE REVIEW

**Comment by Isy232** [comment]
Uhhhhhhhh, replace it with something?

I think a mech punch could do more damage and knock you back or something, especially a durand one.

**Comment by PowerfulBacon** [comment]
It doesn't need anything else, if I replaced the sleeping with something else like this the it would be going from one cancerous gameplay aspect to another

**Comment by nikk735** [comment]
mechs without guns are just beefy armor slow-moving targets now it was already almost impossible to hit anyone

**Comment by Isy232** [comment]
Give it knockdown, it makes it so they can't get away so easy but can still dodge. Sleep is too OP but knockdown would be fair.

**Comment by PowerfulBacon** [comment]
> 
> 
> mechs without guns are just beefy armor slow-moving targets now it was already almost impossible to hit anyone

What combat mech doesn't have guns?

**Comment by githubuser4141** [comment]
> > mechs without guns are just beefy armor slow-moving targets now it was already almost impossible to hit anyone
> 
> What combat mech doesn't have guns?

#2783 Removes mech's weapons to the sec protolathe, so a lot won't have guns at all now. On LRP everyone is so quick even ranged weapons are mostly useless, this just makes mechs completely non-viable against your average hyperspeed nanite infused toolboxer.

**Comment by PowerfulBacon** [comment]
You can still get disablers and non lethals, but even an unarmed mechsh ouldnt have a 1 hit kill. Again this removes its instakillab ability not the ability to melee

**Comment by githubuser4141** [comment]
> You can still get disablers and non lethals, but even an unarmed mechsh ouldnt have a 1 hit kill. Again this removes its instakillab ability not the ability to melee

Maybe not a 1 hit kill, but what if it were to knock them over or slow them down? Again it's pretty much impossible to get consecutive melee hits on something when you're playing a PERSON, let alone a mech with all it's turning delays.

**Comment by PowerfulBacon** [comment]
I can do stamina damage or knockdown (probably a really short knockdown). In their current state unarmed mechs are incredibly overpowered and impossible to fight at close range if the mech user knows what they are doing (we made 2 durands unarmed in about ~5 minutes and wiped out a cult trying to summon nar'sie with only the melee function because you literally cannot fight back when you are put to sleep).

**Pull request merged**
