### PR TITLE
Revert "Make alpha plane invisible while blind"

### LINKED ISSUE #6570: Transforming into a monkey removes your organs.
## Reproduction: Transform someone into a monkey through genetics or become a monkey through ling powers. You'll turn into a monkey with no internal organs and die. The game also seems to spawn an invisble mob without controller where the transformation happened.
I also noticed the invisble mob thing happens if I transform someone into a monkey throught their Player Panel, but in this case the monkey lives. However, if I rehumanize them again the human will have no eyes.

Screenshots: 
https://imgur.com/a/B6pIFBR

### LINKED ISSUE #6573: Eye surgery bugged
Issue reported from  Round ID: 37017 (BeeStation Sage - Roleplay)

Reporting client version: 514.1569

When performing eye surgery it is possible to extract the eyes from a patient, however it doesn't seem to be possible to give them a different set of eyes afterwards (no pop-ups, no loading bars, nothing appears when attempting to do so).

I've noticed this issue once before (either today or yesterday) so it doesn't seem like it's a rare bug, however it does seem recent.

Something worth noting is that when you put items back on, on either the head or eyes slot while the bug is happening the items seem to disappear, however this is only possible once (so once you "put on" a pair of glasses you can't put on another pair).

### LINKED ISSUE #6574: Technophile Chaplain android rite just fucking kills you.
## Reproduction: 
Step one: Be a technophile chaplain, and gather enough points for an android transformation rite.
Step two: Get someone else to do the rite on you since I'm pretty sure you can't do it yourself
Step three: Become an abomination with all human limbs, no organs, and about three seconds to live
Step four: die probably

### LINKED ISSUE #6578: Dragon's Blood Potion is not consumed/removes eyes/
## Reproduction: Drink a Bottle of Dragon's Blood, and roll the Ash Lizard Transformation

The bottle is not consumed, and the resulting transformation completely removes your eyes. As an Adamantine Golem, it also keeps your Adamantine Resonator organ.

### PR DESCRIPTION
**Pull request by Dejaku51**
Reverts BeeStation/BeeStation-Hornet#6482

This PR fucked eyes code badly

fixes #6570
fixes #6573
fixes #6574
fixes #6578 
:cl:
del: reverted changes to blindness
fix: fixed not being able to insert eyes during organ manipulation surgery 
fix: fixed species change removing organs, etc.
fix: other misc eye-related fixes
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Add a CL mentioning the fixes

**Comment by Dejaku51** [comment]
ah sorry because i used revert button it didn't applied template

**Comment by Dejaku51** [comment]
done

**Comment by Dejaku51** [comment]
bruh

**Comment by Dejaku51** [comment]
fuckin pun pun

**Pull request merged**
