### PR TITLE
SOP Energy gun shuffle

### PR DESCRIPTION
**Pull request by Rukofamicom**
### SOP States:
* The Head of Security is permitted to carry any non-lethal weaponry, plus a concealed lethal sidearm.
* The Captain may not take Armory equipment outside of Code Blue or Red Alert, and the Captain must return it once the alert level is lowered.

### Specific changes I made to better accommodate SOP
* Captain's Energy gun in their locker was changed to a miniature energy gun so that it is not an armory class weapon. 
* Captain's antique laser has been made to act more like a gun made technology outdated enough to be called antique. It now fires four rounds per charge and has lost its ability to recharge automatically.
* HoS spawns with a disabler instead of an energy gun. Their multiphase fulfills the role of concealed lethal arm

## Why It's Good For The Game
To be filled in later. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Untested in current iteration, hence draft

</details>

## Changelog
:cl:
balance: HoS spawns with a disabler instead of an Energy Gun
balance: Captain's locker now has a miniature energy gun instead of a full sized one
balance: Captain's antique now behaves like a gun outdated enough to be called an antique can be expected to. 
/:cl:

### CODE REVIEW

**Comment by Ivniinvi** [comment]
HoS gun should not start in armory, they should be able to use it roundstart. It's named the hos gun for a reason, and presents a more powerful non lethal option in the form of its stun setting. While this doesn't solve the latejoin armament issue mentioned, having it start in armory and be inaccessible is not the right answer.

**Comment by Rukofamicom** [comment]
> HoS gun should not start in armory, they should be able to use it roundstart. It's named the hos gun for a reason, and presents a more powerful non lethal option in the form of its stun setting.

This is an exact case of something I brought up. 
> It brings the codebase more closely in line with the rules, SoP and expected gameplay of the server as written, as opposed to just how things have always been on tg derivative servers.

The HoS gun is only the HoS gun because it always has been. The only place it is explicitly tied to the HoS is in code and in how things have always been. There is no specific reason for the HoS to need to start with this weapon or any other extremely powerful weaponry. 

HoS should be following both SOP as written due to being a head of staff, and also following the server rules as written.

> Most shifts (aka "rounds" out-of-character) are "normal" for your character.
> Pretend your shifts normally go smoothly and without major incidents, and that the current round/shift is an anomaly.
> The Head of Security is permitted to carry any non-lethal weaponry, plus a concealed lethal sidearm.

The X-01 Multiphase energy weapon is the equivalent of a personally customized assault rifle. It does not fit the bill of "Concealed Lethal Sidearm", and unless lethal firing mode is removed it also does not fit the bill of being a non-lethal weapon any better than a normal energy gun does. 

Changes similar to this would be a culture shock to any tg derivative server, but they're the sort of changes the codebase needs to bring it more closely in line with the intended goal of the server as described by both the rules and IC policies players are expected to follow. In order for a player to follow SOP currently, they would have to unequip the energy gun that start out equipped into their suit slot with, place it in the armory and take a disabler + optionally take some non-existent lethal sidearm.

**Comment by williamcll** [comment]
Rev rush is going to be so easy now.

**Comment by Ivniinvi** [comment]
So nerf the HoS gun to be in line with a concealed lethal sidearm as described in SOP. Bring its cell down to 600 charge to be inline with the mini egun, or 800 as befits a traitor target and custom sidearm. In comparison, a normal energy gun has 1000 cell charge. Removing the starting energy gun is fine, but the HoS gun has a place in the security weapon system, which is more powerful than the disabler of a secoff but less than an auto rifle or laser gun. Moving it to the armory would make it less powerful than almost anything else in there in terms of lethals, and when the armory is opened up, lethals are most often what people are going for. A HoS gun at its current power level does not merit being moved to the armory. Honestly, even straight up removing the lethal mode would be a better change than moving it to the armory.

**Comment by Rukofamicom** [comment]
> So nerf the HoS gun to be in line with a concealed lethal sidearm as described in SOP.

I mean, yeah that is actually one way of doing it, although the sprite would not be fitting of a "sidearm" weapon at all, even if the weapon is coded as "normal" sized. 

> Honestly, even straight up removing the lethal mode would be a better change than moving it to the armory.

To be honest, I think this is the much better option overall. HoS keeps their highly customized gun as a primary this way, but still has to upgrade to (real) lethals via armory when the time comes as intended.

**Comment by Rukofamicom** [comment]
Okay updated the PR

HoS has their multiphase gun back in their locker
X-01 Multiphase has lost Lethal Firing mode and is instead now a supreme non-lethal weapon instead. 
X-01 Multiphase now has 30 disabler shots per charge (5 more than disabler)
X-01 Multiphase now has 4 taser shots per charge (1 more than before) 
X-01 Multiphase now has 6 freezing shots per charge

**Comment by Rukofamicom** [comment]
Worth noting that the freeze **does** do damage, similar to how the "non-lethal" shotgun shells do. 

Humans take 4 burn damage from one shot
Lizards take 6 damage 
IPCs are immune to cold damage
Oozelings take a whopping 24 damage

So the firing mode is _technically_ lethal to oozelings with enough shots, but will barely do anything to most folks

**Comment by Rukofamicom** [comment]
I erred on the side of caution with the number of freezing rounds, but I'm getting feedback that they are much weaker than I'm giving them credit for, should I increase the amount of freezing shots, or are there some additional non-lethal projectiles I can consider?

Perhaps up it to 8 freezing shots?

**Comment by PowerfulBacon** [comment]
I'm not really a fan of this to be honest, losing the lethal mode of the X-01 is a big deal, especially for antags.
Also I prefer the locker guns, since it allows for them to be stolen.
The miniture energy gun is also pretty rubbish, can it even kill someone in lethal mode?
I always thought the SOP was that captain shouldn't raid the armoury, rather than they aren't allowed an armoury grade gun.
Captain will almost certainly take their antique gun anyway, especially now they have the miniture gun as their gun.
Why wouldn't the HOS just drop the miniture gun and take an energy gun from the armoury? They are permitted to carry any lethal capable sidearm, so why would they keep the worse one?

**Comment by Rukofamicom** [comment]
> I'm not really a fan of this to be honest, losing the lethal mode of the X-01 is a big deal, especially for antags.

Are you also in the boat of thinking a freeze-ray isn't an acceptable replacement? I haven't found anyone who doesn't agree that speed is the most important factor to combat here, and yet the majority response to freeze has been that it is terrible for some reason. Considering it only takes one hit to trigger a substantial slowdown I kinda disagree. 

> Also I prefer the locker guns, since it allows for them to be stolen.

And I prefer antags to use their own tools they are provided instead of raiding the lockers of players who haven't yet connected and aren't present to have a chance at defending their property. The respective lockers have plenty of other useful loot in them and these three roles that are allowed to carry weaponry from the start should have that weaponry on their person.

> The miniture energy gun is also pretty rubbish, can it even kill someone in lethal mode?

While it is a downgrade, I don't think it's nearly as rubbish as its reputation makes others believe. 

Differences between Mini and Normal energy guns:
* It has a battery capacity of 600 instead of 1000 (6 vs 10 lethal, 15 vs 25 disabler)
* It is also a small item instead of a bulky item so it takes up substantially less inventory space and may be pocketed.
Yes it can still crit one person, but you must be relatively accurate. It can easily disable multiple people on one charge.

> I always thought the SOP was that captain shouldn't raid the armoury, rather than they aren't allowed an armoury grade gun.

I can tell you this was absolutely not the intention when I and others writing it, but expecting players to leave powerful equipment in their lockers is too much to ask and also not particularly intuitive, which is why a change like seems necessary now. 

Green alert makes it clear that lethal weaponry should not be considered necessary, as do the server rules regarding treating the shift like you expect nothing will go wrong until something already has.

> Captain will almost certainly take their antique gun anyway, especially now they have the miniture gun as their gun.

I do agree this has already been a problem, and it would definitely be suitable for me to address this within this PR as well. The Captain's **antique** laser is a keepsake, and in a display case as a sort of collector's item given to him by Nanotrasen. I believe it shouldn't be totally useless, but given that it is an antique it should certainly not be 50% better than proprietary energy rifles available in the armory like it currently is. 

I think the Captain should be allowed to walk around with his keepsake, but I do not think the keepsake should be an easy way to get around players being expected not to carry heavy weaponry on green alert. 

> Why wouldn't the HOS just drop the miniture gun and take an energy gun from the armoury? They are permitted to carry any lethal capable sidearm, so why would they keep the worse one?

1. Server rules dictate that the armory is off-limits until a threat is present, it is an admin issue if players ignore this. It cannot be considered an admin issue if the player simply starts out with more weapons than they are supposed to have according to rules though. 
2. The HoS already has substantially better gear than the rest of security with the loadout I have presented. Security officers get a disabler + standard belt gear. HoS gets a Multiphase with more disabler shots and two more firing modes + a sidearm with limited lethals or *even more* disabler shots. HoS also gets all of the standard belt gear and such. 
3. A pistol is a sidearm. An energy assault rifle is not a sidearm. 

> A sidearm is a weapon, usually a handgun, but sometimes a knife, dagger, sword or other melee weapon, which is worn on the body in a holster (in the case of a pistol or revolver) or sheath (in the case of a knife, dagger, sword) to permit immediate access and use.

**Comment by Rukofamicom** [comment]
Updated Cap's laser in line with what I said above. Overall a downgrade, but also improved upon what made the gun unique. 

Current iteration: 
* Clip size 15 -> 4
* Regeneration delay from 8s -> 4s

Burst of ~100 damage with one shot regenerating during the first four, and then a 16 second downtime before it's full again. Strong and unique, but not the stream of 15 continuous shots that puts the armory to shame.

Editted: delay can only occur in intervals divisible by 2 so my calculations were a bit off in testing.

**Comment by Sapfearon** [comment]
hop gun is garbage tho, one of worst guns in game if not the worst. Nobody wants to have it or use, not even explorers. It also can't kill in lethal mode - not enough shots to even kill someone. Captain gun nerf is absurd and insane. So right now cmo, rd, ce have nothing to defend with and die to anyone looking funny at them, hop maybe get lucky and snipe couple disabler shots, hos and captain can possible win if they survive long enough to grab their weapons and fire back.
What you doing is making sure every antag can walk to any head and off them, without 0 chance of fighting back. Thanks.
We still live in world where traitor revolver is strongest weapon you can get by the way, stronger then shotguns, rifles and such.
Let's just remove all weapons and get this over with.

**Comment by Ivniinvi** [comment]
The changes to the captain's antique are not documented in the changelog.

**Comment by Rukofamicom** [comment]
> The changes to the captain's antique are not documented in the changelog.

You are absolutely correct!

I was still playing with numbers trying to find what still feels good to use without being a direct upgrade over armory guns.

Fixing it with current iteration since I never pushed any others I tried out.

**Comment by PowerfulBacon** [comment]
The Head of Security is permitted to carry any non-lethal weaponry, plus a concealed lethal sidearm.
    The Head of Personnel is permitted to carry only their issued equipment for self defense.
    The Captain may not take Armory equipment outside of Code Blue or Red Alert, and the Captain must return it once the alert level is lowered.

I fail to see why anything needs to be changed in order for these to be fufilled. This PR is a balance change with a pretty weak reason at best.

**Comment by Rukofamicom** [comment]
HoS starts with two lethal weapons, neither of which qualify as sidearms. HoS starting equipment is completely out of line for SOP which is intended to be read as "Carry something without lethal capability and an optional concealable lethal weapon". (If the X-01 is supposed to be a small sidearm, I'm really not seeing that in the sprite. I'm also under the impression the only reason it was kept at backpack size was to cater to it being a traitor objective). 

HoP's starting firepower is not really being changed, so I'm disregarding this line.

The captain's starting power has already been nerfed by admins ruling that he is not supposed to take his gun at roundstart. **It is bad game design to leave a powerful gun within grasp on a server where the rules and admins expect you not to touch it**. It's also flavorfully bad that this "antique" gun is easily one of the best guns on the station since it self-charges and sports all the firepower of an armory weapon.

**Comment by SergeiKoralev** [comment]
Sergei, here. Ruko asked me to weigh in.

The intention with SOP is pretty simple: If it's green alert, you shouldn't need a lethal weapon. It's that simple. You _shouldn't_ need one. This does not mean you won't need one, as alert level always starts at green and must be raised as a **_reactive_** measure, not proactive one.

The normal Egun as it stands is neither concealable, nor strictly non-lethal, which puts it into a very grey area for SOP. I agree with Ruko, we shouldn't be utilizing code that instantly sends a separate message from SOP. The X-01 is slightly more in line with SOP as is, considering it's small enough to throw in a backpack and be "concealed", but I again, agree that it's a big yike to carry that and an egun at the same time.

As for the captain's antique laser gun, I want to emphasize this: IT IS AN ANTIQUE! 
Definition: Antique
Noun
a collectible object such as a piece of furniture or work of art that has a high value because of its _considerable age._

My suggestion to dissuade people from using an heirloom like a Bic pen was to make it have the poor aim feature and a chance of exploding when firing. I think Ruko's solution is more fine tuned and makes sense. 

As for the balance concerns here are my thoughts on that.
- If we need to adjust SOP after the fact to assist in balance then we can.
- As it stands no head of staff is completely defenseless. Between batons, flashes, and department gimmicks (Looking at you CMO with a syringe gun), the argument that command won't be able to hold their own is a little preposterous. Between the three members of command who _start_ armed, the miniEguns should provide enough kick if used wisely to get to somewhere where additional armaments can be secured. Of course, if that position is overrun having a few more shots likely won't make a difference.
- The MiniEgun isn't meant to be offensive. Shocker, it's the bug-out gun. It's there to get you out of a shitty situation and then regroup. Your weapon, as a captain or HOP, is to fend off an assassination attempt, not do the job of a security officer. 
- If you don't magdump the MiniEgun will probably serve you better. Aim, use limited fire to make people back off, and then retreat to a secure location.

**Comment by Rukofamicom** [comment]
Following up on the back of Sergei's clarifications and opinions: in order to make it more intuitive to follow the expectations laid out by admins, SOP and the rules I believe **some kind** of change needs to occur to both the Captain and Head of Security's immediate starting loadouts and locker contents.

Two core issues need to be resolved:
* HoS should only have lethals on one weapon at the start of the round, and it should be in the form of a concealable sidearm. While I disagree with the notion, there is some case to be made that the X-01 in its current form qualifies for this. An energy gun absolutely does not and needs to go. 
* It needs to be made intuitive that the antique laser is an antique that isn't really meant to be used for combat, and this needs to be done in a way that is apparent to long-time players who are used to grabbing it immediately. Additionally Captains should either not have access to a personal full-size energy gun in their locker, or somehow be made aware in-game that they are expected not to grab it until alert levels raise. 

There are ways other than my PR to resolve these issues, of course, but you can't tell me these issues simply don't exist. There **is** a disconnect between the codebase and admin expectations of players present here. There is a current admin with a note for taking the captain's laser at roundstart *because it isn't intuitive until you're told.*

There are a lot of points in the PR I will change or remove if told to though, such as giving the three most important roles their self-defense mini Eguns directly instead of via locker. I can have a long argument about why a personally modified and known iconic weapon doesn't qualify as a concealed secondary weapon for the HoS, but it isn't a hill I'm willing to die on either. The HoS and Captain both starting with two assault-class weapons at their disposal, but being expected not to grab them absolutely is though.

**Comment by PowerfulBacon** [comment]
I think if you have a problem with a disconnect between SOP and code, then first make sure a problem isn't with the SOP. The order of priority of things imo should be the game design, then the SOP. I'll be all for this if you can convince me why this is an improvement for the game outside of SOP related reasons.

The Captain's laser gun is basically useless, having only 4 shots before recharging. Even with 15 shots before, you often wouldn't be able to use that alone and would need some other gun as well.
The HOP's gun can no longer be stolen from their locker.
The Captain, who is the most important person on the entire station, now has a gun that is pretty weak and not that great for self defense due to the low capacity. It's more of something to use while trying to run away. I think its fine for the HOP, but the Captain is the person in command of every single person on the station, so should reasonably be able to defend himself even on green alert. From a sense standpoint, someone with that much important would always be protected, even without any known threat at the time, otherwise we wouldn't need presidential bodyguards and what not.
X-01 can no longer fire lethals is a change that I kind of see as a bit non-sensicle. Having a freeze mode instead is incredibly strange.
Again spawning with a gun that is only useful for firing while you run to get a bigger gun is a bit strange for the person in charge of going after and stopping danger, I think they should definitely have a weapon that can be used offensively as well as strictly defensively.

I don't see a problem with SOP being something along the lines of

    The Head of Security is permitted to carry a single non-lethal capable weapon, plus a concealed lethal sidearm.
    The Head of Personnel is permitted to carry only their issued equipment for self defense.
    The Captain may not take Armory equipment outside of Code Blue or Red Alert, and the Captain must return it once the alert level is lowered.

instead of what it currently is and requiring these changes.

**Comment by Rukofamicom** [comment]
After a discussion with Bacon, closing this and pursuing a different path to resolving this issue that better preserves the current game balance. Pending private discussion I'm not part of, I'll be saving the local branch for this in case there is a desire to go back to this path instead later on. 

As it is this branch is such a mess of commits I'll probably just end up remaking it then too though.

**Pull request closed without merging**
