### PR TITLE
Fixes killer tomatos attacking podpeople in frenzy

### LINKED ISSUE #9635: [Bug]: Podpeople get attacked by killer tomatoes
### BYOND Version

514.1589

### Round Date

2023/08/08

### Round ID

_No response_

### Test merges

_No response_

### Describe the bug

Podpeople will still get attacked by killer tomatoes even after awakening them, so becoming a podman is basically useless for antags.

### What did you expect?

I expected the killer tomatoes to not attack me as a podman.

### Reproducible steps

1. Become a podman
2. Awaken a killer tomato
3. Get attacked by it

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

fixes #9635

Killer tomatos would friendly fire when in frenzy mode, which was intended to make them attack other tomatos however this also causes them to friendly fire against pod-people and wood golems which I don't think was intended.
This PR makes it so that frenzy mode will only make them friendly fire against killer tomatos, and will cause them to de-activate frenzy mode after searching for the target.
Also replaces the view with a range and decreases the radius since this code is pretty awful and adds in a 5 second time limit between frenzy checks.

## Why It's Good For The Game

Pod-people and wood golems can now use killer tomatos without getting attacked by them.
Optimises killer tomato lag code.

## Testing Photographs and Procedure

image

## Changelog
:cl:
balance: Killer tomatos will no longer attack pod people and wood golems when in frenzy mode.
/:cl:

### CODE REVIEW

**Comment by Rukofamicom** [comment]
I'm really not a fan of enabling hostile mob spam without any risk to the person doing it.

**Comment by Rukofamicom** [comment]
Adding a key to this one as well, for the reasons outlined in the comment directly above. 

Even if fixing an originally unintended interaction, I don't believe this will actually improve the game to implement. 

:key:

**Comment by PowerfulBacon** [comment]
Make sure to close the associated issue if this Pr is closed

**Comment by PowerfulBacon** [comment]
Actually I'll re-open this since I like the counterplay between pod people and tomato attacks if they can pull it off.

**Comment by Rukofamicom** [comment]
The spam issue I'm talking about was that they can overly spam them with no risk to themselves. 

Current behavior lets them utilize killer tomatoes at no personal risk, but in limited quantities. If they go overboard, suddenly they are at risk of being caught in the frenzy too.

**Pull request closed without merging**
