### PR TITLE
Ports #54991 from /tg/

### PR DESCRIPTION
**Pull request by Wilchenx**
## About The Pull Request

ports https://github.com/tgstation/tgstation/pull/54991

## Why It's Good For The Game

Its good for roleplay, this feature could really assist some of our mrp players in
roleplaying the true depth of their commitments to each other.

## Changelog
:cl: wilchen, optimumtact
add: adds Tail entwining
/:cl:

### CODE REVIEW

**Review by Blueturbo47 — APPROVED** [review]
+1

**Comment by BrotherHangyul** [comment]
No no no no no.

Absolutely not.

-1.

**Comment by Penwin0** [comment]
+1

**Review by ghost — APPROVED** [review]
Good PR.

**Comment by ghost** [comment]
> Good PR.


If it would compile.

**Comment by TeomanTheGreat** [comment]
Second pr for the same port? Funny.

**Comment by qwertyquerty** [comment]
http://static.qtqt.cf/videos/crapola/hilarious.mp4

**Pull request closed without merging**
