### PR TITLE
Arena Controllers - Port from /tg/ [Ready]

### LINKED ISSUE #541: Arena Controller request
Merge request :https://github.com/tgstation/tgstation/pull/46746 , https://github.com/tgstation/tgstation/pull/46904 ,https://github.com/tgstation/tgstation/pull/47008
Details: I would like the Arena Controller to be merged. See, this allows me to spawn certain arenas. This is good for the game because it allows thunderdome to be more dynamic in its fights. My only concern is that it's decently shitcoded. Edit: Added different prs that seem a lot better.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/81945495-arena-controller-request?utm_campaign=plugin&utm_content=tracker%2F120077027&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F120077027&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Was requested by Bass in issue #541. I thought the concept was cool, so I added it. 

Closes #541 

EDIT: LOTS OF CREDIT TO ALL THE MAPPERS FROM /TG/ WHO MADE THE ARENA MAPS

## Why It's Good For The Game
I think it would allow admins to run thunderdome matches a lot easier, and according to most people, thunderdome games are fun. Bass saw it at the /tg/ charity tournament and sent it to me, and then created an issue so I decided to port it.

## Changelog
:cl:
add: Thunderdome Control Console: Easier Setup and more streamlined matches as well as custom arenas.
admin: Added the thunderdome console, which can be controlled IC or with AI interact on.
/:cl:

### CODE REVIEW

**Comment by Bastian0930** [comment]
This is a level 7 qwerty pls moment

**Comment by qwertyquerty** [comment]
How did you test this without any arena maps? Also the readme file appears to still be in the old directory.

**Comment by MarkSuckerberg** [comment]
Er, I used some, I just removed them for fear of them not being acceptable or something. You can also upload DMMs directly into the game.

**Comment by MarkSuckerberg** [comment]
I can add some if you want, though

**Comment by Bastian0930** [comment]
I'd prefer you add the ones included. Kinda nice.

**Comment by MarkSuckerberg** [comment]
There weren't any included.

**Comment by MarkSuckerberg** [comment]
There, all of the /tg/ maps are now in.

**Comment by ike709** [comment]
> step_x/step_y variables detected in maps

**Comment by MarkSuckerberg** [comment]
Fucking /tg/.

**Review by ike709 — APPROVED** [review]

**Comment by Bastian0930** [comment]
Mark: makes few changes
Me: makes map
byond: **DIES**

**Comment by qwertyquerty** [comment]
You didn't map merge centcomm

**Comment by qwertyquerty** [comment]
Also, 2,280 additions, 84,142 deletions doesn't seem quite right...

**Comment by MarkSuckerberg** [comment]
I'm well aware now... I merged it on a computer that doesn't have the hook and the only PC I have that works I can't use so probably just going to revert the commit

**Comment by qwertyquerty** [comment]
Is this ready?

**Comment by MarkSuckerberg** [comment]
I mean, some of the vars are messed up, but it is functional. I'm going to try to fix the things, give me a second.

**Comment by qwertyquerty** [comment]
Looks like mapdiffbot and sprites broke again.

**Pull request merged**
