### PR TITLE
Embedding rework

### PR DESCRIPTION
**Pull request by PowerfulBacon**
closes https://github.com/BeeStation/BeeStation-Hornet/pull/4419

## About The Pull Request

Goes through and ports the fixes from https://github.com/BeeStation/BeeStation-Hornet/pull/4419
Doesn't include the changes that are not relevant to embedding, or the change that makes almost all projectiles embed.

Reworks embedding:
 - Embedding is now blocked by armour
   - If you have enough armour (>50 melee by default) by default the embedded item will not stick into you.
   - If you have less armour, the chance to embed will be linearly decreased based on how much armour you have.
 - Embedding now has a maximum damage it can deal
   - Embedding will only deal brute damage until the maximum damage of the embed is reached. This is, by default, 5 * the weight class of the object + the throw force of the object.
   - Any damage that should be dealt over the max damage is instead dealt as stamina damage.
 - Embedded items can now be removed by other people.
   - Using a hemostat allows you to quickly remove embedded items with no damage.
   - Using wirecutters allows you to remove normal to tiny embedded items with 50% of the removal damage.
   - Using a screwdriver allows you to remove small or tiny embedded items with 80% of the removal damage.
   - ~~Using a shovel allows you to dig out the skin and die from brute damage~~ removed because meme
 - Removes embedding application damage. Anything with large damages applied on embedding has been changed so that the throw-force of the item is now greater.

Ports some important parts of 
tgstation/tgstation#53436
tgstation/tgstation#52912
tgstation/tgstation#59324
tgstation/tgstation#52761

## Why It's Good For The Game

Embedding is incredibly powerful at the moment, and will constantly apply damage while embedded in someone with it being impossible to remove.
This PR makes embedding more reasonable and works it around bee code rather than TG code (since obviously, we have an entirely different medical system).

## Changelog
:cl:
refactor: Refactors embedding:
refactor: Using a hemostat allows you to remove embedded items with no damage applied.
refactor: You can now remove embeds from other people ghetto style: Using a screwdriver allows you to remove small and tiny embedded items with an 80% success rate, and using wirecutters allows you to pull out normal, small or tiny embedded items with a 50% success rate.
refactor: Embeds no longer apply damage constantly, instead they will apply damage until you go under their damage limit (Essentially creating the effect of lowering maxhealth while applied, but alone will not out right kill you).
refactor: Embedded items no longer deal damage when they embed, the impact from the object damages anyway.
refactor: Embeds are blocked by armour, wearing armour reduced the chance of an embed embedding into you. If you have more armour than the embed limit, the embed will fall off, If you have less but still have armour the probability of the embed failing will be decreased linearly proportional to the amount of armour you have.
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Haven't looked at the code, but I like the PR desc 👍🏻 

There's probably a wiki page somewhere that needs to be updated, though.

**Comment by jupyterkat** [comment]
at least make harmless embeds still stick on armor, dammit. How about making it still stick with >50 armor but do no damage overtime and drops when the armor is taken off the user?

**Comment by DatBoiTim** [comment]
BRING BACK THE SHOVEL!!!!!

**Comment by PowerfulBacon** [comment]
> at least make harmless embeds still stick on armor, dammit. How about making it still stick with >50 armor but do no damage overtime and drops when the armor is taken off the user?

If its sticking to the armour then it wouldnt do damage anyway, hence why no embedding. Embedding is for penetration of skin and if something cant penetrate armour, it shouldnt be stuck in the skin.

**Comment by jupyterkat** [comment]
> > at least make harmless embeds still stick on armor, dammit. How about making it still stick with >50 armor but do no damage overtime and drops when the armor is taken off the user?
> 
> If its sticking to the armour then it wouldnt do damage anyway, hence why no embedding. Embedding is for penetration of skin and if something cant penetrate armour, it shouldnt be stuck in the skin.

at least still make sticky taped things still stick to armored people then

**Comment by utilbird** [comment]
bring back the shovel

**Comment by PowerfulBacon** [comment]
> at least still make sticky taped things still stick to armored people then

it would be funky adding in a very specific case to embedding just for sticky tape because sticky tape uses a system for putting objects into people when it is something being put onto something, especially when it would just stick there and do nothing. (Also they got blocked by armour before anyway, but the blocking code was extremely strange)

**Comment by jupyterkat** [comment]
team-fortress-2-loadout-garry-s-mod-polycount-video-game-png-favpng-BsdJGNZCCFAaeCc1nbuj0S0LF

**Comment by OceanFish1** [comment]
Epic embed success

**Comment by utilbird** [comment]
> it would be funky adding in a very specific case to embedding just for sticky tape because sticky tape uses a system for putting objects into people when it is something being put onto something, especially when it would just stick there and do nothing. (Also they got blocked by armour before anyway, but the blocking code was extremely strange)

How will we be able to throw stickynades at sec officers 😔

**Comment by jupyterkat** [comment]
I wanna stick plushies to deathsquads. Bacon hates fun 😔

**Pull request merged**
