### PR TITLE
[SERIOUS 100%] Fixes multiple typos in the Psychozia code

### PR DESCRIPTION
**Pull request by Miliviu**
## About The Pull Request

Fixes a lot of typos we had in the Psychoza code!

## Why It's Good For The Game

Typos are bad and...
E4Dtbt9

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image

</details>

## Changelog
:cl:
fix: Fixed typos in Psyphosia code
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
finally, I have been aksing for this for ages

**Comment by DrDuckedGoose** [comment]
imagew

**Comment by itsmeow** [comment]
merge this right now

**Comment by Penwin0** [comment]
Funniest PR so far

**Review by itsmeow — DISMISSED** [review]
looks good to me, finally some consistency

**Review by EvilDragonfiend — APPROVED** [review]
I am happy with this consistent inconsistency.

**Comment by Miliviu** [comment]
Sadly this will not get merged, 1984 bacon...

**Pull request closed without merging**
