### PR TITLE
Headpats now give a positive moodlet

### PR DESCRIPTION
**Pull request by mcmeiler**
## About The Pull Request
Title.

## Why It's Good For The Game
Hugs have a moodlet, why shouldn't headpats also have one?

## Changelog
:cl:
add: Added a positive moodlet for headpats
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
hey buddy I think you got the wrong airlock, skyrat station is two sectors down

**Comment by mcmeiler** [comment]
> 
> 
> hey buddy I think you got the wrong airlock, skyrat station is two sectors down

tragedy
suffering
absolute hell

**Comment by fighterslam** [comment]
this is good, yes yes.

**Comment by jupyterkat** [comment]
basedo

**Comment by Absolutely-Steph** [comment]
Watch this get shut down due to "fetish content"

**Comment by mcmeiler** [comment]
> 
> 
> Watch this get shut down due to "fetish content"

~~Then we'll know maintainers get turned on by headpats~~

**Review by ike709 — APPROVED** [review]

**Comment by TeomanTheGreat** [comment]
Should have only been for felinids tbh. They are the only species I would think of who would enjoy getting their heads patted.

**Comment by ike709** [comment]
That would be a felinid buff.

**Comment by mcmeiler** [comment]
(and a species PR, which I didn't seek approval for)

**Comment by TeomanTheGreat** [comment]
1984

**Pull request merged**
