### PR TITLE
Clean move delay calculation buffer fix, for cheap

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports:
- https://github.com/tgstation/tgstation/pull/63332

## About The Pull Request

I unno what most of this means, but apparently it's old, archaic, and we can get rid of it for free movement visual performance. Its also like, 3 lines of code. That's good enough for me.

Lemon explains it

> We've got this delay buffer behavior
> Idea is basically, if we're just holding down the key, just keep adding to the old delay
> This way, fractional move delays make sense
> 
> Was added in this commit https://github.com/tgstation/tgstation/commit/491bdace5db9c911add5ff213d04a4b0dad130e3
> 
> When it was added, movement was triggered by verbs sent by the client
> So we needed a big grace window to account for networking delay
> 
> Don't need that anymore cause we use keyLoop, so let's just cut it all the way down
> 
> Why?
> Because right now if you somehow manage to input a move afer move_delay is up
> but before the window runs out, you will be elidgable for a new move before you visually reach the tile
> 
> Got a dm from mothblocks about this last night, something about flash stepping? IDK I don't play here

Assuming "Flash-stepping" refers to the network delay that occurs during movement. I thought this was just a feature of shitty BYOND, but we can just cut it out. Who knew?

## Why It's Good For The Game
Cleaner movement, and for dirt cheap

Goes hand-in-hand with smooth movement (i guess im working on that again lmao)

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Works on my machine

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/2b226123-36b3-44e0-a3ff-18ac266b1e04

</details>

## Changelog
:cl: RKz, LemonInTheDark
fix: fixes visual bug with movement delay calculation, making it cleaner
/:cl:

### CODE REVIEW

**Comment by Rukofamicom** [comment]
> Why?
Because right now if you somehow manage to input a move afer move_delay is up
but before the window runs out, you will be elidgable for a new move before you visually reach the tile

I wonder if this shit is part of why melee combat feels so awful when there's even a moderate difference of ping - People moving out of a tile before they were even fully within the tile. 

I think this should get a test merge to ensure nothing breaks but I don't see why it would if everything Lemon says is true for us as well.

**Comment by Tsar-Salat** [comment]
this is already included in #9529, so uh, TM this first

❤️

**Comment by Tsar-Salat** [comment]
im taking a break, Semester begins soon and this is affecting my mental health

**Comment by Rukofamicom** [comment]
Still testmerged at the moment, but I think it's at least relatively safe to say this causes no issues.

**Review by Rukofamicom — APPROVED** [review]

**Pull request merged**
