### PR TITLE
annihilates the machine deconstruction bug

### PR DESCRIPTION
**Pull request by MACIEKBAKI**
exactly what it says
:cl:
fix: fixed machine decon
/:cl:

### CODE REVIEW

**Comment by MACIEKBAKI** [comment]
i literally copy pasted a line from when tg fixed it and made it a PR

**Comment by MACIEKBAKI** [comment]
@qwertyquerty quickmerge pls

**Comment by qwertyquerty** [comment]
Wait for checks to pass

**Comment by qwertyquerty** [comment]
Travis appears to have broken so I'm just gonna marge

**Pull request merged**
