### PR TITLE
Fixes bomb cores not detonated when installed

### LINKED ISSUE #9608: [Bug]: Syndicate lavaland base lost self-destruct explosion size
### BYOND Version

_No response_

### Round Date

_No response_

### Round ID

_No response_

### Test merges

_No response_

### Describe the bug

Basically ever since the introduction of the bombs rework, the lavaland syndicate outpost lost the explosion size capable of destroying the entire base, which it's... the main purpose of the self destruct device

Currently it only destroys the vault area, a little bit of the unused cargo section and some minor damages to medbay-atmos-backof the bar it's very dissapointed because it misses the whole point of ''self destruct'' specially because most of the ''goodies'' such as the warehouse, the laboratory, chemistry, telecomms are left intact

Some people told me that the base had ''invisible bombs'' under their tiles that caused the massive wipe-out but since the bombs rework got merged we're only left with a regular syndicate bomb that doesn't trigger the chain-detonation of the others

### What did you expect?

For the entire base to be wiped as it was always the case before the bomb reworks

### Reproducible steps

Spawn as an scientist, arm the bomb, wait, admire the small hole left behind, you can even be alive to see it just by stepping into medbay or watching from the cargo warehouse

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Bomb cores will now determine if they are allowed to explode based on some installed variable.

## Why It's Good For The Game

This will fix pizza bombs and bomb turfs not exploding.

## Testing Photographs and Procedure

image
image

## Changelog
:cl:
fix: Pizza bombs and the syndicate lavaland base will now properly explode.
/:cl:

### CODE REVIEW

**Review by Penwin0 — APPROVED** [review]
This probably fixes #9608, could you make this PR close that?

**Comment by Fronsis** [comment]
Yeah i was about to mention @Tsar-Salat about it since he was going to check it, as long as syndiebase gets the old explosion wipe good enough! Good catch on the pizza bomb i knew it looked weird the other day when someone used it

**Comment by Tsar-Salat** [comment]
> Yeah i was about to mention @Tsar-Salat about it since he was going to check it

It's fine. If this fixes the syndie base, then thats that.

**Review by itsmeow — APPROVED** [review]
oh goodie. i was wondering why the pizza bomb just qdeled itself and did nothing

**Pull request merged**
