### PR TITLE
Ports /TG/'s Nekomimetic language 

### PR DESCRIPTION
**Pull request by amidoingitright**
https://github.com/tgstation/tgstation/pull/52958
## About The Pull Request

Adds a special Felinid language

## Why It's Good For The Game

Every other species has its own language, plus felinid currently is all downsides on beecode
lets give the catgirls atleast something unique from humans other than the ears
## Changelog
:cl:
add: Nekomimetic, a special language that felinids can understand
/:cl:

### CODE REVIEW

**Comment by amidoingitright** [comment]
code compiles, i think you should merge this

**Comment by ghost** [comment]
based

**Comment by ToasterBan** [comment]
add this to the languages silicon's know

**Comment by amidoingitright** [comment]
> add this to the languages silicon's know

it is

**Comment by ToasterBan** [comment]
> > add this to the languages silicon's know
> 
> it is

ah then sorry for being a dumbass

so this is probably going to get speedclosed for spiecies change without maintainer approval

**Comment by ivanmixo** [comment]
Yeah shoulda gotten maintainer perm first. Sad.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Species changes require maintainer permission.
Also when spamming uwu on comms will get you banned but you can just talk in this language with these instead
image

**Comment by AnCopper** [comment]
> Species changes require maintainer permission.
> Also when spamming uwu on comms will get you banned but you can just talk in this language with these instead
> image

The obvious meme ones aside, these are all just Japanese words.

**Pull request closed without merging**
