### PR TITLE
Makes Blackbox a bit smaller.

### PR DESCRIPTION
**Pull request by Therealdoooc213**
## About The Pull Request

Makes the blackbox item large.

## Why It's Good For The Game
Traitors shouldn't have to buy a obscure item/ hold the blackbox in their hand to complete objectives.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

https://github.com/user-attachments/assets/0f278ef1-baa5-46c3-873f-cf6084549e1e

</details>

## Changelog
:cl:
tweak: the blackbox is now a large item
/:cl:

### CODE REVIEW

**Comment by Geatish** [comment]
Honestly thats why i like the black box objective. Makes it more like a thing you need to put down and defend instead of just putting it in your backpack and forget about

**Comment by Therealdoooc213** [comment]
> Honestly thats why i like the black box objective. Makes it more like a thing you need to put down and defend instead of just putting it in your backpack and forget about

its not defended though... they just drop it in a corner and wait for shuttle call

**Comment by Fronsis** [comment]
Indeed, most of the time it's interesting to see the objective being stolen but it's just.. very meh after because the traitor hides it on a locker for the remaining of the shift or... walks to the shuttle/pod with the item in hand (And if you aren't buckled say goodbye to objective completion) and it's so obvious.

Or they're forced to invest TC on something like the storage implant

**Comment by St0rmC4st3r** [comment]
Buy an obscure item? Wrapping paper is not obscure....

**Comment by Therealdoooc213** [comment]
> Buy an obscure item? Wrapping paper is not obscure....

This wont fix anything?

**Comment by Therealdoooc213** [comment]
> This wont fix anything?

Also- if this **actually** did something, it'd be a bug.

**Comment by St0rmC4st3r** [comment]
> > Buy an obscure item? Wrapping paper is not obscure....
> 
> This wont fix anything?

Over multiple times, I wrapped the black box in wrapping paper. I couldn't put it in my backpack, but people didn't bat an eye over a little lizard sitting in the shuttle clutching a parcel for his mom in his hands.

**Comment by Therealdoooc213** [comment]
> Over multiple times, I wrapped the black box in wrapping paper. I couldn't put it in my backpack, but people didn't bat an eye over a little lizard sitting in the shuttle clutching a parcel for his mom in his hands.

This doesn't really solve one of the other problems though, traitor's **have** to be buckled to a chair on the emergency shuttle or else they drop it and it doesn't count. Don't say its a non issue either, I've seen it happen multiple times.

**Review by PowerfulBacon — APPROVED** [review]
I don't know when this changed, but it was never intended to be a big item. The exploration blackbox has specific overrides to make it bigger

**Comment by Therealdoooc213** [comment]
IM GONNA LOSE MY SHIT

**Pull request merged**
