### PR TITLE
Makes mindshield block cult stuns instead

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Makes mindshield block cult stuns instead

## Why It's Good For The Game

Cult stuns based on hearing protection is stupid.
1. It's hard to tell if someone has hearing protection and will be affected (they can wear stuff over their ears too)
2. Anyone with a hardsuit or space suit is not convertible

It was intended to counter stun combat, however made the stun an unreliable tool that gets cult cucked way too easily.

having it based on the mindshield instead of the hearing protection is better for these reasons
 - Stealing sec glasses allows you to instantly see who can be affected
 - Combat stuns don't work, as anyone fighting cult *should* have a mindshield
 - Mindshields are a tool for security but aren't powergamed withing 5 minutes by assistants

Some other parts of cult may be overpowered, however, fucking up their only means of early game stealth completely destroys the flow of cult rounds and makes it either 50/50 cult vs sec in an epic battle/cult gets cucked early round and has no chance of winning (discovering cult early on almost guarantees their destruction)

Additionally, out of all the cult rounds I have seen, they only win around 15% of the time, so something that improves the gameplay experience for cultists significantly can't be too bad in terms of making cult literally unstoppable.

## Changelog
:cl:
tweak: Cult stun now works on mindshield instead of hearing protection
/:cl:

### CODE REVIEW

**Comment by Flakkyboo** [comment]
based +1

**Comment by zeskorion** [comment]
I disagree here. First off, the combat potential of cult is already insane- this change was already reverted once, due to stuns just being used for murderbone instead of for conversion.  Remember that all cultists that exist have access to 
- stun
- sword
- armor
- cuffs
- a plethora of other things through their dagger 

On demand, anywhere. Cult isn't like gangs where only the leader and lieutenants can distribute goods- anyone and everyone gets the gear. 

Instead, their conversion process could be improved to be a bit less tedious and more suited for bee. But, at the moment, the ease-of-access of the stuns compared to hearing protection is about where it should be. One hit stuns are always flat out unfair,  and people SHOULD have a fighting chance against conversion

Perhaps start by making sure skinsuit helmets dont have hearing protection before coding some salt after your latest cult redtext

**Comment by PowerfulBacon** [comment]
> , and people SHOULD have a fighting chance against conversion

And mindshields prevent that.
Previously the stun worked on anyone and was easilly used in combat, mindshields are not as accessible and it is very easy to tell who is mindshielded.
Additionally, when fighting a cult you give out mindshields, making it much better for them to remain stealthed.
Also it will prevent getting cucked by a cultist because people wore something that gave them hearing protection for some reason.

**Comment by zeskorion** [comment]
> > , and people SHOULD have a fighting chance against conversion
> 
> And mindshields prevent that.
> Previously the stun worked on anyone and was easilly used in combat, mindshields are not as accessible and it is very easy to tell who is mindshielded.
> Additionally, when fighting a cult you give out mindshields, making it much better for them to remain stealthed.
> Also it will prevent getting cucked by a cultist because people wore something that gave them hearing protection for some reason.

By fighting chance, i mean "a cultist has walked into my department. I cannot in any way fight back because i cant even disarm his magic glowing hand. Guess ill get fucked, then!"

If cult fucks catgo, sec is a condom with mindshields, etc, there is no avoiding that stun. A way to easily avoid getting one-hit-unga'd is the only way to balance one-hit-ungas.  See: flash

Changing it to something like
If(hearing protection == 1)
(Minor effect)
Else if (hearing protection >= 2)
(No effect)
Else
(Full stun)

Would be a better option as well, making sec fully immune but hardsuit fucks only part immune

**Comment by Cenrus** [comment]
I haven't seen the cult win once since the stun nerf. It's incredibly important for their kit because they're weak to ranged ballistic weapons such as riot shotguns. 

Revert both of the stun nerfs and instead nerf barrier runes and the summoning in general to allow more counterplay from the crew. It's too easy to make the Narsie rune then use final reckoning to teleport your entire cult over for a speedy summon.

**Comment by PowerfulBacon** [comment]
> 
> 
> I haven't seen the cult win once since the stun nerf. It's incredibly important for their kit because they're weak to ranged ballistic weapons such as riot shotguns.
> 
> Revert both of the stun nerfs and instead nerf barrier runes and the summoning in general to allow more counterplay from the crew. It's too easy to make the Narsie rune then use final reckoning to teleport your entire cult over for a speedy summon.

I don't think they should be reverted to the 100% win, but mindshield is a good start, and if its too powerful changes can always be made again, and vice versa

**Comment by zeskorion** [comment]
> I haven't seen the cult win once since the stun nerf. It's incredibly important for their kit because they're weak to ranged ballistic weapons such as riot shotguns.
> 
> Revert both of the stun nerfs and instead nerf barrier runes and the summoning in general to allow more counterplay from the crew. It's too easy to make the Narsie rune then use final reckoning to teleport your entire cult over for a speedy summon.

I know what /tg/ pr you're referencing here, and the guy who coded it is a saltcoding cupcake.

**Review by Blueturbo47 — DISMISSED** [review]
+1 also haven't seen cult win once with the new changes except for a time on lrp where all the most robust people got cultist and it made an easy win. Other than that most people who have all antags turned on with lrp don't actually know how to play most of them and when I get people in a cult they are all just incompetent and twiddle their thumbs most of the game without helping cult at all. With the cult stun nerf those incompetent culties just die at the front lines. The mind shield nerf instead of the hearing nerf will help incompetent cult a lot because now they just need to know if someone is mind shielded or not.

**Comment by eLeCtrOssSnake** [comment]
I disagree here.

**Comment by VictorVow** [comment]
What's the status of this PR?

**Comment by eLeCtrOssSnake** [comment]
Stale.

**Comment by Cenrus** [comment]
https://github.com/yogstation13/Yogstation/pull/9543

Yogs has a good solution for combat stuns here.

**Comment by PowerfulBacon** [comment]
I gotta add tin foil that detection and then convince zesk by applying toolbox to head

**Comment by zeskorion** [comment]
> I gotta add tin foil that detection and then convince zesk by applying toolbox to head

do it and ill put it to vote

**Comment by PowerfulBacon** [comment]
Right time to actually do something with my life

**Comment by PowerfulBacon** [comment]
@zeskorion done

**Comment by eLeCtrOssSnake** [comment]
I prematurely vote no, but this should be closed anyway. Bus is not a funny thing to do.

**Comment by eLeCtrOssSnake** [comment]
Btw skinsuits should be removed.

**Comment by eLeCtrOssSnake** [comment]
I would rather make them like a pilot suit that pops like a balloon to protect from pressure for some time, but then wear out quickly and become useless, because depressurisation has now become not dangerous at all, as you can drink coffee before spacing and be full speed resistant.

**Comment by PowerfulBacon** [comment]
This PR has nothing to do with skinsuits or bus I have no idea what you are talking about

**Comment by piterskiy2** [comment]
this sounds like a big L for the cult. instead, make a possibility to disarm their spells if they have it active in their hand. and if their spell get's disarmed, they get disoriantated and lose possibilty to cast spells for 10 seconds or something like that.

**Comment by VictorVow** [comment]
Hearing protection is super common eg hardsuits or printing earmuffs at the public autolathes. This is a cult buff and a necessary one.

**Review by zeskorion — APPROVED** [review]

**Comment by eLeCtrOssSnake** [comment]
Bad chng.

**Comment by PowerfulBacon** [comment]
> Bad chng.

How so?

**Pull request merged**
