### PR TITLE
Makes the SM auxgm-based

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports:
- https://github.com/Monkestation/MonkeStation/pull/551
- https://github.com/Citadel-Station-13/Citadel-Station-13/pull/14961

## About The Pull Request
Shifts a bunch of hardcoded stuff to auxgm. Removes duplicate defines. Added better docs to supermatter

## Why It's Good For The Game
We should be using auxgm for this.
This PR is needed for 5 gas port in a later pr.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Operates normally. o2 plasma and co2 all have normal properties
operatesnormally

I spawned about 30 trit cans in there to see a good delam. good reactions so far
goodreact

still working
goodreact2

delamming fine
goodsds

Explosion range within normal parameters

</details>

## Changelog
:cl: RKz ,Putnam3145, Dwasint
refactor: Supermatter values use auxgm
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
What the hell is auxgm

**Comment by PowerfulBacon** [comment]
We are trying to move away from auxmos and towards the LINDA implementation that TG has

**Comment by Tsar-Salat** [comment]
> We are trying to move away from auxmos and towards the LINDA implementation that TG has

I've seen that said, but I really haven't seen any action towards actually doing so. I assumed that was not actually true, my apologies.

That does bode well for my plans, however.

I will retool the 8 gas pr to work without auxgm changes, and start bringing back pre-auxtool defines in another pr.

**Comment by Tsar-Salat** [comment]
This pr is no longer necessary.

**Pull request closed without merging**
