### PR TITLE
Security hardsuit improvement + Armoured jumpsuit nerf + Syndicate hardsuit disabler buff.

### PR DESCRIPTION
**Pull request by Isy232**
## About The Pull Request

Security hardsuit ballistic armour 15 => 35
Security hardsuit energy armour 40 => 50
Security hardsuit bomb armour 10 => 40
Head of Security's hardsuit is now equal in stats to the security hardsuit, excluding the additional jetpack.

Security jumpsuit stamina armour 30 => 10
The Captain's jumpsuit is now equal in stats to the security jumpsuit.
All jumpsuits with a stamina armour of >10 set to 10, includes syndicate and durathread jumpsuits.

Security hardsuit description improved.

Syndicate hardsuit energy armour 40 => 55
Elite syndicate hardsuit energy armour 60 => 80

## Why It's Good For The Game

Security hardsuits previously had half the ballistic armour of the standard security armour vest. Now they're 5% higher.
Similar for bomb armour, notable being used for PKA's.

Security and syndicate hardsuits have had their energy armour increased to make disablers less effective against them.

Jumpsuits have lost most of their stamina armour, so stacking jumpsuits with armour no longer leads to stamina armour values of 60-80. Requested by Bacon.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/41198990/e8ffe232-5706-48a2-a16d-31e6ae5bf8ce

image

</details>

## Changelog
:cl:
balance: Security hardsuit ballistic armour 15 => 35
balance: Security hardsuit disabler armour 40 => 50
balance: Security hardsuit bomb armour 10 => 40
balance: Head of Security's hardsuit is now equal in stats to the security hardsuit, excluding the additional jetpack.
balance: Security, Durathread and Syndicate jumpsuit stamina armour 30 => 10
balance: The Captain's jumpsuit is now equal in stats to the security jumpsuit.
balance: Syndicate hardsuit disabler armour 40 => 55
balance: Elite syndicate hardsuit disabler armour 60 => 80
tweak: Security jumpsuit description improved.
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
You'll need to check other jumpsuits as well. (i.e. Durathread jumpsuit)

**Comment by WrillWasTaken** [comment]
You changed the laser value too, without mentioning it.

**Comment by Isy232** [comment]
> You changed the laser value too, without mentioning it.

Laser is 30 => 30
Energy was changed which is disablers

**Comment by Isy232** [comment]
> You'll need to check other jumpsuits as well. (i.e. Durathread jumpsuit)

Appreciated, will do

**Comment by WrillWasTaken** [comment]
> > You changed the laser value too, without mentioning it.
> 
> Laser is 30 => 30 Energy was changed which is disablers

Ah I misread, sorry.

**Comment by Isy232** [comment]
I've updated the cl to mention energy armour as disabler armour to simplify it for people who dont know that.

**Comment by Isy232** [comment]
damn that title but this PR morphed into something a big broad

**Comment by DarnTheMarn** [comment]
>All jumpsuits with a stamina armour of >10 set to 10, includes syndicate and durathread jumpsuits.

I think that durathread should have higher than average stamina armor, it takes time and effort to get. Otherwise, pretty cool. Too bad hardsuits still won't be used because space adaptation exists.

**Comment by itsmeow** [comment]
> balance: Security, Durathread and Syndicate jumpsuit stamina armour 30 => 10

This is a huge change. Why?

**Review by PowerfulBacon — APPROVED** [review]

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Durathread should be 20 stamina so that its better, although if it has stamina, it should probably have energy protection too. This could make it worth crafting/obtaining as an antagonist.

**Comment by Isy232** [comment]
> > balance: Security, Durathread and Syndicate jumpsuit stamina armour 30 => 10
> 
> This is a huge change. Why?

A long discussion with bacon and several others.

30 stamina armour is provided by the jumpsuit along with 40 by most standard armours, leaving to ridiculous 70 numbers.
This makes stun batons quite ineffective on these people.

This wasn't intentional, as bacon has said. This is shown in the disabler (energy) armour being significantly lower with none provided by the jumpsuit and 40 by the vest.

Stun batons were unintentionally hard nerfed, I was specifically asked to do this by bacon.

**Comment by Isy232** [comment]
> Durathread should be 20 stamina so that its better, although if it has stamina, it should probably have energy protection too. This could make it worth crafting/obtaining as an antagonist.

Done

`
Durathread Jumpsuit:
armor = list(MELEE = 10, LASER = 10, FIRE = 40, ACID = 10, BOMB = 5, ENERGY = 20, STAMINA = 20)
`

**Review by Isy232 — COMMENTED** [review]
Is this how I review the changes?

**Comment by PowerfulBacon** [comment]
Reviewing is for adding code review on other peoples PR, there is a button to re-request review in the top right of the PR

**Review by PowerfulBacon — APPROVED** [review]
This seems fine with me

**Comment by PowerfulBacon** [comment]
I trust my previous self to have good judgement

**Pull request merged**
