### PR TITLE
Tgchat sorting fix, adds "Mentor PMs" tab

### PR DESCRIPTION
**Pull request by imsynthex**
## About The Pull Request

Yes, I already PRed this once in https://github.com/BeeStation/BeeStation-Hornet/pull/4522 but this is better, probably

## Why It's Good For The Game

Mentor PMs and some radio channels used to be unsorted. Makes it way easier to have a tab with just Mentor PMs or radio channels.

## Changelog
:cl:
add: Added a "Mentor PM" tab to tgchat settings, added most antag comms to "Radio" tab
fix: Fixed "Radio" tab not showing supply, service, centcom and AI private channels
/:cl:

### CODE REVIEW

**Comment by imsynthex** [comment]
run_linters fails no matter what I do send help

**Comment by BrumalLake** [comment]
> 
> 
> run_linters fails no matter what I do send help

bruh you didnt compile tgui

**Comment by imsynthex** [comment]
Because the server compiles it whenever a tgui change gets merged :I (I think, maybe [not])

**Comment by imsynthex** [comment]
It'll still fail run_linters but I'm pretty sure including tgui-panel.bundle.js is unnecessary

**Comment by Sinestia** [comment]
CBT was rejected so it is necessary

**Comment by imsynthex** [comment]
Pain

**Comment by MNarath1** [comment]
> 
> 
> Because the server compiles it whenever a tgui change gets merged :I (I think, maybe [not])

thats for tg you have to compile it manually on bee

**Pull request closed without merging**
