### PR TITLE
Adds a sound effect to the auto transfer vote

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
see title

## Why It's Good For The Game
People often don't notice the transfer vote starting, this attempts to fix that.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image
I can't really put sound in a screenshot but it works.

</details>

## Changelog
:cl:
soundadd: The crew transfer vote now has a sound effect.
/:cl:

### CODE REVIEW

**Review by PestoVerde322 — COMMENTED** [review]
seems like a neat QoL change, approved, even if i'd suggest a way to toggle it.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
Why not have all votes play the sound?

**Comment by itsmeow** [comment]
The only other vote that happens is the map vote, which usually people see easily since it's roundend and they look at OOC, and then custom votes. I think it would probably be a good idea to add to all votes, yeah.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Make this sound effect play on all votes.

**Comment by PowerfulBacon** [comment]
Stale for extended period of time. Ping on discord for reopen.

**Pull request closed without merging**
