### PR TITLE
Upstream ban mirroring

### PR DESCRIPTION
**Pull request by ike709**
Requested by NSV13 since our communities are so intertwined.

Only a draft because I'm too lazy to test it.

## Changelog
:cl:
add: Bee downstreams can now decide to automatically block you from joining if you're banned from bee.
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
This should probably hook into `world/IsBanned`, not `client/new`

**Comment by ike709** [comment]
Probably.

**Comment by utilbird** [comment]
austation is a penal colony

**Comment by ike709** [comment]
Marking this as ready for review @francinum @BeeStation/beestation-reviewers 

It _should_ work, it just needs testing.

**Comment by ike709** [comment]
My response to Fran's comment can be found on discord.

**Review by PowerfulBacon — DISMISSED** [review]

**Comment by PowerfulBacon** [comment]
@Crossedfall code owner

**Review by Crossedfall — DISMISSED** [review]
Looks good to me, just needs the conflicts to be resolved.

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
