### PR TITLE
Lavaland atmos mix is now static

### PR DESCRIPTION
**Pull request by francinum**
## About The Pull Request
Makes the lavaland atmos mix static at `o2=14;n2=5;co2=13;TEMP=300`

## Why It's Good For The Game
Encouraging cargo to mass-scrub lavaland for easy gas isn't a great idea, nor is removing the ability to export gas itself.

This removes the incentive to scrub lavaland, and encourages inter-departmental cooperation if they wish to sell gas.

## Changelog
:cl:
del: For performance reasons, lavaland atmos is static again. The randomization system still exists but sits unused.
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
Thankyou Jesus 🙏

**Comment by aidan-bowman** [comment]
ew

just make it 2-3% bz so you get very little cash out of it, no need to kneejerk nerf this hard

**Comment by francinum** [comment]
> ew
> 
> just make it 2-3% bz so you get very little cash out of it, no need to kneejerk nerf this hard

Yes. There is in fact a need to kneejerk nerf this hard.

**Comment by ike709** [comment]
For performance reasons I'm fine with this. Theoretically an Oxygen Not Included-style gas mining setup could be introduced, but nobody should try it without maintainer approval due to balance issues.

**Comment by ike709** [comment]
You also probably need to edit/remove the station traits that alter lavaland atmos.

**Comment by ike709** [comment]
The players once again stop us from having nice things.

**Review by ike709 — APPROVED** [review]

**Pull request merged**
