### PR TITLE
Ports Mech fixes followup.

### PR DESCRIPTION
**Pull request by Tsar-Salat**
## About The Pull Request

Thought I would be able to port TGUI mech ui in this pr, but mobility refactor will be needed before then.

Features:
- New walking sounds for Ripley!

This PR adds the following fixes:
- Xeno damage is now based on their inherent mob claw damage, not a base hardcoded 15. This means xenos with weaker claws will do less, xenos with stronger claws will do more.
- Mechs no longer explode during destruction
- AIs can operate mech tools through looping in a middleclick (their AI machine interaction ability was overriding the tools)
- Mining mech fixes. Clamps, orebox, etcetera...
- Bumping doors works.
- fixes AI intellicard checks
- You can no longer quadruple time dilation by spamming mech drills
- drill gib is now based on mob health, rather than a hardcoded 200

My fixes:
- Clears up some auxmos fuckery so air cabin works again

Ports:
- https://github.com/tgstation/tgstation/pull/53676
- https://github.com/tgstation/tgstation/pull/54396
- https://github.com/tgstation/tgstation/pull/54523
- https://github.com/tgstation/tgstation/pull/54595
- https://github.com/tgstation/tgstation/pull/55144
- https://github.com/tgstation/tgstation/pull/55145
- https://github.com/tgstation/tgstation/pull/55248
- https://github.com/tgstation/tgstation/pull/55736
- https://github.com/tgstation/tgstation/pull/55986

## Why It's Good For The Game

I think the titanfall pad is cool. Mechs on lavaland are really rare, so this might bump their numbers up a bit. I could also see this as an in interesting innovation for exploration.

The fixes are for the most part not a result of the previous pr, excepting the AI mech tools. Mech drills in particular being able to affect time dilation just by clicking on a singular target a lot was really bad.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/913b1724-36c6-46b6-82a9-e7b668c65cfa

</details>

## Changelog
:cl: rkz, TiviPlus, Fikou, Timberpoes, necromanceranne, InvalidArgument3, zxaber, KathrinBailey
fix: Cleaned up mech door bumping
fix: mechs no longer explode during destruction (inherited from cars lmao)
fix: AIs in mechs can use mech tools again
refactor: cleaned up mining mech tools
fix: AI intellicard checks work on mechs again by checking occupants correctly
fix: Critical fix with mining mech drills

balance: drills now calculate gib damage by checking the mobs health, rather than assuming every mob's health is 200
balance: Xenos now do claw damage on mechs based on their actual arm damage, rather than a base hardcoded 15
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
> Adds a new mech pad that transports mechs from lavaland to robotics via droppod. Prepare for Titanfall!

I love you!!

**Comment by Tsar-Salat** [comment]
> > Adds a new mech pad that transports mechs from lavaland to robotics via droppod. Prepare for Titanfall!
> 
> I love you!!

im going to push it to another pr, this will just be fixes to deal with some stuff I noticed from mech refactor merged this morning

**Comment by Tsar-Salat** [comment]
Alright, found the auxmos that was bugging out and not letting the air cabin spawn like at all. This made firefighter and other mechs with air cabins unable to use them

Should be resolved.

**Review by PowerfulBacon — APPROVED** [review]
Good to go?

**Review by EvilDragonfiend — APPROVED** [review]
I do not see particularly wrong

**Pull request merged**
