### PR TITLE
[Port] Reworks Durand abilities, Adds proyectile components from TG

### PR DESCRIPTION
**Pull request by SomeAngryMiner**
## About The Pull Request

Okay fellows, after a while, my smooth brain figured this out.
First of all, lets start with the short stuff: This PR adds part of tgstation/tgstation/pull/44188 , for the sake of compatibility for new tg features involving guns (although i didnt include the RPG stuff), and for making this PR work, mostly a backend change.
Now, the thing this PR is meant to be: A rework of the durand ability, by Zxaber, from TG, wich was really needed.
For the sake of comparison, Old durand ability used to add 35% reflect chance for the cost of *not being able to move or turn*, making it extremely situacional (Maint tunnels, to name one), and overall useless, but this guy did it good, and replaced it with THIS:
Instead of the reflection chance, the durand spawns a shield, that when activated, nulls all incoming damage (that isnt EMP or explosion) from the front of the mech while still being able to move! for an very high power cost, Im not joking, not even abductor cells will let you keep this shield up forever, and for a reason.

tgstation/tgstation/pull/45144 <- original PR.

## Why It's Good For The Game

Replaces an almost totally useless ability with something that can actually be used properly, making it almost equal as leg servo overload or phasing, their sisters.

## Changelog
:cl:
add: An experimental active shield is being developed by NanoTrasen onboard their stations, Space station 13 has been tasked to do field research on its uses. All Durand type mech blueprints have been adjusted to this.
tweak: Proyectile components have been ported.
/:cl:

### CODE REVIEW

**Comment by SomeAngryMiner** [comment]
Manual port, 30ish minutes of local testing yields no bugs or errors neither with guns or the shield.

**Comment by SomeAngryMiner** [comment]
travis what the fuck is that error.

**Comment by Crossedfall** [comment]
Love when that happens. I've restarted that specific test.

**Comment by SomeAngryMiner** [comment]
everything checks out now that travis works.

**Pull request merged**
