### PR TITLE
[WIP] Machine/Power Code Refactor + Spatial Grid System + Performance Updates

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports /tg/:
- ~~https://github.com/tgstation/tgstation/pull/51536
(While updating AirAlarms why not)~~

- ~~https://github.com/tgstation/tgstation/pull/52235
(Auto SI Units without TGUI, good for examines)~~

- ~~https://github.com/tgstation/tgstation/pull/52970~~

- https://github.com/tgstation/tgstation/pull/53150
(Finish from what I started with machine_stat)

- https://github.com/tgstation/tgstation/pull/53943

- ~~https://github.com/tgstation/tgstation/pull/54373
(Part of machines)~~

- ~~https://github.com/tgstation/tgstation/pull/54600
(Auto SI Units without TGUI)~~

- ~~https://github.com/tgstation/tgstation/pull/60060
(New Alarm Handler)~~

- https://github.com/tgstation/tgstation/pull/60317
(The BIG KAHUNA)

- https://github.com/tgstation/tgstation/pull/61422
(Spatial Grid System)

- ~~https://github.com/tgstation/tgstation/pull/67497
(To help prevent Overlay Overflows, and assist with future scrubber optimizations that process when needed)~~

Ports monke:
- https://github.com/Monkestation/MonkeStation/pull/484

## About The Pull Request
This is a pretty big PR. It adds several things:
- International System of Units (SI) formatting proc applied to examines and other code where it was relevant
- Refactors machine_stat and is_processing() to process on demand
- Start and stop_processing has be adjusted based on the machines operation, meaning that it will process in use, rather than at all times
- Large refactor of machine/power code to cut down on processing time and wasted lists
- Occupant uses setter
- Introduces Spatial Grids
- Light Refactor
- New Alarm Handler Datum

Stuff I need to check was carried over correctly:
- [x] lighting.dm
- [ ] signals(I'm likely gonna have to undo some of your work here. Sorry, Bacon.
- [x] no unintended crossover from monke's apc or tesla ports (I have branches for those already, they are in their own thing.)

## Why It's Good For The Game
Modernizes a lot of code(alarm code was hacky as shit), reduces baseline processing for machines that are operated(it will jump up only when in use rather than just when it exists), better code callbacks
This is going to suck to review, I know, but it has the long term benefit of killing a bunch of debt to be more easily maintainable in the future

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

refactormachineupgrade
Basically the `/RefreshParts()` was touched on nearly every upgradeable machine, just showing upgrades still work

refactormachineupgrade2

refactorlightswitches
Lights look good. Don't see any issues from the refactor. New lightswitches work pretty good.

alarms work
I drained a few batteries and set off a few plasma-fires, alarms responded correctly.

refactorairalarm
hazard_min and hazard_max lookin a whole lot better than min1 and max2

refactorairnames
Vents took the new naming system well. Should be simpler for admins and

</details>

## Changelog
:cl: RKz, DoctorSquishy, Donkie, MadMedicineMan, Rohesie, Kylerace, nicbn, WarlockD
tweak: air alarms can now make vents siphon in addition to pressurize (i.e. if an atmosian is harvesting gas and wants to siphon from a gas chamber only if it is above a certain pressure)
add: pressure vents can siphon
tweak: air vents and scrubbers now have an assigned name entirely unique to it alone. No more 40 different Vent #1's
code: machine code is much more optimized, much in the way of refactoring, much in the way that a lot of resource heavy machines will stop using our goddang processing %100 of the time with the added stop_processing() code
refactor: basically everything thats even tangentially related to machines
add: New Light Switches
imageadd: New Light Switch Icons
refactor: Light Refactor
admin: someone griefing or doing bad stuff with vents or scrubbers should be much easier to investigate with the new unique naming system for vents, rather than the insightful "Primary Hallway vent #4"

/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
I wanted to post this WIP early, but note I am still in the process of adding back any bee-unique features that were erroneously overwritten. If you notice any, kindly post a review. 👍

**Comment by itsmeow** [comment]
*accidentally yolomerges*
that would be so funny i think

**Comment by Tsar-Salat** [comment]
> accidentally yolomerges

Ironically probably the easiest way to test it lmao

**Comment by Tsar-Salat** [comment]
I cross contaminated branches again, woops

**Comment by Tsar-Salat** [comment]
lighting seems to be fucked up on multi-z, probably just going to cut it out

**Comment by Tsar-Salat** [comment]
Screenshot_20230311-141042_Chrome

No point

**Pull request closed without merging**
