### PR TITLE
Adds the ability to craft different types of lockers.

### PR DESCRIPTION
**Pull request by XeonMations**
## About The Pull Request

Adds the ability to select which type of locker you want to create.

## Why It's Good For The Game

Finally allows you to have some variation in lockers, being able to replaced broken lockers easier now.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image
image
image
</details>

## Changelog
:cl: XeonMations
add: Added the ability for people to make different types of lockers
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
personal locker is a no. It should be made with personal crafting with some additional materials... like airlock access thing.

**Comment by PowerfulBacon** [comment]
Crates sell for 500 each at cargo which is why they aren't craftable

**Comment by MarkusLarsson421** [comment]
> Crates sell for 500 each at cargo which is why they aren't craftable

But why? Just remove that. smh

**Comment by PowerfulBacon** [comment]
So that cargo has a way to make money at the start of the round, and once they purchase a crate then its worthwhile to sell the crate, also giving them something to do

**Comment by MarkusLarsson421** [comment]
What if including the note you get from a crate is what gives it its value? So a crate and note are both worthless unless you put in the correct note with the correct type of crate and send it back.

For making money, they can serve a different purpose of being "delivery boys" for different departments in exchange for a small amount of money.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
