### PR TITLE
New brigphys spriters, emt sprites and envirosuits for both

### PR DESCRIPTION
**Pull request by SomeAngryMiner**
## About The Pull Request

Do i have to explain the pr?
Please, cant i just skip to the end?
.
.
its just new sprites.
EMT jacket and vest get a recolor and rework from scratch, EMT jacket gets a total visual overhaul, new jumpsuit style for brig physician, more matching for sec, and a EMT jumpsuit, that way we stray further from them being "MO with fancy jacket"

## Why It's Good For The Game

image

## Changelog
:cl:
add: EMT and brig physician stuff have a new coat of paint.
add: New envirosuits for brig physicians and EMTs
add: Ancient Rigsuit got their old sprite replaced. the legacy suit sprite is still on files, though.
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
image
image
image

Undocumented changes.

**Comment by ike709** [comment]
image

What happened here?

**Comment by SomeAngryMiner** [comment]
oH yeah, the ancient rigsuit also got a rework too, gonna post a pic.
I goofed something up with directions on the EMT envirosuit helmet, but it ended up being fixed with the exact same result as expected.

**Comment by SomeAngryMiner** [comment]
image

**Comment by SomeAngryMiner** [comment]
changelog updated accordingly, now.

**Comment by ike709** [comment]
You added the helmet twice. Once with the dirs properly all in one icon state, and again with each dir as a unique icon state. Please remove the latter.

**Comment by SomeAngryMiner** [comment]
Done.

**Pull request merged**
