### PR TITLE
Boxstations Showers

### PR DESCRIPTION
**Pull request by LastCrusader105**
## About The Pull Request
adds Showers To boxstations Engineering

## Why It's Good For The Game
showers are good for radiation and fires and slimes

## Changelog
:cl:
add: Added showers to Boxstation
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
Nice

**Review by PerishedFraud — DISMISSED** [review]
based, and dare I say, cleanpilled

**Review by super12pl — DISMISSED** [review]

**Comment by PowerfulBacon** [comment]
Why is there 7000 changes for some showers?

**Comment by TeomanTheGreat** [comment]
> Why is there 7000 changes for some showers?

Gotta stay clean

**Comment by 4rchibald** [comment]
@LastCrusader105 Does it just add shower in double airlock between foyer and engineering like it is on other maps or did you work it out in any other way?
If that's the first option I just made a PR (#2660) that reworks medbay on Box but also fixes small issues like wire mess in maints, wrong vent setup in mining airlock and adds shower to engineering in-between airlocks so I guess there's no point in merging your thing.

Curious..years without shower there and 2 people decide to add it in the same day

**Comment by LastCrusader105** [comment]
@4rchibald just adds showers for now
And great minds think alike I guess.....or someone was doing there own work and saw mind and though yes I like that

**Comment by ivanmixo** [comment]
> Why is there 7000 changes for some showers?

Thinking they didn't use strongDMM so Dreammaker spaghetti happened

**Comment by LastCrusader105** [comment]
> > Why is there 7000 changes for some showers?
> 
> Thinking they didn't use strongDMM so Dreammaker spaghetti happened

Pretty much I saw a issue and wanted to contribute to my favourite server, thought I’d fix it, but it’s babies first code
Please feel free to explain what issue is, and how it can be fixed in future

**Review by Crossedfall — CHANGES_REQUESTED** [review]
Mapmerge your change either by using the repo utility https://github.com/BeeStation/BeeStation-Hornet/tree/master/tools/mapmerge2 or by opening the map in a tool that automatically does this for you (e.g. [StrongDMM ](https://github.com/SpaiR/StrongDMM)or [FastDMM2](https://fastdmm2.ss13.io/))

**Comment by LastCrusader105** [comment]
> Mapmerge your change either by using the repo utility https://github.com/BeeStation/BeeStation-Hornet/tree/master/tools/mapmerge2 or by opening the map in a tool that automatically does this for you (e.g. [StrongDMM ](https://github.com/SpaiR/StrongDMM)or [FastDMM2](https://fastdmm2.ss13.io/))

I will do it in about 4 hours

**Comment by LastCrusader105** [comment]
I’ve no idea what I’m doing, I appear to have made a pigs ear of it BUT I think I got the auto mapmerge thing done
I will start again see if I can do it this time

**Review by LastCrusader105 — COMMENTED** [review]
I think this is it @Crossedfall I haven't approved it

**Comment by LastCrusader105** [comment]
no clue anymore
gone in circles

**Comment by LastCrusader105** [comment]
i will do it again

**Pull request closed without merging**
