### PR TITLE
Tail entwinement but it actually compiles.

### PR DESCRIPTION
**Pull request by ghost**
### Why it's good for the Game.

image

## Changelog
:cl:
add: Added Tail entwinement
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
This is low even for you Belone.

**Comment by Blueturbo47** [comment]
At least add it for the meme?

**Comment by PowerfulBacon** [comment]
wheres the gib? I don't see the gib

**Comment by AnjelicaChaykovsky** [comment]
how does it even work ? Code says you target arm or something  ?

**Comment by ghost** [comment]
> how does it even work ? Code says you target arm or something ?

Target the Groin, both persons need to have a Tail.

**Comment by TeomanTheGreat** [comment]
This pr adds tail entwining AND tail holding it seems. Update the CL?

**Comment by utilbird** [comment]
imagine being horny **and** failing to credit any part of the port

**Comment by utilbird** [comment]
also is that austation code without credit smh

**Comment by MCterra10** [comment]
hi, please credit the original authors when you use their code.
I actually authored this commit. your code is literally identical to mine sans the austation comments
https://github.com/austation/austation/pull/2632/commits/037ea3edcc5f2263f94648a9302687c643d2312b

**Comment by utilbird** [comment]
smugged

**Comment by ike709** [comment]
Uncredited port

**Comment by Bestparty** [comment]
Of course belone does it

**Pull request closed without merging**
