### PR TITLE
Added Sections to PR Template to improve maintainability

### PR DESCRIPTION
**Pull request by DatBoiTim**
## About The Pull Request
Revises PR template to adding a testing and issue closer section. 

I pulled the two sections previously non-present here from the template I had made working elsewhere.

**Maintainability starts with the PR.**

## Why It's Good For The Game
Not user facing.

QOL for longer term DevOps. When dealing with unexpected behaviors in the wild, knowing if it is intended can be helpful in some cases.
Moreover, it provides a place for testing/images to be present without getting lost in long lines of commits/comments/etc.

This would also allow for a seamless way to keep a one stop place for documentation in cases of larger PRs.

## Testing Photographs and Procedure

This was pasted right out of the changed file. Idk what else to tell you.

<details>

<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl: DatBoiTIm
server: Revised PR Template
/:cl:

### CODE REVIEW

**Comment by utilbird** [comment]
Is an entire tab needed for closed issues tbh. There's nothing wrong with putting it in "About the pull request" or above it.

**Comment by DatBoiTim** [comment]
> Is an entire tab needed for closed issues tbh. There's nothing wrong with putting it in "About the pull request" or above it.

Well it's not meant to be ever present. Should be removed if N/A for the PR. But having it allows for a physical reminder to put those into the PR when applicable.

**Comment by utilbird** [comment]
If you're one of the few people who actually look through issues you're probably bright enough to reference it. If you _really_ wanted to remind the author you could add a comment at the top of the template informing the author how to properly link issues.

IMO it shouldn't be a section if the author has to delete it 99% of the time, especially for something as simple as issue resolution

**Comment by DatBoiTim** [comment]
> If you're one of the few people who actually look through issues you're probably bright enough to reference it. If you _really_ wanted to remind the author you could add a comment at the top of the template informing the author how to properly link issues.
> 
> 
> 
> IMO it shouldn't be a section if the author has to delete it 99% of the time, especially for something as simple as issue resolution 

Handled

**Comment by mudzbe** [comment]
Everything about the PR should already be described in the about section, this seems like planning for failure

**Comment by DatBoiTim** [comment]
> Everything about the PR should already be described in the about section, this seems like planning for failure

The format of this PR is to provide an easy visual of what the template looks like in action allowing for easier review of its design.

**Comment by KubeRoot** [comment]
I would like to see collapsible sections for screenshots be standardised, like this:

<details>

<summary>Screenshots</summary>

image

</details>

```md

<details>

<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/6917698/145402181-3ec7eb9f-8e80-4858-95d3-a903db342771.png)

</details>
```

Because screenshots take up a lot of space, particularly annoying when looking through the code changes, description and changelog.

But I'd wait on other maintainers' opinion first.

**Comment by DatBoiTim** [comment]
> I would like to see collapsible sections for screenshots be standardised, like this:
> 
> 
> 
> <details>
> 
> 
> 
> <summary>Screenshots</summary>
> 
> 
> 
> image
> 
> 
> 
> </details>
> 
> 
> 
> ```md
> 
> 
> 
> <details>
> 
> 
> 
> <summary>Screenshots</summary>
> 
> 
> 
> image
> 
> 
> 
> </details>
> 
> ```
> 
> 
> 
> Because screenshots take up a lot of space, particularly annoying when looking through the code changes, description and changelog.
> 
> 
> 
> But I'd wait on other maintainers' opinion first.

Yeah that may be a field in the testing procedure section. When I get time to implement

**Comment by DatBoiTim** [comment]
Webedit incoming

**Comment by DatBoiTim** [comment]
> But I'd wait on other maintainers' opinion first.

This entire PR and template lives and dies on maintainer opinion. While on more controversial changes to the template may be worth waiting on, collapsable screenshots/videos is good style, especially in light of the points raised.

**Pull request merged**
