### PR TITLE
Adds blocking tip

### PR DESCRIPTION
**Pull request by That0nePerson**
## About The Pull Request
Adds a tip of the round explaining blocking and linking to the wiki page on it. Also fixes one tip that was wrong.

## Why It's Good For The Game
Blocking is currently not well explained. This somewhat helps.

## Changelog
:cl:
add: Adds a tip of the round for blocking
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
> ## About The Pull Request
> Adds a tip of the round explaining blocking and linking to the wiki page on it. Also fixes one tip that was wrong.
> 
> ## Why It's Good For The Game
> Blocking is currently not well explained. This somewhat helps.
> 
> ## Changelog
> 🆑
> add: Adds a tip of the round for blocking
> /🆑

Advice is wrong. It can be any intent other than harm

**Comment by Sinestia** [comment]
wtf undocumen ted change

**Comment by PowerfulBacon** [comment]
You block on any intent except the one intent made for combat, that is so stupid (although completely unrelated)

**Comment by zeskorion** [comment]
> You block on any intent except the one intent made for combat, that is so stupid (although completely unrelated)

Thats because of a pr (that needs to be reopened but is in pr limbo) that makes your melee attacks hit more easily on harm intent when walking

**Review by utilbird — APPROVED** [review]

**Pull request merged**
