### PR TITLE
no longer makes the cakehat a weapon of war

### PR DESCRIPTION
**Pull request by ghost**
## Why It's Good For The Game

because it is

## Changelog
:cl:

balance: rebalanced cakehat from 15 damage to 5

/:cl:

### CODE REVIEW

**Comment by VictorVow** [comment]
It's just a welder, you can also print a circular saw or butcher's cleaver instead. I'd rather see it's dismembering nerfed first

**Comment by ghost** [comment]
> 
> 
> It's just a welder, you can also print a circular saw or butcher's cleaver instead. I'd rather see it's dismembering nerfed first

yeah i wanted to remove its dismembering but i didnt see any reference to that in the code

**Comment by derpymcfuckwit** [comment]
babby mad

**Comment by zeskorion** [comment]
conflicts

**Pull request closed without merging**
