### PR TITLE
Resprites tools, stock parts, uniforms and hardsuits, spits in the face of god

### PR DESCRIPTION
**Pull request by SomeAngryMiner**
## About The Pull Request

Its that time of the year again, boys. This time i took my sweet sweet time and redid a heavy load of some very old spritesets, such as stockparts, while redesigning a few other things to give bee a more unique style, one example being the engineering hardsuits, each one having a more distinct look instead of the slitted visor, such as the atmospherics one having a gas filters, and engineering having a clearer visor to look at all the pipes to save the soup matter. This is a big one, and i might have missed a few things or fucked something up, better testmerge.

Great contributions by our fellows @Agameofscones and @thatguythere03 as well! thatguy made the new, armored security hardsuits, and triiodine made the new engineering bags and hardhats, both doing a great job.

here are some pictures. _**this is not the entirety of the PR, see icon diffs for the whole thing**_
image
tools and stockparts! (plasma tank not included)

image
chief of engine delamination. Kept the doubleslit visor.

image
engineer's new style.

image
Atmos man, ready to waddle through the 10th plasmafire of the shift.

image
An engineer wearing his snowcoat, insuls, magboots and gasmask, to compare with the old one (image does not include mask transparency)

## Why It's Good For The Game

Bee already has some quite unique features and atmosphere, why not give it unique visuals as well? unifying the colors and shapes, we can strive to have a more uniform style, easily telling us apart from the rest of the TG-like servers.

## Changelog
:cl:
add: The entirety of engineering, stock parts, tools, some of science and security items have been given a new, unique design.
/:cl:

### CODE REVIEW

**Comment by SomeAngryMiner** [comment]
oh god damnit why is travis failing now.

**Comment by Mick1299** [comment]
These all look fantastic. Love the slow updating of textures to include actual depth and shading.

Just two tiny things.
1. Did the nuke screwdriver get an updates screwriver icon? I can see the regular old blue one, and the brass one, but no updated black and red nuke one.
2. Its kind of hard to tell the difference between the engineering and atmos hardsuits at a quick glance. How do they look when they're viewed side by side in game?

**Comment by SomeAngryMiner** [comment]
> 1. Did the nuke screwdriver get an updates screwriver icon? I can see the regular old blue one, and the brass one, but no updated black and red nuke one.

Nuke screwdriver is handled by overlays i assume, since its not present on the tool icon dmi, but there's a chance its somewhere else. If thats the case, ill update it before the merge to include it, not hard.

> 2. Its kind of hard to tell the difference between the engineering and atmos hardsuits at a quick glance. How do they look when they're viewed side by side in game?

while they share colors, you can tell the differences quickly, since engineering has more round and soft shapes, and the atmos hardsuit has more cubical, sharp ones, thats if they have the helmets, the main difference, deactivated.

**Comment by zeskorion** [comment]
1. i like everything here but the gas mask. Gas mask is kinda iconic and shouldn't have such a radical design change
2.have you tested these to sure they all work proper? Especially the cell charger

**Comment by Mick1299** [comment]
New gas mask reminds me of the ones from avatar

**Comment by Coolsurf6** [comment]
Pog

**Comment by SomeAngryMiner** [comment]
> 1. i like everything here but the gas mask. Gas mask is kinda iconic and shouldn't have such a radical design change

if people vote for keeping the old one in, i can just yoink it out of the PR.

>    2.have you tested these to sure they all work proper? Especially the cell charger

all of them work properly, and i tested the cell charger through and through since i wasnt sure if it would work.
do note that i might have fucked up some offsets on inhands or welder fires, so if i happen to stumble into any broken ones ill fix it.

**Comment by triplezeta** [comment]
soul is dead and buried

10/10

**Comment by gonenoculer5** [comment]
@SomeAngryMiner Howdy, im the guy behind T5 parts, we recently moved to being downstream of austation, and was curious if you could take a look at the icons for T5 stock parts and maybe make some textures for em, just to see how they'd turn out with this neato artstyle. Thanks! You can hit me up on discord at Gonenoculer5#9550.

**Comment by Draganfrukts** [comment]
The soul has departed. (Amazing sprites though)

**Comment by nigaalfred69** [comment]
i hate everything except the emergency welder that looks pretty cool

**Comment by Cw3040** [comment]
Change the color of the Jaws back to red ~~and plasma tanks to puce~~

**Comment by Jalleo** [comment]
Now that I am looking at them overall fully. I am noticing the yellow be very prominent. If you can set it up so we can have the analyzer and t-ray be multi-color able like the screwdriver I will code that for you.

**Comment by SomeAngryMiner** [comment]
> Change the color of the Jaws back to red ~and plasma tanks to puce~

i can give it a more distinct look, but i want all advanced tools to have a similar pallette to easily distinguish them.

> i hate everything except the emergency welder that looks pretty cool

cant please everyone sadly, but thats what votes are for!

> Now that I am looking at them overall fully. I am noticing the yellow be very prominent. If you can set it up so we can have the analyzer and t-ray be multi-color able like the screwdriver I will code that for you.

that would be grand, on a different PR.

**Comment by TotallyNotChief** [comment]
Hard no on the gasmasks.
Also the new magboots look kinda lame

Actually the more i look on this, the more things i start disliking. Why did you have to make everything so... yellow? And the difference between the engi and the atmos hardsuits is way too minimal. And the HoS's shoulder pads or whatever those things are look very weird. Also, maybe its just me, but the other major problem with this PR imo is that the hardsuits look more like softsuits now. I don't know chief, this aint it at all.

**Comment by SomeAngryMiner** [comment]
> Also the new magboots look kinda lame

Have any ideas or suggestions on how to improve them? i thinned them down so they dont clip over hardsuits and such.
 
> Actually the more i look on this, the more things i start disliking. Why did you have to make everything so... yellow?

Engineering tools are the only set that'll use a yellow base, i wanted to have a cohesive style and make it so they can be identified easily as tools, besides making them pallette compliant. Other departments are gonna have other colors.

>the difference between the engi and the atmos hardsuits is way too minimal. 

A lot of people said that, changing it right now.

>And the HoS's shoulder pads or whatever those things are look very weird. 

Can tell thatguy to fix them, if more people think its weird.

>maybe its just me, but the other major problem with this PR imo is that the hardsuits look more like softsuits now.

I... dont see it? they have plating and are made of solid metal, how do they look more like softsuits?

>change the color of the jaws back to red

image

ya sure you want them red?

**Comment by TotallyNotChief** [comment]
>i thinned them down so they dont clip over hardsuits and such.

I think this may be the problem. I liked them thicc

**Comment by ike709** [comment]
Mind splitting the hardsuits and tools into separate PRs? I'm not a huge fan of the tool art style but some of the hardsuits are really good.

**Comment by Crossedfall** [comment]
Overall I think these are good changes. The main bit of feedback I have would be that some of the tools aren't as distinguishable as the original sprites. Or, rather, it is a little harder to immediately tell what the item is based on the new sprites.

Some quick examples of that would be the new welders, the jaws of life, and the RCD.

Perhaps using a bit less shading and differentiating the colors a bit more might help there?

**Comment by SomeAngryMiner** [comment]
> Mind splitting the hardsuits and tools into separate PRs? I'm not a huge fan of the tool art style but some of the hardsuits are really good.

sure, but where do stockparts resprite fall exactly?

> Some quick examples of that would be the new welders, the jaws of life, and the RCD.

i had this problem a lot with the older versions of the tools, mainly welders. I see that the jaws might be a lil too busy, so ill see what i can do.

**Comment by Sinmero** [comment]
Its hard to tell welders and rcd apart. 
CE hardsuit is nice but i kinda dont like new engi/atmos hardsuit helmets i think that 'deadspace like' helmets look better.
Also atmos hardsuit and engi hardsuit look too similar.

You forgot to change 'in hand' sprites for hardsuits.

**Comment by yorii** [comment]
Atmos hardsuit needs more blue, it looks way too similar to the engineering one.

**Comment by PowerfulBacon** [comment]
I like it but the engineering and atmos hardsuit seem a bit more like the old rig hardsuit rather than a modern special hardsuit, I think the old brighter yellow colours looked better personally.

Those stock parts are amazingly beautiful though

**Comment by Isy232** [comment]
Ye, atmos suit maybe needs a bit more blue, but other than that these look amazing

**Comment by ivanmixo** [comment]
I kinda like this, but there are quite a few things that bother me.

Could you please make all the basic tools have the same orientation as the originals? Like you made the screwdriver diagonal, but made the wrench horizontal, could you make them have the same orientation as the old ones? Wirecutters look a bit small, analyzer should look less like an engi only tool, and more like something in between sci and engi, plasma tank is just weird and power cells look like legos. Also please try to make the hardsuits look less like space suits and more like hardsuits, add more blue to the atmos suits and make the hardsuits look more like the Dead Space inspired ones. You should give yourself more space with the RCD sprite, it looks really similar to the welding tool.

I love what you did with the stock parts though, the wires hanging out look really nice and the inducers are pretty damn good looking.

**Comment by SomeAngryMiner** [comment]
>could you make them have the same orientation as the old ones? 

having the wrench on diagonal looked incredibly silly, trust me i tried.

>Wirecutters look a bit small

should have that fixed up soon.

>plasma tank is just weird

plasma tank is not on the PR, specified on the image n the icon diffs.

>Also please try to make the hardsuits look less like space suits and more like hardsuits

Gosh darnit people, specify what do you mean by this: they have about the same ratio of plating as the old ones.

>add more blue to the atmos suits

doing that.

>make the hardsuits look more like the Dead Space inspired ones.

having every single hardsuit be the same but in different colors is dull, but *some* are keeping the dead space slit visors, like CE, mining n probably something else.

**Comment by Isy232** [comment]
> Also please try to make the hardsuits look less like space suits and more like hardsuits

> Gosh darnit people, specify what do you mean by this: they have about the same ratio of plating as the old ones.

I think actually it would look like they were plated more if you removed the plating from the joints. As of now I can understand some people thinking the entire thing looks like it is unplated instead.

I have no idea how this would look though, I am not a spriter.

**Review by zeskorion — CHANGES_REQUESTED** [review]
Excellent PR, but could you please atomize it a bit?

**Comment by SomeAngryMiner** [comment]
alrighty, ill split it it tool, stockparts, then armor.

**Comment by Agameofscones** [comment]
🎊

**Pull request closed without merging**
