### PR TITLE
Beeviro part 2: beneficial symptoms, stat rebalance

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request
hoooooooooh, this is a big one.
The biggest part of this pr is the replacement of all conditional healing symptoms with symptoms that passively heal when a threshold is met, at the cost of side-effects. the new symptoms are as follows:
**Pituitary Disruption (level 7):**
At base level, makes you bigger, scaling with stage speed. at 8 stage speed, causes passive brute healing, at the cost of occasionally vomiting up blood and guts. at 12 stage speed, quadruples the healing, but causes you to slowly die of cell damage, and puke up more advanced tumors, which may come to life and attack! (not sure what the brute heal/cell damage ratio per tick should be. at the moment it's 4 brute heal/ .2 cell damage, not sure if this should be changed. it also unpredictably knocks you down while you have it and makes your hitbox larger, so that should be enough downside...)
**Organic Flux Induction(level 6):** 
At base level, emps the host. At 4 stealth, heals mutations and cellular damage. At 8 transmission, causes the host to release EMP pulses
**Hyperperspiration(level 6):**
at base level, causes sweating, lowering firestacks and rarely leaving short-lived pools of water. at 6 transmission, causes sweat to extinguish fire and clean messes in a 2-tile radius every so often. At 8 transmission, heals toxin and purges reagents, spraying them in the same 2-tile radius. 
**Thermal Retrostable Displacement(level 8):**
At base level, causes host to teleport back to an area they experienced stable temperature when they get too hot or cold. At resistance 8, causes this process to occur in a localized space, making the disease heal burn damage, and trigger from burn damage as well as temperature. at a transmission of 8, increases burn healing, and lowers the thresholds at which the host teleports
(thanks to the citadel chem Eigenstasium, coded by Fermi, for the idea and part of the code)

Second, this ports the fun symptom, Polyvitiligo, from this lame pr, as a level 0. This does NOT  replace revitiligo, but i've seen people ask for polyvitiligo.
https://github.com/tgstation/tgstation/pull/45297

Third, this has a number of balance tweaks. Stat tweaks and such, as well as a new beneficial threshold on dna saboteur, a humorous code interaction on spontaneous combustion (it's more dangerous to fat people), and Self Respiration now causes anaerobic reactions in the host, resulting in unfortunate emissions. Vomit (the symptom, not the entire mechanic) also no longer stuns

many of the stat changes, and the code for Self Respiration's change, were taken from this PR
https://github.com/tgstation/tgstation/pull/42979/files

removes a few useless symptoms:
choking (of the three lesser kill symptoms, this one cant even kill people, and has shit stats. will not be missed)
dizziness (bugged, shit stats, even not including that it's utterly useless)
metabolic boost (absolutely useless. Weight Loss and Toxolysis both exist)

oh, and finally adds the beeviro symptoms to sentient diseases

## Why It's Good For The Game
-makes virology healing more interesting
-buffs a lot of off-meta virus shit to mix shit up
-removes useless symptoms that serve no purpose but to clog up the pool
-adds some interesting interactions to old symptoms
-oh, and that one /tg/ symptom people wanted
## Changelog
:cl:
add: Thermal Retrostable Displacement, a new burn healing symptom
add: Pituitary Disruption, a new brute healing symptom
add: Organic Flux Induction, a cell damage healing symptom
add: Hyperperspiration, a toxin healing symptom
add: tumor monky ghostrole. may need some text tweaking- right now it's told to kill it's daddy or the virologist, and then itself.
add: ports Polyvitiligo
add:adds most non-level nine new symptoms to sentient disease
del: Choking symptom
del: Dizziness symptom
del: all conditional heal symptoms
del: that metabolism symptom
tweak: a metric fuckload of symptom stats.
tweak: added fart atmos to self respiration
tweak: adds a beneficial threshold to DNA saboteur
tweak: spontaneous combustion does more damage to fat people
imageadd: tumor monky codersprites
/:cl:

### CODE REVIEW

**Comment by FancyCyclops** [comment]
Fetish code.

**Comment by zeskorion** [comment]
> Fetish code.

...the fuck kinda weird shit do you think im into? I can guarantee you it aint this.

**Comment by triplezeta** [comment]
I think they're referring to self respiration and the farts.

**Comment by zeskorion** [comment]
> I think they're referring to self respiration and the farts.

I'm aware of that fact. The original pr with farting symptoms had the same issue


but farts are funny

**Comment by triplezeta** [comment]
*are they really though?*

**Comment by zeskorion** [comment]
> _are they really though?_

ask goonstation

**Comment by qwertyquerty** [comment]
Has this been well tested?

**Comment by qwertyquerty** [comment]
If this has been well tested by you I'm ready to merge

**Comment by zeskorion** [comment]
> If this has been well tested by you I'm ready to merge

heavily tested

**Comment by zeskorion** [comment]
time to update the wiki

**Pull request merged**
