### PR TITLE
Chem refactor stage 1 - refactor reagent holder, new organ "Veins"

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
Chem refactor stage 1 - refactor reagent holder, new organ "Veins"

* "reagents" are no longer true reagent holder to carbon mobs
* Adds a new organ "Veins", and that's an abstract organ. That exists in every mob, and it works as your reagent holding system

## Why do you do this?
I am planning refactoring the chem system.

A human will have these reagent holders:
* **Stomach**: Pills, liquids will go here first, then metabolisation sends it to "veins"
* **Lungs**: All forms of gas will go here, then metabolisation sends it to "veins"
* **Veins**: a new organ, the true reagent holder of the mob. metabolisation makes an effect, and sends it to "liver"
* **Liver**: Takes reagents from Veins, then "metabol**itize**" accepted reagents, then send it back to Veins.
  Metabolitize makes the metabolite of a reagent.
* **patches**(not organ): This will be on your limb, and will send reagents to "Veins" until it's fully consumed. Each limb can have only one patch at a time, and you can remove it.

But for now, the PR only implements Veins as the true reagent holder of mobs.

## Why It's Good For The Game
Our chem system is super outdated, and it should be improved.

## Testing Photographs and Procedure

image

reagent processing is fine.
feeding works well.

image

I monkified that with "keep organs" flag, and it can still have reagents.

## Changelog
:cl:
add: New organ "veins". This is an abstract type of organs, so you'll never see if this exists.
code: For carbon mobs, their reagent holder is now based on their veins organ. There'll be new chem refactor with this change, but it's just a preparation.
code: minor improvement to organ codes.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
This needs more in the why its good for the game section. Why would we actually need this and what benefit does it provide? Is this a framework for the future? As it stands, I don't see why we would want to store reagents in an abstract organ instead of the body, especially since its an organ that doesn't function like the other organs and needs special behaviours to handle its inability to be removed. This complicates things, but what benefit does it provide?
The PR description talks about an upcoming chem refactor, but all of these would work find if they just sent the reagents to the reagents on the mob rather than to some veins organ.
Plus this is definitely going to introducec some bugs with the way things check for and pull reagents.

**Comment by EvilDragonfiend** [comment]
## Why do you post this framework level PR? (Why do we want this PR?)
The main purpose of the PR is basically implementing some basic parts of full chem refactor, but doing the massive rework gives both maintainers and PR makers an excessive level of tiredness to review what's right or not. I found this when I tried the job refactor. I could have brought the full change with this, but I am sure we won't want that.

As long as you're fine with the massive level of change lines, I will go ahead for that version, but like I said, you'll feel a lot of fatigueness.
but also, downstreams need to check what to go first if they'd like to follow the upcomming chem change, because tracking the full change is a lot of tedious hardwork.

## Why do we want a new abstract organ?
In the upcomming chem rework, you can't tell which is the true reagent holder. You can just keep using "reagents" as a true reagent holder, you'll easily overlook the behaviour of the new chem flow.

```dm
// this is actual code that should be implemented, but for now, not until our chem system refactored.
/mob/living/carbon/get_reagent_holder(target_organ=SOMETHING)
	switch(target_organ)
		if(ORGAN_SLOT_VEINS)
			var/obj/item/organ/veins/veins = getorganslot(ORGAN_SLOT_VEINS)
			return veins.reagents
		if(ORGAN_SLOT_LIVER)
			var/obj/item/organ/liver/liver = getorganslot(ORGAN_SLOT_LIVER)
			return liver.reagents
		if(ORGAN_SLOT_LUNGS)
			var/obj/item/organ/lungs/lungs = getorganslot(ORGAN_SLOT_LUNGS)
			return lungs.reagents
		if(ORGAN_SLOT_STOMACH)
			var/obj/item/organ/stomach/stomach = getorganslot(ORGAN_SLOT_STOMACH)
			return stomach.reagents
	//So, this is why this proc exists. "reagents" will be too tynamic to a carbon
```
To be honest, It's fine to keep mobs' body as a reagent holder, but that eventually makes it hard to maintain because you hardly notice which code is supposed to handle mob reagent system.
Imagine there's a weird species having multiple reagent holders, like 3x vines in this PR. And then, can you really tell "reagents" is their true reagent holder?
That's why I am suggesting an abstract organ as veins.

But For now, veins only works as a simple reagent holder and it's the exactly same as the old mob reagent, but there had to be basic changes like this before doing the full rework. The mob reagent system won't be handled as a single in the future.

## Why do we want the changed chemical system?
Chems are known to be an easy source to powergaming, and that's beacuse our chem system is incredibly simple. I even know how to be super competent with chems as much as nanites level, and it's even safer than nanites because chems don't get EMP'ed.

People have been telling chems are easy to make and too powerful. I don't see any issue from it actually. Because chems are "Easy to make, and powerful", making it hard to make or less powerful doesn't really solve the issue. TG implemented Fermichem, and I found it's incredibly tedious to make chems but nothing is actually changed, because chems are still powerful.

The main issue I see was that it's easy to use. Having a lot of downsides is a way to go, but it's difficult to make downsides because the basic chemical system is not good for such things.


## Again, why do we want this PR?
* Bringing the full chem refactor is extreme pain for all of us to review
* We kinda need to refactor chem system to solve the issues

## Misc...
### some beneficial effect of proc addition
You can track which code does a mob interaction. I found there were a lot of funny mob interactions. Did you know you can poison a person with a paper?

### Another solution to merge this framework with not affecting the change to our master
Making a branch of Bee master, and merging it to track the change is fine to me.
then I can open a PR with the new chem refactor to the branch, then you don't have to review a lot of changes again.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Going to have to make a decision here since otherwise this PR will be in limbo forever.

The organ system is for things that:
- Provide functionality to a body
- Need to be removed or added to a body

The organ system should not be used for "abstract" organs which cannot be added or removed, in that case it should just be a datum on the mob which wraps procs for handling.

I also somewhat dislike the conversions we are using towards a reagent holder, the whole point of reagents being on mobs is that it is the reagent holder. The veins organ is a reagent holder holder for mobs which is misusing the organ system and fails to provide us with any plausable or reasonable benefit. I can't think of a future refactor that would rely on reagents being stored in an abstract organ instead of on the body.

If you want to disconnect the concept of a body from a mob, then it has been attempted before with something like `/datum/body`, but using organs is not the way to go about that.

If you want to flow reagents between parts of the body, then mob.reagents can be the pool which reagents go to when they first enter the body, which can then be transfered to other organs by the heart. The liver can then process reagents stored internally. This is a pretty overly complicated process though and increases the processing requirements on mobs for no forseeable gain. (All the changes would be to the backend and would complicate things without actually providing any changes for players, making it pointless.

Since most of the reasoning for the refactor is around balancing chemistry and chemicals, then the design should focus on that rather than the complications of the body system. Splitting reagents across 5 different organs does not address the focuses of your refactor. If you want to nerf chems, then there are simpler ways to go about doing that which are far easier and will be more effective.

**Comment by EvilDragonfiend** [comment]
Closing for now since it needs clean up by the address

**Pull request closed without merging**
