### PR TITLE
Removes hivemind

### LINKED ISSUE #11590: Completely remove hivemind code
Hivemind code is not in use and should be completely removed.

### PR DESCRIPTION
**Pull request by Szyszkrzyneczka**
No one will miss it for no one even remembers it

fixes #11590

## About The Pull Request

Maintaining old code that no one even plays is kinda poopoo
also no one played this like ever
did I mention no one plays this?

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
del: Removes hivemind
/:cl:

### CODE REVIEW

**Comment by Nakalon** [comment]
I don't understand why we gave up on Hivemind, had a lot of fun with it, even thought it was shortlived

**Comment by Nakalon** [comment]
And yes we remember it, its probably a year old at most

**Comment by PowerfulBacon** [comment]
It was removed due to various bugs and issues with plans to re-enable it when it was fixed. It was never fixed.

**Comment by Nakalon** [comment]
> It was removed due to various bugs and issues with plans to re-enable it when it was fixed. It was never fixed.

Thats a shame... Lost work in the end...

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
Removing it doesn't mean it can't come back, it just means that we save some milliseconds on compile times until someone brings it back

**Pull request merged**
