### PR TITLE
pAIs can now ventcrawl

### PR DESCRIPTION
**Pull request by Vexylius**
## About The Pull Request

Personal pAI intelligences can now ventcrawl.
https://forums.beestation13.com/t/give-pai-the-ability-to-ventcrawl/11874

- [ ] Make pAI not able to teleport on top of pipes etc
- [ ] (optional) make it into a downloadable module. 

## Why It's Good For The Game

"I mean why shouldn’t they be able to?"

## Changelog
:cl: Michiru2, Vexylius
add: pAIs can now ventcrawl
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
should be a download module thing tbh

**Comment by Vexylius** [comment]
yeah, good idea

**Comment by Archanial** [comment]
What happens when pai leaves their holoform while ventcrawling? (or is forced to)

**Comment by ToasterBan** [comment]
> What happens when pai leaves their holoform while ventcrawling? (or is forced to)

if we are using vampires for reference they would just pop out right on top of the vent

**Comment by Archanial** [comment]
pais are not vampires

**Comment by Vexylius** [comment]
> What happens when pai leaves their holoform while ventcrawling? (or is forced to)

just tested it - they just pop on top of the tile where that exact pipe segment were. Either when damaged/destroyed or when willingly you deactivate your holoshell. To be honest it works suprisingly well for a one line of code

**Comment by Archanial** [comment]
> 
> 
> > What happens when pai leaves their holoform while ventcrawling? (or is forced to)
> 
> just tested it - they just pop on top of the tile where that exact pipe segment were. Either when damaged/destroyed or when willingly you deactivate your holoshell. To be honest it works suprisingly well for a one line of code

it shouldn't be expected behavior though, it makes you able to exit pipes everywhere you want

**Comment by Vexylius** [comment]
do you have any better idea on how should it work?

**Comment by Archanial** [comment]
Imo they should stay in pipe, and wait for holoform to recharge (or ideally should just go like they were disposed).

**Comment by MitztheKat** [comment]
TBH I like the idea of pAI spies with ventcrawling abilities

**Comment by Rukofamicom** [comment]
> do you have any better idea on how should it work?

Yeah - it shouldn't work at all. PAI destroyed if pipe is destroyed, and coming out of holoform shouldn't be possible in a pipe. Ventcrawling pAI is just all-around an awful idea imo. Ventcrawling is extraordinarily powerful for scouting and spying.

**Review by utilbird — CHANGES_REQUESTED** [review]
Changes suggested above, the pAI shouldn't be able to phase through pipes onto the floor when deactivating it's chasis.

**Comment by Vexylius** [comment]
> > do you have any better idea on how should it work?
> 
> Yeah - it shouldn't work at all. PAI destroyed if pipe is destroyed, and coming out of holoform shouldn't be possible in a pipe. Ventcrawling pAI is just all-around an awful idea imo. Ventcrawling is extraordinarily powerful for scouting and spying. 

Yeah, that's why I, think it shouldn't be merged

**Comment by Vexylius** [comment]
But sure, I'll make those changes... eventually

**Comment by francinum** [comment]
This is a poor idea with a few nasty edge cases with no good solution.

**Comment by Vexylius** [comment]
lol

**Pull request closed without merging**
