### PR TITLE
The :^) has been removed from the tile_opposing_corners (and moved instead as it's own tile decal)

### PR DESCRIPTION
**Pull request by PestoVerde322**
## About The Pull Request

This PR adjust the tile opposing corner to be, in fact tile opposing corner on all 4 dirs, removing the placeholder :^), while moving said pointy face to it's own decal.

Also adds the opposing corners to the tile painter.

## Why It's Good For The Game

Since the tile decal merge there was an unintentional side effect of having shuttles when moving around with the tile_opposing_corners decal to turn into a :^), this PR actually makes the tile_opposing_corners consistent.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

immagine

immagine

</details>

## Changelog
:cl:
tweak: removed the :^) from the tile_opposing_corners and as it's own tile decal
add: added the :^) and the opposing corners to the tile spriter and all the possible corner options
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
Can you add opposing and half corners to the tile sprayer as well? They're supposed to be there just were not added with the decalening

**Comment by Eric-01** [comment]
The /tg/ tile sprayer pull request that was mentioned in PR #7319 as one of the things it ported, shows many more painting options than we currently have available on Bee.

While you're at it, would it be too difficult to add them too? I'm especially looking forward to being able to paint all 4 tiles at once.

**Comment by PowerfulBacon** [comment]
image
This looks broken

**Comment by itsmeow** [comment]
that's because it indeed is

**Review by PowerfulBacon — APPROVED** [review]

**Review by PowerfulBacon — DISMISSED** [review]
See thing above

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
