### PR TITLE
Add descriptions to deployables explaining how to use them

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

Add examine descriptions to deployables explaining how to use them. Simple enough.

## Why It's Good For The Game

I've seen many players be confused by deployables since they've been added, this should help clarify things.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

23-07-17-1689651465-dreamseeker
23-07-17-1689651489-dreamseeker

</details>

## Changelog
:cl:
add: Added examine hints to deployables, to allow players to more easily figure out how to use them.
/:cl:

### CODE REVIEW

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
> Deployables can now be deployed underneath the deploying user.

This was an intentional decision and should not be changed across the board - deployables which are dense should generally not be possible to place under yourself.

It is possible for deployables to ignore density, and #9371 added an additional variable that allows them to ignore only mob density

**Comment by Rukofamicom** [comment]
> Added a (visual) progress bar to deploying a bluespace capsule, to indicate that its in the process of being deployed.

Can you show testing evidence of this just for my curiosity?

They play a sound and change icon state when attempting to deploy, and are ultimately intended to be thrown when activated.

> Added examine hints to deployables, to help players figure out how to use them.

Good change, but again the capsules are intended to be activated and then thrown (like the mining ones) and the descriptions do not convey this.

**Comment by Absolucy** [comment]
@Rukofamicom this PR _only_ adds the examine hints now, no behavior change, especially since it seems the "allow deployment under mobs" thing was added to master already.

**Comment by Rukofamicom** [comment]
For certain items that needed it yes.

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
Update the testing evidence for the capsule and I'll merge if it looks good.

Currently the test shows incorrect text.

**Pull request closed without merging**
