### PR TITLE
Removing Telecomms Access for Station Engineers

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
Removes telecomms access from the default Engineering access.

## Why It's Good For The Game
Station Engineers can very easily enter telecomms on most maps with zero consequences and zero issues to gain the ability to tamper with the APC and gain telecomms blackouts on demand.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>
Simple JSON change, request screenshots if desired.
</details>

## Changelog
:cl:
balance: Removed telecomms access for Station Engineers.
/:cl:

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
Then let's remove the ability to order weapons from cargo techs because they can be easily fit in the inventory and used by antags.

**Comment by Tsar-Salat** [comment]
Making Tcomms CE only is not a good idea. 
Most experienced players who actually *know* how to fix tcomms, or those with the most engineering hours, are not going to be playing CE 24/7. Infact, I've found most CE's are rather Dunning-Kruger about atmos and tcomms.

If you're sole concern is what an antag can do, I think that is misplaced.

**Comment by ColonelOrion** [comment]
Every time tcomms has gone down in the past year, it's been an engie that fixed it, not the CE. Salat is right.
Comms outages will be less incentivized when the AI code extraction doesn't send out a comms message.

**Comment by MarkusLarsson421** [comment]
Do note that Engineers can still easily enter it via hacking, AI assistance or more prominently; Jaws of Life. This will mostly change their expected access. If they don't normally have access to telecomms, they won't be allowed to be there and it'll count as trespassing. If there is an issue with telecomms, no one will stop them from actually fixing telecomms.

**Comment by Fronsis** [comment]
> Do note that Engineers can still easily enter it via hacking, AI assistance or more prominently; Jaws of Life. This will mostly change their expected access. If they don't normally have access to telecomms, they won't be allowed to be there and it'll count as trespassing. If there is an issue with telecomms, no one will stop them from actually fixing telecomms.

Then... the Traitor is also gonna do that, they can just hack in, ask AI or use... Jaws of life

Like they're engineers it makes **sense** to be the ones that repair T-comms, the CE is the boss and should be delegating tasks not being the only ones responsable for T-comms. Comms outtages or comms bombing are already a pain in the ass, no need to make everything more iserable if your worry is that ''They can toggle t-comms on-off on demand, specially in a stealth manner'' as you said in #11049  you might as well address that particullary issue with the remote signaller. (Can you even take it off from the apc so you can have it as evidence?)

**Comment by MarkusLarsson421** [comment]
The traitors can still do it, and I will still do it. But they would no longer be able to walk in and do it on Box Station with zero risk, zero consequences, and a major reward.

You can take the signaler off the APC, but for that, someone has to actually get inside telecomms, which has yet to happen.

**Comment by MarkusLarsson421** [comment]
Closing this after overwhelming negative feedback, perhaps another time and place.

**Pull request closed without merging**
