### PR TITLE
Gives Centcom a facelift after 1 million years

### PR DESCRIPTION
**Pull request by Marshmellow105**
## About The Pull Request

Puts some makeup on Centcom after being neglected for far too long.

## Why It's Good For The Game

Centcom looks pretty dated, I just wanted to update the tiling and room designs without changing any critical spaces.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

ccERT

ccCARGO

ccSEC

ccCOURT

ccCUSTOMS

ccTHUNDER1

ccTHUNDER2

ccARRIVAL

</details>

## Changelog
:cl:
add: centcom stamp and centcom vendor
tweak: updates centcom
add: one singular extra dir sprite for the offset ramp decal
/:cl:

### CODE REVIEW

**Comment by TsunamiAnt** [comment]
holy based??

**Comment by Rukofamicom** [comment]
I have only one question:

Can ~~admins~~ admirals exist there during rounds with something to do or at least entertain themselves with entirely IC while they wait around for station communications and/or faxes yet?

**Comment by Marshmellow105** [comment]
they can hang out in this little book nook and read

image

or channel their inner papers please at the revamped customs checkpoint

image

or cook in the now functional again thunderdome kitchen/bar

image

they could even look around for the three little easter eggs I left (debatably IC aside from the intern announcer guy)

I could throw an arcade machine in there somewhere too so they can fight zorpblorp minions or whatever too.

**Comment by ClownMoff** [comment]
image

Not a big fan of the floor choice on this being the same one for the whole room

**Review by Rukofamicom — APPROVED** [review]

**Pull request merged**
