### PR TITLE
[READY] Pubby Pipe Net Multi Layer Project

### PR DESCRIPTION
**Pull request by SergeiKoralev**
## About The Pull Request

This PR is intended to give Pubby station multi-layer distro and scrubber piping and remove wall pipes and cables. 

Debugging checks completed
>Debug verbs check plumbing.
>Dumped a can of hypernob into scrubbers to check for scrubber-distro cross connection.
>External airlock functionality testing.

## Why It's Good For The Game

Wall pipes are a scourge on mapping and should be eradicated

## Changelog
:cl:
edit: pubby scrubber and distro pipes are now on different layers. Distro on 1, Scrubbers on 3.
/:cl:

### CODE REVIEW

**Comment by SergeiKoralev** [comment]
I've done preliminary debug testing, but as usual with changes of this scale a test merge is probably in order.

**Comment by SergeiKoralev** [comment]
pubbypipe

**Comment by SergeiKoralev** [comment]
I received no complaints during the round on sage.

**Comment by 4rchibald** [comment]
@Vasily2013 Great PR and I really appreciate the work that went into it

But what happened in atmos?
Pubby atmos was always quite bad, especially when it comes to area where air gets pumped to distro (not having separate room for it, lacking freezers etc), with each PR we should still try to get things improved but this PR somehow made it worse. You really made mess with those layers making any atmos project so much harder since people can't just relay on changing to layer 1 or 3 and be sure they are clear on any collisions), there's less visual clarity in what goes where (just look at distro to waste, not only its in atmos desk for some reason but its all hidden under tiles, pump is the only thing popping above) and features like mix to distro pump got removed.

Thing is, literally all changes you made compared to current Pubby atmos seem unnecessary, you could have just add layer manifolds on distro and waste as they are leaving atmos, so unless you are willing to actually redo Pubby atmos to make it better I would suggest you just limit changes to adding layer manifolds just like it was done on most if not all other maps 

Other than that I really like the PR, you really did a great work and as far as I have seen during test merge there were no issues, at least not any catastrophic ones

**Comment by SergeiKoralev** [comment]
I knew I shouldn't have deleted the master of pre-change atmos yet. Let me go ahead and address a few key points. 



> You really made mess with those layers making any atmos project so much harder since people can't just relay on changing to layer 1 or 3 and be sure they are clear on any collisions),

I'd contest that I haven't removed significant valuable space from the atmospherics area. I made a purposeful attempt to keep layer usage away from the eastern section of atmospherics, and the primary changes were made to the air mix to distro section to remove a significant number of under-window pipes. This allows greater flexibility without deconstruction of any windows. I have prepared a helpful diagram to demonstrate that I for the most part have not encroached on the primary build area in atmos. 
image



> there's less visual clarity in what goes where (just look at distro to waste, not only its in atmos desk for some reason but its all hidden under tiles

This I will concede. Distro to waste will be moved to visible piping in my next commit. For the most part though the only factor that would affect immediate visual clarity are uninterrupted distro and scrubber lines going into the room which are hidden.



> features like mix to distro pump got removed.

A mix to distro pump is not a hard thing to install, so if you're an AI you'll just have to be slightly more clever with your plasmaflood techniques. Calling mix to distro a feature I personally would not agree with, as there is minimal use for it other than grief.



> you could have just add layer manifolds on distro and waste as they are leaving atmos,

The point of the PR was to remove wall embedded pipes, which the initial distro and scrubber piping was. It needed to be replaced as per the scope of the PR.



> just limit changes to adding layer manifolds just like it was done on most if not all other maps

Serious response: Just because it was half-assed on other maps does not mean that I am going to half-ass my own work. Pipes going through walls is sloppy and lazy.

Joke response: Understood, removing all pipes from pubby atmospherics in order to enable a build-your-own atmos center which requires round start setup to provide the station with breathable air.

**Comment by SergeiKoralev** [comment]
I've made some minor corrections. Features include...

- White highlighting of tiles with sub-floor piping.
- Made nothern distro and scrubber lines visible pipes.
- Made junction for distro to scrubber visible.
- Made layer manifolds under doors leading to office visible so the pipe doesn't duck down under the floor for one tile.

Note: there are no hidden/visible variations of the vents and scrubbers, so you're stuck with 'em.

image

**Comment by francinum** [comment]
This PR has been testmerged for a significant amount of time to no significant complaints.

**Review by francinum — APPROVED** [review]

**Pull request merged**
