### PR TITLE
Dissable the space wizard academy from gateway missions untill its fixed

### PR DESCRIPTION
**Pull request by ItsTisme**
## About The Pull Request

Temporarily comment out  the space wizard academy from available gateway missions until it gets redone by some one(or myself)

## Why It's Good For The Game

As it stands now, it's trivial to depressure the entire academy and grab all the loot without any sort of struggle. Even player spawned wizard head masters die at the whole no air.

## Changelog
:cl:
del: Wizard academy has been dissabeld from gateway missions for now
/:cl:

### CODE REVIEW

**Comment by Isy232** [comment]
All the gateway missions need a LARGE rework. Wizard is one of the most functional, just poorly balanced. You either cheese it for the loot or die in 1 shot from a fireball.

I think academy is better to permanently remove as it is just plain bad design.

**Comment by PowerfulBacon** [comment]
The main issues is 
 - Super easy to cheese
 - If you don't cheese it the AI wizards 1 shot you with their fireball spells unless you have magic immunity
 - The die of fate literally destroys the flow of the round when it is obtained
 - If a spawned wizard doesn't want you to get it, they can just hide the die
 - The more balanced items (but still powerful) are almost never gone for, since you can just cheese the thing for the best item (infinite die of fate)

**Comment by ItsTisme** [comment]
> 
> 
> All the gateway missions need a LARGE rework. Wizard is one of the most functional, just poorly balanced. You either cheese it for the loot or die in 1 shot from a fireball.
> 
> I think academy is better to permanently remove as it is just plain bad design.

Very true, but the wizard one has one of the best items and is one of the easiest to cheese. Compared to the  other missions this one feels to me the worst by far

**Comment by PowerfulBacon** [comment]
I agree with this, sicne the die of fate literally destroys the flow of the round, practically guaranteeing at least 1 wizard spawn

**Comment by francinum** [comment]
Discarding my personal musings on the idea of having map-based challenges *stored in the public eye*, This needs to be merged due to the map being fundamentally shit to play without this cheese.

**Review by francinum — DISMISSED** [review]

**Comment by Crossedfall** [comment]
Asked the bois to make a comment on this, but I guess they forgot. I've applied the changes on the server, but this needs to alter both Golden's config and Sage's config before we can merge it into the repo. Once you apply it to https://github.com/BeeStation/BeeStation-Hornet/blob/master/config/Sage/awaymissionconfig.txt it'll be good to go.

**Comment by ItsTisme** [comment]
> 
> 
> Asked the bois to make a comment on this, but I guess they forgot. I've applied the changes on the server, but this needs to alter both Golden's config and Sage's config before we can merge it into the repo. Once you apply it to https://github.com/BeeStation/BeeStation-Hornet/blob/master/config/Sage/awaymissionconfig.txt it'll be good to go.

not sure when the commit gets visible here put I pushed it aswel, should see something soon(TM)

**Review by Crossedfall — APPROVED** [review]

**Comment by zeskorion** [comment]
> Asked the bois to make a comment on this, but I guess they forgot. I've applied the changes on the server, but this needs to alter both Golden's config and Sage's config before we can merge it into the repo. Once you apply it to https://github.com/BeeStation/BeeStation-Hornet/blob/master/config/Sage/awaymissionconfig.txt it'll be good to go.

i commented in the channel when you asked, as did the others, iirc.

**Pull request merged**
