### PR TITLE
Battle Royale fixes

### PR DESCRIPTION
**Pull request by Mat05usz**
## About The Pull Request

Stops people from joining as posibrains/golems etc during Battle Royale, also you no longer can manually turn on a posibrain when sillycone sentience is disabled.

In addition, now the mode kills ALL living mobs, to prevent people from disconnection and then connecting again to avoid the wipe.

## Why It's Good For The Game

Borgo spam during Battle Royale is cringe, don't be cringe.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: Mat05usz
fix: You can no longer join as borgs/golems etc during Battle Royale
fix: All living mobs are cleared when BR starts, no more disconnecting to avoid the wipe
/:cl:

### CODE REVIEW

**Comment by RDS88-beeman** [comment]
au contraire, borgo spam is based since they don't technically have to listen to you. If you're sick of it just join as posi and flashspam the guy to death.

**Comment by Mat05usz** [comment]
> au contraire, borgo spam is based since they don't technically have to listen to you. If you're sick of it just join as posi and flashspam the guy to death.

Sadly what usually happens (or at least what I observed) is borgs teaming up with the guy who made them.

**Comment by RDS88-beeman** [comment]
yes that's because they're usually grateful for getting a chance to play

**Comment by Mat05usz** [comment]
> yes that's because they're usually grateful for getting a chance to play

And what stopped them from partaking as a normal player?
If you wanted to take part in the BR, you could've simply clicked 'yes'. Joining afterwards only to teamup with someone as a borgo (which is even more OP in this mode than usually) is simply unfair for other players.

**Comment by RDS88-beeman** [comment]
i was implying it was people that died because they're bad or ran into the wrong person

**Comment by Mat05usz** [comment]
> i was implying it was people that died because they're bad or ran into the wrong person

Ah well, I usually notice borgs being created right when grace period ends, so noone had a chance to die yet, but
anyways BR isn't supposed to work like that. You die, you leave.

**Comment by ivanmixo** [comment]
Also make the initial BR mob deletion swoop include disconnected players, people dodging it by disconnecting just ruins it. Like we had a ling dodge the deletion and it wasn't neat.

**Comment by Mat05usz** [comment]
> Also make the initial BR mob deletion swoop include disconnected players, people dodging it by disconnecting just ruins it. Like we had a ling dodge the deletion and it wasn't neat.

I thought about doing that and then I forgot lol

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
