### PR TITLE
the nuke disk now has the letters N and T instead of funny lines

### PR DESCRIPTION
**Pull request by Ratvarr**
## About The Pull Request
funny line gone
N T new, I will soon do this with ALL THE DISKS HAHAHAHAHHA

## Why It's Good For The Game
NT likes slaping there name on **everything**
image
image
both versions in both files (items_and_weaoins.dmi and module.dmi)
this is also my first PR
## Changelog
:cl:
tweak: NT has now relabeled the nuke disk to show its 100% NT, however, the syndicate found out and rapidly did it to the fake disks they sell
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Personally I think the lines look better since they represent the data on the disk

**Comment by Bastian0930** [comment]
i'd prefer this as telling the difference between a genetics disk and a nuke disk is sorta hard.

**Comment by PowerfulBacon** [comment]
Actually I can see what you mea  with the similarities between the plant data disk and the nuke disk

**Review by PowerfulBacon — APPROVED** [review]

**Comment by zeskorion** [comment]
> i'd prefer this as telling the difference between a genetics disk and a nuke disk is sorta hard.

note that that is an intentional feature

**Comment by Blueturbo47** [comment]
This is gonna turn stale and I don't think anyone is voting on it anymore, its 29 up to 22 down on the discord, time to merge this?

**Comment by qwertyquerty** [comment]
fix conflicts

**Comment by Ratvarr** [comment]
HA
I DIDENT THINK IT WORKED IN THE END BUT IT DID

**Comment by Ratvarr** [comment]
by stoping merge conficts i went down a rabbit hole of unholy errors
I'm going to make this into a new PR to *attempt* to fix it in a few hours

**Pull request closed without merging**
