### PR TITLE
Actual antag token in the beecoin shop

### PR DESCRIPTION
**Pull request by ike709**
##  Changelog
:cl:
add: You can now buy an actual antag token from the beecoin shop. Yes, really. It's under OOC.
/:cl:

### CODE REVIEW

**Comment by Moccha-Bee** [comment]
very based???????

**Comment by Sparrowbird611** [comment]
Wait, this isn't a joke?

**Comment by 123chess456** [comment]
why not just enable antag rep which is already a perfectly working feature. people might actually play sec for once too.

**Comment by ike709** [comment]
@123chess456 Antag rep is currently being subjected to a council vote.

**Comment by qwertyquerty** [comment]
Last I knew @cthulhuonice vetoed this

**Comment by eLeCtrOssSnake** [comment]
:thonk: Idk, I guess it's ok feature.

**Comment by ike709** [comment]
image

Strong player support. And like I said, it takes about 1,500 hours of playtime to get it.

**Comment by CthulhuOnIce** [comment]
Merge if, and only if, beecoins never become purchaseable with real world money.

**Comment by Cenrus** [comment]
Is this the "give Cenrus free antag" PR?

**Comment by ike709** [comment]
@CthulhuOnIce Deal.

@Cenrus You know it baby.

**Comment by optimumtact** [comment]
nice pay 2 win

**Comment by ike709** [comment]
@optimumtact I'll give you 20 antag tokens for a fiver.

**Comment by 123chess456** [comment]
@optimumtact Just because you're being an antag headcoder >for free doesn't mean that it's somehow more OK for you to murderbone people with cobbychems.

**Pull request merged**
