### PR TITLE
Lets slimes use custom emotes

### PR DESCRIPTION
**Pull request by benbot16**
No idea why this wasn't the case before.

## About The Pull Request

This lets slimes use custom emotes.

## Why It's Good For The Game

Slime RP is good.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
add: Slimes can now use custom emotes.
/:cl:

### CODE REVIEW

**Comment by hotimep** [comment]
/me does slime sign language to say "open the door asshole"

**Comment by benbot16** [comment]
> /me does slime sign language to say "open the door asshole"

Well you could do that, I haven't really seen it happen in practice with any other mobs that might have that issue (like elites, lightgeists, or regular people that are mute).

Although me does have a check for mimes out of all things, which is kinda funny.

**Comment by CydiaLamiales** [comment]
/me burps loudly
After eating all the monkey in the virologist's pen

**Review by itsmeow — APPROVED** [review]

**Comment by itsmeow** [comment]
/me i am going to coderbus you out of existence if you don't open this slime pen

**Comment by PowerfulBacon** [comment]
I'm not entirely convinced this is a good idea, since people are going to abuse the freedom to communicate with people rather than do actual RP emotes.

**Comment by itsmeow** [comment]
i do not trust the playerbase with this

**Comment by PowerfulBacon** [comment]
most other mobs can talk though

**Comment by benbot16** [comment]
> most other mobs can talk though. My problem with this is how there are people who already use _me with some pretty bad ways to convey information. Like an IPC with "_ displays an image of hurt on their screen"

Yes, but I still haven't seen it happen often enough to actually be a problem (excluding some mimes being shitters, but that's just mimes). And if people are abusing RP stuff, they should be getting slapped instead of locking off options for everyone else because a few people can't behave.

**Comment by Tyranicranger4** [comment]
> i do not trust the playerbase with this

I get not trusting the playerbase with some things, I'm pretty jaded myself in that regard, but this is kind of ridiculous.

For once I actually find myself agreeing with the "it's an administrative issue, not a code one" argument. People misusing *me emotes to convey information when they normally shouldn't be able to is already something we deal with on a relatively frequent basis. It's rarely an issue with simple mobs though, if anything it's usually people trying to communicate after they got flashbanged.

**Comment by itsmeow** [comment]
meh whatever

ban abusers

**Pull request merged**
