### PR TITLE
Removes the cause of all problems

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Removes felinds.

## Why It's Good For The Game

Fucking everybody hates them, if you want to play as a furry go to TG or citadel.

## Changelog
:cl:
fix: fixed the genepool
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
@qwertyquerty  what did i do wrong

**Comment by Oshibkka** [comment]
معلومه نکنه هست خ عین یکپارچه

**Review by ike709 — CHANGES_REQUESTED** [review]
I'm not a fan of outright removing them from the code. It's only a one-line config change to remove them from the roundstart races.

**Comment by ghost** [comment]
> I'm not a fan of outright removing them from the code. It's only a one-line config change to remove them from the roundstart races.

Well only kev and qwerty can do that.

**Comment by qwertyquerty** [comment]
Nah I can't, only kev and crossedfall can, so  bug them not us

**Pull request closed without merging**
