### PR TITLE
Bluespace cannon update

### PR DESCRIPTION
**Pull request by Dejaku51**
## About The Pull Request
 - integrated battery charged from a wire connected to the back of the BSA
 - sounds for windup and shooting
 - during the windup there are sparks around the place where cannon will shoot
 - back part of the BSA shows charge in quarters also makes a sound each quarter charged (unique for full)
 - now requires 5MW instead of 2MW
 - bsa doesn't have charge speed limit
 
 might also change the laser to use particles in the future
 

## Why It's Good For The Game
BSA using APC in the area doesn't make sense for such a big gun
big gun like that wouldn't be silent when shooting
more vfx and sfx good

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/user-attachments/assets/a9a015f8-5eaa-425f-a1ac-f25c2df0f150

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
add: BSA now has a windup with sparks on target location
add: BSA now has integrated battery and is powered with a cable attached to the end of BSA
add: BSA shows amount of charge in quarters on the capacitor part of the BSA
balance: BSA requires 5MW to shoot
soundadd: BSA now makes a sound when winding up and shooting
soundadd: BSA makes a sound on quarters charged with unique one on full charge
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
Roughly how many shots can be fired in a full charge and can it be expanded?

**Comment by Dejaku51** [comment]
> Roughly how many shots can be fired in a full charge and can it be expanded?

you need full charge to shoot once, can't be expanded

**Comment by MarkusLarsson421** [comment]
Pretty please? Let us connect additional SMES to it directly or such!

**Comment by Dejaku51** [comment]
> Pretty please? Let us connect additional SMES to it directly or such!
> 
> Edit: Will adding more power output charge it faster perhaps? Such as four upgraded fully charged SMES set to max output.

more power means faster charging yes, even currently there is no charge speed limit

**Comment by Rukofamicom** [comment]
> no charge speed limit

If it ends up being abused regularly this is something that can be added later. 
This looks pretty cool imo

**Review by Rukofamicom — APPROVED** [review]

**Review by Rukofamicom — COMMENTED** [review]
The only thing I'd suggest,, but not worth blocking over is that the sparks at the target location be blue instead of normal sparks.

**Comment by PowerfulBacon** [comment]
I trust ruko's review of the code

**Pull request merged**
