### PR TITLE
Small Radstation atmos fix and changes. 

### PR DESCRIPTION
**Pull request by Geatish**
## About The Pull Request
Fixed the atmos storage shutters not opening.
Removes the glass from the designated atmos area and rerouted undertile distro pipes around it. 

## Why It's Good For The Game
Shutters not being openable is bad. Tiles being where they aren't supposed to be any is bad. N2 in windows to gas chambers is bad, since they would contaminate the gas chambers if you were ever to destroy/remove the window. 
The glass floor is not fire proof nor is it removable through conventional means, meaning that any atmos tech who wants to build a burn chamber there first has to burn or blow away the glass. The distro piping being unexpectedly in the way of atmos projects was is not fun at all.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

https://github.com/user-attachments/assets/0db69bf3-35f5-41da-897e-a34981bfecac

(note: the missing manifold pipes are there, the t-ray is just bugged. 

</details>

## Changelog
:cl: Geatish
tweak: Removed glass floor from the designated atmos work area and rerouted undertile distro piping around it. 
fix: Rad station atmos storage shutters now work. Tiles in space next to gas miners have been removed. Plasma windows in gas chambers no longer spawn with N2. Also removed extra APC in xenobio
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
> The glass floor is not fire proof

Swap it for rplasmaglass. I set that to be fireproof.

These mapchanges specifically were added by Floria, the map owner, so I assume it was part of their design for adding them.

**Comment by Geatish** [comment]
> Swap it for rplasmaglass. I set that to be fireproof... These mapchanges specifically were added by Floria, the map owner, so I assume it was part of their design for adding them

Fair enough, I've asked Flora about this, since i think it looks kinda odd when you're building something on top of them and you can't really hide pipes under tiles.  

>I recommend marking the turfs with white decals, or put catwalk tiles over them. This will make them easily visible.

image

This is how it looked like before, having ANY distro pipes there is hell. Trying to do anything with the thermogen will 80% of cases force you to remove and reroute the distro piping. It doesn't make any sense for them to be anywhere in the designated zone, id rather just shrink and mark off the zone instead of labeling tiles as "you can't use these."

**Comment by Geatish** [comment]
Well shits fucked after pigeons map freeze and i cant seem to fix it. Some maint gotta step in.
Flora also stated that its fine if i remove the glass, since its not pretty once you start laying down pipes there.

**Comment by Geatish** [comment]
Redoing the pr

**Pull request closed without merging**
