### PR TITLE
Mercury Brain Damage Increase

### PR DESCRIPTION
**Pull request by DatBoiTim**
## About The Pull Request

Doubles Mercury's Brain Damage.

## Why It's Good For The Game

Brain Damage is uncommon. Brain traumas, doubly so. Figured making a chem have more brain damage would allow for more approaches for antagonists.

## Changelog
:cl: DatBoiTim
balance: Increased amount of Brain Damage done by Mercury
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
No

**Comment by utilbird** [comment]
Mercury is a default dispenser chem, wouldn’t it be better to buff the brain damage of other chems?

**Comment by ghost** [comment]
> Mercury is a default dispenser chem, wouldn’t it be better to buff the brain damage of other chems?

Yeah what the nerd said!

**Comment by DatBoiTim** [comment]
> > Mercury is a default dispenser chem, wouldn’t it be better to buff the brain damage of other chems?
> 
> 
> 
> Yeah what the nerd said!

How bout this? I'll visit chems that do brain damage individually. Consider this PR the first of a series of tweaks.

Done chem by chem to make for acceptable atomization, and allow for chem by chem community feedback.

**Comment by utilbird** [comment]
Ehhh, this makes Mercury pretty damn powerful. I think some of the more advanced chems could use a rework but a default chemical shouldn’t be this strong (relatively speaking). Brain damage can also be a bit of a pain to fix :p

**Comment by DatBoiTim** [comment]
> Ehhh, this makes Mercury pretty damn powerful. I think some of the more advanced chems could use a rework but a default chemical shouldn’t be this strong (relatively speaking). Brain damage can also be a bit of a pain to fix :p

I did say doubled brain damage but do you know how much it would do if this merges?

It sounds less busted if I said: increased Mercury brain damage to 2.
But my English brain go _brrrrr_

**Comment by utilbird** [comment]
I know, I read the code. 2 brain damage is still twice as fast as one though

**Comment by ghost** [comment]
Brain damage is like genetic damage. It sucks and is unfun

**Comment by Isy232** [comment]
Buff or add a braindamage chem.

Meth used to be the brain damage chem but it got nerfed because people were using meth as a weapon to kill others by OD'ing them, causing brain melt.

**Comment by ike709** [comment]
Bad PR, mercury is really common.

**Pull request closed without merging**
