### PR TITLE
Removes confusion from *spin and *flip

### PR DESCRIPTION
**Pull request by PowerfulBacon**
Whoops didn't mean to make a branch on the main repo, remind me to delete it after.

## About The Pull Request

This is pretty stupid considering things like the de-sword and other weapons cause you to spin and this hasn't been properly coded to account for that.
There's no worth in keeping it around either since we don't allow macros anyway so we don't have the *spin *flip spam that TG has.

## Why It's Good For The Game

Using stuff like the de-sword, pool noodles, wrestling, dancing will no longer give you confusion all the time. *spin and *flip no longer add confusion to you when using them.

## Changelog
:cl:
del: Removed confusion from the *spin and *flip emotes.
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Is there no easy way to only set `intentional` to true when the user actually runs the emote themself?

**Comment by ike709** [comment]
Actually didn't https://github.com/BeeStation/BeeStation-Hornet/pull/5669 fix this?

**Comment by Archanial** [comment]
> Actually didn't #5669 fix this?

it did

**Review by francinum — APPROVED** [review]

**Comment by ike709** [comment]
🔑

**Pull request closed without merging**
