### PR TITLE
Ports a bunch of stuff

### PR DESCRIPTION
**Pull request by yorii**
## About The Pull Request

[TODO]

## Why It's Good For The Game

Updates are good, I'll finish writing this later.

## Changelog
:cl:
add: Added new things
tweak: tweaked a few things
balance: rebalanced something
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
/:cl:

### CODE REVIEW

**Review by francinum — CHANGES_REQUESTED** [review]
missing CL
Seems to be made of several TG commits merged into one, this isn't how we allow ports.

**Comment by yorii** [comment]
> missing CL
> Seems to be made of several TG commits merged into one, this isn't how we allow ports.

That's why I marked it as a draft, I'll figure out how to make this proper later :)

**Comment by PowerfulBacon** [comment]
DNM Due to lighting changes, need to go through and compare with the hybrid beelighting. If hybrid beelighting toned down to moving light sources only fails to perform well enough or has some major underlying issue then DNM will be lifted.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
This PR ports a bunch of completely unrelated PRs all as one. Atomize this down.

**Comment by yorii** [comment]
> This PR ports a bunch of completely unrelated PRs all as one. Atomize this down.

Yeah I'll split it up a bit.

**Comment by yorii** [comment]
Don't need this anymore

**Pull request closed without merging**
