### PR TITLE
[Port] Add 5 new gases, related interactions/items/content, the return of Freon+several related fixes and ports

### PR DESCRIPTION
**Pull request by DatBoiTim**
## About The Pull Request
Ports https://github.com/tgstation/tgstation/pull/53013
Ports https://github.com/tgstation/tgstation/pull/50153
Ports https://github.com/tgstation/tgstation/pull/49821
Ports https://github.com/tgstation/tgstation/pull/52957
Ports https://github.com/tgstation/tgstation/pull/54263
Ports https://github.com/tgstation/tgstation/pull/53781

Adds the following gases:
Healium
Proto Nitrate
Zauker
Halon
Hexane
Brings back Freon and associated bits

-Healium: a red gas, stronger than n2o if breathed, with healing properties
-Proto Nitrate: a green inert gas if breathed but with different reactions with various gases at high temperatures
-Zauker: a black deadly gas if breathed that decomposes very fast if exposed to N2 even at minimal amounts
-Halon: a light blue gas that when used in a fire it will suck up the O2 and will help cool the room, helping fighting the fire
-Hexane: a purple gas that has the ability to filter from the air plasma and n2o, useful to clean distro from the harmful gases quickly
-Healium Crystal: a reddish crystal that when broken will explode cooling the room and removing the plasma from the air (act like a grenade)
-Proto Nitrate Crystal: a greenish crystal that when broken will explode refilling a space with O2 and N2
-Zauker Crystal: a blackish crystal that when broken will explode dealing damage around it
-Supermatter Interactions

## Bringing Back Freon
Freon is a key part of the use/reactions for these 5 gases, and I already decided to substitute hydrogen for CO2(This caused some design problems) so I was not about to compromise further! However, it has been fixed a decent bit!

## Why It's Good For The Game
Adds content to atmos, usable for good internally and throughout the station, and ~~money for cargo~~ ~~tools for security~~ tools for evil as well.
Brings back a long requested gas and its associated things, including several fixes for it.

## Testing Photographs and Procedure

<details>

<summary>Gas Appearance</summary>

Freon
Freon!

Proto-Nitrate
ProtoNitrate!

Healium
Healium!

Zauker
Zauker!

Halon
Halon!

Hexane
Hexane!

</details>

<details>

<summary>Player Effects</summary>

</details>

## TO-DO:

- [x] Finish Up Porting
- [x] Testing Basic Gas Appearance
- [x] Testing Effects Toward Player
- [ ] Testing Reactions
- [ ] Other Testing
- [ ] Stage Wiki Changes
- [ ] Testmerge?
- [ ] Make Wiki Changes permanent

## Changelog
:cl: DatBoiTim, Ghilker, Silicon
add: 5 new gases
add: Healium : made from Bz + Freon + cold, it knocks people down but have healing properties
add: Proto Nitrate : made from pluox and H2 + heat, it has different reaction with a bunch of other gases
add: Zauker: made from hypernoblium + stimulum around 0°C, it has heavy damage if breathed but is decomposed rapidly by N2
add: Halon : made from bz + trit + cold, it reacts with O2 at high temperature removing it and cooling the air, helping putting out fires
add: Hexane : made from bz + H2 + cold, it reacts with plasma and n2o and removes them from the air mix, filtering them.
imageadd: canister sprites, gas sprites
add: crystal from gases formation and reaction
add: supermatter interactions
add: Zauker bounty
add: all 5 gases are up to selling
add: Added cargo worth for freon
tweak: changed the value of hot ice (increased to mythril level)
tweak: increased the amount of plasma released from hot ice to 150 moles per sheet
tweak: increased the amoung of plasma (chem) from hot ice to 300 moles per sheet in grinding
tweak: changed hypernob canister sprite to differenciate it from the freon one
balance: made hot ice easier to make (range of temperatures to 120-160 K and halved the rate of cooling of freon/o2 reaction)
fix: fixed hot ice not showing up over 34 sheet in the stack
fix: fixed negative temperature issue caused by bad coding the cap, increasing the minimum temperature and changed the energy used by the reaction
fix: freon should not have you stuck immobilized anymore
add: Added Freon
add: Added Hot Ice
add: Added interactions of freon with SM and reactions with other gases
refractor: hexane properties are on the reagent and not the breathing
del: hexane no longer grand you dchat hearing
add: hexane makes you heat resistant (can still die due to pressure)
del: Hexane no longer deals brain damage
fix: fixed some atmos reaction from having negative temperature
fix: reaction no longer runtime
tweak: Cyrion-B is now named Zauker
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
I distinctively remember freon being removed in 2018 because people kept opening it in public hallways and turning the entire area into a frozen wasteland.

**Comment by DatBoiTim** [comment]
> I distinctively remember freon being removed in 2018 because people kept opening it in public hallways and turning the entire area into a frozen wasteland.

This doesn't even bring back on map cannisters. You have to fucking make it.

**Comment by BrumalLake** [comment]
h2 is a prerequisite

**Comment by DatBoiTim** [comment]
> h2 is a prerequisite

FUCK

**Comment by DatBoiTim** [comment]
> h2 is a prerequisite

Are you sure? Cause in those freon fix ports I see no reference to hydrogen

**Comment by BrumalLake** [comment]
it's in reaction for the formation of some and also you need to do the gas ids for auxmos

**Comment by DatBoiTim** [comment]
> it's in reaction for the formation of some and also you need to do the gas ids for auxmos

Oh the new gases? Yes, but I subsituted CO2 like we do for fusion.

**Comment by BrumalLake** [comment]
there's also some more follow ups such as cyrion b being renamed to zauker and such as well as halon or hexane one of the two being removed for being similar

**Comment by DatBoiTim** [comment]
> cyrion b being renamed to zauker

Oh jeez I just looked for that PR. That's a fucking grim reference.



> hexane one of the two being removed for being similar

This was due to them pigeon holing hexane into only purifying plasma(ergo being a firefighting fill in)

**Comment by DatBoiTim** [comment]
I think that's all the ports to do for this(without inheriting too many balancing changes)

**Comment by DatBoiTim** [comment]
Oh son of a bitch

**Comment by DatBoiTim** [comment]
> you need to do the gas ids for auxmos

Yeah I need to figure this out

**Comment by DatBoiTim** [comment]
I am now able to compile and run without issue.

Testing Phase begins

**Comment by DatBoiTim** [comment]
Unsure if messing with Healium reagent so that it handles healing counts as a proper port or not so i will err on the side of caution and keep that bit of code as originally written

**Comment by DatBoiTim** [comment]
Reactions may be a while. I need to become actually robust with atmospherics.

**Comment by DatBoiTim** [comment]
Oh god dammit. ICON CONFLICTS?

**Comment by DatBoiTim** [comment]
This can wait.

**Comment by DatBoiTim** [comment]
Ok I have someone who's gonna test the shit since I suck at atmos.

**Comment by DatBoiTim** [comment]
https://tenor.com/view/its-alive-gene-w-ilder-gif-14865163

**Comment by Tsar-Salat** [comment]
> Ping a maintainer if you want this re-opened, closing in order to clean up the PR list a bit.

Tim said his workload is full. I will see if I can continue this with his permission.

Screenshot_20230330_201627

I will create my own iteration of the port in a bit when I have the time.

**Comment by DatBoiTim** [comment]
Just commenting to confirm that I’ve passed this along, as supplement to the screencapture already provided.

From: Tsar-Salat ***@***.***>
Date: Thursday, March 30, 2023 at 8:20 PM
To: BeeStation/BeeStation-Hornet ***@***.***>
Cc: DatBoiTim ***@***.***>, State change ***@***.***>
Subject: Re: [BeeStation/BeeStation-Hornet] [Port] Add 5 new gases, related interactions/items/content, the return of Freon+several related fixes and ports (PR #6137)

Ping a maintainer if you want this re-opened, closing in order to clean up the PR list a bit.

Tim said his workload is full. I will see if I can continue this with his permission.

[Screenshot_20230330_201627]<https://user-images.githubusercontent.com/62388554/228992288-9bedbc81-e015-4b3e-81d7-988024be1385.jpg>

I will create my own iteration of the port in a bit when I have the time.

**Pull request closed without merging**
