### PR TITLE
[PORT] Antique laser gun changes

### PR DESCRIPTION
**Pull request by Therealdoooc213**
## About The Pull Request

Ports https://github.com/tgstation/tgstation/pull/67606

The captains antique lasergun now fires a hitscan projectile that does 16 damage and uses 85 energy per shot (previously 100), this allows for 11 shots before depletion.

## Why It's Good For The Game

I believe that beestation has a severe lack of weapon diversity, especially among laser guns. There are almost no hitscan weapons currently and i believe that needs to change. The new hitscan projectile that the antique uses makes the weapon more striking while still retaining its usefulness as a weapon.

I think everyone can agree the current antique sprite is pretty bad, the new one looks very retro instead of the bulkiness of the old one.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

https://github.com/user-attachments/assets/54be75c5-c024-4e41-ae86-a2890d06f7e2

</details>

## Changelog
:cl: Imaginos16 Therealdoooc
add: The captains antique laser gun now fires hitscan projectiles
balance: The antique laser gun now does 16 damage
imageadd: new antique lasergun sprites
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I heavily dislike hitscan lasers, they are completely unavoidable and are just a bit weird when only 1 gun fires a different type of the same laser for some reason. I'm mostly indifferent on the sprite, but these changes are together so I'll treat them as one 🗝

**Comment by Rukofamicom** [comment]
I was pinged for input on this one in discord:

I'm strongly against hitscan ranged weapons in general. The PKA is the only one we currently have and it thankfully isn't abused much due to range limitations.

**Comment by Geatish** [comment]
The new sprite look awful imo, for being an antique laser gun it looks extremely modern and high tech, way more so if you compare it to the hos's gun, which is supposed to be the newest top of the line stuff. 
Also as bacon and ruco said, hitscan is just stupid powerful with no real way to doge. The captains gun is supposed to be a more self defense weapon than a validhunt weapon, this is just going to promote the cap to get involved in standard sec matter, where he often shouldn't be in the first place

**Comment by Therealdoooc213** [comment]
One day...

**Pull request closed without merging**
