### PR TITLE
Adds Dark FairyGrass Floor tile

### PR DESCRIPTION
**Pull request by GregTheEgg42069**
## About The Pull Request
Adds Fairy Grass floors that removes light in such a way that it is dark without being shadow shroom level dark

## Why It's Good For The Game
Fairy Grass had all the types of "glow" variants  except shadow_emission  #5637 

## Changelog
:cl:
add: dark fairy  grass
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
this is probably going to lag the absolute fuck out of the server

**Comment by Archanial** [comment]
> 
> 
> this is probably going to lag the absolute fuck out of the server

why would it?

**Comment by GregTheEgg42069** [comment]
also i dont know how to embed images but i have some pictures of how dark it can get

**Comment by GregTheEgg42069** [comment]
Shadow FLoor

**Comment by GregTheEgg42069** [comment]
without shadow eyes

**Review by Archanial — APPROVED** [review]

**Pull request merged**
