### PR TITLE
Adds the batong, a toy version of security batons

### PR DESCRIPTION
**Pull request by LodedDiper69**
## About The Pull Request
As said above, the batong has the same sprites as a normal baton and can even be inserted into a charger (though it won't do anything). Also included in arcade prizes and thus cargo toy crates.

## Why It's Good For The Game
More toy variety is always good, plus it can be used to play pranks like with lasertag guns.

## Changelog
:cl:
add: Adds a new chargable toy batong
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
image

**Comment by LodedDiper69** [comment]
The code has been patched up and the batong now works on my test server. There aren't any more bugs I could spot.

**Comment by FortSumter** [comment]
We need more toys just scattered about the station just to make sec go insane. One of my favorite gags I did was I found a suspicious duffle bag and filled it with the syndicate bomb drinks and went around asking people if they want a bomb. I then asked a secoff if they wanted a bomb, they pre-emptively took out their disabler and said yes, and then got super pissed when I handed him a drink.

**Comment by PestoVerde322** [comment]
Question, have you tried to put a baton in the charger and what would happen?

**Review by Dejaku51 — APPROVED** [review]
batong

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
