### PR TITLE
Finishes the Mobility Refactor

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Status
- https://github.com/tgstation/tgstation/pull/45952

Limbs
- https://github.com/tgstation/tgstation/pull/52929
- https://github.com/tgstation/tgstation/pull/53374

Removing update_mobility
- https://github.com/tgstation/tgstation/pull/54078
- https://github.com/tgstation/tgstation/pull/54183

Fixes
- https://github.com/tgstation/tgstation/pull/54320
- https://github.com/tgstation/tgstation/pull/54411

## About The Pull Request

Status:
- The player checkhealth status now says if a limb is disabled.

Limbs A:
- Makes losing limbs event-based, as opposed to going through several long proc chains.
- Losing your legs gives you the floored trait, as long as not flying/floating.
- Losing your arms and legs gives you the immobile trait, as long as not flying/floating.
- Flying, even if you dont have limbs, will never apply limbless slowdown
- hacky get_legs_ignore() deprecated.
- renamed the dumb `disabled` to `bodypart_disabled`, so you can actually find it in searches
- relaymove() and driver_move() parameters properly typed and set.
- canBeHandcuffed() replaces the hacky get_arm_ignore()
- Miscellaneous Fixes

Limbs B:
- Fixes a bug with the previous PR in which paralysis did nothing. lmao
- kills is_disabled()
- changes several variable changes into events
- bodypart_disabled boolean'd
- Reduces an unnecessary amount of updates, as only extremity limbs really suffer from being disabled

Removing update_mobility
- Title

Fixes
- Stuff that Rohesie broke, that they later fixed

Additionally:
- I had to clean up how stamina was applies & heals a tiny bit. I made sure to inherit bacon's changes where Stamina heals slowly after the first second, rather than clearing in 10 like tg does. I think its clean, but tell me if the math looks wrong.

TODO:

- [x] Initial
- [x] Stamcrit applied correctly by weapons
- [x] Stamcrit heals slowly (previous behavior not overwritten)
- [x] Ensure no unintentional wound code ported over
- [x] All mobility traits apply as expected
- [x] 515 compatibility
- [x] Paraplegic quirk people cannot walk
- [x] Firefighter carrying still works

## Why It's Good For The Game

This *was* an atomization, but the recent change to contributing.md and something bacon said changed my mind. We are finishing this in one pr. No more broken mobility, no more incorrect procs. One PR, fixing it here.

Mobility atomization, more responsive mobility overall
Mobility is a pretty bad proccall, as we need to call an update_x proc literally whenever something changes, or it wont take effect.

This makes that not happen, it just took 15 months.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Disabler Stamcrit

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/165dde81-5871-4585-857c-584d68d7159d

Stungun stamcrit

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/5561a433-ce36-47dc-97a7-e5327fe87f39

Limb removal & nuggeting

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/5fc72f55-3326-420a-a346-4b3b9169cc01

Firefighter carrying

image

Roundstart Paraplegics cannot walk

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/70353e13-9872-4e2c-8749-f24a51850a33

</details>

## Changelog
:cl: rkz, rohesie, tralezab, dwasint
add: You can now see if a limb is disabled through checkhealth (HUD, healthanalyzer, ghostscan)
tweak: being limbless while flying will never apply the limbless slowdown (because you are movin just fine, right?)
fix: minor stamina fixes in the way it is applied & healed
code: kills a lot of unecessary limb updating
code: makes Limb removal & disabling event-based. Extricate it from update_mobility
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
#10078 is included in this, that should be merged prior to this one.

This will also need a "Needs TestMerge" label. Ive tested all the traits, which have all applied as expected. Stamina applies & heals as expected.

However, this PR is big enough that I think it would be smart to TM it

**Comment by Tsar-Salat** [comment]
Can confirm no intentional wounds code crossover as of 694274b

**Comment by Tsar-Salat** [comment]
Going to redo my tests after the psyphoza merge

**Comment by Tsar-Salat** [comment]
Ive gotten it to the point where everything basically works as expected... except parapalegia doesnt fucking do anything. At all. 

Stamcrit works
missing limbs work
adding the limbs back work 

guhhh

**Comment by Tsar-Salat** [comment]
lets try... again.

**Comment by Tsar-Salat** [comment]
Im now just finishing the refactor. No more atomizations. Lets just fix it in this PR and be done with it.

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
I trust whatever my old review said

**Comment by Tsar-Salat** [comment]
please dont break please dont break please dont break

**Pull request merged**
