### PR TITLE
Make alpha plane invisible while blind

### LINKED ISSUE #6213: [Feature Request] Give Blind trait vision circle night vision
Why:
- The small vision circle of the blind trait, as far as I know, is meant to represent the culmination of the trait user's senses other than vision. In which case, it doesn't really make sense that someone IC blind in a dark room, cannot see anything OOC and has to turn a light on IC.
______
Why is it good:
- Adds a bit more of a realistic experience to blind characters on the station
- Less blind people in an unlit room with PDA lights on (bonus of scaring people?)
______
Why is it bad:
- I honestly can't think of anything.  (Maybe some sicko trying to somehow powergame blindness?)

### PR DESCRIPTION
**Pull request by Jeff-3**
## About The Pull Request
Closes #6213 The alpha plane is set to invisible so no lighting changes will appear for those with the blind trait. This is a simple fix that only affects alpha, but it should suffice for most common situations that otherwise looked weird.

## Why It's Good For The Game
Blind people should not be able to see light

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

blind lit

blind dark

</details>

## Changelog
:cl:
fix: the blind can no longer see
/:cl:

### CODE REVIEW

**Comment by yyzsong** [comment]
Nice time to powergame blindness

**Comment by Crossedfall** [comment]
Should just be dark all the time, to be honest. What if we just like... Removed the vision circle entirely and gave blind people the ability to scream really loud so they can echo-locate toolboxes in the room? Could do a cool effect where the outlines of everything fades in and then after a few seconds they'd fade back out. They wouldn't be able to tell exactly what people look like or exactly what's in a given spot, but they could figure it out... With enough screaming.

I can "see" it now... 

Guy screams! x56

**Comment by Jeff-3** [comment]
> Should just be dark all the time, to be honest. What if we just like... Removed the vision circle entirely and gave blind people the ability to scream really loud so they can echo-locate toolboxes in the room? Could do a cool effect where the outlines of everything fades in and then after a few seconds they'd fade back out. They wouldn't be able to tell exactly what people look like or exactly what's in a given spot, but they could figure it out... With enough screaming.
> 
> I can "see" it now...
> 
> Guy screams! x56

Coder monkeys are busy, just make everyone pinky promise to close their eyes

**Comment by MNarath1** [comment]
> > Should just be dark all the time, to be honest. What if we just like... Removed the vision circle entirely and gave blind people the ability to scream really loud so they can echo-locate toolboxes in the room? Could do a cool effect where the outlines of everything fades in and then after a few seconds they'd fade back out. They wouldn't be able to tell exactly what people look like or exactly what's in a given spot, but they could figure it out... With enough screaming.
> > I can "see" it now...
> > Guy screams! x56
> 
> Coder monkeys are busy, just make everyone pinky promise to close their eyes

actually this sounds interresting.......

**Review by Archanial — APPROVED** [review]

**Pull request merged**
