### PR TITLE
Buffs Changeling Armour

### PR DESCRIPTION
**Pull request by Penwin0**
## About The Pull Request

Increases melee and bullet resistance to 40 increases bom resistance to 25 and cleans up bio resistance

## Why It's Good For The Game

Its currently a 2 DNA point mutation which gives you a subpar set of armour (worse than security vest) and slows you down, worthless buy in its current state

## Changelog
:cl:
balance: Increased Changeling Armour resistances
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — DISMISSED** [review]
The chitinous armour had less armour than the chitinous space suit.. what?

**Comment by Penwin0** [comment]
Makes a lot of sense i know

**Review by r1ks-iwnl — COMMENTED** [review]
https://github.com/BeeStation/BeeStation-Hornet/blob/c71d65f64c4c807021e7bc43388c69ab06f4fb6f/code/modules/antagonists/changeling/powers/mutations.dm#L495
Forgot the helmet stats

**Comment by eeSPee** [comment]
People forget ling armor blocks shove knockdown (like riot suit)

**Comment by PowerfulBacon** [comment]
> 
> 
> People forget ling armor blocks shove knockdown (like riot suit)

So? Its still shit

**Comment by utilbird** [comment]
Shoving doesn't matter nearly as much when you have a flesh scythe stuck to your arm

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
