### PR TITLE
Updated HoS cloak sprite

### PR DESCRIPTION
**Pull request by Naevii**
## About The Pull Request 
Nanotrasen finally stopped undercutting HoS fashion budget and equiped HoS with refreshed version of his cloak. 

## Why It's Good For The Game
Now you can catch crime and look fabulous.

New-old comparision (top is new)

greytide version

Hos

HoS hardsuit

## Changelog
:cl:
tweak: Updated HoS cloak sprite
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
Epic

**Comment by PowerfulBacon** [comment]
This looks great, putting to vote

**Comment by Isy232** [comment]
Epic, now it looks more glowing, like it was stained with the blood of all the tiders you beat up.

**Comment by PowerfulBacon** [comment]
This looks good and with a rate of 21:1 already I don't see this failing

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
