### PR TITLE
[PORT] Animated Locker Doors from Yogstation

### PR DESCRIPTION
**Pull request by MNarath1**
## About The Pull Request

Ports the PR https://github.com/yogstation13/Yogstation/pull/9706 made by monster860 only difference from the original PR is that i made personal cabinets lockers non animated as those have 2 sided doors also some values got changed a bit.
Of course all credits for this goes to the original coder monster860
here a small video about it from the original PR
https://cdn.discordapp.com/attachments/134720091576205312/755151212759875706/2020-09-14_15-39-58.mp4
https://cdn.discordapp.com/attachments/605179594617782302/764257807884091412/locker.mp4
## Why It's Good For The Game

Fancy locker animations

## Changelog
:cl:
add: Makes locker doors animated
/:cl:

### CODE REVIEW

**Comment by MNarath1** [comment]
ignore the first row of commits i made a bit of an mess on how i created my branch so i had to manually change back somes stuff so that it wouldn't also include stuff from my other PR

**Comment by PowerfulBacon** [comment]
I think it looks a little out of place personally and slightly off. Having linear transition from open to close doesn't really work when the locker door is coming outwards and I think the animation needs speeding up a bit

**Comment by MNarath1** [comment]
@PowerfulBacon I think i can do something about the transition playing around with the squish value seems to help but i am not to keen on the last part of the animation if i do that trough its hardly noticable on a higher speed i will see if i can iron that out

**Comment by MNarath1** [comment]
https://cdn.discordapp.com/attachments/605179594617782302/764474855105757234/2020-10-10_15-07-25.mp4 is this better?

**Comment by MNarath1** [comment]
with this the animation is now slightly faster 0.5 seconds so its down to 2 seconds for normal locker and 3 seconds for freezer i think the animation looks better on higher squish values trough

**Comment by MNarath1** [comment]
https://cdn.discordapp.com/attachments/605179594617782302/764497072233119750/2020-10-10_16-34-43.mp4 ok but i still feel that this might be too fast for the lockers hmm

**Comment by MNarath1** [comment]
https://cdn.discordapp.com/attachments/605179594617782302/764524871723253790/2020-10-10_18-26-53.mp4 brought the speed down to 2.5 seconds again it just looks better that way

**Comment by AnjelicaChaykovsky** [comment]
looks very trippy   but i like it

**Comment by theboy6545** [comment]
Personally ive never been a fan of the locker animations, i just prefer it swapping from open to closed.

**Comment by Bastian0930** [comment]
We dbd now boys

THAT FUCKING MEG IS RUNNING QUICK AND QUIET

**Comment by Wilchenx** [comment]
looks bloody awful m8

**Comment by ike709** [comment]
Vote passed.

**Pull request merged**
