### PR TITLE
Adds Unit Testing: No Glass Placed on Space

### LINKED ISSUE #11409: [Unit Test]: Glass must not be placed on space
See title

### PR DESCRIPTION
**Pull request by Programs-The-Station**
## About The Pull Request

Space was already implemented but the issue was not closed. Modified existing map lint to check for groundless turfs.

Closes  #11409

I made it search for "groundless turfs" so no openspace on multiz maps. This can be changed to just space tiles if we desire.

## Why It's Good For The Game

More unit testing better

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

In progress.

</details>

## Changelog
:cl:
code: Modifies map lint: no glass on groundless turfs.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
There are 2 different types of lints for maps. Ones placed in `tools/maplint` and ones in the unit tests. Unit tests are for complex lints that should only run on actual maps (disposals check, things that need wider context other than just 1 tile).

If you have a lint that only needs a single tile to run, then add it to `tools/maplint`.

I actually requested this lint as part of another PR, so I think somebody might have already made it.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
See `tools/maplint/lints/space_check.yml`

This check is a bit more advanced, but could be rolled up into a maplint (which would then check all maps rather than just station maps). You would need to expand this by adding in all the groundless turfs manually

This is a good PR though, and being able to check more is better.

**Comment by Programs-The-Station** [comment]
Well good. It already caught a problem. Echostation has two windows on openspace. I'll fix those up.

**Comment by Programs-The-Station** [comment]
You've got to be kidding me, already? 

Ha.

**Comment by PowerfulBacon** [comment]
It got me too

**Comment by Programs-The-Station** [comment]
Should be good to go, @PowerfulBacon

**Review by PowerfulBacon — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
Good stuff

**Pull request merged**
