### PR TITLE
Yet Another Kilo Rework PR

### PR DESCRIPTION
**Pull request by Sinestia**
## About The Pull Request

A looot of changes to Kilo cumulatively, this basis was zesko's https://github.com/BeeStation/BeeStation-Hornet/pull/2715 . That original PR went stale but I like the concept of kilo so I wanted to take it up again.

 The differences I've included so far: Tweaked the brig physicians area a bit, give them a locker, make it more aeshetically consistent
And the warden's access has been fixed, so sec officers can't just walz into his room either. 

 I hope to be able to respond to any other issues that are brought up. 

## Why It's Good For The Game

Map, now bee can have more maps than just Metastation, 2 worse versions of Metastation, and pubby. 

## Changelog
:cl:
add: Kilo is back and now votable!
tweak: Massive changes to kilo.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Is it optimized for fastmos?

**Comment by Sinestia** [comment]
> Is it optimized for fastmos?

That appears to have been done in Zesko's PR. Firelocks have been replaced, cycling happens for externals, etc..

**Comment by PowerfulBacon** [comment]
imo the old security was much better, if not for the lack of a brig pysician's room and I am sad to see my favourite part go 
image
I think the sand added so much flavour.
In my opinion, Zesko's changes improved the gameplay a lot, but removed a lot of the flavour which was the only good part of the map since the gameplay of kilo fucking sucks, but the map is just so cosy and nice to be on.

**Comment by Sinestia** [comment]
> imo the old security was much better, if not for the lack of a brig pysician's room and I am sad to see my favourite part go
> image
> I think the sand added so much flavour.
> In my opinion, Zesko's changes improved the gameplay a lot, but removed a lot of the flavour which was the only good part of the map since the gameplay of kilo fucking sucks, but the map is just so cosy and nice to be on.

Yeah, I do agree aesthetically. I also kind of just like the idea of the peanut gallerying to happen from the dorms windows, it's just something different and neat. 

Other thing I noticed too was the maintenance. Obviously old kilo maints wouldn't be done if it was a brand new map, but it being largely replaced with generic templates also feels like a loss. I don't think it's even possible to create unique per-map templates in addition to being a lot of work so eh. 

Although U can't blame zesko too much for changing security the way he did. Kilo's kind of cramped and doesn't leave that much space for modification (literally part of the charm.) I miiight take a crack at changing sec again to be a bit more like its old self, but my primary goal with this is addressing issues so it could be added back.

**Comment by heepox** [comment]
I like kilo for one thing and one thing only. white ship dock has its own asteroid and is not connected to the station.

**Comment by PowerfulBacon** [comment]
Closing due to merge conflicting for a while now, feel free to reopen once merge conflicts are resolved.

**Pull request closed without merging**
