### PR TITLE
Fixes Instruments t2

### PR DESCRIPTION
**Pull request by MNarath1**
## About The Pull Request

I resetted my branch on the PR https://github.com/BeeStation/BeeStation-Hornet/pull/5136 and forgot to recommit a needed change that would ensure only mobs get used inside the second for loop.

## Why It's Good For The Game

Now actually fixes instruments

## Changelog
:cl:
fix: fixes my own mistake on instruments
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Why are non mobs in that list? Remove the as() from the for loop above

**Review by PowerfulBacon — APPROVED** [review]

**Comment by MNarath1** [comment]
> 
> 
> Why are non mobs in that list? Remove the as() from the for loop above

yeah realized that too after looking over this with a bit of sleep behind it

**Comment by PowerfulBacon** [comment]
This seems fine but the code there is pretty bad to begin with, 15 range view check. I wonder if they could use proximity monitors if refactored.

**Comment by MNarath1** [comment]
> 
> 
> This seems fine but the code there is pretty bad to begin with, 15 range view check. I wonder if they could use proximity monitors if refactored.

hmm good question but this would probably cause simmilar issues like beforehand as the proximity monitor would not fire for anything inside an object probably but the initial seach could maybe be butched a bit might look into this on a later date. Or is crossed getting called for objects inside objects?

**Comment by MNarath1** [comment]
> 
> 
> This seems fine but the code there is pretty bad to begin with, 15 range view check. I wonder if they could use proximity monitors if refactored.

Looks like this won't work primarly cause of how proximity monitor works so it won't call for any object that has not called crossed yet in its range so unless a mob moves after like someone went into its range there is no way to tell it is there.
Same goes for like lockers and crates etc we can't really see them unless they get moved and second problem a object with a proximity monitor that  is held inside another one like if you hold it in your hands won't  get called on the movement around it so even trough it should get called when said mob moves it will not do anything.

**Pull request merged**
