### PR TITLE
QM gets loud radio

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
Grants the Quartermaster loud mode

## Why It's Good For The Game
qm gets a mic at roundstart and theyre basically a head so why not?

also the qm now gets a unique headset

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

qmset_ground

qmset_inspect

</details>

## Changelog
:cl:
add: Qm gets a loud-mode headset!
imageadd: Qm gets a unique headset
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
QM doesn't belong to science and hence shouldn't have their radio. Shaft miners have it because they perform science duties as well as cargo duties.

**Comment by itsmeow** [comment]
agreed, close

**Comment by etherware-novice** [comment]
hm, can i just keep the qm headset in? I like how it looks

**Comment by itsmeow** [comment]
Image for reference

image

If you update the CL and PR title, sure.

**Comment by etherware-novice** [comment]
wait actually! i can change the pr into one giving the qm a loud mode headset

**Comment by itsmeow** [comment]
This is already addressed in #6833

**Comment by etherware-novice** [comment]
thats 4 months old come on!

**Comment by itsmeow** [comment]
Just close this PR please

**Comment by etherware-novice** [comment]
w h y

**Comment by itsmeow** [comment]
:key:
Closed because it's already addressed in #6833 and the original purpose of the PR has already been changed in the first place.

**Pull request closed without merging**
