### PR TITLE
[PORT] Return of The New Donk Pockets 2: Electric Boogaloo.

### PR DESCRIPTION
**Pull request by Moccha-Bee**
## About The Pull Request
After a generous donation from the S%n#@!&e, Donk Co. is pleased to announce its new line of products!
Original pr:tgstation/tgstation/pull/48310
Credits to coconutwarrior97

Thanks to Farquaar for the sprites and some of the coding work!

## Why It's Good For The Game
Variety is the spice of life, and the new donk pockets are here to help!

## Changelog
/:cl:
add: Added several new donk pocket types, and boxes, including sprites for each of course. Spicy-Pocket,Teriyaki-Pocket, Pizza-Pocket,Honk-Pocket,Gondola-Pocket and Berry-Pocket. This includes re-organizing them from the OTHER section in snacks_pastry.dm to a donk pocket section. Thanks to Farquaar for the box icons and some of the code! As well as latots for the donk pocket icons.
add: Added a Donk Pocket Variety crate, for 2000 credits, which includes 3 randomly selected donk pocket box types, excluding Gondola-Pocket.
add: Added a recipe for each new Donk Pocket type.
add: Added the new Donk Pocket types to the maint loot table.
add: Donk Pocket loot spawner object, credit to TheVekter for that, which was then added into the kitchens of all the main maps.
tweak: All Donk Pockets now follow the same naming scheme of X-Pocket.
add: Added craftable Donk Pocket boxes.
/:cl:
image

### CODE REVIEW

**Comment by DatBoiTim** [comment]
Good PR but how are Gondola pockets obtained? And how rare?

**Comment by Moccha-Bee** [comment]
> Good PR but how are Gondola pockets obtained? And how rare?

They can be ordered from cargo, and they have tranquility aka pacifier drug, and iirc can only be obtained that way.

**Comment by DatBoiTim** [comment]
> > Good PR but how are Gondola pockets obtained? And how rare?
> 
> They can be ordered from cargo, and they have tranquility aka pacifier drug, and iirc can only be obtained that way.

So it’s a separate cargo order item. Nice.

**Comment by Moccha-Bee** [comment]
> > > Good PR but how are Gondola pockets obtained? And how rare?
> > 
> > 
> > They can be ordered from cargo, and they have tranquility aka pacifier drug, and iirc can only be obtained that way.
> 
> So it’s a separate cargo order item. Nice.

Its a cargo order that comes with a bunch of other donk pockets.

**Comment by DatBoiTim** [comment]
> > > > Good PR but how are Gondola pockets obtained? And how rare?
> > > 
> > > 
> > > They can be ordered from cargo, and they have tranquility aka pacifier drug, and iirc can only be obtained that way.
> > 
> > 
> > So it’s a separate cargo order item. Nice.
> 
> Its a cargo order that comes with a bunch of other donk pockets.

Change log says gondola pockets are excluded from that, you may need to edit it to reflect that

**Review by DatBoiTim — DISMISSED** [review]
Cargo boutta put the Chef outta business :flushed:

**Comment by Moccha-Bee** [comment]
> Cargo boutta put the Chef outta business 😳

death to the chef

**Comment by Moccha-Bee** [comment]
before anyone asks we already have the donk pocket icons

**Comment by ghost** [comment]
I thought you could make gondola pockets with gondola meet

**Comment by Moccha-Bee** [comment]
> I thought you could make gondola pockets with gondola meet

the original recipe for gondola pockets included an ingridient called "faggot" but i don't think that's an actual item in game

**Comment by ghost** [comment]
> the original recipe for gondola pockets included an ingridient called "faggot" but i don't think that's an actual item in game

It is meatball you uncultured swine

**Comment by Moccha-Bee** [comment]
> > the original recipe for gondola pockets included an ingridient called "faggot" but i don't think that's an actual item in game
> 
> It is meatball you uncultured swine

the same way cigarrete is a faggot lmfao

**Review by zeskorion — CHANGES_REQUESTED** [review]
still doesnt have the actual donk pocket sprites

**Comment by Moccha-Bee** [comment]
> still doesnt have the actual donk pocket sprites

https://github.com/BeeStation/BeeStation-Hornet/blob/master/icons/obj/food/food.dmi

image

yes we do

**Review by zeskorion — APPROVED** [review]

**Comment by zeskorion** [comment]
vote will pass

**Pull request merged**
