### PR TITLE
Signal cleanup

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Organises the giant signals file into subfiles.

## Why It's Good For The Game

Organises signals into relevant files which makes it easier to find what components affect something or are used by a module and allows for easier modularisation of signals.
If you want to know what signals are available to /atom, look in atom_signals.dm. 

## Testing Photographs and Procedure

image

Compiles.
Considering that this only moves things around and does a single rename, the only issues that are possible are compilation errors.

## Changelog
:cl:
refactor: Refactors the signals files to split them down into submodules.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Already man

**Review by Penwin0 — APPROVED** [review]
Looked through this on my phone on the metro (would not recommend) but everything appears to be in it's proper place, I'll look at it again this evening if it's not merged by then

**Comment by PowerfulBacon** [comment]
don't get mugged my guy

**Comment by Penwin0** [comment]
How the fuck do you manage to get mugged in such a crowded place

**Comment by Penwin0** [comment]
Looked through this again, everything looks to be in proper place

**Comment by PowerfulBacon** [comment]
Because people can wait until the train stops, grab your phone and sprint off before the doors shut.

**Comment by Penwin0** [comment]
> Because people can wait until the train stops, grab your phone and sprint off before the doors shut.

You are underestimating how packed the place is and how paranoid I am about that sort of stuff, much easier targets out there

**Review by itsmeow — APPROVED** [review]
Literally just moves stuff into files and renames three signals

easiest merge ever

**Review by ike709 — APPROVED** [review]

**Pull request merged**
