### PR TITLE
Adds flyperson, apid, and squid languages to synthetic base languages.

### PR DESCRIPTION
**Pull request by KittyNoodle**
## About The Pull Request

Synthetics (IPCs, borgs, ais, other silicon life) can now understand and speak slime, apid, flyperson, squid, and podperson languages. In addition, they can now understand but not speak drone.

## Why It's Good For The Game

Programming oversight bad, also the ai and borgs should be able to see what the drones are talking about.

## Changelog
:cl:
add: Synthetics can now understand and speak more languages.
add: Synthetics can now understand but not speak drone.
/:cl:

### CODE REVIEW

**Comment by RDS88-beeman** [comment]
why play curator
when can be robot?
why study books
when can have metal brain?
I like this, as an IPC player. but seriously this is a lot of languages. Can't wait to chant ominously in ryl'ehan though

**Comment by BrumalLake** [comment]
> 
> 
> why play curator
> when can be robot?
> why study books
> when can have metal brain?
> I like this, as an IPC player. but seriously this is a lot of languages. Can't wait to chant ominously in ryl'ehan though

r'lyehian looks ridiculous in this game and bears no resemblence

**Comment by KittyNoodle** [comment]
it makes total lore sense for an AI and its borgs to at least understand all languages of the species that nanotrasen formally hires.

**Comment by KittyNoodle** [comment]
@RDS88-beeman curator still has access to all uncommon languages. If this is merged drone will be the only language that the ai can understand, but still cannot speak.

**Comment by St0rmC4st3r** [comment]
Drone language should not be understandable by AIs. This will mess with already shaky drone laws.

**Comment by KittyNoodle** [comment]
I specifically decided to make it understandable but not speak-able, this mirrors what other servers do to make drones more useful to engiborgs.

**Comment by PowerfulBacon** [comment]
Slime and podperson they shouldn't have.
The other ones are for the species rather than them so its arguable if they should have them.
In any case IPC shouldnt have them but AI only.

**Comment by KittyNoodle** [comment]
well oozelings are a race employed by nanotrasen and their language is slime, but I agree with you on the podperson language.

**Comment by BrumalLake** [comment]
bruh who thought it was a good idea to give oozelings slime
now we're here 5 months in the future and ipcs wont even need rainbow slimes to speak it

**Comment by RDS88-beeman** [comment]
you can speak it with rainbows?

**Comment by ToasterBan** [comment]
just because some nanotrasen crewmembers speak these languages means all silicon's should know em

this is litterly just silicon/IPC powercreep, as if they needed to be any more powerful

**Comment by KittyNoodle** [comment]
why the hell would nanotrasen give station synthetics some but not all languages of the species that nanotrasen formally hires.

**Comment by ToasterBan** [comment]
> why the hell would nanotrasen give station synthetics some but not all languages of the species that nanotrasen formally hires.

I don't care about lore, it's gameplay above lore and this is just making a feature that some already call overpowered more powerful, also the other languages silicon's have are for the most common spicieses found on the station so you could say that nanotrasen still hadn't fully translated the language

**Comment by super12pl** [comment]
Non-AI silicons shouldn't be given additional languages in the first place.
In general we should stop giving out languages like candy.
What's the point of having languages if average crewmember and silicon knows 3 and 11 of them respectively?

**Comment by BrumalLake** [comment]
nnoo my loree

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Only slime languages should be able to speak and understand slime.
IPCs shouldnt get to know them all, since they are a species with their own species language, however it does make sense for AIs and Borgs to understand them.

**Comment by BrumalLake** [comment]
this is a species change

**Comment by KittyNoodle** [comment]
marked charges as complete because I have no idea how to use git.

**Comment by PowerfulBacon** [comment]
I still think the IPCs should use a seperate language to AI that can't hear everything

**Comment by Archanial** [comment]
Unathorized race changes

**Pull request closed without merging**
