### PR TITLE
Adds a bunch of DS items

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

gives deathsquad troopers their own, gloves, advanced magboots, combat jumpsuit, combat mask, and changes the DS hardsuit sprite and tweaks the special ops officer/admiral jacket and beret

## Why It's Good For The Game

because why not.

## Changelog
:cl:
add: Added a bunch of new DS gear
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Still conflicts. Still don't know how you screwed it up.

**Comment by qwertyquerty** [comment]
Literally the same PR

**Comment by ghost** [comment]
i changed the branch

**Comment by ghost** [comment]
i dont know whats wrong

**Pull request closed without merging**
