### PR TITLE
Comms console messages now produce a sound to admins.

### PR DESCRIPTION
**Pull request by St0rmC4st3r**
## About The Pull Request

Messaging centcomm or the syndicate or requesting nuke codes via the communication console now actually makes a morse code sound so that the admins would not lose it in the pile of messages that the chat is.

## Why It's Good For The Game

And why not? Why does the chaplain (undoubtedly the holiest person on the station) have a higher chance of being heard by the gods on a day-to-day basis but a **state of the art space station** captain will be ignored by his employers when he uses **a very expensive quantum communication channel that is intended to be used in the case of an emergency**?

Also someone _please_ make separate sound effects for the syndicate and nuke code request. Currently it is the same sound effect.

## Changelog
:cl:
soundadd: Added new morse code sound effect.
admin: Admins now hear a morse code sound whenever centcomm or the syndicate is messaged via comms console.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
9 seconds of beeping is going to get really annoying

**Comment by St0rmC4st3r** [comment]
> 9 seconds of beeping is going to get really annoying

Oh yes, it migh. But it definitely will not be missed. I will be happy if someone proposes a better sound.

**Comment by PowerfulBacon** [comment]
Shorten it to 2 or 3 seconds so it's more bearable

**Comment by francinum** [comment]
1.5x the WPM and shortened the message itself. Gets the point across, and out of the way.

https://file.house/6mxm.wav
30/30/220 : SS13

**Comment by St0rmC4st3r** [comment]
Thanks, @francinum, this is how I wanted it to sound! Not long, but really catches attention.

**Comment by St0rmC4st3r** [comment]
I guess, ready for merging?

**Comment by ike709** [comment]
Personally I think it's incredibly annoying.

**Comment by St0rmC4st3r** [comment]
@ike709 the new one or the old one? Also once again, it should be so that it won't be ignored.

**Comment by ike709** [comment]
Both

**Comment by PowerfulBacon** [comment]
I agree with Ike, since it's going to be used a lot something thats not a high pitched tone and is soft to the ears and under 1 or 2 seconds would be for the best.

**Comment by St0rmC4st3r** [comment]
Okaaaay ::(
I will look for a better sound.

**Comment by francinum** [comment]
*looks at the pray sound*

**Comment by francinum** [comment]
If you want it quieter it should be quite easy to remaster in audacity

**Pull request closed without merging**
