### PR TITLE
[ready] Pubby Engine Easy Mode

### PR DESCRIPTION
**Pull request by SergeiKoralev**
## About The Pull Request

This is a mapping improvement PR based on the factor that engineers don't know how to run a TEG properly. It is supplemental to #1565 for the purposes of making it harder to blow up the SM and still generate power for the station. Primary changes include addition of a burn chamber, addition of burn and SM chamber venting capability for when the engineers still somehow manage to light the SM on fire, and some changes to the plumbing and cooling structure of the engine. Someone will likely still figure out how to blow this up, but the "wrench everything in and max all the pumps" test worked.

image

## Why It's Good For The Game

Engineers don't understand anything other than "radiation go brrrrr" so they explode and the station looses power whenever there is a TEG SM setup. Hopefully this will reduce the number of kabooms. 

## Changelog
:cl:
tweak: alters Pubby's SM/TEG setup.
fix: engineers should now be capable of not exploding on Pubby even if they're incompetent.
/:cl:

### CODE REVIEW

**Comment by SergeiKoralev** [comment]
Something went fucky with a few other map files. Let me figure those out and then this will be fully ready.

**Comment by SergeiKoralev** [comment]
Alright, don't know where those came from, but purging them works.

**Comment by SergeiKoralev** [comment]
FUUUUUUUUUUUUUUUUU---

**Comment by KubeRoot** [comment]
This seems like a neat change, looks like something you'd build for power generation as a project during the round.

I'm worried about the gas mixer on the input to the burn chamber - if both inputs are supplied and it doesn't get the exact right ratio, one of the inputs can get clogged, further clogging the filters and backing up the cooling loop for the SM.
Because of this, I feel like it'd be better to not have the mixer at all and simply connect the pipes together, since it seems like the only reasonably option is to have all of the filtered gasses going in.

I also want to mention the possibility of filtering out a gas from the burn output, could be used to introduce CO2 into the SM gas mix from burnt plasma. I think there's enough space to add that in on your own, however.

**Comment by SergeiKoralev** [comment]
> one of the inputs can get clogged, further clogging the filters and backing up the cooling loop for the SM.

Due to low operating temperatures this likely won't be an issue, if it does become an issue then it's easily rectifiable if the engineer notices what is happening. Both endurance tests I've run so far are around the 1-1.5 hour in duration and even with base 50/50 or a heavily oxy rich mix it hasn't become a problem.



> I also want to mention the possibility of filtering out a gas from the burn output, could be used to introduce CO2 into the SM gas mix from burnt plasma.

This can totally be added independently of the round start setup. It's fairly simple in terms of piping overall. Gotta leave the engineers something to do, right?

**Comment by KubeRoot** [comment]
Now that I think about it, might be out of the scope of this PR, but the cooling loop gas filtering is still done in the opposite way compared to other maps - having you choose which gasses to remove instead of which gasses to keep. Should this maybe be changed to be like the other maps?

**Comment by SergeiKoralev** [comment]
> Now that I think about it, might be out of the scope of this PR, but the cooling loop gas filtering is still done in the opposite way compared to other maps - having you choose which gasses to remove instead of which gasses to keep. Should this maybe be changed to be like the other maps?

Nah, in my opinion the selective filter OUT leads to a little bit higher skill threshold. You can't just set the first one to N2 and then yeet everything else. I'm already making it easier. I don't need to make it hugbox.

**Comment by Emiliapains** [comment]
To be honest I wouldn't use this anyways i would just connect it to heaters as they as more efficient and DONT DEFLAM

**Comment by KubeRoot** [comment]
> To be honest I wouldn't use this anyways i would just connect it to heaters as they as more efficient and DONT DEFLAM

And that's the attitude that will lead to either heaters or TEG being nerfed so the setup doesn't work anymore

You know, I should look into porting the fix for that into bee :)

**Comment by SergeiKoralev** [comment]
Todo: Find a code monkey to make heaters and freezers do an area check on their initilization and dust everyone in the area after it is created.

**Comment by PowerfulBacon** [comment]
The SMs seems pointless in this setup since the burn chamber is doing the heating

**Comment by SergeiKoralev** [comment]
The SM is what provides gas flow for combustion, as well as a possible basis for expansion with rad collectors for the bored engineer. The point of this PR is that engineers are so stupid they can't manage it without different loops already. If N2O didn't decompose I'd be glad to entertain the idea that they're just bad, but it does, so running a super hot engine chamber burn is no longer really viable.

**Review by utilbird — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
Yolo

**Pull request merged**
