### PR TITLE
Revert "Locks felinids behind paywall"

### PR DESCRIPTION
**Pull request by Bastian0930**
About The Pull Request
You can now make catgirls again, because nobody is above the rules.
Why It's Good For The Game
This breaks the 6 month rule. If he's above the rules, why the hell am I not?

Changelog
🆑
tweak: Removes the paywall, because qwerty broke the 6 month felinid removal rule.
/🆑

### CODE REVIEW

**Comment by Moccha-Bee** [comment]
the 6 month rule is about removing felinids, not making them blocked behind a paywall...

**Comment by Bastian0930** [comment]
oh ffs moccha even you know that this is a removal of sorts

**Comment by Moccha-Bee** [comment]
> oh ffs moccha even you know that this is a removal of sorts

its not removing them its just making the felinids pay for a better server :smirk:

**Comment by Wilchenx** [comment]
>its not removing them its just making the felinids pay for a better server 😏

I don't see you having a patreon supporter role on discord.
If you believe in this so strongly maybe you should start paying 😏

**Comment by qwertyquerty** [comment]
I didn't remove anything dude, even people who already had a felinid character can keep it

**Comment by qwertyquerty** [comment]
Closing as it's an instant revert to something that literally just passed and has no code issues

**Comment by aguyiguess** [comment]
owned!

**Comment by Bestparty** [comment]
no simping allowed

**Pull request closed without merging**
