### PR TITLE
Reduces the chance of meteors

### PR DESCRIPTION
**Pull request by AnCopper**
## About The Pull Request

Reduces the chance of meteors.

## Why It's Good For The Game

This shit is annoying as fuck and happens almost every round

## Changelog
:cl:
tweak: reduced the chance for meteors.
/:cl:

### CODE REVIEW

**Comment by jupyterkat** [comment]
no fun allowed

**Comment by ike709** [comment]
I mean a fair number are also triggered by maintainers to get the round to end sooner.

**Comment by PowerfulBacon** [comment]
I have done a lot recently.

**Comment by qwertyquerty** [comment]
I think meteors chance are fine as is

**Comment by Rukofamicom** [comment]
Meteors are definitely a rare event by default. More than half of all meteor events I have been present for were triggered by staff because server needs to reboot and it's the easiest single button solution.

**Comment by SergeiKoralev** [comment]
I've had multiple 2-4 hour rounds on Acacia where meteors do not trigger. Check your station objectives for "build a meteor shield."

If NT says build a meteor shield, build the freaking shield. 

Edit: Code solution for lazy players is not the thing that we want to do. We should be actively encouraging completion of station objectives.

**Pull request closed without merging**
