### PR TITLE
Less HOPcurity

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
Removes their security access (they can access the Brig, but not sec posts/lockers/gear room). Replaces their energy gun with a mini energy gun and gives them combat gloves. 

## Why It's Good For The Game
Having security access means most HOPs will help themselves with a secbelt, secHUDs and use the assortment of sec posts around the station to charge their gun after they go validhunting. But they're not security, they can roll antag so this doesn't make sense. They even use that security access to then sneak into the Armory even when they're not allowed to. This change prevents that.

Their weapons should be used for self-defence only and be a step down from the captain's gear. But also giving them some insulated gloves to disincentivise robbing the cap's locker for their spare pair.

## Changelog
:cl:
balance: Removed security access from the HOP
tweak: Replaced their energy gun with a mini energy gun and added combat gloves to their locker.
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
you know that like... the HoP starts with ID console access, right?

**Comment by VictorVow** [comment]
Obviously? The point is now security can arrest them if they try to take sec gear, and on MRP shouldn't be giving themselves AA anyway.

**Comment by bloons3** [comment]
HoP needs an energy gun since on rev rounds they're literally a single hacked door from death.

**Comment by TheObserver-sys** [comment]
Iunno chief, this smells like even more of an excuse for HoP's to give themselves AA and grab a gun or two from the armory, to replace their shitty gun. Also, with fingerprintless insuls, Stealth HoP Traitor just got easier to get away with.

**Comment by fighterslam** [comment]
just.. remove HoP's e-gun? they already get sunglasses, a flash, and armor vest
granted, every head of staff gets some sort of exosuit, but HoP's one is actual armor

**Comment by VictorVow** [comment]
@bloons3 you could say the same about every Head, at least HOP is in a high traffic area where there's likely security and non-revs plus he can dash into the Bridge, and unlike other Heads has a gun still.

@TheObserver-sys in which case they'd be brigged for major trespass and theft. Fingerprints-wise it'd leave combat glove fibres, which are a dead giveaway also.

@fighterslam leaving them with a mini e-gun is a good middleground, good for self-defence but not great for validhunting.

**Comment by ike709** [comment]
> gives them combat gloves.

You had me. You really had me 100%. Then I saw this part. Remove the gloves.

**Comment by VictorVow** [comment]
@ike709 removed. Also the wiki changes have been made

**Comment by ike709** [comment]
I'm fine with this PR but I think @qwertyquerty had complaints about job bloat.

**Comment by VictorVow** [comment]
That was about the cadets/deputies PR, of which one isn't even a real job

**Comment by ike709** [comment]
Oh yeah that isn't this PR.

**Pull request merged**
