### PR TITLE
New Badge

### PR DESCRIPTION
**Pull request by francinum**
Codermin rank :smug:

## Changelog
:cl:
iconadd: New Badge for codermins
/:cl:

### CODE REVIEW

**Review by Crossedfall — DISMISSED** [review]
🐱

**Comment by francinum** [comment]
Config updated.

**Comment by PowerfulBacon** [comment]
Give it either maintainer blue or admin pink

**Comment by francinum** [comment]
@PowerfulBacon It's set up to use Seniormin red.

**Review by Crossedfall — APPROVED** [review]
> Give it either maintainer blue or admin pink

Purple would have been ideal, but donos have it. 😔  This is probably fine

**Pull request merged**
