### PR TITLE
remakes the wizards ship!

### PR DESCRIPTION
**Pull request by spockye**
## About The Pull Request
This is a draft for now, as im incapable of testing it (branch fuckery)

the new ship leaves more space for RP, while being a more prettified enviroment

no more green walls :)

## Why It's Good For The Game
the wizard ship is.... REALLY old. while it does have soul, im on a quest to bring our oldest maps up to date. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

</details>

## Changelog
:cl:
add: Remakes the Wizard ship
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I liked the green walls more than ugly reinforced ones. Gave it a sense of magicallyness

**Comment by EvilDragonfiend** [comment]
It should have more camera consoles in case when you have a company...

**Comment by EvilDragonfiend** [comment]
also, please repost the green wall version if you changed it. I don't feel good with the current screenshot...

**Comment by spockye** [comment]
> It should have more camera consoles in case when you have a company...

It has two, same as on the old version! I can add more if its wanted

**Comment by Fronsis** [comment]
Soul... another Spockeye, Martin banger! I feel the other colors compensate the green walls

**Comment by Mails-z** [comment]
I hope it still contains a ban hammer and an alien drill like the old one

**Comment by spockye** [comment]
> I hope it still contains a ban hammer and an alien drill like the old one

ofcourse! also added a couple more gimmick items, for more creative freedom :)

**Comment by spockye** [comment]
gurghg

**Comment by PowerfulBacon** [comment]
Failing checks

**Comment by itsmeow** [comment]
Closing all inactive draft PRs. Feel free to reopen whenever.

**Pull request closed without merging**
