### PR TITLE
[Janitor Buff] More things can clean cult runes

### PR DESCRIPTION
**Pull request by mystery3525**
## About The Pull Request

Makes more things use `is_cleanable()` instead of a typecheck for `/obj/effect/decal/cleanable`. These include:
- Soap
- Cleaner Spraybottles
- Cleanbots

## Why It's Good For The Game

I feel that if we have a whole `is_cleanable()` define which INCLUDES cult runes, more things should use this check instead of checking for cleanable decals? Additionally code-wise this allows us to add more cleanable objects instead of making it a subtype of the cleanable decals.

The cultist runes are not magically protected in any way, they are made of blood, they should be able to be cleaned. This may also encourage crewmembers/security/janitors to go out of their way to fully destroy cultist positions instead of leaving teleport or empower runes on the floor.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/30960302/998338cc-35a9-416c-a6b2-72e07ebf2ccc

</details>

## Changelog
:cl:
balance: soap, cleaner spray bottles/grenades, and cleanbots can now clean cult runes (previously just mops, janiborgs, and showers)
/:cl:

### CODE REVIEW

**Comment by CydiaLamiales** [comment]
It's consistency yeah, but I guess this counts as a balance change?

**Comment by mystery3525** [comment]
I guess, I don't really know the difference and think tweak and balance is the same. They surely are used pretty interchangeably

**Comment by Rustyfoxb** [comment]
Correct me if im wrong but isn't holy water needed to remove them currently?, if so then it would mean that they are sorta protected by magic.

**Comment by mystery3525** [comment]
Nope. Currently there is no way to remove them other than mops, water vapor canisters (and literally just splashing water on the tile), janitor borgs moving over the runes, and showers

**Comment by TeomanTheGreat** [comment]
Now I'm not sure if I have dementia but I'm fairly certain if this is cult runes or really any magical rune (this works on heretics ones as well) the chaplain is supposed to use his null rod on it and delete the rune. I'm not sure if there is a misunderstanding here but isn't that common knowledge?

**Review by Rukofamicom — DISMISSED** [review]
If anything, cult runes should require holy water to clean, not space cleaner, and null rods do already also work to remove them.

I'm still pretty uneasy about this as a steep nerf to cult.

**Comment by EvilDragonfiend** [comment]
Same opinion with Ruko

**Comment by mystery3525** [comment]
I won't make that change as that is against the whole point of this PR. Additionally, we pulled logs for how many times the null rod the null rod was used to remove runes and got **4** times for the entire year of 2023, with the most recent one from my ASAY asking about it. The days they were used is as follows: Jun 23rd, June 19th, and April 13th.

**Comment by TeomanTheGreat** [comment]
> I won't make that change as that is against the whole point of this PR. 

So what's the point of the pr? Is this a cult nerf pr? You say that cult blood runes have no magical protection because they are blood but it's evidently magically charged blood. This pr trivializes cult rune removal as literally anyone with space cleaner and a spray bottle can wipe an entire cult base of runes in seconds.

**Comment by Rukofamicom** [comment]
> I won't make that change

🔑

**Review by EvilDragonfiend — CHANGES_REQUESTED** [review]
I will hold my key as the last change request.

If you really want to make normal crews can remove runes with their own, it should be:
* Add HP to each rune (including heretic rune)
* 3x3 runes should have extra HP
* each cleaning action should deal 'minor' damage to runes.
* As long as enough damage is dealt to runes, it will be removed.

If you can't make this, please close the PR instead of telling you won't change this again.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Making them use is cleanable is a good change but runes should be changed to not be cleanable and require a null rod, cult dagger or other specialist removal methods.

**Comment by PowerfulBacon** [comment]
> I won't make that change as that is against the whole point of this PR. Additionally, we pulled logs for how many times the null rod the null rod was used to remove runes and got **4** times for the entire year of 2023, with the most recent one from my ASAY asking about it. The days they were used is as follows: Jun 23rd, June 19th, and April 13th.

There is no logging in the current code for removing runes, it may log if someone hits it on harm intent instead of removing it.

**Comment by mystery3525** [comment]
Won't make this specific change again, though I may port the cleaning refactor from tg eventually

**Comment by Tsar-Salat** [comment]
>  though I may port the cleaning refactor

needs the exposure refactor they did, ive spent over 15 hours trying to fix that broken mess since first porting #8402 lmao

**Pull request closed without merging**
