### PR TITLE
Removes Magicarp from Gold slime cores

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Removed Magicarp and its variants from Gold slime core spawn list.

Alternative to https://github.com/BeeStation/BeeStation-Hornet/pull/3565

## Why It's Good For The Game

Less grief, magic and mayhem.

## Changelog
:cl:
del: Removed Magicarp and its variants from Gold slime core spawn list.
/:cl:

### CODE REVIEW

**Comment by february-ops** [comment]
ngl this should be sage only

**Comment by Sinmero** [comment]
Shall we also remove maxcaps, chemistry, botany, supermatter and atmos? They can cause plenty of chaos and mayhem with much less effort.

If magicarps are a major problem on sage maybe there should a ruling preventing them being destructive there.

**Comment by Effemu** [comment]
> 
> 
> Shall we also remove maxcaps, chemistry, botany, supermatter and atmos? They can cause plenty of chaos and mayhem with much less effort.
> 
> If magicarps are a major problem on sage maybe there should a ruling preventing them being destructive there.

i can say with 90% confidence that botany is probably on the nerf list

**Comment by Sinestia** [comment]
> Shall we also remove maxcaps, chemistry, botany, supermatter and atmos? They can cause plenty of chaos and mayhem with much less effort.
> 
> If magicarps are a major problem on sage maybe there should a ruling preventing them being destructive there.

i prefer the other change to carps but

>maxcap

make pressure affect the ttv's ability ;)
>chemistry

yes
>botany

yes
>supermatter

what
>atmos

if fusion wasn't a thing and fun was a priority over nostalgia then removing the free plasma tank would be pog

**Comment by MNarath1** [comment]
You first want to remove bolt of change from chaos magicarp the mob relying most on rnd of all for some reason and now you want to remove magicarps from xenobio in general this is not an alternative solution to a problem that is entirely handled by server ruling like all the possible grief you can do. Rolling bolt of change for magicarp is just as likely as getting locker bolt or sword energy(probably the weakest of all bolts) its also heavily rnd relying and i see many xenobiologists working all round just to get a single magicarp with the needed power while i personally think gold slime cheese is not really an interresting time usage for xenobio i do not think its really a good idea to remove one of the only actually versitile mobs in the gold slime pool.
Also you call this an alternative solution to removing change bolt from chaos magicarp i cannot really see any reason to remove it from the most heavily relying rnd mob in the game and while magicarp's are used for powergaming they still fall under normal grief powergame ruling

**Comment by Sapfearon** [comment]
Let's remove gold cores completly. And golems. And slimes. And xenobio while we at it.

**Comment by ghost** [comment]
> Let's remove gold cores completly. And golems. And slimes. And xenobio while we at it.

Cult golems should indeed be removed from non-cult gamemodes, as they are utterly broken balance-wise.

**Comment by OceanFish1** [comment]
Combat should be removed because it's unbalanced to new players

**Comment by ghost** [comment]
Literally just... make a xenobio variant of magicarps _without_ the ridiculous grief shit it normally comes with? Is this real? What happened to everyone screaming "muh improve no remove"?

We really are in the clown timeline.

**Comment by MNarath1** [comment]
Or just let rules handle it as intended also still the chance to get turned into some other race its very unlikely to happen why chaos magicarp is rnd thats why they are too unpredictable to be used in combat often my best guess is that the author had this happen once to him due to really bad luck but many players i know who actually got chaos magicarp said they did pretty badly sure you can get fireball or something but just as likely as like getting heal and thats like a death sentence for the carp if you really want to nerf it more then change the probability for getting magicarp or chaos magicarp from gold pool instead of a blank removal but i do not think this is a good idea anyway

**Comment by MNarath1** [comment]
> > Let's remove gold cores completly. And golems. And slimes. And xenobio while we at it.
> 
> 
> 
> Cult golems should indeed be removed from non-cult gamemodes, as they are utterly broken balance-wise.

Cult golems need actual runed metal that you can only get from cult or if you are really lucky then from a lavaland ruin

**Comment by february-ops** [comment]
> > > Let's remove gold cores completly. And golems. And slimes. And xenobio while we at it.
> > 
> > 
> > Cult golems should indeed be removed from non-cult gamemodes, as they are utterly broken balance-wise.
> 
> Cult golems need actual runed metal that you can only get from cult or if you are really lucky then from a lavaland ruin

You can get it in every round in the curator library

**Comment by ghost** [comment]
Closed in favour of https://github.com/BeeStation/BeeStation-Hornet/pull/3565

**Pull request closed without merging**
