### PR TITLE
Makes charcoal pills charcoal colored

### PR DESCRIPTION
**Pull request by Raven-Industries**
## About The Pull Request

Makes pill17 charcoal/blackish colored instead of green. Pacifies the vehement anti-green charcoal faction within the playerbase. 

## Why It's Good For The Game

we already have a circular green pill, this will add variety to pill color. Charcoal pills will also look like charcoal, increasing clarity of use with regards to visual design.

## Changelog
:cl:
tweak: changed color of pill17
imageadd: added new pill17 icon in icons/obj/chemical.dmi and added corresponding new UI icon
imagedel: deleted old pill17 icon in icons/obj/chemical.dmi and removed corresponding old UI icon
/:cl:

### CODE REVIEW

**Comment by Raven-Industries** [comment]
I'd love it if I could figure out how to hide/delete all the now obsolete trial-and-error commits from when I tried to add a new pill entirely.

**Comment by Archanial** [comment]
but where's the soul?

**Comment by Archanial** [comment]
> 
> 
> I'd love it if I could figure out how to hide/delete all the now obsolete trial-and-error commits from when I tried to add a new pill entirely.

Don't commit on master, ask in coding channels, people surely will help you with git stuff.

**Comment by aidan-bowman** [comment]
no no no no NO NO NO NO DO NOT CAVE IN DO NOT FALL TO THE MICHIRU PROPAGANDA CHARCOAL PILLS BEING GREEN IS INHERENT TO OUR CULTURE AAAAAAAAAA

**Comment by TeomanTheGreat** [comment]
Is this really necessary? They are green so new players know they heal toxin damage (which is represented as green)

**Comment by Raven-Industries** [comment]
> Is this really necessary? They are green so new players know they heal toxin damage (which is represented as green)

I can only speak for myself, but I never made that connection as a new player. The real thing that did it was that the bottle of pills was in the box labeled "toxin first aid kit".

**Comment by PowerfulBacon** [comment]
You know pills are containers for a substance, they aren't actually made of the substance. The substance of pills is a powder inside the pill which only gets releases when the shell of the pill disolves. Shells of pills are usually coloured to not look unappealing so bright colours make more sense.

**Comment by Raven-Industries** [comment]
It depends on the type of pill; the circular shape of this one probably implies a tablet rather than a capsule so it's likely either mixed with a binding agent or pressed into shape. A coating could be applied with pigment, but a google image search for "charcoal pills" seems to indicate that most manufacturers don't bother with it.

**Comment by eLeCtrOssSnake** [comment]
Rather than deleting a pill, maybe adding a new one is cooler?

**Comment by PowerfulBacon** [comment]
> 
> 
> It depends on the type of pill; the circular shape of this one probably implies a tablet rather than a capsule so it's likely either mixed with a binding agent or pressed into shape. A coating could be applied with pigment, but a google image search for "charcoal pills" seems to indicate that most manufacturers don't bother with it.

Ok true

**Comment by ToasterBan** [comment]
i would rather stay banned than live with black charcoal pills smh

**Comment by Raven-Industries** [comment]
I don't know why I'm even defending black charcoal pills, I have literally 0 investment in the success or failure of this PR.

**Pull request closed without merging**
