### PR TITLE
Adds RCDs and RPDs to the Science departmental protolathe

### PR DESCRIPTION
**Pull request by LivingBatteryBox**
Changes tool_designs.dm to allow RCDs and RPDs to be printed at science lathe

## About The Pull Request

This Pull Request adds the DEPARTMENTAL_FLAG_SCIENCE flag to RPDs and RCDs.

## Why It's Good For The Game
Science is a department that builds a lot of things like machines. Why cargo would get RCDs and science would not get RCDs is beyond me. There is only one RPD in toxins, so if a greytider steals it in an attempt to reroute disposals into HOP office for AA or whatever, you are stuck begging other departments for another RPD, when you should be able to print them yourself.

## Changelog
:cl:
tweak: Science protolathe can now print RCDs and RPDs
/:cl:

### CODE REVIEW

**Comment by LivingBatteryBox** [comment]
Why the hell did it give it such a weird title? I put the title as "adds RCDs and RPDs to science protolathe"... Weird

**Comment by ike709** [comment]
science power creep

**Comment by PowerfulBacon** [comment]
Put the RCD upgrades too

**Comment by Isy232** [comment]
RPD, yes, RCD no.

Even though it pains me as a science main, they shouldn't get RCD's this easy.

**Comment by yyzsong** [comment]
You should also add cable coil to the lathes. For some fucking reason, none of them can make it other than the autolathe

**Review by PowerfulBacon — APPROVED** [review]
Code is fine

**Comment by alxmra** [comment]
hmm yes good pr yes merge

**Comment by zeskorion** [comment]
closed under executive order

**Pull request closed without merging**
