### PR TITLE
1728 Pirate Shuttle

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
Finally adds the 1728 pirate shuttle. Offers a different way to play pirates.

They are given a 1000 unit barrel filled to the brim with black powder. This is intended to be used for makeshift grenades but could also be used to take out a large chunk of the station. I am not sure if this is a good thing or not, please discuss it. 

## Why It's Good For The Game
I think it is an overall nerf on the pirates, it has a 50/50 chance of spawning instead of the default ship and requires the pirates to play it differently. Instead of being given top of the line gear, they are given shit. Even have to make their own ammo and explosives!

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

https://github.com/user-attachments/assets/a45f366f-f438-485f-9bc6-6f84903b96c3

If the pirates are not careful, their entire shuttle might explodey.

image

</details>

## Changelog
:cl:
add: Added 1728 pirate shuttle!
balance: Nerf/buffs pirates and their shuttle.
add: Black powder barrel. :trollface:
balance: Nerf the Nagant Revolver from 55 damage to 25.
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
The black powder barrel currently doesn't explode and causes runtime errors.

**Comment by PowerfulBacon** [comment]
golden age of piracy was 1650 and 1720 so you were 8 years too late

**Comment by Rukofamicom** [comment]
> balance: Nerf the Nagant Revolver from 55 damage to 25.

No.
Give them a different gun if you want them to have a gun, don't fundamentally change this one please.

**Comment by Rukofamicom** [comment]
> They are given a 1000 unit barrel filled to the brim with black powder. This is intended to be used for makeshift grenades but could also be used to take out a large chunk of the station. I am not sure if this is a good thing or not, please discuss it.

This should not be possible to detonate on its own or it absolutely will be the majority of the time most likely.

**Comment by MarkusLarsson421** [comment]
> This should not be possible to detonate on its own or it absolutely will be the majority of the time most likely. 

I did give them a few 30u bottles of black powder, but that can only make a few improvised shots or maybe one grenade, which won't be able to blow up a door.

It is quite counterintuitive, but should I make the barrel simply not do anything and just vanish?

**Comment by MarkusLarsson421** [comment]
> golden age of piracy was 1650 and 1720 so you were 8 years too late

Fuck. Thank you.

**Comment by MarkusLarsson421** [comment]
> No.
> Give them a different gun if you want them to have a gun, don't fundamentally change this one please. The damage is high to match the ammo it uses. 

Oops, I meant to write the ammo it uses waa nerfed from 55 to 25. Not the gun itself.

**Comment by PowerfulBacon** [comment]
The whole point of revolvers is to be a high damage, but highly expensive weapon. The detective's revolver goes against this by having easilly printable ammo and lower damage though, so that one kind of breaks the rules.

**Comment by Raven-Industries** [comment]
> > They are given a 1000 unit barrel filled to the brim with black powder. This is intended to be used for makeshift grenades but could also be used to take out a large chunk of the station. I am not sure if this is a good thing or not, please discuss it.
> 
> This should not be possible to detonate on its own or it absolutely will be the majority of the time most likely.
> 
> I like the flavor but I am really not sure how to justify making it unable to detonate on its own.

Would some sort of barrier to immediate detonation be sufficient? 

> > They are given a 1000 unit barrel filled to the brim with black powder. This is intended to be used for makeshift grenades but could also be used to take out a large chunk of the station. I am not sure if this is a good thing or not, please discuss it.
> 
> This should not be possible to detonate on its own or it absolutely will be the majority of the time most likely.
> 
> I like the flavor but I am really not sure how to justify making it unable to detonate on its own.

Just my 2 cents, but would something along the general lines of a chem dispenser work? Barrel looking object with a finite amount of black powder to dispense without actually being something you can detonate in and of itself. It is admittedly a bit of a special snowflake solution (and probably outside the PR scope).

**Comment by PowerfulBacon** [comment]
Or just limit the size of the explosion of the barrel so its more efficient to make grenades

**Comment by Rukofamicom** [comment]
> Or just limit the size of the explosion of the barrel so its more efficient to make grenades

I also like this option, even if it's a bit snowflakey, this is the kind of case where that's more or less justified.

**Comment by Fronsis** [comment]
I highly suggest taking a look at the cannons/cannonballs/gunpowder barrels from TG, they perfectly fit what you want to accomplish and allows them to go straight to action, pirates taking time to make nades seems like it will deny a lot of surprise attacks, not to mention not everybody knows how to make nades

**Comment by SunShine214** [comment]
While making your own weapons sounds fun, pirates are midround spawns, and as such lack the prep time required. additionally, having to spend 20-45 minutes (depending on how skilled the players are) to even have a fighting chance might not be the best idea. Perhaps have sufficient spawning supplies to 1) demonstrate you are meant to make/use ghetto ammo and explosives and 2) to decrease prep time required.

**Comment by MarkusLarsson421** [comment]
> While making your own weapons sounds fun, pirates are midround spawns, and as such lack the prep time required. additionally, having to spend 20-45 minutes (depending on how skilled the players are) to even have a fighting chance might not be the best idea. Perhaps have sufficient spawning supplies to 1) demonstrate you are meant to make/use ghetto ammo and explosives and 2) to decrease prep time required.

You still get enough ammo to take down one or two armored opponents assuming you hit enough shots. There are six weapons in total. With a free rubber buckshots box and five free improvised buckshot shells. I would hope to make this maybe an early round or actual mid-round role rather than late game (which is when pirates tend to spawn most often), but that's outside the scope of this PR.

**Review by spockye — COMMENTED** [review]
im a fan! just got some small nitpicks :p 


image
floating cobweb

image

floating webs

other then that not much to say. well made and interesting. i'd like to see it tm'd!

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
I don't like the nerf to the nagant revolver. Choose a more reasonable value than 25 since that's very little damage for a ballistic weapon and a revolver weapon. If you want a revolver weapon, it should be high damage but have limited ammo.

**Comment by Rukofamicom** [comment]
Due to personal circumstances, author has requested that all PRs be treated "as-is" for the time being. 
Closing this one due to failed checks, merge conflict and outstanding changes requested.

**Pull request closed without merging**
