### PR TITLE
Removes Sentient Disease

### PR DESCRIPTION
**Pull request by DatBoiTim**
## About The Pull Request
Sentient Disease are very dated, and not very fun to play as, or against.

There's not a rework in progress that we know of. So removing this unmaintained code is probably for the better.
If someone wants to rework it and re-add by all means. But this code is not really worth keeping around in its current state.

## Why It's Good For The Game
Not very fun to play, not fun to play against. Not many folks are gonna miss it.

This was a flat removal. Not much to test here.

## Changelog
:cl: DatBoiTim
del: Removed Sentient Diseases
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
If this pr is closed, i was planning a rework pending the resolution of #5624 . I dont care much about the antag, but am willing to bring them up-to-date. Said rework would not fix the primary gameplay concern of sentient diseases being utterly unfun for the crew, however, and i have no objection to their removal

**Review by zeskorion — CHANGES_REQUESTED** [review]
Please remove the "sentient" var from advanced diseases as well

**Comment by DatBoiTim** [comment]
> i was planning a rework pending the resolution of #5624 . 

If you open a draft and outline some basic deliverables I don't mind closing this.

There's just no documented in progress rework hence the push for removal.

**Comment by zeskorion** [comment]
> > i was planning a rework pending the resolution of #5624 .
> 
> If you open a draft and outline some basic deliverables I don't mind closing this.
> 
> There's just no documented in progress rework hence the push for removal.

By all means, remove it and save me the work. All sentient disease is , and will be , is an antag who diess easy or griefs the crew if a competent viro rolls it

**Comment by DatBoiTim** [comment]
> Please remove the "sentient" var from advanced diseases as well

Done(sanitized diffs too)

**Review by Archanial — APPROVED** [review]

**Comment by Archanial** [comment]
If someone ever wants to readd this, he can just copypaste code from this pr or revert the specific commit.

The issue with this antag is that it's outdated, code breaks with every major disease change and it's unfun for both sides. Cures are extremely easy to produce and if no cure is ever produced the disease can quickly wipe out the crew.

**Comment by zeskorion** [comment]
> If someone ever wants to readd this, he can just copypaste code from this pr or revert the specific commit.


fuck no

> The issue with this antag is that it's outdated, code breaks with every major disease change and it's unfun for both sides. Cures are extremely easy to produce and if no cure is ever produced the disease can quickly wipe out the crew.

the second part cant be fixed and keep the same core concept, let this rot

**Pull request merged**
