### PR TITLE
v2 Tend Wounds buffs and related tweaks port

### PR DESCRIPTION
**Pull request by VictorVow**
New PR because old branch is fuck

## About The Pull Request

TL,DR: tend wounds is quicker, more effective and is a viable alternative to sleepers:
- Tend Wounds is now only 2 steps (Scalpel > healing with Hemostat. Hemostat step is repeatable. Cautery when you're finished)
- More research means that you can unlock more advanced versions than the basic surgery and eventually it can even heal both brute/burn at once
- It can be done through clothing
- Success chances and fail damage tweaked
- Medibots now tend wounds
- TW heals more scaling with missing health

See changelog at bottom for full info.

## Why It's Good For The Game
Tend wounds is currently so weak and long-winded that it's a waste of time to try to heal someone with it. This makes it a viable alternative to sleepers, and gives doctors something to do rather than spend 5 seconds putting someone in a sleeper and clicking a button. 

## Changelog
:cl:
balance: Tend Wounds is now only 2 steps (Scalpel > healing with Hemostat. Cautery when done)
fix: Borgs can now perform Tend Wounds
add: Anti-spam on Tend Wounds (Starting Message only, Result Message untouched)
add: Keep their pants on! Now Tend Wounds can be done through clothing! However it is 60% less efficient this way
tweak: You can upgrade both Tend Wounds Burn/Brute trees via techwebs
add: Advancing far enough into the tree enables Mixed Tend Wounds surgery, which heals less of each but is considerably faster. Get alien tech for the best of the best!
balance: TW fail chance when using improvised tools decreased. Hooray for ghetto surgery!
balance: Medibot no longer works off chems and instead performs a lesser equivalent to Tend wounds
balance: They still heal all 4 base damages and use same clothing restrictions as previously
del: Medibot Beaker Holding / Virus Treating no longer exists
add: Medibots scale with Tend Wound research (1 tend wound surgery researched = 50% more healing)
add: Medibots heal more of a specific damage if the medkit used to make them was oriented around that damage (a tox medkit medibot will heal toxin better)
tweak: Emagged Medibots now pretend to tend your wounds, actually damaging you and applying 5u chloral per step.
add: Surgery steps are now shown in detail only to the surgeon and anyone standing adjacent to them; the patient and people watching from further away get a more vague/ambiguous description.
add: Operating computers can now be built to sync with all nearby stasis beds within it's LoS and provide them with advanced surgeries.
balance: Failing TW now give 80% damage (based off normal healing) instead of flat 5 brute
add: Tend Wounds now scales with missing health!
tweak: All Tend Wound Upgrades (bar Alien Tech Combo Surgery) do same base healing but scale with missing health differently. They should all heal more than they usually do in most cases though.
code: Medibots were NOT changed and will continue to NOT scale with missing HP to make humans more desired.
add: Operation tables and stasis beds now link to operation computer when built
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Gonna testmerge soon

**Comment by Crossedfall** [comment]
Test merged onto Golden

**Comment by qwertyquerty** [comment]
@Victor239 how is the testmerge going so far?

**Comment by eLeCtrOssSnake** [comment]
I personally see any significant buffs nor disadvantages.

**Comment by eLeCtrOssSnake** [comment]
maybe because nobody uses it on golden

**Comment by VictorVow** [comment]
@qwertyquerty works as expected so far.
@eLeCtrOssSnake you need to have compared the before/after of using tend wounds. Comparing it to MRP where it's unmerged, this buff is sorely needed.

**Pull request merged**
