### PR TITLE
Fixes Stun Resistance Chemicals.

### PR DESCRIPTION
**Pull request by Sparrowbird611**
## About The Pull Request

This fixes stun resistance chemicals, most of which were broken when we switched from tasers and old stun batons to disablers and the reworked stun baton. This also buffs Aranesp.

## Why It's Good For The Game

It fixes broke chemicals, which I will list here.
Stimulants: 60 stamina regeneration
Changeling Adrenaline: 40 stamina regeneration
Meth: 35 stamina regeneration
Crank: 25 stamina regeneration
Aranesp: 28 stamina regeneration (Up from 18)
Ephidrine: 10 stamina regeneration

## Changelog
:cl:
fix: Fixes most of the stun resistance chemicals that weren't working properly. Chemicals include stimulants, Changeling Adrenaline, Meth, Crank, and Ephedrine.
Balance: Buffs the chemical Aranesp to 25 stamina regeneration (Up from 18 stamina regeneration)
/:cl:

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
As a side note, this doesn't completely fix adrenals or the changeling adrenal abilities, since those are supposed to completely purge all the stamina damage sustained. These only fix the base chemicals that get injected (stimulants and changeling adrenaline, respectively). Those abilities will be fixed at a later date.

**Comment by triplezeta** [comment]
why does crank, which has no downsides when not OD'd and not addicted, have a stronger stamina regeneration effect than aranesp? While the downsides of aranesp are pretty negligible, it doesn't make much sense for a chemical to be objectively worse than another while having similar difficulty in mixing.

**Comment by enthethan** [comment]
@triplezeta no downsides?  2 toxin damage per tick is def a downside

**Comment by triplezeta** [comment]
Crank has no downsides, last I checked. Where are you pulling this 2 toxin damage a tick from?

**Comment by Sparrowbird611** [comment]
Changed the numbers slightly. Crank is now 25 stam regen, and Aranesp is 28 stam regen. Changelog accounts for this.

**Pull request closed without merging**
