### PR TITLE
Changes preferred clothing style spawning behaviours.

### LINKED ISSUE #8537: Move skirts to informal wear
Move skirts to informal wear for most job roles, and have them as non-roundstart. People can wear non-formal wear on the job if they want, however they shouldn't start with it.

This should affect roles like:
- Cargo
- Medbay
- Security
- Engineering
- Command (Should fully remove command skirts? At least for the captain it doesn't really fit the vibe of a commanding, powerful person who is wearing a cute skirt)

This shouldn't affect service or science, wearing skirts in those jobs is fine and makes sense.

### PR DESCRIPTION
**Pull request by PowerfulBacon**
closes #8537 

## About The Pull Request

Changes the behaviours of preferred clothing style, jobs that don't make sense to be wearing skirts will not have their official spawn uniform as a skirt style.
Members of these job roles are free to get skirts and wear them from the vendors, the same way they are free to wear a hoodie on the job, however the starting (official) work gear will not be a skirt unless it makes sense to be so.

This gives us the best of both worlds of allowing players to choose to wear informal clothing on the job, but having the official clothing as sensible and practical.

Jobs that include skirts are:
- All service jobs excluding the Head of Personnel
- All science jobs excluding the Research Director

## Why It's Good For The Game

Job roles that shouldn't have a skirt as their official uniform won't have a skirt as their official uniform. Ideally, any casual uniforms shouldn't be default spawn for job roles that have their uniform defined due to the work they are performing.

This is especially important for critical job roles, such as the captain, where ideally we want them to be playing a certain style of character (Powerful, authoritative) as oppossed to a cute kawaii catgirl.

Removes the shitcode of the previous method

## Testing Photographs and Procedure

image

image

image

## Changelog
:cl:
tweak: Preferred uniform style will no longer spawn crewmembers in their informal wear on the job (Job roles will not spawn with skirts when it makes no sense to do so).
/:cl:

### CODE REVIEW

**Comment by CydiaLamiales** [comment]
https://cdn.discordapp.com/attachments/528596617641852928/928031818052173835/1984.mov

**Comment by CydiaLamiales** [comment]
Also did you not include Cargo into the skirt list intentionally? Miners I'd understand, but Cargo Techs and the QM?

**Comment by itsmeow** [comment]
As much as I'm inclined to agree on the roleplay side of things, I really hate removing options from players *just because* it could be more realistic.

Functionally, this just means every player that wants a skirt is now going to put it on as another "roundstart task" they have to do, or they'll be stuck hunting one down from cargo or some vendor rather than doing their job.

It just seems like a really meh solution both ways. It doesn't do much to help and it doesn't do much to hurt.

Whether something is "official" is kind of a moot point when you recognize this is a station run by idiots who are being attacked by maniacs and otherworldy monsters.

Having command players have agency over their character without having to hunt stuff down roundstart is a good thing. Funneling players into not wearing skirts because you don't like captain characters who aren't narcassistic hardasses is not.
Roleplay is not playing the same character every single time. Sometimes you have bad characters who are bad at their job, but still drive conflict, sometimes you have great characters who are amazing at their job but still don't fit the expectations you might have.

This is just a really bad way of funneling and removing player choice in outfits.

**Comment by Rukofamicom** [comment]
I agree with the idea that roles which need fullbody protection shouldn't be performing their jobs in skirts, but that's about as far as I can agree with this PR. It seems like a half-measure designed to avoid upsetting the community, but will fail to do so and also fail to accomplish what it sets out to discourage at the same time. 

Kat said it really well:
> Functionally, this just means every player that wants a skirt is now going to put it on as another "roundstart task" they have to do, or they'll be stuck hunting one down from cargo or some vendor rather than doing their job.

The jumpskirts are also very clearly designed as uniforms rather than casual wear, so the argument that they should only be worn as casual outfits doesn't really hold any ground in my opinion. 

* For roles you don't think are appropriate to be worked in skirts, remove the skirts entirely
* For roles you are okay with putting skirts on right away from vendor, just let them do it from preferences.

**Comment by Rukofamicom** [comment]
The skirts need to be removed from the code, or at the very least from vendors, if you don't want players simply putting them on right away.

**Comment by itsmeow** [comment]
:key: I find this PR pretty heavy handed and I don't like the precedent it sets. I also think it wildly unpopular with the playerbase. Obviously sometimes we have to make decisions that are unpopular to drive roleplay forward but I don't think this is the hill to die on.

**Comment by PowerfulBacon** [comment]
I don't feel strongly enough about this PR to force it through, so I'm just going to close it. I still maintain the opinion that the captain shouldn't get a skirt but that can be a simple change to just remove it.

**Pull request closed without merging**
