### PR TITLE
Makes TRAIT_NODROP shoes unstealable

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Title.

## Why It's Good For The Game

Without this you can't steal a pair of shoes which you then can't drop. This isn't nice.

## Changelog
:cl:
fix: You can no longer steal unstealable shoes
/:cl:

### CODE REVIEW

**Comment by r1ks-iwnl** [comment]
> Without this you steal a pair of shoes which you then can't drop. This isn't nice.

Or

>With this you can tell if someone's shoes have the nodrop trait. This is nice.

**Comment by r1ks-iwnl** [comment]
Actually wait i think im misunderstanding this, does this make you able to steal a disguised ling's shoes ?

**Comment by ivanmixo** [comment]
I wrote it wrong. This just makes undroppable shoes unstealable.

**Comment by r1ks-iwnl** [comment]
Mhm, disregard that first comment then.

**Review by utilbird — APPROVED** [review]

**Pull request merged**
