### PR TITLE
Nukes Runechat and Balloon Alerts

### PR DESCRIPTION
**Pull request by DatBoiTim**
## About The Pull Request
Say Goodbye to Runechat and BalloonAlerts.

This PR keeps the chat bubble icon when speaking.

## Why It's Good For The Game
Runechat and Balloon Alerts have a penchant for fucking with timers. 

It also brings attention to chat pane where there plenty of relevant information, such as:

Radio Communications(hailing, etc.)
Device Readouts
Other Actions, such as combat, etc.
Notifications about mindshielding, etc.

All of which do not show up in these systems(nor should they, due to information density issues).

They need to be removed together since they have some common denominators in their existence.

Server Stability > User Experience

## Changelog
:cl: DatBoiTim
del: Removes Runechat Completely
del: Removes Balloon Alerts Completely
/:cl:

> We didn't use TG's better runechat, we rolled our own. Ours is worse.

### CODE REVIEW

**Comment by utilbird** [comment]
How much did francium pay you

**Comment by Kapu1178** [comment]
No

**Comment by DatBoiTim** [comment]
> How much did francium pay you

🤷 We've not even got an official deal on the table yet

**Comment by DatBoiTim** [comment]
> No

Literally cry about it and learn to read.

**Comment by Kapu1178** [comment]
balloon alerts can go, they are often grammatically incorrect. runechat is based though.

**Comment by francinum** [comment]
I haven't paid him, though with how quickly he turned this around with pretty much only the prompt of me mumbling in a VC and not even actually asking him to do this I probably ought to.

**Comment by utilbird** [comment]
if you're really that concerned about runechat you should optimize it rather than outright removing it. Timers are used because they're easy, not because they're efficient. There are more performant alternatives.

This is a pretty extreme measure for a relatively mundane problem

**Comment by francinum** [comment]
Timers were used because they can be accounted.
We can easily just have them sleep.

**Comment by MCterra10** [comment]
I've never had any use for bubble alerts, they just a nuisance when you switch gun modes midcombat. However rune chat is crazy good and I use it constantly. This is such a lame thing to do with such a useful feature

**Comment by jupyterkat** [comment]
tg moment

**Comment by ike709** [comment]
We didn't use TG's better runechat, we rolled our own. Ours is worse.

**Comment by DatBoiTim** [comment]
> We didn't use TG's better runechat, we rolled our own. Ours is worse.

If it's consolation I've had fran oversee the tests.

Now I will probably go to sleep before my cold medicine fucking knocks me out

**Comment by DatBoiTim** [comment]
> > We didn't use TG's better runechat, we rolled our own. Ours is worse.
> 
> If it's consolation I've had fran oversee the tests.
> 
> Now I will probably go to sleep before my recent dose cold medicine fucking knocks me out

**Comment by Sinestia** [comment]
> 
> 
> We didn't use TG's better runechat, we rolled our own. Ours is worse.

Something something bee moment

**Comment by Archanial** [comment]
?
🔑

**Comment by utilbird** [comment]
🔑

**Comment by francinum** [comment]
One day.

**Comment by ike709** [comment]
🔑

**Comment by MCterra10** [comment]
:key:

**Pull request closed without merging**
