### PR TITLE
Upgrading DMAPI to TGS4

### PR DESCRIPTION
**Pull request by qwertyquerty**
## About The Pull Request

Prepare for the slow switch to tgs4 by upgrading DMAPI

## Why It's Good For The Game

TGS4 is better than TGS3 so good and stuff

## Changelog
:cl:
server: Upgrading DMAPI to 5.1.0 for TGS4
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Still need to do the integrations

**Comment by qwertyquerty** [comment]
Nevermind current integrations appear to suffice

**Comment by Crossedfall** [comment]
Fix yo errors

**Comment by MCterra10** [comment]
Will tgs3 still be functional after the update?

**Comment by Crossedfall** [comment]
> 
> 
> Will tgs3 still be functional after the update?

Yes

**Comment by ike709** [comment]
what's the status with this

**Comment by qwertyquerty** [comment]
@Crossedfall https://www.youtube.com/watch?v=02vDkMEdIkY&t=56

**Review by Crossedfall — APPROVED** [review]

**Comment by Cyberboss** [comment]
@qwertyquerty 5.1.1 was released with fixes https://github.com/tgstation/tgstation-server/releases/tag/dmapi-v5.1.1

**Pull request merged**
