### PR TITLE
Lavaland Spawners will now spawn more Ashwalkers, Golems, and Syndicate Bases

### PR DESCRIPTION
**Pull request by Programs-The-Station**
## About The Pull Request

Round after round, the only ghost spawners that are available on Lavaland are the Beach Bums, Lavaland Veterinarians and Hermit roles. These roles are very rarely selected by ghosts and are more heavily RP focused. With small mining teams, there is not a lot of people down on Lavaland to interact with, so these roles are very limited.

I decreased the weight of the major spawners instead of increasing the weight of the low impact spawns, as recommended by Bacon.

## Why It's Good For The Game

Beach bums, lavaland vets, and lavaland hermit ghost spawners are rarely used, and do not have much potential due to their limited gear and reason to stick to Lavaland (plus fairly unclear rules in the Wiki). Golems, Ashwalkers, Syndicate base, and Lifebringers infrequently spawn due to their cost, and these are the roles which are the most replayable and useful if you want to mess around with other things without impacting the round.

## Testing Photographs and Procedure

It builds... not sure what other testing you would like to see on a 5 line change.

## Changelog
:cl:
balance: Lavaland will now be more dangerous: Some ghost spawns will be more readily available.
/:cl:

### CODE REVIEW

**Review by itsmeow — APPROVED** [review]

**Comment by Isy232** [comment]
I'd argue maybe change the numbers even more than that.

The lavaland syndicate base is often a great source of interesting situations that make for good roleplay.

Nanotrasen excursions, syndicate communications deception, all fun.'

Golems and lizards too.

**Comment by Programs-The-Station** [comment]
@PowerfulBacon :
Now that I had a few minutes, I ran a Monte Carlo simulation of the rough spawning logic behind the ruins. 
image

With the Weights as is, the Vets / Biodome spawns dropped by about 6 percent, while high impact spawns rose about 6 percent. Most other spawns slightly increased, due to the reduction of the weight of the high impacts and sharing that budget around now.

If I drop the weights of all ghost spawns to 5, this is what happens (Option 2):

image

The amount of all ruins increases due to being able to fit more onto Lavaland. All ghost spawns now exist on approximately 40 percent of rounds.

Option 3 is set the high impact spawns to 5 weight, and the low use / low impact spawns to 10, which puts us at just over 35 percent of rounds having a chance to spawn a high impact ghost spawn, while keeping the lower used ghost spawns with reduced weight.

image

Thoughts?

**Comment by PowerfulBacon** [comment]
Option 1 or 2 seem the best to me. I'm happy with whatever choice you go with considering the analysis that has been performed on this. I am confident you have a good understanding of the effects of changing the costs

**Comment by Programs-The-Station** [comment]
> Option 1 or 2 seem the best to me. I'm happy with whatever choice you go with considering the analysis that has been performed on this. I am confident you have a good understanding of the effects of changing the costs

Sounds good. Just lowered the costs to 5, so just waiting on tests to finish now.

**Pull request merged**
