### PR TITLE
[Alpha test] Botany hydroponics Rework - Alpha v.1 (fix.2)

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
# Current Know issue
* plant will likely be weed-overtaken at weed level 5, and it is even before orange-blink warning.
You need to wipe weeds very often.
* Invasive spreading trait will not overtake nearby plants
* Pest spray isn't working.
To remove pest, you need to deconstruct and rebuild a tray.

# PR body

## About The Pull Request
Hydroponics rework
For alpha test, It's somewhere at 80% done.

* At during alpha test, I am going to find out how the new system goes
* No stat change system at the alpha test. the stat chagne will be added in future.

Note: there are some messy codes (mostly defines, and datums), and these should be cleaned properly.

## Why It's Good For The Game
Related bee forum posts
* Vol 1. Very draft - no need to read this: https://forums.beestation13.com/t/botany-rework-sneak-peek/17448
* Vol 2. Plant research: https://forums.beestation13.com/t/botany-rework-sneak-peek-2/18095
* Vol 3. Strange seed recycle: https://forums.beestation13.com/t/botany-rework-sneak-peek-3-strange-seed-cycling/18188
* Vol 4. New nutrient system: https://forums.beestation13.com/t/botany-rework-sneak-peek-4-new-nutriment-system/18217

Goals:
* Your plant is already best. You should be only careful of your plants growing.
* No powergaming plant growing (no 100 potency, 10 yield, 1 production speed)
* Extreme customisation of your plants

new botany wiki document: (chemical change listed)
* https://wiki.beestation13.com/view/User:EvilDragon/Guide_to_space_botanology

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

* https://youtu.be/_UYcJMo6MWw
How to grow a regular plant
* https://youtu.be/w-7bxJQfXrw
Strange Seed Recycle

</details>

## Plants
 - [x] add: Discovering plants now stores their trait and chemical data into Plant DNA Manipulator.
 - [x] add: Every research for plants having nutriment and vitamin increases its maximum reagent size by +0.5 (nutriment) and +0.25 (vitamin) in the gene data. (20 researches = 10 nutriment + 5 vitamin)
 - [x] tweak: Botany crops now bascially provides 200 discovery points, but you can not scan roundstarting crops any longer. (previously 150 points)
 - [x] del: plant doesn't no longer affected by chemicals (i.e. Saltpetre, Unstable Mutagen, etc) still, unstable mutagen can be used to find some weeds...
 - [x] tweak: potency no longer affects the chemical output. The stat now only involves the certain traits' effectiveness.
 - [x] tweak: plant at low potency aren't ridiculously small anymore.
 - [x] add: Roundstart variable to plants. Default=TRUE. Becomes FALSE on harvest. Used to prevent scanning roundstard plants
 - [x] add: Research_identifier variable to plants, which is a key to plant datas.
 - [x] tweak: Most plants have been updated. Check wiki page for the detail.
 - [x] add: Strange seed is now recyclable. You can mutate it into another itself. But a seed has its own cycle. Getting a lot of seeds from one strange plant doesn't mean you can get something a lot from randomness. It will result the same randomness.
 - [x] tweak: strange seed will always come with two chemicals and a trait at least.
 - [x] tweak: strange seed's random chemical size is now selected between 10~30.
 - [x] tweak: strange seed doesn't get random plant type anymore (weed, mushroom). This will be changed in future.
 - [ ] tweak: you likely less get the same trait from picking random traits (which means you get nothing)
 - [x] add: Plant's lowest HP is now -12. while -12~0 HP, plant doesn't take aging. If you want this plant growing again, you need to heal it.
 - [x] add: Plant only dies when they're old but also below 0 HP. (old = plant age>plage lifespan)
 - [x] add: new debug plant - debugging plant (admin spawn to research all traits at once)
 - [x] refactor: plants are now more precisely tracked through investigate_log and log_game procs. 
 - [x] refactor: Kudzu is now stored in botany investigate log.

## Miscelnous
 - [x] tweak: DNA sampler can scan harvested crops now, but roundstarting crops are not scannable.
 - [x] del: Floral somatoray (AKA flora gun) no longer works to botany, and is removed from tech. The item still exists.
 - [x] tweak: replaced Floral somatoray respawns as Strange seed. (i.e. ruins, lifebringer ship)
 - [x] tweak: megaseed vendor doesn't longer need to be hacked.
 - [x] del: megaseed vendor doesn't longer sell strange seeds.
 - [x] add: lifebringer's discovery scanner
 - [x] add: centcom's discovery scanner
 - [x] add: centcom's plant gene manipulator
 - [x] balance: Exotic seed crate has been repriced to 10,000 credits. (This will be rebalanced in future)
 - [x] refactor: apply_type variable is now located in /obj/item/reagent_containers, from /obj/item/reagent_containers/pill
 - [x] refactor: qdel plants and its genes properly
 - [x] tweak: biogenerator now accepts vitamin as 50% more efficiency than nutriment.
 - [x] tweak: grinder now accepts vitamin as 50% more efficiency than nutriment for juicing and grinding

## Bees
 - [x] tweak: Bees can possibly reduce growing ticks by 10% (20 ticks to 18 ticks) - lasts until harvested.
 - [x] tweak: Bees can possibly increase plant harvest output by 30%. (10 yield to 13 crops) - lasts until harvested.
 - [x] del: Bees no longer increases yield stat
 - [x] del: Bees no longer increases potency stat.
 - [x] add: Bees will take damage from carnivory plants.

## Botanist
 - [x] tweak: Botanist is now a member of R&D department mainly along with being in Service department.
 - [x] tweak: Botanists' access has been updated to be a member of R&D.
 - [x] tweak: Botanists' boss is now Research Director, and their second boss is Head of Personnel. 
 - [x] balance: Botanist's payment is increased to medium level.
 - [x] tweak: Botanist now starts with 'Botani-science radioset' which can communicate in Service and Science channels.
 - [x] tweak: Botanist's RPG title is now 'Druid'
 - [x] add: Botanist now starts with Discovery Scanner which can be used to research botanical crops. Once researched, chemical and traits are stored in a Plant DNA manipulator.
 - [x] add: lifebringer's botanical research scanner (which is bound to their Plant DNA Manipulator)
 - [x] tweak: Lifebringer's Plant DNA Manipulator (from their previous manipulator)
 - [x] add: Lifebringer podperson's ruin now starts with Lifebringer's Discovery Scanner
 - [x] add: CentCom botanical research scanner
 - [x] add: CentCom Plant DNA manipulator
 - [x] add: CentCom now roundstarts with CC botany scanner

## Others
 - [x] tweak:  R&D members get hydroponics access as a normal access(RD) or a minimal access(Others). Geneticists and exploration crews are exampt.

## Plant DNA Manipulator
 - [x] del: plant gene diskettes is removed from the whole game
 - [x] del: plant gene diskette storage is removed
 - [x] add: Plant DNA manipulator now can insert genes and chemicals without a disk. But you need to research a harvested crop first through a Discovery scanner.
 - [x] add: Plant DNA manipulator can't modify a seed which isn't researched anymore.
 - [x] add: Plant DNA manipulator now can adjust the amount of plant chemical within the limit.
 - [x] add: Plant DNA manipulator now can mutate seeds into what you want as once they're researched.
 - [x] add: Plant DNA manipulator can edit plant seed name, plant name and plant description.
 - [ ] add: Plant DNA manipulator can provide the information of innate traits of plants.
 - [x] add: botany_research_type variable to the machine which is used to check which faction the machine belongs to. (*station, or lifebringer)
 - [x] tweak: Red light on a tray means "plant's HP is below 0" or "plant's age is above its allowed age" which means you need to pay more attention - previously it only means it's damaged.

## hydroponics
 - [x] tweak: Hydroponics tray nutrient maximum is now 12.
 - [x] tweak: Hydroponics tray water capacity is now 120.
 - [x] tweak: dirt nutrient maximum is now 8.
 - [x] del: most hydroponics plant chem reactions. You still can use unstable mutagen to get kudzu or spider.
 - [x] del: irrigation feature is removed. It's really not helpful, and bad at intuitiveness.
 - [x] del: self-sustaining tray (by earthsblood) feature is removed. (the whole botany system is less harsh now, so, no worries)
 - [x] add: You can remove a tray's nutriments now. (alt click a tray)
 - [x] add: Deleted the tray old efficiency system
 - [x] tweak: wiping dead plants or spading plants now replenishes nutriments and water, purges weeds, pests and toxin. Replenished nutriment type is EZ nutriment.
 - [x] add: a dead plant will self wipe if it's too dead for long time.
 - [x] refactor: botany on_grow proc now works based on given chance.
 - [x] add: using a cultivator needs 2s activation time now.

## New nutriments
 - [x] tweak: a tray will remember a list of taken nutriments. (i.e. Robust Harvest×5, Earthsblood×3, EZ nutriment×2) You can check a list by examining a tray.
 - [x] add: hydroponics tray consumes a nutriment as first-in first-out, while dirt would pick a random nutriments within the nutriment list of its inside. Consumed nutriment has an effect for each.
 - [x] add: earthsblood no longer makes your tray permanently sustainable.
 - [x] add: Nothing: when you fertilise a plant with a nutriment which isn't special, the nutriment type is nothing, and does nothing. (i.e. fertilise a plant with a nutriment recursively.)
 - [x] tweak: EZ nutriment: Does nothing. 66% chance to resupply itself to a tray. - Good basic nutriment.
 - [x] tweak; Left 4 Zed: Heals a plant's HP by 2. If it's below 0 HP, heals by 4. - Advanced healing nutriment
 - [x] tweak; Robust Harvest: takes an age more, but consumes a nutriment without its effect.
 - [x] tweak; Earthsblood: purges all weeds, pests and toxin, and refills water.(Does not heal) 80% chance to refill a unit of nutriment as Earthsblood, and 80% chance of preventing a plant aged. - Specialised nutriment with a big pentalty.
 - [x] tweak; Omnizine: Purges all toxins, but creates 4 level of weeds. - Specialised nutriment
 - [x] tweak; Unstable Mutagen: a plant takes two ages more, but takes 50 toxin damage
 - [x] add: new chemical 'Ashen blood' as a nutriment+healing chem. heals all damage including cell/organ damage by 0.2 or 0.1. but bad side effects to non-ashwalkers. Only available in lavaland tobacco (ashwalker roundstart tobbaco). Detail in chem wiki page.
 - [x] add: Ashen blood: 25% chance to resupply itself to a tray. Kills all pests.
 - [x] balance: water doesn't remove botany toxin anymore.

## Plant traits
 - [x] add: Traits now have a level that how many it should be researched to be unlocked. For example, Perenial Growth needs to be researched 3 times.
 - [x] bugfix: Invasive spreading trait no longer overtakes the same plants.
 - [ ] tweak: Liquid Contents trait will spill 5u of each reagents unless they're synthflesh medicine types. (i.e. silver sulfadaizine)
 - [x] rebalance: Hypodemic Prickle trait has been changed - It will only inject 10x metabolism rate of each chemical and will give the victim for inject immune for 30s. If a chemical has an extreme metabolisation, it only injects 5u.
 - [x] tweak: Hypodemic Prickle trait works with melee attack (it has been only worked by ranged throwing.)
 - [x] tweak: If a plant with Hypodemic Prickle trait contains 0 chemicals, it will self-destruct.
 - [x] tweak: Bluespace Activity provides teleport protection for 60 seconds once you're teleported by this trait. (You don't get this immunity if you use it for yourself.)
 - [x] tweak: perennial growth penaltizes a plant growing speed by 20% regardless of production speed or maturation speed.
 - [x] add: Separated chemicals is back, but only limited to Glow Berries. You can't get this trait to other plants. (by the way, Glow Berries max volume is now 10u)
 - [x] bugfix: Fire Resistance trait applies fire proof ability to plants and seeds properly.
 - [x] add: New botany trait - "Eternal Blooming" disables the ability to harvest, but the plant will never die. Roundstart trait data.
 - [x] add: New mood status "eternalbloom" - once you touch an eternal blooming plant, you get +1 mood boost for 5 minutes.
 - [x] add: New botany trait "Pastable Paste"-  plant becomes a patch type, but has a longer duration to apply based on its chem size. (100u/2 = 5 seconds + basic 3 seconds) If interrupted, the plant disappears. Need Liquid Contents trait togather. Comes from strange seed random.
 - [x] add: New botany trait "Embiggened Size" - makes a plant x2 bites than normal. Roundstart trait data.
 - [x] add: New botany trait "Acid Resistance" - plant becomes acid proof. Comes from strange seed random.
 - [x] add: New botany 'blocking' traits. These traits are used to block to add certain traits to certain plants. They are not researchable and don't come from trait RNG. (I.e. 'incompatible perenial growth')
 - [x] balance: Hypodermic Prickles and Separated Chemicals are not compatible to each other.
 - [x] add: most traits now work with melee attacks.

## Unfinished (Not necessary in Alpha test)
 - [ ] each plant needs a fake trait for a description what a plant does.
 - [ ] wiki update for fake traits (i.e. holymelon antimagic)
 - [ ] DNA manipulator shouls show a pop up description to explain what a trait does.
 - [ ] Plant stat change system
 - [ ] plant family gene system
 - [ ] plant gene system refactor. Make them into a single datum than multiple stat datum. (i.e. Potency datum, Product speed datum... into single datum.)
 - [ ] plant family design
 - [ ] plant distill reagent fix
 - [ ] make some comment-ised lines working actually
 - [ ] re-adjust most plant stats
 - [ ] hypodermic maximum size is 20u?
 - [ ] plant stats should be refered from datum/gene, not obj/seeds
 - [ ] pest as insect - insect level should be middle or plant dies.
 - [x] known issue - starthistle is not available to research
 - [ ] change vendor department? Being service looks fine.
 - [ ] decrease nutrimax nutrient bottles - make biogenerator a thing
 - [x] botanist hud is now purple
 - [ ] bad trait: fragil weed - random generated weeds have this, and not researchable
 - [ ] make tray researchable when plant is harvestable
 - [ ] plant instablility - gets lower by plant age. Fast harvest doesn't work.
 - [ ] plant damage should be stronger
 - [ ] plant analyzer should show chemicals
 - [ ] fix invasive spreading
 - [ ] lavaland strange plant should have their own name?
 - [ ] only plant analyzer should show nutrient list, not just eye examine, or it should be a tray, not dirt.
 - [ ] put more trays to hydroponics
 - [ ] retexturing lavaland tobbaco - more like black/reddish
 - [ ] askwalker needs a better way to grow
 - [ ] ashwalker needs a seed maker (portable one doesn't look working)
 - [ ] ashwalker doesn't look to have any cultivator
 - [ ] new tray - wooden tray. Better than dirt, worse than hydro tray
 - [ ] replace some dirt with wooden tray (i.e. pubby chappel garden, box garden)
 - [ ] make some more garden at stations?
 - [ ] plants (harvestable) at a tray should be scannable through discovery scanner
 - [ ] replica pod should be harvestable even if there's no blood injected
 - [ ] wiping dead plant should return seed
 - [ ] weed overtake should return seed
 - [ ] botanists might need science goggles to check if it's researched
 - [x] pest killer is broken - fixed
 - [ ] vitamin/nutriment should be reserached first
 - [ ] eternal blooming trait should supply nutrient itself
 - [ ] more special nutrients: pest bringer, weed grower, weed preventer, etc, for special plants
 - [ ] botanist in kilo doesn't have access
 - [ ] more seeds in vendor
 - [ ] bioluminescence in pumpkin
 - [ ] essntial traits should be flag removed upon research
 - [ ] ghosts should be available to examine plants
 - [ ] wiki fix (separated chemicals)
 - [ ] wiki fix - most traits
 - [ ] wiki edit - more stat info

## Changelog
:cl:
add: new botany. check the change log above. (This is testmerge purpose one, as not going to be merged yet.)
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
Liquid contents at low pressure or high pressure should explode themselves on a turf they are on.

**Comment by FortSumter** [comment]
I'd like a better description on what this does besides "It's WIP." I personally like botany the way it is currently and so I'd like to know if this will make one of my favorite departments better or worse and what was the main reason why you think it needs to be changed at all...

**Comment by EvilDragonfiend** [comment]
> Not sure I like anything that makes obtaining strange seeds more difficult than it already is. 

This PR is giving a big buff to Strange Seed though. You can mutate Strange seed into Strange seed, so that you can recycle it, but it follows a cycle.

>  I like that you want to re-add separated chems but it really should be just re-added all together.

Separated chemicals was removed because it was bullshitty powerful. I won't add it as it was before, but it will still be usable as a material for your botany building.

So, This isn't just nerfs. This has big buffs too.

**Comment by dwasint** [comment]
As a concept i really like this, makes strange seeds not just a click fest and gives botanists something to do. Gives a bit more depth to botany that isn't in the direction TG went.  I was brainstorming something like this up to granted mine went in a different direction that got shelved. I can't wait to see the final product on this one.

**Comment by dwasint** [comment]
Okay after trying this out in local, i have some concerns that i wish to air out. without the chemical interactions how are you intended to increase the stats of plants, are we just expected to keep them at low levels at all time as i did not see the option to transfer stats between plants.

**Comment by EvilDragonfiend** [comment]
> how are you intended to increase the stats of plants

That's the most problem for now. I really don't like the chem interaction way to change your plant, so I am trying to find out how I would, but I couldn't find any best yet.
The solution I thought is at least, uh, a kind of another gene manipulation. for example, if you research a lot of plants, you get gene points based on the amount of researched plants, and you can add the points to plants increasing its stats.
It's simple solution, but I want more depth way than this.

**Comment by EvilDragonfiend** [comment]
> Gives a bit more depth to botany that isn't in the direction TG went. 

And, yes, They removed gene manipulator, but instead, I thought that would be a key to go for us.

**Comment by dwasint** [comment]
> > Gives a bit more depth to botany that isn't in the direction TG went.
> 
> And, yes, They removed gene manipulator, but instead, I thought that would be a key to go for us. Removing the powergaming factors from botany, and utilising what we would like to have at maximum.

Honestly i don't think this removes the powergaming factor if anything this makes it scarier, the biggest issue i see is deathnettles inserting 10x the metabolism of the chem, wouldn't it be meta to just shove a ton of 1 unit chems into it? and just maxcap there reagents

**Comment by EvilDragonfiend** [comment]
> the biggest issue i see is deathnettles inserting 10x the metabolism of the chem, wouldn't it be meta to just shove a ton of 1 unit chems into it? 

Hypordemic prickle trait's most stupid feature is that it injects its chemical based on the portion of how many it has. If you have 100u of a chemical (and let's say its metabolisation rate is 0,05u), it will inject 20u, and it will persist 400 ticks to you.

Actually, the 10x ticks one should be still adjusted, but at least it prevents you to be stong again for 30 seconds. this means it would likely be one-time usable combat stuff for stinging purpose.

**Comment by EvilDragonfiend** [comment]
also, if you need to leave the hydroponics for a long time, you can put some earthsblood as it can literally stasis aging/dying, or plant will stop aging once it is too damaged.

**Comment by dwasint** [comment]
> > the biggest issue i see is deathnettles inserting 10x the metabolism of the chem, wouldn't it be meta to just shove a ton of 1 unit chems into it?
> 
> Hypordemic prickle trait's most stupid feature is that it injects its chemical based on the portion of how many it has. If you have 100u of a chemical (and let's say its metabolisation rate is 0,05u), it will inject 20u, and it will persist 400 ticks to you.
> 
> Actually, the 10x ticks one should be still adjusted, but at least it prevents you to be stung again for 30 seconds. this means it would likely be one-time usable combat stuff for injecting purpose.

i'm just scared of say a tomato with prickle has like 30 reagents at 1 unit and they just whip it at you, suddenly your reagent cap is filled with god knows what they threw at you if its say 5 toxins your most likely just dead

**Comment by EvilDragonfiend** [comment]
> 30 reagents at 1 unit
ah, right, I forgot to put a maximum for this. I am only going to allow 8 chemicals at max.

**Comment by dwasint** [comment]
> > 30 reagents at 1 unit
> 
> ah, right, I forgot to put a maximum for this. I am only going to allow 8 chemicals at max.

that seems more reasonable

**Comment by dwasint** [comment]
> also, if you need to leave the hydroponics for a long time, you can put some earthsblood as it can literally stasis aging/dying, or plant will stop aging once it is too damaged. plant will never die as long as it's not too old (if not age>lifespan)

wouldn't weeds still nuke the plant outside of age? things like gaia for instance have a high base weed rate or is that only on stage grow now?

**Comment by EvilDragonfiend** [comment]
> > also, if you need to leave the hydroponics for a long time, you can put some earthsblood as it can literally stasis aging/dying, or plant will stop aging once it is too damaged. plant will never die as long as it's not too old (if not age>lifespan)
> 
> wouldn't weeds still nuke the plant outside of age? things like gaia for instance have a high base weed rate or is that only on stage grow now?

I removed weed invsasion for now. The current plan is, when a weed nuke happens, it should produce the original seed onto a tray.

**Comment by dwasint** [comment]
One last thing i will warn you about, this makes omega weed insanely strong as you get access to like 15 drugs and can minmax the combat drugs in plants with your system

**Comment by EvilDragonfiend** [comment]
> One last thing i will warn you about, this makes omega weed insanely strong as you get access to like 15 drugs and can minmax the combat drugs in plants with your system

other contributors are going to make drugs fucked. I think it would be fine. I already know this custom chem mix can be strong already.
but also, botanists can get a more powerful drug from their RNG pool though (like uplink drugs)
so, I guess It's okay.

**Comment by EvilDragonfiend** [comment]
> One last thing i will warn you about, this makes omega weed insanely strong as you get access to like 15 drugs and can minmax the combat drugs in plants with your system

ah, also, there's a bite-size system. unless it has a good bite size (like apple), you need to eat a plant very multiple times.

**Comment by dwasint** [comment]
> > One last thing i will warn you about, this makes omega weed insanely strong as you get access to like 15 drugs and can minmax the combat drugs in plants with your system
> 
> ah, also, there's a bite-size system. unless it has a good bite size (like apple), you need to eat a plant very multiple times.

you have a patch trait though, making meta mixes isn't that hard

**Comment by EvilDragonfiend** [comment]
> > > One last thing i will warn you about, this makes omega weed insanely strong as you get access to like 15 drugs and can minmax the combat drugs in plants with your system
> > 
> > 
> > ah, also, there's a bite-size system. unless it has a good bite size (like apple), you need to eat a plant very multiple times.
> 
> you have a patch trait though, making meta mixes isn't that hard

The only problem is applying them has awful time, and it disappears if you are interrupted. So the trait is strong, but has critical downsides.

**Comment by PowerfulBacon** [comment]
Failing tests

**Comment by dwasint** [comment]
> From what I can tell this is a major botany nerf. And I'm strongly against it, if I can't work to put better potency on plants like holymelon then why bother putting effort into it? If someone needs bulk wood I can't even have fun with the request because the only thing you can even do is sit around staring at the plant, waiting for the indicators to tell you what tool to click on the tray with.

potency has no affect on amount on chemicals now, as for the other point its literally the same? before it was click a button once to magic the seed to max yield than stare at the tray until harvest. This is a massive W to botany, i can min max plants to provide literal perfect healing now

**Comment by cw0** [comment]
Finally got to playtest last night. I could be fine with a lot of these changes but I do have a couple of concerns. Most departments get upgrades to make things faster so that as the game progresses you can easily make more complex items. Gold trays let botanists spend more time playing god and less time running around micromanaging trays. I think gold trays should probably stay. I know the current weed system is bugged but as a solo botanist its almost impossible to keep the trays going and have time to research. I don't know why clearing weeds has a timer on it, but it definitely compounds this problem. When the weeds get dialed back this may be less of a concern but my shift was 95% tray management. The new sequencer was pretty intuitive but I didn't get a lot of time to use it from having to panic weed the whole shift. I didn't get to play antag but I am curious about the shenanigans I can make in house. I like that separate chems is back, still think its a bit small but I'll try and come up with something that can kill people with it before I knock it too hard. Some of the cool downs concern me a bit as well but again I'll try it first. I like the new console and I'm super down to not spam the hell out of mutagen and fertilizers. Overall though I'm ok with the direction just needs some balances.

**Comment by WrillWasTaken** [comment]
> also wanna address your ooc comment about bees, i think this is a buff aswell?

Bees gave double before, now they give 30% more from what I can see. I don't see how that's a buff.

**Comment by EvilDragonfiend** [comment]
this will be delayed because of the damn stat change redesign. It's headaching.

**Comment by ike709** [comment]
Stale, ask for reopen if you're still working on this.

**Comment by EvilDragonfiend** [comment]
I will ask to reopen once I can commit more updates. It is still draft.

**Comment by EvilDragonfiend** [comment]
For those who wonder how this goes: This is currently paused as I should approach it with **remake** level.
This rework will not make the botany properly better, so I am redesigning things, but with having some core features of the current features.

**Pull request closed without merging**
