### PR TITLE
Brig physician changes

### PR DESCRIPTION
**Pull request by Therealdoooc213**
## About The Pull Request

Removes brig physician medical access and moves it to skeleton crew access.
I've also placed a surgical duffel bag and nanomed + in every map that has a brig physicians office

## Why It's Good For The Game

brig physicians should spend most of their time in the brig, not medbay. If the medical bay needs extra help they can go to the head of personnel and ask for it but they shouldn't be acting like a doctor with sec access, 'doctor thats allowed to validhunt', etc.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

image
(not taking a picture of brig med with every single map, go check the map-diff bot)

</details>

## Changelog
:cl:
feature: brig physicians office now starts with a surgical duffel bag, and a nano-med +.
balance: brig physicians medical access has been moved into skeleton crew access.
balance: brig physicians locker now spawns with 1 of every type of station medkit (again)
/:cl:

### CODE REVIEW

**Review by Tsar-Salat — APPROVED** [review]
Yeah, this makes sense. I like the idea.

The purpose of the Brig Physician is their jobtitle. It is my understanding that their primary purpose is that of treating prisoners and being the second line of treatment for officers.

 I think if this had been done a few years ago, antag brig phys would not have been nearly so contentious.

### Requests

PR needs to describe what SOP is going to change. Should be clear so peeps with the high-level wiki editing perms can edit the SOP page.

**Comment by Tsar-Salat** [comment]
> ## About The Pull Request
> Brig physicians act "medical doctors with security access", "security that can roll antag", or a validhunting doctor.

Divide your `About` & `Why its Good` sections cleanly though, please.

**Comment by DarnTheMarn** [comment]
Unless it got changed since my PR, the brig physician does have surgical duffel bags already in their locker

**Comment by Fronsis** [comment]
> Unless it got changed since my PR, the brig physician does have surgical duffel bags already in their locker

Not all maps i think, i've seen complains of brig phys asking where their surgical bags are and there were nowhere to be found.

**Comment by Tsar-Salat** [comment]
Requesting Bacon's review because mortals cannot make SOP edits

**Comment by PowerfulBacon** [comment]
Torn on these changes, I could definitely see a world where its just more annoying than anything else to not be able to access medbay and medical is the primary department that the brig physician belongs to

**Comment by Therealdoooc213** [comment]
I've decided to readd the medkits to the brig physicians locker. They are meant to heal a entire department worths of people alone and a kelotane and charcoal pill bottle wont cut it.

**Comment by DarnTheMarn** [comment]
I changed my mind on this, this is a half measure that just leaves the brig physician in a weirder spot than it is now. It's true that the brig physician doesn't have enough to do to really justify their existence, but that doesn't mean you should just artificially restrict them from being helpful during down time. What will they do without medbay access? No boards, no chems, no patients. 

So they'll just sit around. Doing nothing. Being bored as hell. The devils hands are idle playthings I'm sure they'll figure _something_ out. 

I agree with the basic idea that a brig physician should in theory be a **brig** physician not a doctor with valid hunt privilege. But the fact is there just isn't quite enough content at 30-40-50-60 even 70 pop to justify a whole role just to heal maybe 5-7 people. That is why I believe in making brig physician a sub type of medical doctor like how exploration crew gets dedicated engineering/research/medical crewmembers. That means that they could spend most of their time in medbay without a twinge of guilt, but there's still somebody available to step in when Joe Redshirt gets his brain blown out by a .357 round. It would also make it more clear that they are part of medical, not security, and their job isn't to kick ass and take names pulling bodies out of the jaws of slaughter demons but instead just be the guy who heals prisoners and security.

**Comment by MarkusLarsson421** [comment]
Why not simply give Brig Phys a single advanced medkit? It'll have everything, including toxin medicine in the form of Pentetic Acid.

**Comment by Rukofamicom** [comment]
If this goes through Brig Physician needs to go back to answering to the HoS. This PR solidly moves them back into being exclusively a member of security rather than a member of medbay under the CMO.

**Comment by Therealdoooc213** [comment]
> If this goes through Brig Physician needs to go back to answering to the HoS. This PR solidly moves them back into being exclusively a member of security rather than a member of medbay under the CMO.

I think this was mentioned on a discord discussion, somebody will need to change the wiki.

**Comment by Fronsis** [comment]
While i'm not a fan of the medical access change and i'd rather not see it.. I do think it's quite urgent for the brig phys to have a surgery bag, i've confirmed that multiple stations lack them and they were accidentally removed/forgotten on the last update that brig phys office got, and i could even suggest a basic surgery bed for the ones that have a simple bed(Meta for example)

**Review by spockye — APPROVED** [review]
signed off map-wise. 

image

only thing i dont like is the placement here!

**Comment by PowerfulBacon** [comment]
I don't believe pulling brig physician out of medical is a good change and I don't see the benefit in doing so

**Review by PowerfulBacon — APPROVED** [review]
I change my mind since I see how confusing and arbritrary putting them in medical is when they are a security role after playing.

**Pull request merged**
