### PR TITLE
[Port] Departmental Refactor

### PR DESCRIPTION
**Pull request by XeonMations**
## About The Pull Request

Makes department code into a subsystem, dehardcoding stuff along the way

Partially ports @EvilDragonfiend's:
- https://github.com/BeeStation/BeeStation-Hornet/pull/9057

## Why It's Good For The Game

Refactors for the better are good, allows for future PRs and less headaches down the line

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image
</details>

## Changelog
:cl: EvilDragon, XeonMations
refactor: Refactored departmental code, making it nicer (hopefully)
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
I will review this first. other maints don't have to waste their time to review before it's fully ready.

**Comment by Tsar-Salat** [comment]
> I will review this first



is there a status on this? It is needed for modsuits

**Comment by EvilDragonfiend** [comment]
> > I will review this first
> 
> is there a status on this? It is needed for modsuits

I am editing his PR by myself. I will manage it within a week.

**Comment by XeonMations** [comment]
To do:

Fix being able to set assistant to yes and a second role to high

**Comment by Tsar-Salat** [comment]
> I will manage it within a week.

👀

**Comment by EvilDragonfiend** [comment]
If it has everything that your job refactor PR needs, it might be fine to go. To check that, checkout this to your job refactor PR will work.

**Comment by XeonMations** [comment]
about damn time

**Comment by EvilDragonfiend** [comment]
It's okayish to review now

**Review by PowerfulBacon — APPROVED** [review]
Seems fine, datumisation in this way is a solid improvement over random defines scattered around

**Comment by PowerfulBacon** [comment]
Kind of disappointed that this still fetches the departments by a string value and not by their typepath, but it otherwise seems like a general improvement and isn't worse than what we had already.

**Pull request merged**
