### PR TITLE
Makes Lizards Digitigrade Only

### PR DESCRIPTION
**Pull request by HowToLoLu**
## About The Pull Request

Made to pair with #11112 

Makes lizards only have digitigrade legs, replacing the non-digitigrade legs in code.

Implicit species-related-stuff approval from @Rukofamicom :
https://discord.com/channels/427337870844362753/943311132007997490/1258790078952509521
image

## Why It's Good For The Game

To quote the implicit approval, the human like lizard legs practically "were originally added for entirely meta game reasons in the golden era"

Doing this makes them slightly less of a carbon copy of humans which is good given how they are already barely different gameplay wise.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
del: Removed human-like lizard legs in favor for digitigrade
imgdel: Replaced the human-like lizard leg sprites with the digitigrade version
balance: Lizards are now all digitigrade
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
I personally don't like it. We'll talk about more in dev team.

**Comment by EvilDragonfiend** [comment]
🔑 I put my key against this anyway regardless of how and what we'll discuss in dev team.

**Comment by Rukofamicom** [comment]
> why should this restriction be general to all lizardpeople?

Because it makes the race more distinct to have these sorts of quirks and drawbacks.

**Comment by PestoVerde322** [comment]
> > why should this restriction be general to all lizardpeople?
> 
> Because it makes the race more distinct to have these sorts of quirks and drawbacks. As with many of the things I push, it used to be the norm until lizards got homogeonized.
> 
> > Lizard Jani mains cant be slipping on their own cleaning stuff ;-;
> 
> Then they can add some ammonia to their water to make it space cleaner _like janitors are supposed to do so nobody slips in it_ This is the kind of interactions that are good because they lead to players utilizing other solutions.

you can also loot maint, find a booze dispenser and use vodka or gin as a cleaning solution, which is not only astounding but also amazing. However truth is, why the hell there's no ammonia or space cleaner jugs in the Janitor's?

**Comment by Howluinb** [comment]
This is a good PR, it's an easy way to make lizards different from every other race in a unique way, while not having that many drawbacks (toe stub is gone, that was the *main* problem digi lizards had to face!)
I genuinely do not understand why you'd be against this unless you just want to play human but colored differently and with a tail

**Comment by Rukofamicom** [comment]
I must correct my history - this did not used to be standard for Lizards.

I still think it's a good change regardless.

**Comment by Rukofamicom** [comment]
Pulled up votes from other maints:
2 for
2 against
1 neutral 

This is a mixed enough opinion that I don't think it's a good idea to move forward with or even deal with the aftermath of a larger vote/awareness.

**Pull request closed without merging**
