### PR TITLE
Renames Cat Surgeon to Deranged Surgeon, applies upgrades, and makes it a midround antag

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
Cat Surgeon is no longer limited to felinids and can also be a Moth or Lizard surgeon with equal weight.
Deranged Surgeon is now a midround antag with weight 10 (default weight). Additionally, the Deranged Surgeon's space adaptation (at 4 victims) now actually works, the surgeon also now starts with dark vision and gains a medhud after two victims.
Additionally, generated moth wings are no longer invisible.

## Why It's Good For The Game
Right now cat surgeons aren't much to be scared of, the det will stroll on by and pop two bullets into one and it will fall over dead. This brings a bit more terror to seeing a potentially-sentient cat surgeon (although I expect that most sentient ones will have no more than five or so victims before dying). Additionally this adds some more variety to the midround pool.

## Changelog
:cl:
add: The Cat Surgeon has been renamed to the Deranged Surgeon, and can also now be a Moth Surgeon or Lizard Surgeon
add: The Deranged Surgeon is now a midround antagonist.
add: Deranged Surgeon now has dark vision by default, and gains a medical hud after two victims.
fix: Deranged Surgeon's Space Adaptation after two kills now actually works.
fix: Generated/admin spawn moth wings are no longer invisible
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based based

**Comment by TeomanTheGreat** [comment]
give them a randomized name so it isn't just the same thing over and over again

**Comment by BrumalLake** [comment]
i assume they can beat the shit out of pacifists or felenids though which should be addressed
not gonna look at the code and see if the ai chooses whether or not to heal or the attack does
i'll assume it's tested

**Comment by williamcll** [comment]
What happens if the attacker is a felinid?

**Comment by zeskorion** [comment]
The issue with cat surgeons right now is that their AI keeps freezing and taking several ticks to start attacking and dodging even when attacked

**Comment by Ivniinvi** [comment]
This specific PR has nothing to do with the surgeon's AI, the Cat Surgeon it spawns is sentient.

**Comment by francinum** [comment]
This is a bad idea.

**Comment by ghost** [comment]
> This is a bad idea.

usual fun police strikes once more

**Comment by Ivniinvi** [comment]
> This is a bad idea.

Could you tell me why you think it's a bad idea, so I have feedback to improve upon?

**Comment by francinum** [comment]
I'm mostly not a fan of this because it falls into the exact same corner as the original cat surgeon.

It's entire joke is making fun of a race not for any actually funny reason, but because 'haha funny degenerate'

It breeds this awful attitude that has more than once spilled over into some pretty nasty OOC behavior.
I have no interest in encouraging it.

**Comment by Fronsis** [comment]
I'd rather have the Rat-King midround antagonist than the cat-surgeon, specially because i agree with Fran that it's not a behaviour that needs to keep being encouraged

**Comment by Ivniinvi** [comment]
Cat surgeon is no longer just a cat surgeon, it can also be a moth surgeon or lizard surgeon.

**Comment by williamcll** [comment]
> I'd rather have the Rat-King midround antagonist than the cat-surgeon, specially because i agree with Fran that it's not a behaviour that needs to keep being encouraged

I don't like the Rat-king spawn. You can stuck in one room in maint and die from punching the door.

**Comment by Fronsis** [comment]
> > I'd rather have the Rat-King midround antagonist than the cat-surgeon, specially because i agree with Fran that it's not a behaviour that needs to keep being encouraged
> 
> I don't like the Rat-king spawn. You can stuck in one room in maint and die from punching the door.

Tbh i never seen it on play, not sure how it is on tg but for me a Rat King would be a mid round antag that lurks around maint, some iconic rat abilities and basically fucks power by chewing wire and stuff

**Comment by ghost** [comment]
> > I'd rather have the Rat-King midround antagonist than the cat-surgeon, specially because i agree with Fran that it's not a behaviour that needs to keep being encouraged
> 
> I don't like the Rat-king spawn. You can stuck in one room in maint and die from punching the door.

Use vents or hide till some greytider opens the airlock. skill issue

**Pull request closed without merging**
