### PR TITLE
Rad brig rework

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request

The majority of the Brig has been redesigned without moving the original locations of most of the rooms.

## Why It's Good For The Game

Polishes Rad Station Brig and redesigns it with the prison in mind.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image 
</details>

## Changelog
:cl: Markus Larsson
balance: [RadStation] added an extra Security hardsuit (total of 3)
tweak: [RadStation] remade the majority of the brig and its prison
fix: [RadStation] fixed the Science APC connection
fix: [RadStation] fixed the exosuit output direction
tweak: [RadStation] removed cursed grille at atmospherics space airlock
/:cl:

### CODE REVIEW

**Comment by BriggsIDP** [comment]
noting down things as i sport them, but overall like and approve this change!
image
decals
image
swap?
image
windows?
image
sec decals to remove
image
fire locks

**Comment by MarkusLarsson421** [comment]
> noting down things as i sport them, but overall like and approve this change!

Fixed, commited and pushed.

I also swapped around the table and clothing vendor.
image

**Comment by MarkusLarsson421** [comment]
> HEY!!!!!!!!! I paid a lot of cookies and *gukkles threats to Floria to have a Guillotine on the Brig execution room!!!! i demand it back!!!!

Everything you might need to make a Guillotine!
image

**Comment by MarkusLarsson421** [comment]
The PR is ready for review.
image

**Comment by MarkusLarsson421** [comment]
Fuck, I forgot the rad shelter.

**Review by BriggsIDP — APPROVED** [review]
👍

**Review by PestoVerde322 — APPROVED** [review]

**Pull request merged**
