### PR TITLE
Loaded bullet overlays on guns

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

- Ballistic guns will now display the projectile that is current loaded into them.
- Russiain revolver is excluded.

## Why It's Good For The Game

Useful to know how guns are loading their projectiles and what is currently loaded in your gun.

## Testing Photographs and Procedure

https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/714d3de8-9555-4f69-a5d0-157deedf1adb

https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/9f0eac3a-9be8-4494-9fb7-6f7d4df2e665

## Changelog
:cl:
add: Guns will now have an overlay showing what projectiles are currently loaded.
/:cl:

### CODE REVIEW

**Comment by DrDuckedGoose** [comment]
> Russiain revolver is excluded.

What's the reasoning there?

**Comment by PowerfulBacon** [comment]
So you can't see when the chamber is loaded since then you know when you are going to shoot yourself

**Comment by VickiMorris** [comment]
I love this change, especially with the revolvers. Having a visual about how ammo is queue'd up in the cylinder is really cool looking and seeing the empty casings cycle off to the side with each shot.

**Comment by EvilDragonfiend** [comment]
I like it but there's a disturbing point that you can notice how many bullets left immediately even if you're not the one who owned the gun. This means anyone who steals a gun from someone will immediately notice how many times they can use. I only don't like this point.

**Comment by PowerfulBacon** [comment]
True, maybe I should make it so you have to insert the mag. Or I could make it so you can only see the bullet in the chamber and not the ones in reserve

**Comment by PowerfulBacon** [comment]
I don't want to maintain this and it will require some code changes to make it work with other people giving you an unloaded/rigged gun

**Pull request closed without merging**
