### PR TITLE
[Port] Wizard Spellbook TGUI and fixes

### PR DESCRIPTION
**Pull request by Sarchutar**
## About The Pull Request

<details>
<summary>Ported PRs</summary>

- tgstation/tgstation#56958
- tgstation/tgstation#57361
- tgstation/tgstation#58939
- tgstation/tgstation#64997
- tgstation/tgstation#67844
- tgstation/tgstation#73090
- tgstation/tgstation#76872
- tgstation/tgstation#45376

</details>

Updates the wizard spellbook to TGUI since the old one was a bit dated. Includes a randomizer and four wizard presets.

Fixes wizard apprentice contract, slaughter and laughter demon refund amount/limit.
Previously refunding a slaughter demon or apprentice contract only gave back one spellpoint.
And before refunding a laughter demon also increased the limit of slaughter demons as well.

Changes the owner of the spellbook to be the wizards mind instead, so respawned liches and mindswapped wizards can use their spellbook. (Refunding while not in the wizard den still is not allowed)

## Why It's Good For The Game

The current interface looks a bit old and the new one would be a QOL thing for wizards. (It does come with a searchbar as well)
Refunding the correct amount of points for the contract and bottles is also a good fix.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

https://github.com/user-attachments/assets/c0901ba2-d5ec-4928-a470-626bb6611cf7

</details>

## Changelog
:cl: Sarchutar, tralezab, Timberpoes, CoffeeDragon16, san7890, MrMelbert, Arkatos1
add: Wizard Spellbook TGUI, with a randomizer and four presets
fix: slaughter demon bottles and apprentice contracts now give back their full point amount when refunded
fix: refunding a laughter demon doesn't raise the buy limit of slaughter demons anymore
fix: liches and mindswapped wizard can use their spellbook again
/:cl:

### CODE REVIEW

**Comment by Sarchutar** [comment]
I did not know how the randomizer should be handled considering wild magic is a thing, i left both in for now which can be changed if wanted.

**Comment by Fronsis** [comment]
Bless you, just yesterday i was talking about it! this will be a massive QoL

**Comment by Sarchutar** [comment]
@PowerfulBacon Haven't pushed the changes yet but this is how it would currently look with one page only, had to do some changes to it to make it look right.
I can change stuff should it not be good.

<details>
<Summary>Image</Summary>

Screenshot_4

</details>

**Comment by PowerfulBacon** [comment]
Oh yea, I like that a lot

**Review by PowerfulBacon — COMMENTED** [review]
Update testing evidence to show what the other pages look like (main front page and contents page) and then I'm happy to merge this.

**Comment by Sarchutar** [comment]
> Update testing evidence to show what the other pages look like (main front page and contents page) and then I'm happy to merge this.

I updated the testing evidence and also fixed some visual stuff i seem to have overlooked while i was at it.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
