### PR TITLE
rebases to no code

### PR DESCRIPTION
**Pull request by dinnerwoerror**
## About The Pull Request

completely rebases beestation to no code at all

no code is the best way to write a secure and reliable application
write nothing; deploy nowhere

## Why It's Good For The Game

More balanced as there is no more unbalanced content
Much more efficient, compiles and runs instantly
Perfect for admins, players can't break rules if there's no game

## Changelog
:cl:
TOTAL REBASE: no code
/:cl:

### CODE REVIEW

**Comment by FancyCyclops** [comment]
This will fix the overpowered medbay problem.

**Comment by Epsilos** [comment]
how can it have failed checks? these .dms should be no code too to make sure

**Comment by dinnerwoerror** [comment]
you see, the failed checks are most likely a result of no code dating back to about 2016, and it's obviously running into some issues regarding our modern code

**Comment by triplezeta** [comment]
Finally, we can close those 73 issues we have.

**Comment by zeskorion** [comment]
conflicts

**Comment by MarkSuckerberg** [comment]
I'm not seeing any pressing issues, and the conflicts can be fixed

**Comment by triplezeta** [comment]
why was this closed no god fuck

**Comment by dinnerwoerror** [comment]
damn, i lasted 13 minutes, meanwhile beepsky nulls and cloning removal are out here getting merged

**Comment by FancyCyclops** [comment]
A sad day indeed. The players just don't know what they want.

**Comment by dinnerwoerror** [comment]
zeskoranges probably out here using tilt controls in mario kart 8

just gonna keep this out there, qwerty, Ike, cenrus, zeskoranges, mark, i have the solution to all of your problems out here

**Comment by MarkSuckerberg** [comment]
There's an error in the description, it actually takes 0.2 seconds to compile for me, but that could just be my PC.

**Pull request closed without merging**
