### PR TITLE
Adds an extra total clown slot.

### PR DESCRIPTION
**Pull request by ClownMoff**
##About The Pull Request 
Adds an extra total slot for clown (not roundstart)

## Why It's Good For The Game

Clown is an unique role that represents the game itself and getting one slot only means whoever rolls it roundstart has to wait until next round to play the job they want (unless they do a job change, which is not truly clownery), and sometimes a clown doing a clown gimmick in another department (something I've done) or just being SSD takes hostage the role for the rest of people. So. One more clown slot. And I hear you, you may be worried about shittery, but I don't think that's a problem. 2 clowns can make a lot of things together, having a buddy gives you so much freedom to do more stuff like preparing shows, staging elaborated pranks, etc, etc. I think it would be fair to give it a chance. In my long experience as clown (Numbah 1 in Bee baby) having 2 clowns is better than one.

## Changelog
:cl:
add: New total clown slot

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
I believe some other server made the second Clown a subpar version. I'd say that would be better.

However, this doesn't change the fact that Beestation is most of the time low-pop and therefore having two Clowns when you might not even have an Engineer, Miner, Scientist, or even a Security Guard, is not fun for antagonists and non-antagonist alike I suspect. Clowns exist to "clown around" and not set up teslas or do any other work of high importance.

This feels like a change to simply give yourself a higher chance of playing Clown when it is high-pop and others want to play Clown, too.

**Comment by ToasterBan** [comment]
clowns can add a lot of chaos to a round, maybe have an extra clown slot be a station trait?

**Comment by Nakalon** [comment]
I agree with both comments here.

We already have the janitor station trait, this could be a good thing to add as one.

But yeah if this would just increase the "Clowns do other peoples jobs" phenomenon I don't see the need for it and actually think its deterimental to the round.

**Review by Crossedfall — COMMENTED** [review]
We already have two non-serious roles, clown and mime. We don't need three dedicated slots for it. A clown being AFK all round doesn't honestly impact things in any meaningful way, they are far from essential. 

Do more with your mime friend.

**Pull request closed without merging**
