### PR TITLE
lobbied players can vote now

### PR DESCRIPTION
**Pull request by CthulhuOnIce**
title

### CODE REVIEW

**Comment by qwertyquerty** [comment]
We use 
```
//[BEGIN BEE EDIT]
//[END BEE EDIT]
```

**Comment by qwertyquerty** [comment]
If I would have made this PR you woulda probably been like "lmao just override the proc"

**Comment by CthulhuOnIce** [comment]
fuck off its like 12 characters and doesn't add any new lines

**Comment by CthulhuOnIce** [comment]
@qwertyquerty  happy now hoe?

**Pull request merged**
