### PR TITLE
Adds night vision science goggles, because I was asked to!

### PR DESCRIPTION
**Pull request by RDS88-beeman**
## About The Pull Request
Adds night vision science goggles to the techweb and lathe. It's purple!

## Why It's Good For The Game
It gives scientist new drip and rounds out the HUD whateverillogy, because they didn't have these before.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image
It's on the techweb!
image
Emissives!
image
Holdsprite, it's cool.

</details>

## Changelog
:cl:
add: Science goggles. Night vision. Put them together, now you've got night vision science goggles. Print some at the science lathe.
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
Perhaps add it to Medbay too? Seeing as the Chemists have them, Chemists use them more than scientists, I think.

**Review by PestoVerde322 — APPROVED** [review]
It's good to go, approved.

**Comment by RDS88-beeman** [comment]
Far as I can tell, medical can't print science goggles as-is. That's not hard to change, but it's a bit out-of-scope for this PR.

**Comment by MarkusLarsson421** [comment]
> Far as I can tell, medical can't print science goggles as-is. That's not hard to change, but it's a bit out-of-scope for this PR.

Can Science...?

**Comment by RDS88-beeman** [comment]
Think so.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
