### PR TITLE
Removes the Pheromone Receptor ability

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Removes the changeling pheromone receptor ability. Ruko said this is a good idea and I agree.

## Why It's Good For The Game

The 'Absorb another changeling.' objective is long gone, so this ability is unnecessary. Lings have other ways of identifying each other, and this one is way too easy and leads to problems. Absorbing another changeling should be more effort than just buying an ability and surprise attacking them.

## Changelog
:cl:
del: Removed the Pheromone Receptor ability from changelings
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I don't see a problem with this ability.

**Comment by Archanial** [comment]
I wonder who did it first 🤔

**Comment by PowerfulBacon** [comment]
> 
> 
> I wonder who did it first 🤔

The original creator of changelings probably 🤷

**Comment by FriendlyContractor** [comment]
Hunting down other changelings to increase your power looks cool on paper but in reality it never happens because its not beneficial as other changelings are almost always friendly and willing to cooperate with you. Having a changeling partner is way more beneficial than absorbing them for few extra DNA points. Since removal of absorb another changeling objective this ability is only ever used by changelings cooperating with security and having to deal with what is basically a walking antagonist pinpointer who has security on their side is not very fun experience.

**Review by PowerfulBacon — APPROVED** [review]
Their abilities are pretty bloated too so

**Pull request merged**
