### PR TITLE
Lavaland 2.0

### PR DESCRIPTION
**Pull request by PestoVerde322**
## About The Pull Request

This Pr aims to snap from the curse that plague pretty much every SS13 server, the same, bottom left corner mining area that's been sitting there since the lavaland was created.

On top of that, lavaland's gulag was lagging behind in matter of content, so I gave the gulag some option for doing other stuff aside mining, like botany or some sleeping area, just to make it so that's no longer a instant boredom zone if you get gulag'd.

This moves the lavaland to a central position, alongside some detail changes and QoL addition to both the mining outpost and the gulag.

## Why It's Good For The Game

For one of the most neglected area of the station, it really needed some breath of fresh air.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

dreamseeker_Ovrj8WiEfG

dreamseeker_O3Y9otIgc4

dreamseeker_YUDaDWkjVT

dreamseeker_6JYB27ohXV

</details>

## Changelog
:cl:
add: Added a brand new lavaland, featuring a Sauna, proper cooking equipment, a gulag that doesn't look like a nanotransen 2x2 jail and overall more aesthetic than before
/:cl:

### CODE REVIEW

**Comment by PestoVerde322** [comment]
> there should be a beaker in prisoners' hydroponics, or they can't use biogenerator.
> 
> Also, it looks like you need to put a spade and a cultivator.

ah good point, I'll add those immediately.

**Comment by Sarchutar** [comment]
That bomb testing site seems to be a little to close to the science outpost, considering bombs have a larger range on lavaland

**Comment by Rukofamicom** [comment]
please no merge until gateways have been considered 😭

**Comment by EvilDragonfiend** [comment]
> please no merge until gateways have been considered 😭
> 
> #6802

Loser gets extra work.

**Comment by RDS88-beeman** [comment]
Doesn't the game spawn rarer ores the higher up on lavaland you go? What reason would anyone have to ever go south outside of megafauna/ruin hunting?

**Comment by PowerfulBacon** [comment]
on a planet full of lava and the sauna uses a space heater

**Comment by PowerfulBacon** [comment]
> Doesn't the game spawn rarer ores the higher up on lavaland you go? What reason would anyone have to ever go south outside of megafauna/ruin hunting?

I'm pretty sure thats a myth

**Comment by RDS88-beeman** [comment]
huh

**Comment by Rukofamicom** [comment]
> I'm pretty sure thats a myth

It is. The only difference in ore spawning is Gulag rocks vs the rest of lavaland. Gulag has less rare ores.

**Comment by PestoVerde322** [comment]
> Doesn't the game spawn rarer ores the higher up on lavaland you go? What reason would anyone have to ever go south outside of megafauna/ruin hunting?

yep, the spawn rate of... everything is universal, however the one in the gulag and the one in proximity (usually defined by area) to the mining outpost are less rare, while in the so called "unknown zone" is more common to see higher end ores (and higher end enemies)

**Comment by DerpiestBruh** [comment]
TBH I think it would be nice for the dorm rooms to have personal closets

**Comment by Fronsis** [comment]
Damn, now this will be more amazing whenever they do a station-in-lavaland event! thanks for the contribution

I would personally remove the brute-burn kits from the medbay and only leave a regular one+toxin(?), mostly because we've been pushing against the idea of miners having a lot of heal in their bags and completely avoid visiting medbay, they should micro-manage their survivor pen and cores and play more carefully around that, rest looks amazing and i'm certain the gulag will be more fun for the prisioners! next step is perma and to add prisoner role 😳

**Comment by FortSumter** [comment]
I'm not sure if you understand the point of the gulag. It's really just a form of execution except this way you aren't culpable for them dying.

**Comment by St0rmC4st3r** [comment]
> I'm not sure if you understand the point of the gulag. It's really just a form of execution except this way you aren't culpable for them dying.

It is not a form of execution. It is just an option of applying a punishment. Even a thousand points is not that much.

**Comment by FortSumter** [comment]
It was a joke. The majority of the time the gulag has been used I've gone down there as sec to check on an inmate only to find a body floating in lava.
I get what it's meant to be used for, but....

**Comment by St0rmC4st3r** [comment]
I am sad that nobody is looking at this.

So I will.

image
Labor Capm lockdown button

image
I guess these should be closed


image
Did you intend an AAC in here? The vent does nothing right now.


image
Could use a light over here

image
Why is there a monitor decryption key here?

image
Where is the button?

**Review by St0rmC4st3r — CHANGES_REQUESTED** [review]
Address the concerns in the screenshots, please.

**Comment by itsmeow** [comment]
@St0rmC4st3r Fixes were added

**Review by PowerfulBacon — APPROVED** [review]
Yolo

**Comment by PestoVerde322** [comment]
> Yolo

Unfathomably based.

**Pull request merged**
