### PR TITLE
Makes Mimes better

### PR DESCRIPTION
**Pull request by Cenrus**
## Related PRs

https://github.com/tgstation/tgstation/pull/47177/
https://github.com/tgstation/tgstation/pull/47420/

## About The Pull Request

Mimes can only use emotes on their PDAs. Adds 30 new emotes.

## Why It's Good For The Game

Mimes who talk using their PDA are bad mimes.

## Changelog
:cl: tralezab
add: The mime's PDA messages are silent now!
tweak: Mime's invisible box lasts twice as long.
/:cl:

### CODE REVIEW

**Comment by Sinmero** [comment]
What about writing on a paper?

**Comment by Cenrus** [comment]
They can still do that.

**Comment by ike709** [comment]
You tested this, right?

**Comment by qwertyquerty** [comment]
@Cenrus looks like you might have missed some changes to emojis.dmi to add the 30 new emojis?

**Comment by Cenrus** [comment]
Turns out our emojis dmi file is already up to date, so I didn't have to change it. Sorry, forgot to remove that change from the description

**Comment by Cenrus** [comment]
I tested it and couldn't find any issues.

**Comment by ike709** [comment]
what could go wrong?

**Comment by ACanOpener** [comment]
You took away essentially the only way mimes can communicate any message while not directly in front of them. Shame on you.

**Comment by bloons3** [comment]
"I saw him steal HoP’s card and tried to robust him with a chainsaw for that sweet gamer loot. I talked to the CMO through PDA, but the mime never messaged me so it didn’t occur to me at the time he was my BB. I only later found out that mimes cannot send PDA messages."

https://forums.beestation13.com/t/guilleco-player-report/5011/7

wack

**Pull request merged**
