### PR TITLE
Webhook Processor Ports

### PR DESCRIPTION
**Pull request by Crossedfall**
Ported PR: https://github.com/tgstation/tgstation/pull/54120

> ## About The Pull Request
> Add documentation as to which GitHub webhook events the Webhook Processor expects

----

Ported PR: https://github.com/tgstation/tgstation/pull/55038

> Basically no one ever hits the lower limit and people have fucking bank at this point.
>
> https://tools.tgstation13.org/pr_balances.json
> 
> Sorted in descending order: https://p.smx.lt/mELIPJX

---

Ported PR: https://github.com/tgstation/tgstation/pull/55199

> Unit tests (a label I recently added) will now give 6 GBP. This label should be added to anything that adds a new unit test, even on features.
>
> OK'd by Cyberboss.
> ## Why It's Good For The Game
>
> Giving people more incentive to write unit tests should (hopefully) prevent regressions. Giving me more work to do will prevent me from working on features.

---

Ported PR: https://github.com/tgstation/tgstation/pull/55441
> ## About The Pull Request
>Some rescaling since the stakes are 10x higher now:
>
> - `Fix`: +3
> - `Tweak`: -2
> - `Performance`: +12
> - `Priority: High`: +15
> - `Priority: Critical`: +20
> - `Feedback`: +2
> - `Code Improvement`: +2
>
>The intention with the formula tweak is for the highest absolute value of the label set (favoring the negative) to be applied.
>
>Some examples of how label combos affect totals:
>
> - `Tweak` + `Code Improvement`: -2
> - `Tweak` + `Fix`: +3
> - `Balance/Rebalance` + `Fix`: -8
> - `Balance/Rebalance` + `Refactor`: +10
> - `Feature` + `Refactor`: -10
> - `Tweak` + `Grammar/Formatting`: -2
>
> This is mainly to prevent case 3 currently giving +2 and case 5 giving +10
>
> Also buff starting GBP to `30` after that nerf to gains.

---

Ports PR: https://github.com/tgstation/tgstation/pull/55546
> ## About The Pull Request
>PHP Fatal error: Array and string offset access syntax with curly braces is no longer supported in ./tools/WebhookProcessor/github_webhook_processor.php on line 972 on line 17 of the Run Linters job of the CI Suite workflow.

### CODE REVIEW

**Comment by Crossedfall** [comment]
~~Will also port https://github.com/tgstation/tgstation/pull/55546 when it's merged in~~

**Review by francinum — APPROVED** [review]

**Comment by MCterra10** [comment]
I thought you didn't use the webhook anymore?

**Comment by ike709** [comment]
I thought we also don't use GBP.

**Comment by Crossedfall** [comment]
To answer both at once, we don't. All the changes are in the same file. I'm just keeping it up to date

**Pull request merged**
