### PR TITLE
Pulling tails gives a negative moodlet, felinids are startled and get negative moodlets when wet

### PR DESCRIPTION
**Pull request by PatienceStPim**
## About The Pull Request
Ports https://github.com/BeeStation/NSV13/pull/1830 with some slight changes.
Tail pulling will apply a negative moodlet, and felinids will get negative moodlets when wet be it from being splashed, the pool, or showering.

## Why It's Good For The Game
Makes felinids slightly more cat-like. Felinids are also described as disliking water in the character preferences, this reinforces that.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://youtu.be/tZieO2H6w5I

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: PatienceStPim, red031000
add: felinids get a negative moodlet when wet, and are startled when sprayed or splashed
del:  felinids will no longer get postive moodlets from "swimming"
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
Recommend the review of contributing.md

**Comment by EvilDragonfiend** [comment]
Okay, They asked for my approval for posting this. I don't know what I feel from this PR tho.

**Comment by TsunamiAnt** [comment]
didn't we want to cut down on misc mood modifiers? This seems excessive. I like what TG has where it just interrupts do_afters.
Felinid climbing your table? get the spray bottle.

**Comment by MarkusLarsson421** [comment]
> Felinid climbing your table? get the spray bottle.

I love this. xd

Why don't we have this? I'd also make felinds more unique and less of a human subtype but with hello kitty claws.

**Pull request closed without merging**
