### PR TITLE
Reconstructive surgery for moth wings

### PR DESCRIPTION
**Pull request by Jake-Wheal**
## About The Pull Request
This is a port of https://github.com/tgstation/tgstation/pull/51963, it adds a new advanced surgery which allows medbay to repair burned off moth wings with the use of synthflesh. It modifies the relevant tech node and medical designs to include this under the appropriate research. It also slightly modifies the mothmen species, as wings being burned off currently destroys that genetic information.

## Why It's Good For The Game
Currently burned off moth wings are the only mutant body part which cannot be repaired or reattached by medbay. In fact they cannot be restored by any in-game means (including magical healing and aheals) other than variable editing.

Moth wings confer minor in game benefits and are part of a character's visual identity. At the price of time (and the cost of synthflesh) players now have the option of having an otherwise permanent injury fixed.

## Changelog
:cl:Alt_Alpha9
add: Added reconstructive surgery for moth wings, requiring synthflesh
bugfix: Magical healing and aheals now restore moth wings
/:cl:

### CODE REVIEW

**Comment by Jake-Wheal** [comment]
shoot I forgot to change a file, don't merge this yet

**Comment by Jake-Wheal** [comment]
alright it's now complete, yall can merge it if that's what you wanna do

**Comment by eeSPee** [comment]
I think it should check whether your human has moth wings and they are currently burnt, instead of whether you are operating on a moth.

**Comment by Jake-Wheal** [comment]
> I think it should check whether your human has moth wings and they are currently burnt, instead of whether you are operating on a moth.

I can see where it checks wether or not you are a moth but im afraid I don't know what I would replace it with

**Comment by Jake-Wheal** [comment]
@eeSPee I removed the check for whether or not the target it is a moth but it still only does the surgery if the target has burnt wings. Does it looks okay to you?

**Comment by eeSPee** [comment]
Well I was gonna check the wing organ, but dna["mothwings"] should be enough. Even though, on theory, it should work on anyone with moth wings, only humans of the moth species can actually get their wings burnt off.

**Comment by Jake-Wheal** [comment]
> Well I was gonna check the wing organ, but dna["mothwings"] should be enough. Even though, on theory, it should work on anyone with moth wings, only humans of the moth species can actually get their wings burnt off. 

Is that something I should fix or something for another day and another PR?

**Comment by eeSPee** [comment]
> > Well I was gonna check the wing organ, but dna["mothwings"] should be enough. Even though, on theory, it should work on anyone with moth wings, only humans of the moth species can actually get their wings burnt off.
> 
> Is that something I should fix or something for another day and another PR?

Something future coders will wrap their minds about.

**Pull request closed without merging**
