### PR TITLE
[TM Ready] The return of single Z CorgStation

### PR DESCRIPTION
**Pull request by williamcll**
## About The Pull Request

This is my attempt to bring back PowerfulBacon's CorgStation, one of the first original beestation maps, along with some minor fixes.
Additionally, Science shuttle docking is added next to the exploration office for more flexibility, following fland and kilostation.

This is my first time doing a bigger PR so bear with me.

## Why It's Good For The Game

Variety is good, curb that metastation addiction! Corgstation is one of the most shuttle friendly stations and helps promote supercruise despite all the rebalances it made.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
add: Single Z-level Corgstation added.
add: Science shuttle access on-station.
tweak: unconnected maintenace wires connected, excess wires removed.
tweak: multi Z-level Corgstation disabled until wire layer adapters are fixed.
fix: Supermatter thermomachine pipe overlap fixed.
/:cl:

### CODE REVIEW

**Comment by imsynthex** [comment]
Eh, I liked corg when it was originally single Z-level, good luck!

**Comment by PowerfulBacon** [comment]
Tip right of the map maintain should probably be connected to the hallway, the bedrooms in cargo could be deleted to allow for maints to connect up

**Comment by AnCopper** [comment]
Merging from master, uh oh.

**Comment by williamcll** [comment]
> Merging from master, uh oh.

I don't know what happened there, would be nice if someone can delete that commit, even though it doesn't actually change anything.

**Comment by williamcll** [comment]
<details>
<summary>Updates:</summary>
Modified cargo maintenance to increase access, the QM's room is now retired.

image

Botany intensified
image

Mops removed from robotics before they are useless
image

Re-arranged nanites
image

Central Science Maintenance added
image

</details>
TODO: replace all the firedoors with airlocks

**Comment by Fronsis** [comment]
I liked multi-z Corg because it was our first attempt to introduce the community to em but it had their issues but i liked original Corg so this is a good sight

**Comment by AgentCitrus** [comment]
If you’re still working on it, it might be helpful to mark the pull request as a draft.

**Comment by williamcll** [comment]
Firelocks done, please test it and see if there's any errors.

**Comment by PowerfulBacon** [comment]
Fails tests

**Review by Archanial — DISMISSED** [review]
No way we're adding second corg station to the game. 
Replace current (not working) version instead.

**Comment by williamcll** [comment]
> Fails tests

fixed, thanks to Lord Scrubling#7492 for finding out the punctuation error.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
I agree that there should not be an unused copy of CorgStation in the codebase, there should be the current working version of CorgStation and only Corgstation.

**Comment by williamcll** [comment]
I swapped the names for corgstation, so multi-z corg is now renamed and disabled.

**Comment by PowerfulBacon** [comment]
Remove the map files for corg

**Review by PowerfulBacon — DISMISSED** [review]
Ready for TM

**Comment by williamcll** [comment]
Ah fuck, 5 layer pipes doesn't lay well with my current PR, not sure what is the best course of action here.

**Comment by williamcll** [comment]
figured out how to fix the merge conflict, thanks lordscrubling

**Comment by williamcll** [comment]
TODO:
Fix missing explo vendors ✅
Fix missing explo comms ✅
Fix Explo office access ✅
Fix brings back Multi-Z corg explo shuttle ✅
Make Mining more asteroid friendly ✅

**Comment by PowerfulBacon** [comment]
The random maints need fixing 
image

image

This one just might have to be removed and replaced with some static maint room

image

Something got moved across but not fixed

image

Wrong room size

image

tf?

image

Airlocks must be in the center

image

Remove this one, or add a wall in the corner so its enclosed


image

Wrong room size

**Comment by PowerfulBacon** [comment]
image

**Comment by PowerfulBacon** [comment]
Don't put random maints in places that aren't fully enclosed and don't have doors at the center of the room

**Comment by ToasterBan** [comment]
Engineering is covered in RCDs, not so long ago they were removed from engi lockers due to them being powerful, mind removing them?

**Comment by PowerfulBacon** [comment]
Replace the armoury guns with the non lethal WTs used in the new corg

**Comment by PowerfulBacon** [comment]
image

**Comment by PowerfulBacon** [comment]
image

**Comment by PestoVerde322** [comment]
Aright I've took a good look at the map, the core components are mostly A-ok, however there's some oddities i've spotted:

immagine

All the airlocks, like this one, works fine, however in compliance with the Pipe Crusade, the better solution is to do something like this:

immagine

(without the airlocks in the way)

immagine

(almost) all the windows have a firelock window shutter, which with the current Atmos instance, they're not that much userful as they won't trigger 9/10 times.

this window isn't hooked up to the power grid:

immagine

Loose pipe/decal (x166-y172)

immagine

(also right above, there's a loose wire)

labour shuttle dock's piping isn't hooked up:

immagine

Suggest to hook those cables within the Wardner's office, as if in case security loses power, people can break in without getting shocked. this also apply to the security brig jails:

immagine

If someone sends something to security it will be ejected outside security:

immagine

On the more aesthetical side, this has always bothered me, since it's just grass being... there

immagine


There's probably way, WAY more out there, so I'll report at my best whatever is out there, so for now fix those

**Comment by williamcll** [comment]
> 

half of these were already fixed in the last commit, but I'll go see about the wires.

**Review by PowerfulBacon — COMMENTED** [review]
## AREAS WITHOUT AN APC:
/area/science/mixing/chamber
/area/tcommsat/relay

## AREAS WITHOUT AN AIR ALARM:
/area/tcommsat/relay

## Check intercome ranges in debug verbs, there are a lot of warnings for no intercomms

<details>

```
/area/engine/engine_room
/area/engine/atmos
/area/chapel/office
/area/engine/engine_smes
/area/engine/engineering
/area/maintenance/department/chapel/monastery
/area/maintenance/port/fore
/area/engine/storage
/area/science/xenobiology
/area/maintenance/port
/area/tcommsat/server
/area/chapel/main/monastery
/area/tcommsat/computer
/area/science/shuttle
/area/maintenance/department/science/central
/area/maintenance/solars/port/aft
/area/security/courtroom
/area/lawoffice
/area/engine/storage_shared
/area/hallway/primary/aft
/area/engine/atmospherics_engine
/area/quartermaster/exploration_prep
/area/security/checkpoint/engineering
/area/crew_quarters/heads/chief
/area/science/misc_lab/range
/area/hallway/primary/fore
/area/crew_quarters/fitness/recreation
/area/maintenance/department/science
/area/crew_quarters/toilet
/area/crew_quarters/dorms
/area/ai_monitored/storage/eva
/area/teleporter
/area/science/research
/area/science/server
/area/science/nanite
/area/maintenance/fore
/area/crew_quarters/theatre
/area/maintenance/solars/port/fore
/area/science/mixing/chamber
/area/science/mixing
/area/hallway/secondary/exit
/area/science/lab
/area/science/explab
/area/tcommsat/relay
/area/hallway/secondary/exit/departure_lounge
/area/crew_quarters/heads/hor
/area/storage/tools
/area/science/storage
/area/bridge
/area/security/nuke_storage
/area/ai_monitored/turret_protected/AIsatextAP
/area/security/checkpoint/science
/area/science/robotics/lab
/area/maintenance/port/central
/area/crew_quarters/cryopods
/area/ai_monitored/turret_protected/ai
/area/ai_monitored/turret_protected/aisat/foyer
/area/janitor
/area/hallway/secondary/service
/area/ai_monitored/turret_protected/aisat_interior
/area/maintenance/department/crew_quarters/dorms
/area/library
/area/hallway/secondary/command
/area/hallway/primary/central
/area/crew_quarters/bar
/area/crew_quarters/heads/hop
/area/science/robotics
/area/security/checkpoint/customs
/area/hallway/secondary/entry
/area/crew_quarters/heads/captain
/area/maintenance/department/bridge
/area/ai_monitored/turret_protected/ai_upload
/area/hydroponics
/area/crew_quarters/kitchen
/area/crew_quarters/heads/captain/private
/area/security/brig
/area/maintenance/starboard/aft
/area/engine/gravity_generator
/area/ai_monitored/security/armory
/area/construction/mining/aux_base
/area/hallway/primary/starboard
/area/security/prison
/area/security/warden
/area/crew_quarters/kitchen/coldroom
/area/medical/sleeper
/area/medical/medbay/lobby
/area/medical/medbay/central
/area/hydroponics/garden
/area/gateway
/area/medical/cryo
/area/maintenance/solars/starboard/aft
/area/security/main
/area/medical/chemistry
/area/maintenance/starboard/fore
/area/medical/storage
/area/security/detectives_office
/area/security/checkpoint/supply
/area/quartermaster/office
/area/medical/surgery
/area/crew_quarters/heads/hos
/area/medical/genetics
/area/quartermaster/storage
/area/quartermaster/sorting
/area/maintenance/starboard/central
/area/quartermaster/qm
/area/medical/genetics/cloning
/area/security/execution/education
/area/medical/medbay/aft
/area/quartermaster/warehouse
/area/security/checkpoint/medical
/area/crew_quarters/heads/cmo
/area/medical/morgue
/area/quartermaster/miningdock
/area/maintenance/starboard/secondary
/area/medical/virology
/area/maintenance/disposal
```

</details>

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
image
Remove the clown statue

image
image
This room needs the doors in the center, not at the top

image
This door needs to be centered

**Comment by PestoVerde322** [comment]
Just doublechecked the map again, all seems good (aside what bacon just pointed out that is), be sure however to put it up to standards with the zams' viro remap: https://github.com/BeeStation/BeeStation-Hornet/pull/6628

**Comment by PowerfulBacon** [comment]
Scientists can access this
image

Light switch and APC on same tile
image

No lights or lamps
image
Also the same area as the rest of sci, so light switch turns off the wrong lights

Virology is incorrectly mapped and has no pressure

**Comment by PestoVerde322** [comment]
immagine

I'd personally add some decals beneath those machines, but overall this new viro's all good to go!

immagine

Bad corner.

immagine

Not 100% sure if this would give issues down the line, maybe it will hot wire? maybe not? in doubt, just give more room to this solars.

immagine

Just noticed this, and while inherently service doesn't have many nasty things that can be used by greytiders... are you 100% sure you want the service lathe to be on public access?

immagine

Cable ends in nowhere.

immagine

No Cryo (not the medical tube, the other one) in medbay?

immagine

This zoning is weird, as the smaller zone will draw power from the main Tcomm, meaning if that's powerless, that door and freezer will be powerless.

immagine

Looks weird, give it one extra tile of room.

immagine
This booze-o-mat is in a peculiar situation, as it can be accessed on the other side as well.

immagine
Weird sofa.

immagine
As i mentioned in deadstation's pr, I don't think clustering all the assistant's spawners in the bar is a good idea, since it could lead to a tidal wave to the tech storage, distribute them around the station.

immagine
Interesting Gateway location... (not saying it's bad, but it's unusual to have it by the maint)

immagine

Why so many dual vents and why the layer adaptor goes over wall, give it some extra room to avoid a pipe crusade.

**Comment by PestoVerde322** [comment]
immagine

Stray terminal

immagine

Floaty Exclamation mark

immagine

Cable not connected

immagine

Weeeeeird wire in all of AI

immagine

Also virology misses a Viro Quarantine shutter in the virology lab door

**Review by PestoVerde322 — DISMISSED** [review]
After Reviewing this, I can safely say that this map is Good to go, however I strongly suggest to do one last Testmerge to see if the map behave correctly on highpop situations after the changes before merging and put the map in rotation.

**Comment by PestoVerde322** [comment]
Actually, hold on:

immagine

non-connected wires.

immagine

Cable going nowhere.

immagine

Missing cable.

Should be all within the reach of fixable pretty much instantly.

EDIT:

immagine

immagine

immagine

Missing pieces/rogue cables.

**Comment by PowerfulBacon** [comment]
Engineering doesn't start with magboots

**Comment by PowerfulBacon** [comment]
Did you do Kube's stuff?

**Comment by Rukofamicom** [comment]
image

Not an issue I found, but one I pinged about posting here without response.

**Comment by Megaddd** [comment]
~~Apparently the curator is missing a book binder~~
fixed

**Review by PowerfulBacon — APPROVED** [review]

**Review by PestoVerde322 — APPROVED** [review]

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
