### PR TITLE
Better Toolset Implants

### PR DESCRIPTION
**Pull request by Isy232**
## About The Pull Request

Changes the tools contained in the tool and surgical tool set implants to be alien ones instead of normal ones.

## Why It's Good For The Game

The toolset implants now are just boring. The surgical one is just the normal tools and the engineering one is the tools of an engineering cyborg. Both implants are worse than the advanced versions of their tools that you can print off at the lathe.

The alien tools are extremely cool. I remember when playing on Deathclaw they had the implants give the alien versions and they were really fun to use. In most rounds the alien tools are never seen, even though they are some of the coolest looking and sounding items in the entire game.

## Changelog
:cl:
tweak: Surgical Toolset and Engineering Toolset implants now give the alien versions of the tools.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Aren't they bad on purpose, since they are literally the full set of tools available at any time without needing any storage space?

**Comment by Isy232** [comment]
> Aren't they bad on purpose, since they are literally the full set of tools available at any time without needing any storage space?

I think implants should be cool, not downgrades from what is already widely available earlier.

Advanced tools only take up 4 storage spots, including the multi tool.

The alien tools are not much faster than advanced tools, which are widely available much earlier and do not require any form of surgery to use.

**Comment by Tamuren** [comment]
I think this is a great idea. Maybe we should vote?

**Comment by SomeAngryMiner** [comment]
while i approve of making the toolset implants better, maybe using *alien* tools is not the right way, since uh, that shit is very strong yo, and doesnt make sense unless the tech takes alien tech.

**Comment by Isy232** [comment]
I say vote this, if it fails I'll set it to advanced tools, like the hand drill and such.

**Comment by zeskorion** [comment]
borg tools already have higher success times IIRC. alien ones make no sense.

having nodrop tools that take no inventory slots is already insanely good

**Comment by Isy232** [comment]
> borg tools already have higher success times IIRC. alien ones make no sense.
> 
> having nodrop tools that take no inventory slots is already insanely good

Borg tools do but 

You get to choose between an arm blade and a shittier toolbelt. I think the choice is quite obvious.

Toolbelts fit in backpacks or a belt slot, carrying a full set of tools isn't hard.

Maybe there should be an advanced toolbelt implant but I find it annoying that you can only get an implant that isn't even as good as the advanced tools you can print off far earlier.

**Comment by Dingo-Dongler** [comment]
The main problem to me is the clunkyness. Having an implant should feel cool, like you can switch tools in an instant and don't have to fumble around. I tried to make them retract on drop and make it so you could extend using an empty hand (https://github.com/tgstation/tgstation/pull/47767), but I've never figured out how.

**Comment by zeskorion** [comment]
considering this can be emagged for the armblade anyways, and is already decent enough alone with no real reason to need such a huge, illogical buff, im gonna just close this

**Comment by githubuser4141** [comment]
> I say vote this, if it fails I'll set it to advanced tools, like the hand drill and such.

Aren't cyborg tools actually faster then RnD tools like the hand drill/JoL/ adv. welding tool? The only drawback is their clunkiness and the welder doesn't self-fill.

**Pull request closed without merging**
