### PR TITLE
Man up! smite

### PR DESCRIPTION
**Pull request by TsunamiAnt**
## About The Pull Request

Bay and such has this and i kinda like it. Other admins have expressed their interest too.

1984 etc

## Why It's Good For The Game

The IC issue button is fine and good, but sometimes you just gotta hit 'em with the mallet.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/user-attachments/assets/c9222d03-9565-4c7b-afd4-2289496fb4c3

</details>

## Changelog
:cl:
admin: Man UP! smite for admins.
/:cl:

### CODE REVIEW

**Review by Rukofamicom — APPROVED** [review]

**Comment by TsunamiAnt** [comment]
i might turn the stun length down, it's like 30 seconds right now.

**Comment by MarkusLarsson421** [comment]
I love it!!

**Comment by ClownMoff** [comment]
Can't wait to get hit with this when I ahelp security spacing me over a soap in the floor

**Comment by TsunamiAnt** [comment]
> Can't wait to get hit with this when I ahelp security spacing me over a soap in the floor

_Someone_ definitely was an inspiration

**Comment by ClownMoff** [comment]
Listen here you rascal I rarely EVER ahelp security doing anything unless they are skating over SoP and server rules

**Pull request merged**
