### PR TITLE
Reduce price of EMP Grenades and Implanter kit (4 to 2 TC)

### PR DESCRIPTION
**Pull request by Cenrus**
Undoes the price increase to the EMP kit made in https://github.com/BeeStation/BeeStation-Hornet/pull/1143, making EMPs a more affordable pick for traitors.

EMPs are important for antagonists when we have security cyborgs enabled, and serve as a good counter for energy weapons.

:cl:
tweak: EMP Kit has been reduced to 2 TC (previously 4)
/:cl:

### CODE REVIEW

**Comment by eeSPee** [comment]
I felt a great disturbance in the Force, as if millions of IPC mains suddenly cried out in terror and were suddenly silenced.

**Comment by utilbird** [comment]
It'd be better to fix sec borgs than buff a semi-universal gadget to counter it. 4tc was pretty good for what you got already.

**Comment by Isy232** [comment]
I think this is good, 4 TC is 1/5th of your supply just for an EMP kit. The grenades are barely useful because if you get searched its a dead giveaway, the implant is worth about 2 TC itself while the grenades are worth less than 1.

**Comment by utilbird** [comment]
implant itself is well worth 4tc compared to almost every other item a traitor can get.

Not everything has to be a braindead choice.

**Comment by utilbird** [comment]
Taken from my discord response:

This is bad. It'll make EMP kits a braindead choice instead of something you have to weigh the pros and cons on.
2TC implanter + grenades means you can pay next to nothing for an almost complete immunity to silicons. It's a hard counter against almost everything they can throw at you.

4TC was already dirt cheap, but it was _just_ expensive enough that not _everyone_ would buy it randomly as a cautionary get out of jail card free card. Players not utilizing a strong gadget doesn't necessarily mean said gadget should be buffed, look at other items that cost around 4tc, EMP kit is already dirt cheap for what you're getting

**Comment by heepox** [comment]
as long as there is a miner that gets uranium you can make 100 100 nade and emp a third of the station with one nade

only time i get emp kit is when i dont have any other implants too as EMP fucks em.

**Comment by VictorVow** [comment]
Eh I changed sec borgs so they're [no longer roundstart](https://github.com/BeeStation/BeeStation-Hornet/pull/3106) so they aren't nearly the menace they used to be. 2 TC is dirty cheap whereas 4 TC is still pretty fair.

**Comment by Fronsis** [comment]
Secborgs are only seen on big long rounds so i don't think we need the price of emp adjusted, old price is fine IMO

**Comment by Isy232** [comment]
> Taken from my discord response:
> 
> This is bad. It'll make EMP kits a braindead choice instead of something you have to weigh the pros and cons on.
> 2TC implanter + grenades means you can pay next to nothing for an almost complete immunity to silicons. It's a hard counter against almost everything they can throw at you.

EMP items are not a perfect fix to silicons. The EMP implant/grenade also EMP's you!

Since you EMP yourself you wreck your flashes and whatever charge you have on your guns. This basically means once you EMP a silicon you have no choice but to run away or use multiple EMP's to have enough time to kill it.
 
> 4TC was already dirt cheap, but it was _just_ expensive enough that not _everyone_ would buy it randomly as a cautionary get out of jail card free card. Players not utilizing a strong gadget doesn't necessarily mean said gadget should be buffed, look at other items that cost around 4tc, EMP kit is already dirt cheap for what you're getting

In my long time of playing this game I only remember this item being bought twice. Once by a nuclear operative and once by a traitor.

This kit is very mediocre in its current state. It costs 2/3rd of an emag and only works against silicons and energy weapons. It also affects you, so it pretty much prevents you from using energy weapons or flashes yourself.

You can make EMP grenades yourself with the most basic amount of chemistry knowledge so I would argue the grenades are not even worth a single TC.

I agree with lowering the price on this item, its only good in some situations and there are hefty drawbacks to using it.

**Comment by utilbird** [comment]
> In my long time of playing this game I only remember this item being bought twice. Once by a nuclear operative and once by a traitor.

Just because it's not used by others doesn't mean it's a bad item. I use the kit heaps, it's incredibly strong for 4tc.

> This kit is very mediocre in its current state. It costs 2/3rd of an emag and only works against silicons and energy weapons. It also affects you, so it pretty much prevents you from using energy weapons or flashes yourself.

Not really a fair comparison, the emag is the best traitor utility item in the game. Not every traitor item needs to be a braindead pick like the emag. If you compare the EMP kit with other things that are actually 4TC, it's really good.

> You can make EMP grenades yourself with the most basic amount of chemistry knowledge so I would argue the grenades are not even worth a single TC.

The grenades are just a side addition but they can be useful if you cook them and throw them at chasing silicons or you want to sabotage a department. Yes, chemistry grenades are better but they take some time to make (even if it's quick).

> I agree with lowering the price on this item, its only good in some situations and there are hefty drawbacks to using it.

Almost all of the main drawbacks you mentioned aren't really that big of a deal for what you're getting, an EMPd borg is a dead borg so long as you brought a weapon.

**Comment by FortSumter** [comment]
This isn't really a item traitors buy unless their assasination target is an IPC or the roboticist (or both!). This is more of an item people get from Nulls or buying a 20TC lootbox and will use liberally just to fuck over the crew and cause chaos. I don't really see how discounting it would change anything as it will never be any traitors first choice to use TC on, and the EMP flashlight will always be a better choice to spend TC on if you need a stealthy EMP instead of a box of obviously traitorous grenades.

**Comment by VictorVow** [comment]
I've never bought the flashlight, always gotten the kit so to each their own. Implanted EMP was a lifesaver against secborgs who disable you from a distance.

**Comment by utilbird** [comment]
🔑

**Comment by utilbird** [comment]
keyed by francium, closing.

If you decide to re-open anytime soon, I suggest splitting up the EMP grenades and the implanter into 2 different items

**Pull request closed without merging**
