### PR TITLE
Defib rework, organ damage effects, deja vu and muscled veins port

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
Organs now decay when not in a living host. Defibs thus have a loose timer for when a defibrillation can occur, but are dependent on things such as your heart/brain damage, which will decay at differing rates. As it is now, the heart decays fully in about 2.5 minutes, and the brain decays a lot slower, at around 30 minutes. The brain damage done to simulate decay for defibrillation was removed as a result. Furthermore, brain failure is caused when reaching max brain damage, or forceably removing the brain from its head. This also means that you can fix brains which reach their max damage thresholds by either pouring mannitol onto it, or by performing brain surgery on it.

The PR has:
- Extended defib timer from 2 minutes to 15 minutes
- Organ decay, with the standard decay reaching failing levels at about 15 minutes of decay
- The heart decays far faster, reaching failing levels at 3 minutes
- The brain decays twice as slow for balance reasons, since it still carries traumas over on cloning
- The heart and lungs both increase the rate at which you breath when severely damaged
- A damaged stomach will cause you to vomit depending on how much food you've eaten, and how badly damaged your stomach is. A failing one prevents digestion.
- A failing appendix will burst, causing toxic damage until removed. Appendicitis causes appendix damage when at its max stage.
- Damaged ears will cause bouts of tinnitus, which deafens the individual for a brief four second period as the ringing in his ears grows louder.
- Messages for when the above are damaged/failing to the owner
- Brain damage was moved to work off of brain.damage instead of brain.brainloss
- Removed decay factor from synthetic organs
- Strange Reagent heals all organs before revive, though that is subject to change (some organs may remain damaged)
- Freezers, coolers, and morgue units all prevent organ decay from objects held within
- Lobectomy, a surgical procedure that involves excising a decaying/damaged lobe within the lungs so that it no longer hinders its performance. Can only be done if lung damage is above 80. Sets the damage to 80, and clears the "failing" flag, making the organ usable again. Can only be done once per organ. 95% chance to succeed on the lobectomy step. Failing to perform the lobectomy will suffocate the patient momentarily as blood collects in their lungs.
- Coronary Bypass, a surgical procedure that does the same as the above surgery. 90% to succeed on both incising into the heart and grafting the bypass. Failing either step will cause damage to the heart, and massive amounts of bleeding.
- Organ Smartfridges, an organ storage device (stores significantly less than other smartfridges, 20 parts per tier of matter bin), BUT the device also repairs organs when upgraded beyond the first tier. Every tier beyond the first will repair organs by a magnitude of the normal healing rate, up to 7 times as fast as normal healing. This healing will not fix broken organs, however.
- Organs heal at a rate improved by your healthiness

**Other additions which were needed for this port**
- Regenerative sepia and rewind camera have a deja vu effect which resets all your limbs and damage to the point it was added after 10 seconds (as well as the original position reset).
- Added a new surgery, Muscled Veins, as the contrast to Vein Threading: it makes the patient able to survive without a heart.
- Undead and androids have no metabolism now, with the related upsides and downsides of that.

## Why It's Good For The Game
Having defibs work on a longer range but with more restrictions in regards to organ damage compliments the addition of stasis beds. This also provides a more involved alternative to cloning, as most individuals who come in who haven't been dead for longer than 15 minutes can be revived if you just replace all their organs and fix their brain for its inevitable damages. Synthetic organs will also be more attractive in both the regular and upgraded forms, as the regular synthetics will have the same amount of health buffs and decay decrease as that of the upgraded form when I get around to it, meaning it's a cheaper and easier alternative to giving everyone an upgraded heart.

## Changelog
:cl:
add: The deja vu effect (previously only used by rewind camera) now resets all your limbs and damage to the point it was added after 10 seconds (as well as the original position reset)
add: The deja vu effect cannot resurrect the dead, but will heal their corpse
add: New limbs fall off, old ones re-attach
add: Regenerative sepia cores add a deja vu effect before healing instead of a timestop
add: The rewind camera rewinds 2 times to distinguish it from the regenerative core
add: Androids, skeletons and zombies no longer metabolize reagents. As such they no longer benefit from healing reagents, nor are affected by poisons and toxins.
add: These species are now also immune to any other form of toxin damage.
tweak: Milk now also heals burn damage for skeletons.
add: Added a new advanced surgery, Muscled Veins: it makes the patient able to survive without a heart.
add: Organ Smartfridges! Store your organs safely. Upgrading the matter bin will give it the ability to heal organs held within- though this does not repair organs that are currently failing, however.
add: Lobectomy! Not lobotomy, but cuts out a damaged lung lobe to make its performance passable. Restores a lung to working order if it was too damaged to work before, but can only be done once. The lobectomy step has a 95% chance of success, so use some form of sterilizer to ensure you don't accidentally get blood inside your patient's lungs!
add: Coronary Bypass! Restores a heart to working order if it was too damaged to work before, but can only be done once. Both incising the heart and grafting the bypass have a 90% chance to succeed, and failing them will cause heart damage and massive amounts of bleeding- so be sure to work with ideal conditions, proper tools, and sterilizer!
add: Organs now decay when not in a living host
add: Severe heart damage increases breathing rate, and causes a heart attack on failure
add: Severe lung damage increases breathing rate, and causes suffocation on failure
add: Stomach damage will likely cause the owner to vomit depending on how injured the stomach is, and how much they've eaten
tweak: Brain damage effects now works similarly to the rest of the organ damage
tweak: Appendicitis will do appendix damage when in stages 3 and 4, which can cause it to burst if left
untreated
tweak: Organs heal faster the healthier the host is
balance: Defib timer has been extended to 15 minutes
/:cl:

Ports:
https://github.com/tgstation/tgstation/pull/43870
https://github.com/tgstation/tgstation/pull/44481
https://github.com/tgstation/tgstation/pull/44846
https://github.com/tgstation/tgstation/pull/45104
https://github.com/tgstation/tgstation/pull/45845

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
Hey, can you add a flag defaulted to false that will say that the organ doesn't decay? 
I just don't like how the chaplain's ever beating heart on some maps continues to beat after rotting away.
Also, IPC organs need it.

**Comment by Cenrus** [comment]
https://github.com/tgstation/tgstation/pull/47770
https://github.com/tgstation/tgstation/pull/46042

**Comment by qwertyquerty** [comment]
Doesn't pass checks

**Comment by VictorVow** [comment]
@qwertyquerty it needs the [tend wounds PR](https://github.com/BeeStation/BeeStation-Hornet/pull/1277) to be merged first.

**Comment by eLeCtrOssSnake** [comment]
fuck IPC's

**Comment by Cenrus** [comment]
merge eet

**Comment by VictorVow** [comment]
Going to open a new PR and sort out the conflicts

**Pull request closed without merging**
