### PR TITLE
Removes objective inheritance from IAA.

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Recently a bug was fixed with IAA that made objective inheritance work for IAA.
This means that the only way to succeed in IAA is to kill every single IAA agent and then kill yourself.

## Why It's Good For The Game

The gamemode has gone from kill 1 target and survive against your own target to the battle royale murderbone-fest. Objective inheritance is completely broken, poorly communicated and fundamentally flawed, which is why I am removing it instead of fixing it.

## Changelog
:cl:
del: Removes objective inheritance from IAA.
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
Last man standing is actually a cool concept. This is not murderbone fest, they are meant to kill only other traitors

**Comment by PowerfulBacon** [comment]
The only way to win is to kill every single agent and then stage a terrorist attack to get yourself killed.

**Comment by RDS88-beeman** [comment]
honestly the "kill every other traitor and then yourself" would be a fun gamemode as something rarer than wizard if you could make it work

**Comment by ghost** [comment]
> The only way to win is to kill every single agent and then stage a terrorist attack to get yourself killed.

It's been like this since IAA was implemented, I don't see an issue with it.

**Comment by PowerfulBacon** [comment]
> 
> 
> > The only way to win is to kill every single agent and then stage a terrorist attack to get yourself killed.
> 
> It's been like this since IAA was implemented, I don't see an issue with it.

No its been bugged the entire time and didn't give targets until it was recently fixed by Ike going through runtimes

**Comment by eeSPee** [comment]
> The only way to win is to kill every single agent and then stage a terrorist attack to get yourself killed.

You just gave me a idea for a killer mid-round antag.

**Comment by bloons3** [comment]
Shouldn't the fix be to make the pinpointer work for all new IAA targets?

Spy vs Spy until there's one man standing, not kill your target and hide in a space ruin until shuttle is called.

**Comment by FortSumter** [comment]
Fun removal Pr alert. All you need to do is make it so the last spy standing doesn't need to kill himself and make the pinpointed select new targets and you're good.

**Review by utilbird — APPROVED** [review]

**Pull request closed without merging**
