### PR TITLE
Gulag fix

### PR DESCRIPTION
**Pull request by ghost**
#2366 was accepted yet it isnt ingame, was it stealth reverted or something? this also fixes the missplaced APC.

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
Don't fix the APC, it is solved in the outpost PR.

**Comment by BeloneX** [comment]
> Don't fix the APC, it is solved in the outpost PR.

whats the hotkey for reverting in fastdmm?

**Comment by BeloneX** [comment]
> > Don't fix the APC, it is solved in the outpost PR.
> 
> whats the hotkey for reverting in strongdmm?

**Comment by Moccha-Bee** [comment]
the science base in lavaland already fiexs this,

**Comment by PowerfulBacon** [comment]
This is fixed by another PR, instead of plasma windows there are just standard walls which works much better

**Pull request closed without merging**
