### PR TITLE
Buffs laser shotgun shells.

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Increases the damage of laser shotgun shells from 8 to 12.

## Why It's Good For The Game

Laser shotgun shells have an insanely high spread and worse damage than regular shotgun shells.
This increases the damage of them from 8 to 12, so that they are better than normal buckshot shells in terms of damage and range (however their spread makes them suck at long range).

## Changelog
:cl:
balance: Laser shotgun shell damage increased from 8 to 12 per pellet.
/:cl:

### CODE REVIEW

**Comment by williamcll** [comment]
Nice, L to blob mains.

**Comment by PowerfulBacon** [comment]
> Nice, L to blob mains.

~~well there are already pulse shells which instakill blobs~~

**Comment by Isy232** [comment]
Didnt you nerf these before?

Oh wait no you rebalanced shotguns and nerfed a lot of other stuff.

Cenrus nerfed these back a while ago so more just a partial revert of that I guess.
https://github.com/BeeStation/BeeStation-Hornet/pull/4846

Yeah, basically halving their effectiveness was too much of a nerf, this number now seems reasonable.

**Review by Archanial — APPROVED** [review]

**Comment by PowerfulBacon** [comment]
:+1:

**Pull request merged**
