### PR TITLE
Adds incursion meeting place

### PR DESCRIPTION
**Pull request by Ivniinvi**
## About The Pull Request
Gives incursion members a meeting place.

## Why It's Good For The Game
Adds a more in-character method for Incursions to meet up.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
add: Incursion members are now given a meeting place on spawn.
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
🔑 
There's an ongoing discussion in dev discord channel, and we made some ideas, and one of the important things is:
* meeting places should be determined by themselves because 99% of the given places are so public that they can't say anything

We're expecting to tweak the incursionists' roundstart phase.

**Comment by PowerfulBacon** [comment]
Hold actions on this for the time being

**Comment by PowerfulBacon** [comment]
This is my current stance, but I am open to discussion and testing alternate (and simpler) approaches such as this as long as they have some thought in them. #9183

**Comment by PowerfulBacon** [comment]
This is redundant with the current state of incursion bringing back their radios

**Pull request closed without merging**
