### PR TITLE
Unifies the moth chest sprite

### PR DESCRIPTION
**Pull request by Pontenerd**
## About The Pull Request

Makes it so male and female moths both use the same chest sprite
## Why It's Good For The Game

Female moths currently have breasts and it's kinda weird considering they are insects, this makes it so that they look less mamalian (PR approved by Francium)

## Changelog
:cl:

tweak: tweaked the female moth sprite to match the male sprite

/:cl:

### CODE REVIEW

**Comment by Pontenerd** [comment]
what are you conflicting with

**Comment by Bokkiewokkie** [comment]
> what are you conflicting with

Local coder accidentally uses year old master to base branches off of

**Comment by Pontenerd** [comment]
> 
> 
> > what are you conflicting with
> 
> Local coder accidentally uses year old master to base branches off of

calling me a coder is a massive stretch

**Comment by Naevii** [comment]
Differences between male and female body types are good. 
I dont understand why remove option that gives you a tiny bit more customization and doesn't really impact the game in negative way.

**Comment by BrumalLake** [comment]
what is this it just makes the sprite a duplicate instead of just deleting the sprite and making both use the same sprite

**Comment by Isy232** [comment]
> Differences between male and female body types are good. I dont understand why remove option that gives you a tiny bit more customization and doesn't really impact the game in negative way.

Agree, however there are other far better methods to show a difference in gender besides the basic "give it boobs".

Female moths should be larger then male moths. (maybe give males like a 0.9x resize). To be true to their insect natures instead of just doing mamallian things.

Ideally this PR would also add this, but I do not see a downside to removing an inaccuracy for now.

**Comment by Naevii** [comment]
> > Differences between male and female body types are good. I dont understand why remove option that gives you a tiny bit more customization and doesn't really impact the game in negative way.
> 
> Agree, however there are other far better methods to show a difference in gender besides the basic "give it boobs".
> 
> Female moths should be larger then male moths. (maybe give males like a 0.9x resize). To be true to their insect natures instead of just doing mamallian things.
> 
> Ideally this PR would also add this, but I do not see a downside to removing an inaccuracy for now.

Giving it modifier makes sprites all blury. And shouldn't be used as a default option. 

And simply respriting moths to be bigger is hardly possible or at least not worth the efford. (you would have to resprite every piece of clothing etc)

**Comment by Pontenerd** [comment]
> Differences between male and female body types are good

While I do agree with you, I don't think giving moths boobs was the right way to go about this, I find Issy's idea of making female moths larger interesting, but you raised a good point as to why that's not practical.

**Comment by ToasterBan** [comment]
wether or not this will get closed or merged will be a big step away or towards BEERP

**Comment by FriendlyContractor** [comment]
Uh are we seriously having a  discussing whether moths should have breasts ?

**Comment by Howluinb** [comment]
I do not see why there needs to be a removal - just make it togglable. removing diversity & customization for no genuine reason is just terrible. Especially with how bad bee is with customization already

**Comment by francinum** [comment]
This technically passed vote, but it's also incredibly fucking stupid.

**Comment by Pontenerd** [comment]
Tragedy

**Pull request closed without merging**
