### PR TITLE
Nitpicks of Meta Station

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
Fixes and changes minor nitpicks that have been annoying me and others for a long time. Things that should be there but isn't or things that shouldn't be there but is there.

## Why It's Good For The Game
Bringing up the standard of Meta Station to that of other maps.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
Full map

Taking pictures of the changes and attaching the relevant change log(s) to that picture.

add: BZ Canister to Xenobio.
fix: Changed Xenobio cold room door to have a glass window. 
image

fix: Changed Science break room door to be Science themed. 
image

fix: Changed access of the southern Exploration door to be the same as the north maintenance door. 
image

fix: weird light placement in Medbay-Chapel Maints. 
image

add: Added an O2 canister in Aux base for the purpose of refilling oxygen tanks once on lavaland, welding tank was moved to Aux base maintenance. 
image

add: intercom to toxin testing room.
image

fix: Replaced Robotics Medical tools with a Medical Duffel bag. 
image

add: welding tool, welding goggles and floor tiles to the janitor.
image

fix: Brig Phys back walls with regular non-reinforced walls to allow break ins/outs and allow them to expand easier. 
image

add: camera to toxins to allow AI to see the inner door. 
image

fix: Moved a useless box and closet out of the way in Exploration maints.
image

</details>

## Changelog
:cl:
add: Meta: Added BZ Canister to Xenobio.
tweak: Meta: Changed Xenobio cold room door to have a glass window. 
tweak: Meta: Changed Science break room door to be Science themed. 
tweak: Meta: Changed access of the southern Exploration door to be the same as the north maintenance door. 
fix: Meta: Fixed weird light placement in Medbay-Chapel Maints. 
add: Meta: Added an O2 canister in Aux base for the purpose of refilling oxygen tanks once on lavaland, welding tank was moved to Aux base maintenance. 
add: Meta: Added intercom to toxin testing room.
tweak: Meta: Replaced Robotics Medical tools with a Medical Duffel bag. 
add: Meta: Added welding tool, welding goggles and floor tiles to the janitor.
tweak: Meta: Changed the flooring in maintenance areas on the station to be consistent with Medbay maintenance. 
balance: Meta: Replaced Brig Phys back walls with regular non-reinforced walls to allow break ins/outs and allow them to expand easier. 
add: Meta: Added camera to toxins to allow AI to see the inner door. 
fix: Meta: Moved a useless box and closet out of the way in Exploration maints.
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
The wall in sec that's next to the hardsuits should remain reinforced, brig phys rarely expands onto that area and it's where the suits are stored anyways imo

Unsure if janitors should have a welder and goggles.. While they know how to replace lights they shouldn't know how to repair an airlock or window, that's technically Engineers job (Even if mechanically and gameplay speaking it's literally just one left click) Same reason why Engineers most of the time don't replace light saying ''it's not their job'' (even if they're qualified for it) more or less its like a consensus to respect the turfs of the other jobs so we avoid ''one-man army man'' scenarios.

**Comment by MarkusLarsson421** [comment]
> Unsure if janitors should have a welder and goggles..

It's for fixing floors in maintenance.

**Comment by PestoVerde322** [comment]
immagine

Would remove the plating alltogheder here, since it's a shuttle passtrough in theory.

**Comment by MarkusLarsson421** [comment]
> Would remove the plating alltogheder here, since it's a shuttle passtrough in theory.
Fixed it.

Also swapped the location of the delivery thingy and the maintenance door.
image

**Comment by mystery3525** [comment]
> fix: Brig Phys back walls with regular non-reinforced walls to allow break ins/outs and allow them to expand easier.

Why? Why are we intentionally making a weaker portion in the security department for breakins? For expansions into maintenance? This is not a fix, it is a balance change. With "Easier Expansions", maybe you should contact engineering to destroy those reinforced walls, and not try to do it yourself with your welding tool and wrench?

image

**Comment by MarkusLarsson421** [comment]
What Engineers? Also, even if Engineers help with it. It is a pain. I could perhaps simply change it to make the Brig Phys room a tad bigger but that is less of a nitpick.

**Comment by itsmeow** [comment]
I have no problem with brig having a weak point. It doesn't need to be r-walls all around. It's not Armory. Breaking into brigphys doesn't even give any immediate advantage aside from outing you to sec. It could also give sec something to do, improving security by replacing the walls. Obviously not metagaming but if they start having issues, they could contract engineering to replace it.

**Review by itsmeow — APPROVED** [review]

**Pull request merged**
