### PR TITLE
Adding a player limit on the most over played maps

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request

The map vote maximum player count for each of the most played maps (Kilo, Meta and Box Station) has been set to 30. You can still get 30+ rounds but that will be from late-joins rather than round-start. Map vote occurs at the end of a round, usually prior to people leaving so the player count could drop significantly when the server restarts to change the map.

## Why It's Good For The Game

Box Station, Meta Station, Box Station, Meta Station, Box Station, Meta Station, Box Station, Meta Station.

Enough is enough, at least during the rare high-pop times let us play high-pop maps which aren't ancient by SS13 standards.

Show some love for the other maps and not just the same two or three maps rotating between them over and over again with the VERY occasional different map. You can still vote for your favourite map, you just can't bring an entire 40+ lobby to maps like Kilo, Meta and Box Station. No matter if you're the majority or by any luck the one guy to vote for a map.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: Markus Larsson
tweak: Maxplayers on map votes for Kilo, Meta and Box Station
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
This is a long time coming

**Comment by Fronsis** [comment]
> Why meta? Meta works perfectly on highpop

I agree, Meta works perfectly on highpop it has worked in the past before we had all the new maps and the go-to for highpop rounds were Meta and Delta, while i agree we should be playing other maps at +30 pop taking Meta away is a little ???

**Comment by Absolucy** [comment]
imo lower the max on kilo to like 20

**Comment by MarkusLarsson421** [comment]
Changed Box Station to have a maximum player count of 40 instead of 30 and removed the maximum player count for Meta Station after some discussion.

**Review by itsmeow — APPROVED** [review]
I like where this is at right now.

**Comment by Crossedfall** [comment]
You need to fix your CL.

I also don't think this really does much to solve the problem you're trying to solve.

**Comment by Nakalon** [comment]
Better solution: Nuke Kilo

**Comment by llol111** [comment]
Kilo should absolutely have a max on players to roll, its small and cramped. Thats its charm of course, but i wouldnt wanna play there with 50-60 people.

Strongly disagree on adding limits to maps because they are ""overplayed"" though. People vote for em cause they like em, simple as. 
Should people give new maps a chance? Sure, i guess.
Should they be *forced* off off their favorites? Fuck no.

**Comment by MarkusLarsson421** [comment]
Todays rotation: MetaStation, BoxStation, MetaStation, BoxStation, and finally Rad Station! Followed by Box Station again.

Something has to be done but it's nothing I can do, for now I think this PR is better left to prevent overpopulation on low-pop stations and lowering the bar for high-pop maps.

Can we just make Acacia a BoxStation / MetaStation 24/7 server? You'd instantly get 50+ pop constantly.

**Comment by Fronsis** [comment]
> Todays rotation: MetaStation, BoxStation, MetaStation, BoxStation, and finally Rad Station! Followed by Box Station again.
> 
> Something has to be done but it's nothing I can do, for now I think this PR is better left to prevent overpopulation on low-pop stations and lowering the bar for high-pop maps.
> 
> Can we just make Acacia a BoxStation / MetaStation 24/7 server? You'd instantly get 50+ pop constantly.

Well, this hasn't been merged or tested yet, in the end as lloll said, people vote what they want to play, only sometimes the voting gets a little trolling, even if your change goes in people will still vote Meta, your PR will bring up some other less-played maps for highpop though so that's fine, but you don't win anything by repeating your points and attacking the players for choosing Meta and Box by ''sending them to acacia''

**Comment by llol111** [comment]
> Something has to be done

Thats just like, your oppinion man

**Comment by PowerfulBacon** [comment]
In my opinion, as long as the maps aren't getting overplayed too much then its perfectly fine. If people want to play on some maps more than others, then they will vote for them and they will come up more frequently. Metastation is the most popular map for a reason, it may get boring but its a good map.

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
This feels like a hack job solution to a problem that already has a clear solution in the config.
Maps should have population ranges set to any population they are good to play on.

Letting players vote on maps is the problem here. I had a hand in a PR some many months ago that causes the next map to be chosen by drawing from a hat instead of majority wins. If that didn't solve the issue then the next step is to disabled voting for maps entirely and force a rotation or random suitable map each round.

I think the current system is fine personally: the most popular maps should be the most commonly played, with the others serving as a break now and then. *However*, if there is consensus that unpopular maps should be forced,  they should be forced with existing tools rather than ham-fisting the population ranges

**Comment by PowerfulBacon** [comment]
# Map stats for reference

image
image
image

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Remove the box changes and kilo changes (handled by another PR) and then this is fine.

**Pull request closed without merging**
