### PR TITLE
Adds a security evidence room to Corg

### PR DESCRIPTION
**Pull request by Tyranicranger4**
## About The Pull Request
Adds a security evidence room to corg.
Additionally tweaks the brig and some nearby pipes a tiny bit to make more sense when accounting for the new room.

*It's in the place of what was previously a random maint room. I did that since I didn't see anywhere else that would make sense. If you'd rather I make a completely new area for it I suppose that's possible too.*

## Why It's Good For The Game
Security needs a place to store evidence.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image
Buttons go clicky, firelock goes woosh, all is well in the world.

</details>

## Changelog
:cl:
add: Added an evidence storage room to CorgStation
tweak: Moved a couple of things in the brig and some piping around to accommodate the new room.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Is top right section of maints still accessible from cargo storage? If not, it can't go here.

**Comment by FriendlyContractor** [comment]
Walls need to be reinforced.

**Comment by PowerfulBacon** [comment]
(See my corg store branch for a better placement and security for corg)

**Comment by Tyranicranger4** [comment]
> Is top right section of maints still accessible from cargo storage? If not, it can't go here.

That entire section of maints remains completely accessible.
All that's changed was changed was a singular random maintenance room.
image

**Comment by PowerfulBacon** [comment]
There's no door from the hallway into maints, that's like the opposite of being accessible

**Comment by Tyranicranger4** [comment]
Fair enough. Where would you suggest it go instead?

**Comment by PowerfulBacon** [comment]
Up top somewhere?

**Pull request closed without merging**
