### PR TITLE
Gives the "boop" emote a sound

### PR DESCRIPTION
**Pull request by Rukofamicom**
## About The Pull Request

Adds a sound to boop, the only silicon specific emote that is silent

## Why It's Good For The Game
Boop is literally an emote representing a noise

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

### You have to enable sound due to the player defaulting to mute.

https://user-images.githubusercontent.com/9547572/219972327-90ef0b06-5adb-469f-aa05-ad70091fbd70.mp4

</details>

## Changelog
:cl:
add: The boop emote utilized by IPCs/silicons now has a noise
/:cl:

### CODE REVIEW

**Comment by DatBoiTim** [comment]
Is this available to IPCs?

**Comment by Rukofamicom** [comment]
Now with a totally new sound:

https://user-images.githubusercontent.com/9547572/219972337-19b92ca2-ccdd-4dba-ac3f-fcd62655ae8a.mp4

**Comment by DatBoiTim** [comment]
Amazing. Merge this immediately.

**Review by PestoVerde322 — APPROVED** [review]
Boops.

**Comment by Henri215** [comment]
What is the source on these sounds?

**Comment by Rukofamicom** [comment]
I editted the twobeep.ogg myself to make a boop out of it. 

https://github.com/BeeStation/BeeStation-Hornet/blob/master/sound/machines/twobeep.ogg

**Comment by Henri215** [comment]
> I editted the twobeep.ogg myself to make a boop out of it. It's just a slightly fuzzy square wave.
> 
> https://github.com/BeeStation/BeeStation-Hornet/blob/master/sound/machines/twobeep.ogg

Thank you and nice sound!

**Pull request merged**
