### PR TITLE
WORKING Directional Lighting in 2024

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports:
- https://github.com/tgstation/tgstation/pull/54520
- https://github.com/tgstation/tgstation/pull/54614
- https://github.com/tgstation/tgstation/pull/57058
- https://github.com/tgstation/tgstation/pull/60218
- https://github.com/tgstation/tgstation/pull/60336
- https://github.com/tgstation/tgstation/pull/60756
- https://github.com/tgstation/tgstation/pull/70250
- https://github.com/tgstation/tgstation/pull/70578
- https://github.com/tgstation/tgstation/pull/76009

## About The Pull Request

This ports the directional lighting system from Teegee. Its a recoup of #7418, and #8093 

Essentially, this adds a cone in front of the lightsource, rather than a radius of light. This is meant to emulate lights like headlights or flashlights.

Radius-based light sources & directional light sources are defined by its MOVABLE_LIGHT define

### TODO

- [x] fix ethereals mutcolors getting reset to white
- [x] fix weird light toggling bug

## Why It's Good For The Game

This is a direct upgrade of our lighting system.

As we tend towards projects like #10473, I think this is a good complement to what it is trying to achieve, which is why I am reviving this PR

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/1c971b3b-8d08-40a5-81bf-c41050fbb470

Working Gunlights

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/0c3e2382-2854-45ab-b92c-5f1ad9f78ebb

Working Ethereals

image

</details>

## Changelog
:cl: rkz, azarak, TemporalOroboros, Rohesie, Couls, ShizCalev, TastyFish
add: Adds directional lighting system in 2024!
add: adds directional lighting to cyborg lights, flashlights, and gunlights
refactor: refactors glow effects to be less terrible. Includes ethereal glow, and also the glowy/antiglowy mutation.
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
Correct me if I am wrong, but it looks like it is just off-setting the light source a few meters in front of where you are facing?

**Comment by Tsar-Salat** [comment]
oops lol

**Comment by PestoVerde322** [comment]
in the name of whats holy, unholy and in between, TM this, DO NOT YOLOMERGE

**Comment by Rukofamicom** [comment]
What's up with mineral scan pulse?

**Comment by Rukofamicom** [comment]
damn conflicts can't make up their mind and neither can I because of them

**Review by Rukofamicom — APPROVED** [review]

**Comment by Rukofamicom** [comment]
In the event this doesn't merge cleanly, ping for re-attempt please. 
This is very prone to conflicts so we should get it in as soon as we can.

I may be busy at the moment and unable to respond, but I can push the merge button even remotely if it's not currently conflicted

**Pull request merged**
