### PR TITLE
MC Test

### LINKED ISSUE #11247: [Needs investigation] Subsystem overrunning and pausing could potentially result in the MC stalling
If a subsystem overruns its tick allocation and consumes it all, if it then pauses then the subsystem will not be removed from the queue.
This means on the next tick, it has the opportunity to fire again which could then use all of the tick again, since it will be at the head of the queue.

I have not confirmed if this is causing any issues, however it is a logical issue from a quick lookover the code, and it is possible in the atmos subsystem, as if any of the hooks return 1, it calls pause(). If we work on the assumption that this pauses the subsystem in the case of it overrunning, then this will result in atmos being the highest priority thing to fire.

This gives a plausable, but unconfirmed explanation as to why high-chaos rounds have freezing issues.

Lines of importance:
air.dm:256 (and others, pauses subsystem if 1 is returned)
master.dm:734 (Doesn't remove the subsystem from the master's queue)
master.dm:655 (Gets the head of the queue)
master.dm:657 (If all the tick is consumed, break without condition)

### PR DESCRIPTION
**Pull request by PowerfulBacon**
Testmerge only, spams admins with a warning message if a certain freeze condition in the MC is met, resulting in time freezing.

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
I think you need to leave a message to logging system so that we can track when it started even if there's no one available to investigste live - since we have MC logging, right?

**Comment by PowerfulBacon** [comment]
Yea, I probably should have logged it so I can check it myself without needing someone to ping me lol. As for any details, if the messages are spammed while time is frozen then thats enough to know the exact cause (atmos).

**Comment by PowerfulBacon** [comment]
When time freezes, the MC isn't stalled. Only ticker systems are running, including background ticker systems

**Comment by EvilDragonfiend** [comment]
> When time freezes, the MC isn't stalled. Only ticker systems are running, including background ticker systems

There should be subsystems that weren't executed during subsystem. Afaik MC isn't really frozen, but the stat panel isn't refreshed so that it looks like MC is frozen, but I am pretty sure one of subsystems is jammed.

**Comment by PowerfulBacon** [comment]
You can manually refresh the stat panel by clicking on the MC tab, so that isn't changing my understanding of the situation

**Comment by PowerfulBacon** [comment]
Current notes:
- Tickers will only run if the explosions subsystems does anything. This means that something regularly adding turfs to the low/med/high explosions turf list may prevent anything other than tickers from running.
- When time freezes the MC isn't frozen, in fact it is still highly active and running systems. The problem is that its only running tickers.
- Tickers run before everything else, meaning that a ticker that fires regularly but doesn't tick check could consume all of the tick.

**Comment by PowerfulBacon** [comment]
This has served its purpose

**Pull request closed without merging**
