### PR TITLE
nerfs sepchems

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

you can no longer get sepchems from glowberries. 

## Why It's Good For The Game

see: breaching rocket wheats

## Changelog
:cl:
balance: can only get sepchems from strangeseeds now
/:cl:

### CODE REVIEW

**Comment by Rukofamicom** [comment]
Fuck no, don't make strange seeds **even easier to get and stronger at the same time**. Botany is busted as fuck as it is because of them.

**Comment by jupyterkat** [comment]
nope, It’s busted because you can just mutate some shit to rush nitroplants with sepchems, with strange seeds people has to roll for it. And grow more shit for biomatter if they don’t get it.

**Comment by Effemu** [comment]
strange seeds are literally the most annoying part of botany
rng isnt fun

**Comment by jupyterkat** [comment]
quit making breaching missile plants then nerd. Insta-crititing a person just by throwing a plant at them is annoying

**Comment by Effemu** [comment]
im not making breaching missile plants nerd
get good 😎

**Comment by USB3pt0** [comment]
As the person that authored strange seeds in the biogen to begin with, the 5000 point cost was to keep the production of them somewhat stemmed unless science brings better parts or you go get them yourself.  By default, the thing can only hold 40 plants worth and generate roughly 1.5 seed pack per plant bag.  With higher tier parts, it cuts in half repeatedly.  This would bring them down to t4 parts equivalent with only t2 parts.

Sepchems were put back into glowberries at the same time as /tg/ had just removed the trait entirely and bee was downstream of /tg/ without all the unfun nerfs.  I can't say in the past many rounds I've seen anyone even bother growing glowberries for sepchems, usually it shows up in strange when looking for medicines or fun chems to start with.

**Comment by jupyterkat** [comment]
oh boy they do that in as many rounds as they can once they've discovered it, I saw cultists and officers getting cucked by nitroplants every round that plant's in, even a fucking wizard.

**Comment by jupyterkat** [comment]
If breaching missiles are removed completely from lathes. I think those nitro plants should require more effort to make

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
This is a big buff to strange seeds, will need something like a run-through of the reagent list to remove the more exotic and powerful chemicals. I definitely do not agree with the making them 2500. (Since 5000 is already nothing to a decent botanist)

**Comment by USB3pt0** [comment]
I'd say leave strange seeds alone and if you really must, atomize the removal of sepchem from glowberries.  The random nature of strange seeds with the cost keeps them reasonable in a round, and if you're really bitching about breaching plant bombs, imagine the shit they'll be making with two times as many strange seeds and no empty ones, especially since you can get chemicals that would intensify the explosion in strange seeds.

**Comment by jupyterkat** [comment]
reagent generation stays the same, only traits gets added all the times now

**Comment by jupyterkat** [comment]
the shit they'll be making still requires them to roll it to get what they want instead of just knowing what plant mutation path to take

**Pull request closed without merging**
