### PR TITLE
Fixes stealthmode showing your ckey

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Your real name would be shown in that pop up. This should no longer be the case.

## Why It's Good For The Game

Fix
:cl:
admin: Reply pop-up in stealth mode will no longer reveal your orinigal ckey.
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
Don't speedmerge this, I'll try to figure out if I can replace "message from administrator" with fake ckey.

**Comment by PowerfulBacon** [comment]
Doesn't it say 'message from administrator' if you a stealthed?

**Comment by Archanial** [comment]
> Doesn't it say 'message from administrator' if you a stealthed?

It said message from [your original key] in the pop up window.

**Comment by Blueturbo47** [comment]
> > Doesn't it say 'message from administrator' if you a stealthed?
> 
> It said message from [your original key] in the pop up window.

Can confirm, I've seen this where ruko would msg me, and the window to reply would show their name.

**Comment by Archanial** [comment]
nah, scratch that, it's ready for merge

**Comment by Crossedfall** [comment]
Should have a CL

**Comment by Archanial** [comment]
Done

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
