### PR TITLE
Replaces station bounced radio sprite

### PR DESCRIPTION
**Pull request by imsynthex**
## About The Pull Request

Cream#3976 made this but doesn't know how git works so I PRed it instead.

very gaming

## Why It's Good For The Game

New sprite, good sprite

## Changelog
:cl: ReneAngel (Sprite), ImSynthex (Github)
imageadd: Replaced station bounced radio sprite 
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
not to insult the artist but it's not much of an improvement over an already alright sprite

**Comment by BrumalLake** [comment]
it's got that mining scanner theme

**Comment by KubeRoot** [comment]
I feel like this doesn't fit as regular station radio on bee. However, my first thought was a syndicate radio, and lordScrubling's comment also makes me think it could fit mining as well.

**Comment by imsynthex** [comment]
on smaller, grey items, an outline helps, but then again, im not the one that made it

**Comment by SergeiKoralev** [comment]
Looks like it should be a syndicate device. You COULD make a sub-type of the station bounced radios that has a syndicate skin.

**Review by PowerfulBacon — APPROVED** [review]
I like it, looks more like something from mining / off-station which is generally more what the radio is geared towards considering the station already has their complex comms setup. Also the original sprite looks pretty bad.

**Comment by PowerfulBacon** [comment]
Also add the spriters name to the changelog 
:cl: (Override changelog name)
add: stuff
/:cl:

**Comment by francinum** [comment]
I think this would work well as perhaps a variant of the radio hardlocked to mining's frequency and stocked in the outpost instead of replacing every SBR.

**Pull request merged**
