### PR TITLE
Adds the valentines card to loadout for 700 coins.

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

Adds the valentine card to the beecoin shop for 700 coins.

Requested by Odessa on the discord: 
image

## Why It's Good For The Game

It offers good roleplaying opportunities. I don't think it would hurt anything, it's basically a glorified paper that pre-writes a cheesy valentines message.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
add: You can now use your BeeCoin to buy a valentines card, if you wanna do something sweet.
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
This PR will cause serious weirdness with how the cards work (They aren't just messages, they have behaviours behind them too) which will break a lot of things.
~~It appears that this account is also an alt account for another account which is community banned from beestation, so unfortunately I'm going to have to close this PR.~~ This ban was appealed and removed.
This PR will cause huge issues with the valentine card behaviours, so I'll keep it closed. Feel free to re-open it with using a new item that can't be sent to people in order to make them an antagonist role.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
The card in the shop should have no behaviours on it at all, it shouldn't be sendable or anything. It should just be the message.

I'm not 100% for adding the cards as regular event cards due to some of the things having a potentially rulebreaking nature if used seriously (Some of the meme messages you can get could be considered sexual in nature if people are going to start using these as a serious item).

**Comment by Absolucy** [comment]
Alright, I completely disabled the `write_valentine` proc for the subtype.

**Comment by itsmeow** [comment]
I cannot see this going well at all

**Comment by Absolucy** [comment]
Trust me, absolutely nothing can go wrong!

**Comment by itsmeow** [comment]
:key: noh

valentine card is for valentine's only and this will not go well

**Comment by PowerfulBacon** [comment]
unfortunately I have to agree

**Pull request closed without merging**
