### PR TITLE
Makes felinids somewhat less reskinned humans, gives them a hearing based ability and adds some minor dammods

### PR DESCRIPTION
**Pull request by PowerfulBacon**
Unrelated but why do guns not do hearing damage 😔 

## About The Pull Request

Updates felinids, adds some shitty lore to base the variations from humans around and changes some parts of them.

Shitty lore:
```
 * Felinids are essentially normal humans, but with some major genetic changes. They originate from a time long gone,
 * before the Animal rights consortium. Because I can't be too bothered to write up a super long and complex story
 * ill give you the basics as to where I would say they come from (take it as you will, its lore and this part literally)
 * does not matter, nor affect them mostly; but essentially genetic modification is becoming a more and more accessible thing,
 * experiments are done into modding humans into other species and as one of the first species experiments felinids were created
 * being a hybrid between humans and felines obviously. Due to their modifications ([data expunged]) felinids reproduced at
 * a heavilly increased rate compared to humans, leading to complications with station supply. (The actual numbers of
 * inhabitants was higher than predicted). As a result a large portion of the felinid population was exiled or sent
 * to transfer centers, with only a very small number being allowed to perform menial jobs. At this time almost all felinids
 * on station were of a single gender, and combined with their shorter lifespans when compared to humans caused their
 * numbers to be declining rapidly. As a result of this, and to comply with the requests of a new syndicate faction rising
 * (the animal rights consortium), the reduction of the felinid population was ceased with hopes from Nanotrasen that
 * their numbers would continue to decline. Since the future is here now, medicine is a lot better and cloning is a
 * possibility, the need for new crew and the worry that crew will be lost is only minor, so the population on most stations
 * is pretty stable, felinids can live on and with no further problems with in a long timespan, felinids can finally at
 * last be accepted into most jobs. Oh yea pretty important thing I forgot to add somewhere but makes them make sense a
 * bit more is that when exiled they were sent to some planet considered pretty dangerous, its dark and shit so they
 * have minor genetic changes due to this (natural selection and all).
 *
 * That planet I talked about properties:
 * - Cold and pretty barren, animals and plants do live on the planet, however much of the plants are toxic
 * or dangerous in some way, and only the animals that have lived and adapted there for centuries can consume them. As
 * a result the felinids living there have poor ability to consume plant-based matter, and prefer meats. Additionally felinids
 * are more suited to the cold environment of this planet, and heavily dislike the heat. Obviously they had coats and stuff too,
 * so can live in environments that can support humans; they werent there for /that/ long.
 * - Since the planet was relatively dark, their eyes have adapted to be better in the dark.
 * - Due to their sensitive ears, they have a weakness to flashbangs.
```

### Changes Made:
 - Removes the meow saymod. I'd like to replace this with something that is actually like 'say' but calm sounding but I don't really know what words to use.
 - Felinids now only take 70% cold damage due to their 'home' planet being a cold place, and also they have fur (Obviously they don't have fur on their body so the home planet works better lore-wise).
 - Felinids take 15% more heat damage. (Not burn damage, heat)
 - Felinids take 20% more stamina damage.
 - Felinids take 10% less toxin damage.
 - Adds a new trait 'cat hater', which grants a negative moodlet when a cat nearby wags their tail.
 - When cats wag their tails, nearby humans will get a moodlet. Additionally, when hugging someone a bonus +1 moodlet is given to the person hugged.
 - Removes the ability to qualify for command roels, in case the config option is disabled (They are kind of non humans).

Ear Changes:
 - Felinid ears can now enter a 'listening' mode.
While active, the ear protection factor is set to -5, meaning the ears take huge damage from loud noises and cannot be protected from sounds. Additionally, movement speed will be greatly reduced.
However, while active whenever the felinid hears a noise nearby a red blip will be shown to them.

Ears in action:

https://user-images.githubusercontent.com/26465327/111870453-be80e380-897c-11eb-9ae5-dfc85b662c0a.mp4

## Why It's Good For The Game

Felinids are relatively unremarkable, this gives them a pretty cool ability and some pretty uncool disadvantages.
Changes generally don't suit combat too much and improve their ability to detect and avoid threats, however aren't big enough to make them completely sucky.

## Changelog
:cl:
del: Felinid meow saymod
add: Felinids take 30% less cold damage.
add: Felinids take 15% more heat damage.
add: Felinids take 20% more stamina damage.
add: Felinids take 10% less toxin damage
add: Chocolate acts as an actual poison to felinids now rather than something that can make them throw up and purge reagents.
add: Felinids hugging or wagging tail will cheer up nearby people.
/:cl:

### CODE REVIEW

**Comment by Naevii** [comment]
Making race "unique" by making it take less x damage and making it more y damage is absolutely cringe. 

I dislike those changes. 
There were many ideas stated before in how to improve the race. I don't think its the right direction. As much as i like the extra ability, the rest is just out of place. 

Also felinid hater just straigh forward encourages grief on felinids and killing them for no reason "what do you mean i  cant kill all felinids as non antag, i have the trait!"

**Comment by PowerfulBacon** [comment]
Fine ill remove the cat hater, but the other stuff needs to stay to somewhat balance it out / change them in a minor way (The bit that makes them unique is the ear ability).
If they are literally just going to be humans + tail, then they might as well be removed and we can just have the tail and ears slot of humans unlocked so that people can be humans with tails and ears.

**Comment by PowerfulBacon** [comment]
Also has a side effect of making the game more accessible to people who have trouble hearing (although they may have to walk slow like all the time to hear)

**Comment by Naevii** [comment]
> Fine ill remove the cat hater, but the other stuff needs to stay to somewhat balance it out / change them in a minor way (The bit that makes them unique is the ear ability).
> If they are literally just going to be humans + tail, then they might as well be removed and we can just have the tail and ears slot of humans unlocked so that people can be humans with tails and ears.

The ability is a great idea. 

Do they still get fucked by flashbangs or it was totally moved to ability ?

**Comment by PowerfulBacon** [comment]
They still get fucked by flashbangs if not wearing earmuffs and helmet (I think), the ability while active makes them unable to block it no matter how much hearing protection they have on. (well unless they can get like 6 hearing protection but I don't think that's possible)

**Comment by Effemu** [comment]
wtf no
just remove them its a fetish race anyways

>Felinid ears can now enter a 'listening' mode.
While active, the ear protection factor is set to -5, meaning the ears take huge damage from loud noises and cannot be protected from sounds. Additionally, movement speed will be greatly reduced.
However, while active whenever the felinid hears a noise nearby a red blip will be shown to them.

what the fuck you're literally giving them wallhack

**Comment by PowerfulBacon** [comment]
> what the fuck you're literally giving them wallhack

In practise the ability is pretty shit, it only works for sounds you can hear anyway, lasts for a fraction of a second and doesn't work for sounds that don't play through walls anyway. Additionally while active your ears will get obliterated by flashbangs or loud noises.

**Comment by ghost** [comment]
Make all corgis auto-aggro to felinids. Make all mice squeak repeatedly near felinids.

**Comment by Effemu** [comment]
make tail wagging buff melee damage of all humans standing within 10 tiles by 50% so we can beat them up faster

**Comment by PowerfulBacon** [comment]
support class

**Comment by ghost** [comment]
> make tail wagging buff melee damage of all humans standing within 10 tiles by 50%

A little excessive. I'd instead suggest making tailwagging has a 50% chance to throw around nearby objects.

**Comment by eeSPee** [comment]
I like the hearing, but I see no reason why it should not be a mutation, like apid's wax generation.

Also why do you turn off Geforce Experience Recording with the mouse like a caveman?

**Comment by PowerfulBacon** [comment]
> 
> 
> I like the hearing, but I see no reason why it should not be a mutation, like apid's wax generation.
> 
> Also why do you turn off Geforce Experience Recording with the mouse like a caveman?

Its based on the ears, to be honest apids wax generation should be based on an organ like a wax sack or something rather than a mutation.
As for geforce experience, I don't know the hotkey

**Comment by Kapu1178** [comment]
> 
> 
> > I like the hearing, but I see no reason why it should not be a mutation, like apid's wax generation.
> > Also why do you turn off Geforce Experience Recording with the mouse like a caveman?
> 
> Its based on the ears, to be honest apids wax generation should be based on an organ like a wax sack or something rather than a mutation.
> As for geforce experience, I don't know the hotkey

bind it in your overlay, you CAVE MAN

**Comment by Kapu1178** [comment]
id really suggest making the healing mode its own PR, I think its a really awesome idea.

**Comment by francinum** [comment]
Agree as above, it should be genericized and made available for various use.

also:
> If they are literally just going to be humans + tail, then they might as well be removed and we can just have the tail and ears slot of humans unlocked so that people can be humans with tails and ears.

This is exactly what you should be doing.

**Pull request closed without merging**
