### PR TITLE
Hulk and bath salts now make you immune to stunbatons again

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request

adds the nostamcrit and confuseimmune traits. Hulk and bath salts now both completely ignore stamina damage. Hulks now no longer move around randomly when confused (but are still susceptible to wallstuns)

## Why It's Good For The Game

hulk and bath salts work as intended again

## Changelog
:cl:
add: confuseimmune and nostamcrit traits
tweak: hulk and bath salts bypass stamina damage
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Is this a TG port?

**Comment by zeskorion** [comment]
> Is this a TG port?

nope, coded myself

**Comment by Bastian0930** [comment]
I really don't like the fact you can no longer flash hulks because of this. It buffs them a bit too much.

**Comment by zeskorion** [comment]
> I really don't like the fact you can no longer flash hulks because of this. It buffs them a bit too much.

No, it just brings them back to how they used to be. They arent any more resistant than normal crew- just beat them to crit if you really gotta fuck their face

**Pull request merged**
