### PR TITLE
Increases firelocks and blastdoors animation speed

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

right now the doors are sluggish. while they're supposed to be fast
preview:
Firelocks
blastdoors

## Why It's Good For The Game

looks better and firelocks are supposed to be fast after #2709 anyways

## Changelog
:cl:
tweak: increased firelocks and blastdoors animation speed
/:cl:

### CODE REVIEW

**Comment by ZombiesVsPlants** [comment]
ngl looks beautiful

**Comment by PowerfulBacon** [comment]
.This is going to make firedoors way too powerful. 2709 is an outdated PR and a relic of monstermos

**Comment by PowerfulBacon** [comment]
Also blast doors are absolutely massive, they cannot close quickly

**Comment by jupyterkat** [comment]
Firedoors have always been that fast and nothing is wrong with that. plus fastmos is gonna be back anyways. get that vote going nerd

**Comment by jupyterkat** [comment]
blastdoors close at the same fucking speed as any other airlocks

**Comment by PowerfulBacon** [comment]
> 
> 
> Firedoors have always been that fast and nothing is wrong with that. plus fastmos is gonna be back anyways. get that vote going nerd

No the small firedoors have been, these large ones are slower and crush people and have always been that way.

**Comment by jupyterkat** [comment]
you cannot dodge them with their old speeds anyways

**Comment by PowerfulBacon** [comment]
Yea you can, they take ages to close

**Comment by ZombiesVsPlants** [comment]
Shame I loved this

**Pull request closed without merging**
