### PR TITLE
Corgstation Security Rework

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Reworks CorgStation security.
- Makes armoury accessible from space.
- Makes security less of a single giant hallway and adds some more turns into it.
- Moves the brig medbay area closer to the cells.
- Moves the detective's office deeper into security
- Moves the labour shuttle to a publicly exitable area

TODO:
- [ ] Add gravity generator back in
- [ ] Deconflict the map with new features (This branch was made months ago)

## Why It's Good For The Game

Fixes some of the major critisisms about corgstation armoury being impossible to attack, reworks security to be a more interesting design.

## Testing Photographs and Procedure

Before gravity generator changes:

image
image
image

## Changelog
:cl:
tweak: Reworks CorgStation's security wing, making armoury more accessible from space.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Seed vendor replaced with biogenerator, they can get seeds by asking at botany instead

**Comment by PowerfulBacon** [comment]
image

**Comment by PowerfulBacon** [comment]
image
TODO

**Comment by PowerfulBacon** [comment]
I have no idea where to put grav without reworking all of engineering, which would be fine if it wasnt for the damn pipes

**Comment by PowerfulBacon** [comment]
image
Shuttle goes through the wall

**Comment by WrillWasTaken** [comment]
Grass under trays might look nice, but functionally it's a giant pain, since you'll remove the grass flooring if you even slightly misclick with a spade. Wood floors and standard trays might look decent.

**Comment by CydiaLamiales** [comment]
> Seed vendor replaced with biogenerator, they can get seeds by asking at botany instead

Public gardens have some basic seeds on other maps, sometimes even fruits and veggies.

**Comment by CydiaLamiales** [comment]
Aww, why?

**Pull request closed without merging**
