### PR TITLE
[PORT] Removes lag

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Removes anything that might cause lag.

ORIGINAL PR: https://github.com/tgstation/tgstation/pull/53970

## Why It's Good For The Game

Removing lag is good.

## Changelog
:cl: ZeroDayDaemon
del: Removed any possible source of lag.
/:cl:

### CODE REVIEW

**Comment by Moccha-Bee** [comment]
when i actually thought you were making a good pr you come out with a shitty meme removing the entire game :walter: you are a redditor through and through

**Comment by r1ks-iwnl** [comment]
resolve conflicts smh

**Comment by ghost** [comment]
> resolve conflicts smh

On it.

**Comment by PowerfulBacon** [comment]
put the tg pr this is ported from or it won't get merged

**Comment by ghost** [comment]
> put the tg pr this is ported from or it won't get merged

Done.

**Comment by Moccha-Bee** [comment]
on tg they repo banned the guy for a month can we do the same 😳

**Comment by ghost** [comment]
> on tg they repo banned the guy for a month can we do the same 😳

They blocked me!!! Again!!!

**Comment by Archanial** [comment]
git ban he

**Comment by Archanial** [comment]
Please fix your changelog and credit the original creator thanks

**Comment by ghost** [comment]
> Please fix your changelog and credit the original creator thanks

Done.

**Comment by St0rmC4st3r** [comment]
this is getting old

**Comment by Moccha-Bee** [comment]
> this is getting old

old but gold

**Pull request closed without merging**
