### PR TITLE
Added a retrowave titlescreen.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

adds pretty cool retrowave titlescreen _yes_

image

## Why It's Good For The Game

synth station 13 

## Changelog
:cl: pinkblossom6
imageadd: adds a new titlescreen
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
8/10 needs more bees

**Comment by ghost** [comment]
bees are hidden behind the grid

stealth synthwave bees

**Comment by TheNeoGamer42** [comment]
11/10 pink did an arts, also we should totally have moar title screenses

**Review by Crossedfall — APPROVED** [review]

**Comment by Crossedfall** [comment]
Not Papa John's:tm: branded, but I think this could work.

**Pull request merged**
