### PR TITLE
Sawn off improv has recoil like everything else

### PR DESCRIPTION
**Pull request by ghost**
TG coder nerfed every sawn off but the improvised one hue

## About The Pull Request

gives the improvised shotgun the sawn off shotgun recoil.

## Why It's Good For The Game

Every other sawn off shotgun has the recoil nerf, but the sawn off is considered its own item type unlike the others where its the same item path but with swapped variables. This give the sawn off improv the debuff on recoil.

## Changelog
:cl:
fix: Sawn off improv has recoil like the other shotties.
/:cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
Recoil is already applied in this proc

https://github.com/BeeStation/BeeStation-Hornet/blob/4824b8b3d6381e3b113f73a644566f8677177a5e/code/modules/projectiles/guns/ballistic.dm#L389-L414

This is applied whenever you saw off the end of a shotgun. You can confirm this by checking the variables of the improvised shotgun before you cut the end off (Recoil and 'sawn_off' should be `0`) and then checking again after you saw the end off (Recoil and 'sawn_off' should now be `1`)

**Comment by ghost** [comment]
yeah youd think that but when i tested it in game there was no recoil for it until i made this fix. i think because unlike the other sawn offs which just have different variables, the improv sawn off is its own item and inherits its stuff from the normal shotgun

**Comment by Crossedfall** [comment]
Ah, I see the problem. You're right. The problem is that you can admin spawn in unmodified sawn off improvised shotguns. If you do it correctly in-game you get the intended effect. Not entirely sure why they opted to make them separate objects. 

I'm wondering if a better fix would be to bring the improvised shotgun in-line with how the other shotguns work. Is there any actual reason to have a separate object specifically for the sawn off?

**Comment by ghost** [comment]
theres a single space/lavaland ruin that uses the seperate shottie. and tbh i think the improv shottie should actually br worse then it is now, make its accuracy a little less with more recoil because where it is now its basically a sidegrade to the double barrel because you reload it faster at the cost of one extra shell, should atleast be abit less accurate

**Pull request merged**
