### PR TITLE
Revert "Updates our layers to get ready for plane cube, and weather effects"

### PR DESCRIPTION
**Pull request by PowerfulBacon**
Reverts BeeStation/BeeStation-Hornet#8082

This PR was broken and caused many issues.
Author requested revert so they have more time to fix issues.

:cl:
del: Reverts layer and weather effects update.
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
It did not cause that many issues? I tested and fixed it fairly extensively before merging. There's a few things here and there but I don't think a revert is needed.

**Comment by itsmeow** [comment]
From what I understand it's just a few incorrectly set layers and planes here and there, nothing major

**Comment by dwasint** [comment]
> It did not cause that many issues? I tested and fixed it fairly extensively before merging. There's a few things here and there but I don't think a revert is needed.

it should be test merged at the least for now, i have other prs to work on downstream so i'm unable to get fixes out quickly.

**Comment by PowerfulBacon** [comment]
I have had a big wall of reports coming in

**Pull request closed without merging**
