### PR TITLE
Enables medkits to be equipped to belt slot

### PR DESCRIPTION
**Pull request by lowwy**
## About The Pull Request

Enables medkits to be equipped to the belt slot

## Why It's Good For The Game

With the changes in self-care people don't really take meds with them anymore, as they cannot self-heal more then once.
Plus I have been seeing some discarded med-kits on the floors after the content has been transferred to a cardboard box.

Edit: Also gives medical players more options in clothing to wear, as the first aid kit can only be slotted on the back of medical labcoats.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
tweak: Medkits can now be attacked to the belt
/:cl:

### CODE REVIEW

**Comment by Rukofamicom** [comment]
🔑 

> With the changes in self-care people don't really take meds with them anymore, as they cannot self-heal more then once.

If anything this is justification for keeping the system as-is. There is no longer any reason for players to pocket the entire medkit anymore, unless they're in a caregiving role that is expected to treat other players (Paramedic, Doctor, CMO, Brig Physician) which are still able to pocket a medkit with their roundstart equipment.

Bringing this back will only enable behavior that gets players warned and noted by admins (the original motivation for the PR which changed the size of them)

**Comment by Rustyfoxb** [comment]
> Bringing this back will only enable behavior that gets players warned and noted by admins (the original motivation for the PR which changed the size of them). 

That is kinda defeated by the fact that you can store medicine inside of cardboard boxes, making the weight change more of a annoyance if someone wishes to try and hoard medicine.
Not to mention the change also really makes exploration medic job sorta harder to keep the team in good state in a emergency ( i say sorta as the only real danger this affects is spider venom and clockwork ruins).
Oh and if a medical doc decides to use surgical apron, they can't keep a medkit in thier pocket.

**Comment by Rukofamicom** [comment]
> That is kinda defeated by the fact that you can store medicine inside of cardboard boxes, making the weight change more of a annoyance if someone wishes to try and hoard medicine.

This was brought up in the original PR as well. 

Players who want to powergame will always be able to go out of their way to do so - making the game powergame proof is not a feasible endeavor. It is much more **intuitive** that players shouldn't take an entire medkit when it isn't so easy to pocket. 

> Not to mention the change also really makes exploration medic job sorta harder to keep the team in good state in a emergency ( i say sorta as the only real danger this affects is spider venom and clockwork ruins).

"Exploration medic" is not really a job - all explorers have the same job regardless of the equipment they started with at this time. The explorer job is very poorly executed and misleading in its current state. I understand exploration crews take damage and need to heal, but thinking this should be easily done right at the sight of the wound being received for every wound is an unhealthy speedrunner mentality. 

> Oh and if a medical doc decides to use surgical apron, they can't keep a medkit in thier pocket.

Not only is this their choice to make, but a doctor is never very far from med storage. Nothing stops them from simply carrying the medkit to patient and setting it down if they need both hands.

**Comment by CydiaLamiales** [comment]
This just results I regular MDs putting medicine into cardboard boxes too.

**Comment by Fronsis** [comment]
I haven't personally seen it myself that much spammed by MD's or regular folks (the cardboard strat) but it's like Ruko said, players are always going to find a way around it, there's a reason why some very gamer players toe the line with min-maxing space doing stuff like medicine in box or tools in box(to bypass the need of toolbelt)

I've noticed there's less people carrying 20 medkits nowadays and doctors tend to pick wisely what to take on their bag/kits rather than have all of everything on their bags

It's true that with the introduction of metabolites and such it's not that ''viable'' to use them anymore so that helped on diminishing people hoarding them

As a small note the idea of the explo-doc to have a paramedic thing doesn't sound that bad, i guess the explo-docs are the ones that end up doing that strat the most besides the powergamer folks

**Comment by Absolucy** [comment]
I want to be able to wear more unique outfits as MD 😔

**Comment by lowwy** [comment]
> > That is kinda defeated by the fact that you can store medicine inside of cardboard boxes, making the weight change more of a annoyance if someone wishes to try and hoard medicine.
> 
> This was brought up in the original PR as well.
> 
> Players who want to powergame will always be able to go out of their way to do so - making the game powergame proof is not a feasible endeavor.

I mean, is it really powergaming for a character to think,, Hey... this carboardbox fits the same amount of medicine AND fits in my bag perfectly!

additionally bulky medkits also limits the clothing a doc can wear while still carrying medicine, you either must "powergame" so you can wear outfits you like or be stuck with the default labcoat and not "powergame".

**Comment by Rustyfoxb** [comment]
> I mean, is it really powergaming for a character to think,, Hey... this carboardbox fits the same amount of medicine AND fits in my bag perfectly!
You can also add name to boxes with a name tagger, so you would be able to know if it's the medkit or emergency box.

**Comment by EvilDragonfiend** [comment]
I am fine with this.

**Comment by Rukofamicom** [comment]
> I mean, is it really powergaming for a character to think,, Hey... this carboardbox fits the same amount of medicine AND fits in my bag perfectly!

What was decidedly powergaming was non-med players swiping a medkit at roundstart for no reason other than to have med supplies on hand *just in case*. 

If players are still doing this anyway, that's not my problem unless you want to make a case that I should remove or nerf cardboard boxes 🤔

**Comment by DarnTheMarn** [comment]
I mentioned this on the original PR, but why not made the default ointment/bruise packs not stackable? It'd reduce the frankly insane amount of medicine you can carry on yourself. The brute/burn patches in the specialist kits aren't stackable so it'd be more consistent that way too.

**Comment by EvilDragonfiend** [comment]
I think all first aid kits are fine to be medium except for the doctor's bag because it's a bigger one.

**Comment by lowwy** [comment]
> I think all first aid kits are fine to be medium except for the doctor's bag because it's a bigger one.

Fair point, I added it.

**Review by EvilDragonfiend — APPROVED** [review]
I am more interested in nerfing medicines instead of restricting people have a lot of medicines, so I am okay with this.

**Review by Rukofamicom — CHANGES_REQUESTED** [review]
Make medkits a belt slot item instead of changing their size.

This solves the problem of doctors wanting alternative fashion choices as well as explorers needing to wear spacefaring suits, without returning to enabling multiple medkits in a single player's possession.

**Comment by lowwy** [comment]
> Make medkits a belt slot item instead of changing their size.

This would interfere with the medical toolbelt and Compact Defibrillator.
And the medical toolbelt is meant for that.



@Rukofamicom :
> Why should a reskinned cardboard box be bulky just because it starts with medicine inside?

**Comment by EvilDragonfiend** [comment]
> Why should a reskinned cardboard box be bulky just because it starts with medicine inside?

yeah, ngl, we can just bypass. It's really not that different from a cardboard box that you can't take into your bag.

**Comment by Rustyfoxb** [comment]
> This solves the problem of doctors wanting alternative fashion choices as well as explorers needing to wear spacefaring suits

This would make it the same as how things currently are, since doctor would swap thier medbelt for a medkit, and explorers almost always wear toolbelts.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
I like the idea of allowing people to carry medkits more easilly, however I still don't want scenarios where doctors have 1 of every single medkit type in their bag (This is how I used to play doctor).
I would be very happy with this being a belt item though, as it means it is easier for people to carry around and takes up an important belt slot instead which means you have to actually think about what you want to carry with you (rather than just stuff everything into the bag). Also the suit slot isn't usable by everyone, and is especially annoying if you want to go EVA and need an oxygen tank there.

The general use of slots should be:
Backpack: Minor items with relatively low impact inside a bcakpack, or important enough items to replace the entire bag (shotguns)
Belt: Items which are important but not important enough to need to replace the backpack entirely
Suit storage: Things relevant to the suit you are wearing and shouldn't need at all times

**Comment by EvilDragonfiend** [comment]
One thing: doctor's roundstart bag shouldn't go to the belt slot, then first aid kits to the belt slot are fine.

**Comment by CydiaLamiales** [comment]
The problem is that functionally, medkits are are reskinned cardboard boxes but even worse.

**Comment by Rukofamicom** [comment]
> One thing: doctor's roundstart bag shouldn't go to the belt slot, then first aid kits to the belt slot are fine.

I disagree. 

The extra capacity doctor kit / doctor bag should qualify for belt slot just the same as it does for suit slot currently. The handful of players with access to this item should be able to make use of its extra capacity to aid in their job.

**Comment by Rukofamicom** [comment]
That was a misclick! So sorry!

**Review by Rukofamicom — APPROVED** [review]

**Review by PowerfulBacon — APPROVED** [review]
Do these have a belt icon?

**Comment by EvilDragonfiend** [comment]
> Do these have a belt icon?

No. Only boxes. Boxes being on a belt slot (especially doctor's kit) would look weird

**Comment by Rukofamicom** [comment]
Updated body to be accurate, just realized it never got touched here.

**Pull request merged**
