### PR TITLE
Fixes map verb

### PR DESCRIPTION
**Pull request by Raven-Industries**
## About The Pull Request
Fixes the map verb to direct to the proper place. Tested with Metastation locally, other maps should also work though. 

## Why It's Good For The Game

Fix good

## Changelog
:cl:
fix: fixes map verb
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
If it's no hassle, could you instead port the functionality of NSV's version of this verb?

I'll go through and do the nasty skin editing later.
https://github.com/BeeStation/NSV13/blob/da9faec150a40dda84b22eddee9bb563f31d0c02/interface/interface.dm

**Comment by Raven-Industries** [comment]
> If it's no hassle, could you instead port the functionality of NSV's version of this verb?
> 
> I'll go through and do the nasty skin editing later. https://github.com/BeeStation/NSV13/blob/da9faec150a40dda84b22eddee9bb563f31d0c02/interface/interface.dm

Will do so later tonight, that looks much cleaner.

**Comment by Raven-Industries** [comment]
Switched over to the NSV way of doing things, but I had to add a bit to handle the fact that some of our map names include spaces; I hope it's not too terrible a way to do it.

**Comment by francinum** [comment]
~~you should just be defining a new json entry and config value like NSV/I did so that we can account for any weirdness that affected does instead of praying this never breaks~~

There's a reason NSV uses `mapconfig.map_link`, a var we do not have

**Comment by Raven-Industries** [comment]
... 
I am stupid and possibly blind.

**Pull request closed without merging**
