### PR TITLE
Adds the AI lab ruin room.

### PR DESCRIPTION
**Pull request by AnCopper**
## About The Pull Request

image

## Why It's Good For The Game

More rooms.

## Changelog
:cl:
add: Added the AI lab room as a possible ruin room.
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
No idea what's causing linters to fail.

**Comment by ike709** [comment]
As the linter says, you didn't run the map merger tool.

**Comment by AnCopper** [comment]
> As the linter says, you didn't run the map merger tool.

I thought StrongDMM did that automatically.

**Comment by PowerfulBacon** [comment]
You're door marker is in an Incorrect position and should be moved 2 tiles to thel left or right. The room width must also be 3n+1 so will fail linters if not 5, 9, 13, 17 etc. In width and height
(You can always expand the width by 2 and add noop turfs)

**Comment by AnCopper** [comment]
image
Still failing hnggg

**Comment by PowerfulBacon** [comment]
Needs to be converted to TGM format. Use fastdmm or run the map merger. Theres probably a button in strong DMM to export in TGM format, but I don't use strong DMM so I don't know.

**Comment by AnCopper** [comment]
So I fixed linters, but something else broke now.

image

The exit path is at a 3 coordinate though..

**Comment by AnCopper** [comment]
Oops, the map wasn't in .dmm format.

**Comment by AnCopper** [comment]
Found the issue, my StrongDMM settings were not set to save in tgm format.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
If this is a loot room it needs important loot drop spawns so the research disks can spawn

**Review by PowerfulBacon — APPROVED** [review]
Seems to be all good here.

**Pull request merged**
