### PR TITLE
Finished BSA is indestructible.

### PR DESCRIPTION
**Pull request by AnCopper**
## About The Pull Request

Finished BSA is indestructible.

## Why It's Good For The Game

Just saw a Xeno melt it in under 5 seconds after someone spent an hour setting it up.

## Changelog
:cl:
tweak: the BSA is indestructible.
/:cl:

### CODE REVIEW

**Review by ike709 — DISMISSED** [review]

**Comment by ZombiesVsPlants** [comment]
I somehow feel that allowing people to build indestructible objects will end badly.

**Comment by Absolutely-Steph** [comment]
Indestructible bad, make it tougher, but outright indestructible is a fucking terrible idea

**Comment by ItsTisme** [comment]
you can just, make it acid proof.  IRC thats a flag you can just flip on. Giving it more health to survive is fine but I feel like some funny's will happen if its indestructable

**Comment by AnCopper** [comment]
You can't even attack it anyways.

**Comment by ZombiesVsPlants** [comment]
I can think of numerous "funnies"
Like building them around a doomsdaying malf ai

**Comment by OceanFish1** [comment]
Watch me building multiple BSA infront of evac doors to block path to shuttle as soon as it gets merged

**Review by qwertyquerty — CHANGES_REQUESTED** [review]
I agree with all the flags except indestructible

**Review by qwertyquerty — APPROVED** [review]

**Pull request merged**
