### PR TITLE
fixes blob spore pathing and adds the ability to ignore mobs for JPS pathing

### LINKED ISSUE #5933: Blob lost it's ability to rally spores.
Rally spore power of the blob doesn't work anymore.

### PR DESCRIPTION
**Pull request by MNarath1**
## About The Pull Request

This fixes blob spores beeing unable to path trough blob structures and adds the ability to ignore mobs for JPS (Jump Point Search) pathing.
closes https://github.com/BeeStation/BeeStation-Hornet/issues/5933
## Why It's Good For The Game
Bugfix  good

## Changelog
:cl:
add: ability to ignore mobs for JPS (Jump Point Search) pathing
tweak: blob spores will ignore mobs during pathfinding
fix: fixes blob spores beeing unable to path trough blob structures
refactor: Refactors Goto for blob spores to use JPS pathing instead of the byond native pathfinding
/:cl:

### CODE REVIEW

**Comment by MNarath1** [comment]
for anyone wondering why this also modifies hierophant.dm thats needed so the linter won't complain about the fact that the child proc of goto can sleep as said proc that calls goto in hierophant.dm has signal hander so should_not_sleep is TRUE here and that causes the linter warning to avoid that and save myself some sanity i simply also called goto in hierophant.dm with invoke_async.

**Comment by Kapu1178** [comment]
why not replace the sleep with a callback or timer

**Comment by MNarath1** [comment]
> why not replace the sleep with a callback or timer

hmmm maybe timers don't get cached by the linter its worth a try

**Comment by Kapu1178** [comment]
> > why not replace the sleep with a callback or timer
> 
> hmmm maybe timers don't get cached by the linter its worth a try

you shouldnt be trying to escape the linter you should be trying to fix the problem

**Comment by MNarath1** [comment]
> > > why not replace the sleep with a callback or timer
> > 
> > 
> > hmmm maybe timers don't get cached by the linter its worth a try
> 
> you shouldnt be trying to escape the linter you should be trying to fix the problem

there is no problem even if said proc would sleep it doesn't really matter cause in case of hierophant.dm those get called for simplemobs that then attack the one that basically attacked them with the staff so even if it sleeps there isn't really anything that would actually break here cause there is no feedback it needs i could also just remove the Signal_Handler but there i really am unsure what would happen.

**Comment by MNarath1** [comment]
honestly keeping it at async is probably the best cause then it will not wait for the proc to finish anyways and as i said it doesn't get any feedback back

**Comment by MNarath1** [comment]
> > > why not replace the sleep with a callback or timer
> > 
> > 
> > hmmm maybe timers don't get cached by the linter its worth a try
> 
> you shouldnt be trying to escape the linter you should be trying to fix the problem

thats why i keep it on async i did take a look at how it would work with timer and its not worth the trouble using async is the best strategy simply cause it will keep it from sleeping while it waits for the other proc to finish and it doesn't need it to finish anyways cause there is no feedback that gets returned from that proc.

**Comment by MNarath1** [comment]
In a way that is actually the best solution cause i just realized yes a blob spore could potentially be the hostile/h mob too

**Comment by MNarath1** [comment]
This should do the trick and it doesn't need to change density for blob structures back to FALSE unlike some other PR that where attempted on tg https://github.com/tgstation/tgstation/pull/62247

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
