### PR TITLE
Brig Phys Locker Can Actually Be Opened Again

### PR DESCRIPTION
**Pull request by MCterra10**
## About The Pull Request
coder moment

## Why It's Good For The Game
bashing it open every game isn't fun

## Changelog
:cl:
fix: brig phys locker can be opened again
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Should brig phys have brig phys access?

**Comment by MCterra10** [comment]
> 
> 
> Should brig phys have brig phys access?

captain literally can't open the locker

**Review by PowerfulBacon — APPROVED** [review]
Checked the map files, this doesnt seem to be used for access

**Review by PowerfulBacon — DISMISSED** [review]
brig phys doesnt have brig access lol

**Review by utilbird — APPROVED** [review]

**Pull request merged**
