### PR TITLE
some more combat glove sprite shit

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Applies the combat gloves sprite also to the combat gloves plus and adds character sprites.
## Why It's Good For The Game
because new sprites yay
## Changelog
:cl:
add: Added combat glove plus sprite and adds character sprites to the combat gloves.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
and yes i tested this.

**Comment by MACIEKBAKI** [comment]
show sprites

**Comment by ghost** [comment]
sprite_back
sprite_side
sprite_side2

**Comment by ghost** [comment]
it looks better on an actual character.

**Comment by ghost** [comment]
sprite_front

**Comment by MACIEKBAKI** [comment]
show on character then

**Comment by ghost** [comment]
character_sprite_front
character_sprite_back
character_sprite_side
character_sprite_side2

**Comment by ghost** [comment]
@qwertyquerty  merge pls ok thx

**Pull request merged**
