### PR TITLE
Makes the Detective a real security officer

### PR DESCRIPTION
**Pull request by bloons3**
Alternative to https://github.com/BeeStation/BeeStation-Hornet/pull/4014

## About The Pull Request

Gives the Detective what they've always needed

## Why It's Good For The Game

👍 

## Changelog
:cl:
add: The Detective is now the best armed Security Officer on the station
/:cl:

### CODE REVIEW

**Comment by eeSPee** [comment]
The detective is not a real security officer tho.

**Comment by bloons3** [comment]
You should tell that to Victor

**Comment by VictorVow** [comment]
:salt:

**Comment by ike709** [comment]
I can't tell if this is an April Fools PR or not.

**Comment by eeSPee** [comment]
>### Code Green
>The Detective **may not perform arrests or searches**. Exception is made if there are no active Security Officers or a Warden.
>The Detective **is not permitted to carry any weaponry other than their standard issue equipment**. The Detective's revolver and ammo are one of the notable exceptions.
>### Code Blue
>The Detective is permitted to carry any nonlethal weaponry in addition to their revolver. (and perform arrests)

Kinda fills like you wanna disregard SoP and just go out validhunt like a real seccie.

Play officer instead?

**Comment by bloons3** [comment]
> > ### Code Green
> > The Detective **may not perform arrests or searches**. Exception is made if there are no active Security Officers or a Warden.
> > The Detective **is not permitted to carry any weaponry other than their standard issue equipment**. The Detective's revolver and ammo are one of the notable exceptions.
> > ### Code Blue
> > The Detective is permitted to carry any nonlethal weaponry in addition to their revolver. (and perform arrests)
> 
> Kinda fills like you wanna disregard SoP and just go out validhunt like a real seccie.
> 
> Play officer instead?

which SoP are you using for that?

image

**Review by utilbird — APPROVED** [review]

**Comment by utilbird** [comment]
I hope for a pulse rifle follow up PR but this should work as a bandaid fix for now

**Pull request merged**
