### PR TITLE
Random maint rooms: special jobs

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request

Adds the framework for having job slots open dependent on if their room spawns in maint
Adds the Barber role, a maintenance barber/ghetto surgeon. the barbershop spawns filled with some medical and surgical supplies, hair dye, barber's aid, etc.

the barber gets two unique items: the hand mirror, which can be used for shaving and self-surgery, and the Straight Razor
image

the Straight Razor has 3 uses:
it works as a scalpel
it works as a razor
it works as a weapon, dealing 10 brute and causing high blood loss on harm intent

the bartender currently cannot spawn, and his items are admin only, due to random maintenance being unimplemented.
## Why It's Good For The Game

adding some new roleplay jobs that won't get old

## Changelog
:cl:
add: Barber job and barber shop random room
add: random maint job landmark, opens job slots when it spawns
add: straight razor and hand mirror
add: hair stylist sprays
add: chinese knockoff pda
del: Removed code for removed rooms
tweak: tweaked self surgery and razor interactions with mirrors
imageadd: Straight razor, hand mirror, and various spray sprites
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
don't merge this, still ironing out some issues with the hand mirror

**Comment by ike709** [comment]
Neat.

**Comment by zeskorion** [comment]
Should be ready to merge

**Comment by zeskorion** [comment]
closing so i can refactor this a bit to make it a betterer framework

**Pull request closed without merging**
