### PR TITLE
Motorised wheelchairs

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
Wheelchairs that consume power but go faster and are upgradeable. 

## Why It's Good For The Game
You get to go fast without legs.

## Changelog
:cl:
add: Motorised wheelchairs. Upgrade the power cell, capacitor and manipulators to go even faster for longer.
/:cl:

Ports:
https://github.com/tgstation/tgstation/pull/45737

### CODE REVIEW

**Comment by qwertyquerty** [comment]
What a dumb emag effect. In my opinion they should become so fast that you take a ton of damage from running into anything.

**Comment by VictorVow** [comment]
I'll look into adding that in a future PR, for now I've just removed the emag functionality so this can be merged.

**Comment by despong** [comment]
finally if only i can be able to make an assault vehicle with the wheelchair

**Comment by eLeCtrOssSnake** [comment]
Hahhaahaha yes

**Comment by ike709** [comment]
What could go wrong?

**Pull request merged**
