### PR TITLE
Makes simple bots unable to be summoned while on stationary mode

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
Makes simple bots (medbot, beepsky, cleanbot, etc) unable to be summoned by PDA. Note the ai can still summon stationary bots

as a bonus refactor, stationary_mode is now general to all simple bots and can be tested against for more items in the future

## Why It's Good For The Game
Prevents any old roboticist, med staff, captain, etc. from stealing your personal medibots! Or the stationary medbot that spawns outside medbay,,

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

</details>

## Changelog
:cl:
tweak: medbots can no longer be summoned by PDA while in stationary mode
/:cl:

### CODE REVIEW

**Comment by Eric-01** [comment]
Is it really necessary? With this pull request merged, anyone could go to the medbay and just steal one or more medibots from there, no matter if the bot control panels were locked or not (this action should be trivial, as medbay is one of those departments that basically let everyone in), and then pretend that it has always been their personal bot, with doctors having basically no chance of getting it back.

If someone does not want any wireless communication with their bots (including the summon signal sent by roboticists, captain, etc.), they can simply disconnect their bots from the network using the "Remote network control radio" option in the bot control panels, which is already there.

**Comment by etherware-novice** [comment]
well i stole someones robotics medbot once and they yelled at me so idk i think people would appreciate it

**Comment by itsmeow** [comment]
i was there the round you stole the medibot lol

Jim Berry: "Some fucker summoned my medibot!!"

**Comment by etherware-novice** [comment]
haha yea that was a fun round

**Comment by itsmeow** [comment]
I was poking around in bot control code

TG made it so that bot control is access based on the ID in your tablet.

I think this would be ideal.

**Comment by etherware-novice** [comment]
..well yes and bee grants access through a rom card, what is your point?

**Comment by etherware-novice** [comment]
um..make a new pr for that then? this pr is for stationary mode

**Comment by itsmeow** [comment]
I don't think making bot control locked on stationary mode is a good idea.

**Comment by Eric-01** [comment]
Being able to steal someone else's stationary bot remotely is a problem, I totally get it. However, I don't like your solution for the reasons described in my previous comment here. A better solution to this problem is already in the game and is to completely disconnect the bots from the network using the "Remote network control radio" option.

**Comment by Penwin0** [comment]
This should be tied to a different setting if at all, this shouldn't be tied to stationary mode

**Pull request closed without merging**
