### PR TITLE
Demoted job title is now "Demoted" instead of "Unassigned"

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
Demoted job title is now "Demoted" instead of "Unassigned"

## Why It's Good For The Game
* `Unassigned` is not a good term in-game since it false-alerts coders for possible bugs
* "Demoted" as a crew title... this can make it public shame, and I think it can possibly make more RP moments with it.

 
## Testing Photographs and Procedure

It's just a string edit.

## Changelog
:cl:
tweak: Demoted job title is now "Demoted" instead of "Unassigned"
/:cl:

### CODE REVIEW

**Comment by EvilDragonfiend** [comment]
actually, I can't think of any better term for that besides using Unassigned. `Dishonourable` might be too offensive.

**Comment by itsmeow** [comment]
"Demoted"

**Comment by EvilDragonfiend** [comment]
flavourless, but alright

**Comment by PowerfulBacon** [comment]
does it have a sec hud icon?

**Comment by EvilDragonfiend** [comment]
> does it have a sec hud icon?

It's not what related to sec hud icon since we don't use job titles to sec hud anymore.

**Comment by Rukofamicom** [comment]
Don't forget to update the info section - still says dishonorable there.

**Comment by EvilDragonfiend** [comment]
> Don't forget to update the info section - still says dishonorable there.

Changed other sections except for one lol

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
