### PR TITLE
Pubby Improvement: Science

### PR DESCRIPTION
**Pull request by imsynthex**
## About The Pull Request

(Yes, I am making this PR for the 4th time, this is the last one, promise)
Pubby

## Why It's Good For The Game

Pubby bad, this makes Pubby slightly less bad

## Changelog
:cl:
tweak: Made it so there is no hallway running through Science on Pubbystation
add: Added a nanite lab to Pubbystation Science
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
> (Yes, I am making this PR for the 4th time, this is the last one, promise)

> This pull request has conflicts, please resolve those before we can evaluate the pull request.

it's not the last one
please make another then another one after that when supercruise gets merged

**Comment by imsynthex** [comment]
> it's not the last one
> please make another then another one after that when supercruise gets merged

im fixing this once supercruise gets merged, also yes, the 13024850th iteration of this PR is coming in a few days 😎

**Comment by SergeiKoralev** [comment]
This is literally the thing standing between me and re-piping Pubby.

**Comment by ike709** [comment]
Stale

**Comment by qwertyquerty** [comment]
:key:

**Pull request closed without merging**
