### PR TITLE
Modernises uplinks

### PR DESCRIPTION
**Pull request by Cenrus**
tgstation/tgstation#58872
tgstation/tgstation#51828
tgstation/tgstation#58625
tgstation/tgstation#58542
tgstation/tgstation#59735
tgstation/tgstation#58470

## About The Pull Request

1. Adds uplink implant as a choice in preferences, but it will reduce your starting TC by 3.
2. Uplinks now use flags to determine what can and can't be purchased, instead of the include/exclude mode stuff.
3. Population restricted items will automatically unlock when enough people are playing
4. Starting TC is now kept as a define

## Why It's Good For The Game

Improved code quality and more control over how uplink items are restricted. 

## Changelog

:cl: Coiax, Cenrus, Supernovaa41, Mothblocks, RandomGamer123
add: Uplink implant choice in preferences. deducts 3 TC when used.
fix: Uplinks will now be implanted internally if the game can't find anywhere to put it
add: Population restricted uplink equipment will now automatically unlock when enough players are active
fix: Fixed syndicate uplink UI not having a name
/:cl:

### CODE REVIEW

**Comment by jupyterkat** [comment]
no roundstart implants, that’ll just encourage shitsec to implant check everyone

**Comment by Cenrus** [comment]
The uplink implant is not forced, you have to pick it yourself. Incursionists and BBs already get round start implants anyway.

**Comment by BrumalLake** [comment]
roundstart implants when you can just buy the implant and do it anyways, how is this gonna get everyone to implant check
i'd implant check anyways if i didn't think they had an uplink implant

**Comment by jupyterkat** [comment]
you’d still have to go somewhere to insert it in and dispose it

**Comment by jupyterkat** [comment]
having a removable implant that is easily checked than a passworded pda or a rotating pen is certainly a worse idea anyways. plus if you lose those items you shouldn’t be an antag at all

**Comment by BrumalLake** [comment]
then remove the uplink implant, cause you can get it anyways without this
hiding the implanter isnt hard and not having to hide it makes it so that they won't check for implants as often as you were complaining about

AND IT COSTS 3 TC
it still costs something

**Comment by jupyterkat** [comment]
the point is there’s even more implant checkable antags roundstart than there is before. plus yall removed the chem that reveals lings so make it follow the flow?

**Comment by Cenrus** [comment]
The whole roundstart implanting thing for BBs and Incursionists is concerning and IAA does the whole implanting thing right by making it entirely undetectable, but this is for another PR.

**Comment by PowerfulBacon** [comment]
What if the mob is not human and cannot be implanted?

**Comment by ivanmixo** [comment]
> the point is there’s even more implant checkable antags roundstart than there is before. plus yall removed the chem that reveals lings so make it follow the flow?

I don't know if you get this, but the implant uplink isn't mandatory....

**Comment by Cenrus** [comment]
> 
> 
> What if the mob is not human and cannot be implanted?

Nothing happens, the proc that assigns uplinks will return if the mind isn't controlling a human.

**Comment by utilbird** [comment]
Uplink implants should not be roundstart. It removes the entire issue of disposing of the evidence, something every other implant *traitor* item suffers from. It's not the TC count that matters, it's the sidestepping of a game mechanic as a "preference".

**Comment by Sinestia** [comment]
> 
> 
> Uplink implants should not be roundstart. It removes the entire issue of disposing of the evidence, something every other implant _traitor_ item suffers from. It's not the TC count that matters, it's the sidestepping of a game mechanic as a "preference".

This fits the spirit of spending TC imo. 

If you want to remove that issue, you pay up for it.

**Comment by heepox** [comment]
Merge soon?

**Review by Archanial — APPROVED** [review]

**Pull request merged**
