### PR TITLE
[PORT] RBMK reactor from our good friends in NSV

### PR DESCRIPTION
**Pull request by Moccha-Bee**
## About The Pull Request
Adds the RBMK reactor from NSV, adding one more reactor for good engineer mains like me to master and brake as well as terrifying the station with graphite 
image

from:https://github.com/BeeStation/NSV13/pull/828 and also https://github.com/austation/austation/pull/2375 and as well as https://github.com/BeeStation/NSV13/pull/781 , https://github.com/BeeStation/NSV13/pull/840 and https://github.com/BeeStation/NSV13/pull/824 and now also https://github.com/austation/austation/pull/2402 and https://github.com/austation/austation/pull/2404 
Credits go to Kmc2000 from NSV and JupiterKat from Austation. And also PowerfulBacon for the follow up pool prs. And also fakeElon from austation.

## Why It's Good For The Game
Engineers are a bunch of pussies and need to learn that true power dosen't come from a "glowy yellow crystal" but from an open channel graphite moderated water cooled reactor with a positive void coefficient.

## Changelog
:cl: Kmc, JupiterKat,FakeElon,PowerfulBacon(verypowerful indeed),ZombiesVSPlants.
add: Added the RBMK reactor.
add: Added the pool from nsv
add: Added the fuel rods as a cargo crate.
fixed: the fuel rods being called u238 to the correct u235.
/:cl:

### CODE REVIEW

**Comment by Moccha-Bee** [comment]
this is poggers momment

**Comment by PowerfulBacon** [comment]
clean up the meme icon state names

**Comment by ghost** [comment]
image

**Comment by Moccha-Bee** [comment]
i blame it on gitkraken not being able to properly rebase :salute:

**Comment by AnjelicaChaykovsky** [comment]
Bro most engis blow up sm in 10 mins nowadays.
I already hide in locker each round from what u said is glowy yellow crystal,  which implies that new engine is harder?

**Comment by Moccha-Bee** [comment]
> Bro most engis blow up sm in 10 mins nowadays.
> I already hide in locker each round from what u said is glowy yellow crystal, which implies that new engine is harder?

its only hard if you lack a frontal cortex

**Comment by ghost** [comment]
> > Bro most engis blow up sm in 10 mins nowadays.
> > I already hide in locker each round from what u said is glowy yellow crystal, which implies that new engine is harder?
> 
> its only hard if you lack a frontal cortex

So most beestation players?

**Comment by Moccha-Bee** [comment]
> > > Bro most engis blow up sm in 10 mins nowadays.
> > > I already hide in locker each round from what u said is glowy yellow crystal, which implies that new engine is harder?
> > 
> > 
> > its only hard if you lack a frontal cortex
> 
> So most beestation players?

yes

**Comment by Moccha-Bee** [comment]
@PowerfulBacon hello coder, is this pr up to standards with tgui4?

**Comment by Moccha-Bee** [comment]
I also already added the guide for the reactor to the wiki.

**Comment by utilbird** [comment]
Why have you made the same PR 3 times 🤔

**Comment by Moccha-Bee** [comment]
> Why have you made the same PR 3 times 🤔

gamer

**Comment by utilbird** [comment]
Imagine bumping PRs

**Comment by Moccha-Bee** [comment]
> Imagine bumping PRs

not on discord 🤷🏻‍♂️

**Comment by Moccha-Bee** [comment]
>Conflicting files
tgui/packages/tgui/public/tgui.bundle.js
tgui/public/tgui-common.chunk.js
tgui/public/tgui-panel.bundle.js
tgui/public/tgui.bundle.js

mfw

**Comment by utilbird** [comment]
>catgirls don't like water

Cute

**Comment by Moccha-Bee** [comment]
Before anyone asks, i can't keep working on my other prs at this time due to finals coming up and i would rather close the pr then leave it stale.

**Pull request closed without merging**
