### PR TITLE
Replaced revs with speedyrevs

### PR DESCRIPTION
**Pull request by AnCopper**
## About The Pull Request

Replaced revolution with speedy revolution, it's exactly like revolution except the station blows up after 40 minutes.

## Why It's Good For The Game

To prevent 2 hour hide and seek rounds.

## Changelog
:cl:
config: replaced revolution with speedy revolution.
/:cl:

### CODE REVIEW

**Comment by super12pl** [comment]
what
why

**Comment by AnCopper** [comment]
> what
> why

image

**Comment by Sinestia** [comment]
Timer should be moved to like 30 or 40 minutes imo. 

It's also worth mentioning that super long hide and seeks don't happen terribly much in my experience, I think usually if an admin is on and it devolves to that they push it to end.

**Comment by TeomanTheGreat** [comment]
> 
> 
> Timer should be moved to like 30 or 40 minutes imo.
> 
> It's also worth mentioning that super long hide and seeks don't happen terribly much in my experience, I think usually if an admin is on and it devolves to that they push it to end.

i agree with the timer change but hide and seeks are in fact rare. I would assume the motivation for the pr had to do with the recent round that happened.

**Comment by BrumalLake** [comment]
how does this game mode work when does it tell you the station is gonna go boom and turn into a steaming crater
the start i presume

**Comment by AnCopper** [comment]
> how does this game mode work when does it tell you the station is gonna go boom and turn into a steaming crater
> the start i presume

After 40 minutes run out the stations self destruct gets activated with a 200 second timer, that is the only difference.

**Comment by BrumalLake** [comment]
now the very super critical important question is the self-destruct warning hrp friendly
time pressure sounds fun though, makeshift weapons don't take that long to make and maybe some revs will be less passive and assist their heads getting their ass beat in front of them

all we really need is a good way to tell how much time has passed exactly since the round has started
wici

**Comment by AnCopper** [comment]
> all we really need is a good way to tell how much time has passed exactly since the round has started

image

**Comment by BrumalLake** [comment]
> 
> 
> > all we really need is a good way to tell how much time has passed exactly since the round has started
> 
> image

sadly doesn't start when the round starts precisely just in the lobby

**Comment by AnCopper** [comment]
> > > all we really need is a good way to tell how much time has passed exactly since the round has started
> > 
> > 
> > image
> 
> sadly doesn't start when the round starts precisely just in the lobby

Nah.
https://github.com/BeeStation/BeeStation-Hornet/pull/5039

**Comment by PowerfulBacon** [comment]
This is dumb, make it so the heads and the head revs get tracking implants rather than just killing everyone and making nobody win.

**Pull request closed without merging**
