### PR TITLE
Makes the hostile mutant breadloaf drop plain bread slices upon being butchered

### LINKED ISSUE #8247: If you Butcher mutant bread you get "snack" an invisible item
## Reproduction:
teleport bread and kill the creature then butcher it

bread
i always wondered why they dont drop sliced bread... or tumors

### PR DESCRIPTION
**Pull request by CydiaLamiales**
## About The Pull Request
* closes https://github.com/BeeStation/BeeStation-Hornet/issues/8247

Makes the hostile mutant bread loaf drop plain bread slices upon being butchered.

## Why It's Good For The Game
Less invisible items good.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image

image

</details>

## Changelog
:cl:
fix: Fixed hostile breadloaf dropping invisible bread upon being butchered
/:cl:

### CODE REVIEW

**Comment by St0rmC4st3r** [comment]
How about we make it meat bread?

**Comment by CydiaLamiales** [comment]
> How about we make it meat bread?

Why? It's not like it became meat in the original either
image

**Review by Penwin0 — APPROVED** [review]

**Comment by Tsar-Salat** [comment]
> Why? It's not like it became meat in the original either

Because. It sure as hell didn't make white bread. 

Also, why the hell are you making it *white bread*

There exists an icon for it already:

image

**Comment by Penwin0** [comment]
I mean the mutant bread "corpse" looks like plain bread there, if you are going to change how the slices look like change the corpse as well

**Comment by CydiaLamiales** [comment]
> I know its an unused simplemob rn, but just copy the plainbread stats and use the mutantbreadslice icon on top.

It's actualy spawnable, that's why I didn't use that icon. Also it becomes a regular bread splice once it dies, that's why I went with 'plain'

**Review by Archanial — APPROVED** [review]

**Pull request merged**
