### PR TITLE
Removes the backsurge event, but keeps the beer nuke

### PR DESCRIPTION
**Pull request by ivanmixo**
## About The Pull Request

Removes the scrubber backsurge event completely. Renames the file to reflect the new contents (the beer nuke surge code). 

## Why It's Good For The Game

Backsurge is easily the worst event, not because it's actually too harmful to the station, but because it 

- Takes way too long
- Makes everything ugly
- Causes lag
- See above

## Testing Photographs and Procedure

<details>

<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/22431091/158071520-13958111-2ea8-407c-9c47-6206400e38bf.mp4

</details>

## Changelog
:cl:
del: Removes the backpressure surge event
/:cl:

### CODE REVIEW

**Comment by FriendlyContractor** [comment]
* I disagree with point one it creates interesting opportunity for resourcefull antagonists. Also duration is random
* Absolutely agree here i hate when my workplace turns rainbow
* Not an expert here does it really ?

However while its annoying it makes the game more interesting providing opportunities for janitor to clean and engineerings to fix things. You should offer some replacement even if its just random explosions on the station

**Comment by mcmeiler** [comment]
> * I disagree with point one it creates interesting opportunity for resourcefull antagonists. Also duration is random

No it's not. The only reason it seems random is because of the massive amount of lag... Which the event itself causes.

**Comment by ivanmixo** [comment]
>I disagree with point one it creates interesting opportunity for resourcefull antagonists. Also duration is random

It is actually random, but lag usually extends it super loooooong.

>Not an expert here does it really ? 

Hmm does processing foam on every turf on the station cause lag? (Yes)

Janitors have work to do. Engineers too. The radstorm is basically this event but done good.

**Comment by Wilchenx** [comment]
another goofcode feature removal

**Comment by Sinestia** [comment]
I like it but its fair to want it gone 


 I do think it is too common, so if it is kept it should have its odds reduced.

**Review by Archanial — APPROVED** [review]

**Comment by BrumalLake** [comment]
also erases tcomms code if it happens to be alcohol

**Comment by ta3370** [comment]
My feelings on it are that it should have the Random Backpressure event, and the Random Beer events removed, but still have the non-random Beernuke event for when somebody who has the Nuke Codes somehow gets the Beer Nuke.

NSV had a really hillarious round of a crew saying their goodbyes when some of them knew they were about to miss the shuttle departure, only for the "nuke" to go off a few seconds early and everyone scrambling around drunk for the real nuke, because the Beernuke had ended up in a random hallway and the Captain didn't take five seconds to inspect it before trying to input the code repeatedly.

It can be so fun when the flub happens.

**Comment by ivanmixo** [comment]
This PR removes all the random backsurge events, and only keeps the one when you trigger the nuke in.

**Comment by DatBoiTim** [comment]
> goofcode

This is all the justification we need for removal!

**Comment by Isy232** [comment]
fuck yes nuke this event its by far the worst

no janitor wants to have to clean the entire station because "lol random event", having to clean up after a bloody fight has some meaning to it at least.

then there's also the random chance an entire room can just get acided and essentially deleted, requiring extensive repairs. Which are fine if its player caused, but random events shouldn't cause uncounterable massive station damage.

let the players actions decide what needs to be repaired or cleaned instead of just making them do shit for random event reasons.

**Comment by Sapfearon** [comment]
speedmerge it, by far worst event nobody likes. Doesn't make sense either since scrubber only scrubbing AIR and we don't have any water piping/plumbing at all.

**Comment by Daridine** [comment]
Any chance this could just change how far each scrubber spreads?
Like, half the room instead of filling the room?

**Pull request merged**
