### PR TITLE
Exosuit tweaks

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Changed a few things in response to player requests/complaints

## Why It's Good For The Game
Something about people don't have the patience to drag the suit from the suit slot to their hand and exosuits act weird with pockets

## Changelog
:cl:
tweak: Made exosuit pockets open on alt-click only
tweak: hardsuits no longer have pockets due to potential code issues
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
It looks like you removed pockets from the helmet and not the actual hardsuit

**Comment by MarkSuckerberg** [comment]
Gonna pretend that never happened

**Comment by qwertyquerty** [comment]
What are the potential code issues?

**Comment by MarkSuckerberg** [comment]
The hardsuit helmet and jetpack upgrade for whatever reason seem to use concrete to store themselves inside the hardsuit, and when you take out the jetpack, it still thinks you have a jetpack attached, you just can't use it, and you need to unscrew it from the hardsuit even though it isn't there to reinstall it, as you can't fit hardsuit jetpack upgrades into the pockets.

**Pull request merged**
