### PR TITLE
A victory for revolutionaries will no longer end the round on dynamic, instead no new security and command will be allowed to join (tg#55956)

### LINKED ISSUE #3863: Dynamic: Revs holding the round hostage
Dynamic revs does not end then the heads of staff are exiled or killed off.

## Reproduction:

1. Spawn revs on dynamic
2. Kill heads
3. Round doesn't end and the shuttle is locked, preventing it from leaving and ending the round

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/97516963-dynamic-revs-holding-the-round-hostage?utm_campaign=plugin&utm_content=tracker%2F120077027&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F120077027&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Cenrus**
Original PR: https://github.com/tgstation/tgstation/pull/55956

Closes #3863

Revolution is the only mode that ends the round when they are successful, outside of ops/cult. This can be anti climatic for the other antagonists in the round.

:cl:Mothblocks
add: A victory for revolutionaries will no longer end the round on dynamic, instead no new security and command will be allowed to join.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
I think the shuttle should be force called at this point too

**Comment by wraith-54321** [comment]
but it should be a kinda long call, or can be recalled

**Comment by Cenrus** [comment]
Doesn't that ruin the point?

**Comment by OceanFish1** [comment]
> Doesn't that ruin the point?

It does tho

**Comment by Cenrus** [comment]
Shuttle is now autocalled but it can be recalled if the station wants to

**Review by ike709 — APPROVED** [review]

**Pull request merged**
