### PR TITLE
Antagonist Token Improvements

### PR DESCRIPTION
**Pull request by PowerfulBacon**
Forever now, antagonist tokens have destroyed the balance of the game, infuriating players and completely disrupting the flow of the round, but I have nerfed that.

Just kidding, this just makes them more useable.

## About The Pull Request

Antagonist tokens can now be used in the OOC tab by the client and will give the user forced antagonist for that round (if available) at the cost of 1 token, however they will not know what antagonist they are going to be and cannot pick (Antagonist tokens now force you to be antag, rather than let you pick what antag you want to be).

Tests ran:
 - Attempting to use an antagonist token with no tokens [Success]
 - Attempting to use an antagonist token with a token [Success]
 - Attempting to use an antagonist token but not readying up [Success]
 - Attempting to use an antagonist token, but subtracting the token away before used [Success]
 - Attempting to use the antagonist token on extended [Success]
 - No database access [Success]

## Why It's Good For The Game

Less work for admins, a better system in general. Slightly nerfed antag tokens so they could be given out for other things (maybe).

## Changelog
:cl:
refactor: refactored antagonist tokens to be useable without admin intervention.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
This seems to work good

**Comment by PowerfulBacon** [comment]
damn forgot to add the code that lets people with the ckey powerfulbacon use this without tokens 😳

**Comment by Flakkyboo** [comment]
I dunno about this chief I'd really like to chose my Antag with the token.
I really like to be swarmer

**Comment by PowerfulBacon** [comment]
> 
> 
> I dunno about this chief I'd really like to chose my Antag with the token.
> I really like to be swarmer

You'd probably still be allowed to pick certain midrounds in exchange for changes, but having them less powerful is better since they can be given out for things that aren't as major as admin griefs the server.

**Comment by zeskorion** [comment]
if this is the case, would there be some way to automatically hand them out in case of crashes as well

**Comment by Flakkyboo** [comment]
> 
> 
> > I dunno about this chief I'd really like to chose my Antag with the token.
> > I really like to be swarmer
> 
> You'd probably still be allowed to pick certain midrounds in exchange for changes, but having them less powerful is better since they can be given out for things that aren't as major as admin griefs the server.

nerfing it a bit would be nice and keeping the essence of being able to keep the choice would also be pretty nice

**Comment by zeskorion** [comment]
it still checks for the antags you have enabled, right?

the big thing is, for low-count antags like nukes or wizards, you dont want token fucks to cuck the non-tokens

**Comment by PowerfulBacon** [comment]
> 
> 
> it still checks for the antags you have enabled, right?
> 
> the big thing is, for low-count antags like nukes or wizards, you dont want token fucks to cuck the non-tokens

It gives you any antag no matter your preferences. Otherwise people would only have it on wizard, and you would require an antag token to roll it.
Antagonist tokens are meant to give you a replacement antag round, not the best one in the game.

**Comment by zeskorion** [comment]
> > it still checks for the antags you have enabled, right?
> > the big thing is, for low-count antags like nukes or wizards, you dont want token fucks to cuck the non-tokens
> 
> It gives you any antag no matter your preferences. Otherwise people would only have it on wizard, and you would require an antag token to roll it.
> Antagonist tokens are meant to give you a replacement antag round, not the best one in the game.

here's the thing: i dont wanna get a token for *traitor* and then roll blood brothers, cult, revs, any of that gay shit. If you can't token for midrounds or even be guaranteed to get something that *isn't* shit anymore, why token at all

**Comment by PowerfulBacon** [comment]
> 
> 
> > > it still checks for the antags you have enabled, right?
> > > the big thing is, for low-count antags like nukes or wizards, you dont want token fucks to cuck the non-tokens
> > 
> > 
> > It gives you any antag no matter your preferences. Otherwise people would only have it on wizard, and you would require an antag token to roll it.
> > Antagonist tokens are meant to give you a replacement antag round, not the best one in the game.
> 
> here's the thing: i dont wanna get a token for _traitor_ and then roll blood brothers, cult, revs, any of that gay shit. If you can't token for midrounds or even be guaranteed to get something that _isn't_ shit anymore, why token at all

I don't expect it to completely phase out admins, as midrounds will still need to be done through admins (abductors, sentient disease etc.), but they serve as an alternative to the roundstart ones, which previously could spawn antagonists on other gamemodes (devils on traitors, lings on devils etc.).

An idea that _could_ world:
 - You get a list of antags and can pick 3 that you don't want to be, meaning you can disable antagonists you really would hate, but can't make it so you can keep using it until you roll wizard or nuke or one of the S tier antags.

**Comment by zeskorion** [comment]
> > > > it still checks for the antags you have enabled, right?
> > > > the big thing is, for low-count antags like nukes or wizards, you dont want token fucks to cuck the non-tokens
> > > 
> > > 
> > > It gives you any antag no matter your preferences. Otherwise people would only have it on wizard, and you would require an antag token to roll it.
> > > Antagonist tokens are meant to give you a replacement antag round, not the best one in the game.
> > 
> > 
> > here's the thing: i dont wanna get a token for _traitor_ and then roll blood brothers, cult, revs, any of that gay shit. If you can't token for midrounds or even be guaranteed to get something that _isn't_ shit anymore, why token at all
> 
> I don't expect it to completely phase out admins, as midrounds will still need to be done through admins (abductors, sentient disease etc.), but they serve as an alternative to the roundstart ones, which previously could spawn antagonists on other gamemodes (devils on traitors, lings on devils etc.).
> 
> An idea that _could_ world:
> 
> * You get a list of antags and can pick 3 that you don't want to be, meaning you can disable antagonists you really would hate, but can't make it so you can keep using it until you roll wizard or nuke or one of the S tier antags.

you could never get wizard or nuke with it before, why not just make it so it both checks preferences and blacklists those antags?

**Comment by MarkSuckerberg** [comment]
against god and nature, anyone who uses this rather than asking their friendly neighborhood admin is a heretic and must be burned at the stake

**Comment by ike709** [comment]
Headmins said no.

**Pull request closed without merging**
