### PR TITLE
Explorers No Longer Maint Crawl to Prep Area on Some Maps

### PR DESCRIPTION
**Pull request by DatBoiTim**
## About The Pull Request
Tox Storage Access for Exploration Crew.

## Why It's Good For The Game
I don't want to have to go through maints to get to the prep area. This affects Metastation first and foremost.

## Changelog
:cl:
tweak: Exploration Crew has all the access they may need to get to their prep room without a maint crawl
/:cl:

### CODE REVIEW

**Comment by DatBoiTim** [comment]
Gonna make it a map change per fran's request

**Comment by BrumalLake** [comment]
how a coderman solves a mapping issue

**Comment by PowerfulBacon** [comment]
the reason they lost it was because they stole plasma tanks from toxins.

**Comment by DatBoiTim** [comment]
> the reason they lost it was because they stole plasma tanks from toxins.

You could have changed the access for the toxins main area to be different from the storage room. In fact, there's two separate access types for that.

I am cleaning this up.

**Comment by francinum** [comment]
> 
> 
> the reason they lost it was because they stole plasma tanks from toxins.

And you did no regression testing?

**Comment by PowerfulBacon** [comment]
> And you did no regression testing?

Nah I gave them a path in maints instead

**Comment by DatBoiTim** [comment]
> > And you did no regression testing?
> 
> Nah I gave them a path in maints instead

You also made the toxins internal storage door on meta have a separate access than the external toxins doors. So now I have to check every single door of that type on each map.

**Comment by williamcll** [comment]
Nah give them atmos access instead.

**Comment by PowerfulBacon** [comment]
> You also made the toxins internal storage door on meta have a separate access than the external toxins doors. So now I have to check every single door of that type on each map.

I didn't touch toxins, I touched the maint doors.

**Comment by PowerfulBacon** [comment]
This PR is a more proper solution excluding changing the map a lot https://github.com/austation/austation/pull/4102

**Comment by DatBoiTim** [comment]
Seeing that you're just superseding yet another PR, I'll just close this and wash my hands of this.

**Comment by PowerfulBacon** [comment]
Its a lot of work to remap it and my problem, it would be unfair to ask you to make large changes to box science instead of updating the doors in toxins.

**Pull request closed without merging**
