### PR TITLE
Fixes few jumpsuit errors

### LINKED ISSUE #6364: Durathread Jumpsuit no longer displays on character or in inventory

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Fixes durathread jumpsuit not having icon by repathing it to use GAGS.
Removes wrong path on lawyer's skirts.
Removes some weird '.
Removed unused psyche jumpsuit.

closes: #6364

## Changelog
:cl:
fix: fixed durathread jumpsuit not having icons
fix: fixed a few lawyer skirts having wrong paths.
del: removed unused psyche jumpsuit
/:cl:

### CODE REVIEW

**Comment by BrumalLake** [comment]
if you're gonna get rid of the psyche jumpsuit you may as well get rid of its sprite that has about 20 frames

**Comment by Archanial** [comment]
> if you're gonna get rid of the psyche jumpsuit you may as well get rid of its sprite that has about 20 frames

it's already deleted

**Comment by heepox** [comment]
NOOO MY EPIC PSYCHEDELIC SUIT FOR CHAMELEON SHENANIGANCE!!!

**Comment by heepox** [comment]
CURSE YOU SPEEDMERGE

**Pull request merged**
