### PR TITLE
Simple fires

### LINKED ISSUE #11039: Non-fire caused hotspots should not be on the atmospherics subsystem
Atmos is a background subsystem and under lag they will never go away

### PR DESCRIPTION
**Pull request by PowerfulBacon**
fixes #11039 

## About The Pull Request

Creates a new simple fire type that doesn't run on the atmos system. They require oxygen, but do not consume it, will merge and spread if big enough and will turn into atmospheric fires if they ignite the air.

## Why It's Good For The Game

Fire from dragons and other non-atmopsheric sources won't last forever if atmos is pushed into the background. Also the fires from dragons will burn the floor tiles

## Testing Photographs and Procedure

image

image

image

image

## Changelog
:cl:
tweak: Fires caused by space dragons, chemicals and other non-atmopsheric sources are now optimised to run at high time-dilations.
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
if these are different from gas fires it might be a good idea to give them a different sprite?

**Comment by PowerfulBacon** [comment]
They process different from gas fires, but are intended to work in a way that makes it so its hard to tell the difference between them. If they are in flammable gasses, they will seemlessly convert into full gas fires.

**Comment by Rukofamicom** [comment]
seamlessly

**Review by Rukofamicom — APPROVED** [review]

**Comment by Rukofamicom** [comment]
Fix lint issues and ping me (or self merge)

**Pull request closed without merging**
