### PR TITLE
Detective can be a traitor again,

### PR DESCRIPTION
**Pull request by Wilchenx**
## About The Pull Request

Detective can be a traitor again.

## Why It's Good For The Game

Bad corrupt cop within the security departament breaks the "we can always trust eachother" meta, introduces more intrigue and paranoia.

## Changelog
:cl:
tweak: detective can be a traitor again
tweak: detective is no longer mindshielded
/:cl:

### CODE REVIEW

**Comment by AnCopper** [comment]
Meme PR.

**Comment by Wilchenx** [comment]
> Meme PR.

And why are you saying that?

**Review by Archanial — CHANGES_REQUESTED** [review]
If you are gonna do that mirror the changes onto dynamic gamemode rulesets

**Comment by Wilchenx** [comment]
> If you are gonna do that mirror the changes onto dynamic gamemode rulesets

Should I remove mindshield too?

**Comment by Raven-Industries** [comment]
"I sure do love being falsely convicted of a capital crime because security assumes that any evidence that the detective says exists really exists" 
and the HoS's parallel
"I sure do love being the subject of multiple shitsec ahelps because I trusted the evidence my detective gave me" 
Not saying some good RP couldn't come of this, but apparently the ability of beestation players to roleplay has been called into question, so the antag detective gameplay is going to look like this:
>print lethal rounds at seclathe
> go up to target and BLAM BLAM BLAM 
> ".s Hey HoS, I found a murder in maints, DNA says that [other target] is the killer. Looks like they spaced the brain too."
>capital crime execution time

**Comment by heepox** [comment]
> "I sure do love being falsely convicted of a capital crime because security assumes that any evidence that the detective says exists really exists" and the HoS's parallel "I sure do love being the subject of multiple shitsec ahelps because I trusted the evidence my detective gave me" Not saying some good RP couldn't come of this, but apparently the ability of beestation players to roleplay has been called into question, so the antag detective gameplay is going to look like this:
> 
> > print lethal rounds at seclathe
> > go up to target and BLAM BLAM BLAM
> > ".s Hey HoS, I found a murder in maints, DNA says that [other target] is the killer. Looks like they spaced the brain too."
> > capital crime execution time

or the hos just asks to review the evidence and see the crime scene themselves...
and revive the guy you killed to ask him questions... in which they reveal your duplicity and you instead get perma sentance...
This would force hos to pay attention to avoid getting baited into shitseccery

**Comment by Raven-Industries** [comment]
> or the hos just asks to review the evidence and see the crime scene themselves... and revive the guy you killed to ask him questions... in which they reveal your duplicity and you instead get perma sentance... This would force hos to pay attention to avoid getting baited into shitseccery

I'd love if this is how things go, and I'm fully prepared to eat crow if it does, but I don't have faith that it will.

**Comment by Wilchenx** [comment]
I want to shake things up and I think this is a great way to do it. Make security actually use and look into evidence.

**Comment by PowerfulBacon** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/5236

In before this PR gets some talk and discussion for a week, goes dead, gets marked as stale by a maintainer that doesn't like it despite not being reviewed by any maintainers then get closed.

**Comment by Wilchenx** [comment]
> Should I remove mindshield too?

**Comment by AnCopper** [comment]
> > Should I remove mindshield too?

Obviously.

**Comment by FriendlyContractor** [comment]
I think this a good change. I think its bad in its current state where detective is metaprotected but treated as some sort of "lesser security"

**Comment by KennyBadrige** [comment]
I'm yet to see why this would be a good thing. This solves an non existant issue. 


> the hos just asks to review the evidence and see the crime scene themselves...
> and revive the guy you killed to ask him questions... in which they reveal your duplicity and you instead get perma sentance...
> This would force hos to pay attention to avoid getting baited into shitseccery

This is just HoS being the detective.

Change for the sake of "shaking things up" isnt a good reason. Nobody liked antag heads.

**Comment by Wilchenx** [comment]
> > the hos just asks to review the evidence and see the crime scene themselves...

Imagine that, HoS doing his job.

> > and revive the guy you killed to ask him questions... in which they reveal your duplicity and you instead get perma sentance...

Imagine that, security doing its job.

> > This would force hos to pay attention to avoid getting baited into shitseccery

Imagine that, HoS doing his job.

**Review by Sinestia — CHANGES_REQUESTED** [review]
This generates fun on SEKRIT РУССКИИ SERVER but bee players are really dumb. 

 Also, for this to work, at minimum you need some mapping changes. If we want detective to be a tator he should get less brig access, IIRC he has a decent amount. Also his tools should be less readily available so sec don't just bypass him. 

 One other problem too is that I'm not sure if even detective players would play it correctly, most will probably just be bad all the time and not even remotely do their job (as the rules allow it) instead of MOSTLY doing their job, and then abusing sec's trust once it has been built.

**Comment by Archanial** [comment]
I am fine with the change.

Headmins suggested he should get his own color palette now, that he's officially not security and antag available but that's out of scope here.

**Review by Archanial — DISMISSED** [review]
Gonna leave it open for a while

**Comment by PowerfulBacon** [comment]
> I am fine with the change.
> 
> Headmins suggested he should get his own color palette now, that he's officially not security and antag available but that's out of scope here.

I don't think changing stuff like the colour pallette, the icon, the job being a part of security etc. is out of scope for this PR. If its going to change something at least change it properly.

**Comment by DerpiestBruh** [comment]
> breaks the "we can always trust eachother" meta, introduces more intrigue and paranoia.

wilchen too based for beestation

**Comment by Fronsis** [comment]
If the issue is ''detective getting evolver asap, print lethals and kill target'' maybe he should lose the access to the lathe or lock  their revolver somewhere in office/armory? that can only be opened by hos/warden/the det on code blue

Of course they can hack a lathe to print the ammo and other alternatives but that way, at least with only the lathe access removed it should diminish the mentality of ''yes... i must use revolver to kill my target, no gimmicks.. no planning.. just click until spessman horizontal for dopamine and invisible greentext..''

Also it would be cool if they get some traitor items unique to em, detective related or even go go gadgety lmao

**Comment by Wilchenx** [comment]
>If the issue is ''detective getting evolver asap, print lethals and kill target'' 

as opposed to buying the same stuff with tc and doing it anyways?

>maybe he should lose the access to the lathe

most maps have the techfab behind brig office anyway (only officers and above have access)

>Headmins suggested he should get his own color palette now, that he's officially not security and antag available but that's out of scope here.

Technically the detective never was "security" as he had no proper access to process prisoners anyway.

>Also his tools should be less readily available so sec don't just bypass him.

I can take out forensic scanner from the techfab in this pr if that's necessary

>[...] then abusing sec's trust once it has been built.

yeah the gamemode is called traitor

**Comment by heepox** [comment]
> One other problem too is that I'm not sure if even detective players would play it correctly, most will probably just be bad all the time and not even remotely do their job (as the rules allow it) instead of MOSTLY doing their job, and then abusing sec's trust once it has been built.

reminds me of Detective on goon

**Comment by DatBoiTim** [comment]
> I want to shake things up and I think this is a great way to do it. Make security actually use and look into evidence.

Bro go full send and remove metashielding from anyone but heads of staff and warden.

Only reason heads of staff are metashielded is because they can wind up with very easy objectives(steal a piece of equipment from own department, etc.).

Warden because he's basically HoS the 2th.

**Comment by Crossedfall** [comment]
> I want to shake things up and I think this is a great way to do it. Make security actually use and look into evidence.

But uh.. Isn't that why they have the detective? :thinking:

I feel like this will have the adverse effect and feed into the toxic tg sec-mentality that plagues everyone running downstream.

**Comment by Wilchenx** [comment]
> > I want to shake things up and I think this is a great way to do it. Make security actually use and look into evidence.
> 
> But uh.. Isn't that why they have the detective? 🤔
> 
> I feel like this will have the adverse effect and feed into the toxic tg sec-mentality that plagues everyone running downstream.

Jokes on you, adding mindshield to detective was a tg change

**Comment by Wilchenx** [comment]
> > I want to shake things up and I think this is a great way to do it. Make security actually use and look into evidence.
> 
> Bro go full send and remove metashielding from anyone but heads of staff and warden.
> 
> Only reason heads of staff are metashielded is because they can wind up with very easy objectives(steal a piece of equipment from own department, etc.).
> 
> Warden because he's basically HoS the 2th.

Yeah I agree we should follow the way of /vg/ and allow sec officers to be traitors too

**Comment by Fresh839** [comment]
I heavily disagree with this PR.

The detective currently already has a very hard time getting recognized or even listened to by security.

This PR does not fix that major issue (in my opinion the biggest one the detective role currently has) but makes it even way worse.
Imagine security giving a shit about evidence brought up by someone that might be a traitor.

It basically turns the detective into some form of lawyer. 
Non antagonist detective will be a terrible experience as absolutely nobody will listen to your evidence. (Even more so than how it is already the case)
Antagonist detective might be interesting as it is someone with sec access but i don't believe you will be able to fake evidence and security acting on it in 95% of all cases.

I really don't see anything positive in this PR. And i say that as someone that has experienced multiple of their best roleplay moments as a detective.

**Comment by DerpiestBruh** [comment]
> The detective currently already has a very hard time getting recognized or even listened to by security.

but sec actually listens and interacts with det most time theres a crime scene though??

**Comment by Wilchenx** [comment]
> I heavily disagree with this PR.
> 
> The detective currently already has a very hard time getting recognized or even listened to by security.

And how do you propose to fix that codewise? 

> This PR does not fix that major issue (in my opinion the biggest one the detective role currently has) but makes it even way worse. Imagine security giving a shit about evidence brought up by someone that might be a traitor.

If someone says "I don't trust you cause you can be a traitor" just report them for shit rp and metagaming. Which again, is not fixable codewise but by policy and rule enforcement. 

> It basically turns the detective into some form of lawyer. Non antagonist detective will be a terrible experience as absolutely nobody will listen to your evidence. (Even more so than how it is already the case) Antagonist detective might be interesting as it is someone with sec access but i don't believe you will be able to fake evidence and security acting on it in 95% of all cases.

Detective was never a security officer so I don't get what you're saying by "turning them into a lawyer", if anything this stops blandness of detective by making him more unique rather than "security officer but not really". 

> I really don't see anything positive in this PR. And i say that as someone that has experienced multiple of their best roleplay moments as a detective.

You get to shoot your gun more often.

**Comment by Fresh839** [comment]
> And how do you propose to fix that codewise?

Making the forensic scanner be harder to aquire or use. Something along the lines of that.
> If someone says "I don't trust you cause you can be a traitor" just report them for shit rp and metagaming. Which again, is not fixable codewise but by policy and rule enforcement.

It obviously won't be that obvious. Just an overall "feeling like i'm being ignored". 
And why try and bandaid something with policy and admin work when it is something that can easily be avoided by code? We definitely shouldn't offload even more work onto the admin team.

>Detective was never a security officer so I don't get what you're saying by "turning them into a lawyer", if anything this stops blandness of detective by making him more unique rather than "security officer but not really".

It won't make them more unique at all in my opinion. As the main purpose of the detective, solving crimes and mysteries will feel awful as basically nobody that actually enforces the law, will listen to them

I can be wrong of course and it might be a great addition. But personally, i really believe we don't need the detective to be even more detached from security right now. 
I'm fine with this getting added once security is actually semi dependant on the detective and the detective having an actual role to fill in the security team. But for now i really only see how this will lead to an increase in bad experiences for non antagonist detectives. Like really, i think having the detective be able to fake evidence and stuff is awesome. But i don't think we are ready for it yet codewise.

**Comment by Sinmero** [comment]
Dont we already have brig phys as a potential antag within sec?
If det is going to be antag you should remove his roundstart gun.

**Comment by Wilchenx** [comment]
> Dont we already have brig phys as a potential antag within sec? If det is going to be antag you should remove his roundstart gun.

Yeah no that would make detective really lame

**Comment by Sinmero** [comment]
> Yeah no that would make detective really lame

Det has baton, legal lethal gun, flash, sec access and sec hud glasses with ability to set people to arrest.
No antag role has free legal access to lethal guns roundstart.

If you are making it possible for det to be antag just for the sake of how strong it would be then det shouldnt be antag.

**Comment by Wilchenx** [comment]
> No antag role has free legal access to lethal guns roundstart.

Why

**Comment by AnCopper** [comment]
> Yeah no No antag role has free legal access to lethal guns roundstart.

The bartender has a shotgun, and the miners a pKA.

**Comment by Sinmero** [comment]
> The bartender has a shotgun, and the miners a pKA.

Bartender only has beanbags and needs to aquire proper ammo to shoot his gun. 
Miner pka is shit in pressuresed rooms without the mod. 
Explorer gun needs its pin changed or to be emagged to be able to shoot on the station.
All those jobs need to put some effort (or to invest some tc) to make use of their weapons. Det just gets a free one plus legal access to the sec lathe.

**Comment by Wilchenx** [comment]
> Bartender only has beanbags and needs to aquire proper ammo to shoot his gun.

Two clicks on a autolathe btw

> Det just gets a free one plus legal access to the sec lathe.

Depends on the map

**Review by Crossedfall — APPROVED** [review]
I still think this is a bad idea, but, the community voted in favor of the change.

SmartSelect_20220225-080907_Discord

**Comment by Archanial** [comment]
Epic

**Pull request merged**
