### PR TITLE
Fixes linters runtime caused by QDEL()

### PR DESCRIPTION
**Pull request by WhyIsCaeciliusTaken**
## About The Pull Request

Fixes a very boring runtime error, please don't read

## Why It's Good For The Game

Bugs bad, very boring too

## Changelog
:cl:
fix: fixed runtimes in linters, don't read file diffs
/:cl:

### CODE REVIEW

**Review by KubeRoot — CHANGES_REQUESTED** [review]
Inconsistent indentation: Line 1 has some spaces, please correct those

**Comment by Pirill** [comment]
I can't believe you've done this.

By which I mean selflessly improve the game's code in such a big way. 👍

**Comment by BrumalLake** [comment]
the most superficial title that also doesn't make any sense

**Review by mcmeiler — APPROVED** [review]

**Comment by TeomanTheGreat** [comment]
Given the spam label. Destroyed.

**Pull request closed without merging**
