### PR TITLE
Fully removes mindread from the game

### LINKED ISSUE #5619: Blood Brothers Implant showing up in Mind reading
## Round ID: 253921

Mindread bug
## Reproduction:

Was mind reading and it showed  (Blood brother implant) before one of the messages

### PR DESCRIPTION
**Pull request by Hardly3D**
## About The Pull Request
This PR fully removes mindread from the game, making it no longer available to be obtained in any way.

closes: #5619

## Why It's Good For The Game
The mutation's only good use is for finding antags as it allows you to easily out most of the antags (blood cult, lings, etc.) by simply mindreading them.

## Changelog
:cl: Hardly
del: Removed mindread mutation.
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
good removal

**Comment by mcmeiler** [comment]
based removal, mindread literally has no function beyond enabling sec (and validhunting hulked geneticists) to find the valid faster.

**Review by Archanial — APPROVED** [review]

**Comment by RDS88-beeman** [comment]
holy shit that was fast

**Comment by mcmeiler** [comment]
Finally. Still too slow.

**Pull request merged**
