### PR TITLE
adds needlessly complex finger gun emote

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request

you can *fingergun to get a finger gun to shoot people with invisible bullets that dont do anything. unless the target is a mime, in which it deals 5 damage

## Why It's Good For The Game

It's funny i guess
## Changelog
:cl:
add: fingergun emote
add: admin only lethal fingergun speedloader
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
fuck off travis you're drunk, quit it with the hourglass shit

**Comment by Crossedfall** [comment]
re-ran tests. Also see #1386 with regards to the hourglass stuff.

**Comment by ike709** [comment]
Is this tested?

**Comment by zeskorion** [comment]
> Is this tested?
of course it's bloody tested

**Comment by ike709** [comment]
I'm going to be annoyed when this has bugs.

**Pull request merged**
