### PR TITLE
[Port] Spyglasses from tg

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Nice little item.

## Why It's Good For The Game

Plan on adding them in maints and det office. I like this item, it's sneaky.

## Changelog
:cl:
add: spyglasses
/:cl:

### CODE REVIEW

**Comment by Firefox13** [comment]
Give a link to /tg/ PR

**Comment by ghost** [comment]
Spyglasses are useless garbage No one uses

**Comment by That0nePerson** [comment]
What do they even do? There's a reason the pr prompt asks for a good description

**Comment by eeSPee** [comment]
What are you guys talking about?

You know that little pocket protector that comes with them? The glasses open up a popup window with a camera that always shows you a 3x3 tile view of that item.

**Review by Crossedfall — CHANGES_REQUESTED** [review]
The original author(s) needs to be credited before this can even be considered.

At the very least, you should be linking to the PRs you are porting from.

**Comment by PowerfulBacon** [comment]
Closing due to inactivity. Feel free to reopen when you make changes to what Crossedfall requested.

**Pull request closed without merging**
