### PR TITLE
Reverts #1087: Autophagocytosis Zombie Threshold

### PR DESCRIPTION
**Pull request by DatBoiTim**
## About The Pull Request
Reverts #1087

Listen, this wasn't and never has been remotely "secret". This is a way to avoiding the romerol tax, which exists for a reason. 
Doubly so since zombies can really derail a round when combined with a necrotic metabolism trifecta, making them harder to kill.

## Why It's Good For The Game
Listen, there is a reason why Romerol costs 25 TC. Making this possible sans uplink is a little silly.

I love virology(and tax evasion) as much as some of y'all. But man, there's just a few things that are just straight up wacky and uncharacteristic. Also I am working to get some more interesting new symptoms for virology, to counteract this one unfortunate outlier.

## Changelog
:cl: DatBoiTim
del: Reverts #1087
del: Removed Autophagocytosis Necrosis Zombie Threshold.
del: Removes most of the other Zombie Related Stuff from Zesko's PRs for this symptom
/:cl:

### CODE REVIEW

**Comment by DatBoiTim** [comment]
Linter Moment

**Comment by leestriter** [comment]
I mean, to be, if you are a viro with hijack (the only time you are allowed to use this) a discount on general is fine since the other specific stuff for you as a traitor isnt great. More fun then any other death plague as people stay in the round. Would be sad to see viro lose this. If it was paired with a replacement. But this is just a removal where you say maybe you'll add something new later. I have never seen this mechanic abused and almost never seen it used. Maybe rebalance so the bite isn't contagious, it has to spread like a normal virus? That'd nerf it heavily but be better then just removing it.

**Comment by leestriter** [comment]
I have never seen this mechanic abused and almost never seen it used.

**Comment by leestriter** [comment]
Maybe rebalance so the bite isn't contagious, it has to spread like a normal virus? That'd need it heavily but be better then removing it.

**Comment by DatBoiTim** [comment]
> Maybe rebalance so the bite isn't contagious, it has to spread like a normal virus? That'd need it heavily but be better then removing it.

This, I am not opposed to. However, this should likely be a separate PR, between the fact that Redirecting a PR can be annoying for both readers and coders. I may see discuss this perhaps a bit further. I can't promise that I will close or redirect this PR. But non-contagious zombies will be added to my code radar.

**Comment by WhyIsCaeciliusTaken** [comment]
Zesko otw (on their way) to add antagonist gear to their main job whilst removing it from all other jobs.

It's good that this was finally fixed.

**Comment by eeSPee** [comment]
Emag disease when?

**Comment by leestriter** [comment]
Another good rebalance compared to removal, let viro pay 20 to for romeral instead of 25.

**Comment by utilbird** [comment]
Isn't this extremely hard to do? Imo there's nothing wrong with _virology_ having a (difficult) way to circumvent TC cost for people dedicated enough to try it. The only issue I can see is it's possible for non-antags to produce it, but that's an administrative problem.

**Comment by DatBoiTim** [comment]
> Isn't this extremely hard to do? Imo there's nothing wrong with _virology_ having a (difficult) way to circumvent TC cost for people dedicated enough to try it. The only issue I can see is it's possible for non-antags to produce it, but that's an administrative problem.

Not actually sure about difficulty. I can get a set of answers eventually, about how many different combinations can work.

**Comment by utilbird** [comment]
You need a stealth rate of 2+ and a stage rate 12+

Not exactly _easy_ but I don't have enough viro playtime to make an accurate judgement

**Comment by DatBoiTim** [comment]
> You need a stealth rate of 2+ and a stage rate 12+
> 
> 
> 
> Not exactly easy

So with Eternal Youth+Facial Hypertrichosis you get to Stealth 2 and SS 8. Neither of these are exceedingly rare symptoms.

Add vitiligo, you get up to stealth 4, SS 11. Add Itching, Alopecia, or even necrotic metabolism and boom you're over the thresholds by a decent amount with extra room for a final symptom.

Also, that list isn't all encompassing, and is looking at the most optimal in regards to meeting those thresholds. Ignoring desires for transmission or resistance. Nonetheless it is still incredibly easy, so long as you know what you need to meet it.

None of those are above level 6, so you could realistically get those with some RNG with virochem that you start with in the lab.

If you're worth your salt, you'll have more than enough viro chems to back up on.

**Comment by utilbird** [comment]
It's pretty specific compared to every other late stage viro symptom. That's a monumental effort compared to just saying codewords and buying romerol. 
Sure, worst case scenario you have to spend all of your TC because they won't go halvies, but you don't really need any other gear if you're going for zombies anyway as it's clear winning is not your top priority.

**Comment by leestriter** [comment]
> > You need a stealth rate of 2+ and a stage rate 12+
> > Not exactly easy
> 
> So with Eternal Youth+Facial Hypertrichosis you get to Stealth 2 and SS 8. Neither of these are exceedingly rare symptoms.
> 
> Add vitiligo, you get up to stealth 4, SS 11. Add Itching, Alopecia, or even necrotic metabolism and boom you're over the thresholds by a decent amount with extra room for a final symptom.
> 
> Also, that list isn't all encompassing, and is looking at the most optimal in regards to meeting those thresholds. Ignoring desires for transmission or resistance. Nonetheless it is still incredibly easy, so long as you know what you need to meet it.
> 
> None of those are above level 6, so you could realistically get those with some RNG with virochem that you start with in the lab.
> 
> If you're worth your salt, you'll have more than enough viro chems to back up on.

Auto necro itself is level 9, so you probably only get it if you get money to order cargo crates.

**Comment by DatBoiTim** [comment]
> It's pretty specific compared to every other late stage viro symptom. That's a monumental effort compared to just saying codewords and buying romerol. 
> 
> Sure, worst case scenario you have to spend all of your TC because they won't go halvies, but you don't really need any other gear if you're going for zombies anyway as it's clear winning is not your top priority.

Well of course it's specific it was meant to be "a secret".

But so long as you find auto phagocytosis necrosis, you can fairly repeatedly make this disease, with little if any cooperation to make your own batch of romerol zombies. Which, by the way, will also be infinite until it's unleashed(and even then, that assumes you die or have power cut).

**Comment by utilbird** [comment]
The time/effort it'd take to make that, unless you're extremely lucky, is just not worth saving your TC which will have little relevance during a zombie outbreak. Viro zombies are more of a goof thing for autism traitors, while removing isn't likely to be detrimental to anyone's experience, it's addressing a problem that doesn't exist. Although, this is under the belief that it takes a while to make though, if that's not the case then the requirements should definitely be adjusted.

I'll admit from a quick glance romerol virology looks like a bad, if not terrible idea. But when you think about what actually has to happen compared to the alternative of buying it 5-10 minutes in the round, it turns into a gimmick. Fusion is a good example, it takes a while to make, you can use it to kill the entire station BUT you will probably die as a result.

That's my 2 cents.

**Comment by leestriter** [comment]
" Which, by the way, will also be infinite until it's unleashed(and even then, that assumes you die or have power cut)." 

What does this mean? And I agree the symptom is kinda OP, but its fun. I have made suggestions on balancing it which I think are far better then just removing it, as this allows a viro to kill people without taking them out of the round. And once again, the only time a viro is allowed to use autophage is if they have hijack, and being a viro with hijack is gonna be rare as fuck. And then how often will that viro make zombies? No one is abusing this mechanic, which means it can't be that OP like the mechanics they are abusing in other departments.

**Comment by DatBoiTim** [comment]
> " Which, by the way, will also be infinite until it's unleashed(and even then, that assumes you die or have power cut)." 
> 
> 
> 
> What does this mean? And I agree the symptom is kinda OP, but its fun. I have made suggestions on balancing it which I think are far better then just removing it, as this allows a viro to kill people without taking them out of the round. And once again, the only time a viro is allowed to use autophage is if they have hijack, and being a viro with hijack is gonna be rare as fuck. And then how often will that viro make zombies? No one is abusing this mechanic, which means it can't be that OP like the mechanics they are abusing in other departments.
> 
> 

Once you have a disease which meets thresholds you can just print an infinite amount of culture bottles.

**Comment by leestriter** [comment]
Like, a traitor xenobio can make those fucking self breeding spiders, and botany has kudzu, both of which are more OP. As for infinite amount of culture bottles, having a ton of bottles doesn't help, try to give someone a virus and 9 times out of ten they will refuse or lynch you whether you have 1 bottle or 100.

**Comment by leestriter** [comment]
Cause the thing about it being stealth 2 and stage speed 12 required, it is not possible to make a contagious version of the disease, it only spreads through zombie bites or viro giving it to people. So, the viro depends on the first zombie doing a good job, or the crew just letting the viro infect them and not lynching the viro before they turn.

**Comment by DatBoiTim** [comment]
> Like, a traitor xenobio can make those fucking self breeding spiders, and botany has kudzu, both of which are more OP. As for infinite amount of culture bottles, having a ton of bottles doesn't help, try to give someone a virus and 9 times out of ten they will refuse or lynch you whether you have 1 bottle or 100.

Yes but virology also can just make a regular disease. The spiders and kudzu aren't versions of Antag unique items.
Also in this case you're gonna get lynched anyways so just load some syringes and put them into a syringe gun.

**Comment by leestriter** [comment]
Also, if you just put people infected with the disease out them  on stasis beds, you can keep them stable and go make the disease cure. Unlike romeral, you can make a vaccine for autophage zombies and they are fucked. How high can the resistance on the disease end up? The cure is normally easy to make.

**Comment by leestriter** [comment]
> > Like, a traitor xenobio can make those fucking self breeding spiders, and botany has kudzu, both of which are more OP. As for infinite amount of culture bottles, having a ton of bottles doesn't help, try to give someone a virus and 9 times out of ten they will refuse or lynch you whether you have 1 bottle or 100.
> 
> Yes but virology also can just make a regular disease. The spiders and kudzu aren't versions of Antag unique items.
> Also in this case you're gonna get lynched anyways so just load some syringes and put them into a syringe gun.

Not being version of antag unique items makes them even less balanced, not more. If kudzu was an antag item, how much TC would it be worth?

**Comment by DatBoiTim** [comment]
> > > Like, a traitor xenobio can make those fucking self breeding spiders, and botany has kudzu, both of which are more OP. As for infinite amount of culture bottles, having a ton of bottles doesn't help, try to give someone a virus and 9 times out of ten they will refuse or lynch you whether you have 1 bottle or 100.
> 
> > 
> 
> > Yes but virology also can just make a regular disease. The spiders and kudzu aren't versions of Antag unique items.
> 
> > Also in this case you're gonna get lynched anyways so just load some syringes and put them into a syringe gun.
> 
> 
> 
> Not being version of antag unique items makes them even less balanced, not more. If kudzu was an antag item, how much TC would it be worth?

Okay but here's the difference. Those things, like other kill diseases, exist in the job as is.

Viro can not only make kill diseases but gets no TC romerol. But that isn't even my actual issue.

The issue here is that Romerol shouldn't be available as a consistently creatable thing with no uplink.

**Comment by DatBoiTim** [comment]
> Also, if you just put people infected with the disease out them  on stasis beds, you can keep them stable and go make the disease cure. Unlike romeral, you can make a vaccine for autophage zombies and they are fucked. How high can the resistance on the disease end up? The cure is normally easy to make.

You can easily overwhelm this with a bunch of syringes and a syringe gun. Which again, the disease is already getting you lynched, so you'd have no qualms just syringe gunning people randomly

**Comment by leestriter** [comment]
> > > > Like, a traitor xenobio can make those fucking self breeding spiders, and botany has kudzu, both of which are more OP. As for infinite amount of culture bottles, having a ton of bottles doesn't help, try to give someone a virus and 9 times out of ten they will refuse or lynch you whether you have 1 bottle or 100.
> > 
> > 
> > > 
> > 
> > 
> > > Yes but virology also can just make a regular disease. The spiders and kudzu aren't versions of Antag unique items.
> > 
> > 
> > > Also in this case you're gonna get lynched anyways so just load some syringes and put them into a syringe gun.
> > 
> > 
> > Not being version of antag unique items makes them even less balanced, not more. If kudzu was an antag item, how much TC would it be worth?
> 
> Okay but here's the difference. Those things, like other kill diseases, exist in the job as is.
> 
> Viro can not only make kill diseases but gets no TC romerol. But that isn't even my actual issue.
> 
> The issue here is that Romerol shouldn't be available as a consistently creatable thing with no uplink.

I mean, autophage zombie exist in viro as is. It doesn't answer about all the things of similar power level you can make without an uplink already in other jobs or even in viro, it only goes after autophage zombies for having a equivalent antag item, which isn't really a great reason. Honestly, it would make more sense to remove romeral and keep autophage.

**Comment by utilbird** [comment]
I personally believe that removing features for the sole reason of them being strong is bad for the game's health. Strong things can still be enjoyable for both ends **as long as it's not abused**. Plasma floods, fusion floods, chem bombcores and mass ttv bombings are all fun _in moderation_. Once devastating events become consistent it quickly becomes a negative experience for almost everyone involved. 

Back to my point, if players start abusing mechanics/features, the best approach is to reduce the capacity or availability for abuse rather than nerfing or outright removing the feature itself. As far as I can see, viro romerol zombies are not common enough to warrant removing it. As long as it's difficult to obtain there should be no problem with keeping it in the game.


On a side rant. Unfortunately we're an AGPL codebase so we can't have truly secret content like goonstation/clover, which was a very natural way of limiting mechanic abuse. We just have to wait and <strike>hope</strike> see whether or not people abuse stuff. 
Ultimately the responsibility lies with the player and whether or not they choose to intentionally abuse mechanics.

**Comment by DatBoiTim** [comment]
> I personally believe that removing features for the sole reason of them being strong is bad for the game's health. Strong things can still be enjoyable for both ends **as long as it's not abused**. Plasma floods, fusion floods, chem bombcores and mass ttv bombings are all fun _in moderation_. Once devastating events become consistent it quickly becomes a negative experience for almost everyone involved. 
> 
> 
> 
> Back to my point, if players start abusing mechanics/features, the best approach is to reduce the capacity or availability for abuse rather than nerfing or outright removing the feature itself. As far as I can see, viro romerol zombies are not common enough to warrant removing it. As long as it's difficult to obtain there should be no problem with keeping it in the game.
> 
> 
> 
> 
> 
> On a side rant. Unfortunately we're an AGPL codebase so we can't have truly secret content like goonstation/clover, which was a very natural way of limiting mechanic abuse. We just have to wait and <strike>hope</strike> see whether or not people abuse stuff. 
> 
> Ultimately the responsibility lies with the player and whether or not they choose to intentionally abuse mechanics.

The point here isn't that it's strong, it's that romerol was made to require cooperation to bring into the round for a reason. Adding a workaround makes that design idea into a complete joke.

However, claiming that this is weaker or otherwise less feasible than romerol is really missing the Mark.

**Comment by leestriter** [comment]
You call it a work around, I call it the person whose job it is to make diseases should be the one, infact the only one, making a zombie disease. Referencing previous balance decisions doesn't answer anyone's questions or concerns. Yes, they decided to make romerol 25 TC. Non viros should have to work together for something like that. But, it makes roleplay sense for a traitor viro to have access to romeral more then it does for 2 traitors that teamed up. 

How does the fact that it is weaker then romeral miss the mark? It is true. Romeral doesn't take up one of the three virus slots, requires surgery to cure, can't be vaccinated against, can be used by a traitor on themselves without dying, doesn't require buying a ton of crates from cargo, it has a large number of advantages over autophage zombies and you are being dishonest if you say otherwise.

**Comment by leestriter** [comment]
Also, your only argument seems to be "Romeral is 25 TC". Like, that's not word of god. They decided to make it 25 TC. That doesn't mean it intrinsically deserves to be 25 TC, and I don't feel it is justification in and of itself.

Toxins can make bombs as big or bigger then syndicate bombs, so can chem. That lets them avoid paying TC. Why not remove those?

And xenobio has so many crazy things they can copy that are normally traitor only I can't even list them all.

I'd like to see this put to vote, but I know it won't be. Someone will end up coming and speed merging this soon, because the big trend right now is nerfs and removals.

**Comment by DatBoiTim** [comment]
> You call it a work around, I call it the person whose job it is to make diseases should be the one, infact the only one, making a zombie disease. Referencing previous balance decisions doesn't answer anyone's questions or concerns. Yes, they decided to make romerol 25 TC. Non viros should have to work together for something like that. But, it makes roleplay sense for a traitor viro to have access to romeral more then it does for 2 traitors that teamed up. 
> 
> 
> 
> How does the fact that it is weaker then romeral miss the mark? It is true. Romeral doesn't take up one of the three virus slots, requires surgery to cure, can't be vaccinated against, can be used by a traitor on themselves without dying, doesn't require buying a ton of crates from cargo, it has a large number of advantages over autophage zombies and you are being dishonest if you say otherwise.

But here's the thing, viro has access to diseases as a whole, much like xenobio spiders, kudzu, etc. There's a difference between that and whoop hey this department has access indirectly to traitor items.

**Comment by leestriter** [comment]
> > You call it a work around, I call it the person whose job it is to make diseases should be the one, infact the only one, making a zombie disease. Referencing previous balance decisions doesn't answer anyone's questions or concerns. Yes, they decided to make romerol 25 TC. Non viros should have to work together for something like that. But, it makes roleplay sense for a traitor viro to have access to romeral more then it does for 2 traitors that teamed up.
> > How does the fact that it is weaker then romeral miss the mark? It is true. Romeral doesn't take up one of the three virus slots, requires surgery to cure, can't be vaccinated against, can be used by a traitor on themselves without dying, doesn't require buying a ton of crates from cargo, it has a large number of advantages over autophage zombies and you are being dishonest if you say otherwise.
> 
> But here's the thing, viro has access to diseases as a whole, much like xenobio spiders, kudzu, etc. There's a difference between that and whoop hey this department has access indirectly to traitor items.

But this is a case where the traitor item is a disease. They have access to it because it is a disease. I don't see what the difference is between this and a toxin bomb, kudzu, etc. Like what is the difference. The truth is lots of departments do have indirect access to traitor items (and items as strong as traitor items that traitors can't buy). I feel like we are just repeating the same shit back and forth. I don't feel you've answered any of my questions and concerns. The FakeElon summed it up far better then I will so I'll leave it at this unless you say something other then "Romeral is a traitor item".

**Comment by DatBoiTim** [comment]
> > > You call it a work around, I call it the person whose job it is to make diseases should be the one, infact the only one, making a zombie disease. Referencing previous balance decisions doesn't answer anyone's questions or concerns. Yes, they decided to make romerol 25 TC. Non viros should have to work together for something like that. But, it makes roleplay sense for a traitor viro to have access to romeral more then it does for 2 traitors that teamed up.
> 
> > > How does the fact that it is weaker then romeral miss the mark? It is true. Romeral doesn't take up one of the three virus slots, requires surgery to cure, can't be vaccinated against, can be used by a traitor on themselves without dying, doesn't require buying a ton of crates from cargo, it has a large number of advantages over autophage zombies and you are being dishonest if you say otherwise.
> 
> > 
> 
> > But here's the thing, viro has access to diseases as a whole, much like xenobio spiders, kudzu, etc. There's a difference between that and whoop hey this department has access indirectly to traitor items.
> 
> 
> 
> But this is a case where the traitor item is a disease. They have access to it because it is a disease. I don't see what the difference is between this and a toxin bomb, kudzu, etc. Like what is the difference. The truth is lots of departments do have indirect access to traitor items (and items as strong as traitor items that traitors can't buy). I feel like we are just repeating the same shit back and forth. I don't feel you've answered any of my questions and concerns. The FakeElon summed it up far better then I will so I'll leave it at this unless you say something other then "Romeral is a traitor item".

Here's let's strip this away. Pretend this isn't about romerol. Say there's an item which to use, requires two people. Then, there's a job that can ignore the need for two people with some RNG and time. This item is secondary to that roles niche, and the niche doesn't hinge on nor culminate with this item.

The existence of the item and its cooperation mechanism also predates the ability to bypass cooperation, and the cooperation still exists after the bypass was added.

Creating a workaround to skip cooperation is the issue here.

This is what I am addressing, and in this case, this isn't a core feature of virology. I am not removing a symptom wholesale, nor am I removing a key feature. I am adding consistency regarding design around a niche aspect game, that got a little fucky with this getting added to the role.

**Comment by MNarath1** [comment]
You could also like actually make the threshold random so you cannot codedive it.

**Comment by MNarath1** [comment]
Like only thing you gotta do for that make a roundstart initial that chooses a threshold type and number on random for said round

**Comment by zeskorion** [comment]
10 bucks says this happened after a zombie round killed the coder

Virologists do not often make this disease in my experience. It isnt common to see in a day,  and players tend to enjoy zombie rounds.

**Comment by DatBoiTim** [comment]
> 10 bucks says this happened after a zombie round killed the coder
> 
> 
> 
> Virologists do not often make this disease in my experience. It isnt common to see in a day,  and players tend to enjoy zombie rounds. 

Lmao this happened after a discussion with Fran. Now hand over the tenner.

**Comment by zeskorion** [comment]
> > 10 bucks says this happened after a zombie round killed the coder
> > Virologists do not often make this disease in my experience. It isnt common to see in a day,  and players tend to enjoy zombie rounds.
> 
> Lmao this happened after a discussion with Fran. Now hand over the tenner.

that was my second guess, fran hates my viro shit lol

here's the thing: zombies are the only "fun" antagonistic virus virology can do, that wont ruin the experience for other players- other than that, it's either giant hindrances that make everyone mad, or killing everyone, which makes them less mad cuz the round ends sooner. Zombies are something that can actually be fought off, and keep dead players in the game

**Comment by KazooBard** [comment]
That counts as murderbone so you can't do that without hijack. I rest my case...

**Comment by utilbird** [comment]
:key:

**Comment by ItsTisme** [comment]
Id like to add my 2 cent on the whole "zombies are traitor item"

Many traitor items can be jerry rigged together as a non antag. You can make EMP/pyro/viral grenades. TTV's and chem bombs can act as syndie bombs(hell you can make a identical bomb frame with plasteel) and obvs cases like mag boots and suspicius toolbox.

The uplink items arent ment to just be exclusive, they are tools that are very _convenient_ to get. If you dont wana spend the effort to get something you can spend the TC to leverage yourself. Every item aside of like emag's could be roughly ghetto'ed by non traitors. Thats just how it is

**Comment by DatBoiTim** [comment]
> Many traitor items can be jerry rigged together as a non antag. You can make EMP/pyro/viral grenades. TTV's and chem bombs can act as syndie bombs(hell you can make a identical bomb frame with plasteel) and obvs cases like mag boots and suspicius toolbox.

The issue isn't getting a traitor item, it's getting an item solo when it normally requires cooperation.

To reference your comment, Syndie bombs can be bought without a second person needed. Same for boots and toolbox.

Zombies themselves aren't the issue. It's that zombies require cooperation, and this does not.

**Comment by utilbird** [comment]
This has been inactive for almost a month so I'll close it. If any other maintainer likes this PR enough/wishes to continue discussion, feel free to re-open.

**Pull request closed without merging**
