### PR TITLE
Newfood atomization: Dough & Mexican food

### PR DESCRIPTION
**Pull request by Tsar-Salat**
Ports:
- https://github.com/tgstation/tgstation/pull/55039

## About The Pull Request

Converts Dough to newfood. 

Splits mexican food off of meats and misc food, into its own category and converts it to newfood. Adds a crafting category for it

Makes flour and rice bags start full

## Why It's Good For The Game
newfood atomization

Regarding the balance change, nearly all condiment containers can fit 50u, yet for some reason the flour and rice containers only start with 30u? Why would fresh Flour out of a biogenerator dispense a bag... and only enough to fill half of it? 
Consistency change and something that has irked me for 2 years.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/438512cd-4d11-4540-8ec2-69f7aff42215

</details>

## Changelog
:cl: RKz, Fikou
balance: Nanotrasen's Agricultural & Weapons division has fixed an error in the biogenerator and station-stocking machinery. All rice and flour bags will start full, rather than strangely half-empty!
add: Converts dough to newfood
add: Splits mexican food off of meats and misc food, into its own category and converts it to newfood.
add: mexican food is now its own category in the crafting menu
code: split mexican.dmi off food.dmi
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
fuck, it made the duplication bug worse

**Comment by Tsar-Salat** [comment]
Im doing everything that isnt microwaved first

**Comment by BriggsIDP** [comment]
😥

**Comment by Tsar-Salat** [comment]
I live, I die, I live again!

**Review by itsmeow — CHANGES_REQUESTED** [review]
Add this to the UpdatePaths. You can probably just make one for all of newfood.

**Comment by Tsar-Salat** [comment]
> Add this to the UpdatePaths. You can probably just make one for all of newfood.

765c14f

**Review by itsmeow — APPROVED** [review]

**Comment by Tsar-Salat** [comment]
Brugh

**Review by Rukofamicom — APPROVED** [review]

**Pull request merged**
