### PR TITLE
slimepeople now take damage from zombie tumors

### PR DESCRIPTION
**Pull request by AgentCitrus**
## About The Pull Request

does what it says in the title

## Why It's Good For The Game

slimepeople shouldn't be immune to, let alone heal from a syndicate zombie bioweapon

## Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

https://user-images.githubusercontent.com/35978630/189461324-c1e2ad07-e4a9-46ce-aed1-e7ab3670e033.mp4

</details>

## Changelog
:cl:
balance: slimepeople (including oozelings, jellypeople, etc) are no longer immune to/heal from zombie tumors
/:cl:

### CODE REVIEW

**Review by PowerfulBacon — APPROVED** [review]

**Comment by kit-katz** [comment]
i get it for slimepeople who have no downsides.
But oozelings are banalced around 2 good traits at the cost of many weaknesses
... why remove a property form one of said traits considering they "pay" by being weaker just for it

**Comment by PowerfulBacon** [comment]
In this case, the zombie tumor > oozelings and should damage everyone since it needs to kill in order to function.

**Comment by kit-katz** [comment]
change the way it hurts then. as the current way is even harsher than to humans. a concept literaly counter to what oozeling gameplay promises
toxins cause bloodloss and once an oozeling dies it is harder to recover it since they loose a lot more. and there's only 1 bag and the avarage ooze population is 1-3... and defibs burn blood. also visiting medical is inherently riskier... one of the mentioned balancing downsides. even if they remove the tumor... you are gonna stay in medical for much longer than the avarage person... it is the toxinlover trait gameplay... *you are harder to poison but god help you if you do*

**Comment by EvilDragonfiend** [comment]
romerol spawns non-damaging zombie tumor. I don't think it really changes.

**Comment by LemonLimeSoda** [comment]
added testing evidence

**Comment by EvilDragonfiend** [comment]
ah, it's not injecting romerol. it is spawning zombie tumor(from removed virology) version than romerol tumor version.

**Pull request merged**
