### PR TITLE
The return of flypeople 

### PR DESCRIPTION
**Pull request by Jesusaholy1**
This just makes flypeople available at roundstart again.

## About The Pull Request

This basically allows for flypeople to be a selectable race at roundstart once more. Nothing else was changed.

## Why It's Good For The Game

Stemming from the thought that more is more and that it actually had a decent amount of players that used it, I see no reason not to allow a playable race that brings no drawbacks to gameplay whatsoever and whose reintroduction would not interfere with the addition of apids.

## Changelog
:cl:       FleshGordo
config: Made Flypeople a roundstart race once more
/:cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
The proposed changes would only affect our LRP server Golden. Was this your intention? If not, be sure to also edit the config within the [Sage](https://github.com/BeeStation/BeeStation-Hornet/tree/master/config/Sage) config directory.

**Comment by Jesusaholy1** [comment]
No, but thanks for the heads up. Will change it for Sage as soon as possible. I take it has been approved then?

Em 19 de jun de 2020, à(s) 06:14, Crossedfall <notifications@github.com> escreveu:

**Comment by Crossedfall** [comment]
Yeah why not. Apids are a fly replacement, but I suppose there isn't much harm in having them both running around.

**Comment by Jesusaholy1** [comment]
Just created another pull request for sage and currently awaiting for your
effective approval. Thanks mate.

Crossedfall <notifications@github.com> escreveu no dia sexta, 19/06/2020
à(s) 15:10:

**Comment by Crossedfall** [comment]
Just update this pull request. I'm not going to merge two different ones for the same change. 🤔

**Comment by Jesusaholy1** [comment]
Should be done now

**Review by Crossedfall — APPROVED** [review]

**Pull request merged**
