### PR TITLE
[BOUNTY] New level 9 symptom

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request

Adds a new simplemob, a really angry heart

Adds a new level 9 symptom, Heart disease. The slowest to kill level 9 symptom yet, but also quite hard to come back from. 

More in depth:
Heart disease has -6 stage speed and a .5% chance, per tick, at stage 5, of causing a heart attack. Unless the stealth 2 threshold is met, this disease is incredibly noticeable as well, and does not debilitate the player until they reach this threshold, making a disease with this symptom easier to counteract if noticed

## Why It's Good For The Game

More variety for virology i guess. raises the level 9 list to 6 so far

## Changelog
:cl:
add: Heart Disease symptom
add: angry heart simplemob

/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
gave up on necroseed for now, cuz, like, fuck. ill look at it later, but i just wanna get beeviro done

**Comment by Sparrowbird611** [comment]
Says he won't keep adding stuff to virology for at least a week.

A day later.

**Comment by zeskorion** [comment]
> Says he won't keep adding stuff to virology for at least a week.
> 
> A day later.

that was at least a week ago innit?

As in, i submitted the readding VAM pr a week ago

**Comment by Sparrowbird611** [comment]
Shadup, I don't remember, don't ruin my memes.

**Comment by qwertyquerty** [comment]
This done?

**Comment by zeskorion** [comment]
> This done?

totally done, tested and works perfectly. Only changes that may need to be made are if it proves to be in some way unbalanced, but it seemed to be a decent sidegrade to ARDS when i tested it

**Pull request merged**
