### PR TITLE
Meteor storm inbound

### PR DESCRIPTION
**Pull request by PowerfulBacon**
## About The Pull Request

Non-admin meteor storms will now last for 15 minutes.
The first 5 minutes there will be no warning as to the incomming meteors, then the meteors will be announced and there will be a 10 minute delay before impact.
Meteors are now an orbital object, meaning they appear on orbital maps.
Meteor objects on the map can collide with orbital bodies and shuttles, if you want to save the station you can fly your shuttle into the meteor storm and take the hits. Additionally, meteors may impact lavaland if coming from the opposite side of the station.

There is an awesome effect for falling meteors.

https://user-images.githubusercontent.com/26465327/131897689-b861ba70-f9e2-4f16-a9bb-8a53c922bcd8.mp4

https://user-images.githubusercontent.com/26465327/131899302-acb5ac94-7c9d-416a-a5ca-80d70c98b634.mp4

## Why It's Good For The Game

More stuff on orbital maps, see the meteors coming if you are observant and you can ram your shuttle into them as a noble sacrafice (being a dumbass).

## Changelog
:cl:
refactor: Refactors meteors, they are now orbital map components and will fly towards the station, colliding with orbital bodies and flying shuttles.
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
The use of falling or side-on style meteors should probably be a ztrait, as it doesn't make sense on stations and barely makes sense on shuttles.

**Comment by ike709** [comment]
Incredibly based.

I do agree with fran though, shuttles should use the side-on if you're flying into them.

**Comment by PowerfulBacon** [comment]
They are falling on shuttles and lavaland, not on the station and other space levels.

Shuttles are hard to use the side on due to the hyperspaced and only taking up a small portion of the reserved z-level.

**Comment by williamcll** [comment]
But Can station shields intercept this?
Can I put shields on ships?

**Comment by PowerfulBacon** [comment]
> 
> 
> But Can station shields intercept this?
> Can I put shields on ships?

Yes

**Comment by PowerfulBacon** [comment]
> 
> 
> But Can station shields intercept this?
> Can I put shields on ships?

Nevermind, you can't because they can't be deployed in non space tiles

**Comment by ItsTisme** [comment]
dont meteors target players? you could have the meteor fire at where ever the player is maby.

Another alternative is if it gets deleted by a method that isant a impact, it will remain in the system as if nothing was done in the first lpace

**Comment by PowerfulBacon** [comment]
> 
> 
> dont meteors target players? you could have the meteor fire at where ever the player is maby.
> 
> Another alternative is if it gets deleted by a method that isant a impact, it will remain in the system as if nothing was done in the first lpace

No, they fly from a random point on the edge of the z-level to another

**Comment by PowerfulBacon** [comment]
> Another alternative is if it gets deleted by a method that isant a impact, it will remain in the system as if nothing was done in the first lpace

It can get shot down by meteor shields, its just that meteor shields only work on space tiles.

**Comment by ike709** [comment]
is this mergeable

**Comment by PowerfulBacon** [comment]
Should be yea, I'm currently working on improving collision detection and optimising the orbital map but this should work in the current state. Every now and then a meteor might skip past the station if its going fast enough but that should be a rare occurance.

**Pull request merged**
