### PR TITLE
Fixes size powergaming #48913

### PR DESCRIPTION
**Pull request by Cenrus**
Ports: tgstation/tgstation#48913

I introduced this unwittingly so, here's the fix that I forgot about

:cl: ATHATH
fix: Prevented anomalies around mob resizing with growth serum and red queen drink
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
Tested?

**Comment by Sinestia** [comment]
I wanted to mention that this won't fix the clown shoes letting people become absurdly tiny thing
but it's still good

**Comment by Cenrus** [comment]
@ike709 Double checked it for ya.

**Comment by MNarath1** [comment]
> I introduced this unwittingly so, here's the fix that I forgot about
> 
> 🆑 ATHATH
> fix: You can no longer use growth serum and a stasis bed to enter the quantum realm.
> fix: You also can no longer use the red queen drink and a stasis bed to enter the quantum realm or to become much, much larger than you're supposed to be.
> /🆑

thank god had a detective the other day of the size of like 2 pixel great fighting something like that

**Comment by park66665** [comment]
On Beecode, `on_mob_end_metabolize` is unrelated to stasis; it is only called when the reagent in question is no more, liver fails and/or you gain metabolism-related species trait via specie change.

However, at tgcode, `on_mob_end_metabolize` *is* related to stasis and this fix would've worked. I now doubt Beecode has this bug.

**Comment by Sinestia** [comment]
> On Beecode, `on_mob_end_metabolize` is unrelated to stasis; it is only called when liver fails and/or you gain metabolism-related species trait via specie change.
> 
> However, at tgcode, `on_mob_end_metabolize` _is_ related to stasis and this fix would've worked. I now doubt Beecode has this bug.

Doesn't IIRC, I was trying to port it when looking into the clown issue and gave the stasis a try and it didn't have an issue.

but it still mitigates stacking things to reach absurd sizes, i believe

**Comment by park66665** [comment]
> Doesn't IIRC, I was trying to port it when looking into the clown issue and gave the stasis a try and it didn't have an issue.

Yes, stasis bed won't cause this on Bee.

> but it still mitigates stacking things to reach absurd sizes, i believe

Well, yes, it really does: one only needs to know how one can turn liver on and off. However, if someone really tries to port `end_metabolize` call at stasis, then this fix is needed.

This PR indeed is in an awkward state. However, after thinking about your comment, I decided to merge this after fixing up the initial comment.

**Review by park66665 — APPROVED** [review]
Everything is clear. This PR is good to go.

**Pull request merged**
