### PR TITLE
Lowers volume of Riot Armor

### PR DESCRIPTION
**Pull request by Raven-Industries**
## About The Pull Request
Lowers the loudness of riot armor footsteps by about 25dB.

## Why It's Good For The Game
Why must we sound as if we are wearing a suit of pots and pans on strings? The answer: Bacon wishes us to suffer.

## Changelog
:cl:
tweak: lowers volume of riot armor footsteps
/:cl:

### CODE REVIEW

**Comment by lordScrubling** [comment]
this is such a shsitty way to do it
image
meet the `on_mob_move()` proc which you can EASILY CHANGE THE DECIBELS IN BY DEFINING A CHILD OR A VAR FOR THE DECIBELS

**Comment by jupyterkat** [comment]
I’m Dummy Thicc and the clap of my riot armor's ass cheeks keeps alerting the assistants

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
Anyone wearing riot armor 24/7 deserves annoyances. Admittedly I'd rather make them have a larger something that's not audio based.
Anyway changes requested because the way you do this is absolutely insane. There is literally a volume parameter in playsound

**Comment by AnCopper** [comment]
> Anyone wearing riot armor 24/7 deserves annoyances. Admittedly I'd rather make them have a larger something that's not audio based.
> Anyway changes requested because the way you do this is absolutely insane. There is literally a volume parameter in playsound

It annoys literally everyone, also this is an incredibly awful way to "discourage" and "annoy" people for using an item.

**Comment by PowerfulBacon** [comment]
Its cool to hear them coming. Might be an idea to lower it for the wearer.

**Comment by Raven-Industries** [comment]
> Anyone wearing riot armor 24/7 deserves annoyances. Admittedly I'd rather make them have a larger something that's not audio based.
> Anyway changes requested because the way you do this is absolutely insane. There is literally a volume parameter in playsound

Now that Beestation is, in theory at least, a solely MRP server with RP standards being enforced OOC, I don't see why the armor should be designed with "gotta make it annoying enough that they don't powergame" in mind. Also, the method I've used should be perfectly fine.
suits of clothing have a move_sound list associated with them if they make noise upon movement. in _suits.dm, that list is called upon when using playsound():
```
/obj/item/clothing/suit/proc/on_mob_move()
	SIGNAL_HANDLER
var/mob/living/carbon/human/H = loc
	if(!istype(H) || H.wear_suit != src)
		return
	if(world.time > footstep)
		playsound(src, pick(move_sound), 100, 1)
		footstep = world.time + FOOTSTEP_COOLDOWN
```
If I modify the volume parameter of the playsound(), then in the future, if anyone wants to give their new clothing item a cool new move_sound, they will need to either create a child proc to handle their specific thing, adding overhead, or revert my edits here and do the intuitive thing anyways, which is to modify the sound assets directly.

**Comment by PowerfulBacon** [comment]
I should word better and say that the part of it that is good is being able to hear them coming, hence why I suggested lowering it for the wearer.
The changes requested have nothing to do with my opinion on balance and to do with the fact that the way you did this is still absolutely insane.

**Comment by PowerfulBacon** [comment]
> If I modify the volume parameter of the playsound(), then in the future, if anyone wants to give their new clothing item a cool new move_sound, they will need to either create a child proc to handle their specific thing, adding overhead, or revert my edits here and do the intuitive thing anyways, which is to modify the sound assets directly.
 
Or just have the walk sound of everythnig be quieter, theres not a problem with it not being 100%

**Pull request closed without merging**
