### PR TITLE
Minor typo fix[wip]

### PR DESCRIPTION
**Pull request by Jeff-3**
## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by Ivniinvi** [comment]
Does this just find and replace "plasma" with "lean"?

**Comment by AnCopper** [comment]
I say we speedmerge this, doesn't matter that it's not compiling.

**Comment by imsynthex** [comment]
leancutter 💀

**Comment by Crossedfall** [comment]
Har-har

**Pull request closed without merging**
