### PR TITLE
Fix armory spelling

### LINKED ISSUE #5757: Armory is named armoury
At least it is on delta.

This should be our number 1 priority to fix

### PR DESCRIPTION
**Pull request by KubeRoot**
## About The Pull Request

Fixes https://github.com/BeeStation/BeeStation-Hornet/issues/5757

Renames all cases of "armoury" to "armory", with the exception of references to canada

<details>

<summary>nothing important here</summary>

I **DID NOT** test any of this, in case somebody decides to merge it as a joke, this touched some IDs on remote controlled devices, as well as area typepaths, and might've broken stuff through that.

</details>

## Why It's Good For The Game

Corrupting our glorious language is a crime. Our language shall remain pure, with the exception of mocking canada.

## Changelog
:cl:
fix: fixed armory spelling
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
Good pr

**Comment by DrMacCool** [comment]
Bad pr. Vowels are based.

**Review by ike709 — APPROVED** [review]
Britain stay losing

**Comment by DrMacCool** [comment]
Isn't Beestation based in Europe?

**Comment by ToasterBan** [comment]
these goudless Americans are trying tou destrouy our holy armourys 

goud save the Queen 

🇬🇧🇬🇧🇬🇧🇬🇧🇬🇧

**Comment by Kapu1178** [comment]
> 
> 
> Britain stay losing

Ike I hate to break it to you, the British/Canadian additions of "u" to many words, was actually entirely caused by the Brits in recent history. "Color", "armor", and spellings of the like, are the true British English.

**Review by Archanial — APPROVED** [review]

**Pull request merged**
