### PR TITLE
Adds a simple medkit to the uplink

### LINKED ISSUE #11670: [New Feature]: Healing Options for Syndicates
### Describe the feature request

I'd like it if there was healing options of the Syndicate though the TC shop. Even 25u synthflesh patches would be great in emergencies.

### PR DESCRIPTION
**Pull request by RDS88-beeman**
## About The Pull Request
This adds a normal-sized medkit to the traitor uplink. It contains:
-A health analyzer
-A stack of gauze
-A pill bottle each for bicaridine, kelotane, and charcoal
-Two patches of synthflesh

It currently costs 2tc, but it should probably cost more. Taking suggestions.

## Why It's Good For The Game
It gives traitors the ability to heal themselves in emergencies, and closes #11670. 

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

image
shows up in the uplink

image
image
here's the kit and the contents

</details>

## Changelog
:cl:
add: Syndicate Traitors can now purchase a medkit at the low low cost of 2 telecrystals. Contains medicine for emergency healing.
/:cl:

### CODE REVIEW

**Review by Rukofamicom — APPROVED** [review]

**Comment by MarkusLarsson421** [comment]
Could restorative nanite pills or patches be added to it? Tends to be found in Syndicate sleepers and would be fitting for this medkit.

**Comment by Rukofamicom** [comment]
Those would make this substantially more powerful than it currently is

**Comment by MarkusLarsson421** [comment]
For two TC I don't think it that much to ask for, is it?

**Comment by Rukofamicom** [comment]
We talked privately about how powerful syndicate nanites are. It absolutely is. 

image

A one-time use pen with 20u of this should be 3-5 TC by itself. This shit is STRONG.

**Comment by MarkusLarsson421** [comment]
20 units of it will result in most of it being wasted whilst already being fully healed. 

Although... "A ton of healing - this is a 50 telecrystal investment."

Never mind what I've said previously.

**Comment by TsunamiAnt** [comment]
I'd be up for an anti-tox injector like the epis or the oxy ones. That'd be pretty nice. You could replace the antitox syringes in the toxin treatment kit with it too. Would bring it more in-line with the other kits.

**Pull request merged**
