### PR TITLE
[PR RECOUP] Adds living hour requirement for antags

### PR DESCRIPTION
**Pull request by mystery3525**
## About The Pull Request

From: https://github.com/BeeStation/BeeStation-Hornet/pull/5996

> All roundstart antags now require a certain number of living hours. These have been classed into one of ~~three~~ four categories:

Intense (Wizard): 50 hours
Team-heavy (Head Revolutionary, Both Cults, Incursionist, Xenoqueen Start): 25 hours
Team-lite (BBs, Hivemind, Spiders): 15 hours
All Other Roundstart Antags: 10 hours

The logic behind this being that if you need to support others or carry others, you should be required to have more time living and not get it straight out the gate. Wizard is double because you're against the entire station.

## Why It's Good For The Game

> Nukies that don't know which end of the C20-R points away from you are kinda dumb. Especially on a server where the primary round driver is antagonists.

In addition, while not the primary purpose of this PR, this will heavily slow down the common miner antagonist ban evader (if he still is around who knows)

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Can't test on local

</details>

## Changelog
:cl: Ivniinvi, recouped by mystery3525
add: Antags now have living hour restrictions on rolling them
/:cl:

### CODE REVIEW

**Comment by ActualRory** [comment]
Good change. The antagonists who RP the least also tend the be the ones who have no idea what they're doing.
Because they're struggling to survive and panicking, they don't have the confidence to understand that they're here to make things more fun.

These requirements are pretty low, and I think this is a good change.

**Comment by mystery3525** [comment]
I lowered them from the original PR, but to quote Ivniinv:

> I deliberately put these values in as extreme. I stand by the ten hour one, but the 100 and 200 ones were meant to probably be changed. I am trying to get the highest hour count that will pass review to be the final values.
>
> However:
> An experience I've witnessed:
> Three nukies, one of them has 2000h, one has 147h and one has 189h. The 2000h one has to spend literally twenty minutes teaching the other nukies how guns and uplinks work. On arrival to the station, Mr. 147 blows himself up with a c4 and dies. Mr. 189 sets his jetpack as his internals, and dies. The 2000h player proceeds to carry the entire round with a discounted Mauler and win. Because of this 20m of explaining, there was practically nothing happening on the station for the first 25 minutes.

**Review by PowerfulBacon — CHANGES_REQUESTED** [review]
This should be a config and these numbers are far too high (although its fine for team antags being high, especially if they require high skill like cult).
Ghost spawns should all require 0.
The highest I'd go is up to 25 for the super insane ones.
The highest that the general antag hour requirement for ALL antags should be 1, so that people can't be antag on their first round (to help with griefer antag rounds) but should be able to be after that.

**Comment by PowerfulBacon** [comment]
Keep in mind that as players who have like 1000 hours, 50 seems like nothing but 50 rounds is a lot, especially for a player who might only get 1 round per day if they have work/other responsibilities.

**Comment by itsmeow** [comment]
Also consider a pro ss13 player switching servers may have better gameplay ability than your average 0hrs noob

**Comment by mystery3525** [comment]
I still think it should be 10 regular, 25 for team, and we're at an impasse.

**Comment by itsmeow** [comment]
just do 5hrs regular 10hrs team

**Pull request closed without merging**
