### PR TITLE
[READY] Code improvements and fixes to fugitive events

### PR DESCRIPTION
**Pull request by Cenrus**
Fixes a number of issues with the fugitive event. Corrected issues:

- Fugitives can spawn in space, where they die a slow and hilarious death as all the airlocks are closed to them
- The hunters never spawn on their own even after an hour of waiting.
- The capture pod is invisible

Needs a test merge as I am unable to test this alone in localhost.

Mirrored from /tg/: https://github.com/tgstation/tgstation/pull/43941/

:cl:
fix: Fugitive hunter spawning
/:cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
Since this is a single PR mirror, can you please bring the merging commit into your branch? It should be the first commit for this PR.

**Comment by Cenrus** [comment]
merged to https://github.com/Cenrus/BeeStation-Hornet

**Comment by Crossedfall** [comment]
N..No. You need to cherry-pick the merging commit (920b0e7d444ac2ca15759998d9c081c8e1d4a8fd) and resolve any conflicts. The end result will look something like this on Github

image
image

If you need help, ping me in the coding channel on our discord.

**Comment by Cenrus** [comment]
Ready

**Comment by ike709** [comment]
@Crossedfall Testmerge please.

**Comment by ike709** [comment]
@Crossedfall

**Comment by Crossedfall** [comment]
Test merged onto Golden

**Comment by Crossedfall** [comment]
Everything seemed to have worked except there wasn't a ghost prompt for the hunter shuttle. There should also be a log with a jump to link for admins when it spawns in. Removing the test merge for now.

**Comment by Cenrus** [comment]
I tested this on /TG/ and the hunter spawn prompt isn't showing there either. I saw merge this anyway because it's a definite improvement, and the event actually works correctly now.

**Comment by ike709** [comment]
Those are easy changes, just add them.

**Comment by ike709** [comment]
Stale.

**Pull request closed without merging**
