### PR TITLE
Shade creation follows dnr

### PR DESCRIPTION
**Pull request by DatBoiTim**
## About The Pull Request
If you select to DNR as a ghost you no longer get soul sharded.

## Why It's Good For The Game
Being forced into cult after death when choosing to observe is not great for player agency.

## Testing Photographs and Procedure
TBD on testing procedure. Requires multiple people for a test.

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: DatBoiTim
tweak: If you opt to DNR as a ghost, you cannot be made into a shade
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Ghosting shouldn't make you immune to cult, it should do what it does to dead bodies and dust the body, but pull a ghost from the deadchat pool

**Comment by DatBoiTim** [comment]
> Ghosting shouldn't make you immune to cult, it should do what it does to dead bodies and dust the body, but pull a ghost from the deadchat pool

Wait does ghosting also set re-entering to off?

**Comment by EvilDragonfiend** [comment]
If you want to make it one per person (or time limited), check this PR
* 6807

**Comment by DatBoiTim** [comment]
> 

No I'm not so much looking for something like that. More like seen here https://forums.beestation13.com/t/cult-shades-should-not-surpass-do-not-resusicate/18989

**Comment by EvilDragonfiend** [comment]
> > 
> 
> No I'm not so much looking for something like that. More like seen here https://forums.beestation13.com/t/cult-shades-should-not-surpass-do-not-resusicate/18989

sorry, I deleted my comment cause I noticed I was talking different lol

**Pull request closed without merging**
