### PR TITLE
Makes the Mining Base Better

### PR DESCRIPTION
**Pull request by Kerbin-Fiber**
## About The Pull Request
Changes the piping in the Mining base and makes it better

Makes the Mining base and Gulag connected. Improves the Mining base's and Gulag's Atmos, and makes the officers watching over the Gulag happier.
## Why It's Good For The Game
Mining base and Gulag should stop being fucked over by bad gases leaking into them with the improved piping. Also improves the security part of the gulag by adding it to the powergrid and atmos... and making it bigger.

## Changelog
:cl:
tweak: The mining base is now bigger! Slighty. The security room in the gulag now connects the gulag to the mining base. It also now has a window to keep watch of prisoners.
fix: Rogue gases should stop coming into the mining base and gulag.
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
Good thing we have mapdiffbot, and good thing I'm not in the gulag toilet basin! ...*wait*...

**Review by MarkSuckerberg — CHANGES_REQUESTED** [review]
image
area looks a bit funky here

image
maybe adjust the decals if ya could

other than that it's perfect

**Comment by Kerbin-Fiber** [comment]
Speedmerge when?

**Comment by ike709** [comment]
When mark signs off on it.

**Review by MarkSuckerberg — COMMENTED** [review]
Apologies I didn't review this sooner

**Pull request merged**
