### PR TITLE
Small Airlock refactor and animation time changes for specific airlocks

### PR DESCRIPTION
**Pull request by MNarath1**
## About The Pull Request

This PR replaces some magic numbers in the animation code of the airlock and implements some changes that allow different airlock speeds for specific airlocks. Said animation speed now also directly effects the actual time you can pass trough an airlock. Also there are some changes to the animation time of the hatch and the abductor airlock.
For the hatch that one already overwrote the base animation speed defined in overlays.dm so it was kinda slower then intended so hatches got a bit sped up. Abductor airlocks on the other hand got their animation speed slowed to the original intended speed before the port as it has quite a lot of moving parts and looks honestly better with that speed. https://streamable.com/xpac6p
On a sidenote turns out survival pod airlocks also where still set to the original airlock animation speed and i do not think that should change as just like the alien airlocks they look better at the original speed due to all the moving parts.

Edit: I feel the part where i say some airlocks already have custom time and then say i make them possible is a bit misleading so let me clarify.
Originally the animation time for all airlocks was 5 thus the magic number inside the animation script was also 5 but i set it during the port to 3.5 now that number would get the end time substracted from in most cases that was also 3.5 however there are exceptions for that like the mining airlocks. As those airlocks had different times then expected the resulting animation speed could differ from what was expected(like in cases where it should have returned 0 it returned -1.5). But now that this magic number is actually gone and defined in a var that also gets set in another proc for that specific airlock this difference does not really matter anymore and all the airlock animations should act as expected.

## Changelog
:cl:

refractor: replaces magic number with actual var in set_airlock_overlays
refactor: changes open_speed to be defined as the max animation time taken from all airlock parts
tweak: Changes the animation time of the hatches and the abductor airlock
tweak: animation time now directly influences how long it takes until you can pass trough the airlock

/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
the sound effect when closing not lining up kind of bugs me

**Comment by MNarath1** [comment]
> the sound effect when closing not lining up kind of bugs me

Honestly that one was kinda always off center cause of how its made the whole sound is two seconds long the animation even original was like 0.5 seconds long the final closing sound is like at the 1,3 second mark

**Comment by MNarath1** [comment]
Pardon me the whole audio file is 2 seconds long it actually ends at like 1.7 trough with the sound itself

**Comment by MNarath1** [comment]
sound

**Comment by MNarath1** [comment]
here a little comparison of the sound length the first one is the close sound the second the open sound

**Comment by MNarath1** [comment]
if you want me i can thinker a bit cause most of the sound file is a consistent sound so that should work i guess

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
