### PR TITLE
Oxygen treatment kits contain Dexalin medipens

### PR DESCRIPTION
**Pull request by Cenrus**
:cl:
add: Oxygen deprivation treatment kits now contain two dexalin medipens
imageadd: dexpen sprites
/:cl:

### CODE REVIEW

**Comment by eLeCtrOssSnake** [comment]
Ehhh, idk the idea seems ok, but I wouldn't delete epi pens from them.

**Comment by eLeCtrOssSnake** [comment]
They save from crit and I think they are necessary in every medkit

**Comment by Cenrus** [comment]
they're back in now.

**Comment by eLeCtrOssSnake** [comment]
Yeah, I think that fits more

**Review by eLeCtrOssSnake — APPROVED** [review]

**Pull request merged**
