### PR TITLE
The antimatter engine is no more

### PR DESCRIPTION
**Pull request by PestoVerde322**
## About The Pull Request

This PR just removes the Antimatter engine and all it's references due to horrid icons noone wants to bother with and being overall a scuffed system, both in power production and in how it smoothed with itself.

## Why It's Good For The Game

Dead end systems removal good, and learn to make some power in other less relayable means!

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

immagine

</details>

## Changelog
:cl:
del: The antimatter engine has been retired.
/:cl:

### CODE REVIEW

**Review by Rukofamicom — APPROVED** [review]
Can you consider doing the TEG next? 

The turbine does its job in a better and less immediately abusable way.

**Comment by PestoVerde322** [comment]
> Can you consider doing the TEG next?
> 
> The turbine does its job in a better and less immediately abusable way.

To be fair the TEG has some redeemability if we contain the whole *breaking the 1st law of thermodynamics* ordeal.

**Comment by mystery3525** [comment]
> if we contain the whole breaking the 1st law of thermodynamics ordeal

Ahelp and we'll take care of that

**Comment by PestoVerde322** [comment]
> Obligatory slippery slope warning. We saw what happened to TG going forward axe-ing actually used power generation methods. I would recommend a longer test-merge for this so we can see what happens when engineering fails and we need to call the shuttle 40 minutes into the round because there is no power.
> 
> > if we contain the whole breaking the 1st law of thermodynamics ordeal
> 
> Ahelp and we'll take care of that

it's not the thermomachine trick that only does that...

**Comment by Admiral-Gigaton** [comment]
will miss my small shuttles powered by a 3x3 monster

**Comment by PestoVerde322** [comment]
> will miss my small shuttles powered by a 3x3 monster

What if i replace it with a nautical engine instead?

**Comment by Admiral-Gigaton** [comment]
> > will miss my small shuttles powered by a 3x3 monster
> 
> What if i replace it with a nautical engine instead?

That could work, just hopefully more balanced that the AME, which was horribly unbalanced. Only so much money for power comparable to the singulo??

**Review by Archanial — APPROVED** [review]
I fully support this change.
This engine is not implemented on any map, icons are really old, code is unmaintained and mostly obsolete.

**Comment by Tsar-Salat** [comment]
Methods of making power should become more skill-based, centered upon engineering as well as tertiary methods like Botany Batteries.

This is just replacing engineering primary reason for existing. Thats to say nothing about the ancient sprites, code, explosion scaling, and how ugly it is.

Axe away.

**Pull request merged**
