### PR TITLE
Investigating List for debugging

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
Investigating List for debugging
Added a proc `investigate_list(list/L)`. If you put a list into this, it will tell what's inside.

## Why It's Good For The Game
Debugging tool is good
also, sometimes it's tedious when you can't investigate some list (especially list from TGUI).

## Testing Photographs and Procedure

image

image

## Changelog
:cl:
add: added a investigate_list() proc. This returns a text form of a list, good to investigate a list at a glance. This will be useful when you want to investigate TGUI list.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Byond has a built in proc to encode lists into json called json_encode. This is what I recommend using for debugging lists instead.
image

**Comment by EvilDragonfiend** [comment]
It looks it can't tell if a thing is a path, a datum, or a text.

**Comment by EvilDragonfiend** [comment]
image

image

--------------

image

**Comment by EvilDragonfiend** [comment]
issues of json_encode:
* It can't tell the difference between typepath and text
* It can't tell which type an atom has, but also it will return the name of an atom
* If a list is complex, we kinda need to identify the list which index has which, or how big a list is, or how many depths a list has. (although it's not actual point of the PR)

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
