### PR TITLE
Revert "Add's a reddit moment"

### PR DESCRIPTION
**Pull request by Rukofamicom**
Please for the love of god remove this abomination and the nightmares it has wrought. 
This does not belong in the game, and we should not be encouraging players to be chanting memes in rounds.

### CODE REVIEW

**Comment by mat-lap** [comment]
not wholesome 100 big chungus keanu reeve reddit gold

**Comment by eeSPee** [comment]
Yes here on beestation we are serious adults and don't engage in this activity the younglings call 'meems'.

**Comment by Mat05usz** [comment]
No, leave chungus alone!

**Comment by eeSPee** [comment]
Maybe remove all the negative moodlets and make it a regular costume

**Review by PowerfulBacon — APPROVED** [review]

**Comment by mat-lap** [comment]
chungus rights

**Pull request merged**
