### PR TITLE
Boxstation Genpop and dormitories update

### PR DESCRIPTION
**Pull request by PestoVerde322**
## About The Pull Request

This PR updates Boxstation's brig to have a better fitting brig and genpop, alongside updating dorms and AI upload.
Also there is the implementation of a radstorm shelter, which untill all genpops are updates to have it, will be just an extra room there; alongside the implementation of better icons for the secure floor.

Thanks to Ambrosia over the discord for bugchecking and also better decorations for the whole place.

## Why It's Good For The Game

Current genpop is kinda lacking, also possible future standardization good. Also better tile distinction good.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

immagine

</details>

## Changelog
:cl: Pigeonverde322, Ambrosia
add: [BoxStation] Added a (for now dumb) radiation storm shelter in brig
add: [BoxStation] Reworked the Brig and Dormitories.
imageadd: Implemented new icons for the Secure floors
/:cl:

### CODE REVIEW

**Review by BriggsIDP — APPROVED** [review]
looks good to me 👍

**Review by Penwin0 — APPROVED** [review]
No gripes and can't find anything problematic

**Comment by PestoVerde322** [comment]
*Closing this now due to a fluke in git, pass by later when it's not screwed up!*

**Review by spockye — CHANGES_REQUESTED** [review]
image

Piping error. HOS office

image

More piping errors

image

Cable errors

image

disposals error

image

Area error

image

Missing area

**Pull request merged**
