### PR TITLE
changes to knockdowns and true stuns

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request

Knockdowns no longer cause you to drop items. This doesn't change shoving or slips, however. Note that shit like bolas or pies use paralysis instead of knockdown and are unaffected
true Stuns (stuns that dont knock you down, like climbing tables or goliath tentacles) also no longer cause you to drop items

## Why It's Good For The Game

With a lot of these, especially true stuns, dropping shit just doesnt make sense- there's no reason you *can't* keep a hold on the shit in your hand whilst climbing a table. For balance reasons, however, shoving and slipping remains unchanged

## Changelog
:cl:
tweak: makes stuns and knockdowns other than shoves and slips no longer drop items by default
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
sorry for the mess of commits here, fucked up my master.. again.

**Comment by zeskorion** [comment]
yeah, gonna hafta reclone my master, closing for now

**Comment by Kerbin-Fiber** [comment]
Just create a new branch off of Upstream/master instead of relying on your master...

**Comment by eLeCtrOssSnake** [comment]
its a needed tweak

**Comment by qwertyquerty** [comment]
Looks like you screwed up your branch

**Comment by zeskorion** [comment]
> Looks like you screwed up your branch

Yeah i already recloned

**Comment by eLeCtrOssSnake** [comment]
Wait, I actually realised that we won't be able to steal batons from shitsec. No no no no. I wanna kill these bois as soon as they uncuff me to leave. PLEASE DON'T NERF!@#!

**Comment by zeskorion** [comment]
> Wait, I actually realised that we won't be able to steal batons from shitsec. No no no no. I wanna kill these bois as soon as they uncuff me to leave. PLEASE DON'T NERF!@#!

no? shoves and slips and most other common disarming methods still work. Read the pr text again

**Comment by Crossedfall** [comment]
Re-open when you have your commits figured out. The fact that it's no longer attached to a branch breaks this PR.

**Pull request closed without merging**
