### PR TITLE
Locks felinids behind paywall

### PR DESCRIPTION
**Pull request by qwertyquerty**
# About The Pull Request

You now need to be a donor to create a felinid species character. Previously existing felinid characters will continue to exist.

Followup: https://github.com/BeeStation/BeeStation-Hornet/pull/2580

**VERY IMPORTANT DIAGRAM OF MY BUSINESS MODEL**

image

## Why It's Good For The Game

We could really use a couple more dollars floating around in our budget, and horny pays.

## Changelog
:cl:
tweak: Added a paywall for felinid species
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
image

**Review by Archanial — APPROVED** [review]

**Review by Moccha-Bee — DISMISSED** [review]

**Review by That0nePerson — APPROVED** [review]

**Comment by Coolsurf6** [comment]
lmaooooo

**Comment by Coolsurf6** [comment]
Can't wait to see the amount of comments on this PR hit 100

**Review by qwertyquerty — COMMENTED** [review]
**qwertyquerty** approved these changes ?? minutes ago

**Review by thelaughingbomb — DISMISSED** [review]

**Review by Archanial — DISMISSED** [review]

**Comment by Archanial** [comment]
fuck it double approval, speedmerge now

**Review by ghost — DISMISSED** [review]

**Comment by Racerman2001** [comment]
image

**Review by utilbird — DISMISSED** [review]

**Review by MCterra10 — DISMISSED** [review]

**Review by That0nePerson — DISMISSED** [review]

**Comment by TeomanTheGreat** [comment]
Yes this is how we will bully cat scum

**Comment by That0nePerson** [comment]
I don't see you on the reviewers' list teo

**Comment by qwertyquerty** [comment]
Diagram of my business model
image

**Review by zeskorion — DISMISSED** [review]
get a better visual aid before i approve

**Comment by qwertyquerty** [comment]
> get a better visual aid before i approve

The current one is perfectly fine

**Comment by That0nePerson** [comment]
@qwertyquerty censor the tits on this one and re-post it

**Comment by zeskorion** [comment]
> > get a better visual aid before i approve
> 
> The current one is perfectly fine

sorry bud, you didnt crop with lasso snip, it's not up to beestation mspaint shitpost standards

**Review by zeskorion — COMMENTED** [review]
there will be no approval here until the issue is resolved

**Comment by DatBoiTim** [comment]
> there will be no approval here until the issue is resolved

God damn guys at least get a graphic designer.

**Review by DatBoiTim — DISMISSED** [review]

**Review by Ratvarr — DISMISSED** [review]

**Comment by Ratvarr** [comment]
yes

**Comment by qwertyquerty** [comment]
**VISUAL AID NUMBER TWO (2)**

image

**Review by zeskorion — DISMISSED** [review]

**Comment by That0nePerson** [comment]
speedmerge

**Comment by Archanial** [comment]
reddit do your thing

**Comment by park66665** [comment]
I am pretty sure that this is mostly an annual event but actually seeing one is rather spectacular.

**Comment by Bastian0930** [comment]
Qwerty has gone fucking mad for money and i love it

Felinids arent removed, yet beestation makes money. Based.

**Review by zeskorion — APPROVED** [review]

**Comment by ghost** [comment]
capitalism

**Comment by SweptWasTaken** [comment]
YOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by Couls** [comment]
sick

**Comment by Iamgoofball** [comment]
so, you're charging money for sprite work done by someone that isn't you?

**Comment by Coolsurf6** [comment]
POG, not gonna be merged on aus cause they don't do donations and have like 20-40% felinids.

**Comment by skull132** [comment]
> so, you're charging money for sprite work done by someone that isn't you?

The sprite work is available on GH free of charge tho.

**Comment by Putnam3145** [comment]
> The sprite work is available on GH free of charge tho.

and more importantly licensed in a way that explicitly allows anyone to charge for it

**Comment by park66665** [comment]
It feels like this PR falls under grey area of licenses involved, but I am fairly sure that things like this aren't *explicitly* banned by the licenses. A little bit against the spirit of licenses involved imho, though.

**Comment by r1ks-iwnl** [comment]
@zeskorion This is how you reduce felinids

**Comment by CommandNR** [comment]
Just outright remove them from the game or give them inherent disadvantages to make them easier to robust with toolboxes and spears

**Comment by Coolsurf6** [comment]
There are too many felinid lovers out there to not want the literal reskin of human to be removed. It must be done slowly.

**Comment by PowerfulBacon** [comment]
Is this a meme?

**Comment by amidoingitright** [comment]
[
the gap
](url)
boycot bee, austation is the gap

**Comment by PowerfulBacon** [comment]
> Just outright remove them from the game or give them inherent disadvantages to make them easier to robust with toolboxes and spears

Lol imagine losing to felinids

**Comment by Cenrus** [comment]
[Qwerty after finally monetizing the horny](https://youtu.be/TeXatquVqAc)

**Comment by FantasticFwoosh** [comment]
Honestly this should have been how it was from the very inception. Now round up the others, why should they be free?

**Comment by AtlasRules** [comment]
peak capitalism

**Comment by Stalkeros2** [comment]
Based.

**Comment by Jan-Blasiak** [comment]
Based.

**Comment by lolzyking** [comment]
> [ the gap ](url)
> boycot bee, austation is the gap

Fixed
Fixed this for you.

**Comment by LordZanos** [comment]
Indescribably based. I hope all the downstreams pulls this in.

**Comment by Pill-U** [comment]
Port to tg asap

**Comment by FargothUr** [comment]
blessed bee

**Comment by qwertyquerty** [comment]
Improved via https://github.com/BeeStation/BeeStation-Hornet/pull/2580

**Comment by Effemu** [comment]
thank you qwerty for this based

**Comment by Cooliecan** [comment]
🌏🦘It's in our anthem "For we are young and free(catgirls)"

**Comment by ghost** [comment]
> 🌏🦘It's in our anthem "For we are young and free(catgirls)"

Even GitHub cannot escape the wrath of people necroing shit.

**Comment by celulamp** [comment]
can we readd this

**Comment by Tennessee116** [comment]
> can we readd this



> > 🌏🦘It's in our anthem "For we are young and free(catgirls)"
> 
> Even GitHub cannot escape the wrath of people necroing shit.

**Pull request merged**
