### PR TITLE
Minor Map Fixes

### LINKED ISSUE #11088: [Bug]: Seedvault/podperson ship shutters not working.
### BYOND Version

 515.1640

### Round Date

2024/18/06

### Round ID

49026

### Test merges

_No response_

### Describe the bug

The ship where you spawn as the podperson ghost role has window shutters and a switches that are supposed to activate them and open the window shutters so you can see out.
They do not work, either the switches or the window shutters. 

### What did you expect?

The switches serve no purpose, you push them and i expected the windows shutters to open, instead nothing happens and there is no way to tell if this is intentional or not since the switch does not look broken nor is the window shutters broken. 

### Reproducible steps

Either spawn as podperson ghost role or go to Seedvault ship, then click either of the two switches located inside the ship vaults that looks to be controlling the window shutters.

### PR DESCRIPTION
**Pull request by MarkusLarsson421**
## About The Pull Request
Fixes minor nitpicks, bugs and other annoyances with maps.

Fixes #11088.

A lot of the newer maps already put insuls inside the Engineering lockers and I figured that it is better to standardize it to always be included rather than being mapped in. Currently this raises the available amount of insuls in each Engineering department.

> balance: [Fland] Added a few more beacons around the station.

Personally felt I has no significant locations to teleport to when I have access to the teleporter.

> balance: [Fland] Gave Robotics and Science more materials so they aren't dry on round start.

Most maps you see Robotics and Science start with a good chunk of materials so they and other non-Science personnel can do things. This limited amount is just annoying for everyone.

> balance: [Rad] Added an autolathe to Engineering front desk.

Remember Medbay people complaining how far away the Cargo autolathe was when Rad was first introduced.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>
</details>

## Changelog
:cl:
balance: [Fland] Removed second insuls in tool storage
balance: Added or moved insuls to Engineering lockers.
fix: [Echo] Fix air ratio.
fix: [Fland] Science shutter button permissions to work for Roboticists too.
balance: [Fland] Gave Robotics and Science more materials so they aren't dry on round start.
balance: [Fland] Added a few more beacons around the station.
add: [Echo] Added scrubbers and pumps to air alarms which were lacking them.
balance: [Echo] Removed two out of four (five?) routes into Robotics. Also removed their surgery windoor.
tweak: [Rad] Removed Robotics surgery windoor.
fix: [Seed Vault] Fixes blast door button not working.
tweak: [Seed Vault] Changed the buttons to work for their specific set of blast doors (five in total).
balance: [Rad] Added an autolathe to Engineering front desk.
fix: [Rad] Made SMESs slightly less painful to work with by removing the catwalks.
add: Gave the RD a departmental console so they can do ID stuff.
fix: Fixed Engineering disposals chute.
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
Note to tomorrow me: Fix Rad Engineering disposals bin.

**Comment by ClownMoff** [comment]
Why remove insuls from people

**Comment by MarkusLarsson421** [comment]
> Why remove insuls from people

> Currently this raises the available amount of insuls in each Engineering department.

**Comment by ClownMoff** [comment]
> >  balance: [Fland] Removed second insuls in tool storage

**Comment by MarkusLarsson421** [comment]
Aah, because why should there be three insuls (one paid for) in public? Get an engineer to do Engineering work unless you an antagonist or powergamer.

**Comment by ClownMoff** [comment]
Cringe take

**Review by PestoVerde322 — APPROVED** [review]

**Pull request merged**
