### PR TITLE
nukies can do war below the pop limit without the extra TC

### PR DESCRIPTION
**Pull request by JixS4v**
## About The Pull Request

Allows nuclear operatives to enter war when the pop is below the required amount, without the extra TC that warops would normally afford.

## Why It's Good For The Game

Warops makes the nukie gamemode much more interesting by providing a warning to the station so they can prepare. Countless times stealth nukies have steamrolled the station, and every nukie gimmick is completely exhausted.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/61665800/9c4c92da-9a41-4eb7-aed4-1c170772ec9f

image

</details>

## Changelog
:cl: Ratón
tweak: Nukies can do war without the TC if the pop is below the required amount
tweak: TGUIfied the nukie war prompt
fix: The nukie war time limit display now works properly
/:cl:

### CODE REVIEW

**Review by Miliviu — APPROVED** [review]
LGTM!

**Review by PowerfulBacon — COMMENTED** [review]
Perhaps they should be given something, like if the population is lower than the pop limit you proportionally scale their bonus from 0% to 50% the normal bonus depending on how close the pop is to the limit. (If the limit is 40 and the pop is 39, they get 39/40 * 0.5 extra TC, if the pop is 20 then they get 20/40*0.5 extra TC, if the pop is over 40 they always get 100% of the extra TC pool)

**Comment by JixS4v** [comment]
I don't think this should scale linearly, I'll think something up.

**Review by Rukofamicom — APPROVED** [review]
It can always be improved *more* later, but this is already an improvement to the game as-is and has sat long enough.

**Pull request merged**
