### PR TITLE
TG PORT: New sprite animation

### PR DESCRIPTION
**Pull request by ItsTisme**
## About The Pull Request

Ports https://github.com/tgstation/tgstation/pull/56750
image

TODO ask orginal spriter if hes cool with it. Ill return it to open PR after I got a OK

## Why It's Good For The Game

I have been dared and it looks nice I guese

## Changelog
:cl:
tweak: ports new animation sprite for wag
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
that is disgusting and very furry.

**Comment by Effemu** [comment]
消灭毛茸茸!

**Comment by Septoxide** [comment]
I considered porting this a while ago, then I tested it in game and compared it to the current animation.  Basically it looks really nice and fluid in the sprite viewer, but when on a person in game, the reduced thickness makes it much harder to see, and it just becomes a vague flickering that doesn't look nice.

**Comment by Sinestia** [comment]
I thought it was ugly when i saw it on tg

it's skinny and way too smooth, which makes it not fit at all.  

Only good thing is that I like that it's more of a flick than just... a continuous thing but yeah

its not the worst at least

**Comment by Vexylius** [comment]
It looks weird tbh, not a fan

**Comment by ToasterBan** [comment]
?wilcheb

**Comment by PowerfulBacon** [comment]
Is the only thing stopping this PR from not being a draft permission from original author, or changes to the sprite? If its not the latter we might as well close this already

**Comment by ItsTisme** [comment]
he wont reply to the git comment smh. I think you need permission to port stuff like this but idk for sure

**Comment by ike709** [comment]
Cursed 👍🏻

**Comment by ike709** [comment]
Permission is not required for TG sprite ports.

**Comment by ItsTisme** [comment]
> 
> 
> Permission is not required for TG sprite ports.

gamer to know

**Pull request merged**
