### PR TITLE
Hydrogen Gas

### PR DESCRIPTION
**Pull request by cerebral-314**
## About The Pull Request

This PR will add the Hydrogen gas, a new basic gas that will be used in future for more gas interaction and reactions.
What's changed in the PR (more details in the changelog):

    * New gas H2

    * New machine the Electrolyzer is a machine that works open air, changing the h2o in o2 and h2, it can be upgraded and requires a power cell. To make it you need lasers, capacitor, cable coils, glass, gold and silver.

    * New SM interaction for H2

    * Fusion no longer uses CO2, replaced with H2

    * Hydrogen fire generate water vapor too

    * Reaction with N2 to make ammonia crystals

    * Metal Hydrogen, made in high pressure and heat enviroment (and golems too!)
      With this change fusion is "locked" behind more work to do instead of tech nodes, making it harder to do from roundstart and giving atmos techs more things to make before getting into fusion. Also fusion will get more work in the future to add uses to it.
      Plasma fire got more realistic since normal fires consume the fuel to produce co2+h2o+energy (had to remove the slippery of normal h2o at high temperatures otherwise plasmafloods would be hell). Now there is another way to make h2o so that making h2 no longer need tritium to start with

Credits:
Majority of the code is from: https://github.com/tgstation/tgstation/pull/50510

## Why It's Good For The Game

Increase the amount of stuff to do for the engineering team, stop fusion from being abusable roundstart, a new more basic gas to expand on the current gases and provide more interactions, more realism from an atmos perspective. It also gives a reason to have fusion aside from TEG.

## Changelog

:cl:
add: Added H2 gas
add: Added H2 gas burn (reaction with o2, similar to tritium but without the radiations)
add: Added Electrolyzer (machine to make H2, requires power cell, once turned on and with h2o in the air will start converting it to h2 and o2 with the reaction 2H2O -> 2H2 + O2. Upgrading the parts will increase the amount of converted H2O and the efficency of the cell)
add: Added H2 interaction with SM (similar to trit, less radiation emission, same heat production and a bit of heat protection)
add: H2 reaction with N2 to make ammonia crystals (reaction in open air to make the crystals, temperatures between 0 °C and - 120° C, more N2 than H2)
add: H2 reaction with bz as catalyst at high heat and pressure (over 1e6 for both) to make metal hydrogen
add: metallic hydrogen golem (one of endish atmosian goal)
tweak: plasmaburn now creates some water vapor.
tweak: changed fusion to use h2 instead of co2, everything else is still the same
imageadd: added electrolyzer sprites (reuse of some unused ones)
imageadd: added ammonia crystals sprites
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
How does fastmos handle this, has unobtanium been replaced because of the max gas limit hardcoded?

**Comment by VictorVow** [comment]
I like everything except replacing co2 in fusion, seems like a pointless nerf for something that takes a while to do already.

**Comment by cerebral-314** [comment]
> 
> 
> How does fastmos handle this, has unobtanium been replaced because of the max gas limit hardcoded?

Unobtanium is still in... I recompiled extools to add more gases. I gotta ask... why is `#define TOTAL_NUM_GASES 15` a thing? We could totally just read the server's memory for this. 

> 
> 
> I like everything except replacing co2 in fusion, seems like a pointless nerf for something that takes a while to do already.

It's a needed nerf considering I can make fusion in 7 minutes-ish. Tritium is the hardest part(which isn't hard at all if you have access to a turbine/incin). I can make a solid trit setup with 1 T2 freezer and that's it(it produces about 12 mol a second)... you don't even need to have a waste pipe.

**Comment by ike709** [comment]
> Unobtanium is still in... I recompiled extools to add more gases.

The reason Unobtanium exists was so I didn't have to bother recompiling extools. Please remove unobtainium.

>  We could totally just read the server's memory for this.

When you code it.

**Comment by cerebral-314** [comment]
Okay I coded it... https://github.com/cerebrallolzy/extools

**Comment by Crossedfall** [comment]
> 
> 
> Okay I coded it... [cerebrallolzy/extools](https://github.com/cerebrallolzy/extools)

Don't use your own fork. Push to upstream.

**Comment by cerebral-314** [comment]
> 
> 
> > Okay I coded it... [cerebrallolzy/extools](https://github.com/cerebrallolzy/extools)
> 
> Don't use your own fork. Push to upstream.

We don't own the upstream... it's just go to yogs. I still can if you want though.

**Comment by Crossedfall** [comment]
> 
> 
> > > Okay I coded it... [cerebrallolzy/extools](https://github.com/cerebrallolzy/extools)
> > 
> > 
> > Don't use your own fork. Push to upstream.
> 
> We don't own the upstream... it's just go to yogs. I still can if you want though.

That's what I'm asking you to do, yes.

**Comment by cerebral-314** [comment]
Done.

**Comment by Crossedfall** [comment]
> 
> 
> Done.

Much appreciated. Labeling DNM until they can review https://github.com/yogstation13/extools/pull/5.

**Comment by cerebral-314** [comment]
No problem... fairly new to git so still learning; my apologies.

**Comment by TeomanTheGreat** [comment]
Don't make it so fusion requires it. I dont know a single atmos tech that can make fusion roundstart. Fusion is long enough already bro...

**Comment by cerebral-314** [comment]
1. Round start... create burn can of about 6000 mol(33% o2, 66% plasma). 
2. Get 5 sheets of metal and mats for a freezer(T1 will work)
3. In Incin, replace one of the two connector ports with the freezer
4. Set mix to 92% o2/8% plasma
5. Siphon trit
6. Create a pump/connector on co2/plasma and pump in desired amount
7. Make simple heat exchange/connector thingy(yes, that's a technical term)
8. Heat trit/plasma/co2 can to 10000k and unwrench
9. Rinse repeat profit
10. ???

I know I'm fast but come on dude it's 10 steps to profit. A slow person could do this in 15-20 tops. Also, I just wanna add this doesn't REALLY increase the time to make fusion by all that much. Maybe 5 minutes at most.

**Comment by ghost** [comment]
Wait a fucking sec.... is this a fucking port of /tg/‘s hydrogen gas... this is a fucking word for word recreation you can’t just gloss over that!

**Comment by cerebral-314** [comment]
> 
> 
> Wait a fucking sec.... is this a fucking port of /tg/‘s hydrogen gas... this is a fucking word for word recreation you can’t just gloss over that!

Whoops sorry credits added... the few PRs I've done has been porting my favorite stuff to our server. This one was a bit more involved due to fastmos being a thing though.

**Comment by eLeCtrOssSnake** [comment]
Like everything but fusion replacement 3>

**Comment by eLeCtrOssSnake** [comment]
PR needs more effort to be put in. Don't copy paste tg PRs.

**Comment by eLeCtrOssSnake** [comment]
The simplest one is why the fuck machine that uses rare gas needs so many precious metals?

**Comment by cerebral-314** [comment]
firefox_o6iSqQ7NZg
You just venting or...?

> 
> 
> PR needs more effort to be put in. Don't copy paste tg PRs.

Also you do realize 90% of the stuff you see on Bee is from /tg/ right? Roflmao...

firefox_ekRAVsHyJB

HAHAHAHAHHAHAHHAHAHHAHAHA venting it is...

**Pull request closed without merging**
