### PR TITLE
Removes gang code.

### PR DESCRIPTION
**Pull request by ghost**
This broken gamemode is already disabled on both servers, the sprites are not removed incase anyone is mad enough to remake this gamemode in a way that isn't absolutley terrible.

:cl:
del: gang code has been removed.
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
okay, why?
it not being in code has next to 0 performance increase, and it's fun to force it as admin

**Comment by ghost** [comment]
> okay, why?
> it not being in code has next to 0 performance increase, and it's fun to force it as admin

It's unmaintained and broken content, unmaintained and broken content gets nuked, also yes i know it's fun to force it as admin because you get to watch the chaos, but it's not fun for the majority of players.

**Comment by TeomanTheGreat** [comment]
Improve don't remove

**Comment by ghost** [comment]
> Improve don't remove

No, if it's an absolute hassle to "improve" and is not worth "improving", then by all means remove it.
Gangs starts being shitty at it's base concept, being literally revs with guns, it would be just easier scraping that entirely and begining anew.
But hey, you came here to regurgitate that worthless sentence, do you have any actual suggestion on how to "improve" it, or did you just say that so you can be epic redditor wholesome 100 owned!!!


Also why do you even give a shit? This gamemode is unused you literally won't notice this ingame at all.

**Comment by Archanial** [comment]
First of all, we don't have gamemode maintainers.
Second of all its not broken, just not really good.

**Comment by ghost** [comment]
> First of all, we don't have gamemode maintainers.
> Second of all its not broken, just not really good.

It is  broken, people with mindshields can roll gang boss and not receive gear or hud, and sometimes a random non-mindshielded gang boss just spawns without any gear or HUD.

And yes exactly, this gamemode is bad starting with it's concept, there's no reason to keep it in the code **SINCE IT'S LITERALLY UNUSED**

**Comment by ike709** [comment]
> it not being in code has next to 0 performance increase, and it's fun to force it as admin

This can be technically false actually, due to the way byond handles parent proc lookups.

**Comment by ike709** [comment]
Gang can be re-added via a rework in the future, just like clockcult was.

**Comment by ghost** [comment]
If anyone actually wants this gamemode re-done, then you can start by porting the spitirual succesor of it, famillies, from /tg/.

**Comment by Archanial** [comment]
> 
> 
> If anyone actually wants this gamemode re-done, then you can start by porting the spitirual succesor of it, famillies, from /tg/.

Families are even worse than gangs lol

**Comment by ghost** [comment]
> > If anyone actually wants this gamemode re-done, then you can start by porting the spitirual succesor of it, famillies, from /tg/.
> 
> Families are even worse than gangs lol

¯\_(ツ)_/¯

**Comment by ghost** [comment]
> > If anyone actually wants this gamemode re-done, then you can start by porting the spitirual succesor of it, famillies, from /tg/.
> 
> Families are even worse than gangs lol

No they ain’t

**Comment by utilbird** [comment]
Aww, I don’t wanna modularise all of this for austation, we have gangs in rotation. ;-;

**Comment by ike709** [comment]
@TheFakeElon Try not doing that, it's very broken. If austation has a bunch of bugfixes, PR them upstream.

**Comment by ghost** [comment]
> @TheFakeElon Try not doing that, it's very broken. If austation has a bunch of bugfixes, PR them upstream.

Even if the bugs were fixed, it's just not a good gamemode which is the reason why the players voted to disable it.

**Comment by utilbird** [comment]
😔

**Comment by PowerfulBacon** [comment]
Downstreams have gangs in rotation and it's not actually a broken gamemode it's just not fun. There is no harm in keeping it, but harm can come from removing it so going to close.

**Comment by utilbird** [comment]
😄 yay

I mean, if gangs ever do become a problem code wise, don't feel pressured to keep it, the last thing we want is to be a burden. If I needed to clarify that, thank you though :)

**Pull request closed without merging**
