### PR TITLE
[WIP] Detective Choice Beacon Returns

### PR DESCRIPTION
**Pull request by eeSPee**
## About The Pull Request

Based on Victor's PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2853/files.

Reworked to seem a bit more balanced:
* Detective locker replaced with a Detdrobe: contains all the gear the wardrobe had, and more
* Spyglasses (available in detdrobe and, possibly, maints?)

So the big feature, Detective Beacon, comes with:
* First Responder: Equipts you with deputy gear, detective vest and syndie cigs for healing youself
* Scrunny Sidekick: Medsec HUD, advanced medkit, locator and TRAC
* Undercover Agent: comes with an undercover ID, undercover holster and undercover implanter, perfect for sneaking off as a undercover detective.
* Private Detective: Pretty much your basic detective gear, and a manual that gives you Olfaction, but makes you see everything BnW

Ok so, what changed from the initial PR?
* The kits. Nerfed most of them and added Noir.
* Removed the all modes+mesons det glasses.
* Mapping: wardrobe, remove glasses from det's office, etc

TBD:
- [x] Base Code
- [ ] Fix Conflicts
- [x] Testing
- [ ] Mapping
- [ ] Sprites
- [ ] Foolproof

## Why It's Good For The Game

Det needs love.

## Changelog
:cl:
add: Detective now has a Choice Beacon and a custom Wardrobe
/:cl:

### CODE REVIEW

**Comment by Fronsis** [comment]
Eh, let Olfaction be genetics only so they can at least come and interact with them

**Comment by utilbird** [comment]
Glasses and/or anything else that interacts with ghosts were the main problem with the original PR. You should probably remove them else it'll be unlikely this'll get merged either

**Comment by utilbird** [comment]
Paranormal investigator should just be removed, their only application is observer metagaming

**Comment by OceanFish1** [comment]
Yea interacting with ghosts in any way should be curator only

**Comment by eeSPee** [comment]
> Yea interacting with ghosts in any way should be curator only

Hmm. Agreed.

I think I will need a new gimmick instead of the paranormal investigator.

> Eh, let Olfaction be genetics only so they can at least come and interact with them

Well the beacon is meant to give the Detective a little bit more startup gear that would be obtainable in game at a later stage.

**Comment by Raven-Industries** [comment]
Instead of paranormal investigator, what about Private Eye? A kit for selling your services to the public rather than helping Sec with their weird "threats to the station" and other nonsense.

**Comment by heepox** [comment]
Noir Detective is the one I would always take. gene never gives me olification or there are no gene genies.

Track bullets are very powerful, so really not sure about that.

Paranormal is a bit too metagamey.

how about a hardboiled kit more geared towards combat, but with basic detective tools still. (better protective clothing and cigs laced with healing chems?)

**Comment by eeSPee** [comment]
Fixed most of the kits, under the principle that these ktis should be atainable in game, that are available later through regular means.

**Comment by ItsTisme** [comment]
Will trac bullets be printable? or aviable for resupply some other way?

**Comment by eeSPee** [comment]
TRAC bullets can be printed by prolathe.

**Comment by Raven-Industries** [comment]
Even if this PR doesn't go through, I'd like to see that detective vendor added on its own, it looks great.

**Comment by eeSPee** [comment]
Might atomize this into det-drobe and detbeacon

**Comment by eeSPee** [comment]
To be atomized

**Pull request closed without merging**
