### PR TITLE
Performance improvements and misc fixes

### PR DESCRIPTION
**Pull request by ike709**
Ports:
https://github.com/tgstation/tgstation/pull/51005
https://github.com/tgstation/tgstation/pull/51004
https://github.com/tgstation/tgstation/pull/51002

Credit to vuonojenmustaturska for making things fast.

Bumps the minimum compiler version to 513.1514

**The servers must be running at least 513.1514 or bad things will happen.**

Also did a few minor DreamChecker-related fixes.

I've done some very basic testing and nothing seems horrifically broken, but testmerging this is probably a good idea.

### CODE REVIEW

**Comment by ike709** [comment]
I really hate line endings.

**Comment by qwertyquerty** [comment]
Looks like you slipped a bunch of random stuff in but whatevz

**Review by qwertyquerty — APPROVED** [review]

**Comment by ike709** [comment]
> Also did a few minor DreamChecker-related fixes.

lern 2 reed

**Comment by ike709** [comment]
Don't see any issues, but I'll leave this for @qwertyquerty for merge.

**Review by qwertyquerty — APPROVED** [review]

**Pull request merged**
