### PR TITLE
Roundstart Slimepeople Race: Oozelings

### PR DESCRIPTION
**Pull request by ro5490**
## About The Pull Request

* Unique blood type: Slime Ooze
* Cannot ignite when exposed to flames
* 80% reduced burn damage from high heat, but not burn damage from other sources.
* 300% increased burn damage from cold temperature exposure.
* Takes reverse of normal toxin damage - Take toxin damage from tox-healing medicines and heal toxin damage when consuming normally toxic things
* Has no food preferences despite their gluttonous nature, so no major mood buffs or debuffs from eating.
* Limb regeneration ability
* Random limb vanishes when blood volume is critical, restores some blood volume and nutrition when this happens
* Loses blood volume gradually when hungry
* Loses blood volume rapidly when starving
* Loses blood volume rapidly when processing toxic chemicals
* Loses blood volume rapidly when exposed to water, water vapor, fire extinguishers, and showers
* Slime Vacuole Organ
* Slime faction
* Starts with Galactic Common and Slime Languages + Slime speech verbs

* Reagent: Slime Ooze - Should be interchangeable for Slime Jelly as far as blood transfusions go - it should instantly restore the appropriate blood volume instead just like slime jelly currently does for the existing slime races.
* Reagent: Regenerative Ooze - Restores 0.5 Brute, Burn, Toxin, and clone damage at 0.4u per tick. Created by combining Slime Ooze with Tricordrizine just like its counterpart.
* Reagent: Energizing Ooze - Same as Energizing Jelly, but with an overdose threshold that when reached will shock as if you had plain Teslium in your system. (Slime Ooze + Teslium to make)

## Why It's Good For The Game

Slime Roundstart Race
What more is there to say?

## Changelog
:cl:
add: Added Oozelings, a new race!
add: Added Slime Ooze (bloodtype for Oozelings)
add: Added Slime Vacuole Organ
add: Added Regenerative Ooze - Restores 0.5 Brute, Burn, Toxin, and clone damage at 0.4u per tick. Created by combining Slime Ooze with Tricordrizine
add: Added Energizing Ooze - Boosts Oozeling's nervous system, but only shocks other lifeforms. OD at 30u for teslium shocks. Created by combining Slime Ooze with Teslium
tweak: adjusted watertouch code to interact with Oozelings
config: Oozelings are now in Roundstart Races!
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
PR was approved in DM by myself

**Comment by ike709** [comment]
> 300% increased burn damage from cold temperature exposure.

_Technically_ the malleable cells should actually be _more resistant_ to cold temperatures due to the presumable increase in unsaturated fatty acids in the cell membranes, but this is fine from a balance perspective.

Also I haven't dived into the specifics at all but this seems like a relatively neat race (on paper).

**Comment by ike709** [comment]
Maintainers don't put this to a vote until it's gotten a proper look-over and it's been tweaked for balance.

**Comment by ro5490** [comment]
> Maintainers don't put this to a vote until it's gotten a proper look-over and it's been tweaked for balance.

This.
did some testing with ruko for balance, but it might need more tweaking tbh

**Comment by Rukofamicom** [comment]
I did my best to tone them down and make them an overall fairly weak race that suits the flavor of the simplemob slimes without straying too far from the existing slime races. The goal was a flavorful slime-race with some advantages, but enough drawbacks to dissuade people who simply wish to powergame those advantages. 

Compared to the slime races already in the game through Xenobio, these have:
* A little more resistance to heat
* No resistance to other burn damage (So no resistance to lasers and such)
* A loss of blood volume when hungry, eventually triggering the loss of limbs that comes with that
* A loss of blood volume when exposed to water in any form (Vapor, Showers, Extinguishers, Spray Bottles, Ingestion)
* A weaker version of slime jelly for blood, since slime jelly was far too potent of a toxin on other races
* The ability to make a weak healing reagent for cloneloss out of their blood because outside of rezadone (which requires carpotoxin) they would have no way to restore clone damage. This also follows suit with "weaker slime jelly" by being a weaker version of Regenerative Jelly with a parallel recipe to create.

In my opinion they're balanced quite well after a handful of hours testing and tweaking values with @ro5490

**Comment by Fronsis** [comment]
This looks very neat! Do they have any specific way of naming themselves? Like the moths-plasmemes-lizards-etc

**Comment by Rukofamicom** [comment]
Aaaaaa 
I started trying to make a naming convention last night and forgot to finish it.

**Comment by eeSPee** [comment]
>Loses blood volume gradually when hungry

>Loses blood volume rapidly when starving

:(

**Comment by ghost** [comment]
> Cannot ignite when exposed to flames

Cringe. This is anti plasmaflood race

**Comment by ZombiesVsPlants** [comment]
yeah, they should still be set on fire, maybe have a cap of 5 firestacks?

**Comment by Rukofamicom** [comment]
Plasma floods create water vapor during the burning, and the high pressure (and to a lesser extent) the raw heat still harm them as well. They are more resistant to plasma floods than other races, but are still going to die to one if they don't respond to it.

**Comment by ghost** [comment]
> Plasma floods create water vapor during the burning, and the high pressure (and to a lesser extent) the raw heat still harm them as well. They are more resistant to plasma floods than other races, but are still going to die to one if they don't respond to it.

80% heat resistance for the downside that you need food is still completely idiotic, and they will last far longer in an inferno than any round start race

**Comment by ro5490** [comment]
> > Plasma floods create water vapor during the burning, and the high pressure (and to a lesser extent) the raw heat still harm them as well. They are more resistant to plasma floods than other races, but are still going to die to one if they don't respond to it.
> 
> 80% heat resistance for the downside that you need food is still completely idiotic, and they will last far longer in an inferno than any round start race

They might be able to survive a fire a bit longer, but if you spray em with an extinguisher they die almost as fast or even faster than someone in an inferno. 
Slip some water into their drink? Massive blood loss on each sip, causing loss of limbs and eventually crit.

Its like, if a human puts on an atmos hardsuit, but then gets force fed acid. heat resitance doenst do shit against their insane flaws.
Janitor or clown opens a vapor canister nearby? Whelp there goes your limbs if you're in it too long
You get sprayed by any water, at all? Instant blood loss and possibly loose a limb or go into crit depending on the amount of water.

Fire extingishers are more availiable than plasma floods and do far more damage to them

Its give and take, high heat res, but they're able to be crit with a full drinking glass of water(currently)

**Comment by zeskorion** [comment]
plasma floods are cancer anyways

**Comment by ghost** [comment]
> plasma floods are cancer anyways

You r cancer

**Comment by ro5490** [comment]
lmk if tweaks are needed @ike709 
I think me nd ruko got it pretty balanced but ye, always good to double check things

**Comment by ro5490** [comment]
@Crossedfall Any chance we could get a testmerge for player input on how this could be tweaked?

**Comment by Crossedfall** [comment]
Closed due to the repository being deleted.

**Pull request closed without merging**
