### PR TITLE
Renames the gps signal of the bubblegum and blood drunk miner to better fit them.

### PR DESCRIPTION
**Pull request by Moccha-Bee**
## About The Pull Request

Bubble gum signal is kinda cringe dosen't really relate with his name and makes it seem like he is evil and bad but in reality he is just a warm hearted kid who needs some love that's all. WIth this pr the blood drunk miner gps signal gets renamed to Bloody Signal, to make new players fearful and combine with his name. And bubblegum is now called Bubbly signal

## Why It's Good For The Game
Because yes.

## Changelog
:cl:
add: Renamed bubblegum and blood-drunk gps signals.
/:cl:

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
Based....

**Comment by PowerfulBacon** [comment]
I think the old bubblegum one was better, and blood drunk should either be something mining-related like 'resonant signal' or 'drunk signal'.

**Comment by Moccha-Bee** [comment]
> I think the old bubblegum one was better, and blood drunk should either be something mining-related like 'resonant signal' or 'drunk signal'.

Bloody signal dosen't really fit well , the bubblegum is very easy to beat and the blood drunk miner well he is drunk on blood so he is bloody

**Comment by Moccha-Bee** [comment]
> I think the old bubblegum one was better, and blood drunk should either be something mining-related like 'resonant signal' or 'drunk signal'.

TBH drunk signal is better

**Review by qwertyquerty — CHANGES_REQUESTED** [review]
Update the wiki for merge

**Comment by Moccha-Bee** [comment]
> Update the wiki for merge

Wiki has been updated

**Review by qwertyquerty — APPROVED** [review]

**Pull request merged**
