### PR TITLE
Safety Moth(TM) posters from your friends at Nanotrasen! [Depreciated Version]

### PR DESCRIPTION
**Pull request by AyyRobotics**
Adds Safety Moth Posters. (Credit to AsphaltEvidence for the original images)

## About The Pull Request
Just adds some sprite versions of "Safety Moth" posters into the game.

Themoffs
Themoffs2
Notice, the two on the right suffer from some bug I can't figure out. I _did_ fix it for the ingame posters, so it's just the bottom image that suffers from it, mostly.

## Why It's Good For The Game

1. More posters
2. _Safety Moth_

## Changelog
:cl:
add: Added safety moth posters
add: Added new image file for replacement
del: Removed old image file for replacement
imageadd: added safety moth images
code: changed some code
refactor: refactored some code, I guess. I don't know how the label just showed up.
/:cl:
[](url)

### CODE REVIEW

**Comment by SomeAngryMiner** [comment]
my god, please do not bitcrush things, just sprite them.
Also might be wise to close this, 90% sure you didnt ask asphalt permission for using em.

**Comment by AyyRobotics** [comment]
Oh yeah we don't have the creative commons license do we. I should probably do that

**Review by ike709 — CHANGES_REQUESTED** [review]
These look awful.

**Comment by PowerfulBacon** [comment]
Changelog needs fixing too

**Comment by boolsrealm** [comment]
i cant even make any of it out

**Comment by AyyRobotics** [comment]
Alright to address the mentions of the quality of these images: I know. They are absolutely horrid compared to their original versions, with only _maybe_ one ending up decent. I would sprite better variations of these, but I am not very good at spriting, so I feel that these would end up being better than my work.

**Review by AyyRobotics — COMMENTED** [review]
If I can find better, or maybe even _create_ better versions for the posters I certainly will change them, but for now I have to go with these

**Comment by boolsrealm** [comment]
you **have** to go with these? you don't **have** to go with any of it you can just wait till you have something better, i know spriting is hard bro but anyone can learn it, i'd just give it a try if i was you, i blow at spriting so i know the feel my man

**Comment by ike709** [comment]
> but for now I have to go with these

Alternative: For now you go with nothing since these look terrible.

**Pull request closed without merging**
