### PR TITLE
Remove arena shuttle

### PR DESCRIPTION
**Pull request by ItsTisme**
## About The Pull Request

Removes arena from buyable shuttles

## Why It's Good For The Game

Request from franc also its very not-RP

## Changelog
:cl:
del: Arena shuttle is gone
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Doesnt this require emagging anyway?

**Comment by francinum** [comment]
It's functionally broken, IIRC.

**Comment by francinum** [comment]
It's also pretty much the last word in putting a massive bullet in round progression for the cost of needing to kill one mining megafauna and emagging the console.

**Comment by Sinestia** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/4791

It was fixed here, allegedly.

I don't think it's terrible because it virtually never happens, and it's not horrible to have stuff like this around. It's a "People don't abuse it, so why rip it out" sort of thing.

**Comment by ItsTisme** [comment]
> I don't think it's terrible because it virtually never happens, and it's not horrible to have stuff like this around. It's a "People don't abuse it, so why rip it out" sort of thing.

Semi thinking this aswel, but rather keep it non-purchasable instead of only emag needed. just by its nature.

Avoids future headaches

**Pull request closed without merging**
