### PR TITLE
Adds signal_handler to all procs that handle signals

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request
some code taken from: 
https://github.com/tgstation/tgstation/pull/59176

Only procs that don't have it are crossed and sect altair proc, because they're both getting reworked in separate prs.
Also removes SIGNAL_HANDLER_DOES_SLEEP and any sleeps that block signals.

## Changelog
:cl:
add: SIGNAL_HANDLER to all procs meant to handle signals
del: Removed SIGNAL_HANDLER_DOES_SLEEP
del: Some sleeps
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
the 2 lines after look disgusting

**Comment by Archanial** [comment]
> 
> 
> the 2 lines after look disgusting

ok

**Review by ike709 — APPROVED** [review]
Looks okay, should still probably testmerge first though

**Comment by RDS88-beeman** [comment]
broke using bio bags on reproductives. again. why is that code so fragile

**Comment by Archanial** [comment]
> 
> 
> broke using bio bags on reproductives. again. why is that code so fragile

Unable to reproduce on local and this didn't touch biobag.

**Comment by ike709** [comment]
@TheFakeElon did anything break

**Comment by RDS88-beeman** [comment]
maybe it's a pref or something else idk i just know they didn't work and it was torment

**Pull request merged**
