### PR TITLE
BoxStation importand and not so important changes attempt 2

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request

Second attempt of https://github.com/BeeStation/BeeStation-Hornet/pull/11651. Since some other errors were already adressed in other PRs, this one fixes some left behind on that PRs as well with other small changes that I thought were good.

## Why It's Good For The Game

Makes the game easier to play, as some of this errors, like the chem storage not being accessible from chemistry is bad. As for other changes:

- The bar and areas that are open/not dangerous shouldn't have reinforced windows since they are more expensive to make and you are not protecting anything.
- The mulebot beacon should go in surgery and not the surgery theatre given that the latter is an area open for everyone.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

68747470733a2f2f616666656374656461726330372e626c6f622e636f72652e77696e646f77732e6e65742f6d6462322f696d616765732f3136323335363932372f33313436343631303131392f6d2f5f6d6170735f6d61705f66696c65735f426f7853746174696f

68747470733a2f2f616666656374656461726330372e626c6f622e636f72652e77696e646f77732e6e65742f6d6462322f696d616765732f3136323335363932372f33313436343631303131392f6d2f5f6d6170735f6d61705f66696c65735f426f7853746174696f

</details>

## Changelog
:cl: ClownMoff
add: BoxStation: Added new decals.
add: BoxStation: Added  folders in lobby and psychiatrist room.
del: BoxStation: Deleted an extra crew sensors computer.
tweak: BoxStation: Moves the delivery beacon in medbay from the surgery theatre to the surgery room.
tweak: BoxStation: Adjusts the coldroom MuleBot dock a little .
tweak: BoxStation:  Changes the medical records laptop for a computer to replace the duplicate crew sensors computer.
tweak: BoxStation: Puts the chemistry fridge for medbay staff in an place that can be accessed inside chemistry and moves the medbay storage slightly to accomodate this change.
tweak: BoxStation: Puts the correct floor type in the mulebot delivery place in the bar and kitchen coldroom.
tweak: BoxStation: Fixed a mapping error where the kitchen area would reach the customer area in front of it, allowing chefs to CQC outside the kitchen.
tweak: BoxStation: Moves the organ fridge for surgery to a place that can be accessed inside and outside surgery.
tweak: BoxStation: Moves a NanoMed in the treatment center to a better location.
tweak: BoxStation: Organizes the treatment center in medbay around for a better layout.
tweak: BoxStation: Swaps a lot of reinforced windows for normal windows in service and medbay area.
fix: BoxStation: Fixes the service maintenance not being accesible by having maintenance access
fix: BoxStation: Fixes the morgue door not working due to an error in the access
fix: BoxStation: Adds maintenance area the bar backroom airlock.
/:cl:

### CODE REVIEW

**Review by Rukofamicom — DISMISSED** [review]
> Swaps a lot of reinforced windows for normal windows in service and medbay area.

Revert this and it both sounds and looks good.

**Comment by ClownMoff** [comment]
Why?

**Comment by PowerfulBacon** [comment]
I think using regular glass windows is fine, though the fulltile windows in bar and the medbay public area shouldn't be reinforced.

image

I also prefer the old bar shape since the room now just looks a bit empty since its larger than it needs to be. It's generally good mapping practice not to make rooms overly spacious and empty.

**Comment by Rukofamicom** [comment]
> Why?

Because it's standard as far as I know (I'm open to being corrected) to have reinforced windows aside from the front entrance windows. Example from the current map in-game right now:

Normal windows in the front
image

Reinforced on Chemistry:
image

Reinforced everywhere deeper in the department as well:
image

I don't like deeper reaches of departments being easy to smash into.

**Comment by ClownMoff** [comment]
> I also prefer the old bar shape since the room now just looks a bit empty since its larger than it needs to be. It's generally good mapping practice not to make rooms overly spacious and empty.

Then the maintenance is huge for no reason, 5 tiles wide

**Comment by PowerfulBacon** [comment]
Well it's 4 tiles wide with a little inlet that has shelves in the space. There are solutions to a space being too open that don't involve just shifting the problem to a different room.

**Comment by Rukofamicom** [comment]
I want to point out that #11650 did not change the shape like you claim:

Before #11650 
image

After #11650 
image

**Comment by ClownMoff** [comment]
Fun fact: that was, in fact, my own doing. I had another version with a different shaped room and I just thought that PR changed the bar layout. A layout I made MYSELF. Awesome.

**Review by spockye — CHANGES_REQUESTED** [review]
image

remove those two windows, doesnt really fit. 
the corner in general seems a little weird to me.... mabye try something else? like a vendor + a plant. go crazy

image

bar backroom maints zone
same in surgery and service hall

some small nitpicks here and there

image

please use the new directional wallmounts! 

image

floating bottle

image

floating bottle

image

grinder is under the dispenser?


otherwise looks good

**Comment by Rukofamicom** [comment]
Failing checks

**Review by Rukofamicom — APPROVED** [review]
My approve didn't go through!

**Pull request merged**
