### PR TITLE
Captain cloak update

### PR DESCRIPTION
**Pull request by Naevii**
## About The Pull Request

Now you actually look like the richest person on the station.
New Captain cloak sprite

without backpack

with backpack

## Why It's Good For The Game
Gets rid of this terrible green color and cloak outline.
Another part of the great cloak resprite. 

## Changelog
:cl:
tweak: Captain cloak has a new sprite!
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
I like the old one.
But damn this is so much better.

**Comment by Naevii** [comment]
> I like the old one.
> But damn this is so much better.

this shade of green (in old sprite) as an outline should be considered a crime against art.

**Comment by ghost** [comment]
I like green tho

**Review by PerishedFraud — APPROVED** [review]
Badass.

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
