### PR TITLE
Fixes techfloor_"grey"

### PR DESCRIPTION
**Pull request by spockye**
## About The Pull Request
The icon for techfloor_grey uses "gray", while the iconstate path uses "grey". This PR changes the name of the icon file. 

## Why It's Good For The Game
The stated issue causes it to not spawn with an actual sprite. this is bad. Grey is also the correct way to write it ;(

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
fix: fixed techfloor_grey icon name
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
Sprite changes are cringe, just change the code it's less likely to make a merge conflict

:trollface:

**Comment by spockye** [comment]
> Sprite changes are cringe, just change the code it's less likely to make a merge conflict
> 
> :trollface:

Grey is the right way to spell it, i will fight you on this ;(

**Comment by itsmeow** [comment]
This is not for spelling purposes but merge conflict reasons

change the code not the sprite

**Review by itsmeow — APPROVED** [review]
ok fine

**Pull request merged**
