### PR TITLE
Adds ID modification logging

### PR DESCRIPTION
**Pull request by St0rmC4st3r**
## About The Pull Request

This creates a new log file "id.log" that contains the changes made to cards via ID consoles, stationary or portable. 
It logs the name, assignment, access changes as well as demotion.

As an addition, it logs the agent ID stealing access from cards and access being added using the mining access card from the conscription kit.

It can be enabled and disabled in configuration files.

This PR was made possible by Bloons! With his help Bee has this PR and I can have **Bee**r!

## Why It's Good For The Game

Well, uh. Now admins can find who was the bastard that distributed All Access to everyone.

## Changelog
:cl:
add: ID modification is now logged.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
Does the log need to be started/created first?

**Comment by St0rmC4st3r** [comment]
I don't think so? I don't really understand the question, @PowerfulBacon. You mean the log file itself? It is being created once log_id is called for the first time.

**Comment by St0rmC4st3r** [comment]
@Crossedfall, any input? The roundstart number added.

**Review by PowerfulBacon — APPROVED** [review]
Looks good to me, @Crossedfall you are the config person however

**Review by Crossedfall — APPROVED** [review]
Config applied

**Pull request merged**
