### PR TITLE
Adjusts Sanity Disruptor anomaly, minor nerf to fake wiz robe

### PR DESCRIPTION
**Pull request by EvilDragonfiend**
## About The Pull Request
Adjusts Sanity Disruptor anomaly that's introduced by #10172

* Less chance to appear. it has the same chance to appear like other anomalies, but still has pop cap
* blindness is very short now
* Now it can be neutralised by signal
* you can protect the pulse with artifact protection gears - stuff that you can get from xeno artifact research
* fake wizard robe no longer 100% protective against artefacts. it has 75% chance that bio suit has. zero movement penalty is already effective.
* slight buff to pulse interval

## Why It's Good For The Game
people hate this

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

getting blurry instead of blind, and no stun

image

you can see emote is still there - blind is very short

image
image

can neutralize

</details>

## Changelog
:cl:
tweak: Sanity Disruptor now less appear on dynamic. it still has pop lock, but has the same chance to all anomalies'
tweak: Sanity Disruptor blinds people very very shortly than +60 seconds
tweak: Sanity Disruptor pulse can be protected by xenoartifact protective gears
tweak: Sanity Disruptor interval pulses a little bit often (10s to 7s)
fix: Sanity Disruptor can be neutralised by signal.
balance: fake wizard robe now protects artifact 75%, instead of 100%.
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
I'd still prefer if it affects the local area instead of the whole station, just like every other anomaly.

**Comment by EvilDragonfiend** [comment]
> I'd still prefer if it affects the local area instead of the whole station, just like every other anomaly.

It's intended to punish the whole station because they failed to neutralise it. Other anomalies should be so.

**Comment by zeskorion** [comment]
why is the fake wizard robe lumped into this

**Comment by EvilDragonfiend** [comment]
> why is the fake wizard robe lumped into this

I didn't want this to be a 100% reliable thing.

**Comment by zeskorion** [comment]
> > why is the fake wizard robe lumped into this
> 
> I didn't want this to be a 100% reliable thing.

should be a separate pr?

**Comment by EvilDragonfiend** [comment]
> > > why is the fake wizard robe lumped into this
> > 
> > 
> > I didn't want this to be a 100% reliable thing.
> 
> should be a separate pr?

I don't think it's necessary. Lumped in this PR more makes sense to track the idea for why it was nerfed.
I'd even remove the anti artifact component if it was in its own PR.

**Review by Penwin0 — APPROVED** [review]

**Pull request merged**
