### PR TITLE
v2 Adds Tactical Breaching Shotguns and Grenade Launchers port

### PR DESCRIPTION
**Pull request by VictorVow**
Had to make a new PR because my last branch fucked up. Same as [previous PR](https://github.com/BeeStation/BeeStation-Hornet/pull/1280) except:
1) The breaching shotguns have been removed from the Armory until they can be fixed to only accept breaching slugs by a better coder than I. An extra riot shotgun and ammo box have been added to replace them. 
2) Nukies can now buy 12g breaching slug drums for their Bulldog shotguns for 2 TC. 

## About The Pull Request
Ever conduct a security raid but realize the departmental officer didn't attend, and/or the AI is unavailable? Never again be locked out of the science lab preventing you from ~~executing~~ arresting the gang inside, with the new Tactical Breaching Shotgun!

This holds a brand new type of shotgun ammo, the Breacher Round, which can break most windows and grilles instantly as well as shoot down airlocks in 3 shots. However, it only deals 10 damage to everything else, so using it on people would be pretty dumb. Consequently, this compact device only holds 3 rounds. The ammo, however, can be loaded into any shotgun and can be found in a box in the armory or is producible inside the security protolathe for 4000 metal.

More security tools are always good to add as it lets security explore additional options to deal with station challenges. Officers can take one of these to Reebe, for example, to help the crew by breaking down cult doors. They are also great when raiding departments as a group as it can break down welded or bolted doors. Alternatively, it can be used to quickly make window entry points to surprise defenders.

The main drawback of this device is the low ammo capacity, it can only hold breaching slugs, the fact that the ammo is expensive to make and only does 10 damage to anything not a door or window.

*also*

Grenade launchers were already present in the code but not on any currently rotating stations. One has been added to the Armory on each station. 

## Why It's Good For The Game

Greater variety of tools mean more ways to handle a situation, and it gives sec a way to get past light barricades. 

## Changelog
:cl:
add: The Armory now contains an extra riot shotgun and specialised breaching ammo. Use them to quickly break down airlocks and windows to create entry points, but do note they are nearly useless against people.
add: The Armory now contains a grenade launcher.
add: Nukies can now buy 12g breaching slug drums for their Bulldog shotguns for 2 TC.
/:cl:

### CODE REVIEW

**Comment by qwertyquerty** [comment]
I don't want to merge a PR that has a known bug in it. Do you think you can get it fixed first?

**Comment by VictorVow** [comment]
The shotguns aren't being added to the map yet so it won't affect gameplay, I've asked Zesk to take a look at it since I can't quite figure it out yet. The breaching ammo and grenade launchers work fine and are added.

**Comment by VictorVow** [comment]
Zesk agreed it'd take some major sphagetti to get the new shotgun to take only breacher slugs whilst allowing that ammo to be used by other shotguns. I'd like to leave them in the code for admins to spawn though or if someone wants to use it for something else.  Edit: CL updated.

**Comment by eLeCtrOssSnake** [comment]
SWAT 4 stuff...

**Comment by eLeCtrOssSnake** [comment]
I would like to rework shotguns a bit, to make more logical and realistic ammunition and many types of it.

**Pull request merged**
