### PR TITLE
some holodeck fixes and changes

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request
photoboot:
replaces the snow (why is it here in the first place????) with the actual white tiles
removes a camera and gives the other one 999 photos
adds a razor

beach:
replaces the fake water with an iconchanged pool tiles

## Why It's Good For The Game

better beaches good

better photos good

## Changelog
:cl:
tweak: the holodeck beach and photobooth modules have been updated
tweak: photobooth has been given the correct photoboot tiles instead of snow
tweak: photoboot holodeck module has been given a razor and infinite photos camera
tweak: beach holodeck module can now be swam in
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
would be nice if the spray cans in the sim were infinite too

**Comment by eeSPee** [comment]
Make sure to give holographic tag to the spray decals.

**Comment by ToasterBan** [comment]
> Make sure to give holographic tag to the spray decals.

even before the rework the spray cans didn't have that + I dont know how to do that as I'm not a coder

**Review by utilbird — APPROVED** [review]

**Comment by jupyterkat** [comment]
this broke the photobooth holodeck, the photobooth is snow for a reason

**Comment by ToasterBan** [comment]
> this broke the photobooth holodeck, the photobooth is snow for a reason

the holodeck was broken way before this, and how is snow required? it slows you down and has a weird texture, not the best for photos

**Comment by jupyterkat** [comment]
BeeStation/BeeStation-Hornet#4874

**Pull request merged**
