### PR TITLE
Removes the ore silo

### PR DESCRIPTION
**Pull request by Rukofamicom**
## About The Pull Request

* Removes the ore silo from all maps
* Removes ore silo boards from all maps
* Removes ore silo from the tech web
* **Does not** remove the ore silo and supporting code entirely from the game so that they may still be made obtainable through other means at a later date, such as via station traits, exploration or otherwise. 

Additionally:
* Removes the RCD silo link upgrade, including completely erasing the related code

## Why It's Good For The Game

* The ore silo optimizes a lot of potential interaction right out of the game and contributes heavily to the speedrunner rush mindset that pollutes our server. 
* The ore silo also gives the station a critical vulnerability by having nearly the entirety of station resources kept in a single and relatively remote location, while being equally accessible by everyone on the station. 
* This gives Cargo a tangible and meaningful role on the station again, in terms of not only organizing material deliveries but also deciding who deserves priority in receiving valuable materials. 

## Testing Photographs and Procedure

<details>

image

image

image

</details>

## Changelog
:cl:
del: Removed the ore silo from every map and the tech web
del: Removed the RCD upgrade for linking to ore silos which don't exist anymore. 
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
god I love being right

**Comment by CydiaLamiales** [comment]
Consider shuffling around some of the roundstart supplies of iron/glass to accommodate.
Giving some iron to medbay for additional surgery tools, for example, as those usually were printed with the iron from Robotics.

**Comment by mystery3525** [comment]
I have personally done multiple rounds where the ore silo was not present roundstart, and I have found that Cargo cannot be trusted to distribute resources in those times.

**Review by francinum — APPROVED** [review]

**Comment by Rukofamicom** [comment]
> I have found that Cargo cannot be trusted to distribute resources in those times.

Nothing like a little interdepartment conflict to keep rounds interesting!

**Comment by Wisemonster** [comment]
With cargo needing to distribute resources, one issue that will come up is trying to distribute mats such as bs crystals, where some departments have things that require bs crystals, but will be unlikely to get it due to be rather unimportant (janitor comes to mind) unless there's a surplus. Also, cargo will have more work to do (CE if there's no qm/cargo tech), not to mention more yelling ("Sec make X", "I can't, cargo never gave us mats!", "Cargo, get off your ass!")

**Comment by PowerfulBacon** [comment]
This needs significant work around this to make it not just plain annoying. This was testmerged before and didn't play well. Mainlny, there needs to be an actual value to printing minerals rather than having them as a mush so that you can know what you need to grab before printing (barotrauma style is what comes to mind) or there needs to be a local mineral closet in departments which connects nearby machines.

Cargo having tools to see how many minerals each department has, ways to request minerals or automatic alerts could make this not horrible.

I don't like the ore silo, but everything is designed around it and all of those things just become miserable gameplay-wise once you remove it.

**Comment by CydiaLamiales** [comment]
Also if you do this, please make the recycler actually give materials from the stuff it grinds up.

**Comment by Rukofamicom** [comment]
> This was testmerged before and didn't play well.

This isn't something players can adapt to within the very short timeframe of previous tests.

> there needs to be an actual value to printing minerals rather than having them as a mush so that you can know what you need to grab before printing (barotrauma style is what comes to mind) or there needs to be a local mineral closet in departments which connects nearby machines.

Most departments only have one machine that needs the minerals directly, in fact the only exceptions to this that actively comes to mind are the autolathes which area already loaded manually, and the robotics machines. Other than that every department just has their lathe, which can serve as the central storage for materials.

> Cargo having tools to see how many minerals each department has, ways to request minerals or automatic alerts

Cargo can ask or be told when someone needs something and nothing about that process needs to be or should be automated. Cargo has a general idea of which materials are most valuable who has the best case of necessity in times of shortage.

**Comment by EvilDragonfiend** [comment]
I am fine with testmerging this to see which thing will happen.

**Comment by llol111** [comment]
Oh shit its happening
lets goooooo

**Review by CydiaLamiales — CHANGES_REQUESTED** [review]
I still feel like several changes need to be made in order to accommodate for the removal.
image
The Request Console's UI definitely needs an overhaul.
image
The department protolathe should be able to que up several items like the autolathe, and both should show how many resources the queued up items require.
You should be able to dump out items from backpacks and other storage items directly into lathes with clickdragging.
image
Service techfabs should have mulebot dropoff spots.
There should be a request console by every department techfab.
And a bit more of a thematic change - the vault should get more valuables so it actually makes sense for pirates and other antags to raid it.

**Comment by francinum** [comment]
> Also if you do this, please make the recycler actually give materials from the stuff it grinds up.

It has.
For literal years.

-----

> I still feel like several changes need to be made in order to accommodate for the removal. 

Oh boy let's see this one.

> The Request Console's UI definitely needs an overhaul.

Still works, though. Just because it's aesthetically ugly doesn't change it's function.

> The department protolathe should be able to que up several items like the autolathe, and both should show how many resources the queued up items require.

Reasonable but very out of scope.

> You should be able to dump out items from backpacks and other storage items directly into lathes with clickdragging.

I can't see why you'd want this. You do know that with the removal of the ORM from ubiquity, these things **have a storage cap**, right? You can't just blindly dump materials into it. You DO need to think about what you're putting in.

> Service techfabs should have mulebot dropoff spots.
> There should be a request console by every department techfab. 

This is true for pretty much every existing fabricator that isn't service's. Easy change.
Though honestly I just believe that the contents of the service fabricator barely justify the existence of their own personal fab.


> And a bit more of a thematic change - the vault should get more valuables so it actually makes sense for pirates and other antags to raid it.

Agreed, but horrifically out of scope.

**Comment by CydiaLamiales** [comment]
> > Also if you do this, please make the recycler actually give materials from the stuff it grinds up.
> 
> It has. For literal years.

Not without upgrades. And nobody ever upgrades jt.

> > You should be able to dump out items from backpacks and other storage items directly into lathes with clickdragging.
> 
> I can't see why you'd want this. You do know that with the removal of the ORM from ubiquity, these things **have a storage cap**, right? You can't just blindly dump materials into it. You DO need to think about what you're putting in.

Yes I know that hey have storage and that said storage scales with the matter bins inside. However, I can definitely see Cargo passing along boxes/backpacks/duffels full of requested materials, so it would be nice if there was an option to dump it all at once.

> all the "out of scope" comments

Ruko made a whole list of changes when he proposed the common radio channel to be removed, I'm simply doing the same thing here. And said changes should probably be done before this one comes through, so that the playerbase doesn't have to suffer while they wait for them.
Oh and this honestly feels somewhat poorly thought out, Ruko even forgot to remove the linked Ore Silo upgrade for the RCD untill I reminded him about it.

**Comment by Rukofamicom** [comment]
> Oh and this honestly feels somewhat poorly thought out, Ruko even forgot to remove the linked Ore Silo upgrade for the RCD untill I reminded him about it.

Don't act like this isn't something I've brought up and discussed for months. You know me better than what you're insinuating here and this is insulting.

My first pass of this I that I didn't push addressed the RCD and everything else because it was a 100% code removal, including removing the associated component. I let that sit on my machine for a while and thought about what it could still be used for before pushing it and opening the PR and drama I knew would come with it.

I decided consciously that all of the supporting code should remain for the potential of station trait and/or admin shenanigans. I only overlooked the RCD in the sense that it's a dead upgrade 99% of the time and shouldn't take up a tech node or interface space because of that.

**Comment by MTandi** [comment]
Maybe take a less harsh approach first of making it have a limit of active links and QM responsible for selecting which departments have the active link.

**Comment by MCterra10** [comment]
Surely this is a parody of a pull request

**Comment by bluezorua** [comment]
people are saying cargo techs wont ever send resources, but have you ever played cargo tech? half the time you have nothing to do and I would honestly kill for anything to make me move around and interact, there is mail but normally someone else just becomes a dedicated mailman

**Comment by PowerfulBacon** [comment]
I take it this is dead?

**Comment by Rukofamicom** [comment]
No it isn't.

But I'm currently devoted entirely to a side project you're aware of. I will need help doing TGUI changes though.

**Comment by Rukofamicom** [comment]
Closing in favor of #10113 which I discussed on discord.

**Pull request closed without merging**
