### PR TITLE
[Port] Adds fingerless insulated gloves as a Assistant heirloom item.

### PR DESCRIPTION
**Pull request by bloons3**
https://github.com/tgstation/tgstation/pull/54446

## About The Pull Request

> Well, it adds fingerless insulated gloves to the game, and it also makes them a Assistant heirloom item alongside the heirloom toolbox. The sprites and code were taken from Skyrat, with some modifications by me.

## Why It's Good For The Game

> Variety is the spice of life, and it wouldn't hurt to have more heirloom items.

## Changelog
:cl: sergeirocks100 
add: Adds fingerless insulated gloves as a Assistant heirloom item.
/:cl:

### CODE REVIEW

**Comment by Penwin0** [comment]
Based bloons nerfing assistants that pick heirloom for the free toolbox

**Comment by eeSPee** [comment]
> Based bloons nerfing assistants that pick heirloom for the free toolbox

A cardboard box serves the same purpose :S

**Comment by yyzsong** [comment]
Fingerless insuls have old insul sprite
hnng

**Comment by Penwin0** [comment]
> > Based bloons nerfing assistants that pick heirloom for the free toolbox
> 
> A cardboard box serves the same purpose :S

A cardboard box cant crack your head open

**Comment by bloons3** [comment]
Merge conflicts manually resolved, dunno why github is bitching
image

**Pull request closed without merging**
