### PR TITLE
Pepperspray buff

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
Spray speed slightly increased, range for stream mode increased by 2 tiles, container volume doubled and duration of effects slightly increased.

## Why It's Good For The Game
Pepperspray is never used and it never has been, hopefully it'll be in a state now where it finally is useful enough for this to change.

## Changelog
:cl:
balance: Pepperspray buffed. Spray speed slightly increased, range for stream mode increased by 2 tiles, container volume doubled and duration of effects slightly increased.

### CODE REVIEW

**Comment by Moccha-Bee** [comment]
you even increased the range? I think the speed should be increased but the range should stay the same and the buff to duration is unwarranted it already lasts a good enough while.

**Comment by VictorVow** [comment]
I'd rather overcompensate and then later have to nerf it rather than constant small buffs to try and make it usable. I hope this is enough of a buff to get people to try the item again but I still am concerned it's not going to be.

**Comment by Moccha-Bee** [comment]
> I'd rather overcompensate and then later have to nerf it rather than constant small buffs to try and make it usable. I hope this is enough of a buff to get people to try the item again but I still am concerned it's not going to be.

people don't use the peppery spray because it easy to avoid, any goggles will do the trick and you need to be close to the target to hit him, i think realistically speaking and balance wise the pepperspray is good as it is

**Comment by VictorVow** [comment]
I can only increase the spray speed slightly otherwise the spray sprite is invisible if you aim at one tile adjacent. So the range has been buffed as well which deals with the "you need to be close to the target to hit him" limitation slightly. Pepperspray is not good as is balance-wise, which is why it's never used.

**Comment by PowerfulBacon** [comment]
This is a pretty significant buff to an already decent tool and is way too over the top with the new effect values

**Comment by Isy232** [comment]
Dont buff the knockdown and confusion but buffing speed and range is okay I'd say.

**Comment by zeskorion** [comment]
i've noticed spray paint and pepper spray protection is a tad fucky. that oughtta be fixed first, and then we can see about this.  i'll get around to that right now actually

**Comment by zeskorion** [comment]
update: apparently spraycans use flash protection, and pepper spray has a special variable on every mask. jesus fucking christ, gimme a few minutes

**Comment by utilbird** [comment]
pepper spray is really good already, this isn't really needed, no one using it doesn't make it a bad tool necessarily. Sec officers need to learn that there is more to life than unga bunga disabler and baton

**Comment by PowerfulBacon** [comment]
Closing, this is way too extreme a buff. Pepperspray is already pretty good, the only downside is being hard to tell when it is useful and the fact that it is easy to spray yourself.

**Pull request closed without merging**
