### PR TITLE
KiloStation Rework VERSION 3.

### PR DESCRIPTION
**Pull request by ClownMoff**
## About The Pull Request

This is a v.3  of this PR: https://github.com/BeeStation/BeeStation-Hornet/pull/10080. I'm not dealing with all the merging problems result of freezing and the prior errors that existed beforehand.

KiloStation Medbay rework. All areas have been updated to have a better use of the space. OG Kilo just have rooms weirdly shapend and oddly placed for the sake of it. This rework aims to get a cleaner, more satisfying layout while still keeping Kilos theme of being small and cramped
## Why It's Good For The Game

Because medbay people deserve better

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: Varo
tweak: Kilostation: reworks the lobby, changes the front desk position to where cloning was, moves genetics to the big monkey room, moves cloning where genetic was, adds a surgery room, reworks the CMO, storage and chemistry room, removes a big part of virology and places it all below chemistry, tweaks some maintenance areas 
/:cl:

### CODE REVIEW

**Comment by MarkusLarsson421** [comment]
Screenshots please.

**Comment by JixS4v** [comment]
> Screenshots please.

we have a bot for map differences

**Comment by MarkusLarsson421** [comment]
Door.
 

Corner bed.
 

A tad lacking in medkits spawns. How many other maps have?
 

Weird potted plant and couch spot.
 

It's a bit of a tight area for chemistry and a very empty wall. I'd leave the area that the table is empty and move the tables against the wall. Sometimes you want some floor space.
 

Also, there is no patient area outside surgery for those SSD folks or those still recovering.

There are only two medical lockers that feel a tad little? Even for low-pop.

Genetics is now 100% part of Medbay and should be medbay themed and not science themed.

This main room feels empty as fuck and still feels like an intersection similar to Kilo. I'd move it down a little bit to keep a straight path between lobby-storage and shift the genetics-virology path further to the east. Thus ensuring that the bottom left is entirely part of Medbay treatment and not a hallway. Possibly separated with railings for style points.
 

The surgery viewing area feels super cramped and clunky. Move the vending machines. Else, where or give Doctors a dedicated surgery room door.
 

This feels EXTREMELY empty and plain.
 

This south-western wall feels empty. Give it a few tables or such, maybe even a surgery table for organ harvesting.


The wall behind the file cabinet at the reception and morgue just screams, "Make me into a door!!", I think it should be a door directly to the morgue from the reception. Or swap the indent from the morgue to be on the left side instead of being on the right.

**Comment by ClownMoff** [comment]
I messed up this one too :p

**Pull request closed without merging**
