### PR TITLE
fixes food not being seen in the microwave

### PR DESCRIPTION
**Pull request by ktlwjec0**
## About The Pull Request

File path was changed in #11467 , which caused this to no longer work. This PR changes it back, ~~and removes the microwave dmi as it is just a duplicate of the kitchenmachines dmi.~~ by moving the microwave icons from kitchenmachines to the microwave dmi.

## Why It's Good For The Game

Bug fix.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image
image
image

</details>

:cl: ktlwjec
fix: You can see food placed in microwaves again.
/:cl:

### CODE REVIEW

**Comment by Tsar-Salat** [comment]
Splitting microwaves into their own file was intentional, and I'd prefer if it was sustained.

A machine with 11 icon states to itself should not be in a generic file, its the same issue as having a food.dmi file; terrible to organize and it will merge conflict when it doesnt need to.

In this situation specifically, had microwave.dmi already been a separate file before newfood:ovens and the seeing food in microwave pr, there would be no merge conflict to fix.

**Comment by ktlwjec0** [comment]
> Splitting microwaves into their own file was intentional, and I'd prefer if it was sustained.


Sure, I can move it back. Will do that later today

**Comment by PowerfulBacon** [comment]
That egg looks like it's in front of the microwave

**Comment by ktlwjec0** [comment]
> That egg looks like it's in front of the microwave

I can't tell if you're being serious but just in case, that is because the door is open with the egg out of it. Just showing it works as intended.

**Comment by PowerfulBacon** [comment]
My Internet went down after I realised and couldn't edit the comment

**Review by PowerfulBacon — APPROVED** [review]

**Pull request merged**
